{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda em armadura de poder.}
{102}{}{Você vê alguém vestindo armadura de energia de um design incomum. Há uma insígnia no peitoral que você não conhece.}
{103}{}{Nada a assinalar.}
{104}{}{Nada de errado comigo, que tal você?}
{105}{}{Não deveria estar no seu posto, soldado? Não é bom para passear aqui.}
{106}{}{Você está fora do uniforme.}
{107}{}{É melhor informar o Sargento e se adequar.}
{108}{}{Você está tendo uma grande chance de estar fora de uniforme. Melhor você informar ao fornecimento.}
{109}{}{Quem diabos são vocês... Alerta! Intrusos!}
{110}{}{Temos sido infiltrados! Alerta!}
{111}{}{Vários intrusos! Soar o alarme!}
{112}{}{Alerta de segurança! Selo de base!}
{113}{}{Proteja todas as estações! Estamos em alerta!}
{114}{}{Alerta de intrusão! Vá código vermelho!}
{115}{}{Nós vamos colocá-lo abaixo!}
{116}{}{O Enclave vai dominar o mundo!}
{117}{}{Você morre para que o Enclave sobreviva!}
{200}{}{...imbecil...}
{201}{}{...sim, é MELHOR você ir embora...}
{202}{}{... o que um caipira marrom...}
{203}{}{...sim, senhor! fuckin' senhor!...}
{300}{}{Aguarde lá. O que você acha que está fazendo com essa aeronave? Não há vôos programados por vários dias.}
{301}{}{Nrg?}
{302}{}{Eu estou ciente disso.}
{303}{}{Sinto muito. Eu só estava procurando. Eu vou estar indo agora.}
{304}{}{Houve uma mudança de planos. Eu estou tomando esta aeronave.}
{310}{}{O que? Oh, eu vejo. Olhe, mas não toque. Tudo bem? Toque novamente e você morre.}
{311}{}{(Sorriso, em seguida, atacar.)}
{312}{}{(Ir embora.)}
{315}{}{Oh merda, parece que nos conseguimos um intruso. Código vermelho! Eu repito, código vermelho!}
{316}{}{Isso soa como uma boa ideia. Toque a aeronave novamente e eu vou colocar uma bala em sua cabeça.}
{320}{}{Certo. E, portanto, você é ...}
{321}{}{Prestes a sair. Desculpe incomodá-lo.}
{322}{}{Para entregar uma mensagem importante para a base principal.}
{323}{}{Sério? E o que esta mensagem diz.}
{324}{}{É super secreto. Eu não posso contar a você.}
{325}{}{Eu vou lhe dizer, mas é absolutamente essencial que você não divulgue essas informações a mais ninguém, por medo de um
  pânico em massa. Você vê, chamou a atenção para mim que uma das recentes expedições de escravos está infectada com algo desconhecido, e
  altamente mortal, algum vírus. Eu * devo * chegar à base imediatamente, ou todas as nossas vidas podem ser perdidas. Agora pare de desperdiçar meu tempo,
  pois não há um momento de sobra.}
{326}{}{Sim, eu acredito em você. Parece que temos de nós mesmos um intruso...}
{327}{}{Droga! Ah, seja o que for. Nunca me dizem nada por aqui. Bem. Esteja a caminho.}
{328}{}{Woah, isso parece ruim. É melhor você se mandar, então, não quero essa merda em minhas mãos. Ah, e não se preocupe, não vou contar a ninguém.}
{329}{}{[FEITO]}
