{100}{}{Você vê alguém na armadura de energia. }
{101}{}{Você vê o Comandante da base de Navarro.}
{102}{}{Você vê alguém vestindo armadura de energia de um design incomum. Há uma insígnia no peitoral que você não conhece.}
{103}{}{Quem diabos são vocês... Alerta! Intrusos na base!}
{104}{}{Não tenho tempo para conversar com os grunhidos. Você está dispensado. }
{105}{}{Tempo para morrer.}
{106}{}{Tudo bem.}
{107}{}{Eu disse que não tenho tempo para você. Deixe este escritório e não volte aqui, a menos que eu envie para você. Dispensado!}
{108}{}{A desobediência a uma ordem direta de um superior hierárquico é traição. Eu não tenho tempo para corte marcial de você, então eu vou lidar com isso sozinho. Guardas! Matem esse idiota!}
{109}{}{Tudo bem.}
{110}{}{Que se dane!}
{111}{}{O Fob está no armário lá. Peça ao funcionário que me contacte quando estiver seguro. Dispensado!}
{112}{}{Sim, senhor!}
{113}{}{Faça isso rápido soldado, eu não tenho o dia todo para isso.}
{114}{}{Sim, senhor!}
{115}{}{Deixe o meu armário sozinho ou vou causar uma dor séria.}
{116}{}{Sim, senhor!}
{117}{}{Esta base está em alerta e não reconheço você. Mostre-me seus papéis, soldado.}
{118}{}{Que documentos?}
{119}{}{Você me estoura!}
{120}{}{Acho que não tenho eles comigo...}
{121}{}{Documentos? Eu tenho seus documentos bem aqui!}
{122}{}{Resposta errada, verme. Você deve transportar os seus documentos com você em todos os momentos. Você deve saber disso!}
{123}{}{Foda-se você.}
{124}{}{Deixe o meu armário sozinho ou vou causar uma dor séria.}
{125}{}{Tempo para morrer.}
