{100}{}{Você vê um homem magro, gorduroso.}
{150}{}{Você vê Flick, dando a sua virilha um raspador minucioso.}
{151}{}{Você vê um sujeito impuro com uma contração facial desagradável.}
{200}{}{Saia do heeya, você burro.}
{201}{}{Ei almôndega! Sim, você. Fuja heeya.}
{202}{}{Você é idiota ou estupido?}
{203}{}{Whatchur problema, hein?}
{204}{}{Ao inferno fora de heeya.}
{220}{}{Hey der, eu sou o Flick. Que merda você quer, hein?}
{221}{}{O que agora? Você ficou no meu tempo, heeya.}
{222}{}{Qual é a desse maluco, Flick?}
{223}{}{O que diabos você faz aqui?}
{224}{}{Estou à procura de um Vault - oh, sim, e um comerciante chamado Vic também. Sabe onde eles podem estar?}
{225}{}{Gostaria de trocar com você.}
{240}{}{Que tal fazê-lo para você, amigo?}
{241}{}{Na verdade, gostaria de dar uma olhada em seus produtos se puder.}
{242}{}{Na verdade, eu gostaria de lhe fazer uma pergunta.}
{243}{}{Isso deu certo. Vejo você por aí Flick.}
{260}{}{Eu sou um fodido provedor, pensou Whaddya? Eu sou como um bom homem samurai-irã.}
{261}{}{Dizer o que?}
{262}{}{Yeah, uh, bem...deixe-me perguntar-lhe algo mais.}
{263}{}{Uh, oh. ESTÁ BEM. Adeus, Flick.}
{280}{}{Fornecendo-lhes pequenos paisanos.}
{281}{}{Vocês fornecem pequenos pianos?}
{290}{}{Pai-san-o, você sabe, as crianças. Meus filhos.}
{291}{}{Seus filhos?}
{292}{}{Bem, eu não estou realmente interessado em aulas de música para crianças. Deixe-me perguntar-lhe sobre outra coisa.}
{300}{}{Sim, bem, eles trabalham para mim. Eles me trazem coisas. Pequenas coisas. Você sabe.}
{301}{}{Uh, não.}
{302}{}{Ah, OK. Deixe-me perguntar-lhe algo mais.}
{303}{}{Ah, eu vejo. Bem, eu não quero atrapalhar seu estilo. Adeus.}
{315}{}{They bring me stuff what they find. Little, little things. Stuff no one ain't usin' no more. In return, I takes care of 'em.}
{316}{}{Soa como um bom arranjo.}
{325}{}{(Flick dá de ombros) eu consigo OK.}
{326}{}{Deixe-me perguntar sobre outra coisa, então.}
{327}{}{Eles devem ter trazido a você algumas verdadeiras pechinchas. Vamos ver o que você tem.}
{328}{}{Apenas checando. Bem, adeus Flick.}
{340}{}{Do que você está falando? Você acha que eu sou uma maldito pirata estúpido? Algum estranho filio di puttana? Você acha que eu sou um palhaço? Estou aqui para divertir você, é isso?}
{341}{}{Uh, não. Desculpe, eu estava apenas curioso. Deixe-me perguntar-lhe sobre outra coisa.}
{342}{}{Sim, é verdade, merda. E nada vai me divertir mais do que a sua morte.}
{343}{}{Bem, se você vai ficar irritado com isso, eu vou embora.}
{360}{}{Vault, hein? Talvez mamãe saiba sobre isso, porque eu não. Mas aquele cara o Vic - ele eu sei. Metzger tem aquela porca pistola.}
{361}{}{Vic? Não é ele com você? Você é uma biota. Mas mamãe, ela eu sei.}
{362}{}{Quem é o Metzger?}
{363}{}{Quem é a mãe?}
{364}{}{Obrigado. Deixe-me perguntar-lhe algo mais.}
{365}{}{Obrigado, isso é tudo que eu preciso saber. Adeus.}
{380}{}{Mamãe dirige um lugar de comida no lado leste da cidade. Justo após o cemitério. Bom lugar, ela faz um bom macarrão, Mama Mia.}
{381}{}{Obrigado, e o Metzger que tem Vic?}
{382}{}{Obrigado. Deixe-me perguntar-lhe algo mais.}
{383}{}{Obrigado, isso é tudo que eu preciso saber. Adeus.}
{400}{}{Está certo. Metzger, esse estronzo, ele está morto. Não sei o que aconteceu com Vic.}
{401}{}{Esse Metzger, ele é um verdadeiro rompiballe, aquele. Executa o Slaver's Guild. Lado leste da cidade, ao norte de Mamãe. De qualquer forma, ele prendeu Vic, eu sei.}
{402}{}{Obrigado, agora que sobre a Mamãe?}
{403}{}{Obrigado. Deixe-me perguntar-lhe algo mais.}
{404}{}{Obrigado, isso é tudo que eu preciso saber. Adeus.}
