{100}{}{You see a chem reliant.}
{101}{}{Você vê Petey.}
{150}{}{This here is a poor chem reliant.}
{151}{}{Petey aqui parece que ele poderia usar alguma ajuda.}
{152}{}{[falar]}
{155}{}{[tosse, tosse] Qualquer mudança de reposição para Petey?}
{156}{}{Certo, aqui vamos nós.}
{157}{}{Não, fique longe de mim.}
{158}{}{Peewee?}
{159}{}{Você está pior do que eu. [tosse] Obrigado de qualquer forma.}
{160}{}{Desculpe, tchau.}
{161}{}{Duh, você é bem-vindo, uh-huh, sim.}
{162}{}{Talvez da próxima vez. Obrigado de qualquer forma. [tosse]}
{163}{}{[feito]}
{164}{}{Muito obrigado. [tosse] tão, tão, Tão muito.}
{165}{}{Você é bem-vindo.}
{166}{}{Sim, sim.}
{167}{}{Senhor, [tosse] você pode ajudar um pobre homem baixo em sua sorte?}
{168}{}{Aqui está $5.}
{169}{}{Hoje não.}
{170}{}{Arrume um emprego.}
{171}{}{Gentil senhora, por favor, ajude [tosse], pobre, faminto que é [tosse] demasiado doentes para trabalhar.}
{172}{}{Coitadinho de você, aqui tem $5.}
{173}{}{Eu faço questão de não dar dinheiro para mendigos.}
{174}{}{Não.}
{200}{}{E aí cara; me dê algum dinheiro?}
{201}{}{Poupe alguma mudança, senhor amável?}
{202}{}{Ei, você pode me ajudar com alguns dólares?}
{203}{}{Do you think you can help me out with a coupla dollars?}
{204}{}{Você acha que você poderia me emprestar algum dinheiro?}
{205}{}{De reposição de alguma mudança, gentil senhora?}
{206}{}{Ei, senhora; não poupar algum dinheiro?}
{220}{}{Por favor, ajude-me, senhor.}
{221}{}{Ahhh, dói.}
{222}{}{Eu preciso de ajuda. Dói ruim.}
{223}{}{Senhora, pode me ajuda?}
{225}{}{Aprecio muito isso.}
{226}{}{Hey, o que você pensa que está fazendo?}
{230}{}{Uma sensação tão boa.}
{231}{}{Uhhh...}
{232}{}{[risadinha]}
{233}{}{Ei...}
{300}{}{Ahhh, someone fucking killed Tubby?}
{301}{}{O que diabos aconteceu com Tubby?}
{302}{}{Oh shit, Tubby's...}
{303}{}{Ahhh...}
{304}{}{Na verdade, não gostava desse idiota.}
{305}{}{Flick's dead? Crap.}
{306}{}{O que aconteceu para Flick?}
{307}{}{Flick...}
{310}{}{Hey Tubby, I, Uhhh, need some help here.}
{311}{}{EI TUBBY!}
{312}{}{Olá.}
{313}{}{HEY!}
{314}{}{Hey Flick, I, Uhhh, need some help here.}
{315}{}{HEY FLICK!}
{320}{}{Ei, Tubby, você pode me ligar? Eu tenho dinheiro.}
{321}{}{Ummm, Tubby, eu tenho um pouco de dinheiro.}
{322}{}{Uhhh...}
{323}{}{Eu preciso de uma correção cara.}
{324}{}{Ei, Flick; você pode me ligar? Eu tenho dinheiro.}
{325}{}{Ummm, Flick, eu tenho um pouco de dinheiro.}
{330}{}{Uhhh... Obrigado mais uma vez, Tubby.}
{331}{}{Você é um amigo, Tubby.}
{332}{}{Eu prometo. Eu vou chutar o amanhã.}
{333}{}{Você é um amigo.}
{334}{}{Uhhh ... Obrigado novamente, Flick.}
{335}{}{Você é um amigo, Flick.}
