{100}{}{Você vê um homem vestindo armadura de couro.}
{101}{}{Você vê Kaga.}
{102}{}{Ele está vestindo uma armadura de couro e tem um irritante hábito de falar sobre si mesmo em terceira pessoa.}
{103}{}{Esta será a última vez que Kaga te encontra.}
{104}{}{After Kaga kill yous, he will burn Arroyo to the ground.}
{105}{}{Sinta a ira de Kaga!}
{106}{}{Eu sou o grande Kaga!}
{107}{}{Kaga é para ser temido por todos.}
{108}{}{Kaga terá sua cabeça para um troféu.}
{109}{}{Rendição e sua morte será rápida.}
{110}{}{Kaga estará de volta!}
{111}{}{Você não pode matar o grande Kaga!}
{112}{}{Você tem sorte Kaga tem negócios em outro lugar.}
{113}{}{Kaga irá encontrá-lo novamente.}
