{100}{}{Você vê um homem vestindo armadura de metal.}
{101}{}{Você vê Kaga.}
{102}{}{Sim, Kaga o não-tão-grande. Ele tem armadura de metal e quer matá-lo.}
{103}{}{Você novamente!}
{104}{}{Fico cansado de nossas reuniões constantes.}
{105}{}{Escolhido - hmph!}
{106}{}{Vamos acabar com isso.}
{107}{}{Você vai se arrepender você já ouviu falar o nome de Kaga!}
{108}{}{Minhas habilidades aumentaram desde o nosso último encontro.}
{109}{}{Isso está virando um mau hábito.}
{110}{}{Kaga precisa treinar um pouco mais.}
{111}{}{Kaga vai voltar.}
