{100}{}{Você vê um homem vestindo o mínimo de roupa.}
{101}{}{Você vê Kaga.}
{103}{}{Ele está vestindo calças e parece que ele veio de uma tribo.}
{104}{}{Eu deveria ter sido o Escolhido!}
{105}{}{Como se atreve, Arroyo me expulsou da tribo.}
{106}{}{Eu terei minha vingança sobre você!}
{107}{}{Kaga vai mandar você para a próxima vida.}
{108}{}{Nós vamos nos encontrar novamente!}
{109}{}{Nunca fui espancado antes!}
{110}{}{Vou me dedicar para a sua destruição.}
