{100}{}{Você vê um homem vestindo MKII armadura de energia. Ele não parece amigável.}
{101}{}{Você vê Kaga em MKII armadura de energia.}
{102}{}{Um grande pedaço de metal com armas e armas de fogo.}
{103}{}{Eu cansei de perseguição. Vamos acabar com isto.}
{104}{}{Esta é a última vez que você vai encontrar Kaga.}
{105}{}{Vocês não são páreo para Kaga.}
{106}{}{Estou ansioso para o envio de você em sua próxima vida.}
{107}{}{Você tem sido um digno inimigo.}
{108}{}{Esta parte dos resíduos não precisa de um bem feitor como você.}
{109}{}{Depois de te matar, eu serei a pessoa mais temida nesta parte dos resíduos.}
{110}{}{Estou ansioso para ir para casa para Arroyo - para queimá-la.}
{111}{}{Kaga vai ser famoso por matar você.}
