{100}{}{Você vê um homem vestindo armadura de combate.}
{101}{}{Você vê Kaga na armadura de combate.}
{102}{}{Ele está vestindo armaduras de combate e parece ter algumas armas decentes.}
{103}{}{Neste momento eu estou preparado para você.}
{104}{}{O Escolhido nunca irá retornar para Arroyo!}
{105}{}{Kaga vai esmagar você!}
{106}{}{Kaga não teme ninguém!}
{107}{}{Mantenha-se imóvel, então Kaga pode obter um bom tiro.}
{108}{}{Nós vamos nos encontrar novamente!}
{109}{}{Este não é o último que você vai ver de Kaga.}
{110}{}{Kaga, definitivamente, precisa de mais treinamento.}
