{100}{}{Você vê um nômade.}
{101}{}{Ele parece ser um nômade chefe.}
{102}{}{Por seu vestido e a maneira como ele se desenvolve, ele deve ser um líder de algum tipo.}
{103}{}{Ah, um viajante. Seja bem-vindo a minha humilde tenda. Tire a máscara do infinito calor da terra.}
{104}{}{Obrigado; Aceito graciosamente a sua oferta de sombra.}
{105}{}{Terei que recusar sua oferta. Eu estou apenas de passagem.}
{106}{}{Ooga.}
{107}{}{Seja bem vindo, então. Nós ficamos longe das terras "civilizadas". Precisamos de
  Certos itens. Talvez possamos negociar?}
{108}{}{O que você tem para negociar?}
{109}{}{Eu não tenho nada para negociar. Desculpe.}
{110}{}{Talvez outra vez, então? Que suas viagens estejam livres de perigo.}
{111}{}{Obrigado. Tchau.}
{112}{}{Que pena. Então descanse e seja bem vindo no meu acampamento.}
{113}{}{Obrigado. }
{114}{}{Minha oferta de sombra chegou muito tarde para você. O sol deve ter fervido as palavras do seu
  cérebro. Eu devo ser gentil com aqueles menos afortunados do que eu. Fique o tempo que você gosta no meu acampamento, maldito.}
{115}{}{Adeus.}
{116}{}{Infiel!}
{117}{}{Por que você nos atacar?}
{118}{}{Eu vou defender a tribo com a minha vida!}
{119}{}{Como você se atreve a violar a nossa hospitalidade.}
{120}{}{Sai!}
{121}{}{Deixe-nos.}
{122}{}{Somos uma tribo pacífica.}
{200}{}{Ah, um viajante. Desculpe-me por não termos uma tenda para que você possa se abrigar da sombra desta terra que faz um calor infernal. Descanse um momento para que possamos conversar depois.}
{201}{}{Obrigado; Aceito generosamente sua oferta.}
{202}{}{Que pena. Então descanse um pouco; você é bem vindo entre nós.}
{203}{}{Espero que você encontre o que está procurando. Precisa de mais alguma coisa?}
{204}{}{Hoje não. Tenho que ir.}
