{100}{}{Você vê um viajante.}
{101}{}{Hail! Companheiro de viagem.}
{102}{}{Eu estou precisando de indicações. Você pode me ajudar?}
{103}{}{Onde você está indo?}
{104}{}{O que fazer?}
{105}{}{Ug.}
{106}{}{Bem ... eu não sei. Eu sou muito novo nesta área e só fui nas seguintes áreas.}
{107}{}{Novo Reno}
{108}{}{Vault City}
{109}{}{Redding}
{110}{}{The Den}
{111}{}{San Francisco}
{112}{}{New California Republic}
{113}{}{Uma mina abandonada.}
{114}{}{Não, eu estive lá. Obrigado de qualquer forma.}
{115}{}{Novo Reno -- agora que é um ótimo lugar para ir. Sexo, drogas e jogos de azar. O que mais se pode pedir?
Aqui, deixe-me mostrar-lhe onde ele está.}
{116}{}{Obrigado.}
{117}{}{Vault City-agora que é uma cidade de idiotas. Crescer um extra de dedo e eles tratam você como algum tipo
de freak. Nunca estive dentro, mas eu sei onde ele está.}
{118}{}{Obrigado.}
{119}{}{Redding...eu não sei muito sobre ele, mais do que isso, é uma antiga cidade mineira. Ele está situado ao norte,
direito smack dab no meio de alguns dos pior montanhas que você já viu.}
{120}{}{Obrigado.}
{121}{}{Eu iria ficar longe da Den, se eu fosse você. É um ímã para lowlifes da área. Eu vou te mostrar
onde ele está, mas eu não recomendo que você vá lá.}
{122}{}{Obrigado.}
{123}{}{San Francisco. Hum...tudo o que posso dizer é que as pessoas de lá são...estranhas. Ela está situada na costa.}
{124}{}{Obrigado.}
{125}{}{A Califórnia, Nova República...agora há um lugar agradável. Eu gostaria de estabelecer e viver lá
algum dia. Limpo, boa gente, e muito bem conservado. Ele está localizado aqui no seu mapa.}
{126}{}{Obrigado.}
{127}{}{Sim, um tempo atrás, encontrei um campo de mineração abandonado. Pensei que descansaria um dia ou dois,
  Mas então os lobos começaram a aparecer e achei melhor se eu fosse embora. Uma vergonha também; parece que
  Os mineiros deixaram com pressa. Eles deixaram muitas coisas para trás. Não estou planejando voltar, então acho que está
  Tudo bem, se eu lhe mostrar onde está.}
{128}{}{Obrigado.}
{129}{}{Oh...isso realmente não importa. Eu só decidi viajar um dia e bem, aqui estou eu.}
{130}{}{Talvez você possa me ajudar. Eu preciso de algumas orientações.}
{131}{}{O que fazer?}
{132}{}{Bom falar com você.}
{133}{}{Eu faço trabalhos estranhos aqui e aí para me ajudar. Mas principalmente eu apenas viajo.}
{134}{}{Talvez você possa me ajudar. Eu preciso de algumas orientações.}
{135}{}{Para onde vai?}
{136}{}{Bom falar com você.}
{137}{}{Eu realmente deveria ir agora. Foi legal conversar com você.}
{138}{}{Talvez vamos nos encontrar novamente.}
{139}{}{Eu quero chegar a próxima cidade ao cair da noite. É melhor eu ir.}
{140}{}{I'd be going.}
{141}{}{Uma emboscada!}
{142}{}{Não pode confiar em alguém nos dias de hoje.}
{143}{}{Você quebrou o código do viajante.}
{144}{}{Hora de ir.}
{145}{}{Eu ultrapassei minha saudação.}
{146}{}{Eu devo partir.}
{150}{}{Obrigado. Preciso de direções para outros lugares.}
