{100}{}{Você vê um homem Shi curto e rotundo.}
{101}{}{Você vê o Dr. Wong Yi Tze.}
{102}{}{Você vê um homem Shi curto e rotundo.}
{103}{}{Posso ajudar em alguma coisa?}
{104}{}{Daghi nu?}
{105}{}{Você quem?}
{106}{}{Eu ouvi que você tem o baço de outra pessoa.}
{107}{}{Quem é você?}
{108}{}{O que você faz aqui?}
{109}{}{Não, obrigado. Isso é tudo.}
{110}{}{Devo confessar, não falo sua língua. Talvez você deva falar com Ken Lee, ele entende muitas línguas diferentes.}
{111}{}{Aagh!}
{112}{}{Eu sou o Dr. Wong. Eu sou o principal cientista desta instalação.}
{113}{}{Mais perguntas, por favor.}
{114}{}{Obrigado. Tchau.}
{115}{}{Eu supervisiono os experimentos científicos que criamos e corremos aqui. Eu também estou no comando da rede de informática.}
{116}{}{O que você está planejando?}
{117}{}{Como se faz para obter acesso à rede de computadores?}
{118}{}{Tenho outras perguntas.}
{119}{}{Eu vejo. Tchau.}
{120}{}{Ah, mas se eu lhe contar os nossos planos, todos saberão. Receio que eles sejam planos secretos, por enquanto.}
{121}{}{Bem, bem. Tenho outras perguntas.}
{122}{}{Obrigado. Tchau.}
{123}{}{Que tal se eu pegar uma arma no seu nariz e forçá-lo a me dizer?}
{124}{}{Por que, alguém aprende como invadir isso, ou como fazer amizade com um dos meus subordinados. Eu estou brincando, é claro, com uma invasão - se você fizesse isso, eu enviaria alguém depois de você para matá-lo. [Ele sorri para mostrar que isso não significa ofensa.]}
{125}{}{Você realmente iria me matar?}
{126}{}{Então, você não teria nenhuma objeção real para eu entrar no computador?}
{127}{}{Eu tenho algumas outras perguntas.}
{128}{}{Certeza de que você teria. Tchau.}
{129}{}{Então eu teria de considerá-lo como uma ameaça e avisá-lo de que tal curso de ação pode ser prejudicial para a sua saúde.}
{130}{}{Vamos dar-lhe uma tentativa.}
{131}{}{Eu estava apenas brincando. Tenho outras perguntas.}
{132}{}{[Sorri] Temos que proteger a nossa honra, estranho.}
{133}{}{Err, certo. Então, você teria alguma objeção real para eu entrar no computador?}
{134}{}{Certo. Tenho outras questões.}
{135}{}{Aposto. Tchau.}
{136}{}{Se você pode convencer meus subordinados a fazê-lo. Mas eu certamente não.}
{137}{}{E se eu coloquei uma arma debaixo do nariz?}
{138}{}{Grande. Bem, eu tenho mais perguntas.}
{139}{}{Hmm. Eu vejo. Bem, até mais. }
{140}{}{Ahh, sim! De facto. Vou prepará-lo com fava, feijão e um bom Chianti.}
{141}{}{Você ainda tem ele? Boa. Chip necessidades de volta.}
{142}{}{Isso é um baço humano, seu bastardo doente!}
{143}{}{Você sabe que é suposto servir fígado com esse vinho em vez de baço, certo?}
{144}{}{Isso é um baço humano, você sabe.}
{145}{}{Quem é esse Chip? É meu baço agora, e estou com ele para o jantar.}
{146}{}{O Chip é o proprietário original do baço. Ele estava bêbado e vendeu-o para Lao Chou.}
{147}{}{Ele precisa disso para sobreviver, você sabe. Ele veio de dentro de seu corpo.}
{148}{}{Então, é melhor eu te matar por isso.}
{149}{}{Um acordo é um acordo. Ele não pode ter isso. Desculpe, mas fizemos uma pechincha e só porque Chip se arrepende agora, não significa que ele possa voltar ao acordo.}
{150}{}{[MAIS]}
{151}{}{É um baço humano? Lao Chou não me disse isso!}
{152}{}{No entanto, por causa da descortesia do mensageiro, acredito que vou manter todas as partes no negócio. Em vez disso, vou experimentar.}
{153}{}{Diga ao seu amigo que venha por ele no próximo dia, e com prazer vou devolvê-lo. Eu só espero que você possa encontrar uma maneira de recolocar em seu corpo a tempo.}
{154}{}{Muito bem.}
{155}{}{Ha ha! Sim, eu também vi esse filme antigo. Espere ... o que você está dizendo? Você está dizendo que ...?}
{156}{}{Sim, é um baço humano.}
{157}{}{Na verdade, eu me oponho a isso. Você não se mostrou ser de bom caráter. Na verdade, não sei por que estou falando com você. Bom dia.}
{158}{}{[FEITO]}
{159}{}{Aiee! Guardas! O intruso lao wai está aqui!}
{160}{}{Você tem certos esquemas para dar para mim?}
{161}{}{Ken Lee me disse para dar isso a você.}
{162}{}{Sim. Agora, o que eu recebo?}
{163}{}{Não, ainda não.}
{164}{}{Fale com Ken Lee, e ele deve discutir o que acontece no seu futuro. Obrigado. Devemos verificar alguns dos nossos dados de teste com estes. Bom dia.}
{165}{}{Na verdade, eu tinha outras perguntas.}
{166}{}{Até mais.}
