{100}{}{Você vê um homem que se parece muito com um lojista.}
{101}{}{Você vê Lao Chou, o lojista.}
{102}{}{Você vê um homem em roupas funcionais e confortáveis.}
{103}{}{Saudações! Bem vindo à minha loja, Flying Dragon 8.}
{104}{}{O que posso fazer por você?}
{105}{}{Pastel de Flango!}
{106}{}{Coisas!}
{107}{}{Quem é você?}
{108}{}{Estou procurando por algum equipamento.}
{109}{}{Estou procurando por alguma informação.}
{110}{}{Adeus.}
{111}{}{Você quer comprar algo?}
{112}{}{:: acene com a cabeça ::}
{113}{}{::balançar a cabeça::}
{114}{}{Isso é o que temos, então.}
{115}{}{[FEITO]}
{116}{}{Bem, temo que é tudo que posso fazer por você. Tenha um bom dia. }
{117}{}{[FEITO]}
{118}{}{Eu sou Lao Chou. Eu dirijo este estabelecimento, Flying Dragon 8, uma loja geral. Eu sou conhecido por trocar ... informação.}
{119}{}{Que tipo de informação?}
{120}{}{Entendo. Eu gostaria de algum equipamento.}
{121}{}{Pouco acontece nesta cidade que eu não conheço. Claro, você deve saber a pergunta certa a se fazer, sim? O que você precisa saber?}
{122}{}{Estou procurando algumas atualizações no meu equipamento.}
{123}{}{Onde posso encontrar planos de vertibird?}
{124}{}{Eu preciso encontrar combustível para o PMV Valdez.}
{125}{}{Eu entendo que preciso de um FOB para acessar o computador do Valdez.}
{126}{}{Eu preciso de algumas peças de computador para o PMV Valdez.}
{127}{}{Estou procurando por um baço.}
{128}{}{Eu ouvi que algumas máquinas voadoras trouxeram uma carga de aldeões por este caminho.}
{129}{}{Nada. Tchau.}
{130}{}{Talk to Crockett, over in the Hubologist camp. He is their head scientist.}
{131}{}{Obrigado. Eu preciso de mais informação.}
{132}{}{Obrigado. Tchau.}
{133}{}{Olhe para o norte, em Navarro. Há uma base escondida perto do posto de gasolina.}
{134}{}{Obrigado. Eu preciso de mais informação.}
{135}{}{Obrigado. Tchau.}
{136}{}{Você já tentou procurar nos antigos Refúgios? Eu ouvi dizer que eles são uma riqueza de informações e tecnologia dos antigos.}
{137}{}{Obrigado. Eu preciso de mais informação.}
{138}{}{Obrigado. Tchau.}
{139}{}{Um baço? Ha ha! Sim, Chip do Valdez perdeu o baço em um jogo de cartas no outro dia. Eu vendi para o Dr. Wong. Ele ficou fascinado por isso.}
{140}{}{Dr. Wong? Onde posso encontrá-lo?}
{141}{}{Como você perde um baço?}
{142}{}{Obrigado. Eu tenho mais perguntas.}
{143}{}{Ah, então Tchau.}
{144}{}{O Dr. Wong é o cientista chefe do Palácio de Aço. Procure-o lá.}
{145}{}{Como você perde um baço, aliás?}
{146}{}{Obrigado. Eu preciso de mais informação.}
{147}{}{Obrigado. Tchau.}
{148}{}{Ele estava bêbado. Muito, muito bêbado. Ele estava obcecado com o baço a noite toda. E então ele o aposta.}
{149}{}{Então você pegou o BAÇO dele?}
{150}{}{Eu vejo. Bem, eu tenho mais perguntas.}
{151}{}{Sim. Foi uma dívida. Ele é um homem honrado.}
{152}{}{Entendo. Eu preciso de mais informações.}
{153}{}{Você é um bastardo rude e doente, não é?}
{154}{}{Direito. Tchau.}
{155}{}{Você é uma pessoa desonrosa. Eu não quero você na minha loja. Volte outra hora.}
{156}{}{Seja o que for.}
{157}{}{Não. Eles vieram do norte e voaram sobre nós, indo para o mar.}
{158}{}{Além do horizonte? Como diabos eu chego lá?}
{159}{}{Sim, eles fizeram. Diga-me onde eles estão antes de eu abrir você como uma lata de sardinha.}
{160}{}{Bem... nenhum dos nossos barcos é capaz de percorrer essa distância. A menos que...}
{161}{}{A menos que...?}
{162}{}{Obrigado pela "ajuda". Eu vou procurar um conselho de verdade.}
{163}{}{... a menos que você consiga colocar o velho petroleiro nas docas funcionando. É um navio antigo, mas provavelmente ainda funciona com um pouquinho de trabalho em cima dele. Pergunte aos punks para mais informações.}
{164}{}{Obrigado. Eu preciso de mais informação.}
{165}{}{Obrigado. Tchau.}
{166}{}{Dizem que os Hubologistas conseguiram uma grande quantidade de combustível recentemente. Negocie com eles.}
{167}{}{Obrigado. Eu preciso de mais informação.}
{168}{}{Obrigado. Tchau.}
{169}{}{Você pode tentar alguns dos cientistas Shi no Palácio de Aço. Talvez eles possam ajudá-lo com suas necessidades de combustível.}
{170}{}{Obrigado. Eu preciso de mais informação.}
{171}{}{Obrigado. Tchau.}
{172}{}{Você é um inimigo do meu povo. Morra!}
{173}{}{Você fez bem para o meu pessoal ao matar o AHS-9. Espero poder ajudá-lo de alguma forma.}
{174}{}{Quem é você?}
{175}{}{Estou procurando por algum equipamento.}
{176}{}{Estou procurando por alguma informação.}
{177}{}{Adeus.}
{178}{}{Você já entregou aos Hubologistas. Não?}
{179}{}{Ah sim ... ah ... Posso perguntar outra coisa?}
{180}{}{Ah sim...Tchau}
