{100}{}{Você vê alguém usando um chapéu de capitão.}
{101}{}{Você vê o capitão A. Ron Meyers.}
{102}{}{Você vê um punk em roupas esfarrapadas usando um chapéu de capitão.}
{103}{}{Que porra você quer? Eu não converso com ninguém a menos que seja amigo ou gente boa. Faça algo por um dos meus amigos e depois venha falar comigo.}
{104}{}{[FEITO]}
{105}{}{Eu ouvi o que você fez pelos meus homens. Obrigado. Em que posso ajudar?}
{106}{}{Você quem?}
{107}{}{Ouvi dizer que você é quem sabe tudo sobre este navio.}
{108}{}{Porque te chamam de Capitão?}
{109}{}{Como você faz essa coisa funcionar?}
{110}{}{Nada.}
{111}{}{Eu sou o Capitão. Dirijo esse barco. Se tiver mais perguntas, vá falar com um dos Shi ou Badger ou qualquer outro. Não tenho tempo pra você.}
{112}{}{[FEITO]}
{113}{}{Este navio é um petroleiro Poseidon. Está equipado com tecnologia que durou durante a guerra. Ele tem um FOB que permite o acesso à sala do computador de navegação e um transponder IFF que o protege dos canhões Poseidon.}
{114}{}{Como você sabe tudo isso?}
{115}{}{O que é um transpondedor IFF?}
{116}{}{Como faz para zarpar?}
{117}{}{Obrigado. Tchau.}
{118}{}{Servi com a Enclave. Então eu percebi que eu não estava lutando pelo USA; era para esses velhos mercenários que não queriam desistir de seu poder. Desertei e agora vivo aqui com gente mais honesta.}
{119}{}{Gente mais honesta? Esses caras?}
{120}{}{O que exatamente é a Enclave?}
{121}{}{Como você faz essa coisa funcionar?}
{122}{}{Adeus.}
{123}{}{Como você pilota este equipamento? Encha-o com um pouco de gasolina - tente os Hubologistas ou o Shi depois de cuidar de todo o resto - e pressione o botão. O computador cuidará do resto, se ainda estiver funcionando. Ele navegará direto para a plataforma de petróleo e eles não atirarão em você porque você tem o transponder IFF. Apenas certifique-se de ter o que precisa para acessar tudo: FOB, computador de trabalho e combustível. Fácil o bastante, né?}
{124}{}{Certo. Como você sabe tudo isso?}
{125}{}{O que seria um transpondedor IFF e um FOB?}
{126}{}{Qual plataforma de petróleo?}
{127}{}{Sim. falou.}
{128}{}{IFF: Identificador de amigo e inimigo. Significa que esse navio será identificado como amigo, então outras coisas do Poseidon - como, digamos, uma plataforma de petróleo - não atirarão em você quando você entrar no alcance. Ah, e um FOB é um tipo de tecnologia da Enclave que permite que você entre por uma porta eletronica. Você provavelmente encontraria um deles em uma de suas bases ou em outro lugar assim.}
{129}{}{Como você sabe tudo isso?}
{130}{}{Qual plataforma de petróleo?}
{131}{}{Obrigado. Tchau.}
{132}{}{Sim. Com essa gente você sabe exatamente qual é sua posição. Eles não jogam. A Enclave era uma cambada de hienas - elas se voltariam contra você em um piscar de olhos.}
{133}{}{O que exatamente é a Enclave?}
{134}{}{Como se uniu a eles?}
{135}{}{A Enclave é remanescente dos velhos tempos. Se você atravessar até a plataforma, descobrirá por si mesmo.}
{136}{}{Como faço para pilotar?}
{137}{}{Que plataforma?}
{138}{}{Bem fácil. Acabei de sair da base de Navarro um dia e desci para cá. Achei que era o último lugar que alguém iria olhar. Além disso, não sou importante o suficiente para que a Enclave me procure - sou apenas uma ponta solta.}
{139}{}{O que exatamente é a Enclave?}
{140}{}{Obrigado. Tchau.}
{141}{}{Há uma grande plataforma de petróleo Poseidon no meio do mar. Essa é a última base da Enclave.}
{142}{}{Como você sabe tudo isso?}
{143}{}{O que mais está acontecendo na plataforma?}
{144}{}{Obrigado. Tchau.}
{145}{}{As pessoas falam muito.}
{146}{}{Entendi. O que mais está acontecendo na plataforma?}
{147}{}{Eu vejo. Tchau.}
{148}{}{Nem sei. Eu era um técnico em Navarro, não um operador de plataforma. Conversamos com eles pelas linhas de comunicação, e isso era tudo.}
{149}{}{Entendi. Pode repetir como posso pilotar?}
{150}{}{Obrigado. Tchau.}
{151}{}{Você cometeu um grande erro mexendo com o capitão e seus amigos...}
{152}{}{Como você pilota este equipamento? Bem, vejo que você já o abasteceu. Depois de cuidar de todo o resto, basta pressionar o botão. O computador cuidará do resto, se ainda estiver funcionando. Ele navegará direto para a plataforma de petróleo e eles não atirarão em você porque você tem o transponder IFF. Apenas certifique-se de ter o que precisa para acessar tudo: FOB, computador de trabalho e combustível. Fácil o bastante, né?}
{153}{}{Oh, sim. Você tem que fazer o computador de navegação funcionar também. Aposto que você encontraria peças para ele em uma daquelas vaults antigas.}
{154}{}{Eai, que bom te ver. Do que precisa?}
{155}{}{, e a menos que eu perca minha aposta, seus amigos também estão lá.}
{156}{}{.}
