{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê o terminal do computador Emperor.}
{102}{}{Você vê um computador com uma tela de toque embutida para sua interface. Na lateral está gravado "Terminal de computador do Imperador v8.8".}
{103}{}{Saudações. Por favor, digite a senha para confirmar sua identidade.}
{104}{}{::babando::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{::hackear o computador::}
{109}{}{Sair.}
{110}{}{Identidade confirmada.}
{111}{}{Qual função você deseja acessar?}
{112}{}{Diagnósticos.}
{113}{}{Banco de dados.}
{114}{}{Previsão.}
{115}{}{Nada.}
{116}{}{Por favor, converse com o administrador do sistema. Adeus.}
{117}{}{::hackear o computador::}
{118}{}{::sair::}
{119}{}{Alerta de intruso ativado. Desligando. Tenha um bom dia.}
{120}{}{[FEITO]}
{121}{}{Funções de diagnóstico?}
{122}{}{Varredura da rede.}
{123}{}{Formatar a unidade.}
{124}{}{Verifique a integridade do disco rígido.}
{125}{}{Voltar.}
{126}{}{Qual banco de dados você gostaria de verificar?}
{127}{}{Biologia.}
{128}{}{Quimica.}
{129}{}{Física.}
{130}{}{História.}
{131}{}{Voltar.}
{132}{}{As crianças de Shi-town estão em perigo. 50% de chance de um assassino estar entre eles.}
{133}{}{O perigo chegou à cidade de Shi. 75% de probabilidade de danos aos residentes.}
{134}{}{O lançamento espacial do Hubologist tem 95% de probabilidade de falhar. Fatores: Sem combustível, selante impróprio, liderança deficiente, falta de iniciativa.}
{135}{}{15% de chance de o "Escolhido" designado ter sucesso na tarefa.}
{136}{}{Os dados indicam que a "Enclave" é mais poderosa do que se acreditava anteriormente; não se aproxime.}
{137}{}{Chances of submarine reappearing in this game: 0%}
{138}{}{0% de chance de eliminar a infestação de criaturas no petroleiro sem ajuda externa. Processando conveniência para fornecer assistência.}
{139}{}{Entrada: Petroleiro Poseidon impróprio para viagens. Requer mais informações.}
{140}{}{Não processado. Requer mais dados.}
{141}{}{[MAIS]}
{142}{}{Voltar.}
{143}{}{Estação de Biologia: Ativa}
{144}{}{Estação de Biologia: Inativa}
{145}{}{Estação Química: Ativa}
{146}{}{Estação Química: Inativa}
{147}{}{Estação de Física: Ativa}
{148}{}{Estação de Física: Inativa}
{149}{}{Desativar Estação de Biologia.}
{150}{}{Desativar Estação Química.}
{151}{}{Desativar Estação de Fisica.}
{152}{}{Acesso a Estação de Biologia.}
{153}{}{Acesso a Estação Química.}
{154}{}{Acesso a Estação de Física.}
{155}{}{Ativar Estação de Biologia.}
{156}{}{Ativar Estação Química.}
{157}{}{Ativar Estação de Física.}
{158}{}{Voltar.}
{159}{}{Formatar a unidade: Todos os dados serão perdidos? Deseja continuar?}
{160}{}{Sim.}
{161}{}{Não.}
{162}{}{A integridade funcional do sistema é de 92%. O núcleo blindado do Computador Imperador é 100%. A integridade dos dados é 100%. O nó de previsão está sofrendo pequenos atrasos de energia - tempo projetado para reparo, 6 dias. Previsão 15% operacional.}
{163}{}{Voltar.}
{164}{}{Tem certeza de que deseja formatar esta unidade? Será um processo irreversível.}
{165}{}{Sim.}
{166}{}{Não.}
{167}{}{Formatando... formatando... formatação concluída. A reinicialização exigirá uma instalação completa. Desligando. Desligando... desligando... completo...}
{168}{}{[FEITO]}
{169}{}{Dados a encontrar: - Programa de botânica - Programa genético - Programa Xeno.}
{170}{}{Programa Botânico.}
{171}{}{Programa Genético.}
{172}{}{Xeno program.}
{173}{}{Voltar.}
{174}{}{(Depois de cerca de vinte minutos, você descobre o seguinte: os resultados iniciais da interrupção da radiação botânica se mostram pouco promissores. O Dr. Sheng desenvolveu plantas resistentes à radiação - mas com efeitos colaterais desagradáveis. A vida vegetal resultante é considerada muito perigosa. Sheng insiste em buscar a linha e misturá-la com o programa genético.)}
{175}{}{Programa Genético.}
{176}{}{Xeno program.}
{177}{}{Voltar.}
{178}{}{(Após cerca de vinte minutos, você reúne estas informações: Usando os fundamentos do vírus FEV, o Dr. Long Wang está convencido do sucesso na criação de soldados mutantes. Ele cria um soro que fornece resultados interessantes com experimentos com roedores. Ele se injeta e se dissolve em uma poça de gosma. Dr. Sheng desativa a linha de investigação. Com a morte do Dr. Long, o Dr. Sheng está no comando. Sheng exige foco na vida das plantas que consomem radiação.)}
{179}{}{Programa Botânico.}
{180}{}{Xeno program.}
{181}{}{Voltar.}
{182}{}{"O tema sobre o qual esperávamos estabelecer uma série de experimentos significativos desapareceu, supostamente destruído ou roubado pelos Hubologistas. Pesquisas posteriores não tiveram resultados. Até que mais amostras sejam obtidas, este banco de dados permanecerá inoperante. "- Dr. Sheng.}
{183}{}{Programa Botânico.}
{184}{}{Programa Genético.}
{185}{}{Voltar.}
{186}{}{Banco de dados de química: Combustível e derivados - Polímeros}
{187}{}{Combustível e derivados.}
{188}{}{Polímeros.}
{189}{}{Voltar.}
{190}{}{(Depois de analisar as fórmulas químicas complexas e as notas de laboratório, você chega à conclusão de que os Shi criaram um tipo de combustível a partir de extratos de plantas e vida marinha. Aparentemente, eles se conectaram a dutos existentes anteriormente para que possam transportar combustível para uma ampla variedade de destinos.)}
{191}{}{(Você encontra uma vasta gama de fórmulas químicas complexas e notas de laboratório. Não tem certeza do que tudo isso significa.)}
{192}{}{Combustível direto para o tanque Poseidon.}
{193}{}{Dirigir combustível aos hubologistas.}
{194}{}{Voltar.}
{195}{}{(Depois de passar pela simbologia e discussão técnica, você descobre que os Shi estão trabalhando em um novo tipo de armadura de combate polimérica que é resistente a chamas e penetração. Ainda faltam anos para ser concluído. Você também vê menção a novas capacidades de armamento e construção. Aparentemente, os Shi têm alguns planos para o futuro.)}
{196}{}{Voltar.}
{197}{}{Combustível direcionado de acordo. Tanques de armazenamento = Vazio. Programa de encerramento.}
{198}{}{[FEITO]}
{199}{}{Combustível direcionado de acordo. Tanques de armazenamento = Vazio. Programa de encerramento.}
{200}{}{[FEITO]}
{201}{}{Banco de dados de Física: Exploração - Teoria}
{202}{}{Exploração.}
{203}{}{Teoria.}
{204}{}{Voltar.}
{205}{}{“Com a recente aquisição dos planos do vertibird, a possibilidade de criar uma máquina voadora prática deu um salto quântico. Esperamos ter um protótipo funcionando até o final do ano e a capacidade de produzir esses veículos em massa em dois anos. " -Dr. Wong}
{206}{}{::copiar planos:: Voltar.}
{207}{}{Voltar.}
{208}{}{"Ainda estamos preparando um modelo funcional de um veículo aéreo. Nenhum dos projetos que criamos mostrou ser seguro ou aerodinâmico. Talvez se tivéssemos acesso aos planos dos antigos..." -Dr. Wong}
{209}{}{Voltar.}
{210}{}{(Depois de contornar a introdução e a matemática, você descobre que os Shi estão aprendendo a desenvolver a energia nuclear novamente, reconstruindo as teorias de viagens espaciais antigas - e eles zombam dos Hubologistas ao fazer - e aproveitando a energia do sol, do vento e do mar. Pelo menos, é assim que as notas se parecem.)}
{211}{}{Voltar.}
{212}{}{Estação ativada.}
{213}{}{Voltar.}
{214}{}{O terminal do computador não parece ter uma interface para isso.}
{215}{}{O terminal do computador não parece estar operante.}
{216}{}{O sistema foi comprometido. As ordens são atacar!}
{217}{}{Ataque o intruso!}
{218}{}{É hora de pagar por seus atos, lao wai!}
{219}{}{Tem um traidor em nosso meio!}
{220}{}{Geolocalização.}
{221}{}{O que deseja localizar?}
{222}{}{Os aldeões do meu lar.}
{223}{}{97% de chance agregada - Aldeões localizados nas coordenadas atuais do complexo da Enclave.}
