{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê o terminal do computador Emperor.}
{102}{}{Você vê um computador com uma tela de toque embutida para sua interface. Na lateral está gravado "Terminal de computador do Imperador v8.8".}
{103}{}{Saudações. Por favor, digite a senha para confirmar sua identidade.}
{104}{}{::babando::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{::hackear o computador::}
{109}{}{Sair.}
{110}{}{Identidade confirmada.}
{111}{}{Qual função você deseja acessar?}
{112}{}{Diagnósticos.}
{113}{}{Banco de dados.}
{114}{}{Previsão.}
{115}{}{Nada.}
{116}{}{Por favor, converse com o administrador do sistema. Adeus.}
{117}{}{::hackear o computador::}
{118}{}{::sair::}
{119}{}{Alerta de intruso ativado. Desligando. Tenha um bom dia.}
{120}{}{[FEITO]}
{121}{}{Funções de diagnóstico?}
{122}{}{Varredura da rede.}
{123}{}{Formatar a unidade.}
{124}{}{Verifique a integridade do disco rígido.}
{125}{}{Voltar.}
{126}{}{Qual banco de dados você gostaria de verificar?}
{127}{}{Biologia.}
{128}{}{Quimica.}
{129}{}{Física.}
{130}{}{História.}
{131}{}{Voltar.}
{132}{}{As crianças de Shi-town estão em perigo. 50% de chance de um assassino estar entre eles.}
{133}{}{O perigo chegou à cidade de Shi. 75% de probabilidade de danos aos residentes.}
{134}{}{O lançamento espacial do Hubologist tem 95% de probabilidade de falhar. Fatores: Sem combustível, selante impróprio, liderança deficiente, falta de iniciativa.}
{135}{}{15% de chance de o "Escolhido" designado ter sucesso na tarefa.}
{136}{}{Os dados indicam que a "Enclave" é mais poderosa do que se acreditava anteriormente; não se aproxime.}
{137}{}{Chances of submarine reappearing in this game: 0%}
{138}{}{0% de chance de eliminar a infestação de criaturas no petroleiro sem ajuda externa. Processando conveniência para fornecer assistência.}
{139}{}{Input: Poseidon Oil tanker unfit for travel. Require more input.}
{140}{}{Not processing. Require input.}
{141}{}{[MAIS]}
{142}{}{Voltar.}
{143}{}{Biology station: Active}
{144}{}{Biology station: Inactive}
{145}{}{Chemistry station: Active}
{146}{}{Chemistry station: Inactive}
{147}{}{Physics station: Active}
{148}{}{Physics station: Inactive}
{149}{}{Deactivate Biology Station.}
{150}{}{Deactivate Chemistry Station.}
{151}{}{Deactivate Physics Station.}
{152}{}{Access Biology Station.}
{153}{}{Access Chemistry Station.}
{154}{}{Access Physics Station.}
{155}{}{Activate Biology Station.}
{156}{}{Activate Chemistry Station.}
{157}{}{Activate Physics Station.}
{158}{}{Voltar.}
{159}{}{Format drive: All data will be lost. Are you sure?}
{160}{}{Sim.}
{161}{}{Não.}
{162}{}{The functional integrity of this system is 92%. The shielded core of the Emperor Computer is 100%. The integrity of the data is 100%. The forecasting node is suffering minor power lags - projected time to repair 6 days. Forecast 15% operational.}
{163}{}{Voltar.}
{164}{}{Are you sure you wish to format this unit? This is an irreversible process.}
{165}{}{Sim.}
{166}{}{Não.}
{167}{}{Formatting... formatting... formatting complete. Reboot requires full install. Shutting down. Shutting... down... complete...}
{168}{}{[FEITO]}
{169}{}{Data to find: - Botany program - Genetic program - Xeno program.}
{170}{}{Programa Botânico.}
{171}{}{Programa Genético.}
{172}{}{Xeno program.}
{173}{}{Voltar.}
{174}{}{(After about twenty minutes, you discover this: Initial results of botanical radiation disruption prove unpromising. Dr. Sheng develops radiation resistant plant-life - unpleasant side-effects follow. Resultant plant life deemed too dangerous. Sheng insists on pursuing line and mixing it with genetic program.)}
{175}{}{Programa Genético.}
{176}{}{Xeno program.}
{177}{}{Voltar.}
{178}{}{(After about twenty minutes you piece together this information: Using the basics of the FEV virus, Dr. Long Wang is convinced of success in creating mutant soldiers. He creates a serum providing interesting results with rodent experiments. He injects himself and dissolves into a puddle of goo. Dr. Sheng disables line of inquiry. With the death of Dr. Long, Dr. Sheng is in charge. Sheng demands focus on radiation-consuming plant life.)}
{179}{}{Programa Botânico.}
{180}{}{Xeno program.}
{181}{}{Voltar.}
{182}{}{"The subject on which we had hoped to establish a series of meaningful experiments has disappeared, presumed either destroyed or stolen by the Hubologists. Further inquiries have proven fruitless. Until such time as further specimens are obtained, this database will remain inoperative." - Dr. Sheng.}
{183}{}{Programa Botânico.}
{184}{}{Programa Genético.}
{185}{}{Voltar.}
{186}{}{Chemistry Database: Fuel and derivatives - Polymers}
{187}{}{Combustível e derivados.}
{188}{}{Polímeros.}
{189}{}{Voltar.}
{190}{}{(After sifting through the complex chemical formulae and lab notes, you come to the conclusion that the Shi have created a kind of fuel from plant extracts and sealife. Apparently, they have hooked into previously existing pipelines so they can transport fuel to a wide variety of destinations.)}
{191}{}{(Você encontra uma vasta gama de fórmulas químicas complexas e notas de laboratório. Não tem certeza do que tudo isso significa.)}
{192}{}{Combustível direto para o tanque Poseidon.}
{193}{}{Dirigir combustível aos hubologistas.}
{194}{}{Voltar.}
{195}{}{(Depois de passar pela simbologia e discussão técnica, você descobre que os Shi estão trabalhando em um novo tipo de armadura de combate polimérica que é resistente a chamas e penetração. Ainda faltam anos para ser concluído. Você também vê menção a novas capacidades de armamento e construção. Aparentemente, os Shi têm alguns planos para o futuro.)}
{196}{}{Voltar.}
{197}{}{Combustível direcionado de acordo. Tanques de armazenamento = Vazio. Programa de encerramento.}
{198}{}{[FEITO]}
{199}{}{Combustível direcionado de acordo. Tanques de armazenamento = Vazio. Programa de encerramento.}
{200}{}{[FEITO]}
{201}{}{Physics database: Exploration - Theory}
{202}{}{Exploração.}
{203}{}{Theory.}
{204}{}{Voltar.}
{205}{}{"With recent acquisition of vertibird plans, the possibility of creating a practical flying machine has taken a quantum leap forward. We expect to have a working prototype by the end of the year, and the ability to mass-produce such vehicles within two years." -Dr. Wong}
{206}{}{::copy plans:: Back.}
{207}{}{Voltar.}
{208}{}{"We are still preparing a working model of an aerial vehicle. None of the designs we have created have proven to be safe or aerodynamic. Perhaps if we had access to the plans of the ancients..." -Dr. Wong}
{209}{}{Voltar.}
{210}{}{(After wading through the introduction and the mathematics, you discover that the Shi are learning to develop nuclear power again, rebuilding the space travel theories of the ancients - and they mock the Hubologists while doing so - and harnessing the energy of the sun, wind, and sea. At least, that's what the notes read like.)}
{211}{}{Voltar.}
{212}{}{Station activated.}
{213}{}{Voltar.}
{214}{}{The computer terminal doesn't seem to have an interface for that.}
{215}{}{The computer terminal appears non-operational.}
{216}{}{There has been a compromise in the system. Orders are to attack!}
{217}{}{Attack the intruder!}
{218}{}{Time to pay for your acts, lao wai!}
{219}{}{There is a traitor in our midst!}
{220}{}{Geo-Location.}
{221}{}{What do you wish to locate?}
{222}{}{The villagers from my home.}
{223}{}{97% aggregate chance - Villagers located at current coordinates of Enclave compound.}
