{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê a estação de física.}
{102}{}{Você vê um terminal de computador em funcionamento.}
{103}{}{Olá. Por favor, confirme sua identidade.}
{104}{}{[Oooh! Olhe todas essas luzes ofuscantes!]}
{105}{}{::adivinhar a senha::}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{::hackear o computador::}
{108}{}{Sair.}
{109}{}{Banco de dados de física: -Exploração- -Teoria-}
{110}{}{Exploração...}
{111}{}{Teoria...}
{112}{}{Desativar estação.}
{113}{}{Senha incorreta. Favor falar com o administrador do sistema. Até logo.}
{114}{}{::hackear o computador::}
{115}{}{::sair::}
{116}{}{Alerta de intruso ativado. Desligando. Tenha um bom dia.}
{117}{}{-pronto-}
{118}{}{“Com a recente aquisição dos planos do vertibird, a possibilidade de criar uma máquina voadora prática deu um salto quântico. Esperamos ter um protótipo funcionando até o final do ano e a capacidade de produzir esses veículos em massa em dois anos. " -Dr. Wong}
{119}{}{::copiar planos::}
{120}{}{Voltar.}
{121}{}{"Ainda estamos preparando um modelo funcional de um veículo aéreo. Nenhum dos projetos que criamos se mostrou seguro ou aerodinâmico. Talvez se tivéssemos acesso aos planos dos antigos..." - Dr. Wong}
{122}{}{Voltar.}
{123}{}{(After wading through the introduction and the mathematics, you discover that the Shi are learning to develop nuclear power again, rebuilding the space travel theories of the ancients - and they mock the Hubologists while doing so - and harnessing the energy of the sun, wind, and sea.  At least, that's what the notes read like.)}
{124}{}{Voltar.}
{125}{}{Estação desativada.}
{126}{}{Ativar estação.}
{127}{}{-sair-}
{128}{}{Sabe-se lá como, você digita uma sequência qualquer de letras e acaba ganhando acesso! Como você pode ter tanta sorte?}
{129}{}{-mais-}
{130}{}{O computador não responde a nenhum comando.}
{131}{}{Você não consegue achar nenhum lugar pra colocar isso.}
{132}{}{Copiando planos... Cópia concluída... Retornando a... Erro de E/S... GPF... Desativando terminal.}
