{100}{}{Você vê um homem magro e de aparência amigável.}
{101}{}{Você vê Chad, o caravaneiro.}
{102}{}{Você vê um homem magro com um belo sorriso estampado no rosto. Ele usa roupas indescritíveis, e dá
 a sensação de saber o que está fazendo.}
{120}{}{Olá, amigo! O que posso fazer por você?}
{121}{}{Mais perguntas? Vamos ver o que posso responder.}
{122}{}{Deerk deegler!}
{123}{}{Você quem?}
{124}{}{Marcus tem feito algumas perguntas sobre você.}
{125}{}{Há provas suficientes para prendê-lo por roubar dinheiro que deveria ir para Broken Hills. Você vai se ferrar.}
{126}{}{Há provas suficientes para te prender por roubar dinheiro que deveria ir para Broken Hills. Me pague US$ 1.000 e garanto que você pode fugir da cidade.}
{127}{}{Quem é você?}
{128}{}{Conte-me sobre este lugar.}
{129}{}{Nada. Tchau.}
{130}{}{Olha o quê as Terras Ermas arrastou até aqui! Desculpa, mano, eu não posso te ajudar.}
{131}{}{A-deus!}
{132}{}{Eu sou Chad. }
{133}{}{Olha, eu estou muito ocupado. Por favor encontre outra pessoa para importunar.}
{134}{}{Sou o chefe da caravana da cidade. Eu cuido dos negócios do outro lado das rotas comerciais. Hoje em dia estou me concentrando principalmente em Gecko.}
{135}{}{Tudo bem!}
{136}{}{Eu gostaria trabalhar com você.}
{137}{}{Me sua interessante.}
{138}{}{Me soa tedioso.}
{139}{}{Eu tenho mais perguntas.}
{140}{}{Obrigado. Tchau.}
{141}{}{Falar sobre Broken Hills? Bom... eu me mudei para cá há alguns anos. Consegui um emprego com o Bill -
 ele é o Fornecedor - e eu subi para onde estou agora. Informo ao Marcus e o Bill, mas eu sou o
 responsável pelo sustento da cidade.}
{142}{}{Eu tenho mais perguntas.}
{143}{}{Adeus.}
{144}{}{Como o quê?}
{145}{}{He suspects that you are skimming the money that's supposed to go to Broken Hills.}
{146}{}{Na verdade nada, adeus.}
{147}{}{Look, I don't like people to accuse me about something that I don't know anything about. I suggest that you leave.}
{150}{}{I'm going to find out the truth. Bye.}
{156}{}{Fale com o Bill. Ele irá te ajudar.}
{157}{}{Eu tenho mais perguntas.}
{158}{}{Obrigado. Tchau.}
{159}{}{Sim, é. Pode não parecer, mas eu viajo e vejo o mundo... e sinto que aqui 
 contribuo com a cidade. É uma boa vida.}
{160}{}{Parece bom. Eu gostaria de um trabalho assim.}
{161}{}{Na verdade, isso me da sono.}
{162}{}{Eu tenho mais perguntas.}
{163}{}{Adeus.}
{164}{}{Provavelmente muito mais emocionante do que o que você faz da sua vida, idiota.}
{165}{}{Sim, tanto faz. Eu tenho mais perguntas.}
{166}{}{Ha ha ha ha! Certo. Até mais, perdedor.}
{167}{}{Você vai pagar por isso algum dia, cretino.}
{168}{}{Sai da minha frente, babaca.}
{169}{}{Você montou esta caravana muito bem, amigão. Ótimo para seu bolso.}
{170}{}{Você certamente cagou tudo com essa caravana, meu amigão. Boa sorte em conseguir outra de Broken Hills.}
{171}{}{Bom trabalho naquela caravana. Aqui estão seus $200.}
{172}{}{Saia daqui. Não precisamos mais da sua ajuda.}
{173}{}{Mantenha seus olhos abertos.}
{174}{}{Vou cobrir suas costas.}
{175}{}{Não deixe aqueles cornos chegarem perto de você.}
