{100}{}{Você vê um homem preocupado.}
{101}{}{Você vê Dan, o marido preocupado.}
{102}{}{Você vê um homem bem vestido com uma cara que chega perto a beira da loucura.}
{103}{}{Quem é Você? O que você esta fazendo na minha casa?}
{104}{}{Ack? Oop?}
{105}{}{Eu sou }
{106}{}{Nada de importante.}
{107}{}{Estou aqui pra te roubar.}
{108}{}{Nada não. Tchau.}
{109}{}{Na minha casa não, por favor. Há uma rua lá fora onde você pode dormir e fazer qualquer coisa "especial" que pessoas como você fazem.}
{110}{}{Thppt!}
{111}{}{Ótimo, que bom. Prazer em conhecê-lo. [Ele parece distraído.] Ei, olha... você é do tipo aventureiro, certo?}
{112}{}{Sim.}
{113}{}{Você não reconhece o Escolhido?}
{114}{}{Não.}
{115}{}{E o que isso te importa?}
{116}{}{The reason I ask,  you see, is because my wife is missing. I don't know where she is. She's been gone for days. I've asked around town, and no one has seen her. Can you find her for me?}
{117}{}{O quê tem pra mim?}
{118}{}{Eu vou dar uma olhada. Como ela é?}
{119}{}{Não, estou ocupado.}
{120}{}{Eu de dou $ 500. São as economias da minha vida toda.}
{121}{}{Isso é suficiente. Eu farei.}
{122}{}{Não posso fazer.}
{123}{}{Por favor, por favor. Minha esposa... ela é tudo para mim. Por favor.}
{124}{}{Já disse que não!}
{125}{}{Fine. Fine, just stop pestering me.}
{126}{}{Here's the money. Now please, please, PLEASE... find my wife and tell me where she is. Maybe she's shacked up with someone else, maybe she's left me... but I just need to know.	}
{127}{}{Certo, amigo. Como ela é?}
{128}{}{Certo. Vou fazer o meu melhor.}
{129}{}{::he sobs uncontrollably for a few moments:: Very well. Go away. And realize that you've broken my heart.    }
{130}{}{Até mais, perdedor.}
{131}{}{Ela é loira, sexy e tem uma voz incrível para cantar... Eu a vi pela última vez andando por esta área. Ela não gostava de mutantes ou ghouls, então ela não estaria perto de nenhum deles. Ninguém sabe para onde ela foi... É como se simplesmente tivesse desaparecido.}
{132}{}{Isso deve ser o suficiente.}
{133}{}{E ai? Você achou? Meu coração dói a cada segundo que passa.}
{134}{}{Desculpe, cara, ainda estou procurando.}
{135}{}{Sim, eu encontrei.}
{136}{}{Por enquanto não. Mas estou procurando.}
{137}{}{Oh, que dor no coração. Por favor, me avise quando você a encontrar.}
{138}{}{Sim, claro.}
{139}{}{Na verdade, não vou mais procurar por ela.}
{140}{}{Você a encontrou? ::seus olhos se iluminam:: Onde?}
{141}{}{Ela era uma tesuda sem pernas?}
{142}{}{Encontrei um grupo de mortos nos túneis abaixo da cidade. Ela era uma delas. Eu sinto muito.}
{143}{}{Que? Não! Ela tinha pernas lindas!}
{144}{}{Oh. Right. Well, she hasn't got great legs now. She really got savaged, and her legs are OFF. She's totally dead, and she suffered before she died.	}
{145}{}{Certo. Bem, acho que a encontrei nos túneis abaixo da cidade. Ela está morta, sinto muito.}
{146}{}{Obrigado por me dizer, acho que agora vou chorar.}
{147}{}{Sim, vai chorar lá, seu perdedor apaixonado.}
{148}{}{Desculpe, amigo.}
{149}{}{Te odeio! Todo mundo te odeia! Morra! ::soluço::}
{150}{}{Encontrei uma carta no corpo da sua esposa. Tudo indica que ela pode ter feito parte de uma conspiração para matar os mutantes em Broken Hills.}
{151}{}{Meu Deus! Eu... eu não posso acreditar que... não é... [suspira profundamente]. Acho que é verdade. 
 Ela sempre pareceu odiar todos os mutantes e ghouls apareceram na frente. Eu nunca soube por quê.}
{152}{}{Be that as it may, you may want to consider that the murders might not stop with your wife. If she was implicated, you may be as well.}
{153}{}{You don't mean to say that my life is in danger too? Oh dear. You may be right. I've been hearing noises outside
 the house at night. Whispers and shuffles.}
{154}{}{It might be a good idea to leave. Watch your back. Good luck.}
{155}{}{Thanks so much for your help. I'm not staying here any longer than I have to.}
{156}{}{You informed Dan of his wife's murder.}
{157}{}{.}
