{100}{}{Você vê uma pessoa entediada usando uma armadura de couro.}
{101}{}{Você vê Max, o guarda da caravana.}
{102}{}{Você vê uma pessoa empoeirada e entediada usando uma armadura de couro. Pelo cheiro de brahmin 
 e pelo andar confiante, é claramente um guarda de caravana.}
{103}{}{Posso te ajudar com alguma coisa?}
{104}{}{Urg?}
{105}{}{Tra-balho aqui!}
{106}{}{Quem é você?}
{107}{}{O que você pode me dizer sobre Chad?}
{108}{}{Não tenho paciência para idiotas. Foi mal, amigo, vai achar outro pateta pra brincar com você.}
{109}{}{::sniff::}
{110}{}{Sou o Max. Sou um dos guardas da caravana.}
{111}{}{O que você pode me dizer sobre Chad?}
{112}{}{Obrigado. Tchau.}
{113}{}{Eu não gosto muito dele. Ele parece sempre conseguir algum dinheiro extra de seus trabalhos de caravana. É realmente injusto.}
{114}{}{Bem, Marcus suspeita que está desviando parte do dinheiro que deveria ir para Broken Hills.}
{115}{}{Obrigado. Tchau.}
{116}{}{Obrigado, estou muito feliz por isso ter acabado. É melhor você ver a sua volta.}
{117}{}{Adeus.}
{118}{}{Ele é um inimigo! Morra!}
{119}{}{Oops.}
{120}{}{[Abaixa a voz e olha em volta] Deve ser isso. Uma vez eu vi que ele estava pegando uma "fatia" daquele dinheiro que conseguiu com o carregamento de urânio de Gecko.}
{121}{}{Really? Then why didn't you report that to Marcus?}
{122}{}{Você é idiota? Se eu for contar, muita gente nesta cidade nem vai olhar na minha cara. Além disso, poderia haver alguma vingança.}
{123}{}{Hmm, eu poderia contar isso para Marcus, porque eu não pretendo ficar aqui por muito tempo de qualquer maneira.}
{124}{}{OK. Faça o que quiser, mas não conte nada sobre mim. E nunca tivemos essa conversa, ok?}
{125}{}{Don't worry, I don't want to get you in any trouble, bye.}
