{100}{}{Você vê uma pessoa entediada usando uma armadura de couro.}
{101}{}{Você vê Max, o guarda da caravana.}
{102}{}{Você vê uma pessoa empoeirada e entediada usando uma armadura de couro. Pelo cheiro de brahmin 
 e pelo andar confiante, é claramente um guarda de caravana.}
{103}{}{Posso te ajudar com alguma coisa?}
{104}{}{Urg?}
{105}{}{Tra-balho aqui!}
{106}{}{Quem é você?}
{107}{}{O que você pode me dizer sobre Chad?}
{108}{}{Não tenho paciência para idiotas. Foi mal, amigo, vai achar outro pateta pra brincar com você.}
{109}{}{::sniff::}
{110}{}{Sou o Max. Sou um dos guardas da caravana.}
{111}{}{O que você pode me dizer sobre Chad?}
{112}{}{Obrigado. Tchau.}
{113}{}{I don't like him much. He seems to get always some extra money from his caravan jobs. It's really unfair.}
{114}{}{Well, Marcus suspects that he is skimming some of the money that supposed to go Broken Hills.}
{115}{}{Obrigado. Tchau.}
{116}{}{Thanks. I'm sure glad that this is over. You better watch your back thought.}
{117}{}{Adeus.}
{118}{}{Ele é um inimigo! Morra!}
{119}{}{Oops.}
{120}{}{(Lowers his voice and looks around) That's gotta be it. I once saw myself that he was taking some "slice" of that money he got from uranium shipment from Gecko.}
{121}{}{Really? Then why you haven't tell about it to Marcus then?}
{122}{}{Are you duff? If I go to tell it, a lot of people in this town won't even look at me. Besides I might get some kind of revenge.}
{123}{}{Hmm, I could tell it about to Marcus, cause I don't plan to stay here too long anyway.}
{124}{}{Ok. Do what you want, but don't tell anything about me. And we never had this conversation, ok?}
{125}{}{Don't worry, I don't want to get you in any trouble, bye.}
