{100}{}{Você vê uma pessoa carregando uma arma poderosa.}
{101}{}{Você vê um membro do corpo de comércio e proteção de Broken Hills.}
{102}{}{Você vê uma pessoa carregando uma arma poderosa e coberta pela poeira da trilha.}
{103}{}{Te juro, mais um grupo de salteadores e eu vou carregando dinamite na próxima viagem.}
{104}{}{Um pouco mais de ajuda com as caravanas não faria mal.}
{105}{}{Amigo... a coisa da patrulha da Unidade já está cansando.}
{106}{}{Então eu vi aquele tribal aparecer e... não importa.}
{107}{}{Mais um piada sobre "patrulha arco-íris" e eu mato um.}
{108}{}{Sério, se os bandidos piorarem vamos todos morrer no próximo ano.}
{109}{}{De que desgraça de aldeia você veio?}
{110}{}{Comprar uma bebida para um trabalhador?}
{111}{}{Esse trabalho de caravana me deixa muito cansado para ter vontade de falar.}
{112}{}{Você precisa de algo, fale com Bill, o Fornecedor.}
{113}{}{Qualquer um pensaria que depois de todo esse tempo tentando civilizar o deserto estaríamos um pouco mais perto de nosso objetivo.}
{114}{}{Já cansei dessas disputas entre humanos e mutantes. Não deveríamos ser um exemplo?}
{115}{}{Que foi? Não vê que estou descansando?}
{116}{}{Quando a próxima caravana sai?}
{117}{}{Patrulhar, patrulhar, patrulhar... é tudo o que faço por aqui.}
{118}{}{Acho que preciso de um cochilo.}
{119}{}{Eu mereço um aumento, esse é um trabalho perigoso.}
