{100}{}{You see Three-Card Monte.}
{150}{}{You see a spindly-looking old man with a sunburned face. He's so thin he looks like he's made out of twigs.}
{200}{}{Não entendo como perdi...}
{205}{}{Heeeey! Hero! You all right, you all right.}
{215}{}{Where the hell are my cards? I JUST had them.}
{220}{}{Yo, pal, don't bother with the casinos. Come play with Monte.}
{230}{}{Monte ain't open for games today, friend; my damn cards have gone missing.}
{231}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, friend?}
{250}{}{Get down to what? The game, of course!}
{260}{}{(You hand over the cash. Monte nods, shows you the cards, then slaps them down on the ground and shuffles them for a few seconds.)}
{280}{}{(Monte turns over the card. It is the two of spades.)}
{300}{}{(You hand over the cash. Monte nods, shows you the cards, then lays them on the ground. As he does, he palms a card, so quickly you almost miss it. He then proceeds to shuffle for a few seconds.)}
{320}{}{WHAT did you say, pal?}
{330}{}{Look, I ain't got time for sore losers. You pay your money, you take your chances. If you
 wanna PLAY, fine, but if
 you're just gonna bitch when you lose, then get lost!}
{340}{}{(You hand over the cash. Monte nods, then slaps the cards down and shuffles them for a few seconds.)}
{360}{}{(You hand over the cash. Monte nods, shows you the cards, then slaps them down on the ground and shuffles them for a few seconds.)}
{375}{}{(Monte turns over the card. It is the queen of hearts. He seems paralyzed with shock.) Uh...? Heh. Eh...}
{385}{}{(Monte turns over the card. It is the queen of hearts. He looks shocked.) Uh...? Heh... uh...}
{400}{}{(Looks pained.) Eh... well, I do have something... but it's worth WAY more than you won... still...}
{405}{}{Eh... hmnnn... depends on what you want to know.}
{415}{}{Eh... well... look, you ain't heard it from me, but my bets on Renesco, that asshole who runs the pharmacy on the west side.
 I don't know if he sold it TO the kid for sure, but he knows something. That's all I'm gonna say.}
{420}{}{Eh... well... (looks like he's fighting an inner battle) ...look, you ain't heard it from me, but if I was you, I'd
 check out the basement of the Desperado.}
{425}{}{(Narrows his eyes, leans in) I'd ask ol' Jules at the front of town. Nothing gets by him... and
 if it DID, then he had a finger in it, know what I'm saying?}
{430}{}{Well... know that Eldridge fella that runs New Reno Arms? He says he does weapon upgrades, but I never see him do
 any work. Might be worthwhile to check out his place... but you didn't hear that from me.}
{435}{}{(Monte frowns as he sees you.) Look, I ain't running no games today, all right? Blow.}
{440}{}{Nope. Ain't gonna part with that. Period. It's GENUINE pre-war memorabilia... a little slice of history. No WAY.}
{450}{}{You deaf? That amount ain't even enough to interest me.}
{460}{}{Well, it ain't THAT dear to me. It's yours, pal. (He glances to the right and left, then reaches down and pulls off his
 boot. He twists off the heel and pulls out a playing card from inside.) Here ya go. Take care of it.}
{465}{}{(Frowns) Whether I talk depends on what you want to know. And it's not gonna be cheap.}
{475}{}{No way in Golgotha am I going to even TOUCH that subject. Piss off.}
{490}{}{(Shakes his head.) No way. Talking about that could get somebody killed, startin' with me. Forget it.}
{495}{}{Eh... well... that's a lot of chips. (Licks his lips. He looks like he's fighting an inner battle....but the battle is a brief one.) Look, you ain't heard it from me...}
{500}{}{(Sneers) Maybe I heard something, maybe I didn't. Name a price.}
{510}{}{Ha! You couldn't buy a bucket of piss for that much. Forget it.}
{515}{}{Thaaaat's about right. (Grins evilly.) Look, you ain't heard it from me, but if I was you, I'd check out the basement of the Desperado on Virgin Street. There's a lot of "rats" there, if you catch my drift.}
{520}{}{(Shrugs) Maybe I know something about that, maybe I don't. Tell me a price and I might have something to say.}
{530}{}{(Narrows his eyes, leans in) For that amount, I don't know nothing.}
{535}{}{That's about right... (narrows his eyes, leans in) ...I'd ask ol' Jules at the front of town. Nothing
 gets by him... and if it DID, then he had a finger in it, know what I'm saying?}
{540}{}{(Shrugs) I hear things, I see things. For 200 chips, maybe you can get the benefit of my experience, know what I'm saying?}
{550}{}{You deaf? I SAID 200 chips, n' I meant it.}
{555}{}{Done. (Monte leans in) Well, know that guy Eldridge, runs New Reno Arms? He SAYS he does
 weapon upgrades, but I never see him do any work. You might want to check out his place... but
  you didn't hear that from me.}
{560}{}{Boneyard south of town. Stinks ta high heaven, it does.}
{565}{}{My bets on Renesco, that old asshole who runs the pharmacy on the west side. I don't know
 if he sold it TO the kid for sure, but he knows SOMETHING. (Glances around) That's all I'm gonna say.}
{570}{}{(He glances around, then reaches down and pulls off his boot. He twists off the heel and pulls out a card... on the card
 is a man with a strange hat, wielding a club.) Interested? It's genuine pre-war memorabilia.}
