{100}{}{Você vê um Monte de Três Cartas.}
{150}{}{Você vê um velho magro com o rosto queimado de sol. Ele é tão magro que parece uma tripa escorrida.}
{200}{}{Não entendo como perdi...}
{205}{}{Heeeey! Herói! Você fez bem, muito bem.}
{215}{}{Onde diabos estão minhas cartas? Estavam AGORA aqui.}
{220}{}{Ei, amigo, não se preocupe com os cassinos, venha brincar com o Monte.}
{230}{}{O Monte não está aberto para jogos hoje, amigo; minhas malditas cartas sumiram.}
{231}{}{(O velho sorri e a pele ao redor dos olhos se enruga.) Quer brincar, amigo?}
{250}{}{Descer para o quê? O jogo, claro!}
{260}{}{(Você entrega o dinheiro. Monte acena com a cabeça, mostra as cartas, depois as joga no chão e as embaralha por alguns segundos.)}
{280}{}{(Monte turns over the card. It is the two of spades.)}
{300}{}{(Você entrega o dinheiro. Monte acena com a cabeça, mostra as cartas e as coloca no chão. Ao fazer, ele pega uma carta, tão rápido que você quase a perde. Ele então começa a embaralhar por alguns segundos.)}
{320}{}{O que você disse, colega?}
{330}{}{Olha, eu não tenho tempo para perdedores bunda mole. Você paga seu dinheiro e arrisca,
 só. Se você quer JOGAR, tudo bem, mas se você só vai ficar com graça quando perder,
 então saia!}
{340}{}{(Você entrega o dinheiro. Monte acena com a cabeça, depois bate as cartas e as embaralha por alguns segundos.)}
{360}{}{(Você entrega o dinheiro. Monte acena com a cabeça, mostra as cartas, depois as joga no chão e as embaralha por alguns segundos.)}
{375}{}{(Monte vira a carta. É a rainha de copas. O bixo ficou em choque.) Uh...? Heh. Eh...}
{385}{}{(Monte vira a carta. É a rainha de copas. Ele fica em choque.) Uh...? Eh... ah...}
{400}{}{(Parece aflito.) Eh... bem, eu tenho algo... mas vale MUITO mais do que você ganhou... ainda assim...}
{405}{}{Eh... hmnnn... depende do que você quer saber.}
{415}{}{Eh... bem... olhe, você não ouviu nada de mim, mas eu aposto no Renesco, aquele babaca que tem a farmácia no lado oeste.
 Não tenho certeza se ele vendeu para o garoto, mas ele sabe de alguma coisa. Isso é tudo que eu vou dizer.}
{420}{}{Eh... bem... (parece que ele tem uma luta interior) ...olha, você não ouviu isso de mim, mas se eu fosse
 você, daria uma olhada no porão do Desperado.}
{425}{}{(Aperta os olhos e se inclina) Eu perguntaria ao velho Jules na frente da cidade. Nada passa
 sem ele saber... e se aconteceu, então ele teria um dedo nisso, entendeu o que estou dizendo?}
{430}{}{Bem... conhece aquele tal Eldridge que dirige a New Reno Arms? Ele diz que faz upgrades em armas, mas nunca o
 vejo fazer nada da vida. Talvez seja bom dar uma olhada na casa dele... mas você não ouviu isso de mim.}
{435}{}{(Monte franze a testa quando te vê.) Olha, não vou fazer nenhum jogo hoje, certo? Saia.}
{440}{}{Não, não vou me livrar disso, esquece. É um item AUTENTICO do pré-guerra... um pedacinho da história. NEM VEM.}
{450}{}{Está surdo? Essa quantia nem é suficiente para me interessar.}
{460}{}{Bem, não é tão caro para mim. É seu, amigo. (Ele olha para a direita e para a esquerda, depois se abaixa e tira a
 bota. Ele torce o calcanhar e tira uma carta de baralho de dentro.) Aqui está. Tome conta disso.}
{465}{}{(Carranca) O que eu digo depende do que você quer saber. E não será barato.}
{475}{}{Não vou tocar nesse assunto da Gólgota. Vá dar uma passeada.}
{490}{}{(Balança a cabeça.) De jeito nenhum. Falar sobre isso pode matar alguém, começando por mim. Esqueça.}
{495}{}{Eh... bem... isso é um monte de fichas. (Lambe os lábios. Ele parece estar lutando uma batalha interna... mas dura pouco.) Olha, você não ouviu isso de mim...}
{500}{}{(Risos) Talvez eu tenha ouvido alguma coisa, talvez não. Diga um preço.}
{510}{}{Ah! Você não pode comprar um balde de mijo com isso. Esqueça.}
{515}{}{Tá certo. (Sorri maliciosamente.) Olha, você não ouviu isso de mim, mas se eu fosse você, eu olharia o porão do Desperado na Virgin Street. Há muitos "ratos" lá, se você me entende.}
{520}{}{(Encolhe os ombros) Talvez eu saiba algo sobre isso, talvez não. Me fale um preço e talvez eu tenha algo a dizer.}
{530}{}{(Aperta os olhos, se inclina) Por essa quantia, não sei de nada.}
{535}{}{Isso mesmo... (cerra os olhos, se inclina) ...eu perguntaria ao velho Jules na frente da cidade.
 Nada passa por ele... e se aconteceu, então deve ter um dedo nele, entendeu o que eu disse?}
{540}{}{(Dá de ombros) Eu ouço coisas, eu vejo coisas. Por 200 fichas, talvez você possa ouvir um pouco da minha experiência, entendeu o que eu disse?}
{550}{}{Você é surdo? EU DISSE 200 fichas, só com isso.}
{555}{}{Done. (Monte leans in) Well, know that guy Eldridge, runs New Reno Arms? He SAYS he does
 weapon upgrades, but I never see him do any work. You might want to check out his place... but
  you didn't hear that from me.}
{560}{}{Boneyard south of town. Stinks ta high heaven, it does.}
{565}{}{My bets on Renesco, that old asshole who runs the pharmacy on the west side. I don't know
 if he sold it TO the kid for sure, but he knows SOMETHING. (Glances around) That's all I'm gonna say.}
{570}{}{(He glances around, then reaches down and pulls off his boot. He twists off the heel and pulls out a card... on the card
 is a man with a strange hat, wielding a club.) Interested? It's genuine pre-war memorabilia.}
