{100}{}{You see a card dealer.}
{101}{}{Você vê um Monte de Três Cartas.}
{150}{}{Você vê um velho magro com o rosto queimado de sol. Ele é tão magro que parece uma tripa escorrida.}
{151}{}{You see Three-Card Monte. He scopes out the street, spots you, and nods.}
{152}{}{You see Three-Card Monte. He scopes out the street, spots you, and nods.}
{200}{}{Não entendo como perdi...}
{201}{}{Just keep walking... Monte's not in business today.}
{202}{}{Did I palm the wrong card?}
{203}{}{How did that stupid tribal keep picking the right card?}
{205}{}{Heeeey! Herói! Você fez bem, muito bem.}
{206}{}{::Faz o sinal de positivo pra você::}
{207}{}{::Smiles, nods::}
{208}{}{You done good, hero. You done good.}
{215}{}{Onde diabos estão minhas cartas? Estavam AGORA aqui.}
{216}{}{Goddamn car key gnomes, now they're going after my playing cards.}
{220}{}{Ei, amigo, não se preocupe com os cassinos, venha brincar com o Monte.}
{221}{}{Looking to take a chance, pal? Best odds in New Reno! C'mon...}
{222}{}{You, pal. You look like a lucky guy, c'mon over.}
{223}{}{Anybody looking to play? Free mon-ay, free mon-ay.}
{224}{}{C'mon over and play. Just the other day, I guy won 50 chips off me, easy.}
{225}{}{Easy, just guess the Queen, red Queen, and you win. That easy.}
{226}{}{You allergic to easy money? Then get over here.}
{227}{}{Everybody's winning today... you want to be the next one?}
{228}{}{Casinos'll rip you off, rob you blind... Monte treats you right, gives you a fair chance.}
{229}{}{Looking to take a chance, lady? Best odds in New Reno! C'mon...}
{230}{}{You allergic to easy money, lady? Then get over here.}
{231}{}{You, lady. You look like a lucky gal, c'mon over.}
{232}{}{Yo, lady, don't bother with the casinos. Come play with Monte.}
{233}{}{O Monte não está aberto para jogos hoje, amigo; minhas malditas cartas sumiram.}
{234}{}{(O velho sorri e a pele ao redor dos olhos se enruga.) Quer brincar, amigo?}
{235}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{236}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{237}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, friend?}
{238}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{239}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{240}{}{Three-Card Monte's the name, and the game's the same as the name. Slap down 20 chips, and we'll get down to it.}
{241}{}{You cheater. You no play fair}
{242}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{243}{}{Uh, me flattered but me not want to get down to it now... byyyyye}
{244}{}{Desliga}
{245}{}{Let's play.}
{246}{}{Uh, get down to what?}
{247}{}{I'm familiar with the game. Let's play.}
{248}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{249}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{250}{}{Hoje não, valeu.}
{251}{}{Descer para o quê? O jogo, claro!}
{252}{}{See... (shows you three cards) ...one of these is a queen. I lay them face down, shuffle them, then you pick which one the queen is. If you're right, you win.}
{253}{}{That simple, pal.}
{254}{}{That simple, lady.}
{255}{}{I'm not playing with a cheater like you.}
{256}{}{Could you explain the rules again?}
{257}{}{Sounds simple enough. Let's play. Here's 20 chips.}
{258}{}{Hoje não, valeu.}
{260}{}{(Você entrega o dinheiro. Monte acena com a cabeça, mostra as cartas, depois as joga no chão e as embaralha por alguns segundos.)}
{261}{}{So... which one's the queen, pal?}
{262}{}{So... which one's the queen, lady?}
{263}{}{(You think it's the one on the left.)}
{264}{}{(You think it's the one in the middle.)}
{265}{}{(You think it's the one on the right.)}
{266}{}{(You don't know. The cards moved too fast.)}
{267}{}{Lucy leftie}
{268}{}{Middle of th'road}
{269}{}{Rightie tightie}
{270}{}{The one on the left.}
{271}{}{The one on the right.}
{272}{}{The one in the middle.}
{280}{}{(Monte turns over the card. It is the }
{281}{}{Sorry, pal, not this time, but you were CLOSE.}
{282}{}{Sorry, lady, not this time, but you were CLOSE.}
{283}{}{You sure do got the eye for it, though. Wanna try again?}
{284}{}{You cheater. You no play fair}
{285}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{286}{}{Nuh-uh Me no LIKE game BYYYYE}
{287}{}{I'm not playing with a cheater like you.}
{288}{}{Sure. Here's 20 chips.}
{289}{}{Não, obrigado.}
{300}{}{(Você entrega o dinheiro. Monte acena com a cabeça, mostra as cartas e as coloca no chão. Ao fazer, ele pega uma carta, tão rápido que você quase a perde. Ele então começa a embaralhar por alguns segundos.)}
{301}{}{So... which one's the queen, pal?}
{302}{}{So... which one's the queen, lady?}
{303}{}{You put it in sleevie weevie you no play fair}
{304}{}{Lucy leftie}
{305}{}{Middle of th'road}
{306}{}{Rightie tightie}
{307}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{308}{}{The one in your sleeve.}
{309}{}{The one on the left.}
{310}{}{The one on the right.}
{311}{}{The one in the middle.}
{320}{}{O que você disse, colega?}
{321}{}{WHAT did you say, lady?}
{322}{}{You accusing me of cheating?}
{323}{}{Uh-uh. Me KNOW you cheet}
{324}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{325}{}{Sim.}
{326}{}{Screw this. Keep the money, I'm outta here.}
{330}{}{Olha, eu não tenho tempo para perdedores bunda mole. Você paga seu dinheiro e arrisca,
 só. Se você quer JOGAR, tudo bem, mas se você só vai ficar com graça quando perder,
 então saia!}
{331}{}{ME BREAK YOU}
{332}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{333}{}{That's it. You're dead.}
{334}{}{All right, all right. I'm sorry. Here's 20 chips. Let's play again.}
{335}{}{Screw you. Keep the money, I'm outta here.}
{340}{}{(Você entrega o dinheiro. Monte acena com a cabeça, depois bate as cartas e as embaralha por alguns segundos.)}
{341}{}{So... which one's the queen, pal?}
{342}{}{So... which one's the queen, lady?}
{343}{}{(Monte's using his normal deck! You need to steal his other deck to complete the switch.)}
{344}{}{You put it in sleevie weevie you no play fair}
{345}{}{Uh... Lucy leftie}
{346}{}{Uh... Middle of th'road}
{347}{}{Uh... Rightie tightie}
{348}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{349}{}{The one in your sleeve.}
{350}{}{Uh, the one on the left.}
{351}{}{Uh, the one on the right.}
{352}{}{Uh, the one in the middle.}
{360}{}{(Você entrega o dinheiro. Monte acena com a cabeça, mostra as cartas, depois as joga no chão e as embaralha por alguns segundos.)}
{361}{}{(You hand over the cash. Monte looks uncomfortable.) Uh... all right... (Monte puts the cards on the ground and shuffles them.)}
{362}{}{So... which one's the queen, pal?}
{363}{}{So... which one's the queen, lady?}
{364}{}{(Monte's using the marked deck. Any pick is the right one.)}
{365}{}{Leftie! Leftie!}
{366}{}{Rightie! Rightie!}
{367}{}{Middlie! Middlie!}
{368}{}{Oh, I don't know... the one on the left.}
{369}{}{Hmmmm... maybe the one on the right?}
{370}{}{Gee, I'm not sure... I think it's the one in the middle.}
{375}{}{(Monte vira a carta. É a rainha de copas. O bixo ficou em choque.) Uh...? Heh. Eh...}
{376}{}{guess you win, pal.}
{377}{}{guess you win, lady.}
{378}{}{(He hands over the cash reluctantly.)}
{379}{}{Again! Again!}
{380}{}{Thanx me go now}
{381}{}{So we gonna play again or what? C'mon, Monte. I'm just getting started.}
{382}{}{Well, thanks, Monte. See you later.}
{385}{}{(Monte vira a carta. É a rainha de copas. Ele fica em choque.) Uh...? Eh... ah...}
{386}{}{guess you win, pal.}
{387}{}{guess you win, lady.}
{388}{}{That cleans me out, though... (Looks at you weakly) Anything else I could do for you?}
{389}{}{Nuttin. Me just wanted sum extra EXP. Bye. Bye.}
{390}{}{What have you GOT?}
{391}{}{Why don't you give me some information?}
{392}{}{Forget it, Monte. We'll call it even for today.}
{400}{}{(Parece aflito.) Eh... bem, eu tenho algo... mas vale MUITO mais do que você ganhou... ainda assim...}
{401}{}{Well? What is it?}
{402}{}{If it's worth more to you than dying on Golgotha because you welched on a debt, that's your problem. I'd think
 about it, if I were you.}
{404}{}{Eh... hmnnn... depende do que você quer saber.}
{405}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{406}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{407}{}{You know where my car is, Monte?}
{408}{}{Got anything you think I should know?}
{409}{}{Nevermind, Monte. We're even. See you later.}
{415}{}{Eh... bem... olhe, você não ouviu nada de mim, mas eu aposto no Renesco, aquele babaca que tem a farmácia no lado oeste.
 Não tenho certeza se ele vendeu para o garoto, mas ele sabe de alguma coisa. Isso é tudo que eu vou dizer.}
{416}{}{All right then, Monte. We're even.}
{420}{}{Eh... bem... (parece que ele tem uma luta interior) ...olha, você não ouviu isso de mim, mas se eu fosse
 você, daria uma olhada no porão do Desperado.}
{421}{}{All right then, Monte. We're even.}
{425}{}{(Aperta os olhos e se inclina) Eu perguntaria ao velho Jules na frente da cidade. Nada passa
 sem ele saber... e se aconteceu, então ele teria um dedo nisso, entendeu o que estou dizendo?}
{426}{}{All right then, Monte. We're even.}
{430}{}{Bem... conhece aquele tal Eldridge que dirige a New Reno Arms? Ele diz que faz upgrades em armas, mas nunca o
 vejo fazer nada da vida. Talvez seja bom dar uma olhada na casa dele... mas você não ouviu isso de mim.}
{431}{}{All right then, Monte. We're even.}
{435}{}{(Monte franze a testa quando te vê.) Olha, não vou fazer nenhum jogo hoje, certo? Saia.}
{436}{}{Can I buy that card you showed me before?}
{437}{}{I wanted some information...}
{438}{}{All right, Monte. I'll leave... for now.}
{440}{}{Não, não vou me livrar disso, esquece. É um item AUTENTICO do pré-guerra... um pedacinho da história. NEM VEM.}
{441}{}{You making me ANOTHER offer? Look, I told you I ain't selling it.}
{442}{}{How about a thousand chips? I got it with me. It's yours in exchange for that card.}
{443}{}{Not even for 750 chips?}
{444}{}{How about 500 chips?}
{445}{}{250 chips sound about right?}
{446}{}{OK. Eu tinha algumas outras perguntas...}
{447}{}{Nevermind then, Monte. I'm outta here.}
{450}{}{Está surdo? Essa quantia nem é suficiente para me interessar.}
{451}{}{How about I suggest another amount...?}
{452}{}{Eu tenho mais algumas perguntas...}
{453}{}{Nevermind then, Monte. I'm outta here.}
{460}{}{Bem, não é tão caro para mim. É seu, amigo. (Ele olha para a direita e para a esquerda, depois se abaixa e tira a
 bota. Ele torce o calcanhar e tira uma carta de baralho de dentro.) Aqui está. Tome conta disso.}
{461}{}{Eu tenho mais algumas perguntas...}
{462}{}{Thanks, Monte. Always a pleasure.}
{465}{}{(Carranca) O que eu digo depende do que você quer saber. E não será barato.}
{466}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{467}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{468}{}{You know where my car is, Monte?}
{469}{}{Got anything you think I should know?}
{470}{}{Nevermind then, Monte. I'm outta here.}
{475}{}{Não vou tocar nesse assunto da Gólgota. Vá dar uma passeada.}
{476}{}{Look, that subject's just bad news. Leave it alone, all right?}
{477}{}{You making me another offer? Look, I told you I AIN'T going talk about it.}
{478}{}{A thousand chips change your mind? I got it with me.}
{479}{}{Not even for 750 chips?}
{480}{}{How about 500 chips?}
{481}{}{250 chips sound about right?}
{482}{}{Uh... Golgotha?}
{483}{}{Eu tenho mais algumas perguntas...}
{484}{}{Nevermind then, Monte. I'm outta here.}
{490}{}{(Balança a cabeça.) De jeito nenhum. Falar sobre isso pode matar alguém, começando por mim. Esqueça.}
{491}{}{How about if I offered you this...}
{492}{}{Eu tenho mais algumas perguntas...}
{493}{}{Nevermind then, Monte. I'm outta here.}
{495}{}{Eh... bem... isso é um monte de fichas. (Lambe os lábios. Ele parece estar lutando uma batalha interna... mas dura pouco.) Olha, você não ouviu isso de mim...}
{496}{}{Understood. Go on.}
{500}{}{(Risos) Talvez eu tenha ouvido alguma coisa, talvez não. Diga um preço.}
{501}{}{All right... talk a price.}
{502}{}{How about a thousand chips? I got it with me.}
{503}{}{Not even for 750 chips?}
{504}{}{How about 500 chips?}
{505}{}{250 chips sound about right?}
{506}{}{Eu tenho mais algumas perguntas...}
{507}{}{Nevermind then, Monte. I'm outta here.}
{510}{}{Ah! Você não pode comprar um balde de mijo com isso. Esqueça.}
{511}{}{How about if I offered you this...}
{512}{}{Eu tenho mais algumas perguntas...}
{513}{}{Nevermind then, Monte. I'm outta here.}
{515}{}{Tá certo. (Sorri maliciosamente.) Olha, você não ouviu isso de mim, mas se eu fosse você, eu olharia o porão do Desperado na Virgin Street. Há muitos "ratos" lá, se você me entende.}
{516}{}{Eu tenho mais algumas perguntas...}
{517}{}{Entendi. Obrigado.}
{520}{}{(Encolhe os ombros) Talvez eu saiba algo sobre isso, talvez não. Me fale um preço e talvez eu tenha algo a dizer.}
{521}{}{All right... talk a price.}
{522}{}{How about a thousand chips? I got it with me.}
{523}{}{Not even for 750 chips?}
{524}{}{How about 500 chips?}
{525}{}{250 chips sound about right?}
{526}{}{Eu tenho mais algumas perguntas...}
{527}{}{Nevermind then, Monte. I'm outta here.}
{530}{}{(Aperta os olhos, se inclina) Por essa quantia, não sei de nada.}
{531}{}{How about if I offered you this...}
{532}{}{Eu tenho mais algumas perguntas...}
{533}{}{Nevermind then, Monte. I'm outta here.}
{535}{}{Isso mesmo... (cerra os olhos, se inclina) ...eu perguntaria ao velho Jules na frente da cidade.
 Nada passa por ele... e se aconteceu, então deve ter um dedo nele, entendeu o que eu disse?}
{536}{}{Eu tenho mais algumas perguntas...}
{537}{}{All right then, Monte. Thanks.}
{540}{}{(Dá de ombros) Eu ouço coisas, eu vejo coisas. Por 200 fichas, talvez você possa ouvir um pouco da minha experiência, entendeu o que eu disse?}
{541}{}{Here's 200 chips.}
{542}{}{I'll give you 150.}
{543}{}{100 chips or nothing.}
{544}{}{Eu tenho mais algumas perguntas...}
{545}{}{Nevermind then, Monte. I'm outta here.}
{550}{}{Você é surdo? EU DISSE 200 fichas, só com isso.}
{551}{}{All right. Here's 200 chips.}
{552}{}{Eu tenho mais algumas perguntas...}
{553}{}{Nevermind then, Monte. I'm outta here.}
{555}{}{Done. (Monte leans in) Well, know that guy Eldridge, runs New Reno Arms? He SAYS he does
 weapon upgrades, but I never see him do any work. You might want to check out his place... but you didn't hear that from me.}
{556}{}{Eu tenho mais algumas perguntas...}
{557}{}{Understood. Thanks, Monte.}
{560}{}{O cemitério ao sul da cidade. Fede até quase você perder a consciência, isso é certo.}
{561}{}{Oh... I see. Now, about the Wright kid...}
{562}{}{Forget the Wright kid. I had some other questions...}
{563}{}{All right then, Monte. Thanks.}
{565}{}{Minhas apostas são em Renesco, aquele velho fudido que gerencia a farmácia na zona
 oeste. Eu não tenho certeza se ele vendeu algo para o garoto, mas ele sabe de ALGUMA COISA. (Olha ao redor) Isso é tudo que vou dizer.}
{566}{}{Eu tenho mais algumas perguntas...}
{567}{}{All right then, Monte. Thanks.}
{570}{}{(Ele olha ao redor, depois se abaixa e tira a bota. Ele torce o calcanhar e tira um cartão... no cartão está um homem com
 um chapéu estranho, empunhando um porrete.) Interessado? São lembranças genuínas do pré-guerra.}
{571}{}{No, I already have enough inventory items... I'd rather have some information instead.}
{572}{}{Uh, sure. Why not? This'll settle things between us.}
{573}{}{Sorry pal, no chips, no game. Come back when you got more money.}
{574}{}{Sorry lady, no chips, no game. Come back when you got more money.}
{575}{}{Yeah, maybe next time then.}
{576}{}{You quickly swap Monte's deck of cards for the marked deck.}
{600}{}{spades}
{601}{}{hearts}
{602}{}{diamonds}
{603}{}{clubs}
{604}{}{dois}
{605}{}{três}
{606}{}{quatro}
{607}{}{cinco}
{608}{}{seis}
{609}{}{sete}
{610}{}{oito}
{611}{}{nove}
{612}{}{dez}
{613}{}{ de }
