{100}{}{Você vê o padre Tully.}
{150}{}{Você vê um homem idoso em vestes marrons e manchas vermelhas nas bochechas por causa do uísque. Ele parece um pouco instável.}
{151}{}{Você vê o padre Tully. Ele parece estar de ressaca. }
{200}{}{Eu sou muitobençoado.}
{201}{}{E as mulheres devem me cumprimentar com um beijo santo.}
{202}{}{Expulsarei o demônio de mim bebendo se for possível.}
{203}{}{Um verdadeiro sermão não tem palavras...}
{204}{}{Eu sinto o Todopoderoso em mim.}
{205}{}{Maldição, estou ficando sóbrio. Preciso de uma bebida.}
{206}{}{Por que o chão tá dando umas voltas...}
{207}{}{Uma garrafa de bebida vai me ajudar a falar em línguas.}
{208}{}{Um quinto de licor mataria esse diabo na minha cabeça.}
{209}{}{Oooh. Já tem uma hora desde a última vez que tomei um gole...}
{210}{}{Hora de absorver o espírito santo.}
{211}{}{Eu bebo em nome de tudo o que é sagrado.}
{220}{}{Quer saber o que a igreja acha sobre a felação?}
{221}{}{Pecado! Maldade! Eh... o que você vai fazer depois?}
{222}{}{Vadia! Prostituta! Puta! Ei... o que você vai fazer mais tarde?}
{225}{}{Quem é você? Te conheço? }
{226}{}{Saudaççções... o que o padre Tully pode fazer por você... }
{227}{}{Você venceu a Enclave como um... um... deus, né? Você é um herói.}
{228}{}{Eu rerói}
{229}{}{Eu vou}
{230}{}{Eu enfrentei a Enclave, sim. Eles começaram - e eu terminei. Mas não me entenda mal, padre. Sou apenas um
 homem tentando abrir caminho neste mundo implacável... Não sou um herói.}
{231}{}{Eu enfrentei a Enclave, sim. Eles começaram - e eu terminei. Mas não me entenda mal, padre. Sou apenas uma
 mulher tentando abrir caminho neste mundo implacável... Não sou um heroína.}
{232}{}{É melhor eu ir, padre. Fiquei feliz em sentir o seu cheiro... digo, em vê-lo.}
{235}{}{Você é um HERRRÓI. Eu tenho ago pra você. Não sei o que podia servir, mas imagino que você possa estar precisando.}
{236}{}{Eu pego}
{237}{}{Não preciso... eu quero ir lá fora}
{238}{}{Certo. Eu aceito o que você está dando, padre. Uh, bem, dentro dos limites da decência.}
{239}{}{Er... não, obrigado, padre. Eu realmente preciso ir.}
{240}{}{(Tully vai até um dos bancos, arranca uma tábua do assento e tira um livro de capa mole encardido.) Aqui está. É um
 pouco sujo, mas... (entrega para você.)}
{241}{}{Brigado}
{242}{}{Obrigado, padre. Acho.}
{245}{}{Você é um herói. Ocê merece. Não são os muitos jogadoress TERMINAM os joogoss, mas você foi e fez. Estou
 orgulhoso de você. Tooooda NEW RENO está orgulhosa de você.}
{246}{}{Brigado, padre. Tchaaau}
{247}{}{Obrigado, padre. Se cuida, tá ouvindo?}
{250}{}{Saudaççções, meu filho. O que o padre Tully pode fazer por você nessa... preciosa noite em Reno?}
{251}{}{Saudaçççõões, meu filho. O que o padre Tully pode fazer por você neste... bom dia em Reno?}
{252}{}{Hee-hee. Você fede chacaça. Você fede xixi}
{253}{}{Eu gosto do sol}
{254}{}{Noite bonita.}
{255}{}{Eh, na verdade é de dia, padre.}
{256}{}{Eh, na verdade é de noite, padre.}
{257}{}{Quem é você?}
{258}{}{Está bêbado?}
{259}{}{'Padre' Tully, eh? Você pode fazer divórcios?}
{261}{}{Olhe, eu trouxe um pouco de bebida, padre. Podemos conversar um momento...?}
{262}{}{Nada. Desculpe por atrapalhar.}
{270}{}{(Cheira seu suvaco e depois suas vestes.) Minha palavra, com certeza um cheiro forte, né? Maldição, eu ccheiro
 como um alambique! Melhor me limpar antes que Sssenhora Wright me ache...}
{271}{}{Tchau homem mijo}
{275}{}{Inferno, devo ter dormido demais... teria notado de outra forma... o que diabos eu estava dizendo?}
{290}{}{Padre Tully, a seu serviço. Sou o conselheiro espiritual do bom p... bem, do povo de New Reno.}
{291}{}{Estar bêbado é a única maneira de conseguir isso?}
{292}{}{Eu tenho algumas perguntas sobre New Reno...}
{295}{}{Entendo. Bem, obrigado por conversar comigo.}
{300}{}{Certamente que nãão! No PASSADO, eu erra conhecido por me entregar aos espritos, mas União da Temperança me ajudou a quebrar esse hábito imundo!}
{301}{}{União da Tempe --?}
{302}{}{Oh. eu não --}
{303}{}{Quebrar o --?}
{305}{}{União da Temprança, Sinhoraaa. Wright... a mesma pessoa 
tentando limpar New Reeno. Fez um bom trabalho comigo.}
{306}{}{Claro que sim. Eu tenho algumas outras perguntas...}
{315}{}{Preguntas? Não posso falar que sei muitas cosass. Mas podi falr.}
{316}{}{Você já ouviu falar do Vault 13?}
{317}{}{Estou aqui porque procuro minha tribo, eles foram sequestrados da minha aldeia.}
{318}{}{Você não sabe como consertar um petroleiro, não é?}
{319}{}{Você já ouviu falar de algo chamado Kit de Criação do Jardim do Éden?}
{320}{}{Você pode me falar um pouco sobre New Reno?}
{323}{}{Talvez eu volte quando você estiver um pouco mais sóbrio.}
{325}{}{Bem... Reno... é... bem, é... bem... hum, então...}
{326}{}{Um kit de Crianção do Jardem do Eden? Não. Não posso dizer que já ouvi falar di um. Então, hum...}
{327}{}{Vault Treezee? Não faço idea... bem, quero dizer, tem Vault CITY pra nordeste. Isso é o que você está procurando, talvez? Hummm... digamos, hum...}
{328}{}{Quer dizer escreavistass? Ouvi falaar onde eles compram alguuns estoques... hum... digamos...}
{329}{}{Petrolero? Daquees negocios que flutua...? Não sei muito sobre isso... hum... diga...}
{330}{}{Sim...?}
{335}{}{Me perdoe por perguntar, você poor acasu tem uma garrrafa com você? Eu preciso de djinheiro para meus serviços... e, eh, minha garganta ta meio seca.}
{336}{}{Certo, tenho aqui.}
{337}{}{Não tenho nenhuma, desculpe.}
{338}{}{Eu poderia pegar algum, se você quiser.}
{440}{}{Agora estou certo no caminhu, graaçças a Sinhroa Wright... que Deus a abençoe. Estou limpo há quase, um... uh, mês. Ou é por
 uma ssemana? Ah, Deus, eu não sei. }
{441}{}{Uma semana deve ser difícil. Olha, eu tenho outras perguntas para você...}
{442}{}{Está sóbrio, hein? Quantos dedos eu tenho aqui?}
{443}{}{União da Temperança?}
{444}{}{Senhora Wright?}
{445}{}{Talvez eu volte quando você estiver sóbrio.}
{450}{}{(Tully vai tropeçando até a caixa de doação ao lado do altar e vasculha dentro.) }
{451}{}{Uh... hummm. (Suas mãos saem vazias.) Receio não ter nenhuma t-tampa aqui.}
{452}{}{Hmnnn. Aqui está... (Ele joga algumas tampas em sua mão.) Abenççooados sejam os pobres. Vá gastar em nome de tuuudo o que é sragado.}
{453}{}{Obrigado mesmo assim, padre. Vou ver se consigo arranjar algum licor.}
{454}{}{Obrigado, pai. Em breve estarei de volta com algum licor.}
{460}{}{Não dê dois segundo para 'sua esposa f-filha'... não é de admirar que cresceram tuuudo selvazens.
 Heh-heh... tudo que saem no confessionário, sabe...}
{461}{}{Ah, e o que o Sr. Bishop diz no confessionário?}
{462}{}{Ah, e o que a Sra. Bishop diz no confessionário?}
{463}{}{O que a Sra. Bishop diz no confessionário? Ela não fala de mim, fala... Quer dizer, porque não há nada para
 falar. Tudo mentira.}
{464}{}{Ah, e o que a filha de Bishop diz no confessionário?}
{465}{}{Uh, o que a filha de Bishop diz no confessionário? Nada sobre mim, eu... er, nada de ruim, eu espero.}
{466}{}{Eu imagino. Posso lhe fazer mais algumas perguntas, padre?}
{470}{}{Ná, Vault City disse para eles ENFIAREM no CU. Então... não demora muito, Vault City começa a ser invadida.
 Rápido. Foorte. E toda hora, ali aparece Bischop, dizend-do a eles: "EU PODERIA AJUDAR, SE vocês se juntar a New Reno".}
{471}{}{Hmmm. O que mais você pode me dizer sobre os Bishops?}
{472}{}{Então, chantagem é o jogo de Bishop? Alguns ataques, algumas mortes e Vault City pode estar pronta para ser amiga de
 New Reno. Não muito sutil, mas bem eficaz. O que mais você pode me dizer sobre os Bishops?}
{473}{}{Me parece uma tática estranha... Quero dizer, é muito mais provável que Vault City tente conseguir ajuda de outros
 antes de ceder à pressão de Bishop. O que mais você pode me dizer sobre os Bishops?}
{474}{}{Isso parece uma tática estranha... quero dizer, é muito mais provável que Vault City tente conseguir ajuda de outros...
 tipo a NCR, por exemplo... antes de ceder à pressão de Bishop. O que mais você pode me dizer sobre os Bishops?}
{475}{}{Posso te fazer mais algumas perguntas, padre?}
{476}{}{Muito interessante, padre. Obrigado por conversar comigo.}
{480}{}{(Olha para sua mão). S-seis? Ou talvez treeis…}
{481}{}{Muito bom. Ambos estão certos. Olha, eu tenho algumas perguntas...}
{482}{}{Você pode fazer divórcios?}
{484}{}{Talvez eu volte quando você ficar sóbrio.}
{490}{}{Que o diabo me carregue, claaro que posso! Reno era a capital do d-divorcio bem antes da tragedia. }
{491}{}{Quem essa fudida aí que você quer se livrar? }
{492}{}{Quem esse bunda mole que voce quer se livrar? }
{493}{}{(Parece confuso por um momento enquanto olha para vocês dois. Então ele dá de ombros e bebe.)}
{494}{}{Pode apostar. Podemos começar agora?}
{495}{}{Talvez... mas ainda estou pensando nisso. Eu pretendo estar de volta, no entanto.}
{500}{}{Bem, parece que p-perdi meu livo dos sermoes com o potrocolo oficial...}
{501}{}{Foda-se o livro. Tome um pouco de licor. Você pode simplesmente inventar alguma coisa?}
{502}{}{Tome um pouco de licor. Você pode simplesmente inventar alguma coisa?}
{503}{}{Foda-se o livro. Se eu te trouxer mais licor, acha que poderia inventar alguma coisa?}
{504}{}{Se eu te trouxer mais licor, acha que poderia inventar alguma coisa?}
{505}{}{Ah, sim. Talvez o livro apareça.}
{510}{}{Bem, isso seria certu... so se o licor fosse muuuuito bom.}
{511}{}{Tranquilo. Eu voltarei.}
{512}{}{Bem, eu posso ir buscar algo. Mas vou precisar de algumas tampas primeiro.}
{520}{}{Certo! Deixe um começar a fazer isso agora... (Ele bebe a garrafa com uma velocidade assustadora.)... então, subam no altar voces ai...}
{521}{}{Mais um passo...}
{530}{}{Oh. Tudo bem entao. Nao custa perguntar... entao... uh... Desculpe, quem e voce mesmo?}
{531}{}{Sabe, eu poderia pegar um pouco de licor para você, se você quiser, claro.}
{540}{}{Ora, boa ideia! Que você seja tres vezes abeençoaaado! Eh... Acontece que eu conheço um LUGAR no lado lest, naantiga
 estaçço de trem, que vende o tipo deagua benta que eu preciso.}
{541}{}{OK, eu vou pegar um pouco. Volto logo.}
{542}{}{OK, eu vou pegar algum. Mas vou precisar de algumas tampas pra comprar.}
{550}{}{Claaro, caro... tampas, umas tampis... onde guardo as tampas... (Seus olhos se voltam para a caixa de doações ao lado do altar.) Ah! Nem sei por que não pensei nisso antes... ispera um minuto...}
{551}{}{Espera pacientemente que ele faça a retirada da caixa de doações.}
{552}{}{Uh, deixa pra lá, padre. Essa é por minha conta.}
{560}{}{(Padre Tully olha para a... agora... garrafa vazia em suas mãos.) Diga, não quero me meter, amigo: você teria outra garrafi
 desssa boa safra cum você? Essa conversera está me deixando cum sede.}
{570}{}{Muito obrigaaaado! (Pega a garrafa e toma um gole.) Ahhh... desculpa... que que eu tava falano mesmo?}
{571}{}{Eh... bem, a-agora, com certeza! (Pega a garrafa.) Eu num costumo toca nessas coisaas, sabe... (Toma um gole.)... ahhhh... hum, desculpe, que que eu tava falano mesmo?}
{572}{}{Eh... oh belezera! (Toma a garrafa.) Eu nurmalmente não tomo tanto assim, sabe... (Toma um longo gole.) Ahhhh... Epa, que que eu tava falano mesmo?}
{573}{}{Você estava falando sobre a família Bishop.}
{574}{}{Você estava falando sobre a família Wright.}
{575}{}{Você estava falando sobre a família Mordino.}
{576}{}{Você estava falando sobre a família Salvatore.}
{578}{}{Você estava falando sobre a morte de Richard Wright.}
{579}{}{Voltarei quando voce estiver sóbrio.}
{590}{}{Eh? Os Bishops, certo... sedentos esses sao, está nu sangue. O problema é que o veio John Bischop esta tao preocupado
 em tomar tudo que não cuida mais dus negocios de c-casa.}
{591}{}{Negócios em casa?}
{600}{}{Bem, não muito, mas ouvi c-coisa por FORA no confessionario sobre velho Bishop. Diabo astuto. É corajooso, esse
 tem coraji de sobra. Imagino que ele ta por tras dus saqueadores em Vault City... você ouviu falar deles?}
{601}{}{Não.}
{602}{}{Sim.}
{603}{}{Padre, fale mais baixo. Esse tipo de conversa pode te matar por aqui...}
{604}{}{Olha, talvez eu volte quando voce estiver sobrio.}
{610}{}{(Ignora você.) Veja, uns meis atras, o nosso Bishop envia uma caravana para Vault City, SUGERINDO um casamento por
 cunveniencia entre Vault City e New Reno.}
{611}{}{Eles chegaram a um acordo?}
{612}{}{Acredito que eles não chegaram a um acordo, certo?}
{620}{}{Principarmente o que si espera de uma esposa negligenciada cum corpao que consegui f-fazer ate cego voltar a ve.
 Principalmente adulteeerio. Digo, se vio us peitao dela? Rapaz do ceu!}
{621}{}{Uh... o que mais pode me dizer sobre os bispos, padre?}
{622}{}{Sim, ela tem uns meloes. Quero dizer... eu ouvi sobre. Uh, o que mais você pode me dizer sobre os Bishops, padre?}
{623}{}{Er... ela não disse com quem ela era adúltera, disse, padre?}
{625}{}{De acordo. Bem, obrigado por falar comigo.}
{630}{}{Oooh, doce Angela? Digo, pequena diabinha! Essa m-menina tem deve ter u capeta nas carça. Sempre vagand-do
 por ai, durmindo com qualque um e se intupindo de Jet...}
{631}{}{Eh, dormindo com alguém? Ele disse com quem?}
{632}{}{Jet?}
{633}{}{Isso soa como uma boa família. O que mais você pode me dizer sobre os Bishops?}
{634}{}{Eu tenho algumas outras perguntas, padre...}
{635}{}{Acho que é só coisa de criança. Bem, obrigado por falar comigo.}
{640}{}{Quem? Ah, claro que digo, mas o ceerto seria dizer com quem ela NÃO feiz isso. Ela diz a todos sobre isso. Ei... qual é o seu
 nome memo?}
{641}{}{Uh, nada... o que mais você pode me dizer sobre os Bishops, padre?}
{642}{}{Eu? Monges celibatários como eu não têm nomes. Diga, eu tenho outras perguntas, padre...}
{643}{}{Eu? As freiras celibatárias como eu não têm nomes. Diga, eu tenho outras perguntas, padre...}
{644}{}{Falo com você mais tarde, padre.}
{650}{}{Sangue do diabo! Maldade! Secreça suja da propria teta do mal!}
{651}{}{Então... você não gosta de Jet?}
{652}{}{Uh, sim, teta do mal. Posso te fazer mais algumas perguntas, padre?}
{653}{}{Tudo bem então. Falo com você mais tarde, padre.}
{660}{}{That drug'll be th' death of us. Can't think of another drug...(Drinks, belches.)...that doess more damage than Jet... Killz
 th' mind and th' body. Damn Mordinos...}
{661}{}{What was that about the Mordinos?}
{663}{}{Uh, I'd nurse that bottle a little longer next time, Father. Talk to you later.}
{670}{}{Heh-heh! Wright, eh? (Smiles, wiggles eyebrows.) Lemme tell you a lit-tle sumthin' about th' WRIGHTS... they're a split
 bunch of horny drunks and stonefast puritans, they are!}
{671}{}{Oh, really?}
{672}{}{I think I've heard enough, Father. Thanks for talking with me.}
{680}{}{Those Wrights just keep squeezing out kids... oul' Orville Wright must wanna re-pop-ulate th' world. Hope Missus Wright
 can take th' strain. Heh-heh. An' the thingz they SAY in th' confessional...}
{681}{}{Oh, really? What does Missus Wright say in the confessional?}
{682}{}{Oh, really? What does ol' ORVILLE Wright say in the confessional?}
{683}{}{What does the Wright Family control in New Reno?}
{684}{}{Oh, I bet it's really juicy stuff. Maybe we can talk about it some other time.}
{690}{}{ETHYL Wright? That blesst woman! Keeps me off th' drink, an' on th' straight n' narrow. (Takes a swig.) She can drive th' sin
 outta you, she can... uh, but... what in hell waz I saying?}
{691}{}{About Missus Wright in the confessional...}
{692}{}{Estava falando com a família Wright...}
{693}{}{Esqueça. Eu tenho outras perguntas…}
{694}{}{Nothing much more, I think. Thanks for talking with me.}
{700}{}{Oh, right, right. Well, uh, in th' confessional, she ain't got much t'say. Mostly guilt 'bout stepping on bugs... or 'bout
 enjoying sex with her hubbie too much. Heh-heh. (Takes a swig.) I looove guilt.}
{701}{}{Eu tenho algumas perguntas sobre os Wrights...}
{702}{}{Entendo. Eu tenho outras perguntas...}
{703}{}{It shows. Thanks for talking with me.}
{710}{}{Oul' Orville? Well, he's got a lotta guilt on his shoulders. See, he promised th' Missus he'd quit the alcohol biz, but
 he has a secret still in th' train station behind th' house! She'll beat him uglier than he is if she finds it...}
{711}{}{Heh-heh, herez the funny bit... y'see, ol Mr. Wright promised the Missus he'd quit the alcohol biz, but he has a secret
 still in the train station behind the house! Ha! She'll beat him uglier than he is if she finds it...}
{712}{}{Me conte sobre a senhora Wright...}
{713}{}{Me conte mais sobre os Wrights...}
{715}{}{A secret still in the train station behind the house, huh? Very interesting, Father. Thanks for the info.}
{720}{}{Nuthin'! (Takes a drink.) They're the weakest of th' families, cuz they only brew alke-hol. Barely turn a cent, they do.
 Th' other families buy alke-hol offa them mostly outta pity.}
{721}{}{Where does this alcohol come from?}
{722}{}{Interessante. Me diga mais sobre os Wrights...}
{724}{}{Very interesting, Father. Thanks for the info.}
{730}{}{Th'Mordinos? (Holds up three fingers.) Therez two o' them. (Holds hand up high.) Big Jeezus... (Holds hand down low.) ...an' Leetle
 Jeezus. The Father n' the Son. They control th' drugs and the whoa-men in Reno.}
{731}{}{Tell me about Big Jesus.}
{732}{}{Tell me about Little Jesus.}
{733}{}{So they are the source of drugs and control most of the whores in New Reno?}
{740}{}{Jesus? He's one bad muthuh...(Takes a swig, swishes it around in cheeks.) Deals in slavez, Jet, n' whores. Only person
 worse'n him is hiz filthy son.}
{741}{}{His son?}
{742}{}{So Jesus Mordino Senior controls most of the drugs and whores in New Reno?}
{743}{}{Great family. Can I ask you some other questions, Father?}
{744}{}{Like father, like son. Well, thanks for talking with me, Father.}
{750}{}{Leetle Jezus? Bastard! He's like a prairie tick, sucking blood from hiz Dad's work. Be trouble for alla Reno if he took
 charge. Couldn't hold it toogether, drugz, whorez... all fall down.}
{752}{}{The Mordinos are the source of drugs and most of the whores in New Reno?}
{754}{}{Just like you in a few seconds. Well, thanks for talking with me.}
{760}{}{(Tully stares at you.) }
{761}{}{Yesss... (Smiles, licks lips.) ...whoresss... (Begins stroking neck of the bottle.)}
{762}{}{Uh, Father? About the drugs?}
{763}{}{I think I better go. Thanks for talking with me, Father.}
{770}{}{Eh? Drugz... yes, the drugs. Jet. Filthy Jet. Do horrible thingz with it, horrible... Redding... the Stables. (Takes a swig.) All fer gold...}
{772}{}{What about Redding?}
{773}{}{What about the Stables?}
{775}{}{Interesting. Thanks for talking with me, Father.}
{780}{}{(Makes a walking motion with his two fingers.) Jet leavez town, goez ta Redding. Gold leavez Redding, goez to Mordino.
 (Takes a swig.) Miners die, Mordinos lie.}
{782}{}{What were you saying about the Stables?}
{784}{}{So the Mordinos are selling Jet to Redding, huh? Interesting. Thanks, Father.}
{790}{}{Mordinos havva... farm... ousside of town. Keep slaves there. Test... Jet... on them. Killz them in drovez. (Shudders.) Only th' Mordinos
 know where th' Stables are.}
{792}{}{What were you saying about Redding?}
{794}{}{The Mordinos are testing Jet on slaves, huh? Interesting. Thanks, Father.}
{800}{}{I wuz talking 'bout the Salvatores? (Blinks, shrugs, then drinks.) Can't imagine what I was saying. Family's as silent as
 death. An' you don't wanna cross 'em, either... know why?}
{803}{}{Don't really need to know why right now, Father. Can I ask you some other questions?}
{804}{}{Olha, talvez eu volte quando voce estiver sobrio.}
{810}{}{(Lumbers on drunkenly.) Cuz they got weapons like fires from heaven, weapons no one's ever SEEN before in New Reno or
 nowhere. Shoot beams of light, cut a man in two, leave him twitching in the dust.}
{811}{}{Shoot beams of light?}
{812}{}{Shoot beams of light? You mean laser weapons?}
{814}{}{Wow... maybe I should try and get a hold of one. Well, thanks for talking with me.}
{820}{}{Thaz what I heard them call them... lay-sers... but ta me, those weapons are the devil's own, foul lightbringers, tools
 meant for nuthin but death!}
{821}{}{Yes, of course, Father. Tools of the devil and all that. What do the other families think of these 'lightbringers?'}
{823}{}{Tools of the devil, huh? Maybe I should try and get a hold of one. Well, thanks for talking with me.}
{830}{}{One of them lightbringers can kill a dozen men... Other families useta fight with th' Salvatores, but now no one messes
 with 'em. Itz a peace of sorts... good as long azzit holds out, I s'pose.}
{831}{}{Who's in charge of the Salvatores, Father?}
{833}{}{I suppose. Well, thanks for talking with me, Father.}
{840}{}{Louie... LOUIS... Salvatore runz th' show. (Drains bottle, coughs slightly.) Cripple. Needz an oxygen tank ta keep breathin'... his
 lungs are messed up. Stays in th' top floor of his establishment, never comes out.}
{841}{}{Interesting. Can I ask you some other questions, Father?}
{842}{}{Hmmmm. Tank of oxygen, huh? Interesting. Well, thanks for talking with me, Father.}
{850}{}{That poor boy... Jet took him from his family, it did. That damnable stuff! Worst mind poison ever made...}
{852}{}{Do you know where Richard got the Jet that killed him?}
{853}{}{Eu tenho mais algumas perguntas...}
{854}{}{I see. Thanks for talking with me, Father.}
{860}{}{He coulda gotten it from anyone in New Reno! There's a pharmacy jest cross th' street run by a drug dealer, and if
 he's not selling, stop an' ask anyone on th' street! Damn Jet!}
{862}{}{The pharmacy across the street? I'll check it out. Thanks for talking with me, Father.}
{957}{}{Tudo bem, es-escuta...}
{958}{}{::Takes a drink::}
{959}{}{::Keeps drinking, drains bottle::}
{960}{}{...by the power divested in me, I divorce ye.}
{961}{}{You may now kick the bride. Groom. Watever.}
{962}{}{::Makes a sweeping motion::}
{963}{}{Ughhhhh}
{964}{}{Zzzzsnorezzzzz}
{967}{}{Zzzzsnorezzzzz}
{968}{}{Oh, stop Missus Wright, stop... sznnzzzz}
{969}{}{Zzzstop, Missuz Wright, ah'm a man of th' chursh}
{970}{}{Wickednezz... zzz... sin... zzzz... so musch fun}
{971}{}{Of coursh ah've been zzzober}
{1000}{}{Oh bless you my... *BLEEECHH*}
{1001}{}{Drank too damn much of that blood of... OH CHRIST, *HUUUURRRRRRLLLL*.}
{1002}{}{Oh God, *ELCHHHH*}
{1003}{}{Oh Jesus, Mary, and Joseph, I'm never drinking that much again.}
{1004}{}{I better get up early and go to confession.}
{1005}{}{Maybe I'll just lay down for a little while.}
