{100}{}{Você vê a linda Nikki.}
{125}{}{Você vê um dos crupiês do cassino.}
{150}{}{Você vê a linda Nikki.}
{160}{}{Você vê a linda Nikki. Ela gesticula para que você venha brincar.}
{170}{}{Você vê um dos crupiês do cassino.}
{180}{}{Você vê uma das crupiês do cassino. Ela gesticula para que você venha brincar.}
{200}{}{::Assobios::}
{210}{}{Hello, [MM]. Can I help you with... anything?}
{220}{}{Parece que este já está jogando com a vida.}
{230}{}{Ei, músculos. Você quer gastar algumas tampas?}
{250}{}{Olá, estrela. Você quer gastar algumas tampas?}
{270}{}{Ei, querida. Você quer gastar algumas tampas?}
{290}{}{Bem, você está louco para entrar aqui, mas… faça suas apostas. A aposta mínima é de 5 tampas. Faça suas apostas…}
{310}{}{Uh, very well, sir. Come back soon.}
{320}{}{Very well, sir. Come back soon.}
{330}{}{Sorry, sir. Better luck next time.}
{340}{}{Winner! Well done, sir!}
{350}{}{Winner! You've doubled your money! Well done, sir!}
{360}{}{Winner! You've tripled your money! Luck is in the house tonight! Well done, sir!}
{370}{}{What do you want now? You here to waste my time, or you gonna place a bet?}
{380}{}{Yeah, I heard he's DEAD. That what you want to hear, killer?! Huh?! Now you gonna place a bet or bullshit me some more?}
{390}{}{Then that's a bet you'd LOSE, sweetheart, but if you're as stupid as you are ugly, you'd probably bet anyway. I ain't
 seen that bum since he conned Mr. Salvatore.}
{400}{}{Sweetheart, I TOLD you that I don't know where he is. Now, look, I'm WORKING here, so go back to whatever rock you --}
{410}{}{You touch me, and Mr. Salvatore will skin you alive.}
{420}{}{Do que você está falando?}
{430}{}{Look, LIKE I SAID, I don't know where he is. But *maybe* I heard he used to have a room at the Desperado. You might find
 something there. Now, if you don't mind, I got to get back to work.}
{440}{}{Look, I just STARTED working here, and I can't recognize every card counter and two-bit cheat that walks in.
 I gotta pretty good line on shitheads like you, though.}
{450}{}{Yeah, you take enough Jet, and everything seems suspicious, don't it?}
{460}{}{You get the hell outta here right now. I ain't got nothing else to say to you.}
{470}{}{You talk smooth... but so do snakes. MAYBE I know where Lloyd is, MAYBE I don't. You got 500 chips?}
{480}{}{COULD be that Lloyd still has my take, and I ain't sure he's gonna give it to me. So COULD be that - for 500 chips - I
 COULD tell you where his lying ass is hanging out.}
{490}{}{(Pockets the money) Check the boiler room in the basement of the Desperado. That's where the son of a bitch was
 going to run if things got hot.}
{500}{}{Would you get outta here?! People see us talking like this, then THEY'RE gonna talk. Understand?}
{510}{}{Go to hell, then! I ain't got nothing else to say to you, EVER.}
