{100}{}{Você vê a linda Nikki.}
{125}{}{Você vê um dos crupiês do cassino.}
{150}{}{Você vê a linda Nikki.}
{151}{}{You see Darlin' Nikki. She winks at you.}
{152}{}{Você vê a linda Nikki. Ela gesticula para que você venha brincar.}
{153}{}{You see Darlin' Nikki. Mason was right about her ass.}
{154}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{155}{}{You see Darlin' Nikki. Mason was right about her ass.}
{156}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{160}{}{Você vê a linda Nikki. Ela gesticula para que você venha brincar.}
{161}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{162}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{170}{}{Você vê um dos crupiês do cassino.}
{171}{}{Você vê uma das crupiês do cassino. Ela pisca para você.}
{172}{}{Você vê uma das crupiês do cassino. Ela gesticula para que você venha brincar.}
{173}{}{Você vê uma das crupiês do cassino. Ela tem um monumental par de coxas.}
{174}{}{Você vê uma das crupiês do cassino. Seu vestido mal cobre seu corpo.}
{175}{}{Você vê uma das crupiês do cassino. Ela é muito cheirosa.}
{180}{}{Você vê uma das crupiês do cassino. Ela gesticula para que você venha brincar.}
{181}{}{Você vê uma das crupiês do cassino. Seu vestido mal cobre seu corpo.}
{182}{}{Você vê uma das crupiês do cassino. Seu vestido mal cobre seu corpo.}
{183}{}{Você vê uma das crupiês do cassino. Ela gesticula para que você venha brincar.}
{200}{}{::Assobios::}
{201}{}{::Palmas::}
{202}{}{::Assobios::}
{203}{}{! Bem-vindo ao cassino, herói!}
{204}{}{Thought you'd forgotten about us while you were saving the world.}
{210}{}{Olá, }
{211}{}{Se precisar de companhia mais tarde...}
{212}{}{Hey, you...(winks)...you looking to gamble?}
{213}{}{Ele parece tão... (arrepios) perigoso.}
{214}{}{Bem vindo ao cassino, }
{215}{}{Fale bem de mim pro chefe, beleza?}
{216}{}{Olá, madame. Se eu puder ajudar em algo é só me dizer.}
{217}{}{Quer jogar, senhorita?}
{218}{}{Ela parece tão... (arrepios) perigosa.}
{220}{}{Parece que este já está jogando com a vida.}
{221}{}{Uh, eu acho que ele entrou no cassino errado...}
{222}{}{Se ele não sair antes que os rapazes o vejam...}
{223}{}{Oh-oh. Problema...}
{224}{}{Parece que já esta jogando com a vida.}
{225}{}{Uh, eu acho que ela entrou no cassino errado...}
{226}{}{Se ela não sair antes que os rapazes a vejam...}
{230}{}{Ei, músculos. Você quer gastar algumas tampas?}
{231}{}{Hey, champ...(winks)...you looking to gamble?}
{232}{}{Hey, champ...(smiles)...wanna take a chance?}
{233}{}{Se precisar de companhia mais tarde...}
{234}{}{Me pergunto se eu deveria falar com ele...}
{235}{}{Ei, }
{236}{}{Se você quer ganhar algumas tampas, veio ao lugar certo.}
{237}{}{Best casino in New Reno. In the WORLD, even.}
{238}{}{Dona Sorte está em casa esta noite... Somente vencedores!}
{239}{}{Adiante, }
{240}{}{Precisa de outra bebida?}
{241}{}{Bem vindo ao cassino, }
{242}{}{Olá, }
{243}{}{Com certeza quer jogar, }
{244}{}{Bem vindo ao cassino, }
{250}{}{Olá, estrela. Você quer gastar algumas tampas?}
{251}{}{Ei, }
{252}{}{Ei, }
{253}{}{Se você está querendo ganhar algumas tampas }
{254}{}{Best casino in New Reno. In the WORLD, even.}
{255}{}{Dona Sorte está em casa esta noite... Somente vencedores!}
{266}{}{Adiante, }
{267}{}{Precisa de outra bebida?}
{268}{}{Bem vindo ao cassino, }
{269}{}{Hey there, Mrs. Movie Star. Looking to spend a paycheck?}
{270}{}{Ei, querida. Você quer gastar algumas tampas?}
{271}{}{Hey, sweetie...(winks)...you looking to gamble?}
{272}{}{Hey, sweetie...(smiles)...wanna take a chance?}
{273}{}{Se você quer ganhar algumas tampas, veio ao lugar certo.}
{274}{}{Best casino in New Reno. In the WORLD, even.}
{275}{}{Dona Sorte está em casa esta noite... Somente vencedores!}
{276}{}{Vamos lá, ganhe algumas tampas.}
{277}{}{Precisa de outra bebida, docinho?}
{278}{}{Bem vindo ao cassino, docinho.}
{279}{}{Essa mesa é grátis se você quiser jogar...}
{280}{}{Ei, docinho. Você quer gastar algumas fichas?}
{281}{}{Quer jogar, docinho?}
{282}{}{Bem vindo ao cassino, docinho.}
{290}{}{Bem, você está louco para entrar aqui, mas… faça suas apostas. A aposta mínima é de 5 tampas. Faça suas apostas…}
{291}{}{Um... place your bets... minimum bet 5 chips. Place your bets...}
{292}{}{Place your bet, sir. Minimum bet 5 chips. Place your bets...}
{293}{}{Place your bet, ma'am. Minimum bet 5 chips. Place your bets...}
{294}{}{Place your bets, minimum bet 5 chips. Place your bets...}
{295}{}{Eu meior que oce}
{296}{}{Eu jogo minha calça}
{297}{}{What this game? Can you bet Gecko skin? Me got geck... ooooh... pretty lights over there!}
{298}{}{Bet 5 chips?}
{299}{}{Bet 15 chips?}
{300}{}{Bet 25 chips?}
{301}{}{Bet 50 chips?}
{302}{}{You Nikki?}
{303}{}{How you doing, Nikki?}
{304}{}{Whoa, too rich for my blood. I'm outta here.}
{305}{}{Sem apostas hoje, obrigado.}
{310}{}{Muito bem, senhor. Volte logo.}
{311}{}{Muito bem, senhora. Volte logo.}
{312}{}{Hum… Ouvi dizer que estão dando cérebros lá atrás. Talvez você devesse dar uma olhada.}
{313}{}{Tchaaaaau}
{314}{}{Diaaaaa. }
{315}{}{Uh... brains... what them?}
{320}{}{Muito bem, senhor. Volte logo.}
{321}{}{Muito bem, senhora. Volte logo.}
{322}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{323}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{324}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{325}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{326}{}{Eu vou, obrigado.}
{327}{}{Maybe so, but at least *I* don't live here.}
{330}{}{Desculpe, senhor. Mais sorte da próxima vez.}
{331}{}{Desculpe, senhora. Mais sorte da próxima vez.}
{332}{}{Desculpe, mais sorte da próxima vez.}
{333}{}{You have [C] chips. Keep playing?}
{334}{}{Liga-o por um dia.}
{335}{}{Isso que é noite.}
{340}{}{Vencedor! Muito bem, senhor!}
{341}{}{Winner! Well done, ma'am!}
{342}{}{Winner!}
{343}{}{You have [C] chips. Keep playing?}
{344}{}{Liga-o por um dia.}
{345}{}{Isso que é noite.}
{350}{}{Vencedor! Você dobrou seu dinheiro! Muito bem, senhor!}
{351}{}{Vencedora! Você dobrou seu dinheiro! Muito bem, senhora!}
{352}{}{Vencedor! Você dobrou seu dinheiro!}
{353}{}{You have [C] chips. Keep playing?}
{354}{}{Liga-o por um dia.}
{355}{}{Isso que é noite.}
{360}{}{Vencedor! Você triplicou seu dinheiro! A sorte está na casa esta noite! Muito bem, senhor!}
{361}{}{Vencedor! Você triplicou seu dinheiro! A sorte está em casa esta noite! Muito bem, senhora!}
{362}{}{Vencedor! Você triplicou seu dinheiro!}
{363}{}{You have [C] chips. Keep playing?}
{364}{}{Liga-o por um dia.}
{365}{}{Isso que é noite.}
{370}{}{O que você quer agora? Está aqui para me fazer perder tempo, ou vai fazer uma aposta?}
{371}{}{I'm whoever you WANT me to be, sweetheart. Now, you gonna place a bet?}
{372}{}{I'm whoever you WANT me to be, girlfriend. Now, you gonna place a bet?}
{373}{}{Place a bet.}
{374}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{375}{}{Yeah, I'm betting you and Pretty Boy Lloyd were both stealing money from Mr. Salvatore. Hard to believe you
 didn't notice him cheating all those times.}
{376}{}{Você conhece alguém chamado Lloyd Bonitão?}
{377}{}{We'll talk later, Nikki.}
{380}{}{Sim, ouvi dizer que ele está MORTO. É isso que você quer ouvir, seu assassino?! Huh?! Agora você vai fazer uma aposta continuar com suas besteiras?}
{381}{}{Nope. You gonna place a bet?}
{382}{}{Place a bet.}
{383}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{384}{}{Yeah, I'm betting you and Pretty Boy Lloyd were both stealing money from Mr. Salvatore. Hard to believe you didn't notice
 Lloyd cheating all those times.}
{385}{}{We'll talk later, Nikki.}
{390}{}{Então essa aposta você PERDERIA, docinho, mas se você é tão estúpido quanto é feio, provavelmente apostaria de
 qualquer maneira. Não vejo aquele canalha desde que ele roubou o Sr. Salvatore.}
{391}{}{Then that's a bet you'd lose, sweetheart. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{392}{}{Then that's a bet you'd lose, girlfriend. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{393}{}{Maybe you didn't hear me the first time, so for the benefit of the hearing impaired: Where is Lloyd?}
{394}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{395}{}{Fine. We'll talk later, Nikki.}
{400}{}{Docinho, eu disse a você que não sei onde ele está. Agora, escuta, estou TRABALHANDO aqui, então volte para onde quer que seja...}
{401}{}{Girlfriend, I TOLD you that I don't know where he is. Now, look, I'm WORKING here, so go back to whatever rock you --}
{402}{}{Nikki, Nikki... I'm losing PATIENCE here. If you don't tell me where Lloyd is, I'm going to lose my temper, too.}
{403}{}{Nikki, I don't know what happened between you and Lloyd. But guess what? I don't NEED to know. I'll just tell
 Mr. Salvatore what I suspect.}
{404}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{405}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{406}{}{We'll talk later then, Nikki.}
{410}{}{Encosta em mim, e o Sr. Salvatore te esfola vivo.}
{411}{}{Salvatore won't protect you; dealers like you are a chip a dozen. Cut the shit and tell me where Lloyd is or ELSE.}
{412}{}{Salvatore won't protect you; he's dead. Cut the shit and tell me where Lloyd is or ELSE.}
{413}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{414}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{415}{}{We'll talk later then, Nikki.}
{420}{}{Do que você está falando?}
{421}{}{Nikki, if you don't tell me everything right now, I'll tell Mr. Salvatore you were in on it, whether you were or not.
 He'll have Mason cut you up seven ways to Sunday, and have your job filled in an hour.}
{422}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{423}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{424}{}{We'll talk later then, Nikki.}
{430}{}{Olha, COMO EU DISSE, eu não sei onde ele está. Mas *talvez* eu tenha ouvido que ele costuma ter um quarto no Desperado, você pode
 encontrar alguma coisa lá. Agora, se você não se importa, eu tenho que voltar ao trabalho.}
{431}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{432}{}{Pretty suspicious that you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{433}{}{We'll talk later then, Nikki.}
{440}{}{Olha, acabo de COMEÇAR a trabalhar aqui, não consigo reconhecer cada contador de cartas e trapaceiro de que me
 aparece pela frente.}
{441}{}{Oh, so that's how you and Lloyd hooked up then?}
{442}{}{So you just started work, huh? Pretty convenient. Well, that's all I need to know. Tell Lloyd he's a dead man.}
{443}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{444}{}{We'll talk later then, Nikki.}
{450}{}{Certo, se você tomar bastante Jet, tudo vai parecer suspeito, certo?}
{451}{}{It IS suspicious. You should have had Lloyd pegged for what he was as soon as he walked in this casino.}
{452}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{453}{}{We'll talk later then, Nikki.}
{460}{}{De o fora daqui agora. Não tenho mais nada para te dizer.}
{461}{}{I got nothing to say to you. Get out of here.}
{462}{}{Not now, maybe. We'll talk later though, Nikki. Count on it.}
{470}{}{Sua fala é suave... igual a das cobras. TALVEZ eu saiba onde Lloyd está, TALVEZ não. Você tem 500 tampas?}
{471}{}{Maybe. Depends on what you got for me.}
{480}{}{PODE ser que Lloyd ainda tenha minha parte, mas não tenho certeza se ele vai me dar. Então PODERIA ser que - por 500 tampas
 - EU PODERIA te dizer onde esse rato mentiroso está.}
{481}{}{Done. Here's the 500 chips. Tell me where he is.}
{482}{}{That's a pretty steep price for a whole bunch of "maybes" and "coulds." I'll find him on my own.}
{483}{}{I don't have enough chips, but I'll be back. You better still be here when I return.}
{490}{}{(Embolsa o dinheiro) De uma olhada na sala das caldeiras no porão do Desperado. É para onde o filho da puta iria correr se as 
coisas esquentassem.}
{491}{}{All right then. Later, Nikki.}
{500}{}{Você quer sair daqui?! Se as pessoas nos virem falando sobre isso, ELAS falarão mais ainda. Você entendeu?}
{501}{}{All right then. Later, Nikki.}
{510}{}{Vai pro inferno, então! Não tenho mais nada para te dizer, NUNCA.}
{511}{}{Breaks my heart. Later, Nikki.}
{600}{}{You bribe Nikki in telling you where Lloyd might be hiding.}
{1210}{}{. Can I help you with... anything?}
{1214}{}{.}
{1235}{}{. Procurando onde gastar algumas tampas?}
{1239}{}{, ganhe algumas tampas.}
{1241}{}{.}
{1242}{}{. Me diga se eu posso te ajudar com alguma coisa.}
{1243}{}{?}
{1244}{}{.}
{1251}{}{...(winks)...you looking to gamble?}
{1252}{}{...(smiles)...wanna take a chance?}
{1253}{}{, you came to the right place.}
{1266}{}{, ganhe algumas tampas.}
{1268}{}{.}
{1314}{}{ could always use new inventory item}
{2699}{}{Quer dançar essa noite?}
