{100}{}{Você vê a linda Nikki.}
{125}{}{Você vê um dos crupiês do cassino.}
{150}{}{Você vê a linda Nikki.}
{160}{}{Você vê a linda Nikki. Ela gesticula para que você venha brincar.}
{170}{}{Você vê um dos crupiês do cassino.}
{180}{}{Você vê uma das crupiês do cassino. Ela gesticula para que você venha brincar.}
{200}{}{::Assobios::}
{210}{}{Hello, [MM]. Can I help you with... anything?}
{220}{}{Parece que este já está jogando com a vida.}
{230}{}{Ei, músculos. Você quer gastar algumas tampas?}
{250}{}{Olá, estrela. Você quer gastar algumas tampas?}
{270}{}{Ei, querida. Você quer gastar algumas tampas?}
{290}{}{Bem, você está louco para entrar aqui, mas… faça suas apostas. A aposta mínima é de 5 tampas. Faça suas apostas…}
{310}{}{Muito bem, senhor. Volte logo.}
{320}{}{Muito bem, senhor. Volte logo.}
{330}{}{Desculpe, senhor. Mais sorte da próxima vez.}
{340}{}{Vencedor! Muito bem, senhor!}
{350}{}{Vencedor! Você dobrou seu dinheiro! Muito bem, senhor!}
{360}{}{Vencedor! Você triplicou seu dinheiro! A sorte está na casa esta noite! Muito bem, senhor!}
{370}{}{O que você quer agora? Está aqui para me fazer perder tempo, ou vai fazer uma aposta?}
{380}{}{Sim, ouvi dizer que ele está MORTO. É isso que você quer ouvir, seu assassino?! Huh?! Agora você vai fazer uma aposta continuar com suas besteiras?}
{390}{}{Então essa aposta você PERDERIA, docinho, mas se você é tão estúpido quanto é feio, provavelmente apostaria de
 qualquer maneira. Não vejo aquele canalha desde que ele roubou o Sr. Salvatore.}
{400}{}{Docinho, eu disse a você que não sei onde ele está. Agora, escuta, estou TRABALHANDO aqui, então volte para onde quer que seja...}
{410}{}{Encosta em mim, e o Sr. Salvatore te esfola vivo.}
{420}{}{Do que você está falando?}
{430}{}{Olha, COMO EU DISSE, eu não sei onde ele está. Mas *talvez* eu tenha ouvido que ele costuma ter um quarto no Desperado, você pode
 encontrar alguma coisa lá. Agora, se você não se importa, eu tenho que voltar ao trabalho.}
{440}{}{Look, I just STARTED working here, and I can't recognize every card counter and two-bit cheat that walks in.
 I gotta pretty good line on shitheads like you, though.}
{450}{}{Yeah, you take enough Jet, and everything seems suspicious, don't it?}
{460}{}{You get the hell outta here right now. I ain't got nothing else to say to you.}
{470}{}{You talk smooth... but so do snakes. MAYBE I know where Lloyd is, MAYBE I don't. You got 500 chips?}
{480}{}{COULD be that Lloyd still has my take, and I ain't sure he's gonna give it to me. So COULD be that - for 500 chips - I
 COULD tell you where his lying ass is hanging out.}
{490}{}{(Pockets the money) Check the boiler room in the basement of the Desperado. That's where the son of a bitch was
 going to run if things got hot.}
{500}{}{Would you get outta here?! People see us talking like this, then THEY'RE gonna talk. Understand?}
{510}{}{Go to hell, then! I ain't got nothing else to say to you, EVER.}
