{100}{}{You see the casino pit boss.}
{150}{}{You see a well-dressed man. He is surveying the casino.}
{151}{}{You see a pit boss. He is surveying the casino.}
{200}{}{Uh... you'll need to remove that armor.}
{201}{}{Uh, sir... or ma'am... you'll need to remove that armor.}
{202}{}{Sir... ma'am... you can't wear that in the casino.}
{205}{}{Uh, why are you sneaking around, sir?}
{206}{}{Uh, are you undercover, sir?}
{210}{}{Uh, why are you sneaking around, ma'am?}
{211}{}{Uh, are you undercover, ma'am?}
{215}{}{Good evening, }
{216}{}{Evening, }
{220}{}{Good evening, }
{221}{}{Evening, }
{225}{}{Good day, }
{230}{}{Good day, }
{235}{}{Friend, you're walking into the wrong casino.}
{236}{}{You better leave. Now.}
{237}{}{This ain't the place to be gambling with your life. You better leave.}
{238}{}{Bitch, you're walking into the wrong casino.}
{245}{}{Sir, I'm sorry, you'll have to secure that weapon.}
{250}{}{Ma'am, I'm sorry, you'll have to secure that weapon.}
{255}{}{Honey, I'm sorry, you can't carry weapons into the casino. Heh-heh... you're deadly enough as it is.}
{260}{}{Querida, com um corpo desse, você não poderá se esgueirar para lugar nenhum.}
{265}{}{Tribal, é melhor você guardar essa arma AGORA.}
{270}{}{Tribal, é melhor você parar com essa merda AGORA.}
{275}{}{Hey, hey... Myron! Ain't seen you outside the lab in a long time.}
{276}{}{You here to sample some of the new merchandise, Myron?}
{277}{}{Hey! Come on in, Myron.}
{280}{}{Shoot. What d'you want to know?}
{281}{}{Fooooooo foo foo fooooo}
{282}{}{Cai fora}
{283}{}{Quem é você?}
{284}{}{What casino is this?}
{285}{}{Can you tell me a little about the casino?}
{286}{}{You know somebody named Pretty Boy Lloyd?}
{287}{}{Who's that old guy at the slot machine?}
{288}{}{That comic you got on stage is weak. Mind if I try?}
{289}{}{Thanks. Do you need a dancer for the night? I'm open for a limited engagement.}
{290}{}{Obrigado, eu vou.}
{291}{}{Nothing, thanks. Sorry to bother you.}
{292}{}{Just checking on things. Carry on.}
{295}{}{No droids.}
{296}{}{We don't serve droids.}
{297}{}{No droids. They wait outside.}
{300}{}{Uh, you better run along now, sir.}
{301}{}{Uh, you better run along now, ma'am.}
{302}{}{Get outta here, retard.}
{303}{}{Mom says I was speshal}
{304}{}{Cai fora}
{305}{}{I'm not s'posed ta chat while on duty, but I'm glad you kicked the Enclave's ass.}
{306}{}{Ei, }
{315}{}{Yeah, yer Mom said I was special, too. Now take a hike... maybe she's along Virgin street somewhere.}
{316}{}{Oh goodie! Bye bye}
{317}{}{Cai fora}
{325}{}{I'm the pit boss. Now what can I do for you?}
{326}{}{I run the floor of the casino here. You need anything, just ask.}
{327}{}{What casino is this?}
{328}{}{Can you tell me a little about the casino?}
{329}{}{Nothing, thanks. Sorry to bother you.}
{335}{}{This is [CN]. Need anything, just ask.}
{336}{}{This is [CN]. At least, last time I checked the sign outside the door. Now what can I do for you?}
{337}{}{Quem é você?}
{338}{}{Can you tell me a little about the casino?}
{339}{}{Nothing, thanks. Sorry to bother you.}
{340}{}{What can I do for you, pal?}
{341}{}{What can I do for you, hon?}
{342}{}{Fooooooo foo foo fooooo}
{343}{}{Cai fora}
{344}{}{Quem é você?}
{345}{}{Best goddamn casino in town... but I am a little biased. Anything else you want to know?}
{346}{}{Best goddamn casino in town, best goddamn tables... now why don't you run along now, check 'em out? All right?}
{347}{}{Quem é você?}
{348}{}{Who owns this casino?}
{349}{}{Okay, thanks. Sorry to bother you.}
{350}{}{Thanks. Do you need a dancer for the night? I'm open for a limited engagement.}
{351}{}{Obrigado, eu vou.}
{352}{}{Nothing, thanks. Sorry to bother you.}
{353}{}{Just checking on things. Carry on.}
{355}{}{The [CA] family. They pumped a lot of life into this place, made it a real night spot, a shining jewel in New Reno.}
{356}{}{The [CA] Family. That a problem? Cause if you ain't here to gamble, then this ain't the place for you. Understand?}
{357}{}{Quem é você?}
{358}{}{Can you tell me a little about the casino?}
{359}{}{Eu vejo. Obrigado pelo seu tempo.}
{360}{}{Hey, look who's here! Hey, }
{361}{}{. Welcome to [CN]. Love your films.}
{362}{}{Fooooooo foo foo fooooo}
{363}{}{Cai fora}
{364}{}{Quem é você?}
{365}{}{That guy? Old Man McGee? Crazy sumabitch... he's been playing that machine
 there for the past few years, waiting for the big jackpot. His life fortune
 must be sitting in that thing, but it won't give him a single chip.}
{366}{}{That guy? Old Man McGee? Crazy sumabitch, that's for sure. Heh.
 Sure was pissed about you winning his fortune. I'd be careful around him.}
{367}{}{Is the machine rigged?}
{368}{}{Eu tenho mais algumas perguntas...}
{369}{}{Obrigado pela informação.}
{370}{}{Thanks, I'm flattered. Just stopped by to say hello.}
{375}{}{Nope, it's just stubborn... just like him. It could probably use a little repair work, but we ain't got no slot
 mechanics that can fix that damn thing.}
{376}{}{Eu tenho mais algumas perguntas...}
{377}{}{Interesting. Thanks for the information.}
{385}{}{Yeah, that son of a bitch came in here about a week ago, ripped off one table of about a thousand chips, then bailed.
 Don't know where he is now, but he used to have a room at the Desperado.}
{386}{}{Yeah, some guy by that name was rentin' one of th' rooms upstairs...204. He was all paid up, but he bailed
 a few days ago and nobody saw him leave.}
{387}{}{Mr. Salvatore mentioned that there was a specific dealer that Lloyd won the money from. Who was that?}
{388}{}{Eu tenho mais algumas perguntas...}
{389}{}{Obrigado pela informação.}
{395}{}{Nikki? Yeah, she's over there, at the middle table. Is there some sort of problem?}
{396}{}{Sem problemas. Só queria conhecê-la. Só tenho algumas perguntas...}
{397}{}{Obrigado pela informação.}
{405}{}{Her name WAS Nikki. She used to work here but she got aced... not too long ago.}
{406}{}{Hmmm. Você se importa se eu te fizer outras perguntas...?}
{407}{}{Interesting. Thanks for the information.}
{415}{}{Her name was Nikki. She used to work here but she took off not too long ago. Just packed her shit and bailed.}
{416}{}{Você se importa se eu te fizer outras perguntas...}
{417}{}{Interesting. Thanks for the information.}
{425}{}{Sure, be good for business. Dressing room's in the back...}
{426}{}{Excellent. I'll be on stage in a few minutes...}
{427}{}{Não agora. Eu tenho outras perguntas...}
{428}{}{Not right now, but I'll be back.}
{435}{}{No, we're still recovering from your last gig. You might want to check some of the other casinos.}
{436}{}{Que bom, obrigado. Olha, eu tenho outras perguntas...}
{437}{}{Certo... Mas eu voltarei.}
{445}{}{You count up the evening's tally. chips. Not a bad haul.}
{446}{}{The leather was a nice touch.}
{447}{}{That ball gag you had with you didn't hurt, either.}
{448}{}{I'll do even better next time...}
{455}{}{Yeah, he stinks worse than brahmin shit. Still, you...? Aw, why the hell not. A little improv ain't gonna hurt, but
 it's a rough crowd... better hope you're good.}
{456}{}{Oh, I'm good... just watch me go.}
{1215}{}{, sir.}
{1216}{}{, sir.}
{1220}{}{, ma'am.}
{1221}{}{, ma'am.}
{1225}{}{, sir.}
{1230}{}{, ma'am.}
{1306}{}{. Take a rest from saving the world and have some fun.}
