{100}{}{Você vê o guarda do cassino.}
{150}{}{Você vê um homem bem vestido. Ele está supervisionando o cassino.}
{151}{}{Você vê o guarda do cassino. Ele está supervisionando o lugar.}
{200}{}{Uh... você precisará tirar essa armadura.}
{201}{}{Uh, senhor... ou senhora... você precisará tirar essa armadura.}
{202}{}{Senhor... senhora... você não pode usar isso no cassino.}
{205}{}{Uh, por que você está se esgueirando, senhor?}
{206}{}{Uh, você está disfarçado, senhor?}
{210}{}{Uh, por que você está se esgueirando, senhora?}
{211}{}{Uh, você está disfarçada, senhora?}
{215}{}{Boa tarde, }
{216}{}{Boa noite, }
{220}{}{Boa tarde, }
{221}{}{Boa noite, }
{225}{}{Bom dia, }
{230}{}{Bom dia, }
{235}{}{Amigo, você está entrando no cassino errado.}
{236}{}{É melhor você sair. Agora.}
{237}{}{Este não é um lugar para brincar com sua vida. É melhor ir embora.}
{238}{}{Ô Biscate, entrou no cassino errado.}
{245}{}{Senhor, sinto muito, você terá que guardar essa arma.}
{250}{}{Senhora, sinto muito, você terá que guardar essa arma.}
{255}{}{Querida, desculpe, você não pode levar armas para o cassino. Heh-heh... você já é mortífera o suficiente.}
{260}{}{Querida, com um corpo desse, você não poderá se esgueirar para lugar nenhum.}
{265}{}{Tribal, é melhor você guardar essa arma AGORA.}
{270}{}{Tribal, é melhor você parar com essa merda AGORA.}
{275}{}{Ei, ei... Myron! Não te vejo fora do laboratório há muito tempo.}
{276}{}{Você veio aqui para provar algumas das novas mercadorias, Myron?}
{277}{}{Ei! Myron, chega mais.}
{280}{}{Atira. O que você quer saber?}
{281}{}{Fooooooo foo foo fooooo}
{282}{}{Cai fora}
{283}{}{Quem é você?}
{284}{}{Qual cassino é esse?}
{285}{}{Você pode me dizer um pouco sobre o cassino?}
{286}{}{Você conhece alguém chamado Lloyd Bonitão?}
{287}{}{Quem é aquele velho na máquina caça-níqueis?}
{288}{}{Aquele comediante que você tem no palco é um bundão. Você se importa se eu tentar?}
{289}{}{Obrigado. Você precisa de alguém que dance essa noite? Posso fazer por um tempo limitado.}
{290}{}{Obrigado, eu vou.}
{291}{}{Nada, obrigado. Desculpe te incomodar.}
{292}{}{Apenas verificando as coisas. Continue.}
{295}{}{Nada de droides.}
{296}{}{Nós não servimos droides.}
{297}{}{Sem droides. Ele espera lá fora.}
{300}{}{Uh, é melhor você sair agora, senhor.}
{301}{}{Uh, é melhor você sair agora, senhora.}
{302}{}{Sai daqui, retardado.}
{303}{}{Mamãe diz que eu sou especial}
{304}{}{Cai fora}
{305}{}{Não posso conversar enquanto estiver em serviço, mas me alegro que você deu um chute no cu da Enclave.}
{306}{}{Ei, }
{315}{}{Sim, sua mãe disse que eu também sou especial. Agora vai dar uma voltinha... talvez ela esteja em algum lugar na Virgin Street.}
{316}{}{Oh, que booom! Até}
{317}{}{Cai fora}
{325}{}{Eu sou o segurança daqui. O que posso fazer por você?}
{326}{}{Eu supervisiono este andar do cassino. Se precisar de alguma coisa, é só pedir.}
{327}{}{Qual cassino é esse?}
{328}{}{Você pode me dizer um pouco sobre o cassino?}
{329}{}{Nada, obrigado. Desculpe te incomodar.}
{335}{}{Este é [CN]. Se precisar de alguma coisa, é só pedir.}
{336}{}{This is [CN]. At least, last time I checked the sign outside the door. Now what can I do for you?}
{337}{}{Quem é você?}
{338}{}{Você pode me dizer um pouco sobre o cassino?}
{339}{}{Nada, obrigado. Desculpe te incomodar.}
{340}{}{O que posso fazer por você, amigo?}
{341}{}{O que posso fazer por você, querida?}
{342}{}{Fooooooo foo foo fooooo}
{343}{}{Cai fora}
{344}{}{Quem é você?}
{345}{}{O melhor cassino da cidade... mas pareço um pouco tendencioso. Mais alguma coisa que você queira saber?}
{346}{}{O melhor cassino da cidade, a melhores das melhores mesas... então, por que você não vai dar uma olhada? Certo?}
{347}{}{Quem é você?}
{348}{}{Quem é o dono desse cassino?}
{349}{}{Ok, obrigado. Desculpe incomodá-lo.}
{350}{}{Obrigado. Você precisa de alguém que dance essa noite? Posso fazer por um tempo limitado.}
{351}{}{Obrigado, eu vou.}
{352}{}{Nada, obrigado. Desculpe te incomodar.}
{353}{}{Apenas verificando as coisas. Continue.}
{355}{}{A família [CA]. Eles deram muita vida a este lugar, fizeram dele um verdadeiro ponto da noite, uma joia brilhante em New Reno.}
{356}{}{The [CA] Family. That a problem? Cause if you ain't here to gamble, then this ain't the place for you. Understand?}
{357}{}{Quem é você?}
{358}{}{Você pode me dizer um pouco sobre o cassino?}
{359}{}{Eu vejo. Obrigado pelo seu tempo.}
{360}{}{Ei, olha quem está aqui! Olá, }
{361}{}{. Welcome to [CN]. Love your films.}
{362}{}{Fooooooo foo foo fooooo}
{363}{}{Cai fora}
{364}{}{Quem é você?}
{365}{}{Esse cara? Velho McGee? Totalmente louco... ele tem jogado naquela máquina
 lá nos últimos anos, esperando o grande prêmio. Toda sua fortuna deve
 estar naquela coisa, mas não lhe dará uma única tampinha.}
{366}{}{Aquele cara? Velho McGee? Completamente louco, certeza. Heh.
 Claro que ficou chateado por você ter ganhado a fortuna dele. Eu tomaria cuidado.}
{367}{}{A máquina é modificada?}
{368}{}{Eu tenho mais algumas perguntas...}
{369}{}{Obrigado pela informação.}
{370}{}{Obrigado, estou lisonjeado. Só passei para dizer olá.}
{375}{}{Não, ela é apenas teimosa... assim como ele. Provavelmente poderia ser consertada, mas não temos mecanismos
 de slot que possam consertar essa porcaria.}
{376}{}{Eu tenho mais algumas perguntas...}
{377}{}{Interessante. Obrigado pela informação.}
{385}{}{Sim, aquele filho da puta veio aqui faz uma semana mais ou menos, roubou uma mesa de umas mil tampas, depois saiu.
 Não sei onde ele está agora, mas costumava ter um quarto no Desperado.}
{386}{}{Sim, um cara com esse nome estava alugando um dos quartos lá em cima... 204. Ele pagou tudo, mas saiu há poucos
 dias sem que ninguém o tivesse visto.}
{387}{}{O Sr. Salvatore mencionou que havia um crupiê em particular de quem Lloyd ganhou o dinheiro. E quem foi?}
{388}{}{Eu tenho mais algumas perguntas...}
{389}{}{Obrigado pela informação.}
{395}{}{Nikki? Sim, ela está ali, na mesa do meio. Que tipo de problema estamos falando?}
{396}{}{Sem problemas. Só queria conhecê-la. Só tenho algumas perguntas...}
{397}{}{Obrigado pela informação.}
{405}{}{O nome dela era Nikki. Ela costumava trabalhar aqui, mas foi presa... não faz muito tempo.}
{406}{}{Hmmm. Você se importa se eu te fizer outras perguntas...?}
{407}{}{Interessante. Obrigado pela informação.}
{415}{}{O nome dela era Nikki. Ela costumava trabalhar aqui, mas ela vazou não faz muito tempo. Só fez as malas e saiu.}
{416}{}{Você se importa se eu te fizer outras perguntas...}
{417}{}{Interessante. Obrigado pela informação.}
{425}{}{Claro, seria bom para os negócios. O vestiário fica nos fundos...}
{426}{}{Excelente. Estarei no palco em alguns minutos...}
{427}{}{Não agora. Eu tenho outras perguntas...}
{428}{}{Não agora, mas voltarei.}
{435}{}{Não, ainda estamos nos recuperando da sua última apresentação. Você pode querer tentar em um dos outros cassinos.}
{436}{}{Que bom, obrigado. Olha, eu tenho outras perguntas...}
{437}{}{Certo... Mas eu voltarei.}
{445}{}{You count up the evening's tally. chips. Not a bad haul.}
{446}{}{The leather was a nice touch.}
{447}{}{That ball gag you had with you didn't hurt, either.}
{448}{}{I'll do even better next time...}
{455}{}{Sim, ele fede pior do que merda de brahmin. Então você...? Ótimo, por que não? Um pouco de improvisação deve bastar,
 mas é uma multidão difícil... espero que você esteja bem.}
{456}{}{Ah, eu estou bem... apenas observe.}
{1215}{}{, senhor.}
{1216}{}{, senhor.}
{1220}{}{, senhora.}
{1221}{}{, senhora.}
{1225}{}{, senhor.}
{1230}{}{, senhora.}
{1306}{}{. Descanse de salvar o mundo e divirta-se.}
