{100}{}{Você vê o guarda do cassino.}
{150}{}{Você vê um homem bem vestido. Ele está supervisionando o cassino.}
{151}{}{Você vê o guarda do cassino. Ele está supervisionando o lugar.}
{200}{}{Uh... você precisará tirar essa armadura.}
{201}{}{Uh, senhor... ou senhora... você precisará tirar essa armadura.}
{202}{}{Senhor... senhora... você não pode usar isso no cassino.}
{205}{}{Uh, por que você está se esgueirando, senhor?}
{206}{}{Uh, você está disfarçado, senhor?}
{210}{}{Uh, por que você está se esgueirando, senhora?}
{211}{}{Uh, você está disfarçada, senhora?}
{215}{}{Boa tarde, }
{216}{}{Boa noite, }
{220}{}{Boa tarde, }
{221}{}{Boa noite, }
{225}{}{Bom dia, }
{230}{}{Bom dia, }
{235}{}{Amigo, você está entrando no cassino errado.}
{236}{}{É melhor você sair. Agora.}
{237}{}{Este não é um lugar para brincar com sua vida. É melhor ir embora.}
{238}{}{Ô Biscate, entrou no cassino errado.}
{245}{}{Senhor, sinto muito, você terá que guardar essa arma.}
{250}{}{Senhora, sinto muito, você terá que guardar essa arma.}
{255}{}{Querida, desculpe, você não pode levar armas para o cassino. Heh-heh... você já é mortífera o suficiente.}
{260}{}{Querida, com um corpo desse, você não poderá se esgueirar para lugar nenhum.}
{265}{}{Tribal, é melhor você guardar essa arma AGORA.}
{270}{}{Tribal, é melhor você parar com essa merda AGORA.}
{275}{}{Ei, ei... Myron! Não te vejo fora do laboratório há muito tempo.}
{276}{}{Você veio aqui para provar algumas das novas mercadorias, Myron?}
{277}{}{Ei! Myron, chega mais.}
{280}{}{Atira. O que você quer saber?}
{281}{}{Fooooooo foo foo fooooo}
{282}{}{Cai fora}
{283}{}{Quem é você?}
{284}{}{Qual cassino é esse?}
{285}{}{Você pode me dizer um pouco sobre o cassino?}
{286}{}{Você conhece alguém chamado Lloyd Bonitão?}
{287}{}{Quem é aquele velho na máquina caça-níqueis?}
{288}{}{Aquele comediante que você tem no palco é um bundão. Você se importa se eu tentar?}
{289}{}{Obrigado. Você precisa de alguém que dance essa noite? Posso fazer por um tempo limitado.}
{290}{}{Obrigado, eu vou.}
{291}{}{Nada, obrigado. Desculpe te incomodar.}
{292}{}{Apenas verificando as coisas. Continue.}
{295}{}{Nada de droides.}
{296}{}{Nós não servimos droides.}
{297}{}{Sem droides. Ele espera lá fora.}
{300}{}{Uh, é melhor você sair agora, senhor.}
{301}{}{Uh, é melhor você sair agora, senhora.}
{302}{}{Sai daqui, retardado.}
{303}{}{Mamãe diz que eu sou especial}
{304}{}{Cai fora}
{305}{}{Não posso conversar enquanto estiver em serviço, mas me alegro que você deu um chute no cu da Enclave.}
{306}{}{Ei, }
{315}{}{Sim, sua mãe disse que eu também sou especial. Agora vai dar uma voltinha... talvez ela esteja em algum lugar na Virgin Street.}
{316}{}{Oh, que booom! Até}
{317}{}{Cai fora}
{325}{}{Eu sou o segurança daqui. O que posso fazer por você?}
{326}{}{Eu supervisiono este andar do cassino. Se precisar de alguma coisa, é só pedir.}
{327}{}{Qual cassino é esse?}
{328}{}{Você pode me dizer um pouco sobre o cassino?}
{329}{}{Nada, obrigado. Desculpe te incomodar.}
{335}{}{This is [CN]. Need anything, just ask.}
{336}{}{This is [CN]. At least, last time I checked the sign outside the door. Now what can I do for you?}
{337}{}{Quem é você?}
{338}{}{Você pode me dizer um pouco sobre o cassino?}
{339}{}{Nada, obrigado. Desculpe te incomodar.}
{340}{}{O que posso fazer por você, amigo?}
{341}{}{O que posso fazer por você, querida?}
{342}{}{Fooooooo foo foo fooooo}
{343}{}{Cai fora}
{344}{}{Quem é você?}
{345}{}{Best goddamn casino in town... but I am a little biased. Anything else you want to know?}
{346}{}{Best goddamn casino in town, best goddamn tables... now why don't you run along now, check 'em out? All right?}
{347}{}{Quem é você?}
{348}{}{Who owns this casino?}
{349}{}{Okay, thanks. Sorry to bother you.}
{350}{}{Obrigado. Você precisa de alguém que dance essa noite? Posso fazer por um tempo limitado.}
{351}{}{Obrigado, eu vou.}
{352}{}{Nada, obrigado. Desculpe te incomodar.}
{353}{}{Apenas verificando as coisas. Continue.}
{355}{}{The [CA] family. They pumped a lot of life into this place, made it a real night spot, a shining jewel in New Reno.}
{356}{}{The [CA] Family. That a problem? Cause if you ain't here to gamble, then this ain't the place for you. Understand?}
{357}{}{Quem é você?}
{358}{}{Você pode me dizer um pouco sobre o cassino?}
{359}{}{Eu vejo. Obrigado pelo seu tempo.}
{360}{}{Ei, olha quem está aqui! Olá, }
{361}{}{. Welcome to [CN]. Love your films.}
{362}{}{Fooooooo foo foo fooooo}
{363}{}{Cai fora}
{364}{}{Quem é você?}
{365}{}{That guy? Old Man McGee? Crazy sumabitch... he's been playing that machine
 there for the past few years, waiting for the big jackpot. His life fortune
 must be sitting in that thing, but it won't give him a single chip.}
{366}{}{That guy? Old Man McGee? Crazy sumabitch, that's for sure. Heh.
 Sure was pissed about you winning his fortune. I'd be careful around him.}
{367}{}{Is the machine rigged?}
{368}{}{Eu tenho mais algumas perguntas...}
{369}{}{Obrigado pela informação.}
{370}{}{Obrigado, estou lisonjeado. Só passei para dizer olá.}
{375}{}{Não, ela é apenas teimosa... assim como ele. Provavelmente poderia ser consertada, mas não temos mecanismos
 de slot que possam consertar essa porcaria.}
{376}{}{Eu tenho mais algumas perguntas...}
{377}{}{Interessante. Obrigado pela informação.}
{385}{}{Yeah, that son of a bitch came in here about a week ago, ripped off one table of about a thousand chips, then bailed.
 Don't know where he is now, but he used to have a room at the Desperado.}
{386}{}{Yeah, some guy by that name was rentin' one of th' rooms upstairs...204. He was all paid up, but he bailed
 a few days ago and nobody saw him leave.}
{387}{}{Mr. Salvatore mentioned that there was a specific dealer that Lloyd won the money from. Who was that?}
{388}{}{Eu tenho mais algumas perguntas...}
{389}{}{Obrigado pela informação.}
{395}{}{Nikki? Yeah, she's over there, at the middle table. Is there some sort of problem?}
{396}{}{Sem problemas. Só queria conhecê-la. Só tenho algumas perguntas...}
{397}{}{Obrigado pela informação.}
{405}{}{Her name WAS Nikki. She used to work here but she got aced... not too long ago.}
{406}{}{Hmmm. Você se importa se eu te fizer outras perguntas...?}
{407}{}{Interessante. Obrigado pela informação.}
{415}{}{Her name was Nikki. She used to work here but she took off not too long ago. Just packed her shit and bailed.}
{416}{}{Você se importa se eu te fizer outras perguntas...}
{417}{}{Interessante. Obrigado pela informação.}
{425}{}{Sure, be good for business. Dressing room's in the back...}
{426}{}{Excellent. I'll be on stage in a few minutes...}
{427}{}{Não agora. Eu tenho outras perguntas...}
{428}{}{Not right now, but I'll be back.}
{435}{}{No, we're still recovering from your last gig. You might want to check some of the other casinos.}
{436}{}{Que bom, obrigado. Olha, eu tenho outras perguntas...}
{437}{}{Certo... Mas eu voltarei.}
{445}{}{You count up the evening's tally. chips. Not a bad haul.}
{446}{}{The leather was a nice touch.}
{447}{}{That ball gag you had with you didn't hurt, either.}
{448}{}{I'll do even better next time...}
{455}{}{Yeah, he stinks worse than brahmin shit. Still, you...? Aw, why the hell not. A little improv ain't gonna hurt, but
 it's a rough crowd... better hope you're good.}
{456}{}{Oh, I'm good... just watch me go.}
{1215}{}{, sir.}
{1216}{}{, sir.}
{1220}{}{, ma'am.}
{1221}{}{, ma'am.}
{1225}{}{, sir.}
{1230}{}{, ma'am.}
{1306}{}{. Take a rest from saving the world and have some fun.}
