{100}{}{}
{101}{}{}
{110}{}{Your feet really itch.}
{120}{}{You're developing a nasty bunion on each foot.}
{130}{}{Your shoes feel really tight; those bunions are really getting inflamed.}
{140}{}{That nasty bunion on each foot seems to have turned into an extra toe. But at least that
 persistent, burning itch has gone away.}
{141}{}{Oh, meu Deus, é Bess!}
{150}{}{Você ganhou }
{151}{}{ experience points for getting the GECK.}
