{100}{}{}
{101}{}{}
{110}{}{Seus pés realmente coçam.}
{120}{}{Você está desenvolvendo um joanete desagradável em cada pé.}
{130}{}{Seus sapatos parecem muito apertados; esses joanetes estão realmente ficando inflamados.}
{140}{}{Aquele joanete desagradável em cada pé parece ter se transformado em um dedo extra. Mas pelo
 menos aquela coceira persistente e ardente desapareceu.}
{141}{}{Oh, meu Deus, é Bess!}
{150}{}{Você ganhou }
{151}{}{ pontos de experiência por obter o GECK.}
