{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê o terminal de interface de voz.}
{102}{}{Você vê um terminal de computador padrão, modificado para comandos de voz.}
{103}{}{Você examina o terminal do computador, mas não consegue encontrar nada obviamente errado com ele.
 O que você faz?}
{104}{}{O golpeia de maneira "especial".}
{105}{}{O chuta de maneira "especial".}
{106}{}{Execute o programa de diagnóstico.}
{107}{}{Abre e o olha por dentro.}
{108}{}{O deixa sozinho.}
{109}{}{Você olha para o console por um tempo e decide o melhor local para dar um soco. Depois de
 dar o seu melhor 'isso vai consertar', o monitor pisca algumas vezes e depois se estabiliza.
 Não há outro efeito. O que faz?}
{110}{}{O chuta de maneira "especial".}
{111}{}{Execute o programa de diagnóstico.}
{112}{}{Abre e o olha por dentro.}
{113}{}{O deixa sozinho.}
{114}{}{This well-known repair method produces two results. First, the monitor seems to go haywire for
 several seconds and then stabilizes. Second, you hear a breaking metal type of sound and the panel you
 kicked falls to the floor. What do you do?}
{115}{}{Execute o programa de diagnóstico.}
{116}{}{Damn thing's open. Might as well look inside.}
{117}{}{O deixa sozinho.}
{118}{}{You are certain that the system should have a set of diagnostic routines available. However, the
 keyboard input seems to have been disabled. The unit accepts voice commands only. What do you do?}
{119}{}{A única coisa que resta é olhar para dentro.}
{120}{}{O deixa sozinho.}
{121}{}{Peering into the mass of cables and circuit boards, you find that the system has been deliberately sabotaged.
 One of the circuit boards, the voice recognition module, is beyond repair and must be replaced.
 Now all you need to do is find a replacement module.}
{122}{}{Feito.}
{123}{}{Feito.}
{124}{}{Você instala o módulo no terminal. O sistema é reparado.}
{125}{}{O terminal precisa de um módulo de reconhecimento de voz instalado antes de se tornar operacional.}
{126}{}{Feito.}
{127}{}{O sistema está funcionando bem agora.}
{128}{}{Acessando imagens de segurança, carregando reprodução holográfica...}
{129}{}{Você é o último, Gruthar. A mancha de sua espécie logo será limpa.}
{130}{}{Diga ao seu suposto presidente que ele vai queimar por isso.}
{131}{}{Qualquer que seja. Você nunca foi nada além de um animal falante.}
{132}{}{That may be, but we were created through your experimentation. You gave us life!}
{133}{}{And now I give you death.}
{134}{}{Take his body. The doctor wanted a specimen.}
{135}{}{Their blood will run like the Nile!}
