{100}{}{Você vê um sujeito velho e de aparência bondosa.}
{101}{}{É o Doutor Jubilee.}
{102}{}{Ele é um velho com uma barba branca como a neve e um olhar ligeiramente vazio.}
{103}{}{Eu sou o Doutor Jubilee. O que há de errado, jovem?}
{104}{}{O que há de errado, jovem?}
{105}{}{Estou ferido.}
{106}{}{Eu preciso de um médico.}
{107}{}{Você não pode simplesmente tomar umas pílulas ou qualquer coisa e parar de me incomodar com essa bobagem?}
{108}{}{Inferno, você nem está sangrando.}
{109}{}{Não sei. Não pense que posso salvá-lo, talvez teremos que cortar essa perna fora.}
{110}{}{Você está brincando.}
{111}{}{Ha-ha.}
{112}{}{Aí está você, filho.}
{113}{}{Novamente.}
{114}{}{Obrigado, doutor. Talvez você possa me ajudar com algumas respostas.}
{115}{}{Adeus.}
{116}{}{Vai custar $ 50.}
{117}{}{Só me curar.}
{118}{}{Eu não vou ficar aqui.}
{119}{}{Você parece melhor.}
{120}{}{Eu vou agora.}
{121}{}{Não, nunca brinco. Melhor eu cortar essa perna antes que a gangrena comece.}
{122}{}{De jeito nenhum, você nao vai cortar nada, entendeu?}
{123}{}{Ja chega, vou embora.}
{124}{}{Bem, se infeccionar, não me culpe.}
{125}{}{Não dirijo um hospital de caridade. Você vai precisar de dinheiro antes de eu fazer qualquer coisa.}
{126}{}{Então o que posso fazer por você?}
{127}{}{Manda.}
{128}{}{Vault 13?}
{129}{}{Sabe onde posso encontrar a Vault 13?}
{130}{}{Ouvi alguém dizendo que o Sr. Westin não está bem. Isso é verdade? Me preocupo que algo possa acontecer com ele. Ele esta me devendo.}
{131}{}{Aquele tal de Bob Carne Seca disse que você roubou um mapa dele. Qual é o problema?}
{132}{}{Estou à procura de trabalho. Conhece algum?}
{133}{}{Doutor, você não saberia nada sobre um grupo que está lutando contra esses escravistas do mal, saberia?}
{134}{}{Bem, você não deve se preocupar, filho. Contanto que você não teste seu sistema, ele provavelmente sobreviverá a todos nós. Claro, se você decidir entre meus cuidados médicos ou seus medicamentos.}
{135}{}{Well, that's good to know. There's something else I was wondering.}
{136}{}{Thanks, doc.}
{137}{}{That old drunk! The only thing I ever got from him was my "Velvet Elvii" painting - in lieu of cash.}
{138}{}{A Velvet Elvii? Could I see it?}
{139}{}{Not exactly a map, eh? Well, let me pick your brains on some other things.}
{140}{}{Well, I've got to get on.}
{141}{}{I ain't heard that mentioned since old Saltbeef was brought in here. Sunstroke. Burned with fever for three days, all the time ranting how he'd found Vault 13, his mother lode.}
{142}{}{Mother Lode?}
{143}{}{So where is it?}
{144}{}{Where vault?}
{145}{}{Couldn't tell you. Saltbeef always claimed he had a map, but nobody's ever seen it.}
{146}{}{Saltbeef?}
{147}{}{Ask more.}
{148}{}{Well, that's more than what I had before.}
{149}{}{The big one. Saltbeef's an old uranium prospector - more accurately, a drunk. Lives out on the Westin spread these days.}
{150}{}{Another question...}
{151}{}{Obrigado pela história.}
{152}{}{Well, I was really hoping to get some money for it. I'll let it go for $}
{153}{}{Maybe later, another question...}
{154}{}{Maybe later, I have to go.}
{155}{}{Saltbeef's an old uranium prospector. Lives out on the Westin spread these days.}
{156}{}{Another question...}
{157}{}{Obrigado pela história.}
{158}{}{You best go talk to President Tandi. I've heard she's looking for a special type of person.}
{159}{}{Another question...}
{160}{}{Obrigado.}
{161}{}{I might... There is a group set against slavery and- well, most the other vices, too. You can sometimes find them over at the big shop, working on some automobile.}
{162}{}{Another question...}
{163}{}{Obrigado.}
{164}{}{Hey, get your hands off that, punk!}
{165}{}{Careful there! Just takes tiny amount to expose yourself.}
{166}{}{Put that back! You could seriously hurt yourself with that stuff.}
{167}{}{Those meds are for Mr. Westin, not you. Put them back.}
{168}{}{Get away from that. Got to be careful, see. Wouldn't want Mr. Westin getting the wrong meds now.}
{169}{}{Watch it! I just measured out Mr. Westin's dose.}
{170}{}{I'm Doc Jubilee. What's wrong, young miss?}
{171}{}{What's wrong, young miss?}
{172}{}{There you are, miss.}
{173}{}{Well you shouldn't worry, miss. As long as he doesn't tax his system, he'll probably outlast us all. 'Course that's if he'd ever mind my doctoring or his medicine.}
{174}{}{Sure. Here's the $}
{175}{}{Thanks, I've been trying to get the money out of Saltbeef, but that bum never had any.}
{176}{}{.}
