{100}{}{Você vê um sujeito velho e de aparência bondosa.}
{101}{}{É o Doutor Jubilee.}
{102}{}{Ele é um velho com uma barba branca como a neve e um olhar ligeiramente vazio.}
{103}{}{Eu sou o Doutor Jubilee. O que há de errado, jovem?}
{104}{}{O que há de errado, jovem?}
{105}{}{Estou ferido.}
{106}{}{Eu preciso de um médico.}
{107}{}{Você não pode simplesmente tomar umas pílulas ou qualquer coisa e parar de me incomodar com essa bobagem?}
{108}{}{Inferno, você nem está sangrando.}
{109}{}{Não sei. Não pense que posso salvá-lo, talvez teremos que cortar essa perna fora.}
{110}{}{Você está brincando.}
{111}{}{Ha-ha.}
{112}{}{Aí está você, filho.}
{113}{}{Novamente.}
{114}{}{Obrigado, doutor. Talvez você possa me ajudar com algumas respostas.}
{115}{}{Adeus.}
{116}{}{Vai custar $ 50.}
{117}{}{Só me curar.}
{118}{}{Eu não vou ficar aqui.}
{119}{}{Você parece melhor.}
{120}{}{Eu vou agora.}
{121}{}{Não, nunca brinco. Melhor eu cortar essa perna antes que a gangrena comece.}
{122}{}{De jeito nenhum, você nao vai cortar nada, entendeu?}
{123}{}{Ja chega, vou embora.}
{124}{}{Bem, se infeccionar, não me culpe.}
{125}{}{Não dirijo um hospital de caridade. Você vai precisar de dinheiro antes de eu fazer qualquer coisa.}
{126}{}{Então o que posso fazer por você?}
{127}{}{Manda.}
{128}{}{Vault 13?}
{129}{}{Sabe onde posso encontrar a Vault 13?}
{130}{}{Ouvi alguém dizendo que o Sr. Westin não está bem. Isso é verdade? Me preocupo que algo possa acontecer com ele. Ele esta me devendo.}
{131}{}{Aquele tal de Bob Carne Seca disse que você roubou um mapa dele. Qual é o problema?}
{132}{}{Estou à procura de trabalho. Conhece algum?}
{133}{}{Doutor, você não saberia nada sobre um grupo que está lutando contra esses escravistas do mal, saberia?}
{134}{}{Bem, você não deve se preocupar, filho. Contanto que você não teste seu sistema, ele provavelmente sobreviverá a todos nós. Claro, se você decidir entre meus cuidados médicos ou seus medicamentos.}
{135}{}{Bem, é bom saber disso. Tinha outra coisa que eu estava pensando.}
{136}{}{Obrigado, doutor.}
{137}{}{Aquele velho bêbado! A única coisa que recebi dele foi meu quadro "Velvet Elvis" em vez de dinheiro.}
{138}{}{O "Velvet Elvis"? Eu poderia ver?}
{139}{}{Não é exatamente um mapa, eh? Bem, deixe-me usar seu cérebro em outra coisa.}
{140}{}{Bem, preciso ir andando.}
{141}{}{Não ouço falar disso desde que o velho Carne Seca foi trazido para cá. Uma insolação, queimou de febre por três dias, ficava delirando o tempo todo sobre como havia encontrado o Vault 13, seu filão.}
{142}{}{Filão?}
{143}{}{Então onde está?}
{144}{}{Onde vault?}
{145}{}{Não poderia te dizer. Carne Seca sempre afirmou que tinha um mapa, mas ninguém nunca viu.}
{146}{}{Carne Seca?}
{147}{}{Perguntar mais.}
{148}{}{Bem, já é mais do que eu tinha antes.}
{149}{}{O cara. Saltbeef é um velho garimpeiro de urânio, mais precisamente, um bêbado. Ele agora mora nos arredores do rancho Westin.}
{150}{}{Outra pergunta...}
{151}{}{Obrigado pela história.}
{152}{}{Bem, eu esperava ganhar algum dinheiro com isso. Te deixo por $}
{153}{}{Talvez mais tarde, outra pergunta...}
{154}{}{Talvez mais tarde, preciso ir.}
{155}{}{Carne Seca é um velho garimpeiro de urânio. Ele agora mora nos arredores do rancho Westin.}
{156}{}{Outra pergunta...}
{157}{}{Obrigado pela história.}
{158}{}{É melhor ir falar com a Presidente Tandi. Ouvi dizer que ela está procurando algum tipo de pessoa especial.}
{159}{}{Outra pergunta...}
{160}{}{Obrigado.}
{161}{}{Poderia... Existe um grupo contra a escravidão e... bem, a maioria dos outros vícios também. Às vezes você pode encontrá-los na grande loja, trabalhando em algum carro.}
{162}{}{Outra pergunta...}
{163}{}{Obrigado.}
{164}{}{Ei, tire as mãos disso, vagabundo!}
{165}{}{Cuidado com isso! Leva apenas uma pequena quantidade para se expor.}
{166}{}{Coloque isso de volta! Você pode se machucar gravemente com isso.}
{167}{}{Esses remédios são para o Sr. Westin, não para você. Devolva.}
{168}{}{Se afaste disso. Precisa de cuidado, não gostaria que o Sr. Westin tomasse os remédios errados.}
{169}{}{Cuidado! Acabei de medir a dose do Sr. Westin.}
{170}{}{Eu sou o Doutor Jubilee. O que há de errado, senhorita?}
{171}{}{O que há de errado, senhorita?}
{172}{}{Aí está você, senhorita.}
{173}{}{Bem, você não deve se preocupar, senhorita. Contanto que você não sobrecarregue seu sistema, ele provavelmente sobreviverá a todos. Claro, se você decidir entre meus cuidados médicos ou seus medicamentos.}
{174}{}{Claro. Aqui estão os $}
{175}{}{Obrigado, Já tentei tirar o dinheiro daquele Carne Seca, mas o condenado nunca tem nada.}
{176}{}{.}
