{100}{}{Você vê uma mulher jovem e bonita vestida com roupas de combate.}
{101}{}{É a Elise.}
{102}{}{Ela tem um ar de superioridade, que ela usa para dar ordens e fazer com que as pessoas a obedeçam.}
{103}{}{O que você quer?}
{104}{}{Você novamente?}
{105}{}{Karl me mandou aqui.}
{106}{}{Doc Jubilee disse que eu devia falar com você.}
{107}{}{Quem é você?}
{108}{}{Hã?}
{109}{}{Eu procuro uma organização. Uma que odeia a escravidão. Eles são conhecidos como New California Rangers.}
{110}{}{Você pode consertar meu carro?}
{111}{}{Uh - Eu achei que esse lugar era deserto.}
{112}{}{Ele fez isso? O que ele te disse?}
{113}{}{Não muito. Que vocês são boas pessoas e eu pensei em me juntar com vocês.}
{114}{}{Disse que você tinha pago um bom dinheiro.}
{115}{}{Me chamo Elise. Esse é Gond. Nós somos membros de um 'grupo' que tenta fazer o que é certo para as pessoas.}
{116}{}{Você parece não gostar de caridade ou igreja.}
{117}{}{Parece interessante. Certo em que sentido?}
{118}{}{Eu só quero que consertem meu carro.}
{119}{}{Apenas saia daqui. Volte para o bar na rua principal.}
{120}{}{Odeia escravidão, hum. Interessante. O que você faria se achasse essa organização?}
{121}{}{Eu iria pedir para me juntar a eles.}
{122}{}{Eu iria chutar a bunda deles.}
{123}{}{Nada.}
{124}{}{Não te interessa. Agora saia.}
{125}{}{Saímos do negócio de carros. Fechamos permanentemente. Tchau.}
{126}{}{Isso é não. Tchau.}
{127}{}{Tudo bem, então me diga. Qual sua opinião sobre os escravizadores?}
{128}{}{Odeio eles. Repugnantes, escória do planeta.}
{129}{}{Se eles não mexerem comigo, eu deixo eles em paz.}
{130}{}{Alguns dos meus melhores amigos são escravizadores.}
{131}{}{Você só se importa com o dinheiro?}
{132}{}{Claro que não. Eu acredito na verdade, justiça e na luta pelos oprimidos,}
{133}{}{É um começo - enquanto alguém daria um nome melhor para uma causa de luta. }
{134}{}{O que mais tem aí?}
{135}{}{Não minta para mim. Eu consigo ver que tipo de pessoa você é. Tchau.}
{136}{}{Se você não sabe, então estou perdendo meu tempo. Tchau.}
{137}{}{Não, nós não somos uma organização religiosa. Talvez eu possa te perguntar uma coisa?}
{138}{}{Não, vá em frente.}
{139}{}{Não tão rápido. Você precisa passar em um teste para se juntar aos Rangers.}
{140}{}{Tudo bem. Me diga o que fazer.}
{141}{}{Teste? O que é isso - escola?}
{142}{}{Tem um cativeiro do lado de fora da cidade. Talvez você tenha visto o lugar. Solte os escravos e volte aqui falar com a gente.}
{143}{}{Eu posso fazer isso.}
{144}{}{Nem a pau. Eu não quero arrumar problemas por aqui.}
{145}{}{Bem, é seu dia de sorte.}
{146}{}{Esse tipo de atitude é a primeira coisa que permite a atrocidade da escravidão existir. Me desculpe, mas não tem lugar para você na nossa organização.}
{147}{}{Ok.}
{148}{}{Então, mudou de idéia? Pronto para provar seu valor?}
{149}{}{Com certeza.}
{150}{}{O que você quis fazer?}
{151}{}{Você não está fazendo nada? Não volte aqui enquanto o serviço não estiver completo.}
{152}{}{Eu já ouvi as notícias. Você libertou os escravos. Bom trabalho! Então, você está pronto para ser um Ranger?}
{153}{}{Sim.}
{154}{}{Não.}
{155}{}{Eu ouvi que foi você que libertou todos os escravos do lado de fora da cidade. Foi legal o que você fez e eu queria apertar a sua mão.}
{156}{}{Obrigado.}
{157}{}{Simples. Nós acreditamos que a escravidão seja errada e faremos o que pudermos para lutar contra isso. Em NCR, nós temos muitos amigos poderosos. Graças a eles nós já banimos o cativeiro do sul, mas agora nós esperamos espalhar esse pensamento para as pessoas do norte.}
{158}{}{Os Rangers parece que ser um grupo em que seria uma honra me unir. To dentro.}
{159}{}{Interessante... Eu irei pensar no que você me disse.}
{160}{}{Você jura lutar contra a escravidão sempre que puder e ajudar os Rangers sempre que eles precisarem?}
{161}{}{Sim.}
{162}{}{Não.}
{163}{}{Parabéns, agora você é um Ranger.}
{164}{}{Bem vindo, companheiro Ranger. Acho que não tem muito o que você fazer por aqui agora. A maioria dos nossos guardas já estão em patrulha. Eu vou falar para os outros guardas que você é um de nós agora. Eu não quero que você seja recebido a tiros quando encontrar os outros guardas.}
{165}{}{Bem, nós estamos sempre procurando boas pessoas para promover a nossa causa. Se você mudar de idéia, me procure. Você tem certeza que não quer aceitar essa oportunidade de se juntar a nós?}
{166}{}{Tenho certeza.}
{167}{}{Bem, agora que você mencionou isso, eu acho que gostaria de ser um Ranger.}
{168}{}{Entendo. Bem, eu represento um grupo chamado New Califórnia Rangers. Alguém com suas qualidades seria qualificado para entrar no grupo. Está interessado?}
{169}{}{Ótimo! Eu to dentro.}
{170}{}{Parece interessante. O que você pode me dizer sobre os Rangers?}
{171}{}{Entendo. Bem, obrigado pela conversa, mas não posso dizer mais nada. Se você mudar de idéia, volte para falar comigo.}
{172}{}{Ok.}
{173}{}{Esse é o problema, eu vou te pedir para sair da minha frente. Agora!}
{174}{}{Ok.}
{175}{}{Um escravizador! Antes que eu arranque sua tatuagem na bala!}
{176}{}{Com certeza.}
{177}{}{Tenta a sorte!}
{178}{}{Nós temos agentes e simpatizantes em algumas cidades do norte. Nós estamos promovendo a palavra e acabando com os escravizadores sempre que possível.}
{179}{}{Olá de novo. Você mudou de idéia sobre se juntar a nós?}
{180}{}{Não importa.}
{181}{}{Você não é bem vindo aqui. Agora saia antes que eu use a violência.}
{182}{}{Eu não sei o que você disse para o Gond, mas você vai pagar!}
