{100}{}{Você vê um velho magricela com uma caneta presa atrás da orelha e óculos equilibrados na ponta do nariz.}
{101}{}{É Vortis, o dono deste centro de escravos.}
{102}{}{Ele tem cerca de três dentes. Seus dedos e camisa estão manchados com tinta azul. Há uma tatuagem de escravo desbotada em sua testa.}
{103}{}{Então... o que você quer?}
{104}{}{Irmão, bem-vindo ao salão de Vortis. Como posso ajudá-lo?}
{105}{}{Você está começando a me irritar.}
{106}{}{Este é MEU lugar, e eu, Vortis, dirijo um negócio honesto e legítimo, não importa o que alguém na NCR te diga. Já que a NCR não permite escravos dentro dos portões, eu cuido deles para pessoas que têm negócios lá dentro.}
{107}{}{O que passa com você? É estúpido? Este é um centro de escravos. Eu tenho uma licença para isso.}
{108}{}{}
{109}{}{Preciso fazer algumas perguntas.}
{110}{}{Estou procurando trabalho.}
{111}{}{Uh?}
{112}{}{Isso não é uma latrina? Vou sair.}
{113}{}{O que fazem nesse lugar?}
{114}{}{Nada, lugar errado.}
{115}{}{Oh, olha só, o bom cidadão, modelo da sociedade. Rapazes, levem este modelo hipócrita de virtude santa para fora da minha vista!}
{116}{}{Que se foda.}
{117}{}{Bem?}
{118}{}{Estou procurando a Vault 13.}
{119}{}{Você tem um GECK?}
{120}{}{O que você pode me dizer sobre essa cidade?}
{121}{}{Você é a escória escravista! Por que eu não deveria matar você?}
{122}{}{Já ouvi falar desses caras... os Rangers da Nova California. Eles te deram algum problema?}
{123}{}{Se importa se eu der uma olhada?}
{124}{}{Trabalho? Bem... pode ter algo. Você já ouviu falar dos Rangers da Nova California?}
{125}{}{Sim.}
{126}{}{Não.}
{127}{}{Que se foda. Rapazes, levem esse lixo irritante para longe da minha vista.}
{128}{}{Me chupa!}
{129}{}{Vault 13! Saia daqui. Esse lugar é um mito. Vault 13 é minha bunda.}
{130}{}{Outra pergunta...}
{131}{}{Bem, obrigado por nada.}
{132}{}{Um o quê? Bem, seja o que for, eu não tenho.}
{133}{}{Outra pergunta...}
{134}{}{Bem, obrigado por nada.}
{135}{}{República da Nova Califórnia - nada além de comerciantes e tipos moderados. Eles não gostam nem um pouco de escravistas ou escravidão, que merda, e isso é problema meu.}
{136}{}{Outra pergunta...}
{137}{}{Obrigado, tenho que ir.}
{138}{}{Alguém te guiou errado. Não tenho problemas com ninguém, especialmente com nenhum Ranger. Eu tenho todos os requisitos legais, eles não têm nada contra mim.}
{139}{}{Outra pergunta...}
{140}{}{Diga o que quiser. Vou embora.}
{141}{}{Sim, posso ter algumas opiniões sobre os Rangers. Você está procurando trabalho?}
{142}{}{Sim.}
{143}{}{Não.}
{144}{}{Não, você não pode ficar bisbilhotando, idiota! Isso não é um museu!}
{145}{}{Outra pergunta...}
{146}{}{Você é muito sensível para o meu gosto. Vou embora.}
{147}{}{Bem, você deve saber que algumas pessoas os veem como um problema em potencial. Seria extremamente útil se tivéssemos um mapa de seus esconderijos ao norte, New Reno, Klamath, onde quer que seja. Eu estaria disposto a pagar, digamos, $500 por algo desse tipo. Você acha que poderia conseguir isso para mim?}
{148}{}{Com certeza.}
{149}{}{Acho que não.}
{150}{}{Então deixe-me te dizer: Esses Rangers têm a vontade de acabar com a escravidão e os escravistas, tudo usando a força. Eles têm criado muitos problemas para as pessoas que trabalham duro.}
{151}{}{Eles trabalham em segredo, especialmente no norte.}
{152}{}{Caramba, eu tenho que soletrar isso para você? Eles atacam escravistas, liberam o estoque e os dirigem ao sul, para as terras da NCR, onde a escravidão é ilegal. Te interessa então?}
{153}{}{Não existe "e"! Você quer o emprego ou não?}
{154}{}{E?}
{155}{}{Então, o que você quer que eu faça?}
{156}{}{Certo. Quando eu conseguir um mapa, virei aqui.}
{157}{}{Onde vou encontrar um mapa?}
{158}{}{Ok, mas eu tenho algumas outras perguntas.}
{159}{}{Eu estou trabalhando nisso. Vejo você por ai.}
{160}{}{E como eu deveria saber!? Se eu soubesse já teria um, não é? Olha, deve ter uma cela na cidade. Encontre e veja o que você pode fazer.}
{161}{}{Só mais algumas perguntas.}
{162}{}{Tudo bem. Eu voltarei.}
{163}{}{Já voltou. Você conseguiu esse mapa?}
{164}{}{Sim.}
{165}{}{Não.}
{166}{}{Ainda estou esperando você terminar o primeiro trabalho!}
{167}{}{Ah sim, esqueci.}
{168}{}{Não desde que você fez o seu trabalho. Obrigado.}
{169}{}{Só uma ou outra pergunta.}
{170}{}{Não há problema. Tchau.}
{171}{}{Bom trabalho. Agora é melhor você sumir, para o caso daqueles Rangers descobrirem.}
{172}{}{Prazer fazer negócios.}
{173}{}{Bem, não fique por aqui, seu idiota! Alguém vai desconfiar.}
{174}{}{Tudo bem, entendi a dica.}
{175}{}{Mas que merda! Guardas! Temos um intruso!}
{176}{}{Entre lá e eu vou explodir sua cabeça. Entendeu?}
{177}{}{Já é tarde e estamos fechados. Volte pela manhã.}
