{100}{}{Você vê um velho magricela com uma caneta presa atrás da orelha e óculos equilibrados na ponta do nariz.}
{101}{}{É Vortis, o dono deste centro de escravos.}
{102}{}{He's got about three teeth. His fingers and shirt are stained with blue ink. There's a really faded slaver's tattoo on his forehead.}
{103}{}{So what do you want?}
{104}{}{Brother, welcome to Vortis' hall. How can I help you?}
{105}{}{You're starting to annoy me.}
{106}{}{This place is my place and I, Vortis, run an honest and legitimate business no matter what anybody in NCR tells you. Since NCR doesn't allow slaves inside the gates, I mind them for folks who've got business inside.}
{107}{}{What are you, dense? This is a slave pen. I got licenses for it.}
{108}{}{}
{109}{}{Just got some questions.}
{110}{}{Estou procurando trabalho.}
{111}{}{Uh?}
{112}{}{Not outhouse? Me go away.}
{113}{}{What's this place do?}
{114}{}{Nothing. Wrong place.}
{115}{}{Oh, look - the goody two-shoes, lollipop kid. Boys, escort this hypocritical paragon of saintly virtue out of my sight!}
{116}{}{Fuck this.}
{117}{}{Bem?}
{118}{}{Estou procurando a Vault 13.}
{119}{}{Você tem um GECK?}
{120}{}{O que você pode me dizer sobre essa cidade?}
{121}{}{You're slaver scum! Why shouldn't I kill you?}
{122}{}{I heard there's these guys - New California Rangers. They been giving you any trouble?}
{123}{}{Mind if I have a look around?}
{124}{}{Work? Well... there might be something. You ever hear of the New California Rangers?}
{125}{}{Sim.}
{126}{}{Não.}
{127}{}{Fuck you. Boys, escort this annoying crud out of my sight.}
{128}{}{Me chupa!}
{129}{}{Vault 13! Get outta here. Damn place is a myth. Vault 13, my ass.}
{130}{}{Outra pergunta...}
{131}{}{Well, thanks for nothing.}
{132}{}{A what? Well, whatever it is, I ain't got it.}
{133}{}{Outra pergunta...}
{134}{}{Well, thanks for nothing.}
{135}{}{New California Republic - nothing but temperance types and merchants. Got a bug about slavers and slavery, but what the hell, it makes my business.}
{136}{}{Outra pergunta...}
{137}{}{Obrigado, tenho que ir.}
{138}{}{Alguém te guiou errado. Não tenho problemas com ninguém, especialmente com nenhum Ranger. Eu tenho todos os requisitos legais, eles não têm nada contra mim.}
{139}{}{Outra pergunta...}
{140}{}{Diga o que quiser. Vou embora.}
{141}{}{Sim, posso ter algumas opiniões sobre os Rangers. Você está procurando trabalho?}
{142}{}{Sim.}
{143}{}{Não.}
{144}{}{Não, você não pode ficar bisbilhotando, idiota! Isso não é um museu!}
{145}{}{Outra pergunta...}
{146}{}{Você é muito sensível para o meu gosto. Vou embora.}
{147}{}{Bem, você deve saber que algumas pessoas os veem como um problema em potencial. Seria extremamente útil se tivéssemos um mapa de seus esconderijos ao norte, New Reno, Klamath, onde quer que seja. Eu estaria disposto a pagar, digamos, $500 por algo desse tipo. Você acha que poderia conseguir isso para mim?}
{148}{}{Com certeza.}
{149}{}{Acho que não.}
{150}{}{Então deixe-me te dizer: Esses Rangers têm a vontade de acabar com a escravidão e os escravistas, tudo usando a força. Eles têm criado muitos problemas para as pessoas que trabalham duro.}
{151}{}{Eles trabalham em segredo, especialmente no norte.}
{152}{}{Caramba, eu tenho que soletrar isso para você? Eles atacam escravistas, liberam o estoque e os dirigem ao sul, para as terras da NCR, onde a escravidão é ilegal. Te interessa então?}
{153}{}{Não existe "e"! Você quer o emprego ou não?}
{154}{}{E?}
{155}{}{Então, o que você quer que eu faça?}
{156}{}{Certo. Quando eu conseguir um mapa, virei aqui.}
{157}{}{Onde vou encontrar um mapa?}
{158}{}{Ok, mas eu tenho algumas outras perguntas.}
{159}{}{Eu estou trabalhando nisso. Vejo você por ai.}
{160}{}{E como eu deveria saber!? Se eu soubesse já teria um, não é? Olha, deve ter uma cela na cidade. Encontre e veja o que você pode fazer.}
{161}{}{Só mais algumas perguntas.}
{162}{}{Tudo bem. Eu voltarei.}
{163}{}{Já voltou. Você conseguiu esse mapa?}
{164}{}{Sim.}
{165}{}{Não.}
{166}{}{Ainda estou esperando você terminar o primeiro trabalho!}
{167}{}{Ah sim, esqueci.}
{168}{}{Não desde que você fez o seu trabalho. Obrigado.}
{169}{}{Só uma ou outra pergunta.}
{170}{}{Não há problema. Tchau.}
{171}{}{Bom trabalho. Agora é melhor você sumir, para o caso daqueles Rangers descobrirem.}
{172}{}{Prazer fazer negócios.}
{173}{}{Bem, não fique por aqui, seu idiota! Alguém vai desconfiar.}
{174}{}{Tudo bem, entendi a dica.}
{175}{}{Mas que merda! Guardas! Temos um intruso!}
{176}{}{Entre lá e eu vou explodir sua cabeça. Entendeu?}
{177}{}{Já é tarde e estamos fechados. Volte pela manhã.}
