{100}{}{You see a scrawny old guy with a pen stuck behind his ear and spectacles balanced on the end of his nose.}
{101}{}{It's Vortis, the owner of this slave pen.}
{102}{}{He's got about three teeth. His fingers and shirt are stained with blue ink. There's a really faded slaver's tattoo on his forehead.}
{103}{}{So what do you want?}
{104}{}{Brother, welcome to Vortis' hall. How can I help you?}
{105}{}{You're starting to annoy me.}
{106}{}{This place is my place and I, Vortis, run an honest and legitimate business no matter what anybody in NCR tells you. Since NCR doesn't allow slaves inside the gates, I mind them for folks who've got business inside.}
{107}{}{What are you, dense? This is a slave pen. I got licenses for it.}
{108}{}{}
{109}{}{Just got some questions.}
{110}{}{Estou procurando trabalho.}
{111}{}{Uh?}
{112}{}{Not outhouse? Me go away.}
{113}{}{What's this place do?}
{114}{}{Nothing. Wrong place.}
{115}{}{Oh, look - the goody two-shoes, lollipop kid. Boys, escort this hypocritical paragon of saintly virtue out of my sight!}
{116}{}{Fuck this.}
{117}{}{Bem?}
{118}{}{Estou procurando a Vault 13.}
{119}{}{Você tem um GECK?}
{120}{}{O que você pode me dizer sobre essa cidade?}
{121}{}{You're slaver scum! Why shouldn't I kill you?}
{122}{}{I heard there's these guys - New California Rangers. They been giving you any trouble?}
{123}{}{Mind if I have a look around?}
{124}{}{Work? Well... there might be something. You ever hear of the New California Rangers?}
{125}{}{Sim.}
{126}{}{Não.}
{127}{}{Fuck you. Boys, escort this annoying crud out of my sight.}
{128}{}{Bite me!}
{129}{}{Vault 13! Get outta here. Damn place is a myth. Vault 13, my ass.}
{130}{}{Another question...}
{131}{}{Well, thanks for nothing.}
{132}{}{A what? Well, whatever it is, I ain't got it.}
{133}{}{Another question...}
{134}{}{Well, thanks for nothing.}
{135}{}{New California Republic - nothing but temperance types and merchants. Got a bug about slavers and slavery, but what the hell, it makes my business.}
{136}{}{Another question...}
{137}{}{Obrigado, tenho que ir.}
{138}{}{Alguém te guiou errado. Não tenho problemas com ninguém, especialmente com nenhum Ranger. Eu tenho todos os requisitos legais, eles não têm nada contra mim.}
{139}{}{Another question...}
{140}{}{Diga o que quiser. Vou embora.}
{141}{}{Sim, posso ter algumas opiniões sobre os Rangers. Você está procurando trabalho?}
{142}{}{Sim.}
{143}{}{Não.}
{144}{}{Não, você não pode ficar bisbilhotando, idiota! Isso não é um museu!}
{145}{}{Another question...}
{146}{}{Você é muito sensível para o meu gosto. Vou embora.}
{147}{}{Bem, você deve saber que algumas pessoas os veem como um problema em potencial. Seria extremamente útil se tivéssemos um mapa de seus esconderijos ao norte, New Reno, Klamath, onde quer que seja. Eu estaria disposto a pagar, digamos, $500 por algo desse tipo. Você acha que poderia conseguir isso para mim?}
{148}{}{Com certeza.}
{149}{}{Acho que não.}
{150}{}{Let me tell you, then. These Rangers have got it in their heads to wipe out slavery and slavers - by force. They've been creating a lot of trouble for hard working folks.}
{151}{}{They work in secret, especially up north.}
{152}{}{Jeez, I got to spell this out for you? They raid slavers, drive off the stock, and smuggle 'em down south to NCR lands where slavery's illegal. So you interested?}
{153}{}{There is no "and"! You want the job or not?}
{154}{}{E?}
{155}{}{So what you want me to do?}
{156}{}{Fine. When you get me a map, I'll be here.}
{157}{}{Where am I going to find a map?}
{158}{}{Okay, I got some other questions, though.}
{159}{}{I'm on it. I'll see you then.}
{160}{}{How the hell should I know!? If I knew, I'd have it, wouldn't I? Look, there's supposed to be a cell in town. Find them and see what you can do.}
{161}{}{Just a few more questions.}
{162}{}{Alright. I'll be back.}
{163}{}{You're back again. Did you get that map?}
{164}{}{Sim.}
{165}{}{Não.}
{166}{}{I'm still waiting for you to finish the first job!}
{167}{}{Oh yeah, I forgot.}
{168}{}{Not since you did your job. Thanks.}
{169}{}{Just a question or two.}
{170}{}{Não há problema. Tchau.}
{171}{}{Good work. Now you best make yourself scarce, in case those Rangers ever wise up.}
{172}{}{Prazer fazer negócios.}
{173}{}{Well don't hang around here, you moron! Somebody'll get suspicious.}
{174}{}{All right, I get the hint.}
{175}{}{What the fuck? Guards! We got an intruder!}
{176}{}{Go in there and I'll blow your head off. Understand?}
{177}{}{Já é tarde e estamos fechados. Volte pela manhã.}
