{100}{}{You see a villager.}
{101}{}{You see a villager.}
{102}{}{Olá.}
{103}{}{Bom dia.}
{104}{}{Bem-vindo à nossa aldeia.}
{105}{}{Os monstros nos protegem.}
{106}{}{Hurry back.}
{107}{}{We'll need those guns soon.}
{108}{}{Olá.}
{109}{}{Leave now!}
{110}{}{Go back to where you came from!}
{111}{}{Saia já daqui!}
{112}{}{We're safe now.}
{113}{}{Obrigado.}
{114}{}{Bless you, wanderer.}
