{100}{}{Você vê um homem baixo e jovial.}
{101}{}{Você vê Harry Alegre, o dono da loja.}
{102}{}{Opa, olá... o que posso fazer por você?}
{103}{}{Gostaria de negociar. Posso ver o que você tem a venda?}
{104}{}{Ainda está vendendo aquele arado?}
{105}{}{Compro voce}
{106}{}{Nada por hoje, valeu.}
{107}{}{Desculpa. Não posso ajudá-lo, amigo.}
{108}{}{Bem, sim, tenho. Te deixo com você por... bem, oitocentos.}
{109}{}{Te dou seiscentos por ele.}
{110}{}{Negocio fechado, eu levo.}
{111}{}{Eh, oitocentos? Eu voltarei... com o dinheiro.}
{112}{}{Esqueça. Os Smiths podem morrer de fome.}
{113}{}{É seu. [Embolsa o dinheiro.] Você mesmo leva ou precisa que seja entregue
 em algum lugar?}
{114}{}{Pode deixar com os Smiths.}
{115}{}{Desculpe, amigo. Vai te custar oitocentos.}
{119}{}{Você precisa do dinheiro para pegar, amigo.}
{120}{}{Eu volto com o dinheiro.}
{121}{}{Sem problemas. Tenho que entregar agora mesmo.}
{122}{}{Pensou em colar, não é? Maldito ladrão... guardas! Guardas!}
