call ..\p CCACON
call ..\p CCATECH
call ..\p CCCHEAT
call ..\p CCCHRIS
call ..\p CCCOMP1
call ..\p CCCOMP2
call ..\p CCCOOK
call ..\p CCDOCTOR
call ..\p CCDRGRD
call ..\p CCDRILL
call ..\p CCFAK9
call ..\p CCGGBAK
call ..\p CCGGUARD
call ..\p CCGRDCA
call ..\p CCGRDPA
call ..\p CCK9
call ..\p CCKEVIN
call ..\p CCMANDR
call ..\p CCMEDGRD
call ..\p CCNCOMP
call ..\p CCQMSTR
call ..\p CCQUINCY
call ..\p CCRAUL
call ..\p CCTECH1
call ..\p CCTECH2
call ..\p CCTURRET
call ..\p CCXARN
call ..\p CICMDWCH
call ..\p CICRISDR
call ..\p CIDOCWCH
call ..\p CIMINE
call ..\p CIQUNWCH
call ..\p CIRULWCH
call ..\p CIVENT
call ..\p CSALARM
call ..\p CSAREA
call ..\p CSAREA2
call ..\p CSGATE
call ..\p CSOPEN
call ..\p CSOPEN2
call ..\p CSOPEN3
call ..\p CSTOUCH
call ..\p CSVENT
call ..\p CSXDOOR
call ..\p CTFOB
call ..\p CTK9PART
call ..\p CTPLANS
call ..\p CTSOUND
