{100}{}{Вы видите скучающего человека, одетого в кожаную броню.}
{101}{}{Перед вами Макс, охранник каравана.}
{102}{}{Вы видите скучающего, покрытого пылью, человека в кожаной броне. Судя по уверенной походке и тому, что от него воняет браминами, это наверняка охранник каравана.}
{103}{}{Чем могу служить?}
{104}{}{Гым?}
{105}{}{Моя тут работать!}
{106}{}{Кто вы?}
{107}{}{Что ты можешь рассказать мне о Чеде?}
{108}{}{У меня терпения для идиотов нет. Прости, приятель, найди кого-нибудь другого для своих игр.}
{109}{}{::принюхивается::}
{110}{}{Я Макс. Я один из охранников каравана.}
{111}{}{Что ты можешь рассказать мне о Чеде?}
{112}{}{Спасибо. Пока.}
{113}{}{I don't like him much. He seems to get always some extra money from his caravan jobs. It's really unfair.}
{114}{}{Well, Marcus suspects that he is skimming some of the money that supposed to go Broken Hills.}
{115}{}{Спасибо. Пока.}
{116}{}{Thanks. I'm sure glad that this is over. You better watch your back thought.}
{117}{}{Пока.}
{118}{}{Это враг! Умри!}
{119}{}{Упс.}
{120}{}{(Lowers his voice and looks around) That's gotta be it. I once saw myself that he was taking some "slice" of that money he got from uranium shipment from Gecko.}
{121}{}{Really? Then why you haven't tell about it to Marcus then?}
{122}{}{Are you duff? If I go to tell it, a lot of people in this town won't even look at me. Besides I might get some kind of revenge.}
{123}{}{Hmm, I could tell it about to Marcus, cause I don't plan to stay here too long anyway.}
{124}{}{Ok. Do what you want, but don't tell anything about me. And we never had this conversation, ok?}
{125}{}{Don't worry, I don't want to get you in any trouble, bye.}
