{100}{}{You see a card dealer.}
{101}{}{Вы видите Монте Три Карты.}
{150}{}{Вы видите высокого, очень худого старика с дочерна загорелым лицом. Он настолько худой, что кажется, будто он сделан из хвороста.}
{151}{}{You see Three-Card Monte. He scopes out the street, spots you, and nods.}
{152}{}{You see Three-Card Monte. He scopes out the street, spots you, and nods.}
{200}{}{Не понимаю, как это меня угораздило проиграть...}
{201}{}{Just keep walking... Monte's not in business today.}
{202}{}{Did I palm the wrong card?}
{203}{}{How did that stupid tribal keep picking the right card?}
{205}{}{Э-э-эй! Герой! Ты в порядке, ты ничего.}
{206}{}{::Показывает вам два больших пальца::}
{207}{}{::Smiles, nods::}
{208}{}{You done good, hero. You done good.}
{215}{}{Где, черт дери, мои карты? Они ТОЛЬКО ЧТО здесь были.}
{216}{}{Goddamn car key gnomes, now they're going after my playing cards.}
{220}{}{Эй, приятель, даже не думай ходить в казино. Сыграй лучше с Монте.}
{221}{}{Looking to take a chance, pal? Best odds in New Reno! C'mon...}
{222}{}{You, pal. You look like a lucky guy, c'mon over.}
{223}{}{Anybody looking to play? Free mon-ay, free mon-ay.}
{224}{}{C'mon over and play. Just the other day, I guy won 50 chips off me, easy.}
{225}{}{Easy, just guess the Queen, red Queen, and you win. That easy.}
{226}{}{You allergic to easy money? Then get over here.}
{227}{}{Everybody's winning today... you want to be the next one?}
{228}{}{Casinos'll rip you off, rob you blind... Monte treats you right, gives you a fair chance.}
{229}{}{Looking to take a chance, lady? Best odds in New Reno! C'mon...}
{230}{}{You allergic to easy money, lady? Then get over here.}
{231}{}{You, lady. You look like a lucky gal, c'mon over.}
{232}{}{Yo, lady, don't bother with the casinos. Come play with Monte.}
{233}{}{Монте сегодня не играет, друг мой. Кто-то спер мои чертовы карты.}
{234}{}{[Старик улыбается, и вокруг его глаз образуются морщинки.] Хочешь сыграть, друг мой?}
{235}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{236}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{237}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, friend?}
{238}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{239}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{240}{}{Three-Card Monte's the name, and the game's the same as the name. Slap down 20 chips, and we'll get down to it.}
{241}{}{You cheater. You no play fair}
{242}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{243}{}{Uh, me flattered but me not want to get down to it now... byyyyye}
{244}{}{Хиляй отсюда}
{245}{}{Let's play.}
{246}{}{Uh, get down to what?}
{247}{}{I'm familiar with the game. Let's play.}
{248}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{249}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{250}{}{Не сегодня, спасибо.}
{251}{}{К чему приступать? К игре, конечно!}
{252}{}{See... (shows you three cards) ...one of these is a queen. I lay them face down, shuffle them, then you pick which one the queen is. If you're right, you win.}
{253}{}{That simple, pal.}
{254}{}{That simple, lady.}
{255}{}{I'm not playing with a cheater like you.}
{256}{}{Could you explain the rules again?}
{257}{}{Sounds simple enough. Let's play. Here's 20 chips.}
{258}{}{Не сегодня, спасибо.}
{260}{}{[Вы выкладываете деньги. Монте кивает, показывает вам карты, затем переворачивает их рубашкой вверх и в течение нескольких секунд мешает их.]}
{261}{}{So... which one's the queen, pal?}
{262}{}{So... which one's the queen, lady?}
{263}{}{(You think it's the one on the left.)}
{264}{}{(You think it's the one in the middle.)}
{265}{}{(You think it's the one on the right.)}
{266}{}{(You don't know. The cards moved too fast.)}
{267}{}{Lucy leftie}
{268}{}{Middle of th'road}
{269}{}{Rightie tightie}
{270}{}{The one on the left.}
{271}{}{The one on the right.}
{272}{}{The one in the middle.}
{280}{}{(Монте переворачивает карту. Это }
{281}{}{Sorry, pal, not this time, but you were CLOSE.}
{282}{}{Sorry, lady, not this time, but you were CLOSE.}
{283}{}{You sure do got the eye for it, though. Wanna try again?}
{284}{}{You cheater. You no play fair}
{285}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{286}{}{Nuh-uh Me no LIKE game BYYYYE}
{287}{}{I'm not playing with a cheater like you.}
{288}{}{Sure. Here's 20 chips.}
{289}{}{Нет, спасибо.}
{300}{}{[Вы выкладываете деньги. Монте кивает, показывает вам карты, затем переворачивает их рубашкой вверх. В это время он прячет в руку одну из карт, проделав это так быстро, что вы едва успеваете заметить. Затем в течение нескольких секунд он мешает карты.]}
{301}{}{So... which one's the queen, pal?}
{302}{}{So... which one's the queen, lady?}
{303}{}{You put it in sleevie weevie you no play fair}
{304}{}{Lucy leftie}
{305}{}{Middle of th'road}
{306}{}{Rightie tightie}
{307}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{308}{}{The one in your sleeve.}
{309}{}{The one on the left.}
{310}{}{The one on the right.}
{311}{}{The one in the middle.}
{320}{}{ЧТО ты сказал, приятель?}
{321}{}{WHAT did you say, lady?}
{322}{}{You accusing me of cheating?}
{323}{}{Uh-uh. Me KNOW you cheet}
{324}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{325}{}{Да.}
{326}{}{Screw this. Keep the money, I'm outta here.}
{330}{}{Послушай, у меня нет времени успокаивать неудачников. Ты платишь деньги, ты получаешь возможность выиграть. Хочешь СЫГРАТЬ - пожалуйста. Но если ты собираешься при каждом проигрыше так скулить, лучше убирайся!}
{331}{}{ME BREAK YOU}
{332}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{333}{}{That's it. You're dead.}
{334}{}{All right, all right. I'm sorry. Here's 20 chips. Let's play again.}
{335}{}{Screw you. Keep the money, I'm outta here.}
{340}{}{[Вы выкладываете деньги. Монте кивает, затем кидает карты на землю и несколько секунд их перетасовывает.]}
{341}{}{So... which one's the queen, pal?}
{342}{}{So... which one's the queen, lady?}
{343}{}{(Monte's using his normal deck! You need to steal his other deck to complete the switch.)}
{344}{}{You put it in sleevie weevie you no play fair}
{345}{}{Uh... Lucy leftie}
{346}{}{Uh... Middle of th'road}
{347}{}{Uh... Rightie tightie}
{348}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{349}{}{The one in your sleeve.}
{350}{}{Uh, the one on the left.}
{351}{}{Uh, the one on the right.}
{352}{}{Uh, the one in the middle.}
{360}{}{[Вы выкладываете деньги. Монте кивает, показывает вам карты, затем переворачивает их рубашкой вверх и в течение нескольких секунд мешает их.]}
{361}{}{(You hand over the cash. Monte looks uncomfortable.) Uh... all right... (Monte puts the cards on the ground and shuffles them.)}
{362}{}{So... which one's the queen, pal?}
{363}{}{So... which one's the queen, lady?}
{364}{}{(Monte's using the marked deck. Any pick is the right one.)}
{365}{}{Leftie! Leftie!}
{366}{}{Rightie! Rightie!}
{367}{}{Middlie! Middlie!}
{368}{}{Oh, I don't know... the one on the left.}
{369}{}{Hmmmm... maybe the one on the right?}
{370}{}{Gee, I'm not sure... I think it's the one in the middle.}
{375}{}{[Монте переворачивает карту. Это дама червей. От шока он застывает на месте.] А?.. Кхе. Э...}
{376}{}{guess you win, pal.}
{377}{}{guess you win, lady.}
{378}{}{(He hands over the cash reluctantly.)}
{379}{}{Again! Again!}
{380}{}{Thanx me go now}
{381}{}{So we gonna play again or what? C'mon, Monte. I'm just getting started.}
{382}{}{Well, thanks, Monte. See you later.}
{385}{}{[Монте переворачивает карту. Это дама червей. Он в шоке.] А?... Хе... э...}
{386}{}{guess you win, pal.}
{387}{}{guess you win, lady.}
{388}{}{That cleans me out, though... (Looks at you weakly) Anything else I could do for you?}
{389}{}{Nuttin. Me just wanted sum extra EXP. Bye. Bye.}
{390}{}{What have you GOT?}
{391}{}{Why don't you give me some information?}
{392}{}{Forget it, Monte. We'll call it even for today.}
{400}{}{[Кажется, его задели за живое.] Э... ну, у меня есть кое-что... но оно стоит НАМНОГО больше, чем тебе удалось выиграть... но все равно...}
{401}{}{Well? What is it?}
{402}{}{If it's worth more to you than dying on Golgotha because you welched on a debt, that's your problem. I'd think
 about it, if I were you.}
{404}{}{Э... хмм... зависит от того, что ты хочешь знать.}
{405}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{406}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{407}{}{You know where my car is, Monte?}
{408}{}{Got anything you think I should know?}
{409}{}{Nevermind, Monte. We're even. See you later.}
{415}{}{Э... что ж... послушай, я тебе этого не говорил, но я ставлю на Ренеско, этого засранца, который заведует аптекой в западном районе. Я точно не знаю, продавал ли он парню СПЕЦИАЛЬНО, но он что-то знает. Это все, что я тебе скажу.}
{416}{}{All right then, Monte. We're even.}
{420}{}{Э... что ж... [похоже, в нем происходит какая-то внутренняя борьба] ...послушай, я тебе этого не говорил, но на твоем месте я бы проверил подвал Десперадо.}
{421}{}{All right then, Monte. We're even.}
{425}{}{[Прищуривает глаза и наклоняется поближе к вам.] На твоем месте я бы спросил старого доброго Хулио у входа в город. Мимо него ничего не пройдет... а если и пройдет, значит, это его рук дело, если ты меня понимаешь.}
{426}{}{All right then, Monte. We're even.}
{430}{}{Ну... ты знаешь Элдриджа, который заведует оружейным магазином в западном районе? Он говорит, что может усовершенствовать любое оружие, хотя я никогда не видел его за работой. Возможно, тебе стоит осмотреть его заведение повнимательнее... но я тебе этого не говорил.}
{431}{}{All right then, Monte. We're even.}
{435}{}{[Монте нахмуривается при виде вас.] Слушай, я сегодня не играю, ладно? Уходи.}
{436}{}{Can I buy that card you showed me before?}
{437}{}{I wanted some information...}
{438}{}{All right, Monte. I'll leave... for now.}
{440}{}{Не-а. Я с ней ни за что не расстанусь. Точка. Это же НАСТОЯЩАЯ довоенная реликвия... маленький кусочек истории. НИ ЗА ЧТО.}
{441}{}{You making me ANOTHER offer? Look, I told you I ain't selling it.}
{442}{}{How about a thousand chips? I got it with me. It's yours in exchange for that card.}
{443}{}{Not even for 750 chips?}
{444}{}{How about 500 chips?}
{445}{}{250 chips sound about right?}
{446}{}{Ладно. У меня есть еще вопросы...}
{447}{}{Nevermind then, Monte. I'm outta here.}
{450}{}{Глухота напала, что ли? Этой суммы недостаточно даже для того, чтобы заинтересовать меня.}
{451}{}{How about I suggest another amount...?}
{452}{}{У меня есть еще вопросы...}
{453}{}{Nevermind then, Monte. I'm outta here.}
{460}{}{Ну, она мне не НАСТОЛЬКО дорога. Она твоя, приятель. [Он оглядывается по сторонам, затем нагибается, стаскивает ботинок и отворачивает каблук. Изнутри он достает игральную карту.] Держи. Береги ее.}
{461}{}{У меня есть еще вопросы...}
{462}{}{Thanks, Monte. Always a pleasure.}
{465}{}{[Нахмуривается] Буду я говорить или нет, зависит от того, что ты захочешь узнать. И это будет стоить тебе недешево.}
{466}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{467}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{468}{}{You know where my car is, Monte?}
{469}{}{Got anything you think I should know?}
{470}{}{Nevermind then, Monte. I'm outta here.}
{475}{}{Клянусь Голгофой, ни за что я даже не ЗАИКНУСЬ. Отвали.}
{476}{}{Look, that subject's just bad news. Leave it alone, all right?}
{477}{}{You making me another offer? Look, I told you I AIN'T going talk about it.}
{478}{}{A thousand chips change your mind? I got it with me.}
{479}{}{Not even for 750 chips?}
{480}{}{How about 500 chips?}
{481}{}{250 chips sound about right?}
{482}{}{Uh... Golgotha?}
{483}{}{У меня есть еще вопросы...}
{484}{}{Nevermind then, Monte. I'm outta here.}
{490}{}{[Качает головой.] Ни за что. Разговоры на эту тему могут закончиться чьей-то смертью, и не исключено, что моей. Забудь об этом.}
{491}{}{How about if I offered you this...}
{492}{}{У меня есть еще вопросы...}
{493}{}{Nevermind then, Monte. I'm outta here.}
{495}{}{Э... ну... это же куча денег. [Облизывает губы. Кажется, внутри него происходит отчаянная борьба.... но борьба недолгая.] Послушай, я тебе этого не говорил...}
{496}{}{Understood. Go on.}
{500}{}{[Недобро усмехается] Может, я и знаю что-нибудь, а может, и нет. Назови свою цену.}
{501}{}{All right... talk a price.}
{502}{}{How about a thousand chips? I got it with me.}
{503}{}{Not even for 750 chips?}
{504}{}{How about 500 chips?}
{505}{}{250 chips sound about right?}
{506}{}{У меня есть еще вопросы...}
{507}{}{Nevermind then, Monte. I'm outta here.}
{510}{}{Ха! Да на это и ведро говна не купишь. Забудь об этом.}
{511}{}{How about if I offered you this...}
{512}{}{У меня есть еще вопросы...}
{513}{}{Nevermind then, Monte. I'm outta here.}
{515}{}{Во-о-от это по-нашему. [Злобно ухмыляется.] Слушай, я тебе этого не говорил, но на твоем месте я бы проверил подвал Десперадо на Девичьей улице. Там очень много "крыс", ну ты меня понимаешь.}
{516}{}{У меня есть еще вопросы...}
{517}{}{Ясно. Спасибо.}
{520}{}{[Пожимает плечами] Может, я и знаю что-нибудь, а может, и нет. Назови свою цену, и возможно, я расскажу тебе что-нибудь.}
{521}{}{All right... talk a price.}
{522}{}{How about a thousand chips? I got it with me.}
{523}{}{Not even for 750 chips?}
{524}{}{How about 500 chips?}
{525}{}{250 chips sound about right?}
{526}{}{У меня есть еще вопросы...}
{527}{}{Nevermind then, Monte. I'm outta here.}
{530}{}{[Прищуривает глаза, наклоняется поближе к вам.] За такие деньги я ничего не знаю.}
{531}{}{How about if I offered you this...}
{532}{}{У меня есть еще вопросы...}
{533}{}{Nevermind then, Monte. I'm outta here.}
{535}{}{Вот это дело... [Прищуривает глаза и наклоняется поближе к вам.] На твоем месте я бы спросил старого доброго Хулио у входа в город. Мимо него ничего не пройдет... а если и пройдет, значит, это его рук дело, если ты меня понимаешь.}
{536}{}{У меня есть еще вопросы...}
{537}{}{All right then, Monte. Thanks.}
{540}{}{[Пожимает плечами] Я многое слышу, многое вижу. За 200 монет, возможно, я могу поделиться своим опытом, если ты меня понимаешь.}
{541}{}{Here's 200 chips.}
{542}{}{I'll give you 150.}
{543}{}{100 chips or nothing.}
{544}{}{У меня есть еще вопросы...}
{545}{}{Nevermind then, Monte. I'm outta here.}
{550}{}{У тебя приступ глухоты, что ли? Я СКАЗАЛ, 200 монет, значит, 200.}
{551}{}{All right. Here's 200 chips.}
{552}{}{У меня есть еще вопросы...}
{553}{}{Nevermind then, Monte. I'm outta here.}
{555}{}{Done. (Monte leans in) Well, know that guy Eldridge, runs New Reno Arms? He SAYS he does
 weapon upgrades, but I never see him do any work. You might want to check out his place... but you didn't hear that from me.}
{556}{}{У меня есть еще вопросы...}
{557}{}{Understood. Thanks, Monte.}
{560}{}{Могильник к югу от города. Несет аж до самых небес, так вот.}
{561}{}{Oh... I see. Now, about the Wright kid...}
{562}{}{Forget the Wright kid. I had some other questions...}
{563}{}{All right then, Monte. Thanks.}
{565}{}{Ставлю на Ренеско, старого засранца, который заведует аптекой в западном районе. Я точно не знаю, продавал ли он парню СПЕЦИАЛЬНО, но он что-то знает. [Оглядывается] Это все, что я тебе скажу.}
{566}{}{У меня есть еще вопросы...}
{567}{}{All right then, Monte. Thanks.}
{570}{}{[Он оглядывается, нагибается и стаскивает с ноги ботинок. Он отворачивает каблук и вытаскивает карту... на ней изображен человек в странной шляпе, размахивающий битой.] Ну как? Это настоящая довоенная реликвия.}
{571}{}{No, I already have enough inventory items... I'd rather have some information instead.}
{572}{}{Uh, sure. Why not? This'll settle things between us.}
{573}{}{Sorry pal, no chips, no game. Come back when you got more money.}
{574}{}{Sorry lady, no chips, no game. Come back when you got more money.}
{575}{}{Yeah, maybe next time then.}
{576}{}{You quickly swap Monte's deck of cards for the marked deck.}
{600}{}{spades}
{601}{}{hearts}
{602}{}{diamonds}
{603}{}{clubs}
{604}{}{два}
{605}{}{три}
{606}{}{четыре}
{607}{}{пять}
{608}{}{шесть}
{609}{}{семь}
{610}{}{восемь}
{611}{}{девять}
{612}{}{десять}
{613}{}{ }
