{100}{}{Вы видите Лапусю Никки.}
{125}{}{Вы видите крупье.}
{150}{}{Вы видите Лапусю Никки.}
{151}{}{You see Darlin' Nikki. She winks at you.}
{152}{}{Вы видите Лапусю Никки. Она делает вам знаки подойти и сыграть.}
{153}{}{You see Darlin' Nikki. Mason was right about her ass.}
{154}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{155}{}{You see Darlin' Nikki. Mason was right about her ass.}
{156}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{160}{}{Вы видите Лапусю Никки. Она делает вам знаки подойти и сыграть.}
{161}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{162}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{170}{}{Вы видите крупье.}
{171}{}{Вы видите одну из крупье. Она вам подмигивает.}
{172}{}{Вы видите одну из крупье. Она делает вам знаки подойти и сыграть.}
{173}{}{Вы видите одну из крупье. У нее неплохие ножки.}
{174}{}{Вы видите одну из крупье. Ее платье едва прикрывает тело.}
{175}{}{Вы видите одну из крупье. Она пахнет восхитииительно.}
{180}{}{Вы видите одну из крупье. Она делает вам знаки подойти и сыграть.}
{181}{}{Вы видите одну из крупье. Ее платье едва прикрывает тело.}
{182}{}{Вы видите одну из крупье. Ее платье едва прикрывает тело.}
{183}{}{Вы видите одну из крупье. Она делает вам знаки подойти и сыграть.}
{200}{}{::тост::}
{201}{}{::хлопает::}
{202}{}{::присвистывает::}
{203}{}{! Добро пожаловать в казино, суперзвезда!}
{204}{}{Thought you'd forgotten about us while you were saving the world.}
{210}{}{Привет, }
{211}{}{Если вы не откажетесь от компании сегодня вечером...}
{212}{}{Hey, you...(winks)...you looking to gamble?}
{213}{}{Он кажется таким... (вздрагивает)... опасным.}
{214}{}{Добро пожаловать казино, }
{215}{}{Не замолвите за меня словечко перед боссом?}
{216}{}{Привет, мэм. Дайте мне знать, если что-то понадобится.}
{217}{}{Желаете сыграть, мэм?}
{218}{}{Она кажется такой... (вздрагивает)... опасной.}
{220}{}{Похоже, этот уже поставил на кон свою жизнь.}
{221}{}{Э, я думаю, он просто зашел не в то казино...}
{222}{}{Если он не уйдет, пока мальчики его не заметили...}
{223}{}{О-оу. Беда...}
{224}{}{Похоже, эта уже поставила на кон свою жизнь.}
{225}{}{Э, я думаю, она просто зашла не в то казино...}
{226}{}{Если она не уйдет, пока мальчики ее не заметили...}
{230}{}{Эй, качок! Ищешь, где бы спустить пару монет?}
{231}{}{Hey, champ...(winks)...you looking to gamble?}
{232}{}{Hey, champ...(smiles)...wanna take a chance?}
{233}{}{Если вы не откажетесь от компании сегодня вечером...}
{234}{}{Я вот думаю, может, с ним поговорить...}
{235}{}{Привет, }
{236}{}{Если хочешь выиграть немного денег, то ты в правильном месте.}
{237}{}{Best casino in New Reno. In the WORLD, even.}
{238}{}{Госпожа Удача сегодня с нами... все выигрывают!}
{239}{}{Давай сюда, }
{240}{}{Еще выпьешь?}
{241}{}{Добро пожаловать казино, }
{242}{}{Привет, }
{243}{}{Хочешь сыграть, }
{244}{}{Добро пожаловать казино, }
{250}{}{Приветик, секс-символ. Хочешь пропить пару монет?}
{251}{}{Привет, }
{252}{}{Привет, }
{253}{}{Если хочешь выиграть немного денег, }
{254}{}{Best casino in New Reno. In the WORLD, even.}
{255}{}{Госпожа Удача сегодня с нами... все выигрывают!}
{266}{}{Давай сюда, }
{267}{}{Еще выпьешь?}
{268}{}{Добро пожаловать казино, }
{269}{}{Hey there, Mrs. Movie Star. Looking to spend a paycheck?}
{270}{}{Приветик, сладость моя. Хочешь спустить пару монет?}
{271}{}{Hey, sweetie...(winks)...you looking to gamble?}
{272}{}{Hey, sweetie...(smiles)...wanna take a chance?}
{273}{}{Если хочешь выиграть немного денег, то ты в правильном месте.}
{274}{}{Best casino in New Reno. In the WORLD, even.}
{275}{}{Госпожа Удача сегодня с нами... все выигрывают!}
{276}{}{Подходи, не бойся, сруби капусты.}
{277}{}{Еще выпивки, пупсик?}
{278}{}{Добро пожаловать в казино, пупсик.}
{279}{}{Если хочешь сыграть, то этот столик свободен...}
{280}{}{Приветик, пупсик. Хочешь спустить пару монет?}
{281}{}{Хочешь сыграть, зайка?}
{282}{}{Добро пожаловать в казино, пупсик.}
{290}{}{Ну, зайти сюда с твоей стороны редкая дурость, но... делайте ваши ставки. Минимальная ставка 5 монет. Делайте ваши ставки...}
{291}{}{Um... place your bets... minimum bet 5 chips. Place your bets...}
{292}{}{Place your bet, sir. Minimum bet 5 chips. Place your bets...}
{293}{}{Place your bet, ma'am. Minimum bet 5 chips. Place your bets...}
{294}{}{Place your bets, minimum bet 5 chips. Place your bets...}
{295}{}{Моя ставка лучше твоя}
{296}{}{Моя играть карман-ный биляд}
{297}{}{What this game? Can you bet Gecko skin? Me got geck... ooooh... pretty lights over there!}
{298}{}{Bet 5 chips?}
{299}{}{Bet 15 chips?}
{300}{}{Bet 25 chips?}
{301}{}{Bet 50 chips?}
{302}{}{You Nikki?}
{303}{}{How you doing, Nikki?}
{304}{}{Whoa, too rich for my blood. I'm outta here.}
{305}{}{Спасибо, но сегодня я не играю.}
{310}{}{Эээ, ну хорошо, сэр. Возвращайтесь поскорее.}
{311}{}{Эээ, ну хорошо, мэм. Возвращайтесь поскорее.}
{312}{}{Ммм... Говорят, там мозги раздают бесплатно. Наверное, тебе стоит сходить проверить.}
{313}{}{Пока-покаааа.}
{314}{}{Фусечка. }
{315}{}{Uh... brains... what them?}
{320}{}{Хорошо, сэр. Возвращайтесь поскорее.}
{321}{}{Хорошо, мэм. Возвращайтесь поскорее.}
{322}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{323}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{324}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{325}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{326}{}{Спасибо, постараюсь.}
{327}{}{Maybe so, but at least *I* don't live here.}
{330}{}{Сочувствую, сэр. Удачи в следующий раз.}
{331}{}{Сочувствую, мэм. Удачи в следующий раз.}
{332}{}{Сочувствую, удачи в следующий раз.}
{333}{}{You have [C] chips. Keep playing?}
{334}{}{На сегодняшний день хватит.}
{335}{}{На сегодняшнюю ночь хватит.}
{340}{}{Вы победили! Прекрасно, сэр!}
{341}{}{Winner! Well done, ma'am!}
{342}{}{Winner!}
{343}{}{You have [C] chips. Keep playing?}
{344}{}{На сегодняшний день хватит.}
{345}{}{На сегодняшнюю ночь хватит.}
{350}{}{Вы победили! Вы удвоили ваши деньги! Прекрасно, сэр!}
{351}{}{Вы победили! Вы удвоили ваши деньги! Прекрасно, мэм!}
{352}{}{Вы победили! Вы удвоили ваши деньги!}
{353}{}{You have [C] chips. Keep playing?}
{354}{}{На сегодняшний день хватит.}
{355}{}{На сегодняшнюю ночь хватит.}
{360}{}{Вы победили! Вы утроили ваши деньги! Удача сегодня с нами! Прекрасно, сэр!}
{361}{}{Вы победили! Вы утроили ваши деньги! Удача сегодня с нами! Прекрасно, мэм!}
{362}{}{Вы победили! Вы утроили ваши деньги!}
{363}{}{You have [C] chips. Keep playing?}
{364}{}{На сегодняшний день хватит.}
{365}{}{На сегодняшнюю ночь хватит.}
{370}{}{Чего теперь надо? Будем тратить мое время или сделаем ставку?}
{371}{}{I'm whoever you WANT me to be, sweetheart. Now, you gonna place a bet?}
{372}{}{I'm whoever you WANT me to be, girlfriend. Now, you gonna place a bet?}
{373}{}{Place a bet.}
{374}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{375}{}{Yeah, I'm betting you and Pretty Boy Lloyd were both stealing money from Mr. Salvatore. Hard to believe you
 didn't notice him cheating all those times.}
{376}{}{Ты знаешь человека по имени Красавчик Ллойд?}
{377}{}{We'll talk later, Nikki.}
{380}{}{Да, я слышала, что он МЕРТВ. Ты это имеешь в виду, убийца?! А?! Ты наконец сделаешь ставку или будешь мне и дальше мозги трахать?}
{381}{}{Nope. You gonna place a bet?}
{382}{}{Place a bet.}
{383}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{384}{}{Yeah, I'm betting you and Pretty Boy Lloyd were both stealing money from Mr. Salvatore. Hard to believe you didn't notice
 Lloyd cheating all those times.}
{385}{}{We'll talk later, Nikki.}
{390}{}{Так твоя ставка ПРОИГРАЕТ, зайчик, хотя, если ты настолько же тупой, насколько и страшный, ты все равно поставишь. Я этого поганца не видела с тех пор, как он кинул мистера Сальваторе.}
{391}{}{Then that's a bet you'd lose, sweetheart. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{392}{}{Then that's a bet you'd lose, girlfriend. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{393}{}{Maybe you didn't hear me the first time, so for the benefit of the hearing impaired: Where is Lloyd?}
{394}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{395}{}{Fine. We'll talk later, Nikki.}
{400}{}{Зайчик, я СКАЗАЛА тебе, я не знаю, где он. Так вот, знаешь, я НА РАБОТЕ, так что занялся бы ты своими делами --}
{401}{}{Girlfriend, I TOLD you that I don't know where he is. Now, look, I'm WORKING here, so go back to whatever rock you --}
{402}{}{Nikki, Nikki... I'm losing PATIENCE here. If you don't tell me where Lloyd is, I'm going to lose my temper, too.}
{403}{}{Nikki, I don't know what happened between you and Lloyd. But guess what? I don't NEED to know. I'll just tell
 Mr. Salvatore what I suspect.}
{404}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{405}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{406}{}{We'll talk later then, Nikki.}
{410}{}{Только тронь меня, и мистер Сальваторе тебя живьем обдерет.}
{411}{}{Salvatore won't protect you; dealers like you are a chip a dozen. Cut the shit and tell me where Lloyd is or ELSE.}
{412}{}{Salvatore won't protect you; he's dead. Cut the shit and tell me where Lloyd is or ELSE.}
{413}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{414}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{415}{}{We'll talk later then, Nikki.}
{420}{}{О чем это вы?}
{421}{}{Nikki, if you don't tell me everything right now, I'll tell Mr. Salvatore you were in on it, whether you were or not.
 He'll have Mason cut you up seven ways to Sunday, and have your job filled in an hour.}
{422}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{423}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{424}{}{We'll talk later then, Nikki.}
{430}{}{Послушай, КАК Я УЖЕ ГОВОРИЛА, я не знаю, где он. Но я, *кажется*, слышала, что у него была комната в "Десперадо". Может, ты там что-нибудь и найдешь. Теперь, если не возражаешь, мне нужно вернуться к работе.}
{431}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{432}{}{Pretty suspicious that you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{433}{}{We'll talk later then, Nikki.}
{440}{}{Слушай, я только НАЧАЛА здесь работать, и я не могу уследить за каждой фишкой и всем мелким жульем, которое тут шляется. Хотя таких вот говнюков, как ты, уже хорошо изучила.}
{441}{}{Oh, so that's how you and Lloyd hooked up then?}
{442}{}{So you just started work, huh? Pretty convenient. Well, that's all I need to know. Tell Lloyd he's a dead man.}
{443}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{444}{}{We'll talk later then, Nikki.}
{450}{}{Ну-ну, а ты понюхай еще винта, тебе вообще все покажется подозрительным, так ведь?}
{451}{}{It IS suspicious. You should have had Lloyd pegged for what he was as soon as he walked in this casino.}
{452}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{453}{}{We'll talk later then, Nikki.}
{460}{}{А ну вали отсюда немедленно. Я тебе больше ничего не скажу.}
{461}{}{I got nothing to say to you. Get out of here.}
{462}{}{Not now, maybe. We'll talk later though, Nikki. Count on it.}
{470}{}{Мягко стелешь... как бы жестко спать не пришлось. ВОЗМОЖНО, я знаю, где Ллойд, ВОЗМОЖНО, нет. У тебя есть 500 монет?}
{471}{}{Maybe. Depends on what you got for me.}
{480}{}{ВОЗМОЖНО, что Ллойд до сих пор не отдал мне мою долю, и я не уверена, что он вообще собирается. Так что ВОЗМОЖНО - за 500 монет - я МОГЛА БЫ сказать тебе, где болтается его лживая задница.}
{481}{}{Done. Here's the 500 chips. Tell me where he is.}
{482}{}{That's a pretty steep price for a whole bunch of "maybes" and "coulds." I'll find him on my own.}
{483}{}{I don't have enough chips, but I'll be back. You better still be here when I return.}
{490}{}{(Убирает деньги в карман.) Зайди в бойлерную в подвале "Десперадо". Туда этот сукин сын собирался сбежать, когда его припечет.}
{491}{}{All right then. Later, Nikki.}
{500}{}{Ты когда-нибудь уберешься отсюда?! Люди увидят, как мы разговариваем, и САМИ начнут разговаривать. Понимаешь?}
{501}{}{All right then. Later, Nikki.}
{510}{}{Тогда иди к черту! Я больше ничего тебе не скажу, НИКОГДА.}
{511}{}{Breaks my heart. Later, Nikki.}
{600}{}{You bribe Nikki in telling you where Lloyd might be hiding.}
{1210}{}{. Can I help you with... anything?}
{1214}{}{.}
{1235}{}{. Хочешь спустить пару монет?}
{1239}{}{, выигрывай деньги.}
{1241}{}{.}
{1242}{}{. Дай мне знать, если я смогу чем-нибудь помочь.}
{1243}{}{?}
{1244}{}{.}
{1251}{}{...(winks)...you looking to gamble?}
{1252}{}{...(smiles)...wanna take a chance?}
{1253}{}{, you came to the right place.}
{1266}{}{, выигрывай деньги.}
{1268}{}{.}
{1314}{}{ could always use new inventory item}
{2699}{}{Ты сегодня танцуешь?}
