{100}{}{Вы видите старика, его лицо покрыто глубокими морщинами. Если он и замечает, что вы на него смотрите, то виду не подает.}
{101}{}{Перед вами Кэссиди.}
{102}{}{Вы видите старика, его лицо покрыто глубокими морщинами. Он вам кивает.}
{103}{Cas0103}{Well, now. I ain't seen you around before, stranger. Name's Cassidy. I run this place. What can I do for you?}
{104}{Cas0104}{Well now, if it ain't the mysterious stranger. What can I do for you today?}
{105}{}{Ыг ног?}
{106}{}{Хиляй отсюда}
{107}{}{Я ищу Убежище.}
{108}{}{А вы не хотите уехать отсюда?}
{109}{}{Что у вас есть выпить?}
{110}{}{Что тут у вас интересненького происходит?}
{111}{}{Сегодня ничем, спасибо.}
{112}{Cas0112}{Hit on the head a little too often, eh? Sorry, I don't speak imbecile.}
{113}{}{Крит-тин-оми?}
{114}{Cas0114}{Vault? Only Vault I know of is the one inside the city. Big friggin' hole... you can't miss it, trust me.}
{115}{}{Что у вас тут есть выпить?}
{116}{}{Что тут у вас интересненького происходит?}
{117}{}{Спасибо за указания. До встречи.}
{118}{Cas0118}{Beer for $20, shot of whiskey for $30. Nothing special. Why, you want something?}
{119}{}{Я ищу Убежище.}
{120}{}{Я выпью пива.}
{121}{}{Я выпью рюмочку.}
{122}{}{Что тут у вас интересненького происходит?}
{123}{}{Вообще, ничего, но все равно спасибо.}
{124}{Cas0124}{"Interesting?" Heh. Friend, Vault City ain't an "interesting" place... unless the guards get bored, then you
 better take cover. Why you asking? You looking for something in this sinkhole?}
{125}{}{Что у вас тут есть выпить?}
{126}{}{Собственно говоря, я ищу Убежище.}
{127}{}{Не может быть, чтобы тут все было так плохо.}
{128}{}{Вообще, ничего, но все равно спасибо.}
{129}{Cas0129}{Here you go. Drink up. It might help you forget where you are.}
{130}{}{Не может быть, чтобы тут все было так плохо.}
{131}{}{Спасибо за выпивку. Мне пора идти.}
{132}{Cas0132}{Oh, really? Well, hell then, I must be mistaken, considering YOU'RE the authority and all. Guess you must have been napping during the raid last week?}
{133}{}{Рэйд?}
{134}{Cas0134}{Aw, yeah, a beautiful sight it was. A guard patrol broke in here looking for "illegal substances." They busted down the door, busted up my stock, then busted up a few of my customers, too.}
{135}{}{И что потом?}
{136}{}{Ужасно слышать. Но об этом позже.}
{137}{Cas0137}{After they hauled away this one guy, Joshua, for resisting arrest, they fined my ass for finding - get this - REAL whiskey on the premises. Nevermind that I got a permit from Stark three months before. Bastards.}
{138}{}{Да ладно. Серьезно?}
{139}{}{Ужасно слышать. Но об этом позже.}
{140}{Cas0140}{It gets better. Now I'm in debt to the guards for the fine, an' I had to buy a new case of alcohol from a merchant at triple my standard rate. I'm expecting the guards to come knocking again soon, just to bust my chops. }
{141}{}{А в основном тут как?}
{142}{}{Надеюсь, в будущем удача тебе улыбнется. Еще увидимся.}
{143}{Cas0143}{Even the good days ain't worth a damn. The Citizens don't drink much, so I'm stuck here pouring drinks for merchants. The next cheap sonuvabitch who haggles for a drink is going to be wearing his ass as a hat.}
{144}{}{А зачем ты здесь торчишь, если так ненавидишь это место?}
{145}{}{Ужасно слышать. Я ищу Убежище. Ты можешь мне помочь?}
{146}{}{Ужасно слышать. Надеюсь, все еще наладится.}
{147}{Cas0147}{I have a bad heart. Need cardio booster shots to keep it beating. This city's the only place to get real medical care, so I thought I'd settle here, try and make a living.}
{148}{}{Похоже, вы этим местом сыты по горло.}
{149}{}{Понятно. Послушай, я ищу Убежище. Ты не мог бы мне помочь?}
{150}{}{Надеюсь, у тебя все еще наладится. Увидимся.}
{151}{Cas0151}{Makes me want to close up shop and let this City rot. Screw 'em all.}
{152}{}{Почему вы не уезжаете?}
{153}{}{Ужасно слышать. Надеюсь, все еще утрясется.}
{154}{Cas0154}{Go into the wastes by myself? Ha! I'm sick of this place, but I ain't stupid.}
{155}{}{Я как раз туда направляюсь. Может быть, пойдем вместе?}
{156}{}{Что ж, тогда удачи.}
{157}{Cas0157}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{158}{Cas0158}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{159}{Cas0159}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{160}{Cas0160}{Naw... you look like you got enough of a crowd already.}
{161}{}{Хорошо. Ну что ж, удачи вам.}
{162}{}{Тогда забудь об этом разговоре, брамозад сморщенный. Ну и торчи в этом обветшалом сарае, вдыхая дерьмо этого Города.}
{163}{}{Ну и ладно. Тебе же хуже.}
{164}{Cas0164}{Heh. You serious?}
{165}{}{Конечно. Почему бы и нет? По виду, ты за себя постоять можешь.}
{166}{}{Хотя если подумать, в пустошах чертовски опасно, особенно для человека, у которого проблемы с сердцем. Лучше тебе остаться здесь.}
{167}{Cas0167}{All right, count me in.}
{168}{}{Ну что, пошли.}
{169}{}{}
{170}{}{}
{171}{Cas0171}{What's up? You got that "I need to tell you something you might not like" look again.}
{172}{Cas0172}{Yeah?}
{173}{Cas0173}{What's up? You got that "I'm pulling rank" look again.}
{174}{}{Я хочу задать тебе несколько вопросов...}
{175}{}{Похоже, тебе сильно досталось. Возьми стимуляторы и приведи себя в порядок.}
{176}{}{Кэссиди, подожди здесь, пока я не вернусь.}
{177}{}{Убери оружие.}
{178}{}{Будь ближе ко мне.}
{179}{}{Не отходи слишком далеко.}
{180}{}{Нам надо чуть увеличить дистанцию.}
{181}{}{Пошли, Кэссиди. Нам пора.}
{182}{}{Ничего, спасибо.}
{261}{Cas0261}{You want me to put a bullet in Myron's head, is that it? It'd be no trouble. Just give the word.}
{262}{Cas0262}{What's on your mind?}
{263}{}{Чем тебе помешал Майрон?}
{264}{}{С каким оружием ты умеешь обращаться?}
{265}{}{Вообще-то, у меня была другая просьба...}
{266}{}{Вообще-то, у меня была к тебе просьба...}
{267}{}{Неважно. Проехали.}
{268}{}{Нет, не надо трогать Майрона. По крайней мере, не сегодня. Если что, я тебе скажу.}
{269}{Cas0269}{Well, shotguns and rifles, mostly... just personal preference. I ain't a bad shot with pistols, neither.}
{270}{}{Еще что-нибудь?}
{271}{}{Ладно. У меня есть еще вопросы...}
{272}{}{Хорошо. Просто проверка.}
{273}{Cas0273}{If you ever need to learn somebody some manners up close and personal, slip me some brass knuckles, and I can tapdance on their face with my fists.}
{274}{}{Отлично. Что еще?}
{275}{}{Ладно. У меня есть еще вопросы...}
{276}{}{Хорошо. Просто проверка.}
{277}{Cas0277}{Uh, well... just between you and me, I can also use a spear pretty good. Me and my buddies used to hunt radscorpions with spears way back when... fact I'm alive and they ain't might tell you something.}
{278}{}{А что такого зазорного в том, чтобы владеть копьем?}
{279}{}{Ладно. У меня есть еще вопросы...}
{280}{}{Хорошо. Просто проверка.}
{281}{Cas0281}{Says you. Just don't be calling me no tribal, and we'll get along just fine.}
{282}{Cas0282}{Don't want people mistaking me for ol' Bone-nose over there. Heh-heh. I ain't never seen no tribal do something as dumb as jam a bone in his nose.}
{283}{Cas0283}{Of course there isn't. Spear's a fine weapon. Lots of tribal friends of mine use 'em.}
{284}{}{А ты знаешь, что я тоже "дикарь"?}
{285}{}{Хммм. Слушай, у меня есть еще вопросы...}
{286}{}{Ну, хорошо. Спасибо за подробный отчет.}
{287}{Cas0287}{Aw, don't be playing with ol' Cassidy now. You ain't no tribal.}
{288}{}{Да, я Избранный.}
{289}{}{Ну, неважно. Слушай, у меня есть другие вопросы...}
{290}{}{Забудь. Не хочу сейчас разговаривать на эту тему.}
{291}{Cas0291}{Uh, well... damn it all, you can have my apology right here and now. I didn't mean any offense.}
{292}{}{Все нормально. Слушай, у меня есть и еще вопросы...}
{293}{}{Забудь об этом. Проехали.}
{294}{Cas0294}{Well, now, before you go, I got a question for you. What are we doing out here? We seem to be running all over the place looking for something. Have we got some sort of plan?}
{295}{}{Мы ищем ГЭКК - Генератор Эдемских Кущ Компактный. Он необходим для выживания моей деревни.}
{296}{}{Мы идем в Убежище, затем вернемся с ГЭКК в мою деревню.}
{297}{}{Моих соплеменников похитили. Я пытаюсь выяснить, что с ними случилось.}
{298}{Cas0298}{Them things come in kits now, huh? Man, the good book don't mention that, does it? Well, all right then. Let's get hunting.}
{299}{Cas0299}{Huh. All right then, just checking.}
{300}{Cas0300}{I wouldn't mind plugging a few holes in some kidnappers. A little frontier justice never hurt anyone... well, at least not me.}
{301}{}{Ладно, пойдем.}
{302}{Cas0302}{The things that little cuss says ain't fit for decent ears.}
{303}{Cas0303}{Especially a woman's.}
{304}{}{Ну, Кэсс, мне и в голову не приходило, что тебя это волнует. Мое сердце так и трепещет.}
{305}{}{Да? Что ты говоришь?}
{306}{}{Знаешь, ты тоже не образец культурной речи, Кэссиди.}
{307}{}{Кто бы говорил. Ладно, пошли.}
{308}{Cas0308}{Yeah, but when I do it, it's got style. He's just a little trash mouth.}
{309}{Cas0309}{And I don't like the way he looks at you, neither.}
{310}{}{Ну, Кэсс, мне и в голову не приходило, что тебя это волнует. Мое сердце так и трепещет.}
{311}{}{Да? Что ты говоришь?}
{312}{}{Кто бы говорил. Ладно, пошли.}
{313}{Cas0313}{Now hold on, I didn't mean it like that.}
{314}{Cas0314}{All I'm saying is that bona fide little asshole's gonna get his number clocked one day when it's just me and him and a hole in the desert.}
{315}{}{Что ж, жизнь научит. А у меня есть к тебе другие вопросы...}
{316}{}{Ну, он получит то, что ему причитается. Так что, я бы не беспокоился.}
{317}{}{Успокойся, Кэссиди. Оставь Майрона в покое.}
{318}{}{Ненавижу это место.}
{319}{}{А я то надеялся, что ноги моей тут больше не будет.}
{320}{}{Город жопошников...}
{321}{}{Это место даже хуже, чем Город Убежища.}
{322}{}{Хорошо, что я проверил оружие до того, как мы сюда притащились.}
{323}{}{Если я отброшу коньки, здесь меня не хорони.}
{324}{}{Тут надо быть поосторожнее. Местные не очень-то дружелюбны.}
{325}{}{Да уж. Никогда не думал, что увижу Сан-Франциско.}
{326}{}{Никогда не думал, что заставишь старика вроде меня торчать тут столько времени. Давай закончим это дело и пойдем домой.}
{327}{}{Реддинг - шахтерский город. Добывают по большей части золото. В Город Убежища приходило много караванов отсюда.}
{328}{}{Брокен Хиллс - шахтерский город... в основном добывают уран. Тут надо быть поосторожнее, местечко то еще.}
{329}{}{Меня, похоже, отравили. У тебя есть противоядие?}
{330}{}{Я свечусь, как неоновая вывеска. Есть какие-нить таблетки от радиации?}
{331}{}{Ох, как меня потрепали. Есть стимуляторы?}
{332}{}{Веди себя как следует, Майрон. Я слежу за тобой.}
{333}{}{Вот только дай мне повод, Майрон...и я пощекочу твои кишки.}
{334}{}{Черт побери, Ленни, тебе нужна ванна. Или дезинфекция.}
{335}{}{Слушай, гуль, лучше держись на расстоянии, черт тебя дери. Фу-у, ну ты и воняешь.}
{336}{}{Мерзее этой псины я в жизни не видел.}
{337}{}{Остынь. Кэссиди твой друг, лады?}
{338}{}{Интересно, чем питается этот киберпес. Наверно, людьми.}
{339}{}{Если этот киберпес начнет трахать мою ногу, я его прикончу.}
{340}{}{Аххх. Черт, хорошо, что они наделали миллионы этих штук до того, как упали бомбы.}
{341}{}{Спасибо, друг.}
{342}{}{Надеюсь, эти стимуляторы не повредят моему сердцу...}
{343}{}{Что з--?! Ой, нет, сердце! Я...*хррррр*}
{344}{}{Извини, я просто любуюсь видом.}
{345}{}{Черт, тогда я просто постою вон там.}
{346}{}{Извини, дружище. Не хотел преграждать тебе дорогу.}
{347}{}{Ааххх. Вот это в самую точку. Спасибо большое.}
{348}{}{*Ик* Хе-хе. Ничего нет лучше старой доброй огненной воды, чтобы разогнать кровь.}
{349}{}{Спасибо. Черт, тебе вроде бы тоже глоточек не помешает.}
{350}{}{Так это Убежище. Огромная штуковина, верно?}
{351}{}{Хочешь опять взять меня с собой?}
{352}{}{Отлично, приятель. Снова в путь.}
{353}{}{Уверен, что моя помощь не нужна?}
{354}{}{Все прям чешется, так и хочется убраться отсюда.}
{355}{}{Покурить бы.}
{356}{}{Папаша назвал меня в честь какого-то парня из довоенных комиксов. Говорил, что тот тоже был мерзкий сукин сын.}
{357}{}{...как же все таки приятно путешествовать. От житья в Городе Убежища у меня язва.}
{358}{}{Надеюсь, сердце не начнет барахлить, пока мы в дороге...}
{359}{}{Ох, выпить бы.}
{360}{}{Ох, проверю-ка я свою снарягу еще раз.}
{361}{}{Чертов артрит...}
{362}{}{Если бы я был на двадцать лет моложе, я бы пошел на восток и исследовал Средний Запад. А сейчас, боюсь, слишком поздно.}
{363}{}{Говорят, у них там на Среднем Западе бывают смерчи в милю шириной. Сейчас там здоровенный радиоактивный пыльный котел.}
{364}{}{Интересно, что стало с Техасом...}
{365}{}{Спасибо. Я... ух ты. Что-то перед глазами все плывет.}
{366}{}{Говорят, от этой фигни бывают глю... ух ты! Откуда это сюда понабилось столько змеюк?!}
{367}{}{Каждый раз, как этим пользуюсь, вспоминаю прошлое.}
{368}{}{Ничего нет лучше примитивного лечения дикарей...}
{369}{}{Похоже, скоро мне понадобятся костыли и кресло на колесах.}
{370}{}{Кэссиди умирает от сердечного приступа.}
{371}{}{Вы убедили Кэссиди присоединиться к вашей команде.}
{372}{}{Дай мне сначала принять таблетки от сердца...}
{1000}{Cas1000}{Well... all right, then. I'll wait here 'til you get back. }
{1100}{Cas1100}{Sure. Can't promise I won't pull it out again if there's trouble, though.}
{1200}{Cas1200}{All right, I'll stick close to you then. You must be expecting trouble.}
{1300}{Cas1300}{All right, I'll keep some distance. Get a better vantage point that way.}
{1400}{Cas1400}{All right, I'll be watching your back. You need me, holler, and I'll come running.}
{2000}{Cas2000}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{2100}{Cas2100}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{2200}{Cas2200}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{2300}{Cas2300}{Naw... you look like you got enough of a crowd already.}
{2400}{Cas2400}{All right, then.}
{2999}{}{Ну ладно. Тогда будь осторожен.}
{3000}{}{Пошли.}
{3100}{}{Забудь, что я спрашивал, мудила.}
{3200}{}{Ну и ладно. Тебе же хуже.}
{4100}{Cas4100}{Okay, everything's stitched up. I'm good to go.}
{4200}{Cas4200}{Okay, pretty much everything is patched up.}
{4300}{Cas4300}{That pretty much did it, but I could use a couple more stims.}
{4400}{Cas4400}{I used what I could, but I'm still pretty messed up. If you got any more stims to spare, I could sure use 'em. I can still walk, though.}
{9999}{}{Я хочу задать тебе несколько вопросов...}
{10001}{}{Возьми немного стимуляторов и подлечись.}
{10002}{}{Кэссиди, подожди здесь, пока я не вернусь.}
{10003}{}{Убери оружие.}
{10004}{}{Будь ближе ко мне.}
{10005}{}{Не отходи слишком далеко.}
{10006}{}{Нам надо чуть увеличить дистанцию.}
{10007}{}{Тогда пошли.}
{10100}{}{Пошли, Кэссиди. Нам пора.}
{20000}{Cas20000}{All right, I'm listening.}
{20001}{Cas20001}{My gear? What about it?}
{20002}{Cas20002}{No problem. Too hot for that kinda gear, anyway. Makes me sweat like a New Reno whore.}
{20003}{}{Попробуем другое построение.}
{20004}{}{Нам надо поговорить об оружии и снаряжении.}
{20005}{}{Забудь. Давай ничего не будем менять.}
{20006}{}{Неважно. Пока, вопрос твоего снаряжения подождет.}
{20007}{}{Сними броню.}
