{100}{}{You see a villager.}
{101}{}{You see a villager.}
{102}{}{Привет.}
{103}{}{Доброго вам дня.}
{104}{}{Welcome to our Village.}
{105}{}{Монстры защищают нас.}
{106}{}{Hurry back.}
{107}{}{We'll need those guns soon.}
{108}{}{Привет.}
{109}{}{Leave now!}
{110}{}{Go back to where you came from!}
{111}{}{Вон отсюда к чертовой матери!}
{112}{}{We're safe now.}
{113}{}{Спасибо.}
{114}{}{Bless you, wanderer.}
