{100}{}{Armes légères}
{101}{}{Armes lourdes}
{102}{}{Armes à énergie}
{103}{}{Corps à corps.}
{104}{}{Armes de Mêlée}
{105}{}{Projectiles}
{106}{}{First Aid}
{107}{}{Médecine}
{108}{}{Esquive}
{109}{}{Crochetage}
{110}{}{Voleur}
{111}{}{Pièges}
{112}{}{Science}
{113}{}{Réparation}
{114}{}{Discours}
{115}{}{Troc}
{116}{}{Jeu}
{117}{}{Vie en plein air}
{200}{}{Maniement, entretien et connaissance générale des petites armes à feu. - Pistolets, mitraillettes et carabines.}
{201}{}{Fonctionnement et entretien de l'armement lourd. - Mini-canons, lance-roquettes, lance-flammes et autres.}
{202}{}{Entretien et chargement des armes à énergie. Comment armer et manier des armes utilisant des techniques au laser ou au plasma.}
{203}{}{Divers arts martiaux, combats de boxe et Corps à Corps. Coups de pieds et coups de poings. Cela inclut les poings américains et les gants.}
{204}{}{Capacité à combattre avec des armes blanches. Couteaux, massues, lances, matraques, etc.}
{205}{}{Capacité à lancer des armes à la main, telles que des couteaux, des lances et des grenades.}
{206}{}{Capacité à pratiquer les premiers soins. Traitement des coupures légères, écorchures et autres maux bénins. La compétence Secourisme permet de guérir des points d'impact plus facilement que par un simple repos.}
{207}{}{Capacité à traiter les lésions importantes et à soigner les membres estropiés.  Sans cette compétence, la durée d'attente avant de pouvoir retrouver l'usage des membres estropiés est beaucoup plus importante.}
{208}{}{Quiet movement, and the ability to remain unnoticed.  If successful, you will be much harder to locate.  You cannot run and sneak at the same time.}
{209}{}{The skill of opening locks without the proper key.  The use of lockpicks or electronic lockpicks will greatly enhance this skill.}
{210}{}{Faculté de s'approprier ce qui appartient à autrui. S'applique aux personnes et aux lieux.}
{211}{}{Capacité à repérer et retirer les pièges posés. Permet également de poser des explosifs.}
{212}{}{Recouvre diverses compétences scientifiques, notamment en informatique, biologie, physique et géologie.}
{213}{}{Mise en application de la compétence Science. Réparation des équipements, mécanismes et appareils électroniques endommagés.}
{214}{}{The ability to communicate in a practical and efficient manner.  The skill of convincing others that your position is correct.  The ability to lie and not get caught.}
{215}{}{Trading and trade-related tasks.  The ability to get better prices for items you sell, and lower prices for items you buy.}
{216}{}{The knowledge and practical skills related to wagering.  The skill at cards, dice and other games.}
{217}{}{Practical knowledge of the outdoors, and the ability to live off the land.  The knowledge of plants and animals.}
{300}{}{+ (4 x AG)}
{301}{}{+ (2 x AG)}
{302}{}{+ (2 x AG)}
{303}{}{+ (2 x (AG+FO))}
{304}{}{+ (2 x (AG+FO))}
{305}{}{+ (4 x AG)}
{306}{}{+ (2 x (PE+IN))}
{307}{}{+ (PE + IN)}
{308}{}{+ (3 x AG)}
{309}{}{+ (PE + AG)}
{310}{}{+ (3 x AG)}
{311}{}{+ (PE + AG)}
{312}{}{+ (4 x IN)}
{313}{}{+ (3 x IN)}
{314}{}{+ (5 x CR)}
{315}{}{+ (4 x CR)}
{316}{}{+ (5 x CH)}
{317}{}{+ (2 x (EN+IN))}
{500}{}{Tu guéris %d points d'impact.}
{501}{}{Tu n'as pas besoin de soins.}
{502}{}{%s n'a pas besoin de soins.}
{503}{}{Tu ne parviens pas à guérir.}
{505}{}{Tu mérites %d PE pour avoir su affiner tes compétences.}
{510}{}{\nskill_use: compétence utilisée incorrecte.}
{512}{}{On ne peut plus rien pour les morts.}
{513}{}{Les morts ont droit au repos éternel.}
{514}{}{Dieu ait son âme ! Il faut se faire une raison.}
{520}{}{Tu soignes : %s.}
{521}{}{Tu soignes : %s.}
{525}{}{Tu n'as pas réussi à soigner : %s.}
{526}{}{Tu n'as pas réussi à soigner : %s.}
{530}{}{Oeil crevé}
{531}{}{bras gauche estropié}
{532}{}{bras droit estropié}
{533}{}{jambe droite estropiée}
{534}{}{jambe gauche estropiée}
{550}{}{Tu n'as pas réussi à forcer la serrure.}
{551}{}{Tu n'as réussi à repérer aucun piège.}
{552}{}{Tu n'as rien appris.}
{553}{}{Réparation impossible.}
{570}{}{Tu t'es fait surprendre en train de voler : %s.}
{571}{}{Tu as volé : %s.}
{572}{}{Tu t'es fait surprendre en train de déposer : %s.}
{573}{}{Tu as déposé : %s.}
{590}{}{You've taxed your ability with that skill. Wait a while.}
{591}{}{Tu es à bout de forces.}
{592}{}{Le surmenage, c'est mauvais pour le coeur.}
{600}{}{Tu ne disposes pas du niveau de compétence permettant de guérir les membres estropiés.}
{601}{}{L'unité robotique n'est pas réparable.}
{1000}{}{Laisse-moi t'aider.}
{1001}{}{Pas de problèmes.}
{1002}{}{Je m'en occupe.}
{1003}{}{Ca m'a fait plaisir d'être utile.}
{1004}{}{Ok.}
{1005}{}{Je vais essayer.}
{1100}{}{En cas de problème, appelle-moi.}
{1101}{}{Tu t'en charges ?}
{1102}{}{Bon, si tu veux.}
{1103}{}{Vas-y, essaie.}
{1104}{}{Non, toi, vas-y.}
