call ..\p GCBRAIN
call ..\p GCFESTUS
call ..\p GCFOLK
call ..\p GCGORDON
call ..\p GCGUARD
call ..\p GCHANK
call ..\p GCHAROLD
call ..\p GCJEREM
call ..\p GCLENNY
call ..\p GCLUMPY
call ..\p GCPACOFF
call ..\p GCPERCY
call ..\p GCRDESK
call ..\p GCRGHOUL
call ..\p GCRGHUL
call ..\p GCRGLOW
call ..\p GCRGUARD
call ..\p GCROBOT
call ..\p GCSKEETR
call ..\p GCWANDER
call ..\p GCWOOZ
call ..\p GCWORSHP
call ..\p GCYGUARD
call ..\p GCZOMAK
call ..\p GIJNKBOX
call ..\p GIPERBOX
call ..\p GSALARM
call ..\p GSRDOOR
call ..\p GSREACTR
call ..\p GSTERM
call ..\p GSVALVE
call ..\p GSYDOOR
