{0}{}{Opravdu chceš hru ukonèit?}
{1}{}{Demo verze}
{2}{}{Bude použit pøednastavený charakter.}
{3}{}{Screenshot byl uložen.}
{4}{}{Hra byla úspìšnì naètena.}
{5}{}{Hra byla úspìšnì uložena.}
{6}{}{Èasový limit demoverze vypršel.}
{7}{}{Pip-Boy not available in combat!}
{8}{}{Chyba pøi ukládání screenshotu.}
{9}{}{ÚVOD}
{10}{}{NOVÁ HRA}
{11}{}{NAÈÍST HRU}
{12}{}{VOLBY}
{13}{}{AUTOØI}
{14}{}{KONEC}
{15}{}{Akèní body}
{16}{}{Hit body}
{17}{}{Detektor pohybu není nainstalován.}
{18}{}{Detektor pohybu je vybitý.}
{20}{}{Copyright(c) 1998 Interplay Productions.  All rights reserved.}
{30}{}{Chceš hrát dál?}
{50}{}{Ke spuštìní Falloutu potøebuješ CD!}
{100}{}{Chyba pøi ukládání nastavení!}
{101}{}{Nastavení hry nebylo uloženo.}
{1000}{}{Zvedá se ti žaludek.}
{1001}{}{Zvedá se ti žaludek a zaèínáš zvracet. Cítíš únavu.}
{1002}{}{Cítíš velkou únavu, nepøestáváš zvracet a stále èastìji si potøebuješ odpoèinout.}
{1003}{}{Silnì krvácíš. Je ti velmi špatnì a zaèaly ti vypadávat vlasy.}
{1004}{}{Nepøetržitì silnì krvácíš. Ve tvých zvratcích se objevuje krev. Kùže se ti loupe po celém tìle.}
{1005}{}{Trpíš vnitøním krvácením a silným prùjmem. Oteklo ti celé tìlo a zmítáš se v tìžké agónii.}
{1006}{}{Umíráš v agónii na nemoc z ozáøení.}
{1007}{}{Zasáhla tì silná dávka radiace.}
{1008}{}{Geigerùv pøístroj pípá.}
{1009}{}{Geigerùv pøístroj divoce pípá.}
{2000}{}{Sem se nemùžeš dostat.}
{2001}{}{Zámek je zaseknutý.}
{3000}{}{Dostáváš otravu!}
{3001}{}{Jed ti zpùsobil zranìní.}
{3002}{}{Cítíš se o trochu lépe.}
{3003}{}{Cítíš se lépe.}
{4000}{}{Kvùli tvému neodbornému zacházení výbušnina pøedèasnì explodovala.}
{5000}{}{používá:}
{5001}{}{nemá náboje pro zbraò:}
{5002}{}{nabíjí zbraò:}
{6000}{}{Zeptat se na co?}
{7000}{}{You aren't wearing the Pip-Boy!}
{8000}{}{Neseš toho pøíliš mnoho.}
{8001}{}{%s nese pøíliš mnoho.}
{8500}{}{Získáváš %d zkušenostních bodù za úspìšné použití schopnosti "Pøežití v pustinì".}
{9000}{}{%s postupuje na vyšší úroveò.}
{9010}{}{Páni. Z nièeho nic jsem ucítil veliký nával zkušeností.}
{9011}{}{Další level, kotì! Další level!}
{9012}{}{Cítím veliké narušení síly, jako by všechny mé dovednosti získaly procenta navíc.}
{9013}{}{Cítím se odolnìjší. Silnìjší. Chytøejší.}
{9020}{}{Páni! Cítím, že díky všem tìm novým zkušenostem vzrostla i moje síla!}
{9021}{}{Aaach! Moje svaly... jsou najednou silnìjší... dovednosti... vzrostly... postoupil jsem na další úroveò...}
{9022}{}{Chci diplom a tu legraèní ètverhrannou èepièku se støapcem, protože jsem právì odpromoval!}
{9023}{}{Hej, cítím se najednou nìjak silnìjší! Znamená to, že dostanu pøidáno?}
{9030}{}{Všechno se mi to najednou znova vybavuje...}
{9031}{}{Hehe. Vypadá to, že i takovej starej pes jako já se mùže nauèit pár novejm kouskùm.}
{9032}{}{Zdá se, že se mi všechno to toulání vyplatilo.}
{9033}{}{Nauèil jsem se pár novejch fíglù.}
{9040}{}{Dìd nás uèit. My poslouchat.}
{9041}{}{Duchové nás nauèit mnoho nového, pøítela.}
{9042}{}{My se teï uèiti.}
{9043}{}{Do Sulika teï vstoupit mocná duch.}
{9044}{}{My se teï stát èástí našeho Dìdka Kostìja, pøítela.}
{9045}{}{My teï být jako náš Dìdek Kostìj.}
{9050}{}{Ach, mùj bože...já jsem se opravdu nìco nauèil.}
{9051}{}{Tolik mrtvých...ach, mùj bože, leží na mnì veliká vina.}
{9052}{}{Nemùžu uvìøit, že jsem dokázal pøežít tak dlouho.}
{9060}{}{Haf!}
{9061}{}{Haf!}
{9062}{}{Haf!}
{9063}{}{Haf!}
{9064}{}{HAF! HAF!}
{9070}{}{Umím pár nových vìcí!}
{9071}{}{Umím pár nových vìcí!}
{9080}{}{Myslím, že jsem získal nové znalosti!}
{9081}{}{Vìdomosti jsou dar.}
{9082}{}{Zdá se, že se dobøe vyvíjím.}
{9083}{}{Ve svých znalostech už pøedèím dokonce i Gruthara.}
{9084}{}{Už jsem silnìjší než vìtšina mé smeèky.}
{9085}{}{Teï už jsem ve smeèce nejmocnìjší.}
{9090}{}{Umím pár nových vìcí!}
{9091}{}{Umím pár nových vìcí!}
{9100}{}{Umím pár nových vìcí!}
{9101}{}{Umím pár nových vìcí!}
{9110}{}{Umím pár nových vìcí!}
{9111}{}{Umím pár nových vìcí!}
{9120}{}{ANALÝZA DAT KOMPLETNÍ. PROVÁDÍM UPGRADE VŠECH SYSTÉMÙ.}
{9121}{}{KOMPLETACE NOVÝCH DAT UKONÈENA. VYLEPŠUJI ZAMÌØOVACÍ SYSTÉMY.}
{9122}{}{MODERNIZACE SYSTÉMU DOKONÈENA.}
{9123}{}{PROVÁDÍM PØEKALIBROVÁNÍ ZAMÌØOVACÍHO SYSTÉMU. PØESNOST ZÁSAHU ZVÝŠENA O 20%.}
{9124}{}{DOSAŽEN OPTIMÁLNÍ VÝKON CELÉHO SYSTÉMU.}
{9130}{}{Šéfe! Myslím, že tomu koneènì pøicházím na kloub.}
{9131}{}{Já se opravdu zlepšuju! Øíkal jsem ti, že tì nezklamu, šéfe.}
{9132}{}{Hej... poèkat... už jsem na to pøišel. Myslím, že musím jen líp míøit.}
{9133}{}{Vidíš, šéfe? I starý pes se mùže nauèit novým kouskùm!}
{9134}{}{Víš, co se stalo, šéfe? Myslím, že jsem se doopravdy nauèil nìco nového.}
{9135}{}{Zaèínám v tom být docela dobrý. Já to øíkal, šéfe. Všechno dobré se postupem èasu zlepší.}
{9140}{}{Umím pár nových vìcí!}
{9141}{}{Umím pár nových vìcí!}
{9150}{}{Umím pár nových vìcí!}
{9151}{}{Umím pár nových vìcí!}
{9160}{}{Umím pár nových vìcí!}
{9161}{}{Umím pár nových vìcí!}
{9170}{}{Umím pár nových vìcí!}
{9171}{}{Umím pár nových vìcí!}
{9180}{}{Umím pár nových vìcí!}
{9181}{}{Umím pár nových vìcí!}
{9190}{}{Haf HAF!}
{9191}{}{Òaf HAF VHÚÚÚ!}
{9192}{}{Òaf HAF VHÚÚÚ!}
{9193}{}{Òaf HAF VHÚÚÚ!}
{9194}{}{Òaf HAF VHÚÚÚ!}
{9195}{}{Òaf-Vhúú!}
{9200}{}{}
{9210}{}{}
{9220}{}{}
{9230}{}{}
{9240}{}{Inicializuji aktualizaci programu, pane... upgrade dokonèen.}
{9241}{}{Upgraduji software, pane... verze 2.0 byla nainstalována.}
{9242}{}{Provádím modifikace hardwaru, pane... všechny systémy jsou funkèní.}
{9243}{}{Provádím modifikace hardwaru, pane... všechny systémy bìží v optimálním režimu!}
{9250}{}{}
