{100}{}{Lehké støelné zbranì}
{101}{}{Tìké støelné zbranì}
{102}{}{Energetické zbranì}
{103}{}{Boj beze zbranì}
{104}{}{Chladné zbranì}
{105}{}{Vrhací zbranì}
{106}{}{První pomoc}
{107}{}{Léèení}
{108}{}{Plíení}
{109}{}{Páèení zámkù}
{110}{}{Kradení}
{111}{}{Pasti a vıbušniny}
{112}{}{Vìda}
{113}{}{Opravování}
{114}{}{Øeè}
{115}{}{Obchodování}
{116}{}{Hazardní hry}
{117}{}{Pøeití v pustinì}
{200}{}{Pouívání, údrba a obecné znalosti o lehkıch støelnıch zbraních jako jsou pistole, samopaly a pušky.}
{201}{}{Pouívání, údrba a obecné znalosti o tìkıch støelnıch zbraních jako jsou gatlingy, kulomety, raketomety, plamenomety apod.}
{202}{}{Pouívání, údrba a obecné znalosti o energetickıch zbraních. Technika ovládání zbraní zaloenıch na laserové nebo plazmové technologii.}
{203}{}{Kombinace bojovıch umìní, boxu a dalších technik boje beze zbranì. Boj jen s pomocí rukou a nohou.}
{204}{}{Pouívání chladnıch zbraní na krátkou vzdálenost jako napø. noe, kladiva, kopí, kyje apod.}
{205}{}{Dovednost zacházení s vrhacími zbranìmi jako napø. vrhací noe, oštìpy a granáty.}
{206}{}{Obecné léèitelské znalosti pouívané k vyléèení drobnìjších øeznıch ran, odøenin a všeobecnì lehèích zranìní. Jednoduše øeèeno, pouití první pomoci mùe za kratší èas vyléèit více hit bodù ne spánek.}
{207}{}{Léèení vánıch zranìní a zmrzaèenıch konèetin. Bez pouití této dovednosti bude trvat mnohem déle, ne se zmrzaèené konèetiny vyléèí natolik, aby byly znovu pouitelné.}
{208}{}{Quiet movement, and the ability to remain unnoticed.  If successful, you will be much harder to locate.  You cannot run and sneak at the same time.}
{209}{}{The skill of opening locks without the proper key.  The use of lockpicks or electronic lockpicks will greatly enhance this skill.}
{210}{}{Dovednost pøivlastnit si cizí vìci. Pouívá se pro okrádání lidí nebo vylupování skøíní, stolù apod.}
{211}{}{Dovednost nalézt a odstranit pasti. Zahrnuje rovnì zacházení s vıbušninami urèenıch k demolièním úèelùm.}
{212}{}{Zahrnuje znalosti celé škály vyspìlıch technologií jako napø. poèítaèe, biologie, fyzika a geologie.}
{213}{}{Praktické aplikování technickıch znalostí k opravì znièenıch zaøízení, strojù a elektroniky.}
{214}{}{The ability to communicate in a practical and efficient manner.  The skill of convincing others that your position is correct.  The ability to lie and not get caught.}
{215}{}{Trading and trade-related tasks.  The ability to get better prices for items you sell, and lower prices for items you buy.}
{216}{}{The knowledge and practical skills related to wagering.  The skill at cards, dice and other games.}
{217}{}{Practical knowledge of the outdoors, and the ability to live off the land.  The knowledge of plants and animals.}
{300}{}{+ 4 x HB}
{301}{}{+ 2 x HB}
{302}{}{+ 2 x HB}
{303}{}{+ 2 x (HB + SÍ)}
{304}{}{+ 2 x (HB + SÍ)}
{305}{}{+ 4 x HB}
{306}{}{+ 2 x (VN + IN)}
{307}{}{+ VN + IN}
{308}{}{+ 3 x HB}
{309}{}{+ VN + HB}
{310}{}{+ 3 x HB}
{311}{}{+ VN + HB}
{312}{}{+ 4 x IN}
{313}{}{+ 3 x IN}
{314}{}{+ 5 x CH}
{315}{}{+ 4 x CH}
{316}{}{+ 5 x ŠT}
{317}{}{+ 2 x (OD + IN)}
{500}{}{Vyléèeno %d hit bodù.}
{501}{}{U vypadáš dost zdravì.}
{502}{}{%s vypadá dostateènì zdravì.}
{503}{}{Léèba se nezdaøila.}
{505}{}{Získáváš %d zkušenostních bodù za procvièení dovedností.}
{510}{}{\nskill_use: invalid skill used.}
{512}{}{Nemùeš vyléèit mrtvé.}
{513}{}{Nech mrtvé odpoèívat v pokoji.}
{514}{}{Je po smrti, smiø se s tím.}
{520}{}{Podaøilo se ti vyléèit %s.}
{521}{}{Podaøilo se ti vyléèit %s.}
{525}{}{Nepodaøilo se ti vyléèit %s.}
{526}{}{Nepodaøilo se ti vyléèit %s.}
{530}{}{zranìné oko}
{531}{}{zmrzaèenou levou ruku}
{532}{}{zmrzaèenou pravou ruku}
{533}{}{zmrzaèenou pravou nohu}
{534}{}{zmrzaèenou levou nohu}
{550}{}{Nepodaøilo se ti otevøít zámek.}
{551}{}{Neobjevuješ ádnou past.}
{552}{}{Nic nového ses nenauèil.}
{553}{}{Tohle nemùeš opravit.}
{570}{}{Pøistihli tì pøi krádei objektu: %s.}
{571}{}{Podaøilo se ti ukrást objekt: %s.}
{572}{}{Pøistihli tì pøi umisování objektu: %s.}
{573}{}{Podaøilo se ti umístit objekt: %s.}
{590}{}{You've taxed your ability with that skill. Wait a while.}
{591}{}{Únava ti nedovolí dále pokraèovat v této èinnosti.}
{592}{}{Únava je pøíliš velká. Další vypìtí by tì mohlo zabít.}
{600}{}{Nemáš dost zkušeností pro léèbu zmrzaèení.}
{601}{}{Robot je nenávratnì poškozen.}
{1000}{}{Uka, pomùu ti.}
{1001}{}{Fajn, to zvládnu.}
{1002}{}{Radši mì k tomu pus.}
{1003}{}{Rád pomùu.}
{1004}{}{Dobøe.}
{1005}{}{Zkusím to.}
{1100}{}{Kdy budeš mít nìjaké problémy, dej mi vìdìt.}
{1101}{}{U to máš?}
{1102}{}{Kdy si na to troufáš...}
{1103}{}{Tak do toho.}
{1104}{}{Poslu si.}
