#
# Messages used in gdialog.c for custom NPC combat control.
#
{0}{}{Seria}
{1}{}{Ucieczka}
{2}{}{Wybór broni}
{3}{}{Dystans}
{4}{}{Kogo atakowaæ}
{5}{}{U¿ycie chemikaliów}

{10}{}{Gotowe}
{11}{}{Anuluj}

#
# Burst options.
#
{99}{}{Nie da siê.}
{100}{}{Zawsze!}
{101}{}{Czasami, nie martw siê, ¿e mnie zranisz}
{102}{}{Upewnij siê, ¿e mnie nie zranisz}
{103}{}{Postaraj siê mnie nie zraniæ}
{104}{}{B¹dŸ absolutnie pewny, ¿e mnie nie zranisz}

#
# Run away options.
#
{200}{}{Nêdzny tchórz}
{201}{}{Boli ciê palec}
{202}{}{Lekko krwawisz}
{203}{}{Nie czujesz siê za dobrze}
{204}{}{Potrzebujesz opatrunku}
{205}{}{Nigdy!}

#
# Weapon pref options.
#
{300}{}{Brak}
{301}{}{Bia³a}
{302}{}{Bia³a, potem dystansowa}
{303}{}{Dystansowa, potem bia³a}
{304}{}{Dystansowa}
{305}{}{Bez broni}

#
# Distance options.
#
{400}{}{Zostañ blisko mnie}
{401}{}{Atak!}
{402}{}{Celuj do wroga}
{403}{}{Wybierz samodzielnie}
{404}{}{Zostañ tam, gdzie jesteœ}

#
# Attack who options.
#
{500}{}{Ka¿dego, kto mnie atakuje}
{501}{}{Najsilniejszego}
{502}{}{Najs³abszego}
{503}{}{Kogokolwiek chcesz}
{504}{}{Najbli¿szego}

#
# Chem use options.
#
{600}{}{Jestem czysty}
{601}{}{Stimpaki przy niewielkich obra¿eniach}
{602}{}{Stimpaki przy powa¿nych obra¿eniach}
{603}{}{Dowolna substancja raz na jakiœ czas}
{604}{}{Dowolna substancja w dowolnej chwili}
