{100}{}{Zabij z³oœliwe chwasty, które rozpleni³y siê w ogrodzie Hakuninna.}
{110}{}{Zdob¹dŸ krzemieñ dla Mynoca, ¿eby móg³ naostrzyæ twoj¹ w³óczniê.}
{120}{}{Odszukaj psa Nagora, który zagin¹³ w dziczy.}
{130}{}{Zdob¹dŸ GECK dla Arroyo.}
{140}{}{ZnajdŸ handlarza imieniem Vic.}
{200}{}{Ureguluj nale¿noœci Vica przez przyniesienie radia z jego domu w Klamath i sp³acenie Metzgera.}
{201}{}{Dowiedz siê dlaczego Becky mo¿e sprzedawaæ gorza³ê tak tanio.}
{202}{}{Zepsuj aparaturê Becky.}
{203}{}{Zdob¹dŸ czêœci samochodowe dla Smitty'ego.}
{204}{}{Zwróæ medalion Anny.}
{205}{}{Collect Rebecca's money from Fred.}
{206}{}{Get Rebecca's book from Derek.}
{207}{}{Zanieœ Smitty'emu jedzenie od Mamuœki.}
{208}{}{Lara chce wiedzieæ, co jest przechowywane w koœciele.}
{209}{}{Get permission from Metzger for the gang war.}
{210}{}{Find a weakness in Tyler's gang guarding the church.}
{211}{}{Pomó¿ Larze zaatakowaæ gang Tylera.}
{300}{}{Pod³ó¿ ogieñ pod aparaturê destylacyjn¹.}
{301}{}{Uratuj trapera imieniem Smiley.}
{302}{}{Pilnuj bramin.}
{303}{}{Ukradnij braminy.}
{304}{}{Zabij króla szczurów.}
{305}{}{Ocal Torra.}
{400}{}{Na farmie po³o¿onej na pó³nocny wschód od Modoc dzieje siê coœ dziwnego. Zbadaj sprawê i z³ó¿ relacjê Jo.}
{401}{}{Cornelius zgubi³ swój z³oty zegarek kieszonkowy. ZnajdŸ go i zwróæ w³aœcicielowi.}
{402}{}{Farrel chce, ¿ebyœ znalaz³ z³oty zegarek kieszonkowy Corneliusa. ZnajdŸ go i zwróæ Farrelowi.}
{403}{}{Jonny zagin¹³. ZnajdŸ go i przyprowadŸ do domu, do Balthasa.}
{404}{}{Jonny jest w jaskiniach. ZnajdŸ sposób, ¿eby doprowadziæ Jonny'ego do domu, do Balthasa.}
{405}{}{Farrel ma w swoim ogrodzie problem z chwastami. Pozb¹dŸ siê ich.}
{406}{}{Deliver the Slag's message to Jo in Modoc.}
{407}{}{Jo jest podejrzliwy wobec ¯u¿lowców. Dowiedz siê, sk¹d pochodz¹ martwe cia³a na Nawiedzonej Farmie, a tak¿e co przytrafi³o siê Karlowi.}
{408}{}{IdŸ do Nory powiedz Karlowi, ¿e mo¿e ju¿ wróciæ do domu.}
{409}{}{Pilnuj bramin Grishama.}
{500}{}{Zdob¹dŸ p³ug dla Pana Smitha.}
{501}{}{Dostarcz aktówkê Moore'a Panu Bishopowi w Nowym Reno.}
{502}{}{Dostarcz próbkê narkotyku Jet doktorowi Troy.}
{503}{}{Rozwi¹¿ problem z elektrowni¹ w Gecko.}
{504}{}{Dostarcz holodysk Lynette Westinowi w RNK.}
{505}{}{Ocal mê¿a Amandy, Joshuê.}
{506}{}{Zanieœ piwo i bimber (po 10 butelek) Lydii.}
{507}{}{ZnajdŸ kombinerki (narzêdzia) i klucz francuski dla Valerie.}
{508}{}{Zbadaj osiem sektorów otaczaj¹cych Gecko i wróæ do Starka.}
{509}{}{WejdŸ do RNK i wróæ do Starka.}
{600}{}{Rozwi¹¿ problem z elektrowni¹ w Gecko.}
{601}{}{Napraw elektrowniê.}
{602}{}{Zoptymalizuj pracê elektrowni.}
{603}{}{Zdob¹dŸ dysk z danymi ekonomicznymi i dostarcz go McCluremu w Kryptopolis.}
{604}{}{Zdob¹dŸ super zestaw naprawczy od Skeetera.}
{605}{}{Zdob¹dŸ trójfazowy transformator plazmowy dla Skeetera.}
{606}{}{Poszukaj ghula Woody'ego dla Percy'ego. Spróbuj w Norze.}
{700}{}{}
{701}{}{Napraw system oczyszczania powietrza w kopalni.}
{702}{}{ZnajdŸ zaginionych ludzi dla Marcusa.}
{703}{}{Pokonaj Francisa w si³owaniu siê na rêkê.}
{704}{}{Odbij Mansona i Francisa z wiêzienia.}
{705}{}{WysadŸ system oczyszczania powietrza w kopalni.}
{706}{}{Skieruj wiêcej mocy elektrycznej do domu Erica.}
{800}{}{Odzyskaj swój skradziony samochód.}
{801}{}{ZnajdŸ winnego przedawkowania przez Richarda Wrighta.}
{802}{}{     Podejrzany: Jimmy J}
{803}{}{     Podejrzany: Jules}
{804}{}{     Podejrzany: "Ma³y" Jesus Mordino}
{805}{}{     Podejrzany: Renesco}
{806}{}{ZnajdŸ sposób na dostanie siê do Bazy Sierra.}
{807}{}{WyœledŸ Lloyda, odzyskaj pieni¹dze i spraw, by jego przypadek sta³ siê... przyk³adem dla innych.}
{808}{}{OdwiedŸ Renesco i odbierz op³atê dla Pana Salvatore w wysokoœci $1000.}
{809}{}{Pomó¿ w nadzorowaniu transakcji na pustyni.}
{810}{}{ZnajdŸ substancje blokuj¹ce endorfinê, ¿eby stworzyæ lekarstwo na Jet.}
{811}{}{WysadŸ w powietrze kocio³ Wrighta, w pobli¿u stacji kolejowej.}
{812}{}{Zlikwiduj Westina w RNK tak, ¿eby nie wygl¹da³o to na morderstwo.}
{813}{}{Zabij Carlsona w RNK.}
{814}{}{Dostarcz egzemplarze magazynu Kocia £apka Pani Kici.}
{815}{}{Dostarcz pistolet laserowy Eldridge'owi.}
{816}{}{Dostarcz paczkê Du¿ego Jesusa Ramirezowi, w Stajniach.}
{817}{}{Zbierz op³aty od Braci Corsican.}
{818}{}{Zlikwiduj Pana Salvatore dla Du¿ego Jesusa Mordino.}
{900}{}{}
{1000}{}{}
{1100}{}{Zdob¹dŸ czêœci/uzyskaj dostêp do Krypty 15.}
{1101}{}{Zaopiekuj siê "oficerem Jackiem" dla Miry.}
{1102}{}{Complete the brahmin drive.}
{1103}{}{Retrieve the papers from Dr. Henry.}
{1104}{}{Test the mutagenic serum on a super-mutant. Try Broken Hills.}
{1105}{}{Wyeliminuj Pana Bishopa.}
{1106}{}{Dostarcz holodysk Westina do Lynette w Kryptopolis.}
{1107}{}{Zdob¹dŸ dla Vortisa £owcy Niewolników mapê od Stra¿ników RNK.}
{1108}{}{Uwolnij niewolników z zagrody (dla Stra¿ników RNK).}
{1109}{}{Deliver the Hubologist's field report to AHS-9 in San Francisco.}
{1110}{}{Zabij Centrologa w RNK dla Merka.}
{1111}{}{Powstrzymaj uprowadzenia bramin.}
{1200}{}{Napraw komputer Krypty 13.}
{1201}{}{Porozmawiaj z Gorisem.}
{1300}{}{}
{1400}{}{ZnajdŸ procesor do maszyny górniczej.}
{1401}{}{Przerwij rozróbê w barze.}
{1402}{}{Dowiedz siê, kto poci¹³ dziwkê.}
{1403}{}{Zabij ¯abê Mortona.}
{1500}{}{Tankowiec potrzebuje paliwa.}
{1501}{}{Komputer nawigacyjny potrzebuje uk³adu nawigacyjnego, ¿eby móc dzia³aæ.}
{1502}{}{Musisz u¿yæ karty wejœciowej, ¿eby uzyskaæ dostêp do komputera nawigacyjnego.}
{1503}{}{Zabij Imperatora Shi.}
{1504}{}{Centrolodzy potrzebuj¹ planów latacza z Navarro.}
{1505}{}{Ukradnij plany latacza od Shi.}
{1506}{}{Centrolodzy potrzebuj¹ paliwa dla ich statku kosmicznego.}
{1507}{}{Zabij Badgera, ¿eby w³óczêdzy z tankowca mogli przej¹æ Hub.}
{1508}{}{Zabij UKC-9.}
{1509}{}{Shi potrzebuj¹ planów latacza z Navarro.}
{1510}{}{Zdob¹dŸ plany latacza od Centrologów.}
{1511}{}{ZnajdŸ dziewczynê Badgera w ³adowni pod statkiem.}
{1512}{}{Smok chce, ¿ebyœ pozby³ siê Lo Pana - najlepiej w walce wrêcz.}
{1513}{}{Lo Pan chce, ¿ebyœ pozby³ siê Smoka - najlepiej w walce wrêcz, je¿eli to mo¿liwe.}
{1514}{}{Get Chip's spleen back.}
{1515}{}{Zdob¹dŸ ulepszony pancerz wspomagany od Crocketta.}
{1516}{}{Zdob¹dŸ plany latacza dla Bractwa Stali.}
{1600}{}{Uwolnij szpona œmierci.}
{1601}{}{Napraw K9.}
{1602}{}{Zdob¹dŸ kartê dostêpu od dowódcy bazy.}
{1700}{}{}
{1800}{}{}
{1900}{}{}
{2000}{}{}
{2100}{}{}
{2200}{}{}
{2300}{}{}
{2400}{}{}
{2500}{}{}
{2600}{}{}
{2700}{}{}
{2800}{}{}
{2900}{}{}
{3000}{}{}
{3100}{}{}
{3200}{}{Ocal Chrissy}
{3201}{}{Zabij Dariona}
{3202}{}{Complete the deal with NCR.}
{3203}{}{Give the Spy Holodisk to the authorities in NCR.}
