#
# Quest descriptons
#
# Please leave space between the areas (like 100 or so)
#


#
# Arroyo Quests
#
{100}{}{Zabij z³oœliwe chwasty, które rozpleni³y siê w ogrodzie Hakuninna.}
{110}{}{Zdob¹dŸ krzemieñ dla Mynoca, ¿eby móg³ naostrzyæ twoj¹ w³óczniê.}
{120}{}{Odszukaj psa Nagora, który zagin¹³ w dziczy.}
{130}{}{Zdob¹dŸ GECK dla swojego obozu.}
{140}{}{ZnajdŸ handlarza imieniem Vic.}

#
# Den Quests
#
{200}{}{Ureguluj nale¿noœci Vica. Przynieœ radio z jego domu w Klamath i zap³aæ Metzgerowi.}
{201}{}{Zepsuj aparaturê Becky.}
{202}{}{Zdob¹dŸ czêœci samochodowe dla Smitty'ego.}
{203}{}{Zwróæ medalion Anny.}
{204}{}{Zbierz pieni¹dze od Freda.}
{205}{}{Zdob¹dŸ ksi¹¿kê od Dereka.}
{206}{}{Zanieœ Smitty'emu jedzenie od Mamuœki.}
{207}{}{Lara chce wiedzieæ, co jest przechowywane w koœciele.}
{208}{}{Uzyskaj pozwolenie na wojnê gangów od Metzgera.}
{209}{}{ZnajdŸ s³abe punkty gangu Tylera, strzeg¹cego koœcio³a.}
{210}{}{Pomó¿ Larze zaatakowaæ gang Tylera.}

#
# Klamath Quests
#
{300}{}{Pod³ó¿ ogieñ pod aparaturê destylacyjn¹.}
{301}{}{Uratuj trapera imieniem Smiley.}
{302}{}{Pilnuj braminów.}
{303}{}{Ukradnij braminy.}
{304}{}{Zabij króla szczurów.}
{305}{}{Ocal Torra.}

#
# Modoc Quests
#
{400}{}{Na farmie po³o¿onej na pó³nocny wschód od Modoc dzieje siê coœ dziwnego. Zbadaj sprawê i z³ó¿ relacjê Jo.}
{401}{}{Cornelius zgubi³ swój z³oty zegarek kieszonkowy. ZnajdŸ go i zwróæ w³aœcicielowi.}
{402}{}{Farrel chce, ¿ebyœ znalaz³ z³oty zegarek kieszonkowy Corneliusa. ZnajdŸ go i zwróæ Farrelowi.}
{403}{}{Jonny zagin¹³. ZnajdŸ go i przyprowadŸ do domu, do Balthasa.}
{404}{}{Jonny jest w jaskiniach. ZnajdŸ sposób, ¿eby doprowadziæ Jonny'ego do domu, do Balthasa.}
{405}{}{Farrel ma w swoim ogrodzie problem z chwastami. Pozb¹dŸ siê ich.}
{406}{}{Dostarcz wiadomoœæ do Jo w Modoc.}
{407}{}{Jo jest podejrzliwy wobec ¯u¿lowców. Dowiedz siê, sk¹d pochodz¹ martwe cia³a na Nawiedzonej Farmie, a tak¿e co przytrafi³o siê Karlowi.}
{408}{}{IdŸ do Nory powiedz Karlowi, ¿e mo¿e ju¿ wróciæ do domu.}

#
# Vault City Quests
#
{500}{}{Zdob¹dŸ p³ug dla Pana Smitha.}
{501}{}{Dostarcz aktówkê Moore'a Panu Bishopowi w Nowym Reno.}
{502}{}{Dostarcz próbkê narkotyku Jet doktorowi Troy.}
{503}{}{Rozwi¹¿ problem z elektrowni¹ w Gecko.}
{504}{}{Dostarcz holodysk Lynette Westinowi w RNK.}
{505}{}{Ocal mê¿a Amandy, Joshuê.}
{506}{}{Zanieœ piwo i bimber (po 10 butelek) Lydii.}
{507}{}{ZnajdŸ kombinerki (narzêdzia) i klucz francuski dla Valerie.}
{508}{}{Zbadaj osiem sektorów otaczaj¹cych Gecko i wróæ do Starka.}
{509}{}{WejdŸ do RNK i wróæ do Starka.}

#
# Gecko Quests
#
{600}{}{Rozwi¹¿ problem z elektrowni¹ w Gecko.}
{601}{}{Napraw elektrowniê.}
{602}{}{Zoptymalizuj pracê elektrowni.}
{603}{}{Zdob¹dŸ super zestaw naprawczy od Skeetera.}
{604}{}{Zdob¹dŸ trójfazowy transformator plazmowy dla Skeetera.}
{605}{}{Poszukaj ghula Woody'ego dla Percy'ego. Spróbuj w Norze.}

#
# Broken Hills Quests
#
{700}{}{}
{701}{}{Napraw system oczyszczania powietrza w kopalni.}
{702}{}{ZnajdŸ zaginionych ludzi dla Marcusa.}
{703}{}{Pokonaj Francisa w si³owaniu siê na rêkê.}
{704}{}{Odbij Mansona i Francisa z wiêzienia.}
{705}{}{WysadŸ system oczyszczania powietrza w kopalni.}
{706}{}{Skieruj wiêcej mocy elektrycznej do domu Erica.}

#
# New Reno Quests
#
{800}{}{Odzyskaj swój skradziony samochód.}
{801}{}{ZnajdŸ winnego przedawkowania przez Richarda Wrighta.}
{802}{}{     Podejrzany: Jimmy J}
{803}{}{     Podejrzany: Jules}
{804}{}{     Podejrzany: "Ma³y" Jesus Mordino}
{805}{}{     Podejrzany: Renesco}
{806}{}{ZnajdŸ sposób na dostanie siê do Bazy Sierra.}
{807}{}{WyœledŸ Lloyda, odzyskaj pieni¹dze i spraw, by jego przypadek sta³ siê... przyk³adem dla innych.}
{808}{}{OdwiedŸ Renesco i odbierz op³atê dla Pana Salvatore w wysokoœci $1000.}
{809}{}{Pomó¿ w nadzorowaniu transakcji na pustyni.}
{810}{}{ZnajdŸ substancje blokuj¹ce endorfinê, ¿eby stworzyæ lekarstwo na Jet.}
{811}{}{WysadŸ w powietrze kocio³ Wrighta, w pobli¿u stacji kolejowej.}
{812}{}{Zlikwiduj Westina w RNK tak, ¿eby nie wygl¹da³o to na morderstwo.}
{813}{}{Zabij Carlsona w RNK.}
{814}{}{Dostarcz egzemplarze magazynu Kocia £apka Pani Kici.}
{815}{}{Dostarcz pistolet laserowy Eldridge'owi.}
{816}{}{Dostarcz paczkê Du¿ego Jesusa Ramirezowi, w Stajniach.}
{817}{}{Zbierz op³aty od Braci Corsican.}
{818}{}{Zlikwiduj Pana Salvatore dla Du¿ego Jesusa Mordino.}

#
# Sierra Army Base Quests
#
{900}{}{}

#
# Vault 15 Quests
# Moved it to 3000 on accedent
{1000}{}{}

#
# New California Republic Quests
#
{1100}{}{Zdob¹dŸ czêœci/uzyskaj dostêp do Krypty 15.}
{1101}{}{Zaopiekuj siê "oficerem Jackiem" dla Miry.}
{1102}{}{Skoñcz sprawê z braminami.}
{1103}{}{Odbierz papiery od dr Henry'ego.}
{1104}{}{SprawdŸ dzia³anie serum mutagenicznego na super-mutancie. Spróbuj w Broken Hills.}
{1105}{}{Wyeliminuj Pana Bishopa.}
{1106}{}{Dostarcz holodysk Westina do Lynette w Kryptopolis.}
{1107}{}{Zdob¹dŸ dla Vortisa £owcy Niewolników mapê od Stra¿ników RNK.}
{1108}{}{Uwolnij niewolników z zagrody (dla Stra¿ników).}
{1109}{}{Dostarcz raport polowy centrologów do UKC-9 w San Francisco.}
{1110}{}{Zabij centrologa w RNK dla Merka.}
{1111}{}{Powstrzymaj uprowadzenia braminów.}
#
# Vault 13 Quests
#
{1200}{}{Napraw komputer Krypty 13.}
{1201}{}{Porozmawiaj z Gorisem.}

#
# Military Base Quests
#
{1300}{}{}

#
# Redding Quests
#
{1400}{}{Dowiedz siê, kto poci¹³ dziwkê.}
{1401}{}{ZnajdŸ procesor do maszyny górniczej.}
{1402}{}{Przerwij rozróbê w barze.}
{1403}{}{Zabij ¯abê Mortona.}

#
# San Francisco Quests
#
{1500}{}{Tankowiec potrzebuje paliwa.}
{1501}{}{Komputer nawigacyjny potrzebuje uk³adu nawigacyjnego, ¿eby móc dzia³aæ.}
{1502}{}{Musisz u¿yæ karty wejœciowej, ¿eby uzyskaæ dostêp do komputera nawigacyjnego.}
{1503}{}{Zabij Imperatora Shi.}
{1504}{}{Centrolodzy potrzebuj¹ planów latacza z Navarro.}
{1505}{}{Ukradnij plany latacza od Shi.}
{1506}{}{Centrolodzy potrzebuj¹ paliwa dla ich statku kosmicznego.}
{1507}{}{Zabij Badgera, ¿eby w³óczêdzy z tankowca mogli przej¹æ Hub.}
{1508}{}{Zabij UKC-9.}
{1509}{}{Shi potrzebuj¹ planów latacza z Navarro.}
{1510}{}{Zdob¹dŸ plany latacza od Centrologów.}
{1511}{}{ZnajdŸ dziewczynê Badgera w ³adowni pod statkiem.}
{1512}{}{Smok chce, ¿ebyœ pozby³ siê Lo Pana - najlepiej w walce wrêcz.}
{1513}{}{Lo Pan chce, ¿ebyœ pozby³ siê Smoka - najlepiej w walce wrêcz, je¿eli to mo¿liwe.}
{1514}{}{Zdob¹dŸ œledzionê dla Chipa.}
{1515}{}{Zdob¹dŸ ulepszony pancerz wspomagany od Crocketta.}
{1516}{}{Zdob¹dŸ plany latacza dla Bractwa Stali.}
#
# Navarro Quests
#
#1515, ...
{1600}{}{Uwolnij szpona œmierci.}
{1601}{}{Napraw K9.}
{1602}{}{Zdob¹dŸ kartê dostêpu od dowódcy bazy.}

#
# The Enclave Quests
#
{1700}{}{}

#
# The Abbey Quests
#
{1800}{}{}

#
# Primitive Tribe Quests
#
{1900}{}{}

#
# EPA Quests
#
{2000}{}{}

#
# Ghost Town Quests
#
{2100}{}{}

#
# Car outta Gas Quests
#
{2200}{}{}

#
# Destroyed Arroyo Quests
#
{2300}{}{}

#
# Toxic Caves Quests
#
{2400}{}{}

#
# Den Slave Run Quests
#
{2500}{}{}

#
# Raiders Quests
#
{2600}{}{}

#
# Desert Encounter Quests
#
{2700}{}{}

#
# Mountain Encounter Quests
#
{2800}{}{}

#
# Ruined City Encounter Quests
#
{2900}{}{}

#
# Coast Encounter Quests
#
{3000}{}{}

#
# Golgotha Quests
#
{3100}{}{}


#
# Vault 15 Quests
#
{3200}{}{Ocal Chrissy}
{3201}{}{Zabij Dariona}
{3202}{}{Zfinalizuj transakcjê z RNK.}
{3203}{}{Przeka¿ holodysk szpiegowski odpowiednim w³adzom w RNK.}
