call ..\p QCBIRD
call ..\p QCCURLNG
call ..\p QCEPSQAD
call ..\p QCFRANK
call ..\p QCGENCIT
call ..\p QCGENGRD
call ..\p QCGENPRS
call ..\p QCGENSCI
call ..\p QCGRANIT
call ..\p QCMARTIN
call ..\p QCMURRAY
call ..\p QCPRSSEC
call ..\p QCSECBOT
call ..\p QCTURRET
call ..\p QIBSTDR1
call ..\p QIBSTDR2
call ..\p QIENDDOR
call ..\p QIGECKDR
call ..\p QIKLAXON
call ..\p QIPZLDOR
call ..\p QIPZLTRM
call ..\p QIREACTR
call ..\p QITURTRM
call ..\p QIWIRES
