{100}{}{Vidíš stráce mostu.}
{101}{}{Vidíš Mynoca, stráce mostu.}
{150}{}{Pøed tebou stojí slavnı váleèník tvého kmene. V ruce drí kopí.}
{151}{}{[MLUVIT]}
{152}{}{Ahoj, Vyvolenı. Jdeš hledat GECK?}
{153}{}{Ano.}
{154}{}{Ano. A pøedtím, ne odejdu, se tì chci na nìco zeptat.}
{155}{}{Ne, zatím ne. Musím se tu ještì trošku víc porozhlédnout.}
{156}{}{Tak a tì bohové ochraòují.}
{157}{}{Díky. Sbohem.}
{158}{}{Co chceš vìdìt?}
{159}{}{Co mi mùeš øíct o lidech, kteøí obchodují s naší vesnicí?}
{160}{}{Co mi mùeš povìdìt o tomhle pøedmìtu, kterı prı pochází z Vaultu?}
{161}{}{Nic, zapomeò na to.}
{162}{}{Tak dobrá, ale neztrácej tu zbyteènì moc èasu. Bez GECKu jsme všichni ztraceni.}
{163}{}{Já vím, nemìj strach. Všechno mám pod kontrolou.}
{164}{}{Jak to?}
{165}{}{Musím jít. Sbohem.}
{166}{}{Obchodníci? Zhruba kadé dva mìsíce sem pøicházejí z Klamathu. Další se tu teï neobjeví døív ne za mìsíc i pøesto, e Klamath není zase tak daleko. Je odsud jen pár dní cesty smìrem na vıchod.}
{167}{}{Díky. Sbohem.}
{168}{}{Co mi mùeš øíct o tomhle pøedmìtu, kterı údajnì pochází z posvátného Vaultu?}
{169}{}{Vypadá to jako kovová láhev na vodu. Moná nám ji Vault posílá jako znamení.}
{170}{}{Mùeš mi øíct, kdo ji k nám do vesnice pøinesl?}
{171}{}{Díky, u musím jít. Sbohem.}
{172}{}{To doufám. Sbohem.}
{173}{}{Kvùli tvému pøebujelému sebevìdomí tu všichni trpíme! Sbohem!}
{174}{}{Sbohem.}
{175}{}{Proè? Rozhlédni se kolem. Naše vesnice umírá, zahrady chøadnou a kadı den se zhroutí nìjaké dítì nebo nìkdo ze starších. Musíš nám pøinést Ráj, dokud je ještì èas!}
{176}{}{Postarám se o to. Sbohem.}
{177}{}{Já jsem Vyvolenı. "Musím" dìlat jen to, co se mi líbí. Sbohem.}
{178}{}{Nevzpomínám si na jeho jméno. Vím jen, e byl starı a hluènı. A tak, e to nebylo slušné, ale za to vìdìl hodnì vìcí. Byl z Klamathu. To je na vıchod odsud, jak u jsem øíkal.}
{179}{}{Díky. Sbohem.}
{180}{}{Ty jsi poøád ještì tady? Musíš jít hledat GECK. To, e jsi poøád tady, nám moc nepomùe!}
{181}{}{Tenhle most je to jediné, co tì má zajímat, pøíteli. Já se o sebe umím postarat.}
{182}{}{Právì jsem na odchodu. Sbohem, pøíteli.}
{183}{}{U s tebou nebudu mluvit, ty hnusné prase!}
{184}{}{Chci ti ještì poloit pár otázek.}
{185}{}{To bylo rychlé! U víš, kde leí svatı Vault 13?}
{186}{}{Ano.}
{187}{}{Ne, ještì ne.}
{188}{}{Opravdu? To je skvìlé! Pøinesl jsi nám GECK?}
{189}{}{Ne.}
{190}{}{Ne. Ještì jsem s lidmi z Vaultu nemluvil.}
{191}{}{Myslím, e to není tvoje starost, pøíteli.}
{192}{}{Ne? Vyvolenı, od té doby, co jsi pryè, zemøeli u tøi ze starších. Nesmíš ztrácet èas.}
{193}{}{Najdu ho, nemìj strach.}
{194}{}{Toho tvého neustálého sekırování u zaèínám mít plné zuby.}
{195}{}{No, tak proè mluvíš se mnou? Promluv si s nimi a pøines nám GECK.}
{196}{}{Neboj, všechno bude v poøádku, pøíteli.}
{197}{}{Toho tvého neustálého sekırování u zaèínám mít plné zuby.}
{198}{}{Nìjaké novinky ohlednì GECKu, Vyvolenı?}
{199}{}{U vím, kde je Vault!}
{200}{}{Nemùu Vault 13 poøád nikde najít.}
{201}{}{No to se podívejme, Vyvolenı.}
{202}{}{Ahoj.}
{203}{}{Sklapnìte.}
{204}{}{Mùu se tì na nìco zeptat?}
{205}{}{Ne, nemám na tebe èas.}
{206}{}{Jak chceš. Sbohem.}
{207}{}{No dobøe. Ještì se uvidíme.}
{208}{}{Chcípni!}
{209}{}{Zdravím, trotlíku! Vidíš tenhle most? Ty pøejít. Bıt opatrnı! Most nebezpeènı. Ty nechtít spadnout. Ty rozumìt?}
{210}{}{Hmm... bùm?}
{211}{}{Ty svinì! Jsi zrádce naší vesnice!}
{212}{}{Zradil jsi nás. Za to zemøeš!}
{213}{}{Jsi zrádce svıch vlastních lidí.}
{214}{}{Proè tohle dìláš?}
{215}{}{Starší se zmılila. Ty jsi zlo.}
{300}{}{Mùj otec mì nauèil vyrábìt mnohem ostøejší hroty, ne má vìtšina kopí. Dones mi kousek pazourku a já ti upravím i tvoje kopí. V pustinì se ti to bude hodit.}
{301}{}{Kde se dá takovı pazourek sehnat?}
{302}{}{Myslím, e tvá teta Morlis jeden kus schovávala. Je ale tak nevrlá, e si myslím, e se ji ještì nikdo neodváil na nìj zeptat. Ta èarodìjnice bude urèitì chtít nìco na oplátku.}
{303}{}{Díky. Sbohem.}
{304}{}{Co ten pazourek? Máš ho?}
{305}{}{Ano, tady je.}
{306}{}{Ještì ne.}
{307}{}{Ano, to je dobrı kousek. Podej mi své kopí.}
{308}{}{Tady je.}
{309}{}{Já... já ádné nemám.}
{310}{}{A teï se dáme do práce...}
{311}{}{Vyvolenı a nemá kopí? No, budu muset pouít jedno z mıch. A teï se dáme do práce...}
{312}{}{Tady máš svoje nové kopí.}
{313}{}{Díky, pøíteli. Hodnì mi to pomùe.}
{314}{}{No, zaujalo mì tvoje kopí. Vypadá trochu jinak ne mají ostatní.}
{400}{}{Vítej doma, Vyvolenı! Našel jsi svatı Vault? Máš pro nás GECK?}
{401}{}{Já nenajít... zatím.}
{402}{}{Ne, zatím mi štìstí nepøálo.}
{403}{}{Nemám teï zrovna náladu na tvoje vyptávání. Sbohem.}
{404}{}{Vìci se nevyvíjejí dobøe, Vyvolenı. Je velké sucho a naše úroda je na tom zle. Snaíme se dìlat, co je v našich silách, ale je to poøád horší a horší.}
{405}{}{Proè ne obchod s jiná vesnice?}
{406}{}{Já snait se moc. Já najít GECK. Já vrátit.}
{407}{}{Proè neobchodujeme s ostatními vesnicemi? Myslím, e by nám potøebné potraviny dodaly.}
{408}{}{Snaím se ze všech sil. A najdu GECK, vrátím se s ním.}
{409}{}{Jsme jen obyèejní lidé a nemáme co nabídnout. Tìch nìkolik málo mìst, která jsme poádali, neprojevilo ani špetku zájmu nám pomoct.}
{410}{}{Já chápat.}
{411}{}{Aha.}
{412}{}{Jsi naše jediná nadìje, Vyvolenı. Prosím, nezklam nás!}
{413}{}{Rád tì vidím, Vyvolenı. Jak se ti daøí ve tvém poslání?}
{414}{}{Ne, stále hledat.}
{415}{}{Stále ho ještì hledám.}
{416}{}{Nechci o tom mluvit.}
{417}{}{Musíš si pospíšit. Tady doma je to èím dál horší. Brzy nebudeme mít ádné jídlo a Starší mluví o zavedení pøídìlù. Bojím se budoucnost. Bojím se o Arroyo.}
{418}{}{Vyvolenı! Prosím øekni mi, e u jsi dokonèil své poslání. Naše vesnice umírá a lidé jsou na tom moc špatnì.}
{419}{}{Ne, já stále hledat.}
{420}{}{Bohuel zatím ne. Ale opravdu se snaím.}
{421}{}{Jak to jde?}
{422}{}{Je mi to líto, Vyvolenı, ale pomalu v tebe pøestávám vìøit. ivoty našich lidí jsou ve tvıch rukou. Prosím najdi svatou Tøináctku a pøines nám GECK!}
{423}{}{Naše úroda vadne, brahmíny hynou, všichni hladoví. Náøky dìtí v noci nikoho nenechají spát. Jsme zoufalí.}
{424}{}{Já pokraèovat hledat.}
{425}{}{Udìlám, co je v mıch silách.}
{426}{}{Opìt se k nám navracíš, Vyvolenı? Doufám, e ne s prázdnou.}
{427}{}{Já líto, já ne najít GECK ještì.}
{428}{}{Je mi líto, ale stále nemùu GECK najít.}
{429}{}{U toho mám dost.}
{430}{}{Lidé tady umírají, zatímco ty se touláš po okolí. Moná bys mìl zkusit hledat nìkde jinde a ne se poøád vracet sem.}
{500}{}{U jsi mluvil se Starší?}
{1000}{}{Starsi}
{1001}{}{Zakladatel}
{1002}{}{Obyvatel Vaultu}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Vyvoleny}
{1007}{}{Saman}
{1008}{}{Hakunin}
{1009}{}{Lecivy prasek}
{1010}{}{Most}
{1011}{}{Mynoc}
{1100}{}{Starší je tvoje matka a náš vùdce.}
{1101}{}{Náš slavnı pøedek, kterı nám pøedal své znalosti.}
{1102}{}{První èlovìk, kterı bojoval a zvítìzil nad chaosem.}
{1103}{}{To je naše krásná vesnice.}
{1104}{}{That’s trading outpost a few days east of here.}
{1105}{}{Vault je jako nebe.}
{1106}{}{Ty jsi Vyvolenı.}
{1107}{}{Léèí nás pomocí bylin a magie. Bydlí v severní èásti vesnice.}
{1108}{}{Léèí nás pomocí bylin a magie. Bydlí v severní èásti vesnice.}
{1109}{}{To je léèivı prášek, kterı tì vyléèí, ale bude se ti po nìm chtít spát.}
{1110}{}{Velikı most je jedinım vıchodem z naší vesnice.}
{1111}{}{To bych mìl bıt já.}
