{100}{}{Vidíš malého mue drícího knihu.}
{101}{}{Vidíš doktora Jonese.}
{102}{}{Vidíš malého mue. V ruce drí knihu "Doktorem snadno a rychle."}
{103}{}{Ahoj, já jsem doktor Jones. Mùeš mi øíkat doktore. S èím ti mohu pomoci?}
{104}{}{Mít bebí. Ty pomoct?}
{105}{}{Cítit blbì. Ty pomoct?}
{106}{}{Já ochrnout. Ty pomoct?}
{107}{}{Mít otázky. Jo?}
{108}{}{Promiò, já jít.}
{109}{}{Mám zranìní. Mùeš mi pomoct?}
{110}{}{Cítím se slabì. Mùeš mi pomoct?}
{111}{}{Mám ochrnutou konèetinu. Mùeš mi pomoct?}
{112}{}{Chci se tì na nìco zeptat.}
{113}{}{Jen jsem tì chtìl pozdravit.}
{114}{}{Samozøejmì. Uka, dám ti tuhle injekci... trošku to štípne. Teï ještì obvaz a jsi zase jako ze škatulky.}
{115}{}{Já dík. Ahoj.}
{116}{}{Díky, doktore. Cítím se mnohem lépe.}
{117}{}{Samozøejmì. Musíš vypít tohle... a do dna. Vím, chutná to hroznì. A teï si tady lehni na postel a já tì ráno vzbudím.}
{118}{}{Já cítit dobøe. Ahoj.}
{119}{}{Díky doktore, to mi pomohlo.}
{120}{}{Promiò, ale nemám tu vhodné nástroje k provádìní chirurgickıch zákrokù. Doporuèuju ti zajít do nìkterého vìtšího mìsta a vyhledat chirurga. Zkus Vault City. Je to na sever odsud.}
{121}{}{Dobøe. Sbohem.}
{122}{}{Tak dobøe, ale stejnì díky.}
{123}{}{Co potøebujete vìdìt?}
{124}{}{Ty pracovat pro Darion?}
{125}{}{Ty odejít odsud kdy chtít?}
{126}{}{Co ty vìdìt o Darion?}
{127}{}{Kde ty tu vzít?}
{128}{}{Ty øíkat, e Darion mít pejska?}
{129}{}{Já teï jít.}
{130}{}{Pracuješ pro Dariona?}
{131}{}{Mùeš odejít kdykoliv chceš?}
{132}{}{Co mi mùeš øíct o Darionovi?}
{133}{}{Jak ses sem dostal?}
{134}{}{Øíkal jsi, e má Darion psa?}
{135}{}{Díky za informace. U musím jít.}
{136}{}{Ano i ne. Nevybral jsem si to. Jsem tu vìzeò. Darion je tu u dlouho a potøeboval nìjakého doktora, kterı by se o nìj staral. Khanové mì tu drí pro svou potøebu. Ale radìji bych pracoval pro lidi z té komunity nahoøe. Nemají tam ádnou lékaøskou péèi a myslím, e bych jim mohl opravdu hodnì pomoci.}
{137}{}{Dobøe. Potøebovat vìdìt víc.}
{138}{}{Dík. Naskle.}
{139}{}{To je od tebe velmi chvályhodné.}
{140}{}{Aha. U musím jít.}
{141}{}{Vdy jsou to jen bezdomovci! A si klidnì chcípnou. Ty se radìji starej o svùj vlastní krk.}
{142}{}{Ne. Jsem tady vìznìm. Nemùu ani odejít, abych si doplnil lékaøskı materiál. Darion mi posílá všechno, co potøebuju.}
{143}{}{Já chápat. Já jít.}
{144}{}{Potøebovat zeptat víc.}
{145}{}{Nejspíš nejsi natolik dùvìryhodná osoba, aby sis zaslouil svobodu.}
{146}{}{Rozumím. Promiò, ale u musím jít.}
{147}{}{To je mi líto.}
{148}{}{Darion je struènì øeèeno pøípad pro psychiatra. Má v hlavì víc vrtochù ne jeho pes blech v koichu. Jestli tomu dobøe rozumím, tak kdysi dávno byl èlenem nìjakého gangu, kterı si øíkal Khanové. Ti unesli dívku, Tandi, kterou dreli jako rukojmí. Dreli ji pod zámkem kvùli vıkupnému. Její otec si to ale nenechal líbit a najal si oldáka, aby mu ji našel a pøivedl zpátky. Darion byl jedinı Khan, kterı ten masakr pøeil.}
{149}{}{Eh... co ty øíkat?}
{150}{}{Muset teï jít.}
{151}{}{Hmm... hmmm. No, u budu muset jít.}
{152}{}{No, musím øíct, e tvoje vìdomosti jsou opravdu pozoruhodné.}
{153}{}{Ten chlapík je pøesnì mùj typ.}
{154}{}{Byl jsem unesen. Cestoval jsem z Vault City do New Rena na zaslouenou dovolenou. Jednou veèer jsem si šel lehnout a ráno jsem se probudil spoutanı a s roubíkem v puse. A za tıden nebo dva u jsem byl tady. Od té doby tu jsem zavøenı.}
{155}{}{Eh.}
{156}{}{Díky. Já muset jít.}
{157}{}{Slabí se èasto stávají koøistí silnıch. Takovı u je ivot, pøíteli.}
{158}{}{To je mi líto.}
{159}{}{Zajímavé povídání, ale u musím bìet.}
{160}{}{Jo, má psa. Osobnì si myslím, e je to ta nejhnusnìjší a nejodpornìjší bestie na celém širém svìtì, ale na druhé stranì to vypadá, e má Dariona docela rád, take to s ním snad nebude zase a tak špatné.}
{161}{}{Já ještì ptát.}
{162}{}{Eh, sbohem.}
{163}{}{Aha. Díky za upozornìní.}
{164}{}{Aha. No, u musím jít.}
{165}{}{Nebudu pomáhat nìkomu takovému, jako jsi ty. Jdi pryè.}
{166}{}{Dobøe, tak se mìj a vra se, kdy budeš nìco potøebovat.}
{167}{}{Beru.}
{168}{}{Teï je z nìj paranoik. Myslí si, e ho Tandi chce zabít. Je posedlı pomstou a chce, aby Tandi zemøela. Cítí se vinen za to, e se schoval a pøeil, místo aby zemøel spolu se svım gangem... a tak dále, a tak dále. Seznam jeho obsedantních vizí je opravdu dlouhı.}
