{100}{}{Vidíš strá.}
{101}{}{Vidíš strá v energo zbroji.}
{102}{}{Vidíš osobu v energo zbroji neobvyklého vzhledu. Na prsou má znak, kterı nepoznáváš.}
{103}{}{Po dobu mé sluby se nic zvláštního nestalo.}
{104}{}{U mì nic novıho a co u tebe?}
{105}{}{Nemìl bys stát na svım místì, vojáku? Tady se nemùeš jen tak poflakovat.}
{106}{}{Kde máš uniformu?}
{107}{}{Mìl by ses nahlásit u seri a pøevlíknout se.}
{108}{}{Pìknì riskuješ, kdy tu takhle pobíháš bez uniformy. Radìji si ji vyfasuj.}
{109}{}{Kdo k èertu jste? Poplach! Vetøelci!}
{110}{}{Byli jsme napadeni! Poplach!}
{111}{}{Vetøelci! Spuste alarm!}
{112}{}{Poplach! Chraòte základnu!}
{113}{}{Zabezpeète všechny stanice! Máme tu poplach!}
{114}{}{Poplach! Èervenı kód!}
{115}{}{Chcípneš!}
{116}{}{Enkláva bude vládnou svìtu!}
{117}{}{Ty zhebneš, Enkláva bude ít dál!}
{200}{}{...kretén...}
{201}{}{...jo, RADŠI odsud zmiz...}
{202}{}{...sráè jeden...}
{203}{}{...ano, pane! No jo kurva, pane!...}
{300}{}{Ani se nehni. Co si myslíš, e dìláš s tou helikoptérou? Co vím, tak na nìkolik dalších dnù nejsou naplánovanı ádnı lety.}
{301}{}{Huba buba?}
{302}{}{Já vím.}
{303}{}{Omlouvám se. Jenom se tak dívám. Radìji pùjdu.}
{304}{}{Nastala zmìna plánu. Beru si tuhle helikoptéru.}
{310}{}{Coe? Aha, chápu. Podívej, nesahej na to. Jasnı? Dotkni se toho ještì jednou a chcípneš.}
{311}{}{[Mile se usmát a pak zaútoèit]}
{312}{}{[Odejít]}
{315}{}{Do prdele, vypadá to, e tu máme vetøelce. Èervenı kód! Opakuju, èervenı kód!}
{316}{}{To zní jako dobrı nápad. Dotkni se toho letadla ještì jednou a schytáš jednu do hlavy.}
{320}{}{Správnì. A proto...}
{321}{}{Právì odcházím. Omlouvám se za obtìování.}
{322}{}{Musím do hlavní základny doruèit velmi dùleitou zprávu.}
{323}{}{Fakt jo? A co je v té zprávì?}
{324}{}{To je pøísnì tajné. Nemùu ti to øíct.}
{325}{}{Øeknu ti to, ale je naprosto nezbytné, abys tuto informaci nešíøil dál, protoe by mohla nastat ohromná panika. Víš, zjistilo se, e jedna z posledních dodávek otrokù je nakaena neznámım a velice smrtelnım kmenem viru. *Musím* se okamitì dostat do základny, jinak mùeme zemøít. A teï pøestaò plıtvat mım drahocennım èasem. Záleí na kadé minutì.}
{326}{}{Jasnì, vìøím ti. Vypadá to, e tu máme vetøelce...}
{327}{}{Sakra! No to je jedno. Mnì tady stejnì nikdo neøekne ani hovno. Tak jdi.}
{328}{}{Páni, to zní blbì. Dobøe, tak jdi. Nechci bıt za takovej prùser zodpovìdnej. Jo, a neboj se, nikomu nic neøeknu.}
{329}{}{[KONEC]}
