{100}{}{Vidíš stráž.}
{101}{}{Vidíš stráž v energo zbroji.}
{102}{}{Vidíš osobu v energo zbroji neobvyklého vzhledu. Na prsou má znak, který nepoznáváš.}
{103}{}{Po dobu mé služby se nic zvláštního nestalo.}
{104}{}{U mě nic novýho a co u tebe?}
{105}{}{Neměl bys stát na svým místě, vojáku? Tady se nemůžeš jen tak poflakovat.}
{106}{}{Kde máš uniformu?}
{107}{}{Měl by ses nahlásit u serži a převlíknout se.}
{108}{}{Pěkně riskuješ, když tu takhle pobíháš bez uniformy. Raději si ji vyfasuj.}
{109}{}{Kdo k čertu jste? Poplach! Vetřelci!}
{110}{}{Byli jsme napadeni! Poplach!}
{111}{}{Vetřelci! Spusťte alarm!}
{112}{}{Poplach! Chraňte základnu!}
{113}{}{Zabezpečte všechny stanice! Máme tu poplach!}
{114}{}{Poplach! Červený kód!}
{115}{}{Chcípneš!}
{116}{}{Enkláva bude vládnou světu!}
{117}{}{Ty zhebneš, Enkláva bude žít dál!}
{200}{}{...kretén...}
{201}{}{...jo, RADŠI odsud zmiz...}
{202}{}{...sráč jeden...}
{203}{}{...ano, pane! No jo kurva, pane!...}
{300}{}{Ani se nehni. Co si myslíš, že děláš s tou helikoptérou? Co vím, tak na několik dalších dnů nejsou naplánovaný žádný lety.}
{301}{}{Huba buba?}
{302}{}{Já vím.}
{303}{}{Omlouvám se. Jenom se tak dívám. Raději půjdu.}
{304}{}{Nastala změna plánu. Beru si tuhle helikoptéru.}
{310}{}{Cože? Aha, chápu. Podívej, nesahej na to. Jasný? Dotkni se toho ještě jednou a chcípneš.}
{311}{}{[Mile se usmát a pak zaútočit]}
{312}{}{[Odejít]}
{315}{}{Do prdele, vypadá to, že tu máme vetřelce. Červený kód! Opakuju, červený kód!}
{316}{}{To zní jako dobrý nápad. Dotkni se toho letadla ještě jednou a schytáš jednu do hlavy.}
{320}{}{Správně. A proto...}
{321}{}{Právě odcházím. Omlouvám se za obtěžování.}
{322}{}{Musím do hlavní základny doručit velmi důležitou zprávu.}
{323}{}{Fakt jo? A co je v té zprávě?}
{324}{}{To je přísně tajné. Nemůžu ti to říct.}
{325}{}{Řeknu ti to, ale je naprosto nezbytné, abys tuto informaci nešířil dál, protože by mohla nastat ohromná panika. Víš, zjistilo se, že jedna z posledních dodávek otroků je nakažena neznámým a velice smrtelným kmenem viru. *Musím* se okamžitě dostat do základny, jinak můžeme zemřít. A teď přestaň plýtvat mým drahocenným časem. Záleží na každé minutě.}
{326}{}{Jasně, věřím ti. Vypadá to, že tu máme vetřelce...}
{327}{}{Sakra! No to je jedno. Mně tady stejně nikdo neřekne ani hovno. Tak jdi.}
{328}{}{Páni, to zní blbě. Dobře, tak jdi. Nechci být za takovej průser zodpovědnej. Jo, a neboj se, nikomu nic neřeknu.}
{329}{}{[KONEC]}
