{100}{}{Vidíš osobu v energo zbroji.}
{101}{}{Vidíš velitele základny Navarro.}
{102}{}{Vidíš osobu v energo zbroji neobvyklého vzhledu. Na prsou má znak, kterı nepoznáváš.}
{103}{}{Kdo k èertu jste? Poplach! Vetøelci pronikli na základnu!}
{104}{}{Nemám èas tlachat s pìšáky. Odchod.}
{105}{}{Èas zemøít.}
{106}{}{Dobøe.}
{107}{}{U jsem øekl, e na tebe nemám èas. Vypadni z mojí kanceláøe a nevracej se, dokud tì nezavolám. Odchod!}
{108}{}{Neuposlechnutí pøímého rozkazu nadøízeného dùstojníka je povaováno za zradu. Na váleènı soud nemám èas, take to vyøídím sám. Stráe! Zabijte toho idiota!}
{109}{}{Dobøe.}
{110}{}{Polib si!}
{111}{}{FOB je v támhleté skøíòce. A mì vedoucí kontaktuje, jakmile bude zabezpeèen. Odchod!}
{112}{}{Ano, pane!}
{113}{}{Pohni s tím, vojáku. Nemám na to celı den.}
{114}{}{Ano, pane!}
{115}{}{Nech moji skøíòku na pokoji, nebo ti ukáu co je to opravdová bolest.}
{116}{}{Ano, pane!}
{117}{}{Na základnì je vyhlášen poplach a já vás nepoznávám. Vaše doklady, vojáku.}
{118}{}{Jaké doklady?}
{119}{}{Ty vyhulit mi!}
{120}{}{Zdá se, e je nemám u sebe...}
{121}{}{Doklady? Mám vaše doklady pøímo tady!}
{122}{}{Špatná odpovìï, èerve. Doklady bys mìl mít vdy u sebe. To bys mìl vìdìt!}
{123}{}{Jdi do prdele.}
{124}{}{Nech moji skøíòku na pokoji, nebo ti ukáu co je to opravdová bolest.}
{125}{}{Èas zemøít.}
