{100}{}{Vidíš osobu v energo zbroji.}
{101}{}{Vidíš velitele základny Navarro.}
{102}{}{Vidíš osobu v energo zbroji neobvyklého vzhledu. Na prsou má znak, který nepoznáváš.}
{103}{}{Kdo k čertu jste? Poplach! Vetřelci pronikli na základnu!}
{104}{}{Nemám čas tlachat s pěšáky. Odchod.}
{105}{}{Čas zemřít.}
{106}{}{Dobře.}
{107}{}{Už jsem řekl, že na tebe nemám čas. Vypadni z mojí kanceláře a nevracej se, dokud tě nezavolám. Odchod!}
{108}{}{Neuposlechnutí přímého rozkazu nadřízeného důstojníka je považováno za zradu. Na válečný soud nemám čas, takže to vyřídím sám. Stráže! Zabijte toho idiota!}
{109}{}{Dobře.}
{110}{}{Polib si!}
{111}{}{FOB je v támhleté skříňce. Ať mě vedoucí kontaktuje, jakmile bude zabezpečen. Odchod!}
{112}{}{Ano, pane!}
{113}{}{Pohni s tím, vojáku. Nemám na to celý den.}
{114}{}{Ano, pane!}
{115}{}{Nech moji skříňku na pokoji, nebo ti ukážu co je to opravdová bolest.}
{116}{}{Ano, pane!}
{117}{}{Na základně je vyhlášen poplach a já vás nepoznávám. Vaše doklady, vojáku.}
{118}{}{Jaké doklady?}
{119}{}{Ty vyhulit mi!}
{120}{}{Zdá se, že je nemám u sebe...}
{121}{}{Doklady? Mám vaše doklady přímo tady!}
{122}{}{Špatná odpověď, červe. Doklady bys měl mít vždy u sebe. To bys měl vědět!}
{123}{}{Jdi do prdele.}
{124}{}{Nech moji skříňku na pokoji, nebo ti ukážu co je to opravdová bolest.}
{125}{}{Čas zemřít.}
