{100}{}{Vidíš hubeného oplzle vyhlížejícího muže.}
{150}{}{Vidíš Flicka, který podrobuje svá varlata dùkladnému podrbání.}
{151}{}{Vidíš špinavého chlápka s nepøíjemným tikem v oblièeji.}
{200}{}{Jdi do nìkam, cretino.}
{201}{}{Hej, trdlo! Si, ty. Vypadni ocaï.}
{202}{}{Jseš stupido nebo co?}
{203}{}{Co máš za probléma, no?}
{204}{}{Vypadni ocaï.}
{220}{}{Èágo, já jsem Flick. Co kurva chceš, no?}
{221}{}{Tag co bude? Zdržuješ mì.}
{222}{}{Co to je za praštìný pøízvuk, Flicku?}
{223}{}{Co tu k èertu dìláš?}
{224}{}{Hledám Vault. Jo a taky jednoho obchodníka jménem Vic. Nevíš, kde by mohli být?}
{225}{}{Chci s tebou obchodovat.}
{240}{}{Bude to fšechno, kámo?}
{241}{}{Vlastnì se chci ještì podívat na tvoje zboží, jestli mùžu.}
{242}{}{Vlastnì se chci na nìco zeptat.}
{243}{}{That did it. See you around, Flick.}
{260}{}{Jsem zasranej živitel, co myslíš? Jsem nìco jako dobrej Samuraitán.}
{261}{}{Co prosím?}
{262}{}{Jo, eh, no... chci se ještì na nìco zeptat.}
{263}{}{Eh, aha. Dobøe. Sbohem, Flicku.}
{280}{}{Starám se o malý paisano.}
{281}{}{Staráš se o malé piána?}
{290}{}{Pai-san-o, však víš, dìcka. Moje dìcka.}
{291}{}{Tvoje dìti?}
{292}{}{Nestojím o hodiny hudby pro dìti. Chci se ještì na nìco zeptat.}
{300}{}{Jo, oni pro mì pracujou. Nosí mi vìci. Malý vìci, víš.}
{301}{}{Eh, ne.}
{302}{}{Aha, dobøe. Chci se ještì na nìco zeptat.}
{303}{}{Aha, chápu. No, nebudu rušit tvùj, eh, styl. Sbohem.}
{315}{}{They bring me stuff what they find. Little, little things. Stuff no one ain't usin' no more. In return, I takes care of 'em.}
{316}{}{To zní jako dobrá dohoda.}
{325}{}{(Flick pokrèí rameny) Vyhovuje mi to.}
{326}{}{Chci se ještì na nìco zeptat.}
{327}{}{Urèitì ti pøinesli nìjaké zajímavé vìci. Ukaž mi, co máš.}
{328}{}{Jenom se dívám. Sbohem, Flicku.}
{340}{}{O èem to mluvíš? Myslíš, že jsem nìjakej posranej blbej pirla? Nìjakej debilní filio di puttana? Myslíš, že jsem nìjakej šašek? Že tì mám jako bavit nebo co?}
{341}{}{Eh, ne. Promiò, jen mì to prostì zajímalo. Chci se ještì na nìco zeptat.}
{342}{}{Jo, pøesnì o tom mluvím, ty sráèi. A nic mì nepobaví tak jako tvoje bolestivá smrt.}
{343}{}{No, když tì to tak strašnì urazilo, tak odejdu.}
{360}{}{Vault, jo? Možná o tom nìco ví Máma, páè já vùbec. Ale ten chlapík Vic, toho znám. Metzger má toho porca pistola.}
{361}{}{Vic? Není náhodou s tebou? Ty biota. Ale Mámu, tu znám.}
{362}{}{Kdo je Metzger?}
{363}{}{Kdo je Máma?}
{364}{}{Díky. Chci se ještì na nìco zeptat.}
{365}{}{Díky, to bude asi všechno. Sbohem.}
{380}{}{Máma provozuje jídelnu ve východní èásti mìsta. Hned za høbitovem. Je to hezký místo, vaøí tam dobrý pasta, Mama mia.}
{381}{}{Díky. A co ten chlápek Metzger, co má Vica?}
{382}{}{Díky. Chci se ještì na nìco zeptat.}
{383}{}{Díky, to bude asi všechno. Sbohem.}
{400}{}{Metzger, ten stronzo, je mrtvej. Nevím, co se stalo s Vicem.}
{401}{}{Ten Metzger, to je fakt rompiballe. Provozuje Cech otrokáøù. Na východì mìsta, severnì od Mámy. Každopádnì má Vica, to vím.}
{402}{}{Díky, a co teï nìco o Mámì?}
{403}{}{Díky. Chci se ještì na nìco zeptat.}
{404}{}{Díky, to bude asi všechno. Sbohem.}
