{100}{}{Vidíš hubeného oplzle vyhlížejícího muže.}
{150}{}{Vidíš Flicka, který podrobuje svá varlata důkladnému podrbání.}
{151}{}{Vidíš špinavého chlápka s nepříjemným tikem v obličeji.}
{200}{}{Jdi do někam, cretino.}
{201}{}{Hej, trdlo! Si, ty. Vypadni ocaď.}
{202}{}{Jseš stupido nebo co?}
{203}{}{Co máš za probléma, no?}
{204}{}{Vypadni ocaď.}
{220}{}{Čágo, já jsem Flick. Co kurva chceš, no?}
{221}{}{Tag co bude? Zdržuješ mě.}
{222}{}{Co to je za praštěný přízvuk, Flicku?}
{223}{}{Co tu k čertu děláš?}
{224}{}{Hledám Vault. Jo a taky jednoho obchodníka jménem Vic. Nevíš, kde by mohli být?}
{225}{}{Chci s tebou obchodovat.}
{240}{}{Bude to fšechno, kámo?}
{241}{}{Vlastně se chci ještě podívat na tvoje zboží, jestli můžu.}
{242}{}{Vlastně se chci na něco zeptat.}
{243}{}{That did it. See you around, Flick.}
{260}{}{Jsem zasranej živitel, co myslíš? Jsem něco jako dobrej Samuraitán.}
{261}{}{Co prosím?}
{262}{}{Jo, eh, no... chci se ještě na něco zeptat.}
{263}{}{Eh, aha. Dobře. Sbohem, Flicku.}
{280}{}{Starám se o malý paisano.}
{281}{}{Staráš se o malé piána?}
{290}{}{Pai-san-o, však víš, děcka. Moje děcka.}
{291}{}{Tvoje děti?}
{292}{}{Nestojím o hodiny hudby pro děti. Chci se ještě na něco zeptat.}
{300}{}{Jo, oni pro mě pracujou. Nosí mi věci. Malý věci, víš.}
{301}{}{Eh, ne.}
{302}{}{Aha, dobře. Chci se ještě na něco zeptat.}
{303}{}{Aha, chápu. No, nebudu rušit tvůj, eh, styl. Sbohem.}
{315}{}{Nosej mi věci, kerý najdou. Malý věci. Věci, kerý už nikdo nepoužívá. Na oplátku se starám já o ně.}
{316}{}{To zní jako dobrá dohoda.}
{325}{}{(Flick pokrčí rameny) Vyhovuje mi to.}
{326}{}{Chci se ještě na něco zeptat.}
{327}{}{Určitě ti přinesli nějaké zajímavé věci. Ukaž mi, co máš.}
{328}{}{Jenom se dívám. Sbohem, Flicku.}
{340}{}{O čem to mluvíš? Myslíš, že jsem nějakej posranej blbej pirla? Nějakej debilní filio di puttana? Myslíš, že jsem nějakej šašek? Že tě mám jako bavit nebo co?}
{341}{}{Eh, ne. Promiň, jen mě to prostě zajímalo. Chci se ještě na něco zeptat.}
{342}{}{Jo, přesně o tom mluvím, ty sráči. A nic mě nepobaví tak jako tvoje bolestivá smrt.}
{343}{}{No, když tě to tak strašně urazilo, tak odejdu.}
{360}{}{Vault, jo? Možná o tom něco ví Máma, páč já vůbec. Ale ten chlapík Vic, toho znám. Metzger má toho porca pistola.}
{361}{}{Vic? Není náhodou s tebou? Ty biota. Ale Mámu, tu znám.}
{362}{}{Kdo je Metzger?}
{363}{}{Kdo je Máma?}
{364}{}{Díky. Chci se ještě na něco zeptat.}
{365}{}{Díky, to bude asi všechno. Sbohem.}
{380}{}{Máma provozuje jídelnu ve východní části města. Hned za hřbitovem. Je to hezký místo, vaří tam dobrý pasta, Mama mia.}
{381}{}{Díky. A co ten chlápek Metzger, co má Vica?}
{382}{}{Díky. Chci se ještě na něco zeptat.}
{383}{}{Díky, to bude asi všechno. Sbohem.}
{400}{}{Metzger, ten stronzo, je mrtvej. Nevím, co se stalo s Vicem.}
{401}{}{Ten Metzger, to je fakt rompiballe. Provozuje Cech otrokářů. Na východě města, severně od Mámy. Každopádně má Vica, to vím.}
{402}{}{Díky, a co teď něco o Mámě?}
{403}{}{Díky. Chci se ještě na něco zeptat.}
{404}{}{Díky, to bude asi všechno. Sbohem.}
