{100}{}{Vidíš přátelsky vypadající starší ženu.}
{150}{}{Vidíš Mámu. Právě vaří a uklízí.}
{151}{}{Vidíš statnou starší ženu s veselým úsměvem na tváři.}
{200}{}{Zdravím, já jsem Máma. Ještě jsem tě tu nikdy neviděla.}
{201}{}{Zdravím. Co pro tebe může Máma udělat?}
{202}{}{Já }
{203}{}{Mmmm. Dobže? Pápá Máma.}
{220}{}{Už se ti podařilo sníst půlku mých zásob. Proč si nenajdeš nějaké jiné místo na poflakování? Už se ti toho podařilo pro dnešek sníst dost.}
{221}{}{No, }
{222}{}{ opravdu vypadáš, že jsi drobet zmatený. Nesnáším, když nějaký tvor trpí. Nechceš něco k jídlu?}
{223}{}{Já plný. Máma mít jídlo mňam. Ahoj Máma.}
{224}{}{Já platit?}
{225}{}{Já jít. Ahoj Mámo.}
{240}{}{Tak dobře. Co tam máš? (Máma se natáhne pro tvoji peněženku.)}
{241}{}{Mámo? [Zvednout svoji peněženku]}
{242}{}{Ne! Já jít. Ahoj Máma.}
{250}{}{Ne, ani ne. Promiň. Máme jenom krysí koláč, krysí sekanou a špagety.}
{251}{}{Takže co to bude tentokrát?}
{252}{}{Eh, můžu dostat něco, kde není tolik krys?}
{253}{}{Myslím, že si dám krysí sekanou.}
{254}{}{Myslím, že si dám krysí koláč.}
{270}{}{Můžu ti dát špagety. V nich není tolik krys... jenom v omáčce, jinak ne.}
{271}{}{Tak dobře, myslím, že si dám špagety s krysí omáčkou.}
{280}{}{Hned ti to přinesu. Bude to $10.}
{281}{}{Momentálně nemám dost peněz. Můžu se místo toho na něco zeptat?}
{282}{}{$10 za krysu? Ty ses musela zbláznit. Sakra, vždyť i my si v okolí vesnice účtujeme mnohem víc za pěknou šťavnatou krysu. Dohodnuto.}
{283}{}{Tak dobře. Tady jsou peníze.}
{284}{}{Myslím, že už nemám zájem. Chci se místo toho na něco zeptat.}
{285}{}{Myslím, že se vrátím později. Sbohem.}
{300}{}{Máš docela dobrý apetit. Ráda vidím zdravé strávníky. Bude ti to stačit?}
{301}{}{Ani náhodou, Mámo. Chci nášup.}
{302}{}{Jo, bude. Můžu se tě na něco zeptat, Mámo?}
{303}{}{Teď už jo. Sbohem, Mámo.}
{320}{}{No, nutně potřebuju někoho, aby donesl Smittymu jídlo. Bydlí na západě odtud na smetišti. Uděláš to pro mě? Dám ti za to jídlo zdarma.}
{321}{}{Jistě, žádný problém.}
{322}{}{Rozmyslím si to. Mezitím se tě chci na něco zeptat.}
{323}{}{Eh, promiň, Mámo. Nemůžu. Sbohem.}
{340}{}{Máš štěstí. Máme dušené radškorpiony.}
{341}{}{Máme dušeného prasečího potkana.}
{342}{}{Podáváme spařené radškorpioní ocásky potřené máslem.}
{343}{}{Zelňačka je to jediné, co teď mám.}
{344}{}{Čerstvé brahmíní hranolky!}
{345}{}{Už se to nese, horký geckoní koláč.}
{346}{}{Stejk z brahmíního boku.}
{347}{}{Pěkně vypasenýho krtčího potkana.}
{348}{}{Osmaženýho floatera.}
{349}{}{Hovězí panenku.}
{350}{}{Medailonky z grilovaného geckona.}
{351}{}{Česnekem špikovaného mantise na víně.}
{352}{}{Rolka plněná kousky krtčího potkana.}
{353}{}{Pečené maso z brahmíny.}
{354}{}{Radškorpion v těstíčku.}
{355}{}{Je to bašta!}
{356}{}{Eh, nejsem si tak úplně jistá, ale chutná to jako kuře.}
{357}{}{Kotleta z kentaura, moje specialita.}
{358}{}{To je překvapení.}
{359}{}{Nemůžu prozradit své tajné recepty!}
{360}{}{Opravdu?}
{375}{}{Tady máš. Vypadáš docela hladově. (Máma ti podá velký kouřící talíř lahodně vonícího jídla.)}
{376}{}{Dííííky, Mámo.}
{385}{}{Tady máš. Jsem si jistá, že ti to bude chutnat.}
{386}{}{Mmm, ňam ňam. Ahoj, Máma.}
{395}{}{Díky moc. Udělala bych to sama, ale nevím o nikom, kdo by mi to tu pohlídal, zatímco bych byla pryč. Tady je jídlo pro Smittyho. Jsem si jistá, že kdybych mu ho nedonesla, tak by zapomněl jíst.}
{396}{}{Já mu to donesu.}
{405}{}{Jsem opravdu zklamaná. Chudák Smitty si musel přijít pro své vlastní jídlo. Co ještě chceš?}
{406}{}{Zdravím, jmenuju se Máma a provozuju tenhle podnik. Mám taky nejlepší jídlo severně od New Rena.}
{407}{}{O čem chceš s Mámou mluvit?}
{408}{}{Nejsi moje máma.}
{409}{}{Už jsi někdy slyšela o Vaultu nebo o někom jménem Vic?}
{410}{}{Co se tady dá ve městě podniknout?}
{411}{}{Co tady máš k jídlu?}
{425}{}{Já vím, ale každý mi tak říká. Vlastně se i k lidem chovám, jako by to byly moje děti... tedy pokud dodržují moje pravidla.}
{426}{}{Pravidla?}
{435}{}{Přesně tak. Žádné okrádání, žádné klení a žádné rvačky... ne v mém podniku. Pač když z toho něco porušíš, půjdeš pryč. Mám ráda klid.}
{436}{}{Aha. Chci se ještě na něco zeptat.}
{437}{}{To dává smysl. Uvidíme se později, Mámo.}
{445}{}{No, na východ odtud a pak ještě trochu na sever leží Vault City. A Vic, hmm, nech mě přemýšlet.}
{446}{}{Doufám, že víš, kde je Vic. Je to obchodník.}
{447}{}{Díky, ale to bude asi všechno. Nashle, Mámo.}
{455}{}{Obchodník Vic? Už si vzpomínám. Ano, myslím, že ho z nějakého důvodu drží Metzger.}
{456}{}{Kdo je Metzger a kde ho najdu?}
{457}{}{To je skvělé, Mámo. Díky.}
{465}{}{Metzger je šéf místního Cechu otrokářů. Má pod zámkem nejrůznější lidi. Je to přímo nad touhle ulicí.}
{466}{}{Metzger býval šéfem místního Cechu otrokářů. Měl pod zámkem nejrůznější lidi. Ale teď nevím... slyšela jsem, že ho někdo zabil.}
{467}{}{Díky za informaci. Chci se zeptat na něco jiného, Mámo.}
{468}{}{Potřebuju si ještě něco zařídit. Díky, Mámo.}
{475}{}{Běž a dones Smittymu to jídlo.}
{476}{}{Nepomůžu ti, dokud nedodržíš slovo.}
{477}{}{Pospěš si.}
{478}{}{Dones Smittymu to jídlo. A pospěš si.}
{479}{}{Přestaň se flákat a dones Smittymu to jídlo.}
{485}{}{Dobrá práce. Určitě ti muselo vyhládnout.
 Za odměnu tu pro tebe mám úplnou lahůdku. Výběr toho nejlepšího jídla,
 co tu mám, jen pro tebe.}
{486}{}{To zní skvěle! Sem s tím!}
{487}{}{Panejo, Mámo. Teď nemůžu jíst, ale stejně díky. Sbohem.}
{500}{}{Hmm, moc o tom nevím. Nejspíš si jen někdo dělá srandu,
 nic víc.}
{501}{}{Byl odjakživa strašidelný?}
{502}{}{Bydlí v tom domě někdo?}
{503}{}{Souhlasím. Nashle.}
{520}{}{Začalo to asi před dvěma lety. Slyšela jsem něco o sténání a duchovi a tak.
 Sama tomu nevěřím.}
{521}{}{Dva roky, jo? Nikdo tam v té době nebydlel?}
{522}{}{Já taky ne. Díky.}
{540}{}{Jeden z místních chlapců tam před pár lety spával. Možná něco ví.}
{541}{}{Kdo?}
{542}{}{Pravděpodobně ne. Nashle.}
{560}{}{Vždycky přišel a snažil se dát věci do zástavy. Většinou šperky.
 Vzpomínám si na malý zlatý přívěšek, který si nechal pro sebe.}
{561}{}{Nevzpomínáš si na jeho jméno?}
{562}{}{Přívěšek? Zvláštní. Kdo to byl?}
{563}{}{Chci se ještě na něco zeptat.}
{564}{}{Díky, nashle.}
{580}{}{Nejsem si jistá. Myslím, že to byl Joseph, Joel nebo tak nějak. Je mu teď asi 19...
 opravdová škoda. Mám dojem, že se přidal k nějakým místním hrdlořezům.}
{581}{}{Díky. Mám na tebe ještě jednu otázku.}
{582}{}{Díky, nashle.}
{600}{}{Co víš o tom strašidelném domě?}
