{100}{}{You see a chem reliant.}
{101}{}{Vidíš Peteyho.}
{150}{}{This here is a poor chem reliant.}
{151}{}{Tady Petey by potøeboval píchnout.}
{152}{}{[MLUVIT]}
{155}{}{[kašlání] Nemáš nìjaký drobný pro Peteyho?}
{156}{}{Jistì, tady máš.}
{157}{}{Ne, vypadni ode mì.}
{158}{}{Týpí?}
{159}{}{Jseš na tom hùø než já [kašlání]. Každopádnì díky.}
{160}{}{Promiò, nashle.}
{161}{}{No jo, není zaè, eh, jo.}
{162}{}{Možná pøíštì. Každopádnì díky [kašlání]}
{163}{}{[KONEC]}
{164}{}{Diky moc. [kašlání] Opravdu, opravdu moc.}
{165}{}{Není zaè.}
{166}{}{Jo jo.}
{167}{}{Pane, [kašlání] nechcete pomoct ubožákovi, který je na dnì?}
{168}{}{Tady máš $5.}
{169}{}{Dnes ne.}
{170}{}{Sežeò si práci.}
{171}{}{Paní, buïte tak laskavá a pomozte prosím [kašlání] hladovìjícímu chudákovi, kterej je [kašlání] tak nemocnej, že nemùže pracovat.}
{172}{}{Ty chudinko, tady máš $5.}
{173}{}{Žebrákùm peníze zásadnì nedávám.}
{174}{}{Ne.}
{200}{}{Haló, pane, nemáte nìjaký peníze?}
{201}{}{Nemáte nìjaký drobný, laskavý pane?}
{202}{}{Haló, mùžete mi vypomoct pár doláèema?}
{203}{}{Do you think you can help me out with a coupla dollars?}
{204}{}{Mùžeš mi pùjèit pár doláèù?}
{205}{}{Nemáte nìjaký drobný, laskavá paní?}
{206}{}{Haló, paní, nemáte nìjaký peníze?}
{220}{}{Prosím, pomozte mi, pane.}
{221}{}{Áááá, to bolí.}
{222}{}{Potøebuju pomoct. Strašnì to bolí.}
{223}{}{Paní, mùžete zavolat pomoc?}
{225}{}{Strašnì si toho vážím.}
{226}{}{Hej, co si myslíš, že dìláš?}
{230}{}{Cítím se tak dobøe.}
{231}{}{Ehhh...}
{232}{}{[hihòání]}
{233}{}{Hej...}
{300}{}{Ahhh, someone fucking killed Tubby?}
{301}{}{Co se kurva stalo Tubbymu?}
{302}{}{Oh shit, Tubby's...}
{303}{}{Áááá...}
{304}{}{Stejnì jsem toho kreténa nemìl rád.}
{305}{}{Flick's dead? Crap.}
{306}{}{Co se stalo Flickovi?}
{307}{}{Flick...}
{310}{}{Hey Tubby, I, Uhhh, need some help here.}
{311}{}{HEJ, TUBBY!}
{312}{}{Ahoj.}
{313}{}{HEJ!}
{314}{}{Hey Flick, I, Uhhh, need some help here.}
{315}{}{HEJ, FLICKU!}
{320}{}{Hej, Tubby, mùžeš mi nìco sehnat? Mám prachy.}
{321}{}{Ehhh, Tubby, mám nìjaký prachy.}
{322}{}{Ehhh...}
{323}{}{Potøebuju dávku.}
{324}{}{Hey, Flicku, mùžeš mi nìco sehnat? Mám prachy.}
{325}{}{Ehhh, Flicku, mám nìjaký prachy.}
{330}{}{Ehhh... ještì jednou díky, Tubby.}
{331}{}{Jseš kámoš, Tubby.}
{332}{}{Pøísahám, že s tím od zejtra pøestanu.}
{333}{}{Jseš kámoš.}
{334}{}{Ehhh... ještì jednou díky, Flicku.}
{335}{}{Jseš kámoš, Flicku.}
