{100}{}{Vidíš muže v kovové zbroji.}
{101}{}{Vidíš Kagu v kovové zbroji.}
{102}{}{Jo, je to Kaga, ne-až-tak-velký. Má kovovou zbroj a chce tì zabít.}
{103}{}{Zase ty!}
{104}{}{Už mì ta neustálá setkání zaèínají unavovat.}
{105}{}{Vyvolený - hmm!}
{106}{}{Skonèeme to.}
{107}{}{Bude tì mrzet, že jsi kdy slyšel jméno Kaga!}
{108}{}{Mé schopnosti doznaly velkého zlepšení od doby, co jsme se naposled setkali.}
{109}{}{Stává se z toho zlozvyk.}
{110}{}{Kaga musí ještì trochu trénovat.}
{111}{}{Kaga se vrátí.}
