{100}{}{Vidíš muže v kožené zbroji.}
{101}{}{Vidíš Kagu v kovové zbroji.}
{102}{}{Má na sobì koženou zbroj a má protivný zlozvyk mluvit o sobì v tøetí osobì.}
{103}{}{To bude naposledy, kdy tì Kaga potkává.}
{104}{}{After Kaga kill yous, he will burn Arroyo to the ground.}
{105}{}{Pocítíš Kagùv hnìv!}
{106}{}{Jsem velký Kaga!}
{107}{}{Pøed Kagou se musí všichni tøást.}
{108}{}{Kaga si z tvé hlavy udìlá trofej.}
{109}{}{Vzdej se a tvoje smrt bude rychlá.}
{110}{}{Kaga se vrátí!}
{111}{}{Nemùžeš zabít velkého Kagu!}
{112}{}{Máš štìstí, že má Kaga nìco jiného na práci.}
{113}{}{Kaga se s tebou ještì setká.}
