{100}{}{Vidíš polonahého muže.}
{101}{}{Vidíš Kagu v kovové zbroji.}
{103}{}{Má na sobì kalhoty a vypadá, jako by pocházel z nìjakého kmene.}
{104}{}{Já jsem mìl být Vyvoleným!}
{105}{}{Jak se mohlo Arroyo opovážit vyhnat mì z kmene.}
{106}{}{Vykonám na tobì svou pomstu!}
{107}{}{Kaga tì pošle na onen svìt.}
{108}{}{Ještì se uvidíme!}
{109}{}{Ještì nikdy jsem nebyl poražen!}
{110}{}{Udìlám vše pro to, abych tì znièil.}
