{100}{}{Vidíš mue v kevlarové zbroji.}
{101}{}{Vidíš Kagu v kevlarové zbroji.}
{102}{}{Má kevlarovou zbroj a zdá se, e má i docela slušné zbranì.}
{103}{}{Tentokrát jsem na tebe pøipraven.}
{104}{}{Vyvolenı se nikdy do Arroya nevrátí!}
{105}{}{Kaga tì rozdrtí!}
{106}{}{Kaga se nikoho nebojí!}
{107}{}{Stùj klidnì, a mùe Kaga poøádnì zamíøit.}
{108}{}{Ještì se uvidíme!}
{109}{}{Nevidíš Kagu naposled.}
{110}{}{Kaga nutnì potøebuje víc trénovat.}
