{100}{}{Vidíš pocestného.}
{101}{}{Stůj, bratře pocestný!}
{102}{}{Potřebuju ukázat cestu. Pomůžeš mi?}
{103}{}{Kam máš namířeno?}
{104}{}{Co děláš?}
{105}{}{Eh.}
{106}{}{No... nevím. Jsem tu docela nová a byla jsem jen na následujících místech.}
{107}{}{New Reno.}
{108}{}{Vault City.}
{109}{}{Redding.}
{110}{}{The Den.}
{111}{}{San Francisco.}
{112}{}{New California Republic.}
{113}{}{Nějaký opuštěný důl.}
{114}{}{Ne, tam už jsem byl. Každopádně díky.}
{115}{}{New Reno... to je super místo. Sex, drogy a hazard. Co víc si člověk může přát?
 Hned ti ukážu, kde to je.}
{116}{}{Díky.}
{117}{}{Vault City... to je město hlupáků. Naroste ti extra prst a hned se na tebe dívají jako na nějakou zrůdu.
 Nikdy jsem tam nebyla, ale vím, kde to je.}
{118}{}{Díky.}
{119}{}{Redding... moc toho o tomhle městě nevím. Snad jenom to, že je to staré hornické město. Rozprostírá se na severu.
 Je to taková malá tečka uprostřed těch nejkrutějších hor, které jsi kdy viděl.}
{120}{}{Díky.}
{121}{}{Být tebou, tak se držím dál od Denu. Je to magnet na všechen póvl v okolí. Ukážu ti,
 kde to je, ale nedoporučuji ti tam chodit.}
{122}{}{Díky.}
{123}{}{San Francisco. Hm... jediné, co můžu říct, je to, že lidé jsou tam... divní. Nachází se na
 pobřeží.}
{124}{}{Díky.}
{125}{}{New California Republic... tak to je hezké místo. Ráda bych se tam jednou usadila.
 Čistí, příjemní lidé a dobře udržované místo. Na tvé mapě je to přesně tady.}
{126}{}{Díky.}
{127}{}{No, nedávno jsem narazila na osadu u opuštěného dolu. Myslela jsem, že tam tak den dva zůstanu,
 ale pak se objevili vlci a já usoudila, že bude lepší zmizet. Byla to smůla. Zdá se, že horníci odešli ve spěchu.
 Nechali tam po sobě hodně věcí. Nemám v úmyslu se tam vrátit,
 takže ti můžu ukázat, kde to je.}
{128}{}{Díky.}
{129}{}{No... to je jedno. Jednoho dne jsem se rozhodla, že budu cestovat, a tak jsem tady.}
{130}{}{Možná bys mi mohla pomoct. Potřebuju ukázat cestu.}
{131}{}{Co děláš?}
{132}{}{Bylo fajn si s tebou povídat.}
{133}{}{Sem tam dělám příležitostnou práci. Ale většinou jenom cestuju.}
{134}{}{Možná bys mi mohla pomoct. Potřebuju ukázat cestu.}
{135}{}{Kam máš namířeno?}
{136}{}{Bylo fajn si s tebou povídat.}
{137}{}{Tak teď už opravdu budu muset jít. Bylo fajn si s tebou povídat.}
{138}{}{Třeba se ještě někdy potkáme.}
{139}{}{Chci se dostat do nejbližšího města ještě před setměním. Raději vyrazím.}
{140}{}{I'd be going.}
{141}{}{Přepadení!}
{142}{}{Dneska už nemůžeš věřit nikomu.}
{143}{}{Porušil jsi nepsaný zákon pocestného.}
{144}{}{Je čas jít.}
{145}{}{Už jsem tady déle než je zdrávo.}
{146}{}{Musím vyrazit.}
{150}{}{Díky. Potřebuju nasměrovat na nějaká další místa.}
