{100}{}{Vidíš pocestného.}
{101}{}{Stùj, bratøe pocestný!}
{102}{}{Potøebuju ukázat cestu. Pomùžeš mi?}
{103}{}{Kam máš namíøeno?}
{104}{}{Co dìláš?}
{105}{}{Eh.}
{106}{}{No... nevím. Jsem tu docela nová a byla jsem jen na následujících místech.}
{107}{}{New Reno.}
{108}{}{Vault City.}
{109}{}{Redding.}
{110}{}{The Den.}
{111}{}{San Francisco.}
{112}{}{New California Republic.}
{113}{}{Nìjaký opuštìný dùl.}
{114}{}{Ne, tam už jsem byl. Každopádnì díky.}
{115}{}{New Reno... to je super místo. Sex, drogy a hazard. Co víc si èlovìk mùže pøát?
 Hned ti ukážu, kde to je.}
{116}{}{Díky.}
{117}{}{Vault City... to je mìsto hlupákù. Naroste ti extra prst a hned se na tebe dívají jako na nìjakou zrùdu.
 Nikdy jsem tam nebyla, ale vím, kde to je.}
{118}{}{Díky.}
{119}{}{Redding... moc toho o tomhle mìstì nevím. Snad jenom to, že je to staré hornické mìsto. Rozprostírá se na severu.
 Je to taková malá teèka uprostøed tìch nejkrutìjších hor, které jsi kdy vidìl.}
{120}{}{Díky.}
{121}{}{Být tebou, tak se držím dál od Denu. Je to magnet na všechen póvl v okolí. Ukážu ti,
 kde to je, ale nedoporuèuji ti tam chodit.}
{122}{}{Díky.}
{123}{}{San Francisco. Hm... jediné, co mùžu øíct, je to, že lidé jsou tam... divní. Nachází se na
 pobøeží.}
{124}{}{Díky.}
{125}{}{New California Republic... tak to je hezké místo. Ráda bych se tam jednou usadila.
 Èistí, pøíjemní lidé a dobøe udržované místo. Na tvé mapì je to pøesnì tady.}
{126}{}{Díky.}
{127}{}{No, nedávno jsem narazila na osadu u opuštìného dolu. Myslela jsem, že tam tak den dva zùstanu,
 ale pak se objevili vlci a já usoudila, že bude lepší zmizet. Byla to smùla. Zdá se, že horníci odešli ve spìchu.
 Nechali tam po sobì hodnì vìcí. Nemám v úmyslu se tam vrátit,
 takže ti mùžu ukázat, kde to je.}
{128}{}{Díky.}
{129}{}{No... to je jedno. Jednoho dne jsem se rozhodla, že budu cestovat, a tak jsem tady.}
{130}{}{Možná bys mi mohla pomoct. Potøebuju ukázat cestu.}
{131}{}{Co dìláš?}
{132}{}{Bylo fajn si s tebou povídat.}
{133}{}{Sem tam dìlám pøíležitostnou práci. Ale vìtšinou jenom cestuju.}
{134}{}{Možná bys mi mohla pomoct. Potøebuju ukázat cestu.}
{135}{}{Kam máš namíøeno?}
{136}{}{Bylo fajn si s tebou povídat.}
{137}{}{Tak teï už opravdu budu muset jít. Bylo fajn si s tebou povídat.}
{138}{}{Tøeba se ještì nìkdy potkáme.}
{139}{}{Chci se dostat do nejbližšího mìsta ještì pøed setmìním. Radìji vyrazím.}
{140}{}{I'd be going.}
{141}{}{Pøepadení!}
{142}{}{Dneska už nemùžeš vìøit nikomu.}
{143}{}{Porušil jsi nepsaný zákon pocestného.}
{144}{}{Je èas jít.}
{145}{}{Už jsem tady déle než je zdrávo.}
{146}{}{Musím vyrazit.}
{150}{}{Díky. Potøebuju nasmìrovat na nìjaká další místa.}
