{100}{}{Vidíš malého tlustého Shi muže.}
{101}{}{Vidíš Dr. Wong Yi Tze.}
{102}{}{Vidíš malého tlustého Shi muže.}
{103}{}{Mohu vám s něčím pomoci?}
{104}{}{Daghi nu?}
{105}{}{Kdo ty?}
{106}{}{Prý máte něčí slezinu.}
{107}{}{Kdo jsi?}
{108}{}{Co tady děláš?}
{109}{}{Ne, díky. To bude všechno.}
{110}{}{Musím se přiznat, že nehovořím vaší řečí. Zkuste si pohovořit s Kenem Lee, ten rozumí mnoha různým jazykům.}
{111}{}{Aha!}
{112}{}{Jmenuji se Dr. Wong a jsem hlavní vědec tohoto zařízení.}
{113}{}{Další otázky, prosím.}
{114}{}{Dík. Měj se.}
{115}{}{Dohlížím na vědecké pokusy, jenž se zde provádějí. Jsem také zodpovědný za počítačovou síť.}
{116}{}{Co plánujete?}
{117}{}{Jak získám přístup do počítačové sítě?}
{118}{}{Mám další otázky.}
{119}{}{Aha. Nashle.}
{120}{}{Hm, když vám řeknu naše plány, tak je poté bude znát každý. Obávám se, že jsou prozatím tajné.}
{121}{}{Dobře, dobře. Mám další otázky.}
{122}{}{Dík. Měj se.}
{123}{}{A co když vám strčím pistoli pod rypák a přinutím vás mi to říct?}
{124}{}{Hm, někdo se naučí, jak se do ní hacknout a někdo se spřátelí s jedním z mých podřízených. O tom hackování samozřejmě žertuji. Pokud se o to pokusíte, pošlu někoho, aby vás zabil. (Usměje se, aby dokázal, že to nemyslí vážně.)}
{125}{}{Vy byste mě opravdu nechal zabít?}
{126}{}{Takže vám nebude vadit, když hacknu nějaký počítač?}
{127}{}{Mám ještě nějaké otázky.}
{128}{}{O tom nepochybuju. Nashle.}
{129}{}{Pak bych to musel pokládat za hrozbu a varovat vás, že by taková činnost mohla uškodit vašemu zdraví.}
{130}{}{Tak to vyzkoušíme.}
{131}{}{Jenom si dělám legraci. Mám další otázky.}
{132}{}{(Usměje se.) Musíme si chránit vlastní čest, cizinče.}
{133}{}{Eh, jasně. Takže vám nebude vadit, když hacknu nějaký počítač?}
{134}{}{Jasně. Mám další otázky.}
{135}{}{Tak to každopádně. Nashle.}
{136}{}{Pokud se vám podaří přesvědčit mé podřízené, aby to pro vás udělali, tak klidně, ale já to rozhodně neudělám.}
{137}{}{A co když vám strčím pistoli pod rypák?}
{138}{}{Skvělé. No, mám další otázky.}
{139}{}{Hmm. Chápu. No, tak zatím.}
{140}{}{Ach, ano! To vskutku mám. Chci si ji připravit s hráškem a dobrým Chianti.}
{141}{}{Vy ji pořád máte? To je dobře. Chip ji potřebuje vrátit.}
{142}{}{To je lidská slezina, ty prašivej parchante!}
{143}{}{Víte doufám, že se to víno má podávat s játry místo sleziny?}
{144}{}{Víte, to je lidská slezina.}
{145}{}{Kdo je ten Chip? Teď je to moje slezina a budu ji mít k večeři.}
{146}{}{Chip je původní vlastník sleziny. Byl opilý a prodal ji Lao Chouovi.}
{147}{}{Potřebuje ji, aby přežil, víte. Je z jeho těla.}
{148}{}{V tom případě vás kvůli ní nejspíš zabiju.}
{149}{}{Dohoda je dohoda. Nemůže ji dostat zpět. Lituji, ale dohodli jsme se spolu a to, že toho teď Chip lituje, ještě neznamená, že může z té dohody couvnout.}
{150}{}{[Více]}
{151}{}{To je lidská slezina? To mi Lao Chou neřekl!}
{152}{}{Hmm, v tom případě na ní budu místo toho provádět pokusy.}
{153}{}{Řekněte vašemu kamarádovi, aby se pro ni během zítřka stavil a já mu ji rád vrátím zpět. Jenom doufám, že najdete způsob, jak mu ji voperovat včas zpátky.}
{154}{}{Tak dobrá.}
{155}{}{Hehe! Ano, také jsem ten starý film viděl. Počkat... co tím myslíte? Chcete říct, že... ?}
{156}{}{Ano, je to lidská slezina.}
{157}{}{Vlastně mám vůči tomu námitky. Nepodařilo se vám dokázat, že máte dobrý charakter. Vskutku nevím, proč se s vámi vůbec bavím. Nashle.}
{158}{}{[KONEC]}
{159}{}{Ajéje! Stráže! Je tady Lao wai vetřelec!}
{160}{}{Nemáte pro mě jistá schémata?}
{161}{}{Ken Lee mi řekl, ať vám je předám.}
{162}{}{Ano, ale co za to dostanu?}
{163}{}{Ne, ještě ne.}
{164}{}{Promluvte si s Kenem Lee a on projedná vaši budoucnost. Děkuji vám. Díky těmto schématům si budeme moci ověřit některá naše data z testů. Přeji hezký den.}
{165}{}{Vlastně mám na vás další otázky.}
{166}{}{Zatím.}
