{100}{}{Vidíš malého tlustého Shi mue.}
{101}{}{Vidíš Dr. Wong Yi Tze.}
{102}{}{Vidíš malého tlustého Shi mue.}
{103}{}{Mohu vám s nìèím pomoci?}
{104}{}{Daghi nu?}
{105}{}{Kdo ty?}
{106}{}{Prı máte nìèí slezinu.}
{107}{}{Kdo jsi?}
{108}{}{Co tady dìláš?}
{109}{}{Ne, díky. To bude všechno.}
{110}{}{Musím se pøiznat, e nehovoøím vaší øeèí. Zkuste si pohovoøit s Kenem Lee, ten rozumí mnoha rùznım jazykùm.}
{111}{}{Aha!}
{112}{}{Jmenuji se Dr. Wong a jsem hlavní vìdec tohoto zaøízení.}
{113}{}{Další otázky, prosím.}
{114}{}{Dík. Naskle.}
{115}{}{Dohlíím na vìdecké pokusy, jen se zde provádìjí. Jsem také zodpovìdnı za poèítaèovou sí.}
{116}{}{Co plánujete?}
{117}{}{Jak získám pøístup do poèítaèové sítì?}
{118}{}{Mám další otázky.}
{119}{}{Aha. Nashle.}
{120}{}{Hm, kdy vám øeknu naše plány, tak je poté bude znát kadı. Obávám se, e jsou prozatím tajné.}
{121}{}{Dobøe, dobøe. Mám další otázky.}
{122}{}{Dík. Naskle.}
{123}{}{A co kdy vám strèím pistoli pod rypák a pøinutím vás mi to øíct?}
{124}{}{Hm, nìkdo se nauèí, jak se do ní hacknout a nìkdo se spøátelí s jedním z mıch podøízenıch. O tom hackování samozøejmì ertuji. Pokud se o to pokusíte, pošlu nìkoho, aby vás zabil. (Usmìje se, aby dokázal, e to nemyslí vánì.)}
{125}{}{Vy byste mì opravdu nechal zabít?}
{126}{}{Take vám nebude vadit, kdy hacknu nìjakı poèítaè?}
{127}{}{Mám ještì nìjaké otázky.}
{128}{}{O tom nepochybuju. Nashle.}
{129}{}{Pak bych to musel pokládat za hrozbu a varovat vás, e by taková èinnost mohla uškodit vašemu zdraví.}
{130}{}{Tak to vyzkoušíme.}
{131}{}{Jenom si dìlám legraci. Mám další otázky.}
{132}{}{(Usmìje se.) Musíme si chránit vlastní èest, cizinèe.}
{133}{}{Eh, jasnì. Take vám nebude vadit, kdy hacknu nìjakı poèítaè?}
{134}{}{Jasnì. Mám další otázky.}
{135}{}{Tak to kadopádnì. Nashle.}
{136}{}{Pokud se vám podaøí pøesvìdèit mé podøízené, aby to pro vás udìlali, tak klidnì, ale já to rozhodnì neudìlám.}
{137}{}{A co kdy vám strèím pistoli pod rypák?}
{138}{}{Skvìlé. No, mám další otázky.}
{139}{}{Hmm. Chápu. No, tak zatím.}
{140}{}{Ach, ano! To vskutku mám. Chci si ji pøipravit s hráškem a dobrım Chianti.}
{141}{}{Vy ji poøád máte? To je dobøe. Chip ji potøebuje vrátit.}
{142}{}{To je lidská slezina, ty prašivej parchante!}
{143}{}{Víte doufám, e se to víno má podávat s játry místo sleziny?}
{144}{}{Víte, to je lidská slezina.}
{145}{}{Kdo je ten Chip? Teï je to moje slezina a budu ji mít k veèeøi.}
{146}{}{Chip je pùvodní vlastník sleziny. Byl opilı a prodal ji Lao Chouovi.}
{147}{}{Potøebuje ji, aby pøeil, víte. Je z jeho tìla.}
{148}{}{V tom pøípadì vás kvùli ní nejspíš zabiju.}
{149}{}{Dohoda je dohoda. Nemùe ji dostat zpìt. Lituji, ale dohodli jsme se spolu a to, e toho teï Chip lituje, ještì neznamená, e mùe z té dohody couvnout.}
{150}{}{[Více]}
{151}{}{To je lidská slezina? To mi Lao Chou neøekl!}
{152}{}{Hmm, v tom pøípadì na ní budu místo toho provádìt pokusy.}
{153}{}{Øeknìte vašemu kamarádovi, aby se pro ni bìhem zítøka stavil a já mu ji rád vrátím zpìt. Jenom doufám, e najdete zpùsob, jak mu ji voperovat vèas zpátky.}
{154}{}{Tak dobrá.}
{155}{}{Hehe! Ano, také jsem ten starı film vidìl. Poèkat... co tím myslíte? Chcete øíct, e... ?}
{156}{}{Ano, je to lidská slezina.}
{157}{}{Vlastnì mám vùèi tomu námitky. Nepodaøilo se vám dokázat, e máte dobrı charakter. Vskutku nevím, proè se s vámi vùbec bavím. Nashle.}
{158}{}{[KONEC]}
{159}{}{Ajéje! Stráe! Je tady Lao wai vetøelec!}
{160}{}{Nemáte pro mì jistá schémata?}
{161}{}{Ken Lee mi øekl, a vám je pøedám.}
{162}{}{Ano, ale co za to dostanu?}
{163}{}{Ne, ještì ne.}
{164}{}{Promluvte si s Kenem Lee a on projedná vaši budoucnost. Dìkuji vám. Díky tìmto schématùm si budeme moci ovìøit nìkterá naše data z testù. Pøeji hezkı den.}
{165}{}{Vlastnì mám na vás další otázky.}
{166}{}{Zatím.}
