{100}{}{Vidíš muže, který vypadá jako prodavač.}
{101}{}{Vidíš prodavače Lao Choua.}
{102}{}{Vidíš muže v pohodlném pracovním oblečení.}
{103}{}{Zdravím! Vítej v mém obchodě Flying Dragon 8.}
{104}{}{Co pro tebe mohu udělat?}
{105}{}{Da aggle oo!}
{106}{}{Věcičky!}
{107}{}{Kdo jsi?}
{108}{}{Hledám nějaké vybavení.}
{109}{}{Sháním nějaké informace.}
{110}{}{Nashle.}
{111}{}{Chceš něco koupit?}
{112}{}{::kývnout hlavou::}
{113}{}{::zavrtět hlavou::}
{114}{}{Tohle máme na skladě.}
{115}{}{[KONEC]}
{116}{}{No, obávám se, že víc už pro tebe nemůžu udělat. Pěkný den.}
{117}{}{[KONEC]}
{118}{}{Jsem Lao Chou. Provozuju tenhle obchod, Flying Dragon 8. Jsem známý tím, že obchoduju i... s informacemi.}
{119}{}{S jakými informacemi?}
{120}{}{Aha. Potřebuju nějaké vybavení.}
{121}{}{V tomhle městě se stane jen málo věcí, o kterých bych nevěděl. Samozřejmě se také musíš umět správně zeptat, že? Co potřebuješ vědět?}
{122}{}{Hledám nějaké vylepšení pro svoje vybavení.}
{123}{}{Kde najdu plány vertibirdu?}
{124}{}{Potřebuju najít palivo pro PMV Valdez.}
{125}{}{Potřebuju nějaký FOB k přístupu do počítače Valdezu.}
{126}{}{Potřebuju nějaké součásti do počítače PMV Valdezu.}
{127}{}{Hledám slezinu.}
{128}{}{Prý tudy převáželi nějaké létající stroje náklad vesničanů.}
{129}{}{Nic. Nashle.}
{130}{}{Talk to Crockett, over in the Hubologist camp. He is their head scientist.}
{131}{}{Díky. Potřebuju víc informací.}
{132}{}{Dík. Naskle.}
{133}{}{Hledej na severu, v Navarru. Je tam skrytá základna poblíž benzínové pumpy.}
{134}{}{Díky. Potřebuju víc informací.}
{135}{}{Dík. Naskle.}
{136}{}{Co se zkusit podívat do starých Vaultů? Slyšel jsem, že je uvnitř spousta informací a starobylých technologií.}
{137}{}{Díky. Potřebuju víc informací.}
{138}{}{Dík. Naskle.}
{139}{}{Slezinu? Haha! Ano, Chip z Valdezu prohrál svoji slezinu v kartách. Prodal jsem ji Dr. Wongovi. Fascinovala ho.}
{140}{}{Dr. Wong? Kde ho najdu?}
{141}{}{Jak se dá prohrát slezina?}
{142}{}{Díky. Mám další otázky.}
{143}{}{Aha. Nashle.}
{144}{}{Dr. Wong je hlavní vědec v Ocelovém Paláci. Tam ho zastihneš.}
{145}{}{Jak se dá prohrát slezina?}
{146}{}{Díky. Potřebuju víc informací.}
{147}{}{Dík. Naskle.}
{148}{}{Byl opilý. Velmi, velmi opilý. Celý večer se chlubil svojí slezinou a pak ji vsadil.}
{149}{}{Takže ty jsi mu vzal jeho SLEZINU?}
{150}{}{Chápu. No, mám další otázky.}
{151}{}{Ano. Dlužil mi. Je to čestný muž.}
{152}{}{Aha. Potřebuju víc informací.}
{153}{}{Jsi hnusnej nevychovanej hajzl.}
{154}{}{Jasně. Nashle.}
{155}{}{Jsi nečestná osoba. Nechci tě teď ve svém obchodě. Přijď někdy jindy.}
{156}{}{Nevadí.}
{157}{}{Tudy ne. Přiletěli ze severu, proletěli nad našimi hlavami a pokračovali dál přes moře.}
{158}{}{Až za obzor? Jak se tam sakra dostanu?}
{159}{}{Jo, to určitě. Řekni mi, kde jsou, nebo tě otevřu jako plechovku sardinek.}
{160}{}{Mno... žádná z našich lodí není schopná urazit takovou vzdálenost. Ledaže...}
{161}{}{Ledaže...?}
{162}{}{Díky za "pomoc". Raději se poohlédnu po nějaké opravdové radě.}
{163}{}{...ledaže by se ti podařilo zprovoznit ten starý tanker v přístavu. Je to sice stará loď, ale kdyby se na ní udělalo pár oprav, tak bude možná ještě fungovat. Zeptej se tuláků v tankeru, řeknou ti toho víc.}
{164}{}{Díky. Potřebuju víc informací.}
{165}{}{Dík. Naskle.}
{166}{}{Slyšel jsem, že Hubologisté nedávno přišli k velkému množství paliva. Domluv se s nimi.}
{167}{}{Díky. Potřebuju víc informací.}
{168}{}{Dík. Naskle.}
{169}{}{Zkus se zeptat nějakého vědce Shi v Ocelovém Paláci. Možná by ti s tím palivem mohli pomoct.}
{170}{}{Díky. Potřebuju víc informací.}
{171}{}{Dík. Naskle.}
{172}{}{Jsi nepřítel mého lidu. Chcípni!}
{173}{}{Náš lid je ti za zabití AHS-9 velmi vděčný. Doufám, že ti budu moct nějak pomoct.}
{174}{}{Kdo jsi?}
{175}{}{Hledám nějaké vybavení.}
{176}{}{Sháním nějaké informace.}
{177}{}{Nashle.}
{178}{}{Už jsi je dal Hubologistům. Nebo ne?}
{179}{}{A jo... eh... můžu se zeptat na něco jiného?}
{180}{}{A jo... nashle.}
