{100}{}{Vidíš muže, který vypadá jako prodavaè.}
{101}{}{Vidíš prodavaèe Lao Choua.}
{102}{}{Vidíš muže v pohodlném pracovním obleèení.}
{103}{}{Zdravím! Vítej v mém obchodì Flying Dragon 8.}
{104}{}{Co pro tebe mohu udìlat?}
{105}{}{Da aggle oo!}
{106}{}{Vìcièky!}
{107}{}{Kdo jsi?}
{108}{}{Hledám nìjaké vybavení.}
{109}{}{Sháním nìjaké informace.}
{110}{}{Nashle.}
{111}{}{Chceš nìco koupit?}
{112}{}{::kývnout hlavou::}
{113}{}{::zavrtìt hlavou::}
{114}{}{Tohle máme na skladì.}
{115}{}{[KONEC]}
{116}{}{No, obávám se, že víc už pro tebe nemùžu udìlat. Pìkný den.}
{117}{}{[KONEC]}
{118}{}{Jsem Lao Chou. Provozuju tenhle obchod, Flying Dragon 8. Jsem známý tím, že obchoduju i... s informacemi.}
{119}{}{S jakými informacemi?}
{120}{}{Aha. Potøebuju nìjaké vybavení.}
{121}{}{V tomhle mìstì se stane jen málo vìcí, o kterých bych nevìdìl. Samozøejmì se také musíš umìt správnì zeptat, že? Co potøebuješ vìdìt?}
{122}{}{Hledám nìjaké vylepšení pro svoje vybavení.}
{123}{}{Kde najdu plány vertibirdu?}
{124}{}{Potøebuju najít palivo pro PMV Valdez.}
{125}{}{Potøebuju nìjaký FOB k pøístupu do poèítaèe Valdezu.}
{126}{}{Potøebuju nìjaké souèásti do poèítaèe PMV Valdezu.}
{127}{}{Hledám slezinu.}
{128}{}{Prý tudy pøeváželi nìjaké létající stroje náklad vesnièanù.}
{129}{}{Nic. Nashle.}
{130}{}{Talk to Crockett, over in the Hubologist camp. He is their head scientist.}
{131}{}{Díky. Potøebuju víc informací.}
{132}{}{Dík. Naskle.}
{133}{}{Hledej na severu, v Navarru. Je tam skrytá základna poblíž benzínové pumpy.}
{134}{}{Díky. Potøebuju víc informací.}
{135}{}{Dík. Naskle.}
{136}{}{Co se zkusit podívat do starých Vaultù? Slyšel jsem, že je uvnitø spousta informací a starobylých technologií.}
{137}{}{Díky. Potøebuju víc informací.}
{138}{}{Dík. Naskle.}
{139}{}{Slezinu? Haha! Ano, Chip z Valdezu prohrál svoji slezinu v kartách. Prodal jsem ji Dr. Wongovi. Fascinovala ho.}
{140}{}{Dr. Wong? Kde ho najdu?}
{141}{}{Jak se dá prohrát slezina?}
{142}{}{Díky. Mám další otázky.}
{143}{}{Aha. Nashle.}
{144}{}{Dr. Wong je hlavní vìdec v Ocelovém Paláci. Tam ho zastihneš.}
{145}{}{Jak se dá prohrát slezina?}
{146}{}{Díky. Potøebuju víc informací.}
{147}{}{Dík. Naskle.}
{148}{}{Byl opilý. Velmi, velmi opilý. Celý veèer se chlubil svojí slezinou a pak ji vsadil.}
{149}{}{Takže ty jsi mu vzal jeho SLEZINU?}
{150}{}{Chápu. No, mám další otázky.}
{151}{}{Ano. Dlužil mi. Je to èestný muž.}
{152}{}{Aha. Potøebuju víc informací.}
{153}{}{Jsi hnusnej nevychovanej hajzl.}
{154}{}{Jasnì. Nashle.}
{155}{}{Jsi neèestná osoba. Nechci tì teï ve svém obchodì. Pøijï nìkdy jindy.}
{156}{}{Nevadí.}
{157}{}{Tudy ne. Pøiletìli ze severu, proletìli nad našimi hlavami a pokraèovali dál pøes moøe.}
{158}{}{Až za obzor? Jak se tam sakra dostanu?}
{159}{}{Jo, to urèitì. Øekni mi, kde jsou, nebo tì otevøu jako plechovku sardinek.}
{160}{}{Mno... žádná z našich lodí není schopná urazit takovou vzdálenost. Ledaže...}
{161}{}{Ledaže...?}
{162}{}{Díky za "pomoc". Radìji se poohlédnu po nìjaké opravdové radì.}
{163}{}{...ledaže by se ti podaøilo zprovoznit ten starý tanker v pøístavu. Je to sice stará loï, ale kdyby se na ní udìlalo pár oprav, tak bude možná ještì fungovat. Zeptej se tulákù v tankeru, øeknou ti toho víc.}
{164}{}{Díky. Potøebuju víc informací.}
{165}{}{Dík. Naskle.}
{166}{}{Slyšel jsem, že Hubologisté nedávno pøišli k velkému množství paliva. Domluv se s nimi.}
{167}{}{Díky. Potøebuju víc informací.}
{168}{}{Dík. Naskle.}
{169}{}{Zkus se zeptat nìjakého vìdce Shi v Ocelovém Paláci. Možná by ti s tím palivem mohli pomoct.}
{170}{}{Díky. Potøebuju víc informací.}
{171}{}{Dík. Naskle.}
{172}{}{Jsi nepøítel mého lidu. Chcípni!}
{173}{}{Náš lid je ti za zabití AHS-9 velmi vdìèný. Doufám, že ti budu moct nìjak pomoct.}
{174}{}{Kdo jsi?}
{175}{}{Hledám nìjaké vybavení.}
{176}{}{Sháním nìjaké informace.}
{177}{}{Nashle.}
{178}{}{Už jsi je dal Hubologistùm. Nebo ne?}
{179}{}{A jo... eh... mùžu se zeptat na nìco jiného?}
{180}{}{A jo... nashle.}
