{100}{}{Vidíš osobu s kapitánskou èepicí.}
{101}{}{Vidíš kapitána A. Ron Meyerse.}
{102}{}{Vidíš pankáèe v potrhaných šatech a kapitánskou èepicí.}
{103}{}{Co tady sakra chceš? S nikým se nebavím, jenom s pøáteli a dobrými lidmi. Nejdøív udìlej nìjakou službu pro jednoho z mejch pøátel a pak si pøijï promluvit.}
{104}{}{[KONEC]}
{105}{}{Slyšel jsem, co jsi udìlal pro mý muže. Díky. S èím ti mùžu pomoct?}
{106}{}{Kdo ty?}
{107}{}{Øíká se, že víš o téhle lodi všechno.}
{108}{}{Proè ti øíkají kapitán?}
{109}{}{Jak tuhle vìc uvedeš do pohybu?}
{110}{}{No nic.}
{111}{}{Jsem kapitán a øídím tuhle loï. Jestli máš nìjaký otázky, tak si jdi promluvit s nìkým od Shi, s Badgerem a nebo s nìkým jiným. Nemám na tebe èas.}
{112}{}{[KONEC]}
{113}{}{This ship's a Poseidon tanker. It's equipped with tech that lasted through the war. It's got a FOB that allows access to the navigation computer room, and it's got an IFF transponder that protects it from Poseidon guns.}
{114}{}{Jak tohle všechno víš?}
{115}{}{Co je to IFF radarová rušièka?}
{116}{}{Jak tuhle vìc uvedeš do pohybu?}
{117}{}{Dík. Naskle.}
{118}{}{Kdysi jsem sloužil Enklávì. Pak jsem pøišel na to, že jsem vlastnì nebojoval za USA, ale za ty bohatý starý bastardy, kteøí se nechtìli vzdát svý moci. Dezertoval jsem a teï žiju tady mezi poctivìjšími lidmi.}
{119}{}{Poctivìjšími lidmi? Tihle?}
{120}{}{Co je pøesnì Enkláva?}
{121}{}{Jak tuhle vìc uvedeš do pohybu?}
{122}{}{Nashle.}
{123}{}{How do you pilot this rig? Fill 'er up with some gas - try the Hubologists or the Shi after you've taken care of everything else - and press the button. The computer will take care of the rest, if it's still working. It'll sail right out to the oil rig, and they won't fire at you because you've got the IFF transponder. Just make sure you've got what you need to access everything: FOB, working computer, and fuel. Easy enough, huh?}
{124}{}{Jasnì. Jak tohle všechno víš?}
{125}{}{Co je to IFF radarová rušièka a ten FOB?}
{126}{}{Jaká ropná plošina?}
{127}{}{Ano. Nashle.}
{128}{}{IFF: Identifikuj Pøítele nebo Nepøítele. To znamená, že je tahle loï identifikována jako pøátelská, takže ostatní zaøízení Poseidonu jako tøeba ropná plošina, na tebe nebudou støílet, když se dostaneš na dostøel. Jo a FOB je druh Enklávský technologie, která ti umožòuje otevøít dveøe elektronicky. Nejspíš se nachází v jedný z jejich základen nebo na podobnejch místech.}
{129}{}{Jak tohle všechno víš?}
{130}{}{Jaká ropná plošina?}
{131}{}{Dík. Naskle.}
{132}{}{Ano. U tìhlech lidí pøesnì víš, na èem jsi. Na nic si totiž nehrajou. Enkláva byla jako smeèka hyen - ve vteøinì ti vrazili kudlu do zad.}
{133}{}{Co je pøesnì Enkláva?}
{134}{}{Jak ses sem dostal?}
{135}{}{Enkláva je pozùstatek starejch èasù. Jestli se rozhodneš s touhle vìcí doplout k tý plošinì, pøesvìdèíš se o tom sám.}
{136}{}{Jak se to ovládá?}
{137}{}{Jaká plošina?}
{138}{}{Docela lehce. Prostì jsem jednoho dne opustil základnu Navarro a zamíøil sem dolù. Domníval jsem se, že je tohle poslední místo, kde mì budou hledat. A navíc nejsem pro Enklávu dost dùležitej na to, aby mì vùbec hledali - jsem pro nì prostì ztracenej.}
{139}{}{Co je pøesnì Enkláva?}
{140}{}{Dík. Naskle.}
{141}{}{V oceánu stojí osamocená velká ropná plošina Poseidonu. Je to poslední základna Enklávy}
{142}{}{Jak tohle všechno víš?}
{143}{}{Co se na té plošinì ještì dìje?}
{144}{}{Dík. Naskle.}
{145}{}{Øíká se to.}
{146}{}{Aha. Co se na té plošinì ještì dìje?}
{147}{}{Aha. Nashle.}
{148}{}{Co já vím? Byl jsem v Navarru technik, ne operátor plošiny. Mluvili jsme spolu pøes komunikátory a to bylo naše jediný spojení.}
{149}{}{Aha. Jakže se tahle loï ovládá?}
{150}{}{Dík. Naskle.}
{151}{}{Udìlal jsi chybu zahrávat si s kapitánem a jeho pøáteli...}
{152}{}{How do you pilot this rig? Well, I see you already gassed her up. When you've taken care of everything else, just press the button. The computer will take care of the rest, if it's still working. It'll sail right out to the oil rig, and they won't fire at you because you've got the IFF transponder. Just make sure you've got what you need to access everything: FOB, working computer, and fuel. Easy enough, huh?}
{153}{}{Jo a musíš ještì zprovoznit navigaèní poèítaè. Vsadím se, že pro nìj najdeš nìjaký souèástky v jednom z tìch starejch vaultù.}
{154}{}{Rád tì zase vidím. Co potøebuješ?}
{155}{}{ a moc bych za to nedal, že tam jsou i tví pøátelé.}
{156}{}{.}
