{100}{}{Vidíš poèítaèovı terminál.}
{101}{}{Vidíš terminál poèítaèe Císaø.}
{102}{}{Vídíš poèítaè se zabudovanou dotykovou obrazovkou, která slouí jako rozhraní. Na boku má vyryto "Císaø v8.8 Poèítaèovı Terminál".}
{103}{}{Zdravím. Prosím zadejte heslo pro ovìøení totonosti.}
{104}{}{::slintat::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{::hacknout se do poèítaèe::}
{109}{}{Odhlásit se.}
{110}{}{Identita potvrzena.}
{111}{}{Kterou funkci si pøejete zpøístupnit?}
{112}{}{Diagnostické funkce.}
{113}{}{Databáze.}
{114}{}{Pøedpovìdi.}
{115}{}{Odhlásit se.}
{116}{}{Prosím, obrate se na správce systému. Nashledanou.}
{117}{}{::hacknout se do poèítaèe::}
{118}{}{::odejít::}
{119}{}{Zaznamenán nepovolenı pøístup. Automatické vypnutí. Pøeji hezkı den.}
{120}{}{[KONEC]}
{121}{}{Diagnostické funkce?}
{122}{}{Procházet sí.}
{123}{}{Zformátovat disk.}
{124}{}{Zkontrolovat integritu pevného disku.}
{125}{}{Zpìt.}
{126}{}{Kterou databázi si pøejete provìøit?}
{127}{}{Biologie.}
{128}{}{Chemie.}
{129}{}{Fyzika.}
{130}{}{Historie.}
{131}{}{Zpìt.}
{132}{}{Dìti mìsta Shi jsou v nebezpeèí. Je 50% pravdìpodobnost, e se mezi nimi pohybuje vrah.}
{133}{}{Ve mìstì Shi se objevilo nebezpeèí. Je 75% pravdìpodobnost, e nìkdo pøijde k úrazu.}
{134}{}{Start Hubologistù do vesmíru z 95% zkrachuje. Faktory: bez paliva, nevhodné tìsnìní, špatné vedení, nedostatek iniciativy.}
{135}{}{Je 15% pravdìpodobnost, e urèenı "Vyvolenı" uspìje ve svém úkolu.}
{136}{}{Fakta naznaèují, e je "Enkláva" mnohem silnìjší ne se pùvodnì pøedpokládalo; nepøibliovat se.}
{137}{}{Chances of submarine reappearing in this game: 0%}
{138}{}{Tuláci v tankeru mají pravdìpodobnost 0%, e vyèistí zamoøení pøíšerami bez cizí pomoci. Zpracovávám vhodnost poskytnutí pomoci.}
{139}{}{Fakt: Ropnı tanker Poseidon nevhodnı pro cestu. Vyaduji více informací.}
{140}{}{ádné procesy. Vyaduji vstup.}
{141}{}{[Více]}
{142}{}{Zpìt.}
{143}{}{Biologická stanice: Aktivní}
{144}{}{Biologická stanice: Neaktivní}
{145}{}{Chemická stanice: Aktivní}
{146}{}{Chemická stanice: Neaktivní}
{147}{}{Fyzikální stanice: Aktivní}
{148}{}{Fyzikální stanice: Neaktivní}
{149}{}{Deaktivovat Biologickou Stanici.}
{150}{}{Deaktivovat Chemickou Stanici.}
{151}{}{Deaktivovat Fyzikální Stanici.}
{152}{}{Zpøístupnit Biologickou Stanici.}
{153}{}{Zpøístupnit Chemickou Stanici.}
{154}{}{Zpøístupnit Fyzikální Stanici.}
{155}{}{Aktivovat Biologickou Stanici.}
{156}{}{Aktivovat Chemickou Stanici.}
{157}{}{Aktivovat Fyzikální Stanici.}
{158}{}{Zpìt.}
{159}{}{Formátování disku: Všechna data budou ztracena. Pøejete si pokraèovat?}
{160}{}{Ano.}
{161}{}{Ne.}
{162}{}{Funkèní integrita tohoto systému je 92% Stínìní jádra poèítaèe Císaø je 100% Integrita dat je 100% Pøedpovìdní uzel trpí menšími vıpadky energie - pøedpokládanı èas oprav 6 dní. Pøedpovìdi z 15% funkèní.}
{163}{}{Zpìt.}
{164}{}{Opravdu si pøejete zformátovat tuto jednotku? Proces je nevratnı.}
{165}{}{Ano.}
{166}{}{Ne.}
{167}{}{Formátuji... formátuji... formátování dokonèeno. Restart vyaduje plnou instalaci. Vypínání. Vypnutí... poèítaèe... dokonèeno...}
{168}{}{[KONEC]}
{169}{}{Data to find: - Botany program - Genetic program - Xeno program.}
{170}{}{Botanickı program.}
{171}{}{Genetickı program.}
{172}{}{Xeno program.}
{173}{}{Zpìt.}
{174}{}{(Po dvaceti minutách se ti podaøilo objevit toto: Poèáteèní vısledky rušení radiace pomocí rostlin se ukázaly jako málo slibné. Dr. Sheng vyvinul rostlinnı ivot odolnı vùèi radiaci -- s nepøíjemnımi vedlejšími úèinky. Vıslednı rostlinnı ivot je povaován za pøíliš nebezpeènı. Sheng trvá na dalším zkoumání v kombinaci s genetickım programem.)}
{175}{}{Genetickı program.}
{176}{}{Xeno program.}
{177}{}{Zpìt.}
{178}{}{(Po dvaceti minutách se ti podaøilo poskládat dohromady tuto informaci: Dr. Long Wang byl pøesvìdèen o úspìchu vytvoøení zmutovanıch vojákù s pouitím základní struktury viru FEV. Vytvoøil sérum, které pøi pokusech s hlodavci vykazovalo zajímavé vısledky. Pøi aplikaci séra na sobì se zmìnil na rozplizlou mazlavou hmotu. Dr. Sheng ukonèil tuto oblast vızkumu. Po smrti Dr. Longa se stal Dr. Sheng vedoucím. Sheng poaduje, aby se vızkum soustøedil na rostlinnı ivot pohlcující radiaci.)}
{179}{}{Botanickı program.}
{180}{}{Xeno program.}
{181}{}{Zpìt.}
{182}{}{"The subject on which we had hoped to establish a series of meaningful experiments has disappeared, presumed either destroyed or stolen by the Hubologists. Further inquiries have proven fruitless. Until such time as further specimens are obtained, this database will remain inoperative." - Dr. Sheng.}
{183}{}{Botanickı program.}
{184}{}{Genetickı program.}
{185}{}{Zpìt.}
{186}{}{Chemické Databáze: Palivo a deriváty - Polymery}
{187}{}{Paliva a deriváty.}
{188}{}{Polymery.}
{189}{}{Zpìt.}
{190}{}{(After sifting through the complex chemical formulae and lab notes, you come to the conclusion that the Shi have created a kind of fuel from plant extracts and sealife. Apparently, they have hooked into previously existing pipelines so they can transport fuel to a wide variety of destinations.)}
{191}{}{(Narazil jsi na veliké mnoství sloitıch chemickıch vzorcù a laboratorních zápiskù. Nejsi si úplnì jistı, co všechno znamenají.)}
{192}{}{Pøevést palivo do tankeru Poseidon.}
{193}{}{Pøevést palivo k Hubologistùm.}
{194}{}{Zpìt.}
{195}{}{(Po pøelouskání symbologie a technické dokumentace se ti podaøilo zjistit, e Shi pracují na nové polymerické zbroji, která je odolná vùèi ohni a prùbojnım støelám. Dokonèení je však stále v nedohlednu. Také si všímáš zmínky o novıch zbraních a konstrukèních monostech. Oèividnì mají Shi nìjaké plány do budoucna.)}
{196}{}{Zpìt.}
{197}{}{Palivo pøevedeno dle poadavku. Skladovací nádre = Prázdné. Ukonèuji program.}
{198}{}{[KONEC]}
{199}{}{Palivo pøevedeno dle poadavku. Skladovací nádre = Prázdné. Ukonèuji program.}
{200}{}{[KONEC]}
{201}{}{Fyzikální databáze: Vızkum - Teorie}
{202}{}{Exploration.}
{203}{}{Theory.}
{204}{}{Zpìt.}
{205}{}{"Díky nedávnému získání plánù k vertibirdu se kvantovım skokem zvıšila šance na sestrojení praktického létajícího stroje. Oèekáváme, e koncem roku budeme mít funkèní prototyp a do dvou let budeme moci zahájit hromadnou vırobu." -Dr. Wong}
{206}{}{::zkopírovat plány:: Zpìt.}
{207}{}{Zpìt.}
{208}{}{"Stále pøipravujeme funkèní model vzdušného stroje. ádnı z našich návrhù se neosvìdèil jako bezpeènı nebo aerodynamickı. Moná kdybychom mìli pøístup ke starodávnım plánùm..." -Dr. Wong}
{209}{}{Zpìt.}
{210}{}{(Po pøelouskání úvodu a matematiky zjišuješ, e se Shi opìt snaí zkoumat nukleární energii. Oivují tak teorii vesmírnıch letù našich pøedkù - a pøitom se vysmívají Hubologistùm - a vyuívají energii slunce, vìtru a moøe. Tohle je v tìch zápiskách opravdu napsáno.)}
{211}{}{Zpìt.}
{212}{}{Stanice aktivována.}
{213}{}{Zpìt.}
{214}{}{Poèítaèovı terminál pro tohle nemá rozhraní.}
{215}{}{Poèítaèovı terminál vypadá, e není v provozu.}
{216}{}{Systém byl napaden. Pøíkazy jsou zaútoèit!}
{217}{}{Zaútoète na vetøelce!}
{218}{}{Je èas zaplatit za své èiny, lao wai!}
{219}{}{Mezi námi je zrádce!}
{220}{}{Zemìpisná lokace.}
{221}{}{Co si pøejete lokalizovat?}
{222}{}{Vesnièany z mého domova.}
{223}{}{Celkem 97% pravdìpodobnost - vesnièané lokalizováni na souøadnicích komplexu Enklávy.}
