{100}{}{Vidíš počítačový terminál.}
{101}{}{Vidíš terminál počítače Císař.}
{102}{}{Vídíš počítač se zabudovanou dotykovou obrazovkou, která slouží jako rozhraní. Na boku má vyryto "Císař v8.8 Počítačový Terminál".}
{103}{}{Zdravím. Prosím zadejte heslo pro ověření totožnosti.}
{104}{}{::slintat::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{::hacknout se do počítače::}
{109}{}{Odhlásit se.}
{110}{}{Identita potvrzena.}
{111}{}{Kterou funkci si přejete zpřístupnit?}
{112}{}{Diagnostické funkce.}
{113}{}{Databáze.}
{114}{}{Předpovědi.}
{115}{}{Odhlásit se.}
{116}{}{Prosím, obraťte se na správce systému. Nashledanou.}
{117}{}{::hacknout se do počítače::}
{118}{}{::odejít::}
{119}{}{Zaznamenán nepovolený přístup. Automatické vypnutí. Přeji hezký den.}
{120}{}{[KONEC]}
{121}{}{Diagnostické funkce?}
{122}{}{Procházet síť.}
{123}{}{Zformátovat disk.}
{124}{}{Zkontrolovat integritu pevného disku.}
{125}{}{Zpět.}
{126}{}{Kterou databázi si přejete prověřit?}
{127}{}{Biologie.}
{128}{}{Chemie.}
{129}{}{Fyzika.}
{130}{}{Historie.}
{131}{}{Zpět.}
{132}{}{Děti města Shi jsou v nebezpečí. Je 50% pravděpodobnost, že se mezi nimi pohybuje vrah.}
{133}{}{Ve městě Shi se objevilo nebezpečí. Je 75% pravděpodobnost, že někdo přijde k úrazu.}
{134}{}{Start Hubologistů do vesmíru z 95% zkrachuje. Faktory: bez paliva, nevhodné těsnění, špatné vedení, nedostatek iniciativy.}
{135}{}{Je 15% pravděpodobnost, že určený "Vyvolený" uspěje ve svém úkolu.}
{136}{}{Fakta naznačují, že je "Enkláva" mnohem silnější než se původně předpokládalo; nepřibližovat se.}
{137}{}{Pravděpodobnost, že se v této hře opět objeví ponorka: 0%}
{138}{}{Tuláci v tankeru mají pravděpodobnost 0%, že vyčistí zamoření příšerami bez cizí pomoci. Zpracovávám vhodnost poskytnutí pomoci.}
{139}{}{Fakt: Ropný tanker Poseidon nevhodný pro cestu. Vyžaduji více informací.}
{140}{}{Žádné procesy. Vyžaduji vstup.}
{141}{}{[Více]}
{142}{}{Zpět.}
{143}{}{Biologická stanice: Aktivní}
{144}{}{Biologická stanice: Neaktivní}
{145}{}{Chemická stanice: Aktivní}
{146}{}{Chemická stanice: Neaktivní}
{147}{}{Fyzikální stanice: Aktivní}
{148}{}{Fyzikální stanice: Neaktivní}
{149}{}{Deaktivovat Biologickou Stanici.}
{150}{}{Deaktivovat Chemickou Stanici.}
{151}{}{Deaktivovat Fyzikální Stanici.}
{152}{}{Zpřístupnit Biologickou Stanici.}
{153}{}{Zpřístupnit Chemickou Stanici.}
{154}{}{Zpřístupnit Fyzikální Stanici.}
{155}{}{Aktivovat Biologickou Stanici.}
{156}{}{Aktivovat Chemickou Stanici.}
{157}{}{Aktivovat Fyzikální Stanici.}
{158}{}{Zpět.}
{159}{}{Formátování disku: Všechna data budou ztracena. Přejete si pokračovat?}
{160}{}{Ano.}
{161}{}{Ne.}
{162}{}{Funkční integrita tohoto systému je 92% Stínění jádra počítače Císař je 100% Integrita dat je 100% Předpovědní uzel trpí menšími výpadky energie - předpokládaný čas oprav 6 dní. Předpovědi z 15% funkční.}
{163}{}{Zpět.}
{164}{}{Opravdu si přejete zformátovat tuto jednotku? Proces je nevratný.}
{165}{}{Ano.}
{166}{}{Ne.}
{167}{}{Formátuji... formátuji... formátování dokončeno. Restart vyžaduje plnou instalaci. Vypínání. Vypnutí... počítače... dokončeno...}
{168}{}{[KONEC]}
{169}{}{Vyhledat data: - Botanický program - Genetický program - Xeno program.}
{170}{}{Botanický program.}
{171}{}{Genetický program.}
{172}{}{Xeno program.}
{173}{}{Zpět.}
{174}{}{(Po dvaceti minutách se ti podařilo objevit toto: Počáteční výsledky rušení radiace pomocí rostlin se ukázaly jako málo slibné. Dr. Sheng vyvinul rostlinný život odolný vůči radiaci -- s nepříjemnými vedlejšími účinky. Výsledný rostlinný život je považován za příliš nebezpečný. Sheng trvá na dalším zkoumání v kombinaci s genetickým programem.)}
{175}{}{Genetický program.}
{176}{}{Xeno program.}
{177}{}{Zpět.}
{178}{}{(Po dvaceti minutách se ti podařilo poskládat dohromady tuto informaci: Dr. Long Wang byl přesvědčen o úspěchu vytvoření zmutovaných vojáků s použitím základní struktury viru FEV. Vytvořil sérum, které při pokusech s hlodavci vykazovalo zajímavé výsledky. Při aplikaci séra na sobě se změnil na rozplizlou mazlavou hmotu. Dr. Sheng ukončil tuto oblast výzkumu. Po smrti Dr. Longa se stal Dr. Sheng vedoucím. Sheng požaduje, aby se výzkum soustředil na rostlinný život pohlcující radiaci.)}
{179}{}{Botanický program.}
{180}{}{Xeno program.}
{181}{}{Zpět.}
{182}{}{Subjekt, na kterém jsme chtěli provést sérii významných pokusů, zmizel. Předpokládá se, že byl buď zničen, nebo odcizen Hubologisty. Další výzkumy se ukázaly jako marné. Dokud neobdržíme další exempláře, tato databáze zůstane mimo provoz." - Dr. Sheng.}
{183}{}{Botanický program.}
{184}{}{Genetický program.}
{185}{}{Zpět.}
{186}{}{Chemické Databáze: Palivo a deriváty - Polymery}
{187}{}{Paliva a deriváty.}
{188}{}{Polymery.}
{189}{}{Zpět.}
{190}{}{(Po prostudování složitých chemických vzorců a laboratorních zápisků docházíš k závěru, že Shi vytvořili nový druh paliva z rostlinných extraktů a mořského života. Také se údajně napojili na dříve existující potrubí, aby mohli dopravovat palivo do vícero lokací.)}
{191}{}{(Narazil jsi na veliké množství složitých chemických vzorců a laboratorních zápisků. Nejsi si úplně jistý, co všechno znamenají.)}
{192}{}{Převést palivo do tankeru Poseidon.}
{193}{}{Převést palivo k Hubologistům.}
{194}{}{Zpět.}
{195}{}{(Po přelouskání symbologie a technické dokumentace se ti podařilo zjistit, že Shi pracují na nové polymerické zbroji, která je odolná vůči ohni a průbojným střelám. Dokončení je však stále v nedohlednu. Také si všímáš zmínky o nových zbraních a konstrukčních možnostech. Očividně mají Shi nějaké plány do budoucna.)}
{196}{}{Zpět.}
{197}{}{Palivo převedeno dle požadavku. Skladovací nádrže = Prázdné. Ukončuji program.}
{198}{}{[KONEC]}
{199}{}{Palivo převedeno dle požadavku. Skladovací nádrže = Prázdné. Ukončuji program.}
{200}{}{[KONEC]}
{201}{}{Fyzikální databáze: Výzkum - Teorie}
{202}{}{Výzkum.}
{203}{}{Teorie.}
{204}{}{Zpět.}
{205}{}{"Díky nedávnému získání plánů k vertibirdu se kvantovým skokem zvýšila šance na sestrojení praktického létajícího stroje. Očekáváme, že koncem roku budeme mít funkční prototyp a do dvou let budeme moci zahájit hromadnou výrobu." -Dr. Wong}
{206}{}{::zkopírovat plány:: Zpět.}
{207}{}{Zpět.}
{208}{}{"Stále připravujeme funkční model vzdušného stroje. Žádný z našich návrhů se neosvědčil jako bezpečný nebo aerodynamický. Možná kdybychom měli přístup ke starodávným plánům..." -Dr. Wong}
{209}{}{Zpět.}
{210}{}{(Po přelouskání úvodu a matematiky zjišťuješ, že se Shi opět snaží zkoumat nukleární energii. Oživují tak teorii vesmírných letů našich předků - a přitom se vysmívají Hubologistům - a využívají energii slunce, větru a moře. Tohle je v těch zápiskách opravdu napsáno.)}
{211}{}{Zpět.}
{212}{}{Stanice aktivována.}
{213}{}{Zpět.}
{214}{}{Počítačový terminál pro tohle nemá rozhraní.}
{215}{}{Počítačový terminál vypadá, že není v provozu.}
{216}{}{Systém byl napaden. Příkazy jsou zaútočit!}
{217}{}{Zaútočte na vetřelce!}
{218}{}{Je čas zaplatit za své činy, lao wai!}
{219}{}{Mezi námi je zrádce!}
{220}{}{Zeměpisná lokace.}
{221}{}{Co si přejete lokalizovat?}
{222}{}{Vesničany z mého domova.}
{223}{}{Celkem 97% pravděpodobnost - vesničané lokalizováni na souřadnicích komplexu Enklávy.}
