{100}{}{Vidíš přátelsky vypadajícího hubeného muže.}
{101}{}{Vidíš Chada, správce karavan.}
{102}{}{Vidíš hubeného muže, který předstírá úsměv. Má na sobě nepopsatelné oblečení a vypadá, že ví, co dělá.}
{120}{}{Jak to jde, příteli? Co pro tebe můžu udělat?}
{121}{}{Víc otázek? Pokusím se na ně odpovědět, jak nejlíp dokážu.}
{122}{}{Všiváku prašivej!}
{123}{}{Kdo ty?}
{124}{}{Marcus se na tebe ptal.}
{125}{}{Mám dost důkazů na to, abys byl zatčen za krádež peněz určených pro Broken Hills. Máš to spočítaný.}
{126}{}{Je tu dost důkazů na to, abys byl zatčen za krádež peněz určených pro Broken Hills. Naval $1000 a zajistím ti bezpečný útěk z města.}
{127}{}{Kdo jsi?}
{128}{}{Pověz mi něco o tomhle místě.}
{129}{}{Nic. Nashle.}
{130}{}{Podívejte, co nám sem pustina donesla! Promiň kámo, ale nemůžu ti pomoct.}
{131}{}{Razim!}
{132}{}{Jsem Chad.}
{133}{}{Podívej, mám moc práce. Běž prosím otravovat někoho jiného.}
{134}{}{Jsem správce karavan tohohle města. Starám se o výměnu na druhém konci obchodních cest. Posledních pár dní jsem se zaměřoval hlavně na Gecko.}
{135}{}{To fajn!}
{136}{}{Chci pro tebe pracovat.}
{137}{}{To zní skvěle.}
{138}{}{To zní nudně.}
{139}{}{Mám další otázky.}
{140}{}{Dík. Měj se.}
{141}{}{O Broken Hills? Dobrá... přišel jsem sem před několika lety. Dostal jsem práci u vetešníka Billa a vypracoval se až tam, kde jsem teď. Zodpovídám se sice Marcusovi a Billovi, ale jsem zodpovědný za chod města.}
{142}{}{Mám další otázky.}
{143}{}{Čau.}
{144}{}{Například?}
{145}{}{Má podezření, že si pro sebe ulíváš peníze, které jsou určené pro Broken Hills.}
{146}{}{Vlastně na nic. Sbohem.}
{147}{}{Podívejte, nemám rád, když mě lidé obviňují z něčeho, o čem nic nevím. Navrhuji, abyste odešel.}
{150}{}{Jdu zjistit, jak to doopravdy je. Sbohem.}
{156}{}{Promluv si s Billem. On ti pomůže.}
{157}{}{Mám další otázky.}
{158}{}{Dík. Měj se.}
{159}{}{Jo, taky že je. Asi by tě to ani nenapadlo, ale docela cestuju po světě... a řekl bych, že přispívám tomuhle městu. Je to dobrej život.}
{160}{}{To zní skvěle. Taková práce by se mi líbila.}
{161}{}{No, ve skutečnosti to zní jako pěkná nuda.}
{162}{}{Mám další otázky.}
{163}{}{Čau.}
{164}{}{Určitě je to podstatně víc vzrušující než to, co děláš se svým životem ty, kokote.}
{165}{}{No jasně, jak myslíš. Mám další otázky.}
{166}{}{Hahahaha! Jasně. Zatím, pako.}
{167}{}{Jednou za to zaplatíš, ocasi.}
{168}{}{Zmiz mi z očí, hovado.}
{169}{}{Pěkně jsi tu karavanu podělal, příteli. Na peníze zapomeň.}
{170}{}{Opravdu si tu karavanu neskutečně zbabral, příteli. Hodně štěstí s někým jiným z Broken Hills.}
{171}{}{Dobrá práce. Tady máš svých $200.}
{172}{}{Padej odsud. Tvoji pomoc tady nepotřebujeme.}
{173}{}{Měj oči na šťopkách.}
{174}{}{Budu tě krýt.}
{175}{}{Nenech ty bastardy kolem tebe proklouznout.}
