{100}{}{Vidíš pøátelsky vypadajícího hubeného mue.}
{101}{}{Vidíš Chada, správce karavan.}
{102}{}{Vidíš hubeného mue, kterı pøedstírá úsmìv. Má na sobì nepopsatelné obleèení a vypadá, e ví, co dìlá.}
{120}{}{Jak to jde, pøíteli? Co pro tebe mùu udìlat?}
{121}{}{Víc otázek? Pokusím se na nì odpovìdìt, jak nejlíp dokáu.}
{122}{}{Všiváku prašivej!}
{123}{}{Kdo ty?}
{124}{}{Marcus se na tebe ptal.}
{125}{}{There's enough evidence that you've been stealing money that's supposed to go to Broken Hills
 that you can be arrested. You're going down.}
{126}{}{There's enough evidence that you've been stealing money that's supposed to go to Broken Hills
 that you can be arrested. Cut me in for $1000 and I'll make sure you can flee town.}
{127}{}{Kdo jsi?}
{128}{}{Povìz mi nìco o tomhle místì.}
{129}{}{Nic. Nashle.}
{130}{}{Podívejte, co nám sem pustina donesla! Promiò kámo, ale nemùu ti pomoct.}
{131}{}{Naskle!}
{132}{}{Jsem Chad.}
{133}{}{Podívej, mám moc práce. Bì prosím otravovat nìkoho jiného.}
{134}{}{I'm the caravan master for the city. I take care of the business on the other end of the trade
 routes. These days I'm focusing primarily on Gecko. }
{135}{}{To fajn!}
{136}{}{Chci pro tebe pracovat.}
{137}{}{To zní skvìle.}
{138}{}{To zní nudnì.}
{139}{}{Mám další otázky.}
{140}{}{Dík. Naskle.}
{141}{}{Tell you about Broken Hills? Well... I moved here a few years back. Got a job with the Bill --
 that's the Outfitter -- and moved up to where I am now. I report to Marcus and the Bill, but I'm
 responsible for the livelihood of the town.}
{142}{}{Mám další otázky.}
{143}{}{Nashle.}
{144}{}{Napøíklad?}
{145}{}{He suspects, that you are skimming the money that's supposed to go Broken Hills.}
{146}{}{Vlastnì na nic. Sbohem.}
{147}{}{Look, I don't like people to accuse me about something that I don't know anything about. I suggest that you leave.}
{150}{}{I'm going to find the truth. Bye.}
{156}{}{Promluv si s Billem. On ti pomùe.}
{157}{}{Mám další otázky.}
{158}{}{Dík. Naskle.}
{159}{}{Jo, taky e je. Asi by tì to ani nenapadlo, ale docela cestuju po svìtì... a øekl bych, e pøispívám tomuhle mìstu. Je to dobrej ivot.}
{160}{}{To zní skvìle. Taková práce by se mi líbila.}
{161}{}{No, ve skuteènosti to zní jako pìkná nuda.}
{162}{}{Mám další otázky.}
{163}{}{Nashle.}
{164}{}{Urèitì je to podstatnì víc vzrušující ne to, co dìláš se svım ivotem ty, kokote.}
{165}{}{No jasnì, jak myslíš. Mám další otázky.}
{166}{}{Hahahaha! Jasnì. Zatím, pako.}
{167}{}{Jednou za to zaplatíš, ocasi.}
{168}{}{Zmiz mi z oèí, hovado.}
{169}{}{Pìknì jsi tu karavanu podìlal, pøíteli. Na peníze zapomeò.}
{170}{}{Opravdu si tu karavanu neskuteènì zbabral, pøíteli. Hodnì štìstí s nìkım jinım z Broken Hills.}
{171}{}{Dobrá práce. Tady máš svıch $200.}
{172}{}{Padej odsud. Tvoji pomoc tady nepotøebujeme.}
{173}{}{Mìj oèi na šopkách.}
{174}{}{Budu tì krıt.}
{175}{}{Nenech ty bastardy kolem tebe proklouznout.}
