{100}{}{Vidíš znudìnou osobu v kožené zbroji.}
{101}{}{Vidíš Maxe, strážce karavany.}
{102}{}{Vidíš zaprášenou, znudìnou osobu v kožené zbroji. Podle zápachu brahmín a sebejisté chùze je jasné, že je strážce karavan.}
{103}{}{Mùžu ti nìjak pomoct?}
{104}{}{He?}
{105}{}{Já pracovat tady!}
{106}{}{Kdo jsi?}
{107}{}{Co mi mùžeš øíct o Chadovi?}
{108}{}{S idioty nemám strpení. Promiò kámo, ale budeš si muset najít na hraní nìkoho jiného.}
{109}{}{::smrk::}
{110}{}{Jsem Max, jeden ze strážcù karavan.}
{111}{}{Co mi mùžeš øíct o Chadovi?}
{112}{}{Dík. Naskle.}
{113}{}{I don't like him much. He seems to get always some extra money from his caravan jobs. It's really unfair.}
{114}{}{Well, Marcus suspects that he is skimming some of the money that supposed to go Broken Hills.}
{115}{}{Dík. Naskle.}
{116}{}{Thanks. I'm sure glad that this is over. You better watch your back thought.}
{117}{}{Nashle.}
{118}{}{Nepøítel! Chcípni!}
{119}{}{A sakra.}
{120}{}{(Lowers his voice and looks around) That's gotta be it. I once saw myself that he was taking some "slice" of that money he got from uranium shipment from Gecko.}
{121}{}{Really? Then why you haven't tell about it to Marcus then?}
{122}{}{Are you duff? If I go to tell it, a lot of people in this town won't even look at me. Besides I might get some kind of revenge.}
{123}{}{Hmm, I could tell it about to Marcus, cause I don't plan to stay here too long anyway.}
{124}{}{Ok. Do what you want, but don't tell anything about me. And we never had this conversation, ok?}
{125}{}{Don't worry, I don't want to get you in any trouble, bye.}
