{100}{}{Vidíš znuděnou osobu v kožené zbroji.}
{101}{}{Vidíš Maxe, strážce karavany.}
{102}{}{Vidíš zaprášenou, znuděnou osobu v kožené zbroji. Podle zápachu brahmín a sebejisté chůze je jasné, že je strážce karavan.}
{103}{}{Můžu ti nějak pomoct?}
{104}{}{He?}
{105}{}{Já pracovat tady!}
{106}{}{Kdo jsi?}
{107}{}{Co mi můžeš říct o Chadovi?}
{108}{}{S idioty nemám strpení. Promiň kámo, ale budeš si muset najít na hraní někoho jiného.}
{109}{}{::smrk::}
{110}{}{Jsem Max, jeden ze strážců karavan.}
{111}{}{Co mi můžeš říct o Chadovi?}
{112}{}{Dík. Měj se.}
{113}{}{Nemám ho moc rád. Zdá se, že si vždycky bere peníze navíc ze své pozice v karavaně. Je to opravdu nespravedlivé.}
{114}{}{Nuže, Marcus má podezření, že si pro sebe ulívá peníze, které jsou určené pro Broken Hills.}
{115}{}{Dík. Měj se.}
{116}{}{Díky. Jsem opravdu rád, že je to vyřízené. Ale měl by sis teď hlídat záda.}
{117}{}{Čau.}
{118}{}{Nepřítel! Chcípni!}
{119}{}{A sakra.}
{120}{}{[Ztiší hlas a rozhlédne se] To musí být ono. Sám jsem jednou viděl, že si bere nějaký "krajíc" z těch peněz, co dostal za dodávku uranu od Gecka.}
{121}{}{Opravdu? Tak proč jsi o tom neřekl nic Marcusovi?}
{122}{}{Máš to v hlavě v pořádku? Když to půjdu říct, spousta lidí v tomhle městě se na mě ani nepodívá. Navíc by se mi to mohlo nějak vymstít.}
{123}{}{Hmm, tak to nejspíš řeknu Marcusovi já. Stejně tu nehodlám zůstat delší dobu.}
{124}{}{Dobře. Dělej si co chceš, jen mě do toho netahej. A nikdy jsem nevedly tento rozhovor, jasný?}
{125}{}{Žádný strach, nechci tě zatahovat do žádných potíží, měj se.}
