{100}{}{Vidíš osobu se silnou zbraní.}
{101}{}{Vidíš hlídače karavan z Broken Hills.}
{102}{}{Vidíš osobu se silnou zbraní a v zaprášeném oblečením.}
{103}{}{Něco ti řeknu, ještě jednou potkám skupinu potulnejch zabijáků a na příští cestu si beru dynamit.}
{104}{}{Hodila by se nám nějaká pomoc na hlídání karavan.}
{105}{}{Do háje... práce hlídky už mi leze krkem.}
{106}{}{Pak jsem uviděl, jak se blíží nějakej divoch a... to je jedno.}
{107}{}{Ještě jednou nás bude chtít někdo obrat, tak ho zabiju.}
{108}{}{Přísahám, že jestli banditi ještě jednou něco zkusí, tak příští rok všichni zemřeme.}
{109}{}{Z jakýpak díry jsi to vylez?}
{110}{}{Koupíš pracujícímu drink?}
{111}{}{Jsem tak unavenej hlídáním karavan, že už nemůžu ani mluvit.}
{112}{}{Jestli něco potřebuješ, promluv si s vetešníkem Billem.}
{113}{}{Člověk by si myslel, že budem po všem tom civilizování pustiny blíž cíli.}
{114}{}{Tyhle války mezi lidma a mutantama už mě nudí. Neměli bysme jít příkladem?}
{115}{}{Co chceš? Nevidíš, že odpočívám?}
{116}{}{Kdy odjíždí další karavana?}
{117}{}{Hlídat, hlídat a zase hlídat... to je to jediný, co tady dělám.}
{118}{}{Myslím, že si potřebuju dáchnout.}
{119}{}{Zasloužím si dostat přidáno, tohle je nebezpečná práce.}
