{100}{}{Vidíš osobu se silnou zbraní.}
{101}{}{Vidíš hlídaèe karavan z Broken Hills.}
{102}{}{Vidíš osobu se silnou zbraní a v zaprášeném obleèením.}
{103}{}{Nìco ti øeknu, ještì jednou potkám skupinu potulnejch zabijákù a na pøíští cestu si beru dynamit.}
{104}{}{Hodila by se nám nìjaká pomoc na hlídání karavan.}
{105}{}{Do háje... práce hlídky už mi leze krkem.}
{106}{}{Pak jsem uvidìl, jak se blíží nìjakej divoch a... to je jedno.}
{107}{}{Ještì jednou nás bude chtít nìkdo obrat, tak ho zabiju.}
{108}{}{Pøísahám, že jestli banditi ještì jednou nìco zkusí, tak pøíští rok všichni zemøeme.}
{109}{}{Z jakýpak díry jsi to vylez?}
{110}{}{Koupíš pracujícímu drink?}
{111}{}{Jsem tak unavenej hlídáním karavan, že už nemùžu ani mluvit.}
{112}{}{Jestli nìco potøebuješ, promluv si s vetešníkem Billem.}
{113}{}{Èlovìk by si myslel, že budem po všem tom civilizování pustiny blíž cíli.}
{114}{}{Tyhle války mezi lidma a mutantama už mì nudí. Nemìli bysme jít pøíkladem?}
{115}{}{Co chceš? Nevidíš, že odpoèívám?}
{116}{}{Kdy odjíždí další karavana?}
{117}{}{Hlídat, hlídat a zase hlídat... to je to jediný, co tady dìlám.}
{118}{}{Myslím, že si potøebuju dáchnout.}
{119}{}{Zasloužím si dostat pøidáno, tohle je nebezpeèná práce.}
