{100}{}{Vidíš zamraèenou ženu.}
{101}{}{Vidíš Liz, majitelku obchodu.}
{102}{}{Vidíš ženu ve støedních letech, která se neustále mraèí. Vypadá jako jeden z tìch lidí, kteøí mají z tìžkého života perverzní potìšení.}
{103}{}{Ahoj, jsem Liz. Co potøebuješ?}
{104}{}{A teï co?}
{105}{}{Nggg! Nnnnnng!}
{106}{}{Já chtít vìcièky!}
{107}{}{Chci nakoupit nìjaké vìci.}
{108}{}{Mùžeš mi nìco povìdìt o tomhle mìstì?}
{109}{}{Chci nìco zabít. Nenašlo by se tu nìco?}
{110}{}{Proè máš ve sklepì ty zbranì?}
{111}{}{Prý máš nìjaké pøebyteèné zbranì. Možná by se mi hodily.}
{112}{}{No nic.}
{113}{}{Ach bože... další malý, postižený mutant. Kdy koneènì nìkdo postøílí tyhle vìci?}
{114}{}{Škyt.}
{115}{}{Mluv pomalu a jasnì a pak ti možná budu moct nìjak pomoct.}
{116}{}{Potøebovat! Vìcièky! Já!}
{117}{}{Naskledanou!}
{118}{}{Chceš nìco koupit?}
{119}{}{Ano!}
{120}{}{Ne ne ne.}
{121}{}{No dobøe. Co potøebuješ?}
{122}{}{Obchod.}
{123}{}{Nezapomeò na dýško.}
{124}{}{Dìkujù!}
{125}{}{Chceš nìco koupit? Dobøe. Tohle nabízím.}
{126}{}{Ještì jednu vìc...}
{127}{}{Díky. Zatím.}
{128}{}{Jsme malé, nudné, tìžební mìsto se spoustou nechtìných obyvatel. Jestli chceš prohlídku mìsta s prùvodcem, promluv si se Stevem.}
{129}{}{A jé je, nìkdo dnes vstal špatnou nohou. Chci se ještì na nìco zeptat.}
{130}{}{Dobøe. Ahoj.}
{131}{}{Koho máš na mysli tím zabíjením?}
{132}{}{Radškorpiony, krysy, atd...}
{133}{}{No, tøeba nìjakého humanoida.}
{134}{}{Tebe. Chcípni, dìvko.}
{135}{}{Záporáky.}
{136}{}{Nikoho. Zapomeò na to.}
{137}{}{Kdo ti o tom øekl?? Chci øíct... samozøejmì, že ne. To je smìšné!}
{138}{}{Buï v klidu. Jacob mi o tom øekl.}
{139}{}{No, víš, ví to celé mìsto, takže už to moc tajemství není.}
{140}{}{Neboj se, nikomu to neøeknu. Mám to od spolehlivého zdroje.}
{141}{}{Co tøeba zkusit jeskynì nebo oblast kolem domù? Myslím, že tam nìjaké pøíšery jsou.}
{142}{}{Dík. Naskle.}
{143}{}{Tak humanoidy, jo? A jaké máš na mysli?}
{144}{}{Lidi.}
{145}{}{Ghouly.}
{146}{}{Mutanty.}
{147}{}{Dìlám si srandu.}
{148}{}{Jaká je tvoje definice záporáka?}
{149}{}{Každý, kdo se mi nelíbí. Vìtšinou humanoidi.}
{150}{}{Každý, kdo mi stojí v cestì.}
{151}{}{Tak rùznì.}
{152}{}{Aha, tak pokud to máš ze spolehlivého zdroje, tak to jo. Chceš snad ukonèit nadvládu mutantù ve mìstì?}
{153}{}{Jo.}
{154}{}{Ne.}
{155}{}{Tak to bych asi mìla zatoèit s lidmi, co moc mluví.}
{156}{}{[KONEC]}
{157}{}{Nepodporuju zabíjení. Teï zmiz.}
{158}{}{Jo jo... krávo.}
{159}{}{Ghoulové jsou užiteèní otroci. Sice jich tu moc není, ale nemá cenu je zabíjet. Zabíjení ghoulù nebudu podporovat.}
{160}{}{Fajn. Potøebuju ještì nìco jiného.}
{161}{}{Nevadí. Nashle.}
{162}{}{Jestli chceš opravdu zabíjet mutanty, tak si radši promluv s chemikem Jacobem.}
{163}{}{Jacobem, jo? Tak jo.}
{164}{}{Myslela jsem si to. A teï zmiz.}
{165}{}{Jasnì.}
{166}{}{V tom pøípadì jdi skrytým prùlezem v podlaze v mým pokoji. Tam dole je malé skladištì zbraní. A teï zmiz.}
{167}{}{Díky.}
{168}{}{Zrovna nedávno jsem se zbavila všech zbraní kromì tìch, který tady vidíš. Potøebuješ ještì s nìèím pomoct?}
{169}{}{Ano.}
{170}{}{Ne.}
{171}{}{S tebou obchodovat nebudu. Vypadni z mýho obchodu.}
{172}{}{[KONEC]}
{173}{}{Obchod je zavøený. Otvíráme až v 8 ráno.}
{174}{}{Hej! Odejdi odsud!}
{175}{}{Tak a dost! Teï uvidíš!}
{178}{}{Je mi fuk od koho to máš! Já se jen ujistím, že už se o tom nikdo nedozví.}
{179}{}{Hej! Nelez tam!}
{180}{}{Podruhý to opakovat nebudu. Padej odtamtud!}
{181}{}{Tak a dost! Pojï sem!}
{182}{}{S èím mì budeš ještì otravovat?}
{183}{}{Díky.}
{184}{}{Pokraèovat.}
{185}{}{Hej! Kdo to tam k èertu je?}
{186}{}{Nevím kdo jsi, ale jdu si pro tebe.}
