{100}{}{Vidíš statnou starší ženu s unaveným výrazem v obličeji.}
{101}{}{Vidíš Ardin Bucknerovou, majitelku hospody U Bucknerové.}
{102}{}{Vidíš čilou ženu ve velmi dobré kondici, které bude kolem padesáti let.}
{110}{}{Našel jste mého Smileyho. Mockrát vám děkuji! Už jsem si myslela, že je mrtvý. Jsem na něj tak naštvaná! Myslím, že už Sulika potřebovat nebudeme, když je teď Smiley zpátky.}
{111}{}{Geckon kousnout Smiley. Smiley bebí.}
{112}{}{Rádo se stalo. Jsem rád, že necháte jít Sulika.}
{113}{}{Myslím, že dá stejně přednost vám před geckony. Povězte mi ještě o něčem jiném.}
{114}{}{Nebuďte na něj tak přísná. Víte, on si to taky zrovna dvakrát neužíval. Sbohem.}
{120}{}{Slyšela jsem, že jste ublížil mému chlapci Torrovi. Nevím přesně, co se stalo, ale už vás tu nechci ani vidět. A teď vypadněte.}
{130}{}{Zdravím. Moje jméno je Ardin Bucknerová a tohle je dům Bucknerových.}
{131}{}{Blééé. Fujtajbl}
{132}{}{Pěkná, pěkná dům.}
{140}{}{Připomínáte mi mého chlapce Torra. Vsadím se, že by z vás mohli být kamarádi. Proč za ním nejdete a nepopovídáte si spolu? Sbohem.}
{150}{}{Zdravím. Moje jméno je Ardin Bucknerová a toto je můj podnik. Neviděl jste někde v okolí města lovce Smileyho? (Napůl pro sebe.) Už je pryč hrozně dlouho. Nikdy jsem mu neměla dovolit, aby odešel na tu svoji nesmyslnou výpravu.}
{151}{}{Smiley? Ne, žádného takového lovce jsem neviděl. Povězte mi o něm.}
{152}{}{Teď potřebuju něco jiného.}
{153}{}{Zdravím, Ardin. Myslím, že půjdu zase dál. Sbohem.}
{160}{}{O tom si promluvte s mojí dcerou Maidou. Moc nesleduji, co se tu poslední dobou děje. Jsem příliš zaměstnána dohlížením na svůj podnik.}
{161}{}{Aha, dobře, promluvím si s ní. Potřebuju ještě nějaké informace.}
{162}{}{Dobře, půjdu si s ní promluvit. Sbohem.}
{170}{}{Doufám, že tu nechcete něco provést. Co chcete?}
{171}{}{Jak vám mohu pomoci, příteli?}
{172}{}{Povězte mi o lovci jménem Smiley.}
{173}{}{Myslím, že vy budete ta pravá osoba, od které se dozvím nějaké místní novinky a drby.}
{174}{}{Potřebuju pokoj, prosím.}
{175}{}{Potřebujeme pokoj, prosím.}
{176}{}{Chci si něco koupit.}
{177}{}{Myslím, že teď nic nepotřebuju. Sbohem.}
{180}{}{Víte, mezi mnou a Smileym to začalo být docela vážné. Myslela jsem si, že už jsem ho konečně přesvědčila, aby se tu usadil a pomohl mi s mým podnikem. Jenže mi řekl, že musí ještě odejít na jednu výpravu.}
{181}{}{Výpravu?}
{190}{}{Nabízím tu jen pokoje. Jestli chcete něco koupit nebo vyměnit, promluvte si s mojí dcerou Maidou.}
{191}{}{Aha, dobře. Povězte mi ještě o něčem jiném.}
{192}{}{Díky. Sbohem.}
{200}{}{Máme teď plno. Lituji.}
{201}{}{Dobře, podívám se...jeden volný pokoj tu máme. Bude to za $25.}
{202}{}{Vezmu si ho. Tady je těch $25. Díky.}
{203}{}{Myslím, že ho zrovna teď nechci. Můžu se zeptat na něco jiného?}
{204}{}{Myslím, že ten pokoj vlastně nepotřebuju. Sbohem.}
{210}{}{Obávám se, že na to nemáte dost peněz.}
{211}{}{A sakra. Mám nějakou lehkou šrajtofli. Můžu se zeptat na něco jiného?}
{212}{}{Omlouvám se. Půjdu si nějaké vydělat. Sbohem.}
{220}{}{Děkuji vám. Děkuji vám za nalezení mého chlapce. Už jsem si myslela, že toho hlupáčka nikdy neuvidíme.}
{221}{}{Torr přítel.}
{222}{}{Rádo se stalo.}
{223}{}{Neříkal někdo něco o odměně?}
{230}{}{Dobře, děkuji vám. Myslím, že by se vám mohl hodit alespoň trochu chytrý společník na cesty. Promluvím s Maidou ohledně propuštění Sulika.}
{231}{}{Dobře, jen nevím, jak vám za to dostatečně poděkovat.}
{232}{}{Torr přítel }
{233}{}{Není třeba děkovat. Byla to pro mě samozřejmost.}
{234}{}{No, peníze jsou vždy dobrý způsob jak vyjádřit díky.}
{235}{}{Stačilo by, kdybyste odpustila Sulikovi dluh.}
{236}{}{. Sulik přítel?}
{240}{}{Promluvím s Maidou a ona už to se Sulikem vyřeší. Možná byste si s ní měl také promluvit.}
{241}{}{Maida pustit Sulik. Maida }
{242}{}{Děkuji vám. Myslím, že bude Sulik vděčný, když mu odpustíte jeho dluh. Půjdu si hned promluvit s Maidou. Sbohem.}
{243}{}{Jsem rád, že už Sulika nepotřebujete. Chci se ještě na něco zeptat.}
{244}{}{ přítel.}
{250}{}{Nemám toho moc, ale tady je $100. Přála bych si, abych vám mohla dát víc, ale přišli jsme o většinu brahmín, takže si víc dovolit nemohu. Je mi líto.}
{251}{}{Díky, paní Bucknerová. Sbohem.}
{252}{}{Možná bych si měl vybrat jinou odměnu.}
{260}{}{No, určitě tu musí být něco, čím bych vám mohla prokázat svoji vděčnost. Hmm, odpustím Sulikovi dluh. Může jít. Zdá se, že ne se všemi divochy jsou potíže.}
{261}{}{To zní dobře. Sbohem.}
{262}{}{Hmm, možná bych si měl vybrat jinou odměnu.}
{270}{}{Už nevím, co si mám myslet. Můj chlapec Torr se ztratil. Přeju si, aby mi ho někdo pomohl najít. Ještě nikdy nebyl pryč tak dlouho.}
{271}{}{Torr?}
{272}{}{Co se stalo?}
{273}{}{To je sice hezké, dámo, jenže teď potřebuju něco já od vás.}
{274}{}{Vidím, že máte práci. Přijdu později. Sbohem.}
{280}{}{Odešel včera večer. Dostala jsem na něj vztek po tom, co jsme ztratili několik dalších brahmín. Už si prostě nemůžeme dovolit ztratit ani jednu, ale on stále mluvil o tom, že je všechny odvlekli lido-brouci. Blázínek jeden.}
{281}{}{Torr jít kam?}
{282}{}{Myslím, že měli bratři Duntonovi něco společného se ztrácením brahmín. Neměla byste být na Torra tak přísná. Kam myslíte, že mohl jít?}
{283}{}{Kam myslíte, že mohl jít?}
{290}{}{No, pořád říkal, že hodlá jít tam, kde žijí ti lido-brouci. Víte, na východ od brahmíních pastvin leží kaňon. Nedávno se odtamtud ozývaly podivné zvuky.}
{291}{}{Zvuky?}
{300}{}{Děkuji vám, že se pokusíte najít mého chlapce. Doufám, že ho najdete. Mám o něj velký strach. Pospěšte si prosím.}
{301}{}{Dobře.}
{310}{}{Už se vám podařilo najít mého chlapce? Nevím, jak dlouho tam venku sám přežije. Prosím, najděte ho.}
{311}{}{Torr?}
{312}{}{Budu dál pátrat, ale nejdřív něco potřebuju.}
{313}{}{Jen zjišťuju, jestli se už náhodou nevrátil. Budu pokračovat v hledání. Sbohem.}
{320}{}{Torr si byl jistý, že přesně tam lido-brouci odvádějí naše brahmíny. Také říkal něco o tom, že nám chce dokázat, že není takový hlupák. Kéž by mi někdo přivedl mého chlapce zpátky.}
{321}{}{Torr kaňon. }
{322}{}{Ne jít Torr.}
{323}{}{To vypadá, že bude nejlepší začít s hledáním v tom kaňonu. Půjdu se podívat po vašem chlapci, paní Bucknerová.}
{324}{}{Strašně rád bych pomohl, jenže mám teď zrovna moc práce. Jsem si jistý, že si Torr sám poradí. Sbohem.}
{325}{}{ jít Torr.}
{330}{}{No, nazval to výpravou. Řekl mi, že asi ví, odkud se berou všichni zlatí geckoni a že to místo chce pro jistotu najít. Domníval se, že se možná jedná o nějaký druh magického pramene, nebo možná skrytou jeskyni, či nějaký druh vaultu.}
{331}{}{Hmmm.}
{340}{}{No, nevím úplně přesně, co všechno říkal, ale vypadal opravdu nadšeně. Neměla jsem ho nechat odejít. Má už dva týdny zpoždění a dělám si o něj strach.}
{341}{}{Rád pomůžu. Můžu se po něm podívat.}
{342}{}{To nerad slyším. Můžu se zeptat na něco jiného?}
{343}{}{To je opravdu nemilé, paní Bucknerová. Možná od vás jen utekl. A taky asi vím proč. Sbohem.}
{350}{}{Ach, děkuji vám. Vyznačím vám na mapě to místo, kde chtěl hledat. Pevně věřím, že ho najdete. Není dokonalý, ale pořád ho miluji a stýská se mi po něm víc, než jsem si myslela. Prosím, najděte ho.}
{351}{}{Udělám, co budu moct. Můžu se ale nejdřív na něco zeptat?}
{352}{}{Udělám pro to vše, co bude v mých silách, paní Bucknerová. Sbohem.}
{353}{}{Víte, myslím, že vám teď nemůžu pomoct. Sbohem.}
{360}{}{Už se vám podařilo najít mého Smileyho?}
{361}{}{Bohužel, paní Bucknerová. Stále po něm pátrám. Můžu se nejdřív na něco zeptat?}
{362}{}{Ne, ale právě se ho chystám hledat. Sbohem.}
{370}{}{Věděla jsem, že se mému ubohému chlapci Torrovi muselo přihodit něco strašného. Spoléhala jsem na to (vzlyk), že ho najdete, než bude pozdě. Ubohý, prostoduchý chlapec. Nechápu, proč jsem na vás spoléhala.}
{371}{}{Kéž byste mi býval pomohl najít mého ubohého chlapce Torra. Taková dobrá duše to byla a teď je určitě mrtvý. Bude mi moc chybět.}
{372}{}{Promiňte, paní Bucknerová. Udělal jsem vše, co bylo v mých silách, abych ho pro vás našel. Eh, ještě od vás něco potřebuju.}
{373}{}{Můžu vám pomoct získat jeho ostatky. Sbohem.}
{374}{}{Torr? Kdo Torr? (pokrčíš rameny) Sbohem.}
{375}{}{Je mi líto, chtěl jsem pomoct, ale nešlo to. Eh, nerad se o tom zmiňuju zrovna v takové chvíli, ale něco od vás potřebuju.}
{376}{}{Raději přijdu jindy. Sbohem.}
{380}{}{No, to mě ani nepřekvapuje. Ach ne, křičela jsem na mého ubohého chlapce, i když to nebyla jeho chyba. (vzlyk) Já ty Duntonovi dostanu. Tentokrát zašli příliš daleko.}
{381}{}{To je mi opravdu líto. Kam myslíte, že Torr šel?}
{390}{}{Dobře.}
{400}{}{What? My Smiley is...}
{401}{}{Who? Did I say Smiley? Oh, uh, no. I don't know where he went. Uh, say, let me ask you about something else.}
{402}{}{Yes, he's dead. He was eaten by geckos.}
{403}{}{I was just joking. I, uh, saw him. He said he was running off with another woman. Whoa! Look at the time. I've gotta run.}
{404}{}{Eh, já, eh, my, to je... eh, ne. Pořád po něm pátrám. Určitě se brzy objeví. Eh, sbohem.}
{410}{}{Sežrali ho geckoni? Tomu nevěřím. Geckoni by nikdy nedokázali chytit mého Smileyho, na to je příliš dobrý lovec. Určitě se mýlíte.}
{411}{}{Jo, máte nejspíš pravdu. Promiňte, že jsem vás vylekal. Můžu se zeptat na něco jiného?}
{412}{}{Kdepak, viděl jsem ho nebo spíše to, co z něj zbylo. Nebyl to hezký pohled. No, uvidíme se později. Sbohem.}
{413}{}{Tak jo, dostala jste mě. Haha, jen vás tak tahám za, eh, nohu. Jo, tak je to. No, sbohem.}
{500}{}{Myslím, že vaše brahmíny kradou bratři Duntonovi. Jen jsem myslel, že byste to měla vědět, madam.}
{510}{}{Neviděl jste někde v okolí města lovce Smileyho? (Napůl pro sebe.) Už je pryč hrozně dlouho. Nikdy jsem mu neměla dovolit, aby odešel na tu svoji nesmyslnou výpravu.}
{520}{}{Velmi jste nám tu pomohl. Díky.}
{530}{}{Jenom mě zajímá, co jiného se tu děje kolem.}
{600}{}{Jste úžasný.}
{610}{}{Jste úžasný. Přivedl jste zpět mého syna Torra i mého Smileyho. Nedokáži vám dostatečně poděkovat.}
{620}{}{Našel jste mého syna Torra. Moc vám děkuji.}
{630}{}{Našel jste mého Smileyho. Děkuji vám, moc vám děkuji.}
{640}{}{Rádo se stalo. Byla by škoda ztratit dvě osoby, které máte tak ráda.}
{650}{}{Torr jen potřebuje čas od času trochu pomoct. Jsem rád, že jsem tam byl.}
{660}{}{Smiley měl tentokrát štěstí, ale vyřiďte mu, aby si dával větší pozor.}
{670}{}{Rádo se stalo, paní Bucknerová. Můžu se ještě na něco zeptat?}
{680}{}{Gurrrrg bloop?}
{690}{}{To nestálo za řeč, madam. Sbohem.}
{700}{}{Torr je mrtvý.}
{710}{}{Smiley's dead.}
{720}{}{Já, eh, nevím, kde jsou. Můžu se na něco zeptat?}
{730}{}{Oba jsou dočista mrtví.}
{740}{}{Torr zmizel? Co tím myslíte?}
{750}{}{Nevím, kde je. Můžu se ještě na něco zeptat? Třeba se během našeho povídání vrátí.}
{760}{}{Stále po nich pátrám. Budu v tom pokračovat. Sbohem.}
{770}{}{Stále po něm pátrám. Budu v tom pokračovat. Sbohem.}
{780}{}{Já eh, nevím kde je. Hmm...páni, to je ale hodin. Musím jít.}
{790}{}{Můžu se ještě na něco zeptat?}
{800}{}{No, práce nepočká. Sbohem.}
{810}{}{Urrrrrgh.}
{900}{}{Už se vám podařilo najít mého syna Torra? Mám o něj hrozný strach.}
{910}{}{Už se vám podařilo najít mého Smileyho?}
{920}{}{Už se vám podařilo najít mého syna Torra nebo mého přítele lovce Smileyho?}
{930}{}{Můj ubohý syn Torr utekl.}
{940}{}{Nevěřím vám.}
{942}{}{Je to pravda. Teď už je z něj nejspíš potrava červů. Respektive ten zbytek, co se ještě nestačil proměnit v geckonský sračky. No, tak už to chodí. Zatím.}
{943}{}{Eh, to asi nebyl dobrý *žertík*, omlouvám se.}
{950}{}{Nechci s vámi mluvit.}
{951}{}{Zmizte odsud.}
{952}{}{Zatracení divoši. Jsou s nimi jen samé problémy.}
{953}{}{Zmiz odsud, primitive.}
{954}{}{Nechci tu někoho, jako jste vy.}
{955}{}{Nic ode mě nedostaneš, divochu.}
{956}{}{Už jste tu napáchal dost škod.}
{957}{}{Nechte mě na pokoji.}
{958}{}{Vypadni z mého podniku, domorodý potížisto.}
{959}{}{Už vás mám tak akorát dost. Vypadněte.}
