{100}{}{You see a card dealer.}
{101}{}{Vidíš "Tři karty" Monteho.}
{150}{}{Vidíš vyhublého muže s tváří spálenou od slunce. Je hubený jako proutek.}
{151}{}{Vidíš "Tři karty" Monteho. Prohlíží si ulici, zahlédne tě a přikývne.}
{152}{}{Vidíš "Tři karty" Monteho. Prohlíží si ulici, zahlédne tě a přikývne.}
{200}{}{Nechápu, jak jsem mohl prohrát...}
{201}{}{Jdi dál... Monte dnes nepracuje.}
{202}{}{Podstrčil jsem snad špatnou kartu?}
{203}{}{Jak to, že ten debilní divoch pořád vytahuje tu správnou kartu?}
{205}{}{Heeeej! Hrdino! Jseš v pohodě, jseš fakt v pohodě.}
{206}{}{::Ukáže ti vztyčený palec::}
{207}{}{::Smiles, nods::}
{208}{}{You done good, hero. You done good.}
{215}{}{Kde jsou sakra moje karty? Vždyť jsem je ještě před CHVÍLÍ měl!}
{216}{}{Zatracení skřítci klíčkožrouti, teď jdou po mejch kartách.}
{220}{}{Hej, kámo, vykašli se na kasína. Pojď si zahrát s Montem.}
{221}{}{Nechceš si trochu zariskovat, kámo? Mám nejlepší kurzy v New Renu! No ták...}
{222}{}{Hej, kámo. Vypadáš, že se na tebe lepí štěstí, pojď sem.}
{223}{}{Nechce si někdo zahrát? Rychlý prachy, rychlý prachy.}
{224}{}{Pojď sem a pojď si zahrát. Zrovna minule u mě chlápek lehce vyhrál 50 babek.}
{225}{}{Je to jednoduchý, stačí uhádnout královnu, srdcovou královnu, a vyhraješ. Až takhle jednoduchý to je.}
{226}{}{You allergic to easy money? Then get over here.}
{227}{}{Dneska každej vyhrává... chceš bejt další?}
{228}{}{Kasína tě akorát o všechno oškubou ani nevíš jak... Monte s tebou jedná fér a dá ti slušnou šanci.}
{229}{}{Nechceš si trochu zariskovat, holka? Mám nejlepší kurzy v New Renu! No ták...}
{230}{}{Jseš alergická na rychlý prachy, holka? Tak pojď jsem.}
{231}{}{Hej, holka. Vypadáš, že se na tebe lepí štěstí, pojď sem.}
{232}{}{Yo, lady, don't bother with the casinos. Come play with Monte.}
{233}{}{Monte má dneska zavřenej krám, příteli, ztratil jsem svý blbý karty.}
{234}{}{(Starý muž se usměje a kůže kolem očí se mu svraští.) Nechceš si zahrát, příteli?}
{235}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{236}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{237}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, friend?}
{238}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{239}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{240}{}{Tři Karty Monte je jméno mé a stejně tak se jmenuje i tahle hra. Práskni na stůl 20 babek a můžeme jít na to.}
{241}{}{Ty podvodník. Ty nehrát fér.}
{242}{}{Dobře. Tady peníze, já nevědět kolik být 20, tak tady hrst.}
{243}{}{Eh, já potěšen, ale já nechtít jít na TO... naaaaaskle.}
{244}{}{Odbelhat se.}
{245}{}{Let's play.}
{246}{}{Uh, get down to what?}
{247}{}{I'm familiar with the game. Let's play.}
{248}{}{Tři Karty Monte, jo? Otočíš tři karty lícem dolů, zamícháš je a já jednu vyberu. Pokud to bude ta správná karta, což nebude, protože ji podstrčíš při míchání, tak vyhraju. Ne, díky, kámo.}
{249}{}{Tři Karty Monte, jo? Otočíš tři karty lícem dolů, zamícháš je a já jednu vyberu. Pokud to bude ta správná karta, což nebude, protože ji podstrčíš při míchání, tak vyhraju. Ne, díky, kámo.}
{250}{}{Dnes ne, díky.}
{251}{}{Na co? No přece na hru!}
{252}{}{Podívej... (Ukazuje ti tři karty.) ...jedna z nich je královna. Položím je lícem dolů, zamíchám je a ty pak vybereš jednu, o které si myslíš, že je královna. Pokud uhodneš, vyhráváš.}
{253}{}{That simple, pal.}
{254}{}{That simple, lady.}
{255}{}{I'm not playing with a cheater like you.}
{256}{}{Could you explain the rules again?}
{257}{}{Sounds simple enough. Let's play. Here's 20 chips.}
{258}{}{Dnes ne, díky.}
{260}{}{(Dáš mu peníze, Monte přikývne, ukáže ti karty a poté je položí na stůl a několik vteřin s nimi míchá.)}
{261}{}{Takže... kde je královna, kámo?}
{262}{}{Takže... kde je královna, holka?}
{263}{}{(You think it's the one on the left.)}
{264}{}{(You think it's the one in the middle.)}
{265}{}{(You think it's the one on the right.)}
{266}{}{(You don't know. The cards moved too fast.)}
{267}{}{Lucka levačka.}
{268}{}{Middle of th'road}
{269}{}{Rightie tightie}
{270}{}{The one on the left.}
{271}{}{The one on the right.}
{272}{}{The one in the middle.}
{280}{}{(Monte turns over the card. It is the }
{281}{}{Promiň, kámo, smůla, ale byl jsi BLÍZKO.}
{282}{}{Promiň, holka, smůla, ale byla jsi BLÍZKO.}
{283}{}{Ale docela ti to jde. Nechceš to zkusit ještě jednou?}
{284}{}{Ty podvodník. Ty nehrát fér.}
{285}{}{Dobře. Tady peníze, já nevědět kolik být 20, tak tady hrst.}
{286}{}{Ne-e, já NELÍBIT hra. NASKLEE.}
{287}{}{I'm not playing with a cheater like you.}
{288}{}{Sure. Here's 20 chips.}
{289}{}{Ne, díky.}
{300}{}{(Dáš mu peníze, Monte přikývne, ukáže ti karty, položí je na stůl a přitom vytáhne jednu kartu tak rychle, že to nebylo skoro vidět. Poté je pár sekund míchá.)}
{301}{}{Takže... kde je královna, kámo?}
{302}{}{Takže... kde je královna, holka?}
{303}{}{Ty dát karta do rukáva ty nehrát fér.}
{304}{}{Lucka levačka.}
{305}{}{Middle of th'road}
{306}{}{Rightie tightie}
{307}{}{Ty zatracenej PODVODNÍKU, tu kartu jsi vytáhl. Vrať mi moje peníze, nebo tě zabiju přímo tady na ulici.}
{308}{}{The one in your sleeve.}
{309}{}{The one on the left.}
{310}{}{The one on the right.}
{311}{}{The one in the middle.}
{320}{}{CO JSI to říkal, kámo?}
{321}{}{WHAT did you say, lady?}
{322}{}{You accusing me of cheating?}
{323}{}{E-he. Já VĚDĚT ty podvádět.}
{324}{}{Ne-e! Ne-e! Nezlobit se. Já odcházet.}
{325}{}{Ano.}
{326}{}{Screw this. Keep the money, I'm outta here.}
{330}{}{Poslyš, nemám čas na tvůj brekot. Zaplatíš, zkusíš štěstí. Jestli chceš HRÁT dál, tak fajn, ale jestli mi tu budeš brečet, když prohraješ, tak se ztrať!}
{331}{}{ME BREAK YOU}
{332}{}{Ne-e! Ne-e! Nezlobit se. Já odcházet.}
{333}{}{That's it. You're dead.}
{334}{}{All right, all right. I'm sorry. Here's 20 chips. Let's play again.}
{335}{}{Screw you. Keep the money, I'm outta here.}
{340}{}{(Dáš mu peníze, Monte přikývne, ukáže ti karty a poté je položí na stůl a několik vteřin s nimi míchá.)}
{341}{}{Takže... kde je královna, kámo?}
{342}{}{Takže... kde je královna, holka?}
{343}{}{(Monte používá svoji normální sadu! Pro dokončení výměny musíš ukrást i jeho druhou sadu.)}
{344}{}{Ty dát karta do rukáva ty nehrát fér.}
{345}{}{Uh... Lucy leftie}
{346}{}{Eh ... zlatý střed.}
{347}{}{Uh... Rightie tightie}
{348}{}{Ty zatracenej PODVODNÍKU, tu kartu jsi vytáhl. Vrať mi moje peníze, nebo tě zabiju přímo tady na ulici.}
{349}{}{The one in your sleeve.}
{350}{}{Uh, the one on the left.}
{351}{}{Uh, the one on the right.}
{352}{}{Uh, the one in the middle.}
{360}{}{(Dáš mu peníze, Monte přikývne, ukáže ti karty a poté je položí na stůl a několik vteřin s nimi míchá.)}
{361}{}{(You hand over the cash. Monte looks uncomfortable.) Uh... all right... (Monte puts the cards on the ground and shuffles them.)}
{362}{}{Takže... kde je královna, kámo?}
{363}{}{Takže... kde je královna, holka?}
{364}{}{(Monte používá cinknutou sadu. Cokoliv vybereš je správně.)}
{365}{}{Leftie! Leftie!}
{366}{}{Rightie! Rightie!}
{367}{}{Středíček! Středíček!}
{368}{}{Oh, I don't know... the one on the left.}
{369}{}{Hmmmm... maybe the one on the right?}
{370}{}{Gee, I'm not sure... I think it's the one in the middle.}
{375}{}{(Monte otočí kartu. Je to srdcová královna. Celý šokovaně ztuhne.) Eh...? Hehe. Eh...}
{376}{}{guess you win, pal.}
{377}{}{guess you win, lady.}
{378}{}{(He hands over the cash reluctantly.)}
{379}{}{Again! Again!}
{380}{}{Thanx me go now}
{381}{}{Zahrajeme si ještě jednou? No tak, Monte, teprve se rozjíždím.}
{382}{}{Well, thanks, Monte. See you later.}
{385}{}{(Monte otočí kartu. Je to srdcová královna. Vypadá šokovaně.) Eh...? Hehe. Eh...}
{386}{}{guess you win, pal.}
{387}{}{guess you win, lady.}
{388}{}{That cleans me out, though... (Looks at you weakly) Anything else I could do for you?}
{389}{}{Nic. Já jenom chtít zkušenosti navíc. Ahoj. Ahoj.}
{390}{}{What have you GOT?}
{391}{}{Why don't you give me some information?}
{392}{}{Forget it, Monte. We'll call it even for today.}
{400}{}{(Vypadá mrzutě.) Eh... no, něco bych tu měl... ale má to MNOHEM větší cenu než tvoje výhra... takže...}
{401}{}{Well? What is it?}
{402}{}{Jestli to má pro tebe větší cenu než umírat v Golgotě kvůli nezaplacení dluhu, to už je tvůj problém, ale být tebou, tak si to promyslím.}
{404}{}{Eh... hmnnn... to záleží na tom, co chceš vědět.}
{405}{}{Nevíš, kdo oddělal Wrightovic kluka? Kdo ho donutil předávkovat se Jetem?}
{406}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{407}{}{You know where my car is, Monte?}
{408}{}{Nevíš o nějaké zajímavé informaci?}
{409}{}{Nevermind, Monte. We're even. See you later.}
{415}{}{No... poslyš, ode mě to nemáš, ale vsadím se, že to byl ten sráč Renesco, co prodává léky v Obchodní čtvrti. Nevím jistě, jestli TO prodal tomu klukovi, ale určitě něco ví. To je všechno.}
{416}{}{All right then, Monte. We're even.}
{420}{}{Eh... no... (Zdá se, že bojuje se svým svědomím.) ...poslyš, ode mě to nemáš, ale bejt tebou, tak se podívám do suterénu v podniku Desperado.}
{421}{}{All right then, Monte. We're even.}
{425}{}{(Zamhouří očima a nakloní se k tobě.) Zeptal bych se starýho Julese v ulici Panen. Nic mu neunikne... a POKUD ano, tak v tom má prsty. Chápeš, co tím myslím?}
{426}{}{All right then, Monte. We're even.}
{430}{}{No... znáš Eldridge, co má obchod se zbraněmi Lovecké potřeby? Tvrdí, že upravuje zbraně, ale v životě jsem ho neviděl pracovat. Možná by stálo za to omrknout jeho obchod... ale ode mě to nemáš.}
{431}{}{All right then, Monte. We're even.}
{435}{}{(Monte se na tebe zamračí.) Poslyš, dneska už žádný hry, jasný? Odpal.}
{436}{}{Can I buy that card you showed me before?}
{437}{}{I wanted some information...}
{438}{}{All right, Monte. I'll leave... for now.}
{440}{}{Ne. Ten ti nedám. Tečka. Je to PRAVÁ předválečná památka... kousek historie. Prostě NE.}
{441}{}{Děláš mi DALŠÍ nabídku? Podívej, řekl jsem ti, že ho neprodám.}
{442}{}{Co takhle tisíc babek? Mám je tady u sebe. Dej mi ty karty a jsou tvoje.}
{443}{}{Not even for 750 chips?}
{444}{}{How about 500 chips?}
{445}{}{250 babek by stačilo?}
{446}{}{Dobře. Mám ještě pár otázek...}
{447}{}{Nevermind then, Monte. I'm outta here.}
{450}{}{Sedíš si na uších? Takový směšný sumy mě nezajímají.}
{451}{}{How about I suggest another amount...?}
{452}{}{Chci se ještě zeptat...}
{453}{}{Nevermind then, Monte. I'm outta here.}
{460}{}{No, zase až TAK mi na něm nezáleží. Je tvůj, kámo. (Rychle se podívá nalevo a napravo, poté se sehne a sundá si botu. Odšroubuje patu a z dutiny uvnitř vyndá balíček karet.) Tady ho máš a dávej na něj pozor.}
{461}{}{Chci se ještě zeptat...}
{462}{}{Thanks, Monte. Always a pleasure.}
{465}{}{(Zamračí se.) To záleží na tom, co chceš vědět. A taky to nebude laciný.}
{466}{}{Nevíš, kdo oddělal Wrightovic kluka? Kdo ho donutil předávkovat se Jetem?}
{467}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{468}{}{You know where my car is, Monte?}
{469}{}{Nevíš o nějaké zajímavé informaci?}
{470}{}{Nevermind then, Monte. I'm outta here.}
{475}{}{U Golgoty, tohohle tématu se v žádným případě ani NEDOTKNU. Jdi do hajzlu.}
{476}{}{Poslyš, tohle téma přináší jen samý trable. Nech to bejt, jo?}
{477}{}{Děláš mi další nabídku? Podívej, řekl jsem ti, že o tom NEBUDU mluvit.}
{478}{}{A thousand chips change your mind? I got it with me.}
{479}{}{Not even for 750 chips?}
{480}{}{How about 500 chips?}
{481}{}{250 babek by stačilo?}
{482}{}{Uh... Golgotha?}
{483}{}{Chci se ještě zeptat...}
{484}{}{Nevermind then, Monte. I'm outta here.}
{490}{}{(Zakroutí hlavou.) V žádným případě. Mluvit o něčem takovým je k smrti nebezpečný, obzvlášť pro mě. Zapomeň na to.}
{491}{}{Co když ti nabídnu tohle...}
{492}{}{Chci se ještě zeptat...}
{493}{}{Nevermind then, Monte. I'm outta here.}
{495}{}{Eh... no... to je hodně peněz. (Olizuje si rty. Vypadá to, že nad tím hodně přemýšlí... ale jen nakrátko.) Poslyš, ode mě to nemáš...}
{496}{}{Understood. Go on.}
{500}{}{(Ušklíbne se.) Možná jsem něco slyšel, možná taky ne. Řekni cenu.}
{501}{}{All right... talk a price.}
{502}{}{How about a thousand chips? I got it with me.}
{503}{}{Not even for 750 chips?}
{504}{}{How about 500 chips?}
{505}{}{250 babek by stačilo?}
{506}{}{Chci se ještě zeptat...}
{507}{}{Nevermind then, Monte. I'm outta here.}
{510}{}{Ha! Tak za to si nekoupím ani pytel sraček. Zapomeň na to.}
{511}{}{Co když ti nabídnu tohle...}
{512}{}{Chci se ještě zeptat...}
{513}{}{Nevermind then, Monte. I'm outta here.}
{515}{}{Noooo, to je tak akorát. (Zlomyslně se ušklíbne.) Poslyš, ode mě to nemáš, ale být tebou, tak se zajdu podívat do suterénu v podniku Desperado v ulici Panen. Je tam hodně "krys", jestli mi rozumíš.}
{516}{}{Chci se ještě zeptat...}
{517}{}{Rozumím. Díky.}
{520}{}{(Pokrčí rameny.) Možná o něčem vím, možná taky ne. Řekni cenu a třeba ti něco povím.}
{521}{}{All right... talk a price.}
{522}{}{How about a thousand chips? I got it with me.}
{523}{}{Not even for 750 chips?}
{524}{}{How about 500 chips?}
{525}{}{250 babek by stačilo?}
{526}{}{Chci se ještě zeptat...}
{527}{}{Nevermind then, Monte. I'm outta here.}
{530}{}{(Zamhouří očima a nakloní se k tobě.) Tak za tenhle obnos vím leda tak kulový.}
{531}{}{Co když ti nabídnu tohle...}
{532}{}{Chci se ještě zeptat...}
{533}{}{Nevermind then, Monte. I'm outta here.}
{535}{}{To je tak akorát... (Zamhouří očima a nakloní se k tobě.) ...zeptal bych se starýho Julese v ulici Panen. Nic mu neunikne... a POKUD ano, tak v tom má prsty. Chápeš, co tím myslím?}
{536}{}{Chci se ještě zeptat...}
{537}{}{All right then, Monte. Thanks.}
{540}{}{(Pokrčí rameny.) Slyším věci, vidím věci. Za 200 babek se mi možná osvěží paměť, jestli mi rozumíš.}
{541}{}{Here's 200 chips.}
{542}{}{I'll give you 150.}
{543}{}{100 chips or nothing.}
{544}{}{Chci se ještě zeptat...}
{545}{}{Nevermind then, Monte. I'm outta here.}
{550}{}{Sedíš si na uších? ŘÍKÁM 200 babek a myslím to vážně.}
{551}{}{All right. Here's 200 chips.}
{552}{}{Chci se ještě zeptat...}
{553}{}{Nevermind then, Monte. I'm outta here.}
{555}{}{Done. (Monte leans in) Well, know that guy Eldridge, runs New Reno Arms? He SAYS he does
 weapon upgrades, but I never see him do any work. You might want to check out his place... but you didn't hear that from me.}
{556}{}{Chci se ještě zeptat...}
{557}{}{Understood. Thanks, Monte.}
{560}{}{To je pohřebiště jižně od města. Smrdí to tam jak v prdeli.}
{561}{}{Oh... I see. Now, about the Wright kid...}
{562}{}{Forget the Wright kid. I had some other questions...}
{563}{}{All right then, Monte. Thanks.}
{565}{}{Vsadím se, že to byl ten starej kretén, co prodává léky v Obchodní čtvrti. Nevím jistě, jestli TO prodal tomu klukovi, ale určitě něco ví. To je všechno.}
{566}{}{Chci se ještě zeptat...}
{567}{}{All right then, Monte. Thanks.}
{570}{}{(Rychle se podívá nalevo a napravo, poté se sehne a sundá si botu. Odšroubuje patu a z dutiny uvnitř vyndá balíček karet... na kartě je muž v podivném klobouku držící palici.) Máš zájem? Je to pravá předválečná památka.}
{571}{}{Ne, už mám plný inventář... raději bych místo toho nějakou informaci.}
{572}{}{Eh, jasně. Proč ne? To urovná věci mezi námi.}
{573}{}{Sorry pal, no chips, no game. Come back when you got more money.}
{574}{}{Sorry lady, no chips, no game. Come back when you got more money.}
{575}{}{Yeah, maybe next time then.}
{576}{}{Podařilo se ti rychle vyměnit Monteho sadu karet za cinknutou sadu karet.}
{600}{}{spades}
{601}{}{hearts}
{602}{}{diamonds}
{603}{}{clubs}
{604}{}{dva}
{605}{}{tři}
{606}{}{čtyři}
{607}{}{pět}
{608}{}{šest}
{609}{}{sedm}
{610}{}{osm}
{611}{}{devět}
{612}{}{deset}
{613}{}{ }
