{100}{}{You see a card dealer.}
{101}{}{Vidíš "Tři karty" Monteho.}
{150}{}{Vidíš vyhublého muže s tváří spálenou od slunce. Je hubený jako proutek.}
{151}{}{Vidíš "Tři karty" Monteho. Prohlíží si ulici, zahlédne tě a přikývne.}
{152}{}{Vidíš "Tři karty" Monteho. Prohlíží si ulici, zahlédne tě a přikývne.}
{200}{}{Nechápu, jak jsem mohl prohrát...}
{201}{}{Jdi dál... Monte dnes nepracuje.}
{202}{}{Did I palm the wrong card?}
{203}{}{How did that stupid tribal keep picking the right card?}
{205}{}{Heeeej! Hrdino! Jseš v pohodě, jseš fakt v pohodě.}
{206}{}{::Ukáže ti vztyčený palec::}
{207}{}{::Smiles, nods::}
{208}{}{You done good, hero. You done good.}
{215}{}{Kde jsou sakra moje karty? Vždyť jsem je ještě před CHVÍLÍ měl!}
{216}{}{Goddamn car key gnomes, now they're going after my playing cards.}
{220}{}{Hej, kámo, vykašli se na kasína. Pojď si zahrát s Montem.}
{221}{}{Looking to take a chance, pal? Best odds in New Reno! C'mon...}
{222}{}{You, pal. You look like a lucky guy, c'mon over.}
{223}{}{Anybody looking to play? Free mon-ay, free mon-ay.}
{224}{}{C'mon over and play. Just the other day, I guy won 50 chips off me, easy.}
{225}{}{Easy, just guess the Queen, red Queen, and you win. That easy.}
{226}{}{You allergic to easy money? Then get over here.}
{227}{}{Everybody's winning today... you want to be the next one?}
{228}{}{Casinos'll rip you off, rob you blind... Monte treats you right, gives you a fair chance.}
{229}{}{Looking to take a chance, lady? Best odds in New Reno! C'mon...}
{230}{}{You allergic to easy money, lady? Then get over here.}
{231}{}{You, lady. You look like a lucky gal, c'mon over.}
{232}{}{Yo, lady, don't bother with the casinos. Come play with Monte.}
{233}{}{Monte má dneska zavřenej krám, příteli, ztratil jsem svý blbý karty.}
{234}{}{(Starý muž se usměje a kůže kolem očí se mu svraští.) Nechceš si zahrát, příteli?}
{235}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{236}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{237}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, friend?}
{238}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{239}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{240}{}{Three-Card Monte's the name, and the game's the same as the name. Slap down 20 chips, and we'll get down to it.}
{241}{}{You cheater. You no play fair}
{242}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{243}{}{Uh, me flattered but me not want to get down to it now... byyyyye}
{244}{}{Odbelhat se.}
{245}{}{Let's play.}
{246}{}{Uh, get down to what?}
{247}{}{I'm familiar with the game. Let's play.}
{248}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{249}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{250}{}{Dnes ne, díky.}
{251}{}{Na co? No přece na hru!}
{252}{}{See... (shows you three cards) ...one of these is a queen. I lay them face down, shuffle them, then you pick which one the queen is. If you're right, you win.}
{253}{}{That simple, pal.}
{254}{}{That simple, lady.}
{255}{}{I'm not playing with a cheater like you.}
{256}{}{Could you explain the rules again?}
{257}{}{Sounds simple enough. Let's play. Here's 20 chips.}
{258}{}{Dnes ne, díky.}
{260}{}{(Dáš mu peníze, Monte přikývne, ukáže ti karty a poté je položí na stůl a několik vteřin s nimi míchá.)}
{261}{}{So... which one's the queen, pal?}
{262}{}{So... which one's the queen, lady?}
{263}{}{(You think it's the one on the left.)}
{264}{}{(You think it's the one in the middle.)}
{265}{}{(You think it's the one on the right.)}
{266}{}{(You don't know. The cards moved too fast.)}
{267}{}{Lucy leftie}
{268}{}{Middle of th'road}
{269}{}{Rightie tightie}
{270}{}{The one on the left.}
{271}{}{The one on the right.}
{272}{}{The one in the middle.}
{280}{}{(Monte turns over the card. It is the }
{281}{}{Sorry, pal, not this time, but you were CLOSE.}
{282}{}{Sorry, lady, not this time, but you were CLOSE.}
{283}{}{You sure do got the eye for it, though. Wanna try again?}
{284}{}{You cheater. You no play fair}
{285}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{286}{}{Nuh-uh Me no LIKE game BYYYYE}
{287}{}{I'm not playing with a cheater like you.}
{288}{}{Sure. Here's 20 chips.}
{289}{}{Ne, díky.}
{300}{}{(Dáš mu peníze, Monte přikývne, ukáže ti karty, položí je na stůl a přitom vytáhne jednu kartu tak rychle, že to nebylo skoro vidět. Poté je pár sekund míchá.)}
{301}{}{So... which one's the queen, pal?}
{302}{}{So... which one's the queen, lady?}
{303}{}{You put it in sleevie weevie you no play fair}
{304}{}{Lucy leftie}
{305}{}{Middle of th'road}
{306}{}{Rightie tightie}
{307}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{308}{}{The one in your sleeve.}
{309}{}{The one on the left.}
{310}{}{The one on the right.}
{311}{}{The one in the middle.}
{320}{}{CO JSI to říkal, kámo?}
{321}{}{WHAT did you say, lady?}
{322}{}{You accusing me of cheating?}
{323}{}{Uh-uh. Me KNOW you cheet}
{324}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{325}{}{Ano.}
{326}{}{Screw this. Keep the money, I'm outta here.}
{330}{}{Poslyš, nemám čas na tvůj brekot. Zaplatíš, zkusíš štěstí. Jestli chceš HRÁT dál, tak fajn, ale jestli mi tu budeš brečet, když prohraješ, tak se ztrať!}
{331}{}{ME BREAK YOU}
{332}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{333}{}{That's it. You're dead.}
{334}{}{All right, all right. I'm sorry. Here's 20 chips. Let's play again.}
{335}{}{Screw you. Keep the money, I'm outta here.}
{340}{}{(Dáš mu peníze, Monte přikývne, ukáže ti karty a poté je položí na stůl a několik vteřin s nimi míchá.)}
{341}{}{So... which one's the queen, pal?}
{342}{}{So... which one's the queen, lady?}
{343}{}{(Monte's using his normal deck! You need to steal his other deck to complete the switch.)}
{344}{}{You put it in sleevie weevie you no play fair}
{345}{}{Uh... Lucy leftie}
{346}{}{Uh... Middle of th'road}
{347}{}{Uh... Rightie tightie}
{348}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{349}{}{The one in your sleeve.}
{350}{}{Uh, the one on the left.}
{351}{}{Uh, the one on the right.}
{352}{}{Uh, the one in the middle.}
{360}{}{(Dáš mu peníze, Monte přikývne, ukáže ti karty a poté je položí na stůl a několik vteřin s nimi míchá.)}
{361}{}{(You hand over the cash. Monte looks uncomfortable.) Uh... all right... (Monte puts the cards on the ground and shuffles them.)}
{362}{}{So... which one's the queen, pal?}
{363}{}{So... which one's the queen, lady?}
{364}{}{(Monte's using the marked deck. Any pick is the right one.)}
{365}{}{Leftie! Leftie!}
{366}{}{Rightie! Rightie!}
{367}{}{Middlie! Middlie!}
{368}{}{Oh, I don't know... the one on the left.}
{369}{}{Hmmmm... maybe the one on the right?}
{370}{}{Gee, I'm not sure... I think it's the one in the middle.}
{375}{}{(Monte otočí kartu. Je to srdcová královna. Celý šokovaně ztuhne.) Eh...? Hehe. Eh...}
{376}{}{guess you win, pal.}
{377}{}{guess you win, lady.}
{378}{}{(He hands over the cash reluctantly.)}
{379}{}{Again! Again!}
{380}{}{Thanx me go now}
{381}{}{So we gonna play again or what? C'mon, Monte. I'm just getting started.}
{382}{}{Well, thanks, Monte. See you later.}
{385}{}{(Monte otočí kartu. Je to srdcová královna. Vypadá šokovaně.) Eh...? Hehe. Eh...}
{386}{}{guess you win, pal.}
{387}{}{guess you win, lady.}
{388}{}{That cleans me out, though... (Looks at you weakly) Anything else I could do for you?}
{389}{}{Nuttin. Me just wanted sum extra EXP. Bye. Bye.}
{390}{}{What have you GOT?}
{391}{}{Why don't you give me some information?}
{392}{}{Forget it, Monte. We'll call it even for today.}
{400}{}{(Vypadá mrzutě.) Eh... no, něco bych tu měl... ale má to MNOHEM větší cenu než tvoje výhra... takže...}
{401}{}{Well? What is it?}
{402}{}{If it's worth more to you than dying on Golgotha because you welched on a debt, that's your problem. I'd think
 about it, if I were you.}
{404}{}{Eh... hmnnn... to záleží na tom, co chceš vědět.}
{405}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{406}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{407}{}{You know where my car is, Monte?}
{408}{}{Got anything you think I should know?}
{409}{}{Nevermind, Monte. We're even. See you later.}
{415}{}{No... poslyš, ode mě to nemáš, ale vsadím se, že to byl ten sráč Renesco, co prodává léky v Obchodní čtvrti. Nevím jistě, jestli TO prodal tomu klukovi, ale určitě něco ví. To je všechno.}
{416}{}{All right then, Monte. We're even.}
{420}{}{Eh... no... (Zdá se, že bojuje se svým svědomím.) ...poslyš, ode mě to nemáš, ale bejt tebou, tak se podívám do suterénu v podniku Desperado.}
{421}{}{All right then, Monte. We're even.}
{425}{}{(Zamhouří očima a nakloní se k tobě.) Zeptal bych se starýho Julese v ulici Panen. Nic mu neunikne... a POKUD ano, tak v tom má prsty. Chápeš, co tím myslím?}
{426}{}{All right then, Monte. We're even.}
{430}{}{No... znáš Eldridge, co má obchod se zbraněmi Lovecké potřeby? Tvrdí, že upravuje zbraně, ale v životě jsem ho neviděl pracovat. Možná by stálo za to omrknout jeho obchod... ale ode mě to nemáš.}
{431}{}{All right then, Monte. We're even.}
{435}{}{(Monte se na tebe zamračí.) Poslyš, dneska už žádný hry, jasný? Odpal.}
{436}{}{Can I buy that card you showed me before?}
{437}{}{I wanted some information...}
{438}{}{All right, Monte. I'll leave... for now.}
{440}{}{Ne. Ten ti nedám. Tečka. Je to PRAVÁ předválečná památka... kousek historie. Prostě NE.}
{441}{}{You making me ANOTHER offer? Look, I told you I ain't selling it.}
{442}{}{How about a thousand chips? I got it with me. It's yours in exchange for that card.}
{443}{}{Not even for 750 chips?}
{444}{}{How about 500 chips?}
{445}{}{250 chips sound about right?}
{446}{}{Dobře. Mám ještě pár otázek...}
{447}{}{Nevermind then, Monte. I'm outta here.}
{450}{}{Sedíš si na uších? Takový směšný sumy mě nezajímají.}
{451}{}{How about I suggest another amount...?}
{452}{}{Chci se ještě zeptat...}
{453}{}{Nevermind then, Monte. I'm outta here.}
{460}{}{No, zase až TAK mi na něm nezáleží. Je tvůj, kámo. (Rychle se podívá nalevo a napravo, poté se sehne a sundá si botu. Odšroubuje patu a z dutiny uvnitř vyndá balíček karet.) Tady ho máš a dávej na něj pozor.}
{461}{}{Chci se ještě zeptat...}
{462}{}{Thanks, Monte. Always a pleasure.}
{465}{}{(Zamračí se.) To záleží na tom, co chceš vědět. A taky to nebude laciný.}
{466}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{467}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{468}{}{You know where my car is, Monte?}
{469}{}{Got anything you think I should know?}
{470}{}{Nevermind then, Monte. I'm outta here.}
{475}{}{U Golgoty, tohohle tématu se v žádným případě ani NEDOTKNU. Jdi do hajzlu.}
{476}{}{Look, that subject's just bad news. Leave it alone, all right?}
{477}{}{You making me another offer? Look, I told you I AIN'T going talk about it.}
{478}{}{A thousand chips change your mind? I got it with me.}
{479}{}{Not even for 750 chips?}
{480}{}{How about 500 chips?}
{481}{}{250 chips sound about right?}
{482}{}{Uh... Golgotha?}
{483}{}{Chci se ještě zeptat...}
{484}{}{Nevermind then, Monte. I'm outta here.}
{490}{}{(Zakroutí hlavou.) V žádným případě. Mluvit o něčem takovým je k smrti nebezpečný, obzvlášť pro mě. Zapomeň na to.}
{491}{}{How about if I offered you this...}
{492}{}{Chci se ještě zeptat...}
{493}{}{Nevermind then, Monte. I'm outta here.}
{495}{}{Eh... no... to je hodně peněz. (Olizuje si rty. Vypadá to, že nad tím hodně přemýšlí... ale jen nakrátko.) Poslyš, ode mě to nemáš...}
{496}{}{Understood. Go on.}
{500}{}{(Ušklíbne se.) Možná jsem něco slyšel, možná taky ne. Řekni cenu.}
{501}{}{All right... talk a price.}
{502}{}{How about a thousand chips? I got it with me.}
{503}{}{Not even for 750 chips?}
{504}{}{How about 500 chips?}
{505}{}{250 chips sound about right?}
{506}{}{Chci se ještě zeptat...}
{507}{}{Nevermind then, Monte. I'm outta here.}
{510}{}{Ha! Tak za to si nekoupím ani pytel sraček. Zapomeň na to.}
{511}{}{How about if I offered you this...}
{512}{}{Chci se ještě zeptat...}
{513}{}{Nevermind then, Monte. I'm outta here.}
{515}{}{Noooo, to je tak akorát. (Zlomyslně se ušklíbne.) Poslyš, ode mě to nemáš, ale být tebou, tak se zajdu podívat do suterénu v podniku Desperado v ulici Panen. Je tam hodně "krys", jestli mi rozumíš.}
{516}{}{Chci se ještě zeptat...}
{517}{}{Rozumím. Díky.}
{520}{}{(Pokrčí rameny.) Možná o něčem vím, možná taky ne. Řekni cenu a třeba ti něco povím.}
{521}{}{All right... talk a price.}
{522}{}{How about a thousand chips? I got it with me.}
{523}{}{Not even for 750 chips?}
{524}{}{How about 500 chips?}
{525}{}{250 chips sound about right?}
{526}{}{Chci se ještě zeptat...}
{527}{}{Nevermind then, Monte. I'm outta here.}
{530}{}{(Zamhouří očima a nakloní se k tobě.) Tak za tenhle obnos vím leda tak kulový.}
{531}{}{How about if I offered you this...}
{532}{}{Chci se ještě zeptat...}
{533}{}{Nevermind then, Monte. I'm outta here.}
{535}{}{To je tak akorát... (Zamhouří očima a nakloní se k tobě.) ...zeptal bych se starýho Julese v ulici Panen. Nic mu neunikne... a POKUD ano, tak v tom má prsty. Chápeš, co tím myslím?}
{536}{}{Chci se ještě zeptat...}
{537}{}{All right then, Monte. Thanks.}
{540}{}{(Pokrčí rameny.) Slyším věci, vidím věci. Za 200 babek se mi možná osvěží paměť, jestli mi rozumíš.}
{541}{}{Here's 200 chips.}
{542}{}{I'll give you 150.}
{543}{}{100 chips or nothing.}
{544}{}{Chci se ještě zeptat...}
{545}{}{Nevermind then, Monte. I'm outta here.}
{550}{}{Sedíš si na uších? ŘÍKÁM 200 babek a myslím to vážně.}
{551}{}{All right. Here's 200 chips.}
{552}{}{Chci se ještě zeptat...}
{553}{}{Nevermind then, Monte. I'm outta here.}
{555}{}{Done. (Monte leans in) Well, know that guy Eldridge, runs New Reno Arms? He SAYS he does
 weapon upgrades, but I never see him do any work. You might want to check out his place... but you didn't hear that from me.}
{556}{}{Chci se ještě zeptat...}
{557}{}{Understood. Thanks, Monte.}
{560}{}{To je pohřebiště jižně od města. Smrdí to tam jak v prdeli.}
{561}{}{Oh... I see. Now, about the Wright kid...}
{562}{}{Forget the Wright kid. I had some other questions...}
{563}{}{All right then, Monte. Thanks.}
{565}{}{Vsadím se, že to byl ten starej kretén, co prodává léky v Obchodní čtvrti. Nevím jistě, jestli TO prodal tomu klukovi, ale určitě něco ví. To je všechno.}
{566}{}{Chci se ještě zeptat...}
{567}{}{All right then, Monte. Thanks.}
{570}{}{(Rychle se podívá nalevo a napravo, poté se sehne a sundá si botu. Odšroubuje patu a z dutiny uvnitř vyndá balíček karet... na kartě je muž v podivném klobouku držící palici.) Máš zájem? Je to pravá předválečná památka.}
{571}{}{No, I already have enough inventory items... I'd rather have some information instead.}
{572}{}{Uh, sure. Why not? This'll settle things between us.}
{573}{}{Sorry pal, no chips, no game. Come back when you got more money.}
{574}{}{Sorry lady, no chips, no game. Come back when you got more money.}
{575}{}{Yeah, maybe next time then.}
{576}{}{You quickly swap Monte's deck of cards for the marked deck.}
{600}{}{spades}
{601}{}{hearts}
{602}{}{diamonds}
{603}{}{clubs}
{604}{}{dva}
{605}{}{tři}
{606}{}{čtyři}
{607}{}{pět}
{608}{}{šest}
{609}{}{sedm}
{610}{}{osm}
{611}{}{devět}
{612}{}{deset}
{613}{}{ }
