{100}{}{Vidíš "Tøi karty" Monteho.}
{150}{}{Vidíš vyhublého mue s tváøí spálenou od slunce. Je hubenı jako proutek.}
{200}{}{Nechápu, jak jsem mohl prohrát...}
{205}{}{Heeeej! Hrdino! Jseš v pohodì, jseš fakt v pohodì.}
{215}{}{Kde jsou sakra moje karty? Vdy jsem je ještì pøed CHVÍLÍ mìl!}
{220}{}{Hej, kámo, vykašli se na kasína. Pojï si zahrát s Montem.}
{230}{}{Monte má dneska zavøenej krám, pøíteli, ztratil jsem svı blbı karty.}
{231}{}{(Starı mu se usmìje a kùe kolem oèí se mu svraští.) Nechceš si zahrát, pøíteli?}
{250}{}{Na co? No pøece na hru!}
{260}{}{(Dáš mu peníze, Monte pøikıvne, ukáe ti karty a poté je poloí na stùl a nìkolik vteøin s nimi míchá.)}
{280}{}{(Monte turns over the card. It is the two of spades.)}
{300}{}{(Dáš mu peníze, Monte pøikıvne, ukáe ti karty, poloí je na stùl a pøitom vytáhne jednu kartu tak rychle, e to nebylo skoro vidìt. Poté je pár sekund míchá.)}
{320}{}{CO JSI to øíkal, kámo?}
{330}{}{Poslyš, nemám èas na tvùj brekot. Zaplatíš, zkusíš štìstí. Jestli chceš HRÁT dál, tak fajn, ale jestli mi tu budeš breèet, kdy prohraješ, tak se ztra!}
{340}{}{(Dáš mu peníze, Monte pøikıvne, ukáe ti karty a poté je poloí na stùl a nìkolik vteøin s nimi míchá.)}
{360}{}{(Dáš mu peníze, Monte pøikıvne, ukáe ti karty a poté je poloí na stùl a nìkolik vteøin s nimi míchá.)}
{375}{}{(Monte otoèí kartu. Je to srdcová královna. Celı šokovanì ztuhne.) Eh...? Hehe. Eh...}
{385}{}{(Monte otoèí kartu. Je to srdcová královna. Vypadá šokovanì.) Eh...? Hehe. Eh...}
{400}{}{(Vypadá mrzutì.) Eh... no, nìco bych tu mìl... ale má to MNOHEM vìtší cenu ne tvoje vıhra... take...}
{405}{}{Eh... hmnnn... to záleí na tom, co chceš vìdìt.}
{415}{}{No... poslyš, ode mì to nemáš, ale vsadím se, e to byl ten sráè Renesco, co prodává léky v Obchodní ètvrti. Nevím jistì, jestli TO prodal tomu klukovi, ale urèitì nìco ví. To je všechno.}
{420}{}{Eh... no... (Zdá se, e bojuje se svım svìdomím.) ...poslyš, ode mì to nemáš, ale bejt tebou, tak se podívám do suterénu v podniku Desperado.}
{425}{}{(Zamhouøí oèima a nakloní se k tobì.) Zeptal bych se starıho Julese v ulici Panen. Nic mu neunikne... a POKUD ano, tak v tom má prsty. Chápeš, co tím myslím?}
{430}{}{No... znáš Eldridge, co má obchod se zbranìmi Lovecké potøeby? Tvrdí, e upravuje zbranì, ale v ivotì jsem ho nevidìl pracovat. Moná by stálo za to omrknout jeho obchod... ale ode mì to nemáš.}
{435}{}{(Monte se na tebe zamraèí.) Poslyš, dneska u ádnı hry, jasnı? Odpal.}
{440}{}{Ne. Ten ti nedám. Teèka. Je to PRAVÁ pøedváleèná památka... kousek historie. Prostì NE.}
{450}{}{Sedíš si na uších? Takovı smìšnı sumy mì nezajímají.}
{460}{}{No, zase a TAK mi na nìm nezáleí. Je tvùj, kámo. (Rychle se podívá nalevo a napravo, poté se sehne a sundá si botu. Odšroubuje patu a z dutiny uvnitø vyndá balíèek karet.) Tady ho máš a dávej na nìj pozor.}
{465}{}{(Zamraèí se.) To záleí na tom, co chceš vìdìt. A taky to nebude lacinı.}
{475}{}{U Golgoty, tohohle tématu se v ádnım pøípadì ani NEDOTKNU. Jdi do hajzlu.}
{490}{}{(Zakroutí hlavou.) V ádnım pøípadì. Mluvit o nìèem takovım je k smrti nebezpeènı, obzvláš pro mì. Zapomeò na to.}
{495}{}{Eh... no... to je hodnì penìz. (Olizuje si rty. Vypadá to, e nad tím hodnì pøemıšlí... ale jen nakrátko.) Poslyš, ode mì to nemáš...}
{500}{}{(Ušklíbne se.) Moná jsem nìco slyšel, moná taky ne. Øekni cenu.}
{510}{}{Ha! Tak za to si nekoupím ani pytel sraèek. Zapomeò na to.}
{515}{}{Noooo, to je tak akorát. (Zlomyslnì se ušklíbne.) Poslyš, ode mì to nemáš, ale bıt tebou, tak se zajdu podívat do suterénu v podniku Desperado v ulici Panen. Je tam hodnì "krys", jestli mi rozumíš.}
{520}{}{(Pokrèí rameny.) Moná o nìèem vím, moná taky ne. Øekni cenu a tøeba ti nìco povím.}
{530}{}{(Zamhouøí oèima a nakloní se k tobì.) Tak za tenhle obnos vím leda tak kulovı.}
{535}{}{To je tak akorát... (Zamhouøí oèima a nakloní se k tobì.) ...zeptal bych se starıho Julese v ulici Panen. Nic mu neunikne... a POKUD ano, tak v tom má prsty. Chápeš, co tím myslím?}
{540}{}{(Pokrèí rameny.) Slyším vìci, vidím vìci. Za 200 babek se mi moná osvìí pamì, jestli mi rozumíš.}
{550}{}{Sedíš si na uších? ØÍKÁM 200 babek a myslím to vánì.}
{555}{}{Beru. (Monte se k tobì nakloní.) Znáš Eldridge, co má obchod se zbranìmi Lovecké potøeby? Tvrdí, e upravuje zbranì, ale v ivotì jsem ho nevidìl pracovat. Moná by stálo za to omrknout jeho obchod... ale ode mì to nemáš.}
{560}{}{To je pohøebištì jinì od mìsta. Smrdí to tam jak v prdeli.}
{565}{}{Vsadím se, e to byl ten starej kretén, co prodává léky v Obchodní ètvrti. Nevím jistì, jestli TO prodal tomu klukovi, ale urèitì nìco ví. To je všechno.}
{570}{}{(Rychle se podívá nalevo a napravo, poté se sehne a sundá si botu. Odšroubuje patu a z dutiny uvnitø vyndá balíèek karet... na kartì je mu v podivném klobouku drící palici.) Máš zájem? Je to pravá pøedváleèná památka.}
