{100}{}{Vidíš Drahouška Nikki.}
{125}{}{Vidíš jednu z rozdávaček karet v kasínu.}
{150}{}{Vidíš Drahouška Nikki.}
{151}{}{You see Darlin' Nikki. She winks at you.}
{152}{}{Vidíš Drahouška Nikki. Naznačuje ti, ať jdeš blíž a zahraješ si.}
{153}{}{You see Darlin' Nikki. Mason was right about her ass.}
{154}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{155}{}{You see Darlin' Nikki. Mason was right about her ass.}
{156}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{160}{}{Vidíš Drahouška Nikki. Naznačuje ti, ať jdeš blíž a zahraješ si.}
{161}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{162}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{170}{}{Vidíš jednu z rozdávaček karet v kasínu.}
{171}{}{Vidíš jednu z rozdávaček karet v kasínu. Mrká na tebe.}
{172}{}{Vidíš jednu z rozdávaček karet v kasínu. Naznačuje ti, ať jdeš blíž a zahraješ si.}
{173}{}{Vidíš jednu z rozdávaček karet v kasínu. Má opravdu hezké nohy.}
{174}{}{Vidíš jednu z rozdávaček karet v kasínu. Její šaty sotva zakrývají její tělo.}
{175}{}{Vidíš jednu z rozdávaček karet v kasínu. Voní opravdu nááádherně.}
{180}{}{Vidíš jednu z rozdávaček karet v kasínu. Naznačuje ti, ať jdeš blíž a zahraješ si.}
{181}{}{Vidíš jednu z rozdávaček karet v kasínu. Její šaty sotva zakrývají její tělo.}
{182}{}{Vidíš jednu z rozdávaček karet v kasínu. Její šaty sotva zakrývají její tělo.}
{183}{}{Vidíš jednu z rozdávaček karet v kasínu. Naznačuje ti, ať jdeš blíž a zahraješ si.}
{200}{}{::Fandí::}
{201}{}{::Tleská::}
{202}{}{::Píská::}
{203}{}{! Vítej v kasínu, hrdino!}
{204}{}{Thought you'd forgotten about us while you were saving the world.}
{210}{}{Ahoj, }
{211}{}{Jestli hledáš společnost na večer...}
{212}{}{Hey, you...(winks)...you looking to gamble?}
{213}{}{Vypadá tak... (Zachvěje se.) ...nebezpečně.}
{214}{}{Vítej v kasínu, }
{215}{}{Nepřimluvíte se za mě u šéfa?}
{216}{}{Zdravím, madam. Dejte mi vědet, až budete potřebovat s něčím pomoci.}
{217}{}{Nechcete si zahrát, madam?}
{218}{}{Vypadá tak... (Zachvěje se.) ...nebezpečně.}
{220}{}{Vypadáte jako někdo, kdo každodenně riskuje svůj život.}
{221}{}{Eh, myslím, že právě vešel do špatného kasína...}
{222}{}{Jestli neodejde dřív, než ho zahlédnou gorily...}
{223}{}{A sakra. Problém...}
{224}{}{Vypadáte jako někdo, kdo každodenně riskuje svůj život.}
{225}{}{Eh, myslím, že právě vešla do špatného kasína...}
{226}{}{Jestli neodejde dřív, než ji zahlédnou gorily...}
{230}{}{Ahoj, svalovče, nechceš utratit nějaké peníze?}
{231}{}{Hey, champ...(winks)...you looking to gamble?}
{232}{}{Hey, champ...(smiles)...wanna take a chance?}
{233}{}{Jestli hledáš společnost na večer...}
{234}{}{Přemýšlím, jestli si s ním mám promluvit...}
{235}{}{Nazdar, }
{236}{}{Jestli chcete vyhrát nějaké peníze, tak jste na správné adrese.}
{237}{}{Nejlepší kasíno v New Renu. Dokonce na celém SVĚTĚ.}
{238}{}{Dnes je tu s námi Paní Štěstěna... dnes vyhrává každý!}
{239}{}{Přistup blíže, }
{240}{}{Nechceš ještě něco k pití?}
{241}{}{Vítej v kasínu, }
{242}{}{Ahoj, }
{243}{}{Nechceš si zahrát, }
{244}{}{Vítej v kasínu, }
{250}{}{Ahoj, filmová hvězdo. Nechceš utratit nějaké peníze?}
{251}{}{Nazdar, }
{252}{}{Nazdar, }
{253}{}{Jestli chceš vyhrát nějaké peníze }
{254}{}{Nejlepší kasíno v New Renu. Dokonce na celém SVĚTĚ.}
{255}{}{Dnes je tu s námi Paní Štěstěna... dnes vyhrává každý!}
{266}{}{Přistup blíže, }
{267}{}{Nechceš ještě něco k pití?}
{268}{}{Vítej v kasínu, }
{269}{}{Hey there, Mrs. Movie Star. Looking to spend a paycheck?}
{270}{}{Zdravím, zlato. Nechcete utratit nějaké peníze?}
{271}{}{Hey, sweetie...(winks)...you looking to gamble?}
{272}{}{Hey, sweetie...(smiles)...wanna take a chance?}
{273}{}{Jestli chcete vyhrát nějaké peníze, tak jste na správné adrese.}
{274}{}{Nejlepší kasíno v New Renu. Dokonce na celém SVĚTĚ.}
{275}{}{Dnes je tu s námi Paní Štěstěna... dnes vyhrává každý!}
{276}{}{Přistupte blíže a vyhrajte nějaké peníze.}
{277}{}{Nechcete ještě něco k pití, drahoušku?}
{278}{}{Vítejte v kasínu, drahoušku.}
{279}{}{Jestli si chcete zahrát, tak je tento stůl volný...}
{280}{}{Zdravím, zlato. Nechcete utratit nějaké peníze?}
{281}{}{Nechcete si zahrát, drahoušku?}
{282}{}{Vítejte v kasínu, drahoušku.}
{290}{}{No, jste blázen, když tu jste, ale... vložte svoji sázku. Minimální částka je 5 babek. Vložte svoji sázku...}
{291}{}{Um... place your bets... minimum bet 5 chips. Place your bets...}
{292}{}{Place your bet, sir. Minimum bet 5 chips. Place your bets...}
{293}{}{Place your bet, ma'am. Minimum bet 5 chips. Place your bets...}
{294}{}{Place your bets, minimum bet 5 chips. Place your bets...}
{295}{}{Já lepší než ty.}
{296}{}{Já hrát kostky o kalhota.}
{297}{}{What this game? Can you bet Gecko skin? Me got geck... ooooh... pretty lights over there!}
{298}{}{Bet 5 chips?}
{299}{}{Bet 15 chips?}
{300}{}{Bet 25 chips?}
{301}{}{Bet 50 chips?}
{302}{}{You Nikki?}
{303}{}{How you doing, Nikki?}
{304}{}{Whoa, too rich for my blood. I'm outta here.}
{305}{}{Dnes nesázím, díky.}
{310}{}{Eh, dobře, pane. Přijďte zase.}
{311}{}{Eh, dobře, madam. Přijďte zase.}
{312}{}{Eh... slyšela jsem, že vzadu rozdávají mozky. Možná nebude špatný nápad, když se tam zajdete podívat.}
{313}{}{Naaaskleeee.}
{314}{}{Jupí. }
{315}{}{Uh... brains... what them?}
{320}{}{Dobře, pane. Přijďte zase.}
{321}{}{Dobře, madam. Přijďte zase.}
{322}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{323}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{324}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{325}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{326}{}{Přijdu, díky.}
{327}{}{To je možné, ale aspoň tady nebydlím.}
{330}{}{Je mi líto, pane. Snad budete mít příště více štěstí.}
{331}{}{Je mi líto, madam. Snad budete mít příště více štěstí.}
{332}{}{Je mi líto. Snad budete mít příště více štěstí.}
{333}{}{You have [C] chips. Keep playing?}
{334}{}{Pro dnešek skončit.}
{335}{}{Pro dnešek skončit.}
{340}{}{Výhra! Gratuluji, pane!}
{341}{}{Winner! Well done, ma'am!}
{342}{}{Winner!}
{343}{}{You have [C] chips. Keep playing?}
{344}{}{Pro dnešek skončit.}
{345}{}{Pro dnešek skončit.}
{350}{}{Výhra! Zdvojnásobil jste své peníze! Gratuluji, pane!}
{351}{}{Výhra! Zdvojnásobila jste své peníze! Gratuluji, madam!}
{352}{}{Výhra! Zdvojnásobil jste své peníze!}
{353}{}{You have [C] chips. Keep playing?}
{354}{}{Pro dnešek skončit.}
{355}{}{Pro dnešek skončit.}
{360}{}{Výhra! Ztrojnásobila jste své peníze! Dnes se na vás lepí štěstí! Gratuluji, madam!}
{361}{}{Vítěz! Ztrojnásobila jste svoje peníze!!! Máte ale dnes štěstí, madam.}
{362}{}{Výhra! Ztrojnásobil jste své peníze!}
{363}{}{You have [C] chips. Keep playing?}
{364}{}{Pro dnešek skončit.}
{365}{}{Pro dnešek skončit.}
{370}{}{Co chcete? Budete jen plýtvat mým časem, nebo si vsadíte?}
{371}{}{Jsem kdokoliv jen budete CHTÍT, zlato. Takže, vsadíte si?}
{372}{}{Jsem kdokoliv jen budete CHTÍT, slečno. Takže, vsadíte si?}
{373}{}{Place a bet.}
{374}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{375}{}{Jo. Vsadím se, že jste s Hezounem Lloydem okrádali pana Salvatora. Těžko uvěřit, že jste si nevšimla, že neustále podváděl.}
{376}{}{Znáte někoho jménem Hezoun Lloyd?}
{377}{}{We'll talk later, Nikki.}
{380}{}{Jo, slyšela jsem, že je MRTVÝ. To jste chtěl slyšet, vy vrahu?! Co?! Vsadíte si už, nebo budete dál kecat hovadiny?}
{381}{}{Nope. You gonna place a bet?}
{382}{}{Place a bet.}
{383}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{384}{}{Jo. Vsadím se, že jste s Hezounem Lloyd okrádali pana Salvatora. Těžko uvěřit, že jste si nevšimla, že neustále podváděl.}
{385}{}{We'll talk later, Nikki.}
{390}{}{V tom případě byste tu sázku PROHRÁL, zlato, ale jestli jste stejně tak blbý jako ošklivý, tak byste si stejně vsadil. Neviděla jsem toho pobudu od té doby, co podvedl pana Salvatora.}
{391}{}{Then that's a bet you'd lose, sweetheart. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{392}{}{Then that's a bet you'd lose, girlfriend. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{393}{}{Možná jste mě napoprvé neslyšela, takže to ještě jednou zopakuju: Kde je Lloyd?}
{394}{}{To je velmi podezřelé, že jste si nevšimla, že neustále podváděl. Musela byste být slepá... nebo podplacená.}
{395}{}{Fine. We'll talk later, Nikki.}
{400}{}{Zlato, ŘEKLA jsem vám, že nevím, kde je. Podívejte, já tady PRACUJI, takže se vraťte do té své jeskyně...}
{401}{}{Girlfriend, I TOLD you that I don't know where he is. Now, look, I'm WORKING here, so go back to whatever rock you --}
{402}{}{Nikki, Nikki... ztrácím TRPĚLIVOST. Jestli mi neřeknete, kde je Lloyd, tak ztratím i své zábrany.}
{403}{}{Nikki, nevím, co se stalo mezi vámi a Lloydem, ale víte co? NEPOTŘEBUJU to vědět. Stačí, když panu Salvatorovi povím o svém podezření.}
{404}{}{Nikki, vím, že jste pomáhala Lloydovi podvádět. Řekněte mi, kde je a já vám dám polovinu z toho, co si odtud odnesl: 500 babek.}
{405}{}{To je velmi podezřelé, že jste si nevšimla, že neustále podváděl. Musela byste být slepá... nebo podplacená.}
{406}{}{We'll talk later then, Nikki.}
{410}{}{Dotkněte se mě a pan Salvatore vás stáhne zaživa z kůže.}
{411}{}{Salvatore vás neochrání. Rozdavačů karet, jako jste vy, jsou tucty. Vyserte se na ty kecy a řekněte mi, kde je Lloyd, NEBO...}
{412}{}{Salvatore vás neochrání. Je mrtvý. Vyserte se na ty kecy a řekněte mi, kde je Lloyd, NEBO...}
{413}{}{Nikki, vím, že jste pomáhala Lloydovi podvádět. Řekněte mi, kde je a já vám dám polovinu z toho, co si odtud odnesl: 500 babek.}
{414}{}{To je velmi podezřelé, že jste si nevšimla, že neustále podváděl. Musela byste být slepá... nebo podplacená.}
{415}{}{We'll talk later then, Nikki.}
{420}{}{O čem to mluvíš?}
{421}{}{Nikki, jestli mi teď všechno neřeknete, řeknu panu Salvatorovi, že v tom jedete taky, ať už je to pravda nebo ne. Řekne Masonovi, ať vás naporcuje a rozemele do sekané a vaše pozice bude do hodiny obsazená někým jiným.}
{422}{}{Nikki, vím, že jste pomáhala Lloydovi podvádět. Řekněte mi, kde je a já vám dám polovinu z toho, co si odtud odnesl: 500 babek.}
{423}{}{To je velmi podezřelé, že jste si nevšimla, že neustále podváděl. Musela byste být slepá... nebo podplacená.}
{424}{}{We'll talk later then, Nikki.}
{430}{}{Podívejte, JAK JSEM ŘEKLA, já nevím kde je. Ale *možná* jsem zaslechla, že měl kdysi pokoj u Desperada. Možná tam něco najdete. A pokud mě omluvíte, vrátím se zpět ke své práci.}
{431}{}{Nikki, vím, že jste pomáhala Lloydovi podvádět. Řekněte mi, kde je a já vám dám polovinu z toho, co si odtud odnesl: 500 babek.}
{432}{}{To je velmi podezřelé, že jste si nevšimla, že neustále podváděl. Musela byste být slepá... nebo podplacená.}
{433}{}{We'll talk later then, Nikki.}
{440}{}{Podívejte, ZAČALA jsem tu pracovat teprve nedávno a ještě neodhalím každého počítače karet a vychytralého podvodníka, co sem přijde. Také mám kliku na takové blbce, jako jste vy.}
{441}{}{Aha, tak takhle jste se dali s Lloydem dohromady, jo?}
{442}{}{Takže jste tu právě začala pracovat, jo? Velmi příhodné. No, to bude asi všechno. Řekněte Lloydovi, že je mrtvý muž.}
{443}{}{Nikki, vím, že jste pomáhala Lloydovi podvádět. Řekněte mi, kde je a já vám dám polovinu z toho, co si odtud odnesl: 500 babek.}
{444}{}{We'll talk later then, Nikki.}
{450}{}{No jasně, šlehnete si trochu Jetu a všechno se najednou zdá podezřelé, že?}
{451}{}{Tohle JE podezřelé. Měla jste odhadnout, co je Lloyd zač v momentě, kdy se objevil v tomhle kasínu.}
{452}{}{Nikki, vím, že jste pomáhala Lloydovi podvádět. Řekněte mi, kde je a já vám dám polovinu z toho, co si odtud odnesl: 500 babek.}
{453}{}{We'll talk later then, Nikki.}
{460}{}{A teď odsud ihned vypadněte. Už vám nemám co říct.}
{461}{}{I got nothing to say to you. Get out of here.}
{462}{}{Teď možná ne. Promluvíme si později, Nikki. Počítejte s tím.}
{470}{}{Mluvíte tak přesvědčivě... ale to každá svině. MOŽNÁ vím, kde je Lloyd, MOŽNÁ nevím. Máte 500 babek?}
{471}{}{Maybe. Depends on what you got for me.}
{480}{}{MOŽNÁ, že Lloyd má stále můj podíl a nejsem si jistá, že mi ho dá. Takže MOŽNÁ vám za 500 babek povím, kde se právě teď skrývá.}
{481}{}{Platí. Tady máte 500 babek. Řekněte mi, kde je.}
{482}{}{To je pěkně přehnaná cena za samé "asi" a "možná". Najdu si ho sám.}
{483}{}{I don't have enough chips, but I'll be back. You better still be here when I return.}
{490}{}{(Vezme si úplatek.) Podívejte se do kotelny v suterénu podniku Desperado. Tam by se ten zkurvysyn měl schovávat, kdyby se to profláklo.}
{491}{}{All right then. Later, Nikki.}
{500}{}{Nechcete odsud už vypadnout?! Nesmí nás vidět, že spolu takhle mluvíme, jinak se to ROZKŘIKNE. Rozumíte?}
{501}{}{All right then. Later, Nikki.}
{510}{}{Jděte k čertu! Už vám nic neřeknu. NIKDY.}
{511}{}{To je opravdu škoda. Mějte se, Nikki.}
{600}{}{Podařilo se ti podplatit Nikki, aby ti řekla, kde se Lloyd pravděpodobně skrývá.}
{1210}{}{. Can I help you with... anything?}
{1214}{}{.}
{1235}{}{. Nechceš utratit nějaké peníze?}
{1239}{}{, a vyhraj nějaké peníze.}
{1241}{}{.}
{1242}{}{. Dej mi vědet, až budeš potřebovat s něčím pomoci.}
{1243}{}{?}
{1244}{}{.}
{1251}{}{...(winks)...you looking to gamble?}
{1252}{}{...(smiles)...wanna take a chance?}
{1253}{}{, you came to the right place.}
{1266}{}{, a vyhraj nějaké peníze.}
{1268}{}{.}
{1314}{}{ could always use new inventory item}
{2699}{}{Tancuješ dnes?}
