{100}{}{Vidíš Drahouška Nikki.}
{125}{}{Vidíš jednu z rozdávaček karet v kasínu.}
{150}{}{Vidíš Drahouška Nikki.}
{160}{}{Vidíš Drahouška Nikki. Naznačuje ti, ať jdeš blíž a zahraješ si.}
{170}{}{Vidíš jednu z rozdávaček karet v kasínu.}
{180}{}{Vidíš jednu z rozdávaček karet v kasínu. Naznačuje ti, ať jdeš blíž a zahraješ si.}
{200}{}{::Fandí::}
{210}{}{Zdravím [MM]. Můžu vám s *něčím* pomoct?}
{220}{}{Vypadáte jako někdo, kdo každodenně riskuje svůj život.}
{230}{}{Ahoj, svalovče, nechceš utratit nějaké peníze?}
{250}{}{Ahoj, filmová hvězdo. Nechceš utratit nějaké peníze?}
{270}{}{Zdravím, zlato. Nechcete utratit nějaké peníze?}
{290}{}{No, jste blázen, když tu jste, ale... vložte svoji sázku. Minimální částka je 5 babek. Vložte svoji sázku...}
{310}{}{Eh, dobře, pane. Přijďte zase.}
{320}{}{Dobře, pane. Přijďte zase.}
{330}{}{Je mi líto, pane. Snad budete mít příště více štěstí.}
{340}{}{Výhra! Gratuluji, pane!}
{350}{}{Výhra! Zdvojnásobil jste své peníze! Gratuluji, pane!}
{360}{}{Výhra! Ztrojnásobila jste své peníze! Dnes se na vás lepí štěstí! Gratuluji, madam!}
{370}{}{Co chcete? Budete jen plýtvat mým časem, nebo si vsadíte?}
{380}{}{Jo, slyšela jsem, že je MRTVÝ. To jste chtěl slyšet, vy vrahu?! Co?! Vsadíte si už, nebo budete dál kecat hovadiny?}
{390}{}{V tom případě byste tu sázku PROHRÁL, zlato, ale jestli jste stejně tak blbý jako ošklivý, tak byste si stejně vsadil. Neviděla jsem toho pobudu od té doby, co podvedl pana Salvatora.}
{400}{}{Zlato, ŘEKLA jsem vám, že nevím, kde je. Podívejte, já tady PRACUJI, takže se vraťte do té své jeskyně...}
{410}{}{Dotkněte se mě a pan Salvatore vás stáhne zaživa z kůže.}
{420}{}{O čem to mluvíš?}
{430}{}{Podívejte, JAK JSEM ŘEKLA, já nevím kde je. Ale *možná* jsem zaslechla, že měl kdysi pokoj u Desperada. Možná tam něco najdete. A pokud mě omluvíte, vrátím se zpět ke své práci.}
{440}{}{Podívejte, ZAČALA jsem tu pracovat teprve nedávno a ještě neodhalím každého počítače karet a vychytralého podvodníka, co sem přijde. Také mám kliku na takové blbce, jako jste vy.}
{450}{}{No jasně, šlehnete si trochu Jetu a všechno se najednou zdá podezřelé, že?}
{460}{}{A teď odsud ihned vypadněte. Už vám nemám co říct.}
{470}{}{Mluvíte tak přesvědčivě... ale to každá svině. MOŽNÁ vím, kde je Lloyd, MOŽNÁ nevím. Máte 500 babek?}
{480}{}{MOŽNÁ, že Lloyd má stále můj podíl a nejsem si jistá, že mi ho dá. Takže MOŽNÁ vám za 500 babek povím, kde se právě teď skrývá.}
{490}{}{(Vezme si úplatek.) Podívejte se do kotelny v suterénu podniku Desperado. Tam by se ten zkurvysyn měl schovávat, kdyby se to profláklo.}
{500}{}{Nechcete odsud už vypadnout?! Nesmí nás vidět, že spolu takhle mluvíme, jinak se to ROZKŘIKNE. Rozumíte?}
{510}{}{Jděte k čertu! Už vám nic neřeknu. NIKDY.}
