{100}{}{Vidíš Drahouška Nikki.}
{125}{}{Vidíš jednu z rozdávaèek karet v kasínu.}
{150}{}{Vidíš Drahouška Nikki.}
{160}{}{Vidíš Drahouška Nikki. Naznaèuje ti, a jdeš blí a zahraješ si.}
{170}{}{Vidíš jednu z rozdávaèek karet v kasínu.}
{180}{}{Vidíš jednu z rozdávaèek karet v kasínu. Naznaèuje ti, a jdeš blí a zahraješ si.}
{200}{}{::Fandí::}
{210}{}{Hello, [MM]. Can I help you with... anything?}
{220}{}{Vypadáte jako nìkdo, kdo kadodennì riskuje svùj ivot.}
{230}{}{Ahoj, svalovèe, nechceš utratit nìjaké peníze?}
{250}{}{Ahoj, filmová hvìzdo. Nechceš utratit nìjaké peníze?}
{270}{}{Zdravím, zlato. Nechcete utratit nìjaké peníze?}
{290}{}{No, jste blázen, kdy tu jste, ale... vlote svoji sázku. Minimální èástka je 5 babek. Vlote svoji sázku...}
{310}{}{Eh, dobøe, pane. Pøijïte zase.}
{320}{}{Dobøe, pane. Pøijïte zase.}
{330}{}{Je mi líto, pane. Snad budete mít pøíštì více štìstí.}
{340}{}{Vıhra! Gratuluji, pane!}
{350}{}{Vıhra! Zdvojnásobil jste své peníze! Gratuluji, pane!}
{360}{}{Vıhra! Ztrojnásobila jste své peníze! Dnes se na vás lepí štìstí! Gratuluji, madam!}
{370}{}{Co chcete? Budete jen plıtvat mım èasem, nebo si vsadíte?}
{380}{}{Jo, slyšela jsem, e je MRTVİ. To jste chtìl slyšet, vy vrahu?! Co?! Vsadíte si u, nebo budete dál kecat hovadiny?}
{390}{}{V tom pøípadì byste tu sázku PROHRÁL, zlato, ale jestli jste stejnì tak blbı jako ošklivı, tak byste si stejnì vsadil. Nevidìla jsem toho pobudu od té doby, co podvedl pana Salvatora.}
{400}{}{Zlato, ØEKLA jsem vám, e nevím, kde je. Podívejte, já tady PRACUJI, take se vrate do té své jeskynì...}
{410}{}{Dotknìte se mì a pan Salvatore vás stáhne zaiva z kùe.}
{420}{}{O èem to mluvíš?}
{430}{}{Podívejte, JAK JSEM ØEKLA, já nevím kde je. Ale *moná* jsem zaslechla, e mìl kdysi pokoj u Desperada. Moná tam nìco najdete. A pokud mì omluvíte, vrátím se zpìt ke své práci.}
{440}{}{Podívejte, ZAÈALA jsem tu pracovat teprve nedávno a ještì neodhalím kadého poèítaèe karet a vychytralého podvodníka, co sem pøijde. Také mám kliku na takové blbce, jako jste vy.}
{450}{}{No jasnì, šlehnete si trochu Jetu a všechno se najednou zdá podezøelé, e?}
{460}{}{A teï odsud ihned vypadnìte. U vám nemám co øíct.}
{470}{}{Mluvíte tak pøesvìdèivì... ale to kadá svinì. MONÁ vím, kde je Lloyd, MONÁ nevím. Máte 500 babek?}
{480}{}{MONÁ, e Lloyd má stále mùj podíl a nejsem si jistá, e mi ho dá. Take MONÁ vám za 500 babek povím, kde se právì teï skrıvá.}
{490}{}{(Vezme si úplatek.) Podívejte se do kotelny v suterénu podniku Desperado. Tam by se ten zkurvysyn mìl schovávat, kdyby se to profláklo.}
{500}{}{Nechcete odsud u vypadnout?! Nesmí nás vidìt, e spolu takhle mluvíme, jinak se to ROZKØIKNE. Rozumíte?}
{510}{}{Jdìte k èertu! U vám nic neøeknu. NIKDY.}
