{100}{}{Vidíš šéfa spodního patra kasína.}
{150}{}{Vidíš dobøe obleèeného muže. Hlídá kasíno.}
{151}{}{Vidíš šéfa spodního patra kasína. Hlídá kasíno.}
{200}{}{Eh... budete si muset sundat tu zbroj.}
{201}{}{Eh, pane... nebo madam... budete si muset sundat tu zbroj.}
{202}{}{Pane... madam... tohle nemùžete nosit v kasínu.}
{205}{}{Eh, proè se tady tak plížíte, pane?}
{206}{}{Eh, jste snad v utajení, pane?}
{210}{}{Eh, proè se tady tak plížíte, madam?}
{211}{}{Eh, jste snad v utajení, madam?}
{215}{}{Dobrý veèer, }
{216}{}{Brý veèer, }
{220}{}{Dobrý veèer, }
{221}{}{Brý veèer, }
{225}{}{Dobrý den, }
{230}{}{Dobrý den, }
{235}{}{Jseš ve špatným kasínu, pøíteli.}
{236}{}{Mìla bys radši odejít. Hned.}
{237}{}{Jestli tu zùstaneš, hazarduješ se svým životem. Radši odejdi.}
{238}{}{Jseš ve špatným kasínu, dìvko.}
{245}{}{Je mi líto, pane, ale tu zbraò budete muset dát pryè.}
{250}{}{Je mi líto, madam, ale tu zbraò budete muset dát pryè.}
{255}{}{Do tohohle kasína nemùžeš se zbranìmi, zlato. Hehe... už tak jsi smrtící i bez nich.}
{260}{}{S takovouhle figurou se nikam neproplížíš, zlato.}
{265}{}{Radši bys mìl tu zbraò schovat, divochu. HNED.}
{270}{}{Divochu, pøestaò se tu kurva plížit. HNED.}
{275}{}{Nazdar, nazdar... Myrone! Už jsem tì dlouho nevidìl vylízt z laboratoøe.}
{276}{}{Jdeš vyzkoušet to nový 'zboží', Myrone?}
{277}{}{Nazdar! Pojï dovnitø, Myrone.}
{280}{}{Jasnì. Co chceš vìdìt?}
{281}{}{Fooooooo foo foo fooooo.}
{282}{}{Odbelhat se.}
{283}{}{Kdo jsi?}
{284}{}{Co je tohle za kasíno?}
{285}{}{Mùžeš mi øíct nìco o tomhle kasínu?}
{286}{}{Znáte nìkoho jménem Hezoun Lloyd?}
{287}{}{Kdo je ten starý chlapík támhle u toho automatu?}
{288}{}{Ten váš komik je ubohý. Nebude ti vadit, když to zkusím?}
{289}{}{Díky. Nepotøebujete taneènici na dnešní veèer? Mohla bych dìlat na polovièní úvazek.}
{290}{}{Díky, jdu si s ním promluvit.}
{291}{}{Nic, díky. Promiò, že obtìžuju.}
{292}{}{Jenom se tak dívám. Pokraèuj dál.}
{295}{}{Droidùm vstup zakázán.}
{296}{}{Droidy neobsluhujeme.}
{297}{}{Žádní droidi. Musí poèkat venku.}
{300}{}{Eh, mìl byste radìji odejít, pane.}
{301}{}{Eh, mìla byste radìji odejít, madam.}
{302}{}{Vypadni odsud, retarde.}
{303}{}{Máma øíkat já výjimešná!}
{304}{}{Odbelhat se.}
{305}{}{Nemìl bych se sice vykecávat pøi práci, ale jsem rád, že Enklávì koneènì nìkdo nakopal prdel.}
{306}{}{Nazdar, }
{315}{}{Jo, to mi tvoje máma taky øekla. A teï zmiz... tøeba ji najdeš nìkde na ulici Panen.}
{316}{}{Jo dobøe! Pá pá.}
{317}{}{Odbelhat se.}
{325}{}{Jsem šéf tohohle patra. Co pro tebe mùžu udìlat?}
{326}{}{Šéfuju tomuhle patru kasína. Jestli nìco potøebuješ, staèí øíct.}
{327}{}{Co je tohle za kasíno?}
{328}{}{Mùžeš mi øíct nìco o tomhle kasínu?}
{329}{}{Nic, díky. Promiò, že obtìžuju.}
{335}{}{Tohle je [CN]. Nìco chceš, ptej se.}
{336}{}{This is [CN]. At least, last time I checked the sign outside the door. Now what can I do for you?}
{337}{}{Kdo jsi?}
{338}{}{Mùžeš mi øíct nìco o tomhle kasínu?}
{339}{}{Nic, díky. Promiò, že obtìžuju.}
{340}{}{Co pro tebe mùžu udìlat, kámo?}
{341}{}{Co pro tebe mùžu udìlat, zlato?}
{342}{}{Fooooooo foo foo fooooo.}
{343}{}{Odbelhat se.}
{344}{}{Kdo jsi?}
{345}{}{Tohle je zatracenì nejlepší kasíno ve mìstì... no, možná trochu pøeháním. Chceš vìdìt ještì nìco?}
{346}{}{Tohle je zatracenì nejlepší kasíno ve mìstì a má zatracenì nejlepší stoly... nechceš si je jít vyzkoušet?}
{347}{}{Kdo jsi?}
{348}{}{Komu patøí tohle kasíno?}
{349}{}{Dobøe, díky. Promiò, že obtìžuju.}
{350}{}{Díky. Nepotøebujete taneènici na dnešní veèer? Mohla bych dìlat na polovièní úvazek.}
{351}{}{Díky, jdu si s ním promluvit.}
{352}{}{Nic, díky. Promiò, že obtìžuju.}
{353}{}{Jenom se tak dívám. Pokraèuj dál.}
{355}{}{[CA] rodina. Vložili do toho velké množství práce a udìlali z toho skvìlý noèní podnik, opravdový diamant New Rena.}
{356}{}{The [CA] Family. That a problem? Cause if you ain't here to gamble, then this ain't the place for you. Understand?}
{357}{}{Kdo jsi?}
{358}{}{Mùžeš mi øíct nìco o tomhle kasínu?}
{359}{}{Rozumím. Díky za tvùj èas.}
{360}{}{Podívejte kdo tu je! Nazdar, }
{361}{}{. Welcome to [CN]. Love your films.}
{362}{}{Fooooooo foo foo fooooo.}
{363}{}{Odbelhat se.}
{364}{}{Kdo jsi?}
{365}{}{Ten dìdek? Starej McGee? Je to naprostý blázen... hraje na tom automatu už nìkolik let a èeká na velký jackpot. Naházel do nìj všechny svoje úspory, jenže mu nikdy nedal ani drobák.}
{366}{}{Ten dìdek? Starej McGee? Je to naprostý blázen, to je jisté. Hehe. Byl pìknì naštvaný, když jsi vyhrál jeho peníze. Dávej si na nìj pozor.}
{367}{}{Je ten automat nìjak... cinknutý?}
{368}{}{Chci se ještì zeptat...}
{369}{}{Díky za informace.}
{370}{}{Díky, to mi lichotí. Jdu jen tak kolem.}
{375}{}{Ne, jenom tvrdohlavý... stejnì jako on. Potøebuje trochu opravit, jenže nemáme žádného mechanika, který by tomu rozumìl.}
{376}{}{Chci se ještì zeptat...}
{377}{}{Zajímavé. Díky za informace.}
{385}{}{Jo, ten parchant sem pøišel minulý týden, vybral u jednoho stolu nìkolik tisíc babek a pak zmizel. Nevím, kde teï je, ale míval pokoj v Desperadu.}
{386}{}{Jo, nìjaký chlápek s tímhle jménem mìl pronajatý jeden z pokojù v patøe... èíslo 204. Mìl ho zaplacený, ale pøed pár dny zmizel a nikdo ho nevidìl odejít.}
{387}{}{Pan Salvatore se zmínil, že Lloyd vyhrál peníze od jednoho konkrétního dealera. Nevíš, kdo to byl?}
{388}{}{Chci se ještì zeptat...}
{389}{}{Díky za informace.}
{395}{}{Myslíš Nikki? Jo, je zrovna támhle, u prostøedního stolu. Je snad v nìjakém maléru?}
{396}{}{Ne, není. Jenom se s ní chci seznámit. Mám ještì nìjaké otázky...}
{397}{}{Díky za informace.}
{405}{}{Její jméno BYLO Nikki. Pracovala tu, ale nìkdo ji oddìlal... není to tak dlouho.}
{406}{}{Hmmm. Nebude ti vadit, když se zeptám ještì na nìco jiného?}
{407}{}{Zajímavé. Díky za informace.}
{415}{}{Jmenovala se Nikki. Pracovala tu, ale nedávno odešla. Prostì si sbalila svých pár švestek a znièehonic zmizela.}
{416}{}{Nebude ti vadit, když se zeptám ještì na nìco jiného?}
{417}{}{Zajímavé. Díky za informace.}
{425}{}{Jasnì, to bude dobré pro kšefty. Šatna je vzadu...}
{426}{}{Skvìle. Budu na jevišti za pár minut...}
{427}{}{Teï ne. Chci se ještì zeptat...}
{428}{}{Teï nemùžu, ale ještì se vrátím.}
{435}{}{Ne, ještì jsme se nedostali z tvého posledního vystoupení. Zkus to v jiném kasínu.}
{436}{}{Tak dobøe, díky. Mám ještì nìjaké otázky...}
{437}{}{Dobøe... ale myslím, že se ještì vrátím.}
{445}{}{You count up the evening's tally. chips. Not a bad haul.}
{446}{}{The leather was a nice touch.}
{447}{}{That ball gag you had with you didn't hurt, either.}
{448}{}{I'll do even better next time...}
{455}{}{Jo, smrdí hùø než brahmíní hovno. A ty myslíš, že...? Ále, proè ne? Malé zlepšení by neškodilo, ale pøiprav se na to, že tohle je opravdu drsné publikum... doufám, že jsi dobrý.}
{456}{}{Jsem pøímo vynikající... dívej.}
{1215}{}{, pane.}
{1216}{}{, pane.}
{1220}{}{, madam.}
{1221}{}{, madam.}
{1225}{}{, pane.}
{1230}{}{, madam.}
{1306}{}{. Odpoèiò si od záchrany svìta a trochu se pobav.}
