{100}{}{Vidíš počítačový terminál.}
{101}{}{Vidíš terminál s hlasovým rozhraním.}
{102}{}{Vidíš běžný počítačový terminál upravený pro hlasové povely.}
{103}{}{Zkoumáš počítačový terminál, ale nevidíš, že by s ním bylo něco špatně. Co uděláš?}
{104}{}{Udeříš ho 'speciálním' způsobem.}
{105}{}{Kopneš ho do 'speciálního' místa.}
{106}{}{Spustíš diagnostický program.}
{107}{}{Otevřeš ho a podíváš se dovnitř.}
{108}{}{Necháš ho být.}
{109}{}{Chvíli zíráš na konzoli a vybíráš nejvhodnější místo, kam zasadit úder. Poté, co ho zasáhneš svým nejlepším úderem typu 'to opraví vše', monitor několikrát problikne a poté se vrátí zpět do normálního stavu. Nic víc se nestalo. Co uděláš?}
{110}{}{Kopneš ho do 'speciálního' místa.}
{111}{}{Spustíš diagnostický program.}
{112}{}{Otevřeš ho a podíváš se dovnitř.}
{113}{}{Necháš ho být.}
{114}{}{Tato osvědčená opravná metoda vyústí ve dva výsledky. Zaprvé, monitor se na několik sekund zblázní a poté se vrátí zpět do normálního stavu. Zadruhé, uslyšíš zvuky řinčícího kovu a ten panel, do kterého jsi kopl, spadne na zem. Co uděláš?}
{115}{}{Spustíš diagnostický program.}
{116}{}{Ta zatracená věc je teď otevřená, takže se podívám dovnitř.}
{117}{}{Necháš ho být.}
{118}{}{Víš určitě, že by měl mít systém k dispozici několik diagnostických programů. Bohužel to vypadá, že je vstup přes klávesnici vypnutý. Terminál přijímá pouze hlasové povely. Co uděláš?}
{119}{}{Už zbývá se jen podívat dovnitř.}
{120}{}{Necháš ho být.}
{121}{}{Po důkladném prolezení kabeláže a plošných spojů se ti podařilo přijít na to, že byl systém úmyslně sabotován. Jeden z plošných spojů, modul pro rozpoznávání hlasu, nelze opravit a musí se vyměnit. Teď už jen potřebuješ najít náhradní modul.}
{122}{}{Beru.}
{123}{}{Beru.}
{124}{}{Podařilo se ti nainstalovat modul do terminálu. Systém je opraven.}
{125}{}{Terminál nemůže fungovat, dokud nemá nainstalovaný modul pro rozpoznávání hlasu.}
{126}{}{Beru.}
{127}{}{Systém již pracuje v pořádku.}
{128}{}{Přistupuji k bezpečnostním záznamům, nahrávám holografický záznam...}
{129}{}{Jsi poslední, Gruthare. Brzy po tvém druhu nezbude ani flek.}
{130}{}{Vzkaž svému takzvanému Prezidentovi, že za tohle shoří v pekle.}
{131}{}{To je jedno. Nikdy jsi nebyl nic víc než jen mluvící zvíře.}
{132}{}{To je možné, ale stvořili jste nás vy při svých experimentech. Dali jste nám život!}
{133}{}{A teď ti dám smrt.}
{134}{}{Vezměte jeho tělo. Doktor ho chce podrobně prozkoumat.}
{135}{}{Jejich krev poteče jako řeka Nil!}
