{100}{}{Vidíš poèítaèový terminál.}
{101}{}{Vidíš terminál s hlasovým rozhraním.}
{102}{}{Vidíš bìžný poèítaèový terminál upravený pro hlasové povely.}
{103}{}{Zkoumáš poèítaèový terminál, ale nevidíš, že by s ním bylo nìco špatnì. Co udìláš?}
{104}{}{Udeøíš ho 'speciálním' zpùsobem.}
{105}{}{Kopneš ho do 'speciálního' místa.}
{106}{}{Spustíš diagnostický program.}
{107}{}{Otevøeš ho a podíváš se dovnitø.}
{108}{}{Necháš ho být.}
{109}{}{Chvíli zíráš na konzoli a vybíráš nejvhodnìjší místo, kam zasadit úder. Poté, co ho zasáhneš svým nejlepším úderem typu 'to opraví vše', monitor nìkolikrát problikne a poté se vrátí zpìt do normálního stavu. Nic víc se nestalo. Co udìláš?}
{110}{}{Kopneš ho do 'speciálního' místa.}
{111}{}{Spustíš diagnostický program.}
{112}{}{Otevøeš ho a podíváš se dovnitø.}
{113}{}{Necháš ho být.}
{114}{}{Tato osvìdèená opravná metoda vyústí ve dva výsledky. Zaprvé, monitor se na nìkolik sekund zblázní a poté se vrátí zpìt do normálního stavu. Zadruhé, uslyšíš zvuky øinèícího kovu a ten panel, do kterého jsi kopl, spadne na zem. Co udìláš?}
{115}{}{Spustíš diagnostický program.}
{116}{}{Ta zatracená vìc je teï otevøená, takže se podívám dovnitø.}
{117}{}{Necháš ho být.}
{118}{}{Víš urèitì, že by mìl mít systém k dispozici nìkolik diagnostických programù. Bohužel to vypadá, že je vstup pøes klávesnici vypnutý. Terminál pøijímá pouze hlasové povely. Co udìláš?}
{119}{}{Už zbývá se jen podívat dovnitø.}
{120}{}{Necháš ho být.}
{121}{}{Po dùkladném prolezení kabeláže a plošných spojù se ti podaøilo pøijít na to, že byl systém úmyslnì sabotován. Jeden z plošných spojù, modul pro rozpoznávání hlasu, nelze opravit a musí se vymìnit. Teï už jen potøebuješ najít náhradní modul.}
{122}{}{Beru.}
{123}{}{Beru.}
{124}{}{Podaøilo se ti nainstalovat modul do terminálu. Systém je opraven.}
{125}{}{Terminál nemùže fungovat, dokud nemá nainstalovaný modul pro rozpoznávání hlasu.}
{126}{}{Beru.}
{127}{}{Systém již pracuje v poøádku.}
{128}{}{Pøistupuji k bezpeènostním záznamùm, nahrávám holografický záznam...}
{129}{}{Jsi poslední, Gruthare. Brzy po tvém druhu nezbude ani flek.}
{130}{}{Vzkaž svému takzvanému Prezidentovi, že za tohle shoøí v pekle.}
{131}{}{To je jedno. Nikdy jsi nebyl nic víc než jen mluvící zvíøe.}
{132}{}{To je možné, ale stvoøili jste nás vy pøi svých experimentech. Dali jste nám život!}
{133}{}{A teï ti dám smrt.}
{134}{}{Vezmìte jeho tìlo. Doktor ho chce podrobnì prozkoumat.}
{135}{}{Jejich krev poteèe jako øeka Nil!}
