{100}{}{Vidíš starého, pøátelsky vypadajícího chlapíka.}
{101}{}{Vidíš doktora Jubilee.}
{102}{}{Je to starı mu s bílou bradkou a lehce prázdnım pohledem.}
{103}{}{Jsem doktor Jubilee. Co se dìje, mladı mui?}
{104}{}{Co se dìje, mladı mui?}
{105}{}{Já zranìn.}
{106}{}{Potøebuju doktora.}
{107}{}{Nemùete si vzít nìjakı pilulky nebo nìco a pøestat mì otravovat s takovıma blbostma?}
{108}{}{Ale prdlajz, vdy sotva krvácíte.}
{109}{}{No nevím. Myslím, e tu nohu nedokáu zachránit. Moná ji budu muset amputovat.}
{110}{}{To si dìláte srandu!}
{111}{}{Haha.}
{112}{}{Tak a je to, synku.}
{113}{}{Znova.}
{114}{}{Díky, doktore. Moná byste mi mohl ještì zodpovìdìt pár otázek.}
{115}{}{Sbohem.}
{116}{}{Bude vás to stát $50.}
{117}{}{Prostì mì uzdravte.}
{118}{}{Mizím odsud.}
{119}{}{Ty dìlat líp.}
{120}{}{Já teï jít.}
{121}{}{Ne. Nikdy neertuju. Radši tu nohu uøíznu døív, ne se do rány dostane snì.}
{122}{}{V ádném pøípadì se nebude nic øezat, rozumíte?}
{123}{}{Tak a dost, odcházím.}
{124}{}{Dobrá, ale jestli to zaène hnisat, tak to na mì nesvádìjte.}
{125}{}{Nedìlám to pro charitu. Budete muset sehnat nìjaké peníze, ne pro vás nìco udìlám.}
{126}{}{Take, co pro vás mùu udìlat?}
{127}{}{Mluvte.}
{128}{}{Vault 13?}
{129}{}{Nevíte, kde najdu Vault 13?}
{130}{}{Prı na tom pan Westin není dobøe. Je to pravda? Bojím se, aby se mu nìco nestalo. Dluí mi peníze.}
{131}{}{Slaneèek tvrdí, e jste mu ukradl mapu. O co jde?}
{132}{}{Hledám práci. Nevíte o nìèem?}
{133}{}{Doktore, nevíte nìco o skupinì, která bojuje s tìmi zlımi otrokáøi?}
{134}{}{Nemusíte se obávat, synku. Pokud nebude svùj organismus pøetìovat, tak nás pravdìpodobnì všechny pøeije. Samozøejmì by mì ale musel nìkdy poslouchat nebo brát své léky.}
{135}{}{To je dobrá zpráva. Chci se ještì na nìco zeptat.}
{136}{}{Díky, doktore.}
{137}{}{Ten starej opilec! Jediná vìc, kterou od nìj mám, je obraz s "Velvet Elvii", místo dluhu.}
{138}{}{Velvet Elvii? Mùu ho vidìt?}
{139}{}{Náhodou nevypadá jako mapa, e? No nic, zamìstnám váš mozek nìèím jinım.}
{140}{}{No, u musím jít.}
{141}{}{O tom jsem neslyšel od té doby, co sem pøinesli starıho Slaneèka. S úpalem. Leel v horeèkách tøi dny a celou dobu blouznil o tom, jak našel Vault 13, svoji mateøskou ílu.}
{142}{}{Mateøskou ílu?}
{143}{}{Take kde to je?}
{144}{}{Kde vault?}
{145}{}{To nedokáu øíct. Slaneèek poøád tvrdil, e má mapu, ale nikdo ji nikdy nevidìl.}
{146}{}{Slaneèek?}
{147}{}{Ptát se víc.}
{148}{}{No, aspoò vím víc ne pøedtím.}
{149}{}{A velikou. Slaneèek je starı hledaè uranu, pøesnìji øeèeno opilec. Momentálnì ije u Westina.}
{150}{}{Další otázka...}
{151}{}{Díky za pøíbìh.}
{152}{}{No, doufal jsem, e za nìj dostanu nìjaké peníze. Nechám vám ho za $}
{153}{}{Moná pozdìji, další otázka...}
{154}{}{Moná pozdìji, teï musím jít.}
{155}{}{Slaneèek je starı hledaè uranu. Momentálnì ije u Westina.}
{156}{}{Další otázka...}
{157}{}{Díky za pøíbìh.}
{158}{}{Nejlepší bude, kdy si promluvíte s prezidentkou Tandi. Slyšel jsem, e hledá nìkoho speciálního.}
{159}{}{Další otázka...}
{160}{}{Díky.}
{161}{}{Moná jo... existuje skupinka, která bojuje proti otrokáøství a, no, vìtšinì neøestí. Nìkdy jsou k vidìní u toho velkého obchodu jak pracují na nìjakém autì.}
{162}{}{Další otázka...}
{163}{}{Díky.}
{164}{}{Hej, dej od toho pracky pryè, hajzle!}
{165}{}{Opatrnì! I nepatrné mnoství je nebezpeèné.}
{166}{}{Vrate to zpátky! Mùete si tím dost ublíit.}
{167}{}{Ty léky jsou pro pana Westina, ne pro vás. Vrate je zpátky.}
{168}{}{Jdìte od toho. Musím bıt opatrnı, víte. Nechci, aby pan Westin dostal špatné léky.}
{169}{}{Dávejte pozor! Právì jsem odmìøil dávku pro pana Westina.}
{170}{}{Jsem doktor Jubilee. Co se dìje, sleèno?}
{171}{}{Co se dìje, sleèno?}
{172}{}{Tak a je to, sleèno.}
{173}{}{Nemusíte se bát, sleèno. Pokud nebude svùj organismus pøetìovat, tak nás pravdìpodobnì všechny pøeije. Samozøejmì by mì ale musel nìkdy poslouchat nebo brát své léky.}
{174}{}{Jasnì. Tady je $}
{175}{}{Díky, pokoušel jsem se dostat peníze ze Slaneèka, ale ten pobuda nikdy ádné nemìl.}
{176}{}{.}
