{100}{}{Vidíš starého, přátelsky vypadajícího chlapíka.}
{101}{}{Vidíš doktora Jubilee.}
{102}{}{Je to starý muž s bílou bradkou a lehce prázdným pohledem.}
{103}{}{Jsem doktor Jubilee. Co se děje, mladý muži?}
{104}{}{Co se děje, mladý muži?}
{105}{}{Já zraněn.}
{106}{}{Potřebuju doktora.}
{107}{}{Nemůžete si vzít nějaký pilulky nebo něco a přestat mě otravovat s takovýma blbostma?}
{108}{}{Ale prdlajz, vždyť sotva krvácíte.}
{109}{}{No nevím. Myslím, že tu nohu nedokážu zachránit. Možná ji budu muset amputovat.}
{110}{}{To si děláte srandu!}
{111}{}{Haha.}
{112}{}{Tak a je to, synku.}
{113}{}{Znova.}
{114}{}{Díky, doktore. Možná byste mi mohl ještě zodpovědět pár otázek.}
{115}{}{Sbohem.}
{116}{}{Bude vás to stát $50.}
{117}{}{Prostě mě uzdravte.}
{118}{}{Mizím odsud.}
{119}{}{Ty dělat líp.}
{120}{}{Já teď jít.}
{121}{}{Ne. Nikdy nežertuju. Radši tu nohu uříznu dřív, než se do rány dostane sněť.}
{122}{}{V žádném případě se nebude nic řezat, rozumíte?}
{123}{}{Tak a dost, odcházím.}
{124}{}{Dobrá, ale jestli to začne hnisat, tak to na mě nesvádějte.}
{125}{}{Nedělám to pro charitu. Budete muset sehnat nějaké peníze, než pro vás něco udělám.}
{126}{}{Takže, co pro vás můžu udělat?}
{127}{}{Mluvte.}
{128}{}{Vault 13?}
{129}{}{Nevíte, kde najdu Vault 13?}
{130}{}{Prý na tom pan Westin není dobře. Je to pravda? Bojím se, aby se mu něco nestalo. Dluží mi peníze.}
{131}{}{Slaneček tvrdí, že jste mu ukradl mapu. O co jde?}
{132}{}{Hledám práci. Nevíte o něčem?}
{133}{}{Doktore, nevíte něco o skupině, která bojuje s těmi zlými otrokáři?}
{134}{}{Nemusíte se obávat, synku. Pokud nebude svůj organismus přetěžovat, tak nás pravděpodobně všechny přežije. Samozřejmě by mě ale musel někdy poslouchat nebo brát své léky.}
{135}{}{To je dobrá zpráva. Chci se ještě na něco zeptat.}
{136}{}{Díky, doktore.}
{137}{}{Ten starej opilec! Jediná věc, kterou od něj mám, je obraz s "Velvet Elvii", místo dluhu.}
{138}{}{Velvet Elvii? Můžu ho vidět?}
{139}{}{Náhodou nevypadá jako mapa, že? No nic, zaměstnám váš mozek něčím jiným.}
{140}{}{No, už musím jít.}
{141}{}{O tom jsem neslyšel od té doby, co sem přinesli starýho Slanečka. S úpalem. Ležel v horečkách tři dny a celou dobu blouznil o tom, jak našel Vault 13, svoji mateřskou žílu.}
{142}{}{Mateřskou žílu?}
{143}{}{Takže kde to je?}
{144}{}{Kde vault?}
{145}{}{To nedokážu říct. Slaneček pořád tvrdil, že má mapu, ale nikdo ji nikdy neviděl.}
{146}{}{Slaneček?}
{147}{}{Ptát se víc.}
{148}{}{No, aspoň vím víc než předtím.}
{149}{}{A velikou. Slaneček je starý hledač uranu, přesněji řečeno opilec. Momentálně žije u Westina.}
{150}{}{Další otázka...}
{151}{}{Díky za příběh.}
{152}{}{No, doufal jsem, že za něj dostanu nějaké peníze. Nechám vám ho za $}
{153}{}{Možná později, další otázka...}
{154}{}{Možná později, teď musím jít.}
{155}{}{Slaneček je starý hledač uranu. Momentálně žije u Westina.}
{156}{}{Další otázka...}
{157}{}{Díky za příběh.}
{158}{}{Nejlepší bude, když si promluvíte s prezidentkou Tandi. Slyšel jsem, že hledá někoho speciálního.}
{159}{}{Další otázka...}
{160}{}{Díky.}
{161}{}{Možná jo... existuje skupinka, která bojuje proti otrokářství a, no, většině neřestí. Někdy jsou k vidění u toho velkého obchodu jak pracují na nějakém autě.}
{162}{}{Další otázka...}
{163}{}{Díky.}
{164}{}{Hej, dej od toho pracky pryč, hajzle!}
{165}{}{Opatrně! I nepatrné množství je nebezpečné.}
{166}{}{Vraťte to zpátky! Můžete si tím dost ublížit.}
{167}{}{Ty léky jsou pro pana Westina, ne pro vás. Vraťte je zpátky.}
{168}{}{Jděte od toho. Musím být opatrný, víte. Nechci, aby pan Westin dostal špatné léky.}
{169}{}{Dávejte pozor! Právě jsem odměřil dávku pro pana Westina.}
{170}{}{Jsem doktor Jubilee. Co se děje, slečno?}
{171}{}{Co se děje, slečno?}
{172}{}{Tak a je to, slečno.}
{173}{}{Nemusíte se bát, slečno. Pokud nebude svůj organismus přetěžovat, tak nás pravděpodobně všechny přežije. Samozřejmě by mě ale musel někdy poslouchat nebo brát své léky.}
{174}{}{Jasně. Tady je $}
{175}{}{Díky, pokoušel jsem se dostat peníze ze Slanečka, ale ten pobuda nikdy žádné neměl.}
{176}{}{.}
