{100}{}{Vidíš hezkou mladou enu v maskáèích.}
{101}{}{Vidíš Elise.}
{102}{}{Šíøí kolem sebe zvláštní atmosféru. Jako by byla zvyklá dávat rozkazy, které ostatní plní.}
{103}{}{Co chceš?}
{104}{}{Zase vy?}
{105}{}{Posílá mì Karl.}
{106}{}{Dr. Jubilee mi øekl, e si mám s tebou promluvit.}
{107}{}{Kdo jsi?}
{108}{}{Guh?}
{109}{}{Hledám jistou skupinu. Takovou, co nenávidí otroctví. Øíkají si New Californští Rangeøi.}
{110}{}{Dokáeš opravit moje auto?}
{111}{}{Eh, myslel jsem, e je to tady opuštìné.}
{112}{}{Opravdu? Co ti øekl?}
{113}{}{Nic moc. Jen e jste dobrá parta a e bych se k vám mìl pøidat.}
{114}{}{Øíkal, e dobøe platíte.}
{115}{}{Jsem Elise a tohle je Gond. Patøíme ke skupinì, která se snaí konat správné vìci.}
{116}{}{Nevypadáte jako charita ani církev.}
{117}{}{To zní zajímavì. Správné v jakém smyslu?}
{118}{}{Chci jenom opravit auto.}
{119}{}{Odejdi odsud. Salón je na hlavní ulici.}
{120}{}{Nenávidíš otroctví, jo? Zajímavé. Co bys dìlal, kdybys tu skupinu našel?}
{121}{}{Poádal bych je o èlenství.}
{122}{}{Nakopal bych jim prdel.}
{123}{}{No nic.}
{124}{}{Do toho ti nic není. Teï se odtud kliï.}
{125}{}{S obchodem s auty u jsme skonèili. Definitivnì. Sbohem.}
{126}{}{Není. Sbohem.}
{127}{}{Dobøe. Povìz, co si myslíš o otrokáøích?}
{128}{}{Nenávidím je. Jsou nechutná spodina lidstva.}
{129}{}{Dokud mi nic neudìlají, neudìlám ani já nic jim.}
{130}{}{Nìkteøí z mıch nejlepších pøátel jsou otrokáøi.}
{131}{}{Peníze jsou to jediné, co tì zajímá?}
{132}{}{Jasnì, e ne. Vìøím v pravdu, zákon a boj proti utiskovatelùm.}
{133}{}{Pro zaèátek jo... dokud nìkdo nenajde lepší dùvod proè bojovat.}
{134}{}{Co jiného by mì mìlo zajímat?}
{135}{}{Nedìlej ze mì blbce. Dobøe vidím, co jsi zaè. Sbohem.}
{136}{}{Jestli to nevíš, tak tu jen ztrácíme èas. Sbohem.}
{137}{}{Ne, nejsme náboenská organizace. Mùu se tì na nìco zeptat?}
{138}{}{Jasnì, jen do toho.}
{139}{}{Ne tak rychle. Èlenství ve skupinì Rangerù vyaduje splnìní testu.}
{140}{}{Dobøe, tak povídej.}
{141}{}{Testu? Jsme snad... ve škole?}
{142}{}{Venku za mìstem je otrokáø. Moná jsi to místo u vidìl. Osvoboï odtamtud všechny otroky a pak nám to pøijï øíct.}
{143}{}{Fajn, to zvládnu.}
{144}{}{V ádném pøípadì. Nechci mít problémy.}
{145}{}{No, dneska je tvùj šastnı den.}
{146}{}{A pøesnì díky takovému pøístupu existují zvìrstva jako je otrokáøství. Promiò, ale v naší skupinì pro tebe není místo.}
{147}{}{Dobøe.}
{148}{}{Tak jak? Zmìnil jsi názor? Pøipraven prokázat, e jsi hoden bıt Ranger?}
{149}{}{Jasnì.}
{150}{}{Co e to mám udìlat?}
{151}{}{Nemáš náhodou nìco udìlat? Nevracej se, dokud nedokonèíš svùj úkol.}
{152}{}{U jsem ty novinky slyšela. Osvobodil jsi otroky. Dobrá práce! Take, jsi pøipraven stát se Rangerem?}
{153}{}{Ano.}
{154}{}{Ne.}
{155}{}{Slyšela jsem, e jsi ten, co osvobodil otroky za mìstem. To byla opravdu správná vìc a já bych ti za to ráda potøásla rukou.}
{156}{}{Díky.}
{157}{}{Je to prosté. Vìøíme v to, e je otrokáøství špatné a udìláme všechno proto, abychom s ním bojovali. V NCR máme hodnì pøátel na vysokıch pozicích. Díky nim jsme zlikvidovali otroctví na jihu a teï se nám to doufám podaøí i na severu.}
{158}{}{Rangeøi mi pøijdou jako skupina, ke které by mi bylo ctí se pøipojit. Zapiš mì.}
{159}{}{Zajímavé... budu pøemıšlet o tom, co jsi øekla.}
{160}{}{Pøísaháš, e budeš potírat otroctví kdekoliv na svìtì a e budeš vdy pomáhat svım bratrùm Rangerùm kdykoliv to budou potøebovat?}
{161}{}{Ano.}
{162}{}{Ne.}
{163}{}{Gratuluju, nyní jsi Ranger.}
{164}{}{Vítej, bratøe Rangere. V tuhle chvíli tu pro tebe není moc práce. Vìtšina našich lidí je venku na hlídce. Øeknu ostatním, e patøíš mezi nás. Nechci, aby tì nìkdo z našich zastøelil.}
{165}{}{Víš, neustále hledáme dobré lidi, kteøí jsou ochotni podpoøit náš cíl. Jestli zmìníš názor, dej mi vìdìt. Opravdu nechceš vyuít monosti se k nám teï pøipojit?}
{166}{}{Ne, opravdu ne.}
{167}{}{No, kdy o tom tak mluvíš... myslím, e chci bıt Rangerem.}
{168}{}{Aha. Zastupuju skupinu, která si øíká New Californští Rangeøi. Lidé s názory jako ty se mùou zajímat o naše èlenství. Máš zájem?}
{169}{}{Vıbornì! Zapiš mì.}
{170}{}{To zní zajímavì. Co mi mùeš øíct o Rangerech?}
{171}{}{Aha. No, díky, e ses zastavil, ale myslím, e v tuhle chvíli si u nemáme co øíct. Jestli zmìníš názor, dej mi vìdìt.}
{172}{}{Dobøe.}
{173}{}{V tom pøípadì se mi kliï z oèí. Hned!}
{174}{}{Dobøe.}
{175}{}{Otrokáø! Rychle zmiz, ne ti to tvı tetování rozstøílím na kousky!}
{176}{}{Jasnì.}
{177}{}{To si mùeš zkusit!}
{178}{}{Máme nìkolik agentù a pøátel v nìkterıch mìstech na severu. Rozšiøujeme naše názory a škodíme otrokáøùm kdekoliv to jen jde.}
{179}{}{Vítej zpìt. Chceš se k nám tedy pøipojit?}
{180}{}{Zapomeò na to.}
{181}{}{To není tvoje. Teï odejdi, nebo ti ublíím.}
{182}{}{Nevím, co jsi Gondovi udìlal, ale zaplatíš za to!}
