{100}{}{Vidíš hezkou mladou ženu v maskáčích.}
{101}{}{Vidíš Elise.}
{102}{}{Šíří kolem sebe zvláštní atmosféru. Jako by byla zvyklá dávat rozkazy, které ostatní plní.}
{103}{}{Co chceš?}
{104}{}{Zase vy?}
{105}{}{Posílá mě Karl.}
{106}{}{Dr. Jubilee mi řekl, že si mám s tebou promluvit.}
{107}{}{Kdo jsi?}
{108}{}{Guh?}
{109}{}{Hledám jistou skupinu. Takovou, co nenávidí otroctví. Říkají si New Californští Rangeři.}
{110}{}{Dokážeš opravit moje auto?}
{111}{}{Eh, myslel jsem, že je to tady opuštěné.}
{112}{}{Opravdu? Co ti řekl?}
{113}{}{Nic moc. Jen že jste dobrá parta a že bych se k vám měl přidat.}
{114}{}{Říkal, že dobře platíte.}
{115}{}{Jsem Elise a tohle je Gond. Patříme ke skupině, která se snaží konat správné věci.}
{116}{}{Nevypadáte jako charita ani církev.}
{117}{}{To zní zajímavě. Správné v jakém smyslu?}
{118}{}{Chci jenom opravit auto.}
{119}{}{Odejdi odsud. Salón je na hlavní ulici.}
{120}{}{Nenávidíš otroctví, jo? Zajímavé. Co bys dělal, kdybys tu skupinu našel?}
{121}{}{Požádal bych je o členství.}
{122}{}{Nakopal bych jim prdel.}
{123}{}{No nic.}
{124}{}{Do toho ti nic není. Teď se odtud kliď.}
{125}{}{S obchodem s auty už jsme skončili. Definitivně. Sbohem.}
{126}{}{Není. Sbohem.}
{127}{}{Dobře. Pověz, co si myslíš o otrokářích?}
{128}{}{Nenávidím je. Jsou nechutná spodina lidstva.}
{129}{}{Dokud mi nic neudělají, neudělám ani já nic jim.}
{130}{}{Někteří z mých nejlepších přátel jsou otrokáři.}
{131}{}{Peníze jsou to jediné, co tě zajímá?}
{132}{}{Jasně, že ne. Věřím v pravdu, zákon a boj proti utiskovatelům.}
{133}{}{Pro začátek jo... dokud někdo nenajde lepší důvod proč bojovat.}
{134}{}{Co jiného by mě mělo zajímat?}
{135}{}{Nedělej ze mě blbce. Dobře vidím, co jsi zač. Sbohem.}
{136}{}{Jestli to nevíš, tak tu jen ztrácíme čas. Sbohem.}
{137}{}{Ne, nejsme náboženská organizace. Můžu se tě na něco zeptat?}
{138}{}{Jasně, jen do toho.}
{139}{}{Ne tak rychle. Členství ve skupině Rangerů vyžaduje splnění testu.}
{140}{}{Dobře, tak povídej.}
{141}{}{Testu? Jsme snad... ve škole?}
{142}{}{Venku za městem je otrokář. Možná jsi to místo už viděl. Osvoboď odtamtud všechny otroky a pak nám to přijď říct.}
{143}{}{Fajn, to zvládnu.}
{144}{}{V žádném případě. Nechci mít problémy.}
{145}{}{No, dneska je tvůj šťastný den.}
{146}{}{A přesně díky takovému přístupu existují zvěrstva jako je otrokářství. Promiň, ale v naší skupině pro tebe není místo.}
{147}{}{Dobře.}
{148}{}{Tak jak? Změnil jsi názor? Připraven prokázat, že jsi hoden být Ranger?}
{149}{}{Jasně.}
{150}{}{Co že to mám udělat?}
{151}{}{Nemáš náhodou něco udělat? Nevracej se, dokud nedokončíš svůj úkol.}
{152}{}{Už jsem ty novinky slyšela. Osvobodil jsi otroky. Dobrá práce! Takže, jsi připraven stát se Rangerem?}
{153}{}{Ano.}
{154}{}{Ne.}
{155}{}{Slyšela jsem, že jsi ten, co osvobodil otroky za městem. To byla opravdu správná věc a já bych ti za to ráda potřásla rukou.}
{156}{}{Díky.}
{157}{}{Je to prosté. Věříme v to, že je otrokářství špatné a uděláme všechno proto, abychom s ním bojovali. V NCR máme hodně přátel na vysokých pozicích. Díky nim jsme zlikvidovali otroctví na jihu a teď se nám to doufám podaří i na severu.}
{158}{}{Rangeři mi přijdou jako skupina, ke které by mi bylo ctí se připojit. Zapiš mě.}
{159}{}{Zajímavé... budu přemýšlet o tom, co jsi řekla.}
{160}{}{Přísaháš, že budeš potírat otroctví kdekoliv na světě a že budeš vždy pomáhat svým bratrům Rangerům kdykoliv to budou potřebovat?}
{161}{}{Ano.}
{162}{}{Ne.}
{163}{}{Gratuluju, nyní jsi Ranger.}
{164}{}{Vítej, bratře Rangere. V tuhle chvíli tu pro tebe není moc práce. Většina našich lidí je venku na hlídce. Řeknu ostatním, že patříš mezi nás. Nechci, aby tě někdo z našich zastřelil.}
{165}{}{Víš, neustále hledáme dobré lidi, kteří jsou ochotni podpořit náš cíl. Jestli změníš názor, dej mi vědět. Opravdu nechceš využít možnosti se k nám teď připojit?}
{166}{}{Ne, opravdu ne.}
{167}{}{No, když o tom tak mluvíš... myslím, že chci být Rangerem.}
{168}{}{Aha. Zastupuju skupinu, která si říká New Californští Rangeři. Lidé s názory jako ty se můžou zajímat o naše členství. Máš zájem?}
{169}{}{Výborně! Zapiš mě.}
{170}{}{To zní zajímavě. Co mi můžeš říct o Rangerech?}
{171}{}{Aha. No, díky, že ses zastavil, ale myslím, že v tuhle chvíli si už nemáme co říct. Jestli změníš názor, dej mi vědět.}
{172}{}{Dobře.}
{173}{}{V tom případě se mi kliď z očí. Hned!}
{174}{}{Dobře.}
{175}{}{Otrokář! Rychle zmiz, než ti to tvý tetování rozstřílím na kousky!}
{176}{}{Jasně.}
{177}{}{To si můžeš zkusit!}
{178}{}{Máme několik agentů a přátel v některých městech na severu. Rozšiřujeme naše názory a škodíme otrokářům kdekoliv to jen jde.}
{179}{}{Vítej zpět. Chceš se k nám tedy připojit?}
{180}{}{Zapomeň na to.}
{181}{}{To není tvoje. Teď odejdi, nebo ti ublížím.}
{182}{}{Nevím, co jsi Gondovi udělal, ale zaplatíš za to!}
