{100}{}{Vidíš vychrtlého starého muže s tužkou za uchem a brýlemi na špičce nosu.}
{101}{}{Vidíš Vortise, majitele této ohrady pro otroky.}
{102}{}{Má asi tak tři zuby. Jeho prsty a košile jsou potřísněné modrým inkoustem. Na čele se mu tkví hodně zašlé otrokářské tetování.}
{103}{}{Takže, co tu chceš?}
{104}{}{Vítej ve Vortisově sídle, bratře. Jak ti můžu pomoct?}
{105}{}{Začínáš mi jít na nervy.}
{106}{}{Tohle místo je moje a já, Vortis, tu vedu počestnej a zákonem schválenej podnik, bez ohledu na to, co ti o tom někdo v NCR navykládal. Jelikož není uvnitř NCR otrokářství dovoleno, starám se tu o otroky lidem, kteří maj něco na práci ve městě.}
{107}{}{Pomalu chápeš nebo co? Tohle je ohrada pro otroky. Mám na to povolení.}
{108}{}{}
{109}{}{Mám jen nějaké otázky.}
{110}{}{Hledám práci.}
{111}{}{Eh?}
{112}{}{Toto ne kadibudka? Já jít pryč.}
{113}{}{Co je tohle za místo?}
{114}{}{Nic. Špatné místo.}
{115}{}{A to se podívejme... přišel se k nám podívat nějakej dobrodinec. Hoši, vyprovoďte tohohle pokryteckýho svatouška pryč z mýho dohledu!}
{116}{}{Do hajzlu.}
{117}{}{Ano?}
{118}{}{Hledám Vault 13.}
{119}{}{Nemáš GECK?}
{120}{}{Můžeš mi něco povědět o tomhle městě?}
{121}{}{Ty otrokářskej sviňáku! Řekni mi jedinej důvod, proč tě nemám hned oddělat?}
{122}{}{Povídá se tu o nějakých chlápcích... New Californští Rangeři. Nemáš s nimi nějaké potíže?}
{123}{}{Nebude ti vadit, když se tu trochu porozhlédnu?}
{124}{}{Práci? Mno... něco by se možná našlo. Říkají ti něco "New Californští Rangeři"?}
{125}{}{Ano.}
{126}{}{Ne.}
{127}{}{Jdi do prdele. Hoši, vyprovoďte odsud toho otrapu.}
{128}{}{Polib mi!}
{129}{}{Vault 13! Neblázni. To zatracený místo je výmysl. Vault 13 neexistuje.}
{130}{}{Další otázka...}
{131}{}{No, tak díky za nic.}
{132}{}{Cože? No, ať už je to cokoliv, tak já to nemám.}
{133}{}{Další otázka...}
{134}{}{No, tak díky za nic.}
{135}{}{New California Republic... nic než ukáznění lidi a obchodníci. Vlezlo jim nějak na mozek otrokářství a otroci, ale to je fuk, aspoň mám kšeft.}
{136}{}{Další otázka...}
{137}{}{Díky, už půjdu.}
{138}{}{Máš špatný informace. S nikým potíže nemám... a už vůbec ne s Rangery. Všechno mám legální, takže na mě nemůžeš.}
{139}{}{Další otázka...}
{140}{}{Jak myslíš. Už půjdu.}
{141}{}{Jo, možná mám nějaký potíže s Rangery. Hledáš práci?}
{142}{}{Ano.}
{143}{}{Ne.}
{144}{}{Ne, nebudeš tady čmuchat kolem, ty demente! Tady nejseš v muzeu!}
{145}{}{Další otázka...}
{146}{}{Moc se urážíš. Raději půjdu.}
{147}{}{Víš, někteří lidi v nich vidí potenciální problém. Hrozně by nám pomohlo, kdybysme měli mapu jejich úkrytů směrem na sever - New Reno, Klamath a tak dále. Jsem ochotnej ti za tu mapu dát řekněme $500. Co ty na to? Seženeš mi ji?}
{148}{}{Jasně.}
{149}{}{Ne-e!}
{150}{}{Tak já ti to teda povím. Tihle Rangeři si usmysleli, že kompletně vyhladí otrokářství a otroky... násilím. Způsobujou tak těžce pracujícím lidem hodně problémů.}
{151}{}{Pracují v tajnosti, obzvlášť na severu.}
{152}{}{Ježíš, musím ti to snad hláskovat? Přepadnou otrokáře, vyženou otroky a propašují je dolů na jih do NCR, kde je otroctví zakázaný. Máš teda zájem?}
{153}{}{Není žádné "a"! Chceš tu práci nebo ne?}
{154}{}{A?}
{155}{}{A co mám přesně udělat?}
{156}{}{Fajn. Sežeň mi tu mapu, budu tady.}
{157}{}{Kde se ta mapa nachází?}
{158}{}{Dobře, ale mám ještě nějaké otázky.}
{159}{}{Jdu na to. Uvidíme se později.}
{160}{}{Jak to mám sakra vědět!? Kdybych to věděl, tak už ji dávno mám, nemyslíš? Hele, ve městě by mělo bejt vězení. Najdi ho a třeba tě to někam zavede.}
{161}{}{Ještě pár otázek.}
{162}{}{Dobře. Vrátím se.}
{163}{}{Á, vítej zpátky. Máš tu mapu?}
{164}{}{Ano.}
{165}{}{Ne.}
{166}{}{Pořád čekám, až doděláš svůj první úkol!}
{167}{}{No jó, já hlava děravá.}
{168}{}{Od tý doby, co máš za sebou tu práci, tak ne. Díky.}
{169}{}{Jenom otázečku nebo dvě.}
{170}{}{Žádný problém. Nashle.}
{171}{}{Dobrá práce. A teď se radši vypař, než to těm Rangerům dojde.}
{172}{}{Rádo se stalo.}
{173}{}{No tak tady jen tak nestůj, blbečku! Ještě to bude někomu připadat podezřelý.}
{174}{}{Jasně, chápu.}
{175}{}{Co to má kurva znamenat? Stráže! Máme tu vetřelce!}
{176}{}{Ještě jeden krok a vystřelím ti mozek. Rozumíš?}
{177}{}{Je pozdě, už máme zavřeno. Přijď ráno.}
