{100}{}{Vidíš vychrtlého starého mue s tukou za uchem a brılemi na špièce nosu.}
{101}{}{Vidíš Vortise, majitele této ohrady pro otroky.}
{102}{}{Má asi tak tøi zuby. Jeho prsty a košile jsou potøísnìné modrım inkoustem. Na èele se mu tkví hodnì zašlé otrokáøské tetování.}
{103}{}{Take, co tu chceš?}
{104}{}{Vítej ve Vortisovì sídle, bratøe. Jak ti mùu pomoct?}
{105}{}{Zaèínáš mi jít na nervy.}
{106}{}{Tohle místo je moje a já, Vortis, tu vedu poèestnej a zákonem schválenej podnik, bez ohledu na to, co ti o tom nìkdo v NCR navykládal. Jeliko není uvnitø NCR otrokáøství dovoleno, starám se tu o otroky lidem, kteøí maj nìco na práci ve mìstì.}
{107}{}{Pomalu chápeš nebo co? Tohle je ohrada pro otroky. Mám na to povolení.}
{108}{}{}
{109}{}{Mám jen nìjaké otázky.}
{110}{}{Hledám práci.}
{111}{}{Eh?}
{112}{}{Toto ne kadibudka? Já jít pryè.}
{113}{}{Co je tohle za místo?}
{114}{}{Nic. Špatné místo.}
{115}{}{A to se podívejme... pøišel se k nám podívat nìjakej dobrodinec. Hoši, vyprovoïte tohohle pokryteckıho svatouška pryè z mıho dohledu!}
{116}{}{Do hajzlu.}
{117}{}{Ano?}
{118}{}{Hledám Vault 13.}
{119}{}{Nemáš GECK?}
{120}{}{Mùeš mi nìco povìdìt o tomhle mìstì?}
{121}{}{Ty otrokáøskej sviòáku! Øekni mi jedinej dùvod, proè tì nemám hned oddìlat?}
{122}{}{Povídá se tu o nìjakıch chlápcích... New Californští Rangeøi. Nemáš s nimi nìjaké potíe?}
{123}{}{Nebude ti vadit, kdy se tu trochu porozhlédnu?}
{124}{}{Práci? Mno... nìco by se moná našlo. Øíkají ti nìco "New Californští Rangeøi"?}
{125}{}{Ano.}
{126}{}{Ne.}
{127}{}{Jdi do prdele. Hoši, vyprovoïte odsud toho otrapu.}
{128}{}{Polib mi!}
{129}{}{Vault 13! Neblázni. To zatracenı místo je vımysl. Vault 13 neexistuje.}
{130}{}{Další otázka...}
{131}{}{No, tak díky za nic.}
{132}{}{Coe? No, a u je to cokoliv, tak já to nemám.}
{133}{}{Další otázka...}
{134}{}{No, tak díky za nic.}
{135}{}{New California Republic... nic ne ukáznìní lidi a obchodníci. Vlezlo jim nìjak na mozek otrokáøství a otroci, ale to je fuk, aspoò mám kšeft.}
{136}{}{Další otázka...}
{137}{}{Díky, u pùjdu.}
{138}{}{Máš špatnı informace. S nikım potíe nemám... a u vùbec ne s Rangery. Všechno mám legální, take na mì nemùeš.}
{139}{}{Další otázka...}
{140}{}{Jak myslíš. U pùjdu.}
{141}{}{Jo, moná mám nìjakı potíe s Rangery. Hledáš práci?}
{142}{}{Ano.}
{143}{}{Ne.}
{144}{}{Ne, nebudeš tady èmuchat kolem, ty demente! Tady nejseš v muzeu!}
{145}{}{Další otázka...}
{146}{}{Moc se uráíš. Radìji pùjdu.}
{147}{}{Víš, nìkteøí lidi v nich vidí potenciální problém. Hroznì by nám pomohlo, kdybysme mìli mapu jejich úkrytù smìrem na sever - New Reno, Klamath a tak dále. Jsem ochotnej ti za tu mapu dát øeknìme $500. Co ty na to? Seeneš mi ji?}
{148}{}{Jasnì.}
{149}{}{Ne-e!}
{150}{}{Tak já ti to teda povím. Tihle Rangeøi si usmysleli, e kompletnì vyhladí otrokáøství a otroky... násilím. Zpùsobujou tak tìce pracujícím lidem hodnì problémù.}
{151}{}{Pracují v tajnosti, obzvláš na severu.}
{152}{}{Jeíš, musím ti to snad hláskovat? Pøepadnou otrokáøe, vyenou otroky a propašují je dolù na jih do NCR, kde je otroctví zakázanı. Máš teda zájem?}
{153}{}{Není ádné "a"! Chceš tu práci nebo ne?}
{154}{}{A?}
{155}{}{A co mám pøesnì udìlat?}
{156}{}{Fajn. Seeò mi tu mapu, budu tady.}
{157}{}{Kde se ta mapa nachází?}
{158}{}{Dobøe, ale mám ještì nìjaké otázky.}
{159}{}{Jdu na to. Uvidíme se pozdìji.}
{160}{}{Jak to mám sakra vìdìt!? Kdybych to vìdìl, tak u ji dávno mám, nemyslíš? Hele, ve mìstì by mìlo bejt vìzení. Najdi ho a tøeba tì to nìkam zavede.}
{161}{}{Ještì pár otázek.}
{162}{}{Dobøe. Vrátím se.}
{163}{}{Á, vítej zpátky. Máš tu mapu?}
{164}{}{Ano.}
{165}{}{Ne.}
{166}{}{Poøád èekám, a dodìláš svùj první úkol!}
{167}{}{No jó, já hlava dìravá.}
{168}{}{Od tı doby, co máš za sebou tu práci, tak ne. Díky.}
{169}{}{Jenom otázeèku nebo dvì.}
{170}{}{ádnı problém. Nashle.}
{171}{}{Dobrá práce. A teï se radši vypaø, ne to tìm Rangerùm dojde.}
{172}{}{Rádo se stalo.}
{173}{}{No tak tady jen tak nestùj, blbeèku! Ještì to bude nìkomu pøipadat podezøelı.}
{174}{}{Jasnì, chápu.}
{175}{}{Co to má kurva znamenat? Stráe! Máme tu vetøelce!}
{176}{}{Ještì jeden krok a vystøelím ti mozek. Rozumíš?}
{177}{}{Je pozdì, u máme zavøeno. Pøijï ráno.}
