{100}{}{Vidíš postaršího mue s oblièejem plnım vrásek. Pokud si všiml, e se na nìj díváš, nedává to nijak znát.}
{101}{}{Vidíš Cassidyho.}
{102}{}{Vidíš postaršího mue s oblièejem plnım vrásek. Kıvne na tebe hlavou.}
{103}{Cas0103}{Well, now. I ain't seen you around before, stranger. Name's Cassidy. I run this place. What can I do for you?}
{104}{Cas0104}{Well now, if it ain't the mysterious stranger. What can I do for you today?}
{105}{}{Ug Nog?}
{106}{}{Odbelhat se.}
{107}{}{Hledám Vault.}
{108}{}{Vypadá to, jako bys chtìl odsud vypadnout, nemám pravdu?}
{109}{}{Co tady èepujete?}
{110}{}{Dìje se tu v okolí nìco zajímavého?}
{111}{}{Dnes nic, díky.}
{112}{Cas0112}{Hit on the head a little too often, eh? Sorry, I don't speak imbecile.}
{113}{}{Béé-cil?}
{114}{Cas0114}{Vault? Only Vault I know of is the one inside the city. Big friggin' hole... you can't miss it, trust me.}
{115}{}{Co tu máš k pití?}
{116}{}{Dìje se tu v okolí nìco zajímavého?}
{117}{}{Díky za informace. Sbohem.}
{118}{Cas0118}{Beer for $20, shot of whiskey for $30. Nothing special. Why, you want something?}
{119}{}{Hledám Vault.}
{120}{}{Dám si pivo.}
{121}{}{Dám si panáka.}
{122}{}{Dìje se tu v okolí nìco zajímavého?}
{123}{}{Ani ne. Kadopádnì díky.}
{124}{Cas0124}{"Interesting?" Heh. Friend, Vault City ain't an "interesting" place... unless the guards get bored, then you
 better take cover. Why you asking? You looking for something in this sinkhole?}
{125}{}{Co tu máš k pití?}
{126}{}{No, vlastnì hledám Vault.}
{127}{}{Nemùe to tady bıt a tak špatné.}
{128}{}{Ani ne. Kadopádnì díky.}
{129}{Cas0129}{Here you go. Drink up. It might help you forget where you are.}
{130}{}{Nemùe to tady bıt a tak špatné.}
{131}{}{Díky za pití. U musím jít.}
{132}{Cas0132}{Oh, really? Well, hell then, I must be mistaken, considering YOU'RE the authority and all. Guess you must have been napping during the raid last week?}
{133}{}{Razii?}
{134}{Cas0134}{Aw, yeah, a beautiful sight it was. A guard patrol broke in here looking for "illegal substances." They busted down the door, busted up my stock, then busted up a few of my customers, too.}
{135}{}{Co se stalo potom?}
{136}{}{To je mi líto. Promluvíme si pozdìji.}
{137}{Cas0137}{After they hauled away this one guy, Joshua, for resisting arrest, they fined my ass for finding - get this - REAL whiskey on the premises. Nevermind that I got a permit from Stark three months before. Bastards.}
{138}{}{Pane jo. To si dìláš srandu.}
{139}{}{To je mi líto. Promluvíme si pozdìji.}
{140}{Cas0140}{It gets better. Now I'm in debt to the guards for the fine, an' I had to buy a new case of alcohol from a merchant at triple my standard rate. I'm expecting the guards to come knocking again soon, just to bust my chops. }
{141}{}{Takhle to tu chodí poøád?}
{142}{}{Snad se ti povede v budoucnu lépe. Zatím.}
{143}{Cas0143}{Even the good days ain't worth a damn. The Citizens don't drink much, so I'm stuck here pouring drinks for merchants. The next cheap sonuvabitch who haggles for a drink is going to be wearing his ass as a hat.}
{144}{}{Proè tu zùstáváš, kdy to tu tak nenávidíš?}
{145}{}{To je mi líto. Hledám Vault. Mùeš mi pomoct?}
{146}{}{To je mi líto. No, snad se to zlepší.}
{147}{Cas0147}{I have a bad heart. Need cardio booster shots to keep it beating. This city's the only place to get real medical care, so I thought I'd settle here, try and make a living.}
{148}{}{To zní, jako bys toho tady mìl a po krk.}
{149}{}{Aha. No, hledám Vault. Mùeš mi pomoct?}
{150}{}{Snad se to èasem zlepší. Zatím.}
{151}{Cas0151}{Makes me want to close up shop and let this City rot. Screw 'em all.}
{152}{}{Tak proè prostì neodejdeš?}
{153}{}{To je mi líto. Snad se to èasem zlepší.}
{154}{Cas0154}{Go into the wastes by myself? Ha! I'm sick of this place, but I ain't stupid.}
{155}{}{Brzy se chystám jít zpátky do pustiny. Nechceš jít se mnou?}
{156}{}{No, tak hodnì štìstí.}
{157}{Cas0157}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{158}{Cas0158}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{159}{Cas0159}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{160}{Cas0160}{Naw... you look like you got enough of a crowd already.}
{161}{}{Dobrá, tak hodnì štìstí.}
{162}{}{Tak na tu nabídku zapomeò, kreténe. Klidnì se vra ke svımu baru v tomhle podìlanım zapadákovì.}
{163}{}{Jak myslíš, tvoje chyba.}
{164}{Cas0164}{Heh. You serious?}
{165}{}{Jasnì. Proè sakra ne? Vypadáš na èlovìka, kterı umí bojovat.}
{166}{}{No, kdy se tak nad tím zamyslím, venku je to docela drsné, zvláš pro nìkoho se srdeèními problémy. Radìji zùstaò tady.}
{167}{Cas0167}{All right, count me in.}
{168}{}{Mùeme vyrazit.}
{169}{}{}
{170}{}{}
{171}{Cas0171}{What's up? You got that "I need to tell you something you might not like" look again.}
{172}{Cas0172}{Yeah?}
{173}{Cas0173}{What's up? You got that "I'm pulling rank" look again.}
{174}{}{Chci se zeptat na pár otázek...}
{175}{}{Zdá se, e jsi trochu zranìnı. Pouij pár Stimpakù a uzdrav se.}
{176}{}{Cassidy, poèkej tady, ne se vrátím.}
{177}{}{Schovej svoji zbraò.}
{178}{}{Dr se blízko mì.}
{179}{}{Moc se nevzdaluj.}
{180}{}{Mìli bychom se trochu rozestoupit.}
{181}{}{Tak pojï, Cassidy. Je èas vyrazit.}
{182}{}{Nic, zapomeò na to.}
{261}{Cas0261}{You want me to put a bullet in Myron's head, is that it? It'd be no trouble. Just give the word.}
{262}{Cas0262}{What's on your mind?}
{263}{}{Proè chceš sejmout Myrona?}
{264}{}{Jaké zbranì preferuješ?}
{265}{}{Vlastnì po tobì chci ještì nìco jiného...}
{266}{}{Vlastnì po tobì chci nìco jiného...}
{267}{}{Zapomeò na to. Pokraèujme.}
{268}{}{Ne, neubliuj Myronovi. Alespoò ne dnes. Dám ti ještì vìdìt.}
{269}{Cas0269}{Well, shotguns and rifles, mostly... just personal preference. I ain't a bad shot with pistols, neither.}
{270}{}{Ještì nìco?}
{271}{}{Dobøe. Mám ještì pár otázek...}
{272}{}{Tak jo. Jenom se ujišuju.}
{273}{Cas0273}{If you ever need to learn somebody some manners up close and personal, slip me some brass knuckles, and I can tapdance on their face with my fists.}
{274}{}{Skvìlé. Ještì nìco?}
{275}{}{Dobøe. Mám ještì pár otázek...}
{276}{}{Tak jo. Jenom se ujišuju.}
{277}{Cas0277}{Uh, well... just between you and me, I can also use a spear pretty good. Me and my buddies used to hunt radscorpions with spears way back when... fact I'm alive and they ain't might tell you something.}
{278}{}{Na oštìpu není nic špatného.}
{279}{}{Dobøe. Mám ještì pár otázek...}
{280}{}{Tak jo. Jenom se ujišuju.}
{281}{Cas0281}{Says you. Just don't be calling me no tribal, and we'll get along just fine.}
{282}{Cas0282}{Don't want people mistaking me for ol' Bone-nose over there. Heh-heh. I ain't never seen no tribal do something as dumb as jam a bone in his nose.}
{283}{Cas0283}{Of course there isn't. Spear's a fine weapon. Lots of tribal friends of mine use 'em.}
{284}{}{Víš o tom, e já jsem taky "divoch?"}
{285}{}{Hmmm. Poslyš, mám ještì pár otázek...}
{286}{}{Tak dobøe. Díky za rozbor.}
{287}{Cas0287}{Aw, don't be playing with ol' Cassidy now. You ain't no tribal.}
{288}{}{Jo, jsem.}
{289}{}{To je jedno. Poslyš, mám ještì pár otázek...}
{290}{}{Zapomeò na to. Nechci to s tebou teï rozebírat.}
{291}{Cas0291}{Uh, well... damn it all, you can have my apology right here and now. I didn't mean any offense.}
{292}{}{V pohodì. Poslyš, mám ještì pár otázek...}
{293}{}{Zapomeò na to. Pokraèujme.}
{294}{Cas0294}{Well, now, before you go, I got a question for you. What are we doing out here? We seem to be running all over the place looking for something. Have we got some sort of plan?}
{295}{}{Hledáme GECK. Soupravu pro vytvoøení rajské zahrady. Má vesnice ho potøebuje, abychom obnovili úrodu.}
{296}{}{Jdeme do Vaultu a potom pøineseme GECK do mojí vesnice.}
{297}{}{Moje vesnice byla unesena. Snaím se zjistit, co se jim stalo.}
{298}{Cas0298}{Them things come in kits now, huh? Man, the good book don't mention that, does it? Well, all right then. Let's get hunting.}
{299}{Cas0299}{Huh. All right then, just checking.}
{300}{Cas0300}{I wouldn't mind plugging a few holes in some kidnappers. A little frontier justice never hurt anyone... well, at least not me.}
{301}{}{Tak dobøe. Mùeme jít.}
{302}{Cas0302}{The things that little cuss says ain't fit for decent ears.}
{303}{Cas0303}{Especially a woman's.}
{304}{}{Vánì, Cassidy? Pøekvapuje mì, e ti na tom záleí. Mé srdce se úplnì chvìje.}
{305}{}{Co tím chceš øíct?}
{306}{}{Víš, ty taky pìknì kleješ, Cassidy.}
{307}{}{To mi povídej. Pokraèujme.}
{308}{Cas0308}{Yeah, but when I do it, it's got style. He's just a little trash mouth.}
{309}{Cas0309}{And I don't like the way he looks at you, neither.}
{310}{}{Vánì, Cassidy? Pøekvapuje mì, e ti na tom záleí. Mé srdce se úplnì chvìje.}
{311}{}{Co tím chceš øíct?}
{312}{}{To mi povídej. Pokraèujme.}
{313}{Cas0313}{Now hold on, I didn't mean it like that.}
{314}{Cas0314}{All I'm saying is that bona fide little asshole's gonna get his number clocked one day when it's just me and him and a hole in the desert.}
{315}{}{No, ivot dokáe bıt tvrdá škola. Mám ještì pár otázek...}
{316}{}{No, je na nejlepší cestì k tomu, aby ho to potkalo. Netrap se tím.}
{317}{}{Uklidni se, Cassidy. Nech Myrona bıt.}
{318}{}{Nenávidím to tady.}
{319}{}{Doufal jsem, e se tomudle místu navdy vyhneme.}
{320}{}{Mìsto tìsnıch prdelí...}
{321}{}{Tady to vypadá hùø ne ve Vault City.}
{322}{}{Ještì, e jsem si pøed chvíli pøekontroloval zbranì.}
{323}{}{Jestli mì nìkdy dostanou, nepohøbívej mì tady.}
{324}{}{Dávej si tu bacha. Místní nevypadají moc pøátelsky.}
{325}{}{Hehe. Nevìøil bych, e nìkdy spatøím San Francisco.}
{326}{}{Nevìøil bych, e vytáhneš starocha jako já na takovou cestu. Udìláme si to svoje a vrátíme se domù.}
{327}{}{Redding je dùlní mìsto. Tìí se tu hlavnì zlato. Jezdí odsud spousta karavan do Vault City.}
{328}{}{Broken Hills je dùlní mìsto. Tìí se tu hlavnì uranová ruda. Bejvá to tu docela drsnı, take si dávej bacha.}
{329}{}{Jsem nìjakej pøiotrávenej, nemáš nìjakej protijed?}
{330}{}{Svítím jako támhleten neon. Nemáš nìjakı antiradiaèní tablety?}
{331}{}{Jsem docela zranìnej. Nemáš nìjakı Stimpaky?}
{332}{}{Hlavnì ádnej fet, Myrone. Sleduju tì.}
{333}{}{Udìlej jeden špatnej krok, Myrone, a udìlám z tebe sekanou.}
{334}{}{Sakra, Lenny, potøebuješ vykoupat. Nebo nìjakou dezinfekci.}
{335}{}{Ghoulíku, radši se dr sakra dál. Fùùùùùj, ty ale smrdíš.}
{336}{}{To je ten nejzlejší pes, kterıho jsem kdy vidìl.}
{337}{}{Klídek, pejsku. Cassidy je tvùj kámoš, jasnı?}
{338}{}{Co asi takovej kyberpes jí? Nejspíš lidi.}
{339}{}{Jestli mì ten kyberpes zaène obskakovat nohu, tak ho na místì odprásknu.}
{340}{}{Áááách. Jsem tak rád, e vyrobili miliony tìchhle vìcí, ne spadly bomby.}
{341}{}{Díky, pøíteli.}
{342}{}{Doufám, e mi ty Stimpaky neudìlaj nic se srdcem...}
{343}{}{Co to sakr...?! Ne, moje srdce! Já...*rrrruuuup*}
{344}{}{Pardon, jen jsem se kochal vıhledem.}
{345}{}{Sakra, tak já si stoupnu támhle.}
{346}{}{Omlouvám se, pøíteli. Nechtìl jsem ti stát v cestì.}
{347}{}{Áááách. To je ono. Díky moc.}
{348}{}{*škyt* Hehe. Není nic lepšího na rozproudìní krve ne stará dobrá ohnivá voda.}
{349}{}{Díky. Sakra, nedáš si taky?}
{350}{}{Támhle je Vault. Obrovská blbá vìc, co?}
{351}{}{Chceš, abych se k tobì zase pøidal?}
{352}{}{Jsem pøipraven vyrazit, kdykoliv budeš chtít.}
{353}{}{Urèitì nepotøebuješ moji pomoc?}
{354}{}{U chci zase vyrazit.}
{355}{}{Dal bych cígo.}
{356}{}{Táta mì pojmenoval podle jednı postavy z nìjakıho pøedváleènıho komiksu. Øíkal, e to byl taky pìknej parchant.}
{357}{}{Je fajn bejt zase na cestách. Ze ivota ve Vault City jsem mìl u vøedy.}
{358}{}{Doufám, e mì na cestách nebude zlobit srdce...}
{359}{}{Dal bych si panáka.}
{360}{}{Radši si ještì zkontroluju vıbavu.}
{361}{}{Podìlaná artritida...}
{362}{}{Bejt o dvacet let mladší, vyrazil bych na vıchod a prozkoumal støedozápad. Mám pocit, e teï u je na to pozdì.}
{363}{}{Slyšel jsem, e maj na støedozápadì tornáda širokı nìkolik mil. Teï je z toho obrovská radioaktivní pánev.}
{364}{}{Jestlipak Texas pøeil válku...}
{365}{}{Díky, pøíteli. Já...jejda. Nìjak se mi mlí zrak.}
{366}{}{Slyšel jsem, e tohle vyvolává halucin...jéje! Kde se tu vzali ti hadi?!}
{367}{}{Kdykoliv si tohle dám, mám záblesky minulosti.}
{368}{}{Nic se nevyrovná troše divošskıho léèitelskıho umìní...}
{369}{}{Asi si budu muset pùjèit nìjakı berle a vozík.}
{370}{}{Cassidy zemøel na infarkt.}
{371}{}{Podaøilo se ti pøesvìdèit Cassidyho, aby se k tobì pøidal.}
{372}{}{Musím si vzít prášky na srdce...}
{1000}{Cas1000}{Well... all right, then. I'll wait here 'til you get back. }
{1100}{Cas1100}{Sure. Can't promise I won't pull it out again if there's trouble, though.}
{1200}{Cas1200}{All right, I'll stick close to you then. You must be expecting trouble.}
{1300}{Cas1300}{All right, I'll keep some distance. Get a better vantage point that way.}
{1400}{Cas1400}{All right, I'll be watching your back. You need me, holler, and I'll come running.}
{2000}{Cas2000}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{2100}{Cas2100}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{2200}{Cas2200}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{2300}{Cas2300}{Naw... you look like you got enough of a crowd already.}
{2400}{Cas2400}{All right, then.}
{2999}{}{Tak dobøe, dej na sebe pozor.}
{3000}{}{Mùeme vyrazit.}
{3100}{}{Zapomeò na to, kreténe.}
{3200}{}{Tak nic, tvoje mínus.}
{4100}{Cas4100}{Okay, everything's stitched up. I'm good to go.}
{4200}{Cas4200}{Okay, pretty much everything is patched up.}
{4300}{Cas4300}{That pretty much did it, but I could use a couple more stims.}
{4400}{Cas4400}{I used what I could, but I'm still pretty messed up. If you got any more stims to spare, I could sure use 'em. I can still walk, though.}
{9999}{}{Chci se zeptat na pár otázek...}
{10001}{}{Vezmi si pár Stimpakù a uzdrav se.}
{10002}{}{Cassidy, poèkej tady, ne se vrátím.}
{10003}{}{Schovej svoji zbraò.}
{10004}{}{Dr se blízko mì.}
{10005}{}{Moc se nevzdaluj.}
{10006}{}{Mìli bychom se trochu rozestoupit.}
{10007}{}{Tak pojïme.}
{10100}{}{Tak pojï, Cassidy. Je èas vyrazit.}
{20000}{Cas20000}{All right, I'm listening.}
{20001}{Cas20001}{My gear? What about it?}
{20002}{Cas20002}{No problem. Too hot for that kinda gear, anyway. Makes me sweat like a New Reno whore.}
{20003}{}{Zkusíme jiné rozestavìní.}
{20004}{}{Potøebuju si s tebou promluvit o tvé vıstroji.}
{20005}{}{Zapomeò na to. Tohle rozestavìní je v poøádku.}
{20006}{}{Vlastnì nic. Teï o tvé vıbavì nepotøebuju mluvit.}
{20007}{}{Potøebuju, aby sis sundal tu zbroj, co máš na sobì.}
