{100}{}{Vidíš špinavého, silně vypadajícího muže.}
{101}{}{Vidíš Connara.}
{102}{}{Hey you! What are you doing!}
{103}{}{Zůstaň, kde jsi, venkovane. Co tady pohledáváš?}
{104}{}{I'm killing off the monsters here.}
{105}{}{Proč, co je ti po tom?}
{106}{}{Proč ty řvát?}
{107}{}{I bet those bastards at Vault City sent you. Well you best be off, and leave everything else
 alive.}
{108}{}{No, na to už je trochu pozdě.}
{109}{}{Jak to?}
{110}{}{Promiň, ale je to moje práce.}
{111}{}{Those creatures are the only thing that are stopping Vault City from making us their so-called
 servants.}
{112}{}{Well they're paying me to get rid of the monsters, and that's what I'm going to do.}
{113}{}{To mi neřekli.}
{114}{}{Zaplatili mi za jejich vyhubení a už je to hotové.}
{115}{}{Ty idiote! Proč jsi to k čertu udělal!}
{116}{}{Potřebuju peníze.}
{117}{}{Víš, jestli to uděláš, tak si pro nás přijdou.}
{118}{}{To není můj problém.}
{119}{}{V tom případě doufám, že se nimi udusíš. Brzy si pro nás přijdou.}
{120}{}{Nevěděl jsem, že to chtěli udělat kvůli tomu.}
{121}{}{Jo, stejně nejednám s takovým póvlem, jako jsi ty.}
{122}{}{To ti nemůžeme dovolit.}
{123}{}{Když musíš, tak musíš.}
{124}{}{A ty jim to opravdu věříš? Máš se ještě co učit, příteli.}
{125}{}{Můžu nějak pomoct?}
{126}{}{Stráže Vault City nepatří k nejstatečnějším. Stačí se jen zmínit o souboji a utečou daleko za humny. Kdybychom měli pár zbraní, mohli bychom se jim postavit.}
{127}{}{What sort of guns?}
{128}{}{Well, I'm good with a shotgun, and we have some people in here that can handle a rifle. I think
 three of those would do.}
{129}{}{Uvidím, co se dá dělat.}
{130}{}{Nechceme tě tu. Odejdi.}
{131}{}{Myslím, že ne. S čím vám můžu pomoct?}
{132}{}{Jo, stejně tu už nebudeš moc dlouho.}
{133}{}{Jako by mě to zajímalo.}
{134}{}{Vítej zpátky! Máš pro nás ty zbraně?}
{135}{}{Co že to vlastně potřebujete?}
{136}{}{Jo, tady jsou.}
{137}{}{We need three rifles and a shotgun. The sooner you can get them to us, the better.}
{138}{}{Dobře.}
{139}{}{With these, we'll be able to make something of this place over the next months. If you ever need
 a place to rest, you will always be welcome here.}
{140}{}{Není zač.}
{141}{}{Welcome back. Things are going well. We're going to work on expanding the Village.}
{142}{}{Zdravíčko! Jak vidíš, jde to docela dobře. Klidně se porozhlédni kolem, pokud máš čas.}
{143}{}{Pořád ještě stavíme. Doufáme, že příští měsíc opět rozšíříme zdi.}
{144}{}{Greetings! The village has expanded again as we have hoped. You are welcome as always.}
{145}{}{We have nothing to fear from Vault City any longer, and will be able to live here in peace.
 Thank you again, wanderer.}
{146}{}{Ne že tam něco zabiješ, hlupáku.}
