{100}{}{Vidíš špinavého, silnì vypadajícího muže.}
{101}{}{Vidíš Connara.}
{102}{}{Hey you! What are you doing!}
{103}{}{Zùstaò, kde jsi, venkovane. Co tady pohledáváš?}
{104}{}{I'm killing off the monsters here.}
{105}{}{Proè, co je ti po tom?}
{106}{}{Proè ty øvát?}
{107}{}{I bet those bastards at Vault City sent you. Well you best be off, and leave everything else
 alive.}
{108}{}{No, na to už je trochu pozdì.}
{109}{}{Jak to?}
{110}{}{Promiò, ale je to moje práce.}
{111}{}{Those creatures are the only thing that are stopping Vault City from making us their so-called
 servants.}
{112}{}{Well they're paying me to get rid of the monsters, and that's what I'm going to do.}
{113}{}{To mi neøekli.}
{114}{}{Zaplatili mi za jejich vyhubení a už je to hotové.}
{115}{}{Ty idiote! Proè jsi to k èertu udìlal!}
{116}{}{Potøebuju peníze.}
{117}{}{Víš, jestli to udìláš, tak si pro nás pøijdou.}
{118}{}{To není mùj problém.}
{119}{}{V tom pøípadì doufám, že se nimi udusíš. Brzy si pro nás pøijdou.}
{120}{}{Nevìdìl jsem, že to chtìli udìlat kvùli tomu.}
{121}{}{Jo, stejnì nejednám s takovým póvlem, jako jsi ty.}
{122}{}{To ti nemùžeme dovolit.}
{123}{}{Když musíš, tak musíš.}
{124}{}{A ty jim to opravdu vìøíš? Máš se ještì co uèit, pøíteli.}
{125}{}{Mùžu nìjak pomoct?}
{126}{}{Stráže Vault City nepatøí k nejstateènìjším. Staèí se jen zmínit o souboji a uteèou daleko za humny. Kdybychom mìli pár zbraní, mohli bychom se jim postavit.}
{127}{}{What sort of guns?}
{128}{}{Well, I'm good with a shotgun, and we have some people in here that can handle a rifle. I think
 three of those would do.}
{129}{}{Uvidím, co se dá dìlat.}
{130}{}{Nechceme tì tu. Odejdi.}
{131}{}{Myslím, že ne. S èím vám mùžu pomoct?}
{132}{}{Jo, stejnì tu už nebudeš moc dlouho.}
{133}{}{Jako by mì to zajímalo.}
{134}{}{Vítej zpátky! Máš pro nás ty zbranì?}
{135}{}{Co že to vlastnì potøebujete?}
{136}{}{Jo, tady jsou.}
{137}{}{We need three rifles and a shotgun. The sooner you can get them to us, the better.}
{138}{}{Dobøe.}
{139}{}{With these, we'll be able to make something of this place over the next months. If you ever need
 a place to rest, you will always be welcome here.}
{140}{}{Není zaè.}
{141}{}{Welcome back. Things are going well. We're going to work on expanding the Village.}
{142}{}{Zdravíèko! Jak vidíš, jde to docela dobøe. Klidnì se porozhlédni kolem, pokud máš èas.}
{143}{}{Poøád ještì stavíme. Doufáme, že pøíští mìsíc opìt rozšíøíme zdi.}
{144}{}{Greetings! The village has expanded again as we have hoped. You are welcome as always.}
{145}{}{We have nothing to fear from Vault City any longer, and will be able to live here in peace.
 Thank you again, wanderer.}
{146}{}{Ne že tam nìco zabiješ, hlupáku.}
