{100}{}{Vidíš jednoho z obyvatel vesnice.}
{101}{}{Vidíš jednoho z obyvatel vesnice.}
{102}{}{Ahoj.}
{103}{}{Hezký den.}
{104}{}{Vítej v naší vesnici.}
{105}{}{Tyhle monstra nás chrání.}
{106}{}{Pospěš si zpět.}
{107}{}{Ty zbraně budeme už brzy potřebovat.}
{108}{}{Ahoj.}
{109}{}{Teď vypadni!}
{110}{}{Vraťte se, odkud jste přišli.}
{111}{}{Vypadni sakra odsud!}
{112}{}{Teď už jsme v bezpečí.}
{113}{}{Díky.}
{114}{}{Bůh ti žehnej, poutníku.}
