{100}{}{Vidíš malého veselého mue.}
{101}{}{Vidíš Šastného Harryho, majitele obchodu.}
{102}{}{Zdravíèko... co pro tebe mùu udìlat?}
{103}{}{Chci obchodovat. Mùu vidìt, co nabízíš?}
{104}{}{Ten pluh venku je poøád na prodej?}
{105}{}{Já koupit.}
{106}{}{Dnes nic, díky.}
{107}{}{Promiò. Nemùu ti pomoct, sousede.}
{108}{}{Ano, je. Mùu ti ho nechat za... øeknìme, osm set.}
{109}{}{Dám ti za nìj šest set.}
{110}{}{Dohodnuto. To beru.}
{111}{}{Eh, osm set? Vydr, vrátím se... s penìzi.}
{112}{}{Zapomeò na to. Jen a si Smithovi hladoví.}
{113}{}{Je tvùj. (Dá si do kapsy peníze.) Vezmeš si ho hned, nebo ho chceš nìkam dopravit?}
{114}{}{Doprav ho ke Smithovım.}
{115}{}{Promiò, pøíteli. Bude tì to stát osm set.}
{119}{}{Na zaplacení potøebuješ peníze, pøíteli.}
{120}{}{Vrátím se s penìzi.}
{121}{}{ádnı problém. Hned ho tam nechám dopravit.}
{122}{}{Chtìli jsme si pøilepšit, co? Zatracenej zlodìji... stráe! Stráe!}
