{100}{}{Vidíš malého veselého muže.}
{101}{}{Vidíš Šťastného Harryho, majitele obchodu.}
{102}{}{Zdravíčko... co pro tebe můžu udělat?}
{103}{}{Chci obchodovat. Můžu vidět, co nabízíš?}
{104}{}{Ten pluh venku je pořád na prodej?}
{105}{}{Já koupit.}
{106}{}{Dnes nic, díky.}
{107}{}{Promiň. Nemůžu ti pomoct, sousede.}
{108}{}{Ano, je. Můžu ti ho nechat za... řekněme, osm set.}
{109}{}{Dám ti za něj šest set.}
{110}{}{Dohodnuto. To beru.}
{111}{}{Eh, osm set? Vydrž, vrátím se... s penězi.}
{112}{}{Zapomeň na to. Jen ať si Smithovi hladoví.}
{113}{}{Je tvůj. (Dá si do kapsy peníze.) Vezmeš si ho hned, nebo ho chceš někam dopravit?}
{114}{}{Doprav ho ke Smithovým.}
{115}{}{Promiň, příteli. Bude tě to stát osm set.}
{119}{}{Na zaplacení potřebuješ peníze, příteli.}
{120}{}{Vrátím se s penězi.}
{121}{}{Žádný problém. Hned ho tam nechám dopravit.}
{122}{}{Chtěli jsme si přilepšit, co? Zatracenej zloději... stráže! Stráže!}
