{100}{}{Vidíš staříka se známkami šílenství.}
{101}{}{Vidíš Starého Joea, místního blázna.}
{102}{}{Ahoj. Dlouho jsme se neviděli.}
{103}{}{My se známe?}
{104}{}{Jo, jasně. Už to bude nějaká doba. Co jsi celou tu dobu dělal?}
{105}{}{No, už to bude nějaká doba. Co jsi celou tu dobu dělal?}
{106}{}{To a taky tamto. Odkud mě znáš?}
{107}{}{Podívej, staříku, vůbec nevím, kdo sakra jsi.}
{108}{}{Jo, to teda. No, potuloval jsem se všude možně a nakonec jsem skončil tady na tomhle bohem zapomenutým místě. Už to není jako za starejch dobrejch časů. Už ne, kamaráde.}
{109}{}{Jó, starý dobrý časy. Vzpomínáš, jak jsme tenkrát...}
{110}{}{Už to není jako dřív, to teda ne. Poslyš... co máme vlastně společného?}
{111}{}{Ty si na mě nevzpomínáš, že ne? No, zdáš se mi trošku moc mladej.}
{112}{}{Co se mi tím snažíš říct?}
{113}{}{Ale vypadáš tak povědomě. Ach, moje oči už nejsou to, co bývaly. No nic, přeju hezkej den.}
{114}{}{Eh, jo... sbohem.}
{115}{}{Jo, udělali jsme Vůdci ze života peklo, že jo? Ale po tvým odchodu to šlo pěkně do sraček. Musel jsem se přestěhovat a změnit si jméno. Co se stalo s tebou?}
{116}{}{Užíval jsem si života v jedné malé vesničce.}
{117}{}{No, radši si tu dávej na sebe bacha. Už to není taková sranda jako dřív. Radši si hlídej zadek.}
{118}{}{Dobře, díky.}
{119}{}{Jo, chvíli jsem hledal ten tvůj Vault, ale nikdy jsem ho nenašel. Máš nějaký zajímavý historky pro svýho starýho přítele Iana?}
{120}{}{Iana?}
{121}{}{Jo, Ian. Nevzpomínáš si na mě? Už je to pár let. Člověk by si myslel, že se nedá zapomenout na svýho nejlepšího kámoše. Teda... až na to střílení do zad. Za to se ti ještě jednou omlouvám.}
{122}{}{Promiň, ale ty si nejspíš myslíš, že jsem Zakladatel. Moje vesnice byla založena člověkem, který pocházel z Vaultu.}
{123}{}{Aha, tak teď už to dává trošku větší smysl. No, jsem rád, že měl můj přítel dobrej život. Starej Ian má pro tebe radu. Dávej tam venku na sebe pozor. Tohle místo není tak skvělý, jak se zdá. }
{124}{}{Co se tady děje?}
{125}{}{No, Občané Vault City si o sobě hodně myslí a moc se nezajímají o lidi, jako jsem já nebo ty. Tohle si vezmi. Ochrání tě, když se věci trochu vymknou z ruky. Poslyš, asi by tě neměli vidět, jak mluvíš se starým šílencem, takže bude lepší, když už půjdeš.}
{126}{}{Díky za pomoc.}
{127}{}{Nech starýho muže odpočívat.}
{128}{}{Vypadáš tak povědomě...}
{129}{}{Nech mě teď o samotě.}
{130}{}{Radši odejdi.}
{131}{}{Budou tě podezírat, jestli spolu budeme dál mluvit.}
{132}{}{Běž už. Ať je na tebe můj starý přítel hrdej.}
