{100}{}{Vidíš staøíka se známkami šílenství.}
{101}{}{Vidíš Starého Joea, místního blázna.}
{102}{}{Ahoj. Dlouho jsme se nevidìli.}
{103}{}{My se známe?}
{104}{}{Jo, jasnì. U to bude nìjaká doba. Co jsi celou tu dobu dìlal?}
{105}{}{No, u to bude nìjaká doba. Co jsi celou tu dobu dìlal?}
{106}{}{To a taky tamto. Odkud mì znáš?}
{107}{}{Podívej, staøíku, vùbec nevím, kdo sakra jsi.}
{108}{}{Jo, to teda. No, potuloval jsem se všude monì a nakonec jsem skonèil tady na tomhle bohem zapomenutım místì. U to není jako za starejch dobrejch èasù. U ne, kamaráde.}
{109}{}{Jó, starı dobrı èasy. Vzpomínáš, jak jsme tenkrát...}
{110}{}{U to není jako døív, to teda ne. Poslyš... co máme vlastnì spoleèného?}
{111}{}{Ty si na mì nevzpomínáš, e ne? No, zdáš se mi trošku moc mladej.}
{112}{}{Co se mi tím snaíš øíct?}
{113}{}{Ale vypadáš tak povìdomì. Ach, moje oèi u nejsou to, co bıvaly. No nic, pøeju hezkej den.}
{114}{}{Eh, jo... sbohem.}
{115}{}{Jo, udìlali jsme Vùdci ze ivota peklo, e jo? Ale po tvım odchodu to šlo pìknì do sraèek. Musel jsem se pøestìhovat a zmìnit si jméno. Co se stalo s tebou?}
{116}{}{Uíval jsem si ivota v jedné malé vesnièce.}
{117}{}{No, radši si tu dávej na sebe bacha. U to není taková sranda jako døív. Radši si hlídej zadek.}
{118}{}{Dobøe, díky.}
{119}{}{Jo, chvíli jsem hledal ten tvùj Vault, ale nikdy jsem ho nenašel. Máš nìjakı zajímavı historky pro svıho starıho pøítele Iana?}
{120}{}{Iana?}
{121}{}{Jo, Ian. Nevzpomínáš si na mì? U je to pár let. Èlovìk by si myslel, e se nedá zapomenout na svıho nejlepšího kámoše. Teda... a na to støílení do zad. Za to se ti ještì jednou omlouvám.}
{122}{}{Promiò, ale ty si nejspíš myslíš, e jsem Zakladatel. Moje vesnice byla zaloena èlovìkem, kterı pocházel z Vaultu.}
{123}{}{Aha, tak teï u to dává trošku vìtší smysl. No, jsem rád, e mìl mùj pøítel dobrej ivot. Starej Ian má pro tebe radu. Dávej tam venku na sebe pozor. Tohle místo není tak skvìlı, jak se zdá. }
{124}{}{Co se tady dìje?}
{125}{}{No, Obèané Vault City si o sobì hodnì myslí a moc se nezajímají o lidi, jako jsem já nebo ty. Tohle si vezmi. Ochrání tì, kdy se vìci trochu vymknou z ruky. Poslyš, asi by tì nemìli vidìt, jak mluvíš se starım šílencem, take bude lepší, kdy u pùjdeš.}
{126}{}{Díky za pomoc.}
{127}{}{Nech starıho mue odpoèívat.}
{128}{}{Vypadáš tak povìdomì...}
{129}{}{Nech mì teï o samotì.}
{130}{}{Radši odejdi.}
{131}{}{Budou tì podezírat, jestli spolu budeme dál mluvit.}
{132}{}{Bì u. A je na tebe mùj starı pøítel hrdej.}
