{100}{}{Vidíš seranta Starka.}
{101}{}{Vidíš ohromného èernocha v tìké zbroji. Pozornì tì sleduje.}
{102}{}{Vidíš seranta Starka.}
{103}{}{Vidíš ohromného èernocha v tìké zbroji. Pozornì tì sleduje.}
{104}{}{Dobrá práce tam dole na jihu. Vidìl jsem ten ohòostroj a sem.}
{105}{}{Dobrı den... pane.}
{106}{}{Vault City vdy zvítìzí... pane.}
{107}{}{Zdravíèko, Obèane.}
{108}{}{Vault City vdy zvítìzí, Obèane.}
{109}{}{Budete litovat, e jste pøišel do mìsta... stráe!}
{110}{}{Mutant! Stráe!}
{111}{}{Ghoul! Stráe!}
{112}{}{Musím ještì vyplnit ty seznamy munice...}
{113}{}{Zítra musím ještì zkontrolovat skøíòky se zbranìmi dole ve Vaultu...}
{114}{}{Moná, e vás vìzení nauèí, jak se chovat.}
{115}{}{A ZÙSTANETE tu tak dlouho, dokud vám První Obèanka neudìlí milost.}
{116}{}{Omlouvám se, Obèane, ale nikdo nemá pøístup do Nápravného zaøízení po setmìní. Vrate se ráno.}
{117}{}{Je po návštìvních hodinách. Co dìláte v tuhle dobu ve mìstì?}
{118}{}{No jó!}
{119}{}{Eh, jako Obèan mùu pobıvat ve mìstì i po setmìní.}
{120}{}{Jen jsem musel pøed odchodem vyøešit jednu záleitost.}
{121}{}{Právì odcházím.}
{122}{}{Opravdu? Znám KADÉHO Obèana ve Vault City a vás nepoznávám. Kde máte doklady?}
{123}{}{Chcete moje doklady? Tak si pro nì pojïte.}
{124}{}{Nemám je u sebe.}
{125}{}{Tady je.}
{126}{}{Tak mì pøestaòte zdrovat, "Obèane." No tak, pohnìte sebou.}
{127}{}{Pro dnešek konèíte. No tak, pohnìte sebou.}
{128}{}{Nikam nepùjdu. Zkuste na mì sáhnout a budete toho litovat.}
{129}{}{Dobrá, u jdu.}
{130}{}{Kapitáne. Mùu vám pomoct... pane?}
{131}{}{Mohu vám pomoci, Obèane?}
{132}{}{Co chceš?}
{133}{}{No jó!}
{134}{}{Odbelhat se.}
{135}{}{Kdo jsi?}
{136}{}{Nic, promiò, e ruším.}
{137}{}{Pojïte se mnou, chlapèe. IHNED.}
{138}{}{Pojïte se mnou, sleèno. IHNED.}
{139}{}{Já odejít? Já odejít!}
{140}{}{JÁ NE JÍT. TEÏ.}
{141}{}{Budete litovat, e jste tu zùstal.}
{142}{}{JÁ NE JÍT PRYÈ.}
{143}{}{Serant Stark... pane. Potøebujete nìco?}
{144}{}{Jsem Obèan SERANT Stark, Obèane. Mùu vám s nìèím pomoct?}
{145}{}{Jsem Obèan SERANT Stark, venkovane. Co chcete?}
{146}{}{Co tady dìláš?}
{147}{}{Mùete mi øíct, kde je Vault?}
{148}{}{Nic, promiò, e ruším.}
{149}{}{Dìlám VAŠI práci, pane.}
{150}{}{Vedu Nápravné zaøízení. A poslouchám vaše rozkazy, pane.}
{151}{}{Vedu Nápravné zaøízení. Drím venkovany za hranicemi mìsta. Dohlíím na to, aby se sluebníci chovali slušnì. Organizuji hlídky. Pokouším se ochránit mìsto pøed nájezdníky.}
{152}{}{Máte nìjakı problém, serante?}
{153}{}{Nejste vy náhodou ten, co rozmlátil Cassidymu bar?}
{154}{}{Neslyšel jste o sluebníkovi jménem Joshua?}
{155}{}{Hlídky?}
{156}{}{Nájezdníky?}
{157}{}{O tìch nájezdnících...}
{158}{}{Mùu se tì na nìco zeptat?}
{159}{}{Díky. Sbohem.}
{160}{}{Povolení mluvit otevøenì, pane.}
{161}{}{Udìleno.}
{162}{}{Ne. Nejdøív mám na vás pár otázek.}
{163}{}{Dnes ne, serante.}
{164}{}{Svoji hodnost si NEZASLOUÍTE. iju ve Vault City celı svùj ivot. MOJI podøízení mi vìøí a respektují mì, vás nikoliv... pane.}
{165}{}{A to je pøesnì ten dùvod, proè vás potøebuju na vaší pozici, serante. Není pochyb o tom, e jste schopnı a znáte Vault City lépe ne já. Nicménì jsem vám ukázal PØÍPADY, kdy tomu tak NEBYLO. Nikdy na to nezapomeòte.}
{166}{}{Beru na vìdomí, serante. Teï mám na vás nìjaké otázky.}
{167}{}{Beru na vìdomí, serante. Doporuèuju vám, abyste spolkl svoje námitky a pokraèoval ve své práci. Hezkı den.}
{168}{}{Rozumím, pane.}
{169}{}{A teï mám na vás nìjaké otázky.}
{170}{}{Pokraèujte, serante.}
{171}{}{Ano, pane. Organizoval jsem povolenou razii v podniku pana Cassidyho.}
{172}{}{Moná vám váš pøítel Cassidy neøekl, e ve svém podniku pøechovával nedovolené látky a jeho licence k prodeji alkoholu vypršela. Nezapomnìl jste to øíct svému pøíteli, Cassidy?}
{173}{}{Cassidy øíká, e mìl všechno zaplacené a vy jste jeho obchod stejnì vyraboval.}
{174}{}{Zapomeòte na to. Chci se ještì na nìco zeptat...}
{175}{}{Tak na to zapomeòte. Sbohem.}
{176}{}{Ne, pane. Pan Cassidy nezaplatil licenèní poplatek k prodeji alkoholu za poslední mìsíc a pøitom ho stále prodával. Vıpis jeho plateb je zapsán v poèítaèi.}
{177}{}{Cassidy je vinen z neoprávnìného prodeje alkoholu bez licence. Jestli se mu to nelíbí, mùe odejít z Vault City. Jednoduché jak facka.}
{178}{}{Vìøím vám, serante. Dobrá práce. A teï mì poslouchejte: Chci, abyste se panu Cassidymu omluvil, vymazal jeho trestní rejstøík a zaplatil mu za škody, které jste zpùsobil v jeho podniku.}
{179}{}{Víte, myslím, e moje pìst a váš ksicht si spolu chtìjí popovídat.}
{180}{}{Zapomeòte na to. Chci se ještì na nìco zeptat...}
{181}{}{Zapomeòte na to. Nashledanou.}
{182}{}{Díky za pomoc, pøíteli. Stark je pìknì tvrdohlavej zkurvysyn.}
{183}{}{To si mùete zkusit. Tìším se, a s vámi a Cassidym provedu krátkej proces.}
{184}{}{Fajn. Stejnì jsem se tìšil na to, a vám budu moct nakopat prdel.}
{185}{}{Zapomeòte na to. Chci se ještì na nìco zeptat...}
{186}{}{Zapomeòte na to. Nashledanou.}
{187}{}{Ano... PANE.}
{188}{}{IHNED, serante.}
{189}{}{Tak do toho, serante. Hejbnìte sebou.}
{190}{}{Hotovo, PANE.}
{191}{}{A teï se vás chci na nìco zeptat, serante.}
{192}{}{Vıbornì, serante. Jen tak dál.}
{193}{}{Jo, to je jeden z tìch opilıch venkovanù, co zaútoèili na moje stráe pøi té rvaèce ve Spittoonu. Skonèil jako sluebník v Centru pro rozdìlování sluebníkù... zavøenı. Je to tou ulicí dolù.}
{194}{}{Chci se ještì na nìco zeptat...}
{195}{}{Hmmm. Pùjdu se tam teï podívat.}
{196}{}{Vault je hned za dveømi... pane.}
{197}{}{Vault je hned za dveømi. Staèí øíct stráím, e jste Obèan a nechají vás projít.}
{198}{}{Vault je hned za dveømi, ale dovnitø mají pøístup pouze Obèané, take ne abych vás pøistihl, jak otravujete stráe.}
{199}{}{Mùu se vás zeptat na nìco jiného?}
{200}{}{Ale já jsem Obèan.}
{201}{}{Jak jste pøišel k Obèanství?}
{202}{}{Díky. Sbohem.}
{203}{}{Opravdu? Nepoznávám vás a to znám kadého Obèana ve Vault City.}
{204}{}{Tady jsou mé doklady. Myslím, e jsou v poøádku.}
{205}{}{Eh, zapomeòte na to. Chci se ještì na nìco zeptat...}
{206}{}{Radìji u pùjdu.}
{207}{}{Ale ale, jestlipak tohle nejsou ty doklady, které nìkdo minulı mìsíc ukradl. Vypadá to, e jsem koneènì našel pachatele. Pùjdete se mnou, venkovane.}
{208}{}{Dotknìte se mì a budete toho litovat.}
{209}{}{No jo, vdy u jdu. Pøestaòte do mì strkat.}
{210}{}{NARODIL jsem se jako Obèan. Chcete se stát Obèanem? Tak zajdìte za nìjakım èlenem rady.}
{211}{}{Mùu se vás zeptat na nìco jiného?}
{212}{}{To udìlám, díky. Nashle.}
{213}{}{Jo, co je s nimi?}
{214}{}{Podaøilo se mi najít jejich základnu.}
{215}{}{Vyhladil jsem je.}
{216}{}{Máte nìjakou pøedstavu, kde se ti nájezdníci zdrují?}
{217}{}{To je jedno. Chci se na nìco zeptat...}
{218}{}{Zapomeòte na to. Moná si popovídáme nìkdy jindy.}
{219}{}{Opravdu? Kde je?}
{220}{}{Ano, to u jsem slyšel. Øeknìte to První Obèance, pokud jste spolu ještì nemluvili.}
{221}{}{V horskıch jeskynních systémech dole na jihu. Tady, ukáu vám to...}
{222}{}{Chci se ještì na nìco zeptat.}
{223}{}{Dobøe. Pùjdu si s ní popovídat.}
{224}{}{Vy jste je vyhladil?}
{225}{}{Ano, to u jsem slyšel. Øeknìte to První Obèance, pokud jste spolu ještì nemluvili.}
{226}{}{Jo, Vault City se jich u nemusí obávat.}
{227}{}{Chci se ještì na nìco zeptat.}
{228}{}{Dobøe. Pùjdu si s ní popovídat.}
{229}{}{Jdìte to okamitì øíct První Obèance. O tomhle bude chtít vìdìt co nejdøíve.}
{230}{}{Chci se nejdøív na nìco zeptat.}
{231}{}{Dobøe. Pùjdu si s ní popovídat.}
{232}{}{Jo, nájezdníci. Poslední dobou na nás útoèí dost tvrdì. (Zamraèí se.) Proè se na nì vlastnì ptáte?}
{233}{}{Chci se pokusit najít jejich základnu a zastavit jejich útoky.}
{234}{}{Jen ze zvìdavosti.}
{235}{}{To je jedno. Chci se na nìco zeptat...}
{236}{}{Zapomeòte na to. Moná si popovídáme nìkdy jindy.}
{237}{}{Co, vy jste nìjakej dobrodinec nebo co? Tomu nevìøím.}
{238}{}{Nejsem dobrodinec. Ve skuteènosti pocházím z Arroya... to je vesnice na západì.}
{239}{}{Rád pomùu, kdy mùu.}
{240}{}{Podívejte, iju na tomhle svìtì u dost dlouho a vím, e kadá pomoc se èlovìku nìkdy v budoucnu vrátí.}
{241}{}{To je jedno. Chci se na nìco zeptat...}
{242}{}{Zapomeòte na to. Moná si popovídáme nìkdy jindy.}
{243}{}{Co, chcete tu ze sebe dìlat chytráka? Opravdu?}
{244}{}{Eh, jo? No ale postavit se takové bandì mùe bıt nad vaše síly.}
{245}{}{Ne, ale pokud potøebujete pomoc, pomùu vám.}
{246}{}{I pøesto chci pomoct.}
{247}{}{Tak na to zapomeòte. Chci se na nìco zeptat...}
{248}{}{Zapomeòte na to. Moná si popovídáme nìkdy jindy.}
{249}{}{Hmmm. Dobrá, v tom pøípadì neodmítnu pomoc. A najdete jejich základnu, nebo je dokonce vyhladíte, øeknìte to První Obèance.}
{250}{}{Ve skuteènosti se mi u podaøilo najít jejich základnu.}
{251}{}{Ve skuteènosti jsou u všichni nájezdníci mrtví.}
{252}{}{Máte nìjakou pøedstavu, kde se ti nájezdníci zdrují?}
{253}{}{Tak dobøe. Chci se ještì zeptat...}
{254}{}{Samozøejmì.}
{255}{}{Tak ze zvìdavosti, jo? Taky jsem zvìdavı. Co vlastnì víte o tìch nájezdnících?}
{256}{}{Chci se pokusit najít jejich základnu a zastavit jejich útoky.}
{257}{}{Nevím o nich nic. Proto se vás taky ptám.}
{258}{}{To je jedno. Chci se na nìco zeptat...}
{259}{}{Zapomeòte na to. Moná si popovídáme nìkdy jindy.}
{260}{}{Nic o nich nevíte? Moná bych si vás mìl nechat v Nápravném zaøízení, dokud si na nìco NEVZPOMENETE.}
{261}{}{Chci se pokusit najít jejich základnu a zastavit jejich útoky.}
{262}{}{Dostal jste mì. Jsem oèividnì ve spolèení s tìmi nájezdníky. Zatknìte mì.}
{263}{}{Podívejte, odcházím odsud. A jestli se mì pokusíte zastavit, budete mít problémy.}
{264}{}{Vy u máte problémy. Chcete, aby to bylo ještì horší?}
{265}{}{Ne, chci se pokusit najít jejich základnu a zastavit jejich útoky.}
{266}{}{Dostal jste mì. Jsem oèividnì ve spolèení s tìmi nájezdníky. Zatknìte mì.}
{267}{}{Odcházím. Chcete mì zastavit? Tak si poslute.}
{268}{}{Tak dobøe...}
{269}{}{Prr! Poèkej! Tak jsem to...}
{270}{}{Tak se uka, sráèi.}
{271}{}{Myslím, e se tomuto tématu tak jednoduše nevyhnete. Take, co o tìch nájezdnících víte?}
{272}{}{Chci se pokusit najít jejich základnu a zastavit jejich útoky.}
{273}{}{Jen ze zvìdavosti.}
{274}{}{Podívejte, odcházím odsud. A jestli se mì pokusíte zastavit, budete mít problémy.}
{275}{}{Nevím. S tìmi nájezdníky je to nìjaké podivné. POKUD jsou to vùbec nájezdníci.}
{276}{}{Co tím myslíš?}
{277}{}{Chci se ještì zeptat...}
{278}{}{U musím jít.}
{279}{}{Mají zbranì velkého kalibru. Drahé zbranì. Znají vojenské taktiky. Bojují ve formaci. Jejich linie palby se nikdy nekøíí a pokadé se zastaví tìsnì pøed prolomením naší obrany.}
{280}{}{Eh... zastaví se tìsnì pøed prolomením obrany?}
{281}{}{Chci se ještì zeptat...}
{282}{}{U musím jít.}
{283}{}{Pøesnì tak. Pøi posledním útoku vyøadili z provozu laserovou vì v západním kvadrantu. Mìli volnı pøístup do mìsta. Poté jsem si všiml, jak jeden z jejich "kapitánù" vydává ROZKAZ, aby se stáhli zpìt. Nedává to ádnı smysl.}
{284}{}{Máte nìjakou pøedstavu, kde se ti nájezdníci zdrují?}
{285}{}{Hmmm. Chci se ještì zeptat...}
{286}{}{Zajímavé. Musím u jít.}
{287}{}{Ne. A to je to, co mì nejvíc frustruje. Obvykle ustupují na jih, ale na prùzkum té oblasti nemám dost muù. Myslím, e mají nájezdníci nìjakého místního prùvodce, kterı je provádí jiními kaòony.}
{288}{}{Co je na jihu?}
{289}{}{Hmmm. Chci se ještì zeptat...}
{290}{}{Zajímavé. Musím u jít.}
{291}{}{Je tam spousta míst, kde se dá ukrıt. To místo je jeskynìmi prodìravìlé jak ementál.}
{292}{}{Moná se je mùu pokusit najít.}
{293}{}{Chci se ještì zeptat...}
{294}{}{Hmmm. Budu si to pamatovat. Sbohem.}
{295}{}{Tak jen do toho. Zkuste to. Vsadím se, e jedinı zpùsob, jak je najít, je ten, e nám sami dají mapu.}
{296}{}{Chci se ještì zeptat...}
{297}{}{Pokud je to všechno... tak díky za informace.}
{298}{}{Jo, mám málo hlídek. Stìí dám dohromady mue k ochranì Vault City. Na rekognoskaci mi u nikdo nezbıvá.}
{299}{}{Rekog-no-co?}
{300}{}{Hodnì cestuju. Mùu vám s nìèím pomoct?}
{301}{}{To je mi líto. Chci se ještì na nìco zeptat...}
{302}{}{Tak na to zapomeòte. Sbohem.}
{303}{}{Prùzkum.}
{304}{}{Co tím myslíš?}
{305}{}{Mùu pro vás provést prùzkum, pokud na to nemáte dost lidí.}
{306}{}{Zapomeòte na to. Chci se ještì na nìco zeptat...}
{307}{}{Tak na to zapomeòte. Sbohem.}
{308}{}{Ne, na takovou práci potøebujete Pip-Boy a zrovna teï nemùu ádnı postrádat.}
{309}{}{Já mám Pip-Boy. Je starı... a má svoje vrtochy... a všude z nìj èouhají dráty a tlaèítka... ale je funkèní.}
{310}{}{No, tak dobøe. Chci se ještì na nìco zeptat...}
{311}{}{Tak na to zapomeòte. Sbohem.}
{312}{}{Jo? A má nainstalovanou mapu severní Kalifornie?}
{313}{}{Ano. Tedy, alespoò to tak na tı zatracenı vìci vypadá.}
{314}{}{Pak mám pro vás práci. Potøebuju nìkoho, kdo prozkoumá oblast kolem Gecka... to táboøištì ghoulù na severovıchodì. Projdìte osm sektorù na mapì svìta kolem mìsta a pak mi podejte hlášení.}
{315}{}{Jak to?}
{316}{}{ádnı problém. U je ta oblast prozkoumaná.}
{317}{}{Dobøe. Vrátím se, a tu oblast prozkoumám.}
{318}{}{Kdy o tom tal pøemıšlím, radìji se mnou nepoèítejte. Sbohem.}
{319}{}{Pokud budou nadále zneèisovat naši podzemní vodu, budeme moná muset zahájit vojenskou operaci.}
{320}{}{Chci zjistit rozsah škod zpùsobenıch roztavením elektrárny.}
{321}{}{Moná budeme nuceni proti nim zahájit vojenskou operaci, obzvláš pokud zaènou opìt zneèišovat naši podzemní vodu.}
{322}{}{Tak chcete tu práci nebo ne?}
{323}{}{Ano. Stejnì je ta oblast u prozkoumaná.}
{324}{}{Tu práci beru. A to bude hotové, podám hlášení.}
{325}{}{Tu práci beru. Nejdøív se chci ale na nìco zeptat...}
{326}{}{Ne díky. Moná nìkdy jindy.}
{327}{}{Opravdu? Hehe. No... tak dobøe.}
{328}{}{Dobrá práce. Nahrajte informace do mého Pip-Boye a já je nahraju do policejního poèítaèe.}
{329}{}{Tak dobøe...}
{330}{}{Vaše hlášení vypadá dobøe. Dobrá práce. Tady máte odmìnu... tøi sta dolarù.}
{331}{}{Skvìle... nemáte pro mì ještì nìjakou práci?}
{332}{}{Skvìlé. Chci se ještì na nìco zeptat...}
{333}{}{Díky. S tebou je radost obchodovat.}
{334}{}{Jo, vlastnì... potøebuju nìkoho poslat do NCR. Poslední dobou dostávám hlášení, e moná zvyšují svoje vojenské stavy. A u je to pravda nebo ne, potøebuju nìkoho, kdo se vydá do NCR a pak mi podá hlášení.}
{335}{}{ádnı problém. U je to hotové.}
{336}{}{Jen cesta do NCR a pak se vrátit zpìt?}
{337}{}{Zapomeòte na to. Chci se ještì na nìco zeptat...}
{338}{}{Ne, díky. Sbohem.}
{339}{}{Pøesnì to mi staèí. Zajímám se spíš o samotnou cestu ne o Republiku, ale i tak budu potøebovat, abyste vstoupil do mìsta, a tam dorazíte.}
{340}{}{ádnı problém. U je to hotové.}
{341}{}{Tu práci beru. A to bude hotové, podám hlášení.}
{342}{}{Tu práci beru. Chci se ještì na nìco zeptat ne odejdu...}
{343}{}{Ne dìkuju. Chci se ještì na nìco zeptat...}
{344}{}{Myslím, e tu práci nechci. Moná nìkdy jindy.}
{345}{}{Opravdu? Hehe.}
{346}{}{Vıbornì. Nahrajte informace do mého Pip-Boye a já je nahraju do policejního poèítaèe.}
{347}{}{Tak dobøe.}
{348}{}{Vaše hlášení vypadá dobøe. Dobrá práce. Tady máte odmìnu... pìt set dolarù... a tady ještì nìco navíc. Mohlo by se vám to hodit.}
{349}{}{Co to je?}
{350}{}{Je to Vault-Tec detektor pohybu. Chtìli jsme ho rozebrat na souèástky, jeliko je pøíliš starı pro naše Pip-Boye, ale zdá se, e je s vaším modelem kompatibilní.}
{351}{}{Jak to funguje?}
{352}{}{Staèí ho dret v ruce a kdy ho zapnete, ukáe vám všechny nepøátele v blízkém okolí. Nebo si staèí vyvolat automapu v Pip-Boyi, cvaknout na tlaèítko "scanner" a nepøátelé se rozsvítí jako vánoèní stromeèek.}
{353}{}{Díky, to se mùe hodit. Mùu se ještì na nìco zeptat?}
{354}{}{Tisíceré díky. Jdu to vyzkoušet.}
{355}{}{Dobrı den... Kapitáne. Potøebujete nìco?}
{356}{}{Vítejte zpìt, Obèane. Mùu vám s nìèím pomoct?}
{357}{}{U jste zase zpìt? Potøebujete nìco, nebo jen bloudíte?}
{358}{}{Na co... pane?}
{359}{}{Ano, Obèane. Co chcete vìdìt?}
{360}{}{Napøíklad?}
{361}{}{Umbaj kví}
{362}{}{Odbelhat se.}
{363}{}{Máte nìjakı problém, serante?}
{364}{}{Nejste vy náhodou ten, co rozmlátil Cassidymu bar?}
{365}{}{Neslyšel jste o sluebníkovi jménem Joshua?}
{366}{}{Co tady dìláš?}
{367}{}{Mùete mi øíct, kde je Vault?}
{368}{}{Podaøilo se mi prozkoumat oblast v okolí Gecka.}
{369}{}{Máte pro mì ještì nìjakou práci?}
{370}{}{Podaøilo se mi zmapovat cestu do NCR.}
{371}{}{O tìch nájezdnících...}
{372}{}{Tak nic. Nashle.}
{373}{}{Dobrı den... madam.}
{374}{}{Vault City vdy zvítìzí... madam.}
{375}{}{Kapitáne, mùu vám pomoct... madam?}
{376}{}{Serant Stark... madam. Potøebujete nìco?}
{377}{}{Dìlám VAŠI práci, madam.}
{378}{}{Vedu Nápravné zaøízení. A poslouchám vaše rozkazy, madam.}
{379}{}{Povolení mluvit otevøenì, madam.}
{380}{}{Svoji hodnost si NEZASLOUÍTE. iju ve Vault City celı svùj ivot. MOJI podøízení mi vìøí a respektují mì, vás nikoliv... madam.}
{381}{}{Rozumím, madam.}
{382}{}{Ano, madam. Organizoval jsem povolenou razii v podniku pana Cassidyho.}
{383}{}{Ne, madam. Pan Cassidy nezaplatil licenèní poplatek k prodeji alkoholu za poslední mìsíc a pøitom ho stále prodával. Vıpis jeho plateb je zapsán v poèítaèi.}
{384}{}{Ano... MADAM.}
{385}{}{Hotovo, MADAM.}
{386}{}{Pouil jsi svoji hodnost vùèi Starkovi, abys tak pomohl svému pøíteli Cassidymu.}
{387}{}{Vault je hned za dveømi... madam.}
{388}{}{Podaøilo se ti prozkoumat okolí Gecka pro Vault City.}
{389}{}{Podaøilo se ti zmapovat cestu do NCR pro Vault City.}
{390}{}{Na co... madam?}
