{100}{}{Tu vois un garde.}
{101}{}{Tu vois un garde en SuperArmure.}
{102}{}{Tu vois quelqu'un vêtu d'une SuperArmure quelque peu inhabituelle. Son plastron porte un insigne que tu n'as jamais vu avant.}
{103}{}{Rien à signaler.}
{104}{}{Rien à signaler de mon côté et toi ?}
{105}{}{Tu devrais pas être à ton poste, soldat ? Faut pas traîner par ici !}
{106}{}{Tu n'es pas en uniforme.}
{107}{}{Tu ferais mieux d'aller retrouver le Sergent et de te mettre en tenue.}
{108}{}{Tu prends des gros risques en te promenant sans uniforme. Tu ferais mieux d'aller à la réserve.}
{109}{}{Mais bon sang, qui es-tu ?! -- Alerte ! Des intrus !!!}
{110}{}{La base a été infiltrée ! Alerte !!}
{111}{}{Un groupe d'intrus ! Sonnez l'alarme !!}
{112}{}{Alerte de sécurité !! Condamnez la base !!!}
{113}{}{Fermez toutes les stations !! Nous sommes en état alerte !!}
{114}{}{Alerte intrus !! Activez le code rouge !!!}
{115}{}{On va t'exterminer !!}
{116}{}{L'Enclave régnera sur le monde !}
{117}{}{Ta mort permettra à l'Enclave de survivre !}
{200}{}{...Enfoiré...}
{201}{}{...Ouais, tu ferais MIEUX de foutre le camp...}
{202}{}{... Quel trou du cul...}
{203}{}{...Oui, m'sieur ! Enfoiré de m'sieur... !}
{300}{}{Halte-là. Que fais-tu avec cet hélico ? Il n'y a pas de vols prévus pendant quelques jours.}
{301}{}{Nrg ?}
{302}{}{Je suis au courant.}
{303}{}{Je suis désolé. J'étais juste en train de jeter un oeil. Je m'en vais maintenant.}
{304}{}{Il y a eu un changement de programme. Je dois prendre cet hélico.}
{310}{}{Quoi ? Oh, je vois. Regarde, mais ne touche pas, d'accord ? Remets une seule fois tes mains là-dessus et t'es mort.}
{311}{}{[Tu souris, puis dégaines ton arme]}
{312}{}{[S'en aller]}
{315}{}{Eh merde, voilà qu'on se farcit des intrus maintenant. Code Rouge ! Je répète code Rouge !}
{316}{}{En voilà une idée qu'elle est bonne. Touche à cet hélico encore une fois, et tu te retrouves avec une balle dans le crâne.}
{320}{}{C'est vrai. Et tu es...}
{321}{}{Sur le point de partir. Désolé de t'avoir dérangé.}
{322}{}{Quelqu'un qui doit délivrer au Président des Etats-Unis un message de la plus haute importance.}
{323}{}{Oh, vraiment ? Et que dit ce message ?}
{324}{}{C'est Ultra Top Secret. Je ne peux rien te dire.}
{325}{}{C'est une question de sécurité nationale. Nous avons été informés que l'une des récentes cargaisons d'esclaves avait été infectée par un virus indéterminé. Si je ne remets pas ces informations à la base dans les plus brefs délais, des vies seront perdues.}
{326}{}{Ouais, bien sûr j'te crois. On dirait qu'on s'est coltiné un intrus...}
{327}{}{Nom de... ! Laisse tomber... On me dis jamais rien ici. Bien. Tu peux y aller.}
{328}{}{Ouah, ça a l'air important. Eh bien dans ce cas, tu peux y aller. J'veux pas être tenu pour responsable si quelque chose arrivait.}
{329}{}{[Terminé]}
