{100}{}{Tu vois quelqu'un en SuperArmure. }
{101}{}{Tu vois le Commandant de la base Navarro.}
{102}{}{Tu vois quelqu'un vêtu d'une SuperArmure quelque peu inhabituelle. Son plastron porte un insigne que tu n'as jamais vu avant.}
{103}{}{Qui êtes-vous... ?! Alerte ! Des envahisseurs !}
{104}{}{Je n'ai pas le temps de bavarder avec les bidasses. Rompez !}
{105}{}{Je t'avais prévenu !}
{106}{}{Ok.}
{107}{}{Je t'ai dit que je n'avais pas de temps pour toi. Quitte ce bureau et ne reviens que si je te fais demander. Rompez !}
{108}{}{La désobéissance à un ordre direct d'un officier supérieur est un acte de trahison. Je n'ai pas le temps d'aller en cour martiale alors je vais régler ça moi-même. Gardes ! Tuez ce parasite !}
{109}{}{Ok.}
{110}{}{Va t'faire mettre !}
{111}{}{Le passe électronique est dans le placard là-bas. Demande à l'officier de service de me contacter une fois qu'elle est en lieu sûr. Rompez !}
{112}{}{A vos ordres !}
{113}{}{Grouille-toi soldat, je n'ai pas toute la journée !}
{114}{}{A vos ordres !}
{115}{}{Laisse mon placard tranquille ou j'te fais une tête au carré !}
{116}{}{A vos ordres !}
{117}{}{Cette base est en état d'alerte et je ne te reconnais pas. Montre-moi tes papiers, soldat !}
{118}{}{Quels papiers ?}
{119}{}{Tu rigoles ou quoi ?!}
{120}{}{Apparemment, je ne les ai pas sur moi...}
{121}{}{Des papiers ? Les v'là tes papiers, tiens, regarde !}
{122}{}{Mauvaise réponse, l'asticot. Tu dois toujours avoir tes papiers sur toi. Tu devrais le savoir !}
{123}{}{Va te faire mettre !}
{124}{}{Laisse mon placard tranquille ou j'te fais une tête au carré !}
{125}{}{Je t'avais prévenu !}
