{100}{}{Tu vois la propriétaire du saloon.}
{101}{}{Tu vois Babeth.}
{150}{}{On dirait que c'est la propriétaire.}
{151}{}{C'est Babeth, la propriétaire de cet endroit.}
{152}{}{[Parler]}
{153}{}{Bonjour, étranger, et bienvenue dans mon saloon. Je m'appelle Babeth.}
{154}{}{Bonjour, je suis }
{155}{}{. Y'a des choses à faire par ici ?}
{156}{}{Salut, je suis}
{157}{}{. Je peux poser des questions ?}
{158}{}{M'man ?}
{159}{}{Mag gah.}
{160}{}{Va-t'en. Je n'ai pas besoin de toi ici.}
{161}{}{Mmmm...}
{162}{}{Va t'faire !}
{163}{}{J'y vais.}
{164}{}{Désolé, je ne voulais pas t'offenser. Je peux te demander quelque chose ?}
{165}{}{Un verre de whisky coûte 5 dollars et les tables de jeu sont juste là. Passe une bonne soirée.}
{166}{}{Puis-je te poser une question ?}
{167}{}{Je veux un verre !}
{168}{}{Hmm, ce sont des boissons bon marché. Laisse-moi essayer.}
{169}{}{Merci. Au revoir.}
{170}{}{L'Abri 13 ? Non, jamais entendu parler.}
{171}{}{Hmm, je peux demander autre chose ?}
{172}{}{Mince, je dois le trouver. Salut.}
{173}{}{Que veux-tu savoir ?}
{174}{}{Où est un bon endroit pour manger ?}
{175}{}{Sais-tu où se trouve l'Abri 13 ?}
{176}{}{Pourquoi tes boissons sont si bon marché ?}
{177}{}{Rien. Salut.}
{178}{}{Maman tient un petit restaurant à l'autre bout de la ville.}
{179}{}{Maman ! Maman !}
{180}{}{Une dernière question.}
{181}{}{Merci. Au revoir.}
{182}{}{Casse-toi.}
{183}{}{Gwah.}
{184}{}{Je vais te donner quelque chose à battre.}
{185}{}{Une petite question d'abord ?}
{186}{}{Au revoir.}
{187}{}{Un verre de whisky coûte 5 dollars. Payez d'abord.}
{188}{}{Hein ?}
{189}{}{Voilà l'argent.}
{190}{}{J'ai changé d'avis.}
{191}{}{Je suis un peu à court d'argent. Je peux avoir une note ?}
{192}{}{Puis-je te poser une question ?}
{193}{}{Je dois y aller.}
{194}{}{Voici la boisson. Autre chose ?}
{195}{}{Une question ?}
{196}{}{Yeha, que dirais-tu de toi et moi...}
{197}{}{Non.}
{198}{}{Hé, tu n'as pas assez d'argent pour cette boisson. Tu es plus pauvre que ces soporifiques !}
{199}{}{Pardon.}
{200}{}{Hmm, je reviendrai.}
{201}{}{Hmm. Je vais chercher quelqu'un pour surveiller le bar. Toi et moi, on peut aller dans l'arrière-salle et jouer à un petit jeu que j'appelle "First Strike." Si tu es bon, eh bien, il y a "Ground Zero."}
{202}{}{D'accord !}
{203}{}{Er...uh...je dois y aller.}
{205}{}{Tu étais bien.}
{206}{}{La prochaine fois, jouons à "Into the Glow". Mais pour l'instant...}
{207}{}{Tu peux faire quelque chose pour moi ?}
{208}{}{Je dois partir, mais je reviendrai.}
{209}{}{Que puis-je faire pour toi, ma belle ?}
{210}{}{J'ai besoin d'un peu plus d'amour.}
{211}{}{J'ai quelques questions.}
{212}{}{Comment peux-tu vendre tes boissons si bon marché ?}
{213}{}{Que dirais-tu d'un verre ?}
{214}{}{Je dois y aller. A plus tard.}
{215}{}{Pas maintenant. Peut-être plus tard. Oui, définitivement plus tard.}
{216}{}{Puis-je te poser une question ?}
{217}{}{Au revoir.}
{218}{}{J'ai un alambic au sous-sol. Je l'ai fabriqué moi-même. C'est mieux que de payer le triple à ces gangsters de New Reno.}
{219}{}{Une fille intelligente ! J'aime bien ça !}
{220}{}{Hmm, je dois y aller. Je te verrai plus tard.}
{221}{}{Pourquoi ? Pourquoi as-tu détruit mon alambic ? Espèce de salaud !}
{222}{}{Rien de personnel. J'ai été payé pour le faire.}
{223}{}{Quel dommage.}
{224}{}{Au revoir.}
{225}{}{Je vais en faire un autre, tu sais.}
{226}{}{Je sais.}
{227}{}{C'est une bonne chose.}
{228}{}{Au revoir.}
{232}{}{Pourquoi ? Pourquoi as-tu détruit mon alambic ? Espèce de salope !}
{233}{}{Où es-tu, bébé ?}
{234}{}{Tu viens ?}
{235}{}{J'attends.}
{236}{}{Je suis là, mon amour.}
{237}{}{J'ai un bar à gérer.}
{238}{}{Suis-moi, mon chou.}
{240}{}{Comment as-tu... fait ça... Euhhh...}
{241}{}{C'est bon, la taille n'a pas vraiment d'importance.}
{242}{}{C'était, ummm, sympa -- je suppose.}
{243}{}{Merci, chérie, c'était amusant.}
