{100}{}{Tu vois un homme qui porte une armure métallique.}
{101}{}{Tu vois Kaga.}
{102}{}{Ouais, c'est Kaga le pas si Magnifique que ça. Il porte une armure métallique et veut te tuer.}
{103}{}{Encore toi !}
{104}{}{Il commence à en avoir marre de nos rencontres incessantes.}
{105}{}{Etre Elu, hum...}
{106}{}{Finissons-en !}
{107}{}{Tu regretteras d'avoir entendu un jour le nom de Kaga !}
{108}{}{Ses compétences ont progressé depuis notre dernière rencontre.}
{109}{}{Ca devient une sale manie !}
{110}{}{Kaga a besoin de plus d'entraînement.}
{111}{}{Kaga reviendra !}
