{100}{}{Tu vois un homme qui porte le strict minimum.}
{101}{}{Tu vois Kaga.}
{103}{}{Il porte des pantalons et on dirait qu'il vient d'une tribu.}
{104}{}{Ca aurait dû être moi l'Etre Elu !}
{105}{}{Comment les gens d'Arroyo ont-ils osé chasser Kaga de la tribu ?}
{106}{}{Kaga se vengera !}
{107}{}{Kaga va t'envoyer dans l'au-delà !}
{108}{}{On se reverra !}
{109}{}{Personne n'a encore réussi à battre Kaga !}
{110}{}{Il consacrera sa vie à te détruire !}
