{100}{}{Tu vois un homme qui porte une armure de combat.}
{101}{}{Tu vois Kaga vêtu d'une armure de combat.}
{102}{}{Il porte une armure de combat. On dirait qu'il a de bonnes armes.}
{103}{}{Cette fois, il t'attendait.}
{104}{}{L'Etre Elu ne retournera jamais à Arroyo !}
{105}{}{Kaga te réduira en miettes !}
{106}{}{Kaga n'a peur de personne !}
{107}{}{Ne bouge plus, laisse Kaga viser !}
{108}{}{On se reverra !}
{109}{}{Ce n'est pas la dernière fois que tu verras Kaga !}
{110}{}{Kaga a vraiment besoin d'un entraînement plus poussé.}
