{100}{}{Tu vois un homme qui porte une armure en cuir.}
{101}{}{Tu vois Kaga.}
{102}{}{Il porte une armure en cuir. Il a une sale manie, il parle de lui à la troisième personne.}
{103}{}{Ce sera notre dernière rencontre.}
{104}{}{After Kaga kill yous, he will burn Arroyo to the ground.}
{105}{}{Sens la colère de Kaga !}
{106}{}{Il est le grand Kaga !}
{107}{}{Il sera respecté par tous.}
{108}{}{Kaga fera de ta tête un trophée.}
{109}{}{Rends-toi et ta mort sera rapide.}
{110}{}{Je reviendrai !}
{111}{}{Tu ne peux pas tuer le grand Kaga !}
{112}{}{Tu as de la chance, les affaires appellent Kaga ailleurs.}
{113}{}{On se reverra.}
