{100}{}{Tu vois un homme qui porte une SuperArmure Mk II. Il n'a pas l'air très amical.}
{101}{}{Tu vois Kaga dans sa SuperArmure Mk II.}
{102}{}{Un gros morceau de métal avec des bras et des fusils.}
{103}{}{Il en a marre de cette chasse. Finissons-en.}
{104}{}{C'est la dernière fois que tu rencontres Kaga.}
{105}{}{Tu n'es pas à la hauteur de Kaga.}
{106}{}{Il a hâte de t'envoyer dans ta prochaine vie !}
{107}{}{Tu as été un digne adversaire.}
{108}{}{Cette région du désert n'a pas besoin d'une bonne âme dans ton genre.}
{109}{}{Il va te tuer, et il deviendra la personne la plus respectée de cette région du désert !}
{110}{}{Il a hâte de retourner à Arroyo... pour tout brûler !}
{111}{}{Kaga sera célèbre pour le meurtre de ta petite personne.}
