{100}{}{Tu vois un nomade.}
{101}{}{Chef nomade.}
{102}{}{Ses habits et sa prestance montrent qu'il est certainement une sorte de chef.}
{103}{}{Je te souhaite la bienvenue dans mon humble tente. Viens à l'ombre t'abriter de la chaleur infinie de la terre.}
{104}{}{Merci, j'accepte ta proposition bien volontiers.}
{105}{}{Je dois refuser ta proposition. Je ne fais que passer.}
{106}{}{Ooga.}
{107}{}{Alors ta présence est la bienvenue. Nous n'avons pas fait de troc avec les "civilisés" depuis longtemps. Nous avons besoin de certains produits. Et si nous faisions quelques échanges ?}
{108}{}{Quels produits proposez-vous ?}
{109}{}{Je n'ai rien à échanger, je regrette.}
{110}{}{Peut-être une autre fois, hein ? Que tes voyages se passent sans danger !}
{111}{}{Merci. Au revoir.}
{112}{}{Quel dommage... Alors repose-toi et sois ici chez toi.}
{113}{}{Merci. Au revoir.}
{114}{}{Ma proposition est arrivée trop tard. Le soleil a déjà brûlé les mots dans ton cerveau. Je dois être bon avec les moins bien lotis que moi. Reste aussi longtemps qu'il te plaira dans mon campement, faible d'esprit...}
{115}{}{Au revoir.}
{116}{}{Infidèle !}
{117}{}{Pourquoi nous attaques-tu ?}
{118}{}{Je défendrai la tribu au prix de ma vie !}
{119}{}{Comment oses-tu violer notre hospitalité ?!}
{120}{}{Hors d'ici !}
{121}{}{Laisse-nous !}
{122}{}{Notre tribu est pacifique.}
{200}{}{Ah, un voyageur. Je suis désolé que nous n'ayons pas de tente pour vous protéger de la chaleur incessante de cette terre. Repose-toi un instant, afin que nous puissions discuter.}
{201}{}{Merci, j'accepte volontiers ton offre.}
{202}{}{Quel dommage. Alors repose-toi et sois ici chez toi.}
{203}{}{J'espère que tu as trouvé ce dont tu avais besoin. Autre chose ?}
{204}{}{Pas aujourd'hui. Je dois y aller.}
