{100}{}{Un voyageur.}
{101}{}{Hé ! Camarade voyageur !}
{102}{}{Je cherche mon chemin. Peux-tu m'aider ?}
{103}{}{Où vas-tu ?}
{104}{}{Que fais-tu ?}
{105}{}{Ug.}
{106}{}{Ben, j'sais pas. J'suis pas depuis longtemps dans le coin, je connais seulement les endroits suivants.}
{107}{}{New Reno}
{108}{}{La Cité de l'Abri}
{109}{}{Redding}
{110}{}{La Fosse}
{111}{}{San Francisco}
{112}{}{R.N.C.}
{113}{}{Une mine abandonnée.}
{114}{}{J'y suis déjà allé. Merci quand même.}
{115}{}{New Reno, c'est une super ville. Le paradis du sexe, de la drogue et du jeu. Que demander de plus ? Regarde, je vais t'montrer où c'est...}
{116}{}{Merci.}
{117}{}{La Cité de l'Abri, c'est une ville de cons. Si t'as un orteil en trop, il te traitent comme un monstre. J'y ai jamais mis les pieds, mais j'sais où c'est.}
{118}{}{Merci.}
{119}{}{J'sais pas grand-chose de Redding, sauf que c'est une vieille ville de mineurs. Ca se trouve au Nord, en plein milieu des montagnes les plus minables que je connaisse.}
{120}{}{Merci.}
{121}{}{Je ne m'aventurerais pas près de La Fosse si j'étais toi. Cet endroit attire toutes les raclures de la région. Je vais te montrer où c'est mais j'te conseille pas d'y aller...}
{122}{}{Merci.}
{123}{}{San Francisco, c'est sur la côte. Hum, tout ce que je peux t'dire, c'est que les gens là-bas sont... bizarres.}
{124}{}{Merci.}
{125}{}{La République de Nouvelle Californie... Ca c'est un chouette endroit. J'aimerais bien m'y installer un jour. C'est propre, les gens sont sympa et c'est très bien entretenu. C'est situé ici sur ta carte.}
{126}{}{Merci.}
{127}{}{Il y a quelques temps, j'ai trouvé un camp de mineurs abandonné. Je voulais m'y reposer un jour ou deux mais deux loups ont débarqué et j'ai pensé qu'il valait mieux déguerpir. Dommage. On aurait dit que les mineurs étaient partis précipitamment en laissant beaucoup d'affaires. Je ne compte pas y retourner, alors je suppose que je peux t'indiquer son emplacement.}
{128}{}{Merci.}
{129}{}{Oh... Ca n'a pas vraiment d'importance. Un jour, j'ai décidé de partir en voyage... et me voilà.}
{130}{}{Tu peux peut-être m'aider. Je cherche mon chemin.}
{131}{}{Que fais-tu ?}
{132}{}{Ca m'a fait plaisir de parler avec toi.}
{133}{}{Je fais des petits boulots ça et là pour m'en sortir. Mais la plupart du temps, je voyage.}
{134}{}{Tu peux peut-être m'aider. Je cherche mon chemin.}
{135}{}{Où vas-tu ?}
{136}{}{Ca m'a fait plaisir de parler avec toi.}
{137}{}{Il faut que je parte. Ca m'a fait plaisir de parler avec toi.}
{138}{}{On se reverra peut-être un jour.}
{139}{}{Je veux atteindre la prochaine ville avant la nuit. Il vaudrait mieux que je file.}
{140}{}{I'd be going.}
{141}{}{Embuscade !}
{142}{}{On ne peut plus faire confiance à personne.}
{143}{}{Tu as violé le code du voyageur.}
{144}{}{Faut qu'je file.}
{145}{}{J'ai abusé de ton hospitalité.}
{146}{}{Je dois partir.}
{150}{}{Merci. J'ai besoin de précision sur d'autres endroits.}
