{100}{}{Tu vois un petit Shi rondelet.}
{101}{}{Tu vois le Docteur Wong Yi Tze.}
{102}{}{Tu vois un petit Shi rondelet.}
{103}{}{Puis-je t'aider ?}
{104}{}{Daghi hein ?}
{105}{}{Toi qui ?}
{106}{}{J'ai entendu dire que tu avais la rate de quelqu'un d'autre.}
{107}{}{Qui es-tu ?}
{108}{}{Qu'est-ce tu fais ici ?}
{109}{}{Non, merci. C'est tout.}
{110}{}{Je dois avouer que je ne comprends pas ta langue. Tu devrais peut-être t'adresser à Ken Lee, il parle plusieurs langues.}
{111}{}{Aagh !}
{112}{}{Je suis le Docteur Wong. Je suis le chef des scientifiques de cette installation.}
{113}{}{D'autres questions, s'il te plaît.}
{114}{}{Merci. Au revoir.}
{115}{}{Je supervise les expériences scientifiques que nous menons ici. Je suis également responsable du réseau informatique.}
{116}{}{Qu'envisages-tu ?}
{117}{}{Comment peut-on accéder au réseau informatique ?}
{118}{}{J'ai d'autres questions.}
{119}{}{Je vois. Au revoir.}
{120}{}{Ah, mais si je te révèle nos plans, tout le monde sera au courant. Je regrette mais ces plans sont secrets pour le moment.}
{121}{}{Très bien. J'ai d'autres questions.}
{122}{}{Merci. Au revoir.}
{123}{}{Et si je te mets un revolver sous le nez et que je te force à me les révéler ?}
{124}{}{Pour ça, apprends à pirater ou fais ami-ami avec un des mes subalternes. Je plaisante, bien sûr, quand je parle de piratage... à la moindre tentative, j'enverrai quelqu'un te tuer. [Il sourit pour indiquer qu'il ne voulait pas t'offenser.]}
{125}{}{Tu me tuerais vraiment ?}
{126}{}{Alors tu ne verrais pas d'objections à ce que j'accède à l'ordinateur ?}
{127}{}{J'ai d'autres questions à te poser.}
{128}{}{Certainement. Au revoir.}
{129}{}{Je considérerais cela comme une menace et je dois t'avertir qu'une telle action serait nuisible à ta santé.}
{130}{}{On peut toujours essayer.}
{131}{}{Je plaisantais. J'ai d'autres questions.}
{132}{}{[Il sourit.] Nous devons protéger notre honneur.}
{133}{}{Heu, très bien. Aurais-tu alors de réelles objections à ce que j'accède à l'ordinateur ?}
{134}{}{Trèèès bien. J'ai d'autres questions.}
{135}{}{J'parie que oui. Au revoir.}
{136}{}{Si tu réussis à convaincre mes subalternes de le faire. Mais moi, je ne le ferai pas.}
{137}{}{Et si je te pointe un revolver sous le nez ?}
{138}{}{Parfait. Bon, dis-moi.}
{139}{}{Hum. Je vois. Eh bien, au revoir.}
{140}{}{Ahh, oui ! En fait, je vais la préparer avec des fèves et l'accompagner d'un bon chianti.}
{141}{}{Tu l'as toujours ? Formidable. Chip en a besoin.}
{142}{}{C'est une rate humaine, espèce de malade dégénéré !}
{143}{}{Tu devrais savoir que ce vin accompagne bien le foie et non la rate, pas vrai ?}
{144}{}{C'est une rate humaine, tu sais.}
{145}{}{Qui c'est ce Chip ? C'est ma rate maintenant, et je vais la manger au dîner.}
{146}{}{A l'origine, cette rate appartenait à Chip. Il était saoul et il l'a vendue à Lao Chou.}
{147}{}{Il en a besoin pour survivre, tu sais. Elle vient de son corps.}
{148}{}{Eh bien, je devrais peut-être te tuer pour ça.}
{149}{}{Un marché est un marché. Elle ne lui appartient plus. Je regrette mais nous avons conclu un marché et ce n'est pas parce que Chip regrette qu'il peut revenir sur sa décision.}
{150}{}{[Suite]}
{151}{}{C'est une rate humaine ? Lao Chou ne me l'a pas dit !}
{152}{}{Pourtant, à cause de la grossièreté du messager, je ne vais pas revenir sur notre marché. Je vais plutôt utiliser cette rate pour des expériences.}
{153}{}{Dis à ton ami de venir la chercher demain, je la lui rendrai avec plaisir. J'espère simplement que tu trouveras un moyen de la lui réimplanter rapidement.}
{154}{}{Très bien.}
{155}{}{Ha ha ! Oui, j'ai aussi vu ce vieux film. Attends... De quoi parles-tu ? Es-tu en train de dire que... ?}
{156}{}{Oui, c'est une rate humaine.}
{157}{}{En fait, je ne suis pas d'accord. Tu n'as pas été très aimable. D'ailleurs, je ne sais même pas pourquoi je t'adresse la parole. Au revoir.}
{158}{}{[Terminé]}
{159}{}{Ohé ! Gardes ! L'intrus est ici !}
{160}{}{Tu dois sûrement avoir des schémas à me donner ?}
{161}{}{Ken Lee m'a demandé de te les donner.}
{162}{}{Oui. Et qu'est-ce que j'y gagne ?}
{163}{}{Non, pas encore.}
{164}{}{Va voir Ken Lee et il te parlera de ton avenir. Merci. Avec ceci, nous devrions pouvoir vérifier certains résultats expérimentaux. Au revoir.}
{165}{}{En fait, j'avais d'autres questions.}
{166}{}{Au revoir.}
