{100}{}{Tu vois quelqu'un portant une casquette de capitaine.}
{101}{}{Tu vois le Capitaine A. Ron Meyers}
{102}{}{Tu vois une crapule portant des vêtements en lambeaux et une casquette de capitaine.}
{103}{}{Qu'est-ce tu veux ? Je n'adresse la parole qu'à mes amis et aux gens bien. Commence par faire quelque chose pour un des mes potes si tu veux me parler.}
{104}{}{[Terminé]}
{105}{}{J'ai entendu parler de ce que tu as fait pour mes hommes. Merci. Que puis-je faire pour toi ?}
{106}{}{Toi qui ?}
{107}{}{J'ai entendu dire que tu en savais beaucoup sur ce navire.}
{108}{}{Pourquoi t'appellent-ils Capitaine ?}
{109}{}{Comment fais-tu marcher ce truc ?}
{110}{}{Rien.}
{111}{}{Je suis le Capitaine. Je commande ce navire. Si tu as d'autres questions, adresse-toi à un des Shi, à Badger, ou à quelqu'un d'autre. Je n'ai pas de temps à t'accorder.}
{112}{}{[Terminé]}
{113}{}{This ship's a Poseidon tanker. It's equipped with tech that lasted through the war. It's got a FOB that allows access to the navigation computer room, and it's got an IFF transponder that protects it from Poseidon guns.}
{114}{}{Comment sais-tu tout ça ?}
{115}{}{C'est quoi un transpondeur IFF ?}
{116}{}{Comment ça marche ?}
{117}{}{Merci. Au revoir.}
{118}{}{J'ai travaillé pour l'Enclave. Et puis, je me suis rendu compte que je ne me battais pas pour les Etats-Unis, mais pour les vieux salauds fortunés qui ne voulaient rien céder de leur pouvoir. J'ai déserté et maintenant, je vis ici avec des gens plus honnêtes.}
{119}{}{Des gens plus honnêtes ? Ces types ?}
{120}{}{C'est quoi au juste l'Enclave ?}
{121}{}{Comment fais-tu marcher ce truc ?}
{122}{}{Salut.}
{123}{}{How do you pilot this rig? Fill 'er up with some gas - try the Hubologists or the Shi after you've taken care of everything else - and press the button. The computer will take care of the rest, if it's still working. It'll sail right out to the oil rig, and they won't fire at you because you've got the IFF transponder. Just make sure you've got what you need to access everything: FOB, working computer, and fuel. Easy enough, huh?}
{124}{}{Certainement. Comment sais-tu tout ça ?}
{125}{}{C'est quoi au juste ce transpondeur IFF et ce fameux passe ?}
{126}{}{Quelle plate-forme pétrolière ?}
{127}{}{Oui. Au revoir.}
{128}{}{La technologie IFF signifie que le navire est identifié comme un navire ami et que les autres installations Poséidon, comme disons, une plate-forme pétrolière, ne te tireront pas dessus lorsque tu t'en approcheras. Oh, et le passe électronique c'est un passe issu d'une technologie de l'Enclave te permettant de franchir électroniquement une porte. Tu devrais en trouver un dans une de leurs bases ou un endroit de ce genre.}
{129}{}{Comment sais-tu tout ça ?}
{130}{}{Quelle plate-forme pétrolière ?}
{131}{}{Merci. Au revoir.}
{132}{}{Oui. Avec ces gens-là, on sait vraiment à quoi s'en tenir. Ils ne plaisantent pas. L'Enclave était comme une meute de hyènes, elle pouvait te tomber dessus en une seconde.}
{133}{}{C'est quoi au juste l'Enclave ?}
{134}{}{Comment as-tu fait pour t'en débarrasser ?}
{135}{}{L'Enclave c'est le vestige d'une époque révolue. En pilotant cet engin jusqu'à la plate-forme, tu t'en rendras compte par toi-même.}
{136}{}{Comment fait-on pour piloter ça ?}
{137}{}{Quelle plate-forme ?}
{138}{}{C'était assez facile. Un jour, j'ai simplement quitté la base de Navarro et je suis arrivé ici. J'ai pensé que ce serait le dernier endroit où on viendrait me chercher. Et puis, je ne suis pas assez important pour que l'Enclave me cherche.}
{139}{}{C'est quoi au juste l'Enclave ?}
{140}{}{Merci. Au revoir.}
{141}{}{Il y a une grande plate-forme Poséidon sur l'eau. C'est la dernière base de l'Enclave.}
{142}{}{Comment sais-tu tout ça ?}
{143}{}{Que se passe-t-il d'autre sur la plate-forme ?}
{144}{}{Merci. Au revoir.}
{145}{}{Des rumeurs se propagent.}
{146}{}{Je vois. Que se passe-t-il d'autre sur la plate-forme ?}
{147}{}{Je vois. Au revoir.}
{148}{}{J'en ai aucune idée. J'étais technicien à Navarro, pas opérateur de plate-forme. On leur a juste parlé via les lignes de communication et c'est à peu près tout.}
{149}{}{Je vois. Comment on pilote ça déjà ?}
{150}{}{Merci. Au revoir.}
{151}{}{Tu as commis une grave erreur en venant te frotter au Capitaine et à ses amis...}
{152}{}{How do you pilot this rig? Well, I see you already gassed her up. When you've taken care of everything else, just press the button. The computer will take care of the rest, if it's still working. It'll sail right out to the oil rig, and they won't fire at you because you've got the IFF transponder. Just make sure you've got what you need to access everything: FOB, working computer, and fuel. Easy enough, huh?}
{153}{}{Oh ouais. Tu dois également faire marcher l'ordinateur de navigation.}
{154}{}{Je suis content de te revoir ! De quoi t'as besoin ?}
{155}{}{, et sauf si je me trompe, c'est la que sont tes amis aussi.}
{156}{}{.}
