{100}{}{Tu vois un terminal d'ordinateur.}
{101}{}{Tu vois le terminal de l'Ordinateur Empereur.}
{102}{}{Tu vois un ordinateur doté d'une interface à écran tactile. Sur le côté, tu peux lire "Terminal d'ordinateur de l'Empereur v8.8".}
{103}{}{Bienvenue. Veuillez entrer votre mot de passe pour confirmer votre identité.}
{104}{}{[Tu baves abondamment]}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{[Pirater l'ordinateur]}
{109}{}{Déconnexion.}
{110}{}{Identité confirmée.}
{111}{}{A quelle fonction voulez-vous accéder ?}
{112}{}{Diagnostic.}
{113}{}{Base de données.}
{114}{}{Prévisions.}
{115}{}{Aucune.}
{116}{}{Veuillez vous adresser à l'administrateur système. Au revoir.}
{117}{}{[Pirater l'ordinateur]}
{118}{}{[Quitter]}
{119}{}{Alarme intrusion activée. Arrêt en cours. Bonne journée.}
{120}{}{[Terminé]}
{121}{}{Fonctions de diagnostic ?}
{122}{}{Analyse réseau.}
{123}{}{Formatage du lecteur.}
{124}{}{Vérification de l'intégrité du disque dur.}
{125}{}{[Retour]}
{126}{}{Quelle base de données voulez-vous consulter ?}
{127}{}{Biologie.}
{128}{}{Chimie.}
{129}{}{Physique.}
{130}{}{Histoire.}
{131}{}{[Retour]}
{132}{}{Les enfants de Shitown sont en danger. Ils ont 50% de risque de mourir.}
{133}{}{Le mal est arrivé à Shitown. Le danger guette ses résidents avec une probabilité de 75%.}
{134}{}{Le lancement spatial des Hubologistes est à 95% voué à l'échec. Facteurs : pas de carburant, mauvaise étanchéité, mauvais commandement, manque d'initiative.}
{135}{}{Les chances de réussite de *l'Etre Elu* désigné sont de 15%.}
{136}{}{Les données indiquent que *l'Enclave* est plus puissante qu'on ne le pensait et qu'il ne faut pas s'en approcher.}
{137}{}{Chances of submarine reappearing in this game: 0%}
{138}{}{Les vagabonds du pétrolier ont 0% de chance de se débarrasser de l'invasion de monstres sans aide extérieure. Traitement de la proposition d'aide en cours.}
{139}{}{Données : pétrolier Poséidon incapable de prendre le large. Plus de données nécessaires.}
{140}{}{Pas de traitement. Entrée requise.}
{141}{}{[Suite]}
{142}{}{[Retour]}
{143}{}{Station de biologie : activée}
{144}{}{Station de biologie : désactivée}
{145}{}{Station de chimie : activée}
{146}{}{Station de chimie : désactivée}
{147}{}{Station de physique : activée}
{148}{}{Station de physique : désactivée}
{149}{}{Désactiver Station de biologie.}
{150}{}{Désactiver Station de chimie.}
{151}{}{Désactiver Station de physique.}
{152}{}{Accéder à la Station de biologie.}
{153}{}{Accéder à la Station de chimie.}
{154}{}{Accéder à la Station de Physique.}
{155}{}{Activer Station de biologie.}
{156}{}{Activer Station de chimie.}
{157}{}{Activer Station de physique.}
{158}{}{[Retour]}
{159}{}{Formatage de disque : toutes les données seront perdues. êtes-vous sûr de vouloir formater ?}
{160}{}{Oui.}
{161}{}{Non.}
{162}{}{L'intégrité de fonctionnement de ce système est de 92%. L'efficacité du noyau blindé de l'Ordinateur Empereur est de 100%. L'intégrité des données est de 100%. Le noyau de prévisions comporte des retards d'alimentation électrique mineurs, délai de réparation prévu : 6 jours. Prévisions à 15% opérationnelles.}
{163}{}{[Retour]}
{164}{}{Voulez-vous vraiment formater cette unité ? Ce processus est irréversible.}
{165}{}{Oui.}
{166}{}{Non.}
{167}{}{Formatage en cours... Formatage en cours... Formatage terminé. Réinitialisation nécessaire pour valider l'installation. Fermeture en cours. Fermeture en cours... Terminée...}
{168}{}{[Terminé]}
{169}{}{Données à rechercher : - Programme botanique - Programme génétique - Programme Xeno.}
{170}{}{Programme botanique.}
{171}{}{Programme génétique.}
{172}{}{Programme Xeno.}
{173}{}{[Retour]}
{174}{}{[Après une vingtaine de minutes, tu découvres que les premiers résultats de dissipation botanique de la radioactivité se révèlent peu prometteurs. Le Docteur Sheng met au point une flore capable de résister aux radiations, se soldant par l'apparition d'effets secondaires déplaisants. La plante qui en résulte est jugée trop dangereuse. Sheng insiste pour poursuivre ses recherches en les associant à un programme génétique.]}
{175}{}{Programme génétique.}
{176}{}{Programme Xeno.}
{177}{}{[Retour]}
{178}{}{[Après une vingtaine de minutes, tu réunis les informations suivantes : grâce aux éléments de base du virus FEV, le Docteur Long Wang est persuadé de pouvoir créer des soldats mutants. Il met au point un sérum offrant des résultats intéressants suite à des expériences menées sur des rongeurs. Il se l'est injecté et s'est transformé en substance collante. Le Docteur Sheng arrête les recherches. Le Docteur Sheng a pris la suite du défunt docteur Long Wang. Sheng souhaite qu'on l'on étudie en profondeur la flore qui se nourrit de radiations.]}
{179}{}{Programme botanique.}
{180}{}{Programme Xeno.}
{181}{}{[Retour]}
{182}{}{"Le sujet sur lequel nous avions espéré établir une série d'expériences significatives a disparu, vraisemblablement détruit ou volé par les Hubologistes. Les recherches qui ont suivi se sont révélées infructueuses. Jusqu'à l'obtention de nouveaux spécimens, cette base de données restera inopérationnelle" - Docteur Sheng.}
{183}{}{Programme botanique.}
{184}{}{Programme génétique.}
{185}{}{[Retour]}
{186}{}{Base de données Chimie : Carburant et dérivés - Polymères}
{187}{}{Carburant et dérivés.}
{188}{}{Polymères.}
{189}{}{[Retour]}
{190}{}{[Après avoir passé au crible la formule chimique complexe et les notes du laboratoire, tu en conclus que les Shis ont créé une sorte de carburant à partir d'extraits de plantes et de composants marins. Apparemment, ils ont utilisé les anciens pipelines pour transporter le carburant vers des destinations nombreuses et variées.]}
{191}{}{[Tu découvres de nombreuses formules chimiques et des notes de laboratoire. Tu ne sais pas vraiment ce que tout cela signifie.]}
{192}{}{Transférer carburant vers pétrolier Poséidon.}
{193}{}{Transférer carburant vers Hubologistes.}
{194}{}{[Retour]}
{195}{}{[Après avoir réussi à te familiariser avec la symbologie et la terminologie technique, tu découvres que les Shis travaillent sur un nouveau type d'armure de combat polymérique capable de résister aux flammes et aux projectiles. Il va encore falloir des années pour finaliser ce projet. Tu vois également des allusions à de nouvelles armes et techniques de construction. Apparemment les Shis ont des projets pour l'avenir.]}
{196}{}{[Retour]}
{197}{}{Carburant correctement transféré. Réservoirs de stockage = vides. Fermeture du programme en cours.}
{198}{}{[Terminé]}
{199}{}{Carburant correctement transféré. Réservoirs de stockage = vides. Fermeture du programme en cours.}
{200}{}{[Terminé]}
{201}{}{Base de données de Physique : Exploration - Théorie}
{202}{}{Exploration.}
{203}{}{Théorie.}
{204}{}{[Retour]}
{205}{}{"Grâce à la récente acquisition des plans des hélicos, le projet de création d'une machine volante a fait un immense pas en avant. Nous espérons mettre au point un prototype en état de marche d'ici la fin de l'année et entamer la production en masse de ces véhicules d'ici deux ans " - Docteur Wong}
{206}{}{[Copier les plans et revenir en arrière]}
{207}{}{[Retour]}
{208}{}{"Nous travaillons toujours à la mise au point d'un véhicule aérien. Aucun des modèles que nous avons créés ne s'est révélé sûr ou aérodynamique. Peut-être que si nous avions accès aux plans des anciens..." - Docteur Wong}
{209}{}{[Retour]}
{210}{}{[Après une lecture pénible de la présentation et des mathématiques, tu découvres que les Shis essaient de redévelopper l'énergie nucléaire, en utilisant les théories de voyages spatiaux des anciens et, ce faisant, ils imitent les Hubologistes et ont recours à l'énergie du soleil, du vent et de la mer. Du moins, c'est ce qui est écrit dans les notes.]}
{211}{}{[Retour]}
{212}{}{Station activée.}
{213}{}{[Retour]}
{214}{}{Le terminal d'ordinateur ne semble disposer d'aucune interface pour cela.}
{215}{}{Le terminal d'ordinateur ne semble pas fonctionner.}
{216}{}{La sécurité du système est mise en péril. Les ordres sont d'attaquer !}
{217}{}{Attaquez l'intrus !}
{218}{}{Il est temps que tu paies pour tes agissements, gaijin !}
{219}{}{Il y a un traître parmi nous !}
{220}{}{Géo-repérage.}
{221}{}{Que voulez-vous repérer ?}
{222}{}{Les villageois de chez moi.}
{223}{}{97% de chances cumulées, villageois situés aux coordonnées actuelles de l'enceinte de l'Enclave.}
