{100}{}{Tu vois une Goule plus grande que la moyenne.}
{101}{}{Tu vois Zomak, que certains surnomment « Le Destructeur ».}
{102}{}{Tu vois une grande goule costaude dont le visage, sous un front fortement incliné, reflète de vastes réserves de supériorité simple d'esprit.}
{110}{}{Renouveau camarade ! Je suis Zomak. Certains m'appellent Zomak le Destructeur. Que fais-tu ici ?}
{111}{}{Renouveau, Camarade ! Que fais-tu ici ? Décris ton problème à « Zomak le Destructeur ».}
{112}{}{Reunouvoo !}
{113}{}{Okéé ?}
{114}{}{Je fais juste un tour.}
{115}{}{Je voudrais expérimenter le renouveau.}
{116}{}{J'ai pas pris le bon chemin.}
{120}{}{T'as intérêt à regarder ailleurs ou Zomak va te faire voir trente-six chandelles.}
{130}{}{Alors, tu dois le voir lui.}
{131}{}{Lui ? Où est lui, je veux dire, où est-il ?}
{132}{}{Je ne suis pas digne de le voir. Au revoir.}
{140}{}{Il est celui qui donne l'éclairement. C'est lui qui promet le Renouveau à tous ceux qui le suivent.}
{141}{}{Je suis sur le point de renouveler mon contrat. Où est-il ?}
{142}{}{Il me semble qu'il s'agit d'un autre cinglé. Je m'en vais.}
{150}{}{Eh bien, il revient tout de suite... Hé, qui es-tu au juste ?}
{151}{}{Je ne suis qu'un vagabond.}
{152}{}{Je suis l'être Elu.}
{153}{}{Je suis ici pour mon renouveau annuel.}
{154}{}{Tout ira bien. Je dois juste lui poser quelques questions.}
{160}{}{Alors, sors d'ici.}
{161}{}{Euh, d'accord. Au revoir.}
{170}{}{Dans ce cas. Entre. Il est dans la pièce voisine. Ne le fais pas attendre.}
{171}{}{Pas moi. J'y vais. Au revoir.}
{172}{}{Je reviendrai peut-être plus tard. Au revoir.}
{180}{}{Tu devrais partir. Sors d'ici.}
{181}{}{Ok.}
{200}{}{Oui, vous pouvez tous vous réinsérer à l'intérieur.}
{201}{}{Ok.}
{210}{}{Ok ? Que veux-tu dire ? T'es bête ou quoi ?}
{211}{}{Gloup ?}
{220}{}{Dégage d'ici. Cortex n'a pas de temps à perdre avec des gens comme toi.}
{221}{}{Ok. Je vais partir.}
{230}{}{Il n'y a rien d'autre ici que le repaire de Cortex. Tiens, t'es vraiment con.}
{231}{}{Cortex ?}
{232}{}{Je voulais juste te faire passer un test. Tu as réussi. Maintenant, laisse-moi entrer.}
{233}{}{Je crois que je m'embrouille. Ca doit venir de toutes ces radiations. Au revoir.}
{240}{}{Oh... Euh, il n'y a rien ici. Rien du tout. Va-t'en maintenant.}
{241}{}{Il n'y a rien, c'est sûr ?}
{242}{}{Ok. Au revoir.}
{250}{}{Ouais. C'est sûr. Maintenant, pars.}
{251}{}{Si tu le dis. Au revoir.}
{260}{}{Oh, heh, heh, Ouais. Je le savais. Umm, eh bien, euh, j'ai réussi ? }
{261}{}{Bien sûr. Maintenant, laisse-moi entrer.}
{262}{}{Non. Tu as échoué, et maintenant je dois signaler ta présence.}
{270}{}{D'accord, alors. Tu peux entrer directement.}
{271}{}{Ok. Au revoir.}
{280}{}{Tu as le signe. Entre.}
{281}{}{Entrrrrrer.}
{282}{}{Le signe ?}
{283}{}{Crains le signe. Au revoir.}
{290}{}{Oui, le talisman sacré du renouveau. Renouveau Camarade ! Renouvelle-toi !}
{291}{}{Oui, Reno à vous aussi. Au revoir.}
{300}{}{Renouveau, mon frère. Tu peux passer.}
{301}{}{Renouveau, ma soeur. Tu peux passer.}
