{100}{}{Tu vois un homme maigre à l'air aimable.}
{101}{}{Tu vois Chad, le caravanier.}
{102}{}{Tu vois un homme maigre avec un grand sourire. Il porte des vêtements quelconques, et donne l'impression de savoir ce qu'il fait.}
{120}{}{Salut ! Que puis-je faire pour toi ?}
{121}{}{D'autres questions ? Je vais voir ce que je peux faire pour te répondre.}
{122}{}{Deerk deugleu !}
{123}{}{Toi qui ?}
{124}{}{Marcus se pose quelques questions à ton sujet.}
{125}{}{There's enough evidence that you've been stealing money that's supposed to go to Broken Hills
 that you can be arrested. You're going down.}
{126}{}{There's enough evidence that you've been stealing money that's supposed to go to Broken Hills
 that you can be arrested. Cut me in for $1000 and I'll make sure you can flee town.}
{127}{}{Qui es-tu ?}
{128}{}{Parle-moi de cet endroit.}
{129}{}{Rien. Salut.}
{130}{}{Regarde ce que le désert t'as fait ! Je regrette, camarade, je peux pas t'aider.}
{131}{}{Heu r'voir !}
{132}{}{Je m'appelle Chad.}
{133}{}{Ecoute, je suis très occupé. Va embêter quelqu'un d'autre.}
{134}{}{I'm the caravan master for the city. I take care of the business on the other end of the trade
 routes. These days I'm focusing primarily on Gecko. }
{135}{}{D'OOkK !}
{136}{}{Je voudrais travailler pour toi.}
{137}{}{Ca a l'air excitant.}
{138}{}{Ca a l'air chiant.}
{139}{}{J'ai d'autres questions.}
{140}{}{Merci. Au revoir.}
{141}{}{Te parler des Collines Brisées ? Bien... Je suis arrivé il y a quelques années. J'ai commencé à travailler pour Bill, l'armateur, et j'ai gravi les échelons. Je suis sous les ordres de Marcus et de Bill, mais je suis responsable du gagne-pain de la ville.}
{142}{}{J'ai d'autres questions.}
{143}{}{Salut.}
{144}{}{Comme quoi ?}
{145}{}{He suspects, that you are skimming the money that's supposed to go Broken Hills.}
{146}{}{Apparemment rien, salut.}
{147}{}{Ecoute, je n'aime pas que les gens m'accusent de quelque chose dont je ne sais rien. Je te suggère de partir.}
{150}{}{I'm going to find the truth. Bye.}
{156}{}{Vois avec Bill. Il te donnera un coup de main.}
{157}{}{J'ai d'autres questions.}
{158}{}{Merci. Au revoir.}
{159}{}{Ouais, c'est vrai. On y pense pas, mais je voyage, je vois le monde... et j'ai le sentiment d'apporter quelque chose à la ville. C'est une vie cool.}
{160}{}{Ca a l'air génial. Je voudrais bien avoir un travail comme ça.}
{161}{}{A vrai dire, ça a l'air plutôt ennuyeux.}
{162}{}{J'ai d'autres questions.}
{163}{}{Salut.}
{164}{}{Sûrement beaucoup plus excitant que ce que tu fais de ta vie, minable.}
{165}{}{Ouais, comme tu le sens. J'ai d'autres questions.}
{166}{}{Ha ha ha ha ! Ok. A plus, minable.}
{167}{}{Tu me l'paieras !!}
{168}{}{Barre-toi, saloperie !}
{169}{}{T'as vraiment pas assuré pour cette caravane... Tu peux te gratter pour ton fric.}
{170}{}{Tu l'as vraiment salopé cette caravane... Bon courage si tu veux en avoir une autre un jour.}
{171}{}{T'as fait du bon travail sur cette caravane. Tiens, voilà tes $200.}
{172}{}{Tire-toi. On a plus besoin de ton aide.}
{173}{}{Ouvre l'oeil.}
{174}{}{Je te surveillerai.}
{175}{}{Ne laisse pas ces connards t'emmerder.}
