{100}{}{Tu vois une personne portant une armure de cuir qui a l'air de s'ennuyer.}
{101}{}{Tu vois Max, le garde de caravane.}
{102}{}{Tu vois une personne sale portant une armure de cuir noir. Elle a l'air de s'ennuyer. L'odeur fétide de Brahmine et sa démarche assurée indiquent qu'il doit s'agir d'un garde de caravane.}
{103}{}{Puis-je t'aider ?}
{104}{}{Hein ?}
{105}{}{Cravail ici !}
{106}{}{Qui es-tu ?}
{107}{}{Que peux-tu me dire sur Chad ?}
{108}{}{J'ai aucune patience avec les idiots. Je regrette, camarade, mais tu devras trouver quelqu'un d'autre pour jouer.}
{109}{}{[Sniff]}
{110}{}{Je m'appelle Max. Je travaille comme garde de caravane.}
{111}{}{Que peux-tu me dire sur Chad ?}
{112}{}{Merci. Au revoir.}
{113}{}{Je ne l'aime pas beaucoup. On dirait qu'il a toujours de l'argent en plus grâce à son travail avec les caravanes. C'est vraiment injuste.}
{114}{}{Marcus le soupçonne de détourner une partie de l'argent qui est censé aller à Broken Hills.}
{115}{}{Merci. Au revoir.}
{116}{}{Thanks. I'm sure glad that this is over. You better watch your back thought.}
{117}{}{Salut.}
{118}{}{L'ennemi est là ! Crève !}
{119}{}{Oh là là !}
{120}{}{(Parle doucement et regarde autour de lui) Ça doit être ça. J'ai vu une fois qu'il prenait une "part" de l'argent qu'il a obtenu de la cargaison d'uranium de Gecko.}
{121}{}{Really? Then why you haven't tell about it to Marcus then?}
{122}{}{Tu es sourd ? Si je vais le raconter, beaucoup de gens dans cette ville ne me regarderont même plus. En plus, je pourrais subir une sorte de vengeance.}
{123}{}{Hmm, I could tell it about to Marcus, cause I don't plan to stay here too long anyway.}
{124}{}{Ok. Do what you want, but don't tell anything about me. And we never had this conversation, ok?}
{125}{}{Pas question. Je ne veux pas créer d'ennuis, salut.}
