{100}{}{Tu vois une personne portant une armure de cuir qui a l'air de s'ennuyer.}
{101}{}{Tu vois Max, le garde de caravane.}
{102}{}{Tu vois une personne sale portant une armure de cuir noir. Elle a l'air de s'ennuyer. L'odeur fétide de Brahmine et sa démarche assurée indiquent qu'il doit s'agir d'un garde de caravane.}
{103}{}{Puis-je t'aider ?}
{104}{}{Hein ?}
{105}{}{Cravail ici !}
{106}{}{Qui es-tu ?}
{107}{}{Que peux-tu me dire sur Chad ?}
{108}{}{J'ai aucune patience avec les idiots. Je regrette, camarade, mais tu devras trouver quelqu'un d'autre pour jouer.}
{109}{}{[Sniff]}
{110}{}{Je m'appelle Max. Je travaille comme garde de caravane.}
{111}{}{Que peux-tu me dire sur Chad ?}
{112}{}{Merci. Au revoir.}
{113}{}{I don't like him much. He seems to get always some extra money from his caravan jobs. It's really unfair.}
{114}{}{Well, Marcus suspects that he is skimming some of the money that supposed to go Broken Hills.}
{115}{}{Merci. Au revoir.}
{116}{}{Thanks. I'm sure glad that this is over. You better watch your back thought.}
{117}{}{Salut.}
{118}{}{L'ennemi est là ! Crève !}
{119}{}{Oh là là !}
{120}{}{(Lowers his voice and looks around) That's gotta be it. I once saw myself that he was taking some "slice" of that money he got from uranium shipment from Gecko.}
{121}{}{Really? Then why you haven't tell about it to Marcus then?}
{122}{}{Are you duff? If I go to tell it, a lot of people in this town won't even look at me. Besides I might get some kind of revenge.}
{123}{}{Hmm, I could tell it about to Marcus, cause I don't plan to stay here too long anyway.}
{124}{}{Ok. Do what you want, but don't tell anything about me. And we never had this conversation, ok?}
{125}{}{Don't worry, I don't want to get you in any trouble, bye.}
