{100}{}{Tu vois quelqu'un avec une arme puissante.}
{101}{}{Tu vois quelqu'un de l'équipe de commerce et protection des Collines Brisées.}
{102}{}{Tu vois quelqu'un avec une arme puissante et couvert de poussière.}
{103}{}{J'te dis, encore un autre groupe de bandits, et j'apporterai de la dynamite pendant le prochain voyage !}
{104}{}{J'aurais bien besoin d'aide pour les caravanes.}
{105}{}{Le travail des Patrouilles de l'Unité se fait très, très vieux.}
{106}{}{Donc, après j'ai vu venir c'te tribal et... peu importe.}
{107}{}{Encore un coup des *Arc-en-Ciel* et je tue quelqu'un !}
{108}{}{Si la situation avec les bandits empire, nous serons tous morts l'année prochaine !}
{109}{}{De quel village paumé viens-tu ?}
{110}{}{Tu paies ta tournée à un mec qui bosse ?}
{111}{}{Je suis trop naze pour parler.}
{112}{}{Si t'as besoin d'un truc, va parler à Bill, l'armateur.}
{113}{}{Tu devrais penser qu'après tant de temps passé à essayer de civiliser ce trou on est censé se rapprocher de notre but.}
{114}{}{J'en ai marre de ces chamailleries entre humains et mutants. Ne devrions nous pas montrer l'exemple ?}
{115}{}{Qu'est-ce tu veux ? Tu vois pas que j'me repose ?!}
{116}{}{Quand part la prochaine caravane ?}
{117}{}{Patrouiller, patrouiller, patrouiller, c'est tout ce que je fais ici...}
{118}{}{J'ai besoin d'une sieste.}
{119}{}{Je mérite une augmentation. C'est un travail dangereux.}
