{100}{}{You see a card dealer.}
{101}{}{Tu vois Monte Trois-Cartes.}
{150}{}{Tu vois un vieil homme au visage décoloré par le soleil. Il est si mince qu'on dirait une brindille.}
{151}{}{You see Three-Card Monte. He scopes out the street, spots you, and nods.}
{152}{}{You see Three-Card Monte. He scopes out the street, spots you, and nods.}
{200}{}{Je ne vois pas comment j'ai pu perdre...}
{201}{}{Just keep walking... Monte's not in business today.}
{202}{}{Did I palm the wrong card?}
{203}{}{How did that stupid tribal keep picking the right card?}
{205}{}{Héé ! Le Héros ! T'es trop fort, vraiment trop fort.}
{206}{}{::Lève le pouce et te fait signe::}
{207}{}{::Smiles, nods::}
{208}{}{You done good, hero. You done good.}
{215}{}{Où sont passées mes putains de cartes ? Je les avais JUSTE LA.}
{216}{}{Goddamn car key gnomes, now they're going after my playing cards.}
{220}{}{Salut mon pote, te prends pas la tête avec les casinos. Viens jouer avec Monte.}
{221}{}{Looking to take a chance, pal? Best odds in New Reno! C'mon...}
{222}{}{You, pal. You look like a lucky guy, c'mon over.}
{223}{}{Anybody looking to play? Free mon-ay, free mon-ay.}
{224}{}{C'mon over and play. Just the other day, I guy won 50 chips off me, easy.}
{225}{}{Easy, just guess the Queen, red Queen, and you win. That easy.}
{226}{}{You allergic to easy money? Then get over here.}
{227}{}{Everybody's winning today... you want to be the next one?}
{228}{}{Casinos'll rip you off, rob you blind... Monte treats you right, gives you a fair chance.}
{229}{}{Looking to take a chance, lady? Best odds in New Reno! C'mon...}
{230}{}{You allergic to easy money, lady? Then get over here.}
{231}{}{You, lady. You look like a lucky gal, c'mon over.}
{232}{}{Yo, lady, don't bother with the casinos. Come play with Monte.}
{233}{}{Monte n'est pas ouvert pour les jeux aujourd'hui, j'ai perdu mes foutues cartes.}
{234}{}{[Le vieil homme sourit, et la peau autour de ses yeux se ride.] Tu cherches à jouer, l'ami ?}
{235}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{236}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{237}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, friend?}
{238}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{239}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{240}{}{Three-Card Monte's the name, and the game's the same as the name. Slap down 20 chips, and we'll get down to it.}
{241}{}{You cheater. You no play fair}
{242}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{243}{}{Uh, me flattered but me not want to get down to it now... byyyyye}
{244}{}{Dégage !}
{245}{}{Let's play.}
{246}{}{Uh, get down to what?}
{247}{}{I'm familiar with the game. Let's play.}
{248}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{249}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{250}{}{Pas aujourd'hui, merci.}
{251}{}{Se la mettre où ça ? Mais dans le jeu, bien sûr !}
{252}{}{See... (shows you three cards) ...one of these is a queen. I lay them face down, shuffle them, then you pick which one the queen is. If you're right, you win.}
{253}{}{That simple, pal.}
{254}{}{That simple, lady.}
{255}{}{I'm not playing with a cheater like you.}
{256}{}{Could you explain the rules again?}
{257}{}{Sounds simple enough. Let's play. Here's 20 chips.}
{258}{}{Pas aujourd'hui, merci.}
{260}{}{[Tu lui donnes l'argent. Monte hoche la tête, te montre les cartes, puis les met sur la table et les mélange quelques secondes.]}
{261}{}{So... which one's the queen, pal?}
{262}{}{So... which one's the queen, lady?}
{263}{}{(You think it's the one on the left.)}
{264}{}{(You think it's the one in the middle.)}
{265}{}{(You think it's the one on the right.)}
{266}{}{(You don't know. The cards moved too fast.)}
{267}{}{Lucy leftie}
{268}{}{Middle of th'road}
{269}{}{Rightie tightie}
{270}{}{The one on the left.}
{271}{}{The one on the right.}
{272}{}{The one in the middle.}
{280}{}{[Monte retourne la carte, c'est un 2 de pique.]}
{281}{}{Sorry, pal, not this time, but you were CLOSE.}
{282}{}{Sorry, lady, not this time, but you were CLOSE.}
{283}{}{You sure do got the eye for it, though. Wanna try again?}
{284}{}{You cheater. You no play fair}
{285}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{286}{}{Nuh-uh Me no LIKE game BYYYYE}
{287}{}{I'm not playing with a cheater like you.}
{288}{}{Sure. Here's 20 chips.}
{289}{}{Pas de problème.}
{300}{}{[Tu lui donnes l'argent. Monte hoche la tête, te montre les cartes, puis les met sur la table. Pendant qu'il fait ça, il attrape une carte, tellement vite que tu l'as à peine vu. Ensuite il mélange les cartes quelques secondes.]}
{301}{}{So... which one's the queen, pal?}
{302}{}{So... which one's the queen, lady?}
{303}{}{You put it in sleevie weevie you no play fair}
{304}{}{Lucy leftie}
{305}{}{Middle of th'road}
{306}{}{Rightie tightie}
{307}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{308}{}{The one in your sleeve.}
{309}{}{The one on the left.}
{310}{}{The one on the right.}
{311}{}{The one in the middle.}
{320}{}{QU'EST-CE que t'as dit, l'ami ?}
{321}{}{WHAT did you say, lady?}
{322}{}{You accusing me of cheating?}
{323}{}{Uh-uh. Me KNOW you cheet}
{324}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{325}{}{Oui.}
{326}{}{Screw this. Keep the money, I'm outta here.}
{330}{}{Ecoute, j'ai pas de temps à perdre avec des minables. Tu as payé, t'as eu ta chance. Si tu veux JOUER, ça me va, mais si c'est pour râler quand tu perds, c'est pas la peine, casse-toi !}
{331}{}{ME BREAK YOU}
{332}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{333}{}{That's it. You're dead.}
{334}{}{All right, all right. I'm sorry. Here's 20 chips. Let's play again.}
{335}{}{Screw you. Keep the money, I'm outta here.}
{340}{}{[Tu lui donnes l'argent. Monte hoche la tête, te montre les cartes, puis les met sur la table et les mélange quelques secondes.]}
{341}{}{So... which one's the queen, pal?}
{342}{}{So... which one's the queen, lady?}
{343}{}{(Monte's using his normal deck! You need to steal his other deck to complete the switch.)}
{344}{}{You put it in sleevie weevie you no play fair}
{345}{}{Uh... Lucy leftie}
{346}{}{Uh... Middle of th'road}
{347}{}{Uh... Rightie tightie}
{348}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{349}{}{The one in your sleeve.}
{350}{}{Uh, the one on the left.}
{351}{}{Uh, the one on the right.}
{352}{}{Uh, the one in the middle.}
{360}{}{[Tu lui donnes l'argent. Monte hoche la tête, te montre les cartes, puis les met sur la table et les mélange quelques secondes.]}
{361}{}{(You hand over the cash. Monte looks uncomfortable.) Uh... all right... (Monte puts the cards on the ground and shuffles them.)}
{362}{}{So... which one's the queen, pal?}
{363}{}{So... which one's the queen, lady?}
{364}{}{(Monte's using the marked deck. Any pick is the right one.)}
{365}{}{Leftie! Leftie!}
{366}{}{Rightie! Rightie!}
{367}{}{Middlie! Middlie!}
{368}{}{Oh, I don't know... the one on the left.}
{369}{}{Hmmmm... maybe the one on the right?}
{370}{}{Gee, I'm not sure... I think it's the one in the middle.}
{375}{}{[Monte retourne la carte, c'est la reine de coeur, il semble choqué et paralysé.] Hein... ? Hé. Euh...}
{376}{}{guess you win, pal.}
{377}{}{guess you win, lady.}
{378}{}{(He hands over the cash reluctantly.)}
{379}{}{Again! Again!}
{380}{}{Thanx me go now}
{381}{}{So we gonna play again or what? C'mon, Monte. I'm just getting started.}
{382}{}{Well, thanks, Monte. See you later.}
{385}{}{[Monte retourne la carte, c'est la reine de coeur, il semble choqué et paralysé.] Hein... ? Hé. Euh...}
{386}{}{guess you win, pal.}
{387}{}{guess you win, lady.}
{388}{}{That cleans me out, though... (Looks at you weakly) Anything else I could do for you?}
{389}{}{Nuttin. Me just wanted sum extra EXP. Bye. Bye.}
{390}{}{What have you GOT?}
{391}{}{Why don't you give me some information?}
{392}{}{Forget it, Monte. We'll call it even for today.}
{400}{}{[Il a l'air affligé.] Euh... J'ai bien quelque chose... mais ça vaut vraiment BEAUCOUP plus que ce que tu as gagné...}
{401}{}{Well? What is it?}
{402}{}{If it's worth more to you than dying on Golgotha because you welched on a debt, that's your problem. I'd think
 about it, if I were you.}
{404}{}{Euh... hmmmm... ça dépend de ce que tu veux savoir.}
{405}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{406}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{407}{}{You know where my car is, Monte?}
{408}{}{Got anything you think I should know?}
{409}{}{Nevermind, Monte. We're even. See you later.}
{415}{}{Euh... eh bien... écoute, si on te demande c'est pas moi qui te l'ai dit, mais je parie sur Renesco, cet enfoiré qui tient la pharmacie à l'Ouest. Je sais pas s'il l'a vendu directement au gamin, mais c'est sûr qu'il sait quelque chose. C'est tout ce que je te dirais.}
{416}{}{All right then, Monte. We're even.}
{420}{}{Euh... eh bien... [On dirait qu'il combat à l'intérieur de lui-même.] ... écoute, si on te demande, personne ne t'en a parlé, mais si j'étais toi, j'irais faire un tour à la cave du Desperado.}
{421}{}{All right then, Monte. We're even.}
{425}{}{[Plisse les yeux, se penche.] Je demanderais au vieux Jules à l'entrée de la ville si j'étais toi. Rien ne lui échappe... et si c'était le cas, c'est qu'il le souhaitait comme ça, tu vois ce que je veux dire ?}
{426}{}{All right then, Monte. We're even.}
{430}{}{Eh bien... tu vois ce gars Eldrige qui tient l'Armurerie de New Reno ? Il dit qu'il fait des améliorations d'armes, mais je ne l'ai jamais vu faire aucun travail. Ca pourrait être intéressant de fouiller chez lui... mais si on te demande personne ne t'en a parlé, hein ?}
{431}{}{All right then, Monte. We're even.}
{435}{}{[Monte fronce les sourcils lorsqu'il te voit.] Ecoute, je ne joue plus aujourd'hui, d'accord ? Allez, bouge.}
{436}{}{Can I buy that card you showed me before?}
{437}{}{I wanted some information...}
{438}{}{All right, Monte. I'll leave... for now.}
{440}{}{Non. Je ne m'en séparerai pas. Point barre. C'est un VERITABLE souvenir d'avant-guerre... une petite portion d'histoire. Alors, PAS QUESTION.}
{441}{}{You making me ANOTHER offer? Look, I told you I ain't selling it.}
{442}{}{How about a thousand chips? I got it with me. It's yours in exchange for that card.}
{443}{}{Not even for 750 chips?}
{444}{}{How about 500 chips?}
{445}{}{250 chips sound about right?}
{446}{}{D'accord. J'avais encore une ou deux questions...}
{447}{}{Nevermind then, Monte. I'm outta here.}
{450}{}{T'es sourd ? Ce montant n'est pas assez pour m'intéresser.}
{451}{}{How about I suggest another amount...?}
{452}{}{J'ai d'autres questions...}
{453}{}{Nevermind then, Monte. I'm outta here.}
{460}{}{Hmmm, finalement je crois que ce n'est pas aussi précieux que ça. Ok c'est pour toi, mon pote. [Il jette un coup d'oeil de gauche à droite, se baisse et enlève sa botte. Il tourne le talon et retire la carte de l'intérieur.] Tiens, voilà. Prends en soin.}
{461}{}{J'ai d'autres questions...}
{462}{}{Thanks, Monte. Always a pleasure.}
{465}{}{[Fronce les sourcils.] Ce que je pourrais te dire dépend de ce que tu veux savoir. Et ce ne sera pas gratuit.}
{466}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{467}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{468}{}{You know where my car is, Monte?}
{469}{}{Got anything you think I should know?}
{470}{}{Nevermind then, Monte. I'm outta here.}
{475}{}{Pour tout le Golgotha jamais je ne toucherai à ce sujet. Dégage.}
{476}{}{Look, that subject's just bad news. Leave it alone, all right?}
{477}{}{You making me another offer? Look, I told you I AIN'T going talk about it.}
{478}{}{A thousand chips change your mind? I got it with me.}
{479}{}{Not even for 750 chips?}
{480}{}{How about 500 chips?}
{481}{}{250 chips sound about right?}
{482}{}{Uh... Golgotha?}
{483}{}{J'ai d'autres questions...}
{484}{}{Nevermind then, Monte. I'm outta here.}
{490}{}{[Secoue la tête.] Pas question. En parler pourrait coûter la vie à quelqu'un, à commencer par moi. Oublie ça.}
{491}{}{How about if I offered you this...}
{492}{}{J'ai d'autres questions...}
{493}{}{Nevermind then, Monte. I'm outta here.}
{495}{}{Euh... hé bien... ça fait beaucoup d'argent. [Il se lèche les babines. On dirait qu'il combat à l'intérieur de lui-même... mais la bataille est rapide.] Ecoute, si on te demande, personne ne t'en a parlé...}
{496}{}{Understood. Go on.}
{500}{}{[Sourire narquois.] Peut-être que j'ai entendu quelque chose, peut-être que non. Fais-moi une offre.}
{501}{}{All right... talk a price.}
{502}{}{How about a thousand chips? I got it with me.}
{503}{}{Not even for 750 chips?}
{504}{}{How about 500 chips?}
{505}{}{250 chips sound about right?}
{506}{}{J'ai d'autres questions...}
{507}{}{Nevermind then, Monte. I'm outta here.}
{510}{}{Ha ! Tu ne pourrais même pas acheter un seau de pisse avec si peu. Oublie ça.}
{511}{}{How about if I offered you this...}
{512}{}{J'ai d'autres questions...}
{513}{}{Nevermind then, Monte. I'm outta here.}
{515}{}{Haaaa ben voilà. [Large sourire.] Ecoute, si on te demande tu es au courant de rien, mais si j'étais toi, j'irais faire un tour du côté du sous-sol du Desperado dans la rue de la Vierge. Il y a beaucoup de "rats" par là, si tu vois où je veux en venir.}
{516}{}{J'ai d'autres questions...}
{517}{}{D'accord. Merci.}
{520}{}{[Hausse les épaules.] Peut-être que je sais quelque chose à ce propos, peut-être que non. Donne-moi un prix et j'aurais peut-être quelque chose à dire.}
{521}{}{All right... talk a price.}
{522}{}{How about a thousand chips? I got it with me.}
{523}{}{Not even for 750 chips?}
{524}{}{How about 500 chips?}
{525}{}{250 chips sound about right?}
{526}{}{J'ai d'autres questions...}
{527}{}{Nevermind then, Monte. I'm outta here.}
{530}{}{[Plisse les yeux, se penche en avant.] Pour ce prix là, je ne sais rien du tout.}
{531}{}{How about if I offered you this...}
{532}{}{J'ai d'autres questions...}
{533}{}{Nevermind then, Monte. I'm outta here.}
{535}{}{Ca va à peu près... [Plisse les yeux, se penche en avant.] ... Je demanderais au vieux Jules à l'entrée de la ville si j'étais toi. Rien ne lui échappe... et si c'était le cas, c'est qu'il le souhaitait comme ça, tu vois ce que je veux dire ?}
{536}{}{J'ai d'autres questions...}
{537}{}{All right then, Monte. Thanks.}
{540}{}{[Hausse les épaules.] J'entends des trucs, j'en vois d'autres. Pour 200 jetons tu peux peut-être tirer profit de mon expérience, tu vois ce que je veux dire ?}
{541}{}{Here's 200 chips.}
{542}{}{I'll give you 150.}
{543}{}{100 chips or nothing.}
{544}{}{J'ai d'autres questions...}
{545}{}{Nevermind then, Monte. I'm outta here.}
{550}{}{T'es sourd ? J'ai dit 200 jetons, je le pensais vraiment.}
{551}{}{All right. Here's 200 chips.}
{552}{}{J'ai d'autres questions...}
{553}{}{Nevermind then, Monte. I'm outta here.}
{555}{}{Done. (Monte leans in) Well, know that guy Eldridge, runs New Reno Arms? He SAYS he does
 weapon upgrades, but I never see him do any work. You might want to check out his place... but you didn't hear that from me.}
{556}{}{J'ai d'autres questions...}
{557}{}{Understood. Thanks, Monte.}
{560}{}{C'est le cimetière au Sud de la ville. Ca pue l'enfer ou le paradis, comme tu veux.}
{561}{}{Oh... I see. Now, about the Wright kid...}
{562}{}{Forget the Wright kid. I had some other questions...}
{563}{}{All right then, Monte. Thanks.}
{565}{}{Je parie sur Renesco, cet enfoiré qui tient la pharmacie à l'Ouest. Je sais pas s'il l'a vendu directement au gamin, mais c'est sûr qu'il sait quelque chose. [Jette un oeil autour.] C'est tout ce que je te dirais.}
{566}{}{J'ai d'autres questions...}
{567}{}{All right then, Monte. Thanks.}
{570}{}{[Il jette un oeil autour, se baisse et retire sa botte. Il tourne le talon et retire une carte de l'intérieur... Sur la carte il y a un homme avec un chapeau étrange, portant une massue.] Intéressé ? C'est un véritable souvenir d'avant-guerre.}
{571}{}{No, I already have enough inventory items... I'd rather have some information instead.}
{572}{}{Uh, sure. Why not? This'll settle things between us.}
{573}{}{Sorry pal, no chips, no game. Come back when you got more money.}
{574}{}{Sorry lady, no chips, no game. Come back when you got more money.}
{575}{}{Yeah, maybe next time then.}
{576}{}{You quickly swap Monte's deck of cards for the marked deck.}
{600}{}{spades}
{601}{}{hearts}
{602}{}{diamonds}
{603}{}{clubs}
{604}{}{deux}
{605}{}{trois}
{606}{}{quatre}
{607}{}{cinq}
{608}{}{six}
{609}{}{sept}
{610}{}{huit}
{611}{}{neuf}
{612}{}{dix}
{613}{}{ de }
