{100}{}{Tu vois Monte Trois-Cartes.}
{150}{}{Tu vois un vieil homme au visage décoloré par le soleil. Il est si mince qu'on dirait une brindille.}
{200}{}{Je ne vois pas comment j'ai pu perdre...}
{205}{}{Héé ! Le Héros ! T'es trop fort, vraiment trop fort.}
{215}{}{Où sont passées mes putains de cartes ? Je les avais JUSTE LA.}
{220}{}{Salut mon pote, te prends pas la tête avec les casinos. Viens jouer avec Monte.}
{230}{}{Monte n'est pas ouvert pour les jeux aujourd'hui, j'ai perdu mes foutues cartes.}
{231}{}{[Le vieil homme sourit, et la peau autour de ses yeux se ride.] Tu cherches à jouer, l'ami ?}
{250}{}{Se la mettre où ça ? Mais dans le jeu, bien sûr !}
{260}{}{[Tu lui donnes l'argent. Monte hoche la tête, te montre les cartes, puis les met sur la table et les mélange quelques secondes.]}
{280}{}{(Monte turns over the card. It is the two of spades.)}
{300}{}{[Tu lui donnes l'argent. Monte hoche la tête, te montre les cartes, puis les met sur la table. Pendant qu'il fait ça, il attrape une carte, tellement vite que tu l'as à peine vu. Ensuite il mélange les cartes quelques secondes.]}
{320}{}{QU'EST-CE que t'as dit, l'ami ?}
{330}{}{Ecoute, j'ai pas de temps à perdre avec des minables. Tu as payé, t'as eu ta chance. Si tu veux JOUER, ça me va, mais si c'est pour râler quand tu perds, c'est pas la peine, casse-toi !}
{340}{}{[Tu lui donnes l'argent. Monte hoche la tête, te montre les cartes, puis les met sur la table et les mélange quelques secondes.]}
{360}{}{[Tu lui donnes l'argent. Monte hoche la tête, te montre les cartes, puis les met sur la table et les mélange quelques secondes.]}
{375}{}{[Monte retourne la carte, c'est la reine de coeur, il semble choqué et paralysé.] Hein... ? Hé. Euh...}
{385}{}{[Monte retourne la carte, c'est la reine de coeur, il semble choqué et paralysé.] Hein... ? Hé. Euh...}
{400}{}{[Il a l'air affligé.] Euh... J'ai bien quelque chose... mais ça vaut vraiment BEAUCOUP plus que ce que tu as gagné...}
{405}{}{Euh... hmmmm... ça dépend de ce que tu veux savoir.}
{415}{}{Euh... eh bien... écoute, si on te demande c'est pas moi qui te l'ai dit, mais je parie sur Renesco, cet enfoiré qui tient la pharmacie à l'Ouest. Je sais pas s'il l'a vendu directement au gamin, mais c'est sûr qu'il sait quelque chose. C'est tout ce que je te dirais.}
{420}{}{Euh... eh bien... [On dirait qu'il combat à l'intérieur de lui-même.] ... écoute, si on te demande, personne ne t'en a parlé, mais si j'étais toi, j'irais faire un tour à la cave du Desperado.}
{425}{}{[Plisse les yeux, se penche.] Je demanderais au vieux Jules à l'entrée de la ville si j'étais toi. Rien ne lui échappe... et si c'était le cas, c'est qu'il le souhaitait comme ça, tu vois ce que je veux dire ?}
{430}{}{Eh bien... tu vois ce gars Eldrige qui tient l'Armurerie de New Reno ? Il dit qu'il fait des améliorations d'armes, mais je ne l'ai jamais vu faire aucun travail. Ca pourrait être intéressant de fouiller chez lui... mais si on te demande personne ne t'en a parlé, hein ?}
{435}{}{[Monte fronce les sourcils lorsqu'il te voit.] Ecoute, je ne joue plus aujourd'hui, d'accord ? Allez, bouge.}
{440}{}{Non. Je ne m'en séparerai pas. Point barre. C'est un VERITABLE souvenir d'avant-guerre... une petite portion d'histoire. Alors, PAS QUESTION.}
{450}{}{T'es sourd ? Ce montant n'est pas assez pour m'intéresser.}
{460}{}{Hmmm, finalement je crois que ce n'est pas aussi précieux que ça. Ok c'est pour toi, mon pote. [Il jette un coup d'oeil de gauche à droite, se baisse et enlève sa botte. Il tourne le talon et retire la carte de l'intérieur.] Tiens, voilà. Prends en soin.}
{465}{}{[Fronce les sourcils.] Ce que je pourrais te dire dépend de ce que tu veux savoir. Et ce ne sera pas gratuit.}
{475}{}{Pour tout le Golgotha jamais je ne toucherai à ce sujet. Dégage.}
{490}{}{[Secoue la tête.] Pas question. En parler pourrait coûter la vie à quelqu'un, à commencer par moi. Oublie ça.}
{495}{}{Euh... hé bien... ça fait beaucoup d'argent. [Il se lèche les babines. On dirait qu'il combat à l'intérieur de lui-même... mais la bataille est rapide.] Ecoute, si on te demande, personne ne t'en a parlé...}
{500}{}{[Sourire narquois.] Peut-être que j'ai entendu quelque chose, peut-être que non. Fais-moi une offre.}
{510}{}{Ha ! Tu ne pourrais même pas acheter un seau de pisse avec si peu. Oublie ça.}
{515}{}{Haaaa ben voilà. [Large sourire.] Ecoute, si on te demande tu es au courant de rien, mais si j'étais toi, j'irais faire un tour du côté du sous-sol du Desperado dans la rue de la Vierge. Il y a beaucoup de "rats" par là, si tu vois où je veux en venir.}
{520}{}{[Hausse les épaules.] Peut-être que je sais quelque chose à ce propos, peut-être que non. Donne-moi un prix et j'aurais peut-être quelque chose à dire.}
{530}{}{[Plisse les yeux, se penche en avant.] Pour ce prix là, je ne sais rien du tout.}
{535}{}{Ca va à peu près... [Plisse les yeux, se penche en avant.] ... Je demanderais au vieux Jules à l'entrée de la ville si j'étais toi. Rien ne lui échappe... et si c'était le cas, c'est qu'il le souhaitait comme ça, tu vois ce que je veux dire ?}
{540}{}{[Hausse les épaules.] J'entends des trucs, j'en vois d'autres. Pour 200 jetons tu peux peut-être tirer profit de mon expérience, tu vois ce que je veux dire ?}
{550}{}{T'es sourd ? J'ai dit 200 jetons, je le pensais vraiment.}
{555}{}{Très bien. [Monte se penche en avant.] Hé bien... tu vois ce gars Eldrige qui tient l'Armurerie de New Reno ? Il dit qu'il fait des améliorations d'armes, mais je ne l'ai jamais vu faire aucun travail. Ca pourrait être intéressant de fouiller chez lui... mais si on te demande personne ne t'en a parlé, hein ?!}
{560}{}{C'est le cimetière au Sud de la ville. Ca pue l'enfer ou le paradis, comme tu veux.}
{565}{}{Je parie sur Renesco, cet enfoiré qui tient la pharmacie à l'Ouest. Je sais pas s'il l'a vendu directement au gamin, mais c'est sûr qu'il sait quelque chose. [Jette un oeil autour.] C'est tout ce que je te dirais.}
{570}{}{[Il jette un oeil autour, se baisse et retire sa botte. Il tourne le talon et retire une carte de l'intérieur... Sur la carte il y a un homme avec un chapeau étrange, portant une massue.] Intéressé ? C'est un véritable souvenir d'avant-guerre.}
