{100}{}{Tu vois Mam'zelle Nikki.}
{125}{}{Tu vois une des croupiers du casino.}
{150}{}{Tu vois Mam'zelle Nikki.}
{160}{}{Tu vois Mam'zelle Nikki. Elle te fait signe de venir jouer..}
{170}{}{Tu vois une des croupiers du casino.}
{180}{}{Tu vois une des croupiers du casino. Elle te fait signe de venir jouer..}
{200}{}{::Acclamations::}
{210}{}{Hello, [MM]. Can I help you with... anything?}
{220}{}{On dirait que ce type est déjà en train de jouer avec sa vie.}
{230}{}{Hé, Monsieur Muscles. Tu viens pour dépenser un peu de fric ?}
{250}{}{Hé là, l'acteur. Tu viens pour dépenser un peu de fric ?}
{270}{}{Hé là, mon coeur. Tu viens pour dépenser un peu de fric ?}
{290}{}{Bien, tu es fou de venir ici, mais... place ta mise. Minimum $5. Faites vos jeux...}
{310}{}{Heu, très bien m'sieur. Reviens vite.}
{320}{}{Très bien m'sieur. Reviens vite.}
{330}{}{Désolé, m'sieur. Tu auras plus de chances la prochaine fois.}
{340}{}{Gagné ! Bien joué, m'sieur !}
{350}{}{Gagné ! Tu as doublé ta mise ! Bien joué, m'sieur !}
{360}{}{Gagné ! Tu as triplé ta mise ! La chance est au rendez-vous ce soir ! Bien joué, m'dame !}
{370}{}{Que veux-tu maintenant ? Tu es là pour me faire perdre mon temps, ou vas-tu miser quelque chose ?}
{380}{}{Ouais, j'ai entendu dire qu'il est MORT. C'est ce que tu voulais entendre, assassin ?! Hein ?! Tu vas placer ta mise maintenant ou m'emmerder encore longtemps ?}
{390}{}{Eh bien c'est un pari que tu as perdu, mon coeur, mais si tu es aussi stupide que tu es moche, tu devrais probablement parier à nouveau. J'ai plus r'vu ce clodo depuis qu'il a pigeonné M.Salvatore.}
{400}{}{Mon coeur, je t'ai DIT que je ne savais pas où il était. Maintenant, regarde, je TRAVAILLE ici, alors retourne d'où tu viens --}
{410}{}{Tu m'as touchée, et M.Salvatore va te dépecer vif pour ça.}
{420}{}{De quoi parles-tu ?}
{430}{}{Ecoute, JE TE L'AI DEJA DIT, je ne sais pas où il est. Mais j'ai entendu dire qu'il aurait *peut-être* l'habitude de prendre une chambre au Desperado. Tu devrais trouver quelque chose par là. Maintenant, si ça ne t'ennuie pas, je dois retourner travailler.}
{440}{}{Ecoute, je COMMENCE juste à travailler ici, et je ne saurais reconnaître tous les joueurs et les escrocs de pacotille qui traînent ici. Cependant, je suis assez bonne pour identifier les têtes-de-noeud comme toi.}
{450}{}{Ouais, tu as un peu trop pris de Jet, et tout te semble suspect, c'est ça ?}
{460}{}{Tu vas me débarrasser le plancher immédiatement bon sang. Je n'ai rien d'autre à te dire.}
{470}{}{Tu parles agréablement... Mais les vipères font pareil. PEUT-ETRE que je sais où est Lloyd, PEUT-ETRE que non. Tu as les $500 ?}
{480}{}{Il se POURRAIT que Lloyd ait encore ma part, et je ne suis pas sûre qu'il me la donnera. Il se POURRAIT donc que, pour $500, je PUISSE te dire où se planque ce trou-du-cul.}
{490}{}{[Elle range l'argent dans sa poche.] Va fouiller la salle de la chaudière au sous-sol du Desperado. C'est là que ce fils de pute devait détaler pour se terrer si les choses devaient mal tourner.}
{500}{}{Veux-tu bien dégager de là ?! Les gens nous voient parler comme ça, et donc ils PARLERONT. Compris ?}
{510}{}{Va donc au diable ! Je n'ai rien à te dire, JAMAIS.}
