{100}{}{Tu vois Mam'zelle Nikki.}
{125}{}{Tu vois une des croupiers du casino.}
{150}{}{Tu vois Mam'zelle Nikki.}
{151}{}{You see Darlin' Nikki. She winks at you.}
{152}{}{Tu vois Mam'zelle Nikki. Elle te fait signe de venir jouer..}
{153}{}{You see Darlin' Nikki. Mason was right about her ass.}
{154}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{155}{}{You see Darlin' Nikki. Mason was right about her ass.}
{156}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{160}{}{Tu vois Mam'zelle Nikki. Elle te fait signe de venir jouer..}
{161}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{162}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{170}{}{Tu vois une des croupiers du casino.}
{171}{}{Tu vois une des croupiers du casino. Elle te fait un clin d'oeil.}
{172}{}{Tu vois une des croupiers du casino. Elle te fait signe de venir jouer..}
{173}{}{Tu vois une des croupiers du casino. Elle a de longues et jolies jambes.}
{174}{}{Tu vois une des croupiers du casino. Sa robe recouvre à peine son corps.}
{175}{}{Tu vois une des croupiers du casino. Elle sent vraiiiiment bon.}
{180}{}{Tu vois une des croupiers du casino. Elle te fait signe de venir jouer..}
{181}{}{Tu vois une des croupiers du casino. Sa robe recouvre à peine son corps.}
{182}{}{Tu vois une des croupiers du casino. Sa robe recouvre à peine son corps.}
{183}{}{Tu vois une des croupiers du casino. Elle te fait signe de venir jouer..}
{200}{}{::Acclamations::}
{201}{}{::Applaudissements::}
{202}{}{::Siffle::}
{203}{}{ ! Sois le bienvenu au casino, héros !}
{204}{}{Thought you'd forgotten about us while you were saving the world.}
{210}{}{Bonjour, }
{211}{}{Si tu cherches de la compagnie plus tard...}
{212}{}{Hey, you...(winks)...you looking to gamble?}
{213}{}{Il est trop... ::Frissonne:: ... dangereux.}
{214}{}{Bienvenue au casino, }
{215}{}{Tu peux glisser un mot sympa sur moi au patron ?}
{216}{}{Bonjour, m'dame. Dis-moi si je peux t'aider en quoi que ce soit.}
{217}{}{Tu cherches à faire des paris, m'dame ?}
{218}{}{Elle est trop... ::Frissonne:: ... dangereuse.}
{220}{}{On dirait que ce type est déjà en train de jouer avec sa vie.}
{221}{}{Heu, je pense qu'il est entré dans le mauvais casino...}
{222}{}{S'il ne part pas avant que les gars le voient...}
{223}{}{Ho-ho. Problèmes en vue...}
{224}{}{On dirait que cette meuf est déjà en train de jouer avec sa vie.}
{225}{}{Heu, je pense qu'elle est entrée dans le mauvais casino...}
{226}{}{Si elle ne part pas avant que les gars la voient...}
{230}{}{Hé, Monsieur Muscles. Tu viens pour dépenser un peu de fric ?}
{231}{}{Hey, champ...(winks)...you looking to gamble?}
{232}{}{Hey, champ...(smiles)...wanna take a chance?}
{233}{}{Si tu cherches de la compagnie plus tard...}
{234}{}{Je me demande si je pourrais lui parler...}
{235}{}{Hé, }
{236}{}{Si tu cherches à gagner du fric, tu es tombé au bon endroit.}
{237}{}{Best casino in New Reno. In the WORLD, even.}
{238}{}{Dame Chance est ici ce soir... Rien que des gagnants !}
{239}{}{Reste là, }
{240}{}{Tu veux un autre verre ?}
{241}{}{Bienvenue au casino, }
{242}{}{Bonjour, }
{243}{}{Tu cherches à parier, }
{244}{}{Bienvenue au casino, }
{250}{}{Hé là, l'acteur. Tu viens pour dépenser un peu de fric ?}
{251}{}{Hé, }
{252}{}{Hé, }
{253}{}{Si tu cherches à gagner de l'argent }
{254}{}{Best casino in New Reno. In the WORLD, even.}
{255}{}{Dame Chance est ici ce soir... Rien que des gagnants !}
{266}{}{Reste là, }
{267}{}{Tu veux un autre verre ?}
{268}{}{Bienvenue au casino, }
{269}{}{Hey there, Mrs. Movie Star. Looking to spend a paycheck?}
{270}{}{Hé là, mon coeur. Tu viens pour dépenser un peu de fric ?}
{271}{}{Hey, sweetie...(winks)...you looking to gamble?}
{272}{}{Hey, sweetie...(smiles)...wanna take a chance?}
{273}{}{Si tu cherches à gagner du fric, tu es tombé au bon endroit.}
{274}{}{Best casino in New Reno. In the WORLD, even.}
{275}{}{Dame Chance est ici ce soir... Rien que des gagnants !}
{276}{}{Reste là, et gagne un peu d'argent.}
{277}{}{Tu veux un autre verre, mon chou ?}
{278}{}{Bienvenue au casino, mon chou.}
{279}{}{Cette table est libre si tu cherches à jouer...}
{280}{}{Hé là, mon chou. Tu viens pour dépenser un peu de fric ?}
{281}{}{Tu veux faire des paris, mon chou ?}
{282}{}{Bienvenue au casino, mon chou.}
{290}{}{Bien, tu es fou de venir ici, mais... place ta mise. Minimum $5. Faites vos jeux...}
{291}{}{Um... place your bets... minimum bet 5 chips. Place your bets...}
{292}{}{Place your bet, sir. Minimum bet 5 chips. Place your bets...}
{293}{}{Place your bet, ma'am. Minimum bet 5 chips. Place your bets...}
{294}{}{Place your bets, minimum bet 5 chips. Place your bets...}
{295}{}{Moi mis-illeur que toi.}
{296}{}{Moi jouer aux dés dans culotte.}
{297}{}{What this game? Can you bet Gecko skin? Me got geck... ooooh... pretty lights over there!}
{298}{}{Bet 5 chips?}
{299}{}{Bet 15 chips?}
{300}{}{Bet 25 chips?}
{301}{}{Bet 50 chips?}
{302}{}{You Nikki?}
{303}{}{How you doing, Nikki?}
{304}{}{Whoa, too rich for my blood. I'm outta here.}
{305}{}{Pas de pari aujourd'hui, merci.}
{310}{}{Heu, très bien m'sieur. Reviens vite.}
{311}{}{Heu, très bien m'dame. Reviens vite.}
{312}{}{Hum... J'ai entendu dire qu'ils vendaient des cerveaux là-bas. Tu devrais peut-être aller voir.}
{313}{}{Saaaluuut.}
{314}{}{Ar'voir.}
{315}{}{Uh... brains... what them?}
{320}{}{Très bien m'sieur. Reviens vite.}
{321}{}{Très bien m'dame. Reviens vite.}
{322}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{323}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{324}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{325}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{326}{}{Je sais, merci.}
{327}{}{Maybe so, but at least *I* don't live here.}
{330}{}{Désolé, m'sieur. Tu auras plus de chances la prochaine fois.}
{331}{}{Désolé, m'dame. Tu auras plus de chances la prochaine fois.}
{332}{}{Désolé. Tu auras plus de chances la prochaine fois.}
{333}{}{You have [C] chips. Keep playing?}
{334}{}{Ca c'est une bonne journée.}
{335}{}{Ca c'est une bonne soirée.}
{340}{}{Gagné ! Bien joué, m'sieur !}
{341}{}{Winner! Well done, ma'am!}
{342}{}{Winner!}
{343}{}{You have [C] chips. Keep playing?}
{344}{}{Ca c'est une bonne journée.}
{345}{}{Ca c'est une bonne soirée.}
{350}{}{Gagné ! Tu as doublé ta mise ! Bien joué, m'sieur !}
{351}{}{Gagné ! Tu as doublé ta mise ! Bien joué, m'dame !}
{352}{}{Gagné ! Tu as doublé ta mise !}
{353}{}{You have [C] chips. Keep playing?}
{354}{}{Ca c'est une bonne journée.}
{355}{}{Ca c'est une bonne soirée.}
{360}{}{Gagné ! Tu as triplé ta mise ! La chance est au rendez-vous ce soir ! Bien joué, m'dame !}
{361}{}{Gagné ! Vous avez triplé votre mise ! La chance est avec vous ce soir ! Bien joué m'dame !}
{362}{}{Gagné ! Tu as triplé ta mise !}
{363}{}{You have [C] chips. Keep playing?}
{364}{}{Ca c'est une bonne journée.}
{365}{}{Ca c'est une bonne soirée.}
{370}{}{Que veux-tu maintenant ? Tu es là pour me faire perdre mon temps, ou vas-tu miser quelque chose ?}
{371}{}{I'm whoever you WANT me to be, sweetheart. Now, you gonna place a bet?}
{372}{}{I'm whoever you WANT me to be, girlfriend. Now, you gonna place a bet?}
{373}{}{Place a bet.}
{374}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{375}{}{Yeah, I'm betting you and Pretty Boy Lloyd were both stealing money from Mr. Salvatore. Hard to believe you
 didn't notice him cheating all those times.}
{376}{}{Tu connais quelqu'un du nom de Lloyd Beau Gosse ?}
{377}{}{We'll talk later, Nikki.}
{380}{}{Ouais, j'ai entendu dire qu'il est MORT. C'est ce que tu voulais entendre, assassin ?! Hein ?! Tu vas placer ta mise maintenant ou m'emmerder encore longtemps ?}
{381}{}{Nope. You gonna place a bet?}
{382}{}{Place a bet.}
{383}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{384}{}{Yeah, I'm betting you and Pretty Boy Lloyd were both stealing money from Mr. Salvatore. Hard to believe you didn't notice
 Lloyd cheating all those times.}
{385}{}{We'll talk later, Nikki.}
{390}{}{Eh bien c'est un pari que tu as perdu, mon coeur, mais si tu es aussi stupide que tu es moche, tu devrais probablement parier à nouveau. J'ai plus r'vu ce clodo depuis qu'il a pigeonné M.Salvatore.}
{391}{}{Then that's a bet you'd lose, sweetheart. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{392}{}{Then that's a bet you'd lose, girlfriend. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{393}{}{Maybe you didn't hear me the first time, so for the benefit of the hearing impaired: Where is Lloyd?}
{394}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{395}{}{Fine. We'll talk later, Nikki.}
{400}{}{Mon coeur, je t'ai DIT que je ne savais pas où il était. Maintenant, regarde, je TRAVAILLE ici, alors retourne d'où tu viens --}
{401}{}{Girlfriend, I TOLD you that I don't know where he is. Now, look, I'm WORKING here, so go back to whatever rock you --}
{402}{}{Nikki, Nikki... I'm losing PATIENCE here. If you don't tell me where Lloyd is, I'm going to lose my temper, too.}
{403}{}{Nikki, I don't know what happened between you and Lloyd. But guess what? I don't NEED to know. I'll just tell
 Mr. Salvatore what I suspect.}
{404}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{405}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{406}{}{We'll talk later then, Nikki.}
{410}{}{Tu m'as touchée, et M.Salvatore va te dépecer vif pour ça.}
{411}{}{Salvatore won't protect you; dealers like you are a chip a dozen. Cut the shit and tell me where Lloyd is or ELSE.}
{412}{}{Salvatore won't protect you; he's dead. Cut the shit and tell me where Lloyd is or ELSE.}
{413}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{414}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{415}{}{We'll talk later then, Nikki.}
{420}{}{De quoi parles-tu ?}
{421}{}{Nikki, if you don't tell me everything right now, I'll tell Mr. Salvatore you were in on it, whether you were or not.
 He'll have Mason cut you up seven ways to Sunday, and have your job filled in an hour.}
{422}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{423}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{424}{}{We'll talk later then, Nikki.}
{430}{}{Ecoute, JE TE L'AI DEJA DIT, je ne sais pas où il est. Mais j'ai entendu dire qu'il aurait *peut-être* l'habitude de prendre une chambre au Desperado. Tu devrais trouver quelque chose par là. Maintenant, si ça ne t'ennuie pas, je dois retourner travailler.}
{431}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{432}{}{Pretty suspicious that you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{433}{}{We'll talk later then, Nikki.}
{440}{}{Ecoute, je COMMENCE juste à travailler ici, et je ne saurais reconnaître tous les joueurs et les escrocs de pacotille qui traînent ici. Cependant, je suis assez bonne pour identifier les têtes-de-noeud comme toi.}
{441}{}{Oh, so that's how you and Lloyd hooked up then?}
{442}{}{So you just started work, huh? Pretty convenient. Well, that's all I need to know. Tell Lloyd he's a dead man.}
{443}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{444}{}{We'll talk later then, Nikki.}
{450}{}{Ouais, tu as un peu trop pris de Jet, et tout te semble suspect, c'est ça ?}
{451}{}{It IS suspicious. You should have had Lloyd pegged for what he was as soon as he walked in this casino.}
{452}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{453}{}{We'll talk later then, Nikki.}
{460}{}{Tu vas me débarrasser le plancher immédiatement bon sang. Je n'ai rien d'autre à te dire.}
{461}{}{I got nothing to say to you. Get out of here.}
{462}{}{Not now, maybe. We'll talk later though, Nikki. Count on it.}
{470}{}{Tu parles agréablement... Mais les vipères font pareil. PEUT-ETRE que je sais où est Lloyd, PEUT-ETRE que non. Tu as les $500 ?}
{471}{}{Maybe. Depends on what you got for me.}
{480}{}{Il se POURRAIT que Lloyd ait encore ma part, et je ne suis pas sûre qu'il me la donnera. Il se POURRAIT donc que, pour $500, je PUISSE te dire où se planque ce trou-du-cul.}
{481}{}{Done. Here's the 500 chips. Tell me where he is.}
{482}{}{That's a pretty steep price for a whole bunch of "maybes" and "coulds." I'll find him on my own.}
{483}{}{I don't have enough chips, but I'll be back. You better still be here when I return.}
{490}{}{[Elle range l'argent dans sa poche.] Va fouiller la salle de la chaudière au sous-sol du Desperado. C'est là que ce fils de pute devait détaler pour se terrer si les choses devaient mal tourner.}
{491}{}{All right then. Later, Nikki.}
{500}{}{Veux-tu bien dégager de là ?! Les gens nous voient parler comme ça, et donc ils PARLERONT. Compris ?}
{501}{}{All right then. Later, Nikki.}
{510}{}{Va donc au diable ! Je n'ai rien à te dire, JAMAIS.}
{511}{}{Breaks my heart. Later, Nikki.}
{600}{}{You bribe Nikki in telling you where Lloyd might be hiding.}
{1210}{}{. Can I help you with... anything?}
{1214}{}{.}
{1235}{}{. Tu viens pour dépenser un peu de fric ?}
{1239}{}{, et gagne un peu d'argent.}
{1241}{}{.}
{1242}{}{. Dis-moi si je peux t'aider en quoi que ce soit.}
{1243}{}{ ?}
{1244}{}{.}
{1251}{}{...(winks)...you looking to gamble?}
{1252}{}{...(smiles)...wanna take a chance?}
{1253}{}{, you came to the right place.}
{1266}{}{, et gagne un peu d'argent.}
{1268}{}{.}
{1314}{}{ could always use new inventory item}
{2699}{}{Tu dances ce soir ?}
