{100}{}{Tu vois le chef croupier du casino.}
{150}{}{Tu vois un homme très bien habillé. Il inspecte le casino.}
{200}{}{Euh... Il va falloir enlever cette armure.}
{210}{}{Hum, que cherchez-vous à faire en venant fouiner par ici, monsieur ?}
{220}{}{Hum, que cherchez-vous à faire en venant fouiner par ici, madame ?}
{230}{}{Good evening, [MM], sir.}
{240}{}{Good evening, [MM], ma'am.}
{250}{}{Good day, [MM], sir.}
{260}{}{Good day, [MM], ma'am.}
{270}{}{L'ami, tu te diriges vers le mauvais casino.}
{280}{}{Monsieur, je regrette mais vous allez devoir laisser cette arme en lieu sûr.}
{290}{}{Madame, je regrette mais vous allez devoir laisser cette arme en lieu sûr.}
{300}{}{Chérie, je suis désolé, tu ne peux pas porter d'armes dans le casino. [Sourires.] Tu es déjà suffisamment mortel.}
{310}{}{Avec un corps pareil, tu vas avoir du mal à te faufiler mon chou.}
{320}{}{Tribal, tu ferais mieux de sécuriser cette arme dès *maintenant*.}
{330}{}{Tribal, tu ferais mieux d'arrêter de te faufiler partout dès *maintenant*.}
{340}{}{[A Myron] Hé, hé... Myron ! Ça fait longtemps que je ne t'ai pas vu en dehors du labo.}
{350}{}{[Il fait un signe de tête à Marcus.] Pas de mutants. Il attend dehors.}
{360}{}{Pas de droïdes.}
{370}{}{J'suis pas censé parler pendant le boulot, mais j'suis content que t'aies botté le cul de l'Enclave.}
{380}{}{On a besoin d'autres jetons à la table trois...}
{390}{}{On a besoin d'autres jetons à la table trois...}
{400}{}{Hé, [X] ! J'ai entendu dire que c'était vous qui aviez ramené l'Enclave à l'âge de pierre ! [Devient formel.] On m'a demandé de vous donner des jetons, c'est le casino qui offre. Amusez-vous bien, monsieur.}
{420}{}{Hé, regardez qui est là ! Hé, [PS]. [Sourires.] Bienvenue à [CN]. J'adore tes films.}
{440}{}{Vas-y. Que veux-tu savoir ?}
{460}{}{Euh, vous feriez mieux de partir, monsieur.}
{470}{}{Ouais, ta maman a dit que j'étais spécial moi aussi. Maintenant, va te faire voir... Elle est peut-être quelque part sur la rue de la Vierge.}
{480}{}{Je suis le chef croupier. [Il a l'air légèrement irrité.] Bon, que puis-je faire pour toi ?}
{490}{}{C'est [CN]. Si t'as besoin de quelque chose, t'as qu'à demander.}
{500}{}{Le meilleur foutu casino de la ville... mais je suis un peu partial. [Rires.] Tu veux savoir autre chose ?}
{510}{}{La famille [CA]. Ils ont énormément investi d'énergie dans cet endroit pour en faire un vrai lieu de nuit, un véritable bijou à New Reno.}
{520}{}{Ce type ? Le vieux McGee ? Un vieux fou... Voilà des années qu'il joue à cette machine en attendant de remporter le gros jackpot. La fortune de toute sa vie a probablement été engloutie dans cette machine, mais elle ne lui rendra pas une seule pièce.}
{530}{}{[Secoue la tête.] Nan, elle est juste un peu têtue... Comme lui. [Hausse les épaules.] Elle devrait pouvoir être réparée, mais nous n'avons aucun technicien capable de réparer ce fichu truc.}
{540}{}{Ouais, ce fils de pute est venu ici il y a environ une semaine, il a grugé une table d'environ un millier de jetons, puis il est parti. Je ne sais pas où il est maintenant, mais il avait une chambre au Desperado.}
{550}{}{Nikki ? [Regarde le sol.] Ouais, elle est là-bas, à la table centrale. Y'a un problème ?}
{560}{}{Elle *s'appelait* Nikki. Elle travaillait ici mais il lui est arrivé des bricoles... Il n'y a pas très longtemps.}
{570}{}{Elle s'appelait Nikki. Elle travaillait ici mais elle s'est envolée il n'y a pas très longtemps. Elle a juste rassemblé ses affaires et elle est partie.}
{580}{}{Certainement, c'est bon pour les affaires. Le vestiaire se trouve à l'arrière...}
{590}{}{[Secoue la tête.] Non, on se remet tout juste de ton dernier gag. Tu devrais aller faire un tour dans d'autres casinos.}
{600}{}{Tu fais le décompte de la soirée. [C] = chips. Ce n'est pas un mauvais butin.}
{610}{}{Ouais, il pue encore plus que la merde de Brahmine. Encore toi... ? [Il te regarde de haut en bas avec scepticisme.] Aïe, bon sang, pourquoi pas ? Une petite improvisation ne peut pas faire de mal, mais la foule est un peu dure... J'espère que tu vas t'en sortir.}
