{100}{}{}
{101}{}{}
{110}{}{Tes pieds te démangent vraiment beaucoup.}
{120}{}{Tu développes une grosse et vilaine boursouflure sur chaque pied.}
{130}{}{Tes chaussures te semblent trop serrées. L'inflammation gagne ces boursouflures.}
{140}{}{Ces horribles boursouflures sur chaque pied ressemblent de plus en plus à un orteil supplémentaire. Mais au moins, les démangeaisons persistantes et l'inflammation ont disparu.}
{141}{}{Bon Dieu, c'est Bess !}
{150}{}{Tu gagnes }
{151}{}{ points d'expérience pour avoir trouvé le J.E.K.}
