{100}{}{Tu vois un terminal d'ordinateur.}
{101}{}{Tu vois le terminal d'interface vocale.}
{102}{}{Tu vois un terminal d'ordinateur standard modifié pour les commandes vocales.}
{103}{}{[Tu examines le terminal d'ordinateur, mais tu ne trouves rien d'anormal.]}
{104}{}{[Le frapper d'une manière bien *spéciale*]}
{105}{}{[Donner un coup sur cet endroit *spécial*]}
{106}{}{[Lancer le programme de diagnostic]}
{107}{}{[L'ouvrir et regarder à l'intérieur]}
{108}{}{[Ne pas s'en occuper]}
{109}{}{[Tu observes la console pendant un moment et tu choisis le meilleur endroit où frapper. Après lui avoir délivré ton meilleur coup *réparateur*, le moniteur clignote quelques instants, puis se stabilise. Il ne se passe rien d'autre.]}
{110}{}{[Donner un coup sur cet endroit *spécial*]}
{111}{}{[Lancer le programme de diagnostic]}
{112}{}{[L'ouvrir et regarder à l'intérieur]}
{113}{}{[Ne pas s'en occuper]}
{114}{}{[Cette méthode de réparation bien connue produit deux résultats. Premièrement, le moniteur semble se détraquer durant quelques secondes avant de se stabiliser. Deuxièmement, tu entends un bruit métallique et le panneau sur lequel tu as cogné tombe par terre. ]}
{115}{}{[Lancer le programme de diagnostic]}
{116}{}{[Bon sang, cette saleté de truc s'est ouverte. Tu devrais regarder à l'intérieur.]}
{117}{}{[Ne pas s'en occuper]}
{118}{}{[Tu es sûr que le système devrait disposer d'un ensemble de routines de diagnostic. Les entrées du clavier semblent cependant désactivées. L'unité n'accepte que les commandes vocales.]}
{119}{}{La seule chose qui reste à faire est de regarder à l'intérieur.}
{120}{}{[Ne pas s'en occuper]}
{121}{}{[En observant la masse de câbles et de cartes de circuit, tu comprends que le système a été volontairement saboté. Une des cartes de circuit, le module de reconnaissance vocale, est irréparable et doit être remplacée. Il ne te reste plus qu'à trouver un module de remplacement.]}
{122}{}{C'est terminé.}
{123}{}{C'est terminé.}
{124}{}{[Installer le module dans le terminal]}
{125}{}{[Le terminal requiert un module de reconnaissance vocale pour fonctionner]}
{126}{}{C'est terminé.}
{127}{}{[Le système fonctionne bien maintenant.]}
{128}{}{Accès aux séquences de sécurité, chargement de l'affichage holographique...}
{129}{}{Tu es le dernier, Gruthar. Les tâches de ton espèce vont bientôt être nettoyées.}
{130}{}{Dis à ton soi-disant président qu'il brûlera pour cela.}
{131}{}{Bref. Tu n'as jamais été rien d'autre qu'un animal qui parle.}
{132}{}{Possible, mais nous sommes issus de vos expériences. Vous nous avez donné la vie !}
{133}{}{Et maintenant, je t'apporte la mort.}
{134}{}{Prenez son corps. Le médecin voulait un spécimen.}
{135}{}{Leur sang coulera tel le Nil !}
