{100}{}{Tu vois un vieux type à l'air gentil.}
{101}{}{Voici le Dr Jubilé.}
{102}{}{C'est un vieil homme à la barbe blanche et au regard un peu vide.}
{103}{}{Je suis le Dr Jubilé. Qu'est-ce qui ne va pas mon p'tit ?}
{104}{}{Qu'est-ce qui ne va pas, mon p'tit ?}
{105}{}{Moi avoir blessure.}
{106}{}{Je dois voir un médecin.}
{107}{}{Tu ne peux pas prendre des remèdes et arrêter de m'embêter avec ces fadaises ?}
{108}{}{Hé, mais tu saignes à peine.}
{109}{}{Je ne sais pas. Je ne crois pas pouvoir la sauver. On va peut-être devoir amputer cette jambe.}
{110}{}{C'est une plaisanterie.}
{111}{}{Ah, ah.}
{112}{}{Et voilà, mon garçon.}
{113}{}{Encore une fois.}
{114}{}{Merci docteur. Je peux peut-être te poser quelques questions.}
{115}{}{Salut.}
{116}{}{Ca te coûtera $50.}
{117}{}{Contente-toi de me guérir.}
{118}{}{Je ne reste pas ici.}
{119}{}{Toi guérir.}
{120}{}{Moi partir maintenant.}
{121}{}{Non. Je ne plaisante jamais. Il vaut mieux couper cette jambe avant que la gangrène ne s'installe.}
{122}{}{Tu ne couperas rien, tu entends ?!}
{123}{}{C'est bon, je m'en vais.}
{124}{}{Bon, si ça s'infecte, c'est pas de ma faute.}
{125}{}{C'est pas un hôpital de charité ici ! Trouve de l'argent et on verra.}
{126}{}{Alors, que puis-je faire pour toi ?}
{127}{}{Accouche !}
{128}{}{L'Abri 13 ?}
{129}{}{Sais-tu où se trouve l'Abri 13 ?}
{130}{}{Quelqu'un m'a dit que M. Westin n'allait pas bien. C'est vrai ? J'ai peur qu'il ne lui arrive quelque chose. Il me doit de l'argent.}
{131}{}{Petit Salé dit que tu lui as volé une carte. C'est quoi cette histoire ?}
{132}{}{Je cherche du travail. Tu sais quelque chose ?}
{133}{}{Docteur, tu n'aurais pas entendu parler d'un groupe qui combat ces affreux esclavagistes ?}
{134}{}{Eh bien, tu ne devrais pas t'en faire, mon garçon. S'il ne se surmène pas, il nous enterrera tous. Mais seulement s'il suit mes conseils et s'il prend ses remèdes.}
{135}{}{C'est bon à savoir. Je me posais une autre question.}
{136}{}{Merci, docteur.}
{137}{}{Ce vieux poivrot ! La seule chose qu'il m'ait jamais donnée, c'est ma toile d'Elvis.}
{138}{}{Une toile d'Elvis ? Je peux voir ?}
{139}{}{Pas une carte, hein ? Bien, laisse-moi t'occuper la mémoire avec autre chose.}
{140}{}{Bon, il faut que je continue.}
{141}{}{J'avais pas entendu ça depuis que ce vieux Petit Salé a été amené ici. Insolation. La fièvre pendant 3 jours. Il divaguait et disait qu'il avait trouvé l'Abri 13, le Filon Mère.}
{142}{}{Le Filon Mère ?}
{143}{}{Alors, où se trouve-t-il ?}
{144}{}{Où Abri ?}
{145}{}{Je ne saurais pas dire. Petit Salé disait toujours qu'il avait une carte mais personne ne l'a jamais vue.}
{146}{}{Petit Salé ?}
{147}{}{Demander encore.}
{148}{}{C'est plus que ce que j'avais auparavant.}
{149}{}{Le gros. Petit Salé était un ancien chercheur d'uranium, un ivrogne si tu veux savoir. Il vit sur les terres de Westin.}
{150}{}{Une autre question...}
{151}{}{Merci pour l'histoire.}
{152}{}{Eh bien, c'est que je comptais l'échanger contre de l'argent. Je te fais un prix : $}
{153}{}{Plus tard peut-être. Une autre question...}
{154}{}{Plus tard peut-être, il faut que je parte.}
{155}{}{Petit Salé était un ancien chercheur d'uranium. Il vit sur les terres de Westin.}
{156}{}{Une autre question...}
{157}{}{Merci pour l'histoire.}
{158}{}{Va parler à la Présidente Tandi. J'ai entendu dire qu'elle cherchait quelqu'un de spécial.}
{159}{}{Une autre question...}
{160}{}{Merci.}
{161}{}{Peut-être. Un certain groupe oeuvre contre l'esclavage et bien d'autres vices. Parfois tu peux les trouver au grand magasin. Ils travaillent sur une automobile.}
{162}{}{Une autre question...}
{163}{}{Merci.}
{164}{}{Hé, bas les pattes !}
{165}{}{Doucement ! Une dose infime et c'est le feu d'artifice !}
{166}{}{Repose ça ! Tu pourrais vraiment te faire mal.}
{167}{}{Ces remèdes sont pour M.Westin, pas pour toi. Repose ça.}
{168}{}{Ne t'approche pas de ça. Il faut être prudent. Je voudrais pas que M.Westin prenne les mauvais remèdes.}
{169}{}{Attention ! J'ai mesuré les doses pour M.Westin.}
{170}{}{Je suis le Dr Jubilé. Qu'est-ce qui ne va pas, ma p'tite ?}
{171}{}{Qu'est-ce qui ne va pas, ma p'tite ?}
{172}{}{Et voilà, mademoiselle.}
{173}{}{Ben, ma p'tite, tu ne devrais pas t'en faire. S'il ne se surmène pas, il nous enterrera tous. Mais seulement s'il suit mes conseils et s'il prend ses remèdes.}
{174}{}{Certainement. Voici les $}
{175}{}{Merci, j'ai essayé de soutirer l'argent à Petit Salé, mais cet imbécile n'en avait jamais.}
{176}{}{.}
