{100}{}{Tu vois une jolie jeune femme en tenue de combat.}
{101}{}{Voici Elise.}
{102}{}{Elle a un air de quelqu'un à qui on ne la fait pas, comme si elle était habituée à donner des ordres et à se faire obéir.}
{103}{}{Que veux-tu ?}
{104}{}{Encore toi ?}
{105}{}{C'est Karl qui m'envoie.}
{106}{}{Dr Jubilé m'a dit que je devrais te parler.}
{107}{}{Qui es-tu ?}
{108}{}{Hein ?}
{109}{}{Je cherche un groupe qui déteste l'esclavage. Il s'appelle le Commando de la Nouvelle Californie.}
{110}{}{Tu peux réparer ma voiture ?}
{111}{}{Je croyais que cet endroit était déserté.}
{112}{}{Est-ce qu'il savait ? Que t'a-t-il dit ?}
{113}{}{Pas grand-chose. Que vous étiez de braves gens et que j'irais peut-être au pieu avec toi.}
{114}{}{Il a dit que tu payais bien.}
{115}{}{Moi, c'est Elise. Et voilà Gond. On est membres d'un *groupe* qui essaie de faire le bien.}
{116}{}{On ne dirait pas une fondation charitable ou une église.}
{117}{}{Ca a l'air intéressant. Le bien dans quel sens ?}
{118}{}{Je veux seulement faire réparer ma voiture.}
{119}{}{Sors d'ici. Le saloon, c'est sur l'avenue principale.}
{120}{}{Qui déteste l'esclavage, hein ? Intéressant. Que ferais-tu si tu trouvais ce groupe ?}
{121}{}{Je leur demanderais si je peux me joindre à eux.}
{122}{}{Je leur casserais la gueule.}
{123}{}{Rien.}
{124}{}{Ca ne te regarde pas. Maintenant, va-t'en.}
{125}{}{On ne s'occupe plus de voiture. C'est fermé, pour toujours. Au revoir.}
{126}{}{Non. Au revoir.}
{127}{}{D'accord. Alors, dis-moi. Que penses-tu des esclavagistes ?}
{128}{}{Je les déteste. Ils sont dégoûtants, vils, abjects.}
{129}{}{S'ils me fichent la paix, je leur fiche la paix.}
{130}{}{Plusieurs de mes meilleurs amis sont esclavagistes.}
{131}{}{Y'a que l'argent qui t'intéresse ?}
{132}{}{Bien sûr que non. Je crois en la vérité, la justice, et la lutte en faveur des opprimés.}
{133}{}{C'est un début, en attendant que quelqu'un lance une meilleure cause.}
{134}{}{Quoi d'autre ?}
{135}{}{Me raconte pas de conneries. Je vois le genre. Au revoir.}
{136}{}{Si tu ne sais pas, j'ai perdu mon temps. Au revoir.}
{137}{}{Non, nous ne sommes pas une organisation religieuse. Je peux te poser une question ?}
{138}{}{Vas-y.}
{139}{}{Pas si vite. Tu dois passer un test avant d'entrer dans le Commando.}
{140}{}{Bien. Dis-moi.}
{141}{}{Un test ? On est où ici, à l'école ?}
{142}{}{Il y a un esclavagiste à la sortie de la ville. Tu as peut-être vu sa maison. Libère ses esclaves et reviens nous raconter.}
{143}{}{Pas de problèmes.}
{144}{}{Pas question. Je ne veux pas créer d'ennuis.}
{145}{}{Eh bien, c'est ton jour de chance.}
{146}{}{C'est ce genre d'attitude qui cautionne l'atrocité de l'esclavage. Je regrette mais il n'y a pas de place pour toi dans notre organisation.}
{147}{}{Ok.}
{148}{}{Alors, tu as changé d'avis ? Tu veux faire tes preuves ?}
{149}{}{Certainement.}
{150}{}{Que dois-je faire ?}
{151}{}{Tu n'as pas quelque chose à faire ? Reviens quand le travail sera fini.}
{152}{}{J'ai entendu la nouvelle. Tu as libéré les esclaves. Joli travail ! Alors, tu veux faire partie du Commando ?}
{153}{}{Oui.}
{154}{}{Non.}
{155}{}{J'ai entendu dire que tu as libéré tous les esclaves qui étaient hors de la ville. Ce que tu as fait est très bien et je voulais te serrer la main.}
{156}{}{Merci.}
{157}{}{C'est simple. Nous croyons que l'esclavage est mal et que nous devons le combattre. En RNC, nous avons beaucoup d'amis en haut lieu. Grâce à eux, nous avons aboli l'esclavage dans le Sud, et nous espérons gagner au Nord.}
{158}{}{Le Commando, j'aimerais faire partie d'un tel groupe. Inscris-moi.}
{159}{}{Intéressant... Je vais réfléchir à ce que tu m'as dit.}
{160}{}{Jures-tu de combattre l'esclavage dès que l'occasion se présentera et d'aider les membres du Commando ?}
{161}{}{Oui.}
{162}{}{Non.}
{163}{}{Félicitations, tu fais partie du Commando.}
{164}{}{Tu es des nôtres. Mais en ce moment il n'y a pas grand-chose à faire, c'est dommage. La plupart de nos hommes sont partis en patrouille. Je préviendrai tout le monde que tu es des nôtres désormais. Je n'ai pas envie que tu te fasses tirer dessus par l'un d'entre nous.}
{165}{}{Nous cherchons toujours de braves gens pour servir notre cause. Si tu changes d'avis, viens me voir. Tu ne veux pas saisir ta chance et te joindre à nous ?}
{166}{}{Non.}
{167}{}{Maintenant que tu le dis, je crois que j'aimerais bien faire partie du Commando.}
{168}{}{Je vois. Je représente un groupe, le Commando de la Nouvelle Californie. Avec tes opinions, tu peux prétendre à devenir membre. Ca t'intéresse ?}
{169}{}{Super ! Inscris-moi.}
{170}{}{Ca a l'air intéressant. Que peux-tu me dire sur le Commando ?}
{171}{}{Je vois. Merci de nous avoir rendu visite mais je crois que nous n'avons plus rien à nous dire. Si tu changes d'avis, viens me voir.}
{172}{}{Ok.}
{173}{}{Puisqu'il en est ainsi, je te demanderai de sortir d'ici. Immédiatement !}
{174}{}{Ok.}
{175}{}{Un esclavagiste ! Barre-toi d'ici sinon je remplace ton tatouage par une balle !}
{176}{}{Certainement.}
{177}{}{Essaie !}
{178}{}{On a des agents et des sympathisants dans plusieurs villes du Nord. On fait passer le message et on attaque les esclavagistes à chaque occasion.}
{179}{}{Re-bonjour. T'as changé d'avis... Tu te joins à nous ?}
{180}{}{Ca ne fait rien.}
{181}{}{Ca ne t'appartient pas. Alors tu dégages ou je vais me mettre en rage !}
{182}{}{Je ne sais pas ce que t'as fait à Gond, mais tu vas payer !}
