{100}{}{Tu vois un squatteur.}
{101}{}{Tu vois Bill, le squatteur.}
{102}{}{Tu vois un homme d'âge moyen portant des vêtements usés.}
{103}{}{Je regrette mais je n'ai pas le temps de discuter avec toi.}
{104}{}{Pas parler ? Pourquoi ?}
{105}{}{Ok, wavy.}
{106}{}{Bon, alors à une prochaine.}
{107}{}{Attends une minute. Pourquoi ne veux-tu pas me parler ?}
{108}{}{Nous formons une communauté très fermée et nous ne voulons pas de problèmes ou de contacts avec l'extérieur. Laisse-nous s'il te plaît.}
{109}{}{Ok.}
{110}{}{Bonjour... Et au revoir.}
{111}{}{Merci pour tout ce que tu as fait. Je m'excuse pour la froideur.}
{112}{}{Va te faire voir, enflure !}
