{100}{}{Tu vois un squatteur.}
{101}{}{Tu vois Bill, le squatteur.}
{102}{}{Tu vois un homme d'âge moyen portant des vêtements usés.}
{103}{}{Je regrette mais je n'ai pas le temps de discuter avec toi.}
{104}{}{Pas parler ? Pourquoi ?}
{105}{}{Ok, wavy.}
{106}{}{Bon, alors à une prochaine.}
{107}{}{Attends une minute. Pourquoi ne veux-tu pas me parler ?}
{108}{}{We're a very private community here and we don't want any trouble or interference from outside sources. Please just leave us be.}
{109}{}{Ok.}
{110}{}{Bonjour... Et au revoir.}
{111}{}{Merci pour tout ce que tu as fait. Je m'excuse pour la froideur.}
{112}{}{Va te faire voir, enflure !}
