{100}{}{Tu vois un vieux bonhomme maigrelet. Il porte un stylo sur l'oreille et des lunettes en équilibre sur son nez.}
{101}{}{Voici Vortis, le propriétaire de cet enclos à esclaves.}
{102}{}{Il doit lui rester 3 dents. Ses doigts et son tricot sont tachés d'encre bleue. Un tatouage d'esclavagiste un peu passé est dessiné sur son front.}
{103}{}{Alors, que veux-tu ?}
{104}{}{Bienvenue chez Vortis. Que puis-je faire pour toi ?}
{105}{}{Tu commences à m'ennuyer.}
{106}{}{Je suis ici chez moi et je dirige un commerce honnête et légitime, même si l'on raconte des choses en RNC. Puisque la RNC ne tolère pas les esclaves dans ses murs, je m'occupe d'eux pour tous ceux qui y font commerce.}
{107}{}{T'es stupide ou quoi ? Ici, c'est un enclos à esclaves. J'ai une licence.}
{108}{}{}
{109}{}{J'ai juste quelques questions à te poser.}
{110}{}{Je cherche du travail.}
{111}{}{Hein ?}
{112}{}{Pas cabinets ? Moi partir.}
{113}{}{On y fait quoi ici ?}
{114}{}{Rien. Mauvais endroit.}
{115}{}{Oh, regardez-moi cette sainte-nitouche ! Hé, les gars, sortez-moi cette mauvaise copie d'hypocrisie chrétienne !}
{116}{}{Merde.}
{117}{}{Eh bien ?}
{118}{}{Je cherche l'Abri 13.}
{119}{}{As-tu un J.E.K ?}
{120}{}{Que pouvez-vous me dire à propos de cette ville ?}
{121}{}{Sale esclavagiste ! Je devrais te tuer !}
{122}{}{J'ai entendu parler des membres du Commando de la Nouvelle Californie. Ils t'ont cherché des noises ?}
{123}{}{Je peux jeter un coup d'oeil ?}
{124}{}{Du travail ? Eh bien, il y a peut-être quelque chose. T'as déjà entendu parler du Commando de la Nouvelle Californie ?}
{125}{}{Oui.}
{126}{}{Non.}
{127}{}{Va-t'faire. Les gars, sortez-moi cette saloperie.}
{128}{}{Va t'faire !}
{129}{}{L'Abri 13 ! Arrête ton char ! Ce truc c'est carrément un mythe ! Abri 13, mon cul !}
{130}{}{Une autre question...}
{131}{}{Bon, merci quand même.}
{132}{}{Un quoi ? Je sais pas ce que c'est mais j'en ai pas.}
{133}{}{Une autre question...}
{134}{}{Bon, merci quand même.}
{135}{}{En RNC, il n'y a que des antialcooliques et des marchands. Ils ont quelque chose contre les esclavagistes et l'esclavage. Merde, c'est un commerce comme un autre.}
{136}{}{Une autre question...}
{137}{}{Merci, faut que je parte.}
{138}{}{On t'a raconté n'importe quoi. J'ai des problèmes avec personne, et encore moins avec le Commando. Je suis en règle, j'ai un casier vierge.}
{139}{}{Une autre question...}
{140}{}{Si tu le dis. Je m'en vais.}
{141}{}{Ouais, j'ai peut-être une dent contre le Commando. Tu cherches du travail ?}
{142}{}{Oui.}
{143}{}{Non.}
{144}{}{Non, tu peux pas y fourrer ton nez. C'est pas un musée ici !}
{145}{}{Une autre question...}
{146}{}{T'es trop susceptible pour moi. Je m'en vais.}
{147}{}{Alors, tu dois savoir que certaines personnes les voient comme une source potentielle de problèmes. Il serait très utile d'avoir une carte des lieux sûrs au Nord, New Reno, Klamath... Je suis prêt à te payer, disons $500 pour un tel service. Tu crois que tu peux te procurer ça pour moi ?}
{148}{}{Certainement.}
{149}{}{Je ne pense pas.}
{150}{}{Ecoute-moi bien. Ce Commando s'est mis dans la tête d'abolir l'esclavage et les esclavagistes, par la force. Il crée des ennuis à d'honnêtes travailleurs.}
{151}{}{Le Commando travaille en secret, surtout dans le Nord.}
{152}{}{Tu veux un dessin ou quoi ? Il décime les esclavagistes, chasse nos cheptels et les traîne clandestinement au Sud de la RNC où l'esclavage est illégal. Alors, ça t'intéresse ?}
{153}{}{Il n'y a pas de *et après* ! Tu veux le boulot ou non ?}
{154}{}{Ah...}
{155}{}{Alors, que veux-tu que je fasse ?}
{156}{}{Bon. Quand tu auras la carte, reviens me trouver ici.}
{157}{}{Où puis-je la trouver cette carte ?}
{158}{}{D'accord, j'ai d'autres questions à te poser.}
{159}{}{Ca marche. A plus tard.}
{160}{}{Qu'est-ce que j'en sais ? Si je le savais, je t'enverrais pas la chercher ! Ecoute, il devrait y avoir une cellule en ville. Trouve-les et vois ce que tu peux faire.}
{161}{}{Encore quelques questions.}
{162}{}{D'accord. Je reviendrai.}
{163}{}{Te voilà de retour. As-tu trouvé la carte ?}
{164}{}{Oui.}
{165}{}{Non.}
{166}{}{Tu n'as pas terminé le premier boulot que je t'ai confié.}
{167}{}{Ah ouais, j'avais oublié.}
{168}{}{Pas depuis que tu as fait ton boulot. Merci.}
{169}{}{Encore une ou deux questions.}
{170}{}{Pas de problème. Salut.}
{171}{}{Joli travail. Maintenant, fais-toi oublier, au cas où le Commando pigerait le coup.}
{172}{}{Ce fût un plaisir.}
{173}{}{Eh ben, reste pas là, imbécile ! Ca va paraître louche !}
{174}{}{D'accord, j'ai pigé.}
{175}{}{Gardes ! Sortez-moi ce parasite !}
{176}{}{Si tu rentres là-dedans, j't'éclate la tête. Tu piges ?}
{177}{}{Il est tard et nous sommes fermés. Revenez dans la matinée.}
