{100}{}{Tu vois un homme grand et costaud, c'est Cassidy. S'il a remarqué que tu le regardais, il n'en donne aucun signe.}
{101}{}{Tu vois Cassidy.}
{102}{}{Tu vois un homme grand et costaud, c'est Cassidy. Il te fait un signe de tête.}
{103}{Cas0103}{Well, now. I ain't seen you around before, stranger. Name's Cassidy. I run this place. What can I do for you?}
{104}{Cas0104}{Well now, if it ain't the mysterious stranger. What can I do for you today?}
{105}{}{Ben, hein ??}
{106}{}{Dégage !}
{107}{}{Je recherche l'Abri.}
{108}{}{T'as déjà cherché à te tirer d'ici ?}
{109}{}{Qu'avez-vous à la pression ?}
{110}{}{Il se passe des trucs intéressants dans le coin ?}
{111}{}{Rien pour aujourd'hui, merci.}
{112}{Cas0112}{Hit on the head a little too often, eh? Sorry, I don't speak imbecile.}
{113}{}{Baie-cil ?}
{114}{Cas0114}{Vault? Only Vault I know of is the one inside the city. Big friggin' hole... you can't miss it, trust me.}
{115}{}{Que boit-on chez toi ?}
{116}{}{Il se passe des trucs intéressants dans le coin ?}
{117}{}{Merci. Salut.}
{118}{Cas0118}{Beer for $20, shot of whiskey for $30. Nothing special. Why, you want something?}
{119}{}{Je recherche l'Abri.}
{120}{}{Je prendrais une bière.}
{121}{}{Sers-moi un whisky.}
{122}{}{Il se passe des trucs intéressants dans le coin ?}
{123}{}{Pas vraiment. Merci quand même.}
{124}{Cas0124}{"Interesting?" Heh. Friend, Vault City ain't an "interesting" place... unless the guards get bored, then you
 better take cover. Why you asking? You looking for something in this sinkhole?}
{125}{}{Que boit-on chez toi ?}
{126}{}{Je recherche l'Abri.}
{127}{}{Ca peut pas être si nul que ça ici.}
{128}{}{Pas vraiment. Merci quand même.}
{129}{Cas0129}{Here you go. Drink up. It might help you forget where you are.}
{130}{}{Ca peut pas être si nul que ça.}
{131}{}{Merci pour le verre. Faut que j'y aille.}
{132}{Cas0132}{Oh, really? Well, hell then, I must be mistaken, considering YOU'RE the authority and all. Guess you must have been napping during the raid last week?}
{133}{}{Le pillage ?}
{134}{Cas0134}{Aw, yeah, a beautiful sight it was. A guard patrol broke in here looking for "illegal substances." They busted down the door, busted up my stock, then busted up a few of my customers, too.}
{135}{}{Que s'est-il passé, ensuite ?}
{136}{}{Je regrette, vraiment. On discutera plus tard.}
{137}{Cas0137}{After they hauled away this one guy, Joshua, for resisting arrest, they fined my ass for finding - get this - REAL whiskey on the premises. Nevermind that I got a permit from Stark three months before. Bastards.}
{138}{}{Ouaah. Tu déconnes ?}
{139}{}{Je regrette, vraiment. On discutera plus tard.}
{140}{Cas0140}{It gets better. Now I'm in debt to the guards for the fine, an' I had to buy a new case of alcohol from a merchant at triple my standard rate. I'm expecting the guards to come knocking again soon, just to bust my chops. }
{141}{}{Ca se passe comment, en général ?}
{142}{}{J'espère que ça va s'améliorer pour toi, à l'avenir. Salut.}
{143}{Cas0143}{Even the good days ain't worth a damn. The Citizens don't drink much, so I'm stuck here pouring drinks for merchants. The next cheap sonuvabitch who haggles for a drink is going to be wearing his ass as a hat.}
{144}{}{Que fais-tu là, si ça t'énerve tellement ?}
{145}{}{Je regrette vraiment. Je cherche un Abri. Tu peux m'aider à le trouver ?}
{146}{}{Je regrette vraiment. J'espère que ça va s'arranger.}
{147}{Cas0147}{I have a bad heart. Need cardio booster shots to keep it beating. This city's the only place to get real medical care, so I thought I'd settle here, try and make a living.}
{148}{}{On dirait que t'en as marre d'être ici.}
{149}{}{Je vois. Dis, je cherche un Abri. Peux-tu m'aider à le trouver ?}
{150}{}{J'espère que ça va s'arranger pour toi. Salut.}
{151}{Cas0151}{Makes me want to close up shop and let this City rot. Screw 'em all.}
{152}{}{Pourquoi tu ne te fais pas la malle ?}
{153}{}{Je regrette, vraiment. J'espère que ça va s'arranger pour toi.}
{154}{Cas0154}{Go into the wastes by myself? Ha! I'm sick of this place, but I ain't stupid.}
{155}{}{J'y retourne bientôt. Pourquoi ne pas te joindre à moi ?}
{156}{}{Bon, alors bonne chance.}
{157}{Cas0157}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{158}{Cas0158}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{159}{Cas0159}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{160}{Cas0160}{Naw... you look like you got enough of a crowd already.}
{161}{}{Ok, alors bonne chance et au revoir.}
{162}{}{Ok, alors laisse tomber. T'as qu'à continuer à tenir ton bistrot dans ce patelin de merde.}
{163}{}{Tant pis. Tu sais pas ce que tu perds.}
{164}{Cas0164}{Heh. You serious?}
{165}{}{Ouais. Pourquoi, ça t'étonne ? On dirait que tu sais éviter les coups dans une bagarre.}
{166}{}{A bien y réfléchir, c'est plutôt dangereux là-bas, surtout quand on a des problèmes cardiaques. Tu ferais mieux de rester ici.}
{167}{Cas0167}{All right, count me in.}
{168}{}{On y va.}
{169}{}{}
{170}{}{}
{171}{Cas0171}{What's up? You got that "I need to tell you something you might not like" look again.}
{172}{Cas0172}{Yeah?}
{173}{Cas0173}{What's up? You got that "I'm pulling rank" look again.}
{174}{}{Je voulais te poser quelques questions...}
{175}{}{On dirait que tu as subi des dégâts. Prends des Stimpaks et soigne-toi.}
{176}{}{Cassidy, il faut que tu attendes ici jusqu'à mon retour.}
{177}{}{Pose ton arme.}
{178}{}{Reste près de moi.}
{179}{}{Ne t'en vas pas trop loin.}
{180}{}{On devrait se disperser un peu.}
{181}{}{Allez viens, Cassidy. Faut y aller.}
{182}{}{Rien, tant pis.}
{261}{Cas0261}{You want me to put a bullet in Myron's head, is that it? It'd be no trouble. Just give the word.}
{262}{Cas0262}{What's on your mind?}
{263}{}{Pourquoi tu veux te faire Myron ?}
{264}{}{Quelles armes sais-tu utiliser ?}
{265}{}{En fait, il y a autre chose que je voulais que tu fasses...}
{266}{}{En fait, il y a un truc que je voulais que tu fasses...}
{267}{}{Tant pis. Allez, on bouge.}
{268}{}{Non, touche pas à Myron. Pas aujourd'hui, en tout cas. Reste à ton poste.}
{269}{Cas0269}{Well, shotguns and rifles, mostly... just personal preference. I ain't a bad shot with pistols, neither.}
{270}{}{Rien d'autre ?}
{271}{}{D'accord. J'avais encore une ou deux questions...}
{272}{}{Parfait. J'voulais juste vérifier.}
{273}{Cas0273}{If you ever need to learn somebody some manners up close and personal, slip me some brass knuckles, and I can tapdance on their face with my fists.}
{274}{}{Super. Autre chose ?}
{275}{}{D'accord. J'avais encore une ou deux questions...}
{276}{}{Parfait. J'voulais juste vérifier.}
{277}{Cas0277}{Uh, well... just between you and me, I can also use a spear pretty good. Me and my buddies used to hunt radscorpions with spears way back when... fact I'm alive and they ain't might tell you something.}
{278}{}{Je n'ai rien contre la lance.}
{279}{}{D'accord. J'avais encore une ou deux questions...}
{280}{}{Parfait. J'voulais juste vérifier.}
{281}{Cas0281}{Says you. Just don't be calling me no tribal, and we'll get along just fine.}
{282}{Cas0282}{Don't want people mistaking me for ol' Bone-nose over there. Heh-heh. I ain't never seen no tribal do something as dumb as jam a bone in his nose.}
{283}{Cas0283}{Of course there isn't. Spear's a fine weapon. Lots of tribal friends of mine use 'em.}
{284}{}{Tu savais que j'étais un *tribal* ?}
{285}{}{Hum. Ecoute, j'avais une ou deux autres questions...}
{286}{}{Très bien. Merci de m'avoir mis au parfum.}
{287}{Cas0287}{Aw, don't be playing with ol' Cassidy now. You ain't no tribal.}
{288}{}{Si, c'est moi.}
{289}{}{Peu importe. Ecoute, j'avais encore une ou deux questions...}
{290}{}{Laisse tomber. Je veux pas parler de ça avec toi maintenant.}
{291}{Cas0291}{Uh, well... damn it all, you can have my apology right here and now. I didn't mean any offense.}
{292}{}{Bien sûr que non. Ecoute, j'avais encore une ou deux questions...}
{293}{}{Laisse tomber. On y va.}
{294}{Cas0294}{Well, now, before you go, I got a question for you. What are we doing out here? We seem to be running all over the place looking for something. Have we got some sort of plan?}
{295}{}{On cherche un J.E.K, un Jardin d'Eden en Kit. Mon village en a besoin pour récupérer les récoltes.}
{296}{}{On va à l'Abri, et puis on rapporte le J.E.K dans mon village.}
{297}{}{Les gens de mon village ont été kidnappés. J'essaie de savoir ce qu'ils sont devenus.}
{298}{Cas0298}{Them things come in kits now, huh? Man, the good book don't mention that, does it? Well, all right then. Let's get hunting.}
{299}{Cas0299}{Huh. All right then, just checking.}
{300}{Cas0300}{I wouldn't mind plugging a few holes in some kidnappers. A little frontier justice never hurt anyone... well, at least not me.}
{301}{}{Très bien. Allons-y.}
{302}{Cas0302}{The things that little cuss says ain't fit for decent ears.}
{303}{Cas0303}{Especially a woman's.}
{304}{}{Ben, Cassidy, je savais pas que ça te perturbait. J'en ai le coeur qui bat la chamade.}
{305}{}{Alors ? Que dis-tu ?}
{306}{}{Tu sais, Cassidy, tu jures pas mal, toi aussi.}
{307}{}{Tu m'en diras tant. Allez, on y va.}
{308}{Cas0308}{Yeah, but when I do it, it's got style. He's just a little trash mouth.}
{309}{Cas0309}{And I don't like the way he looks at you, neither.}
{310}{}{Ben, Cassidy, je savais pas que ça te perturbait. J'en ai le coeur qui bat la chamade.}
{311}{}{Alors ? Que dis-tu ?}
{312}{}{Tu m'en diras tant. Allez, on y va.}
{313}{Cas0313}{Now hold on, I didn't mean it like that.}
{314}{Cas0314}{All I'm saying is that bona fide little asshole's gonna get his number clocked one day when it's just me and him and a hole in the desert.}
{315}{}{Ouais, la vie donne parfois de rudes leçons. J'avais encore une ou deux questions à te poser...}
{316}{}{De toute façon, il finira bien par mordre la poussière un jour ou l'autre. A ta place, je me ferais pas de souci.}
{317}{}{Allez, du calme, Cassidy. Laisse Myron tranquille.}
{318}{}{Je déteste cet endroit.}
{319}{}{J'avais espéré qu'on se tirerait définitivement de cet endroit.}
{320}{}{Une ville de radins...}
{321}{}{Cet endroit a l'air pire que la Cité de l'Abri.}
{322}{}{J'ai bien fait de vérifier mes armes avant de venir ici.}
{323}{}{Si je casse ma pipe, m'enterre pas ici.}
{324}{}{Fais gaffe à toi dans le coin. Les locaux sont pas franchement accueillants.}
{325}{}{Héé. J'pensais pas que je verrais San Francisco un jour.}
{326}{}{J'pensais pas que tu garderais un vieux croûton comme moi aussi longtemps. Allez, on fait le boulot et on rentre.}
{327}{}{Redding est une ville minière. Des mines d'or, essentiellement. Il y a beaucoup de caravanes qui sont parties d'ici pour la Cité de l'Abri.}
{328}{}{Collines Brisées est une ville minière... des mines d'uranium, surtout. Ca peut-être assez chaud, alors fais gaffe à toi.}
{329}{}{J'ai du poison qui se balade dans le corps. T'aurais pas un antidote ?}
{330}{}{Je rayonne comme une enseigne lumineuse, là. T'aurais pas des médicaments anti-radiations ?}
{331}{}{Ca me fait un mal de chien, là. T'aurais pas des Stimpaks ?}
{332}{}{Toi, tu te tiens à carreau, Myron. Je t'ai à l'oeil.}
{333}{}{A la moindre incartade, Myron, je te casse en deux !}
{334}{}{Bon sang, Lenny, tu as besoin d'un bon bain. Ou d'un désinfectant.}
{335}{}{Ma petite Goule, tu ferais bien de te tenir à distance. Pouuaaah, ce que tu peux chlinguer.}
{336}{}{Ce chien-là a le plus sale air que j'aie vu de ma vie.}
{337}{}{Du calme, le clebs. Cassidy est ton copain, d'accord ?}
{338}{}{J'me demande ce que ça bouffe un cyberchien. Des humains, sûrement...}
{339}{}{Si ce cyberchien commence à me faire du rentre-dedans, je l'flingue !}
{340}{}{Aaaah. Ca me fait carrément plaisir qu'ils aient eu le temps de faire des millions de trucs comme ça avant que la bombe nous tombe dessus !}
{341}{}{Merci.}
{342}{}{J'espère que ces Stimpaks, ça va pas m'attaquer le coeur...}
{343}{}{Qu'est-ce qu -- ?! Non, mon coeur ! Je... <Aarrrkkk>}
{344}{}{Je m'excuse, j'admirais juste la vue.}
{345}{}{Je vais rester là, alors.}
{346}{}{J'regrette. Je voulais pas te bloquer le chemin.}
{347}{}{Aaaah. Ca, c'est exactement ce qu'il me fallait. Merci, c'est bien aimable.}
{348}{}{<Hic> Hé-hé. Rien de tel qu'une bonne vieille eau de feu pour faire circuler le sang.}
{349}{}{Merci. Allez, prends-en donc un coup, toi aussi.}
{350}{}{Voilà l'Abri. C'est un sacré gros truc, hein ?}
{351}{}{Tu veux encore que je vienne avec toi ?}
{352}{}{On peut y aller quand tu veux.}
{353}{}{Tu n'as pas besoin de mon aide, c'est sûr ?}
{354}{}{Ca me démange de partir.}
{355}{}{Pour une clope, sûr que j'irais...}
{356}{}{Mon vieux m'a donné le nom d'un personnage de bande dessinée d'avant-guerre. C'était un sacré fils de pute, lui aussi !}
{357}{}{Ca fait du bien de repartir en voyage. La vie dans la Cité de l'Abri, ça commençait à me filer un ulcère !}
{358}{}{J'espère que mon coeur va pas faire le mariole quand on sera en voyage...}
{359}{}{Je serais pas contre un petit coup à boire.}
{360}{}{Je ferais bien de revérifier mon équipement.}
{361}{}{Saloperie d'arthrite...}
{362}{}{Si j'avais vingt ans de moins, j'irais vers l'Est et j'explorerais le Midwest. C'trop tard, maintenant.}
{363}{}{Il paraît qu'il y avait des tornades de plusieurs kilomètres d'envergure dans le Midwest. Maintenant, c'est plus qu'un vieux nuage de poussière radioactive.}
{364}{}{J'me demande si le Texas a survécu à la guerre...}
{365}{}{Merci. Je... ouaoh. Maintenant, je vois tout trouble.}
{366}{}{Il paraît que ce truc donne des hallucinations... ouaoh ! Mais, d'où ils sortent, tous ces serpents ?!! Allez, crevez, bande de salopards !}
{367}{}{A chaque fois que je prends ce truc, j'ai des flashbacks.}
{368}{}{Rien de tel qu'un petit remède tribal à base d'eau...}
{369}{}{Autant dire que je suis bon pour des béquilles et une chaise roulante, là.}
{370}{}{Cassidy meurt d'une crise cardiaque.}
{371}{}{Tu as réussi à convaincre Cassidy de se joindre à ton groupe.}
{372}{}{Laisse moi juste prendre une pilule pour mon coeur avant...}
{1000}{Cas1000}{Well... all right, then. I'll wait here 'til you get back. }
{1100}{Cas1100}{Sure. Can't promise I won't pull it out again if there's trouble, though.}
{1200}{Cas1200}{All right, I'll stick close to you then. You must be expecting trouble.}
{1300}{Cas1300}{All right, I'll keep some distance. Get a better vantage point that way.}
{1400}{Cas1400}{All right, I'll be watching your back. You need me, holler, and I'll come running.}
{2000}{Cas2000}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{2100}{Cas2100}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{2200}{Cas2200}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{2300}{Cas2300}{Naw... you look like you got enough of a crowd already.}
{2400}{Cas2400}{All right, then.}
{2999}{}{Bon. Attention, alors.}
{3000}{}{Allez, on y va.}
{3100}{}{Ok, laisse tomber, pôv'tache.}
{3200}{}{Tant pis. Tu sais pas ce que tu perds.}
{4100}{Cas4100}{Okay, everything's stitched up. I'm good to go.}
{4200}{Cas4200}{Okay, pretty much everything is patched up.}
{4300}{Cas4300}{That pretty much did it, but I could use a couple more stims.}
{4400}{Cas4400}{I used what I could, but I'm still pretty messed up. If you got any more stims to spare, I could sure use 'em. I can still walk, though.}
{9999}{}{Je voulais te poser quelques questions...}
{10001}{}{Prends encore des Stimpaks et soigne-toi.}
{10002}{}{Cassidy, il faut que tu attendes ici jusqu'à mon retour.}
{10003}{}{Pose ton arme.}
{10004}{}{Reste près de moi.}
{10005}{}{Ne t'en vas pas trop loin.}
{10006}{}{On devrait se disperser un peu.}
{10007}{}{Bon, alors, on y va.}
{10100}{}{Allez viens, Cassidy. Faut y aller.}
{20000}{Cas20000}{All right, I'm listening.}
{20001}{Cas20001}{My gear? What about it?}
{20002}{Cas20002}{No problem. Too hot for that kinda gear, anyway. Makes me sweat like a New Reno whore.}
{20003}{}{Essayons une autre formation.}
{20004}{}{Il faut que je te parle de ton équipement.}
{20005}{}{Laisse tomber. On va garder notre formation actuelle.}
{20006}{}{Tant pis. Je n'ai pas besoin de savoir quoi que ce soit sur ton équipement.}
{20007}{}{Je voudrais que tu enlèves l'armure que tu portes.}
