{100}{}{Tu vois un homme sale mais qui semble costaud.}
{101}{}{Tu vois Connar.}
{102}{}{Hey you! What are you doing!}
{103}{}{Reste où tu es pour le moment, voyageur. Que fais-tu ici ?}
{104}{}{I'm killing off the monsters here.}
{105}{}{Pourquoi, qu'est-ce que ça te fait ?}
{106}{}{Pourquoi tu brailles ?!}
{107}{}{I bet those bastards at Vault City sent you. Well you best be off, and leave everything else
 alive.}
{108}{}{Eh bien, c'est un peu tard pour ça.}
{109}{}{Pourquoi ?}
{110}{}{Désolé, j'ai un boulot à faire.}
{111}{}{Those creatures are the only thing that are stopping Vault City from making us their so-called
 servants.}
{112}{}{Well they're paying me to get rid of the monsters, and that's what I'm going to do.}
{113}{}{Ils ne m'ont pas dit cela.}
{114}{}{Ils m'ont payé pour me débarrasser de ces choses, et le boulot est terminé.}
{115}{}{Imbécile ! Pourquoi t'as fait ça, bon sang !}
{116}{}{J'avais besoin du fric.}
{117}{}{Ils viendront s'emparer de nous si tu fais cela, tu sais.}
{118}{}{C'est pas mon problème.}
{119}{}{Eh bien j'espère que le remord t'étouffera. Ils seront bientôt là pour nous.}
{120}{}{Je ne savais pas que c'était la raison pour laquelle ils voulaient que le boulot soit fait.}
{121}{}{Ouais, eh bien, je ne ferai plus jamais affaire avec des ordures dans ton genre à l'avenir.}
{122}{}{Eh bien, nous ne pouvons te laisser faire ça.}
{123}{}{Tu dois faire ce que t'as à faire.}
{124}{}{Tu les as crus simplement sur parole ? Tu as beaucoup à apprendre de ce monde, mon ami.}
{125}{}{Y a-t-il quelque chose que je puisse faire pour aider ?}
{126}{}{Les gars de la Cité de l'Abri ne sont pas les plus valeureux. Tu leur montres le début d'une résistance et ils détalent comme des lapins. Si nous avions quelques armes, je pense qu'on pourrait les repousser.}
{127}{}{What sort of guns?}
{128}{}{Eh bien, je suis bon avec un fusil de chasse, et nous avons quelques personnes ici qui savent utiliser un fusil. Je pense que trois d'entre eux feraient l'affaire.}
{129}{}{Je vais voir ce que je peux faire.}
{130}{}{On ne veut pas de toi ici. Pars maintenant.}
{131}{}{J'ai changé d'avis. Que puis-je faire pour vous aider ?}
{132}{}{Ouais, eh bien tu ne resteras pas longtemps ici de toute façon.}
{133}{}{Comme je m'en moque !}
{134}{}{Tu es de retour ! As-tu les armes pour nous ?}
{135}{}{De quoi avais-tu besoin déjà ?}
{136}{}{Ouais, les voilà.}
{137}{}{We need three rifles and a shotgun. The sooner you can get them to us, the better.}
{138}{}{Ok.}
{139}{}{With these, we'll be able to make something of this place over the next months. If you ever need
 a place to rest, you will always be welcome here.}
{140}{}{Pas d'quoi.}
{141}{}{Welcome back. Things are going well. We're going to work on expanding the Village.}
{142}{}{Rebonjour ! Les choses se sont bien passées, comme tu vois. Regarde donc autour de toi si tu as le temps.}
{143}{}{On est toujours en travaux. On espère étendre encore les murs le mois prochain.}
{144}{}{Greetings! The village has expanded again as we have hoped. You are welcome as always.}
{145}{}{We have nothing to fear from Vault City any longer, and will be able to live here in peace.
 Thank you again, wanderer.}
{146}{}{Essaie simplement de ne rien tuer dans les alentours, crétin.}
