{100}{}{You see a villager.}
{101}{}{You see a villager.}
{102}{}{Bonjour.}
{103}{}{Au revoir.}
{104}{}{Welcome to our Village.}
{105}{}{Les monstres nous protègent.}
{106}{}{Hurry back.}
{107}{}{We'll need those guns soon.}
{108}{}{Bonjour.}
{109}{}{Leave now!}
{110}{}{Go back to where you came from!}
{111}{}{Va au diable !}
{112}{}{We're safe now.}
{113}{}{Merci.}
{114}{}{Bless you, wanderer.}
