{100}{}{Tu vois un petit homme à l'air jovial.}
{101}{}{Tu vois Harry le Ravi, le propriétaire du magasin.}
{102}{}{Euh, salut... que puis-je faire pour toi ?}
{103}{}{Je cherche à faire du business. Puis-je voir ce que tu as en stock ?}
{104}{}{Elle est toujours à vendre cette charrue ?}
{105}{}{Moi acheter.}
{106}{}{Rien pour aujourd'hui, merci.}
{107}{}{Je regrette, je peux pas t'aider mon gars.}
{108}{}{Ben, oui, toujours. Je la laisse partir pour... disons, huit cents.}
{109}{}{Je t'en donne six cents.}
{110}{}{Ok, ça marche. Je la prends.}
{111}{}{Hein, huit cents, tu dis ? Bon, je reviendrai... avec l'argent.}
{112}{}{Laisse tomber. Les Smith peuvent crever.}
{113}{}{Elle est à toi. [Il empoche l'argent.] Tu la prends tout de suite, ou il faut la livrer quelque part ?}
{114}{}{Dépose-la chez les Smith.}
{115}{}{Je regrette l'ami, ça va te coûter huit cents.}
{119}{}{Tu as besoin d'argent pour me payer, mon ami.}
{120}{}{Je reviens avec le pognon.}
{121}{}{Y'a pas de problème. Je vais la faire livrer tout de suite.}
{122}{}{Tu voulais te servir, hein ? Saleté de voleur... Gardes ! Gardes !}
