{100}{}{Tu vois un homme très âgé avec une lueur de folie dans l'oeil.}
{101}{}{Tu vois le Vieux Joe, l'idiot savant local.}
{102}{}{Salut ! Ca fait longtemps que je t'avais pas vu !}
{103}{}{Je te connais ??}
{104}{}{Ah, c'est sûr, ça fait un bail ! Alors, qu'est-ce que tu deviens ?}
{105}{}{Hé bien, ça faisait longtemps ! Qu'est-ce tu faisais ?}
{106}{}{Des choses et d'autres... Tu me connais d'où ?}
{107}{}{Ecoute, vieil homme, je ne sais absolument pas qui tu es.}
{108}{}{C'est ça... J'ai atterri ici, dans cette ville-abandonnée-de-dieu, comme ils disent... C'est plus comme dans le bon vieux temps. Non monsieur !}
{109}{}{Ouaip, le bon vieux temps... Tu te souviens de cette fois où...}
{110}{}{C'est plus pareil, c'est sûr. Qu'avait-on fait, déjà ?}
{111}{}{Tu te souviens pas de moi, c'est ça ? Ouais... T'as l'air plus jeune...}
{112}{}{Qu'essaies-tu de me dire ?}
{113}{}{Tu m'as l'air si familier... Ca doit être mes vieux yeux fatigués. Bonne journée à toi...}
{114}{}{Euh, ouais... Salut...}
{115}{}{Ouais, pour sûr on lui a fait sa fête, au Maître ! Mais après, j'étais recherché, et j'ai dû bouger, changer de nom...}
{116}{}{J'ai vécu dans un petit village...}
{117}{}{Bon, surveille tes arrières par ici... Les choses sont devenues bizarres ces derniers temps...}
{118}{}{D'accord, merci.}
{119}{}{Ouais, j'ai recherché ton Abri un certain temps, mais en vain... Alors, tu dois avoir des tas d'histoires à raconter à ton vieil ami Ian, non ?}
{120}{}{Ian ?}
{121}{}{Ouais, Ian. Tu te souviens pas de moi ? Ca remonte à loin, maintenant... Tu te souviendrais pas de ton meilleur pote ? Bon, à part pour les tirs dans le dos, je m'en excuse aujourd'hui encore.}
{122}{}{Désolé, mais tu dois penser que je suis l'habitant de l'Abri. C'est lui qui a fondé mon village.}
{123}{}{Je commence à comprendre... C'est bien de savoir que mon vieil ami a fait de bonnes choses. Oh, le vieux Ian a un conseil pour toi... Fais gaffe dans les parages. Les choses dégénèrent en ce moment...}
{124}{}{Que se passe-t-il ici ?}
{125}{}{Eh bien, les citoyens de l'Abri tiennent à leurs communautés *d'origine*, et ils ne s'intéressent pas du tout à des gens comme toi et moi... Tiens, prends ça, on sait jamais. Pour te protéger si les choses tournent mal... Il ne faudrait pas qu'on te voie avec ce vieux fou de Ian... Tu devrais partir.}
{126}{}{Merci pour ton aide.}
{127}{}{J'ai besoin de repos...}
{128}{}{Si familier...}
{129}{}{Laisse-moi, maintenant...}
{130}{}{Tu ferais mieux d'y aller maintenant...}
{131}{}{Ils vont se poser des questions s'ils nous voient encore parler...}
{132}{}{Allez, vas-y. Rends mon vieux pote fier.}
