{100}{}{Bạn thấy Lucas.}
{101}{}{Lucas là chiến binh trưởng trong bộ tộc.}
{102}{}{Cậu đây rồi, Cứu tinh. Hừm! Nhiệm vụ của cậu đến đâu rồi?}
{103}{}{Vẫn ổn.}
{104}{}{Không ổn lắm.}
{105}{}{Ớ?!}
{106}{}{Tôi phải đi tiếp đây.}
{107}{}{Có thể cậu cần sự giúp đỡ của một chiến binh.}
{108}{}{Chắc chắn rồi. Anh giúp gì được tôi?}
{109}{}{Không cần. Tôi vẫn ổn.}
{110}{}{Trả lời hay lắm, đồ đần. Giờ thì câm miệng lại trong lúc tập.}
{111}{}{Ừ được.}
{112}{}{Ta biết cách chiến đấu bằng chân và tay. Cậu xem có học được không?}
{113}{}{Anh có thể dạy tôi cái gì?}
{114}{}{Cầu cho gió luôn theo lưng cậu, Cứu tinh.}
{115}{}{Tạm biệt.}
{116}{}{Hừm -- ở một ngày cạnh ta và ta sẽ dạy cách đấm đau hơn.}
{117}{}{Được. Bắt đầu đi.}
{118}{}{Xin lỗi, không có thời gian.}
{119}{}{Cậu đã biết tất cả những gì ta có thể dạy, Cứu tinh. Chúc hành trình may mắn.}
{120}{}{Ồ, okay.}
{121}{}{Hà! Cứu tinh, cậu không đủ khéo léo để học thứ gì của ta cả.}
{122}{}{Ồ, okay.}
{123}{}{Cậu đánh đấm chậm đến mức bài tập của ta cũng không giúp được, Cứu tinh ạ.}
{124}{}{Ồ, okay.}
{125}{}{Cậu cần phải học thêm về cách chiến đấu trước khi ta có thể giúp, em giai ạ.}
{126}{}{Ồ, okay.}
{127}{}{Ta có thể dạy cậu đá mạnh hơn. Sẽ mất cả một ngày đấy.}
{128}{}{Okay.}
{129}{}{Ta có thể dạy cậu đủ để chiến đấu tốt hơn. Sẽ mất một ngày đấy.}
{130}{}{Okay.}
{131}{}{Cậu đã học tốt lắm, Cứu tinh. Cầu cho gió luôn theo lưng cậu.}
{132}{}{Cám ơn đã giúp đỡ.}
{133}{}{Ta đã dạy tất cả những gì ta biết, Cứu tinh. Chúc hành trình may mắn.}
