{100}{}{Bạn thấy Jordan, đang múa ngọn giáo như mọi khi.}
{101}{}{Bạn thấy Jordan, đang múa ngọn giáo như mọi khi.}
{102}{}{Chúc may mắn! Ngôi làng trông chờ vào cậu.}
{103}{}{Cứu tinh, nhìn cách cậu múa giáo thế thì chả mấy mà cậu làm mồi
cho gecko. Tôi có thể chỉ cậu vài đường.}
{104}{}{Được thôi.}
{105}{}{Không, cám ơn.}
{106}{}{Sẽ mất một thời gian đấy.}
{107}{}{Cậu học nhanh đấy -- có vẻ như cậu đã học hết những gì tôi
có thể dạy rồi.}
{108}{}{Cám ơn Jordan. Anh đã giúp tôi rất nhiều đấy.}
