{100}{}{Bạn thấy Jordan, đang múa ngọn giáo như mọi khi.}
{101}{}{Bạn thấy Jordan, đang múa ngọn giáo như mọi khi.}
{102}{}{Chúc may mắn! Tôi phải đi tập tiếp đây.}
{103}{}{Chào Cứu tinh. Tôi thấy là cậu cần luyện tập thêm một chút. Tôi giúp được không?}
{104}{}{Được thôi.}
{105}{}{Không, cám ơn.}
{106}{}{Sẽ mất một thời gian đấy.}
{107}{}{Vậy là cậu đã học hết những chiêu giáo mà tôi có thể dạy rồi.}
{108}{}{Cám ơn Jordan. Anh đã giúp tôi rất nhiều đấy.}
