{100}{}{Bạn thấy Klint, một người đồng tộc.}
{101}{}{Bạn thấy Klint.}
{102}{}{Bạn thấy một cậu trai trẻ có cơ bắp cuồn cuộn với dáng vẻ rất tự tin.}
{103}{}{Xin chào, }
{104}{}{. Anh chưa hoàn thành thử thách của Trưởng lão nên không qua đây được.}
{105}{}{Ừ...}
{106}{}{Tôi cần quay lại làng.}
{107}{}{Tôi có vài câu hỏi.}
{108}{}{Được rồi, tôi đi làm thử thách đây.}
{109}{}{(thở dài)}
{110}{}{. Vào đền. Làm thử thách. Không quay lại cho đến khi xong. Tuân lời Trưởng lão. Đi đi!}
{111}{}{Ngộ đi.}
{112}{}{Thứ lỗi cho tôi, }
{113}{}{, nhưng tôi không để anh qua được. Nếu anh muốn trở lại làng, hãy đi theo đường hoàn thành thử thách trước mặt.}
{114}{}{Hiểu rồi. Chắc là tôi đi đây.}
{115}{}{Tôi hỏi vài câu được không?}
{116}{}{Tôi có thể đá đít cậu và đi khỏi đây.}
{117}{}{Thứ lỗi cho tôi, nhưng tôi không trả lời được. Hãy thực hiện thử thách do Trưởng lão đặt ra và chứng tỏ anh xứng đáng dẫn đầu bộ tộc.}
{118}{}{Được rồi.}
{119}{}{Cần có hai người mới có thể bê được cây cột này. Một mình anh chắc chắn không được đâu. Tôi sẽ không giúp anh cho đến khi anh vượt qua thử thách của Trưởng lão.}
{120}{}{Ừ hứ. Tôi hiểu rồi.}
{121}{}{Xin chào, Cứu tinh! Rất vui được gặp anh. Tôi giúp gì được đây?}
{122}{}{Ngộ chào. Thế thôi.}
{123}{}{Chào hỏi thôi. Tôi sắp lên đường làm nhiệm vụ rồi.}
{124}{}{Cầu cho linh hồn tiên tổ phù hộ anh, Cứu tinh. Tôi chúc anh hành trình tốt đẹp.}
