{100}{}{Bạn thấy Morlis, một người dì của bạn -- người chẳng bao giờ ưu bạn.}
{101}{}{Sao mày lại đi làm phiền tao hả cháu? Mày không thấy tao đang bận à?}
{102}{}{Ừm, okay. Xin lỗi.}
{103}{}{Gì đấy? Mày biết là tao bận lắm mà!}
{104}{}{Ừm, Mynoc nói là...}
{105}{}{Mynoc nói gì? Nói nhanh lên nào, nhóc con!}
{106}{}{Là, ừm, dì có đá mài.}
{107}{}{Tao có đây. Muốn một ít chứ gì?}
{108}{}{Ờ, vâng.}
{109}{}{Rồi... Tao muốn ba bọc bột chữa thương. Thời điểm khó khăn sắp tới
và tao cần phải chuẩn bị. Hãy mang chúng đến đây và mày sẽ có đá mài.
Giờ thì đi kiếm đi!}
{110}{}{Vâng, thưa dì!}
{111}{}{Đừng có làm mất thời gian của tao. Mày có bột chưa?}
{112}{}{Vâng, ở đây ạ.}
{113}{}{Ừm, chắc là chưa ạ.}
{114}{}{Đá mài đây. Giờ thì biến đi! Tao không có thì giờ bốc phét đâu.}
{115}{}{Cám ơn, Dì Morlis.}
{116}{}{Lại làm phiền tao à, đồ cháu vô dụng! Làm sao mà mày lại trở thành
Cứu tinh được nhỉ?}
{117}{}{Vâng, Dì Morlis.}
{118}{}{Ờ, Dì Morlis, cháu có ba bọc ở đây.}
{150}{}{Dì Morlis, cháu đang thực hiện nhiệm vụ đầy hiểm nguy để cứu ngôi làng.
Cháu sẽ có cơ hội thành công cao hơn nếu giữ lại bột chữa thương và dì đưa
đá mài cho cháu. Dì thấy có đúng không?}
{151}{}{Mày đang nghĩ gì thế hả nhóc? Đấy không phải là cách mà Cứu tinh làm. Giờ thì biến đi cho khuất mắt tao!}
{152}{}{Nếu cục đá mài quan trọng đến mức mày sẵn sàng làm nhục cái tên Cứu tinh thì đây. Cầm lấy và biến đi
cho khuất mắt tao.}
{153}{}{Vâng, Dì Morlis.}
{154}{}{Ờ... Ồ, được thôi. Đá mày đây. Ta chúc con hành trình bình an.}
{155}{}{Không hề. Giờ thì đừng có lèo nhèo mất thời gian và biến khỏi đây đi!}
{156}{}{Vâng, Dì Morlis.}
{200}{}{Vậy là mày đã quay trở lại. Mày tìm được số 13 thần thánh chưa?}
{201}{}{Chưa, Dì Morlis, cháu...}
{202}{}{Thế thì cút khỏi đây và đi tìm đi! Mọi người đang trông đợi ở mày đấy!}
{203}{}{Vâng, Dì Morlis.}
{204}{}{Ài, mày lại vác mặt về đây à. Có phải mày lại không thực hiện được nhiệm vụ thêm lần nữa không?}
{205}{}{Vâng, Dì Morlis, nhưng...}
{206}{}{Vậy thì cút khỏi đây và đừng có về chừng nào làm xong! Sao lại mất thời gian quay về khi mà có thể tiếp tục đi tìm chứ!?}
{207}{}{Vâng, Dì Morlis.}
{208}{}{Mày đang đứng ở đây chứng tỏ là mày đã làm xong nhiệm vụ rồi. Mày sẽ không phí phạm thời gian quý báu để trở về tay không chứ hả?}
{209}{}{Vâng, Dì Morlis. Ý cháu là, không, Dì Morlis, Ừ, cháu phải đi đây, Dì Morlis.}
{210}{}{Vậy là, nhóc lại một lần nữa đứng trước mặt ta. Lại về tay trắng à?}
{211}{}{Vâng, Dì Morlis.}
{212}{}{Nghe này, }
{213}{}{. Người thì chết dần, bò cũng chết dần, cây trồng thì héo úa. Mọi người hoặc là chết vì đói, hoặc bệnh, hoặc cả hai. Thời gian sắp hết rồi. Nếu mày không sớm tìm thấy GECK thì chúng ta chết hết. Mày có hiểu không?}
{214}{}{Vâng, Dì Morlis.}
{215}{}{Vậy thì cút khỏi đây và đi tìm GECK đi! Mọi người đang trông chờ vào mày đấy!}
{216}{}{Vâng, Dì Morlis.}
{300}{}{Chà, có vẻ như tao để đá mài chỗ khác rồi. Ồ ít nhất thì tao cũng có bột rồi. Giờ thì biến đi! Tao không có thời gian để tán nhảm.}
{301}{}{Sao mày lại đi làm phiền tao hả cháu? Mày không thấy tao đang bận à?}
{302}{}{Chà, tìm mãi không thấy đá mài. Chắc chắn là mày lấy trộm lúc tao không canh chừng rồi. Lần trước cũng thế. Giờ thì cút đi! Tao không có thời gian để tán nhảm đâu.}
{303}{}{Chà... Ồ, ta xin lỗi nhưng ta không tìm thấy đá mài. Ta chúc con hành trình bình an, nhóc ạ.}
{304}{}{Tao đã đưa đá mài cho mày rồi, đồ ngu. Giờ thì đừng có làm mất thời gian của tao và biến đi!}
{305}{}{Tao đã đưa đá mài cho mày rồi, đồ ngu. Ồ, ít nhất thì tao cũng có bột rồi. Giờ thì biến đi! Tao không có thời gian để tán nhảm đâu.}
