{100}{}{B?n th?y ngư?i gác c?u.}
{101}{}{B?n th?y Mynoc, ngư?i gác c?u.}
{150}{}{Đ?ng trư?c b?n là m?t chi?n binh cao to c?a làng,
n?m trong tay m?t ng?n giáo.}
{151}{}{[NÓI CHUY?N]}
{152}{}{Chào, C?u tinh. Đi t?m GECK h??}
{153}{}{Đúng v?y.}
{154}{}{Đúng v?y. Nhưng trư?c khi đi, tôi mu?n h?i vài câu.}
{155}{}{Chưa. Tôi đang đi v?ng quanh xem xét thêm
m?t lát đ?.}
{156}{}{?, c?u các th?n phù h? cho c?u.}
{157}{}{Cám ơn, t?m bi?t.}
{158}{}{Mu?n bi?t g? nào?}
{159}{}{Anh có th? nói cho tôi bi?t v? ngư?i trao đ?i hàng hóa
v?i làng chúng ta không?}
{160}{}{Anh có bi?t g? v? th? này mà tôi l?y đư?c t? h?m
không?}
{161}{}{Không, không có g?.}
{162}{}{Đư?c r?i, nhưng đ?ng có m?t nhi?u th?i gian quá. Không có
GECK, chúng ta tiêu tùng đ?y.}
{163}{}{Tôi bi?t, đ?ng lo -- M?i chuy?n đ?u trong t?m ki?m soát.}
{164}{}{T?i sao?}
{165}{}{Tôi ph?i đi đây. T?m bi?t.}
{166}{}{Đám thương gia ?y h?? H? đ?n t? Klamath kho?ng 2 tháng m?t l?n. L?n
ti?p theo c?n hơn m?t tháng n?a cơ, nhưng đi đ?n Klamath th? ch? m?t vài
ngày v? phía Đông.}
{167}{}{Cám ơn. T?m bi?t.}
{168}{}{Anh có bi?t g? v? th? này mà tôi l?y đư?c t? h?m
th?n không?}
{169}{}{Trông gi?ng m?t b?u đ?ng nư?c b?ng kim lo?i. Có th?
h?m g?i nó đ?n đây như m?t đi?m báo.}
{170}{}{Anh có th? cho tôi bi?t ai đ? mang th? này đ?n làng chúng ta không?}
{171}{}{Cám ơn. Tôi ph?i đi đây. T?m bi?t.}
{172}{}{Hi v?ng là v?y.}
{173}{}{C?u mà t? tin quá s? khi?n t?t c? chúng ta ph?i tr? giá đ?y! T?m bi?t!}
{174}{}{T?m bi?t.}
{175}{}{T?i sao à? Nh?n quanh xem -- Ngôi làng đang ch?t. Vư?n tư?c héo úa,
ngày nào c?ng có tr? con và ngư?i già n?m xu?ng. C?u ph?i mang Đ?a đàng v?
trư?c khi quá mu?n!}
{176}{}{R?i tôi s? lo chuy?n đó. T?m bi?t.}
{177}{}{Tôi là C?u tinh -- Tôi "ph?i" làm theo ? tôi.
T?m bi?t.}
{178}{}{Tôi không nh? tên, nhưng l?o ta già v?i to m?m l?m -- nói to ch?
gi? ? g? c? -- nhưng l?o ta bi?t nhi?u l?m. L?o đ?n t? Klamath, v? phía Đông
như tôi v?a nói.}
{179}{}{Cám ơn, t?m bi?t.}
{180}{}{Sao c?u v?n c?n ? đây? C?u ph?i đi t?m GECK. C?u ? đây
ch?ng có ích g? đâu.}
{181}{}{Anh ch? c?n lo gác c?u thôi, anh b?n ?. Tôi
có th? t? lo thân đư?c.}
{182}{}{Tôi chu?n b? đi đây. T?m bi?t, anh b?n.}
{183}{}{Tôi không nói chuy?n v?i anh n?a đâu, đ? l?n khó b?o!}
{184}{}{Tôi mu?n h?i thêm câu n?a.}
{185}{}{Nhanh th?t đ?y! C?u đ? t?m th?y Vault 13 th?n thánh chưa?}
{186}{}{Đúng v?y.}
{187}{}{Chưa.}
{188}{}{Th?y r?i? Tuy?t quá! C?u có mang GECK v?
không?}
{189}{}{Không.}
{190}{}{Chưa. Tôi v?n chưa nói chuy?n v?i đám ngư?i trong h?m.}
{191}{}{Tôi th?y r?ng đ?y không ph?i là vi?c c?a anh, b?n tôi ?.}
{192}{}{Chưa ư? C?u tinh, ba ngư?i già đ? ch?t k? t? lúc c?u r?i đi. C?u không
đư?c l?ng phí thêm th?i gian n?a.}
{193}{}{Tôi s? t?m th?y, đ?ng lo.}
{194}{}{Tôi th?y m?t m?i v?i m?y l?i càu nhàu c?a anh l?m r?i.}
{195}{}{?, th? th? sao c?u l?i đi nói chuy?n v?i tôi? Đ?n nói chuy?n v?i h? và l?y GECK đi.}
{196}{}{Tôi s? làm mà -- th?t chó s? có m?m tôm, b?n tôi ơi.}
{197}{}{Tôi th?y m?t m?i v?i m?y l?i càu nhàu c?a anh l?m r?i.}
{198}{}{Có tin g? v? GECK chưa, C?u tinh?}
{199}{}{Tôi đ? t?m th?y căn h?m!}
{200}{}{Tôi chưa t?m th?y Vault 13.}
{201}{}{?, nh?n này, C?u tinh v? r?i.}
{202}{}{Chào.}
{203}{}{Câm m?m đi.}
{204}{}{Tôi h?i m?t câu đư?c không?}
{205}{}{Không, tôi không có r?nh.}
{206}{}{Sao c?ng đư?c. T?m bi?t.}
{207}{}{? đư?c r?i. G?p l?i sau.}
{208}{}{Đi ch?t đi.}
{209}{}{Chào th?ng th?n! Th?y c?u ch?? Qua c?u, c?n th?n đ?y.
C?u đáng s? l?m. Mày không mu?n ng? ch?. Okay?}
{210}{}{?... H??}
{211}{}{Kh?n n?n! Mày đ? khi?n c? làng th?t v?ng!}
{212}{}{Mày đ? ph?n b?i chúng ta. Gi? th? ch?t đi!}
{213}{}{Mày đ? ph?n b?i chính nh?ng ngư?i đ?ng t?c.}
{214}{}{T?i sao mày l?i làm th??}
{215}{}{Trư?ng l?o đ? nh?m. Mày đúng là ác qu?.}
{300}{}{Cha tôi d?y tôi cách t?o ra lư?i dao s?c hơn. Ki?m cho tôi m?t c?c đá mài và
tôi s? s?a giáo cho c?u. Nó s? có ích cho c?u ngoài hoang đ?a đ?y.}
{301}{}{Tôi có th? ki?m đá mài ? đâu đư?c?}
{302}{}{Có ngư?i b?o D? Morlis đang gi? m?t c?c. M? ta khó tính như ma
nên tôi ch?c ch?ng ai bu?n h?i đâu. D? nhiên là m? già ?y s? mu?n đ?i
l?y th? g? đó.}
{303}{}{Cám ơn. T?m bi?t.}
{304}{}{C?u đ? nói chuy?n v?i bà d? v? c?c đá mài chưa?}
{305}{}{R?i, tôi có đá ? đây.}
{306}{}{Chưa.}
{307}{}{C?c này t?t đ?y. Đưa giáo cho tôi.}
{308}{}{Đây.}
{309}{}{Ch?c là tôi không có r?i.}
{310}{}{Gi? th? đ?t viên đá vào đây...}
{311}{}{C?u tinh mà không có giáo á? Đây, c?u l?y m?t cái c?a tôi mà dùng.
Gi? th? b?t đ?u vào vi?c nào...}
{312}{}{Giáo m?i c?a c?u đây.}
{313}{}{Cám ơn b?n tôi -- Th? này r?t có ích đ?y.}
{314}{}{?, nhưng tôi th?y giáo c?a anh là l?. Trông nó có v? hơi
khác.}
{400}{}{Chào m?ng v? đ?n nhà, C?u tinh! C?u t?m th?y căn h?m chưa? C?u có mang GECK v? không?}
{401}{}{Ng? không th?y chưa.}
{402}{}{Chưa, tôi chưa t?m th?y.}
{403}{}{Tôi không r?nh đ? tr? l?i câu h?i c?a anh. Chào.}
{404}{}{M?i th? không ?n r?i, C?u tinh à. Cơn h?n hán càng ngày càng t?, cây tr?ng c?a chúng ta
s?p héo h?t r?i. Chúng ta đang c? hái h?t nh?ng g? c?n sót l?i đ? tích tr? lương th?c.}
{405}{}{Sao không trao đ?i v?i làng khác?}
{406}{}{Ng? làm t?t nh?t ng? làm. Ng? t?m GECK. Ng? v?.}
{407}{}{T?i sao chúng ta không trao đ?i v?i các ngôi làng khác đ? l?y lương th?c c?n thi?t?}
{408}{}{Tôi đang c? h?t s?c đây. Tôi s? tr? l?i khi nào t?m th?y GECK.}
{409}{}{We are a simple people and have little to offer in trade. The few towns that we have
 contacted while you were away have shown no interest in helping us.}
{410}{}{Me see.}
{411}{}{I see.}
{412}{}{You are our only hope, Chosen One. Please do not fail us!}
{413}{}{It is good to see you, Chosen One. How fares your quest?}
{414}{}{Me still look.}
{415}{}{I'm still looking.}
{416}{}{I don't want to talk about it.}
{417}{}{You must hurry. Things are getting worse here at home. Soon there will be little food and
 the Elder speaks of rationing what we have. I fear for the future of Arroyo.}
{418}{}{Chosen One! Please tell me that you have completed your quest. Our village is dying, and so
 are our people. }
{419}{}{No, me still look.}
{420}{}{No, I'm still looking.}
{421}{}{How are things?}
{422}{}{I am sorry, Chosen One, but I am beginning to question my faith in you. The very lives of
 our people are in your hands. Please find the holy Thirteen and return to us with the GECK!}
{423}{}{Our crops fail, the brahmin die, everyone goes hungry now. The cries of the children at night
 allow no one any sleep. We are becoming a desperate people.}
{424}{}{Me continue look.}
{425}{}{I'll do what I can.}
{426}{}{Once again you return to us, Chosen One. Not empty-handed, I hope?}
{427}{}{Me sorry, no find GECK yet.}
{428}{}{I'm sorry, I still haven't found the GECK.}
{429}{}{I've had enough of this.}
{430}{}{People are dying here while you stroll about the lands. Perhaps you should be searching
 elsewhere instead of returning here.}
{500}{}{Have you talked to the Elder yet?}
{1000}{}{Elder}
{1001}{}{Founder}
{1002}{}{Vault Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Chosen One}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Healing Powder}
{1010}{}{Bridge}
{1011}{}{Mynoc}
{1100}{}{The Elder is your mother and our leader.}
{1101}{}{Our great ancestor who gave us knowledge.}
{1102}{}{The first to fight and win over chaos.}
{1103}{}{That would be our beautiful village.}
{1104}{}{That's a trading outpost a few days east of here.}
{1105}{}{The Vault is heaven.}
{1106}{}{You are the Chosen One.}
{1107}{}{He heals us with his herbs and magic. He is in the
 northern part of our village.}
{1108}{}{He heals us with his herbs and magic. He is in the
 north part of our village.}
{1109}{}{It is a magic powder which will heal you, but will
 make you sleepy.}
{1110}{}{The Great Bridge exits our village in the south.}
{1111}{}{That would be me.}
