{100}{}{B?n th?y ngư?i gác c?u.}
{101}{}{B?n th?y Mynoc, ngư?i gác c?u.}
{150}{}{Đ?ng trư?c b?n là m?t chi?n binh cao to c?a làng,
n?m trong tay m?t ng?n giáo.}
{151}{}{[NÓI CHUY?N]}
{152}{}{Chào, C?u tinh. Đi t?m GECK h??}
{153}{}{Đúng v?y.}
{154}{}{Đúng v?y. Nhưng trư?c khi đi, tôi mu?n h?i vài câu.}
{155}{}{Chưa. Tôi đang đi v?ng quanh xem xét thêm
m?t lát đ?.}
{156}{}{?, c?u các th?n phù h? cho c?u.}
{157}{}{Cám ơn, t?m bi?t.}
{158}{}{Mu?n bi?t g? nào?}
{159}{}{Anh có th? nói cho tôi bi?t v? ngư?i trao đ?i hàng hóa
v?i làng chúng ta không?}
{160}{}{Anh có bi?t g? v? th? này mà tôi l?y đư?c t? h?m
không?}
{161}{}{Không, không có g?.}
{162}{}{Đư?c r?i, nhưng đ?ng có m?t nhi?u th?i gian quá. Không có
GECK, chúng ta tiêu tùng đ?y.}
{163}{}{Tôi bi?t, đ?ng lo -- M?i chuy?n đ?u trong t?m ki?m soát.}
{164}{}{T?i sao?}
{165}{}{Tôi ph?i đi đây. T?m bi?t.}
{166}{}{Đám thương gia ?y h?? H? đ?n t? Klamath kho?ng 2 tháng m?t l?n. L?n
ti?p theo c?n hơn m?t tháng n?a cơ, nhưng đi đ?n Klamath th? ch? m?t vài
ngày v? phía Đông.}
{167}{}{Cám ơn. T?m bi?t.}
{168}{}{Anh có bi?t g? v? th? này mà tôi l?y đư?c t? h?m
th?n không?}
{169}{}{Trông gi?ng m?t b?u đ?ng nư?c b?ng kim lo?i. Có th?
h?m g?i nó đ?n đây như m?t đi?m báo.}
{170}{}{Anh có th? cho tôi bi?t ai đ? mang th? này đ?n làng chúng ta không?}
{171}{}{Cám ơn. Tôi ph?i đi đây. T?m bi?t.}
{172}{}{Hi v?ng là v?y.}
{173}{}{C?u mà t? tin quá s? khi?n t?t c? chúng ta ph?i tr? giá đ?y! T?m bi?t!}
{174}{}{T?m bi?t.}
{175}{}{T?i sao à? Nh?n quanh xem -- Ngôi làng đang ch?t. Vư?n tư?c héo úa,
ngày nào c?ng có tr? con và ngư?i già n?m xu?ng. C?u ph?i mang Đ?a đàng v?
trư?c khi quá mu?n!}
{176}{}{R?i tôi s? lo chuy?n đó. T?m bi?t.}
{177}{}{Tôi là C?u tinh -- Tôi "ph?i" làm theo ? tôi.
T?m bi?t.}
{178}{}{Tôi không nh? tên, nhưng l?o ta già v?i to m?m l?m -- nói to ch?
gi? ? g? c? -- nhưng l?o ta bi?t nhi?u l?m. L?o đ?n t? Klamath, v? phía Đông
như tôi v?a nói.}
{179}{}{Cám ơn, t?m bi?t.}
{180}{}{Sao c?u v?n c?n ? đây? C?u ph?i đi t?m GECK. C?u ? đây
ch?ng có ích g? đâu.}
{181}{}{This bridge is all you need to worry about,
 friend. I can take care of myself.}
{182}{}{I was just heading out. Goodbye, my friend.}
{183}{}{I will speak to you no longer, insubordinate pig!}
{184}{}{I would like to ask you another question.}
{185}{}{That was quick! Have you found the holy Vault 13?}
{186}{}{Đúng v?y.}
{187}{}{No, not yet.}
{188}{}{You have? Wonderful! Did you bring back the
 GECK?}
{189}{}{No.}
{190}{}{No. I haven't spoken to the people of the vault yet.}
{191}{}{I don't believe that's any business of yours, my friend.}
{192}{}{No? Chosen One, three old ones have died since you left. You must
 not waste any more time.}
{193}{}{I'll find it, don't worry.}
{194}{}{I'm getting sick of your constant nagging.}
{195}{}{Well, why are you talking to me? Talk to them, and get the GECK.}
{196}{}{I will -- all in good time, my friend.}
{197}{}{I'm getting sick of your constant nagging.}
{198}{}{What news of the GECK, Chosen One?}
{199}{}{I have found the vault!}
{200}{}{I have not been able to find Vault 13.}
{201}{}{Well, look, it's the Chosen One.}
{202}{}{Chào.}
{203}{}{Shut up.}
{204}{}{Can I ask you a question?}
{205}{}{No, I've no time for you.}
{206}{}{Whatever. Good bye.}
{207}{}{Oh well. See you around.}
{208}{}{Go die.}
{209}{}{Greetings, dull one! See bridge? You cross, you be careful.
 Bridge dangerous. You not want to fall. Okay?}
{210}{}{Umm... Hunh?}
{211}{}{Wretch! You have failed the village!}
{212}{}{You betray us. For that you'll die!}
{213}{}{You are a traitor to your own people.}
{214}{}{Why do you do this?}
{215}{}{The Elder was wrong. You are evil.}
{300}{}{My father taught me how to make stronger blades than most. Get me a piece
 of flint and I'll fix your spear, too. You'll need it in the wilderness.}
{301}{}{Where would I get some of this flint?}
{302}{}{They say your Aunt Morlis has been hoarding a piece. She's so
 ill-tempered I don't think anyone's asked her. Of course, the witch will want
 something in return.}
{303}{}{Thanks. Goodbye.}
{304}{}{Did you talk your aunt out of her flint?}
{305}{}{Yes, I have some right here.}
{306}{}{Not yet.}
{307}{}{It's a good piece. Give me your spear.}
{308}{}{Đây.}
{309}{}{I guess I don't have one.}
{310}{}{Now, you put the pieces like so...}
{311}{}{The Chosen One without a spear? Well, you'll have to take one of
 mine. Now, let's get to work...}
{312}{}{Here is your new spear.}
{313}{}{Thank you, my friend -- this will help a lot.}
{314}{}{Yes, but I was wondering about your spear. It looks a little
 different.}
{400}{}{Welcome home, Chosen One! Did you find the vault? Have you returned with the GECK?}
{401}{}{Me not find yet.}
{402}{}{No, I haven't found it yet.}
{403}{}{I'm not in the mood for your questions. Goodbye.}
{404}{}{Things are not going well, Chosen One. The drought is getting worse and our crops are
 sure to fail. We are trying to salvage what we can to build up our food reserves.}
{405}{}{Why no trade with other villages?}
{406}{}{Me doing best me can. Me find GECK. Me return.}
{407}{}{Why can't we trade with other villages for the food we need? }
{408}{}{I'm doing my best. When I find the GECK I'll return with it.}
{409}{}{We are a simple people and have little to offer in trade. The few towns that we have
 contacted while you were away have shown no interest in helping us.}
{410}{}{Me see.}
{411}{}{I see.}
{412}{}{You are our only hope, Chosen One. Please do not fail us!}
{413}{}{It is good to see you, Chosen One. How fares your quest?}
{414}{}{Me still look.}
{415}{}{I'm still looking.}
{416}{}{I don't want to talk about it.}
{417}{}{You must hurry. Things are getting worse here at home. Soon there will be little food and
 the Elder speaks of rationing what we have. I fear for the future of Arroyo.}
{418}{}{Chosen One! Please tell me that you have completed your quest. Our village is dying, and so
 are our people. }
{419}{}{No, me still look.}
{420}{}{No, I'm still looking.}
{421}{}{How are things?}
{422}{}{I am sorry, Chosen One, but I am beginning to question my faith in you. The very lives of
 our people are in your hands. Please find the holy Thirteen and return to us with the GECK!}
{423}{}{Our crops fail, the brahmin die, everyone goes hungry now. The cries of the children at night
 allow no one any sleep. We are becoming a desperate people.}
{424}{}{Me continue look.}
{425}{}{I'll do what I can.}
{426}{}{Once again you return to us, Chosen One. Not empty-handed, I hope?}
{427}{}{Me sorry, no find GECK yet.}
{428}{}{I'm sorry, I still haven't found the GECK.}
{429}{}{I've had enough of this.}
{430}{}{People are dying here while you stroll about the lands. Perhaps you should be searching
 elsewhere instead of returning here.}
{500}{}{Have you talked to the Elder yet?}
{1000}{}{Elder}
{1001}{}{Founder}
{1002}{}{Vault Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Chosen One}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Healing Powder}
{1010}{}{Bridge}
{1011}{}{Mynoc}
{1100}{}{The Elder is your mother and our leader.}
{1101}{}{Our great ancestor who gave us knowledge.}
{1102}{}{The first to fight and win over chaos.}
{1103}{}{That would be our beautiful village.}
{1104}{}{That's a trading outpost a few days east of here.}
{1105}{}{The Vault is heaven.}
{1106}{}{You are the Chosen One.}
{1107}{}{He heals us with his herbs and magic. He is in the
 northern part of our village.}
{1108}{}{He heals us with his herbs and magic. He is in the
 north part of our village.}
{1109}{}{It is a magic powder which will heal you, but will
 make you sleepy.}
{1110}{}{The Great Bridge exits our village in the south.}
{1111}{}{That would be me.}
