{100}{}{Bạn thấy cậu em họ Nagor. Bạn không thấy con chó Smoke của cậu ta đâu cả.}
{101}{}{Bạn biết Nagor từ hồi còn bé tí, và luôn giúp đỡ cậu ta khi nào có thể.}
{102}{}{Anh họ, rất vui được gặp anh! Em cần anh giúp.}
{103}{}{Thứ lỗi nhưng tôi không có thời gian.}
{104}{}{Cậu cần giúp gì?}
{105}{}{Vậy thì em sẽ tự đi đến đất hoang!}
{106}{}{Chờ đã... cậu cần giúp gì thế?}
{107}{}{Cứ đi đi.}
{108}{}{Smoke đã chạy vào khu săn và vẫn chưa quay về. Giờ thì Morlis không để em đi tìm.
Mẹ bảo chỗ đó quá nguy hiểm và nó chỉ là chó thôi, nhưng em định có thế nào em 
cũng phải đi. Nhưng giờ có anh rồi. Anh có thể đi giúp và em sẽ không gặp
rắc rối nữa.}
{109}{}{Hẳn rồi. Nhưng khu săn ở chỗ nào?}
{110}{}{Được rồi. Để tôi đi tìm nó giờ đây.}
{111}{}{Quên đi, tôi đâu có rảnh.}
{112}{}{Anh làm sao thế, bị ăn đá chọi vào đầu à? Khu săn nằm cách xa lều của
Hakunin, phía Bắc của làng.}
{113}{}{Tôi sẽ sớm đưa nó quay về.}
{114}{}{Anh đã tìm thấy Smoke chưa?}
{115}{}{Vẫn chưa. Cậu nói khu săn ở đâu thế nhỉ?}
{116}{}{Chưa.}
{117}{}{Anh đã tìm thấy Smoke chưa?}
{118}{}{Chưa. Tôi sẽ sớm quay lại thôi.}
{119}{}{Tôi rất tiếc nhưng nó chết rồi.}
{120}{}{Anh chỉ nói vậy vì anh không muốn đi tìm thì có! Em đéo sợ Morlis nói gì,
em phải đi tìm nó đây.}
{121}{}{Nagor, nếu có chuyện gì với cậu thì sao? Dì Morlis sẽ chỉ còn lại một mình và sẽ
buồn lắm đấy. Cậu không muốn làm dì buồn chứ, đúng không?}
{122}{}{Cứ đi đi.}
{123}{}{Thì... không, em không muốn làm vây. Được rồi, em sẽ không đi, nhưng như vậy không công bằng!}
{124}{}{Smoke sẽ ổn thôi. Tạm biệt.}
{125}{}{Anh tìm thấy Smoke rồi! Cám ơn! Smoke, đồ chó hư!}
{126}{}{Không có gì. Tạm biệt.}
{127}{}{Cám ơn lần nữa. Hi vọng anh có một chuyến đi thật vui!}
{128}{}{Em nhớ Smoke quá. Sao anh lại không cứu nó chứ? Anh là Cứu tinh cơ mà.}
{129}{}{Tôi bận, đồ đần. Đi chỗ khác chơi đi.}
{130}{}{Tôi đi.}
{131}{}{Tôi sẽ đi tìm Smoke.}
{200}{}{Xin chào anh họ... ừ, ý em là Cứu tinh. Em hi vọng là anh đã tìm thấy GECK. Em nghe
mọi người nói nhiều về thời kì khó khăn sắp đến rồi.}
{202}{}{Ngộ vẫn tìm, Nagor.}
{203}{}{Tôi vẫn đang đi tìm, em họ ạ.}
{204}{}{Chào mừng trở về, anh họ. Mọi thứ ở nhà đang hơi loạn. Anh đã tìm thấy số 13 thần thánh và
GECK chưa?}
{206}{}{Ngộ không tìm. Xin lỗi.}
{207}{}{Tôi xin lỗi, Nagor. Tôi vẫn đang tìm.}
{208}{}{Xin chào, anh họ. Em chắc anh cũng thấy là mọi thứ nát như tương rồi. Làm ơn đi tìm
GECK đi. Chúng ta nguy cấp lắm rồi!}
{210}{}{Chào, em họ.}
{212}{}{Cậu nghe không như mọi khi.}
{213}{}{Cậu nghe có vẻ không giống như mọi khi.}
{214}{}{Em xin lỗi, anh họ. Mọi thứ đang ngày càng tệ hơn sau khi anh đi. Mọi người thi nhau bị bệnh,
đàn bò thì chết và... em... con chó Smoke của em đã chết - Morlis đã nấu nó lên. Em nhớ nó quá. Xin lỗi,
nhưng em không thể nói chuyện thêm nữa...}
{215}{}{Em xin lỗi, anh họ. Mọi thứ đang ngày càng tệ hơn sau khi anh đi. Mọi người thi nhau bị bệnh,
đàn bò thì chết và... em... con chó Smoke của em đã chết. Em nhớ nó quá. Xin lỗi, nhưng em
không thể nói chuyện thêm nữa...}
{300}{}{Bạn thấy Nagor.}
