{100}{}{Bạn thấy một cái cây của linh hồn hắc ám.}
{101}{}{Những cái cây này không chỉ gây hại cho khu vườn. Chúng còn có khả năng tấn công con người
và các động vật khác.}
{102}{}{Những cái cây của linh hồn hắc ám là một biến chủng dị biệt. Thật khó để coi đây là kết quả
của sự biến dị tự nhiên.}
{103}{}{Bạn không nhận thấy có điều gì đặc biệt về những cái cây này – trừ việc chúng tấn công con người.}
{150}{}{Bạn đã loại trừ hết cây linh hồn hắc ám khỏi khu vườn.}
