{100}{}{Bạn thấy một người đàn ông trong làng.}
{101}{}{Bạn thấy một phụ nữ trong làng.}
{150}{}{Một thành viên tốt bụng trong làng.}
{151}{}{[NÓI CHUYỆN]}
{152}{}{Xin chào! Tôi nghe nói anh là Cứu tinh. Có lẽ ngôi làng sắp được cứu rồi.}
{153}{}{Có thể nói cho tôi chỗ tìm bột chữa thương được không?}
{154}{}{Nói cho tôi biết về thương gia hay đến đây mua bán được không?}
{155}{}{Nói chuyện vui lắm, nhưng tôi phải đi đây.}
{156}{}{Các thần phù hộ cho hành trình của anh.}
{157}{}{Tôi có câu hỏi này.}
{158}{}{Chào nhé, bạn tôi.}
{159}{}{Đến gặp Hakunin ở góc phía Bắc ngôi làng. Ông ta sẽ giúp.}
{160}{}{Cám ơn. Tạm biệt.}
{161}{}{Ồ, tôi không trực tiếp mua bán với ông ta. Hãy đến nói chuyện với Mynoc, người gác
cây cầu lớn. Anh ta lo việc đón khách.}
{162}{}{Cám ơn. Tạm biệt.}
{163}{}{Cây cầu lớn ở chỗ nào nhỉ?}
{164}{}{Tôi hỏi thêm câu nữa nhé.}
{165}{}{Đùa hay đấy, Cứu tinh! Ai cũng biết mà. Lối đó -- về phía Nam.}
{166}{}{Cám ơn. Tạm biệt.}
{167}{}{Tôi hỏi thêm câu nữa nhé.}
{168}{}{Dĩ nhiên rồi, gì thế?}
{169}{}{Tôi có thể tìm thảo dược ở đâu được?}
{170}{}{Nói cho tôi biết về thương gia hay đến đây mua bán được không?}
{171}{}{Không có gì.}
{172}{}{Ơi các thần linh -- cầu cho linh hồn của Người sáng lập dẫn đường cho anh. Nếu quả thực
anh là Cứu tinh thì chúng ta sẽ cần được phù hộ như vậy.}
{173}{}{Ù gà.}
{174}{}{Lên đường an toàn.}
{175}{}{????}
{176}{}{Chúng ta tiêu rồi! Anh đã thất bại.}
{177}{}{Anh không thể tiếp tục thế này được.}
{180}{}{Mày đã phản bội chính những người đồng tộc.}
{181}{}{Tại sao mày lại làm thế?}
{182}{}{Mày là ác quỷ. Cứu tinh là ác quỷ!}
{183}{}{Họ đến từ phía Đông, nhưng đồ của họ chán lắm.}
{184}{}{Tôi có thể tìm thảo dược ở đâu được?}
{185}{}{Cám ơn. Tạm biệt.}
{186}{}{Tôi hỏi thêm câu nữa nhé.}
{300}{}{Chào, Cứu tinh. Rất vui được gặp lại. Cầu cho nhiệm vụ thần thành luôn suôn sẻ. Tôi có thể giúp gì không?}
{301}{}{Cứu tinh, mọi người đang chết dần. Cần phải đi tìm GECK thần thánh nhanh lên. Tôi có thể giúp gì để giúp đỡ nhiệm vụ thần thánh đây?}
{302}{}{Chúng ta sắp hết thời gian rồi, Cứu tinh ơi. Làm ơn sớm hoàn thành nhiệm vụ thần thánh đi. Chúng ta không chờ được lâu hơn nữa đâu. Nếu tôi có thể giúp gì để cứu chúng ta thì hãy nói đi.}
{303}{}{Cứu tinh, ngôi làng sắp tiêu rồi... Anh là niềm hi vọng duy nhất của chúng ta. Liệu
tôi có thể giúp gì để cứu chúng ta không?}
{1000}{}{Trưởng lão}
{1001}{}{Người mở làng}
{1002}{}{Cụ tổ từ Vault}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Cứu tinh}
{1007}{}{Thầy cúng}
{1008}{}{Hakunin}
{1009}{}{Bột chữa thương}
{1010}{}{Cầu}
{1011}{}{Mynoc}
{1100}{}{Trưởng lão là mẹ cậu đồng thời là trưởng làng.}
{1101}{}{Cụ tổ vĩ đại đã truyền kiến thức cho chúng ta.}
{1102}{}{Người đầu tiên chiến đấu và chiến thắng cái xấu.}
{1103}{}{Đó là ngôi làng xinh đẹp của chúng ta.}
{1104}{}{Đó là một khu buôn bán cách nơi này vài ngày về phía Đông.}
{1105}{}{Vault là thiên đường.}
{1106}{}{Cậu là Cứu tinh.}
{1107}{}{Ông ta chữa thương bằng thảo dược và phép thuật. Ông ta ở khu
phía Bắc của ngôi làng.}
{1108}{}{Ông ta chữa thương bằng thảo dược và phép thuật. Ông ta ở khu
phía Bắc của ngôi làng.}
{1109}{}{Đây là bột chữa thương có thể chữa lành cho anh, nhưng sẽ khiến
anh thấy buồn ngủ.}
{1110}{}{Cây Cầu Lớn dẫn ra ngoài làng ở phía Nam.}
{1111}{}{Anh ta canh gác cây cầu dẫn vào làng chúng ta.}
