{100}{}{B?n th?y m?t ngư?i đàn ông trong làng.}
{101}{}{B?n th?y m?t ph? n? trong làng.}
{150}{}{M?t thành viên t?t b?ng trong làng.}
{151}{}{[NÓI CHUY?N]}
{152}{}{Xin chào! Tôi nghe nói anh là C?u tinh. Có l? ngôi làng s?p đư?c c?u r?i.}
{153}{}{Có th? nói cho tôi ch? t?m b?t ch?a thương đư?c không?}
{154}{}{Nói cho tôi bi?t v? thương gia hay đ?n đây mua bán đư?c không?}
{155}{}{Nói chuy?n vui l?m, nhưng tôi ph?i đi đây.}
{156}{}{Các th?n phù h? cho hành tr?nh c?a anh.}
{157}{}{Tôi có câu h?i này.}
{158}{}{Chào nhé, b?n tôi.}
{159}{}{Đ?n g?p Hakunin ? góc phía B?c ngôi làng. Ông ta s? giúp.}
{160}{}{Cám ơn. T?m bi?t.}
{161}{}{?, tôi không tr?c ti?p mua bán v?i ông ta. H?y đ?n nói chuy?n v?i Mynoc, ngư?i gác
cây c?u l?n. Anh ta lo vi?c đón khách.}
{162}{}{Cám ơn. T?m bi?t.}
{163}{}{Cây c?u l?n ? ch? nào nh??}
{164}{}{Tôi h?i thêm câu n?a nhé.}
{165}{}{Đùa hay đ?y, C?u tinh! Ai c?ng bi?t mà. L?i đó -- v? phía Nam.}
{166}{}{Cám ơn. T?m bi?t.}
{167}{}{Tôi h?i thêm câu n?a nhé.}
{168}{}{D? nhiên r?i, g? th??}
{169}{}{Tôi có th? t?m th?o dư?c ? đâu đư?c?}
{170}{}{Nói cho tôi bi?t v? thương gia hay đ?n đây mua bán đư?c không?}
{171}{}{Không có g?.}
{172}{}{Ơi các th?n linh -- c?u cho linh h?n c?a Ngư?i sáng l?p d?n đư?ng cho anh. N?u qu? th?c
anh là C?u tinh th? chúng ta s? c?n đư?c phù h? như v?y.}
{173}{}{Ù gà.}
{174}{}{Lên đư?ng an toàn.}
{175}{}{????}
{176}{}{Chúng ta tiêu r?i! Anh đ? th?t b?i.}
{177}{}{Anh không th? ti?p t?c th? này đư?c.}
{180}{}{Mày đ? ph?n b?i chính nh?ng ngư?i đ?ng t?c.}
{181}{}{T?i sao mày l?i làm th??}
{182}{}{Mày là ác qu?. C?u tinh là ác qu?!}
{183}{}{H? đ?n t? phía Đông, nhưng đ? c?a h? chán l?m.}
{184}{}{Tôi có th? t?m th?o dư?c ? đâu đư?c?}
{185}{}{Cám ơn. T?m bi?t.}
{186}{}{Tôi h?i thêm câu n?a nhé.}
{300}{}{Chào, C?u tinh. R?t vui đư?c g?p l?i. C?u cho nhi?m v? th?n thành luôn suôn s?. Tôi có th? giúp g? không?}
{301}{}{C?u tinh, m?i ngư?i đang ch?t d?n. C?n ph?i đi t?m GECK th?n thánh nhanh lên. Tôi có th? giúp g? đ? giúp đ? nhi?m v? th?n thánh đây?}
{302}{}{Chúng ta s?p h?t th?i gian r?i, C?u tinh ơi. Làm ơn s?m hoàn thành nhi?m v? th?n thánh đi. Chúng ta không ch? đư?c lâu hơn n?a đâu. N?u tôi có th? giúp g? đ? c?u chúng ta th? h?y nói đi.}
{303}{}{C?u tinh, ngôi làng s?p tiêu r?i... Anh là ni?m hi v?ng duy nh?t c?a chúng ta. Li?u
tôi có th? giúp g? đ? c?u chúng ta không?}
{1000}{}{Trư?ng l?o}
{1001}{}{Ngư?i m? làng}
{1002}{}{C? t? t? Vault}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{C?u tinh}
{1007}{}{Th?y cúng}
{1008}{}{Hakunin}
{1009}{}{B?t ch?a thương}
{1010}{}{C?u}
{1011}{}{Mynoc}
{1100}{}{Trư?ng l?o là m? c?u đ?ng th?i là trư?ng làng.}
{1101}{}{C? t? v? đ?i đ? truy?n ki?n th?c cho chúng ta.}
{1102}{}{Ngư?i đ?u tiên chi?n đ?u và chi?n th?ng cái x?u.}
{1103}{}{Đó là ngôi làng xinh đ?p c?a chúng ta.}
{1104}{}{Đó là m?t khu buôn bán cách nơi này vài ngày v? phía Đông.}
{1105}{}{Vault là thiên đư?ng.}
{1106}{}{C?u là C?u tinh.}
{1107}{}{Ông ta ch?a thương b?ng th?o dư?c và phép thu?t. Ông ta ? khu
phía B?c c?a ngôi làng.}
{1108}{}{Ông ta ch?a thương b?ng th?o dư?c và phép thu?t. Ông ta ? khu
phía B?c c?a ngôi làng.}
{1109}{}{Đây là b?t ch?a thương có th? ch?a lành cho anh, nhưng s? khi?n
anh th?y bu?n ng?.}
{1110}{}{Cây C?u L?n d?n ra ngoài làng ? phía Nam.}
{1111}{}{Anh ta canh gác cây c?u d?n vào làng chúng ta.}
