{100}{}{Bạn thấy một người đàn ông trong tộc.}
{101}{}{Bạn thấy một phụ nữ trong tộc.}
{150}{}{Đứng trước mặt bạn là một chiến binh to lớn mặc chiếc quần
được làm từ da thú.}
{151}{}{[NÓI CHUYỆN]}
{152}{}{Chào, Cứu tinh. Ta có thể giúp gì cho cậu đây?}
{153}{}{Tôi chỉ ngó quanh làng lần cuối trước khi đi thôi.}
{154}{}{Nói cho tôi biết về thương gia hay đến đây mua bán được không?}
{155}{}{Có thể nói cho tôi biết chỗ kiếm bột chữa thương không?}
{156}{}{Cầu các thần phù hộ cho cậu sớm đưa vườn Địa đàng về trước khi quá muộn.}
{157}{}{Tôi có câu hỏi này.}
{158}{}{Chào nhé, bạn tôi.}
{159}{}{Ồ, cậu giỡn tôi rồi. Hãy đi đến chỗ Hakunin ở góc phía Bắc ngôi làng. Ông ta là người chế
thuốc cho chúng ta.}
{160}{}{Cám ơn. Tạm biệt.}
{161}{}{Ồ, tôi có thấy họ khi Mynoc bảo chúng tôi gác cầu, nhưng anh ta mua bán mọi thứ.
Đến nói chuyện với anh ta ở Cây cầu lớn.}
{162}{}{Cám ơn. Tạm biệt.}
{163}{}{Cây cầu lớn nằm ở đâu?}
{164}{}{Tôi hỏi thêm câu nữa nhé.}
{165}{}{Cứu tinh à? Cây cầu lớn nằm ở cuối khu phía Nam của ngôi làng. Cậu đến đó
bao nhiêu lần rồi cơ mà.}
{166}{}{Cám ơn. Tạm biệt.}
{167}{}{Tôi hỏi thêm câu nữa nhé.}
{168}{}{Dĩ nhiên rồi, gì thế?}
{169}{}{Tôi có thể tìm thảo dược ở đâu được?}
{170}{}{Nói cho tôi biết về thương gia hay đến đây mua bán được không?}
{171}{}{Không có gì.}
{172}{}{À, thằng đần. Mọi người bảo mày là Cứu tinh, nhưng phải nói là linh hồn
Người sáng lập chọn kì cục thật đấy.}
{173}{}{On gà.}
{174}{}{ Đi đường an toàn nhé, đồ đần -- vì chúng ta.}
{175}{}{????}
{176}{}{Mày đã phản bội chúng ta. Chết đi.}
{177}{}{Một kẻ phản bội chính tộc của mình!}
{178}{}{Tại sao mày lại làm thế?}
{179}{}{Ác quỷ hãy chết đi!}
{180}{}{Bọn chúng chẳng là gì cả! Chúng chuyên săn tìm các xác chết
trên hoang mạc để tồn tại.}
{181}{}{Tôi có thể tìm thảo dược ở đâu được?}
{182}{}{Cám ơn. Tạm biệt.}
{183}{}{Tôi hỏi thêm câu nữa nhé.}
{300}{}{Lại gặp mặt rồi, Cứu tinh. Cầu cho các linh hồn chiến binh phù hộ và dẫn lối cho anh.}
{301}{}{Gặp khó khăn à, Cứu tinh? Đừng để chúng tôi chết - làm ơn nhanh lên.}
{302}{}{Sao lại chờ lâu vậy? Chúng ta cần sớm có GECK. Cứu tinh, ngôi làng đang chết rồi.}
{303}{}{Cứu tinh, ngôi làng sắp tiêu tùng rồi. Tại sao vẫn chưa mang GECK thần thánh về vậy?}
{970}{}{Đấy là tên tôi.}
{971}{}{Cậu đang nói chuyện với tôi.}
{972}{}{Hỏi ngốc thật. Đấy là tôi.}
{980}{}{Tôi không biết gì về chuyện đó.}
{981}{}{Xin lỗi, không biết.}
{982}{}{Chưa nghe bao giờ cả.}
{1000}{}{Trưởng lão}
{1001}{}{Người mở làng}
{1002}{}{Cụ tổ từ Vault}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Cứu tinh}
{1007}{}{Thầy cúng}
{1008}{}{Hakunin}
{1009}{}{Bột chữa thương}
{1010}{}{Cầu}
{1011}{}{Mynoc}
{1100}{}{Trưởng lão là mẹ cậu đồng thời là trưởng làng.}
{1101}{}{Cụ tổ vĩ đại đã truyền kiến thức cho chúng ta.}
{1102}{}{Người đầu tiên chiến đấu và chiến thắng cái xấu.}
{1103}{}{Đó là ngôi làng xinh đẹp của chúng ta.}
{1104}{}{Đó là một khu buôn bán cách nơi này vài ngày về phía Đông.}
{1105}{}{Vault là thiên đường.}
{1106}{}{Cậu là Cứu tinh.}
{1107}{}{Ông ta trị thương bằng thảo dược và phép thuật. Ông ta ở
khu phía Bắc của ngôi làng.}
{1108}{}{Ông ta trị thương bằng thảo dược và phép thuật. Ông ta ở
khu phía Bắc của ngôi làng.}
{1109}{}{Đây là bột chữa thương sẽ chữa lành, nhưng gây
buồn ngủ.}
{1110}{}{Cây Cầu Lớn dẫn ra ngoài làng ở phía Nam.}
{1111}{}{Anh ta canh gác cây cầu dẫn vào làng chúng ta.}
