{100}{}{B?n th?y m?t ngư?i đàn ông trong t?c.}
{101}{}{B?n th?y m?t ph? n? trong t?c.}
{150}{}{Đ?ng trư?c m?t b?n là m?t chi?n binh to l?n m?c chi?c qu?n
đư?c làm t? da thú.}
{151}{}{[NÓI CHUY?N]}
{152}{}{Chào, C?u tinh. Ta có th? giúp g? cho c?u đây?}
{153}{}{Tôi ch? ngó quanh làng l?n cu?i trư?c khi đi thôi.}
{154}{}{Nói cho tôi bi?t v? thương gia hay đ?n đây mua bán đư?c không?}
{155}{}{Có th? nói cho tôi bi?t ch? ki?m b?t ch?a thương không?}
{156}{}{C?u các th?n phù h? cho c?u s?m đưa vư?n Đ?a đàng v? trư?c khi quá mu?n.}
{157}{}{Tôi có câu h?i này.}
{158}{}{Chào nhé, b?n tôi.}
{159}{}{?, c?u gi?n tôi r?i. H?y đi đ?n ch? Hakunin ? góc phía B?c ngôi làng. Ông ta là ngư?i ch?
thu?c cho chúng ta.}
{160}{}{Cám ơn. T?m bi?t.}
{161}{}{?, tôi có th?y h? khi Mynoc b?o chúng tôi gác c?u, nhưng anh ta mua bán m?i th?.
Đ?n nói chuy?n v?i anh ta ? Cây c?u l?n.}
{162}{}{Cám ơn. T?m bi?t.}
{163}{}{Cây c?u l?n n?m ? đâu?}
{164}{}{Tôi h?i thêm câu n?a nhé.}
{165}{}{C?u tinh à? Cây c?u l?n n?m ? cu?i khu phía Nam c?a ngôi làng. C?u đ?n đó
bao nhiêu l?n r?i cơ mà.}
{166}{}{Cám ơn. T?m bi?t.}
{167}{}{Tôi h?i thêm câu n?a nhé.}
{168}{}{D? nhiên r?i, g? th??}
{169}{}{Tôi có th? t?m th?o dư?c ? đâu đư?c?}
{170}{}{Nói cho tôi bi?t v? thương gia hay đ?n đây mua bán đư?c không?}
{171}{}{Không có g?.}
{172}{}{Ah, dull one. They say you are the Chosen One. I must say the spirit
 of the Founder works in strange ways.}
{173}{}{Oon Ga.}
{174}{}{ Have a safe journey, dull one -- for our sake.}
{175}{}{????}
{176}{}{You betray us. You must die.}
{177}{}{A traitor to your own people!}
{178}{}{T?i sao mày l?i làm th??}
{179}{}{Death to the evil one!}
{180}{}{They are nothing to us! They scavenge the dying corpse
 of the wastes to live.}
{181}{}{Tôi có th? t?m th?o dư?c ? đâu đư?c?}
{182}{}{Cám ơn. T?m bi?t.}
{183}{}{Tôi h?i thêm câu n?a nhé.}
{300}{}{Hello again, Chosen One. May the warrior spirits protect and guide you.}
{301}{}{Are you having difficulties, Chosen One? You must not fail us - please hurry.}
{302}{}{Why do you wait so long? We must have the GECK soon. Chosen One, our village is dying.}
{303}{}{Chosen One, our village is almost dead. Why have you not brought the holy GECK to us yet?}
{970}{}{That is my name.}
{971}{}{You are talking to me.}
{972}{}{What a silly question. That's me.}
{980}{}{I don't know anything about that.}
{981}{}{Sorry. No clue.}
{982}{}{Never heard of it.}
{1000}{}{Trư?ng l?o}
{1001}{}{Ngư?i m? làng}
{1002}{}{C? t? t? Vault}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{C?u tinh}
{1007}{}{Th?y cúng}
{1008}{}{Hakunin}
{1009}{}{B?t ch?a thương}
{1010}{}{C?u}
{1011}{}{Mynoc}
{1100}{}{Trư?ng l?o là m? c?u đ?ng th?i là trư?ng làng.}
{1101}{}{C? t? v? đ?i đ? truy?n ki?n th?c cho chúng ta.}
{1102}{}{Ngư?i đ?u tiên chi?n đ?u và chi?n th?ng cái x?u.}
{1103}{}{Đó là ngôi làng xinh đ?p c?a chúng ta.}
{1104}{}{Đó là m?t khu buôn bán cách nơi này vài ngày v? phía Đông.}
{1105}{}{Vault là thiên đư?ng.}
{1106}{}{C?u là C?u tinh.}
{1107}{}{He heals us with his herbs and magic. He is in the northern
 part of our village.}
{1108}{}{He heals us with his herbs and magic. He is in the northern
 part of our village.}
{1109}{}{It is a magic powder which will heal you, but will make
 you sleepy.}
{1110}{}{Cây C?u L?n d?n ra ngoài làng ? phía Nam.}
{1111}{}{Anh ta canh gác cây c?u d?n vào làng chúng ta.}
