{100}{}{B?n th?y m?t ngư?i đàn ông trong t?c.}
{101}{}{B?n th?y m?t ph? n? trong t?c.}
{150}{}{Đ?ng trư?c m?t b?n là m?t chi?n binh to l?n m?c chi?c qu?n
đư?c làm t? da thú.}
{151}{}{[NÓI CHUY?N]}
{152}{}{Chào, C?u tinh. Ta có th? giúp g? cho c?u đây?}
{153}{}{Tôi ch? ngó quanh làng l?n cu?i trư?c khi đi thôi.}
{154}{}{Nói cho tôi bi?t v? thương gia hay đ?n đây mua bán đư?c không?}
{155}{}{Có th? nói cho tôi bi?t ch? ki?m b?t ch?a thương không?}
{156}{}{C?u các th?n phù h? cho c?u s?m đưa vư?n Đ?a đàng v? trư?c khi quá mu?n.}
{157}{}{Tôi có câu h?i này.}
{158}{}{Chào nhé, b?n tôi.}
{159}{}{?, c?u gi?n tôi r?i. H?y đi đ?n ch? Hakunin ? góc phía B?c ngôi làng. Ông ta là ngư?i ch?
thu?c cho chúng ta.}
{160}{}{Cám ơn. T?m bi?t.}
{161}{}{?, tôi có th?y h? khi Mynoc b?o chúng tôi gác c?u, nhưng anh ta mua bán m?i th?.
Đ?n nói chuy?n v?i anh ta ? Cây c?u l?n.}
{162}{}{Cám ơn. T?m bi?t.}
{163}{}{Cây c?u l?n n?m ? đâu?}
{164}{}{Tôi h?i thêm câu n?a nhé.}
{165}{}{C?u tinh à? Cây c?u l?n n?m ? cu?i khu phía Nam c?a ngôi làng. C?u đ?n đó
bao nhiêu l?n r?i cơ mà.}
{166}{}{Cám ơn. T?m bi?t.}
{167}{}{Tôi h?i thêm câu n?a nhé.}
{168}{}{D? nhiên r?i, g? th??}
{169}{}{Tôi có th? t?m th?o dư?c ? đâu đư?c?}
{170}{}{Nói cho tôi bi?t v? thương gia hay đ?n đây mua bán đư?c không?}
{171}{}{Không có g?.}
{172}{}{À, th?ng đ?n. M?i ngư?i b?o mày là C?u tinh, nhưng ph?i nói là linh h?n
Ngư?i sáng l?p ch?n k? c?c th?t đ?y.}
{173}{}{On gà.}
{174}{}{ Đi đư?ng an toàn nhé, đ? đ?n -- v? chúng ta.}
{175}{}{????}
{176}{}{Mày đ? ph?n b?i chúng ta. Ch?t đi.}
{177}{}{M?t k? ph?n b?i chính t?c c?a m?nh!}
{178}{}{T?i sao mày l?i làm th??}
{179}{}{Ác qu? h?y ch?t đi!}
{180}{}{B?n chúng ch?ng là g? c?! Chúng chuyên săn t?m các xác ch?t
trên hoang m?c đ? t?n t?i.}
{181}{}{Tôi có th? t?m th?o dư?c ? đâu đư?c?}
{182}{}{Cám ơn. T?m bi?t.}
{183}{}{Tôi h?i thêm câu n?a nhé.}
{300}{}{L?i g?p m?t r?i, C?u tinh. C?u cho các linh h?n chi?n binh phù h? và d?n l?i cho anh.}
{301}{}{G?p khó khăn à, C?u tinh? Đ?ng đ? chúng tôi ch?t - làm ơn nhanh lên.}
{302}{}{Sao l?i ch? lâu v?y? Chúng ta c?n s?m có GECK. C?u tinh, ngôi làng đang ch?t r?i.}
{303}{}{C?u tinh, ngôi làng s?p tiêu tùng r?i. T?i sao v?n chưa mang GECK th?n thánh v? v?y?}
{970}{}{Đ?y là tên tôi.}
{971}{}{C?u đang nói chuy?n v?i tôi.}
{972}{}{H?i ng?c th?t. Đ?y là tôi.}
{980}{}{Tôi không bi?t g? v? chuy?n đó.}
{981}{}{Xin l?i, không bi?t.}
{982}{}{Chưa nghe bao gi? c?.}
{1000}{}{Trư?ng l?o}
{1001}{}{Ngư?i m? làng}
{1002}{}{C? t? t? Vault}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{C?u tinh}
{1007}{}{Th?y cúng}
{1008}{}{Hakunin}
{1009}{}{B?t ch?a thương}
{1010}{}{C?u}
{1011}{}{Mynoc}
{1100}{}{Trư?ng l?o là m? c?u đ?ng th?i là trư?ng làng.}
{1101}{}{C? t? v? đ?i đ? truy?n ki?n th?c cho chúng ta.}
{1102}{}{Ngư?i đ?u tiên chi?n đ?u và chi?n th?ng cái x?u.}
{1103}{}{Đó là ngôi làng xinh đ?p c?a chúng ta.}
{1104}{}{Đó là m?t khu buôn bán cách nơi này vài ngày v? phía Đông.}
{1105}{}{Vault là thiên đư?ng.}
{1106}{}{C?u là C?u tinh.}
{1107}{}{Ông ta tr? thương b?ng th?o dư?c và phép thu?t. Ông ta ?
khu phía B?c c?a ngôi làng.}
{1108}{}{Ông ta tr? thương b?ng th?o dư?c và phép thu?t. Ông ta ?
khu phía B?c c?a ngôi làng.}
{1109}{}{Đây là b?t ch?a thương s? ch?a lành, nhưng gây
bu?n ng?.}
{1110}{}{Cây C?u L?n d?n ra ngoài làng ? phía Nam.}
{1111}{}{Anh ta canh gác cây c?u d?n vào làng chúng ta.}
