{100}{}{B?n th?y Trư?ng l?o c?a làng.}
{101}{}{Đây là Trư?ng l?o.}
{102}{}{Trư?ng l?o r?t - già, già hơn c? nh?ng g? b?n nh? đư?c. Tuy nhiên, bà v?n
gi? đư?c s?c l?c và tinh th?n đ? d?n d?t ngôi làng vư?t qua th?i đi?m khó khăn.}
{103}{aeld1}{Chúc m?ng, C?u tinh, con đ? s?ng sót qua Ngôi đ?n th? thách. Con đ? s?n sàng
đi làm nhi?m v? chưa?}
{104}{}{Bà làm g? đ?y - c? gi?t tôi trong đ?n à?}
{105}{}{D? nhiên r?i.}
{106}{}{Con mu?n ngh? thêm m?t chút v? vi?c đó.}
{107}{aeld2a}{Ta r?t t? hào v? con, C?u tinh. Con đ? vư?t qua nhi?u th?. Bây gi?, con ph?i đi t?m Vault 13.
Vault 13. C?m GECK v?. GECK. Đây là m?t cái b?nh sáng bóng. Vic đ? mang đ?n đây. Vic. L?o ta
là thương nhân ? Klamath. Klamath. Đi t?m Vic. T?m Vault 13. T?m GECK. V? nhà. H?y
c? h?t s?c, con ta.}
{112}{aeld2b}{Con chưa t?m đư?c h?m. T?m căn h?m! Vault 13.}
{113}{}{?.}
{114}{aeld3}{C?u tinh, con mu?n t?t c? chúng ta đ?u ch?t à? Con ph?i đi t?m Vault!}
{115}{}{Con xin l?i, Trư?ng l?o. Con s? thành công.}
{116}{}{?, ?. Im m?m đi.}
{117}{aeld4}{C?u tinh, sao con l?i ? đây?}
{118}{}{Con bi?t Vault 13 ? đâu!}
{119}{}{Con đ? s?n sàng làm nhi?m v? th?n thánh.}
{120}{}{Con c?n thêm thông tin.}
{121}{}{Con s? không đi t?m ch?t đâu!}
{122}{}{Con c?n làm cái g? ?y nh??}
{123}{}{Con đi đây.}
{124}{aeld5}{Tin t?t đ?y, nhưng chưa đ? đ? c?u chúng ta. Con c?n ph?i s?m c?m GECK v?, 
n?u không m?i ngư?i s? ch?t!}
{125}{}{Con c?n thêm thông tin.}
{126}{}{R?i, con đi gi? đây.}
{127}{aeld6}{Con đ? s?ng sót. C?u tinh không th? y?u đu?i đư?c, n?u không chúng ta s? tiêu đ?i.
Con đ? s?n sàng đi làm nhi?m v? chưa?}
{128}{}{Con đ? vư?t qua th? thách. D? nhiên là con s?n sàng r?i.}
{129}{}{Con c?n ngh? v? vi?c đó.}
{130}{}{Con s? không đi t?m ch?t đâu!}
{131}{aeld7}{Nghe này. H?y đi t?m Vault 13 th?n thành và c?m GECK v? đây. Vic, thương nhân
t? Klamath đ? đưa cái b?ch nư?c t? s? 13 th?n thánh đ?n đây. B?t đ?u t?m ki?m t?
ch? ông ta. Chi?c đ?a này s? nh?c nh? con v? nhi?m v?. C?u các th?n Vault phù h? cho con.}
{133}{}{Trư?c khi đi, con có m?y câu h?i.}
{134}{}{T?m bi?t. Con s? c?u đư?c b? t?c.}
{135}{aeld8}{Đư?c r?i. H?y đ?n g?p ta khi nào con quy?t đ?nh - nhưng đ?ng đ? lâu quá.}
{136}{}{T?m bi?t.}
{137}{aeld9}{Ta không giúp đư?c nhi?u đâu. R?t nhi?u th? t? th?i Xa xưa đ? không c?n n?a. Con mu?n bi?t v? vi?c g??}
{138}{aeld9b}{Con c?n g??}
{139}{}{Nói thêm v? GECK đi.}
{140}{}{How do I get to Klamath?}
{141}{}{Where is Vault 13?}
{142}{}{On second thought, I don't need any help now. Goodbye.}
{143}{aeld10}{It is a holy artifact - the Garden of Eden Creation Kit. The disks promise it
 will make our lands green and our village prosperous. It will save us. More, I do not know.}
{144}{}{There's more I want to know.}
{145}{}{T?m bi?t.}
{146}{aeld11}{Klamath is to the east.}
{147}{}{There are other things I would learn.}
{148}{}{I am ready. Goodbye.}
{149}{aeld12}{The holy Thirteen? I cannot help you. Only the Vault Dweller knew. His tales have
 the sound of a perilous journey. }
{150}{}{I see. There is much I need to know.}
{151}{}{Goodbye, Elder.}
{152}{aeld13}{Being a coward will kill us all! Including you. You passed
 the Temple Trials. We have faith in you. We need you.}
{153}{}{Not so fast, old woman. I need time to think about this!}
{154}{}{As you wish, Elder.}
{155}{aeld14a}{You've betrayed us. You will perish.}
{156}{aeld14b}{You are a traitor!}
{157}{aeld14c}{Why do you do this?}
{158}{aeld14d}{I knew you had the soul of darkness!}
{159}{aeld15}{Then take this flask. It is from the holy Vault 13. Vic, a trader in Klamath,
 brought it to us. He may know where the vault is. You may also need some of what they
 call money. Here.}
{160}{}{Uh... What was my quest again?}
{161}{}{Is there more you can tell me?}
{162}{}{Wish me luck, Elder, and I will not fail you.}
{163}{aeld16}{Find Vic in Klamath. We are counting on you.}
{164}{aeld17}{It's good to see you again, Child. I don't mean to be abrupt but I see you
 haven't completed your quest to find the holy Thirteen. Please, let's not waste time
 talking. The need of our people is great. Go find the Vault!}
{165}{}{Me go now.}
{166}{}{All right, I'm going.}
{167}{}{I will not fail you elder.}
{168}{}{I'm working on it, Ok?}
{169}{aeld18}{Once again you return without the GECK. Our crops begin to fail us, Chosen. Our
 need becomes greater with the passage of time. Go find the holy Thirteen!}
{170}{}{Ok, me go now.}
{171}{}{Yes, Elder.}
{172}{}{I will not fail you or our people, Elder.}
{173}{}{Look. If you think you can do better... }
{174}{aeld19}{Chosen One, things are not well here. We need the GECK if our village is to
 survive. Our people grow weak with hunger and our food reserves will not last much
 longer. Please, find the holy Thirteen and return to us. Go now.}
{175}{}{Ng? đi.}
{176}{}{Very well. I'm on my way.}
{177}{}{I will do my best to find the GECK and save our village.}
{178}{}{Don't push me, old woman. I'm doing my best.}
{179}{aeld20}{Child, our need is greater than ever before. Our people sicken, the brahmin
 are dying, and our food is all but gone. The blight of the land can only be cured with
 the GECK. Go, find the GECK and save our people.}
{180}{}{Ng? hi?u.}
{181}{}{I'm on my way.}
{182}{}{Forgive me Elder. I will find the GECK without delay.}
{183}{}{Yeah, yeah. You're beginning to sound like a broken disk...}
{200}{eeld1}{Chosen One! How did you get here?}
{201}{}{Uhh... duh?}
{202}{}{I've come to rescue you.}
{203}{}{What the hell's going on here?}
{204}{eeld2}{You monster! Have you come to kill me, too?}
{205}{}{Uhhh?}
{206}{}{No, it's me, the Chosen One!}
{207}{}{Oh, shut up, you old bitch! It's me, your Chosen One.}
{208}{eeld3}{Oh, gods... Listen - go down. Find machine that makes power. Kill machine. Kill bad men. Kill everybody! You kill, we go home. Also, if you not have GECK then look for GECK here. Must have GECK to save village! Freedom is nothing without home to return to. Understand? Oh, gods.}
{209}{}{Uh -huh!}
{210}{eeld4}{Careful, do not touch the glow wall. I think the machine that feeds it is beneath us. Destroy it so we may escape. How did you get here?}
{211}{}{I have a ship. }
{212}{eeld5}{Men came to our village in flying machines and took us. There were others, too - from the holy Thirteen! I thought we were saved. I thought we were going to heaven. (sigh)}
{213}{}{And then?}
{214}{eeld5a}{Then they brought us here, to hell. They have killed most of us with something they call effeevee. They will kill us all before they are through!
 Do you know what must be done, Chosen One?}
{215}{}{Effeevee?}
{216}{}{Đúng v?y.}
{217}{}{Không.}
{218}{eeld6}{If you destroy the machine, we will find the ship. Hurry, there are not many of us left. }
{219}{}{What happened?}
{220}{}{Tôi hi?u r?i.}
{221}{eeld7}{You must destroy the machine and kill the devils in this place. We will meet you outside! And Chosen One, if you have not found the GECK, seek it here. Our freedom is nothing if we cannot save our village. Now go!}
{222}{}{T?m bi?t.}
{223}{eeld8}{I am still the Elder. Remember your place! Apologize or I will not help you anymore.}
{224}{}{Sorry, you're not an old bitch. What's going on?}
{225}{}{Like you could help me in there? Fuck off and die.}
{226}{eeld9}{Go away. You are no better than these devils. I weep you were named the Chosen One.}
{227}{eeld10}{Why are you here? Every minute you waste another of our people could be killed. And don't forget the GECK! We must have it.}
{228}{}{Nuh??}
{229}{}{Where was I supposed to go?}
{230}{}{Just wanted to annoy you. I'm on it. Don't worry.}
{231}{eeld11}{(sigh) Go below. Kill. Smash machines. Go now!}
{232}{eeld12}{Listen this time! Go to the levels below us. Find the machine that makes power. Stop it and we can escape. The men here are not true to the Vault dream. They are evil. Also, if you have not yet found the GECK, seek it here. Our freedom is nothing if our village cannot be saved. Now go!}
{233}{}{Got it.}
{234}{eeld13}{That is what they call it. They stick needles into our skin, like stimpaks, but then terrible things happen. Then... (chokes up)}
{235}{}{Then what?}
{236}{}{This is going to make me sick, isn't it?}
{237}{eeld13a}{Then the skin bubbles like maggots beneath it. Boils grow and burst. Blood runs from your ears and your tongue swells. Those who are lucky choke to death. Those who are not...}
{238}{}{They'll pay.}
{239}{}{That certainly was disgusting. What am I supposed to do?}
