{100}{}{Bạn thấy Trưởng lão của làng.}
{101}{}{Đây là Trưởng lão.}
{102}{}{Trưởng lão rất - già, già hơn cả những gì bạn nhớ được. Tuy nhiên, bà vẫn
giữ được sức lực và tinh thần để dẫn dắt ngôi làng vượt qua thời điểm khó khăn.}
{103}{aeld1}{Chúc mừng, Cứu tinh, con đã sống sót qua Ngôi đền thử thách. Con đã sẵn sàng
đi làm nhiệm vụ chưa?}
{104}{}{Bà làm gì đấy - cố giết tôi trong đền à?}
{105}{}{Dĩ nhiên rồi.}
{106}{}{Con muốn nghĩ thêm một chút về việc đó.}
{107}{aeld2a}{Ta rất tự hào về con, Cứu tinh. Con đã vượt qua nhiều thứ. Bây giờ, con phải đi tìm Vault 13.
Vault 13. Cầm GECK về. GECK. Đây là một cái bình sáng bóng. Vic đã mang đến đây. Vic. Lão ta
là thương nhân ở Klamath. Klamath. Đi tìm Vic. Tìm Vault 13. Tìm GECK. Về nhà. Hãy
cố hết sức, con ta.}
{112}{aeld2b}{Con chưa tìm được hầm. Tìm căn hầm! Vault 13.}
{113}{}{Ừ.}
{114}{aeld3}{Cứu tinh, con muốn tất cả chúng ta đều chết à? Con phải đi tìm Vault!}
{115}{}{Con xin lỗi, Trưởng lão. Con sẽ thành công.}
{116}{}{Ờ, ờ. Im mồm đi.}
{117}{aeld4}{Cứu tinh, sao con lại ở đây?}
{118}{}{Con biết Vault 13 ở đâu!}
{119}{}{Con đã sẵn sàng làm nhiệm vụ thần thánh.}
{120}{}{Con cần thêm thông tin.}
{121}{}{Con sẽ không đi tìm chết đâu!}
{122}{}{Con cần làm cái gì ấy nhỉ?}
{123}{}{Con đi đây.}
{124}{aeld5}{Tin tốt đấy, nhưng chưa đủ để cứu chúng ta. Con cần phải sớm cầm GECK về, 
nếu không mọi người sẽ chết!}
{125}{}{Con cần thêm thông tin.}
{126}{}{Rồi, con đi giờ đây.}
{127}{aeld6}{Con đã sống sót. Cứu tinh không thể yếu đuối được, nếu không chúng ta sẽ tiêu đời.
Con đã sẵn sàng đi làm nhiệm vụ chưa?}
{128}{}{Con đã vượt qua thử thách. Dĩ nhiên là con sẵn sàng rồi.}
{129}{}{Con cần nghĩ về việc đó.}
{130}{}{Con sẽ không đi tìm chết đâu!}
{131}{aeld7}{Nghe này. Hãy đi tìm Vault 13 thần thành và cầm GECK về đây. Vic, thương nhân
từ Klamath đã đưa cái bịch nước từ số 13 thần thánh đến đây. Bắt đầu tìm kiếm từ
chỗ ông ta. Chiếc đĩa này sẽ nhắc nhở con về nhiệm vụ. Cầu các thần Vault phù hộ cho con.}
{133}{}{Trước khi đi, con có mấy câu hỏi.}
{134}{}{Tạm biệt. Con sẽ cứu được bộ tộc.}
{135}{aeld8}{Được rồi. Hãy đến gặp ta khi nào con quyết định – nhưng đừng để lâu quá.}
{136}{}{Tạm biệt.}
{137}{aeld9}{Ta không giúp được nhiều đâu. Rất nhiều thứ từ thời Xa xưa đã không còn nữa. Con muốn biết về việc gì?}
{138}{aeld9b}{Con cần gì?}
{139}{}{Nói thêm về GECK đi.}
{140}{}{Đi Klamath đường nào thế?}
{141}{}{Vault 13 chỗ nào ấy nhỉ?}
{142}{}{Mà thôi, con không cần giúp nữa. Tạm biệt.}
{143}{aeld10}{Đó là một món bảo vật thần thánh – Bộ tạo Vườn Địa đàng. Chiếc đĩa ghi rằng thứ này sẽ mang đến
màu xanh và sự sung túc cho làng. Nó sẽ cứu chúng ta. Còn lại thì ta không rõ.}
{144}{}{Con muốn biết thêm.}
{145}{}{Tạm biệt.}
{146}{aeld11}{Klamath đi về phía Đông.}
{147}{}{Con muốn biết về những việc khác.}
{148}{}{Con sẵn sàng rồi. Tạm biệt.}
{149}{aeld12}{Số 13 thần thánh? Ta không giúp gì được. Chỉ có Cụ tổ từ Vault mới biết thôi. Theo lời
ông thì đó là một cuộc hành trình đầy gian nan.}
{150}{}{Vậy à. Vẫn còn nhiều thứ con muốn biết.}
{151}{}{Tạm biệt, Trưởng lão.}
{152}{aeld13}{Sự hèn nhát sẽ giết chết tất cả chúng ta! Kể cả con nữa. Con đã
vượt qua Ngôi đền thử thách. Chúng ta tin con. Chúng ta cần con.}
{153}{}{Từ từ đã, bà già. Tôi cần thêm thời gian để suy nghĩ về việc này!}
{154}{}{Cứ theo ý người đi, Trưởng lão.}
{155}{aeld14a}{Mày đã phản bội chúng ta. Mày phải chết.}
{156}{aeld14b}{Đồ phản bội!}
{157}{aeld14c}{Tại sao mày lại làm thế?}
{158}{aeld14d}{Ta biết là mày có tâm địa xấu xa mà!}
{159}{aeld15}{Vậy thì cầm lấy cái bịch này, vốn từ Vault 13 thần thánh. Vic, thương nhân đến từ
Klamath đã mang nó đến đây. Ông ta có thể biết căn hầm đó ở đâu. Con cũng sẽ cần
một ít thứ bọn họ gọi là tiền. Đây.}
{160}{}{Ừm... Nhiệm vụ của con là gì ấy nhỉ?}
{161}{}{Con có cần biết thêm gì không?}
{162}{}{Hãy chúc con may mắn đi, Trưởng lão. Con sẽ thành công.}
{163}{aeld16}{Tìm Vic ở Klamath. Chúng ta trông chờ vào con.}
{164}{aeld17}{Rất vui được gặp lại con. Ta không có ý ném đá đâu nhưng ta thấy là con vẫn
chưa hoàn thành nhiêm vụ đi tìm số 13 thần thánh. Đừng lãng phí thời gian
tán nhảm nữa. Mọi người đang trông ngóng từng ngày. Hãy đi tìm Vault!}
{165}{}{Ngộ đi giờ.}
{166}{}{Được rồi, con đi đây.}
{167}{}{Con sẽ thành công, Trưởng lão.}
{168}{}{Tôi đang làm rồi, Ô xừ kê?}
{169}{aeld18}{Vậy là con lại về mà không có GECK. Cây trồng đang héo tàn rồi, Cứu tinh. Chúng ta
đang ngày càng nguy cấp hơn. Hãy đi tìm số 13 thần thánh!}
{170}{}{Ok, ngộ đi giờ.}
{171}{}{Vâng, thưa Trưởng lão.}
{172}{}{Con sẽ cứu được mọi người, Trưởng lão.}
{173}{}{Này, nếu bà nghĩ là bà có thể làm tốt hơn... }
{174}{aeld19}{Cứu tinh, mọi thứ ở làng đều bất ổn. Ngôi làng cần có GECK để tồn tại. Mọi người
đang chết đói, còn kho lương dự trữ chẳng mấy nữa. Làm ơn đi, hãy đi tìm số 13
thần thánh và trở về đây. Giờ thì đi đi.}
{175}{}{Ngộ đi.}
{176}{}{Được rồi. Con lên đường đây.}
{177}{}{Con sẽ cố hết sức đi tìm GECK và cứu ngôi làng.}
{178}{}{Đừng có giục, bà già. Tôi đang cố hết sức đây.}
{179}{aeld20}{Con ơi, chúng ta đang cần hơn bao giờ hết. Mọi người đều yếu rồi, đàn gia súc
chết dần, lương thực thì cạn kiệt. Đất bạc màu hết và chỉ có GECK mới có thể giải quyết
được. Đi đi, tìm GECK và cứu lấy chúng ta.}
{180}{}{Ngộ hiểu.}
{181}{}{Con đi đây.}
{182}{}{Thứ lỗi cho con, Trưởng lão. Con sẽ đi tìm GECK ngay.}
{183}{}{Rồi, rồi. Bà bắt đầu ca cẩm chẳng khác nào cái đĩa kẹt cả...}
{200}{eeld1}{Cứu tinh! Làm thế nào mà con lại đến đây thế?}
{201}{}{Ờ.. đờ?}
{202}{}{Con đến để cứu người.}
{203}{}{Chuyện quái gì đang diễn ra thế?}
{204}{eeld2}{Đồ quái vật! Mày cũng đến để giết tao à?}
{205}{}{Ờ ờ?}
{206}{}{Không phải, là con đây, Cứu tinh đây!}
{207}{}{Ồ, im mồm đi, bà già khó tính! Là tôi, Cứu tinh của bà đây.}
{208}{eeld3}{Ôi, thần linh ơi... Nghe này, đi xuống dưới. Hãy tìm cái máy tạo ra điện. Giết máy. Giết người xấu. Giết tất! Con giết, chúng ta về nhà. Còn nữa, nếu chưa có GECK thì tìm GECK ở đây. Cần có GECK để cứu làng! Tự do để làm gì nếu nhà không còn. Hiểu chưa? Ôi, thần linh.}
{209}{}{Ừ hứ!}
{210}{eeld4}{Cẩn thận, đừng chạm vào tường lung linh. Ta nghĩ là cái máy cấp điện ở bên dưới chúng ta. Hãy phá hủy nó để chúng ta có thể trốn thoát. Làm sao con lại đến được đây?}
{211}{}{Con có cái tàu. }
{212}{eeld5}{Đám người này đến làng bằng máy biết bay và bắt chúng ta. Có cả những người khác nữa – từ số 13 thần thánh! Ta tưởng chúng ta được cứu rồi. Ta tưởng là chúng ta sắp được lên thiên đường. (thở dài)}
{213}{}{Rồi sau đó?}
{214}{eeld5a}{Sau đó họ đưa chúng ta đến đây, đến địa ngục. Chúng đã giết gần hết bọn ta bằng thứ mà chúng gọi là ép e vi. Chúng sẽ giết hết chúng ta
trước khi thứ đó hoàn thiện! Con biết cần phải làm gì rồi chứ, Cứu tinh?}
{215}{}{Ép e vi?}
{216}{}{Đúng vậy.}
{217}{}{Không.}
{218}{eeld6}{Nếu con phá hủy cái máy, chúng ta sẽ đi tìm tàu. Nhanh lên, chúng ta không còn bao nhiêu người đâu.}
{219}{}{Chuyện gì đã xảy ra thế?}
{220}{}{Tôi hiểu rồi.}
{221}{eeld7}{Con phải phá hủy cái máy và tiêu diệt ác quỷ nơi này. Chúng ta sẽ gặp con ở bên ngoài! À mà Cứu tinh ơi, nếu con vẫn chưa tìm thấy GECK thì hãy tìm ở đây. Tự do để làm gì nếu chúng ta không thể cứu được ngôi làng. Giờ thì đi đi!}
{222}{}{Tạm biệt.}
{223}{eeld8}{Ta vẫn là Trưởng lão đấy. Đừng có hỗn! Xin lỗi ngay hoặc ta sẽ không giúp ngươi nữa đâu.}
{224}{}{Xin lỗi, bà không phải bà già khó tính. Chuyện gì đang xảy ra thế?}
{225}{}{Bà ở trong đó thì giúp cái đéo gì? Cuốn xéo rồi chết đi.}
{226}{eeld9}{Cút đi. Mày chẳng khác gì đám quỷ đó cả. Ta tuyên bố mày không còn là Cứu tinh nữa.}
{227}{eeld10}{Sao con lại ở đây? Mỗi phút con lãng phí là lại có thêm người trong tộc bị giết. Và đừng có quên GECK đấy! Chúng ta cần thứ đó.}
{228}{}{Nuh??}
{229}{}{Con cần phải đi đâu?}
{230}{}{Trêu tí thôi, con đi đây. Đừng lo.}
{231}{eeld11}{(Thở dài) Đi xuống dưới. Giết. Đập máy. Giờ thì đi đi!}
{232}{eeld12}{Lần này thì nghe cho kĩ! Đi xuống tầng bên dưới. Tìm cái máy tạo điện. Dừng nó lại và chúng ta có thể thoát ra. Những kẻ ở đây không phải là Vault trong mơ đích thực. Chúng là ác quỷ. Còn nữa, nếu con vẫn chưa tìm thấy GECK, hãy tìm ở đây. Tự do để làm gì nếu không thể cứu được ngôi làng. Giờ thì đi đi!}
{233}{}{Hiểu rồi.}
{234}{eeld13}{Chúng gọi nó như vậy. Chúng chọc kim vào người chúng ta, giống như stimpak, nhưng những thứ khủng khiếp xảy ra. Sau đó... (nấc nghẹn)}
{235}{}{Sau đó thì sao?}
{236}{}{Thứ đó kinh khủng lắm phải không?}
{237}{eeld13a}{Sau đó trên da sôi lên như có giòi ở trong. Sủi bọt và vỡ tung. Máu phun ra từ lỗ tai, lưỡi thì phồng lên. Những người chết đi còn may. Những người không chết thì...}
{238}{}{Bọn chúng sẽ phải trả giá.}
{239}{}{Đúng là kinh vl. Con phải làm gì đây?}
