{100}{}{Trư?c m?t b?n là Hakunin, pháp sư c?a làng. L?o ta soi b?n b?ng c?p m?t thao láo, như th? đang nh?n t? m?t th? gi?i c?a riêng l?o v?y...}
{101}{}{B?n th?y Hakunin đang n?m trên m?t đ?y. L?o ta b? thương r?t n?ng.}
{102}{}{B?n th?y Hakunin. L?o ta g?n như ch?t r?i.}
{103}{}{Hakunin b? b?ng r?t n?ng. Mùi ch?ng khác nào gà rán, nh?n như mi?ng th?t băm cháy r?i, và b?n không bi?t làm th? nào mà l?o v?n c?n s?ng đư?c đ?n gi?.}
{104}{hak001}{Xin chào, C?u tinh. Sao kho?nh đ?t trư?c m?t ta l?i đư?c con d?m lên v?y?}
{105}{}{??}
{106}{}{Tôi đ?n đ? chào t?m bi?t. Tôi s?p lên đư?ng th?c hi?n nhi?m v? th?n thánh.}
{107}{}{Tôi s?p đi. Tôi hi v?ng là l?n này l?o có th? nói chuy?n như ngư?i b?nh thư?ng.}
{108}{}{L?o bú c?n quá đ? r?i đ?y. Tôi bi?n kh?i đây đây.}
{109}{}{Tôi b? thương. L?o ch?a đư?c không?}
{110}{}{Vư?n c?a l?o b? m?y cái cây t?m v?i m?c chen vào, tôi nh? s?ch chúng cho l?o r?i.}
{111}{hak001a}{H?y cho c?p m?t m? đ?c này th?y con đư?ng c?a con.}
{112}{}{??}
{113}{}{Tôi đ?n đ? chào t?m bi?t. Tôi s?p lên đư?ng th?c hi?n nhi?m v? th?n thánh.}
{114}{}{Tôi s?p đi. Tôi hi v?ng là l?n này l?o có th? nói chuy?n như ngư?i b?nh thư?ng.}
{115}{}{L?o bú c?n quá đ? r?i đ?y. Tôi bi?n kh?i đây đây.}
{116}{}{Vư?n c?a l?o b? m?y cái cây t?m v?i m?c chen vào, tôi nh? s?ch chúng cho l?o r?i.}
{117}{hak002}{M?t đ?t ngân lên ti?ng ca v? v? anh hùng giáng th?... Có l? trư?c khi đi, con có th? th? hi?n s? hào hi?p đư?c chăng?}
{118}{}{Đư?c ch?. L?o c?n g? nào?}
{119}{}{Đ? xem... L?o s? tr? công tôi th? nào?}
{120}{hak002a}{Có vô s? cách quan sát th? gi?i – đi?u mà con s? s?m h?c đư?c... Có l?, trư?c khi con hái qu? ng?t t? cây đ?i kinh nghi?m, con có th? th? hi?n s? hào hi?p chăng?}
{121}{}{Ch?ng ph?i l?o v?a m?i nh? tôi giúp sao? N?u v?y th? đư?c r?i, sao l?i không ch??}
{122}{}{Tôi s? giúp l?o, nhưng v? l?o c? huyên thuyên khó hi?u v?i nên giúp ph?i tính công đ?y.}
{123}{hak003}{Các th?n phù h? con, con đúng là m?t đ?a tr? t?t b?ng. Li?u con có th? s? d?ng tài năng đ?c bi?t và gi?i thoát cho m?nh vư?n c?a ta kh?i nh?ng cái cây c?a linh h?n h?c ám?}
{124}{}{? h?.}
{125}{}{Khôn. L?ooo. Đưa. Đau đ?u.}
{126}{hak004}{C?u cho hào quang c?a con r?i chi?u lên ta khi con xong... ?, quay l?i l?u c?a ta sau khi xong và ta s? đưa cho con đ? t?t.}
{127}{}{Ch?c.}
{128}{hak005}{Nh?ng cái cây c?a linh h?n h?c ám m?t l?n n?a l?i xâm chi?m m?nh vư?n c?a ta. Nh?ng đ?t xương này đ? già c?i sau nhi?u mùa và ta đ? tr? nên quá y?u trư?c cu?c chi?n trư?c thiên nhiên v?nh h?ng. Ta c?n con làm ngư?i b?o h?.}
{129}{}{Tôi không ngh? v?y. Tôi c?n ph?i b?t đ?u nhi?m v? ngay bây gi?.}
{130}{}{Tôi bi?t là l?o không ph?i là ngư?i x?u, nhưng tôi đau đ?u quá, nên ch?c là thôi nhé.}
{131}{}{Quên đi. Tôi là trư?ng t?c tương lai cơ mà. Đâu l?i có chuy?n trư?ng t?c đi nh? c? cho l?o.}
{132}{}{R?t vinh d?, thưa pháp sư th?n thánh.}
{133}{}{L?o nh? tôi nh? c? trong vư?n à? N?u v?y th? đư?c thôi.}
{134}{}{Tr? công nhé.}
{135}{hak006}{Đ?i tr? công cho m?t món quà s? khi?n con ch?ng nh?n đư?c g? c?. Ta s? trao cho con như v?y, cùng v?i bài h?c v? s? th?t v?ng mà con c?n nh?n l?nh.}
{136}{}{?n đ?y. Khu vư?n ? đâu th??}
{137}{}{L?o bi?t đ?y, m?t món quà t?t th? c?n ph?i BI?T NÓI CHO ĐÚNG!}
{138}{}{Th? th? sao tôi l?i không cho l?o bài h?c v? s? th?t v?ng và đi kh?i đây nh?? T?m bi?t.}
{139}{}{?, n?u ông thái đ? th? tôi c?ng đ?ch quan tâm. Chào nhé.}
{140}{hak006a}{N?u chúng ta nói cùng m?t t? th? li?u chúng có cùng m?t ngh?a không? M?i t? có luôn khi?n các linh h?n rung đ?ng như nhau không?}
{141}{}{? đ?y. T?t hơn r?i đ?y. Cái tôi v?a h?c đư?c là thôi kh?i c?i và ch? c?n h?i khu vư?n ? đâu.}
{142}{}{Th? th? th? t? này đi, "t?m bi?t". Nó có ngh?a là tôi đi đây.}
{143}{hak007}{H?n con ph?i nh? là khu vư?n ? phía Đông B?c ch?, đ? đ?n.}
{144}{}{Cám ơn đ? giúp.}
{145}{}{Cám ơn. Nói v?y tôi l?i hi?u đ?y.}
{146}{}{L?o dám g?i tôi là đ?n à? Th? th? tôi đéo mu?n giúp n?a đâu.}
{147}{}{Tôi s? s?m quay l?i đ? l?y công.}
{148}{hak008}{Gánh n?ng mà con mang trên m?nh gi? s? c?n n?ng hơn.}
{149}{hak009}{C?u các th?n linh phù h? cho n? l?c c?a con, C?u tinh. C?u cho hào quang c?a con chi?u r?i lên m?nh ta sau khi m?nh đ?t đư?c thanh l?c tr? l?i.}
{150}{}{Tôi coi đ?y là l?o mu?n g?p l?i sau khi tôi xong... L?o ch? c?n nói th?ng ra mà.}
{151}{}{T?m bi?t.}
{152}{hak010}{Ha! Linh h?n t? tiên s?ng trong con. H?y t?p trung b?i dư?ng b?n thân nh?m nâng cao khí l?c đ? khai m? h?ng ch?m đ?n gi?i giác ng?. D? nhiên, ph?n thư?ng s? không ch? là nh?ng đó c?a lin h?n.}
{153}{}{?n đ?y. Tôi s? quay l?i khi nào xong.}
{154}{}{V?y là tôi s? nh?n đư?c th? th?c t? g? đó à. ?n đ?y. G?p l?i l?o sau.}
{155}{}{Tôi ngh? là l?o chơi v?i m?y cái cây trong vư?n nhi?u quá r?i đ?y. Đ? tránh b? như l?o, tôi s? tránh xa kh?i cái khu vư?n đó.}
{156}{hak011}{Không th? l?ng phí hay ti?t ki?m th?i gian – chúng ta luôn s?ng ? hi?n t?i. Chính hành đ?ng là n?n t?ng xây d?ng cu?c s?ng c?a con.}
{157}{}{?, ch?c th?. Như v?a nói, tôi ph?i đi đây. T?m bi?t.}
{158}{}{L?o bi?t đ?y, nói chuy?n v?i l?o làm tôi t? h?i v? cái ? không nên l?ng phí th?i gian. Tôi bi?n đây.}
{159}{}{Ư?c g? tôi có đư?c trí tu?, ngư?i thông thái. Th? l?i cho tôi – d? nhiên là tôi s? lo vi?c đó.}
{160}{hak012}{Con có th? mang l?p v? C?u tinh, nhưng linh h?n x?u xa đang gào thét bên trong.}
{161}{}{Tôi c?u xin s? tha th?, ? đ?ng th?n thánh. Làm th? nào tôi có th? g?t r?a linh h?n m?nh?}
{162}{}{Đúng v?y, Hakunin, và l?o nên đ? khôn đ? không quên đi?u đó.}
{163}{}{Nghe l?o nói làm tôi đau đ?u v?i. Bi?n thôi.}
{164}{}{Ú ?a!}
{165}{hak013}{H?y g?t r?a linh h?n trong lúc thanh tr? ác qu? kh?i m?nh vư?n c?a ta.}
{166}{}{Nh?t đ?nh r?i, ngư?i thông thái. Tôi s? đ?n c?u s? tha th? sau khi đ? thanh t?y khu vư?n.}
{167}{}{L?o đang mu?n nói r?ng nh? c? trong vư?n là t?t cho tôi, ph?i không? ?, đư?c r?i, đ? tôi th?.}
{168}{}{Tôi thích linh h?n c?a m?nh như v?y. Chào.}
{169}{}{Tôi không x?ng đáng như v?y. Tôi s? đi đây.}
{170}{hak014}{C?u tinh, m?t l?n n?a s? hi?n di?n toàn v?n c?a con l?i mang đ?n s? phù h? c?a đ?t tr?i.}
{171}{}{Cám ơn.}
{172}{}{? l?o là tôi đ? tr? nên t?t hơn, đúng ch??}
{173}{hak015}{Đ? t?o nên cái toàn v?n c?n đ?n c?m giác tr?n v?n mà con đ? trí tu? đ? hi?u r?, C?u tinh.}
{174}{}{Ch? đ?, đ?ng nói. Tôi tr? nên t?t hơn và ông cám th?y vui, đúng ch?. Cám ơn.}
{175}{}{Ngư?i th?t là trí tu? và thánh thi?n, Đ?ng th?n thánh.}
{176}{hak017}{B?ng cách nào ta có th? ch?m đ?n linh h?n c?u tinh đây, H?t gi?ng c?a T? tiên?}
{177}{}{?, chính xác là m?nh vư?n ? đâu th??}
{178}{}{Tôi b? thương. L?o ch?a đư?c không?}
{179}{}{?, không có g?. T?m bi?t.}
{180}{hak018}{À. Con đ? mang linh h?n c?a T? tiên tr? l?i v?i th? gi?i c?ng như mang n? cư?i đ?n v?i linh h?n c?a m?t ông l?o s?p ra đi. V? v?y, ta trao cho con ch? b?t ch?a thương này. H?y nh?, chúng s? làm lu m? tâm trí trong lúc thanh t?y cơ th?.}
{181}{}{Cám ơn.}
{182}{hak018a}{Và c?n n?a, ta s? xào hoa broc cùng r? xander b?t c? lúc nào con mang c? hai đ?n cho ta. C?u cho con luôn bư?c trên con đư?ng đúng và gi? v?ng tâm h?n.}
{183}{}{Tôi có th? t?m nh?ng th? này ? đâu?}
{184}{}{Cám ơn.}
{185}{}{Tí n?a th? tôi đi m?t r?i. Gi? th? tôi hơi b?t đ?u hi?u l?o đ?y. T?m bi?t.}
{186}{hak019}{À, C?u tinh, m?nh vư?n c?a ta v?n ?n, c?a con th? sao?}
{187}{}{Tôi v?n ?n.}
{188}{}{Tôi c?n tr? thương.}
{189}{}{L?o nói m?y cái cây ? đâu th? nh??}
{190}{}{Tôi làm g? có vư?n. L?o đang nói cái đéo g? th??}
{191}{}{Tôi mu?n nh? l?o xào ít b?t ch?a thương.}
{192}{}{?, không có g?. Tôi ph?i đi đây.}
{193}{}{??}
{194}{}{Ong! Bư?m!}
{195}{hak020}{Nh?ng l?i này th?m đ?m tai khi?n ta th?t khoan khoái. Than ôi, các th?n linh đang th? th?m vào tai ta. T?m bi?t.}
{196}{}{Chào.}
{197}{}{V?n đang xào đ? à? G?p l?i l?o sau.}
{198}{hak021}{T?t c? chúng ta đ?u có m?t khu vư?n. C?u cho hành tr?nh c?a con c?ng đư?c gi?ng như làm vư?n v?y. H?y gi? g?n. Ta ph?i đi c?u nguy?n các đ?ng th?n linh đây.}
{199}{}{G?p l?i sau.}
{200}{}{Tôi ch?c là đi đâu l?o c?ng luôn l?m b?m trong đ?u. B?o tr?ng.}
{201}{hak022}{H?y nh?n v? phía B?c, C?u tinh à, và l?i đi s? m? ra.}
{202}{}{Okay. Cám ơn.}
{203}{hak023}{Ta th?y th?t vinh d? đư?c ph?c v? C?u tinh.}
{204}{hak024}{Cu?c s?ng là v?y. Hai t?o nên ba. Con s? c?n c? r? xander và hoa broc đ? ch? b?t ch?a thương.}
{205}{}{?, cám ơn.}
{206}{}{C?t.}
{207}{hak025}{C?u cho th? này là không c?n thi?t.}
{208}{}{Okay. Cám ơn.}
{209}{}{?!}
{210}{hak026}{Con ?n r?i.}
{211}{}{Cám ơn.}
{212}{}{Không có bài h?c nào? C?ng ch?ng có l?i d?y vô ngh?a nào à? L?o có ch?c là l?o v?n ?n không th??}
{213}{hak027}{Chào m?ng, C?u tinh. H?y ban cho chúng ta l?i truy?n r?ng GECK s? s?m đư?c t?m th?y. Ngôi làng đang y?u d?n, chúng ta c?n quá nhi?u, nhưng th?i gian l?i quá ng?n.}
{214}{}{N?.}
{215}{}{Và ông v?n không nói đư?c như ngư?i b?nh thư?ng. Tôi v?n đang c? đây.}
{216}{}{Tôi v?n đang t?m.}
{217}{}{Bi?n đi l?o già. Tôi đang c? h?t s?c đây.}
{218}{}{Tôi v?n đang t?m, thưa thánh nhân. Tôi hi v?ng s? s?m t?m th?y GECK.}
{219}{hak028a}{C?u cho Đ?t ti?p s?c cho bư?c chân c?a con.}
{220}{hak028b}{C?u cho Nư?c xuôi d?ng cu?c hành tr?nh c?a con.}
{221}{hak028c}{C?u cho Gió d?n đư?ng con đ?n đích.}
{222}{hak028d}{C?u cho L?a đ?t cháy mông thôi thúc con cho đ?n khi hoàn thành.}
{223}{}{Cám ơn.}
{224}{}{Cái đm?!}
{225}{}{?.}
{226}{}{H??!}
{227}{hak029}{Welcome back, Chosen. I see by your face the salvation of the GECK is not yet ours. Be tireless as the ant before our reserves run out. You are our last hope.}
{228}{}{Uh-huh.}
{229}{}{I'm trying. I'd like to see the ant covering the miles I am.}
{230}{}{I'm doing my best.}
{231}{}{I'll double my efforts, holy one. I will not let you down.}
{232}{}{Yeah, yeah. I've heard it all before.}
{233}{hak030}{Chosen - the village cries in desperation. The children are weak with hunger. Please, we cannot hold out much longer.}
{234}{}{Uh-huh.}
{235}{}{I'm trying. I'm trying! Give me a break!}
{236}{}{I'll find the GECK, holy one. You have my word.}
{237}{}{I'll do my best to find the GECK.}
{238}{hak031}{Chosen, the sands of time are but a few grains. Please. Bring the GECK soon and make the future of the village like the beach of the ocean. Quickly, before the last grain falls.}
{239}{}{Uh-huh.}
{240}{}{All right. I'm off to find it.}
{241}{}{Life's a beach, huh?}
{242}{}{I will find the GECK, holy one. I will not let our people down.}
{243}{hak032}{Chosen, the spirits of our ancestors guide me to a world of dreams that I may touch thoughts. Our village suffers without the holy GECK. Your hands hold our lives as a father holds his children.}
{244}{hak033}{Once again my spirit touches you from the void, Chosen. Our crops fail, our reserves are meager. Return to us with the GECK. Your failure is our last light.}
{245}{hak034}{Chosen. The village weakens. It is harder to touch your dreams. You must hurry or we will all...}
{246}{hak035}{Chosen? Chosen? Do you hear me? The village dies. All of our futures die, too. We have little left in both time and essence... Hurry. Hurry...}
{247}{hak101}{Chosen - the shadow of darkness arrived before you.}
{248}{}{Owwww!}
{249}{}{Chuy?n g? đ? x?y ra th??}
{250}{}{You look bad. Let me help.}
{251}{hak102}{Child of Nature, how could we put such a burden on your shoulders? (sigh) Your people have been taken.}
{252}{}{Uhh?}
{253}{hak103}{Yes. Gone. Many dark souls came, riding the metal birds like a flock of hungry chittick bugs, hiding their evil in shiny skins. }
{254}{}{Ooo! Shiny Purty!}
{255}{hak104}{No! Not shiny pretty! They kidnapped our people and took them to the southwest.}
{256}{}{Ow.}
{257}{hak105}{Yes. Great sadness and pain. I stand between worlds to tell you, Chosen. Save your people.}
{258}{}{Uh?}
{259}{hak106}{Chosen, please let my words touch you. Go southwest. South and west. Save our people. Save our people.}
{260}{}{Uh-huh..}
{261}{hak107}{Thank the ancestors. Now my soul may join the eternal song. Safe journey, Chosen.}
{262}{}{Go?}
{263}{hak108}{Go!...}
{264}{}{Bye bye.}
{265}{hak109}{Dark souls came. They took everyone.}
{266}{}{Dark souls? What do you mean?}
{267}{hak110}{A rush of wind came. On it were great dragonflies that spat flame. Evil men crawled from the beasts' bellies and brought death to our warriors.}
{268}{}{Our warriors couldn't stop them?}
{269}{hak112}{The spirit was willing, but the spearheads were weak. The evil ones burned our warriors with the lights of hell.}
{270}{}{They killed everyone?}
{271}{hak113}{All were dead or taken. My spirit returned to flesh only to reveal the truth to the Chosen.}
{272}{}{What happened to the ones taken?}
{273}{hak114}{The beasts swallowed all, then took to the winds.}
{274}{}{Uh, which way were the winds that they followed going?}
{275}{hak115}{Did you never listen when I taught you the yearly dance of the wind spirits? South, of course.}
{276}{}{Your descriptions were so vivid and powerful, great Hakunin, that I was often stricken senseless for the duration of your lessons.}
{277}{}{Oh, those winds. Of course. }
{278}{hak116}{Yes, they traveled the wind south. I overheard the dark souls speaking. They planned to rest their beasts at a place named Navarro before crossing the great basin of our earth-mother's tears.}
{279}{}{What shall I do?}
{280}{}{Basin of tears?}
{281}{hak117}{For me, nothing. Chosen, you must seek the fold of the dark ones and rescue our people.}
{282}{}{I will try.}
{283}{hak118}{You are the Chosen. You must do.}
{284}{}{Hakunin?}
{285}{}{First time I understood what you meant.}
{286}{hak120}{An ocean of tears, cried by a mother for her children.}
{287}{}{Oh, the ocean. But what shall I do?}
{288}{hak121}{A strange mist stole their minds and sent them to the land of Sleep. The evil ones walked among the dreamers, yet did not dream.}
{289}{}{R?i sau đó?}
{290}{hak122}{Too many seasons and too many wounds, Chosen. Instead, you must listen.}
{291}{}{Đư?c r?i.}
{300}{}{Those who steal carry a great burden. Remember this, Chosen One.}
{301}{}{You must now pay for your sins, Chosen One.}
