{100}{}{Trư?c m?t b?n là Hakunin, pháp sư c?a làng. L?o ta soi b?n b?ng c?p m?t thao láo, như th? đang nh?n t? m?t th? gi?i c?a riêng l?o v?y...}
{101}{}{B?n th?y Hakunin đang n?m trên m?t đ?y. L?o ta b? thương r?t n?ng.}
{102}{}{B?n th?y Hakunin. L?o ta g?n như ch?t r?i.}
{103}{}{Hakunin b? b?ng r?t n?ng. Mùi ch?ng khác nào gà rán, nh?n như mi?ng th?t băm cháy r?i, và b?n không bi?t làm th? nào mà l?o v?n c?n s?ng đư?c đ?n gi?.}
{104}{hak001}{Xin chào, C?u tinh. Sao kho?nh đ?t trư?c m?t ta l?i đư?c con d?m lên v?y?}
{105}{}{??}
{106}{}{Tôi đ?n đ? chào t?m bi?t. Tôi s?p lên đư?ng th?c hi?n nhi?m v? th?n thánh.}
{107}{}{Tôi s?p đi. Tôi hi v?ng là l?n này l?o có th? nói chuy?n như ngư?i b?nh thư?ng.}
{108}{}{L?o bú c?n quá đ? r?i đ?y. Tôi bi?n kh?i đây đây.}
{109}{}{Tôi b? thương. L?o ch?a đư?c không?}
{110}{}{Vư?n c?a l?o b? m?y cái cây t?m v?i m?c chen vào, tôi nh? s?ch chúng cho l?o r?i.}
{111}{hak001a}{H?y cho c?p m?t m? đ?c này th?y con đư?ng c?a con.}
{112}{}{??}
{113}{}{Tôi đ?n đ? chào t?m bi?t. Tôi s?p lên đư?ng th?c hi?n nhi?m v? th?n thánh.}
{114}{}{Tôi s?p đi. Tôi hi v?ng là l?n này l?o có th? nói chuy?n như ngư?i b?nh thư?ng.}
{115}{}{L?o bú c?n quá đ? r?i đ?y. Tôi bi?n kh?i đây đây.}
{116}{}{Vư?n c?a l?o b? m?y cái cây t?m v?i m?c chen vào, tôi nh? s?ch chúng cho l?o r?i.}
{117}{hak002}{M?t đ?t ngân lên ti?ng ca v? v? anh hùng giáng th?... Có l? trư?c khi đi, con có th? th? hi?n s? hào hi?p đư?c chăng?}
{118}{}{Đư?c ch?. L?o c?n g? nào?}
{119}{}{Đ? xem... L?o s? tr? công tôi th? nào?}
{120}{hak002a}{Có vô s? cách quan sát th? gi?i – đi?u mà con s? s?m h?c đư?c... Có l?, trư?c khi con hái qu? ng?t t? cây đ?i kinh nghi?m, con có th? th? hi?n s? hào hi?p chăng?}
{121}{}{Ch?ng ph?i l?o v?a m?i nh? tôi giúp sao? N?u v?y th? đư?c r?i, sao l?i không ch??}
{122}{}{Tôi s? giúp l?o, nhưng v? l?o c? huyên thuyên khó hi?u v?i nên giúp ph?i tính công đ?y.}
{123}{hak003}{Các th?n phù h? con, con đúng là m?t đ?a tr? t?t b?ng. Li?u con có th? s? d?ng tài năng đ?c bi?t và gi?i thoát cho m?nh vư?n c?a ta kh?i nh?ng cái cây c?a linh h?n h?c ám?}
{124}{}{? h?.}
{125}{}{Khôn. L?ooo. Đưa. Đau đ?u.}
{126}{hak004}{C?u cho hào quang c?a con r?i chi?u lên ta khi con xong... ?, quay l?i l?u c?a ta sau khi xong và ta s? đưa cho con đ? t?t.}
{127}{}{Ch?c.}
{128}{hak005}{Nh?ng cái cây c?a linh h?n h?c ám m?t l?n n?a l?i xâm chi?m m?nh vư?n c?a ta. Nh?ng đ?t xương này đ? già c?i sau nhi?u mùa và ta đ? tr? nên quá y?u trư?c cu?c chi?n trư?c thiên nhiên v?nh h?ng. Ta c?n con làm ngư?i b?o h?.}
{129}{}{Tôi không ngh? v?y. Tôi c?n ph?i b?t đ?u nhi?m v? ngay bây gi?.}
{130}{}{Tôi bi?t là l?o không ph?i là ngư?i x?u, nhưng tôi đau đ?u quá, nên ch?c là thôi nhé.}
{131}{}{Quên đi. Tôi là trư?ng t?c tương lai cơ mà. Đâu l?i có chuy?n trư?ng t?c đi nh? c? cho l?o.}
{132}{}{R?t vinh d?, thưa pháp sư th?n thánh.}
{133}{}{Ông nh? tôi nh? c? trong vư?n à? N?u v?y th? đư?c thôi.}
{134}{}{Tr? công nhé.}
{135}{hak006}{Đ?i tr? công cho m?t món quà s? khi?n con ch?ng nh?n đư?c g? c?. Ta s? trao cho con như v?y, cùng v?i bài h?c v? s? th?t v?ng mà con c?n nh?n l?nh.}
{136}{}{?n đ?y. Khu vư?n ? đâu th??}
{137}{}{L?o bi?t đ?y, m?t món quà t?t th? c?n ph?i BI?T NÓI CHO ĐÚNG!}
{138}{}{Th? th? sao tôi l?i không cho l?o bài h?c v? s? th?t v?ng và đi kh?i đây nh?? T?m bi?t.}
{139}{}{?, n?u ông thái đ? th? tôi c?ng đ?ch quan tâm. Chào nhé.}
{140}{hak006a}{N?u chúng ta nói cùng m?t t? th? li?u chúng có cùng m?t ngh?a không? M?i t? có luôn khi?n các linh h?n rung đ?ng như nhau không?}
{141}{}{? đ?y. T?t hơn r?i đ?y. Cái tôi v?a h?c đư?c là thôi kh?i c?i và ch? c?n h?i khu vư?n ? đâu.}
{142}{}{H?y th? t? này, "t?m bi?t". Nó có ngh?a là tôi đi đây.}
{143}{hak007}{Surely you remember it is to the northeast, foolish one.}
{144}{}{Thank you for your help.}
{145}{}{Thanks. I actually understood that.}
{146}{}{Are you calling me a fool? I don't think I want to help you, after all. }
{147}{}{I'll be back for my payment soon.}
{148}{hak008}{The burden you carry now will grow ever heavier.}
{149}{hak009}{May the gods bless your efforts, Chosen. May your aura grace my presence when the earth breathes clean again.}
{150}{}{I take it you want to see me again when I'm done... You could have just said so, you know.}
{151}{}{T?m bi?t.}
{152}{hak010}{Ha! The founder's spirit lives in you. Focus in to fortify the self to expand the greatness to enable such to touch the world. Of course, the rewards will be more than those of the spirit. }
{153}{}{Sounds good. I'll be back when I'm done.}
{154}{}{So, I'm getting an actual thing in payment. Good enough. See ya later.}
{155}{}{I think you've been playing with those plants way too much. To avoid your fate, I'm staying away from the garden.}
{156}{hak011}{Time can neither be wasted or saved- it must always be now. The actions create the fabric of your life.}
{157}{}{Uh, right. Like I said, I've got to go. Goodbye. }
{158}{}{You know, talking to you makes me wonder about that time can't be wasted idea. I'm outta here. }
{159}{}{If only I had your wisdom, wise one. Forgive me- of course I'll take care of it for you.}
{160}{hak012}{You may bear the mantle of the Chosen, but your dark soul cries from within.}
{161}{}{I beg your forgiveness, holy one. How can I cleanse my soul? }
{162}{}{That's right, Hakunin, and you'd be a real wise man not to forget it.}
{163}{}{My head aches from within listening to you. I'm gone.}
{164}{}{Booka!}
{165}{hak013}{Cleanse your soul as you would banish demons from my garden.}
{166}{}{It shall be done, wise one. I will come seek your forgiveness after I have purified your garden.}
{167}{}{You're trying to say that weeding your garden will be good for me, right? Well, okay, I'll give it a try.}
{168}{}{I kinda like my soul the way it is. Bye.}
{169}{}{I'm not worthy. I'll take my leave now.}
{170}{hak014}{Chosen, once again the wholeness of your being is like a land blessed.}
{171}{}{Thank you.}
{172}{}{You mean I'm better, right?}
{173}{hak015}{To make one whole instills a sense of fullness that you would be well to understand, Chosen.}
{174}{}{Wait, don't tell me. I'm better and you felt good doing it, right? Thanks.}
{175}{}{You are wise and kind, Holy One.}
{176}{hak017}{In what way may I touch the chosen soul, Seed of the Dweller?}
{177}{}{Uh, where exactly is your garden?}
{178}{}{Tôi b? thương. L?o ch?a đư?c không?}
{179}{}{Oh, nothing. Goodbye.}
{180}{hak018}{Ahh. You return the spirit of the Dweller to the world and bring a smile to the soul of an old man in passing. For this, I give you powders of healing. Remember, they fog the mind as they cleanse the body.}
{181}{}{Thank you.}
{182}{hak018a}{And also, will I mix the broc flower with the xander root together whenever you bring both to me. May your pathways be true and your heart follow suit. }
{183}{}{Where can I find these things?}
{184}{}{Thank you.}
{185}{}{I'm almost sorry to go. I can just about understand you now. Bye.}
{186}{hak019}{Ah, Chosen, my garden is well- how is yours?}
{187}{}{I'm all right.}
{188}{}{I need healing.}
{189}{}{Where did you say the plants were?}
{190}{}{I don't have a garden- what the hell are you talking about this time?}
{191}{}{I'd like you to make some healing powder for me.}
{192}{}{Oh, never mind. I've got to go.}
{193}{}{Ow?}
{194}{}{Ooog! Bak!}
{195}{hak020}{The pleasure of these words fills me. Alas, the gods whisper for my ear. Goodbye.}
{196}{}{Chào.}
{197}{}{Still mixing the herbs, huh? See you later.}
{198}{hak021}{We all have gardens. May your journeys act as tending. Be well. I must seek audience with the gods now.}
{199}{}{See ya.}
{200}{}{I'm betting you carry your audience with you wherever you go. Be well.}
{201}{hak022}{Look to the north, Chosen, and the way will be open.}
{202}{}{Okay. Thanks.}
{203}{hak023}{I am honored to serve the Chosen.}
{204}{hak024}{Such is life. Two creates a third. You will need both xander root and broc flower for the healing powder.}
{205}{}{Oh. Thanks}
{206}{}{Poo.}
{207}{hak025}{May this be of no use.}
{208}{}{Okay. Thanks.}
{209}{}{Uh!}
{210}{hak026}{You are well.}
{211}{}{Thank you.}
{212}{}{No lessons? No incomprehensible speeches? You sure you're okay?}
{213}{hak027}{Welcome, Chosen. Bless us with words that the GECK will be found soon. Our village ails, our need is great, our time, short.}
{214}{}{Nuh.}
{215}{}{And your ability to speak normally, non-existent. I'm still trying.}
{216}{}{I'm on it. }
{217}{}{Get off my back, old man. I'm doing the best I can.}
{218}{}{I'm still looking, holy one. I hope to have the GECK soon.}
{219}{hak028a}{May the Earth cushion the steps you must take.}
{220}{hak028b}{May the Waters soothe your journey.}
{221}{hak028c}{May the Wind guide you to your goal.}
{222}{hak028d}{May the Fire toast your bottom until you get this done.}
{223}{}{Cám ơn.}
{224}{}{Say what?!}
{225}{}{?.}
{226}{}{Huh?!}
{227}{hak029}{Welcome back, Chosen. I see by your face the salvation of the GECK is not yet ours. Be tireless as the ant before our reserves run out. You are our last hope.}
{228}{}{Uh-huh.}
{229}{}{I'm trying. I'd like to see the ant covering the miles I am.}
{230}{}{I'm doing my best.}
{231}{}{I'll double my efforts, holy one. I will not let you down.}
{232}{}{Yeah, yeah. I've heard it all before.}
{233}{hak030}{Chosen - the village cries in desperation. The children are weak with hunger. Please, we cannot hold out much longer.}
{234}{}{Uh-huh.}
{235}{}{I'm trying. I'm trying! Give me a break!}
{236}{}{I'll find the GECK, holy one. You have my word.}
{237}{}{I'll do my best to find the GECK.}
{238}{hak031}{Chosen, the sands of time are but a few grains. Please. Bring the GECK soon and make the future of the village like the beach of the ocean. Quickly, before the last grain falls.}
{239}{}{Uh-huh.}
{240}{}{All right. I'm off to find it.}
{241}{}{Life's a beach, huh?}
{242}{}{I will find the GECK, holy one. I will not let our people down.}
{243}{hak032}{Chosen, the spirits of our ancestors guide me to a world of dreams that I may touch thoughts. Our village suffers without the holy GECK. Your hands hold our lives as a father holds his children.}
{244}{hak033}{Once again my spirit touches you from the void, Chosen. Our crops fail, our reserves are meager. Return to us with the GECK. Your failure is our last light.}
{245}{hak034}{Chosen. The village weakens. It is harder to touch your dreams. You must hurry or we will all...}
{246}{hak035}{Chosen? Chosen? Do you hear me? The village dies. All of our futures die, too. We have little left in both time and essence... Hurry. Hurry...}
{247}{hak101}{Chosen - the shadow of darkness arrived before you.}
{248}{}{Owwww!}
{249}{}{Chuy?n g? đ? x?y ra th??}
{250}{}{You look bad. Let me help.}
{251}{hak102}{Child of Nature, how could we put such a burden on your shoulders? (sigh) Your people have been taken.}
{252}{}{Uhh?}
{253}{hak103}{Yes. Gone. Many dark souls came, riding the metal birds like a flock of hungry chittick bugs, hiding their evil in shiny skins. }
{254}{}{Ooo! Shiny Purty!}
{255}{hak104}{No! Not shiny pretty! They kidnapped our people and took them to the southwest.}
{256}{}{Ow.}
{257}{hak105}{Yes. Great sadness and pain. I stand between worlds to tell you, Chosen. Save your people.}
{258}{}{Uh?}
{259}{hak106}{Chosen, please let my words touch you. Go southwest. South and west. Save our people. Save our people.}
{260}{}{Uh-huh..}
{261}{hak107}{Thank the ancestors. Now my soul may join the eternal song. Safe journey, Chosen.}
{262}{}{Go?}
{263}{hak108}{Go!...}
{264}{}{Bye bye.}
{265}{hak109}{Dark souls came. They took everyone.}
{266}{}{Dark souls? What do you mean?}
{267}{hak110}{A rush of wind came. On it were great dragonflies that spat flame. Evil men crawled from the beasts' bellies and brought death to our warriors.}
{268}{}{Our warriors couldn't stop them?}
{269}{hak112}{The spirit was willing, but the spearheads were weak. The evil ones burned our warriors with the lights of hell.}
{270}{}{They killed everyone?}
{271}{hak113}{All were dead or taken. My spirit returned to flesh only to reveal the truth to the Chosen.}
{272}{}{What happened to the ones taken?}
{273}{hak114}{The beasts swallowed all, then took to the winds.}
{274}{}{Uh, which way were the winds that they followed going?}
{275}{hak115}{Did you never listen when I taught you the yearly dance of the wind spirits? South, of course.}
{276}{}{Your descriptions were so vivid and powerful, great Hakunin, that I was often stricken senseless for the duration of your lessons.}
{277}{}{Oh, those winds. Of course. }
{278}{hak116}{Yes, they traveled the wind south. I overheard the dark souls speaking. They planned to rest their beasts at a place named Navarro before crossing the great basin of our earth-mother's tears.}
{279}{}{What shall I do?}
{280}{}{Basin of tears?}
{281}{hak117}{For me, nothing. Chosen, you must seek the fold of the dark ones and rescue our people.}
{282}{}{I will try.}
{283}{hak118}{You are the Chosen. You must do.}
{284}{}{Hakunin?}
{285}{}{First time I understood what you meant.}
{286}{hak120}{An ocean of tears, cried by a mother for her children.}
{287}{}{Oh, the ocean. But what shall I do?}
{288}{hak121}{A strange mist stole their minds and sent them to the land of Sleep. The evil ones walked among the dreamers, yet did not dream.}
{289}{}{R?i sau đó?}
{290}{hak122}{Too many seasons and too many wounds, Chosen. Instead, you must listen.}
{291}{}{Đư?c r?i.}
{300}{}{Those who steal carry a great burden. Remember this, Chosen One.}
{301}{}{You must now pay for your sins, Chosen One.}
