{100}{}{Trước mặt bạn là Hakunin, pháp sư của làng. Lão ta soi bạn bằng cặp mắt thao láo, như thể đang nhìn từ một thế giới của riêng lão vậy...}
{101}{}{Bạn thấy Hakunin đang nằm trên mặt đấy. Lão ta bị thương rất nặng.}
{102}{}{Bạn thấy Hakunin. Lão ta gần như chết rồi.}
{103}{}{Hakunin bị bỏng rất nặng. Mùi chẳng khác nào gà rán, nhìn như miếng thịt băm cháy rụi, và bạn không biết làm thế nào mà lão vẫn còn sống được đến giờ.}
{104}{hak001}{Xin chào, Cứu tinh. Sao khoảnh đất trước mặt ta lại được con dẫm lên vậy?}
{105}{}{Ờ?}
{106}{}{Tôi đến để chào tạm biệt. Tôi sắp lên đường thực hiện nhiệm vụ thần thánh.}
{107}{}{Tôi sắp đi. Tôi hi vọng là lần này lão có thể nói chuyện như người bình thường.}
{108}{}{Lão bú cần quá độ rồi đấy. Tôi biến khỏi đây đây.}
{109}{}{Tôi bị thương. Lão chữa được không?}
{110}{}{Vườn của lão bị mấy cái cây tởm vãi mọc chen vào, tôi nhổ sạch chúng cho lão rồi.}
{111}{hak001a}{Hãy cho cặp mắt mờ đục này thấy con đường của con.}
{112}{}{Ờ?}
{113}{}{Tôi đến để chào tạm biệt. Tôi sắp lên đường thực hiện nhiệm vụ thần thánh.}
{114}{}{Tôi sắp đi. Tôi hi vọng là lần này lão có thể nói chuyện như người bình thường.}
{115}{}{Lão bú cần quá độ rồi đấy. Tôi biến khỏi đây đây.}
{116}{}{Vườn của lão bị mấy cái cây tởm vãi mọc chen vào, tôi nhổ sạch chúng cho lão rồi.}
{117}{hak002}{Mặt đất ngân lên tiếng ca về vị anh hùng giáng thế... Có lẽ trước khi đi, con có thể thể hiện sự hào hiệp được chăng?}
{118}{}{Được chứ. Lão cần gì nào?}
{119}{}{Để xem... Lão sẽ trả công tôi thế nào?}
{120}{hak002a}{Có vô số cách quan sát thế giới – điều mà con sẽ sớm học được... Có lẽ, trước khi con hái quả ngọt từ cây đời kinh nghiệm, con có thể thể hiện sự hào hiệp chăng?}
{121}{}{Chẳng phải lão vừa mới nhờ tôi giúp sao? Nếu vậy thì được rồi, sao lại không chứ?}
{122}{}{Tôi sẽ giúp lão, nhưng vì lão cứ huyên thuyên khó hiểu vãi nên giúp phải tính công đấy.}
{123}{hak003}{Các thần phù hộ con, con đúng là một đứa trẻ tốt bụng. Liệu con có thể sử dụng tài năng đặc biệt và giải thoát cho mảnh vườn của ta khỏi những cái cây của linh hồn hắc ám?}
{124}{}{Ừ hứ.}
{125}{}{Khôn. Lãooo. Đưa. Đau đầu.}
{126}{hak004}{Cầu cho hào quang của con rọi chiếu lên ta khi con xong... Ồ, quay lại lều của ta sau khi xong và ta sẽ đưa cho con đồ tốt.}
{127}{}{Chậc.}
{128}{hak005}{Những cái cây của linh hồn hắc ám một lần nữa lại xâm chiếm mảnh vườn của ta. Những đốt xương này đã già cỗi sau nhiều mùa và ta đã trở nên quá yếu trước cuộc chiến trước thiên nhiên vĩnh hằng. Ta cần con làm người bảo hộ.}
{129}{}{Tôi không nghĩ vậy. Tôi cần phải bắt đầu nhiệm vụ ngay bây giờ.}
{130}{}{Tôi biết là lão không phải là người xấu, nhưng tôi đau đầu quá, nên chắc là thôi nhé.}
{131}{}{Quên đi. Tôi là trưởng tộc tương lai cơ mà. Đâu lại có chuyện trưởng tộc đi nhổ cỏ cho lão.}
{132}{}{Rất vinh dự, thưa pháp sư thần thánh.}
{133}{}{Lão nhờ tôi nhổ cỏ trong vườn à? Nếu vậy thì được thôi.}
{134}{}{Trả công nhé.}
{135}{hak006}{Đòi trả công cho một món quà sẽ khiến con chẳng nhận được gì cả. Ta sẽ trao cho con như vậy, cùng với bài học về sự thất vọng mà con cần nhận lãnh.}
{136}{}{Ổn đấy. Khu vườn ở đâu thế?}
{137}{}{Lão biết đấy, một món quà tốt thì cần phải BIẾT NÓI CHO ĐÚNG!}
{138}{}{Thế thì sao tôi lại không cho lão bài học về sự thất vọng và đi khỏi đây nhỉ? Tạm biệt.}
{139}{}{Ồ, nếu ông thái độ thì tôi cũng đếch quan tâm. Chào nhé.}
{140}{hak006a}{Nếu chúng ta nói cùng một từ thì liệu chúng có cùng một nghĩa không? Mỗi từ có luôn khiến các linh hồn rung động như nhau không?}
{141}{}{Ồ đấy. Tốt hơn rồi đấy. Cái tôi vừa học được là thôi khỏi cãi và chỉ cần hỏi khu vườn ở đâu.}
{142}{}{Thế thì thử từ này đi, "tạm biệt". Nó có nghĩa là tôi đi đây.}
{143}{hak007}{Hẳn con phải nhớ là khu vườn ở phía Đông Bắc chứ, đồ đần.}
{144}{}{Cám ơn đã giúp.}
{145}{}{Cám ơn. Nói vậy tôi lại hiểu đấy.}
{146}{}{Lão dám gọi tôi là đần à? Thế thì tôi đéo muốn giúp nữa đâu.}
{147}{}{Tôi sẽ sớm quay lại để lấy công.}
{148}{hak008}{Gánh nặng mà con mang trên mình giờ sẽ còn nặng hơn.}
{149}{hak009}{Cầu các thần linh phù hộ cho nỗ lực của con, Cứu tinh. Cầu cho hào quang của con chiếu rọi lên mình ta sau khi mảnh đất được thanh lọc trở lại.}
{150}{}{Tôi coi đấy là lão muốn gặp lại sau khi tôi xong... Lão chỉ cần nói thẳng ra mà.}
{151}{}{Tạm biệt.}
{152}{hak010}{Ha! Linh hồn tổ tiên sống trong con. Hãy tập trung bồi dưỡng bản thân nhằm nâng cao khí lực để khai mở hòng chạm đến giới giác ngộ. Dĩ nhiên, phần thưởng sẽ không chỉ là những đó của lin hồn.}
{153}{}{Ổn đấy. Tôi sẽ quay lại khi nào xong.}
{154}{}{Vậy là tôi sẽ nhận được thứ thực tế gì đó à. Ổn đấy. Gặp lại lão sau.}
{155}{}{Tôi nghĩ là lão chơi với mấy cái cây trong vườn nhiều quá rồi đấy. Để tránh bị như lão, tôi sẽ tránh xa khỏi cái khu vườn đó.}
{156}{hak011}{Không thể lãng phí hay tiết kiệm thời gian – chúng ta luôn sống ở hiện tại. Chính hành động là nền tảng xây dựng cuộc sống của con.}
{157}{}{Ờ, chắc thế. Như vừa nói, tôi phải đi đây. Tạm biệt.}
{158}{}{Lão biết đấy, nói chuyện với lão làm tôi tự hỏi về cái ý không nên lãng phí thời gian. Tôi biến đây.}
{159}{}{Ước gì tôi có được trí tuệ, người thông thái. Thứ lỗi cho tôi – dĩ nhiên là tôi sẽ lo việc đó.}
{160}{hak012}{Con có thể mang lớp vỏ Cứu tinh, nhưng linh hồn xấu xa đang gào thét bên trong.}
{161}{}{Tôi cầu xin sự tha thứ, ồ đấng thần thánh. Làm thế nào tôi có thể gột rửa linh hồn mình?}
{162}{}{Đúng vậy, Hakunin, và lão nên đủ khôn để không quên điều đó.}
{163}{}{Nghe lão nói làm tôi đau đầu vãi. Biến thôi.}
{164}{}{Ú òa!}
{165}{hak013}{Hãy gột rửa linh hồn trong lúc thanh trừ ác quỷ khỏi mảnh vườn của ta.}
{166}{}{Nhất định rồi, người thông thái. Tôi sẽ đến cầu sự tha thứ sau khi đã thanh tẩy khu vườn.}
{167}{}{Lão đang muốn nói rằng nhổ cỏ trong vườn là tốt cho tôi, phải không? Ồ, được rồi, để tôi thử.}
{168}{}{Tôi thích linh hồn của mình như vậy. Chào.}
{169}{}{Tôi không xứng đáng như vậy. Tôi sẽ đi đây.}
{170}{hak014}{Cứu tinh, một lần nữa sự hiện diện toàn vẹn của con lại mang đến sự phù hộ của đất trời.}
{171}{}{Cám ơn.}
{172}{}{Ý lão là tôi đã trở nên tốt hơn, đúng chứ?}
{173}{hak015}{Để tạo nên cái toàn vẹn cần đến cảm giác trọn vẹn mà con đủ trí tuệ để hiểu rõ, Cứu tinh.}
{174}{}{Chờ đã, đừng nói. Tôi trở nên tốt hơn và ông cám thấy vui, đúng chứ. Cám ơn.}
{175}{}{Người thật là trí tuệ và thánh thiện, Đấng thần thánh.}
{176}{hak017}{Bằng cách nào ta có thể chạm đến linh hồn cứu tinh đây, Hạt giống của Tổ tiên?}
{177}{}{Ờ, chính xác là mảnh vườn ở đâu thế?}
{178}{}{Tôi bị thương. Lão chữa được không?}
{179}{}{Ồ, không có gì. Tạm biệt.}
{180}{hak018}{À. Con đã mang linh hồn của Tổ tiên trở lại với thế giới cũng như mang nụ cười đến với linh hồn của một ông lão sắp ra đi. Vì vậy, ta trao cho con chỗ bột chữa thương này. Hãy nhớ, chúng sẽ làm lu mờ tâm trí trong lúc thanh tẩy cơ thể.}
{181}{}{Cám ơn.}
{182}{hak018a}{Và còn nữa, ta sẽ xào hoa broc cùng rễ xander bất cứ lúc nào con mang cả hai đến cho ta. Cầu cho con luôn bước trên con đường đúng và giữ vững tâm hồn.}
{183}{}{Tôi có thể tìm những thứ này ở đâu?}
{184}{}{Cám ơn.}
{185}{}{Tí nữa thì tôi đi mất rồi. Giờ thì tôi hơi bắt đầu hiểu lão đấy. Tạm biệt.}
{186}{hak019}{À, Cứu tinh, mảnh vườn của ta vẫn ổn, của con thì sao?}
{187}{}{Tôi vẫn ổn.}
{188}{}{Tôi cần trị thương.}
{189}{}{Lão nói mấy cái cây ở đâu thế nhỉ?}
{190}{}{Tôi làm gì có vườn. Lão đang nói cái đéo gì thế?}
{191}{}{Tôi muốn nhờ lão xào ít bột chữa thương.}
{192}{}{Ồ, không có gì. Tôi phải đi đây.}
{193}{}{Ớ?}
{194}{}{Ong! Bướm!}
{195}{hak020}{Những lời này thấm đẫm tai khiến ta thật khoan khoái. Than ôi, các thần linh đang thì thầm vào tai ta. Tạm biệt.}
{196}{}{Chào.}
{197}{}{Vẫn đang xào đồ à? Gặp lại lão sau.}
{198}{hak021}{Tất cả chúng ta đều có một khu vườn. Cầu cho hành trình của con cũng được giống như làm vườn vậy. Hãy giữ gìn. Ta phải đi cầu nguyện các đấng thần linh đây.}
{199}{}{Gặp lại sau.}
{200}{}{Tôi chắc là đi đâu lão cũng luôn lẩm bẩm trong đầu. Bảo trọng.}
{201}{hak022}{Hãy nhìn về phía Bắc, Cứu tinh à, và lối đi sẽ mở ra.}
{202}{}{Okay. Cám ơn.}
{203}{hak023}{Ta thấy thật vinh dự được phục vụ Cứu tinh.}
{204}{hak024}{Cuộc sống là vậy. Hai tạo nên ba. Con sẽ cần cả rễ xander và hoa broc để chế bột chữa thương.}
{205}{}{Ồ, cám ơn.}
{206}{}{Cứt.}
{207}{hak025}{Cầu cho thứ này là không cần thiết.}
{208}{}{Okay. Cám ơn.}
{209}{}{Ừ!}
{210}{hak026}{Con ổn rồi.}
{211}{}{Cám ơn.}
{212}{}{Không có bài học nào? Cũng chẳng có lời dạy vô nghĩa nào à? Lão có chắc là lão vẫn ổn không thế?}
{213}{hak027}{Chào mừng, Cứu tinh. Hãy ban cho chúng ta lời truyền rằng GECK sẽ sớm được tìm thấy. Ngôi làng đang yếu dần, chúng ta cần quá nhiều, nhưng thời gian lại quá ngắn.}
{214}{}{Nồ.}
{215}{}{Và ông vẫn không nói được như người bình thường. Tôi vẫn đang cố đây.}
{216}{}{Tôi vẫn đang tìm.}
{217}{}{Biến đi lão già. Tôi đang cố hết sức đây.}
{218}{}{Tôi vẫn đang tìm, thưa thánh nhân. Tôi hi vọng sẽ sớm tìm thấy GECK.}
{219}{hak028a}{Cầu cho Đất tiếp sức cho bước chân của con.}
{220}{hak028b}{Cầu cho Nước xuôi dòng cuộc hành trình của con.}
{221}{hak028c}{Cầu cho Gió dẫn đường con đến đích.}
{222}{hak028d}{Cầu cho Lửa đốt cháy mông thôi thúc con cho đến khi hoàn thành.}
{223}{}{Cám ơn.}
{224}{}{Cái đm?!}
{225}{}{Ừ.}
{226}{}{Hả?!}
{227}{hak029}{Chào mừng trở lại, Cứu tinh. Ta có thể thấy qua biểu cảm của con là sự cứu rỗi của GECK vẫn còn xa vời. Hãy như con kiến lao động không mỏi trước khi kho lương của chúng ta cạn kiệt. Con là niềm hi vọng cuối cùng của chúng ta.}
{228}{}{Uh-huh.}
{229}{}{Tôi đang cố đây. Tôi muốn xem có con kiến nào đi được quãng đường như tôi không.}
{230}{}{Tôi đang cố hết sức.}
{231}{}{Tôi sẽ cố gấp đôi, thưa thánh nhân. Tôi sẽ không khiến người phiền não.}
{232}{}{Ờ ờ. Tôi đã nghe mấy lời này rồi.}
{233}{hak030}{Cứu tinh – Ngôi làng đang kêu cứu trong tuyệt vọng. Đám trẻ đói lả cả người. Làm ơn đi, chúng ta không còn giữ được lâu hơn nữa đâu.}
{234}{}{Uh-huh.}
{235}{}{Tôi đang cố. Tôi đang cố đây! Vội thế đéo nào được!}
{236}{}{Tôi sẽ tìm GECK, thưa thánh nhân. Tôi hứa đấy.}
{237}{}{Tôi sẽ cố hết sức đi tìm GECK.}
{238}{hak031}{Cứu tinh, đụn cát thời gian chỉ còn lại vài hạt. Làm ơn đi. Hãy sớm đưa GECK về và biến tương lai của ngôi làng giống như bãi bờ của biển. Nhanh lên, trước khi hạt cát cuối cùng rơi xuống.}
{239}{}{Uh-huh.}
{240}{}{Được rồi. Tôi đi tìm đây.}
{241}{}{Cuộc sống chẳng khác nào bãi chịch, hể?}
{242}{}{Tôi sẽ đi tìm GECK, thưa thánh nhân. Tôi sẽ không để mọi người thất vọng đâu.}
{243}{hak032}{Cứu tinh, các linh hồn tổ tiên đã dẫn lối cho ta đến thế giới giấc mơ, nơi ta có thể chạm vào ý thức. Ngôi làng sẽ tàn lụi nếu thiếu GECK thần thánh. Con đang nắm giữ vận mệnh của chúng ta trong tay chẳng khác nào người cha bế ẵm đứa con thơ.}
{244}{hak033}{Linh hồn của ta một lần nữa liên lạc với con từ cõi hư không, Cứu tinh. Mùa màng đang thất bát, lương thực dự trữ chẳng còn mấy. Hãy mang GECK về cho chúng ta. Thất bại của con sẽ khiến chúng ta chìm vào đêm đen.}
{245}{hak034}{Cứu tinh. Ngôi làng đang suy kiệt. Càng lúc càng khó bước vào giấc mơ của con. Con phải nhanh lên, nếu không thì mọi người...}
{246}{hak035}{Cứu tinh? Cứu tinh? Con có nghe thấy gì không? Ngôi làng mà chết thì toàn bộ tương lai của chúng ta cũng không còn. Chúng ta đang kiệt quệ cả thời gian lẫn tinh thần... Nhanh lên. Nhanh lên...}
{247}{hak101}{Cứu tinh – bóng đen của hắc ám đã đến trước con.}
{248}{}{Ớ ớ ớ!}
{249}{}{Chuyện gì đã xảy ra thế?}
{250}{}{Trông lão tệ quá. Để tôi giúp.}
{251}{hak102}{Đứa con của Thiên nhiên, làm sao mà chúng ta lại đặt gánh nặng này lên vai con chứ? (thở dài) Mọi người đã bị bắt đi rồi.}
{252}{}{Hở?}
{253}{hak103}{Đúng vậy. Đi rồi. Rất nhiều linh hồn hắc ám đã đến, cưỡi trên những con chim sắt như bầy côn trùng đói hung hăng, che kín sự hung ác bằng lớp vỏ sáng bóng.}
{254}{}{Ồ! Sáng bóng đợp!}
{255}{hak104}{Không! Không sáng đẹp! Chúng đã bắt cóc mọi người và đưa họ về phía Tây Nam.}
{256}{}{Ớ.}
{257}{hak105}{Đúng vậy. Nỗi đau đớn tận cùng. Ta đứng chờ ở giữa hai thế giới để nói với con, Cứu tinh. Hãy cứu mọi người.}
{258}{}{Ừ?}
{259}{hak106}{Cứu tinh, làm ơn hãy nghe lời ta. Đi về phía Tây Nam. Tây và Nam. Cứu mọi người. Cứu mọi người.}
{260}{}{Uh-huh...}
{261}{hak107}{Cám ơn tổ tiên. Giờ thì linh hồn ta có thể hòa vào khúc ca vĩnh hằng rồi. Lên đường an toàn, Cứu tinh.}
{262}{}{Đi?}
{263}{hak108}{Đi đi!...}
{264}{}{Chào nhé.}
{265}{hak109}{Linh hồn hắc ám đã đến. Chúng bắt mọi người.}
{266}{}{Linh hồn hắc ám? Ông nói gì thế?}
{267}{hak110}{Một con gió ập đến. Cùng với đó là những con chuồn chuồn bự phun lửa. Những kẻ xấu xa nhảy ra từ bụng của con quái vật và mang diệt vong đến cho những chiến binh của chúng ta.}
{268}{}{Các chiến binh của chúng ta không thể ngăn chúng sao?}
{269}{hak112}{Tinh thần hừng hực, nhưng ngọn giáo lại yếu đuối. Những kẻ hung tàn đã thiêu đốt các chiến binh bằng thứ ánh sáng địa ngục.}
{270}{}{Chúng đã giết tất cả mọi người?}
{271}{hak113}{Tất cả đều đã chết hoặc bị bắt đi. Linh hồn của ta đã trở lại thân xác chỉ để khai mở sự thật cho con, Cứu tinh.}
{272}{}{Chuyện gì đã xảy ra với những người bị bắt đi?}
{273}{hak114}{Bầy quái vật đã nuốt tất cả, sau đó cưỡi lên cơn gió.}
{274}{}{Ờ, con gió mà chúng cưỡi lên thổi theo hướng nào?}
{275}{hak115}{Con có bao giờ nghe lời ta dạy trong những buổi nhảy múa của gió thần hằng năm không vậy? Dĩ nhiên là về phía Nam rồi.}
{276}{}{Lời của lão luôn hào hùng và mạnh mẽ, Hakunin vĩ đại à, đến mức tôi thường đờ ra trong các buổi giảng của lão.}
{277}{}{Ồ, mấy cơn gió đó. Dĩ nhiên rồi.}
{278}{hak116}{Đúng vậy, chúng cưỡi theo gió Nam. Ta đã nghe lũ linh hồn hắc ám đó nói chuyện. Chúng dự định sẽ cho đám quái vật nghỉ tại một nơi gọi là Navarro trước khi vượt qua đại hải chất chứa nước mắt của mẹ trái đất.}
{279}{}{Tôi cần làm gì?}
{280}{}{Đại hải nước mắt?}
{281}{hak117}{Với ta, chẳng gì cả. Cứu tinh, con phải đi tìm vết đuôi của bè lũ hắc ám và giải cứu mọi người.}
{282}{}{Tôi sẽ thử.}
{283}{hak118}{Con là Cứu tinh. Con phải làm vậy.}
{284}{}{Hakunin?}
{285}{}{Đây là lần đầu tôi hiểu lão nói gì đấy.}
{286}{hak120}{Biển nước mắt, do người mẹ khóc về những đứa con của mình.}
{287}{}{Ồ, là biển. Nhưng tôi cần làm gì?}
{288}{hak121}{Một màn sương kì lạ xâm chiếm tâm hồn và gửi họ đến vùng đất của Giấc ngủ. Những kẻ xấu xa đi giữa những người say giấc, nhưng lại không hề mơ màng.}
{289}{}{Rồi sau đó?}
{290}{hak122}{Quá nhiều mùa và thương quá nặng. Cứu tinh. Con phải nghe đây.}
{291}{}{Được rồi.}
{300}{}{Những kẻ ăn trộm phải vác nặng trên vai. Hãy nhớ lấy, Cứu tinh.}
{301}{}{Giờ thì con phải trả giá cho tội lỗi của mình, Cứu tinh.}
