{100}{}{Bạn thấy một người ở nhờ.}
{101}{}{Bạn thấy Bill, người ở nhờ.}
{102}{}{Bạn thấy một gã trung niên mặc quần áo cũ mèm.}
{103}{}{Xin lỗi, người lạ. Tôi không có thời gian trò chuyện đâu.}
{104}{}{Này, tôi đã nói là không có thời gian tán nhảm rồi. Đi chỗ khác đi.}
{105}{}{Cám ơn đã giúp đỡ Rebeccca. Làm tốt lắm.}
{106}{}{Để tôi yên. Tôi có làm gì cậu đâu.}
{107}{}{Rồi, rồi. Tôi đi.}
