{100}{}{Bạn thấy một phụ nữ trẻ trong bộ quần áo rách rưới.}
{101}{}{Bạn thấy Dalia.}
{102}{}{Bạn thấy một phụ nữ trẻ trong bộ quần áo rách rưới. Cô ta trông có vẻ rất cảnh giác, và cẩn thận
để mắt đến mọi thứ xung quanh.}
{103}{}{Chào. Tôi là Dalia. Tôi có thể giúp gì nhỉ?}
{104}{}{Không có gì, chỉ chào thôi.}
{105}{}{Ừ, ai cô?}
{106}{}{Cô làm gì ở đây?}
{107}{}{Cô giống lính gác thế.}
{108}{}{Ngộ đi giờ.}
{109}{}{Chỉ chào thôi.}
{110}{}{Ông là ai?}
{111}{}{Đang làm gì thế?}
{112}{}{Trông như cô đang gác lối nhỏ này.}
{113}{}{Tôi đi giờ đây.}
{114}{}{Ồ, chào cô. Rất tiếc, nhưng tôi phải đi bây giờ.}
{115}{}{Ngộ muốn chuyện.}
{116}{}{Được, ngộ đi.}
{117}{}{Tôi muốn nói chuyện.}
{118}{}{Chào.}
{119}{}{Tôi nói tôi là Dalia. Này, tôi không muốn càu nhàu, nhưng hiện tại tôi không muốn nói chuyện với ai cả. Được chứ?}
{120}{}{Okay, tạm biệt.}
{121}{}{Thêm chút thôi.}
{122}{}{Rồi tôi sẽ đi.}
{123}{}{Tôi chỉ muốn hỏi một câu thôi.}
{124}{}{Tôi thích không khí trong lành, tôi thích cây cối nên tôi đứng đây. Có vấn đề gì không?}
{125}{}{Xin lỗi, ngộ đi.}
{126}{}{Không, không sao. Ngộ hỏi cô thứ này.}
{127}{}{Tôi không có vấn đề gì, nhưng tôi đang thắc mắc một chuyện.}
{128}{}{Xin lỗi, tôi sẽ đi đây.}
{129}{}{Không, tôi chẳng gác lối đi nào cả. Chẳng có cái mẹ gì đáng canh gác ở cái lỗ này. Tôi nói rồi,
tôi đang hít khí trong lành. Giờ thì đi đi.}
{130}{}{Cô nói hay. Ngộ nói thêm.}
{131}{}{Xin lỗi ngộ phiền. Ngộ đi.}
{132}{}{Nhưng chúng ta đang dở câu chuyện vui mà, sao lại dừng?}
{133}{}{Chắc là đến lúc tôi phải đi rồi.}
{134}{}{Ôi không, lại là con ruồi đến lẩn quẩn à. Nghe này, tôi không có gì để nói cả. Biến đi!}
{135}{}{}
{136}{}{}
{137}{}{Tôi không muốn đôi co làm gì. Để tôi yên.}
{138}{}{}
{139}{}{}
{140}{}{Chào. Tôi là Dalia. Tôi có thể giúp gì nhỉ?}
{141}{}{Người đi qua đây? Vội?}
{142}{}{Không có gì.}
{143}{}{Không có gì.}
{144}{}{Cô có nhìn thấy ai vội vã đi qua đây không?}
{145}{}{Tôi thấy người đi qua đây hằng ngày. Tôi không quá để ý đến họ.}
{146}{}{Ngộ không có giờ cho cô nhảm.}
{147}{}{Ồ, okay.}
{148}{}{Mạng gái gặp nguy. Gái trẻ. Con gái ai đó. Vui lòng giúp?}
{149}{}{Tôi không có thời gian nghe cô nói nhảm.}
{150}{}{Được rồi, tạm biệt.}
{151}{}{Này, một cô gái trẻ đang gặp nguy hiểm. Con gái của một bà mẹ đang lo phát sốt lên. Liệu cô
có thể giúp tôi không?}
{152}{}{Tôi đéo quan tâm cái cứt chó... tôi xin lỗi. Tôi chỉ là người được thuê để đứng đây và canh gác
lối đi này. Ngoài ra tôi không biết chuyện gì đang diễn ra quanh đây. Tôi cũng từng có con gái,
nhưng... ừ, có một gã đã qua đây. Tôi để hắn đi qua vì hắn làm đúng kí hiệu... giống như câu anh
vừa nói vậy. Đi đi. Tôi biến khỏi đây đây.}
{153}{}{Cám ơn. Ngộ không quên này, Dalia.}
{154}{}{Cám ơn. Tôi sẽ không quên ơn này đâu, Dalia.}
{155}{}{Vậy thì cút mẹ đi và để tôi yên!}
{156}{}{Đã xong.}
{157}{}{Vậy thì cút mẹ đi và để tôi yên!}
{158}{}{Đã xong.}
