{100}{}{Bạn thấy một ông già.}
{101}{}{Bạn thấy Darion, tướng cướp nhóm Khan tân.}
{102}{}{Bạn thấy một ông già có mái tóc hoa râm mỏng tang. Trông ông ta có vẻ săn chắc so với tuổi.}
{103}{}{Vậy là mày cuối cùng cũng đến đây rồi. Vị cứu tinh của những người bị áp bức, người trừng trị
kẻ xấu, biểu tượng hi vọng của nhân loại. Đúng là đồ đần! Nào, trước khi mày bắt đầu mở mồm
ra lải nhải thì bố mày muốn nói rằng đm câm mồm đi. Vào thẳng vấn đề và kết thúc nào. Chó điên, giết!}
{104}{}{Đã xong.}
