{100}{}{Bạn thấy một kẻ cướp Khan.}
{101}{}{Bạn thấy một kẻ cướp Khan.}
{102}{}{Bạn thấy một người to lớn mặc giáp, đeo vũ khí và rất thái độ. Hẳn phải là một Khan.}
{103}{}{Cái gì... Tao đâu có quen mày. Mày là đứa đéo nào thế?}
{104}{}{Tao có ID đây này! Để tao cho xem.}
{105}{}{Tên là... ờ... Pat. Nhân viên mới.}
{106}{}{Được rồi, đồ lươn lẹo. Cố lên nào.}
{107}{}{Ồ đúng rồi. Xin lỗi. Tự nhiên quên mất mày. Giờ thì tiếp tục đi lo việc đi.}
{108}{}{Này, tao đâu có ngu như mày chứ.}
{109}{}{Mày vẫn chưa chết à? Cứt thật.}
{110}{}{Mẹ kiếp, Darion trả công có tí tẹo đéo bõ công đứng đây cả ngày ngáp ruồi.}
{111}{}{Đôi khi tao đứng và nghĩ về đm nó đéo gì cả.}
{112}{}{Tao đéo quan tâm đm nó nghĩ gì.}
{113}{}{Đéo biết là vui nhất... chắc thế.}
{114}{}{Khi nào thì lại có đoàn lữ hành đây? Tao ngứa tay lắm rồi.}
{115}{}{Muốn nghỉ thế nhỉ.}
{116}{}{Bà nó chứ, chỗ con đĩ Chrissy đấy đạp vào giờ vẫn còn đau.}
{117}{}{Này, chỗ này chẳng có ma mới bao giờ nhỉ.}
{118}{}{Vậy là bao giờ thì chúng ta mới cút khỏi cái chỗ củ lìn này thế?}
{119}{}{Không biết mày nghĩ sao, nhưng tao thấy như cứt.}
{120}{}{Chẳng có cục cứt nào để bắn ở đây cả.}
{121}{}{Cái phòng rửa cặc đâu rồi?}
{122}{}{Này, chỗ này đéo thấy ai nghỉ ngơi gì. Đéo có luật lệ gì cả à?}
{123}{}{Nên lập lại trật tự như hồi xưa thôi.}
{124}{}{Mẹ nó, không biết ngày xưa Tổng thống làm cái chó gì nhỉ?}
{125}{}{Tao chắc là làm Tổng thống thì muốn cái đéo gì cũng có.}
{126}{}{Tao nghĩ là ông già tao sẽ tự hào về tao lắm. Tiếc là tao giết ổng rồi.}
{127}{}{ĐM TAO GHÉT CHUỘT! GHÉT VL VCL!}
{128}{}{Này, giáp mới à? Mày đánh giá bộ giáp mới ra sao?}
{129}{}{Đm cái hầm hôi vl. Mày có thấy ghét cái mùi này không?}
{130}{}{Ê, chúng ta phải để mắt đến thằng lìn nào ấy nhỉ?}
{131}{}{Tất cả những gì tao làm là đứng, đứng và đứng.}
{132}{}{Tao nghĩ chúng ta nên thịt toàn bộ lũ tầng trên và cút mẹ nó khỏi cái chỗ này thôi.}
{133}{}{Chuột cắn chim mày à mà kêu lắm thế?}
{134}{}{Mày có từng thử xé chân ra khỏi con chuột bao giờ chưa?}
{135}{}{Tao thích súng, yeah! SÚNG TAO THÍCH! SÚNG: TAO CỰC, CỰC KÌ THÍCH!}
{136}{}{Này, có ai đang nghe bố mày nói không thế?}
{137}{}{Ồ thôi kệ, nói cho khỏi khô mồm thôi.}
{138}{}{Này, có ai nhớ trong Trà đá Long Island có cái lìn gì không?}
{139}{}{Ờ, vodka, rum, tequila, triple sec, chanh và Nuka.}
{140}{}{Ê nhìn này -- đèn sáng rồi. Cái đm...}
{141}{}{Darion có nói là sẽ sửa đèn. Cứ tưởng đùa hóa ra thật.}
{142}{}{Chắc là cái máy phát điện không tự sửa đâu nhỉ?}
{143}{}{Tự nhiên thấy mọi thứ cứ thế đéo nào ý. Jesus, chỗ này trông như cứt!}
{144}{}{Ồ, sáng vãi. Điều khiển cho tối đi chỗ nào ấy nhỉ?}
{145}{}{Chết đi!}
