{100}{}{Bạn thấy một người ở nhờ.}
{101}{}{Bạn thấy John, người ở mượn.}
{102}{}{Bạn thấy một người đàn ông trung niên mặc quần áo cũ.}
{103}{}{Xin lỗi, người lạ, tôi không có thời gian để nói chuyện.}
{104}{}{Sao không nói?}
{105}{}{Okay, lượn.}
{106}{}{Được rồi, gặp lại sau.}
{107}{}{Chờ đã. Sao ông không nói chuyện với tôi?}
{108}{}{Chúng tôi là một cộng đồng khép kín ở đây và không muốn gặp rắc rối hoặc bị người từ bên ngoài
làm phiền. Vui lòng để chúng tôi yên.}
{109}{}{Okay.}
{110}{}{Chào... và tạm biệt.}
{111}{}{Cám ơn vì tất cả những gì cậu đã làm. Tôi xin lỗi vì đã phớt lờ trước đó.}
{112}{}{Biến đi, đồ chó!}
{113}{}{Mẹ nó, ghét mấy chuyện này thế không biết.}
{114}{}{Đỡ này! Đấy, thấy chưa.}
