{100}{}{Bạn thấy một người đàn ông lùn đang cầm sách trong tay.}
{101}{}{Bạn thấy Bác sĩ Jones, thầy thuốc.}
{102}{}{Bạn thấy một người đàn ông lùn với quyển sách có tên "Vậy là bạn muốn làm Bác sĩ".}
{103}{}{Chào, tôi là Bác sĩ Jones. Hãy gọi tôi là bác sĩ. Tôi giúp gì được nhỉ?}
{104}{}{Bị đao. Sửa không?}
{105}{}{Bị ngứa. Sửa không?}
{106}{}{Ngộ què, sửa không?}
{107}{}{Muốn hỏi. Okay?}
{108}{}{Xin lỗi, ngộ đi.}
{109}{}{Tôi bị thương. Ông giúp tôi được không?}
{110}{}{Tôi thấy bị bệnh. Ông giúp tôi được không?}
{111}{}{Tôi bị gãy tay chân. Ông giúp tôi được không?}
{112}{}{Tôi muốn hỏi một vài câu.}
{113}{}{Chỉ chào thôi.}
{114}{}{Ồ, dĩ nhiên rồi. Đây, tôi sẽ tiêm cho cậu mũi này -- sẽ hơi xót một xíu -- giờ thì dán cái
băng này, rồi xong, cậu ổn rồi.}
{115}{}{Ngộ cám ơn. Tạm biệt.}
{116}{}{Cám ơn, Bác sĩ. Tôi thấy khá hơn nhiều rồi.}
{117}{}{Ồ, dĩ nhiên rồi. Đây, cậu sẽ cần uống thứ này -- tất cả chứ, tôi biết vị hơi tởm. Rồi, giờ
thì nằm lên chiếc giường đằng kia, sáng mai tôi sẽ đánh thức cậu.}
{118}{}{Ngộ thấy ổn. Tạm biệt.}
{119}{}{Cám ơn Bác sĩ, chữa tài thật đấy.}
{120}{}{Tôi rất tiếc nhưng tôi không có đủ thiết bị cần thiết để tiến hành phẫu thuật. Tôi khuyên cậu nên
đi tới một thành phố lớn và gặp bác sĩ phẫu thuật. Thử Thành phố Vault xem. Đi về phía Bắc chỗ này.}
{121}{}{Okay. Tạm biệt.}
{122}{}{Được rồi. Dù sao cũng cám ơn.}
{123}{}{Muốn hỏi gì thế?}
{124}{}{Ông làm Darion?}
{125}{}{Ông đi đây nếu muốn?}
{126}{}{Ông biết gì về Darion?}
{127}{}{Sao ông ở đây?}
{128}{}{Ông bảo Darion có chóa?}
{129}{}{Ngộ đi giờ.}
{130}{}{Ông có làm việc cho Darion không?}
{131}{}{Ông có thể rời khỏi chỗ này nếu muốn không?}
{132}{}{Ông có thể nói về Darion được không?}
{133}{}{Sao ông lại đến chỗ này vậy?}
{134}{}{Ông nói rằng Darion có một con chó à?}
{135}{}{Thanks for the information. I'll be heading out now.}
{136}{}{Well, yes and no. It's not by choice. I'm a prisoner here. Darion is getting up there in years
 and he needs a dedicated physician to look after him. The Khans keep me here for his needs. I'd rather
 be here for the people in the town above. They have no medical help at all, and there is a lot I can
 do to aid them.}
{137}{}{Okay. Need know more.}
{138}{}{Cám ơn. Tạm biệt.}
{139}{}{That's very commendable of you.}
{140}{}{I see. I'll be going now.}
{141}{}{They're squatters! Let 'em die. Get on with your life.}
{142}{}{No, I'm pretty much trapped here. I can't even leave to refill my medical supplies. Darion
 sends out for anything I need.}
{143}{}{Me got it. Go now.}
{144}{}{Need ask more.}
{145}{}{I guess you just aren't a trustworthy enough person to be allowed freedom.}
{146}{}{All right. I'm sorry, but I have to get going.}
{147}{}{I'm sorry to hear that.}
{148}{}{Darion is a mental case, plain and simple. He's got more spooks in his head than his dog has
 fleas. As far as I can figure it, he was a member of another gang called the Khans. They kidnapped
 this girl, Tandi, and held her for ransom. Her father didn't take kindly to that, and hired some merc
 to get her back. Darion was the only one to come out alive.}
{149}{}{Uh... what you said.}
{150}{}{Got go now.}
{151}{}{Uh-huh. Well, I'll be leaving now.}
{152}{}{Wow; I'm impressed with your knowledge.}
{153}{}{Sounds like my kind of guy.}
{154}{}{I was kidnapped. I was traveling from Vault City to New Reno for a well-deserved vacation. Went
 to bed one night and woke up bound and gagged the next morning. A week or so later, I was here. Been
 here ever since.}
{155}{}{Ugh.}
{156}{}{Thanks. Me be leave now.}
{157}{}{The weak are often the prey of the strong.}
{158}{}{I'm sorry to hear that.}
{159}{}{Interesting, but I need to get going.}
{160}{}{Yeah, he's got a dog. Personally, I think it's the meanest, most vile creature on the face of
 the earth. It seems to love Darion, though, so I guess it can't be all that bad.}
{161}{}{Me ask more.}
{162}{}{Uh, bye.}
{163}{}{I see. Well, thanks for the warning.}
{164}{}{Ah. Well, I've got to go.}
{165}{}{I'll not help someone like you. Go away.}
{166}{}{Okay, well, you take care, and come back if you need anything.}
{167}{}{Đã xong.}
{168}{}{Now he's paranoid. He believes that Tandi is out to get him. He's obsessed with revenge, and he
 wants Tandi dead. He's riddled with guilt 'cause he hid and lived, rather than dying with his
 gang... and the list goes on and on.}
