{100}{}{Bạn thấy một kẻ cướp Khan.}
{101}{}{Bạn thấy Phil, một lính gác Khan.}
{102}{}{Bạn thấy một gã trai khó nhằn mặc bộ giáp thép. Hắn ta có vũ trang đầy đủ.}
{103}{}{Tao có thể bắn mày chết luôn, nhưng tao tự hỏi là mày có thể mở mồm phun ra câu gì.}
{104}{}{Ngộ tìm gián điệp. Đi lối này.}
{105}{}{Ngộ tìm cô gái mất tích. Biết đâu đi tìm?}
{106}{}{Ngộ đến đây lạc. Đi giờ.}
{107}{}{Mẹ mày. Ngộ bắn mày chết.}
{108}{}{Ờ, chúng ta có thể nói chuyện được không?}
{109}{}{Tôi đang tìm người nghe lén nào đã đi lối này.}
{110}{}{Tôi đang đi tìm một cô gái bị mất tích. Có thấy cô ta không?}
{111}{}{Xin lỗi, đi nhầm đường xíu. Tôi đi đây.}
{112}{}{Chổng đít lên để tao nhồi đạn vào mông nào, củ lìn.}
{113}{}{Tôi thấy là chúng ta có thể nói chuyện như hai người văn minh đấy.}
{114}{}{À, là bố mày đấy. Giờ tìm thấy rồi thì sao?}
{115}{}{Sao cậu nghe Rebecca?}
{116}{}{Giờ ngộ biết không bắn nhầm người. Cám ơn!}
{117}{}{Không có gì, ngộ đi giờ.}
{118}{}{Sao cậu lại đi nghe lén Rebecca?}
{119}{}{Chỉ muốn chắc chắn là tôi bắn đúng người thôi. Cám ơn, chúc một ngày tốt lành!}
{120}{}{Hừm. Không có gì, chắc là tôi sẽ đi giờ đây.}
{121}{}{Tao đéo thể tin là mày nghĩ mày có thể chui vào đây để được trả lời câu hỏi đâu đấy! Ồ, đm,
đằng nào thì mày cũng sắp tỏi còn tao đang thấy hài hước. Bọn tao nhốt con bé của mụ ta ở phòng
trong và thi thoảng vào vui vẻ với con bé. Con mụ Rebecca đó đang cố tìm con bé, nên chúng ta
để mắt đến mụ ta để đảm bảo là mụ ta không vào được chỗ này.}
{122}{}{Cậu có vấn đề đầu. Ngộ sửa bằng cách cắt đầu.}
{123}{}{Vui vẻ với cô gái là gì?}
{124}{}{Ồ, vậy à. Ngộ đi giờ.}
{125}{}{Cậu đúng là đồ cún bệnh hoạn. Chắc là tôi sẽ cho cậu ngủ với giun ngay bây giờ.}
{126}{}{Được rồi, cứ cười đi còn tôi sẽ đi giờ đây.}
{127}{}{Hãy đưa cô gái ra đây và tất cả chúng ta đều còn sống mà rời khỏi đây.}
{128}{}{Cứ nghĩ về việc đó trong lúc chết đi, đồ đần.}
{129}{}{}
{130}{}{}
{131}{}{Tại sao bố mày lại phải làm vậy?}
{132}{}{Điều đó tốt cho linh hồn vĩnh hằng của cậu.}
{133}{}{Vì tôi có thể mang điều mà cậu sợ nhất đến đấy. Giờ thì thả cô gái ra hoặc đón nhận sự
đau đớn đi.}
{134}{}{Bởi vì nếu chúng ta đánh nhau thì một người sẽ phải chết. Tôi cũng không muốn chết chẳng khác
gì cậu, thế nên hãy kết thúc trong hòa bình. Được chứ?}
{135}{}{Câm cái mồm lại.}
{136}{}{}
{137}{}{}
{138}{}{Lời thách thức hay đấy. Tôi nhận.}
{139}{}{}
{140}{}{}
{141}{}{Hừm... tôi... ờ, okay. Đây là chìa khóa vào buồng; cô ta ở phòng sau của căn lều. Hãy đưa cô ta
ra ngoài nhưng đừng có trở lại. Nếu tôi mà thấy lần nữa thì để xem ai sống ai chết đấy.}
{142}{}{Để xem ai sống mà rời khỏi đây nào.}
{143}{}{Cám ơn, cậu đã làm điều đúng đấy.}
{144}{}{Cách duy nhất để cậu ra khỏi đây là nằm trong hòm, chân ra trước.}
{145}{}{}
{146}{}{}
{147}{}{Ý mày là con bé bị nhốt ở trong mà bọn tao đang chơi ấy hả? Không, chưa thấy bao giờ.}
{148}{}{Cậu có vấn đề đầu. Ngộ sửa bằng cách cắt đầu.}
{149}{}{Vui vẻ với cô gái là gì?}
{150}{}{Ồ. Ngộ đi giờ.}
{151}{}{Cậu đúng là đồ cún bệnh hoạn. Chắc là tôi sẽ cho cậu ngủ với giun ngay bây giờ.}
{152}{}{Được rồi, cứ cười đi còn tôi sẽ đi giờ đây.}
{153}{}{Hãy đưa cô gái ra đây và tất cả chúng ta đều còn sống mà rời khỏi đây.}
{154}{}{Vậy là mày đã trở lại. Để xem ai sẽ sống nào.}
{155}{}{Bọn tao đã giết con đũy Chrissy rồi, giờ đến lượt mày phải chết!}
