{100}{}{Bạn thấy một phụ nữ có tuổi.}
{101}{}{Bạn thấy Rebecca.}
{102}{}{Bạn thấy một phụ nữ có tuổi. Dù cho bà ta có vẻ đã sống trong cơ cực, nhưng vẫn không bị mất
đi vẻ đẹp tự nhiên.}
{103}{}{Chào, tôi là Rebecca. Chúng ta có thể nói chuyện riêng được không?}
{104}{}{Nói chuyện gì?}
{105}{}{Sao lại cần nói chuyện riêng?}
{106}{}{Okay.}
{107}{}{Không. Ngộ đi.}
{108}{}{Xin lỗi, không có hứng.}
{109}{}{Bà có việc gì muốn nói với tôi?}
{110}{}{Được chứ, chúng ta có thể đến chỗ vắng nào đây?}
{111}{}{Sao lại cần riêng tư thế?}
{112}{}{(thì thầm) Con gái tôi bị mất tích và tôi cần người giúp tìm con bé. Nhưng tôi không thể nói
chuyện ở đây. Liệu chúng ta có thể đi đến chỗ nào vắng vẻ được không?}
{113}{}{Okay.}
{114}{}{Sao lại cần nói chuyện riêng?}
{115}{}{Không, ngộ đi.}
{116}{}{Được rồi, đi thôi.}
{117}{}{Sao lại cần riêng tư thế?}
{118}{}{Khỏi đi, tôi không muốn liên can.}
{119}{}{(thì thầm) Cậu có thể nghĩ tôi bị điên nhưng tôi cảm thấy mình bị theo dõi suốt. Việc này khiến
tôi hơi lo lắng và thấy khó chịu.}
{120}{}{Okay, chúng ta đi riêng.}
{121}{}{Không có thời gian để bị điên đâu.}
{122}{}{Được rồi; chúng ta có thể nói chuyện ở đâu?}
{123}{}{Xin lỗi, tôi không muốn nghe chuyện này.}
{124}{}{Cám ơn; chúng ta có thể đi đến lều của tôi.}
{125}{}{Okay.}
{126}{}{Chúng ta có thể nói chuyện ở đó.}
{127}{}{Okay, có vấn đề gì?}
{128}{}{Ngộ muốn hỏi trước.}
{129}{}{Okay, vậy có gì quan trọng thế?}
{130}{}{Tôi có mấy câu muốn hỏi trước.}
{131}{}{Tôi có cô con gái tên là Chrissy tính hơi nghịch một chút. Con bé thích chạy khắp nơi, đi khám phá
và luôn chọc mũi vào mọi thứ. Tuy vậy Chrissy là một cô bé ngoan. Con bé không gây rắc rối gì,
luôn về nhà đúng giờ và chứng tỏ mình là một cô gái hiểu chuyện. Tôi hầu như để con bé được tự do.
Tuần trước Chrissy không về nhà. Tôi đã đi hỏi xung quanh và chẳng ai thấy hay nghe tin gì của con bé cả.
Tôi đã thử tự đi tìm, nhưng Zeke, ông ta... như kiểu thị trưởng ở đây... đã cản tôi. Ông ta bảo tôi tự đi tìm thì
không an toàn; ông ta sẽ cho người đi tìm. Nhưng họ cũng chẳng thấy gì, và nói có thể đám buôn nô lệ đã
bắt mất con bé rồi.}
{132}{}{Không, không muốn tham gia.}
{133}{}{Cần nghĩ trước khi quyết định.}
{134}{}{Ok, gần đây ngộ làm anh hùng.}
{135}{}{Xin lỗi, không có hứng.}
{136}{}{Con cần nghĩ về việc đó.}
{137}{}{Được rồi, Rebecca. Tôi sẽ cố giúp.}
{138}{}{Nếu giúp thì tôi sẽ được gì?}
{139}{}{Muốn biết gì nào?}
{140}{}{Có chuyện gì thế?}
{141}{}{Ai chủ?}
{142}{}{Ngộ cố tìm Vault 13. Bà biết đâu không?}
{143}{}{Nói về vault.}
{144}{}{Nói về Darion.}
{145}{}{Cám ơn. Chúng ta nói vấn đề bà?}
{146}{}{Chuyện gì đang diễn ra ở đây thế?}
{147}{}{Ai là người đứng đầu ở đây?}
{148}{}{Tôi đang đi tìm Vault 13. Bà có biết gì không?}
{149}{}{Hãy nói cho tôi về căn hầm.}
{150}{}{Vậy hãy nói cho tôi biết về Darion.}
{151}{}{Cám ơn Rebecca. Giờ hãy nói về vấn đề của bà.}
{152}{}{Chúng tôi gọi nơi này là "Ở mượn" vì đây là nơi người vô gia cư từ nhiều thành phố trú ngụ. Tuy
không nhiều nhưng đó là tất cả những gì chúng tôi có. Có một thành phố gọi là NCR về phía Tây.
Họ biết về chúng tôi một thời gian rồi, nhưng không bao giờ giúp đỡ hay cản trở gì cả. Đột nhiên giờ họ
nhận đây là đất của tổ tiên họ và muốn lấy lại.}
{153}{}{Okay.}
{154}{}{Ở đây họ muốn gì?}
{155}{}{Hiểu rồi.}
{156}{}{Ở đây có gì mà họ lại muốn đến vậy?}
{157}{}{Ồ... có một căn hầm ở đây; tôi nghĩ là số 15. Họ muốn tìm lấy bất kì công nghệ cũ nào
có thể vẫn còn ở dưới đó.}
{158}{}{À, ngộ hiểu.}
{159}{}{Tôi biết là dưới đó phải có thứ gì đó khác ngoài lũ ăn hại đái khai kia.}
{160}{}{Hiểu rồi.}
{161}{}{Hóa ra là vậy. Cám ơn bà nhiều. Tôi vẫn còn muốn hỏi thêm mấy câu nữa.}
{162}{}{Đó là Zeke. Ông ta lo mọi thứ ở đây. Cậu có thể tìm thấy ông ta trong tòa nhà đằng kia.
::chỉ về phía Đông Bắc::}
{163}{}{Cám ơn. Hỏi thêm.}
{164}{}{Cám ơn. Tôi muốn hỏi thêm mấy câu nữa.}
{165}{}{Tôi xin lỗi, tôi không biết. Chắc là nên hỏi ở NCR. Gần đây họ quan tâm đến mấy 
căn hầm lắm.}
{166}{}{Okay, ngộ làm.}
{167}{}{Được rồi.}
{168}{}{Ồ... chúng tôi đáng lẽ không được nói về chuyện này, nhưng vì tôi đang nhờ cậu... Darion đang
sửa chữa căn hầm. Ông ta là người giúp chúng tôi. Sau khi nó hoạt động hoàn toàn trở lại, chúng tôi 
có thể chuyển vào để tránh khỏi lũ cướp, đám buôn nô lệ và tương tự thế. Mới nhất thì ông ta đã
khôi phục được hệ thống cấp nước và đồ ăn, nhưng chỉ có vậy.}
{169}{}{Ngộ hiểu. Cần biết thêm.}
{170}{}{Tôi cần hỏi thêm.}
{171}{}{Thực ra tôi cũng không biết nhiều lắm. Darion luôn ẩn thân và không bao giờ rời khỏi hầm. Nếu
cần nói gì thì ông ta sẽ nói qua Zeke. Tôi chỉ mới gặp ông ta một lần, và có vẻ là người tốt.}
{172}{}{Okay.}
{173}{}{Mấy gã quân tử đến cuối mới ra tay. Không biết lão ta muốn làm gì?}
{174}{}{Hiểu rồi.}
{175}{}{Được rồi. Bà đã giúp nhiều lắm.}
{176}{}{Tôi chẳng biết đưa gì cho cậu ngoài sự cảm kích vô bờ bến.}
{177}{}{Vậy là quá đủ rồi. Tôi sẽ giúp.}
{178}{}{Sẽ cần nhiều hơn thế để được tôi giúp đấy.}
{179}{}{Cái quái gì thế, tôi sẽ giúp.}
{180}{}{Cám ơn nhiều lắm. Tôi biết lấy gì để trả ơn này của cậu. Tôi sẽ chờ ở đây cho đến khi...
Ê, vừa có người ngoài kia nghe lén chúng ta! Tôi thấy bóng của họ trên lều. Chúng chạy đi theo
lối đó! ::chỉ phía Đông Bắc:: Chắc chắn là chúng đã nghe được mọi chuyện rồi!}
{181}{}{Ngộ dừng, không chạy mất!}
{182}{}{Bà không lo, ngộ tìm cô gái.}
{183}{}{Ồ ồ.}
{184}{}{Tôi sẽ cố đi ngăn chúng.}
{185}{}{Họ sẽ không ngăn được tôi đi tìm con gái bà đâu.}
{186}{}{Ồ, chuyện thường thôi.}
{187}{}{Làm ơn đi chỗ khác đi.}
{188}{}{Cậu đã nghĩ thông suốt chưa?}
{189}{}{Ngộ hỏi câu.}
{190}{}{Chưa, đang nghĩ.}
{191}{}{Không, nhưng tôi vẫn sẽ xem xét mọi thứ.}
{192}{}{Tôi muốn hỏi thêm mấy câu nữa.}
{193}{}{Cậu đã đổi ý chưa? Cậu sẽ giúp tôi chứ?}
{194}{}{Xin lỗi, không.}
{195}{}{Ngộ giúp.}
{196}{}{Ừ, tôi sẽ giúp.}
{197}{}{Cậu đúng là người đã cứu con gái tôi. Tôi biết lấy gì để trả ơn cho cậu. Cám ơn nhé. Vui lòng chờ ở đây,
tôi cần nói chuyện với Chrissy rồi tôi sẽ nói chuyện với cậu.}
{198}{}{Cậu đã cứu con gái tôi. Tôi biết lấy gì để trả ơn cho cậu. Cám ơn nhé. Vui lòng
chờ ở đây, tôi cần nói chuyện với Chrissy rồi tôi sẽ nói chuyện với cậu.}
{199}{}{Okay.}
{200}{}{Con gái tôi đã kể hết mọi chuyện cho tôi. Thật khó tin là Darion lại là một con quái vật như vậy
sau tất cả những gì ông ta đã làm cho chúng tôi. Và biết rằng chúng tôi đang giúp hắn ta che giấu hành vi
ăn cướp nữa. Tôi có thể đảm bảo là chúng tôi sẽ không tiếp tục giúp hắn nữa. Tôi đã nói chuyện với Zeke,
và ông ta muốn gặp cậu. Cậu nên đến gặp ông ta ngay.}
{201}{}{Thật khó tin là Darion lại là một con quái vật như vậy sau tất cả những gì ông ta đã làm cho chúng tôi.
Và biết rằng chúng tôi đang giúp hắn ta che giấu hành vi ăn cướp nữa. Tôi có thể đảm bảo là chúng tôi sẽ
không tiếp tục giúp hắn nữa. Tôi sẽ nói chuyện với Zeke và giải thích mọi chuyện. Tôi chắc là ông ta sẽ muốn
gặp cậu. Cậu nên đến gặp ông ta sau.}
{202}{}{Cám ơn.}
{203}{}{Tôi hi vọng là cậu sẽ sớm tìm thấy Chrissy.}
{204}{}{Ngộ đang tìm.}
{205}{}{Tôi sẽ tiếp tục tìm kiếm con gái bà.}
{206}{}{Cám ơn về mọi thứ cậu đã làm giúp tôi.}
{207}{}{Tôi không thể giải thích tại sao, nhưng tôi không tin là lũ buôn nô lệ đã bắt con bé. Tôi có cảm giác
khó chịu rằng có chuyện gì đó đang diễn ra. Và rồi cả cảm giác đang bị theo dõi nữa. Tôi luôn cảm thấy
như vậy sau khi nói chuyện với Zeke về Chrissy. Tôi cần ai đó giúp tôi đi tìm con gái. Cậu sẽ giúp tôi chứ,
làm ơn đi?}
{208}{}{Họ liên tục cử người đến đây để thử yêu cầu chúng tôi rời khỏi nhà, nhưng họ không hiểu là
chúng tôi không còn nơi nào khác để đi. Chúng tôi không có các kĩ năng cần thiết để tự tồn tại
nếu rời khỏi đây.}
{209}{}{Cậu biết đấy, thật hài hước là họ tự nhận có thể sửa được thứ phức tạp như vậy nhưng lại không sửa
nổi mấy cái đèn. Cả cái hốc đấy cắm toàn đuốc. Dù sao thì Darion cũng không muốn ai biết về chuyện gì
đang diễn ra dưới hầm. Ông ta sợ rằng ai đó sẽ lấy đi tất cả nếu lộ ra. Vì vậy, chúng tôi được lệnh phải
đuổi tất cả những ai đến đây -- nhất là từ NCR.}
