{100}{}{Bạn thấy một phụ nữ có tuổi.}
{101}{}{Bạn thấy Rebecca.}
{102}{}{Bạn thấy một phụ nữ có tuổi. Dù cho bà ta có vẻ đã sống trong cơ cực, nhưng vẫn không bị mất
đi vẻ đẹp tự nhiên.}
{103}{}{Chào, tôi là Rebecca. Chúng ta có thể nói chuyện riêng được không?}
{104}{}{Nói chuyện gì?}
{105}{}{Sao lại cần nói chuyện riêng?}
{106}{}{Okay.}
{107}{}{Không. Ngộ đi.}
{108}{}{Xin lỗi, không có hứng.}
{109}{}{Bà có việc gì muốn nói với tôi?}
{110}{}{Được chứ, chúng ta có thể đến chỗ vắng nào đây?}
{111}{}{Sao lại cần riêng tư thế?}
{112}{}{(thì thầm) Con gái tôi bị mất tích và tôi cần người giúp tìm con bé. Nhưng tôi không thể nói
chuyện ở đây. Liệu chúng ta có thể đi đến chỗ nào vắng vẻ được không?}
{113}{}{Okay.}
{114}{}{Sao lại cần nói chuyện riêng?}
{115}{}{Không, ngộ đi.}
{116}{}{Được rồi, đi thôi.}
{117}{}{Sao lại cần riêng tư thế?}
{118}{}{Khỏi đi, tôi không muốn liên can.}
{119}{}{(thì thầm) Cậu có thể nghĩ tôi bị điên nhưng tôi cảm thấy mình bị theo dõi suốt. Việc này khiến
tôi hơi lo lắng và thấy khó chịu.}
{120}{}{Okay, chúng ta đi riêng.}
{121}{}{Không có thời gian để bị điên đâu.}
{122}{}{Được rồi; chúng ta có thể nói chuyện ở đâu?}
{123}{}{Xin lỗi, tôi không muốn nghe chuyện này.}
{124}{}{Cám ơn; chúng ta có thể đi đến lều của tôi.}
{125}{}{Okay.}
{126}{}{Chúng ta có thể nói chuyện ở đó.}
{127}{}{Okay, có vấn đề gì?}
{128}{}{Ngộ muốn hỏi trước.}
{129}{}{Okay, vậy có gì quan trọng thế?}
{130}{}{Tôi có mấy câu muốn hỏi trước.}
{131}{}{Tôi có cô con gái tên là Chrissy tính hơi nghịch một chút. Con bé thích chạy khắp nơi, đi khám phá
và luôn chọc mũi vào mọi thứ. Tuy vậy Chrissy là một cô bé ngoan. Con bé không gây rắc rối gì,
luôn về nhà đúng giờ và chứng tỏ mình là một cô gái hiểu chuyện. Tôi hầu như để con bé được tự do.
Tuần trước Chrissy không về nhà. Tôi đã đi hỏi xung quanh và chẳng ai thấy hay nghe tin gì của con bé cả.
Tôi đã thử tự đi tìm, nhưng Zeke, ông ta... như kiểu thị trưởng ở đây... đã cản tôi. Ông ta bảo tôi tự đi tìm thì
không an toàn; ông ta sẽ cho người đi tìm. Nhưng họ cũng chẳng thấy gì, và nói có thể đám buôn nô lệ đã
bắt mất con bé rồi.}
{132}{}{Không, không muốn tham gia.}
{133}{}{Cần nghĩ trước khi quyết định.}
{134}{}{Ok, gần đây ngộ làm anh hùng.}
{135}{}{Xin lỗi, không có hứng.}
{136}{}{Con cần nghĩ về việc đó.}
{137}{}{Được rồi, Rebecca. Tôi sẽ cố giúp.}
{138}{}{Nếu giúp thì tôi sẽ được gì?}
{139}{}{Muốn biết gì nào?}
{140}{}{Có chuyện gì thế?}
{141}{}{Ai chủ?}
{142}{}{Ngộ cố tìm Vault 13. Bà biết đâu không?}
{143}{}{Nói về vault.}
{144}{}{Nói về Darion.}
{145}{}{Cám ơn. Chúng ta nói vấn đề bà?}
{146}{}{Chuyện gì đang diễn ra ở đây thế?}
{147}{}{Ai là người đứng đầu ở đây?}
{148}{}{Tôi đang đi tìm Vault 13. Bà có biết gì không?}
{149}{}{Hãy nói cho tôi về căn hầm.}
{150}{}{Vậy hãy nói cho tôi biết về Darion.}
{151}{}{Cám ơn Rebecca. Giờ hãy nói về vấn đề của bà.}
{152}{}{Chúng tôi gọi nơi này là "Ở mượn" vì đây là nơi người vô gia cư từ nhiều thành phố trú ngụ. Tuy
không nhiều nhưng đó là tất cả những gì chúng tôi có. Có một thành phố gọi là NCR về phía Tây.
Họ biết về chúng tôi một thời gian rồi, nhưng không bao giờ giúp đỡ hay cản trở gì cả. Đột nhiên giờ họ
nhận đây là đất của tổ tiên họ và muốn lấy lại.}
{153}{}{Okay.}
{154}{}{Ở đây họ muốn gì?}
{155}{}{Hiểu rồi.}
{156}{}{Ở đây có gì mà họ lại muốn đến vậy?}
{157}{}{Ồ... có một căn hầm ở đây; tôi nghĩ là số 15. Họ muốn tìm lấy bất kì công nghệ cũ nào
có thể vẫn còn ở dưới đó.}
{158}{}{À, ngộ hiểu.}
{159}{}{Tôi biết là dưới đó phải có thứ gì đó khác ngoài lũ ăn hại đái khai kia.}
{160}{}{Hiểu rồi.}
{161}{}{Hóa ra là vậy. Cám ơn bà nhiều. Tôi vẫn còn muốn hỏi thêm mấy câu nữa.}
{162}{}{Đó là Zeke. Ông ta lo mọi thứ ở đây. Cậu có thể tìm thấy ông ta trong tòa nhà đằng kia.
::chỉ về phía Đông Bắc::}
{163}{}{Cám ơn. Hỏi thêm.}
{164}{}{Cám ơn. Tôi muốn hỏi thêm mấy câu nữa.}
{165}{}{Tôi xin lỗi, tôi không biết. Chắc là nên hỏi ở NCR. Gần đây họ quan tâm đến mấy 
căn hầm lắm.}
{166}{}{Okay, ngộ làm.}
{167}{}{Được rồi.}
{168}{}{Ồ... chúng tôi đáng lẽ không được nói về chuyện này, nhưng vì tôi đang nhờ cậu... Darion đang
sửa chữa căn hầm. Ông ta là người giúp chúng tôi. Sau khi nó hoạt động hoàn toàn trở lại, chúng tôi 
có thể chuyển vào để tránh khỏi lũ cướp, đám buôn nô lệ và tương tự thế. Mới nhất thì ông ta đã
khôi phục được hệ thống cấp nước và đồ ăn, nhưng chỉ có vậy.}
{169}{}{Ngộ hiểu. Cần biết thêm.}
{170}{}{Tôi cần hỏi thêm.}
{171}{}{Thực ra tôi cũng không biết nhiều lắm. Darion luôn ẩn thân và không bao giờ rời khỏi hầm. Nếu
cần nói gì thì ông ta sẽ nói qua Zeke. Tôi chỉ mới gặp ông ta một lần, và có vẻ là người tốt.}
{172}{}{Okay.}
{173}{}{Mấy gã quân tử đến cuối mới ra tay. Không biết lão ta muốn làm gì?}
{174}{}{Hiểu rồi.}
{175}{}{Được rồi. Bà đã giúp nhiều lắm.}
{176}{}{Tôi chẳng biết đưa gì cho cậu ngoài sự cảm kích vô bờ bến.}
{177}{}{That's more than enough. I'll help you.}
{178}{}{It'll take more than that to buy my help.}
{179}{}{What the hell, I'll help you.}
{180}{}{Thank you so much. I'll never be able to repay you for this. I'll wait here until you bring...
 Hey, there was someone outside listening to us! I saw their shadow on the tent wall. They just ran off
 that way! ::points north-east:: They must have heard everything!}
{181}{}{Me stop, no get away!}
{182}{}{You no worry, me find girl.}
{183}{}{Ooops.}
{184}{}{I'll try and stop them.}
{185}{}{They won't stop me from finding your daughter.}
{186}{}{Oh well. Shit happens.}
{187}{}{Please, just go away.}
{188}{}{Have you thought things through?}
{189}{}{Me ask questions.}
{190}{}{No, still think.}
{191}{}{No, I'm still considering everything.}
{192}{}{I want to ask you some questions.}
{193}{}{Have you changed your mind? Will you help me?}
{194}{}{Sorry, no.}
{195}{}{Me help.}
{196}{}{Yes, I'll help you.}
{197}{}{You must be the person who saved my daughter. I can never repay you for your kindness. Thank you.
 Please wait here, I need to talk to Chrissy and then I'd like to talk to you.}
{198}{}{You saved my daughter. I can never repay you for your kindness. Thank you.
 Please wait here, I need to talk to Chrissy and then I'd like to talk to you.}
{199}{}{Okay.}
{200}{}{My daughter has told me everything. I find it hard to believe that Darion is such a monster
 after all he's been doing for us. And to think, we've been helping him hide his operations as a raider.
 I can guarantee you we won't stand for it any longer. I've already talked to Zeke, and he wants to see
 you. You should go see him now.}
{201}{}{I find it hard to believe that Darion is such a monster after all he's been doing for us. And to
 think, we've been helping him hide his operations as a raider. I can guarantee you we won't stand for
 it any longer. I'll talk to Zeke and explain everything. I'm sure he'll want to see you. You should go
 talk to him later.}
{202}{}{Cám ơn.}
{203}{}{I hope you find Chrissy soon.}
{204}{}{Me looking.}
{205}{}{I'll continue to search for her.}
{206}{}{Thanks for everything you've done for me.}
{207}{}{I can't explain why, but I don't believe the slavers took her. I've an uneasy feeling that
 something else is going on. And then there's this feeling that I'm being followed. I've had it ever
 since I talked to Zeke about Chrissy. I need someone to help me find my daughter. Will you help me,
 please?}
{208}{}{They keep sending people here to try and talk us out of our home, but they don't understand
 that we have nowhere else to go. We don't have the skills necessary to survive on our own if we leave
 here.}
{209}{}{You know, it's kind of funny that they managed to get something that complex fixed, but not the
 lights. The damn place is lit by torches. Anyway, Darion doesn't want anyone to know what's going on
 with the vault. He's afraid that someone will take it all away from us if they find out. So, we're told
 to drive off anyone who shows up here -- especially the NCR.}
