{100}{}{Bạn thấy một người ở mượn già nua.}
{101}{}{Bạn thấy Zeke, một người ở mượn.}
{102}{}{Bạn thấy một ông già với mái tóc trắng lưa thưa.}
{103}{}{Tên tôi là Zeke, người lạ. Xin lỗi nhưng tôi không có thời gian nói chuyện đâu -- và tôi nghĩ
rằng khu trại này cũng chẳng có gì cả đâu. Cậu nên đi chỗ khác thôi.}
{104}{}{Ừ, okay.}
{105}{}{Ngộ muốn hỏi.}
{106}{}{Được rồi, tôi đi.}
{107}{}{Tôi chỉ muốn hỏi vài câu thôi.}
{108}{}{Ồ, tôi nghĩ là cậu sẽ thấy rằng chúng tôi không trả lời được gì cả. Sao cậu không quay trở lại
sau khi chúng tôi có đoàn chở hàng đến ý?}
{109}{}{Đã xong.}
{110}{}{Xin chào lần nữa. Tôi vẫn không có câu trả lời nào đâu, người lạ. Sao cậu không hiểu ý và
gói đồ cuốn xéo khỏi đây đi?}
{111}{}{Đã xong.}
{112}{}{Rebecca đã kể cho tôi về những gì cậu đã làm. Tôi muốn xin lỗi về thái độ mà cậu đã phải nhận
ở đây. Rõ ràng là cậu xứng đáng được đối xử tốt hơn. Tôi có thể giúp gì đây?}
{113}{}{Ngộ muốn hỏi.}
{114}{}{Không có gì. Lượn.}
{115}{}{Tôi có vài câu hỏi đây.}
{116}{}{Hiện không có gì. Cám ơn.}
{117}{}{Muốn biết gì nào?}
{118}{}{Ông làm việc cho Darion à?}
{119}{}{Ông làm gì với cướp?}
{120}{}{Cửa hầm đâu?}
{121}{}{Còn chuyện gì khác ở đây không?}
{122}{}{Ngộ đi giờ.}
{123}{}{Ông có làm việc cho Darion không?}
{124}{}{Ông định làm thế nào với lũ cướp?}
{125}{}{Lối vào hầm ở chỗ nào?}
{126}{}{Còn chuyện gì khác ở đây không?}
{127}{}{Chắc vậy là đủ. Giờ tôi sẽ đi đây.}
{128}{}{À, có chứ. Tôi đóng vai trò trung gian giữa ông ta và mọi người ở đây. Giờ tôi không thấy vui vẻ mấy
về việc đó sau khi biết mục đích của hắn ta.}
{129}{}{Okay.}
{130}{}{Hiểu rồi.}
{131}{}{Nothing. They have the guns, they control the water, and they control the food. That means
 they are in charge. Period. We have no skills and no means of support without the backing of Darion.
 How can we turn against him? We're at his mercy.}
{132}{}{Hmm. Me think me understand.}
{133}{}{Hmm. I see.}
{134}{}{It's behind that door over there, but it's locked from the other side and trapped, too. I don't have
 any means of opening it... Wait a minute. I found this key card some time ago, and I have no idea what
 it is for. Rebecca says that you found some sort of door where they were holding Chrissy. Maybe this
 card will open it. Here, take it.}
{135}{}{Me thank you.}
{136}{}{Thanks. I'll give it a try.}
{137}{}{There's a city west of here called NCR. They claim Vault 15 is their ancestral home and they want it
 back. They've been sending people here trying to talk us into leaving but we aren't going for it. This is the only home we know.}
{138}{}{You maybe make deal NCR?}
{139}{}{Would you consider making a deal with NCR?}
{140}{}{That all depends. What did you have in mind?}
{141}{}{Join NCR tribe. Learn from elders. Give NCR you permission enter vault. Both happy.}
{142}{}{Join NCR, let them annex your territory, and give them access to the vault. In return, they can teach you all the skills
 you need to survive on your own and offer you their protection.}
{143}{}{Not bad... I like it. You've got yourself a deal if you can get NCR to agree to it as well. But...
 Look, someone has to take care of Darion and his cronies. It should be done now before they realize what has happened
 and have time to prepare for an attack. Why not get this over with and take Darion out now?
 You'll have the element of surprise on your side.}
{144}{}{You right, me take care of.}
{145}{}{Me not sure.}
{146}{}{Yeah, I guess it has to be done.}
{147}{}{I don't know.}
{148}{}{Excellent. Good luck to you, and thank you.}
{149}{}{Đã xong.}
{150}{}{Well, take the time to think about it, but know this -- until Darion is out of the picture, I
 have no choice but to maintain things around here as they are. It's for the safety of everyone
 concerned. That means no deal and you are still persona non grata. Understand?}
{151}{}{Okay.}
{152}{}{Hi. I'm still waiting for a final resolution to our troubles. In other words, kick Darion's ass!}
{153}{}{Đã xong.}
{154}{}{You've done it, friend! We're no longer under Darion's yoke. Thank you! I'm ready to accept your deal with NCR now.
 Just have them send one of their reps by and I'll seal the deal.}
{155}{}{Đã xong.}
{156}{}{Thanks for the chance of a new life. We all owe you.}
{157}{}{Just go away. I have nothing to say to you.}
{158}{}{Wait, before you go... I found this key card some time ago, and I have no idea what it's for.
 Rebecca says that you found some sort of entrance where they were holding Chrissy. Maybe this card will
 open it. Here, take it.}
{159}{}{Cám ơn.}
{160}{}{What can I help you with?}
{161}{}{Just the problems with the NCR, but I think the deal you offered will solve that.}
{162}{}{You've done it, friend! We're no longer under Darion's yoke. Thank you!}
{163}{}{Now that Darion's gone we don't have any way to get food. We will surely perish! Thanks a lot.}
