{100}{}{Bạn thấy một người ở mượn già nua.}
{101}{}{Bạn thấy Zeke, một người ở mượn.}
{102}{}{Bạn thấy một ông già với mái tóc trắng lưa thưa.}
{103}{}{Tên tôi là Zeke, người lạ. Xin lỗi nhưng tôi không có thời gian nói chuyện đâu -- và tôi nghĩ
rằng khu trại này cũng chẳng có gì cả đâu. Cậu nên đi chỗ khác thôi.}
{104}{}{Ừ, okay.}
{105}{}{Ngộ muốn hỏi.}
{106}{}{Được rồi, tôi đi.}
{107}{}{Tôi chỉ muốn hỏi vài câu thôi.}
{108}{}{Ồ, tôi nghĩ là cậu sẽ thấy rằng chúng tôi không trả lời được gì cả. Sao cậu không quay trở lại
sau khi chúng tôi có đoàn chở hàng đến ý?}
{109}{}{Đã xong.}
{110}{}{Xin chào lần nữa. Tôi vẫn không có câu trả lời nào đâu, người lạ. Sao cậu không hiểu ý và
gói đồ cuốn xéo khỏi đây đi?}
{111}{}{Đã xong.}
{112}{}{Rebecca đã kể cho tôi về những gì cậu đã làm. Tôi muốn xin lỗi về thái độ mà cậu đã phải nhận
ở đây. Rõ ràng là cậu xứng đáng được đối xử tốt hơn. Tôi có thể giúp gì đây?}
{113}{}{Ngộ muốn hỏi.}
{114}{}{Không có gì. Lượn.}
{115}{}{Tôi có vài câu hỏi đây.}
{116}{}{Hiện không có gì. Cám ơn.}
{117}{}{Muốn biết gì nào?}
{118}{}{Ông làm việc cho Darion à?}
{119}{}{Ông làm gì với cướp?}
{120}{}{Cửa hầm đâu?}
{121}{}{Còn chuyện gì khác ở đây không?}
{122}{}{Ngộ đi giờ.}
{123}{}{Ông có làm việc cho Darion không?}
{124}{}{Ông định làm thế nào với lũ cướp?}
{125}{}{Lối vào hầm ở chỗ nào?}
{126}{}{Còn chuyện gì khác ở đây không?}
{127}{}{Chắc vậy là đủ. Giờ tôi sẽ đi đây.}
{128}{}{À, có chứ. Tôi đóng vai trò trung gian giữa ông ta và mọi người ở đây. Giờ tôi không thấy vui vẻ mấy
về việc đó sau khi biết mục đích của hắn ta.}
{129}{}{Okay.}
{130}{}{Hiểu rồi.}
{131}{}{Chẳng gì cả. Chúng có súng, chúng kiểm soát nước và thực phẩm. Điều đó có nghĩa là chúng
nắm quyền. Chấm hết. Chúng tôi không làm được gì và chẳng có điểm tựa nào nếu không dựa vào
Darion. Làm sao chúng tôi có thể chống lại hắn được chứ? Chúng tôi phụ thuộc vào hắn.}
{132}{}{Hừm. Ngộ nghĩ là ngộ hiểu.}
{133}{}{Hừm. Tôi hiểu rồi.}
{134}{}{Ở đằng sau cái cửa kia, nhưng lối vào bị khóa từ bên trong và có cả bẫy nữa. Tôi không biết mở bằng
cách nào... Chờ đã. Tôi tìm thấy cái thẻ từ này hồi trước nhưng chẳng biết dùng để làm gì cả. Rebecca
nói rằng cậu có tìm thấy một cánh cửa gì đó ở chỗ chúng giam giữ Chrissy. Có thể cái thẻ này sẽ mở được
đấy. Đây, cầm lấy.}
{135}{}{Ngộ cám ơn.}
{136}{}{Cám ơn. Tôi sẽ thử.}
{137}{}{Có một thành phố ở phía Tây chỗ này gọi là NCR. Họ nhận rằng Vault 15 là ngôi nhà gốc của mình và họ muốn lấy lại.
Họ đã cử người đến đây để cố thuyết phục chúng tôi rời đi nhưng không đâu. Đây là chốn nương thân duy nhất của chúng tôi.}
{138}{}{Ông có thể thương lượng với NCR?}
{139}{}{Liệu ông có muốn thương lượng với NCR không?}
{140}{}{Còn tùy. Cậu có ý gì?}
{141}{}{Gia nhập tộc NCR. Học từ trưởng lão. Cho NCR quyền vào hầm. Vui cả hai.}
{142}{}{Gia nhập NCR, để họ sáp nhập lãnh thổ và cho họ vào trong hầm. Đổi lại, họ sẽ dạy cho các ông tất cả các kĩ năng
cần thiết để tự sinh tồn và cho quân bảo vệ nơi này.}
{143}{}{Không tệ... tôi thích ý này. Coi như cậu đã đạt được thảo thuận nếu như NCR cũng đồng ý. Nhưng...
Này, cần có ai đó giải quyết Darion và tay chân của hắn. Việc này cần phải làm ngay trước khi chúng biết được điều gì
đã xảy ra và có thời gian để chuẩn bị tấn công. Sao không kết thúc việc này và giải quyết Darion luôn?
Cậu đang có yếu tố bất ngờ cơ mà.}
{144}{}{Ông đúng, ngộ đi giải quyết.}
{145}{}{Ngộ không chắc.}
{146}{}{Ừ, tôi chắc là kiểu gì cũng phải làm.}
{147}{}{Tôi không chắc.}
{148}{}{Tuyệt. Chúc cậu may mắn, và cảm ơn.}
{149}{}{Đã xong.}
{150}{}{Ồ, thế thì cứ dành thời gian nghĩ đi, nhưng nghe này -- trừ khi Darion chết rồi thì thôi, còn tôi
không có lựa chọn nào khác ngoài việc tiếp tục duy trì mọi thứ như bây giờ. Để bảo đảm an toàn cho
mọi người. Có nghĩa là chẳng có thỏa thuận nào và cậu vẫn không được chào đón. Hiểu chứ?}
{151}{}{Okay.}
{152}{}{Chào. Tôi vẫn đang chờ lời kết cuối cùng cho vấn đề này. Nói cách khác, đi đá đít Darion đi!}
{153}{}{Đã xong.}
{154}{}{Cậu đã làm được rồi, anh bạn! Chúng tôi không còn phải lo về Darion nữa. Cám ơn! Tôi đã sẵn sàng để chấp nhận
thỏa thuận với NCR rồi. Chỉ cần họ cử người đại diện đến đây và tôi sẽ chốt.}
{155}{}{Đã xong.}
{156}{}{Cám ơn vì cơ hội cho một cuộc sống mới. Tất cả chúng tôi đều nợ cậu.}
{157}{}{Đi đi. Tôi không có gì để nói cả.}
{158}{}{Chờ đã, trước khi đi... tôi tìm thấy cái thẻ từ này trước đây không lâu, nhưng chẳng biết để làm gì.
Rebecca nói là cậu có tìm thấy một lối vào gì đó ở chỗ chúng giam giữ Chrissy. Có thể cái thẻ này sẽ
mở được. Đây, cầm lấy.}
{159}{}{Cám ơn.}
{160}{}{Tôi có thể giúp gì đây?}
{161}{}{Chỉ là vấn đề với NCR, nhưng đề nghị của cậu đã giải quyết chuyện đó rồi.}
{162}{}{Cậu làm được rồi, anh bạn! Chúng tôi không còn phải lo về Darion nữa. Cám ơn!}
{163}{}{Giờ thì Darion không còn nữa và chúng tôi chẳng có cách nào để kiếm lương thực. Chắc chắn là chúng tôi sẽ tiêu tùng rồi! Cám ơn nhiều đấy.}
