{100}{}{Bạn bắt gặp lũ trộm và sói.}
{101}{}{Bạn bắt gặp lũ trộm.}
{102}{}{Bạn bắt gặp sói.}
{103}{}{Bạn bắt gặp bọ cạp.}
{104}{}{Bạn bắt gặp cây bào tử.}
{105}{}{Bạn bắt gặp một Đội tuần tra của Khối đoàn kết đang chiến đấu với lũ trộm.}
{106}{}{Bạn bắt gặp một Đoàn tuần tra của Khối đoàn kết đang chiến đấu với sói.}
{107}{}{Bạn bắt gặp một Đoàn tuần tra của Khối đoàn kết.}
{150}{}{Bạn bắt gặp người buôn nô lệ và chó.}
{151}{}{Bạn bắt gặp người buôn nô lệ.}
{152}{}{Bạn bắt gặp tắc kè vàng.}
{153}{}{Bạn bắt gặp chó hoang.}
{154}{}{Bạn bắt gặp một đội tuần tra và chó đang chiến đấu với người buôn nô lệ.}
{155}{}{Bạn bắt gặp người buôn nô lệ đang chiến đấu với tắc kè vàng.}
{156}{}{Bạn bắt gặp một đội tuần tra đang chiến đấu với người buôn nô lệ.}
{157}{}{Bạn bắt gặp một đội tuần tra đang chiến đấu với tắc kè vàng.}
{158}{}{Bạn bắt gặp một đội tuần tra đang chiến đấu với chó hoang.}
{159}{}{Bạn bắt gặp một đội tuần tra.}
{200}{}{Bạn bị toán cướp phục kích.}
{201}{}{Bạn bắt gặp sói.}
{202}{}{Bạn bắt gặp một đoàn lữu hành đang chống lại toán cướp.}
{203}{}{Bạn bắt gặp một đoàn lữu hành đang chống lại toán cướp.}
{204}{}{Bạn bắt gặp một đoàn lữ hành đang chống lại toán cướp}
{205}{}{Bạn bắt gặp một đoàn lữu hành đang chống lại toán cướp.}
{206}{}{Bạn bắt gặp một đoàn lữ hành.}
{207}{}{Bạn bắt gặp một đoàn lữ hành.}
{208}{}{Bạn bắt gặp một đoàn lữ hành.}
{209}{}{Bạn bắt gặp một đoàn lữ hành.}
{250}{}{Bạn bắt gặp lũ cướp.}
{251}{}{Bạn bắt gặp sói.}
{252}{}{Bạn bắt gặp bọ cạp.}
{253}{}{Bạn bắt gặp một đoàn lữ hành đang chống lại lũ cướp.}
{254}{}{Bạn bắt gặp một đoàn lữ hành đang chống lại lũ cướp.}
{255}{}{Bạn bắt gặp một đoàn lữ hành đang chống lại sói.}
{256}{}{Bạn bắt gặp một đoàn lữ hành đang chống lại bò cạp.}
{257}{}{Bạn bắt gặp một đoàn lữ hành.}
{258}{}{Bạn bắt gặp một đoàn lữ hành.}
{259}{}{Bạn bắt gặp một đoàn lữ hành.}
{260}{}{Bạn bắt gặp một đoàn lữ hành.}
{261}{}{Bạn bắt gặp một người phiêu lưu.}
{300}{}{Bạn bắt gặp một toán thất trận từ đội quân của Ông trùm.}
{301}{}{Bạn bắt gặp lũ cướp.}
{302}{}{Bạn bắt gặp Đội biệt kích NCR đang chiến đấu với toán thất trận từ đội quân của Ông trùm.}
{303}{}{Bạn bắt gặp Đội biệt kích NCR đang chiến đấu với lũ cướp.}
{304}{}{Bạn bắt gặp mấy nông dân đang chống lại toán thất trận từ đội quân của Ông trùm.}
{305}{}{Bạn bắt gặp mấy nông dân đang chống lại lũ cướp.}
{306}{}{Bạn bắt gặp Đội biệt kích NCR.}
{307}{}{Bạn bắt gặp mấy nông dân.}
{350}{}{You encounter a slaver caravan.}
{351}{}{You encounter highwaymen and robbers.}
{352}{}{You encounter highwaymen.}
{353}{}{You encounter robbers.}
{354}{}{You encounter a caravan fending off highwaymen.}
{355}{}{You encounter a caravan fighting robbers.}
{356}{}{You encounter a caravan fighting highwaymen.}
{357}{}{You encounter a caravan besieged by robbers.}
{358}{}{You encounter a slave caravan fighting a caravan.}
{359}{}{You encounter highwaymen fighting robbers.}
{360}{}{Bạn bắt gặp một đoàn lữ hành.}
{361}{}{Bạn bắt gặp một đoàn lữ hành.}
{400}{}{You encounter highwaymen.}
{401}{}{You encounter robbers.}
{402}{}{You encounter robbers and highwaymen.}
{403}{}{You encounter golden geckos and radscorpions.}
{404}{}{Bạn bắt gặp tắc kè vàng.}
{405}{}{You encounter mole rats and pig rats.}
{406}{}{Bạn bắt gặp bọ cạp.}
{407}{}{Bạn bắt gặp cây bào tử.}
{408}{}{You encounter robbers fighting highwaymen.}
{409}{}{You encounter a caravan fending off highwaymen.}
{410}{}{You encounter a caravan fending off robbers.}
{411}{}{Bạn bắt gặp một đoàn lữ hành đang chống lại bò cạp.}
{412}{}{You encounter geckos fighting radscorpions.}
{413}{}{Bạn bắt gặp một đoàn lữ hành.}
{450}{}{You encounter highwaymen and robbers.}
{451}{}{You encounter highwaymen and geckos.}
{452}{}{Bạn bắt gặp tắc kè vàng.}
{453}{}{You encounter radscorpions and spore plants.}
{454}{}{You encounter robbers fighting radscorpions.}
{455}{}{You encounter radscorpions fighting robbers.}
{456}{}{You encounter a caravan fending off highwaymen.}
{457}{}{You encounter a caravan fending off robbers.}
{458}{}{You encounter some highwaymen weeding out some spore plants.}
{459}{}{Bạn bắt gặp một đoàn lữ hành.}
{500}{}{You encounter highwaymen and wild dogs.}
{501}{}{You encounter robbers and wild dogs.}
{502}{}{You encounter robbers.}
{503}{}{You encounter highwaymen.}
{504}{}{You encounter a swarm of mantis and some spore plants.}
{505}{}{You encounter dogs and spore plants.}
{506}{}{You encounter a swarm of mantis.}
{507}{}{Bạn bắt gặp chó hoang.}
{508}{}{You encounter robbers fighting dogs.}
{509}{}{You encounter a caravan fending off dogs.}
{510}{}{You encounter a caravan fending off robbers.}
{511}{}{You encounter a caravan fending off highwaymen.}
{512}{}{Bạn bắt gặp một đoàn lữ hành.}
{550}{}{You encounter geckos and wolves.}
{551}{}{You encounter claim jumpers.}
{552}{}{Bạn bắt gặp sói.}
{553}{}{Bạn bắt gặp tắc kè vàng.}
{554}{}{You encounter prospectors fending off claim jumpers.}
{555}{}{You encounter trappers hunting geckos.}
{556}{}{You encounter bootleggers fighting wolves.}
{557}{}{You encounter homesteaders fighting claim jumpers}
{558}{}{You encounter homesteaders fighting wolves.}
{559}{}{You encounter bootleggers.}
{560}{}{You encounter trappers.}
{561}{}{You encounter prospectors.}
{600}{}{You encounter deathclaws.}
{601}{}{You encounter fire geckos.}
{602}{}{You encounter a caravan fleeing from deathclaws.}
{603}{}{You encounter a caravan fighting deathclaws.}
{604}{}{You encounter a caravan fighting fire geckos.}
{605}{}{You encounter a caravan fighting fire geckos.}
{606}{}{Bạn bắt gặp một đoàn lữ hành.}
{607}{}{Bạn bắt gặp một đoàn lữ hành.}
{608}{}{Bạn bắt gặp một đoàn lữ hành.}
{609}{}{Bạn bắt gặp một đoàn lữ hành.}
{650}{}{You encounter aliens and deathclaws.}
{651}{}{You encounter centaurs and floaters.}
{652}{}{You encounter fire geckos.}
{653}{}{You encounter aliens.}
{654}{}{You encounter deathclaws.}
{655}{}{You encounter fire geckos.}
{656}{}{You encounter aliens.}
{657}{}{You encounter centaurs.}
{658}{}{You encounter floaters.}
{700}{}{You encounter some Yakuza.}
{701}{}{You encounter a gang.}
{702}{}{You encounter some wolves.}
{703}{}{You encounter some mobsters fighting some Yakuza.}
{704}{}{You encounter some mobsters fighting a gang.}
{705}{}{You encounter some mobsters.}
{706}{}{Bạn bắt gặp một người phiêu lưu.}
{750}{}{You encounter a caravan fending off remnants of the Master's army.}
{751}{}{You encounter a caravan fighting remnants of the master's army.}
{752}{}{You encounter a caravan fighting deathclaws.}
{753}{}{Bạn bắt gặp một đoàn lữ hành.}
{754}{}{Bạn bắt gặp một đoàn lữ hành.}
{755}{}{Bạn bắt gặp một đoàn lữ hành.}
