{100}{}{Bạn thấy một bảng máy tính.}
{101}{}{Bạn thấy bảng máy tính của trung tâm điều khiển.}
{102}{}{Bạn thấy một bảng máy tính thông thường. Trông có vẻ vẫn còn hoạt động và đã sẵn sàng nhập lệnh.}
{103}{}{Bảng cho thấy rằng giờ đây trường lực bảo vệ tại cửa hầm đã được kích hoạt sau khi
nguồn điện được khôi phục.}
{104}{}{Bảng cho thấy rằng tất cả hệ thống bảo vệ trong hầm đã bị tắt do mất nguồn điện.}
{105}{}{Tắt trường lực.}
{106}{}{Bật trường lực.}
{107}{}{Đã xong.}
{108}{}{Bạn thực hiện lệnh hủy kích hoạt trường lực.}
{109}{}{Đã xong.}
{110}{}{Bạn thực hiện lệnh kích hoạt trường lực.}
{111}{}{Đã xong.}
{112}{}{Bảng cho thấy rằng trường lực đã bị tắt do ghi đè thủ công.}
{113}{}{Bảng cho thấy rằng hệ thống trường lực đã bị xâm nhập.}
{114}{}{Bảng cho thấy rằng hệ thống trường lực đã tắt.}
