{100}{}{Bạn thấy một bảng máy tính.}
{101}{}{Bạn thấy bảng máy tính an ninh.}
{102}{}{Bạn thấy một bảng máy tính thông thường. Trông có vẻ vẫn còn hoạt động và đã sẵn sàng nhập lệnh.}
{103}{}{Bảng này quản lý máy tạo trường lực. Chỉ báo cho thấy rằng mọi thứ đang hoạt động
bình thường.}
{104}{}{Bảng này quản lý máy tạo trường lực. Chỉ báo cho thấy rằng thiết bị đang không hoạt động
do mất nguồn cấp điện.}
{105}{}{Tắt trường lực.}
{106}{}{Bật trường lực.}
{107}{}{Đã xong.}
{108}{}{Bạn thực hiện lệnh hủy kích hoạt trường lực.}
{109}{}{Có vẻ bạn không bỏ qua được mã an ninh để hủy kích hoạt trường lực.}
{110}{}{Đã xong.}
{111}{}{Bạn thực hiện lệnh kích hoạt trường lực.}
{112}{}{Có vẻ như bạn không bỏ qua được mã an ninh để kích hoạt trường lực.}
{113}{}{Đã xong.}
{114}{}{Bảng này quản lý máy tạo trường lực. Chỉ báo cho thấy trường lực đang tắt.}
{115}{}{Bảng này quản lý máy tạo trường lực. Chỉ báo cho thấy trường lực đã bị tắt tạm thời.}
{116}{}{Bảng này quản lý máy tạo trường lực. Chỉ báo cho thấy trường lực đã bị xâm nhập.}
