{100}{}{Bạn thấy một bảng máy tính.}
{101}{}{You see the power center computer terminal.}
{102}{}{Bạn thấy một bảng máy tính thông thường. Trông có vẻ vẫn còn hoạt động và đã sẵn sàng nhập lệnh.}
{103}{}{This terminal monitors the power generator. It indicates that everything is functioning
 normally.}
{104}{}{This terminal monitors the power generator. It indicates that the unit is off line due to a
 malfunction of some sort.}
{105}{}{Đã xong.}
