{100}{}{Bạn thấy một bảng máy tính.}
{101}{}{Bạn thấy bảng máy tính của trung tâm điều khiển.}
{102}{}{Bạn thấy một bảng máy tính thông thường. Trông có vẻ vẫn còn hoạt động và đã sẵn sàng nhập lệnh.}
{103}{}{Bảng này quản lý máy tạo trường lực. Chỉ báo cho thấy mọi thứ đang hoạt động
bình thường.}
{104}{}{Bảng này quản lý máy tạo trường lực. Chỉ báo cho thấy thiết bị đang không hoạt động
do một sự cố nào đó.}
{105}{}{Đã xong.}
