{100}{}{Bạn thấy một cái cửa gỗ.}
{101}{}{Bạn thấy một cái cửa sắt.}
{102}{}{Bạn thấy một cánh cửa kiên cố có khóa, có thể dùng cậy khóa
để mở, và bẫy thuốc nổ nhạy trên khung cửa mà bạn có thể
thử cậy mở.}
{103}{}{Bạn thấy một cánh cửa kiên cố có khóa và bẫy
thuốc nổ nhạy trên khung cửa, mà bạn có thể
thử cậy mở.}
{104}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa
và bẫy thuốc nổ nhạy trên khung cửa, mà bạn có thể
thử cậy mở.}
{105}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét và
bẫy thuốc nổ nhạy trên khung cửa, mà bạn có thể thử cậy mở.}
{106}{}{Bạn thấy một cánh cửa kiên cố có khóa (có thể dùng
cậy khóa để mở) và bẫy trên khung cửa, mà bạn có thể
thử cậy mở.}
{107}{}{Bạn thấy một cánh cửa kiên cố có khóa và bẫy
trên khung cửa, mà bạn có thể thử cậy mở.}
{108}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa
và bẫy trên khung cửa, mà bạn có thể thử cậy mở.}
{109}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét
và bẫy trên khung cửa, mà bạn có thể thử cậy mở.}
{110}{}{Bạn thấy một cánh cửa kiên cố có khóa, có thể dùng cậy khóa
để mở, và đoạn dây thép bị cắt trên khung cửa mà bạn có thể
thử cậy mở.}
{111}{}{Bạn thấy một cánh cửa kiên cố có khóa và đoạn dây
thép bị đứt trên khung cửa, mà bạn có thể thử cậy mở.}
{112}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa
và đoạn dây thép bị đứt trên khung cửa, mà bạn có thể thử
cậy mở.}
{113}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét
và đoạn dây thép bị cắt trên khung cửa, mà bạn có thể
thử cậy mở.}
{114}{}{Bạn thấy một cánh cửa kiên cố có khóa (có thể dùng
cậy khóa để mở) mà bạn có thể thử cậy mở.}
{115}{}{Bạn thấy một cánh cửa kiên cố có khóa mà bạn có thể
thử cậy mở.}
{116}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có
khóa mà bạn có thể thử cậy mở.}
{117}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ,
rỉ sét mà bạn có thể thử cậy mở.}
{118}{}{Bạn thấy một cánh cửa kiên cố có khóa, có thể dùng cậy khóa
để mở, và bẫy thuốc nổ nhạy trên khung cửa.}
{119}{}{Bạn thấy một cánh cửa kiên cố có khóa và bẫy
thuốc nổ nhạy trên khung cửa.}
{120}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa
và bẫy thuốc nổ nhạy trên khung cửa.}
{121}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét
và bẫy thuốc nổ nhạy trên khung cửa.}
{122}{}{Bạn thấy một cánh cửa kiên cố có khóa, có thể dùng cậy khóa
để mở, và bẫy trên khung cửa.}
{123}{}{Bạn thấy một cánh cửa kiên cố có khóa và bẫy
trên khung cửa.}
{124}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa
và bẫy trên khung cửa.}
{125}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét
và bẫy trên khung cửa.}
{126}{}{Bạn thấy một cánh cửa kiên cố có khóa, có thể dùng cậy khóa
để mở, và đoạn dây thép bị cắt trên khung cửa.}
{127}{}{Bạn thấy một cánh cửa kiên cố có khóa và đoạn dây thép
bị đứt trên khung cửa.}
{128}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa và
đoạn dây thép bị đứt trên khung cửa.}
{129}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét và
đoạn dây thép bị cắt trên khung cửa.}
{130}{}{Bạn thấy một cánh cửa kiên cố có khóa, có thể dung cậy khóa
để mở.}
{131}{}{Bạn thấy một cánh cửa kiên cố có khóa.}
{132}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa.}
{133}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ,
rỉ sét.}
{134}{}{Bạn thấy một cánh cửa bị hư hại có khóa, có thể dùng cậy khóa
để mở, và bẫy thuốc nổ nhạy trên khung cửa.}
{135}{}{Bạn thấy một cánh cửa bị hư hại có khóa và bẫy
thuốc nổ nhạy trên khung cửa.}
{136}{}{Bạn thấy một cánh cửa bị hư hại có vẻ như không có khóa và
bẫy thuốc nổ nhạy trên khung cửa.}
{137}{}{Bạn thấy một cánh cửa bị hư hại với ổ khóa cũ kĩ, rỉ sét và
bẫy thuốc nổ nhạy trên khung cửa.}
{138}{}{Bạn thấy một cánh cửa bị hư hại có khóa, có thể dùng cậy khóa
để mở, và bẫy trên khung cửa.}
{139}{}{Bạn thấy một cánh cửa bị hư hại có khóa và bẫy trên
khung cửa.}
{140}{}{Bạn thấy một cánh cửa bị hư hại có vẻ như không có khóa và
bẫy trên khung cửa.}
{141}{}{Bạn thấy một cánh cửa bị hư hại với ổ khóa cũ kĩ, rỉ sét và
bẫy trên khung cửa.}
{142}{}{Bạn thấy một cánh cửa bị hư hại có khóa, có thể dùng cậy khóa
để mở, và một đoạn dây thép bị cắt trên khung cửa.}
{143}{}{Bạn thấy một cánh cửa bị hư hại có khóa và đoạn dây thép
bị đứt trên khung cửa.}
{144}{}{Bạn thấy một cánh cửa bị hư hại có vẻ như không có khóa và
đoạn dây thép bị đứt trên khung cửa.}
{145}{}{Bạn thấy một cánh cửa bị hư hại với ổ khóa cũ kĩ, rỉ sét và
đoạn dây thép bị cắt trên khung cửa.}
{146}{}{Bạn thấy một cánh cửa bị hư hại có khóa, có thể dùng cậy khóa
để mở.}
{147}{}{Bạn thấy một cánh cửa bị hư hại có khóa.}
{148}{}{Bạn thấy một cánh cửa bị hư hại có vẻ như không có khóa.}
{149}{}{Bạn thấy một cánh cửa bị hư hại với ổ khóa cũ kĩ, rỉ sét.}
{150}{}{Bạn thấy một cánh cửa cũ có khóa, có thể dùng cậy khóa
để mở, và bẫy thuốc nổ nhạy trên khung cửa.}
{151}{}{Bạn thấy một cánh cửa cũ có khóa và bẫy
thuốc nổ nhạy trên khung cửa.}
{152}{}{Bạn thấy một cánh cửa cũ có vẻ như không có khóa và
bẫy thuốc nổ nhạy trên khung cửa.}
{153}{}{Bạn thấy một cánh cửa cũ với ổ khóa cũ kĩ, rỉ sét và
bẫy thuốc nổ nhạy trên khung cửa.}
{154}{}{Bạn thấy một cánh cửa cũ có khóa, có thể dùng cậy khóa
để mở, và bẫy trên khung cửa.}
{155}{}{Bạn thấy một cánh cửa cũ có khóa và bẫy trên
khung cửa.}
{156}{}{Bạn thấy một cánh cửa cũ có vẻ như không có khóa và
bẫy trên khung cửa.}
{157}{}{Bạn thấy một cánh cửa cũ với ổ khóa cũ kĩ, rỉ sét và
bẫy trên khung cửa.}
{158}{}{Bạn thấy một cánh cửa cũ có khóa, có thể dùng cậy khóa
để mở, và một đoạn dây thép bị cắt trên khung cửa.}
{159}{}{Bạn thấy một cánh cửa cũ có khóa và đoạn dây thép
bị đứt trên khung cửa.}
{160}{}{Bạn thấy một cánh cửa cũ có vẻ như không có khóa và
đoạn dây thép bị đứt trên khung cửa.}
{161}{}{Bạn thấy một cánh cửa cũ với ổ khóa cũ kĩ, rỉ sét và
đoạn dây thép bị cắt trên khung cửa.}
{162}{}{Bạn thấy một cánh cửa cũ có khóa, có thể dùng cậy khóa
để mở.}
{163}{}{Bạn thấy một cánh cửa cũ có khóa.}
{164}{}{Bạn thấy một cánh cửa cũ có vẻ như không có khóa.}
{165}{}{Bạn thấy một cánh cửa với ổ khóa cũ kĩ, rỉ sét.}
{166}{}{Bạn bị dính bẫy và đã nhận }
{167}{}{ điểm sát thương.}
{168}{}{ đã dính bẫy và nhận }
{169}{}{ điểm sát thương.}
{170}{}{Bạn khéo léo cậy khóa trên cửa.}
{171}{}{Kĩ năng kém cỏi của bạn đã làm kẹt ổ khóa trên cửa.}
{172}{}{Bạn không cậy được khóa trên cánh cửa này.}
{173}{}{ khéo léo cậy khóa trên cửa.}
{174}{}{do thiếu kĩ năng đã làm kẹt ổ khóa trên cửa.}
{175}{}{ không cậy được khóa trên cửa.}
{176}{}{Bạn đã phá khóa khỏi cửa.}
{177}{}{Bạn bị căng cơ lưng khi cố gắng phá khóa và
nhận một điểm sát thương.}
{178}{}{Bạn bị căng cơ lưng khi cố gắng phá khóa và
nhận }
{179}{}{ điểm sát thương.}
{180}{}{Bạn quá yếu để có thể phá khóa.}
{181}{}{ đã phá khóa khỏi cửa.}
{182}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận một
 điểm sát thương.}
{183}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận }
{184}{}{ điểm sát thương.}
{185}{}{ quá yếu để có thể phá khóa.}
{186}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận một
 điểm sát thương.}
{187}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận}
{188}{}{ điểm sát thương.}
{189}{}{Bạn khéo léo khóa cửa.}
{190}{}{Bạn không khóa được cửa.}
{191}{}{ khéo léo khóa cửa.}
{192}{}{ không khóa được cửa.}
{193}{}{Thuốc nổ còn chẳng làm xước nổi cửa.}
{194}{}{Bạn tìm thấy bẫy trên cửa.}
{195}{}{Bạn không tìm thấy bẫy trên cửa.}
{196}{}{Bạn khéo léo vô hiệu hóa bẫy.}
{198}{}{Bạn không vô hiệu hóa được bẫy.}
{199}{}{ tìm thấy bẫy trên cửa.}
{200}{}{ không tìm thấy bẫy trên cửa.}
{201}{}{ khéo léo vô hiệu hóa bẫy.}
{202}{}{ không vô hiệu hóa được bẫy.}
{203}{}{Cửa trông như bị khóa. Có vẻ như cần dùng một thẻ mỏng nào đó làm chìa.}
{204}{}{Bạn nghe tiếng dòng điện chạy tách qua cửa.}
{205}{}{ nghe thấy tiếng dòng điện chạy tách qua cửa.}
{206}{}{Bạn không thể đặt bẫy trên cái cửa này vì cửa đang mở.}
{207}{}{ không thể đặt bẫy trên cái cửa này vì cửa đang mở.}
{208}{}{Bạn khéo léo đặt bẫy trên khung cửa.}
{209}{}{Bạn không đặt được bẫy đúng cách trên khung cửa.}
{210}{}{ khéo léo đặt bẫy trên khung cửa.}
{211}{}{ không đặt được bẫy đúng cách trên khung cửa.}
{300}{}{Bạn mở khóa cửa.}
{301}{}{Bạn khóa cửa.}
{302}{}{Bạn không thể khóa trong lúc cửa đang mở.}
{303}{}{Chiếc chìa không vừa với ổ khóa này.}
{320}{}{Không có cách nào để mở cánh cửa này.}
{400}{}{Bạn mở khóa cửa.}
{500}{}{Không có cách nào để tháo bẫy khỏi cửa.}
