{100}{}{Máy phát điện đang hoạt động bình thường. Điện cấp ở mức tối ưu.}
{101}{}{Có vẻ như máy phát điện đang ở trong trạng thái chờ khẩn cấp. Điện cấp ở mức tối thiểu.}
{102}{}{Cố tìm hiểu vấn đề.}
{103}{}{Ồ thôi đi vậy.}
{104}{}{Chắc hẳn hệ thống bị ngắn mạch vào thời điểm nào đó. Cầu dao khẩn cấp đã được kích hoạt, nhưng
cầu chì ở vị trí mở. Bạn có thể cắm lại chúng và khôi phục nguồn điện.}
{105}{}{Bạn không tìm thấy có gì hỏng hóc cả. Thứ này mãi không chạy.}
{106}{}{Cố thử sửa.}
{107}{}{Đã đến lúc đi rồi.}
{108}{}{Bạn đã tách được đầu nối lỏng và khôi phục nguồn điện!}
{109}{}{Mẹ nó. Khó hơn tưởng tượng.}
{110}{}{Đã xong.}
