{100}{}{Bạn thấy một người mặc đồ quân đội.}
{101}{}{Bạn thấy một người mặc đồ quân đội.}
{102}{}{Bạn thấy một người mặc đồ quân đội nhưng trông có vẻ giống kĩ sư hơn là lính.}
{103}{}{Này, ổn chứ?}
{104}{}{"Hiểu rõ, đã bắt được tín hiệu" -- xin lỗi, nhưng tôi đang dở việc bây giờ.}
{105}{}{Giờ tôi không nói chuyện được.}
{106}{}{Cứ xem tự nhiên, nhưng đừng có chạm vào.}
{107}{}{Cậu bị điên à mà đi lại không mặc quân phục? Mặc đồ vào!}
{108}{}{Trung sĩ mà bắt được cậu không mặc quân phục thì ông ấy sạc cho teo chim.}
{109}{}{Sao cậu lại không mặc quân phục?}
{110}{}{Đm! Chúng ta đang bị xâm nhập! Báo động!}
{111}{}{Có kẻ xâm nhập! Gọi bảo vệ ngay!}
{112}{}{Bảo vệ đâu! Có kẻ xâm nhập trong phòng điều khiển không lưu!}
{113}{}{Gì thế? Chúng ta bị tấn công à?}
{114}{}{Sao lại báo động? Chuyện gì thế?}
{115}{}{Cái củ lìn gì đang diễn ra thế?}
