{100}{}{Bạn thấy một kĩ thuật viên.}
{101}{}{Bạn thấy một kĩ thuật viên của Enclave.}
{102}{}{Bạn thấy một người mặc áo khoác phòng thí nghiệm. Ông ta trông có vẻ rất tự tin.}
{103}{}{Gì thế, cậu lính?}
{104}{}{Ngộ mới đây. Cần hỏi.}
{105}{}{Ngộ chỉ chào. Ngộ đi giờ.}
{106}{}{Tôi là người mới ở đây và đang cố làm quen với căn cứ. Tôi có thể hỏi vài câu không?}
{107}{}{Chỉ chào thôi. Gặp lại sau.}
{108}{}{Được, tôi có vài phút.}
{109}{}{Tôi có thể giúp gì đây?}
{110}{}{Đây chỗ nào?}
{111}{}{Việc ông gì?}
{112}{}{Căn cứ chính Enclave chỗ mô?}
{113}{}{Ngộ tìm bản vẽ máy bay trực thăng. Ngộ tìm đâu?}
{117}{}{Ngộ đi giờ.}
{118}{}{Đây là nơi nào?}
{119}{}{Công việc của ông ở đây là gì?}
{120}{}{Căn cứ chính của Enclave nằm ở đâu?}
{121}{}{Tôi cần xem bản vẽ máy bay trực thăng. Chúng để ở đâu thế?}
{125}{}{Không có gì. Tôi phải đi đây.}
{126}{}{Đây là phòng kiểm soát không lưu. Chúng tôi có thể theo dõi tất cả các chuyến bay tại đây.}
{127}{}{Ngộ thấy. Ngộ hỏi thêm.}
{128}{}{Được rồi. Hỏi thêm mấy câu nữa.}
{129}{}{Tôi là kĩ thuật viên máy tính, hạng nhất. Tôi duy trì liên kết đến máy chủ ở bên dưới.}
{130}{}{Ừ... vậy à.}
{131}{}{Tốt. Cứ tiếp tục đi.}
{132}{}{Chẳng phải cậu đến từ đó sao?}
{133}{}{Ờ... không, ngộ đến từ phía Bắc.}
{134}{}{Không, tôi thực ra đến từ phía Bắc.}
{135}{}{Ồ... tôi không biết là chúng ta có tiền đồn ở đấy đâu. Còn căn cứ chính nằm cách bờ biển San Fran một quãng.}
{136}{}{Chúng ta đến thế nào?}
{137}{}{Ồ... Làm sao đế đến được đó?}
{138}{}{Bằng máy bay trực thăng, dĩ nhiên rồi. Chẳng có cách nào khác, trừ phi có thuyền. Chỗ đấy quá xa để bơi đến.}
{139}{}{Cám ơn.}
{140}{}{Cám ơn.}
{141}{}{Bản vẽ máy bay trực thăng... tôi không hiểu tại sao cậu lại cần thứ đó. Tôi khuyên cậu sang nói chuyện với phòng bảo trì bên cạnh ấy.}
{142}{}{Okay.}
{143}{}{Hiểu rồi.}
{153}{}{Cậu điên à, đi lại ở đây mà không mặc quân phục? Mặc đồ vào!}
{154}{}{Trung sĩ mà bắt được cậu không mặc quân phục thì ông ấy sạc cho teo chim.}
{155}{}{Sao cậu lại không mặc quân phục?}
{156}{}{Đm! Chúng ta đang bị xâm nhập! Báo động!}
{157}{}{Có kẻ xâm nhập! Gọi bảo vệ ngay!}
{158}{}{Bảo vệ đâu! Có kẻ xâm nhập trong trung tâm liên lạc!}
{159}{}{Gì thế? Chúng ta bị tấn công à?}
{160}{}{Sao lại báo động? Chuyện gì thế?}
{161}{}{Cái củ lìn gì đang diễn ra thế?}
{162}{}{Tôi chỉ là kĩ thuật viên thôi! Đừng bắn tôi!}
{163}{}{Tôi đâu có đăng kí chiến đấu, chỉ huấn luyện kĩ thuật thôi!}
{164}{}{Đây là áo khoác thí nghiệm chứ có phải giáp đâu! Tôi biến khỏi đây đây!}
