{100}{}{Bạn thấy một ông già.}
{101}{}{Bạn thấy Chris, người trông coi trạm xăng.}
{102}{}{Bạn thấy một ông già ăn mặc lôi thôi trong chiếc áo choàng màu tím.}
{103}{}{Chào chào, người lạ. Ồ bé yêu ơi! Xem bộ bánh xe này. Bao năm rồi mới lại
thấy một chiếc. Lão Chris có thể giúp gì nhỉ?}
{104}{}{Chào chào, người lạ. Chưa thấy cậu ở đây bao giờ. Lão Chris có thể giúp
gì đây?}
{105}{}{Đây chỗ nào?}
{106}{}{Ngộ tìm Navarro. Đây phải không?}
{107}{}{Ông thấy chim sắt bay ở đây?}
{108}{}{Ông có nghe Enclave? Họ đây?}
{109}{}{Ngộ chỉ ngó quanh.}
{110}{}{Đây là nơi nào?}
{111}{}{Tôi đang tìm Navarro. Có phải ở đây không?}
{112}{}{Ông có nhìn thấy cái máy bay trực thăng nào bay qua đây không?}
{113}{}{Có từng nghe đến Enclave không? Họ có ở quanh đây không?}
{114}{}{Tôi chỉ ngó quanh đây thôi.}
{115}{}{Đây là chỗ của tôi, của Chris. Đây là trạm dịch vụ – chưa từng nhìn thấy
trước đây, trong tạp chí cũ hoặc đại khái thế à? Đó là thứ này – một
trạm dịch vụ.}
{116}{}{Ngộ tìm Navarro. Đây phải không?}
{117}{}{Ông thấy chim sắt bay ở đây?}
{118}{}{Ông có nghe Enclave? Họ đây?}
{119}{}{Ừ... ngộ phải đi.}
{120}{}{Tôi đang tìm Navarro. Có phải ở đây không?}
{121}{}{Ông có nhìn thấy cái máy bay trực thăng nào bay qua đây không?}
{122}{}{Có từng nghe đến Enclave không? Họ có ở quanh đây không?}
{123}{}{Xin lỗi, phải đi.}
{124}{}{Navarro? Lâu lắm rồi chưa nghe thấy cái tên đó. Căn cứ quân sự cũ ở phía
Đông Nam của San Fran, đi tuốt về phía Nam cơ.}
{125}{}{Ngộ đến đó. Không phải Navarro.}
{126}{}{Okay. Ngộ cám ơn. Ngộ xem đó.}
{127}{}{Ông lừa ngộ. Ngộ biết Navarro đây. Ông nói thật hoặc ngộ làm ông xin lỗi!}
{128}{}{Tôi đã ở đó và chỗ đó không phải là Navarro.}
{129}{}{Okay, tôi sẽ đến đó xem. Cám ơn.}
{130}{}{Ông nói dối. Tôi biết là Navarro ở đây. Nói thật đi hoặc tôi sẽ cho
ông một trận!}
{131}{}{Hở? Ờ... Chắc là vậy chứ. Tôi nghe người ta nói thế trước đây! Căn cứ
quân sự Navarro, phía Đông Nam của San Francisco.}
{132}{}{Ông lừa ngộ. Ngộ không có kiên nhẫn. Ông nói thật hoặc ngộ làm ông xin lỗi!}
{133}{}{Ông nói dối. Tôi không có đủ kiên nhẫn cho mấy trò này đâu.
Nói thật ngay hoặc tôi sẽ cho ông một trận.}
{134}{}{Đmm! (lấy từ trong áo ra đài radio) Mày muốn dần tao á? Tao có
mấy thằng đệ sẽ cho mày thấy ăn đòn là như thế nào! (bắt đầu bật đài radio lên)}
{135}{}{Ngộ giết ông chết!}
{136}{}{Ông làm gì giờ?}
{137}{}{Ngộ đi.}
{138}{}{Nước đi sai lầm rồi, ông bạn.}
{139}{}{Ông nghĩ mình đang làm cái quái gì thế?}
{140}{}{Này, tôi biến khỏi đây ngay.}
{141}{}{(nói vào radio) Báo động! Chúng ta có kẻ đột nhập tại trạm! Báo động!}
{142}{}{[XONG]}
{143}{}{Ồ, nói chuyện vui đấy. Tôi có lời khuyên này – khu này chẳng có quái gì
ngoài hoang mạc với phóng xạ đâu. Văn minh ở phía Nam ấy. Nếu là cậu tôi sẽ đi về phía đó.}
{144}{}{Cám ơn.}
{145}{}{Chim sắt? Ồ, ý cậu là máy bay trực thăng. Nào tại sao cậu lại đến đây
để hỏi thế?}
{146}{}{Máy bay trực thăng? Chủ đề hay đấy. Nào tại sao cậu lại đến đây
để hỏi thế?}
{147}{}{Pháp sư nói chim sắt bắt làng, bay Navarro. Ngộ cố tìm.}
{148}{}{Có người cần. Ngộ tìm cho họ.}
{149}{}{Ông biết về? Ông biết gì?}
{150}{}{Pháp sư trong tộc của tôi nói rằng mấy cái máy bay trực thăng đã
bắt cóc người trong tộc. Tôi đến đây để tìm họ.}
{151}{}{Tôi biết mấy người đang quan tâm đến máy bay trực thăng. Tôi
đang cố định vị chúng cho họ.}
{152}{}{Vậy là ông biết về máy bay trực thăng. Hãy nói những gì ông biết đi.}
{153}{}{Pháp sư? Nghe này; nếu pháp sư của cậu nói rằng ông ta thấy chim bay
quanh và ăn mất người thì ông ta bú cần quá độ rồi. Hiểu chứ?}
{154}{}{Hakunin great shaman. If he say he see then he see.}
{155}{}{Hakunin was a great shaman. If he says he saw vertibirds, then he
 saw them!}
{156}{}{Well, that doesn't mean anything to me, but in case I see one of
 these vertibirds, whom should I be telling?}
{157}{}{You tell me. Me be around.}
{158}{}{Tell Shi.}
{159}{}{Tell Brotherhood of Steel.}
{160}{}{Tell Hubologists.}
{161}{}{Take pick. You tell Shi or Brotherhood of Steel or Hubologists.
 Everybody interested.}
{162}{}{You tell me. I'll be around.}
{163}{}{You can tell the Shi.}
{164}{}{You can tell the Brotherhood of Steel.}
{165}{}{You can tell the Hubologists.}
{166}{}{Take your pick. You can tell the Shi or the Brotherhood of Steel
 or the Hubologists. Everybody seems to be interested in vertibirds.}
{167}{}{The Shi, huh? Well if you say so. I'll send word to 'em down in
 Chiny town. Meanwhile, I got things to do.}
{168}{}{Wait. Me have strong friends. They say Navarro here. You tell
 where or things get messy!}
{169}{}{Wait a minute, pal. Obviously, I've got some powerful friends and
 they tell me Navarro is here. Now you tell me where or things will get messy!}
{170}{}{The Brotherhood... Uh, yeah, well, I'll do just that. Meanwhile,
 I got things to do.}
{171}{}{Wait. Me have strong friends. They say Navarro here. You tell
 where or things get messy!}
{172}{}{Wait a minute, pal. Obviously, I've got some powerful friends and
 they tell me Navarro is here. Now you tell me where or things will get messy!}
{173}{}{The Hubs? Yeah, sure, I'll send word if something comes up.
 Meanwhile, I got things to do.}
{174}{}{Wait. Me have strong friends. They say Navarro here. You tell
 where or things get messy!}
{175}{}{Wait a minute, pal. Obviously, I've got some powerful friends and
 they tell me Navarro is here. Now you tell me where or things will get messy!}
{176}{}{Damn, that's a hell of a list... Uh, well, if something comes up
 I'll... Yeah, well, I got some things to do.}
{177}{}{Wait. Me have strong friends. They say Navarro here. You tell where
 or things get messy!}
{178}{}{Wait a minute, pal. Obviously, I've got some powerful friends and they
 tell me Navarro is here. Now you tell me where or things will get messy!}
{179}{}{Uh... Hey, I'm just told to shy off visitors and such. I don't want
 the kind of trouble you're talking.}
{180}{}{Then tell best way in base... now!}
{181}{}{Then I would suggest you tell me the best way into the base... now!}
{182}{}{I suppose that would be through the trap door in the floor of my room.
 Just go and leave me be.}
{183}{}{Được, ngộ đi.}
{184}{}{All right. I'll do that.}
{185}{}{I know they fly over here from time to time. They're usually heading
 south toward San Fran. If you're interested in vertibirds, I'd head there.}
{186}{}{Okay, me try there.}
{187}{}{Me have friends who want me find vertibirds. Friends say vertibirds
 come here.}
{188}{}{Okay, I'll head that way.}
{189}{}{Look, I have some friends who want me to find vertibirds. They say
 they come from here.}
{190}{}{Enclave? That a group or something? That don't ring no chimes
 with me. What you want with 'em?}
{191}{}{Me want join.}
{192}{}{I want to join.}
{193}{}{Join up? You're a tribal! What makes you think they'd want a tribal?}
{194}{}{Join up? You're a tribal! What makes you think they'd want a tribal,
 and his posse no less?}
{195}{}{Me serious. Me join Enclave.}
{196}{}{Me serious. Me Join Enclave.}
{197}{}{I'm serious. I'm looking to join the Enclave.}
{198}{}{I'm serious. I'm looking to join the Enclave.}
{199}{}{Wait a minute, dummy. Are you trying to say you're one of the Enclave
 replacements?}
{200}{}{Wait a minute. Are you trying to say you're one of the Enclave
 replacements?}
{201}{}{Ừ... vậy à.}
{202}{}{That's right.}
{203}{}{Damn. Sorry for the hassles. I'm supposed to clear a bunch of newbies
 coming through here but I got to weed out the trash. Anyway, just go up to the gate,
 through the woods there, and give 'em the password. It's 'sheepshead.' Oh, and stay on the path!}
{204}{}{Thanks!}
{205}{}{Wait a minute, dummy. Are you trying to say you're one of the Enclave
 replacements? If that's the case, then why aren't you alone?}
{206}{}{Wait a minute. Are you trying to say you're one of the Enclave
 replacements? If that's the case, then why aren't you alone?}
{207}{}{Uh... escort?}
{208}{}{I hired an escort!}
{209}{}{Well, I don't mean to be rude or nothing, but this here's private property.
 If you're going to be poking around somewhere, don't be doing it here.}
{210}{}{[XONG]}
{211}{}{You're back. What can old Chris help you with?}
{212}{}{You tell me Navarro south. You lie! Me here for truth.}
{213}{}{You told me Navarro was to the south, old man. Now I want to know the truth.}
{214}{}{You look familiar. Old Chris thinks he's seen you before... Nope, can't be.}
{215}{}{Intruder at the station! Send help!}
{216}{}{Sound the alarm!}
{217}{}{Intruder alert! Intruder alert!}
{218}{}{Die, scum!}
{219}{}{The Enclave will promote me for killing you!}
{220}{}{Die, outsider!}
{221}{}{What the...?!}
{222}{}{You use radio and me make you sorry!}
{223}{}{You use that radio and I'll make you sorry!}
{224}{}{Fuck you! You want to see sorry? I got some boys who'll show you a
 whole new meaning for the word! (starts to turn the radio on)}
{225}{}{Ngộ giết ông chết!}
{226}{}{Ông làm gì giờ?}
{227}{}{Ngộ đi.}
{228}{}{Nước đi sai lầm rồi, ông bạn.}
{229}{}{Ông nghĩ mình đang làm cái quái gì thế?}
{230}{}{Này, tôi biến khỏi đây ngay.}
{231}{}{Yeah, right.}
{232}{}{He's pulling out a radio. He's going to alert the whole base! I've got to deal with him quickly.}
{233}{}{Oh, no. Man pull out talkie box. He tell on me. Must stop him.}
{800}{}{You conned Chris to give you the password.}
{810}{}{You killed Chris before he could warn the base.}
