{100}{}{Bạn thấy một ông già.}
{101}{}{Bạn thấy Chris, người trông coi trạm xăng.}
{102}{}{Bạn thấy một ông già ăn mặc lôi thôi trong chiếc áo choàng màu tím.}
{103}{}{Chào chào, người lạ. Ồ bé yêu ơi! Xem bộ bánh xe này. Bao năm rồi mới lại
thấy một chiếc. Lão Chris có thể giúp gì nhỉ?}
{104}{}{Chào chào, người lạ. Chưa thấy cậu ở đây bao giờ. Lão Chris có thể giúp
gì đây?}
{105}{}{Đây chỗ nào?}
{106}{}{Ngộ tìm Navarro. Đây phải không?}
{107}{}{Ông thấy chim sắt bay ở đây?}
{108}{}{Ông có nghe Enclave? Họ đây?}
{109}{}{Ngộ chỉ ngó quanh.}
{110}{}{Đây là nơi nào?}
{111}{}{Tôi đang tìm Navarro. Có phải ở đây không?}
{112}{}{Ông có nhìn thấy cái máy bay trực thăng nào bay qua đây không?}
{113}{}{Có từng nghe đến Enclave không? Họ có ở quanh đây không?}
{114}{}{Tôi chỉ ngó quanh đây thôi.}
{115}{}{Đây là chỗ của lão, của Chris. Đây là trạm dịch vụ – sao, chưa từng nhìn
thấy trước đây, trong tạp chí cũ hoặc đại khái thế à? Lão có ngay đây – một
trạm dịch vụ.}
{116}{}{Ngộ tìm Navarro. Đây phải không?}
{117}{}{Ông thấy chim sắt bay ở đây?}
{118}{}{Ông có nghe Enclave? Họ đây?}
{119}{}{Ừ... ngộ phải đi.}
{120}{}{Tôi đang tìm Navarro. Có phải ở đây không?}
{121}{}{Ông có nhìn thấy cái máy bay trực thăng nào bay qua đây không?}
{122}{}{Có từng nghe đến Enclave không? Họ có ở quanh đây không?}
{123}{}{Xin lỗi, phải đi.}
{124}{}{Navarro? Lâu lắm rồi chưa nghe thấy cái tên đó. Căn cứ quân sự cũ ở phía
Đông Nam của San Fran, đi tuốt về phía Nam cơ.}
{125}{}{Ngộ ở đó. Không phải Navarro.}
{126}{}{Okay. Ngộ cám ơn. Ngộ xem đó.}
{127}{}{Ông lừa ngộ. Ngộ biết Navarro đây. Ông nói thật hoặc ngộ làm ông xin lỗi!}
{128}{}{Tôi đã ở đó và chỗ đó không phải là Navarro.}
{129}{}{Okay, tôi sẽ đến đó xem. Cám ơn.}
{130}{}{Ông nói dối. Tôi biết là Navarro ở đây. Nói thật đi hoặc tôi sẽ khiến
ông thấy hối hận!}
{131}{}{Hở? Ờ... Chắc là vậy chứ. Lão nghe người ta nói thế trước đây! Căn cứ
quân sự Navarro, phía Đông Nam của San Francisco.}
{132}{}{Ông lừa ngộ. Ngộ không có kiên nhẫn. Ông nói thật hoặc ngộ làm ông xin lỗi!}
{133}{}{Ông nói dối. Tôi không có đủ kiên nhẫn cho mấy trò này đâu.
Nói thật ngay hoặc tôi sẽ khiến ông thấy hối hận.}
{134}{}{Đmm! (lấy từ trong áo ra đài radio) Mày muốn thấy hối hận à? Tao có mấy
thằng đệ sẽ cho mày thấy hối hận là thế nào! (bắt đầu bật đài lên)}
{135}{}{Ngộ giết ông chết!}
{136}{}{Ông làm gì giờ?}
{137}{}{Ngộ đi.}
{138}{}{Nước đi sai lầm rồi, ông bạn.}
{139}{}{Ông nghĩ mình đang làm cái quái gì thế?}
{140}{}{Này, tôi biến khỏi đây ngay.}
{141}{}{(nói vào radio) Báo động! Chúng ta có kẻ đột nhập tại trạm! Báo động!}
{142}{}{[XONG]}
{143}{}{Ồ, nói chuyện vui đấy. Lão khuyên này – khu này chẳng có quái gì ngoài
hoang mạc với phóng xạ đâu. Văn minh ở phía Nam ấy. Cậu nên đi về phía đó.}
{144}{}{Cám ơn.}
{145}{}{Chim sắt? Ồ, ý cậu là máy bay trực thăng. Nào tại sao cậu lại đến đây
để hỏi thế?}
{146}{}{Máy bay trực thăng? Chủ đề hay đấy. Nào tại sao cậu lại đến đây
để hỏi thế?}
{147}{}{Pháp sư nói chim sắt bắt làng, bay Navarro. Ngộ cố tìm.}
{148}{}{Có người cần. Ngộ tìm cho họ.}
{149}{}{Ông biết về? Ông biết gì?}
{150}{}{Pháp sư trong tộc của tôi nói rằng mấy cái máy bay trực thăng đã
bắt cóc người trong tộc. Tôi đến đây để tìm họ.}
{151}{}{Tôi biết mấy người đang quan tâm đến máy bay trực thăng. Tôi
đang cố định vị chúng cho họ.}
{152}{}{Vậy là ông biết về máy bay trực thăng. Hãy nói những gì ông biết đi.}
{153}{}{Pháp sư? Nghe này; nếu tay thầy pháp của cậu nói rằng ông ta thấy chim lượn
quanh và ăn mất người thì ông ta bú cần quá độ rồi. Hiểu chứ?}
{154}{}{Hakunin pháp sư vĩ đại. Nếu ông nói ông thấy thì ông thấy.}
{155}{}{Hakunin là một pháp sư rất giỏi. Nếu ông ta nói có thấy máy bay trực thăng,
thì chắc chắn là có thấy!}
{156}{}{Ồ, việc đó đéo liên quan gì đến lão cả, nhưng cứ cho là nếu có thấy
đi thì lão phải nói với ai?}
{157}{}{Ông nói ngộ. Ngộ ở quanh.}
{158}{}{Nói Shi.}
{159}{}{Nói Hội bằng hữu Thép.}
{160}{}{Nói Hubologist.}
{161}{}{Chọn thôi. Ông nói cho Shi hay Hội bằng hữu Thép
hoặc Hubologist. Mọi người quan tâm.}
{162}{}{Hãy nói với tôi. Tôi sẽ ở quanh đây.}
{163}{}{Ông có thể nói cho đám người Shi.}
{164}{}{Ông có thể nói cho Hội bằng hữu Thép.}
{165}{}{Ông có thể nói cho Hubologist.}
{166}{}{Chọn thôi. Ông có thể nói cho đám người Shi hay Hội bằng hữu Thép
hoặc đám Hubologist. Có vẻ như bọn họ đều quan tâm đến máy bay trực thăng.}
{167}{}{Đám người Shi hả? Ồ, nếu cậu nói vậy. Lão sẽ gửi lời đến khu
phố Tàu. Giờ thì lão có việc rồi.}
{168}{}{Chờ đã. Ngộ có bạn mạnh. Họ bảo Navarro đây. Ông nói ở đâu
hoặc mọi thứ tan tành!}
{169}{}{Chờ đã, ông bạn. Dĩ nhiên là tôi có mấy đồng đội cực băm và họ bảo
với tôi là Navarro ở đây. Giờ thì phun ra địa chỉ hoặc tôi cho ông tan xác ngay!}
{170}{}{Hội bằng hữu... ừ, ồ, lão sẽ làm vậy. Giờ lão có việc rồi.}
{171}{}{Chờ đã. Ngộ có bạn mạnh. Họ bảo Navarro đây. Ông nói ở đâu
hoặc mọi thứ tan tành!}
{172}{}{Chờ đã, ông bạn. Dĩ nhiên là tôi có mấy đồng đội cực băm và họ bảo
với tôi là Navarro ở đây. Giờ thì phun ra địa chỉ hoặc tôi cho ông tan xác ngay!}
{173}{}{Đám Hub à? Ờ, rồi, lão sẽ nhắn cho họ nếu phát hiện được gì.
Giờ lão có việc rồi.}
{174}{}{Chờ đã. Ngộ có bạn mạnh. Họ bảo Navarro đây. Ông nói ở đâu
hoặc mọi thứ tan tành!}
{175}{}{Chờ đã, ông bạn. Dĩ nhiên là tôi có mấy đồng đội cực băm và họ bảo
với tôi là Navarro ở đây. Giờ thì phun ra địa chỉ hoặc tôi cho ông tan xác ngay!}
{176}{}{Mẹ kiếp, danh sách khủng vãi... Ừ, rồi, nếu phát hiện thấy gì
thì lão sẽ... ờ, lão có việc phải làm.}
{177}{}{Chờ đã. Ngộ có bạn mạnh. Họ bảo Navarro đây. Ông nói ở đâu
hoặc mọi thứ tan tành!}
{178}{}{Chờ đã, ông bạn. Dĩ nhiên là tôi có mấy đồng đội cực băm và họ bảo
với tôi là Navarro ở đây. Giờ thì phun ra địa chỉ hoặc tôi cho ông tan xác ngay!}
{179}{}{Ờ... Này, lão chỉ được dặn là đuổi những ai đến đây, đại loại thế.
Lão không muốn gặp rắc rối như cậu bảo.}
{180}{}{Vậy nói lối nhanh nhất vào căn cứ... ngay!}
{181}{}{Vậy thì tôi khuyên ông nên nói cho tôi lối dễ nhất để vào căn cứ... ngay bây giờ!}
{182}{}{Chắc là đi lối qua cửa sập trên sàn trong phòng tôi. Hãy đi đi và để
tôi được yên.}
{183}{}{Được, ngộ đi.}
{184}{}{Được rồi. Tôi sẽ làm vậy.}
{185}{}{Tôi biết là thỉnh thoảng họ có bay qua đây. Họ thường tiến về phía Nam
hướng San Fran. Nếu cậu quan tâm đến máy bay trực thăng thì nên đi về phía đó.}
{186}{}{Okay, ngộ thử đó.}
{187}{}{Ngộ có bạn muốn ngộ tìm máy bay. Bạn nói máy bay đến đây.}
{188}{}{Được, tôi sẽ đi theo lối đó.}
{189}{}{Nghe này, tôi có mấy người bạn nhờ tôi tìm máy bay trực thăng. Họ nói
chúng đến từ đây.}
{190}{}{Enclave? Một nhóm gì đấy à? Chưa nghe đến lần nào. Thế cậu
muốn làm gì với họ?}
{191}{}{Ngộ muốn gia nhập.}
{192}{}{Tôi muốn tham gia.}
{193}{}{Gia nhập? Cậu chỉ là một tộc nhân! Cái gì khiến cậu nghĩ họ lại muốn một gã toọc chứ?}
{194}{}{Gia nhập? Cậu chỉ là một tộc nhân! Cái gì khiến cậu nghĩ họ lại muốn
một gã toọc tay không tấc sắt chứ?}
{195}{}{Ngộ nghiêm túc. Ngộ gia nhập Enclave.}
{196}{}{Ngộ nghiêm túc. Ngộ gia nhập Enclave.}
{197}{}{Nghiêm túc đấy. Tôi muốn gia nhập Enclave.}
{198}{}{Nghiêm túc đấy. Tôi muốn gia nhập Enclave.}
{199}{}{Chờ đã, đầu đất. Có phải cậu đang muốn nói rằng cậu là một lính dự bị
của Enclave?}
{200}{}{Chờ đã. Có phải cậu đang muốn nói rằng cậu là một lính dự bị
của Enclave?}
{201}{}{Ừ... vậy à.}
{202}{}{Đúng vậy.}
{203}{}{Mẹ nó. Thứ lỗi vì đã vặn vẹo. Lão cần đón một lũ tân binh đến đây nhưng
vẫn phải tống cổ lũ đần ra ngoài. Mà thôi, cứ đi qua khu rừng thẳng đến chỗ cổng,
rồi đọc mật khẩu: "đầu cừu". Ồ, nhớ đi theo đúng lối mòn đấy!}
{204}{}{Cám ơn!}
{205}{}{Chờ đã, đầu đất. Có phải cậu đang muốn nói rằng cậu là một lính dự bị
của Enclave? Nếu vậy thì tại sao cậu lại không đi một mình?}
{206}{}{Chờ đã. Có phải cậu đang muốn nói rằng cậu là một lính dự bị
của Enclave? Nếu vậy thì tại sao cậu lại không đi một mình?}
{207}{}{Ừm... hộ tống?}
{208}{}{Tôi thuê đoàn hộ tống!}
{209}{}{Ồ, lão không muốn bất lịch sự đâu nhưng chỗ này là tài sản tư nhân.
Nếu muốn đi lụi đồ ở khu này thì đừng có mò đến đây.}
{210}{}{[XONG]}
{211}{}{Quay lại rồi à. Lão Chris giúp gì được đây?}
{212}{}{Ông nói Navarro phía Nam. Ông lừa! Ngộ ở đây vì sự thật.}
{213}{}{Ông đã bảo tôi là Navarro ở phía Nam, lão già. Giờ thì tôi muốn biết sự thật.}
{214}{}{Trông quen thế. Lão Chris nghĩ là lão gặp cậu trước đây rồi... Không, làm đéo có chuyện.}
{215}{}{Có kẻ đột nhập đến trạm! Gửi tiếp viện ngay!}
{216}{}{Rung chuông báo động ngay!}
{217}{}{Có kẻ đột nhập! Có kẻ đột nhập!}
{218}{}{Chết đi, đồ chó chết!}
{219}{}{Enclace sẽ thăng chức cho tao nếu giết được mày!}
{220}{}{Chết đi, thằng người ngoài!}
{221}{}{Cái đm...?!}
{222}{}{Ông dùng radio và ngộ làm ông xin lỗi!}
{223}{}{Ông mà dùng đài radio là tôi sẽ khiến ông thấy hối hận đấy!}
{224}{}{Đmm! Mày muốn thấy hối hận à? Tao có mấy thằng đệ sẽ cho
mày thấy hối hận là thế nào! (bắt đầu bật đài lên)}
{225}{}{Ngộ giết ông chết!}
{226}{}{Ông làm gì giờ?}
{227}{}{Ngộ đi.}
{228}{}{Nước đi sai lầm rồi, ông bạn.}
{229}{}{Ông nghĩ mình đang làm cái quái gì thế?}
{230}{}{Này, tôi biến khỏi đây ngay.}
{231}{}{Ờ, đúng vậy.}
{232}{}{Lão ta lấy đài radio ra. Lão sẽ báo động cho toàn căn cứ! Phải xử lí lão thật nhanh.}
{233}{}{Ôi, không. Lão lấy ra hộp nói. Lão nói về ngộ. Phải dừng lão.}
{800}{}{Bạn đã lừa Chris nói mật khẩu cho bạn.}
{810}{}{Bạn đã giết Chris trước khi lão ta kịp báo cho căn cứ.}
