{100}{}{Bạn thấy Ngài chơi xấu.}
{101}{}{Trông hắn ta vẫn giống kẻ chơi xấu.}
{200}{}{Chào, tôi là Ngài chơi xấu. Tôi có thể giúp gì được?}
{201}{}{Ông có thể bắt cóc bộ tộc của tôi không?}
{202}{}{Ông có thể cho tôi nhiệm vụ của người Shi không?}
{203}{}{Ông có thể cho tôi nhiệm vụ của Elron không?}
{204}{}{Ông có thể cho tôi nhiệm vụ của Hội bằng hữu không?}
{205}{}{Hãy đặt để tôi đã đến căn cứ quân sự rồi.}
{206}{}{Tôi đã bắt cóc bộ tộc.}
{207}{}{Tôi đã bật nhiệm vụ của người Shi.}
{208}{}{Tôi đã bật nhiệm vụ Elron.}
{209}{}{Tôi đã bật nhiệm vụ của Hội bằng hữu.}
{210}{}{Giờ cậu đã đến căn cứ quân sự.}
{211}{}{Cám ơn, Ngài chơi xấu.}
