{100}{}{Bạn thấy một đầu bếp.}
{101}{}{Bạn thấy Cookie, đầu bếp.}
{102}{}{Bạn thấy một người mặc giáp đội mũ đầu bếp và quàng tạp dề.}
{103}{}{Này cậu lính. Cậu đang kiếm đồ bỏ mồm hay muốn nói chuyện thế?}
{104}{}{Ngộ muốn ăn.}
{105}{}{Ngộ muốn chuyện.}
{106}{}{Tôi muốn ăn món gì đó.}
{107}{}{Hãy nói chuyện một lát.}
{108}{}{Ồ, đây. Cứt bôi trên gạch ngói. Tuyết và cứt ruồi ở đằng kia. Gì nữa không?}
{109}{}{Ông muốn ngộ ăn gì?}
{110}{}{Cứt? Tuyết? Đây là món lìn gì thế?}
{111}{}{Tôi xin lỗi, chắc hẳn cậu là lính mới. Tôi không có ý chửi bới gì đâu, ở đây chúng tôi gọi đồ ăn như vậy.
Cứt bôi trên gạch ngói là bò thái miếng trên đĩa nướng. Tuyết và cứt ruồi là tên khác của muối và tiêu.}
{112}{}{Ồ... cám ơn. Chúng ta nói chuyện khi ăn.}
{113}{}{Được rồi, xin lỗi. Hãy nói chuyện trong lúc tôi ăn.}
{114}{}{Muốn nói chuyện gì nào?}
{115}{}{Có chuyện gì thế?}
{116}{}{Bản vẽ máy bay ở đâu?}
{118}{}{Căn cứ chính ở đâu?}
{119}{}{Ngộ cần quay lại nhiệm vụ. Cám ơn.}
{120}{}{Chuyện gì đang diễn ra ở đây thế?}
{121}{}{Tôi đang quan tâm tới cái máy bay trực thăng. Nếu muốn xem bản vẽ thì tôi có thể tìm ở đâu nhỉ?}
{123}{}{Căn cứ chính của Enclave nằm ở đâu thế?}
{124}{}{Cám ơn. Tôi cần phải quay về chỗ trực đây.}
{125}{}{Muốn nghe tin gậm giường không? Tôi có thể nói cho cậu về chuyện mới nhất ở phòng bảo trì, phòng thí nghiệm hoặc của đám lính.}
{126}{}{Muốn nghe chuyện gì nào?}
{127}{}{Phòng bảo trì thì sao?}
{128}{}{Phòng thí nghiệm thì sao?}
{129}{}{Đám lính thì sao?}
{130}{}{Gì nữa không?}
{131}{}{Ngộ nghe đủ rồi.}
{132}{}{Phòng bảo trì có chuyện gì thế?}
{133}{}{Ông có tin gì về phòng thí nghiệm không?}
{134}{}{Đám lính có gì hay ho không?}
{135}{}{Có chuyện gì nữa không?}
{136}{}{Tôi nghĩ là mình nghe đủ rồi.}
{137}{}{Raul, thợ cơ khí máy bay trực thăng không thích Quincy, trưởng phòng bảo trì. Hai người bọn họ
lúc nào cũng hục hặc nhau. Tôi không nghĩ đấy là do nghề nghiệp. Dù sao thì Raul là một gã kiêu ngạo
còn Quincy thì khá ổn. Tôi hi vọng là ông ta cuối cùng sẽ thắng.}
{138}{}{Okay.}
{139}{}{Ờ, chắc vậy.}
{140}{}{Phòng thí nghiệm do một lão hói từ Enclave tên là Schreber nắm quyền. Đm cái loại sống chó; đéo quan tâm
đến ai hoặc gì hết cả. Lão đang làm thí nghiệm gì đó trên deathclaw ở dưới đó, nhưng tôi không biết là làm gì.
Dù sao thì lão ta cũng gây ra đủ loại tiếng động cho đến khi chỉ huy ra lệnh ốp cách âm cả căn phòng đó.}
{141}{}{Hiểu rồi.}
{142}{}{Hay đấy.}
{143}{}{Ha! Đến phần ái tình rồi, anh bạn. Có vẻ như một con nghiện máy tính đã yêu một cô lính gác ở phía ngoài phòng thí nghiệm. Thậm chí còn đặt tên tình củm cho cô ta nữa, gọi là "Snookie" mới hài chứ.}
{144}{}{Đáng yêu đấy.}
{145}{}{Nà, hết chuyện ở đây rồi. Nếu nghe thêm được gì tôi sẽ nói thêm sau. Tôi thích kể lại những gì mà tôi nghe được!}
{146}{}{Cám ơn.}
{147}{}{Sao cậu lại quan tâm đến thứ đó? Ồ mà chả sao. Quincy giữ chúng trong phòng bảo trì, tôi nghĩ thế.}
{148}{}{Okay.}
{149}{}{Đâu vậy?}
{150}{}{Hiểu rồi.}
{151}{}{Ở chỗ nào thế?}
{152}{}{Góc phía Đông Bắc của căn cứ, bạn tôi à. Đến là thấy.}
{153}{}{Okay. Cám ơn.}
{156}{}{Tôi thấy lạ là cậu lại không biết đấy, chắc cậu là dân địa phương. Còn căn cứ chính thì nằm ở chính con mẹ nó
giữa biển. Ồ, không hẳn là giữa lỗ đít lắm, nhưng cũng gần như vậy. Cách duy nhất để đến đó là bằng tàu hoặc
máy bay nhưng con tàu chết tiệt đã bị sửa đổi rồi. Cần một cái thẻ fob để vận hành mớ sắt vụn đấy.}
{157}{}{Fob?}
{158}{}{Ừ, một mã khóa. Chỉ huy để ở trong văn phòng của ông ta. Thiếu cái đó thì cậu sẽ không thể vào một số khu vực
trên tàu và đấy là cách để giữ chân đám thổ dân San Fran khỏi thích thì chèo đò đến.}
{159}{}{Ý hay đó.}
{160}{}{Phòng chỉ huy đâu?}
{161}{}{Đấy là một ý hay.}
{162}{}{Thế phòng chỉ huy ở chỗ nào vậy?}
{163}{}{Đi thang máy ở phòng bên cạnh xuống, dọc theo lối hành lang đến chỗ lối giao chính rồi đi thẳng.}
{164}{}{Cám ơn.}
{165}{}{Này, bạn tôi. Rất vui được gặp lại. Thích ăn hay nói chuyện nào?}
{166}{}{Đồ ăn.}
{167}{}{Tán gẫu.}
{168}{}{Ngộ chỉ chào thôi.}
{169}{}{Không gì cả, tôi chỉ chào thôi.}
{170}{}{Đây. Đã chết, đã nướng, đéo biết thịt gì. Ăn đi.}
{171}{}{Ờ... cám ơn.}
{172}{}{Con giai, ngửi mùi thôi là bố biết mày đang không mặc áo giáp năng lượng rồi. Nếu Trung sĩ mà
nhìn thấy mày không mặc quân phục là đi đời đấy. Và bố đang nói về kiểu đi đời mà mày sẽ không thích đâu. Giờ thì lê đít xuống phòng hậu cần mặc đồ vào.}
{173}{}{Quý cô, ngửi mùi thôi là bố biết là cô đang không mặc áo giáp năng lượng rồi. Nếu Trung sĩ mà
nhìn thấy cô không mặc quân phục là đi đời đấy. Và bố đang nói về kiểu đi đời mà cô không thích đâu. Giờ thì lê đít xuống phòng hậu cần mặc đồ vào.}
{174}{}{Đâu vậy?}
{175}{}{Okay.}
{176}{}{Ở chỗ nào thế?}
{177}{}{Tôi sẽ lo việc đó.}
{178}{}{Đi thang máy ở phòng bên cạnh xuống, dọc theo lối hành lang đến chỗ lối giao chính, rẽ trái rồi vào phòng đầu tiên bên trái. Đi đi.}
{179}{}{Cám ơn.}
{180}{}{Giời đất ơi! Tôi chỉ là đầu bếp... và tôi bị mù. Tôi đéo thấy kẻ đột nhập nào đi qua đây cả.}
{181}{}{Cám ơn.}
{182}{}{Đm báo động. Lúc nào cũng loạn cả lên mỗi lần rung.}
{183}{}{Cái lìn gì khiến cái củ cặc này rung thế?}
{184}{}{Ước gì chúng ta dùng chuông báo không ồn, cái củ cặc này khiến tôi đau hết cả đầu.}
{185}{}{Bố sẽ nướng cặp mông mày lên và bày trên đĩa.}
{186}{}{Ngỗng chín rồi đấy. Ha! Câu này hay đấy!}
{187}{}{Bay khỏi chảo chui zô lửa.}
