{100}{}{Bạn thấy một nhà khoa học.}
{101}{}{Bạn thấy Tiến sĩ Schreber.}
{102}{}{Bạn thấy một ông hói mặc áo choàng thí nghiệm.}
{103}{}{Ta hi vọng là cậu có lí do chính đáng để làm phiền ta đấy, đồ lính quèn.}
{104}{}{Ngộ muốn hỏi câu.}
{105}{}{Không, ngộ quay lại sau.}
{106}{}{Được rồi. Ta phải sống cạnh mấy gã lính quèn nên chắc là ta sẽ cố thử
làm quen với cậu.}
{107}{}{Muốn biết gì nào?}
{108}{}{Ai ông?}
{109}{}{Ông làm gì?}
{110}{}{Đây chỗ nào?}
{111}{}{Sao phòng không có tiếng?}
{112}{}{Sao D'claw ở phòng khác?}
{113}{}{Sao chó cạnh cửa không chạy? Không gì cả?}
{114}{}{Ngộ đi giờ.}
{115}{}{Ông là ai?}
{116}{}{Ông làm gì ở đây?}
{117}{}{Đây là nơi nào?}
{118}{}{Sao căn phòng này lại được cách âm thế?}
{119}{}{Sao lại có con deathclaw ở phòng bên thế?}
{120}{}{Cái tượng chó ở cạnh cửa là sao thế?}
{121}{}{Tôi phải đi giờ.}
{122}{}{Tên ta là Schreber, Tiến sĩ Schreber. Ta là bác sĩ của căn cứ và làm cả những
thứ khác nữa. Không cần nói tên đâu, lính quèn. Tất cả các người đều trông
y hệt nhau trong cái bộ giáp đấy.}
{123}{}{Okay.}
{124}{}{Hiểu rồi.}
{125}{}{Ta làm bác sĩ cho căn cứ nhưng thực chất đấy chỉ là phụ thôi.
Thực ra ta là nhà di truyền học.}
{126}{}{Gì vậy?}
{127}{}{Di truyền học là gì?}
{128}{}{Ta thực sự không nghĩ cậu có đủ trí thông minh để hiểu công việc
của ta đâu, lính quèn. Chỉ cần hiểu là ta có thể "tùy chỉnh" người
hoặc động vật.}
{129}{}{Ờ... được rồi.}
{130}{}{Ờ... tôi cần hỏi ông thêm mấy câu nữa.}
{131}{}{Đây là phòng thuốc của căn cứ. Tuy nhiên, ta thấy rằng thí nghiệm
của ta quan trọng hơn nhu cầu y tế tối thiểu của đám lính ở đây nên
ta đã chuyển thành phòng thí nghiệm.}
{132}{}{Hay... thật đấy.}
{133}{}{Hay đấy. Cho tôi biết việc khác đi.}
{134}{}{Sao phòng không có tiếng động? Ồ, ý cậu là cách âm! Trong lúc nghiên cứu
ta thực hiện... thí nghiệm trên mẫu vật. Đôi khi chúng hơi kêu một chút.
Chỉ huy căn cứ thấy việc này làm phiền quá nên ông ta cho lắp phần
cách âm.}
{135}{}{Trong lúc nghiên cứu ta thực hiện... thí nghiệm trên mẫu vật. Đôi khi
chúng hơi kêu một chút. Chỉ huy căn cứ thấy việc này làm phiền quá
nên ông ta cho lắp phần cách âm.}
{136}{}{Ồ...}
{137}{}{Hiểu rồi.}
{138}{}{Bự cồ, nâu và xấu xí? Đó là một thí nghiệm mà ta mới hoàn thiện
gần đây. Thứ đó sẽ bị loại bỏ theo lịch trình.}
{139}{}{Loại bỏ nghĩa gì?}
{140}{}{Sao ông lại muốn giết nó?}
{141}{}{Ồ... cậu có vẻ khôn nhỉ? Loại bỏ. Giết, hạ gục, cho ngủ,
làm chết. Hiểu chứ?}
{142}{}{Ngộ hiểu. Sao ông muốn giết D'claw?}
{143}{}{Enclave đang tìm nguồn lính rẻ, dễ dàng thay thế. Chúng ta
quan tâm đến deathclaw vì chúng có sẵn giáp và vũ khí, cũng như
có tập tính hung hăng. Chúng chỉ cần thông minh hơn một chút
để hiểu lệnh, nhưng không được khôn đến mức có
suy nghĩ riêng. Đến đây vẫn hiểu chứ?}
{144}{}{Ờ... có.}
{145}{}{Có, tôi vẫn đang nghe đây.}
{146}{}{Well, we succeeded! We actually managed to increase their
 intelligence. However, I began to suspect that we went too far.
 That maybe they were a lot smarter than they were letting on. So
 when I was transferred here I brought one of them with me so I
 could put my theory to the test.}
{147}{}{And?}
{148}{}{I was right! The deathclaws have apparently been playing
 dumb, biding their time, and trying to learn as much as they can
 from us. They can even mimic human speech! I've actually had a
 conversation with that fellow in the next room.}
{149}{}{Anyway. The fact that they were capable of conceiving
 this plan and pulling off the deception shows just how dangerous
 they are.}
{150}{}{So what you plan do now?}
{151}{}{So what do you plan to do now?}
{152}{}{I'm going to write a report on my findings and have it
 transmitted to the Enclave. Of course I'll have to recommend the
 extermination of the deathclaw breed. They are much too dangerous
 a threat.}
{153}{}{Me got. Need ask more.}
{154}{}{Uh... You sure room soundproof?}
{155}{}{Me want kill D'claw for you!}
{156}{}{Hey, can I kill the deathclaw for you?}
{157}{}{Interesting. Can I ask you about some other things?}
{158}{}{Say Doc, are you sure this room is soundproof?}
{159}{}{Of course I'm sure. The commander would have a fit otherwise. Why?}
{160}{}{No reason.}
{161}{}{Me not want anyone hear you scream as me kill you!}
{162}{}{I was just curious.}
{163}{}{I don't want anyone to hear your screams as I experiment on you.}
{164}{}{Back again? What can I do for you this time?}
{165}{}{You sure room soundproof?}
{166}{}{Me got more question.}
{167}{}{Nothing. Me say hi.}
{168}{}{Are you sure this room is soundproof?}
{169}{}{I wanted to ask you something else.}
{170}{}{Nothing, I just wanted to say 'Hi' again.}
{171}{}{Of course I'm sure. The commander would have a fit otherwise. Why?}
{172}{}{No reason.}
{173}{}{Me not want anyone hear you scream as me kill you!}
{174}{}{I was just curious.}
{175}{}{I don't want anyone to hear your screams as I experiment on you.}
{176}{}{Be my guest. It's in the next room.}
{177}{}{Cám ơn!}
{178}{}{That is K-9, my dog. I decided to see if I could cyber
 enhance his intelligence. It worked but he developed a bad case of
 morals. He decided he didn't like my work or me much, and he bit me.}
{179}{}{As punishment I disabled his legs but left him pretty much
 functional otherwise. Now he gets to sit there and watch every
 distasteful thing I do.}
{180}{}{Ồ...}
{181}{}{He be fixed?}
{182}{}{Hiểu rồi.}
{183}{}{Can he be fixed?}
{184}{}{Oh yes. I removed his motivator circuit and gave it to
 Raul up in maintenance. It could always be put back in... Maybe
 I'll do that someday just to see if he's changed his attitude.}
{185}{}{Okay.}
{186}{}{Được rồi.}
{187}{}{Are you a civilian?}
{188}{}{This is the med lab. The armory is down the hall on your left.}
{189}{}{Why are you out of uniform?}
{190}{}{Đm! Chúng ta đang bị xâm nhập! Báo động!}
{191}{}{Có kẻ xâm nhập! Gọi bảo vệ ngay!}
{192}{}{Guard! Intruders in the med lab!}
{193}{}{Gì thế? Chúng ta bị tấn công à?}
{194}{}{Sao lại báo động? Chuyện gì thế?}
{195}{}{Cái củ lìn gì đang diễn ra thế?}
{196}{}{I'm not a hostile, don't shoot me.}
{197}{}{I didn't sign up for combat, so leave me alone.}
{198}{}{Damn it! I'm a doctor not a soldier!}
{200}{}{[THÊM]}
{201}{}{Tôi muốn hỏi một vài câu.}
{202}{}{Not right now. Sorry to bother you.}
{800}{}{You killed Doctor Schreber.}
