{100}{}{Bạn thấy một nhà khoa học.}
{101}{}{Bạn thấy Tiến sĩ Schreber.}
{102}{}{Bạn thấy một ông hói mặc áo choàng thí nghiệm.}
{103}{}{Ta hi vọng là cậu có lí do chính đáng để làm phiền ta đấy, đồ lính quèn.}
{104}{}{Ngộ muốn hỏi câu.}
{105}{}{Không, ngộ quay lại sau.}
{106}{}{Được rồi. Ta phải sống cạnh mấy gã lính quèn nên chắc là ta sẽ cố thử
làm quen với cậu.}
{107}{}{Muốn biết gì nào?}
{108}{}{Ai ông?}
{109}{}{Ông làm gì?}
{110}{}{Đây chỗ nào?}
{111}{}{Sao phòng không có tiếng?}
{112}{}{Sao D'claw ở phòng khác?}
{113}{}{Sao chó cạnh cửa không chạy? Không gì cả?}
{114}{}{Ngộ đi giờ.}
{115}{}{Ông là ai?}
{116}{}{Ông làm gì ở đây?}
{117}{}{Đây là nơi nào?}
{118}{}{Sao căn phòng này lại được cách âm thế?}
{119}{}{Sao lại có con deathclaw ở phòng bên thế?}
{120}{}{Cái tượng chó ở cạnh cửa là sao thế?}
{121}{}{Tôi phải đi giờ.}
{122}{}{Tên ta là Schreber, Tiến sĩ Schreber. Ta là bác sĩ của căn cứ và làm cả những
thứ khác nữa. Không cần nói tên đâu, lính quèn. Tất cả các người đều trông
y hệt nhau trong cái bộ giáp đấy.}
{123}{}{Okay.}
{124}{}{Hiểu rồi.}
{125}{}{Ta làm bác sĩ cho căn cứ nhưng thực chất đấy chỉ là phụ thôi.
Thực ra ta là nhà di truyền học.}
{126}{}{Gì vậy?}
{127}{}{Di truyền học là gì?}
{128}{}{Ta thực sự không nghĩ cậu có đủ trí thông minh để hiểu công việc
của ta đâu, lính quèn. Chỉ cần hiểu là ta có thể "tùy chỉnh" người
hoặc động vật.}
{129}{}{Ờ... được rồi.}
{130}{}{Ờ... tôi cần hỏi ông thêm mấy câu nữa.}
{131}{}{Đây là phòng thuốc của căn cứ. Tuy nhiên, ta thấy rằng thí nghiệm
của ta quan trọng hơn nhu cầu y tế tối thiểu của đám lính ở đây nên
ta đã chuyển thành phòng thí nghiệm.}
{132}{}{Hay... thật đấy.}
{133}{}{Hay đấy. Cho tôi biết việc khác đi.}
{134}{}{Sao phòng không có tiếng động? Ồ, ý cậu là cách âm! Trong lúc nghiên cứu
ta thực hiện... thí nghiệm trên mẫu vật. Đôi khi chúng hơi kêu một chút.
Chỉ huy căn cứ thấy việc này làm phiền quá nên ông ta cho lắp phần
cách âm.}
{135}{}{Trong lúc nghiên cứu ta thực hiện... thí nghiệm trên mẫu vật. Đôi khi
chúng hơi kêu một chút. Chỉ huy căn cứ thấy việc này làm phiền quá
nên ông ta cho lắp phần cách âm.}
{136}{}{Ồ...}
{137}{}{Hiểu rồi.}
{138}{}{Bự cồ, nâu và xấu xí? Đó là một thí nghiệm mà ta mới hoàn thiện
gần đây. Thứ đó sẽ bị loại bỏ theo lịch trình.}
{139}{}{Loại bỏ nghĩa gì?}
{140}{}{Sao ông lại muốn giết nó?}
{141}{}{Ồ... cậu có vẻ khôn nhỉ? Loại bỏ. Giết, hạ gục, cho ngủ,
làm chết. Hiểu chứ?}
{142}{}{Ngộ hiểu. Sao ông muốn giết D'claw?}
{143}{}{Enclave đang tìm nguồn lính rẻ, dễ dàng thay thế. Chúng ta
quan tâm đến deathclaw vì chúng có sẵn giáp và vũ khí, cũng như
có tập tính hung hăng. Chúng chỉ cần thông minh hơn một chút
để hiểu lệnh, nhưng không được khôn đến mức có
suy nghĩ riêng. Đến đây vẫn hiểu chứ?}
{144}{}{Ờ... có.}
{145}{}{Có, tôi vẫn đang nghe đây.}
{146}{}{Ồ, chúng ta đã làm được! Chúng ta đã thật sự tăng được trí tuệ
của bọn chúng. Tuy nhiên, ta bắt đầu nghi ngờ là chúng ta đã đi 
quá xa. Có lẽ là chúng thông minh hơn nhiều so với dự tính.
Vì thế khi chuyển đến đây ta mang theo một con để tiến hành
thí nghiệm giả thuyết này.}
{147}{}{Và?}
{148}{}{Ta đã đúng! Đám deathclaw dường như đang giả ngu, tìm cách
kéo dài thời gian và cố học từ chúng ta càng nhiều càng tốt.
Chúng thậm chí còn có thể giả cả giọng con người! Trên thực tế ta
đã trò chuyện với cái gã ở phòng bên.}
{149}{}{Thế đấy. Sự thật rằng chúng có khả năng lên kế hoạch
và thực hiện hành vi lừa dối đã cho thấy mức độ nguy hiểm
của chúng.}
{150}{}{Vậy ông định làm giờ?}
{151}{}{Vậy giờ ông định sẽ làm gì?}
{152}{}{Ta sẽ viết báo cáo về phát hiện này và chuyển về Enclave.
Dĩ nhiên là ta sẽ phải đề nghị tiêu diệt toàn bộ giống deathclaw.
Chúng đã trở thành một mối nguy hiểm vượt ngoài tầm
kiểm soát.}
{153}{}{Ngộ hiểu. Cần hỏi thêm.}
{154}{}{Ờ... ông chắc phòng cách âm?}
{155}{}{Ngộ muốn giết D'claw cho ông!}
{156}{}{Này, tôi có thể giết deathclaw cho ông chứ?}
{157}{}{Hay đấy. Tôi hỏi về chuyện khác được không?}
{158}{}{Này Tiến sĩ, ông có chắc là phòng này được cách âm không thế?}
{159}{}{Dĩ nhiên là ta chắc chắn rồi. Nếu không thì lão chỉ huy lại gào ầm lên. Sao chứ?}
{160}{}{Không gì.}
{161}{}{Ngộ không muốn ai nghe ông gào khi ngộ giết ông!}
{162}{}{Tôi chỉ tò mò thôi.}
{163}{}{Tôi không muốn ai nghe thấy ông gào khi tôi làm thí nghiệm với ông.}
{164}{}{Quay lại rồi à? Lần này ta có thể giúp gì đây?}
{165}{}{Ông chắc phòng cách âm?}
{166}{}{Ngộ có thêm câu hỏi.}
{167}{}{Không có gì. Ngộ chào.}
{168}{}{Ông chắc là phòng này cách âm chứ?}
{169}{}{Tôi muốn hỏi về chuyện khác.}
{170}{}{Không có gì, tôi chỉ ghé qua "chào" lần nữa thôi.}
{171}{}{Dĩ nhiên là ta chắc chắn rồi. Nếu không thì lão chỉ huy lại gào ầm lên. Sao chứ?}
{172}{}{Không gì.}
{173}{}{Ngộ không muốn ai nghe ông gào khi ngộ giết ông!}
{174}{}{Tôi chỉ tò mò thôi.}
{175}{}{Tôi không muốn ai nghe thấy ông gào khi tôi làm thí nghiệm với ông.}
{176}{}{Cứ tự nhiên. Nó ở phòng bên.}
{177}{}{Cám ơn!}
{178}{}{Đấy là K-9, con chó của ta. Ta quyết định thử xem ta có thể tăng cường
sinh học trí tuệ cho nó không. Kết quả là có nhưng lại có vấn đề về
đạo đức. Con chó này không thích việc ta làm cũng như bản thân ta, nên nó cắn lại.}
{179}{}{Để trừng phạt, ta đã tắt hết mấy cái chân nhưng vẫn để nguyên
các chức năng khác. Giờ thì nó phải ngồi đấy và chứng kiến
tất cả những điều xấu xa ta làm.}
{180}{}{Ồ...}
{181}{}{Nó có thể sửa?}
{182}{}{Hiểu rồi.}
{183}{}{Liệu có thể sửa nó không?}
{184}{}{Ồ có chứ. Ta đã tháo mạch động cơ và đưa cho Raul ở phòng
bảo trì. Chỉ cần lắp lại là đâu lại vào đấy... Có thể ta sẽ làm vậy
trong tương lai để xem liệu nó có thay đổi thái độ không.}
{185}{}{Okay.}
{186}{}{Được rồi.}
{187}{}{Ông có phải dân thường không?}
{188}{}{Đây là phòng thuốc. Kho khí giới ở cuối hành lang bên trái.}
{189}{}{Sao cậu lại không mặc quân phục?}
{190}{}{Đm! Chúng ta đang bị xâm nhập! Báo động!}
{191}{}{Có kẻ xâm nhập! Gọi bảo vệ ngay!}
{192}{}{Lính đâu! Có kẻ đột nhập trong phòng thí nghiệm!}
{193}{}{Gì thế? Chúng ta bị tấn công à?}
{194}{}{Sao lại báo động? Chuyện gì thế?}
{195}{}{Cái củ lìn gì đang diễn ra thế?}
{196}{}{Ta đâu có tấn công, đừng bắn ta.}
{197}{}{Ta không tập đánh nhau, hãy để ta yên.}
{198}{}{Mẹ nó chứ! Ta là bác sĩ chứ có phải lính đâu!}
{200}{}{[THÊM]}
{201}{}{Tôi muốn hỏi một vài câu.}
{202}{}{Không phải bây giờ. Xin lỗi đã làm phiền.}
{800}{}{Bạn đã giết Tiến sĩ Schreber.}
