{100}{}{Bạn thấy Trung sĩ huấn luyện.}
{101}{}{Bạn thấy Trung sĩ Dornan.}
{102}{}{Bạn thấy một người đàn ông mặc power armor được thiết kế khác lạ. Có một phù hiệu trên tấm giáp ngực mà bạn không nhận ra.}
{103}{sgnt1a}{Chào mừng đến Trại Navarro... một thường dân! Thế đéo nào một đứa bỏ mẹ lại lọt được vào căn cứ thế! Tao sẽ dần nát mông đứa nào đó tối nay! Giải đứa dân thường này ra khỏi khu vực chính phủ ngay.}
{104}{sgnt1b}{Chào mừng đến Trại Navarro... một đám thường dân! Thế đéo nào một đám bỏ mẹ lại lọt được vào căn cứ thế! Bố sẽ dần nát mông ai đó tối nay! Giải cái lũ dân thường này ra khỏi khu vực chính phủ ngay.}
{105}{}{Chờ đã. Tôi...}
{106}{sgnt2a}{Ồ cái đm tôi. Tao cho người giải mày biến khỏi căn cứ và rồi mày lại ở đây. Tao không nghĩ mày là dân thường nữa rồi. Mày giống gián điệp hơn! Rung chuông báo động lên và xử con ruồi này nào!}
{107}{sgnt2b}{Ồ cái đm tôi. Tao cho người giải cả đám chúng mày khỏi căn cứ và rồi chúng mày lại ở đây. Tao không nghĩ chúng mày là dân thường nữa rồi. Cả lũ chúng mày giống gián điệp hơn! Rung chuông báo động lên và xử bầy ruồi này nào!}
{108}{sgnt3}{Chào mừng đến Trại Navarro. Vậy mày là lính dự bị đấy hử. Tên gì thế, binh nhì?}
{109}{}{Ừm... ngộ }
{110}{}{Tôi là }
{111}{sgnt4}{Ồ, yêu thế. Chúng nó gửi cho tao một đứa mất não. Nghe cho thủng lỗ tai đây. Mày sẽ đứng gác ở nhà chứa máy bay. Đây là vị trí gác của mày. Mày sẽ đi ngay lập tức và đứng gác ở đó cho đến khi có lệnh khác. Giờ thì đi đi, lính quèn!}
{112}{}{Ngộ đi.}
{113}{sgnt5}{Cái gì thế? Mày quên mất gì à, đồ ruồi?}
{114}{}{Tên tôi là }
{115}{sgnt6}{Tao đéo phải là Ngài. tao có công việc đàng hoàng, đồ đần độn. Mày sẽ gọi tao là Trung sĩ hoặc Trung sĩ Dornan. Mày có hiểu không! }
{116}{}{Có, thưa Trung sĩ!}
{117}{}{Rồi rồi, Tờ sĩ. Sao cũng được.}
{118}{sgnt7}{Tốt lắm. Giờ thì chạy ngay đến chỗ nhà chứa máy bay và làm nhiệm vụ đứng gác ở đó. Mày sẽ thực hiện tốt nhiệm vụ. Hiểu chứ?}
{119}{}{Tôi sẽ gác gì ở đó vậy, Trung sĩ?}
{120}{}{Có, thưa Trung sĩ!}
{121}{sgnt8}{Đồ đần, ai cho mày thắc mắc lệnh của tao hả! Khi nào tao bảo nhảy thì mày nhảy! Khi nào tao bảo đánh thì mày đánh! Khi nào tao bảo chết vì đất nước thì chắc chắn mày sẽ chết! Tao nói thế đã thủng chưa?}
{122}{}{Có, thưa Trung sĩ!}
{123}{sgnt9}{Chào mừng đến Trại Navarro. Thế mày là lính dự bị mới hả... Mày không mặc quân phục à, đồ lính quèn! Power armor của mày đâu?}
{124}{}{Ừ... ngộ không có.}
{125}{}{Căn cứ không cấp cho tôi. Họ nói đến đây sẽ được cấp.}
{126}{}{Ừ... tôi không được cấp bộ giáp nào.}
{127}{}{Ông đang mặc nó đấy... Tôi sẽ tháo giáp khỏi cái xác chết của ông!}
{128}{sgnt10}{Không có à? Mày tưởng tao sẽ tin lời mày sao, đồ ruồi? Thực tế là mày đã làm mất một thiết bị quân sự đắt tiền rồi. Bộ giáp đấy sẽ được trừ vào lương của mày, và mày sẽ ở lại đây phục vụ cho đội quân của tao cho đến khi mày 510 tuổi, vì đấy là số năm mày cần để trả cho một bộ Áo giáp chiến đấu Power Armor đời II mà mày vừa làm mất! Đi báo cáo cho kho khí giới và báo chúng nó cấp một bộ mới, rồi quay lại đây báo cáo cho tao, binh nhì! Giải tán!}
{129}{}{Okay. Ngộ đi lấy giáp.}
{130}{}{Có, thưa Trung sĩ!}
{131}{sgnt11}{Mấy thằng soạn giấy đầu lìn này! Đéo hiểu chúng nó nghĩ tao điều hành kiểu gì khi mà lúc đéo nào cũng thiếu quân tư trang! Chạy ngay đến chỗ kho khí giới và nhận quân phục rồi quay lại báo cáo cho tao. Nghỉ!}
{132}{}{Okay.}
{133}{}{Có, thưa Trung sĩ!}
{134}{sgnt12}{Nếu tao thích mày thì mày có thể gọi tao là Tờ sĩ. Nhưng biết gì không? Bố đéo thích mày! Mày có hiểu không?}
{135}{}{Có, thưa Trung sĩ!}
{136}{sgnt13}{Tốt lắm! Giờ thì mày mặc quân phục rồi và tao sẽ cho mày một cơ hội hiếm hoi. Chúng ta sẽ bắt đầu lại từ đầu, coi như tao chưa từng gặp đứa củ lìn nào. Được chứ hả, binh nhì?}
{137}{}{Vâng, ờ... tung sĩ!}
{138}{}{Không! Ngộ đéo cần nữa. Ngộ đá đít ông.}
{139}{}{Có, thưa Trung sĩ!}
{140}{}{Giờ tôi mặc bộ giáp ngon lành rồi nên tôi đéo cần nữa. Tôi sẽ cho ông ăn đạp đít.}
{141}{sgnt14a}{Binh nhì, mày vẫn chưa mặc quân phục. Tao ra lệnh trực tiếp cho mày đi đến phòng hậu cần và nhận đồ. Giờ thì cút cho khuất mắt tao và đừng có trở lại cho đến khi nào mày ăn mặc giống lính!}
{142}{sgnt14b}{Đây là lần thứ hai mày đến gặp tao mà không mặc quân phục rồi, lính quèn. Sẽ đéo có lần thứ ba đâu!}
{143}{}{Okay! Okay! Ngộ đi đây.}
{144}{}{Biến đi. Ngộ chán trò này rồi.}
{145}{}{Vâng, thưa Trung sĩ! Tôi lên đường ngay đây.}
{146}{}{Đm. Tôi đéo hợp làm trò này.}
{147}{sgnt15a}{Lính dù, mày đang làm gì ở đây thế? Quay trở lại vị trí gác ngay!}
{148}{sgnt15b}{Đồ đần. Tao mà còn thấy mày rời khỏi vị trí gác thì hôm nay sẽ là ngày cuối cùng trong cuộc đời ngắn ngủi của mày đấy!}
{149}{sgnt15c}{Mày là mối hiểm họa cho tất cả chúng ta. Giờ mày sẽ phải chết.}
{150}{sgnt16}{Căn cứ đang báo động và tao không nhận ra mày. Trình giấy tờ ra, đồ lính quèn.}
{151}{}{Ngộ không có giấy tờ theo người.}
{152}{}{Ngộ không cần giấy tờ!}
{153}{}{Tôi không mang theo giấy tờ. Chúng ở trong hòm đồ rồi.}
{154}{}{Giấy tờ? Tôi có giấy tờ ở đây này!}
{155}{sgnt17}{Trả lời sai rồi, đồ ruồi nhặng. Lúc nào mày cũng phải mang giấy tờ theo và mày phải biết điều đó!}
{156}{}{Chẹp.}
{157}{}{Tập trung vào, đồ lính quèn!}
{158}{}{Tốt. Mày đang đứng đúng chỗ rồi. Cứ ở yên đấy!}
{159}{}{Không có gì cần báo cáo cả, hiểu rồi. Cứ đứng gác ở đấy.}
{160}{}{Tao mà bắt được đứa nào ngủ gật thì tao sẽ làm cho chúng mày đéo bao giờ dậy được nữa!}
{161}{}{Tốt! Mày tìm được đúng chỗ gác rồi đấy!}
{162}{}{Cứ gác ở đây cho đến khi nào có lệnh thôi, đồ lính quèn!}
{163}{}{Vẫn đang đứng gác và không ngủ gật. Tốt lắm!}
{164}{}{Tỉnh táo, cảnh giác, sống lâu!}
{165}{}{Báo động! Có kẻ đột nhập căn cứ!}
{166}{}{Bảo vệ đâu! Có kẻ đột nhập!}
{167}{}{Đứa đéo nào để mấy thằng lìn này vào đây thế? Lính gác đâu!}
{168}{}{Báo động! Có gián điệp trong khu trại!}
{169}{}{Cái đứa binh nhì đần độn đấy ở chỗ đéo nào rồi?!}
{200}{}{.}
{201}{}{, thưa Ngài!}
{300}{}{Tao đã bảo là mày đừng có quay lại đây nếu chưa mặc quân phục cơ mà!}
