{100}{}{Bạn thấy ai đó mặc bộ áo giáp chiến đấu.}
{101}{}{Bạn thấy lính gác cửa phòng chỉ huy.}
{102}{}{Bạn thấy ai đó mặc áo giáp chiến đấu. Có miếng phù hiệu trên tấm giáp ngực mà bạn không nhận ra là gì.}
{103}{}{Thưa ngài! Ngài có việc gì ở đây?}
{104}{}{Đây chỗ nào?}
{105}{}{Ờ... ngộ mới đến đây.}
{106}{}{Ngộ đây lau dọn.}
{107}{}{Ngộ không nhớ. Ngộ đi.}
{108}{}{Đây là nơi nào?}
{109}{}{Xin chào, tôi mới đến đây.}
{110}{}{Tôi đến đây để lau dọn văn phòng cho chỉ huy.}
{111}{}{Không có gì.}
{112}{}{Đây là văn phòng chỉ huy của căn cứ. Khu vực này cấm tất cả mọi người vào. Tôi cần phải yêu cầu ngài rời đi, thưa ngài.}
{113}{}{Ngộ cần gặp chỉ huy.}
{114}{}{Được rồi.}
{115}{}{Tôi có việc cần gặp chỉ huy.}
{116}{}{Được rồi.}
{117}{}{Ngài có việc gì vậy, thưa ngài?}
{118}{}{Ừ...}
{119}{}{Chết, hỏng rồi...}
{120}{}{Quên đi. Ngộ đi.}
{121}{}{Ờ...}
{122}{}{Ờ, chúng ta vừa nhận được cuộc gọi của phòng an ninh căn cứ. Có vẻ như họ đang lo rằng mã khóa của tàu chở hàng bị rơi vào tay kẻ xấu. Tôi đến để khóa nó lại.}
{123}{}{Tôi sẽ đi đây.}
{124}{}{Thưa ngài. đây là cảnh báo cuối cùng. Tôi phải yêu cầu ngài rời khỏi khu vực này.}
{125}{}{Ok.}
{126}{}{Ồ... Đm. Ngộ bắn mở đường.}
{127}{}{Đm. Rút súng ra mở đường vào thôi.}
{128}{}{Cái gì? Ồ, tôi hiểu rồi. Cậu làm hỏng con cún và Dornan bắt cậu đi dọn cứt.}
{129}{}{Ờ... ngộ hỏng... chó cún và... cứt.}
{130}{}{(tự nói chuyện) Chỉ huy. Nhân viên dọn dẹp đã đến, thưa chỉ huy. (dừng) Vâng, thưa chỉ huy. (nhìn bạn) Vào đi.}
{131}{}{Cám ơn.}
{132}{}{(tự nói chuyện) Chỉ huy. Nhân viên dọn dẹp đã đến. Căn cứ chính muốn bảo mật mã khóa tàu chở hàng. (dừng) Vâng, thưa chỉ huy. (nhìn bạn) Vào đi.}
{133}{}{Đưa tôi xem lệnh nào.}
{134}{}{Cám ơn.}
{135}{}{Ồ, tôi không mang theo lệnh rồi.}
{136}{}{(yên lặng) Chắc cậu đi lạc rồi. Đây là văn phòng chỉ huy căn cứ. Không ai được phép vào đây trừ khi cụ khốt gửi cậu đến.}
{137}{}{Không ai đến đây? Mãi mãi?}
{138}{}{Không ai gặp ông?}
{139}{}{(yên lặng) Không ai cả. Ồ, chỉ có đội dọn dẹp thôi. Họ thường đến đây sau khoảng một tiếng nữa. Ngoài ra, nơi này cấm vào. Giờ thì tốt nhất cậu nên đi ra đi.}
{140}{}{Okay.}
{141}{}{(tự nói chuyện) Chỉ huy. Nhân viên dọn dẹp đã đến, thưa chỉ huy. (dừng) Vâng, thưa chỉ huy. (nhìn bạn) Vào đi.}
{142}{}{Đến sớm thế. Đúng giờ thì quay lại.}
{143}{}{Okay.}
{144}{}{Vậy thì quay lại chỗ trung tâm liên lạc và bảo họ in lại lệnh đi.}
{145}{}{Okay.}
{146}{}{Chắc là cậu đang tìm kho khí giới. Quay trở lại hành lang, rẽ phải và vào chỗ cửa đầu tiên bên trái. Cậu sẽ được cấp đồ tại đó.}
{147}{}{Cám ơn.}
{148}{}{Chúng mày là thế đéo nào... Báo động! Có kẻ xâm nhập!}
{149}{}{Chúng ta đã bị xâm nhập! Báo động!}
{150}{}{Có nhiều kẻ đột nhập! Rung chuông báo động lên!}
{151}{}{Cảnh báo an ninh! Khóa căn cứ!}
{152}{}{Bảo vệ toàn bộ căn cứ! Chúng ta đang báo động!}
{153}{}{Báo động có kẻ đột nhập! Vào mã đỏ!}
{154}{}{Chúng tao sẽ cho mày cạp đất!}
{155}{}{Enclave sẽ thống trị cả thế giới!}
{156}{}{Mày phải chết để Enclave tồn tại!}
{160}{}{Cậu quay lại rồi. Cậu có mang theo lệnh lấy fob theo không?}
{161}{}{Chưa. Tôi sẽ đi lấy.}
{162}{}{Ờ, đúng vậy. Tôi nói cho cậu là đội dọn dẹp sẽ đến và rồi cậu biến hình thành một nhân viên lau dọn.
Cậu thậm chí còn chưa đi khuất khỏi mắt tôi. Đm cậu nghĩ tôi bị ngu à? Cút con mẹ nó khỏi đây ngay!}
{200}{}{(tự nói chuyện) Chỉ huy. (dừng) Chỉ huy có ở đó không? (dừng) Hừm... không có trả lời. Không giống như thường lệ.
Tốt nhất là mình nên vào kiểm tra.}
{201}{}{(Ôi cái đcm Chỉ huy chết rồi! Rung chuông báo động lên chúng ta có kẻ đột nhập!!}
