{100}{}{Bạn thấy một lính gác. }
{101}{}{Bạn thấy lính gác cổng.}
{102}{}{Bạn thấy một lính gác mặc power armor với thiết kế khác lạ. Có phù hiệu trên tấm giáp ngực mà bạn không nhận ra.}
{103}{gate1}{Đứng lại! Đây là tài sản liên bang -- không phận sự cấm vào.}
{104}{}{Ừm... luyên bang?}
{105}{}{Ngộ có thẻ... đâu ngộ để?}
{106}{}{Ngộ mới. Ngộ được nói ông biết.}
{107}{}{Ồ. Xin lỗi, ngộ đi.}
{108}{}{Tôi có thẻ ra vào... ở ngay đây.}
{109}{}{Tôi là lính mới nhập ngũ. Tôi được bảo là ông sẽ biết tôi.}
{110}{}{Ồ, xin lỗi. Tôi sẽ đi chỗ khác vậy.}
{111}{gate2}{Lề mề quá nhỉ? Này, cứ tiếp tục di chuyển đi và đừng có quay trở lại. Mọi việc sẽ ổn thôi, hiểu chứ?}
{112}{}{Ngộ muốn vào trong.}
{113}{}{Ok. Ngộ đi.}
{114}{gate3}{Không ai được... Mẹ nó chứ. (nói chậm) Cần thẻ để vào. Mày không có thẻ. Mày đi chỗ khác. Mày không đi thì ăn đạn. Hiểu chứ?}
{115}{}{Thế ngộ đánh ông thì sao?}
{116}{}{Ok. Ngộ đi.}
{117}{gate14}{(đặt tay lên vũ khí) Đừng có lí do lí trấu! Hoặc là trình thẻ hoặc là đọc mật khẩu!}
{118}{}{Không có thấy thẻ, không nhớ mật khẩu!}
{119}{}{Chết tiệt. Ngộ giết.}
{120}{}{Tôi xin lỗi, tôi làm mất thẻ và tôi không biết mật khẩu nào cả.}
{121}{}{Mẹ nhà ông và tất cả những đứa nào giống ông!}
{122}{gate5}{Tôi khuyên là hãy rời khỏi nơi này ngay lập tức và đừng có trở lại nếu không được phép. Tôi nói thế đã rõ chưa?}
{123}{}{Đúng vậy.}
{124}{gate6a}{Hiểu rồi. Thế mật khẩu là gì?}
{125}{gate6b}{Hiểu rồi. (đặt tay lên vũ khí) Tất cả lính mới đều phải đến báo cáo một mình. Tôi khuyên là hãy rời khỏi nơi này ngay tức khắc và đừng có kéo đàn kéo lũ trở lại. Tôi nói thế đã rõ ràng chưa?}
{126}{}{Đầu cừu.}
{127}{}{Đúng vậy.}
{128}{gate7a}{Chờ chút. (dừng) Okay, vào đi. Hãy đến báo cáo cho đội trưởng huấn luyện. Đi vào cửa, qua hàng rào sắt đến chỗ cái cửa đầu tiên bên phải.}
{129}{gate7b}{(lẩm bẩm) Mẹ kiếp lũ đầu đất càng lúc càng đần.}
{130}{}{Ok.}
{131}{gate8a}{Đứng lại! -- Ồ, tôi thấy là cậu đã trở lại một mình. Được rồi, tân binh, mật khẩu là gì?}
{132}{gate8b}{Đứng lại! -- Lại là cậu. Tôi thấy là cậu vẫn đi dẫn đoàn. (đặt tay lên vũ khí) Tôi khuyên là hãy rời khỏi nơi này ngay lập tức và đừng có quay trở lại. Tôi nói thế đã rõ chưa?}
{133}{}{Đầu cừu.}
{134}{}{Đúng vậy.}
{135}{gate9}{Halt! -- Back again, huh? You'd better have your pass or know your password this time. Well, I'm waiting?}
{136}{}{Uh... me not know. Me come back.}
{137}{}{Screw this. Me walk in over you dead body.}
{138}{}{Look, I lost my pass...}
{139}{}{Oh to hell with it. Bite the bullet, asshole!}
{140}{gate10}{This is your final warning. I suggest you leave this installation immediately and do not return here. Do I make myself clear?}
{141}{}{Ok, me go again...}
{142}{}{In words of ancients... Fuck you!}
{143}{}{Được rồi, con đi đây.}
{144}{}{In the words of the ancients... Fuck you!}
{145}{gate11a}{Halt! -- You again? You were warned. Alarm! Intruder at the gate! }
{146}{}{Damn!}
{147}{}{Intruder at the gate!}
{148}{}{Main entrance under attack!}
{149}{}{To the gate! Intruder at the gate!}
{200}{}{...asshole...}
{201}{}{...yeah, you'd BETTER walk away...}
{202}{}{...what a brownie hound...}
{203}{}{...yes, sir! fuckin' sir!...}
{300}{}{Move along soldier.}
