{100}{}{Bạn thấy một lính gác.}
{101}{}{Bạn thấy một lính gác mặc power armor.}
{102}{}{Bạn thấy một người mặc power armor có thiết kế khác lạ. Có miếng phù hiệu trên tấm giáp ngực mà bạn không nhận ra.}
{103}{}{Không có gì mới.}
{104}{}{Tôi không thấy có gì mới, cậu thì sao?}
{105}{}{Này cậu lính, sao cậu không về vị trí gác đi? Đừng có đi lang thang ở đây.}
{106}{}{Cậu đang không mặc quân phục.}
{107}{}{Tốt hơn hết là đến chỗ Trung sĩ báo cáo rồi đi nhận quân phục đi.}
{108}{}{Cậu to gan lắm mới đi lại mà không mặc quân phục đấy. Tốt nhất là nên đi báo lại cho hậu cần đi.}
{109}{}{Chúng mày là thế đéo nào... Báo động! Có kẻ xâm nhập!}
{110}{}{Chúng ta đã bị xâm nhập! Báo động!}
{111}{}{Có nhiều kẻ đột nhập! Rung chuông báo động lên!}
{112}{}{Cảnh báo an ninh! Khóa căn cứ!}
{113}{}{Bảo vệ toàn bộ căn cứ! Chúng ta đang báo động!}
{114}{}{Báo động có kẻ đột nhập! Vào mã đỏ!}
{115}{}{Chúng tao sẽ cho mày cạp đất!}
{116}{}{Enclave sẽ thống trị cả thế giới!}
{117}{}{Mày phải chết để Enclave tồn tại!}
{200}{}{...đồ chết tiệt...}
{201}{}{...đúng rồi, TỐT HƠN HẾT là mày nên bước đi...}
{202}{}{...con chó này đen thế...}
{203}{}{...vâng, thưa ngài! đcm ngài!...}
{300}{}{Chờ đã. Cậu đang làm cái quái gì với chiếc máy bay thế? Làm gì có lịch bay nào trong mấy ngày tới.}
{301}{}{Nrg?}
{302}{}{Tôi biết.}
{303}{}{Tôi xin lỗi. Tôi chỉ xem thôi. Đi giờ đây.}
{304}{}{Kế hoạch đã thay đổi. Tôi sẽ lấy chiếc máy bay này.}
{310}{}{Cái gì? Ồ, hiểu rồi. Này, đừng có động vào. Được chứ? Động vào lần nữa là chết đấy.}
{311}{}{(Cười rồi tấn công).}
{312}{}{(Đi khỏi).}
{315}{}{Ồ cứt thật, có vẻ như chúng ta bị đột nhập rồi. Mã đỏ! Nhắc lại, mã Đỏ!}
{316}{}{Nghe hay đấy. Động vào cái máy bay lần nữa và tôi sẽ nhồi chì vào đầu cậu.}
{320}{}{Rồi. Và cậu là...}
{321}{}{Chuẩn bị đi đây. Xin lỗi đã làm phiền.}
{322}{}{Chuẩn bị đi gửi tin quan trọng về căn cứ chính.}
{323}{}{Ồ thật ư? Và tin này về việc gì thế.}
{324}{}{Đây là siêu bí mật. Tôi không thể nói được.}
{325}{}{Tôi sẽ nói cho anh, nhưng phải tuyệt đối bảo đảm không được tiết lộ thông tin này cho bất kì ai khác vì có thể
sẽ dẫn đến đại hoảng loạn. Biết gì không? Tôi nhận thấy một trong số chuyến hàng nô lệ gần đây đã bị nhiễm một loại 
virus không xác định và cực kì nguy hiểm. Tôi *phải* đi đến căn cứ ngay, nếu không tất cả chúng ta sẽ tiêu đời. Giờ thì 
đừng có làm lãng phí thời gian nữa vì không thể chờ được nữa đâu.}
{326}{}{Được, tôi tin cậu. Có vẻ như chúng ta có kẻ đột nhập...}
{327}{}{Mẹ nó chứ! À, sao cũng được. Chẳng ai nói cái cứt gì cho tôi cả. Rồi. Đi đi.}
{328}{}{Ồ, nghe tệ thật đấy. Vậy thì cậu nên lên đường đi, tôi không muốn dính phải cứt đâu. Ồ và đừng lo, tôi sẽ không nói với ai đâu.}
{329}{}{[XONG]}
