{100}{}{Bạn thấy người mặc đồ thép sáng bóng.}
{101}{}{Một người lính mặc power armor.}
{102}{}{Một người lính mặc loại power armor mới, chắc vậy.}
{103}{}{Tin được không? Tôi lại bị điều đi KP lần nữa!}
{104}{}{Có tin đồn là lão già sẽ ra lệnh điều đi SF!}
{105}{}{Chờ ăn cặc. Tao nói rồi, cứ trồng nấm hết cả lũ khỉ đi cho xong.}
{106}{}{Có bật lửa không? Ồ khoan đã, không cần. Có rồi.}
{107}{}{Tối nghỉ thì đổ xúc xắc chia lại thu nhập nhá. Đừng có để đám Sĩ quan biết đấy.}
{108}{}{Ai đấy-? <zzz>Có kẻ đột nhập vào đây!}
{109}{}{Người kia! Đứng lại!}
{110}{}{Có kẻ đột nhập căn cứ!}
{111}{}{Chờ đã -- ồ, không có gì. }
{112}{}{Này, cầm theo thẻ đi. Mấy cái báo động giả này khiến mọi người phát điên lên được.}
{113}{}{Cậu đúng là người ở đây chứ? Mẹ nó mấy cái báo động giả này khiến tôi phát rồ lên!}
{114}{}{Kẻ đột nhập ở đây! Bắt lấy!}
{115}{}{Kẻ đột nhập kia rồi!}
{116}{}{Ở đây! Đừng để nó chạy thoát!}
{117}{}{Chúng ta bị tấn công trực diện. Gửi tiếp viện ngay!}
{118}{}{Đừng để kẻ đột nhập đến được cửa!}
{119}{}{Chết đi, đồ khỉ!}
