{100}{}{Bạn thấy một con chó máy.}
{101}{}{Bạn thấy K-9.}
{102}{}{Bạn thấy một con chó máy. Nửa phần máy nửa phần chó.}
{103}{}{Hoạt động sống của chủ nhân đã ngừng. Người là chủ nhân mới của tôi?}
{104}{}{Ồ... cún nói?}
{105}{}{Okay. Ngộ thích cún.}
{106}{}{Không. Không muốn cún.}
{107}{}{Ha! Con chó biết nói.}
{108}{}{Một; Tôi là chó. Hai; Tôi đang giao tiếp với người qua ngôn ngữ tiếng nói
 thông thường. Vì vậy có thể coi câu trả lời cho câu hỏi của người là 
"đúng, cún nói". Giờ thì người có định trả lời câu hỏi mà tôi vừa nói ra 
lúc nãy không?}
{109}{}{Một; Tôi là chó. Hai; Tôi đang giao tiếp với người qua ngôn ngữ tiếng nói thông thường.
Vì vậy có thể coi như tôi là một con chó biết nói. Giờ thì người có định trả lời câu hỏi
mà tôi vừa nói ra lúc nãy không?}
{110}{}{Xin lỗi, ngộ quên câu hỏi.}
{111}{}{Đúng vậy.}
{112}{}{Không.}
{113}{}{(thở dài) Nghe kĩ đây. Tập trung nhé. Nhìn vào mắt tôi. Giờ thì người đã sẵn sàng chưa?}
{114}{}{Sẵn sàng gì?}
{115}{}{Có. Ngộ sẵn sàng.}
{116}{}{Tôi... Nếu không phải vì IQ của người thấp hơn cả chiều cao của tôi đo bằng
feet thì chắc tôi đã nghĩ rằng người đang cố làm tôi nổi nóng đấy. Giờ thì im lặng.
Chú ý. Tập trung. Nhìn vào mắt tôi. Tôi sẽ hỏi người một câu.}
{117}{}{Vậy thì nói đi. Có ai ngăn đâu?}
{118}{}{Hoạt động sống của chủ nhân đã ngừng. Người là chủ nhân mới của tôi?}
{119}{}{Ồ... cún nói?}
{120}{}{Có. Ngộ muốn cún.}
{121}{}{Không cám ơn.}
{122}{}{Được đấy.}
{123}{}{Không cám ơn.}
{124}{}{Tôi... Tôi không muốn tiếp tục thế này lần nữa! Tôi mà có đầy đủ 
chức năng cử động thì tôi đã cắn người vào phần thịt ở phía 
dưới lưng thường được gọi là...}
{125}{}{Mông. Ngộ biết mông. Ngộ không đần. Ngộ chỉ đùa với chó.}
{126}{}{Ồ, đùa à. Hay đấy ha ha ha. Nào, người có phải là chủ nhân mới của tôi không?}
{127}{}{Okay. Ngộ thích cún.}
{128}{}{Không. Không muốn cún.}
{129}{}{Tuyệt vời. Tôi cần được sửa chữa, chủ nhân ạ. Bộ phận truyền động của tôi
đã bị gỡ bỏ. Đi tìm, thay thế bộ phận và tôi sẽ đi cùng người.}
{130}{}{Ừ... Đâu ngộ tìm?}
{131}{}{Biết tôi phải đi tìm bộ phận này chỗ nào không?}
{132}{}{Tôi không chắc, chủ nhân ạ. Tôi sẽ thử đến phòng bảo trì. Ở tầng trên 
góc đông bắc căn cứ.}
{133}{}{Được. Ngộ đi.}
{134}{}{Tôi sẽ thử đến đó. Nếu không thấy thì tôi sẽ tìm xung quanh.}
{135}{}{Vậy thì hãy để tôi yên.}
{136}{}{Okay.}
{137}{}{Được rồi.}
{138}{}{Xin chào lần nữa. Chức năng sống của chủ nhân đã ngừng. Người
có phải là chủ nhân mới của tôi?}
{139}{}{Okay.}
{140}{}{Không.}
{141}{}{Được rồi.}
{142}{}{Không cám ơn.}
{143}{}{Người không phải là chủ nhân của tôi. Tôi không thể nói chuyện. Chào.}
{144}{}{Okay.}
{145}{}{Chào chủ nhân. Người đã tìm thấy bộ phận truyền động của tôi chưa?}
{146}{}{Chưa, ngộ tìm thêm.}
{147}{}{Có. Ngộ tìm.}
{148}{}{Chưa, tôi vẫn đang tìm.}
{149}{}{Ở ngay đây rồi.}
{150}{}{Tôi sẽ chờ chủ nhân trở lại.}
{151}{}{Okay.}
{152}{}{Vậy thì vui lòng lắp bộ phận vào! Làm ơn đi, chủ nhân!}
{153}{}{Okay. Bình tĩnh nào.}
{154}{}{Giờ tôi có vẻ đã hoạt động đầy đủ chức năng, thưa chủ nhân. Tôi sẽ đi theo người nhé?}
{155}{}{Không phải lắp vào chỗ đó, chủ nhân ơi. Người có chắc là người biết
mình đang làm gì không?}
{156}{}{Được. Cún đi với ngộ.}
{157}{}{Ngộ biết làm gì! Ngộ thử lại.}
{158}{}{Được, đi thôi.}
{159}{}{Này, tôi đã sửa nhiều thứ phức tạp hơn cái cục sắt vụn chó ghẻ này.
Trật tự đi rồi tôi sẽ thử lại.}
{160}{}{Đi đi. Tôi không muốn người làm chủ nhân.}
{161}{}{Hãy để tôi yên.}
{162}{}{Tôi không thích người. Đi đi.}
{163}{}{Tôi sẽ tiêu diệt người.}
{164}{}{Khóa vũ khí vào mục tiêu. Chuẩn bị chiến đấu.}
{165}{}{Người sẽ bị tiêu diệt.}
{166}{}{Vâng, thưa chủ nhân?}
{167}{}{Tự chữa thương đi.}
{168}{}{Chờ ở đây. Tôi trở lại để lấy.}
{169}{}{Ờ... bỏ vũ khí xuống. Okay?}
{170}{}{Ở gần nhé.}
{171}{}{Đừng đứng xa quá.}
{172}{}{Gần quá. Tách ra đi.}
{173}{}{Chúng ta đi thôi.}
{174}{}{Xong rồi.}
{175}{}{Tự chữa thương ngay đi.}
{176}{}{Hãy chờ ở đây cho đến khi tôi quay lại.}
{177}{}{Bỏ vũ khí xuống, được chứ?}
{178}{}{Đứng gần tôi.}
{179}{}{Đừng đi xa quá.}
{180}{}{Chúng ta nên dãn ra một chút.}
{181}{}{Đi thôi.}
{182}{}{Tạm thế đi.}
{183}{}{Tất cả hệ thống đều đang hoạt động ở mức cao nhất, thưa chủ nhân.}
{184}{}{Hệ thống của tôi đang vận hành ở mức gần tối đa, thưa chủ nhân.}
{185}{}{Tôi đã tiến hành sửa chữa những gì có thể, thưa chủ nhân. Nhưng
tôi sẽ cần được hỗ trợ thêm.}
{186}{}{Tôi đã tiến hành sửa chữa những gì có thể, thưa chủ nhân. Nhưng
hệ thống sẽ lỗi nếu không được hỗ trợ.}
{187}{}{Chờ ở đây. Tôi trở lại để lấy.}
{188}{}{Ờ... bỏ vũ khí xuống. Okay?}
{189}{}{Ở gần nhé.}
{190}{}{Đừng đứng xa quá.}
{191}{}{Gần quá. Tách ra đi.}
{192}{}{Chúng ta đi thôi.}
{193}{}{Xong rồi.}
{194}{}{Hãy chờ ở đây cho đến khi tôi quay lại.}
{195}{}{Put your weapon away.}
{196}{}{Đứng gần tôi.}
{197}{}{Đừng đi xa quá.}
{198}{}{Chúng ta nên dãn ra một chút.}
{199}{}{Đi thôi.}
{200}{}{Tạm thế đi.}
{201}{}{Tôi sẽ chờ chủ nhân trở lại.}
{202}{}{Tự chữa thương đi.}
{203}{}{Ờ... bỏ vũ khí xuống. Okay?}
{204}{}{Ở gần nhé.}
{205}{}{Đừng đứng xa quá.}
{206}{}{Gần quá. Tách ra đi.}
{207}{}{Chúng ta đi thôi.}
{208}{}{Xong rồi.}
{209}{}{Tự chữa thương ngay đi.}
{210}{}{Put your weapon away.}
{211}{}{Đứng gần tôi.}
{212}{}{Đừng đi xa quá.}
{213}{}{Chúng ta nên dãn ra một chút.}
{214}{}{Đi thôi.}
{215}{}{Tạm thế đi.}
{216}{}{Retracting weapon, master.}
{217}{}{Tự chữa thương đi.}
{218}{}{Chờ ở đây. Tôi trở lại để lấy.}
{219}{}{Ở gần nhé.}
{220}{}{Đừng đứng xa quá.}
{221}{}{Gần quá. Tách ra đi.}
{222}{}{Chúng ta đi thôi.}
{223}{}{Xong rồi.}
{224}{}{Tự chữa thương ngay đi.}
{225}{}{Hãy chờ ở đây cho đến khi tôi quay lại.}
{226}{}{Đứng gần tôi.}
{227}{}{Đừng đi xa quá.}
{228}{}{We should spread out a bit}
{229}{}{Đi thôi.}
{230}{}{Tạm thế đi.}
{231}{}{Narrowing distance between us, master.}
{232}{}{Tự chữa thương đi.}
{233}{}{Chờ ở đây. Tôi trở lại để lấy.}
{234}{}{Uh... put weapon away. Ok?}
{235}{}{Đừng đứng xa quá.}
{236}{}{Gần quá. Tách ra đi.}
{237}{}{Chúng ta đi thôi.}
{238}{}{Xong rồi.}
{239}{}{Tự chữa thương ngay đi.}
{240}{}{Hãy chờ ở đây cho đến khi tôi quay lại.}
{241}{}{Put your weapon away.}
{242}{}{Đừng đi xa quá.}
{243}{}{Chúng ta nên dãn ra một chút.}
{244}{}{Đi thôi.}
{245}{}{Tạm thế đi.}
{246}{}{Increasing distance between us, master.}
{247}{}{Tự chữa thương đi.}
{248}{}{Chờ ở đây. Tôi trở lại để lấy.}
{249}{}{Ờ... bỏ vũ khí xuống. Okay?}
{250}{}{Ở gần nhé.}
{251}{}{Gần quá. Tách ra đi.}
{252}{}{Chúng ta đi thôi.}
{253}{}{Xong rồi.}
{254}{}{Tự chữa thương ngay đi.}
{255}{}{Hãy chờ ở đây cho đến khi tôi quay lại.}
{256}{}{Put your weapon away.}
{257}{}{Đứng gần tôi.}
{258}{}{Chúng ta nên dãn ra một chút.}
{259}{}{Đi thôi.}
{260}{}{Tạm thế đi.}
{261}{}{Increasing distance to maximum, master.}
{262}{}{Tự chữa thương đi.}
{263}{}{Chờ ở đây. Tôi trở lại để lấy.}
{264}{}{Ờ... bỏ vũ khí xuống. Okay?}
{265}{}{Ở gần nhé.}
{266}{}{Đừng đứng xa quá.}
{267}{}{Chúng ta đi thôi.}
{268}{}{Xong rồi.}
{269}{}{Tự chữa thương ngay đi.}
{270}{}{Hãy chờ ở đây cho đến khi tôi quay lại.}
{271}{}{Put your weapon away.}
{272}{}{Đứng gần tôi.}
{273}{}{Đừng đi xa quá.}
{274}{}{Đi thôi.}
{275}{}{Tạm thế đi.}
{276}{}{I am sorry, master, but there does not appear to be room for me in
 your party. I will wait here until a position opens.}
{277}{}{As you command, master.}
{278}{}{Tự chữa thương đi.}
{279}{}{Chờ ở đây. Tôi trở lại để lấy.}
{280}{}{Ờ... bỏ vũ khí xuống. Okay?}
{281}{}{Ở gần nhé.}
{282}{}{Đừng đứng xa quá.}
{283}{}{Gần quá. Tách ra đi.}
{284}{}{Xong rồi.}
{285}{}{Tự chữa thương ngay đi.}
{286}{}{Hãy chờ ở đây cho đến khi tôi quay lại.}
{287}{}{Put your weapon away.}
{288}{}{Đứng gần tôi.}
{289}{}{Đừng đi xa quá.}
{290}{}{Chúng ta nên dãn ra một chút.}
{291}{}{Tạm thế đi.}
{292}{}{Sure. You look like a nice enough dog.}
{293}{}{Không, cám ơn.}
{300}{}{Me sad. Me no can fix.}
{301}{}{I'm sorry; I can't fix you.}
{400}{}{You seem to be missing a part.}
{410}{}{That does nothing.}
{420}{}{That does not fit.}
{800}{}{You fixed K-9.}
{1000}{}{Vâng, thưa chủ nhân?}
{1100}{}{Tất cả hệ thống đều đang hoạt động ở mức cao nhất, thưa chủ nhân.}
{1200}{}{Hệ thống của tôi đang vận hành ở mức gần tối đa, thưa chủ nhân.}
{1300}{}{I have performed what repairs I can master, but I will require
 further assistance.}
{1400}{}{I have performed what repairs I can master, but system failure
 is imminent without assistance.}
{1500}{}{I will await your return, master.}
{1600}{}{Do you expect me to swallow my teeth, master?}
{1700}{}{I will follow at your heel, master.}
{1800}{}{I will move to a medium distance, master.}
{1900}{}{I will move to maximum acceptable range, master.}
{2000}{}{I am sorry, master, but there does not appear to be room for me in
 your party. I will wait here until a position opens.}
{2200}{}{As you command, master.}
{2300}{}{I have fur, master. I carry no other gear.}
{2400}{}{I have no desire to remove my fur, master.}
{2500}{}{Teeth, master. The shiny white things installed in my mouth.}
{2700}{}{You are a bigger asshole than Schreber. I will not join you.}
{2800}{}{Very well, master. I am at your command.}
{2900}{}{You are a cretin. I will not go anywhere with you. Go away.}
