{100}{}{Bạn thấy một người thợ cơ khí.}
{101}{}{Bạn thấy Kevin, thợ cơ khí.}
{102}{}{Bạn thấy một người mặc quân phục. Dựa trên những vết dầu mỡ, bạn nghĩ người này 
giống thợ cơ khí hơn là lính.}
{200}{}{Giờ tôi không nói chuyện được. Hãy đến gặp Quincy.}
{201}{}{Quincy điều hành ở đây. Hãy đến gặp ông ta.}
{202}{}{Tôi chỉ là thợ cơ khí cấp thấp thôi. Cậu đến nói chuyện với Quincy ấy.}
{300}{}{Cậu đang không mặc quân phục.}
{301}{}{Này cậu lính, cậu nên mặc đồ vào.}
{302}{}{Cậu to gan lắm mới đi lại mà không mặc quân phục đấy. Tốt nhất là nên đi báo lại cho hậu cần đi.}
{400}{}{Chúng mày là thế đéo nào... Báo động! Có kẻ xâm nhập!}
{401}{}{Chúng ta đã bị xâm nhập! Báo động!}
{402}{}{Có nhiều kẻ đột nhập! Rung chuông báo động lên!}
{500}{}{Cứt thật! Cho cứu viện bắt đầu vào đi.}
{501}{}{Đóng tất cả các hoạt động bí mật.}
{502}{}{Bảo vệ hệ thống và bật tất cả mật khẩu an ninh.}
{600}{}{Tôi là thợ cơ khí, không phải chiến binh!}
{601}{}{Chĩa đầu súng có thấu kính laser về phía kẻ địch. Rồi bóp cò.}
{602}{}{Cứu! Cứu! Đến phòng bảo trì!}
