{100}{}{You see a mechanic.}
{101}{}{You see Kevin, the mechanic.}
{102}{}{You see a man in a military uniform. Judging by the grease spots you think he is more of
 a mechanic than a soldier.}
{200}{}{I can't talk right now. Go see Quincy.}
{201}{}{Quincy is in charge here. Go see him.}
{202}{}{I'm just a junior mechanic. You'll want to talk to Quincy.}
{300}{}{Cậu đang không mặc quân phục.}
{301}{}{You better suit up soldier.}
{302}{}{Cậu to gan lắm mới đi lại mà không mặc quân phục đấy. Tốt nhất là nên đi báo lại cho hậu cần đi.}
{400}{}{Chúng mày là thế đéo nào... Báo động! Có kẻ xâm nhập!}
{401}{}{Chúng ta đã bị xâm nhập! Báo động!}
{402}{}{Có nhiều kẻ đột nhập! Rung chuông báo động lên!}
{500}{}{Cứt thật! Cho cứu viện bắt đầu vào đi.}
{501}{}{Đóng tất cả các hoạt động bí mật.}
{502}{}{Bảo vệ hệ thống và bật tất cả mật khẩu an ninh.}
{600}{}{I'm a mechanic, not a fighter!}
{601}{}{Pointy end with the laser diode goes toward the enemy. Then pull the trigger.}
{602}{}{Help! Help! To maintenance!}
