{100}{}{Bạn thấy ai đó mặc power armor. }
{101}{}{Bạn thấy Chỉ huy căn cứ Navarro.}
{102}{}{Bạn thấy một người mặc power armor có thiết kế khác lạ. Có miếng phù hiệu trên tấm giáp ngực mà bạn không nhận ra.}
{103}{}{Mấy người các ngươi là lũ quái nào thế... Báo động! Có kẻ đột nhập trong căn cứ!}
{104}{}{Ta không có thời gian tán nhảm với lính quèn. Giải tán.}
{105}{}{Đến lúc chết rồi.}
{106}{}{Okay.}
{107}{}{Ta đã bảo là ta không có thời gian rồi. Rời văn phòng và đừng có quay lại đây trừ khi ta có lệnh triệu tập. Giải tán!}
{108}{}{Không tuân lệnh trực tiếp của sĩ quan cấp trên là tội phản cấp. Ta không có thời gian lôi ra tòa án binh nên ta sẽ tự mình xử lí. Lính gác đâu! Tiêu diệt kẻ đần độn này!}
{109}{}{Okay.}
{110}{}{Chết đi!}
{111}{}{Fob ở trong tủ khóa đăng kia. Khi nào an toàn thì báo sĩ quan trực liên hệ với ta. Giải tán!}
{112}{}{Vâng, thưa chỉ huy!}
{113}{}{Nói nhanh lên, đồ linh, ta không có cả ngày để chờ đâu.}
{114}{}{Vâng, thưa chỉ huy!}
{115}{}{Đừng có động vào cái tủ khóa, không thì ta sẽ ra tay thật đấy.}
{116}{}{Vâng, thưa chỉ huy!}
{117}{}{Căn cứ đang báo động và ta không nhận ra ngươi. Này lính, trình giấy tờ ra.}
{118}{}{Giấy tờ nào?}
{119}{}{Mày bắn tao!}
{120}{}{Hình như tôi không mang theo người...}
{121}{}{Giấy tờ? Tôi có giấy tờ ở đây này!}
{122}{}{Trả lời sai rồi, đồ sâu bọ. Lúc nào mày cũng phải mang giấy tờ theo. Mày phải biết điều đó!}
{123}{}{Đmm.}
{124}{}{Đừng có động vào cái tủ khóa, không thì ta sẽ ra tay thật đấy.}
{125}{}{Đến lúc chết rồi.}
