{100}{}{Bất ngờ chưa -- trông giống một gã mặc power armor.}
{101}{}{Đúng vậy, vẫn là một gã mặc power armor.}
{102}{}{Ông ta có miếng phù hiệu gì đó trên tấm giáp ngực, trông khác với những người khác mà bạn
đã thấy quanh đây.}
{103}{}{<Rè rè> - kho khí giới!}
{104}{}{Cái gì - <tiếng nhiễu!>>}
{105}{}{(Vậy là Trung sĩ cử ngươi đến về việc cần power armor. Ồ, tất cả những gì ta có ở đây 
là có một bộ đang bảo trì. Có thể vẫn còn chút vấn đề, nên cẩn thận chút. Kí vào đây).}
{106}{}{Ờ... ông nhắc lại được không?}
{107}{}{Tôi nghĩ là có vấn đề với bộ giáp của ông.}
{108}{}{Được, tôi sẽ làm vậy.}
{109}{}{Không đâu. Quên đi.}
{110}{}{Ngươi là người mà Arch đã gọi đàm vào à?}
{111}{}{Có chắc là ngươi không phải gã đó không?}
{112}{}{Hở?}
{113}{}{Đúng vậy.}
{114}{}{Không.}
{115}{}{Ngươi là ai? Ngươi làm gì ở đây?}
{116}{}{Cái gì?}
{117}{}{Ờ... tôi là người mới ở đây?}
{118}{}{Ú òa!}
{119}{}{Ngươi là ai? Ngươi làm gì ở đây?}
{120}{}{Cái gì?}
{121}{}{Ờ... tôi là người mới ở đây?}
{122}{}{Ú òa!}
{123}{}{Ý ngươi là sao? Bộ giáp này đang hoạt động bình thường! Ngươi có kí giấy hay không nào?}
{124}{}{Tôi chẳng hiểu từ nào cả.}
{125}{}{Bộ đám của ông bị hỏng rồi.}
{126}{}{Rồi, sao cũng được.}
{127}{}{Kết thúc trò này thôi!}
{128}{}{(Cái gì, ngươi điếc à? Ta đã nói là ta có giáp; chỉ cần kí vào đây).}
{129}{}{Gã hề này. Ồ, ta không cần. Ngươi đi mà giải thích cho Trung sĩ về việc sao ngươi không có quân phục!}
{130}{}{Hở?}
{131}{}{Okay, được rồi. Tôi sẽ làm vậy.}
{132}{}{Quên đi, được chứ?}
{133}{}{Bộ đàm của ngươi không hỏng. Ta có thể nghe rõ ngươi nói gì. Chỉ cần kí vào giấy và chúng ta
xong việc.}
{134}{}{Hở?}
{135}{}{Được rồi, tôi chịu rồi!}
{136}{}{Ông muốn tôi làm gì? Tôi không phải loại người đó!}
{137}{}{Được rồi, tên ngươi là gì?}
{138}{}{[Tên người chơi]}
{139}{}{Pisces?}
{140}{}{Tôi muốn bộ power armor.}
{141}{}{Cá kiếm.}
{142}{}{Rồi. Đơn vị?}
{143}{}{Arroyo.}
{144}{}{Không hề.}
{145}{}{Tôi có thứ hay hơn.}
{146}{}{42.}
{147}{}{Thứ có S hay C?}
{148}{}{Đúng vậy.}
{149}{}{Không.}
{150}{}{Tôi không chắc.}
{151}{}{Ngươi sẽ có bộ giáp khi nào ta xong việc và sẵn sàng! Nào, giờ thì trả lời câu hỏi đi.}
{152}{}{[Tên người chơi]}
{153}{}{Pisces?}
{154}{}{Cá kiếm.}
{155}{}{Arroy -- Chờ đã! Bọn ta vừa mới dẹp chỗ đó. Mày là một gã tộc chết tiệt! Lính gác đâu!}
{156}{}{Này, gã hề, đừng có bày trò hoặc ta sẽ cho người lôi ngươi ra làm thịt đấy. Trả lời câu hỏi đi.}
{157}{}{Arroyo.}
{158}{}{42.}
{159}{}{Được rồi! Lê đít về chỗ trung sĩ đi. Ta gửi ngươi về đó chịu phạt. Giải tán.}
{160}{}{Nhóm 42 à? Đơn vị tốt đó. Được rồi. Đồ đây. Giải tán, cậu lính.}
{161}{}{Ngươi bị điếc à? Ngươi có phải gã đó hay không nào?}
{162}{}{Đúng vậy.}
{163}{}{Như cá gặp nước.}
{164}{}{Không.}
{165}{}{Được rồi, làm nhanh nào. Tháo cái đó xuống và ta sẽ cho ngươi bộ giáp mới.}
{166}{}{Ông chỉ toàn phát ra tiếng rè thôi.}
{167}{}{Hở?}
{168}{}{Okay.}
{169}{}{Ông định đuổi tôi á? Tôi không nghĩ vậy đâu!}
{170}{}{Ồ, không có gì.}
{171}{}{Bộ power armor. Đưa ta bộ power armor, đồ đần.}
{172}{}{Okay.}
{173}{}{Tôi đã giao dịch rồi. Tôi sẽ không đưa cho ông đâu.}
{174}{}{Tôi có thứ này cho ông đây, đồ chết tiệt.}
{175}{}{Được rồi, bộ đồ này. Giờ thì cút khỏi đây ngay.}
{176}{}{Đồ chó chết; ngươi không có bộ đồ. Cút khỏi đây ngay!}
{177}{}{Ngươi đang nói cái quái gì thế? Đưa ta bộ đồ.}
{178}{}{Được rồi, đây rồi!}
{179}{}{Bỏ đi!}
{180}{}{Rồi, J. Okay, đơn vị?}
{181}{}{Arroyo.}
{182}{}{Không hề.}
{183}{}{Tôi có thứ hay hơn.}
{184}{}{42.}
{185}{}{Ngươi điếc à? Ngươi là ai?}
{186}{}{Tôi là người mới?}
{187}{}{Chưa, chưa nghe đến lần nào.}
{188}{}{Tân binh à? Chắc là ngươi muốn được cấp quân trang. Sao chẳng đứa đéo nào báo cho ta việc này thế?
Tên ngươi là gì?}
{189}{}{Hở? Ông chỉ toàn phát ra tiếng rè thôi.}
{190}{}{[Tên người chơi]}
{191}{}{Không đâu nếu tôi bắn trước!}
{192}{}{Chờ đã -- mày không phải lính ở đây! LÍNH GÁC ĐÂU!}
{193}{}{Này đồ lính, ta đã đưa bộ quân trang cho ngươi rồi. Giờ thì cút khỏi đây ngay.}
{194}{}{Muốn gì?}
{195}{}{Droog?}
