{100}{}{Bất ngờ chưa -- trông giống một gã mặc power armor.}
{101}{}{Đúng vậy, vẫn là một gã mặc power armor.}
{102}{}{Ông ta có miếng phù hiệu gì đó trên tấm giáp ngực, trông khác với những người khác mà bạn
đã thấy quanh đây.}
{103}{}{<Rè rè> - kho khí giới!}
{104}{}{Cái gì - <tiếng nhiễu!>>}
{105}{}{(Vậy là Trung sĩ cử ngươi đến về việc cần power armor. Ồ, tất cả những gì ta có ở đây 
là có một bộ đang bảo trì. Có thể vẫn còn chút vấn đề, nên cẩn thận chút. Kí vào đây).}
{106}{}{Ờ... ông nhắc lại được không?}
{107}{}{Tôi nghĩ là có vấn đề với bộ giáp của ông.}
{108}{}{Được, tôi sẽ làm vậy.}
{109}{}{Không đâu. Quên đi.}
{110}{}{Ngươi là người mà Arch đã gọi đàm vào à?}
{111}{}{Có chắc là ngươi không phải gã đó không?}
{112}{}{Hở?}
{113}{}{Đúng vậy.}
{114}{}{Không.}
{115}{}{Ngươi là ai? Ngươi làm gì ở đây?}
{116}{}{Cái gì?}
{117}{}{Ờ... tôi là người mới ở đây?}
{118}{}{Ú òa!}
{119}{}{Ngươi là ai? Ngươi làm gì ở đây?}
{120}{}{Cái gì?}
{121}{}{Ờ... tôi là người mới ở đây?}
{122}{}{Ú òa!}
{123}{}{Ý ngươi là sao? Bộ giáp này đang hoạt động bình thường! Ngươi có kí giấy hay không nào?}
{124}{}{Tôi chẳng hiểu từ nào cả.}
{125}{}{Bộ đám của ông bị hỏng rồi.}
{126}{}{Rồi, sao cũng được.}
{127}{}{Kết thúc trò này thôi!}
{128}{}{(Cái gì, ngươi điếc à? Ta đã nói là ta có giáp; chỉ cần kí vào đây).}
{129}{}{Gã hề này. Ồ, ta không cần. Ngươi đi mà giải thích cho Trung sĩ về việc sao ngươi không có quân phục!}
{130}{}{Hở?}
{131}{}{Okay, được rồi. Tôi sẽ làm vậy.}
{132}{}{Quên đi, được chứ?}
{133}{}{Bộ đàm của ngươi không hỏng. Ta có thể nghe rõ ngươi nói gì. Chỉ cần kí vào giấy và chúng ta
xong việc.}
{134}{}{Hở?}
{135}{}{Được rồi, ta chịu rồi!}
{136}{}{Ngươi muốn ta làm gì? Ta không phải loại người đó!}
{137}{}{Được rồi, tên ngươi là gì?}
{138}{}{[Tên người chơi]}
{139}{}{Pisces?}
{140}{}{Tôi muốn bộ power armor.}
{141}{}{Cá kiếm.}
{142}{}{Đúng vậy. Đơn vị?}
{143}{}{Arroyo.}
{144}{}{Không hề.}
{145}{}{Tôi có thứ hay hơn.}
{146}{}{42.}
{147}{}{Thứ có S hay C?}
{148}{}{Đúng vậy.}
{149}{}{Không.}
{150}{}{Tôi không chắc.}
{151}{}{Ngươi sẽ có bộ giáp khi nào ta xong việc và sẵn sàng! Nào, giờ thì trả lời câu hỏi đi.}
{152}{}{[Tên người chơi]}
{153}{}{Pisces?}
{154}{}{Cá kiếm.}
{155}{}{Arroy -- Chờ đã! Bọn ta vừa mới dẹp chỗ đó. Mày là một gã tộc chết tiệt! Lính gác đâu!}
{156}{}{Này, gã hề, đừng có bày trò hoặc ta sẽ cho người lôi ngươi ra làm thịt đấy. Trả lời câu hỏi đi.}
{157}{}{Arroyo.}
{158}{}{42.}
{159}{}{Được rồi! Lê đít về chỗ trung sĩ đi. Ta gửi ngươi về đó chịu phạt. Giải tán.}
{160}{}{The 42nd, eh? Good unit. Okay. Here's your gear. Dismissed, soldier.}
{161}{}{What are you, deaf? Are you the guy or not?}
{162}{}{Đúng vậy.}
{163}{}{Like a fish in water.}
{164}{}{Not.}
{165}{}{Okay, let's make this quick. Take that off and I'll give you a new suit.}
{166}{}{You're nothing but static.}
{167}{}{Hở?}
{168}{}{Okay.}
{169}{}{You're gonna off me? I don't think so!}
{170}{}{Oh, well never mind.}
{171}{}{The power armor. Give me the power armor, you moron.}
{172}{}{Okay.}
{173}{}{I already made the deal. I'm not giving you any more.}
{174}{}{You bet I got something for you, you bastard.}
{175}{}{Okay, here's the suit. Now get out of here.}
{176}{}{You moron; you don't have the suit. Get out of here!}
{177}{}{What the hell are you talking about? Give me the suit.}
{178}{}{All right, already!}
{179}{}{Screw this!}
{180}{}{Right, J. Okay, Unit?}
{181}{}{Arroyo.}
{182}{}{Không hề.}
{183}{}{Tôi có thứ hay hơn.}
{184}{}{42.}
{185}{}{You deaf? Who are you?}
{186}{}{I'm the new guy?}
{187}{}{Nope, never heard of 'em.}
{188}{}{New guy, eh? Suppose you want your issue. Why don't anybody ever tell me these things? What's
 your name?}
{189}{}{Huh? You ain't nothing but static.}
{190}{}{[Tên người chơi]}
{191}{}{Not if I shoot first!}
{192}{}{Wait a minute -- you're not one of us! GUARDS!}
{193}{}{Look soldier, I already gave you your gear, so get on out of here.}
{194}{}{Muốn gì?}
{195}{}{Droog?}
