{100}{}{Bạn thấy một lính gác.}
{101}{}{Bạn thấy một lính gác mặc áo giáp chiến đấu.}
{102}{}{Bạn thấy ai đó mặc áo giáp chiến đấu. Có miếng phù hiệu trên tấm giáp ngực
mà bạn không nhận ra.}
{103}{}{Không có gì mới.}
{104}{}{Tôi không thấy có gì mới, cậu thì sao?}
{105}{}{Này cậu lính, sao cậu không về vị trí gác đi? Đừng có đi lang thang ở đây.}
{106}{}{Cậu đang không mặc quân phục.}
{107}{}{Tốt hơn hết là đến chỗ Trung sĩ báo cáo rồi đi nhận quân phục đi.}
{108}{}{Cậu to gan lắm mới đi lại mà không mặc quân phục đấy. Tốt nhất là nên đi báo lại cho hậu cần đi.}
{109}{}{Chúng mày là thế đéo nào... Báo động! Có kẻ xâm nhập!}
{110}{}{Chúng ta đã bị xâm nhập! Báo động!}
{111}{}{Có nhiều kẻ đột nhập! Rung chuông báo động lên!}
{112}{}{Cảnh báo an ninh! Khóa căn cứ!}
{113}{}{Bảo vệ toàn bộ căn cứ! Chúng ta đang báo động!}
{114}{}{Báo động có kẻ đột nhập! Vào mã đỏ!}
{115}{}{Chúng tao sẽ cho mày cạp đất!}
{116}{}{Enclave sẽ thống trị cả thế giới!}
{117}{}{Mày phải chết để Enclave tồn tại!}
{118}{}{Rất tiếc, cậu lính. Đây là khu cấm nhân sự trong căn cứ. Tôi yêu cầu cậu
rời khỏi chỗ này.}
{119}{}{Tiến sĩ muốn ngộ giết con Vuốt. Ông ta không muốn tự làm.}
{120}{}{Được, ngộ đi.}
{121}{}{Tiến sĩ muốn tôi giết mẫu vật thay. Ông ta không muốn tự tay làm.}
{122}{}{I knew the bastard wouldn't have the balls to do it himself. Oh no, it's okay
 if one of us gets fucked up. (sigh) Oh well. Go on in and good luck, soldier.}
{123}{}{Cám ơn.}
{124}{}{Why are you looking at me like that, soldier?}
{125}{}{Me hear you call Snookie. That cute.}
{126}{}{I hear you're called Snookie. I think that's cute.}
{127}{}{What... He told you that? When I get off duty I'm going to kick his ass...
 Move along, soldier. And wipe that smirk off your face!}
{128}{}{Okay.}
