{100}{}{Bạn thấy một lính gác.}
{101}{}{You see a guard in combat armor.}
{102}{}{You see someone wearing combat armor. There is an insignia on the breastplate
 that you are unfamiliar with.}
{103}{}{Nothing to report.}
{104}{}{Nothing going on with me, how 'bout you?}
{105}{}{Shouldn't you be at your post, soldier? It's not good to wander about here.}
{106}{}{You're out of uniform.}
{107}{}{You better report to the Sarge and get suited up.}
{108}{}{Cậu to gan lắm mới đi lại mà không mặc quân phục đấy. Tốt nhất là nên đi báo lại cho hậu cần đi.}
{109}{}{Chúng mày là thế đéo nào... Báo động! Có kẻ xâm nhập!}
{110}{}{Chúng ta đã bị xâm nhập! Báo động!}
{111}{}{Có nhiều kẻ đột nhập! Rung chuông báo động lên!}
{112}{}{Cảnh báo an ninh! Khóa căn cứ!}
{113}{}{Bảo vệ toàn bộ căn cứ! Chúng ta đang báo động!}
{114}{}{Báo động có kẻ đột nhập! Vào mã đỏ!}
{115}{}{Chúng tao sẽ cho mày cạp đất!}
{116}{}{Enclave sẽ thống trị cả thế giới!}
{117}{}{Mày phải chết để Enclave tồn tại!}
{118}{}{Sorry, soldier. That area is off limits to base personnel. I have to ask you
 to leave.}
{119}{}{Doc want me kill D'claw. He no want do himself.}
{120}{}{Được, ngộ đi.}
{121}{}{Doc wants me to kill the critter for him. He doesn't want to do it himself.}
{122}{}{I knew the bastard wouldn't have the balls to do it himself. Oh no, it's okay
 if one of us gets fucked up. (sigh) Oh well. Go on in and good luck, soldier.}
{123}{}{Cám ơn.}
{124}{}{Why are you looking at me like that, soldier?}
{125}{}{Me hear you call Snookie. That cute.}
{126}{}{I hear you're called Snookie. I think that's cute.}
{127}{}{What... He told you that? When I get off duty I'm going to kick his ass...
 Move along, soldier. And wipe that smirk off your face!}
{128}{}{Okay.}
