{100}{}{Bạn thấy một lính gác.}
{101}{}{Bạn thấy một lính gác mặc áo giáp chiến đấu.}
{102}{}{Bạn thấy ai đó mặc áo giáp chiến đấu. Có miếng phù hiệu trên tấm giáp ngực
mà bạn không nhận ra.}
{103}{}{Không có gì mới.}
{104}{}{Tôi không thấy có gì mới, cậu thì sao?}
{105}{}{Này cậu lính, sao cậu không về vị trí gác đi? Đừng có đi lang thang ở đây.}
{106}{}{Cậu đang không mặc quân phục.}
{107}{}{Tốt hơn hết là đến chỗ Trung sĩ báo cáo rồi đi nhận quân phục đi.}
{108}{}{Cậu to gan lắm mới đi lại mà không mặc quân phục đấy. Tốt nhất là nên đi báo lại cho hậu cần đi.}
{109}{}{Chúng mày là thế đéo nào... Báo động! Có kẻ xâm nhập!}
{110}{}{Chúng ta đã bị xâm nhập! Báo động!}
{111}{}{Có nhiều kẻ đột nhập! Rung chuông báo động lên!}
{112}{}{Cảnh báo an ninh! Khóa căn cứ!}
{113}{}{Bảo vệ toàn bộ căn cứ! Chúng ta đang báo động!}
{114}{}{Báo động có kẻ đột nhập! Vào mã đỏ!}
{115}{}{Chúng tao sẽ cho mày cạp đất!}
{116}{}{Enclave sẽ thống trị cả thế giới!}
{117}{}{Mày phải chết để Enclave tồn tại!}
{118}{}{Rất tiếc, cậu lính. Đây là khu cấm nhân sự trong căn cứ. Tôi yêu cầu cậu
rời khỏi chỗ này.}
{119}{}{Tiến sĩ muốn ngộ giết con Vuốt. Ông ta không muốn tự làm.}
{120}{}{Được, ngộ đi.}
{121}{}{Tiến sĩ muốn tôi giết mẫu vật thay. Ông ta không muốn tự tay làm.}
{122}{}{Tôi biết là lão chết tiệt đấy không dám tự tay làm mà. Ôi, kiểu gì thì cũng có
người phải nhúng bùn. (thở dài) Ồ được rồi. Vào đi và chúc may mắn, cậu lính.}
{123}{}{Cám ơn.}
{124}{}{Sao cậu lại nhìn tôi như thế hả, cậu lính?}
{125}{}{Ngộ nghe cô gọi là Snookie. Yêu đấy.}
{126}{}{Tôi nghe nói cô là Snookie. Tên dễ thương thật đấy.}
{127}{}{Cái... Hắn ta nói cho cậu à? Khi nào hết ca gác tôi sẽ cho hắn ta một trận...
Bước đi, cậu lính. Và thôi cái điệu cười trên mặt đi!}
{128}{}{Okay.}
