{100}{}{Bạn thấy một cái máy tính.}
{101}{}{Bạn thấy một cái máy tính.}
{102}{}{Bạn thấy cái máy tính trung tâm của Navarro.}
{103}{}{Vui lòng nhập mật khẩu.}
{104}{}{Nhập "Snookie"}
{105}{}{Quên cái đụ đị.}
{106}{}{Mẹ nó chứ.}
{107}{}{Cố bẻ khóa hệ thống.}
{108}{}{Chào mừng đến với Enclave. Bạn có quyền truy cập hệ thống giới hạn trong phiên này. Để thuận tiện cho việc sử dụng, hệ thống đã được trang bị thiết bị phân tích câu Tiếng Anh. Vui lòng nhập tất cả yêu cầu bằng Tiếng Anh.}
{109}{}{Tôi có thể giúp gì được?}
{110}{}{Bản vẽ máy bay ở đâu?}
{111}{}{Căn cứ chính của Enclave ở chỗ nào?}
{112}{}{Kho khí giới đâu?}
{113}{}{Chỉ huy căn cứ đâu?}
{114}{}{Ngộ chắc hết rồi.}
{115}{}{Bản vẽ máy bay trực thăng ở chỗ nào?}
{116}{}{Căn cứ chính của Enclave nằm ở đâu?}
{117}{}{Kho khí giới nằm ở đâu?}
{118}{}{Phòng của chỉ huy căn cứ ở chỗ nào?}
{119}{}{Tôi chắc vậy là đủ rồi.}
{120}{}{Đang tìm kiếm... Đang truy cập vào hồ sơ kho hiện tại... Nhận được dữ liệu. Hồ sơ hiện tại cho biết có 1 bản sơ đồ máy bay lên thẳng trong kho. Bốn bảo sao sơ đồ máy bay lên thẳng đã được yêu cầu trong quý này. Bốn bản sao sơ đồ máy bay lên thẳng đã được gửi trong quý này. Ba bản sao sơ đồ máy bay lên thẳng đã được báo cáo bị mất trong quý này. Sơ đồ máy bay lên thẳng được lưu trữ trong phòng bảo trì.}
{121}{}{Okê. Bảo trì đâu?}
{122}{}{Rồi. Thế phòng bảo trì ở đâu?}
{123}{}{Đang tìm kiếm... Đang truy cập tệp kiến trúc căn cứ... Nhận được dữ liệu. Phòng bảo trì nằm trên mặt đất ở góc Đông Bắc của căn cứ.}
{124}{}{Cám ơn.}
{125}{}{Đang tìm kiếm... Đang truy cập bản đồ địa lí... Nhận được dữ liệu. Căn cứ chính của Enclave cách bờ biển California giáp Thái Bình Dương 175 dặm, có tọa độ 37 độ 18 phút vĩ độ Bắc, 120 độ 7 phút kinh độ tây.}
{126}{}{Mấy thứ đó nghĩa quái gì vậy?}
{127}{}{Mấy con số quái quỷ đó có nghĩa là gì vậy?}
{128}{}{Đang tìm kiếm... Đang truy cập từ điển tiếng lóng Tiếng Anh... Nhận được dữ liệu. Bản dịch như sau: 1) Cách xa ngoài biển. 2) Đi từ bờ biển California. 3) Phía Tây thành phố San Fransico. 4) Nếu không hiểu được hệ thống tọa độ địa lí thì bạn sẽ không tìm được.}
{129}{}{Đi cách nào?}
{130}{}{Tôi có thể đến đó bằng cách nào?}
{131}{}{Đang tìm kiếm... Đang truy cập thư mục vận tải... Nhận được dữ liệu. Tệp vận tải cho biết có 1.257 phương tiện có thể đi đến căn cứ chính Enclave. Tuy nhiên, theo hồ sơ thì hiện chỉ còn 2 cách để đi. Có thể đi bằng máy bay trực thăng từ căn cứ tiền phương Navarro. Có thể đi bằng tàu thủy từ cảng San Fransico. Vui lòng lưu ý rằng đường đi bằng tàu thủy đã được đánh dấu là không sử dụng được do đạo luật an ninh 9837-334-27A. Tàu đã bị vô hiệu hóa và cần có bộ mã khóa để kích hoạt lại. Chỉ huy căn cứ tiền phương Navarro hiện đang giữ bộ mã khóa.}
{132}{}{Okay.}
{133}{}{Hiểu rồi.}
{134}{}{Đang tìm kiếm... Đang truy cập tệp kiến trúc căn cứ... Nhận được dữ liệu. Kho khí giới nằm dưới lòng đất ở góc Tây Bắc căn cứ.}
{135}{}{Ngộ hiểu rồi.}
{136}{}{Được, hiểu rồi.}
{137}{}{Đang tìm kiếm... Đang truy cập tệp kiến trúc căn cứ... Nhận được dữ liệu. Phòng chỉ huy căn cứ nằm dưới lòng đất ở góc Đông Bắc căn cứ.}
{138}{}{Được rồi.}
{139}{}{Được đấy.}
{140}{}{Cám ơn đã truy cập EnclaveNet. Đang đăng xuất...}
{141}{}{Đã xong.}
{142}{}{Lệnh?}
{143}{}{Đã phát hiện hành vi trái phép trong khu phức hợp máy tính chính. Báo động an ninh. Báo động an ninh.}
{144}{}{Bắt đầu chương trình chào mừng.}
{145}{}{Cứt thật!}
{146}{}{Đang tiến hành Khóa an ninh hệ thống.}
