{100}{}{Bạn thấy một kĩ thuật viên.}
{101}{}{Bạn thấy một kĩ sư máy tính.}
{102}{}{Bạn thấy một người mặc áo khoác phòng thí nghiệm kín người với miếng bảo hộ túi và một nắm bút.}
{103}{}{Chào cậu lính.}
{104}{}{Vui lòng đừng chạm vào thứ gì.}
{105}{}{Lính cấp thấp đáng ra không được vào đây.}
{106}{}{Cậu đang không mặc quân phục. }
{107}{}{Tốt hơn hết là nên đi mặc đồ vào. Kho khí giới ở cuối hành lang bên trái.}
{108}{}{Cậu to gan lắm mới đi lại mà không mặc quân phục đấy. Tốt nhất là nên đi báo lại cho hậu cần đi.}
{109}{}{Chúng mày là thế đéo nào... Báo động! Có kẻ xâm nhập!}
{110}{}{Chúng ta đã bị xâm nhập! Báo động!}
{111}{}{Có nhiều kẻ đột nhập! Rung chuông báo động lên!}
{112}{}{Cứt thật! Cho cứu viện bắt đầu vào đi.}
{113}{}{Đóng tất cả các hoạt động bí mật.}
{114}{}{Bảo vệ hệ thống và bật tất cả mật khẩu an ninh.}
{115}{}{Tôi là nhà khoa học, không phải lính chiến!}
{116}{}{Chiếu đầu nhọn của mũi laser về hướng kẻ địch. Rồi bóp cò.}
{117}{}{Cứu! Cứu! Chạy về phía phòng lab máy tính!}
