{100}{}{Bạn thấy một kĩ thuật viên.}
{101}{}{Bạn thấy một kĩ thuật viên của Enclave.}
{102}{}{Bạn thấy một người mặc áo khoác phòng thí nghiệm. Ông ta trông có vẻ rất tự tin.}
{103}{}{Yes soldier?}
{104}{}{Đây chỗ nào?}
{105}{}{Ngộ chỉ chào. Ngộ đi giờ.}
{106}{}{Đây là nơi nào?}
{107}{}{Chỉ chào thôi. Gặp lại sau.}
{108}{}{Đây là phòng máy tính. Máy chủ ở đó, bảng giao diện bên cạnh, còn đống này là thiết bị lưu trữ dữ liệu dạng băng holotape. Đây là thiết bị mới và tân tiến nhất.}
{109}{}{Oh. Uh, What you do?}
{110}{}{Vậy ông làm gì ở đây?}
{111}{}{Tôi là chuyên viên phân tích máy tính cấp cao. Tôi lo việc bảo dưỡng toàn bộ thiết bị ở đây.}
{112}{}{Ồ. Ngộ dùng máy tính?}
{113}{}{Ngộ không hiểu. Ngộ đi.}
{114}{}{Này, tôi có thể dùng hệ thống một chút không? Thế nào nhỉ, kiểm tra thôi?}
{115}{}{Này, nói chuyện vui đấy. Gặp lại sau nhé.}
{116}{}{Well... I'm not supposed to allow anyone other than trained personnel to use the equipment. It's all rather complex and delicate you understand.}
{117}{}{Làm ơn? Ngộ không phá.}
{118}{}{I promise not to break it}
{119}{}{All right. You can access the system from the terminal over there. Just be careful please. They'll shoot us both if you damage that machine. Oh, the guest password is 'Snookie.'}
{120}{}{Tôi rất tiếc nhưng không thể được. Tôi thậm chí còn không được phép để người vào trong phòng chứ đừng nói là để họ sử dụng thiết bị.}
{121}{}{Snookie? Snookie nào?}
{122}{}{Ok. Ngộ hiểu.}
{123}{}{Snookie? Snookie là cái quái gì thế?}
{124}{}{Được rồi. Tôi hiểu.}
{125}{}{"Snookie" là biệt danh của bạn gái tôi. Dễ thương chứ hả? Mà cô ấy đứng ngoài hành lang kìa. Cô ấy là một lính gác.}
{126}{}{Ok, được rồi. Cám ơn.}
{127}{}{Yeah... Cute. Thanks.}
{128}{}{Cậu đang không mặc quân phục. }
{129}{}{Tốt hơn hết là nên đi mặc đồ vào. Kho khí giới ở cuối hành lang bên trái.}
{130}{}{Cậu to gan lắm mới đi lại mà không mặc quân phục đấy. Tốt nhất là nên đi báo lại cho hậu cần đi.}
{131}{}{Chúng mày là thế đéo nào... Báo động! Có kẻ xâm nhập!}
{132}{}{Chúng ta đã bị xâm nhập! Báo động!}
{133}{}{Có nhiều kẻ đột nhập! Rung chuông báo động lên!}
{134}{}{Cứt thật! Cho cứu viện bắt đầu vào đi.}
{135}{}{Đóng tất cả các hoạt động bí mật.}
{136}{}{Bảo vệ hệ thống và bật tất cả mật khẩu an ninh.}
{137}{}{Tôi là nhà khoa học, không phải lính chiến!}
{138}{}{Chiếu đầu nhọn của mũi laser về hướng kẻ địch. Rồi bóp cò.}
{139}{}{Cứu! Cứu! Chạy về phía phòng lab máy tính!}
