{100}{}{Bạn thấy ai đó mặc power armor.}
{101}{}{Bạn thấy Sĩ quan quân nhu.}
{102}{}{Bạn thấy ai đó mặc power armor được thiết kế khác lạ.
Có miếng phù hiệu trên tấm giáp ngực mà bạn không nhận ra.}
{103}{}{Mấy người các ngươi là lũ quái nào thế... Báo động! Có kẻ đột nhập trong căn cứ!}
{104}{}{Cái gì... Ta có thể thấy tại sao cậu đến đây. Hẳn là cậu muốn
lột bỏ cái thứ cổ lỗ sĩ đang đeo trên người rồi.}
{105}{}{Sao lại không mặc quân phục hả, đồ lính?}
{106}{}{Chết đi!}
{107}{}{Ờ, thì...}
{108}{}{Ừ...}
{109}{}{Ngộ mới.}
{110}{}{Ngộ không lính của ông!}
{111}{}{Ừ, thì...}
{112}{}{Tôi là lính mới.}
{113}{}{Tôi không phải lính của ông!}
{114}{}{Ừ cái gì? Không nặn ra được lí do nào lọt tai à? Ta đang nghe đây, đồ lính!}
{115}{}{Ngộ chưa có quân phục.}
{116}{}{Tôi vẫn chưa có quân phục.}
{117}{}{Cậu hơi đần nhỉ? (thở dài) Ồ, không phải lỗi của cậu.
Ta có thằng em y như cậu. Mà cậu là lính mới ở đây à?
Ta không nhớ có gặp cậu trước kia.}
{118}{}{Lính mới à? Ta không nhớ có từng gặp qua.}
{119}{}{Đúng! Ngộ mới đây!}
{120}{}{Đúng vậy, tôi mới đến đây.}
{121}{}{Ồ, thế thì cậu sẽ cần đồ tiêu chuẩn. Đi đến kho khí giới, 
mặc đồ và nhận vũ khí. Sau đó đến báo cáo chỗ 
Trung sĩ huấn luyện.}
{122}{}{Cám ơn!}
{123}{}{Ổn rồi. Giờ thì biến khỏi đây đi. Ta có việc phải là và không
muốn bị quấy rầy.}
{124}{}{Giờ ta đang bận. Quay lại sau đi.}
{125}{}{Chào, tân binh. Ta mới nhận được cuộc gọi của Trung sĩ. Ông ta
bảo cậu đến nhận đồ rồi quay lại vị trí. Đúng chứ?}
{126}{}{Đúng vậy.}
{127}{}{Căn cứ đang có báo động và ta không nhận ra ngươi. Xuất trình
giấy tờ ra, đồ lính.}
{128}{}{Ngộ không có giấy tờ theo người.}
{129}{}{Ngộ không cần giấy tờ!}
{130}{}{Tôi không mang theo giấy tờ. Chúng ở trong hòm đồ rồi.}
{131}{}{Giấy tờ? Tôi có giấy tờ ở đây này!}
{132}{}{Trả lời sai rồi. Lúc nào mày cũng phải mang giấy tờ theo 
và mày phải biết điều đó!}
{133}{}{Chẹp.}
