{100}{}{Bạn thấy một người đàn ông mặc quân phục.}
{101}{}{Bạn thấy Quincy, thợ cơ khí.}
{102}{}{Bạn thấy một người đàn ông mặc quân phục. Nhìn mấy vết dầu mỡ bạn nghĩ
ông ta giống thợ cơ khí hơn là lính.}
{103}{}{Tên là Quincy, cậu lính. Sao cậu lại vỗ vai ta rồi đần mặt ra thế?}
{104}{}{Ngộ cần hỏi ông chuyện.}
{105}{}{Không có gì.}
{106}{}{Chào. Tôi cần hỏi mấy thứ.}
{107}{}{Không có gì.}
{108}{}{Được rồi, nhưng nhanh lên nhé. Ta còn phải xếp hàng nữa.}
{109}{}{Cần biết gì nào?}
{110}{}{Đây chỗ nào?}
{111}{}{Ngộ tìm bản vẽ máy bay trực thăng. Tìm đâu?}
{112}{}{Kĩ thuật bảo ngộ tìm bản vẽ máy bay trực thăng ở đây.}
{113}{}{Ngộ đi giờ.}
{114}{}{Đây là nơi nào?}
{115}{}{Tôi đang tìm bản vẽ máy bay trực thăng. Ông có biết là cần tìm ở đâu không?}
{116}{}{Một nhân viên kĩ thuật bảo tôi có thể tìm thấy bản vẽ máy bay trực thăng ở đây.}
{117}{}{Được, tôi đi đây.}
{118}{}{Đây là phòng bảo trì. Bọn ta sửa gần như mọi thứ, trừ máy bay trực thăng.}
{119}{}{Máy bay trực thăng sửa đâu?}
{120}{}{Máy bay trực thăng được sửa ở đâu thế?}
{121}{}{Chúng chỉ có thể đậu trong khoang chứa hoặc ngoài trời. Đến đấy rồi tự tìm tiếp, được chứ?}
{122}{}{Ồ... okay.}
{123}{}{Ồ, được. Tôi hiểu rồi.}
{124}{}{Ồ... Ta có bản sao đây nhưng làm sao ta có thể đưa cho bất kì gã ngốc
nào đến hỏi được. Cậu cần chúng làm gì?}
{125}{}{Ngộ có bạn phía Nam muốn.}
{126}{}{Ừ... thì...}
{127}{}{Tôi có mấy người bạn phía Nam muốn lấy bản vẽ.}
{128}{}{Trung sĩ bảo tôi đến lấy.}
{129}{}{Phía Nam... Đậu má! Có gián điệp! Lính gác! Báo động!}
{130}{}{Ồ ồ.}
{131}{}{Ồ ồ. Đạp phải cứt rồi.}
{132}{}{Thiếu một viên nữa là đầy băng rồi ha? Ồ, họ xếp cậu làm lính cũng phải.
Nghe này, Einstein, ta không thể đưa bản vẽ cho cậu mà không có giấy phép
được, rõ chứ? Quay lại chỗ đứa nào gửi cậu đến đây và xin đầy đủ giấy tờ
đi.}
{133}{}{Nghe này, Einstein, ta không thể đưa bản vẽ cho cậu mà không có giấy phép được, rõ chứ?
Quay lại chỗ đứa nào gửi cậu đến đây và xin đầy đủ giấy tờ đi.}
{134}{}{Được, ngộ đi.}
{135}{}{Không, ngộ bắn ông số một, tìm bản vẽ số hai, rồi... sau số hai là số mấy nhỉ?}
{136}{}{Này, được rồi.}
{137}{}{Không, chắc là tôi cho ông ăn đạn rồi đi tìm bản vẽ trong lúc ông
ngáp vì mất máu.}
{138}{}{Kĩ thuật bảo cậu... Ý cậu là Raul? Hắn ta bảo cậu đến đây?}
{139}{}{Ừ, đúng thế.}
{140}{}{Ừ, không.}
{141}{}{Đúng, đúng là gã đó.}
{142}{}{Không, tôi nghĩ đấy không phải là Raul.}
{143}{}{Mẹ kiếp! Đầu gã Raul này chắc phải rụng ra nếu không có ai gắn chặt vào đít mất!
Đây là lần thứ ba trong quý này thằng đầu khấc làm mất bản vẽ rồi! Và giờ hắn ta
thậm chí còn tụt cả bi vào trong nên không dám đến gặp yêu cầu ta nữa hả? Rồi,
bản vẽ ở trong tủ khóa ở kia. Ồ, khi nào cầm đến tay thì bảo thằng lìn đấy đến
đây gặp ta.}
{144}{}{Cám ơn.}
{145}{}{Quay lại rồi đấy. Có giấy phép chưa?}
{146}{}{Lại nữa à? Giờ thì là chuyện gì?}
{147}{}{Đúng, ngộ có súng plasma. Ngộ đủ rồi!}
{148}{}{Chưa.}
{149}{}{Đúng, tôi có khẩu súng to vãi lìn đây. Thế là đầy đủ giấy tờ rồi chứ!}
{150}{}{Chưa.}
{151}{}{Ngộ hỏi chuyện ông.}
{152}{}{Ngộ chỉ "chào" thôi.}
{153}{}{Tôi cần hỏi chút việc.}
{154}{}{Không có gì, chỉ "chào" thôi.}
{155}{}{Điên à? Đi loanh quanh mà không mặc quân phục? Đi mặc đồ vào!}
{156}{}{Trung sĩ mà bắt được cậu không mặc quân phục thì ông ấy sạc cho teo chim.}
{157}{}{Sao cậu lại không mặc quân phục?}
{158}{}{Đm! Chúng ta đang bị xâm nhập! Báo động!}
{159}{}{Có kẻ xâm nhập! Gọi bảo vệ ngay!}
{160}{}{Lính gác! Có kẻ đột nhập trong phòng bảo trì!}
{161}{}{Gì thế? Chúng ta bị tấn công à?}
{162}{}{Sao lại báo động? Chuyện gì thế?}
{163}{}{Cái củ lìn gì đang diễn ra thế?}
{164}{}{Này! Đừng có bới tung cả tủ lên thế.}
{165}{}{Ta đã bảo là đừng có động vào đồ của ta mà! Lính gác đâu!}
{200}{}{Được. Ồ, đừng có tin mọi thứ nghe được.}
{201}{}{Ai bảo cậu thế? Cho cậu một trận xong là ta sẽ đến dạy cho kẻ đó một bài học.}
{300}{}{Không thấy là ta đang bận hả?}
{301}{}{Này! Đừng có bới tung cả tủ lên thế!}
{302}{}{Ta đã bảo là đừng có động vào đồ của ta mà! Lính gác đâu!}
