{100}{}{Bạn thấy một người đàn ông mặc quân phục.}
{101}{}{Bạn thấy Quincy, thợ cơ khí.}
{102}{}{Bạn thấy một người đàn ông mặc quân phục. Nhìn mấy vết dầu mỡ bạn nghĩ
ông ta giống thợ cơ khí hơn là lính.}
{103}{}{Tên là Quincy, cậu lính. Sao cậu lại vỗ vai ta rồi đần mặt ra thế?}
{104}{}{Ngộ cần hỏi ông chuyện.}
{105}{}{Không có gì.}
{106}{}{Chào. Tôi cần hỏi mấy thứ.}
{107}{}{Không có gì.}
{108}{}{Được rồi, nhưng nhanh lên nhé. Ta còn phải xếp hàng nữa.}
{109}{}{Cần biết gì nào?}
{110}{}{Đây chỗ nào?}
{111}{}{Ngộ tìm bản vẽ máy bay trực thăng. Tìm đâu?}
{112}{}{Kĩ thuật bảo ngộ tìm bản vẽ máy bay trực thăng ở đây.}
{113}{}{Ngộ đi giờ.}
{114}{}{Đây là nơi nào?}
{115}{}{Tôi đang tìm bản vẽ máy bay trực thăng. Ông có biết là cần tìm ở đâu không?}
{116}{}{Một nhân viên kĩ thuật bảo tôi có thể tìm thấy bản vẽ máy bay trực thăng ở đây.}
{117}{}{Được, tôi đi đây.}
{118}{}{Đây là phòng bảo trì. Bọn ta sửa gần như mọi thứ, trừ máy bay trực thăng.}
{119}{}{Máy bay trực thăng sửa đâu?}
{120}{}{Máy bay trực thăng được sửa ở đâu thế?}
{121}{}{Chúng chỉ có thể đậu trong khoang chứa hoặc ngoài trời. Đến đấy rồi tự tìm tiếp, được chứ?}
{122}{}{Ồ... okay.}
{123}{}{Ồ, được. Tôi hiểu rồi.}
{124}{}{Ồ... Ta có bản sao đây nhưng làm sao ta có thể đưa cho bất kì gã ngốc
nào đến hỏi được. Cậu cần chúng làm gì?}
{125}{}{Ngộ có bạn phía Nam muốn.}
{126}{}{Ừ... thì...}
{127}{}{Tôi có mấy người bạn phía Nam muốn lấy bản vẽ.}
{128}{}{Trung sĩ bảo tôi đến lấy.}
{129}{}{Phía Nam... Đậu má! Có gián điệp! Lính gác! Báo động!}
{130}{}{Ồ ồ.}
{131}{}{Ồ ồ. Đạp phải cứt rồi.}
{132}{}{Thiếu một viên nữa là đầy băng rồi ha? Ồ, họ xếp cậu làm lính cũng phải.
Nghe này, Einstein, ta không thể đưa bản vẽ cho cậu mà không có giấy phép
được, rõ chứ? Quay lại chỗ đứa nào gửi cậu đến đây và xin đầy đủ giấy tờ
đi.}
{133}{}{Nghe này, Einstein, ta không thể đưa bản vẽ cho cậu mà không có giấy phép được, rõ chứ?
Quay lại chỗ đứa nào gửi cậu đến đây và xin đầy đủ giấy tờ đi.}
{134}{}{Được, ngộ đi.}
{135}{}{Không, ngộ bắn ông số một, tìm bản vẽ số hai, rồi... sau số hai là số mấy nhỉ?}
{136}{}{Này, được rồi.}
{137}{}{Không, chắc là tôi cho ông ăn đạn rồi đi tìm bản vẽ trong lúc ông
ngáp vì mất máu.}
{138}{}{Kĩ thuật bảo cậu... Ý cậu là Raul? Hắn ta bảo cậu đến đây?}
{139}{}{Uh, yeah.}
{140}{}{Uh, no.}
{141}{}{Yeah, that's the guy.}
{142}{}{No, I don't think it was Raul.}
{143}{}{Damn it! You know, Raul would lose his head if it weren't placed so
 firmly up his ass! This is the third time this quarter that he's lost those
 plans! And now he doesn't even have the brass bouncing balls to come to me
 and ask for them? Fine, they're in the locker over there. Oh and, when you
 deliver them, tell that asshole I want to see him.}
{144}{}{Cám ơn.}
{145}{}{So you're back. Did you get the authorization?}
{146}{}{You again? What is it now?}
{147}{}{Yeah, me got plasma rifle. That good enough me!}
{148}{}{Chưa.}
{149}{}{Yeah, I've got a big fucking gun. That's good enough for me!}
{150}{}{Chưa.}
{151}{}{Me ask you something.}
{152}{}{Me just say 'Hi'.}
{153}{}{I need to ask you something.}
{154}{}{Nothing, just saying 'Hi'.}
{155}{}{Are you nuts? Walking around here out of uniform? Get suited up!}
{156}{}{Trung sĩ mà bắt được cậu không mặc quân phục thì ông ấy sạc cho teo chim.}
{157}{}{Sao cậu lại không mặc quân phục?}
{158}{}{Đm! Chúng ta đang bị xâm nhập! Báo động!}
{159}{}{Có kẻ xâm nhập! Gọi bảo vệ ngay!}
{160}{}{Guard! Intruders in maintenance!}
{161}{}{Gì thế? Chúng ta bị tấn công à?}
{162}{}{Sao lại báo động? Chuyện gì thế?}
{163}{}{Cái củ lìn gì đang diễn ra thế?}
{164}{}{Hey! Don't be rummaging through those drawers.}
{165}{}{I told you not to go through my stuff! Guards!}
{200}{}{Yeah. Well, don't believe everything you hear.}
{201}{}{Who told you that? 'Cause he's next after I knock some sense into you.}
{300}{}{Can't you see that I am busy?}
{301}{}{Hey! Don't be rummaging through those drawers!}
{302}{}{I told you not to go through my stuff! Guards!}
