{100}{}{Bạn thấy một người thợ cơ khí.}
{101}{}{Bạn thấy Raul, thợ cơ khí.}
{102}{}{Bạn thấy một người đàn ông mặc bộ quân phục bẩn thỉu. Nhìn vào mấy vết
dầu mỡ bạn nghĩ người này giống thợ cơ khí hơn là lính, hơn nữa còn
chăm làm lắm.}
{103}{}{Xin lỗi, em giai, nhưng ta không có thời gian tán nhảm, rõ chứ? Ta còn
phải làm cho con chim này bay được.}
{104}{}{Tiến sĩ muốn sửa K-9. Ông ta nói ông có bộ phận.}
{105}{}{Ừ... okay.}
{106}{}{Ừ, Quincy muốn gặp ông. Ông ta bảo tôi nói cho ông biết.}
{107}{}{Tiến sĩ muốn sửa con chó. Ông ta cử tôi đến lấy bộ phận.}
{108}{}{Rồi. Tạm biệt.}
{109}{}{Raul, Quincy muốn gặp ông.}
{110}{}{Quincy à? Ồ, Raul không muốn gặp lão ta, em giai à. Raul chán đống
cứt đấy lắm rồi, hiểu chứ?}
{111}{}{Okay.}
{112}{}{Quincy nói ông đầu lìn. Ông sợ không dám đến.}
{113}{}{Được rồi.}
{114}{}{Quincy nói rằng ông là đồ đầu lìn, và rằng ông sợ không dám đến
chỗ ông ta báo cáo.}
{115}{}{ Này đứa kia, Raul không để yên cho ai ném cứt đâu nhé. Mày có thấy Quincy
sửa chim không? Làm đéo có chuyện. Chỉ có Raul mới sửa được mấy bé này thôi.
Biết tại sao không? Vì Quincy đéo biết cái lìn gì, rõ chưa!}
{116}{}{Ừ...}
{117}{}{Ờ...}
{118}{}{Này, xin lỗi em giai. Raul không nên quát cậu, hiểu chứ? Đâu phải lỗi của
cậu; cậu chỉ là người đưa tin. Này, em giai, cậu có đang bận gì không?}
{119}{}{Không, ngộ không bận. Sao chứ?}
{120}{}{Không hẳn, sao chứ?}
{121}{}{Hey look, man. Raul's going to go pay Quincy a visit, you know?
 Raul's going to clean the old man's clock.
 You stay here and watch Raul's birds. Ok?}
{122}{}{Me watch.}
{123}{}{Sure Raul. I'll do it for you, but not just anybody.}
{124}{}{Hey, thanks, man. Raul owes you one!
 Don't go away and, hey, man, if anybody
 screws with Raul's birds, you shoot them in the ass. Ok?}
{125}{}{Okay.}
{126}{}{Hey man, what you think you doing? Get the fuck away from that bird,
 man! Raul's got enough problems without you grunts fucking with things, you
 know? Damn flyboys are bad enough!}
{127}{}{Hey, man, Raul told you to keep the fuck away from his birds, man.
 Now Raul has to teach you to listen. Come on, man. Take off the fucking
 armor and go one on one, mano e mano with Raul.}
{128}{}{No, me not think so.}
{129}{}{Screw you, Raul. Me shoot you ass dead!}
{130}{}{No thanks, you're too tough for me pal.}
{131}{}{Why use fists when I have a perfectly good gun?}
{132}{}{Then don't fuck with Raul's birds, man! Get out of here!}
{133}{}{Okay.}
{134}{}{Raul thinks you must be nuts walking around here out of uniform.}
{135}{}{Hey, man, if the sergeant catches you out of uniform he'll hand
 you your ass.}
{136}{}{Why are you out of uniform, man?}
{137}{}{Đm! Chúng ta đang bị xâm nhập! Báo động!}
{138}{}{Có kẻ xâm nhập! Gọi bảo vệ ngay!}
{139}{}{Guard! Intruders in the hangar!}
{140}{}{Hey, man, what's up? We under attack?}
{141}{}{Why the alert, man? What's happening?}
{142}{}{Cái củ lìn gì đang diễn ra thế?}
{143}{}{Raul's going to put you in med lab, man.}
{144}{}{Hey, man, say your prayers!}
{145}{}{Raul's going to kick your ass!}
{146}{}{Hey, man, it's in the locker over there. Take it and tell the doc
 Raul says hi.}
{147}{}{Cám ơn.}
{150}{}{Hey, man! Raul don't like it when people mess with his shit. Get out, man.}
{151}{}{Raul told you not to go through his stuff! Guards!}
{200}{}{Raul heard you were talking shit about him again.}
{201}{}{This has happened once too often, asshole. Raul's gonna hurt you bad this time.}
{300}{}{Can't you see that Raul's busy?}
