{100}{}{Bạn thấy một người thợ cơ khí.}
{101}{}{Bạn thấy Raul, thợ cơ khí.}
{102}{}{Bạn thấy một người đàn ông mặc bộ quân phục bẩn thỉu. Nhìn vào mấy vết
dầu mỡ bạn nghĩ người này giống thợ cơ khí hơn là lính, hơn nữa còn
chăm làm lắm.}
{103}{}{Xin lỗi, em giai, nhưng ta không có thời gian tán nhảm, rõ chứ? Ta còn
phải làm cho con chim này bay được.}
{104}{}{Tiến sĩ muốn sửa K-9. Ông ta nói ông có bộ phận.}
{105}{}{Ừ... okay.}
{106}{}{Ừ, Quincy muốn gặp ông. Ông ta bảo tôi nói cho ông biết.}
{107}{}{Tiến sĩ muốn sửa con chó. Ông ta cử tôi đến lấy bộ phận.}
{108}{}{Rồi. Tạm biệt.}
{109}{}{Raul, Quincy muốn gặp ông.}
{110}{}{Quincy à? Ồ, Raul không muốn gặp lão ta, em giai à. Raul chán đống
cứt đấy lắm rồi, hiểu chứ?}
{111}{}{Okay.}
{112}{}{Quincy nói ông đầu lìn. Ông sợ không dám đến.}
{113}{}{Được rồi.}
{114}{}{Quincy nói rằng ông là đồ đầu lìn, và rằng ông sợ không dám đến
chỗ ông ta báo cáo.}
{115}{}{ Này đứa kia, Raul không để yên cho ai ném cứt đâu nhé. Mày có thấy Quincy
sửa chim không? Làm đéo có chuyện. Chỉ có Raul mới sửa được mấy bé này thôi.
Biết tại sao không? Vì Quincy đéo biết cái lìn gì, rõ chưa!}
{116}{}{Ừ...}
{117}{}{Ờ...}
{118}{}{Này, xin lỗi em giai. Raul không nên quát cậu, hiểu chứ? Đâu phải lỗi của
cậu; cậu chỉ là người đưa tin. Này, em giai, cậu có đang bận gì không?}
{119}{}{Không, ngộ không bận. Sao chứ?}
{120}{}{Không hẳn, sao chứ?}
{121}{}{Nghe này, cậu em. Raul sẽ đến chỗ Quincy một lúc, được chứ?
Raul sẽ đi thông não lão già dịch ấy.
Cậu em ở đây trông chim giúp Raul. Ok?}
{122}{}{Ngộ trông.}
{123}{}{Được chứ Raul. Tôi sẽ giúp ông, nhưng không phải ai tôi cũng hộ đâu nhé.}
{124}{}{Này, cám ơn em giai. Raul nhờ cậu lần này!
Đừng có rời khỏi đây, và em giai ơi, nếu có thằng nào
nghịch chim của Raul, cứ dí súng vào đít hắn. Ok?}
{125}{}{Okay.}
{126}{}{Này, đứa kia, làm cái gì đấy? Tránh con mẹ mày ra khỏi con chim sắt
ngay! Raul có thừa rắc rối rồi, không cần đến đám lính quèn đến phá nữa đâu,
hiểu chứ? Mẹ nó mấy đứa ruồi bay là đủ lắm rồi!}
{127}{}{Này, Raul đã bảo là tránh con mẹ mày ra khỏi con chim tao rồi. Giờ thì
Raul sẽ dạy cho mày một bài học. Đến đây nào, thằng cờ hó. Tụt bộ giáp
củ lìn ra vào đây một chọi một, meno e mano, với Raul nào.}
{128}{}{Không, ngộ không nghĩ vậy.}
{129}{}{Cút đi, Raul. Ngộ bắn ông nát đít!}
{130}{}{Không được đâu sói ạ, sói cứng vãi lìn ai mà dại.}
{131}{}{Có khẩu súng ngon thế này thì ngu sao mà phải chơi tay không?}
{132}{}{Thế thì đừng có đmm nghịch chim của Raul nữa! Cút khỏi đây ngay!}
{133}{}{Okay.}
{134}{}{Raul nghĩ cậu em chắc phải điên lắm mới lượn lờ quanh đây mà không mặc quân phục.}
{135}{}{Này cậu em, trung sĩ mà bắt được cậu không mặc quân phục là
lão ta cho cậu nát mông đấy.}
{136}{}{Sao cậu em lại không mặc quân phục thế?}
{137}{}{Đm! Chúng ta đang bị xâm nhập! Báo động!}
{138}{}{Có kẻ xâm nhập! Gọi bảo vệ ngay!}
{139}{}{Lính gác! Có kẻ đột nhập vào khoang chứa máy bay!}
{140}{}{Này cậu em, sao thế? Chúng ta bị tấn công à?}
{141}{}{Sao lại báo động thế? Có chuyện gì vậy?}
{142}{}{Cái củ lìn gì đang diễn ra thế?}
{143}{}{Raul sẽ cho cậu vào bệnh xá đấy, cậu em.}
{144}{}{Này cậu em, hãy cầu nguyện đi!}
{145}{}{Raul sẽ cho cậu em một trận!}
{146}{}{Này cậu em, nó ở trong cái tủ khóa đằng kia. Lấy đi và nói với tiến sĩ
là Raul gửi lời chào nhé.}
{147}{}{Cám ơn.}
{150}{}{Hey, man! Raul don't like it when people mess with his shit. Get out, man.}
{151}{}{Raul told you not to go through his stuff! Guards!}
{200}{}{Raul heard you were talking shit about him again.}
{201}{}{This has happened once too often, asshole. Raul's gonna hurt you bad this time.}
{300}{}{Can't you see that Raul's busy?}
