{100}{}{Bạn thấy một kĩ thuật viên.}
{101}{}{Bạn thấy một kĩ thuật viên của Enclave.}
{102}{}{Bạn thấy một người mặc áo khoác phòng thí nghiệm. Ông ta trông có vẻ rất tự tin.}
{103}{}{Vâng?}
{104}{}{Ngộ mới đây. Cần hỏi.}
{105}{}{Ngộ chỉ chào. Ngộ đi giờ.}
{106}{}{Tôi là người mới ở đây và đang cố làm quen với căn cứ. Tôi có thể hỏi vài câu không?}
{107}{}{Chỉ chào thôi. Gặp lại sau.}
{108}{}{Chắc rồi, anh lính.}
{109}{}{Tôi có thể giúp gì đây?}
{110}{}{Đây chỗ nào?}
{111}{}{Việc ông gì?}
{112}{}{Căn cứ chính Enclave chỗ mô?}
{113}{}{Ngộ tìm bản vẽ máy bay trực thăng. Ngộ tìm đâu?}
{117}{}{Ngộ đi giờ.}
{118}{}{Đây là nơi nào?}
{119}{}{Công việc của ông ở đây là gì?}
{120}{}{Căn cứ chính của Enclave nằm ở đâu?}
{121}{}{Tôi cần xem bản vẽ máy bay trực thăng. Chúng để ở đâu thế?}
{125}{}{Không có gì. Tôi phải đi đây.}
{126}{}{Đây là trung tâm liên lạc. Tại đây chúng tôi xử lí toàn bộ nội dung liên lạc với căn cứ chính và những tiền đồn đã được tạo lập khác.}
{127}{}{Ngộ thấy. Ngộ hỏi thêm.}
{128}{}{Được rồi. Hỏi thêm mấy câu nữa.}
{129}{}{Tôi là nhân viên kĩ thuật của trung tâm liên lạc, binh nhất. Tôi thực hiện nhiệm vụ giám sát. Chủ yếu là tôi đảm bảo những người khác không mắc lỗi.}
{130}{}{Ừ... vậy à.}
{131}{}{Tốt. Cứ tiếp tục đi.}
{132}{}{Anh lính, thông tin đó thuộc mục cơ bản "cần phải biết". Nếu anh phải đi hỏi thì tức là anh không cần biết.}
{133}{}{Okay.}
{134}{}{Thôi nào, tôi có phải dân toọc đâu. Chúng ta ăn mặc giống nhau mà; có thấy cái phù hiệu trên giáp đây không?}
{135}{}{Tôi hiểu rồi.}
{136}{}{Vâng. Căn cứ chính ở ngoài khơi bờ biển Thái Bình Dương gần thành phố San Fransico. Tôi có thể biết tại sao anh hỏi vậy không?}
{137}{}{Anh lính, tôi đã bảo thông tin đó thuộc mục cơ bản "cần phải biết" rồi.}
{138}{}{Vì lí do an ninh, tôi đang đi kiểm tra mức nhận biết thông tin của nhân sự trong căn cứ. Giờ thì nói cho tôi tất cả những cách mà ông biết để đến được căn cứ chính đi.}
{139}{}{Tôi hiểu rồi.}
{140}{}{Vâng. Đầu tiên, máy bay trực thăng là phương pháp chính để đi đến căn cứ chính. Do tính phức tạp của hành trình mà rất khó để nhân sự cấp thấp có thể lái máy bay. Thứ hai là có tàu chạy xăng vẫn còn hoạt động ở cảng San Fransico. Tuy nhiên, chiếc tàu này đã bị vô hiệu hóa và cần có bộ mã khóa để khởi động lại. Chỉ huy căn cứ là người đang giữ bộ mã khóa. Thứ ba, nếu có trang thiết bị phù hợp thì có thể bơi đến căn cứ chính nhưng khả năng sống sót gần như bằng 0.}
{141}{}{Cám ơn.}
{142}{}{Cám ơn.}
{143}{}{Chúng ở trong phòng bảo trì, bên cạnh phòng kiểm soát không lưu.}
{144}{}{Okay.}
{145}{}{Hiểu rồi.}
{155}{}{Cậu điên à, đi lại ở đây mà không mặc quân phục? Mặc đồ vào!}
{156}{}{Nếu trung sĩ mà bắt được không mặc quân phục thì ông ta sẽ dần cho nát đít đấy.}
{157}{}{Sao cậu lại không mặc quân phục?}
{158}{}{Đm! Chúng ta đang bị xâm nhập! Báo động!}
{159}{}{Có kẻ xâm nhập! Gọi bảo vệ ngay!}
{160}{}{Bảo vệ đâu! Có kẻ xâm nhập trong trung tâm liên lạc!}
{161}{}{Gì thế? Chúng ta bị tấn công à?}
{162}{}{Sao lại báo động? Chuyện gì thế?}
{163}{}{Cái củ lìn gì đang diễn ra thế?}
{164}{}{Tôi chỉ là nhân viên kĩ thuật thôi, đừng bắn tôi!}
{165}{}{Tôi đâu có đăng kí chiến đấu, chỉ huấn luyện kĩ thuật thôi!}
{166}{}{Đây là áo khoác thí nghiệm chứ có phải giáp đâu! Tôi biến khỏi đây đây!}
