{100}{}{Một người lính trong đồng phục nhiệm vụ.}
{101}{}{Một vài Pfc-Tech, hạng X.}
{102}{}{Ông ta mặc đồng phục quân đội, nhưng rõ ràng người này giống nhân viên kĩ thuật hơn là lính.}
{103}{}{Này, ta đã bảo lũ lính quèn chúng mày bao nhiêu lần rồi? Đừng có lẩn quẩn vướng chân!}
{104}{}{Không còn cái bia nào để bắn à?}
{105}{}{Xin chào, lính dù.}
{106}{}{Mày là ai? Lính gác!}
{107}{}{Cái củ cải gì thế này? Có kẻ đột nhập trong căn cứ!}
{108}{}{Cứt thật! Súng để đâu rồi!}
{109}{}{Này, họ đã đến đây tìm rồi và không phát hiện thấy gì cả.}
{110}{}{Phù, mấy cái báo động giả này làm tôi sợ cứng cả người.}
{111}{}{Hay đấy, lại báo động giả nữa. Giờ thì bọn tôi phải tháo dỡ toàn bộ hệ thống rồi lắp lại
như cũ.}
{112}{}{Mẹ nó chứ! Ở đây! Đến bắt gián điệp đi!}
{113}{}{Cứt thật! Bị tấn công rồi! Đồ của tao đâu?}
{114}{}{Có nổ súng à? Làm đéo có ai nói là sẽ có nổ súng đâu!}
{115}{}{Mày là thằng đéo nào thế? Lính gác đâu!}
{116}{}{Mày không phải người của Enclave! Lính gác!}
{117}{}{Kẻ đột nhập! Đồ phá hoại! Ở đây!}
{118}{}{Này, đừng có làm mọi thứ lộn tùng phèo lên. Tôi đang làm việc.}
{119}{}{Bộ phận hồi chuyển ở chỗ đéo nào thế?}
{120}{}{Mẹ cái lũ ruồi bay, lúc đéo nào cũng làm hỏng máy.}
{121}{}{Đã rõ, chúng tôi đã bắt được tín hiệu trên máy quét -- đừng có làm phiền, tôi đang làm việc.}
{122}{}{Này, không được gọi ai cả, cậu lính.}
{123}{}{Xin lỗi, hiện không giúp được.}
{124}{}{Có việc gì ở đây à? Không thì tránh đường.}
{125}{}{Đây là khu vực hạn chế, đồ lính.}
{126}{}{Tránh đường ra, đồ lính.}
{127}{}{Cái đéo gì thế? Trên đấy đang có chuyện gì thế?}
{128}{}{Cứt thật! Chúng nó vào được rồi!}
{129}{}{Lũ hề này! Chắc là lại báo động giả nữa rồi.}
