{100}{}{Bạn thấy một kĩ thuật viên.}
{101}{}{Bạn thấy một kĩ thuật viên của Enclave.}
{102}{}{Bạn thấy một người mặc áo khoác phòng thí nghiệm. Ông ta trông có vẻ rất tự tin.}
{103}{}{Yes, sir?}
{104}{}{Ngộ mới đây. Cần hỏi.}
{105}{}{Ngộ chỉ chào. Ngộ đi giờ.}
{106}{}{Tôi là người mới ở đây và đang cố làm quen với căn cứ. Tôi có thể hỏi vài câu không?}
{107}{}{Chỉ chào thôi. Gặp lại sau.}
{108}{}{Certainly, soldier.}
{109}{}{Tôi có thể giúp gì đây?}
{110}{}{Đây chỗ nào?}
{111}{}{Việc ông gì?}
{112}{}{Căn cứ chính Enclave chỗ mô?}
{113}{}{Ngộ tìm bản vẽ máy bay trực thăng. Ngộ tìm đâu?}
{117}{}{Ngộ đi giờ.}
{118}{}{Đây là nơi nào?}
{119}{}{Công việc của ông ở đây là gì?}
{120}{}{Căn cứ chính của Enclave nằm ở đâu?}
{121}{}{Tôi cần xem bản vẽ máy bay trực thăng. Chúng để ở đâu thế?}
{125}{}{Không có gì. Tôi phải đi đây.}
{126}{}{This is the comm center. From here we handle all communications with the main base and any other outposts that have been established.}
{127}{}{Ngộ thấy. Ngộ hỏi thêm.}
{128}{}{Được rồi. Hỏi thêm mấy câu nữa.}
{129}{}{I'm a comm center technician, first class. I perform supervisory duties. Mainly I make sure the other techs don't screw up.}
{130}{}{Ừ... vậy à.}
{131}{}{Tốt. Cứ tiếp tục đi.}
{132}{}{Soldier, that information is on a "need to know"-only basis. If you have to ask the question then you don't need to know.}
{133}{}{Okay.}
{134}{}{Come on, it's not like I'm some damn tribal or something. We're in the same outfit; notice the insignia on the armor?}
{135}{}{Tôi hiểu rồi.}
{136}{}{Yes, sir. The main base is located off the Pacific coast near the city of San Francisco. May I inquire why you are asking, sir?}
{137}{}{Soldier, I told you that information is on a "need to know"-only basis.}
{138}{}{For security purposes, I'm checking the level of information awareness among base personnel. Now, tell me all the ways you personally know of to get to main base.}
{139}{}{Tôi hiểu rồi.}
{140}{}{Yes, sir. First, the vertibirds are the primary method used in reaching main base. Due to the complexity of their operation it is doubtful that subversives could commandeer a vertibird. Second, there is an operational fuel tanker in San Francisco harbor. The ship has, however, been disabled and a passkey is required to restart it. The base commander has the passkey in his possession. Third, with the proper equipment, you could conceivably swim to main base but the probability of survival is next to nil.}
{141}{}{Cám ơn.}
{142}{}{Cám ơn.}
{143}{}{They would be located in maintenance, next to air traffic control. }
{144}{}{Okay.}
{145}{}{Hiểu rồi.}
{155}{}{Cậu điên à, đi lại ở đây mà không mặc quân phục? Mặc đồ vào!}
{156}{}{If the sergeant catches you out of uniform he'll hand you your ass.}
{157}{}{Sao cậu lại không mặc quân phục?}
{158}{}{Đm! Chúng ta đang bị xâm nhập! Báo động!}
{159}{}{Có kẻ xâm nhập! Gọi bảo vệ ngay!}
{160}{}{Bảo vệ đâu! Có kẻ xâm nhập trong trung tâm liên lạc!}
{161}{}{Gì thế? Chúng ta bị tấn công à?}
{162}{}{Sao lại báo động? Chuyện gì thế?}
{163}{}{Cái củ lìn gì đang diễn ra thế?}
{164}{}{I'm just a tech, don't shoot me!}
{165}{}{Tôi đâu có đăng kí chiến đấu, chỉ huấn luyện kĩ thuật thôi!}
{166}{}{Đây là áo khoác thí nghiệm chứ có phải giáp đâu! Tôi biến khỏi đây đây!}
