{100}{}{Bạn thấy một kĩ thuật viên.}
{101}{}{Bạn thấy một kĩ thuật viên của Enclave.}
{102}{}{Bạn thấy một người mặc áo khoác phòng thí nghiệm, đeo miếng bảo vệ túi có nhét đầy bút bên trong. Ông ta trông có vẻ hơi bối rối như thể chưa quen với công việc.}
{103}{}{Vâng?}
{104}{}{Ngộ mới đây. Cần hỏi.}
{105}{}{Ngộ chỉ chào. Ngộ đi giờ.}
{106}{}{Tôi mới đến. Tôi cần hỏi vài câu để làm quen với căn cứ.}
{107}{}{Xin lỗi đã làm phiền. Tôi chỉ chào hỏi thôi.}
{108}{}{Tôi cũng là nhân viên mới. Tôi không chắc là mình có thể trả lời toàn bộ các câu hỏi, nhưng tôi sẽ cố.}
{109}{}{Tôi có thể giúp gì đây?}
{110}{}{Đây chỗ nào?}
{111}{}{Việc ông gì?}
{112}{}{Căn cứ chính Enclave chỗ nào.}
{113}{}{Ngộ tìm bản vẽ máy bay trực thăng. Ngộ tìm đâu?}
{117}{}{Ngộ đi giờ.}
{118}{}{Đây là nơi nào?}
{119}{}{Công việc của ông ở đây là gì?}
{120}{}{Căn cứ chính của Enclave nằm ở đâu?}
{121}{}{Tôi cần xem bản vẽ máy bay trực thăng. Chúng để ở đâu thế?}
{125}{}{Không có gì. Tôi phải đi đây.}
{126}{}{Đây là trung tâm liên lạc. Chúng tôi xử lí tất cả nội dung liên lạc với căn cứ từ đây.}
{127}{}{Ngộ thấy. Ngộ hỏi thêm.}
{128}{}{Được rồi. Hỏi thêm mấy câu nữa.}
{129}{}{Tôi là nhân viên kĩ thuật của trung tâm liên lạc, binh nhì. Tôi xử lí tất cả nội dung liên lạc với căn cứ chính và bảo trì tình trạng thiết bị.}
{130}{}{Ừ... vậy à.}
{131}{}{Tốt. Cứ tiếp tục đi.}
{132}{}{Đùa đấy thôi, phải không? }
{133}{}{Không đùa. Căn cứ đâu?}
{134}{}{Trông tôi có giống đang đùa không?}
{135}{}{Căn cứ chính ở ngoài khơi bờ biển Thái Bình Dương gần thành phố San Fransico. Liệu tôi có thể biết là anh hỏi làm gì được không?}
{136}{}{Không. Lí do quân sự. Có bao nhiêu cách để đến căn cứ?}
{137}{}{Không. Đây là bí mật quân sự. Còn giờ, ông biết bao nhiêu cách để đến căn cứ?}
{138}{}{Ồ... có máy bay trực thăng, nhưng cách đấy rõ như ban ngày nhỉ. Rồi còn có cái tàu ở San Fran nữa. Ngoài ra thì tôi chắc là chỉ còn mỗi cách tự bơi thôi.}
{139}{}{Cám ơn.}
{140}{}{Cám ơn.}
{141}{}{Chúng ở trong phòng bảo trì, bên cạnh phòng kiểm soát không lưu.}
{142}{}{Okay.}
{143}{}{Hiểu rồi.}
{153}{}{Cậu điên à, đi lại ở đây mà không mặc quân phục? Mặc đồ vào!}
{154}{}{Nếu trung sĩ mà bắt được không mặc quân phục thì ông ta sẽ dần cho nát đít đấy.}
{155}{}{Sao cậu lại không mặc quân phục?}
{156}{}{Đm! Chúng ta đang bị xâm nhập! Báo động!}
{157}{}{Có kẻ xâm nhập! Gọi bảo vệ ngay!}
{158}{}{Bảo vệ đâu! Có kẻ xâm nhập trong trung tâm liên lạc!}
{159}{}{Gì thế? Chúng ta bị tấn công à?}
{160}{}{Sao lại báo động? Chuyện gì thế?}
{161}{}{Cái củ lìn gì đang diễn ra thế?}
{162}{}{Tôi chỉ là nhân viên kĩ thuật thôi, đừng bắn tôi!}
{163}{}{Tôi đâu có đăng kí chiến đấu, chỉ huấn luyện kĩ thuật thôi!}
{164}{}{Đây là áo khoác thí nghiệm chứ có phải giáp đâu! Tôi biến khỏi đây đây!}
