{100}{}{Chào, người. Ta là chiến binh Xarn. Người là kẻ giết ta?}
{101}{}{Đúng vậy.}
{102}{}{Không, ngộ đây cứu ngươi.}
{103}{}{Không biết. Ngộ muốn biết sao ngươi ở đây.}
{104}{}{Đúng vậy.}
{105}{}{Không, ta đến để cứu ngươi.}
{106}{}{Ta không biết. Ta muốn biết sao ngươi lại ở đây.}
{107}{}{Được rồi. Ta không định ngồi yên chịu chết đâu, người. Hãy chiến đấu
một trận đáng nhớ nào!}
{108}{}{Okay.}
{109}{}{Chờ. Ngộ đổi ý. Sao ngươi ở đây?}
{110}{}{Ta sẵn sàng rồi. Chiến nào.}
{111}{}{Chờ một chút đã. Sao ngươi lại ở đây?}
{112}{}{Ta thấy thật khó tin rằng một lính Enclave lại đến đây để cứu ta. Đúng hơn là,
người mang hi vọng đến để làm chúng tan vỡ.}
{113}{}{Không. Ngộ đây cứu ngươi. Thật.}
{114}{}{Này, ta thật sự đến đây để cứu ngươi!}
{115}{}{Người là hi vọng cuối cùng nên ta sẽ tin người. Cái cửa
đằng kia dẫn vào ống thông gió lên khu rừng ở trên.
Ta có thể trèo qua ống thông để tìm tự do. Tuy nhiên, 
cửa đã bị khóa chặt và cần có chìa để mở.
Hãy tìm chìa, mở khóa cửa và cho ta được tự do.}
{116}{}{Okay, ngộ làm.}
{117}{}{Ngộ nghĩ về chuyện đó.}
{118}{}{Được, ta sẽ làm vậy.}
{119}{}{Ta sẽ nghĩ về việc đó.}
{120}{}{(Xarn nhìn bạn chằm chằm một lúc) Được. Enclave tạo ra
chúng ta làm chiến binh nô lệ. Họ tăng cường trí tuệ cho 
chúng ta với hi vọng chúng ta sẽ hiểu được lệnh, nhưng không
nhận ra tình trạng nô lệ. Họ đã thất bại; chúng ta thông minh
hơn nhiều so với những gì họ nghĩ.}
{121}{}{Chúng ta quyết định giả ngu cho đến khi có thể được tự do.
Cơ hội đã đến khi Enclave quyết định đưa chúng ta ra ngoài
khu kiểm soát để thử nghiệm tại đây trên lục địa. Tiến sĩ Schreber
phản đối quyết định này, nhưng ông ta bị áp quyền.}
{122}{}{Not accepting the Enclave decision, he chose exile to this base,
 captured me, and has been performing experiments to determine my
 true nature. He has been successful. When he reports his findings
 to the Enclave my people will be hunted down and slain. I must
 escape and warn my people.}
{123}{}{(Xarn stares at you intently for a moment) I have nothing
 to tell you, human. I can sense the darkness of your soul.}
{124}{}{If doctor such threat why you no kill?}
{125}{}{Screw you then. Me shoot you ass.}
{126}{}{If this guy is such a threat, then why didn't you just kill him?}
{127}{}{Up yours, then. Die, deathclaw.}
{128}{}{(sigh) Recently I began to consider just such an action,
 even though it is not my way to kill. I am certain the doctor
 noticed because he stopped seeing me in person. The choice is
 no longer mine to make.}
{129}{}{You not worry. Doctor dead. He not make report.}
{130}{}{Me thank you for story.}
{131}{}{You don't have to worry. The doc is dead and he
 didn't make the report.}
{132}{}{Thanks for the story. It was interesting.}
{133}{}{I am sorry to hear of his death but it is for the
 better that this is so. I would ask you to help me escape
 this place. Will you?}
{134}{}{Yes, me do.}
{135}{}{Ngộ nghĩ về chuyện đó.}
{136}{}{No, me no think so.}
{137}{}{Yeah, I'll do it.}
{138}{}{No, but I'll think about it.}
{139}{}{No, I don't think so.}
{140}{}{Very well... I will wait here until you come to a decision.}
{141}{}{Đã xong.}
{142}{}{Very well... I am saddened by your decision but it is
 your choice. If you change your mind, I will be here.}
{143}{}{Chào.}
{144}{}{Tạm biệt.}
{145}{}{I would ask you to help me escape this place. Will you?}
{146}{}{Yes, me do.}
{147}{}{Ngộ nghĩ về chuyện đó.}
{148}{}{No, me no think so.}
{149}{}{Yeah, I'll do it.}
{150}{}{No, but I'll think about it.}
{151}{}{No, I don't think so.}
{152}{}{Hello again. Are you ready for our battle?}
{153}{}{No want fight, want hear you story.}
{154}{}{Me not want fight. Me here rescue you.}
{155}{}{No. Me go.}
{156}{}{Có. Ngộ sẵn sàng.}
{157}{}{I don't really want to fight. Can I hear your story instead?}
{158}{}{I'm here to rescue you, not fight.}
{159}{}{No. I'll be leaving now.}
{160}{}{All right, let's get it over with.}
{161}{}{Hello again. Have you changed your mind? Will you help me?}
{162}{}{Đúng vậy.}
{163}{}{Không.}
{164}{}{Hello again. Have you changed your mind? Will you help me?}
{165}{}{Đúng vậy.}
{166}{}{No. Me still think about it.}
{167}{}{No. Me not help.}
{168}{}{No, I'm still thinking.}
{169}{}{I don't want to help you.}
{170}{}{Hello again. Have you found the key to the door?}
{171}{}{Yes, me open for you.}
{172}{}{Ngộ vẫn tìm.}
{173}{}{Yeah, I've got it. I'll open the door for you.}
{174}{}{Tôi vẫn đang tìm.}
{175}{}{Thank you. I will not forget this.}
{176}{}{Không gì.}
{177}{}{You are welcome.}
{178}{}{Thank you again, my friend. I owe you a debt that can not be repaid.}
{179}{}{Greetings, human. The base is on full alert. Are you by any chance the cause?}
{180}{}{Hello again. The base is on full alert. Are you the cause?}
{181}{}{Yes, me cause. Who you, why you want know?}
{182}{}{Yes, me cause. Why?}
{183}{}{I am Xarn, pack warrior. Allow me to join you and fight at your side for our freedom. Together we stand a chance; alone... who knows?}
{184}{}{Then allow me to join you and fight at your side. Together
 we may be able to gain our freedom; alone... who knows?}
{185}{}{Before me decide you tell why you here?}
{186}{}{Uh... okay. You come me. We fight way out together.}
{187}{}{You on you own. Me out of here.}
{188}{}{Before I come to any decision I'd like to know why you're here?}
{189}{}{Fine. We're in this together. Load up your claws and let's party down!}
{190}{}{You're on your own pal. I'm out of here.}
{191}{}{Uh... okay. You come me. We fight way out together.}
{192}{}{You on you own. Me out of here.}
{193}{}{Fine. We're in this together. Load up your claws and let's party down!}
{194}{}{You're on your own pal. I'm out of here.}
{195}{}{I thank you, human. Let us kick some Enclave ass! Pack Gruthar! Grrrrrrrhh!}
{196}{}{Okay.}
{200}{}{[THÊM]}
{201}{}{Yes. Who are you?}
{202}{}{Yes. Why?}
{300}{}{Very well. The Enclave created my people as a slave warrior race.
 They enhanced our intellect hoping we could better understand their
 commands, and yet not recognize our status as slaves. They failed; we are
 much more intelligent than they suspect.}
{301}{}{We decided to play the fool until we could gain our freedom. Our
 chance arrived when the Enclave decided to test us outside their control, here
 on the mainland. Doctor Schreber opposed their decision, but he was overruled.}
{302}{}{Not accepting the Enclave decision, he chose exile to this base, captured
 me, and has been performing experiments to determine my true nature. He has
 been successful. When he reports his findings to the Enclave my people will be
 hunted down and slain. I must escape and warn my people.}
{500}{}{You are a true Pack brother. May we meet again in more peaceful times.
 I must go now to prepare my people for war.}
{501}{}{I am going to tear off your limbs and beat you with them.}
{502}{}{Die, treacherous human!}
{503}{}{This will hurt you a lot more than it does me.}
{600}{}{Together we will crush our enemies.}
{601}{}{You line 'em up and I'll knock 'em down.}
{602}{}{Time for some serious head bashing.}
{700}{}{You see a deathclaw. It watches you with strangely intelligent eyes.}
{701}{}{You see Xarn, the Deathclaw.}
{702}{}{You see a typical deathclaw. The creature is huge, with a powerful body, sharp teeth, and long claws.}
{800}{}{You killed Xarn.}
{810}{}{You freed Xarn.}
{820}{}{You joined Xarn.}
{900}{}{No. Me here rescue you. Really. Me already open door for leave. You go.}
{901}{}{Look, I really am here to rescue you! I already unlocked the other door. You are free to leave.}
