{100}{}{Bạn thấy chiếc thùng gỗ.}
{101}{}{Bạn thấy tủ khóa thép.}
{102}{}{Bạn thấy một chiếc thùng chắc chắn có khóa (có thể dùng 
cậy khóa để mở) và bẫy thuốc nổ nhạy trên khung, mà bạn 
có thể thử cậy mở.}
{103}{}{Bạn thấy một thùng chứa chắc chắn có khóa 
và bẫy thuốc nổ nhạy trên khung mà bạn
có thể thử cậy mở.}
{104}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có khóa
nhưng có bẫy thuốc nổ nhạy trên khung mà bạn có thể thử
cậy mở.}
{105}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ rét và
bẫy thuốc nổ nhạy trên khung mà bạn có thể thử
cậy mở.}
{106}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng
cậy khóa để mở) và bẫy trên khung, mà bạn có thể thử
cậy mở.}
{107}{}{Bạn thấy một thùng chứa chắc chắn có khóa và bẫy trên
khung mà bạn có thể thử cậy mở.}
{108}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có
khóa nhưng có bẫy trên khung mà bạn có thể thử cậy mở.}
{109}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét
và bẫy trên khung mà bạn có thể thử cậy mở.}
{110}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) và đoạn dây thép bị cắt trên khung mà bạn có thể thử
cậy mở.}
{111}{}{Bạn thấy một thùng chứa chắc chắn có khóa và một đoạn dây thép
bị đứt trên khung mà bạn có thể thử cậy mở.}
{112}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có khóa
nhưng có đoạn dây thép bị đứt trên khung mà bạn có thể thử
cậy mở.}
{113}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét và
đoạn dây thép bị đứt trên khung mà bạn có thể thử cậy mở.}
{114}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) mà bạn có thể thử cậy mở.}
{115}{}{Bạn thấy một thùng chứa chắc chắn có khóa mà bạn có thể
thử cậy mở.}
{116}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không
có khóa mà bạn có thể thử cậy mở.}
{117}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét
mà bạn có thể thử cậy mở.}
{118}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) và bẫy thuốc nổ nhạy trên khung.}
{119}{}{Bạn thấy một thùng chứa chắc chắn có khóa và bẫy
thuốc nổ nhạy trên khung.}
{120}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có khóa
nhưng có bẫy thuốc nổ nhạy trên khung.}
{121}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét
và bẫy thuốc nổ nhạy trên khung.}
{122}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) và bẫy trên khung.}
{123}{}{Bạn thấy một thùng chứa chắc chắn có khóa và bẫy trên
khung.}
{124}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có khóa
nhưng có bẫy trên khung.}
{125}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét
và bẫy trên khung.}
{126}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) và đoạn dây thép bị đứt trên khung.}
{127}{}{Bạn thấy một thùng chứa chắc chắn có khóa và đoạn dây thép
bị đứt trên khung.}
{128}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có khóa
nhưng có đoạn dây thép bị đứt trên khung.}
{129}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét
và đoạn dây thép bị cắt trên khung.}
{130}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) bên trên.}
{131}{}{Bạn thấy một thùng chứa chắc chắn có khóa.}
{132}{}{Bạn thấy một thùng chứa chắc chắn, nhìn có vẻ như không có khóa.}
{133}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét.}
{134}{}{Bạn thấy một thùng chứa cũ nát có khóa (có thể dùng cậy khóa để 
mở) và bẫy thuốc nổ nhạy trên khung.}
{135}{}{Bạn tháy một thùng chứa cũ nát có khóa và bẫy thuốc nổ
nhạy trên khung.}
{136}{}{Bạn thấy một thùng chứa cũ nát. Nhìn có vẻ như không có khóa nhưng
có bẫy thuốc nổ nhạy trên khung.}
{137}{}{Bạn thấy một thùng chứa cũ nát với ổ khóa cũ kĩ, rỉ sét và bẫy
thuốc nổ nhạy trên khung.}
{138}{}{Bạn thấy một thùng chứa cũ nát có khóa (có thể dùng cậy khóa để
mở) và bẫy trên khung.}
{139}{}{Bạn thấy một thùng chứa cũ nát có khóa và bẫy
trên khung.}
{140}{}{Bạn thấy một thùng chứa cũ nát, nhìn có vẻ như không có khóa
nhưng có bẫy trên khung.}
{141}{}{Bạn thấy một thùng chứa cũ nát với ổ khóa cũ kĩ, rỉ sét và bẫy
trên khung.}
{142}{}{Bạn thấy một thùng chứa cũ nát có khóa (có thể dùng cậy khóa để mở)
và đoạn dây thép bị cắt trên khung.}
{143}{}{Bạn thấy một thùng chứa cũ nát có khóa và đoạn dây thép bị đứt
trên khung.}
{144}{}{Bạn thấy một thùng chứa cũ nát, nhìn có vẻ như không có khóa
nhưng có đoạn dây thép bị đứt trên khung.}
{145}{}{Bạn thấy một thùng chứa cũ nát với ổ khóa cũ kĩ, rỉ sét và đoạn
dây thép bị đứt trên khung.}
{146}{}{Bạn thấy một thùng chứa cũ nát có khóa (có thể dùng cậy khóa
để mở).}
{147}{}{Bạn thấy một thùng chứa cũ nát có khóa.}
{148}{}{Bạn thấy một thùng chứa cũ nát, nhìn có vẻ như không có khóa.}
{149}{}{Bạn thấy một thùng chứa cũ nát với ổ khóa cũ kĩ, rỉ sét.}
{150}{}{Bạn thấy một thùng chứa đã cũ có khóa (có thể dùng cậy khóa để
mở) và bẫy thuốc nổ nhạy trên khung.}
{151}{}{Bạn thấy một thùng chứa đã cũ có khóa và bẫy thuốc nổ
nhạy trên khung.}
{152}{}{Bạn thấy một thùng chứa đã cũ, nhìn có vẻ như không có khóa
nhưng có bẫy thuốc nổ nhạy trên khung.}
{153}{}{Bạn thấy một thùng chứa đã cũ với ổ khóa cũ kĩ, rỉ sét và bẫy
thuốc nổ nhạy trên khung.}
{154}{}{Bạn thấy một thùng chứa đã cũ có khóa (có thể dùng cậy khóa
để mở) và bẫy trên khung.}
{155}{}{Bạn thấy một thùng chứa đã cũ có khóa và bẫy trên
khung.}
{156}{}{Bạn thấy một thùng chứa đã cũ, nhìn có vẻ như không có khóa
nhưng có bẫy trên khung.}
{157}{}{Bạn thấy một thùng chứa đã cũ với ổ khóa cũ kĩ, rỉ sét và
bẫy trên khung.}
{158}{}{Bạn thấy một thùng chứa đã cũ có khóa (có thể dùng cậy khóa
để mở) và đoạn dây thép bị cắt trên khung.}
{159}{}{Bạn thấy một thùng chứa đã cũ có khóa và đoạn dây thép
bị đứt trên khung.}
{160}{}{Bạn thấy một thùng chứa đã cũ, nhìn có vẻ như không có khóa
nhưng có đoạn dây thép bị đứt trên khung.}
{161}{}{Bạn thấy một thùng chứa đã cũ với ổ khóa cũ kĩ, rỉ sét và đoạn
dây thép bị cắt trên khung.}
{162}{}{Bạn thấy một thùng chứa đã cũ có khóa (có thể dùng cậy khóa
để mở).}
{163}{}{Bạn thấy một thùng chứa đã cũ có khóa.}
{164}{}{Bạn thấy một thùng chứa đã cũ, nhìn có vẻ như không có khóa.}
{165}{}{Bạn thấy một thùng chứa đã cũ với ổ khóa cũ kĩ, rỉ sét.}
{166}{}{Bạn bị dính bẫy và đã nhận }
{167}{}{ điểm sát thương.}
{168}{}{ đã dính bẫy và nhận }
{169}{}{ điểm sát thương.}
{170}{}{Bạn khéo léo cậy khóa trên thùng chứa.}
{171}{}{Kĩ năng kém cỏi của bạn đã làm kẹt khóa trên thùng chứa.}
{172}{}{Bạn không cậy được khóa trên thùng chứa này.}
{173}{}{ khéo léo cậy khóa trên thùng chứa.}
{174}{}{'s lack of skill has jammed the lock on this container.}
{175}{}{ failed to pick the lock on this container.}
{176}{}{You bust the lock off the container.}
{177}{}{Bạn bị căng cơ lưng khi cố gắng phá khóa và
nhận một điểm sát thương.}
{178}{}{Bạn bị căng cơ lưng khi cố gắng phá khóa và
nhận }
{179}{}{ điểm sát thương.}
{180}{}{Bạn quá yếu để có thể phá khóa.}
{181}{}{ busts the lock off the container.}
{182}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận một
 điểm sát thương.}
{183}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận }
{184}{}{ điểm sát thương.}
{185}{}{ quá yếu để có thể phá khóa.}
{186}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận một
 điểm sát thương.}
{187}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận}
{188}{}{ điểm sát thương.}
{189}{}{You deftly lock the container.}
{190}{}{You fail to lock the container.}
{191}{}{ deftly locks the container.}
{192}{}{ failed to lock the container.}
{193}{}{The explosives don't even put a scratch on the container.}
{194}{}{You find a trap on the container.}
{195}{}{You fail to find any traps on the container.}
{196}{}{Bạn khéo léo vô hiệu hóa bẫy.}
{198}{}{Bạn không vô hiệu hóa được bẫy.}
{199}{}{ finds a trap on the container.}
{200}{}{ fails to find any traps on the container.}
{201}{}{ khéo léo vô hiệu hóa bẫy.}
{202}{}{ không vô hiệu hóa được bẫy.}
{203}{}{The container appears to be locked.}
{204}{}{You notice a trap on the container.}
{205}{}{ notices a trap on the container jamb.}
{206}{}{You are unable to place a trap on this container, because
 the container is open.}
{207}{}{ is unable to place a trap on this container, because the
 container is open.}
{208}{}{You skillfully set a trap in the container.}
{209}{}{You fail to properly set the trap in the container.}
{210}{}{ skillfully sets a trap on the container.}
{211}{}{ fails to properly set the trap in the container.}
{212}{}{You see a refrigerator.}
{400}{}{You unlock the container.}
{601}{}{It is open, dummy.}
{610}{}{You fail spectacularly, and the explosive goes off prematurely.}
{611}{}{ fails spectacularly, and the explosive goes off prematurely.}
{620}{}{You bend the crowbar beyond recognition. It's useless now.}
{621}{}{ bends the crowbar beyond recognition. It's useless now.}
