{100}{}{Bạn thấy chiếc thùng gỗ.}
{101}{}{Bạn thấy tủ khóa thép.}
{102}{}{Bạn thấy một chiếc thùng chắc chắn có khóa (có thể dùng 
cậy khóa để mở) và bẫy thuốc nổ nhạy trên khung, mà bạn 
có thể thử cậy mở.}
{103}{}{Bạn thấy một thùng chứa chắc chắn có khóa 
và bẫy thuốc nổ nhạy trên khung mà bạn
có thể thử cậy mở.}
{104}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có khóa
nhưng có bẫy thuốc nổ nhạy trên khung mà bạn có thể thử
cậy mở.}
{105}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ rét và
bẫy thuốc nổ nhạy trên khung mà bạn có thể thử
cậy mở.}
{106}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng
cậy khóa để mở) và bẫy trên khung, mà bạn có thể thử
cậy mở.}
{107}{}{Bạn thấy một thùng chứa chắc chắn có khóa và bẫy trên
khung mà bạn có thể thử cậy mở.}
{108}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có
khóa nhưng có bẫy trên khung mà bạn có thể thử cậy mở.}
{109}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét
và bẫy trên khung mà bạn có thể thử cậy mở.}
{110}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) và đoạn dây thép bị cắt trên khung mà bạn có thể thử
cậy mở.}
{111}{}{Bạn thấy một thùng chứa chắc chắn có khóa và một đoạn dây thép
bị đứt trên khung mà bạn có thể thử cậy mở.}
{112}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có khóa
nhưng có đoạn dây thép bị đứt trên khung mà bạn có thể thử
cậy mở.}
{113}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét và
đoạn dây thép bị đứt trên khung mà bạn có thể thử cậy mở.}
{114}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) mà bạn có thể thử cậy mở.}
{115}{}{Bạn thấy một thùng chứa chắc chắn có khóa mà bạn có thể
thử cậy mở.}
{116}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không
có khóa mà bạn có thể thử cậy mở.}
{117}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét
mà bạn có thể thử cậy mở.}
{118}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) và bẫy thuốc nổ nhạy trên khung.}
{119}{}{Bạn thấy một thùng chứa chắc chắn có khóa và bẫy
thuốc nổ nhạy trên khung.}
{120}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có khóa
nhưng có bẫy thuốc nổ nhạy trên khung.}
{121}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét
và bẫy thuốc nổ nhạy trên khung.}
{122}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) và bẫy trên khung.}
{123}{}{Bạn thấy một thùng chứa chắc chắn có khóa và bẫy trên
khung.}
{124}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có khóa
nhưng có bẫy trên khung.}
{125}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét
và bẫy trên khung.}
{126}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) và đoạn dây thép bị đứt trên khung.}
{127}{}{Bạn thấy một thùng chứa chắc chắn có khóa và đoạn dây thép
bị đứt trên khung.}
{128}{}{Bạn thấy một thùng chứa chắc chắn. Nhìn có vẻ như không có khóa
nhưng có đoạn dây thép bị đứt trên khung.}
{129}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét
và đoạn dây thép bị cắt trên khung.}
{130}{}{Bạn thấy một thùng chứa chắc chắn có khóa (có thể dùng cậy khóa
để mở) bên trên.}
{131}{}{Bạn thấy một thùng chứa chắc chắn có khóa.}
{132}{}{Bạn thấy một thùng chứa chắc chắn, nhìn có vẻ như không có khóa.}
{133}{}{Bạn thấy một thùng chứa chắc chắn với ổ khóa cũ kĩ, rỉ sét.}
{134}{}{Bạn thấy một thùng chứa cũ nát có khóa (có thể dùng cậy khóa để 
mở) và bẫy thuốc nổ nhạy trên khung.}
{135}{}{Bạn tháy một thùng chứa cũ nát có khóa và bẫy thuốc nổ
nhạy trên khung.}
{136}{}{Bạn thấy một thùng chứa cũ nát. Nhìn có vẻ như không có khóa nhưng
có bẫy thuốc nổ nhạy trên khung.}
{137}{}{Bạn thấy một thùng chứa cũ nát với ổ khóa cũ kĩ, rỉ sét và bẫy
thuốc nổ nhạy trên khung.}
{138}{}{Bạn thấy một thùng chứa cũ nát có khóa (có thể dùng cậy khóa để
mở) và bẫy trên khung.}
{139}{}{Bạn thấy một thùng chứa cũ nát có khóa và bẫy
trên khung.}
{140}{}{Bạn thấy một thùng chứa cũ nát, nhìn có vẻ như không có khóa
nhưng có bẫy trên khung.}
{141}{}{Bạn thấy một thùng chứa cũ nát với ổ khóa cũ kĩ, rỉ sét và bẫy
trên khung.}
{142}{}{Bạn thấy một thùng chứa cũ nát có khóa (có thể dùng cậy khóa để mở)
và đoạn dây thép bị cắt trên khung.}
{143}{}{Bạn thấy một thùng chứa cũ nát có khóa và đoạn dây thép bị đứt
trên khung.}
{144}{}{Bạn thấy một thùng chứa cũ nát, nhìn có vẻ như không có khóa
nhưng có đoạn dây thép bị đứt trên khung.}
{145}{}{Bạn thấy một thùng chứa cũ nát với ổ khóa cũ kĩ, rỉ sét và đoạn
dây thép bị đứt trên khung.}
{146}{}{Bạn thấy một thùng chứa cũ nát có khóa (có thể dùng cậy khóa
để mở).}
{147}{}{Bạn thấy một thùng chứa cũ nát có khóa.}
{148}{}{Bạn thấy một thùng chứa cũ nát, nhìn có vẻ như không có khóa.}
{149}{}{Bạn thấy một thùng chứa cũ nát với ổ khóa cũ kĩ, rỉ sét.}
{150}{}{Bạn thấy một thùng chứa đã cũ có khóa (có thể dùng cậy khóa để
mở) và bẫy thuốc nổ nhạy trên khung.}
{151}{}{Bạn thấy một thùng chứa đã cũ có khóa và bẫy thuốc nổ
nhạy trên khung.}
{152}{}{Bạn thấy một thùng chứa đã cũ, nhìn có vẻ như không có khóa
nhưng có bẫy thuốc nổ nhạy trên khung.}
{153}{}{Bạn thấy một thùng chứa đã cũ với ổ khóa cũ kĩ, rỉ sét và bẫy
thuốc nổ nhạy trên khung.}
{154}{}{Bạn thấy một thùng chứa đã cũ có khóa (có thể dùng cậy khóa
để mở) và bẫy trên khung.}
{155}{}{Bạn thấy một thùng chứa đã cũ có khóa và bẫy trên
khung.}
{156}{}{Bạn thấy một thùng chứa đã cũ, nhìn có vẻ như không có khóa
nhưng có bẫy trên khung.}
{157}{}{Bạn thấy một thùng chứa đã cũ với ổ khóa cũ kĩ, rỉ sét và
bẫy trên khung.}
{158}{}{Bạn thấy một thùng chứa đã cũ có khóa (có thể dùng cậy khóa
để mở) và đoạn dây thép bị cắt trên khung.}
{159}{}{Bạn thấy một thùng chứa đã cũ có khóa và đoạn dây thép
bị đứt trên khung.}
{160}{}{Bạn thấy một thùng chứa đã cũ, nhìn có vẻ như không có khóa
nhưng có đoạn dây thép bị đứt trên khung.}
{161}{}{Bạn thấy một thùng chứa đã cũ với ổ khóa cũ kĩ, rỉ sét và đoạn
dây thép bị cắt trên khung.}
{162}{}{Bạn thấy một thùng chứa đã cũ có khóa (có thể dùng cậy khóa
để mở).}
{163}{}{Bạn thấy một thùng chứa đã cũ có khóa.}
{164}{}{Bạn thấy một thùng chứa đã cũ, nhìn có vẻ như không có khóa.}
{165}{}{Bạn thấy một thùng chứa đã cũ với ổ khóa cũ kĩ, rỉ sét.}
{166}{}{Bạn bị dính bẫy và đã nhận }
{167}{}{ điểm sát thương.}
{168}{}{ đã dính bẫy và nhận }
{169}{}{ điểm sát thương.}
{170}{}{Bạn khéo léo cậy khóa trên thùng chứa.}
{171}{}{Kĩ năng kém cỏi của bạn đã làm kẹt khóa trên thùng chứa.}
{172}{}{Bạn không cậy được khóa trên thùng chứa này.}
{173}{}{ khéo léo cậy khóa trên thùng chứa.}
{174}{}{do thiếu kĩ năng đã làm kẹt khóa trên thùng chứa này.}
{175}{}{ đã không cậy được khóa trên thùng chứa này.}
{176}{}{Bạn đã phá khóa khỏi thùng chứa.}
{177}{}{Bạn bị căng cơ lưng khi cố gắng phá khóa và
nhận một điểm sát thương.}
{178}{}{Bạn bị căng cơ lưng khi cố gắng phá khóa và
nhận }
{179}{}{ điểm sát thương.}
{180}{}{Bạn quá yếu để có thể phá khóa.}
{181}{}{ đã phá khóa khỏi thùng chứa.}
{182}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận một
 điểm sát thương.}
{183}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận }
{184}{}{ điểm sát thương.}
{185}{}{ quá yếu để có thể phá khóa.}
{186}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận một
 điểm sát thương.}
{187}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận}
{188}{}{ điểm sát thương.}
{189}{}{Bạn khéo léo khóa thùng chứa.}
{190}{}{Bạn không khóa được thùng chứa.}
{191}{}{ khéo léo khóa thùng chứa.}
{192}{}{ đã không khóa được thùng chứa.}
{193}{}{Thuốc nổ thậm chí còn chẳng làm xước nổi thùng chứa.}
{194}{}{Bạn tìm thấy bẫy trên thùng chứa.}
{195}{}{Bạn không tìm thấy cái bẫy nào trên thùng chứa.}
{196}{}{Bạn khéo léo vô hiệu hóa bẫy.}
{198}{}{Bạn không vô hiệu hóa được bẫy.}
{199}{}{ tìm thấy bẫy trên thùng chứa.}
{200}{}{ không tìm thấy cái bẫy nào trên thùng chứa.}
{201}{}{ khéo léo vô hiệu hóa bẫy.}
{202}{}{ không vô hiệu hóa được bẫy.}
{203}{}{Thùng chứa có vẻ như đã bị khóa.}
{204}{}{Bạn nhận thấy có bẫy trên thùng chứa.}
{205}{}{ nhận thấy có bẫy trên khung thùng chứa.}
{206}{}{Bạn không đặt được bẫy trên thùng chứa, vì thùng chứa
đang mở.}
{207}{}{ không đặt được bẫy trên thùng chứa, vì thùng chứa
đang mở.}
{208}{}{Bạn khéo léo đặt bẫy trên thùng chứa.}
{209}{}{Bạn không đặt được bẫy đúng cách trên thùng chứa.}
{210}{}{ khéo léo đặt bẫy trên thùng chứa.}
{211}{}{ không đặt được bẫy đúng cách trên thùng chứa.}
{212}{}{Bạn thấy một cái tủ lạnh.}
{400}{}{Bạn mở khóa thùng chứa.}
{601}{}{Đang mở rồi, đồ ngốc.}
{610}{}{Bạn thất bại thảm hại và thuốc nổ phát nổ sớm.}
{611}{}{ thất bại thảm hại và thuốc nổ phát nổ sớm.}
{620}{}{Bạn bẻ cong cây xà beng đến mức không sửa nổi nữa. Vứt đi thôi.}
{621}{}{ bẻ cong cây xà beng đến mức không sửa nổi nữa. Vứt đi thôi.}
{800}{}{Bạn đã lấy được chìa khóa.}
{810}{}{Bạn đã nhận được bản vẽ.}
{820}{}{Bạn đã nhận được động cơ của K-9.}
