{100}{}{Bạn thấy một con nghiện.}
{101}{}{Người này nghiện nặng.}
{102}{}{Trông hắn ta phê lắm rồi.}
{103}{}{Trông mụ ta phê lắm rồi.}
{104}{}{Trông ông ta nát lắm rồi. Bạn đoán là do bị đói loại thuốc nào đó.}
{105}{}{Mụ này nhàu lắm rồi. Có vẻ như đang trải qua cơn vã thuốc.}
{106}{}{Con nghiện này trông y như xác chết.}
{107}{}{Bạn chắc rằng con nghiện này chỉ vừa mới nôn.}
{150}{}{Sáng đéo gì chói thế!}
{151}{}{Quỷ ở khắp nơi!}
{152}{}{Lạ thật đấy.}
{153}{}{Tôi đang chảy máu à?}
{154}{}{Bình thường có thật đến thế này đâu nhỉ.}
{155}{}{Dừng lại đi!}
{156}{}{Không ai giúp tôi ư?}
{157}{}{Cứu với!}
{158}{}{Biến đi!}
{159}{}{Đầu tao đau thế là đủ lắm rồi!}
{160}{}{Để tôi yên.}
{200}{}{Ồ, ngươi có ánh sáng đen lạ thế.}
{201}{}{Ồ, ngươi to lớn thật đấy.}
{202}{}{Đừng nói với chúng là những gì bọn ta biết không ở đó.}
{203}{}{À à...}
{204}{}{Thấy ta không?}
{205}{}{Yên, uyên lặng lào. Tao đang săn trỏ.}
{206}{}{Làm sao mà mày bay được lên đó thế?}
{207}{}{Suỵt, ta đang trốn.}
{208}{}{Tao chạy còn nhanh hơn cả sói!}
{209}{}{Mình khỏe vãi lìn!}
{210}{}{Ngấm vào từng mạch máu...}
{211}{}{Đúng chỗ rồi, cưng ơi.}
{212}{}{Ồ ồ ồ, có cảm thấy sức mạnh không?}
{213}{}{Ồ, ngươi đang tỏa sáng...}
{214}{}{Bạn tôi ơi, yêu thế không biết!}
{215}{}{Cuộc sống thật là tươi đẹp. Bạn có thấy thế không?}
{216}{}{Đám tiểu yêu đến tối mới bay.}
{217}{}{Chào cậu bạn bé nhỏ của tôi đi.}
{218}{}{Chà, buồn ngủ thế...}
{219}{}{Có ai thấy chó của tôi không?}
{220}{}{Suỵt, chúng ở ngay sau lưng kìa...}
{221}{}{Của ta!}
{222}{}{Ồ ôi, cái đầu tôi.}
{223}{}{Đau hết cả mình.}
{224}{}{Bắt đầu thấy rung rồi đấy.}
{225}{}{Ồ, vẫn chưa đủ đô.}
{226}{}{Cần một liều.}
{227}{}{Đéo chờ được nữa, bố cần ngay.}
{228}{}{Mày lấy đồ của tao à?}
{229}{}{A, để ta yên.}
{230}{}{Ặc, rung kinh thật.}
{231}{}{Ta ghét phần này.}
{232}{}{Tôi chỉ muốn chết thôi.}
{233}{}{Ta cần đồ nặng hơn.}
{234}{}{Không chịu nổi thêm nữa.}
{235}{}{Tôi nghĩ là tôi bị sốt rồi.}
{236}{}{Tôi e là mình sắp nôn rồi.}
{237}{}{Có lẽ nếu mình nhắm mắt lại...}
{238}{}{Cô ơi, tôi đang lắc dữ lắm.}
{300}{}{Phải máu không?}
{301}{}{Whoa! Am I bleeding? I can't feel a thing!}
{302}{}{It tingles.}
{303}{}{Who did that?}
{304}{}{What's going on?}
{305}{}{I'm bleeding... I think.}
{306}{}{Oh, the pain.}
{307}{}{Now I really need a fix.}
{308}{}{Just let me die.}
{350}{}{Ahhhh...}
{351}{}{I'm floating...}
{352}{}{I have the power!}
{353}{}{Hello, Mr. Flower.}
{354}{}{All the colors...}
{355}{}{More longer friend see that sky?}
{356}{}{They aren't listening...}
{357}{}{Where am I?}
{358}{}{There it is!}
{359}{}{Whoa, no! Stop! Wait! Okay, go ahead.}
{360}{}{There, there... ahh...}
{361}{}{Yea, baby!}
{362}{}{What was that?}
{363}{}{Sasha? Where are you Sasha?}
{364}{}{The colors are fading!}
{365}{}{Mom?}
{366}{}{Hey! Get away from me! Oh...}
{367}{}{Don't you do that!}
{368}{}{I can't see... again.}
{369}{}{Need...}
{370}{}{Get more...}
{371}{}{There? No.}
{372}{}{No. Can't find it.}
{373}{}{Make it stop!}
{374}{}{Ug.}
{375}{}{Oh, the pain.}
{376}{}{<cough> <cough> <cough>}
{377}{}{Ooh, my head!}
{378}{}{Where'd I put my stash?}
{400}{}{A demon!}
{401}{}{The enemy is upon us!}
{402}{}{You murderer! You killed my son!}
{403}{}{A monster! Kill it!}
{404}{}{Ah! Pargasraka!}
{405}{}{Feet fom chin rat going! Ahhh!}
{406}{}{You won't take it from me!}
{407}{}{Give it back!}
{408}{}{No!!!}
{409}{}{My family!}
