{100}{}{Bạn thấy một người đàn ông thấp lùn với bộ râu rậm.}
{101}{}{Bạn thấy Montania vĩ đại.}
{102}{}{Bạn thấy một người đàn ông thấp lùn để râu ria với bộ dạng lén lút.}
{103}{}{Ngươi! Ngươi muốn làm gì với Ananias vốn từng vĩ đại đây?}
{104}{}{Tránh xa ta ra!}
{105}{}{Đi phá chỗ khác đi.}
{106}{}{Đi chỗ khác mà đái.}
{107}{}{Ngươi đã khiến ta mất tất cả rồi.}
{108}{}{Hãy cút đi, ngươi phá thế là đủ lắm rồi.}
{109}{}{Tôi đói quá.}
{110}{}{Làm thế nào nuôi sống được gia đình giờ?}
{111}{}{Ngươi sinh ra với trái tim nhỏ hơn 12 cỡ.}
{112}{}{Không phải, bạn tôi ơi, một XÁC ƯỚP! Được đưa trực tiếp từ cát vùng Ai Cập cổ đại đến cát vùng Hoang mạc! Chỉ có mình ngươi được thấy!}
{113}{}{Rồi, cắn câu rồi đây. Thế nghía cái xác chết khô hết bao xèng?}
{114}{}{(tự lẩm nhẩm) Hừm, xác ướp cũng khá giống với ghoul. OK, tôi sẽ xem -- bao nhiêu?}
{115}{}{Tôi đã thấy đủ xác chết rồi. Chào.}
{116}{}{Xin chào, chào mừng! Ta là Montania vĩ đại (ông ta khẽ cúi chào với động tác khoa trương). Ta mang đến điều bí ẩn từ mọi chốn xa xôi, bạn à. Những điều bí ẩn từ thế giới vượt ra khỏi thế giới của chúng ta... thế giới Bên kia.}
{117}{}{Quay lại để tìm hiểu những điều bí ẩn của Montania vĩ đại về thế giới Bên kia à?}
{118}{}{Bí ẩn nào thế?}
{119}{}{Ờ, rất vui được gặp ngài Mông to... gì đấy.}
{120}{}{Hừm, bí ẩn làm tôi mất ngủ. Tôi nên đi thì hơn. Chào.}
{121}{}{Tiến lên đi!}
{127}{}{Hôm nay, trong căn phòng này, ta có thứ này, chỉ mình bạn được thấy... Xác ướp Ai Cập Jan-ướp-rượu!}
{128}{}{Xác ướp à?}
{129}{}{Xác ướp à? Hừm, không biết có phải... Không, làm gì có ai ngốc đến thế.}
{130}{}{Tôi không quan tâm đến mấy thứ đó. Xác chết kinh bỏ xừ.}
{131}{}{Tránh đường, ngươi đang cản lối khách trả tiền đấy.}
{132}{}{Ta không nghĩ thứ này hợp với ngươi.}
{133}{}{Sao ngươi không lê cái thân toọc đi chỗ khác đi.}
{134}{}{Thứ này không hợp với ngươi.}
{135}{}{Hiểu rồi. Hừm, vậy thì BIẾN (ông ta chỉ tay) ĐI!}
{136}{}{Đối với một nhân vật sành sỏi như bạn, ta rất vui được trưng bày mẫu vật đặc biệt và cổ đại này chỉ với giá 25$.}
{137}{}{OK, tôi sẽ nôn tiền ra. Giờ thì... Cho xem Xác ướp nào!}
{138}{}{Tôi không muốn tiêu phí tiền. Tôi chắc là mình không cần nhìn thứ đó. Chào.}
{139}{}{Chỉ cần mở nắp quan tài và Xác ướp kì diệu sẽ lộ diện, với tất cả vẻ đẹp cổ xưa trước mắt quý khách. Nhưng vui lòng không sờ, và, ờ, không chụp ảnh có đèn nháy.}
{140}{}{Tuyệt.}
{141}{}{Mời quý khách xem! XÁC ƯỚP đến đây! (Nắp quan tài mở ra và bạn thấy một cái xác khô kiệt, trông rất giống một người ghoul bình thường, đứng trong một chiếc quan tài bằng giấy bồi được bôi sơn cẩu thả, thủng lỗ chỗ và đầy vết nứt).}
{142}{}{Mời quý khách! Xin giới thiệu, XÁC ƯỚP! (cái nắp giống như cửa hầm mở ra, hé lộ một xác ướp Ai Cập Jan-ướp-rượu đứng trong chiếc quan tài mở trông giống như được làm từ vàng nguyên chất!)}
{143}{}{Này, chờ chút. Đấy không phải Xác ướp. Đó là một ghoul. WOODY! Này WOODY! Phải ông không?}
{144}{}{Sao tôi nhìn thứ này giống hệt dân ghoul.}
{145}{}{Xác ướp đấy à? Đéo thể tin là tôi vừa trả 25$ để nghía miếng thịt bò khô dài 6 bộ. Chào.}
{146}{}{Ồ, tuyệt thật đấy... Chắc vậy (Bạn chăm chú nhìn Xác ướp một lúc). Ờ, cám ơn. Chào.}
{147}{}{(Xác ướp hắt xì hơi, duỗi người một cách uể oải rồi nhìn bạn bằng ánh mắt ngái ngủ) Chào. (ông ta nói bằng giọng ngủ gật).}
{148}{}{Con mẹ nó! Đây *là* Woody! Chạy đi Woody, chạy đi! À, ờ, lê bước đi cũng được! Đi nào, Woody, đi đi!}
{149}{}{Tôi đảm bảo với cậu rằng Xác ướp này đúng thực là một xác-ngâm-rượu.}
{150}{}{Tôi không nghĩ mình có thể tin được ông. Để tôi thử xem sao. WOODY! Này WOODY! Phải ông không thế?}
{151}{}{Ồ, nếu ông đã nói thế. Nhưng tôi vẫn chắc là thứ này trông giống một gã ghoul bình thường. Chào.}
{152}{}{(Wood -- đúng là Woody chứ không phải một Xác ướp, đứng dậy một cách ngái ngủ -- vịn tay vào thành chiếc
quan tài
bằng giấy bồi, hét lên một tiếng rồi chạy về phía cửa, để lại sau lưng dải giấy vệ sinh "băng buộc xác ướp" và
câu nói vội "Cạm ơn nhiệu, Người lạ!".}
{153}{}{Ha! Tôi biết mà! Ông hết trò ở cái thị trấn này rồi. Ông không còn là Montania vĩ đại nữa, ông chỉ là một gã khốn nạn thôi.}
{154}{}{Chạy đi, Woody! À há! Tôi biết mà!}
{155}{}{(Motania vĩ đại nhún vai) Ta biết là đáng lẽ mình nên vác con Brahmin một đầu đấy đi mà. Ôi dào, lại về nghĩ mưu tiếp.}
{156}{}{Bò một đầu ấy hả? Hà, có cái đầu kak đi tin ấy! Chào nhé, đồ Lừa đảo.}
{157}{}{Bạn đã đánh thức ghoul Woody và giải thoát cho ông ta khỏi bị đóng vai xác ướp nữa.}
{158}{}{Tôi nghĩ là mình muốn nghe truyện ma hơn.}
{200}{}{Ta biết là có những thứ người phàm không được phép biết. Aiieee! Nyarloth... Ồ, xin lỗi (he-he). Hơi quá mồm một chút. Ta
biết những câu truyện Ma ám ảnh ngay những mảnh đất này, cũng như Xác ướp Ai Ca-a-ập ngâm rượu mà bạn có thể xem,
ngay tại đây trong chiếc quan tài diễm lệ này.}
{201}{}{Hãy nói cho tôi về xác ướp đi. Tôi rất muốn nghe thêm.}
{202}{}{Tôi chỉ muốn nghe truyện ma thôi. Ồ, mà tôi có được uống ca cao nóng tặng kèm không?}
{203}{}{Tôi không nghĩ là mình có thừa thời gian để ngồi nghe ông lảm nhảm những điều huyên thuyên.}
{300}{}{Ồ bạn thấy đấy (ông ta ra hiệu cho bạn lại gần hơn) hồi xưa từng có một nữ hoàng vĩ đại cai trị tất cả những vùng quanh đây.
Nàng giữ vững được ngai vị nhờ tấm bùa đặc biệt mà nàng luôn đeo trên cổ. Hấp dẫn đấy chứ hả?}
{301}{}{Ừ, ờ. Đúng thế. Vậy là cô công chúa này có một tấm bùa *phép*. Ồ, kể tiếp đi. Tôi không thể chờ
lâu hơn được nữa đâu (ngáp).}
{302}{}{OK. Tôi nghĩ là mình nghe đủ rồi. Chào.}
{400}{}{Ồ, để ta vào thẳng mạch chính dzậy. Gã phù thủy độc ác đã hạ độc nàng công chúa trẻ và lấy đi tấm bùa của nàng. Kể từ đó,
nàng vẫn luôn luẩn quẩn trong căn phòng kế bên. À, ừ, luôn ở đó vào giờ hắc đạo. Đấy là lí do tại sao ta luôn khóa chặt cửa.
Đáng sợ đấy chứ hả?}
{401}{}{The ghost of an amuletless princess in the trashed room next door? That's it? I can't believe you're peddling *that* as a story.
 I'd rather hear about this stupid Mummy you're supposed to have here.}
{402}{}{OK. Tôi nghĩ là mình nghe đủ rồi. Chào.}
