{100}{}{Bạn thấy một hồn ma!}
{101}{}{Bạn thấy hồn ma Anna.}
{150}{}{Đó là một hồn ma. Không phải thứ bạn vẫn thấy mỗi ngày.}
{151}{}{Trông cô ta có vẻ đau khổ.}
{152}{}{[NÓI CHUYỆN]}
{153}{}{Ôi, cơn đau này! Đốt cháy tim tôi!}
{154}{}{Có chuyện gì thế?}
{155}{}{Ông là ai?}
{156}{}{Hãy cút đi, linh hồn tội lỗi!}
{157}{}{Tôi đã đi gõ từng cánh cửa, nhưng chẳng ai thấy, chẳng ai nghe cả.}
{158}{}{Tôi có thể nghe tiếng cô. Có chuyện gì vậy?}
{159}{}{Tôi nghĩ là cô cần tắt Thiết bị tàng hình đi đấy, cô gái ạ.}
{160}{}{Nó đâu rồi? Tôi không tìm được! Tôi lạc lối! Ôi...}
{161}{}{Cô đang tìm gì thế? Có lẽ tôi có thể giúp đỡ.}
{162}{}{Cô cần phải ngừng kêu ca than vãn lại và nói cho tử tế đi.}
{163}{}{Mặt dây chuyền của tôi! Mất rồi! Kẻ trộm! Có kẻ trộm!}
{164}{}{Ồ, tôi mới đến đây. Tôi không trộm nó.}
{165}{}{Tôi giúp cô tìm được không?}
{166}{}{Ôi, số phận nghiệt ngã.}
{167}{}{Cô không nghe thấy tôi phải không?}
{168}{}{Gặp lại sau, cô gái ma.}
{169}{}{Chào. Tôi sẽ cố giúp.}
{170}{}{Mặt dây chuyền của tôi! Đưa nó cho tôi!!! Ôi!!!}
{171}{}{Mơ à! Biến về địa ngục đi. Tôi tự mình tìm thấy thứ này cơ mà.}
{172}{}{OK. Của cô đây.}
{173}{}{Đây. Mong cô yên nghỉ.}
{174}{}{OK.}
{175}{}{Không.}
{176}{}{Mặt dây chuyền của tôi, của tôi! Con đến đây, Cha ơi! Con đang đến đây!}
{177}{}{Tạm biệt.}
{178}{}{Chờ đã! Đừng đi!}
{179}{}{Hãy bước theo ánh sáng.}
{200}{}{Ở đâu được nhỉ?}
{201}{}{Ồ-ồ-ồ.}
{202}{}{Mẹ? Cha ơi? Mọi người đâu rồi?}
{203}{}{Tôi không tìm được nó!}
{500}{}{Mẹ ơi... Cha ơi... Con đến đây...}
{501}{}{Sáng quá...}
{502}{}{Bà ơi, con có thể gặp người rồi...}
{503}{}{Ồ, là ngài Cain tốt bụng. Thật vui được gặp lại ông...}
{550}{}{Ngôi nhà này đã thanh bình rồi.}
{551}{}{Oog, xương xinh đấy.}
{560}{}{SĂN MA!}
{561}{}{Hực.}
