{100}{}{Bạn thấy một người đàn ông thấp lùn với bộ râu rậm.}
{101}{}{Bạn thấy Montania vĩ đại.}
{102}{}{Bạn thấy một người đàn ông thấp lùn để râu ria với bộ dạng lén lút.}
{103}{}{Ngươi! Ngươi muốn làm gì với Ananias vốn từng vĩ đại đây?}
{104}{}{Tránh xa ta ra!}
{105}{}{Đi phá chỗ khác đi.}
{106}{}{Đi chỗ khác mà đái.}
{107}{}{Ngươi đã khiến ta mất tất cả rồi.}
{108}{}{Hãy cút đi, ngươi phá thế là đủ lắm rồi.}
{109}{}{Tôi đói quá.}
{110}{}{Làm thế nào nuôi sống được gia đình giờ?}
{111}{}{Ngươi sinh ra với trái tim nhỏ hơn 12 cỡ.}
{112}{}{Không phải, bạn tôi ơi, một XÁC ƯỚP! Được đưa trực tiếp từ cát vùng Ai Cập cổ đại đến cát vùng Hoang mạc! Chỉ có mình ngươi được thấy!}
{113}{}{Rồi, cắn câu rồi đây. Thế nghía cái xác chết khô hết bao xèng?}
{114}{}{(tự lẩm nhẩm) Hừm, xác ướp cũng khá giống với ghoul. OK, tôi sẽ xem -- bao nhiêu?}
{115}{}{Tôi đã thấy đủ xác chết rồi. Chào.}
{116}{}{Xin chào, chào mừng! Ta là Montania vĩ đại (ông ta khẽ cúi chào với động tác khoa trương). Ta mang đến điều bí ẩn từ mọi chốn xa xôi, bạn à. Những điều bí ẩn từ thế giới vượt ra khỏi thế giới của chúng ta... thế giới Bên kia.}
{117}{}{Quay lại để tìm hiểu những điều bí ẩn của Montania vĩ đại về thế giới Bên kia à?}
{118}{}{Bí ẩn nào thế?}
{119}{}{Ờ, rất vui được gặp ngài Mông to... gì đấy.}
{120}{}{Hừm, bí ẩn làm tôi mất ngủ. Tôi nên đi thì hơn. Chào.}
{121}{}{Tiến lên đi!}
{127}{}{Hôm nay, trong căn phòng này, ta có thứ này, chỉ mình ngươi được thấy... Xác ướp Ai Cập Jan-ướp-rượu!}
{128}{}{Xác ướp à?}
{129}{}{A mummy? Hmm, I wonder if it could be.... No, nobody could be that stupid.}
{130}{}{I don't have any interest in that sort of thing. Corpses scare me.}
{131}{}{Out of the way, you're blocking paying customers.}
{132}{}{I don't think this is for you.}
{133}{}{Why don't you take your little tribal self elsewhere.}
{134}{}{This isn't really for you.}
{135}{}{I see, hmmm, how about GO (he points) AWAY!}
{136}{}{For a person of your obvious class I would be happy to show this unique, and historic, specimen to you for a mere $25.}
{137}{}{OK, I'll cough up the dough. Now... Show Me The Mummy!}
{138}{}{I don't want to spend that much. I think I'll survive without seeing the thing. Goodbye.}
{139}{}{Simply open the sarcophagus lid and the marvelous Mummy will be revealed, in all its ancient glory, to you. But please, no touching, and, uh, no flash photography.}
{140}{}{Great.}
{141}{}{There you go! The MUMMY! (the door to the sarcophagus swings open to reveal a desiccated corpse, that looks very much like an ordinary ghoul, standing in a poorly painted, chipped and cracked paper-mache sarcophagus.)}
{142}{}{There you go! Presenting, the MUMMY! (a crypt-like door swings open to reveal a jan-u-wine Egyptian mummy standing in an open sarcophagus that looks as though it's made out of pure gold!)}
{143}{}{Hey, wait a minute. That's not a Mummy. That's a ghoul. WOODY! Hey WOODY! Is that you?}
{144}{}{That sure looks like a ghoul to me.}
{145}{}{That's a mummy? I can't believe I just paid $25 to see a six-foot hunk of jerky. Goodbye.}
{146}{}{Wow, that's fantastic... I guess. (you look at the Mummy very intently for a while). Uh, thanks, Goodbye.}
{147}{}{(the Mummy, snorts, stretches languidly, and then looks at you with a sleepy blink to its eyes) Hello. (he says, sleepily)}
{148}{}{Holy shit! That *is* Woody! Run Woody, run for it! Well, uh, gimp for it then! Go Woody go!}
{149}{}{I assure you that the Mummy is, in fact, quite jan-u-wine.}
{150}{}{I don't think I believe you. Let me try something. WOODY! Hey WOODY! Is that you?}
{151}{}{Well, if you say so. But I sure think it looks like an ordinary ghoul. Goodbye.}
{152}{}{(Woody--for it is in fact Woody, not a Mummy, that stands somewhat drowsily before you--grabs the sides of the
 paper-
mache sarcophagus, lets out a shriek and runs for the door, leaving a trail of toilet-paper 'mummy-wrappings'
 and a hasty "Thankee kindly, Stranger!" behind him.)}
{153}{}{Hah! I knew it! You're finished in this town. You're not the Great Ananias anymore, you're just another ass.}
{154}{}{Go Woody go! Ahah! I knew it!}
{155}{}{(The Great Ananias shrugs) I knew I should have picked up that mono-headed Brahmin instead. Oh well, back to the drawing board.}
{156}{}{Mono-headed brahmin? Sure, who would ever believe that! Goodbye, you Charlatan.}
{157}{}{You woke up Woody the ghoul and freed him from indentured mummy-tude.}
{158}{}{I think I'd rather hear the ghost story.}
{200}{}{I know things that mere mortal man is not meant to know. Aiiieeee! Nyarloth... Oh, sorry (heh, heh). Got a little carried away
 there for a moment. I have tales of a Ghost that haunts these very grounds, as well as a Jan-u-wine Egypt-ee-an Mummy that you
 can see, right here in this marvelous sarcophagus.}
{201}{}{Tell me about the mummy. I'm just dying to hear more about that.}
{202}{}{I've just got to hear that ghost story. Uh, do I get a nice hot cup of cocoa to go with it?}
{203}{}{I don't think I have any more time to waste on whatever it is that you're hawking.}
{300}{}{Well, you see, (he motions you closer) there was once a great queen that ruled all of the surrounding town. She kept her
 throne by virtue of a special amulet that she kept around her neck at all times. Great stuff, huh?}
{301}{}{Uh, yeah. You bet. So this princess had a *magic* amulet. Oh, do go on. I just can't stand this level of suspense
 much longer (yawn).}
{302}{}{OK. I think I've heard just about enough. Goodbye.}
{400}{}{Well, I'll cut to the chase then. So, the evil wizard poisoned the young princess and took her amulet. She's been wandering
 around the room next door ever since. Well, uh, that is, just at the witching hour, anyway. That's why I keep the door locked.
 Pretty darn scary, huh?}
{401}{}{The ghost of an amuletless princess in the trashed room next door? That's it? I can't believe you're peddling *that* as a story.
 I'd rather hear about this stupid Mummy you're supposed to have here.}
{402}{}{OK. I think I've heard just about enough. Goodbye.}
