{100}{}{Người đàn ông này trông có vẻ khỏe mạnh và cảnh giác.}
{101}{}{Trông cô ta có vẻ khỏe dù có thân hình nhỏ bé.}
{200}{}{Ông ta tuy rất gầy gò nhưng mặt lại cau có.}
{201}{}{Người này trông khá mạnh.}
{202}{}{Ông ta di chuyển nhanh thật.}
{210}{}{Trông cô ta cứ như thể chưa tắm bao giờ.}
{211}{}{Cô ta trông có vẻ chiến.}
{212}{}{Người này chắc chỉ một đòn là gục.}
{245}{}{Yên lặng nào! Chúng đang ở gần rồi.}
{246}{}{Diệt người xấu.}
{247}{}{Không lấy nhà từ tôi.}
{248}{}{Tôi bảo vệ nhà.}
{249}{}{Không được tìm thấy chúng tôi.}
{250}{}{Chúng người xấu.}
{260}{}{Đám buôn người đang đến. Mọi người yên lặng.}
{261}{}{Sẵn sàng đi. Tôi nghĩ giờ chúng ở gần rồi.}
{262}{}{Tôi sẽ không bỏ cuộc mà không chiến đấu đâu.}
{263}{}{Chúng sẽ không bao giờ ép chúng ta thành nô lệ được.}
{264}{}{Đám buôn người sẽ phải trả giá vì điều này.}
{265}{}{Không kẻ buôn người nào lấy nhà tôi đi được.}
{300}{}{Mày chết giờ!}
{301}{}{Ta giết!}
{302}{}{Mày không làm đau nhà!}
{303}{}{Mày không lấy mất nhà!}
{304}{}{Ta bảo vệ!}
{305}{}{Ta làm đau mày!}
{306}{}{Mày trả giá!}
{307}{}{Chết đi!}
{308}{}{Ta sẽ làm ngươi thấy đau đớn.}
{350}{}{Kẻ buôn người, ngươi sẽ không cướp được gia đình ta đâu!}
{351}{}{Chết đi, đồ buôn người ghê tởm!}
{352}{}{Mày sẽ phải trả giá, đồ khốn!}
{353}{}{Ta sẽ chiến đấu đến cùng vì gia đình!}
{354}{}{Ngươi sẽ không thoát được đâu!}
{355}{}{Mày sẽ không đưa các bạn ta rời khỏi đây được đâu!}
{356}{}{Ta sẽ cho ngươi một trận!}
{357}{}{Lũ buôn người chết tiệt!}
{358}{}{Mày sẽ trả giá cho chuyện này!}
