{100}{}{Bạn thấy một khách của quán Lỗ.}
{150}{}{Người này rõ ràng là không hấp dẫn lắm.}
{151}{}{Gã này chỉ còn mỗi một cái răng.}
{152}{}{[NÓI CHUYỆN]}
{153}{}{Vợ cậu đẹp đấy!}
{154}{}{Tránh xa bọn tôi ra.}
{155}{}{Ông thích cô ta à?}
{156}{}{Ừ, đúng vậy.}
{157}{}{Chuẩn.}
{158}{}{Tôi khá chắc là muốn đụ cô ta.}
{159}{}{Thì cứ tự nhiên.}
{160}{}{OK. Hết tất cả 50$.}
{161}{}{Được, nhưng ông phải nhè 200$ ra.}
{162}{}{Không đâu! Tránh xa bọn tôi ra!}
{163}{}{OK.}
{164}{}{Không.}
{165}{}{Được rồi! Giờ thì đi với Billy nào cưng.}
{166}{}{Giờ thì biến đi.}
{167}{}{Cám ơn. Tạm biệt.}
{168}{}{Chào.}
{169}{}{Òa, tệ thật.}
{170}{}{[XONG]}
{171}{}{Tôi mệt lắm rồi.}
{172}{}{Tôi sẽ trở lại.}
{173}{}{OK.}
{174}{}{Cưng đẹp thật đấy.}
{175}{}{Tránh xa tôi ra.}
{176}{}{Nhè 200$ ra và ông có thể chơi tôi.}
{177}{}{Tôi giá 50$, Mac.}
{178}{}{He he. Cám ơn.}
{179}{}{Tôi không có đủ tiền.}
{180}{}{Ok, thế 50$.}
{181}{}{Thế thì tệ quá.}
{182}{}{Gặp lại sau.}
{183}{}{Đừng có làm phiền tôi. Tôi đang săn đám gà tơ.}
{184}{}{Chúc may mắn. Ông sẽ cần nhiều đấy.}
{185}{}{What am I, chopped liver?}
{186}{}{Chào.}
{187}{}{Oooh. OK. Bye.}
{188}{}{[looks you up and down] No. I like chopped liver.}
{189}{}{I don't need this from you!}
{190}{}{Excuse me, I have to go.}
{191}{}{Too bad. I thought you were cute.}
{203}{}{I want my money back.}
{204}{}{I ain't giving you anything but a hole in the head.}
{205}{}{OK, here you go.}
{206}{}{Hey.}
{207}{}{Oh come on, give }
{208}{}{ another chance here.}
{209}{}{I can see you don't want to talk to me. I'm leaving.}
{210}{}{I gave you your chance and you blew it.}
{211}{}{OK, but just one more chance.}
{212}{}{That's my boy.}
{213}{}{I'm just gonna have to kill you, then.}
{220}{}{Hey, Frankie, I'm gonna just borrow the back room for a little while.}
{221}{}{Hey, Frankie, look what I snagged.}
{222}{}{Uh, Frankie, if anyone's... uh... looking for me, I'll be in back.}
{223}{}{Follow me.}
{224}{}{It's gonna have to wait. I'll talk to you later.}
{225}{}{I don't have it.}
{300}{}{Damn, I'm fucked flat.}
{301}{}{Wahoo.}
{302}{}{That was... was... WOW!!!}
{303}{}{You could set her ass on fire.}
{304}{}{Damn that parted my hair - well, what little I have.}
{305}{}{Sure beats a roll with Dave.}
{320}{}{Not bad... Not bad...}
{321}{}{I might even pay for that again.}
{322}{}{Mmmm...}
{323}{}{Not bad, not bad.}
{324}{}{We'll have to do that again and work on our... flexibility.}
{350}{}{Looks like I'm going to be getting Handy again.}
{351}{}{Don't let the door hit your DRY ASS on the way out!}
{352}{}{Time to finish what you couldn't even start!}
{370}{}{Oh, that's nice.}
{371}{}{Billy likes that.}
{372}{}{Ohhhh yeah.}
{373}{}{Nice.}
{374}{}{Jeezus and ramona.}
{375}{}{Good Gracious.}
{376}{}{I shoulda packed a box of tissue.}
{377}{}{Hmmm, who should I imagine now.}
{390}{}{Hey, can't you see I'm busy in here?}
{391}{}{Hey, hey, get the hell out.}
{392}{}{Hey, you couldn't finish the job, so get out.}
{393}{}{Can you get me a mop and come back in 5?}
{400}{}{Billy, you better not have made a mess on that mattress again!}
{401}{}{Hey Billy, you need a mop?}
{402}{}{Billy, your fly's down. AGAIN!}
{403}{}{Yo Billy, don't forget to change your pants later.}
{404}{}{Billy, you been eating doughnuts?}
{410}{}{Uhhh.}
{411}{}{Shucks}
{412}{}{Jeesh}
{413}{}{He, he, heee...}
{414}{}{Hở?}
{500}{}{*SPIT, SPIT* Eccchhhh...}
{510}{}{Hey buddy, care to "rent" that fine ho of yours?}
{511}{}{Can't this wait? I've got to get a drink.}
{512}{}{Yeah, if you want to talk to me, I'll be at The Hole.}
{513}{}{How about you meet me at The Hole and I buy you a drink?}
{520}{}{Sorry, I'm a hurry to get home. I just got some new porn in.}
{521}{}{I'm uhhh, tired, please let me go home and uhhh, sleep...}
{522}{}{I'm going over to Dave's. He's got a whole porn wing!}
{530}{}{Uhhh, no thanks. I don't have money to piss away on that again.}
{540}{}{Alright, I'll give your ass a try again.}
