{100}{}{Bạn thấy một khách của quán Lỗ.}
{150}{}{Người này rõ ràng là không hấp dẫn lắm.}
{151}{}{Gã này chỉ còn mỗi một cái răng.}
{152}{}{[NÓI CHUYỆN]}
{153}{}{Vợ cậu đẹp đấy!}
{154}{}{Tránh xa bọn tôi ra.}
{155}{}{Ông thích cô ta à?}
{156}{}{Ừ, đúng vậy.}
{157}{}{Chuẩn.}
{158}{}{Tôi khá chắc là muốn đụ cô ta.}
{159}{}{Thì cứ tự nhiên.}
{160}{}{OK. Hết tất cả 50$.}
{161}{}{Được, nhưng ông phải nhè 200$ ra.}
{162}{}{Không đâu! Tránh xa bọn tôi ra!}
{163}{}{OK.}
{164}{}{Không.}
{165}{}{Được rồi! Giờ thì đi với Billy nào cưng.}
{166}{}{Giờ thì biến đi.}
{167}{}{Cám ơn. Tạm biệt.}
{168}{}{Chào.}
{169}{}{Òa, tệ thật.}
{170}{}{[XONG]}
{171}{}{Tôi mệt lắm rồi.}
{172}{}{Tôi sẽ trở lại.}
{173}{}{OK.}
{174}{}{Cưng đẹp thật đấy.}
{175}{}{Tránh xa tôi ra.}
{176}{}{Nhè 200$ ra và ông có thể chơi tôi.}
{177}{}{Tôi giá 50$, Mac.}
{178}{}{He he. Cám ơn.}
{179}{}{Tôi không có đủ tiền.}
{180}{}{Ok, thế 50$.}
{181}{}{Thế thì tệ quá.}
{182}{}{Gặp lại sau.}
{183}{}{Đừng có làm phiền tôi. Tôi đang săn đám gà tơ.}
{184}{}{Chúc may mắn. Ông sẽ cần nhiều đấy.}
{185}{}{Tôi là gì, gan băm sống à?}
{186}{}{Chào.}
{187}{}{Ồ-ồ. OK. Chào.}
{188}{}{[nhìn bạn từ trên xuống dưới] Không. Tôi thích gan băm.}
{189}{}{Tôi không cần thứ này của ông!}
{190}{}{Thứ lỗi, tôi phải đi.}
{191}{}{Tệ thật. Tôi cứ tưởng cô dễ thương lắm.}
{203}{}{Tôi muốn lấy lại tiền.}
{204}{}{Tôi sẽ không trả lại ông cái gì ngoài một lỗ trên sọ đâu.}
{205}{}{OK, của ông đây.}
{206}{}{Này.}
{207}{}{Ồ thôi nào, cho }
{208}{}{ một cơ hội nữa đi.}
{209}{}{Tôi có thể thấy là ông không muốn nói chuyện nữa. Tôi đi đây.}
{210}{}{Tôi đã cho cô cơ hội và cô đã phung phí rồi.}
{211}{}{OK, nhưng chỉ một lần nữa thôi.}
{212}{}{Thế mới là đàn ông chứ.}
{213}{}{Thế thì tôi sẽ phải thịt ông vậy.}
{220}{}{Này, Frankie, tôi mượn phòng sau một lát nhé.}
{221}{}{Này, Frankie, xem tôi kiếm được gì này.}
{222}{}{Ờ, Frankie, nếu có ai... ờ... tìm tôi, thì tôi ở phòng sau nhé.}
{223}{}{Theo tôi.}
{224}{}{Cứ chờ đấy. Tôi sẽ nói chuyện sau.}
{225}{}{Tôi không có tiền.}
{300}{}{Mẹ kiếp, tôi cháy túi rồi.}
{301}{}{Wahoo.}
{302}{}{Thật là... là... WOW!!!}
{303}{}{Ông có thế đốt mông cô ta đấy.}
{304}{}{Chậc vặt trụi hết cả tóc - ồ, tôi cũng chả còn mấy.}
{305}{}{Đúng là hơn hẳn Dave.}
{320}{}{Không tệ... Không tệ...}
{321}{}{Có thể tôi sẽ trả tiền để thêm lần nữa.}
{322}{}{Hừm...}
{323}{}{Không tệ, không tệ.}
{324}{}{Chúng ta sẽ phải làm lại và điều chỉnh lại... độ dẻo dai.}
{350}{}{Có vẻ như tôi sẽ lại cần đấy Tay đấy.}
{351}{}{Đừng có để cửa đập vào CÁI MÔNG KHÔ KHÔNG KHỐC lúc ra đấy!}
{352}{}{Đã đến lúc kết thúc thứ mà ông còn thậm chí còn chưa bắt đầu rồi!}
{370}{}{Ồ, hay đấy.}
{371}{}{Billy thích vậy.}
{372}{}{Ồ tuyệt.}
{373}{}{Tuyệt.}
{374}{}{Jeezus và Ramona.}
{375}{}{Trời đất ơi.}
{376}{}{Đáng ra tôi phải cầm theo hộp khăn giấy.}
{377}{}{Hừm, tôi nên tưởng tượng đến ai giờ nhỉ.}
{390}{}{Này, không thấy là tôi đang bận à?}
{391}{}{Này, này, cút khỏi đây ngay.}
{392}{}{Này, cô làm còn chẳng xong, biến đi.}
{393}{}{Lấy giúp tôi cái chổi và quay lại lúc 5 giờ được không?}
{400}{}{Billy, tốt nhất là ông đừng có làm bẩn thảm lần nữa đấy!}
{401}{}{Này Billy, ông cần chổi à?}
{402}{}{Billy, ông lại hở khuy quần NỮA RỒI!}
{403}{}{Yo Billy, tí nữa đừng quên thay quần đấy nhé.}
{404}{}{Billy, ông dạo này ăn bánh vòng à?}
{410}{}{Ù-ừ.}
{411}{}{Chậc}
{412}{}{Hừ}
{413}{}{He, he, heee...}
{414}{}{Hở?}
{500}{}{*KHẠC NHỔ* Oạc ẹ...}
{510}{}{Này anh bạn, có cho thuê cô bồ xinh đẹp đấy không?}
{511}{}{Chờ chút được không? Tôi đi làm ly đã.}
{512}{}{Ờ, nếu muốn nói chuyện với tôi thì tôi sẽ ở quán Lỗ.}
{513}{}{Thế gặp tôi ở quán Lỗ đi, rồi tôi sẽ mời một ly?}
{520}{}{Xin lỗi, tôi cần phải về nhà sớm. Có mấy món khiêu dâm mới về.}
{521}{}{Tôi ờ ờ, mệt rồi, làm ơn để tôi về nhà và ờ, ngủ...}
{522}{}{Tôi sẽ đi đến chỗ Dave. Hắn ta có cả một phòng khiêu dâm!}
{530}{}{Ừ, không cám ơn. Tôi không có tiền để tè vào chỗ đấy nữa.}
{540}{}{Được rồi, tôi sẽ thử mông cô lần nữa.}
