{100}{}{Bạn thấy một thành viên của Hội buôn người.}
{150}{}{Bạn thấy Metzger, người đứng đầu Hội buôn người.}
{151}{}{[NÓI CHUYỆN]}
{152}{}{Lính gác! Tấn công!}
{153}{}{[xong]}
{154}{}{Quay lại lúc sáng ấy mẹ kiếp! Tao chỉ làm việc ban ngày thôi.}
{155}{}{[xong]}
{156}{}{Giờ thì cần gì? Mày bắt đầu khiến tao phát cáu rồi đấy.}
{157}{}{Tôi muốn xin lỗi.}
{158}{}{Xin lỗi, lúc trước tôi phê quá. Tôi không có ý gì đâu.}
{159}{}{Ồ này, ông sao thế?}
{160}{}{Tôi muốn hỏi một câu.}
{161}{}{Rõ ràng là có rồi. Chào.}
{162}{}{Wa.}
{163}{}{Ồ, trễ quá rồi. Biến đi.}
{164}{}{Làm ơn, làm ơn đi mà; Tôi xin lỗi.}
{165}{}{Ồ, tôi cũng đã thử rồi.}
{166}{}{Vậy thì đi chết đi!}
{167}{}{Được rồi, được rồi. Nhận lỗi thế là được.}
{168}{}{Phù. Tôi hỏi mấy câu được không?}
{169}{}{Tôi mừng là chúng ta đã giải quyết xong chuyện đó. Gặp lại sau.}
{170}{}{Chào, rất vui gặp lại cậu.}
{171}{}{Chào Metzger. Chúng ta cần nói chuyện.}
{172}{}{Ông cũng thế. Chào.}
{173}{}{Ợ.}
{174}{}{Tao là Metzger, Trưởng Hội buôn người. Mày cần gì?}
{175}{}{Tôi có mấy câu hỏi.}
{176}{}{Không, cám ơn. Tôi đi giờ đây.}
{177}{}{Bun ngùi???}
{178}{}{Làm ơn biến đi. Ngay bây giờ.}
{179}{}{Không thì sao?}
{180}{}{Được rồi. Nhưng tôi sẽ trở lại!}
{181}{}{OK. Chào.}
{182}{}{Muốn hỏi gì thế?}
{183}{}{Về Thương nhân Vic...}
{184}{}{Tôi gia nhập Hội buôn người được không?}
{185}{}{Tôi muốn bán chồng đi làm nô lệ.}
{186}{}{Tôi muốn bán vợ. Giá nhiêu?}
{187}{}{Tôi muốn bán một trong số đám bạn ở đây.}
{188}{}{Hãy kể cho tôi về hội đi.}
{189}{}{Ông mua nô lệ ở thành phố nào thế?}
{190}{}{Tôi muốn mua nô lệ.}
{191}{}{Tôi đang tìm Vault 13. Ông có biết gì không?}
{192}{}{Metzger? Tên lạ thật đấy.}
{193}{}{Không có gì. Tôi phải đi.}
{195}{}{Tên này từ một ngôn ngữ cổ, trước chiến tranh gì đó.}
{196}{}{Metzger có nghĩa là đồ tể. Hợp đấy chứ, phải không?}
{197}{}{Đấy là tên ông cố nội tao. Lão đến từ chỗ rất xa về phía Đông. Qua một
vùng nước lớn.}
{198}{}{Tôi đã đọc một số sách về gã Metzger. Ông ta là tổng thống gì đó.}
{199}{}{Xem ai đang nói tiếng toọc này.}
{200}{}{Tiếng Đút, Đức, Đục gì đấy. Ngôn ngữ cổ,
cổ lổ xĩ lắm rồi.}
{201}{}{Et tu, Brutus?}
{202}{}{Hiểu rồi. Mà tôi vẫn còn muốn hỏi thêm nữa.}
{203}{}{Đó là thứ ngu ngốc nhất mà tôi từng nghe.}
{204}{}{Hay đấy. Tôi phải đi rồi.}
{205}{}{Nhiệm vụ của chúng tao là cung cấp lực lượng lao động ổn định có chất lượng cao
cho các thành phố lớn đang ngày càng thiếu nhân lực. Muốn tham gia cùng không?}
{206}{}{Được chứ. Nghe hay đấy.}
{207}{}{Không đời nào.}
{208}{}{Tôi sẽ quay lại việc đó sau. Thành phố nào mua nô lệ của ông thế?}
{209}{}{Thứ lỗi, đấy là thông tin nội bộ trong hội.}
{210}{}{OK. Ghi tên tôi vào nào!}
{211}{}{Không! Lũ các người là một đám bệnh hoạn!}
{212}{}{Tôi sẽ suy nghĩ về việc đó. Tôi muốn hỏi thêm.}
{213}{}{Hừm, tôi sẽ trở lại sau.}
{214}{}{Bọn ta cần xăm một dấu nhỏ trên trán mày để thể hiện cho mọi người
rằng mày là một thành viên của hội buôn người. Sẵn sàng chưa?}
{215}{}{Nghe tuyệt đấy! Làm đi!}
{216}{}{Tôi đổi ý rồi. Tôi hỏi câu khác được không?}
{217}{}{Hiện tại tôi không có thời gian. Tôi phải đi.}
{218}{}{Chào mừng đến với hội!}
{219}{}{Tuyệt, tôi có câu hỏi!}
{220}{}{OK, cám ơn. Tôi sẽ trở lại.}
{221}{}{Vault 13? Không. Chờ tí... Tao nghĩ là Vic đến từ Thành phố Vault. Chắc là chỗ đó.}
{222}{}{Đúng rồi, nơi đó ở đâu vậy?}
{223}{}{Không. Nhưng tôi có câu hỏi khác.}
{224}{}{Không, thôi quên đi.}
{225}{}{Bọn tao chủ yếu bán nô lệ cho Thành phố Vault và New Reno. New Reno ở
phía Đông Nam chỗ này và phần lớn người The Den đều trao đổi với họ.}
{226}{}{Thành phố Vault ở đâu vậy?}
{227}{}{Tôi muốn hỏi thêm.}
{228}{}{Cám ơn, phải đi đây.}
{229}{}{Thành phố Vault đi về phía Đông, rồi lên hướng Bắc một chút. Vic từ đó đến đây.}
{230}{}{Tôi muốn hỏi thêm.}
{231}{}{Cám ơn; phải đi đây.}
{232}{}{Hừm, trông có vẻ khỏe mạnh. Tao sẽ trả mày }
{233}{}{ xu.}
{234}{}{OK! Cứ thế đi.}
{235}{}{Ờ, thôi quên đi.}
{236}{}{Không được! Phải gấp đôi!}
{237}{}{Mày trả giá cứng đấy. Tiền đây!}
{238}{}{Cám ơn. Tôi muốn hỏi thêm mấy câu.}
{239}{}{Cám ơn. Tạm biệt.}
{240}{}{Gì nữa không?}
{241}{}{Cám ơn, tôi muốn hỏi thêm một câu.}
{242}{}{Không. Chào.}
{243}{}{Mày muốn bán "bạn" nào?}
{244}{}{Ờ, thôi quên đi.}
{245}{}{Hay đấy. Tao sẽ trả mày }
{246}{}{ xu.}
{247}{}{Bán!}
{248}{}{Không, cám ơn.}
{249}{}{Tôi muốn nhiều hơn thế!}
{250}{}{Được rồi, tao sẽ trả mày }
{251}{}{ nhưng không hơn nữa đâu!}
{252}{}{Bán!}
{253}{}{Chưa đủ.}
{254}{}{Thế thì ít quá. Tôi đi đây.}
{255}{}{Mày muốn làm gì với Vic? Lão ta giờ là tài sản của ta rồi. Ai bảo đi chọc vào tao.}
{256}{}{Tôi muốn mua ông ta.}
{257}{}{Sao ông lại giữ ông ta ở đây?}
{258}{}{Không có gì. Thôi quên đi.}
{259}{}{Lão ta vẫn chưa được bán đâu.}
{260}{}{Sao lại chưa?}
{261}{}{Ồ, okay.}
{262}{}{Lão ta có giá 2000$.}
{263}{}{Tiền của ông đây.}
{264}{}{Nhiều thế. Để sau đi.}
{265}{}{Giá 1000$.}
{266}{}{Tiền của ông đây.}
{267}{}{Don't have that much yet. Bye.}
{268}{}{Our radio is broken and he's in charge of fixing it.}
{269}{}{Hiểu rồi.}
{270}{}{You haven't got the money!}
{271}{}{Too bad for me. Can I ask you a question?}
{272}{}{Sorry, I'll come back.}
{307}{}{How dare you return after abandoning your brothers during a Slave Run! Guards! Attack!}
{308}{}{[xong]}
{309}{}{Excellent! It may take a few days for you to travel there and back. Are you ready to leave now?}
{310}{}{No. I'll come back.}
{311}{}{Yes, I'm ready. Let's go.}
{312}{}{Ah, you are back from the Slave run. Let's see how you did...}
{313}{}{[more]}
{314}{}{[more]}
{315}{}{You killed potential slaves! A dead man brings us no income! Only kill the ones that are a threat,
 the others are of no threat.}
{316}{}{[more]}
{317}{}{You returned no slaves at all! What the hell is wrong with you? We're trying to make money here,
 not lose it.}
{318}{}{[more]}
{319}{}{Overall, you did well this Run. Keep up the good work and I might keep you around a while.}
{320}{}{Thank you. I will.}
{321}{}{I don't know if I like this too much.}
{322}{}{You need to improve your enslavement technique.}
{323}{}{Tôi sẽ thử.}
{324}{}{I apologize for my poor performance.}
{325}{}{I think I'm good enough.}
{326}{}{Damn it! You did terribly in this Run. Are you trying to ruin me? Be more careful next time.
 You don't need to kill them all! Just kill off the hostile ones. Leave the unarmed ones for collection.}
{327}{}{I'm sorry, Metzger.}
{328}{}{Hey, it's tough work to be a Slaver!}
{329}{}{I'd like to see you do better.}
{330}{}{I'd like to go on a slave run.}
{331}{}{Damn it! I hate losing any guild member on a Run. Try to watch each other's back!}
{332}{}{Overall, you did well this Run. Here is $}
{333}{}{ as an incentive for you to keep up the good work.}
