{100}{}{Bạn thấy một thành viên của Hội buôn người.}
{150}{}{Bạn thấy Metzger, người đứng đầu Hội buôn người.}
{151}{}{[NÓI CHUYỆN]}
{152}{}{Lính gác! Tấn công!}
{153}{}{[xong]}
{154}{}{Quay lại lúc sáng ấy mẹ kiếp! Tao chỉ làm việc ban ngày thôi.}
{155}{}{[xong]}
{156}{}{Giờ thì cần gì? Mày bắt đầu khiến tao phát cáu rồi đấy.}
{157}{}{Tôi muốn xin lỗi.}
{158}{}{Xin lỗi, lúc trước tôi phê quá. Tôi không có ý gì đâu.}
{159}{}{Ồ này, ông sao thế?}
{160}{}{Tôi muốn hỏi một câu.}
{161}{}{Rõ ràng là có rồi. Chào.}
{162}{}{Wa.}
{163}{}{Ồ, trễ quá rồi. Biến đi.}
{164}{}{Làm ơn, làm ơn đi mà; Tôi xin lỗi.}
{165}{}{Ồ, tôi cũng đã thử rồi.}
{166}{}{Vậy thì đi chết đi!}
{167}{}{Được rồi, được rồi. Nhận lỗi thế là được.}
{168}{}{Phù. Tôi hỏi mấy câu được không?}
{169}{}{Tôi mừng là chúng ta đã giải quyết xong chuyện đó. Gặp lại sau.}
{170}{}{Chào, rất vui gặp lại cậu.}
{171}{}{Chào Metzger. Chúng ta cần nói chuyện.}
{172}{}{Ông cũng thế. Chào.}
{173}{}{Ợ.}
{174}{}{Ta là Metzger, Trưởng Hội buôn người. Mày cần gì?}
{175}{}{Tôi có mấy câu hỏi.}
{176}{}{Không, cám ơn. Tôi đi giờ đây.}
{177}{}{Swavuh???}
{178}{}{Làm ơn biến đi. Ngay bây giờ.}
{179}{}{Không thì sao?}
{180}{}{Được rồi. Nhưng tôi sẽ trở lại!}
{181}{}{OK. Chào.}
{182}{}{Muốn hỏi gì thế?}
{183}{}{Về Thương nhân Vic...}
{184}{}{Tôi gia nhập Hội buôn người được không?}
{185}{}{Tôi muốn bán chồng đi làm nô lệ.}
{186}{}{Tôi muốn bán vợ. Giá nhiêu?}
{187}{}{Tôi muốn bán một trong số đám bạn ở đây.}
{188}{}{Hãy kể cho tôi về hội đi.}
{189}{}{Ông mua nô lệ ở thành phố nào thế?}
{190}{}{Tôi muốn mua nô lệ.}
{191}{}{Tôi đang tìm Vault 13. Ông có biết gì không?}
{192}{}{Metzger? Tên lạ thật đấy.}
{193}{}{Không có gì. Tôi phải đi.}
{195}{}{Tên này từ một ngôn ngữ cổ, trước chiến tranh gì đó.}
{196}{}{Metzger có nghĩa là đồ tể. Hợp đấy chứ, phải không?}
{197}{}{Đấy là tên ông cố nội tao. Lão đến từ chỗ rất xa về phía Đông. Qua một
vùng nước lớn.}
{198}{}{I read some book about a Metzger. He was a president, or something.}
{199}{}{Look who's talking tribal.}
{200}{}{It's Germen, German, Garmen, or something. Ancient language, from a
 long time ago.}
{201}{}{Et tu, Brutus?}
{202}{}{I see. I still have a question, though.}
{203}{}{That is the dumbest thing I have ever heard.}
{204}{}{Fascinating. Gotta go.}
{205}{}{Our mission is to provide a steady and high-quality labor force to
 handle the ever-growing demands of the larger cities. Would you like to join?}
{206}{}{Sure. Sounds great.}
{207}{}{No way.}
{208}{}{I'll get back to you on that. What cities buy your slaves?}
{209}{}{Sorry, that's private guild information.}
{210}{}{OK. Sign me up!}
{211}{}{No! You guys are sick people!}
{212}{}{I'll consider that. I have more questions.}
{213}{}{Hmm, I'll come back later.}
{214}{}{We will need to brand a small marking on your forehead to show to all
 your allegiance with the slavers guild. Are you ready?}
{215}{}{Sounds great! Do it!}
{216}{}{I've changed my mind. Can I ask another question?}
{217}{}{I don't have time right now. I have to go.}
{218}{}{Welcome to the guild!}
{219}{}{Great, I have questions!}
{220}{}{OK, thanks. I'll be back.}
{221}{}{Vault 13? No. Wait... I think Vic's from Vault City. Maybe that's it.}
{222}{}{Yes, where is it?}
{223}{}{No. I have another question though.}
{224}{}{No, never mind.}
{225}{}{We sell most of our slaves to Vault City and New Reno. New Reno is
 south east of here and most of the Den trades with it.}
{226}{}{Where is Vault City?}
{227}{}{I have more questions.}
{228}{}{Thanks, gotta go.}
{229}{}{Vault City is east of here, and a little south. Vic's from there.}
{230}{}{I have more questions.}
{231}{}{Thanks; gotta go.}
{232}{}{Hmm, looks like a healthy slave. I'll give you }
{233}{}{ coins.}
{234}{}{OK! It's a deal.}
{235}{}{Uh, never mind.}
{236}{}{No way! I want double!}
{237}{}{You drive a hard bargain. Here is your money!}
{238}{}{Thanks. I have some more questions.}
{239}{}{Cám ơn. Tạm biệt.}
{240}{}{Gì nữa không?}
{241}{}{Yes, I have a question.}
{242}{}{Nope. Bye.}
{243}{}{Which "friend" are you selling?}
{244}{}{Um, never mind.}
{245}{}{Interesting. I'll give you }
{246}{}{ coins.}
{247}{}{Sold!}
{248}{}{Không, cám ơn.}
{249}{}{I want more money than that!}
{250}{}{Alright, I'll give you }
{251}{}{ but no more!}
{252}{}{Sold!}
{253}{}{Not good enough.}
{254}{}{That's way too little. I'm leaving.}
{255}{}{What do you want with Vic? He's my property now. He shouldn't have fucked with me.}
{256}{}{I'd like to buy him.}
{257}{}{Why are you keeping him here?}
{258}{}{Nothing. Never mind.}
{259}{}{He is not for sale, yet.}
{260}{}{Why not?}
{261}{}{Ồ, okay.}
{262}{}{He will cost $2000.}
{263}{}{Here is your money.}
{264}{}{That's a lot. Maybe later.}
{265}{}{The cost is $1000.}
{266}{}{Here is your money.}
{267}{}{Don't have that much yet. Bye.}
{268}{}{Our radio is broken and he's in charge of fixing it.}
{269}{}{Hiểu rồi.}
{270}{}{You haven't got the money!}
{271}{}{Too bad for me. Can I ask you a question?}
{272}{}{Sorry, I'll come back.}
{307}{}{How dare you return after abandoning your brothers during a Slave Run! Guards! Attack!}
{308}{}{[xong]}
{309}{}{Excellent! It may take a few days for you to travel there and back. Are you ready to leave now?}
{310}{}{No. I'll come back.}
{311}{}{Yes, I'm ready. Let's go.}
{312}{}{Ah, you are back from the Slave run. Let's see how you did...}
{313}{}{[more]}
{314}{}{[more]}
{315}{}{You killed potential slaves! A dead man brings us no income! Only kill the ones that are a threat,
 the others are of no threat.}
{316}{}{[more]}
{317}{}{You returned no slaves at all! What the hell is wrong with you? We're trying to make money here,
 not lose it.}
{318}{}{[more]}
{319}{}{Overall, you did well this Run. Keep up the good work and I might keep you around a while.}
{320}{}{Thank you. I will.}
{321}{}{I don't know if I like this too much.}
{322}{}{You need to improve your enslavement technique.}
{323}{}{Tôi sẽ thử.}
{324}{}{I apologize for my poor performance.}
{325}{}{I think I'm good enough.}
{326}{}{Damn it! You did terribly in this Run. Are you trying to ruin me? Be more careful next time.
 You don't need to kill them all! Just kill off the hostile ones. Leave the unarmed ones for collection.}
{327}{}{I'm sorry, Metzger.}
{328}{}{Hey, it's tough work to be a Slaver!}
{329}{}{I'd like to see you do better.}
{330}{}{I'd like to go on a slave run.}
{331}{}{Damn it! I hate losing any guild member on a Run. Try to watch each other's back!}
{332}{}{Overall, you did well this Run. Here is $}
{333}{}{ as an incentive for you to keep up the good work.}
