{100}{}{Bạn thấy một đứa trẻ đang hét những câu sến sủa.}
{101}{}{Đứa trẻ bẩn thỉu này trông như được thuê để quảng cáo cho điểm du lịch gì đó.}
{500}{}{Hãy vào xem Xác ướp huyền bí đi!}
{501}{}{Hãy xem Kì quan cổ đại!}
{502}{}{Xác-ướp-rượu, ở ngay đây!}
{503}{}{Hãy đến xem Hoàng tử Ai Cập!}
{504}{}{Đến xem Nữ hoàng sông Nile!}
{505}{}{Hãy vào ngôi nhà bị ám Ướp-rượu!}
{506}{}{Bí ẩn của Thế giới bên kia đã được hé lộ!}
{507}{}{Vào đi, vào nào!}
{508}{}{Cơ hội học hỏi cả đời chỉ có một!}
