{100}{}{Bạn thấy một khách hàng.}
{101}{}{Bạn thấy một cư dân thị trấn.}
{150}{}{Ông ta trông như đang đi đâu đó.}
{151}{}{Cô ta trông như đang đi đâu đó.}
{152}{}{Ông ta đang bận uống và nói chuyện với những khách hàng khác.}
{153}{}{Cô ta có vẻ đang bận nói chuyện.}
{154}{}{Ông ta đang xem mấy cái tủ của Tubby.}
{155}{}{Cô ta trông như đang ngó hàng của Tubby.}
{156}{}{Bạn không thấy ông ta có gì khác thường cả.}
{157}{}{Bạn không thấy cô ta có gì khác thường cả.}
{200}{}{Tránh xa ta ra!}
{201}{}{Để tôi yên!}
{202}{}{Đừng chạm vào tôi!}
{203}{}{Thôi đi!}
{204}{}{Đang làm gì thế?}
{300}{}{Xin lỗi, giờ tôi không nói chuyện được.}
{301}{}{Tôi đang đi đâu ấy nhỉ?}
{302}{}{Chào.}
{303}{}{Thứ lỗi.}
{304}{}{Chào.}
{305}{}{Chỗ của Becky là số một, và không chỉ có mỗi giá thôi đâu.}
{306}{}{Anh đến đây để uống hay chơi bạc?}
{307}{}{Giờ thì chỉ cần thêm một lũ hát rong nữa thôi.}
{308}{}{Chào.}
{309}{}{Anh có chơi không?}
{310}{}{Bên ngoài sao rồi?}
{311}{}{Frank là một gã tồi. Lão ta thù hận Becky chẳng vì cái gì cả.}
{312}{}{Anh có phải bạn của Becky không?}
{313}{}{Gọi đồ uống đi, bạn tôi ơi!}
{314}{}{Uống đi! Đồ ở đây rẻ lắm!}
{315}{}{Mấy món này không pha nước đâu.}
{316}{}{Cô pha chế kia đúng là biết nghề đấy.}
{317}{}{Rượu ngon bạn hiền, đúng là số dách.}
{318}{}{Vấn đề duy nhất với đồ uống của Becky là lúc nào cũng muốn uống nhiều!}
{319}{}{Becky... ý tôi là Rebecca đúng là một phụ nữ tuyệt vời.}
{320}{}{Kẻ nào mà dám động tay vào cô ta sẽ phải hối hận.}
{321}{}{Món này ngon đấy.}
{340}{}{Bọn ta phải giết ngươi vì những gì ngươi đã làm.}
{341}{}{Tôi không biết cô ta đã làm gì với cậu nhưng cô ta không đáng phải chết.}
{342}{}{Có lẽ chúng ta nên đến New Reno vì giờ quán Becky đóng cửa rồi.}
{343}{}{Tôi nhớ nụ cười của Becky quá.}
{344}{}{Thế là hết rượu rẻ rồi.}
{345}{}{The Den mà không có quán Becky thì không được như xưa nữa.}
{360}{}{Frankie đúng là như lỗ... trên tường ấy.}
{361}{}{Tôi thích quán Lỗ hơn chỗ Becky.}
{362}{}{Chúng tôi gọi nơi này là Lỗ.}
{363}{}{Ngồi đi. Ồ, chờ đã. Có thể là không.}
{364}{}{Frankie's has action. Becky's is just a money pit.}
{365}{}{Frankie sure doesn't like Becky.}
{366}{}{Frankie says Becky's drinks are watered down.}
{367}{}{How's it going?}
{368}{}{Frankie knows how to party.}
{369}{}{Becky's tables are rigged! Well, that's what Frankie says.}
{370}{}{Bottoms up!}
{390}{}{Damn, I warned Frankie about how he treated people.}
{391}{}{Frankie should have watched his temper.}
{392}{}{Now where we going to hang out?}
{393}{}{Too bad Frankie's gone. He knew how to party.}
{394}{}{You got quite a temper. What'd Frankie do to you?}
{395}{}{Frankie insult your mom or something?}
{410}{}{Tôi chỉ ngó quanh đây thôi.}
{411}{}{I'm not sure what I'm looking for.}
{412}{}{Tubby sure goes through a lot of Jet.}
{413}{}{You see anything good?}
{414}{}{Not much here.}
{415}{}{Tubby needs to get some better suppliers.}
{416}{}{You need drugs? Tubby is normally well stocked.}
{430}{}{What did you kill Tubby for?}
{431}{}{No great loss, but Tubby was the only real shop in town.}
{432}{}{What'd Tubby do to piss you off?}
{433}{}{Tubby sold you some bad shit, didn't he?}
{434}{}{The rumor is you whacked Tubby because of a bad deal or something.}
{435}{}{Not surprised really. A lot of people have been sore with Tubby lately.}
{440}{}{Nothing I'm interested in today...}
{441}{}{Oh, hi. Just talking to my good friend Flick.}
{442}{}{What are you doing in here?}
{443}{}{You a friend of Flick's, too?}
{444}{}{I didn't do anything.}
{445}{}{What are you staring at?}
{446}{}{Just pretend you don't see me.}
{447}{}{Don't mind me.}
{460}{}{Damn. You killed Flick.}
{461}{}{Flick rip you off?}
{462}{}{Flick's been into some dangerous work.}
{463}{}{That sucks about Flick.}
{464}{}{Wonder what all those kids are going to do now that Flick is dead.}
{465}{}{Surprised Flick lasted this long.}
{480}{}{We call this home.}
{481}{}{Most of us grew up on Mom's cooking.}
{482}{}{I've known Mom since I was a kid.}
{483}{}{Mom takes care of everyone in the Den.}
{484}{}{Mom can make a sandwich out of anything.}
{485}{}{I hope you get to know Mom as well as us.}
{486}{}{Great company, great food. What else could you ask for?}
{487}{}{Cheers!}
{488}{}{Chào.}
{500}{}{How could you have hurt poor old Mom?}
{501}{}{I've known, I mean, knew Mom all my life.}
{502}{}{What did she ever do to you?}
{503}{}{Murderer! Poor Mom...}
{504}{}{Why did you have to do that?}
{505}{}{You heartless monster!}
