{100}{}{Bạn thấy một khách hàng.}
{101}{}{Bạn thấy một cư dân thị trấn.}
{150}{}{Ông ta trông như đang đi đâu đó.}
{151}{}{Cô ta trông như đang đi đâu đó.}
{152}{}{Ông ta đang bận uống và nói chuyện với những khách hàng khác.}
{153}{}{Cô ta có vẻ đang bận nói chuyện.}
{154}{}{Ông ta đang xem mấy cái tủ của Tubby.}
{155}{}{Cô ta trông như đang ngó hàng của Tubby.}
{156}{}{Bạn không thấy ông ta có gì khác thường cả.}
{157}{}{Bạn không thấy cô ta có gì khác thường cả.}
{200}{}{Tránh xa ta ra!}
{201}{}{Để tôi yên!}
{202}{}{Đừng chạm vào tôi!}
{203}{}{Thôi đi!}
{204}{}{Đang làm gì thế?}
{300}{}{Xin lỗi, giờ tôi không nói chuyện được.}
{301}{}{Tôi đang đi đâu ấy nhỉ?}
{302}{}{Chào.}
{303}{}{Thứ lỗi.}
{304}{}{Chào.}
{305}{}{Chỗ của Becky là số một, và không chỉ có mỗi giá thôi đâu.}
{306}{}{Anh đến đây để uống hay chơi bạc?}
{307}{}{Giờ thì chỉ cần thêm một lũ hát rong nữa thôi.}
{308}{}{Chào.}
{309}{}{Anh có chơi không?}
{310}{}{Bên ngoài sao rồi?}
{311}{}{Frankie là một gã tồi. Lão ta thù hận Becky chẳng vì cái gì cả.}
{312}{}{Anh có phải bạn của Becky không?}
{313}{}{Gọi đồ uống đi, bạn tôi ơi!}
{314}{}{Uống đi! Đồ ở đây rẻ lắm!}
{315}{}{Mấy món này không pha nước đâu.}
{316}{}{Cô pha chế kia đúng là biết nghề đấy.}
{317}{}{Rượu ngon bạn hiền, đúng là số dách.}
{318}{}{Vấn đề duy nhất với đồ uống của Becky là lúc nào cũng muốn uống nhiều!}
{319}{}{Becky... ý tôi là Rebecca đúng là một phụ nữ tuyệt vời.}
{320}{}{Kẻ nào mà dám động tay vào cô ta sẽ phải hối hận.}
{321}{}{Món này ngon đấy.}
{340}{}{Bọn ta phải giết ngươi vì những gì ngươi đã làm.}
{341}{}{Tôi không biết cô ta đã làm gì với cậu nhưng cô ta không đáng phải chết.}
{342}{}{Có lẽ chúng ta nên đến New Reno vì giờ quán Becky đóng cửa rồi.}
{343}{}{Tôi nhớ nụ cười của Becky quá.}
{344}{}{Thế là hết rượu rẻ rồi.}
{345}{}{The Den mà không có quán Becky thì không được như xưa nữa.}
{360}{}{Frankie đúng là như lỗ... trên tường ấy.}
{361}{}{Tôi thích quán Lỗ hơn chỗ Becky.}
{362}{}{Chúng tôi gọi nơi này là Lỗ.}
{363}{}{Ngồi đi. Ồ, chờ đã. Có thể là không.}
{364}{}{Chỗ của Frankie mới có mấy trò hay ho. Đến quán Becky thì chỉ phí tiền.}
{365}{}{Frankie đúng là không ưa Becky tí nào.}
{366}{}{Frankie nói rằng đồ của Becky toàn pha nước lã.}
{367}{}{Sao rồi?}
{368}{}{Frankie biết cách quẩy đấy.}
{369}{}{Mấy cái xới bạc bên Becky giở trò đấy! Ồ, là Frankie nói thế.}
{370}{}{Cạn ly nào!}
{390}{}{Mẹ nó chứ, tôi đã cảnh báo Frankie về cách lão ta đối nhân xử thế rồi.}
{391}{}{Frankie cần phải bớt nóng giận đi.}
{392}{}{Nào giờ thì chúng ta đi đâu đây?}
{393}{}{Thật tệ là Frankie tiêu rồi. Lão ta biết cách quẩy lắm.}
{394}{}{Cậu đúng là dễ nổi nóng. Frankie đã làm gì cậu?}
{395}{}{Frankie lăng nhục mẹ cậu hay sao chứ?}
{410}{}{Tôi chỉ ngó quanh đây thôi.}
{411}{}{Tôi không chắc mình đang tìm cái gì.}
{412}{}{Tubby hẳn là bú Jet nhiều lắm.}
{413}{}{Thấy gì hay ho không?}
{414}{}{Ở đây chẳng có gì.}
{415}{}{Tubby cần phải kiếm mối cấp hàng tốt hơn.}
{416}{}{Cần thuốc không? Tubby thường trữ nhiều lắm đấy.}
{430}{}{Sao cậu lại giết Tubby?}
{431}{}{Không phải mất mát gì lớn lắm, nhưng Tubby là nơi bán hàng thật sự duy nhất của thị trấn.}
{432}{}{Tubby đã làm gì khiến cậu lên cơn thế?}
{433}{}{Tubby bán đồ lởm cho cậu phải không?}
{434}{}{Mọi người đồn là cậu thịt Tubby vì lão giở trò khi mua bán, đại loại thế.}
{435}{}{Không có gì đáng ngạc nhiên cả. Dạo gần đây nhiều người nóng mắt với Tubby lắm rồi.}
{440}{}{Hôm nay tôi chẳng thấy thú gì cả...}
{441}{}{Ồ chào. Tôi chỉ đang nói chuyện với người bạn tốt Flick thôi.}
{442}{}{Cậu đang làm gì ở đây thế?}
{443}{}{Cậu cũng là bạn của Flick à?}
{444}{}{Tôi chẳng làm gì cả.}
{445}{}{Đang nhìn gì đấy?}
{446}{}{Cứ coi như không thấy tôi đi.}
{447}{}{Kệ tôi đi.}
{460}{}{Mẹ kiếp. Cậu giết Flick rồi.}
{461}{}{Flick gạt cậu à?}
{462}{}{Flick từng làm mấy việc nguy hiểm lắm.}
{463}{}{Kết cục của Flick tệ thật đấy.}
{464}{}{Không biết lũ trẻ sẽ thế nào khi giờ đây Flick toi rồi.}
{465}{}{Ngạc nhiên là Flick sống được đến giờ đấy.}
{480}{}{Chúng tôi gọi đây là nhà.}
{481}{}{Hầu hết chúng tôi lớn lên nhờ ăn đồ của Má.}
{482}{}{Tôi biết Má từ hồi còn bé tí.}
{483}{}{Má chăm sóc mọi người ở khu The Den.}
{484}{}{Má có thể làm bánh mì kẹp từ bất cứ thứ gì.}
{485}{}{Tôi hi vọng cậu cũng sẽ thân với Má như chúng tôi.}
{486}{}{Đồ ăn ngon, mọi người thân thiện. Còn gì hơn thế nữa?}
{487}{}{Vui lên nào!}
{488}{}{Chào.}
{500}{}{Sao cậu lại có thể đánh bà Má già yếu chứ?}
{501}{}{Tôi biết, ý tôi là, đã từng biết Má cả đời rồi.}
{502}{}{Bà ấy đã làm gì cậu chứ?}
{503}{}{Đồ sát nhân! Tội nghiệp Má...}
{504}{}{Sao cậu lại phải làm vậy?}
{505}{}{Đồ quái vật vô lương tâm!}
