{100}{}{Bạn thấy một cư dân của khu The Den.}
{101}{}{Bạn thấy Derek.}
{150}{}{Trông ông ta có vẻ khéo léo.}
{200}{}{Thôi đi.}
{201}{}{Tôi mệt, không muốn nói chuyện.}
{202}{}{Ra khỏi chỗ của tôi đi.}
{203}{}{Tự đi tìm chỗ riêng mà ngủ đi.}
{204}{}{Đừng làm phiền tôi nữa.}
{205}{}{Tôi cháy túi rồi.}
{206}{}{Doh!}
{207}{}{Này, cậu đang làm gì ở đây thế?}
{220}{}{Stay away from Metzger, tribal.}
{221}{}{Why is it always so damn hot?}
{222}{}{Why do we live in the desert?}
{223}{}{I'm a good cook.}
{224}{}{I'm going to open my own restaurant someday.}
{225}{}{I wish I had a real kitchen.}
{226}{}{Why am I always getting the short end of life?}
{227}{}{People are always screwing me.}
{228}{}{Fred's a dreamer - master plan, my ass.}
{240}{}{Shhhh! They're everywhere.}
{241}{}{Make them stop!}
{242}{}{So you found that damn book?}
{243}{}{I don't know why Becky won't hire me.}
{244}{}{I will not go insane!}
{245}{}{I got my quarters!}
{246}{}{They come out at night, mostly.}
{247}{}{I like potatoes!}
{248}{}{Don't walk on the green stuff without boots!}
{249}{}{Just turn it inside out.}
{250}{}{Oh, my head hurts really bad now.}
{251}{}{I'm a grandmaster cook!}
{252}{}{I would never poison a newbie's food.}
{260}{}{Hey you looking for some freshly baked bread?}
{261}{}{Đúng vậy.}
{262}{}{I'm looking for Becky's book.}
{263}{}{No, bye.}
{270}{}{Oh, hi again.}
{271}{}{So where's Becky's book?}
{272}{}{Hey, how about some of that bread?}
{273}{}{Chào.}
{280}{}{Ha! So am I. Have I told you what a great cook I am? Becky wont' hire me for some reason. She says I'm unstable.}
{281}{}{She's probably right.}
{282}{}{I'm looking for Becky's book.}
{283}{}{That's great. I've uh... got to go.}
{290}{}{What? You! Screw you buddy! I'm not... Ow! Fuck.}
{291}{}{What? You! Screw you lady! I'm not... Ow! Fuck.}
{292}{}{Damn.}
{293}{}{Nuf Said.}
{300}{}{Oh yeah. I didn't like it. Too much kissing. I threw it in the corner of that building... no that building... no... was it a building? Maybe I dropped it somewhere else... or did I throw it? Ow! My head!}
{301}{}{Book? Oh, that book. Who sent you? I'm not sure if that's the proper side. Don't forget the tissue.}
{302}{}{I can't! They're... oh crap... Do you have the cheese? Hide!}
{303}{}{Hey! Not my problem. What was I supposed to do? Fight them? Little green men, big pointy teeth! Fuck! Ouch! Stop that!}
{304}{}{My head hurts! What... who said that?}
{305}{}{That helps a lot.}
{306}{}{Ừ.}
{310}{}{What? Are you mocking me! Screw you! I'm not unstable! I can cook! I don't have voices in my head!}
{311}{}{I'm gonna- shit! Fuck! Damn it! Stop that. Be quiet! What?... Okay.}
{312}{}{Hey! Sto- do... fuck.}
{313}{}{Chào.}
{314}{}{Không có gì.}
{320}{}{Hey! Get away from me!}
{321}{}{Đừng chạm vào tôi!}
