{100}{}{Bạn thấy một cư dân của khu The Den.}
{101}{}{Bạn thấy Derek.}
{150}{}{Trông ông ta có vẻ khéo léo.}
{200}{}{Thôi đi.}
{201}{}{Tôi mệt, không muốn nói chuyện.}
{202}{}{Ra khỏi chỗ của tôi đi.}
{203}{}{Tự đi tìm chỗ riêng mà ngủ đi.}
{204}{}{Đừng làm phiền tôi nữa.}
{205}{}{Tôi cháy túi rồi.}
{206}{}{Doh!}
{207}{}{Này, cậu đang làm gì ở đây thế?}
{220}{}{Tránh xa Metzger ra, đồ tộc.}
{221}{}{Sao lúc đéo nào cũng nóng vãi thế?}
{222}{}{Sao chúng ta lại sống ở sa mạc nhỉ?}
{223}{}{Tôi nấu ăn khéo lắm đấy.}
{224}{}{Một ngày nào đó tao sẽ mở nhà hàng riêng.}
{225}{}{Ước gì có một căn bếp ra hồn.}
{226}{}{Sao mình lúc nào cũng đen đủi thế không biết?}
{227}{}{Mọi người chỉ phá đám là giỏi.}
{228}{}{Gã Fred chỉ mơ mộng hão huyền. Kế hoạch vĩ đại cái củ kak ấy.}
{240}{}{Suỵt! Chúng ở khắp nơi.}
{241}{}{Bảo chúng dừng lại đi!}
{242}{}{Cậu tìm thấy quyển sách chết tiệt đấy rồi à?}
{243}{}{Chả hiểu sao Becky không thuê tôi nhỉ.}
{244}{}{Tôi không điên đâu!}
{245}{}{Tôi có xiền rồi!}
{246}{}{Đa số chúng đến tối mới ra.}
{247}{}{Tôi thích khoai!}
{248}{}{Đừng có dẫm chân lên mấy bãi xanh xanh mà không đi giày!}
{249}{}{Cứ lột ngược từ trong ra.}
{250}{}{Ôi, đầu tôi giờ đau như búa bổ.}
{251}{}{Tôi là đầu bếp bậc thầy đấy!}
{252}{}{Tôi không bao giờ cho độc vào đồ của lũ lính mới đâu.}
{260}{}{Này, muốn mua bánh mì mới ra lò không?}
{261}{}{Đúng vậy.}
{262}{}{Tôi đang tìm kiếm quyển sách của Becky.}
{263}{}{Không, chào.}
{270}{}{Ồ, xin chào.}
{271}{}{Thế sách của Becky đâu?}
{272}{}{Này, thế vài ổ bánh mì đấy thì sao?}
{273}{}{Chào.}
{280}{}{Ha! Tôi cũng thế. Tôi có từng kể tôi là đầu bếp giỏi chưa ấy nhỉ? Becky vì sao đó mà không chịu thuê tôi. Cô ta bảo tôi không ổn.}
{281}{}{Chắc hẳn là vậy rồi.}
{282}{}{Tôi đang tìm kiếm quyển sách của Becky.}
{283}{}{Hay đấy. Tôi ờ... phải đi rồi.}
{290}{}{Cái gì? Thằng kia! Cút đi! Tao không... Ôi! ĐM.}
{291}{}{Cái gì? Con kia! Cút đi! Tao không... Ôi! ĐM.}
{292}{}{Mẹ kiếp.}
{293}{}{Đừng nói thêm gì nữa.}
{300}{}{Ồ đúng. Tôi không nuốt nổi. Nhiều đoạn hôn nhau quá. Tôi ném nó vào góc tòa nhà kia... không, tòa kia... không... có phải nhà không nhỉ? Có thể tôi để ở chỗ khác... hay tôi ném đi nhỉ? Ôi! Cái đầu tôi!}
{301}{}{Sách? Ồ, quyển đó hả. Ai cử cậu đến? Tôi không chắc phía đó đúng đâu. Đừng có quên khăn giấy đấy.}
{302}{}{Tôi không thể! Chúng là... ồ chết tiệt... cậu có phô mai không? Trốn đi!}
{303}{}{Này! Đâu phải vấn đề của tôi. Tôi biết làm gì chứ? Đấm nhau à? Mấy gã da xanh bé tí, răng chìa nhọn hoắt! ĐM! Đau! Dừng lại!}
{304}{}{Đau đầu thế! Cái gì... đứa nào vừa nói thế?}
{305}{}{Có ích đấy.}
{306}{}{Ừ.}
{310}{}{Cái gì? Cậu chọc tôi đấy à! Cút đi! Tôi đâu có không ổn! Tôi biết nấu ăn! Tôi đâu có nghe thấy giọng nói trong đầu đâu!}
{311}{}{Tôi sẽ- cứt thật! Đm! Chết tiệt! Dừng lại đi. Trật tự! Cái gì?... Được rồi.}
{312}{}{Này! Dừn- đừng... đm.}
{313}{}{Chào.}
{314}{}{Không có gì.}
{320}{}{Này! Tránh xa tôi ra!}
{321}{}{Đừng chạm vào tôi!}
