{100}{}{Bạn thấy một gã gày gò, nhờn mỡ.}
{150}{}{Bạn thấy Flick, đang cật lực gãi chim.}
{151}{}{Bạn thấy một gã bẩn thỉu với khuôn mặt nhăn như táo tàu.}
{200}{}{Biến khỏi đây ngey, đồ đần độn.}
{201}{}{Này đồ đầu thịt! Đúng, mày đấy. Biến khỏi đây ngey.}
{202}{}{Mày bị đần hay seo thế?}
{203}{}{Có dzấn đề gì, hả?}
{204}{}{Cuốn xéo khỏi đây ngey.}
{220}{}{Này nèy, tao là Flick. Mày muốn cái lìn gì thế?}
{221}{}{Giờ thì sao? Mày đang làm lãng phí thời gian của tao đếy.}
{222}{}{Nói cái giọng gì thế hả Flick?}
{223}{}{Ông đang làm cái chó gì ở đây thế?}
{224}{}{Tôi đang đi tìm Vault – ồ đúng rồi, một gã thương gia tên Vic nữa. Biết tìm ở đâu không?}
{225}{}{Tôi muốn trao đổi.}
{240}{}{Vệy đã được chưa, cậu bạn?}
{241}{}{Thật ra là tôi muốn xem lại hàng lần nữa, nếu được.}
{242}{}{Thật ra tôi muốn hỏi một câu.}
{243}{}{Được rồi. Gặp lại sau, Flick.}
{260}{}{Bố bán cái đm nó hàng, sao hả? Tao như kiểu gã Samurai-itan tốt bụng ấy.}
{261}{}{Cái gì cơ?}
{262}{}{Ồ, ừ, ờ... tôi muốn hỏi về thứ khác.}
{263}{}{Ừ, ồ, OK. Chào nhé, Flick.}
{280}{}{Tao chu cấp cho đám paisano chân đất mắt toét.}
{281}{}{Ông cấp đàn piano á?}
{290}{}{Pai-san-o ấy, biết không, lũ nhóc. Đám nhóc của tao.}
{291}{}{Đám nhóc của ông?}
{292}{}{Ồ, tôi không hứng thú lắm với mấy bài nhạc cho lũ trẻ. Để tôi hỏi ông chuyện khác.}
{300}{}{Ờ, chúng nó làm cho tao. Chúng mang đồ về đây. Mấy món nhỏ nhỏ xinh xinh ấy.}
{301}{}{Ừ, không.}
{302}{}{Ồ, OK. Để tôi hỏi ông chuyện khác.}
{303}{}{À, hiểu rồi. Ồ này, tôi không muốn làm đứt ờ, phong cách của ông. Chào.}
{315}{}{Chúng mang những thứ chúng tìm thấy về đây. Mấy món be bé, nhỏ nhắn. Những thứ chả ma nèo cần nữa. Đổi lại, tao chăm lo cho chúng.}
{316}{}{Thỏa thuận nghe có vẻ ổn đấy.}
{325}{}{(Flick nhún vai) Cũng đủ qua ngày.}
{326}{}{Để tôi hỏi ông về chuyện khác vậy.}
{327}{}{Hẳn là lũ trẻ đã mang về cho ông nhiều món hời lắm. Để xem ông có gì nào.}
{328}{}{Chỉ ngó qua thôi. Ồ, chào ông, Flick.}
{340}{}{Mày nói gì đấy? Mày nghĩ tao là thứ pirla ngốc đm nghếch à? loại filio di puttana đần độn? Mày nghĩ tao là thằng hề à? Tao ở đây để làm trò vui chứ gì?}
{341}{}{Ừ, không. Xin lỗi, tôi chỉ tò mò thôi. Để tôi hỏi ông chuyện khác.}
{342}{}{Ờ đúng rồi đấy, đồ đầu cứt. Chẳng gì khiến tao vui hơn là nghe mày rên giãy chết đâu.}
{343}{}{Ồ, nếu ông cứ nổi cơn như thế thì tôi té đây.}
{360}{}{Vault à? Có thể Momma biết đấy, vì tao đếu biết. Nhưng gã Vic thì tao biết. Metzger đang giữ gã porca pistola đấy.}
{361}{}{Vic? Chẻng phải lão đi với mày sao? Đồ biota. Nhưng Momma thì tao biết.}
{362}{}{Metzger là ai?}
{363}{}{Momma là ai?}
{364}{}{Cám ơn. Để tôi hỏi ông chuyện khác.}
{365}{}{Cám ơn, tôi hỏi thế là đủ rồi. Chào.}
{380}{}{Momma mở tiệm đồ ăn ở phía Đông của thị trấn. Qua nghĩa trang là tới. Chỗ đấy đẹp phết, bả có pasta ngon lắm, Mama mia.}
{381}{}{Cám ơn. Còn cái gã Metzger đang giữ Vic thì sao?}
{382}{}{Cám ơn. Để tôi hỏi ông chuyện khác.}
{383}{}{Cám ơn, tôi hỏi thế là đủ rồi. Chào.}
{400}{}{Đúng rồi. Metzger, cái gã stronzo đấy, nghẹo rồi. Tao không biết Vic ra sao nữa.}
{401}{}{Gã Metzger đấy rõ là một rompiballe. Cai quản Hội buôn người. Ở phía Đông thị trấn, ngay trên chỗ Momma. Hắn ta bắt Vic, tao biết mà.}
{402}{}{Cám ơn, còn giờ Momma thì sao?}
{403}{}{Cám ơn. Để tôi hỏi ông chuyện khác.}
{404}{}{Cám ơn, tôi hỏi thế là đủ rồi. Chào.}
