{100}{}{Bạn thấy một gã gày gò, nhờn mỡ.}
{150}{}{Bạn thấy Flick, đang cật lực gãi chim.}
{151}{}{Bạn thấy một gã bẩn thỉu với khuôn mặt nhăn như táo tàu.}
{200}{}{Biến khỏi đây ngey, đồ đần độn.}
{201}{}{Này thịt viên! Đúng, mày đấy. Biến khỏi đây ngey.}
{202}{}{Mày bị đần hay seo thế?}
{203}{}{Có dzấn đề gì, hả?}
{204}{}{Cuốn xéo khỏi đây ngey.}
{220}{}{Này nèy, tao là Flick. Mày muốn cái lìn gì thế?}
{221}{}{Giờ thì sao? Mày đang làm lãng phí thời gian của tao đếy.}
{222}{}{Nói cái giọng gì thế hả Flick?}
{223}{}{Ông đang làm cái chó gì ở đây thế?}
{224}{}{Tôi đang đi tìm Vault – ồ đúng rồi, một gã thương gia tên Vic nữa. Biết tìm ở đâu không?}
{225}{}{Tôi muốn trao đổi.}
{240}{}{Vệy đã được chưa, cậu bạn?}
{241}{}{Thật ra là tôi muốn xem lại hàng lần nữa, nếu được.}
{242}{}{Thật ra tôi muốn hỏi một câu.}
{243}{}{Được rồi. Gặp lại sau, Flick.}
{260}{}{I'm a fuckin' provider, waddya think? I'm like a good Samurai-itan guy.}
{261}{}{Say what?}
{262}{}{Yeah, uh, well... let me ask you something else.}
{263}{}{Uh, oh. OK. Goodbye, Flick.}
{280}{}{I provide fer them little paisanos.}
{281}{}{You provide little pianos?}
{290}{}{Pai-san-o, you know, the kids. My kids.}
{291}{}{Your kids?}
{292}{}{Well, I'm not really interested in music lessons for children. Let me ask you about something else.}
{300}{}{Yeah, well they work for me. They bring me things. Little things. You know.}
{301}{}{Ừ, không.}
{302}{}{Oh, OK. Let me ask you something else then.}
{303}{}{Ah, I see. Well, I don't want to cramp your, uh, style. Goodbye.}
{315}{}{They bring me stuff that they find. Little, little things. Stuff no one ain't usin' no more. In return, I takes care of 'em.}
{316}{}{Sounds like a nice arrangement.}
{325}{}{(Flick shrugs) I get by OK.}
{326}{}{Let me ask you about something else then.}
{327}{}{They must have brought you some real bargains. Let's see what you've got.}
{328}{}{Just checking. Well, goodbye Flick.}
{340}{}{What you talkin' about? You think I'm a fucking stupid pirla? Some dumb filio di puttana? You think I'm some kinda clown? Am I here to amuse you, is that it?}
{341}{}{Uh, no. Sorry, I was just curious. Let me ask you about something else.}
{342}{}{Yeah, that's right, shithead. And nothing's going to amuse me more than your death-throes.}
{343}{}{Well, if you're going to get all huffy about it, I'm leaving.}
{360}{}{Vault huh? Maybe Momma knows about that, 'cause I don't. But that Vic guy - him I know. Metzger's got that porca pistola.}
{361}{}{Vic? Ain't that him with you? You biota. But Momma, her I know.}
{362}{}{Who's Metzger?}
{363}{}{Who's Momma?}
{364}{}{Thanks. Let me ask you something else.}
{365}{}{Thanks, that's all I need to know. Goodbye.}
{380}{}{Momma runs a food place over in da East side a town. Just past the graveyard. Nice place, she got good pasta, Mama mia.}
{381}{}{Thanks, What about that Metzger fellow that's got Vic?}
{382}{}{Thanks. Let me ask you something else.}
{383}{}{Thanks, that's all I need to know. Goodbye.}
{400}{}{That's right. Metzger, that stronzo, he's dead. I don't know what happen to Vic.}
{401}{}{That Metzger, he's a real rompiballe, that one. Runs the Slaver's Guild. East side of town, just north of Momma's. Anyhow, he got Vic, I know.}
{402}{}{Thanks, now what about Momma?}
{403}{}{Thanks. Let me ask you something else.}
{404}{}{Thanks, that's all I need to know. Goodbye.}
