{100}{}{Bạn thấy chủ của The Hole.}
{101}{}{Bạn thấy Frankie, chủ của The Hole.}
{150}{}{Đây có vẻ là người chủ chỗ này.}
{151}{}{Đây là Frankie. Ông ta là chủ quán này.}
{152}{}{[NÓI CHUYỆN]}
{153}{}{Tôi là Frankie và cậu đang ở "The Hole". Quán bar tuyệt nhất trong vòng
 trăm dặm quanh đây! Mọi người mò đến The Hole khi cần phê pha.
 Giờ thì đừng giở trò rắc rối gì, được chứ?}
{154}{}{Tôi nghe rồi.}
{155}{}{Rồi, okay. Sao cũng được.}
{156}{}{Tôi biết sao ông lại gọi chỗ này là "Cái lỗ" rồi.}
{157}{}{Hở?}
{158}{}{Cậu muốn thứ gì?}
{159}{}{Whiskey.}
{160}{}{Gái.}
{161}{}{Giai.}
{162}{}{Thông tin.}
{163}{}{Hôm nay thì không. Chào.}
{164}{}{Wee wee.}
{165}{}{Này! Tốt hơn là câm cái mõm chó lại!}
{166}{}{Không thì sao?}
{167}{}{Lo làm việc của ông và lấy đồ uống cho tôi đi.}
{168}{}{Để tôi rời đi vậy.}
{169}{}{Whiskey có giá $}
{170}{}{ một ly.}
{171}{}{Tiền đây.}
{172}{}{Không được! Đắt quá!}
{173}{}{Sao whiskey của ông lại đắt hơn chỗ Becky nhiều thế?}
{174}{}{Không cám ơn.}
{175}{}{Gì nữa không?}
{176}{}{Đúng vậy.}
{177}{}{Không, cám ơn.}
{178}{}{Cậu không có đủ tiền! Đây có phải chỗ từ thiện đâu!}
{179}{}{Ồ, xin lỗi. Tôi đang cháy túi.}
{180}{}{Tôi sẽ trở lại.}
{181}{}{Muốn gì?}
{182}{}{Whiskey.}
{183}{}{Không gì cả. Tôi đi đây.}
{184}{}{Wahdo a peedee!}
{185}{}{Và đừng vào nữa!}
{186}{}{[ĐI RA]}
{187}{}{Tôi không muốn chứa người như cậu ở chỗ tôi. Biến đi!}
{188}{}{Alright, I'm going.}
{189}{}{Wa.}
{190}{}{Those New Reno families charge an arm and a leg for their booze. I don't know how she does it!}
{191}{}{Well, you should try to find out.}
{192}{}{I could find out.}
{193}{}{I know how she does it.}
{194}{}{I'll just go buy whiskey from her.}
{195}{}{If you find out where she gets her booze, I'll pay you $100.}
{196}{}{OK, I'll find out.}
{197}{}{Nope, not interested.}
{198}{}{So, how does Becky do it? How does she sell her booze so cheap?}
{199}{}{She has a still.}
{200}{}{I don't know yet. I'll come back.}
{201}{}{What? A still! Damn. Hey, here's the $100, and I'll pay you $500 to destroy it. You can use my crowbar, in the back room over there. That'll do a number on her stupid little still!}
{202}{}{I already did.}
{203}{}{OK, I'll destroy it.}
{204}{}{No way. That's too much. I got the information. You handle it.}
{205}{}{No, I have a better idea.}
{206}{}{So, is the still destroyed? Like I said, just use my crowbar on it. That'll really fuck it up fast.}
{207}{}{Yes, it is.}
{208}{}{I have a better idea.}
{209}{}{Nope. I'll let you know when it is.}
{210}{}{Then here's the $500. Thanks.}
{211}{}{Nice doing business with you.}
{212}{}{You know, Frankie, she's just going to build another one.}
{213}{}{Cám ơn, chào.}
{214}{}{Damn! Well, in the mean time she'll have no booze.}
{215}{}{Why fight her, Frankie? Join her.}
{216}{}{Think. Where else can you get liquor?}
{217}{}{What do you mean?}
{218}{}{Buy liquor from her. It's cheaper than New Reno's, so you'll make more money, too.}
{219}{}{I don't want to do this.}
{220}{}{Không có gì.}
{221}{}{Look, I just want her still destroyed. Will you do it?}
{222}{}{Alright, I will.}
{223}{}{No, I won't. Good bye.}
{224}{}{Maybe you're right. I'll talk to her. Thanks.}
{225}{}{Hey, what are friends for?}
{226}{}{Chào.}
{227}{}{Information I do not have.}
{228}{}{Really? How about why Becky's drinks are so much cheaper than yours?}
{229}{}{I thought bartenders knew everything.}
{230}{}{Then I'm in the wrong place. Bye.}
{231}{}{Go talk to Sheila. Hey, Sheila, you got a customer!}
{232}{}{Wait, that's not what I want!}
{233}{}{Cám ơn. Tạm biệt.}
{234}{}{Yeah, I bet. You must have the damnedest time getting men. Try your luck somewhere else, sister. I ain't into no charities.}
{235}{}{Fine! Something else then.}
{236}{}{Why, you little...}
{237}{}{Tôi không cần thứ này của ông!}
{238}{}{I have a room over there. You and I can use it.}
{239}{}{OK.}
{240}{}{No, I didn't mean that!}
{242}{}{Neither were you.}
{243}{}{I might have tried if you knew how to please a woman.}
{244}{}{You were the best I ever had. Really. I mean that.}
{245}{}{I hate to eat and run, but...}
{246}{}{Well, see you later.}
{247}{}{Chào.}
{248}{}{Yeah, whatever. Just clean up after yourself this time, will ya?}
{249}{}{Hey, everyone! Let's hear it for Billy. He's actually getting some!}
{250}{}{You need a mop?}
{251}{}{See ya in five.}
{252}{}{Sheila! Watch the bar!}
{253}{}{Hey, Billy, get outta here!}
{254}{}{Now where were we?}
{255}{}{Where are you, woman?}
{256}{}{Would you get in here?}
{257}{}{Come on, baby.}
{258}{}{Theo tôi.}
{259}{}{No woman stands me up. Get the hell out!}
{260}{}{Được rồi.}
{261}{}{I forgot; I had something else I had to attend to right away. Please forgive me, baby.}
{262}{}{I decided I didn't want to sleep with your ugly ass after all.}
{263}{}{Lucky for you, I'm a nice guy. Just don't pull that crap with me again.}
{264}{}{I won't, baby, I promise.}
{265}{}{I'm gonna put my foot in your ass, woman!}
{266}{}{No one talks to me like that! Die!}
{267}{}{I've given you all the chances I'm gonna give ya. Now get out.}
{268}{}{You're not going in my back room with that trash!}
{300}{}{Hey, I didn't fucking say I'd pay you to kill the bitch. Get the fuck out!}
{350}{}{Wow! Holy fuck. That was amazing.}
{351}{}{Damn, you were pretty good baby.}
{352}{}{Thanks, it was fun. Now get out.}
{353}{}{You were, uhhh... Never mind, get out.}
{354}{}{Well, I've never had worse than that.}
{400}{}{You know baby, you might be hot and all, but you've got lots and lots to learn.}
{410}{}{Baby, I do have work to do you know. I don't just stand around in this spot all day and do nothing.
 Well, okay, so what if I do? That's what I'm here to do.}
{420}{}{Look, I just wanted her still destroyed and you do it. Now beat it.}
