{100}{}{Bạn thấy chủ của The Hole.}
{101}{}{Bạn thấy Frankie, chủ của The Hole.}
{150}{}{Đây có vẻ là người chủ chỗ này.}
{151}{}{Đây là Frankie. Ông ta là chủ quán này.}
{152}{}{[NÓI CHUYỆN]}
{153}{}{Tôi là Frankie và cậu đang ở "The Hole". Quán bar tuyệt nhất trong vòng
 trăm dặm quanh đây! Mọi người mò đến The Hole khi cần phê pha.
 Giờ thì đừng giở trò rắc rối gì, được chứ?}
{154}{}{Tôi nghe rồi.}
{155}{}{Rồi, okay. Sao cũng được.}
{156}{}{Tôi biết sao ông lại gọi chỗ này là "Cái lỗ" rồi.}
{157}{}{Hở?}
{158}{}{Cậu muốn thứ gì?}
{159}{}{Whiskey.}
{160}{}{Gái.}
{161}{}{Giai.}
{162}{}{Thông tin.}
{163}{}{Hôm nay thì không. Chào.}
{164}{}{Wee wee.}
{165}{}{Này! Tốt hơn là câm cái mõm chó lại!}
{166}{}{Không thì sao?}
{167}{}{Lo làm việc của ông và lấy đồ uống cho tôi đi.}
{168}{}{Để tôi rời đi vậy.}
{169}{}{Whiskey có giá $}
{170}{}{ một ly.}
{171}{}{Tiền đây.}
{172}{}{Không được! Đắt quá!}
{173}{}{Sao whiskey của ông lại đắt hơn chỗ Becky nhiều thế?}
{174}{}{Không cám ơn.}
{175}{}{Gì nữa không?}
{176}{}{Đúng vậy.}
{177}{}{Không, cám ơn.}
{178}{}{Cậu không có đủ tiền! Đây có phải chỗ từ thiện đâu!}
{179}{}{Ồ, xin lỗi. Tôi đang cháy túi.}
{180}{}{Tôi sẽ trở lại.}
{181}{}{Muốn gì?}
{182}{}{Whiskey.}
{183}{}{Không gì cả. Tôi đi đây.}
{184}{}{Wahdo a peedee!}
{185}{}{Và đừng vào nữa!}
{186}{}{[ĐI RA]}
{187}{}{Tôi không muốn chứa người như cậu ở chỗ tôi. Biến đi!}
{188}{}{Rồi, đi đây.}
{189}{}{Wa.}
{190}{}{Đám gia tộc ở New Reno bán rượu với giá cắt cổ. Đéo hiểu sao mụ ta bán được rẻ thế!}
{191}{}{Ồ, ông nên thử tìm hiểu xem sao.}
{192}{}{Tôi có thể dò hỏi cho.}
{193}{}{Tôi biết cô ta làm cách nào đấy.}
{194}{}{Thế thôi tôi đến đấy mua whiskey.}
{195}{}{Cậu mà tìm được nguồn lấy rượu của cô ta, tôi sẽ trả $100.}
{196}{}{Được, tôi sẽ đi tìm hiểu.}
{197}{}{Chịu, không quan tâm.}
{198}{}{Sao, thế Becky làm cách nào? Sao mụ ta bán được rượu giá rẻ vl thế?}
{199}{}{Cô ta có lò chưng cất rượu.}
{200}{}{Tôi vẫn chưa rõ. Tôi sẽ quay lại.}
{201}{}{Cái gì? Lò chưng rượu á! Khốn nạn. $100 đây, và tôi sẽ trả thêm $500 để phá nó. Cậu có thể dùng cái xà beng trong phòng đằng kia. Chỉ cần vài nhát là cái lò chết tiệt đấy đi đời!}
{202}{}{Tôi đã làm rồi.}
{203}{}{OK, tôi sẽ phá nó.}
{204}{}{Không đời nào. Quá đáng rồi đấy. Tôi đã lấy được thông tin. Ông đi mà xử lấy.}
{205}{}{Không, tôi có ý này hay hơn.}
{206}{}{Sao, phá được lò chưa? Tôi bảo rồi, cứ cầm xà beng mà phang. Vài nhát là lò nát như tương ngay.}
{207}{}{Rồi.}
{208}{}{Tôi có ý này hay hơn.}
{209}{}{Không. Tôi sẽ nói cho ông biết nó ở chỗ nào.}
{210}{}{Thế thì $500 đây. Cám ơn.}
{211}{}{Rất hân hạnh được giao dịch.}
{212}{}{Ông biết gì không, Frankie, cô ta chỉ cần đi làm cái lò mới là đâu lại vào đấy.}
{213}{}{Cám ơn, chào.}
{214}{}{Mẹ nó chứ! Ồ, ít nhất hiện tại cô ta cũng không có rượu.}
{215}{}{Sao phải đấu đá chứ Frankie? Nhập hội cùng cô ta đi.}
{216}{}{Thử nghĩ xem. Ông còn có thể kiếm rượu ở đâu được?}
{217}{}{Ý cậu là sao?}
{218}{}{Mua rượu từ chỗ Becky chứ sao. Rẻ hơn từ New Reno và ông cũng kiếm được thêm xiền.}
{219}{}{Tôi không muốn làm việc này.}
{220}{}{Không có gì.}
{221}{}{Nghe này, tôi chỉ muốn cái lò đấy đi đời. Có muốn làm không?}
{222}{}{Được rồi, để tôi lo.}
{223}{}{Không đời nào. Tạm biệt.}
{224}{}{Có lẽ cậu nói đúng. Tôi sẽ đi nói chuyện với cô ta. Cám ơn.}
{225}{}{Này, thế bạn bè để làm gì?}
{226}{}{Chào.}
{227}{}{Thông tin tôi không có.}
{228}{}{Thật ư? Thế thì nói về việc sao đồ ở chỗ Becky rẻ hơn của ông nhiều đi?}
{229}{}{Tôi cứ nghĩ là người pha chế biết hết mọi thứ cơ đấy.}
{230}{}{Thế thì tôi đến nhầm chỗ rồi. Chào.}
{231}{}{Đi gặp Sheila ấy. Này, Sheila, có khách!}
{232}{}{Chờ đã, tôi không muốn vậy!}
{233}{}{Cám ơn. Tạm biệt.}
{234}{}{Ồ, chắc rồi. Cô chắc hẳn khó kiếm giai lắm. Đi thử vận may chỗ khác đi, cưng à. Tôi không làm từ thiện đâu.}
{235}{}{Được rồi! Thế nói chuyện khác vậy.}
{236}{}{Sao chứ, đồ nhóc tì...}
{237}{}{Tôi không cần thứ này của ông!}
{238}{}{Tôi có phòng ở đằng kia. Chúng ta có thể vào đó.}
{239}{}{OK.}
{240}{}{Không, tôi không có ý đó!}
{242}{}{Cả cô cũng vậy.}
{243}{}{Đáng ra tôi có thể thử nếu cô biết cách chiều phụ nữ.}
{244}{}{Cô đúng là tuyệt cú mèo. Thật. Tôi thề đấy.}
{245}{}{Tôi không muốn ăn xong rồi chuồn, nhưng...}
{246}{}{Ồ, gặp lại sau nhé.}
{247}{}{Chào.}
{248}{}{Ồ, sao cũng được. Lần này tự đi mà lo thân đi, nhá?}
{249}{}{Này, mọi người! Đến nghe Billy xem. Lão ta có đồ thật này!}
{250}{}{Cần chổi lau sàn không?}
{251}{}{Gặp lại sau năm tiếng.}
{252}{}{Sheila! Trông chừng quầy bar đấy!}
{253}{}{Này, Billy, biến khỏi đây ngay!}
{254}{}{Nào, chúng ta đang nói đến đâu rồi nhỉ?}
{255}{}{Cưng ơi, em đâu rồi?}
{256}{}{Vào đây đi?}
{257}{}{Vào đi cưng ơi.}
{258}{}{Theo tôi.}
{259}{}{Không con đuỹ nào bỏ được tao cả. Cút đi ngay!}
{260}{}{Được rồi.}
{261}{}{Tôi quên mất; tôi có việc gấp phải đi ngay. Thứ lỗi cho tôi, cưng à.}
{262}{}{Tôi quyết định là mình không muốn ngủ với cái đồ xấu xí như cô.}
{263}{}{May mắn cho cô là tôi lành tính đấy. Đừng có giở cái trò mèo này với tôi lần nữa.}
{264}{}{Không đâu, cưng à. Hứa đấy.}
{265}{}{Tao sẽ đạp chân vào lỗ hậu mày đấy!}
{266}{}{Không ai được nói thế với tao cả! Chết đi!}
{267}{}{Tao đã cho mày nhiều cơ hội lắm rồi đấy. Giờ thì biến đi.}
{268}{}{Không được mang cái thứ rác rưởi đó vào phòng của tôi!}
{300}{}{Này, tao có nói là sẽ trả tiền để mày giết con đuỹ đó đâu! Cút khỏi đây ngay!}
{350}{}{Ồ! Đỉnh vl. Tuyệt cmn vời.}
{351}{}{Chết tiệt, tay nghề của cưng giỏi đấy.}
{352}{}{Cám ơn, vui xong rồi thì đi đi.}
{353}{}{Cô ờ... mà thôi, ra đi.}
{354}{}{Ồ, chưa có lần nào tệ như lần này.}
{400}{}{Cưng biết đấy, cưng tuy dáng ngon nhưng mà vẫn còn phải học nhiều lắm.}
{410}{}{Cưng à, tôi vẫn phải làm việc nữa. Tôi đâu chỉ đứng mỗi chỗ này cả ngày đâu.
Ồ, được, tôi làm như vậy á? Đó là công việc của tôi mà.}
{420}{}{Nghe này, tôi chỉ muốn phá cái lò của mụ ta và cậu sẽ làm điều đó. Giờ thì biến đi.}
