{100}{}{You see a big, primitive looking man.}
{101}{}{Người đàn ông này trông có vẻ khỏe mạnh và cảnh giác.}
{110}{}{You see a slender primitive woman.}
{111}{}{Trông cô ta có vẻ khỏe dù có thân hình nhỏ bé.}
{120}{}{You see a strange looking man.}
{121}{}{He seems to be awfully thin.}
{130}{}{You see a ragged looking man.}
{131}{}{Người này trông khá mạnh.}
{140}{}{You see a man in tattered clothing.}
{141}{}{He moves with suggesting speed.}
{150}{}{You see a very grimy woman.}
{151}{}{Trông cô ta cứ như thể chưa tắm bao giờ.}
{160}{}{You see a rather large woman.}
{161}{}{Cô ta trông có vẻ chiến.}
{170}{}{You see a scrawny looking woman.}
{171}{}{Người này chắc chỉ một đòn là gục.}
{200}{}{Chết đi!}
{201}{}{Where you at?}
{202}{}{I'm gunna hurt you.}
{210}{}{I'm going to get your for this!}
{211}{}{Lũ buôn người chết tiệt!}
{212}{}{Mày sẽ trả giá cho chuyện này!}
{220}{}{Leave alone!}
{221}{}{Don't hurt!}
{222}{}{No hurt you!}
{223}{}{I don't fight!}
{230}{}{I recognize that tattoo!}
{231}{}{No, please!}
{232}{}{Please don't kill me!}
{233}{}{I won't fight; don't kill me!}
{234}{}{Please, I don't want to die!}
{235}{}{You're slavers aren't you? Oh, god.}
{245}{}{Yên lặng nào! Chúng đang ở gần rồi.}
{246}{}{Diệt người xấu.}
{247}{}{Không lấy nhà từ tôi.}
{248}{}{Tôi bảo vệ nhà.}
{249}{}{Không được tìm thấy chúng tôi.}
{250}{}{Chúng người xấu.}
{260}{}{Đám buôn người đang đến. Mọi người yên lặng.}
{261}{}{Get ready; I think they're close now.}
{262}{}{Tôi sẽ không bỏ cuộc mà không chiến đấu đâu.}
{263}{}{Chúng sẽ không bao giờ ép chúng ta thành nô lệ được.}
{264}{}{Đám buôn người sẽ phải trả giá vì điều này.}
{265}{}{Không kẻ buôn người nào lấy nhà tôi đi được.}
{270}{}{They no find me.}
{271}{}{Must hide. Must hide.}
{272}{}{Why they want hurt.}
{273}{}{Me scared.}
{274}{}{Me no fight.}
{275}{}{Me want live.}
{276}{}{No hurt family.}
{280}{}{Oh, shit!}
{281}{}{Why are they doing this?}
{282}{}{What about my family?}
{283}{}{I don't want to die.}
{284}{}{I don't want to be a slave.}
{285}{}{I deserve better than this.}
{290}{}{Mày chết giờ!}
{291}{}{Ta giết!}
{292}{}{Mày không làm đau nhà!}
{293}{}{Mày không lấy mất nhà!}
{294}{}{Ta bảo vệ!}
{295}{}{Ta làm đau mày!}
{296}{}{Mày trả giá!}
{300}{}{Kẻ buôn người, ngươi sẽ không cướp được gia đình ta đâu!}
{301}{}{Chết đi, đồ buôn người ghê tởm!}
{302}{}{Mày sẽ phải trả giá, đồ khốn!}
{303}{}{Ta sẽ chiến đấu đến cùng vì gia đình!}
{304}{}{Ngươi sẽ không thoát được đâu!}
{305}{}{Mày sẽ không đưa các bạn ta rời khỏi đây được đâu!}
{310}{}{Ahhh!}
{311}{}{No kill! No kill!}
{312}{}{Stop!}
{313}{}{Heeeelp!}
{314}{}{Run!}
{315}{}{No do that!}
{320}{}{Run for your lives!}
{321}{}{Don't let them catch you!}
{322}{}{Slavers! Run for it!}
{323}{}{Help someone! Please!}
{324}{}{Run for it, Marty!}
{325}{}{Ahhh!}
{326}{}{Stop the insanity!}
{327}{}{We didn't do anything! Leave us alone!}
