{100}{}{You see one of Klamath's Children.}
{101}{}{You see one of Klamath's Children.}
{150}{}{Don't eat me!}
{151}{}{Eeeee! The boogy-monster!}
{152}{}{Daddy says you're a bad person.}
{153}{}{Aieeee! Run away!}
{154}{}{You're scaring me.}
{155}{}{Stop looking at me.}
{156}{}{I'm not supposed to talk to tribals.}
{157}{}{You're just like the Duntons.}
{158}{}{My mom said you'll eat me if I'm bad.}
{159}{}{I'm not afraid of you!}
{160}{}{Help meee!}
{161}{}{It's after me!}
{162}{}{Please don't hurt me!}
{163}{}{Stay away from me!}
{164}{}{Eeeeeeeee!}
{165}{}{I hate you!}
{166}{}{Mommy, mommy, mommy!}
{167}{}{Để tôi yên!}
{168}{}{You stink!}
{170}{}{Hello there.}
{171}{}{Want to play house?}
{172}{}{Do you really poke a bone through your nose?}
{173}{}{How come you're so funny looking?}
{174}{}{My mom says you're primitive.}
{175}{}{Has your tribe stopped eating people?}
{176}{}{Who dressed you so funny?}
{177}{}{I'll bet you're nicer than you look.}
{178}{}{Let's play tag. You're it.}
{179}{}{You don't smell that bad.}
{180}{}{Chú có thấy bạn ma của cháu không?}
{181}{}{I want to travel the world when I'm as old as you.}
{182}{}{You're a nice tribal, not like the others.}
{183}{}{I bet you do bathe.}
{184}{}{You're smarter than Torr.}
{185}{}{Is that blade you have really sharp?}
{186}{}{I want to be just like you when I grow up.}
{187}{}{My dog loves drymeat.}
{188}{}{I've got a shiny pebble.}
{189}{}{Chú có thấy bạn ma của cháu không?}
{190}{}{Can I join your tribe?}
{191}{}{You're nice.}
{192}{}{You look funny.}
{193}{}{Whatcha wearing?}
{194}{}{I want a brahmin ride!}
{195}{}{Are you from far away?}
{196}{}{Weeee! Ha ha ha!}
{197}{}{Don't leave!}
{198}{}{Do you have some food?}
{199}{}{Am I bothering you?}
{200}{}{Where ya going?}
{201}{}{Can I come with you?}
{202}{}{How old are you?}
{203}{}{What's your name?}
{204}{}{Do you like kids?}
{205}{}{What is that?}
{206}{}{Do you wanna play a game?}
{207}{}{Whatcha doing?}
{208}{}{Have you seen any bugs?}
{209}{}{Where did you get that?}
{210}{}{Can I have that?}
{211}{}{What do you do?}
{212}{}{I can run fast. Wanna see?}
{213}{}{Watch me! Watch me!}
{214}{}{Mommy says I talk too much.}
{215}{}{Where is your home?}
{216}{}{Heeee! Heeee!}
{217}{}{Are you gonna stay here?}
{218}{}{Do you have kids?}
{219}{}{Why did you come here?}
{220}{}{I like you.}
{221}{}{Do you like me?}
{222}{}{Are you married?}
{223}{}{One, two, three... Weee!}
{1000}{}{Trưởng lão}
{1001}{}{Người mở làng}
{1002}{}{Cụ tổ từ Vault}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Cứu tinh}
{1007}{}{Thầy cúng}
{1008}{}{Hakunin}
{1009}{}{Bột chữa thương}
{1010}{}{Cầu}
{1011}{}{Mynoc}
{1100}{}{Trưởng lão là mẹ cậu đồng thời là trưởng làng.}
{1101}{}{Cụ tổ vĩ đại đã truyền kiến thức cho chúng ta.}
{1102}{}{Người đầu tiên chiến đấu và chiến thắng cái xấu.}
{1103}{}{Đó là ngôi làng xinh đẹp của chúng ta.}
{1104}{}{That's trading outpost a few days east of here.}
{1105}{}{Vault là thiên đường.}
{1106}{}{Cậu là Cứu tinh.}
{1107}{}{He heals us with his herbs and magic. He is in the north part
 of our village.}
{1108}{}{He heals us with his herbs and magic. He is in the north part
 of our village.}
{1109}{}{Đây là bột chữa thương có thể chữa lành cho anh, nhưng sẽ khiến
anh thấy buồn ngủ.}
{1110}{}{Cây Cầu Lớn dẫn ra ngoài làng ở phía Nam.}
{1111}{}{Anh ta canh gác cây cầu dẫn vào làng chúng ta.}
