{100}{}{Bạn thấy một cái cửa gỗ.}
{101}{}{Bạn thấy một cái cửa sắt.}
{102}{}{You see a study door with a lock which can be picked with
 lockpicks and a highly explosive trap in the doorframe, which
 you may be able to pry open.}
{103}{}{Bạn thấy một cánh cửa kiên cố có khóa và bẫy
thuốc nổ nhạy trên khung cửa, mà bạn có thể
thử cậy mở.}
{104}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa
và bẫy thuốc nổ nhạy trên khung cửa, mà bạn có thể
thử cậy mở.}
{105}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét và
bẫy thuốc nổ nhạy trên khung cửa, mà bạn có thể thử cậy mở.}
{106}{}{You see a study door with a lock which can be picked with
 lockpicks and a trap in the doorframe, which you may be able to
 pry open.}
{107}{}{Bạn thấy một cánh cửa kiên cố có khóa và bẫy
trên khung cửa, mà bạn có thể thử cậy mở.}
{108}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa
và bẫy trên khung cửa, mà bạn có thể thử cậy mở.}
{109}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét
và bẫy trên khung cửa, mà bạn có thể thử cậy mở.}
{110}{}{You see a study door with a lock which can be picked with
 lockpicks and a cut wire in the doorframe, which you may be
 able to pry open.}
{111}{}{Bạn thấy một cánh cửa kiên cố có khóa và đoạn dây
thép bị đứt trên khung cửa, mà bạn có thể thử cậy mở.}
{112}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa
và đoạn dây thép bị đứt trên khung cửa, mà bạn có thể thử
cậy mở.}
{113}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét
và đoạn dây thép bị cắt trên khung cửa, mà bạn có thể
thử cậy mở.}
{114}{}{You see a study door with a lock which can be picked with
 lockpicks, which you may be able to pry open.}
{115}{}{Bạn thấy một cánh cửa kiên cố có khóa mà bạn có thể
thử cậy mở.}
{116}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có
khóa mà bạn có thể thử cậy mở.}
{117}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ,
rỉ sét mà bạn có thể thử cậy mở.}
{118}{}{You see a study door with a lock which can be picked with
 lockpicks and a highly explosive trap in the doorframe.}
{119}{}{Bạn thấy một cánh cửa kiên cố có khóa và bẫy
thuốc nổ nhạy trên khung cửa.}
{120}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa
và bẫy thuốc nổ nhạy trên khung cửa.}
{121}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét
và bẫy thuốc nổ nhạy trên khung cửa.}
{122}{}{You see a study door with a lock which can be picked with
 lockpicks and a trap in the doorframe.}
{123}{}{Bạn thấy một cánh cửa kiên cố có khóa và bẫy
trên khung cửa.}
{124}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa
và bẫy trên khung cửa.}
{125}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét
và bẫy trên khung cửa.}
{126}{}{You see a study door with a lock which can be picked with
 lockpicks and a cut wire in the doorframe.}
{127}{}{Bạn thấy một cánh cửa kiên cố có khóa và đoạn dây thép
bị đứt trên khung cửa.}
{128}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa và
đoạn dây thép bị đứt trên khung cửa.}
{129}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ, rỉ sét và
đoạn dây thép bị cắt trên khung cửa.}
{130}{}{You see a study door with a lock which can be picked with
 lockpicks.}
{131}{}{Bạn thấy một cánh cửa kiên cố có khóa.}
{132}{}{Bạn thấy một cánh cửa kiên cố có vẻ như không có khóa.}
{133}{}{Bạn thấy một cánh cửa kiên cố với ổ khóa cũ kĩ,
rỉ sét.}
{134}{}{You see a damaged door with a lock which can be picked with
 lockpicks and a highly explosive trap in the doorframe.}
{135}{}{Bạn thấy một cánh cửa bị hư hại có khóa và bẫy
thuốc nổ nhạy trên khung cửa.}
{136}{}{Bạn thấy một cánh cửa bị hư hại có vẻ như không có khóa và
bẫy thuốc nổ nhạy trên khung cửa.}
{137}{}{Bạn thấy một cánh cửa bị hư hại với ổ khóa cũ kĩ, rỉ sét và
bẫy thuốc nổ nhạy trên khung cửa.}
{138}{}{You see a damaged door with a lock which can be picked with
 lockpicks and a trap in the doorframe.}
{139}{}{Bạn thấy một cánh cửa bị hư hại có khóa và bẫy trên
khung cửa.}
{140}{}{Bạn thấy một cánh cửa bị hư hại có vẻ như không có khóa và
bẫy trên khung cửa.}
{141}{}{Bạn thấy một cánh cửa bị hư hại với ổ khóa cũ kĩ, rỉ sét và
bẫy trên khung cửa.}
{142}{}{You see a damaged door with a lock which can be picked with
 lockpicks and a cut wire in the doorframe.}
{143}{}{Bạn thấy một cánh cửa bị hư hại có khóa và đoạn dây thép
bị đứt trên khung cửa.}
{144}{}{Bạn thấy một cánh cửa bị hư hại có vẻ như không có khóa và
đoạn dây thép bị đứt trên khung cửa.}
{145}{}{Bạn thấy một cánh cửa bị hư hại với ổ khóa cũ kĩ, rỉ sét và
đoạn dây thép bị cắt trên khung cửa.}
{146}{}{You see a damaged door with a lock which can be picked with
 lockpicks.}
{147}{}{Bạn thấy một cánh cửa bị hư hại có khóa.}
{148}{}{Bạn thấy một cánh cửa bị hư hại có vẻ như không có khóa.}
{149}{}{Bạn thấy một cánh cửa bị hư hại với ổ khóa cũ kĩ, rỉ sét.}
{150}{}{You see an old door with a lock which can be picked with
 lockpicks and a highly explosive trap in the doorframe.}
{151}{}{Bạn thấy một cánh cửa cũ có khóa và bẫy
thuốc nổ nhạy trên khung cửa.}
{152}{}{Bạn thấy một cánh cửa cũ có vẻ như không có khóa và
bẫy thuốc nổ nhạy trên khung cửa.}
{153}{}{Bạn thấy một cánh cửa cũ với ổ khóa cũ kĩ, rỉ sét và
bẫy thuốc nổ nhạy trên khung cửa.}
{154}{}{You see an old door with a lock which can be picked with
 lockpicks and a trap in the doorframe.}
{155}{}{Bạn thấy một cánh cửa cũ có khóa và bẫy trên
khung cửa.}
{156}{}{Bạn thấy một cánh cửa cũ có vẻ như không có khóa và
bẫy trên khung cửa.}
{157}{}{Bạn thấy một cánh cửa cũ với ổ khóa cũ kĩ, rỉ sét và
bẫy trên khung cửa.}
{158}{}{You see an old door with a lock which can be picked with
 lockpicks and a cut wire in the doorframe.}
{159}{}{Bạn thấy một cánh cửa cũ có khóa và đoạn dây thép
bị đứt trên khung cửa.}
{160}{}{Bạn thấy một cánh cửa cũ có vẻ như không có khóa và
đoạn dây thép bị đứt trên khung cửa.}
{161}{}{Bạn thấy một cánh cửa cũ với ổ khóa cũ kĩ, rỉ sét và
đoạn dây thép bị cắt trên khung cửa.}
{162}{}{You see an old door with a lock which can be picked with
 lockpicks.}
{163}{}{Bạn thấy một cánh cửa cũ có khóa.}
{164}{}{Bạn thấy một cánh cửa cũ có vẻ như không có khóa.}
{165}{}{Bạn thấy một cánh cửa với ổ khóa cũ kĩ, rỉ sét.}
{166}{}{Bạn bị dính bẫy và đã nhận }
{167}{}{ điểm sát thương.}
{168}{}{ đã dính bẫy và nhận }
{169}{}{ điểm sát thương.}
{170}{}{Bạn khéo léo cậy khóa trên cửa.}
{171}{}{Kĩ năng kém cỏi của bạn đã làm kẹt ổ khóa trên cửa.}
{172}{}{Bạn không cậy được khóa trên cánh cửa này.}
{173}{}{ khéo léo cậy khóa trên cửa.}
{174}{}{do thiếu kĩ năng đã làm kẹt ổ khóa trên cửa.}
{175}{}{ không cậy được khóa trên cửa.}
{176}{}{Bạn đã phá khóa khỏi cửa.}
{177}{}{Bạn bị căng cơ lưng khi cố gắng phá khóa và
nhận một điểm sát thương.}
{178}{}{Bạn bị căng cơ lưng khi cố gắng phá khóa và
nhận }
{179}{}{ điểm sát thương.}
{180}{}{Bạn quá yếu để có thể phá khóa.}
{181}{}{ đã phá khóa khỏi cửa.}
{182}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận một
 điểm sát thương.}
{183}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận }
{184}{}{ điểm sát thương.}
{185}{}{ quá yếu để có thể phá khóa.}
{186}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận một
 điểm sát thương.}
{187}{}{ bị căng cơ lưng khi cố gắng phá khóa và nhận}
{188}{}{ điểm sát thương.}
{189}{}{Bạn khéo léo khóa cửa.}
{190}{}{Bạn không khóa được cửa.}
{191}{}{ khéo léo khóa cửa.}
{192}{}{ không khóa được cửa.}
{193}{}{Thuốc nổ còn chẳng làm xước nổi cửa.}
{194}{}{Bạn tìm thấy bẫy trên cửa.}
{195}{}{Bạn không tìm thấy bẫy trên cửa.}
{196}{}{Bạn khéo léo vô hiệu hóa bẫy.}
{198}{}{Bạn không vô hiệu hóa được bẫy.}
{199}{}{ tìm thấy bẫy trên cửa.}
{200}{}{ không tìm thấy bẫy trên cửa.}
{201}{}{ khéo léo vô hiệu hóa bẫy.}
{202}{}{ không vô hiệu hóa được bẫy.}
{203}{}{Cửa trông như bị khóa.}
{204}{}{Bạn để ý thấy có bẫy trên khung cửa.}
{205}{}{ để ý thấy có bẫy trên khung cửa.}
{206}{}{Bạn không thể đặt được bẫy trên cánh cửa này, vì
 cửa đang mở.}
{207}{}{ không thể đặt được bẫy trên cánh cửa này, vì cửa
 đang mở.}
{208}{}{Bạn khéo léo đặt bẫy trên khung cửa.}
{209}{}{Bạn không đặt được bẫy đúng cách trên khung cửa.}
{210}{}{ khéo léo đặt bẫy trên khung cửa.}
{211}{}{ không đặt được bẫy đúng cách trên khung cửa.}
{212}{}{This door does not unlock here.}
{213}{}{The door won't budge.}
