call ..\p SCBGRD
call ..\p SCBRAHMN
call ..\p SCBUSTER
call ..\p SCCARGRD
call ..\p SCCARKID
call ..\p SCCARLSN
call ..\p SCCGTGRD
call ..\p SCCHEAT
call ..\p SCCOP
call ..\p SCDOCJUB
call ..\p SCDOROTH
call ..\p SCDRVPAY
call ..\p SCDTHCLA
call ..\p SCDUPPO
call ..\p SCDUSTY
call ..\p SCELISE
call ..\p SCENLONE
call ..\p SCFELIX
call ..\p SCFERGUS
call ..\p SCGGCAP
call ..\p SCGOND
call ..\p SCGTEGRD
call ..\p SCGUNTHR
call ..\p SCHAL
call ..\p SCHENRY
call ..\p SCHOSS
call ..\p SCKARL
call ..\p SCLENNY
call ..\p SCMERK
call ..\p SCMIKEY
call ..\p SCMIRA
call ..\p SCMRKGRD
call ..\p SCOFJACK
call ..\p SCOSWALD
call ..\p SCPEAON
call ..\p SCRATCH
call ..\p SCRAWPAT
call ..\p SCROBO
call ..\p SCRONDO
call ..\p SCSALBOB
call ..\p SCSHERIF
call ..\p SCSKEETE
call ..\p SCSLAVES
call ..\p SCSLVGRD
call ..\p SCSLVOVR
call ..\p SCTOTO
call ..\p SCVORTIS
call ..\p SCWESGRD
call ..\p SCWESTIN
call ..\p SCWRHAND
call ..\p SICLSDOR
call ..\p SICMPWES
call ..\p SIDSHELF
call ..\p SIDTBL
call ..\p SIELNOBJ
call ..\p SIEMTR
call ..\p SIEXIT
call ..\p SIFAKHLO
call ..\p SIFFIELD
call ..\p SIGCAOBJ
call ..\p SIHISHOL
call ..\p SIKDOOR
call ..\p SILOCKER
call ..\p SIMBOX
call ..\p SIMSERUM
call ..\p SIPAINT
call ..\p SIPTBOX
call ..\p SIRAGOBJ
call ..\p SISHELF1
call ..\p SISHELF2
call ..\p SISHELF3
call ..\p SISLVDOR
call ..\p SITERM
call ..\p SIVDOR
call ..\p SIWESHOL
call ..\p SSCOMP
call ..\p SSCRPDOR
call ..\p SSEMIEN1
call ..\p SSEMIENT
call ..\p SSEMIWE1
call ..\p SSEMIWES
call ..\p SSEMTN2
call ..\p SSFLXDOR
call ..\p SSFRGDOR
call ..\p SSGUNDOR
call ..\p SSROPE
call ..\p SSSIGN
call ..\p SSSTAT
call ..\p STCARATK
