{100}{}{Õ Jordan, aki szokásához híven a dárdáját forgatja.} 
{101}{}{Õ Jordan, aki szokásához híven a dárdáját forgatja.}
{102}{}{Sok szerencsét! Tõled függ a falu élete.}
{103}{}{Kiválasztott, ahogy azzal a dárdával bánsz, könnyû préda leszel a gekkók számára. Mutathatok neked néhány fogást.}
{104}{}{Rendben.}
{105}{}{Nem, kösz.}
{106}{}{Eltart majd egy darabig.}
{107}{}{Gyorsan tanulsz! Úgy látszik, mindent a fejedbe véstél, amit mutattam neked.}
{108}{}{Köszönöm, Jordan, sokat segítettél.}