{100}{}{Õ Jordan, aki szokása szerint a dárdáját forgatja.} 
{101}{}{Õ Jordan, aki szokása szerint a dárdáját forgatja.}
{102}{}{Sok szerencsét! Tõled függ a falu élete.}
{103}{}{Kiválasztott, ahogy azzal a dárdával bánsz, könnyû préda leszel a gekkók számára. Mutathatok neked néhány fogást.}
{104}{}{Rendben.}
{105}{}{Nem, kösz.}
{106}{}{Egy kis idõbe fog telni.}
{107}{}{Jó tanuló vagy. Úgy látszik, mindent megtanultál, amit mutattam neked.}
{108}{}{Köszönöm, Jordan, sokat segítettél.}