{100}{}{Morlist látod, a nagynénédet, aki sohasem szeretett téged.}
{101}{}{Miért zavarsz, unokaöcsém? Nem látod, hogy most nem érek rá?}
{301}{}{Miért zavarsz, unokahúgom? Nem látod, hogy most nem érek rá?}
{102}{}{Hmm, rendben. Bocsánat.}
{103}{}{Mi az? Tudod, hogy nagyon sok dolgom van!}
{104}{}{Hát, Mynoc azt mondta...}
{105}{}{Mit mondott Mynoc? Ki vele, kölyök!}
{106}{}{Azt, hogy, hát, talán van néhány kovaköved.}
{107}{}{Van. Talán akarsz egyet?}
{108}{}{Hát igen...}
{109}{}{Na, figyelj rám szépen... Három zsák gyógyító porra van szükségem. Rossz idõk jönnek, és fel akarok készülni. Hozdd el, amit akarok, és megkaphatod a kovakövet. Gyerünk, lódulj!}
{110}{}{Igen, nénikém!}
{111}{}{Ne fecséreld az idõmet! Megvannak a gyógyító porok?}
{112}{}{Igen, itt vannak.}
{113}{}{Még nincsenek.}
{114}{}{Itt a kovakõ. Most tûnj innen! Nincs idõm csevegni.}
{115}{}{Köszönöm, Morlis nagynéni.}
{116}{}{Újfent csak fecsérled az idõmet, hitvány unokaöcs! Hogy lehettél pont te a Kiválasztott?}
#sajnos az öcs egy cs (bass)
{117}{}{Igenis, Morlis nagynéni.}
{118}{}{Öö, Morlis nagynéni, itt van mind a három.}

{150}{}{Morlis nagynéni, egy nagyon veszélyes küldetésre indulok a falu megmentéséért. A túlélési esélyeim sokkal jobbak lennének, ha megtarthatnám a gyógyító porokat, te pedig ideadnád a kovakövet. Egyetértesz?}
{151}{}{Mit csinálsz, fiam? Egy Kiválasztott nem viselkedhet így. Takarodj a szemem elõl!}
{152}{}{Ha ez a kovakõ olyan fontos, hogy bemocskolod érte a Kiválasztott nevet, hát tessék. Most pedig tûnés a szemem elõl!}
{153}{}{Igenis, Morlis nagynéni.}
{154}{}{Nos... Jól van. Itt a kovakõ. Biztonságos utat kívánok, gyermekem!}
{155}{}{Nem. Ne fecséreld az idõm, és szedd a sátorfádat!}
{156}{}{Igen, Morlis nagynéni.}


# new add on stuff for time limit
{200}{}{Visszatértél hát... Megtaláltad a szent 13-ast?}
{201}{}{Nem, Morlis nagynéni, én...}
{202}{}{Akkor tûnj el innen, és folytasd a keresést! Tõled függ az életünk!}
{203}{}{Igenis, Morlis nagynéni.}
{204}{}{Szóval újra itt vagy... Még mindig sikertelen a küldetésed?}
{205}{}{Igen, Morlis nagynéni, de...}
{206}{}{Akkor tûnj innen, és ne gyere vissza, amíg nem jársz sikerrel! Miért fecséreled az idõmet azzal, hogy visszajössz ide, amikor a keresésre kéne fordítanod!?}
{207}{}{Igenis, Morlis nagynéni.}
{208}{}{A tény, hogy itt állsz, azt bizonyítja, hogy megcsináltad a küldetést. Ugye nem fecsérelnéd arra az idõt, hogy üres kézzel térj vissza?}
{209}{}{Igen, Morlis nagynéni. Vagyis nem, Morlis nagynéni. Öö... Most mennem kell, Morlis nagynéni.}
{210}{}{Tehát ismét itt állsz elõttem. Megint üres kézzel jöttél?}
{211}{}{Igen, Morlis nagynéni.}
{212}{}{Figyelj, }
{213}{}{. az emberek haldokolnak, a marhák pusztulnak, a termés pedig elenyészik. Mindenki vagy éhes, vagy beteg, vagy mindkettõ. Az idõ sürget. Ha rövidesen nem találod meg az ÉLET-et, eljön a végzetünk. Értesz engem?}
{214}{}{Igen, Morlis nagynéni.}
{215}{}{Akkor indulj, és keresd meg az ÉLET-et! Tõled függ az életünk!}
{216}{}{Igen, Morlis nagynéni.}