{100}{}{A híd őrzőjét látod.}
{101}{}{Mynoc, a híd őrzője.}
{150}{}{A falu nagy harcosa áll előtted, kezében dárdával.}
{151}{}{[Beszéd]}
{152}{}{Üdv, Kiválasztott. Indulsz az ÉLET nyomába?}
{153}{}{Igen.}
{154}{}{Igen. De mielőtt elmegyek, szeretnék feltenni néhány kérdést.}
{155}{}{Még nem. Csak körülnézek egy kicsit.}
{156}{}{Hát, talán figyelnek az istenek.}
{157}{}{Köszönöm az információt, viszlát!}
{158}{}{Mit akarsz tudni?}
{159}{}{Mit tudnál mondani a kereskedőkről, akik a falunkkal üzletelnek?}
{160}{}{Mit tudnál mondani erről a menedékből való tárgyről?}
{161}{}{Hagyjuk, viszlát!}
{162}{}{Nagyon jó, de ne pocsékolj túl sok időt! Az ÉLET nélkül halálra vagyunk ítélve.}
{163}{}{Tudom, ne aggódj... Már kezembe vettem a dolgot.}
{164}{}{Miért?}
{165}{}{Mennem kell. Viszlát!}
{166}{}{A kereskedők Klamathból jönnek kéthavonta. Most vagy egy hónapig nem fognak jönni, de Klamath csak pár napra van innen keleti irányban.}
{167}{}{Köszönöm. Viszlát!}
{168}{}{Mit tudsz mondani erről a tárgyról, ami a menedékből származik?}
{169}{}{Egy acél vizespalacknak néz ki. Talán az istenek küldték előjelként.}
{170}{}{Meg tudnád mondani, ki hozta ezt a faluba?}
{171}{}{Köszönöm. Mennem kell. Viszlát!}
{172}{}{Remélem, sikerül.}
{173}{}{A magabiztosságod miatt kell szenvednünk! Viszlát!}
{174}{}{Viszlát!}
{175}{}{Miért? Nézz körbe... a falu pusztul. A kertek elhervadnak, a gyerekek és öregek elpusztulnak. El kell hoznod az Édent, mielőtt túl késő lenne!}
{176}{}{Rendben, megoldom. Viszlát!}
{177}{}{Én vagyok a Kiválasztott... azt csinálom, ami nekem jólesik. Viszlát!}
{178}{}{A nevére nem emlékszem, de öreg volt és hangos - túl hangos rendes ember létére - viszont sok dolgot tudott. Klamathból jött, keletről, mint már mondottam.}
{179}{}{Köszönöm az információt, viszlát!}
{180}{}{Még mindig itt vagy? Meg kell találnod az ÉLET-et. Az, hogy itt állsz, nem segít rajtunk.}
{181}{}{Te csak törődj a kis hidaddal, barátom! Tudom én, mit csinálok.}
{182}{}{Éppen most indulok. Viszlát, barátom!}
{183}{}{Többet nem beszélek veled, parancsolgatós disznó!}
{184}{}{Szeretnék még kérdezni valamit.}
{185}{}{Ez gyors volt! Megtaláltad a Szent 13-as Menedéket?}
{186}{}{Igen.}
{187}{}{Nem, még nem.}
{188}{}{Megtaláltad? Csodálatos! Elhoztad az ÉLET-et?}
{189}{}{Nem.}
{190}{}{Nem. Még nem beszéltem a Menedék lakóival.}
{191}{}{Nem hiszem, hogy ez rád tartozna, barátom.}
{192}{}{Nem-e? Kiválasztott, mióta elmentél, három idős ember meghalt. Nem szabad több időt veszítened!}
{193}{}{Meg fogom találni, ne aggódj!}
{194}{}{Unom már az állandó parancsolgatást!}
{195}{}{Hát miért velem beszélsz? Beszélj velük, és szerezd meg az ÉLET-et!}
{196}{}{Fogok is... még időben vagyok, barátom.}
{197}{}{Unom már az állandó parancsolgatást!}
{198}{}{Mi újság az ÉLET-tel, Kiválasztott?}
{199}{}{Megtaláltam a Menedéket!}
{200}{}{Képtelen voltam megtalálni a 13-as Menedéket.}
{201}{}{Nézzétek csak, itt a Kiválasztott!}
{202}{}{Helló!}
{203}{}{Pofa be!}
{204}{}{Feltehetek egy kérdést?}
{205}{}{Nem, most nincs időm veled beszélgetni.}
{206}{}{Jól van. Viszlát!}
{207}{}{Ó, hát, majd később találkozunk.}
{208}{}{Dögölj meg!}
{209}{}{Üdvözöllek, idióta! Látod hidat? Átmész, leszel óvatos! Híd veszélyes. Nem leesni, oké?}
{210}{}{Umm... Mi?}
{211}{}{Nyomorult! Nem törődtél a faluval!}
{212}{}{Elárultál minket! Ezért most meghalsz!}
{213}{}{Elárultad a saját embereidet.}
{214}{}{Miért csináltad ezt?}
{215}{}{A Törzsfő tévedett. Te gonosz ember vagy.}
{300}{}{Az apám megtanított rá, hogyan csináljak erősebb pengéket a többinél. Hozz egy kovakövet, és megélezem a te dárdádat is. Szükséged lesz rá a vadonban.}
{301}{}{Hol találhatnék kovakövet?}
{302}{}{Azt mondták, Morlis nagynénédnél van egy. Mivel olyan rossz természetű, ezért szerintem senki sem kérte el tőle. Persze, a banya majd biztosan akar valamit cserébe.}
{303}{}{Kösz, viszlát!}
{304}{}{Beszéltél a nagynénéddel a kovakőről?}
{305}{}{Igen, itt van.}
{306}{}{Még nem.}
{307}{}{Ez egy szép darab. Add ide a dárdát!}
{308}{}{Tessék.}
{309}{}{Azt hiszem, nincs dárdám.}
{310}{}{Most tedd a darabokat úgy, hogy...}
{311}{}{Kiválasztott lándzsa nélkül? Na, akkor adok egyet a saját dárdáim közül. Fogjunk hozzá...}
{312}{}{Tessék az új dárdád...}
{313}{}{Köszönöm, barátom... ez sokat fog segíteni.}
{314}{}{Igen, de csodálkozom a dárdádon. Kicsit másképpen néz ki, mint a többi.}
{400}{}{Üdvözöllek itthon, Kiválasztott! Megtaláltad a Menedéket? Elhoztad az ÉLET-et?}
{401}{}{Én nem talál még meg.}
{402}{}{Nem, még nem találtam meg.}
{403}{}{Nem vagyok olyan hangulatban, hogy válaszoljak a kérdéseidre. Viszlát!}
{404}{}{A dolgok rosszul mennek, Kiválasztott. A szárazság egyre nagyobb, és a termés biztosan tönkremegy. Megpróbáljuk megmenteni, amit tudunk.}
{405}{}{Miért nem keresked faluval másik?}
{406}{}{Csinálni legjobb tudásból. Megtalálni ÉLET. Visszatérni én.}
{407}{}{Miért nem üzletelünk a többi faluval az ételért, amire szükségünk van? }
{408}{}{Ha megtalálom az ÉLET-et, visszatérek.}
{409}{}{Mi csak egyszerű emberek vagyunk, és kevés árunk van kereskedésre. Az a kevés város, amikkel kapcsolatban vagyunk, nem mutatnak túl nagy érdeklődést irántunk.}
{410}{}{Érteni.}
{411}{}{Értem.}
{412}{}{Te vagy az egyetlen reménységünk, Kiválasztott. Kérlek ne bukj el!}
{413}{}{Örülök, hogy látlak, Kiválasztott. Hogy halad a küldetés?}
{414}{}{Én még keres.}
{415}{}{Még keresem az ÉLET-et.}
{416}{}{Nem akarok beszélni róla.}
{417}{}{Sietned kell! A dolgok egyre rosszabbul állnak. Hamarosan elfogy az ételünk. Aggódom Arroyo jövője miatt.}
{418}{}{Kiválasztott! Kérlek, mondd, hogy sikerült a küldetés! A falu, és az emberek egyre csak pusztulnak.}
{419}{}{Nem, még keresek én.}
{420}{}{Nem, még keresek.}
{421}{}{Hogy mennek a dolgok?}
{422}{}{Sajnálom, Kiválasztott, de meg kell kérdeznem, bízhatunk-e benned. Az embereink élete a te kezedben van. Kérlek, találd meg a szent tizenhármast, és térj vissza az ÉLET-tel!}
{423}{}{A termés tönkrement, a brahminok elpusztulnak, már mindenki éhezik. Gyerekeink sírása az éjszakában senkit sem hagy aludni. A helyzetünk kezd reménytelenné válni.}
{424}{}{Én folytat keresés.}
{425}{}{Megteszem, amit tudok.}
{426}{}{Ismét visszatértél, Kiválasztott. Remélem, nem üres kézzel!}
{427}{}{Én sajnál, nem talál még ÉLET.}
{428}{}{Sajnálom, de még nem találtam meg az ÉLET-et.}
{429}{}{Elég ebből!}
{430}{}{Amíg te itt sétálgatsz, az emberek haldokolnak. Keresd az ÉLET-et máshol, ne gyere folyton vissza ide!}
{500}{}{Beszéltél már a Bölccsel?}
{1000}{}{Törzsfőnök}
{1001}{}{Alapító}
{1002}{}{Menedéklakó}
{1003}{}{Arroyo}
{1004}{}{Kalmath}
{1005}{}{Menedek}
{1006}{}{Kiválasztott}
{1007}{}{Sámán}
{1008}{}{Hakunin}
{1009}{}{Gyógyító por}
{1010}{}{Hid}
{1011}{}{Mynoc}
{1100}{}{A törzsfő a te édesanyád és a vezetőnk.}
{1101}{}{Ő a mi nagyszerű ősünk, neki köszönhetjük a tudást.}
{1102}{}{Ő volt az, aki először küzdött meg sikeresen a káosszal.}
{1103}{}{Ez a mi szépséges falunk.}
{1104}{}{Kereskedelmi csomópont néhány napi járóföldre keleti irányban.}
{1105}{}{A Menedék maga a mennyország.}
{1106}{}{TE vagy a Kiválasztott.}
{1107}{}{Ő a növényeivel és a mágiájával gyógyít bennünket. A falu északi részében megtalálod.}
{1108}{}{Ő a növényeivel és a mágiájával gyógyít bennünket. A falu északi részében megtalálod.}
{1109}{}{Az egy mágikus por, amely ugyan meggyógyít, de egyúttal el is álmosít.}
{1110}{}{A Nagy Híd dél felé van a falunktól.}
{1111}{}{Ez én lennék.}
