{100}{}{A híd ?rz?jét látod.}
{101}{}{Mynoc, a híd ?rz?je.}
{150}{}{A falu nagy harcosa áll el?tted, kezében dárdával.}
{151}{}{[Beszélgetés]}
{152}{}{Üdv, Kiválasztott. Indulsz az ÉLET nyomába?}
{153}{}{Igen.}
{154}{}{Igen. De miel?tt elmegyek, szeretnék feltenni néhány kérdést.}
{155}{}{Még nem. Csak körülnézek egy kicsit.}
{156}{}{Hát, talán figyelnek az istenek.}
{157}{}{Köszönöm, viszlát!}
{158}{}{Mit akarsz tudni?}
{159}{}{Mit tudnál mondani a keresked?kr?l, akik a falunkkal üzletelnek?}
{160}{}{Mit tudnál mondani err?l a menedékb?l való tárgyr?l?}
{161}{}{Hagyjuk, viszlát!}
{162}{}{Nagyon jó, de ne pocsékolj túl sok id?t! Az ÉLET nélkül halálra vagyunk ítélve.}
{163}{}{Tudom, ne aggódj... Már kezembe vettem a dolgot.}
{164}{}{Miért?}
{165}{}{Mennem kell. Viszlát!}
{166}{}{A keresked?k Klamathból jönnek kéthavonta. Most vagy egy hónapig nem fognak jönni, de Klamath csak pár napra van innen keleti irányban.}
{167}{}{Köszönöm. Minden jót!}
{168}{}{Mit tudsz mondani err?l a tárgyról, ami a menedékb?l származik?}
{169}{}{Egy acél vizespalacknak néz ki. Talán az istenek küldték el?jelként.}
{170}{}{Meg tudnád mondani, ki hozta ezt a faluba?}
{171}{}{Thank you. I must be going. Goodbye.}
{172}{}{Remélem, sikerül.}
{173}{}{A magabiztosságod miatt kell szenvednünk! Viszlát!}
{174}{}{Viszlát!}
{175}{}{Miért? Nézz körbe... a falu pusztul. A kertek elhervadnak, a gyerekek és öregek elpusztulnak. El kell hoznod az Édent, miel?tt túl kés? lenne!}
{176}{}{Rendben, megoldom. Viszlát!}
{177}{}{Én vagyok a Kiválasztott... azt csinálom, ami nekem jólesik. Viszlát!}
{178}{}{A nevére nem emlékszem, de öreg volt és hangos - túl hangos rendes ember létére - viszont sok dolgot tudott. Klamathból jött, keletr?l, mint már mondottam.}
{179}{}{Köszönöm, viszlát!}
{180}{}{Még mindig itt vagy? Meg kell találnod az ÉLET-et. Az, hogy itt állsz, nem segít rajtunk.}
{181}{}{Te csak tör?dj a kis hidaddal, barátom! Tudom én, mit csinálok.}
{182}{}{Éppen most indulok. Viszlát, barátom!}
{183}{}{Többet nem beszélek veled, parancsolgatós disznó!}
{184}{}{Szeretnék még kérdezni valamit.}
{185}{}{Ez gyors volt! Megtaláltad a Szent 13-as Menedéket?}
{186}{}{Igen.}
{187}{}{Nem, még nem.}
{188}{}{Megtaláltad? Csodálatos! Elhoztad az ÉLET-et?}
{189}{}{Nem.}
{190}{}{Nem. Még nem beszéltem a Menedék lakóival.}
{191}{}{Nem hiszem, hogy ez rád tartozna, barátom.}
{192}{}{Nem-e? Kiválasztott, mióta elmentél, három id?s ember meghalt. Nem szabad több id?t veszítened!}
{193}{}{Meg fogom találni, ne aggódj!}
{194}{}{Unom már az állandó parancsolgatást!}
{195}{}{Hát miért velem beszélsz? Beszélj velük, és szerezd meg az ÉLET-et!}
{196}{}{Fogok is... még id?ben vagyok, barátom.}
{197}{}{Unom már az állandó parancsolgatást!}
{198}{}{Mi újság az ÉLET-tel, Kiválasztott?}
{199}{}{Megtaláltam a Menedéket!}
{200}{}{Képtelen voltam megtalálni a 13-as Menedéket.}
{201}{}{Nézzétek csak, itt a Kiválasztott!}
{202}{}{Helló!}
{203}{}{Pofa be!}
{204}{}{Kérdezhetnék valamit?}
{205}{}{Nem, most nincs id?m veled beszélgetni.}
{206}{}{Jól van. Viszlát!}
{207}{}{Ó, hát, majd kés?bb találkozunk.}
{208}{}{Dögölj meg!}
{209}{}{Üdvözöllek, idióta! Látod hidat? Átmész, leszel óvatos! Híd veszélyes. Nem leesni, oké?}
{210}{}{Umm... Mi?}
{211}{}{Nyomorult! Nem tör?dtél a faluval!}
{212}{}{Elárultál minket! Ezért most meghalsz!}
{213}{}{Elárulod a saját embereidet.}
{214}{}{Miért teszed ezt?}
{215}{}{A Törzsf? tévedett. Te gonosz ember vagy.}
{300}{}{Az apám megtanított rá, hogyan csináljak er?sebb pengéket a többinél. Hozz egy kovakövet, és megélezem a te dárdádat is. Szükséged lesz rá a vadonban.}
{301}{}{Hol találhatnék kovakövet?}
{302}{}{They say your Aunt Morlis has been hoarding a piece. She's so
 ill-tempered I don't think anyone's asked her. Of course, the witch will want
 something in return.}
{303}{}{Kösz. Viszlát!}
{304}{}{Beszéltél a nagynénéddel a kovak?r?l?}
{305}{}{Igen, itt van.}
{306}{}{Még nem.}
{307}{}{Ez egy szép darab. Add ide a dárdát!}
{308}{}{Tessék.}
{309}{}{Azt hiszem, nincs dárdám.}
{310}{}{Most tedd a darabokat úgy, hogy...}
{311}{}{Kiválasztott lándzsa nélkül? Na, akkor adok egyet a saját dárdáim közül. Fogjunk hozzá...}
{312}{}{Tessék az új dárdád...}
{313}{}{Köszönöm, barátom... ez sokat fog segíteni.}
{314}{}{Igen, de csodálkozom a dárdádon. Kicsit másképpen néz ki, mint a többi.}
{400}{}{Üdvözöllek itthon, Kiválasztott! Megtaláltad a Menedéket? Elhoztad az ÉLET-et?}
{401}{}{Én nem talál még meg.}
{402}{}{Nem, még nem találtam meg.}
{403}{}{Nem vagyok olyan hangulatban, hogy válaszoljak a kérdéseidre. Viszlát!}
{404}{}{A dolgok rosszul mennek, Kiválasztott. A szárazság egyre nagyobb, és a termés biztosan tönkremegy. Megpróbáljuk megmenteni, amit tudunk.}
{405}{}{Why no trade with other villages?}
{406}{}{Csinálni legjobb tudásból. Megtalálni ÉLET. Visszatérni én.}
{407}{}{Miért nem üzletelünk a többi faluval az ételért, amire szükségünk van? }
{408}{}{Ha megtalálom az ÉLET-et, visszatérek.}
{409}{}{Mi csak egyszer? emberek vagyunk, és kevés árunk van kereskedésre. Az a kevés város, amikkel kapcsolatban vagyunk, nem mutatnak túl nagy érdekl?dést irántunk.}
{410}{}{Én érteni.}
{411}{}{Értem.}
{412}{}{You are our only hope, Chosen One. Please do not fail us!}
{413}{}{Örülök, hogy látlak, Kiválasztott. Hogy halad a küldetés?}
{414}{}{Még keresni.}
{415}{}{Még keresem.}
{416}{}{Nem akarok beszélni róla.}
{417}{}{Sietned kell! A dolgok egyre rosszabbul állnak. Hamarosan elfogy az ételünk. Aggódom Arroyo jöv?je miatt.}
{418}{}{Kiválasztott! Kérlek, mondd, hogy sikerült a küldetés! A falu, és az emberek egyre csak pusztulnak.}
{419}{}{Nem, még keresek én.}
{420}{}{Nem, még keresek.}
{421}{}{Hogy mennek a dolgok?}
{422}{}{Sajnálom, Kiválasztott, de meg kell kérdeznem, bízhatunk-e benned. Az embereink élete a te kezedben van. Kérlek, találd meg a szent tizenhármast, és térj vissza az ÉLET-tel!}
{423}{}{A termés tönkrement, a brahminok elpusztulnak, már mindenki éhezik. Gyerekeink sírása az éjszakában senkit sem hagy aludni. A helyzetünk kezd reménytelenné válni.}
{424}{}{Én folytat keresés.}
{425}{}{Megteszem, amit tudok.}
{426}{}{Ismét visszatértél, Kiválasztott. Remélem, nem üres kézzel!}
{427}{}{Én sajnál, nem talál még ÉLET.}
{428}{}{Sajnálom, de még nem találtam meg az ÉLET-et.}
{429}{}{Elég ebb?l!}
{430}{}{Amíg te itt sétálgatsz, az emberek haldokolnak. Keresd az ÉLET-et máshol, ne gyere folyton vissza ide!}
{500}{}{Beszéltél már a Törzsf?vel?}
{1000}{}{Törzsf?}
{1001}{}{Alapító}
{1002}{}{Menedéklakó}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Menedék}
{1006}{}{Kiválasztott}
{1007}{}{Sámán}
{1008}{}{Hakunin}
{1009}{}{Gyógyító por}
{1010}{}{Híd}
{1011}{}{Mynoc}
{1100}{}{A törzsf? a te édesanyád és a vezet?nk.}
{1101}{}{? a mi nagyszer? ?sünk, neki köszönhetjük a tudást.}
{1102}{}{? volt az, aki el?ször küzdött meg sikeresen a káosszal.}
{1103}{}{Ez a mi szépséges falunk.}
{1104}{}{Kereskedelmi csomópont néhány napi járóföldre keleti irányban.}
{1105}{}{A Menedék maga a mennyország.}
{1106}{}{TE vagy a Kiválasztott.}
{1107}{}{He heals us with his herbs and magic. He is in the
 northern part of our village.}
{1108}{}{? a növényeivel és a mágiájával gyógyít bennünket. A falu északi részében megtalálod.}
{1109}{}{Az egy mágikus por, amely ugyan meggyógyít, de egyúttal el is álmosít.}
{1110}{}{A Nagy Híd dél felé van a falunktól.}
{1111}{}{Ez én lennék.}
