{100}{}{Egy gonosz növényt látsz.}
{101}{}{Ezek a növények nem csak a kertet, hanem más él?lényeket, köztük az embereket is képesek megtámadni.}
{102}{}{Ezek a gonosz növények igen furcsák. Nem valószín?, hogy természtes módon mutálódtak ilyenné.}
{103}{}{Semmi különöset nem veszel észre ezeken a növényeken - kivéve azt, hogy embereket is megtámadnak.}
{150}{}{Kigyomláltad a kertb?l a gonosz növényeket.}
