{100}{}{Egy gonosz növényt látsz.}
{101}{}{Ezek a növények nem csak a kertet, hanem más élõlényeket, köztük az embereket is képesek megtámadni.}
{102}{}{Ezek a gonosz növények igen furcsák. Nem valószínû, hogy természtes módon mutálódtak ilyenné.}
{103}{}{Semmi különöset nem veszel észre ezeken a növényeken - kivéve azt, hogy embereket is megtámadnak.}
{150}{}{Kigyomláltad a kertbõl a gonosz növényeket.}
