{100}{}{Ő Cameron, az egyik törzsbéli társad.}
{101}{}{Ő Cameron.}
{102}{}{Egy ifjú embert látsz duzzadó izmokkal és merész arckifejezéssel.}
{103}{}{Légy üdvözölve, }
{104}{}{. Enyém a megtiszteltetés, hogy ismertessem utolsó feladatod. A küldetésed folytatásához le kell engem győznöd közelharcban, fegyverek nélkül. Kezdhetjük?}
{105}{}{Nekem lenni kérdés.}
{106}{}{Oké, mi harcol.}
{107}{}{Nem, én felkészül először.}
{108}{}{Először lenne hozzád néhány kérdésem.}
{109}{}{Rendben, kezdhetjük.}
{110}{}{Várj egy pillanatot, előbb felkészülnék!}
{111}{}{Mit szeretnél tudni? }
{112}{}{Miért harcol mi?}
{113}{}{Harcolunk mi halálba?}
{114}{}{Harcolunk mi fegyver nélkül?}
{115}{}{Rendben, most harcolunk mi.}
{116}{}{Nekem kell készülni fel.}
{117}{}{Miért kell harcolnunk?}
{118}{}{Élet-halál harcra számíthatok?}
{119}{}{Azt mondtad, fegyverek nélkül harcolunk?}
{120}{}{Legyünk túl ezen a harcon!}
{121}{}{Egy pillanat, még fel kell készülnöm.}
{122}{}{A Kiválasztott útját nem könnyű végigjárni, }
{123}{}{. Rengeteg megpróbáltatásban lesz még részed életed során, és ezek közül a legnehezebb az, ha a társaddal kell összecsapnod. Eljön majd az idő, amikor a diplomácia és a cselek csődöt mondanak, ezért a puszta kezedet kell használnod. Ez a megpróbáltatás felkészít arra, hogy ha meglátod az ellenséged, a szemébe nézhess, és tudd, hogy meg kell ölnöd őt.}
{124}{}{Oké.}
{125}{}{Értem.}
{126}{}{Nem, barátom, csak le kell győznöd. Ha eljön az ideje, rögtön abbahagyjuk a küzdelmet.}
{127}{}{Én érteni.}
{128}{}{Értem.}
{129}{}{Igen. A fegyverek csak akadályoznának bennünket a harcban, és gyengítenék az egymás elleni cselekedeteink hatását. Mikor puszta ököllel harcolsz egy másik ember ellen, látod is, érzed is a fájdalmat, amit okoztál. A harc nagyon személyessé válik kettőtök között. Ez fontos lecke lehet számodra, }
{130}{}{ dollár.}
{131}{}{Vettem.}
{132}{}{Értem.}
{133}{}{Nagyon jó. Kezdhetjük?}
{134}{}{Én készen állni.}
{135}{}{Nem, én felkészül először.}
{136}{}{Készen állok.}
{137}{}{Nem, kell egy kis idő, amíg felkészülök.}
{138}{}{Rendben van. Gyere vissza, és szólj, ha készen állsz!}
{139}{}{Készen állsz a feladatra, }
{140}{}{ barátoddal?}
{141}{}{Én készen. }
{142}{}{Én még nem lenni kész.}
{143}{}{Azt hiszem, igen.}
{144}{}{Nem, adj még egy percet!}
{145}{}{Nagyszerű! A felszerelésed az ajtó melletti ládában lesz, a másik teremben. A harc után magadhoz veheted. Harcra fel! Sok szerencsét, }
{146}{}{ dollár.}
{147}{}{Örülök, hogy újra láthatlak, Kiválasztott. Miben segíthetek?}
{148}{}{Én akarja újra menni be templom.}
{149}{}{Akarsz velem újra harcolni?}
{150}{}{Csak mondani üdv. Én mostan már menni.}
{151}{}{Szeretnék újra bemenni a templomba.}
{152}{}{Üdv, Cameron! Készen állsz egy újabb harcra?}
{153}{}{Csak gondoltam, beköszönök. Később találkozunk.}
{154}{}{Rendben, Kiválasztott. Ez a barlang mögöttem a templom utolsó kamrájába vezet.}
{155}{}{Oké. Menni.}
{156}{}{Rendben. Köszönöm.}
{157}{}{Nem, kösz, Kiválasztott. Még mindig megvannak a sebeim, amiket tőled szereztem a harcban, és több évbe fog telni, amíg teljesen meggyógyulok!}
{158}{}{Üdv, Cameron.}
{159}{}{Hát akkor, sok szerencsét, Cameron!}
{160}{}{Kiválasztott ám a valagam! Meg foglak ölni!}
{161}{}{Legyőztél. Méltó vagy a feladatra, Kiválasztott.}
{165}{}{Nem értek veled egyet. Szerintem ezt békésen is megoldhatnánk.}
{166}{}{Talán igazad van, }
{167}{}{, de a mi helyzetünkben ez most nem lehetséges. Le kell győznöd engem, hogy kiálld a próbát!}
{168}{}{Nézd, nem ismerjük egymás erősségeit, és gyengeségeit. Baleset is történhet. Mi lesz például, ha valamelyikünk akaratán kívül megöli a másikat? Hagyjuk ezt a harcot, rendben?}
{169}{}{Hmm... Értem, mire gondolsz. Nem akarom, hogy véletlenül meghalj, miközben csak a harci képességeidet tesztelném. Rendben... továbbmehetsz, Kiválasztott!}
{170}{}{Hmm... Értem, mire gondolsz, de mindenképp harcolnunk kell. Megígérem, hogy nem fogok nagy fájdalmat okozni.}
{171}{}{Köszönöm! Majd találkozunk a faluban.}
{172}{}{Értem.}
{200}{}{Mintha nem emlékeznék az utolsó harcunkra, Kiválasztott. Egész életemben csodálkozni fogok, hogyan vettél rá arra, hogy tovább engedjelek.}
{201}{}{Nyelved akár az ezüst, Kiválasztott. Úgy bánsz a szavakkal, hogy minden bizonnyal hasznát tudod majd venni utazásod során.}
{300}{}{Neked szintúgy, Kiválasztott. Őseink szelleme vezessen utadon!}
{301}{}{Köszönöm, Cameron.}
{302}{}{Kiválasztott, látom gyenge vagy a harcban. Így utad során csak a szavaidra számíthatsz. Ha megengeded, tanítok neked néhány harci cselt.}
{303}{}{Igen, te tanít engem.}
{304}{}{Nem, én nem kell ezt.}
{305}{}{Jó, kérlek taníts meg mindenre, amit tudsz!}
{306}{}{Köszönöm, de jól meg tudom védeni magam.}
{307}{}{Jól tanulsz, Kiválasztott. Azt hiszem, most már boldogulni fogsz a harcban. Emlékezz azonban arra, hogy a legerősebb harcosoknak is vissza kell vonulniuk egyszer! Nincs ebben semmi szégyen.}
{308}{}{Én köszönni neked, Cameron.}
{309}{}{Köszönöm, Cameron. Emlékezni fogok a szavaidra.}
{310}{}{Hát jó. Térj vissza, ha meggondolod magad!}
{311}{}{Én köszönni neked, Cameron.}
{312}{}{Köszönöm, Cameron. Emlékezni fogok a szavaidra.}
