{100}{}{A falu egyik férfi lakóját látod.}
{101}{}{A falu egyik nõi lakóját látod.}
{150}{}{A falu egyik tagja.}
{151}{}{[BESZÉLGETÉS]}
{152}{}{Üdvözöllek! Hallottam, te vagy a Kiválasztott. Így talán megmenekülhet a falu.}
{153}{}{Meg tudnád mondani, hol találhatok még gyógyító port?}
{154}{}{Mit tudnál mondani a velünk üzletelõ kereskedõkrõl?}
{155}{}{Örülök, hogy láthatlak, de most mennem kell.}
{156}{}{Talán az istenek majd megvédenek az utadon.}
{157}{}{Lenne egy kérdésem hozzád.}
{158}{}{Viszlát, barátom!}
{159}{}{Keresd Hakunint a sátrában! A falu északi részén megtalálod. Õ majd biztosan segít neked.}
{160}{}{Köszönöm. Viszlát!}
{161}{}{Ó, én nem szoktam találkozni velük. Beszélj Mynockal, a Nagy Híd õrzõjével! Õ tartja a kapcsolatot az összes kereskedõvel.}
{162}{}{Köszönöm. Viszlát!}
{163}{}{Meg tudnád mondani, merre találom a Nagy Hidat?}
{164}{}{Még egy kérdést, ha lehetne.}
{165}{}{Jó vicc, Kiválasztott! Tudod te, hol van... Arra... déli irányban.}
{166}{}{Köszönöm. Viszlát!}
{167}{}{Még egy kérdést, ha lehetne.}
{168}{}{Természetesen, mit szeretnél tudni?}
{169}{}{Meg tudnád mondani, hol találhatok gyógynövényeket?}
{170}{}{Mit tudnál mondani a kereskedõkrõl, akik velünk üzletelnek?}
{171}{}{Semmi-semmi...}
{172}{}{Ó, Istenek! ...talán az Alkotó szelleme majd vezetni fog. Ha te vagy a Kiválasztott, szükségünk lesz rá.}
{173}{}{Ja.}
{174}{}{Legyen biztonságos az utad.}
{175}{}{????}
{176}{}{Halálra vagyunk ítélve! Elbuktad a küldetésed!}
{177}{}{Így nem folytathatod!}
{180}{}{Elárultad a saját embereidet.}
{181}{}{Miért csinálod ezt?}
{182}{}{Gonosz vagy. A Kiválasztott gonosz!!!}
{183}{}{Keletrõl jönnek a falunkba, de az árujuk igen szegényes.}
{184}{}{Meg tudnád mondani, merre találhatok gyógynövényeket?}
{185}{}{Köszönöm. Viszlát!}
{186}{}{Még egy kérdést, ha feltehetnék...}

# Starting Dialog after 1st Hakunin Movie
{300}{}{Üdv, Kiválasztott. Jó, hogy újra láthatlak. Imádkoztam, hogy a küldetésed jól sikerüljön. Segíthetnék valamiben?}

# Starting Dialog after 2nd Hakunin Movie
{301}{}{Kiválasztott, az emberek haldokolnak. Sietned kell az ÉLET-tel! Mit tehetnék küldetésed sikerének érdekében?}

# Starting Dialog after 3rd Hakunin Movie
{302}{}{Kifutunk az idõbõl, Kiválasztott! Kérlek, fejezd be hamar a küldetésed! Már nem tudunk sokáig várni. Mondd meg, ha segíthetnék valamiben a küldetés sikerének érdekében!}

# Starting Dialog after 4th Hakunin Movie
{303}{}{Kiválasztott, a falu csaknem elpusztult... te vagy az egyetlen reménységünk. Van valami, amiben segíthetnék nehéz küldetésedben?}


#############################################################
#  TELL - ME - ABOUTS                                       #
#############################################################
{1000}{}{Elder}
{1001}{}{Founder}
{1002}{}{Vault Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Chosen One}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Healing Powder}
{1010}{}{Bridge}
{1011}{}{Mynoc}

{1100}{}{The Elder is your mother and our leader.}
{1101}{}{Our great ancestor who gave us knowledge.}
{1102}{}{The first to fight and win over chaos.}
{1103}{}{That would be our beautiful village.}
{1104}{}{That’s a trading outpost a few days east of here.}
{1105}{}{The Vault is heaven.}
{1106}{}{You are the Chosen One.}
{1107}{}{He heals us with his herbs and magic. He is in the north part
 of our village.}
{1108}{}{He heals us with his herbs and magic. He is in the north part
 of our village.}
{1109}{}{It is a magic powder which will heal you, but will make you
 sleepy.}
{1110}{}{The Great Bridge exits our village in the south.}
{1111}{}{He guards the bridge leading into our village.}