{100}{}{A falu egyik férfi harcosát látod.}
{101}{}{A falu egyik nõi harcosát látod.}
{150}{}{A falu egyik nagy harcosa áll elõtted. Állatbõrbõl készült nadrágot visel.}
{151}{}{[BESZÉLGETÉS]}
{152}{}{Üdvözöllek, Kiválasztott, segíthetek a küldetésedben?}
{153}{}{Mielõtt elmennék, utoljára körülnézek a faluban.}
{154}{}{Mit tudnál mondani a velünk üzletelõ kereskedõkrõl?}
{155}{}{Meg tudnád mondani, hol találhatok még gyógyító port??}
{156}{}{Az istenek majd sebes lépteket adnak, hogy hamarabb visszatérhess.}
{157}{}{Lenne hozzád egy kérdésem.}
{158}{}{Viszlát, barátom!}
{159}{}{Ugye csak viccelsz? Ugorj be Hakuninhoz, a falu északi részén megtalálod! Õ készíti az orvosságainkat.}
{160}{}{Köszönöm. Viszlát!}
{161}{}{Hát, amikor Mynoc ránk bízta a hidat, láttam némelyiküket, de az összes árucserét Mynoc szervezi. Keresd fel, a Nagy Hídnál összefuthatsz vele!}
{162}{}{Köszönöm. Viszlát!}
{163}{}{Meg tudnád mondani, merre van a Nagy Híd?}
{164}{}{Még egy kérdést, ha lehetne.}
{165}{}{Kiválasztott! A Nagy Híd délre van a falu határában. Tudod, már sokszor jártál ott.}
{166}{}{Köszönöm. Viszlát!}
{167}{}{Még egy kérdést, ha lehetne.}
{168}{}{Mi lenne az?}
{169}{}{Megmondanád, merre találhatok gyógynövényeket?}
{170}{}{Mit tudnál mondani a velünk üzletelõ kereskedõkrõl?}
{171}{}{Felejtsd el!}
{172}{}{Azt mondják, te vagy a Kiválasztott. Az Alapító bizony nagyot tévedett, amiért rád esett a választása.}
{173}{}{Ja.}
{174}{}{Kellemes utat... de csak miattunk.}
{175}{}{????}
{176}{}{Te átversz minket! Meg kell halnod!}
{177}{}{Elárultad a saját népedet!}
{178}{}{Miért csináltad ezt?}
{179}{}{Halál a gonoszra!}
{180}{}{Õk nem jelentenek számunkra semmit! A puszták dögevõi.}
{181}{}{Meg tudnád mondani, merre találhatok gyógynövényeket?}
{182}{}{Köszönöm. Viszlát!}
{183}{}{Még egy kérdést, ha lehetne.}

# Starting Dialog after 1st Hakunin Movie
{300}{}{Üdvözöllek, Kiválasztott. Talán a harcos szellemek vezérelnek és megvédenek majd.}

# Starting Dialog after 2nd Hakunin Movie
{301}{}{Nehézségeid vannak, Kiválasztott? Nem vallhatsz kudarcot! Kérlek, siess!}

# Starting Dialog after 3rd Hakunin Movie
{302}{}{Miért vársz olyan sokáig? Gyorsan meg kell szerezned az ÉLET-et, a falu egyre csak pusztul!}

# Starting Dialog after 4th Hakunin Movie
{303}{}{Kiválasztott, a falunk már csaknem odalett. Miért nem hozod már a szent ÉLET-et?}



#############################################################
#  TELL - ME - ABOUTS                                       #
#############################################################

#                      #
#                      #
# TELL ME ABOUT STUFF  #
#      "my name"       #
#      (970-979)       #
#                      #
#                      #
{970}{}{That is my name.}
{971}{}{You are talking to me.}
{972}{}{What a silly question. That's me.}

#                      #
#                      #
# TELL ME ABOUT STUFF  #
#     "don't know"     #
#      (980-989)       #
#                      #
#                      #
{980}{}{I don't know anything about that.}
{981}{}{Sorry. No clue.}
{982}{}{Never heard of it.}


{1000}{}{Elder}
{1001}{}{Founder}
{1002}{}{Vault Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Chosen One}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Healing Powder}
{1010}{}{Bridge}
{1011}{}{Mynoc}

{1100}{}{The Elder is your mother and our leader.}
{1101}{}{Our great ancestor who gave us knowledge.}
{1102}{}{The first to fight and win over chaos.}
{1103}{}{That would be our beautiful village.}
{1104}{}{That’s a trading outpost a few days east of here.}
{1105}{}{The Vault is heaven.}
{1106}{}{You are the Chosen One.}
{1107}{}{He heals us with his herbs and magic. He is in the north
 part of our village.}
{1108}{}{He heals us with his herbs and magic. He is in the north
 part of our village.}
{1109}{}{It is a magic powder which will heal you, but will make
 you sleepy.}
{1110}{}{The Great Bridge exits our village in the south.}
{1111}{}{He guards the bridge leading into our village.}