# Dialog Editor last position: 5
{100}{}{Egy alacsony férfit látsz, a kezében egy könyvet tart.}
{101}{}{Dr. Jones, az orvos.}
{102}{}{Egy alacsony férfit látsz, kezében egy könyv, amelynek címe: "Szóval orvos akarsz lenni?".}
{103}{}{Helló, Dr. Jones vagyok, de hívhatsz Dokinak is. Miben segíthetek?}
{104}{}{Én beteg. Te gyógyít?}
{105}{}{Én érez rosszul. Te gyógyít?}
{106}{}{Én lerobban, te gyógyít?}
{107}{}{Én kérdez. Oké?}
{108}{}{Én sajnál, én megy.}
{109}{}{Megsérültem. Tudsz segíteni?}
{110}{}{Rosszul érzem magam. Segítenél?}
{111}{}{Eltörött néhány csontom.}
{112}{}{Feltennék pár kérdést.}
{113}{}{Csak beköszöntem.}
{114}{}{Természetesen. Tessék, adunk egy adagot ebbõl -- ez egy picit csípni fog -- aztán bekötjük, és már kész is vagy.}
{115}{}{Én köszön. Bye.}
{116}{}{Kösz, Doki. Sokkal jobban érzem magam.}
{117}{}{Természetesen. Tessék, idd meg ezt! Tudom, hogy pocsék íze van, de az egészet le kell nyelned. Most pedig feküdj le az ágyra, holnap reggelre kutya bajod se lesz.}
{118}{}{Én érez jól. Szia.}
{119}{}{Kösz, Doki, ez tényleg segített.}
{120}{}{Sajnálom, de nincs megfelelõ felszerelésem a mûtétekhez. Azt javaslom, menj el valamelyik nagyobb városba, és keress egy sebészt! Próbáld meg Menedékvárost! Innen északra van.}
{121}{}{Oké. Üdv!}
{122}{}{Rendben. Köszönöm.}
{123}{}{Mit szeretnél tudni?}
{124}{}{Te dolgozol Darion?}
{125}{}{Te elmész ha akarsz?}
{126}{}{Mit te tudni Darion?}
{127}{}{Hogy te kerültél ide?}
{128}{}{Azt mondani, Darion van kutya?}
{129}{}{Most én megy.}
{130}{}{Darionnak dolgozol?}
{131}{}{Elmehetnél innen, ha akarnál?}
{132}{}{Mit tudsz mondani nekem Darionról?}
{133}{}{Hogy kerültél ide?}
{134}{}{Említetted, hogy Darionnak van egy kutyája.}
{135}{}{Kösz, most mennem kell.}
{136}{}{Nos, igen is meg nem is. Nem szabad akaratomból vagyok itt. Darion évekkel ezelõtt berendezkedett ide, és szüksége volt egy orvosra. A Khan-ok kizárólag az õ személye miatt tartanak itt. Szívem szerint a fenti enbereken segítenék, de rab vagyok. }
{137}{}{Oké. Én akar tudni még.}
{138}{}{Köszi. Viszlát.}
{139}{}{Értem. Kérdeznék valami mást.}
{140}{}{Kösz. Most mennem kell.}
{141}{}{De hát azok csak koszos földfoglalók. Dögöljenek csak meg! Éld a saját életed!}
{142}{}{Nem, be vagyok zárva. Még annyi idõre sem mehetek el, hogy feltöltsem a készleteimet. Darion kiküldet mindenért, amire szükségem van.}
{143}{}{Én ért. Most menni.}
{144}{}{Én akar kérdezni még.}
{145}{}{Azt hiszem, nem vagy méltó arra, hogy szabadon élhess.}
{146}{}{Értem. Sajnálom, de most mennem kell.}
{147}{}{Sajnálattal hallom.}
{148}{}{Egyszerûen és érthetõen fogalmazva Darion klinikai eset. Több kísértetet lát, mint ahány bolhája van a kutyájának. Annyit tudok, hogy egy banda tagja volt, akik elraboltak egy lányt, Tandit, és váltságdíjat követeltek érte. Az apja pokoli haragra gerjedt, és felbérelt néhány zsoldost, hogy visszahozzák a lányát. Darion volt az egyetlen, aki túlélte.}
{149}{}{Öö...}
{150}{}{Én most megy.}
{151}{}{Köszönöm az információt, most megyek.}
{152}{}{Lenyûgöz a tudásod.}
{153}{}{Mintha csak rólam beszélnél.}
{154}{}{Elraboltak. Épp Menedékvárosból New Renóba tartottam, hogy kipihenjem az éves munka fáradalmait. Egyik este aludni tértem és reggel arra ébredtem, hogy összekötözve, betömött szájjal fekszem a földön.}
{155}{}{Ugh.}
{156}{}{Kösz. Én most távozni.}
{157}{}{A gyengék gyakran az erõsek zsákmányává válnak.}
{158}{}{Sajnálattal hallom.}
{159}{}{Ez érdekes, de mennem kell.}
{160}{}{Igen, van. Véleményem szerint a legaljasabb, leghitványabb kreatúra a Földön. Úgy tûnik, szereti Dariont. Õ az egyetlen, akit megtûr maga mellett. Nagyon vigyázz vele!}
{162}{}{Öö, üdv.}
{163}{}{Kösz a figyelmeztetést.}
{164}{}{Most mennem kell.}
{165}{}{Nem segítek a magadfajtának. Menj el!}
{166}{}{Oké, vigyázz magadra, és gyere vissza, ha szükséged van segítségre!}
{167}{}{Rendben.}
{168}{}{Paranoid. Azt hiszi, Tandi el akarja kapni. Rögeszméjévé vált a bosszú, és mindenáron végezni akar vele. Közben teljesen elemészti a bûntudat, mert elrejtõzött és túlélte, ahelyett, hogy ott pusztult volna a bandával.}
