{100}{}{Ez az alacsony ember könyvet tart a kezében.}
{101}{}{Dr. Jones, az orvos.}
{102}{}{Egy alacsony férfit látsz, kezében egy könyv, amelynek címe: "Szóval orvos akarsz lenni?".}
{103}{}{Helló, Dr. Jones vagyok, de hívhatsz Dokinak is. Miben segíthetek?}
{104}{}{Van bibi. Te gyógyít?}
{105}{}{Itt viszket. Te gyógyít?}
{106}{}{Én fáj, te gyógyít?}
{107}{}{Van kérdés. Oké?}
{108}{}{Bocs, én megy.}
{109}{}{Megsérültem. Meg tudnál gyógyítani?}
{110}{}{Beteg vagyok. Meg tudnál gyógyítani?}
{111}{}{Súlyosan megsérültem. Tudsz segíteni?}
{112}{}{Fel szeretnék tenni néhány kérdést.}
{113}{}{Csak beköszöntem.}
{114}{}{Természetesen. Tessék, adunk egy adagot ebből -- ez egy picit csípni fog -- aztán bekötjük, és már kész is vagy.}
{115}{}{Én köszön. Szia.}
{116}{}{Kösz, doki! Sokkal jobban vagyok.}
{117}{}{Természetesen. Tessék, idd meg ezt! Tudom, hogy pocsék íze van, de az egészet le kell nyelned. Most pedig feküdj le az ágyra, holnap reggelre kutya bajod se lesz.}
{118}{}{Én lenni jól. Szia.}
{119}{}{Kösz, Doki, ez tényleg segített.}
{120}{}{Sajnálom, de nincs megfelelő felszerelésem a műtétekhez. Azt javaslom, menj el valamelyik nagyobb városba, és keress egy sebészt! Próbáld meg Menedékvárost! Innen északra van.}
{121}{}{Oké. Üdv!}
{122}{}{Rendben. Azért kösz.}
{123}{}{Mit szeretnél tudni?}
{124}{}{Te dolgozol Darion?}
{125}{}{Te menni innen, ha akar?}
{126}{}{Mit te tudni Darion?}
{127}{}{Milyen itt élni?}
{128}{}{Azt mondani, Darion van kutya?}
{129}{}{Én menek mostan.}
{130}{}{Darionnak dolgozol?}
{131}{}{Bármikor távozhatsz?}
{132}{}{Mit tudsz mondani nekem Darionról?}
{133}{}{Hogy kerültél ide?}
{134}{}{Említetted, hogy Darionnak van egy kutyája.}
{135}{}{Kösz az infót. Most már megyek.}
{136}{}{Nos, igen is meg nem is. Nem szabad akaratomból vagyok itt. Darion évekkel ezelőtt berendezkedett ide, és szüksége volt egy orvosra. A Khan-ok kizárólag az ő személye miatt tartanak itt. Szívem szerint a fenti enbereken segítenék, de rab vagyok. }
{137}{}{Oké. Még kérdezni.}
{138}{}{Köszönöm. Viszlát!}
{139}{}{Ez nagyon rendes tőled.}
{140}{}{Kösz. Most mennem kell.}
{141}{}{De hát azok csak koszos földfoglalók. Dögöljenek csak meg! Éld a saját életed!}
{142}{}{Nem, be vagyok zárva. Még annyi időre sem mehetek el, hogy feltöltsem a készleteimet. Darion kiküldet mindenért, amire szükségem van.}
{143}{}{Én érteni. Menni mostan.}
{144}{}{Kell még kérdés.}
{145}{}{Azt hiszem, nem vagy méltó arra, hogy szabadon élhess.}
{146}{}{Értem. Sajnálom, de most mennem kell.}
{147}{}{Sajnálattal hallom.}
{148}{}{Egyszerűen és érthetően fogalmazva Darion klinikai eset. Több kísértetet lát, mint ahány bolhája van a kutyájának. Annyit tudok, hogy egy banda tagja volt, akik elraboltak egy lányt, Tandit, és váltságdíjat követeltek érte. Az apja pokoli haragra gerjedt, és felbérelt néhány zsoldost, hogy visszahozzák a lányát. Darion volt az egyetlen, aki túlélte.}
{149}{}{Öö... ér-teem...}
{150}{}{Menni kell.}
{151}{}{Köszönöm az információt, most megyek.}
{152}{}{Lenyűgöz a tudásod.}
{153}{}{Mintha csak rólam beszélnél.}
{154}{}{Elraboltak. Épp Menedékvárosból New Renóba tartottam, hogy kipihenjem az éves munka fáradalmait. Egyik este aludni tértem és reggel arra ébredtem, hogy összekötözve, betömött szájjal fekszem a földön.}
{155}{}{Ööhh.}
{156}{}{Kösz. Én menni most.}
{157}{}{A gyengék gyakran az erősek zsákmányává válnak.}
{158}{}{Sajnálattal hallom.}
{159}{}{Ez érdekes, de mennem kell.}
{160}{}{Igen, van. Véleményem szerint a legaljasabb, leghitványabb kreatúra a Földön. Úgy tűnik, szereti Dariont. Ő az egyetlen, akit megtűr maga mellett. Nagyon vigyázz vele!}
{161}{}{Én még kérdezze.}
{162}{}{Öö, üdv.}
{163}{}{Kösz a figyelmeztetést.}
{164}{}{Most mennem kell.}
{165}{}{Nem segítek a magadfajtának. Eredj innen!}
{166}{}{Oké, vigyázz magadra, és gyere vissza, ha szükséged van segítségre!}
{167}{}{[Kész]}
{168}{}{Paranoid. Azt hiszi, Tandi el akarja kapni. Rögeszméjévé vált a bosszú, és mindenáron végezni akar vele. Közben teljesen elemészti a bűntudat, mert elrejtőzött és túlélte, ahelyett, hogy ott pusztult volna a bandával.}
