# Dialog Editor last position: 16
{100}{}{Egy embert látsz a hadsereg egyenruhájában.}
{101}{}{Egy embert látsz a hadsereg egyenruhájában.}
{102}{}{Ez az ember a hadsereg egyenruháját viseli, de inkább látszik technikusnak, mint katonának.}
{103}{}{Hali! Hogy ityeg?}
{104}{}{Képben vagy ám... viszont most épp dolgom van.}
{105}{}{Most nem beszélhetek veled.}
{106}{}{Nézelõdni lehet, de hozzá ne nyúlj semmihez!}
{107}{}{Valami nudista vagy te, hogy így flangálsz? Öltözz már fel rendesen!}
{108}{}{Ha az õrmi észrevesz egyenruha nélkül, lecsavarja a tököd!}
{109}{}{Miért nincs rajtad egyenruha?}
{110}{}{Szent szar! Megtámadtak minket! Riadó!}
{111}{}{Behatoló! Õrség!}
{112}{}{Õrség! Behatoló a légiirányításnál!}
{113}{}{Mi van? Megtámadtak, vagy mi a szar?}
{114}{}{Miért szól a rohadt sziréna?! Mi történt?}
{115}{}{Mi a szar folyik itt?}
