# Dialog Editor last position: 50
{100}{}{Egy technikust látsz.}
{101}{}{Egy Enklávé technikust látsz.}
{102}{}{Egy fickót látsz laborköpenyben. Nagyon magabiztosnak látszik.}
{103}{}{Igen, katona?}
{104}{}{Én lenni itt új. Kell tenni fel néhány kérdés.}
{105}{}{Én csak mondani csá. Én mostan menni.}
{106}{}{Helló, új vagyok és szeretnék kiigazodni a bázison. Kérdezhetnék néhány dolgot?}
{107}{}{Áh, semmi, viszlát!}
{108}{}{Persze. Van néhány szabad percem.}
{109}{}{Miben segíthetek?}
{110}{}{Mi ez a hely?}
{111}{}{Mit dolgozol itt?}
{112}{}{Hol találom az Enklávé fõbázisát?}
{113}{}{Én keresni gépmadár tervei. Hol találni?}
{117}{}{Én most menni el.}
{118}{}{Mi ez a hely?}
{119}{}{Mi a munkád itt?}
{120}{}{Hol találom az Enklávé fõbázisát?}
{121}{}{Vetnem kéne néhány pillantást a gépmadár terveire. Nem tudod, hol tartják õket?}
{125}{}{Semmiben. Most mennem kell.}
{126}{}{Ez a légiirányító központ. Innen nyomon követhetjük az öszes gépmadár mozgását.}
{127}{}{Én érteni. Én kérdezni még.}
{128}{}{Oké. Volna még néhány kérdésem.}
{129}{}{Elsõ osztályú számítógép-kezelõ vagyok. Én tartom fenn a kapcsolatot a számítógépek és a vezérlõegység között.}
{130}{}{Ah, értem.}
{131}{}{Jól van. Csak így tovább!}
{132}{}{Te nem a Pusztaságból jöttél?}
{133}{}{Öh..nem, mi jönni messzi észak.}
{134}{}{Nem, valójában északról jöttem.}
{135}{}{Hm... Nem is tudtam, hogy van megfigyelõ bázisunk arrafelé. Na, nem baj, a fõbázist úgyis a San Francisco-i partokról lehet elérni.}
{136}{}{Hogy jutni oda?}
{137}{}{Hm... Hogy lehet odajutni?}
{138}{}{Gépmadáron, természetesen. Nincs más út, hacsak nincs egy saját hajód, hehe. Mert úszva kicsit messzebb van.}
{139}{}{Köszönni meg.}
{140}{}{Köszönöm.}
{141}{}{Gépmadár tervek... Nem tudom, mi szükséged lenne rájuk. Azt javaslom, beszélj a szerelõkkel! Itt vannak mellettünk.}
{142}{}{Oké.}
{143}{}{Vettem.}
{153}{}{Valami nudista vagy te, hogy így flangálsz? Vedd fel az egyenruhát!}
{154}{}{Ha az õrmi észrevesz egyenruha nélkül, lecsavarja a tököd!}
{155}{}{Miért nincs rajtad az egyenruha?}
{156}{}{Szent szar! Megtámadtak minket! Riadó!}
{157}{}{Behatoló! Hívjátok az õrséget!}
{158}{}{Õrség! Behatoló az operatív parancsnokságon!}
{159}{}{Mi van? Megtámadtak, vagy mi?}
{160}{}{Miért van riadó? Mi történt?}
{161}{}{Mi a franc folyik itt?}
{162}{}{Csak egy technikus vagyok! Ne lõj le!}
{163}{}{Nem veszek részt harcban, legfeljebb a továbbképzésben!}
{164}{}{Hogy az a... ez nem páncél, hanem laborköpeny. Már itt se vagyok.}
