# Dialog Editor last position: 40
{100}{}{Egy technikust látsz.}
{101}{}{Egy Enklávé technikust látsz. }
{102}{}{Egy fickót látsz laborköpenyben. Nagyon magabiztosnak tûnik.}
{103}{}{Igen, katona?}
{104}{}{Mi lenni ez hely?}
{105}{}{Csak mondani csá! Most menni.}
{106}{}{Mi ez a hely?}
{107}{}{Csak beugrottam. Most megyek.}
{108}{}{Ez a gépterem. Az ott a fõegység, mellette a terminál az interfésszel, azok ott pedig a hololemez-tároló egységek.}
{109}{}{Óh! Mit csinálni itt?}
{110}{}{Szóval, mi a munkád itt?}
{111}{}{A rangidõs számítógép elemzõ vagyok. Ezzel a sok cuccal kell törõdnöm, meg biztosítani, hogy mûködjenek.}
{112}{}{Óh? Lehet használni nagy csudagép?}
{113}{}{Nem érteni. Inkább elmenni mostan.}
{114}{}{Mondd csak, használhatnám a gépet egy percre? Tudod, kis ellenõrzés meg miegymás...}
{115}{}{Jó volt dumálni veled. Majd még találkozunk.}
{116}{}{Hát... nem engedhetem, hogy a képzett személyzeten kívül más is használja a gépet. Ez egy komplex és érzékeny rendszer, ugye megérted?}
{117}{}{Kérem! Megígérni, nem rontani széjjel.}
{118}{}{Megígérem, hogy nem vágom gallyra.}
{119}{}{Jól van. Beléphetsz a rendszerbe azon a terminálon keresztül. De csak óvatosan, kérlek. Mindkettõnket lelõnek, ha a gépnek baja lesz. Ja, a vendégjelszó "Csacsifül".}
{120}{}{Sajnálom, de még a hivatalos állománynak sem engedhetem meg, hogy hozzányúljon a gépekhez. }
{121}{}{Csacsifül? Mi az a csacsifül?}
{122}{}{Ok. Én érteni elsõre.}
{123}{}{Csacsifül? Mi a rák ez?}
{124}{}{Oké, értem.}
{125}{}{"Csacsifül" a barátnõm beceneve. Szerintem kedves. Õ az az õr, aki kint áll a terem mellett.}
{126}{}{Oké, jó. Köszönni.}
{127}{}{Ja... kedves. Köszönöm.}
{128}{}{Nincs rajtad egyenruha.}
{129}{}{Jobb lenne, ha felöltöznél. A fegyvertár a terem végén van balra.}
{130}{}{Nagy kockázatot vállalsz, ha csak így járkálsz! Gyorsan szerezz egy egyenruhát!}
{131}{}{Te meg ki a fene... Riadó! Behatolók!}
{132}{}{Bejutottak, riadó!}
{133}{}{Behatolók, riadó!}
{134}{}{Kurva eget! Na, kezdjük gyorsan az archiválást!}
{135}{}{Hagyjatok abba minden titkos mûveletet!}
{136}{}{Biztosítsátok a rendszert!}
{137}{}{Tudós vagyok, nem katona!}
{138}{}{"A hegyes végén lévõ lézerdiódát irányítsa rá a célpontra, aztán húzza meg a ravaszt!"}
{139}{}{Segítség! Erõsítést a számítógép-laborba!}
