# Dialog Editor last position: 18
{100}{}{Egy technikust látsz.}
{101}{}{Egy számítógép-technikust látsz. }
{102}{}{Egy laborköpenyes embert látsz. Egy rakás tollat hord a zsebében.}
{103}{}{Jó napot, katona!}
{104}{}{Kérem, ne nyúljon semmihez!}
{105}{}{A katonáknak nem szabadna itt lennie.}
{106}{}{Magán nincs egyenruha.}
{107}{}{Jobb, ha felöltözik! A fegyvertár a terem végén van balra.}
{108}{}{Nagy kockázatot vállal, ha csak így járkál! Gyorsan szerezzen egy egyenruhát!}
{109}{}{Maga meg ki a fene... Riadó! Behatolók!}
{110}{}{Bejutottak, riadó!}
{111}{}{Behatolók, riadó!}
{112}{}{Kurva eget! Na, kezdjük gyorsan az archiválást!}
{113}{}{Hagyjatok abba minden titkos mûveletet!}
{114}{}{Biztosítsátok a rendszert!}
{115}{}{Tudós vagyok, nem katona!}
{116}{}{"A hegyes végén lévõ lézerdiódát irányítsa rá a célpontra, aztán húzza meg a ravaszt!"}
{117}{}{Segítség! Erõsítést a számítógép-laborba!}
