# Dialog Editor last position: 73
{100}{}{Egy õrt látsz.}
{101}{}{Egy kapuõrt látsz.}
{102}{}{Egy õr áll itt, rajta valami különös erõpáncél. Van egy jel a mellkasán, amit nem tudsz hova tenni.}
{103}{sgnt1a}{Üdvözlöm a navarrói táborban... egy civil! Hogy a francba jutott be egy civil a bázisra?! Kicsinálok valakit... Tüntessétek el ezt a bohócot a bázis területérõl!}
{104}{sgnt1b}{Üdvözlöm a navarrói táborban... civilek! Hogy a francba jutottak be civilek a bázisra?! Kicsinálok valakit... Tüntessétek el ezeket a bázis területérõl!}
{105}{}{Várjon! Én...}
{106}{sgnt2a}{Hogy a rohadás állna magába! Elvezettettem a bázisról, és már megint itt van?! Nem hiszem, hogy közönséges civillel állunk szemben, inkább egy kémmel. Fegyverbe! Nyírjátok ki ezt a bohócot! }
{107}{sgnt2b}{Hogy a rohadás állna magukba! Elvezettettem magukat a bázisról és már megint itt vannak! Nem hiszem, hogy közönséges civilekkel állunk szemben, sokkal inkább kémekkel! Fegyverbe! Nyírjátok ki ezeket! }
{108}{sgnt3}{Üdvözlöm a navarrói táborban! Szóval maga a váltás! Mi a neve, közlegény?}
{109}{}{Ühm... öhh... én...}
{110}{}{Én }
{111}{sgnt4}{Áh, remek! Egy barmot küldtek! Nagyon figyeljen! Õrt fog állni a hangárnál. Az lesz az õrhelye! Nem mozdul el onnan, amíg mást nem mondok! Most pedig mozgás!}
{112}{}{Menni.}
{113}{sgnt5}{Mi volt ez? Nem felejtett el valamit, ökör?}
{114}{}{Én nevem lenni }
{115}{sgnt6}{Nem vagyok az Ura!!! A felettese vagyok, hatökör!!! Mostantól õrmesternek hív, vagy Dornan õrmesternek! Megértette? }
{116}{}{Igen, õrmester!}
{117}{}{Persze, õrmi, hogyne...}
{118}{sgnt7}{Kifelé! Kotródjon a hangárhoz és el ne mozduljon onnan! Jó munkát várok magától! Megértette?}
{119}{}{Mit fogok ott õrizni, õrmester?}
{120}{}{Igen, õrmester!}
{121}{sgnt8}{Maga ökör!!! Nem kérdõjelezünk meg parancsot! Ha azt mondom ugrik... ugrik, mint nyúl! Ha azt mondom, harcol... harcol, mint egy oroszlán! Ha azt mondom meghal, akkor elesik a hazájáért! Világos voltam?!}
{122}{}{Igen, õrmester!}
{123}{sgnt9}{Üdvözlöm a navarrói táborban! Szóval maga a váltás... Miért nincs magán egyenruha, katona? Hol van az erõpáncélja?}
{124}{}{Öhm... nekünk nem lenni.}
{125}{}{Nem utalt nekem a bázis belõle. Azt mondták, majd itt kapok.}
{126}{}{Öhm... nem utalt nekem a bázis belõle.}
{127}{}{Nézd már, ennek a fazonnak itt van egy... Milyen szerencse, lehúzhatom a hullájáról!}
{128}{sgnt10}{Nem-e? Azt várja, hogy ezt elhigyjem, maga tinó?! Az igazság az, hogy elvesztette a méregdrága kincstári páncélját! Magára fogjuk hátékázni, és addig rohad itt, amíg le nem telik az ötszáztíz szolgálati éve, és a zsoldjából le nem vonják a kettes verziójú erõpáncél árát! Jelentkezzen a fegyvertárban, aztán jöjjön vissza hozzám! Lelépni!}
{129}{}{Oké. Menni ruháér'.}
{130}{}{Igen, õrmester!}
{131}{sgnt11}{Azok az aktarágó seggfejek! Szerintük hogy tudnám vezetni ezt a bázist, ha állandóan csonkítják a készleteimet?! Húzzon le a fegyvertárba és kapjon magára egyet, aztán jöjjön vissza ide! Lelépni!}
{132}{}{Oké.}
{133}{}{Igen, õrmester!}
{134}{sgnt12}{Ha kedvelem magát, akkor hívhat õrminek! De tudja mit, nem kedvelem magát! Megértette?!!!}
{135}{}{Igen, õrmester!}
{136}{sgnt13}{Kiváló! Van egyenruhája, ezért adok magának egy különleges lehetõséget! Kezdjünk mindent elölrõl, mintha sosem találkoztam volna a szánalmas seggével! Szeretné ezt, katona?}
{137}{}{Igen... öhm, õrmajszter!}
{138}{}{Nem. Mi nem érdekelni ez az egész! Mi rúgjuk szétfele seggedet!}
{139}{}{Igen, õrmester!}
{140}{}{Nem nagyon érdekel, van-e rajtam páncél. Inkább szétrúgom a segged!}
{141}{sgnt14a}{Katona, még mindig nincs magán egyenruha?! Nem megmondtam, hogy jelentkezzen a fegyvertárban! Most takarodjon a szemem elõl és menjen a páncéljáért! És ne jöjjön vissza addig, amíg nem néz ki úgy, mint egy valódi katona!}
{142}{sgnt14b}{Már másodjára látom páncél nélkül, katona! Harmadik alkalom nem lesz!}
{143}{}{Oké! Oké! Menni!}
{144}{}{Bazmeg! Elegünk lenni ebbõl!}
{145}{}{Igenis, õrmester úr! Már megyek is!}
{146}{}{Bazmeg! Faszom is kivan veled!}
{147}{sgnt15a}{Katona, mit csinál itt? Takarodjon vissza az õrhelyére!}
{148}{sgnt15b}{Ö-KÖR! Ha még egyszer meglátom, hogy nincs az õrhelyén, élete legszomorúbb napját fogja átélni!}
{149}{sgnt15c}{Maga mindannyiunkra veszélyt jelent! Most ennek véget vetünk!}
{150}{sgnt16}{Riadó van, és én nem ismerem fel, katona! Mutassa a papírjait!}
{151}{}{Nem lenni velünk papírok!}
{152}{}{Nem kelleni nekünk papírok!}
{153}{}{Nincsenek nálam. A ládámban vannak.}
{154}{}{Papírok? Ja, persze a papírok! Itt is vannak...}
{155}{sgnt17}{Rossz válasz! A katonáknak mindig maguknál kell hordaniuk õket! Ezt tudnod kellett volna!}
{156}{}{Hoppá.}
{157}{}{Legyen éber, katona!}
{158}{}{Jól van, ébren van! Maradjon is így!}
{159}{}{Látom, nincs jelenteni való. Maradjon az õrhelyén!}
{160}{}{Ha meglátom, hogy alszik, gondoskodom róla, hogy ne ébredjen fel belõle!}
{161}{}{Jól van, az õrhelyén van!}
{162}{}{Maradjon a posztján, katona, amíg le nem váltják!}
{163}{}{Az õrhelyén és éberen! Jól van, katona!}
{164}{}{Éberen, készenlétben! Így maradnak életben!}
{165}{}{Riadó! Behatoló a bázison!}
{166}{}{Õrség! Behatolók!}
{167}{}{Kik ezek a marhák ilyenkor... Õrség!}
{168}{}{Riadó! Kémek a bázison!}
{169}{}{Hol a francba van az az ökör közlegény?}
{200}{}{.}
{201}{}{, Uram!}
{300}{}{Mondtam, hogy ne jöjjön vissza egyenruha nélkül!!!}
