# Dialog Editor last position: 10
{100}{}{Egy õrt látsz.}
{101}{}{Egy õrt látsz harci páncélban.}
{102}{}{Egy embert látsz harci páncélban. Van egy jel a mellkasán, amit nem tudsz hova tenni.}
{103}{}{Nincs jelenteni valóm.}
{104}{}{Nálam nem történt semmi, és nálad?}
{105}{}{Nem kéne a posztodon lenni, haver? Nem jó, ha csak így mászkálsz itt.}
{106}{}{Nincs rajtad egyenruha.}
{107}{}{Jobb ha jelentkezel az õrminél és magadra kapsz egy páncélt!}
{108}{}{Nagy kockázatot vállalsz, ha egyenruha nélkül mászkálsz itt. Jelentkezz a fegyvertárban!}
{109}{}{Kik ezek a fickók?... Riadó! Behatolók!}
{110}{}{Megtámadtak bennünket! Riadó!}
{111}{}{Behatolók! Riadó!}
{112}{}{Biztonsági riadó! Zárjátok le a bázist!}
{113}{}{Zárjatok le mindent! Riadó!}
{114}{}{Behatolók! Vörös kód!}
{115}{}{Kifektetünk, ne félj!}
{116}{}{Az Enklávé lesz a világ ura!}
{117}{}{Te elbuksz, az Enklávé fennmarad!}
