# Dialog Editor last position: 22
{100}{}{Egy õrt látsz.}
{101}{}{Egy õrt látsz erõpáncélban.}
{102}{}{Egy õrt látsz, aki az erõpáncél egy különös változatát viseli. A mellkasán van egy jel, amit nem tudsz hova tenni.}
{103}{}{Nincs jelenteni valóm.}
{104}{}{Nálam nem történt semmi, és nálad?}
{105}{}{Nem kéne az õrhelyeden lenned? Nem jó, ha csak így flangálsz itt.}
{106}{}{Nincs rajtad egyenruha.}
{107}{}{Jobb, ha jelentkezel az õrminél és szerzel egy páncélt.}
{108}{}{Nagy kockázatot vállalsz, ha egyenruha nélkül mászkálsz itt. Jelentkezz a fegyvertárban!}
{109}{}{Kik ezek a fickók?... Riadó! Behatolók!}
{110}{}{Megtámadtak bennünket! Riadó!}
{111}{}{Behatolók! Riadó!}
{112}{}{Biztonsági riadó! Zárjátok le a bázist!}
{113}{}{Zárjatok le mindent! Riadó!}
{114}{}{Behatolók! Vörös kód!}
{115}{}{Kifektetünk, ne félj!}
{116}{}{Az Enklávé lesz a világ ura!}
{117}{}{Te elbuksz, az Enklávé fennmarad!}
{200}{}{...seggfej...}
{201}{}{...igen, jobb ha húzol innen...}
{202}{}{...ekkora tirpák köcsögöt...}
{203}{}{...Igen, uram! Bassza meg, uram!...}
