{100}{}{Egy őrt látsz.}
{101}{}{Egy őrt látsz erőpáncélban.}
{102}{}{Egy őrt látsz, aki az erőpáncél egy különös változatát viseli. A mellkasán van egy jel, amit nem tudsz hova tenni.}
{103}{}{Nincs jelenteni valóm.}
{104}{}{Nálam semmi, és nálad?}
{105}{}{Nem kéne a posztodon lenned? Nem jó, hogy itt csavarogsz.}
{106}{}{Nincs rajtad egyenruha.}
{107}{}{Jelentkezz az őrmesternél és kapj magadra egy páncélt!}
{108}{}{Nagy kockázatot válalsz, ha csak így flangálsz itt. Vegyél fel egy páncélt!}
{109}{}{Kik ezek a fickók?... Behatolók! Riadó!}
{110}{}{Megtámadtak bennünket! Riadó!}
{111}{}{Behatolók! Riadó!}
{112}{}{Biztonsági riadó! Zárjátok le a bázist!}
{113}{}{Helyezzétek biztonságba az állomásokat! Riadó!}
{114}{}{Behatolók! Vörös kód!}
{115}{}{Szétalázunk!}
{116}{}{Az Enklávé lesz a világ ura!}
{117}{}{Te elpusztulsz, az Enklávé fennmarad!}
{200}{}{...seggfej...}
{201}{}{...igen, jobb ha húzol innen...}
{202}{}{...ekkora tirpák köcsögöt...}
{203}{}{...Igen, uram! Bassza meg, uram!...}
{300}{}{Állj csak meg. Mit akarsz tenni azzal a légijárművel? Nincsenek tervezett repülések az elkövetkezendő napokban.}
{301}{}{Nrg?}
{302}{}{Tudatában vagyok.}
{303}{}{Sajnálom. Csak nézelődtem. Már megyek is.}
{304}{}{Változás állt be a tervekben. Én viszem ezt a madárkát.}
{310}{}{Mi? Oh, értem. Nézd, meg se érintsd. Rendben? Ha megérinted újra meghalsz.}
{311}{}{(Nyugodtan mosolyogsz, bólogatsz, aztán nekitámadsz.)}
{312}{}{(Te is indulsz a dolgodra.)}
{315}{}{Óh basszameg, úgy tűnik van egy behatolónk. Vörös Riadó! Ismétlem, Vörös Riadó!}
{316}{}{Ez jó ötletnek tűnik. Ha újra megérinted egy lövedéket eresztek a fejedbe.}
{320}{}{Rendben. Szóval evégett te...}
{321}{}{Távozni készülsz. Bocs, nem akartalak zavarni.}
{322}{}{Arra készülsz, hogy egy fontos üzenetet továbbíts a főbázisra.}
{323}{}{Csakugyan? És miről szól ez az üzenet?}
{324}{}{Ez szuper titkos. Elnézést, nem mondhatom el.}
{325}{}{Elmondom neked, de alapvető fontosságú, hogy ne add tovább ezt az információt senki másnak elkerülendő a tömegpánikot.  
Tudomásomra jutott, hogy az egyik közelmúltbeli rabszolga-szállítmányban olyan rabszolgák érkeztek akik meg voltak fertőzve egy ismeretlen és erősen halálos vírus fajtával.  
*Muszály* eljutnom azonnal a bázisra, vagy mindannyiunk élete veszélybe kerül. 
Most pedig ne vesztegesd tovább az időmet mivel egyetlen elvesztegetni való percem sincs. }
{326}{}{Igen, hiszek neked. Úgy tűnik van egy behatolónk...}
{327}{}{Bassza meg! Eh, bárhogy is. Még sosem akartak ennyi szarral megetetni itt. Menj utadra.}
{328}{}{Basszus, az rosszul hangzik. Akkor jobb, ha indulsz, nem akarom ezt a problémát magamnak. Oh és ne aggódj, senkinek sem fogom elmondani.}
{329}{}{[RENDBEN]}
