{100}{}{Egy őrt látsz.}
{101}{}{Egy őrt látsz erőpáncélban.}
{102}{}{Egy őrt látsz, aki az erőpáncél egy különös változatát viseli. A mellkasán van egy jel, amit nem tudsz hova tenni.}
{103}{}{Nincs jelenteni valóm.}
{104}{}{Nálam semmi, és nálad?}
{105}{}{Nem kéne a posztodon lenned? Nem jó, hogy itt csavarogsz.}
{106}{}{Nincs rajtad egyenruha.}
{107}{}{Jelentkezz az őrmesternél és kapj magadra egy páncélt!}
{108}{}{Nagy kockázatot válalsz, ha csak így flangálsz itt. Vegyél fel egy páncélt!}
{109}{}{Kik ezek a fickók?... Behatolók! Riadó!}
{110}{}{Megtámadtak bennünket! Riadó!}
{111}{}{Behatolók! Riadó!}
{112}{}{Biztonsági riadó! Zárjátok le a bázist!}
{113}{}{Helyezzétek biztonságba az állomásokat! Riadó!}
{114}{}{Behatolók! Vörös kód!}
{115}{}{Szétalázunk!}
{116}{}{Az Enklávé lesz a világ ura!}
{117}{}{Te elpusztulsz, az Enklávé fennmarad!}
{200}{}{...seggfej...}
{201}{}{...igen, jobb ha húzol innen...}
{202}{}{...ekkora tirpák köcsögöt...}
{203}{}{...Igen, uram! Bassza meg, uram!...}
{300}{}{Állj csak meg. Mit akarsz tenni azzal a légijárművel? Nincsenek tervezett repülések az elkövetkezendő napokban.}
{301}{}{Nrg?}
{302}{}{Tudatában vagyok.}
{303}{}{Sajnálom. Csak nézelődtem. Már megyek is.}
{304}{}{Változás állt be a tervekben. Én viszem ezt a madárkát.}
{310}{}{Mi? Oh, értem. Nézd, meg se érintsd. Rendben? Ha megérinted újra meghalsz.}
{311}{}{(Nyugodtan mosolyogsz, bólogatsz, aztán nekitámadsz.)}
{312}{}{(Te is indulsz a dolgodra.)}
{315}{}{Óh basszameg, úgy tűnik van egy behatolónk. Vörös Riadó! Ismétlem, Vörös Riadó!}
{316}{}{Ez jó ötletnek tűnik. Ha újra megérinted egy lövedéket eresztek a fejedbe.}
{320}{}{Rendben. Szóval evégett te...}
{321}{}{Távozni készülsz. Bocs, nem akartalak zavarni.}
{322}{}{Arra készülsz, hogy egy fontos üzenetet továbbíts a főbázisra.}
{323}{}{Csakugyan? És miről szól ez az üzenet?}
{324}{}{Ez szuper titkos. Elnézést, nem mondhatom el.}
{325}{}{I'll tell you, but it's absolutely essential that you don't disclose this information to anyone else, for fear of a
 mass panic. You see, it's come to my attention that one of the recent shipments of slaves is infected with an unknown, and
 highly deadly, virus strain. I *must* get to the base immediately, or all our lives could be lost. Now stop wasting my time,
 as there isn't a moment to spare.}
{326}{}{Yeah, I believe you. Looks like we got ourselves an intruder...}
{327}{}{Damnit! Ah, whatever. I never get told shit around here. Fine. Be on your way.}
{328}{}{Woah, that sounds bad. You better get moving then, I don't want this shit on my hands. Oh, and don't worry, I won't tell anyone.}
{329}{}{[RENDBEN]}
