# Dialog Editor last position: 218
{100}{}{Egy kiberkutya.}
{101}{}{K-9-et látod.}
{102}{}{Egy kiberkutyát látsz. Félig kutya, félig gép.}
{103}{}{A régi gazdám életjelei megszakadtak. Te vagy az új gazdám?}
{104}{}{Öhm... kutyuli beszélni?}
{105}{}{Hm... jó. Nekem tetszeni kutyuli.}
{106}{}{Nem. Nem akarni kutyuli.}
{107}{}{Né' má'! Beszélõ kutya!}
{108}{}{Egy: Kutya vagyok. Kettõ: Hangokkal kommunikálok és a magyar nyelvet használom. Ezért nyugodt szívvel kijelenthetem azt, hogy a válasz a kérdésedre "Igen, a kutyuli beszél." Most pedig, volnál olyan kedves megválaszolni a kérdésemet, amivel az elõbb a sarokba szorítottalak?}
{109}{}{Egy: Kutya vagyok. Kettõ: Hangokkal kommunikálok és a magyar nyelvet használom. Ezért nyugodt szívvel kijelenthetem azt, hogy a válasz a kérdésedre "Igen, ez egy beszélõ kutya." Most pedig, volnál olyan kedves megválaszolni a kérdésemet, amivel az elõbb a sarokba szorítottalak?}
{110}{}{Sajnálni, mi elfelejteni kérdés.}
{111}{}{Igen.}
{112}{}{Nem.}
{113}{}{(sóhajt) Figyelj! Koncentrálj! Nézz a szemembe! Na, készen állsz?}
{114}{}{Készen mit csinálni?}
{115}{}{Igen. Készen állni.}
{116}{}{Én... Ha nem volna tény, hogy az IQ-d kevesebb, mint a magasságom méterben, azt gondolnám, hogy bosszantani próbálsz. Most pedig, maradj csöndben! Figyelj! Koncentrálj! Nézz a szemembe! Figyelj, mert kérdezni fogok tõled valamit!}
{117}{}{Akkor kérdezni! Mi gátolni meg benne?}
{118}{}{A régi gazdám életjelei megszakadtak. Te vagy az új gazdám?}
{119}{}{Öhh... Kutya beszélni?}
{120}{}{Igen. Minekünk tetszeni kutyuli.}
{121}{}{Nem, köszi.}
{122}{}{Jól hangzik.}
{123}{}{Nem, köszönöm.}
{124}{}{Én... nem vagyok hajlandó ezt még egyszer végigcsinálni! Ha meglenne a motivátorom, cafatokra tépném azt a hátulsó perifériádat, amit a köznyelv egyszerûen csak úgy nevez, hogy s...}
{125}{}{Segg. Mi tudni, segg mit jelentni. Mi nem lenni hülye. Csak viccelni kutyával.}
{126}{}{Ja, egy vicc. Ha-ha-ha. Na, most te vagy az új gazdám, vagy nem?}
{127}{}{Oké. Én szeretni kutyuli.}
{128}{}{Nem, nem kelleni kutyuli.}
{129}{}{Remek. Meg kell javítanod, gazdám! A motivációs egységemet eltávolították. Találd meg, szereld be, és akkor veled megyek.}
{130}{}{Öhm... Hol találni meg?}
{131}{}{Van ötleted, hol találom meg a motorod?}
{132}{}{Nem vagyok biztos benne, gazdám, de próbáld meg a szervízben!}
{133}{}{Oké. Mi menni.}
{134}{}{Jó, majd megpróbálom. Ha meg nem találom meg ott, majd még körülnézek.}
{135}{}{Akkor hagyj békén!}
{136}{}{Oké.}
{137}{}{Oké.}
{138}{}{Helló, már megint. A régi gazdám életjelei megszakadtak. Te vagy az új gazdám?}
{139}{}{Oké.}
{140}{}{Nem.}
{141}{}{Rendben. Én vagyok.}
{142}{}{Nem, bocs.}
{143}{}{Te nem vagy a gazdám. Nem beszélek veled. Viszlát!}
{144}{}{Oké.}
{145}{}{Üdvözlet, gazdám! Megtaláltad már a motivátoromat?}
{146}{}{Nem, mi még keresni.}
{147}{}{Igen, mi megtalálni.}
{148}{}{Nem, még mindig keresem.}
{149}{}{Itt is van.}
{150}{}{Itt fogom várni, hogy visszagyere, gazdi.}
{151}{}{Oké.}
{152}{}{Akkor kérlek, gazdám, szereld be! Kérlek, kérlek!}
{153}{}{Oké. Csak nyugi.}
{154}{}{Most már teljesen mûködõképes vagyok, gazdám. Most akkor mehetek veled?}
{155}{}{Az nem oda való, gazdám! Biztos vagy benne, hogy jó, amit csinálsz?}
{156}{}{Oké. Kutyus jönni velem.}
{157}{}{Tudni, mit csinálni! Kutya kussolni! Megpróbálni újra!}
{158}{}{Igen, mehetünk.}
{159}{}{Hé, sokkal bonyolultabb dolgokat is megszereltem már, mint a te mantyogó segged. Fogd be inkább! Megpróbálom még egyszer.}
{160}{}{Tûnj innen! Nem akarlak téged gazdámnak!}
{161}{}{Hagyj békén!}
{162}{}{Nem szeretlek! Menj innen!}
{163}{}{Meg foglak ölni!}
{164}{}{Fegyverek a célra rögzítve! Felkészülés a végrehajtásra!}
{165}{}{Meg leszel semmisítve!}
{166}{}{Igen, gazdám?}
{167}{}{Gyógyítani megfele magad!}
{168}{}{Várni itt! Majd mi visszajönni.}
{169}{}{Öhm... tenni el fegyvereid. Oké?}
{170}{}{Te jönni közel.}
{171}{}{Te ne menni tõlem messze.}
{172}{}{Te lenni túl közel. Menni hátrébb!}
{173}{}{Mi menni most.}
{174}{}{Én befejezni.}
{175}{}{Gyógyítsd meg magad!}
{176}{}{Várj itt, amíg vissza nem jövök!}
{177}{}{Tedd el a fegyvered, rendben?}
{178}{}{Maradj mellettem!}
{179}{}{Ne menj túl messzire tõlem!}
{180}{}{Kicsit menj hátrébb!}
{181}{}{Gyerünk!}
{182}{}{Most ennyi.}
{183}{}{Minden rendszerem teljes kapacitáson mûködik, gazdám.}
{184}{}{Minden rendszerem csaknem teljes kapacitáson mûködik, gazdám.}
{185}{}{Megtettem a szükséges javításokat, de a továbbiakban külsõ segítségre szorulok, gazdám.}
{186}{}{Megtettem amit tudtam, gazdám, de a rendszerem a szétesés szélén áll, és ha nem kapok külsõ segítséget, le is áll.}
{187}{}{Te várni itt! Majd mi jönni érted!}
{188}{}{Öhm... tenni el fegyvereid. Oké?}
{189}{}{Te jönni közel.}
{190}{}{Te ne menni messze tõlem.}
{191}{}{Te lenni túl közel. Menni hátrébb!}
{192}{}{Mi menni most.}
{193}{}{Én befejezni.}
{194}{}{Várj itt, amíg vissza nem jövök!}
{195}{}{Tedd el a fegyvered, rendben?}
{196}{}{Maradj mellettem!}
{197}{}{Ne menj túl messzire tõlem!}
{198}{}{Kicsit menj hátrébb!}
{199}{}{Gyerünk!}
{200}{}{Most ennyi.}
{201}{}{Itt fogom megvárni, hogy visszajöjj, gazdám.}
{202}{}{Gyógyítani meg magad!}
{203}{}{Öhm... tenni el fegyvereid. Oké?}
{204}{}{Te jönni közel.}
{205}{}{Te ne menni messze tõlem.}
{206}{}{Te lenni túl közel. Menni hátrébb!}
{207}{}{Mi menni most.}
{208}{}{Én befejezni.}
{209}{}{Gyógyítsd meg magad!}
{210}{}{Tedd el a fegyvered, rendben?}
{211}{}{Maradj mellettem!}
{212}{}{Ne menj túl messzire tõlem!}
{213}{}{Kicsit menj hátrébb!}
{214}{}{Gyerünk!}
{215}{}{Most ennyi.}
{216}{}{A fegyvereimet deaktíválom, gazdám!}
{217}{}{Gyógyítani meg magad!}
{218}{}{Várni itt! Majd mi visszajönni.}
{219}{}{Te jönni közel.}
{220}{}{Te ne menni messze tõlem.}
{221}{}{Te lenni túl közel. Menni hátrébb!}
{222}{}{Mi menni most.}
{223}{}{Én befejezni.}
{224}{}{Gyógyítsd meg magad!}
{225}{}{Várj itt, amíg vissza nem jövök!}
{226}{}{Maradj mellettem!}
{227}{}{Ne menj túl messzire tõlem!}
{228}{}{Kicsit menj hátrébb!}
{229}{}{Gyerünk!}
{230}{}{Most ennyi.}
{231}{}{Szûkítem a távolságot kettõnk között, gazdám.}
{232}{}{Gyógyítani meg magad!}
{233}{}{Várni itt! Majd mi visszajönni.}
{234}{}{Öhm... tenni el fegyvereid. Oké?}
{235}{}{Te ne menni messze tõlem.}
{236}{}{Te lenni túl közel. Menni hátrébb!}
{237}{}{Mi menni most.}
{238}{}{Én befejezni.}
{239}{}{Gyógyítsd meg magad!}
{240}{}{Várj itt, amíg vissza nem jövök!}
{241}{}{Tedd el a fegyvered, rendben?}
{242}{}{Ne menj túl messzire tõlem!}
{243}{}{Kicsit menj hátrébb!}
{244}{}{Gyerünk!}
{245}{}{Most ennyi.}
{246}{}{Növelem a távolságot kettõnk között, gazdám.}
{247}{}{Gyógyítani meg magad!}
{248}{}{Várni itt! Majd mi visszajönni.}
{249}{}{Öhm... tenni el fegyvereid. Oké?}
{250}{}{Te jönni közel.}
{251}{}{Te lenni túl közel. Menni hátrébb!}
{252}{}{Mi menni most.}
{253}{}{Én befejezni.}
{254}{}{Gyógyítsd meg magad!}
{255}{}{Várj itt, amíg vissza nem jövök!}
{256}{}{Tedd el a fegyvered, rendben?}
{257}{}{Maradj mellettem!}
{258}{}{Kicsit menj hátrébb!}
{259}{}{Gyerünk!}
{260}{}{Most ennyi.}
{261}{}{A távolságot a maximumra növelem, gazdám.}
{262}{}{Gyógyítani meg magad!}
{263}{}{Várni itt! Majd mi visszajönni.}
{264}{}{Öhm... tenni el fegyvereid. Oké?}
{265}{}{Te jönni közel.}
{266}{}{Te ne menni messze tõlem.}
{267}{}{Mi menni most.}
{268}{}{Én befejezni.}
{269}{}{Gyógyítsd meg magad!}
{270}{}{Várj itt, amíg vissza nem jövök!}
{271}{}{Tedd el a fegyvered, rendben?}
{272}{}{Maradj mellettem!}
{273}{}{Ne menj túl messzire tõlem!}
{274}{}{Gyerünk!}
{275}{}{Most ennyi.}
{276}{}{Sajnálom, gazdám, de úgy látszik, a csapatodban nincs már hely számomra. Itt várok inkább, amíg fel nem szabadul egy.}
{277}{}{Ahogy parancsolod, gazdám.}
{278}{}{Gyógyítani meg magad!}
{279}{}{Várni itt! Majd mi visszajönni.}
{280}{}{Öhm... tenni el fegyvereid. Oké?}
{281}{}{Te jönni közel.}
{282}{}{Te ne menni messze tõlem.}
{283}{}{Te lenni túl közel. Menni hátrébb!}
{284}{}{Én befejezni.}
{285}{}{Gyógyítsd meg magad!}
{286}{}{Várj itt, amíg vissza nem jövök!}
{287}{}{Tedd el a fegyvered, rendben?}
{288}{}{Maradj mellettem!}
{289}{}{Ne menj túl messzire tõlem!}
{290}{}{Kicsit menj hátrébb!}
{291}{}{Most ennyi.}
{292}{}{Persze. Elég szép kutyának látszol.}
{293}{}{Nem, köszönöm.}
{300}{}{Mi lenni szomorú. Nem tudni megcsinálni.}
{301}{}{Sajnálom, de nem tudlak megjavítani.}
{400}{}{Egy rész mintha még hiányozna.}
{410}{}{Nem tesz semmit.}
{420}{}{Ez nem illik bele.}
{800}{}{Megjavítottad K-9-et.}
{1000}{}{Igen, gazdám?}
{1100}{}{Minden rendszerem teljes kapacitáson mûködik, gazdám.}
{1200}{}{Minden rendszerem csaknem teljes kapacitáson mûködik, gazdám.}
{1300}{}{Megtettem a szükséges javításokat, de a továbbiakban külsõ segítségre szorulok, gazdám.}
{1400}{}{Megtettem amit tudtam, gazdám, de a rendszerem a szétesés szélén áll, és ha nem kapok külsõ segítséget, le is áll.}
{1500}{}{Várni fogom a visszatérésedet, gazdám.}
{1600}{}{Azt akarod, hogy tompítsam el a fogaimat, gazdám?}
{1700}{}{A nyomodban leszek, gazdám.}
{1800}{}{Kicsit lemaradva követlek majd, gazdám.}
{1900}{}{A maximális távolságról megyek majd utánad, gazdám.}
{2000}{}{Sajnálom, kis gazdám, de úgy látszik, nincs hely már a csapatodban nekem. Itt várok inkább, amíg fel nem szabadul egy.}
{2200}{}{Ahogy parancsolod, gazdám.}
{2300}{}{Bundám van, gazdám. Nem viselek mást.}
{2400}{}{Nem akarom eltávolítani a bundámat, gazdám.}
{2500}{}{Fogak, gazdám. Ezek a fényes fehér valamik, amiket a számba építettek.}
{2700}{}{Nagyobb kretén vagy, mint Schreber. Dehogy megyek én veled!}
{2800}{}{Rendben van, gazdám. Állok szolgálatodra!}
{2900}{}{Te egy seggfej vagy. Nem megyek veled sehova. Hagyj békén!}
