# Dialog Editor last position: 18
{100}{}{Egy szerelõt látsz.}
{101}{}{Kevin, a szerelõ.}
{102}{}{Egy embert látsz katonai gyakorlóban. A kinézetbõl ítélve inkább szerelõ lehet, mint katona.}
{200}{}{Most nem beszélhetek veled. Menj Quincyhez!}
{201}{}{Quincy a fõnök. Vele beszélj!}
{202}{}{Még kezdõ szerelõ vagyok. Te biztos Quincyt keresed.}
{300}{}{Nincs rajtad egyenruha.}
{301}{}{Jobb lenne, ha felöltöznél.}
{302}{}{Nagy kockázatot vállalsz, hogy egyenruha nélkül mászkálsz itt. Jelentkezz a fegyvertárban!}
{400}{}{Kik ezek a fickók?... Riadó! Behatolók!}
{401}{}{Megtámadtak bennünket! Riadó!}
{402}{}{Behatolók! Riadó!}
{500}{}{Picsába! Kezdjük gyorsan az archiválást!}
{501}{}{Minden titkos mûveletet hagyjatok abba}
{502}{}{Biztosítsátok a rendszert!}
{600}{}{Szerelõ vagyok, nem katona!}
{601}{}{"A hegyes végén lévõ lézerdiódát irányítsa rá a célpontra, aztán húzza meg a ravaszt!"}
{602}{}{Segítség! Segítség! Mindenki a szervízbe!}
