{100}{}{Egy er?páncélt visel? egyén.}
{101}{}{A navarrói bázisparancsnok.}
{102}{}{Egy ?rt látsz, aki az er?páncél egy különös változatát viseli. A mellkasán van egy jel, amit nem tudsz hova tenni.}
{103}{}{Kik ezek a fickók?... Riadó! Behatolók!}
{104}{}{Nem érek rá a katonákkal társalogni. Lelépni!}
{105}{}{Legf?bb ideje, hogy a föld alá kerülj!}
{106}{}{Oké.}
{107}{}{Megmondtam, hogy nincs id?m magára. Hagyja el az irodámat és csak akkor jöjjön vissza, ha én küldök magáért. Lelépni!}
{108}{}{A felettesei parancsának megtagadása hazaárulás. Nincs id?m rögtönítél? bíróságot felállítani, szóval az ügyet személyesen veszem a kezembe.}
{109}{}{Oké.}
{110}{}{Baszd meg!}
{111}{}{Az FBK itt van a szekrényemben. Mondd meg az ügyeletes tisztnek, lépjen kapcsolatba velem, ha már elzárta a kódkártyát. Lelépni!}
{112}{}{Igen, uram!}
{113}{}{Haladjon már katona, nincs id?m magával foglalkozni.}
{114}{}{Igen, uram!}
{115}{}{Hagyja békén a szekrényemet, különben szíjat hasítok a hátából!}
{116}{}{Igen, uram!}
{117}{}{Riadó van, és nem ismerem fel. Mutassa a papírjait, katona!}
{118}{}{Milyen papírokat?}
{119}{}{Kapd be!}
{120}{}{Hát, úgy t?nik, nincsenek nálam...}
{121}{}{Papírok? Ja, persze a papírok! Itt vannak, ni...}
{122}{}{Rossz válasz! A katona mindig magánál hordja a papírjait! Ezt tudnia kellett volna!}
{123}{}{Baszd meg!}
{124}{}{Hagyja békén a szekrényemet, különben szíjat hasítok a hátából!}
{125}{}{Legf?bb ideje, hogy a föld alá kerülj!}
