# Dialog Editor last position: 47
{100}{}{Számítógép.}
{101}{}{Számítógép.}
{102}{}{A navarrói bázis számítógépe.}
{103}{}{Kérem, adja meg a jelszót!}
{104}{}{Csacsifül.}
{105}{}{Elfelejteni...}
{106}{}{Baszd meg a jelszavadat!}
{107}{}{Betörés a rendszerbe...}
{108}{}{Üdvözöljük az Enklávé rendszerén. Jelenleg csak korlátozott hozzáférés lehetséges. A könnyebb használat érdekében minden terminált magyar nyelvû konzollal szereltek fel. A kérdéseket egyszerû mondatok formájában adja meg!}
{109}{}{Miben segíthetek?}
{110}{}{Hol gépmadár tervek?}
{111}{}{Hol Enklávé fõbázis?}
{112}{}{Hol fegyvertár?}
{113}{}{Hol bázisparancsnok?}
{114}{}{Gondolni csak ennyi van.}
{115}{}{Hol találhatók a gépmadár tervek?}
{116}{}{Hol található az Enklávé fõbázis?}
{117}{}{Hol van a fegyvertár?}
{118}{}{Hol van a parancsnok irodája?}
{119}{}{Azt hiszem, ennyi.}
{120}{}{Keresés... Leltári adatok... Adat letöltve. A jelenlegi jelentés szerint csak egyetlen teljes gépmadár-tervrajz található a bázison. Négy tervrajzot rendeltek ebbe a körzetbe. Négy tervrajz szállítása megtörtént. Három terv elveszett. A tervrajzot a szervízben tárolják.}
{121}{}{Oké. Hol szervíz?}
{122}{}{Jól van. Hol találom a szervízt?}
{123}{}{Keresés... Bázis-tervrajzok... Adat letöltve. A szervíz a bázis felsõ szintjén található az észak-keleti negyedben.}
{124}{}{Köszi.}
{125}{}{Keresés... Földrajzi adatok... Adat letöltve. A fõparancsnokság a Csendes-óceánon található 175 tengeri mérföldre a kaliforniai partoktól. Koordináták: Északi szélesség 37,18'' Nyugati hosszúság 120,7''.}
{126}{}{Mi szart ez jelenteni?}
{127}{}{Mi a szart jelent ez?}
{128}{}{Keresés... Szleng szótár... Információ feldolgozva. Ez négy dolgot jelent:
                                                         1, Jó mélyen van az óceánon.                                      2, Kalifornia partjaitól is messze van.                            3, San Franciscótól nyugatra található.                          4, Ha nem tanultál földrajzot, úgysem fogod megérteni.         }
{129}{}{Hogy menni oda?}
{130}{}{Hogyan juthatok oda?}
{131}{}{Keresés... Logisztikai adatbázis... Adat letöltve. A logisztikai napló szerint 1257 lehetséges módja van az odajutásnak. Viszont, most csak kettõ elérhetõ: A gépmadár-szállítás igénybevétele a navarrói bázison, vagy hajóval történõ szállítás San Franciscóban. Az öbölben állomásozó hajót a biztonsági parancsnokság a 9837-334-27A sz. rendelkezés hatálya alá vonja, tehát kódkártya nélkül mûködésképtelen. A felülírásahoz az F.B.K. szükséges, amit jelenleg a bázisparancsnok tart magánál.}
{132}{}{Oké.}
{133}{}{Megvan.}
{134}{}{Keresés... Bázis-tervrajzok... Adat letöltve. A fegyvertár a föld alatti szinten, a bázis észak-nyugati részében található.}
{135}{}{Ah.}
{136}{}{Oké.}
{137}{}{Keresés... Bázis-tervrajzok... Adat letöltve. A bázisparancsnok irodája a föld alatti szinten, a bázis észak-keleti részében található.}
{138}{}{Jól van.}
{139}{}{Jól van.}
{140}{}{Köszönjük, hogy az Enklávé-Netet használta. Kilépés...}
{141}{}{Vége.}
{142}{}{Parancs?}
{143}{}{Engedély nélküli hozzáférés történt a fõterminálon. Biztonsági riadó!}
{144}{}{Üdvözlés indítása.}
{145}{}{Picsába!}
{146}{}{Biztonsági rendszerzár feloldása folyamatban.}
