# Dialog Editor last position: 40
{100}{}{Egy technikust látsz.}
{101}{}{Egy Enklávé technikust látsz. }
{102}{}{Egy fickót látsz laborköpenyben. Nagyon magabiztosnak tûnik.}
{103}{}{Igen, katona?}
{104}{}{Mi lenni ez hely?}
{105}{}{Csak mondani üdv! Mostan menni.}
{106}{}{Mi ez a hely?}
{107}{}{Csak beugrottam. Most megyek.}
{108}{}{Ez a gépterem. Az ott a fõegység, a terminál, mellette az interfésszel, azok ott pedig a hololemez-tároló egységek.}
{109}{}{Óh! Mit csinálni itt?}
{110}{}{Szóval, mi a munkája itt?}
{111}{}{A rangidõs számítógép elemzõ vagyok. Ezzel a sok cuccal kell törõdnöm, és biztosítani, hogy mûködjenek.}
{112}{}{Hûûû... Lehet használni csuda nagy gép?}
{113}{}{Nem érteni. Inkább elmenni mostan.}
{114}{}{Mondja csak, használhatnám a gépet egy percre? Tudja, kis ellenõrzés, meg miegymás...}
{115}{}{Jó volt beszélgetni magával. Majd még találkozunk.}
{116}{}{Nos... nem engedhetem, hogy más is használja a gépet a képzett személyzeten kívül. Ez egy komplex és érzékeny rendszer, ugye megérti?}
{117}{}{Kérem! Megígérni, nem rontani széjjel.}
{118}{}{Megígérem, hogy nem vágom haza.}
{119}{}{Jól van. Beléphet a rendszerbe azon a terminálon keresztül. De csak óvatosan, kérem! Mindkettõnket lelövik, ha baja lesz a gépnek Ja, a vendégjelszó "Csacsifül".}
{120}{}{Sajnálom, de még a hivatalos állománynak sem engedhetem meg, hogy hozzányúljon a gépekhez.}
{121}{}{Csacsifül? Mi az a csacsifül?}
{122}{}{Ok. Én érteni elsõre.}
{123}{}{Csacsifül? Mi a rák ez?}
{124}{}{Oké, értem.}
{125}{}{"Csacsifül" a barátnõm beceneve. Szerintem kedves. Õ az az õr, aki kint áll az ajtó elõtt.}
{126}{}{Ok, jó. Köszönni.}
{127}{}{Aha... kedves. Köszönöm.}
{128}{}{Magán nincs egyenruha!}
{129}{}{Jobb lenne, ha felöltözne. A fegyvertár a terem végén van balra.}
{130}{}{Nagy kockázatot vállal, ha csak így járkál itt! Gyorsan szerezzen egy egyenruhát!}
{131}{}{Maga meg ki a fene... Riadó! Behatolók!}
{132}{}{Bejutottak, riadó!}
{133}{}{Behatolók, riadó!}
{134}{}{Kurva eget! Kezdjük gyorsan az archiválást!}
{135}{}{Abbahagyni minden titkos mûveletet!}
{136}{}{Biztosítsátok a rendszert!}
{137}{}{Tudós vagyok, nem katona!}
{138}{}{"A hegyes végén lévõ lézerdiódát irányítsa rá a célpontra, aztán húzza meg a ravaszt!"}
{139}{}{Segítség! Erõsítést a számítógép-laborba!}
