# Dialog Editor last position: 13
{100}{}{Technikus.}
{101}{}{Egy számítógép-technikus.}
{102}{}{Ez az ember egy rakás tollat hord a köpenye zsebében.}
{103}{}{Jó napot, katona!}
{104}{}{Kérem, ne nyúljon semmihez!}
{105}{}{Katonáknak nem szabadna itt lennie.}
{106}{}{Magán nincs egyenruha!}
{107}{}{Jobb, ha felöltözik! A fegyvertár a terem végén van balra.}
{108}{}{Nagy kockázatot vállal, ha csak így járkál itt! Gyorsan szerezzen egy egyenruhát!}
{109}{}{Maga meg ki a fene... Riadó! Behatolók!}
{110}{}{Bejutottak, riadó!}
{111}{}{Behatolók, riadó!}
{112}{}{Kurva eget! Kezdjük meg az archiválást!}
{113}{}{Abbahagyni minden titkos mûveletet!}
{114}{}{Biztosítsátok a rendszert!}
{115}{}{Tudós vagyok, nem katona!}
{116}{}{"A hegyes végén lévõ lézerdiódát irányítsa rá a célpontra, aztán húzza meg a ravaszt!"}
{117}{}{Segítség! Erõsítést a számítógép-laborba!}
