# Dialog Editor last position: 52
{100}{}{Technikus.}
{101}{}{Számítógép-technikus.}
{102}{}{Egy laborköpenyes embert látsz. Nagyon magabiztosnak tûnik.}
{103}{}{Igen, uram?}
{104}{}{Én lenni új itten. Kérdezni kell néhány dolog.}
{105}{}{Csak beugrani. Most pedig menni.}
{106}{}{Helló, új vagyok és szeretnék kiigazodni a bázison. Segít nekem?}
{107}{}{Bocs, hogy zavartam. Már megyek is.}
{108}{}{Természetesen, katona.}
{109}{}{Miben segíthetek?}
{110}{}{Mi lenni ez hely?}
{111}{}{Mi munkád?}
{112}{}{Hol lenni fõbázis?}
{113}{}{Keresni gépmadár tervek. Hol lenni?}
{117}{}{Menni mostan.}
{118}{}{Mi ez a hely?}
{119}{}{Mit dolgozik itt?}
{120}{}{Hol található az Enklávé fõ bázisa?}
{121}{}{Vetnem kéne néhány pillantást a gépmadár tervekre. Hol tartják õket?}
{125}{}{Semmiben. Mennem kell.}
{126}{}{Ez az operatív parancsnokság. Innen kezeljük a fõbázis és a kihelyezett megfigyelõpontok közötti kummunikációt. }
{127}{}{Értem. Kérdezni még.}
{128}{}{Értem. Van még néhány kérdésem.}
{129}{}{Elsõ osztályú technikus vagyok, és fõnöki munkakörben dolgozom. Én felelek azért, hogy a többiek ne rontsanak el semmit.}
{130}{}{Öhm... ja.}
{131}{}{Jól van, csak így tovább!}
{132}{}{Katona, ezt az információt mindenkinek tudni kell. Ha mégis meg kell kérdezie, akkor ez nem magára tartozik.}
{133}{}{Oké.}
{134}{}{Na, gyerünk, nem vagyok én hülye nomád vagy ilyesmi. Ugyanabban a csapatban játszunk. Látja ezt a jelet a páncélomon?}
{135}{}{Értem.}
{136}{}{Igen, uram. A fõbázis a Csendes-óceánon található. Nem bánja, ha megtudakolom, miért kérdi?}
{137}{}{Katona, mondtam, hogy ezt az információt mindenkinek tudnia kell.}
{138}{}{Biztonsági okokból ellenõrzöm, hogy a személyzet tagjai tudatában vannak-e fontos információknak. Most pedig mondja el az összes lehetséges odajutási módot, amit ismer!}
{139}{}{Értem.}
{140}{}{Igenis, uram! Elõször is, az elsõdleges mód a gépmadarak használata. Ám a kezelésük nehézkessége miatt valószínûtlen, hogy képzetlenek vezetni tudnák õket. A második lehetséges mód a  San Francisco-i öbölben veszteglõ tanker. A hajót hatástalanították, és kódkártya kell az újraindításához, amit a bázisparancsnok tart magánál. A harmadik és egyben utolsó mód az úszás, melynek túlélési esélye a nulla felé konvergál.}
{141}{}{Köszi.}
{142}{}{Köszi.}
{143}{}{A szervízben tárolják õket, a légiirányítók mellett.}
{144}{}{Oké.}
{145}{}{Fogom.}
{155}{}{Maga valami nudista, hogy egyenruha nélkül mászkál?}
{156}{}{Ha az õrmester elkapja egyenruha nélkül, szétrúgja a seggét!}
{157}{}{Miért nincs magán egyenruha?}
{158}{}{Szent szar! Megtámadtak bennünket!}
{159}{}{Behatolók! Hívjátok az õrséget!}
{160}{}{Õrség! Behatolók az operatív parancsnokságon!}
{161}{}{Mi van itt? Megtámadtak bennünket?}
{162}{}{Miért szól a sziréna? Mi történt?}
{163}{}{Mi folyik itt?}
{164}{}{Én csak egy technikus vagyok, ne bántson!}
{165}{}{Nem harcolni jöttem, csak továbbképzésre!}
{166}{}{Ez egy laborköpeny, nem páncél! Már itt sem vagyok!}
