# Dialog Editor last position: 10
{100}{}{Egy vékony, koszos ember áll elõtted.}
{150}{}{Flick, aki éppen a tökét vakarássza. }
{151}{}{Ennek a mocskos alaknak idõnként visszataszítóan rángatózik az arca.}
{200}{}{Takaroggyá kifele, hallod-e, faszkalap!?}
#Felejteni kell az ilyesmi tukorforditasat (bass)
{201}{}{Mi van má', hurkatõ'tõ! Húzzá' innét elfele!}
{202}{}{Megsüketûté', vagy csak meghülyûté'?}
{203}{}{Na, mongyad, mi a gondod!}
{204}{}{Takaroggyá' innét francba!}
{220}{}{Egen? Flick vagyok. Mi faszt akarol, mi?}
{221}{}{Na, mi legyen? Idõmet pazarlom itten csak, hela!}
{222}{}{Mi ez a bolondos akcentus, Flick?}
{223}{}{Mi a fenével foglalkozol te itt?}
{224}{}{Meg akarok találni egy Menedéket és egy Vic nevû kereskedõt. Nem tudsz segíteni?}
{225}{}{Kereskedni akarok.}
{240}{}{Kõne még valami?}
{241}{}{Éppenséggel megnézném még egyszer, milyen cuccaid vannak.}
{242}{}{Tulajdonképpen akarok valamit kérdezni.}
{243}{}{Egyelõre megteszi. Majd találkozunk.}
{260}{}{Kibaszott beszerzõ vagyok én, mit gondósz? Én vagyok helyi jó szamuráj-itánus.}
{261}{}{Hogy mondod?}
{262}{}{He, öö, rendben... hadd kérdezzek valamit!}
{263}{}{Na, jó... oké. Viszlátásra, Flick!}
{280}{}{Azér' dógozok, hogy a kis paisanos érezzék jól maguk.}
{281}{}{Hogy a kis pajzánok jól érezzék magukat?}
{290}{}{Pai-san-o, tudod, kölkök. Én kölkeim.}
{291}{}{A te kölkeid?}
{292}{}{Õszintén remélem, hogy most nem gyerekek pajzánkodásáról fogok hallani. Hadd kérdezzek valami mást!}
{300}{}{Bizony, nekem dógoznak. Hoznak nekem dógokat. Aprócska dógokat. Tudod...}
{301}{}{Ömm, nem tudom...}
{302}{}{Aha, oké. Akkor hadd kérdezzek valami mást!}
{303}{}{Értem már. Nem akarlak ööö... kellemetlen helyzetbe hozni. Viszlát!}
{315}{}{Ide hozzák cuccokat, amit talá'nak. Ici-pici dógokat. Ami má' senkinek se nem kõ. Cserébe gongyukat viselem nekijjük.}
{316}{}{Remek egyezségnek látszik.}
{325}{}{(Flick vállat von). E'vagyunk, mint befõtt...}
{326}{}{Akkor hadd kérdezzek valami mást!}
{327}{}{Biztos hoztak valamit, amiért érdemes alkudni. Hadd nézzem, mid van!}
{328}{}{Csak szétnéztem. Rendben, viszlát, Flick!}
{340}{}{Mirõ' beszé'sz? Aztat gondolod, hogy valami kibaszott pirla vagyok? Valami süket filio di puttana? Valami bohócnak képzõ'sz? Azé' vagyok tán itten, hogy szórakoztassalak?}
{341}{}{Ó, nem. Elnézést, csak kiváncsi voltam. Hadd kérdezzek valami mást!}
{342}{}{Aha, így igaz szarfej. És semmi nem fog jobban mulattatni, mint a haláltusád.}
{343}{}{Rendben, ha ennyitõl megsértõdtél, akkor lelépek.}
{360}{}{Menedék, he? Talán Mama tuggya valamit, mer' én nem. De én ismerem Vic gyereket, Metzgerné' van az a porca pistola.}
{361}{}{Vic? Nem õ az ott veled? Marharépa... a Mamát viszont ismerem.}
{362}{}{Ki az a Metzger?}
{363}{}{Ki az a Mama?}
{364}{}{Kösz. Hadd kérdezzek valami mást!}
{365}{}{Kösz, csak ennyit akartam tudni. Viszlát!}
{380}{}{Mama kosztoldát üzemeltet városnak keleti részin. Temetõ mögött. Szép hely az ottan, van neki jó pasta. Mama mia!}
{381}{}{Kösz. Mi van azzal a Metzger gyerekkel, akinél Vic van?}
{382}{}{Kösz. Kérdeznék még valami mást.}
{383}{}{Kösz, csak ennyit akartam tudni. Viszlát!}
{400}{}{Ez igaz. Metzger, az a stronzo, halott. De nem tudni, mi történje Vic-kel.}
{401}{}{Az a Metzger, az egy igazi rompiballe. Õ Rabszolga-Céh vezére, keleti részen, északra Mama vendéglõjétõ'. Akárhogyis, nála van Vic, tudom.}
{402}{}{Kösz, mit tudsz a Mamáról?}
{403}{}{Kösz. Hadd kérdezzek valami mást!}
{404}{}{Kösz, csak ennyit akartam tudni. Viszlát!}
