{100}{}{Egy vékony, koszos ember áll el?tted.}
{150}{}{Flick, aki éppen a tökét vakarássza. }
{151}{}{Ennek a mocskos alaknak id?nként visszataszítóan rángatózik az arca.}
{200}{}{Takaroggyá kifele, hallod-e, faszkalap!?}
{201}{}{Mi van má', hurkat?'t?! Húzzá' innét elfele!}
{202}{}{Megsüket?té', vagy csak meghüly?té'?}
{203}{}{Na, mongyad, mi a gondod!}
{204}{}{Takaroggyá' innét francba!}
{220}{}{Egen? Flick vagyok. Mi faszt akarol, mi?}
{221}{}{Na, mi legyen? Id?met pazarlom itten csak, hela!}
{222}{}{Mi ez a bolondos akcentus, Flick?}
{223}{}{Mi a fenével foglalkozol te itt?}
{224}{}{Meg akarok találni egy Menedéket és egy Vic nev? keresked?t. Nem tudsz segíteni?}
{225}{}{Kereskedni akarok.}
{240}{}{K?ne még valami?}
{241}{}{Éppenséggel megnézném még egyszer, milyen cuccaid vannak.}
{242}{}{Tulajdonképpen akarok valamit kérdezni.}
{243}{}{That did it. See you around, Flick.}
{260}{}{Kibaszott beszerz? vagyok én, mit gondósz? Én vagyok helyi jó szamuráj-itánus.}
{261}{}{Hogy mondod?}
{262}{}{He, öö, rendben... hadd kérdezzek valamit!}
{263}{}{Na, jó... oké. Viszlátásra, Flick!}
{280}{}{Azér' dógozok, hogy a kis paisanos érezzék jól maguk.}
{281}{}{Hogy a kis pajzánok jól érezzék magukat?}
{290}{}{Pai-san-o, tudod, kölkök. Én kölkeim.}
{291}{}{A te kölkeid?}
{292}{}{?szintén remélem, hogy most nem gyerekek pajzánkodásáról fogok hallani. Hadd kérdezzek valami mást!}
{300}{}{Bizony, nekem dógoznak. Hoznak nekem dógokat. Aprócska dógokat. Tudod...}
{301}{}{Ömm, nem tudom...}
{302}{}{Aha, oké. Akkor hadd kérdezzek valami mást!}
{303}{}{Értem már. Nem akarlak ööö... kellemetlen helyzetbe hozni. Viszlát!}
{315}{}{Ide hozzák cuccokat, amit talá'nak. Ici-pici dógokat. Ami má' senkinek se nem k?. Cserébe gongyukat viselem nekijjük.}
{316}{}{Remek egyezségnek látszik.}
{325}{}{(Flick vállat von). E'vagyunk, mint bef?tt...}
{326}{}{Akkor hadd kérdezzek valami mást!}
{327}{}{Biztos hoztak valamit, amiért érdemes alkudni. Hadd nézzem, mid van!}
{328}{}{Csak szétnéztem. Rendben, viszlát, Flick!}
{340}{}{Mir?' beszé'sz? Aztat gondolod, hogy valami kibaszott pirla vagyok? Valami süket filio di puttana? Valami bohócnak képz?'sz? Azé' vagyok tán itten, hogy szórakoztassalak?}
{341}{}{Ó, nem. Elnézést, csak kiváncsi voltam. Hadd kérdezzek valami mást!}
{342}{}{Aha, így igaz szarfej. És semmi nem fog jobban mulattatni, mint a haláltusád.}
{343}{}{Rendben, ha ennyit?l megsért?dtél, akkor lelépek.}
{360}{}{Menedék, he? Talán Mama tuggya valamit, mer' én nem. De én ismerem Vic gyereket, Metzgerné' van az a porca pistola.}
{361}{}{Vic? Nem ? az ott veled? Marharépa... a Mamát viszont ismerem.}
{362}{}{Ki az a Metzger?}
{363}{}{Ki az a Mama?}
{364}{}{Köszi. Kérdeznék még.}
{365}{}{Kösz, csak ennyit akartam tudni. Viszlát!}
{380}{}{Mama kosztoldát üzemeltet városnak keleti részin. Temet? mögött. Szép hely az ottan, van neki jó pasta. Mama mia!}
{381}{}{Kösz. Mi van azzal a Metzger gyerekkel, akinél Vic van?}
{382}{}{Köszi. Kérdeznék még.}
{383}{}{Kösz, csak ennyit akartam tudni. Viszlát!}
{400}{}{Ez igaz. Metzger, az a stronzo, halott. De nem tudni, mi történje Vic-kel.}
{401}{}{Az a Metzger, az egy igazi rompiballe. ? Rabszolga-Céh vezére, keleti részen, északra Mama vendégl?jét?'. Akárhogyis, nála van Vic, tudom.}
{402}{}{Kösz, mit tudsz a Mamáról?}
{403}{}{Köszi. Kérdeznék még.}
{404}{}{Kösz, csak ennyit akartam tudni. Viszlát!}
