# Dialog Editor last position: 133
{100}{}{Rejtek egyik lakosát látod.}
{101}{}{Fred.}
{102}{}{Õ Fred. Nagyon szép ruhát hord.}
{150}{}{Nagyon gondolkodik valamin.}
{151}{}{Nagyon boldognak látszik az új öltözékében.}
{200}{}{Egyszer még sokra viszem.}
{201}{}{Hagyj békén! Nem érek rá.}
{202}{}{Mesteri terv az...}
{203}{}{Egyszer a végére járok...}
{204}{}{Miért mindig én veszítek?}
{205}{}{Biztos, hogy megpiszkálták az asztalokat...}
{206}{}{...egyszer majd lesz egy saját házam.}
{207}{}{Szép ruhákat fogok venni...}
{220}{}{Hé, ember! Késõre jár, hagyjál békén!}
{221}{}{Nem, nem vágyom társaságra.}
{222}{}{Tudod, mennyi az idõ?}
{223}{}{Nincs semmim.}
{224}{}{Reggel zavarj! Fáradt vagyok.}
{225}{}{Kotródj!}
{226}{}{Nincs itthon senki.}
{227}{}{Nem akarok beszélgetni. Aludni készülök.}
{228}{}{Kisanyám, késõ van! Hagyj békén!}

{240}{}{Nincs több pénzem! Hagyj békén!}
{241}{}{Nincs itt semmilyen munka. Mit fogok csinálni?}
{242}{}{Csak azt ne mondd, hogy tartozom még valakinek! Ahh!}
{243}{}{Soha nem fog sikerülni.}
{244}{}{Mocskosul le vagyok égve...}
{245}{}{Haver, kéne egy kis pénz.}
{246}{}{Soha nem fogok új ruhákat venni.}
{247}{}{Ki kell találni egy újabb tervet...}
{260}{}{Kösz, hogy támogatsz.}
{261}{}{Igazi életmentõ vagy.}
{262}{}{Nemsokára meglesz a pénzed.}
{263}{}{Bármikor megnyerhetem a fõnyereményt.}
{264}{}{Ha nyerek, elõször neked szólok.}
{275}{}{Mûködik a tervem...}
{276}{}{Kösz a kölcsönt. Jó kezekben van a pénzed.}
{277}{}{Az asztalok meg vannak buherálva, de ne aggódj!}
{278}{}{Neked köszönhetõen egyszer még nagyot nyerek.}
{279}{}{Bármikor nyerhetek! Érzem.}
{280}{}{Ki foglak fizetni, esküszöm.}
{281}{}{Bármikor megnyerhetem a fõnyereményt. Kiszagoltam.}
{295}{}{Ismerlek én téged? Mit akarsz?}
{296}{}{Miért piszkálsz állandóan? Nem is ismerlek. Zargass valaki mást!}
{297}{}{Azért jöttem, hogy beszedjem a pénzt, amivel tartozol valakinek.}
{298}{}{Áh, hagyjuk...}
{299}{}{Uk!}
{300}{}{Viszlát!}
{310}{}{Hát itt vagy? Mindenütt kerestelek! Nézd meg ezt a ruhát!}
{311}{}{Még egyszer köszönöm.}
{312}{}{Jól nézel ki.}
{313}{}{Úgy nézel ki, mint egy rakás szar.}
{314}{}{Yuk!}
{315}{}{Ug.}
{320}{}{Köszönöm. Nagyon köszönöm! Hála neked, négy ugyanilyenem van.}
{321}{}{Szóval nyertél?}
{322}{}{Naszóval... hol a pénzem?}
{330}{}{Nem tetszik a ruhám? Igazad lehet. Én sem vagyok oda érte. Kéne egy-két új... hisz megengedhetem magamnak.}
{331}{}{Szóval nyertél?}
{332}{}{Hol a pénzem?}
{333}{}{Hmmm.}
{340}{}{Épp rá akartam térni! Nem fürödhetek a dicsõségben? Ezért nagyon keményen megdolgoztam ám!}
{341}{}{Tudom, elnézést.}
{342}{}{Cseszd meg! Hol a pénz, amivel támogattalak?}
{343}{}{Egy szart! Hol a pénzem?}
{350}{}{Jó! Itt van. [Fred átnyújt 500 dollárt] Egy kis extra, amiért bíztál bennem. Késõbb találkozunk. Kösz még egyszer.}
{351}{}{Kösz!}
{352}{}{Jól van, jól...}
{360}{}{Kösz, hogy biztál bennem. Sokat jelentett, hogy egy teljesen idegen megbízott bennem. Hadd adjam ezt oda!}
{361}{}{Oké!}
{362}{}{Nem szükséges ez...}
{363}{}{Öh.}
{370}{}{Sokkal tartozom neked. Bíztál bennem, amikor elfordult tõlem a szerencse. A hálám jeléül van valamim a számodra.}
{371}{}{Oké.}
{372}{}{Nem kellene.}
{373}{}{Öh.}
{380}{}{Itt van. [Fred átad neked 1000 dollárt.] Remélem, ez segít. Gondolom, van mire költened.}
{381}{}{Bocs, de nem fogadhatom el.}
{382}{}{Kösz.}
{383}{}{Nem igazán, de elteszem.}
{384}{}{Nyam.}
{390}{}{Itt van. [Fred átad neked 2000 dollárt, 5 fúziós cellát, 5 energia cellát és egy plazma gránátot.] Remélem, ez segít valamicskét.}
{391}{}{Elnézést, de nem fogadhatom el.}
{392}{}{Nagyon köszönöm.}
{393}{}{Nem igazán, de azért elteszem.}
{394}{}{Nyami.}
{400}{}{Mi? Rendben, ha nagyon akarod. Köszönöm szépen. Vigyázz magadra!}
{401}{}{Viszlát!}
{410}{}{Mi? Valami furcsa drogot szedsz? Nem úgy nézel ki, mint egy Jet-függõ. Takarodj innen, te rusnyaság!}
{411}{}{Takarodj!}
{412}{}{Úg.}
{420}{}{Mirõl beszélsz? Senkinek semmivel nem tartozom. Kirõl beszélsz tulajdonképpen?}
{421}{}{Aha, múltkor is ezt mondtad. Nem tudom, mirõl beszélsz. Ki ez a képzeletbeli személy már megint?}
{422}{}{Becky azt mondta, hogy 500 dollárral lógsz neki.}
{423}{}{Becky küldött...}
{424}{}{Rebecca mondta, hogy kölcsönadott neked 200 dollárt.}
{430}{}{Ó igen. Rebecca adott nekem 200-at... Várj! Talán... ömm...}
{431}{}{Azt mondta, törjem el a nyakad, ha nem fizetsz.}
{432}{}{Add elõ!}
{440}{}{Életemben nem láttam annyi pénzt...}
{441}{}{Hmm.}
{442}{}{Ó.}
{450}{}{Csakugyan? Erre aztán várhatsz! Becky a légynek sem ártana. Mellesleg elég csinos.}
#Ravasz egy idioma - that'll be a day> that will never happen, not on your life  (bass)
{451}{}{Hát ebben tévedsz, seggfej!}
{452}{}{Talán valaki más volt.}
{460}{}{A fene ott egye meg! Nem tagadom... viszont teljesen le vagyok égve. Nem tudok annyi pénzt adni! Ennem is kell ám!}
{461}{}{Sajnálom!}
{462}{}{Pech.}
{470}{}{Basszus! 100 dollár sok nekem. Ki tudsz segíteni a felével? Igérem, visszafizetem!}
{471}{}{Sajnálom, de nem.}
{472}{}{Gyerünk! Add ide a teljes összeget!}
{473}{}{Rendben.}
{480}{}{Francba! Tönkreteszel. Rendben, itt van. Most már teljesen le vagyok égve.}
{481}{}{Oké. Megtámogatlak.}
{482}{}{Kösz. Legközelebb jobban bánj a pénzeddel!}
{483}{}{Kösz, hogy üzleteltünk...}
{490}{}{Mondtam már, hogy nem tudom! Ha megteszem, éhezni fogok. Ugyan már, nem tudnál kisegíteni?}
{491}{}{Rendben. Állom a felét!}
{492}{}{Sajnos nem. Nekem sincs pénzem.}
{493}{}{Visszajövök késõbb...}
{500}{}{Mi? Tényleg? Szuper! Köszönöm, barátom! Itt van 100 dollár! Megszerzem a másik 100-at, amilyen gyorsan csak lehet.}
{501}{}{Mi? Tényleg? Szuper! Köszönöm, hölgyem! Itt van 100 dollár! Megszerzem a másik 100-at, amilyen gyorsan csak lehet.}
{502}{}{Semmi probléma.}
{503}{}{Ajánlom, hogy visszaadd a pénzem...}
{510}{}{Nem kell aggódnod! Visszaadom. Szavamat adtam, és ez alkalommal nem fogok róla megfeledkezni.}
{511}{}{Oké.}
{520}{}{Tudod mit? Az a százas nagyon le fogja lassítani a dolgokat. Nem gondolod, hogy egy kicsit visszakérhetnék belõle?}
{521}{}{Mennyit?}
{522}{}{Semmi esetre sem.}
{530}{}{Várj! Tudom már. Adok neked száz dollárt, te pedig kisegítesz a maradék százzal, amivel Becky-nek tartozom. Hamarosan visszafizetem neked.}
{531}{}{Oké, rendben.}
{532}{}{Nincs alku.}
{540}{}{Csak 50 dollárt! Ez a tökéletes terv része.}
{541}{}{Rendben.}
{542}{}{De így csak 50 dollár marad nálam, hogy kifizessem a 200 dolláros tartozásodat.}
{543}{}{Nem.}
{550}{}{Mii-öö... Francba! Ezt nem fogod megbánni! Abban jó vagyok.}
{551}{}{Semmi probléma.}
{560}{}{Látom, hogy a matematikai képességeid... ugyan már, kérlek! Ez neked nem túl sok, de számomra igen.}
{561}{}{Oké.}
{562}{}{Nem.}
{570}{}{Persze, hogy Õ volt. Mindenki tudja, hogy utálja azt a nevet. Nem vágsz át!}
{571}{}{Semmivel nem tartozom neki.}
{572}{}{Azt mondta, feledékeny vagy.}
{573}{}{Nézd, erre nincs idõm. Fizess, basszus!}
{574}{}{Rebecca állítása szerint már jó ideje adta kölcsön.}
{580}{}{Én nem! Én... várj csak... Egyszer mégis. Nem fizettem volna vissza? Úgy tudtam, visszaadtam...}
{581}{}{Nem, nem adtad. Ezért küldött.}
{582}{}{Csak fizess ki és már itt sem vagyok.}
{590}{}{Nem emlékszem... de Becky biztosan kisegített engem és barátaimat a múltban.}
{591}{}{Add elõ a 200 dollárt!}
{592}{}{Add csak ide a pénzt gyorsan!...}
{600}{}{Hagyjál békén!}
{601}{}{Bizonyára...}
{602}{}{Oké.}
{610}{}{Öö. Üdv!.. Gondolom a pénzt akarod. Nem tudnál kisegíteni a felével?}
{611}{}{Sajnálom, de nem.}
{612}{}{Ha kölcsönadott neked 200 dollárt, akkor szépen vissza is fizeted neki!}
{613}{}{Oké, rendben.}
