# Dialog Editor last position: 57
{100}{}{Egy gengszter.}
{150}{}{Lara bandájához tartozik.}
{151}{}{Úgy tûnik, Lara bandájához tartozik.}
{200}{}{Bölcs fickó vagy mondhatom...}
{201}{}{Megkapod a magadét!}
{202}{}{Eljött a fizetség ideje!}
{203}{}{Gyere csak ide!}
{204}{}{Még nem végeztem veled.}
{205}{}{Mocsadék!}

{225}{}{Kíváncsi vagyok, Metzger halála után mire számíthatunk...}
{226}{}{Szóval Metzgernek végre annyi?}
{227}{}{A te mûved volt?}
{228}{}{Rejtek már sosem lesz a régi.}
{240}{}{El sem hiszem, végre legyõztük õket.}
{241}{}{Metzgernek most már tisztelnie kell minket.}
{242}{}{Megmutattuk nekik!}
{243}{}{Megismerték a mi igazságunkat.}
{244}{}{Nélküled nem tudtuk volna véghez vinni.}
{245}{}{Kösz a segítséget!}
{246}{}{Megcsináltuk!}
{247}{}{Bennünket akarsz csesztetni?}
{248}{}{Jobb lesz, ha kétszer is meggondolod, mit csinálsz...}
{249}{}{Lara az egyetlen indok, hogy miért nem akasztunk fel.}
{250}{}{Mit akartál elérni?}

{251}{}{Gyáva féreg!}
{252}{}{Undorodom tõled!}
{253}{}{Takarodj!}
{254}{}{Tûnés!}

{255}{}{Készen állunk, csak add meg a jelet!}
{256}{}{Ideje már, hogy szétrúgjuk a seggüket.}
{257}{}{Utálom a várakozást.}
{258}{}{Menjünk már!}
{259}{}{Kész vagy már?}
{260}{}{Szólj Larának, ha készen állsz!}

{270}{}{Csatlakozni akarsz?}
{271}{}{Biztos Larához jöttél.}
{272}{}{Mi a pálya?}
{273}{}{Larával beszélj, ha akarsz valamit!}
{274}{}{Szia...}
{275}{}{Larához jöttél?}
{300}{}{Helló!}
{301}{}{Mizújs?}
{302}{}{Remélem, jól mennek a dolgok.}
{303}{}{Szóval tudsz nekünk segíteni?}
{304}{}{Örülök, hogy látlak.}
{305}{}{Hamarosan megmutatjuk Tylernek...}
{306}{}{Vannak új fejlemények?}
{310}{}{Kösz a segítséget. Sajnálom, ami Larával történt.}
{311}{}{Végre elkaptuk õket!}
{312}{}{Nélküled nem sikerült volna.}
{313}{}{Lara legalább harc közben halt meg.}
{314}{}{Nem hiszem el, hogy Lara is otthagyta a fogát...}
{315}{}{Megmutattuk Metzgernek, hogy ki a jobb.}
{316}{}{Metzgernek jobb velünk.}
{350}{}{Te akartad!}
{351}{}{Most mind kinyiffan!}
{352}{}{Ideje szétrúgni néhány lepcses picsát!}
