{100}{}{Egy kedves, id?s asszony.}
{150}{}{? a "Mama", aki éppen szorgosan f?z, mos, takarít.}
{151}{}{Egy rubensi idomokkal megáldott korosodó asszonyt látsz, némi Da Vinchi-s mosollyal az arcán.}
{200}{}{Szervusz, én vagyok a Mama! Korábban még nem láttalak errefelé, kedveském.}
{201}{}{Szia, aranyoskám! Mit tehet érted a Mama?}
{202}{}{Én }
{203}{}{Hmmm. R-rendben? Nyuszi-puszi, Mama!}
{220}{}{Már félig kiettél engem a házamból és az otthonomból! Miért nem keresel valami más helyet, ahol egész nap lebzselhetsz? Ma már amúgy is eleget ettél!}
{221}{}{Well }
{222}{}{ you sure do look as though you're a mite confused. I hate to see a critter suffer. Want something to eat?}
{223}{}{Én tele. Mama f?zni jól! Viszlát, Mama!}
{224}{}{Én fizet?}
{225}{}{Én megy! Viszlát, Mama!}
{240}{}{Nos, oké. Mid van? (Mama az erszényedért nyúl)}
{241}{}{Mama? (odanyújtod az erszényed)}
{242}{}{Nem! Én megy! Viszlát, Mama!}
{250}{}{Igazán sajnálom. Csak patkány-pitém, patkány-pogácsám és némi spagettim van.}
{251}{}{Akkor mi legyen a következ? fogás?}
{252}{}{Öhm, kérhetnék valamit, amiben nincs olyan sok patkány?}
{253}{}{Akkor kérek egy olyan patkány-pogácsát.}
{254}{}{Kérnék egy kis patkány-pitét.}
{270}{}{Ebben az esetben a spagettit tudom ajánlani. Nem sok patkány van benne... legfeljebb a szósz... de tényleg csak annyi.}
{271}{}{Rendicsek. Ha lehetne, akkor a spagettit választanám, patkány-szósszal.}
{280}{}{Rögvest hozok neked repetát. Ez összesen 10 dollár lesz.}
{281}{}{Most éppen nincs ennyi pénzem. Helyette hadd kérdezzek valamit!}
{282}{}{10 dolcsi egy patkányért? Maga bizonyára meg?rült! A falu környékén sokkal többet kérhetünk az ízesebb darabokért! Persze, hogy jöhet!}
{283}{}{Rendben, megegyeztünk! Itt a pénz...}
{284}{}{Meggondoltam magam. Hadd kérdezzek inkább valamit!}
{285}{}{Még majd visszanézek kés?bb. Viszlát!}
{300}{}{Látom, nagyon éhes vagy. Szeretem látni, ha valaki ennyire jóíz?en eszik. Elégedett vagy?}
{301}{}{Ez nem lehet kérdés, Mama! Jöhet a repeta!}
{302}{}{Persze, hogyne! Hadd kérdezzek valamit!}
{303}{}{Most elég ennyi. Viszlát, Mama!}
{320}{}{Kellene nekem valaki, aki ételt visz Smittynek. A fickó a szeméttelepen dolgozik, innen nyugatra. Megtennéd nekem? Ha megcsinálod, kapsz t?lem egy kis ingyen ételt.}
{321}{}{Rendben, nem bánom.}
{322}{}{Hadd gondolkodjak egy kicsit! Közben kérdeznék még valami mást is.}
{323}{}{Öühm, izé... bocsi, Mama. Nem lehet. Viszlát!}
{340}{}{Szerencséd van! Tudunk szolgálni egy kis radskorpió-rántottával.}
{341}{}{Van dinsztelt-párolt disznó-patkányunk.}
{342}{}{Vajban sült radskorpió-farok.}
{343}{}{Most mindössze csak káposztalevesem van.}
{344}{}{Frissen sült brahmin-bélszín.}
{345}{}{T?zforró gekkópite, egyenesen a süt?b?l.}
{346}{}{Farhát.}
{347}{}{T?zdelt vadkány.}
{348}{}{Lebeg?b?l készített frikasszé.}
{349}{}{Filé mignon.}
{350}{}{Sz?zérmék gekkó módra.}
{351}{}{Mantisz marsala.}
{352}{}{Vakondpatkány manicotti.}
{353}{}{Sült brahmin.}
{354}{}{Pirított radskorpió.}
{355}{}{Szójafasírt!}
{356}{}{Ehem, nem vagyok benne biztos... de eléggé csirkeíze van.}
{357}{}{Kentaúr-kockák, a specialitásom.}
{358}{}{Meglepetés!}
{359}{}{Szójafasírt!}
{360}{}{Igazán?}
{375}{}{Tessék. Éhesnek látszol. (A Mama feléd nyújt egy óriási tányért, amin valami nagyon finom illatú étel g?zölög.)}
{376}{}{Kösz-I, Mam-I!}
{385}{}{Egyél! Tudtam, hogy ízleni fog.}
{386}{}{Hmm, nyam-nyam. Viszlát, Mama!}
{395}{}{Nagyon szépen köszönöm! Persze én is el tudnám vinni... csak akkor ki marad itt, hogy vigyázzon a helyre, amíg oda vagyok? Itt van Smitty ebédje. Ha én nem vinnék neki, biztos vagyok benne, hogy enni is elfelejtene.}
{396}{}{Elviszem neki, egyenesen a kezébe...}
{405}{}{Annyira csalódtam benned! Szegény Smittynek magának kellett eljönni az ebédjéért. Most meg mit akarsz?}
{406}{}{Üdvözöllek, a nevem Mama és enyém ez a hely. S?t, New Reno északi részén mindenki csak az ujját nyalja nálam.}
{407}{}{Mit akarsz, mir?l meséljen neked a Mama?}
{408}{}{Maga nem az anyám!}
{409}{}{Hallott valamelyik Menedékr?l vagy egy Vic nev? fickóról?}
{410}{}{Mi tennivaló van ebben a városban?}
{411}{}{Milyen ehet? dolgok vannak errefelé?}
{425}{}{Tudom. De mindenki így nevez engem. Heh, én úgy tekintek itt az emberekre, mint a saját kölykeimre. Amíg betartod a szabályokat, rád is.}
{426}{}{Miféle szabályokat?}
{435}{}{Elmondom: nem lopunk, nem káromkodunk, és nem verekszünk! Az én üzletemben semmiképp. Ha megszeged a szabályokat, egy-kett?re kipenderítünk. Szeretem, ha békesség van itt.}
{436}{}{Értem. Talán akkor kérdez?sködnék más fel?l is.}
{437}{}{Teljesen logikus. Majd kés?bb még beszélünk, Mama!}
{445}{}{Ott van Menedékváros innent?l egy kicsit keletre és egy cseppet északra. És ez a Vic... hmm, várjunk csak...}
{446}{}{Biztos vagyok benne, hogy tudja, hol találom Vicet. ? egy keresked?.}
{447}{}{Kösz, ez minden, amit tudnom kell. Viszlát, Mama!}
{455}{}{Vic, a keresked?? Á, így már beugrott. Igen, ha jól tudom, Metzger tartja fogva valami oknál fogva.}
{456}{}{Ki az a Metzger és hol lehet vele összefutni?}
{457}{}{Ez nagyszer?, Mama! Köszönöm!}
{465}{}{Metzger a Rabszolga-Céh itteni vezet?je. Nála aztán a legkülönfélébb emberek raboskodnak. Északra innen, egy utcával arrébb lakik.}
{466}{}{Metzger régen a Rabszolga-Céh itteni vezet?je volt. Rengeteg féle-fajta embert tartott fogva a táborában, de most nem tudom, mi van vele. Azt hallottam, hogy megölték.}
{467}{}{Köszönöm az információt! Hadd érdekl?djek valami másról is, Mama.}
{468}{}{El kell intéznem még pár fontos dolgot. Kösz, Mama!}
{475}{}{Eredj és vidd most már el azt az ebédet Smittynek!}
{476}{}{Addig nem fogok segíteni, amíg be nem tartod a szavad.}
{477}{}{Pattanj hát!}
{478}{}{Menj, vidd el Smittynek az ételt. Mozgás!}
{479}{}{Stop your lollygagging and get that meal to Smitty.}
{485}{}{Ügyes voltál! Bizonyára alaposan megéheztél. Jutalomból mindent megkapsz t?lem, mi szem-szájnak ingere. Nézd csak, mid van nekem a számodra. Egy tál a legremekebb ételekb?l.}
{486}{}{Ez jól hangzik! Nézzük csak!}
{487}{}{Izé, Mama... Nem hiszem, hogy most annyira éhes lennék, de azért mindesetre kösz! Viszlát!}
{500}{}{Hmm, nem tudok túl sokat róla. Valószín?leg csak valaki hülyéskedik, semmi több.}
{501}{}{Mindig is kísértetjárta volt?}
{502}{}{Lakik valaki abban a házban?}
{503}{}{Egyetértek. Viszlát!}
{520}{}{Úgy körülbelül két évvel ezel?tt kezd?dött. Hallottam pár dolgot a sírásról meg a szellemekr?l. Jómagam nem hiszek benne.}
{521}{}{Az igen! Két évvel ezel?tt? Lakott azóta valaki ott?}
{522}{}{Én sem. Kösz!}
{540}{}{Az egyik fiam néhány éve ott aludt. Lehet, hogy ? tud róla valamit.}
{541}{}{Ki?}
{542}{}{Valószín?leg nem. Viszlát!}
{560}{}{Egyszer járt nálam, és el akarta zálogosítani a cuccait. Többségében ékszereket. Emlékszem, volt nála egy apró arany medál, amit megtartott magának.}
{561}{}{Emlékszik a nevére?}
{562}{}{Egy medál? Különös. Ki volt az?}
{563}{}{Feltennék még kérdéseket.}
{564}{}{Kösz, viszlát!}
{580}{}{Nem biztos. Talán Joseph volt... vagy Joel, vagy valami ilyesmi. Nemsokára 19 éves lesz... A család fekete báránya. Ha jól tudom, hozzácsapódott néhány helyi nehézfiúhoz.}
{581}{}{Kösz! Van egy másik kérdésem is a számára.}
{582}{}{Kösz, viszlát!}
{600}{}{Mit tud a kísértetházról?}
