{100}{}{Egy drogos.}
{101}{}{Petey.}
{150}{}{Ez bizony egy szerencsétlen drogfüggõ.}
{151}{}{Peteyre aztán ráférne egy kis segítség.}
{152}{}{[beszéd]}
{155}{}{[köhécsel] Nincs egy kis apród?}
{156}{}{De van, tessék.}
{157}{}{Ne lejmolj, hagyj békén!}
{158}{}{Piti?}
{159}{}{Rosszabb vagy, mint én. [köhög] Azért kösz.}
{160}{}{Sajnálom, viszlát!}
{161}{}{Szívesen, aha, persze.}
{162}{}{Talán majd legközelebb... Kösz. [köhög]}
{163}{}{[kész]}
{164}{}{Köszönöm szépen. [köhög] Annyira, de annyira köszönöm!}
{165}{}{Szóra sem érdemes.}
{166}{}{Persze, persze.}
{167}{}{Uram, [köhög] segítene egy szegény, nyomorult emberen?}
{168}{}{Here's $5.}
{169}{}{Ma nem.}
{170}{}{Szerezz munkát magadnak!}
{171}{}{Hölgyem, kérem segítsen [köhög] egy szegény, éhezõ emberen, [köhög] aki túl beteg a munkavégzéshez.}
{172}{}{Te szegény lélek, itt van 5 dollár.}
{173}{}{Nem adok pénzt kunyerálóknak.}
{174}{}{Nem.}
{200}{}{Hé, ember, adnál egy kis pénzt?}
{201}{}{Némi aprót, uram?}
{202}{}{Hé, ki tudnál segíteni néhány dolcsival?}
{203}{}{Ki tudnál segíteni néhány dollárral?}
{204}{}{Kölcsön tudnál adni némi pénzt?}
{205}{}{Némi aprót, hölgyem?}
{206}{}{Hölgyem, kisegítene egy kis pénzzel?}
{220}{}{Kérem segítsen, uram!}
{221}{}{Áá, ez fáj!}
{222}{}{Segítség kell. Nagyon fáj!}
{223}{}{Hölgyem, hívna segítséget?}
{225}{}{Nagyon hálás vagyok.}
{226}{}{Hé, mégis mit csinálsz?!}
{230}{}{Olyan jól esik.}
{231}{}{Uhhh...}
{232}{}{[kacarászik]}
{233}{}{Hé...}
{300}{}{Nahát, valami nyamvadt kinyírta Tubbyt?}
{301}{}{Mi a fasz történt Tubbyval?}
{302}{}{A francba, Tubby...}
{303}{}{Áhhh...}
{304}{}{Nem is kedveltem azt a seggfejet.}
{305}{}{Flick meghalt? Fenébe!}
{306}{}{Mi történt Flick-kel?}
{307}{}{Flick...}
{310}{}{Hé, Tubby, én, ööö, segítségre szorulok.}
{311}{}{HÉ, TUBBY!}
{312}{}{Helló!}
{313}{}{HÉ!}
{314}{}{Hé, Flick, én, öö, segítségre szorulok.}
{315}{}{HÉ, FLICK!}
{320}{}{Hé, Tubby, meg tudsz dobni egy kis cuccossal? Van pénzem.}
{321}{}{Ööö, Tubby, van pénzem...}
{322}{}{Uhhh...}
{323}{}{Ember, kéne egy kis anyag...}
{324}{}{Hé, Flick, tudsz adni nekem is? Van pénzem.}
{325}{}{Ömm, Flick... Van némi pénz nálam.}
{330}{}{Öhhh... Még egyszer kösz, Tubby.}
{331}{}{Haver vagy, Tubby.}
{332}{}{Ígérem, hogy holnap véget vetek ennek.}
{333}{}{Haver vagy.}
{334}{}{Uhhh... Még egyszer kösz, Flick.}
{335}{}{Haver vagy, Flick.}
