# Dialog Editor last position: 44
{100}{}{Egy nagy darab, primitív ember.}
{101}{}{Egy karcsú, de primitív nõt látsz.}
{200}{}{Egy fura külsejû embert látsz.}
{201}{}{Egy toprongyos ember.}
{202}{}{Egy szakadt rongyokba öltözött embert látsz.}
{210}{}{Ez a nõ igencsak piszkos.}
{211}{}{Egy eléggé koszos nõt látsz.}
{212}{}{Ez a nõ nagyon sovány.}

{270}{}{Õk nem találják engemet.}
{271}{}{Elbújni kell. Elbújni.}
{272}{}{Mér akar õk bántani minket?}
{273}{}{Én fél.}
{274}{}{Én nem harcol.}
{275}{}{Én akarja élni.}
{276}{}{Nem bántani család.}


{280}{}{Ó, a francba!}
{281}{}{Miért csinálják ezt?}
{282}{}{Mi lesz a családommal?}
{283}{}{Nem akarok meghalni.}
{284}{}{Nem akarok rabszolga lenni.}
{285}{}{Ennél jobbat érdemlek.}


{300}{}{Ahhh!}
{301}{}{Ne ölj! Ne ölj!}
{302}{}{Állj!}
{303}{}{Segítsééég!}
{304}{}{Fussunk!}
{305}{}{Hagyjatok békén!}
{306}{}{Ne bánts!}
{307}{}{Nem bántlak!}
{308}{}{Nem harcolok!}

{350}{}{Fussatok, ha kedves az életetek!}
{351}{}{Ne hagyd, hogy elkapjanak!}
{352}{}{Rabszolga-hajcsárok! Futás!}
{353}{}{Valaki segítsen! Kérem!}
{354}{}{Menekülés!}
{355}{}{Ahhh!}
{356}{}{Elég ebbõl az õrületbõl!}
{357}{}{Mi nem csináltunk semmit! Hagyjatok békén!}
{358}{}{Felismerem azt a tetoválást!}
{359}{}{Ne, kérem!}
{360}{}{Kérem ne öljön meg!}
{361}{}{Nem állok ellen, csak ne öljön meg!}
{362}{}{Kérem, én nem akarok meghalni!}
{363}{}{Ugye maguk rabszolga-hajcsárok? Jaj nekem!}
