# 0. Look
{100}{}{Rabszolga-hajcsár.}
{000}{}{Ezt a rabszolga-hajcsárt Aidan-nek hívják.}

{150}{}{Pont olyannak néz ki, aki meg tudná védeni magát egy bunyóban.}

# 1. First Time - Self Initiated (From Where to go)
{200}{}{Nocsak, friss hús... Üdvözöllek a rabszolga-céhben. A nevem Aidan. Üzletõni jötté? Jobban teszed, ha igen.}
{201}{}{Mit is csinál pontosan ez a céh?}
{202}{}{Rabszolga-Céh?}
{203}{}{Szóga cé}
{204}{}{Aruk kun sung?}

# 2. Yes, join (From 4)
{215}{}{[Aidan végigmustrál] Illenél közénk, de Metzgerrel kell beszélned errõl. Menj egyenesen be azon az ajtón!}
{216}{}{[Aidan végigmustrál] Nem bírnád ezt a melót, de ki vagyok én, hogy döntsek? Metzgerrel kõ beszélned. Menj be egyenesen azon az ajtón!}
{217}{}{Aszontam beszélj Metzgerrel. Megsüketültél, vagy egyszerûen hülye vagy?}
{218}{}{Ki az a Metzger?}
{219}{}{Feltennék még egy kérdést.}
{220}{}{Kösz, úgy lesz.}
{221}{}{Medger}
{222}{}{O... ké.}

# 3. Hostile, Start Combat. (From Where to go)
{230}{}{Most kinyiffansz!}

# 4. (From Where to go, 1-2, 6, 10-11, 16-18)
{240}{}{Hülyéskedsz velem?! Rabszolgákat ejtünk foglyul és adunk el. Te is ezért vagy itt, nem? Akciót akarsz már, nemde?}
{241}{}{Hülyéskedsz velem?! Rabszolgákat ejtünk foglyul és adunk el. Ha nem ezért jöttél, akkó minek?}
{242}{}{Szóval te is beléptél... Ez érdekes lesz. Ha szereted az izgalmakat, jó munkát választottál. Ha nem, akkor nem fogsz sokáig élni.}
{243}{}{Nem gondoltam volna, hogy ezt a tetkót nõn is látni fogom valaha. Egyébként jól néz ki. Csodálkozom, hogy Metzger... na, mindegy, faszt se érdekel. Szóval mi kõne?}
{244}{}{Mi kell?? Eltévedtél vagy mi?}
{245}{}{Helló, kishölgy. Mi kéne, ha volna?}
{246}{}{Mit akarsz?}
{247}{}{Be akarok lépni.}
{248}{}{Honnan szerzitek a rabszolgákat?}
{249}{}{Vennék pár rabszolgát.}
{250}{}{Ismersz egy Vic nevû pasast?}
{251}{}{Egy kereskedõt keresek.}
{252}{}{Hallottál már a 13-as Menedékrõl?}
{253}{}{Viszlát!}
{254}{}{Munka.}
{255}{}{Kaja.}
{256}{}{Gyilok!}
{257}{}{Ug.}

# 5. Dumb Kill (From 4)
{270}{}{Áh, egy vérszomjas fajta. Hát... Beszélj a fõnökkel! Talán van egy helyünk a számodra. Menj be azon az ajtón!}
{271}{}{Metzgernek még sosem volt ribi rabszolga-hajcsárja, de ha tényleg ilyen vérszomjas vagy, akkor beszélj vele! Ott van a hátsó szobában.}
{272}{}{Okké.}
{273}{}{Uh.}
{274}{}{Krook}

# 6. Buy slaves (From 4)
{280}{}{Errõl Metzgerrel kell beszélned! Általában nem ad el a magánembereknek. Már tele van... nagyobb vevõkkel.}
{281}{}{Ki az a Metzger?}
{282}{}{Akkor kérdeznék valami mást.}
{283}{}{Oké, viszlát!}
{284}{}{És mi van Vic-kel?}

# 7. Dumb Exit (From 1, 4)
{290}{}{Nem mondod... Na, tûnés innen!}
{291}{}{Hülye gyökér!}
{292}{}{Oook?}
{293}{}{Hmph.}

# 8. What about buying Vic (From 6, 19)
{300}{}{Nem valószínû. Az a hülye Vic átverte Metzgert valami rádióval. Kétlem, hogy eladná. Errõl vele személyesen kén' beszé'ned.}
{301}{}{Hallom, megjavította a rádiót. Kérdezd meg Metzgert. Most már nem sok haszna van, nem valami jó áru.}
{302}{}{Metzger? Az meg ki?}
{303}{}{Hol van Metzger?}
{304}{}{Oké, kösz. Viszlát!}

# 9. Where's Metzger (From 8)
{310}{}{Ott van a hátsó szobában.}
{311}{}{Hülyéskedsz? Ott van hátul. Csak menj át azon az ajtón!}
{312}{}{Oké.}
{313}{}{Kösz.}

# 10. Who's Metzger? (From 2, 8, 16)
{320}{}{Picsába, nem ismered Metzgert? Micsinálsz ebben a városban, ha nem õt keresed? Õ a Rabszolga-Céh feje.}
{321}{}{Hányszor kell még elmondanom? Õ vezeti a Rabszolga-Céhet. Õ irányít bizonyos dolgokat a városban.}
{322}{}{Kérdeznék valamit}
{323}{}{Oké, kösz.}

# 11. Where do you get slaves from? (From 4)
{330}{}{Nem mondom meg... Metzger megnyúzna. Ráadásul, nem szeretnénk semmiféle vetélytársat.}
{331}{}{Már mondtam, hogy nem beszélek errõl.}
{332}{}{Mondd el, mielõtt lyukat csinálok a fejedbe!}
{333}{}{Megértem. Kérdeznék még valamit.}
{334}{}{Oké, viszlát!}

# 12. Threatened life (From 11)
{340}{}{Ide figyelj, te kis szarkupac, ne merj megfenyegetni se engem, se mást a céhbõl, különben halott ember vagy! Fogtad? Halott!}
{341}{}{Ide figylej, te kis picsa, ne merj megfenyegetni se engem, se mást a céhbõl, különben halott ember vagy! Fogtad? Halott!}
{342}{}{Na, te kis Jetes, most meghalsz!}
{343}{}{Baszd meg!}
{344}{}{Bocsánat, kérlek, ne bánts!}
{345}{}{Ja, persze. Most az egyszer életben hagylak.}

# 13. Threaten back (From 12)
{350}{}{Valóban? Valszeg itt helyben lyukat kéne durrantanom a fejedbe. Mit szólsz az ötlethez, nagyfiú?}
{351}{}{Hozz ki magadból mindent!}
{352}{}{Ne nevettes!}
{353}{}{Csak vicceltem, ember.}
{354}{}{Elnézést. Én csak le akartalak nyûgözni.}

# 14. Run along (From 12, 13)
{360}{}{Futás, mielõtt meggondolom magam!}
{361}{}{Okés.}

# 15. Food? (From 4)
{370}{}{Mit? Ja, te biztos a Mama étkezdéjét keresed. Egy épülettel lejjebb megtalálod. L-e-j-j-e-b-b. Arra! [Aidan kimutat az ajtón.]}
{371}{}{Hö? Öö... óh.}

# 16. Yes, join - Female (From 4)
{380}{}{Szerintem csatlakozhatnál hozzánk, de Metzger még soha nem vett fel nõt. Nem tudom miért, de kétlem, hogy épp most változtatna a szokásán.}
{381}{}{Nem olyannak nézel ki, mint aki bírná ezt a melót. Metzger még soha nem alkalmazott nõt és kétlem, hogy most fog változtatni a szokásán.} # Error intentional, please do not remove.
{382}{}{Aszontam beszélj Metzgerrel!}
{383}{}{Ki az a Metzger?}
{384}{}{Kérdeznék még.}
{385}{}{Kösz, beszélek vele.}
{386}{}{Medger}
{387}{}{O... ké.}

# 17. Vault 13? (From 4)
{400}{}{Nem, de én megkérdezném helyedben a fõnököt. Õ már biztosan járt ott.}
{401}{}{Van még pár kérdésem.}
{402}{}{Oké, kösz. Viszlát!}

# 18. Vic/Merchant? (From 4)
{410}{}{Kereskedõ? Ó, biztos Vicet keresed, õ árul régi menedékekbõl való cuccokat. Rábaszott. Metzger nagyon mérges rá.}
{411}{}{Ja, Vic... az a kereskedõ fickó, ugye? Amelyik régi menedékekbõl való cuccokat árul. Rábaszott. Metzger nagyon dühös rá.}
{412}{}{Hányszor fogod még megkérdezni? Metzger elkapta.}
{413}{}{Ki az a Metzger?}
{414}{}{Feltennék még pár kérdést.}
{415}{}{Eladó?}
{416}{}{Oké, kösz.}

# 19. Float Greeting (From WTG)
{430}{}{Hé, fiúk, nézzétek már, ki jött vissza hozzánk!}
{431}{}{Fussatok, egy rabszolga-hajcsár! Áh, szétröhögöm magam!}
{432}{}{Visszajöttél akciózni?}
{433}{}{Tudod a járást...}
{434}{}{Menj csak be!}
{435}{}{Már vár rád.}
{436}{}{Most meg mit akarsz?}
{437}{}{Ismerem ezt a ronda pofát.}
{438}{}{Na, mi az ábra?}
{439}{}{Visszajöttél hát... Csatlakozol hozzánk?}
