# Dialog Editor last position: 84
{100}{}{Egy nagy darab, primitív embert látsz.}
{101}{}{Ez az ember meglehetõsen erõs és éber.}
{110}{}{Egy karcsú, de primitív nõt látsz.}
{111}{}{A mérete ellenére erõsnek tûnik.}
{120}{}{Egy furcsa embert látsz.}
{121}{}{Rettenetesen vékony.}
{130}{}{Egy rongyos ember.}
{131}{}{Ez az ember meglehetõsen erõsnek tûnik.}
{140}{}{Egy toprongyos embert látsz.}
{141}{}{A mozdulatain érzõdik a gyorsaság.}
{150}{}{Egy piszkos nõ.}
{151}{}{Úgy látszik, nem fürdött egész életében.}
{160}{}{Egy jól megtermett nõt látsz.}
{161}{}{Erõs harcosnak tûnik.}
{170}{}{Egy cingár nõ.}
{171}{}{Ez az illetõ nem sok galibát tudna okozni.}
{200}{}{Dögöjj meg!}
{201}{}{Hol vagyol?}
{202}{}{Mostan bántani foglak!}
{210}{}{Visszakapod te esztet!}
{211}{}{Mocskos rabszóga-vadászok!}
{212}{}{Ezér' még megfizetsz!}
{220}{}{Haggyá' békén!}
{221}{}{Ne báncsá'!}
{222}{}{Nem bántalak!}
{223}{}{Nem harcolok!}
{230}{}{Ismerem ezt a tetoválást!}
{231}{}{Kérlek, ne!}
{232}{}{Kérlek, ne ölj meg!}
{233}{}{Nem harcolok, ne ölj meg!}
{234}{}{Kérlek, nem akarok meghalni!}
{235}{}{Rabszolga-vadászok vagytok? Ó, istenem!}

#primitive
{245}{}{Csönd! Közelbe' vannak.}
{246}{}{Megöl rossz emberek.}
{247}{}{Ne vegyed te el család tõlem!}
{248}{}{Meg védem családot!}
{249}{}{Nem szabad megtalá'ni minket.}
{250}{}{Õk rossz emberek.}

{260}{}{Rabszolga-vadászok jönnek. Mindenki hallgasson!}
{261}{}{Felkészülni, azt hiszem, közel vannak!}
{262}{}{Nem adom meg magam harc nélkül.}
{263}{}{Soha sem tesztek minket rabszolgává.}
{264}{}{Azok a rabszolga-vadászok még megfizetnek ezért!}
{265}{}{Egy rabszolga-vadász sem veszi el a családom!}

#primitive jon
{270}{}{Nem taná'nak meg.}
{271}{}{E' kõ bújni. E' kõ bújni.}
{272}{}{Mér akarnak bántani?}
{273}{}{Megijedtem.}
{274}{}{Nem harcolok.}
{275}{}{Élni akarok.}
{276}{}{Ne báncs család!}


{280}{}{Ó, a fenébe!}
{281}{}{Miért csinálják ezt?}
{282}{}{Mi van a családommal?}
{283}{}{Nem akarok meghalni!}
{284}{}{Nem akarok rabszolga lenni.}
{285}{}{Én jobbat érdemlek.}

#primitive
{290}{}{Mostan halsz te meg!}
{291}{}{Én ölök!}
{292}{}{Te nem bántol család!}
{293}{}{Te nem viszed család!}
{294}{}{Én védekezek!}
{295}{}{Én fog bántani téged!}
{296}{}{Megfizetel!}


{300}{}{Nem viszed el a családomat, hajcsár!}
{301}{}{Meghalsz, rohadék hajcsár!}
{302}{}{Megfizetsz, te fattyú!}
{303}{}{Halálig harcolok a családomért!}
{304}{}{Ezt nem viszed el szárazon!}
{305}{}{Nem mész el innem a barátaimmal!}

#Primitive
{310}{}{Ahhh!}
{311}{}{Ne öjjé'! Ne öjjé'!}
{312}{}{Állj!}
{313}{}{Segííííccs!}
{314}{}{Fuss!}
{315}{}{Ne tegyed!}


{320}{}{Fussatok, ha kedves az életetek!}
{321}{}{Ne hagyd, hogy elfogjanak!}
{322}{}{Rabszolga-vadászok! Futás!}
{323}{}{Segítség, valaki! Kérem!}
{324}{}{Fuss, Marty!}
{325}{}{Ahh!}
{326}{}{Állítsd meg ezt az õrületet!}
{327}{}{Nem csináltunk semmit! Hagyj békén minket!}
