# Dialog Editor last position: 53
{100}{}{Õ a bolt tulajdonosa.}
{101}{}{Tubby.}
{150}{}{Õ az üzlet tulajdonosa.}
{151}{}{Õ Tubby, az üzlet tulaja.}
{152}{}{[Beszéd]}
{153}{}{Örülnék, ha máshol intézné a dolgait.}
{154}{}{Maga üzletember. Üzleteljünk.}
{155}{}{Kérdezhetek valamit?}
{156}{}{Viszlát!}
{157}{}{Annyira örülök, hogy újra látom. Miben segíthetek?}
{158}{}{Kereskedjünk!}
{159}{}{Kérdezhetek valamit?}
{160}{}{Most nem kérek semmit. Viszlát!}
{161}{}{Üdvözlöm, uram, Isten hozta Tubby boltjában. Én vagyok a tulajdonos. Segíthetek valamiben?}
{162}{}{Igen, csereberéli szeretnék.}
{163}{}{Információra lenne szükségem.}
{164}{}{Viszlát!}
{165}{}{Üdvözlöm, hölgyem. A barátaim Tubbynak hívnak, nagyon szívesen látom magát az üzletemben. Miben segíthetek?}
{166}{}{Vennék néhány dolgot.}
{167}{}{Információra van szükségem.}
{168}{}{Viszlát!}
{169}{}{Jobban örülnék, ha inkább távozna.}
{170}{}{Viszlát!}
{171}{}{Mit szeretne tudni?}
{172}{}{Ki vezeti ezt a várost?}
{173}{}{Miért árul mindenki drogokat?}
{174}{}{Tudja, merre van a Menedék?}
{175}{}{Mégiscsak úgy döntöttem, hogy csereberélnék.}
{176}{}{Áh, inkább hagyjuk most. Viszlát!}
{177}{}{Nahát! Úgy tûnik, a kommunikációval lesz egy kis gondunk. Kérlek bólints, ha szeretnél csereberélni.}
{178}{}{[Bólintasz]}
{179}{}{Sziaszia.}
{180}{}{Attól tartok, senki. Rejtek olyan hely, ahol anarchia uralkodik és egyfajta darwini kiválasztódás érvényesül. Itt csak a legerõsebb, a leggyorsabb vagy a legokosabb marad életben.}
{181}{}{Öm, köszi.}
{182}{}{Oké-oké... A drogok jelentik e város gazdaságának alapját. Pont úgy, mint máshol az arany vagy a gabona.}
{183}{}{Kösz.}
{184}{}{Hallottam egy Menedékváros nevû helyrõl, de hogy hol van pontosan, meg nem tudnám mondani magának. Nálunk nagyon kevesen tudnak elfogadható cserealappal szolgálni a menedékvárosiak által nyújtott egészségügyi ellátás fejében, így a legtöbbünk még soha nem járt ott.}
{185}{}{Oké. Köszi.}
{186}{}{Ez nem olyan infó, amit csak úgy bárkinek elmondanék.}
{187}{}{Egy százas megoldaná a nyelvét?}
{188}{}{Mi lenne, ha adnék 50 dolcsit és elmondaná nekem.}
{189}{}{Mit szólna, ha kapna két lehetõséget? Vagy elmondja az infót, vagy csinálok egy újabb lyukat a fejébe. Na?}
{190}{}{Hagyjuk...}
{191}{}{Akkor kérdezhetek valami mást?}
{192}{}{Persze, ez az összeg TALÁN segítene, de nincs magánál ennyi!}
{193}{}{Biztos elvesztettem valahol. Megyek, azt' megkeresem.}
{194}{}{Nem hiszem, hogy ennyi elég lesz.}
{500}{}{Persze, Petey. Mindjárt jövök.}
{501}{}{Kitartás, Petey!}
{502}{}{Jövök már, jövök.}
{510}{}{Tessék, Petey...}
{511}{}{Tudja, Petey, le kéne állnia ezzel a szarral!}
{512}{}{Fogja és tûnjön innen a francba, Petey!}
