# Dialog Editor last position: 117
{100}{}{Rabszolga-hajcsár.}
{150}{}{Nagyon figyel a mellette lévõ ajtóra.}
{200}{}{Hékás! El a kezekkel!}
{201}{}{Na, elég!}
{210}{}{Probléma???}
{211}{}{Gyakorolunk? Gyakorlunk?}
{212}{}{Hmmm.}
{220}{}{Tessék...}
{230}{}{Hali, hogy ityeg?}
{231}{}{Na, mi van, beléptél hozzánk, mi? Frankó. Remélem, majd megyünk együtt vadászatra.}
{232}{}{Tehát mirõl akarsz beszélni?}
{233}{}{Ki van bent?}
{234}{}{Vicrõl kérdeznék...}
{235}{}{Nem panaszkodhatom, köszi.}
{236}{}{Mennem kell.}
{237}{}{Wuk?}
{238}{}{Meko veek?}
{239}{}{Ugruk.}
{240}{}{Ruru!}
{250}{}{Vic... tönkretette a fõnök valamijét, vagy valami ilyesmi. Nem vagyok benne biztos.}
{251}{}{Vic... tönkretette a fõnök valamijét, vagy valami ilyesmi. Nem vagyok benne biztos.}
#ez a párbeszéd miatt van így 251 (Bass)
{252}{}{Ja, õrá gondolsz? Persze, valami kereskedõ. Mintha tönkretett volna valamit, de nem vagyok benne biztos. Miért? Ismered?}
{253}{}{Ja, õrá gondolsz? Persze, valami kereskedõ. Mintha tönkretett volna valamit, de nem vagyok benne biztos. Miért? Ismered?}
{254}{}{Igen?}
{255}{}{Miért õrzöd?}
{256}{}{Ki a fõnököd?}
{257}{}{Bemehetnék hozzá?}
{258}{}{Hát, eléggé jól képzett szerelõ vagyok. Tudnék segíteni esetleg?}
{259}{}{Hát, eléggé jól képzett vagyok a tudományokban, esetleg tudnék segíteni?}
{260}{}{Az ajtó zárva van. Ki tudnád nyitni?}
{261}{}{Kösz.}
{275}{}{Kösz a pénzt. Beszélhetsz vele, ha akarsz, de semmi cicó! Nem mehet ki a szobából Metzger beleegyezése nélkül.}
{276}{}{Megengedem, hogy beszélj vele, de semmi cicó! Nem mehet ki a szobából Metzger beleegyezése nélkül. }
{277}{}{Oké.}
{285}{}{Biztos kell legyek abban, hogy senki ne zavarja, míg a fõnöknek dolgozik, de leginkább abban, nehogy megszökjön.}
{286}{}{Talán azért, hogy meg ne szökjön. Valahogy megjavította a rádiót.}
{287}{}{Ki a fõnököd?}
{288}{}{Láthatom?}
{289}{}{Láthatom?}
{290}{}{Oké, köszi.}
{295}{}{Ó, persze. Nem úgy értettem, hogy újdonsült rabszolga-kereskedõ létedre már egybõl be is mehetsz hozzá.}
{296}{}{Ó, persze. Miért is ne. Nincs különösebb dolga és nem is megy sehova, úgyhogy nem hinném, hogy ez gond lenne.}
{297}{}{Akkor ki tudnád nyitni az ajtót?}
{298}{}{Oké, kösz.}
{305}{}{Természetesen. Nem tudtam, hogy most rögtön akarsz vele beszélni, bocs. Azt hittem, csak kiváncsiskodsz vagy valami.}
{306}{}{Kösz.}
{310}{}{Hogy? Az a mániád, hogy sosem látott helyekre is beteszed a lábad? Ez itt a Rabszolga-Céh. }
{311}{}{Aha, szóval a fõnököd onnan kapta a nevét...}
{312}{}{Szóval így állunk... Azt hittem, Kansas-ban vagyok.}
{313}{}{Oké, kösz.}
{320}{}{Hol? Nem, soha nem hallottam róla. Ez itt Rejtek. Nem tudok sokat arról a helyrõl, nem túl sokszor jutok ki innen. Bocs.}
{321}{}{Hülye.}
{322}{}{Rendben, kösz.}
{330}{}{Francba, ember! Metzger a rabszolga-kereskedõk vezére. Õ tartja kezében itt a dolgokat.}
{331}{}{Francba, hölgyem! Metzger a rabszolga-kereskedõk vezére. Õ tartja kezében itt a dolgokat.}
{332}{}{Hol az irodája?}
{333}{}{Oké, csá.}
{340}{}{Rögtön a hátsó ajtó mögött.}
{341}{}{Kösz.}
{350}{}{Bocs, nem értem.}
{351}{}{Hmmm.}
{360}{}{Bocs, Vichez nem mehet be senki.}
{361}{}{Igen, ez Vic.}
{362}{}{Seve?}
{363}{}{Surek?}
{364}{}{Gaw.}
{370}{}{Persze, bemehetsz hozzá.}
{371}{}{Persze, bemehetsz hozzá. Hadd nyissam ki neked!}
{372}{}{Köf.}
{380}{}{Valóban? Biztos vagyok benne, hogy a fõnök méltányolni fogja. Legalábbis amíg nyugton marad. Nem akarjuk, hogy még egyszer meglépjen.}
{381}{}{Kösz.}
{390}{}{Bocs, de nem. Dolga van, a fõnöknek dolgozik valamin.}
{391}{}{Bocs, nem tehetem. A fõnök közvetlen parancsa.}
{392}{}{Naszóval, megkaptad a pénzem?}
{393}{}{Csak meg akarok kérdezni tõle valamit.}
{394}{}{Ugyan már!!! Csak gyorsan beszélek vele...}
{395}{}{Igen. Tessék.}
{396}{}{Nem. Késõbb visszajövök.}
{397}{}{Ki a fõnököd?}
{398}{}{Nem fontos! Üdv!}
{410}{}{Hagyj békén! Metzgerrel beszélj! Õ a fõnök.}
{411}{}{Hagyj békén! Mi a fene bajod van?}
{412}{}{Mondtam már, beszélj Metzgerrel!}
{413}{}{Oké, rendben! Beszélhetsz vele, de aztán annyi... Egy lépést nem tehet a szobán kívûl. Fogtad? Na, gyerünk!}
{414}{}{Oké.}
{415}{}{Kösz!}
{430}{}{Igen, beszélj Metzgerrel! Szerintem tud ajánlani valami munkát. Mintha említette volna, hogy kell neki egy új ember.}
{431}{}{Ja, beszélj Metzgerrel! Szerintem tud ajánlani valami munkát. Azt mondta, kellene neki egy új ember... biztos vagyok benne, hogy megfelesz.}
{432}{}{Beszélj Metzgerrel!}
{433}{}{Ruru?}
{434}{}{Öö?}
{435}{}{Oh.}
{450}{}{Kapjátok el, fiúk!}
{451}{}{Kapjátok el, fiúk!}
{460}{}{Nem ér rá.}
{461}{}{Légyszi, nem jön ki majd a szobából. Megígérem!}
{462}{}{Nem lehetne valamit kitalálni? Valami pénzügyi megoldást...}
{463}{}{Oké, csõ.}
{470}{}{Rendben, öö... nem is tudom. Nem hiszem, hogy nagy gond lenne, ha beengednélek hozzá. Lecsengetsz 300 dollárt a markomba és már mehetsz is.}
{471}{}{Te megbolondultál! Ez túl sok!}
{472}{}{Baszd meg, haver!}
{473}{}{Persze.}
{474}{}{Bocs, de nincs ennyim.}
{480}{}{Rendben, érdekel. }
{481}{}{Oké.}
{482}{}{Rendben.}
{490}{}{Bocs, de nem.}
{491}{}{Azt mondtam, nem! Most pedig húzz innen! Beszélnem kell Metzgerrel.}
{492}{}{Oké.}

{500}{}{Elég baj, hogy nem csatlakoztál hozzánk.}
{501}{}{Be kellett volna lépned a céhbe.}
{502}{}{Õrködök... mint mindig..}
{503}{}{Remélem, Vic beválik.}
{504}{}{Vic jobban teszi, ha keményem dolgozik.}
{505}{}{Lehet, hogy egyszer elfoglak egy rabszolga-vadászaton.}
{506}{}{Hogy mennek a dolgok?}
{507}{}{Helló!}
