{100}{}{Rabszolga.}
{101}{}{Vic.}
{150}{}{Úgy tûnik, ezt a rabszolgát nagyon szemmel tartják.}
{151}{}{Õ Vic.}
{152}{}{[BESZÉD]}
{153}{}{Megmondaná neki, hogy én nem... na megálljunk! Ki vagy te? Te nem vagy hajcsár. Mit keresel itt?}
{154}{}{A nevem }
{155}{}{. Azért jöttem, hogy megszöktesselek.}
{156}{}{}
{157}{}{ az én nevem, de téged miért zártak be ebbe a szobába?}
{158}{}{Meg tudnád mondani, merre van a 13-as Menedék?}
{159}{}{}
{160}{}{ a nevem. Késõbb még visszajövök.}
{161}{}{Dubba iba }
{162}{}{.}
{163}{}{Metzger még mindig nagyon mérges rám, annak ellenére, hogy megjavítottuk azt a nyamvadt rádióját. Azzal fenyeget, hogy elad valakinek! Ha kijuttatsz ebbõl a nagy rakás kupiból, bármit megteszek neked, amire csak kérsz!}
{164}{}{Renden, rendben.}
{165}{}{Bocsi, nem tudlak. Minden jót!}
{166}{}{Hohóóó.}
{167}{}{Nahát, újra erre jártál? Ez a piszok rádió nem fog magától megjavulni! Hogyan is várhatná el tõlem Metzger, hogy helyre pofozzam?!}
{168}{}{Honnan szerezhetném be az alkatrészeket?}
{169}{}{Én talán meg tudnám javítani.}
{170}{}{Hasznát vennéd ennek a rádiónak, amit találtam?}
{171}{}{Meglátjuk, mit tehetek.}
{172}{}{Spa pa?}
{173}{}{Tudom, hogy semmiség megcsinálni, csak kellene egy-két alkatrész. Van egy régi rádióm Klamathban, a házikóm hátsó részében. Pont olyan, amilyen kell. Ismered a Duntonék üzletét? A házikóm az övékétõl keletre áll.}
{174}{}{Erre a rádióra gondolsz?}
{175}{}{Megyek és megkeresem!}
{176}{}{Hhmmm... Még visszanézek!}
{206}{}{Pontosan itt van. [egy térképre mutat]}
{177}{}{Nagyszerû! Pillanatokon belül megjavítom a rádiót!}
{178}{}{Oké, beszélek Metzgerrel.}
{179}{}{Kösz.}
{180}{}{Üdv!}
{181}{}{Hogy? Elnézést, de nem értem.}
{182}{}{Hmm.}
{183}{}{Köszönöm szépen! Örökké adósod maradok. Hogyan hálálhatnám meg?}
{184}{}{Mondd meg, hol van a 13-as Menedék!}
{186}{}{Csatlakozz hozzám! Jól jönne a segítség!}
{187}{}{Á, semmiség, ugyan már! Ég veled!}
{188}{}{Van cukorka?}
{189}{}{A 13-as Menedék? Innen keletre ott van Menedékváros. Néhányszor jártam ott üzletelni.}
{190}{}{Eljössz velem oda?}
{191}{}{Kösz! Csocsesz!}
{192}{}{Naná! Beállok hozzád! Ez a vén trotty már látott egy-két érdekes dolgot, ebben biztos vagyok! Ráadásul szinte mindent meg tudok szerelni, bármit is mondjon Metzger!}
{193}{}{Nagyszerû, induljunk!}
{194}{}{Üdvözöllek a csapatban!}
{195}{}{Öööö... izé.}
{196}{}{Vic legjobb barátom!}
{197}{}{Akarsz segíteni a keresésben?}
{198}{}{Nagyon jó! Kösz!}
{203}{}{Menedékváros innen keletre van. Mindjárt megmutatom a térképeden.}
{204}{}{Kösz!}
{220}{}{A fene egye meg! Majdnem megvan, de szükségem lenne a rádiómra a klamath-i házamból. Tudom, hogy pontosan ugyanolyan alkatrészek vannak benne, mint amik nekem kellenek.}
{300}{}{Ja, valószínûleg tudok rajtad segíteni, de elõtte ki kell hoznod engem innen.}
{301}{}{Megmondtam. Amennyiben ki tudsz innen jutattni, rám bármiben számíthatsz.}
{302}{}{Hogy kellene csinálni?}
{303}{}{Akkor saját magadra vagy utalva.}
{304}{}{Okés, majd meglátom mit tehetnék ezügyben.}
{350}{}{Szerinted én ki tudnálak innen hozni?}
{351}{}{Metzger még mindig nem enged elmenni.}
{352}{}{Én nem bírom itt tovább!}
{353}{}{Akármit megteszek érted, ha segítesz rajtam!}
{354}{}{Megtérítem az összes költségedet!}
{400}{}{Ugye még nem voltál a házamban? Tényleg nagyon kellene az a rádió, Metzger kezd egyre jobban begõzölni!}
{450}{}{Honnan szerezted azt a kulacsot?}
{451}{}{Van egy kulacsom, rajta egy bazi nagy sárga tizenhármassal. Emlékszel még, honnan szerezted?}
{500}{}{Na, ja! Emlékszem bizony. Ed-tõl vettem. Õ egy menedékvárosi brahminkupec.}
{501}{}{Kulacs? Óh, várj csak! Ja, van egy jó pár tucattal belõle. Elég jól el lehet passzolni. Ed-tõl, a menedékvárosi brahminkupectõl szereztem.}
{502}{}{Menedékvárost mondtál?!}
{550}{}{Abbahagynád ezt a folytonos fõnöközést?}
{600}{}{Hogyne, fõnök!}
{601}{}{Azt mondtam, hogy ELÉG!}
{602}{}{Remélem, ez megteszi.}
{650}{}{Rendicsek, komám!}
{651}{}{Úúg!}
{700}{}{Legyééél a barátom!}
{710}{}{Megmondanád neki, hogy ezt nem tudom megcsinálni pótalkatrészek nélkül. Hát nem tudom... várj! Ki vagy te? Valami új ember? Ugye azért küldött ide, hogy megint buzeráljon, mint a múltkor? Ettõl még semmi nem fog megváltozni! Itt nem tudom megcsinálni!}{750}{}{Igazán megtennéd ezt értem? Semmit sem tudok tenni, amíg nem keveredtem ki innen. A gond csak az, hogy Metzger egy rádió megjavítása miatt zárt be ide, és nincsenek meg a szükséges pótalkatrészek.}
{753}{}{Honnan tudnám elõkeríteni azokat az alkatrészeket?}
{754}{}{Majd kiderül, mit tudok tenni az ügy érdekében.}
{760}{}{Ez egy bonyolult és hosszú történet. Szerintem annyi elég lesz röviden, hogy Metzger itt tart engem, amíg meg nem javítom neki ezt a nyamvadt rádiót. A kristály kiégett, és nincs semmilyen pótalkatrészem. Így hogy a francba várhatja el tõlem, hogy megcsináljam?!}
{761}{}{Azért jöttem, hogy kiszabadítsalak.}
{764}{}{Nem tudom. Na, minden jót!}
{800}{}{Meg kell szerelnem ezt a rádiót. Ha tudnál nekem segíteni ebbe, esetleg tudnánk mire hivatkozni.}
{801}{}{Hol találok ilyen pótalkatrészeket?}
{803}{}{Kétlem. Sok szerencsét!}
{810}{}{Miért ölted meg szegény Mamát? Bizonyára megvolt rá az okod... Elnézést, fõnök! Nekem ugyebár nem osztottak lapot itt. Ez egy nagyon gonosz város. Biztos vagyok benne, hogy õ is valami gonoszságot mûvelt.}
{811}{}{Hé, fõnök! Kösz, hogy kirángattál abból a slamasztikából, amibe Metzgerrel keveredtem! Kell valami? Mama volt olyan rendes és ellátott, amíg nem voltál itt. Segítek neki a ház körül...}
{812}{}{Üdv!}
{813}{}{Óóoooh...}
{814}{}{Szia szia!}
{823}{}{Még egyszer megkérdem: hol találom Ed barátodat?}
{830}{}{Megtenném, ha tudnám, de problémásnak tûnsz. Csak felesleges teher lennék. Most, hogy a Mama meghalt, világgá megyek. Még nem tudom, hova. Talán látjuk még egyszer egymást valamikor. Mindent köszönök, amit értem tettél!}
{831}{}{Megtenném, ha tudnám, de problémásnak tûnsz. Látszik, hogy csak alig tudod megvédeni magad. Én meg csak púp lennék a hátadon. Majd állok és várok itt, a Mama fõztje emlékeztet a volt feleségemére...}
{832}{}{Szívesen megtenném, de tényleg! Szinte bármit megtennék érted. Csak mostanában nem tûnsz túl jó fõnöknek. Én csak konc lennék a nyakadon. Egy kicsit visszanézek a Mamához... Amíg a dolgok tisztázódnak. Már vagy ezer éve nem ettem abból a csodálatos levesébõl.}
{833}{}{Sajnálom, fõnök. Túl sokan vagytok. Most, hogy a Mama eltávozott, fogom magam és felszívódok. Azt sem tudom még, hogy hova... Egyszer még majd találkozunk valamikor. Köszönök mindent, amit értem tettél!}
{834}{}{Nem férek be a csapatba, fõnök. Itt várok rád, amíg megoldódnak a dolgok. A Mama fõztje emlékeztet a volt nejemére... Nem vagyok benne biztos, hogy ez jót vagy rosszat jelent...}
{835}{}{Én benne lennék, fõnök, de szemlátomást kevés hely van nálad. Elmegyek a Mamához. Rég nem voltam már náluk. Majd nézz arra, ha lenne még kiadó hely a csapatodban.}
{840}{}{Ed Menedékvárosban lakik. Brahminkereskedõ. A számos ellátóim egyike volt. Menedékváros nincs messze innen.}
{845}{}{Mondtam... itt van, ni! [Vic rámutat egy helyre a PipBoyodon.]}
{900}{}{Megtudtad, hogy Vic kereskedõ.}
{1000}{}{Meg kell kérdeznem valamit tõled.}
{1100}{}{Teljesen fel vagyok gyógyulva, fõnök. Egyéb teendõ?}
{1200}{}{Majdnem tökéletes formában vagyok, fõnök.}
{1300}{}{Nagyjából be vannak kötözve a sebeim, fõnök, de voltam már jobban is.}
{1400}{}{Próbáltam, fõnök, de nem eszik olyan forrón a kását! Megteszek minden tõlem telhetõt.}
{1500}{}{Ahogy parancsolja, kedves fõnök!}
{1501}{}{Itt? Pont itt? Rendben, te vagy a fõnök.}
{1502}{}{Oké. Itt maradok, amíg vissza nem jössz, fõnök. Ugye vissza fogsz jönni?}
{1503}{}{Ameddig csak akarod. Én egy tapodtat sem mozdulok innen!}
{1504}{}{Természetesen, fõnök!}
{1600}{}{Ha te mondod...}
{1601}{}{Jó beszólás, fõnök!}
{1602}{}{Nagy ötlet, fõnök!}
{1603}{}{Naná, fõnök! Más egyéb?}
{1604}{}{Messze van, fõnök!}
{1605}{}{Nem gond, fõnök!}
{1606}{}{Kész, fõnök!}
{1700}{}{Naná, fõnök!}
{1701}{}{Közel van, fõnök!}
{1702}{}{Te tudod a legjobban, fõnök.}
{1703}{}{Mögötted vagyok, fõnök!}
{1704}{}{Tapadok, mint a pióca, fõnök!}
{1705}{}{Ha így akarod, fõnök.}
{1706}{}{Óh! Okés, fõnök!}
{1800}{}{Rendben, tartok némi távolságot, de nem megyek túl messzire, fõnök!}
{1801}{}{Oké, nem fogok, fõnök.}
{1802}{}{Akkor egy kicsit lemaradok, fõnök.}
{1803}{}{Persze, fõnök!}
{1900}{}{Jól van, fõnök! Kicsit lemaradok.}
{1901}{}{Ahogy mondod, tisztelt fõnököm!}
{1902}{}{Te mész elõl, fõnök.}
{1903}{}{Lemaradok, fõnök.}
{1904}{}{Hátrébb megyek, fõnök.}
{1905}{}{Arrébb húzódok, fõnök!}
{1906}{}{Okés, fõnök!}
{2000}{}{Ööhm... fõnök? Egy kicsit sokan vagyunk. Itt maradok, és várok rád.}
{2100}{}{Megrémisztesz, fõnök! Mi történt veled? Olyan... izé, ijesztõen nézel ki. Asszem, itt maradok egy ideig...}
{2200}{}{Kétségtelen, fõnök!}
{2201}{}{Állatira rendben lesz, fõnök!}
{2202}{}{Tutira, fõnök!}
{2203}{}{Amint kész vagy, én is kész vagyok, fõnök!}
{2204}{}{Nagyszerû! Menjünk!}
{2205}{}{Nagyszerû!}
{2206}{}{Te vagy a legjobb, fõnök!}
{2207}{}{Nem leszel többé csalódott. Nem lesz itt több hiba!}
{2208}{}{Ezúttal óvatosabb leszek, ne aggódj!}
{2209}{}{Tudtam, hogy meg fogsz bocsátani nekem ezért... Ööhm. Na, akkor ööö... fõnök. Mi a terv?}
{2210}{}{Nem engedlek meghalni, fõnök!}
{2211}{}{Szuper vagy, fõnök!}
{2212}{}{Tudtam, hogy annyira öreg azért nem vagyok még ehhez. Csak kicsi volt a valószínûsége! Ugye, fõnök?}
{2300}{}{Ed-tõl. A fickó brahminokkal kereskedik Menedékvárosban. Jártál már arra? Hadd mutatassam meg azon a térkép-izéden!}
{2305}{}{Menedékvárosban. Itt! Hadd mutassam meg azon az aranyos térkép-micsodádon!}
{2310}{}{Neki valahol itt kell lennie.}
{2311}{}{Menedékvárosban. Nézd meg azon a térkép-bigyón!}
{2403}{}{Hol szerezted a 13-as Menedék kulacsát?}
{2404}{}{Sebaj!}
{2500}{}{Hogyne, fõnök!}
{2501}{}{Kérdezz bármit, fõnök!}
{2502}{}{Segítek, ha tudok, fõnök!}
{2503}{}{Ugye nem vagyok bajban, fõnök?}
{2504}{}{Valamit rosszul csináltam, fõnök?}
{2505}{}{Természetesen.}
{2600}{}{Most mit fogunk csinálni, fõnök?}
{2601}{}{Mi a terv, fõnök?}
{2602}{}{A legjobbat próbálom kihozni magamból, fõnök!}
{2603}{}{Mit tehetek érted, fõnök?}
{2604}{}{Változik a terv, fõnök?}
{2605}{}{Más stratégia, fõnök?}
{2700}{}{Elég jól ellátták a bajom, fõnök! Szerezned kell nekem egy orvost! Nem tudom, hogy valaha tudok-e még segíteni neked...}
{2701}{}{Orvosra van szükségem, fõnök! Elég rosszul nézek ki. Nem tudom, hogy valaha tudok-e még harcolni az oldaladon.}
{2702}{}{Szépen tropára mentem, fõnök! El kell vinned Lennyhez, hogy meg tudjon vizsgálni.}
{2800}{}{Hé, fõnök! Azt akarod, hogy csatlakozzam hozzád?}
{2801}{}{Hé, fõnök! Nem okoz gondot, hogy várni kell rád. Nagyon türelmes ember vagyok.}
{2802}{}{Újra együtt fogunk nyomulni, fõnök? Sokkal jobban fogok vigyázni.}
{2803}{}{Féltem, hogy esetleg sosem fogsz visszajönni. Örülök, hogy újra látlak, fõnök!}
{2804}{}{Megint szükséged van rám?}
{2805}{}{Készen állok, fõnök!}
{2806}{}{Tudtam, hogy nem hagysz el!}
{2807}{}{Kell némi erõsítés?}
{2808}{}{Ugye valamit meg kellene bütykölni? Én vagyok a te embered, fõnök!}
{2809}{}{Ne aggódj, fõnök! Sulik és én nagyon jól ki fogunk jönni egymással.}
{2810}{}{Induljunk!}
{2811}{}{Maradj itt! Mindjárt jövök.}
{2812}{}{Én menni.}
{3100}{}{Mi? Ööhm. Rendben, fõnök! Ha egyszer ezt mondtad...}
{3101}{}{Felvehetnék valami mást, fõnök? Egy kicsikét aggódom.}
{3102}{}{Okés! Nem fogsz engem itthagyni... Ugye, fõnök?}
{3103}{}{De... Értem... Természetesen, fõnök! Leszakadok.}
{3200}{}{Nos, fõnök... Elég tûrhetõen bánok a kisebb fegyverekkel. Tudok lõni szinte bármilyen puskával, sörétessel, és a legtöbb kis-közepes méretû pisztollyal is. Jól "forgatom" a késeket is. Ezen kívül jól tudok dobni, de célozni már nem annyira... Mondjuk úgy, rettenetesen. Nézd el nekem, fõnök! Én tényleg a legjobbat próbálom kihozni magamból.}
{3201}{}{Ahogy már mondtam, fõnök, a kisebb fegyverek kezelésében vagyok leginkább járatos. Rengeteg puskát ismerek - köztük a sörétest is - , a kis és közepes méretû pisztolyok többsége sem okoz gondot. Ha nagyon bajban lennénk, akár a kés vagy egyéb fegyverek dobásával is megpróbálkoznék.}
{3300}{}{Alap szinten bánok a késekkel és nagyon jól tudok dobni. Mondjuk nem vagyok túl jó célzó. Igazság szerint elég szörnyû. Bocsáss meg, fõnök! Minden erõmmel azon vagyok, hogy fejlesszem magam.}
{3301}{}{Mint már említettem, fõnök, forgatom a késeket is és nagyon jól tudok dobni... Csak egy picikét félre...}

{3400}{}{Na, eddig a pontig bírtam!}
{3401}{}{Letépem azt a tetves fejedet! Senki sem bánthajta a családomat!}

{4000}{}{Inkább ide?}
{4001}{}{Jobb így, fõnök?}
{4002}{}{Ez a hely megfelel?}
{4003}{}{Igen, fõnök!}
{4004}{}{Mi?}
{4005}{}{Hova megyünk?}
{4006}{}{Indulunk, fõnök?}
{4007}{}{Már megyek is!}
{4008}{}{Bocsánat, fõnök!}
{4009}{}{Így jobb?}
{4010}{}{Úúuuuf!}
{4011}{}{Így jó lesz, fõnök?}
{4012}{}{Akkor most ideállok.}
{4013}{}{Na, akkor arrébbállok szépen.}

{4100}{}{Fõnök! Nem érzem valami jól magam.}
{4101}{}{Szükségem van egy orvosra!}
{4102}{}{Ó, ember! Ez tényleg fáj!}
{4103}{}{Aú!}
{4104}{}{Jaj!}
{4105}{}{Francba!}
{4106}{}{Orvost!}
{4107}{}{Még elvagyok... de már csak alig...}

{4200}{}{Soha nem szerettem ezt a helyet.}
{4201}{}{Miért ilyen tiszta ez a hely?}
{4202}{}{Nem érzel valami szagot, fõnök?}
{4203}{}{Te tudod, fõnök. Nem hiszem, hogy miután elmentünk innen, valaha is visszajönnék ide. Már nem érzem az otthonomnak.}
{4204}{}{Határozottabban mocskosabb, mint amire emlékeztem.}
{4205}{}{Ugye nem maradunk itt sokáig, fõnök?}
{4206}{}{Ez a hely sosem fog megváltozni.}
{4207}{}{Nem fogom hiányolni ezt a helyet, fõnök.}
{4208}{}{Még egyszer kösz, hogy kihoztál onnan, fõnök!}
{4209}{}{Valóban jövök neked egyel, fõnök!}
{4210}{}{Nem semmi, ez a hely nagyon megváltozott.}
{4211}{}{Már évek óta nem jártam itt.}
{4212}{}{Itt fogok nyugdíjba menni.}
{4213}{}{Nyithatnék itt egy szerelõmûhelyt.}

{4300}{}{Íme, a lakhelyek lakhelye. Ez volt az én kis házikóm, de erre nyilván már magad is rájöttél. Ugye, fõnök?}

{4400}{}{Sulik, ne nézz így rám!}
{4401}{}{Fõnök, Sulik már megint engem bámul!}
{4402}{}{Aranyos kutyus.}

{4500}{}{Trallala}
{4501}{}{Hm-hm.}
{4502}{}{Várom a fõnököt...}
{4503}{}{Várom a fõnökömet.}
{4504}{}{Csak várok.}
{4505}{}{A fõnök tuti nem hagyna el...}
{4506}{}{Kopp-kopp, ki van ott? Várj! Hogy is...}
{4507}{}{Még várok.}
{4508}{}{Mi ez a szag?}
{4509}{}{Van itt valami javítanivaló?}
{4510}{}{Itt vagyok! Várok a fõnökre.}
{4511}{}{Egy magamfajta vénember csak elpazarolja a tehetségét a céltalan álldogálással.}
{4512}{}{Bárcsak lenne egy gumi nálam... már az idejét sem tudom, mikor voltam nõvel...}
#Ez most az egyszer nem ragogumi, hanem ovszer
{4513}{}{Ki kellene szállnom az ereklyeüzletbõl... Csak a gond van vele.}
{4514}{}{Miért ilyen fárasztó a várakozás...?}
{4600}{}{Üühm, kösz, fõnök!}
{4601}{}{Kösz!}
{4602}{}{Biztosan tudod, mit csinálsz?}
{4603}{}{Egyszerûen nem pihenhetnénk helyette?}
{4604}{}{Ne üssünk tábort?}
{4605}{}{Ennyire rosszul lennék?}

{4700}{}{Ne sokat, fõnök!}
{4701}{}{Ha ragaszkodsz hozzá, fõnök...}
{4702}{}{Fõnök, ugye nem fog szétrobbani a fejem?}
{4703}{}{Fõnök, van egy olyan érzésem, hogy kezdem megkedvelni ezt a vackot.}
{4704}{}{Egy kicsit mókásan érzem magam, fõnök.}
{4705}{}{Látom, van elég nálad.}
{4706}{}{Hogyne, fõnök! Beadom magamnak.}
{4707}{}{Kösz, fõnök!}
{4708}{}{Nem rossz!}
