# 0. Look
{100}{}{Hirdetõtábla.}

{150}{}{Úgy tûnik, van rajta pár üzenet.}

# 1. Main Page
{200}{}{Rejtek Hírek: Fenntartja: Rebecca Kaszinó Bárja, Rejtek legjobb piái itt találhatók. }
{201}{}{Rejtek Hírek: Fenntartja: Rebecca Kaszinó Bárja...}
{202}{}{[Egy ismeretlen odafirkált valamit a tábla szélére.]}
{203}{}{[Ennek a hirdetésnek egy részét letépték.]}
{204}{}{Rabszolga-Céh}
{205}{}{Bárok & Szerencsejátékok}
{206}{}{Kajálda}
{207}{}{Üzletek}

# 2. Slaver's Guild
{225}{}{A Rabszolga-Céh az egyetlen és legjobb rabszolga-ellátó az egész pusztaságban.}

# 3. Slaver's - Continue
{250}{}{Állásért, vásárlásért és eladásért, beszélj Metzgerrel!}

# 4. Slaver's - Directions
{275}{}{A Rabszolga-Céh a város keleti felében található, Becky és Frankie bárjain túl.}

# 5. Slaver's - Not selling
{300}{}{A megnõtt kereslet miatt jelen pillanatban nem adnak el magánembereknek.}

# 6. Bars and Gambling
{325}{}{[Kettõt látsz felsorolva]}

# 7. Becky's Casino Bar
{350}{}{Rebecca Kaszinó Bárjában mind a szerencsejátékot, mind az olcsó italokat megtalálod.}

# 8. Becky's Directions.
{375}{}{Innen egyenesen keletre találsz minket. Ahogy belépsz a városba, az elsõ épület balra. Gyere el bátran!}

# 9. Frankie's Message
{400}{}{Becky egy kurva és vizezett a piája! Csaló és hazug! [Az írás alig olvasható.]}
{401}{}{[Az ide ragasztott üzenet gondosan le lett tépve.]}

# 10. Dumb Board
{425}{}{[Szavak szavak... szavak...] Bár... [szavak...] Rejtekben.}
{426}{}{Nagyon zavarónak találod és meg is fájdult tõle a fejed.}

# 11. Frankie's
{450}{}{Frankie egy bárt, fogadót, és 'élvezetes' üzletet vezet a város keleti felén.}

# 12. Dining
{475}{}{A Mama étterme egyedülálló Rejtekben. A város keleti felén, délre a Rabszolga-Céhtõl megtalálod.}

# 13. Becky Dead
{500}{}{[Úgy tûnik, valaki megpróbálta felgyújtani. Egyik hirdetés sem olvasható.]}

# 14. Shops
{525}{}{[Három üzlet hirdetését olvashatod.]}

# 15. Tubby's
{550}{}{Tubby mindent árul, de legfõképp drogokat és lõszert.}

# 16. Tubby's Directions
{575}{}{Tubby a hirdetõtáblától nyugatra található. Ahogy belépsz a városba, az elsõ épület jobbra.}

# 17. Flick
{600}{}{Flick számtalan cuccot árul az "irodájában". A hely innen egyenesen délre van.}

# 18. Smitty
{625}{}{Smitty a helyi szerelõ. Néha elad egy-két dolgot.}

# 19. Smitty Directions
{650}{}{Smitty a roncstelepen található, a város dél-nyugati sarkában.}

# MENU OPTIONS
{1000}{}{Folytatás}
{1010}{}{Hol található?}
{1020}{}{Kilép}
{1030}{}{Flick}
{1040}{}{Frankie}
{1050}{}{Rebecca Kaszinó Bárja}
{1060}{}{Vissza a fõ oldalra}
{1070}{}{Smitty}
{1080}{}{Különleges hirdetés:}
{1090}{}{Tubby}