{100}{}{Ez az ember erõpáncélt visel.}
{101}{}{Sir Bedemir.}
{102}{}{Úgy tûnik, mélyen gondolkodóba esett.}
{103}{}{Sir Bedemir vagyok, szolgálatodra.}
{104}{}{...és így gyõzõdtek meg róla, hogy a Föld banán alakú.}
{105}{}{Mondd csak el még egyszer, hogy lehet birkavesével földrengést megelõzni?}
{106}{}{Most gondolkodnom kell. Kérlek, zavarj valaki mást!}

{200}{}{Hé, jéghidegek a kezeid!}
{201}{}{Az nem a tied!}
{202}{}{Hé, az ott mind az enyém!}