{100}{}{You see a Fisherman.}
{101}{}{Épp idõben érkeztél, hogy saját szemeddel lásd a Tenger Istennõjének áldását.}
{102}{}{[Tovább]}
{103}{}{}
{104}{}{Minden nagy vihar elõtt lándzsákat hajítunk a tengerbe, hogy megmutassuk az elemeknek a bátorságunkat. Ha méltónak találtatunk, az Istennõ gyümölccsel ajándékoz meg minket.}
{105}{}{Az viharos évszak kezdetekor broc-virágokat szórunk a tengerbe dagály idején. Az Istennõ mágiájának hatására a virágok helyett nagyon ritka xander gyökereket sodornak partra a hullámok.}
{106}{}{Minden évben xander gyökér áldozatot mutatunk be a Tenger Istennõjének. Ha az áldozat elfogadtatik, az Istennõ átváltoztatja a gyökereket broc virággá. }
{107}{}{Minden aratás után áldozatot mutatunk be a Tenger Istennõjének, hogy vigyázzon ránk és védjen minket. Áhítatunkat minden évben lándzsákkal jutalmazza, melyeket a hullámok vetnek partra. Ez a jel, hogy figyelni fog ránk.}
{108}{}{Láthatnám, mivel ajándékozott meg titeket az Istennõ?}
{109}{}{Ah...}
{110}{}{Itt láthatod, ami a magasságos istennõ ebben az évben adott nekünk. Szívesen megosztjuk veled az õ áldását, megfelelõ ellenértékért.}
{111}{}{Junk [$10]}
{112}{}{Lézerpisztoly [10000]}
{113}{}{Sharpened sticks [$40]}
{114}{}{Fruit [$5]}
{115}{}{Xander [$20]}
{116}{}{Broc [$10]}
{117}{}{Viszlát!}
{118}{}{[A tenger felé mutat.] Menj egyenesen elõre! Az Istennõ személyesen akar találkozni veled.}
{119}{}{[Vége]}
{120}{}{A Tenger Istennõjének áldása kísérjen utadon!}
{121}{}{[Vége]}
{122}{}{[Amikor látja, hogy nincs elég pénzed, összehúzza a szemöldökét.] Talán majd legközelebb.}
{123}{}{[Vége]}
