# Dialog Editor last position: 10
{100}{}{Egy férfi, erõpáncélban.}
{101}{}{Sir Galahad.}
{102}{}{Elpirul, amikor észreveszi, hogy õt nézed.}
{103}{}{Sir Galahad, szolgálatodra!}
{104}{}{Egyszer raboskodtam Rossznyavalyavárban.}
#A filmben ennek van fordítva. (bass)

{105}{}{Sir Launcelot megmentett. Az Isten verje meg!}
#Nem lancelot, hanem launcelot (Bass)

{106}{}{Még mindig rab lehetnék. [Szipp]}
{200}{}{Hé, jéghidegek a kezeid!}
{201}{}{Az nem a tied!}
{202}{}{Hékás, azok az én cuccaim!}
