{100}{}{Egy szikár, napbarnított embert látsz.}
{101}{}{Telepes.}
{102}{}{A farmerekre jellemzõ napcserzett bõre van.}
{103}{}{Épp a legjobbkor érkeztél. Ha késõbb jöttél volna... szóval, hálát adok az égnek, hogy idõben érkeztél. Nincs túl sok értékünk, de szeretném ha elfogadnád ezt jutalmul, amiért segítettél nekünk. [Átad neked valamit.]}
{104}{}{Köszönöm szépen.}
{105}{}{Ögh.}
{106}{}{Még egyszer köszönjük, hogy segítettél.}
{107}{}{}
{108}{}{}
{109}{}{Csak tartsd olyan helyen a kezed, ahol láthatom! Mostanában egyre több bandita járkál errefelé, és szerintem te is az vagy. Mit akarsz?}
{110}{}{Csak venni szeretnék ezt-azt.}
{111}{}{Átutazóban vagyok. Megyek is.}
{112}{}{Ögh.}
{113}{}{Hát, azt hiszem, azzal nem árthatsz. Itt van a kínálatom.}
{114}{}{[Üzlet]}
{115}{}{Oké, most eriggy!}
{116}{}{[Üzlet]}
{117}{}{Mondom, eriggy!}
{118}{}{}
{119}{}{[Megnyugszik egy kicsit.] Túl hülye vagy ahhoz, hogy bandita légy. Üzletelni akarsz?}
{120}{}{Ahha.}
{121}{}{[ingatod a fejed]}
{122}{}{Jól van. Megvolt az üzlet. Kérlek, távozz!}
{123}{}{[VÉGE]}
{124}{}{Hagyd el a farmomat!}
{125}{}{Senki nem veheti el tõlem az otthonomat!}
{126}{}{Mocskos banditák!}
{127}{}{Tûnj a földemrõl!}
{128}{}{Senkiben sem lehet bízni manapság.}
{129}{}{Rohadt banditák!}
{130}{}{Túl keményen dolgoztam ahhoz, hogy most feladjam.}
{131}{}{Talán máshol telepedek le.}
{132}{}{Csak egy szegény farmer vagyok.}
{133}{}{Kérlek, ne égesd fel a farmomat!}
{134}{}{Úgysem szerettem kapálni.}
{135}{}{Még visszatérek.}
{136}{}{Vidd inkább a feleségemet... kérlek...}