# Dialog Editor last position: 10
{100}{}{Ez a férfi éppen egy lanton pötyögtet.}
{101}{}{Joshua.}
{102}{}{Egy vándor kobzos.}
#Ezek mind a gyalog galoppbol vannak (bass)

{103}{}{Robin a bátor elszaladt...}
{104}{}{Bátran elfutott, el õ...}
{105}{}{A vész láttán, ahogy tudott, farkát behúzva elfutott.}
{106}{}{Jó messzire, s ina szakadt... mindõn nyúlként bátran szaladt.}
{107}{}{Elõre csak lassan jutott, mert közben többször elcsúszott...}
{108}{}{A bátor, a bátor, a hõs sir Robin...}
{109}{}{Óh, a bátor sir Robin...}
