{100}{}{Egy II-es erõpáncélt viselõ férfit látsz. Nem látszik barátságosnak.}
{101}{}{Kagát látod, aki egy II-es erõpáncélt visel.}
{102}{}{Egy jó nagy vasdarab, karokkal és fegyverekkel.}
{103}{}{Belefáradtam az üldözésbe. Fejezzük ezt be!}
{104}{}{Ez az utolsó alkalom, hogy Kagával találkozol.}
{105}{}{Nem kelhetsz versenyre Kagával!}
{106}{}{Már alig várom, hogy a következõ életedbe küldhesselek.}
{107}{}{Méltó ellenfél voltál.}
{108}{}{A pusztaságnak ez a része nem tart igényt a magadfajta jótevõkre.}
{109}{}{Miután megöltelek, én leszek a legrettegettebb ember a pusztaságnak ezen a részén.}
{110}{}{Már alig várom, hogy hazatérhessek Arroyóba... porig fogom égetni!}
{111}{}{Kaga híres lesz, amiért megöl téged.}
