# Dialog Editor last position: 10
{100}{}{Egy alig felöltözött férfit látsz.}
{101}{}{Kaga.}
{103}{}{Az illetõ ágyékkötõt visel, és úgy néz ki, mintha valami törzs tagja lenne.}
{104}{}{Nekem kellett volna a Kiválasztottnak lennem!}
{105}{}{Hogy mert elûzni engem Arroyo a törzsbõl?!}
{106}{}{Most megbosszulom!}
{107}{}{Kaga a következõ életbe küld téged.}
{108}{}{Találkozni fogunk még!}
{109}{}{Még sohasem gyõztek le!}
{110}{}{Az elpuszításodnak szentelem az életem!}
