# Dialog Editor last position: 14
{100}{}{Egy bõrpáncélt viselõ férfit látsz.}
{101}{}{Kaga.}
{102}{}{Bõrpáncélt visel, és van egy nagyon idegesítõ szokása: harmadik személyben beszél saját magáról.}
{103}{}{Ez lesz az utolsó alkalom, hogy Kaga találkozott veled.}
{104}{}{Miután Kaga megölt téged, porig fogja égetni Arroyót.}
{105}{}{Érezd Kaga haragját!}
{106}{}{Én vagyok a nagy Kaga!}
{107}{}{Kagát mindenki rettegi!}
{108}{}{Kaga megtartja a fejedet trófeaként.}
{109}{}{Add meg magad, és a halálod gyors lesz.}
{110}{}{Kaga visszatér!}
{111}{}{Nem ölheted meg a nagy Kagát!}
{112}{}{Szerencsés vagy, hogy Kagának máshol van dolga.}
{113}{}{Kaga majd újra találkozni fog veled.}
