# Dialog Editor last position: 11
{100}{}{Egy férfit látsz harci páncélban.}
{101}{}{Kagát látod harci páncélban.}
{102}{}{Harci páncélt visel, és úgy tûnik, néhány egész tûrhetõ fegyvere is van.}
{103}{}{Ez alkalommal felkészültem rád.}
{104}{}{A Kiválasztott sohasem fog visszatérni Arroyóba!}
{105}{}{Kaga szét fog zúzni téged!}
{106}{}{Kaga nem fél senkitõl!}
{107}{}{Maradj mozdulatlan, hogy Kaga pontosan célozhasson!}
{108}{}{Találkozni fogunk még!}
{109}{}{Ez nem az utolsó alkalom, hogy láttad Kagát.}
{110}{}{Kagának határozottan több gyakorlásra van szüksége...}
