# Dialog Editor last position: 12
{100}{}{Egy fémpáncélt viselõ férfit látsz.}
{101}{}{Kaga.}
{102}{}{Egen, ez Kaga, a nem-is-annyira-nagy. Fémpáncélja van, és bizony éppen meg akar ölni téged.}
{103}{}{Megint te vagy?}
{104}{}{Kezdek belefáradni, hogy állandóan találkozunk.}
{105}{}{Kiválasztott... hogy oda ne rohanjak!}
{106}{}{Vessünk véget ennek!}
{107}{}{Meg fogod bánni, hogy hallottad Kaga nevét!}
{108}{}{Utolsó találkozásunk óta gyarapodtak a képességeim.}
{109}{}{Ez most már kezd rossz szokássá válni.}
{110}{}{Kagának még egy kis gyakorlásra van szüksége.}
{111}{}{Kaga visszatér még...}
