{100}{}{Egy nomád embert látsz.}
{101}{}{Nomád sámán.}
{102}{}{A gyógynövények erõs illata illik a fickó ruházatához.}
{103}{}{Üdvözlégy, idegen! Én vagyok a törzs sámánja. Képzett vagyok a gyógyítás mûvészetében.}
{104}{}{Üdv!}
{105}{}{Szükségem lenne némi gyógyításra.}
{106}{}{Össze tudod keverni a xander gyökeret és a broc virágot?}
{107}{}{Viszlát!}
{108}{}{Úúga.}
{109}{}{Maradj nyugodtan, hogy megvizsgálhassalak!}
{110}{}{[Tovább]}
{111}{}{Igen, van itt egy-két probléma.} #continue at 136
{112}{}{Tudsz segíteni?}
{113}{}{A megfelelõ összegért a következõkben tudok neked segíteni:} # continue at 140
{114}{}{Távolítsd el a mérget a szervezetembõl!}
{115}{}{Kérlek, gyógyíts meg!}
{116}{}{Lássuk, mit tudsz kezdeni azzal a bénult végtaggal!}
{117}{}{Viszlát!}
{118}{}{Meggyógyultál.}
{119}{}{Meggyógyultál.}
{120}{}{Meggyógyultál.}
{121}{}{Szükségem lenne még a gyógyító tudásodra.}
{122}{}{Köszönöm! Sokkal jobban érzem magam. Viszlát!}
{123}{}{Az én tudásom is véges. Sajnos nem tudok rajtad többet segíteni.}
{124}{}{[Tovább]}
{125}{}{Nincs szükséged efféle gyógyításra!}
{126}{}{[Tovább]}
{127}{}{Áhh... Szóval ismered a két növény gyógyító erejét. Lássuk csak, az annyi lesz, mint} # continue at 150
{128}{}{Kérlek, keverd össze a két növényt!}
{129}{}{Talán majd késõbb, viszlát!}
{130}{}{[Figyeled, ahogyan óvatosan összemorzsolja és elkeveri a két növényt, majd átnyújtja neked a precízen kimért gyógyító por adagokat.]}
{131}{}{Viszlát!}
{132}{}{Úgy tûnik, kevés a pénzed. Akkor gyere vissza, ha kövérebb a pénztárcád!}
{133}{}{[VÉGE]}
{134}{}{Nincs idõm ilyen lehetetlenségekre. Távozz!}
{135}{}{[VÉGE]}
{136}{}{[Mérgezés]}
{137}{}{[Sérülés]}
{138}{}{[Sugárfertõzés]}
{139}{}{[Törött végtag]}
{140}{}{Méregtelenítés,}
{141}{}{Törött testrész meggyógyítása,}
{142}{}{A gyógyítás $}
{143}{}{Hitetlen!}
{144}{}{Miért támadsz meg minket?}
{145}{}{Az életemmel védelmezem a törzsemet!}
{146}{}{Hogy merészeled így megsérteni a vendégszeretetünket!?}
{147}{}{Távozz!}
{148}{}{Menj innen!}
{149}{}{Mi békés törzs vagyunk!}
{150}{}{ dollár, és összekombinálom neked ezt a kettõt.}