# Dialog Editor last position: 12
{100}{}{Ah! Még egy újonc.}
{101}{}{Csatlakozz, vagy pusztulj el!}
{102}{}{Itt bármit elérhetsz.}
{103}{}{Kevesen vagyunk, büszkék vagyunk, zsoldosok vagyunk.}
{104}{}{Csatlakozz hozzánk!}
{105}{}{Te kis "E" kategóriás...}
# 4F classification meant the army would never want you (bass)

{106}{}{Ideje máshol körülnézni!}
{107}{}{Menj, csatlakozz a Haditengerészethez!}
{108}{}{Fenébe!}
{109}{}{Azta! Nézd csak, mennyi az idõ, mennem kell!}
{110}{}{Újonc.}
{111}{}{Õrmester.}
