{100}{}{Egy utazót látsz.}
{101}{}{Üdv, utazó!}
{102}{}{Útba tudsz igazítani néhány város felé?}
{103}{}{Merre tartasz?}
{104}{}{Mivel foglalkozol?}
{105}{}{Aghhh!}
{106}{}{Hát... nem biztos, hogy tudok segíteni. Új vagyok ezen a környéken, még csak az alábbi helyeken voltam.}
{107}{}{New Reno.}
{108}{}{Menedékváros.}
{109}{}{Redding.}
{110}{}{The Den.}
{111}{}{San Francisco.}
{112}{}{New California Republic.}
{113}{}{Egy elhagyatott bánya.}
{114}{}{Most ennyi elég is lesz. Köszönöm.}
{115}{}{New Reno -- now that's a great place to go. Sex, drugs and gambling. What more can one ask for?
 Here, let me show you where it is.}
{116}{}{Kösz.}
{117}{}{Menedékváros - idióták városa. Ha csak egy ujjal több van a kezeden, máris úgy kezelnek, mint egy korcsot. Soha nem voltam ott, de tudom, merre található.}
{118}{}{Kösz.}
{119}{}{Redding... Nem tudok róla sokat, csak annyit, hogy egy régi bányászváros. Fent van északon, a legmegmászhatatlanabb hegyek kellős közepén.}
{120}{}{Kösz.}
{121}{}{A helyedben távol maradnék Rejtektől. Vonzza a rosszéletűeket, akár egy mágnes. Megmutatom, hogy hol van, de nem ajánlom, hogy odamenj.}
{122}{}{Kösz.}
{123}{}{San Francisco. Ööö... csak annyit tudok róla mondani, hogy az emberek nagyon... furcsák arrafelé. A part mentén található.}
{124}{}{Kösz.}
{125}{}{Új Kalifornia Köztársaság... na, az egy jó hely. Ott szeretnék majd letelepedni egy szép napon. Ápolt, rendes emberek lakják, akik nem szűkölködnek semmiben. A térképen pont itt található.}
{126}{}{Kösz.}
{127}{}{Igen, nemrég áthaladtam egy elhagyatott bányásztáboron. Gondoltam, hogy pihenek ott egy-két napot, de hirtelen farkasok jelentek meg a semmiből, úgyhogy inkább gyorsan leléptem. Kár, mert úgy tűnt, hogy a bányászok sietve távoztak. Ott maradt egy csomó cuccuk. Nem tervezem, hogy visszamegyek, szóval azt hiszem, nyugodtan megmutathatom, hol találtam rá.}
{128}{}{Kösz.}
{129}{}{Ó... nincs konkrét célom. Csak egyszerűen elhatároztam, hogy utazni fogok. Hát, most itt vagyok.}
{130}{}{Talán tudsz segíteni. Meg tudnád mondani egy-két város helyét?}
{131}{}{Mivel foglalkozol?}
{132}{}{Jó volt társalogni egy kicsit.}
{133}{}{Elvállalok néha egy-két munkát, hogy meglegyen a betevő, de leginkább csak utazgatok.}
{134}{}{Talán tudsz segíteni. Meg tudnád mondani egy-két város helyét?}
{135}{}{Mi az úticélod?}
{136}{}{Jó volt társalogni egy kicsit.}
{137}{}{Most már igazán mennem kell. Örültem a beszélgetésnek.}
{138}{}{Talán még találkozunk.}
{139}{}{Még az éj beállta előtt a következő faluban szeretnék lenni. Jobb, ha indulok.}
{140}{}{Jobb lesz, ha megyek.}
{141}{}{Rajtaütés!}
{142}{}{Manapság már senkiben sem lehet megbízni.}
{143}{}{Megszegted az utazók íratlan törvényeit!}
{144}{}{Ideje indulnom.}
{145}{}{Túl sokáig időztem itt.}
{146}{}{Mennem kell.}
{150}{}{Thanks. I need directions to some other places.}
