{100}{}{Egy utazó.}
{101}{}{Üdv, utazó!}
{102}{}{Útba tudsz igazítani néhány város felé?}
{103}{}{Merre tartasz?}
{104}{}{Mivel foglalkozol?}
{105}{}{Ögh.}
{106}{}{Hát... nem biztos, hogy tudok segíteni. Új vagyok ezen a környéken, még csak az alábbi helyeken voltam.}
{107}{}{New Reno érdekelne.}
{108}{}{Menedékváros merre van?}
{109}{}{Hol találom Reddinget?}
{110}{}{Hogy jutok el Rejtekbe?}
{111}{}{Merre van San Francisco?}
{112}{}{Az Új Kalifornia Köztársaságot keresem.}
{113}{}{Egy elhagyatott bánya.}
{114}{}{Most ennyi elég is lesz. Köszönöm.}
{115}{}{New Reno - jó kis hely. Szex, drogok és szerencsejáték. Mi kellhet még? Hadd mutassam meg, hol van!}
{116}{}{Kösz.}
{117}{}{Menedékváros - idióták városa. Ha csak egy ujjal több van a kezeden, máris úgy kezelnek, mint egy korcsot. Soha nem voltam ott, de tudom, merre található.}
{118}{}{Kösz.}
{119}{}{Redding... Nem tudok róla sokat, csak annyit, hogy egy régi bányászváros. Fent van északon, a legmegmászhatatlanabb hegyek kellõs közepén.}
{120}{}{Kösz.}
{121}{}{A helyedben távol maradnék Rejtektõl. Vonzza a rosszéletûeket, akár egy mágnes. Megmutatom, hogy hol van, de nem ajánlom, hogy odamenj.}
{122}{}{Kösz.}
{123}{}{San Francisco. Ööö... csak annyit tudok róla mondani, hogy az emberek nagyon... furcsák arrafelé. A part mentén található.}
{124}{}{Kösz.}
{125}{}{Új Kalifornia Köztársaság... na, az egy jó hely. Ott szeretnék majd letelepedni egy szép napon. Ápolt, rendes emberek lakják, akik nem szûkölködnek semmiben. A térképen pont itt található.}
{126}{}{Kösz.}
{127}{}{Igen, nemrég áthaladtam egy elhagyatott bányásztáboron. Gondoltam, hogy pihenek ott egy-két napot, de hirtelen farkasok jelentek meg a semmibõl, úgyhogy inkább gyorsan leléptem. Kár, mert úgy tûnt, hogy a bányászok sietve távoztak. Ott maradt egy csomó cuccuk. Nem tervezem, hogy visszamegyek, szóval azt hiszem, nyugodtan megmutathatom, hol találtam rá.}
{128}{}{Kösz.}
{129}{}{Ó... nincs konkrét célom. Csak egyszerûen elhatároztam, hogy utazni fogok. Hát, most itt vagyok.}
{130}{}{Talán tudsz segíteni. Meg tudnád mondani egy-két város helyét?}
{131}{}{Mivel foglalkozol?}
{132}{}{Jó volt társalogni egy kicsit.}
{133}{}{Elvállalok néha egy-két munkát, hogy meglegyen a betevõ, de leginkább csak utazgatok.}
{134}{}{Talán tudsz segíteni. Meg tudnád mondani egy-két város helyét?}
{135}{}{Mi az úticélod?}
{136}{}{Örülök, hogy találkoztunk.}
{137}{}{Most már igazán mennem kell. Örültem a beszélgetésnek.}
{138}{}{Talán még találkozunk.}
{139}{}{Még az éj beállta elõtt a következõ faluban szeretnék lenni. Jobb, ha indulok.}
{140}{}{Jobb lesz, ha megyek.}
{141}{}{Rajtaütés!}
{142}{}{Manapság már senkiben sem lehet megbízni.}
{143}{}{Megszegted az utazók íratlan törvényeit!}
{144}{}{Ideje indulnom.}
{145}{}{Túl sokáig idõztem itt.}
{146}{}{Mennem kell.}