# Dialog Editor last position: 1
{100}{}{Ez itt egy punk srác mosolynak is nevezhetõ arckifejezéssel.}
{101}{}{Õ Borz.}
{102}{}{Ez itt egy punk srác, arcán olyasféle arckifejezéssel, amit akár kaján mosolynak is nevezhetnénk.}
{103}{}{::Hangosan böfög::: Mit akarsz?}
{104}{}{::Böfögsz::}
{105}{}{Ki vagyol?}
{106}{}{Te ki vagy?}
{107}{}{Tudnál mondani valamit errõl a tankerrõl!}
{108}{}{Mivel foglalkozol itt?}
{109}{}{Szeretném, ha meghekkelnéd nekem a számítógépet.}
{110}{}{Hogy halad a hekkelés?}
{111}{}{Semmit. Jó büfizést!}
{112}{}{::Megereszt egy újabb öblös büffentést::}
{113}{}{::Még hangosabban büfögsz::}
{114}{}{Picsába.}
{115}{}{::Olyan éktelen nagyot büfög, hogy égzengésnek is beillene::}
{116}{}{::Megtapsolod::}
{117}{}{Borz vagyok. Volt egy zenekarom... ::felsóhajt:: Az volt a nevünk, hogy "Elégtünk". Most én vagyok az ügyeletes számítógép buherátor San Franban.}
{118}{}{Ah, köszi!}
{119}{}{Miket tudsz varázsolni a számítógéppel?}
{120}{}{Gondolom befuccsoltatok a bandával.}
{121}{}{Jó volt az a zenekar?}
{122}{}{Köszi, Szia.}
{123}{}{Ööö... oké.}
{124}{}{Szia!}
{125}{}{Ezügyben beszélj Marc-kal vagy a Kapitánnyal!}
{126}{}{Hol találom Marcot?}
{127}{}{Hol találom a Kapitányt?}
{128}{}{Én vagyok a helyi számítógép-zseni.}
{129}{}{Miket tudsz varázsolni a számítógéppel?}
{130}{}{Köszi. Szia.}
{131}{}{Ne basztass már... ::Fingik egyet:: Dolgozom rajta, ha nem látnád!}
{132}{}{Jól van, jól van. Majd szólj, ha kész van!}
{133}{}{Hát mondjuk úgy, hogy én egy információszerzõ specialista vagyok.}
{134}{}{Tudnál nekem is szerezni dolgokat?}
{135}{}{Hova akarsz kilyukadni?}
{136}{}{Hát akkor baszódj meg!}
{137}{}{Hé!}
{138}{}{Baszódj meg te!}
{139}{}{Hát jobb, ha tudod, hogy királyok voltunk! Az énekesünk... ööö... egy kicsit ripacs volt, Aaron folyton problémázott, minden egyebet meg Todd szúrt el. Ennek ellenére jók voltunk.}
{140}{}{Kár, hogy már nem játszotok együtt. Szívesen meghallgattalak volna titeket.}
{141}{}{Öö. Hogyne. Hadd kérdezzek valamit.}
{142}{}{Fogadjunk, befuccsoltatok.}
{143}{}{Marc rendszerint lenn a bárban múlatja az idõt.}
{144}{}{Köszi. Volna még egy-két kérdésem.}
{145}{}{Köszi. Ez minden.}
{146}{}{A Kapitány általában a hídon tartózkodik. A bárból feljuthatsz a lépcsõn.}
{147}{}{Köszi. Hadd kérdezzek egy s mást!}
{148}{}{Köszi. Ez minden.}
{149}{}{Oké, de ezért a zsebedbe kell nyúlnod.}
{150}{}{Mennyit kérsz?}
{151}{}{Igen, hogyne... de most mennem kell.}
{152}{}{Ez azt jelenti, hogy ha adatokat akarsz felkutatni, én vagyok a te embered.}
{153}{}{Megcsinálnál nekem valamit?}
{154}{}{Értem. Ez király. Még kérdeznék valamit, ha nem zavar.}
{155}{}{Értem. Köszi.}
{156}{}{Igen, kéne. Egyébként vissza kell térnem ehhez a vacakhoz.}
{157}{}{Várj! Még akarok kérdezni valamit.}
{158}{}{Köszi. Viszlát!}
{159}{}{Szerintem vagyunk annyira jóban, hogy segítsek neked. Kit látogassak meg?}
{160}{}{A Hubologistákat.}
{161}{}{A Shiket.}
{162}{}{Senkit. Csak tájékozódom.}
{163}{}{Asszem, amiért megmentetted a csajomat, ingyen megcsinálom. Persze eltart majd egy darabig. Hova törjek be neked?}
{164}{}{A Hubologistákhoz.}
{165}{}{A Shikhez.}
{166}{}{Egyikhez sem. Csak tájékozódom.}
{167}{}{Elõször is tégy nekem egy szívességet! A barátnõmnek nyoma veszett a tankerben. Találd meg nekem és akkor megcsinálom.}
{168}{}{Megegyeztünk. Üdv!}
{169}{}{Ne is álmodj róla! Üdv!}
{170}{}{Ez olyan, mint cukorkát lopni egy kisgyerektõl. Sosem fognak megtalálni. Mit akarsz tõlük?}
{171}{}{Nagyszerû! Kérdeznék még ezt-azt, ha nem probléma.}
{172}{}{Nagyszerû! Késõbb visszajövök.}
{173}{}{El tudom érni õket. Az infó szerint elégé védettek, a gépeiket komoly J.É.G. védi. Teljesen biztos vagy abban, hogy igényled a segítségemet ez ügyben?}
{174}{}{Akkor jó szerencsét! Ellenben kérdeznék egy-két dolgot.}
{175}{}{Jó szerencsét! Késõbb visszajövök.}
{176}{}{Találd meg nekem a barátnõmet és akkor majd beszélgethetünk.}
{177}{}{Rendben, rendben!}
{178}{}{Meghalt? MEGHALT? Hogy  halt meg? Ne, inkább mégse mondd el... tartsd meg magadnak! Adj néhány órát, hogy összeszedjem magam!}
{179}{}{Hogyne, hogyne.}
{180}{}{Ne durcáskodj már, öcsém! Csomó dolgunk van, vazze!}
{181}{}{Rendben. Már jobban vagyok.}
{182}{}{Jó. Meg kell, hogy kérdezzek valamit.}
{183}{}{Na, tessék. Én nem akartam veled beszélni.}
{184}{}{Köszönöm, köszönöm, köszönöm. Nem tudom eléggé megköszönni, hogy megmentetted õt. Miben segíthetek?}
{185}{}{Volna néhány kérdésem.}
{186}{}{A hálád elég nekem. Viszlát!}
{187}{}{Oké, behatoltam a Shi számítógépekbe. Nem tudom, észrevettek-e. Szerintem most a legjobb az lesz, ha meghúzzuk magunkat. Egyéb teendõ?}
{188}{}{Volna.}
{189}{}{Nincs. Üdv!}
{190}{}{Megfogtam a Hubologistákat. Nem ügy. Segíthetek bármi egyébben?}
{191}{}{Igen.}
{192}{}{Nem kell. Üdv!}
{193}{}{Nagy hibát követtél el, haver! A számítógépeken keresztül a Shiket és a Hubologistákat is neked ugrasztottam. Neked véged van, mint a botnak San-Franciscóban.}
{194}{}{Hát, akkor asszem, most megöllek.}
{195}{}{Adj néhány órát, hogy összeszedhessem magam!}
{196}{}{Egy formázott számítógépbe hatoljak be? Az információnak már annyi. Rá nem veszel erre.}
{197}{}{Elhagyom ezt a helyet.}
{198}{}{Jó, hogy látlak.}
{199}{}{Üzemanyag után hajkurászok.}
{200}{}{Úgy hallottam, a Hubologistáknak van üzemanyaguk, esetlek ránézhetek a számítógépükre.}
{201}{}{Az összes üzemanyagot a Shik birtokolják nálunk. Ha akarod, rákukkanthatok neked a számítógépükre.}
{202}{}{Megtennéd?}
{203}{}{Mi a fenét akarsz?}
{204}{}{Borzot, a punk-ot, szerintem.}
{205}{}{Megszégyenítetted az Uralkodónkat!}
{206}{}{Asszem, megyek cukorkáért Lao Chouhoz a városba.}
{207}{}{Ennyit a tisztességes tárgyalásról. Hmmm...}
{208}{}{Haver, fogd vissza magad! Én csak egy kis cukorkát szerettem volna.}
{209}{}{Át tudnád irányítani az üzemanyagot az ûrhajóból a tankerbe?}
{210}{}{Tudnál szerezni egy példányt a gépmadár terveibõl?}
{211}{}{Át tudnád irányítani az üzemanyagot és mellé meg tudod szerezni nekem a terveket?}
{212}{}{Igen, szükségem van a dolgaikra.}
{213}{}{Na, mindegy, majd valahogy megoldom.}
{214}{}{Jó-jó, de szar kerülhet a palacsintába.}
{215}{}{Át tudnád irányítani az üzemanyagot a tartályokból a tankerbe?}
{216}{}{Na, sebaj, majd máshogy megoldom.}
{217}{}{Na, sebaj.}
{218}{}{Rendben. Kábé egy napon belül gyere vissza és megbeszéljük.}
{219}{}{Megszerezted, amit kértem?}
{220}{}{Igen, megvan az üzemanyag.}
{221}{}{Igen, megvan a gépmadár terve.}
{222}{}{Igen, megvannak a tervek meg az üzemanyag is.}
{223}{}{Nagyon szépen köszönöm. Még látjuk egymást.}
