# Dialog Editor last position: 9
{100}{}{Ez itt egy savanyú képû Shi férfi.}
{101}{}{Õ Dr. Jing Tie Gahng.}
{102}{}{Egy fehér köpenyes Shi férfihez van szerencséd.}
{103}{}{Maga kicsoda? Mit akar itt?}
{104}{}{Mi?}
{105}{}{MAGA kicsoda?}
{106}{}{A nevem}
{107}{}{Semmi köze hozzá!}
{108}{}{Semmit. Itthagyom magát.}
{109}{}{Ha elmebeteg, akkor nem idevaló. Menjen innen, mielõtt hívom az õrséget!}
{110}{}{Úgy látszik, maga tényleg nem ért a szóból! Talán majd az õrség jobb észre téríti. Õrség! Behatoló!}
{111}{}{-kész-}
{112}{}{Jing Tie Gahng vagyok, az Acélpalota vegyi laboratóriumának vezetõje... maga épp egy fontos munkafolyamatot zavart meg. Kérem, távozzon! MOST AZONNAL... mielõtt hívom az õrséget!}
{113}{}{Hívja csak õket, vénember!}
{114}{}{Jó, jó, már megyek is.}
{115}{}{Nézze,}
{116}{}{Igen. Azért jöttem, hogy üzemanyagot szerezzek a Poseidon Olaj Tanker számára.}
{117}{}{Szeretném megtudni, hogy mit csinálnak ebben a laborban.}
{118}{}{Azért jöttem, hogy üzemanyagot szerezzek a Hubologisták számára.}
{119}{}{Nincs. Már megyek is.}
{120}{}{Már hogyne volna közöm hozzá! Ez itt az én laborom. Most pedig adja elõ, mit keres itt!}
{121}{}{Azért jöttem, hogy üzemanyagot szerezzek a Poseidon Olaj Tanker számára.}
{122}{}{Szeretném megtudni, mivel foglalkozik itt.}
{123}{}{Azért jöttem, hogy üzemanyagot szerezzek a Hubologisták számára.}
{124}{}{Nem adom elõ. Már megyek is...}
{125}{}{Üzemanyagot akar a tankerbe? Én meg egy megerõsített erõpáncélt akarok. Tudok egy Hubologistáról, Crocketnek hívják, aki közönséges erõpáncélokat szokott felturbózni. Szerezzen nekem egy olyan öltözéket, és megkapja az üzemanyagot.}
{126}{}{Megyek, beszélek vele.}
{127}{}{Nem ígérhetek semmit.}
{128}{}{Épp itt van nálam egy.}
{129}{}{Mûanyagokat és berendezéseket gyártok az Uralkodónak és az Uralkodó tanácsadójának, Ken Leenek. Jelen pillanatban olyan üzemanyag származékokon és polimereken dolgozom, amelyek egy komoly támadást is elviselnek. Persze nyilván ez nem nagyon érdekli magát, hiszen egyelõre csak elméletben léteznek.}
{130}{}{Az a helyzet, hogy érdekel a dolog. Üzemanyagot szeretnék a Poseidon Olaj Tankerbe.}
{131}{}{Le merném fogadni, hogy a Hubologistákat érdekelné. Üzemanyagra fáj a foguk.}
{132}{}{Egyelõre valóban nem. Késõbb viszont lehet. Majd még jövök!}
{133}{}{Szóval üzemanyagot akarnak? Hát amilyen bosszantó egy népség, bizonyára megvan rá az okuk. Úgy hallottam, kifejlesztettek egy eljárást, amellyel egy közönséges erõpáncélt még ellenállóbbá tudnak tenni. Ha csinálnak nekem egy olyan páncélt, megkapják az üzemanyagukat. Gondolom a kis játék-ûrhajójukba kell. Egy Crocket nevû emberrel kellene beszélnie ez ügyben.}
{134}{}{Megyek, beszélek vele.}
{135}{}{Nem ígérhetek semmit.}
{136}{}{Épp itt van nálam egy.}
{137}{}{Még ha akarnék is segíteni, nem tudok. Az üzemanyag tartalékaink kimerültek. Talán a Hubologistáknál kéne érdeklõdnie. Viszlátásra.}
{138}{}{Aha, hát akkor ennyi lenne.}
{139}{}{Ez a lehetetlen határát súrolja. Az üzemanyag tartalékaink kimerültek. Még ha akarnék is segíteni a Hubologistáknak - ami távol áll tõlem -, nem tehetnék semmit. Viszlátásra.}
{140}{}{Rendben, viszlát!}
{141}{}{Jó. Akkor hadd tegyem a dolgomat.}
{142}{}{-kész-}
{143}{}{Nem tudja megcsinálni? Akkor mondjon le az üzemanyagtól is! Távozzék, most dolgom van!}
{144}{}{-kész-}
{145}{}{Van magánál egy megerõsített erõpáncél? Kiváló! Milyen fizetségre gondolt?}
{146}{}{Ezért cserébe, kérem, irányítsa át az üzemanyagot a Hubologisták számára!}
{147}{}{Irányítsa át az üzemanyagot a Hubologisták számára!}
{148}{}{Mit szólna egy kis pénzhez? Mondjuk }
{149}{}{Úgy döntöttem, hogy inkább megtartom.}
{150}{}{Vegye elintézettnek! Rövidesen megcsinálom a változtatásokat. Most pedig, ha megbocsát, vár a munka...}
{151}{}{Köszönöm. Viszlát!}
{152}{}{Ilyen sokat? Ah! Hát egy ilyen fejlett páncél tanulmányozásáért... jól van. Itt a pénze.}
{153}{}{Köszönöm. Viszlát!}
{154}{}{Meg akarja tartani? Helyes. Ha meggondolta magát, csak szóljon!}
{155}{}{Szólok. Viszlát!}
{156}{}{Aligha. Viszlát!}
{157}{}{Õrség! Õrség! Visszajött a kívülálló! Megölni!}
{158}{}{Beszélt a Crocket nevû Hubologistával a páncél ügyében? Megszerezte?}
{159}{}{Nem, még nem beszéltem.}
{160}{}{Akkor miért zaklat folyton feleslegesen?}
{161}{}{Azért, mert kérdezni akarok egy s mást.}
{162}{}{Fogalmam sincs. Viszlát!}
{163}{}{Ne tegye próbára a türelmemet!}
{164}{}{Mit akar?}
{165}{}{Maga mivel foglalkozik itt?}
{166}{}{Azért jöttem, hogy üzemanyagot szerezzek a Poseidon Olaj Tankerbe.}
{167}{}{Azért jöttem, hogy üzemanyagot szerezzek a Hubologisták számára.}
{168}{}{Semmit. Elnézést.}
{169}{}{Teljesen kifogytunk az üzemanyagból. Másban nem tudok segíteni. Ez a páncél túlságosan leköt. Viszlát!}
{170}{}{-Viszlát-}
{171}{}{. Csak körülnézek itt.}
{172}{}{, meg kell kérdeznem, van-e itt valami dolga.}
{173}{}{ dollár megfelelõ lenne.}
{174}{}{Annyi van, amennyi szükséges. Beszéljen Wonggal, ha elengedhetetlen!}
