{100}{}{Egy köpcös, jól tápált Shi férfihez van szerencséd.}
{101}{}{Ő Dr. Wong Yi Tze.}
{102}{}{Egy köpcös, jól tápált Shi férfihez van szerencséd.}
{103}{}{Segítséget nyújthatok önnek, kérem?}
{104}{}{Daghi nu?}
{105}{}{Te vagyol ki?}
{106}{}{Úgy hallottam, magánál van egy illető lépe.}
{107}{}{Ki vagy?}
{108}{}{Mit csinálsz itt?}
{109}{}{Nem, köszönöm. Ez minden.}
{110}{}{Meg kell vallanom valamit. Nem beszélem az ön nyelvét. Talán Ken Leevel kéne beszélnie, ő nagyon sokféle nyelvet megért.}
{111}{}{Agh!}
{112}{}{Dr. Wong vagyok. Én vagyok e létesítmény vezető tudósa.}
{113}{}{Kérem, még kérdeznék.}
{114}{}{Köszönöm. Viszlát!}
{115}{}{Az általunk folytatott kísérleteket felügyelem. Ezenkívül a számítógép-hálózatért is én felelek.}
{116}{}{Mik a tervei?}
{117}{}{Hogy tud az ember hozzáférni a számítógép-hálózathoz?}
{118}{}{Volna még néhány egyéb kérdésem.}
{119}{}{Értem. Viszlát!}
{120}{}{Ah, abban az esetben, ha elmondom önnek a terveimet, mindenki tisztában lesz velük. Attól tartok, egyelőre titokban tartom őket.}
{121}{}{Remek, remek. Van még néhány kérdésem.}
{122}{}{Köszönöm. Viszlát!}
{123}{}{Mi lenne, ha egy puskacsövet nyomnék az orra alá és úgy szedném ki magából?}
{124}{}{Az ember megtanulja, hogy kell behatolni a rendszerbe, hogyan kell összebratyizni valamelyik beosztottammal. Természetesen csak viccelek. Ha ilyesmit akarna tenni, magára küldenék valakit, hogy ölje meg. [mosolyog, jelezvén, hogy nem akar megbántani ezzel.]}
{125}{}{Maga tényleg megölne engem?}
{126}{}{Szóval nem lenne komoly kifogása az ellen, hogy rákattanjak a számítógépre?}
{127}{}{Volna még néhány kérdésem.}
{128}{}{Hát persze. Viszlát!}
{129}{}{Fenyegetésnek venném és figyelmeztetném, hogy ez megárthat az egészségének.}
{130}{}{Tegyünk egy próbát!}
{131}{}{Csak poénkodtam. Inkább kérdeznék valami mást.}
{132}{}{[mosolyog] Meg kell védenünk a becsületünket, idegen.}
{133}{}{Öö, hogyne. Szóval nem lenne ellenére, ha rákattannék a számítógépre?}
{134}{}{Úúúúgy van. Hadd kérdezzek még!}
{135}{}{Le merném fogadni. Viszlát!}
{136}{}{Ha meg tudja győzni a beosztottaimat... üsse kő.}
{137}{}{Mi lenne, ha egy fegyert dugnék az orra alá?}
{138}{}{Nagyszerű! Hát, még kérdeznék, ha nem gond.}
{139}{}{Hmm. Értem. Hát akkor viszlát!}
{140}{}{Ahh, igen! Bizony. Szép nagy szemű babbal fogom elkészíteni, és jó Chianti-t fogok inni hozzá.}
{141}{}{Még megvan magának? Remek. Chip már epedve várja.}
{142}{}{Az egy emberi lép, maga beteg állat!}
{143}{}{Azt ugye tudja, hogy ehhez májat kell felszolgálni, nem lépet?}
{144}{}{Tudja... az egy emberi lép.}
{145}{}{Ki ez a Chip? A lép az enyém és meg fogom enni vacsorára.}
{146}{}{Chip a lép eredeti tulajdonosa. Részeg volt és eladta Lao Chounak.}
{147}{}{Az a helyzet, hogy szeretne életben maradni, ezért vissza akarja kapni. Belőle származik ugyebár.}
{148}{}{Akkor esetleg megölöm magát, hogy visszakapjam.}
{149}{}{Az üzet az üzlet. Jobb lesz, ha búcsút int a lépének. Sajnálom, de mi megegyeztünk és az, hogy Chip megbánást tanúsít, nem jelenti, hogy vissza lehet táncolni az üzlettől.}
{150}{}{[TOVÁBBI LEHETŐSÉG]}
{151}{}{Az egy emberi lép? La Chou ezt nem említette!}
{152}{}{Ennek ellenére, a hírvivő kíméletlensége miatt, azt hiszem, a megállapodáshoz fogom tartani a feleket. Kísérleteket fogok végezni azon a lépen.}
{153}{}{Mondja el a barátjának, hogy holnapig jöjjön érte, és akkor örömmel visszaadom. Remélem, megtalálja a módját, hogy időben visszakerüljön a testébe.}
{154}{}{Jól van.}
{155}{}{Haha! Igen, én is láttam azt a régi filmet. Na, várjunk... mit akar ezzel mondani? Csak nem azt, hogy...?}
{156}{}{Igen, az bizony egy emberi lép.}
{157}{}{Igazság szerint ellenkeznék ezzel. Maga nem bizonyult jó embernek. Azt sem tudom, miért beszélek magával egyáltalán. Minden jót!}
{158}{}{[RENDBEN]}
{159}{}{Aijjj! Őrség! Itt van a lao wai behatoló!}
{160}{}{Vannak vázlatai, amit odaadna nekem?}
{161}{}{Ken Lee mondta nekem, hogy adjam ezeket magának.}
{162}{}{Igen. Mit kapok cserébe?}
{163}{}{Nem, még nem.}
{164}{}{Beszéljen Ken Leevel! Megtárgyalhatják, mi legyen a jövőjével. Köszönöm. Ezzel képesek leszünk ellenőrizni a tesztadataink egy részét. Minden jót!}
{165}{}{Az a helyzet, hogy volna még más kérdésem.}
{166}{}{Viszlát!}
