{100}{}{Egy lelkes Shi.}
{101}{}{Õ Mai Da Chiang, a Red 888 Fegyverbolt tulajdonosa.}
{102}{}{Ez egy jól táplált Shi, aki úgy lászik, állandóan magas fordulatszámon pörög.}
{103}{}{Üdvözöllek a Red 888 Fegyverboltban! Mai Da Chiang vagyok, a tulaj. Segíthetek?}
{104}{}{Grokken di ma!}
{105}{}{Én vásárol!}
{106}{}{Valami fegyverzet vásárlásán töröm a fejem.}
{107}{}{Mesélj errõl a helyrõl!}
{108}{}{Felejtsd el!}
{109}{}{Sajnálom! Nem értem a nyelvedet! Minden jót!}
{110}{}{Rrr?}
{111}{}{Ahh, fegyvert vennél, mi? Hát... ezt tudom nyújtani.}
{112}{}{-tovább-}
{113}{}{Nagyszerû, nagyszerû. Kösz az üzletelést. Jöjj vissza mihamarabb!}
{114}{}{Még kérdeznék!}
{115}{}{Üdv!}
{116}{}{Nem. Nem elég jó. Sajnálom. Esetleg valami egyéb?}
{117}{}{Még kérdeznék.}
{118}{}{Nem. Viszlát!}
{119}{}{Szükséged van még valamire?}
{120}{}{Én vásárol!}
{121}{}{Nem. Üdv!}
{122}{}{Valami fegyverzet vásárlásán töröm a fejem.}
{123}{}{Mesélj errõl a helyrõl!}
{124}{}{Felejtsd el!}
{125}{}{Évek óta itt élünk, de ez nem mindig volt így. Dr. Fung tudja a teljes történetünket. Le merném fogadni, hogy az érdekel, amivel mi foglalkozunk.}
{126}{}{Igen.}
{127}{}{Nem, igazság szerint a történelem érdekel. Megyek, megkeresem Fungot. Minden jót!}
{128}{}{Embereink fõleg halászattal és tudományokkal foglalkoznak. A halászok halat fognak, a tudósok pedig egy olyan projekten dolgoznak, amely az elmondásuk szerint hamarosan megváltoztatja a világot.}
{129}{}{Meg akarják változtatni a világot?}
{130}{}{Mi egyéb történik manapság a városban?}
{131}{}{Hmm. Érdekes. Még kérdeznék valamit, ha nem gond.}
{132}{}{Kösz. Üdv!}
{133}{}{Nem tudok egyebet mondani. A titkaikat megtartják maguknak.}
{134}{}{Értem. Mi egyéb történik a városban?}
{135}{}{Értem. Hadd kérdezzek még valamit!}
{136}{}{Kösz. Üdv!}
{137}{}{A városban két rivális harcmûvész verseng egymással. Az egyik Lo Pan, az önzõ, a másik a Sárkány, az emberek pártfogója. Azt mondják, bármelyikük is nyer, az esemény meghatározza majd a harcmûvészetek jövõjét.}
{138}{}{Értem. Van valami egyéb a városban?}
{139}{}{Értem. Volna még néhány kérdésem.}
{140}{}{Kösz.}
{141}{}{Egy rakás csavargó felköltözött a kikötõben álló Poseidon Olaj Tankerre. Szörnyek tanyáztak a hajóban, de azok a csavargók bezárták õket a hajótest alsóbb szintjeire. Habár kívülállókról van szó, hálásak vagyunk, hogy megtették ezt nekünk.}
{142}{}{Egyéb újság?}
{143}{}{Értem. Hadd kérdezzek még valamit!}
{144}{}{Kösz. Üdv!}
{145}{}{A tudósok azt jelentették, hogy valaki áttörte a számítógépes védelmüket és ellopta a titkainkat.}
{146}{}{Egyéb újság?}
{147}{}{Értem. Hadd kérdezzek még valamit!}
{148}{}{Kösz. Üdv!}
{149}{}{Jelen pillanatban más nem jut eszembe. Szép napot!}
{150}{}{Jó napot!}
{151}{}{Tolvaj, gyilkos, bûnözõ vagy. Attól tartok, meg kell, hogy öljelek.}

