{100}{}{A férfi úgy néz ki, mint egy eladó.}
{101}{}{Lao Chou, a boltos.}
{102}{}{Az illető praktikus, kényelmes öltözéket visel.}
{103}{}{Légy üdvözölve az üzletemben, a Repülő Sárkány 8-ban.}
{104}{}{Segíthetek valamiben?}
{105}{}{Da aggle oo!}
{106}{}{Cucc!}
{107}{}{Ki vagy?}
{108}{}{Felszereléseket szeretnék vásárolni.}
{109}{}{Információt szeretnék.}
{110}{}{Viszlát!}
{111}{}{Akarsz vásárolni valamit?}
{112}{}{::bólintasz::}
{113}{}{::megrázod a fejed::}
{114}{}{Ezzel szolgálhatok.}
{115}{}{[DONE]}
{116}{}{Nos, ennél többet nem tehetek érted. Minden jót!}
{117}{}{[DONE]}
{118}{}{Lao Chou vagyok. Én vezetem ezt a vegyesboltot, a Repülő Sárkány 8-at. Olyan embernek ismernek engem, aki... információkban utazik...}
{119}{}{Miféle információra gondoltál?}
{120}{}{Értem. Vethetek egy pillantást a felszereléseidre?}
{121}{}{Kevés olyan dolog történik a városban, amiről ne tudnék. Persze csak a megfelelő kérdést kell feltenned ugyebár... Mit szeretnél tudni?}
{122}{}{Szeretnék tuningokat egyes cuccaimhoz.}
{123}{}{Hol találom meg a gépmadár terveit?}
{124}{}{Üzemanyagot szeretnék találni a POT Valdez számára.}
{125}{}{Rájöttem, hogy szükség van egy FBK-ra, hogy kezelhessem a Valdez számítógépét.}
{126}{}{Kéne néhány számítógép-alkatrész a POT Valdez működtetéséhez.}
{127}{}{Egy lép nyomában kutatok.}
{128}{}{Úgy hallottam, egy repülő alkalmatosság falusiakat hozott errefelé.}
{129}{}{Semmit. Viszlát!}
{130}{}{Talk to Crockett, over in the Hubologist camp. He is their head scientist.}
{131}{}{Köszi. Szeretnék még egy-két infót.}
{132}{}{Köszönöm. Viszlát!}
{133}{}{Kutakodj északon, Navarróban! A benzinkút közelében van egy titkos bázisuk.}
{134}{}{Köszi. Szeretnék még egy-két infót.}
{135}{}{Köszönöm. Viszlát!}
{136}{}{Próbáltad már a régi Menedékekben? Úgy hallottam, hogy az ősök rakás információját és technológiáját tárolják odalenn.}
{137}{}{Köszi. Szeretnék még egy-két infót.}
{138}{}{Köszönöm. Viszlát!}
{139}{}{Egy lép nyomában? Haha! Igen, Chip a Valdezről nemrég elvesztette a lépét kártyán. Eladtam Dr. Wongnak. Nagyon odavolt tőle.}
{140}{}{Dr. Wong? Hol találom őt?}
{141}{}{Hogy lehet elveszteni egy lépet?}
{142}{}{Köszönöm. Volna még néhány kérdésem.}
{143}{}{Ja, vagy úgy... Üdv!}
{144}{}{Dr. Wong az Acél Palota fő kutatója. Keresd ott!}
{145}{}{Hogy lehet egy lépet véletlenül elveszíteni?}
{146}{}{Köszi. Szeretnék még egy-két infót.}
{147}{}{Köszönöm. Viszlát!}
{148}{}{Részeg volt. Nagyon, nagyon részeg. Egész éjszaka csak a lépére panaszkodott, aztán fogadott rá.}
{149}{}{EZÉRT vetted ki a lépét?}
{150}{}{Értem. Hát... talán inkább kérdeznék valami mást.}
{151}{}{Igen. Adósság volt, és ő becsületes ember.}
{152}{}{Értem. Szeretnék még egy-két infót.}
{153}{}{Te beteg vagy, vazger!}
{154}{}{Szuper. Viszlát!}
{155}{}{Te viszont becstelen ember vagy! Nem tűrlek a boltomban. Gyere vissza máskor!}
{156}{}{Jól van, jól van...}
{157}{}{Nem-nem. Észak felől jöttek, és elrepültek fölöttünk, egyenesen a nyílt tenger irányába.}
{158}{}{A nyílt tenger irányába? Hogy a francba menjek arrafelé?}
{159}{}{Aha, hát hogyne... Mondd el, hol vannak, mielőtt felbontalak, mint egy doboz szardíniát!}
{160}{}{Az a nagy helyzet... hogy a hajóink egyike sem alkalmas olyan nagy távolság megtételére. Hacsak...}
{161}{}{Hacsak...?}
{162}{}{Kösz a "segítségért". Inkább valami használhatóbb tanács után nézek...}
{163}{}{...hacsak nem tudod működésre bírni a kikötőben veszteglő ósdi tankert. Ősrégi hajó ugyan, de ha egy kicsit foglalkozik vele az ember, még működhet. Kérdezd az ottani punkokat, ha több információ kell!}
{164}{}{Köszi. Szeretnék még egy-két infót.}
{165}{}{Köszönöm. Viszlát!}
{166}{}{Azt rebesgetik, hogy a Hubologisták nagy mennyiségű üzemanyagra tettek szert a közelmúltban. Próbálj velük egyezkedni!}
{167}{}{Köszi. Szeretnék még egy-két infót.}
{168}{}{Köszönöm. Viszlát!}
{169}{}{Próbálkozz valamelyik Shi tudóssal az Acél Palotában! Talán sikerül megoldaniuk az üzemanyag-problémádat.}
{170}{}{Köszi. Szeretnék még egy-két infót.}
{171}{}{Köszönöm. Viszlát!}
{172}{}{Te az ellenségünk vagy. Halál rád!}
{173}{}{Azzal, hogy eltetted BHK-9-t láb alól, nagy szolgálatot tettél a népemnek. Remélem, valahogy a szolgálatodra lehetek.}
{174}{}{Ki vagy?}
{175}{}{Felszereléseket szeretnék vásárolni.}
{176}{}{Információt szeretnék.}
{177}{}{Viszlát!}
{178}{}{Már odaadtad a Hubologistáknak, nemde?}
{179}{}{Ó, hogyne... ah... Kérdezhetek valami mást?}
{180}{}{Ó, hogyne... na, üdv!}
