{100}{}{Arrogáns Shi gengszter.}
{101}{}{Õ Lo Pan, egy dölyfös, kíméletlen férfi.}
{102}{}{Egy selyemruhába öltözött Shi gengszterhez van szerencséd. A keze alaposan fel van keményítve. Veszélyes és idegesítõ embernek tûnik.}
{103}{}{Mit akarsz?}
{104}{}{Daggle aggle aggle!}
{105}{}{Ki lenni?}
{106}{}{Kivel verekedtél?}
{107}{}{Kihez van szerencsém?}
{108}{}{Szeretnék úgy verekedni, ahogy te. Taníts, kérlek!}
{109}{}{Szeretnélek kihívni.}
{110}{}{Felejtsük el!}
{111}{}{Tûnés innen, idióta! Nincs mit mondanom a számodra!}
{112}{}{GRR!}
{113}{}{Lo Pan vagyok. A Sárkányt leszámítva én vagyok a város legjobb harcosa. Egy nap persze meg fog halni. Ha ez megtörténik, elkezdem tanítani a stílusomat.}
{114}{}{Taníts!}
{115}{}{Köfönöm.}
{116}{}{Tanulni akarsz? Megvan, ami kell hozzá? Na, lássuk csak...}
{117}{}{-kész-}
{118}{}{Miért is kéne téged tanítanom? Túlságosan öntörvényû embernek látszol. Tûnj innen!}
{119}{}{Mi a... ?}
{120}{}{Ó, te szerencsétlen... nem akarok beszélni veled. Eridj innen!}
{121}{}{Duhhh...}
{122}{}{A Sárkánnyal. Nyápic egy alak, aki a gyengeséget pártfogolja.}
{123}{}{A nép olyan, mint egy birkanyáj. Légy a magad ura!}
{124}{}{Micsoda? Te gonosz ember vagy akkor?}
{125}{}{Értem. Volna még néhány kérdésem.}
{126}{}{Gonosz? Aligha. Csak ravasz. Ha problémád van azzal, ha ennyire aggaszt a nép sorsa, eridj, beszélj a Sárkánnyal! Õ szereti a hozzád hasonló szenvelgõ puhányokat.}
{127}{}{-kész-}
{128}{}{Igen, azt kéne. Sõt azt is teszem. Sajnos a Sárkány az utamban áll. Túlságosan kiegyenlítettek a harci képességeink. Szükségem van egy képzett emberre, aki segítene nekem.}
{129}{}{Én jó leszek?}
{130}{}{Értem. Nos, még kérdeznék, ha nem gond.}
{131}{}{Értem. Hát akkor isten veled.}
{132}{}{Akár... képes vagy puszta kézzel és lábbal verekedni, védõfelszerelések és fegyverek nélkül?}
{133}{}{Képes, de miért is kéne ilyesmit tennem?}
{134}{}{Elég méltányos. Hogy mûködik a teszt?}
{135}{}{Ó, hát ebben az esetben mennem kell.}
{136}{}{Mivel a közemberek el fognak engem átkozni és sokkal nehezebb lesz õket betörni, amikor legyõztem a Sárkányt.}
{137}{}{Fogom. Kezdjük a tesztet!}
{138}{}{Fogom. Hadd kérdezzek még valamit!}
{139}{}{Hát persze. Viszlát!}
{140}{}{Életre halálra akarsz harcolni, vagy csak leellenõrizni, melyikünk a jobb?}
{141}{}{A végsõkig. Én képes vagyok legyõzni téged.}
{142}{}{Csak teszteljük a képességeinket. Nem akarlak megölni.}
{143}{}{Én sem. Felejtsd el!}
{144}{}{Nagyszerû! Remélem, már megvan a sírhelyed. A Sárkány küldött téged?}
{145}{}{Igen. A Shik nevében jöttem.}
{146}{}{Nem. Azért csinálom, mert utálom a hozzád hasonló söpredéket.}
{147}{}{Szívós vagy, mi? Elõször az embereimmel fogsz harcolni, aztán majd meglátjuk, érdemes vagy-e arra, hogy kiálljak veled.}
{148}{}{-kezdjük-}
{149}{}{Lo Pan vagyok. A Sárkány "esküdt" ellensége. Hogy miért kell neki esküdt ellenség, fogalmam sincs. Ugyanúgy harcolok, mint õ, de szerintem õ nem elég elszánt és hagy másokat is érvényesülni. Azért vagyunk ellenségek, mert ugyanazt a stílust ûzzük, és bármelyikünk is nyer, õ viszi tovább a hagyományt.}
{150}{}{Elég jó vagyok a pusztakezes harcban. Akarsz egy próbát?}
{151}{}{Ez érdekes. Bizonyára gyümölcsözõ. Hadd kérdezzek még valamit!}
{152}{}{Köszönöm. Üdv!}
{153}{}{Lehet, hogy egy söpredék vagyok, de azt sosem fogják rámfogni, hogy nem állok ki a népemért. Mielõtt meghalnál, fájdalmat fogok okozni neked.}
{154}{}{-kész-}
{155}{}{Akkor viszont eszetlen bolond vagy, hogy mások ugráltatnak. Nevetni fogok, amikor meghalsz.}
{156}{}{- védõöltözékben és fegyverrel támadsz -}
{157}{}{- védõöltözék és fegyverek nélkül belépsz a szorítóba, és puszta kézzel harcolsz -}
{158}{}{Jó. Legalább a magad ura vagy. Elég szívósnak érzed magad, hogy védõöltözék és fegyverek nélkül küzdj?}
{159}{}{- védõöltözékben és fegyverrel támadsz -}
{160}{}{- védõöltözék és fegyverek nélkül belépsz a szorítóba, és puszta kézzel harcolsz -}
{161}{}{Beee, birka, beee! Menj vissza a palástba burkolt barátaidhoz! Nincs mit mondanom számodra.}
{162}{}{-kész-}
{163}{}{Nem mondtam volna, hogy a morális aggályaiddal a Sárkányt boldogítsd? Õ majd fogja a kezed. Én nem. Most pedig távozz!}
{164}{}{-kész-}
{165}{}{El kell ismernem, még nálam is jobb küzdõ vagy. Nem akarsz próbát tenni a Sárkánnyal?}
{166}{}{De. Akár most azonnal.}
{167}{}{Ez nem igazán az én harcom.}
{168}{}{Dehogynem, viszont szeretnék még kérdezni ezt-azt.}
{169}{}{Nem, nem így van. Viszont a Sárkány még mindig legyõz engem. Ha van benned gerinc, kiiktatod õt. Mellesleg sosem gondoltam volna, hogy egy lao wai-t ekkora büszkeség feszítsen.}
{170}{}{Jól van. Volna néhány kérdésem.}
{171}{}{Igen, hát persze. Üdv!}
{172}{}{Épp most jöttem vissza, megöltem egy lao wai-t, aki megpróbálta ellopni a titkainkat. A Sárkánnyal karöltve csináltuk és el kell ismernem, egész jól dolgoztunk együtt.}
{173}{}{Nagyszerû! Lenne viszont néhány kérdésem.}
{174}{}{Nagyszerû! Üdv!}
{175}{}{A Sárkány meghalt... Alig hiszem el. Mostantól legalább nem kell, hogy folyton a bosszantó hagyományok határozzák meg minden egyes lépésünket. Köszönet illet.}
{176}{}{Nagyszerû! Kérdeznék.}
{177}{}{Nagyszerû! Üdv!}

{200}{}{Lo Pan detects your advance and you slip by him.}
{201}{}{Nézd, nem szeretem, ha valaki ellopja a dolgaimat. Menj máshova tolvajkodni! Távozz innen!}
{202}{}{Azt mondtam, hogy távozz, nem azt, hogy halj meg! Anyám.}
{203}{}{Már túl vagy a Sárkány tesztjén!}

{204}{}{A mai tréningnek vége. Gyere vissza holnap!}

{205}{}{Khung mester vagyok, az utolsó ellenfeled.}
{206}{}{Imbot vagyok. Készülj!}
{207}{}{Wejungh a nevem. Légy készen!}
{208}{}{Loopal vagyok. Innen nem mész tovább!}
{209}{}{Smitty vagyok. Itt az idõ, hogy elverjen valaki!}
{210}{}{Krall mester vagyok. Most véged!}
{211}{}{HARC!}
{212}{}{Többet kell edzened!}
{213}{}{Készülj!}
{214}{}{Igazi halálig tartó küzdelemben gyõzted le Lo Pant. Valami oknál fogva mintha fényesebben sütne ma a nap.}
{215}{}{Már legyõzted az embereimet. Átmentél a teszten. Készen állsz, hogy megküzdj a Sárkánnyal.}
{216}{}{Már éppen elég jó vagy. Menj, tanulj lõni, vagy akármi...}

#training messages
{217}{}{Kezdjük! Jer utánam!}
{218}{}{Mára elég volt a tréningbõl.}
{219}{}{Jól tanultál.}

{220}{}{Már legyõzted az embereimet. Senki nem akar kiállni veled.}

{221}{}{Segítettél nekem, és még csak nem is tudtál róla. A Sárkány halálával többé nem kell követnem az idejétmúlt hagyományokat.}
{222}{}{Örömömre szolgált. Üdv!}
{223}{}{Nem tesz semmit. Viszlát!}
{224}{}{Nem tesz semmit. Kérdezhetek valamit?}
{225}{}{Üdv! Én kérdezhetni?}

{226}{}{NYERTÉL!}
{227}{}{VESZTETTÉL!}
{228}{}{Következõ ellenfél!}

{229}{}{Hé, nézzétek már, mit találtam!}

{230}{}{Elõször is be kell bizonyítanod, hogy képes vagy megcsinálni. Öt emberemmel fogsz megküzdeni, egyszerre persze csak egyikükkel. Ha legyõzöd õket, jöhet a végsõ megmérettetés.}
{231}{}{Mirõl van szó?}
{232}{}{Tûl nagy gondnak hangzik. Késõbb találkozunk!}
{233}{}{Le kell, hogy gyõzz engem. Mindazonáltal egyik összecsapásnak sem kell életre-halálra menni - az embereim védelmében persze. [gúnyosan mosolyog]}
{234}{}{Fogjunk bele!}
{235}{}{A Sárkánnyal magadnak kell elbánni!}
{236}{}{[Lo Pan végigmér, majd egy gyors ütéssel úgy orrba vág, hogy még reagálni sem tudsz.] Nem vagy elég jó.}
{237}{}{Oké, de kérdezhetek valami mást?}
{238}{}{Remek. Üdv!}