{100}{}{Egy csuklyás Hubologista. Ez itt valahogy különbözik a többitõl.}
{101}{}{Õ BHK-7, a helyettes.}
{102}{}{Ez egy csuklyás Hubologista.}
{103}{}{Õrség! Egy elnyomó! Lekapcsolni!}
{104}{}{Adja elõ gyorsan, mit akar!}
{105}{}{Aaagh! Nu! Nee!}
{106}{}{Hoztam egy levelet BHK-9 számára az ÚKK-ból, a Megvilágosodottól.}
{107}{}{Azért jöttem, hogy beszéljek Crockettel valami páncélzat ügyében.}
{108}{}{Szeretnék körülnézni.}
{109}{}{Érdekelne, hogy esetleg csatlakozzam a maguk szervezetéhez.}
{110}{}{Maga kicsoda?}
{111}{}{Azért jöttem, hogy mindannyiukat megöljem!}
{112}{}{Ah, szegény gyermek. Szeretnéd, ha behangolnánk?}
{113}{}{Eggen!}
{114}{}{Nem!}
{115}{}{Szegény gyermek. Be vagy hangolva, mégsem tudsz rendesen beszélni. Menj csak tovább!}
{116}{}{Köfönet!}
{117}{}{Menj tovább, és keresd Juan-t és Vikkit. Õk majd segítenek. Légy szerencsés, gyermekem!}
{118}{}{Köffönet!}
{119}{}{::megkeményedik a hangja:: Akkor nem látok egyetlen okot sem, amiért be kéne magát ide engednem. Minden jót!}
{120}{}{Héhé!}
{121}{}{Nagyon jó. Mellesleg siessen - õ nagyon elfoglalt ember!}
{122}{}{Oké.}
{123}{}{Ez nem az a hely, ahova csak úgy, ha kedve szottyan az embernek, látogatásokat lehet tenni. Minden jót!}
{124}{}{-kész-}
{125}{}{Kiváló! Menjen csak be, menjen csak be! Beszéljen Juan Cruzzal és Vikki Goldman-el! Õk hírességek ugyan, de szóba állnak magával.}
{126}{}{Kik õk?}
{127}{}{Óh! Hírességek!}
{128}{}{Én BHK-7 vagyok, e komplexum helyettes vezetõje. Mielõtt rákérdezne: BHK annyit tesz, hogy Behangolt Hub Keresõ. Ez azt jelenti, hogy a neurodinjaim hét szintjét már eltávolították a lelkembõl. Ebbõl következik, hogy magánál sokkal megvilágosodottabb vagyok, és közelebb állok a Nagy Kerék tengelyéhez, viszont azt is jelenti, hogy most szépen elmondja nekem, mit is keres itt. De ne kelljen ám várnom!}
{129}{}{Hoztam egy levelet BHK-9 számára az ÚKK-ból, a Megvilágosodottól.}
{130}{}{Azért jöttem, hogy beszéljek Crockettel valami páncélzat ügyében.}
{131}{}{Szeretnék körülnézni.}
{132}{}{Érdekelne, hogy esetleg csatlakozzam a maguk szervezetéhez.}
{133}{}{Azért jöttem, hogy mindannyiukat megöljem.}
{134}{}{New Reno-i filmcsillagok. Meghallották az evangéliumunk mögött húzódó igazságot, és azonnal jöttek megtisztítani a neurodinjaikat.}
{135}{}{Hol találom õket?}
{136}{}{Hagyjuk inkább! Mehetnékem van...}
{137}{}{Az imahelyiségben megtalálja õket, ott mutatják meg az újoncoknak és a Perem Pépeknek, milyen hasznos dolog Hubologistának lenni.}
{138}{}{Hát akkor, hadd menjek hozzájuk!}
{139}{}{Én majd eldöntöm. Nézzük, mibõl élünk!}
{140}{}{Felejtsük el! Megyek is...}
{141}{}{Szóval most már beszélt Juan-nal és Vikkivel. Érdekli tehát, hogy csatlakozzon barátainkhoz a Nagy Kerék nyújtotta megvilágosodás keresésében?}
{142}{}{Ó, igen. Igen, igen, igen.}
{143}{}{Hogyne.}
{144}{}{Most nem. Késõbb visszajöhetek?}
{145}{}{Nem hiszem, hogy ez az én lelkivilágomnak való. Elnézést.}
{146}{}{Francokat! Az idióta szektájuk kiérdemelte, hogy porig égessék!}
{147}{}{::mosolyog:: Nem fogja megbánni. Akár még vezetheti is e komplexumot. Ó... szóval maga ért a fegyverekhez! Volna kedve a Nagy Kerék szolgálatában használni õket?}
{148}{}{Igen.}
{149}{}{Talán késõbb.}
{150}{}{Túl sokat ne várasson minket a válasszal! A megtisztító eljárás megkezdéséig egyre több és több neurodinja szennyezõdhet be.}
{151}{}{Meggondoltam magam. Csatlakozom.}
{152}{}{Elkönyveltem. Késõbb találkozunk.}
{153}{}{Biztonságban elhagyhatja a komplexumot, utazó, de nem ajánlom, hogy visszajöjjön! Ha nem velünk utazik, akkor ellenünk dolgozik, és nem szívesen látnám magát sérülten.}
{154}{}{Kösz, hogy törõdik velem. Viszlát!}
{155}{}{Nem hinném, hogy én sérülnék meg. Minden jót!}
{156}{}{Porig akarsz égetni? PORIG AKARSZ ÉGETNI? ÕRSÉG! MEGÖLNI A HITETLENT!}
{157}{}{-kész-}
{158}{}{Szóval... Elég ideje volt, hogy átgondolja a döntését. Csatlakozik hozzánk?}
{159}{}{Igen.}
{160}{}{Nem.}
{161}{}{Még kell egy kis idõ.}
{162}{}{Nincs több idõ. Hozza meg a döntését, pép!}
{163}{}{Remek, csatlakoznék.}
{164}{}{Hagyjuk ezt! Nem szeretem az erõn alapuló taktikát.}
{165}{}{Az elnyomó Shik egyfolytában vetekednek velünk és a neurodin befolyásoló üzelmeikkel pusztítást hoznak a magunkfajtára. Hisszük, hogyha az Uralkodójukat meggyilkoljuk, észreveszik a saját szemükben a szálkát. Megöli nekünk az Uralkodót?}
{166}{}{Igen, megölöm.}
{167}{}{Nem, a Shik sosem tettek ellenem semmit!}
{168}{}{Talán meggondolja még magát. Tudassa velem, ha így lenne! Nos, újonc, tud valamiben a Hub segíteni magának?}
{169}{}{Igen, egy-két kérdésem még lenne.}
{170}{}{Nem, most nem, köszönöm.}
{171}{}{Gondolt már arra, hogy segítõ kezet nyújt nekünk az elnyomó Shik ellenében? Csillagbéli Atyánk megáldja majd magát, ha részt vesz e keresztes hadjáratban.}
{172}{}{Még mindig nem vagyok benne biztos, hogy szeretném...}
{173}{}{Legyen.}
{174}{}{Talán tudok könnyíteni a problémákkal küzdõ lelkén. Mire van szüksége?}
{175}{}{Hol találhatnék üzemanyagot a Poseidon tankerbe?}
{176}{}{Hol találom a maguk által használt fogalmak jegyzékét?}
{177}{}{Mikor száll fel a hajó?}
{178}{}{Hol van Crocket?}
{179}{}{Semmire, köszönöm. Üdv!}
{180}{}{Ha kész van a feladattal, tudassa velünk!}
{181}{}{Tudatni fogom. Hadd kérdezõsködjek addig is!}
{182}{}{Hogyne! Üdv!}
{183}{}{Eltávolította végre az Uralkodót, az elnyomó szégyenfoltot eme anyagi létezésbõl?}
{184}{}{Nem, még nem távolítottam el.}
{185}{}{Igen, BHK-7. Meghalt.}
{186}{}{A Tanker csavargóinak de facto vezetõje egy "Borz" nevezetû jó nagy darab, egészségtelen Perem Pép. A halálával helyre tesszük õket. Kiiktatja nekünk?}
{187}{}{Éppen kiiktathatom...}
{188}{}{Nem ártott õ nekem semmit. Inkább nem.}
{189}{}{Szóval... meggondolta magát a "Borz" eltávolítása ügyében?}
{190}{}{Megteszem.}
{191}{}{Inkább mégsem...}
{192}{}{Eltávolította ezt a "Borzot"?}
{193}{}{Eddig még nem.}
{194}{}{Igen. Kicsináltam.}
{195}{}{A népe most átöleli a Hub-ot! Minden rendbe jön! Nagyon nagy szolgálatot tett számunkra!}
{196}{}{Köszönöm! Volna még néhány kérdésem.}
{197}{}{Mindent a Kerék számára teszek. Isten önnel.}
{198}{}{Az a helyzet, hogy most magát is kicsinálom szépen...}
{199}{}{Most, hogy a hajó tele van üzemanyaggal, már csak a Nagy és Rettegett BHK-9 szavára várunk, hogy megkezdõdhessék a felemelkedés.}
{200}{}{Hogyne, hogyne... Addig is kérdeznék valamit.}
{201}{}{Köszönöm. Üdv!}
{202}{}{Eltekintve az értékes üzemanyagtól, mely arra kell, hogy kilõjük magunkat a Quetzel bolygón tartózkodó csillagtestvéreink kebelébe, nem jut eszembe egyetlen hely sem. Talán a Shikre tudnék gondolni...}
{203}{}{Ejha. Hadd kérdezzek még, ha nem zavarok vele!}
{204}{}{Igen, lehet.}
{205}{}{Tudom, hogy a Shiknek van egy nagy rakás üzemanyaguk. Esetleg ellophatná tõlük.}
{206}{}{Ez is egy elképzelés... Volna ellenben még néhány kérdésem.}
{207}{}{Esetleg. Köszönöm.}
{208}{}{Használja a Juan és Vikki által adott hololemezt, és olvassa át a szójegyzéket!}
{209}{}{Köszönöm. Még kérdezhetek?}
{210}{}{Köszönöm.}
{211}{}{Amikor BHK-9 számára megérkezik a látomás a Hub-tól, mindannyian elmegyünk és csillagközi dicsõségtõl övezve csatlakozunk hozzá!}
{212}{}{Igen, dícsértessék a Kerék vagy mi... hadd kérdezzek még egy s mást!}
{213}{}{Nagyon informatív. Köszönöm.}
{214}{}{Általában a laborjában tartózkodik és új módszereken munkálkodik, miképpen tehetjük a testünket meg a lelkünket tökéletesebbé.}
{215}{}{Köszönöm. Inkább kérdeznék valami mást!}
{216}{}{Köszönöm.}
{217}{}{Mielõtt igazán közénk tartozna, végre kell hajtanunk magán egy kezdeti zéta szkennelést - be kell, hogy hangoljuk. Készen áll a szkennelésre?}
{218}{}{Nem! Szó nem lehet szkenrõl!}
{219}{}{Hogyne! Csináljuk!}
{220}{}{Szkennelés nélkül nem csatlakozhat. Biztos benne, hogy elutasítja magától?}
{221}{}{Abszolút biztos. Nem akarom, hogy a gépük visszabutítson egy majom szintjére.}
{222}{}{Ah, rendben van, szkenneljen csak!}
{223}{}{Ezennel elimináltuk a legmocskosabb neurodinjait. Mostantól ön BHK-1. Készen áll, hogy csatlakozzon nemes ügyünkhöz?}
{224}{}{Ó, igen.}
{225}{}{Nem. Most nem.}

{226}{}{Elsõ lecke: Ugyebár itt van az örökkévalóság. Az egyik oldalon ott van Quetzel. [ujjával mutat valahova] Itt pedig mi vagyunk. [megintcsak mutat valahova] Nem kell mást csinálnunk, hogy eljussunk oda, csak egyszerûen jó sokat járni.}
{227}{}{Ember, temérdek cipõre lesz szükségünk!}

{228}{}{Gondolkozhatok rajta?}
{229}{}{Már megint maga? Mi az?}
{230}{}{Akar még valamit, hogy csináljak?}
{231}{}{Maga itt nem kívánatos személy. Kérem, menjen el!}