{100}{}{Egy Kapitány-sapkát viselõ egyén.}
{101}{}{You see Captain A. Ron Meyers.}
{102}{}{Ez a szakadt ruhát viselõ punk Kapitány-sapkát visel.}
{103}{}{Mi a fenét akarsz? Addig nem beszélek senkivel, amíg nem a barátom, vagy nem bizonyul jó embernek. Tégy valami jót valamelyik emberemmel, és akkor gyere vissza!}
{104}{}{[DONE]}
{105}{}{Hallottam, mit tettél az emberemmel. Köszönöm neked. Miben segíthetek?}
{106}{}{Te ki lenni?}
{107}{}{Úgy hallottam, te vagy az, aki mindent tud errõl a hajóról.}
{108}{}{Miért hívnak téged a Kapitánynak?}
{109}{}{Hogy lehetne ezt a teknõt mozgásra bírni?}
{110}{}{Semmi.}
{111}{}{Én vagyok a Kapitány, én mûködtetem ezt a hajót. Ha további kérdéseid vannak, keress meg egy Shi-t vagy a Borzot, vagy akárkit! Nincs idõm rád!}
{112}{}{[DONE]}
{113}{}{Ez a hajó egy Poseidon tanker. Olyan technológiával van felszerelve, ami túlélte a háborút. Van benne egy FBK, amely lehetõvé teszi, hogy hozzáférj a navigációs számítógéphez, és van benne egy EBFR jeladó, amely megvédi a Poseidon ágyúitól.}
{114}{}{Honnan tud minderrõl?}
{115}{}{Mi az az EBFR jeladó?}
{116}{}{Hogy lehet mozgásra bírni?}
{117}{}{Kösz. Viszlát!}
{118}{}{Régen az Enklávét szolgáltam. Hamar rájöttem, hogy nem az Egyesült Államokért harcolok, hanem az öreg, gazdag gyökerekért, akik nem akartak megválni a hatalmuktól. Dezertáltam és most sokkal becsületesebb emberek között élek.}
{119}{}{Becsületesebb emberek közt? Ezekre a srácokra gondolsz?}
{120}{}{Pontosan mi az Enklávé?}
{121}{}{Hogy lehetne ezt a teknõt mozgásra bírni?}
{122}{}{Viszlát!}
{123}{}{Azt kérded, hogy lehet elvezetni ezt? Fel kéne tölteni üzemanyaggal. Próbálkozz a Hubologistáknál vagy a Shiknél, és ha minden egyéb rendben van, csak egy gombnyomás. A maradékról a számítógép gondoskodik, ha még mûködik egyáltalán. A hajó szépen elúszik az olajfúró-toronyhoz, és nem fognak rád lõni, mert fel vagy szerelve az EBFR jeladóval. Annyi a dolgod, hogy minden rendben legyen: FBK, mûködõ számítógép, és üzemanyag. Elég könnyû, mi?}
{124}{}{Az, de honnan tudsz te minderrõl?}
{125}{}{Mi az az EBFR jeladó meg az FBK?}
{126}{}{Miféle fúrótoronyról van szó?}
{127}{}{Igen. Viszlát!}
{128}{}{IFF: Identify Friend or Foe. It means that this ship is identified as a friend, so other Poseidon things - like, say, an oil rig - won't fire at you when you come into range. Oh, and a FOB is some sort of Enclave technology that lets you enter a door electronically. You'd probably find one of them at one of their bases or some such place.}
{129}{}{Honnan tud minderrõl?}
{130}{}{Miféle fúrótoronyról van szó?}
{131}{}{Kösz. Viszlát!}
{132}{}{Igen. Ezekkel az emberekkel pontosan tudod, mire számíthatsz. Nem játszanak ki téged. Az Enklávé olyan volt, mint egy csapat hiéna. Semmi perc alatt ellened fordulnak.}
{133}{}{Pontosan mi az Enklávé?}
{134}{}{Hogy jöttél össze velük?}
{135}{}{Az Enklávé a régi idõk maradványa. Ha ezt a teknõt odakormányozod az olajfúró-toronyhoz, magad is rájössz.}
{136}{}{Hogyan tudnám elvezetni?}
{137}{}{Miféle olajfúró-toronyról van szó?}
{138}{}{Elég egyszerûen. Egy szép napon otthagytam a navarrói bázist és ide vettem az irányt. Arra gondoltam, ez az utolsó hely, amit átkutatnának utánam. Nem vagyok én annyira fontos az Enklávé számára, hogy nekiálljanak kerestetni. Kis porszem vagyok csupán.}
{139}{}{Pontosan mi az Enklávé?}
{140}{}{Kösz. Viszlát!}
{141}{}{There's a big Poseidon oil rig left out on the water. That's the final base of the Enclave}
{142}{}{Honnan tud minderrõl?}
{143}{}{Van még valami tudnivaló errõl a fúrótoronyról?}
{144}{}{Kösz. Viszlát!}
{145}{}{Gyorsan terjed a szóbeszéd.}
{146}{}{Értem. Mi egyéb tudható errõl a fúrótoronyról?}
{147}{}{Értem. Viszlát!}
{148}{}{Nem tudok mit mondani. Én navarrói technikus voltam, mezei fúrótorony-kezelõ. Rádión kommunikáltunk velük és ennyiben kimerült a kapcsolatunk.}
{149}{}{Értem. Elmondanád, hogy tudnám ezt a hajót elvezetni?}
{150}{}{Kösz. Viszlát!}
{151}{}{Nagy hibát követtél el, hogy kekeckedtél a Kapitánnyal és a barátaival...}
{152}{}{How do you pilot this rig? Well, I see you already gassed her up. When you've taken care of everything else, just press the button. The computer will take care of the rest, if it's still working. It'll sail right out to the oil rig, and they won't fire at you because you've got the IFF transponder. Just make sure you've got what you need to access everything: FOB, working computer, and fuel. Easy enough, huh?}
{153}{}{Ó, igen. A navigációs számítógépet is mûködésre kell bírnod. Le merném fogadni, hogy egy régi Menedékben lehet még olyan alkatrészeket találni.}
{154}{}{Jó, hogy újra látlak. Mire van szükséged?}
{155}{}{, and unless I miss my bet, that's where your friends are, too.}
{156}{}{ vagyok.}
