{100}{}{Egy zaklatott kinézetû, kopasz férfit látsz.}
{101}{}{Õ Harry, a rakétákért felelõs illetékes.}
{102}{}{Egy zaklatott kinézetû, kopasz férfit látsz.}
{103}{}{Aijjééé! A megvilágosodás ellenségei! Segítség! Õrség!}

{107}{}{Hé! Nyers Pép! Ki maga? Mit csinál itt?}
{108}{}{Döh?}
{109}{}{Hoztam egy levelt BHK-9 számára. Hova kell vinnem?}
{110}{}{A nevem}
{111}{}{Semmi köze hozzá!}
{112}{}{Szeretnék csatlakozni a Hubologistákhoz.}
{113}{}{Ki maga és mit keres itt?}
{114}{}{Semmit. Üdv!}
{115}{}{Nagyszerû, egy elmebeteg! Nézd, öregem, menj csak le azon a lépcsõn, ott talán behangolhatják a neurodinjaidat, hogy hasznos emberré válhass. Most azonban, hagyj békén, dolgom van! Eridj!}
{116}{}{Rendicsekk!}
{117}{}{Menjen le a lépcsõn! Mutassa meg BHK-7-nek, aki a kapuõri teendõket látja el, majd elveszi vagy elküldi magát BHK-9-hez. Most akkor visszatérhetek a munkámhoz, pép?}
{118}{}{Hogyne.}
{119}{}{Maga nem tartozik közénk, ezért semmi joga itt tartózkodni! Hacsak nem akar csatlakozni hozzánk - mely igényérõl tájékoztatnia kell az õrhelyen álló BHK-7 elvtársunkat. Tehát vagy lemegy a lépcsõn, vagy sürgõsen távozik innen!}
{120}{}{Értem, értem. Nem kell felkapnia a vizet!}
{121}{}{Az a helyzet, hogy igenis van közöm hozzá. Ez az én hajóm, ezek az én õreim... szóval ki is maga, és mit csinál itt?}
{122}{}{A nevem}
{123}{}{Semmi köze hozzá!}
{124}{}{Szeretnék csatlakozni a Hubologistákhoz.}
{125}{}{Ki maga és mit keres itt?}
{126}{}{Semmit. Üdv!}
{127}{}{Harry vagyok, a fõ rakétatechnikus.}
{128}{}{A nevem}
{129}{}{Semmi köze hozzá!}
{130}{}{Szeretnék csatlakozni a Hubologistákhoz.}
{131}{}{Semmit. Üdv!}
{132}{}{Nem akar együttmûködni, mi? Õrség! Öljék meg a behatolót!}
{133}{}{Az õrei mind halott emberek.}
{134}{}{Menjen le azon a liften, és beszéljen BHK-7-el az õrhelyen. Megfelelõen el fogja igazítani.}
{135}{}{Köszönöm. Viszlát!}

{170}{}{Segítségre van szükségem, gyermekem. Tud nekem segíteni??}
{171}{}{Még mindig segítségre van szükségem, gyermekem. Tud nekem segíteni??}
{172}{}{Maga kicsoda?}
{173}{}{Mit csinál itt?}
{174}{}{Megszereztem a tervek másolatát a Shiktõl.}
{175}{}{Megvannak a gépmadár tervei.}
{176}{}{A gépmadár tervei a Shiknél vannak.}
{177}{}{Mit tehetek magáért?}
{178}{}{Felejtse el! Üdv!}
{179}{}{Harry vagyok, BHK-5, a rakétahajóval megbízott csillagtestvér. A hajót arra fogjuk használni, hogy eljussunk a Quetzel-re.}
{180}{}{Kérdezhetek valami mást?}
{181}{}{Fogom. Üdv!}
{182}{}{A feladatom az, hogy felkészítsem a hajót a Csillagbéli Atyánkhoz való utazásra. Közel már a pillanat.}
{183}{}{Kérdezhetek valami mást?}
{184}{}{Fogom. Viszlát!}
{185}{}{Magánál vannak a tervek? Kiváló! Most már csak üzemanyagra van szükségünk! A Shiknek van egy csomó. Tegye lehetõvé, hogy egy része eljusson hozzánk. Legyen szerencséje, újonc!}
{186}{}{-kész-}
{187}{}{Akkor menjen és ne késlekedjen, jó? Most, ha megbocsát, elvtársam - folytatnom kell a hajó felkészítését epikus utazására.}
{188}{}{Megvannak a gépmadár tervei.}
{189}{}{Hogyne.}
{190}{}{Végre minden megvan a nagy utazáshoz! Kiváló! Most már csak BHK-9 szavára várunk - és biztos vagyok, hogy õ azt szeretné, ha maga velünk jönne. Menjen, intézze el minden ügyét, aztán jöjjön vissza, hogy együtt csatlakozhassunk Csillagbéli Atyánkhoz!}
{191}{}{Akkor viszlát!}
{192}{}{Elõször szükségünk van bizonyos gépmadár tervekre, hogy egyenesbe jöjjünk az aerodinamikai dolgokkal. Ha úgy gondolja, hogy képes ezt megtenni, nézzen be a Shikhez, vagy menjen el a régi navarrói bázisra!}
{193}{}{Emlékeztetõnek: az a feladata, hogy megszerezze a gépmadár terveit! Akár a Shiktõl, akár a régi navarrói bázisról.}
{194}{}{A gépmadár terveit eddig senkinek nem sikerült megszerezni a Shiktõl vagy a navarrói régi bázisról. Meggondolta magát, és segít nekünk?}
{195}{}{Emlékezzen, újonc! A tervek a gyûlölt Shiknél vannak.}
{196}{}{Megvannak a gépmadár tervei.}
{197}{}{Felejtse el!}
{198}{}{Oké, segítek.}
{199}{}{Tudja, mi kell nekünk? Üzemanyag. Egy rakással. A Shiknek van belõle. Járjon utána, tud-e szerezni tõlük!}
{200}{}{Emlékezetõnek: üzemanyagot kell szereznie a nagy ûrhajónkba!}
{201}{}{Ó, persze. Üdv!}

{161}{}{. Csak körbenézek.}
{162}{}{. Csak körbenézek.}
{163}{}{. Csak körbenézek.}