{100}{}{A nõ arcát aggodalom torzítja el.}
{101}{}{Suze.}
{102}{}{A nõ arcát aggodalom torzítja el.}
{103}{}{Jajjajj! Segítség!}
{104}{}{Ments meg! Légyszi!}
{105}{}{Ezek meg akarnak ölni!}
{106}{}{Légyszi! Ezek meg akarnak ölni engem!}
{107}{}{Állítsd meg õket! Jajjajjajj!}
{108}{}{A Borz küldött téged? Tudtam, hogy segíteni fog. Úgy megkönnyebbültem.}
{109}{}{Aagggh.}
{110}{}{Mit csináltál idelenn?}
{111}{}{Igen. Gyere utánam!}
{112}{}{Ó, szegénykém. A sugárzás meg a pusztaság nem egy leányálom, mi? Remélem, valaki segít rajtad.}
{113}{}{Tudom, hogy hülyeséget csináltam. Kiváncsiságból nekiálltam kutakodni, mert a Borz számítógépezett. Lementem a lépcsõn és eltévedtem. Semmi perc alatt körbevettek a szörnyek. Nagyon jó, hogy jöttél.}
{114}{}{Volna még kérdésem, ha nem baj.}
{115}{}{Igen, az. Találtál valami érdekeset?}
{116}{}{Igen, az... Na, haladjunk...}
{117}{}{Ugyebár rátaláltam arra a helyre, ahol meghúztam magam. Ezenkívül találtam egy helyiséget, ami úgy nézett ki, mint valami üzemanyagtöltõ állomás. A szörnyek miatt nem jutottam messzire.}
{118}{}{Volna még kérdésem, ha nem baj.}
{119}{}{Honnan való vagy?}
{120}{}{Nagyszerû! Most elég lesz ennyi.}
{121}{}{Egy Csontteleptõl délre fekvõ helyrõl származom, délre az Izzástól. Nincs messze onnan a tenger. Régen óvónõ voltam, de a gyerekek mind átmutálódtak szörnyekké.}
{122}{}{Volna még kérdésem, ha nem baj.}
{123}{}{Hogy találkoztál a Borzzal?}
{124}{}{Elbûvölõ. Most elég lesz ennyi.}
{125}{}{A srác lejött délre és felbukkant abban a klubban, ahova én is jártam. Szóval amikor beütött a költözés ideje, úgy gondoltam, jó hely lesz ez itt majd kettõnknek.}
{126}{}{Volna még kérdésem, ha nem baj.}
{127}{}{Ez minden. Köszi.}
{128}{}{Megmentetted az életem. Bármilyen kérdésedre válaszolok.}
{129}{}{Jaaaaa.}
{130}{}{Mit csináltál odalenn?}
{131}{}{Találtál valami érdekeset?}
{132}{}{Honnan való vagy?}
{133}{}{Hogy találkoztál a Borzzal?}
{134}{}{Most nincs kérdésem. Szia.}
{135}{}{Ó, istenem... a Borz meghalt ... nem tudom, most mit csinálok... Nincs itt egyetlen barátom se... az egész családom elpusztult... ó, istenem...}
{136}{}{Köszönök mindent. Megyek, megkeresem a Borzot.}