{100}{}{Számítógép-terminál.}
{101}{}{Vegyészeti munkaállomás.}
{102}{}{Számítógépes munkaállomás.}
{103}{}{Üdvözöljük! Kérem, adja meg a jelszavát, hogy ellenõrizhessük a személyazonosságát!}
{104}{}{? Én nem érteni nagy szavak.}
{105}{}{TIUASPO-Lo-Shi-S12908}
{106}{}{::meghekkeled a számítógépet::}
{107}{}{Kilépés.}
{108}{}{Vegyészeti adatbázis: -Üzemanyag és származékok- -Polimerek-}
{109}{}{Üzemanyag és származékok.}
{110}{}{Polimerek.}
{111}{}{Munkaállomás deaktiválása.}
{112}{}{Kilépés.}
{113}{}{Kérem, beszéljen a rendszergazdával! Viszlát!}
{114}{}{::meghekkeled a számítógépet::}
{115}{}{::távozol::}
{116}{}{Behatolót érzékeltem. Lekapcsolás. Legyen jó napja!}
{117}{}{-kész-}
{118}{}{(Miután átvizsgálsz egy hatalmas vegyi képleteket és laborfeljegyzéseket felvonultató adathalmazt, arra a következtetésre jutsz, hogy a Shik növényi kivonatokból és tengeri herkentyûkbõl készítettek üzemanyagot. Evidens számodra, hogy rákapcsolódtak a korábban használatos vezetékekre. Így képesek a lehetõ legjobban teríteni az általuk elõállított üzemanyagot.)}
{119}{}{(Átvizsgálsz egy hatalmas vegyi képleteket és laborfeljegyzéseket felvonultató adathalmazt. Nem sok lövésed van róla, hogy ez a sok adat mit is jelent.)}
{120}{}{Üzemanyag átirányítása a Poseidon tankerbe.}
{121}{}{Üzemanyag átirányítása a Hubologistáknak.}
{122}{}{Vissza.}
{123}{}{(Miután temérdek ábrán és technikai értekezésen átgázoltál, felfedezed, hogy a Shik egy új típusó polimer alapú harci páncél kifejlesztésén dolgoznak, mely mind a tûznek, mind a lövedékeknek ellenáll. A befejezéstõl még mindig évekre tart. Mindemellett említéseket olvasol egy bizonyos új fegyverzetrõl, és gyártási lehetõségekrõl. A Shik szemlátomást el vannak látva tervekkel a jövõt illetõen.)}
{124}{}{Vissza.}
{125}{}{Az üzemanyag átirányítva a kért helyre. Tároló = Üres. Program bezárása.}
{126}{}{-kész-}
{127}{}{Az üzemanyag átirányítva a kért helyre. Tároló = Üres. Program bezárása.}
{128}{}{-kész-}
{129}{}{Állomás deaktiválva.}
{130}{}{Állomás aktiválása.}
{131}{}{-kilépés-}
{132}{}{[Véletlenszerû próbálkozásodat siker koronázta... benn vagy a gépben!]}
{133}{}{-tovább-}

{134}{}{A számítógép semmilyen inputra nem reagál.}
{135}{}{Nem találsz rajta semmilyen helyet, ahol ezt alkalmazhatnád.}

{136}{}{::megpróbálod kitalálni a jelszót::}
{137}{}{Üzemanyag csõvezetékbe juttatása.}
{138}{}{Válasszon célpontot!}