#{100}{}{Ez egy igen "izmos" számítógép.} //This is for the computer object itself
#{101}{}{Õ az Uralkodó Számítógép.}
#{102}{}{Ez egy nagy, duruzsoló, teljesen mûködõképes számítógép, melynek alsó fertályára az "Uralkodó v8.8" cimkét ragasztották.}
{100}{}{Ez egy számítógép-terminál.}
{101}{}{Õ az Uralkodó Számítógép-terminál.}
{102}{}{A számítógép interfészeként egy beépített érintõs képernyõ szolgál. Az oldalán ez áll: "Uralkodó v8.8" számítógép-terminál.}
{103}{}{Üdvözöljük. Kérem, adja meg a jelszavát, hogy ellenõrizhessem a személyazonosságát!}
{104}{}{::összevissza beírsz valamit::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{::meghekkeled a számítógépet::}
{109}{}{Kilépés.}
{110}{}{Személyazonosság ellenõrizve.}
{111}{}{Mely funkciót szeretné elérni?}
{112}{}{Diagnosztika.}
{113}{}{Adatbázis.}
{114}{}{Elõrejelzés.}
{115}{}{Semelyiket.}
{116}{}{Kérem, beszéljen a rendszergazdával! Viszlát!}
{117}{}{::meghekkeled a számítógépet::}
{118}{}{::távozol::}
{119}{}{Behatolót érzékeltem. Lekapcsolás. Legyen jó napja!}
{120}{}{-kész-}
{121}{}{Diagnosztikai funkciók?}
{122}{}{Hálózati szken}
{123}{}{Merevlemez formázása}
{124}{}{Merevlemez integritásának ellenõrzése.}
{125}{}{Vissza.}
{126}{}{Melyik adatbázishoz szeretne hozzáférni?}
{127}{}{Biológia.}
{128}{}{Vegyészet.}
{129}{}{Fizika.}
{130}{}{Történelem.}
{131}{}{Vissza.}
{132}{}{A Shi város gyermekei veszélyben vannak. 50% esély van rá, hogy gyilkos jár köztük.}
{133}{}{A Shi város egyre nagyobb veszélyben. 75% esély van rá, hogy baj éri a lakosokat.}
{134}{}{A Hubologista ûrhajó-kilövésnek 95% esélye van, hogy csõdöt mond. Tényezõk: Nincs üzemanyag, elégtelen tömítõgyûrû, gyenge vezetés, kezdeményezés hiánya.}
{135}{}{15% esély van arra, hogy a "Kiválasztott" sikeresen végrehajtja a küldetését.}
{136}{}{Az adatok azt jelzik, hogy az "Enklávé" sokkal erõsebb, mint azt korábban hittük. Ne közelítse meg õket!}
{137}{}{Annak az esélye, hogy egy tengeralattjáró feltûnik ebben a játékban: 0%}
{138}{}{A tanker csavargóinak 0% százalék esélye van, hogy a raktérben külsõ segítség nélkül megszüntessék a szörny-járást. Segítségnyújtás testhezállóságának kiszámítása folyamatban.}
{139}{}{Adat: A Poseidon Olaj Tanker alkalmatlan az útra. Több adatra van szükség.}
{140}{}{Nem feldolgozható. Több adatra van szükség.}
{141}{}{-tovább-}
{142}{}{Vissza.}
{143}{}{Biológia állomás: Aktív}
{144}{}{Biológia állomás: Inaktív}
{145}{}{Vegyészeti állomás: Aktív}
{146}{}{Vegyészeti állomás: Inaktív}
{147}{}{Fizika állomás: Aktív}
{148}{}{Fizika állomás: Inaktív}
{149}{}{Biológiai állomás deaktiválása.}
{150}{}{Vegyészeti állomás deaktiválása.}
{151}{}{Fizika állomás deaktiválása.}
{152}{}{Hozzáférés a biológiai állomáshoz.}
{153}{}{Hozzáférés a vegyészeti állomáshoz.}
{154}{}{Hozzáférés a fizika állomáshoz.}
{155}{}{Biológiai állomás aktiválása.}
{156}{}{Vegyészeti állomás aktiválása.}
{157}{}{Fizika állomás aktiválása.}
{158}{}{Vissza.}
{159}{}{Meghajtó formázása: Minden adat megsemmisül. Akarja folytatni?}
{160}{}{Igen.}
{161}{}{Nem.}
{162}{}{A rendszer funkcionális integritása 92%. Az Uralkodó-Számítógép páncélozott magja 100%. Az adat integritása 100%. Az elõrejelzõ egység enyhe feszültségingadozásoktól szenved - elõrelátható javítási idõ 6 nap. Elõrejelzés 15%-os készültségben.}
{163}{}{Vissza.}
{164}{}{Biztos, hogy le akarja formázni ezt az egységet? A folyamat visszafordíthatatlan.}
{165}{}{Igen.}
{166}{}{Nem.}
{167}{}{Formázás... formázás... formázás kész. Az újraindítás elõtt teljes telepítés szükséges. Lekapcsolás... lekapcsolás... kész...}
{168}{}{-kész-}
{169}{}{Megtalálandó adat: - Botanika program  - Genetikai program - Xeno program}
{170}{}{Botanika program.}
{171}{}{Genetikai program.}
{172}{}{Xeno program.}
{173}{}{Vissza.}
{174}{}{(Körülbelül húsz perc elteltével az alábbiakat találod: A növények sugárzás-ellenállásának kezdeti eredményei nem túl kecsegtetõek. A Dr. Sheng által kifejlesztett sugárzásálló növények kellemetlen mellékhatással bírnak, túlságosan veszélyesek. Shen ragaszkodik hozzá, hogy folytassák a megadott irányvonalat és vessék be a genetikai vívmányokat is.)}
{175}{}{Genetikai program.}
{176}{}{Xeno program.}
{177}{}{Vissza.}
{178}{}{(Körülbelül húsz perc múltán összerakod a szerzett információt: A FEV vírus alapjait felhasználva Dr. Long Wang sikeresen hozott létre mutáns katonákat. Egy szérumot is készített hozzá, amely érdekes eredményeket produkált egyes rágcsálókban. Beadta magának, mire eltûnt egy bugyborékoló tócsában. Ezt követõen Dr. Sheng hírzárlatot rendelt el. Dr. Long halálával a stafétabotot Dr. Sheng vette át, aki minden tudását a sugárzásálló növények kutatására koncentrálta.)}
{179}{}{Botanika program.}
{180}{}{Xeno program.}
{181}{}{Vissza.}
{182}{}{"Az alany, amelyen oly sok ígéretes kísérletet szerettünk volna végrehajtani, eltûnt. Vagy megsemmisült, vagy ellopták a Hubologisták. A további adatszerzés nem bizonyult gyümölcsözõnek. Amíg nem tudunk újabb példányokat keríteni, ezt az adatbázist elérhetetlenné teszem." - Dr. Sheng}
{183}{}{Botanika program.}
{184}{}{Genetikai program.}
{185}{}{Vissza.}
{186}{}{Vegyészeti adatbázis: Üzemanyag és származékok - Polimerek}
{187}{}{Üzemanyag és származékok.}
{188}{}{Polimerek}
{189}{}{Vissza.}
{190}{}{(Miután átvizsgálsz egy hatalmas vegyi képleteket és laborfeljegyzéseket felvonultató adathalmazt, arra a következtetésre jutsz, hogy a Shik növényi kivonatokból és tengeri herkentyûkbõl készítettek üzemanyagot. Evidens számodra, hogy rákapcsolódtak a korábban használatos vezetékekre. Így képesek a lehetõ legjobban teríteni az általuk elõállított üzemanyagot.)}
{191}{}{(Átvizsgálsz egy hatalmas vegyi képleteket és laborfeljegyzéseket felvonultató adathalmazt. Nem sok lövésed van róla, hogy ez a sok adat mit is jelent.)}
{192}{}{Üzemanyag átirányítása a Poseidon tankerbe.}
{193}{}{Üzemanyag átirányítása a Hubologistáknak.}
{194}{}{Vissza.}
{195}{}{(Miután temérdek ábrán és technikai értekezésen átgázoltál, felfedezed, hogy a Shik egy új típusó polimer alapú harci páncél kifejlesztésén dolgoznak, mely mind a tûznek, mind a lövedékeknek ellenáll. A befejezéstõl még mindig évekre tart. Mindemellett említéseket olvasol egy bizonyos új fegyverzetrõl, és gyártási lehetõségekrõl. A Shik szemlátomást el vannak látva tervekkel a jövõt illetõen.)}
{196}{}{Vissza.}
{197}{}{Az üzemanyag átirányítva a kért helyre. Tároló = Üres. Program bezárása.}
{198}{}{-kész-}
{199}{}{Az üzemanyag átirányítva a kért helyre. Tároló = Üres. Program bezárása.}
{200}{}{-kész-}
{201}{}{Fizika adatbázis: Felfedezés - Teória}
{202}{}{Felfedezés}
{203}{}{Teória}
{204}{}{Vissza.}
{205}{}{"A gépmadár terveinek közelmúltbeli megszerzésével hatalmas lépést tettünk egy repülõ jármû gyakorlati megvalósítása felé. Az év végére várjuk a mûködõ prototípus elkészülését, két éven belül pedig megkezdõdhet a tömeggyártás." - Dr. Wong}
{206}{}{::tervek másolása:: Vissza.}
{207}{}{Vissza.}
{208}{}{"Még mindig dolgozunk egy levegõben közlekedõ jármû használható modelljén. Az eddig elkészült tervek egyike sem bizonyult biztonságosnak, aerodinamikusnak. Talán ha hozzáférhetnénk az õsök terveihez..." - Dr. Wong}
{209}{}{Vissza.}
{210}{}{(Miután keresztülrágtad magad a bemutatkozáson és a matematikán, felfedezed, hogy a Shik, az õsök ûrutazási teóriáit alapul véve, újra nukleáris energia kifejlesztésén munkálkodnak. Ezzel fityiszt mutatnak a Hubologistáknak és megzabolázzák a nap, a szél és a tenger energiáját. Legalábbis a jegyzetek tanúsága szerint.)}
{211}{}{Vissza.}
{212}{}{Állomás aktiválva.}
{213}{}{Vissza.}
{214}{}{A számítógép-terminálnak nemigen van interfésze ilyesmihez.}
{215}{}{A számítógép-terminál nem mûködik.}

{216}{}{Ellenséges beavatkozás a rendszerben! Támadási parancs érvényesítve!}
{217}{}{Megtámadni a behatolót!}
{218}{}{Itt az idõ, hogy megfizess a tetteidért, lao wai!}
{219}{}{Áruló van a sorainkban!}

{220}{}{Geo-Lokáció.}
{221}{}{Mit szeretne lokalizálni?}
{222}{}{A falubelieimet.}
{223}{}{97% számszerûsített esély - a falusiak az Enklávé komplexum jelenlegi koordinátáján találhatók.}