{100}{}{PoseidoNet számítógép.}
{101}{}{PoseidoNet számítógép.}
{102}{}{PoseidoNet számítógép.}


{103}{}{::pittyegés:: A terminál meghibásodott. NavKomp telepítés szükséges. ::pittyegés::}
{104}{}{-kész-}
{105}{}{Üdvözöljük a PoseidoNeten! Ez a terminál csak a POT Valdez tankhajó és a dokkoló egység közötti átvitelre alkalmas. Várom a parancsát...}
{106}{}{Induljunk!}
{107}{}{Státusz ellenõrzése.}
{108}{}{Kilépés}
{109}{}{-Üzemanyag tartály: Üres- -Raktér: Üres- -Navigációs Számítógép: Nem mûködik- -Dokkoló kötél: Kivetve-}
{110}{}{-vissza-}
{111}{}{Kilépés.}
{112}{}{-Üzemanyag tartály: Teli- -Raktér: Üres- -Navigációs Számítógép: Nem mûködik- -Dokkoló kötél: Kivetve-}
{113}{}{-vissza-}
{114}{}{Kilépés}
{115}{}{HIBA: Az üzemanyagtartály üres.}
{116}{}{HIBA: A Navigációs Számítógép nem mûködik.}

{117}{}{-Üzemanyag tartály: Üres- -Raktér: Üres- -Navigációs Számítógép: Mûködik- -Dokkoló kötél: Kivetve-}
{118}{}{-Üzemanyag tartály: Teli- -Raktér: Üres- -Navigációs Számítógép: Mûködik- -Dokkoló kötél: Kivetve-}

{119}{}{PoseidoNet Navigációs számítógép.}

{129}{}{[Sietve átfutsz a kidokkolási procedúrán, mire a hajó leválik a dokkról...]}
{130}{}{-kész-}
{131}{}{A Navigációs számítógép várja a parancsokat.}