# Dialog Editor last position: 162
{100}{}{Ez a vakondpatkány szokatlanul nagyra nõtt.}
{101}{}{Õ az AGY.}
{102}{}{Ez itt egy jókora, albínó vakondpatkány. Az agykoponyája rendesen megnõtt, és bizony szokatlanul intelligensnek látszik.}
{110}{}{Sokan jönnek hozzám a fajtádból, de te mindegyiken túlteszel az ostobaságban. Most pedig meghalsz!}
{120}{}{Nem tudom, hogy vetõdtél ide, de ugyanarra kéne távoznod is.}
{121}{}{Nincs idõm az oktalanságaidra. Nagyratörõ terveim vannak a világ elfoglalását illetõen. Ne is lássalak!}
{122}{}{Ne zavarj! Nem akarom még egyszer mondani!}
{123}{}{Na, jó! Zomak, öldd meg!}
{130}{}{Közel a Megújhodás. Sajnos egy tapodtat sem jutunk elõrébb, ha nem javítod meg az atomreaktorunkat. (saját magának) Ezek az emberek... annyira kiábrándítóak.}
{131}{}{Javítsam meg az atomreaktort?}
{132}{}{Hát persze, mi sem egyszerûbb. Most viszont mennem kell. Viszlát!}
{140}{}{Kiszagoltam, hogy a talizmánjaink egyikét viseled, de nem emlékszem, hogy kaptál volna tõlünk egyet is.}
{141}{}{Találtam.}
{142}{}{Hát... valszeg kiesett a fejedbõl.}
{143}{}{Ez csak az arcszeszem illata. Old Spájz -- jó illata van?}
{144}{}{Megöltem az egyik talpnyalódat, és a még ki nem hûlt hullájáról egyszerûen magamhoz vettem.}
{150}{}{Készen állsz, hogy közénk tartozz?}
{151}{}{Mi az hogy! Késznek születtem. Hol kell beiratkozni?}
{152}{}{Úgy érted, hogy óriási patkány legyen belõlem?}
{153}{}{Nem akarok semmilyen formában olyan lenni, mint ti.}
{154}{}{Most azt kérdezed magatól: kik is ezek valójában?}
{160}{}{A túlélés érdekében mind Gekkó, mind Menedékváros együttmûködést kell, hogy tanúsítson. A fejlõdés miatt Menedékvárosnak kell az áram, amit a mi atomreaktorunk termel, nekünk viszont az õ gyógyászati technológiájukra van égetõ szükségünk. Ha nem kooperálunk, mindkét város megreked a jelenlegi szinten. Menedékvárosnak segítenie kell, hogy az erõmûvünk helyre jöjjön.}
{161}{}{Mégis hogy akarjátok rávenni õket az együttmûködésre?}
{170}{}{A zsenialitásom elismeréseképp engem egyszerûen csak Agynak neveznek. Gekkóban nem sokminden kerüli el a figyelmemet.}
{171}{}{De hát te csak egy jól megtermett patkány vagy.}
{172}{}{Mintha mondtál volna valamit a hozzátok való csatlakozásról...}
{180}{}{Nem érdekel, honnan szerezted. A fontos kérdés az, hogy akarsz-e közénk állni és szívvel-lélekkel viselni.}
{181}{}{Közétek állni? Ezt hogy értsem?}
{182}{}{Inkább a ketreceteket takarítanám mintsem, hogy közétek álljak.}
{190}{}{Nos, világhódító terveim részeként szeretném ghoul barátaimat megjutalmazni. Vissza akarom nekik adni az emberi mivoltukat.}
{191}{}{És ezt mégis hogy akarod véghezvinni?}
{200}{}{Ha Gekkót és Menedékvárost a saját vezetésem alatt egyesítettem, kiadom majd parancsba a menedékvárosi kutatólaboratóriumoknak, hogy találják meg az embereimet ghoullá változtató sugárzás visszafordításának módját.}
{201}{}{Ez ígéretesen hangzik.}
{210}{}{Az Ankh az élet szimbóluma. Ha átadom neked e talizmánt, rögvest közénk tartozol. Bajtársaid sokkal szívesebben segítenek neked majd a Megújhodáshoz vezetõ rögös úton. Vigyázz azonban, kinek mutatod meg.}
{211}{}{Készen állsz, hogy elfogadd a Megújhodást és viseld az Ankh talizmánt?}
{212}{}{Rendben, jöhet az a talizmán.}
{213}{}{Eszembe nincs megújhodni. Úgy szeretem magam, ahogy vagyok. Tartsd meg a talizmánodat!}
{214}{}{Megújhodás? Mit akar ez jelenteni?}
{220}{}{A reaktorunk megsemmisítésével azok a Menedékvárosbeli barmok aláírták saját halálos ítéletüket.}
{221}{}{Most kénytelen leszek más módot kieszelni, hogy átvegyem a világuralmat. Na, lódulj!}
{222}{}{Elég volt az ügyetlenkedésedbõl! Zomak, nyírd ki ezt a tökkelütöttet!}
{230}{}{A reaktor megjavítása jelentõs tett volt, de nem torpanhatunk meg ennél a pontnál. Gekkó és Menedékváros túlélése érdekében még egy lépésre van szükség.}
{231}{}{Hogyhogy még egy lépésre?}
{232}{}{Hirtelenjében nem te lettél a mindenben illetékes polgár?}
{233}{}{Szerintem máris épp eleget tettem. Na, viszlát!}
{234}{}{Azt nem értem, hogy egy óriáspatkányt miért foglalkoztat ennyire ez a dolog?}
{240}{}{Jó munkát végeztél. Menedékváros és Gekkó immár joggal örvendezhet. Most, hogy a reaktorunk teljes kapacitással mûködik, a világuralmi terveim lassan beérnek. Most távozhatsz. Dolgom van.}
{241}{}{Hát abban biztos lehetsz, hogy nem érted tettem. Volt szerencsém...}
{242}{}{Nem kis tervek egy ilyen balettpatkánytól :). Na, légy jó.}
{250}{}{Nos, a reaktor ugyan mûködik, de korántsem teljes kapacitással. Be kéne vetnünk Menedékváros központi számítógépét, hogy diagnózist készítsünk a reaktorról.}
{251}{}{Ah, szóval a központi számítógép... Biztos vagyok benne, hogy az ottaniakhoz hasonló nyílt gondolkodású emberek boldogan segítenének egy óriási, mutáns patkánynak és egy ghouloktól hemzsegõ városnak.}
{252}{}{Szerinted hogy lehetne ezt véghezvinni?}
{260}{}{Illetékes polgár? Akár így is mondhatjuk. A világuralom megragadásához meg kell bizonyosodnom, hogy egyáltalán érdemes-e törnöm magam érte. Gekkó és Menedékváros segítségével erõs áramtermelõ központot akarok létesíteni.}
{261}{}{Egy patkány, mint a világ ura?}
{270}{}{Nos, annak ellenére, hogy megvan a saját véleményed egy rágcsáló világuralmát illetõen, az általam kiötlött terv Gekkó és Menedékváros sokezer lakójának jelentene boldogulást. Lehet, hogy hidegen hagy a személyem és a törekvéseim, de az eredmény megéri a fáradságot.}
{271}{}{Mondj valamit arról a következõ lépésrõl, talán törhetném rajta a fejem.}
{272}{}{A hideg kiráz a gondolatától, hogy bizonyos fokig már eddig is segítettem rajtad. Most jött el tehát az idõ, hogy sürgõsen távozzak. Viszlát!}
{280}{}{Szerintem nem fognak ellenkezni, ha bebizonyítod, milyen sok hasznuk származik belõle. Készítettünk egy gazdálkodási jelentést, amely igazolja, hogy Gekkó atomerõmûvének optimalizálása révén Menedékváros csak jól járhat. Küldetésed részleteit rögvest tudatom Gekkóbeli követõimmel.}
{281}{}{Ha képes vagy bebizonyítani nekik, milyen jól járnak, egy hidroelektromos magnetoszféra szabályzót kapsz tõlük. Elõkészítettem egy gazdálkodási jelentést, amely részletesen ecseteli, hogy Gekkó atomerõmûvének megjavítása milyen elsõrangú hatással lesz Menedékvárosra. Gekkóbeli követõim mind tudni fognak küldetésedrõl.}
{282}{}{Ez remek, de ki az a személy Menedékvárosban, aki egyáltalán kezébe venné ezt a dokumentumot?}
{283}{}{Az erõmûben van egy vén trotli, egy büdösbogár, úgy hívják Festus. Beszélj vele, hátha megerõlteti azt a tök fejét és kiráncigál belõle néhány használható információt. Lehet, hogy tudja az erõmû optimalizálásának részleteit. Gekkóbeli társaim mind tudni fognak küldetésedrõl.}
{284}{}{Ez használható ötletnek tûnik. Késõbb találkozunk.}
{290}{}{Úgy vélem McClure az egyetlen menedékvárosi tanácstag, akinek elég esze van, hogy elõítéletek nélkül dönthessen. Õ biztosan segít majd megszerezni, amire szükséged van.}
{291}{}{Nincs az az isten, hogy én a te futárod legyek!}
{292}{}{Hát szerintem megér egy próbát. Hol juthatok a lemezhez?}
{300}{}{Fel kell menned a felszínre egyenesen a roncstelepre. Keress egy Gordon nevû ghoult. Nála van az említett Gazdálkodási Adatlemez. A talizmán nálad lesz, tehát nem lehet kétsége afelõl, kinek adja.}
{301}{}{Miféle talizmán?}
{310}{}{Egészen biztos vagy benne, hogy a két város lakosságát lassú halálra akarod ítélni?}
{311}{}{Lehet, hogy nem jó ötlet. Rendben, mondd meg, hogy jutok a lemezhez.}
{312}{}{Inkább a lassú halál, minthogy egy patkány uralkodjon a világon. Na, én leléptem.}
{320}{}{[szimatol] Hmmm, érzem rajtad a Sajtos Pufi összetéveszthetetlen illatát. Egészen véletlenül nincs nálad egy plusz adag? Sajnos a Sajtos Pufi a gyengém.}
{321}{}{Hmm... nincs. Egy deka Sajtos Pufi sincs nálam.}
{322}{}{Igazság szerint, akár adhatnék is egy kis Sajtos Pufit.}
{330}{}{Most már közénk tartozol. Hamarosan átveszem a világuralmat és mindannyian beteljesültök a Megújhodásban.}
{331}{}{Hogyne-hogyne. Nem kétlem.}
{332}{}{Na, jó, ebbõl elég! Ezt nem bírom hallgatni. Valakinek nagyon a nyakadra kéne már lépni és ez a valaki... egész véletlenül én leszek.}
{340}{}{Hát szerintem most jött el a pillanat, hogy nincs mit mondanunk egymásnak. Azt azonban tudnod kell, hogy hacsak nem állsz közénk, élve innen el nem mész.}
{341}{}{Inkább meghalok, minthogy beálljak közétek.}
{342}{}{Hmmm... talán egy kicsit elhamarkodtam az ítéletet.}
{343}{}{Ne kíméld, Willard!}
{350}{}{Idióta! Zomak, nyírd ki a behatolót!}
{360}{}{Ti emberek hihetetlenül intoleránsak vagytok. Ha a fajtátok nem jeleskedett volna a világ elpusztításában, még ma is közönséges patkány lehetnék. Sugárzás híján most nem lennék ilyen.}
{361}{}{Milyen? Meg lehet ezt pontosan határozni?}
{370}{}{Most, hogy mindent elmagyaráztam, készen állsz, hogy közénk állj?}
{371}{}{Nincs semmi kifogásom ellene.}
{372}{}{Azt hiszem, meg vagyok gyõzve. Sikerült rábeszélned, hogy sürgõsen tûnjek a fenébe ebbõl az õrültekházából.}
{380}{}{Régen magam is csak egy közönséges patkány voltam egy jól feleszerelt laboratóriumban. Aztán egy napon robbanásokat hallottunk. A ketreceink kinyíltak, és egy óriási tartályból kiömlõ folyadék a nyakunkba zúdult.}
{381}{}{Aztán?}
{390}{}{Valahogy kijutottam. Miközben gyógyultam, észrevettem magamon a változást. Próbáltam kommunikálni az emberekkel, de azok egytõl-egyig meg akartak ölni. Az emberek túlságosan erõszakosak ahhoz, hogy a saját vezetésük alatt túléljenek bármit... na de nem terelem másra a szót. Az elsõ lépés tehát, hogy meg kell javítani a reaktort.}
{391}{}{Meg kell javítani a reaktort?}
{400}{}{Gekkó reaktorának megjavításához Menedékvárosból kell szerezned egy hidroelektromos magnetoszféra szabályzót. Ha ez nem sikerül, Menedékváros biztosan megtámad bennünket. Persze tudni kell, hogy a reaktorunk megsemmisülésével hosszú távon magukat is tönkreteszik.}
{401}{}{Mit kell azalatt érteni, hogy magukat is tönkreteszik?}
{402}{}{Mire fel adnának nekem ott egy alkatrészt Gekkó atomerõmûvéhez?}
{410}{}{Rá kell ébresztened õket, hogy ehhez bizony erõs érdekük fûzõdik. Az emberek könnyen manipulálhatók, ha a saját érdekükrõl van szó.}
{411}{}{Nem hinném, hogy a menedékvárosi emberek csak úgy adnának nekem egy atomerõmû-tartozékot.}
{420}{}{Ami viszont a jelent illeti, nincs egyéb dolgod?}
{421}{}{Azt hiszem, jobb, ha most rögtön utánanézek ennek az erõmû-alkatrésznek. Késõbb találkozunk.}
{422}{}{Ebben nem lesz hiba. Egyik lábam itt, a másik ott.}
{430}{}{Az orrom nem szokott megcsalni. Biztos vagyok benne, hogy van nálad Sajtos Pufi. Légyszíves adj belõle. Kérlek.}
{431}{}{Ha Sajtos Pufit szeretnél tõlem látni, kénytelen leszel a jéghideg, élettelen ujjaim közül kicsavarni.}
{432}{}{Na, nézzenek oda! Csak nem Sajtos Pufit találtam a zsebemben?! Mitszó'sz?}
{440}{}{[rágcsál, majszol] Mmmm, imádom a Sajtos Pufit, annyira... hogyismondjamcsak... sajtos... Ezért cserébe felajánlom, hogy különleges szektám tagja lehess, és ezzel együtt segíthetsz a világuralom megszerzésében.}
{441}{}{[rágcsál, majszol egyfolytában] Mmmm, imádom a Sajtos Pufit, annyira... hogyismondjamcsak... sajtos... bölcs voltam, hogy hagytalak csatlakozni hozzánk. Most épp nincs semmi dolgod?}
{442}{}{[rágcsál, majszol] Mmmm, imádom a Sajtos Pufit, annyira... hogyismondjamcsak... sajtos...}
{443}{}{[rágcsál, majszol] Mmmm, imádom a Sajtos Pufit, annyira... hogyismondjamcsak... sajtos...}
{444}{}{Rendben.}
{450}{}{Akkor legyen hát! Zomak! Öld meg ezt a szerencsétlent! Vigyázz, nehogy kárt tegyél a Sajtos Pufiban!}
{460}{}{A Reaktor Adatlemezt be kéne helyezned a Menedékváros központi számítógépébe. Két megoldás létezik. Vagy beosonsz, és titkon tevékenykedsz, vagy felkeresed McClure-t a Gazdálkodási Adatlemezzel.}
{461}{}{Gazdálkodási Adatlemezt említettél?}
{462}{}{Ja, értem.}
{463}{}{Csak vidd el Festus számára az Analizált Reaktoradatokat, amit majd a reaktor hatékony mûködése érdekében betáplál a számítógépbe.}
{464}{}{Ha nálad van a hidroelektromos magnetoszféra szabályzó, hozd el nekünk a reaktorba. Ott megpróbálhatod meggyõzni azt a vén majom Festust, hogy cserélje ki az alkatrészt. A munkára a javítórobotot is használhatod, sõt sajátmagad is elvégezheted a mûveletet. A lényeg, hogy valaki megcsinálja, és akkor már egyenesben vagyunk.}
{465}{}{Menedékvárosban hogy jutok hozzá az alkatrészhez?}
{466}{}{Á, értem! Kösz az információért. Majd jövök...}
{467}{}{Festus, aki az atomerõmûvet vezeti, egy vén ripacs. Az idõ eljárt felette, szeszélyes és könnyen kijön a sodrából, de azt meg kell hagyni, hogy az erõmûhöz ért. Az irodája az erõmû dél-keleti részén túl van. Vidd el neki az adatlemezt, és tudni fogja, mi a teendõ.}
{468}{}{Megértettem, rendben. Köszönöm és legyen jó napod.}
{500}{}{[magában elmélkedik] Annyi mindent megértem már. Nem olyan idõk járnak, mint régen [sóhajt]. Sajnos az egész fajtám kipusztult már. Veszettül szívós fajta voltam, de bárcsak ne lettem volna. Reméltem, hogy még a szenilitásom ellenére is megtalálom a magam boldogságát [hozzád] Na, jó, elég a sajnálkozásból!}
{501}{}{Ah, rendben.}
{504}{}{A hidroelektromos magnetoszféra szabályzó az az alkatrész, amit meg kell szerezned Menedékvárosból. Ha megvan, hozd el nekünk és tedd lehetõvé, hogy a helyére kerüljön.}
{505}{}{Tegyem lehetõvé, hogy a helyére kerüljön? De mégis hogy?}
{506}{}{Ah, oké, kösz.}
{510}{}{A reaktor optimalizációs adatai felkerültek a lemezre, amit a menedékvárosi központi számítógépnél szereztél. Most már nincs más dolgod, mint elvinni Festusnak, a vén ripacsnak. Ha valamely rejtélyes oknál fogva nem lennél képes Festusszal beszélni, akár magad is használhatnád a reaktor robotvezérlõ terminálján.}
{511}{}{Festus? Õ kicsoda?}
{512}{}{Ó, értem. Köszönöm. Viszlát!}
{600}{}{A Megújhodás küszöbén állunk, de amíg nem sikerül megjavítanod az atomreaktort, csak egyhelyben toporgunk. [magának] Ezek az emberek... annyira kiábrándítóak...}
{601}{}{A Megújhodás már kézzelfogható, de nem tudunk továbblépni, amíg a Reaktor Adatlemezt nem használod a Menedékváros központi számítógépén. Alapvetõen hajlamos lennék feltételezni, hogy ez nem haladja meg egy emberi lény felfogó képességét.}
{602}{}{Nagyon közel jársz már ahhoz, hogy kezünkbe helyezd a Megújhodás kulcsát. Elõrébb tartanánk, ha az analizált Reaktor Adatlemezt odaadnád Festusnak.}
{603}{}{Nyilván emlékszel, hogy Menedékvárosból meg kell szerezned a hidroelektromos magnetoszféra szabályzót, hogy behelyezhessük az atomreaktorunk rendszerébe. Néha az az érzésem, a Megújhodás az életben el nem jön, amíg emberektõl függünk.}
{604}{}{Mi ez a reaktorjavítás? Fejtsd már ki bõvebben!}
{605}{}{Mit csináljak ezzel a Reaktor Adatlemezzel? Elmondanád?}
{606}{}{Adjam oda Festusnak?}
{607}{}{Egy hidro-miaszar???}
{608}{}{Hogy is van ez a reaktor dolog?}
{609}{}{Kinek adjam?}
{610}{}{Ó, igen. Akkor már itt sem vagyok. Viszlát!}
{620}{}{A zsenialitásom elismeréseképp engem egyszerûen csak Agynak neveznek. Gekkóban nem sokminden kerüli el a figyelmemet.}
{621}{}{De hát te csak egy jól megtermett patkány vagy!}
{622}{}{Mintha mondtál volna valamit a hozzátok való csatlakozásról...}
{630}{}{Az általam kiötlött terv Gekkó és Menedékváros sokezer lakójának jelentene boldogulást. Lehet, hogy hidegen hagy a személyem és a törekvéseim, de az eredmény megéri a fáradságot.}
{631}{}{Most, hogy megvan a Reaktor Adatlemez, használnod kéne.}
{632}{}{Birtokodban van az analizált Reaktor Adatlemez, most már csak használni kellene.}
{633}{}{Az atomreaktorunkból hiányzik egy fõdarab, nélküle nem tudjuk hatékonyan használni.}
{634}{}{Megszerezted az adatokat, melyek alapján optimalizálhatjuk az atomreaktort. Most már nincs más dolgod, mint odaadni Festusnak.}
{635}{}{Miért nem nyögöd ki, miben töröd a fejed?}
{636}{}{Hogy van ezzel a Reaktor Adatlemezzel? Mi a teendõ?}
{637}{}{Nyilván, ezt én magam is kitaláltam, de mi kell ehhez?}
{638}{}{Fõdarab? Miféle fõdarab?}
{639}{}{Áruld el, mi a teendõ az utolsó lépés érdekében, és megfontolom, mit tehetek.}
{640}{}{Kinek kell odaadnom?}
{641}{}{Még egy lépés?}
{650}{}{Nos, annak ellenére, hogy megvan a saját véleményed egy rágcsáló világuralmát illetõen, az általam kiötlött terv Gekkó és Menedékváros sokezer lakójának jelentene boldogulást. Lehet, hogy hidegen hagy a személyem és a törekvéseim, de az eredmény páratlan módon megéri a fáradságot.}
{651}{}{Most, hogy megvan a Reaktor Adatlemez, használnod kéne.}
{652}{}{Birtokodban van az analizált Reaktor Adatlemez, most már csak használni kellene.}
{653}{}{Az atomreaktorunkból hiányzik egy fõdarab, nélküle nem tudjuk hatékonyan használni.}
{654}{}{Miért nem mondod el, miben töröd az agyad?}
{655}{}{Mit csináljak ezzel a Reaktor Adatlemezzel? Világosíts fel!}
{656}{}{Nyilván, ezt én magam is kitaláltam, de mi kell ehhez?}
{657}{}{Úgymint?}
{658}{}{Alkatrész? Miféle alkatrész?}
{659}{}{Áruld el, mi a teendõ az utolsó lépés érdekében, és megfontolom, mit tehetek.}
{670}{}{A reaktor még mindig a reaktor [sóhajt]. Gyere vissza, ha jutottál vele valamire.}
{671}{}{Gyere vissza késõbb, épp egy felsõbb hatalommal diskurálok a francba!}
{700}{}{Nincs több mondanivalóm a számodra.}
