# Dialog Editor last position: 1
{100}{}{Ez az idõsebb ghoul különösen kisnövésû.}
{101}{}{Õ Lenny. Harold segédje.}
{102}{}{Egy alacsony, idõsebb ghoult látsz. Nem nagyon jut ideje rád.}
{110}{}{Üdv, a nevem Lenny. M'miben s'segíthetek?}
{111}{}{Ü'üdv minálunk. Miben s'segíthetek?}
{112}{}{Úgy hallottam, a Menedéklakó leszármazottja vagy. Tudnod kell, hogy én már találkoztam egyszer a Menedéklakóval.}
{113}{}{Üdvözlet! N'nem t'tudom fölfogni, m'mennyire hasonlítasz a Menedéklakóra. M'mit t'tehetek érted?}
{114}{}{Grenny? Hahó!}
{115}{}{Mivel foglalkozol itt?}
{116}{}{Megsebesültem. Tudsz segíteni?}
{117}{}{Az egyik társam megsebesült. Tudsz segíteni?}
{118}{}{A barátaim megsebesültek. Számíthatunk a segítségedre?}
{119}{}{Lenny, hallottál már valaha az Édenkert Létrehozást Elõsegítõ Táskáról?}
{120}{}{Te találkoztál az õsömmel?}
{121}{}{Csak körbejárok. Viszlát!}
{122}{}{Tudsz gyógyítani?}
{125}{}{Hogyne. Mi a bajod?}
{126}{}{Hála az égnek, most rendben vagyok.}
{130}{}{N'nem k'kellett volna elhagyni a faludat. M'menj haza!}
{131}{}{Haza? Viszla...}
{140}{}{M'menj haza!}
{141}{}{N'nem tudok idõt sz'szakítani rád.}
{142}{}{Gy'gyagyás. Menj el innen!}
{150}{}{Az Édenkert L'létrehozást Elõsegítõ T'táskát mondtad? Úgy hallottam, a Menedékekben van ilyesmi. Ennél többet én se tudok róla.}
{151}{}{Megsebesültem. Tudsz rajtam segíteni?}
{152}{}{Az egyik társam megsebesült. Számíthatok a segítségedre?}
{153}{}{Az õsöm, akit a Menedéklakóként tiszteltek, azt mondta, hogy a 13-as Menedék tartozik nekünk egy ilyennel. Meg kell találnom azt a táskát.}
{154}{}{Ennél többet szerintem most nem akarok tudni. Viszlát!}
{160}{}{H'háát, leginkább H'haroldnak segítek. M'mikor az emberek megsérülnek, m'meggyógyítom õket.}
{161}{}{Miben segítesz neki?}
{162}{}{Hadd kérdezzek valami mást!}
{163}{}{Az embereket gyógyítod?}
{164}{}{Megsebesültem. Tudsz rajtam segíteni?}
{165}{}{Az egyik társam megsebesült. Tudsz segíteni?}
{166}{}{Ha megsebesültem, eszembe fogsz jutni. Köszi. Késõbb még jövök.}
{170}{}{Hadd v'vessek rá egy p'pillantást. Sz'szerintem t'tudok segíteni.}
{171}{}{Tartozom ezért valamivel?}
{172}{}{Köszönet, Lenny. Ugye nem baj, ha kérdezek?}
{173}{}{Kösz, Lenny, viszlát!}
{174}{}{S'segíthetek rajtad. D'de 30 d'dollárod bánja. A k'kötszerért.}
{175}{}{Most nem hinném, hogy segítségre szorulnék. Viszlát máskor.}
{180}{}{Hát a b'barátodnak elkelne egy kis s'segítség.. R'rajta is s'segítek, ha kell.}
{181}{}{Úgy t'tûnik, hogy v'valami balhéba k'keveredtél. A t'társaidat is össze tudom t'tákolni.}
{182}{}{Mennyibe fog ez nekem kerülni?}
{183}{}{Kösz, Lenny. Mit szólnál, ha kérdeznék ezt-azt?}
{184}{}{Kösz, Lenny. Viszlát!}
{185}{}{A barátod m'megsérült. Harminc d'dollárért összetákolom neked. A p'pénz k'kötszerre kell.}
{186}{}{Hát ti meg mibe k'keveredtetek? R'rátok férne egy kis gyógykezelés. Hatvan dollár l'lesz összevissza.}
{187}{}{A b'barátod fittnek tûnik.}
{190}{}{T'tulajdonképpen nem t'találkoztam a M'menedéklakóval, de egyszer már láttam.}
{191}{}{Láttad a Menedéklakót? Hol?}
{192}{}{Ah, értem. Az a helyzet, hogy még egy rakás gyilkolnivalóm van. Üdv!}
{200}{}{Hát a h'háború elõtt orvos v'voltam.}
{201}{}{A háború elõtt? Az legalább százhatvan éve volt.}
{202}{}{Hát ez megmagyarázza. Kösz. Viszlát máskor.}
{210}{}{Ez igaz, d'de a sugárzástól m'megnõtt a ghoulok élettartama. Persze m'minden egyéb r'rovására.}
{211}{}{Hogyhogy minden egyéb rovására?}
{212}{}{Itt már senki nem tudja, mi a jó és mi a rossz. Viszlát!}
{220}{}{Hát p'persze. Úgy n'nézünk ki, mint valami brutális sz'szörnyszülött. Még b'bõrünk sincs, az isten szerelmére...}
{221}{}{Hát meglehet, hogy láttatok már jobb napokat is.}
{222}{}{Igaz, ami igaz, így együtt nem mutattok valami vonzóan. Na, minden jót.}
{230}{}{Nem b'bánt, hogy ezt mondod. Ha újra n'normális ember lehetnék, odaadnám azokat az éveket cs'cserébe.}
{231}{}{Aligha hinném, hogy erre sok esély van. Szerintem.}
{232}{}{Meghiszem azt. Na, viszlát!}
{240}{}{Ha azok a m'menedékvárosi tökkelütöttek megosztanák velünk a gy'gyógyászati technológiájukat, biztos vagyok benne, hogy m'megszabadíthatnánk magunkat a s'sugárbetegségtõl.}
{241}{}{Nem akarnak segíteni?}
{242}{}{Máris eleget hallottam. Viszlát!}
{250}{}{V'voltál Menedékvárosban? Akkor megmondhatnád, mekkora esélyét látod, hogy az a földhözragadt n'népség segítsen rajtunk. Sz'szerintem majd akkor segítenek, ha p'piros hó esik.}
{251}{}{Sajnálattal hallom, de asszem, igazad van. Kérdeznék még egy s mást.}
{252}{}{Sajnálattal hallom ezt. Most mennem kell.}
{260}{}{N'nem. Az élet túl r'rövid, legalábbis a legtöbb ember sz'számára, -- he, he -- hogy érdemes legyen apróságok miatt aggódni. T'tudod mit mondok? Az egész annyi, mint a l'légypiszok. És még csak n'nem is kérek semmit a t'tanácsért.}
{261}{}{Kösz, Lenny.}
{270}{}{Régen t'történt. Egy N'nekropolisz nevû helyen. Egy csomó ghoul élt ott egy r'rakáson. Egyik nap látom, hogy valaki rohan át a v'városon.}
{271}{}{Rohan?}
{272}{}{Na, asszem, egy darabig elég lesz a ködös mesékbõl. Majd még jövök talán.}
{280}{}{Igen, ott futott. T'tudod, mi ghoulok már nem nagyon tudunk futni. Így hát amikor m'megláttam, rögtön tudtam, hogy egy idegenrõl v'van szó. Olyan közel futott el, hogy m'megérinthettem volna. Bárcsak cs'csatlakoztam volna a M'menedéklakóhoz...}
{281}{}{Tényleg megfordult a fejedben, hogy mellé állsz?}
{282}{}{Hát persze, az õsöm majd biztos egy ilyen nyúzott szörnypofával szeretett volna sétálgatni. Na, minden jót.}
{283}{}{Igazság szerint szívesen meghallgattam volna az egész történetet, de van még elég dolgom. Minden jót!}
{290}{}{Bizony. Egyszer az életben r'rámmosolyog a sz'szerencse, és jól elbaltázom.}
{291}{}{Ezt kifejtenéd?}
{292}{}{Az élet valóban nem habostorta. Viszont most megyek...}
{300}{}{K'késõbb hallottam, hogy a Menedéklakó megszerelte a v'vízrendszerünket. A M'menedéklakó megmentett minket. Mindannyiunkat. G'gondold végig! Nem tartotta vissza, hogy ghoulok v'vagyunk. Nem számított n'neki és emberszámba vett minket. Érdemesek v'voltunk, hogy valaki velünk is t'törõdjön.}
{301}{}{A törzsünket az õsöm alapította. Nálunk ezt az eseményt nagy tisztelet övezi.}
{302}{}{Hát engem csak az érdekel, hogy a törzsem megmeneküljön. A világ többi része oldja meg a saját problémáit. Ég veled.}
{310}{}{Késõbb hallottam, hogy a Menedéklakó k'kifüstölte a mutáns hadsereg f'forrását. A Menedéklakó mindannyiunkat m'megmentett. Embert, ghoult v'válogatás nélkül... Részese lehettem volna, de inamba szállt a b'bátorságom. Ezt sosem b'bocsátom meg m'magamnak.}
{311}{}{Az õsöm nyomában járok. Mit szólnál, ha egy újabb esélyt kapnál az élettõl? Beállsz hozzám?}
{312}{}{Biztos vagyok benne, hogy az itt végzett munka értékes és megbecsülnek érte. Jó érzés volt hallanom az õsömrõl. Most azonban kérdeznék egy-két dolgot.}
{313}{}{Hát legbelül elég sok ember gyáva kukac. Nem kell szégyellni, egyszerûen csak a gyengékhez tartozol. Na, üdv neked.}
{314}{}{Gyakran megesik, hogy a jó út majd kiüti a szemünket, mégsem látjuk. Mindannyiunknak megvan a maga küldetése. Kösz, hogy felemlítetted az õsömet, most viszont indulnom kell.}
{320}{}{B'boldogabb vagyok, mint egy brahmin bika a t'tehenekkel teli k'karámban! M'megtisztelõ lenne, ha csatlakozhatnék. Lehet, hogy öreg v'vagyok és nem tudok elég f'fürgén mozogni, meg túl sokat se igazán, de az b'biztos, hogy ha m'megsebesülnél, én összefércellek.}
{321}{}{Örülök, hogy így döntöttél. Biztos vagyok, hogy az orvosi képességeid jól jönnek még.}
{322}{}{Hmm, egy ilyen öreg embernek már nem kéne ennyire lelkesednie semmiért. Szerintem jobb lesz, ha ittmaradsz. Sajnálom, ég áldjon.}
{330}{}{Van itt munkám elég, nem cs'csatlakozhatom.}
{331}{}{Az õsödre bizony egy fikarcnyit sem hasonlítasz. Meggyalázod az emlékét!}
{332}{}{M'még sok mindent kell t'tanulnod az életrõl. Amit eddig t'tanultál, nem nagyon t'tetszik nekem.}
{333}{}{Hát nem vagyok feldobva, hogy visszautasítasz...}
{334}{}{Nemááá! Azt hiszed, egy hozzád hasonló nagy rakás rohadó húsnak van bármi esélye is van, hogy ezt az atomtemetõnek is beillõ várost elhagyja? Na, én most itt hagylak szépen...}
{340}{}{Én s'segítek H'haroldnak a város irányításában. M'mindig akad egy cs'csomó p'papírmunka.}
{341}{}{Mit mondtál, mi egyebet csinálsz itt?}
{342}{}{Csak ennyit szerettem volna... Viszlát!}
{350}{}{N'nem volt elég pénzed... de azért s'segítettem. Nem t'tudom elnézni, ha emberek sz'szenvednek.}
{351}{}{Nem tudom eléggé megköszönni, Lenny. Mindenesetre elárulhatnál még egy-két dolgot.}
{352}{}{Kösz, Lenny. Leköteleztél. Viszlát!}
{360}{}{Annyi ember él itt. M'megleszel a segítségem n'nélkül is. Legyen sz'szerencséd.}
{370}{}{Sosem g'gondoltam volna, hogy megérem a n'napot, hogy sz'szégyellni fogom a tetteidet. M'megszégyeníted a Menedéklakó emlékét. Menny', menny', ne is lássalak.}
{371}{}{T'tudod, aszittem, h'hogy jó lenne v'veled utazgatni. De olyan csökönyös és kötekedõ v'vagy, mint a brahminbika, amikor k'kaktusz áll a seggébe. Mellesleg a szagod se j'jobb. Menny' el innét!}
{372}{}{Sajnálom, hogy itthagysz, Lenny.}
{373}{}{Nem bírsz ezzel mit kezdeni, mi? Jobb lenne, ha elhordanád a félig rohadt testedet, mielõtt észbekapok és végiggondolom, hogy megérsz-e egy töltényt vagy sem.}
{374}{}{*böff* Hát persze. Nyilván van más dolgod, mint például naphosszat azon elmélkedni, milyen volt a rendes bõröd, amikor még nem úgy nézett ki, mint a három hónapos útszéli dög július tájékán. Tûnés innen, kibaszott szörnyszülött!}
{375}{}{Rendben.}
{380}{}{M'mit akarsz, mit t'tegyek?}
{381}{}{Lenny, tudom, hogy kiteszel magadért, de légyszi menj el elõlem!}
{382}{}{Szeretném, ha másképp harcolnál, Lenny.}
{383}{}{Szeretném, ha itt várnál rám.}
{384}{}{Felcser, gyógyítsd tenmagad!}
{385}{}{Gyógykezelésre van szükségem, Lenny.}
{386}{}{Néhány barátom orvosi kezelésre szorul.}
{387}{}{Láss el bennünket.}
{388}{}{Hogy ityeg a fityeg, öreg rája?}
{389}{}{Most nincs szükségem másra, Lenny.}
{400}{}{Harcoljak m'másképp?}
{401}{}{Azt akarom, hogy változtassunk a távolságon.}
{402}{}{Azt akarom, hogy a legjobb fegyveredet használd.}
{403}{}{Azt akarom, hogy használd a legjobb védõfelszerelésedet.}
{404}{}{Változtatni kéne a harcmodorodon.}
{405}{}{Rendben, hagyjuk az egészet.}
{410}{}{M'milyen messze álljak? Tudod, elég nehéz l'lépést t'tartanom.}
{411}{}{Maradj a közvetlen közelemben.}
{412}{}{Ne nagyon maradj le, állj egy kicsit hátrébb, de ne nagyon messze.}
{413}{}{Jó lenne, ha jócskán lemaradnál.}
{414}{}{Szeretném, ha felderítést végeznél.}
{415}{}{Felejtsd el.}
{420}{}{Mit t'tegyek?}
{421}{}{Mostantól h'harcolj védekezve.}
{422}{}{Mostantól h'harcolj a megszokott módon.}
{423}{}{Mostantól h'harcolj agresszíven.}
{424}{}{Ne is törõdj vele!}
{430}{}{Sz'szerintem tudnál az öreg r'rókának tanítani új t'trükköket. Nagyon b'baba.}
{431}{}{Valahogy n'nem t'tudok rájönni a nyitjára.}
{432}{}{Rendben.}
{440}{}{Ah, rendben. Itt v'várok majd, amíg v'vissza nem jössz. Jó is lesz megpihentetni f'fájós tagjaimat.}
{441}{}{Csak nyugodtan, Lenny. Még találkozunk.}
{442}{}{Itt kéne várnod... ja és még valami...}
{443}{}{Vedd úgy, hogy nem szóltam.}
{450}{}{Kéne egy n'nagyobb f'fegyver nekem.}
{451}{}{Használd a legjobb fegyvered, Lenny!}
{461}{}{Vedd fel a legjobb védõfelszerelésedet, Lenny.}
{462}{}{Lenny, miután felvetted a legjobb védõfelszerelésedet, akarok kérni valamit tõled.}
{463}{}{Haladjunk...}
{470}{}{Ez jó ötlet. Már azon g'gondolkodtam, mikor állunk m'meg. Sajog m'minden t'tagom.}
{471}{}{Hadd vessek egy p'pillantást a s'sebeidre.}
{472}{}{Nagyon úgy tûnik, v'valaki már megint az én s'segítségemre szorul.}
{473}{}{Ne fogd vissza magad, kezeld le magad!}
{474}{}{Kezeld le magad, utána van még egy s más, amit meg kéne beszélnünk.}
{475}{}{Kezelj le engem, légyszíves.}
{476}{}{Kezelj le, aztán még van ez-az, amit meg kéne beszélnünk.}
{477}{}{Gyerünk, kezelj le bennünket.}
{478}{}{Kezelj le bennünket, aztán még meg kéne vitatnunk ezt-azt.}
{479}{}{Á, hagyjuk...}
{480}{}{Én nem t'tudok olyat. Nem v'vagyok én felderítõ.}
{481}{}{Értem, akkor vedd úgy, mintha nem is mondtam volna.}
{490}{}{A nyomodban f'fogok l'lihegni.}
{491}{}{Maradj közel, Lenny!}
{492}{}{Maradj közvetlenül a nyomomban, és még valamit meg kéne beszélnünk.}
{493}{}{Vedd úgy, mintha nem is szóltam volna.}
{500}{}{G'gondolom nem akarunk k'könnyû célponttá v'válni.}
{501}{}{Ne gyere ennyire rám, Lenny, azt akarom, hogy ha ránklõnek, legalább dolgozzanak meg érte.}
{502}{}{Ne lihegj a nyakamba, kérlek, ezenkívül beszélnünk kell még másról is.}
{503}{}{Nem szóltam.}
{510}{}{Rendben. K'kicsit lemaradok. Úgy t'tûnik egyébként, hogy az emberek leginkább téged akarnak h'holtan látni.}
{511}{}{A saját biztonságod érdekében maradj le kissé! Semmi köze nincs a szagodhoz.}
{512}{}{Mielõtt szétszóródunk, valamire meg akarlak kérni.}
{513}{}{Nem szóltam, rendben?}
{520}{}{Az évek s'során eléggé megtanultam t'törõdni magammal.}
{521}{}{Azt akarom, ha harcra kerül sor, légy óvatos.}
{522}{}{Biztos akarok lenni, hogy semmi bajod nem esik. Antik darab vagy a fenébe is! Volna amúgy még valami itt...}
{523}{}{Rá se ránts!}
{530}{}{Csak úgy lehet megcsinálni.}
{531}{}{Csak harcolj úgy, ahogy normálisan harcolnál, és nem lesz gond.}
{532}{}{Kicsit maradj le és harcolj a megszokott módon. Ja és még valami...}
{533}{}{Nem szóltam...}
{540}{}{N'nem tudok én olyat. M'már az is szép tõlem, ha egyáltalán h'harcolni tudok.}
{541}{}{Rendben. Felejtsük el...}
{1000}{}{M'mit tegyek?}
{1100}{}{J'jól elvagyok.}
{1200}{}{Van egy k'kisebb sérülésem, de oda se neki.}
{1300}{}{Ez jó ötlet. Már azon g'gondolkodtam, mikor állunk meg. Eléggé s'sajog mindenem.}
{1400}{}{Kezelés kell, k'különben elpatkolok...}
{1500}{}{R'rendben. Itt várok, amíg v'vissza nem jössz. Amúgy is r'rámfért már egy k'kiadós pihenõ.}
{1600}{}{Rendben.}
{1700}{}{Közel m'maradok.}
{1800}{}{G'gondolom, nem akarunk k'könnyû célponttá v'válni.}
{1900}{}{Legyen, egy k'kissé lemaradok. Úgy t'tûnik egyébként, hogy az emberek leginkább téged akarnak h'holtan látni.}
{2000}{}{Úgy látom, egy csomóan vannak m'ár itt. Nem kell n'neked az én segítségem. L'légy szerencsés.}
{2100}{}{Sosem g'gondoltam volna, hogy megérem a n'napot, hogy sz'szégyellni fogom a tetteidet. M'megszégyeníted a Menedéklakó emlékét. Mennyé, mennyé, ne is lássalak.}
{2200}{}{N'nem voltam benne b'biztos, hogy még visszajössz.}
{2300}{}{Minek ez a hercehurca állandóan?}
{2301}{}{Ó, sajnálom, eltûnök a képbõl.}
{2302}{}{Megyek, megyek, megyek. Nem kell engem abajgatni. Bocs, nem akartam lábatlankodni.}
{2303}{}{Sajnálom, egyszerûen n'nem tudok gyorsabban h'haladni. Már megyek is az útból...}
{2304}{}{ó, értem. Húzok el az utadból...}
{2305}{}{Ott fogok battyogni, ahol akarod.}
{2306}{}{Nem akartam útban lenni.}
{2307}{}{Ó, elnézést.}
{3000}{}{Túl sok baj történik körülötted. Mielõtt valami történne velem, lelépek...}
{3001}{}{Nem s'segítek egy gyerekgyilkosnak. Minden jót!}
{3002}{}{Megrémítesz a v'vérszomjaddal, ezért többé nem akarok veled t'tartani.}
{3003}{}{Egy r'rabszolgahajcsárral nekem nincs s'semmi dolgom. Minden jót n'neked.}
{3004}{}{Áruló vagy! Megsemmisítetted az erõmûvünket. Segítsen n'neked a halál!}
{3005}{}{Nem akarok én tõled semmit!}
{4000}{}{Nos, rendben, de nehogy már itt h'hagyj engem egyedül!}
{4001}{}{Rendben, ha szerinted ez jó ötlet.}
{4002}{}{Hát nem nagyon sz'szeretem a fegyvereket, hacsak n'nincs rájuk égetõ szükség. Szerintem egy k'kés nem okozna különösebb g'gondot, és tudok bánni a p'pisztollyal is, legalábbis régen tudtam. Ha nagyon r'rákényszerülnék, szerintem egy g'géppisztolytól sem jönnék zavarba. Bárcsak ne lennének olyan h'hangosak ezek a f'fegyverek. Gyógyító vagyok én, nem k'katona.}
{4003}{}{Hát remélem, nem lesz rá szükségem!}
