{100}{}{Egy barátságos arcú, szikár embert látsz.}
{101}{}{Chad, a karavánvezetõ.}
{102}{}{Egy szikár embert látsz, arcán olyan mosollyal, akár egy pajzs. Ruhája teljesen jellegtelen, és úgy járkál fel-alá, mintha aki tudja, mit csinál.}

{120}{}{Hahó, barátom! Mit tehetek érted?}
{121}{}{Még több kérdés? Meglátom, mit tehetek érted a válaszok terén.}
{122}{}{Dörk digglerr!}
#ez volna tehat a boogie nights fohose (bass)

{123}{}{Te ki lenni?}
{124}{}{Marcus kérdezõsködik felõled.}
{125}{}{Elég bizonyítékom van arra, hogy pénzt loptál Broken Hills városától. Le leszel tartóztatva. Mész a sittre!}
{126}{}{Elég bizonyítékom van arra, hogy pénzt loptál Broken Hills városától. Le leszel tartóztatva, de ha megkensz egy ezressel hagyom, hogy elmenekülj.}
{127}{}{Ki vagy te?}
{128}{}{Mesélnél errõl a helyrõl?}
{129}{}{Semmit. Viszlát!}

{130}{}{Nézd már, mit fújt be a sivatagi szél a városba! Bocs, haver, nem tudok rajtad segíteni.}
{131}{}{Szióka!}

{132}{}{Chad vagyok. }
{133}{}{Bocs, elég sok dolgom van. Keress valaki mást!}
{134}{}{Én vagyok a város karavánmestere. Én kötöm az üzleteket a karavánutak túlsó végén. Mostanában leginkább Gekkóra koncentrálok.}
{135}{}{Defrankó!}
{136}{}{Lenne valami munka a számomra?}
{137}{}{Izgalmas lehet.}
{138}{}{Unalmas lehet.}
{139}{}{Szeretnék valami mást kérdezni.}
{140}{}{Kösz. Viszlát!}

{141}{}{Meséljek Broken Hillsrõl? Hát... Pár évvel ezelõtt jöttem ide. Munkát szereztem Billnél... õ a karavánmester... és azóta ott tartok, ahol most. Marcusnak és Billnek kell jelentenem. Én felelek a város élelmiszer-ellásátásért.}
{142}{}{Szeretnék valami mást kérdezni.}
{143}{}{Viszlát!}

{156}{}{Beszélj Billel! Õ tud segíteni.}
{157}{}{Szeretnék valami mást kérdezni.}
{158}{}{Kösz. Viszlát!}

{159}{}{Igen, az. Nem is gondolnád, de sokat kell utaznom, így láthatom a világot... és úgy érzem, ezzel hozzájárulok a város elõrelépéséhez. Jó élet ez.}
{160}{}{Jól hangzik. Szeretnék egy ilyen állást.}
{161}{}{Hát, ez elég unalmasan hangzik.}
{162}{}{Szeretnék valami mást kérdezni.}
{163}{}{Viszlát!}

{164}{}{Szerintem százszor izgalmasabb, mint amit te csinálsz az életeddel, seggfej!}
{165}{}{Igen, persze. Mást kérdeznék.}
{166}{}{Ha ha ha ha! Hát persze. Viszlát, te vesztes!}

{167}{}{Egyszer megfizetsz ezért, te tetû!}

{168}{}{Tûnj innen, te mocsok!}

{169}{}{Ezt jól elbaltáztad, barátom. Ennyit a pénzedrõl.}
{170}{}{Hát, ezt rendesen elcseszted, haver. Sok sikert ahhoz, hogy másik munkát találj Broken Hillsben!}
{171}{}{Szép munka volt! Itt a 200 dolcsid.}

{172}{}{Tûnj innen! Nincs szükségünk többé a segítségedre!}

{173}{}{Tartsd nyitva a szemed!}
{174}{}{Hátulról fedezlek!}
{175}{}{Ne engedd a mocskokat közel magadhoz!}