{100}{}{Egy barátságos arcú, szikár embert látsz.}
{101}{}{Chad, a karavánvezető.}
{102}{}{Egy szikár embert látsz, arcán olyan mosollyal, akár egy pajzs. Ruhája teljesen jellegtelen, és úgy járkál fel-alá, mintha aki tudja, mit csinál.}
{120}{}{Hahó, barátom! Mit tehetek érted?}
{121}{}{Még több kérdés? Meglátom, mit tehetek érted a válaszok terén.}
{122}{}{Dörk digglerr!}
{123}{}{Te vagyol ki?}
{124}{}{Marcus kérdezősködik felőled.}
{125}{}{Elég bizonyítékom van arra, hogy pénzt loptál melyet Broken Hills városának szántak. Le leszel tartóztatva. Mész a sittre!}
{126}{}{Elég bizonyítékom van arra, hogy pénzt loptál Broken Hills városától. Le kellene tartóztassalak, de ha megkensz egy ezressel hagyom, hogy elmenekülj.}
{127}{}{Ki vagy?}
{128}{}{Meséljen erről a helyről!}
{129}{}{Semmit. Viszlát!}
{130}{}{Nézd már, mit fújt be a sivatagi szél a városba! Bocs, haver, nem tudok rajtad segíteni.}
{131}{}{Szióka!}
{132}{}{Chad vagyok. }
{133}{}{Bocs, elég sok dolgom van. Keress valaki mást!}
{134}{}{Én vagyok a város karavánmestere. Én kötöm az üzleteket a karavánutak túlsó végén. Mostanában leginkább Gekkóra koncentrálok.}
{135}{}{Okké!}
{136}{}{Lenne valami munka a számomra?}
{137}{}{Izgalmas lehet.}
{138}{}{Unalmas lehet.}
{139}{}{Mást szeretnék kérdezni.}
{140}{}{Köszönöm. Viszlát!}
{141}{}{Meséljek Broken Hillsről? Hát... Pár évvel ezelőtt jöttem ide. Munkát szereztem Billnél... ő a karavánmester... és azóta ott tartok, ahol most. Marcusnak és Billnek kell jelentenem. Én felelek a város élelmiszer-ellásátásért.}
{142}{}{Mást szeretnék kérdezni.}
{143}{}{Viszlát!}
{144}{}{Úgymint?}
{145}{}{Ő azt feltételezi, hogy sikkasztasz a pénzből amit Broken Hillsnek szánnak.}
{146}{}{Semmi különös. Viszlát!}
{147}{}{Nézd. Nem szeretem mikor emberek megvádolnak engem valamivel amiről semmit sem tudok. Azt javaslom távozz.}
{150}{}{Rá fogok jönni az igazságra. Viszlát.}
{156}{}{Beszélj Billel! Ő tud segíteni.}
{157}{}{Mást szeretnék kérdezni.}
{158}{}{Köszönöm. Viszlát!}
{159}{}{Igen, az. Nem is gondolnád, de sokat kell utaznom, így láthatom a világot... és úgy érzem, ezzel hozzájárulok a város előrelépéséhez. Jó élet ez.}
{160}{}{Jól hangzik. Szeretnék egy ilyen állást.}
{161}{}{Hát, ez elég unalmasan hangzik.}
{162}{}{Mást szeretnék kérdezni.}
{163}{}{Viszlát!}
{164}{}{Szerintem százszor izgalmasabb, mint amit te csinálsz az életeddel, seggfej!}
{165}{}{Igen, persze. Mást kérdeznék.}
{166}{}{Ha ha ha ha! Hát persze. Viszlát, te vesztes!}
{167}{}{Egyszer megfizetsz ezért, te tetű!}
{168}{}{Tűnj innen, te mocsok!}
{169}{}{Ezt jól elbaltáztad, barátom. Ennyit a pénzedről.}
{170}{}{Hát, ezt rendesen elcseszted, haver. Sok sikert ahhoz, hogy másik munkát találj Broken Hillsben!}
{171}{}{Szép munka volt! Itt a 200 dolcsid.}
{172}{}{Tűnj innen! Nincs szükségünk többé a segítségedre!}
{173}{}{Tartsd nyitva a szemed!}
{174}{}{Hátulról fedezlek!}
{175}{}{Ne engedd a mocskokat közel magadhoz!}
