{100}{}{Egy barátságos arcú, szikár embert látsz.}
{101}{}{Chad, a karavánvezet?.}
{102}{}{Egy szikár embert látsz, arcán olyan mosollyal, akár egy pajzs. Ruhája teljesen jellegtelen, és úgy járkál fel-alá, mintha aki tudja, mit csinál.}
{120}{}{Hahó, barátom! Mit tehetek érted?}
{121}{}{Még több kérdés? Meglátom, mit tehetek érted a válaszok terén.}
{122}{}{Dörk digglerr!}
{123}{}{Te ki lenni?}
{124}{}{Marcus kérdez?sködik fel?led.}
{125}{}{Elég bizonyítékom van arra, hogy pénzt loptál Broken Hills városától. Le leszel tartóztatva. Mész a sittre!}
{126}{}{Elég bizonyítékom van arra, hogy pénzt loptál Broken Hills városától. Le leszel tartóztatva, de ha megkensz egy ezressel hagyom, hogy elmenekülj.}
{127}{}{Ki vagy te?}
{128}{}{Mondj valamit err?l a helyr?l!}
{129}{}{Semmit. Viszlát!}
{130}{}{Nézd már, mit fújt be a sivatagi szél a városba! Bocs, haver, nem tudok rajtad segíteni.}
{131}{}{Szióka!}
{132}{}{Chad vagyok. }
{133}{}{Bocs, elég sok dolgom van. Keress valaki mást!}
{134}{}{Én vagyok a város karavánmestere. Én kötöm az üzleteket a karavánutak túlsó végén. Mostanában leginkább Gekkóra koncentrálok.}
{135}{}{Okké!}
{136}{}{Lenne valami munka a számomra?}
{137}{}{Izgalmas lehet.}
{138}{}{Unalmas lehet.}
{139}{}{Volna még néhány kérdésem.}
{140}{}{Kösz. Viszlát!}
{141}{}{Tell you about Broken Hills? Well... I moved here a few years back. Got a job with the Bill --
 that's the Outfitter -- and moved up to where I am now. I report to Marcus and the Bill, but I'm
 responsible for the livelihood of the town.}
{142}{}{Volna még néhány kérdésem.}
{143}{}{Viszlát!}
{144}{}{Úgymint?}
{145}{}{He suspects, that you are skimming the money that's supposed to go Broken Hills.}
{146}{}{Nothing really, Bye.}
{147}{}{Look, I don't like people to accuse me about something that I don't know anything about. I suggest that you leave.}
{150}{}{I'm going to find the truth. Bye.}
{156}{}{Beszélj Billel! ? tud segíteni.}
{157}{}{Volna még néhány kérdésem.}
{158}{}{Kösz. Viszlát!}
{159}{}{Igen, az. Nem is gondolnád, de sokat kell utaznom, így láthatom a világot... és úgy érzem, ezzel hozzájárulok a város el?relépéséhez. Jó élet ez.}
{160}{}{Jól hangzik. Szeretnék egy ilyen állást.}
{161}{}{Hát, ez elég unalmasan hangzik.}
{162}{}{Volna még néhány kérdésem.}
{163}{}{Viszlát!}
{164}{}{Szerintem százszor izgalmasabb, mint amit te csinálsz az életeddel, seggfej!}
{165}{}{Igen, persze. Mást kérdeznék.}
{166}{}{Ha ha ha ha! Hát persze. Viszlát, te vesztes!}
{167}{}{Egyszer megfizetsz ezért, te tet?!}
{168}{}{T?nj innen, te mocsok!}
{169}{}{Ezt jól elbaltáztad, barátom. Ennyit a pénzedr?l.}
{170}{}{Hát, ezt rendesen elcseszted, haver. Sok sikert ahhoz, hogy másik munkát találj Broken Hillsben!}
{171}{}{Szép munka volt! Itt a 200 dolcsid.}
{172}{}{T?nj innen! Nincs szükségünk többé a segítségedre!}
{173}{}{Tartsd nyitva a szemed!}
{174}{}{Hátulról fedezlek!}
{175}{}{Ne engedd a mocskokat közel magadhoz!}
