{100}{}{Egy bõrpáncélos, unatkozó embert látsz.}
{101}{}{Õ (x), a karavánkísérõ.}
{102}{}{Egy bõrpáncélos, unatkozó embert látsz. A brahminbûzbõl, ami körüllengi, és a magabiztos járásából egyértelmûen látszik, hogy karavánkísérõ.}

{103}{}{Segíthetek valamiben?}
{104}{}{Urg?}
{105}{}{Énn dolgozni!}
{106}{}{Ki vagy te?}
{107}{}{Mit tudsz nekem mondani Chadról?}

{108}{}{Nincs idõ hülyegyerekekre. Bocs, haver, de keress mást, akivel játszhatsz!}
{109}{}{::szipp::}

{110}{}{(x) vagyok. Az egyik karavánkísérõ.}
{111}{}{Mit tudsz nekem mondani Chadról?}
{112}{}{Kösz. Viszlát!}

{113}{}{Chad jó ember. Kemény, de igazságos. Bõkezûen bánik azokkal, akik jól dolgoznak.}
{114}{}{Mi a neved?}
{115}{}{Kösz. Viszlát!}

{116}{}{Kösz. De, igazán. Kösz, hogy elvetted tõlünk a bónusz keresetet. Chad csak azokat rövidítette meg, akikkel kereskedtünk. Ezzel segített rajtunk, te meg jól elszúrtad. Seggfej!}
{117}{}{Viszlát!}

{118}{}{Itt az ellenség! Pusztulj!}
{119}{}{Hopplá!}