{100}{}{Egy bőrpáncélos, unatkozó embert látsz.}
{101}{}{You see Max, the caravan guard.}
{102}{}{Egy bőrpáncélos, unatkozó embert látsz. A brahminbűzből, ami körüllengi, és a magabiztos járásából egyértelműen látszik, hogy karavánkísérő.}
{103}{}{Segíthetek valamiben?}
{104}{}{Örgh?}
{105}{}{Énn dolgozni!}
{106}{}{Ki vagy?}
{107}{}{Mit tudsz nekem mondani Chadról?}
{108}{}{Nincs idő hülyegyerekekre. Bocs, haver, de keress mást, akivel játszhatsz!}
{109}{}{::szipp::}
{110}{}{I'm Max. I'm one of the caravan guards.}
{111}{}{Mit tudsz nekem mondani Chadról?}
{112}{}{Köszönöm. Viszlát!}
{113}{}{I don't like him much. He seems to get always some extra money from his caravan jobs. It's really unfair.}
{114}{}{Well, Marcus suspects that he is skimming some of the money that supposed to go Broken Hills.}
{115}{}{Köszönöm. Viszlát!}
{116}{}{Thanks. I'm sure glad that's over. You better watch your back though.}
{117}{}{Viszlát!}
{118}{}{Itt az ellenség! Pusztulj!}
{119}{}{Jaj...}
{120}{}{[Lowers his voice and looks around] That's gotta be it. I once saw myself that he was taking some "slice" of that money he got from uranium shipment from Gecko.}
{121}{}{Really? Then why didn't you report that to Marcus?}
{122}{}{Are you duff? If I go to tell it, a lot of people in this town won't even look at me. Besides I might get some kind of revenge.}
{123}{}{Hmm, I could tell it about to Marcus, cause I don't plan to stay here too long anyway.}
{124}{}{Ok. Do what you want, but don't tell anything about me. And we never had this conversation, ok?}
{125}{}{Don't worry, I don't want to get you in any trouble, bye.}
