{100}{}{Egy embert látsz, aki egy szép, nagy fegyvert szorongat a kezében.}
{101}{}{A Broken Hillsi kereskedõ és õrzõ testület egyik tagját látod.}
{102}{}{Egy embert látsz, akit az út pora borít. Szép nagy fegyvert tart a kezében.}
{103}{}{Én mondom, még egy csapat útonálló, és legközelebb dinamitot is viszek magammal!}
{104}{}{Hasznát látnánk egy kis segítségnek a karavánoknál.}
{105}{}{Haver... az "Összefogás" õrjárat kezd nagyon, nagyon kiöregedni.}
{106}{}{Szóval akkor jött az a törzsbéli, mire én... ööö, hagyjuk.}
{107}{}{Még egy "Szivárvány õrjárat" seggség, és valakit biztosan kinyírok!}
{108}{}{Ha az útonálók bekeményítenek, jövõre mind meghalunk, az tuti.}
{109}{}{Milyen faluból jössz?}
{110}{}{Nem vennél egy kis piát egy dolgozó embernek?}
{111}{}{Túlságosan kifáraszt a karavánmunka, hogy még beszélgessek is.}
{112}{}{Ha kell valami, beszélj Billel, a karavánok szervezõjével!}
{113}{}{Talán ennyi idõ után, amit a puszta civilizálásával töltöttünk, közelebb kerültünk a célunkhoz.}
{114}{}{Elegem van ebbõl az ember-mutáns veszekedésbõl. Nem éppen nekünk kellene példát mutatnunk?}
{115}{}{Mit akarsz? Nem látod, hogy pihenek?}
{116}{}{Mikor indul a következõ karaván?}
{117}{}{Járõrözni, járõrözni, járõrözni... mindig ugyanaz a meló.}
{118}{}{Kezdek álmos lenni.}
{119}{}{Fizetésemelést követelek! Ez veszélyes munkakör.}
