{100}{}{Egy termetes mutáns.}
{101}{}{Marcus, Broken Hills mutáns seriffje.}
{102}{}{Egy nagy darab, öreg mutánst látsz. Arcáról kimerültség tükrözõdik, de még mindig életerõsnek látszik.}

# node 1
{103}{mcs1a}{Nocsak, mi a fene! Jó rég láttam utoljára ilyen öltözetet. Emlékeket ébreszt bennem.}
{104}{mcs1b}{Mit akarsz, ember?}
{105}{mcs1c}{Szeretnél még valamit?}
{106}{}{Csúúny!}
{107}{}{Ki vagy te?}
{108}{}{Mesélnél nekem errõl a városról?}
{109}{}{Miért nem támadnak meg a mutánsok itt?}
{110}{}{Mi újság?}
{111}{}{Van valami, amit el szeretnék mondani.}
{112}{}{Nincs kedved velem vándorolni?}
{113}{}{Viszlát!}

{114}{mcs3}{Igen, egy nagy, csúnya mutáns vagyok, és én vezetem ezt a várost. Van valami problémád ezzel?}
{115}{}{Igeh!}
{116}{}{Neh.}

{117}{mcs4}{Harcolni akarsz?}
{118}{}{Igeh!}
{119}{}{Neh.}

{120}{mcs5}{Célozz pontosan, ember!}

{121}{mcs6a}{Rendben.}
{122}{mcs6b}{Ne üsd bele semmibe az orrod, és nem lesz semmi bajod!}
{123}{}{He?}

{124}{mcs7}{Marcus vagyok, a város egyik alapítója. Most én vagyok a seriff.}
{125}{}{Te alapítottad ezt a várost? Az jó régen lehetett...}
{126}{}{Lószart! Hogy a fenébe élhetnél akkor még mindig?}
{127}{}{Viszlát!}

{128}{mcs8}{Ez egy hosszú történet. A rövid vagy a hosszú verziót akarod?}
{129}{}{Beérem a röviddel.}
{130}{}{Végülis idõm van bõven. Halljuk az egészet!}
{131}{}{Egyiket sem. Mást kérdeznék inkább.}
{132}{}{Egyiket sem. Viszlát!}

{133}{mcs9}{Rendben. Én és egy Jacob nevû ember építettük ezt a várost a már meglévõ bank köré körülbelül 60 éve. Mindenkit szívesen látunk, amíg nem zavarják a rendet.}
{134}{}{Nagyszerû! Viszont lenne még néhány kérdésem.}
{135}{}{Értem. Viszlát!}

{136}{mcs10}{Rendben... Miután a Mester elpusztult, nyakamba vettem a világot. Nem volt hova mennem. Egy nap megtámadott egy erõpáncélos bolond.}
{137}{}{Tényleg?}

{138}{mcs11}{Õ volt Jacob, az Acél Testvériségbõl. Esküt tett, hogy minden mutánst megöl. Verekedtünk egy darabig (nevet)... talán egy vagy két napig. Egy idõ után elnevettük magunkat: miért is verekszünk?}
{139}{}{És aztán?}

{140}{mcs12}{Barátok lettünk és együtt utaztunk tovább. Mások is elkezdtek követni minket. Talán úgy gondolták, ha egy mutáns és egy Acél-lovag mellett nincsenek biztonságban, akkor sehol.}
{141}{}{Szóval itt telepedtetek le... Miért pont itt?}

{142}{mcs13}{Az uránbánya miatt. Régi térképekrõl tudtam, hogy errefelé van egy. Most már mindenkit szívesen látunk, amíg nem zavarják a rendet. Mások talán nem tartanak sokra minket, de senki sem olyan szabad, mint mi. Hát ennyi.}
{143}{}{Várj... egy Testvériségbeli volt a barátod?}
{144}{}{Mi, mostantól nem ölsz több embert?}
{145}{}{Kösz. Viszlát!}

{146}{mcs14}{Te hol a fenében éltél eddig? A mutik és az emberek réges-rég békét kötöttek.}
{147}{}{Egy faluban, amit az Eredeti Menedéklakó alapított.}
{148}{}{Egy faluban messze északnyugatra.}
{149}{}{Óh, bocs, tévedtem. Kösz, és viszlát!}

{150}{mcs15a}{Mi újság... Mi újság...}
{151}{mcs15b}{Hát, kezdek aggódni az egyik karavános emberke miatt. Chad a neve. Az a gyanúm, hogy sikkaszt. Nincs kedved utánajárni?}
{152}{}{Mit kapok cserébe?}
{153}{}{Dehogynincs! Utánajárok.}
{154}{}{Sok a dolgom.}
{155}{}{Más munka nincs?}

{156}{mcs16}{A hálámat, mely örökké üldözni fog. Megfelel?}
{157}{}{Megfelel.}
{158}{}{Nem elég. Valami mást akarok.}
{159}{}{Mit szólsz pár kérdéshez, amíg meggondolom?}
{160}{}{Gondolkozom rajta. Viszlát!}

{161}{mcs17}{Ha ez nem elég neked, akkor tûnj innen!}
{162}{}{Viszlát!}

{163}{mcs18}{Van egy kis gond a bányával. Ha érdekel a dolog, beszélj Zaiusszal, a bányavezetõvel!}
{164}{}{Hol találom õt?}
{165}{}{Nincs más munka?}
{166}{}{Mást szeretnék kérdezni.}
{167}{}{Talán késõbb. Viszlát!}

{168}{mcs19}{Leginkább a bányánál. Néha a kocsmában.}
{169}{}{Nincs más munka?}
{170}{}{Mást szeretnék kérdezni.}
{171}{}{Viszlát!}

{172}{mcs20}{Valaki kiengedett két elmebajost a bank börtönébõl. Találd meg õket, szólj nekem és visszasittelem õket!}
{173}{}{Nincs más munka?}
{174}{}{Mást szeretnék kérdezni.}
{175}{}{Viszlát!}

{176}{mcs21}{Mit akarsz tulajdonképpen? Rendben. Eltûnt pár ember. Gõzöm sincs, mi történhetett. Ha megtalálod õket, kapsz 500 dolcsit.}
{177}{}{Megcsinálom ingyen.}
{178}{}{500 dolcsi? Jól hangzik.}
{179}{}{Nem érek rá.}
{180}{}{Mást szeretnék kérdezni.}
{181}{}{Viszlát!}

{182}{mcs22}{Rendben. Szólj, ha találtál valamit, oké?}
{183}{}{Persze. Szeretnék valami mást is kérdezni...}
{184}{}{Oké. Viszlát!}

{185}{mcs23}{Igen? Mi az?}
{186}{}{Mondtad, hogy keressem meg az eltûnt embereket. Találtam a város alatt egy alagútrendszert. Azt hiszem, ott vannak.}
{187}{}{Megvannak az elveszett emberek. A város alatti alagutakban vannak.}
{188}{}{A két szökött elítéltrõl lenne szó. Összeszûrik a levet Jacobbal és Aileennel. Jacob Gyógyszertárában rejtõznek.}
{189}{}{Jacob és Aileen megkért, hogy segítsek nekik kihozni két embert a börtönbõl. Azt hiszem, van kész tervük is rá.}
{190}{}{Jacob és Aileen azt akarják, hogy robbantsam fel a bányát. Gondoltam, jobb ha tudsz róla.}
{191}{}{Egy ÚKK-s tudós azt akarta, hogy próbáljak itt ki egy kísérleti mutánsölõ szérumot. Jobb lesz, ha figyeltek rá, hogy mit esztek és isztok!}
{192}{}{Chad 6000 dollárt kért Gekkó üzletkötõjétõl. Az panaszkodott az ár miatt... túl soknak találta a múltkorihoz képest.}
{193}{}{Chad megtartott magának egy ezrest a legutóbbi uránszállítmány árából. Tervezi, hogy elhagyja a várost.}
{194}{}{Semmi. Felejtsd el!}

{195}{mcs24}{Város alatti alagutak? Végülis nem meglepõ a bánya miatt. Folytatod a keresést, ugye?}
{196}{}{Folytatom.}

{197}{mcs25a}{Halottak? A fene... megmondom a hozzátartozóknak.}
{198}{mcs25b}{Itt a pénzed. 500 dollár. Kösz a munkát.}
{199}{mcs25c}{Hé, tudom, hogy ingyen csináltad, de ez téged illet.}
{200}{}{Kösz.}

{201}{mcs26}{Értem. Innen átveszem én a dolgot... És kösz. Nem felejtem el!}
{202}{}{Nem probléma. Viszlát!}

{203}{mcs27}{Mit akarnak az emberek a mutánsoktól? Résen leszünk. Kösz. A város nyitva áll elõtted. Ezt nem felejtem el neked.}
{204}{}{Enyém a megtiszteltetés. Viszlát!}

{205}{mcs28}{Tartsd rajta a szemed, rendben? Tetten kell, hogy érjem.}
{206}{}{Nem probléma.}

{207}{mcs29}{Hát, akkor azt hiszem, jobban tesszük, ha megállítjuk. Velem jössz?}
{208}{}{Aha.}
{209}{}{Nem, kösz.}

{210}{mcs30}{Azt akarod, hogy veled menjek? A fenébe is, túl öreg vagyok, hogy megállapodjak. Indulunk?}
{211}{}{Igen.}
{212}{}{Nem, még nem.}

{213}{mcs31}{Sajnos túl sok a tennivaló mostanában. Ha lecsendesednek a dolgok, talán igen.}
{214}{}{Oké. Lenne még pár kérdésem.}
{215}{}{Viszlát!}

{216}{mcs32}{Ahogy mondod. A legjobb barátom volt.}
{217}{}{Aha, persze, õt is megmerítetted volna, ahogy mindenki mást.}
{218}{}{Viszlát!}

{219}{mcs33}{A fenébe is, igen, meg kellett volna merítkeznie. Micsoda nagyszerû mutáns lehetett volna.}
{220}{}{Nem hiszem, hogy örülne, ha ezt hallaná.}
{221}{}{Viszlát!}

{222}{mcs34}{(nevet) Mindig ezen vitatkoztunk. (sóhajt) Hiányzik az öreg keményfejû.}
{223}{}{Mi a helyzet a Mester embergyûlöletével?}
{224}{}{Szerintem ez akkor is szar sors.}
{225}{}{Viszlát!}

{226}{mcs35}{Régi dolgokról beszélsz. A világ megváltozott. Szeretnéd hallani az õsi történelmet?}
{227}{}{Feltétlenül.}
{228}{}{Most nem, de lenne még pár kérdésem.}
{229}{}{Most nem. Késõbb beszélünk.}

{230}{mcs36}{Jól van. Igazából sosem utáltuk az embereket. Mást akartunk elérni. Ezek az új irányítási szervek azt hiszik, mindenre tudják a választ. Bla-bla. Voltam ott, láttam, amit láttam, megvannak a sebeim.}
{231}{}{Szóval akkor mit akartatok elérni?}

{232}{mcs37}{A Mester mindenkit a saját szintjére akart emelni, hogy ne harcoljunk többé egymással. Meg volt róla gyõzõdve, hogy magunktól nem tennénk... nem tudnánk. Fejlõdést kellett ránkerõltetni.}
{233}{}{Egyetértesz ezzel?}

{234}{mcs38}{Amíg Jacob élt, úgy gondoltam, hogy a Mesternek nincs igaza, de úgy tûnik csupán pár ember látja meg az utat és lép rá. A többiek gyáván elfutnak.}
{235}{}{Szóval egyetértesz a Mesterrel?}

{236}{mcs38a}{Jacob látta az utat és rá is lépett, ahogyan a Menedéklakó is. De nem számít, hányan lépnek az útra, a tömeg akarata mindig megsemmisíti õket, nem?}
{237}{}{Talán.}

{238}{mcs39}{A Mester egyszerûen csak azt akarta, hogy mindenki tisztán lásson. A Menedéklakó pontot tett az álom végére.}
{239}{}{Úgy tûnik, hogy egyszerre csodálod és gyûlölöd a Menedéklakót.}
{240}{}{Te is ember voltál. Hogy ítéled meg, amit a Mester tett veled?}
{241}{}{Szerinted akkor jó volt a Mester terve?}
{242}{}{Én az Eredeti Menedéklakó leszármazottja vagyok ám...}

{243}{mcs40}{Úgy van. Ha minden ember úgy harcolt volna az igazáért, mint õ, nem kellett volna a Mester tervét elõtérbe helyezni.}
{244}{}{A Mester rabszolgaságba akarta hajtani az emberiséget!}
{245}{}{Érdekes nézõpont. Mennem kell.}

{246}{mcs41}{Ne felejtsd, én ismerem azokat, akik benne voltak. Õk voltak az emberiség legjava. A tieid ezt a sztorit másképpen mesélik, nem?}
{247}{}{Ööö... talán. Ööö, szeretnék mást kérdezni.}
{248}{}{Nem igaz!}

{249}{mcs42}{Az "Eredeti Menedéklakó"? Úgy érted az, aki megölte a Mestert és felrobbantotta a medencéket?}
{250}{}{Ööö... igen.}
{251}{}{Pontosan. Akarsz esetleg tenni ellene valamit, muti?}
{252}{}{Neeem... ez más. Nem tudom, mirõl beszélsz.}

{253}{mcs43}{Nem igazán. Ahogy mondtam, az már régen volt.}
{254}{}{Nem félek ám tõled!}
{255}{}{Akkor miért utáltad az embereket régen?}

{256}{mcs44}{Nem igazán érdekel, hacsak nem kötsz bele valakibe, vagy belém a városban. Viselkedj civilizáltan, ennyit kérek csak!}
{257}{}{Észben tartom. Viszont kérdeznék valami mást.}
{258}{}{Észben fogom tartani. Viszlát!}

{259}{mcs45}{Hadd legyek világos: Semmi sem fog itt történni, hacsak nem te kezded. Csak viselkedj civilizáltan, amíg a városban vagy!}
{260}{}{Oké, persze. Viszont kérdeznék még valami mást.}
{261}{}{Oké, persze. Viszlát!}

{262}{mcs46}{Emlékeim már nem a régiek arról, hogy milyen volt embernek lenni, de amire emlékszem az kicsinyesség, gyûlölet és féltékenység... inkább vagyok mutáns.}
{263}{}{Szerinted akkor jó volt a Mester terve?}
{264}{}{Hú, így sokkal rondább vagy. Viszlát!}
{265}{}{Akkor légy jó! Viszlát!}

{266}{mcs47}{Hibás volt. Csak a legjobbakat kellett volna kiválasztani. Nézz körül! A legtöbb mutánsnak ahhoz sincs elég agya vagy akarata, hogy elviselje a mindennapi nyomást. (sóhaj) Bárcsak jobban válogattunk volna...}
{267}{}{Szóval Jacobot is megmerítetted volna, akárcsak a Menedéklakót?}
{268}{}{Igen, micsoda tragédia. Hát, minden jót!}

{269}{mcs48}{Ha valaha is visszamész, mondd meg nekik, hogy a háborúnak vége! Már nagyon régen.}
{270}{}{Ööö, rendben. Szeretnék valami mást kérdezni.}
{271}{}{Tiszta sor. Viszlát!}

{272}{mcs49alt}{Kösz a segítséget! Gondok lehettek volna belõle. Elvettük a fegyvereiket és szétszereltük a bombáikat.}
{273}{}{Nagyszerû! Lenne néhány kérdésem...}

# Not using
{274}{}{Hé, találtam valamit.}

# Not using
{275}{}{Nem találtam semmit.}

# I'm leaving you responses
{276}{mcs103a}{Túl sokan vagytok. A hordával való utazás az én életemben már megvolt.}
{277}{mcs103b}{Azt hittem, a jó oldalon állsz. Nem megyek veled.}
{278}{mcs103c}{Sajnálom, de most nem megyek veled. [lekicsinylõen végigmér]}
{279}{}{Rendben.}

# 104. Fear/Defeat Floats, are we using?
{280}{}{Ez még a szart is kiijesztette belõlem.}
{281}{}{Nem sok minden tud megrémíteni a pusztában... ennek sikerült.}

# 105. Victory Floats, are we using?
{282}{}{Ha meg akarsz támadni, pont olyan hülye vagy, mint amilyennek látszol.}
{283}{}{Szétrúgtunk pár segget... megin'.}
{284}{}{Ez túl könnyû volt.}

# 106. Combat Taunt Floats, are we using?
{285}{}{Nincsenek barátaid, akik ki tudnának segíteni ebbõl?}
{286}{}{Elég lesz már?}

# 107. Skill use Success Confirm Float, are we using?
{287}{}{Kész. Ahogy akartad.}

# 108. Skill use Failure Confirm Float, are we using?
{288}{}{Hmmm. Valami nem stimmel.}

# 109. Rejoin Party, NEEDED. Waiting for Voc file.
{289}{mcs109}{Visszaveszel?}
{290}{}{Aha.}
{291}{}{Most nem. Viszlát!}

# 110. NPC in party
{292}{mcs110}{Mit akarsz?}
{293}{}{Hogy érzed magad?}
{294}{}{Gyógyítsd meg magad!}
{295}{}{Várj itt, amíg vissza nem jövök!}
{296}{}{Egyelõre ennyi.}

# 111. Heal Yourself
{297}{mcs111a}{Kész vagyok.}
{298}{mcs111b}{Semmi sem lassíthat le minket.}
{299}{mcs111c}{Tudsz segíteni?}
{300}{mcs111d}{Jó lenne, ha megnéznéd.}
{301}{}{Használd a képességeidet, hogy meggyógyítsd magad!}
{302}{}{Rendicsek.}
{303}{}{OKÉ}

# 112. Wait here
{304}{mcs160}{Itt maradok és megigazítom a satukat a vállamon.}
#csak nezz a kepre, valoban az van a vallan egy rakas, raadasul ez a szo csak ezt jelenti (Bass)

{305}{}{Rendben.}
{306}{}{OKÉ}

# Prases, Not using any but 2 and those are duplicated at the bottom
# Lines 317 is now 20,000 and 315 is 20,001
# Lines 307 through 348
{307}{}{Észak.}
{308}{}{Észak-nyugat.}
{309}{}{Nyugat.}
{310}{}{Dél-nyugat.}
{311}{}{Dél.}
{312}{}{Dél-kelet.}
{313}{}{Kelet.}
{314}{}{Észak-kelet.}
{315}{}{Ne kérdezz! Nem tudom. }
{316}{}{Aha.}
{317}{}{Igen.}
{318}{}{Nem.}
{319}{}{Miért beszélsz így velem?}
{320}{}{Nem túl szép.}
{321}{}{Kösz. }
{322}{}{Ez jó.}
{323}{}{Ez nem baró.}
{324}{}{Ez tetszik. Nagyon. }
{325}{}{Rossz elõérzetem van.}
{326}{}{Ezek az emberek hülyék.}
{327}{}{Nem tanultam semmit.}
{328}{}{Tanultam valamit.}
{329}{}{Van itt valaki normális?}
{330}{}{Kell lennie más útnak is.}
{331}{}{Kövess!}
{332}{}{Próbáljuk ezt!}
{333}{}{Gyere ide!}
{334}{}{Találtam valamit, amit talán használhatnál.}
{335}{}{Szerintem itt letáborozhatunk.}
{336}{}{Itt nem biztonságos letáborozni.}
{337}{}{Itt pihenhetünk.}
{338}{}{Szerencsém van.}
{339}{}{Megjavítanád ezt?}
{340}{}{Kapcsold be!}
{341}{}{Ki kellene nyitni a zárat.}
{342}{}{Ki fogod nyitni?}
{343}{}{Talán még visszajövünk késõbb.}
{344}{}{Nem értem.}
{345}{}{Nem tudom.}
{346}{}{Jaj!}
{347}{}{Ez nagyon fáj!}
{348}{}{Ez nem valami jó...}

# Player responses leading to pregnancy
{349}{}{Ööö... amikor azt mondtad a New Reno-i Cat's Paw-ban, hogy "Hát remélem, nem esett teherbe.", azt mire véljem?}
#Egyeztetve Renoval

# 113. Waiting for Vocs.
{350}{mcs113}{A szüleid nem magyarázták el?}
{351}{}{Nem, úgy értem... azt hittem, hogy a mutánsok sterilek.}
{352}{}{Hagyjuk!}

# 114. Waiting for Vocs.
{353}{mcs114}{Mi? Hol hallottad ezt?}
{354}{}{Akkor... te NEM vagy meddõ?}
{355}{}{Hagyjuk!}

# 116. Waiting for Vocs.
{356}{mcs116}{Nem. Azaz már nem. A megmerítkezés után eltart pár évig, amíg a nedvek újra mozgásba nem jönnek. Miért?}
{357}{}{Oh. Öö, mindegy.}

# Exp description
{360}{}{Leleplezted a mutánsok elleni összeesküvést Broken Hillsben.}
{361}{}{Marcus belegyezett, hogy beálljon a csapatodba.}

# Additional Player responses
{400}{}{Az elveszett emberekrõl...}
{410}{}{Jacobról és Aileenrõl...}
{420}{}{Chadról...}
{430}{}{A szökött fegyencekrõl...}
{440}{}{Egy ÚKK-s tudósról...}

# Float, Pissed
{500}{}{Kemény gyerek lehetsz, hogy újra ide mered tolni a képedet!}

# Player additional responses
{501}{}{Hagyjuk! Kérdezhetek mást?}
{502}{}{Mindegy. Viszlát!}

# Marcus floats
{600}{}{Nem érzem jól magam, fõnök.}
{601}{}{Ne tedd ezt!}
{602}{}{Nem gondolod, hogy ez a hely túl ijesztõ?}
{603}{}{Remélem, van horgászcsizmátok... mert most nagyon mély szarban fogunk gázolni.}
{604}{}{Nem tetszik nekem ez a hely.}
{605}{}{Ez a törött csont addig fog macerálni, amíg fel nem dobom a bakancsomat, fõnök.}
{606}{}{Ahh, emberiség.}
{607}{}{Na, ez egy nagyszerû példa, hogy miért volt igaza a Mesternek.}
{608}{}{És még azt hitted, hogy a mutánsok betegek.}
{609}{}{Vigyázni, fõnök! Ezek a srácok nem viccelnek.}
{610}{}{Haver... mindig elámulok rajtatok, embereken.}
{611}{}{Remélem, tudod, hova megyünk...}
{612}{}{Rúgjuk szét a seggüket, fõnök!}
{613}{}{Az ilyen seggfejektõl mindig bekattanok.}
{614}{}{Ááh, újra itthon.}
{615}{}{Ne felejtsd... én is részt vettem a város építésében. Légy jó!}
{616}{}{Otthon, édes otthon!}
{617}{}{Mindig is utáltam ezt a helyet.}
{618}{}{Mikor megyünk már?}
{619}{}{Menjünk innen!}
{620}{}{Nem hiszem, hogy szeretnek itt, fõnök.}
{621}{}{Szóval minden itt kezdõdött, mi?}
{622}{}{Gyógyulni kellene egy sort, nem?}
{623}{}{Hozd vissza, blöki!}
{624}{}{Fekszik! Jó kutya! Tettesd magad halottnak!}
{625}{}{Hé, kutya! Csibész!}
{626}{}{Hé, Lenny! Voltál már Broken Hillsben?}
{627}{}{Lenny! Gyerünk, igyunk valamit!}
{628}{}{Örülök, hogy van még egy fejlett ember a csapatban, Lenny.}
{629}{}{Hé, Myron! Szkanderozunk?}
{630}{}{Ne aggódj, kicsi Myron! Vigyázok rád.}
{631}{}{Nézzétek Myron dagadó agyát!}
{632}{}{Pfhuuu!!! Ki engedte el ezt a galambot?}
{633}{}{[fütyül] Virágom, virágom... [énekel]}
{634}{}{Haver, ezt jól megkaptam.}
{635}{}{Az én koromban, jó néha egy kicsit lelassulni.}
{636}{}{Csak a felhõket néztem...}
{637}{}{Zzzzzzzzz.}
{638}{}{Kösz, fõnök.}
{639}{}{Öö... kösz, haver.}
{640}{}{Öö... kösz. Jaja.}
{641}{}{Kösz. Elég szomjas voltam.}
{642}{}{Ááá... furcsán érzem magam.}
{643}{}{Asszem, Francisnek igaza volt Jacobot illetõen. Az a rohadt gyilkos nem csinál több galibát ebben a városban.}
{644}{}{Kaptál egy távcsöves vadászpuskát.}
# End of Floats

# Marcus Dialog, in party response
{1100}{mcs43alt}{Nem probléma.}

# Player responses
{3000}{}{Gyerünk!}
{3100}{}{Felejtsd el, hogy kérdeztem valamit, seggfej!}
{3200}{}{Nem érdekes akkor. A te bajod.}
{3300}{}{Francba! Talán majd késõbb.}

# Player responses, that should have been replaced by new party format. Keeping just to be safe
{9999}{}{Kérni akartam tõled valamit...}
{10001}{}{Végy magadhoz pár stimpakkot és gyógyítsd magad!}
{10002}{}{Marcus, maradj itt, és várd meg, míg visszajövök!}
{10003}{}{Tedd el a fegyvered!}
{10004}{}{Maradj közel!}
{10005}{}{Ne menj túl messze!}
{10006}{}{Szóródjunk szét egy kicsit!}
{10100}{}{Gye'ünk, Marcus! Ideje indulni.}
{10007}{}{Na, akkor induljunk!}


# New Marcus dialog for new party structure, waiting for Vocs, from Phrases 81 and 79
{20000}{mcs81b}{Rendben.}
{20001}{}{Heh. Majdnem minden nagyméretû fegyvert tudok használni. Rakétavetõket, gépágyúkat és a nagy energiafegyvereket is. Nem vagyok rossz pusztakézzel sem, és állati jól célzok gránáttal. Páncélt nem hordok. Az én méretemben nem készülnek.}