{100}{}{Egy furcsa, rongyosbõrû, mutáns valamit látsz, aminek rémes a mosolya.}
{101}{}{A finomító felügyelõjét látod.}
{102}{}{Egy ghoult látsz. A bõre úgy fest, mintha bármelyik pillanatban hajlandó lenne elválni gazdájától. Úgy tûnik, a többiek így is befogadták.}

{103}{}{Ide tilos bejönni!}
{104}{}{Mit akarsz?}
{105}{}{Da jagga! Ííp úúp op!}
{106}{}{Nemtom.}
{107}{}{Van nálam egy kis finomítani való érc.}
{108}{}{Ki vagy te?}
{109}{}{Mi ez a hely?}
{110}{}{Egy kis uránt szeretnék.}
{111}{}{Semmit.}
{112}{}{Felejtsd el! Pá.}

{113}{}{Figyelj, fiam, sajnálom, hogy nincs agyad, de nem maradhatsz itt. Tûnés kifelé.}
{114}{}{-vége-}

{115}{}{Nem maradhatsz itt! Veszélyes. Menj innen!}
{116}{}{-vége-}

{117}{}{Nagyszerû! 1000 dollár lesz, alku nincs. Talán drágának találod, de ez semmi ahhoz képest, amit a végtermékért kaphatsz egy megfelelõ vevõtõl.}
{118}{}{Áll az alku.}
{119}{}{1000 dollár? Ez nevetséges. Verd ki a fejedbõl!}

{120}{}{Én vagyok a finomító felügyelõje. Mit akarsz?}
{121}{}{Mi ez a hely?}
{122}{}{Van nálam némi finomítandó érc.}
{123}{}{Uránt szeretnék venni.}
{124}{}{Semmit.}

{125}{}{Ez Broken Hills finomítója. Itt tisztítjuk meg a bányából kiásott ércet. Mit akarsz?}
{126}{}{Mi ez a hely?}
{127}{}{Van nálam némi érc finomítás céljából.}
{128}{}{Szeretnék venni egy kevéske uránt.}
{129}{}{Semmit.}

{130}{}{Nincs nálad elég pénz. Gyere vissza, ha lesz!}
{131}{}{-vége-}

{132}{}{Rendben. Adj egy napot, és már viheted is.}
{133}{}{Nagyszerû! Viszlát!}

{134}{}{Sok sikert, hogy találj egy másik finomítóhelyet! A mûvelet veszélyes, csak egy profi tudja rendesen megcsinálni. Mi képesek vagyunk rá. Akarod vagy nem?}
{135}{}{Igen.}
{136}{}{Nem.}

{137}{}{Rendben. Akkor nincs itt semmi keresnivalód! Kérlek, távozz, hadd folytassuk a munkánkat!}
{138}{}{Viszlát!}

{139}{}{Ez nevetséges! Ebbõl él a város! Nem adhatunk el uránt.}
{140}{}{Akkor meghaltok!}
{141}{}{Kár. Viszlát!}

{142}{}{Hé! Menj onnan, vagy számolnod kell a következményekkel!}

{143}{}{Kifelé a finomítómból! Azonnal!}

{144}{}{Dolgozunk az érced finomításán. Kell még egy kis idõ. Ez a fajta munka nem megy tapsra.}
{145}{}{Kérdeznék pár dolgot.}
{146}{}{Rendben. Viszlát!}

{147}{}{Kész ez érced. Mielõtt elvinnéd, figyelj: a városunknak nagy szüksége van az uránra. Ha ezt nekünk adod, visszafizetem a pénzed. Mi a válaszod?}
{148}{}{Nincs üzlet.}
{149}{}{Rendben.}

{150}{}{Rendben. Úgy legyen. Itt az érced. Most pedig távozz!}
{151}{}{Viszlát!}

{152}{}{Kösz szépen! Itt a pénzed.}
{153}{}{Nem probléma.}