{100}{}{Egy bõrpáncélba öltözött, mosolygó embert látsz.}
{101}{}{Õ Steve, Broken Hills üdvözlõ embere.}
{102}{}{Egy bõrpáncélba öltözött, barátságos embert látsz. Úgy fest, egész nap itt áll, hogy beszélgethessen valakivel.}

{103}{}{Helló! A nevem Steve. Én vagyok az, akitõl megtudhatod, mi merre van ebben a helyre kis városban, Broken Hillsben. Hova szeretnél menni, vagy esetleg más segítség kellene?}
{104}{}{Daa...}
{105}{}{Borókanyíl?}
{106}{}{Mesélj nekem errõl a helyrõl!}
{107}{}{Kik élnek itt?}
{108}{}{Ki a vezetõ?}
{109}{}{Mi újság a városban?}
{110}{}{Hova lehet itt menni egyáltalán?}
{111}{}{Nem, kösz. Elnézést.}

{112}{}{Óh, anyám! A sivatag újabb nyomorék gyermeke. Na, kerülj beljebb! Meglátod, vagyunk annyira vendégszeretõk, mint bármely más város a pusztában.}
{113}{}{Jóóóóóóóóó!}

{114}{}{Valóban. Sok szerencsét, vándor, és viszlát!}
{115}{}{Viszlát!}

{116}{}{Broken Hills. Bányászváros. Dolgokat ásunk ki, és eladjuk õket.}
{117}{}{Áásunki?}
{118}{}{Ellad!}

{119}{}{Ahogy mondod. A földbõl. Van egy bányánk. Nem hiszem, hogy lenne ott munka számodra. Ha dolgozni akarsz, beszélj a karavánmesterrel!}
{120}{}{O-kké.}
{121}{}{Elad dolog?}

{122}{}{Amit kiásunk, azt eladjuk más városoknak a környéken. Szükségük van rá. Ha el akarsz adni valamit, beszélhetsz az itteni kereskedõkkel. Nekem viszont dolgoznom kell, úgyhogy legyél jó és vigyázz magadra, oké?}
{123}{}{Oh-ké! Pááá!}

{124}{}{Nekem dolgoznom kell, úgyhogy legyél jó és vigyázz magadra, oké?}
{125}{}{Megint te vagy? Tudod te, mit kell tenned: legyél jó és óvatos! Vigyázz magadra!}
{126}{}{O-kké! Páááááá!}

{127}{}{Tedd el a fegyvereidet, barátom! Nem válaszolok semmire, amíg így hadonászol velük!}

{128}{}{Ez csak egy kis bányászközösség. Marcus, a seriff, és egy Jacob nevû ember alapították pár évtizede. Azért választották ezt a helyet, mert uránérc van a közeli hegyekben. Többet szeretnél hallani?}
{129}{}{Igen.}
{130}{}{Nem.}

{131}{}{Közösségünk emberekbõl, mutánsokból és ghoulokból áll. Itt nincsenek faji elõítéletek, mint mondjuk Menedékvárosban. A mi szemünkben mindenki egyenlõ.}
{132}{}{Mutánsokkal éltek együtt? De hát nem tudjátok, hogy gonoszak?}
{133}{}{Egyenlõ?}
{134}{}{Kösz. Viszlát!}

{135}{}{Névlegesen Marcus, a seriff vezeti a várost. Segített a megalapításánál, most pedig segít a válságok leküzdésében. De valójában minden helyinek ugyanannyit ér a szava.}
{136}{}{Ez így mûködésképtelen.}
{137}{}{Ez jó megoldásnak tûnik.}
{138}{}{Folytasd!}
{139}{}{A fickó, aki a várost alapította, még most is a vezetõ? Akkor jó öreg lehet már.}
{140}{}{Kösz. Viszlát!}

{141}{}{Eltekintve attól, hogy a mutánsok mind MEGHALTAK, és így a város el van ÁTKOZVA...}
{142}{}{Eltekintve attól, hogy a mutánsok halottak, és a város egyetlen megélhetési forrása megsemmisült...}
{143}{}{Eltekintve attól, hogy te egy hõs vagy, amiért leleplezted a köztünk settenkedõ gonoszt...}
{144}{}{Eltekintve attól, hogy a gonosz köztünk jár, mivel Franc and Manson megszöktek...}
{145}{}{Eltekintve Chad árulásától, és az általad szolgáltatott igazságtól... amiért mindenki hálás...}
{146}{}{Nem túl sok. Igazán...}
{147}{}{Lenne még néhány kérdésem.}
{148}{}{Viszlát!}

{149}{}{Óh. Megint te vagy?}
{150}{}{Helló!}
{151}{}{Üdv!}
{152}{}{Többet szeretnél megtudni?}
{153}{}{Mi újság errefelé?}
{154}{}{Ki a vezetõ?}
{155}{}{Mesélj nekem errõl a helyrõl!}
{156}{}{Kik élnek itt?}
{157}{}{Miben tudsz nekem segíteni?}
{158}{}{Nem, kösz.}

{159}{}{A hegyekbõl bányászott és helyben finomított érc eladásából élünk. Többnyire Gekkóba, Menedékvárosba és az Új Kalifornia Köztársaságba szállítunk. Persze, magunknak is megtartunk belõle. Mondjam tovább?}
{160}{}{Aha.}
{161}{}{Ne!}

{162}{}{Mindenki egyenlõ. Mi mind emberektõl származunk. A külsõ alatt mindenkiben ott lakozik az ember. Azt mondani, hogy valaki csak azért gonosz, mert máshogy néz ki, tudatlanságra vall.}
{163}{}{Szerinted tehát tudatlan vagyok?}
{164}{}{Úgy van.}
{165}{}{Nem feltétlenül. Ki tudhatja, hogy a mutáns vírus nem támadta-e meg az agyát?}
{166}{}{Persze. Na, viszlát!}

{167}{}{A mi igényeinknek tökéletesen megfelel. Ráadásul Marcus nagyon korrekt.}
{168}{}{Hol találom ezt a Marcust?}
{169}{}{Viszlát!}

{170}{}{Öreg, de jól tartja magát. Tudod, õ mutáns, a mutánsok pedig tovább élnek, mint az emberek.}
{171}{}{Képesek voltatok egy MUTÁNSRA bízni a város irányítását? Ennyire hülyék vagytok?}
{172}{}{Tényleg? Azt hittem, a legtöbb így is elpusztult mostanra.}
{173}{}{Egy mutáns a seriff, mi? Gondolom, akkor a helyiek elég törvénytisztelõek. Jól ki van ez találva...}
{174}{}{Viszlát!}

{175}{}{Tehát létrehoztuk a saját kis civilizációnkat, éljük az életünket, és megpróbáljuk elkerülni, hogy Menedékváros, vagy az ÚKK fennhatósága alá kerüljünk... nincs szükségünk az õ vezetési elveikre. Ez minden.}
{176}{}{Nagyszerû! Lenne még néhány kérdésem.}
{177}{}{Kösz. Viszlát!}

{178}{}{Ha kitartasz amellett, hogy valakit meg lehet ítélni pusztán a külseje alapján, akkor igen, tagadhatatlanul tudatlan vagy.}
{179}{}{A pokolba veled, haver! TE VAGY a tudatlan!}
{180}{}{Óh, rendben. Értem már.}

{181}{}{Bárhogyis, amit mondani akartam: Légy üdvözölve Broken Hillsben!}
{182}{}{Várj!}
{183}{}{Viszlát!}

{184}{}{Ha a mutánsok bántani akartak volna minket, már réges-rég megtehették volna. Nem fognak örökké élni... igazából a többségük már kezd szenilissé válni. Egy közösség építése nem fog segíteni nekik a céljaik elérésében.}
{185}{}{Úgy van.}
{186}{}{Akkor is gonoszak.}
{187}{}{Viszlát!}

{188}{}{Minél többet beszélek veled, annál hülyébbnek érzem magam. Ilyen hozzáállással, nem leszel túl népszerû Broken Hillsben. Bocsáss meg, vár a munkám!}
{189}{}{Seggfej!}
{190}{}{Most meghalsz, seggfej!}

{191}{}{Van egy bányánk, egy ércfinomítónk, egy kocsmánk, egy hotelünk, aminek nincs tulajdonosa, szóval az emberek ingyen lakhatnak benne... egy kórházunk, egy vegyesboltunk és egy gyógyszertárunk. Az élelmet magunk termeljük.}
{192}{}{Értem. Lenne még néhány kérdésem, ha nem gond.}
{193}{}{Viszlát!}

{194}{}{Hát, sokuk valóban meghalt már. Mivel a mutánsok meddõk... ahogy hallottam... kihalófélben vannak. Akik megmaradtak, azok is kezdenek szenilissé válni. Bár Marcus nem. Az õ agya most is vág, mint mindig.}
{195}{}{Hol találom Marcust?}
{196}{}{Lenne még néhány kérdésem.}
{197}{}{Viszlát!}

{198}{}{Marcus, biztos, hogy nem akarsz itt maradni, és tovább vezetni minket?}
{199}{}{Marcus! Nincs értelme. Boldogultok most már nélkülem is.}
{200}{}{-tovább-}

{201}{}{Ne rontsd itt tovább a levegõt! Így is elég bajt okoztál.}
{202}{}{-rendben-}

{300}{}{Marcust általában a banknál találod... ami mellékesen a szigorított börtön is... esetleg a rendes börtönnél. Néha a kocsmában van, vagy otthon, de általában dolgozik.}

{301}{}{Idióta!}
{302}{}{A fene!}
{303}{}{Hurrá!}
{304}{}{Gazember!}
{305}{}{A mocskos patkány!}