{100}{}{Egy furcsa, rongyosbõrû mutáns izét látsz, aminek rémes a mosolya.}
{101}{}{A finomító felügyelõjét látod.}
{102}{}{Egy ghoult látsz. A bõre úgy fest, mintha bármelyik pillanatban hajlandó lenne leválni a gazdájáról. Úgy tûnik, a többi falubeli még így is szívesen befogadta.}

{103}{}{Nem szabadna itt lenned!}
{104}{}{Mit akarsz?}
{105}{}{Da jagga! Íp úp op!}
{106}{}{Nemtom.}
{107}{}{Van nálam egy kis érc finomítás céljából.}
{108}{}{Ki vagy te?}
{109}{}{Mi ez a hely?}
{110}{}{Egy kevés uránt szeretnék.}
{111}{}{Semmit.}
{112}{}{Felejtsd el! Üdv!}

{113}{}{Figyelj, fiam, sajnálom, hogy nincs agyad, de nem lehetsz itt. Sipirc kifelé!}
{114}{}{-vége-}

{115}{}{Nem maradhatsz itt. Veszélyes. Menj innen!}
{116}{}{-vége-}

{117}{}{Nagyszerû! 1000 dollár lesz, alku nincs. Talán drágának találod, de ez semmi ahhoz képest, amit a végtermékért kaphatsz egy megfelelõ vevõtõl.}
{118}{}{Áll az alku.}
{119}{}{1000 dollár? Ez nevetséges. Felejtsd el!}

{120}{}{Én vagyok a finomító felügyelõje. Mit akarsz?}
{121}{}{Mi ez a hely?}
{122}{}{Van nálam némi finomítandó érc.}
{123}{}{Uránt szeretnék venni.}
{124}{}{Semmit.}

{125}{}{Ez Broken Hills finomítója. Itt tisztítjuk meg a bányából kitermelt ércet. Mi járatban vagy?}
{126}{}{Mi ez a hely?}
{127}{}{Van nálam némi érc finomítás céljából.}
{128}{}{Egy kevés uránt szeretnék venni.}
{129}{}{Semmit.}

{130}{}{Nincs nálad elég pénz. Gyere vissza, ha lesz!}
{131}{}{-vége-}

{132}{}{Rendben. Adj egy napot, és már viheted is!}
{133}{}{Nagyszerû! Viszlát!}

{134}{}{Sok sikert, hogy találj egy másik finomítóhelyet! A mûvelet veszélyes, csak egy profi tudja rendesen megcsinálni. Akarod vagy nem?}
{135}{}{Igen.}
{136}{}{Nem.}

{137}{}{Rendben. Akkor nincs itt semmi keresnivalód. Kérlek, távozz, hadd folytassuk a munkánkat!}
{138}{}{Viszlát!}

{139}{}{Ez nevetséges! Mi nem adunk el uránt.}
{140}{}{Akkor meghaltok!}
{141}{}{Kár. Viszlát!}

{142}{}{Hé! Menj onnan, vagy számolnod kell a következményekkel!}

{143}{}{Kifelé a finomítómból! Azonnal!}

{144}{}{Még dolgozunk az érced finomításán. Kell még egy kis idõ. Ez a fajta munka nem megy tapsra.}
{145}{}{Kérdeznék pár dolgot.}
{146}{}{Rendben. Viszlát!}

{147}{}{Kész ez érced. Mielõtt elvinnéd, figyelj: a városunknak nagy szüksége van az uránra. Ha ezt nekünk adod, visszafizetem a pénzed. Sõt, ha pénz kérdése az egész, akkor meg tudom toldani még 500 dollárral, hogy megérje neked. Kérlek! A bányában történtek után Broken Hillsnek nagy szüksége lenne rá. Mi a válaszod?}
{148}{}{Nincs üzlet.}
{149}{}{Persze. Ne törõdj az 500-zal se, nektek talán jobban kell, mint nekem!}

{150}{}{Rendben. Úgy legyen. Itt az érced. Most pedig távozz!}
{151}{}{Viszlát!}

{152}{}{Kösz szépen! Itt a pénzed. Broken Hills nem fogja ezt elfelejteni neked.}
{153}{}{Örülök, hogy segíthettem.}

{154}{}{Mondtam, hogy menj innen!}

{155}{}{...a kis mocskok bejönnek ide és [morgolódik, panaszkodik]...}

{156}{}{Plusz 500? Persze, elfogadom.}

{157}{}{Köszönöm! Itt a pénzed és a plusz 500 dollár.}
{158}{}{Szuper! Kösz.}

{159}{}{Felfedezted, hogyan lehet uránércet finomíttatni Broken Hillsben.}
{160}{}{Visszaadtad a finomított ércet Broken Hills városának.}
{161}{}{Eladtad a finomított ércet Broken Hills városának.}