{100}{}{Egy öreg ghoult látsz.}
{101}{}{Õ Typhon, Set fia.}
{102}{}{Egy öreg ghoult látsz, szemében intelligencia fénylik.}
{103}{}{Helló, ifjonc! Légy üdvözölve a Öreg Ghoulok Otthonában!}
{104}{}{Reg gúl?}
{105}{}{Öreg Ghoulok Otthona?}
{106}{}{Mi a neved?}
{107}{}{Halott valaha az ÉLET-rõl?}
{108}{}{Viszlát!}
{109}{}{Még egy fejreejtett, he? Hé, kölyök, akarsz tudni egy nagy titkot?}
{110}{}{Ige!}
{111}{}{Ne-ehm.}
{112}{}{Még fiatal koromban sok versenyt megnyertem. Jó sok pénzt kaszáltam vele. Még régebben elrejtettem mindet a közelben. Ha megtennél egy-két szívességet nekem, talán elmondanám, hol van a "kincs".}
{113}{}{Mondja el!}
{114}{}{Nem érdekel.}
{115}{}{Milyen kincs?}
{116}{}{Milyen szívességre gondol?}
{117}{}{Mást kérdeznék inkább.}
{118}{}{Viszlát!}
{119}{}{Heh. Rendben. Nincs akkor mit mondanom neked. Tûnés!}
{120}{}{Viszlát!}
{121}{}{Elõbb tenned kell nekem valamit, kölyök.}
{122}{}{Okké!}
{123}{}{Ne-ehm!}
{124}{}{Mi lenne az?}
{125}{}{Felejtse el!}
{126}{}{Öreg vagyok, nem sok mindent tehetek már. Nincs túl sok lehetõségem egy kis izgalomra sem, ha érted, mire gondolok. Szóval nem szeretnék mást, mint egy Cat's Paw magazint. Szerezz nekem egyet!}
{127}{}{Tess'! [odaadom a Cat's Paw magazint Typhonnak]}
{128}{}{Okké!}
{129}{}{Nehm!}
{130}{}{Tessék. [odaadom a Cat's Paw magazint Typhonnak]}
{131}{}{Rendben. Visszajövök még.}
{132}{}{Felejtse el!}
{133}{}{Kösz a magazint, kölök. Várj kábé egy órát és visszajövök!}
{134}{}{Oké!}
{135}{}{Még nem fejeztem be, kölyök! Tûnés! Egy öreg ghoulnak talán nem lehet magánélete?}
{136}{}{-rendben-}
{137}{}{Milyen kincs? Pénz, kölyök, rengeteg pénz. Elegendõ egy józan embernek.}
{138}{}{Mi a pálya vele?}
{139}{}{Nincs szükségem pénzre.}
{140}{}{Visszajöttél, mi? A kincsrõl szeretnél hallani, ugye kölyök?}
{141}{}{Ige'!}
{142}{}{Ne-ehm.}
{143}{}{Milyen kincsrõl van szó?}
{144}{}{Igen, mesélje el!}
{145}{}{Elõbb valami mást szeretnék kérdezni.}
{146}{}{Nem.}
{147}{}{Például?}
{148}{}{Ez az Öreg Ghoulok Otthona?}
{149}{}{Hallott valaha az ÉLET-rõl?}
{150}{}{Ki maga?}
{151}{}{Bármi egyéb, amit elmondana?}
{152}{}{Ez amolyan vicc, hiszen csak öreg ghoulok léteznek. Mind meddõk vagyunk, tudod, de nagyon sokáig élünk. Mi vagyunk a ghoulok elsõ és egyben utolsó generációja. Ez az a hely, ahol a magamfajták pihenhetnek egy kicsit.}
{153}{}{Értem. Kérdeznék valami mást.}
{154}{}{Aha. Viszlát!}
{155}{}{Typhon vagyok. Hallottál valaha Setrõl? Õ vezette a Necropolis nevû jó öreg várost. A fia vagyok. Még a nagy sugárzás elõtt születtem, szóval mutánsként nõttem fel. Nem volt más választásom.}
{156}{}{Mesélj nekem Setrõl!}
{157}{}{Set? Úgy hallottam, hogy egy nagy rohadék volt.}
{158}{}{Értem. Lenne még kérdésem.}
{159}{}{Aha. Viszlát!}
{160}{}{Igen. Régen volt pár nekem, de ellopkodták a tisztavérû emberek, hogy felépítsék a saját Édenkertjüket. Menedékvárosban jó eséllyel találhatsz egyet, vagy esetleg az ÚKK-ban, innen délre.}
{161}{}{Francba! Mindegy, mást kérdeznék inkább.}
{162}{}{A fene! Viszlát!}
{163}{}{A "nagy rohadék" megszólítás, azt hiszem, tökéletesen illik az öregre. Az, hogy a sugárzás miatt ghoullá vált, nem nagyon segített a humorérzékén vagy a hatalomvágyán. Persze a sugárzás midnenkinek megcsavarta kicsit az agyacskáját. Azt hiszem az, hogy ghoulként nõttem fel, nagyon sokat segített nekem.}
{164}{}{Értem. Kérdeznék még valamit.}
{165}{}{Kösz. Viszlát!}
{166}{}{Nos? Hoztál nekem Cat's Paw magazint?}
{167}{}{Ige'. [odaadom a Cat's Paw magazint Typhonnak]}
{168}{}{Ne-ehm.}
{169}{}{Aha. Tessék. [odaadom a Cat's Paw magazint Typhonnak]}
{170}{}{Még nem, de kérdeznék valamit.}
{171}{}{Nem.}
{172}{}{Hát akkor siess! Nagyon öreg ghoul vagyok, és én mondom neked, szükségem van egy kis kikapcsolódásra! Gyerünk, gyerünk, gyerünk!}
{173}{}{-rendben-}
{174}{}{Hát, kölyök, ez a magazin beindított egy-két dolgot bennem, és úgy érzem azért a kincsért, amirõl meséltem neked, igazán hozhatnál még néhány dolgot az öreg Typhonnak. Szerezz nekem egy felfújható gumibabát. New Renóban egészen biztos találsz egyet.}
{175}{}{Okké! Pá!}
{176}{}{Ne-ehm!}
{177}{}{Tessék! [odaadom a gumibabát Typhonnak]}
{178}{}{Rendben, de elõbb válaszoljon néhány kérdésre!}
{179}{}{Rendben. Viszlát!}
{180}{}{Na, felejtsen el!}
{181}{}{Itt van. [odaadom a gumibabát Typhonnak]}
{182}{}{Ez az, kölyök, pont ez kell! Adj néhány órát nekem, utána beszélünk. Tûnés! [nyálcsorgatva bámulja a babát]}
{183}{}{-rendben-}
{184}{}{Nem lehet egy csepp nyugalmam sem?! Tûnés! Tûnés! Mars!}
{185}{}{-rendben-}
{186}{}{Eléggé kifáradtam. Hozz nekem egy üveg pálinkát és akkor mesélek a kincsrõl! Phil, a kocsmáros biztos tud ebben segíteni.}
{187}{}{Rendics! Pá!}
{188}{}{Nem!}
{189}{}{Tess! [odaadom a pálinkát Typhonnak]}
{190}{}{Itt van. Tessék. [odaadom a pálinkát Typhonnak]}
{191}{}{Meddig fog ez még tartani?}
{192}{}{Rendben. Viszlát!}
{193}{}{Felejtse el!}
{194}{}{Azt hiszem... óh, már csak egyetlen egy dolgot kérnék. Elmondom, mi az, amint meghoztad a pálinkát, rendben?}
{195}{}{Oké. Hozom már.}
{196}{}{Felejtsen el!}
{197}{}{Pont ez kellett, kölyök! Még egy növényt szerettem volna kérni tõled, de inkább hagyjuk.}
{198}{}{Köszike!}
{199}{}{Kösz. Akkor kérdeznék valamit.}
{200}{}{Kösz. Viszlát!}
{201}{}{Megtaláltad már a kincset, kölyök?}
{202}{}{Ne-ehm.}
{203}{}{Még nem.}
{204}{}{Nem, de lenne pár kérdésem.}
{205}{}{Nem. Pá!}
{206}{}{Hát, keresem, keresem. Valamikor majd csak megkapja...}
{207}{}{Oké.}
{208}{}{Gondolom. Viszlát!}
{209}{}{Na, mit szólsz a kincshez, kölyök?}
{210}{}{Rossz! Kupakok!}
{211}{}{Kupakok ezrével! Értéktelen!}
{212}{}{Ha ha. Nagyon vicces. Lenne pár kérdésem.}
{213}{}{Hagyjuk!}
{214}{}{Beee! Pá!}
{215}{}{Mi? Már nem kupakokat használnak pénzként? Azt mondod, hogy minden, amit gyûjtögettem, rejtegettem  és aggódtam miatta hiába volt? Az isten VERJE MEG! Sajnálom, hogy ennyit dolgoztattalak emiatt, kölyök. Ha tudtam volna...}
{216}{}{Rendbe' van. Pá!}
{217}{}{Aha. De sebaj, ez volt az utolsó tévedése, vén ghoul. Ideje meghalni!}
{218}{}{Mással is megtörténhetett volna. Lenne pár kérdésem.}
{219}{}{Persze, persze. Jól van. Viszlát!}
{220}{}{Gondolom, tényleg nem tehet róla. Viszlát!}
{221}{}{Jó. Hol pénz?}
{222}{}{Huu, Typhon. Olyan figyelmes vagy! Szóval, hol a pénz?}
{223}{}{Oké. Úgy emlékszem, valahol a belvárosban rejtettem el, sok-sok éve már. Épületeket húztak fel azóta, sõt többször újjá is épültek, szóval nem tudom, pontosan hol lehet. Ha az segít valamit, úgy emlékszem, olyan helyre tettem, amit biztosan nem bontanak le, vagy tesz tönkre az idõ. Valami nélkülözhetetlen dolog, tudod? Sok sikert!}
{224}{}{Végre rávetted Typhont, hogy beszéljen a kincs rejtekhelyérõl.}

# Typhon/Seymour Floats.
{300}{}{De a hegeli dialektika nem foglalkozik a...}
{301}{}{Hegel, Hegel, Hegel! Mindig Hegelrõl beszélsz!}
{302}{}{És akkor a nõ azt mondta: "Az ott nem nyúl, atyám!"}
{303}{}{Ha ha ha ha!}
{304}{}{És az elsõ proton azt mondta, "Igen, én pozitív vagyok!"}
{305}{}{[reccs] Ez olyan rossz volt, hogy mindjárt elhervadok.}
{306}{}{Nem könnyû zöldnek lenni.}
{307}{}{Mesélj róla!}
{308}{}{De ez teljesen nyilvánvalóan filozófiai zsákutca!}
{309}{}{Csak azért mondod ezt, mert nem vizsgáltad meg az összes leágazását. Figyelj, ha...}
{310}{}{Kérsz gyümölcsöt?}
{311}{}{Etess, Seymour!}
{312}{}{Agy... aaaaaagy... bocs, régi szokás.}
{313}{}{Semmi baj. Nekem nincs, emlékszel?}
{314}{}{Hát, a trágya határozottan kellemes, de nincs jobb egy kiadós rothadó tetemnél komposzt gyanánt.}
{315}{}{Szóval ezért akartál idejönni?! Ingyenélõ.}
{316}{}{Szerintem nincs jobb, mint egy kiadós, gyors futás.}
{317}{}{Érzed, ahogy a szél átsuhan a hajfürtjeiden, mi?}
{318}{}{Évek óta nem voltam már beporozva!}
{319}{}{Képzeld el! Bezárva EBBE a testbe! Semmi mozgás! Semmi akció egyáltalán!}
{320}{}{Talán ha megpróbálnád a fotoszintézist...}
{321}{}{Nem felelek az evolúciós gyökereimért, te zöld fattyú!}
{322}{}{Pfhûûûû! Remélem, fel tudod dolgozni a metánt!}
{323}{}{A leveleim! Szegény kicsi leveleim! Aaaaah!}
{324}{}{Szeretem ezt a helyet. Azt hiszem, itt gyökeret verek.}
{325}{}{Jól van, elég már a növényviccekbõl, haver!}
{326}{}{Vajon hogy vannak az arroyói kuzinjaim? Remélem, szépen virágzanak.}
{327}{}{Hát persze! Hacsak nem gyomlálta ki õket valaki.}
{328}{}{Hát, azt hiszem megyek és kinyitok egy ajtót vagy valami ilyesmi...}
{329}{}{Azt hiszem szembefordítható hüvelykujj-irigységben szenvedek.}
{330}{}{Szerintem te nem látod a fától az erdõt...}
{331}{}{Aaaaaaaaaaaaaagh! Elegem van a növényviccekbõl!}
{332}{}{Nézd csak a termést azokon a búzaszárakon! Vú-hú!}
{333}{}{Nyugi! Nem hinném, hogy meg tudnád emészteni.}
{334}{}{Olvassak neked valamit?}
{335}{}{Mondjuk az Égigérõ paszulyt, vagy a Zabhegyezõt?}
{336}{}{Egy ÉLET? Persze! Volt az a fickó, aki...}
{337}{}{Pszzz! Psszt! Valaki hallgatózik!}
{338}{}{Ez az élet nagy körforgása... az élet élettel táplálkozik, ami szintén élettel táplálkozik...}
{339}{}{Aha. De TE trágyát eszel. Pssszz... növény-filozófia...}
{340}{}{Játszhatok majd az erõpáncéloddal valamikor?}
{341}{}{Arra az ócskaságra gondolsz, amit a szekrényben tartok? He-he...}
{342}{}{Igen, én is hímnõs vagyok.}
{343}{}{Nincs abban semmi rossz.}