{100}{}{Egy nagy gépezet.}
{101}{}{A légtisztító nyikorgó és csattogó hangokat ad. Úgy tûnik, lerobbant. Talán egy alkatrész hiányzik...}
{102}{}{A légtisztító csedesen zümmög. Úgy tûnik, most már tökéletesen mûködik.}

{110}{}{Ezzel az alkatrésszel nem tudod megjavítani.}
{120}{}{Megjavítottad a légtisztítót.}
{125}{}{Tönkretetted a légtisztítót.}
{129}{}{Az összeesküvõk már nem tudják mûködésbe hozni a detonátort. Használhatatlan, ezért eldobod.}
{130}{}{Már megjavítottad.}
{131}{}{Klank}
{132}{}{Nyikor}
{133}{}{Klenk}
{134}{}{Vhirrrrrrrr}