# 0. QUICK LOOK
{100}{}{Árnyékban-Járó-t látod.}

# 0. LOOK
{150}{}{Egy izmos benszülöttet látsz, akinek fekete sebhelyek borítják az arcát. Csendben figyel téged.}
{151}{}{Arnyékban-Járót-t látod. Az arca tele van karcolt törzsi tetoválásokkal.}

# 1. CLICK ON HIM (WTG)
{200}{}{::Csak némán bámul rád.::}
{201}{}{::Csendben figyel téged.::}

# WABBITS
{300}{}{Psszt... Nyúlhra vhadászom.}