{100}{}{Egy izmos, id?sebb n?t látsz, aki megviselten mosolyog.}
{101}{}{Ardin Bucknert látod, a Buckner ház tulajdonosát.}
{102}{}{Egy nagyon fitt és vidám n?t látsz, aki a korai ötvenes éveiben jár.}
{110}{}{Megtaláltad Smileyt, nagyon köszönöm! Már kezdtem azt hinni, hogy meghalt. Nagyon haragszom rá! Most, hogy ? már itt van, nem lesz szükségünk Sulikra.}
{111}{}{Gekkó harapja Smiley. Smiley áúú.}
{112}{}{Örülök, hogy segíthettem és örülök, hogy elengedik Sulikot.}
{113}{}{Szerintem jobban örül magának, mint a gekkóknak. Lenne pár kérdésem magához.}
{114}{}{Ne haragudjon rá nagyon! ? sem igazán élvezte a helyzetét. Viszlát!}
{120}{}{Hallom, hogy ártottál a fiamnak, Torrnak. Nem tudom pontosan, mi történt, de nem akarlak a közelemben látni! Takarodj innen!}
{130}{}{Üdvözlet! A nevem Ardin Buckner, ez pedig a Buckner ház.}
{131}{}{Hümmpf.}
{132}{}{Szép, szép ház.}
{140}{}{A fiamra, Torr-ra emlékeztetsz. Ti ketten biztos jól kijönnétek egymással. Miért nem mész és beszélsz vele? Viszlát!}
{150}{}{Üdvözlet! A nevem Ardin Buckner és ez az én házam. Mondd csak, nem láttál egy Smiley nev? prémvadászt a városon kívül? (Félig magának mondja) Túl rég óta ment el. Nem kellett volna elengednem arra a hülye küldetésére.}
{151}{}{Smiley? Nem, nem találkoztam ilyen nev? prémvadásszal. Meséljen nekem róla!}
{152}{}{Valami másra lenne szükségem.}
{153}{}{Most mennem kell. Viszlát!}
{160}{}{Arról a lányommal, Maidával kell beszélned. Az utóbbi id?ben nem követtem nyomon az eseményeket. Az is elég nekem, hogy az üzletre figyeljek.}
{161}{}{Oké, azt fogom tenni. Most viszont szükségem van némi információra valami másról.}
{162}{}{Hát, akkor err?l megkérdezem ?t is. Viszlát!}
{170}{}{Jobban teszed, ha itt nem csinálsz bajt. Mit akarsz?}
{171}{}{Miben segíthetek, barátom?}
{172}{}{Meséljen nekem Smileyról, a prémvadászról!}
{173}{}{Azon gondolkoztam, tudna-e nekem mesélni a helyi hírekr?l és eseményekr?l.}
{174}{}{Ki szeretnék venni egy szobát.}
{175}{}{Kivennénk egy szobát.}
{176}{}{Vennék valamit.}
{177}{}{Nincs már semmi másra szükségem ebben a pillanatban. A viszontlátásra!}
{180}{}{Nos, Smiley és én kezdtünk egyenesbe jönni. Már azt gondoltam, hogy sikerült meggy?znöm arról, hogy itt telepedjen le és segítsen vezetni ezt az üzletet. De azt mondta, hogy van még egy utolsó küldetése.}
{181}{}{Küldetése?}
{190}{}{Én csak a szobákkal foglalkozom. Ha venni, vagy cserélni akarsz, beszélj Maidával, a lányommal!}
{191}{}{Ó, értem. Akkor beszéljen nekem valami másról!}
{192}{}{Kösz. Viszlát!}
{200}{}{Tele vagyunk. Sajnálom.}
{201}{}{Nos, nézzük csak. Van egy szabad szobánk 25 dollárért.}
{202}{}{Rendben. Itt a 25 dollár. Köszönöm.}
{203}{}{Most nincs erre szükségem. Hadd kérdezzek valami másról!}
{204}{}{Azt hiszem, mégsem kell szoba. Viszlát!}
{210}{}{Attól félek, nincs elég pénzed.}
{211}{}{Upsz. Azt hiszem, kicsit leégtem. Hadd kérdezzek valami mást!}
{212}{}{Sajnálom. Jobb lesz, ha megyek és keresek még egy keveset. Viszlát!}
{220}{}{Köszönöm szépen. Annyira örülök, hogy segítettél megtalálni a fiamat. Már azt hittem, sosem látjuk többet.}
{221}{}{Torr barát.}
{222}{}{Örülök, hogy segíthettem.}
{223}{}{Nem említett valamiféle jutalmat?}
{230}{}{Well, thank you. I think you might need someone with a few more smarts to help look after you -
 a traveling companion. I'll talk to Maida about freeing up Sulik.}
{231}{}{Hát, nem is tudom, mivel tudnánk neked megköszönni.}
{232}{}{Torr barát }
{233}{}{Nincs szükség hálára. Segítség kellett és én ott voltam.}
{234}{}{Hát, pénzzel szépen ki lehet fejezni a hálát.}
{235}{}{Ha el tudná engedni Sulik tartozását, az elég lenne jutalomnak.}
{236}{}{. Sulik barát?}
{240}{}{Beszélek Maidával és ? majd minden Sulikkal kapcsolatos ügyet elrendez. Jobb lesz, ha err?l vele is beszélsz.}
{241}{}{Maida szabadít Sulik. Maida }
{242}{}{Köszönöm szépen. Biztos vagyok benne, hogy Sulik hálás lesz, amiért elengedik a tartozását. Megyek és beszélek Maidával. Viszlát,}
{243}{}{Örülök, hogy Sulikra nincs már szükségük. Lenne még valami, amir?l megkérdezném.}
{244}{}{ barát.}
{250}{}{Nincs sok pénzem, de itt van 100 dollár. Bárcsak több lenne, de sok Brahminunk elt?nt és csak ennyit engedhetünk meg magunknak. Sajnálom.}
{251}{}{Köszönöm, Ms. Buckner. Viszlát!}
{252}{}{Talán valami más jutalmat kéne választanom.}
{260}{}{Hát, biztos van valami módja, hogy megmutassam, milyen hálás is vagyok. Hmm, szemet hunyok Sulik tartozása felett. Most már szabadon távozhat. Talán mégsem olyan bajkever?k ezek a törzsbéliek.}
{261}{}{Jól hangzik. Viszlát!}
{262}{}{Hmm, talán egy másik jutalom jobb lenne.}
{270}{}{Nem is tudom, mit gondoljak. A fiam, Torr, elt?nt. Örülnék, ha lenne valaki, aki segítene nekem megtalálni ?t. Még soha nem t?nt el ennyi id?re.}
{271}{}{Torr?}
{272}{}{Mi történt?}
{273}{}{Ez szép és jó, de szükség lenne valamire.}
{274}{}{Látom elfoglalt. Majd kés?bb visszajövök.}
{280}{}{Múlt éjjel elment. Mérges lettem rá, miután azt a pár brahmint is elvesztettük. Nem engedhetjük meg, hogy még többet elveszítsünk, de ? csak a bogáremberekr?l tudott beszélni, amik elvitték ?ket. Az a bolond kölyök...}
{281}{}{Torr megy?}
{282}{}{Szerintem a Duntonoknak közük van az elt?nt brahminokhoz. Nem szabadna mérgesnek lennie Torr-ra. Mégis hova mehetett?}
{283}{}{Maga szerint hova mehetett?}
{290}{}{Hát, mindig azt mondogatta, hogy megy és elkapja a bogárembereket ott, ahol élnek. Keletre van egy kanyon. Mostanában fura zajok jöttek abból az irányból.}
{291}{}{Zajok?}
{300}{}{Köszönöm, hogy elvállaltad a fiam megkeresését. Remélem, megtalálod. Nagyon aggódom érte. Kérlek, siess!}
{301}{}{Oké.}
{310}{}{Megtaláltad már a fiamat? Nem tudom, meddig bírhatja egyedül. Kérlek, találd meg ?t nekem!}
{311}{}{Torr?}
{312}{}{Még nem adtam fel, de el?bb szükségem lenne pár dologra.}
{313}{}{Csak meg akartam nézni, hogy visszajött-e már. Megyek és folytatom a keresést. Viszlát!}
{320}{}{Torr biztos volt benne, hogy a bogáremberek, amik elviszik a brahminokat, onnan jönnek. Azt is mondta, hogy bebizonyítja nekünk. Remélem, valaki visszahozza nekem az én fiamat.}
{321}{}{Torr kanyon.}
{322}{}{Nem megy Torr.}
{323}{}{Úgy t?nik, a kanyonban kéne kezdeni a keresést. Megyek és megkeresem a fiát, Mrs. Buckner.}
{324}{}{Szívesen segítenék, ha nem lenne még annyi más dolgom. Biztos vagyok benne, hogy Torr egyedül is boldogulni fog. Viszlát!}
{325}{}{ megy Torr.}
{330}{}{? küldetésnek nevezte. Azt mondta, sejti, honnan jönnek az aranygekkók és ki akarta deríteni, hogy igaza van-e. Úgy gondolta, valami b?vös forrásból, vagy egy eldugott barlangból, vagy valamiféle bunkerb?l jönnek.}
{331}{}{Hmmm.}
{340}{}{Hát, nem tudom, pontosan mit is mondott, de nagyon izgatottnak látszott. Nem kellett volna elengednem. Két héttel ezel?ttre jelezte az érkezését és már aggódom kissé.}
{341}{}{Szívesen segítenék. Megkereshetem a kedvéért.}
{342}{}{Sajnálattal hallom. Kérdeznék inkább valami mást.}
{343}{}{That's too bad, Mrs. Buckner. Maybe he just ran out on you. I think I know why he would, too.
 Goodbye.}
{350}{}{Ó, köszönöm. Hadd jelöljem be a térképeden a helyet, amir?l beszélt. Nagyon remélem, hogy megtalálod. Nem egy világsztár, de még mindig szeretem, és jobban hiányzik, mint valaha is gondoltam, hogy fog. Kérlek, találd meg ?t nekem.}
{351}{}{Megteszem, amit csak tudok. El?bb viszont kérdeznék még valamit.}
{352}{}{I'll do my best, Mrs. Buckner. Goodbye.}
{353}{}{Azt hiszem, mégsem tudok magának segíteni. Viszlát}
{360}{}{Megtaláltad már az én Smileymat?}
{361}{}{Sajnálom, Mrs. Buckner. Még mindig keresem. Lenne még pár kérdésem viszont.}
{362}{}{Nem, még csak most fogom elkezdeni a keresését. Viszlát}
{370}{}{Biztos valami borzalmas dolog történt a fiammal, Torr-ral. Számítottam rád (zokog), hogy még id?ben megtalálod. Az a szegény, együgy? fiú. El sem hiszem, hogy rád számítottam.}
{371}{}{Bárcsak tudtál volna segíteni a fiam keresésében. Olyan gyengéd lélek volt és most már biztosan halott. Nagyon fog hiányozni.}
{372}{}{Sajnálom, Mrs. Buckner. Mindent megtettem, hogy megtaláljam. Ömm, lenne valami, amire szükségem van.}
{373}{}{Talán visszahozhatom, ami megmaradt bel?le. Viszlát!}
{374}{}{Torr? Ki Torr? (vonogatod a vállad) Viszlát!}
{375}{}{Sajnálom, segíteni akartam, de nem tudtam. Ööö, utálom ilyenkor megemlíteni, de szükségem lenne valamire.}
{376}{}{Talán kicsit kés?bb kéne visszajönnöm. Viszlát!}
{380}{}{Hát, ez egyáltalán nem lep meg. Te jó ég, kiabáltam szegény fiammal, amikor nem is az ? hibája volt. (zokog) Elkapom azokat a Duntonokat. Most túl messzire mentek.}
{381}{}{Sajnálom. Maga szerint hova mehetett Torr?}
{390}{}{Oké.}
{400}{}{What? My Smiley is...}
{401}{}{Who? Did I say Smiley? Oh, uh, no. I don't know where he went. Uh, say, let me ask you about something else.}
{402}{}{Yes, he's dead. He was eaten by geckos.}
{403}{}{I was just joking. I, uh, saw him. He said he was running off with another woman. Whoa! Look at the time. I've gotta run.}
{404}{}{Öö, én, öö, mi, azaz... Öö, nem. Még mindig keresem. Pár nap múlva biztos felbukkan. Öö, viszlát!}
{410}{}{Eaten by geckos? I just don't believe you. Geckos would never catch my Smiley, he's too good a trapper for that. You must be mistaken.}
{411}{}{Igaz, biztosan igaza van. Bocsánat az ijesztgetésért. Hadd kérdezzek valamit!}
{412}{}{Nem, én láttam, vagy legalábbis, ami megmaradt bel?le. Nem volt valami szép látvány. Hát, kés?bb találkozunk. Viszlát!}
{413}{}{Hát, megfogott. He-he, csak vicceltem. Igen, csak vicc volt. Na, akkor... viszlát!}
{500}{}{Azt hiszem, a Duntonok lopják a brahminjaikat. Gondoltam nem árt, ha tudja.}
{510}{}{Nem láttál a városon kívül egy prémvadászt, akit Smileynak hívnak? (félig magának) Túl régóta ment el. Nem kellett volna elengednem arra a hülye küldetésére.}
{520}{}{Nagyon segít?kész volt. Köszönöm.}
{530}{}{Arra lennék kíváncsi, mi egyéb történik még a városban.}
{600}{}{Csodálatos vagy.}
{610}{}{Csodálatos vagy. Visszahoztad Torrt és Smileyt. Nem tudok elég hálás lenni.}
{620}{}{Megtaláltad a fiam, Torrt. Nagyon hálás vagyok érte.}
{630}{}{Te vagy az, aki megtalálta Smileyt. Köszönöm, nagyon köszönöm.}
{640}{}{Boldog vagyok, hogy segíthettem maguknak. Kár lett volna elveszíteni két ilyen embert, akik olyan közel állnak magához.}
{650}{}{Torrnak csak segítségre van szüksége néha. Örülök, hogy én segíthettem neki.}
{660}{}{Smileynak most szerencséje volt. Mondja meg neki, hogy legközelebb legyen óvatosabb!}
{670}{}{Boldog vagyok, hogy segíthettem, Mrs. Buckner. Hadd kérdezzek valamir?l!}
{680}{}{Gurrrrg bluup?}
{690}{}{Nem tesz semmit. Viszlát!}
{700}{}{Torr meghalt.}
{710}{}{Smiley meghalt.}
{720}{}{Én, öö, én nem tudom, hol lehetnek. Mondja csak, kérdezhetek valamit?}
{730}{}{Mind a ketten olyan halottak, mint annak a rendje.}
{740}{}{Torr elment? Mit értesz ez alatt?}
{750}{}{Nem tudom, hol lehet. Hadd kérdezzek valamit, talán visszajönnek, amíg beszélgetünk.}
{760}{}{Még mindig keresem ?ket. Jobb lesz, ha folytatom. Viszlát!}
{770}{}{Még mindig keresem, jobb is lesz, ha folytatom tovább. Viszlát!}
{780}{}{Én öö, nem tudom, hol van. Hmm... a mindenit, már ennyi az id??! Mennem kell.}
{790}{}{Lenne pár kérdésem magához.}
{800}{}{Hát, sok a munkám. Viszlát!}
{810}{}{Urrrrrgh.}
{900}{}{Megtaláltad már a fiamat, Torrt? Már nagyon aggódom miatta.}
{910}{}{Megtaláltad már az én Smileymat?}
{920}{}{Megtaláltad már a fiamat, Torrt, vagy a barátomat, Smileyt, a prémvadászt?}
{930}{}{Én szegény kis Torrom elfutott.}
{940}{}{Nem hiszek neked.}
{942}{}{Ó, pedig igaz. Mostanra már biztosan mindkett?jüket a kukacok zabálják... legalábbis azt a részüket, amib?l nem lett gekkószar. Hát ez van. Na, isten áldja! }
{943}{}{Öö, azt hiszem, ez rossz *vicc* volt, sajnálom.}
{950}{}{Nem akarok veled szóba állni!}
{951}{}{Takarodj ki innen!}
{952}{}{Francos törzsbéliek. Semmit nem tudnak, csak bajt keverni.}
{953}{}{T?nj el a szemem el?l, te barbár!}
{954}{}{Nem szeretjük a te fajtádat errefelé.}
{955}{}{Nem kapsz t?lem semmit, törzsbéli!}
{956}{}{Már így is elég nagy a fájdalom itt.}
{957}{}{Csak hagyj békén!}
{958}{}{Törzsbéli bajkever?, takarodj a házamból!}
{959}{}{Elég volt bel?led! Takarodj!}
