# Dialog Editor last position: 59
{100}{}{Egy fiatal és vonzó nõt látsz.}
{101}{}{Egy fürdõkísérõt látsz.}
{102}{}{Õ Nagyorrú Sally lányainak egyike.}
{103}{}{Egy unatkozó nõt látsz.}
{104}{}{Egy nõt látsz, aki téged méreget.}
{105}{}{Ez a nõ már képzeletben levetkõztetett.}
{106}{}{Egy fiatal nõ.}
{110}{}{Ez gyors volt.}
{111}{}{Régóta volt már, édesem?}
{112}{}{Talán legközelebb tovább bírod.}
{113}{}{Ez nem verseny!}
{114}{}{A barátaid is Szélvésznek becéznek?}
{115}{}{Ha minden ügyfelem ilyen gyors lenne, sokkal korábban mehetnék haza.}
{116}{}{Sokkal izgalmasabb, ha megvárod, amíg segítek.}
{117}{}{Ha legalább megvártad volna, amíg levetkõzök...}
{120}{}{Ez jó volt. Te aztán igazi férfi vagy.}
{121}{}{Ez különleges volt. Remek vagy. Következõ!}
{122}{}{Ez az, bébi, még sosem volt ilyen jó! (ásít)}
{123}{}{Te vagy a legjobb! Gyere gyakran!}
{124}{}{Biztos vagyok benne, hogy valami törzsbéli lányt boldoggá fogsz tenni.}
{125}{}{Dehogy édesem, a méret nem számít. Igazán aranyos volt.}
{126}{}{Hát nem vagy tele égetõ szerelemmel.}
{127}{}{Milyen aranyos kis fickód van odalenn.}
{130}{}{A méret a lényeg! Az élet édes rejtélye...}
{131}{}{Ha legközelebb jössz, túlórázni fogok.}
{132}{}{Te aztán megkapod azt, amiért fizettél.}
{133}{}{A nap hátralévõ felében haza megyek.}
{134}{}{Ez igen! Neked is beremegett a föld?}
{135}{}{Na, most már tudom, mit érezhetett Catherine, a Nagy.}
{140}{}{Hát, a pénz az pénz.}
{141}{}{Ez, ömm, más volt, asszem.}
{142}{}{Ez aztán különleges volt. Következõ!}
{143}{}{Nem! Nem használhatod a parfümömet.}
{144}{}{Hát, legalább kisebb a bajuszod, mint a többi ügyfélnek.}
{145}{}{Biztos, hogy lány vagy?}
{150}{}{Ez kellemes volt.}
{151}{}{Ez más volt, de nem rosszabb, mint a megszokott.}
{152}{}{Azt hiszem, ezt még egyszer ki fogom próbálni.}
{153}{}{Ezt munka után is csinálhatnánk.}
{154}{}{Ez édes volt, mézesmackóm.}
{155}{}{Ez igen! Innentõl kezdve más lesz az életem.}
{156}{}{Nem is tudtam, hogy így is lehet.}
{160}{}{Beszélj Nagyorrú Sallyvel!}
{161}{}{Hát nem édes?}
{162}{}{Mindig imádni foglak!}
{163}{}{Néha látogass meg!}
{164}{}{Tudod, hogy kell fütyülni, ugye?}
{165}{}{Tiszta voltam, mint a hó, aztán jött a sodrás.}
{166}{}{(Farkas üvöltés)}
{167}{}{Hé, tigris!}
{168}{}{Hé, béééébi...}
{169}{}{Beszélj Sallyvel, ha izgalomra vágysz!}
{170}{}{(dudorászik)}
{171}{}{Rádférne egy mosás.}
{172}{}{Óh, egy törzsbéli! Imádom a különlegességeket.}
{173}{}{Általában nem vállalok törzsbélieket.}
{174}{}{Tetszik, amit látsz, bébi?}
{175}{}{Kívánsz?}
{176}{}{Ha játszani akarsz, fizess!}
