# Dialog Editor last position: 51
{100}{}{Ez az ember valószínûleg prémvadász.}
{101}{}{Relaxál.}
{102}{}{Egy városlakót látsz.}
{103}{}{Egy relaxáló melóst látsz.}
{104}{}{Egy embert látsz, aki éppen iszogat.}
{150}{}{Rossz fogadóban vagy, nemde?}
{151}{}{Nincs szükségünk bajkeverõkre.}
{152}{}{A törzsbéliek mindig bajt csinálnak.}
{153}{}{Csak ne igyál túl sok tüzes-vizet...}
{154}{}{(motyog, dünnyög) ...kijutni a városból...}
{155}{}{Na, még egy a Dunton bandájából.}
{156}{}{Mit bámulsz?}
{157}{}{Menj tovább!}
{158}{}{Fizess mindenkinek egy kört, jövevény!}
{159}{}{Remélem, tudsz mértéket tartani.}
{160}{}{Nem úgy nézel ki, mint egy kannibál.}
{161}{}{Itt nincs hely a te fajtádnak!}
{162}{}{Túl sok az idegen mostanában.}
{163}{}{Legalább a te fogaid nincsenek lereszelve.}
{164}{}{Ott megy a szomszédság.}
{165}{}{Nem kellene csontnak lenni az orrodban?}
{166}{}{(rádnéz, aztán csóválja a fejét)}
{167}{}{(finoman beint)}
{168}{}{Biztos te okozod a brahmin-csonkításokat.}
{169}{}{Néhány vadászunk eltûnt és biztosan miattad.}
{170}{}{Bogáremberek ijesztgetnek a városban.}
{171}{}{Egy szellem van a kanyonban, északra a várostól.}
{172}{}{Ne hagyd, hogy elkapjon a járkáló szellem!}
{173}{}{Jobban teszed, ha békén hagyod a brahminjainkat!}
{174}{}{Szemmel tartunk!}
{201}{}{De jó végre valaki újat látni a városban.}
{202}{}{Szerintem a törzsbéliek nem is olyan rosszak.}
{203}{}{Fizess egy kört!}
{204}{}{Köszönj Smileynak és a mellette ülõ Sánta Jim-nek.}
{205}{}{Te lehetnél Sulik ikertesója.}
{206}{}{Találkoztál már Sulikkal?}
{207}{}{Mostanában jól megy a vadászat.}
{208}{}{Az idõjárás hamarosan megváltozik, szerintem.}
{209}{}{Van egy jó vadászterület innen délre.}
{210}{}{Ha okos vagy, elkerülöd a Duntonokat!}
{211}{}{Ha égsz a vágytól, akkor próbáld ki a Fürdõházat.}
{212}{}{Nyugatra van a Prémvadászok Városa.}
{213}{}{Üdvözöllek, barátom.}
{214}{}{Remélem, tetszik a városunk.}
{215}{}{Klamath jó kis hely.}
{216}{}{Örülök, hogy velünk vagy.}
{217}{}{(feléd emeli a korsóját)}
{218}{}{(rádkacsint)}
{219}{}{Ne kószálj éjszaka!}
{220}{}{A hegyekben bogáremberek laknak.}
{221}{}{Eltûnt az egyik legjobb prémvadászunk.}
