# Dialog Editor last position: 74
{100}{}{Ez a vendég téged bámul.}
{101}{}{Egy vendég épp szárított húst csócsál.}
{102}{}{Ez a vendég egy korsó sörrel küzd.}
{103}{}{Vendég.}
{104}{}{Ez a vendég elég ápolatlan, bizonyára prémvadász.}
{105}{}{Ez a vendég elég keménykötésû, biztosan prémvadász.}
{106}{}{Egy megviselt vendég, talán prémvadász, vagy farmer.}
{107}{}{Ez a kocsmatöltelék jó erõben van. Talán brahmin-tenyésztõ vagy farmer.}
{110}{}{Ide tökéletesen illesz.}
{111}{}{Fizess egy kört, aszondom!}
{112}{}{Le akarod nyomni a Duntonokat?}
{113}{}{Ahogy elnézem, Rejtektõl északra éltél.}
{114}{}{Te meg mit néze'?}
{115}{}{Neked aztán sötét a bõröd szívecském. He-he-he.}
{116}{}{Hukk, jól esne még egy korsó ebbõl a gekkóhúgyból.}
{117}{}{Ha pénzt akarsz keresni, keresd meg a Duntonokat, úgy tudom, embereket keresnek.}
{118}{}{Nem is rossz egy törzsbélihez képest.}
{119}{}{'Lökd ide a sört...'}
{120}{}{Elmegyek délre, Rejtekbe, ott sok meló akad.}
{121}{}{Még egy kört ide, Salvadore!}
{122}{}{A prémvadászat nem túl jövedelmezõ mostanság, kell hogy legyen könnyebb módja a pénzszerzésnek.}
{123}{}{Nem vagyok ám olyan részeg, mint hinnéd.}
{124}{}{Hé haver, szerinted ezek a kockák cinkeltek?}
{125}{}{Ha munka kell, beszélj a Duntonokkal vagy a csapossal!}
{126}{}{Ez a legjobb hely az ivásra, cimbora!}
{127}{}{Hé, Bishop, mutasd meg, mit tudsz azzal a késsel!}
{128}{}{Akar valaki kockázni?}
{129}{}{Jó, hogy nincs itt Aldo. Így elviselhetõ a szag.}
{130}{}{Loptál már brahmint valaha?}
{131}{}{Vigyázz a Járkáló Szellemmel!}
{132}{}{Van egy szellem a kanyonban, keletre innen.}
{133}{}{A prémvadászat veszélyes, a múlt héten is elvesztettünk egy embert.}
{134}{}{Imádom szivatni Torrt.}
{140}{}{Nicsak, ki van itt.}
{141}{}{(motyog) ...belevaló ember ez... (motyog)}
{142}{}{Csak nem tévedtél el?}
{143}{}{Nem kell a te fajtád ide!}
{144}{}{Ha fizetsz nekünk egy kör piát, talán megengedjük, hogy itt maradj!}
{145}{}{Kopj le!}
{146}{}{Te meg mi a fenét bámulsz?}
{147}{}{Majd a Duntonok rendbetesznek, vadember!}
{148}{}{A lehetõ legrosszabb helyre jöttél inni!}
{149}{}{Mama nincs itt, kölyök, nézd meg a Fürdõben!}
{150}{}{Miért nem mész és játszol valahol máshol?}
{151}{}{Van egy szép kanyon innen keletre. Pont neked való.}
{152}{}{Mi kéne?}
{153}{}{Jobb, ha a magad dolgával törõdsz!}
{154}{}{Te név Torr? (he-he-he)}
{155}{}{Menj és igyál Aldóval!}
{156}{}{Ez nem neked való hely!}
{157}{}{Nem vagy az esetem, öreg!}
{158}{}{Hmmm. (a padlóra köp)}
{159}{}{Nem vagy valami nagy látványosság.}
{160}{}{Na, érzed már a vendégszeretetünk... hiányát?}
{162}{}{Épp idõben!}
{163}{}{Kösz!}
{164}{}{Ni!}
{165}{}{Eki-eki, eki-eki, potang!}
{166}{}{Kezdek ideges lenni!}
{167}{}{Nincs is jobb ennél a gekkóhúgynál!}
{168}{}{Kösz a piát!}
{169}{}{Hahó!}
{170}{}{Ti törzsbéliek aztán tudtok élni!}
{171}{}{Köszönöm!}
{172}{}{Piát mindenkinek!}
{173}{}{Ez már nagyon rámfért, kösz!}
{174}{}{Ezer köszönet!}
{175}{}{Inkább egy homloklebenymûtét...}
{176}{}{Ez aztán a pia!}
{177}{}{Ez az!}
{178}{}{Imádom ezt a piát.}
{179}{}{Te jó ember vagy.}
{180}{}{Szép lépés.}
{181}{}{Igen!}
