# Dialog Editor last position: 88
{100}{}{Ez nõ csúnyácska és erõs felépítésû. Komor a tekintette.}
{101}{}{Maida Bucknert látod, Mrs. Buckner lányát.}
{102}{}{Ez nõ csúnyácska és erõs felépítésû. Mogorván néz vissza rád.}
{200}{}{Nagyon mérges vagyok rád! Nem akarlak többet látni! Takarodj ki innen! Törzsbéliek, humph! (motyog valamit) ...ügyefogyott, haszontalan, lusta...}
{201}{}{Még idegesítõbb vagy, mint Sulik! Nincs idõm most veled beszélgetni. Menj el!}
{202}{}{Én sem akarlak többet látni. Viszlát!}
{203}{}{Sajnálom, ha megbántottalak. Nem ismerem az itteni szokásokat. Csak az otthoni szokás szerint próbáltalak köszönteni.}
{204}{}{A mindenit... úgy sajnálom. Végülis csak egy tudatlan vadember vagyok. Meg tudsz nekem bocsátani?}
{205}{}{Csak nem tudtam mit is mondhatnék egy ilyen vonzó nõnek, mint te. Mindig ideges leszek, ha meglátok egy gyönyörû nõt. Kérlek, fogadd el a bocsánatkérésem!}
{206}{}{Bocsánat. De olyan gyönyörû és mûvelt vagy, hogy féltékeny lettem. Kérlek, bocsáss meg! Oly sokat kell még tanulnom a hozzád hasonlóktól.}
{210}{}{Helló! A nevem Maida Buckner, én segítek anyámnak itt a Buckner Házban. Segíthetek valamiben?}
{211}{}{Öghh?}
{212}{}{Én }
{213}{}{Unker Hász?}
{220}{}{Hmm... úgy látszik, nem túl gyors a felfogásod. Miért nem beszélsz inkább az öcsémmel, Torr-ral? Vele jól megértenétek egymást. Viszlát!}
{230}{}{Maida Buckner vagyok. Én intézem itt az italokat és a kereskedést. Nem tûröm, ha törzsbéliek feldúlják a Buckner házat. Jobb lesz, ha megnézed hova lépsz, vagy úgy végzed, mint Sulik. Mit akarsz? }
{231}{}{Maida Bucknernek hívnak. Én intézem a kereskedést és az italokat. Mit kérsz, barátom?}
{232}{}{Helló, régi barátom.}
{233}{}{Miben segíthetek?}
{234}{}{Jobb lesz, ha megtanulsz viselkedni! Egyáltalán mi a fenét akarsz? Miben segíthetek?}
{235}{}{Lenne néhány kérdésem.}
{236}{}{Kellene egy hely, ahol aludhatnék.}
{237}{}{Vennék pár dolgot.}
{238}{}{Egy italt szeretnék.}
{239}{}{Most nincs szükségem semmire. Viszlát!}
{240}{}{Kérdések, mi? Akkor lökjed! Nem jutok elõrébb, ha veled beszélgetek.}
{241}{}{Még több kérdés? Kérdezz csak, de remélem, nem lesz sok!}
{242}{}{Hallottál már az Édenkert Létrehozást Elõsegítõ Táskáról?}
{243}{}{Mesélj nekem Sulikról!}
{244}{}{Mesélj nekem, mi történik mostanában Klamathban!}
{245}{}{Milyen települések vannak a közelben?}
{246}{}{Ennyit akartam tudni. Viszlát!}
{250}{}{Anyám végzi a szobákkal kapcsolatos ügyeket. Errõl vele kell beszélned.}
{251}{}{Oké, kösz. Azért lenne még pár kérdésem.}
{252}{}{Akkor megyek és beszélek vele. Viszlát!}
{260}{}{Csereberélni akarsz? Mindig jó árat fizetek a gekkóbõrökért.}
{261}{}{Venni akarsz valamit? Remélem, nem gekkóbõrrel akarsz fizetni, mert azzal dugig vagyunk.}
{262}{}{Igen, szeretnék csereberélni.}
{263}{}{Inkább valami más érdekelne.}
{264}{}{Most mégsem akarok üzletelni. Viszlát!}
{270}{}{Az éden megteremtése sok és nehéz munkát követel, de úgy látszik, ti törzsbéliek ezt nem tudjátok megérteni. Azt hiszem, ez különböztet meg minket, civilizált népeket tõletek.}
{271}{}{Öö, biztosan. Inkább kérdeznék valami mást.}
{272}{}{Húú, azt hiszem, sokat kell még tanulnom tõletek. Én is szeretnék civilizált lenni egyszer.}
{273}{}{Civilizált? Azt hiszed, civilizáltabb vagy nálam, csak mert egy hajdani város kiégett romjai közt élsz? Inkább beszéljünk másról!}
{274}{}{Azt hiszem, épp eleget hallottam. Viszlát!}
{280}{}{Szóval, tehetek érted még valamit?}
{281}{}{Egész életemre elég gekkóbõröm van. Akarsz még valamit?}
{282}{}{Van nálam más is, amit csencselhetnénk.}
{283}{}{Kicsit jobb árakra számítottam. Nem vagy éppen olcsó. Inkább kérdeznék valamit.}
{284}{}{Nem könnyû veled alkudozni, de megéri. Kérdeznék még valamit.}
{285}{}{Most nincs szükségem másra. Viszlát!}
{290}{}{Ott van Redding messze dél-nyugaton és néhány napnyira délre ott van Rejtek. Bár én nem mennék oda.}
{291}{}{Miért nem mennél Rejtekbe?}
{292}{}{Vannak törzsek a környéken?}
{293}{}{Kösz a jótanácsot. Lenne még egy kérdésem.}
{294}{}{Ez minden, amire kíváncsi voltam. Viszlát!}
{300}{}{Hát, a törzseket nem számoltam, mikor a városokról kérdeztél. De úgy tudom, van egy barbár horda valahol észak-nyugaton, meg persze Sulik törzse, messze innen dél-nyugatra.}
{301}{}{Ez fura, otthon a faluban mi sem számoljuk a romos városokat, amikor civilizált helyekrõl beszélünk. De lenne még kérdésem.}
{302}{}{Óó, ti aztán civilizáltak vagytok... én pedig nem kérek belõle. Inkább kérdeznék valamit.}
{303}{}{Mondj valamit Sulikról!}
{304}{}{Mi van Rejtekkel?}
{305}{}{Érdekes. Hadd kérdezzek még valamit!}
{310}{}{Rejtek nem túl jó hely. A hozzád hasonló tudatlan törzsbéliekbõl például rabszolgát csinálnak. Nagyjából egy heti út innen délre, de a legtöbben nem térnek vissza.}
{311}{}{Mondj valamit a helyi törzsekrõl.}
{312}{}{Sulik talán nem rabszolga? Különben miért bánnál vele úgy?}
{313}{}{Érdekes. Lenne még egy kérdésem.}
{320}{}{Sulik csak azért van itt, hogy ledolgozza a tartozását, amit ostoba módon okozott. De nem rabszolga! Itt Klamathban nincsenek rabszolgák.}
{321}{}{Ledolgozza a tartozását? Mit csinált?}
{330}{}{Hát, a helyzet az, hogy egyik este valamiért nagyon ideges volt és túl sokat ivott. Aztán mikor már nem bírt uralkodni magán, szétverte a berendezést. Nagyjából 500 dollárnyi kárt csinált. Még mindig nem sikerült mindent megjavítania.}
{331}{}{És mitõl volt olyan ideges?}
{340}{}{Megtudta, hogy a húgát elrabolták a rabszolga-kereskedõk. Persze errõl õt kell megkérdezned, én csak ennyit tudok. De addig úgyis itt marad, amíg le nem dolgozza a részegen okozott kárt.}
{341}{}{Mennyit kell még ledolgoznia?}
{350}{}{Még mindig tartozik 350 dollárral. Persze ha nem lenne olyan lusta és ügyetlen, akkor gyorsabban haladna. Addig nem mehet el, amíg nem rendezni a tartozását.}
{351}{}{Az jó sok pénz. Ezek szerint még sokáig marad.}
{360}{}{Lehet hogy lassú, de egy idõ után azért megkedveli az ember. (vágyakozva néz felé) ... (idegesen) De elég a fecsegésbõl. Akarsz még valamit?}
{361}{}{Érdekelne még valami.}
{362}{}{Mi lenne, ha valaki hajlandó lenne kifizetni Sulik tartozását?}
{363}{}{Más most nem érdekel. Viszlát!}
{370}{}{Nem tudom, miért akarná bárki is kifizetni a tartozását, de én nem tiltakoznék. A számlája 350 dollár. Nem hiszem, hogy tényleg ezt akarod, Sulik csak bajba keverne téged is.}
{371}{}{Nem szívesen hagynám itt egy ilyen bigott nõszeméllyel, mint te. Ki akarom fizetni a tartozását!}
{372}{}{Biztos nagyon boldog, hogy itt dolgozhat, de azért én inkább kifizetem a kárt, amit okozott. Nem tartom helyesnek, hogy helybenjárásra van kényszerítve.}
{373}{}{Talán igazad van. Amúgy sincs annyi pénzem. Viszlát!}
{380}{}{Hát, rendben, ha tényleg ki akarod fizetni a tartozását... ti törzsbéliek aztán összetartotok.}
{381}{}{Igen, ki akarom fizetni és van is elég pénzem.}
{382}{}{Tényleg sok pénzrõl van szó. Azt hiszem, tényleg nem akarok ennyit fizetni. Viszlát!}
{390}{}{Szerintem te bolond vagy. De legalább megszabadulok attól az átkozott (zokog) bajkeverõtõl. (sír)}
{391}{}{(szipog) Jó üzlet, egy idióta báty egy idióta (zokog) Sulikért. Egyáltalán nem fog hiányozni.}
{392}{}{Hát, szerintem Suliknak hiányozni fogtok. Majd néha meglátogatunk titeket, biztos vagyok benne. Most viszont szükségem lenne még valamire.}
{393}{}{Szerintem jobb lesz Suliknak nélkületek.}
{394}{}{Kösz, most már mennem kell.}
{400}{}{Viszajöttél, mi? Remélem, vigyázol Sulikra. Biztos hiányzik neki, hogy megmondjam, mit csináljon.}
{401}{}{Visszajöttem, mert szükségem lenne valamire.}
{402}{}{Hát, biztos nem tudok olyan jól vigyázni rá, mint ahogyan te tetted, de próbálkozom.}
{420}{}{Mamától kérdezd, hogy mi történik a városban!}
{421}{}{Jobb lesz, ha mamától kérdezed, mi történik mostanában a városban! Apropó, nem láttad Torrt valahol? Úgy tûnik, elmenekült, és már nagyon aggódunk.}
{422}{}{Oké, errõl akkor Mrs. Bucknert faggatom ki, de tõled még kérdeznék egy s mást.}
{423}{}{Nem láttam Torrt. Ha látom, értesítelek, most viszont lenne pár kérdésem.}
{430}{}{Kösz, hogy megtaláltad a bátyámat, Torrt. Mama és én már nagyon aggódtunk. Mit tehetek érted?}
{431}{}{Újra csak kösz, hogy megtaláltad Torrt. Miben segíthetek neked?}
{432}{}{Örülök, hogy segíthettem Torrnak.}
{433}{}{Örülök, hogy megtaláltam Torrt, de most nem kell semmi. Viszlát!}
{434}{}{Örülök, hogy segíthettem. Talán tehetnél nekem egy szívességet és kiszabadíthatnád Sulikot a bátyád megmentéséért cserében. }
{440}{}{Nem láttad valahol Torrt, a bátyámat? Elvesztett pár brahmint és mama ordibált vele. Biztos elfutott utána.}
{441}{}{Ó-ó, szerinted hova mehetett?}
{442}{}{Sajnálom, de valami másról szeretnélek megkérdezni.}
{450}{}{Hogy hova ment azt nem tudom, de biztos a kanyonba, amirõl mindig beszélt.}
{451}{}{Miféle kanyonba?}
{460}{}{Van egy kanyon innen keletre. Torr mindig vad történeteket mesélt bogáremberekrõl, amik onnan jönnek. Azt mondta, hogy a bogáremberek csonkították meg a brahminokat. A félelemtõl teljesen meghülyült.}
{461}{}{Úgy hangzik, ez bárkit meghülyített volna.}
{470}{}{Talán a kanyonba ment, hogy bebizonyítsa a bátorságát, vagy valami. Remélem, valaki rátalál, mielõtt baja esik.}
{471}{}{Esetleg megkereshetném.}
{472}{}{Tényleg sajnálom, hogy eltûnt. Biztos vagyok benne, hogy jól van. Szükségem lenne pár információra.}
{473}{}{Ki tudhatja, hogy hova tûnt az idióta testvéred... és kit érdekel? Kéne pár infó.}
{480}{}{Nagyon hálásak lennénk, ha megtalálnád a bátyámat.}
{481}{}{Szívesen megkeresem.}
{482}{}{Sajnálom, de erre most nincs idõm. Viszlát!}
{500}{}{Nagyon köszönöm. Mindent visszavonok, amit a törzsbéliekrõl mondtam. Kérlek, találd meg a bátyámat!}
{501}{}{Meg fogom, számíthatsz rám!}
{510}{}{Megtaláltad már a bátyámat? Nagyon remélem, hogy nem esett baja.}
{520}{}{Italt akarsz? Egy pohár Buckner féle sör 5 dollár lesz.}
{521}{}{Jól esne egy finom sör. Töltsd tele!}
{522}{}{Meghívnék mindenkit egy körre, csak hogy bemutatkozzam. A nevem }
{523}{}{ Arroyóból.}
{524}{}{Mégsem kérek sört. Némi infó viszont jól jönne.}
{530}{}{Egy kör rendel mindenkinek. Ejha, te aztán nagylelkû vagy. 30 dollár lesz.}
{531}{}{A vendégeim vagytok, fiúk. Most viszont lenne még hozzád pár kérdésem.}
{532}{}{Meggondoltam magam, inkább csak magamnak vennék sört.}
{533}{}{Azt hiszem, most elég lesz némi információ.}
{540}{}{Úgy tûnik, nincs elég pénzed.}
{541}{}{Nos, rendben, akkor megelégszem némi információval.}
{542}{}{Talán visszajövök, amikor több pénzem lesz. Viszlát!}
{550}{}{Boldog leszek, ha végre elmegy innen (zokog) az a szerencsétlen (zokog) Sulik. (sír) }
{600}{}{[TOVÁBB]}
