# Dialog Editor last position: 26
{100}{}{Egy nagy, rühes kutyát látsz.}
{101}{}{Ez a kutya mocskos, szõre sárgás és vastagon belepi a por.}
{110}{}{Grrrrrr. Vaú! Vaú! Grrrrrrrr...}
{111}{}{Vau, árf, árf?}
{112}{}{(A kutya szemébe nézve) Grrrrr! Árrrrr! Grrrrrrrrrr!}
{113}{}{Hmm, fogadok, hogy azért vagy mérges, mert akarsz valamit.}
{114}{}{Éhes vagy öregfiú, nemde? Hadd nézzem meg, van-e nálam fincsi szárított hús, amit neked adhatnék.}
{120}{}{Vaú! (A kutya elõreugrik a fogait vicsorítva, kikapja a húst a kezedbõl, és hangosan eszik)}
{121}{}{Vaú! (A korcs boldogan elveszi a fincsi szárított húst, de közben elejtett egy kulcsot, ami végig a szájában volt. Felveszed a kulcsot)}
{122}{}{Nyami, hús...}
{123}{}{Áh, szegény fickó, biztos nagyon éhes voltál. (Megsimogatod a fejét)}
{130}{}{Grrr. Vaú! Vaú!}
{131}{}{Árf-árf, kutyus. Hehe.}
{132}{}{Viszlát, kutyus!}
{133}{}{Bocs, de nincs nálam kutyakeksz.}
{134}{}{El innen! Takarodj innen, büdös korcs!}
{140}{}{Vaú, vaú. Vaú-vaú!}
{141}{}{Vaú, vaú? Eru?}
{142}{}{Jó kutyus, jófiú.}
{143}{}{Éhes vagy, öregfiú, nemde? Hadd nézzem meg, van-e nálam fincsi szárított hús, amit neked adhatnék.}
{200}{}{Vaú! (simi, simi, simi -- nyalás)}
{201}{}{Vaú-vaú}
{202}{}{Árf}
{203}{}{Árf, árf, árf}
{204}{}{(Szeretet-teljesen néz rád)}
{205}{}{Vaú!}
