# Dialog Editor last position: 10
{100}{}{[sírdogál]}
{101}{}{Jonny...}
{102}{}{[szipog]}
{103}{}{Hiányzik a fiam.}
{110}{}{Kérlek, kerítsd elõ Jonnyt!}
{120}{}{Kérlek, hozd vissza Jonnyt!}
{121}{}{Köszönöm, hogy Jonny újra velem lehet!}
{150}{}{A hölgy Baltha felesége.}
{151}{}{A hölgy Baltha felesége. Eléggé ki van borulva.}
{152}{}{A hölgy Balhta felesége. Úgy tûnik, elég jó hangulatban van.}
