# Dialog Editor last position: 62
{100}{}{Szép darab ember bõrkötényben.}
{101}{}{Balthas a tímár.}
{102}{}{Magas, izmos férfi, akibõl árad a cserzett bõr szaga.}
{151}{}{A fiamat véletlenül megölték a harc során.}
{152}{}{Nem tudok Jonny nélkül élni.}
{153}{}{[potyognak a könnyei]}
{154}{}{Találkozunk a Kísértetfarmon. Kicsináljuk a szellemeket!}
{155}{}{Üdv, a nevem Balthas. Enyém a modoci cserzõmûhely. Tudok segíteni?}
{156}{}{Mintha kissé elfoglalt lennél. Nincs semmi probléma?}
{157}{}{Szeretném átnézni a kínálatodat.}
{158}{}{Nem láttál itt valahol egy aranyórát kallódni?}
{159}{}{Késõbb még jövök.}
{160}{}{Egy ÉLET nevû dolgot hajkurászok mostanában. Van rá némi esély, hogy mond neked ez a szó valamit? Esetleg még azt is tudhatnád, hogy juthatnék egy ilyenhez...}
{161}{}{ÉLET?}
{163}{}{Miben segíthetek?}
{168}{}{Csak körülnézek, kösz...}
{171}{}{Nem találtál még Jonnyra?}
{172}{}{Ezt egy régi, kiszáradt kút fenekén találtam. A kút egy része beomlott, és ez hevert a törmelék közt. Sajnálom, de attól tartok, Jonny meghalt.}
{173}{}{Nem, egyelõre nem...}
{175}{}{Köszönöm, hogy visszahoztad a fiunkat! Nincs módomban, hogy valaha is méltó módon visszafizessem ezt neked, de hálánk jeléül fogadd el ezt a bõrdzsekit. Nem is olyan régen egy új kikészítési eljárást dolgoztam ki. Szerintem elég szívósnak fogod találni ezt a páncélt, ráadásul még jól is áll majd rajtad.}
{176}{}{Köszönöm, hogy megmentetted a fiamat!}
{177}{}{Kérlek, hagyj magamra a bánatommal...}
{178}{}{Jonny él! A magukat dacból Aljanépnek nevezõ társaság megmentette õt. Ha még nem fogyott el a türelmed, van esély, hogy Jonny megkerül. }
{179}{}{Jonnyt elrabolták a tanya szellemei, és sötét istenüknek akarják feláldozni õt.}
{180}{}{Értem. Bocsáss meg, inkább nem zavarok.}
{181}{}{Hogy? Nézd, nem szoktam a magánéletemet kiteregetni idegenek számára. Akarsz tõlem valamit vagy sem?}
{182}{}{Elnézést, a nevem }
{183}{}{. Most, hogy bemutatkoztunk, látom, valami nem stimmel veled.}
{184}{}{Igen, bõráruk érdekelnének.}
{186}{}{Szerintem nem.}
{187}{}{Azt mondtad, }
{188}{}{? Igen, meglehet, hogy hallottam rólad. Egy elhaladó karaván õreivel beszélgettem, és jó dolgokat meséltek egy ilyen nevû személyrõl. Tudom, hogy csak most találkoztunk elõször, de igazán elkelne a segítséged.}
{189}{}{Mondd csak el, mi a probléma, talán tudok segíteni.}
{190}{}{Sajnálom, megvannak a magam problémái.}
{191}{}{[Kezébe kap egy fémvésõt és idegesen tekergetni kezdi. Legnagyobb meglepetésedre a vésõ úgy hajlik, mintha gitt lenne. Ez az ember aztán nem gyenge!] Jonny fiam eltûnt! Néhány napja kiment játszani, és azóta sem jött vissza. Mindenütt kerestük már, de sehol nincs.}
{192}{}{Jonny hol szokott általában játszani? Elõfordul, hogy nem egyedül játszik?}
{193}{}{Sajnálom, ami a gyermekkel történt, de mit tudnék én csinálni?}
{194}{}{Ez szörnyû... Viszont azért jöttem, hogy bõrcuccokat vegyek, szóval akár meg is mutathatnád õket...}
{195}{}{Nézzenek oda, hogy elszaladt az idõ! Mennem kell.}
{196}{}{Ez azt jelenti, hogy segítesz nekem? Köszönöm. Jonny indiánosdit játszott odakint Öcsivel, a kutyájával. Azok ketten elválaszthatatlan jóbarátok. Valójában ebbõl jöttem rá, hogy valami nem stimmel. Egyik nap Öcsi a fiam nélkül jött haza. Azóta is kutatunk utána. Mi lenne, ha magaddal vinnéd Öcsit? Talán ketten megtalálhatjátok Jonnyt.}
{197}{}{Érzem, hogy tapasztalt utazó vagy. A képességeiddel talán a fiam nyomára bukkanhatunk.}
{198}{}{Meglehet! Ha szólhatok néhány jó szót a magam érdekében, elég tapasztalt nyomolvasó vagyok. Szóval... segítek.}
{199}{}{A hízelgéssel semmire sem jutsz. Nézd, volna néhány kérdésem.}
{200}{}{Az imáim meghallgattattak! Vidd magaddal Öcsit, talán segíthet rajtad. Kérlek, ne késlekedj!}
{201}{}{Talán igazad van. Kösz, hogy végighallgattál.}
{202}{}{Hallottam már rólad. Jobb ha tudod, hogy nem akarok balhét. Békés kis közösség a mienk. Szorítkozzunk tehát csak az üzletre, rendben?}
{203}{}{Feltennék néhány kérdést.}
{204}{}{Jelenleg nem tudok mit ajánlani. Viszlát!}
{205}{}{Az a helyzet, hogy aggódom az eltûnt fiam, Jonny miatt. Már mindenütt kerestük, de sajnos sehol nem találjuk. Félek, hogy a vadállatok már kiszagolták, merre bujkál.}
{206}{}{Talán segíthetek. Sokat utazgatok erre-arra és simán belefér nálam, hogy a fiút is felkutassam.}
{208}{}{Oh, igazán nagylelkû vagy. Minden létezõ segítség elkél. Addig is nem akarsz valamit vásárolni?}
{210}{}{Nem, nem... Inkább indulnék, kösz...}
{211}{}{Sajnálom, sosem hallottam róla.}
{214}{}{Hehehe. Csak nem elkapott a jó öreg Cornelius, hogy keresd meg neki az óráját? Sajna itt nem fogod megtalálni. A vén tata egyszerûen letette valahova és kiesett a fejébõl, hogy hova.}
{215}{}{Azért köszönöm. Körbenézek. Üdv}
{216}{}{[Tüzetesen végigmér, aztán elmosolyodik]. Miért nem vagy jófiú és mész játszani a többiekkel odakinn?}
{217}{}{[Tüzetesen végigmér, aztán elmosolyodik]. Miért nem vagy jó kislány és mész játszani a többiekkel odakinn?}
{218}{}{Kérlek ne hagyd abba a keresést! Tudom, hogy él még valahol. Érzem!}
{219}{}{Ez Jonny BB puskája! Neeeeeeeeeeeeeeeee! [Balthas magába roskad, és keservesen sírni kezd]}
{220}{}{Tudtam, hogy Jonny nem halt meg! Azt mondod, várnom kell... de ezt nem értem! Baja lett tán? Az ösztöneim azt súgják, hogy fussak a fiamhoz, de azt is érzem, hogy te a fiam legjobb érdekében cselekszel. Kérlek, siess és hozd vissza a fiam!}
{221}{}{Jaj ne, csak a szellemeket ne említetted volna! Tudtam, hogy porig kellett volna égetnem azt a helyet. Nem engedem, hogy elvegyék a fiam... Bármi áron, de visszahozom õt. Biztos vagyok, hogy Modoc lakosai segítenek ebben! Találkozzunk a Kísértetfarmon! Mindegyiket kinyírjuk!}
{230}{}{Biztonságban visszajutattad Jonnyt Modocba.}
