# Dialog Editor last position: 66
{100}{}{Kisfiú.}
{101}{}{Kislány.}
{120}{}{Ez a kisfiú elég játékosnak mutatkozik.}
{121}{}{Ez a kislány elég játékosnak mutatkozik.}
{150}{}{Ne egyél meg!}
{151}{}{Ááááá! Itt a mumus!}
{152}{}{Apu azt mondta, rossz vagy.}
{153}{}{Ajjajjj! Fuss el!}
{154}{}{Félek tõled.}
{155}{}{Ne nézz rám!}
{156}{}{Nem beszélhetek törzsbéliekkel.}
{157}{}{Ez egy tacskó.}
{158}{}{Anyukám azt mondta, megeszel, ha rossz vagyok.}
{159}{}{Nem félek ám tõled!}
{160}{}{Segíííts!}
{161}{}{Jön utánam!}
{162}{}{Kérlek, ne bánts!}
{163}{}{Ne gyere közelebb!}
{164}{}{Ííííííííííííííííí!}
{165}{}{Utállak!}
{166}{}{Mami, mami, mami!}
{167}{}{Hagyj békén!}
{168}{}{Bûzlesz!}
{170}{}{Szia.}
{171}{}{Játszunk papás-mamást?}
{172}{}{Tényleg csontot szúrtok az orrotokba?}
{173}{}{Miért nézel ki ilyen furcsán?}
{174}{}{A mamám szerint primitívek vagytok.}
{175}{}{A te törzsed már abbahagyta az emberevést?}
{176}{}{Miért öltöztök ilyen furcsán?}
{177}{}{Szerintem aribb vagy, mint ahogy kinézel.}
{178}{}{Fogócskázzunk! Te vagy a fogó.}
{179}{}{Nem is vagy olyan büdös.}
{180}{}{Láttad már a láthatatlan barátomat?}
{181}{}{Ha olyan nagy leszek, mint te, az egész világot be akarom járni.}
{182}{}{Egész kedves törzsbéli vagy, nem úgy mint a többi.}
{183}{}{Szerintem te szoktál fürdeni.}
{184}{}{Okosabb vagy mint Torr.}
{185}{}{Az a penge nálad tényleg éles?}
{186}{}{Ha felnövök, én is olyan akarok lenni, mint te.}
{187}{}{A kutyám szereti a kutyatápot.}
{188}{}{Van egy fényes kavicsom...}
{189}{}{Láttad már a láthatatlan barátomat?}
{190}{}{Beléphetek a törzsetekbe?}
{191}{}{Ari vagy.}
{192}{}{Furcsán nézel ki.}
{193}{}{Mi van rajtad?}
{194}{}{Brahminra akarok ülni!}
{195}{}{Messzirõl jöttél?}
{196}{}{Íhíííííjjj! Ha, ha, ha!}
{197}{}{Ne menj el!}
{198}{}{Van valami kajád?}
{199}{}{Zavarlak?}
{200}{}{Hova mész?}
{201}{}{Mehetek veled?}
{202}{}{Hány éves vagy?}
{203}{}{Hogy hívnak?}
{204}{}{Szereted a gyerekeket?}
{205}{}{Az mi?}
{206}{}{Akarsz játszani?}
{207}{}{Micsinálsz?}
{208}{}{Láttál bogarakat?}
{209}{}{Honnan szedted?}
{210}{}{Enyém lehet?}
{211}{}{Mivel foglalkozol?}
{212}{}{Gyorsan futok ám! Akarod látni?}
{213}{}{Nézz ide! Nézz ide!}
{214}{}{Mami szerint túl sokat jár a szám.}
{215}{}{Hol az otthonod?}
{216}{}{Heeee! Heeee!}
{217}{}{Itt akarsz maradni?}
{218}{}{Vannak gyerekeid?}
{219}{}{Miért jöttél ide?}
{220}{}{Tetszel nekem.}
{221}{}{Tetszem neked?}
{222}{}{Házas vagy?}
{223}{}{Egy, kettõ, három... Íhhíííííjjj!}
{300}{}{Idegen!}
