# Dialog Editor last position: 129
{100}{}{Egy energikus öregúr.}
{101}{}{Grisham.}
{102}{}{Nem tudod hova tenni, de ismerõsnek tûnik.}
{151}{}{Mondtam már, hogy húzzon innen!} #DIREKT
{152}{}{Muhahahaha!}
{153}{}{Menjen innen!}
{154}{}{Dolgom van!}
{155}{}{Tudtam, hogy fura egy lányom van.}
{156}{}{Különbözõ emberek, különbözõ ízlések...}
{157}{}{Asszem, mindjárt rosszul leszek.}
{158}{}{Tudtam, hogy fura egy fiam van.}
{159}{}{Gondolom most már egy a család.}
{160}{}{Bánjon jól a gyermekemmel.}
{161}{}{Bánjon jól a gyermekemmel.}
{162}{}{Grisham-nek hívnak. Üdvözlet a mészárszéken. Felszed vagy lead?}
{163}{}{Azt hiszem, inkább felszednék. Néhány utazáshoz szükséges holmira lenne szükségem.}
{164}{}{Nincs rá egy hangyányi esély, hogy látott valahol egy aranyórát heverni?}
{350}{}{[Bessy-re pillantván] Inkább leadnék.}
{165}{}{Miben segíthetek?}
{166}{}{Szeretnék vásárolni a híres szárított húsából.}
{168}{}{Mondana valami közelebbit a mészárszékrõl?}
{169}{}{Látom, az aszály még nem befolyásolta komolyan az üzletet.}
{360}{}{Szeretném, ha készítene nekem egy kis szárított húst.}
{170}{}{Tudtam, hogy menni fog. Nézzük csak, akkor 1000 pénzzel tartozom a munkáért. Sajnos }
{171}{}{ brahmin odaveszett a gondatlansága miatt. Darabonként 100 dolcsival számolva a jutalma }
{172}{}{ dollár. Eszébe ne jusson, hogy szépítgeti a megölt brahminok számát. Az egyik segédem messzirõl figyelte az eseményeket.}
{173}{}{Nekem nem mondta, hogy az elpusztult brahminok miatt kevesebb pénzt kapok!}
{174}{}{Na, idefigyelj, te hátulróljövõ, aszott kis tetû. Figyelj a szavamra! Ez volt az utsó alkalom, hogy palira vettél.}
{175}{}{Köszi, papa. Öröm volt együtt dolgozni.}
{176}{}{Hogy merészeli idetolni a képét? A gyávasága miatt tíz brahmint vesztettem. Ha amúgy a kártérítésen törné a fejét, 1500 dolcsival elsimíthatjuk a dolgot.}
{177}{}{Azok a brahminok nem értek többet ezernél.}
{178}{}{Nincs annyi pénzem, de ha lenne sem adnám egy ilyen pitiáner alaknak.}
{179}{}{A szobámban hagytam a pénzem. Hadd menjek el érte.}
{180}{}{Ah! Persze, persze. Nézzük csak, útravalónak ajánlanám a világhírû szárított brahminhúsunkat. Nem romlik meg és remek íze van. Egy csomag 10 dollár. Érdekli?}
{181}{}{Jól hangzik. Adjon egy adagot.}
{182}{}{Nem kösz, talán késõbb. Viszont feltennék néhány kérdést.}
{183}{}{Öröm magával üzletelni. Van még valami, amiben segíthetek?}
{185}{}{Várjon! Egészen belevaló utazónak látszik. Esetleg egy kis pénzkereseti lehetõség nem érdekli?}
{186}{}{Biztos, hogy nem érdekli a pénzkereseti lehetõség? Meg vagyok gyõzõdve, hogy könnyedén meg tudná oldani a problémámat.}
{187}{}{Attól függ. Mennyit kapok, mit kell csinálni, és fõleg... MENNYIT KAPOK?}
{188}{}{Dörzsölt, nagyon dörzsölt. A fiatalabb énemre emlékeztet. Na, akkor térjünk a lényegre. Vadkutyák jöttek le a hegyrõl mostanában. Brahminokra mennek, mivel nekik ez könnyû préda. Minden éjjel rájárnak a gulyára. Ezer dollárt adok, ha kiirtja õket.}
{189}{}{Valamit elhallgat itt, vén tata. Lesz valami hátrányom?}
{190}{}{Nemcsak dörzsölt, de jó emberismerõ is. Gondoltam, hogy nem kapkodja el a dolgokat. Ami a hátrányt illeti, minden elpusztult brahmin után 100 dollár fájdalomdíjat számolok fel. A jól végzett munkáért jól is fizetek, de a bénázásért én is megkérem a pénzemet. Ha nekem dolgozik, ezt a kockázatot vállalnia kell.}
{191}{}{Remek! Menjen ki éjszaka a terepre és ölje meg a brahminra vadászó vadkutyákat. Ha kész, újra találkozunk.}
{192}{}{Azt a rézfánfütyülõjét! Cornelius még mindig keresi az óráját? Miért nem képes elfogadni az öreg, hogy eltûnt? Az a vacak óra sosem mûködött egyébként, és brahmin legyen a nagyapám, ha egyáltalán aranyból készült. Hagyja a fenébe, sosem fogja megtalálni.}
{193}{}{A helyzet az, hogy Farrel kért meg engem a felkutatására.}
{194}{}{Feltehetek további kérdéseket?}
{195}{}{Kösz, de azért én még nem adom fel.}
{196}{}{Nem-e? Biztos benne? Megesküdtem volna, hogy elmondtam elõre... talán legközelebb nem vállal el munkákat a részletek ismerete nélkül. Most pedig, ha megbocsát, dolgom van.}
{197}{}{Hehehe. Attól függ. Sokáig akar a városban maradni? Bwahahahaha!}
{198}{}{Látom, maga aztán nem esett e fejére. Legyen akkor 1000 dollár és kvittek vagyunk. }
{199}{}{[KEZET RÁZTOK GRISHAM-MEL]}
{200}{}{Egy pillanat. Most, hogy így végiggondolom a dolgot, azok a brahminok elég satnyák voltak. Mit szólna 750-hez?}
{201}{}{Meggondoltam magam, nem fizetek.}
{202}{}{[Széles mosolyt küld feléd] Jó látni, hogy ilyen karakteres személyiséggel állok szemben.}
{203}{}{[Grisham arca céklavörössé válik és összeszorított foggal sziszegi:] Rendben, legyen 750. Ide a pénzzel!}
{204}{}{Tudja, 750 még mindig elég soknak tûnik. Ha a kutyák nem lettek volna, azok a brahminok anélkül is beadták volna a kulcsot. Viszont nem vagyok annyira önzõ, és adok 50 dollárt.}
{206}{}{JÓ! ADJA IDE A PÉNZT ÉS MENJEN INNEN!}
{207}{}{[FIZETÉS NÉLKÜL TÁVOZOL]}
{208}{}{Vésse az eszébe a szavaimat, mert megjárja. Ha nem én intézem el, majd más megteszi.}
{209}{}{[Grisham úgy néz rád, hogy önkéntelenül is hátralépsz egyet] Miért nem tartja meg a pénzét? Van egy olyan érzésem, hogy késõbb még hasznát venné.}
{210}{}{Nem sok mindent tudok mondani. Én vezetem a modoci mészárszéket. Ha le akar vágni valami állatot, idehozza hozzám, én levágom és a létezõ legjobb szárított húst csinálom belõle.}
{211}{}{Mi a helyzet az állat bõrével, és más részeivel?}
{213}{}{Tulajdonképpen egész felfuttatta az üzletemet. Eddig senki nem volt képes elegendõ takarmányt termelni a brahminjainak, ezért mindenki arra kényszerült, hogy alaposan megritkítsa a gulyáját. De ez csak átmeneti állapot. A dolgoknak van egy nagyobb szabású vonzata is. A brahminállomány csökkenésével az üzlet egyre csak rosszabbodik.}
{215}{}{Grisham körbejár, megbökdös néhányszor, aztán kinyitja a szád, és megnézi a fogsorodat.] Ah! Remek, egészséges példány. Megteszi. Khm... Rossz kutyák megölik a jó brahmint. Eridj, öld meg a rossz kutyákat Grisham barátodnak. Grisham jó pénzt fizet. Oké?}
{216}{}{Nem, én szeret kutya. Csak rossz ember nem szeret kutya. Én itthagy rossz ember.}
{217}{}{Megtesz. Menni oda!}
{218}{}{Jó! Vésd észbe, a rossz dolog Vaúzik, a jó dolog Múúúzik. Próbáld ne megölni a jó dolgokat.}
{219}{}{Kissé kifogyott a pénzbõl. Hitel nincs és ne higgye, hogy semmiért adok valamit.}
{221}{}{Na, ezért küldök egy Neandervölgyit! Eridj!}
{222}{}{Uh... sznarf ikk unga bunga. Most pedig fogd a pénzt kis Neandervölgyim, és irány az ajtó.}
{223}{}{Maga aztán eszes fajta, mi? Ha engem kérdez, az állat bármely részét visszakapja. Balthus rendszerint átveszi a bõröket, Rose meg mindenféle nyesedéket felvásárol. Levest meg kutyakaját csinál belõle.}
{225}{}{Maga viccel! Mindenki tudja, hogy Farrel tette zsebre az órát. Ugyan miért kerestetné magával... hacsak tényleg nem Farrel lopta el! Az is lehet, hogy ez a trükk, amivel mindenkit meg akar gyõzni, hogy nem õ volt. Meg kéne ezt még hányni-vetni.}
{228}{}{Fiú, ne is próbáld megmagyarázni. Nem akarom hallani. Hívatom a plébánost, törvényes keretet adunk a dolognak, és ha elmész, magaddal viszed a fiamat.}
{229}{}{Nem mondanám, hogy nem izgatott fel a dolog, de most hogy láttam ezt meg azt, nem tudnék vele egy házban élni. Ti ketten szépen összeházasodtok, aztán távoztok az életembõl.}
{230}{}{Nem akarod elmagyarázni, mit csiná'sz a lányommal?}
{231}{}{Nem akarod elmagyarázni, mit csiná'sz a fiammal?}
{232}{}{Hadd világítsak rá értelmesen, tata. Vannak ugye a madarak meg a méhek, tudja...}
{233}{}{Orvos vagyok, csak ellátásban részesítettem a hölgyet.}
{234}{}{Orvos vagyok, csak ellátásban részesítettem az urat.}
{235}{}{Ez nem úgy van, ahogy gondolja!}
{236}{}{Ez nagyszerû! Egy okostojás lesz a vejem. Na, fiam... akkor essünk túl rajta.}
{237}{}{Ez nagyszerû! Egy okostojás lesz a menyem. Na, lányom... akkor essünk túl rajta.}
{238}{}{Ami azt illeti, nekem úgy tûnt, mintha te meg a lányom az üzekedõ brahminokat utánoztátok volna.}
{239}{}{Ami azt illeti, nekem úgy tûnt, mintha te meg a fiam vízszintes tangót jártatok volna a lepedõn.}
{240}{}{Oké, talán nem áll messze az igazságtól. De ez csak szex, semmi szerelem vagy ilyesmi nincs benne.}
{241}{}{Értem én. Hormonok meg ugye az évszak is kedvez a dolognak.}
{242}{}{Örülök, hogy megértõ.}
{243}{}{Az vagyok, és remélem, elfogadható a részetekrõl, hogy most szépen összeházasodtok. Nem fognak az emberek itt pletykálkodni. Gyerünk, irány a plébános! Ne akarjátok, hogy a puskámra bízzam a dolgot.}
{244}{}{Valóban? Aztán miért voltatok mindketten meztelenek?}
{245}{}{Ööö... a baktériumok miatt... Igen-igen, A BAKTÉRIUMOK MIATT! Nagyon fontos, hogy miközben ezeket a vizsgálatokat végezzük, tiszták legyünk.}
{246}{}{Nos, ha valóban orvos, akkor rendben van. Viszont jobb lenne, ha felöltözne, mert az ilyen félreértések miatt születnek a pletykák. Egyébként van egy kis panaszom. Egyfolytában fáj a végbelem és arra gondoltam, ha már itt van, talán vethetne rá egy pillantást.}
{247}{}{Ööö... késõbb megnézem. Van még egy várakozó betegem. Viszlát!}
{248}{}{Hogyne. Miért nem megyünk akkor együtt a plébánoshoz? Ne próbálkozz semmivel, különben neked lesz orvosra szükséged.}
{260}{}{Tudtam, hogy menni fog! Nézzük csak, 1000 dolcsival jövök a munkáért. Tessék.}
{300}{}{Mi a franc folyik itt?}
{301}{}{Hûha... Uram, én csak...}
{302}{}{Elõször is vedd le a mocskos kezedet a lányomról...}
{400}{}{Mi folyik itt?}
{402}{}{Szent ég! Tudtam, hogy }
{452}{}{ amolyan másféle... ezt viszont csak egy módon lehet helyrehozni.}
{403}{}{}
{453}{}{ nevét akarod beszennyezni ilyesmivel? Csak egy módon lehet ezt orvosolni!}
{404}{}{Elnézést, Jo, nem tudnánk esetleg az esküdözõs résztõl eltekinteni?}
{406}{}{Fiam...}
{407}{}{Missy...}
{410}{}{Ne akard, hogy özvegyet csináljak }
{460}{}{ "testvérünkbõl"!}
{461}{}{ "testvérünkbõl"!}
{412}{}{Miria}
{413}{}{Davin}
{220}{}{Nem mész te sehova, fiam!}
{221}{}{Nem mész te sehova, Missy!}
{500}{}{Nagyon derék állat ez. Jó kis szárított húst lehetne belõle készíteni. Na, tudja mit, egyszerûen megtartom a szárított húst fizetség gyanánt. Mit szól?}
{501}{}{Dehogyis! Bess a kedvencem. Senki nem csinál belõle semmiféle szárított húst!}
{502}{}{Jól hangzik. Mikor jöhetek vissza a húsért?}
{503}{}{Felejtse el, tatus. Már itt sem vagyok.}
{510}{}{Ó... már megint itt egy... A világért sem venném el tõled a "barátodat". A sivatagi éjszaka valószínûleg szörnyen magányos lenne nélküle. Na, jó... erre most nincs idõm. Meg kell még csinálnom egy-két dolgot.}
{515}{}{Remek! Jöjjön vissza egy héten belül. A mészárszék melletti füstölõházban magához veheti a húst. Egy zsákban otthagyom majd. Jó magával üzletelni.}
{600}{}{Mizújs }
{1600}{}{. Õ az életem értelme és a szívem szakadna meg, ha valami történne vele. Hol van egyébként? Reméltem, hogy hamarosan láthatom.}
{601}{}{Nos, ha esetleg nem }
{1601}{}{. Milyen amúgy a házasélet? Davint nem látom veled. Nagyon hiányzik. Ha legközelebb erre járnál, hozd magaddal. Az öregember szívét megmelengetné, ha látná néha egyetlen fiát.}
{602}{}{Hát... meghalt.}
{603}{}{Hát... meghalt.}
{604}{}{Miria élt, amikor otthagytam, de most már biztos, hogy meghalt.}
{605}{}{Davin élt, amikor otthagytam, de most már biztos, hogy meghalt.}
{606}{}{Davin, öööö... szóval nem bírta az utat, de ha találkozunk, átadom az üdvözletét.}
{607}{}{Miria, öööö... szóval nem bírta az utat, de ha találkozunk, átadom az üdvözletét.}
{700}{}{Arghh... [Grisham megdöbbent arcot vág, aztán a szívéhez kap és összeesik.]}
{750}{}{Most vissza kell térnem a munkámhoz. Viszlát bármikor.}
{800}{}{Megóvtad Grisham brahminjait.}
