# Dialog Editor last position: 1
{100}{}{Egy õr az Aljanépbõl.}
{150}{}{Add meg magad, vagy meghalsz!}
{151}{}{Megadom magam.}
{152}{}{Meghalsz!}
{153}{}{Úhh!}
{154}{}{Ha látni akarod Vegeirt, elvezethetünk hozzá.}
{155}{}{Most nem. Majd késõbb felkeresem Vegeirt.}
{156}{}{Igen, most azonnal kell Vegeirrel találkoznom.}
{160}{}{Hülyébb vagy, mint hat pár rendõrcsizma! Ha Vegeirrel van dolgod, keresd meg magad!}
{200}{}{Nem bízom a "fentiekben."}
{201}{}{Vegeir meghagyta, hogy ne bántsunk... EGYELÕRE!}
{202}{}{Azzal bíztak meg, hogy védjük a népünket.}
{203}{}{Figyellek...}
{220}{}{Szerintem nincs veled semmi baj... egy "felszínihez" képest.}
{221}{}{Akár még ki is jöhetünk a "felszíniekkel".}
{222}{}{Örülök, hogy tévedtem veled kapcsolatban.}
