# Dialog Editor last position: 1
{100}{}{Õ nem más, mint Ittapiros-Holapiros.}
{150}{}{Egy nyeszlett öregúrhoz van szerencséd. Arcát kicserzette a nap, és olyan vékony szegény, mintha az egész ember két törékeny gallyacska lenne.}
{000}{}{Ittapiros-Holapiroshoz van szerencséd. Az utcát fürkészi, és amikor épp rád néz, bólogat.}
{000}{}{Ittapiros-Holapiroshoz van szerencséd. Az utcát fürkészi, és amikor épp rád néz, bólogat.}
{200}{}{Nem látja, hogy megkopasztottak?...}
{000}{}{Csak fel-alá járok... Ittapiros bácsi szabadságot vett ki.}
{000}{}{Vajon a rossz lapot dugtam el?}
{000}{}{Hogy a fenébe képes az az agyatlan õsember folyton a jó kártyát kiválasztani?}
{205}{}{Hé, nagy ember! Igaza van, igaza van!}
{000}{}{::Felfelé mutatott hüvelykjével mutatja, hogy minden rendben.::}
{000}{}{::Mosolyog, bólogat::}
{000}{}{Megcsinálta a frankót, nagy ember. Megcsinálta...}
{215}{}{Hol a francba vannak a kártyácskáim? Nem tudok meglenni nélkülük!}
{000}{}{Azok a mocskos slusszkulcs-tolvajok, most épp a kártyáimra hajtottak rá.}
{220}{}{Hela, kispajtás, fenébe a kaszinóval, játsszon inkább Ittapiros bácsival!}
{000}{}{Szerencsét próbálgatunk, kispajtás? New Reno a legjobb, ha nyerni akar! Ne tétovázzon...}
{000}{}{Hela, kispajtás. Szerencsés fajtának látszik, nem akar közelebb húzódni?}
{000}{}{Akar valaki játszani? Hullik a pééz, hullik a pééz!}
{000}{}{Jöjjön oszt játsszunk. Tegnap egy fazon vagy ötven dolcsit nyert tõlem, és milyen könnyedén!}
{000}{}{Nagyon könnyû ez, csak mutasson rá a dámára, a vörös dámára, és már nyert is. Rém egyszerû!}
{000}{}{Na, mi van? Irtózik a könnyû pénzkeresettõl? Akkor jöjjön mán ide!}
{000}{}{Ma mindenki csak nyer... nem akar a következõ lenni?}
{000}{}{A kaszinók kizsebelik magát, mint a huzat... Ittapiros bácsi jól bánik magával, még esélyt is kap.}
{000}{}{Szerencsét próbálgatunk, szép kisasszony? New Reno a legjobb, ha nyerni akar! Ne tétovázzon...}
{000}{}{Na, mi van? Irtózik a könnyû pénzkeresettõl, kis kisasszony? Merészkedjen közelebb!}
{000}{}{Hahó, szép hölgy. Magácska szerencsés csillagzat alatt született, nem jön közelebb?}
{000}{}{Szép hölgyemény, fenébe a kaszinóval, játsszon inkább Ittapiros bácsival!}
{230}{}{Ittapiros bácsi ma nem tud játszani, barátom. Eltûntek a francos kártyáim.}
{231}{}{(Az öregember mosolyog, miközben a szemei körül jócskán meggyûlnek a ráncok.) Játszhatnéka van, barátom?}
{000}{}{(Az öregember mosolyog, miközben a szemei körül jócskán meggyûlnek a ráncok.) Kegyed netán a játékon töri a fejét?}
{000}{}{(Az öregember mosolyog, miközben a szemei körül jócskán meggyûlnek a ráncok.) A kis hõsünk netán játszani óhajt?}
{000}{}{(Ittapiros mosolyog, miközben a szemei körül jócskán meggyûlnek a ráncok.) Játszhatnéka van, barátom?}
{000}{}{(Ittapiros mosolyog, miközben a szemei körül jócskán meggyûlnek a ráncok.) Csak nem játszani óhajt kegyed?}
{000}{}{(Ittapiros mosolyog, miközben a szemei körül jócskán meggyûlnek a ráncok.) A mi kis hõsünk játszani kíván?}
{000}{}{Ittapiros-Holapiros a teljes nevem, és ugyanezen a névre hallgató játékról van szó. Dobjon a közösbe 20 dolcsit, és már neki is feküdhetünk a dolognak.}
{000}{}{Maga csap itt be engemet! Maga játszik nem tiszta}
{000}{}{Rendbe' lerakok dolcsi, nem vok biztos 20 mennyi, hát itt egy rakat.}
{000}{}{Hát... kösz a hízelkedés, én nem akar most magának nekifekünni... viszláááát}
{000}{}{Elbattyogsz}
{000}{}{Egy ilyen csalóval, mint maga, nem játszom!}
{000}{}{Minek akar nekifeküdni?}
{000}{}{Ismerem a játékot. Itt a pénze. Játsszunk!}
{000}{}{Ittapiros-holapiros? Színnel lefelé lerak három kártyát, megkeveri, én meg kiválasztok egyet. Ha jó kártyát választok - amely ugyebár lehetetlen, hiszen keverés közben bûvészkedik vele - akkor nyerek. Hát kösz nem kérek belõle, jóember.}
{000}{}{Ittapiros-holapiros? Színnel lefelé lerak három kártyát, megkeveri, én meg kiválasztok egyet. Ha jó kártyát választok - amely ugyebár lehetetlen, hiszen keverés közben bûvészkedik vele - akkor nyerek. Hát kösz nem kérek belõle, jóember.}
{000}{}{Ma nem, kösz.}
{250}{}{Na, mégis mit gondol? Hát a játéknak!}
{000}{}{Na, sasoljon ide... (megmutatja a három kártyalapot) ...az egyik a dáma. Színnel lefelé lerakom az asztalra, megkeverem, aztán kiválasztja a dámát. Ha sikerül, nyert.}
{000}{}{Egyszerû ez, barátocskám.}
{000}{}{Egyszerû ez, szép hölgyem.}
{000}{}{Egy ilyen csalóval játsszon, akinek hat anyja van!}
{000}{}{Elmagyarázná még egyszer a szabályokat?}
{000}{}{Hát elég egyszerûnek tûnik. Na, gyerünk, itt a 20 dolcsija!}
{000}{}{Ma nem, kösz.}
{260}{}{(Átnyújtod a pénzt. Ittapiros bólint, megmutatja a lapokat, aztán leteríti õket a földre, és néhány másodpercig kevergeti õket.)}
{000}{}{Nos... melyik a dáma, kispajtás?}
{000}{}{Nos... melyik a dáma, kisasszony?}
{000}{}{(Szerinted a bal oldali.)}
{000}{}{(Szerinted a középsõ.)}
{000}{}{(Szerinted a jobb oldali.)}
{000}{}{(Gõzöd nincs róla, melyik az. A kártyák túl gyorsan kavarogtak.)}
{000}{}{Én a szívemre hallgatok, legyen a bal oldal}
{000}{}{Az arany középút mindig bejön}
{000}{}{Hiszek a jobbkézszabályban}
{000}{}{A bal oldali.}
{000}{}{A jobb oldali.}
{000}{}{A középsõ.}
{280}{}{(Ittapiros megfordítja a lapot. A pikk kettest választottad.)}
{000}{}{Hát ez most nem jött be, pajtás, de majdnem rátapintott.}
{000}{}{Hát ez most nem jött be, kisasszonyka, de majdnem rátapintott.}
{000}{}{Amúgy elég jó szeme van hozzá. Esetleg egy újabb próba?}
{000}{}{Maga csap itt be engemet! Maga játssza nem tiszta}
{000}{}{Rendbe' lerakok dolcsi, nem vok biztos 20 mennyi, hát itt egy rakat.}
{000}{}{Nemááán nem teccik játék MENEK ELFELE}
{000}{}{Nem ettem meszet, hogy egy ilyen csalóval játsszak!}
{000}{}{Hogyne. Itt a 20 dolcsija.}
{000}{}{Kösz nem.}
{300}{}{(Átnyújtod a pénzt. Ittapiros rábólint, megmutatja a lapokat, aztán leteríti õket a földre. Miközben ezt teszi, az egyik kártyát a tenyerébe rejti, de olyan villámsebesen, hogy majdnem elsiklasz felette. Ezután néhány másodpercig még folytatja a keverést .)}
{000}{}{Akkor tehát... melyik a dáma, kispajtásom?}
{000}{}{Akkor tehát, kis hölgyem... melyik a dáma?}
{000}{}{Dugdosik itten nem játssza tisztességes}
{000}{}{Én a szívemre hallgatok, legyen a bal oldal}
{000}{}{Az arany középút mindig bejön}
{000}{}{Hiszek a jobbkézszabályban}
{000}{}{Maga átkozott CSALÓ! Láttam, ahogy dugdossa a kártyát! Adja vissza pénzemet, vagy itt helyben kicsinálom!}
{000}{}{Azt választom, amelyik az ingujjában van.}
{000}{}{A bal oldalit választom.}
{000}{}{A jobb oldalit választom.}
{000}{}{A középsõt választom.}
{320}{}{MIT mondott, pajti?}
{000}{}{MIT mondott, hölgyem?}
{000}{}{Csalással vádol engem?}
{000}{}{Én tud maga ver engemet átfele}
{000}{}{Neh! Neh! Lazíccsa! Menek is!}
{000}{}{Igen.}
{000}{}{Legyen boldog a pénzemmel, húzok a francba!}
{330}{}{Nincsen énnekem idõm a zsír kezdõkre. Maga fizet, ezért esélyt kap a nyerésre. Ha játszani akar, benne vagyok, de tûnjön innen, ha csak hõzöng itt nekem vesztéskor!}
{000}{}{MEGDÖGLÖL}
{000}{}{Nehe-ne! Nehe-ne! Maraggya. Menek én.}
{000}{}{Na, jó. Most meghalsz!}
{000}{}{Rendben, rendben. Sajnálom. Itt a húsz dolcsi. Játsszunk újra egyet.}
{000}{}{Legyen boldog a pénzemmel, én lelépek!}
{340}{}{(Átnyújtod a pénzt. Ittapiros bólint, aztán leteríti a lapokat és egy darabig kevergeti õket.)}
{000}{}{Tehát... melyik a dáma, pajti?}
{000}{}{Tehát... melyik a dáma, hölgyem?}
{000}{}{(Ittapiros a hétköznapi pakliját használja! El kell lopnod a másik pakliját, hogy a trükköt befejezd.)}
{000}{}{Ingujjazza itt a lap, maga játssza nem tisztességes.}
{000}{}{Ööö... Én a szívemre hallgatok, legyen a bal oldal}
{000}{}{Ööö... Az arany középút mindig bejön}
{000}{}{Ööö... Hiszek a jobbkézszabályban}
{000}{}{Átkozott CSALÓ! Láttam, hogy dugdossa a kártyát! Adja vissza a pénzemet, vagy itt helyben kinyírom!}
{000}{}{Az ingujjában lévõt választom.}
{000}{}{Ööö, a bal oldalit választom.}
{000}{}{Ööö, a jobb oldalit választom.}
{000}{}{Ööö, a középsõt választom.}
{360}{}{(Átnyújtod a pénzt. Ittapiros bólint, megmutatja a lapokat, aztán leteríti õket a földre, és néhány másodpercig kevergeti õket.)}
{000}{}{(Átnyújtod a pénzt. Ittapiros kényelmetlenül érzi magát.) Ööö... rendben... (A férfi lerakja a lapokat a földre, és megkeveri õket.)}
{000}{}{Tehát, melyik a dáma, pajti?}
{000}{}{Tehát, melyik a dáma, hölgyem?}
{000}{}{(Ittapiros a jelölt lapokat használja. Bármelyiket választod, jó lesz.)}
{000}{}{Balos! Balos!}
{000}{}{Jobbos! Jobbos!}
{000}{}{Közép! Közép!}
{000}{}{Hát, a fene tudja... legyen a bal.}
{000}{}{Hmmmm... talán a jobb oldali?}
{000}{}{A fenébe, nem vagyok biztos benne... szerintem a középsõ az.}
{375}{}{(Ittapiros megfordítja a lapot, amely nem más, mint a kõr dáma. A férfi szinte lebénul a meglepetéstõl.) Ah...? Ej...}
{000}{}{mintha nyert volna, pajtás.}
{000}{}{mintha nyert volna, hölgyem.}
{000}{}{(Vonakodva válik meg a pénztõl.)}
{000}{}{Megin! Megin!}
{000}{}{Kössz menek mostan}
{000}{}{Most játszunk, vagy mi lesz? Gyerünk bátyám! Még csak most kezdek belemelegedni.}
{000}{}{Hát köszönöm szépen, Ittapiros úr. Késõbb találkozunk.}
{385}{}{(Ittapiros megfordítja a kártyát, amely nem más, mint a kõr dáma. Teljesen ki van akadva ettõl.) Ööö... Hát ez...}
{000}{}{asszem, nyert, pajtás.}
{000}{}{asszem, nyert, hölgyem.}
{000}{}{Hát ez bizony jól leapasztotta a zsebemet... (Megtörten néz rád) Valamit tehetek még magáért?}
{000}{}{Semmitse. Csak akartam kis extra TAPasztalat pont. Üdv-üdv.}
{000}{}{MILYE van?}
{000}{}{Miért nem ad némi információt?}
{000}{}{Felejtse el, Ittapiros úr. Ma kiegyezünk egy döntetlenben.}
{400}{}{(Fájdalmas arcot vág.) Fenébe... azért még van valamim... SOKKAL többet ér, mint amennyit elnyert tõlem... egyelõre...}
{000}{}{Mégpedig? Mi lenne az?}
{000}{}{Ha ez többet ér magának, mintha teljesen eladósodva a Golgotán nyúvadna meg, akkor az a maga problémája. A maga helyében én gondolkodnék rajta.}
{405}{}{Eh... hmnnn... attól függ, mit akar tudni.}
{000}{}{Tudja, ki nyírta ki Wright kölkét? Ki szoktatta rá a Jetre?}
{000}{}{Nem tudja véletlenül, hol találok meg egy bizonyos Szépfiú Lloydot?}
{000}{}{Ittapiros bátyám, nem tudja, hova lett az autóm?}
{000}{}{Nem tud semmi olyat, amit maga szerint nekem is kéne tudnom?}
{000}{}{Sebaj, Ittapiros bácsi. Kvittek vagyunk. Késõbb találkozunk.}
{415}{}{Eh... izé... hát nem tõlem hallotta, de szerintem Renesco a ludas. Õ az a seggarc, aki a nyugati kerületben vezeti a gyógyszertárat. Biztos ugyan nem vagyok benne, hogy épp õ adta volna el a gyereknek, de hogy tud valamit, az tutti. Ennél többet nem mondok.}
{000}{}{Rendben, Ittapiros úr. Kvittek vagyunk.}
{420}{}{Hát... hogyismondjamcsak... (mintha magában vívódna)... hát nem tõlem hallotta, de a maga helyében lenéznék a Desperado alagsorába.}
{000}{}{Rendben, Ittapiros úr. Kvittek vagyunk.}
{425}{}{(Hunyorítva közelebb hajol) Kérdezgesse a vén Jules-t az elõvárosban. Mindenrõl tud... vagy ha mégsem, akkor benne van a keze. Gondolom, tudja mirõl beszélek.}
{000}{}{Rendben, Ittapiros úr. Kvittek vagyunk.}
{430}{}{Hát... azt tudta-e, hogy az az Eldridge fazon vezeti a New Reno-i Fegyverboltot? Azt állítja, hogy fegyvertuningolással is foglalkozik, de én még az életben nem láttam egyetlen munkáját se. Talán érdemes lenne benézni hozzá... persze nem tõlem hallotta.}
{000}{}{Rendben, Ittapiros úr. Kvittek vagyunk.}
{435}{}{(Amint meglát, Ittapiros összevonja a szemöldökét.) Ma nem szerencsejátékozunk itt, értve? Le lehet kopni.}
{000}{}{Megvásárolhatom azt a kártyát, amit korábban mutatott nekem?}
{000}{}{Némi információra volna szükségem...}
{000}{}{Rendben, Ittapiros úr. Most az egyszer... lelépek.}
{440}{}{Fenét! Én ugyan meg nem válok tõle. Pont. HAMISÍTATLAN háború elõtti ereklye... a történelem kis szelete. Haggyon engem békét ezzel!}
{000}{}{ÚJABB ajánlata van? Már mondtam, hogy nem eladó.}
{000}{}{Mit szólna ezer dolcsihoz? Itt van nálam. Ha nekem adja azt a kártyát, a magáé.}
{000}{}{Még 750-ért sem?}
{000}{}{Mit szólna 500 dolcsihoz?}
{000}{}{250 dollár elég jól hangzana, nemde?}
{000}{}{Rendben. Hadd kérdezzek akkor ezt-azt...}
{000}{}{Na, jó felejtsük el egymást, Ittapiros. Tûzök innen.}
{450}{}{Süket maga? Ez az összeg még csak meg sem birizgálja az érdeklõdésemet.}
{000}{}{Mit szólna egy másik árajánlathoz...?}
{000}{}{Volna még néhány kérdésem...}
{000}{}{Jól van, fátylat rá, Ittapiros. Húzok a fenébe.}
{460}{}{Hát, igazán nem is ANNYIRA kell már. A magáé, pajtás. (Félve jobbra-balra tekinget, aztán lenyúl és lehúzza a csizmáját. Elcsavarja a sarkát, és elõvesz belõle egy kártyalapot.) Tessék. Vigyázzon rá.}
{000}{}{Feltennék még néhány kérdést...}
{000}{}{Kösz, Ittapiros. Örömömre szolgált.}
{465}{}{(Szemöldökét ráncolja) Az, hogy beszélek-e attól függ, mit akar tudni. Ráadásul nem lesz olcsó.}
{000}{}{Tudja, ki nyírta ki Wright kölkét? Ki szoktatta rá a Jetre?}
{000}{}{Nem tudja véletlenül, hol találok meg egy bizonyos Szépfiú Lloydot?}
{000}{}{Ittapiros bátyám, nem tudja, hova lett az autóm?}
{000}{}{Nem tud semmi olyat, amit maga szerint nekem is kéne tudnom?}
{000}{}{Semmi gond, Ittapiros. Húzok, mint a vadlibák.}
{475}{}{A Golgotát ne is említse, ÉRINTÕLEG sem! Kopjon le!}
{000}{}{Ez a téma nagyon gázos. Hagyjuk a fenébe, jó?}
{000}{}{Újabb ajánlatot akar tenni? Mondtam már, hogy NEM akarok beszélni róla.}
{000}{}{Ezer dolcsi talán jobb belátásra bírná? Itt van a zsebemben ám...}
{000}{}{Még 750-ért sem?}
{000}{}{Mit szólna 500 dolcsihoz?}
{000}{}{250 dollár egész jól hangzana, nemde?}
{000}{}{Öö... Golgota?}
{000}{}{Volna még néhány kérdésem...}
{000}{}{Sebaj, Ittapiros, már itt sem vagyok.}
{490}{}{(Megrázza a fejét.) Nincs az az isten! Már attól meghal valaki, ha beszélnek róla, lehet, hogy pont én. Üsse ki a fejébõl!}
{000}{}{Mit szólna hozzá, ha ezt itt felajánlanám magának...}
{000}{}{Egy-két kérdést még feltennék...}
{000}{}{Sebaj, Ittapiros, már megyek is.}
{495}{}{Öö... izé... ez jó sok pééz. (Megnyalja az ajkait. Látszik, hogy vívódik magában... de csak rövid ideig.) Hát idefigyeljen, nem tõlem hallotta...}
{000}{}{Értem. Folytassa.}
{500}{}{(Horkant) Lehet, hogy hallottam ezt-azt, lehet, hogy nem. A dolgoknak ára van.}
{000}{}{Rendben... beszéljünk az árról.}
{000}{}{Mit szólna egy egész ezer dollárhoz? Itt van a zsebemben.}
{000}{}{Még 750-ért sem?}
{000}{}{Mit szólna 500 dolcsihoz?}
{000}{}{250 nem hangzik rosszul, nemde?}
{000}{}{Kérdeznék még, ha lehet...}
{000}{}{Ne is törõdjön vele, Ittapiros. Már megyek is.}
{510}{}{Ha! Ennyiért egy vödör pisát sem kap. Hagyjon lógva!}
{000}{}{Mi lenne, ha ezt ajánlanám magának...}
{000}{}{Volna még egy-két kérdésem...}
{000}{}{Akkor felejtse el, Ittapiros. Megyek a vérbe.}
{515}{}{Eeeez már valami! (Gonosz módon vigyorog.) Hát nem tõlem hallotta, de ha a maga helyében lennék, lenéznék a Szûz utcai Desperado alagsorába. Egy csomó "patkány" van odalenn, ha veszi az adást.}
{000}{}{Most pedig kérdezni fogok...}
{000}{}{Vettem. Kösz.}
{520}{}{(Vállat von) Lehet, hogy tudok róla valamit, lehet, hogy semmit se. Térjünk az anyagiakra, és akkor talán megnyílik a szám.}
{000}{}{Rendben... beszéljünk a piszkos anyagiakról.}
{000}{}{Mit szólna egy rongyhoz? Itt van a zsebemben.}
{000}{}{Még 750-ért sem?}
{000}{}{Esetleg 500 dolcsi megteszi?}
{000}{}{250 nem hangzik rosszul, nemde?}
{000}{}{Kérdeznék, még ha nem bánja...}
{000}{}{Akkor hagyjuk, Ittapiros. Már megyek is.}
{530}{}{(Hunyorít és közelebb hajol) Azért az összegért én bizony nem tudok semmit.}
{000}{}{Mi lenne, ha ezt ajánlanám fel...}
{000}{}{Kérdeznék még, ha nem gond...}
{000}{}{Sebaj, Ittapiros, úgyis menni akartam.}
{535}{}{Ez már döfi... (Hunyorít és közelebb hajol) ...én megkérdezném a vén Jules-t az elõvárosban. Mindenrõl tud... és ha mégsem, akkor nyakig benne van. Remélem, érti, mire gondolok.}
{000}{}{Kérdeznék még ezt-azt...}
{000}{}{Rendben, Ittapiros. Kösz.}
{540}{}{(Vállat von) Hallok, látok ezt-azt. 200 dolcsiért hasznát veheti a tapasztalatomnak, ha érti, mire gondolok.}
{000}{}{Itt a 200 dollárja.}
{000}{}{Adok 150-et.}
{000}{}{100 dolcsi vagy semmi.}
{000}{}{Most inkább kérdeznék...}
{000}{}{Hagyjuk akkor, Ittapiros. Leléptem.}
{550}{}{Maga süket? 200 dolcsit mondtam, és nem a levegõbe beszéltem.}
{000}{}{Rendben van. Itt a 200 dollárja.}
{000}{}{Volna néhány kérdésem...}
{000}{}{Sebaj, Ittapiros, már amúgy is menni akartam.}
{555}{}{Rendbe'. (Ittapiros közelebb hajol) Azt tudta-e, hogy az az Eldridge fazon vezeti a New Reno-i Fegyverboltot? Azt állítja, hogy foglalkozik fegyvertuningolással, de én még az életben nem láttam tõle semmit. Esetleg beugorhatna megnézni... persze nem tõlem hallotta.}
{000}{}{Most kérdéseket fogok feltenni...}
{000}{}{Értem. Kösz, Ittapiros bátya.}
{560}{}{Csontlerakat a várostól délre. Bûzlik, mint a seggem, annyi szent.}
{000}{}{Ó... értem. Akkor térjünk vissza a Wright gyerekre...}
{000}{}{Felejtse el a Wright kölyköt! Koncentráljon inkább a kérdéseimre...}
{000}{}{Akkor rendben vagyunk, Ittapiros. Kösz.}
{565}{}{Fogadnék, hogy Renesco a ludas. Õ az a seggarc, aki a nyugati kerületben vezeti a gyógyszertárat. Biztos ugyan nem vagyok benne, hogy épp õ adta volna el a gyereknek, de hogy tud valamit, az tutti. (Körbeleseget.) Ennél többet nem mondok.}
{000}{}{Volna még néhány kérdésem...}
{000}{}{Rendben van, Ittapiros. Köszi.}
{570}{}{(Félve jobbra-balra tekinget, aztán lenyúl és lehúzza a csizmáját. Elcsavarja a sarkát, és elõvesz belõle egy kártyát. A lapon egy fura fickó látható, kezében bunkóval.) Érdekli? Ez egy hamisítatlan háború elõtti ereklye.}
{000}{}{Nem, már épp elég cucc van nálam... inkább nézzük az információkat, amiket nyújtani tud.}
{000}{}{Ó, hogyne. Miért is ne? Ez elegyengeti a köztünk levõ balhét.}
