{100}{}{Õ nem más, mint Ittapiros-Holapiros.}
{150}{}{Egy nyeszlett öregúrhoz van szerencséd. Arcát kicserzette a nap, és olyan vékony szegény, mintha az egész ember két törékeny gallyacska lenne.}
{200}{}{Nem látja, hogy megkopasztottak?...}
{205}{}{Hé, nagy ember! Igaza van, igaza van!}
{215}{}{Hol a francba vannak a kártyácskáim? Nem tudok meglenni nélkülük!}
{220}{}{Hela, kispajtás, fenébe a kaszinóval, játsszon inkább Ittapiros bácsival!}
{230}{}{Ittapiros bácsi ma nem tud játszani, barátom. Eltûntek a francos kártyáim.}
{231}{}{(Az öregember mosolyog, miközben a szemei körül jócskán meggyûlnek a ráncok.) Játszhatnéka van, barátom?}
{250}{}{Na, mégis mit gondol? Hát a játéknak!}
{260}{}{(Átnyújtod a pénzt. Ittapiros bólint, megmutatja a lapokat, aztán leteríti õket a földre, és néhány másodpercig kevergeti õket.)}
{280}{}{(Ittapiros megfordítja a lapot. A pikk kettest választottad.)}
{300}{}{(Átnyújtod a pénzt. Ittapiros rábólint, megmutatja a lapokat, aztán leteríti õket a földre. Miközben ezt teszi, az egyik kártyát a tenyerébe rejti, de olyan villámsebesen, hogy majdnem elsiklasz felette. Ezután néhány másodpercig még folytatja a keverést .)}
{320}{}{MIT mondott, pajti?}
{330}{}{Nincsen énnekem idõm a zsír kezdõkre. Maga fizet, ezért esélyt kap a nyerésre. Ha játszani akar, benne vagyok, de tûnjön innen, ha csak hõzöng itt nekem vesztéskor!}
{340}{}{(Átnyújtod a pénzt. Ittapiros bólint, aztán leteríti a lapokat és egy darabig kevergeti õket.)}
{360}{}{(Átnyújtod a pénzt. Ittapiros bólint, megmutatja a lapokat, aztán leteríti õket a földre, és néhány másodpercig kevergeti õket.)}
{375}{}{(Ittapiros megfordítja a lapot, amely nem más, mint a kõr dáma. A férfi szinte lebénul a meglepetéstõl.) Ah...? Ej...}
{385}{}{(Ittapiros megfordítja a kártyát, amely nem más, mint a kõr dáma. Teljesen ki van akadva ettõl.) Ööö... Hát ez...}
{400}{}{(Fájdalmas arcot vág.) Fenébe... azért még van valamim... SOKKAL többet ér, mint amennyit elnyert tõlem... egyelõre...}
{405}{}{Eh... hmnnn... attól függ, mit akar tudni.}
{415}{}{Eh... izé... hát nem tõlem hallotta, de szerintem Renesco a ludas. Õ az a seggarc, aki a nyugati kerületben vezeti a gyógyszertárat. Biztos ugyan nem vagyok benne, hogy épp õ adta volna el a gyereknek, de hogy tud valamit, az tutti. Ennél többet nem mondok.}
{420}{}{Hát... hogyismondjamcsak... (mintha magában vívódna)... hát nem tõlem hallotta, de a maga helyében lenéznék a Desperado alagsorába.}
{425}{}{(Hunyorítva közelebb hajol) Kérdezgesse a vén Jules-t az elõvárosban. Mindenrõl tud... vagy ha mégsem, akkor benne van a keze. Gondolom, tudja mirõl beszélek.}
{430}{}{Hát... azt tudta-e, hogy az az Eldridge fazon vezeti a New Reno-i Fegyverboltot? Azt állítja, hogy fegyvertuningolással is foglalkozik, de én még az életben nem láttam egyetlen munkáját se. Talán érdemes lenne benézni hozzá... persze nem tõlem hallotta.}
{435}{}{(Amint meglát, Ittapiros összevonja a szemöldökét.) Ma nem szerencsejátékozunk itt, értve? Le lehet kopni.}
{440}{}{Fenét! Én ugyan meg nem válok tõle. Pont. HAMISÍTATLAN háború elõtti ereklye... a történelem kis szelete. Haggyon engem békét ezzel!}
{450}{}{Süket maga? Ez az összeg még csak meg sem birizgálja az érdeklõdésemet.}
{460}{}{Hát, igazán nem is ANNYIRA kell már. A magáé, pajtás. (Félve jobbra-balra tekinget, aztán lenyúl és lehúzza a csizmáját. Elcsavarja a sarkát, és elõvesz belõle egy kártyalapot.) Tessék. Vigyázzon rá.}
{465}{}{(Szemöldökét ráncolja) Az, hogy beszélek-e attól függ, mit akar tudni. Ráadásul nem lesz olcsó.}
{475}{}{A Golgotát ne is említse, ÉRINTÕLEG sem! Kopjon le!}
{490}{}{(Megrázza a fejét.) Nincs az az isten! Már attól meghal valaki, ha beszélnek róla, lehet, hogy pont én. Üsse ki a fejébõl!}
{495}{}{Öö... izé... ez jó sok pééz. (Megnyalja az ajkait. Látszik, hogy vívódik magában... de csak rövid ideig.) Hát idefigyeljen, nem tõlem hallotta...}
{500}{}{(Horkant) Lehet, hogy hallottam ezt-azt, lehet, hogy nem. A dolgoknak ára van.}
{510}{}{Ha! Ennyiért egy vödör pisát sem kap. Hagyjon lógva!}
{515}{}{Eeeez már valami! (Gonosz módon vigyorog.) Hát nem tõlem hallotta, de ha a maga helyében lennék, lenéznék a Szûz utcai Desperado alagsorába. Egy csomó "patkány" van odalenn, ha veszi az adást.}
{520}{}{(Vállat von) Lehet, hogy tudok róla valamit, lehet, hogy semmit se. Térjünk az anyagiakra, és akkor talán megnyílik a szám.}
{530}{}{(Hunyorít és közelebb hajol) Azért az összegért én bizony nem tudok semmit.}
{535}{}{Ez már döfi... (Hunyorít és közelebb hajol) ...én megkérdezném a vén Jules-t az elõvárosban. Mindenrõl tud... és ha mégsem, akkor nyakig benne van. Remélem, érti, mire gondolok.}
{540}{}{(Vállat von) Hallok, látok ezt-azt. 200 dolcsiért hasznát veheti a tapasztalatomnak, ha érti, mire gondolok.}
{550}{}{Maga süket? 200 dolcsit mondtam, és nem a levegõbe beszéltem.}
{555}{}{Rendbe'. (Ittapiros közelebb hajol) Azt tudta-e, hogy az az Eldridge fazon vezeti a New Reno-i Fegyverboltot? Azt állítja, hogy foglalkozik fegyvertuningolással, de én még az életben nem láttam tõle semmit. Esetleg beugorhatna megnézni... persze nem tõlem hallotta.}
{560}{}{Csontlerakat a várostól délre. Bûzlik, mint a seggem, annyi szent.}
{565}{}{Fogadnék, hogy Renesco a ludas. Õ az a seggarc, aki a nyugati kerületben vezeti a gyógyszertárat. Biztos ugyan nem vagyok benne, hogy épp õ adta volna el a gyereknek, de hogy tud valamit, az tutti. (Körbeleseget.) Ennél többet nem mondok.}
{570}{}{(Félve jobbra-balra tekinget, aztán lenyúl és lehúzza a csizmáját. Elcsavarja a sarkát, és elõvesz belõle egy kártyát. A lapon egy fura fickó látható, kezében bunkóval.) Érdekli? Ez egy hamisítatlan háború elõtti ereklye.}
