# Dialog Editor last position: 32
{100}{}{Õ a csapos.}
{150}{}{A löttyedt fickó egykedvûen áll a pult mögött. Amikor rádnéz, fejével biccent egyet.}
{200}{}{Hé! }
{201}{}{! Jó munka volt farba billenteni az Enklávésokat! Akarsz valamit inni?}
{206}{}{! Mi a nagy helyzet?}
{210}{}{Egy adag rotgut rendel...}
{211}{}{Három dolcsi lesz...}
{212}{}{Esetleg egy másikat, haver?}
{213}{}{Itt egy érfogó, ha kell.}
{214}{}{Ne egyszerre lélegezd be a Jetet... szívj egy slukkot, végy mély levegõt, és hagyd, hogy átjárja a tested!}
{215}{}{Pohár vagy korsó?}
{216}{}{A Jet-belélegzõ extrának számít...}
{217}{}{Várj, kitalálom: Magad akarod eldönteni?}
{218}{}{Egy ütõs atombomba rendel...}
{219}{}{Nem engedjük, hogy a kuncsaftok Buffout-ozzanak itt, haver.}
{225}{}{Jobban tennéd, ha eltûnnél, mielõtt az egészséges szintnél több ólmot szolgálok fel! Megértetted?!}
{226}{}{Gyerünk... kifelé! Itt nem fogsz bajt keverni!}
{227}{}{Meg fognak ölni, ha ideszoksz. Kopj le!}
{228}{}{Mindenbõl kifogytunk. És most mi legyen, hülyegyerek?}
{236}{}{! Mivel akarod mérgezni magad?}
{237}{}{Héééé, bajnok! Mivel akarod mérgezni magad?}
{238}{}{Mivel akarod mérgezni magad, haver?}
{239}{}{Mivel akarod mérgezni magad, drágám?}
{240}{}{Méh-gezni hangoz jól.}
{241}{}{Mérgezni? Én nem akarni méreg!}
{242}{}{Mit tud adni?}
{243}{}{Milyen drogja van?}
{244}{}{Ki az az idõsebb fickó ott annál a szakadt játékgépnél?}
{245}{}{Ki az a késes fickó ott a bárpultnál?}
{246}{}{Most nem kérek semmit, kösz.}
{250}{}{Óh, a vén McGeere gondolsz? Többnyire ártalmatlan. Egy egész vagyont dobált abba az automatába, és évek óta semmit sem nyert. Amúgy... mit hozhatok, barátom?}
{260}{}{Az ott Jesus kisebbik fia, Kis Jesus. Õ meg a kése egész közeli barátok... magam láttam, milyen ördöngõs dolgokat tud vele csinálni. Amúgy... hozhatok valamit, barátom?}
