# Dialog Editor last position: 1
{100}{}{Ez itt egy vérmes bokszrajongó.}
{150}{}{Ez itt egy elég vad kinézetû ember. Torkaszakadtából üvölt valami kihámozhatatlant.}
{151}{}{Ez itt egy vérmes bokszrajongó. Láthatóan vért akar.}
{152}{}{Ez itt egy elég vad kinézetû ember. Zagyvaságokat üvölt torkaszakadtából.}
{153}{}{Ez itt egy vérmes bokszrajongó. Láthatóan vért akar.}
{200}{}{Igggeeeeeennnn!}
{201}{}{::rikolt:: ::üvölt:: ::rikolt::}
{202}{}{Öldd meg, }
{1202}{}{!}
{203}{}{Te vagy a legjobb, }
{1203}{}{!}
{204}{}{Kapd el õket, }
{1204}{}{!}
{205}{}{Igen! Adj neki!}
{206}{}{}
{1206}{}{a LEGJOBB! A LEGJOBB!}
{207}{}{}
{1207}{}{!!!}
{208}{}{}
{1208}{}{, te aztán vagy valaki!}
{209}{}{}
{1209}{}{ a legnagyobb bokszbajnok, akit valaha láttam.}
{210}{}{}
{1210}{}{ is nagyon ravasz. Tudja, hogy kell sérülést okozni a másiknak.}
{211}{}{}
{1211}{}{ foglalkozik a rajongóival. Nem szarik rájuk, mint a többi bokszoló.}
{212}{}{}
{1212}{}{ annyira jóképû.}
{213}{}{}
{1213}{}{ annyira férfias.}
{214}{}{A kedvencem }
{1214}{}{Áiiiijééééééééé!}
{215}{}{::sivít:: ::sivít::}
{216}{}{}
{1216}{}{ körültekintõ és ad a táplálkozásra. Ezt mondta nekem múlt éjszaka.}
{250}{}{}
{1250}{}{, te aztán vagy valaki!}
{251}{}{}
{1251}{}{ is nagyon ravasz. Tudja, hogy kell sérülést okozni az ellenfélnek.}
{252}{}{}
{1252}{}{ foglalkozik a rajongóival. Nem tojik rájuk, mint a többi bokszoló.}
{253}{}{Az hallottam, }
{1253}{}{, mielõtt New Renóba jött volna bokszolni, teljesen ismeretlen volt. Egyenesen a pusztából jött. Rejtélyes alak! Halálos ellenfél!}
{254}{}{Óhistenem! }
{1254}{}{! Hadd kérjek autogramot!}
{255}{}{Üss meg! Üss meg! El akarom mesélni a kölykeimnek, hogy megütöttél!}
{256}{}{Te vagy a legjobb, }
{1256}{}{! Mutasd meg nekik!}
{257}{}{Öldd meg, }
{1257}{}{!}
{258}{}{Te vagy a legjobb, }
{1258}{}{!}
{259}{}{Kapd el õket, }
{1259}{}{!}
{260}{}{Igen! Adj neki!}
{261}{}{}
{1261}{}{, te vagy a LEGJOBB! A LEGJOBB!}
{262}{}{}
{1262}{}{!!!}
{263}{}{Igggeeeeeeennn!}
{264}{}{::rikolt:: ::üvölt:: ::rikolt::}
{265}{}{}
{1265}{}{ a legnagyobb bokszbajnok, akit valaha láttam.}
{266}{}{}
{1266}{}{, te vagy a legkeményebb csaj a világon!}
{267}{}{Szívósabb vagy, mint Tyson neje!}
{268}{}{}
{1268}{}{, te aztán nõ vagy a javából!}
{269}{}{}
{1269}{}{ is nagyon ravasz. Tudja, hogy kell igazán bántalmazni valakit.}
{270}{}{}
{1270}{}{ törõdik a rajnogóival. Nem tojik a fejükre, mint a többi bokszoló.}
{271}{}{Az hallottam, }
{1271}{}{, mielõtt New Renóba jött volna bokszolni, teljesen ismeretlen volt. Egyenesen a pusztából jött. Annyira rejtélyes egy nõ!}
{280}{}{Egy szerencsecsókot?}
{281}{}{}
{1281}{}{, te aztán vagy valaki!}
{282}{}{}
{1282}{}{ annyira jóképû.}
{283}{}{}
{1283}{}{ olyan felépítésû, mint egy harckocsi!}
{284}{}{}
{1284}{}{ is nagyon ravasz. Tudja, hogy kell igazán bántalmazni az ellenfeleket.}
{285}{}{}
{1285}{}{ törõdik a rajongóival. Nem veszi õket semmibe, mint a többi bokszoló.}
{286}{}{Úgy hallottam, }
{1286}{}{, mielõtt New Renóba jött volna bokszolni, teljesen ismeretlen volt. Egyenesen a pusztából jött. Rejtélyes alak! Halálos ellenfél!}
{287}{}{Óhistenem! }
{1287}{}{! Adnál egy autogramot!}
{288}{}{Üss meg! Üss meg! El akarom mesélni a kölykeimnek, hogy megütöttél!}
{289}{}{Te vagy a legjobb, }
{1289}{}{! Mutasd meg nekik!}
{290}{}{Öldd meg, }
{1290}{}{!}
{291}{}{Te vagy a legjobb, }
{1291}{}{!}
{292}{}{Kapd el õket, }
{1292}{}{!}
{293}{}{Igen! Adj neki!}
{294}{}{}
{1294}{}{, te vagy a LEGJOBB! A LEGJOBB!}
{295}{}{}
{1295}{}{!!!}
{296}{}{Áiiijjjééééééé!}
{297}{}{::sivít:: ::sivít::}
{298}{}{}
{1298}{}{ a legnagyobb bokszbajnok, akit valaha láttam.}
{299}{}{}
{1299}{}{, te vagy a legkeményebb nõ a világon!}
{300}{}{Szívósabb vagy, mint Tyson felesége!}
{301}{}{}
{1301}{}{, te aztán nõ vagy a javából!}
{302}{}{}
{1302}{}{ is nagyon ravasz fajta. Õ aztán tudja, hogy kell az ellenfelet bántalmazni.}
{303}{}{}
{1303}{}{ törõdik a rajongóival. Nem tojik rájuk, mint a többi bokszoló.}
{304}{}{Úgy hallottam, }
{1304}{}{, mielõtt New Renóba jött volna bokszolni, teljesen ismeretlen volt. Egyenesen a pusztából jött. Annyira rejtélyes egy nõ!}
{320}{}{ mindenkit kinyír, aki az útjába áll!}
{321}{}{ a LEGJOBB! A LEGJOBB!}
{322}{}{!!!}
{323}{}{ a férfiak férfija!}
{324}{}{ a legnagyobb bokszbajnok, akit valaha láttam.}
{325}{}{ is nagyon ravasz. Tudja, hogy kell igazán bántalmazni az ellenfeleket.}
{326}{}{ törõdik a rajongóival. Nem ignorálja oket, mint a többi bokszoló.}
{327}{}{ annyira jóképû!}
{328}{}{ körültekintõ és ad a táplálkozásra. Ezt mondta nekem múlt éjszaka.}
{350}{}{}
{1350}{}{, te aztán férfi vagy a javából!}
{351}{}{Otthon egy üvegben õrzök az izzadságodból!}
{352}{}{Óhistenem! }
{1352}{}{! Adnál egy autogramot?}
{353}{}{Üss meg! Üss meg! El akarom mesélni a kölykeimnek, hogy megütöttél!}
{354}{}{Te vagy a legjobb, }
{1354}{}{! Adj nekik!}
{355}{}{Te vagy a legjobb, }
{1355}{}{!}
{356}{}{Menj és mutasd meg nekik, }
{1356}{}{!}
{357}{}{}
{1357}{}{, te vagy a LEGJOBB! A LEGJOBB!}
{358}{}{}
{1358}{}{!!!}
{359}{}{Igggeeeeeeennnn!}
{360}{}{}
{1360}{}{, te vagy a legnagyobb bokszbajnok, akit valaha láttam.}
{361}{}{}
{1361}{}{, te aztán tudod, hogy kell bántalmazni az ellenfelet.}
{362}{}{}
{1362}{}{, látom, törõdsz a rajongóiddal. Nem tojsz a fejükre, mint a többi bokszoló.}
{363}{}{Azt hallottam, mielõtt New Renóba jöttél volna bokszolni, teljesen ismeretlen voltál. Honnan jöttél végül is?}
{364}{}{}
{1364}{}{, te vagy a legkeményebb nõ a világon!}
{365}{}{Szívósabb vagy, mint Tyson felesége!}
{366}{}{}
{1366}{}{, te aztán igazi nõ vagy!}
{380}{}{Egy szerencsecsókot?}
{381}{}{}
{1381}{}{, igazi férfi vagy a javából!}
{382}{}{}
{1382}{}{, annyira jóképû vagy.}
{383}{}{::Ahogy beszélsz hozzá, elsápad::}
{384}{}{Otthon egy üvegben õrzök az izzadságodból!}
{385}{}{Óhistenem! }
{1385}{}{! Adnál egy autogramot?}
{386}{}{Üss meg! Üss meg! El akarom mesélni a kölykeimnek, hogy megütöttél!}
{387}{}{Te vagy a legjobb }
{1387}{}{! Mutasd meg nekik!}
{388}{}{Öldd meg, }
{1388}{}{!}
{389}{}{Te vagy a legjobb, }
{1389}{}{!}
{390}{}{Kapd el õket, }
{1390}{}{!}
{391}{}{.}
{1391}{}{, te vagy a LEGJOBBAK LEGJOBBIKA!}
{392}{}{}
{1392}{}{!!!}
{393}{}{Áijjjjééééééé!}
{394}{}{}
{1394}{}{, te vagy a legnagyobb bokszbajnok, akit valaha láttam.}
{395}{}{}
{1395}{}{, te aztán tudod, hogy kell fájdalmat okozni az ellenfélnek.}
{396}{}{}
{1396}{}{, te legalább törõdsz a rajongóiddal. Nem szarsz rájuk, mint a többi bokszoló.}
{397}{}{Azt hallottam, mielõtt New Renóba jöttél volna bokszolni, teljesen ismeretlen voltál. Honnan is jöttél hozzánk?}
{398}{}{}
{1398}{}{, te vagy a legkeményebb nõ a világon!}
{399}{}{Szívósabb vagy, mint Tyson felesége!}
{400}{}{}
{1400}{}{, te aztán nõ vagy a javából!}
