# Dialog Editor last position: 1
{100}{}{Egy kaszinósegéd.}
{150}{}{Ez itt az egyik kaszinósegéd. Fáradtnak látszik.}
{151}{}{Az egyik kaszinósegédhez van szerencséd. Szemében aranyszínû fény csillan.}
{152}{}{Õ az egyik kaszinósegéd. Arcát a kezébe temeti.}
{153}{}{Õ az egyik kaszinósegéd. Láthatóan becsípett egy kissé.}
{154}{}{Õ az egyik kaszinósegéd. Rádkacsint egy nagyot, aztán továbbáll.}
{155}{}{Õ az egyik kaszinósegéd. Egyfolytában próbálja felhívni magára a pincérnõ figyelmét.}
{156}{}{Ez a nõ kaszinósegéd. Eléggé fáradtnak látszik.}
{157}{}{Az egyik kaszinósegédhez van szerencséd. Szemében aranyszínû fény csillan.}
{158}{}{Õ az egyik kaszinósegéd. Arcát a kezébe temeti.}
{159}{}{Õ az egyik kaszinósegéd. A nõ láthatóan becsípett kissé.}
{160}{}{Õ az egyik kaszinósegéd. Rádkacsint egy nagyot, aztán továbbáll.}
{161}{}{Õ az egyik kaszinósegéd. Egyfolytában próbálja felhívni magára a pincér figyelmét.}
{200}{}{::Tapsol::}
{201}{}{::Éljenez::}
{202}{}{Faszán lenyomtad azokat az Enklávés barmokat! Nem semmi!}
{203}{}{Jól lezúztad az Enklávét!}
{204}{}{Gratula, hogy letapostad az Enklávét!}
{205}{}{Gratula, hogy letapostad az Enklávét!}
{206}{}{Ööö... Menjetek az útból!}
{207}{}{Nézz rá, akármiféle is legyen... megborzongok tõle...}
{208}{}{Szerinted az a valami rajtad elrettenti a népet?}
{209}{}{Pokoli tüzes kis test... Ööö, úgy értem a páncél alatt...}
{210}{}{Álljatok el az elõl az izé elõl!}
{211}{}{Egy veszélyes kinézetû emberrõl beszélnek a...}
{212}{}{*Nyel egyet*}
{213}{}{Asszem, Mr. Robotka megszkennelt egy kicsit.}
{214}{}{Az a sétáló tank rámnézett, és majd meghaltam! Na, akkor én mennék is...}
{215}{}{Az az izé ott, csak tegnap három verõembert szedett szét.}
{216}{}{Ha csak ránézek, kiver a víz...}
{217}{}{Szerintetek el akarja rettenteni a népet?}
{218}{}{Menjen mindenki az útjából!}
{219}{}{Asszem, rámnézett...}
{220}{}{Ajjaj, rámnézett és majd meghaltam! Na, akkor én mennék is...}
{221}{}{Azt hallottam, csak tegnap vagy három verõembert lõtt agyon...}
{222}{}{Öö... el az útból, mindenki!}
{223}{}{Pokolian tüzes egy test.}
{224}{}{Egy veszélyes kinézetû alakról beszéln...}
{225}{}{*Nyel egyet*}
{226}{}{La Femme Nikita, meg a hozzá hasonlók.}
{227}{}{Ha csak ránézek, elfog a borzongás.}
{228}{}{Szerintetek el akarja rettenteni a népet?}
{229}{}{Szerintem a nõ pont rámnézett...}
{230}{}{Úgy nézett rám, hogy majd meg haltam. Na, én léptem.}
{231}{}{Azt mondják, csak tegnap három verõembert lõtt agyon.}
{232}{}{Szép a feneke... úgy értem, fene kemény egy alak.}
{233}{}{Nem is tûnsz olyan keménynek, Mr. Bunyós.}
{234}{}{Volna 20 dolcsim, hogy kipróbáljalak!}
{235}{}{Hé, bajnok! Az uccsó meccs nagyon ott volt!}
{236}{}{Láttalak küzdeni a szorítóban. Király jobb horgokat nyomtál.}
{237}{}{Ugye nem fogsz lefeküdni a ringben? 30 dolcsit tettem rád.}
{238}{}{Mennyit nyomsz fekve?}
{239}{}{Hol edzel?}
{240}{}{Vigyázz a Húsdarálóval! A fülekre utazik.}
{241}{}{Ha nem az ellenfeledre fogadtam volna, maradt volna pénzem és hozhatnék neked egy italt.}
{242}{}{Nem is tûnsz olyan keménynek, Mr. Balhorog.}
{243}{}{Megnézhetem a befeszített hasizmodat?}
{244}{}{Azta! Azt kapjátok ki!}
{245}{}{Vetnél egy pillantást *arra*?}
{246}{}{::Szájával a "francba" szót formázza::}
{247}{}{TUDTAM, hogy reggel borotválkoznom kellett volna.}
{248}{}{Gyere, beszélgessünk már, piciny bogaram.}
{249}{}{Ezt az ungabunga csöcsöt! Berosálok!}
{250}{}{Nézd már milyen lökhárítója van annak a törzsbélinek!}
{251}{}{Ott az én nyájam legszebb példánya.}
{252}{}{Annak a nõnek a kedvéért megfürdenék.}
{253}{}{Nálam megtalálod a saját aranybányádat.}
{254}{}{Vigyázz szét ne ess!}
{255}{}{Ez az, ne hagyd abba!}
{256}{}{::Fütyül::}
{257}{}{Ezek aztán mutatós lábak...}
{258}{}{A francbaaaaaa.}
{259}{}{Szépségem, tetszik ahogy rázod! Áram is van hozzá?}
{260}{}{Lehet, hogy ma éjjel táncolni fog...}
{261}{}{Láttátok a legújabb filmjét? Nagyon király, nagyon-nagyon király!}
{262}{}{Elnézést, el kell mennem a mosdóba, és ööö... egy kicsit meg kell fésülködnöm.}
{263}{}{Szeretnék a bugyija lenni.}
{264}{}{Szívesen lennék a bugyija helyében.}
{265}{}{Hát megszagolnám a sortját...}
{266}{}{Az ott nagyon dögös egy csaj.}
{267}{}{Francba. Csupa ív... addig bámulom, míg kisodródok.}
{268}{}{Helló, csõdörke!}
{269}{}{Egy ilyen csõdör nem hiányolja a nyerget? Holnap éjjel szabad vagyok.}
{270}{}{Micsiná'sz ma, tengerész? Nem érsz rá?}
{271}{}{Megtapinthatom az izmaidat?}
{272}{}{Hogyhogy nem ájulsz el, ha erekciód van?}
{273}{}{Nem jössz el hozzám egy italra?}
{274}{}{A mellkasodról szeretnék vacsorázni.}
{275}{}{Nem kell egy partner a következõ filmedhez?}
{276}{}{::A bicepszedet bámulja.::}
{277}{}{Az ott valami pénzbedobós automata, ami folyton utánad lohol?}
{278}{}{Az ott egy robot pénzbedobós automata?}
{279}{}{A robotod tud trükköket? Ööö... úgy értem bûvésztrükköket.}
{280}{}{Ez nagyobb badarság, mint a róka esete, amikor csirkékbe lett szerelmes.}
{281}{}{Hadd pörögjön!}
{282}{}{Új cipõ kell a gyereknek...}
{283}{}{Franc esne a sóher turistákba...}
{284}{}{Az istenit! Már ötvenhárom dolcsinál tartottam, amikor...}
{285}{}{Na, ennyit az én híres szerencsémrõl...}
{286}{}{Ez közel volt!}
{287}{}{A bankra hajtok.}
{288}{}{Hogy én? A bankra hajtok. Figyelj csak...}
{289}{}{Az egész Ház ellenem volt.}
{290}{}{A szerencse elpártolt tõlem.}
{291}{}{Fortuna, ne hagyj el!}
{292}{}{A Ház megkegyelmezett rajtam.}
{293}{}{A tippek meg a beszívott költekezések között...}
{294}{}{Csak játssz még ebben a stílusban egy darabig és hamarosan a Golgota lesz az otthonod.}
{295}{}{Pincér, még egy italt!}
{296}{}{Pincér, még egy italt!}
{297}{}{Ez a pia eléggé... fura ízû...}
{298}{}{Kezdek belejönni!}
{299}{}{Már elköltöttem az összes pénzem?}
{300}{}{A szerencse egy rohadt ribanc... az anyósommal együtt.}
{301}{}{Mostanában jól megszaporodtak erre a hajcsárok.}
{302}{}{Érdekelne, mi folyik a városon kívüli istállóban.}
{303}{}{Hamarosan megint balhé lesz.}
{304}{}{A helyiség tele van mocskos csalókkal...}
{305}{}{Nagyszerû, egy újabb sóher.}
{306}{}{Annyira tudok!!!}
{307}{}{Majd alszom, ha meghaltam.}
{308}{}{Öcsém, pisálnom kell! Mindjárt széthasadok.}
{309}{}{Öcsém, ki kell csavarnom a gyíkot...}
{310}{}{A francba, hogy bárkit beengednek ide...}
{311}{}{Gyerünk hetes!}
{312}{}{Parádésan nézel ki, bébi.}
{313}{}{Na, ki a mai nap nagy nyertese? Naná, hogy Mikey!}
{314}{}{Ugyan, ne szállj má' ki!}
{315}{}{Repülnöm kell egyet... gondolom tudod, mire célzok.}
{316}{}{Ez egy bõdületes nagy BAROMSÁG!}
{317}{}{Végül is csak 60 dolcsit vesztettem. Igaz, hogy az elmúlt öt perc alatt.}
{318}{}{Piros 23-as! Piros 23-as! Gyerünk... piros 23-as!}
{319}{}{50 dolcsit a fekete 15-re...}
{320}{}{Gurul a golyócska, ki tudja hol áll meg... ki tudja hol áll meg, s kit hogyan talál meg...}
{321}{}{Jól elintézted azokat az Enklávés gyíkokat! Nagy dolog volt!}
{322}{}{Mindig tudtam, hogy az Elnök mindannyiunkat ki akar nyírni.}
{323}{}{Élt még az Elnök? Mikor is volt az utolsó választás?}
{324}{}{Jól lenyomtad az Enklávét, mi? Na, hadd vegyek neked egy italt!}
{325}{}{Szuper, hogy lenyomtad az Enklávét!}
{326}{}{Az Enklávé megsemmisítésével ez a kaszinó már sokkal jobb hely lesz a gyerekeim számára. Hogyan tudnám ezt valaha is megköszönni?}
{327}{}{Az Enklávé nem sok fejfájást okozott nekem, de azért örülök, hogy végük.}
{328}{}{Egyszerûen nem hiszem el, hogy az Enklávé ennyi idõ után még mindig a háborúskodással foglalkozott. Komplett hülyék.}
{329}{}{Érzem, hogy valami háborog... mintha több száz gonosz pöcsfej kiáltott volna fel végsõ kétségbeesésében egy olajfúrótornyon, aztán néma csend lett. Különös.}
{330}{}{Gratula, hogy eltapostad az Enklávét, }
{331}{}{Gratula, hogy eltapostad az Enklávét, }
{332}{}{Robi testvéredet keresed? Tudod, a Robot? Na, mindegy, hagyjuk...}
{333}{}{Elnézést, az utadban álltam? Elmegyek egy másik városba!}
{334}{}{Bocs, hogy elszívom elõled a levegõt! Most rögtön abbahagyom.}
{335}{}{Nem jutott el a tudatomig, hogy az ajtókat a te méretedre gyártották.}
{336}{}{::Megkopogtatja a páncélt:: Van valaki odabenn?}
{337}{}{"Veszélyben a Robinson család! Veszélyben a Robinson család!" Hehe... ööö... csak vicceltem.}
{338}{}{Kiráááály ez a páncél! Van benne légkondi?}
{339}{}{Nincs meleg odabenn?}
{340}{}{Hozzádörzsölhetem a kockáimat a páncélodhoz, hogy szerencsém legyen?}
{341}{}{Elhagytad a szíved, bádogember?}
{342}{}{Öö, üdv, uram... vagy hölgyem... vagy akármi van odabenn.}
{343}{}{Add át elismerésem annak, akitõl ezt a páncélt kaptad.}
{344}{}{Nincs semmi gond, uram... hölgyem... ööö, vagy akármi is legyen?}
{345}{}{Te vagy az új kidobó? Vagy csak egy új sétáló játékautomata?}
{346}{}{Nem, nem fogom megolajozni az eresztékeidet!}
{347}{}{Az a páncél nem képes repülõvé alakulni és röpködni? Csak kíváncsi vagyok.}
{348}{}{Persze, persze, jó "csitt-csatt, dirr-durr"-t kívánok neked is...}
{349}{}{Ha azt hiszed, hogy meg tudsz félemlíteni azzal a páncéllal... akkor igazad van.}
{350}{}{Á, tudom már... te egy háború elõtti videójáték konzol vagy.}
{351}{}{Nézd... nem akarok bajt. Csak egy napig leszek a városban.}
{352}{}{Légyszi... nem akarok balhét.}
{353}{}{Bocs, hogy elálltam az utad. Már megyek is egy másik városba.}
{354}{}{Bocs, hogy elszívtam elõled a levegõt. Abbahagyom.}
{355}{}{Add át üdvözletem a fõnöködnek!}
{356}{}{Ööö.. *nyel egyet* ...van valami gond?}
{357}{}{Légyszi... nem akarok bajt, sejtheted. Csak egy napig leszek a városban.}
{358}{}{Nézd... nem akarok balhét.}
{359}{}{Árulsz valamit?}
{360}{}{Megvásárolhatom az öltözéked? Úgy értem most azonnal.}
{361}{}{Tudtam, hogy borotválkoznom kellett volna reggel.}
{362}{}{Gyere, beszélgessünk már, tündibündi!}
{363}{}{Gyere, tündérke...sétáljunk egyet!}
{364}{}{Ügyes kis buksza vagy, mi?}
{365}{}{A kedvedért megfürdenék.}
{366}{}{Itt van a te különbejáratú aranybányád.}
{367}{}{Ezek aztán mutatós lábak...}
{368}{}{Táncolsz ma este?}
{369}{}{Elnézést, el kell mennem a mosdóba, és ööö... egy kicsit meg kell fésülködnöm.}
{370}{}{Szeretnék a bugyid lenni.}
{371}{}{Hát megszagolnám a sortodat...}
{372}{}{Nagyon dögös egy csajszi vagy ám.}
{373}{}{Javíts ki, ha tévednék, de nem akarsz megcsókolni?}
{374}{}{Francba. Csupa ív... addig bámulom, míg kisodródok.}
{375}{}{Tudod mi állna jól rajtad? Én.}
{376}{}{Lehet, hogy a bugyid nem a legjobb dolog a világon, de nem sok választ el tõle.}
{503}{}{!}
{504}{}{! Te vagy a legkirályabb! Te vagy a LEGKIRÁLYABB!}
{505}{}{! Te aztán vagy VALAKI!}
{625}{}{!}
{630}{}{! Király vagy! KIRÁLY VAGY!}
{631}{}{! Te aztán vagy VALAKI!}
