# Dialog Editor last position: 1
{100}{}{Õ Chris Wright.}
{150}{}{A fiatalember punk-taréjt visel, ezenkívül bõrszerkót és egy rakás láncot hord.}
{151}{}{A fiatalember Chris Wright.}
{152}{}{Õ Chris Wright. Unottan néz ki a fejébõl.}
{200}{}{Hé! }
{201}{}{Kitartás, }
{202}{}{Mindent bele, }
{203}{}{::Éljenez::}
{204}{}{::Tapsol::}
{205}{}{::Fütyül::}
{215}{}{Hogy mész fürdeni, ha rajtad van ez az izé?}
{220}{}{Na, mi van, }
{221}{}{Nincsen meleg odabenn, }
{222}{}{Na, mi van, }
{230}{}{Még minding nem hiszem, hogy apu meghalt. Annyi mindent akartam neki mondani...}
{235}{}{Tûnés!}
{236}{}{Tûnj el, nem mondom még egyszer!}
{237}{}{Nincs mit mondanom neked.}
{245}{}{Eggen?}
{246}{}{Hé! Hogy mennek a dolgok?}
{1246}{}{? Jól bánnak veled? Nincs szükséged semmire?}
{247}{}{A hálám mindig üldözni fog, amiért megtaláltad Richard gyilkosát.}
{248}{}{. Jövök neked eggyel, és a Wright család mindig kifizeti az adósságát. Miben segíthetek?}
{249}{}{Gyarló. Ember gyarló!}
{250}{}{Hubajube}
{251}{}{Otthagyod}
{252}{}{Ki vagy te?}
{253}{}{Azt kell mondjam, igen. Munkát keresek. Van valami betöltendõ állás a Wright családnál?}
{254}{}{Összefutottam édesanyáddal.}
{255}{}{Mondanál valamit Richard-ról?}
{256}{}{Kösz, semmit. Bocs, hogy zavartalak.}
{265}{}{Kopj le, te retardált! Nincs idõm, hogy nekiálljak jel-beszélgetni veled!}
{266}{}{Elbattyogsz}
{275}{}{Chris Wrightnak hívnak. A Wright családból. Kielégítõ válasz?}
{276}{}{Hogyne. Munkát keresek. A Wright család épp nem keres valami munkaerõt?}
{277}{}{Semmit nem tudok a Wright családról.}
{278}{}{Chris Wright? Összefutottam a mamáddal.}
{279}{}{Tudsz valamit mondani arról, mi történt Richard öcséddel?}
{280}{}{Nem igazán. Bocs, hogy zavartalak.}
{290}{}{Nem hallottál a Wright családról? Jó sokat lehettél a sivatagban! A Wright család a legnagyobb bûnszövetkezet Renóban. Mi fogjuk uralni a várost.}
{291}{}{Valóban? Úgy tûnik, a Wright családnál vannak a legjobb lapok. Nem akarnak felbérelni senkit?}
{292}{}{Igazság szerint épp arra gondoltam, hogy õk a leggyengébb család... Úgy értem, csak alkoholban utaznak, nincs kaszinó, meg drogkereskedelem, és a család létszáma is alacsonyabb, mint a többieké.}
{293}{}{Ha már a családnál tartunk, összefutottam édesanyáddal.}
{294}{}{El tudnád mondani, mi történt Richard öcséddel?}
{295}{}{Igazán? Nagyon érdekes... nos hát... most mennem kell.}
{305}{}{Úgymint?}
{306}{}{Mondanál valamit a Wright családról?}
{307}{}{A Wright család szokott embereket felbérelni?}
{308}{}{Nem olyan régen összefutottam édesanyáddal. Kedves asszony.}
{309}{}{El tudnád mondani, mi történt Richard öcséddel?}
{310}{}{Nem, nincs több kérdésem. Jobb, ha megyek.}
{315}{}{(A fiatalember feléd fordul, végigmér tetõtõl talpig. Szeme megakad a homlokodon lévõ jelen.) Vagy úgy. (Lekicsinylõen néz rád, és leköpi a lábad.) Miért nem teszed hasznossá magad azzal, hogy lenyalod, hajcsár?}
{316}{}{(A fiatalember feléd fordul, végigmér tetõtõl talpig.) Vagy úgy. (Lekicsinylõen néz rád, és leköpi a lábad.) Miért nem teszed hasznossá magad azzal, hogy lenyalod, te fosarcú gyökér?}
{317}{}{Belerúgsz azzal a lábaddal, amit leköpött.}
{318}{}{Elslattyogsz}
{319}{}{Békén hagyod és elmész. Ezúttal...}
{325}{}{Hogyismondjam... az a helyzet, hogy a Wright család... az én családom... talán tud ajánlani egy állást. Nem ígérek semmit, de menj a dél felé lévõ kúriához, keresd fel Keith bátyámat, és mondd meg neki, hogy én küldtelek. A nevem Chris Wright.}
{326}{}{Öö... Wright családot mondtál? Kik õk?}
{327}{}{Wrightot mondtál? Összefutottam édesanyáddal.}
{328}{}{El tudod mondani, mi történt Richard öcséddel?}
{329}{}{Köszi. Megyek és beszélek vele.}
{335}{}{Neeem, nem hinném, hogy bárki foglalkozna itt új emberek alkalmazásával. A családok többségében igen nagy az összetartás.}
{336}{}{Rendben.}
{345}{}{Ó, ez király. Beszélgettetek?}
{346}{}{Egy kicsit. Nem szereted a mamádat?}
{347}{}{Nem. Gyakran szokott beszélgetni idegenekkel?}
{348}{}{Nem igazán. Figyu, most mennem kell.}
{355}{}{Ez *vicc* akart lenni? Ha igen, alaposan mellélõttél vele. Akarsz valamit a Wright családtól, okoska?}
{356}{}{Hogy akarok-e valamit? Hát persze. Ki akarom nyírni az egész családot.}
{357}{}{Nem, elnézést. Nem akartam semmi bántót mondani. Kérdezhetek ezt-azt?}
{358}{}{Nem, egyáltalán nem. Asszem, most jobb, ha megyek.}
{365}{}{Anyám egyszerûen nem figyel a maga körül történõ dolgokra. Szeretem õt, meg minden, de néha annyira vak, mint a halál.}
{366}{}{Hát nem is olyan régen anyám berontott a szeszfõzdénkbe, és szétbarmolta az egészet, megsemmisítette a pénzforrásunkat! Szeretem õt, meg minden, de néha annyira vak, mint a halál.}
{367}{}{Hehe. És úgy is néz ki.}
{368}{}{Mit értesz az alatt, hogy vak?}
{369}{}{Óh, hát akkor valami mást kérdeznék...}
{370}{}{Nem kétlem... most viszont mennem kell.}
{380}{}{Jár-kel fel-alá és a bûnbeesésrõl papol, meg ilyenek, de nem tudja igazán, Apu mit csinál. Vagy ha igen, nem vesz róla tudomást.}
{381}{}{Miért, mit csinál az édesapád?}
{382}{}{Hmmmm. Feltennék még inkább néhány kérdést...}
{383}{}{Érdekes, viszont most mennem kell.}
{390}{}{Alkoholt gyárt, fegyvereket ad el, kicsinál embereket, akik baszakodnak vele... tipikus családi elfoglaltságok. Anyám kiakadna, ha tudná, hogy tulajdonképpen mi folyik a háttérben. Különösen, ha itt megtalálná a szeszfõzdét.}
{391}{}{Mennyire akadna ki?}
{392}{}{Hmmm. Hát akkor kérdeznék valami mást...}
{393}{}{Érdekes-érdekes. Viszont most mennem kell.}
{400}{}{Annyira biztos, hogy szétverné ezt a helyet... minimum. Valszeg szétmagyarázná a fejét és néhány napig folyamatosan imádkozhatnánk. Hehe.}
{401}{}{Érdekes... Kérdeznék mást...}
{402}{}{Hmmmmm. Köszi.}
{410}{}{A Richie-t kérded? Hát tudod, úgy találtunk rá, mint a többi jet-használóra, otthagyták egy árokban. Amennyire meg tudtuk állapítani, valaki halálra pumpálta droggal.}
{411}{}{"Valaki" túl sokat adott be neki? Mibõl gondolod, hogy nem saját magát adagolta túl?}
{412}{}{Szerinted ki csinálhatta?}
{413}{}{Szomorúan hallom ezt. Kérdeznék még egy s mást...}
{414}{}{Mocskos dolog ez. Figyu, most mennem kell.}
{420}{}{Mert az a gyerek tiszta volt... az anyám SOKMINDENRE megtanította. Ha pedig más lenne a véleményed, itt helyben lerendezhetjük.}
{421}{}{Nem úgy gondoltam. Bocs, hogy felhoztam a témát.}
{422}{}{Ne vakítson el a gondolat, hogy magának csinálta. A Jet hihetetlenül addiktív.}
{423}{}{Nézd, KÖLYÖK, ha szereted még az élet napos oldalát, akkor egy kis fájó igazság hallatán ne gyere nekem a bunyóval...}
{424}{}{Szerinted ki tehette?}
{425}{}{Én nem keresem a bajt. Csá...}
{435}{}{Na, nehogy már! Ezt bármelyik Wright beszólásnak venné, szóval, ha lennél olyan szíves ne dobálózz itt a kemény szavakkal!}
{436}{}{Ne vakítson el a gondolat, hogy õ csinálta magának. A Jet hihetetlenül addiktív.}
{437}{}{Nézd, KISFIAM, ne szarakodj itt velem! Ha szereted még az élet napos oldalát, akkor egy kis fájó igazság hallatán ne gyere nekem a bunyóval...}
{438}{}{Bocs, nem akartam beszólni. Kérdeznék inkább valami mást...}
{439}{}{Megértettem. Akkor most inkább megyek.}
{445}{}{Tûnj el! Nem akarok veled tovább beszélni!}
{446}{}{Várj, egyetlenegy kérdésem lenne még...}
{447}{}{Megyek, megyek...}
{455}{}{(Chris egy pillanatig rádbámul, aztán neked ugrik!)}
{456}{}{Szóval ennek így kell lennie, he? RENDBEN, AKKOR GYERÜ...}
{465}{}{Én a Mordinókra szavaznék. Vagy az egyik dílerükre, vagy az egyik Mordinóra személyesen. Azok a gyökerek tonnaszám gyártják a Jetet.}
{466}{}{Fogom. Na, akkor kérdezek mást...}
{467}{}{Szerinted melyik díler adhatta el Richard-nak?}
{468}{}{Értem. Most mennem kell.}
{475}{}{Bármelyik lehetett: vagy Csipkés Jimmy J., az a sebhelyes faszkalap a Szûz utca sarkán, vagy az a görény Rakétás Renesco, aki a Nyugati Negyedbeli erõdített házikójában árusítja a Jetjét.}
{476}{}{Van még más díler is?}
{477}{}{Fogom. Akkor most kérdezek mást...}
{485}{}{Haver, köszönöm NEKED!!!}
{486}{}{Te kislány, köszönöm NEKED!!!}
{487}{}{Rájöttél, ki ölte meg az öcsémet. Az egész Wright család köszönettel tartozik neked. És ez bizony nem akármi ám!}
{488}{}{Értem. Késõbb találkozunk, Chris.}
{495}{}{A város szélén tevékenykedõ Jules szintén árul Jetet, de õ leginkább a turistákat veszi célba... aztán ott van a Kis Jesus Mordino, akár õ is telenyomhatta Richie-t, amikor egyedül volt. A csávó a Desperadóban szokta múlatni az idõt.}
{496}{}{Fogom. Viszont kérdeznék még egy s mást...}
{497}{}{Csipkés Jimmy J, a Rakétás Renesco, Jules és Kis Jesus... mindegyiknek utánanézek. Kösz az infóért, Chris.}
{1200}{}{! Jó munka volt picsán rúgni az Enklávét!}
{1201}{}{! Büszke lehetsz magadra!}
{1202}{}{!}
{1220}{}{. Mi járatban?}
{1221}{}{?}
{1222}{}{. Hogy mennek a dolgok mostanában?}
