# Dialog Editor last position: 1
{100}{}{Egy rakás ládát látsz, melyekbe vegyi anyagokat pakoltak.}
{150}{}{Egy rakás ládát látsz, melyekbe vegyi anyagokat pakoltak. Nem tudod õket beazonosítani, de a csomagolás *szerfelett* gondos.}
{175}{}{Ez itt egy Gépmadár.}
{199}{}{Ez itt egy Gépmadár... a helikopter továbbfejlesztett változata. Sajnos gõzöd sincs, hogy lehetne elvezetni.}
{200}{}{(Ezektõl a srácoktól összecsinálom magam...)}
{000}{}{(Pofa be! Ott jönnek.)}
{000}{}{*Zzttt* Maguknál van az igényelt áru? *Zzzttt*}
{000}{}{Igen, az összes vegyi anyag itt van. Ha gondolja, ellenõrizze le!}
{000}{}{*Zztttt* Erre nincs szükség. *Zzzttt*}
{000}{}{*Zztttt* Azt tudja, mi történik abban az esetben, ha a vegyi anyagok minõsége nem üti meg a kívánt mértéket? *Zzzttt*}
{000}{}{Hogyne, természetesen. Ööö... és maguk hozták a fényhozókat...?}
{000}{}{*Zztttt* A lézerfegyverek a rakodóterünkben vannak. *Zzzttt*}
{000}{}{*Zztttt* A kooperáció biztonsága érdekében az élesítõ kódokat a vegyi anyagok átpakolása után fogjuk továbbítani. *Zzzttt*}
{000}{}{Ööö... hát... akkor rendben. Rakodás indul, fiúk...}
{000}{}{*Zztttt* Megállni! *Zztttt*}
{000}{}{*Zztttt* A rakományt mi pakoljuk át. *Zztttt*}
{000}{}{Öö, rendben... rendben. Természetesen. Adjatok helyet, fiúk!}
{000}{}{Kész! Itt rendben vagyunk. A többi õr... te is, zöldfülû... irány vissza Renóba! Ott találkozunk.}
{250}{}{Odanézzetek! Valaki kifigyelt bennünket!}
{000}{}{Megölni!}
{000}{}{Úgy tûnik, valaki kémkedik utánunk...!}
{000}{}{*Zztttt* Küldetés lefújva! A rakomány vészhelyzeti kódját aktiváltam. *Zztttt*}
{000}{}{*Zztttt* Küzdjék le az ellenséges erõket, aztán térjenek vissza a bázisra! *Zztttt*}
{300}{}{Nem kéne közel menni azokhoz a páncélozott faszikhoz! Mindent szecskává aprítanak.}
{000}{}{Menj vissza a helyedre!}
{000}{}{Ne izegj-mozogj... azok a páncélos fickók nem nagyon szeretik ezt!}
{350}{}{Francba! Mit csinálsz, faszkalap?}
{000}{}{Menjen vissza a posztjára! Mi a jó francot csinál maga...?!}
{000}{}{*Zztttt* Küldetés lefújva! A rakomány vészhelyzeti kódját aktiváltam. *Zztttt*}
{000}{}{*Zztttt* Küzdjék le az ellenséges erõket, aztán irány a bázis! *Zztttt*}
{400}{}{[Úgy tûnik, ez egy ajtó. Kinyitod és bemászol?]}
{000}{}{Ja}
{000}{}{Elpályázol}
{000}{}{Beszállsz a Gépmadárba.}
{000}{}{Békén hagyod.}
{450}{}{[Az ajtó lezáródik mögötted és a Gépmadár felszáll! Az ajtó nem nyitható!]}
{000}{}{Ajjaj}
{000}{}{Bakker...}
{500}{}{A ládák csupa nehézfém tartállyal vannak tele. A csomagolás gondosságából ítélve azt gyanítod, hogy valami veszélyes vegyianyagról lehet szó.}
