# Dialog Editor last position: 1
{100}{}{Ez itt egy ökölvívó.}
{101}{}{Õ Evan Hollyfeld.}
{150}{}{Ez itt egy zömök fickó, masszív, szögletes állkapoccsal. A fülei alaposan meg vannak tépázva.}
{151}{}{A fülei alaposan meg vannak tépázva.}
{152}{}{A fülei alaposan meg vannak tépázva.}
{200}{}{Hnffff}
{201}{}{Hnrrgggg}
{202}{}{::Nyöszörögve tapogatja a fülét::}
{203}{}{::Befeszít::}
{300}{}{::A füleihez nyúlkál és közben egyre csak bámul::}
{301}{}{Én csípni fejelés}
{302}{}{Én meg Mike fejeltünk}
{303}{}{Én megfejel Mike õ harapja fülem}
{304}{}{Mike harapja fülem mer' éhes}
{305}{}{Én hallani nem jól}
{306}{}{::Megvakarja a füle helyét::}
{307}{}{He?}
{308}{}{Mi? Én nem hall jól.}
{309}{}{Egyszer ül, máskor fül}
{310}{}{Harapol?}
{311}{}{Hell-ó jóillatú}
{312}{}{Hell-ó lánka}
{313}{}{Akarol fejelõdni}
{314}{}{Én szeret fejelés}
{315}{}{Én meg Mike fejelünk}
{316}{}{Megfejel Mike õ meg harap le fülem}
{317}{}{Mike harapja fülem mer éhes}
{318}{}{Nem hallok jól}
{319}{}{::Megvakarja a füle helyét::}
{320}{}{He?}
{321}{}{Mi? Nem hallak.}
{322}{}{Egyszer ül máskor fül}
