# Dialog Editor last position: 1
{100}{}{Ez itt egy lepusztult csöves.}
{101}{}{Ez egy hiperaktív csöves.}
{150}{}{Ez itt egy lepusztult csöves. Nagyon lassan mozog.}
{151}{}{Ez itt egy lepusztult csöves. Betegnek tûnik.}
{152}{}{Ez itt egy lepusztult csöves. Olyan sovány, hogy a legkisebb szél is elfújná.}
{153}{}{Ez itt egy lepusztult csöves. Üres tekintettel néz vissza rád.}
{154}{}{Ez itt egy lepusztult csöves. Olyan véreresek a szemei, hogy akár vért tudna könnyezni.}
{155}{}{Ez itt egy lepusztult csöves. Akármikor mozdul egyet, összerezzen, mintha tûkkel szurkálnák.}
{156}{}{Ez itt egy lepusztult csöves. A szemei táskásak, arcán fájdalmas kifejezés ül.}
{160}{}{Ez itt egy csöves. Arcán üdvözült kifejezés ül.}
{161}{}{Ez itt egy csöves. Arcán halovány mosoly ül és valami érzékelhetetlen ritmusra mozog.}
{162}{}{Ez itt egy csöves. Üresen bámul a semmibe.}
{163}{}{Ez itt egy csöves. Mosolyog és mögéd integet.}
{164}{}{Ez itt egy csöves. Egyfolytában tapogatja az arcát és magában mormog.}
{165}{}{Ez itt egy csöves. A szeme alatt lévõ táskák ellenére úgy mosolyog, mintha épp az imént nyert volna a lottón.}
{170}{}{Ez itt egy lepusztult csöves. Nagyon lassan mozog.}
{171}{}{Ez itt egy lepusztult csöves. A nõ úgy néz ki, mint aki hónapok óta nem evett.}
{172}{}{Ez itt egy lepusztult csöves. Annyira sovány, hogy a legkisebb szél is elfújná.}
{173}{}{Ez itt egy lepusztult csöves. A szeme akár egy kiment biztosíték.}
{174}{}{Ez itt egy lepusztult csöves. Éhes pillantásokat vet rád.}
{175}{}{Ez itt egy lepusztult, véreres szemû csöves.}
{176}{}{Ez itt egy lepusztult csöves. Akárhányszor mozdul egyet, összerezdül, mintha tûvel szurkálnák.}
{177}{}{Ez itt egy lepusztult csöves. A szeme táskás, az arcán fájdalmas kifejezés ül.}
{180}{}{Ez itt egy csöves. A nõ arcán üdvözült kifejezés ül.}
{181}{}{Ez itt egy csöves. Egyszerre sír és nevet.}
{182}{}{Ez itt egy csöves. Egyfolytában mosolyog és valami nem hallható zenére táncol.}
{183}{}{Ez itt egy csöves. A semmibe bámul és sóhajtozik.}
{184}{}{Ez itt egy csöves. Egyfolytában mosolyog és mögéd integet.}
{185}{}{Ez itt egy csöves. Folyamatosan vakarja a kézfejét.}
{186}{}{Ez itt egy csöves. Ide-oda hajlong és alig bír megállni a lábán.}
{187}{}{Ez itt egy csöves. Lerobbant kinézete ellenére úgy mosolyog, mintha épp az imént nyert volna a lottón.}
{200}{}{::Éljenez, aztán összerezzen::}
{201}{}{::Erõtlenül tapsol, minden egyes tapsnál összerezdül::}
{202}{}{::Alig hallhatóan fütyül::}
{210}{}{Te vagy a legjobb... öö valami. Te vagy a legjobb VALAMI!}
{211}{}{::Ordít::}
{212}{}{, még a JET-nél is jobb vagy!}
{213}{}{::Vadul éljenez::}
{214}{}{::Vadul tapsol::}
{215}{}{::Fütyül::}
{220}{}{A fejem...}
{221}{}{Kész vagyok... kész vagyok...}
{222}{}{Rosszabb, mint múltkor...}
{223}{}{Szerintem ez nagyon-nagyon sokáig így marad...}
{224}{}{::Óóóóóóó::}
{225}{}{::Sír::}
{226}{}{::Köhög::}
{227}{}{::Vakaródzik::}
{228}{}{::Magában mormog::}
{229}{}{Ez így... így nem mehet... tovább...}
{230}{}{Láttad Jules-t mostanában? Kéne anyag.}
{231}{}{Láttad Csipkés Jimmy J.-t mostanában? Kéne anyag.}
{232}{}{Renesco gyógyszertárába igyekszem. Ott majd helyrepofoznak.}
{233}{}{Tudom, hogy a Fallout 2 nem 3D játék, de igazán kihasználhatná a legújabb 3D-s kártyámat. Viszont mûködik XP-n, ami nagy szó!}
{240}{}{[Énekel.] Ez az adag éppen jó, ez az anyag éppen jó... Összeraknám a testem egy másik égi testen.}
{241}{}{[Énekel.] Félre a tréfát ûrhajós vagyok, ...mm mm... még egy rakétát! }
{242}{}{Vigyázat! Rózsaszín halálkarom három óránál!}
{243}{}{Túl sok a fény! Kiégeti a szemem, kiégeti a szemem...}
{244}{}{A fények... túl erõsek... ::Elsírja magát::}
{245}{}{Reeeeeeeeno. Reeeeeeeeno. Reno?}
{246}{}{Hol hagytam a fejem?}
{247}{}{Igyál sört, szívjál füvet}
{248}{}{}
{249}{}{::Kuncog::}
{250}{}{::Nevet::}
{251}{}{::Mosolyog és enyhén imbolyog::}
{252}{}{Ihhhiiiiiijjjjjjjjjjjjjjjjjjj}
{253}{}{Szójafasírt. Szójakolbász. Szójatok a nõvérnek, hogy beálltam.}
{254}{}{Hééló... hova tûnt az égbolt?}
{255}{}{Ha a ruhám nem hagyja abba a pofázást, én rögtön leveszem.}
{256}{}{Lélegzik a cipõm!}
{257}{}{Tudom, hogy a Fallout 2 nem 3D játék, de igazán kihasználhatná a legújabb 3D-s kártyámat. Viszont mûködik XP-n, ami nagy szó!}
{258}{}{Te engem bámulsz?! Te engem bámulsz?!! Megöllek!}
{270}{}{Öö... megünnepelném veled az Enklávés gyõzelmet, de a fejem tisztára lüktet. Gyere vissza éjszaka!}
{271}{}{::Próbál tapsolni, de nem sikerül::}
{272}{}{Remek volt! Túlságosan belõttem magam, hogy tudjam, mit csináltál, de biztos nagyszerû dologról van szó.}
{273}{}{Ööö... kösz, hogy megmentettél minket. Van... ööö... egy kis felesleges apród?}
{274}{}{Már én is megmentettem egyszer a világot. Talán túlságosan be voltam lõve.}
{275}{}{Az Enklávénak volt Jetje?}
{276}{}{Te okoztad azt a nagy pukkanást délen? Megfájdult tõle a fejem.}
{277}{}{Tudom, hogy megmentetted a világot, de nekünk, mellékszereplõknek kell viselni a következményeit.}
{278}{}{Engem Chris Avellone tervezett és Tom French szkriptelt. Nem én tehetek a Jetfüggõségemrõl.}
{279}{}{Igen, igen, nagyszerû, hogy megnyerted a játékot. Gondolom ez azt is jelenti, hogy hamarosan letörölsz minket a vinyódról. Elõre is kösz.}
{291}{}{Te vagy a legjobb... öö, valami. Te vagy a legjobb VALAMI!}
{292}{}{, te még a JET-nél is jobb vagy!}
{293}{}{Ember, bárcsak láthattam volna azt a robbanást, miközben be voltam lõve. Nem lehetett semmi, he?}
{294}{}{IMÁDLAK! HÕS VAGY. EGY ISTENVERTE HÕS. HALÁLRA TUDNÁLAK ÖLELNI.}
{295}{}{Ha legközelebb mész Enklávét gyakni, engem is vigyél!}
{296}{}{Király vagy, }
{297}{}{Tudom, hogy megmentetted a világot, de nekünk, mellékszereplõknek kell viselni a következményeit.}
{298}{}{Újra végig kéne játszanod a játékot egy drogfüggõ karakterrel. Tényleg! Válaszd ki a Drogfüggõ tulajdonságot! Nekem tetszik.}
{299}{}{Kösz, hogy megmentettél bennünket. Megcsókolnálak, ha nem volna hányásszagú a leheletem.}
{300}{}{Ha elég Jetet szednék be, én magam is le tudnám nyomni az Enklávét.}
{301}{}{[Énekel egy részt a Mad Max 3-ból.] "We don't need another hero, we don't need to know the way home..."}
{302}{}{Engem Chris Avellone tervezett és Tom French szkriptelt. Nem én vagyok felelõs a Jetfüggõségemért.}
{303}{}{Lõjünk be közösen egy kis Jetet és ünnepeljük meg a gyõzelmet! Te fizetsz!}
{304}{}{Ha letörlöd a játékot a merevlemezrõl, mi még megmaradunk?}
{305}{}{Ööö... az Enklávésok miféle drogtesztet csináltak? Volt ingyen Jet?}
{320}{}{Hogy mész fürdeni abban a fémvacakban?}
{321}{}{Ööö... te hozzám beszélsz?}
{322}{}{Ó, te jó ég... ez a drogterápia egyre rosszabb. Most már beszélõ bádogembereket látok magam körül.}
{323}{}{Valaki fémet öntött rád?}
{324}{}{Hé, ööö... van odabenn egy kis Jet?}
{325}{}{Adj egy kis pénzt... á, hagyjuk...}
{326}{}{::Kopog a páncélodon:: Hahó! Van otthon valaki?}
{327}{}{Te valami fridzsider-ember hibrid vagy?}
{328}{}{Nem melegszik fel belülrõl az az izé?}
{350}{}{Ha adsz egy kis Jetet, hajcsár, megmondom, hol lehet könnyen friss utánpótláshoz jutni errefelé.}
{351}{}{Hajcsár, megtarthatod a gyerekemet, ha adsz egy kis Jetet cserébe...}
{352}{}{Ha adsz pár dolcsit, a rabszolgád leszek... de elõször is Jetre van szükségem.}
{353}{}{Ha adsz egy kis Jetet, a rabszolgád leszek.}
{354}{}{Ha szerzel nekem egy kis Jetet, eladhatsz rabszolgának.}
{355}{}{Nem én! Már leszoktam. Öö... miért? Vásárolni akarsz?}
{360}{}{Te vagy az a bunyós? Kölcsönkérhetek egy kis lóvét?}
{361}{}{Naaa, adj már egy kis pénzt!}
{362}{}{Kölcsönkérhetek egy kis pénzt tõled? Megígérem, hogy visszafizetem!}
{363}{}{Hé, ööö... van egy kis Jet nálad?}
{364}{}{Ember, repülnöm kell! Felfogod, mirõl beszélek?}
{365}{}{Orvosság kell a fiamnak. Segíts, kérlek!}
{366}{}{Tudnál adni egy kis pénzt?}
{367}{}{Kéne egy kis pénz ételre...}
{368}{}{Ha adsz egy kis Jetet, a rabszolgád leszek.}
{369}{}{Ha adsz egy kis Jetet, eladhatsz rabszolgának.}
{370}{}{Nem én! Már leszoktam. Öö... miért? Vásárolni akarsz?}
{371}{}{Te a }
{372}{}{Kölcsönkérhetek egy kis pénzt...? Ugyan már, nem nyúlom le!}
{373}{}{Megdolgoznék egy kis Jetért...}
{380}{}{Hé, tesó! Segítesz elszállni?}
{381}{}{Egy kis pénzért bármit megteszek érted. Vagy Jetért, ha van nálad.}
{382}{}{Nincs szükséged valakire, akivel elszállhatnál, haver?}
{383}{}{Apa?}
{384}{}{Ember, *repülnöm* kell most azonnal, ha tudod mire gondolok...}
{385}{}{Nem én! Már leszoktam. Ööö... miért? Vásárolni akarsz?}
{386}{}{Pssszt. Nem tudnál megdobni egy kis Jettel?}
{387}{}{Kölcsönkérhetek egy kis pénzt tõled...? Ígérem, hogy megadom!}
{388}{}{Megdolgoznék egy kis Jetért...}
{389}{}{Ugyan, barátom, adj már egy kis pénzt!}
{390}{}{Kölcsönkérhetek egy kis pénzt? Ígérem, hogy visszaadom.}
{391}{}{Hé, ööö... nincs nálad egy kis jet, barátom?}
{392}{}{A fiamnak sürgõsen orvosságra van szüksége. Segíts rajtam, kérlek!}
{393}{}{Nem tudnál adni egy kis pénzt?}
{394}{}{Kéne egy kis pénz, hogy ételt tudjak vásárolni... tényleg...}
{395}{}{Egy kis Jetért vagy pénzért lefekszem veled. Tiszta vagyok, nekem elhiheted!}
{396}{}{Valamikor a renói nagymenõk közé tartoztam. Egy kis Jetért fejtágítást kaphatsz tõlem...}
{397}{}{Ha adsz egy kis Jetet, a rabszolgád leszek.}
{398}{}{Ha adsz egy kis Jetet, eladhatsz rabszolgának.}
{399}{}{Hé, húgi! Segítesz repülnöm?}
{400}{}{Ugyan, kisasszony, adjon már egy kis pénzt!}
{401}{}{Hahó, ööö... nincs egy kis Jetje, kisasszony?}
{402}{}{Figyelj, nekem most azonnal *repülnöm* kell, ha érted, mire gondolok!}
{403}{}{Nem én! Már leszoktam. Ööö... miért? Vásárolni akarsz?}
{404}{}{Mama?}
{420}{}{Hé, tesó! Nem segítenél repülni?}
{421}{}{Gyerünk, fiú, adj már egy kis pénzt!}
{422}{}{Egy kis Jetért vagy pénzért lefekszem veled. Tiszta vagyok, nekem elhiheted!}
{423}{}{Olcsóbb vagyok, mint a családok kurvái. Öö, azért ne mondd el nekik, hogy elszedem elõlük a kuncsaftokat!}
{424}{}{Bármit megteszek, ha adsz egy kis pénzt... vagy Jetet, ha van nálad.}
{425}{}{Egyszer szépségversenyt nyertem Renóban. Látod, semmit nem változtam...}
{426}{}{Nem akarsz valakit, akivel elszállhatnál?}
{427}{}{Nem én! Már leszoktam. Ööö.. miért? Vásárolni akarsz?}
{428}{}{Apu?}
{429}{}{Psszt... Nem tudnál megdobni egy kis Jettel?}
{430}{}{Kölcsönkérhetek egy kis pénzt...? Meglásd visszafizetem!}
{431}{}{Megdolgoznék egy kis Jetért...}
{432}{}{Kérhetek tõled egy kis pénzt? Hidd el, visszafizetem!}
{433}{}{Hé, ööö... van nálad egy kis Jet, barátom? Ember, "repülnöm kell", ha érted, mire gondolok!}
{434}{}{A fiamnak égetõen szüksége van egy orvosságra. Segíts, kérlek!}
{435}{}{Nem adnál egy kis aprót?}
{436}{}{Kellene egy kis pénz kajára... olyan nagy kérés ez?}
{437}{}{Ha adsz egy kis Jetet, a rabszolgád leszek.}
{438}{}{Ha adsz egy kis Jetet, eladhatsz rabszolgának.}
{439}{}{Ugyan, kisasszony, csak egy kevés aprót, ha lehetne...}
{440}{}{Hé, húgocskám! Segíts már repülnöm!}
{441}{}{A kedvedre teszek... ha adsz egy kis Jetet.}
{442}{}{Hé, ööö... nincs egy kis Jet nálad, húgi?}
{443}{}{Húgocskám, "repülnöm" kell, ha érted, mire célzok.}
{444}{}{Nem én, kishúgom! Már leszoktam. Öö... miért? Vásárolni akarsz?}
{445}{}{Mami?}
{450}{}{Szentséges...! Te meg mi a fene vagy? Valami robot?}
{451}{}{Mit szedtél be, hogy ilyen fémes külsõd lett?}
{452}{}{Öcsém! Egy vasember! És beszél hozzám...}
{453}{}{Ha egy másik bolygóról jöttél, jobb ha visszamész... itt már nincs mit meghódítani.}
{454}{}{A mindenségit... Látom Reno fényeit a sisakrostélyodban.}
{455}{}{Úgy elszálltam, hogy... ööö, mit is akartam mondani?}
{456}{}{Ember, nincs meleged ebben az izében?}
{457}{}{Van valaki abban a vacakban?}
{458}{}{Megáll az eszem, ha ez nem Mr. Darttttth Vadrrrr}
{459}{}{Ember, nekem is kéne az anyagból, amit használsz. Úgy nézel ki, mint egy nagy, fém... valami...}
{460}{}{Ember, te rossz játékba csöppentél! Próbálj ki valami csatarobotos játékot.}
{461}{}{Te ûrhajós vagy?}
{462}{}{Elõbb még be kell lõnöm magamba néhány Jetet, hogy egyáltalán eszembe jusson a veled való kekeckedés...}
{470}{}{Hé, hajcsár, mi a nagy helyzet?}
{471}{}{El akarsz adni rabszolgának? He? Próbáld csak meg! Legyõzhetetlen vagyok!}
{472}{}{Gyere, kapj el, hajcsár!}
{473}{}{Nincs egy kis Jeted a számomra, hajcsár?}
{474}{}{Olyan magasan szállok, hajcsár, hogy alig látlak odalenn.}
{475}{}{Kötözködni akarsz, hajcsár? Én egy Jet hajtotta pofozógép vagyok! Úgy picsán rúglak, hogy attól koldulsz!}
{476}{}{Akarsz velem repülni, hajcsár?}
{477}{}{Miért látok kettõt belõled? Az ott a testvéred?}
{478}{}{Höh? Te igazi vagy?}
{479}{}{Úgy elszálltam, hogy... ööö, mit is akartam mondani?}
{480}{}{Repülni akarsz? Beszélj Juuuuules-el!}
{481}{}{Csipkés Jimmy J. mindenkit rendbehoz. Ugye veszed az adást?}
{482}{}{Ha találkozol Renescóval, mondd meg neki, hogy holnapra meglesz a pénz!}
{483}{}{Csipkés Jimmy cucca a LEGJOBB. Úúúúúgy elszállsz tõle, hogy soha többé nem akarsz leszállni a földre.}
{484}{}{Hozzám beszélsz? Hozzám beszélsz?!}
{485}{}{Akarsz belõle egy kicsit? He?}
{486}{}{::Droggõzös szemekkel néz mögéd a semmibe::}
{487}{}{Akarsz velem repülni?}
{488}{}{Hé, bajnok, mi a helyzet mostanában?}
{489}{}{Bokszolni akarsz? He? Na, gyerünk!}
{490}{}{Kötözködni akarsz, bajnok? Én egy Jet hajtotta pofozógép vagyok! Picsán foglak rúgni ám!}
{500}{}{Hohó! Egy Családtag jött közénk!}
{501}{}{Olyan magasan szállok, gengszter, hogy alig látlak odalenn.}
{502}{}{Miért látok kettõt belõletek? Az ott a testvéred?}
{503}{}{Hé... te igazi Családtag vagy?}
{504}{}{Hé, gengszter, úgy elszálltam, hogy... ööö, mit is akartam mondani?}
{505}{}{Akarsz velem repülni, gengszter?}
{506}{}{Repülni akarsz, gengszter? Beszélj Juuuuules-el!}
{507}{}{Csipkés Jimmy J. mindenkit rendbehoz. Ugye veszed az adást?}
{508}{}{Ha Renesco megbízásából jöttél, mondd meg neki, hogy holnapra meglesz a pénz!}
{509}{}{Csipkés Jimmy cucca a LEGJOBB. Öö... kivéve, ha nem csíped õt.}
{510}{}{Hozzám beszélsz? Hozzám beszélsz?!}
{511}{}{Kötözködni akarsz, te maffia bérenc? Én egy Jet hajtotta pofozógép vagyok! Jól picsán foglak rúgni!}
{512}{}{Akarsz ebbõl egy kicsit, gengszter? He?}
{513}{}{::Droggõzös tekintettel bámul mögéd::}
{520}{}{A mindenit... mivel lövöd magad? Nem maradt egy kicsi mutatóba?}
{521}{}{Aszittem én vagyok itt a legelbaszottabb figura.}
{522}{}{Hé, barátom... adj már abból az anyagból, amit magadba nyomtál!}
{523}{}{Mondanám, hogy szálljunk együtt, de látom, már fenn vagy...}
{524}{}{Miért látok kettõt belõled? Az ott a testvéred?}
{525}{}{Honnan vetted azt a vackot, amit magadba nyomtál?}
{530}{}{Ember, tudtad, hogy egy agyas robot követ mindenhova?}
{531}{}{Szép! Biztos megint valami szar anyagot vettem be... most már agyas robotokat látok.}
{532}{}{Ha még egyszer meglátom azt az agyas robotot itt zizeregni, rögtön felhagyok a Jettel!}
{533}{}{Korábban én is úgy éreztem magam, mint a robot barátod... mondd meg neki, hogy rendben lesz, ha egyszer leszokik.}
{534}{}{Mi a franc történt az agyas barátoddal? Elvesztette a testét?}
{535}{}{Mondd már, hogy az a robotagy nem igazi! Légyszi...}
{536}{}{}
{537}{}{Akarsz velem repülni? És mi a helyzet a robot haveroddal?}
{538}{}{Kötözködni akarsz, te robotgyûjtõ? Én egy Jet hajtotta pofozógép vagyok! Picsán foglak rúgni, aztán a kutyádat is szépen picsán fogom rúgni!}
{539}{}{Akarsz ebbõl, te kis robotgyûjtõ?! He?}
{540}{}{Hö? Te igazi vagyol?}
{541}{}{Úgy elszálltam, hogy... ööö, mit is akartam mondani?}
{542}{}{Repülni akarsz? Beszélj Juuuuules-el!}
{543}{}{Csipkés Jimmy J. mindenkit rendbehoz. Ugye veszed az adást?}
{544}{}{Ha látod Renescót, mondd meg neki, hogy holnap megadom neki a tartozásomat.}
{545}{}{Csipkés Jimmy cucca a LEGJOBB. Úgy elszállsz tõle, hogy soha többé nem akarsz leszállni a földre.}
{546}{}{Hozzám beszélsz? Hozzám beszélsz?}
{547}{}{::Droggõzös szemekkel néz mögéd a távolba::}
{548}{}{Ember, tudtad, hogy egy mutáns jár a nyomodban?}
{549}{}{Szépen vagyunk Valami szart vehettem be... most már mutánsokat hallucinálok.}
{550}{}{Most én vagyok belõve vagy a barátod tényleg ekkora bazi nagy állat?}
{551}{}{::Nevet:: A mutánsnak satu nõtt a vállára!}
{552}{}{Öö... az most egy mutáns, vagy be vagyok állva?}
{553}{}{A batár barátod elég elbaszott egy figurának látszik!}
{554}{}{A batár barátod nagyon fosul néz ki... ::Kuncog::}
{555}{}{Az a nagy darab pasi igazi? Tisztára úgy néz ki, mint egy mutáns.}
{556}{}{Akarsz velem repülni? És mi a helyzet a mutáns haveroddal?}
{557}{}{Kötözködsz, mutánsok kedvence? Én egy Jet fûtötte pofozógép vagyok! Jól PICSÁN foglak rúgni!}
{558}{}{Akarsz ebbõl, te mutánsok kedvence?! He?}
{560}{}{Ember, tudtad, hogy egy kannibál jár a nyomodban?}
{561}{}{Azta! Még az a vadember! Szép dákó került az orrába.}
{562}{}{Azta. A haverod tudja, hogy egy dákó nõtt az orrába?}
{563}{}{Azta! Valami nagyon szar anyagot vehettem be... épp most láttam egy fickót, akinek dákó nõtt az orrába.}
{564}{}{Most én vagyok betépve, vagy a haverodnak dákó nõtt az orrába?}
{565}{}{Mondd már meg a haverodnak, hogy valaki belevert egy dákót az orrába.}
{566}{}{Annyira elszálltam, hogy alig látlak odalenn.}
{567}{}{Mért látok kettõt belõletek? Õ a testvéred?}
{568}{}{Hö? Te igazi vagyol?}
{569}{}{Úgy elszálltam, hogy... ööö, mit is akartam mondani?}
{570}{}{Akarsz velem repülni?}
{571}{}{Repülni akarsz? Beszélj Juuuuules-el!}
{572}{}{Csipkés Jimmy J. mindenkit rendbehoz. Ugye veszed az adást?}
{573}{}{Ha találkozol Renescóval, mondd meg neki, hogy holnap megadom neki a tartozásomat.}
{574}{}{Csipkés Jimmy cucca a LEGJOBB. Úgy elszállsz tõle, hogy többé nem akarsz földet érni.}
{575}{}{Hozzám beszélsz? Hozzám beszélsz?!}
{576}{}{Kötözködsz? Egy Jettel töltött pofozógép vagyok! Jól PICSÁN foglak rúgni!}
{577}{}{Akarsz egy kicsit ebbõl?! He?}
{578}{}{::Droggõzös szemekkel néz mögéd::}
{600}{}{Szép...}
{601}{}{Mmmm...}
{602}{}{Haver vagy.}
{603}{}{j}
{604}{}{J}
{605}{}{Adj egy J...öööö...}
{796}{}{! KIRÁLY VAGY!! MI A KÖVETKEZÕ LÉPÉS, BÉBI, MI A KÖVETKEZÕ?!!}
{871}{}{ család tagja vagy? Nem tudnál meglepni egy kis Jettel?}
