# Dialog Editor last position: 1
{100}{}{Bokszoló.}
{101}{}{Õ Pete "Hurrikán" McKneely.}
{150}{}{Egy izomkolosszusnak beillõ fehér férfit látsz. Látszólag. Olyan gyenge ugyanis, hogy egy szelet pizzával is kiüthetnéd.}
{151}{}{Az állkapcsa úgy fénylik, mint az üveg.}
{152}{}{Olyannak tûnik, mint aki hét másodpercet sem bírna ki a szorítóban.}
{153}{}{Ez az ember olyan gyenge, hogy egy szelet pizzával is kiüthetnéd.}
{200}{}{*Hnffff*}
{201}{}{*Hnrggg*}
{202}{}{::Feszeget::}
{203}{}{Tanácstalan vagyok.}
{204}{}{Fáradt vagyok.}
{205}{}{*Pffúúú* Kemény nap volt a mai.}
{206}{}{Az edzéstõl mindig kifáradok.}
{207}{}{A bunyó teljesen kiveszi az erõmet.}
{208}{}{Jobb lesz, ha megyek és kifényezem az üveg-állkapcsomat.}
{300}{}{::A bokszoló rádnéz, és eltakarja az állkapcsát::}
{301}{}{::A bokszoló rádnéz, és megdörzsöli az állkapcsát::}
{302}{}{Az edzés mindig kifáraszt.}
{303}{}{Jó, hogy a menedzserem be tud jönni a ringbe és leállíthatja a bunyót.}
{304}{}{Pete vagyok. Pete McKneely, a "Vesztes".}
{305}{}{Szeretem a pizzát, de vigyáznom kell a tésztájával.}
{306}{}{Kinyitottam reggel az ajtót, mire a szél ledöntött a lábamról.}
{307}{}{A bunyó kimerít.}
{308}{}{Jobb, ha megyek és kifényezem az üveg-állkapcsomat.}
{309}{}{Ha eleget edzek, akár TÍZ másodpercig is bírni fogom a ringben.}
{310}{}{Lehet, hogy csak hét másodpercig bírom a ringben, de az ágyban akár tíz másodpercig is kitartok.}
