{100}{}{Ez itt Édes Nikki.}
{125}{}{? a kaszinó egyik kártyaosztója.}
{150}{}{Ez itt Édes Nikki.}
{160}{}{Ez itt Édes Nikki. Int, hogy menj közelebb, és játssz.}
{170}{}{? a kaszinó egyik kártyaosztója.}
{180}{}{? a kaszinó egyik kártyaosztója. Int, hogy menj közelebb, és játssz.}
{200}{}{::Éljenez::}
{210}{}{Helló, [MM]. Van valami, amiben... segíthetnék?}
{220}{}{Ez itt már éppen eléggé kockára tette az életét.}
{230}{}{Hé, izomagy! Nem akarsz egy kis pénzt kockára tenni?}
{250}{}{Helló, mozisztár! Nem akarsz itthagyni egy kis pénzt?}
{270}{}{Szia, édesem. El akarsz költeni egy kis pénzt?}
{290}{}{Asszem, elment az eszed, hogy idejöttél, de... tedd csak meg a tétedet. A legkisebb tét 5 dolcsi. Tedd meg a tétedet...}
{310}{}{Ööö, jól van, uram. Jöjjön máskor is.}
{320}{}{Jól van, uram. Jöjjön vissza minél hamarabb!}
{330}{}{Sajnálom, uram. Legközelebb biztos nagyobb szerencséje lesz.}
{340}{}{Nyert! Gratulálok, uram!}
{350}{}{Nyert! Megduplázta a pénzét! Gratulálok, uram!}
{360}{}{Nyert! Ön megtriplázta a pénzét! A szerencse beköltözött a házba! Gratulálok, uram!}
{370}{}{Most akkor mi lesz? Az id?met akarod vesztegetni, vagy megteszel valami tétet?}
{380}{}{Igen, azt hallottam, hogy MEGHALT. Ezt akartad hallani, te gyilkos?! He?! Most akkor játszol vagy csesztetsz még egy kicsit?}
{390}{}{Ne vegyél rá mérget, kedvesem! Persze ha olyan hülye vagy, mint amilyen ronda, nyugodtan törd csak a fejed ilyesmin. Azóta nem láttam azt a csavargót, hogy átejtette Mr. Salvatorét.}
{400}{}{Kedvesem, már mondtam, hogy nem tudom, hova t?nt. Nézd, nekem itt DOLGOM van, szóval menj és csináld azt, ami...}
{410}{}{Ha egy ujjal hozzámérsz, Mr. Salvatore elevenen fog megnyúzatni.}
{420}{}{Mir?l beszélsz?}
{430}{}{Figyelj, AMINT AZT MÁR MONDTAM, nem tudom, hol van. Mintha *rémlene* viszont, hogy volt egy szobája a Desperadóban. Esetleg ott utána nézhetsz. Most pedig, ha nem haragszol, dolgom van.}
{440}{}{Nézd, én csak nemrég dolgozom itt, és nem tudok minden besétáló kártyazsongl?rt meg ruppótlan csalót felismerni. A hozzád hasonló szar alakokhoz viszont elég jó a szemem.}
{450}{}{Hát persze, beszedsz egy rakás Jetet, és rögtön mindenre gyanakodni kezdesz, mi?}
{460}{}{Na, húzz innen a francba! Nincs mit mondanom neked!}
{470}{}{Fel van vágva a nyelved, mint egy kígyónak. Lehet, hogy tudom, hol van Lloyd, lehet, hogy nem. Van 500 dollárod a nemes célra?}
{480}{}{LEHET, hogy Lloyd még mindig a zsebében tartja a részemet, és valszeg húzódozni fog, hogy odaadja. Ezért NEM LEHETETLEN, hogy 500 dolcsiért elmondhatnám, hol húzta meg magát.}
{490}{}{(Zsebre vágja a pénzt.) Nézz be a Desperado alagsorában lév? kazánházba! Az a pondró mindig oda menekül, ha forrósodni kezd a lába alatt a talaj.}
{500}{}{Lennél szíves lekopni? Ha az emberek így látnak együtt minket, rögtön beindul a szóbeszéd. Érthet??}
{510}{}{Akkor menj a büdös francba! Bel?lem soha többet ki nem húzol semmit!}
