{100}{}{Ez az ember a kaszinó felügyelője.}
{150}{}{Ez a férfi igen jólöltözött. Egyfolytában a kaszinót fürkészi.}
{151}{}{Ez az ember a kaszinó egyik felügyelője. Folyamatosan fürkészi a kaszinót.}
{200}{}{Ööö... le kéne vennie azt a páncélt!}
{201}{}{Öö, uram... vagy hölgyem... le kéne vennie azt a páncélt!}
{202}{}{Uram... hölgyem... a kaszinóban nem lehet azt a páncélt viselni!}
{205}{}{Ööö... miért lopakodik itt, uram?}
{206}{}{Ööö... valami titkos küldetésben jár, uram?}
{210}{}{Ööö... miért lopakodik itt, hölgyem?}
{211}{}{Ööö... valami titkos küldetésben jár, hölgyem?}
{215}{}{Jó estét, }
{216}{}{Jó estét, }
{220}{}{Jó estét, }
{221}{}{Jó estét, }
{225}{}{Jó napot, }
{230}{}{Jó napot, }
{235}{}{Barátom, úgy tűnik, nem abba a kaszinóba jöttél, amelyikbe akartál.}
{236}{}{A legjobb lenne, ha távoznál. Mondjuk most azonnal.}
{237}{}{Ez nem az a hely, ahol az életedet kéne kockára tenni. Inkább menj máshova!}
{238}{}{Hé szukácska, úgy tűnik, nem abba a kaszinóba jöttél, amelyikbe akartál.}
{245}{}{Uram, sajnálom, de el kell raknia azt a fegyvert!}
{250}{}{Hölgyem, sajnálom, de el kell raknia azt a fegyvert!}
{255}{}{Drágám, bocsánat, hogy szólok, de a kaszinóba nem vihetsz fegyvert. Hehe... anélkül is épp elég halálosan nézel ki.}
{260}{}{Kedvesem, ilyen testtel sehova nem fogsz tudni elosonni.}
{265}{}{Hé, vadember, a saját érdekedben most azonnal tedd el azt a fegyvert!}
{270}{}{Basszus, most rögtön hagyd abba a lopakodást, vadember!}
{275}{}{Szeva, szeva, Myron! Régóta nem láttunk a laboron kívül.}
{276}{}{Azért jöttél, Myron, hogy kipróbáld az új húsokat?}
{277}{}{Hé! Gyere be hozzánk, Myron!}
{280}{}{Mondd! Mit akarsz tudni?}
{281}{}{Fúúúúúúúúú fúú fúú fúúúúú}
{282}{}{Otthagyod}
{283}{}{Ki vagy?}
{284}{}{Miféle kaszinó ez itt?}
{285}{}{Tudnál mondani valamit a kaszinóról?}
{286}{}{Ismersz egy Szépfiú Lloyd nevű pasast?}
{287}{}{Ki az az öreg fószer a játékautomatánál?}
{288}{}{Az a humorista a színpadon nagyon zsé. Mit szólnál, ha én is megpróbálnám?}
{289}{}{Kösz. Nincs szükséged egy éjszakai táncosra. Valami lazább munkabeosztásra kapható lennék.}
{290}{}{Kösz, úgy lesz.}
{291}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak.}
{292}{}{Csak érdekeltek itt a dolgok. Ne zavartasd magad!}
{295}{}{A droid kinnmarad!}
{296}{}{Droidokat nem szolgálunk ki!}
{297}{}{A droid szépen kinnmarad! Majd idekinn megvár!}
{300}{}{Öö, jobb lenne, ha továbbállna, uram.}
{301}{}{Öö, jobb lenne, ha továbbállna, hölgyem.}
{302}{}{Húzz innen, retardált!}
{303}{}{Mama mongya különlegyes vagyok}
{304}{}{Otthagyod}
{305}{}{Hát szolgálatban nemigen beszélgethetek, de azért örülök, hogy seggberúgtad az Enklávét.}
{306}{}{Hé, }
{315}{}{Igen, anyád szerint én is különleges vagyok. Na, eridj innen... lehet, hogy valahol a Szűz utcában megtalálod a mamádat.}
{316}{}{Ó jójó! Csá csá}
{317}{}{Otthagyod}
{325}{}{Én vagyok itt a felvigyázó. Mit tehetek érted?}
{326}{}{Én felelek a kaszinó biztonságáért. Ha szükséged van valamire, csak szólj!}
{327}{}{Miféle kaszinó ez itt?}
{328}{}{Tudnál mondani valamit a kaszinóról?}
{329}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak.}
{335}{}{Ez itt a [CN]. Ha kell valami, csak szólj!}
{336}{}{Ez itt a [CN]. Legalábbis, amikor utoljára megnéztem a táblát az ajtón, még az volt. Nos, mit tehetek érted?}
{337}{}{Ki vagy?}
{338}{}{Tudnál mondani valamit a kaszinóról?}
{339}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak.}
{340}{}{Mit tehetek érted, haver?}
{341}{}{Mit tehetek érted, kedves?}
{342}{}{Fúúúúúúúúú fúú fúú fúúúúú}
{343}{}{Otthagyod}
{344}{}{Ki vagy?}
{345}{}{A város legfaszább kaszinója... csak egy kicsit el vagyok havazva. Akarsz még valamit tudni?}
{346}{}{A város legfaszább kaszinója... a legfaszább asztalokkal... miért nem próbálsz szerencsét, hm?}
{347}{}{Ki vagy?}
{348}{}{Kié ez a kaszinó?}
{349}{}{Oké, köszi. Bocs, hogy zavartalak.}
{350}{}{Kösz. Nincs szükséged egy éjszakai táncosra. Valami lazább munkabeosztásra kapható lennék.}
{351}{}{Kösz, úgy lesz.}
{352}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak.}
{353}{}{Csak érdekeltek itt a dolgok. Ne zavartasd magad!}
{355}{}{A [CA] család tulajdona. Ők dobták fel ezt a krimót, és csináltak belőle igazi éjszakai szórakozóhelyet. Ragyogó ékkő New Renóban.}
{356}{}{A [CA] család tulajdona. Remélem, nem gond? Na, csak azért mondom, mert ha nem játszani jöttél, akkor nem neked való ez a hely. Értve vagyok?}
{357}{}{Ki vagy?}
{358}{}{Tudnál mondani valamit a kaszinóról?}
{359}{}{Értem. Köszönöm, hogy szakított rám időt.}
{360}{}{Hé, nézd már ki van itt! Hé, }
{361}{}{. Üdvözlünk a [CN] kaszinóban. Tetszenek a filmjeid.}
{362}{}{Fúúúúúúúúú fúú fúú fúúúúú}
{363}{}{Otthagyod}
{364}{}{Ki vagy?}
{365}{}{Az ott? A vén McGee? Őrült vén fasz... az utóbbi években folyton azon a gépen játszik, és egyre csak a főnyereményt várja. Az összes vagyonát beleölte a gépbe, de egy kanyit sem akar neki visszaadni.}
{366}{}{Az ott? A vén McGee? Őrült vén fasz, annyi szent. Hehe. Biztos ki van akadva, hogy elnyerted a vagyonát. Én vigyáznék vele.}
{367}{}{Meg van piszkálva az a gép?}
{368}{}{Van itt valami, ami nagyon érdekel.}
{369}{}{Köszönöm az információkat.}
{370}{}{Köszi, hízelgő, amit mondasz. Csak azért jöttem, hogy beköszönjek.}
{375}{}{Nincs, csak nagyon makacs szegény... csakúgy, mint az öreg. Nyilván volna mit rajta javítgatni, de nincs játékautomata szerelőnk, aki meg tudná szerelni azt a vackot.}
{376}{}{Van itt valami, ami nagyon érdekel.}
{377}{}{Hát érdekes dolgok ezek. Kösz az információt.}
{385}{}{Ja, az a köcsög bejött ide egy hete, és az egyik asztalnál nyert vagy ezer dollárt, aztán lelépett. Nem tudom, most hol lehet, de volt neki egy szobája a Desperadóban.}
{386}{}{Ja, egy ilyen nevű fickó bérelt nálunk szobát az emeleten... 204-es. Kifizetett mindent, de néhány napja lelépett és azóta senki nem látta.}
{387}{}{Mr. Salvatore azt mondta nekem, hogy Lloyd egy bizonyos dílertől nyerte a pénzt. Lehet tudni, kiről van szó?}
{388}{}{Van itt valami, ami nagyon érdekel.}
{389}{}{Köszönöm az információkat.}
{395}{}{Nikki? Igen, a középső asztalnál ül. Van valami probléma?}
{396}{}{Nincs probléma. Csak össze akartam vele futni. Kérdeznék még, ha nem baj...}
{397}{}{Köszönöm az információkat.}
{405}{}{Nikki-nek HÍVTÁK. Nálunk dolgozott, de kinyírták... a közelmúltban.}
{406}{}{Hmmm. Nem baj, ha felteszek még egy-két kérdést...?}
{407}{}{Hát érdekes dolgok ezek. Kösz az információt.}
{415}{}{Nikki-nek hívták. Nálunk dolgozott, de nem is olyan régen felmondott. Szépen összepakolt és lelépett.}
{416}{}{Nem baj, ha még kérdezek egy s mást...?}
{417}{}{Hát érdekes dolgok ezek. Kösz az információt.}
{425}{}{Hogyne, számítunk rád. Az öltöző hátul van...}
{426}{}{Kiváló. Néhány percen belül a színpadon leszek...}
{427}{}{Sajnálom, erre most nincs időm, viszont kérdeznék valamit.}
{428}{}{Majd egy kicsit később. Számíthatsz rám hamarosan...}
{435}{}{Szó sem lehet róla, még mindig próbálunk magunkhoz térni az utolsó előadásod óta. Asszem, jobb lesz, ha más kaszinóban próbálkozol.}
{436}{}{Jól van, köszi. Még azért kérdeznék valamit...}
{437}{}{Oké... később azért visszajövök még.}
{445}{}{Összeszámolod az esti keresetet. Megteszi. Szép summa.}
{446}{}{A bőrcucc jó ötlet volt.}
{447}{}{A szájpeckes bemutató sem volt rossz.}
{448}{}{Legközelebb még jobb leszek...}
{455}{}{Ja, büdösebb, mint a brahminszar. Azért oké...? Hát miért is ne. Egy kis impró nem árthat, de a közönség nagyon finnyás... nagyon jónak kell ám lenned.}
{456}{}{Nem fogsz csalódni... figyelj csak...}
{1215}{}{, uram.}
{1216}{}{, uram.}
{1220}{}{, hölgyem.}
{1221}{}{, hölgyem.}
{1225}{}{, uram.}
{1230}{}{, hölgyem.}
{1306}{}{. Gyere, pihenj egyet! Biztos elfáradtál a világ megmentése közben. Szórakozz egy jót!}
