# Dialog Editor last position: 1
{100}{}{Ez az ember a kaszinó felügyelõje.}
{150}{}{Ez a férfi igen jólöltözött. Egyfolytában a kaszinót fürkészi.}
{151}{}{Ez az ember a kaszinó egyik felügyelõje. Folyamatosan fürkészi a kaszinót.}
{200}{}{Ööö... le kéne vennie azt a páncélt!}
{201}{}{Öö, uram... vagy hölgyem... le kéne vennie azt a páncélt!}
{202}{}{Uram... hölgyem... a kaszinóban nem lehet azt a páncélt viselni!}
{205}{}{Öö, miért lopakodik, uram?}
{206}{}{Öö, titkos küldetésben jár, uram?}
{210}{}{Öö, miért lopakodik, hölgyem?}
{211}{}{Öö, titkos küldetésben jár, hölgyem?}
{215}{}{Jó estét, }
{1215}{}{, uram.}
{216}{}{Jó estét, }
{1216}{}{, uram.}
{220}{}{Jó estét, }
{1220}{}{, hölgyem.}
{221}{}{Jó estét, }
{1221}{}{, hölgyem.}
{225}{}{Jó napot, }
{1225}{}{, uram.}
{230}{}{Jó napot, }
{1230}{}{, hölgyem.}
{235}{}{Barátom, asszem, rossz kaszinóba jöttél.}
{236}{}{Jobb lenne, ha távoznál. Most azonnal!}
{237}{}{Itt az emberek nem az életükkel játszanak. Jobb lenne távoznod.}
{238}{}{Asszem, rossz kaszinóba jöttél, szajha.}
{245}{}{Uram, sajnálom, de el kellene raknia a fegyverét.}
{250}{}{Hölgyem, sajnálom, de el kellene raknia a fegyverét.}
{255}{}{Kedvesem, sajnálom, de a kaszinóban nem lehet fegyvert hordani. Hehe... anélkül is éppen elég halálos vagy.}
{260}{}{Kedvesem, ezzel a kinézettel sehova nem fogsz tudni elosonni.}
{265}{}{Vadember, most azonnal tedd el azt a fegyvert!}
{270}{}{Vadember, hagyd a picsába abba a lopakodást most azonnal!}
{275}{}{Hé, hé... Myron! Régóta nem láttunk a laboron kívül.}
{276}{}{Azért jöttél, Myron, hogy leteszteld az új árukészletet?}
{277}{}{Hé! Szállj már be, Myron!}
{285}{}{Mutánsoknak kinn a helyük!}
{286}{}{Engem nem érdekel, hogy a barátod egy X-Man. A mutánsoknak kívül tágasabb!}
{287}{}{Az a mutáns szörnyszülött nem tartózkodhat itt!}
{295}{}{Droidok nem jöhetnek ide!}
{296}{}{Droidokat nem szolgálunk ki.}
{297}{}{Droidok nem jöhetnek ide. Kint kell várakozniuk!}
{305}{}{Szolgálatban nem beszélgethetek, de azért örülök, hogy lenyomtad az Enklávét.}
{306}{}{Hé, }
{1306}{}{. Gyere, pihenj egyet! Biztos elfáradtál a világ megmentése közben. Szórakozz egy jót!}
{315}{}{A hármas asztalhoz több pénz kell...}
{316}{}{Jó kis tömeg gyûlt ma össze...}
{325}{}{A hármas asztalhoz több pénz kell...}
{326}{}{Jó kis tömeg gyûlt ma össze...}
{335}{}{Hé, }
{336}{}{! Hallottam, hogy te taszítottad vissza az Enklávét a kõkorszakba! Azt az utasítást kaptam, hogy a cég ajándékaként adjak egy kisebb összeget. Érezd jól magad nálunk!}
{337}{}{! Hallottam, hogy te taszítottad vissza az Enklávét a kõkorszakba! Azt az utasítást kaptam, hogy a cég ajándékaként adjak egy kisebb összeget. Érezd jól magad nálunk!}
{338}{}{. Mi a helyzet, fõnök? Hozhatok valamit? Egy italt? Egy pincérnõt?}
{339}{}{. Te vagy a kaszinó legszebb lánya. Ajánlhatok valamit? Egy italt? Egy privát asztalt?}
{340}{}{Mit tehetek érted, haver?}
{341}{}{Mit tehetek érted, kedves?}
{342}{}{Fúúúúúúúúú fúú fúú fúúúúú}
{343}{}{Továbbállsz}
{344}{}{Te meg ki vagy?}
{345}{}{Miféle kaszinó ez itt?}
{346}{}{Tudnál mondani valamit a kaszinóról?}
{347}{}{Ismersz egy Szépfiú Lloyd nevû embert?}
{348}{}{Ki az az öreg muksó a játékautomatánál?}
{349}{}{Az a humorista a színpadon nagyon zsé. Mit szólnál, ha én is megpróbálnám?}
{350}{}{Kösz. Nincs szükséged egy éjszakai táncosra. Valami lazább munkabeosztásra kapható lennék.}
{351}{}{Kösz, úgy teszek.}
{352}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak.}
{353}{}{Csak érdekeltek itt a dolgok. Ne zavartasd magad!}
{360}{}{Hé, nézd már ki van itt! Hé, }
{361}{}{. Üdvözlünk a [CN] kaszinóban. Tetszenek a filmjeid.}
{362}{}{Fúúúúúúú fúú fúú fúúúúú}
{363}{}{Elpályázol}
{364}{}{Te meg ki vagy?}
{365}{}{Miféle kaszinó ez itt?}
{366}{}{Tudnál mondani valamit a kaszinóról?}
{367}{}{Ismersz egy Szépfiú Lloyd nevû ürgét?}
{368}{}{Ki az az öreg manus a játékautomatánál?}
{369}{}{Kösz. Nincs szükséged egy éjszakai táncosra. Valami lazább munkabeosztásra kapható lennék.}
{370}{}{Köszi, hízelgõ, amit mondasz. Csak azért jöttem, hogy beköszönjek.}
{280}{}{Mondd! Mit akarsz tudni?}
{281}{}{Fúúúúúúú fúú fúú fúúúúú}
{282}{}{Otthagyod}
{283}{}{Ki vagy?}
{284}{}{Miféle kaszinó ez itt?}
{285}{}{Tudnál mondani valamit a kaszinóról?}
{286}{}{Ismersz egy Szépfiú Lloyd nevû pasast?}
{287}{}{Ki az az öreg fószer a játékautomatánál?}
{288}{}{Az a humorista a színpadon nagyon zsé. Mit szólnál, ha én is megpróbálnám?}
{289}{}{Kösz. Nincs szükséged egy éjszakai táncosra. Valami lazább munkabeosztásra kapható lennék.}
{290}{}{Kösz, úgy lesz.}
{291}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak.}
{292}{}{Csak érdekeltek itt a dolgok. Ne zavartasd magad!}
{300}{}{Öö, jobb lenne, ha továbbállna, uram.}
{301}{}{Öö, jobb lenne, ha továbbállna, hölgyem.}
{302}{}{Húzz innen, retardált!}
{303}{}{Mama mongya különlegyes vagyok}
{304}{}{Továbbállsz}
{315}{}{Igen, anyád szerint én is különleges vagyok. Na, eridj innen... lehet, hogy valahol a Szûz utcában megtalálod a mamádat.}
{316}{}{Ó jójó! Csá csá}
{317}{}{Otthagyod}
{325}{}{Én vagyok itt a felvigyázó. Mit tehetek érted?}
{326}{}{Én felelek a kaszinó biztonságáért. Ha szükséged van valamire, csak szólj!}
{327}{}{Miféle kaszinó ez itt?}
{328}{}{Tudnál mondani valamit a kaszinóról?}
{329}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak.}
{335}{}{Ez itt a [CN]. Ha kell valami, csak szólj!}
{336}{}{Ez itt a [CN]. Legalábbis, amikor utoljára megnéztem a táblát az ajtón, még az volt. Nos, mit tehetek érted?}
{337}{}{Ki vagy?}
{338}{}{Tudnál mondani valamit a kaszinóról?}
{339}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak.}
{345}{}{A város legfaszább kaszinója... csak egy kicsit el vagyok havazva. Akarsz még valamit tudni?}
{346}{}{A város legfaszább kaszinója... a legfaszább asztalokkal... miért nem próbálsz szerencsét, hm?}
{347}{}{Ki vagy?}
{348}{}{Kié ez a kaszinó?}
{349}{}{Oké, köszi. Bocs, hogy zavartalak.}
{355}{}{A [CA] család tulajdona. Õk dobták fel ezt a krimót, és csináltak belõle igazi éjszakai szórakozóhelyet. Ragyogó ékkõ New Renóban.}
{356}{}{A [CA] család tulajdona. Remélem, nem gond? Na, csak azért mondom, mert ha nem játszani jöttél, akkor nem neked való ez a hely. Értve vagyok?}
{357}{}{Ki vagy?}
{358}{}{Tudnál mondani valamit a kaszinóról?}
{359}{}{Értem. Kösz, hogy idõt szakítottál rám.}
{365}{}{Az ott? A vén McGee? Õrült vén fasz... az utóbbi években folyton azon a gépen játszik, és egyre csak a fõnyereményt várja. Az összes vagyonát beleölte a gépbe, de egy kanyit sem akar neki visszaadni.}
{366}{}{Az ott? A vén McGee? Õrült vén fasz, annyi szent. Hehe. Biztos ki van akadva, hogy elnyerted a vagyonát. Én vigyáznék vele.}
{367}{}{Meg van piszkálva az a gép?}
{368}{}{Kérdeznék valami mást, ha nem gond...}
{369}{}{Kösz az információt.}
{375}{}{Nincs, csak nagyon makacs szegény... csakúgy, mint az öreg. Nyilván volna mit rajta javítgatni, de nincs játékautomata szerelõnk, aki meg tudná szerelni azt a vackot.}
{376}{}{Volna még egy-két kérdésem...}
{377}{}{Ez bizony érdekes. Kösz az információt.}
{385}{}{Ja, az a köcsög bejött ide egy hete, és az egyik asztalnál nyert vagy ezer dollárt, aztán lelépett. Nem tudom, most hol lehet, de volt neki egy szobája a Desperadóban.}
{386}{}{Ja, egy ilyen nevû fickó bérelt nálunk szobát az emeleten... 204-es. Kifizetett mindent, de néhány napja lelépett és azóta senki nem látta.}
{387}{}{Mr. Salvatore azt mondta nekem, hogy Lloyd egy bizonyos dílertõl nyerte a pénzt. Lehet tudni, kirõl van szó?}
{388}{}{Feltennék még egynéhány kérdést...}
{389}{}{Kösz az információt.}
{395}{}{Nikki? Igen, a középsõ asztalnál ül. Van valami probléma?}
{396}{}{Nincs probléma. Csak össze akartam vele futni. Kérdeznék még, ha nem baj...}
{397}{}{Kösz az infót.}
{405}{}{Nikki-nek HÍVTÁK. Nálunk dolgozott, de kinyírták... a közelmúltban.}
{406}{}{Hmmm. Nem baj, ha felteszek még egy-két kérdést...?}
{407}{}{Érdekes. Kösz az információt.}
{415}{}{Nikki-nek hívták. Nálunk dolgozott, de nem is olyan régen felmondott. Szépen összepakolt és lelépett.}
{416}{}{Nem baj, ha még kérdezek egy s mást...?}
{417}{}{Érdekes. Kösz az információt.}
{425}{}{Hogyne, számítunk rád. Az öltözõ hátul van...}
{426}{}{Kiváló. Néhány percen belül a színpadon leszek...}
{427}{}{Majd egy kicsit késõbb. Hadd kérdezzek elõbb valamit...}
{428}{}{Majd egy kicsit késõbb. Számíthatsz rám hamarosan...}
{435}{}{Szó sem lehet róla, még mindig próbálunk magunkhoz térni az utolsó elõadásod óta. Asszem, jobb lesz, ha más kaszinóban próbálkozol.}
{436}{}{Jól van, köszi. Még azért kérdeznék valamit...}
{437}{}{Oké... késõbb azért visszajövök még.}
{445}{}{Összeszámolod az esti keresetet. Megteszi. Szép summa.}
{446}{}{A bõrcucc jó ötlet volt.}
{447}{}{A szájpeckes bemutató sem volt rossz.}
{448}{}{Legközelebb még jobb leszek...}
{455}{}{Ja, büdösebb, mint a brahminszar. Azért oké...? Hát miért is ne. Egy kis impró nem árthat, de a közönség nagyon finnyás... nagyon jónak kell ám lenned.}
{456}{}{Nem fogsz csalódni... figyelj csak...}