# Dialog Editor last position: 1
{100}{}{Ez az ember a kaszinó felügyelõje.}
{150}{}{Ez a férfi igen jólöltözött. Egyfolytában a kaszinót fürkészi.}
{000}{}{Ez az ember a kaszinó egyik felügyelõje. Folyamatosan fürkészi a kaszinót.}
{000}{}{Folyamatosan fürkészi a kaszinót.}
{200}{}{Ööö... le kéne vennie azt a páncélt!}
{000}{}{Öö, uram... vagy hölgyem... le kéne vennie azt a páncélt!}
{000}{}{Uram... hölgyem... a kaszinóban nem lehet azt a páncélt viselni!}
{210}{}{Öö, miért lopakodik, uram?}
{000}{}{Öö, titkos küldetésben jár, uram?}
{220}{}{Öö, miért lopakodik, hölgyem?}
{000}{}{Öö, titkos küldetésben jár, hölgyem?}
{230}{}{Jó estét, [MM], uram.}
{000}{}{Jó estét, [MM], uram.}
{240}{}{Jó estét, [MM], hölgyem.}
{000}{}{Jó estét, [MM], hölgyem.}
{250}{}{Jó napot, [MM], uram.}
{260}{}{Jó napot, [MM], hölgyem.}
{270}{}{Barátom, asszem, rossz kaszinóba jöttél.}
{000}{}{Jobb lenne, ha távoznál. Most azonnal!}
{000}{}{Ide nem azért jönnek az emberek, hogy az életükkel játszanak. Jobb lenne távoznod.}
{000}{}{Asszem, rossz kaszinóba jöttél, szajha.}
{280}{}{Uram, sajnálom, de el kellene raknia a fegyverét.}
{290}{}{Hölgyem, sajnálom, de el kellene raknia a fegyverét.}
{300}{}{Kedvesem, sajnálom, de a kaszinóban nem lehet fegyvert hordani. [Mosolyog.]... anélkül is éppen elég halálos vagy.}
{310}{}{Kedvesem, ezzel a kinézettel sehova nem fogsz tudni elosonni.}
{320}{}{Vadember, most azonnal tedd el azt a fegyvert!}
{330}{}{Vadember, hagyd a picsába abba a lopakodást most azonnal!}
{340}{}{[Myronnak] Hé, hé... Myron! Régóta nem láttunk a laboron kívül.}
{000}{}{[Myronnak] Azért jöttél, Myron, hogy leteszteld az új árukészletet?}
{000}{}{[Myronnak] Szállj már be, Myron!}
{350}{}{[Marcus felé biccent.] Mutánsoknak kinn a helyük!}
{000}{}{[Marcus felé biccent.] Engem nem érdekel, hogy a barátod egy X-Man. A mutánsoknak kívül tágasabb!}
{000}{}{[Marcusra bámul.] Az a mutáns szörnyszülött nem tartózkodhat itt!}
{360}{}{Droidok nem jöhetnek ide!}
{000}{}{Droidokat nem szolgálunk ki.}
{000}{}{Droidok nem jöhetnek ide. Kint kell várakozniuk!}
{370}{}{Szolgálatban nem beszélgethetek, de azért örülök, hogy lenyomtad az Enklávét.}
{000}{}{Hé, [X]! Gyere, pihenj egyet! Biztos elfáradtál a világ megmentése közben. Szórakozz egy jót!}
{380}{}{A hármas asztalhoz több pénz kell...}
{000}{}{Jó kis tömeg gyûlt ma össze...}
{390}{}{A hármas asztalhoz több pénz kell...}
{000}{}{Jó kis tömeg gyûlt ma össze...}
{400}{}{[X]! Hallottam, hogy ön taszította vissza az Enklávét a kõkorszakba! [Hivatalos hangra vált.] Azt az utasítást kaptam, hogy a cég ajándékaként adjak egy kisebb összeget. Érezze jól magát nálunk, uram!}
{000}{}{[X]! Hallottam, hogy ön taszította vissza az Enklávét a kõkorszakba! [Hivatalos hangra vált.] Azt az utasítást kaptam, hogy a cég ajándékaként adjak egy kisebb összeget. Érezze jól magát nálunk, hölgyem! [Kacsint.]}
{000}{}{Hé [X]! [Mosolyog.] Mi a helyzet, fõnök? Hozhatok valamit? Egy italt? Egy pincérnõt?}
{000}{}{Hé, [X]! [Mosolyog.] Te vagy a kaszinó legszebb lánya. Ajánlhatok valamit? Egy italt? Egy privát asztalt?}
{000}{}{[A kaszinó felügyelõje egyfolytában rajta tartja a szemét mindenen.] Mit tehetek érted, haver?}
{000}{}{[A kaszinó felügyelõje egyfolytában rajta tartja a szemét mindenen.] Mit tehetek érted, kedves?}
{000}{}{Fúúúúúúúúú fúú fúú fúúúúú}
{000}{}{Továbbállsz [Távozol.]}
{000}{}{Te meg ki vagy?}
{000}{}{Miféle kaszinó ez itt?}
{000}{}{Tudnál mondani valamit a kaszinóról?}
{000}{}{Ismersz egy Szépfiú Lloyd nevû embert?}
{000}{}{Ki az az öreg muksó a játékautomatánál?}
{000}{}{Az a humorista a színpadon nagyon zsé. Mit szólnál, ha én is megpróbálnám?}
{000}{}{Kösz. Nincs szükséged egy éjszakai táncosra. Valami lazább munkabeosztásra kapható lennék.}
{000}{}{Kösz, úgy teszek. [Távozol.]}
{000}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak. [Távozol.]}
{000}{}{Csak érdekeltek itt a dolgok. Ne zavartasd magad! [Távozol.]}
{420}{}{Hé, nézd már ki van itt! Hé, [PS]! [Mosolyog.] Üdvözlünk a [CN] kaszinóban. Tetszenek a filmjeid.}
{000}{}{Fúúúúúúú fúú fúú fúúúúú}
{000}{}{Elpályázol [Távozol.]}
{000}{}{Te meg ki vagy?}
{000}{}{Miféle kaszinó ez itt?}
{000}{}{Tudnál mondani valamit a kaszinóról?}
{000}{}{Ismersz egy Szépfiú Lloyd nevû ürgét?}
{000}{}{Ki az az öreg manus a játékautomatánál?}
{000}{}{Kösz. Nincs szükséged egy éjszakai táncosra. Valami lazább munkabeosztásra kapható lennék.}
{000}{}{Köszi, hízelgõ, amit mondasz. Csak azért jöttem, hogy beköszönjek. [Távozol.]}
{440}{}{Mondd! Mit akarsz tudni?}
{000}{}{Fúúúúúúú fúú fúú fúúúúú}
{000}{}{Otthagyod [Távozol.]}
{000}{}{Ki vagy?}
{000}{}{Miféle kaszinó ez itt?}
{000}{}{Tudnál mondani valamit a kaszinóról?}
{000}{}{Ismersz egy Szépfiú Lloyd nevû pasast?}
{000}{}{Ki az az öreg fószer a játékautomatánál?}
{000}{}{Az a humorista a színpadon nagyon zsé. Mit szólnál, ha én is megpróbálnám?}
{000}{}{Kösz. Nincs szükséged egy éjszakai táncosra. Valami lazább munkabeosztásra kapható lennék.}
{000}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak. [Távozol.]}
{000}{}{Csak érdekeltek itt a dolgok. Ne zavartasd magad! [Távozol.]}
{460}{}{Öö, jobb lenne, ha továbbállna, uram.}
{000}{}{Öö, jobb lenne, ha továbbállna, hölgyem.}
{000}{}{[Lenézõen] Húzz innen, retardált!}
{000}{}{Mama mongya különlegyes vagyok}
{000}{}{Továbbállsz [Távozol.]}
{470}{}{Igen, anyád szerint én is különleges vagyok. Na, eridj innen... lehet, hogy valahol a Szûz utcában megtalálod a mamádat.}
{000}{}{Ó jójó! Csá csá [Távozol.]}
{000}{}{Otthagyod [Távozol.]}
{480}{}{Én vagyok itt a felvigyázó. [Egy kicsit bosszankodik.] Mit tehetek érted?}
{000}{}{Én felelek a kaszinó biztonságáért. Ha szükséged van valamire, csak szólj!}
{000}{}{Miféle kaszinó ez itt?}
{000}{}{Tudnál mondani valamit a kaszinóról?}
{000}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak.}
{490}{}{Ez itt a [CN]. Ha kell valami, csak szólj!}
{000}{}{Ez itt a [CN]. Legalábbis, amikor utoljára megnéztem a táblát az ajtón, még az volt. [Összevonja a szemöldökét.] Na, lökjed, mit tehetek érted!?}
{000}{}{Ki vagy?}
{000}{}{Tudnál mondani valamit a kaszinóról?}
{000}{}{Semmi-semmi, kösz. Bocs, hogy zavartalak.}
{500}{}{A város legfaszább kaszinója... csak egy kicsit el vagyok havazva. [Nevet.] Akarsz még valamit tudni?}
{000}{}{A város legfaszább kaszinója... a legfaszább asztalokkal... miért nem próbálsz szerencsét, hm?}
{000}{}{Ki vagy?}
{000}{}{Kié ez a kaszinó?}
{000}{}{Oké, köszi. Bocs, hogy zavartalak. [Távozol.]}
{510}{}{A [CA] család tulajdona. Õk dobták fel ezt a krimót, és csináltak belõle igazi éjszakai szórakozóhelyet. Ragyogó ékkõ New Renóban.}
{000}{}{A [CA] család tulajdona. [Méricskél.] Remélem, nem gond? Na, csak azért mondom, mert ha nem játszani jöttél, akkor nem neked való ez a hely. Értve vagyok?}
{000}{}{Ki vagy?}
{000}{}{Tudnál mondani valamit a kaszinóról?}
{000}{}{Értem. Kösz, hogy idõt szakítottál rám. [Távozol.]}
{520}{}{Az ott? A vén McGee? Õrült vén fasz... az utóbbi években folyton azon a gépen játszik, és egyre csak a fõnyereményt várja. Az összes vagyonát beleölte a gépbe, de egy kanyit sem akar neki visszaadni.}
{000}{}{Az ott? A vén McGee? Õrült vén fasz, annyi szent. Hehe. Biztos ki van akadva, hogy elnyerted a vagyonát. Én vigyáznék vele.}
{000}{}{Meg van piszkálva az a gép?}
{000}{}{Kérdeznék valami mást, ha nem gond...}
{000}{}{Kösz az információt. [Távozol.]}
{530}{}{[Megrázza a fejét.] Nincs, csak nagyon makacs szegény... csakúgy, mint az öreg. [Vállat von.] Nyilván volna mit rajta javítgatni, de nincs játékautomata szerelõnk, aki meg tudná szerelni azt a vackot.}
{000}{}{Volna még egy-két kérdésem...}
{000}{}{Ez bizony érdekes. Kösz az információt.}
{540}{}{Ja, az a köcsög bejött ide egy hete, és az egyik asztalnál nyert vagy ezer dollárt, aztán lelépett. Nem tudom, most hol lehet, de volt neki egy szobája a Desperadóban.}
{000}{}{Ja, egy ilyen nevû fickó bérelt nálunk szobát az emeleten... 204-es. Kifizetett mindent, de néhány napja lelépett és azóta senki nem látta.}
{000}{}{Mr. Salvatore azt mondta nekem, hogy Lloyd egy bizonyos dílertõl nyerte a pénzt. Lehet tudni, kirõl van szó?}
{000}{}{Feltennék még egynéhány kérdést...}
{000}{}{Kösz az információt.}
{550}{}{Nikki? [Végignéz a termen.] Igen, a középsõ asztalnál ül. Van valami probléma?}
{000}{}{Nincs probléma. Csak össze akartam vele futni. Kérdeznék még, ha nem baj...}
{000}{}{Kösz az infót. [Távozol.]}
{560}{}{Nikki-nek HÍVTÁK. Nálunk dolgozott, de kinyírták... a közelmúltban.}
{000}{}{Hmmm. Nem baj, ha felteszek még egy-két kérdést...?}
{000}{}{Érdekes. Kösz az információt. [Távozol.]}
{570}{}{Nikki-nek hívták. Nálunk dolgozott, de nem is olyan régen felmondott. Szépen összepakolt és lelépett.}
{000}{}{Nem baj, ha még kérdezek egy s mást...?}
{000}{}{Érdekes. Kösz az információt. [Távozol.]}
{580}{}{Hogyne, számítunk rád. Az öltözõ hátul van...}
{000}{}{[Nekiállsz produkálni magad.]}
{000}{}{Majd egy kicsit késõbb. Viszont kérdeznék még valamit...}
{000}{}{Majd egy kicsit késõbb. Számíthatsz rám hamarosan... [Távozol.]}
{590}{}{[A fejét rázza.] Szó sem lehet róla, még mindig próbálunk magunkhoz térni az utolsó elõadásod óta. Asszem, jobb lesz, ha más kaszinóban próbálkozol.}
{000}{}{Jól van, köszi. Még azért kérdeznék valamit...}
{000}{}{Oké... késõbb azért visszajövök még. [Távozol.]}
{600}{}{Összeszámolod az esti keresetet. [C] dolcsi ütötte a markod. Szép summa.}
{000}{}{A bõrcucc jó ötlet volt.}
{000}{}{A szájpeckes bemutató sem volt rossz.}
{000}{}{[Rendben.]}
{610}{}{Ja, büdösebb, mint a brahminszar. Azért oké...? [Kicsit kétkedve méreget.] Hát miért is ne. Egy kis impró nem árthat, de a közönség nagyon finnyás... nagyon jónak kell ám lenned.}
{000}{}{Nem fogsz csalódni... figyelj csak...}
