# Dialog Editor last position: 53
{100}{}{Õ Rakétás Renesco.}
{150}{}{Ez itt egy idõs ember. Jókora, ízléstelen szemüveget visel, és miközben nézed, bosszankodva sóhajtozik.}
{200}{}{Õ Rakétás Renesco. Miközben figyeled, leveszi repedt szemüvegét, és az egyik ép lencséjét kezdi tisztogatni.}
{201}{}{Õ Rakétás Renesco. Miközben figyeled, leveszi repedt szemüvegét, és az egyik ép lencséjét kezdi tisztogatni.}
{210}{}{Kéne egy másik lencse. Nem olyan nagy kérés ez...}
{211}{}{Franc esne ebbe a szemüvegbe!}
{212}{}{A fene a szememet!}
{213}{}{Akarsz VÁSÁROLNI valamit?}
{214}{}{Ez itt nem kirakodóvásár! Akarsz vásárolni vagy sem?}
{215}{}{Ha tovább folytatom ezt a munkát, meg fogok vakulni.}
{216}{}{Asszem, még kell egy kis chemtex kilences alapanyag...}
{217}{}{Egyre többet és többet akarnak...}
{225}{}{Menj a fenébe!}
{226}{}{Tûnj innen, vagy lelõlek!}
{227}{}{Tûnés innen!}
{228}{}{Kifelé! Kifelé! Kifelé! Kifelé! Kifelé!}
{235}{}{(Az idõs férfi felteszi az orrára a szemüvegét, és bosszankodva sóhajt.) IGEN? Mégis mit akarsz? }
{236}{}{Gyerünk, jóember, ki vele!}
{237}{}{Gyerünk, asszony, ki vele!}
{238}{}{Oki-doki jön az... Álljá csak hátrább (Zippzár...)}
{239}{}{Oki-doki jön az... Elõbb melltartó. Figyu (Zippzár...)}
{240}{}{Én mit AKAR? MIJED VAN?}
{241}{}{Egy pillanatig rábámulsz, csak hogy biztos legyél benne, nem káprázik a szemed, aztán elpályázol.}
{242}{}{Maga kicsoda?}
{243}{}{Hé, van egy eladó szemüvegem, ha kell.}
{244}{}{Mennyi a szemüveg?}
{245}{}{Tudja, vannak koffeinmentes termékek, amelyek ugyanolyan ízûek, mint az eredeti.}
{246}{}{Asszem, nem jó helyre jöttem. Viszlát!}
{255}{}{(Megütközve néz rád.) }
{256}{}{...na tessék, egy újabb méhen kívül abortált roncs az idióta gyermekektõl hemzsegõ poszt-holokauszt világban. (Felemeli a kezét.) Tûnés az üzletembõl! Tûnj innen, de rögtön! Ne is gyere vissza, hallod??!!!}
{257}{}{Én sajnál kicsi }
{258}{}{Én nem tud hogy kell rakni vissza melltartó}
{259}{}{Nem kiabál }
{260}{}{ utál! }
{261}{}{Megyek, megyek. Most az egyszer.}
{270}{}{Hogy én? Ó, hát én vagyok a Mikulás, te kis észkombájn.}
{271}{}{Hogy én? Én vagyok a Mikulás. TE pedig bizonyára az az idióta bérenc vagy, aki éhezõ kutya módjára járja a várost a saját ürüléke nyomában.}
{272}{}{Hogy én? Én vagyok a jó öreg Mikulás. TE pedig bizonyára az az idióta pornóhulladék vagy, akinek akkora, mint egy lónak, és az esze is kábé annyi.}
{273}{}{Hogy én? Én vagyok a jó öreg Mikulás bácsi. TE pedig kétségtelenül az az idióta pornóhulladék jeles példánya vagy, akikre a ballonkabátos öreg fószerek verik a farkukat.}
{274}{}{Örülök, hogy nem kell bemutatkoznom. Mit csinál errefelé, "Mikulás úr"?}
{275}{}{Mikulás? Ki a jó fene az?}
{276}{}{Figyeljen rám, papa, még egy ilyen beszólás, és nyakláncnak fogom használni a fogsorát!}
{277}{}{Figyeljen ide, ezt most vegyük úgy, hogy nem hallottam... Szóval akkor kicsoda maga?}
{278}{}{Remek szókincse van... "Mikulás úr". Idevalósi?}
{279}{}{Felejtse el! Már itt sem vagyok.}
{290}{}{(Rádbámul, aztán rádröffen.) Renesco vagyok. Mondd meg, mit akarsz, te... akármi is legyél. (Rádsandít.) Úgy nézel ki, mint egy ruhába bújtatott, napimádó fõemlõs.}
{291}{}{Egy észak-nyugati faluból, Arroyóból jöttem.}
{292}{}{Mit árul?}
{293}{}{Hogy MIT AKAROK? Nem igazán tudom. Többnyire fittyet hányok a kitûzött feladatomra, helyette idegen házakat keresek fel, és az emberek polcain turkálok... mint például az ott!}
{294}{}{Érdekes szókincse van... Renesco. Idevalósi?}
{295}{}{Na, én leléptem...}
{305}{}{Többnyire gyógyhatású drogokat árusítok. Ezért aggatták rám az idióta Rakétás becenevet. Merthogy fellövöm õket az égbe... Hmmmm... ezenkívül karavánokat is szoktam felszerelni. Szükséged van valamire vagy mehetek a dolgomra?}
{306}{}{Rakétás? Van egy Tankcsapda szám, amiben azt énekli a srác, hogy "Félre a tréfát ûrhajós vagyok, ...mm mm... még egy rakétát". Nem emlékszik, hogy szól a szöveg egész pontosan?}
{307}{}{Láthatnám az áruját?}
{308}{}{Itt árul drogokat a BOLTBAN?}
{309}{}{Úgy érti, hogy itt árulja a drogokat a Wrighték fiának?}
{310}{}{Menjen csak, csinálja a dolgát...}
{320}{}{(Renesco rádbámul. Úgy tûnik fejben levetkõztet és egyenként kitépi a végtagjaidat.)}
{321}{}{Mindegy, hagyjuk! Kérdezek mást...}
{322}{}{Mindegy, hagyjuk!}
{330}{}{(Renesco undorral néz rád.) Igen. Itt a BOLTBAN. Ez nem a huszadik század, ahol a drogokat a büntetéstõl egyfolytában reszketõ utcasarki csótányok árulják.}
{331}{}{Na, hát akkor...}
{332}{}{De...}
{333}{}{Ööö, asszem, jobb, ha...}
{350}{}{Ez itt NEW RENO! Itt nincsenek zsaruk, nincs törvény, és rengeteg vevõ akad, akik nem riadnak vissza, hogy egy kis mérget vásároljanak maguknak a sarki gyógyszerésznél. Ez megfelelõ válasz, te fõemlõsök gyöngye?}
{351}{}{Igen, egy valamit kivéve: Richard Wright a vevõi közé tartozott?}
{352}{}{Rendben, rendben... milyen áruja van?}
{353}{}{Igazából kérdeznék inkább mást...}
{354}{}{De hát, ahogy maga is mondta, a drogok... mérgezõek. Elpusztítják az elmét. Nem zavarja, hogy ilyesmit árul?}
{355}{}{Úgy ahogy mondja. Most viszont léptem.}
{365}{}{Azt kérded, zavar-e, ha a világ hátán csak púpot jelentõ idiótáknak, hajcsároknak, maffiafõnököknek vagy vadembereknek adom el? Három szót mondok erre, Fõemlõs barátom: Járj nyitott szemmel!}
{366}{}{Oké... láthatnám az áruját?}
{367}{}{Jól van, jól van. Inkább kérdeznék valami mást...}
{368}{}{A New Renóban gyártott drogok eljutnak máshova is és ott fejtik ki áldatlan hatásukat. Ez nem aggasztja?}
{369}{}{Azzal kezdem, hogy most azonnal távozom.}
{375}{}{És? Mit kéne vele foglalkoznom?}
{377}{}{Az emberi faj szörnyû tragédián esett át! Most az újjáépítésen kéne fáradozni. A Jet árusítása... eléggé ellentmond ennek a törekvésnek.}
{378}{}{Legyen úgy... most mennem kell.}
{385}{}{És akkor mi van? Senki nem ERÕLTETI azokat az idiótákat, hogy Jetet szedjenek be. Senki nem jár körbe és nyomja le a torkukon!}
{386}{}{Láthatnám a...}
{387}{}{Nem gondol...}
{388}{}{Ez a maga...}
{395}{}{Azok a félkegyelmû kõtörõk Reddingben nagyon jól tudják, mit vesznek be, szóval egy milliméter szánalmat nem érzek irántuk! Ennyit az én aggodalmamról. A Jet szépen kipusztítja az emberi mocskot, amit a bombák életben hagytak!}
{396}{}{Öö.. oké. Láthatnám az áruját?}
{397}{}{Hol van ez a Redding, amit említett? Miért hozta szóba õket?}
{398}{}{Határozottan Reddinget említette. A Jet miért olyan fontos Reddingben?}
{400}{}{Joga van ahhoz, hogy így gondolkodjon. Nekem viszont jogomban áll most elmennem.}
{410}{}{Hát Redding egy... különleges eset. Tudod, vannak emberek Renóban, akik gondoskodnak róla, hogy Redding jól el legyen látva. Végül is, ha csak egyszer megkóstolod a Jetet, rászoksz. Én ebbõl élek.}
{411}{}{Ha már így szóba került... megmutatná az áruját?}
{412}{}{Kik azok, akik gondoskodnak Redding Jet-ellátásáról? És fõleg miért?}
{413}{}{Én is észrevettem. Amúgy volna néhány kérdésem...}
{414}{}{Értem... most mennem kell.}
{420}{}{Nos, kis fõemlõsöm, kétlem, hogy képes lennél az ilyesmit meglátni, de New Reno semmi hasznosat nem képes elõállítani. Olyan, mint egy nagy, fényes kullancs, amely ott terpeszkedik a pusztaság közepén. Ami Reddinget illeti, nos... az más kérdés...}
{421}{}{Folytassa!}
{422}{}{...IGENIS elõállít valami hasznos dolgot.}
{423}{}{Eleget hallottam.}
{430}{}{Elõször és utoljára figyelmeztetlek, vadember! Ne te fejezd be a rohadt mondataimat! Nem szeretem ha az okostojás fõemlõsök akkor szólalnak meg, amikor figyelniük kéne. Nem csoda, hogy még mindig lándzsát használtok...}
{431}{}{Nem mindannyian. Én például egész változatos fegyverarzenált használok az emberek meggyilkolására... hadd mutassam meg, mire gondolok!}
{432}{}{Bocsásson meg! Kérem, folytassa!}
{433}{}{Menjen a pokolba! Nem hallgatom ezt tovább! }
{440}{}{Reddingben jelentõs munkaerõ dolgozik a bányákban, leginkább aranyat termelnek. New Renónak egész jól jönne az az arany. Erre valaki kitalálta, hogy a bányászokat rá kell szoktatni a drogra, és mienk a világ. Érted már?}
{441}{}{Igen... egy dolgot kivéve: Honnan származik a Jet?}
{442}{}{Ki az, aki megpróbálja rászoktatni a bányászokat a drogra?}
{443}{}{Igen, értem. Kérdeznék valami mást...}
{444}{}{Nem akarok többet hallani. Mennem kell...}
{450}{}{(Myronra mutat.) Miért nem kérdezed a kis kanos varangy barátodat? Biztos, boldogan mesélne róla. (Myronra mered.) Igazam van, kölyök?}
{451}{}{Egyetlen embernek köszönhetjük a Jet létrejöttét. Hallottál a Mordino család kis aranyifjáról, Myronról? Nos, az a kis gyökér kreálta a Jetet. Nagy Jesus Mordino pedig mindenfelé hirdeti, hol lehet droghoz jutni.}
{452}{}{Mondjon még valamit Mryon-ról!}
{453}{}{Van gyógyír a Jetre?}
{454}{}{Volna még néhány kérdésem...}
{460}{}{Nagy Jesus Mordino az, aki Reddinget tömi a Jettel. Tipikus hatalmi játszma. Ha nagyüzem lesz, azoknak a bányászoknak lõttek.}
{461}{}{Honnan származik a Jet?}
{463}{}{Értem. Hadd kérdezzek valami mást...}
{470}{}{Kanos, mint egy varangy és kábé az erkölcse is azon a szinten mozog. Amúgy okos gyerek. Magas az IQ-ja. A fenébe is, arra fecsérli a tudását, hogy drogot gyártson!}
{471}{}{Hol találom õt?}
{472}{}{Értem. Hadd kérdezzek valami mást...}
{480}{}{A Mordino család jól eldugta õt valahova. Valószínûleg tisztességesen õrzik azt a helyet, de fogalmam sincs, merre található.}
{481}{}{Köszönöm az információt. Megnézhetem az áruját?}
{490}{}{Hogy van-e gyógyír a metamfetamin addikcióra? Hah! Egyrõl tudok, úgy hívják, hogy halál. A másik az, hogy bezárnak egy ketrecbe és egy álló évig nem adnak Jetet. Akkor talán kiizzadod magadból a bajt. Hmmm. Méghogy "gyógyír"! Ezt a baromságot!}
{492}{}{Kell, hogy legyen gyógyír. Mi a Jet kémiai összetétele?}
{505}{}{Itt van a barátod, miért nem kérdezed õt? Neki köszönhetjük azt a drogot.}
{506}{}{Én csak árulom az anyagot. Kérdezz egy tudóst, vagy Myront magát. Õ találta ki a Jetet.}
{515}{}{(Renesco szótlanul bámul rád.)}
{516}{}{(Renesco újra csak rádbámul, ezúttal szótlanul.)}
{517}{}{(Szerintem magának tetszene Arroyo. Békés kis falu. Az mondjuk nem annyira jó, hogy a növényeket gonosz lelkek szállták meg... és az is rossz, hogy a Próbák Temploma telis-tele van halálos dárdacsapdákkal és emberevõ óriáshangyákkal.}
{518}{}{Hallott maga valaha is az Édenkert Létrehozást Elõsegítõ Táskáról? Vagy a 13-as Menedékrõl?}
{519}{}{Akkor jó... már itt sem vagyok.}
{525}{}{(Renesco egyfolytában csak bámul.)}
{526}{}{Ráadásul a törzsfõ kis dolgokon is felhúzza magát, mint... hehe... például amikor megszegtem a nõtlenségi fogadalmamat és Az Ezer Kígyó Erejével Szorító Reynával kiosontunk az Arroyót körülölelõ kanyonba...}
{1526}{}{Ráadásul a törzsfõ kis dolgokon is felhúzza magát, mint... hehe... például amikor megszegtem a szûzességi fogadalmamat és Az Ezer Csõdörként Mennydörgõ Khorral kiosontunk az Arroyót körülölelõ kanyonba...}
#a Korral nem lett volna tul jo magyarul

{535}{}{(Renesco lesújtó pillantással illet.)}
{536}{}{Mintha csak tegnap lett volna. Reyna teste ezüstösen izzott a holdfényben, amikor letérdelt és... hé, mondok én magának valamit! Szerintem jól kijönnének a törzsfõnkkel. Nagyjából egyidõsek.}
{1536}{}{Mintha csak tegnap lett volna. Kor bronz teste ott vonaglott a holdfényben, amikor letérdeltem és... hé, mondok én magának valamit! Szerintem jól kijönnének a törzsfõnkkel. Nagyjából egyidõsek.}
{545}{}{(Renesco úgy bámul rád, mint aki abban bízik, ha elég erõsen rádgondol, eltûntethet a föld színérõl.)}
{546}{}{Említettem már, hogy Arroyót az õsöm, a szent Menedéklakó alapította? Miután a mindenkit fenyegetõ gonoszt legyõzte, legendás utazásra indult dél felõl. (Teleszívod a tüdõdet, és büszkén a messzeségbe bámulsz.) Most ÉN vagyok törzsünk kiválasztottja, akinek meg kell keresnie a szent ÉLET-et!}
{547}{}{Na, jó, elég az anekdotázásból... jobb, ha megyek a dolgomra. Dícsértessék a Menedék!}
{555}{}{(Renesco megenyhültebb képet vág.) }
{556}{}{ÉLET-et mondtál? Az Édenkert Létrehozást Elõsegítõ Táskát??? Egy alap replikátor egységgel rendelkezik, mellékeltek hozzá egy hololemez olvasót, a kongresszusi könyvtár legjelentõsebb olvasnivalóiból készített összeállítással együtt, valamint egy apró zseblámpát is találni benne.}
{557}{}{Igen, de ez most nem annyira fontos. Még nem fejeztem be az Arroyóval kapcsolatos beszámolómat.}
{558}{}{Igen! A falunknak problémája volt a terméssel, és az ÉLET kell a dolgok helyrepofozásához. Tudja, hol találhatnék egyet?}
{559}{}{Úgy tudjuk, a 13-as Menedék falai közt találni egyet, legalábbis a legendák szerint. Ismer ilyen nevû helyet?}
{560}{}{Ha nem hallgatja végig, amikor a szentírásból idézek, megyek a fenébe!}
{561}{}{Meglehet. Most viszont mennem kell.}
{570}{}{Francba az elmaradott, fûszívó falutokkal, veled együtt! Egy fõemlõs mi a fenét kezdene egy ÉLET-tel?}
{571}{}{Arroyónak... a mi elmaradott, fûszívó falunknak, ahogy maga mondja... problémája támadt a terméssel. Ahhoz, hogy megoldjuk, szükségünk van egy ÉLET-re.}
{572}{}{Azt mondják, a 13-as Menedékben van egy példány. Van tudomása egy ilyen nevû helyrõl?}
{573}{}{Most nem érzem úgy, hogy osztoznom kéne ebben. Viszlát!}
{580}{}{Hmmmm. Hát az biztos segítene... minden bizonnyal. Ha neaggyisten találnál egyet. Viszont gõzöm sincs, hol kéne kezdeni a keresést. ÚKK vagy Menedékváros talán szóba jöhet, de kétlem, hogy maradt volna nekik egy is... mindazonáltal...}
{581}{}{Mindazonáltal...?}
{590}{}{Mindazonáltal azok az öntörvényû barmok lehet, hogy mégis tudnak segíteni. Rájössz majd, ha lassan és szájbarágósan beszélnek...}
{591}{}{ÚKK vagy Menedékváros? Megyek, felkeresem ezeket a helyeket. Kikérdezem majd az ott élõ falusiakat az ÉLET holléte felõl.}
{592}{}{Miért ne lenne az ÉLET a szent 13-as Menedékben? Az írás szerint az ÉLET a szent 13-as Menedék falain belül található.}
{593}{}{Nagyon vicces. Kérdeznék azért valami mást is...}
{594}{}{Akkor jó... utánanézek. Köszönöm.}
{600}{}{A francba, dehogyis, te fõemlõs! Hallottam én Menedékekrõl, de 13-as Menedékrõl sosem. A nevében legjobban hasonlító hely Menedékváros, amely észak-kelet felé fekszik... és ha azok az arisztokratikus majompöcsök valaha is láttak egy Menedéket belülrõl, mostanra már biztosan elõjöttek belõle.}
{601}{}{Szóval Menedékváros... Megyek és megkeresem ezt a Menedékvárost, a falubelieket meg kikérdezem az ÉLET felõl. Köszönöm, Renesco. Dícsértessék a Menedék! }
{602}{}{Nocsak! Több, mint egy Menedék létezik???}
{603}{}{Hmmm, kérdeznék valami mást...}
{610}{}{Ha Menedékvárosba mész, fõemlõs barátom, nekem ne köszönj semmit! New Renóban jobban jársz. Legalábbis a koporsóméretedet felvevõ egyén nem fog a szemedbe hazudni.}
{611}{}{Rendben van... megyek Menedékvárosba. Dícsértessék a Menedék! }
{612}{}{Értem. Kösz a figyelmeztetést. }
{620}{}{Mibõl gondolod, hogy TIZENHÁRMASNAK hívják azt a Menedéket, lándzsarázó barátom? A törzsbéliek eleve pici aggyal születnek vagy rituális lobotómiát szoktatok végezni, hogy azt a kevés eszet is kiirtsátok az agyatokból?}
{623}{}{Látom, már megint elkényeztet a szövegével. Köszönöm... az információt... ha mást nem is. }
{630}{}{Itt New Renóban nem bevett beszédtéma egy ember múltja. Szóval mit is akarsz?}
{632}{}{Maga elég mûvelt embernek tûnik. Hallott valaha egy ÉLETNEK nevezett dologról és a szent 13-as Menedékrõl?}
{634}{}{Mindegy, hagyjuk... }
{640}{}{(Renesco kikapja a kezedbõl a szemüveget és miközben felbiggyeszti magára, a szeme elkerekedik.) Jószagú Reno! HOGY néz már ki ez az üzlet!? (Homlokát ráncolja.) Micsoda rendetlenség... és az ott mi a polcon? Egy nagy rakás brahminszar.}
{641}{}{Nem tesz semmit...}
{642}{}{Leld benne örömed! }
{650}{}{Hmmm! ...hát ööö... honnan szedted ezt?}
{651}{}{Hát hallottam egy kis radskorpióról, tudod, és volt egy tudós, aki tanítgatta, és... tudod mit? Még én sem hiszem el. Tartsd meg és kész, rendben van?}
{652}{}{Vegyük úgy, hogy találtam. Valahol.}
{660}{}{Hé! Álljunkmegegypillanatra! Honnan szedted ezt?}
{661}{}{Hát hallottam egy kis radskorpióról, tudod, és volt egy tudós, aki tanítgatta, és... tudod mit? Még én sem hiszem el. Tartsd meg és kész, rendben van?}
{670}{}{Hát... izé... én... hálás vagyok neked. Már azt hittem, hogy egész életemben csak szenvedni fogok a törött keret miatt. Ha tehetek valamit érted, csak szólj... és én... ööö... megpróbálok mindent.}
{671}{}{Mit szólnál egy kis árengedményhez?}
{672}{}{Szóra sem érdemes... viselje egészséggel! Ellenben kérdeznék egy s mást...}
{673}{}{Egy napon - s ez a nap talán sosem jön el - megkérem magát, hogy tegyen meg egy kis szívességet. Addig is fogadja el ezt a szemüveget a lányom esküvõje alkalmából. }
{680}{}{Ehhh...}
{681}{}{Öööö...}
{682}{}{Hogyismondjam...}
{683}{}{Oké! Oké! Adok egy kis árengedményt! Hmmm.}
{684}{}{Ugyan már, egy kis árengedmény nem a világ! Gyerünk...}
{687}{}{Nagyszerû! Nézzük, mije van "haver".}
{688}{}{Kiváló! Mindenesetre volna néhány kérdésem...}
{689}{}{Késõbb még visszajövök vásárolni. }
{700}{}{Fogd rövidre!}
{701}{}{Idehallgass, én elfoglalt ember vagyok...}
{702}{}{Na, gyerünk, ne fogd vissza magad!}
{703}{}{Igen?}
{704}{}{Beszéltem már magának a falumról, Arroyóról?}
{706}{}{Maga adott el Jetet Richard Wrightnak?}
{707}{}{Azért jöttem, hogy begyûjtsem Mr. Salvatore részesedését.}
{710}{}{A Broken Hillsi bányába keresek néhány alkatrészt...}
{711}{}{Érdekes szókincse van, mondhatom... idevalósi?}
{712}{}{Felejtse el... }
{725}{}{(Összeszükül a szeme.) Vagyis?}
{726}{}{Azért kellenek az alkatrészek, hogy megjavíthassam a bányájuk légfrissítõjét. Nekem azt mondták, maga segíteni tud rajtam.}
{727}{}{Azért kellenek az alkatrészek, hogy megjavíthassam a bányájuk légfrissítõjét. Zaius küldött. Azt is mondta még, hogy ööö... ööö... a francba.}
{728}{}{Azért kellenek az alkatrészek, hogy megjavíthassam a bányájuk légfrissítõjét. Zaius küldött. Azt is mondta még, hogy "Kipurcant a kanári.".}
{735}{}{Igen, történetesen van egy-két alkatrészem, amivel megjavíthatod a légtisztítót. 100 dolcsi lesz.}
{736}{}{Elvinném. Tessék, itt a pénz.}
{737}{}{Mit szólna ötven dolcsihoz?}
{738}{}{Öö, nincs nálam az a százas... késõbb visszajövök a pénzzel. }
{745}{}{Idõközben infláció lépett fel az alkudozásnak köszönhetõ menedzseri bosszankodás következtében. 200 vagy semmi.}
{746}{}{(Összevonja a szemöldökét.) 200 vagy semmi.}
{747}{}{Kétszáz? Az elõbb még SZÁZAT mondott?}
{748}{}{Öö, elviszem. Tessék, itt a pénze.}
{749}{}{Öö, nincs nálam két darab százas... késõbb visszajövök a pénzzel. }
{755}{}{ERÕSEN kétlem, hogy ezt mondta volna. Biztos, hogy azt mondta: Kipurcant a kanári?}
{756}{}{Hát, igen...}
{760}{}{És...?}
{761}{}{"Miféle ÉS?"}
{765}{}{És a folytatás...?}
{766}{}{"Folytatás?" Nekem nem mondott semmiféle folytatást. Az a mocskos disz...}
{769}{}{Csak teszteltelek. Nincs folytatás... Nos, ha Zaius küldött, KÖNNYEN MEGLEHET, hogy van nálam egy-két alkatrész. }
{770}{}{Tessék... vigyázz le ne ejtsd!}
{771}{}{Köszönöm. Hadd kérdezzek más egyebet...}
{772}{}{Öö, kösz... }
{780}{}{Ne próbáld ezt is rámkenni! Ha tudni akarod, ki tette, kérdezd Tweedledumb-ot és Tweedledumber-t, hogy még mindig árulják-e az arzénnal dúsított Jetet.}
{781}{}{Ki az a Tweedledumb és Tweedledumber?}
{782}{}{Jules mondta, hogy kérdezzem magát. Õ állította, hogy maga fos anyagot árul.}
{783}{}{Csipkés Jimmy J. mondta, hogy kérdezzem magát. Õ állította, hogy maga fos anyagot árul.}
{784}{}{Mindketten azt mondták, hogy kérdezzem magát. Azt állították, hogy maga fos anyagot árul.}
{785}{}{Nem hiszem, hogy arzén volt benne... viszont, hogy mérgezõ volt az tuti.}
{786}{}{Tud valamit mondani errõl az üres Jet-ampulláról?}
{788}{}{Akkor megyek és megkérdezem õket. }
{795}{}{Az a dögkeselyû Jules meg az a semmirekellõ Csipkés Jimmy. Jules folyton a város bejáratánál lófrál és a tudatlan látogatókra vadászik. Csipkés Jimmy a 2. utcán butítja a maradék renói csordát.}
{798}{}{Õk mondták, hogy kérdezzem magát, merthogy maga árulja itt a fos anyagot... ami megöli az embereket.}
{800}{}{Akkor megyek és beszélek mindkettõjükkel. }
{805}{}{Figyelj rám, fõemlõs... te még azzal sem vagy tisztában, hogy mit hablatyolsz itt össze-vissza.}
{806}{}{Ó, azt hiszem, én...}
{807}{}{Igen? Ha így van, miért nem...}
{808}{}{Felejtse el! Kérdeznék valami má...}
{809}{}{Nézze, azt hiszem, jobb, ha me...}
{815}{}{Ha még egyszer kinyitod a szád, legyen az egy kis suttogás vagy egy elejtett szó, és eljut Mr. Wright fülébe, hogy nekem... vagy neked... akármi közünk is van a gyerek túladagolásához, az életünk egy kalap brahminszart sem ér. Ha ez bekövetkezne...}
{816}{}{Hohó! Szóval magának...}
{817}{}{Hogy nekem? Várjon már egy pillanatot...}
{825}{}{Ha ez bekövetkezne, te szaros õsember, megesküszöm, hogy elõbb fogsz meghalni, mint én. Most pedig még egyszer utoljára... az a gyerek tõlem sosem vett semmiféle szart, érthetõ? Itt még a nevét se mondd ki többet, mert isten engem úgy segéljen, én...}
{826}{}{JULES azt mondja, õ nem adta el. JIMMY szintén azt mondja, hogy nem õ volt. Maga is ugyanezt állítja. Valamelyikük hazudik.}
{827}{}{JULES azt mondja, õ nem adta el. JIMMY szintén azt mondja, hogy nem õ volt. Maga is ugyanezt állítja. Valamelyikük hazudik, vagy... valaki más a felelõs.}
{828}{}{Tud még valamit Richard Wrightról mondani? Kivel látták még õt, aki esetleg összefüggésbe hozható a droggal?}
{829}{}{Rendben... ellenben kérdeznék még egy s mást...}
{830}{}{Oké, oké... már itt sem vagyok. }
{835}{}{Ezt könnyû megválaszolni. A két korcs közül valamelyik hazudik, hogy mentse az irháját. Kettejük közt oszlik meg a renói terítés 90 százaléka, ezért nyilván az egyikük lesz az, aki eladta a drogot a "fiúnak".}
{836}{}{Vagy valaki, aki hármójuk valamelyikétõl vette az anyagot. Az elmúlt hónapban kik voltak a kuncsaftjai, akik kapcsolatba kerülhettek az... áldozattal?}
{837}{}{Tud még valamit mondani Richard Wrightról? Nem került esetleg droghasználók társaságába?}
{838}{}{Értem... akkor kérdeznék valami mást.}
{839}{}{Most dolgom van. }
{845}{}{TE IDIÓTA FASZ! }
{846}{}{TE IDIÓTA RIBANC! }
{847}{}{Mondtam, hogy ne ejtsd ki a nevét ezen a helyen! Tûnés innen! Ha még egyszer meglátlak, szarrá foglak lõni! Ha Mr. Wright meggyanúsít, hogy én öltem meg a fiát, te fogsz elsõnek megdögleni!}
{848}{}{Ne fenyegessen, vén fószer...}
{849}{}{Ejha! Na, akkor most léptem... }
{855}{}{Fogalmam sincs. Nem ismerem a fiút, ezért nem ismerem a barátait vagy a szokásait sem. Ha van valaki, aki biztosat tudna mondani, már régen a Golgotán pihenget.}
{856}{}{Miféle Golgotán?}
{858}{}{Talán ezt kéne tennem. Viszlát! }
{865}{}{Akkor hiábavaló volt a menet! Mr. Salvatore "jussát" két héttel ezelõtt kifizettem, ahogy azt elõre leszögeztük. Nem tudom, ki vagy, mit akarsz, de tõlem egy büdös kanyit nem kapsz, annyi biztos! Lehet lelépni...}
{866}{}{Nézze, papi. Ne csinálja nekem itt a fesztivált! Böffentse fel a manit, mert ha nem, akkor egy percen belül vért fog felböffenteni.}
{867}{}{Én Mr. Salvatore képviselõje vagyok. Most szépen adja ide nekem az õt megilletõ részesedést, és akkor baj nélkül megússza...}
{868}{}{Megyek és leellenõrzöm Mr. Salvatore fizetési naplóját, aztán visszajövök. }
{875}{}{A füleden ülsz, fiam? }
{876}{}{A füleden ülsz, lányom? }
{877}{}{AZT MONDTAM, HOGY MÁR KIFIZETTEM. Két hete. Ha tényleg Salvatore embere vagy, tudnod kéne. Most pedig eridj innen!}
{878}{}{Figyeljen ide. Utoljára mondom: adja át a pénzt!}
{879}{}{Maga ül a fülén! Én Mr. Salvatore embere vagyok, maga pedig szépen kifizeti a részesedést ide a markomba!}
{880}{}{Én szóltam, papus! Úgy látszik, maga mindig a nehezebb utat választja. Na, akkor hulljon a férgese!}
{881}{}{Megyek, beugrom Mr. Salvatoréhoz, és rákérdezek nála a pénz ügyében. Aztán majd kitárgyaljuk. }
{890}{}{Bizonyítsd be, hogy Salvatore embere vagy, akkor TALÁN elgondolkodom, hogy adjak-e neked pénzt! Egyéb esetben szart se kapsz.}
{891}{}{Nincs szükség itt bizonygatásra. Én vagyok a képviselõje, és ez éppen elég.}
{892}{}{Maga szerint ez a lézerpisztoly dísznek van itt nálam?}
{893}{}{Ha öt másodpercen belül nem adja ide a részesedést, MEGÖLÖM magát!}
{900}{}{Tûnj innen a vérvörös picsába, te kis pitiáner tolvaj! Ha még egyszer idetolod a képed, magam puffantalak le!}
{901}{}{Én figyelmeztettem... itt az idõ, hogy csendben elhalálozzon!}
{910}{}{Hmmm. Nem számít, mert nem tudok fizetni. Az utolsó fizetés szinte teljesen lenullázott.}
{911}{}{Ez nem az én problémám. Adja ide a pénzt most azonnal! Mr. Salvatore nem kiváncsi a kifogásaira.}
{920}{}{A fenyegetõzés nálam nem jön be. Mr. Salvatore a pénzt akarja, nekem viszont nincs egy vasam sem. Haragudni fog rám, de rád is. Salvatore nem szereti azokat, akik cserbenhagyják... jobb lesz, ha sietve kitalálsz valamit.}
{921}{}{Már kitaláltam. Erre az idõszakra kifizetem a pénzét, cserébe maga árengedményt ad a boltjában.}
{924}{}{Jó, majd kitalálok valamit... késõbb találkozunk.}
{930}{}{Na, megállj, te neandervölgyi...}
{931}{}{Nem vitatkozom tovább magával. A türelmem lejárt. Hallotta a feltételeimet...}
{940}{}{Én... nézd... szóval... én... hmmmm... rendben... Megkapod azt az... "árengedményt".}
{941}{}{Hadd nézzek rá az árukészletére! Itt az idõ egy kis "bevásárlásra".}
{943}{}{Most nem akarok semmit, de ne aggódjon, még látjuk egymást. }
{950}{}{(Karbatett kézzel néz rád.) Ha azt hiszed, hogy jó szamaritánius módjára majd kapsz tõlem valamit, NAGYON tévedsz. Most pedig... mondd el, mit is akarsz!}
{951}{}{A franc esne bele abba a Halálkaromba vagy kereskedelmi igazgatóba, ami a világra hozott! Nesze! FOGD! VIGYED! VIDD AZ EGÉSZET! VIGYÉL BÁRMIT, CSAK HAGYJ BÉKÉN!}
{952}{}{Hadd nézzem az áruját!}
{953}{}{Van néhány kérdésem...}
{955}{}{Mi a fészkes fene EZ...? }
{960}{}{Milyen méregrõl hadoválsz itt össze-vissza?}
{961}{}{A test állapotából arra lehetett következtetni, hogy radskorpió méreg járta át. Attól tartok, mérgezett Jettõl halt meg és nem túladagolástól.}
{962}{}{Találtam egy üres Jet-ampullát a szobájában. Radskorpió méreg maradványai voltak benne.}
{963}{}{Na, sebaj. Kérdezek mást...}
{964}{}{Felejtse el! Most amúgy is mennem kell... }
{970}{}{Radskorpió? (Renesco hirtelen ledermed, mintha felidézett volna valamit.)}
{971}{}{Maga mocskos rohadék! Maga mérgezte meg a gyereket, ugye?!?}
{972}{}{Tud valamit róla, ugye?}
{980}{}{Na, várjunk csak egy picit!...}
{981}{}{Ne kötözködjön velem, Renesco! Ha megpróbál kibújni a felelõsség alól, hamarosan találkozik Richard-dal! Megértette?}
{982}{}{Na, jó. Megyek és beszélek Mr. Wrighttal. Legyen jó napja, Renesco... vagy mondhatnám azt is, "Viszlát!"}
{990}{}{Egy pillanat! Az a helyzet... hogy én nem adtam el drogot a gyereknek! Soha nem vásárolt tõlem! Valaki... megkért, hogy keverjek radskorpió mérget a Jethez, de... de nem én adtam el a gyereknek!}
{991}{}{Valaki megkérte? Mégis kicsoda?}
{992}{}{Kinek adta el?}
{995}{}{A Salvatore család bízott meg. Azt mondták, ez egy speciális rendelés. Nem tudtam, hogy a Wright kölyöknek akarják odaadni. Higgy nekem... gyerekek mérgezése nem az én asztalom.}
{996}{}{Csak a felnõtteké, Renesco? Te szerencsétlen faszkalap...}
{997}{}{Miért rakott mérget a Jetbe? Sejthette, hogy valakit meg akarnak ölni vele.}
{998}{}{Rendben, rendben, hiszek magának. Viszont kérdeznék még valamit...}
{999}{}{Fogja be! Válaszoljon inkább a kérdéseimre...}
{1000}{}{Szóval a Salvatore család bízta meg? Szerintem Mr. Wright szívesen tudomást szerezne errõl. }
{1005}{}{Én a Salvatore család tulajdona vagyok, ez a bolt az övék, és ha akarnak valamit, meg kell csinálnom, különben megölnek és ideraknak valaki mást. Soha nem akartam, hogy baja legyen annak a fiúnak.}
{1007}{}{Na, fogja be szépen! Válaszoljon inkább a kérdéseimre...}
{1008}{}{Persze, biztos vagyok benne, hogy a legjobb szándék vezette, amikor mérget rakott a Jetbe. Na, ég áldja, Renesco.}
{1009}{}{Viszlát, Renesco. }
{1020}{}{Annál többet, hogy üres, nem. Úgy néz ki, mint a több száz egyéb ampulla, amit New Renóban találni lehet. Segíthetek esetleg valami másban?}
{1021}{}{A magáé?}
{1022}{}{Tud valamit a radskorpió méregrõl, ami ezen az ampullán található?}
{1023}{}{Igen, kérdeznék még valamit...}
{1030}{}{Nem. Segíthetek még valamiben?}
{1033}{}{Nem. Viszlát! }
{1040}{}{A Golgota egy tömegsír délfelé. Csak kövesd a bûzt... ha egyáltalán érzed a sajátodtól...}
{1041}{}{Óh... még volna néhány kérdésem...}
{1042}{}{Renesco, ha nem hagyja abba ezt a mézesmázos dumát, sokáig fog szenvedni! }
{1043}{}{KÖSZÖNÖM, Renesco. }
{2000}{}{Fényt derítettél arra, hogy Renescónak van némi köze Richard Wright halálához.}
{5257}{}{ nagyon nagyon. Én most megy }
{5259}{}{ nem kiabál MÉRT KIABÁL? HAGYNI ABBA KIABÁLÁS }
{6259}{}{ ÖL MEG TÉGED}
{5260}{}{... *szipogsz* ...megy nagy tesóér' lenyomni tégedet öreg! Aztán jégkrémezünk... *szipogsz* ...meg TORTA jön meg nagy buli meg mókamesterek és...}
