# Dialog Editor last position: 26
{100}{}{Ez itt egy jó nagy darab bûnözõ.}
{101}{}{Õ Rico.}
{150}{}{Ez itt egy jó nagy darab, kõarcú ember. Úgy néz ki, mint aki rendszeresen téglát reggelizik.}
{151}{}{Ez itt Rico. Ittapiros testõre. Úgy néz ki, mint aki rendszeresen téglát reggelizik.}
{175}{}{Hörgghh}
{176}{}{Hnrfff}
{177}{}{Sznffff}
{178}{}{Örb-lööö}
{179}{}{Klörgggg}
{180}{}{Úúg}
{200}{}{Én Ittapiros barát. TE Ittapiros barát?}
{201}{}{Ittapiros mond kit én ütök}
{202}{}{Én verem emberek}
{203}{}{Én verem emberek mintha dobolnák}
{204}{}{Én szeret ütni}
{205}{}{::Csukott szájjal mosolyog::}
{206}{}{::Vakaródzik::}
{207}{}{::Feszeget::}
{208}{}{Horkant}
{209}{}{Horkant néhányat.}
{210}{}{Én nem szeret beszél}
{211}{}{Tied szag jó}
{212}{}{Tied szag olyan, mint mama}
{213}{}{Te lenni csinos. Én nem üt téged}
{214}{}{Én pirulok elfele}
{215}{}{Ööö... én Rico...}
