# Dialog Editor last position: 1
{100}{}{Ez egy pénzbedobós játékgép.}
{101}{}{Ez egy csillogó pénzbedobós játékgép.}
{150}{}{Ez egy pénzbedobós játékgép. Ahogy a szemed sarkából nézed, meg mernél rá esküdni, hogy téged bámul.}
{151}{}{Ez egy pénzbedobós játékgép. Fényes doboza és aranyszínû karja csábítóan ragyog New Reno fényeiben.}
{152}{}{Ez egy csillogó pénzbedobós játékgép. Költekezõ világfiaknak szánták... a minimum tét }
{153}{}{ dollár.}
{154}{}{Ez egy csillogó pénzbedobós játékgép.}
{160}{}{*Gyere, játsszunk egy kicsit, cowboy!*}
{161}{}{*Üdv, tengerész!*}
{162}{}{*Dobj be egy érmét, és húzd meg a kart! Kedves leszek hozzád.*}
{163}{}{*Klikk... klikk... Kliiiikk...*}
{164}{}{*Üdv, szépségem! Gyere, játsszunk már egy kicsit!*}
{165}{}{*Üdvözlet, szépségem.*}
{166}{}{*Hogy micsoda szépségek nem járnak erre! Miért nem játszol velem?*}
{175}{}{*Ding*}
{176}{}{*Bing*}
{177}{}{*Kattyogás*}
{178}{}{*Zzzzzzz*}
{179}{}{*Csilingelés*}
{180}{}{*Csingi-lingi*}
{185}{}{Egy három szemmel, egy karral megáldott, fura, aranyszínû fémdobozt látsz. Ez a legszebb valami, amit egész eddigi életedben láttál.}
{186}{}{Én }
{187}{}{ ki vagyol}
{188}{}{Mama hiányzik. }
{189}{}{ akar ARR-YO. Én akar menni haza}
{190}{}{(Kezet fogsz vele)}
{191}{}{Te lenni fura mutáns}
{192}{}{Dícsértesse Menelék! Dícsértesse Menelék!}
{193}{}{Te lenni víztisztáló csip?}
{194}{}{Továbbállsz, és más fényes dolgok után nézel.}
{195}{}{Távozol.}
{205}{}{A három szemmel, egy karral megáldott, fura, aranyszínû fémdoboz nem válaszol.}
{206}{}{ÉN }
{207}{}{ VÁLASZOJJ!}
{208}{}{(Kezet ráztok)}
{209}{}{Én lenni gyereke Menedéklakóé Te mostan beszélni FOGOL}
{210}{}{Te lenni fura mutáns}
{211}{}{Te lenni víztisztáló csip?}
{212}{}{Továbbállsz, és más fényes dolgok után nézel.}
{213}{}{Távozol.}
{220}{}{Megragadod a karját, és melegen megrázod. Miközben ezt teszed, egy *bzzzzzzz* hallatszik és a doboz beszélni kezd! *Kérem... dobjon be egy érmét!"}
{221}{}{Ajjjaaajjj! Robot! Robot! Futááláás!}
{222}{}{Távozol.}
{225}{}{Nincs elég pénzed, hogy játssz az automatával, és átkozni kezded a szegénységedet. Talán egy másik alkalommal...}
{226}{}{Távozol.}
{230}{}{Ez egy pénzbedobós játékgép. Fényes doboza és aranyszínû karja csábítóan ragyog New Reno fényeiben. A bedobónyílás hívogatóan kínálja fel magát, az arcod pedig a játék lázában ég.}
{231}{}{(Miközben a pénzedért nyúlsz, megremeg a kezed. A gép egyre csak suttog.) *Gyerünk, édesem... ez az... ne habozz... ne incselkedj velem...*}
{232}{}{(Miközben a pénzedért nyúlsz, megremeg a kezed. A gép egyre csak suttog.) *Gyerünk, kedvesem... ez az... ragadd meg a kart... jó erõsen... ne tétovázz...*}
{233}{}{Összesen }
{234}{}{ dolcsid van. Megkockáztatod mindet?}
{235}{}{Összesen }
{236}{}{ pénzed van. Beledobsz }
{237}{}{ dollárt?}
{238}{}{Beledobsz }
{239}{}{ dollárt?}
{240}{}{Mára elég lesz ennyi.}
{241}{}{Ma estére elég lesz ennyi.}
{245}{}{A tárcsa elkezd pörögni, és... semmit sem nyertél.}
{246}{}{SEMMI! SEMMI! Hallod a nevetését és elfog a düh... üvölteni kezdesz, és a kidobóknak kell lerángatni téged a géprõl.}
{247}{}{(A gép kuncog.) *Megkaptam, ami kijár nekem a kapcsolatunkból. Sajnálom, kedvesem. Vigyázz, nehogy fenéken billentsen a kaszinó ajtaja kifelé menet! Hahahahahahah*}
{248}{}{}
{249}{}{ dolcsid maradt. Fütyülsz a veszteségre és folytatod a játékot?}
{250}{}{}
{251}{}{ dolcsid maradt. Mindet megkockáztatod?}
{252}{}{Kiürült a zsebed. Abba kell hagynod a játékot.}
{253}{}{Kiürült a zsebed. Abba kell hagynod a játékot.}
{254}{}{Mára elég lesz ennyi.}
{255}{}{Ma estére elég lesz ennyi.}
{260}{}{Három tõr! Visszanyerted a pénzed.}
{261}{}{(A gép egyre csak suttog.) *Gyerünk, édesem... bárkivel megesik legalább egyszer az életben... próbáld újra... kérlek...*}
{262}{}{(A gép egyre csak suttog.) *Gyerünk, kedvesem... próbáld újra... ragadd meg a kart... húzd meg... ne habozz...*}
{263}{}{Még mindig van }
{264}{}{ dollárod. Tovább játszol?}
{265}{}{Még mindig van }
{266}{}{ dollárod. Folytatod?}
{267}{}{Mára elég lesz ennyi.}
{268}{}{Ma estére elég lesz ennyi.}
{275}{}{Három Töltény! Megdupláztad a pénzedet!}
{276}{}{(A gép elégedetten felsóhajt.) *Ez az, édesem... húzogasd csak a kart... gyorsabban, erõsebben, gyorsabban... ne tétovázz...*}
{277}{}{(A gép elégedetten felnyög.) *Ez az, kedvesem... húzogasd csak a kart... gyorsabban, erõsebben, gyorsabban... ne tétovázz...*}
{278}{}{}
{279}{}{ dollárod maradt! Folytatod a játékot?}
{280}{}{Mára elég lesz ennyi.}
{281}{}{Ma estére elég lesz ennyi.}
{290}{}{Három Gránát! Szent Kleofás! Megtripláztad a pénzedet!}
{291}{}{(Ahogy a pénzed megcsörren a tálcán, a gép felvisít a gyönyörtõl.) *Aiiiijjjjjjjjjj! Ez az, édesem! Ó, istenem, igen! Igen! Igen, újra! Gyorsabban! Keményebben! Mire vársz?! Csináld újra!*}
{292}{}{(Ahogy a pénzed megcsörren a tálcán, a gép nyögdécsel a gyönyörtõl.) *Ennnngghhhh! Ez az, kedvesem! Megfogtalak! Megfogtalak! Csináld még egyszer! Most ragadd meg keményebben! Keményebben!*}
{293}{}{Gyõzelmi táncot lejtesz, karjaiddal a levegõben megrázod a csípõdet, aztán mély lélegzetet veszel és tovább játszol.}
{294}{}{Pörögjetek gránátok! Új cipõ kell a gyereknek! (Tovább játszol.)}
{295}{}{}
{296}{}{ dollárod maradt. Tovább játszol?}
{297}{}{Mára elég lesz ennyi.}
{298}{}{Ma estére elég lesz ennyi.}
{305}{}{(Ez egy pénzbedobós játékgép. Fényes doboza és aranyszínû karja csábítóan ragyog New Reno fényeiben. A bedobónyílás hívogatóan kínálja fel magát, az arcod pedig a játék lázában ég. Ahogy rábámulsz, a három ablak egyike rádkacsint. A pénzbedobó nyílásból egy fojtott hang szólal meg.) *Hallgass ide! Üdvözlünk, édesem! Nem akarsz egy lányt felvidítani?*}
{306}{}{(Ez egy pénzbedobós játékgép. Erõs, masszív doboza és aranyszínû karja napistenként ragyog New Reno fényeiben. A bedobónyílás hívogatóan kínálja fel magát, a combod pedig egész beleremeg. Ahogy rábámulsz, a pénzbedobó nyílásból egy mély férfi hang suttog feléd.) *Még sosem láttam ilyen csinos nõt korábban. Szeretnél szerencsét próbálni?*}
{307}{}{::Magadba csípsz::}
{308}{}{Öö... helló.}
{309}{}{::Mély lélegzetet veszel és otthagyod::}
{315}{}{*Még mindig itt vagyok, csinibaba.* (A játékgép mélyebb hangon folytatja.) *Itt az idõ, hogy belémdobj egy kis pénzt.*}
{316}{}{*Még mindig itt vagyok, édesem.* (A játékgép mélyebb hangon folytatja.) *Szép darab egy ember vagy, hallod-e! Gyerünk! Itt az idõ, hogy kis, öreg szerénységembe gyorsan belenyomass egy kis pénzt.*}
{317}{}{Kiiiiii VAGYOL?}
{318}{}{Há' perrrsszee, hogy belléddobomm a pézt}
{319}{}{Szerintem jobb lesz addig elmennem, amíg olyasmit nem nyomatok beléd, amit megbánnék.}
{320}{}{::Mély levegõt veszel és otthagyod::}
{325}{}{*Én vagyok az ideális férfi, akit mindig is kerestél.* (A játékgép rádkacsint.) *Adj nekem egy kis pénzt, és úgy elkényeztetlek, ahogy még férfi sosem.*}
{326}{}{*Kedvesem, én vagyok az ideális nõ, akit mindig is kerestél. Csak egy kicsit figyelj rám. Tudnál rajtam, szegény vénségemen segíteni? Rajta, csak néhány érmét dobj belém!*}
{327}{}{Inkább csakhh bheszélgetni kén'}
{328}{}{Há' perrrsszee, hogy belléddobomm a pézt}
{329}{}{Szerintem jobb lesz addig elmennem, amíg olyasmit nem nyomatok beléd, amit megbánnék.}
{330}{}{::Mély levegõt veszel és otthagyod::}
{335}{}{*Hát persze, édesem, hát persze.* (A játékgép együttérzõ hangon beszél hozzád.) *Mi bántja a kis buksidat?*}
{336}{}{*Hát persze, kedvesem, hát persze.* (A játékgép együttérzõ hangon beszél hozzád.) *Mi zavar téged, szépfiú?*}
{337}{}{Mama hiányzik és ARROYO is hiányzik és én... nem találni ÉLET és... *szipogsz*}
{338}{}{Mama hiányzik meg ARROYO veszélyben és én... nemtom merre vannak... és... *szipogsz*}
{339}{}{Javítani kell nagy hajó.. és én nem tom hogy.. és az én, az én mamim eltûnt és... *szipogsz*}
{340}{}{Abbahagyni játék... és mostan én csak mászkál és... aggódni, hogy vége, meg minden és... *szipogsz*}
{341}{}{Hátcsakk azvan hogy Fallóút senem támogassa enyim 3D kártya és ojan sokk *pééézt* keelle rája kõteni *szipogsz*}
{342}{}{Akartam én jó karakterrt de *rosszan* kõtöttem pontokat elfele... és mostan fostos a karrakterem... és... *szipogsz*}
{343}{}{beszé'getek én egy játhékgépel, rosszul áll széna}
{344}{}{::Mély lélegzetet veszel, és otthagyod::}
{350}{}{*Ugyan, ugyan... ne fájjon ettõl a kis buksid... én majd mindent elboronálok. Gyere, hajtsd rám a fejed! Errõl van szó... Add ki magadból a feszültséget!*}
{351}{}{*Ugyan, ugyan... ne keseredj el, édesem... én majd mindent elboronálok. Gyere, hajtsd rám azt a szép fejed! Errõl van szó... Add ki magadból a feszültséget!*}
{352}{}{Köszi, játékgép *szipogsz* te vagyol legjobb}
{353}{}{Teee vagyol egyedül JÓÓ szeméj akivel találkozódtam mindenki ojan ajjass és próbájja BÁNT engemet meg elveszi pénztet és... *szipogsz*}
{354}{}{::Mély lélegzetet veszel, és otthagyod::}
{360}{}{(Megfáradt fejed a gépre hajtod.)}
{361}{}{*Minden rendben lesz, kedvesem? Bánt, hogy ilyen állapotban kell elengednem téged.*}
{362}{}{*Minden rendben lesz, édesem? Bánt, hogy ilyen állapotban kell elengednem téged.*}
{363}{}{Megleszek... köszönöm hogy beszété nekem, játéggép én szeret tégedet}
{370}{}{(Mintha egy könnycsepp gördülne ki a gép egyik kis ablakán.)}
{371}{}{*Te vagy az egyetlen hõsnõnk a gyökerek és rablók kétbites világában, }
{372}{}{. Vigyázz magadra, kedvesem, hallod?* (Elfordul.) *Menj, mielõtt elsírom magam.*}
{373}{}{*Te vagy az egyetlen hõsünk a gyökerek és rablók kétbites világában, }
{374}{}{ . Édesem... édesem... vigyázz magadra, hallod?* (Elfordul.) *Menj, mielõtt elsírom magam.*}
{375}{}{Viszláááát}
{380}{}{Ez itt egy extravagáns pénzbedobós játékgép. A minimum tét }
{381}{}{ dollár. Fényes doboza és aranyszínû karja csábítóan ragyog New Reno fényeiben. A bedobónyílás hívogatóan kínálja fel magát, az arcod pedig a játék lázában ég.}
{382}{}{(Miközben a pénzedért nyúlsz, megremeg a kezed. A gép egyre csak suttog.) *Gyerünk, édesem... ez az... ne habozz... ne incselkedj...*}
{383}{}{(Miközben a pénzedért nyúlsz, megremeg a kezed. A gép egyre csak suttog.) *Gyerünk, kedvesem... ez az... ragadd meg a kart... jó erõsen... ne habozz...*}
{384}{}{}
{385}{}{ dollárod maradt. Megkockáztatod mindet?}
{386}{}{}
{387}{}{ dollárod maradt. Bedobsz }
{388}{}{ dollárt belõle?}
{389}{}{Bedobsz }
{390}{}{ dollárt?}
{391}{}{Mára elég lesz ennyi.}
{392}{}{Ma estére elég lesz ennyi.}
{400}{}{A tárcsa elkezd pörögni, és... semmit sem nyertél.}
{401}{}{SEMMI! SEMMI! Hallod a nevetését és elfog a düh... üvölteni kezdesz, és a kidobóknak kell lerángatni téged a géprõl.}
{402}{}{(A gép kuncog.) *Megkaptam, ami kijár nekem a kapcsolatunkból. Sajnálom, kedvesem. Vigyázz, nehogy fenéken billentsen a kaszinó ajtaja kifelé menet! Hahahahahahah*}
{403}{}{}
{404}{}{ dolcsid maradt. Fütyülsz a veszteségre és folytatod a játékot?}
{405}{}{}
{406}{}{ dollárod maradt. Mindet megkockáztatod?}
{407}{}{Kiürült a zsebed. Abba kell hagynod a játékot.}
{408}{}{Kiürült a zsebed. Abba kell hagynod a játékot.}
{409}{}{Mára elég lesz ennyi.}
{410}{}{Ma estére elég lesz ennyi.}
{415}{}{Három bomba. Visszanyerted a pénzed.}
{416}{}{(A gép kitartóan suttog.) *Gyerünk, édesem... bárkivel megesik legalább egyszer... próbáld újra... légyszíves...*}
{417}{}{(A gép kitartóan suttog.) *Gyerünk, kedvesem... próbáld újra... ragadd meg a kart... húzd meg... ne habozz...*}
{418}{}{}
{419}{}{ dollárod maradt. Folytatod a játékot?}
{420}{}{Mára elég lesz ennyi.}
{421}{}{Ma estére elég lesz ennyi.}
{425}{}{Három Nukleáris bomba! Megdupláztad a pénzed!}
{426}{}{(A gép elégedetten felsóhajt.) *Ez az, édesem... húzogasd csak a kart... gyorsabban, erõsebben, gyorsabban... ne tétovázz...*}
{427}{}{(A gép elégedetten felnyög.) *Ez az, kedvesem... húzogasd csak a kart... gyorsabban, erõsebben, gyorsabban... ne tétovázz...*}
{428}{}{}
{429}{}{ dollárod maradt! Tovább játszol?}
{430}{}{Mára elég lesz ennyi.}
{431}{}{Ma estére elég lesz ennyi.}
{435}{}{Három gombafelhõ! Megtripláztad a pénzed!}
{436}{}{(Ahogy a pénzed megcsörren a tálcán, a gép felvisít a gyönyörtõl.) *Aiiiijjjjjjjjjj! Ez az, édesem! Ó, istenem, igen! Igen! Igen, újra! Gyorsabban! Keményebben! Mire vársz?! Csináld újra!*}
{437}{}{Ahogy a pénzed megcsörren a tálcán, a gép nyögdécsel a gyönyörtõl.) *Ennnngghhhh! Ez az, kedvesem! Megfogtalak! Megfogtalak! Csináld még egyszer! Most ragadd meg keményebben! Keményebben!*}
{438}{}{Gyõzelmi táncot lejtesz, karjaiddal a levegõben megrázod a csípõdet, aztán mély lélegzetet veszel és tovább játszol.}
{439}{}{Pörögjetek gombafelhõk! Új cipõ kell a gyereknek! (Tovább játszol.)}
{440}{}{}
{441}{}{ dollárod maradt. Folytatod a játékot?}
{442}{}{Mára elég lesz ennyi.}
{443}{}{Ma estére elég lesz ennyi.}
{1000}{}{Az esélyek nem valami kecsegtetõek.}
{1001}{}{Az esélyek kecsegtetõnek tûnnek.}
{1005}{}{Nem tudod biztosra megsaccolni az esélyeket.}
{1006}{}{Az esélyek hellyel-közel kecsegtetõek.}
{1010}{}{Az esélyek kecsegtetõnek tûnnek.}
{1011}{}{Az esélyek nem tûnnek valami kecsegtetõnek.}
{1015}{}{Az esélyek kecsegtetõnek tûnnek.}
{1016}{}{Az esélyek nem tûnnek valami kecsegtetõnek.}
