# Dialog Editor last position: 1
{100}{}{Ez a rabszolga igen beteges.}
{101}{}{Ezt a rabszolgát jól telenyomták droggal.}
{102}{}{Rabszolga.}
{150}{}{Ez az ember nagyon megtört. A tekintete ide-oda cikázik, mintha valami láthatatlan rovart akarna követni.}
{151}{}{Ez a rabszolga igen beteges. Iszonyúan ijedt képet vág, a szeme pedig képtelen rádfókuszálni.}
{152}{}{Ez a rabszolga igen beteges. A ruhája össze-vissza szakadozott, a bõre úgy lóg rajta, mint egy ruha.}
{153}{}{Ez a rabszolga igen beteges. Keservesen köhög, inge mellkasi részét vérfoltok csúfítják.}
{154}{}{Ez a rabszolga igen beteges. Rászáradt vizelet és ürülék szaga árad belõle.}
{155}{}{Ez a rabszolga igen beteges. A fogai kihullottak, a szemei vérben úsznak.}
{156}{}{Ez a rabszolga igen beteges. Az arcát és a nyakát valami jellegzetes folt tarkítja, amit idõrõl-idõre megvakar.}
{160}{}{A nõ nagyon megtört. Egyfolytában a földet bámulja, mintha nem merne felpillantani.}
{161}{}{Ez a rabszolga igen beteges. Iszonyúan ijedt képet vág, a szeme pedig képtelen rádfókuszálni.}
{162}{}{Ez a rabszolga igen beteges. Úgy tûnik, nemigen vesz tudomást a folyamatosan rászálló döglegyek hadáról.}
{163}{}{Ez a rabszolga igen beteges. A ruhája össze-vissza szakadozott, a bõre úgy lóg rajta, mint egy ruha.}
{164}{}{Ez a rabszolga igen beteges. Minden lélegzetnél zihál és a taknya-nyála összefolyik.}
{165}{}{Ez a rabszolga igen beteges. Rászáradt vizelet és ürülék szaga árad belõle.}
{166}{}{Ez a rabszolga igen beteges. Az arcát és a nyakát valami jellegzetes folt tarkítja, amit idõrõl-idõre megvakar.}
{167}{}{Ez a rabszolga igen beteges. Olyan, mintha egyfolytában sírni akarna, de könnyek nem jönnek a szemébõl.}
{170}{}{Ez itt egy igen-igen lelassult fickó. Üres szemekkel bámul maga elé.}
{171}{}{Ezt a rabszolgát jól telenyomták droggal. A szemei ide-oda cikáznak, soha nem állapodik meg semmin.}
{172}{}{Ezt a rabszolgát jól telenyomták droggal. Miközben nézed õt, beleharap a saját alkarjába, lehánt egy réteg bõrt és lassan rágni kezdi.}
{173}{}{Ezt a rabszolgát jól telenyomták droggal. Arcán halvány mosoly ül, de a tekintete fátyolos és semmitmondó.}
{174}{}{Ezt a rabszolgát jól telenyomták droggal. Üres tekintettel bámul a vakvilágba, közben pedig egyfolytában nyáladzik.}
{175}{}{Ezt a rabszolgát jól telenyomták droggal. Amint megpillant, összerezdül és fájdalmas arcot vág, mintha túl sok fényt bocsátanál ki magadból.}
{180}{}{Ez a nõ reszket. A földet bámulja, mintha attól rettegne, elmegy alóla, ha nem nézi.}
{181}{}{Ezt a rabszolgát jól telenyomták droggal. Magában kuncog, a szája sarkából vér szivárog.}
{182}{}{Ezt a rabszolgát jól telenyomták droggal. A karján szúrások helyei láthatók egyéb zúzódásokkal és korbácsnyomokkal vegyítve.}
{183}{}{Ezt a rabszolgát jól telenyomták droggal. Sebesen pislog, mintha kiszáradt volna a szeme.}
{184}{}{Ezt a rabszolgát jól telenyomták droggal. Olyan erõsen vakarja a kézfejét, hogy lejön a bõre.}
{185}{}{Ezt a rabszolgát jól telenyomták droggal. Az ingét hányás borítja, és enyhe terpentin szagot áraszt.}
{190}{}{Ez az ember igen sovány. A testét korbácsnyomok borítják, közben jámbor arccal bámul a földre, mintha csak parancsra várna.}
{191}{}{Ezt a rabszolgát jól megverték.}
{192}{}{Ez az ember igen sovány. A testét korbácsnyomok borítják, közben jámbor arccal bámul a földre, mintha csak parancsra várna.}
{195}{}{Ez a nõ reszket. A testét korbácsnyomok borítják, közben a ruhája cafatokban lóg rajta.}
{196}{}{Egy rabszolga-nõ...}
{197}{}{Egy rabszolga-nõt látsz. Egyfolytában reszket, a testét korbácsnyomok borítják.}
{200}{}{::Snnnffff::}
{201}{}{::Höhhhhk::}
{202}{}{::Köhög::}
{203}{}{::Vakaródzik::}
{204}{}{::Elhessegeti a legyeket::}
{210}{}{::Snnnffff::}
{211}{}{*Kuncog*}
{212}{}{Heeeeeeee}
{213}{}{Hee heeeee hee... hee...}
{214}{}{EeeeEEEEeeeeEEEE}
{220}{}{::Üres arccal bámul rád::}
{221}{}{::Csendesen sír::}
{222}{}{::Üres arccal bámul rád::}
{223}{}{::Hülyén pislog feléd::}
{224}{}{::Zihálva köhög::}
{225}{}{::Érthetetlenül mormog valamit::}
{226}{}{Hnnnnnh... hnnn}
{227}{}{::Megtörli az orrát a kezével::}
{228}{}{Hönnnnnhh}
{229}{}{Rrrörr..rrr... ::Köhög::}
{240}{}{::A szemét dörzsöli::}
{241}{}{::Horkant mint a disznó::}
{242}{}{::Megvakarja a fejét, aztán a szemét dörzsöli::}
{243}{}{Hee heeee hee.. hee..}
{244}{}{Ugyi Gugyi Bugyi}
{245}{}{Fúú-fúúúúúú}
{246}{}{EeeeEEEEeeeeEEEE}
{247}{}{A szemem egy nagy bogár}
{248}{}{Hú hú hú hú}
{249}{}{Húúú Húúúú}
{250}{}{Múúúúúúúúú}
{251}{}{Rossz vagyok jó vagyok rossz vagyok jó vagyok}
{252}{}{Ez mindennél jobb}
{260}{}{Már van gazdám. Nála vannak a papírjaim.}
{261}{}{Kérlek, hagyj! Már van gazdám.}
{262}{}{Könyörgöm... láttál két sötét hajú gyereket? Egy másik hajcsár vitte el õket két évvel ezelõtt és Északon adott túl rajtuk.}
{263}{}{Nagyon kérlek... nem beszélhetek senkivel!}
{264}{}{Légyszíves... hagyj békén! A gazdám mindjárt visszajön.}
{265}{}{Ha a gazdám meglátja, hogy egy hajcsárral beszélek, el fog verni.}
{266}{}{Már van gazdám. Nem fog örülni, ha meglátja, hogy veled beszélgetek.}
{267}{}{Nem beszélhetünk. El kell látnom a munkámat.}
{268}{}{Ha elkapnak, hogy egy hajcsárral beszélek, drogot fognak tesztelni rajtam.}
{269}{}{Légyszíves, menj el, hajcsár! Nem akarok bajt.}
{270}{}{Ne beszél itt szökésrõl! Én... sosem próbáltam megszökni innen. Nem mernék ellenszegülni a gazdámnak.}
{280}{}{Ha elkapnak, hogy beszélgetünk, nekiállnak drogot tesztelni rajtam.}
{281}{}{Egy másik rabszolgával dolgoztam együtt, de néhány napja meghalt túladagolásban.}
{282}{}{Rajtunk tesztelik az új drogokat. Némelyik nagyon mérgezõ.}
{283}{}{A gazdám... jó hozzám.}
{284}{}{A gazdám megtiltotta, hogy bárkivel is beszélgessek.}
{285}{}{Légyszíves... nem beszélgethetünk!}
{286}{}{Kérlek, hagyj magamra! A gazdám hamarosan visszajön.}
{287}{}{Ha a gazdám elkap, hogy beszélgetünk, el fog verni.}
{288}{}{A gazdám jó ember. Csak ritkán ver meg.}
{289}{}{Nem hiányzik a család. A gazdám kedves hozzám.}
{290}{}{Egy északi törzs falujából hurcoltak ide. Az ÉLET... itt sokkal jobb.}
{291}{}{Engem Rejtekben ejtettek foglyul.}
{292}{}{Nem beszélgethetünk. Sajnos dolgom van.}
{293}{}{Mielõtt a gazdám visszajön, be kell fejeznem a munkámat.}
{294}{}{Tilos beszélnünk!}
{295}{}{Kérlek, menj el! Könyörgöm! Így csak bajba sodorsz!}
{296}{}{Megszökni? Nincs hova. A pusztákat szörnyetegek lakják! Elevenen megeszik a szökevényeket.}
{297}{}{A lebetegedõ rabszolgákat rendszerint megölik.}
{298}{}{Nekem sikerült eljutnom New Reno-ig. A másik kettõ megbetegedett és a hajcsárok lelõtték õket.}
{299}{}{Igen? Miben segíthetek?}
{300}{}{Hallottam pletykákat rebesgetni valami földalatti vágányrendszerrõl, de nem tudok senkirõl, aki meglépett volna.}
{301}{}{Julia megszökött, de másnap elfogták a Golgotán. Kikötözték egy kerékhez, és hagyták éhenhalni.}
{302}{}{A szökevény rabszolgákat elfogják és hagyják õket meghalni a Golgotán.}
{303}{}{Nem, fogalmam sincs, hol lehet a családom. Néha még gondolok rájuk, de nem túl gyakran.}
{304}{}{New Reno, hogy is mondjam... nem olyan rossz hely, mint Rejtek. Legalábbis egy-két tekintetben.}
{305}{}{::Félve elfordul::}
{306}{}{::Fél, ezért inkább elfordul tõled.::}
{307}{}{Ha rájöttél, mit kíván a gazdád, a verések... megritkulnak.}
{308}{}{Engem is hajcsárok fogtak el. Már jó régen volt, alig emlékszem.}
{309}{}{Régen volt két gyermekem, de elhurcolták õket észak felé. Remélem, valami jobb helyen kötöttek ki, mint ez.}
{310}{}{Sajnálom, de nincs idõm beszélgetni.}
{311}{}{A gazdám mostanában haragszik rám. Azt mondja, ha még egyszer feldühítem, el fog adni az Istállóba.}
{312}{}{A szökevények mind a Golgotán végzik, vagy eladják õket az Istállóba tesztelés céljából.}
