# Dialog Editor last position: 1
{100}{}{Bokszoló.}
{101}{}{Ez itt Mike, a "Húsdaráló".}
{150}{}{A karja olyan, mint egy farönk.}
{151}{}{A karjai harckocsi lövegeknek is beillenének.}
{152}{}{Amikor megmozdul, megbabonáz az izomkötegek látványa.}
{153}{}{Éhesen nézi a füledet.}
{157}{}{Az arca olyan, mint egy darab nyers hús.}
{158}{}{Höörgggh}
{159}{}{Görhnnn}
{160}{}{Mike szétzúz}
{161}{}{Szeretem vanilia jégkrémet}
{162}{}{Gnarrrr}
{163}{}{Nrrrörhhh}
{164}{}{Mike szereti füleket}
{165}{}{Finom fül}
{166}{}{Grrrrrr}
{167}{}{Gr. Gr? Grrrrrrr.}
{168}{}{Gr?}
{169}{}{Rrrgggg}
{170}{}{Én eszek fület}
{171}{}{A fül finom}
{172}{}{Gr... grrrgr?}
{173}{}{Snrggg}
{174}{}{Utálom Robbin' Givens-t}
{175}{}{Grrrrrgrrrrgrrr... grrr... grrr... grr! Grr! Grrr?}
{176}{}{Mit jelent "részesedés" szó?}
{200}{}{::Ahogy közeledsz, Mike meghúzza magát::}
{201}{}{::Ahogy közeledsz, Mike nyöszörög::}
{202}{}{::Ahogy közeledsz, Mike megadóan felemeli a kezét::}
{203}{}{Csinos vagyol}
{204}{}{tetszik füled}
{205}{}{Elég duma volt, mennyünk ágyba}
{206}{}{Robin? Te vagyol?}
