# Dialog Editor last position: 57
{100}{}{Egy számkombinációs zárral ellátott széfet látsz a falra szerelve. Be van csukva.}
{150}{}{Egy számkombinációs zárral ellátott széfet látsz a falra szerelve. Nyitva van.}
{200}{}{(A falon egy apró ajtót látsz. Akárki is éljen mögötte, nagyon-nagyon kicsi embör kell hogy legyen! Az ajtó közepén látható még egy gomb, a peremén számokkal.)}
{000}{}{(Megvizsgálod a faliszéfet. Masszívan beleerõsítették a falba, a külsején pedig egy kombinációs tárcsa látható.)}
{000}{}{Bekopogtatsz}
{000}{}{Elfordítod a gombot}
{000}{}{Elhúzol}
{000}{}{Elkezded forgatni a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Elkezded forgatni a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Elkezded forgatni a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Véletlenszerûen elkezded forgatni a tárcsát.}
{000}{}{Átkutatod a széfet, hátha rejt valami csapdát.}
{000}{}{Hagyod a széfet, ahogy van...}
{220}{}{(Néhány kattanást követõen a széf kinyílik.)}
{000}{}{(A széf nyitva van.)}
{000}{}{(Az ajtó kicsapódik. Az apró ház belseje nagggyon sötét. És szûkös.)}
{000}{}{(Az ajtó nyitva van. Az belsõ tér nagggyon sötét. És szûkös.)}
{000}{}{Átkutatod a házikót, hátha laknak benne}
{000}{}{Továbbállsz}
{000}{}{Kifosztod a széfet.}
{000}{}{Békénhagyod a széfet.}
{240}{}{(Jónéhány percig tekergeted a tárcsát, de nem jutsz vele semmire.)}
{000}{}{Tekergeted a tárcsát, közben fülelsz a kattogó hangokra.}
{000}{}{Tekergeted a tárcsát, közben fülelsz a kattogó hangokra.}
{000}{}{Tekergeted a tárcsát, közben fülelsz a kattogó hangokra.}
{000}{}{Véletlenszerûen tekergetni kezded a tárcsát.}
{000}{}{Átkutatod a széfet, hátha találsz csapdát.}
{000}{}{Hagyod a széfet, ahogy van.}
{260}{}{(Nem találtál csapdát a széfen.)}
{000}{}{Tekergeted a tárcsát, közben pedig fülelsz a kattogó zajokra.}
{000}{}{Tekergeted a tárcsát, közben pedig fülelsz a kattogó zajokra.}
{000}{}{Tekergeted a tárcsát, közben pedig fülelsz a kattogó zajokra.}
{000}{}{Véletlenszerûen tekergetni kezded a tárcsát.}
{000}{}{Újra átvizsgálod a széfet, hátha mégis van rajta csapda.}
{000}{}{Hagyod a széfet, ahogy van.}
{270}{}{(Elfordítod a gombot... mire hirtelen kattanásokat hallasz, és az ajtó kinyílik!)}
{000}{}{(Ötletszerûen elkezded forgatni a tárcsát, ami egyszercsak bezökken a helyére... kattogásokat hallasz, és a széf kitárul!)}
{000}{}{Hahó! Hahóóó! Otthonba' valaki?}
{000}{}{Ez az, ÉN aztán tudok!}
{280}{}{(Elfordítod a gombot, de az apró ajtó nem nyílik!)}
{000}{}{(Néhány percig tekergeted a tárcsát, de nem történik semmi.)}
{000}{}{Kopogtatsz az ajtón}
{000}{}{Tovább forgatgatod a gombot}
{000}{}{Továbbállsz}
{000}{}{Tekergeted a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Tekergeted a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Tekergeted a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Ötletszerûen tovább tekergeted a tárcsát.}
{000}{}{Megvizsgálod a széfet, van-e rajta valami csapda.}
{000}{}{Hagyod a széfet, ahogy van.}
{300}{}{(Nem hallasz senkit, és csengõt sem látsz. Talán nincs is otthon senki.)}
{000}{}{(Senki nem jön ajtót nyitni.)}
{000}{}{(Fájni kezd a kezed.)}
{000}{}{(Ha van is otthon valaki, nem akar ajtót nyitni.)}
{000}{}{Újra kopogtatsz az ajtón}
{000}{}{Elfordítod a gombot}
{000}{}{Eloldalogsz}
