# Dialog Editor last position: 1
{100}{}{Az elõtted látható széfet masszívan beleerõsítették a falba. Az ajtaja csukva van.}
{150}{}{Az elõtted látható széfet masszívan beleerõsítették a falba. Az ajtaja nyitva van.}
{200}{}{(A falon egy apró ajtót látsz. Akárki is éljen mögötte, nagyon-nagyon kicsi embör kell hogy legyen! Az ajtó közepén látható még egy gomb, a peremén számokkal.)}
{000}{}{(Megvizsgálod a faliszéfet. Masszívan beleerõsítették a falba, a külsején pedig egy kombinációs tárcsa látható.)}
{000}{}{Bekopogtatsz}
{000}{}{Elfordítod a gombot}
{000}{}{Elpályázol}
{000}{}{[JBJBJB]}
{000}{}{Elkezded forgatni a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Elkezded forgatni a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Elkezded forgatni a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Véletlenszerûen elkezded forgatni a tárcsát.}
{000}{}{Átkutatod a széfet, hogy megtaláld a Mrs. Bishop által említett csapdát.}
{000}{}{Átkutatod a széfet, hátha rejt valami csapdát.}
{000}{}{Hagyod a széfet, ahogy van.}
{220}{}{(Kattanásokat hallasz, és a széf már nyitva is van.)}
{000}{}{(A széf nyitva van.)}
{000}{}{(Az ajtó kicsapódik. Az apró ház belseje nagggyon sötét. És szûkös.)}
{000}{}{(Az ajtó tárva-nyitva. Az apró ház belseje nagggyon sötét. És szûkös.)}
{000}{}{Átkutatod a házat, hátha laknak benne}
{000}{}{Elpályázol}
{000}{}{Kifosztod a széfet.}
{000}{}{Hagyod a széfet, ahogy van.}
{230}{}{(Tüzetesebb szemlélõdést követõen találsz egy apró plasztikbombát, amit a széf alá erõsítettek. Úgy állították be, hogy akkor robbanjon, ha valaki rossz számot üt be. Az egészet vékony réteg gipsz fedte, hogy nehezebb legyen megtalálni.)}
{000}{}{Megpróbálod hatástalanítani a csapdát.}
{000}{}{Alaphelyzetbe állítod a csapdát, hogy egy másik kombinációra lépjen mûködésbe.}
{000}{}{Hagyod a széfet, ahogy van.}
{240}{}{(Jónéhány percig tekergeted a tárcsát, de nem jutsz vele semmire.)}
{000}{}{[JBJBJB]}
{000}{}{Tekergeted a tárcsát, közben figyelsz a kattogó hangokra.}
{000}{}{Tekergeted a tárcsát, közben figyelsz a kattogó hangokra.}
{000}{}{Tekergeted a tárcsát, közben figyelsz a kattogó hangokra.}
{000}{}{Véletlenszerûen tekergetni kezded a tárcsát.}
{000}{}{Hagyod a széfet, ahogy van.}
{250}{}{(Nem találtál semmiféle csapdát a széfen.)}
{000}{}{[JBJBJB]}
{000}{}{Tekergeted a tárcsát, közben figyelsz a kattogó hangokra.}
{000}{}{Tekergeted a tárcsát, közben figyelsz a kattogó hangokra.}
{000}{}{Tekergeted a tárcsát, közben figyelsz a kattogó hangokra.}
{000}{}{Véletlenszerûen tekergetni kezded a tárcsát.}
{000}{}{Újra átvizsgálod a széfet, hátha mégis van rajta csapda.}
{000}{}{Hagyod a széfet, ahogy van.}
{260}{}{(Elfordítod a gombot... mire hirtelen kattanásokat hallasz, és az ajtó kinyílik!)}
{000}{}{(Ötletszerûen elkezded forgatni a tárcsát, ami egyszercsak bezökken a helyére... kattogásokat hallasz, és a széf kitárul!)}
{000}{}{Hahó! Hahóóó! Otthonba' valaki?}
{000}{}{Ez az, ÉN aztán tudok!}
{270}{}{(Elfordítod a gombot, de az apró ajtó nem nyílik!)}
{000}{}{(Néhány percig tekergeted a tárcsát, de nem történik semmi.)}
{000}{}{Kopogtatsz az ajtón}
{000}{}{Tovább forgatod a gombot}
{000}{}{Továbbállsz}
{000}{}{[JBJBJB]}
{000}{}{Tekergeted a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Tekergeted a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Tekergeted a tárcsát, és fülelsz a kattogó hangokra.}
{000}{}{Ötletszerûen tovább tekergeted a tárcsát.}
{000}{}{Hagyod a széfet, ahogy van.}
{290}{}{(Nem hallasz senkit, és csengõt sem látsz. Talán nincs is otthon senki.)}
{000}{}{(Senki nem jön ajtót nyitni.)}
{000}{}{(Fájni kezd a kezed.)}
{000}{}{(Ha van is otthon valaki, nem akar ajtót nyitni.)}
{000}{}{Újra kopogtatsz az ajtón}
{000}{}{Elfordítod a gombot}
{000}{}{Eloldalogsz}
{300}{}{(Sebészi pontossággal hatástalanítod az indítószerkezetet, és kihúzod a plasztikbombát a falból. A csapda mostantól hatástalan.)}
{000}{}{Nézzük, mit rejt a széf...}
{000}{}{Hagyod a széfet, ahogy van.}
{310}{}{(Sebészi precizitással szétkapod az indítószerkezetet, és átállítod a kombinációs kallantyút. A széf tulajdonosa meg fog lepõdni, ha legközelebb kinyitja.)}
{000}{}{Nézzük, mit rejt a kicsike...}
{000}{}{Hagyod a széfet, ahogy van.}
