# Dialog Editor last position: 1
{100}{}{Egy számkombinációs zárral ellátott széfet látsz a falra szerelve. Be van csukva.}
{101}{}{Egy számkombinációs zárral ellátott széfet látsz a falra szerelve. Nyitva van.}
{120}{}{Amint épp nekiállsz a széf zárjának megberheléséhez, észreveszed, hogy a széf alatt egy drót fut végig a falban. Nagyon úgy tûnik, hogy csapdával látták el ezt a vackot.}
{121}{}{A széfen még mindig rajta van a csapda.}
{150}{}{Halk kattanásokat követõen a széf zárja megadja magát.}
{160}{}{Véletlenszerûen elkezded tekergetni a kombinációs zárat, amikor a tárcsa hirtelen megakad egy számnál... kattanásokat hallasz, aztán a széf zárja engedni kezd.}
{170}{}{Jónéhány percig tekergeted a tárcsát, de nem jutsz vele semmire.}
{171}{}{Jónéhány percig tekergeted a tárcsát, de semmi nem történik.}
{180}{}{Találtál egy csapdát a széfen, de sikeresen hatástalanítottad.}
{181}{}{A széfre szerelt csapdát sikeresen hatástalanítottad.}
{190}{}{Találtál egy csapdát a széfen, de nem sikerült hatástalanítanod.}
{200}{}{Szerinted nincs csapda a széfre szerelve.}
{201}{}{Nem sikerült hatástalanítanod a széfre szerelt csapdát.}
{220}{}{Minden bizonnyal tanácsos lenne újraélesíteni a széfet egy kis plasztikkal vagy dinamittal.}
{230}{}{A széf kombinációját sikerült megváltoztatni... hehehe...}
{231}{}{A széf kombinációját sikerült megváltoztatni... már megint...}
{240}{}{Nincs meg a tudásod, hogy a kombinációt megváltoztasd.}
{241}{}{ nem rendelkezik a megfelelõ tudással, hogy megváltoztassa a kombinációt.}
{250}{}{A széfet be kéne csukni.}
{260}{}{A széfen már van egy csapda.}
{270}{}{Nem sikerült csapdát szerelned a széfre.}
{271}{}{ elügyetlenkedte a csapda felszerelését a széfre.}
{280}{}{A széfre szerelt csapdát sikerült újraélesíteni.}
{300}{}{Az emeletrõl tompa robbanást hallasz.}
{400}{}{A széf alján lefeszítesz egy apró panelt. Szerinted ha Mrs. Bishop nem mondta volna el, hol van, sosem találtad volna meg. A belsejében egy furcsa kinézetû PipBoy kiegészítõt találsz.}
{290}{}{Miközben csapda után kutatsz a széf környékén, felrobban az egész...}
{291}{}{Miközben a csapdát hatástalanítottad, a rossz drótot húztad meg.}
