# Dialog Editor last position: 1
{100}{}{A koporsóban egy idõs ember holtteste fekszik. A torkát elvágták. A testen semmi nincs.}
{101}{}{Pritchard teste egy masszív fakoporsóban fekszik, és úgy tûnik, valaki elvágta a torkát.}
{150}{}{Miközben átkutatod Pritchard testét, lehúzod a csizmáját, és észreveszed, hogy a lábbeli egyik sarka lazább, mint kéne. Lefeszíted, és találsz benne egy rongyos térképet, amely egy "SHR" nevû helyet jelöl. Gyorsan betáplálod a PipBoyba.}
{200}{}{A sírkõ szerint: "Itt nyugszik Sam Pritchard: Olyan sokat beszélt, hogy kapott egy másik szájat is."}
{250}{}{Megtaláltad Pritchard sírját... és a Sierra Hadiraktár helyét jelölõ térképet szintén.}
{255}{}{Hmmm... Asszem, találtam egy nyomot.}
{256}{}{Hmmm... szééép papér... én játssza rajta "cuwa"}
