{100}{}{}
{101}{}{}
{110}{}{Nagyon viszket a lábfejed.}
{120}{}{Kis ocsmány bütykök nõnek a lábfejeidre.}
{130}{}{A cipõd nagyon szorít, a bütykök tényleg nõnek.}
{140}{}{Az ocsmány kis bütykökbõl új lábujjak lettek. De legalább az a tartós, égõ viszketés elmúlt.}
{141}{}{Istenem, ez Bess!}
{150}{}{Amiért elboronáltad a Hubologista ügyét Merk számára, }
{151}{}{ experience points for getting the GECK.}
