{100}{}{}
{101}{}{}
{110}{}{Nagyon viszket a lábfejed.}
{120}{}{Kis ocsmány bütykök n?nek a lábfejeidre.}
{130}{}{A cip?d nagyon szorít, a bütykök tényleg n?nek.}
{140}{}{Az ocsmány kis bütykökb?l új lábujjak lettek. De legalább az a tartós, ég? viszketés elmúlt.}
{141}{}{Istenem, ez Bess!}
{150}{}{Amiért elboronáltad a Hubologista ügyét Merk számára, }
{151}{}{ experience points for getting the GECK.}
