# Dialod Editor last position: 1
{100}{}{}
{101}{}{}
{110}{}{Nagyon viszket a lábfejed.}
{120}{}{Kis ocsmány bütykök nõnek a lábfejeidre.}
{130}{}{A cipõd nagyon szorít, a bütykök tényleg nõnek.}
{140}{}{Az ocsmány kis bütykökbõl új lábujjak lettek. De legalább az a tartós, égõ viszketés elmúlt.}
{141}{}{Uram-atyám, ez Bess!}
{150}{}{}
{151}{}{ tap. pontot kaptál az ÉLET megszerzéséért.}
