{100}{}{Ez a Halálkarom szokatlanul intelligens tekintettel néz rád.}
{101}{}{Dar, a Halálkarmok egyike.}
{102}{}{Egy átlagos Halálkarmot látsz. Óriási teremtmény, erõs testtel, éles fogakkal és karmokkal felvértezve.}
{103}{}{Üdv, ember!}
{104}{}{Mit akarsz?}
{105}{}{Szia. Te ki?}
{106}{}{Miért vagy itt?}
{107}{}{Okos vagy, mint a többi?}
{108}{}{Én unatkozza, menek.}
{109}{}{Elnézést a zavarásért, de ki vagy te?}
{110}{}{Mi a munkád a menedékben?}
{111}{}{Ne vedd sértésnek, de mennyire vagy mûvelt?}
{112}{}{Hát, csak lógatom a lábam.}
{113}{}{Dar vagyok, harcos.}
{114}{}{Oké.}
{115}{}{Ti egyformák. Elmegyek.}
{116}{}{Én} #continue 137
{117}{}{Értem. Most már mennem kell.}
{118}{}{Én} #continue 138
{119}{}{Értem.}
{120}{}{Harcos! Ha! Ez jó. Tudsz még valamit ezen kívül?}
{121}{}{Dar õrzi a hallt, és a békét. Semmi több.}
{122}{}{Hallani elõtte.}
{123}{}{Oké.}
{124}{}{Hát, te aztán jól dolgozol Dar. Csak így tovább!}
{125}{}{Ja, rájöttem én is.}
{126}{}{Semmi újdonság. Azt hiszem, megyek is.}
{127}{}{Egy ilyen pofával, mint a tied, hogyan tartod fenn a békét?}
{128}{}{Te nem vagy szép. Mennyé innen!}
{129}{}{Nem nagyon, de tanulok. Gruthar, a vezetõnk, mondta, hogy tanuljunk.}
{130}{}{Törzsfõ a faluban ugyanez csinál nekem.}
{131}{}{Ah.}
{132}{}{Grutharnak igaza van, meg kell próbálnotok önállóan tanulni.}
{133}{}{Értem.}
{134}{}{Szóval olyan hülye vagy, hogy másnak kell tanulásra ösztönözni téged? Na, szép...}
{135}{}{Helló, te falka-barát!}
{136}{}{Grrrrrrrrr! Argggggghhhh.}

{137}{}{.}
{138}{}{ vagyok, Dar.}