# Dialog Editor last position: 50
{100}{}{Halálkarom.}
{101}{}{Kerith, a Halálkarom anya.}
{102}{}{Egy átlagos Halálkarom. Az állat óriási, erõs testû, éles fogai és hosszú karmai vannak. Ez nõsténynek tûnik, de semmi biztosat nem tudsz. A felsõtestét sebhelyek borítják.}
{103}{}{Egy ember... Hm... furcsa, de nem kellemetlen látogató. Kerith vagyok.}
{104}{}{Miben lehetek a segítségedre?}
{105}{}{Te Halá'karom anya?}
{106}{}{Ki Halá'karom apa?}
{107}{}{Ajtó, kinéz, mint roncs. Mi történni?}
{108}{}{Ki építeni fészek szoba?}
{109}{}{Menni most.}
{110}{}{Szóval te vagy a Halálkarom anya?}
{111}{}{Ki a Halálkarom apa?}
{112}{}{Mi történt az ajtóval? Úgy tûnik, szebb napokat is megért már...}
{113}{}{Ki építette ezt a költõszobát?}
{114}{}{Elmegyek.}
{115}{}{Igen. Én vagyok a jelenlegi falka-anya. Amint kikelnek a tojásaim, a többi anyára kerül a sor.}
{116}{}{Okés.}
{117}{}{Többi anyára?}
{118}{}{Értem.}
{119}{}{Vannak más anyák is?}
{120}{}{Igen, több anya van. Bármi történjen is velem, egyet kiválasztanak helyettem. A falkának túl kell élnie.}
{121}{}{Öö, én érteni.}
{122}{}{Értem.}
{123}{}{Ezeket a tojásokat Gruthar, a falkavezér nemzette. Gruthar dönti el, ki párosodik és ki nem. Az õ segítségével erõsek leszünk.}
{124}{}{Öö, oké.}
{125}{}{Hmmm. Értem. Szelektív párosítás a szaporulat javításáért.}
{126}{}{Fájdalmas emlék ez. Egy álnok ember beosont, és bombát telepített a tojások közé, amíg aludtam. Szerencsére a fickó nem tudott elég óvatosan kiosonni, így hát felébredtem. Nem volt idõm vacakolni a bombával, ezért odadobtam az ajtóhoz, és a testemmel védtem a tojásokat. Mi túléltük, az ajtó nem.}
{127}{}{Mi lett emberrel?}
{128}{}{Hogy jutni át õrökön?}
{129}{}{Nekem lenni még kérdés.}
{130}{}{Mi történt az elkövetõvel?}
{131}{}{Hogyan tudott átjutni az õrökön?}
{132}{}{Van még pár kérdésem.}
{133}{}{Matt a neve, jelenleg fogoly. A legjobb lenne, ha meghalna, de Gruthar nem hagyná. Nem látom benne a logikát, de Gruthar szava törvény, mi pedig engedelmeskedünk. Beszélhetsz az emberrel, de légy óvatos! Megbízhatatlan!}
{134}{}{Hogy jönni át õrökön?}
{135}{}{Okés.}
{136}{}{Hogyan tudott átjutni az õrökön?}
{137}{}{Okés.}
{138}{}{Az õrök csak az eset után kerültek ide. Korábban túl magabiztosak voltunk, azóta sokkal óvatosabbak lettünk.}
{139}{}{Mi történni emberrel?}
{140}{}{Vettem.}
{141}{}{Mi lett ezzel a személlyel?}
{142}{}{Értem.}
{143}{}{Mi építettük a barlang részt, és egy ember barátunk az ajtót. Egy észak-keleti településrõl hozta az alkatrészeket.}
{144}{}{Lenni kedves.}
{145}{}{Ez kedves volt tõle.}
{146}{}{Újra nálunk? Jó, hogy látlak. Miben segíthetek?}
{147}{}{Csak mondani helló. Menni máris.}
{148}{}{Csak beköszöntem. Megyek is.}
{149}{}{Elszomorít, hogy meg kell öljelek.}
