{100}{}{Egy számítógép-terminált látsz.}
{101}{}{A hangmodul interfész-terminálja.}
{102}{}{Egy átlagos, hétköznapi számítógép-terminált látsz, hangmodullal kiegészítve.}
{103}{}{Megvizsgálod a gépet, de semmi érdekeset nem találsz. Mit teszel?}
{104}{}{'Spéci' ütést mérek rá.}
{105}{}{'Spéci' rúgást mérek rá.}
{106}{}{Lefuttatom a diagnosztikát.}
{107}{}{Szétszedem, és belenézek.}
{108}{}{Békén hagyod.}
{109}{}{You gaze at the console for a while and decide upon the best spot to place a punch. After giving
 it your best 'this'll fix it' hit, the monitor flashes a couple of times and then stabilizes. There is
 no other effect. What do you do?}
{110}{}{'Spéci' rúgást mérek rá.}
{111}{}{Lefuttatom a diagnosztikát.}
{112}{}{Szétszedem, és belenézek.}
{113}{}{Békén hagyod.}
{114}{}{Ez a jól-ismert javítási folyamat két dolgot eredményezett. A monitor látszólag kiakadt pár percre, aztán helyreállt a kép. Ezzel egyidőben fémtörés-szerű hangot hallatott, majd a megrúgott panel leesett a földre. Mit teszel?}
{115}{}{Lefuttatom a diagnosztikát.}
{116}{}{Ez a vacak nyitva van. Akár bele is nézhetnék.}
{117}{}{Békén hagyod.}
{118}{}{Biztos vagy benne, hogy kell itt lennie valami diagnosztikai tesztnek. Mindenesetre úgy tűnik, a billentyűzet le van zárva. Az egység csak hangüzenetet fogad. Mit teszel?}
{119}{}{Már csak egy dolog maradt hátra: belenézni.}
{120}{}{Békén hagyod.}
{121}{}{Ahogy beletúrsz a kábelrengetegbe, a kártyák közé, észreveszed, hogy a rendszert szándékosan tönkretették. Az egyik kártya, a hangazonosító modul, javításra szorul, ki kell cserélni. Már csak keresni kell egy pótkártyát.}
{122}{}{[Kész]}
{123}{}{[Kész]}
{124}{}{Miután belehelyezted a modult a terminálba, a rendszer megjavult.}
{125}{}{Ha esetleg használni szeretnéd a terminált, telepítened kell egy hangmodult.}
{126}{}{[Kész]}
{127}{}{A rendszer jól működik.}
{128}{}{Hozzáférés a biztonsági naplóhoz, holografikus felvétel betöltése...}
{129}{}{Te vagy az utolsó, Gruthar. A hozzád hasonló szennyet hamarosan kiirtjuk a világból.}
{130}{}{Mondd meg az úgynevezett "Elnöködnek", hogy ezt keservesen megbánja!}
{131}{}{Jártasd csak a szád! Soha nem voltál több egy beszélő állatnál!}
{132}{}{That may be, but we were created through your experimentation. You gave us life!}
{133}{}{Most majd halált adok.}
{134}{}{Hozdd a testét! A dokinak kell egy kis minta.}
{135}{}{Úgy folyik majd a vérük, mint a Nílus!}
