{100}{}{Számítógép-terminál.}
{101}{}{A hangmodul interfész-terminálja.}
{102}{}{Egy átlagos, hétköznapi számítógép-terminált látsz, hangmodullal kiegészítve.}
{103}{}{Megvizsgálod a gépet, de semmi érdekeset nem találsz. Mit teszel?}
{104}{}{'Spéci' ütést mérek rá.}
{105}{}{'Spéci' rúgást mérek rá.}
{106}{}{Lefuttatom a diagnosztikát.}
{107}{}{Szétszedem, és belenézek.}
{108}{}{Békén hagyom.}
{109}{}{Egy ideig bámulod a konzolt, majd kiválasztod a legjobb helyet az ütés számára. Miután elhelyezted rajta a 'mindent megoldó' ütést, a monitor néhányat villan, és helyreáll a kép. Más nem történt. Mit teszel?}
{110}{}{'Spéci' rúgást mérek rá.}
{111}{}{Lefuttatom a diagnosztikát.}
{112}{}{Szétszedem, és belenézek.}
{113}{}{Békén hagyom.}
{114}{}{Ez a jól-ismert javítási folyamat két dolgot eredményezett. A monitor látszólag kiakadt pár percre, aztán helyreállt a kép. Ezzel egyidõben fémtörés-szerû hangot hallatott, majd a megrúgott panel leesett a földre. Mit teszel?}
{115}{}{Lefuttatom a diagnosztikát.}
{116}{}{Ez a vacak nyitva van. Akár bele is nézhetnék.}
{117}{}{Békén hagyom.}
{118}{}{Biztos vagy benne, hogy kell itt lennie valami diagnosztikai tesztnek. Mindenesetre úgy tûnik, a billentyûzet le van zárva. Az egység csak hangüzenetet fogad. Mit teszel?}
{119}{}{Már csak egy dolog maradt hátra: belenézni.}
{120}{}{Békén hagyom.}
{121}{}{Ahogy beletúrsz a kábelrengetegbe, a kártyák közé, észreveszed, hogy a rendszert szándékosan tönkretették. Az egyik kártya, a hangazonosító modul, javításra szorul, ki kell cserélni. Már csak keresni kell egy pótkártyát.}
{122}{}{[Kész]}
{123}{}{[Kész]}
{124}{}{Miután belehelyezted a modult a terminálba, a rendszer megjavult.}
{125}{}{Ha esetleg használni szeretnéd a terminált, telepítened kell egy hangmodult.}
{126}{}{[Kész]}
{127}{}{A rendszer jól mûködik.}

{128}{}{Hozzáférés a biztonsági naplóhoz, holografikus felvétel betöltése...}

{129}{}{Te vagy az utolsó, Gruthar. A hozzád hasonló szennyet hamarosan kiirtjuk a világból.}
{130}{}{Mondd meg az úgynevezett "Elnöködnek", hogy ezt keservesen megbánja!}
{131}{}{Jártasd csak a szád! Soha nem voltál több egy beszélõ állatnál!}
{132}{}{Lehet, de mi a kutatásaitokból születtünk. Ti adtatok életet nekünk!}
{133}{}{Most majd halált adok.}
{134}{}{Hozdd a testét! A dokinak kell egy kis minta.}
{135}{}{Úgy folyik majd a vérük, mint a Nílus!}