# Dialog Editor last position: 162
{100}{}{Terminál.}
{101}{}{Ez egy terminál. Mûködõképesnek látszik.}
{102}{}{Egy DataPlex 2000 SmarTerminált látsz, full 64t RAM-mal, a mai technika csúcsa, kár, hogy nem mûködik.}
{103}{}{Egy DataPlex 2000 SmarTerminált látsz, full 64t RAM-mal. Ez a mai technika csúcsa.}
#A terabyte talan elfogadhato ezidotajt (Bass)
{104}{}{Üdvözöljük a PosiedoNeten! Válasszon a menübõl:}
{105}{}{Bejelentkezés.}
{106}{}{Súgó.}
{107}{}{Vége.}
{108}{}{A terminál egy westernfilmet játszik - rohadt unalmas.}
{109}{}{A terminál valami lövöldözõs programmal játszik. Csak azt látod, hogy mindent telibe trafál.}
{110}{}{Ezen a terminálon valamiféle modern mûvészeti alkotás látható - egy csomó különbözõ színû vonal egy rakáson.}
{111}{}{Egy terminált látsz. Kis zöld bombák úsznak átlósan a képernyõn.}
{112}{}{Ezen a terminálon egy üzenetet látsz: "Most már kikapcsolhatja a számítógépet." Fogalmad sincs, ez mit jelent.}
{113}{}{Egy képet látsz különbözõ árnyalatú kék, vörös és zöld pontokból...}
{114}{}{Ez a terminál egy visszataszító arcképet mutat... ja, hogy ki van kapcsolva... hm...}
{115}{}{Ez a terminál egy idõn túli dimenzióba néz.}
{116}{}{A terminálon ez a felirat olvasható: "Fenestra 98 indítása" A terminált vastag porréteg fedi.}
#Windows tul direkt lenne, ok sem irtak, pedig irhattak volna :) (Bass)
{117}{}{Ezen a gépen valami barack-jel van. Épp valami Fallout 2 nevû program fut rajta. Anyád, ez 3D meg többjátékos módú!}
#Nyilvan az apple a poen targya (bass)
{118}{}{Azonosítás:}
{119}{}{(Próbáljuk meg ezt) Felhasználói lista.}
{120}{}{(Ez vajon beenged?) Smith, John}
{121}{}{Vissza.}
{123}{}{Ezt valahogy máshol kellene csinálni.}
{124}{}{Listázás. (A terminál vagy 500 nevet görget le.)}
{125}{}{Listázás. (A terminál egy rakás nevet görget le.)}
{126}{}{Azonosítsa magát, vagy lépjen ki!}
{127}{}{(Ennek van hozzáférése) Smith, John}
{128}{}{(Ez valami egyedinek tûnik) Belépés elnöki kulcskártyával - Biztonsági rendszer felülírása}
{129}{}{(Ennek közepes hozzáférése van) Murray, Tom}
{130}{}{(Ennek magas hozzáférése van) Curling, Dr. Charles}
{131}{}{(Ennek nagyon magas hozzáférése van) Bird, Daniel}
{132}{}{(Majd inkább máskor) Kijelentkezés.}

#Ehhez a sok szarhoz ne nyuljatok, mert szetesik az egesz, en belottem.
#Az eredetiben is szar, biztos siettek a vegen. Most jo. :) (bass) 
#Az elcsusztatott veguek is jok


{133}{}{Válasszon:                                              }
{134}{}{                A .E. C.: Atomreaktor vezérlés                }
{135}{}{                     Biztonsági státusz:}
{136}{}{Letöltés: A. E. C.: Atomreakor vezérlés                     }
{137}{}{Biztonsági státusz:                                         }
{138}{}{Vissza az azonosításhoz:                                    }
{139}{}{Válasszon:                                              }
{140}{}{                Biztonsági szint: Jelenlegi állapot              }
{141}{}{                   Vegyi Kutatóalakulat: Projekt állapota          }
{142}{}{                 A. E. C.: Atomreaktor vezérlés                    }
{143}{}{                 Biztonsági státusz?                         }
{144}{}{Biztonság/szint: Jelenlegi állapot                          }
{145}{}{Letöltés: Vegyi Kutatóalakulat - Projekt állapota           }
{146}{}{Letöltés: A. E. C.: Atomreaktor vezérlés                    }
{147}{}{Biztonsági státusz                                          }
{148}{}{Vissza az azonosításhoz:                                    }
{149}{}{Válasszon:                                             }
{150}{}{                A Nemzet helyzete: Jelenlegi státusz        }
{151}{}{                 (Szavak listája)                            }
{152}{}{                Biztonsági szint: Jelenlegi állapot            }
{153}{}{                Vegyi Kutatóalakulat: Projekt állapota         }
{154}{}{                A. E. C.: Atomreaktor vezérlés              }
{155}{}{                Biztonsági státusz?                         }
{156}{}{A Nemzet helyzete: Jelenlegi státusz                        }
{157}{}{Letöltés: Szavak listája                                    }
{158}{}{Biztonság/szint: Jelenlegi állapot                          }
{159}{}{Letöltés: Vegyi Kutatóalakulat - Projekt állása             }
{160}{}{Letöltés: A. E. C.: Atomreaktor vezérlés                    }
{161}{}{Biztonsági státusz                                          }
{162}{}{Vissza az azonosításhoz:                                    }
{163}{}{Válasszon: Biztonsági státusz?                              }
{164}{}{Biztonsági státusz                                          }
{165}{}{Hozzáférés vége.                                            }
{166}{}{A letöltés befejezõdött.                                    }
{167}{}{A Nemzet helyzete: Jelenlegi státusz                        }
{168}{}{Letöltés: Szavak listája                                    }
{169}{}{Biztonság/szint: Jelenlegi állapot                          }
{170}{}{Letöltés: Vegyi Kutatóalakulat - Projekt állása             }
{171}{}{Letöltés: A. E. C.: Atomreaktor vezérlés                    }
{172}{}{Vissza az azonosításhoz:                                    }
{173}{}{A letöltés befejezõdött.                                    }
{174}{}{Letöltés: Szavak listája                                    }
{175}{}{Biztonság/szint: Jelenlegi állapot                          }
{176}{}{Letöltés: Vegyi Kutatóalakulat - Projekt állása             }
{177}{}{Letöltés: A. E. C.: Atomreaktor vezérlés                    }
{178}{}{Biztonsági státusz                                          }
{179}{}{Vissza az azonosításhoz:                                    }
{180}{}{A letöltés befejezõdött.                                    }
{181}{}{A Nemzet helyzete: Jelenlegi státusz                        } 
{182}{}{Biztonság/szint: Jelenlegi állapot                          }
{183}{}{Letöltés: Vegyi Kutatóalakulat - Projekt állása             }
{184}{}{Letöltés: A. E. C.: Atomreaktor vezérlés                    }
{185}{}{Biztonsági státusz                                          }
{186}{}{Vissza az azonosításhoz:                                    }
{187}{}{Körletek: Biztonsági lövegek élesített és riasztott állapotban.}
{188}{}{Körletek: Biztonsági lövegek normál állapotban.}
{189}{}{Körletek: Biztonsági lövegek átmenetileg deaktivált módban.}
{190}{}{Tesztalanyok szintje: Biztonsági lövegek élesített és riasztott állapotban.}
{191}{}{Tesztalanyok szintje: Biztonsági lövegek normál állapotban.}
{192}{}{Tesztalanyok szintje: Biztonsági lövegek átmenetileg deaktivált módban.}
{193}{}{Kutatási- és fejlesztési szint: Biztonsági lövegek élesített és riasztott állapotban.}
{194}{}{Kutatási- és fejlesztési szint: Biztonsági lövegek normál állapotban.}
{195}{}{Kutatási- és fejlesztési szint: Biztonsági lövegek átmenetileg deaktivált módban.}
{196}{}{Adminisztráció: Biztonsági lövegek élesített és riasztott állapotban.}
{197}{}{Adminisztráció: Biztonsági lövegek normál állapotban.}
{198}{}{Adminisztráció: Biztonsági lövegek átmenetileg deaktivált módban.}
{199}{}{Erõmû szint: Biztonsági lövegek élesített és riasztott állapotban.}
{200}{}{Erõmû szint: Biztonsági lövegek normál állapotban.}
{201}{}{Erõmû szint: Biztonsági lövegek átmenetileg deaktivált módban.}
{202}{}{Biztonsági szint átállítása                                 }
{203}{}{A Nemzet helyzete: Jelenlegi státusz                        }
{204}{}{Letöltés: Szavak listája                                    }
{205}{}{Letöltés: Vegyi Kutatóalakulat - Projekt állása             }
{206}{}{Letöltés: A. E. C.: Atomreaktor vezérlés                    }
{207}{}{Biztonsági státusz                                          }
{208}{}{Vissza az azonosításhoz:                                    }
{209}{}{A letöltés befejezõdött.                                    }
{210}{}{A Nemzet helyzete: Jelenlegi státusz                        }
{211}{}{Letöltés: Szavak listája                                    }
{212}{}{Biztonság/Szint: Jelenlegi állapot                          }
{213}{}{Letöltés: A. E. C.: Atomreaktor vezérlés                    }
{215}{}{Biztonsági státusz                                          }
{216}{}{Vissza az azonosításhoz:                                    }
{217}{}{A letöltés befejezõdött.                                    }
{218}{}{Letöltés: A Nemzet helyzete - Jelenlegi státusz             }
{219}{}{Letöltés: Szavak listája                                    }
{220}{}{Biztonság/Szint: Jelenlegi állapot                          }
{221}{}{Letöltés: Vegyi Kutatóalakulat - Projekt állása             }
{222}{}{Biztonsági státusz                                          }
{223}{}{Vissza az azonosításhoz:                                    }


#Itt a vege


{224}{}{Ez a terminál mélydiagnosztikai mûveleteket végez. Kérjük, próbálkozzon egy másik terminálnál! Köszönjük.}
{225}{}{Üdvözöljük a PoseidoNet Súgójában. Sajnálattal közöljük, hogy a Súgó állománya elavult, és átmenetileg nem is elérhetõ. Keres frissítést?}
{226}{}{Igen.}
{227}{}{Nem, vissza.}
{228}{}{A frissítés nem lehetséges a próbaidõszakos PoseidoNet szoftverrel. Kérjük, vásárolja meg a teljes verziót a teljes hozzáféréshez. Az Ön tesztidõszaka 59.439 napja lejárt.}
{229}{}{Vissza a bejelentkezéshez.}
{230}{}{Vége.}
{231}{}{A Biztonsági rendszerek felülírása csak elnöki kulcskártyával lehetséges. Újabb menüpontok: Felkelés elfojtása, Vészvédelmi rendszerek leállítása.}
{232}{}{(Hm, nézzük meg ezt!) Lázadás elfojtása.}
{233}{}{(Hm, vessünk rá egy pillantást!) Vészvédelmi rendszerek leállítása.}
{234}{}{(Inkább valami kevésbé gázos dologgal próbálkozom.) Vissza az azonosításhoz.}
{235}{}{(Nem akarok most ezzel bajlódni) Kijelentkezés.}
{236}{}{Felkelés elfojtása. Fegyveres lázadás esetén az elnöki kulcskártya lehetõvé teszi a védelmi rendszerek átprogramozását, hogy az elõzõleg lojális, de idõközben veszélyessé vált embereket támadja. A védelmi rendszer a mindenkori legerõsebb egyént célozza. Figyelmeztetés! Átmenetileg csak a Belépõ szinten mûködtethetõ!}
{237}{}{(Ez használható lehet.) Aktiválás - Felkelés elfojtása protokoll.}
{238}{}{(Még megnézhetem.) Vissza.}
{239}{}{(Nem akarok most ezzel játszani.) Kijelentkezés.}
{240}{}{Elnöki kulcskártyát elfogadtam... Jó napot, Elnök úr... Felkelés elfojtása protokoll inicializálva... Célpont bemérve.}
{241}{}{(Lássuk, mi történik!)}
{242}{}{Elnöki kulcskártyát elfogadtam... Jó napot, Elnök úr... Lázadás elfojtása protokoll inicializálva... **Üzemzavar**... A biztonsági hálózat ezen a szinten nem mûködõképes. Kérjük, hogy a javítás megkezdéséhez szerezze meg az FG-I-106-32-0635 protokoll kódját. Köszönjük, hogy újabb kiváló Menedék-Tek terméket használt. További jó napot!}
{243}{}{(Ja, szóval a Belépõ szint alatt a dokk utáni területet érti. Akkor ott majd mûködni fog.) Vissza az azonosításhoz.}
{244}{}{(Mi más van itt még?) Vissza.}
{245}{}{A protokoll aktiválásához elnöki kulcskártya szükséges. A kártya nem található.}
{246}{}{(Mi más van itt még?) Vissza.}
{247}{}{A Vészvédelmi rendszerek leállítása átmenetileg az összes aktív védelmi eszközt lekapcsolja szintrõl-szintre. A leállítást, mielõtt a rendszerek újraindulnának, hosszú mélydiagnosztika követi.}
{248}{}{(Ez jónak hangzik.) Aktiválás - Vészvédelmi rendszerek leállítása.}
{249}{}{(Hm, talán kicsit késõbb.) Vissza.}
{250}{}{(Nem akarok szórakozni most ezzel.) Kijelentkezés.}
{251}{}{Elnöki kulcskártyát elfogadtam... Jó napot, Elnök úr!... A Vészvédelmi rendszerek leállítása megtörtént. Mélydiagnosztika megkezdése. Alfa... Bravo... Charlie...}
{252}{}{(Nem akarok ezzel bajlódni.) Vissza.}
{253}{}{(Jobb, ha sietek, amíg ez megy.) Kijelentkezés.}
{254}{}{Elnöki kulcskártya nem található. Hozzáférés megtagadva.}
{255}{}{(Hm, kíváncsi vagyok, ki tudom-e játszani a szkennert, ha belenyúlok a fájlokba. Megpróbálom.)}
{256}{}{(Hát, azért szép próbálkozás volt.) Vissza.}
{257}{}{Biztonsági szkenner üzemzavar... Szkenner újrakalibrálása...}
{258}{}{(Na, most ugrik a majom a vízbe, vajon felismeri-e a "kártyát"...)}
{259}{}{(Francba, sose jön be...) Vissza.}
{260}{}{Szkenner újrakalibrálva. Újraszkennelés...}
{261}{}{(Na, itt a nagy alkalom!) - Lázasan gépelsz.}
{262}{}{Illegális tevékenységet észleltem. További hozzáférés megtagadva. Riadó!}
{263}{}{A picsába! Egyáltalán nem ezt akartam!}
