# Dialog Editor last position: 10
{100}{}{Egy szakadt pénztárost látsz.}
{101}{}{Messzirõl látszik rajta, hogy gyakorlatilag bármit megvenne azért, hogy az emberek itt játsszannak.}
{102}{}{Mit aka'sz?}
{103}{}{Elvesztegetnék néhány dolgot.}
{104}{}{Semmit.}
{105}{}{ akar csecsebecse.}
{106}{}{ megy, viszla.}
{107}{}{Bármi egyebet?}
{108}{}{Van még néhány eladó cuccom.}
{109}{}{ akar még csecsebecse.}
