# Dialog Editor last position: 1
{100}{}{Ez itt egy nagy szakállú, lompos kinézetû alak.}
{101}{}{Õ Athabaska Dick.}
{102}{}{Ez az ember olyan bányásznak látszik, aki tudja mi a dörgés.}
{103}{}{Te túl ostoba vagy a bányászmelóhoz.}
{104}{}{Isten hozott a nagyvárosban!}
{105}{}{Van valami beütésed, mi?}
{106}{}{Annyi eszed van mint egy marék lepkének.}
{107}{}{Volt olyan lapátom, aminek több esze volt, mint neked.}
{108}{}{Többnyire csak a szokásos. Mi bányászok csak annyit dolgozunk, amennyi a következõ Jetetúrához elég.}
{109}{}{Mi lenne, ha valami mást kérdeznék?}
{110}{}{Mi az a Jet?}
{111}{}{Értem. Viszlát!}
{112}{}{Nos, a legtöbbünk belegebed, hogy elég Jethez jusson. A rohadt árak meg állandóan csak mennek felfelé. Gyûlölöm azt az érzést, mikor nem repülhetek.}
{113}{}{Hadd kérdezzek valami mást!}
{114}{}{Mi az a Jet?}
{115}{}{Értem. Viszlát!}
{116}{}{Nem tudok én annyit dógozni, amennyi Jet kéne nekem ahhoz, hogy jól érezzem magam. Tán ki tudnánk ókumulálni valamit New Renóval, má' direktbe értem. Hallottam, hogy Ascorti mán ügyködik ezen.}
{117}{}{Hadd kérdezzek valami mást!}
{118}{}{Ascorti? Az ki?}
{119}{}{Mi az a Jet?}
{120}{}{Értem. Viszlát!}
{121}{}{Nem érzem magam valami jól mostanában, és úgy néz ki, ezzel nem vagyok egyedül. Próbáltam még több Jetet benyomni, de szart se segít. Inkább csak rosszabbul érzem magam tõle. A béka segge alatt vagyok, akárcsak a többi bányász.}
{122}{}{Kérdeznék valami mást.}
{123}{}{Mi az a Jet?}
{124}{}{Értem. Viszlát}
{125}{}{Nem tudom, mi történt, de a legutóbbi szállítmány után majdnem mindenki leállt a Jettel. Úgy éreztem, hogy mindannyian a nagy égi reptéren fogunk kikötni. Mostanság már senki nem akar többet Jetezni. Már a gondolatától is irtózunk.}
{126}{}{Kérdeznék valami mást.}
{127}{}{Mi az a Jet?}
{128}{}{Világos. Viszlát!}
{129}{}{Adjisten, Athabaska Dick vagyok. Az emberek általában csak Dick-nek szólítanak. Persze van olyan, aki Athabaskának hív, de leginkább mégiscsak Dick-nek.}
{130}{}{Üdvözlet! Mit tehet érted a jó öreg Athabaska Dick?}
{131}{}{Sietek. Gyorsabban, gyorsabban! Na? Mire vársz? Ha Athabaska Dickkel akarsz beszélni, akkor gyorsabban kell járjon a szád!}
{132}{}{Mi... mit akarsz? Nem látod, hogy dógom van? (morog magában) Muszáj mindig dógozni ... dógozni ... dógozni...}
{133}{}{(nyög egyet) Mit akarsz az öreg Athabaska Dicktõl? (magának) Úgy érzem, mintha fejbe rúgott volna egy öszvér.}
{134}{}{Baromi szarul érzem magam. Mivel akarod a jó öreg Dick-et zargatni?}
{135}{}{Üdv, Athabaska Dick vagyok. Valaha egyfolytában Jet-mámorban éltem, de többé hozzá nem nyúlok ahhoz a szarhoz!}
{136}{}{Születésem óta nem éreztem magam ilyen mosogatórongynak.}
{137}{}{Dick, mit csinálsz te itt?}
{138}{}{Hé, Dick, mi újság a városban?}
{139}{}{Nem hallottál valami érdekes pletykát?}
{140}{}{Mit jelent ez az Ad-ta-baszta?}
{141}{}{Mi bajod van?}
{142}{}{Mi történt veled?}
{143}{}{Itt dolgozgatok a Morningstarnál. Mindig szükségük van kétkezi munkásokra.}
{144}{}{Akkor hadd kérdezzek valami mást.}
{145}{}{Értem. Hát, csak ennyit akartam tudni. Viszlát!}
{146}{}{Hát mostanában nem sokat, kivéve azokat a dög Wanamingókat.}
{147}{}{Milyen mongolokat? Mi a franc az?}
{148}{}{Hát persze. Hadd kérdezzek valami mást.}
{149}{}{Csak ennyit akartam tudni. Viszlát!}
{150}{}{Atha-baska, Athabaska. Nem olyan átkozottul nehéz azt kimondani! Kriminális. Ez a gúnynevem. Akarod tudni, hogy ragadt rám?}
{151}{}{Öö, nem igazán. Inkább kérdeznék valami mást.}
{152}{}{Azt hiszem, csak ennyit akartam tudni. Viszlát!}
{153}{}{Jójézus! Betegebb vagyok, mint egy kutya és már napok óta csak üvöltök a fájdalomtól... mióta azt az utolsó adag Jetet bevettem. Valamit elszúrhattak azzal a szállítmánnyal. Ha túlélem, én ugyan nem nyúlok többet a Jethez!}
{154}{}{Rosszul hangzik. Viszont kérdeznék még valamit.}
{155}{}{Értem. Azt hiszem, csak ezt akartam tudni. Viszlát!}
{156}{}{Megtettem. Egyelõre nem érzem magam túl jól, de tudom, hogy jobb lesz nélküle.}
{157}{}{Mit beszélsz? Mi történt?}
{158}{}{Azt mondod, még sosem hallottál a Wanamingókról?}
{159}{}{Öö, nos, izé. Persze, hogy hallottam a Wanamingókról. Kérdeznék valami mást, ha nem gond.}
{160}{}{Nem, soha nem hallottam róluk. Felvilágosítanál?}
{161}{}{Soha nem hallottam ilyen Wanya-minya-monyókról és nincs idõm arra, hogy a meséidet hallgassam. Viszlát!}
{162}{}{Egyszerûen abbahagytam - ennyi történt. Soha többé nem nyúlok a Jethez. Az az utolsó adag majdnem megölt. Utána már nem is kívántam annyira, és érdekes módon azóta sem.}
{163}{}{Hát jó neked! Kérdeznék még valamit.}
{164}{}{Érdekes dolgok vannak. Hát, akkor hagylak gyógyulni. Viszlát!}
{165}{}{Egyesek szerint már az atom-, hidrogén- és az összes többi franc-tudja-milyen bomba elõtt itt voltak. Vannak, akik szerint gén-eti-kailag tenyésztették ki õket, fegyvernek. Oszt vannak, akik szerint egy tök más bolygóról valók.}
{166}{}{Mik "ezek" a lények? Nem érdekel, honnan jöttek, csak az, hogy micsodák!}
{167}{}{Ja, persze. Na, eleget hallottam, öregfiú. Viszlát!}
{168}{}{Hát, azt pontosan nem tudom, hogy micsodák, de azt tudom, hogy pár éve miattuk zárták be a várostól nyugatra lévõ Wanamingo Bányát.}
{169}{}{Miattuk zárták be a Wanamingo Bányát?}
{170}{}{Ez tetszik. Na, jobb, ha megyek, öregfiú. Kösz a történetet! Viszlát!}
{171}{}{Bezony. És a Nagy Wanamingo volt a leggazdagabb telér ezen a részen, az ám! Most viszont mindenki messze elkerüli. Idehallgass, akár meg is vehetnéd Ascortitól, ha akarnád! Persze senki nem akarja.}
{172}{}{Ahogy mondtam. A Nagy Wanamingo volt a leggazdagabb bánya a környéken, most meg akár bagóért is megveheted.}
{173}{}{Szóval megvehetném... Ér egyáltalán valamit?}
{174}{}{Ki az az Ascorti?}
{175}{}{Számomra ez túl veszélyesnek hangzik. Viszlát!}
{176}{}{Hát most nem igazán. Te nem figyelsz oda, amit mondok? Tele van azokkal a rohadt Wanamingókkal. Persze mindjárt más lenne a leányzó fekvése, ha valaki kipucolná a helyet. Tán nem is kéne mindet kinyírni!}
{177}{}{Hova akarsz kilyukadni ezzel?}
{178}{}{Milyen leányzóról beszélsz? Nõhiányod van, vagy mi? Na, hagylak álmodozni! Viszlát!}
{179}{}{Van ott lenn néhány cucc, amiért a Morningstar és a Kokoweef bányák tulajdonosai élbõl szép kis summát fizetnének.}
{180}{}{Miféle cuccról van szó?}
{181}{}{Pénz. Hmm. Na, most mennem kell. Viszlát!}
{182}{}{Hát, tudod a bányákat valaha nagy gépekkel vájták ki. A francba, azokat az örökkévalóságnak építették! Mindkét bányának vannak nagy ásógépei. De - és itt jön be a pénz a képbe - a rohadt kis vezérlõchipek nem bizonyultak túl tartósnak. Egyik bányának sincs belõle mûködõképes példánya. Hehe.}
{183}{}{Nem vagyok biztos benne, hogy értem az okfejtésed.}
{184}{}{Minél több alkatrész van valamiben, annál nagyobb az esély, hogy el is romlanak. Kösz az infót. Viszlát!}
{185}{}{Én bizony azt mondom neked, hogy egy ilyen ásógép-vezérlõ chipért bármelyik bányatulajdonos úgy fizetne, mint a katonatiszt. Naná, ha neki van egy mûködõ gépe, a másik bányának meg nincs, akkor a másik bányát bezárathatja, vagy semmi perc alatt felvásárolhatja.}
{186}{}{Bizony nagy kár, hogy senki sem tudja, honnan lehetne ilyen csipet szerezni.}
{187}{}{Utána kell nézzek, mennyit fizetnének egy ilyen chipért. Kösz, viszlát!}
{188}{}{Mosd már ki a rohadt füledet! Megmondtam, hol keresd azt az átkozott chipet! Egy árva szóra sem figyeltél abból, amit mondtam? A Wanamingo bányának voltak gépei és a bánya bezárásáig mûködtek is. Valszeg a csipek még mindig odalenn vannak. Csak arra várnak, hogy valaki lemenjen értük és felhozza õket.}
{189}{}{Hm, hát lehet. Kérdeznék még valamit.}
{190}{}{Na, akkor mesélj nekem azokról a Wanto-mongolokról!}
{191}{}{Kösz, ennek utána kell néznem. Viszlát!}
{192}{}{Naszóval - Isten a megmondhatója, hogy igazat beszélek - ismerek valakit, aki látott egyet egész közelrõl... (rövid idõ elteltével)... Hatalmas szemfogai voltak, amiket arra használt... (sokkal több idõ elteltével)...}
{193}{}{Volt egy haverom, akivel együtt dolgoztam és egy napon... (kis idõvel késõbb) ...akkora volt, mint egy brahmin, csak jóval büdösebb... (sok idõvel késõbb)...}
{194}{}{Csinálhatsz te bármit, akkor is elalszol, de sebaj. Szóval késõ éjjel volt, amikor... (kis idõ elteltével) ...a nyomok mintha egy radskorpió és egy gekkó keverékétõl származtak volna... (valamivel késõbb) ...Na, látod, mondtam én, hogy elalszol!}
{195}{}{He, mi!? (Felkapod a fejed. Kissé elszenderedtél.)}
{196}{}{Jobb, ha keresek valamit, ami segít ébren maradni. Viszlát!}
{197}{}{...Na, most már tudod. A bányában egykor dolgozó rabszolgák inkább felrobbantották a dinamitraktárat és elmenekültek, minthogy szembeszálljanak azokkal a Wanamingókkal. A bányát ezután rögtön bezárták és azóta sem ment oda vissza senki.}
{198}{}{Mit is mondtál, hol van ez a Nagy Wanamingo Bánya?}
{199}{}{Érdekesnek tûnik. Na, egyelõre viszlát!}
{200}{}{Ippeg nyugatra a várostól. De úgy hallottam, hogy késõ éjjel néhány Wanamingo be szokott tévedni a városba. Sz'al, lehet, hogy nem is kell odamenned, hogy találkozz velük. Hehe.}
{201}{}{Azt hiszem, már mindent hallottam a Wanamingókról. Kérdeznék valami mást.}
{202}{}{Majd óvatos leszek egy ilyen Wanda Mentollal. Viszlát!}
{203}{}{Ascorti a polgármester. Övé az Ascorti Ásza a belvárosban. Mindenféle cuccokat ad és vesz. Körülötte forog minden.}
{204}{}{Ascorti Redding polgármestere. Mondjuk nem igazán tudom, merre lehet. Jó ideje nem láttam.}
{205}{}{Inkább valami más érdekelne.}
{206}{}{Ó, rendben. Halljuk a történet folytatását!}
{207}{}{Azt hiszem, eleget hallgattalak. Viszlát!}
{208}{}{A Jet egy kis New Reno-i meglepi. Épp csak annyit szedek be, hogy kisimítsa az idegeimet.}
{209}{}{Kérdeznék valami mást.}
{210}{}{Érdekes. Kösz és viszlát!}
{211}{}{A Jet maga az élet, haver. Ha nem repülhetnék, nem is érezném magam jól többé. Neked is szerezned kellene egy keveset.}
{212}{}{Kérdeznék valami mást.}
{213}{}{Érdekes. Kösz és viszlát!}
{214}{}{Jet nélkül nem tudnék ellenni. Mostanában mindenki repül. Ki kell próbálnod, csak hogy érezd! A francba, nem érzem magam olyan jól vele, mint amennyire szarul érzem magam nélküle.}
{215}{}{Kérdeznék valami mást, oké?}
{216}{}{Érdekes. Kösz és viszlát!}
{217}{}{Barátom, a Jet félresikerült dolog. Akik használják, olyan betegek lesznek, mint akik menten meghalnak. Azt hiszem, én már jobban... (összegörnyed és szárazon öklendezik egy kicsit) ...elnézést. Mondd csak, nem beszélhetnénk valami másról?}
{218}{}{De, bocsánat. Inkább kérdezek valami mást.}
{219}{}{Érdekes. Kösz és viszlát!}
{220}{}{Soha többé nem akarok hallani arról az átkozott Jetrõl! Az az anyag megöl téged! Itt dögöljek meg, ha nem rosszabb, mint a radskorpió-méreg. Nem is értem, hogy lehettem oda azért az anyagért. Legutoljára... azt hittem, végem.}
{221}{}{Mit szólnál, ha rátérnénk valami másra?}
{222}{}{Érdekes. Köszi és viszlát!}
