# Dialog Editor last position: 1
{100}{}{Ez a megfáradt asszony fiatalabb korában egész jól nézhetett ki.}
{101}{}{Lou-t, a Malamute Szalon tulajdonosát látod.}
{102}{}{Egy idõsebb, meglehetõsen kirúzsozott nõt látsz.}
{103}{}{Csak azt akartam, hogy tudja, hálás vagyok azért, amit tett. Segíthetek valamiben?}
{104}{}{A börtön túl enyhe azért, amit az a gazember mûvelt.}
{105}{}{Egyszerûen nem tudom elhinni, hogy futni hagyta azt a gazembert, aki összevagdalta a lánykámat! Magának aztán van bátorsága, hogy még vissza is mer jönni ide. Mi a frászt akar?}
{106}{}{Maga akkor is tök idióta. Persze az élet megy tovább, legalábbis a számunkra. Szóval mi a frászt is akar?}
{107}{}{Emlékezzen, mit mondtam! A túl sok pénz nem tesz jót ennek a lánynak. Na, mi kõne, ha vóna?}
{108}{}{Üdv, Lou vagyok. A Malamute Szalon tulajdonosa. Ez a legjobb betérõ San Francisco-tól északra.}
{109}{}{Nos tehát?}
{110}{}{Óóó?}
{111}{}{Üdv, Lou. Szükségem lenne valamire.}
{112}{}{Hallott már egy bizonyos Édenkert Létrehozást Elõsegítõ Táskáról?}
{113}{}{Üdv, Lou. Mi újság a városban?}
{114}{}{Mi az a Malamute?}
{115}{}{Merre van innen San Fran?}
{116}{}{Besegítek a seriffnek. Õ szólt, hogy összevagdalták az egyik lányát.}
{117}{}{Bocs, de sem idõm, sem türelmem nincs az ostoba emberekhez. Mit akarsz?}
{118}{}{Itaa?}
{119}{}{Szoba?}
{120}{}{Viszla.}
{121}{}{Italt akarsz, ugye? Egy üveg finom, hideg sör 25 dollárba kerül. Mivel az együgyûek a szívem csücskei, extra kedvezményes árat kapsz.}
{122}{}{Itaa? (felé nyújtod a tárcádat)}
{123}{}{Szoba?}
{124}{}{Nincs itaa. Pá pá.}
{125}{}{Szobát akarsz? Hát lehet, hogy van valahol egy szobám a számodra. 50 dolcsi lesz egy kényelmes hely.}
{126}{}{Szoba. (felé nyújtod tárcádat)}
{127}{}{Itaa?}
{128}{}{Nincs szoba. Pá pá.}
{129}{}{Te bejöhetsz, de a torzszülött vándorcirkusz kinn marad.}
{130}{}{Nem hallottad? Nem tûrök torzszülötteket a szalonomban!}
{131}{}{Azok az "akármik" nem jöhetnek be a szalonba. Hagyd kinn õket!}
{132}{}{Nem mondhatnám, hogy korábban hallottam volna ilyenrõl. Mi az?}
{133}{}{Nos ez egy eszköz, amivel... hát, izé. Szóval valami, amit keresek. Beszéljünk valami másról!}
{134}{}{Nem igazán fontos. Azt hiszem, jobb, ha megyek a dolgomra.}
{135}{}{Nos, itt fõleg aranyat bányászunk és eladjuk más városoknak.}
{136}{}{Aranyat bányásznak?}
{137}{}{Hol adják el az aranyat?}
{138}{}{Ez érdekes. Inkább beszéljünk valami másról!}
{139}{}{Ja. Egyedül a város északi szélén két mûködõ aranybánya is van.}
{140}{}{Azt mondta, hogy arannyal kereskednek?}
{141}{}{Érdekes. Mindegy, kérdeznék valami mást.}
{142}{}{Menedékvárosból gyógyeszközöket kapunk az aranyért. Az Új Kalifornia Köztársaság friss brahmin-húst és más élelmet ad érte, New Reno pedig kábítószert és piát.}
{143}{}{Maguk bányásszák az aranyat?}
{144}{}{Érdekes. Mindegy, kérdeznék valami mást.}
{145}{}{Csak egy nagytestû kutya.}
{146}{}{Á, már értem. Izé, hadd kérdezzek még valamit!}
{147}{}{Természetesen. Ez minden, amit tudni akartam. Köszi, viszlát!}
{148}{}{Jó messze van innen. Délre és egy hangyányit nyugatra. Rögtön az óceán partján, ha nem tudnád. Nem tudom, miért akarna egy épeszû ember odamenni.}
{149}{}{Miért? Veszélyes?}
{150}{}{Érdekes. Kérdeznék még valamit.}
{151}{}{Kösz az információt. Viszlát!}
{152}{}{Hallottam én mindenféléket, hogy az egész városban nincs semmi egyéb, csak egy fura vallás õrült hívei.}
{153}{}{Miféle õrült hívekrõl beszél?}
{154}{}{Egyes dolgok nem változnak másokhoz képest. Viszlát és kösz.}
{155}{}{Azt hallottam, hogy valami hatalmas berendezést építenek, amivel kapcsolatba léphetnek az isteneikkel. Vagy valami ilyesmi. Nem vagyok biztos benne. Túl messze van.}
{156}{}{Azt hiszem, az isteneknek állított emlékmûvek mindig valami bajt hordoznak a mélyükben. Beszéljünk valami másról!}
{157}{}{Most csak ennyit akartam tudni. Kösz és viszlát!}
{158}{}{Pontosan. Elég rosszul van, pedig valaha egész csinos volt. Remélem, gyorsan a végére jár ennek. Rosszat tesz az üzletnek, ha azok a bányászok azt hiszik, megúszhatnak egy ilyen dolgot.}
{159}{}{Láthatnám a lányt?}
{160}{}{Tudja, hogy ki tette?}
{161}{}{Tudja, hogy mi történt?}
{162}{}{Rendben, ez tényleg zûrösnek hangzik. Kérdeznék valami mást.}
{163}{}{Elküldtem. Ebben az üzletben neki már nem terem babér. Nem mintha bárki is vele akart volna lenni az után, amit az a gazember tett vele. Adtam neki egy kis pénzt és útjára bocsátottam.}
{164}{}{Tudja, hogy ki tette?}
{165}{}{Tudja, hogy mi történt?}
{166}{}{Kérdeznék valami mást.}
{167}{}{Majd én elrendezem. Számíthat rám. Viszlát!}
{168}{}{Nem tudom pontosan, hogy ki volt az, de amikor rátaláltunk, egy Morningstar-bányás fizetési jegy volt a kezében. Amúgy egy bányásszal volt utoljára.}
{169}{}{Láthatnám a lányt?}
{170}{}{Tudja, hogy mi történt?}
{171}{}{Egy Morningstar-bányás fizetési jegy? Az mi?}
{172}{}{Hadd kérdezzek valami mást.}
{173}{}{Majd én elrendezem. Számíthat rám. Viszlát!}
{174}{}{Szóval, valami sikoltozás hallatszott, aztán, mivel nem maradt abba, hát bementem a szobába. Mire odaértem, a tettes, az a gazember már meglépett és a lánykám pocsék állapotban volt. Így hát hívtam az orvost és a seriffet. A többit tudja.}
{175}{}{Tudja, hogy ki tette?}
{176}{}{Láthatnám a lányt?}
{177}{}{Kérdeznék valami mást.}
{178}{}{Majd én elrendezem. Számíthat rám. Viszlát!}
{179}{}{A város északi részén Dan McGrew mûködteti a Morningstar Bányát. A bányászokat általában mindkét bányában számlára fizetik vagy értékjeggyel... Hát a lánykámat egy ilyen fecnivel a kezében találták meg. Itt van, nézze meg maga is. (Átadja a jegyet.)}
{180}{}{Aha, értem. Láthatnám a lányt?}
{181}{}{Aha, értem. Tudja, hogy mi történt?}
{182}{}{Kérdeznék valami mást.}
{183}{}{Majd én elrendezem. Számíthat rám. Viszlát!}
{184}{}{Igazán örülök, hogy valaki foglalkozik vele. Az ilyen dolgok mindenkinek ártanak. Remélem, az a disznó megfizet azért, amit a lánykámmal tett. Tegyen róla, hogy soha többé senkivel ne tehesse meg újra!}
{185}{}{Meglátom, mit tehetek. Most kérdeznék még valamit.}
{186}{}{Meglátom, mit tehetek. Viszlát!}
{187}{}{Mit tehetek magáért? Egy üres ágyat akar vagy egy telit? Esetleg egy kis piát vagy más egyebet?}
{188}{}{Egy szobát szeretnék, Lou, üres ággyal.}
{189}{}{Teli ágy? Ez jól hangzik, mondjon errõl valamit!}
{190}{}{Pia és egyebek, igen, ezek mennek. Csereberéljünk!}
{191}{}{Ööö, kérdeznék valami mást.}
{192}{}{Ez minden vagy akar még venni valamit?}
{193}{}{Mintha kicsit nehezen tudná elhatározni magát. Ennyi vagy újra meg akarja nézni?}
{194}{}{Ennyi, ez minden, amire most szükségem volt. Kösz. Viszont kérdeznék még valamit.}
{195}{}{Hmm, hadd nézzem meg még egyszer a készletet.}
{196}{}{Köszönöm, Lou. Mára ennyi. Viszlát!}
{197}{}{Aludni szeretne, ugye? 40 dolcsiba kerül. Benne van a friss, nagyjából tiszta ágynemû is. Érdekli?}
{198}{}{Jöhet, Lou.}
{199}{}{Hmm, azt hiszem, ennyire nem vagyok fáradt. Kérdeznék valami mást.}
{200}{}{Most nincs ennyi pénzem. Viszont kérdeznék még valamit.}
{201}{}{Maga Fannie egyik törzsvendége, ugye? Miért nem beszél vele? Valahol hátul kell legyen.}
{202}{}{Figyeljen ide, maga rossz ómen itt. Azután, ami Fannie-val történt, egyik lányom sem vágyik rá, hogy magával legyen... és nem mondhatnám, hogy hibáztatom õket ezért.}
{203}{}{Kellene valaki, aki segít bemelegíteni azt a magányos, nagy ágyat, mi? Na, lássuk csak, ki szabad? Hmm, miért nem próbálja ki Fannie Mae-t? Itt kell legyen valahol. A részleteket megbeszélheti vele.}
{204}{}{Jó ötletnek hangzik, ezt fogom tenni. Viszlát!}
{205}{}{De én nem... na mindegy. Viszlát!}
{206}{}{Maga meg Fannie már összeszoktak. Miért nem keresi meg? Valahol ott kell lennie hátul.}
{207}{}{Figyeljen ide, maga rossz ómen itt. Azután, ami Fannie-val történt, egyik lányom sem vágyik rá, hogy magával legyen... és nem mondhatnám, hogy hibáztatom õket ezért.}
{208}{}{Itt csak lányok dolgoznak, szivi. Ha így is jó, egy dolcsi az egy dolcsi. Megpróbálhatja Fannie Mae-vel. Valahol hátul kell lennie. A részleteket megbeszélheti vele.}
{209}{}{Jó ötletnek hangzik, ezt fogom tenni. Viszlát!}
{210}{}{De én nem... na mindegy. Viszlát!}
{211}{}{Nem tudom elhinni, hogy volt olyan ostoba és egyszerre annyi pénzt adott Fannie-nak, amibõl túllõhette magát. Maga teljesen meggárgyult?}
{212}{}{Nem tudtam! Tényleg nem! Ugyan, Lou.. kérdeznem kell még valamit!}
{213}{}{Az õ dolga, hogy mit csinált az életével. Viszlát!}
{214}{}{Én adtam neki az egyetlen megoldást, ami ebbõl a szar létezésbõl megszabadíthatta õt. Maga sem egy szent Lou. Viszlát!}
{215}{}{Szóval maga az a balek, aki a pénzt adja az én Fannie-mnak. A maga helyében nem tenném. Ezzel nem úgy segít rajta, ahogy gondolja.}
{216}{}{Hogy érti ezt?}
{217}{}{Segítek neki új életet kezdeni.}
{218}{}{Jó-jó... Beszéljünk valami másról!}
{219}{}{Fannie problémájára nem a pénz a megoldás! Sajnálom, hogy össze kell törjem a szívét, de Fannie csak baleknek tartja magát. Csak azért kell neki a pénz, hogy Jetre költse. Átkozottul túl sok Jetre.}
{220}{}{Azt hiszem, maga csak amiatt aggódik, hogy elveszíti az egyik legjobb pénzforrását. Csak a lányait akarja megtartani.}
{221}{}{Ja, persze. Eleget hallottam, viszlát!}
{222}{}{A maga sok pénze csak a túlvilágra segíti õt. Csak arra kell neki a pénz, hogy egy rahedli Jetet vegyen belõle. Ha továbbra is pénzt ad neki, egy napon túllövi magát.}
{223}{}{Hmm, ez elgondolkodtató.}
{224}{}{Ezt át kell gondoljam. Viszlát!}
{225}{}{Gondolkodjon csak el! Én megpróbáltam elmondani, mi a tényleges helyzet. Maga dönt, hogy hallgat-e rám vagy sem.}
{226}{}{Ezt már hallottam. Térjünk át más témára!}
{227}{}{Köszönöm, átgondolom a hallottakat. Viszont kérdeznék még valamit.}
{228}{}{Ezt át kell még gondolnom. Viszlát!}
