# Dialog Editor last position: 1
{100}{}{Egy dundi, hivatalnok-szerû férfit látsz.}
{101}{}{Õ Nording, a pénztáros.}
{102}{}{Egy ideges, dundi, galambszerû férfit látsz.}
{103}{}{A karaván elhagyásáért nem jár pénz!}
{104}{}{Öö, néhány dolog hiányzik a karaván készletébõl. Az ÚKK törvényei nem engedik meg, hogy tolvajoknak fizessek. Sajnálom.}
{105}{}{Tolvajoknak? Kikérem magamnak, te hálátlan disznó! Na, én leléptem. Viszlát!}
{106}{}{Hamarosan megbánod, hogy ujjat húztál velem! Viszlát!}
{107}{}{Nem jutalmazhatlak meg egy ilyen katasztrófális karaván út után. Semmit nem kapsz tõlem!}
{108}{}{Te szemétláda! Megfizetsz, amiért bepaliztál! Viszlát!}
{109}{}{Néha az ember szerencsésebb másoknál. Ez most nem az a nap. Viszlát!}
{110}{}{Ez nagyon ráfizetéses karaván-út volt. 500 dollárnál nem tudok többet adni.}
{111}{}{Hát, azt hiszem, ez is több, mint a semmi. Viszlát!}
{112}{}{Te, tetves szemétláda! Senki sem csinálta volna jobban! Megbánod még, hogy átvertél. Viszlát!}
{113}{}{Végülis nem volt ez olyan rossz. Tessék, az 1500 dollárod. Nem tudom, mikor találunk megint egy karaván-vezetõt, de ha sikerül, megint dolgozhatsz nekünk.}
{114}{}{Nem hiszem, hogy valaha is szándékomban állna újra ennyi idõt tölteni egy brahmin hátsó felének nézegetésével. Viszlát!}
{115}{}{Végülis nem volt ez annyira rossz. Még találkozunk. Viszlát késõbb.}
{116}{}{Annak ellenére, hogy Stanwell eltûnt, jó út volt ez. Az emberrel néha történnek rossz dolgok is. Tessék, a 100 dollárod, plusz 50 dolcsi Stanwell részébõl.}
{117}{}{Mindig öröm számomra, ha olyan emberrel találkozom, aki tudja értékelni a minõségi munkát. Talán látjuk még egymást. Viszlát!}
{118}{}{Mindig jól jön egy kis plusz pénz. Kösz, és viszlát!}
{119}{}{Ha az ÚKK-ban élnél, lehetne egy kellemes szobácskád, és nem volna muszáj a világot járnod. Mi legalább lehetõvé tettük, hogy biztonságban utazhass. Viszlát!}
{120}{}{Ook?}
{121}{}{A fene egye meg, hogy Stanwell kinyírta magát! A nevem Nording, és én fogom rendezni az adósságot.}
{122}{}{Öö, kösz.}
