# Dialog Editor last position: 1
{100}{}{Egy mézes-mázos, kereskedõ-féle embert látsz.}
{101}{}{Õ Velani, Mordinóék kereskedõje.}
{102}{}{Egy nyájas, szépen manikûrözött férfit látsz.}
{103}{}{Szánalmas vagy! Ha izmosabb lennék, nem úsznád meg ennyivel egy másik karaván elhagyását. Na, mindegy, tûnj innen!}
{104}{}{Nagy hibát követtél el azzal, hogy megloptad a Mordino családot. Megfizetsz még ezért - kamatostul! Most pedig, tûnj a szemem elõl!}
{105}{}{Tolvaj? Kikérem magamnak, te hálátlan dög! Most pedig távozom. Viszlát!}
{200}{}{Miért nem intézzük el azonnal? Készülj a halálra, seggfej!}
{106}{}{Hamarosan megbánod, hogy ujjat húztál velem! Viszlát!}
{107}{}{Ez a karaván-út gyalázatos volt! Örülök, hogy Savinelli nem élte túl. Nem hiszem el, hogy szerinted még fizetni is fogunk ezért a kudarcért! Tûnj innen!}
{108}{}{Te szemétláda! Megfizetsz azért, hogy bepaliztál! Viszlát!}
{109}{}{Néha az ember szerencsésebb másoknál. Ez most nem az a nap. Viszlát!}
{110}{}{Fél seggel ülted meg a lovat! Ez nagyon nem játszik nálunk, ezért csak a felét fizetem a neked járó pénznek. Tessék, az 500 dollárod. Most pedig tûnés innen!}
{111}{}{Hát, azt hiszem, ez is több, mint a semmi. Viszlát!}
{112}{}{Te tetves szemétláda! Senki sem csinálta volna jobban! Megbánod még, hogy átvertél! Viszlát!}
{113}{}{Nos, a karaván zöme célhoz ért, még ha Savinelli nem is. Tessék, az 1500 dollárod. Nem tudom, mikor találunk megint valakit a karaván-vezetõ állásra.}
{114}{}{Nem hiszem, hogy valaha is szándékomban állna újra ennyi idõt tölteni egy brahmin hátsó felének nézegetésével. Viszlát!}
{115}{}{Végülis nem volt ez annyira rossz. Viszlát késõbb.}
{116}{}{Jó út volt. Elveheted Savinelli részét, neki úgy sem lesz már szüksége rá. Tessék, 150 dolcsi. Nem tudom, mikor találunk megint valakit, hogy vezesse ezt a francos karavánt, de ha sikerül, megint melózhatsz nálunk, ha akarsz!}
{117}{}{Mindig öröm számomra, ha olyan emberrel találkozom, aki tudja értékelni a minõségi munkát. Talán látjuk még egymást. Viszlát!}
{118}{}{Mindig jól jön egy kis zsebpénz. Kösz, és viszlát!}
{119}{}{Savinelli még azelõtt elveszítette a farmját, hogy megvehette volna. Egyébként nem tudom, miért hagyta, hogy egy hozzádhasonló kolonc vele menjen. Tûnj innen!}
{120}{}{Ook?}
{121}{}{Savinellit kinyírták. A francba, még most sem tudom elhinni. Velani vagyok. Én fogom rendezni az tartozásunkat.}
{122}{}{Öö, köszi.}
