# Dialog Editor last position: 11
{100}{}{Egy harci páncélt viselõ zsoldos.}
{101}{}{Egy õrt látsz.}
{102}{}{Úgy áll itt, mintha várna valamire.}
{103}{}{Hát persze. Mozgás!}
{104}{}{Légy kedves Mr. Busterhez, akkor egyikõnknek sem kell elpazarolni a drága skulót.}
{105}{}{Azért vagyok itt, hogy öljek meg rágózzak. Szerencsédre még van nálam egy rágó.}
{106}{}{Mi a faszt bámulsz? Tûnés a picsába!}
{107}{}{Tartsd a távolságot!}
{108}{}{Ez az, gyere a papához! Mit szólnál egy italhoz késõbb?}
{109}{}{Drágaságom, szívesebben hetyegnék egy brahminnal, mint veled.}
{110}{}{Vedd meg, amit akarsz, aztán tûnés a francba!}
