# Dialog Editor last position: 50
{100}{}{Egy alacsony emberkét látsz. Testét itt-ott zsírfoltok borítják. }
{101}{}{Ez itt Buster, a fegyver-sefter.}
{102}{}{A fickó rongyos ruhát visel, a testét mindenütt fegyverlövések nyomai borítják. Mindemellett egész vidámnak tûnik.}
{103}{}{Légy üdvözölve Buster Kóser Hadi Lerakatában! Jómagam lennék Buster. A smukk a polcokon van, nézz csak körül, és szólj, ha érdekel valami!}
{104}{}{Hali, újra nálunk? Mit tehetek érted?}
{105}{}{Másvalamit?}
{106}{}{Fegyver kõ.}
{107}{}{Mid van?}
{108}{}{Fel tudnád turbózni valamelyik fegyverem?}
{109}{}{Lenne néhány kérdésem.}
{110}{}{Viszlát!}
{111}{}{Jól választottál!}
{112}{}{Nahát, nahát, lopkodjuk az árut?}
{113}{}{Nem akarlak siettetni, de más dolgom is lenne.}
{114}{}{Persze idegen, mit szeretnél tudni?}
{115}{}{Beszélj nekem az ÚKK-ról.}
{116}{}{Ismered Merket?}
{117}{}{Mit tudsz Frank Westinrõl?}
{118}{}{Az öreg Carlsonnal kellene találkoznom. Nem tudsz valakit, aki ismeri?}
{119}{}{Nincs egy ÉLETED?}
{120}{}{Ez mind szép és jó, de én nem vagyok információs iroda.}
{121}{}{Talán. Akad itt egy Triveld 10x puskatávcsõ - tökéletesen ráillik egy vadászpuskára, csak eddig nem akadt rá vevõ. Olcsón adom, 500 dolcsiért.}
{122}{}{Hé, már kitisztítottál haver.}
{123}{}{Áll az alku.}
{124}{}{Nem, kösz.}
{125}{}{Ez itt az Új Kalifornia Köztársaság. Tandi elnöknõ és a társai azt mondják, hogy a régi idõket szeretnék újra visszahozni. Szerintem csak harácsolni akarnak. A fenébe is, nem fogok én panaszkodni! Meg sem születtem még akkor. Érdekes egy gárda egyébként. Nem szeretik a rabszolgákat, a szerencsejátékot meg a hasonlókat. Ezért telepedtem le a városon kívül. Nem csípem, ha szabályok kötik a kezem. Sosem csíptem.}
{126}{}{Értem.}
{127}{}{Viszlát!}
{128}{}{Nem akarok Mr. Merk ügyeibe belekeveredni és amúgy sem kifizetõdõ pletykákat elhinteni róla. Ha kérdésed van, beszélj vele magad a Rawhide-ban.}
{129}{}{Értem.}
{130}{}{Viszlát!}
{131}{}{Van egy kisebb birtoka a város nyugati részén. Brahminokkal foglalkozik. Õ a fõ mozgatórugó a Marhatenyésztõk Szervezetében. Nála mindig akad munka, ha esetleg pénzre lenne szükséged.}
{132}{}{Értem.}
{133}{}{Viszlát!}
{134}{}{Meglepõ, hogy ezt kérdezed azok után, ami Frank Westinnel történt. Nem én mondtam, de van egy fószer, Merk, lenn a Rawhide-ban, aki talán segíthet.}
{135}{}{Értem.}
{136}{}{Viszlát}
{137}{}{Az olyan békebeli cucc? Hadd találjam ki, 14mm-es lõszer? Nem, olyanom nincs.}
{138}{}{Értem.}
{139}{}{Viszlát!}
{140}{}{Nézd, ez csak vadászpuskára megy rá, ilyen a kialakítása, érted?}
{141}{}{Értem.}
{142}{}{Viszlát!}
{143}{}{Bezárt a bazár. Tûnés!}
{144}{}{Az istenit! Lennél szíves emberi idõben jönni?}
{145}{}{Gyere vissza, ha nyitva leszek, és ne felejtsd el behúzni a sátrat magad után.}
{146}{}{Zárva vagyok.}
{147}{}{Nézd, ha nem tûnsz el, dühös lesz a pisztolyom!}
{148}{}{Ezt nem kellett volna, idegen!}
{149}{}{Válogass csak nyugodtan! Ha esetleg más is kell, nézd meg a többi polcot is.}
