# Dialog Editor last position: 2
{100}{}{Egy újabb õr. Bizonyára tenyésztik õket, mert mindegyik tökugyanúgy néz ki.}
{101}{}{Ismét egy ellenszenves õr.}
{102}{}{Közelebbrõl is megszemléled, és meg vagy gyõzõdve róla, hogy ez egy õr.}
{103}{}{Nincs engedélye itt tartózkodni.}
{104}{}{Láthatnám a belépõjét?}
{105}{}{Ez a terület kormányfennhatóság alatt áll. Menjen tovább!}
{106}{}{Magáról beszélt Merk? Oké, engedjétek be, fiúk!}
{107}{}{Menjetek arrébb fiúk!}
{108}{}{Oké, tiszta. Nyissátok ki a kaput fiúk!}
{109}{}{Magáról beszélt Merk? Oké, engedjétek be, fiúk!}
{110}{}{Szolgálatban vagyok. Nincs idõm trécselésre.}
{111}{}{Tetszik a cipõje.}
{112}{}{Foglalkozzon a maga dolgával!}
