{100}{}{Egy id?sebb személyt látsz. Barátságosnak t?nik.}
{101}{}{Ez itt Jubilee doktor.}
{102}{}{Elég koros ember, hófehér szakálla van, és kissé üres a tekintete.}
{103}{}{Jubilee doktor vagyok. Mi a problémája, fiatalember?}
{104}{}{Mi a problémája, fiatalember?}
{105}{}{Én sebesült.}
{106}{}{Orvosra van szükségem.}
{107}{}{Elbújhat ezzel a kis karcolással. Inkább szedjen be valamilyen tablettát, engem meg hagyjon békén!}
{108}{}{Úristen, maga súlyosan vérzik!}
{109}{}{Nem is tudom. Nem hinném, hogy meg tudom menteni a lábát. A legjobb lenne levágni.}
{110}{}{Ugye csak viccel?}
{111}{}{Haha.}
{112}{}{Itt van hát, fiam!}
{113}{}{Újra találkozunk?}
{114}{}{Kösz doki. Válaszolhatna pár kérdésre.}
{115}{}{Viszlát!}
{116}{}{50 dollár lesz.}
{117}{}{Csak gyógyítson meg!}
{118}{}{Nem maradok itt!}
{119}{}{Maga jobban csinálja.}
{120}{}{Én menni mostan.}
{121}{}{Nem. Én sosem hazudok. El fog üszkösödni, ha nem vágom le.}
{122}{}{No way you're cutting anything off, understand?}
{123}{}{Ennyi lett volna, megyek is.}
{124}{}{Ha elüszkösödik, ne engem hibáztasson!}
{125}{}{Ez nem jótékonysági kórház. Ha nincs pénz, nem dolgozom.}
{126}{}{Mit tehetek magáért?}
{127}{}{Ne kíméljen!}
{128}{}{13-as Menedék?}
{129}{}{Tudja, hol találom a 13-as Menedéket?}
{130}{}{I heard somebody saying Mr. Westin's not well. That true? I'm worried something might happen to him. He owes me money.}
{131}{}{Sóshús azt mondta, maga ellopott t?le egy térképet. Igaz ez?}
{132}{}{Munkát keresek. Tudna segíteni?}
{133}{}{Doki, tud valamit egy bizonyos csoportról, akik a rabszolga-keresked?k ellen harcolnak?}
{134}{}{Nem kell aggódnia, fiam! Ha nem terheli túl a szervezetét, talán tovább eléldegél bármelyik?nknél. Feltéve, ha nem felejti el bevenni a gyógyszereit.}
{135}{}{Ennek örülök. Érdekelne még valami.}
{136}{}{Kösz, doki.}
{137}{}{Az a részeg disznó! Egyetlen dolgot szereztem t?le, egy "Velvet Elvii" festményt... természetesen pénz ellenében.}
{138}{}{Velvet Elvii? Láthatnám esetleg?}
{139}{}{Hát ez nem éppen térkép. Na, hadd noszogassam egy kicsit más témában!}
{140}{}{Sajna mennem kell.}
{141}{}{Ezt még senki sem említette, mióta az öreg Sóshúst idehozták. Három napig lázas volt, egész id? alatt arról mormolt, hogyan találta meg a 13-as Menedéket.}
{142}{}{Sóshús?}
{143}{}{Szóval hol is van?}
{144}{}{Hun lenni menedék?}
{145}{}{Nem tudom. Sóshús mindig mondta, hogy van róla térképe, de még sohasem látta senki.}
{146}{}{Sóshús?}
{147}{}{Kérdezni még.}
{148}{}{Ez is több, mint a semmi...}
{149}{}{Sóshús egy öreg földmér? - jobban mondva - egy részeg disznó. Westin birtokán él.}
{150}{}{Lenne még valami...}
{151}{}{Kösz a történetet.}
{152}{}{Hát, reméltem, hogy nem ingyen válok meg t?le. Legyen az ára }
{153}{}{Talán kés?bb, de még valami érdekelne...}
{154}{}{Talán kés?bb, de most mennem kell.}
{155}{}{Sóshús egy öreg földmér? - jobban mondva - egy részeg disznó. Westin birtokán él.}
{156}{}{Lenne még valami...}
{157}{}{Kösz a történetet.}
{158}{}{A legjobb lesz, ha beszél Tandival, az elnökkel. Hallottam, hogy valamiféle különleges embert keres.}
{159}{}{Lenne még valami...}
{160}{}{Köszi.}
{161}{}{Meglehet... Tudok egy csoportról, akik a rabszolga-keresked?k ellen küzdenek. Mindig ott lézengenek annál a nagy m?helynél... egy autó javításán munkálkodnak.}
{162}{}{Lenne még valami...}
{163}{}{Köszi.}
{164}{}{El a kezekkel, punk!}
{165}{}{Careful there! Just takes tiny amount to expose yourself.}
{166}{}{Tedd azt vissza! Nem gyerekjáték!}
{167}{}{Azok Mr. Westin gyógyszerei, ne nyúlj hozzájuk!}
{168}{}{Ne piszkáld azokat! Nem szeretném, ha Mr. Westin tévedésb?l a rossz gyógyszereket kapná.}
{169}{}{Ne piszkáld! Épp most mértem ki Mr. Westin adagját.}
{170}{}{Jubilee doktor vagyok. Mi a probléma, szép hölgy?}
{171}{}{Mi a probléma, szép hölgy?}
{172}{}{Hát újra itt van, hölgyem?!}
{173}{}{Nem kell aggódnia, hölgyem! Ha nem terheli túl a szervezetét, bizonyára tovább eléldegél, mint bármelyik?nk. Feltéve, ha nem felejti el bevenni a gyógyszereit.}
{174}{}{Rendben. Itt van a jussa, }
{175}{}{Kösz. Próbáltam már Sóshústól némi pénzt kicsikarni, de annak a részeg disznónak mindig üres volt a zsebe.}
{176}{}{ vagyok.}
