# Dialog Editor last position: 32
{100}{}{Egy vörös arcú, barátságos embert látsz.}
{101}{}{Õ Duppo, a Marhatenyésztõk Szövetségének elnöke.}
{102}{}{Egy köpcös kis emberke, állandóan kipirult arccal, és kócos, vékony, szõke hajjal. Járás közben enyhén sántít.}
{103}{}{Üdvözöllek, idegen! Nem vagy ismerõs a környékrõl, tehát nem vagy marhatenyésztõ. Munkát keresel, vagy vásárolni akarsz valamit?}
{104}{}{Mi lenne az, idegen?}
{105}{}{Munka kell.}
{106}{}{Vásárolnék.}
#az a baj, hogy a sporolos kocsogok ugyanezt raktak a low iqra is (bass) 105-106

{107}{}{A nevem Duppo. Termelõeszközök árusítása, munkaerõ toborzás, mind egy helyen. Meg kell, hogy mondjam, nem nézel ki brahmin-terelõnek. Hogy állsz a fegyverekkel?}
{108}{}{Mindig keresek néhány õrt, ha érdekel a dolog. Hogy hangzik?}
{109}{}{Heh. Öl.}
{110}{}{Elég jól.}
{111}{}{Nem kenyerem az erõszak.}
{112}{}{Itt van az árum. Nézd át a készletet a többi asztalon is. Ha nem tetszik a cucc, told át a segged ahhoz a zugprókátor Busterhez! Persze õ még a szemedet is ki fogja lopni.}
{113}{}{A fizetség 2000 dollár, mínusz a beérkezésed elõtt gallyra tett áru értéke. Ha érdekel a dolog, legyél holnap Westin birtoka elõtt a kapunál. Ha nem jössz, nem mész. Megegyeztünk?}
{114}{}{Én jön.}
{115}{}{Nem szeretni. Én nem csinájja.}
{116}{}{Jól hangzik.}
{117}{}{Nem akarok én Reddingbe menni...}
{118}{}{Akkor itt nincs számodra munka. A vidék kemény hely. Puhányokra nincs szükségünk, idegen.}
{119}{}{Valami más?}
{120}{}{Remek. Valami mást, idegen?}
{121}{}{Vásárolnék.}
{122}{}{Munkát keresek.}
{123}{}{Wes-tin?}
{124}{}{Roger Westint keresem. Hallottál már róla?}
{125}{}{Hol találom Frank Carlsont?}
{126}{}{Carl-son?}
{127}{}{Viszlát!}
{128}{}{Roger Westinre gondolsz? A város nyugati részén?}
{129}{}{Õ a marhatenyésztõk egyike, a város nyugati részén lakik. Nem hinném, hogy munkásokat keresne a farmjára, ha esetleg ez járna az eszedben.}
{130}{}{Õ az alelnök, ennyit tudok. Ezenkívûl tényleg nem tudok mondani semmit. Minden idejét az Elnöki Rezidencián tölti. Ritkán jön ki, pláne most, amikor ilyen balhéban vagyunk.}
{131}{}{Carlson. Nagy fõnök. Nagy házban lakik. Ez minden.}
{132}{}{Sajnálom... vége van a csordaterelõ szezonnak. Gyere vissza néhány hónap múlva!}
{133}{}{Szódával elmegy... Van valami más mód gyors pénzszerzésre a városban?}
{134}{}{Akad ilyesmi. Mondjuk olyan lehetõség, amirõl a hivatalos szerveknek sem kéne tudni.}
{135}{}{Nos, fizetnék valamennyit az információért cserébe.}
{136}{}{Hmm, mennyit áldoznál a nemes célra?}
{137}{}{Mit szólsz 500-hoz?}
{138}{}{Mit szólsz 300-hoz?}
{139}{}{Mit szólsz 200-hoz?}
{140}{}{Mit szólsz 100-hoz?}
{141}{}{Hát, nem tõlem hallottad, de a hátsó ajtóhoz a jelszó BANDA - PROBLÉMA - VÉGTAG.}
{142}{}{Hmm... Ez nem hangzik valami érdekfeszítõen.}
{143}{}{Hmmm.. Ne feledkezz meg a 10 gyermekemrõl!}
{144}{}{Hmmm.. A feleségem új bundát akar!}
{145}{}{Hmmm.. Többet kell hozzáadnod.}
{146}{}{Ah, kicsit kiköltekeztünk mostanában?}
{147}{}{Meghiszem azt!}
{148}{}{Gyerünk már, ne legyél smucig!}
{149}{}{Kezdesz bemelegedni!}
{150}{}{Több ösztönzésre van szükségem!}
{151}{}{Gyorsan, még mielõtt meglátja valaki!}
{152}{}{Biztos, hogy semmi közöd a törvényhez?}
{153}{}{Nézd, már majdnem ott vagy, csak ne állj meg!}
{154}{}{Rendben, csak még egy kicsit, jó?}
{155}{}{Legyél holnap Westin birtoka elõtt a kapunál. Ha nem jössz, nem mész, megértetted?}
