{100}{}{Egy nagyon csinos, harci páncélba bújt fiatal lányt látsz.}
{101}{}{Ő Elise.}
{102}{}{Egyfajta "semmi-sem-lehetetlen" aura lengi körül, mintha hozzászokott volna, hogy utasításokat ad másoknak, azok pedig engedelmeskednek neki.}
{103}{}{Mit akar?}
{104}{}{Már megint maga az?}
{105}{}{Karl küldött.}
{106}{}{Jubilee doki említette, hogy beszélnem kellene veled.}
{107}{}{Ki vagy?}
{108}{}{Göh?}
{109}{}{Egy szervezetet keresek. Gyűlölik a rabszolgaságot. Új Kalifornia Felderítőinek hívják magukat.}
{110}{}{Meg tudnád javítani a kocsimat?}
{111}{}{Bocs... már azt hittem, nincs gazdája ennek a helynek.}
{112}{}{Valóban? Mit mondott neked?}
{113}{}{Nem sokat. Csak annyit, hogy jó fejek vagytok és, hogy bizonyára jól kijönnénk egymással.}
{114}{}{Azt mondta, jó pénzt fizetsz.}
{115}{}{Én Elise vagyok, ő pedig Gond. Egy "csoporthoz" tartozunk, megpróbálunk az emberek javára tenni.}
{116}{}{Nem úgy néztek ki, mint egy segélyegylet vagy egy templom.}
{117}{}{Érdekesnek hangzik. Milyen módon teszitek ezt?}
{118}{}{Én csak a kocsimat akarom megjavíttatni.}
{119}{}{Just get yourself out of here. Saloon's back on Main Street.}
{120}{}{Gyűlölik a rabszolgaságot, hűha! Ez érdekes. Mit csinálnál, ha megtalálnád ezt a csoportot?}
{121}{}{Megkérném, hogy csatlakozhassak hozzájuk.}
{122}{}{Szétrúgnám a seggüket.}
{123}{}{Semmi.}
{124}{}{Semmi közöd hozzá. Na, kifelé!}
{125}{}{Már kiszálltunk az autóüzletből. Átmenetileg zárva tartunk. Viszlát!}
{126}{}{Amint látod, van. Viszlát!}
{127}{}{Rendben, akkor mondd meg nekem, mi a véleményed a rabszolga-kereskedőkről?}
{128}{}{Gyűlölöm őket. Undorító, aljas söpredék.}
{129}{}{Ha békén hagynak, békén hagyom őket.}
{130}{}{Néhány rabszolga-hajcsárt a legjobb barátomnak tudhatok.}
{131}{}{Csak a pénz érdekel?}
{132}{}{Természetesen nem. Hiszek az igazságban, a jogban és az elnyomottakért vívott harcban.}
{133}{}{Kezdetnek megteszi... amíg valaki nem hozakodik elő egy nemesebb céllal.}
{134}{}{Mi egyéb van még itt?}
{135}{}{Ne nézz hülyének! Tudom, miféle alak vagy te. Na, minden jót!}
{136}{}{Ha nem tudod, akkor csak vesztegeted az időmet. Viszlát!}
{137}{}{Neem, mi nem vallási szervezet vagyunk. Nem bánod, ha megkérdezek valamit?}
{138}{}{Nem, kérdezz csak!}
{139}{}{Ne olyan hevesen! Hogy csatlakozhass a Felderítőkhöz, át kell menned egy teszten.}
{140}{}{Rendben, mondd csak!}
{141}{}{Teszten? Mi ez, iskola?}
{142}{}{Egy rabszolga-kereskedő a város határában rontja a levegőt. Talán láttad is a helyet. Szabadítsd ki a rabszolgákat, aztán gyere vissza és tárgyalhatunk!}
{143}{}{Ezt meg tudom csinálni!}
{144}{}{No way. I don't want to make any trouble here.}
{145}{}{Hát, szerencsés napod van.}
{146}{}{Elsősorban ez a hozzáállás teszi lehetővé, hogy a rabszolgaság embertelensége még létezhet. Sajnálom, de a számodra nincs hely a szervezetünkben.}
{147}{}{Oké.}
{148}{}{Nos, meggondoltad magad? Kész vagy kiállni a próbát?}
{149}{}{Persze.}
{150}{}{Mit is akartál tőlem?}
{151}{}{Nem kellett volna elintézned valamit? Amíg nem végeztél a feladattal, ne gyere vissza!}
{152}{}{Már hallottam a híreket a rabszolgák kiszabadításáról. Szép munka volt! Nos, készen állsz, hogy te is Felderítő legyél?}
{153}{}{Igen.}
{154}{}{Nem.}
{155}{}{Hallottam, hogy te szabadítottad ki a rabszolgákat a városon kívül. Tisztességes dolog volt és meg szeretném érte szorítani a kezed.}
{156}{}{Kösz.}
{157}{}{Egyszerű. Mi úgy tartjuk, hogy a rabszolgaság rossz dolog és mindent megteszünk ellene, amit szükségesnek látunk. Itt, az ÚKK-ban sok, magas beosztású barátunk van. Nekik köszönhetően délre tőlünk már betiltottuk a rabszolgaságot, és reményeink szerint északon is elterjeszthetjük a nézeteinket.}
{158}{}{Büszke lennék, ha tagja lehetnék a Felderítők szervezetének. Írj csak fel nyugodtan!}
{159}{}{Érdekes... Át kell még gondolnom, amit mondtál.}
{160}{}{Megesküszöl, hogy harcolsz a rabszolgaság ellen, ahol csak lehetőséged nyílik rá és segítesz Felderítő társaidon, amikor csak szükségük van rá?}
{161}{}{Igen.}
{162}{}{Nem.}
{163}{}{Gratulálok, mostantól Felderítő vagy.}
{164}{}{Jól van, Felderítő társam. Attól tartok, mostanság nincs túl sok tennivaló errefelé. A legtöbb emberünk őrjáratozik. Elhintem majd, hogy mostantól te is közénk tartozol. Nem akarom, hogy valamelyikük véletlenül golyót eresszen beléd.}
{165}{}{Nos, a mi ajtónk mindig tárva-nyitva áll a jó emberek előtt, hogy csatlakozzanak az ügyünkhöz. Ha meggondolod magad, keress fel! Biztos, hogy nem akarod megragadni az alkalmat a csatlakozásra?}
{166}{}{Biztos vagyok benne.}
{167}{}{Hát, most, hogy így mondod, mégis beállnék Felderítőnek.}
{168}{}{Értem. Én egy csoportot képviselek, a nevünk Új Kalifornia Felderítői. A hozzád hasonló gondolkodású embereket szívesen a tagjaink közé fogadjuk. Érdekelne a dolog?}
{169}{}{Nagyszerű! Írj csak fel nyugodtan!}
{170}{}{Érdekesen hangzik. Mit tudsz mondani nekem a Felderítőkről?}
{171}{}{Értem. Hát, kösz, hogy beugrottál, de nem tudom, mit is mondhatnánk még egymásnak. Ha meggondolod magad, gyere vissza hozzánk!}
{172}{}{Oké.}
{173}{}{Ebben az esetben meg kell kérjelek, hogy tűnj a szemem elől. Ne mondjam még egyszer!}
{174}{}{Oké.}
{175}{}{Egy rabszolga-hajcsár! Kifelé innen, mielőtt egy golyóval szedem le azt a tetkót rólad!}
{176}{}{Persze.}
{177}{}{Próbáld csak meg!}
{178}{}{Néhány északi városban vannak ügynökeink és szimpatizánsaink. Terjesztjük a nézeteinket és ott csapunk le a rabszolga-kereskedőkre, ahol csak tudunk.}
{179}{}{Üdv! Meggondoltad magad a csatlakozással kapcsolatban?}
{180}{}{Rá se ránts!}
{181}{}{Ez nem tartozik rád. Most távozz, különben begorombulok!}
{182}{}{Nem tudom, mit tettél Gonddal, de most megfizetsz!}
