{100}{}{Egy nagyon csinos, harci páncélba bújt fiatal lányt látsz.}
{101}{}{? Elise.}
{102}{}{Egyfajta "semmi-sem-lehetetlen" aura lengi körül, mintha hozzászokott volna, hogy utasításokat ad másoknak, azok pedig engedelmeskednek neki.}
{103}{}{Mit akarsz?}
{104}{}{Már megint maga az?}
{105}{}{Karl küldött.}
{106}{}{Jubilee doki említette, hogy beszélnem kellene veled.}
{107}{}{Ki vagy te?}
{108}{}{Göh?}
{109}{}{Egy szervezetet keresek. Gy?lölik a rabszolgaságot. Új Kalifornia Felderít?inek hívják magukat.}
{110}{}{Meg tudnád javítani a kocsimat?}
{111}{}{Bocs... már azt hittem, nincs gazdája ennek a helynek.}
{112}{}{Valóban? Mit mondott neked?}
{113}{}{Nem sokat. Csak annyit, hogy jó fejek vagytok és, hogy bizonyára jól kijönnénk egymással.}
{114}{}{Azt mondta, jó pénzt fizetsz.}
{115}{}{Én Elise vagyok, ? pedig Gond. Egy "csoporthoz" tartozunk, megpróbálunk az emberek javára tenni.}
{116}{}{Nem úgy néztek ki, mint egy segélyegylet vagy egy templom.}
{117}{}{Érdekesnek hangzik. Milyen módon teszitek ezt?}
{118}{}{Én csak a kocsimat akarom megjavíttatni.}
{119}{}{Just get yourself out of here. Saloon's back on Main Street.}
{120}{}{Gy?lölik a rabszolgaságot, h?ha! Ez érdekes. Mit csinálnál, ha megtalálnád ezt a csoportot?}
{121}{}{Megkérném, hogy csatlakozhassak hozzájuk.}
{122}{}{Szétrúgnám a seggüket.}
{123}{}{Semmi.}
{124}{}{Semmi közöd hozzá. Na, kifelé!}
{125}{}{Már kiszálltunk az autóüzletb?l. Átmenetileg zárva tartunk. Viszlát!}
{126}{}{Amint látod, van. Viszlát!}
{127}{}{Rendben, akkor mondd meg nekem, mi a véleményed a rabszolga-keresked?kr?l?}
{128}{}{Gy?lölöm ?ket. Undorító, aljas söpredék.}
{129}{}{Ha békén hagynak, békén hagyom ?ket.}
{130}{}{Néhány rabszolga-hajcsárt a legjobb barátomnak tudhatok.}
{131}{}{Csak a pénz érdekel?}
{132}{}{Természetesen nem. Hiszek az igazságban, a jogban és az elnyomottakért vívott harcban.}
{133}{}{Kezdetnek megteszi... amíg valaki nem hozakodik el? egy nemesebb céllal.}
{134}{}{Mi egyéb van még itt?}
{135}{}{Ne nézz hülyének! Tudom, miféle alak vagy te. Na, minden jót!}
{136}{}{Ha nem tudod, akkor csak vesztegeted az id?met. Viszlát!}
{137}{}{Neem, mi nem vallási szervezet vagyunk. Nem bánod, ha megkérdezek valamit?}
{138}{}{Nem, kérdezz csak!}
{139}{}{Ne olyan hevesen! Hogy csatlakozhass a Felderít?khöz, át kell menned egy teszten.}
{140}{}{Rendben, mondd csak!}
{141}{}{Teszten? Mi ez, iskola?}
{142}{}{Egy rabszolga-keresked? a város határában rontja a leveg?t. Talán láttad is a helyet. Szabadítsd ki a rabszolgákat, aztán gyere vissza és tárgyalhatunk!}
{143}{}{Nem látom akadályát...}
{144}{}{No way. I don't want to make any trouble here.}
{145}{}{Hát, szerencsés napod van.}
{146}{}{Els?sorban ez a hozzáállás teszi lehet?vé, hogy a rabszolgaság embertelensége még létezhet. Sajnálom, de a számodra nincs hely a szervezetünkben.}
{147}{}{Oké.}
{148}{}{Nos, meggondoltad magad? Kész vagy kiállni a próbát?}
{149}{}{Hogyne.}
{150}{}{Mit is akartál t?lem?}
{151}{}{Nem kellett volna elintézned valamit? Amíg nem végeztél a feladattal, ne gyere vissza!}
{152}{}{Már hallottam a híreket a rabszolgák kiszabadításáról. Szép munka volt! Nos, készen állsz, hogy te is Felderít? legyél?}
{153}{}{Igen.}
{154}{}{Nem.}
{155}{}{Hallottam, hogy te szabadítottad ki a rabszolgákat a városon kívül. Tisztességes dolog volt és meg szeretném érte szorítani a kezed.}
{156}{}{Köszi.}
{157}{}{Egyszer?. Mi úgy tartjuk, hogy a rabszolgaság rossz dolog és mindent megteszünk ellene, amit szükségesnek látunk. Itt, az ÚKK-ban sok, magas beosztású barátunk van. Nekik köszönhet?en délre t?lünk már betiltottuk a rabszolgaságot, és reményeink szerint északon is elterjeszthetjük a nézeteinket.}
{158}{}{Büszke lennék, ha tagja lehetnék a Felderít?k szervezetének. Írj csak fel nyugodtan!}
{159}{}{Érdekes... Át kell még gondolnom, amit mondtál.}
{160}{}{Megesküszöl, hogy harcolsz a rabszolgaság ellen, ahol csak lehet?séged nyílik rá és segítesz Felderít? társaidon, amikor csak szükségük van rá?}
{161}{}{Igen.}
{162}{}{Nem.}
{163}{}{Gratulálok, mostantól Felderít? vagy.}
{164}{}{Jól van, Felderít? társam. Attól tartok, mostanság nincs túl sok tennivaló errefelé. A legtöbb emberünk ?rjáratozik. Elhintem majd, hogy mostantól te is közénk tartozol. Nem akarom, hogy valamelyikük véletlenül golyót eresszen beléd.}
{165}{}{Nos, a mi ajtónk mindig tárva-nyitva áll a jó emberek el?tt, hogy csatlakozzanak az ügyünkhöz. Ha meggondolod magad, keress fel! Biztos, hogy nem akarod megragadni az alkalmat a csatlakozásra?}
{166}{}{Biztos vagyok benne.}
{167}{}{Hát, most, hogy így mondod, mégis beállnék Felderít?nek.}
{168}{}{Értem. Én egy csoportot képviselek, a nevünk Új Kalifornia Felderít?i. A hozzád hasonló gondolkodású embereket szívesen a tagjaink közé fogadjuk. Érdekelne a dolog?}
{169}{}{Nagyszer?! Írj csak fel nyugodtan!}
{170}{}{Érdekesen hangzik. Mit tudsz mondani nekem a Felderít?kr?l?}
{171}{}{Értem. Hát, kösz, hogy beugrottál, de nem tudom, mit is mondhatnánk még egymásnak. Ha meggondolod magad, gyere vissza hozzánk!}
{172}{}{Oké.}
{173}{}{Ebben az esetben meg kell kérjelek, hogy t?nj a szemem el?l. Ne mondjam még egyszer!}
{174}{}{Oké.}
{175}{}{Egy rabszolga-hajcsár! Kifelé innen, miel?tt egy golyóval szedem le azt a tetkót rólad!}
{176}{}{Hogyne.}
{177}{}{Próbáld csak meg!}
{178}{}{Néhány északi városban vannak ügynökeink és szimpatizánsaink. Terjesztjük a nézeteinket és ott csapunk le a rabszolga-keresked?kre, ahol csak tudunk.}
{179}{}{Üdv! Meggondoltad magad a csatlakozással kapcsolatban?}
{180}{}{Értem.}
{181}{}{Ez nem tartozik rád. Most távozz, különben begorombulok!}
{182}{}{Nem tudom, mit tettél Gonddal, de most megfizetsz!}
