{100}{}{Ez egy kövérkés fickó, fényes, kopasz fejjel, és vastag üvegû szemüveggel.}
{101}{}{Õ Dr. Henry}
{102}{}{Ez a fickó annyira nincs képben, hogy az már fáj. Igazi tojásfej, nem a való világban él, annyi szent.}
{103}{}{Bocsásson meg, Dr. Henry vagyok és nagyon elfoglalt. Mit akar?}
{104}{}{Már megint maga az? Mit akar?}
{105}{}{Hörgh.}
{106}{}{}
{107}{}{Elég a dumcsizásból! Van magánál egy-két papír, amikre Mr. Merknek fáj a foga. Adja át õket, és senkinek nem esik bántódása!}
{108}{}{Hallott valaha egy Enklávénak nevezett helyrõl?}
{109}{}{Nem a maga dolga...}
{110}{}{Hmm, visszamaradott cranium-fejlõdés... eltompult intellektuális fejlettség. Nem jelentõs testi mutáció... Nem, egyszerûen maga nem alkalmas, attól tartok. Minden jót!}
{111}{}{Kiválasztott? Természetesen ez figyelemreméltó. Érdekes... Attól tartok azonban, nem segíthetek. Engem kibergenetikai kutatásokra jelöltek ki, nem egy Menedék-viselkedéstan Projektre.}
{112}{}{Maga mirõl beszél?}
{113}{}{Menedék-viselkedéstan Projekt?}
{114}{}{Kibergenetika? Nem emlékszem, hogy valaha is tanultam ilyesmit.}
{115}{}{Áh, értem. Magának nincs ki az összes kereke. Ég magával!}
{116}{}{Nagy ég, máris többet mondtam, mint kéne. Nem számít... ha bárki is rákérdezne, én nem mondtam semmit.}
{117}{}{Extrém szociológiai kezelésrõl van szó. Ami azt illeti, mindig is azt gondoltam, hogy ez csak bûvészkedés, semmi igazi tudomány nincs mögötte. Viszont hallottam valamit a tizenhármasról, hogy a kísérlet során bevetettek valamit náluk. Felszínes munka, mondhatom.}
{118}{}{Milyen kísérletrõl beszél?}
{119}{}{Mi ez a kibergenetika dolog?}
{120}{}{Azt várja, hogy elhiggyem ezt? Maga most szökött a zártosztályról!}
{121}{}{Ó, az egy egészen új kutatási terület, nagyon izgalmas. Néhány projekten dolgozom mostanság, a mutáció problémájának egy radikálisan új koncepcióján. Tudja... eléggé egyszerû dologról van szó. A mutáció nem végérvényes. Gyógyítható.}
{122}{}{Természetesen az egyszerû gondolkodású kollégáim a lehetõ legdurvább módon próbálják megoldani a problémát. Megtisztulás a javából! Elismerem, hogy voltak korai nehézségek, de mostanra már elimináltuk õket... szerintem.}
{123}{}{}
{124}{}{[folytatás]}
{125}{}{Az a helyzet, hogy maga akár segíthetne is nekem a tesztelésben. Érdekelné a dolog?}
{126}{}{Milyen tesztelésre gondolt?}
{127}{}{Még csak az kéne...}
{128}{}{Elõkészítettem egy apró szérum-mintát, de bele kéne injektálni egy hordozóba.}
{129}{}{Nem hagyom, hogy bármilyen tût is belémnyomjon!}
{130}{}{Itt hagyjuk abba, már le is léptem!}
{131}{}{Magába? Jaj, dehogyis... a szérum nem tud mit kezdeni egy ilyen alacsony mutagén hányadossal. Ezt egy szupermutánson kell használni. Injektálja bele a szérumot egy szupermutáns testébe, és jelentse nekem az eredményt! Tisztában vagyok vele, hogy Broken Hills tele van velük.}
{132}{}{Mit csinál ez?}
{133}{}{Mi esik le nekem ebbõl?}
{134}{}{Nos, a genetikai mátrixban regressziót kell, hogy létrehozzon, amely destabilizációhoz vezet és egyszerûen asszimilálja a torzult DNS-t. A hordozót megszabadítja a mutagénektõl. Ha biztos lennék a dolgomban, nem volna szükség a tesztre.}
{135}{}{Mi esik le nekem ebbõl?}
{136}{}{Maga egy igen fontos kísérlet részesévé válik, igazság szerint a lehetõ legfontosabb tudományos... óh, maga pénzre gondol... Nos, van itt nekem egy kiberkutyám, egy továbbfejlesztett változat, személyes biztonsági feladatok ellátására. Szerintem mire visszatér, mûködésre tudnám bírni. Megfelelõ kompenzáció lenne?}
{137}{}{Kiberkutya? Hogyne, jól hangzik.}
{138}{}{Maga teljesen megzavarodott. Gumiszobába kéne zárni!}
{139}{}{Kiváló! Tessék a szérum, egy stimpakk fecskendõbe töltöttem. Semmi mást nem kell csinálnia, csak használni egy szupermutánson, és jelenteni az eredményt. Mint ahogy azt már említettem, Broken Hills... nos... jó hely lenne a kutakodáshoz. Sok szerencsét!}
{140}{}{Mondja meg a maga Mr. Merkjének, hogy a válaszom egy fikarcnyit sem változott. Nem érdekel semmiféle "közös üzlet". Köszönöm, és minden jót!}
{141}{}{Semmi értelme. Nem megyek vissza. Egyikõjük sem ismerte el az általam végzett munkát, ezért ne próbálja itt kiadni magát a barátomnak! Nagyon szépen köszönöm!}
{142}{}{Hát, akkor nincs mirõl beszélnünk. Minden jót!}
{143}{}{Nos, hogy ment? Sikerült a teszt?}
{144}{}{Igen.}
{145}{}{Nem.}
{146}{}{Ha nem bánja, ne fecséreljük egymás idejét! Már nem vagyok fiatal.}
{147}{}{És... Hogy mûködött?}
{148}{}{A szérum megölte a szupermutánst! Maga azt mondta, hogy a szérum gyógyít!}
{149}{}{Meghalt, Jim!}
{150}{}{Félreért engem. Én azt mondtam, hogy eltávolítja a mutagéneket. Az eljárás szemmel láthatóan eléggé beavatkozik a szervezetbe. Asszem, még finomítani kell.}
{151}{}{Mi a helyzet a fizetségemmel?}
{152}{}{Maga egy szörnyeteg! Semmi közöm magához!}
{153}{}{Kicsit bugos még. Újra és újra kell próbálkozni!}
{154}{}{Mi a helyzet a fizetségemmel?}
{155}{}{Maga egy szörnyeteg! Semmi közöm magához!}
{156}{}{Természetesen a kiberkutya a magáé. Most azonban dolgom van.}
{157}{}{...ezek szerint a mutációs ráta stabilizálódik... ne zavarjon, kérem!}
{158}{}{A környezeti behatások primitív adaptációja. Káprázatos...}
{159}{}{Nincs magánál egy oszcillációs kalibrátor? Persze, miért is lenne...}
{160}{}{ vagyok, a Kiválasztott. A 13-as Menedéket keresem.}
{161}{}{Minden jót ám, a valagam! Itt csak én udvariaskodhatok. Adja át a papírokat, különben egyenként szaggatom le az ujjait! Majd akkor megnézzük, milyen jó orvos is maga...}
{162}{}{Rendben, hagyom inkább.}
{163}{}{Öö... rendben, a papírok abban a asztalban vannak. Vigye csak! Egy kérésem van, a kezemet ne bántsa, kérem!}
{164}{}{Egyen szart, maga kretén! Õrség! Õrség!}
{165}{}{Látom, veszi a dolgokat. El is mondom Mr. Merknek.}
{166}{}{Ezt még megbánja, doki!}
{167}{}{Hé! Tíz másodpercet kap, hogy lerakja azt a köteg papírt, különben hívom az õrséget!}
{168}{}{Már megint kutakodik? Rendben! Majd a törvény odahat a magafajtára. Õrség! Õrség!}