# Dialog Editor last position: 4
{100}{}{Egy fiatalembert látsz az ÚKK rendõrség jelvényével.}
{101}{}{Õ Karl, a városi megbízott.}
{102}{}{Egy pelyhedzõ állú srácot látsz. Alig várja, hogy segíthessen.}
{103}{}{Üdvözlöm, idegen! Én Karl megbízott vagyok. Mit tehetek magáért?}
{104}{}{Mint például?}
{105}{}{Öh... nögh..}
{106}{}{Új vagyok itt az ÚKK-ban. Mit tud mondani a városáról?}
{107}{}{A 13-as Menedéket keresem.}
{108}{}{Tandi Elnök küldött, hogy beszéljek egy foglyukkal.}
{109}{}{A nevem}
{110}{}{Egy Jack nevû ürgét keresek. Néhányan Gyakós Jacknek hívják. }
{111}{}{Hol találom Roger Westint?}
{112}{}{Nem mulattott maga egy kicsit sokat? Nézze csak, itt egy nyitott cella! Miért nem megy hátra és alussza ki magát?}
{113}{}{Hallgasson rám! Kérje meg a barátait, hogy vigyék haza, ott majd kialussza magát. Itt bûnnek számít nyilvános helyen inni.}
{114}{}{Ez az ÚKK, az Új Kaliforniai Köztársaság fõvárosa. 3000 lakosa van, és folyamatosan nõ. Nincs rabszolgatartás, nincs szerencsejáték, nincs drog. Mrs. Tandi az elnök, Dumont seriff a fõnököm. Ezzel megválaszoltam a kérdését?}
{115}{}{Hát, lenne még néhány...}
{116}{}{Ja, ez minden.}
{117}{}{Mikor kicsi gyerek voltam, én is azt kerestem. Szóljon, ha megtalálta!}
{118}{}{Hát, lenne még néhány kérdésem.}
{119}{}{Ja, köszi.}
{120}{}{Õ Oswald. Ez minden, amit ki tudtunk szedni belõle. A 15-ös Menedék lakójának kellene lennie, de én kételkedem benne. Nagyon kemény fickó. Sejti, mire gondolok?}
{121}{}{Szóval kemény...??}
{122}{}{Mit fog csinálni vele??}
{123}{}{Mondja csak, nem hallottam én már magáról? Bizony, elég jó dolgokat... Nézze, ismerek itt bizonyos fickókat, akiknek hasznára volna egy magafajta ember. Csak menjen el az autósboltba, és kérdezzen rá Elise-nél! Mondja meg neki, hogy Karl üdvözli!}
{124}{}{Munkát akar? A Marhatenyésztõk Szervezete õröket keres. A rablók egyre gyakrabban támadják meg a jószágokat. Ezenkívül hallottam, hogy Tandi elnöknõ keres egy "talpraesett" embert, ahogy Õ mondja. Remélem, tudtam segíteni.}
{125}{}{Hát, lenne még néhány kérdésem.}
{126}{}{Elég lesz. Kösz.}
{127}{}{Az Jack rendõrtiszt, idegen. Az egyik emberünk. Ugye még nem beszélt Mirával?}
{128}{}{Igen.}
{129}{}{Ki az a Mira?}
{130}{}{Az egy kurafi! Van egy birtoka éppen a város mellett. Menjen végig a Marhatenyésztõk melletti úton!}
{131}{}{Nem nagyon csípi, amint látom.}
{132}{}{Hát, lennének egyéb kérdéseim.}
{133}{}{Kösz.}
{134}{}{Ja. A rosszabbik fajtából való. Minden szó nélkül megölte két emberünket.}
{135}{}{Hagyjon magunkra egy kicsit! Talán meg tudom gyõzni, hogy együttmûködõbb legyen.}
{136}{}{Most már megnézhetem?}
{137}{}{Remélem, felakasztják a rohadékot. Õ és a barátai megölték két jó emberünket. Nem okoz majd szívfájdalmat, ha meghal.}
{138}{}{Most már láthatom?}
{139}{}{Õ és Jack házasok voltak, de volt egy nagyon csúnya válásuk. Nem hiszem, hogy igazán elszakadtak egymástól. Ha jót akar magának, maradjon ki belõle! Jack jó ember, csak egy kicsit felidegesítették ezek a dolgok.}
{140}{}{Oké, váltsunk témát!}
{141}{}{Rendben, kösz a szíves felvilágositást, megbízott.}
{142}{}{Az ex-neje. Ha épp nincs itt, akkor biztos az erõmûben van. Dorothynál szokott éjszakai mûszakot vállalni.}
{143}{}{Hát, vannak még egyéb kérdéseim.}
{144}{}{Kösz.}
{145}{}{Amint láthatja, nem kertelek. Rengeteg ember felnéz rá, mert tanácstag, de én nem. Azt gondolja, hogy nagy ember és, hogy a törvény nem mindig vonatkozik rá. Én egy kicsit alacsonyabb lóra ültetném.}
{146}{}{Furcsa dolgok történtek mostanában. Mit tud errõl mondani?}
{147}{}{Mennem kell. Hogy is mondta? Éppen a város határában?}
{148}{}{Semmi probléma. Öt percig talán nem történik semmi. Kövessen!}
{149}{}{Persze, bármi jó is származzék magának ebbõl.}
{150}{}{Hát, néhány éve szélütést kapott, viszont Jubillee doki szerzett neki valami gyógyszert. Egyébként is, miért érdekli?}
{151}{}{Semmi, csak úgy kérdeztem! Nem vesztegetem tovább az idejét.}
{152}{}{. Kéne valami tisztességes munka.}
