{100}{}{Egy piszkos, vérfoltos ruhát viselõ ember.}
{101}{}{Ez itt a foglyul ejtett földfoglaló.}
{102}{}{Az arcán és a kezein késtõl származó régi sebek láthatók. Õrült tekintete egy igazi törvényenkívüli verekedõre enged következtetni.}
{103}{}{Csak az idõdet vesztegeted! Egy szót se szólok se hozzád, se máshoz!}
{104}{}{Menj el innen és hagyj békén, te disznó!}
{105}{}{Hirtelen milyen büdös lett itt...}
{106}{}{Mit fogsz csinálni? Addig fenyegetõzöl, míg ki nem nyitom a szám?}
{107}{}{Nem ijedtem meg tõled.}
{108}{}{Miért nem nyalod le a csizmámat?}
{109}{}{Mi a picsa? Meg akarsz ölni? Õrség!}
{110}{}{Beszéjjé' vagy én kinyírja te.}
{111}{}{Senki nem fog a segítségedre sietni. Ha élni akarsz, beszélsz!}
{112}{}{Oké, oké! Mit akarsz tudni? Csak ne bánts!}
{113}{}{15-ös Menedék... beszélni!}
{114}{}{Mit tudsz a 15-ös menedékrõl?}
{115}{}{Nézd, én csak egy porszem vagyok, nem a vezéregyéniség... az Darion. Õ a te embered. Õ találta ki ezt a dolgot Shady Sands-el, meg Tandival, a vén kurvával. Van egy rejtekhelye a 15-ös Menedékben, még a helyiekkel is elhitette, hogy velük van. Csak ennyit tudok. Nem hazudok!}
{116}{}{Really, I don't know anything else! I told you everything I know, really! Don't hurt me anymore.}
{117}{}{Semmiképpen! Nem dõlök be ennek a trükknek. BANG!... lelõnek szökés közben. Felejtsd el!}
