# Dialog Editor last position: 11
{100}{}{Nagy faszi + nagy puska + járkál = Õr.}
{101}{}{Még mindig õr.}
{102}{}{A homlokán ott van a rabszolga-hajcsárok tetkója, ami nem teszi intelligensebbé.}
{103}{}{Beszélj Mr. Vortisszal, ne velem!}
{104}{}{Öhh..}
{105}{}{Kérdésed van? Beszélj Vortisszal!}
{106}{}{Épp a magadfajták miatt kellünk. Érted?}
{107}{}{Na, megint van egy behatolónk!}
{108}{}{Riadó! Behatoló a helyszínen!}
{109}{}{Mr. Vortis - fosztogatók!}
{110}{}{Nagy hibát követtél el!}
