# Dialog Editor last position: 49
{100}{}{Ez a köpcös ember egy géppisztolyt hintáztat a kezében.}
{101}{}{Ez a rabszolga-felügyelõ.}
{102}{}{A tetoválásáról rögtön tudod, hogy õ egy rabszolga-hajcsár. Úgy néz ki, hogy õ az itteni õrök fõnöke.}
{103}{}{Mi a fene vagy te? Valami betörõ?}
{104}{}{Az ÚKK jótevõje! Van neked egy kis gyógyszerem.}
{105}{}{Vortis, van egy behatolónk!}
{106}{}{Õrség! Riadó!}
{107}{}{Mit akarsz?}
{108}{}{Kurg?}
{109}{}{Mi ez a hely?}
{110}{}{A Felderítõk küldtek.}
{111}{}{A tulajt keresem.}
{112}{}{Hajcsár-testvérem, volna néhány kérdésem.}
{113}{}{Bocs, nem téged kereslek.}
{114}{}{El innen, eridj! Van már itt épp elég hülye õr.}
{115}{}{Mi van, tökfej, vak vagy? Ez egy rabszolga-karám. Ha többet akarsz tudni, beszélj Vortisszal!}
{116}{}{Szóval így állunk? Rendben, hullazsákban fogod végezni!}
{117}{}{Nyilván Vortisra gondolsz, az öreg fickóra.}
{118}{}{Kösz. Te értelmesnek látszol. Fogadok, hogy ki tudsz engem segíteni pár kérdésben.}
{119}{}{Az öreg fickó? Okés.}
{120}{}{Ha már így állunk, nem igazán tudok nemet mondani. Mi jár a fejedben?}
{121}{}{Kösz, idegen.}
{122}{}{Többet tudok, mint amennyit az öreg Vortis feltételez rólam.}
{123}{}{Több mindent csináltam már, mint amire az emberek többsége számítana. Itt van például ez a meló. Igazán megfelel az igényeimnek.}
{124}{}{Hogyne, hogyne...}
{125}{}{Mi a helyzet a mindenfelé elhíresült Felderítõkkel?}
{126}{}{A 13-as Menedéket keresem. Hallottál már róla?}
{127}{}{Hallottál az ÉLET-rõl?}
{128}{}{Hallottál már egy Enklávé nevû csoportosulásról?}
{129}{}{Munkát keresek. Tudsz valakit, aki szerzõdtetne?}
{130}{}{Na, magadra hagylak... Nem akarlak feltartani.}
{131}{}{Azok a mocskok megölték a testvéremet és azt mondták, hogy az emberek jólétéért tették. Ki kell pusztítani õket. Ha tudsz segíteni, beszélj Vortisszal!}
{132}{}{Nekem jó ötletnek tûnik.}
{133}{}{Vortisszal? Te vagy itt a bölcsesség forrása. Mit egyebet tudsz még mondani?}
{134}{}{Kösz. Azt hiszem, azt fogom most csinálni. }
{135}{}{Mindenki hallott a 13-as Menedékrõl. Mikor kölyök voltam, én és a haverok egyre csak kerestük. Innen keletre kellene lennie, mindent átkutattuk utána, de soha nem találtuk meg.}
{136}{}{Biztos vagyok benne, hogy mindent beleadtatok. Kérdeznék még valamit, ha már ilyen sokat tudsz.}
{137}{}{A helyzet az, hogy mennem kell...}
{138}{}{ÉLET, na hiszen... Régen, amikor a Menedék-technikát tanulmányoztam, olvastam róluk. Feltehetõen minden menedéknek volt egy és amikor kinyitották az ajtókat, ezeket kellett elõször használniuk. Azt mondják, Shady Sands is így kezdte... egy ÉLET-tel. Segít ez valamit?}
{139}{}{Tanulmányoztad a Menedék-technikát? Lenyûgözõ. Van még néhány kérdésem a számodra.}
{140}{}{Rendben, viszont mennem kell.}
{141}{}{Az Enklávé... Tudod, van egy doki a városban, egy Henry nevû. Valamelyik éjjel, amikor be volt rúgva, beszélt valami Enklávésoknak titulált fickókról.}
{142}{}{Pontoson ezt akartam tudni. Te aztán jól informált ember vagy.}
{143}{}{Csak ennyit akartam tõled, testvérem. Kösz.}
{144}{}{Én mindig odafigyelek a dolgokra... a baj az, hogy többé már senki nem akar rabszolga-hajcsárt bérelni. Vortis, a fõnököm, titkol valamit. A városi marhatenyésztõk mindig tudnak munkát adni a Marhatenyésztõk Egyesületében, Dorothynál, az erõmûben pedig mindig elkél egy dolgos kéz, ha megvan a képzettséged hozzá. Az a szóbeszéd is járja, hogy Tandi Elnöknõ egy specialistát keres.}
{145}{}{Ember, te aztán jó sokmindent tudsz! Az egész napot el tudnám tölteni azzal, hogy téged kérdezgetlek.}
{146}{}{Rendben, megyek és utána nézek a dolgoknak.}
{147}{}{Levágod nekem a... tudod, mirõl van szó... rendben?}
{148}{}{Semmi gond. Mindamellett van itt még valami, amit tudni szeretnék.}
{149}{}{Elintézem õket, ne aggódj!}
