{100}{}{Ez itt egy ösztövér, vén fickó, a füle mögött golyóstollal, az orrán pedig szemüveg billeg.}
{101}{}{Vortis, e rabszolga-karám felügyel?je.}
{102}{}{A fickónak kábé három foga van. Az ujját és az ingét tintapacák csúfítják. A homlokán egy meglehet?sen halvány rabszolga-hajcsár tetoválás díszlik.}
{103}{}{Szóval mit is akarsz?}
{104}{}{Testvérem, üdvözlünk Vortis papánál. Miben segíthetek?}
{105}{}{Kezdesz bosszantani...}
{106}{}{This place is my place and I, Vortis, run an honest and legitimate business no matter what anybody in NCR tells you. Since NCR doesn't allow slaves inside the gates, I mind them for folks who've got business inside.}
{107}{}{Mi van, meggárgyultál? Ez egy rabszolga-karám. Engedélyem van rá.}
{108}{}{}
{109}{}{Csak néhány kérdést tennék fel...}
{110}{}{Munkát keresek.}
{111}{}{Öh?}
{112}{}{Nem budi? Menek innét elfele.}
{113}{}{Mire való ez a hely?}
{114}{}{Semmi. Rossz hely.}
{115}{}{Nézzétek már... egy kis jótét lélek, egy nyalókáért ácsingózó kölyök jött hozzánk... Fiúk, vezessétek el a szemem el?l ezt a kétszín?, álszentesked? díszpéldányt!}
{116}{}{Baszódj meg!}
{117}{}{Igen?}
{118}{}{A 13-as Menedéket keresem.}
{119}{}{Nincs egy ÉLETED?}
{120}{}{Mit tud mondani err?l a városról?}
{121}{}{Te egy mocsokláda hajcsár vagy! Egy okot mondj, hogy ne öljelek meg!}
{122}{}{Úgy hallottam, van itt egy kompánia, akiket az Új Kaliforniai Felderít?knek neveznek. Nem törnek borsot az orrod alá?}
{123}{}{Nem bánod, ha körbenézek?}
{124}{}{Munkát keresel? Hát... lehet, hogy volna valami. Hallottál valaha az Új Kaliforniai Felderít?kr?l?}
{125}{}{Igen.}
{126}{}{Nem.}
{127}{}{Baszódj meg, ott ahol vagy! Fiúk, vigyétek ki innen ezt a bosszantó kis mocskot!}
{128}{}{Cseszd meg!}
{129}{}{13-as Menedék?! T?nj innen a francba! Az egy kamu hely! Méghogy 13-as Menedék... meg a valagam.}
{130}{}{Lenne még valami...}
{131}{}{Hát, köszi, bár sokra nem mentem vele.}
{132}{}{Egy micsodám? Hát, nem tudom, mi az, de nincs nekem olyanom.}
{133}{}{Lenne még valami...}
{134}{}{Hát, köszi, bár sokra nem mentem vele.}
{135}{}{Új Kaliforniai Köztársaság - csupa önmegtartóztató meg keresked? lakik itt. Nem csípik a hajcsárokat meg a rabszolgaságot, de hát az istenit, ez a munkám!}
{136}{}{Lenne még valami...}
{137}{}{Kösz, most mennem kell.}
{138}{}{Valaki rossz irányba terelt téged. Nincs nekem bajom senkivel, különösen nem a Felderít?kkel. Teljesen legálisan m?ködöm itt, szóval nem érheti szó a ház elejét.}
{139}{}{Lenne még valami...}
{140}{}{Mondhatsz, amit akarsz, nekem most mennem kell.}
{141}{}{Igen, a felderít?k bandája a szívem csücske. Munkát keresel?}
{142}{}{Igen.}
{143}{}{Nem.}
{144}{}{Nem, te csak ne nézel?dj itt, szararcú! Ez nem múzeum!}
{145}{}{Lenne még valami...}
{146}{}{Túl ingerlékeny vagy. Engedelmeddel távozom.}
{147}{}{Ami azt illeti... egyesek potenciális problémát látnak bennük. Szerfelett örülnénk neki, ha az északi területeken, New Reno, Klamath meg ilyenek környékén lév? rejtekhelyeikr?l térképet szerezhetnénk. Fizetnék érte vagy 500 dollárt. Szerinted tudnál ilyesmit szerezni?}
{148}{}{Hogyne.}
{149}{}{Nem hinném.}
{150}{}{Elmondok valamit akkor. Ezek a Felderít?k azt vették a fejükbe, hogy a hajcsárokat és magát a rabszolgaságot is eltörlik a föld színér?l. Er?vel. Sok problémát okoznak egy rakás keményen dolgozó embernek.}
{151}{}{Titokban m?ködnek, különösen északon.}
{152}{}{A jóéletbe! Külön magyarázatot kell benyújtanom? Megtámadják a rabszolga-keresked?ket, elhajtják az állományt, és lehozzák délre, az ÚKK-ba, ahol a rabszolga-tartás illegális. Na, érdekel?}
{153}{}{Nincs semmiféle "és"! Akarod a munkát vagy sem?}
{154}{}{És?}
{155}{}{Szóval mit akarsz, hogy tegyek?}
{156}{}{Remek. Amint megszerzed a térképet, itt leszek.}
{157}{}{Hol találjak térképet?}
{158}{}{Oké, volna néhány kérdésem azért...}
{159}{}{Benne vagyok. Találkozunk kés?bb.}
{160}{}{Honnan a francból tudjam!? Ha tudnám, nálam lenne, nem igaz? Figyelj rám, van egy sejt a városban. Találd meg ?ket, és gondold át, mire mehetsz velük!}
{161}{}{Csak még néhány kérdést, ha lehet...}
{162}{}{Rendben. Kés?bb jövök...}
{163}{}{Szóval megint itt vagy... Megszerezted azt a térképet?}
{164}{}{Igen.}
{165}{}{Nem.}
{166}{}{Még mindig várom, hogy teljesítsd az els? feladatot!}
{167}{}{Oh yeah, I forgot.}
{168}{}{Nem, mivel megcsináltad a munkát. Köszönöm.}
{169}{}{Csak egy vagy két kérdést még...}
{170}{}{Semmi baj. Viszlát!}
{171}{}{Jó munka volt! Most viszont jobb, ha felszívódsz! Ha esetleg azok a Felderít?k rájönnének erre-arra...}
{172}{}{Öröm, ha együtt üzletelünk.}
{173}{}{Ne lófrálj már itt, te üt?dött! Valaki még gyanút foghat!}
{174}{}{Rendben, veszem én az adást...}
{175}{}{Mi a faszom...? ?rség! Fogtam egy behatolót!}
{176}{}{Csak menj be oda, és lerobbantom a fejedet! Megértetted?}
{177}{}{It's late and we're closed. Come back in the morning.}
