{100}{}{Ez itt egy ösztövér, vén fickó, a füle mögött golyóstollal, az orrán pedig szemüveg billeg.}
{101}{}{Vortis, e rabszolga-karám felügyelõje.}
{102}{}{A fickónak kábé három foga van. Az ujját és az ingét tintapacák csúfítják. A homlokán egy meglehetõsen halvány rabszolga-hajcsár tetoválás díszlik.}
{103}{}{Szóval mit is akarsz?}
{104}{}{Testvérem, üdvözlünk Vortis papánál. Miben segíthetek?}
{105}{}{Kezdesz bosszantani...}
{106}{}{Ez itt az én kis birodalmam és én, Vortis, legális üzletmenetet folytatok. Nem számít, hogy az ÚKK-s okosok mivel tömik a fejed. Mivel az ÚKK nem engedi be a rabszolgákat a falain belülre, én felügyelem a városban üzleti ügyeiket intézõk tulajdonát is.}
{107}{}{Mi van, meggárgyultál? Ez egy rabszolga-karám. Engedélyem van rá.}
{108}{}{}
{109}{}{Csak néhány kérdést tennék fel...}
{110}{}{Munkát keresek.}
{111}{}{Öh?}
{112}{}{Nem budi? Menek innét elfele.}
{113}{}{Mire való ez a hely?}
{114}{}{Semmi. Rossz hely.}
{115}{}{Nézzétek már... egy kis jótét lélek, egy nyalókáért ácsingózó kölyök jött hozzánk... Fiúk, vezessétek el a szemem elõl ezt a kétszínû, álszenteskedõ díszpéldányt!}
{116}{}{Baszódj meg!}
{117}{}{Nos?}
{118}{}{A 13-as Menedéket keresem.}
{119}{}{Nincs véletlenül egy ÉLET-ed?}
{120}{}{Mit tudnál elmondani errõl a városról?}
{121}{}{Te egy mocsokláda hajcsár vagy! Egy okot mondj, hogy ne öljelek meg!}
{122}{}{Úgy hallottam, van itt egy kompánia, akiket az Új Kaliforniai Felderítõknek neveznek. Nem törnek borsot az orrod alá?}
{123}{}{Nem bánod, ha körbenézek?}
{124}{}{Munkát keresel? Hát... lehet, hogy volna valami. Hallottál valaha az Új Kaliforniai Felderítõkrõl?}
{125}{}{Hallottam.}
{126}{}{Soha az életben...}
{127}{}{Baszódj meg, ott ahol vagy! Fiúk, vigyétek ki innen ezt a bosszantó kis mocskot!}
{128}{}{Bekaphatod!}
{129}{}{13-as Menedék?! Tûnj innen a francba! Az egy kamu hely! Méghogy 13-as Menedék... meg a valagam.}
{130}{}{Kérdeznék még...}
{131}{}{Hát, köszi, bár sokra nem mentem vele.}
{132}{}{Egy micsodám? Hát, nem tudom, mi az, de nincs nekem olyanom.}
{133}{}{Kérdeznék még...}
{134}{}{Hát, köszi, bár sokra nem mentem vele.}
{135}{}{Új Kaliforniai Köztársaság - csupa önmegtartóztató meg kereskedõ lakik itt. Nem csípik a hajcsárokat meg a rabszolgaságot, de hát az istenit, ez a munkám!}
{136}{}{Kérdeznék még...}
{137}{}{Kösz, most mennem kell.}
{138}{}{Valaki rossz irányba terelt téged. Nincs nekem bajom senkivel, különösen nem a Felderítõkkel. Teljesen legálisan mûködöm itt, szóval nem érheti szó a ház elejét.}
{139}{}{Kérdeznék még...}
{140}{}{Mondhatsz, amit akarsz, nekem most mennem kell.}
{141}{}{Igen, a felderítõk bandája a szívem csücske. Munkát keresel?}
{142}{}{Igen.}
{143}{}{Nem.}
{144}{}{Nem, te csak ne nézelõdj itt, szararcú! Ez nem múzeum!}
{145}{}{Kérdeznék még...}
{146}{}{Túl ingerlékeny vagy. Engedelmeddel távozom.}
{147}{}{Ami azt illeti... egyesek potenciális problémát látnak bennük. Szerfelett örülnénk neki, ha az északi területeken, New Reno, Klamath meg ilyenek környékén lévõ rejtekhelyeikrõl térképet szerezhetnénk. Fizetnék érte vagy 500 dollárt. Szerinted tudnál ilyesmit szerezni?}
{148}{}{Hogyne!}
{149}{}{Nem hinném.}
{150}{}{Elmondok valamit akkor. Ezek a Felderítõk azt vették a fejükbe, hogy a hajcsárokat és magát a rabszolgaságot is eltörlik a föld színérõl. Erõvel. Sok problémát okoznak egy rakás keményen dolgozó embernek.}
{151}{}{Titokban mûködnek, különösen északon.}
{152}{}{A jóéletbe! Külön magyarázatot kell benyújtanom? Megtámadják a rabszolga-kereskedõket, elhajtják az állományt, és lehozzák délre, az ÚKK-ba, ahol a rabszolga-tartás illegális. Na, érdekel?}
{153}{}{Nincs semmiféle "és"! Akarod a munkát vagy sem?}
{154}{}{És?}
{155}{}{Szóval mit akarsz, hogy tegyek?}
{156}{}{Remek. Amint megszerzed a térképet, itt leszek.}
{157}{}{Hol találjak térképet?}
{158}{}{Oké, volna néhány kérdésem azért...}
{159}{}{Benne vagyok. Találkozunk késõbb.}
{160}{}{Honnan a francból tudjam!? Ha tudnám, nálam lenne, nem igaz? Figyelj rám, van egy sejt a városban. Találd meg õket, és gondold át, mire mehetsz velük!}
{161}{}{Csak még néhány kérdést, ha lehet...}
{162}{}{Rendben. Késõbb jövök...}
{163}{}{Szóval megint itt vagy... Megszerezted azt a térképet?}
{164}{}{Igen.}
{165}{}{Nem}
{166}{}{Még mindig várom, hogy teljesítsd az elsõ feladatot!}
{167}{}{Ja, igen, elfelejtettem...}
{168}{}{Nem, mivel megcsináltad a munkát. Köszönöm.}
{169}{}{Csak egy vagy két kérdést még...}
{170}{}{Nem probléma. Üdv!}
{171}{}{Jó munka volt! Most viszont jobb, ha felszívódsz! Ha esetleg azok a Felderítõk rájönnének erre-arra...}
{172}{}{Öröm, ha együtt üzletelünk.}
{173}{}{Ne lófrálj már itt, te ütõdött! Valaki még gyanút foghat!}
{174}{}{Rendben, veszem én az adást...}
{175}{}{Mi a faszom...? Õrség! Fogtam egy behatolót!}
{176}{}{Csak menj be oda, és lerobbantom a fejedet! Megértetted?}
