{100}{}{A férfi remek cowboy öltözéket hord.}
{101}{}{Õ Westin Tanácstag.}
{102}{}{Ezüst és türkizkék gyûrûk, ezüst csat, pisztoly az oldalán... ez a fickó alaposan hozzászokott, hogy van pénze, és mindent megengedhet magának.}
{103}{}{Roger Westin vagyok. Maga nem jöhet csak úgy ide. Mit akar?}
{104}{}{Már megint itt van? Mi a fenét akar?}
{105}{}{Mit akar?}
{106}{}{Döh...}
{107}{}{Én keresse 13-as Menedék? Segíccse nekem?}
{108}{}{A 13-as Menedéket keresem. Tud segíteni?}
{109}{}{Befejeztem a piszkos munkáját...}
{110}{}{Rossz dolgok jönnek. Én ijessze elfele. Mú-Múúk rendbe'.}
{111}{}{A brahmin problémájáról van szó... úgy tûnik, egyszerûen csak oda kell állítania egy embert. Nem kell csinálnia semmit, csak ott lenni. Tudom, hogy furán hangzik, de mûködik. Mintha valami fizetségrõl is lett volna szó...}
{112}{}{Megbízatás ügyében jöttem.}
{113}{}{Lynette Elsõ Polgár Asszony üdvözletét küldi. Küldött magának valamit.}
{114}{}{Bishoptól jövök...}
{115}{}{Jaj...}
{116}{}{Ez minden? Beszéljen a telepvezetõmmel, Felixszel!}
{117}{}{Úgy látom, nem érti. Megbízatás ügyében jöttem.}
{118}{}{Egyenesen a seriff ajánlotta, hogy jöjjek magához személyesen.}
{119}{}{Remek. Legyen úgy.}
{120}{}{Gondolhattam volna. Mit ígért magának? Pénzt? Drogot? Szexet? Nem mintha számítana. Sosem kapja meg egyiket sem.}
{121}{}{Ezt hogy érti?}
{122}{}{Pofa be!}
{123}{}{Mi van, tú egyszerûnek születtünk? Milyen szomorú. Nehéz sorsa lehet. Figyeljen rám! Menjen, beszéljen Felixszel! Õ majd ad munkát. Értem?}
{124}{}{[Bólogatsz].}
{125}{}{Mit képzel? Túl sokat tud. Mi lenne, ha visszajönne az ÚKK-ba és beárulná magát, vagy megfenyegetné vele? Halott is lenne semmi perc alatt. Mellesleg van egy jobb ajánlatom.}
{126}{}{Ûgymint?}
{127}{}{Nem hiszek magának.}
{128}{}{Nyírja ki Bishopot! Készpénzben fizetek. Bármennyit is ígért, én másfélszer többet adok. Mennyit is kap?}
{129}{}{(infó kell Chris)}
{130}{}{(Avellone-tól, ez az)}
{131}{}{Remek.}
{132}{}{Megegyeztünk.}
{133}{}{Szar ügy, vénember!}
{134}{}{Várom, hogy mire jutott. Most, kérem távozzon arra, amerrõl jött!}
{135}{}{Kiváló! Tudtam, hogy maga az én emberem. Megígértem, hogy fizetek, és én állom a szavam. Tessék a pénze.}
{136}{}{Bármi egyéb, amit tehetek magáért?}
{137}{}{Köszönöm. Esetleg segíthetne nekem. A 13-as Menedéket próbálom megtalálni.}
{138}{}{Minden jót!}
{139}{}{Dumont ajánlotta magát? Ez nekem éppen elég. Valami, vagy valaki dézsmálja a brahminjaimat éjszakánként. Szeretnék rájönni, mi áll a háttérben. Mit szólna, ha utánajárna nekem? Megfizetem a fáradozását.}
{140}{}{Könnyû munkának tûnik, elvállalom.}
{141}{}{Nem fûlik hozzá a fogam...}
{142}{}{Valami, vagy valaki dézsmálja a brahminjaimat éjszakánként. Szeretnék rájönni, mi áll a háttérben. Mit szólna, ha utánajárna nekem? Megfizetem a fáradozását.}
{143}{}{Jó ötletnek tûnik, elvállalom.}
{144}{}{Nem, köszönöm. Ülni a mezõn és csak arra várni, hogy valami nagy sáskalény odatolja a képét, marha unalmas dolog.}
{145}{}{Kiváló! Felix elvezeti oda. Most, ha megbocsát...}
{146}{}{Hát, lehet, hogy tudok segíteni. Rengeteg történetet hallottam Tandiról és a Menedéklakóról. Évekkel az ÚKK alapítása elõtt megmentette Tandi életét. A legenda mellesleg azt tartja, hogy a Menedéklakó rengeteg idõt töltött az innen keletre lévõ Menedék felkutatásával. Ha az nem a 13-as Menedék, talán ott a nyomára akad annak, amit keres.}
{147}{}{Óóóóh. Jó.}
{148}{}{Köszönöm!}
{149}{}{Hát, lehet, hogy tudok segíteni. Mellesleg szeretnék kérni egy szívességet elõször. Valami, vagy valaki dézsmálja a brahminjaimat éjszakánként. Szeretnék rájönni, mi áll a háttérben. Mit szólna, ha utánajárna nekem? Megfizetem a fáradozását és elmondom azt, amit tudok.}
{150}{}{Jó ötletnek tûnik, elvállalom.}
{151}{}{Nem, köszönöm. Ülni a mezõn és csak arra várni, hogy valami nagy sáskalény odatolja a képét, marha unalmas dolog.}
{152}{}{Akkor a viszont látásra! Egy élmény volt magával beszélgetni, idegen...}
{153}{}{Nem tudom, higgyek-e magának, de azért itt a fizetsége. A fenébe is, ha hazudik, az embereim megtalálják. Azt is ígértem, hogy elmondok magának ezt-azt, amit tudok. Hát tessék: Rengeteg történetet hallottam Tandiról és a Menedéklakóról. Évekkel az ÚKK alapítása elõtt megmentette Tandi életét. A legenda mellesleg azt tartja, hogy a Menedéklakó rengeteg idõt töltött az innen keletre lévõ Menedék felkutatásával. Ha az nem a 13-as Menedék, talán ott a nyomára akad annak, amit keres.}
{154}{}{Én köszönni meg!}
{155}{}{Köszönöm.}
{156}{}{Az Elsõ Polgár? Kiváló, erre várok már jó ideje. Maga Menedékváros Polgára?}
{157}{}{Igen.}
{158}{}{Nem.}
{159}{}{Biztos vagyok benne, hogy maga jó Polgár. Szeretném, ha ezt a hololemezt visszavinné az Elsõ Polgárnak. Nagyon fontos. Azok az információk vannak rajta, ami az ÚKK-New Reno terveihez kellenek.}
{160}{}{Volna még néhány kérdésem.}
{161}{}{Igen, uram.}
{162}{}{Rendben vagyunk, ez minden.}
{163}{}{Volna még néhány kérdésem.}
{164}{}{Jól van, jól van...}
{165}{}{Megbízatás? Úgy érti...}
{166}{}{Engem Bishop küldött. Volna egy rövidke üzenete a maga számára.}
{167}{}{Ég magával, és álmodjon szépeket, vénember!}
{168}{}{dollár. Ha rendesen megcsinálja a munkát, én minden további nélkül fizetek. Ha nemet mond, nem jut ki innen élve. Nos?}

{169}{}{Ah, igen... hát, volt egy kis problémám a rágcsálókkal, de abbamaradt. Elnézést, ami ezt illeti. Próbálkozzon Felixnél, hátha van valami munka a maga számára!}
{170}{}{Oké, köszönöm.}

{171}{}{Ehhh... nagyon rossz a szívem... nem bírom...}
{172}{}{El kell... mooonddaaniiii Feeelixneeeek.}
{173}{}{Nocsak-nocsak! Asszem, már csak múlt idõben beszélhetünk a szívbántalmáról...}

{174}{}{AHHAHH!!! AHAHAHHAH!!! AHHAHAH!!! ÉGET!!!}