{100}{}{Egy idõs hölgy. Vékony és megviselt.}
{101}{}{Õ Tandi, az ÚKK elnöke.}
{102}{}{Egy kemény, önbizalomtól fûtött asszony. Lerí róla, hogy hozzászokott mások tiszteletnyilvánításához.}

{103}{tand1}{Tandi vagyok, az ÚKK elnöke. A fiaim szerint maga megbízatás ügyében jött. Mihez ért?}
{104}{}{Én jól lõ. Legjobb.}
{105}{}{Én jól beszéjje emberek.}
{106}{}{Én jól harcóni. Királyosan.}
{107}{}{Én osonolok. Jutok elfele bárhova. Nem láccok, nem hallaccok.}
{108}{}{Sok mindenhö'.}
{109}{}{Öö, hát, úgy... mindenhö'.}
{110}{}{Értek a fegyverekhez. Az egyik legjobb vagyok.}
{111}{}{Azt mondták rólam, Elnöknõ Asszony, hogy jól bánok a szavakkal.}
{112}{}{Jó vagyok a pusztakezes harcban. Addig ütöm, amíg meleg...}
{113}{}{Jó vagyok abban, ha láthatatlanul kell bejutnom valahova.}
{114}{}{Somindenhez értek, és bármelyik képességemet a maga szolgálatába állítom, ha úgy hozza a sors.}
{115}{}{Hát, szerintem mindenhez.}

{116}{tand2}{Hmmm. Azt hiszem, maga nem az én emberem. Biztos benne, hogy tudna boldogulni?}
{117}{}{Én nem tuggya. Miféle feladat?}
{118}{}{Hiszek én énbennem. Én tudja megcsiná'ni!}
{119}{}{Attól függ, milyen feladattal bíz meg.}
{120}{}{Igen, bízom a képességeimben, és egyáltalán... magamban.}

{121}{tand3}{Olyan embernek tûnik, akire most épp szükségünk van.}
{122}{}{Jó. Hogyan én segíccse?}
{123}{}{Remek, miképpen segíthetnék?}

{124}{tand4}{Számítógép-alkatrészekre van szükségünk egy régi bázisból, egész pontosan a 15-ös Menedékbõl. Az a probléma, hogy földfoglalók vették be oda magukat, és nem engednek be senkit. Valakinek meg kéne gyõzni õket, hogy bejuthassunk... vagy csak egyszerûen vissza kéne hozni az alkatrészeket. Vállalja a megbízatást?}
{125}{}{Én nem tesse, nem. Menek elfele.}
{126}{}{Én aszongya, vállalni.}
{127}{}{Én lenni máris ottan. Fõdfoglalók akarni egyesség. Maguk tanít, segít, õk aggyák Menedék.}
{128}{}{Én lenni máris ottan. Itten lenni alkatosrészek.}
{129}{}{Én lenni máris ottan. Fõdfoglalók akarni egyesség. Maguk tanít, segít, õk aggyák Menedék. Meg itten lenni alkatosrészek hozzája.}
{130}{}{Sajnálom, de ez nem esik bele a tevékenységi körömbe.}
{131}{}{Boldogan segítek, ha tudok.}
{132}{}{Érdekel a dolog, de mennyi üti a markomat ezért?}
{133}{}{A nagy részét máris megcsináltam. A földfoglalók egyezséget kínálnak. Maguk segítenek, hogy önellátók lehessenek, ezért cserébe hozzáférést biztosítanak a Menedékhez.}
{134}{}{Már voltam ott, és nálam vannak a kért számítógép-alkatrészek.}
{135}{}{Ezt az ügyet már lerendeztem. A földfoglalók egyezséget kínálnak. Maguk segítenek, hogy önellátók lehessenek, ezért cserébe hozzáférést biztosítanak a Menedékhez. Ezenkívül itt vannak az alkatrészek.}

{136}{tand5}{A mennydörgõs mindenit... hát, maga dönt... de ha esetleg meggondolná magát...}
{137}{}{[Kész]}

{138}{tand6a}{Részemrõl elfogadható. Csinálja meg a munkát, és jutalmat kap!}
{139}{tand6b}{Ó, Uram, tudom, hogy hibát követek el, de... próbálja meg... ha bármit is megértett abból, amit mondtam!}
{140}{}{Oké. Menek...}
{141}{}{Nekem lenni kérdés.}
{142}{}{Rendben, indulok is...}
{143}{}{Szeretnék néhány kérdést feltenni.}

{144}{tand7a}{Nos, tudok egy kis idõt szakítani erre...}
{145}{tand7b}{Mit szeretne tudni}
{146}{}{Mit mongya 15-ös Menedékrõ'?}
{147}{}{Mér nem egyezkeggye foglalók?}
{148}{}{Tuggya hol 13-as Menedék?}
{149}{}{ÉLET kell. Lenni?}
{150}{}{Mit tuggya mondani New Reno?}
{151}{}{Mit tuggya mondani Frank Westin?}
{152}{}{Mit tuggya mondani Carlson?}
{153}{}{Törzsfõ mongya sztori. Mesélni Menedéklakó, Tandi. Te lenni Tandi?}
{154}{}{Az a Sédiszendsz Törzsfõ mongya?}
{155}{}{Minden mondani elfele. Menek innét.}
{156}{}{Mit tudna mondani a 15-ös Menedékrõl?}
{157}{}{Miért nem kötöttek üzletet a földfoglalókkal?}
{158}{}{Tudja, merre van a 13-as Menedék?}
{159}{}{Egy ÉLET-et keresek. Nincs véletlenül egy maguknak?}
{160}{}{Mit tudna mondani New Renóról?}
{161}{}{Mit tudna mondani Frank Westinrõl?}
{162}{}{Mit tudna mondani Carlsonról?}
{163}{}{A Törzsfõ mesélt a Menedéklakóról és egy Tandi nevû nõrõl. Maga lenne ez a Tandi?}
{164}{}{Ez a hely Shady Sands, amirõl a Törzsfõ beszélt?}
{165}{}{Ez minden... Most mennem kell...}

{166}{tand8}{Kelet felé található innen, egy földalatti bunker a háború idejébõl. Az ÚKK legtöbb családja onnan származik, tehát jogos tulajdonunk.}
{167}{}{Mongya több!}
{168}{}{Folytassa, kérem!}

{169}{tand9}{Néhány esztendõvel ezelõtt földfoglalók kisebb hada költözött be oda, és putrivárost építettek a felszínen. "Birtoknak" nevezik. Azok az emberek nem jobbak, mint a kóbor kutyák. Nem tudnak bemenni a Menedékbe, de bennünket is hátráltatnak.}
{170}{}{Még vannak kérdések.}
{171}{}{Értem. Szeretnék még egy-két dolgot megkérdezni.}

{172}{tand10}{Próbáltam. Elküldtem néhány emberünket oda, de az elsõ néhánytól eltekintve rendre eltünedeztek. Nem tudom bebizonyítani, hogy a földfoglalók lelkén szárad-e a dolog. A fiaimnak sikerült foglyul ejteni az egyiküket, de az istennek sem akar beszélni. Most a belvárosi fogdában csücsül.}
{173}{}{Kell még tudni több.}
{174}{}{Szeretnék még kérdezni, kérem.}

{175}{tand11}{Térjen a lényegre! Nem tölthetem magával az egész napomat...}
{176}{}{Oké, én sietni}
{177}{}{Próbálok tömör lenni.}

{178}{tand12}{Mivel azt a ruhát viseli, nyilvánvaló, hogy tisztában van ezzel.}
{179}{}{Ruha régóta lenni faluba'. Tartozik a Menedéklakkóhó', ki törzsnek alapítója.}
{180}{}{Ez az öltözék már a kezdetek óta a falum tulajdona. A Menedéklakóé volt, az alapítónké.}

{181}{tand13}{Ugye nem viccel? Ugyanarról az emberrõl beszélünk, aki megmentette az életemet. (Fúj egyet) Késõbb eltûnt. Amikor már-már azt hinném, hogy álom volt csupán, megnézem a kint felállított szobrot.}
{182}{}{Szobrot?}

{183}{tand14a}{Úgy van. A fosztogatók elrettentésére. Eltakarodtak Shady Sandstõl, miután berendezkedtünk. Hõst csináltunk a Menedéklakóból... pedig egy szavát sem hittük, hogy a 13-as Menedékbõl érkezett.}
{184}{}{Én emlékezze... Kérdezhetni még?}
{185}{}{Eszemben fogom tartani. Kérdezhetek még?}

{186}{tand15}{Miért érdeklõdik a 13-as Menedékrõl?}
{187}{}{Lenni kíváncsi...}
{188}{}{Én lenni Kiválasztott. Én leszármazottya Menedéklakó.}
{189}{}{Nem számíccsa. Én kérdezni többet.}
{190}{}{Hallottam történeteket és bizony kíváncsi vagyok.}
{191}{}{A falum Kiválasztottja vagyok, egyúttal a Menedéklakó leszármazottja.}
{192}{}{Nem fontos, csak kíváncsiskodom...}

{193}{tand16}{Ez csak egy átkozott mítosz, mint az elveszettnek hitt uránbányák. Egyszer találkoztam valakivel, aki azt állította, hogy onnan származik. Sokan meghaltak, akik onnantól fogva a 13-as Menedék keresésére indultak.}
{194}{}{Menedéklakó igazi! Én leszármazott lenni neki.}
{195}{}{Én tunni kell több minden.}
{196}{}{A Menedéklakó nem kitaláció. Én vagyok a leszármazottja.}
{197}{}{Értem. Hadd kérdezzek valami egyebet!}

{198}{tand17}{ÉLET? Mindannyiunk maga rendelkezik a sajátja felett.}
{199}{}{Nem az... mindegy... Én kérdezze kérdés.}
{200}{}{Nem, nem arra az életre gondoltam... mindegy, hagyjuk! Hadd kérdezzek valami egyebet!}

{201}{tand18}{New Reno? Egy rakás brahminköpet az egész. Csupa erkölcstelenség. Ha összefogást akarunk ebben a régióban, keménynek kell lennünk velük. A Kongresszusnak meg kéne ezt értenie...}
{202}{}{Mit tuggya Bishopró'?}
{203}{}{Mongya valamit Kong Resszus?}
{204}{}{Én még kérdezze.}
{205}{}{Mi a helyzet a Bishopokkal?}
{206}{}{Meséljen a Kongresszusról, kérem!}
{207}{}{Értem. Mondana még valamit nekem?}

{208}{tand19}{Lehet, hogy beszélek a kígyóhoz, de ne várja el, hogy magamhoz ölelem. Ha találkoznak, nyugodtan mondja ezt el nekik.}
{209}{}{Én hallani ÚKK üzletelje Bishopék.}
{210}{}{Oké. Én kellje tunni több.}
{211}{}{Azt rebesgetik, hogy az ÚKK lepaktál a Bishopokkal.}
{212}{}{Oké, térjünk át másra...}

{213}{tand20}{Hiába próbál az ember titkot tartani errefelé... Nos, tárgyalásokat folytatunk New Renóval az ÚKK-hoz való csatlakozás ügyében. Nem ártana, ha befolyásuk lenne az olyan helyekre, mint például Menedékváros.}
{214}{}{Érteni.}
{215}{}{Értem.}

{216}{tand21}{A többség szerint együtt kell mûködnünk New Renóval így vagy úgy. Azonban Westin és a marhatenyésztõk New Renót vádolják a Reddingbe irányuló marhaszállítmányok dézsmálásával.}
{217}{}{Hümm.}
{218}{}{Ki Westin?}
{219}{}{Értem.}
{220}{}{Ki ez a Westin?}

{221}{tand22}{Westin tanácsos? Az egyik legnagyobb brahmintenyésztõ a városban. Ha beszélgetnének, ne említse New Renót! Minden bizonnyal ideges lenne tõle. Abban az esetben, ha állandó munkát akar nála... na, nem mintha olyasféle embernek tûnne... jól sejtem?}
{222}{}{Háááát...}

{223}{tand23}{Makacs, mint egy öszvér... de azért jó ember. Miért kérdi?}
{224}{}{Kíváncsi lenni munka ügybe'.}
{225}{}{Kíváncsi lenni munka ügybe'.}
{226}{}{Kíváncsi vagyok, lehet-e náluk munkát kapni.}
{227}{}{Kíváncsi vagyok, lehet-e náluk munkát kapni.}

{228}{tand24}{Úgy tûnik, máris van mit aprítania a levesbe...}
{229}{}{Oké. Felejtsük el...}
{230}{}{Hát igen, ez már szent igaz...}

{231}{tand25}{Amióta Westin meghalt, Carlson bevette magát az irodájába. Valószínûleg nem szívesen fogadná magát, de azért kérdezzen rá az embereinél!}
{232}{}{Oké.}

{233}{tand26}{Figyeljen ide... Nagyon sok ember, beleértve engem is, szereti a vén Carlsont, mégha nem is értünk egyet New Reno kérdésében. Ha történne vele valami, egyáltalán nem repesnénk az örömtõl. Ha bárki azon törné a fejét, hogy az élete könnyebb lenne Carlson nélkül, nagyon-nagyon téved. Érthetõ?}
{234}{}{Jaja. Én érteni.}
{235}{}{Igen, érthetõ...}

{236}{tand27}{Ó, Teremtõm, ez már nagyon rég volt! Alig emlékszem, ki is voltam akkortájt. Azt hiszem, csak egy naiv leányzó. Az ember, akit Menedéklakónak hív, még él?}
{237}{}{Õ lenni õs. Él õ lelkekkel. Bennem.}
{238}{}{A Menedéklakó az õsöm. Emléke bennem él tovább...}

{239}{tand28}{Igen... bizony van hasonlóság... ugyanaz a tûz... mindig féltem attól, hogy a csontjai már réges-rég kint porladnak a sivatagban.}
{240}{}{Én akarja hallani maga történet.}
{241}{}{Szeretném meghallgatni a történetét.}

{242}{tand29}{Gondoltam... (sóhajt) Nos, eléggé fiatalka voltam, amikor annak idején találkoztunk. Létezett akkoriban egy fosztogató banda, a Khan-ok bandája. Foglyul ejtettek. A dolgok már épp kezdtek eléggé rosszra fordulni, amikor ez az idegen feltûnt, és megmentett. A Menedéklakó... személyesen...}
{243}{}{Menedéklakkó sok kalandba vót.}
{244}{}{A Menedéklakó sok kalandot megélt.}

{245}{tand30}{Régen irigyeltem érte. Kalandos életet szerettem volna, de végülis ittragadtam és amikor apám meghalt, én lettem a polgármester. Azóta is én vezetem ezt a várost, és én építettem ki az ÚKK-t. Végülis egész jó élet kerekedett ki belõle.}
{246}{}{Törzsfõ bódog ha tunni hogy még élni. Bocsássa, de kérdezni még.}
{247}{}{A Törzsfõ boldog lesz, ha megtudja, hogy maga még mindig él. Elnézést, de még többet kellene tudnom.}

{248}{tand31}{Régen Shady Sands volt, jelenleg ÚKK-nak hívják. Új Kalifornia Köztársaság. Meggyõzõ név, nem igaz?}
{249}{}{Mesélje ÚKK-t!}
{250}{}{Én kérdezze mástot.}
{251}{}{Kérem, beszéljen még az ÚKK-ról!}
{252}{}{Hadd kérdezzek valami mást!}

{253}{tand32}{Ó, Teremtõm, örökké tudnék beszélni errõl, de nincs rá elég idõm. Tessék, itt egy hololemez az ÚKK-ról. Azért készítettük, hogy terjesszük a nézeteinket.}
{254}{}{Öö, köszönet...}

{255}{tand33}{Szóval a végén még megegyezünk velük... Esetleg meggyõzhetném a Kongresszust, hogy különféle árukat és technológiát kapjanak tõlünk. Biztos benne, hogy be tudunk jutni a Menedékbe?}
{256}{}{Én biztos. Csavarogók lenni ottan de én füstölni kifele.}
{257}{}{Eléggé biztos vagyok benne. Volt néhány csavargó ott, de kifüstöltem õket.}

{258}{tand34}{Mindig hittem abban, hogy a jó munkáért jó fizetség jár. A titkárom majd vázolja a teendõket.}
{259}{}{Én találni probléma. Nézze lemeztet! Kém lenni ÚKK-ba.}
{260}{}{Én kellje tunni még valami. Mi lenni, ha találom megfele 13-as Menedék?}
{261}{}{Attól tartok, van itt még egy probléma. Ha megnézi ezt a hololemezt, láthatja, hogy egy kém fészkelte be magát az ÚKK soraiba.}
{262}{}{Volna még valami. Mit szólna, ha azt mondanám, megtaláltam a 13-as Menedéket?}
{263}{}{Köszönöm.}

{264}{tand35}{Fenébe is... az egyetlen ember, aki mindezt tudhatta, Feargus! Nem akarok találgatni, de talán Günthernek nem ártana tudni errõl.}
{265}{}{Én mondani elfele. Menek máris.}
{266}{}{Én kellje tunni még valami. Mi lenni, ha találom megfele 13-as Menedék??}
{267}{}{Csak még egy dolog... mi lenne, ha azt mondanám, hogy megtaláltam a 13-as Menedéket}
{268}{}{Beszélek vele. Minden jót!}

{269}{tand36}{Szóval jöhet az üzlet, mi? Jól van. Ötszáz, ha végzett a feladattal. Nem állok neki alkudozni, szóval fogadja el a munkát vagy ne vesztegesse az idõmet!}
{270}{}{Én elfogaggya, de kérdezni elõtte}
{271}{}{Én nem érdekelni.}
{272}{}{Elfogadom, de elõbb információkra van szükségem.}
{273}{}{Nem érdekel a dolog.}

{274}{tand37a}{Tandi vagyok, az ÚKK elnöke. Szóval eltángálta a fiamat, Hosst, Dusty bárjában? Talán éppen maga az az ember, aki jókor, jó helyen jár. Nem érdekli egy megbízatás?}
{275}{tand37b}{Tandi vagyok, az ÚKK elnöke. Szóval maga az a nõ, aki eltángálta a fiamat, Hosst? Ilyen lány kellett volna nekem! Volna egy munkám a számára. Érdekli?}
{276}{}{Talán. Mi lenni megbízatás?}
{277}{}{Akár... mi lenne a feladat?}

{278}{tand38}{Tandi vagyok, az Új Kalifornia Köztársaság elnöke. Üdvözöljük Shady Sandsben. Szerfelett meggyõzõ dolgokat hallottam magáról. Nem akarok köntörfalazni. Volna itt egy megbízatás, amirõl beszélnünk kéne.}
{279}{}{Öö, oké.}
{280}{}{Rendben, mit tehetek magukért?}

{281}{tand39}{Szóval visszajött... Érdekli a munka, vagy sem?}
{282}{}{Nem.}
{283}{}{Érdekel.}

{284}{tand40}{Szóval visszajött, idegen? Teljesítette a feladatot? Megvan a hozzáférés a Menedékhez?}
{285}{}{Én dolgozza rajta. Üdv!}
{286}{}{Volni ottan. Fõdfoglalók akarja eggyesség. Maguk taníccsa, segíccsep, õk aggya Menedék.}
{287}{}{Volni ottan. Lenni alkatosrészek megfele.}
{288}{}{Volni ottan. Fõdfoglalók akarja eggyesség. Maguk taníccsa, segíccsep, õk aggya Menedék. Lenni itten alkatosrészek szintén.}
{289}{}{Még dolgozom az ügyön. Minden jót!}
{290}{}{A nagy részét már elintéztem. A földfoglalók egyezséget ajánlanak. Ha maguk segítenek önellátóvá válniuk, hozzáférést biztosítanak a Menedékhez.}
{291}{}{Már voltam ott, és nálam vannak a kért számítógép-alkatrészek.}
{292}{}{A nagy részét már elintéztem. A földfoglalók egyezséget ajánlanak. Ha maguk segítenek önellátóvá válniuk, hozzáférést biztosítanak a Menedékhez. Ezenkívül a kért alkatrészek is itt vannak.}

{293}{tand41}{A mennydörgõs mindenit! Ne fecsérelje a drága idõmet!}
{294}{}{Elnézést.}

{295}{tand42}{Megtalálta a 13-as Menedéket? Ez rengeteg problémánkat megoldja! Merre van?}
{296}{}{Öö, mielõtte mondok elfele, vóna még probléma Menedékkel.}
{297}{}{Én rajzojja térképtet. Tessék.}
{298}{}{Mielõtt elmondanám, volna még egy aprócska gond a Menedékkel kapcsolatban.}
{299}{}{Rajzoltam egy térképet, a maguké.}
{300}{}{Nem vagyok én olyan ember, aki csak úgy ingyen átad egy aranybányát. Húsz rongyot akarok, különben búcsút inthet neki.}

{301}{tand43}{Micsoda?}
{302}{}{Tele lenni Halá'karom. Okosak. Beszé'nek.}
{303}{}{Tele van intelligens halálkaromokkal. Még beszélni is tudnak.}

{304}{tand44a}{Hogyne. (Megrázza a fejét) Teremtõm, maga ostobább, mint Hoss valaha is volt! (sóhajt) Az ajtót ott találja!}
{305}{tand44b}{Hogyne. (Megrázza a fejét) Jól van akkor, ne fecséreljük egymás idejét! (sóhajt) Az ajtót ott találja.}
{306}{}{Én menek mostan.}
{307}{}{Rendben. Már itt sem vagyok.}

{308}{tand45}{Ezzel bónuszt nyert magának. A titkárom lerendezi a dolgot.}
{309}{}{}
{310}{}{Köszönöm.}

{311}{tand46}{Maga aztán egy igazi kufár, de nem bánom, keresse fel Günthert! Õ majd elboronálja az ügyet.}
{312}{}{Köszönöm.}

{313}{tand47}{Fiúk, tûntessétek el ezt a rakás brahminköpetet az irodámból! Itt az idõ, hogy eltûnjön innen, idegen!}
{314}{}{[Kész]}

{315}{tand14b}{Apám és Seth évekig keresgéltek, hogy megtalálják a 13-as Menedéket. Folyton azt mondogatták, hogy nyugatra van innen, mégis meghaltak a keresés közben. Ha valaki megtalálná a 13-ast, nagyobb hasznot hajtana nekünk, mint a 15-ös.}

# Float
{316}{}{Ezügyben beszéljen a titkárommal, Güntherrel!}