# Dialog Editor last position: 103
{100}{}{Fából készült ajtó.}
{101}{}{Acélból készült ajtó.}
{102}{}{Egy erõs ajtót látsz zárral (tolvajkulccsal nyitható) és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve. Talán ki tudod feszíteni. }
{103}{}{Egy erõs ajtót látsz zárral és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve. Talán ki tudod feszíteni. }
{104}{}{Egy erõs ajtót látsz minden látható zárszerkezet nélkül és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve. Talán ki tudod feszíteni. }
{105}{}{Egy erõs ajtót látsz régi rozsdás zárral és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve. Talán ki tudod feszíteni. }
{106}{}{Egy erõs ajtót látsz zárral (tolvajkulccsal nyitható) és egy csapda van az ajtófélfába erõsítve. Talán ki tudod feszíteni. }
{107}{}{Egy erõs ajtót látsz zárral és egy csapda van az ajtófélfába erõsítve. Talán ki tudod feszíteni.}
{108}{}{Egy erõs ajtót látsz minden látható zárszerkezet nélkül és egy csapda van az ajtófélfába erõsítve. Talán ki tudod feszíteni. }
{109}{}{Egy erõs ajtót látsz régi rozsdás zárral és egy csapda van az ajtófélfába erõsítve. Talán ki tudod feszíteni. }
{110}{}{Egy erõs ajtót látsz zárral (tolvajkulccsal nyitható) és egy vágó huzalt az ajtófélfán. Talán ki tudod feszíteni. }
{111}{}{Egy erõs ajtót látsz zárral és egy egyszerû drótot az ajtófélfán. Talán ki tudod feszíteni. }
{112}{}{Egy erõs ajtót látsz minden látható zárszerkezet nélkül és egy egyszerû drótot az ajtófélfában, amit esetleg ki tudnál feszíteni. }
{113}{}{Egy erõs ajtót látsz régi rozsdás zárral és egy vágó drót van az ajtófélfába erõsítve. Talán ki tudod feszíteni. }
{114}{}{Egy erõs ajtót látsz zárral (tolvajkulccsal nyitható). Talán ki tudod feszíteni. }
{115}{}{Egy erõs ajtót látsz zárral. Talán ki tudod feszíteni. }
{116}{}{Egy erõs ajtót látsz minden látható zárszerkezet nélkül. Talán ki tudod feszíteni. }
{117}{}{Egy erõs ajtót látsz régi rozsdás zárral. Talán ki tudod feszíteni. }
{118}{}{Egy erõs ajtót látsz zárral (tolvajkulccsal nyitható) és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve.}
{119}{}{Egy erõs ajtót látsz zárral és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve.}
{120}{}{Egy erõs ajtót látsz minden látható zárszerkezet nélkül és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve.}
{121}{}{Egy erõs ajtót látsz régi rozsdás zárral és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve.}
{122}{}{Egy erõs ajtót látsz zárral (tolvajkulccsal nyitható) és egy csapdát az ajtófélfán.}
{123}{}{Egy erõs ajtót látsz zárral és egy csapdát az ajtófélfán.}
{124}{}{Egy erõs ajtót látsz minden látható zárszerkezet nélkül és egy csapdát az ajtófélfán.}
{125}{}{Egy erõs ajtót látsz régi rozsdás zárral és egy csapda van az ajtófélfára erõsítve.}
{126}{}{Egy erõs ajtót látsz zárral (tolvajkulccsal nyitható) és egy vágó drótot az ajtófélfán.}
{127}{}{Egy erõs ajtót látsz zárral és egy egyszerû drótot az ajtó félfán.}
{128}{}{Egy erõs ajtót látsz minden látható zárszerkezet nélkül és egy egyszerû drótot az ajtó félfában.}
{129}{}{Egy erõs ajtót látsz egy régi rozsdás zárral és egy egyszerû drótot az ajtófélfában.}
{130}{}{Egy erõs ajtót látsz zárral (tolvajkulccsal nyitható).}
{131}{}{Egy erõs ajtót látsz zárral.}
{132}{}{Egy erõs ajtót látsz minden látható zárszerkezet nélkül.}
{133}{}{Egy erõs ajtót látsz régi rozsdás zárral.}
{134}{}{Egy sérült ajtót látsz zárral (tolvajkulccsal nyitható) és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve.}
{135}{}{Egy sérült ajtót látsz zárral és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve.}
{136}{}{Egy sérült ajtót látsz minden látható zárszerkezet nélkül és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve.}
{137}{}{Egy sérült ajtót látsz régi rozsdás zárral és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve.}
{138}{}{Egy sérült ajtót látsz zárral (tolvajkulccsal nyitható) és egy csapda van az ajtófélfába erõsítve.}
{139}{}{Egy sérült ajtót látsz zárral és egy csapda van az ajtófélfába erõsítve.}
{140}{}{Egy sérült ajtót látsz minden látható zárszerkezet nélkül és egy csapda van az ajtófélfába erõsítve.}
{141}{}{Egy sérült ajtót látsz zárral és egy csapda van az ajtófélfába erõsítve.}
{142}{}{Egy sérült ajtót látsz zárral (tolvajkulccsal nyitható) és egy vágó drótot az ajtófélfában.}
{143}{}{Egy sérült ajtót látsz zárral és egy elszakadt drótot az ajtófélfán.}
{144}{}{Egy sérült ajtót látsz minden látható zárszerkezet nélkül és egy elszakadt drótot az ajtófélfán.}
{145}{}{Egy sérült ajtót látsz egy régi rozsdás zárral és egy szakító drótot az ajtófélfán.}
{146}{}{Egy sérült ajtót látsz zárral (tolvajkulccsal nyitható).}
{147}{}{Egy sérült ajtót látsz zárral.}
{148}{}{Egy sérült ajtót látsz minden látható zárszerkezet nélkül.}
{149}{}{Egy sérült ajtót látsz régi rozsdás zárral.}
{150}{}{Egy régi ajtót látsz zárral (tolvajkulccsal nyitható) és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve.}
{151}{}{Egy régi ajtót látsz zárral és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve.}
{152}{}{Egy régi ajtót látsz minden látható zárszerkezet nélkül és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve. }
{153}{}{Egy régi ajtót látsz régi rozsdás zárral és egy erõs robbanóanyagból készített csapda van az ajtófélfába erõsítve.}
{154}{}{Egy régi ajtót látsz zárral (tolvajkulccsal nyitható) és egy csapda van az ajtófélfába erõsítve.}
{155}{}{Egy régi ajtót látsz zárral és egy csapda van az ajtófélfába erõsítve.}
{156}{}{Egy régi ajtót látsz minden látható zárszerkezet nélkül és egy csapda van az ajtófélfába erõsítve.}
{157}{}{Egy régi ajtót látsz régi rozsdás zárral és egy csapda van az ajtófélfába erõsítve.}
{158}{}{Egy régi ajtót látsz zárral (tolvajkulccsal nyitható) és egy szakító drótot az ajtófélfában.}
{159}{}{Egy régi ajtót látsz zárral és egy elszakadt drótot az ajtófélfán.}
{160}{}{Egy régi ajtót látsz minden látható zárszerkezet nélkül és egy elszakadt drótot az ajtófélfán.}
{161}{}{Egy régi ajtót látsz régi rozsdás zárral és egy szakító drótot az ajtófélfán.}
{162}{}{Egy régi ajtót látsz zárral (tolvajkulccsal nyitható).}
{163}{}{Egy régi ajtót látsz zárral.}
{164}{}{Egy régi ajtót látsz minden látható zárszerkezet nélkül.}
{165}{}{Egy régi ajtót látsz régi rozsdás zárral.}
{166}{}{Mûködésbe hoztad a csapdát és }
{167}{}{[x] ÉP sérülést szenvedtél.}
{168}{}{ mûködésbe hozta a csapdát és }
{169}{}{[x] ÉP sérülést szenvedett.}
{170}{}{Sikerült kinyitnod a zárat.}
{171}{}{Képességek hiányában összetörted a zárat ezen az ajtón.}
{172}{}{Nem sikerül kinyitnod a zárat.}
{189}{}{Ügyesen bezártad az ajtót.}
{190}{}{Nem tudod bezárni az ajtót.}
{194}{}{Egy csapdát találtál az ajtón.}
{195}{}{Nem voltál képes csapdát találni az ajtón.}
{196}{}{Szakképzetten hatástalanítottad a csapdát.}
{198}{}{Nem tudtad hatástalanítani a csapdát.}
{173}{}{ ügyesen kinyitotta a zárat.}
{174}{}{ képességek hiányában összetörte a zárat ezen az ajtón.}
{175}{}{ nem tudta kinyitni a zárat.}
{191}{}{ bezárta az ajtót.}
{192}{}{ nem tudta bezárni az ajtót.}
{199}{}{ talált egy csapdát az ajtón.}
{200}{}{ nem volt képes csapdát találni az ajtón.}
{201}{}{ szakképzetten hatástalanította a csapdát.}
{202}{}{ nem tudta hatástalanítani a csapdát.}
{176}{}{Széttörted a zárat az ajtón.}
{177}{}{Miközben megpróbáltad széttörni a zárat az ajtón, meghúzódott a hátad és [x] ÉP-t sérültél.}
{178}{}{Miközben megpróbáltad széttörni a zárat az ajtón, meghúzódott a hátad és }
{179}{}{[x] ÉP-t sérültél.}
{180}{}{Túl gyenge vagy, hogy széttörd a zárat.}
{181}{}{ széttörte az ajtón lévõ zárat.}
{182}{}{ háta meghúzódott, miközben megpróbálta széttörni a zárat az ajtón és [x] ÉP-t sérült.}
{183}{}{ háta meghúzódott, miközben széttörte a zárat az ajtón és }
{184}{}{[x] ÉP-t sérült.}
{185}{}{ túl gyenge, hogy széttörje a zárat az ajtón.}
{186}{}{ háta meghúzódott, miközben megpróbálta széttörni a zárat az ajtón és [x] ÉP-t sérült.}
{187}{}{ háta meghúzódott, miközben megpróbálta széttörni a zárat az ajtón és }
{188}{}{[x] ÉP-t sérült.}
{193}{}{Ez még csak meg sem karcolta az ajtót.}
{203}{}{Az ajtó zárva van.}
{204}{}{Észreveszel egy csapdát az ajtón.}
{205}{}{ észrevett egy csapdát az ajtón.}
{206}{}{Nem tudsz csapdát helyezni az ajtóra, mert az ajtó nyitva van.}
{207}{}{ nem tud csapdát helyezni az ajtóra, mert az ajtó nyitva van.}
{208}{}{Tökéletes csapdát helyeztél az ajtóra.}
{209}{}{Nem tudod rendesen felszerelni a csapdát az ajtóra.}
{210}{}{ tökéletes csapdát helyezett az ajtóra.}
{211}{}{ nem tudja rendesen felszerelni a csapdát az ajtóra.}
{212}{}{Ez az ajtó az istennek nem akar kinyílni.}
{213}{}{Ez az ajtó nem mozdul.}