# Dialog Editor last position: 5
{100}{}{Ennek a korosodó embernek mély ráncok barázdálják az arcát. Ha észre is vette fürkészõ  tekinteted, nem látszik rajta.}
{101}{}{Cassidy.}
{102}{}{Ennek a korosodó embernek mély ráncok barázdálják az arcát. Biccent feléd.}
{103}{}{Még nem láttak errefelé, idegen. Cassidy-nek hívnak, én vagyok itt a tulaj. Mit tehetek érted?}
{104}{}{Látom, ismét itt a titokzatos idegen. Miben segíthetek?}
{105}{}{Pá... linka?}
{106}{}{[Elbattyogsz]}
{107}{}{Menedéket keresem.}
{108}{}{Na? Meggondoltad magad? Csatlakozol hozzám?}
{109}{}{Mit lehet itt inni?}
{110}{}{Történt valami különös mostanában?}
{111}{}{Kösz, csak benéztem.}
{112}{}{Túl sokszor vertek kupán igaz, barátom? Bocs, de én nem beszélek gyogyósul.}
{113}{}{O-gyós?}
{114}{}{Menedék? Az egyetlen általam ismert Menedék itt van a városban. Egy bazi nagy lyuk, el sem lehet téveszteni.}
{115}{}{Szomjas vagyok. Adnál valamit inni?}
{116}{}{Megtalálom. Egyébként történt valami különös mostanában?}
{117}{}{Kösz az útbaigazítást. Viszlát!}
{118}{}{A sör 20 dolcsi, egy pohár viszki 30, extrák nincsenek. Mivel szolgálhatok?}
{119}{}{Információval. Egy Menedéket keresek.}
{120}{}{Kérek egy sört.}
{121}{}{Egy viszki jól esne.}
{122}{}{Egy sztorival. Történt valami különös mostanában?}
{123}{}{Semmivel, köszönöm. Mennem kell.}
{124}{}{Hosszú lenne a lista, barátom. Menedékváros "érdekes" egy hely, jobban teszed, ha messzirõl kerülöd.}
{125}{}{Ha te mondod... most azonban innék valamit.}
{126}{}{Fontos dolgom van, egy Menedéket keresek.}
{127}{}{Utálsz itt lenni? Szerintem nem rossz hely ez.}
{128}{}{Kösz a jó tanácsot, most mennem kell.}
{129}{}{Tessék, hajtsd fel! Talán ez segít elfelejteni, hogy hol is vagy.}
{130}{}{Nekem tetszik ez a hely.}
{131}{}{Kösz az italt. Mennem kell.}
{132}{}{Most ugye csak viccelsz? Ezek szerint te épp szunyókáltál, amikor a rablótámadás történt.}
{133}{}{Rablótámadás?!}
{134}{}{Az bizony. Stark õrmester vezetésével bejött ide egy õrjárat, hogy "illegális anyagok" után kutasson. Bezúzták a raktárajtót, felforgatták a helyiséget és a vicces kedvû fiúk még néhány vendégem orrát is beverték.}
{135}{}{Ejha. Mi történt utána?}
{136}{}{Sajnálattal hallom, de most mennem kell.}
{137}{}{Elhurcoltak egy Joshua nevû fickót, amiért bátorkodott visszaütni, én meg kaptam egy zsíros büntetést... na, ezt figyeld... mert VALÓDI viszkit találtak a helyszínen! Itt ez nem tilos. Mocskok!}
{138}{}{Elképesztõ! Folytasd csak!}
{139}{}{Sajnos mennem kell. Késõbb még találkozunk.}
{140}{}{Az önérzetem megtaposva, de nem ez a legnagyobb baj. Anyagilag is lesújtott az eset. Összetörték a készleteimet és az eredeti ár háromszorosáért tudtam csak pótolni. A tönk szélén állok, barátom.}
{141}{}{Legalább sok vendég jár ide? Van hasznod?}
{142}{}{Nehéz idõket élünk. Viszlát!}
{143}{}{Sajnos a Polgárok nem sokat isznak, a csórók meg állandóan hepciáskodnak az árak miatt. Esküszöm, a következõ potyalesõnek rojtosra rugdosom a seggét.}
{144}{}{Miért nem lépsz le, ha ennyire utálod ezt a helyet?}
{145}{}{Megértelek, barátom, de dolgom van. Egy Menedéket keresek.}
{146}{}{Most mennem kell. Viszlát!}
{147}{}{Rossz a szívem és szíverõsítõ injekciókra van szükségem, hogy ketyegjen még egy ideig a vekker. Ez a város az egyetlen hely a környéken, ahol normális az egészségügyi ellátás. Ezért telepedtem le itt.}
{148}{}{Értelek, de nincs mit szépíteni a dolgon. Befuccsoltál!}
{149}{}{Bocs, de kevés az idõm. Tudnál segíteni? A Menedéket keresem.}
{150}{}{Remélem, a jövõben jobb sorod lesz. Viszlát!}
{151}{}{Igen, tudom. Emiatt akarom becsukni a boltot és elhagyni a várost. A Polgárok meg... [közelebb hajol és a füledbe súgja]... kinyalhatják a seggem! Tudod, ahogy kell. Dobszó mellett a Tanácsháza díszterén.}
{152}{}{Zárd be ezt a kócerájt, és lépj le! Ne habozz!}
{153}{}{Sajnálom, de most már tényleg mennem kell.}
{154}{}{Menjek a pusztába? Önként? Na, ja, elegem van ebbõl a helybõl, de azért hülye nem vagyok.}
#nekem igy jobbnak tunik
{155}{}{Én is a pusztába tartok, csatlakozz hozzám!}
{156}{}{Értem. Ahogy akarod. Most mennem kell, viszlát!}
{157}{}{Ne vedd sértésnek, barátom, de nem úgy nézel ki, mint aki egy brahminon kívül bármire is vigyázni tudna. A puszta megenne reggelire.}
{158}{}{Nem, kösz, nem utazom rabszolga-kereskedõkkel. Tudod, meg van az a rossz szokásuk, hogy eladják a társukat, ha elfogyott a pénzük.}
{159}{}{Ne vedd zokon, de úgy nézel ki, mint aki fél lábbal a sírban, a másikkal meg a pokolban áll. Így is épp elég rossz a hírem, nem szeretnék tovább rontani rajta.}
{160}{}{Köszönet a lehetõségért, de úgy látom, nélkülem is épp elegen vagytok.}
{161}{}{Rendben. Sok szerencsét!}
{162}{}{Vedd úgy, hogy nem kérdeztem semmit, seggfej! Maradj csak bártulaj ebben a lepattant kricsmiben!}
{163}{}{Felejtsd el! Te bajod.}
{164}{}{Mi van? EZ KOMOLY?}
{165}{}{Persze, hogy az. Nem vagy már fiatal, de biztos vagyok benne, hogy hasznos útitárs leszel. Nos?}
{166}{}{Bocs, felejtsd el, amit mondtam! Beteg szívvel nem húznád sokáig.}
{167}{}{Rendben, benne vagyok. Induljunk!}
{168}{}{Gyerünk!}
{169}{}{ }
{170}{}{ }
{171}{}{Mi van? Már megint azzal az "el kell mondanom valamit, ami nem fog tetszeni" tekintettel nézel rám.}
{172}{}{Igen?}
{173}{}{Mi van? Már megint azt a "visszaélek a hatalmammal" tekintetet látom.}
{174}{}{Feltennék néhány kérdést.}
{175}{}{Úgy látom, megsérültél. Használj egy stimpakkot és gyógyítsd meg magad!}
{176}{}{Cassidy, itt kéne várnod, amíg visszajövök!}
{177}{}{Tedd el a fegyvert!}
{178}{}{Maradj szorosan mögöttem!}
{179}{}{Ne menj túl messzire!}
{180}{}{Szét kéne szóródni egy kicsit!}
{181}{}{Gyerünk, Cassidy, ideje indulni!}
{182}{}{Semmi, felejtsd el!}
{261}{}{Azt akarod, hogy repítsek golyót Myron fejébe, ugye? Nem probléma. Egy szavadba kerül.}
{262}{}{Mire vagy kíváncsi?}
{263}{}{Miért akarod kinyírni Myront?}
{264}{}{Milyen fegyverekhez értesz?}
{265}{}{Igazából valami mást kéne csinálnod.}
{266}{}{Igazából azt akarom, hogy..}
{267}{}{Felejtsd el! Menjünk!}
{268}{}{Neee... ne bántsd Myront! Legalábbis ma ne. Majd szólok...}
{269}{}{Jól bánok a kézifegyverekkel, különösen a puskákkal, ezek a kedvenceim. Azért a pisztolyokkal is elboldogulok.}
{270}{}{Valami más?}
{271}{}{Rendben. Lenne még egy kérdésem.}
{272}{}{Értem.}
{273}{}{Ha valakitõl valami személyes dolgot szeretnél megtudni, csak passzolj ide egy bokszert és én majd kicsipkézem az arcát az öklömmel.}
{274}{}{Nagyszerû! Egyéb?}
{275}{}{Rendben. Lenne még néhány kérdésem.}
{276}{}{Kösz, Cassidy.}
{277}{}{Ezen kívül elég jól bánok a lándzsával. A haverokkal radskorpiókra vadásztunk annak idején. Én élek, õk már nem. Ez talán mond valamit.}
{278}{}{Én is szeretem a lándzsákat.}
{279}{}{Világos. Kérdeznék még valamit.}
{280}{}{Erre voltam kíváncsi. Kösz.}
{281}{}{Mondod te. Csak ne hívj törzsbélinek, és jól megleszünk!}
{282}{}{Azért nem szeretném, ha összetévesztenél az öreg Csontorrúval hehe... még nem láttam törzsbélit, aki ilyen bazi nagy csontot rakott volna az orrába.}
{283}{}{A lándzsa jó fegyver. Sok törzsbéli barátom használja.}
{284}{}{Tudtad, hogy én is "törzsbéli" vagyok?}
{285}{}{Valami mást szeretnék.}
{286}{}{Rendben, Ez minden.}
{287}{}{Na, ne szórakozz az öreg Cassidy-vel! Nem vagy te törzsbéli.}
{288}{}{De, az vagyok.}
{289}{}{Mindegy. Lenne még valami.}
{290}{}{Felejtsd el! Nem akarok belebonyolódni.}
{291}{}{Rendben... a fenébe is, bocsánat. Nem akartalak megbántani.}
{292}{}{Persze, tudom, semmi baj. Kérdeznék valami mást.}
{293}{}{Menjünk!}
{294}{}{Mielõtt folytatnánk elárulnád, mit csinálunk mi odakint? Csak úgy fel-le bóklászunk, vagy van valami konkrét célunk is?}
{295}{}{Az ÉLET-et keressük. Az Édenkert Létrehozást Elõsegítõ Táskát. A falumnak szüksége van rá.}
{296}{}{Bemegyünk a Menedékbe és visszavisszük az ÉLET-et a falumba.}
{297}{}{A falumat elpusztították. Azt próbálom kideríteni, hogy mi történt.}
{298}{}{Az ilyesmit táskába rakják egyáltalán? Ezt elég nehéz elhinni, barátom, de hát te tudod. Mehetünk.}
{299}{}{Minden rendben, csak érdeklõdtem.}
{300}{}{Szívesen csinálok pár extra-lyukat néhány bandita fejébe. Egy kis magán-igazságszolgáltatás senkinek sem árt... legalábbis nem nekem.}
{301}{}{Rendben. Induljunk!}
{302}{}{Amiket az a suttyó mond, nem való bizonyos füleknek.}
{303}{}{Például a nõknek...}
{304}{}{Nocsak, Cassidy, nem is  tudtam, hogy ilyesmivel is törõdsz. Repes a szívem.}
{305}{}{Valóban?}
{306}{}{Tudod, te is sokat káromkodsz, Cassidy.}
{307}{}{Nekem mondod? Menjünk!}
{308}{}{Valóban, de legalább stílusosan. Bár igaz, egy kicsit mocskos szájú.}
#itt esetleg lehet valami gixer 308
{309}{}{És az sem tetszik, ahogy rád néz.}
{310}{}{Nocsak, Cassidy, nem is tudtam, hogy ilyesmivel is törõdsz. Repes a szívem.}
{311}{}{Valóban?}
{312}{}{Nekem mondod? Menjünk!}
{313}{}{Állj csak meg egy pillanatra, nem értettem...}
{314}{}{Azt mondom, hogy ennek a kis seggarcú baromnak egyszer még kicsengetnek. Csak egy percig maradjunk kettesben a pusztában.}
{315}{}{Az élet bizony szigorú tanár. Lenne még pár kérdésem.}
{316}{}{Nos, már úgysincs sok hátra neki. Én nem aggódnék miatta.}
{317}{}{Csak nyugodj meg, Cassidy! Hagyd békén Myront!}
{318}{}{Utálom ezt a helyet.}
{319}{}{Reméltem, hogy eltûzünk errõl a helyrõl.}
{320}{}{Seggarcúak Városa.}
{321}{}{Ez a hely rosszabb, mint Menedékváros.}
{322}{}{Jó, hogy ellenõriztem a fegyvereimet, mielõtt bejöttem ide.}
{323}{}{Ha elpatkolok, ne itt temessetek el!}
{324}{}{Vigyázz magadra, a helybeliek nem túl barátságosak.}
{325}{}{Nahát... sosem hittem volna, hogy egyszer még látni fogom San Franciscót.}
{326}{}{Nem hittem volna, hogy egy ilyen öreg trottyost mint én, ennyi ideig magadnál tartasz. Csináljuk meg ezt a melót és menjünk haza!}
{327}{}{Redding egy bányaváros, elsõsorban aranyat termelnek. Sok karavánt küldtek már Menedékvárosba.}
{328}{}{Broken Hills egy bányaváros, leginkább uránt hoznak a felszínre. Durva hely is tud lenni, úgyhogy vigyázz magadra!}
{329}{}{Egy kis méreg szaladgál a szervezetemben. Van nálad ellenméreg?}
{330}{}{Neonreklám lett belõlem. Adnál egy RadX-et?}
{331}{}{Rosszul vagyok. Szükségem lenne egy stimpakkra.}
{332}{}{Ne üsd bele az orrod, Myron! Figyellek!}
{333}{}{Lépj ki, Myron és kinyírlak!}
{334}{}{A francba, Lenny, ideje lenne már megfürödnöd. Vagy inkább fertõtlenítsd magad!}
{335}{}{Ghoul-fiú, menj már egy kicsit odébb! Fúúúúúú, te aztán bûzlesz!}
{336}{}{Ez a legrémisztõbb kutya, amit valaha láttam.}
{337}{}{Jól van, kutyus. Cassidy  a barátod, oké?}
{338}{}{Vajon mit esznek a kiberkutyák? Valószínûleg embereket.}
{339}{}{Ha ez a kiberkutya belekap a lábamba, kicsinálom.}
{340}{}{Örülök, hogy több milliót csináltak ezekbõl az izékbõl, mielõtt ledobták a bombát.}
{341}{}{Kösz, barátom.}
{342}{}{Remélem, ezek a stimpakkok nem ártanak meg a szívemnek.}
{343}{}{Mi a... ?! Úristen, a szívem... én... *hrrrkkk*}
{344}{}{Bocs, csak gyönyörködtem a kilátásban.}
{345}{}{A fenébe, én meg csak álldogálok itt.}
{346}{}{Bocsánat, barátaim. Nem akartam elállni az utat.}
{347}{}{Ez már valami. Köszönöm szépen!}
{348}{}{*Hukk* Hehehe... Semmi sem serkenti annyira a vérkeringést, mint a jó öreg tüzes víz.}
{349}{}{Kösz. A pokolba is, innod kéne egy kortyot.}
{350}{}{Az a Menedék. Bazi nagy egy izé, mi?}
{351}{}{Azt akarod, hogy megint csatlakozzak hozzád?}
{352}{}{Én kész vagyok, csak szólj!}
{353}{}{Biztos ne segítsek?}
{354}{}{Alig várom, hogy induljunk.}
{355}{}{Elszívnék egy cigit.}
{356}{}{Apám egy háború elõtti képregény-figura után nevezett el. Azt mondta, az is egy mogorva fickó volt.}
{357}{}{Jó újra úton lenni. A menedékvárosi élettõl már herótom volt.}
{358}{}{Remélem, a szívem még bírja az utazást.}
{359}{}{Jól esne egy ital.}
{360}{}{Jobb, ha még egyszer átnézem a felszerelésem.}
{361}{}{Rohadt ízületi gyulladás!}
{362}{}{Ha húsz évvel fiatalabb lennék, felderíteném a középnyugatot. Most már túl késõ... szerintem.}
{363}{}{Úgy halottam, középnyugaton több mérföld széles tornádók voltak. Most az egész egy nagy radioaktív szemétgödör.}
{364}{}{Vajon Texas túlélte a háborút?}
{365}{}{Kösz, barátom. Én... húúú... mintha egyre homályosabban látnék.}
{366}{}{Úgy hallottam, ez a cucc okozhat hallucin... húúú... honnan a fenébõl jött elõ ez a rengeteg kígyó?!}
{367}{}{Ha beveszem ezt a cuccot, emlékképek jelennek meg a szemeim elõtt.}
{368}{}{Semmi sem hasonlítható egy jó kis törzsbéli gyógyításhoz.}
{369}{}{Hamarosan szükségem lesz egy pár mankóra és egy tolószékre.}
{370}{}{Cassidy meghalt egy szívrohamban.}
{371}{}{Meggyõzted Cassidy-t, hogy csatlakozzon a csapatodhoz.}
{1000}{}{Rendben, legalább pihenek egy kicsit. Ráfér a gyenge szívemre.}
{1100}{}{Rendben, habár nem ígérem, hogy bajban nem veszem elõ.}
{1200}{}{Rendben, közel maradok hozzád. Támadástól tartasz?}
{1300}{}{Rendben, de azért kissé lemaradok. Legalább így elõnyösebb pozícióban leszek.}
{1400}{}{Rendben, fedezlek. Csak füttyents, és én rohanok!}
{2000}{}{Nem azért, de nem úgy nézel ki, mint aki bárkit vezetni tudna. A pusztaság megenne reggelire.}
{2100}{}{Nem utazom rabszolga-hajcsárokkal. Van egy olyan rossz szokásuk, hogy eladják a társukat, ha elfogyott a pénzük.}
{2200}{}{Úgy nézel ki, mint aki fél lábbal a sírban, a másikkal meg már a pokolban áll. Így is épp elég rossz hírem van, nem szeretnék tovább rontani rajta.}
{2300}{}{Úgy látom, már épp elegen vagytok.}
{2400}{}{Rendben, készen állok.}
{2999}{}{Nos, rendben. Vigyázz magadra!}
{3000}{}{Gyerünk, induljunk!}
{3100}{}{Felejtsd el, seggfej!}
{3200}{}{Felejtsd el! A te bajod.}
{4100}{}{Oké, minden rendben van. Mehetünk.}
{4200}{}{Oké, elég jól összefoltoztál.}
{4300}{}{Jobban vagyok, bár néhány stimpakk jól jönne még.}
{4400}{}{Amit tudtam, használtam, de így is elég szarul vagyok. Ha van, adhatnál még pár stimpakkot,  bár járni már tudok.}
{9999}{}{Feltennék néhány kérdést.}
{10001}{}{Vegyél még néhány stimpakkot és gyógyíts magadon!}
{10002}{}{Cassidy! Várj itt, amíg visszajövök!}
{10003}{}{Tedd el a fegyvert!}
{10004}{}{Maradj közel hozzám!}
{10005}{}{Ne menj túl messzire!}
{10006}{}{Szét kéne szóródnunk!}
{10100}{}{Gyerünk, Cassidy! Ideje indulni.}
{10007}{}{Na, akkor induljunk!}
{20000}{}{Oké, hallgatlak.}
{20001}{}{A felszerelésem? Mi van vele?}
{20002}{}{No problemo. Amúgy is túl meleg van itt ilyen felszereléshez. Úgy izzadtam tõle, mint egy New Reno-i kurva.}
{20003}{}{Próbáljunk más formációt!}
{20004}{}{Beszélnem kell veled a felszerelésedrõl.}
{20005}{}{Felejtsd el! Maradjunk a mostani formációban!}
{20006}{}{Semmi. Nem érdekes.}
{20007}{}{Kérlek, vedd le a páncélodat!}
