# Dialog Editor last position: 5
{100}{}{Õ a csapos.}
{101}{}{Ez a férfi elegáns öltönyt visel. Egyenesen elõre mered, láthatóan tudomást sem vesz a körülötte álldogáló vendégekrõl.}
{102}{}{Õ a csapos.}
{103}{}{Igazi pókerarcnak tûnik. Ha észre is vett, nem látszik rajta.}
{104}{}{Tölthetek egy italt, bajnok?}
{105}{}{Üdvözlöm, bajnok. Kérem, foglaljon helyet!}
{106}{}{Üljön le és pihenjen egy kicsit!}
{107}{}{Jó napot, Kapitány!}
{108}{}{Menedékváros mindenek felett, Kapitány!}
{109}{}{Jó napot, Polgártárs!}
{110}{}{Menedékváros mindenek felett, Polgártárs!}
{111}{}{Egy mutáns! Õrség! Õrség!!!}
{112}{}{Egy ghoul! Õrség! Õrség!!!}
{113}{}{Sajnálom, de a bár nem üzemel éjszaka.}
{114}{}{Zárva vagyunk, elnézést. Csak befejezem a standolást és már indulok is haza.}
#Standolás? Az mi? Nem lehetne inkább: Csak befejezem ezt az anyaglistát...
{115}{}{Nincs hova mennie?}
{116}{}{Nézzék, itt van õ, a bajnok! Mindannyian hallottunk az Enklávé elleni hõstetteirõl. Hozhatok egy italt?}
{117}{}{Glugy-glugy}
{118}{}{[Elbattyogsz]}
{119}{}{Mit lehet itt inni?}
{120}{}{Néhány információra lenne szükségem.}
{121}{}{Csak benéztem. Viszlát!}
{122}{}{"Glugy-glugy" neked is, egyszerû barátom. Kérlek, légy óvatos kint a pusztaságban!}
{123}{}{Hmmm...uhmmm!}
{124}{}{[Elbattyogsz]}
{125}{}{Mit tehetek önért, Kapitány?}
{126}{}{Mit tehetek önért, Polgártárs?}
{127}{}{Mit parancsol?}
{128}{}{Glugy-glugy}
{129}{}{[Elbattyogsz]}
{130}{}{Mit lehet itt inni?}
{131}{}{Némi információra lenne szükségem.}
{132}{}{Kösz, csak benéztem. Viszlát!}
{133}{}{"Glugy-glugy"? Jól mondod, barátom. Várj egy kicsit, hívom az õröket, ezt nekik is hallaniuk kell.}
{134}{}{He? hummm-ummm.}
{135}{}{[Elbattyogsz]}
{136}{}{Inni? Ezt-azt.}
{137}{}{Van ásványvizünk, desztillált vizünk és szódavizünk. Ezen kívül számos szintetizált alkohol közül választhat.}
{138}{}{Milyen szinte... zitált italokat kínál?}
#Esetleg szinte... szitált? :)
{139}{}{Valódi alkoholjuk nincs?}
#Ez kivetelesen jobban hangzik
{140}{}{Egy pohár víz jól esne.}
{141}{}{Némi információra lenne szükségem.}
{142}{}{Azt hiszem, nem ezt a helyet kerestem. Viszlát!}
{143}{}{Nagyon jó, uram.}
{144}{}{Nagyon jó, asszonyom.}
{145}{}{Melyikbõl adjak? Az ásvány-,  a desztillált-, vagy a szódavízbõl? Most mindegyiket mérsékelt áron, poharanként 5 dollárért mérem.}
{146}{}{Ásványvizet kérek.}
{147}{}{Megkóstolnám azt a deszti... lálisat.}
{148}{}{Kezdjük mondjuk a szódavízzel.}
{149}{}{Milyen szintetikus alkoholt tartanak?}
{150}{}{Inkább kérdeznék valamit.}
{151}{}{Ilyen drága italokat sajnos nem engedhetek meg magamnak.}
{152}{}{Köszönöm, de most inkább kihagynám. Viszlát!}
{153}{}{Van H és T típusú italunk, illetve nemrég fõztünk egy rendkívül népszerû párlatot, a "Z-Alkoholt". Testes pszeudó-mikro-cefre íze van. Most mérsékelt áron, kupicánként mindössze 20 dollárért megkaphatja.}
#Az alkohol-z angol formula
{154}{}{Hogy készülnek ezek a szinte... izés italok?}
{155}{}{Valódi alkoholjuk nincs?}
{156}{}{Azt hiszem, csak egy pohár vizet kérek.}
{157}{}{Kipróbálnám azt a pompásnak ígérkezõ Z-Alkoholt.}
{158}{}{Némi információra lenne szükségem.}
{159}{}{Sajnos most nincs elég pénzem.}
{160}{}{Egyiket se szeretem. Viszlát!}
{161}{}{Esetleg még egy italt?}
{162}{}{Igen, kérek egy pohár vizet.}
{163}{}{Miért is ne? Ha megkérem, felsorolná még egyszer az itt kapható... puccos piákat?}
{164}{}{Kösz nem, inkább kérdeznék valamit.}
{165}{}{Nem, köszönöm. Viszlát!}
{166}{}{Minden rendben, uram? Ennyi Z-Alkoholnak, úgy látom, van némi hatása. Biztos benne, hogy kér még egyet?}
{167}{}{Minden rendben, asszonyom? Ennyi Z-Alkoholnak, úgy látom, van némi hatása. Biztos benne, hogy kér még egyet?}
#Nagy esellyel a dupla "sir" egy bug az angolban
{168}{}{Esetleg még egy italt?}
{169}{}{Rosszul vagyok. Egy pillanatra kilépek ebbõl a beszélgetésbõl és megnézem az életerõ pontjaimat.}
{170}{}{Remekül érzem magam, csak egy pillanatra kilépek ebbõl a beszélgetésbõl és megnézem az életerõ pontjaimat. Utána folytathatjuk.}
{171}{}{Csak egy kis vizet kérek.}
{172}{}{Adna még abból a remek Z-Alkoholból?}
{173}{}{Hogy készülnek ezek az italok?}
{174}{}{Néhány információra lenne szükségem.}
{175}{}{Ma már nem kérek semmit, köszönöm.}
{176}{}{Menedékváros Auto-dokija csinálja. Képes az egyébként függõséget okozó anyagokat kiváltó szintetikus helyettesítõk elõállítására. Azt hallottam, ezeket placebóként használták még a háború elõtt.}
{177}{}{Meglepõen sokat tud ezekrõl a dolgokról.}
{178}{}{Valódi piájuk nincs?}
{179}{}{Egy pohár vizet kérek.}
{180}{}{Innék még abból a Z-Alkoholból.}
{181}{}{Másra lennék kíváncsi.}
{182}{}{Köszönöm az információt. Viszlát!}
{183}{}{Pár hónapig Dr. Troy mellett asszisztáltam, és csak nemrég kerültem ide. A munkám miatt szükséges volt, hogy betéve tudjam Menedékváros orvosi adatbázisát.}
{184}{}{"Betéve"?! És ez legális, mármint ilyet csinálni egy számítógéppel?}
{185}{}{Orvosi adatbázis?! Nocsak!}
{186}{}{Érdekes, de én másra lennék kíváncsi.}
{187}{}{Köszönöm. Viszlát!}
{188}{}{"Betéve" nem AZT jelenti, uram! Ezt a szót használjuk, ha valaki, valamit alaposan, minden aspektusból megismert.}
{189}{}{Hogy?... Ja, persze. Kanko Aspectulus. Ismerem. Nekem is volt, de kikezeltettem. Viszont a kollega említett valami orvosi adatbázist.}
#Ez azert elegge szabad forditas :)
{190}{}{Ez rendkívül érdekes... [ásítasz]... de most másra lennék kíváncsi.}
{191}{}{Megértelek. Én is ezt mondanám, ha idõnként "betenném" a számítógépnek. Viszlát!}
{192}{}{A Menedék elsõ szintjén lévõ terminálok rendkívül nagy orvosi adatbázishoz kapcsolódnak. Igen érdekes anyag, bár a zsargon néha zavaró.}
{193}{}{Zsargon? Ezt a szót is ismerem. Elnyomót, diktátort jelent. Igazam van?}
{194}{}{Jó ezt tudni. Most azonban másra lennék kíváncsi.}
{195}{}{Ennek azonnal utánanézek. Viszlát!}
{196}{}{Nem egészen, uram... [vörösödik a feje]... A "zsargon" annyit tesz, terminológia, szakmai nyelv. Amire ön gondol, az a "zsarnok".}
{197}{}{Honnan a francból tudná, hogy mire gondolok. Mi maga? Média? Inkább kérdeznék valamit.}
{198}{}{Ha maga mondja. Azt azért jobb, ha tudja, én már sok zsargont kicsináltam. Szóval ehhez tartsa magát!}
#Ez tetszett
{199}{}{Ha arra gondol, amit a pusztában, ki tudja, mibõl erjesztenek, akkor olyannal nem szolgálhatok.}
{200}{}{Sosem éreztük szükségét, hogy efféle párlatokkal mérgezzük magunkat. Ha van gyomra az ilyesmihez, térjen be az elõvárosi csapszékbe... uram!}
{201}{}{Akkor csak egy pohár vizet kérek. }
{202}{}{Várjon egy percet! Azért én innék valami erõset. Mi a napi kínálat?}
{203}{}{Némiy információra lenne szükségem.}
{204}{}{Ezt fogom tenni, viszlát!}
{205}{}{Akkor talán felkeresek egy másik helyet.}
{206}{}{Akkor talán nem ehhez az intézményhez, hanem az Információs Központhoz kellene fordulnia. Most pedig kérem, távozzon... szeretnék a többi vendéggel is foglalkozni!}
{207}{}{Várjon egy percet! Kérek egy italt. Mit tud ajánlani?}
{208}{}{NEM!!! Rám figyelsz és válaszolsz! Figyelmeztetlek, egy hajszál választ el attól, hogy komoly bajba kerülj!}
{209}{}{Rendben. Viszlát!}
{210}{}{Elnézést. Mit szeretne tudni, uram?}
{211}{}{Elnézést. Mit szeretne tudni, hölgyem?}
{212}{}{Elnézést. Mit szeretne tudni, Kapitány?}
{213}{}{Elnézést. Mit szeretne tudni, Polgártárs?}
{214}{}{Elárulná, ki vezeti a várost?}
{215}{}{Mit tud a menedékvárosi rabszolgaságról?}
{216}{}{Már semmit. Egy italt szeretnék. Mije van?}
{217}{}{Viszlát!}
{218}{}{Lynette Elsõ Polgár. Õ irányítja a várost több, mint két ciklus óta. A Tanács nem örül ennek, de õ az illetékes a Menedékvárost érintõ legtöbb ügyben.}
{219}{}{Tanács?}
{220}{}{Mit tud a menedékvárosi rabszolgaságról?}
{221}{}{Mit lehet itt inni?}
{222}{}{Köszönöm az információt. Viszlát!}
{223}{}{Igen, van egy Menedékvárosi Tanács is. A rangidõst McClure Fõtanácsosnak hívják... [közelebb hajol]... McClure és az Elsõ Polgár nem szívelik egymást.}
{224}{}{Valóban?}
{225}{}{Engem inkább az érdekel, amit a menedékvárosi rabszolgaságról tud.}
{226}{}{Innék valamit. Mit tud ajánlani?}
{227}{}{Értem. Viszlát!}
{228}{}{Ó... igen. Nemrég petíciót nyújtottak be McClure-hoz, hogy a Tanács bírálja felül az Elsõ Polgár néhány döntését. Jó kis kavarodás támadt ebbõl, mondhatom.}
{229}{}{Értem. Mást kérdeznék.}
{230}{}{Egy ital jót tenne. Mit ajánl?}
{231}{}{Köszönöm a segítséget, de most már mennem kell. Viszlát!}
{232}{}{Ó... nem, nem... ez nem rabszolgaság. A városban dolgozó emberek csupán szolgák... magamat is beleértve. Nagyon jól bánnak velünk, megtanítottak írni és olvasni. Ezenkívül rendszeres orvosi ellátást, szálláshelyet és ételt is kapunk.}
{233}{}{Mindent megkap... leszámítva a szabadságot, igaz?}
{234}{}{Ha nem panaszkodik, nem lesz probléma. Felejtse el, hogy megkérdeztem!}
{235}{}{Egy italt szeretnék. Mit tud felkínálni?}
{236}{}{Értem. Köszönöm a beszélgetést. Viszlát!}
{237}{}{Ha nem szándékozik italt rendelni, talán legjobb, ha elmegy, hölgyem!}
{238}{}{Ha nem szándékozik italt rendelni, talán legjobb, ha elmegy, uram!}
{239}{}{Ha nem panaszkodik, nem lesz probléma. Felejtse el, hogy megkérdeztem!}
{240}{}{Akkor kérek egy italt. Mit lehet inni?}
{241}{}{Ezt fogom tenni. Viszlát!}
{242}{}{Nem panaszkodom. Van valami, amiben segíthetek?}
{243}{}{Akkor kérek egy italt. Mit lehet inni?}
{244}{}{Nem kérek semmit, köszönöm. Viszlát!}
{245}{}{Zzzzzz.}