{100}{}{Egy koszos, izmos férfit látsz.}
{101}{}{Connar-t látod.}
{102}{}{Hé te! Mit csinálsz?}
{103}{}{Ne mozdulj vándor! Mit keresel itt?}
{104}{}{Legyilkolom ezeket a szörnyeket.}
{105}{}{Miért? Mit ártottak neked?}
{106}{}{Mert csak!}
{107}{}{Fogadni mernék, hogy azok a rohadékok küldtek Menedékvárosból. Jobban tennéd, ha lelépnél és békén hagynál minket!}
{108}{}{Hát, ezzel elkéstél.}
{109}{}{Miért?}
{110}{}{Bocs, de a munka az munka.}
{111}{}{Azoknak az állatoknak köszönhetjük, hogy még nem vagyunk Menedékváros úgynevezett "szolgái".}
{112}{}{Bocs, de fizetnek érte, hogy végezzek a szörnyekkel és meg is teszem.}
{113}{}{Errõl nem szóltak.}
{114}{}{Fizetnek, hogy kipucoljam a helyet. Már végeztem is velük.}
{115}{}{Te idióta! Mi a francért csináltad ezt?}
{116}{}{Kellett a pénz.}
{117}{}{Ugye tudod, hogy elvisznek minket, ha megteszed?}
{118}{}{Nem az én bajom.}
{119}{}{Akkor dögölj meg! Hamarosan jönnek értünk.}
{120}{}{Nem tudtam, hogy ezért olyan fontos nekik.}
{121}{}{Aha, persze. Különben sem tárgyalok ilyen szar alakkal, mint te.}
{122}{}{Bocs, de nem hagyhatjuk.}
{123}{}{Tedd amit tenned kell.}
{124}{}{Megvettek kilóra? Még sokat kell tanulnod a világról, barátom.}
{125}{}{Segíthetek bármiben?}
{126}{}{A menedékvárosi srácok elég beszariak. Csinálsz egy-két figurát és már futnak is a hegyekbe. Ha lenne pár lõfegyverünk, azt hiszem, elbírnánk velük.}
{127}{}{Milyen fegyverekre gondolsz?}
{128}{}{Hát, én jól bánok a sörétessel és van pár emberem, akik  boldogulnak az uzival. Szerintem három darab elég lenne.}
{129}{}{Megnézem, mit tehetek.}
{130}{}{Nem vagy közénk való. Tünj el!}
{131}{}{Meggondoltam magam. Tudok segíteni?}
{132}{}{Aha, a legjobb ha minél hamarabb lelépsz.}
{133}{}{Aggódom.}
{134}{}{Hát visszajöttél! Sikerült fegyvereket szerezned?}
{135}{}{Mi kell már megint?}
{136}{}{Ja, itt vannak.}
{137}{}{Kell három uzi és egy sörétes puska. Minél elõbb, annál jobb.}
{138}{}{Oké.}
{139}{}{Most végre kezdhetünk valamit ezzel a hellyel. Ha kell egy vacok ahol meg akarsz pihenni, mi mindig szívesen látunk.}
{140}{}{Szóra sem érdemes.}
{141}{}{Üdv újra. Jól mennek a dolgok, épp a falu bõvítésén dolgozunk.}
{142}{}{Üdv újra. Jól mennek a dolgok, mint látod. Nézz körül, ha van idõd!}
{143}{}{Még mindig épitkezünk. Ha minden jól megy, jövõ hónapban megemeljük a falakat.}
{144}{}{Üdv! A falu megint bõvült. Örülünk, hogy újra itt vagy!}
{145}{}{Nincs többé félnivalónk Menedékvárostól, így végre békében élhetünk. Mégegyszer köszönjük, vándor!}
{146}{}{Csak ne gyilkolássz itt semmit, te gyökér!}
