{100}{}{Egy zord tekintetû õrt látsz.}
{101}{}{Egy zord tekintetû menedékvárosi õrt látsz.}
{102}{}{Törõdj a magad dolgával!}
{103}{}{Azt hiszem, ideje eltûnnöd innen.}
{104}{}{Nem tetszik a tekinteted.}
{105}{}{Vigyázz magadra!}
{106}{}{Üdvözlöm, Polgártárs.}
{107}{}{Jó hogy látom, Polgártárs.}
{108}{}{Sok a tennivaló ugye, Polgártárs?}
{109}{}{Csak ön után, Polgártárs.}
{110}{}{Ne ácsorogj itt!}
{111}{}{Törõdj a magad dolgával, idegen!}
{112}{}{Nincs itt semmi látnivaló!}
{113}{}{Ha be akarsz jutni a városba, beszélj Wallace-szal!}
