# Dialog Editor last position: 50
{100}{}{Ez a polgár világoskék kezeslábast visel. Éppen olyan, mint a Menedéklakóé, csak nincs rajta szám.}
{101}{}{Darrow, az  "A" Komfort Osztály vezetõje.}
{102}{}{Ez a polgár világoskék kezeslábast visel. Éppen olyan, mint a Menedéklakóé, csak nincs rajta szám.}
{103}{}{::tapsol::}
{104}{}{Nézzétek! A Hõsünk!}
{105}{}{Emberek! A hõsünk itt van Menedékvárosban!}
{106}{}{Jó napot, Kapitány.}
{107}{}{Menedékváros mindenek felett, Kapitány!}
{108}{}{Jó napot, Polgártárs!}
{109}{}{Menedékváros mindenek felett, Polgártárs!}
{110}{}{Itt egy mutáns! Õrség! Õrség!!!}
{111}{}{Itt egy ghoul! Õrség! Õrség!!!}
{112}{}{Szükségünk lesz még pár szerszámra Reddingbõl.}
{113}{}{Unalmas nap ez a mai.}
{114}{}{Meglepne, ha Randal végzett volna már a szállítólevelekkel.}
{115}{}{Hisz tegnap adtam oda a leltár-jegyzéket Randalnak. Micsoda fejetlenség.}
{116}{}{A Lista Hivatal sokkal hamarabb végezne egy ilyen munkával.}
{117}{}{A szolgák elkoptatták a szerszámok zömét. Örülnék, ha jobban vigyáznának rá.}
{118}{}{Jól jönne egy kis vakáció.}
{119}{}{Az "A" Komfort Osztály éjjel zárva van, gyere vissza reggel!}
{120}{}{Már leltározok, gyere vissza reggel!}
{121}{}{Zárva vagyunk. Próbáld meg Boldog Harrynél, ha nagyon sürgõs!}
{122}{}{Segíthetek valamiben, Kapitány?}
{123}{}{Segíthetnék valamiben, Polgártárs?}
{124}{}{Igen? Segíthetek?}
{125}{}{Segít én? Tiira-riira taraaaaam}
{126}{}{[Elcsosszansz]}
{127}{}{Nem is tudom. Mi ez a hely?}
{128}{}{Láthatnám a készleteidet?}
{129}{}{Kösz, nem. Viszlát!}
{130}{}{Várj egy pillanatot, rendben? Hozok valakit, aki megmutatja neked a kijáratot.}
{131}{}{NEM ÉN NEM MENNI}
{132}{}{Okiiii-dokiiii}
{133}{}{Megjegyzem, hogy sok a dolgom. Legközelebb Elõvárosban vásárolj, Boldog Harry boltjában, rendben?}
{134}{}{Elnézést, hogy feltartottalak.}
{135}{}{Megjegyzem, nem vagyok kíváncsi se az idõbeosztásodra, se a véleményedre. Rendben?}
{136}{}{Köszönöm. Menedékváros mindenek felett, Polgártárs!}
{137}{}{Köszönöm. Menedékváros mindenek felett, Kapitány!}
{138}{}{Menedékváros mindenek felett, Polgártárs!}
{139}{}{Jó napot, Polgártárs!}
{140}{}{Ez itt az "A" Komfort Osztály. Komoly készleteink vannak szerszámokból, javító eszközökbõl. A nevem Darrow. Biztos, hogy jó helyen jársz?}
{141}{}{Ez itt az "A" Komfort Osztály. Mi tároljuk a város szerszámait, javító eszközeit. Biztos, hogy jó helyen jársz?}
{142}{}{Láthatnám a készleteidet?}
{143}{}{Igen, ezt kerestem. Láthatnám a készleteidet?}
{144}{}{Nem is tudom.}
{145}{}{Nem hiszem. Viszlát!}
{146}{}{Hé! Azt hagyd békén!}
{147}{}{Mars ki innen!}
{148}{}{Kösz.}
{149}{}{[tovább]}
