# Dialog Editor last position: 5
{100}{}{Középkorú férfi, orvosi köpenyben. Elfoglaltnak tûnik.}
{101}{}{Dr.Troy}
{102}{}{Középkorú férfi, orvosi köpenyben. Elfoglaltnak tûnik.}
{103}{}{Lássuk csak! Holnap reggel három védõoltást kell beadnunk, aztán...}
{104}{}{Esküszöm, Gregory egy hipochonder!}
#ezt sajna igy kell irni

{105}{}{Az új szolgákat is orvosi ellátásban kell részesítenünk.}
{106}{}{Phyllis kérem, idehozná nekem a Fõtanácsos vérvételi leleteit?}
{107}{}{Furcsa! Ezek az értékek nem jellemzõk ilyen alacsony trombocita szintnél.}
{108}{}{Talán klónozhatjuk a lépet azokból a sejtekbõl, amiket ma délután kaptunk.}
{109}{}{Több vitamint kell adagolnunk a diétás ellátmányba.}
{110}{}{Hmmm...}
{111}{}{Phyllis, kérem! Csinálna nekem egy másolatot Helen kartonjáról?}
{112}{}{Ha belegondolok, hogy most akár a Szerelemvonalnak is dolgozhatnék.}
{113}{}{Belefáradtam abba, hogy állandóan csak listákat gyártsak.}
{114}{}{Listát kell készítenünk az orvosi felszereléseinkrõl?! De hát tegnap már küldtem egyet!}
{115}{}{Egy mutáns! Õrség!}
{116}{}{Egy ghoul! Õrség!}
{117}{}{Üdvözlöm, Dr.Troy vagyok. Miben segíthetek?}
{118}{}{Nekem lenni bibi.}
{119}{}{Segg... ít... ség !}
{120}{}{[Elbattyogsz]}
{121}{}{A Központi Számítógépet keresem. Megmondaná, hol találom?}
{122}{}{Mit csinál itt?}
{123}{}{Csak benéztem, de már megyek is. Viszlát!}
{124}{}{Ön orvos? Örvendek a szerencsének! Mi lenne, ha megosztanánk egymással a tapasztalatainkat? Szakítana rám egy kis idõt?}
{125}{}{Természetesen. Nagyon érdekel, milyen technikákat alkalmaznak a Polgárok kezelésénél.}
{126}{}{Sajnálom, erre most nincs idõm, viszont kérdeznék valamit.}
{127}{}{Talán majd késõbb. Viszlát!}
{128}{}{Nagyszerû! Ha megengedi, elõször is megmutatom a felszerelésünket. Itt vannak a megfigyelõ berendezéseink...}
{129}{}{}
{130}{}{... és így klónozunk sejtekbõl átültethetõ szerveket. Nagyon kell ügyelnünk arra, hogy a sebkötözõ anyagok sterilek legyenek... de azt hiszem, már eleget beszéltem. Remélem, van, amit hasznosítani tud.}
{131}{}{Természetesen, de kérdezhetnék még valamit?}
{132}{}{Köszönöm a bemutatót, Dr.Troy. Nagyon hasznosnak bizonyult, de most már mennem kell.}
{133}{}{A Központi Számítógépet? Lent van a harmadik szinten. Használja a liftet, majd menjen egyenesen tovább, amíg egy T-elágazáshoz nem ér! Ott forduljon balra és már meg is találta!}
{134}{}{Mit csinál itt?}
{135}{}{Köszönöm!}
{136}{}{Menedékváros fõorvosa vagyok. Igyekszem megõrizni Polgártársaink egészségét illetve meggyógyítom õket, ha szükséges.}
{137}{}{A Központi Számítógépet keresem. Megmondaná, hol találom?}
{138}{}{Értem. Viszlát!}
{139}{}{Bocsásson meg egy pillanatra... nem emlékszem, hogy valaha is találkoztunk volna. Ön polgár?}
{140}{}{Igen. Most kaptam meg a Polgársági papírjaimat.}
{141}{}{Tulajdonképpen én }
{142}{}{ vagyok. Az Õrség Kapitánya.}
{143}{}{Hmm... az vagyok.}
{144}{}{Nem.}
{145}{}{Örülök, hogy találkoztunk kedves, }
{146}{}{. Ha bármikor szüksége lenne a segítségemre, itt megtalál.}
{147}{}{Köszönöm. Viszlát!}
{148}{}{Ön nem Menedékvárosban született, igaz? Biztosan emlékeznék rá. Elárulná, honnan jött?}
{149}{}{Bocsásson meg egy pillanatra... ön egy Kívülálló, igaz? Elárulná, honnan jött?}
{150}{}{Egy kis faluból innen nyugatra. Arroyónak hívják.}
{151}{}{Miért kérdezi?}
{152}{}{Ez nem tartozik magára, doki.}
{153}{}{Nem akarok a múltamról beszélni.}
{154}{}{Arroyo... Arroyo... még sose hallottam róla. Elnézést, amiért faggatom, de egy olyan embert keresek, aki már járt Menedékváros falain túl. A legtöbb Polgár ugyanis nem hagyja el a várost.}
{155}{}{Tapasztalt utazó vagyok. Segíthetek?}
{156}{}{Kifejtené bõvebben?}
{157}{}{Elnézést, amiért faggatom, de egy olyan embert keresek, aki már járt Menedékváros falain túl. A legtöbb Polgár ugyanis nem hagyja el a várost.}
{158}{}{Tapasztalt utazó vagyok. Segíthetek?}
{159}{}{Kifejtené bõvebben?}
{160}{}{Azt hiszem, ön eltévedt. Menjen vissza a folyosóra kérem, majd forduljon jobbra! Így visszajuthat a felszínre.}
{161}{}{Köszönöm az útbaigazítást. Viszlát!}
{162}{}{Ha már így összefutottunk, láthatnám a készleteit?}
{163}{}{Keresek valakit, aki elvégezne nekem egy különleges munkát.}
{164}{}{Mi lenne az?}
{165}{}{Köszönöm, hogy rám gondolt, de nem érdekel.}
{166}{}{Örülök, hogy így döntött!}
{167}{}{Tudomásom szerint megjelent egy új drog, amit Jetnek hívnak. Hajlandó vagyok ezer dollárt fizetni egy adagért.}
{168}{}{Épp van nálam egy adag.}
{169}{}{Legyen inkább 1200!}
{170}{}{Lehet róla szó, de 1500 dollárba fog kerülni.}
{171}{}{Jól értettem? Azt akarja, hogy Jetet csempésszek a városba?}
{172}{}{Jet? Minek az magának?}
{173}{}{Csábító, de nem érdekel.}
{174}{}{Értem és elnézést, amiért feltartottam. Azért jöjjön vissza, ha meggondolta magát! Bõkezûen megjutalmazom.}
{175}{}{Rendben. Addig is feltehetnék egy kérdést?}
{176}{}{Értem. Majd meglátom, mit tehetek.}
{177}{}{Viszlát!}
{178}{}{Figyelembevéve a tényt, hogy rögtön megkapom, ez az ár elfogadhatónak tûnik. Legyen. Itt a pénze... és köszönöm!}
{179}{}{Kérdeznék valamit.}
{180}{}{Szerintem nem kéne belélegeznie azt a szart. Higgyen nekem!}
{181}{}{Megmutassam, hogy kell használni? Úgy értem, rájöttem, hogy akkor a legütõsebb, ha befogja az orrát, kifúj minden levegõt, mélyen letüdõzi és benntartja egy percig.}
{182}{}{Élmény magával üzletet kötni, doki. Azért vigyázzon azzal a cuccal, oké?}
{183}{}{Mint már mondtam, KÖSZÖNÖM! Most kérem hagyjon magamra!}
{184}{}{Lenne itt még egy kérdés.}
{185}{}{Szerintem nem kéne belélegeznie azt a szart. Higgyen nekem!}
{186}{}{Rendben, késõbb még találkozunk.}
{187}{}{Mirõl beszél?}
{188}{}{Hagyjuk! Inkább kérdeznék valamit.}
{189}{}{Ezt az anyagot brahmin-trágyából készítik.}
{190}{}{Amit abban a Jet-adagolóban lát, az brahmin-szar párlat. Fincsi, mi?}
{191}{}{Amit abban a Jet-adagolóban lát, az brahmin-szar párlat. Fincsi, mi? Egyébként tényleg nincs endorfin blokkolója?}
{192}{}{Nos, a zsenifiú szerint ezt a cuccot brahmin-trágyából állítják elõ.}
{193}{}{A zsenifiú szerint amit abban a Jet-adagolóban lát, az brahmin-szar párlat. Fincsi, mi?}
{194}{}{A zsenifiú szerint amit abban a Jet-adagolóban lát, az brahmin-szar párlat. Fincsi, mi? Egyébként tényleg nincs endorfin blokkolója?}
{195}{}{Nem fontos, most mennem kell. Viszlát!}
{196}{}{Azt hiszem... téved.}
{197}{}{Nem muszáj elhinni. Kérdezhetek még valamit?}
{198}{}{Nem, tényleg. A Jetet brahmin-szarból nyerik, bár az alapanyagot eredetileg mûtrágyaként használták.}
{199}{}{Komolyan mondom. Régebben hallucinogén gombákat termesztettek rajta, de észrevették, hogy a "gázok" felpörgetik a munkásokat. Nos, itt van ez a háború elõtti fehérjekivonat, és...}
{200}{}{Lehetséges. Késõbb még találkozunk, doktor.}
{201}{}{Valóban? Azt hiszem, a brahmin... ürülékbõl valóban jó mûtrágyát lehet készíteni. Ez még eddig eszembe sem jutott. Köszönöm, barátom! Habár az elõállítás mikéntjére azért kíváncsi lennék.}
{202}{}{Arra én is. Egyébként fogalmazzunk pontosan! Brahmin-SZARRA van szükség és nem ÜRÜLÉKRE, oké? Majd még találkozunk, doki.}
{203}{}{Szívesen! Azért vigyázzon azzal a cuccal, rendben?}
{204}{}{Késõbb még találkozunk. Viszlát!}
{205}{}{Ez... rendkívül érdekes. Talán a város külsõ övezetében sikerül mintát vennem. Köszönöm, barátom! Nagyon hálás vagyok. Habár az elõállítás mikéntjére azért kíváncsi lennék.}
{206}{}{Szívesen! Azért vigyázzon azzal a cuccal, rendben?}
{207}{}{Késõbb még találkozunk, doktor.}
{208}{}{Endorfin blokkoló? Miért kérdi?}
{209}{}{Szerintem az endorfin blokkolóval semlegesíthetjük a Jet hatását. Bár ez csak teória, még nem teszteltem.}
{210}{}{Nem érdekes. Inkább kérdeznék valamit.}
{211}{}{Most nincs idõm bõvebben kifejteni, mennem kell. Viszlát!}
{212}{}{Nincs ilyen anyagom, de az Auto-doki képes az elõállítására. Egész pontosan miért kellene?}
{213}{}{Mint bizonyára tudja, a Jet-okozta függõségtõl szinte lehetetlen megszabadulni. Arra gondoltam, ha endorfin blokkolót juttatnánk a szervezetbe, akkor...}
{215}{}{Hihetetlen! Ez a legbriliánsabb megoldás, amit valaha is hallottam. Hónapokig kísérleteztem a Jet-függõség gyógyításán, de nem jutottam semmire.}
{216}{}{Ön is az ellenanyagon dolgozik?}
{217}{}{Igen, ezért volt szükségem egy adag Jetre.}
{218}{}{Igen, de sikertelenül.}
{219}{}{A drog hatóanyagát semlegesíteni kell, mielõtt az lebomlik. Erre a teóriára alapozva még ma elkészíthetjük az ellenanyagot! Várjon! Azonnal nekiállok.}
{220}{}{Remek! Köszönöm, doktor.}
{221}{}{Ez a fiatalember? Õ készítette a Jetet?}
{222}{}{Azt nem mondanám, hogy "ember", de igen, õ készítette. Vagy legalábbis azt állítja.}
{223}{}{Úgy bizony, bár meg nem mondaná meg így elsõ ránézésre, igaz?}
{224}{}{Myron, Dr. Troy... Dr. Troy, Myron.}
{225}{}{Lenne néhány kérdésem ehhez a fiatalemberhez.}
{226}{}{Csak bátran! Azért javaslom, hogy mielõtt elkezdi, vegyen be pár aszpirint! Nem egyszerû eset.}
{227}{}{Parancsoljon, doktor!}
{228}{}{Ahogy gondolja, doki. Azért szóljon majd, ha szüksége lesz valamire. Mondjuk egy baseball ütõre vagy ilyesmi.}
{229}{}{Brahmin-gázok? Hát nem egy konvencionális elõállítási folyamat de... miért is ne? Talán, ha mintát vennék egy brahmintól a külsõ övezetben. Köszönöm, barátom!}
{230}{}{Nem probléma.}
{231}{}{Szívesen!}
{232}{}{Megmondhatja a kis huligán barátjának, hogy ostobaságot csinál, ha drogok kifejlesztésére vesztegeti el az egyébként briliáns elméjét. Valamint azt, hogy a modora és a kommunikációs készsége még IGEN SOK kívánnivalót hagy maga után.}
{233}{}{Beszéljen róla!}
{234}{}{Azt hiszem, túloz egy kicsit, doki! Némi drog-fogyasztás nem árt meg senkinek... Na jó, talán kivétel ez alól a szuper stimpakk, a buffout, a pszycho meg a... Rendben van, hagyjuk! Mennem kell.}
{235}{}{Ezt fogom tenni.}
{236}{}{Hajlandó vagyok ezer dollárt fizetni egy adagért... és a hallgatásáért.}
{237}{}{Van nálam egy adag Jet.}
{238}{}{Mire kell az magának?}
{239}{}{Jól hangzik, benne vagyok.}
{240}{}{Sajnálom, de nem érdekel.}
{241}{}{Szükségem van erre az anyagra... a munkám miatt. Ezer dollárt fizetek érte, de nagyon fontos, hogy bizalmasan kezelje a tranzakciót!}
{242}{}{Hmm... szóval bizalmasan?}
{243}{}{Igazán? És mennyit fizetne azért, hogy tartsam a pofám? Akár már most is feldobhatnám.}
{244}{}{Van nálam egy adag.}
{245}{}{Mire kell a Jet?}
{246}{}{Nem probléma. Számíthat rám.}
{247}{}{Nem érdekel a dolog.}
{248}{}{Igen, bizalmasan. Vagyis maradjon a dolog kettõnk közt, ne beszéljen róla senkinek vagy ha úgy jobban tetszik, tartsa a száját!}
{249}{}{Értem. Egyébként van nálam egy adag.}
{250}{}{Mire kell a Jet?}
{251}{}{Nagy bajban van, doki! Illegális anyag behozatalára próbált rávenni. Sokba fog ez magának kerülni!}
{252}{}{Rendben, számíthat rám.}
{253}{}{Nem érdekel, keressen valaki mást!}
{254}{}{Ez nem tartozik magára. Szerezzen egy adag Jetet, hozza el nekem, én meg fizetek érte ezer dollárt! Ez az összeg magában foglalja a hallgatását is! Rendben?}
{255}{}{Rendben. Egyébként van is nálam egy adag.}
{256}{}{Jobbat tudok. Fogom magam, és szépen elsusogom mondjuk az Elsõ Polgárnak, hogy miben mesterkedik.}
{257}{}{Számíthat rám, vállalom!}
{258}{}{Szó sem lehet róla, keressen valaki mást!}
{259}{}{Micsoda?! Pimasz gazember!!! Hogy merészel... megfenyegetni?!}
{260}{}{Higgadjon le, csak tréfa volt! Nem kell pánikolni!}
{261}{}{Én már csak ilyen bátor fickó vagyok. Szóval, mennyit ér a Polgársága? Tudja, a pusztai élet nagyon megviselheti az embert.}
{262}{}{Ostoba voltam, hogy megbíztam magában! Legyen... mit akar tõlem?}
{263}{}{Ötszáz dolcsi minden hónap elsején és ez a kis drogcsempészet köztünk marad.}
{264}{}{Egy ezres minden hónap elsején és megtarthatja a Polgárságát.}
{265}{}{Kétezer minden hónap elsején és hallgatok.}
{266}{}{Megõrült? Ennyit nem tudok fizetni!}
{267}{}{Jól van, nyugalom! Legyen csak ötszáz, és nem kell beavatnunk az Elsõ Polgárt.}
{268}{}{Jobban teszi, ha TALÁL rá módot, különben mehet koldulni a külsõ övezetébe!}
{269}{}{Rendben van, feladom... itt a pénze!}
{270}{}{Kösz, doki, élmény magával üzletet kötni. Hamarosan találkozunk.}
{271}{}{Jobban teszi, ha ez továbbra is így marad, különben magán fogom tesztelni az Auto-doki kicsontozó programját. Megértette?}
{272}{}{Ez nem olyan dolog, amivel viccelni lehet, rendkívül fontos ügyrõl van szó. Tehát ezer dollárt fizetek a Jetért, a hallgatásáért, és nincs több kérdés. Érdekli a munka vagy sem?}
{273}{}{Még szép, hogy érdekel. Van is nálam egy adag.}
{274}{}{Nem. Az viszont annál inkább, hogy mennyit ér meg magának a hallgatásom?}
{275}{}{Rendben van, vállalom.}
{276}{}{Nem érdekel.}
{277}{}{Valóban?}
{278}{}{Ez nagyszerû! Köszönöm, barátom! El sem tudja képzelni, milyen fontos ez a számomra. Itt a pénze.}
{279}{}{Köszönöm! Mielõtt indulnék, kérdeznék valamit.}
{280}{}{Szerintem nem kéne belélegeznie azt a szart. Higgyen nekem!}
{281}{}{Kösz, viszlát!}
{282}{}{Üdvözlöm, Kapitány! Miben lehetek a segítségére?}
{283}{}{Üdvözlöm, Polgártárs! Miben lehetek a segítségére?}
{284}{}{Miben lehetek a segítségére?}
{285}{}{Igen?}
{286}{}{Nekem lenni bibi.}
{287}{}{Segg... ít... ség?}
{288}{}{[Elbattyogsz]}
{289}{}{Orvosi ellátásra van szükségem.}
{290}{}{Egy kollégához van szerencsém? Én is sokat foglalkozom az orvostudományokkal.}
{291}{}{Nincs véletlenül endorfin blokkolója?}
{292}{}{Nálam van a Jet, amit kért.}
{293}{}{Arról a bizonyos munkáról lenne szó. Mi lenne a dolgom?}
{294}{}{A Jettel kapcsolatban, amit kért. Szerintem a többi Polgár is szeretne tudni róla.}
{295}{}{Azt hiszem, semmiben. Viszlát!}
{296}{}{Van itt egy bevált szérum, ez segíteni fog. A legtöbb Polgár már évekkel ezelõtt megkapta, ezért szinte teljesen megfeledkeztem róla. Várjon egy percet, felkészítem az Auto-dokit a mûveletre!}
{297}{}{Rendben, köszönöm!}
{298}{}{Kész is vagyunk. Azt azért tudnia kell, ez az oltás nem teszi immunissá a mérgekkel és a sugárzással szemben, csak megnöveli a természetes ellenálló képességét.}
{299}{}{Köszönöm! Feltennék egy kérdést, ha lehet.}
{300}{}{Megértettem és hálás vagyok a szérumért. Viszlát!}
{301}{}{Maga az? Mit akar?}
{302}{}{Orvosi ellátásra van szükségem.}
{303}{}{Megmérgeztek.}
{304}{}{Sugárfertõzésben szenvedek.}
{305}{}{A pénzemért jöttem. Megvan?}
{306}{}{Csak beugrottam, hogy figyelmeztessem, közeleg elseje és jobban teszi, ha összeszedi addigra a pénzt.}
{307}{}{Tulajdonképpen... semmit.}
{308}{}{Nem felejtettem el, itt a pénze. Most pedig tûnjön el!}
{309}{}{Várjon! Elõbb orvosi ellátásra van szükségem.}
{310}{}{Várjon! Megmérgeztek, gyógyítson meg!}
{311}{}{Várjon! Sugárfertõzött vagyok, gyógyítson meg!}
{312}{}{Örültem az üzletnek. Hamarosan találkozunk, doki.}
{313}{}{Nem felejtettem el, meg fogja kapni a pénzét. Most pedig tûnjön el!}
{314}{}{Várjon! Elõbb orvosi ellátásra van szükségem.}
{315}{}{Várjon! Megmérgeztek, gyógyítson meg!}
{316}{}{Várjon! Sugárfertõzött vagyok, gyógyítson meg!}
{317}{}{Csak ennyit akartam. Hamarosan találkozunk, doki.}
{318}{}{Elõször is ellenõriznem kell az életfunkcióit. Kérem, feküdjön le ide...}
{320}{}{Ejnye no. Úgy tûnik, a mûvelet során egy rendszerszintû utasítás felülbírálta az enyémet, és az Auto-doki véletlenül szódium trietilént fecskendezett testébe.}
{321}{}{Mit? Mi van? Mit motyog?}
{322}{}{Csak azt, hogy kevesebb mint tíz másodperc van hátra az életébõl. Az ostobasága minden képzeletet felülmúl! Megzsarol, majd az életét a kezembe adja?! Elképesztõ. Na... viszlát, BARÁTOM! Jó utat!}
{323}{}{Tele a bakancsom, most tölthetem vissza a mentésemet. Ne féljen, doki! Egy perc múlva itt vagyok és akkor KICSINÁLOM!!!}
{324}{}{Hééé... és mi van a Hippokratészi esküvel?! Én...}
{325}{}{...kísérteni fogom a sírból is. Ígérem!}
{326}{}{Hogy jutott be ide? Attól tarok, barátom, el kel mennie. Várjon egy pillanatot, hívok néhány õrt, hogy kikísérjenek!}
{327}{}{ÉN NEM MENNI!}
{328}{}{Várjon egy pillanatot!}
{329}{}{Jó hírem van! Sikerült ellenanyagot készítenem abból a Jetbõl, amit nekem adott.}
{330}{}{Jó hírem van, megtaláltam a Jet ellenszerét. Nem sikerült volna az ön briliáns ötlete nélkül.}
{331}{}{A szervezetbe juttatva megszünteti a drog által okozott eufóriát és enyhíti az elvonási tüneteket is.}
{332}{}{Nagyszerû! Kaphatnék belõle?}
{333}{}{Ez valóban jó hír. Kaphatnék egy adagot? Szeretnék segíteni Redding lakóin.}
{334}{}{Természetesen. Kérem, vigye el a reddingi kollégámnak, Dr. Johnsonnak! Õ majd segít a rászorulókon.}
{335}{}{A Jet-probléma különösen Reddinget érinti. Ha elviszi az ellenanyagot Dr. Johnsonnak, õ majd  eljuttatja a rászorulóknak.}
{336}{}{Rendben van, elviszem Dr.Johnsonnak. Elõtte azonban kérdeznék valamit.}
{337}{}{Köszönöm, doki. Azonnal indulok.}
{338}{}{Nagyszerû! Jöjjön vissza, ha szerzett egy adag Jetet és rögtön megkapja a pénzét!}
{339}{}{Megegyeztünk, de kérdezhetnék még valamit?}
{340}{}{Hamarosan visszajövök a Jettel. Viszlát!}
{341}{}{Igen, ismerem az eljárást. Ez egy olyan beavatkozás, amikor páncéllemezeket és hõelosztó membránokat ültetnek a páciens testébe, hogy segítsen a fizikai trauma és a hõ elviselésében. Miért kérdi?}
{342}{}{Igen, már korábban is említette. Sajnálom, de nem fogom elvégezni az operációt. Az eljárás visszafordíthatatlan és több kárt okoz, mint amennyi haszna van.}
{343}{}{Ezeket a terveket az orvosi adatbázisában találtam. Elvégezne rajtam egy ilyen operációt?}
{344}{}{Végrehajtana egy ilyen mûtétet?}
{345}{}{Kérdeznék valami mást.}
{346}{}{Csak kíváncsiskodtam.}
{347}{}{Értem. Azért bízom benne, hogy találok majd valakit, aki vállalja a beavatkozást.}
{348}{}{Nem, sajnálom. Az implantok beültetése veszélyes eljárás, a felépülési idõ pedig hosszú és fájdalmas. Arról nem is beszélve, hogy akiken végrehajtottuk az operációt, deformálódott a csontvázuk.}
{349}{}{Azért én csak megkockáztatnám. Elvállalja?}
{350}{}{Mint azt már mondtam, NEM! Csak vészhelyzetben végeznék el egy ilyen operációt, a nagyobb biztonságérzete kedvéért nem. Magas a rizikófaktor és az implantok nem nyújtanak nagyobb védelmet, mint egy közönséges harci páncél.}
{351}{}{Akkor kérdeznék valami mást.}
{352}{}{Köszönöm.}
{353}{}{Értem. Azért bízom benne, hogy találok majd valakit, aki vállalja a beavatkozást.}
{354}{}{Sajnálom, de orvosi ellátásban kizárólag Polgárok részesülhetnek. Nem tehetek kivételt, a páciensek adatait egy számítógépen rögzítik... [halkabban kezd beszélni]... A harmadik szinten van néhány stimpakk. Véleményem szerint ezek senkinek se hiányoznának.}
{355}{}{Kösz a tippet. Kérdezhetnék még valamit?}
{356}{}{Nagyszerû. Megyek és megkeresem.}
{357}{}{Természetesen, Kapitány. Mit tehetek önért és a barátaiért?}
{358}{}{Természetesen, Kapitány. Mit tehetek önért és a barátjáért?}
{359}{}{Elõször is ellenõriznem kell az életfunkcióit. Kérem, feküdjön le ide...}
{361}{}{A barátjának nagyon sok lövedék és repesz volt a testében. Kész csoda, hogy egyáltalán még él. Szerencsére sikerült az összeset eltávolítanom.}
{362}{}{Ez majd rendbe hozza. Csak szólnia kell, ha ismét a segítségemre lenne szüksége!}
{363}{}{Megsérültem.}
{364}{}{Sugárfertõzést kaptam.}
{365}{}{Megmérgeztek. Segítene rajtam?}
{366}{}{Köszönöm, doktor. Mondja csak, tud valamit a dermális beültetésekrõl?}
{367}{}{Feltehetnék néhány kérdést?}
{368}{}{Valószínûleg még találkozunk. Viszlát!}
{369}{}{Állok a rendelkezésére, Polgártárs. Mi a probléma?}
{370}{}{Állok a rendelkezésére, Kapitány. Mi a probléma?}
{371}{}{Állok a rendelkezésére. Mi a probléma?}
{372}{}{Megsérültem.}
{373}{}{Sugárfertõzést kaptam.}
{374}{}{Megmérgeztek.}
{375}{}{Meggyógyítaná a barátomat?}
{376}{}{Meggyógyítaná a barátaimat?}
{377}{}{Hallott már a dermális beültetésekrõl?}
{378}{}{Kérdeznék valamit.}
{379}{}{Nem fontos. Viszlát!}
{380}{}{Elõször is ellenõriznem kell az életfunkcióit. Kérem, feküdjön le ide...}
{382}{}{Ettõl majd rendbe jön. Nos, hogy érzi magát?}
{383}{}{Remekül! Meggyógyítaná a barátomat is?}
{384}{}{Remekül! Meggyógyítaná a barátaimat is?}
{385}{}{Tud valamit a dermális beültetésekrõl?}
{386}{}{Sokkal jobban vagyok, köszönöm! Feltehetnék egy kérdést?}
{387}{}{Köszönöm, doktor!}
{388}{}{Elõször is ellenõriznem kell az életfunkcióit. Kérem, feküdjön le ide...}
{390}{}{Ettõl majd rendbe jön. Nos, hogy érzi magát?}
{391}{}{Sokkal jobban, köszönöm! A múltkor említette, hogy van egy védõoltásuk, ami növeli a mérgekkel és a sugárzással szembeni ellenálló képességet. Megkaphatnám?}
{392}{}{Remekül! Meggyógyítaná a barátomat is?}
{393}{}{Remekül! Meggyógyítaná a barátaimat is?}
{394}{}{Hallott már a dermális beültetésekrõl?}
{395}{}{Sokkal jobban vagyok, köszönöm! Feltehetnék egy kérdést?}
{396}{}{Köszönöm, doktor!}
{397}{}{Õrség!}
{398}{}{Zzzzzzz.}
