# Dialog Editor last position: 5
{100}{}{Lydia.}
{101}{}{Ez a barna hajú nõ katonai terepruhát hord. Úgy tûnik, õ a csapos.}
{102}{}{Lydia.}
{103}{}{Ez a barna hajú nõ katonai terepruhát hord. Úgy tûnik, õ a csapos.}
{104}{}{Üdvözöllek! Egy italt, Kiválasztott?}
{105}{}{Üdvözöllek, Kiválasztott! Kérlek, foglalj helyet a bárban!}
{106}{}{Kérlek, foglalj helyet, pihenj egy kicsit!}
{107}{}{Õ a Kiválasztott !!!! Senki sem állhat ellen a Fallout 2 HÕSÉNEK!}
{108}{}{Jó napot, Kapitány!}
{109}{}{Menedékváros mindenek felett, Kapitány!}
{110}{}{Jó napot, Polgártárs!}
{111}{}{Menedékváros mindenek felett, Polgártárs!}
{112}{}{Egy mutáns! Õrség! Õrség!!!}
{113}{}{Egy ghoul! Õrség! Õrség!!!}
{114}{}{Zárva vagyunk. Gyere vissza reggel!}
{115}{}{Sajnálom, késõn jöttél. Gyere vissza holnap!}
{116}{}{Zárva vagyunk. Amint befejeztem a leltározást, lehúzom a rolót.}
{117}{}{Hé, Kiválasztott! Épp a kalandjaidról beszélgettünk... hozhatok neked egy italt?}
{118}{}{Humma..aa... bambinaa... humba aa.}
{119}{}{[Továbbállsz]}
{120}{}{Mit lehet inni?}
{121}{}{Néhány információra lenne szükségem.}
{122}{}{Meghoztam a megbeszélt alkohol szállítmányt.}
{123}{}{Ma nem kérek semmit, köszi.}
{124}{}{Aha... persze. Hmmm... még egyszer kösz, hogy megmentetted a világot, meg minden.}
{125}{}{Humma... aa... hubba... aa... bambaa... djoo ez a aaa... pi aaa...}
{126}{}{[Elbattyogsz]}
{127}{}{Nézd! Lehet, hogy megmentetted a világot meg minden, de pocsék a hangod. Muszáj neked énekelned?}
{128}{}{Hummaaa...da... bumbaa...djoo... ez a piiiaaa...}
{129}{}{[Elslattyogsz]}
#csak a változatosság kedvéért
{130}{}{Nézd, itt van még egy ital, de most már tûnj el, oké? Remélem, amíg iszol, abbahagyod az éneklést.}
{131}{}{Kösz... ikeee... eee...}
{132}{}{[Lelépsz]}
{133}{}{Mit tehetek érted, Kapitány?}
{134}{}{Mit tehetek érted, Polgártárs?}
{135}{}{Üdvözlöm a kedves vendéget. Mivel szolgálhatok?}
{136}{}{Te? Tee? Thee? Tehhhe...hukk .. thheee is úgy beszész, mint a több'ek, amikor meglátnak.}
{137}{}{[Elbattyogsz]}
{138}{}{Innék valamit. Mit ajánlasz?}
{139}{}{Néhány információra lenne szükségem.}
{140}{}{Meghoztam a... szállítmányt. Tudod, amit megbeszéltünk.}
{141}{}{Köszönöm, semmivel, csak benéztem. Viszlát!}
{142}{}{Ez volt a legelbûvölõbb dolog, amit valaha is hallottam. Várj egy kicsit, szólok az õröknek... hadd hallják õk is.}
{143}{}{Túl? Thúl. Túúúhhhl. Túúúhhhl szhekszi a ruhháimhozz}
{144}{}{[Továbbállsz]}
{145}{}{Van szintetikus sörünk és likõrünk, úgymint vodka-H és W, valamint tekila származékok, például W2. Friss vízzel is szolgálhatok, de kapható brahmin-tej is. A sör és likõr tíz dollár, a víz és a tej három.}
{146}{}{Mivel szolgálhatok?}
{147}{}{Vodka-H? Tekila W2?? Igazi alkoholotok nincs?}
{148}{}{Szintetikus sört kérek.}
{149}{}{Egy kupica Vodka-H most jól esne.}
{150}{}{Az a tekila W2 remekül hangzik.}
{151}{}{Csak egy pohár vizet szeretnék.}
{152}{}{Brahmin-tejet kérek.}
{153}{}{Igazából néhány információra lenne szükségem.}
{154}{}{Sajnos most nincs pénzem, de majd benézek még ide. Tetszik ez a hely.}
{155}{}{Értem, köszönöm. Sajnos most mennem kell. Viszlát!}
{156}{}{Tejet?! Bátor ember. Sajnos ezzel pillanatnyilag nem szolgálhatok, persze ha van idõd és megvárod, amíg megfejek egy állatot...}
{157}{}{Megvárom, idõmilliomos vagyok. A tej élet, erõ, egészség... és még a légutakat is tisztíccsa. Szóval, ide vele!}
{158}{}{Inkább kipróbálok valami mást.}
{159}{}{Akkor hagyjuk! Viszont néhány információra lenne szükségem.}
{160}{}{Sajnos nincs idõm, mennem kell. Viszlát!}
{161}{}{Egészségedre! Esetleg... még egy italt?}
{162}{}{Isten ments, ez borzalmas volt. Igazi alkoholotok nincs?}
{163}{}{Szintetikus sört kérek.}
{164}{}{Egy kupica Vodka-H most jól esne.}
{165}{}{A tekila W2-bõl kérek.}
{166}{}{Most inkább csak vizet innék.}
{167}{}{Mulassunk! Brahmin-tejet ide, de ízibe!}
{168}{}{Inkább némi információra lenne szükségem.}
{169}{}{Sajnos elfogyott a pénzem. Viszlát!}
{170}{}{Kösz, nem, mennem kell.}
{171}{}{Éspedig?}
{172}{}{Ki irányítja Menedékvárost?}
{173}{}{Hol van a Menedék?}
{174}{}{Mit tudsz a helyi rabszolgaságról?}
{175}{}{Milyen Menedékváros kapcsolata a külvilággal?}
{176}{}{Innék valamit. Mit ajánlasz?}
{177}{}{Meghoztam a... szállítmányt. Tudod, amit megbeszéltünk.}
{178}{}{Sajnos mennem kell, Viszlát!}
{179}{}{Hát, Lynette Elsõ Polgár, ki más,... de te ugye Polgár vagy? Ezt azért illene tudni.}
{180}{}{Lynette Elsõ Polgár. Ha esetleg beszélni szeretnél vele, a Tanács épületében találod, innen északra.}
{181}{}{Értem. Kérdeznék valami mást.}
{182}{}{Igen, ez a szándékom. Akkor megyek is, viszlát!}
{183}{}{Innen keletre, egy nagy lyuk a hegy oldalában... de nem azt mondtad, hogy Polgár vagy? Ezt akkor tudnod kéne.}
{184}{}{Innen keletre, egy nagy lyuk a hegy oldalában. El sem lehet téveszteni. Azért jobb ha tudod,  oda csak Polgárok léphetnek be.}
{185}{}{Értem. További információkra lenne szükségem.}
{186}{}{Polgár vagyok, csak egy kicsit... ittas.}
{187}{}{Csak tájékozódtam. Már megyek is.}
{188}{}{Kösz, viszlát!}
{189}{}{Hát persze, hogy az vagy... ahogy a kedves vendég óhajtja. Én a helyedben azért kétszer is meggondolnám, kinek mondom azt, hogy "Polgártárs". Esetleg valaki felismeri azokat a lopott papírokat, amit attól a vérszívó Skeev-tól vettél. Csak egy baráti jó tanács. Húzd meg magad, rendben?}
{190}{}{Persze, kösz Lydia. Viszont szükségem lenne még néhány információra.}
{191}{}{Rendben. Viszlát!}
{192}{}{Nézd! Az elsõ dolog, amit meg kell tanulnod, hogy nem hagyhatja el a szádat a "rabszolga" szó, mert komoly zûrbe keveredhetsz. Használd a "szolgák" kifejezést, rendben? Csak egy baráti jó tanács.}
{193}{}{Értem, észben tartom. Kérdeznék még valamit.}
{194}{}{Kösz, mennem kell.}
{195}{}{Nem sokat tudunk a kinti világról. A legtöbb információt a kereskedõk szolgáltatják, akik a "Nagy Kört" járják. Az egyetlen hely, amit ezen a kereskedõ úton kívül ismerek, az Gekkó.}
{196}{}{Mesélj Broken Hillsrõl!}
{197}{}{Mesélj New Renóról!}
{198}{}{Mesélj Reddingrõl!}
{199}{}{Mesélj Gekkóról!}
{200}{}{Másra lennék kíváncsi.}
{201}{}{Kösz, viszlát!}
{202}{}{Broken Hills egy bányász kommuna, hasonlít Reddinghez. Annyit tudok róla, hogy messze délen van és az uránszállítmányaink nagy részét onnan kapjuk.}
{203}{}{Mesélj New Renóról!}
{204}{}{Mesélj Reddingrõl!}
{205}{}{Mesélj Gekkóról!}
{206}{}{Másra lennék kíváncsi.}
{207}{}{Kösz, viszlát!}
{208}{}{Dél-nyugatra találod. Egymásnak ellentmondó véleményeket hallottam Renóról. Néhány kereskedõ, különösen a rabszolga-kereskedõk, imádják a helyet, mások meg nagy ívben kerülik. Rengeteg a csillogás és a balhé is arrafelé, ahogy hallom.}
{209}{}{Mesélj Broken Hillsrõl!}
{210}{}{Mesélj Reddingrõl!}
{211}{}{Mesélj Gekkóról!}
{212}{}{Másra lennék kíváncsi.}
{213}{}{Kösz, viszlát!}
{214}{}{Az egy bányaváros messze nyugaton. Az utóbbi idõben nem sok karaván érkezett onnan és ez a fejeseket egy kicsit aggasztja. Fõként McClure Fõtanácsost.}
{215}{}{Mesélj Broken Hillsrõl!}
{216}{}{Mesélj New Renóról!}
{217}{}{Mesélj Gekkóról!}
{218}{}{Másra lennék kíváncsi.}
{219}{}{Kösz, viszlát!}
{220}{}{Az egy ghoul város, kevesebb mint egy napi járásra észak-kelet felé. Azt beszélik, hogy minden utazót foglyul ejtenek, aki belép a területükre. Jobb messzire elkerülni azt a helyet.}
{221}{}{Mesélj Broken Hillsrõl!}
{222}{}{Mesélj New Renóról!}
{223}{}{Mesélj Reddingrõl!}
{224}{}{Másra lennék kíváncsi.}
{225}{}{Kösz, viszlát!}
{226}{}{Igazi?! Minek az? Nagyon ütõs anyag ez, hidd el nekem! Egyszer, az egyik kedves vendég annyira berúgott, állat módjára úgy leittasodott, hogy...}
{227}{}{Nem ezzel van a baj. Nem is tudom, a színe... a zamata... az illata. Vagy te még sose ittál igazi alkoholt?}
{228}{}{Igazad van, nincs ezekkel semmi baj. Kérdeznék még valamit.}
{229}{}{Te tudod. Viszlát!}
{230}{}{De... egyszer. Ismertem egy kereskedõt, akinek volt egy üveg Maddog 30/30-a és meghívott egy pohárkára. Keserû cucc, utána nem éreztem a nyelvemet, de... üdítõen más volt.}
{231}{}{Ugye? És mi történt azután?}
{232}{}{Ahogy mondod. Egyébként kérdezhetnék még valamit?}
{233}{}{Értem. Viszlát!}
{234}{}{Nem nehéz kitalálni, berúgtunk, mint az albán szamár. Tivornyázás közben persze akadt néhány segítõkész száj is, akikkel közösen benyeltük a készletet. Bár a kereskedõ aranyárban mérte az italt, tolongtak érte a cimborák.}
#Ezt a szamarat nem tudtam kihagyni (Bass) :)
{235}{}{Errõl beszéltem, és... tudod, mit? Szereznék neked eredeti italokat, amin szép haszonnal túladhatnál. Mit szólsz?}
{236}{}{Nagy buli lehetett. Kérdezhetnék még valamit?}
{237}{}{Értem, most mennem kell.}
{238}{}{Sajnálom, de Menedékvárosban kizárólag mesterséges alkoholt szolgálhatunk fel... [körbepillant, majd közelebb hajol]... persze, ha lenne egy ügyes ember, aki bejuttatna a kapun egy szállítmány eredetit...}
{239}{}{Ügyes?! Errõl vagyok híres... többek között. Ez utóbbit azért ne nagyon firtassuk! Egész pontosan, mire is lenne szükséged?}
{240}{}{Mondjuk tíz üveg jó minõségû égetett szeszre és tíz üveg sörre. De ne az a radioaktív lötty legyen, ami Gekkóból jön, csak a régi, hagyományos, jó öreg "pia" érdekel. Mindez maximális titoktartás mellett. Rendben?}
{241}{}{Ennyi épp van nálam. Tessék.}
{242}{}{Nem lesz gond, leszállítom az árut és köztünk marad az ügy. De kérdeznék még valamit.}
{243}{}{Nem is tudom, még gondolkodom a dolgon. Viszlát!}
{244}{}{Nagyszerû! Tessék a pénzed... pont a duplája annak, amennyit érnek. És ez a tranzakció meg se történt, rendben?}
{245}{}{Természetesen. Egyébként kérdezhetek valamit?}
{246}{}{Kösz, öröm veled üzletelni.}
{247}{}{Szó sem lehet róla. Azok a pusztából származó készítmények illegálisak itt, Menedékvárosban. Még azt sem akarom tudni róluk, hogy léteznek. Adhatok valamit inni, Kapitány?}
{248}{}{Nincs semmi rossz egy kis alkoholban. Persze az észlelésed ideiglenesen megsínyli a fogyasztásukat, de hát ugyanez történik, ha túl sok gyógyító port használsz.}
{249}{}{Az bizony jól esne.}
{250}{}{Felejtsd el, hogy megkérdeztem! Néhány információra lenne szükségem.}
{251}{}{Értem, rendben van.}
{252}{}{Mi csak legális, szintetikus italokat tartunk. Ha esetleg valami módon igazi alkohol kerülne Menedékvárosba, arról nekem nem kell tudnom.}
{253}{}{Néhány információra lenne szükségem.}
{254}{}{Értem. Mindenesetre kösz.}
{255}{}{Értem... Nos, hmmm... vigyázz magadra, oké?}
{256}{}{Köszi... keee... eee...}
{257}{}{[Otthagyod]}
{258}{}{Zzzzzzzz.}
