# Dialog Editor last position: 5
{100}{}{Egy foghíjas embert látsz koszos, kék pulóverben. Erõsen bûzlik a brahmintól.}
{101}{}{Ed, a brahmin-kereskedõ.}
{102}{}{Kibaszott brahminok! Abba nem hagynák a bõgést.}
{103}{}{Esküszöm, hallottam, ahogy az egyik brahmin megszólalt. "Mondom, múúú!"... vagy valami ilyesmi.}
{104}{}{Idén alacsony a brahmin ára.}
{105}{}{Nem tudok rájönni, honnan lesz ez a sok brahminszar. Hirtelen csak úgy megjelenik.}
{106}{}{Üdvözöllek, idegen. Ed vagyok, a helyi brahmin-kereskedõ. Segíthetek?}
{107}{}{Üdv, örülök, hogy újra látlak. Mit tehetek érted?}
{108}{}{Ismersz egy Vic nevû kereskedõt? Azt mondta, hogy tõled vette ezt a kulacsot.}
{109}{}{Ismersz egy Vic nevû kereskedõt?}
{110}{}{Az egyik társam, Vic azt állítja, hogy évekkel ezelõtt vett tõled egy kulacsot.}
{111}{}{Eszedbe jutott már, hogy honnan szerezted a kulacsot?}
{112}{}{Egy Menedéket keresek.}
{113}{}{Mi a véleményed Menedékvárosról?}
{114}{}{Mit csinálsz itt?}
{115}{}{Viszlát!}
{116}{}{Vic?}
{117}{}{Eladtál neki egy kulacsot? Egy 13-as feliratút?}
{118}{}{Mindegy. Mennem kell.}
{119}{}{Nálad van? Talán felfrissítené az emlékezetem.}
{120}{}{Mindegy. Másra lennék kíváncsi.}
{121}{}{Talán elõkeríthetem. Késõbb visszajövök.}
{122}{}{Hmm... igen, dereng valami. Egy kulacs? Miért érdekel?}
{123}{}{Hmm... igen, dereng valami. Egy kopaszodó, dagadt fickó, bõr mellényben. Emlékszem rá. Mi van vele?}
{124}{}{Elárulnád, honnan származik?}
{125}{}{Azt mondta, eladtál neki egy kulacsot.}
{126}{}{Egyszerû kíváncsiság. Kösz.}
{127}{}{Õszintén szólva nem emlékszem pontosan, de azt hiszem, az egyik brahmin-karavánutam során szereztem.}
{128}{}{Brahmin-karavánút?}
{129}{}{Értem. Köszönöm a segítséget.}
{130}{}{Amikor fiatalabb voltam, brahmin-karavánokat vezettem át a 'Nagy Körön'... Broken Hills, New Reno, Redding, Rejtek, Modoc és aztán vissza ide. Egy idõ után már túl veszélyessé vált az út, ezért letelepedtem itt.}
{131}{}{Hol vannak ezek a helyek?}
{132}{}{Értem. Kösz az információt.}
{133}{}{Bejelölöm a térképeden. Látod, itt van Broken Hills, attól egy kicsit nyugatra Reno, északnyugatra pedig Redding. Ha innen északnak fordulsz, Rejtekbe jutsz, attól keletre meg Modoc van. Ha továbbra is keletnek tartasz visszajutsz ide, Menedékvárosba.}
{134}{}{Van tipped, hogy a kulacsot melyik helyen szerezted?}
{135}{}{Kösz, most mennem kell.}
{136}{}{Sajnálom, de nem emlékszem, az már nagyon rég volt. Miért akarod tudni?}
{137}{}{Azt a Menedéket keresem, ahonnan a kulacs származik.}
{138}{}{Nem érdekes, mennem kell.}
{139}{}{Hát ha Menedéket keresel, akkor van egy Menedékváros falain túl.}
{140}{}{Ami a városban van, az a 13-as Menedék?}
{141}{}{Köszönöm. Viszlát!}
{142}{}{Gõzöm sincs, de a Menedék központi számítógépe talán meg tudja mondani. Minden kibaszott adatot abban tárolnak.}
{143}{}{Kérdeznék valami mást.}
{144}{}{Köszönöm.}
{145}{}{Rendben. Mit szeretnél tudni?}
{146}{}{Ismersz egy Vic nevû kereskedõt? Azt mondta, hogy ezt a kulacsot tõled vette.}
{147}{}{Ismersz egy Vic nevû kereskedõt?}
{148}{}{Az egyik társam, Vic azt állítja, hogy évekkel ezelõtt vett tõled egy kulacsot.}
{149}{}{Eszedbe jutott már, honnan szerezted azt a kulacsot?}
{150}{}{Egy Menedéket keresek.}
{151}{}{Mit tudsz Menedékvárosról?}
{152}{}{Mit csinálsz itt?}
{153}{}{Viszlát!}
{154}{}{Van egy a város központjában, azt megnézted már? Lehet hogy az az.}
{155}{}{Van egy a város központjában, talán az lesz az.}
{156}{}{Lehet. Volna még egy kérdésem.}
{157}{}{Meglehet. Kösz a tippet.}
{158}{}{Nem rossz hely ez... ha megszokod a Polgárokat. Néhányuktól viszket a tenyerem, de azért egész jó életem van itt.}
{159}{}{Másra lennék kíváncsi.}
{160}{}{Értem. Kösz a segítséget. Viszlát!}
{161}{}{Brahminokat árulok. Ebbõl tartom el magam és fizetem a védelmi pénzt az õröknek.}
{162}{}{Kérdeznék valami mást.}
{163}{}{Értem. Viszlát!}
{164}{}{Nálad bármelyik brahminom okosabb. Kifelé!}
{165}{}{Úgy tûnik, ez Ed lakhelye. Õ az, akitõl a kulacsot vettem.}
{166}{}{Megtaláltad a kulacs korábbi tulajdonosát.}
