# Dialog Editor last position: 5
{100}{}{Ez a Polgár világoskék kezeslábast hord. Olyan mint a Menedéklakóé, csak nincs rajta szám.}
{101}{}{Holden, a "B" Komfort Osztály vezetõje.}
{102}{}{Ez a Polgár világoskék kezeslábast hord. Olyan mint a Menedéklakóé, csak nincs rajta szám.}
{103}{}{::tapsol::}
{104}{}{Nézzétek! A hõsünk!}
{105}{}{Emberek! A hõsünk itt van Menedékvárosban!}
{106}{}{Jó napot, Kapitány.}
{107}{}{Menedékváros mindenek felett, Kapitány!}
{108}{}{Jó napot, Polgártárs!}
{109}{}{Menedékváros mindenek felett, Polgártárs!}
{110}{}{Egy mutáns! Õrség! Õrség!!!}
{111}{}{Egy ghoul! Õrség! Õrség!!!}
{112}{}{Lássuk csak ... három stimpakk, egy doboz Rad-X.}
{113}{}{Randal még mindig hiányolja a leltár-jegyzéket.}
{114}{}{Lássuk csak! Át kell nézni a készletet, megcsinálni a leltárt, le kell ellenõrizni a listákat, aztán felvinni a gépre.}
{115}{}{Pótolni kell az elhasznált elsõsegély csomagokat.}
{119}{}{Sajnálom, de a "B" Komfort Osztály este zárva tart.}
{120}{}{Gyere vissza reggel! Zárva vagyunk.}
{121}{}{Most épp leltározok. Holnap nyitva leszünk.}
{122}{}{Segíthetek, Kapitány?}
{123}{}{Segíthetek, Polgártárs?}
{124}{}{Igen? Mit akarsz?}
{125}{}{Mida... karsz.}
{126}{}{[Továbbállsz]}
{127}{}{Én is örülök, hogy látlak. Mi ez a hely?}
{128}{}{Vásárolni szeretnék.}
{129}{}{Tõled? Semmit.}
{130}{}{Nagyszerû! Megint egy ostoba Kívülálló. Õrség! Van itt egy fickó, akit ki kellene kísérni.}
{131}{}{NEM SZERET ÕRT. TE NYÚVADNI KI}
{132}{}{*Szipp* Én MEGY az ÕRÖK}
{133}{}{Tudnod kell, hogy ez itt nem a piac, fiam. Legközelebb Boldog Harry boltjában vásárolj!}
{134}{}{Úgy lesz, köszönöm.}
{135}{}{Ez itt nem... a piac?! Bocsánat, hülye vagyok, szegény apámtól örököltem. Na, tûnjünk innen!}
{136}{}{Menedékváros mindenek felett, Polgártárs!}
{137}{}{Menedékváros mindenek felett, Kapitány!}
{138}{}{Menedékváros mindenek felett, Polgártárs!}
{139}{}{Jó napot, Polgártárs!}
{140}{}{Ez? Ez a "B" Komfort Osztály és Menedékváros gyógyszer ellátásával foglalkozunk. Én Holden vagyok, az Osztály vezetõje. Miben lehetek a segítségedre, Polgártárs?}
{141}{}{Ez itt a "B" Komfort Osztály és Menedékváros gyógyszer ellátásával foglalkozunk. Ezt kerested?}
{142}{}{Láthatnám a készleteket?}
{143}{}{Igen. Láthatnám a készleteket?}
{144}{}{Nem. Viszlát!}
{145}{}{Talán. Viszlát!}
{150}{}{Ez? Ez a "B" Komfort Osztály és Menedékváros gyógyszer ellátásával foglalkozunk. Én Holden vagyok, az Osztály vezetõje. Miben lehetek a segítségedre, Kapitány?}
{151}{}{Hé! Azt hagyd békén!}
{152}{}{Elég! Mars ki innen!}
{153}{}{Kösz.}
{154}{}{[tovább]}
