# Dialog Editor last position: 5
{100}{}{Menedékváros egyik õrét látod.}
{101}{}{Egy szúrós tekintetû õrt látsz. Fémpáncélt visel, és egy sörétes puskát szorongat a kezében.}
{102}{}{Hé! Tûnj onnan!}
{103}{}{Egyszer már figyelmeztettünk.}
{104}{}{Odass! Õ az, aki legyõzte az Enklávét! Azonnal nyissátok ki a kaput!}
{105}{}{Jó napot, Kapitány!}
{106}{}{Uram! Örülök, hogy láthatom, uram!}
{107}{}{Uram, igenis, uram!}
{108}{}{Menedékváros mindenek felett, Kapitány!}
{109}{}{Elnézésedet kérem, Polgártárs, de ghoulok nem léphetnek be Menedékváros területére.}
{110}{}{Elnézésedet kérem, Polgártárs, de mutánsok nem léphetnek be Menedékváros területére.}
{111}{}{Jobb lesz, ha az a ghoul hátrébb lép a kaputól. Most rögtön!}
{112}{}{Jobb lesz, ha az a mutáns hátrébb lép a kaputól. Most rögtön!}
{113}{}{Jó napot, Polgártárs!}
{114}{}{Örülök, hogy látlak, Polgártárs!}
{115}{}{Menedékváros mindenek felett, Polgártárs!}
{116}{}{Tûnés innen!}
{117}{}{Kopj le!}
{118}{}{Valami baj van? Vagy épp keresel magadnak egyet?}
{119}{}{Nem akarlak bántani... ha nem muszáj.}
{120}{}{Minden rendben, beléphetsz.}
{121}{}{Jó napot, utazó!}
{122}{}{Üdvözöllek!}
{123}{}{Az Enklávé elleni harcod nagy hatással volt még az Elsõ Polgárra is.}
{124}{}{Azt hallottam, hogy délen egész San Francisco-ig merészkedtél. Igaz ez?}
{125}{}{Igaz, hogy az Egyesült Államok még mindig háborúban áll?}
{126}{}{Felvihetnéd az utazásaid történetét Menedékváros számítógépére.}
{127}{}{Szívesen látunk Menedékvárosban. Addig maradsz, ameddig csak akarsz.}
{128}{}{Szép rendben katalogizálnod kellene az Enklávé elleni tetteidet, és feltenni a Lista Szerverre.}
{129}{}{Ghoulok nem léphetnek be. Fogd azt az... izét, és tûnjetek innen! Most rögtön!}
{130}{}{Mutánsok nem léphetnek be. Tüntesd el innen azt a... teremtményt! Most rögtön!}
{131}{}{Lassan a testtel, barátom! Nem léphetsz be oda a megfelelõ engedély nélkül.}
{132}{}{Ehng-edh-éj?}
{133}{}{[Elpályázol]}
{134}{}{Megfelelõ engedély?}
{135}{}{Bocsánat.}
{136}{}{Úgy látom, a Kívülállók beltenyészetének egy tipikus példányával állunk szemben. Nézd, setét barátom! Tûnj innen, mielõtt megsérülsz! Rendben?}
{137}{}{ÉN NEM LENNI SETÉTT!}
{138}{}{[Elpályázol]}
{139}{}{Ahogy mondod, "megfelelõ engedély".}
{140}{}{Ha be akarsz jutni Menedékvárosba, Wallace-szal, a vámparancsnokkal beszélj! Tõle kaphatsz Napi Belépõt... indokolt esetben.}
{141}{}{Hol találom Wallace-t?}
{142}{}{Napi Belépõ? Mi az?}
{143}{}{Értem, köszönöm.}
{144}{}{A Vámhivatal épületében dolgozik, tõled jobbra.}
{145}{}{Most pedig menj! Nincs idõm Kívülállókkal fecserészni.}
{146}{}{Mi az a Napi Belépõ?}
{147}{}{Köszönöm, hogy szakítottál rám idõt. Viszlát!}
{148}{}{Egy kártya, amivel jogosult vagy sötétedésig a városban tartózkodni.}
{149}{}{Most pedig menj! Nincs idõm Kívülállókat pesztrálni.}
{150}{}{Hol találom Wallace-t?}
{151}{}{Köszönöm, hogy szakítottál rám idõt. Viszlát!}
{152}{}{Ha be akarsz jutni, Napi Belépõre lesz szükséged.}
{153}{}{Szerezz egy Napi Belépõt, és beengedlek!}
{154}{}{Maradj távol a kaputól!}
{155}{}{Ne bámészkodj!}
{156}{}{Van Napi Belépõd?}
{157}{}{Sajnos nincs.}
{158}{}{Nincs, mivel nincs rá szükségem. Polgár vagyok.}
{159}{}{Mire véljem ezt, Polgártárs?! Nem szoktam hozzá az ilyen hangnemhez. Tessék, az igazolványom.}
{160}{}{Egy Polgár, mi? Na, mutasd csak az igazolványod... "Polgártárs"!}
{161}{}{Oppsz... nézzenek oda... hát nem otthon felejtettem?}
{162}{}{Tessék.}
{163}{}{Elnézést, félreértettük egymást. Tulajdonképpen csak az érdekel, hogy juthatok be a kapun.}
{164}{}{Elnézésedet kérem, Polgártárs, nem akartalak megsérteni. NYISSÁTOK KI A KAPUT!}
{165}{}{Köszönöm.}
{166}{}{Ne nézz minket bolondnak, Kívülálló! Ha be akarsz jutni, beszélj Wallace-szal és kérj tõle egy Napi Belépõt! Eszedbe ne jusson még egyszer ezzel próbálkozni, megértetted?}
{167}{}{Természetesen, elnézést.}
{168}{}{Hmmmm... érvényesnek tûnik. Furcsa, de nem emlékszem rád.}
{169}{}{Arra semmi szükség. Elég ha megsasolod azt az írást, fiam!}
{170}{}{Nem neheztelek, Polgártárs, ilyesmi velem is elõfordult már.}
{171}{}{Ki érti ezt? Pedig én tisztán emlékszem rád... kedves... izomagy.}
{172}{}{Bizonyára csak elkerültük egymást, Polgártárs.}
{173}{}{Ó... igen? Nézd! Nem tudom, ki vagy, de hogy nem Polgár, az egészen biztos. Add csak ide azt az igazolványt és kotródj innen! Ha be akarsz jutni, kérj te is egy Napi Belépõt Wallace-tól, mint bárki más.}
{174}{}{Ezt az igazolványt akarod? Gyere és vedd el!}
{175}{}{Elnézést, mit is kell tennem, hogy Napi Belépõt kaphassak?}
{176}{}{Rendben. Viszlát!}
{177}{}{Nos... rendben, NYISSÁTOK KI A KAPUT! Menedékváros mindenek felett!}
{178}{}{Mi van?... Ja persze... Menedékváros mindenki felett!}
{179}{}{Köszönöm.}
{180}{}{Kérem a Napi Belépõt.}
{181}{}{Tessék.}
{182}{}{Nekem nem kell Napi Belépõ. Polgár vagyok.}
{183}{}{Csak egy pillanatra beugranék megnézni, hogy mi a helyzet.}
{184}{}{Nincs idõm csevegni, értve vagyok? Na, tûnés innen!}
{185}{}{Oké, oké. Csak barátságos próbáltam lenni.}
{186}{}{(Távozik.)}
{187}{}{Rendben, de mielõtt belépsz, át kell kutatnom a holmidat.}
{188}{}{Semmi akadálya.}
{189}{}{Miért van erre szükség? Mit keresel?}
{190}{}{Arról szó sem lehet. Inkább elmegyek.}
{191}{}{Megállni! Kívülállók sötétedés után nem mehetnek a városba!}
{192}{}{De hát van Napi Belépõm.}
{193}{}{Miért? Én Polgár vagyok.}
{194}{}{Értem, viszlát!}
{195}{}{Polgár vagy? Úgy, mint múltkor, igaz? Na, add csak ide azt a "polgársági igazolványt" és takarodj innen!}
{196}{}{Erre gondolsz, barátom?... [meglobogtatod a papírt]... gyere, és vedd el! Képes vagy rá?}
{197}{}{Elnézést, már itt sem vagyok.}
{198}{}{Menj és beszélj Wallace-szal, a Vámparancsnokkal! És... még valami. Kezdelek unni. Ha nem akarsz megsérülni, jobban teszed, ha lekopsz.}
{199}{}{Már itt sem vagyok.}
{200}{}{Igen, de ugye NAPI Belépõd van? És szerinted most nappal van? Lelépni!}
{201}{}{Oké, oké.}
{202}{}{A Kívülállók néha megpróbálnak alkoholt, vagy függõséget okozó drogokat, például Buffoutot, Jetet, Pszichót vagy Mentátot csempészni a városba. Ilyesmiket keresünk.}
{203}{}{Értem. Tiszta vagyok, kutass át csak nyugodtan!}
{204}{}{Tulajdonképpen semmi dolgom Menedékvárosban. Viszlát!}
{205}{}{Sajnálom, de a drogok és az alkohol tiltólistán vannak, ezekkel nem léphetsz be. Dobd õket az árokba, aztán gyere vissza! Rendben?}
{206}{}{Oké, egy perc és itt vagyok.}
{207}{}{Úgy néz ki, minden rendben van. Bemehetsz.}
{208}{}{Köszönöm.}
{209}{}{Ighen. Heer}
{210}{}{Byeeee}
{211}{}{Hmmmm... [érdeklõdve tanulmányoz egy ideig, majd megvonja a vállát]}
{212}{}{Okhéééj.}
{213}{}{Nyem. Byeeee}
{214}{}{Rhendbhen}
{215}{}{Ighhen.}
