# Dialog Editor last position: 5
{100}{}{Egy falubélit látsz.}
{101}{}{Egy falubélit látsz.}
{102}{}{Hello.}
{103}{}{Jó napot.}
{104}{}{Üdvözöllek a falunkban.}
{105}{}{Szörnyek oltalmaznak minket.}
{106}{}{Siess vissza!}
{107}{}{Hamarosan szükségünk lesz a fegyverekre.}
{108}{}{Hello.}
{109}{}{Menj!}
{110}{}{Menj vissza oda, ahonnan jöttél!}
{111}{}{Menj innen a francba!}
{112}{}{Most biztonságban vagyunk.}
{113}{}{Köszönöm!}
{114}{}{Légy áldott, vándor!}
