# Dialog Editor last position: 5
{100}{}{Egy Polgárt látsz világoskék kezeslábasban, ami olyan, mint a Menedéklakó ruhája, csak nincs szám a hátán.}
{101}{}{Egy Mendékvárosi Polgárt látsz.}
{102}{}{Egy Polgárt látsz világoskék kezeslábasban, ami olyan, mint a Menedéklakó ruhája, csak nincs szám a hátán.}
{103}{}{::tapsol::}
{104}{}{Itt a hõsünk! Nézd!}
{105}{}{Szavamra! A hõsünk itt, Menedékvárosban!}
{106}{}{Jó napot, Kapitány!}
{107}{}{Menedékváros mindenek felett, Kapitány!}
{108}{}{Marad vacsorára, Kapitány?}
{109}{}{Jó napot, Polgártárs!}
{110}{}{Menedékváros mindenek felett, Polgártárs!}
{111}{}{Maradsz vacsorára?}
{112}{}{Egy mutáns! Õrség! Õrség!!!}
{113}{}{Egy ghoul! Õrség! Õrség!!!}
{114}{}{Kérlek, töröld meg a lábad, mielõtt belépsz a házba!}
{115}{}{Elnézést, meghívtunk volna?}
{116}{}{Segíthetek?}
{117}{}{Ti, Kívülállók sosem tanultok jó modort.}
{118}{}{Tipikus Kívülálló viselkedés. Betolakodtok ide.}
{119}{}{Hallottam bátor tetteidrõl. Nagy szolgálatot tettél Menedékvárosnak... és az egész világnak.}
{120}{}{Az Enklávé elleni harcod nagy hatással volt még az Elsõ Polgárra is.}
{121}{}{Úgy hallottam, hogy dél felé egészen San... Fran... Ciscó-ig is eljutottál. Igaz ez?}
{122}{}{Tán Menedékvárosnak kellene üdvözölnie a Kívülállókat ?}
{123}{}{Ez igaz? A régi világkormány még mindig háborúzik?}
{124}{}{Az utazásaidat be kellene táplálni Menedékváros számítógépébe, hogy mindenki olvashasson róla.}
{125}{}{Szívesen látunk, addig maradsz, amíg jólesik.}
{126}{}{Felvihetnéd az Enklávé elleni tetteidet egy csinos, rendezett kis listába.}
{127}{}{*Ásít* ...hrmnnn? Igen? Hogy mi?}
{128}{}{Kicsit késõ van már a látogatáshoz.}
{129}{}{A LEGTÖBB Polgár már aludna ilyenkor.}
{130}{}{Aludni? Nem, már nem.}
{131}{}{Kérlek, gyere vissza reggel! Nagyon nehéz napom volt, rengeteg listát készítettem.}
{132}{}{Jó napot, Kapitány!}
{133}{}{Menedékváros mindenek felett, Kapitány!}
{134}{}{Marad vacsorára, Kapitány? A szolgánk pompás gulyást készített.}
{135}{}{Néhány fánkot, Kapitány?}
{136}{}{Valami baj van, Kapitány?}
{137}{}{Remélem, nem azok a piszkos Kívülállók okoznak gondot már megint, Kapitány.}
{138}{}{Vinne egy kis harapnivalót az õrségnek, Kapitány?}
{139}{}{Jó napot, Polgártárs!}
{140}{}{Menedékváros mindenek felett, Polgártárs!}
{141}{}{Mint minden hasznos Polgárnak, nekünk is kötelességünk listákat készíteni és karbantartani.}
{142}{}{Kérlek, maradj vacsorára, Polgártárs! A szolgánk  pompás gulyást készített.}
{143}{}{A nap nagyobb részét egy hosszú lista betáplálásával és ellenõrzésével töltöttem. Imádok listákat készíteni.}
{144}{}{A Lista Hivatalban dolgozom, ahogy a legtöbbünk. Mi itt Menedékvárosban imádunk listákat készíteni.}
{145}{}{A mai nap nagy részét a Lista Hivatalban töltöttem. Kiváló, értékes, produktív munka volt.}
{146}{}{Hallottam, hogy sokat utaztál a pusztaságban. Hogy élted túl a megpróbáltatásokat a piszkos Kívülállók között?}
{147}{}{Ó! Te vagy az új Polgár. Üdvözöllek Menedékvárosban!}
{148}{}{Van hol aludnod, amíg a városban vagy?}
{149}{}{A Tanács jól képviseli az érdekeinket.}
{150}{}{Ügyelnünk kell gyönyörû városunk tisztaságára.}
{151}{}{Minden család kap egy szobát a közös házban.}
{152}{}{A város mindent megad nekünk, amire csak szükségünk van.}
{153}{}{A szolgák? Csak alantas feladatokra használjuk õket.}
{154}{}{Szereznem kell egy szolgát a raktár kitakarításához.}
{155}{}{Egy szolgának még maradnia kell, nincs rendesen kigyomlálva a kert.}
{156}{}{A tegnapi Tanácsülés nagyon produktív volt. Rengeteg listát készítettünk. Mi itt Menedékvárosban imádunk listákkal foglalkozni.}
{157}{}{Igen?}
{158}{}{Elnézést, segíthetek?}
{159}{}{Úgy helyénvaló, ha megkérdezed a házigazdát, mielõtt a házába lépsz.}
{160}{}{Kérlek, töröld meg a lábad, mielõtt belépsz a házba!}
{161}{}{Te ki vagy? Meghívtunk volna?}
{162}{}{Mit keresel itt?}
{163}{}{Ti, Kívülállók annyira modortalanok vagytok.}
{164}{}{A város mindent megad nekünk, amire csak szükségünk van.}
{165}{}{A szolgák? Csak alantas feladatokra használjuk õket.}
{166}{}{Szereznem kell egy szolgát a raktár kitakarításához.}
{167}{}{Egy szolgának még maradnia kell, nincs rendesen kigyomlálva a kert.}
{168}{}{Igen, érzem ... látom, hogy Kívülálló vagy.}
{169}{}{Kívülálló vagy? Milyen furcsa.}
