{100}{}{Egy falubélit látsz.}
{101}{}{Egy falubélit látsz.}
{102}{}{Helló!}
{103}{}{Jó napot.}
{104}{}{Welcome to our village.}
{105}{}{Szörnyek oltalmaznak minket.}
{106}{}{Siess vissza!}
{107}{}{Hamarosan szükségünk lesz a fegyverekre.}
{108}{}{Helló!}
{109}{}{Menj!}
{110}{}{Menj vissza oda, ahonnan jöttél!}
{111}{}{Menj innen a francba!}
{112}{}{Most biztonságban vagyunk.}
{113}{}{Köszönöm.}
{114}{}{Légy áldott, vándor!}
