# Dialog Editor last position: 5
{100}{}{Gregory Fõbiztos.}
{101}{}{Egy komor tekintetû bürokratát látsz. Keskeny arc, vastag szemöldök.}
{102}{}{Gregory Fõbiztos.}
{103}{}{Egy komor tekintetû bürokratát látsz. Keskeny arc, vastag szemöldök.}
{104}{}{Bátor tetteidért Menedékváros minden rendszeréhez teljes hozzáférést kaptál. Ó... és az Elsõ Polgár azt üzente, látni kíván.}
{105}{}{Behatoló! Õrség! Õrség!!!}
{106}{}{Egy mutáns! Õrség! Õrség!!!}
{107}{}{Egy ghoul! Õrség! Õrség!!!}
{108}{}{Jó napot, Kapitány!}
{109}{}{Menedékváros mindenek felett, Kapitány!}
{110}{}{Jó napot, Polgártárs!}
{111}{}{Menedékváros mindenek felett, Polgártárs!}
{112}{}{Listák, listák, listák! Csodálatos! Imádom a listákat.}
{113}{}{Ma még csinálnom kell az 534-esbõl egy 412-est.}
{114}{}{Egy összegzõ listára van szükségem a 43A-tól 121B-ig terjedõ anyagokból.}
{115}{}{Csodálatos nap elé nézünk. Sok lista vár még ránk.}
{116}{}{Mielõtt lefekszem, leellenõrzöm ezeket a tesztlapokat.}
{117}{}{Jöjjön vissza holnap, ma már nem lesz idõm magával foglalkozni!}
{118}{}{Mocskos mutáns!}
{119}{}{Nem tudom, hogy lett magából Polgár. Számomra nem más, csak egy felfuvalkodott mutáns.}
{120}{}{Nem tudom, hogy lett magából Kapitány. Számomra nem más, csak egy arrogáns betolakodó.}
{121}{}{Mit óhajt? Fogja rövidre, rendkívül elfoglalt vagyok!}
{122}{}{Segitni nekem!}
{123}{}{[Elbattyogsz]}
{124}{}{Kihez van szerencsém?}
{125}{}{Elnézést a zavarásért. Viszlát!}
{126}{}{Már MEGINT egy szolga, aki csak úgy elkószált a helyérõl?! Jelenteni fogom Barkus hanyagságát. Hé te... tûnés innen! Hess, iszkiri, iszkiri!}
{127}{}{Én lelõ téged! Te kinyúvadol.}
{128}{}{[Elbattyogsz]}
{129}{}{Elképesztõ! Ezek a szolgák percrõl-percre hülyébbek.}
{130}{}{Gregory Fõbiztos vagyok. Engem keres?}
{131}{}{Fõbiztos?! Mi a fene az a Fõbiztos?}
{132}{}{Nem is tudom. Mit csinál itt?}
{133}{}{Nem. Viszlát!}
{134}{}{Az Elsõ Polgár ASSZISZTENSE vagyok. Beosztom az idejét, vizsgáztatom a Polgárságra áhítozó jelölteket, frissítem a listákat. Biztosíthatom, nem kis feladat.}
{135}{}{Mi ez a polgársági teszt?}
{136}{}{Most, hogy szóba hozta, újra megpróbálnám a Polgársági tesztet.}
{137}{}{Feltehetnék néhány kérdést?}
{138}{}{Értem. Most mennem kell.}
{139}{}{Ha helyesen kitölti a tesztlapot, Polgár státuszt kap.}
{140}{}{Az én tisztem, hogy a Polgársági teszt segítségével megbizonyosodjak róla, megfelel-e az illetõ a magas szintû követelményeknek.}
{141}{}{Tulajdonképpen mibõl áll egy ilyen teszt?}
{142}{}{Szeretnék újra próbálkozni.}
{143}{}{Milyen elõnyökkel jár a polgári státusz?}
{144}{}{Feltehetnék néhány kérdést?}
{145}{}{Értem. Viszlát!}
{146}{}{Elõnyökkel?! Hát csak nézzen körül! Menedékváros a legbiztonságosabb és leggazdagabb város az egész pusztaságban. A Polgárok ingyenes orvosi ellátásban részesülnek, vízbõl és élelembõl bõség van. Nincs bûnözés, nincsenek járványok.}
{147}{}{Mibõl áll egy ilyen teszt?}
{148}{}{Jól hangzik. Megpróbálkozhatok vele?}
{149}{}{Feltehetnék néhány kérdést?}
{150}{}{Értem. Most mennem kell.}
{151}{}{Ez egy átfogó vizsga néhány alrészre bontva. Magas szintû matematika, térbeli kapcsolatok, levezetéses okfejtés, nyelvtan... ó... és van orvosi felülvizsgálat is.}
#Ez, mint mar emlitettem, nem jo. A physical az nem fizikai. A kesobbiek ismereteben ez a megfelelo.

{152}{}{Hogy mondta? Magas szintû mate-ma-miii? Nincs egy berendezés, amit meg kell szerezni, vagy egy személy, akit lehengerelhetnék a tûzerõmmel?}
{153}{}{Nem állítom, hogy a felét is értettem annak, amit itt vakerol. Azért én csak megpróbálnék egy ilyen tesztet.}
{154}{}{Nehéznek tûnik. Azért megpróbálnék egy tesztet, ha lehetséges.}
{155}{}{Semmiség. Megpróbálnám, ha nincs ellene kifogása.}
{156}{}{Az alany vizuális, vagy logikai képességeit nem tesztelik? Nem? Nos, talán betehetnék a késõbbi tesztekbe... persze csak miután én már levizsgáztam.}
{157}{}{Feltehetnék néhány kérdést?}
{158}{}{Köszönöm, hogy rabolhattam az idejét. Viszlát!}
{159}{}{Ha végrehajtja a küldetést, amivel az Elsõ Polgár megbízta, megkapja a Polgári státuszt. Na, nem mintha megérdemelné.}
{160}{}{Ha Polgár szeretne lenni, sikeres vizsgát kell tennie. Nincs más mód.}
{161}{}{Gondja van ezzel, jóember? Helytelen hozzáállás.}
{162}{}{Megpróbálnám a tesztet.}
{163}{}{Szeretnék újra próbálkozni a teszttel.}
{164}{}{Feltehetnék néhány kérdést?}
{165}{}{Köszönöm, hogy idõt szakított rám. Viszlát!}
{166}{}{Tehát megpróbálja? Nagyszerû! Semmi sem tesz boldogabbá, mint elbírálni a potenciális jelentkezõk alkalmasságát... de figyelmeztetnem kell. A teszt nagyon nehéz és akár órákig is eltarthat.}
{167}{}{Nos, rendben. Bárki próbát tehet, bár úgy érzem az ön esetében ez pusztán idõpocsékolás. Valaki az ön... hmm... adottságaival egyszerûen nem Polgárnak való.}
{168}{}{Nem probléma. Vágjunk bele!}
{169}{}{Inkább feltennék néhány kérdést.}
{170}{}{Meggondoltam magam. Viszlát!}
{171}{}{Én azért szeretném megpróbálni.}
{172}{}{Adja már ide azt az átkozott tesztlapot!}
#Elnezest, folosleges stilusvaltas
{173}{}{Értem. Akkor inkább kérdeznék valamit.}
{174}{}{Akkor már itt sem vagyok.}
{175}{}{Rendben.}
{176}{}{Nos, próbálkozni lehet, bár kétlem, hogy sikerülni fog.}
{177}{}{Itt van az 5028-as és 6112-es vizsgaanyag, valamint a PipBoy ellenõrzõ konzol. Felhívom a figyelmét, hogy minden kérdésre válaszolnia kell! Talán akkor foglaljon is helyet, és lásson hozzá!}
{178}{}{Na... veselkedjünk neki.}
{179}{}{Már kész is van? Biztos benne, hogy nem akarja még egyszer ellenõrizni a tesztlapját?}
{180}{}{Rendben, lejárt az idõ. Odaadná a tesztlapját, kérem!}
{181}{}{Már megtettem. Tessék.}
{182}{}{Várjon még, nem vagyok kész! Hé... ne rángassa már azt a kurva papírt! A francba, tessék...}
# Kell ez a kirohanas? Nincs az eredetiben
{183}{}{Lássuk csak... hmm... nem... ez rossz... ez is... itt meg nullával osztott... hmm... itt nem vitte át a kettõt... ó egek... a szókincse is elég szegényes.}
{184}{}{Lássuk csak... nem deriválta a belsõ egyenletet... aztán... nem értette meg a hetedik bekezdés lényegét... hmm a piramis diagram pedig nem három, hanem hét helyen járható át.}
{185}{}{Nos, a válaszai helyesnek tûnnek, de... kifutott az idõbõl és azok a szembeötlõ helyesírási hibák.}
{186}{}{Szóval?}
{187}{}{Szóval... megbukott! Sajnálattal közlöm, de ez alkalommal nem tudok Polgári státuszt adni önnek.}
{188}{}{Õszintén szólva úgy tûnik, nem rendelkezik a magasabb szintû matematika elsajátításához szükséges intelligenciával.}
{189}{}{Ha fogalmazhatok így... önnél a térbeli kapcsolatok felismerésének képessége alig észlelhetõ.}
{190}{}{Ha szabad megjegyeznem, a jelenlegi tudása nem elég a teszt sikeres kitöltéséhez. Próbálja meg késõbb, talán szerencsésebb lesz!}
{191}{}{Rendben, késõbb majd újra megpróbálom.}
{192}{}{Lássuk csak... hmm... ez jó, látom ezt érti, de mi van a... nocsak... átvitte a kettõt, okos... okos... de miért tette ezt az... ó... a deriválást hatványozva alkalmazta... briliáns!}
{193}{}{Naná, hogy briliáns!}
#tulsagosan ontorvenyu lenne a forditas az ilyenektol

{194}{}{Átment a vizsgán... ez... ez ELKÉPESZTÕ!}
{195}{}{Remek. Szóval most már Polgár vagyok?}
{196}{}{Egy pillanat, az orvosi felülvizsgálat még hátra van. Szerencsére itt van nálam minden szükséges eszköz. Akkor most vegye le a... cipõjét!}
#A physical problema

{197}{}{Vegyem le a cipõmet?! Két éve nem mostam lábat, jól meggondolta?}
{198}{}{Ne gyerekeskedjen már, mutassa a lábát!... De hisz maga... magának van egy hatodik lábujja! Maga mutáns!!! Hogy képzelte, hogy MERÉSZELTE egyáltalán megpróbálni a tesztet... maga... maga FÖRTELEM! Kifelé! Takarodjon!!! És be ne merje ide tenni még egyszer a MOCSKOS LÁBÁT!}
{199}{}{Na, jó, betelt a pohár! Tele a tököm ezzel a várossal!!! Minden piperkõc Polgárt kinyúvasztok és VELED FOGOM KEZDENI!!!}
{200}{}{Jól van, nyugalom! Megyek már.}
{201}{}{A vérnyomása rendben, és nem találtam fertõzõ betegségre utaló nyomokat. Gratulálok, Polgártárs! Isten hozott Menedékvárosban!}
{202}{}{Kösz, Polgártárs! Jó ide tartozni.}
{203}{}{Már megint maga az?! Mit akar? Sok a dolgom.}
{204}{}{Rendben, de fogalmazzon tömören, kevés az idõm!}
{205}{}{Tulajdonképpen kihez van szerencsém?}
{206}{}{Megpróbálnék egy Polgársági tesztet.}
{207}{}{Szeretnék újra próbálkozni.}
{208}{}{Mit tud Gekkóról?}
{209}{}{Akkor nem is zavarom. Viszlát!}
{210}{}{Ha végrehajtja a küldetést, amivel az Elsõ Polgár megbízta, megkapja a Polgári státuszt. Na, nem mintha megérdemelné.}
{211}{}{Polgár szeretnék lenni.}
{212}{}{Kifogásolja, hogy Polgárságot ajánl nekem?}
{213}{}{Kérdezhetnék valami mást?}
{214}{}{Viszlát!}
{215}{}{Nem szokásom megkérdõjelezni az Elsõ Polgár döntéseit.}
{216}{}{Van más módja annak, hogy Polgár váljon belõlem?}
{217}{}{Kérdezhetnék valami mást?}
{218}{}{Rendben. Viszlát!}
{219}{}{Gekkó? Az egy koszos putri fent északon. Ott élnek a "ghoul" nevû... teremtmények, õk mérgezik a talajvizünket. Ez nem más, mint egy ellenünk irányuló terrorista akció, és ennek megfelelõen bánunk majd velük.}
{220}{}{Mérgezik a vizet?}
{221}{}{Kérdezhetnék valami mást?}
{222}{}{Köszönöm az információt, viszlát!}
{223}{}{A koszfészküket egy régi atomerõmû köré építették, amit valahogy sikerült újraindítaniuk. Ebbõl a berendezésbõl radioaktív hulladék szivárog, ez mérgezi a vizünket. Azokat a... létformákat el kell zavarni, a reaktort pedig mihamarabb le kell állítani!}
{224}{}{Kérdeznék még valamit.}
{225}{}{Értem. Viszlát!}
{226}{}{Átmentél a vizsgán és most már Menedékváros teljes jogú polgára vagy.}
#Ez ugy kivankozott
