{100}{}{Egy alacsony, mosolygós férfit látsz.}
{101}{}{Boldog Harry, a bolt tulaja.}
{102}{}{Üdvözöllek, barátom! Mondd, mit tehetek érted?}
{103}{}{Vásárolni szeretnék. Láthatnám a kínálatot?}
{104}{}{Van kint egy eke. Eladó?}
{105}{}{Én vesz}
{106}{}{Kösz, egyel?re elleszek magam is.}
{107}{}{Sajnálom barátom, nem tudok segíteni.}
{108}{}{Természetesen, nyolcszázért a tiéd lehet. Biztosíthatlak, pompás darab.}
{109}{}{Nyolcszáz?! Hatszázat adok érte.}
{110}{}{Rendben van, megveszem.}
{111}{}{Nyolcszáz? Rendben, mindjárt hozom a pénzt.}
{112}{}{Az túl sok! Smith-ék pusztuljanak csak éhen!}
{113}{}{Nagyszer? [elteszi a pénzt]. Házhozszállítást is kérsz? Ingyen van.}
{114}{}{Házhozszállítás? Ingyen? Remek! Kérlek, vitesd el Smith-ékhez!}
{115}{}{Sajnálom, barátom. Nyolcszáz az ára, egy centtel se kevesebb.}
{119}{}{Ez sajnos nem lesz elég, barátom!}
{120}{}{Értem. Hamarosan visszajövök a teljes összeggel.}
{121}{}{Rendben van, azonnal intézkedem. Mindent a kedves vev?ért.}
{122}{}{Azt hiszed, csak úgy elviheted? Piszkos csirkefogó! ?rség! ?rség!!!}
