# Dialog Editor last position: 5
{100}{}{Kohl Fõkönyvtáros.}
{101}{}{Egy intelligens tekintetû férfit látsz, aki kifogástalanul vasalt menedékvárosi ruhát visel.}
{102}{}{Kohl Fõkönyvtáros.}
{103}{}{Egy intelligens tekintetû férfit látsz, aki kifogástalanul vasalt menedékvárosi ruhát visel.}
{104}{}{Biztosra veszem, hogy hõstetteit bejegyzik majd a menedékvárosi adattárba.}
{105}{}{Egy betolakodó! Segítség! Õrség!!!}
{106}{}{Szavamra! Egy mutáns! Õrség! Õrség!!!}
{107}{}{Istenem, ez egy ghoul! Õrség ! Õrség!!!}
{108}{}{Az Információs Iroda este zárva tart. Kérem, jöjjön vissza holnap!}
{109}{}{Sajnálom, zárva vagyunk. Hazamegyek, miután lajstromba vettem ezeket a könyveket.}
{110}{}{Psssszt!}
{111}{}{Halkabban, kérem!}
{112}{}{Pssssssszt!}
{113}{}{Legyen szíves, ne hangoskodjon!}
{114}{}{Üdvözlöm a kedves látogatót. Miben segíthetek?}
{115}{}{Könyv-vum-bu!}
{116}{}{[Elbattyogsz]}
{117}{}{Ó... nagyon kedves. Mi ez a hely?}
{118}{}{Köszönöm, semmiben. Viszlát!}
{119}{}{Pardon?}
{120}{}{Humm... humm.}
{121}{}{[Elbattyogsz]}
{122}{}{Ó, egek... ön bizonyára az egyik szolga. Ha szépen megkérem, visszamegy Mr. Barkushoz? Különben nagyon dühös lesz ám!}
{123}{}{Okéé!}
{124}{}{Ez Menedékváros Információs Irodája, vagy ha közérthetõen akarok fogalmazni, egy könyvtár. Ezt kereste?}
{125}{}{Pontosan. Feltehetek önnek egy kérdést?}
{126}{}{Könyvtár? Remek. Szükségem van könyvekre, használati útmutatókra.}
{127}{}{Sajnos nem. Elnézést a zavarásért.}
{128}{}{Szörnyen sajnálom, de már nincsenek könyveink. Digitális formába átírták, majd a Komfort Hivatalba szállították õket. Kérem, ott érdeklõdjön!}
{129}{}{Hova kerültek a digitális kópiák?}
{130}{}{Szomorúan hallom, szeretem a könyveket. Mind elvitték?}
{131}{}{Értem. Feltehetek egy kérdést?}
{132}{}{Köszönöm a segítséget.}
{133}{}{Üdvözlöm a kedves látogatót. Miben segíthetek?}
{134}{}{Szívesen segítek, ha tudok.}
{135}{}{Mi ez a hely?}
{136}{}{Tud valamit az ÉLET-rõl?}
{137}{}{A Menedéket keresem.}
{138}{}{Köszönöm, de boldogulok magam is. Viszlát!}
{139}{}{ÉLET? Pontosan mire gondolt?}
#Abbol indulunk ki, hogy az ELET automatikusan mindenkinek a targyat jelenti, de ez nem igaz
#ha belegondolunk

{140}{}{Igazából magam sem tudom. Ahogy a falum elöljárója mondaná, ez egy õsi csoda, ami felvirágoztatja a közösségünket. Én azért egy kicsit szkeptikus vagyok.}
{141}{}{Igazából magam sem tudom.}
{142}{}{Gõzöm sincs. Feltehetnék még egy kérdést?}
{143}{}{Sajnos mennem kell. Viszlát!}
{144}{}{Itt van a közelben, tõlünk keletre. A bejáratát az utca végén találja, egy nagy lyuk a hegyoldalban.}
{145}{}{Vannak máshol is Menedékek?}
{146}{}{Feltehetnék még egy kérdést?}
{147}{}{Köszönöm az útbaigazítást.}
{148}{}{Más Menedékek? Nem is tudom. Lehet, hogy építettek ilyeneket, de én még egyet se láttam. Talán a központi számítógépben talál róluk adatokat.}
{149}{}{Szeretnék bejutni oda.}
{150}{}{Feltehetnék még egy kérdést?}
{151}{}{Köszönöm az információt.}
{152}{}{Értem. Nos, talán a Menedék központi számítógépében talál róla információkat. A legtöbb adatot ott tároljuk.}
{153}{}{Köszönöm. Hogy juthatok be oda?}
{154}{}{Feltehetnék még egy kérdést?}
{155}{}{Köszönöm. Viszlát!}
{156}{}{Ön a város egyik Polgára, nemdebár? Mint ilyen, jogosult a belépésre.}
{157}{}{Amennyiben ön Polgár, természetesen használhatja a terminált.}
{158}{}{A Menedéket kizárólag Polgárok látogathatják. Ha gondolja, végigcsinálhatja a Polgársági tesztet, vagy ami még jobb, beszéljen Lynette Elsõ Polgárral! Biztos vagyok benne, hogy az ön esetében kivételt tesz majd.}
{159}{}{Már elnézést, de én Polgár vagyok.}
{160}{}{Feltehetek még egy kérdést?}
{161}{}{Köszönöm.}
{162}{}{Igen. A digitális formátumú könyveké a jövõ és hát... senki sem állhat a haladás útjába. Sajnos ezzel feleslegessé vált a munkám itt, Menedékvárosban.}
{163}{}{Feleslegessé? Ezt hogy érti?}
{164}{}{Feleslegessé? Ugyan miért?}
{165}{}{Értem. Feltehetnék még egy kérdést?}
{166}{}{Sajnálattal hallom, de most már mennem kell.}
{167}{}{Azt jelenti, hogy többé nincs szükség a munkámra. Így lesz a legjobb.}
{168}{}{A tervek szerint összekötnék a terminálokat a Listaszerverrel és az Információs Adattárral. Ha ez megtörténik, az Információs Iroda és én... feleslegessé válunk. Talán így lesz a legjobb. Tényleg.}
{169}{}{Ezt szomorúan hallom. Biztos benne, hogy így lesz a legjobb?}
{170}{}{Értem. Kérdeznék valami mást.}
{171}{}{Most már tényleg mennem kell. Viszlát!}
{172}{}{Természetesen. Az Elsõ Polgár ritkán téved az ilyen dolgokban. Egyébként meg hallottam, hogy  vár rám egy állás a Lista Hivatalban. Ennek ellenére sajnálom itthagyni ezt a helyet, úgy a szívemhez nõtt. Nem is beszélve a könyvekrõl...}
{173}{}{Megértem önt. Imádom a könyveket és én is ragaszkodnék hozzájuk.}
{174}{}{Megértem önt. Imádom a könyveket és én is ragaszkodnék hozzájuk.}
{175}{}{Kérdeznék valami mást.}
{176}{}{Ezt szomorúan hallom. Most mennem kell.}
{177}{}{Tudja, nekem semmi bajom a digitális kiadással, de van valami izgalmas abban, ahogy az ember egy könyvet lapozgat. Ön bizonyára érti, mirõl beszélek.}
{178}{}{Tökéletesen értem. Engem is lázba hoz, ahogy a pergament morzsolgatom az ujjaim közt. Nem maradt egyetlen példány sem?}
#Nem tul szabad ez a forditas? eredetileg csak annyi volt itt, hogy "Yes?"

{179}{}{Kérdeznék öntõl valamit.}
{180}{}{Sajnálom, most mennem kell.}
{181}{}{Hát... nem tagadom, félretettem néhány kötetet. Randalnak nem fog hiányozni és... szeretném önnek ajándékozni. Biztos vagyok benne, hogy jó kezekbe kerül.}
{182}{}{Ez nagyon megtisztelõ. Köszönettel elfogadom.}
{183}{}{Rendben. Megyek, hozom õket.}
{184}{}{Köszönöm szépen.}
{185}{}{Tessék. Remélem, ön értékelni fogja és a hasznára válnak majd. Ezek a kedvenceim. Egy kicsit technikai jellegûek, de kitûnõ munkák.}
{186}{}{Hálásan köszönöm, ígérem, vigyázok rájuk. Nem bánná, ha feltennék még néhány kérdést?}
{187}{}{Köszönöm szépen, de most már mennem kell.}
{188}{}{Egy számítógépbe táplálták a Menedék harmadik szintjén. Pontosan már nem emlékszem melyikbe, de biztos nem a központi mag mellettiekbe.}
{189}{}{Az összes könyvet elvitték?}
{190}{}{Hogy juthatok be oda?}
{191}{}{Értem. Lenne még egy kérdésem.}
{192}{}{Köszönöm.}
{193}{}{Nagyszerû! Bravó!}