# Dialog Editor last position: 5
{100}{}{Egy vénembert látsz, szemében õrült ragyogás.}
{101}{}{Old Joe-t látod, a helyi nagyokost.}
{102}{}{Heló! Már jó ideje nem láttalak.}
{103}{}{Ismerjük egymást?}
{104}{}{Ó igen, bár elég rég volt már. Mit csináltál mostanában?}
{105}{}{Hát, elég régen volt. Mi jót csináltál mostanság?}
{106}{}{Ezt is, azt is. Honnan ismersz?}
{107}{}{Nézd papa, én nem tudom, ki a franc vagy te.}
{108}{}{Persze. Nos, körülnéztem a pusztában és végül itt kötöttem ki, ezen az istenhátamögötti helyen. Nem olyan, mint a régi szép idõkben. Nem bizony.}
{109}{}{Ja, a régi szép idõk. Emlékszem akkoriban mi...}
{110}{}{Minden megváltozott, ez biztos. De... mit is csináltunk mi együtt?}
{111}{}{Nem emlékszel rám, ugye? Nos, kicsit fiatalnak tûnsz.}
{112}{}{Mit akarsz ezzel mondani?}
{113}{}{Pedig nagyon hasonlítasz. Eh, biztos megcsaltak a vén szemeim... Hát ... akkor viszlát.}
{114}{}{Hmm... ok ... viszlát.}
{115}{}{Ja, átküldtük a Mestert a túlvilágra, igaz? Csak szaros sziklák maradtak utána, úgy emlékszem. Aztán körüljártam a világot, nevet változtattam. És veled mi van?}
{116}{}{Én egy kis faluban éldegéltem.}
{117}{}{Vigyázz a környéken, már nem olyan mint rég. Nem árt néha hátranézni...}
{118}{}{Oké, kösz.}
{119}{}{Egy ideig a menedéketeket kutattam, de soha nem találtam meg. Nincs valami jó sztorid a barátodról, az öreg Ian-ról?}
{120}{}{Ian?}
{121}{}{Aha, Ian. Nem emlékszel rám? Jópár éve már annak. Azt hinné az ember, hogy soha nem felejtik el a legjobb haverok. Nos ... úgy látom, tévedtem. Bocs mégegyszer.}
{122}{}{Elnézést, de szerintem te azt hiszed, hogy én vagyok a Menedéklakó. Õ alapította a falunkat.}
{123}{}{Nos, így kicsit másképp fest a dolgot. Jó hallani, hogy a barátom jól élt. Fogadj el egy jótanácsot az öreg Ian-tól! Légy óvatos odakinn! Már nem olyan békés a hely, mint amilyennek tûnik!}
{124}{}{Mi folyik itt?}
{125}{}{Menedékváros polgárai nagyon vigyáznak a vérvonalra és nem törõdnek a magunkfajtával. Itt ez a fegyver, megvéd, ha kicsit elszaladnának a dolgok.  Most már jobb lesz ha indulsz, nem lenne szerencsés, ha meglátnának minket.}
{126}{}{Kösz a segítséget!}
{127}{}{Hagyd a vénembert pihenni.}
{128}{}{Annyira hasonlít...}
{129}{}{Hagyj most kérlek!}
{130}{}{Jobb ha mész.}
{131}{}{Gyanút fognak, ha tovább beszélgetünk.}
{132}{}{Gyerünk, menj! Had legyen büszke az én vén barátom.}
