# Dialog Editor last position: 5
{100}{}{Randal, a Komfort Hivatal vezetõje.}
{101}{}{Egy középkorú embert látsz ritkuló, fekete hajjal.}
{102}{}{Randal, a Komfort Hivatal vezetõje.}
{103}{}{Egy középkorú embert látsz ritkuló, fekete hajjal.}
{104}{}{Gratulálok,}
{105}{}{ imádtam, ahogy elbántál azokkal az Enklávés seggfejekkel.}
{106}{}{Úgy hallom, délen néhány nagykutyának szétrúgtad a seggét. Csak így tovább!}
{107}{}{Behatoló! Õrség! Õrség!!!}
{108}{}{Mi a... ?! Egy mutáns! Õrség!}
{109}{}{Mi a...?! Egy ghoul! Õrség!}
{110}{}{Jó napot, Kapitány!}
{111}{}{Menedékváros mindenek felett, Kapitány!}
{112}{}{Jó napot, Polgártárs!}
{113}{}{Menedékváros mindenek felett, Polgártárs!}
{114}{}{Néhány kimutatást kell még majd küldenünk az A és B Komfort Osztálynak.}
{115}{}{Leltárba kell venni a legújabb felszereléseket és fel kell vinni az adatokat a lista szerverre.}
{116}{}{Hiányzik a DOS. Ezzel az új operációs rendszerrel sokkal nehezebb az adatokat kezelni.}
{117}{}{Az Elsõ Polgárnak még mindig kellenek azok a felszerelés listák.}
{118}{}{Bocsánat, de már zárva vagyunk. Gyere vissza holnap reggel!}
{119}{}{Zárva vagyunk. Csak rögzítem még ezeket a listákat, mielõtt hazamegyek.}
{120}{}{Üdvözöllek, idegen! Mindig örülök, ha új arcot látok. A nevem Randal, én vagyok a Komfort Hivatal vezetõje.}
{121}{}{ÉLhett}
{122}{}{Neeeeem-öm}
{123}{}{[Elbattyogsz]}
{124}{}{Komfort Hivatal?!}
{125}{}{Értem, viszlát!}
{126}{}{ÉLET? Az Édenkert Létrehozást Elõsegítõ Táskáról beszélsz? Egy szürke aktatáskának kinézõ valamirõl?}
{127}{}{KEEEL ÉLhettt!}
{128}{}{[Elbattyogsz]}
{129}{}{IGEN!!! Kaphatnék egyet?}
{130}{}{Kérdezhetnék valami mást?}
{131}{}{Köszönöm a segítséget, de most mennem kell. Viszlát!}
{132}{}{Sajnálom, barátom, de a miénk már nincs meg. Menedékváros létrehozásánál felhasználtuk.}
{133}{}{KEEEL ÉLhettt!}
{134}{}{[Elbattyogsz]}
{135}{}{Ó, hogy bassza meg...  már bocsánat. Nem tudsz egy helyet, ahol még találhatnék?}
{136}{}{Kérdezhetnék valami mást?}
{137}{}{Értem, most mennem kell. Viszlát!}
{138}{}{Hmmm... nos... a probléma a következõ. Az ÉLET egy régi technológia... háború elõtti, hogy egész pontos legyek. Nem terem az ilyen minden bokorban. Kizárólag Menedékeknek volt ilyen felszerelésük.}
{139}{}{KEEL Mendnék.}
{140}{}{[Elbattyogsz]}
{141}{}{Segítenél? Hol találok még Menedékeket?}
{142}{}{Kérdezhetnék valami mást?}
{143}{}{Értem, most mennem kell. Viszlát!}
{144}{}{Én a helyedben a Menedék Központi Számítógépében keresném, az majd talán kiadja a koordinátákat. Õszintén szólva kétlem, de próbálkozni azért még lehet.}
{145}{}{Én a helyedben a Menedék Központi Számítógépében keresném, az majd talán kiadja a koordinátákat. Sajnos oda csak Polgárok léphetnek be.}
{146}{}{Köszönöm.}
{147}{}{Kérdezhetnék valami mást?}
{148}{}{Kösz a tippet. Viszlát!}
{149}{}{Megint itt vagy? Tehetek érted valamit?}
{150}{}{Miben segíthetek?}
{151}{}{Élhett?}
{152}{}{[Elbattyogsz]}
{153}{}{Mi ez a hely tulajdonképpen? Komfort Hivatal?}
{154}{}{Egy ÉLET nevû szerkezetet keresek. Van nektek ilyen?}
{155}{}{Valerie-nek a karbantartó részlegrõl szüksége lenne egy új villáskulcsra és kombinált fogóra.}
{156}{}{McClure Fõtanácsos mondta, hogy itt átvehetek egy olyan hidro... magneszofos izét, ami a gekkói erõmûbe kell.}
{157}{}{McClure Fõtanácsos mondta, hogy itt átvehetek egy hidroelektromos magnetoszféra szabályzót, ami a gekkói erõmûbe kell.}
{158}{}{Az Elsõ Polgár küldött, hogy átvegyem a jutalmamat.}
{159}{}{Kösz, de mennem kell. Viszlát!}
{160}{}{Igen, Komfort Hivatal, de ha úgy jobban tetszik, ez egy raktár. Olyan felszereléseket tárolunk, ami a Polgárok életét megkönnyíti. Például "csináld magad" útmutatókat, szerszámokat, stimpakkokat, gyógyászati felszereléseket.}
#olyan nincs, hogy medikai
{161}{}{Így már értem. Megnézhetném, mi van raktáron?}
{162}{}{Egy ÉLET nevû szerkezetet keresek. Kaphatnék egyet?}
{163}{}{Valerie-nek a karbantartó részlegrõl szüksége lenne egy új villáskulcsra és kombinált fogóra.}
{164}{}{McClure Fõtanácsos mondta, hogy itt átvehetek egy olyan hidro... magneszofos izét, ami a gekkói erõmûbe kell.}
{165}{}{McClure Fõtanácsos mondta, hogy itt átvehetek egy hidroelektromos magnetoszféra szabályzót, ami a gekkói erõmûbe kell.}
{166}{}{Az Elsõ Polgár küldött, hogy átvegyem a jutalmamat.}
{167}{}{Kérdezhetnék valami mást?}
{168}{}{Értem, most mennem kell. Viszlát!}
{169}{}{Bocsáss meg, de a szabályzat szerint itt csak Polgárok vásárolhatnak. Félre ne értsd, semmi bajom veled, de tudod a szabály az szabály. Szerintem nézz be Boldog Harry boltjába, elég nagy árukészlettel rendelkezik.}
{170}{}{Bocsáss meg, de a szabályzat szerint itt csak Polgárok vásárolhatnak. Félre ne értsd, semmi bajom veled, de tudod a szabály az szabály. Szerintem nézz be Boldog Harry boltjába, elég nagy árukészlettel rendelkezik.}
{171}{}{Mit kell tennem, hogy Polgár lehessek?}
{172}{}{De hisz én Polgár vagyok!}
{173}{}{Nézd, a pénzem ugyanolyan jó, mint bármely Polgáré.}
{174}{}{McClure Tanácsos mondta, hogy van egy hidroelektromos magnetoszféra szabályzód a számomra.}
{175}{}{Az Elsõ Polgár küldött, hogy átvegyem a jutalmamat.}
{176}{}{Kérdezhetnék valami mást?}
{177}{}{Köszönöm, viszlát!}
{178}{}{Ki kell töltened egy Polgársági tesztet. Gregory Fõbiztosnál bárki próbát tehet, de ha elfogadsz egy baráti jótanácsot, elõbb beszélj Lynette-el, az Elsõ Polgárral! Õ eligazít a helyi dolgokban.}
{179}{}{Hol találom?}
{180}{}{Értem. Kérdezhetnék valami mást?}
{181}{}{Köszönöm. Megyek és beszélek vele.}
{182}{}{A Tanács Épületében. Ha kilépsz az ajtón, jobbra kell fordulnod, majd egyenesen át a parkon. A város legészakibb épülete az.}
{183}{}{Értem. Kérdezhetnék valami mást?}
{184}{}{Köszönöm. Megkeresem és beszélek vele.}
{185}{}{Valóban? Nem emlékszem rád, de egy pillanat alatt tisztázhatjuk a dolgot. Nálad vannak a papírjaid?}
{186}{}{Hoppsz... hát nem otthon felejtettem?}
{187}{}{Természetesen, Polgártárs. Parancsolj!}
{188}{}{Hogy rohan az idõ? Nekem is azt kell tennem. Viszlát!}
{189}{}{Akkor most szépen áthúzom a leolvasón és megbizonyosodunk róla, hogy minden rendben van-e. Egy pillanat az egész.}
{190}{}{Mi van?! Ácsi! Nem kell itt semmit, sehol huzigálni, okés? Még elkopik. Na... add csak szépen vissza azokat a papírokat!}
{191}{}{Most jut eszembe, hogy halaszthatatlan dolgom akadt. Visszakaphatnám a papírjaimat?}
{192}{}{Köszönöm, Polgártárs, türelmesen várok.}
{193}{}{Nos... hmmm... rendben.}
{194}{}{Kérdezhetnék valami mást?}
{195}{}{Mennem kell, viszlát!}
{196}{}{Úgy látom, minden a legnagyobb rendben van... itt vannak a papírjaid. Tehát mit tehetek érted?}
{197}{}{Megnézném, mi van raktáron.}
{198}{}{Feltehetek egy kérdést?}
{199}{}{Kösz, csak körülnéztem.}
{200}{}{Szóval... te Polgár vagy.}
{201}{}{Igen mondta, hogy beugrasz majd.}
{202}{}{Rendben.}
{203}{}{Hagyjuk, majd késõbb visszajövök érte.}
{204}{}{Itt van, tessék, egy Hi-Mag. Úgy néz ki mint egy láva lámpa, nem? Ó... és vigyázz rá... nagyon törékeny.}
{205}{}{Megnézhetem, mi van raktáron?}
{206}{}{Kérdezhetnék valami mást?}
{207}{}{Kösz. Azt hiszem, gyönyörködni fogok benne még egy darabig, mielõtt elvinném a gekkói erõmûbe.}
{208}{}{Megvan. Kösz az alkatrészt.}
{209}{}{Igen, az Elsõ Polgár mondta, hogy benézel majd ide, Kapitány...[kacsint]... hogy is mondjam,... egy igazi SZÉPSÉG vár rád.}
{210}{}{Igen, az Elsõ Polgár mondta, hogy benézel majd. Hogy is mondjam, barátom... egy igazi SZÉPSÉG vár rád.}
{211}{}{Mi az?}
{212}{}{Tudod, mit? Tedd félre nekem, majd késõbb beugrok érte!}
{213}{}{Nem más mint egy Heckler and Koch G11, az egyik legjobb támadó fegyver, amit valaha is készítettek... (átnyújtja neked a fegyvert)... 4,7 mm-es hüvely nélküli töltények, 50-töltényes tár. Ha ez beszél, az emberek hallgatnak.}
{214}{}{Abban biztos vagyok. Köszönöm.}
{215}{}{Szívesen. Plusz... van itt még néhány repeszgránát is. Tekintsd úgy, mint személyes köszönetnyilvánítást tõlem, amiért elintézted azokat a seggfejeket.}
{216}{}{Remek! Megnézhetném, mi van még raktáron?}
{217}{}{Feltehetnék még néhány kérdést?}
{218}{}{Kösz. Biztos jó hasznát veszem majd.}
{219}{}{Akkor rendben vagyunk?}
{220}{}{Igen, köszönöm. Feltehetek egy kérdést?}
{221}{}{Igen, de most mennem kell. Viszlát!}
{222}{}{Igen, tudom. Még mindig várok a kérvény listákra, hogy rendbe rakjam a szervert. Nem tudok mit mondani. A dolgok néha idõt vesznek igénybe.}
{223}{}{Értem. Kérdezhetnék valami mást?}
{224}{}{Akkor talán máshol nézek utána azoknak a cuccoknak.}
{225}{}{!}
{226}{}{, he? Várj egy percet, mindjárt hozom neked a Hidroelektromos magento... izé... a Hi-Mag -ot.}
{227}{}{, jól mondom? Várj egy percet, mindjárt hozom neked a Hidroelektromos magento... izé... a Hi-Mag-ot.}
{228}{}{Kösz.}
{229}{}{[tovább]}
