# Dialog Editor last position: 5
{100}{}{Ez a Polgár világoskék kezeslábast hord, olyat, mint a Menedéklakó, de nincs a hátán szám.}
{101}{}{Õ Menedékváros egyik Polgára.}
{102}{}{Ez a Polgár világoskék kezeslábast hord, olyat, mint a Menedéklakó, de nincs a hátán szám.}
{103}{}{::tapsol::}
{104}{}{Õ a hõsünk! Nézzétek!}
{105}{}{Nem hiszek a szememnek! A bajnok itt van, Menedékvárosban!}
{106}{}{Jó napot, Kapitány!}
{107}{}{Menedékváros mindenek felett, Kapitány!}
{108}{}{Jó napot, Polgártárs!}
{109}{}{Menedékváros mindenek felett, Polgártárs!}
{110}{}{Ez egy mutáns! Õrség! Õrség!!!}
{111}{}{Itt egy ghoul! Õrség! Õrség!!!}
{112}{}{Hogy jutott be ide?}
{113}{}{Elnézést, láthatnám a Napi Belépõjét?}
{114}{}{Hmmm... még egy Kívülálló.}
{115}{}{Úgy tûnik, egyre több Kívülállót engednek be ide.}
{116}{}{Szerfelett remélem, hogy van önnek Napi Belépõje.}
{117}{}{Úgy látom, most már mindenféle jöttmentnek adnak Napi Belépõt.}
{118}{}{Hallottam a bátor tetteidrõl. Nagy szolgálatot tettél Menedékvárosnak... és az egész világnak.}
{119}{}{Az Enklávé elleni harcod még az Elsõ Polgár elismerését is kivívta.}
{120}{}{Azt hallottam, hogy egészen San... Fran... ciscóig jutottál. Igaz ez?}
{121}{}{Lehet, hogy az lenne a legjobb megoldás, ha befogadnánk a Kívülállókat.}
{122}{}{Igaz a szóbeszéd? A régi világkormánynak még mindig a háborún jár az esze?}
{123}{}{Az utazásod részleteit be kéne táplálnod a számítógépbe, hogy bárki elolvashassa.}
{124}{}{Addig maradsz, ameddig csak akarsz, BAJNOK!}
{125}{}{Az Enklávé ellen végrehajtott akciódról egy szép, takaros listát kéne készítened.}
{126}{}{*Ásít*... hmmmm? Igen? Mi van?}
{127}{}{Késõre jár, hamarosan távoznia kell.}
{128}{}{Az állampolgárok zöme ilyenkor már alszik.}
{129}{}{Szép nap ez a mai a listakészítéshez.}
{130}{}{Jöjjön vissza reggel! Még sok listát kell elkészítenem.}
{131}{}{Jó napot, Kapitány!}
{132}{}{Menedékváros mindenek felett, Kapitány!}
{133}{}{Adhatok egy fánkot, Kapitány?}
{134}{}{Minden rendben van, Kapitány?}
{135}{}{Remélem, egyetlen Kívülálló sem okoz problémát magának, Kapitány.}
{136}{}{Nincs valami jó kis története a kinti világról, Kapitány?}
{137}{}{Jó napot, Polgártárs!}
{138}{}{Menedékváros mindenek felett, Polgártárs!}
{139}{}{Ma a szokásosnál is jobban érzem magam. Hát ön?}
{140}{}{Állampolgárként kötelességünk listákat készíteni és karbantartani az adatokat.}
{141}{}{A napom nagy részét a Fõtanácsosnak szánt listák készítésével töltöttem, aztán újra leellenõriztem õket. Imádom a listákat.}
{142}{}{A városlakók többségéhez hasonlóan én is a Lista Hivatalban dolgozom. Menedékváros polgárai számára öröm a listakészítés.}
{143}{}{A napom nagy részét a Lista Hivatalnak szánt listák frissítésével töltöttem. Nagyszerû, produktív, eredményes munka volt.}
{144}{}{Azt hallottam, hogy beutaztad a világot. Hogy voltál képes életben maradni a mocskos Kívülállók között?}
{145}{}{Ó! Te vagy az új Polgárunk? Üdvözöllek Menedékvárosban!}
{146}{}{Amíg a városban vagy, nincs szükséged egy szobára?}
{147}{}{A Tanács mindannyiunk érdekét a szívén viseli.}
{148}{}{Gondoskodnunk kell róla, hogy szépséges városunk tiszta maradjon.}
{149}{}{Mármint a szolgák? Õket csak alantas munkák elvégzésére használjuk.}
{150}{}{A tegnapi tanácsülés nagyon eredményes volt, rengeteg listát készítettünk. Menedékváros lakosai nagyon szeretik a listakészítést.}
{151}{}{Igen?}
{152}{}{Mit akarsz... Kívülálló?}
{153}{}{Bocsánat, hozzám szólt?}
{154}{}{Márminthogy én? Megyek a dolgomra. Tegye ön is azt!}
{155}{}{Megmutatná a Napi Belépõjét, kérem?}
{156}{}{Ó, bocsánat. Majdnem összetévesztettem egy szolgával.}
{157}{}{Most tényleg nincs idõm arra, hogy egy Kívülállóval csevegjek. Kérem, távozzon!}
{158}{}{Odébb menne, ha megkérem? Köszönöm!}
{159}{}{Menjen át a másik oldalra, kérem!}
{160}{}{A szolgák-végezte munka lehetõvé teszi számunkra, hogy sokkal fontosabb ügyekre koncentrálhassunk. Például a listakészítésre.}
{161}{}{A szolgák? Õket csak alantas munkák elvégzésére használjuk.}
{162}{}{Igen, érzem...  hogy ön csak egy Kívülálló.}
{163}{}{Ön Kívülálló? Ez meglep.}