# !!! Figyelem a következõ sorok megváltoztatása eltájolja a játékban a többi sort !!!
{100}{}{Számítógép-terminál. Bugos!!!}
{101}{}{Különbözõ helyeken és pózokban egy hiányos öltözetû nõ bukkan fel a számítógép képernyõjén.}
{102}{}{Képtelen vagy elolvasni, mi van a képernyõn.}
{103}{}{Hadianyag Hozzáférési Terminál
                                      Erõterek - Kikapcsolva
                                             Elektromos Lapok - Kikapcsolva}
# a lõszer nem jó, mivel van itt egy pár fegyver is, szóval maradt a hadianyag
# ki/bekapcsolvát írtam ide a nyelvhelyesség miatt
{104}{}{Hadianyag Hozzáférési Terminál
                                      Erõterek - Kikapcsolva
                                             Elektromos Lapok - Bekapcsolva}
{105}{}{Hadianyag Hozzáférési Terminál
                                      Erõterek - Bekapcsolva
                                             Elektromos Lapok - Kikapcsolva}
{106}{}{Hadianyag Hozzáférési Terminál
                                      Erõterek - Bekapcsolva
                                             Elektromos Lapok - Bekapcsolva}
{107}{}{Elektromos lapok kikapcsolása}
{108}{}{Erõterek kikapcsolása}
#107-108 fel voltak csererlve. Nyilvan probaltad a fennallo bugot javítani, de ne igy. A bug az bug, de #ne tetezzuk. (bass)
{109}{}{Levelek olvasása}
{110}{}{Kilépés}
{111}{}{[Nem gond, hogy megpróbáld, de ez a macskakaparás nem mond valami sokat neked.]}
{112}{}{Elektromos lapok kikapcsolása.
                                     Kérem, adja meg a jelszót:}
{113}{}{Védelmi rendszer feltörése}
{114}{}{Megpróbálsz rájönni a jelszóra}
{115}{}{Visszatérés a Fõmenübe}
{116}{}{Kilépés}
{117}{}{[Ez a program túl összetett ahhoz, hogy megértsd.]}
{118}{}{Visszatérés a Fõmenübe.}
{119}{}{Kilépés}
{120}{}{[Sikerül megkerülnöd a jelszót és kikapcsolni az elektromos lapokat.]}
{121}{}{Visszatérés a Fõmenübe}
{122}{}{Kilépés}
{123}{}{Erõterek kikapcsolása.
                                                 Kérem, adja meg a jelszót:}
{124}{}{Védelmi rendszer feltörése}
{125}{}{Megpróbálsz rájönni a jelszóra}
{126}{}{Visszatérés a Fõmenübe}
{127}{}{Kilépés}
{128}{}{[A fájlok titkosítottak, így a megfelelõ dekódoló nélkül képtelen vagy bármit is elolvasni.]}
{129}{}{Visszatérés a Fõmenübe}
{130}{}{Kilépés}
{131}{}{[Puszta gyerekjáték! Az erõterek mostantól ki vannak kapcsolva.]}
{132}{}{Visszatérés a Fõmenübe}
{133}{}{Kilépés}
{134}{}{[Valaki elfelejtette bezárni a postafiókját.]
                      1.) Rendelés megerõsítése
                                           2.) Értesítés az evakuálásról
                                       3.) Egy levelezõtárs üdvözlete
                                     4.) Üzlet}
{135}{}{[Kiválasztod, melyik tárgyú levelet szeretnéd elolvasni]}
{136}{}{Elolvasom a "Rendelés megerõsítése" tárgyú levelet.}
{137}{}{Elolvasom az "Értesítés az evakuálásról" tárgyú levelet.}
{138}{}{Elolvasom a "Levelezõtárs üdvözlete" tárgyú levelet.}
{139}{}{Elolvasom az "Üzlet" tárgyú levelet.}
{140}{}{Visszatérés a Fõmenübe}
{141}{}{Kilépés}
{142}{}{Ez egy megerõsítés az ön videófilm rendelésére, pontosabban a "Debbie lerendezi a hadsereget" és a "Mély torok" 1059. epizódjára. A küldemény a levél érkezésétõl számolva 2-4 héten belül várható. Köszönjük rendelését.}
{143}{}{Más levelet is elolvasok}
{144}{}{Kilépés}
{145}{}{A Sierra Hadiraktár evakuálása egy hétre lett szûkítve. Clifton Tábornok parancsára minden biztonsági intézkedést hatályba kell léptetni ez idõ alatt.}
{146}{}{Más levelet is elolvasok}
{147}{}{Kilépés}
{148}{}{[Miközben füst tör fel a számítógép-terminálból, halk búgásra leszel figyelmes. Megdöbbenve állsz és bámulod, ahogy a billentyûzet ragacsos tócsává változik. Hmm... ez valószínûleg egyike azoknak a vírusoknak, amirõl már hallottál korábban.]}
{149}{}{Kilépés}
{150}{}{Klinger vagyok a 8063-as körzetbõl. Égetõ szükségünk van a 102-53B sorozatszámú alkatrészre. Ha megsürgeted az eljárást, van egy láda 2155-es évjáratú Chateau Lafayett-em a számodra. Küldd el nekem, amilyen gyorsan csak lehet!}
# ASAP??? ötlet As soon as possible (bass)
{151}{}{Más levelet is elolvasok}
{152}{}{Kilépés}
{153}{}{[Milyen hihetetlen szerencse! Sikerült rájönnöd a helyes jelszóra. "Dudák"] Elektromos Lapok kikapcsolása folyamatban!}
# Ez aztán a szleng:)
{154}{}{Visszatérés a Fõmenübe}
{155}{}{Kilépés}
{156}{}{[Akárhogy is próbálkozol, képtelen vagy rájönni a jelszóra.]}
{157}{}{Visszatérés a Fõmenübe}
{158}{}{Kilépés}
{159}{}{[Ez az ember bizonyára nagyon rajong a nõi keblekért. A jelszó a következõ volt: "Mellbimbók"]  Erõterek kikapcsolása folyamatban!}
#és ez is... 
{160}{}{Visszatérés a Fõmenübe}
{161}{}{Kilépés}
{162}{}{[Akárhogy is próbálkozol, képtelen vagy rájönni a jelszóra.]}
{163}{}{Visszatérés a Fõmenübe}
{164}{}{Kilépés}
{165}{}{[Ügyködésednek hála, a képernyõ hirtelen az arcodba robbant.]}
{166}{}{Kilépés}

{200}{}{[Ez a terminál többé már nem mûködõképes.]}
