# !!! Figyelem a következõ sorok megváltoztatása eltájolja a játékban a többi sort !!!
{100}{}{Számítógép-terminál.}
{101}{}{A képerernyõkímélõ aktív.}
{103}{}{Skynet Biztonsági Rendszer
                                 Betolakodó a 2. szinten
                                                   Ellenintézkedések aktiválása az 1. szinten
                        Ellenintézkedések - A továbbítás megszûnt
                        Automata javító rendszer aktiválása}
{104}{}{Skynet Biztonsági Rendszer
                                          Betolakodó a 2. szinten
                                             Ellenintézkedések aktiválása az 1. szinten
                       Energia-átirányítási kísérlet az erõtér-emittereknek}
{105}{}{Skynet Biztonsági Rendszer
                                          Betolakodó a 2. szinten
                                             Ellenintézkedések aktiválása az 1. szinten}
{106}{}{2. Szint Riasztásának Vége - Téves Riasztás}
{107}{}{[Felfedezel egy "Súgó" feliratú billentyût a klaviatúrán.] Megnyomod.}
{108}{}{Feltöröd a Biztonsági Rendszert}
{109}{}{Megkísérled kikapcsolni a riasztót}
{110}{}{Kilépés.}
{111}{}{Agrr! [Öklöddel csalódottan rávágsz az billentyûzetre.]}
{113}{}{Skynet Biztonsági Rendszer
                                          Figyelem! Behatoló az 1. Szinten
                                    Retina Szkenner Aktiválva
                                          Szkennelés...
                                                           Keresés az adatbázisban... }
{300}{}{ - ID Megerõsítve}
{301}{}{/Utolsó belépés: }
{302}{}{Felvonózár kikapcsolása}

{303}{}{Clifton tábornok }
#ez nem tudom, miért van itt
#Azért mert az egyik szobában megtalálható Clifton szeme (Dixoné az 1. szinten van).(Randal)
{304}{}{                                         Dixon tizedes }
#szerintem ez a két név fel volt cserélve az eredetiben, így bátorkodtam helyrehozni
{305}{}{2120. December 5./             }
{306}{}{ napja./                        }
#teszt

{114}{}{Skynet Biztonsági Rendszer
                                        Figyelem! Betolakodó regisztrálva az alábbi szinten: 1  }
{307}{}{            Skynet Biztonsági Rendszer
                                        Figyelem! Betolakodó regisztrálva az alábbi szinteken: }
{115}{}{A 2. szint Riasztó Rendszerének aktiválása.}
{116}{}{Saját diagnosztikai program futtatása.}
{117}{}{Kilépés}
{118}{}{Agrr! [Öklöddel csalódottan rávágsz a billentyûzetre.]}
{120}{}{Skynet Biztonsági Rendszer
                                          Hozzáférés a terminálhoz: Elutasítva}
{122}{}{Kilépés.}
{124}{}{Hiba!
                                                                 Nincsenek rendszerfájlok jelen
                                            Kérem, indítsa újra a gépet}
# nem igaz, hogy csak nekem nincs ilyen szerencsétlen karakterem... Ha valakinek van, az légyszi küldje el a karakter lapját, hogy tesztelni tudjam. Köszi
{126}{}{Kilépés}
{127}{}{Parancs megvizsgálása - Kérem, várjon...
                           Felülbírált felhasználói parancs
                                     Belépés elutasítva}
{128}{}{[Tovább]}
{129}{}{A Riasztó kikapcsolásához nyomja meg az 1-est!
                 Diagnosztikához nyomja meg a 2-est!
                             Kilépéshez nyomja meg a 3-ast!}
{130}{}{Megnyomod az 1-est!}
{131}{}{Megnyomod a 2-est!}
{132}{}{Megnyomod a 3-ast!}
{133}{}{Kilépés}
{134}{}{Figyelem! Ez a program akkor mûködik a leghatásosabban, ha ön minden programot bezár. Biztosan szeretné most futtatni?}
{135}{}{Igen.}
{136}{}{Nem.}
{137}{}{Kilépés}
{138}{}{===Biztonsági program bezárása===
                                Adat-struktúra analizálása...
                                       Diagnosztikai program félbeszakadt
                               Diagnosztikai program kikapcsolva
                                 Biztonsági program újraindítása
                                   Riasztás visszaállítása
                                              Skynet Biztonsági Rendszer - Készenléti állapot}
{139}{}{[Úgy látszik, ez nem sikerült] Kilépés}
{140}{}{Hozzáférés megtagadva...
                                             Hozzáférés megtagadva...
                                           Hozzáférés engedélyezve
                                           A 2. szint riasztó rendszere kikapcsolva}
{141}{}{Kilépés}
{142}{}{Illetéktelen hozzáférés
                                                Biztonsági kizárás elindítása a terminálon}
{143}{}{Kilépés}
{144}{}{Parancs Értelmezése - Kérem, várjon...
                             Befejezni az összes...
                                                Figyelem! Skynet által felülbírálva - 667. Kód
                    Hozzáférés ehhez a terminálhoz: Elutasítva.}
{145}{}{Kilépés}
{146}{}{Diagnosztikai Program befejezése.}
{147}{}{[Tovább]}
# én nem tudom, de ennek a terminálnak nem sok értelme van...
