# !!! Figyelem a következõ sorok megváltoztatása eltájolja a játékban a többi sort !!!
{100}{}{Ez itt nem más, mint egy aktív számítógép-terminál.}
{101}{}{Közelebbrõl megvizsgálva egy fénylõ feliratra leszel figyelmes: "I*tel Inside".}
{102}{}{Képtelen vagy elolvasni, mi van a képernyõn.}
{200}{}{ képtelen elolvasni, mi van a képernyõn.}

{103}{}{Fõ Energia - Kikapcsolva                      
                        Tartalék Energia - Bekapcsolva
                                    Biztonsági Rendszer Újraindítása    
                             Figyelem! Alacsony energiaszint - Az Erõterek  50%-osan mûködnek
                                                          Betöltés Befejezve...
                                                Skynet Biztonsági Ellenõrzés 1
                                   Kérem, adja meg a jelszót:}
{104}{}{1-es Skynet Biztonsági Ellenõrzõ Pont
                                       Kérem, adja meg a jelszót:}
{105}{}{Csajkovszkij}
{106}{}{Szezám tárulj!}
{107}{}{Sierra}
{108}{}{Armageddon}
{109}{}{Feltöröd a védelmi rendszert}
{110}{}{Gõzöd nincs. Kilépés.}
{113}{}{Erõterek az 1. Szinten: Kikapcsolva}
{115}{}{Kilépés}
{117}{}{Ehhez a terminálhoz le van tiltva a hozzáférés.}
{119}{}{Kilépés}
{121}{}{29-es Hibakód
                                                            Nem sikerült csatlakozni a szerverhez
                                     Kérem, indítsa újra a gépet!}
# hát lehet maradnia kellett volna a zsargóval, lásd server, error404, deaktiválva stb.
{123}{}{Kilépés}
{124}{}{Belépés: Engedélyezve
                                                 Erõterek az 1. szinten: Kikapcsolva}
{125}{}{Kilépés}
{126}{}{Érvénytelen Jelszó
                                                     Belepés: Elutasítva
                                                   Kérem, adja meg a jelszót:}
{127}{}{Csajkovszkij}
{128}{}{Szezám tárulj!}
{129}{}{Sierra}
{130}{}{Armageddon}
{131}{}{Feltöröd a Biztonsági Rendszert}
{132}{}{Gõzöd nincs. Kilépés.}
{133}{}{[A <Ctrl><Alt><C> összeomlást okozott a programnak. Abban reménykedsz, hogy a maradék biztonsági berendezéseken is hasonlóan egyszerû lesz átrágnod magad.]}
{134}{}{Kilépés.}
{135}{}{Biztonsági Rés az 1. Szinten
                                          Biztonsági Protokoll Aktiválása
                                    A Felhasználók terminál-hozzáférése visszavonva  
     Átvitel Vége}
     #ha valakinek van ilyen állása, akkor írjon, hogy tesztelhessem: mig21@fremail.hu
{136}{}{Kilépés}
{137}{}{A hozzá-nemértésed bekapcsolta a riasztó rendszert.}
{138}{}{Ez nem jött be! A program túl összetett, hogy megértsd.}
{139}{}{Kilépés.}

{300}{}{Úgy látszik, a számítógép védelmi mechanizmussal van ellátva.}
{301}{}{Áramütés ért, ezért -}
{302}{}{, a társad, áramütést szenvedett, ezért -}
{303}{}{ ÉP a büntetés!}
