# !!! Figyelem a következõ sorok megváltoztatása eltájolja a játékban a többi sort !!!
{100}{}{Számítógép-terminál}
{101}{}{Ez a Menedék-Tek Automata Szerveltávolító Berendezés irányító egysége}
{102}{}{Képtelen vagy elolvasni, mi van a képernyõn.}
{103}{}{Üdvözli Önt a Menedék-Tek Ultramodern Szerveltávolító Berendezése. Az operációhoz kérem, tegye be a donort a mûtõbe, fordítsa el a tárcsát a megfelelõ faj nevére, és válassza ki, milyen szervet szeretne eltávolítani!}
{104}{}{Kiválasztod a fajt}
{105}{}{Kiválasztod a szervet}
{106}{}{Kilépés}
{107}{}{Agrr!}
{108}{}{[A tárcsán a következõ fajok szerepelnek:]
                         Kutya
                                                                   Macska
                                                                  Madár
                                                                   Rágcsáló
                                                                Ember [Bár ez az utóbbi csak bele van karcolva a konzolba...]}
# A road runner az a kengyelfutó gyalogkakukk megfelelõje, de én inkább madarakat írtam a helyére
{109}{}{}
{110}{}{}
{111}{}{}
{112}{}{}
{113}{}{}
{114}{}{Kiválasztod a Kutyát}
{115}{}{Kiválasztod a Macskát}
{116}{}{Kiválasztod a Madarat}
{117}{}{Kiválasztod a Rágcsálót}
{118}{}{Kiválasztod az Embert}
{119}{}{Új fajt karcolsz a konzolra.}
{120}{}{Kilépés}
{121}{}{[Felveszel egy darab fémet és eltûnõdsz, hogy mit is kellene belevésni a konzolba.]}
{122}{}{Bevésed a Mutáns szót a konzolba.}
{123}{}{Bevésed a Halálkarom szót a konzolba.}
{124}{}{Kilépés}
{125}{}{Jelenlegi választás:                                                    }
{126}{}{Faj: }
{127}{}{Szerv: }
{128}{}{Kiválasztod a Fajt}
{129}{}{Kiválasztod a Szervet}
{130}{}{Az eltávolítás megkezdése.}
{131}{}{Kilépés}
{132}{}{[A tárcsán látható szervek listája:]
                                   Szív
                                                                     Agy
                                                                      Vese
                                                                    Máj
                                                                      Tüdõ
                                                                     Vakbél
                                                                  Vastagbél [Csak bele van karcolva]}
{133}{}{}
{134}{}{}
{135}{}{}
{136}{}{}
{137}{}{}
{138}{}{}
{139}{}{}
{140}{}{A Szívet választod}
{141}{}{Az Agyat választod}
{142}{}{A Vesét választod}
{143}{}{A Májat választod}
{144}{}{A Tüdõt választod}
{145}{}{A Vakbelet választod}
{146}{}{A Vastagbelet választod}
{147}{}{Kilépés}
{148}{}{A donor nincs jelen a mûtõben.}
{149}{}{Az eltávolítás nem sikerült}
{150}{}{Az eltávolítás sikeresen befejezõdött}
{151}{}{Az eltávolítás sikeresen befejezõdött
                                           Köszönjük, hogy a Menedék-Tek-et választotta! Kéjük, nézze meg katalógusunkat, melyben egy sor kiváló Menedék-Tek termék szerepel!}
{152}{}{}
{153}{}{Kilépés}

{170}{}{Ember                                                              }
{171}{}{Kutya                                                             }
{172}{}{Macska                                                            }
{173}{}{Madár                                                              }
{174}{}{Rágcsáló                                                          }
{175}{}{Mutáns                                                            }
{176}{}{Halálkarom                                                        }

{180}{}{Agy}
{181}{}{Szív}
{182}{}{Vese}
{183}{}{Máj}
{184}{}{Tüdõ}
{185}{}{Vakbél}
{186}{}{Vastagbél}

{200}{}{ képtelen elolvasni, mi van a képernyõn.}
