# !!! Figyelem a következõ sorok megváltoztatása eltájolja a játékban a többi sort !!!
{100}{}{Számítógép-terminál.}
{101}{}{Úgy tûnik, ez egy biztonsági terminál.}
{102}{}{Képtelen vagy elolvasni, mi van a képernyõre írva.}
{103}{}{Skynet Biztonsági Rendszer
                                          Hozzáférés: Elutasítva}
{104}{}{}
{105}{}{Kilépés}
{106}{}{Hiba!
                                                                 A Rendszerfájlok nincsenek jelen
                                      Kérem, indítsa újra a számítógépet!}
 # itt is ugyanaz van mint az elõbbieknél. Please help me!
{107}{}{}
{108}{}{}
{109}{}{Kilépés}


{200}{}{ képtelen elolvasni, mi van a képernyõre írva.}
{300}{}{Úgy látszik, a számítógép védelmi mechanizmussal van ellátva.}
