# Dialog Editor last position: 1
{100}{}{Ez itt egy Black Jack asztal.}
{101}{}{Õ egy Black Jack osztó.}
{102}{}{Szeretnél Black Jacket játszani? A minimun tét }
{103}{}{ dolcsi.}
{104}{}{Persze, hogy szeretnék.}
{105}{}{Kösz nem.}
{106}{}{Mi blek dzsek?}
{107}{}{Sajnálom, de úgy néz ki, nincs elég pénzed a minimális téthez. Gyere vissza, ha több pénzed van!}
{108}{}{Oké, minden minimum tét bent van.}
{109}{}{[osztás]}
{110}{}{Ez egy Black Jack asztal. A minimun tét }
{111}{}{ dollár.}
{112}{}{Egy }
{113}{}{ egy}
{114}{}{, egy}
{115}{}{ és egy }
{116}{}{ kaptál, és}
{117}{}{. Black Jack}
{118}{}{. Semmi}
{119}{}{.}
{120}{}{Az osztónak van }
{121}{}{[még]}
{122}{}{[keverés közben] Akarsz még egyet játszani?}
{123}{}{Sajnálom, úgy látom, elérted itt a maximumot. Megkérlek, hogy távozz!}
{124}{}{Ez a kör a tied.}
{125}{}{Az osztó nyert.}
{126}{}{Nincs semmid.}
{127}{}{Persze, semmi probléma.}
{128}{}{Majd megmutatom én a maximumomat!}
{129}{}{Itt nem játszhatsz többé. Kérlek, menj el!}
{130}{}{Ó, elnézést.}
{131}{}{Nyertél }
{132}{}{ dollárt.}
{201}{}{ász}
{202}{}{kettes}
{203}{}{hármas}
{204}{}{négyes}
{205}{}{ötös}
{206}{}{hatos}
{207}{}{hetes}
{208}{}{nyolcas}
{209}{}{kilences}
{210}{}{tizes}
{211}{}{bubi}
{212}{}{dáma}
{213}{}{király}
{251}{}{kõr}
{252}{}{káró}
{253}{}{pikk}
{254}{}{treff}
