# Dialog Editor last position: 1
{100}{}{Egy kártyaosztót látsz.}
{101}{}{Ez egy kockázó asztal.}
{110}{}{Ifjú leányzó.}
{111}{}{Asztal.}
{140}{}{Ezen az asztalon kockázni szoktak.}
{141}{}{Az asztal tele van mindenféle tárggyal.}
{150}{}{A kaszinó egyik kártyaosztójához van szerencséd.}
{151}{}{Õ a kaszinó egyik kártyaosztója. Int, hogy menj közelebb, és játssz.}
{152}{}{Õ a kaszinó egyik kártyaosztója. A ruhája alig takarja el a testét.}
{153}{}{Õ a kaszinó egyik kártyaosztója. Csinos virgácsai vannak.}
{154}{}{Õ a kaszinó egyik kártyaosztója. Rádkacsint.}
{155}{}{Õ a kaszinó egyik kártyaosztója. Naggggyon jó illata van.}
{160}{}{Ez a nõ hihetetlenül gyönyörû.}
{161}{}{Integet neked, hogy menj oda hozzá.}
{162}{}{Ehhez a kosztümhöz nem sok állatot öltek le. Meglehetõsen apróra sikeredett.}
{163}{}{A virgácsai lenyûgözõek.}
{164}{}{Rádkacsintott!}
{165}{}{Naggggyon jó illata van.}
{175}{}{NINCS KOCKA!!!}
{176}{}{TÚL SOK KOCKA VAN JÁTÉKBAN!!!}
{177}{}{Mióta dobókockát cseréltél, mintha javultak volna az esélyeid.}
{178}{}{Az esélyek nem túl rózsásak.}
{179}{}{Nem tudod pontosan felmérni az esélyeidet.}
{185}{}{Az esélyeid normálisak.}
{186}{}{Nehéz lenne teljes bizonyossággal megjósolni az eredményt.}
{187}{}{Az esélyek nem túl rózsásak.}
{200}{}{::Éljenez::}
{201}{}{::Tapsol::}
{202}{}{::Fütyül::}
{203}{}{}
{204}{}{Már azt hittük, teljesen megfeledkeztél rólunk, míg a világ megmentésén fáradoztál!}
{215}{}{Szia, }
{216}{}{Ha késõbb vágynál egy kis társaságra...}
{217}{}{Hé, te... [kacsint] Nem akarsz kockáztatni?}
{218}{}{Õ aztán... [megborzong] ...nagyon veszélyes!}
{219}{}{Köszöntjük a kaszinóban, }
{220}{}{Szólnál értem egy-két jó szót a fõnöködnek?}
{221}{}{Üdvözlöm hölgyem! Segíthetnék Önnek valamiben?}
{222}{}{Játszani szeretne, hölgyem?}
{223}{}{Ez a lány... [megborzong] ...nagyon veszélyes!}
{235}{}{Ez itt már éppen eléggé kockára tette az életét.}
{236}{}{Öö, szerintem egyszerûen csak eltévesztette a kaszinót...}
{237}{}{Ha nem tûnik el, mielõtt a fiúk meglátnák...}
{238}{}{Ajjaj! Gond van...}
{239}{}{Ez itt már éppen eléggé kockára tette az életét.}
{240}{}{Ehm. Szerintem ez nem éppen a legmegfelelõbb kaszinó neki...}
{241}{}{Ha nem tûnik el, mielõtt a fiúk meglátják...}
{250}{}{Hé, Izomagy! Nem teszel fel pár dolcsit?}
{251}{}{Hé, bajnok... [rádkacsint] ...nincs kedved játszani?}
{252}{}{Hé, bajnok... [mosolyog] ...nem teszed próbára a szerencséd?}
{253}{}{Ha majd késõbb egy kis társaságra vágynál...}
{254}{}{Kíváncsi vagyok, beszélhetnék-e vele...}
{255}{}{Hé, }
{256}{}{Ha szeretnél nyerni néhány dolcsit, a lehetõ legjobb helyen jársz!}
{257}{}{Fortuna megvendégelt minket ma este... mindenki csak nyer!}
{258}{}{Lépjen ide, }
{259}{}{Tölthetek újra?}
{260}{}{Köszöntjük a kaszinóban, }
{261}{}{Helló, }
{262}{}{Próbáljon szerencsét, }
{263}{}{Üdvözöljük a kaszinóban, }
{270}{}{Hé maga ott, Sztár úr! Nem szánna néhány dollárt a szórakozásra?}
{271}{}{Hé, }
{272}{}{Hahó, }
{273}{}{Ha szeretne pár dolcsival gazdagabb lenni, }
{274}{}{Fortuna ma este kegyes hozzátok! Ma itt mindenki csak nyer!}
{275}{}{Jöjjön közelebb, }
{276}{}{Kér még egy italt?}
{277}{}{Köszönjük, hogy ellátogatott a kaszinónkba, }
{278}{}{Hé, miss Díva! Nem akarod elkölteni a gázsidat!}
{279}{}{Táncolsz ma éjjel?}
{290}{}{Szia, szívi! El akarsz költeni egy kis pénzt?}
{291}{}{Szia, édes! [rádkacsint] ...nincs kedved játszani?}
{292}{}{Hé, cukipofa! [mosolyog] Nem akarod próbára tenni a szerencsédet?}
{293}{}{Ha nyerni szeretnél egy kis pénzt, a legjobb helyen jársz!}
{294}{}{Érzem Fortuna asszony illatát... mindenki csak nyer és nyer!}
{295}{}{Lépjen ide, és nyerjen pár dollárt!}
{296}{}{Hozhatok egy újabb italt, kedves?}
{297}{}{Helló, édes! Köszöntelek a kaszinóban!}
{298}{}{Ha most éppen játszani szeretnél, szabad az asztal...}
{299}{}{Csók, édes! Csak nem akarsz egy kis pénzt elkölteni?}
{300}{}{Játszani szeretnél, édesem?}
{301}{}{Köszönjük, hogy a mi kaszinónkat választottad, édesem!}
{320}{}{[Az osztó idegesen rádpillant, majd az ajkába harap.] Öö, tegyék meg tétjeiket! A legkisebb tét }
{321}{}{Tegye meg a tétjét, uram! Legalább }
{322}{}{Hölgyem, tegye meg a tétjét! A minimális tét }
{323}{}{Tegyék még a tétjeiket! A minimális tét  }
{324}{}{Én jác-ccani jobban}
{325}{}{Én játszani csapol le csacsi pucérba'}
{326}{}{Miféle játék? Lehet gekkóbõrbe foganni? Nekem van gekk... óóóóóó... mi szép fények!}
{327}{}{[Van }
{328}{}{Fogadok }
{329}{}{Áááá, nekem ez már túl nagymenõ!}
{330}{}{Köszönöm, ma nincs több tét!}
{331}{}{Ööö... Bocsi, de nem tudom, hogy kell ezeket a fránya játékokat játszani.}
{340}{}{Izé... Úgy hallottam, hogy az értelmi fogyatékosaknak agyat osztogatnak hátul. Talán nem ártana ott körülnézned.}
{341}{}{Öhm, rendben, uram. Jöjjön vissza minél hamarabb!}
{342}{}{Öhm, rendben, asszonyom. Jöjjön vissza minél hamarabb!}
{343}{}{Uisz-láááááát!}
{344}{}{Álllllat! }
{345}{}{Öööagyizémicsoda?! Én akar megnézni!}
{350}{}{Jól van, uram. Jöjjön vissza minél hamarabb!}
{351}{}{Jól van, hölgyem. Jöjjön vissza minél hamarabb!}
{352}{}{[Az osztó felhúzza a szemöldökét.] }
{354}{}{Kösz, meglesz!}
{355}{}{Meglehet...}
{400}{}{Sajnálom. Talán legközelebb több szerencséje lesz.}
{401}{}{Sajnálom, uram! Talán majd a következõ alkalommal...}
{402}{}{Együttérzek, asszonyom! Esetleg ha újra megpróbálná...}
{410}{}{Ön nyert!}
{411}{}{Ön nyert! Gratulálok, uram!}
{412}{}{Ön nyert! Gratulálok, hölgyem!}
{420}{}{Nyert! Megduplázta a pénzét!}
{421}{}{Ön nyert! Megkétszerezte a pénzét! Jól csinálta, uram!}
{422}{}{Ön nyert! Most dupla pénzt vihet haza! Nagyszerû volt, hölgyem!}
{430}{}{Gratulálok! Háromszoros pénz üti a markát!}
{431}{}{Hihetetlen! Megtriplázta a nyereményét! A szerencse ma este magának dolgozik! Szép volt, uram!}
{432}{}{Fantasztikus! A nyeremény háromszorosát vitte most el! Maga ma este nagyon szerencsés! Csodálatos volt, uram!}
{440}{}{Mára elég lesz.}
{441}{}{Ma estére elég lesz ennyi.}
{450}{}{Elnézést, de az asztalt lezártuk. Valaki megbuherálta a kockákat.}
{451}{}{Bocsánatot kérek, uram, de az asztal nem használható. Valaki csalt a kockákkal.}
{452}{}{Bocsásson meg asszonyom, az asztal most nem üzemelhet. Valaki megberhelte a kockákat.}
{453}{}{Ehhh, rendben.}
{454}{}{Sajnálattal hallom. Kösz!}
{2203}{}{! Isten hozta a kaszinóban, tisztelt hõs!}
{2215}{}{! Segíthetek *valamiben*?}
{2219}{}{!}
{2255}{}{. Szeretne gazdag lenni?}
{2258}{}{, nyerjen egy kis pénzt!}
{2260}{}{ dollár.}
{2261}{}{. Árulja el, ha bármiben is a segítségére tudnék lenni!}
{2262}{}{?}
{2263}{}{ dollár.}
{2321}{}{ dollár. Tegyék meg a tétjeiket!...}
{2327}{}{ dollárod] }
{2328}{}{ dollárban.}
{2344}{}{ számára újabb tárgy mindig jön jól [Távozol.]}
{2352}{}{ dolcsi neked túl nagymenõ? [gúnyolódik] Haver, te aztán tényleg rossz városban kötöttél ki!}
{2353}{}{ dolcsi neked túl nagymenõ? [megvetõen] Csajszikám, ez a város aztán tényleg nem neked való!}
