# Dialog Editor last position: 1
{100}{}{Sikeresen kinyitottad a zárat.}
{101}{}{Nem sikerült kinyitnod a zárat.}
{102}{}{Sikeresen bezártad.}
{103}{}{Nem sikerült bezárnod.}
{200}{}{ sikeresen kinyitotta a zárat.}
{201}{}{ képtelen kinyitnia a zárat.}
{202}{}{ sikeresen bezárta.}
{203}{}{ képtelen bezárni.}
{300}{}{A robbanás megsemmisítette a zárat.}
{301}{}{A robbanás meg sem kottyant a zárnak.}
{400}{}{Sikeresen kifeszítetted a zárat.}
{401}{}{Képtelen vagy kifeszíteni a zárat.}
{500}{}{ sikeresen kifeszítette a zárat.}
{501}{}{ képtelen kifeszíteni a zárat.}
