{100}{}{Ez az autó nem úgy néz ki, mintha mûködne. Bár, jobb állapotban van, mint a többi autó a környéken. Ezt még talán meg lehet javítani.}
{101}{}{Ez az autó nem mûködik, hiányzik belõle az üzemanyagelosztó.}
{200}{}{Sikeresen beszerelted az üzemanyagelosztót a kocsiba.}
{210}{}{Nem tudtad megjavítanod az autót, nem sikerült beszerelned az üzemanyagelosztót.}
{300}{}{Nem sikerült megjavítanod az autót. Talán tényleg az üzemanyagelosztó hiányzik belõle, amirõl Smitty beszélt.}
{400}{}{Túl sok zajjal járna felnyitni a motorháztetõt, és a megjavítani a kocsit.}
