call ..\p ACBRAHMN
call ..\p ACDOG
call ..\p ACERIC
call ..\p ACFIST
call ..\p ACGECKO
call ..\p ACJORDAN
call ..\p ACKLINT
call ..\p ACMORLIS
call ..\p ACMYNOC
call ..\p ACNAGOR
call ..\p ACSPORPL
call ..\p ACTEMVIL
call ..\p ACVILLGR
call ..\p ACWARIOR
call ..\p AIBKDOR
call ..\p AIBROC
call ..\p AICAVDOR
call ..\p AICHEST
call ..\p AICROPS
call ..\p AILKBOX
call ..\p AITEMCST
call ..\p AITEMDOR
call ..\p AIVASE
call ..\p AIXANDER
call ..\p ASCRLDR
call ..\p ASWELL
call ..\p ATDEATH
call ..\p ATGOO
call ..\p ATSRTRP0
call ..\p ATSRTRP1
call ..\p ATSRTRP2
call ..\p ATSRTRP3
call ..\p ATSRTRP4
call ..\p ATSRTRP5
call ..\p ATSRTRP6
call ..\p ATSRTRP7
call ..\p ATSRTRP8
call ..\p ATSRTRP9
call ..\p ATSRTRPA
call ..\p ATSRTRPB
call ..\p ATSRTRPC
call ..\p ATSRTRPD
call ..\p ATSRTRPE
call ..\p ATSRTRPF
call ..\p SPRTRP50
call ..\p SPRTRP51
call ..\p SPRTRP52
call ..\p SPRTRP53
