call ..\p HCAILEEN
call ..\p HCANT1
call ..\p HCANT2
call ..\p HCBNKGRD
call ..\p HCBRIAN
call ..\p HCCHAD
call ..\p HCCHUCK
call ..\p HCDAN
call ..\p HCDOC
call ..\p HCELMO
call ..\p HCENCHA
call ..\p HCENCHB
call ..\p HCERIC
call ..\p HCFEMALE
call ..\p HCFRANCI
call ..\p HCFRANK
call ..\p HCGHOUL
call ..\p HCGRD2
call ..\p HCHENCH
call ..\p HCHUSWIF
call ..\p HCJACOB
call ..\p HCLIZ
call ..\p HCLUMPY
call ..\p HCMALE
call ..\p HCMANSON
call ..\p HCMARCUS
call ..\p HCMICKY
call ..\p HCMINERS
call ..\p HCMUTANT
call ..\p HCOLDGHL
call ..\p HCOUTFIT
call ..\p HCPHIL
call ..\p HCPROF
call ..\p HCSCORP
call ..\p HCSEYMOR
call ..\p HCSTEVE
call ..\p HCSULVAN
call ..\p HCSUPER
call ..\p HCTYPHON
call ..\p HCZAIUS
call ..\p HIBH1BOX
call ..\p HICAVEIN
call ..\p HICONSOL
call ..\p HIDEAD
call ..\p HIDOCBOX
call ..\p HIJACBOX
call ..\p HILADDER
call ..\p HILBOX
call ..\p HIMANHOL
call ..\p HINOTE
call ..\p HIOUTBOX
call ..\p HIPOWER
call ..\p HIPRFBX1
call ..\p HIPRFBX2
call ..\p HIWELL
call ..\p HSCELLDR
call ..\p HSCRLDR
call ..\p HSPURIFY
call ..\p HTBODY
call ..\p HTCHUCK
call ..\p HTCORPSE
call ..\p HTFLIES
call ..\p HTSECRET
