call ..\p RCASCGRD
call ..\p RCASCORT
call ..\p RCBETTE
call ..\p RCCAMINT
call ..\p RCCSHTND
call ..\p RCCVNDRV
call ..\p RCCVNGRD
call ..\p RCDICK
call ..\p RCDRJOHN
call ..\p RCFANNIE
call ..\p RCFERN
call ..\p RCFITRAT
call ..\p RCFROG
call ..\p RCGAMBLE
call ..\p RCGENPES
call ..\p RCHAKES
call ..\p RCHOFFY
call ..\p RCJANE
call ..\p RCJOSH
call ..\p RCLOU
call ..\p RCMARGE
call ..\p RCMARION
call ..\p RCMCGREW
call ..\p RCMODJES
call ..\p RCMORBRS
call ..\p RCMOTGNG
call ..\p RCNORD
call ..\p RCRATRAY
call ..\p RCROONEY
call ..\p RCSAVINE
call ..\p RCSTANWL
call ..\p RCVELANI
call ..\p RCWADE
call ..\p RCWANAMI
call ..\p RICSHBOX
call ..\p RIJALDOR
call ..\p RIMINENT
call ..\p RIVLTDOR
call ..\p RTLNDMIN
