{100}{}{Armas Leves}
{101}{}{Armas Pesadas}
{102}{}{Armas de Energia}
{103}{}{Desarmado}
{104}{}{Armas Brancas}
{105}{}{Arremesso}
{106}{}{Primeiros Socorros}
{107}{}{Medicina}
{108}{}{Furtividade}
{109}{}{Arrombamento}
{110}{}{Roubo}
{111}{}{Armadilhas}
{112}{}{Ciência}
{113}{}{Reparo}
{114}{}{Persuadir}
{115}{}{Negociação}
{116}{}{Jogos}
{117}{}{Sobrevivência}
{200}{}{O uso, cuidados e conhecimentos gerais de pequenas armas de fogo - pistolas, SMGs e rifles.}
{201}{}{O uso e manutenção das grandes armas - metralhadoras, lança-foguetes, lança-chamas e tal.}
{202}{}{O cuidado e a alimentação de armas baseadas em energia. Como armar e operar as armas que usam tecnologia laser ou plasma.}
{203}{}{Uma combinação de artes marciais, boxe e outras artes marciais. Combate com as mãos e pés.}
{204}{}{É o uso de armas de mão, ou combate corpo a corpo - facas, marretas, lanças, tacos e assim por diante.}
{205}{}{A habilidade de lançar varias armas como: facas, lanças e granadas.}
{206}{}{Habilidade geral de cura. Usado para curar pequenos cortes, arranhões e outros males menores. Em termos de jogo, o uso de primeiros socorros pode curar mais pontos de vida ao longo do tempo do que apenas descansar.}
{207}{}{A cura de ferimentos e principais membros mutilados. Sem essa habilidade, ele vai ter um período muito longo de tempo para restaurar membros mutilados.}
{208}{}{Quiet movement, and the ability to remain unnoticed.  If successful, you will be much harder to locate.  You cannot run and sneak at the same time.}
{209}{}{The skill of opening locks without the proper key.  The use of lockpicks or electronic lockpicks will greatly enhance this skill.}
{210}{}{A capacidade de roubar coisas. Pode ser usado para roubar de pessoas ou lugares.}
{211}{}{A descoberta e remoção de armadilhas. Além disso, ajustes dos explosivos para fins de demolição.}
{212}{}{Abrange uma variedade de habilidades de alta tecnologia, como computadores, biologia, física e geologia.}
{213}{}{A aplicação prática da habilidade ciência para a fixação de equipamentos quebrados, máquinas e eletrônicos.}
{214}{}{The ability to communicate in a practical and efficient manner.  The skill of convincing others that your position is correct.  The ability to lie and not get caught.}
{215}{}{Trading and trade-related tasks.  The ability to get better prices for items you sell, and lower prices for items you buy.}
{216}{}{The knowledge and practical skills related to wagering.  The skill at cards, dice and other games.}
{217}{}{Practical knowledge of the outdoors, and the ability to live off the land.  The knowledge of plants and animals.}
{300}{}{+ (4 x AG)}
{301}{}{+ (2 x AG)}
{302}{}{+ (2 x AG)}
{303}{}{+ (2 x (AG + FO))}
{304}{}{+ (2 x (AG + FO))}
{305}{}{+ (4 x AG)}
{306}{}{+(2x(PE+IN))}
{307}{}{+ (PE + IN)}
{308}{}{+ (3 x AG)}
{309}{}{+ (PE + AG)}
{310}{}{+ (3 x AG)}
{311}{}{+ (PE + AG)}
{312}{}{+ (4 x IN)}
{313}{}{+ (3 x IN)}
{314}{}{+ (5 x CA)}
{315}{}{+ (4 x CA)}
{316}{}{+ (5 x SO)}
{317}{}{+ (2 x (RE + IN))}
{500}{}{Cura %d pontos de vida.}
{501}{}{Você parece saudável.}
{502}{}{%s parece saudável.}
{503}{}{Não consegue curar nada.}
{505}{}{Ganhou %d XP por usar suas habilidades.}
{510}{}{\nskill_use: habilidade usada não é válida.}
{512}{}{Você não pode curar os mortos.}
{513}{}{Deixe os mortos em paz.}
{514}{}{Ele está morto, deixe-o em paz.}
{520}{}{Você se cura %s.}
{521}{}{Você cura %s.}
{525}{}{Você não conseguem se curar %s.}
{526}{}{Você não consegue cura-lo %s.}
{530}{}{olho ferido}
{531}{}{braço esquerdo mutilado}
{532}{}{braço direito mutilado}
{533}{}{perna direita mutilado}
{534}{}{perna esquerda mutilado}
{550}{}{Você falha em arrombar a fechadura.}
{551}{}{Você não encontrar nenhuma armadilha.}
{552}{}{Você não aprende nada.}
{553}{}{Você não pode reparar isso.}
{570}{}{Você foi pego roubando o %s.}
{571}{}{Você rouba %s.}
{572}{}{Você foi pego plantando %s.}
{573}{}{Você planta %s.}
{590}{}{You've taxed your ability with that skill. Wait a while.}
{591}{}{Você está muito cansado.}
{592}{}{O cansaço pode matá-lo.}
{600}{}{Não tem habilidade suficiente para curar ossos quebrados.}
{601}{}{Impossível reparar Unidade robótica.}
{1000}{}{Me deixe ajudar.}
{1001}{}{Eu posso fazer isso.}
{1002}{}{Eu entendi.}
{1003}{}{Fico feliz em ajudar.}
{1004}{}{Tudo bem.}
{1005}{}{Eu vou tentar.}
{1100}{}{Se você tiver problemas, me avise.}
{1101}{}{Você entendeu?}
{1102}{}{Se é isso que você quer.}
{1103}{}{Vá em frente e tenta.}
{1104}{}{Vá em frente.}
