call ..\p DCADDICT
call ..\p DCANAN
call ..\p DCANNA
call ..\p DCATKSLV
call ..\p DCBILLY
call ..\p DCBLKJCK
call ..\p DCCARNKD
call ..\p DCCRAPS
call ..\p DCCUSTMR
call ..\p DCDEREK
call ..\p DCFLICK
call ..\p DCFRANKI
call ..\p DCFRED
call ..\p DCG1GRD
call ..\p DCG2GRD
call ..\p DCGAMBLE
call ..\p DCJOEY
call ..\p DCLARA
call ..\p DCMARC
call ..\p DCMETROM
call ..\p DCMETZGE
call ..\p DCMOM
call ..\p DCORPHAN
call ..\p DCPENGRD
call ..\p DCPETEY
call ..\p DCREBDOR
call ..\p DCREBECC
call ..\p DCREBGRD
call ..\p DCRNSLVR
call ..\p DCRUNSLV
call ..\p DCSHEILA
call ..\p DCSLAVE
call ..\p DCSLAVER
call ..\p DCSLVGRT
call ..\p DCSLVRUN
call ..\p DCSMITTY
call ..\p DCSTORY1
call ..\p DCSTORY2
call ..\p DCTEMP
call ..\p DCTHUG
call ..\p DCTUBBY
call ..\p DCTUBFRI
call ..\p DCTYLER
call ..\p DCVIC
call ..\p DCVICGRD
call ..\p DIANNGRV
call ..\p DIBONES
call ..\p DIBULBRD
call ..\p DICHCDOR
call ..\p DICRATE
call ..\p DIDADGRV
call ..\p DIDIARY
call ..\p DIDOOR
call ..\p DIFLIBOX
call ..\p DIFLKBOX
call ..\p DIMETBOX
call ..\p DIMOMBOX
call ..\p DIMOMGRV
call ..\p DIPENDOR
call ..\p DIREBBOK
call ..\p DIREBDOR
call ..\p DIROMDOR
call ..\p DISLVCRT
call ..\p DISMIBOX
call ..\p DISTILL
call ..\p DITUBBOX
call ..\p DIVICDOR
call ..\p DIVICTBL
