call ..\p KCALDO
call ..\p KCARDIN
call ..\p KCBGIRL
call ..\p KCBHCUST
call ..\p KCBOB
call ..\p KCBRAHMN
call ..\p KCDUNTON
call ..\p KCGGCUST
call ..\p KCGNRATR
call ..\p KCHILD
call ..\p KCITIZEN
call ..\p KCJENNY
call ..\p KCLVATR
call ..\p KCMAIDA
call ..\p KCRATGOD
call ..\p KCROB
call ..\p KCSAJAG
call ..\p KCSALLY
call ..\p KCSCORP
call ..\p KCSCORPA
call ..\p KCSLIM
call ..\p KCSMILEY
call ..\p KCSULIK
call ..\p KCTORR
call ..\p KCTRAPR
call ..\p KCWUPASS
call ..\p KCYELLOW
call ..\p KIBBOX
call ..\p KIDBOX
call ..\p KISBOX
call ..\p KSBBOARD
call ..\p KSCORVEG
call ..\p KSCVDOOR
call ..\p KSMALLDR
call ..\p KSTILL
call ..\p KTGOO
call ..\p KTSMOKE
call ..\p STUFF
call ..\p TRESPASS
