call ..\p BCBILL
call ..\p BCBRAHMN
call ..\p BCCRISSY
call ..\p BCDALIA
call ..\p BCDARDOG
call ..\p BCDARGRD
call ..\p BCDARION
call ..\p BCGENGRD
call ..\p BCJOHN
call ..\p BCJONES
call ..\p BCKARLA
call ..\p BCPHIL
call ..\p BCREBECC
call ..\p BCROBERT
call ..\p BCSARA
call ..\p BCZEKE
call ..\p BIENTDR
call ..\p BISPYHOL
call ..\p BSCOMP1
call ..\p BSCOMP2
call ..\p BSCOMP3
call ..\p BSCOMP4
call ..\p BSCOMP5
call ..\p BSELEV
call ..\p BSEMTR
call ..\p BSFIELD
call ..\p BSPOWER
call ..\p BSSDOR1
