{100}{}{Widzisz Jordana. Jak zwykle wywija w³óczni¹.}
{101}{}{Widzisz Jordana. Jak zwykle wywija w³óczni¹.}
{102}{}{Good luck!  I must get back to my training.}
{103}{}{Hello Chosen One.  I see you're in need of a little training.  Can I be of help?}
{104}{}{Jasne.}
{105}{}{Nie, dziêki.}
{106}{}{To zajmie chwilkê.}
{107}{}{Wiesz ju¿ o w³adaniu w³óczni¹ tyle, co ja.}
{108}{}{Dziêki, Jordan. To mi siê bardzo przyda.}
