{100}{}{Widzisz stra¿nika mostu.}
{101}{}{Widzisz Mynoca, stra¿nika mostu.}

{150}{}{Przed tob¹ stoi wielki wojownik z twojej wioski, trzymaj¹cy w³ócznie.}
{151}{}{[ROZMAWIAJ]}
{152}{}{Witaj, Dziecko Przeznaczenia. Wyruszasz, by odnaleŸæ GECK?}
{153}{}{Tak.}
{154}{}{Tak, lecz zanim pójdê chcê zadaæ ci kilka pytañ.}
{155}{}{Jeszcze nie. Chcê siê jeszcze trochê rozejrzeæ po okolicy.}
{156}{}{Có¿, niechaj bogowie czuwaj¹ nad tob¹.}
{157}{}{Dziêkujê, do widzenia.}
{158}{}{Co chcesz wiedzieæ?}
{159}{}{Co mo¿esz mi powiedzieæ o ludziach, którzy handluj¹ z nasz¹ wiosk¹?}
{160}{}{Co mo¿esz mi powiedzieæ o tym przedmiocie, który pochodzi z Krypty?}
{161}{}{Nic, niewa¿ne.}
{162}{}{Dobrze, lecz nie marnuj zbyt wiele czasu. Bez GECKa jesteœmy zgubieni.}
{163}{}{Wiem, nie martw siê - wszystko jest pod kontrol¹.}
{164}{}{Dlaczego?}
{165}{}{Muszê iœæ. Do widzenia.}
{166}{}{Handlarze? Przyje¿d¿aj¹ z Klamath co dwa miesi¹ce. Wprawdzie ¿aden z nich nie przyjedzie tu przez miesi¹c albo i d³u¿ej, ale Klamath jest tylko kilka dni drogi st¹d.}
{167}{}{Dziêkujê. Do widzenia.}
{168}{}{Co mo¿esz mi powiedzieæ o tym przedmiocie, który mam ze Œwiêtej Krypty?}
{169}{}{Wygl¹da jak metalowa manierka. Mo¿e zosta³a tu przys³ana z Krypty jako znak.}
{170}{}{Mo¿esz mi powiedzieæ, kto przyniós³ ten przedmiot do naszej wioski?}
{171}{}{Dziêkujê. Muszê iœæ. Do zobaczenia.}
{172}{}{Mam nadziejê.}
{173}{}{Przez tw¹ zarozumia³oœæ wszyscy cierpimy! ¯egnaj!}
{174}{}{Do widzenia.}
{175}{}{Dlaczego? Rozejrzyj siê - nasza wioska umiera. Ogrody usychaj¹ a ka¿dego dnia dzieci i starcy s³abn¹. Musisz pomóc nam stworzyæ tu Cudown¹ Krainê zanim bêdzie za póŸno!}
{176}{}{Zajmê siê tym. Do zobaczenia.}
{177}{}{Jestem Dzieckiem Przeznaczenia - "muszê" robiæ tylko to na co mam ochotê. ¯egnaj.}
{178}{}{Nie pamiêtam jego imienia. Wiem tylko, ¿e by³ stary i ha³aœliwy - zbyt ha³aœliwy jak na dobrze wychowanego cz³owieka - ale wiedzia³ du¿o rzeczy. Pochodzi³ z Klamath, to na wschód st¹d.}
{179}{}{Dziêkujê, do widzenia.}
{180}{}{Ci¹gle tu jesteœ? Musisz znaleŸæ GECK. Zostaj¹c tu wcale nam nie pomo¿esz.}
{181}{}{Martw siê tylko mostem, przyjacielu, ja sobie radê dam.}
{182}{}{W³aœnie wychodzi³em. Do zobaczenia, przyjacielu.}
{183}{}{Nie bêdê z tob¹ rozmawiaæ ani chwili d³u¿ej, zarozumia³a œwinio!}
{184}{}{Czy mogê zadaæ ci kolejne pytanie?}
{185}{}{To by³o szybkie! Uda³o ci siê odnaleŸæ œwiêt¹ Kryptê 13?}
{186}{}{Tak.}
{187}{}{Nie, jeszcze nie.}
{188}{}{Tak? To wspaniale! Masz GECK?}
{189}{}{Nie.}
{190}{}{Nie. Nie uda³o mi siê jeszcze porozmawiaæ z mieszkañcami Krypty.}
{191}{}{Nie wydaje mi siê, ¿eby to by³a twoja sprawa, przyjacielu.}
{192}{}{Nie? Dziecko, troje starców zmar³o, odk¹d twa wyprawa siê zaczê³a. Nie marnuj wiêcej czasu.}
{193}{}{Znajdê go, nie martw siê.}
{194}{}{Robi mi siê niedobrze od twego nieustannego zrzêdzenia.}
{195}{}{Dlaczego wiêc rozmawiasz ze mn¹? Porozmawiaj z nimi i przynieœ nam GECK.}
{196}{}{Zrobiê to - wszystko w swoim czasie, przyjacielu.}
{197}{}{Mam doœæ twojego ci¹g³ego zrzêdzenia.}
{198}{}{I co z GECKiem, Dziecko?}
{199}{}{Wiem, gdzie jest Krypta!}
{200}{}{Nie uda³o mi siê odnaleŸæ Krypty 13.}
{201}{}{No popatrz, to¿ to Dziecko Przeznaczenia.}
{202}{}{Witaj.}
{203}{}{Zamknij siê.}
{204}{}{Czy mogê ci zadaæ pytanie?}
{205}{}{Nie, nie mam dla ciebie czasu.}
{206}{}{Niewa¿ne. ¯egnaj}
{207}{}{No có¿, do zobaczenia..}
{208}{}{Powieœ siê..}
{209}{}{Pozdrowienia, Dziecko Têpoty! Widzisz most? PrzechodŸ ostro¿nie. Most niebezpieczny. Nie chcesz spaœæ. Dobra?}
{210}{}{Umm... Hunh?}
{211}{}{Wioska zawiod³a siê na tobie!}
{212}{}{Zdrada! Zginiesz za to!}
{213}{}{Twoja zdrada zgubi nasz lud.}
{214}{}{Dlaczego to robisz?}
{215}{}{Starsza siê myli³a. Widzê z³o w twoich oczach.}

{300}{}{Ojciec nauczy³ mnie, jak uczyniæ ostrze silniejszym. Daj mi kawa³ek krzemienia, a naostrzê równie¿ twoj¹ w³óczniê. Przyda ci siê na Pustkowiach.}
{301}{}{Gdzie mogê znaleŸæ krzemieñ?}
{302}{}{Podobno twoja ciotka Morlis ma kawa³ek. Jest tak wredna, ¿e nie s¹dzê, aby ktoœ j¹ o to pyta³. Oczywiœcie wiedŸma bêdzie chcia³a czegoœ w zamian.}
{303}{}{Dziêki. Do zobaczenia.}
{304}{}{Uda³o ci siê wyci¹gn¹æ krzemieñ od swojej ciotki?}
{305}{}{Tak, mam tu kawa³ek.}
{306}{}{Jeszcze nie.}
{307}{}{Powinien siê nadaæ. Daj mi swoj¹ w³óczniê.}
{308}{}{Proszê bardzo.}
{309}{}{Nie mam w³óczni.}
{310}{}{Robi siê to tak...}
{311}{}{Dziecko Przeznaczenia bez w³óczni? Có¿, bêdê musia³ daæ ci jedn¹ ze swoich. A teraz do dzie³a...}
{312}{}{Oto twoja nowa w³ócznia.}
{313}{}{Dziêki, przyjacielu - ta w³ócznia bardzo mi siê przyda.}
{314}{}{Tak, ale zastanawia mnie twoja w³ócznia. Wygl¹da trochê nietypowo.}

# added in for time limit
{400}{}{Witaj w domu, Dziecko! Uda³o ci siê odnaleŸæ Kryptê? Masz GECK?}
{401}{}{Moja nie go ma.}
{402}{}{Nie, jeszcze go nie mam.}
{403}{}{Nie jestem w nastroju na twoje pytania. ¯egnaj.}
{404}{}{Sprawy nie id¹ zbyt dobrze, Dziecko. Susza jest coraz gorsza i nasze plony na pewno uschn¹. Próbujemy ocaliæ co tylko siê da, aby zgromadziæ zapasy.}
{405}{}{Dlaczego handel nie z inna wioska?}
{406}{}{Moja robiæ co mo¿e. Szukaæ GECK. Moja wróciæ.}
{407}{}{Dlaczego nie mo¿emy handlowaæ ¿ywnoœci¹ z innymi wioskami? }
{408}{}{Robiê co tylko mogê. Kiedy tylko znajdê GECK wrócê z nim.}
{409}{}{Jesteœmy prostym ludem i nie mamy czym handlowaæ. Te kilka miast, z którymi nawi¹zaliœmy kontakt, nie wykaza³o woli pomocy nam.}
{410}{}{Moja rozumieæ.}
{411}{}{Rozumiem.}
{412}{}{Jesteœ nasz¹ nadziej¹, Dziecko Przeznaczenia. Proszê, nie zawiedŸ nas!}
{413}{}{Dobrze ciê widzieæ, Dziecko Przeznaczenia. Jak ci siê powodzi w twojej wyprawie?}
{414}{}{Moja ci¹gle szukaæ.}
{415}{}{Ci¹gle szukam.}
{416}{}{Nie chcê o tym rozmawiaæ.}
{417}{}{Musisz siê œpieszyæ. W wiosce sprawy id¹ coraz gorzej. Wkrótce zacznie brakowaæ jedzenia. Starsza mówi o racjonowaniu tego, co nam jeszcze zosta³o. Bojê siê o przysz³oœæ Arroyo.}
{418}{}{Dziecko! Proszê, powiedz, ¿e twoje zadanie spe³nione. Nasza wioska umiera, a z ni¹ - nasz lud. }
{419}{}{Nie, moja ci¹gle szukaæ}
{420}{}{Nie, wci¹¿ szukam.}
{421}{}{Jak id¹ sprawy?}
{422}{}{Przykro mi, Dziecko Przeznaczenia, lecz zaczynam w ciebie w¹tpiæ. Nasze ¿ycie jest w twoich rêkach. B³agam odnajdŸ Œwiêt¹ Trzynastkê i powróæ do nas z GECKiem!}
{423}{}{Nasze plony obumieraj¹, brahminy zdychaj¹, wszyscy g³oduj¹. P³acz dzieci nie pozwala nam spaæ. Stajemy siê zdesperowani.}
{424}{}{Moja ci¹gle szukaæ.}
{425}{}{Zrobiê wszystko, co w mojej mocy.}
{426}{}{I znowu wracasz do nas, Dziecko. Mam nadziejê, ¿e nie z pustymi rêkami?}
{427}{}{Moja przykro, jeszcze nie znaleŸæ GECK.}
{428}{}{Przykro mi, wci¹¿ nie wiem, gdzie jest GECK.}
{429}{}{Mam tego doœæ.}
{430}{}{Ludzie umieraj¹, a ty siê spokojnie przechadzasz. Mo¿e lepiej bêdzie jak poszukasz gdzieœ indziej zamiast ci¹gle wracaæ tutaj.}

{500}{}{Czy Starsza rozmawia³a ju¿ z tob¹?}

#############################################################
# TELL - ME - ABOUTS #
#############################################################
{1000}{}{Starsza}
{1001}{}{Za³o¿yciel}
{1002}{}{Przybysz z Krypty}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Krypta}
{1006}{}{Dziecko Przeznaczenia}
{1007}{}{Szaman}
{1008}{}{Hakunin}
{1009}{}{Proszek Leczniczy}
{1010}{}{Most}
{1011}{}{Mynoc}

{1100}{}{Starsza jest nasz¹ matk¹ i przywódczyni¹.}
{1101}{}{To nasz wielki przodek, który da³ nam wiedzê.}
{1102}{}{Pierwszy, który walczy³ i zwyciê¿y³ chaos.}
{1103}{}{To jest nasza piêkna wioska.}
{1104}{}{To miasto handlowe le¿¹ce kilka dni na wschód st¹d.}
{1105}{}{Krypta jest rajem.}
{1106}{}{Ty jesteœ Dzieckiem Przeznaczenia.}
{1107}{}{On leczy nas swoimi zio³ami i magi¹. Mieszka w pó³nocnej czêœci naszej wioski.}
{1108}{}{On leczy nas swoimi zio³ami i magia. Mieszka w pó³nocnej czêœci naszej wioski.}
{1109}{}{To magiczny proszek, który ciê uleczy, ale spowoduje sennoœæ.}
{1110}{}{Wielki Most stanowi wyjœcie z naszej wioski od po³udnia.}
{1111}{}{To ja.}
