{100}{}{Widzisz strażnika mostu.}
{101}{}{Widzisz Mynoca, strażnika mostu.}
{150}{}{Przed tobą stoi wielki wojownik z twojej wioski, trzymający włócznie.}
{151}{}{[ROZMAWIAJ]}
{152}{}{Witaj, Dziecko Przeznaczenia. Wyruszasz, by odnaleźć GECK?}
{153}{}{Tak.}
{154}{}{Tak, lecz zanim pójdę chcę zadać ci kilka pytań.}
{155}{}{Jeszcze nie. Chcę się jeszcze trochę rozejrzeć po okolicy.}
{156}{}{Cóż, niechaj bogowie czuwają nad tobą.}
{157}{}{Dziękuję, do widzenia.}
{158}{}{Co chcesz wiedzieć?}
{159}{}{Co możesz mi powiedzieć o ludziach, którzy handlują z naszą wioską?}
{160}{}{Co możesz mi powiedzieć o tym przedmiocie, który pochodzi z Krypty?}
{161}{}{Nic, nieważne.}
{162}{}{Dobrze, lecz nie marnuj zbyt wiele czasu. Bez GECKa jesteśmy zgubieni.}
{163}{}{Wiem, nie martw się - wszystko jest pod kontrolą.}
{164}{}{Dlaczego?}
{165}{}{Muszę iść. Do widzenia.}
{166}{}{Handlarze? Przyjeżdżają z Klamath co dwa miesiące. Wprawdzie żaden z nich nie przyjedzie tu przez miesiąc albo i dłużej, ale Klamath jest tylko kilka dni drogi stąd.}
{167}{}{Dziękuję. Do widzenia.}
{168}{}{Co możesz mi powiedzieć o tym przedmiocie, który mam ze Świętej Krypty?}
{169}{}{Wygląda jak metalowa manierka. Może została tu przysłana z Krypty jako znak.}
{170}{}{Możesz mi powiedzieć, kto przyniósł ten przedmiot do naszej wioski?}
{171}{}{Dziękuję. Muszę iść. Do zobaczenia.}
{172}{}{Mam nadzieję.}
{173}{}{Przez twą zarozumiałość wszyscy cierpimy! Żegnaj!}
{174}{}{Żegnaj.}
{175}{}{Dlaczego? Rozejrzyj się - nasza wioska umiera. Ogrody usychają a każdego dnia dzieci i starcy słabną. Musisz pomóc nam stworzyć tu Cudowną Krainę zanim będzie za późno!}
{176}{}{And I will take care of it.  Goodbye.}
{177}{}{Jestem Dzieckiem Przeznaczenia - "muszę" robić tylko to na co mam ochotę. Żegnaj.}
{178}{}{Nie pamiętam jego imienia. Wiem tylko, że był stary i hałaśliwy - zbyt hałaśliwy jak na dobrze wychowanego człowieka - ale wiedział dużo rzeczy. Pochodził z Klamath, to na wschód stąd.}
{179}{}{Dziękuję, do widzenia.}
{180}{}{Ciągle tu jesteś? Musisz znaleźć GECK. Zostając tu wcale nam nie pomożesz.}
{181}{}{Martw się tylko mostem, przyjacielu, ja sobie radę dam.}
{182}{}{Właśnie wychodziłem. Do zobaczenia, przyjacielu.}
{183}{}{Nie będę z tobą rozmawiać ani chwili dłużej, zarozumiała świnio!}
{184}{}{Chciałbym zapytać cię o coś jeszcze.}
{185}{}{To było szybkie! Udało ci się odnaleźć świętą Kryptę 13?}
{186}{}{Tak.}
{187}{}{Nie, jeszcze nie.}
{188}{}{Tak? To wspaniale! Masz GECK?}
{189}{}{Nie.}
{190}{}{Nie. Nie udało mi się jeszcze porozmawiać z mieszkańcami Krypty.}
{191}{}{Nie wydaje mi się, żeby to była twoja sprawa, przyjacielu.}
{192}{}{Nie? Dziecko, troje starców zmarło, odkąd twa wyprawa się zaczęła. Nie marnuj więcej czasu.}
{193}{}{Znajdę go, nie martw się.}
{194}{}{Robi mi się niedobrze od twego nieustannego zrzędzenia.}
{195}{}{Dlaczego więc rozmawiasz ze mną? Porozmawiaj z nimi i przynieś nam GECK.}
{196}{}{Zrobię to - wszystko w swoim czasie, przyjacielu.}
{197}{}{Robi mi się niedobrze od twego nieustannego zrzędzenia.}
{198}{}{I co z GECKiem, Dziecko?}
{199}{}{Wiem, gdzie jest Krypta!}
{200}{}{Nie udało mi się odnaleźć Krypty 13.}
{201}{}{No popatrz, toż to Dziecko Przeznaczenia.}
{202}{}{Cześć.}
{203}{}{Zamknij się.}
{204}{}{Czy mogę ci zadać pytanie?}
{205}{}{Nie, nie mam dla ciebie czasu.}
{206}{}{Nieważne. Żegnaj}
{207}{}{No cóż, do zobaczenia..}
{208}{}{Powieś się..}
{209}{}{Pozdrowienia, Dziecko Tępoty! Widzisz most? Przechodź ostrożnie. Most niebezpieczny. Nie chcesz spaść. Dobra?}
{210}{}{Umm... Hunh?}
{211}{}{Wioska zawiodła się na tobie!}
{212}{}{Zdrada! Zginiesz za to!}
{213}{}{Twoja zdrada zgubi nasz lud.}
{214}{}{Dlaczego to robisz?}
{215}{}{Starsza się myliła. Widzę zło w twoich oczach.}
{300}{}{Ojciec nauczył mnie, jak uczynić ostrze silniejszym. Daj mi kawałek krzemienia, a naostrzę również twoją włócznię. Przyda ci się na Pustkowiach.}
{301}{}{Gdzie mogę znaleźć krzemień?}
{302}{}{Podobno twoja ciotka Morlis ma kawałek. Jest tak wredna, że nie sądzę, aby ktoś ją o to pytał. Oczywiście wiedźma będzie chciała czegoś w zamian.}
{303}{}{Dzięki. Do zobaczenia.}
{304}{}{Udało ci się wyciągnąć krzemień od swojej ciotki?}
{305}{}{Tak, mam tu kawałek.}
{306}{}{Jeszcze nie.}
{307}{}{Powinien się nadać. Daj mi swoją włócznię.}
{308}{}{Trzymaj.}
{309}{}{Nie mam włóczni.}
{310}{}{Robi się to tak...}
{311}{}{Dziecko Przeznaczenia bez włóczni? Cóż, będę musiał dać ci jedną ze swoich. A teraz do dzieła...}
{312}{}{Oto twoja nowa włócznia.}
{313}{}{Dzięki, przyjacielu - ta włócznia bardzo mi się przyda.}
{314}{}{Tak, ale zastanawia mnie twoja włócznia. Wygląda trochę nietypowo.}
{400}{}{Witaj w domu, Dziecko! Udało ci się odnaleźć Kryptę? Masz GECK?}
{401}{}{Moja nie go ma.}
{402}{}{Nie, jeszcze go nie mam.}
{403}{}{Nie jestem w nastroju na twoje pytania. Żegnaj.}
{404}{}{Sprawy nie idą zbyt dobrze, Dziecko. Susza jest coraz gorsza i nasze plony na pewno uschną. Próbujemy ocalić co tylko się da, aby zgromadzić zapasy.}
{405}{}{Dlaczego handel nie z inna wioska?}
{406}{}{Moja robić co może. Szukać GECK. Moja wrócić.}
{407}{}{Dlaczego nie możemy handlować żywnością z innymi wioskami? }
{408}{}{Robię co tylko mogę. Kiedy tylko znajdę GECK wrócę z nim.}
{409}{}{Jesteśmy prostym ludem i nie mamy czym handlować. Te kilka miast, z którymi nawiązaliśmy kontakt, nie wykazało woli pomocy nam.}
{410}{}{Moja rozumieć.}
{411}{}{Rozumiem.}
{412}{}{Jesteś naszą nadzieją, Dziecko Przeznaczenia. Proszę, nie zawiedź nas!}
{413}{}{Dobrze cię widzieć, Dziecko Przeznaczenia. Jak ci się powodzi w twojej wyprawie?}
{414}{}{Moja ciągle szukać.}
{415}{}{Ciągle szukam.}
{416}{}{Nie chcę o tym rozmawiać.}
{417}{}{Musisz się śpieszyć. W wiosce sprawy idą coraz gorzej. Wkrótce zacznie brakować jedzenia. Starsza mówi o racjonowaniu tego, co nam jeszcze zostało. Boję się o przyszłość Arroyo.}
{418}{}{Dziecko! Proszę, powiedz, że twoje zadanie spełnione. Nasza wioska umiera, a z nią - nasz lud. }
{419}{}{Nie, moja ciągle szukać}
{420}{}{Nie, wciąż szukam.}
{421}{}{Jak idą sprawy?}
{422}{}{Przykro mi, Dziecko Przeznaczenia, lecz zaczynam w ciebie wątpić. Nasze życie jest w twoich rękach. Błagam odnajdź Świętą Trzynastkę i powróć do nas z GECKiem!}
{423}{}{Nasze plony obumierają, brahminy zdychają, wszyscy głodują. Płacz dzieci nie pozwala nam spać. Stajemy się zdesperowani.}
{424}{}{Moja ciągle szukać.}
{425}{}{Zrobię wszystko, co w mojej mocy.}
{426}{}{I znowu wracasz do nas, Dziecko. Mam nadzieję, że nie z pustymi rękami?}
{427}{}{Moja przykro, jeszcze nie znaleźć GECK.}
{428}{}{Przykro mi, wciąż nie wiem, gdzie jest GECK.}
{429}{}{Mam tego dość.}
{430}{}{Ludzie umierają, a ty się spokojnie przechadzasz. Może lepiej będzie jak poszukasz gdzieś indziej zamiast ciągle wracać tutaj.}
{500}{}{Czy Starsza rozmawiała już z tobą?}
{1000}{}{Starsza}
{1001}{}{Założyciel}
{1002}{}{Przybysz z Krypty}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Krypta}
{1006}{}{Dziecko Przeznaczenia}
{1007}{}{Szaman}
{1008}{}{Hakunin}
{1009}{}{Proszek Leczniczy}
{1010}{}{Most}
{1011}{}{Mynoc}
{1100}{}{Starsza jest naszą matką i przywódczynią.}
{1101}{}{To nasz wielki przodek, który dał nam wiedzę.}
{1102}{}{Pierwszy, który walczył i zwyciężył chaos.}
{1103}{}{To jest nasza piękna wioska.}
{1104}{}{To miasto handlowe leżące kilka dni na wschód stąd.}
{1105}{}{Krypta jest rajem.}
{1106}{}{Ty jesteś Dzieckiem Przeznaczenia.}
{1107}{}{On leczy nas swoimi ziołami i magią. Mieszka w północnej części naszej wioski.}
{1108}{}{On leczy nas swoimi ziołami i magia. Mieszka w północnej części naszej wioski.}
{1109}{}{To magiczny proszek, który cię uleczy, ale spowoduje senność.}
{1110}{}{Wielki Most stanowi wyjście z naszej wioski od południa.}
{1111}{}{To ja.}
