{100}{}{Widzisz roślinę o mrocznej duszy.}
{101}{}{These plants aren't just harmful to the garden.  They also have the ability to attack humans
 and other creatures.}
{102}{}{Te rośliny o mrocznej duszy to dziwna mutacja. Wątpliwe, by zmutowały z przyczyn naturalnych.}
{103}{}{Nie widzisz nic nadzwyczajnego w tych roślinach - oprócz faktu, że atakują ludzi.}
{150}{}{Rośliny o mrocznej duszy zostały zniszczone.}
