{100}{}{Widzisz roœlinê o mrocznej duszy.}
{101}{}{These plants aren't just harmful to the garden.  They also have the ability to attack humans
 and other creatures.}
{102}{}{Te roœliny o mrocznej duszy to dziwna mutacja. W¹tpliwe, by zmutowa³y z przyczyn naturalnych.}
{103}{}{Nie widzisz nic nadzwyczajnego w tych roœlinach - oprócz faktu, ¿e atakuj¹ ludzi.}
{150}{}{Roœliny o mrocznej duszy zosta³y zniszczone.}
