{100}{}{Widzisz niskiego mężczyznę niosącego pokaźnych rozmiarów księgę.}
{101}{}{Widzisz Jonesa, lekarza.}
{102}{}{Widzisz niewysokiego mężczyznę z książką pod tytułem: "A więc chcesz zostać lekarzem".}
{103}{}{Witam, nazywam się Jones, ale możesz mi mówić "doktorku". Mogę ci w czymś pomóc?}
{104}{}{Mam kuku. Pomoże?}
{105}{}{Moja chora. Pomoże?}
{106}{}{Moja nie ma kawałek, pomoże?}
{107}{}{Ma pytanie. Tak?}
{108}{}{Przepraszać, moja iść.}
{109}{}{Możesz coś poradzić na moje obrażenia?}
{110}{}{Nie czuję się najlepiej. Możesz mi pomóc?}
{111}{}{Okaleczono mnie. Możesz mi pomóc?}
{112}{}{Chcę ci zadać kilka pytań.}
{113}{}{Nie, chcę się tylko przywitać.}
{114}{}{Ależ oczywiście. Zaraz, damy ci zastrzyk z tego - lekko zakłuje - teraz bandaż i po sprawie.}
{115}{}{Moja dzięki. Pa.}
{116}{}{Dzięki, doktorku. Czuję się już dużo lepiej.}
{117}{}{Nie ma sprawy. Wypij to - tylko do dna. Wiem, że jest ohydne. A teraz połóż się na tamtym łóżku. Rano cię obudzę.}
{118}{}{Moja cacy. Pa.}
{119}{}{Dzięki, doktorku. To załatwiło sprawę.}
{120}{}{Przykro mi, ale nie mam odpowiednich warunków do przeprowadzenia operacji. Sugerowałbym udanie się do jakiegoś większego miasta i znalezienie chirurga. Spróbuj na północ stąd, w Kryptopolis.}
{121}{}{Dobra. Żegnaj.}
{122}{}{W porządku. Dzięki.}
{123}{}{Co chcesz wiedzieć?}
{124}{}{Ty pracuje z Darion?}
{125}{}{Ty wyjść, kiedy chcieć?}
{126}{}{Co ty wie o Darion?}
{127}{}{Jak ci tu?}
{128}{}{Darion ma piesek?}
{129}{}{Moja iść już}
{130}{}{Pracujesz dla Dariona?}
{131}{}{Możesz stąd odejść, kiedy zechcesz?}
{132}{}{Co możesz powiedzieć o Darionie?}
{133}{}{Jak się tu znalazłeś?}
{134}{}{Nie mówiłeś czasem, że Darion ma psa?}
{135}{}{Dzięki za informacje. Muszę już iść.}
{136}{}{Cóż... Tak i nie. W każdym bądź razie nie z własnej woli. Jestem tu raczej więźniem. Darion potrzebuje oddanego lekarza, aby się nim opiekował. Chanowie trzymają mnie tylko dlatego. Oczywiście wolałbym pomagać tym biedakom na górze. Nie mają ani odrobiny wiedzy medycznej i mógłbym im bardzo pomóc.}
{137}{}{Dobra. Pytać więcej.}
{138}{}{Dzięki. Na razie.}
{139}{}{To bardzo szlachetne.}
{140}{}{Rozumiem. Lepiej już sobie pójdę.}
{141}{}{To bezdomni! Daj im umrzeć i pogódź się z tym.}
{142}{}{Nie. Jestem tutaj właściwie uwięziony. Nie mogę nawet wyjść, aby uzupełnić zapasy medyczne. Darion posyła po wszystko, czego mi potrzeba.}
{143}{}{Moja rozumie. Już iść.}
{144}{}{Pytać więcej.}
{145}{}{Myślę, że nie jesteś wystarczająco godny zaufania, aby pozwolić ci iść wolno.}
{146}{}{No dobra. Muszę już iść.}
{147}{}{Bardzo mi przykro.}
{148}{}{Darion to świr. To proste i oczywiste. Męczy go więcej lęków, niż jego pies ma pcheł. Z tego, co wiem, był członkiem innego gangu zwanego Chanami. Dla okupu porwali dziewczynę o imieniu Tandi. Jej ojcu się to nie spodobało i wynajął jakiegoś najemnika, aby sprowadził ją z powrotem. Darion był jedynym, który wyszedł z tego z życiem.}
{149}{}{Uch... co ty powiedział.}
{150}{}{Musi już iść.}
{151}{}{Och-ach. Cóż, muszę już iść.}
{152}{}{Jej. Jestem pod wrażeniem twojej wiedzy.}
{153}{}{Ten gość już mi się podoba.}
{154}{}{Zostałem porwany. Podróżowałem z Kryptopolis do Nowego Reno na zasłużone wakacje. Którejś nocy położyłem się spać, a następnego ranka obudziłem się związany i zakneblowany. Mniej więcej tydzień później znalazłem się tutaj. Tkwię tutaj od tamtego czasu.}
{155}{}{Ugh.}
{156}{}{Dzięki. Moja już iść.}
{157}{}{Słabi są często ofiarami silnych.}
{158}{}{Bardzo mi przykro.}
{159}{}{Bardzo ciekawe, ale muszę spadać.}
{160}{}{Tak, ma psa. Osobiście uważam, że jest to najwredniejsza i najpodlejsza istota na świecie. Zdaje się jednak kochać Dariona, więc chyba nie może być aż taki zły.}
{161}{}{Moja pytać więcej.}
{162}{}{Uh, pa.}
{163}{}{Rozumiem. Dzięki za ostrzeżenie.}
{164}{}{Och. Cóż, muszę już iść.}
{165}{}{Nie pomogę komuś takiemu jak ty. Odejdź.}
{166}{}{Dobra, trzymaj się. Wróć jak będziesz czegoś potrzebować.}
{167}{}{Zrobione.}
{168}{}{Teraz stał się paranoikiem. Wierzy, że Tandi chce go dorwać. Opętała go żądza zemsty i chce ją widzieć martwą. Przepełnia go wina, bo ukrył się i przeżył, zamiast zginąć razem z resztą gangu... i można by tak jeszcze długo wyliczać.}
