{100}{}{Widzisz osobê ubrana w mundur wojskowy.}
{101}{}{Widzisz osobê ubrana w mundur wojskowy.}
{102}{}{Widzisz osobê ubrana w mundur wojskowy, która jednak wygl¹da bardziej na technika ni¿ na ¿o³nierza.}

{103}{}{Hej. Jak leci?}
{104}{}{'Rozumiem, mam ciê na ekranie' - przepraszam, ale jestem teraz w trakcie wykonywania czynnoœci.}
{105}{}{Nie mogê teraz rozmawiaæ.}
{106}{}{Mo¿esz rozgl¹daæ siê ile chcesz, ale niczego nie dotykaj.}

{107}{}{Odbi³o ci, ¿e ³azisz tu bez munduru? Ubieraj siê!}
{108}{}{Jeœli sier¿ant z³apie ciê bez munduru, urwie ci g³owê.}
{109}{}{Dlaczego nie masz na sobie munduru? }

{110}{}{Ja pierdolê! Zostaliœmy zaatakowani! Alarm!}
{111}{}{Intruzi! Zawo³aæ stra¿e!}
{112}{}{Stra¿! Intruzi w centrum kontroli lotów!}

{113}{}{Co jest? Zaatakowano nas?}
{114}{}{Sk¹d ten alarm? Co siê dzieje?}
{115}{}{Co siê dzieje, do cholery?}
