{100}{}{Widzisz stra¿nika.}
{101}{}{Widzisz stra¿nika w pancerzu wspomaganym.}
{102}{}{Widzisz kogoœ w nietypowym pancerzu wspomaganym. Na napierœniku ma jakieœ nieznane ci insygnia.}

{103}{}{Nic siê nie dzieje.}
{104}{}{U mnie nic ciekawego, a u ciebie?}
{105}{}{Co robisz z dala od posterunku, ¿o³nierzu? Lepiej siê tutaj nie wa³êsaæ.}

{106}{}{Gdzie masz swój uniform?}
{107}{}{Zg³oœ siê lepiej do sier¿anta i oporz¹dŸ siê trochê.}
{108}{}{NieŸle ryzykujesz w³ócz¹c siê tak bez uniformu. Zg³oœ siê lepiej do zaopatrzenia.}

{109}{}{Kim wy do cholery jesteœcie... Alarm! Intruzi!}
{110}{}{Nieprzyjaciel! Alarm!}
{111}{}{Nieprzyjaciele! W³¹czcie alarm!}

{112}{}{Alarm! Zamykajcie wejœcie do bazy!}
{113}{}{Wszystkie stanowiska w gotowoœci! Alarm bojowy}
{114}{}{Alarm! Intruzi! Czerwony stan gotowoœci!}

{115}{}{Za³atwimy ciê na cacy!}
{116}{}{Enklawa bêdzie rz¹dziæ œwiatem!}
{117}{}{Zginiesz a Enklawa bêdzie trwaæ na wieki!}

{200}{}{...dupek...}
{201}{}{...lepiej, ¿eby ciê tu nie by³o...}
{202}{}{...co za pajac...}
{203}{}{...tak - kurwa - jest!...}
