{100}{}{Widzisz stra¿niczkê.}
{101}{}{Widzisz stra¿nika w pancerzu wspomaganym.}
{102}{}{Widzisz kogoœ w nietypowym pancerzu wspomaganym. Na napierœniku widnieje nieznany ci symbol.}
{103}{}{U mnie wszystko w porz¹dku.}
{104}{}{Nic mi nie jest, a tobie?}
{105}{}{¯o³nierzu, mo¿e lepiej udaj siê na swój posterunek? Niedobrze jest siê tu krêciæ.}
{106}{}{Nie masz muduru.}
{107}{}{Lepiej zg³oœ siê do sier¿anta po wyposa¿enie.}
{108}{}{Chodz¹c bez munduru du¿o ryzykujesz. Lepiej zg³oœ siê do zaopatrzenia.}
{109}{}{Kim wy u licha jesteœcie... Alarm! Intruzi!}
{110}{}{Zostaliœmy zinfiltrowani! Alarm!}
{111}{}{Liczni intruzi! Og³osiæ alarm!}
{112}{}{Alarm! Zamkn¹æ bazê!}
{113}{}{Zabezpieczyæ wszystkie odcinki! Mamy alarm!}
{114}{}{Alarm! Intruzi! Kod czerwony!}
{115}{}{Rozgnieciemy ciê!}
{116}{}{Enklawa bêdzie rz¹dziæ œwiatem!}
{117}{}{Umrzesz, by Enklawa mog³a przetrwaæ!}
{200}{}{...dupek...}
{201}{}{...lepiej st¹d spadaj...}
{202}{}{...co za trep...}
{203}{}{...tak jest, sir!-kurwa-sir!...}
{300}{}{Staæ. Co robisz z tym samolotem? Nie ma zaplanowanych ¿adnych lotów przez nastêpnych kilka dni.}
{301}{}{Hê?}
{302}{}{Zdajê sobie z tego sprawê.}
{303}{}{Przepraszam. Tylko patrzê. Muszê ju¿ iœæ.}
{304}{}{Plany lotów siê zmieni³y. Zabieram ten samolot.}
{310}{}{Co? Oh, rozumiem. S³uchaj, nie dotykaj. Dobra? Dotkniesz jeszcze raz to zginiesz.}
{311}{}{[Uœmiechasz siê i ... atakujesz.]}
{312}{}{(OdejdŸ.)}
{315}{}{O kurwa, wygl¹da na to, ¿e mamy intruza. Kod czerwony! Powtarzam, kod czerwony!}
{316}{}{To brzmi nieŸle. Dotknij tego samolotu jeszcze raz, a zarobisz kulkê w ³eb.}
{320}{}{Racja. I oto jesteœ...}
{321}{}{W³aœnie sobie idê. Przepraszam za k³opot.}
{322}{}{Mam dostarczyæ wa¿n¹ informacje do g³ównej bazy.}
{323}{}{O, naprawdê? I co to za wiadomoœæ.}
{324}{}{Jest super tajna. Nie mogê powiedzieæ.}
{325}{}{Dobra powiem ci, ale jest niezwykle wa¿ne ¿ebyœ nie zdradzi³ tej informacji nikomu innemu, chcê unikn¹æ zbiorowej paniki.
 Widzisz, nie usz³o mojej uwadze, ¿e ostatni transport niewolników by³ zara¿ony nieznan¹ chorob¹, szczep wirusa o du¿ej œmiertelnoœci zara¿onych.
 Ja *muszê* jak najszybciej dostaæ siê do bazy, albo wszyscy zginiemy. A teraz przestañ marnowaæ mój czas, nie mam ani chwili do stracenia.}
{326}{}{Jaaasne, wierzê ci. Wygl¹da, ¿e mamy intruza...}
{327}{}{Cholera! A, wszystko jedno. Nikt mi nigdy nic nie mówi. Dobra. Rób swoje.}
{328}{}{¯e co? To nie brzmi dobrze. Ruszaj, nie chcê byæ za to odpowiedzialny. A i nie martw siê, nikomu nie powiem.}
{329}{}{[dalej]}
