{100}{}{Widzisz strażniczkę.}
{101}{}{Widzisz strażnika w pancerzu wspomaganym.}
{102}{}{Widzisz kogoś w nietypowym pancerzu wspomaganym. Na napierśniku widnieje nieznany ci symbol.}
{103}{}{U mnie wszystko w porządku.}
{104}{}{Nic mi nie jest, a tobie?}
{105}{}{Żołnierzu, może lepiej udaj się na swój posterunek? Niedobrze jest się tu kręcić.}
{106}{}{Nie masz muduru.}
{107}{}{Lepiej zgłoś się do sierżanta po wyposażenie.}
{108}{}{Chodząc bez munduru dużo ryzykujesz. Lepiej zgłoś się do zaopatrzenia.}
{109}{}{Kim wy u licha jesteście... Alarm! Intruzi!}
{110}{}{Zostaliśmy zinfiltrowani! Alarm!}
{111}{}{Liczni intruzi! Ogłosić alarm!}
{112}{}{Alarm! Zamknąć bazę!}
{113}{}{Zabezpieczyć wszystkie odcinki! Mamy alarm!}
{114}{}{Alarm! Intruzi! Kod czerwony!}
{115}{}{Rozgnieciemy cię!}
{116}{}{Enklawa będzie rządzić światem!}
{117}{}{Umrzesz, by Enklawa mogła przetrwać!}
{200}{}{...dupek...}
{201}{}{...lepiej stąd spadaj...}
{202}{}{...co za trep...}
{203}{}{...tak jest, sir!-kurwa-sir!...}
{300}{}{Stać. Co robisz z tym samolotem? Nie ma zaplanowanych żadnych lotów przez następnych kilka dni.}
{301}{}{Hę?}
{302}{}{Zdaję sobie z tego sprawę.}
{303}{}{Przepraszam. Tylko patrzę. Muszę już iść.}
{304}{}{Plany lotów się zmieniły. Zabieram ten samolot.}
{310}{}{Co? Oh, rozumiem. Słuchaj, nie dotykaj. Dobra? Dotkniesz jeszcze raz to zginiesz.}
{311}{}{[Uśmiechasz się i ... atakujesz.]}
{312}{}{(Odejdź.)}
{315}{}{O kurwa, wygląda na to, że mamy intruza. Kod czerwony! Powtarzam, kod czerwony!}
{316}{}{To brzmi nieźle. Dotknij tego samolotu jeszcze raz, a zarobisz kulkę w łeb.}
{320}{}{Racja. I oto jesteś...}
{321}{}{Właśnie sobie idę. Przepraszam za kłopot.}
{322}{}{Mam dostarczyć ważną informacje do głównej bazy.}
{323}{}{O, naprawdę? I co to za wiadomość.}
{324}{}{Jest super tajna. Nie mogę powiedzieć.}
{325}{}{Dobra powiem ci, ale jest niezwykle ważne żebyś nie zdradził tej informacji nikomu innemu, chcę uniknąć zbiorowej paniki.
 Widzisz, nie uszło mojej uwadze, że ostatni transport niewolników był zarażony nieznaną chorobą, szczep wirusa o dużej śmiertelności zarażonych.
 Ja *muszę* jak najszybciej dostać się do bazy, albo wszyscy zginiemy. A teraz przestań marnować mój czas, nie mam ani chwili do stracenia.}
{326}{}{Jaaasne, wierzę ci. Wygląda, że mamy intruza...}
{327}{}{Cholera! A, wszystko jedno. Nikt mi nigdy nic nie mówi. Dobra. Rób swoje.}
{328}{}{Że co? To nie brzmi dobrze. Ruszaj, nie chcę być za to odpowiedzialny. A i nie martw się, nikomu nie powiem.}
{329}{}{[dalej]}
