{100}{}{Widzisz kogoœ w pancerzu wspomaganym. }
{101}{}{Widzisz dowódcê bazy Navarro.}
{102}{}{Widzisz kogoœ w nietypowym pancerzu wspomaganym. Na napierœniku widnieje nieznany ci symbol.}
{103}{}{Kim wy u diab³a jesteœcie... Alarm! Intruzi w bazie!}
{104}{}{Nie mam czasu na pogaduszki z szeregowcami. Odmaszerowaæ.}
{105}{}{Czas na œmieræ.}
{106}{}{W porz¹dku.}
{107}{}{Mówi³am, ¿e nie mam czasu na rozmowê z tob¹. Opuœæ to pomieszczenie i nie wracaj, jeœli po ciebie nie poœlê. Odmaszerowaæ!}
{108}{}{Odmowa wykonania bezpoœredniego rozkazu starszego oficera jest zdrad¹. Nie mam teraz czasu, ¿eby zwo³ywaæ trybuna³, wiêc zajmê siê tym sama. Stra¿! Zabiæ tego kretyna!}
{109}{}{W porz¹dku.}
{110}{}{Pierdol siê!}
{111}{}{KD znajduje siê w tej szafce. Powiedz oficerowi dy¿urnemu, ¿eby skontaktowa³ siê ze mn¹, gdy tylko zostanie zabezpieczona. Odmaszerowaæ!}
{112}{}{Tak jest!}
{113}{}{Poœpiesz siê, ¿o³nierzu, nie mam ca³ego dnia, ¿eby tak tu staæ.}
{114}{}{Tak jest!}
{115}{}{Zostaw moj¹ szafkê w spokoju, albo ukarzê ciê porz¹dn¹ dawk¹ bólu.}
{116}{}{Tak jest!}
{117}{}{W tej bazie og³oszono alarm, a ja ciê nie poznajê. Poka¿ mi swoje papiery, ¿o³nierzu.}
{118}{}{Jakie papiery?}
{119}{}{Mo¿esz mi naskoczyæ!}
{120}{}{Obawiam siê, ¿e nie mam ich przy sobie...}
{121}{}{Papiery? Zaraz ci poka¿e papiery!}
{122}{}{Z³a odpowiedŸ, robaku. Masz obowi¹zek nosiæ swoje papiery przy sobie przez ca³y czas. ¯o³nierz powinien to wiedzieæ.}
{123}{}{IdŸ siê jebaæ.}
{124}{}{Zostaw moj¹ szafkê w spokoju, albo ukarzê ciê porz¹dn¹ dawk¹ bólu.}
{125}{}{Czas na œmieræ.}
