{100}{}{Widzisz kogoś w pancerzu wspomaganym. }
{101}{}{Widzisz dowódcę bazy Navarro.}
{102}{}{Widzisz kogoś w nietypowym pancerzu wspomaganym. Na napierśniku widnieje nieznany ci symbol.}
{103}{}{Kim wy u diabła jesteście... Alarm! Intruzi w bazie!}
{104}{}{Nie mam czasu na pogaduszki z szeregowcami. Odmaszerować.}
{105}{}{Czas na śmierć.}
{106}{}{W porządku.}
{107}{}{Mówiłam, że nie mam czasu na rozmowę z tobą. Opuść to pomieszczenie i nie wracaj, jeśli po ciebie nie poślę. Odmaszerować!}
{108}{}{Odmowa wykonania bezpośredniego rozkazu starszego oficera jest zdradą. Nie mam teraz czasu, żeby zwoływać trybunał, więc zajmę się tym sama. Straż! Zabić tego kretyna!}
{109}{}{W porządku.}
{110}{}{Pierdol się!}
{111}{}{KD znajduje się w tej szafce. Powiedz oficerowi dyżurnemu, żeby skontaktował się ze mną, gdy tylko zostanie zabezpieczona. Odmaszerować!}
{112}{}{Tak jest!}
{113}{}{Pośpiesz się, żołnierzu, nie mam całego dnia, żeby tak tu stać.}
{114}{}{Tak jest!}
{115}{}{Zostaw moją szafkę w spokoju, albo ukarzę cię porządną dawką bólu.}
{116}{}{Tak jest!}
{117}{}{W tej bazie ogłoszono alarm, a ja cię nie poznaję. Pokaż mi swoje papiery, żołnierzu.}
{118}{}{Jakie papiery?}
{119}{}{Możesz mi naskoczyć!}
{120}{}{Obawiam się, że nie mam ich przy sobie...}
{121}{}{Papiery? Zaraz ci pokaże papiery!}
{122}{}{Zła odpowiedź, robaku. Masz obowiązek nosić swoje papiery przy sobie przez cały czas. Żołnierz powinien to wiedzieć.}
{123}{}{Idź się jebać.}
{124}{}{Zostaw moją szafkę w spokoju, albo ukarzę cię porządną dawką bólu.}
{125}{}{Czas na śmierć.}
