{100}{}{Widzisz chudego mężczyznę o niemiłej powierzchowności.}
{150}{}{Widzisz Flicka. Zapamiętale drapie swoje klejnoty rodowe.}
{151}{}{Widzisz niezbyt domytego mężczyznę o nieprzyjemnej twarzy.}
{200}{}{Uciekaj stąd, głupolu.}
{201}{}{Hej przygłupie! Tak, do ciebie mówię! Smykaj stąd, sio!}
{202}{}{Niesły s ciebie głupol, co?}
{203}{}{Szczym masz problem, hę?!}
{204}{}{Uciekaj stąd, sio!}
{220}{}{Heja, jestem Flick. Czego tu do cholery szukasz?}
{221}{}{I co teras? Marnujesz mój czas.}
{222}{}{O co chodzi z tym akcentem, Flick?}
{223}{}{Co ty tu do cholery robisz?}
{224}{}{Szukam Krypty - no i kupca imieniem Vic. Wiesz gdzie go można znaleźć?}
{225}{}{Chcę z tobą pohandlować.}
{240}{}{To jak, chcesz jeszcze coś?}
{241}{}{Jeśli można, chętnie jeszcze raz rzucę okiem na twoją ofertę.}
{242}{}{W zasadzie chcę cię tylko o coś zapytać.}
{243}{}{To już wszystko. Do zobaczenia Flick.}
{260}{}{Ja tu kurna handluję, a co myślisz? Jestem jak taki Samurajtanin, nie?}
{261}{}{Że co?}
{262}{}{No tak... mogę cię zapytać o coś jeszcze?}
{263}{}{A, tak. W porządku. Żegnaj, Flick.}
{280}{}{Dbam o te małe urwipołcie.}
{281}{}{Handlujesz mięsem, tak?}
{290}{}{Urwipołcie! No, kumasz, dzieci. Moje dzieci!}
{291}{}{Twoje dzieci?}
{292}{}{Cóż, nie interesuje mnie zbytnio dokarmianie dzieci. Chcę cię zapytać o coś innego.}
{300}{}{No tak! Dzieci, które dla mnie pracują. Pszynoszą mi szeczy. Różne takie pierduły. No wiesz!}
{301}{}{Ee, nie.}
{302}{}{W porządku. Chcę cię jeszcze o coś zapytać.}
{303}{}{Ach, rozumiem. No to nie będę ci przeszkadzać. Żegnaj.}
{315}{}{They bring me stuff what they find. Little, little things. Stuff no one ain't usin' no more. In return, I takes care of 'em.}
{316}{}{To chyba niezły układ.}
{325}{}{[Flick wzrusza ramionami] Jakoś sobie wspólnie radzimy.}
{326}{}{To może zapytam cię o coś innego?}
{327}{}{Na pewno przynoszą ci różne ciekawe rzeczy. Zobaczmy co tam masz.}
{328}{}{Tylko pytam. Cóż, żegnaj Flick.}
{340}{}{O czym ty gadasz?! Co ja ci wyglądam, jak pirla? Jakiś głupi filio di puttana? Masz mnie sa błasna? Myślisz, sze jestem sajebiście sabawny, tak?}
{341}{}{Ależ skąd. Przepraszam, pytam tylko z ciekawości. Mogę cię zapytać o coś innego?}
{342}{}{Właśnie tak. A nic nie rozbawi mnie bardziej, niż twoje wyprute na ziemię bebechy.}
{343}{}{Cholera, jeśli zamierzasz się złościć o byle co, to ja wychodzę.}
{360}{}{Krypta, co? Może Mamuśka coś o tym wie, bo ja nie mam pojęcia. Ale ten cały Vic - jego snam. Metsger dorwał tego porca pistola.}
{361}{}{Vic? A to nie jest ten gość s tobą? Biota. Ale Mamuśka... ją znam.}
{362}{}{Kim jest Metzger?}
{363}{}{Kim jest Mamuśka?}
{364}{}{Dziękuję. Pozwól, że zapytam o coś innego.}
{365}{}{Dzięki, to już chyba wszystko. Do widzenia.}
{380}{}{Mamuśka prowadzi restaurację we wschodniej części miasta. Saras sa Cmentarzem. Fajne miejsce, dobre spaghetti, Mama mia.}
{381}{}{Dzięki, a co z tym Metsgerem, który przetrzymuje Vica?}
{382}{}{Dziękuję. Pozwól, że zapytam o coś innego.}
{383}{}{Dzięki, to już chyba wszystko. Do widzenia.}
{400}{}{A, tak! Metsger, ten stronzo, już nie żyje. Nie wiem co się stało z Vicem.}
{401}{}{Ten Metsger, to prawdziwy rompiballe. Prowadzi gildię łowców niewolników. To na wschodzie, saras na północ od Mamuśki. To on uwięził Vica.}
{402}{}{Dzięki, a co z Mamuśką?}
{403}{}{Dziękuję. Pozwól, że zapytam o coś innego.}
{404}{}{Dzięki, to już chyba wszystko. Do widzenia.}
