# 0. Look
{100}{}{Widzisz chudego mê¿czyznê o niemi³ej powierzchownoœci.}

{150}{}{Widzisz Flicka. Zapamiêtale drapie swoje klejnoty rodowe.}
{151}{}{Widzisz niezbyt domytego mê¿czyznê o nieprzyjemnej twarzy.}

# 1. Low Intelligence (WtG)
{200}{}{Uciekaj st¹d, g³upolu.}
{201}{}{Hej przyg³upie! Tak, do ciebie mówiê! Smykaj st¹d, sio!}
{202}{}{Nies³y s ciebie g³upol, co?}
{203}{}{Szczym masz problem, hê?!}
{204}{}{Uciekaj st¹d, sio!}

# 2. Hello (WtG, 3,4,6,7,911,12,13)
{220}{}{Heja, jestem Flick. Czego tu do cholery szukasz?}
{221}{}{I co teras? Marnujesz mój czas.}
{222}{}{O co chodzi z tym akcentem, Flick?}
{223}{}{Co ty tu do cholery robisz?}
{224}{}{Szukam Krypty - no i kupca imieniem Vic. Wiesz gdzie go mo¿na znaleŸæ?}
{225}{}{Chcê coœ kupiæ.}

# 3. After Barter (2,3,9)
{240}{}{To jak, chcesz jeszcze coœ?}
{241}{}{Jeœli mo¿na, chêtnie jeszcze raz rzucê okiem na twoj¹ ofertê.}
{242}{}{W zasadzie chcê ciê tylko o coœ zapytaæ.}
{243}{}{To ju¿ chyba wszystko. Trzymaj siê Flick.}

# 4. What do you do here (2)
{260}{}{Ja tu kurna handlujê, a co myœlisz? Jestem jak taki Samurajtanin, nie?}
{261}{}{¯e co?}
{262}{}{No tak... mogê ciê zapytaæ o coœ jeszcze?}
{263}{}{A, tak. W porz¹dku. ¯egnaj, Flick.}

# 5. You do what? (4)
{280}{}{Dbam o te ma³e urwipo³cie.}
{281}{}{Handlujesz miêsem, tak?}

# 6. Pianos?(5)
{290}{}{Urwipo³cie! No, kumasz, dzieci. Moje dzieci!}
{291}{}{Twoje dzieci?}
{292}{}{Có¿, nie interesuje mnie zbytnio dokarmianie dzieci. Chcê ciê zapytaæ o coœ innego.}

# 7. Your kids? (6)
{300}{}{No tak! Dzieci, które dla mnie pracuj¹. Pszynosz¹ mi szeczy. Ró¿ne takie pierdu³y. No wiesz!}
{301}{}{Nie, nie wiem.}
{302}{}{W porz¹dku. Chcê ciê jeszcze o coœ zapytaæ.}
{303}{}{Ach, rozumiem. No to nie bêdê ci przeszkadzaæ. ¯egnaj.}

# 8. They bring you things? (7)
{315}{}{Pszynosz¹ mi wszystkie swoje snalesiska. Takie tam malutkie pierdu³ki. Takie, co to ich nikt inny nie potszebuje. A ja siê nimi w samian opiekujê.}
{316}{}{To chyba niez³y uk³ad.}

# 9. Nice arrangement (8)
{325}{}{(Flick wzrusza ramionami) Jakoœ sobie wspólnie radzimy.}
{326}{}{To mo¿e zapytam ciê o coœ innego?}
{327}{}{Na pewno przynosz¹ ci ró¿ne ciekawe rzeczy. Zobaczmy co tam masz.}
{328}{}{Tylko pytam. Có¿, ¿egnaj Flick.}

# 10. Wacky accent? (2)
{340}{}{O czym ty gadasz?! Co ja ci wygl¹dam, jak pirla? Jakiœ g³upi filio di puttana? Masz mnie sa b³asna? Myœlisz, sze jestem sajebiœcie sabawny, tak?}
{341}{}{Ale¿ sk¹d. Przepraszam, pytam tylko z ciekawoœci. Mogê ciê zapytaæ o coœ innego?}
{342}{}{W³aœnie tak. A nic nie rozbawi mnie bardziej, ni¿ twoje wyprute na ziemiê bebechy.}
{343}{}{Cholera, jeœli zamierzasz siê z³oœciæ o byle co, to ja wychodzê.}

# 11. Vic & Vault (2)
{360}{}{Krypta, co? Mo¿e Mamuœka coœ o tym wie, bo ja nie mam pojêcia. Ale ten ca³y Vic - jego snam. Metsger dorwa³ tego porca pistola.}
{361}{}{Vic? A to nie jest ten goœæ s tob¹? Biota. Ale Mamuœka... j¹ znam.}
{362}{}{Kim jest Metsger?}
{363}{}{Kim jest Mamuœka?}
{364}{}{Dziêki. Mam jeszcze kilka pytañ.}
{365}{}{Dziêki, to ju¿ chyba wszystko. Do widzenia.}

# 12. Who's Momma? (11,13)
{380}{}{Mamuœka prowadzi restauracjê we wschodniej czêœci miasta. Saras sa Cmentarzem. Fajne miejsce, dobre spaghetti, Mama mia.}
{381}{}{Dziêki, a co z tym Metsgerem, który przetrzymuje Vica?}
{382}{}{Dziêki. Mam jeszcze jedno pytanie.}
{383}{}{Dziêki, to ju¿ chyba wszystko. Do zobaczenia.}

# 13. Who's Metzger? (11,12)
{400}{}{A, tak! Metsger, ten stronzo, ju¿ nie ¿yje. Nie wiem co siê sta³o z Vicem.}
{401}{}{Ten Metsger, to prawdziwy rompiballe. Prowadzi gildiê ³owców niewolników. To na wschodzie, saras na pó³noc od Mamuœki. To on uwiêzi³ Vica.}
{402}{}{Dziêki, a co z Mamuœk¹?}
{403}{}{Dziêki. Mam jeszcze jedno pytanie.}
{404}{}{Dziêki, to ju¿ chyba wszystko. Do widzenia.}
