{100}{}{Widzisz chudego mê¿czyznê o niemi³ej powierzchownoœci.}
{150}{}{Widzisz Flicka. Zapamiêtale drapie swoje klejnoty rodowe.}
{151}{}{Widzisz niezbyt domytego mê¿czyznê o nieprzyjemnej twarzy.}
{200}{}{Uciekaj st¹d, g³upolu.}
{201}{}{Hej przyg³upie! Tak, do ciebie mówiê! Smykaj st¹d, sio!}
{202}{}{Nies³y s ciebie g³upol, co?}
{203}{}{Szczym masz problem, hê?!}
{204}{}{Uciekaj st¹d, sio!}
{220}{}{Heja, jestem Flick. Czego tu do cholery szukasz?}
{221}{}{I co teras? Marnujesz mój czas.}
{222}{}{O co chodzi z tym akcentem, Flick?}
{223}{}{Co ty tu do cholery robisz?}
{224}{}{Szukam Krypty - no i kupca imieniem Vic. Wiesz gdzie go mo¿na znaleŸæ?}
{225}{}{Chcê z tob¹ pohandlowaæ.}
{240}{}{To jak, chcesz jeszcze coœ?}
{241}{}{Jeœli mo¿na, chêtnie jeszcze raz rzucê okiem na twoj¹ ofertê.}
{242}{}{W zasadzie chcê ciê tylko o coœ zapytaæ.}
{243}{}{To ju¿ wszystko. Do zobaczenia Flick.}
{260}{}{Ja tu kurna handlujê, a co myœlisz? Jestem jak taki Samurajtanin, nie?}
{261}{}{¯e co?}
{262}{}{No tak... mogê ciê zapytaæ o coœ jeszcze?}
{263}{}{A, tak. W porz¹dku. ¯egnaj, Flick.}
{280}{}{Dbam o te ma³e urwipo³cie.}
{281}{}{Handlujesz miêsem, tak?}
{290}{}{Urwipo³cie! No, kumasz, dzieci. Moje dzieci!}
{291}{}{Twoje dzieci?}
{292}{}{Có¿, nie interesuje mnie zbytnio dokarmianie dzieci. Chcê ciê zapytaæ o coœ innego.}
{300}{}{No tak! Dzieci, które dla mnie pracuj¹. Pszynosz¹ mi szeczy. Ró¿ne takie pierdu³y. No wiesz!}
{301}{}{Ee, nie.}
{302}{}{W porz¹dku. Chcê ciê jeszcze o coœ zapytaæ.}
{303}{}{Ach, rozumiem. No to nie bêdê ci przeszkadzaæ. ¯egnaj.}
{315}{}{They bring me stuff what they find. Little, little things. Stuff no one ain't usin' no more. In return, I takes care of 'em.}
{316}{}{To chyba niez³y uk³ad.}
{325}{}{[Flick wzrusza ramionami] Jakoœ sobie wspólnie radzimy.}
{326}{}{To mo¿e zapytam ciê o coœ innego?}
{327}{}{Na pewno przynosz¹ ci ró¿ne ciekawe rzeczy. Zobaczmy co tam masz.}
{328}{}{Tylko pytam. Có¿, ¿egnaj Flick.}
{340}{}{O czym ty gadasz?! Co ja ci wygl¹dam, jak pirla? Jakiœ g³upi filio di puttana? Masz mnie sa b³asna? Myœlisz, sze jestem sajebiœcie sabawny, tak?}
{341}{}{Ale¿ sk¹d. Przepraszam, pytam tylko z ciekawoœci. Mogê ciê zapytaæ o coœ innego?}
{342}{}{W³aœnie tak. A nic nie rozbawi mnie bardziej, ni¿ twoje wyprute na ziemiê bebechy.}
{343}{}{Cholera, jeœli zamierzasz siê z³oœciæ o byle co, to ja wychodzê.}
{360}{}{Krypta, co? Mo¿e Mamuœka coœ o tym wie, bo ja nie mam pojêcia. Ale ten ca³y Vic - jego snam. Metsger dorwa³ tego porca pistola.}
{361}{}{Vic? A to nie jest ten goœæ s tob¹? Biota. Ale Mamuœka... j¹ znam.}
{362}{}{Kim jest Metzger?}
{363}{}{Kim jest Mamuœka?}
{364}{}{Dziêkujê. Pozwól, ¿e zapytam o coœ innego.}
{365}{}{Dziêki, to ju¿ chyba wszystko. Do widzenia.}
{380}{}{Mamuœka prowadzi restauracjê we wschodniej czêœci miasta. Saras sa Cmentarzem. Fajne miejsce, dobre spaghetti, Mama mia.}
{381}{}{Dziêki, a co z tym Metsgerem, który przetrzymuje Vica?}
{382}{}{Dziêkujê. Pozwól, ¿e zapytam o coœ innego.}
{383}{}{Dziêki, to ju¿ chyba wszystko. Do widzenia.}
{400}{}{A, tak! Metsger, ten stronzo, ju¿ nie ¿yje. Nie wiem co siê sta³o z Vicem.}
{401}{}{Ten Metsger, to prawdziwy rompiballe. Prowadzi gildiê ³owców niewolników. To na wschodzie, saras na pó³noc od Mamuœki. To on uwiêzi³ Vica.}
{402}{}{Dziêki, a co z Mamuœk¹?}
{403}{}{Dziêkujê. Pozwól, ¿e zapytam o coœ innego.}
{404}{}{Dziêki, to ju¿ chyba wszystko. Do widzenia.}
