# 0. Look
{100}{}{Widzisz sympatyczn¹, starsz¹ kobietê.}

{150}{}{Widzisz Mamuœkê, jak zwykle zajêt¹ gotowaniem i sprz¹taniem.}
{151}{}{Widzisz krzepk¹, starsz¹ kobietê. Uœmiecha siê weso³o.}

# 1. Low Intelligence (WtG)
{200}{}{Witaj, mówi¹ na mnie Mamuœka. Chyba nigdy ciê tu nie widzia³em.}
{201}{}{Witaj ponownie. Co Mamuœka mo¿e dla ciebie zrobiæ?}
{202}{}{Ja .}
{203}{}{Mmmm. Uuk? Pa pa Mamuœka.}

# 2. Low IQ more (1)
{220}{}{Jak tak dalej pójdzie, puœcisz mnie z torbami. Mo¿e pokrêcisz siê trochê gdzie indziej? Starczy ci jedzenia na dziœ.}
{221}{}{Có¿.}
{222}{}{ wygl¹dasz na zb³¹kan¹ owieczkê. Nie mogê patrzeæ jak ktoœ cierpi. Chcesz coœ do jedzenia?}
{223}{}{Moja pe³na. Mamuœki jedzenie mniam. Pa Mamuœka.}
{224}{}{Moja p³aciæ?}
{225}{}{Moja iœæ. Pa Mamuœka.}

# 3. Pay? (2)
{240}{}{Jeœli chcesz. Ile masz? (Mamuœka wyci¹ga rêkê po pieni¹dze)}
{241}{}{Mamuœka? (Wyci¹gasz swoje pieni¹dze)}
{242}{}{Nie! Ja iœæ. Pa Mamuœka.}

# 4. No, not really (7,9)
{250}{}{Nie, przykro mi. Mamy tylko szczurzy placek, kanapkê ze szczura i spaghetti.}
{251}{}{Na co masz ochotê?}
{252}{}{Najchêtniej na coœ bez szczurzego miêsa.}
{253}{}{Mo¿e kanapkê ze szczura.}
{254}{}{Mo¿e szczurzy placek.}

# 5. Not so much rat in it (4)
{270}{}{To mo¿e spaghetti? Nie ma w nim ZBYT wiele szczurzego miêsa... tylko sos.}
{271}{}{Niech bêdzie, zjem spaghetti ze szczurzym sosem.}

# 6. Here's your food (4,5)
{280}{}{Zaraz ci przyniosê du¿¹ porcjê. To bêdzie $10.}
{281}{}{Chwilowo nie mam doœæ pieniêdzy. Mam natomiast kilka pytañ.}

{282}{}{$10 za szczura? ¯artujesz?! W mojej wiosce za t³ustego szczura trzeba zap³aciæ du¿o wiêcej. To dopiero okazja!}
{283}{}{Niech bêdzie. Proszê, oto pieni¹dze.}
{284}{}{Mo¿e jednak zmieniê zdanie. Mam kilka pytañ.}
{285}{}{Mo¿e zajrzê tu innym razem. Do widzenia.}

# 7. Thanks Mom (6,20)
{300}{}{Masz niez³y apetyt. Lubiê ludzi, którzy potrafi¹ dobrze zjeœæ. Masz dosyæ?}
{301}{}{Nie ma szans! Proszê o dok³adkê.}
{302}{}{Zdecydowanie. Mogê ciê o coœ zapytaæ?}
{303}{}{Na razie wystarczy. Do widzenia.}

# 8. What's there to do here? (13)
{320}{}{Có¿, przyda³by mi siê ktoœ, kto dostarczy posi³ek Smittiemu. Jest na zachód st¹d, na z³omowisku. Zrobisz to dla mnie? Dostaniesz w zamian darmowy posi³ek.}
{321}{}{Jasne, nie ma sprawy.}
{322}{}{Zastanowiê siê. W miêdzyczasie chcê ciê o coœ zapytaæ.}
{323}{}{Przykro mi, ale nie mogê. Do zobaczenia.}

# 9. Random Food item list (13)
{340}{}{Masz szczêœcie. Mamy zupê z radskorpiona.}
{341}{}{Mamy potrawkê z radskorpiona.}
{342}{}{Serwujemy dziœ odw³ok radskorpiona w œmietanie.}
{343}{}{Mamy tylko zupê fasolow¹.}
{344}{}{Œwie¿a pieczeñ z bramina!}
{345}{}{Œwie¿uteñka pieczeñ z gekona.}
{346}{}{Stek-niespodzianka.}
{347}{}{Kruchuteñki kretoszczur.}
{348}{}{Zupa z robali.}
{349}{}{Kotlet z psa.}
{350}{}{Udka gekona w galarecie.}
{351}{}{Mus z modliszki.}
{352}{}{Pieczeñ z kretoszczura.}
{353}{}{Bramin w buraczkach.}
{354}{}{Radskorpion w sosie w³asnym.}
{356}{}{Nie wiem co to jest, ale smakuje zupe³nie jak kurczak.}
{357}{}{Zrazy z psa.}
{358}{}{Danie-niespodzianka.}
{359}{}{Kotlet-niespodzianka!}
{360}{}{Serio?}

# 10. Low IQ hand food (3)
{375}{}{Proszê. Dawno nie widzia³am kogoœ tak wyg³odzonego. (Mamuœka podaje ci talerz z cudownie pachn¹cym miêsem)}
{376}{}{Dzienk, Mamuœka.}


# 11. Low IQ fed (10)
{385}{}{Mam nadziejê, ¿e smakowa³o?}
{386}{}{Mmm, mniam mniam. Pa, Mamuœka.}

# 12. Sure I'll deliver it (8)
{395}{}{Wielkie dziêki. Pobieg³abym sama, ale kto by wtedy przypilnowa³ interesu? Oto jedzenie dla Smittiego. Gdyby nie ja, ten g³uptas pewnie w ogóle zapomnia³by o posi³kach.}
{396}{}{Chêtnie dostarczê mu jedzenie.}

# 13. Hello (WtG, 6,7,8,15,18)
{405}{}{Bardzo siê na tobie zawiod³am. Biedny Smitty musia³ sam przyjœæ tutaj po jedzenie. Czego ode mnie chcesz?}
{406}{}{Witaj, mówi¹ na mnie Mamuœka, jestem w³aœcicielk¹ tego lokalu. Znajdziesz tu najlepsze jedzenie na pó³noc od Nowego Reno.}
{407}{}{O co chcesz zapytaæ Mamuœkê?}
{408}{}{Nie jesteœ moj¹ mam¹.}
{409}{}{S³ysza³aœ mo¿e o Kryptach, albo o niejakim Vicu?}
{410}{}{Co s³ychaæ w mieœcie?}
{411}{}{Co tu mo¿na zjeœæ?}

# 14. I'm not your mom (13)
{425}{}{Wiem o tym. Po prostu wszyscy mnie tak nazywaj¹. Ja nawet traktujê moich goœci, jakbyœmy byli spokrewnieni - oczywiœcie tak d³ugo, jak przestrzegaj¹ moich zasad.}
{426}{}{Zasad?}

# 15. Rules? (14)
{435}{}{Tak, zasad. ¯adnych kradzie¿y, przeklinania i bójek - tylko tego wymagam. Kto nie potrafi siê podporz¹dkowaæ mo¿e tu nie zagl¹daæ. W moim lokalu ma byæ cisza i spokój!}
{436}{}{Rozumiem. Mam jeszcze jedno pytanie.}
{437}{}{Naturalnie. Do zobaczenia.}

# 16. Vic or Vault? (13)
{445}{}{Niech pomyœlê... gdzieœ daleko na wschód i trochê na pó³noc jest Kryptopolis. A Vic? Hmm... zaraz, zaraz.}
{446}{}{Mo¿e wiesz, gdzie znajdê Vica. Jest kupcem.}
{447}{}{Dziêkujê, to chwilowo wszystko, co mnie interesuje. Do zobaczenia.}

# 17. Trader Vic (16)
{455}{}{Kupiec Vic? No, teraz sobie przypomnia³am! Tak, zdaje siê, ¿e jest wiêŸniem Metzgera. Nie wiem dlaczego zosta³ uwiêziony.}
{456}{}{Kim jest ten Metzger i gdzie go mogê znaleŸæ?}
{457}{}{Œwietnie. Dziêkujê!}

# 18. Who's Metzger (17)
{465}{}{Metzger to przywódca tutejszej gildii ³owców niewolników. Przetrzymuje u siebie najró¿niejszych biedaków. Znajdziesz go na tej samej ulicy, trochê na pó³noc st¹d.}
{466}{}{Metzger by³ kiedyœ przywódc¹ tutejszej gildii ³owców niewolników. Przetrzymywa³ u siebie najró¿niejszych biedaków. Ale teraz ludzie mówi¹, ¿e nie ¿yje.}
{467}{}{Dziêkujê za informacje. Mam jeszcze jedno pytanie.}
{468}{}{Muszê za³atwiæ pewne sprawy. Dziêkujê za pomoc.}


# 19. Smitty's meal in progress (WtG)
{475}{}{No ju¿, zanieœ jedzenie Smittiemu.}
{476}{}{Nie pomogê ci, dopóki nie wywi¹¿esz siê z obietnicy.}
{477}{}{Na co czekasz? Pospiesz siê, proszê.}
{478}{}{No ju¿, szybciutko. Zanieœ Smittiemu jedzenie.}
{479}{}{Przestañ siê obijaæ i zanieœ Smittiemu jedzenie.}

# 20. Reward (WtG)
{485}{}{Dobra robota. Na pewno zaostrzy³ ci siê apetyt. Mam dla ciebie nie lada niespodziankê: Talerz najlepszych frykasów jakie mo¿na tu dostaæ, specjalnie dla ciebie.}
{486}{}{Brzmi wspaniale! Chcê jeœæ!}
{487}{}{Ojej, apetyt jakoœ mi nie dopisuje. Mo¿e innym razem. Dziêkujê. Do zobaczenia.}

# 21. What do you know about that haunted house? (13)
{500}{}{Hmm, niezbyt wiele. Pewnie ktoœ siê po prostu wyg³upia.}
{501}{}{Czy zawsze by³ nawiedzony?}
{502}{}{Czy ktoœ w nim dalej mieszka?}
{503}{}{Zapewne masz racjê, ¿egnaj.}

# 22. Started 2 years back... (21)
{520}{}{To siê zaczê³o jakieœ dwa lata temu. Ludzie mówi¹ o jakichœ jêkach i duchach. Osobiœcie uwa¿am, ¿e to brednie.}
{521}{}{Dwa lata? A od tego czasu ktoœ tam mieszka³?}
{522}{}{Pewnie masz racjê. Dziêkujê.}

# 23. Anyone used it then? (21-22)
{540}{}{Któryœ z ch³opców kiedyœ tam nocowa³. Mo¿e on coœ wie.}
{541}{}{Który?}
{542}{}{Nie wydaje mi siê. ¯egnaj.}

# 24. Who? (23)
{560}{}{Przychodzi³ kiedyœ do mnie i próbowa³ sprzedawaæ ró¿ne drobiazgi. G³ównie bi¿uteriê. Pamiêtam, ¿e jeden z³oty medalion zachowa³ dla siebie.}
{561}{}{Pamiêtasz jak siê nazywa³?}
{562}{}{Medalion? Dziwne. Kto to by³?}
{563}{}{Mam jeszcze jedno pytanie.}
{564}{}{Dziêkujê. Do zobaczenia.}

# 25. Name? (24)
{580}{}{Nie jestem pewna. Joseph... Joel... coœ w tym stylu. Ma teraz jakieœ 19 lat. Obawiam siê, ¿e w³óczy siê z miejscowymi bandziorami.}
{581}{}{Dziêki. Mam jeszcze jedno pytanie.}
{582}{}{Dziêkujê.}

# 13b. PC Responce line added to node 13
{600}{}{Co mo¿esz mi powiedzieæ o nawiedzonym domu?}
