{100}{}{You see a chem reliant.}
{101}{}{To Petey.}
{150}{}{This here is a poor chem reliant.}
{151}{}{Petey wygl¹da na kogoœ, kto potrzebuje profesjonalnej opieki.}
{152}{}{[Rozmawiaj.]}
{155}{}{[Kaszle.] Masz jakieœ drobniaki?}
{156}{}{Jasne, proszê bardzo.}
{157}{}{Nie, spadaj.}
{158}{}{Pitek?}
{159}{}{Widzê, ¿e tobie te¿ siê nie powodzi. [Kaszle.] Mimo to, dziêki.}
{160}{}{Przykro mi. ¯egnaj.}
{161}{}{Proszê bardzo.}
{162}{}{Mo¿e innym razem. Mimo to, dziêki. [Kaszle.]}
{163}{}{[Koniec]}
{164}{}{Piêkne dziêki. [Kaszle.] Wieeelkie dziêki.}
{165}{}{Nie ma za co.}
{166}{}{Tak, tak.}
{167}{}{Proszê pana, [Kaszle.] zechce pan wspomóc schorowanego cz³owieka w potrzebie?}
{168}{}{Masz tu $5.}
{169}{}{Nie dzisiaj.}
{170}{}{Poszukaj sobie lepiej jakiejœ uczciwej pracy.}
{171}{}{Proszê pani, mo¿e wesprze pani [Kaszle.] biednego, g³odnego cz³owieka, który nie mo¿e pracowaæ [Kaszle.] ze wzglêdu na s³abe zdrowie.}
{172}{}{Biedaku, masz tu $5.}
{173}{}{Nigdy nie dajê ja³mu¿ny ¿ebrakom.}
{174}{}{Nie.}
{200}{}{Hej, rzucisz parê groszy?}
{201}{}{Mo¿e zechce pan rzuciæ parê groszy?}
{202}{}{Hej, znajdziesz parê groszy dla biednego cz³owieka?}
{203}{}{Do you think you can help me out with a coupla dollars?}
{204}{}{Po¿yczysz mi parê dolców?}
{205}{}{Mo¿e zechce pani rzuciæ mi parê groszy?}
{206}{}{Hej, proszê pani! Grosik dla biednego cz³owieka?}
{220}{}{Niech mi pan pomo¿e.}
{221}{}{Aaach, jak strasznie boli.}
{222}{}{Potrzebujê pomocy. Bardzo boli.}
{223}{}{Mo¿e mi pani pomo¿e?}
{225}{}{Bêdê dozgonnie wdziêczny.}
{226}{}{Hej, co ty wyprawiasz?}
{230}{}{Jakie to przyjemne.}
{231}{}{Yyyy...}
{232}{}{[Chichocze]}
{233}{}{Hej...}
{300}{}{Ahhh, someone fucking killed Tubby?}
{301}{}{Co siê sta³o Tubby'emu?}
{302}{}{Oh shit, Tubby's...}
{303}{}{Aaach...}
{304}{}{I tak go nie lubi³em.}
{305}{}{Flick's dead? Crap.}
{306}{}{Co siê sta³o Flickowi?}
{307}{}{Flick...}
{310}{}{Hey Tubby, I, Uhhh, need some help here.}
{311}{}{HEJ TUBBY!}
{312}{}{Czeœæ.}
{313}{}{HEJ!}
{314}{}{Hey Flick, I, Uhhh, need some help here.}
{315}{}{HEJ FLICK!}
{320}{}{Hej Tubby, mo¿emy pogadaæ? Mam kasê.}
{321}{}{Ummm, Tubby, mam trochê pieniêdzy.}
{322}{}{Yyyy...}
{323}{}{Jestem na g³odzie.}
{324}{}{Hej, Flick, mo¿emy pogadaæ? Mam kasê.}
{325}{}{Ummm, Flick, mam trochê pieniêdzy.}
{330}{}{Uuuch... Wielkie dziêki, Tubby.}
{331}{}{Dobry z ciebie kumpel, Tubby.}
{332}{}{Obiecujê - od jutra odstawiam ten szajs.}
{333}{}{Dobry z ciebie kumpel.}
{334}{}{Uuuch... Wielkie dziêki, Flick.}
{335}{}{Prawdziwy z ciebie kumpel, Flick.}
