{100}{}{Widzisz Rybaka.}
{101}{}{Przybywasz w sam¹ porê, aby byæ œwiadkiem b³ogos³awieñstwa Bogini Morza.}
{102}{}{[More]}
{103}{}{}
{104}{}{Tu¿ przed wielkim sztormem rzucamy w³óczniami w morze, ¿eby okazaæ nasze mêstwo wobec ¿ywio³u. Jeœli oka¿emy siê godni, Bogini nagrodzi nas owocami.}
{105}{}{When the season of storms begins, we throw Broc flowers out on the sea with the tide.  After
 the Goddess works her magic, she returns the Broc flowers as the rare Xander root. }
{106}{}{We offer tribute to the Goddess of the Sea each year in the form of Xander root.  If the
 Goddess deems us worthy, she will turn the Xander root into Broc flowers. }
{107}{}{Po obfitych zbiorach wznosimy do Bogini Morza modlitwê dziêkczynn¹, z proœb¹, aby mia³a nas w swojej opiece, a ona co roku nagradza nasze oddanie przysy³aj¹c nam w³ócznie jako znak, ¿e nad nami czuwa.}
{108}{}{Mogê zobaczyæ, co zes³a³a wam Bogini Morza?}
{109}{}{Ug}
{110}{}{Oto przedmioty, które otrzymaliœmy od Bogini w tym roku. Chêtnie podzielimy siê nimi z tob¹ za odpowiedni¹ cenê.}
{111}{}{Z³om [10$]}
{112}{}{Pistolet laserowy [10000$]}
{113}{}{Zaostrzone kije [40$]}
{114}{}{Owoc [5$]}
{115}{}{Korzeñ Xandrowy [20$]}
{116}{}{Kwiat Broca [10$]}
{117}{}{Bywaj.}
{118}{}{[Wyci¹ga rêkê w kierunku morza] IdŸ przed siebie. Bogini ¿yczy sobie spotkaæ siê z tob¹ osobiœcie.}
{119}{}{[Koniec]}
{120}{}{Niech b³ogos³awiona Bogini Morza czuwa nad twoimi œcie¿kami.}
{121}{}{[Koniec]}
{122}{}{[He frowns as you fail to produce the required sum of money.]  Perhaps another time, then.}
{123}{}{[Koniec]}
