{100}{}{Widzisz Rybaka.}
{101}{}{Przybywasz w samą porę, aby być świadkiem błogosławieństwa Bogini Morza.}
{102}{}{[More]}
{103}{}{}
{104}{}{Tuż przed wielkim sztormem rzucamy włóczniami w morze, żeby okazać nasze męstwo wobec żywiołu. Jeśli okażemy się godni, Bogini nagrodzi nas owocami.}
{105}{}{When the season of storms begins, we throw Broc flowers out on the sea with the tide.  After
 the Goddess works her magic, she returns the Broc flowers as the rare Xander root. }
{106}{}{We offer tribute to the Goddess of the Sea each year in the form of Xander root.  If the
 Goddess deems us worthy, she will turn the Xander root into Broc flowers. }
{107}{}{Po obfitych zbiorach wznosimy do Bogini Morza modlitwę dziękczynną, z prośbą, aby miała nas w swojej opiece, a ona co roku nagradza nasze oddanie przysyłając nam włócznie jako znak, że nad nami czuwa.}
{108}{}{Mogę zobaczyć, co zesłała wam Bogini Morza?}
{109}{}{Ug}
{110}{}{Oto przedmioty, które otrzymaliśmy od Bogini w tym roku. Chętnie podzielimy się nimi z tobą za odpowiednią cenę.}
{111}{}{Złom [10$]}
{112}{}{Pistolet laserowy [10000$]}
{113}{}{Zaostrzone kije [40$]}
{114}{}{Owoc [5$]}
{115}{}{Korzeń Xandrowy [20$]}
{116}{}{Kwiat Broca [10$]}
{117}{}{Bywaj.}
{118}{}{[Wyciąga rękę w kierunku morza] Idź przed siebie. Bogini życzy sobie spotkać się z tobą osobiście.}
{119}{}{[Koniec]}
{120}{}{Niech błogosławiona Bogini Morza czuwa nad twoimi ścieżkami.}
{121}{}{[Koniec]}
{122}{}{[He frowns as you fail to produce the required sum of money.]  Perhaps another time, then.}
{123}{}{[Koniec]}
