{100}{}{Widzisz mê¿czyznê w skórzanej zbroi.}
{101}{}{Widzisz Kagê.}
{102}{}{Jest ubrany w skórzan¹ zbrojê i ma denerwuj¹cy zwyczaj mówienia o sobie w trzeciej osobie.}
{103}{}{To ju¿ twoje ostatnie spotkanie z Kag¹.}
{104}{}{After Kaga kill yous, he will burn Arroyo to the ground.}
{105}{}{Poczuj gniew Kagi!}
{106}{}{Jestem Kaga Wielki!}
{107}{}{Kaga budzi strach w sercach wrogów.}
{108}{}{Kaga zrobi sobie z twojej g³owy trofeum.}
{109}{}{Poddaj siê, a twoja œmieræ bêdzie szybka.}
{110}{}{Kaga jeszcze wróci!}
{111}{}{Nie mo¿esz zabiæ Wielkiego Kagi!}
{112}{}{Masz szczêœcie, ¿e Kaga ma teraz wa¿niejsze sprawy gdzie indziej.}
{113}{}{Kaga jeszcze ciê znajdzie.}
