{100}{}{Widzisz mê¿czyznê w pancerzu bojowym.}
{101}{}{Widzisz Kagê w pancerzu bojowym.}
{102}{}{Ma na sobie pancerz bojowy i zdaje siê byæ nieŸle uzbrojony.}
{103}{}{Tym razem Kaga jest przygotowany na spotkanie z tob¹.}
{104}{}{Dziecko Przeznaczenia nigdy ju¿ nie wróci do Arroyo!}
{105}{}{Kaga ciê zmia¿d¿y!}
{106}{}{Kaga nie lêka siê nikogo!}
{107}{}{Stój w miejscu, Kaga chce dobrze wycelowaæ.}
{108}{}{Jeszcze spotkasz Kagê!}
{109}{}{Nie po raz ostatni widzisz Kagê.}
{110}{}{Kaga zdecydowanie musi jeszcze trochê potrenowaæ.}
