{100}{}{Widzisz mê¿czyznê w pancerzu wspomaganym MKII. Nie wygl¹da na przyjaŸnie nastawionego.}
{101}{}{Widzisz Kagê w pancerzu wspomaganym MKII.}
{102}{}{Wielki kawa³ ¿elastwa z rêkoma i broni¹.}
{103}{}{Mam ju¿ doœæ tego poœcigu. Pora to skoñczyæ.}
{104}{}{To ju¿ ostatnie twoje spotkanie z Kag¹.}
{105}{}{Nie masz szans z Kag¹.}
{106}{}{Przygotuj siê na pobyt w zaœwiatach.}
{107}{}{Godny by³ z ciebie przeciwnik.}
{108}{}{Ta czêœæ pustkowi nie potrzebuje takiego dobroczyñcy jak ty.}
{109}{}{Kiedy Kaga ciê zabijê, bêdzie najgroŸniejsz¹ osob¹ w tej czêœci pustkowi.}
{110}{}{Kaga nie mo¿e siê ju¿ doczekaæ powrotu do Arroyo... ¿eby puœciæ j¹ z dymem.}
{111}{}{Kaga bêdzie s³awny za zabicie ciebie.}
