{100}{}{Widzisz sk¹po odzianego mê¿czyznê.}
{101}{}{Widzisz Kagê.}
{103}{}{Nosi tylko spodnie i wygl¹da jakby by³ z jakiegoœ plemienia.}
{104}{}{To Kaga powinien byæ "Dzieckiem Przeznaczenia"!}
{105}{}{Jak œmieli wygnaæ Kagê z Arroyo, wykluczyæ z plemienia.}
{106}{}{Kaga zemœci siê... na TOBIE!}
{107}{}{Kaga wyœle ciê na tamt¹ stronê!}
{108}{}{Jeszcze spotkasz Kagê!}
{109}{}{Nikt, nigdy wczeœniej nie pokona³ Kagi!}
{110}{}{Kaga poœwiêci swoje ¿ycie, ¿eby ciê zniszczyæ.}
