{100}{}{Widzisz Nomada.}
{101}{}{On wygl¹da na przywódcê Nomadów.}
{102}{}{S¹dz¹c po stroju i sposobie zachowania, najprawdopodobniej jest przywódc¹.}
{103}{}{Oh, podró¿nik. B¹dŸ pozdrowiony, w moim skromnym namiocie. Skryj siê w jego cieniu przed pal¹cym s³oñcem pustkowi.}
{104}{}{Dziêki ci; z wdziêcznoœci¹ przyjmuje twoj¹ ofertê cienia.}
{105}{}{Muszê odmówiæ. Bardzo siê œpieszê.}
{106}{}{Uuga.}
{107}{}{B¹dŸ wiêc pozdrowiony podró¿niku. D³ugo byliœmy z dala od "cywilizowanych" krain. Potrzebujemy pewnych przedmiotów. Mo¿e bêdziemy mogli pohandlowaæ?}
{108}{}{Co macie na wymianê?}
{109}{}{Nie mam nic do zaoferowania. Przepraszam.}
{110}{}{Có¿, mo¿e innym razem? Niech twoje podró¿e bêd¹ wolne od niebezpieczeñstw.}
{111}{}{Pa.}
{112}{}{To niefortunne. Wiêc rozgoœæ siê i odpocznij w moim obozie.}
{113}{}{Pa.}
{114}{}{Widzê, ¿e moja oferta cienia jest spóŸniona. S³oñce zd¹¿y³o ju¿ wypaliæ s³owa z twojej g³owy. Lud pustyni ze wspó³czuciem traktuje braci i siostry o chorych umys³ach. Zostañ jak d³ugo zechcesz w moim obozie, o wolnomyœl¹cy.}
{115}{}{Pa.}
{116}{}{Niewierny pies!}
{117}{}{Dlaczego nas atakujesz?}
{118}{}{Oddam ¿ycie za moje plemiê!}
{119}{}{Jak œmiesz odrzucaæ nasz¹ goœcinnoœæ.}
{120}{}{OdejdŸ st¹d!}
{121}{}{Zostaw nas.}
{122}{}{Jesteœmy pokojowym plemieniem.}
