{100}{}{Nomad.}
{101}{}{Wódz Nomadów.}
{102}{}{S¹dz¹c po stroju i sposobie zachowania, widzisz zapewne wodza Nomadów.}
{103}{}{Ach, goœæ z dalekich stron. Witaj w moim skromnym namiocie. Spocznij w jego cieniu.}
{104}{}{Dziêkujê ci za goœcinê. Chêtnie chwilê odpocznê.}
{105}{}{Niestety, muszê odmówiæ. Bardzo siê spieszê.}
{106}{}{Uuga.}
{107}{}{Zatem spocznij. Od dawna nie odwiedzaliœmy 'cywilizowanych' krain. Potrzebujemy wielu rzeczy. Mo¿e zechcesz siê z nami wymieniæ?}
{108}{}{A co mo¿ecie mi zaoferowaæ?}
{109}{}{Przykro mi. Nie mam nic na wymianê.}
{110}{}{Có¿, mo¿e innym razem? Niech nad tw¹ drog¹ zawsze czuwaj¹ dobre duchy.}
{111}{}{¯egnaj.}
{112}{}{Wielka szkoda. Tak czy inaczej - rozgoœæ siê i odpoczywaj ile zechcesz.}
{113}{}{¯egnaj.}
{114}{}{Widzê, ¿e moja oferta jest spóŸniona. S³oñce zd¹¿y³o ju¿ wypaliæ s³owa z twojej g³owy. Lud pustyni ze wspó³czuciem traktuje braci i siostry o chorych umys³ach. Proszê, rozgoœæ siê. Nie zaznasz od nas krzywdy.}
{115}{}{¯egnaj.}
{116}{}{Niewierny pies!}
{117}{}{Dlaczego nas atakujesz?}
{118}{}{Poœwiêcê ¿ycie dla mojego plemienia!}
{119}{}{To pogwa³cenie naszej goœcinnoœci.}
{120}{}{OdejdŸ st¹d!}
{121}{}{Zostaw nas w spokoju.}
{122}{}{Nie chcemy wojny.}
