{100}{}{Widzisz... Tandi.}
{101}{}{Widzisz milutk¹, o kruczoczarnych w³osach dziewczynê z poci¹gaj¹cym wyrazem oczu. Spogl¹da marzycielsko w dal.}
{102}{}{Widzisz Tandi. Spogl¹da marzycielsko w dal.}
{103}{}{Widzisz Tandi. Spogl¹da marzycielsko w dal.}
{104}{}{Czeœæ! Jesteœ potomkiem bohatera jedynki Fallouta? £a³! Jestem Tandi! Witaj!}
{105}{}{Nie chcia³am tego tak po prostu pokazaæ po sobie, ale twój dziadek by³ bardzo milutki. [wzdycha]}
{106}{}{Ian? Chyba jesteœ gdzieœ w Falloucie 2. Mo¿e w Opactwie?}
{107}{}{Tak naprawdê, to podobno i *ja* jestem gdzieœ w Falloucie 2. Jednak nie chcê iœæ siebie poszukaæ... mog³oby to nas obydwie przestraszyæ na amen.}
{108}{}{Przepraszam, ¿e nie mia³am lepszych umiejêtnoœci bojowych w jedynce Fallouta. Chyba nie na wiele siê przyda³am.}
{109}{}{S³uchaj... czy ty i Tycho nadal jesteœcie w kontakcie?}
{110}{}{A wiêc by³ taki b³¹d, ¿e jak ju¿ by³am uratowana z r¹k najeŸdŸców i odprowadzona do taty, to czasami odbija³a mu palma. Kurcze, to by³o s³abe!}
{111}{}{Przy³¹czy³abym siê do ciebie, ale czekam, a¿ pojawi siê tu mój tata, Aradesh. Mia³ do³¹czyæ do mnie kilka wersji temu.}
