{100}{}{Widzisz podró¿nika.}
{101}{}{Nareszcie! Jakaœ przyjazna twarz.}
{102}{}{Potrzebujê wskazówek. Mo¿esz mi pomóc?}
{103}{}{Dok¹d zmierzacie?}
{104}{}{Czym siê zajmujesz?}
{105}{}{Ug.}
{106}{}{No nie wiem. Nie znam zbyt dobrze tych stron. Wiem, gdzie le¿¹.}
{107}{}{Nowego Reno}
{108}{}{Kryptopolis}
{109}{}{Redding}
{110}{}{Nory}
{111}{}{San Francisco}
{112}{}{Republika Nowej Kalifornii}
{113}{}{Opuszczona kopalnia.}
{114}{}{Nie, te miejsca ju¿ znam. Mimo to - dziêki.}
{115}{}{Nowe Reno - to dopiero wspania³e miejsce. Seks, narkotyki i hazard. Czego wiêcej chcieæ od ¿ycia? Czekaj, poka¿ê ci gdzie to jest.}
{116}{}{Dziêki.}
{117}{}{Kryptopolis - to dopiero miasto kretynów. Wystarczy, ¿e wyroœnie ci dodatkowy palec i traktuj¹ ciê jak jakieœ dziwad³o. Nie by³em w œrodku, ale wiem gdzie to jest.}
{118}{}{Dziêki.}
{119}{}{Redding... Nie wiem zbyt wiele o tym mieœcie, poza tym, ¿e to osiedle górnicze. Le¿y na pó³nocy w samiutkim œrodku najgorszych gór jakie œwiat ogl¹da³.}
{120}{}{Dziêki.}
{121}{}{Lepiej trzymaj siê z dala od Nory. To miasto po prostu przyci¹ga najgorsze mêty pustkowi. Poka¿ê ci gdzie to jest, ale uprzedzam - omijaj Norê szerokim ³ukiem.}
{122}{}{Dziêki.}
{123}{}{San Francisco. Hmmmm... wiem tylko, ¿e ¿yj¹ tam dziwni ludzie. To na wybrze¿u.}
{124}{}{Dziêki.}
{125}{}{Republika Nowej Kalifornii... to ca³kiem mi³e miejsce. Chêtnie siê tam kiedyœ osiedlê. Czysto, mili ludzie, dobrze zarz¹dzane. Zaznaczê ci RNK na mapie.}
{126}{}{Dziêki.}
{127}{}{Tak, jakiœ czas temu zdarzy³o mi siê obozowaæ w starej osadzie górniczej. Niestety, wilki szybko mnie stamt¹d wyp³oszy³y. A szkoda, bo górnicy zwiewali chyba w pop³ochu i zostawili sporo sprzêtu. Nie zamierzam tam raczej wracaæ, wiêc chyba mogê pokazaæ ci gdzie to by³o.}
{128}{}{Dziêki.}
{129}{}{Och... to naprawdê nieistotne. Ot - zachcia³o mi siê kiedyœ wyruszyæ w podró¿ i... oto jestem.}
{130}{}{Mo¿esz mi pomóc? Potrzebujê wskazówek.}
{131}{}{Czym siê zajmujesz?}
{132}{}{Mi³o siê gawêdzi³o.}
{133}{}{Pracujê dorywczo tu i tam. Ale g³ównie po prostu podró¿ujê.}
{134}{}{Mo¿esz mi pomóc? Potrzebujê wskazówek.}
{135}{}{Dok¹d zmierzasz?}
{136}{}{Mi³o siê gawêdzi³o.}
{137}{}{Naprawdê muszê ju¿ iœæ. Mi³o siê gawêdzi³o.}
{138}{}{Mo¿e siê jeszcze kiedyœ spotkamy.}
{139}{}{Chcê dotrzeæ przed zmrokiem do jakiejœ osady. Muszê ju¿ iœæ.}
{140}{}{I'd be going.}
{141}{}{Pu³apka!}
{142}{}{Nikomu nie mo¿na ju¿ zaufaæ.}
{143}{}{£amiesz honorowy kodeks podró¿nika.}
{144}{}{Pora iœæ dalej.}
{145}{}{No, to pora iœæ.}
{146}{}{Pora ruszaæ w drogê.}
{150}{}{Dziêki. Potrzebujê lokalizacji jeszcze kilku innych miejsc.}
