{100}{}{Widzisz podróżnika.}
{101}{}{Nareszcie! Jakaś przyjazna twarz.}
{102}{}{Potrzebuję wskazówek. Możesz mi pomóc?}
{103}{}{A dokąd zmierzasz?}
{104}{}{Co tutaj robisz?}
{105}{}{Ug.}
{106}{}{No nie wiem. Nie znam zbyt dobrze tych stron. Wiem, gdzie leżą.}
{107}{}{Nowego Reno}
{108}{}{Kryptopolis}
{109}{}{Redding}
{110}{}{Nory}
{111}{}{San Francisco}
{112}{}{Republika Nowej Kalifornii}
{113}{}{Opuszczona kopalnia.}
{114}{}{Nie, te miejsca już znam. Mimo to - dzięki.}
{115}{}{New Reno -- now that's a great place to go. Sex, drugs and gambling.  What more can one ask for?
 Here, let me show you where it is.}
{116}{}{Dziękuję.}
{117}{}{Kryptopolis - to dopiero miasto kretynów. Wystarczy, że wyrośnie ci dodatkowy palec i traktują cię jak jakieś dziwadło. Nie byłem w środku, ale wiem gdzie to jest.}
{118}{}{Dziękuję.}
{119}{}{Redding... Nie wiem zbyt wiele o tym mieście, poza tym, że to osiedle górnicze. Leży na północy w samiutkim środku najgorszych gór jakie świat oglądał.}
{120}{}{Dziękuję.}
{121}{}{Lepiej trzymaj się z dala od Nory. To miasto po prostu przyciąga najgorsze męty pustkowi. Pokażę ci gdzie to jest, ale uprzedzam - omijaj Norę szerokim łukiem.}
{122}{}{Dziękuję.}
{123}{}{San Francisco. Hmmmm... wiem tylko, że żyją tam dziwni ludzie. To na wybrzeżu.}
{124}{}{Dziękuję.}
{125}{}{Republika Nowej Kalifornii... to całkiem miłe miejsce. Chętnie się tam kiedyś osiedlę. Czysto, mili ludzie, dobrze zarządzane. Zaznaczę ci RNK na mapie.}
{126}{}{Dziękuję.}
{127}{}{Tak, jakiś czas temu zdarzyło mi się obozować w starej osadzie górniczej. Niestety, wilki szybko mnie stamtąd wypłoszyły. A szkoda, bo górnicy zwiewali chyba w popłochu i zostawili sporo sprzętu. Nie zamierzam tam raczej wracać, więc chyba mogę pokazać ci gdzie to było.}
{128}{}{Dziękuję.}
{129}{}{Och... to naprawdę nieistotne. Ot - zachciało mi się kiedyś wyruszyć w podróż i... oto jestem.}
{130}{}{Możesz mi pomóc? Potrzebuję wskazówek.}
{131}{}{Co tutaj robisz?}
{132}{}{Miło się rozmawiało.}
{133}{}{Pracuję dorywczo tu i tam. Ale głównie po prostu podróżuję.}
{134}{}{Możesz mi pomóc? Potrzebuję wskazówek.}
{135}{}{Dokąd zmierzasz?}
{136}{}{Miło się rozmawiało.}
{137}{}{Naprawdę muszę już iść. Miło się gawędziło.}
{138}{}{Może się jeszcze kiedyś spotkamy.}
{139}{}{Chcę dotrzeć przed zmrokiem do jakiejś osady. Muszę już iść.}
{140}{}{I'd be going.}
{141}{}{Pułapka!}
{142}{}{Nikomu już nie można ufać.}
{143}{}{Łamiesz honorowy kodeks podróżnika.}
{144}{}{Pora iść dalej.}
{145}{}{No, to pora iść.}
{146}{}{Pora ruszać w drogę.}
{150}{}{Dzięki. Potrzebuję lokalizacji jeszcze kilku innych miejsc.}
