{100}{}{Widzisz ch³opa Shi.}
{101}{}{Widzisz dokera.}
{102}{}{Widzisz ch³opa Shi, którego ubranie pokryte jest rybimi ³uskami, smo³¹ i sol¹.}
{103}{}{Dobry dzieñ na spêdzenie go nad oceanem.}
{104}{}{Zawsze lubiê obserwowaæ rozbijaj¹ce siê fale.}
{105}{}{Lubisz tran?}
{106}{}{S³oñce, œwie¿e powietrze i frutti di mare. Czego jeszcze mo¿na by sobie ¿yczyæ poza k¹piel¹?}
{107}{}{Mam ju¿ doœæ ryb.}
{108}{}{Boli mnie krzy¿.}
{109}{}{O, patrzcie... Nastêpny turysta.}
{112}{}{Uwa¿aj na potwory na tankowcu. A, zaraz... Chyba ju¿ zosta³y przez ciebie zauwa¿one.}
{113}{}{A wiêc nie masz problemów z poruszaniem siê po tankowcu?}
{114}{}{Ten tankowiec to ciê¿kie miejsce. Tak przynajmniej mówi¹ punki.}
{115}{}{Dochodzisz tam do czegoœ?}
{116}{}{Dobry dzieñ na spêdzenie go nad oceanem.}
{117}{}{Zawsze lubiê obserwowaæ rozbijaj¹ce siê fale.}
{118}{}{Lubisz tran?}
{119}{}{S³oñce, œwie¿e powietrze i frutti di mare. Czego jeszcze mo¿na by sobie ¿yczyæ poza k¹piel¹?}
{120}{}{Mam ju¿ doœæ ryb.}
{121}{}{Boli mnie krzy¿.}
{122}{}{O, patrzcie... Nastêpny turysta.}
{125}{}{}
{126}{}{}
{127}{}{}
{128}{}{}
{150}{}{Czas na œmieræ, turysto.}
{151}{}{S¹dzisz, ¿e prze¿yjesz bójkê w dokach?}
{152}{}{Nie s¹dzê, aby by³ z ciebie jakiœ twardziel.}
{153}{}{Zobaczymy, jak ci siê spodoba parê ciosów od dokera Shi!}
