{100}{}{Widzisz niskiego, okr¹g³ego Shi.}
{101}{}{Widzisz dr Wonga Yi Tze.}
{102}{}{Widzisz niskiego, okr¹g³ego Shi.}
{103}{}{Czy mogê ci w czymœ pomóc?}
{104}{}{Dagi nu?}
{105}{}{Ty kto?}
{106}{}{Podobno posiadasz cudz¹ œledzionê.}
{107}{}{Kim jesteœ?}
{108}{}{Czym siê tutaj zajmujesz?}
{109}{}{Nie, dziêki. To wszystko.}
{110}{}{Muszê przyznaæ, ¿e nie mówiê w twoim jêzyku. Mo¿esz spróbuj porozmawiaæ z Kenem Lee, on zna wiele ró¿nych jêzyków.}
{111}{}{Aag!}
{112}{}{Jestem dr Wong. Jestem szefem tej placówki.}
{113}{}{Jeszcze kilka pytañ, proszê.}
{114}{}{Dziêki. Na razie.}
{115}{}{Nadzorujê eksperymenty naukowe, które tu tworzymy i przeprowadzamy. Jestem te¿ odpowiedzialny za sieæ komputerow¹.}
{116}{}{Co planujecie?}
{117}{}{Jak dostaæ siê do sieci komputerowej?}
{118}{}{Mam inne pytania.}
{119}{}{Rozumiem. Do zobaczenia.}
{120}{}{Ach, ale je¿eli zdradzê ci nasze plany, to wszyscy je bêd¹ znali. Obawiam siê, ¿e na razie s¹ one tajne.}
{121}{}{W porz¹dku, nie ma sprawy. Mam inne pytania.}
{122}{}{Dziêki. Na razie.}
{123}{}{A co, je¿eli przy³o¿ê ci pistolet do g³owy i zmuszê do mówienia?}
{124}{}{Có¿, albo ucz¹c siê, jak siê tam w³amaæ, albo zaprzyjaŸniaj¹c siê z jednym z moich podw³adnych. Oczywiœcie ¿artujê na temat tego w³amywania siê - w takim wypadku musia³bym kogoœ za tob¹ wys³aæ, ¿eby ciê zabi³. [Uœmiecha siê, aby pokazaæ, ¿e nie chcia³ ciê obraziæ]}
{125}{}{Naprawdê byœ mnie zabi³?}
{126}{}{A wiêc nie mia³byœ ¿adnych wiêkszych obiekcji, gdyby ktoœ, np. ja, zajrza³ do komputera?}
{127}{}{Mam inne pytanie.}
{128}{}{Oczywiœcie. Na razie.}
{129}{}{Wtedy musia³bym uznaæ to za zagro¿enie i ostrzec ciê, ¿e takie dzia³anie mo¿e byæ niebezpieczne dla twojego zdrowia.}
{130}{}{SprawdŸmy to.}
{131}{}{To by³ tylko ¿art. Mam inne pytania.}
{132}{}{[Uœmiecha siê] Musimy broniæ naszego honoru, lao wai.}
{133}{}{Yy, jasne. A wiêc mia³byœ jakieœ wiêksze obiekcje, gdyby ktoœ, np. ja, zajrza³ do komputera?}
{134}{}{Jaaasne. Mam inne pytania.}
{135}{}{Nie w¹tpiê. Na razie.}
{136}{}{Je¿eli przekonasz do tego moich podw³adnych. Ale ja na pewno nie.}
{137}{}{A co gdyby tak nagle pod twoim nosem pojawi³a siê spluwa?}
{138}{}{Wspaniale. Có¿, mam inne pytania.}
{139}{}{Hmm. Rozumiem. Có¿, do zobaczenia.}
{140}{}{Ach, tak! Dok³adnie. Przygotujê j¹ sobie z czerwon¹ fasolk¹ i doskona³ym chianti.}
{141}{}{Wci¹¿ j¹ masz? To dobrze. Chip potrzebuje jej z powrotem.}
{142}{}{To ludzka œledziona, ty kopniêty draniu!}
{143}{}{Zdajesz sobie sprawê, ¿e do tego wina powinno siê podawaæ w¹trobê, a nie œledzionê, prawda?}
{144}{}{Wiesz, to ludzka œledziona.}
{145}{}{Kto to jest ten Chip? To teraz moja œledziona i zjem j¹ sobie na obiad.}
{146}{}{Chip to pierwszy w³aœciciel tej œledziony. By³ pijany i sprzeda³ j¹ Lao Chou.}
{147}{}{Wiesz, potrzebuje jej do prze¿ycia. Pochodzi z jego cia³a.}
{148}{}{Wiêc mo¿e lepiej, jeœli ciê dla niej zabijê.}
{149}{}{Umowa to umowa. Nie mo¿e jej dostaæ z powrotem. Przykro mi, ale ubiliœmy interes, wiêc to, ¿e Chip ¿a³uje swojej decyzji nie oznacza wcale, ¿e mo¿e teraz cofaæ dane s³owo.}
{150}{}{[KONTYNUUJ]}
{151}{}{To jest ludzka œledziona? Lao Chou nic mi o tym nie mówi³!}
{152}{}{Pomimo to, z powodu bezczelnoœci pos³añca, s¹dzê, ¿e dalej bêdê trzyma³ siê ca³oœci umowy. Bêdê na niej eksperymentowa³.}
{153}{}{Powiedz swojemu przyjacielowi, ¿eby przyszed³ tu w ci¹gu nastêpnego dnia, a ja z chêci¹ mu j¹ zwrócê. Mam tylko nadziejê, ¿e znajdziesz jakiœ sposób na w³o¿enie mu jej z powrotem na czas.}
{154}{}{Dobrze.}
{155}{}{Cha cha! Tak, ja te¿ ogl¹da³em ten stary film. Chwila... chcesz powiedzieæ? Czy chcesz powiedzieæ, ¿e...?}
{156}{}{Tak, to jest ludzka œledziona}
{157}{}{W³aœciwie, to nie zgodzi³bym siê na to. Nie uda³o ci siê pokazaæ siebie z dobrej strony. Tak naprawdê, to nawet nie wiem, po co z tob¹ rozmawiam. Dobrego dnia ¿yczê.}
{158}{}{[dalej]}
{159}{}{Ratunku! Stra¿e! Intruz lao wai jest tutaj!}
{160}{}{Masz dla mnie pewne schematy?}
{161}{}{Ken Lee powiedzia³ mi, aby ci to oddaæ.}
{162}{}{Tak. A co dostanê w zamian?}
{163}{}{Nie, jeszcze nie.}
{164}{}{Porozmawiaj z Kenem Lee, a przedyskutuje z tob¹, co siê stanie w twojej przysz³oœci. Dziêkujê ci. Dziêki temu bêdziemy mogli sprawdziæ niektóre z naszych eksperymentalnych danych. Do widzenia.}
{165}{}{Mam jeszcze tylko kilka pytañ.}
{166}{}{Do widzenia.}
