{100}{}{Widzisz niskiego, okrągłego Shi.}
{101}{}{Widzisz dr Wonga Yi Tze.}
{102}{}{Widzisz niskiego, okrągłego Shi.}
{103}{}{Czy mogę ci w czymś pomóc?}
{104}{}{Dagi nu?}
{105}{}{Ty kto?}
{106}{}{Podobno posiadasz cudzą śledzionę.}
{107}{}{Kim jesteś?}
{108}{}{Czym się tutaj zajmujesz?}
{109}{}{Nie, dzięki. To wszystko.}
{110}{}{Muszę przyznać, że nie mówię w twoim języku. Możesz spróbuj porozmawiać z Kenem Lee, on zna wiele różnych języków.}
{111}{}{Aag!}
{112}{}{Jestem dr Wong. Jestem szefem tej placówki.}
{113}{}{Jeszcze kilka pytań, proszę.}
{114}{}{Dzięki. Na razie.}
{115}{}{Nadzoruję eksperymenty naukowe, które tu tworzymy i przeprowadzamy. Jestem też odpowiedzialny za sieć komputerową.}
{116}{}{Co planujecie?}
{117}{}{Jak dostać się do sieci komputerowej?}
{118}{}{Mam inne pytania.}
{119}{}{Rozumiem. Do zobaczenia.}
{120}{}{Ach, ale jeżeli zdradzę ci nasze plany, to wszyscy je będą znali. Obawiam się, że na razie są one tajne.}
{121}{}{W porządku, nie ma sprawy. Mam inne pytania.}
{122}{}{Dzięki. Na razie.}
{123}{}{A co, jeżeli przyłożę ci pistolet do głowy i zmuszę do mówienia?}
{124}{}{Cóż, albo ucząc się, jak się tam włamać, albo zaprzyjaźniając się z jednym z moich podwładnych. Oczywiście żartuję na temat tego włamywania się - w takim wypadku musiałbym kogoś za tobą wysłać, żeby cię zabił. [Uśmiecha się, aby pokazać, że nie chciał cię obrazić]}
{125}{}{Naprawdę byś mnie zabił?}
{126}{}{A więc nie miałbyś żadnych większych obiekcji, gdyby ktoś, np. ja, zajrzał do komputera?}
{127}{}{Mam inne pytanie.}
{128}{}{Oczywiście. Na razie.}
{129}{}{Wtedy musiałbym uznać to za zagrożenie i ostrzec cię, że takie działanie może być niebezpieczne dla twojego zdrowia.}
{130}{}{Sprawdźmy to.}
{131}{}{To był tylko żart. Mam inne pytania.}
{132}{}{[Uśmiecha się] Musimy bronić naszego honoru, lao wai.}
{133}{}{Yy, jasne. A więc miałbyś jakieś większe obiekcje, gdyby ktoś, np. ja, zajrzał do komputera?}
{134}{}{Jaaasne. Mam inne pytania.}
{135}{}{Nie wątpię. Na razie.}
{136}{}{Jeżeli przekonasz do tego moich podwładnych. Ale ja na pewno nie.}
{137}{}{A co gdyby tak nagle pod twoim nosem pojawiła się spluwa?}
{138}{}{Wspaniale. Cóż, mam inne pytania.}
{139}{}{Hmm. Rozumiem. Cóż, do zobaczenia.}
{140}{}{Ach, tak! Dokładnie. Przygotuję ją sobie z czerwoną fasolką i doskonałym chianti.}
{141}{}{Wciąż ją masz? To dobrze. Chip potrzebuje jej z powrotem.}
{142}{}{To ludzka śledziona, ty kopnięty draniu!}
{143}{}{Zdajesz sobie sprawę, że do tego wina powinno się podawać wątrobę, a nie śledzionę, prawda?}
{144}{}{Wiesz, to ludzka śledziona.}
{145}{}{Kto to jest ten Chip? To teraz moja śledziona i zjem ją sobie na obiad.}
{146}{}{Chip to pierwszy właściciel tej śledziony. Był pijany i sprzedał ją Lao Chou.}
{147}{}{Wiesz, potrzebuje jej do przeżycia. Pochodzi z jego ciała.}
{148}{}{Więc może lepiej, jeśli cię dla niej zabiję.}
{149}{}{Umowa to umowa. Nie może jej dostać z powrotem. Przykro mi, ale ubiliśmy interes, więc to, że Chip żałuje swojej decyzji nie oznacza wcale, że może teraz cofać dane słowo.}
{150}{}{[KONTYNUUJ]}
{151}{}{To jest ludzka śledziona? Lao Chou nic mi o tym nie mówił!}
{152}{}{Pomimo to, z powodu bezczelności posłańca, sądzę, że dalej będę trzymał się całości umowy. Będę na niej eksperymentował.}
{153}{}{Powiedz swojemu przyjacielowi, żeby przyszedł tu w ciągu następnego dnia, a ja z chęcią mu ją zwrócę. Mam tylko nadzieję, że znajdziesz jakiś sposób na włożenie mu jej z powrotem na czas.}
{154}{}{Dobrze.}
{155}{}{Cha cha! Tak, ja też oglądałem ten stary film. Chwila... chcesz powiedzieć? Czy chcesz powiedzieć, że...?}
{156}{}{Tak, to jest ludzka śledziona}
{157}{}{Właściwie, to nie zgodziłbym się na to. Nie udało ci się pokazać siebie z dobrej strony. Tak naprawdę, to nawet nie wiem, po co z tobą rozmawiam. Dobrego dnia życzę.}
{158}{}{[dalej]}
{159}{}{Ratunku! Straże! Intruz lao wai jest tutaj!}
{160}{}{Masz dla mnie pewne schematy?}
{161}{}{Ken Lee powiedział mi, aby ci to oddać.}
{162}{}{Tak. A co dostanę w zamian?}
{163}{}{Nie, jeszcze nie.}
{164}{}{Porozmawiaj z Kenem Lee, a przedyskutuje z tobą, co się stanie w twojej przyszłości. Dziękuję ci. Dzięki temu będziemy mogli sprawdzić niektóre z naszych eksperymentalnych danych. Do widzenia.}
{165}{}{Mam jeszcze tylko kilka pytań.}
{166}{}{Do widzenia.}
