{100}{}{Widzisz mê¿czyznê, który wygl¹da ca³kiem jak sklepikarz.}
{101}{}{Widzisz Lao Choua, sklepikarza.}
{102}{}{Widzisz mê¿czyznê w funkcjonalnym, wygodnym ubraniu.}
{103}{}{Witaj! Witaj w moim sklepie, Lataj¹cym Smoku 8.}
{104}{}{Co mogê dla ciebie zrobiæ?}
{105}{}{Da aggle oo!}
{106}{}{Toffar!}
{107}{}{Kim jesteœ?}
{108}{}{Szukam pewnego sprzêtu.}
{109}{}{Poszukujê pewnych informacji.}
{110}{}{Do widzenia.}
{111}{}{Chcesz coœ kupiæ?}
{112}{}{[pokiwaj g³ow¹]}
{113}{}{[pokrêæ g³ow¹]}
{114}{}{A wiêc oto, co mam.}
{115}{}{[dalej]}
{116}{}{Có¿, obawiam siê wiêc, ¿e to ju¿ wszystko, co mogê dla ciebie zrobiæ. Mi³ego dnia.}
{117}{}{[dalej]}
{118}{}{Jestem Lao Chou. Prowadzê sklep wielobran¿owy, Lataj¹cy Smok 8. Znany jestem z wymiany... informacjami.}
{119}{}{Jakimi informacjami?}
{120}{}{Rozumiem. Chcê coœ kupiæ.}
{121}{}{W tym mieœcie ma³o dzieje siê takich spraw, o których bym nie wiedzia³. Oczywiœcie musisz znaæ odpowiednie pytanie do zadania, prawda? Co chcesz wiedzieæ?}
{122}{}{Szukam jakichœ usprawnieñ do mojego sprzêtu.}
{123}{}{Gdzie mogê zdobyæ plany lataczy?}
{124}{}{Potrzebujê paliwa do PMV Valdeza.}
{125}{}{Rozumiem, ¿e potrzebujê KD do tankowca, aby dostaæ siê do komputera na Valdezie.}
{126}{}{Potrzebujê pewnych czêœci do PMV Valdeza.}
{127}{}{Szukam œledziony.}
{128}{}{Podobno jakieœ lataj¹ce maszyny przywioz³y tu pe³no ludzi z wioski.}
{129}{}{Nic. Do widzenia.}
{130}{}{Porozmawiaj z Crocketem z obozu Centrologów. Jest ich g³ównym naukowcem.}
{131}{}{Dziêki. Potrzebujê wiêcej informacji.}
{132}{}{Dziêki. Na razie.}
{133}{}{Szukaj na pó³noc, w Navarro. Jest tam ukryta baza w pobli¿u stacji benzynowej.}
{134}{}{Dziêki. Potrzebujê wiêcej informacji.}
{135}{}{Dziêki. Na razie.}
{136}{}{Mo¿e warto by poszukaæ w starych Kryptach. Podobno s¹ skarbnic¹ informacji i technologii staro¿ytnych.}
{137}{}{Dziêki. Potrzebujê wiêcej informacji.}
{138}{}{Dziêki. Na razie.}
{139}{}{Œledziony? Cha cha! Tak, Chip z Valdeza straci³ œledzionê w trakcie jednej z partyjek gry karcianej. Sprzeda³em j¹ dr Wongowi. By³ ni¹ zafascynowany.}
{140}{}{Dr Wong? Gdzie mogê go znaleŸæ?}
{141}{}{Jak mo¿na straciæ œledzionê?}
{142}{}{Dziêki. Potrzebujê wiêcej informacji.}
{143}{}{Ach tak. Na razie.}
{144}{}{Dr Wong jest g³ównym naukowcem Stalowego Pa³acu. Tam go szukaj.}
{145}{}{Tak przy okazji, to jak mo¿na straciæ œledzionê?}
{146}{}{Dziêki. Potrzebujê wiêcej informacji.}
{147}{}{Dziêki. Na razie.}
{148}{}{By³ pijany. Bardzo, bardzo pijany. Ca³¹ noc mia³ obsesjê na punkcie swojej œledziony. No i j¹ postawi³.}
{149}{}{Wiêc wzi¹³eœ jego ŒLEDZIONÊ?}
{150}{}{Rozumiem. Có¿, mam inne pytania.}
{151}{}{Tak. Taki by³ zak³ad. On jest honorowym cz³owiekiem.}
{152}{}{Rozumiem. Có¿, mam inne pytania.}
{153}{}{Ale z ciebie chory, prymitywny drañ, nie?}
{154}{}{Ta. Na razie.}
{155}{}{Jesteœ osob¹ bez honoru. Nie chcê ciê mieæ w moim sklepie. Wróæ kiedy indziej.}
{156}{}{Jak chcesz.}
{157}{}{Nie. Przyby³y z pó³nocy i przelecia³y nad nami, udaj¹c siê za morze.}
{158}{}{Za horyzont? A jak do diab³a mam siê tam dostaæ?}
{159}{}{Ta, no oczywiœcie. A teraz gadaj mi gdzie s¹, zanim otworzê ciê jak puszkê sardynek.}
{160}{}{Có¿... ¿adna z naszych ³odzi nie jest w stanie przebyæ takiej odleg³oœci. Chyba ¿e...}
{161}{}{Chyba ¿e...?}
{162}{}{Dziêki za "pomoc". Idê zdobyæ jak¹œ rozs¹dn¹ radê.}
{163}{}{...chyba ¿e uda ci siê zmusiæ ten stary tankowiec w dokach do dzia³ania. To stary statek, ale zapewne wci¹¿ jeszcze dzia³a, je¿eli trochê siê nad nim popracuje. Poproœ punków o wiêcej informacji.}
{164}{}{Dziêki. Chcê ciê spytaæ o coœ jeszcze.}
{165}{}{Dziêki. Na razie.}
{166}{}{Mówi siê, ¿e ostatnio Centrolodzy weszli w posiadanie du¿ej iloœci paliwa. Dogadaj siê z nimi.}
{167}{}{Dziêki. Chcê ciê spytaæ o coœ jeszcze.}
{168}{}{Dziêki. Na razie.}
{169}{}{Mo¿esz spróbowaæ popytaæ naukowców Shi w Stalowym Pa³acu. Byæ mo¿e bêd¹ ci w stanie pomóc z twoim zapotrzebowaniem na paliwo.}
{170}{}{Dziêki. Chcê ciê spytaæ o coœ jeszcze.}
{171}{}{Dziêki. Na razie.}
{172}{}{Jesteœ wrogiem mojego ludu. Giñ!}
{173}{}{Zabicie UKC-9 by³o dobrym uczynkiem dla naszego ludu. Mam nadziejê, ¿e bêdê ci w stanie w jakiœ sposób pomóc.}
{174}{}{Kim jesteœ?}
{175}{}{Szukam pewnego sprzêtu.}
{176}{}{Poszukujê pewnych informacji.}
{177}{}{Do widzenia.}
{178}{}{Dostali je ju¿ od ciebie Centrolodzy, nie?}
{179}{}{A tak... e... Mogê spytaæ o coœ innego?}
{180}{}{A tak... na razie.}
