{100}{}{Widzisz mężczyznę, który wygląda całkiem jak sklepikarz.}
{101}{}{Widzisz Lao Choua, sklepikarza.}
{102}{}{Widzisz mężczyznę w funkcjonalnym, wygodnym ubraniu.}
{103}{}{Witaj! Witaj w moim sklepie, Latającym Smoku 8.}
{104}{}{Co mogę dla ciebie zrobić?}
{105}{}{Da aggle oo!}
{106}{}{Toffar!}
{107}{}{Kim jesteś?}
{108}{}{Szukam pewnego sprzętu.}
{109}{}{Szukam informacji.}
{110}{}{Bywaj.}
{111}{}{Chcesz coś kupić?}
{112}{}{[Pokiwaj głową.]}
{113}{}{[Pokręć głową.]}
{114}{}{A więc oto, co mam.}
{115}{}{[dalej]}
{116}{}{Cóż, obawiam się więc, że to już wszystko, co mogę dla ciebie zrobić. Miłego dnia.}
{117}{}{[dalej]}
{118}{}{Jestem Lao Chou. Prowadzę sklep wielobranżowy, Latający Smok 8. Znany jestem z wymiany... informacjami.}
{119}{}{Jakimi informacjami?}
{120}{}{Rozumiem. Chcę coś kupić.}
{121}{}{W tym mieście mało dzieje się takich spraw, o których bym nie wiedział. Oczywiście musisz znać odpowiednie pytanie do zadania, prawda? Co chcesz wiedzieć?}
{122}{}{Szukam jakichś usprawnień do mojego sprzętu.}
{123}{}{Gdzie mogę zdobyć plany lataczy?}
{124}{}{Potrzebuję paliwa do PMV Valdeza.}
{125}{}{Rozumiem, że potrzebuję KD do tankowca, aby dostać się do komputera na Valdezie.}
{126}{}{Potrzebuję pewnych części do PMV Valdeza.}
{127}{}{Szukam śledziony.}
{128}{}{Podobno jakieś latające maszyny przywiozły tu pełno ludzi z wioski.}
{129}{}{Nic takiego. Na razie.}
{130}{}{Porozmawiaj z Crockettem z obozu Centrologów. Jest ich głównym naukowcem.}
{131}{}{Dzięki. Potrzebuję więcej informacji.}
{132}{}{Dzięki. Na razie.}
{133}{}{Szukaj na północ, w Navarro. Jest tam ukryta baza w pobliżu stacji benzynowej.}
{134}{}{Dzięki. Potrzebuję więcej informacji.}
{135}{}{Dzięki. Na razie.}
{136}{}{Może warto by poszukać w starych Kryptach. Podobno są skarbnicą informacji i technologii starożytnych.}
{137}{}{Dzięki. Potrzebuję więcej informacji.}
{138}{}{Dzięki. Na razie.}
{139}{}{Śledziony? Cha cha! Tak, Chip z Valdeza stracił śledzionę w trakcie jednej z partyjek gry karcianej. Sprzedałem ją dr Wongowi. Był nią zafascynowany.}
{140}{}{Dr Wong? Gdzie mogę go znaleźć?}
{141}{}{Jak można stracić śledzionę?}
{142}{}{Dzięki. Potrzebuję więcej informacji.}
{143}{}{Ach tak. Na razie.}
{144}{}{Dr Wong jest głównym naukowcem Stalowego Pałacu. Tam go szukaj.}
{145}{}{Tak przy okazji, to jak można stracić śledzionę?}
{146}{}{Dzięki. Potrzebuję więcej informacji.}
{147}{}{Dzięki. Na razie.}
{148}{}{Był pijany. Bardzo, bardzo pijany. Całą noc miał obsesję na punkcie swojej śledziony. No i ją postawił.}
{149}{}{Więc wziąłeś jego ŚLEDZIONĘ?}
{150}{}{Rozumiem. Mam także inne pytania.}
{151}{}{Tak. Taki był zakład. On jest honorowym człowiekiem.}
{152}{}{Rozumiem. Cóż, mam inne pytania.}
{153}{}{Ale z ciebie chory, prymitywny drań, nie?}
{154}{}{Ta. Na razie.}
{155}{}{Jesteś osobą bez honoru. Nie chcę cię mieć w moim sklepie. Wróć kiedy indziej.}
{156}{}{Jak chcesz.}
{157}{}{Nie. Przybyły z północy i przeleciały nad nami, udając się za morze.}
{158}{}{Za horyzont? A jak do diabła mam się tam dostać?}
{159}{}{Ta, no oczywiście. A teraz gadaj mi gdzie są, zanim otworzę cię jak puszkę sardynek.}
{160}{}{Cóż... żadna z naszych łodzi nie jest w stanie przebyć takiej odległości. Chyba że...}
{161}{}{Chyba że...?}
{162}{}{Dzięki za "pomoc". Idę zdobyć jakąś rozsądną radę.}
{163}{}{...chyba że uda ci się zmusić ten stary tankowiec w dokach do działania. To stary statek, ale zapewne wciąż jeszcze działa, jeżeli trochę się nad nim popracuje. Poproś punków o więcej informacji.}
{164}{}{Dzięki. Potrzebuję więcej informacji.}
{165}{}{Dzięki. Na razie.}
{166}{}{Mówi się, że ostatnio Centrolodzy weszli w posiadanie dużej ilości paliwa. Dogadaj się z nimi.}
{167}{}{Dzięki. Potrzebuję więcej informacji.}
{168}{}{Dzięki. Na razie.}
{169}{}{Możesz spróbować popytać naukowców Shi w Stalowym Pałacu. Być może będą ci w stanie pomóc z twoim zapotrzebowaniem na paliwo.}
{170}{}{Dzięki. Potrzebuję więcej informacji.}
{171}{}{Dzięki. Na razie.}
{172}{}{Jesteś wrogiem mojego ludu. Giń!}
{173}{}{Zabicie UKC-9 było dobrym uczynkiem dla naszego ludu. Mam nadzieję, że będę ci w stanie w jakiś sposób pomóc.}
{174}{}{Kim jesteś?}
{175}{}{Szukam pewnego sprzętu.}
{176}{}{Szukam informacji.}
{177}{}{Bywaj.}
{178}{}{Dostali je już od ciebie Centrolodzy, nie?}
{179}{}{A tak... e... Mogę spytać o coś innego?}
{180}{}{A tak... na razie.}
