{100}{}{Widzisz kogoś noszącego kapitańską czapkę.}
{101}{}{Widzisz Kapitana A. Rona Meyersa.}
{102}{}{Widzisz punka w znoszonym ubraniu noszącego kapitańską czapkę.}
{103}{}{Czego do cholery chcesz? Nie rozmawiam z nikim, chyba że to przyjaciele albo dobrzy ludzie. Zrób coś dla jednego z moich kumpli, a wtedy możesz przyjść i porozmawiać.}
{104}{}{[dalej]}
{105}{}{Słyszałem o twojej pomocy dla moich ludzi. Dziękuję. Jak mogę ci pomóc?}
{106}{}{Ty kto?}
{107}{}{Podobny ty jesteś tym, kto wie wszystko o tym statku.}
{108}{}{Dlaczego nazywają cię Kapitanem?}
{109}{}{Jak ten okręt wprawić w ruch?}
{110}{}{Nic nic.}
{111}{}{Jestem Kapitanem. Dowodzę tym statkiem. Inne pytania możesz iść zadać któremuś z Shi, Borsukowi lub komuś innemu. Ja nie mam dla ciebie czasu.}
{112}{}{[dalej]}
{113}{}{This ship's a Poseidon tanker. It's equipped with tech that lasted through the war. It's got a FOB that allows access to the navigation computer room, and it's got an IFF transponder that protects it from Poseidon guns.}
{114}{}{Skąd ty to wszystko wiesz?}
{115}{}{Co to jest transponder IFF?}
{116}{}{Jak go wprawić w ruch?}
{117}{}{Dzięki. Na razie.}
{118}{}{Kiedyś służyłem w Enklawie. Potem zrozumiałem, że to nie dla USA walczę, lecz dla bogatych, starych drani, którzy nie chcą oddać swojej władzy. Zdezerterowałem i żyję teraz z bardziej uczciwymi ludźmi.}
{119}{}{Bardziej uczciwymi? Tymi tutaj?}
{120}{}{Co to dokładnie jest ta Enklawa?}
{121}{}{Jak ten okręt wprawić w ruch?}
{122}{}{Bywaj.}
{123}{}{How do you pilot this rig? Fill 'er up with some gas - try the Hubologists or the Shi after you've taken care of everything else - and press the button. The computer will take care of the rest, if it's still working. It'll sail right out to the oil rig, and they won't fire at you because you've got the IFF transponder. Just make sure you've got what you need to access everything: FOB, working computer, and fuel. Easy enough, huh?}
{124}{}{Jasne. Skąd to wszystko wiesz?}
{125}{}{Co to jest transponder IFF i KD?}
{126}{}{Jakiej platformy wiertniczej?}
{127}{}{Tak. Na razie.}
{128}{}{IFF: Identyfikacja Friend or Foe - Przyjaciel czy Wróg. Oznacza to, że ten statek jest rozpoznawany jako przyjaciel, więc inne jednostki Posejdona - jak na przykład platforma wiertnicza - nie będą strzelać do ciebie, gdy już znajdziesz się w ich zasięgu. Aha, no i KD to taka technologia Enklawy, która pozwala ci otwierać elektronicznie drzwi za pomocą karty. Zapewne takie coś można by znaleźć w jednej z ich baz, czy w podobnym miejscu.}
{129}{}{Skąd ty to wszystko wiesz?}
{130}{}{Jakiej platformy wiertniczej?}
{131}{}{Dzięki. Na razie.}
{132}{}{Tak. Z tymi ludźmi przynajmniej wiesz dokładnie, na czym stoisz. Oni nie bawią się w różne gierki. Enklawa przypomina stado hien - w sekundę obróciliby się przeciwko tobie.}
{133}{}{Co to dokładnie jest ta Enklawa?}
{134}{}{Jak się do nich przyłączyłeś?}
{135}{}{Enklawa to pozostałość po starych czasach. Jeżeli zabierzesz tę łajbę przez wodę na platformę, to zobaczysz na własne oczy, o czym mówię.}
{136}{}{Jak się nią pływa?}
{137}{}{Jaką platformę?}
{138}{}{Dość łatwo. Po prostu pewnego dnia opuściłem bazę w Navarro i skierowałem się tutaj. Pomyślałem sobie, że to jest ostatnie miejsce, gdzie ktokolwiek by mnie szukał. A poza tym nie jestem aż tak ważny dla Enklawy, żeby mnie szukać - po co marnować siły na zbuntowaną płotkę.}
{139}{}{Co to dokładnie jest ta Enklawa?}
{140}{}{Dzięki. Na razie.}
{141}{}{Kawał od brzegu znajduje się duża platforma wiertnicza Posejdona. To jest ostateczna baza Enklawy}
{142}{}{Skąd ty to wszystko wiesz?}
{143}{}{Co jeszcze dzieje się tam, na platformie?}
{144}{}{Dzięki. Na razie.}
{145}{}{Słowa się roznoszą.}
{146}{}{Rozumiem. Co jeszcze dzieje się tam, na platformie?}
{147}{}{Rozumiem. Do zobaczenia.}
{148}{}{Nie mam pojęcia. Byłem technikiem w Navarro, a nie operatorem na platformie. Rozmawialiśmy tylko przez linie komunikacyjne... To tyle, jeżeli chodzi o nasz kontakt.}
{149}{}{Rozumiem. Jeszcze raz, jak się pływa tym statkiem?}
{150}{}{Dzięki. Na razie.}
{151}{}{To duży błąd zadzierać z Kapitanem i jego przyjaciółmi...}
{152}{}{How do you pilot this rig? Well, I see you already gassed her up. When you've taken care of everything else, just press the button. The computer will take care of the rest, if it's still working. It'll sail right out to the oil rig, and they won't fire at you because you've got the IFF transponder. Just make sure you've got what you need to access everything: FOB, working computer, and fuel. Easy enough, huh?}
{153}{}{A tak. Musisz jeszcze zmusić komputer nawigacyjny do działania. Założę się, że znajdziesz części do niego w jednej z tych starych krypt.}
{154}{}{Dobrze cię znowu widzieć. Czego potrzebujesz?}
{155}{}{, i o ile się nie mylę, tam też są twoi przyjaciele.}
{156}{}{.}
