{100}{}{Widzisz kogoœ nosz¹cego kapitañsk¹ czapkê.}
{101}{}{Widzisz Kapitana A. Rona Meyersa.}
{102}{}{Widzisz punka w znoszonym ubraniu nosz¹cego kapitañsk¹ czapkê.}
{103}{}{Czego do cholery chcesz? Nie rozmawiam z nikim, chyba ¿e to przyjaciele albo dobrzy ludzie. Zrób coœ dla jednego z moich kumpli, a wtedy mo¿esz przyjœæ i porozmawiaæ.}
{104}{}{[dalej]}
{105}{}{S³ysza³em o twojej pomocy dla moich ludzi. Dziêkujê. Jak mogê ci pomóc?}
{106}{}{Ty kto?}
{107}{}{Podobny ty jesteœ tym, kto wie wszystko o tym statku.}
{108}{}{Dlaczego nazywaj¹ ciê Kapitanem?}
{109}{}{Jak ten okrêt wprawiæ w ruch?}
{110}{}{Nic nic.}
{111}{}{Jestem Kapitanem. Dowodzê tym statkiem. Inne pytania mo¿esz iœæ zadaæ któremuœ z Shi, Borsukowi lub komuœ innemu. Ja nie mam dla ciebie czasu.}
{112}{}{[dalej]}
{113}{}{This ship's a Poseidon tanker. It's equipped with tech that lasted through the war. It's got a FOB that allows access to the navigation computer room, and it's got an IFF transponder that protects it from Poseidon guns.}
{114}{}{Sk¹d ty to wszystko wiesz?}
{115}{}{Co to jest transponder IFF?}
{116}{}{Jak go wprawiæ w ruch?}
{117}{}{Dziêki. Na razie.}
{118}{}{Kiedyœ s³u¿y³em w Enklawie. Potem zrozumia³em, ¿e to nie dla USA walczê, lecz dla bogatych, starych drani, którzy nie chc¹ oddaæ swojej w³adzy. Zdezerterowa³em i ¿yjê teraz z bardziej uczciwymi ludŸmi.}
{119}{}{Bardziej uczciwymi? Tymi tutaj?}
{120}{}{Co to dok³adnie jest ta Enklawa?}
{121}{}{Jak ten okrêt wprawiæ w ruch?}
{122}{}{Bywaj.}
{123}{}{How do you pilot this rig? Fill 'er up with some gas - try the Hubologists or the Shi after you've taken care of everything else - and press the button. The computer will take care of the rest, if it's still working. It'll sail right out to the oil rig, and they won't fire at you because you've got the IFF transponder. Just make sure you've got what you need to access everything: FOB, working computer, and fuel. Easy enough, huh?}
{124}{}{Jasne. Sk¹d to wszystko wiesz?}
{125}{}{Co to jest transponder IFF i KD?}
{126}{}{Jakiej platformy wiertniczej?}
{127}{}{Tak. Na razie.}
{128}{}{IFF: Identyfikacja Friend or Foe - Przyjaciel czy Wróg. Oznacza to, ¿e ten statek jest rozpoznawany jako przyjaciel, wiêc inne jednostki Posejdona - jak na przyk³ad platforma wiertnicza - nie bêd¹ strzelaæ do ciebie, gdy ju¿ znajdziesz siê w ich zasiêgu. Aha, no i KD to taka technologia Enklawy, która pozwala ci otwieraæ elektronicznie drzwi za pomoc¹ karty. Zapewne takie coœ mo¿na by znaleŸæ w jednej z ich baz, czy w podobnym miejscu.}
{129}{}{Sk¹d ty to wszystko wiesz?}
{130}{}{Jakiej platformy wiertniczej?}
{131}{}{Dziêki. Na razie.}
{132}{}{Tak. Z tymi ludŸmi przynajmniej wiesz dok³adnie, na czym stoisz. Oni nie bawi¹ siê w ró¿ne gierki. Enklawa przypomina stado hien - w sekundê obróciliby siê przeciwko tobie.}
{133}{}{Co to dok³adnie jest ta Enklawa?}
{134}{}{Jak siê do nich przy³¹czy³eœ?}
{135}{}{Enklawa to pozosta³oœæ po starych czasach. Je¿eli zabierzesz tê ³ajbê przez wodê na platformê, to zobaczysz na w³asne oczy, o czym mówiê.}
{136}{}{Jak siê ni¹ p³ywa?}
{137}{}{Jak¹ platformê?}
{138}{}{Doœæ ³atwo. Po prostu pewnego dnia opuœci³em bazê w Navarro i skierowa³em siê tutaj. Pomyœla³em sobie, ¿e to jest ostatnie miejsce, gdzie ktokolwiek by mnie szuka³. A poza tym nie jestem a¿ tak wa¿ny dla Enklawy, ¿eby mnie szukaæ - po co marnowaæ si³y na zbuntowan¹ p³otkê.}
{139}{}{Co to dok³adnie jest ta Enklawa?}
{140}{}{Dziêki. Na razie.}
{141}{}{Kawa³ od brzegu znajduje siê du¿a platforma wiertnicza Posejdona. To jest ostateczna baza Enklawy}
{142}{}{Sk¹d ty to wszystko wiesz?}
{143}{}{Co jeszcze dzieje siê tam, na platformie?}
{144}{}{Dziêki. Na razie.}
{145}{}{S³owa siê roznosz¹.}
{146}{}{Rozumiem. Co jeszcze dzieje siê tam, na platformie?}
{147}{}{Rozumiem. Do zobaczenia.}
{148}{}{Nie mam pojêcia. By³em technikiem w Navarro, a nie operatorem na platformie. Rozmawialiœmy tylko przez linie komunikacyjne... To tyle, je¿eli chodzi o nasz kontakt.}
{149}{}{Rozumiem. Jeszcze raz, jak siê p³ywa tym statkiem?}
{150}{}{Dziêki. Na razie.}
{151}{}{To du¿y b³¹d zadzieraæ z Kapitanem i jego przyjació³mi...}
{152}{}{How do you pilot this rig? Well, I see you already gassed her up. When you've taken care of everything else, just press the button. The computer will take care of the rest, if it's still working. It'll sail right out to the oil rig, and they won't fire at you because you've got the IFF transponder. Just make sure you've got what you need to access everything: FOB, working computer, and fuel. Easy enough, huh?}
{153}{}{Oh, yeah. You gotta get the navigation computer working as well.  I bet you'd find parts for it in one of those old vaults.}
{154}{}{Dobrze ciê znowu widzieæ. Czego potrzebujesz?}
{155}{}{, i o ile siê nie mylê, tam te¿ s¹ twoi przyjaciele.}
{156}{}{.}
