{100}{}{Widzisz kogoœ nosz¹cego kapitañsk¹ czapkê.}
{101}{}{To Kapitan A. Ron Meyers.}
{102}{}{Widzisz punka w znoszonym ubraniu nosz¹cego kapitañsk¹ czapkê.}
{103}{}{Czego do cholery chcesz? Nie rozmawiam z nikim, chyba ¿e to przyjaciele albo dobrzy ludzie. Zrób coœ dla jednego z moich kumpli, a wtedy mo¿esz przyjœæ i porozmawiaæ.}
{104}{}{[dalej]}
{105}{}{S³ysza³em o twojej pomocy dla moich ludzi. Dziêkujê. Jak mogê ci pomóc?}
{106}{}{Kto twoja?}
{107}{}{Podobny ty jesteœ tym, kto wie wszystko o tym statku.}
{108}{}{Dlaczego nazywaj¹ ciê Kapitanem?}
{109}{}{Jak ten okrêt wprawiæ w ruch?}
{110}{}{W ¿aden sposób.}
{111}{}{Jestem Kapitanem. Dowodzê tym statkiem. Inne pytania mo¿esz iœæ zadaæ któremuœ z Shi, Borsukowi lub komuœ innemu. Ja nie mam dla ciebie czasu.}
{112}{}{[dalej]}
{113}{}{Tan statek to tankowiec Posejdona. Wyposa¿ony jest w technikê, która przetrwa³a wojnê. Posiada KD, która pozwala na dostêp do pokoju nawigacji komputerowej, i transponder IFF, który broni go przed dzia³ami Posejdona.}
{114}{}{Sk¹d to wszystko wiesz?}
{115}{}{Co to jest transponder IFF?}
{116}{}{Jak go wprawiæ w ruch?}
{117}{}{Dziêki. Na razie.}
{118}{}{Kiedyœ s³u¿y³em w Enklawie. Potem zrozumia³em, ¿e to nie dla USA walczê, lecz dla bogatych, starych drani, którzy nie chc¹ oddaæ swojej w³adzy. Zdezerterowa³em i ¿yjê teraz z bardziej uczciwymi ludŸmi.}
{119}{}{Bardziej uczciwymi? Tymi tutaj?}
{120}{}{Co to dok³adnie jest ta Enklawa?}
{121}{}{Jak uruchomiæ ten statek?}
{122}{}{Na razie.}
{123}{}{Jak pilotowaæ tê krypê? Nalej do pe³na paliwa - spróbuj u Centrologów lub u Shi po tym, jak ju¿ wszystko inne bêdzie za³atwione - i naciœnij guzik. Reszt¹ zajmie siê ju¿ komputer, je¿eli wci¹¿ dzia³a. Pop³ynie prosto do platformy wiertniczej, a oni nie bêd¹ strzelaæ, bo masz transponder IFF. Upewnij siê tylko, ¿e masz wszystko, co jest ci potrzebne: KD, dzia³aj¹cy komputer i paliwo. Proste, nie?}
{124}{}{Jasne. Sk¹d to wszystko wiesz?}
{125}{}{Co to jest transponder IFF i KD?}
{126}{}{Jakiej platformy wiertniczej?}
{127}{}{Tak. Na razie.}
{128}{}{IFF: Identyfikacja Friend or Foe - Przyjaciel czy Wróg. Oznacza to, ¿e ten statek jest rozpoznawany jako przyjaciel, wiêc inne jednostki Posejdona - jak na przyk³ad platforma wiertnicza - nie bêd¹ strzelaæ do ciebie, gdy ju¿ znajdziesz siê w ich zasiêgu. Aha, no i KD to taka technologia Enklawy, która pozwala ci otwieraæ elektronicznie drzwi za pomoc¹ karty. Zapewne takie coœ mo¿na by znaleŸæ w jednej z ich baz, czy w podobnym miejscu.}
{129}{}{Sk¹d to wszystko wiesz?}
{130}{}{Jaka platforma wiertnicza?}
{131}{}{Dziêki. Na razie.}
{132}{}{Tak. Z tymi ludŸmi przynajmniej wiesz dok³adnie, na czym stoisz. Oni nie bawi¹ siê w ró¿ne gierki. Enklawa przypomina stado hien - w sekundê obróciliby siê przeciwko tobie.}
{133}{}{Co to dok³adnie jest ta Enklawa?}
{134}{}{Jak siê do nich przy³¹czy³eœ?}
{135}{}{Enklawa to pozosta³oœæ po starych czasach. Je¿eli zabierzesz tê ³ajbê przez wodê na platformê, to zobaczysz na w³asne oczy, o czym mówiê.}
{136}{}{Jak siê ni¹ p³ywa?}
{137}{}{Jak¹ platformê?}
{138}{}{Doœæ ³atwo. Po prostu pewnego dnia opuœci³em bazê w Navarro i skierowa³em siê tutaj. Pomyœla³em sobie, ¿e to jest ostatnie miejsce, gdzie ktokolwiek by mnie szuka³. A poza tym nie jestem a¿ tak wa¿ny dla Enklawy, ¿eby mnie szukaæ - po co marnowaæ si³y na zbuntowan¹ p³otkê.}
{139}{}{Co to dok³adnie jest ta Enklawa?}
{140}{}{Dziêki. Na razie.}
{141}{}{Kawa³ od brzegu znajduje siê du¿a platforma wiertnicza Posejdona. To jest ostateczna baza Enklawy i, je¿eli siê nie mylê, tam te¿ s¹ twoi przyjaciele.}
{142}{}{Sk¹d to wszystko wiesz?}
{143}{}{Co jeszcze dzieje siê tam, na platformie?}
{144}{}{Dziêki. Na razie.}
{145}{}{S³owa siê roznosz¹.}
{146}{}{Rozumiem. Co jeszcze dzieje siê tam, na platformie?}
{147}{}{Ach tak. Na razie.}
{148}{}{Nie mam pojêcia. By³em technikiem w Navarro, a nie operatorem na platformie. Rozmawialiœmy tylko przez linie komunikacyjne... To tyle, je¿eli chodzi o nasz kontakt.}
{149}{}{Rozumiem. Jeszcze raz, jak siê p³ywa tym statkiem?}
{150}{}{Dziêki. Na razie.}
{151}{}{To du¿y b³¹d zadzieraæ z Kapitanem i jego przyjació³mi...}
{152}{}{Jak siê pilotuje tê krypê? Có¿, widzê, ¿e ju¿ ma pe³ne zbiorniki. Gdy ju¿ zajmiesz siê wszystkim innym, po prostu naciœnij przycisk. Reszt¹ zajmie siê ju¿ komputer, je¿eli wci¹¿ dzia³a. Pop³ynie prosto do platformy wiertniczej, a oni nie bêd¹ strzelaæ, bo masz transponder IFF. Upewnij siê tylko, ¿e oprócz paliwa masz wszystko, co jest ci potrzebne: KD i dzia³aj¹cy komputer. Proste, nie?}
{153}{}{A tak. Musisz jeszcze zmusiæ komputer nawigacyjny do dzia³ania. Za³o¿ê siê, ¿e znajdziesz czêœci do niego w jednej z tych starych krypt.}
{154}{}{Dobrze ciê znowu widzieæ. Czego potrzebujesz?}
