{100}{}{Widzisz kobietę o zatroskanej minie.}
{101}{}{Widzisz Suze.}
{102}{}{Widzisz kobietę o zatroskanej minie.}
{103}{}{Aaaaaa! Ratunku!}
{104}{}{Ocal mnie! Proszę!}
{105}{}{Próbują mnie zabić!}
{106}{}{Proszą! Zabiją mnie!}
{107}{}{Powstrzymaj je! Aaaaa!}
{108}{}{Czy to Borsuk cię przysłał? Wiedziałam, że tak zrobi. Kamień spadł mi z serca.}
{109}{}{Aaggg.}
{110}{}{Co tu robiłaś?}
{111}{}{Ta. Idź za mną.}
{112}{}{Och, moje ty biedne. Radiacja i pustkowia nie są miłe, prawda? Mam nadzieję, że ktoś będzie mógł ci pomóc.}
{113}{}{Wiesz, to trochę głupie. Zwiedzałam sobie, bo Borsuk był zajęty komputerem. Poszłam na dół, zgubiłam się, a zaraz potem otoczyły mnie potwory. Dobrze, że tu jesteś.}
{114}{}{Mam więcej pytań.}
{115}{}{Tak, to prawda. Znalazłaś coś ciekawego?}
{116}{}{Tak masz rację. Chodźmy.}
{117}{}{I found the room I was in. I also found a room that looked like a fueling area.  I didn't get much farther because of the monsters.}
{118}{}{Mam więcej pytań.}
{119}{}{Skąd jesteś?}
{120}{}{Super. Na razie to wszystko.}
{121}{}{I'm from a place south of the Boneyard and south of the Glow. We're not too far from the sea.  I used to be a nanny, but then the kids mutated into monsters.}
{122}{}{Mam więcej pytań.}
{123}{}{Jak poznałaś Borsuka?}
{124}{}{Fascynujące. To na razie wszystko.}
{125}{}{Przybył na południe i zajrzał do klubu, do którego i ja zwykłam chadzać. Więc kiedy sprawy zaczęły marnie wyglądać, pomyślałam, że to będzie dobre miejsce na mój nowy dom.}
{126}{}{Mam więcej pytań.}
{127}{}{To wszystko. Dzięki.}
{128}{}{Zawdzięczam ci życie. Odpowiem na wszystkie twoje pytania.}
{129}{}{Taaa.}
{130}{}{Co tu robiłaś?}
{131}{}{Czy znalazłaś coś ciekawego?}
{132}{}{Skąd jesteś?}
{133}{}{Jak poznałaś Borsuka?}
{134}{}{Na razie nie mam żadnych. Na razie.}
{135}{}{Oh my god... Badger is dead ... I don't know what I'll do... I haven't got any friends here... all my family is dead... oh my god...}
{136}{}{Dzięki za całą okazaną pomoc. Idę poszukać Borsuka.}
