{100}{}{Widzisz terminal komputerowy.}
{101}{}{Widzisz terminal Cesarskiego Komputera.}
{102}{}{Widzisz komputer z wbudowanym ekranem dotykowym. Na boku wyryto napis - "Terminal komputerowy - Cesarz v8.8".}
{103}{}{Witaj. Podaj hasło, aby potwierdzić swoją tożsamość.}
{104}{}{::ślinisz się::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{[Włam się do komputera.]}
{109}{}{Wyloguj się.}
{110}{}{Tożsamość potwierdzona.}
{111}{}{Do której funkcji chcesz mieć dostęp?}
{112}{}{Diagnostyka.}
{113}{}{Baza danych.}
{114}{}{Prognozy.}
{115}{}{Nic.}
{116}{}{Prosze skontaktować się z administratorem systemu. Do widzenia.}
{117}{}{[Włam się do komputera.]}
{118}{}{[Odejdź.]}
{119}{}{Intruz wykryty, alarm aktywowany. Wyłączenie systemu. Miłego dnia życzę.}
{120}{}{[dalej]}
{121}{}{Funkcje diagnostyczne?}
{122}{}{Skanowanie sieci.}
{123}{}{Formatowanie twardego dysku.}
{124}{}{Sprawdz spójność dysku.}
{125}{}{Wróć.}
{126}{}{Którą bazę pragniesz przeszukać?}
{127}{}{Biologii.}
{128}{}{Chemii.}
{129}{}{Fizyki.}
{130}{}{Historii.}
{131}{}{Wróć.}
{132}{}{Dzieci miasta Shi są w niebezpieczenstwie. 50% szans, że wsród nich porusza się morderca.}
{133}{}{Miasto Shi w niebezpieczenstwie. 75% szans na skrzywdzenie mieszkanców.}
{134}{}{Wystrzelenie statku kosmicznego Centrologów oceniane na 95% porażki. Czynniki: brak paliwa, niewłaściwe uszczelnienie, kiepskie dowodzenie, brak inicjatywy.}
{135}{}{15% szans na powodzenie misji obiektu "Dziecko Przeznaczenia".}
{136}{}{Wprowadzone dane wskazują na to, że "Enklawa" jest potężniejsza, niż początkowo przypuszczano: nie dokonywać kontaktu.}
{137}{}{Szansa na ponowne ukazanie się łodzi podwodnej w tej grze: 0%.}
{138}{}{Włóczędzy z tankowca mają 0% szans na oczyszczenie statku z wrażych istot bez pomocy z zewnątrz. Obliczanie pożądania udzielenia pomocy w toku.}
{139}{}{Dane wejściowe: Tankowiec roponośny Posejdon niezdatny do podróży. Wymagane dalsze dane.}
{140}{}{Brak przetwarzania. Wymagane dalsze dane.}
{141}{}{[KONTYNUUJ]}
{142}{}{Wróć.}
{143}{}{Serwer biologiczny: Aktywny}
{144}{}{Serwer biologiczny: Nieaktywny}
{145}{}{Serwer chemiczny: Aktywny}
{146}{}{Serwer chemiczny: Nieaktywny}
{147}{}{Serwer fizyczny: Aktywny}
{148}{}{Serwer fizyczny: Nieaktywny}
{149}{}{Wyłącz serwer biologiczny.}
{150}{}{Wyłącz serwer chemiczny.}
{151}{}{Wyłącz serwer fizyczny.}
{152}{}{Wejdź na serwer biologiczny.}
{153}{}{Wejdź na serwer chemiczny.}
{154}{}{Wejdź na serwer fizyczny.}
{155}{}{Uaktywnij serwer biologiczny.}
{156}{}{Uaktywnij serwer chemiczny.}
{157}{}{Uaktywnij serwer fizyczny.}
{158}{}{Wróć.}
{159}{}{Formatowanie dysku: Wszystkie dane zostaną utracone. Kontynuować?}
{160}{}{Tak.}
{161}{}{Nie.}
{162}{}{Spójność systemu na poziomie 92%. Chronione centrum Cesarskiego Komputera na 100%. Integralność danych na 100%. W systemie prognoz niewielkie zaniki mocy - planowany czas naprawy - 6 dni. Prognozy sprawne w 15%.}
{163}{}{Wróć.}
{164}{}{Czy na pewno chcesz sformatować tę jednostkę? To jest nieodwracalny proces.}
{165}{}{Tak.}
{166}{}{Nie.}
{167}{}{Formatowanie w toku... formatowanie w toku... formatowanie zakończone. Bootowanie wymaga ponownej instalacji. Wyłączam systemy. Zamykanie... systemu... zakończone...}
{168}{}{[dalej]}
{169}{}{Dane do znalezienia: - program botaniczny - program genetyczny - program kseno.}
{170}{}{Program botaniczny.}
{171}{}{Program genetyczny.}
{172}{}{Program kseno.}
{173}{}{Wróć.}
{174}{}{(Po dwudziestu minutach odkrywasz, że początkowe wyniki botanicznego rozpraszania radiacji są nieobiecujące. Dr Sheng wyhodował roślinną formę życia odporną na promieniowanie - z nieprzyjemnymi skutkami ubocznymi. Uzyskana roślinna forma życia uważana jest za zbyt niebezpieczną. Sheng nalega na dalsze badania w tym kierunku i połączenie ich z programem genetycznym.)}
{175}{}{Program genetyczny.}
{176}{}{Program kseno.}
{177}{}{Wróć.}
{178}{}{(Po dwudziestu minutach wyłania ci się przed oczyma następujacy obraz: Używając podstaw wirusa FEV, dr Long Wang jest przekonany o powodzeniu tworzenia zmutowanych żołnierzy. Stwarza serum dające interesujące rezultaty w eksperymentach na gryzoniach. Następnie wstrzykuje je sobie i rozpuszcza się w kałuży mazi. Dr Sheng wstrzymuje dochodzenie. Wraz ze śmiercią dr Longa, dr Sheng zostaje szefem. Sheng domaga się skupienia na pochłaniającej promieniowanie roślinnej formie życia.)}
{179}{}{Program botaniczny.}
{180}{}{Program kseno.}
{181}{}{Wróć.}
{182}{}{"Obiekt, na którym mieliśmy nadzieję przeprowadzić serię znaczących eksperymentów zniknął, zapewne albo zniszczony, albo skradziony przez Centrologów. Dalsze dochodzenie nie przyniosło rezultatów. Do czasu znalezienia dalszych obiektów badań ta baza danych pozostanie nieaktywna." - dr Sheng.}
{183}{}{Program botaniczny.}
{184}{}{Program genetyczny.}
{185}{}{Wróć.}
{186}{}{Chemiczna baza danych: Paliwo i pochodne - Polimery}
{187}{}{Paliwo i pochodne.}
{188}{}{Polimery.}
{189}{}{Wróć.}
{190}{}{(Po przekopaniu się przez złożone wzory chemiczne i notatki laboratoryjne dochodzisz do wniosku, że Shi stworzyli pewien rodzaj paliwa z wyciągu z roślin i organizmów morskich. Wygląda również na to, że przyłączyli się do istniejących już uprzednio rur przesyłowych, dzięki czemu mogą transportować paliwo do szerokiego wachlarza miejsc.)}
{191}{}{(Napotykasz ogromną ilość skomplikowanych formuł chemicznych i notatek laboratoryjnych. Nie masz zbytniej pewności, co to wszystko może znaczyć.)}
{192}{}{Skieruj paliwo do tankowca Posejdon.}
{193}{}{Skieruj paliwo do Centrologów.}
{194}{}{Wróć.}
{195}{}{(Po przebiciu się przez dyskusje techniczne i symbolikę odkrywasz, że Shi pracują nad nowym rodzajem polimerycznego pancerza bojowego, odpornego zarówno na ogień, jak i na przebicie. Miną jednak lata, zanim zostanie ukończony. Widzisz także wzmianki o nowym uzbrojeniu i możliwościach konstrukcyjnych. Najwidoczniej Shi mają jakieś plany na przyszłość.)}
{196}{}{Wróć.}
{197}{}{Paliwo przesłane zgodnie z poleceniem. Zbiorniki paliwa = Puste. Zamykam program.}
{198}{}{[dalej]}
{199}{}{Paliwo przesłane zgodnie z poleceniem. Zbiorniki paliwa = Puste. Zamykam program.}
{200}{}{[dalej]}
{201}{}{Fizyczna baza danych: Badania - Teoria}
{202}{}{Badania.}
{203}{}{Teoria.}
{204}{}{Wróć.}
{205}{}{"Wraz z niedawnym uzyskaniem planów lataczy, możliwość stworzenia praktycznej maszyny latającej przybliżyła się o wiele lat. Oczekujemy stworzenia działającego prototypu do końca tego roku, a możliwości masowej produkcji w ciągu dwóch lat." - dr Wong}
{206}{}{::skopiuj plany:: Wróć.}
{207}{}{Wróć.}
{208}{}{"Wciąż przygotowujemy działający model maszyny latajacej. Żaden z naszych dotychczasowych projektów nie był ani bezpieczny, ani aerodynamiczny. Być może gdybyśmy mieli dostęp do planów naszych przodków..." - dr Wong}
{209}{}{Wróć.}
{210}{}{(Po przejrzeniu wstępu i podstaw matematycznych dowiadujesz się, że Shi uczą się po raz kolejny używać energii atomowej, odbudować teorię lotów kosmicznych starożytnych - i biją w tym Centrologów na głowę - i wykorzystywać energię słońca, wiatru, morza. A przynajmniej tak tam jest napisane.)}
{211}{}{Wróć.}
{212}{}{Serwer uaktywniony.}
{213}{}{Wróć.}
{214}{}{Ten terminal komputerowy nie umie chyba tego obsługiwać.}
{215}{}{Ten terminal komputerowy chyba nie działa.}
{216}{}{Nastąpiło włamanie do systemu. Rozkaz - atakować!}
{217}{}{Atakować intruza!}
{218}{}{Czas zapłacić za swoje czyny, lao wai!}
{219}{}{W naszych szeregach jest zdrajca!}
{220}{}{Geolokalizacja.}
{221}{}{Co/kogo pragniesz zlokalizować?}
{222}{}{Mieszkańców mojej wioski.}
{223}{}{97% szans - Mieszkańcy wioski zlokalizowani w obecnych koordynatach kompleksu Enklawy.}
