#{100}{}{Widzisz potê¿ny komputer.} //This is for the computer object itself
#{101}{}{Widzisz Cesarski Komputer.}
#{102}{}{Widzisz du¿y, szumi¹cy, w pe³ni sprawny komputer, ktry na spodzie obudowy ma napis: "Cesarz v8.8".}
{100}{}{Widzisz terminal komputerowy.}
{101}{}{Widzisz terminal Cesarskiego Komputera.}
{102}{}{Widzisz komputer z wbudowanym ekranem dotykowym. Na boku wyryto napis - "Terminal komputerowy - Cesarz v8.8".}
{103}{}{Witaj. Podaj has³o, aby potwierdziæ swoj¹ to¿samoœæ.}
{104}{}{::œlinisz siê::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{::w³am siê do komputera::}
{109}{}{Wyloguj siê.}
{110}{}{To¿samoœæ potwierdzona.}
{111}{}{Do której funkcji chcesz mieæ dostêp?}
{112}{}{Diagnostyka.}
{113}{}{Baza danych.}
{114}{}{Prognozy.}
{115}{}{Nic.}
{116}{}{Prosze skontaktowaæ siê z administratorem systemu. Do widzenia.}
{117}{}{::w³am siê do systemu::}
{118}{}{::wyjdŸ::}
{119}{}{Intruz wykryty - uruchomiono alarm. Wy³¹czam siê. Mi³ego dnia.}
{120}{}{[Dalej]}
{121}{}{Funkcje diagnostyczne?}
{122}{}{Skanowanie sieci.}
{123}{}{Formatowanie twardego dysku.}
{124}{}{Sprawdz spójnoœæ dysku.}
{125}{}{Wróæ.}
{126}{}{Któr¹ bazê pragniesz przeszukaæ?}
{127}{}{Biologii.}
{128}{}{Chemii.}
{129}{}{Fizyki.}
{130}{}{Historii.}
{131}{}{Wróæ.}
{132}{}{Dzieci miasta Shi s¹ w niebezpieczenstwie. 50% szans, ¿e wsród nich porusza siê morderca.}
{133}{}{Miasto Shi w niebezpieczenstwie. 75% szans na skrzywdzenie mieszkanców.}
{134}{}{Wystrzelenie statku kosmicznego Centrologów oceniane na 95% pora¿ki. Czynniki: brak paliwa, niew³aœciwe uszczelnienie, kiepskie dowodzenie, brak inicjatywy.}
{135}{}{15% szans na powodzenie misji obiektu o kryptonimie "Dziecko Przeznaczenia".}
{136}{}{Wprowadzone dane wskazuj¹ na to, ¿e "Enklawa" jest potê¿niejsza, ni¿ pocz¹tkowo przypuszczano: nie dokonywaæ kontaktu.}
{137}{}{Szansa na ponowne ukazanie siê ³odzi podwodnej w tej grze: 0%.}
{138}{}{W³óczêdzy z tankowca maj¹ 0% szans na oczyszczenie statku z wra¿ych istot bez pomocy z zewn¹trz. Obliczanie po¿¹dania udzielenia pomocy w toku.}
{139}{}{Dane wejœciowe: Tankowiec roponoœny Posejdon niezdatny do podró¿y. Wymagane dalsze dane.}
{140}{}{Brak przetwarzania. Wymagane dalsze dane.}
{141}{}{[Dalej]}
{142}{}{Wróæ.}
{143}{}{Serwer biologiczny: Aktywny}
{144}{}{Serwer biologiczny: Nieaktywny}
{145}{}{Serwer chemiczny: Aktywny}
{146}{}{Serwer chemiczny: Nieaktywny}
{147}{}{Serwer fizyczny: Aktywny}
{148}{}{Serwer fizyczny: Nieaktywny}
{149}{}{Wy³¹cz serwer biologiczny.}
{150}{}{Wy³¹cz serwer chemiczny.}
{151}{}{Wy³¹cz serwer fizyczny.}
{152}{}{WejdŸ na serwer biologiczny.}
{153}{}{WejdŸ na serwer chemiczny.}
{154}{}{WejdŸ na serwer fizyczny.}
{155}{}{Uaktywnij serwer biologiczny.}
{156}{}{Uaktywnij serwer chemiczny.}
{157}{}{Uaktywnij serwer fizyczny.}
{158}{}{Wróæ.}
{159}{}{Formatowanie dysku: Wszystkie dane zostan¹ utracone. Kontynuowaæ?}
{160}{}{Tak.}
{161}{}{Nie.}
{162}{}{Spójnoœæ systemu na poziomie 92%. Chronione centrum Cesarskiego Komputera na 100%. Integralnoœæ danych na 100%. W systemie prognoz niewielkie zaniki mocy - planowany czas naprawy - 6 dni. Prognozy sprawne w 15%.}
{163}{}{Wróæ.}
{164}{}{Czy na pewno chcesz sformatowaæ tê jednostkê? To jest nieodwracalny proces.}
{165}{}{Tak.}
{166}{}{Nie.}
{167}{}{Formatowanie w toku... formatowanie w toku... formatowanie zakoñczone. Bootowanie wymaga ponownej instalacji. Wy³¹czam systemy. Zamykanie... systemu... zakoñczone...}
{168}{}{[Dalej]}
{169}{}{Dane do znalezienia: - program botaniczny - program genetyczny - program ksenotyczny.}
{170}{}{Program botaniczny.}
{171}{}{Program genetyczny.}
{172}{}{Program ksenotyczny.}
{173}{}{Wróæ.}
{174}{}{(Po dwudziestu minutach odkrywasz, ¿e pocz¹tkowe wyniki zak³ócania radiacji botanicznej s¹ nieobiecuj¹ce. Dr Sheng wyhodowa³ roœlinn¹ formê ¿ycia odporn¹ na promieniowanie - z nieprzyjemnymi skutkami ubocznymi. Uzyskana roœlinna forma ¿ycia uwa¿ana jest za zbyt niebezpieczn¹. Sheng nalega na dalsze badania w tym kierunku i po³¹czenie ich z programem genetycznym.)}
{175}{}{Program genetyczny.}
{176}{}{Program ksenotyczny.}
{177}{}{Wróæ.}
{178}{}{(Po dwudziestu minutach wy³ania ci siê przed oczyma nastêpujacy obraz: U¿ywaj¹c podstaw wirusa FEV, dr Long Wang jest przekonany o powodzeniu tworzenia zmutowanych ¿o³nierzy. Stwarza serum daj¹ce interesuj¹ce rezultaty w eksperymentach na gryzoniach. Nastêpnie wstrzykuje je sobie i rozpuszcza siê w ka³u¿y mazi. Dr Sheng wstrzymuje dochodzenie. Wraz ze œmierci¹ dr Longa, dr Sheng zostaje szefem. Sheng domaga siê skupienia na poch³aniaj¹cej promieniowanie roœlinnej formie ¿ycia.)}
{179}{}{Program botaniczny.}
{180}{}{Program ksenotyczny.}
{181}{}{Wróæ.}
{182}{}{"Obiekt, na którym mieliœmy nadziejê przeprowadziæ seriê znacz¹cych eksperymentów znikn¹³, zapewne albo zniszczony, albo skradziony przez Centrologów. Dalsze dochodzenie nie przynios³o rezultatów. Do czasu znalezienia dalszych obiektów badañ ta baza danych pozostanie nieaktywna." - dr Sheng}
{183}{}{Program botaniczny.}
{184}{}{Program genetyczny.}
{185}{}{Wróæ.}
{186}{}{Chemiczna baza danych: Paliwo i pochodne - Polimery}
{187}{}{Paliwo i pochodne.}
{188}{}{Polimery.}
{189}{}{Wróæ.}
{190}{}{(Po przekopaniu siê przez z³o¿one wzory chemiczne i notatki laboratoryjne dochodzisz do wniosku, ¿e Shi stworzyli rodzaj paliwa z wyci¹gu z roslin i organizmów morskich. Wygl¹da równie¿ na to, ¿e przy³¹czyli siê do istniej¹cych ju¿ uprzednio ruroci¹gów, dziêki czemu mog¹ transportowaæ paliwo do wielu miejsc.)}
{191}{}{(Napotykasz ogromn¹ iloœæ skomplikowanych formu³ chemicznych i notatek laboratoryjnych. Nie masz zbytniej pewnoœci, co to wszystko mo¿e znaczyæ.)}
{192}{}{Skieruj paliwo do tankowca Posejdon.}
{193}{}{Skieruj paliwo do Centrologów.}
{194}{}{Wróæ.}
{195}{}{(Po przebiciu siê przez dyskusje techniczne i symbolikê odkrywasz, ¿e Shi pracuj¹ nad nowym rodzajem polimerycznego pancerza bojowego, odpornego zarówno na ogieñ, jak i na przebicie. Min¹ jednak lata, zanim zostanie ukoñczony. Widzisz tak¿e wzmianki o nowym uzbrojeniu i mo¿liwoœciach konstrukcyjnych. Najwidoczniej Shi maj¹ jakieœ plany na przysz³oœæ.)}
{196}{}{Wróæ.}
{197}{}{Paliwo przekierowane zgodnie z planem. Zbiorniki puste. Zamykam program.}
{198}{}{[Dalej]}
{199}{}{Paliwo przekierowane zgodnie z planem. Zbiorniki puste. Zamykam program.}
{200}{}{[Dalej]}
{201}{}{Fizyczna baza danych: Badania - Teoria}
{202}{}{Badania.}
{203}{}{Teoria.}
{204}{}{Wróæ.}
{205}{}{"Wraz z niedawnym uzyskaniem planów lataczy, mo¿liwoœæ stworzenia praktycznej maszyny lataj¹cej przybli¿y³a siê o wiele lat. Oczekujemy stworzenia dzia³aj¹cego prototypu do koñca tego roku, a mo¿liwoœci masowej produkcji w ci¹gu dwóch lat." - dr Wong}
{206}{}{::skopiuj plany:: Wróæ.}
{207}{}{Wróæ.}
{208}{}{"Wci¹¿ przygotowujemy dzia³aj¹cy model maszyny latajacej. ¯aden z naszych dotychczasowych projektów nie by³ ani bezpieczny, ani aerodynamiczny. Byæ mo¿e gdybyœmy mieli dostêp do planów naszych przodków..." - dr Wong}
{209}{}{Wróæ.}
{210}{}{(Po przejrzeniu wstêpu i podstaw matematycznych dowiadujesz siê, ¿e Shi ucz¹ siê od nowa u¿ywaæ energii atomowej, odbudowuj¹ teoriê lotów kosmicznych staro¿ytnych - i bij¹ w tym Centrologów na g³owê - wykorzystywaæ energiê s³oñca, wiatru, morza. A przynajmniej tak tam jest napisane.)}
{211}{}{Wróæ.}
{212}{}{Serwer uaktywniony.}
{213}{}{Wróæ.}
{214}{}{Ten terminal komputerowy nie umie chyba tego obs³ugiwaæ.}
{215}{}{Ten terminal komputerowy chyba nie dzia³a.}

{216}{}{Nast¹pi³o w³amanie do systemu. Rozkaz - atakowaæ!}
{217}{}{Atakowaæ intruza!}
{218}{}{Czas zap³aciæ za swoje czyny, lao wai!}
{219}{}{W naszych szeregach jest zdrajca!}

{220}{}{Geolokalizacja.}
{221}{}{Co/kogo pragniesz zlokalizowaæ?}
{222}{}{Mieszkañców mojej wioski.}
{223}{}{97% szans - Mieszkañcy wioski zlokalizowani w obecnych koordynatach kompleksu Enklawy.}
