{100}{}{Widzisz szczupłego mężczyznę o wyglądzie budzącym sympatię.}
{101}{}{Widzisz Chada, karawaniarza.}
{102}{}{Widzisz szczupłego mężczyznę, który uśmiecha się tak, jakby uśmiech ten miał służyć za tarczę. Nosi niczym nie wyróżniające się ubrania i trzyma się jak ktoś, kto wie co robi.}
{120}{}{Witaj! Co mogę dla ciebie zrobić?}
{121}{}{Więcej pytań? Zobaczmy, czy uda mi się odpowiedzieć.}
{122}{}{Diirk diigler!}
{123}{}{Ty kto?}
{124}{}{Marcus pytał o ciebie.}
{125}{}{There's enough evidence that you've been stealing money that's supposed to go to Broken Hills
 that you can be arrested. You're going down.}
{126}{}{There's enough evidence that you've been stealing money that's supposed to go to Broken Hills
 that you can be arrested. Cut me in for $1000 and I'll make sure you can flee town.}
{127}{}{Kim jesteś?}
{128}{}{Opowiedz mi o tym miejscu.}
{129}{}{Nic takiego. Na razie.}
{130}{}{Zobaczcie, co tu przywiało z pustkowi! Przykro mi, nie umiem ci pomóc.}
{131}{}{Po razie!}
{132}{}{Jestem Chad. }
{133}{}{Słuchaj, jestem bardzo zajęty. Proszę, idź poprzeszkadzać komuś innemu.}
{134}{}{I'm the caravan master for the city. I take care of the business on the other end of the trade
 routes. These days I'm focusing primarily on Gecko. }
{135}{}{Oki!}
{136}{}{Chcę zdobyć u ciebie pracę.}
{137}{}{Fascynujące.}
{138}{}{Ale nudy.}
{139}{}{Mam więcej pytań.}
{140}{}{Dzięki. Na razie.}
{141}{}{Opowiedzieć ci o Broken Hills? Cóż... Przeprowadziłem się tu kilka lat temu. Dostałem pracę u Billa --
 to nasz Zaopatrzeniowiec -- i przeniosłem się tu, gdzie żyję do dzisiaj. Jestem podwładnym Marcusa i Billa, ale
 odpowiadam za utrzymanie miasta.}
{142}{}{Mam więcej pytań.}
{143}{}{Bywaj.}
{144}{}{Na przykład?}
{145}{}{He suspects, that you are skimming the money that's supposed to go Broken Hills.}
{146}{}{Właściwie to nic. Cześć.}
{147}{}{Look, I don't like people to accuse me about something that I don't know anything about. I suggest that you leave.}
{150}{}{I'm going to find the truth. Bye.}
{156}{}{Porozmawiaj z Billem. On ci pomoże.}
{157}{}{Mam więcej pytań.}
{158}{}{Dzięki. Na razie.}
{159}{}{O tak. Pewnie nie przyszłoby ci to do głowy, ale dzięki temu dużo podróżuję i zwiedzam cały świat... i czuję, że robię coś pożytecznego dla miasta. To dobre życie.}
{160}{}{Brzmi świetnie. Miło byłoby mieć taką pracę.}
{161}{}{Właściwie wydaje mi się to dosyć nudne.}
{162}{}{Mam więcej pytań.}
{163}{}{Bywaj.}
{164}{}{Pewnie i tak jest dużo bardziej fascynujące niż twój tryb życia, palancie.}
{165}{}{Niech ci będzie. Mam więcej pytań.}
{166}{}{Ha ha ha ha! Jasne. Bywaj zdrów, ofiaro losu.}
{167}{}{Któregoś dnia za to zapłacisz, pacanie.}
{168}{}{Nie chcę cię więcej widzieć.}
{169}{}{Naprawdę nie wyszło ci z tą karawaną. To tyle, jeśli chodzi o twoje pieniądze.}
{170}{}{Nie ma co, to się nazywa spieprzyć robotę. Życzę szczęścia w szukaniu pracy przy jakiejkolwiek naszej karawanie.}
{171}{}{Dobra robota. Oto twoje 200$.}
{172}{}{Zmiataj stąd. Nie chcemy już twojej pomocy.}
{173}{}{Miej oczy szeroko otwarte.}
{174}{}{Będę pilnować twoich tyłów.}
{175}{}{Nie pozwól draniom cię zaskoczyć.}
