{100}{}{Widzisz szczup³ego mê¿czyznê o wygl¹dzie budz¹cym sympatiê.}
{101}{}{Widzisz Chada, karawaniarza.}
{102}{}{Widzisz szczup³ego mê¿czyznê, który uœmiecha siê tak, jakby uœmiech ten mia³ s³u¿yæ za tarczê. Nosi niczym nie wyró¿niaj¹ce siê ubrania i trzyma siê jak ktoœ, kto wie co robi.}
{120}{}{Witaj! Co mogê dla ciebie zrobiæ?}
{121}{}{Wiêcej pytañ? Zobaczmy, czy uda mi siê odpowiedzieæ.}
{122}{}{Diirk diigler!}
{123}{}{Ty kto?}
{124}{}{Marcus pyta³ o ciebie.}
{125}{}{There's enough evidence that you've been stealing money that's supposed to go to Broken Hills
 that you can be arrested. You're going down.}
{126}{}{There's enough evidence that you've been stealing money that's supposed to go to Broken Hills
 that you can be arrested. Cut me in for $1000 and I'll make sure you can flee town.}
{127}{}{Kim jesteœ?}
{128}{}{Opowiedz mi o tym miejscu.}
{129}{}{Niczego. Czeœæ.}
{130}{}{Zobaczcie, co tu przywia³o z pustkowi! Przykro mi, nie umiem ci pomóc.}
{131}{}{Po razie!}
{132}{}{Jestem Chad. }
{133}{}{S³uchaj, jestem bardzo zajêty. Proszê, idŸ poprzeszkadzaæ komuœ innemu.}
{134}{}{I'm the caravan master for the city. I take care of the business on the other end of the trade
 routes. These days I'm focusing primarily on Gecko. }
{135}{}{D’obra!}
{136}{}{Chcê zdobyæ u ciebie pracê.}
{137}{}{Fascynuj¹ce.}
{138}{}{Ale nudy.}
{139}{}{Mam wiêcej pytañ.}
{140}{}{Dziêki. Pa.}
{141}{}{Tell you about Broken Hills? Well... I moved here a few years back. Got a job with the Bill --
 that's the Outfitter -- and moved up to where I am now. I report to Marcus and the Bill, but I'm
 responsible for the livelihood of the town.}
{142}{}{Mam wiêcej pytañ.}
{143}{}{Pa.}
{144}{}{Jak co?}
{145}{}{He suspects, that you are skimming the money that's supposed to go Broken Hills.}
{146}{}{W³aœciwie to nic. Czeœæ.}
{147}{}{Look, I don't like people to accuse me about something that I don't know anything about. I suggest that you leave.}
{150}{}{I'm going to find the truth. Bye.}
{156}{}{Porozmawiaj z Billem. On ci pomo¿e.}
{157}{}{Mam wiêcej pytañ.}
{158}{}{Dziêki. Pa.}
{159}{}{O tak. Pewnie nie przysz³oby ci to do g³owy, ale dziêki temu du¿o podró¿ujê i zwiedzam ca³y œwiat... i czujê, ¿e robiê coœ po¿ytecznego dla miasta. To dobre ¿ycie.}
{160}{}{Brzmi œwietnie. Mi³o by³oby mieæ tak¹ pracê.}
{161}{}{W³aœciwie wydaje mi siê to dosyæ nudne.}
{162}{}{Mam wiêcej pytañ.}
{163}{}{Pa.}
{164}{}{Pewnie i tak jest du¿o bardziej fascynuj¹ce ni¿ twój tryb ¿ycia, palancie.}
{165}{}{Niech ci bêdzie. Mam wiêcej pytañ.}
{166}{}{Ha ha ha ha! Jasne. Bywaj zdrów, ofiaro losu.}
{167}{}{Któregoœ dnia za to zap³acisz, pacanie.}
{168}{}{Nie chcê ciê wiêcej widzieæ.}
{169}{}{Naprawdê nie wysz³o ci z t¹ karawan¹. To tyle, jeœli chodzi o twoje pieni¹dze.}
{170}{}{Nie ma co, to siê nazywa spieprzyæ robotê. ¯yczê szczêœcia w szukaniu pracy przy jakiejkolwiek naszej karawanie.}
{171}{}{Dobra robota. Oto twoje 200$.}
{172}{}{Zmiataj st¹d. Nie chcemy ju¿ twojej pomocy.}
{173}{}{Miej oczy szeroko otwarte.}
{174}{}{Bêdê pilnowaæ twoich ty³ów.}
{175}{}{Nie pozwól draniom ciê zaskoczyæ.}
