{100}{}{Widzisz zatroskanego mężczyznę.}
{101}{}{Widzisz Dana, jest bardzo zatroskany.}
{102}{}{Widzisz dobrze ubranego mężczyznę. Jego twarz wskazuje na to, że jest na skraju histerii.}
{103}{}{Kim jesteś? Co robisz w moim domu?}
{104}{}{Ack? Oop?}
{105}{}{Jestem }
{106}{}{Nikim ważnym.}
{107}{}{Jestem tu, aby cię okraść.}
{108}{}{Nic. Nikim. Żegnam.}
{109}{}{Proszę, nie w moim domu. Na zewnątrz jest ulica, na której możesz robić sobie wszystko, co tacy "szczególni" ludzie robią.}
{110}{}{Thppt!}
{111}{}{Wspaniale, wspaniale. Miło mi cię poznać. [Zastanawia się chwilę] Hej, słuchaj... jesteś typem poszukiwacza, prawda?}
{112}{}{Tak.}
{113}{}{Nie rozpoznajesz Dziecka Przeznaczenia?}
{114}{}{Nie.}
{115}{}{A dlaczego tak cię to interesuje?}
{116}{}{The reason I ask,  you see, is because my wife is missing. I don't know where she is. She's been gone for days. I've asked around town, and no one has seen her. Can you find her for me?}
{117}{}{Co będę z tego mieć?}
{118}{}{Rozejrzę się. Jak ona wygląda?}
{119}{}{Nie ma mowy. Mam dużo spraw na głowie.}
{120}{}{Dam ci 500$. To wszystkie moje oszczędności.}
{121}{}{To wystarczy. Zrobię to.}
{122}{}{Nie. Nic z tego.}
{123}{}{Proszę. Błagam. Moja żona... ona jest dla mnie wszystkim. Proszę.}
{124}{}{Nie!}
{125}{}{Fine. Fine, just stop pestering me.}
{126}{}{Here's the money. Now please, please, PLEASE... find my wife and tell me where she is. Maybe she's shacked up with someone else, maybe she's left me... but I just need to know.	}
{127}{}{Masz to jak w banku, koleś. Jak ona wygląda?}
{128}{}{Oczywiście. Zrobię, co w mojej mocy.}
{129}{}{::he sobs uncontrollably for a few moments:: Very well. Go away. And realize that you've broken my heart.    }
{130}{}{No to na razie, frajerze.}
{131}{}{Jest wysoką, seksowną blondynką o najwspanialszym głosie, jaki kiedykolwiek słyszałem... Ostatnio widziano ją spacerującą w tej okolicy. Nigdy nie lubiła mutantów i ghuli, więc raczej nie będzie w okolicy ich domów. Nikt nie wie, gdzie poszła. To tak, jakby po prostu zniknęła.}
{132}{}{To mi wystarczy.}
{133}{}{No i? Udało ci się ją odnaleźć? Moje serce boli mocniej z każdą chwilą.}
{134}{}{Przykro mi - ciągle szukam.}
{135}{}{Tak, wiem gdzie jest.}
{136}{}{Nie, jeszcze nie. Ciągle szukam.}
{137}{}{Och, moje biedne serce. Proszę, daj mi znać, gdy ją znajdziesz.}
{138}{}{Jasne, oczywiście.}
{139}{}{Właściwie, już mi się znudziło szukanie twojej laski.}
{140}{}{Wiesz gdzie jest? [Dostrzegasz nadzieję w jego wzroku] Gdzie?}
{141}{}{Czy to była taka laska bez nóg?}
{142}{}{W tunelach pod miastem jest grupka martwych osób. Twoja żona jest wśród nich. Przykro mi.}
{143}{}{Co? Nie! Miała fantastyczne nogi!}
{144}{}{Oh. Right. Well, she hasn't got great legs now. She really got savaged, and her legs are OFF. She's totally dead, and she suffered before she died.	}
{145}{}{Jasne. Cóż, myślę, że wiem, gdzie jest. Leży pośród ciał w tunelach pod miastem. Ona nie żyje. Strasznie mi przykro.}
{146}{}{Dzięki za informację. Teraz, jeśli pozwolisz, muszę się iść wypłakać.}
{147}{}{Taa, idź sobie płakać, ty lalusiu.}
{148}{}{Przykro mi, stary.}
{149}{}{Nienawidzę cię! Wszyscy cię nienawidzą! Najlepiej umrzyj! [płacz]}
{150}{}{Przy jej ciele był list. Wynika z niego, że była w grupie planującej wymordowanie mutantów w Broken Hills.}
{151}{}{O mój Boże! Ja... Ja nie wierzę, że... To po prostu nie... [Głęboko wzdycha] To, co mówisz, może być niestety prawdą. Już wcześniej nienawidziła każdego mutanta i ghula, jakiego spotkała. Nie wiem dlaczego.}
{152}{}{To wszystko prawda - ale pomyśl. Morderstwa mogą nie skończyć się na twojej żonie. Jeśli zabili ją - mogą też chcieć zabić ciebie.}
{153}{}{Chyba nie chcesz powiedzieć, że moje życie jest w niebezpieczeństwie? O Boże. Możesz mieć rację. Ostatniej nocy słyszałem jakieś szepty i szuranie dookoła domu.}
{154}{}{Opuszczenie miasta może być w tej sytuacji jedynym rozwiązaniem. Uważaj na siebie. Powodzenia.}
{155}{}{Dzięki za pomoc. Zostanę tu tylko tyle, ile potrzeba na spakowanie się.}
{156}{}{Dan dowiedział się od ciebie o morderstwie żony.}
{157}{}{.}
