{100}{}{Widzisz zatroskanego mê¿czyznê.}
{101}{}{Widzisz Dana, jest bardzo zatroskany.}
{102}{}{Widzisz dobrze ubranego mê¿czyznê. Jego twarz wskazuje na to, ¿e jest na skraju histerii.}
{103}{}{Kim jesteœ? Co robisz w moim domu?}
{104}{}{Ack? Oop?}
{105}{}{Jestem }
{106}{}{Nikim wa¿nym.}
{107}{}{Jestem tu, aby ciê okraœæ.}
{108}{}{Nic. Nikim. ¯egnam.}
{109}{}{Proszê, nie w moim domu. Na zewn¹trz jest ulica, na której mo¿esz robiæ sobie wszystko, co tacy "szczególni" ludzie robi¹.}
{110}{}{Thppt!}
{111}{}{Wspaniale, wspaniale. Mi³o mi ciê poznaæ. [Zastanawia siê chwilê] Hej, s³uchaj... jesteœ typem poszukiwacza, prawda?}
{112}{}{Tak.}
{113}{}{Nie rozpoznajesz Dziecka Przeznaczenia?}
{114}{}{Nie.}
{115}{}{A dlaczego tak ciê to interesuje?}
{116}{}{The reason I ask,  you see, is because my wife is missing. I don't know where she is. She's been gone for days. I've asked around town, and no one has seen her. Can you find her for me?}
{117}{}{Co bêdê z tego mieæ?}
{118}{}{Rozejrzê siê. Jak ona wygl¹da?}
{119}{}{Nie ma mowy. Mam du¿o spraw na g³owie.}
{120}{}{Dam ci 500$. To wszystkie moje oszczêdnoœci.}
{121}{}{To wystarczy. Zrobiê to.}
{122}{}{Nie. Nic z tego.}
{123}{}{Proszê. B³agam. Moja ¿ona... ona jest dla mnie wszystkim. Proszê.}
{124}{}{Nie!}
{125}{}{Fine. Fine, just stop pestering me.}
{126}{}{Here's the money. Now please, please, PLEASE... find my wife and tell me where she is. Maybe she's shacked up with someone else, maybe she's left me... but I just need to know.	}
{127}{}{Masz to jak w banku, koleœ. Jak ona wygl¹da?}
{128}{}{Oczywiœcie. Zrobiê, co w mojej mocy.}
{129}{}{::he sobs uncontrollably for a few moments:: Very well. Go away. And realize that you've broken my heart.    }
{130}{}{No to na razie, frajerze.}
{131}{}{Jest wysok¹, seksown¹ blondynk¹ o najwspanialszym g³osie, jaki kiedykolwiek s³ysza³em... Ostatnio widziano j¹ spaceruj¹c¹ w tej okolicy. Nigdy nie lubi³a mutantów i ghuli, wiêc raczej nie bêdzie w okolicy ich domów. Nikt nie wie, gdzie posz³a. To tak, jakby po prostu zniknê³a.}
{132}{}{To mi wystarczy.}
{133}{}{No i? Uda³o ci siê j¹ odnaleŸæ? Moje serce boli mocniej z ka¿d¹ chwil¹.}
{134}{}{Przykro mi - ci¹gle szukam.}
{135}{}{Tak, wiem gdzie jest.}
{136}{}{Nie, jeszcze nie. Ci¹gle szukam.}
{137}{}{Och, moje biedne serce. Proszê, daj mi znaæ, gdy j¹ znajdziesz.}
{138}{}{Jasne, oczywiœcie.}
{139}{}{W³aœciwie, ju¿ mi siê znudzi³o szukanie twojej laski.}
{140}{}{Wiesz gdzie jest? [Dostrzegasz nadziejê w jego wzroku] Gdzie?}
{141}{}{Czy to by³a taka laska bez nóg?}
{142}{}{W tunelach pod miastem jest grupka martwych osób. Twoja ¿ona jest wœród nich. Przykro mi.}
{143}{}{Co? Nie! Mia³a fantastyczne nogi!}
{144}{}{Oh. Right. Well, she hasn't got great legs now. She really got savaged, and her legs are OFF. She's totally dead, and she suffered before she died.	}
{145}{}{Jasne. Có¿, myœlê, ¿e wiem, gdzie jest. Le¿y poœród cia³ w tunelach pod miastem. Ona nie ¿yje. Strasznie mi przykro.}
{146}{}{Dziêki za informacjê. Teraz, jeœli pozwolisz, muszê siê iœæ wyp³akaæ.}
{147}{}{Taa, idŸ sobie p³akaæ, ty lalusiu.}
{148}{}{Przykro mi, stary.}
{149}{}{Nienawidzê ciê! Wszyscy ciê nienawidz¹! Najlepiej umrzyj! [p³acz]}
{150}{}{Przy jej ciele by³ list. Wynika z niego, ¿e by³a w grupie planuj¹cej wymordowanie mutantów w Broken Hills.}
{151}{}{O mój Bo¿e! Ja... Ja nie wierzê, ¿e... To po prostu nie... [G³êboko wzdycha] To, co mówisz, mo¿e byæ niestety prawd¹. Ju¿ wczeœniej nienawidzi³a ka¿dego mutanta i ghula, jakiego spotka³a. Nie wiem dlaczego.}
{152}{}{To wszystko prawda - ale pomyœl. Morderstwa mog¹ nie skoñczyæ siê na twojej ¿onie. Jeœli zabili j¹ - mog¹ te¿ chcieæ zabiæ ciebie.}
{153}{}{Chyba nie chcesz powiedzieæ, ¿e moje ¿ycie jest w niebezpieczeñstwie? O Bo¿e. Mo¿esz mieæ racjê. Ostatniej nocy s³ysza³em jakieœ szepty i szuranie dooko³a domu.}
{154}{}{Opuszczenie miasta mo¿e byæ w tej sytuacji jedynym rozwi¹zaniem. Uwa¿aj na siebie. Powodzenia.}
{155}{}{Dziêki za pomoc. Zostanê tu tylko tyle, ile potrzeba na spakowanie siê.}
{156}{}{Dan dowiedzia³ siê od ciebie o morderstwie ¿ony.}
{157}{}{.}
