{100}{}{Widzisz znudzonego goœcia ubranego w skórzany pancerz.}
{101}{}{Widzisz Maxa, stra¿nika karawany.}
{102}{}{Widzisz brudnego, znudzonego goœcia ubranego w skórzany pancerz. Po zapachu byd³a i pewnym kroku poznajesz w nim stra¿nika karawany.}
{103}{}{Mogê ci w czymœ pomóc?}
{104}{}{Hê?}
{105}{}{Ny tu pracowaæ!}
{106}{}{Kim jesteœ?}
{107}{}{Co mo¿esz mi powiedzieæ o Chadzie?}
{108}{}{Nie mam cierpliwoœci dla idiotów. Przykro mi, koleœ. Musisz sobie znaleŸæ kogoœ innego do zabawy.}
{109}{}{::chlip::}
{110}{}{Jestem Max. Jestem stra¿nikiem karawany.}
{111}{}{Co mo¿esz mi powiedzieæ o Chadzie?}
{112}{}{Dziêki. Na razie.}
{113}{}{I don't like him much. He seems to get always some extra money from his caravan jobs. It's really unfair.}
{114}{}{Well, Marcus suspects that he is skimming some of the money that supposed to go Broken Hills.}
{115}{}{Dziêki. Na razie.}
{116}{}{Thanks. I'm sure glad that this is over. You better watch your back thought.}
{117}{}{Bywaj.}
{118}{}{To nasz wróg! Zabiæ go!}
{119}{}{Ups.}
{120}{}{(Lowers his voice and looks around) That's gotta be it. I once saw myself that he was taking some "slice" of that money he got from uranium shipment from Gecko.}
{121}{}{Really? Then why you haven't tell about it to Marcus then?}
{122}{}{Are you duff? If I go to tell it, a lot of people in this town won't even look at me. Besides I might get some kind of revenge.}
{123}{}{Hmm, I could tell it about to Marcus, cause I don't plan to stay here too long anyway.}
{124}{}{Ok. Do what you want, but don't tell anything about me. And we never had this conversation, ok?}
{125}{}{Don't worry, I don't want to get you in any trouble, bye.}
