# Plik nieu¿ywany
{100}{}{Widzisz znudzonego goœcia ubranego w skórzany pancerz.}
{101}{}{Widzisz (x), stra¿nika karawany.}
{102}{}{Widzisz brudnego, znudzonego goœcia ubranego w skórzany pancerz. Po zapach byd³a i pewnym kroku poznajesz w nim stra¿nika karawany.}

{103}{}{Mogê ci w czymœ pomóc?}
{104}{}{Urg?}
{105}{}{Ny tu pracowaæ!}
{106}{}{Kim jesteœ?}
{107}{}{Co mo¿esz mi powiedzieæ o Chadzie?}

{108}{}{Nie mam cierpliwoœci dla idiotów. Przykro mi, koleœ. Musisz sobie znaleŸæ kogoœ innego do zabawy.}
{109}{}{::chlip::}

{110}{}{Jestem (x). Jestem stra¿nikiem karawany.}
{111}{}{Co mo¿esz mi powiedzieæ o Chadzie?}
{112}{}{Dziêki. Czeœæ.}

{113}{}{Chad to równy goœæ. Twardy, ale uczciwy. Lubi nagradzaæ najciê¿ej pracuj¹cych.}
{114}{}{Kim jesteœ?}
{115}{}{Dziêki. Czeœæ.}

{116}{}{Dziêki. Nie, naprawdê. Dziêki za nasze utracone premie. Jedynymi ludŸmi jakich Chad krzywdzi³ byli leszcze, z którymi handlowa³. Bardzo nam pomaga³, a ty to wszystko psujesz. Dupku.}
{117}{}{Czeœæ.}

{118}{}{To nasz wróg! Zabiæ go!}
{119}{}{Ups.}
