{100}{}{Widzisz osobę trzymającą potężną broń.}
{101}{}{Widzisz członka korpusu handlu i ochrony Broken Hills.}
{102}{}{Widzisz osobę trzymającą potężna broń i pokrytą kurzem ze szlaku.}
{103}{}{Mówię ci, jeszcze jedna grupa bandytów, a na następną wyprawę zabieram dynamit.}
{104}{}{Przydałaby się pomoc przy karawanach.}
{105}{}{Rany... Praca w Patrolu Jedności staje się naprawdę nudna.}
{106}{}{No i wtedy widzę, jak ten dzikus podchodzi i... zresztą nieważne.}
{107}{}{Jeszcze jedna aluzja do "Słonecznego Patrolu" i chyba kogoś zastrzelę.}
{108}{}{Przysięgam, że jeśli bandyci staną się gorsi, to nie dożyjemy następnej jesieni.}
{109}{}{Z jakiej zapadłej dziury jesteś?}
{110}{}{Kupisz ciężko pracującemu człowiekowi drinka?}
{111}{}{Po tej pracy przy karawanach nie mam siły na rozmowę.}
{112}{}{Jak czegoś potrzebujesz, to idź do zaopatrzeniowca - nazywa się Bill.}
{113}{}{Myśleliśmy, że po tylu latach prób ucywilizowania tych pustkowi będziemy nieco bliżej naszego celu.}
{114}{}{Mam dość tych ciągłych przepychanek miedzy ludźmi, a mutantami. Czy nie powinniśmy dawać przykład?}
{115}{}{Czego chcesz? Nie widzisz, że odpoczywam?}
{116}{}{Kiedy wyrusza kolejna karawana?}
{117}{}{Patrole, patrole, patrole... ciągle tylko to.}
{118}{}{Chyba się zdrzemnę.}
{119}{}{Zasługuję na podwyżkę. To przecież niebezpieczna służba.}
