{100}{}{Widzisz osobê trzymaj¹c¹ potê¿n¹ broñ.}
{101}{}{Widzisz cz³onka korpusu handlu i ochrony Broken Hills.}
{102}{}{Widzisz osobê trzymaj¹c¹ potê¿na broñ i pokryt¹ kurzem ze szlaku.}
{103}{}{Mówiê ci, jeszcze jedna grupa bandytów, a na nastêpn¹ wyprawê zabieram dynamit.}
{104}{}{Przyda³aby siê pomoc przy karawanach.}
{105}{}{Rany... Praca w Patrolu Jednoœci staje siê naprawdê nudna.}
{106}{}{No i wtedy widzê, jak ten dzikus podchodzi i... zreszt¹ niewa¿ne.}
{107}{}{Jeszcze jedna aluzja do "S³onecznego Patrolu" i chyba kogoœ zastrzelê.}
{108}{}{Przysiêgam, ¿e jeœli bandyci stan¹ siê gorsi, to nie do¿yjemy nastêpnej jesieni.}
{109}{}{Z jakiej zapad³ej dziury jesteœ?}
{110}{}{Kupisz ciê¿ko pracuj¹cemu cz³owiekowi drinka?}
{111}{}{Po tej pracy przy karawanach nie mam si³y na rozmowê.}
{112}{}{Jak czegoœ potrzebujesz, to idŸ do zaopatrzeniowca - nazywa siê Bill.}
{113}{}{Myœleliœmy, ¿e po tylu latach prób ucywilizowania tych pustkowi bêdziemy nieco bli¿ej naszego celu.}
{114}{}{Mam doœæ tych ci¹g³ych przepychanek miedzy ludŸmi, a mutantami. Czy nie powinniœmy dawaæ przyk³ad?}
{115}{}{Czego chcesz? Nie widzisz, ¿e odpoczywam?}
{116}{}{Kiedy odchodzi nastêpna karawana?}
{117}{}{Patrole, patrole, patrole... ci¹gle tylko to.}
{118}{}{Chyba siê zdrzemnê.}
{119}{}{Zas³ugujê na podwy¿kê. To przecie¿ niebezpieczna s³u¿ba.}
