{100}{}{Widzisz mutanta w zakurzonym ubraniu, trzymaj¹cego kilof.}
{101}{}{Widzisz mutanta górnika.}
{102}{}{Widzisz mutanta w zakurzonym ubraniu, trzymaj¹cego kilof. Z odcisków na rêkach i zmêczonej twarzy wnioskujesz, ¿e ten mutant musi byæ górnikiem. Wygl¹da na zmêczonego i nieco sko³owanego.}
{103}{}{Czego?}
{104}{}{Ag-ag! Ooo!}
{105}{}{Ork! Ooky!}
{106}{}{Dalo?}
{107}{}{Dalo!}
{108}{}{Jest tu coœ do roboty?}
{109}{}{Kim jesteœ?}
{110}{}{O, kurcze. Idiota. Dotknê³a ciê radiacja, co? Nie rozumiem ciê. Nie mogê ci pomóc.}
{111}{}{Powiedzia³em, ¿e nie mogê ci pomóc! IdŸ naprzykrzaæ siê komuœ innemu!}
{112}{}{What's there to do? Well, the mine's shut down because we haven't got an air purifier that
 works. There's the saloon. There's the caravaneers, and there's the general store.  That's about it.
 Wait... what were we talking about?}
{113}{}{Z kim mam porozmawiaæ o kopalni?}
{114}{}{Gdzie jest saloon?}
{115}{}{Gdzie s¹ te karawany?}
{116}{}{Gdzie jest ten sklep?}
{117}{}{Dziêki. Na razie.}
{118}{}{Just one of the miners.  Do you want someone important?}
{119}{}{Tak.}
{120}{}{Nie.}
{121}{}{Bywaj.}
{122}{}{Szychami w mieœcie s¹ Marcus, który jest kimœ w rodzaju burmistrza i szeryfa, Zaius, sztygar, no i Chad, który prowadzi karawany. Barman Phil jest chyba przywódc¹ ghuli... je¿eli w ogóle mo¿na mówiæ o ich przywódcy. Jeszcze raz, jak twoja godnoœæ?}
{123}{}{Gdzie mogê znaleŸæ Marcusa?}
{124}{}{Gdzie mogê znaleŸæ Zaiusa?}
{125}{}{Gdzie mogê znaleŸæ Camerona?}
{126}{}{Gdzie mogê znaleŸæ Chada?}
{127}{}{Gdzie mogê znaleŸæ Phila?}
{128}{}{Dziêki. Na razie.}
{129}{}{Je¿eli s¹dzisz, ¿e mo¿esz pomóc przy kopalni, to idŸ pogadaæ z Zaiusem. Zazwyczaj jest w budce sztygara na zewn¹trz kopalni. Jest w z³ym humorze z powodu zepsutego oczyszczacza powietrza. Jeszcze coœ?}
{130}{}{Ghul Phil prowadzi saloon. Jest kimœ w rodzaju reprezentanta ghuli w mieœcie. Mo¿esz go znaleŸæ na po³udnie od banku. Jeszcze coœ?}
{131}{}{Chad prowadzi karawany ze swojego miejsca w po³udniowo-zachodniej czêœci miasta. Coœ jeszcze?}
{132}{}{Liz, porz¹dna kobieta, prowadzi sklep wielobran¿owy tu¿ obok banku. Jeszcze coœ?}
{133}{}{A wiêc dobrze. Na razie.}
{134}{}{Cameron jest przywódc¹ tutejszych normalnych ludzi. Mutantów i ghuli niezbyt lubi, ale dobrze nas traktuje. Jest politykiem, wiêc zazwyczaj znajdziesz go w banku lub w saloonie. Czasami nawet mo¿esz go znaleŸæ pracuj¹cego u kowala. Jeszcze co? I w ogóle gdzie jestem? A tak... wiêc... coœ jeszcze?}
{135}{}{Marcus jest naszym przywódc¹. Pomaga³ za³o¿yæ Broken Hills. Zazwyczaj mo¿esz go znaleŸæ w Banku lub
 w wiêzieniu. Jeszcze coœ?}
{136}{}{Co za chciwoœæ! Czy wiesz, jak ciê¿ko pracujemy? Mam nadziejê, ¿e skiœniesz.}
{137}{}{Dziêki za rudê!}
{138}{}{Nie mogê uwierzyæ, ¿e kopalnia wylecia³a w powietrze. Teraz wszyscy umrzemy z g³odu. Ta kopalnia by³a jedyn¹ rzecz¹, która podtrzymywa³a to miasto. Có¿, przynajmniej mogê siê starzeæ ju¿ bez ¿adnej pracy...}
{139}{}{Ty gnido! Giñ!}
{140}{}{Dziêki za przywrócenie dla nas kopalni do u¿ywalnoœci. Naprawdê mamy u ciebie za to d³ug. Co mogê dla ciebie zrobiæ?}
{141}{}{Kim jesteœ?}
{142}{}{Co mo¿na tutaj robiæ?}
{143}{}{Nic nic.}
{144}{}{Mamy u ciebie d³ug za uratowanie nas przed tymi draniami z RNK. Dziêkujê, przyjacielu. Co mogê dla ciebie zrobiæ?}
{145}{}{Kim jesteœ?}
{146}{}{Co mo¿na tutaj robiæ?}
{147}{}{Nic nic.}
