# 0. QUICK LOOK
{100}{}{Widzisz Chodz¹cego Cienia.}

# 0. LOOK
{150}{}{Widzisz silnie umiêœnionego prymitywa z czarnymi szramami pokrywaj¹cymi jego twarz. Obserwuje ciê w milczeniu.}
{151}{}{Widzisz Chodz¹cego Cienia. Jego twarz jest poznaczona licznymi rytualnymi tatua¿ami.}

# 1. CLICK ON HIM (WTG)
{200}{}{Tylko siê na ciebie w ciszy gapi.}
{201}{}{W milczeniu obserwuje ciê.}

# WABBITS
{300}{}{Szzzzz... Polujê na k³óliki.}
