{100}{}{Widzisz Montego Trzy-Karty.}
{150}{}{Widzisz wrzecionowatego starszego mężczyznę o twarzy spalonej słońcem. Jest tak chudy, że wygląda, jakby był zrobiony z patyków.}
{200}{}{Nie wiem jak mogłem przegrać...}
{205}{}{Heeeej! Bohaterze! Jesteś w porząsiu, w porząsiu.}
{215}{}{Gdzie do licha są moje karty? Jeszcze PRZED CHWILĄ je miałem.}
{220}{}{Jo, chłopie, olej kasyna. Chodź zagrać u Montego.}
{230}{}{U Montego dzisiaj nieczynne. Te cholerne karty gdzieś się zapodziały.}
{231}{}{(Staruszek uśmiecha się, a skóra wokół jego oczu marszczy się) Chcesz zagrać, co?}
{250}{}{W co? W grę oczywiście!}
{260}{}{(Wręczasz mu pieniądze. Monte kiwa głową, pokazuje ci karty, potem kładzie je na ziemi i przekłada przez kilka sekund.}
{280}{}{(Monte odwraca kartę. To dwójka pik)}
{300}{}{(Wręczasz mu pieniądze. Monte kiwa głową, pokazuje ci karty i kładzie je na ziemi. W tej samej chwili podmienia kartę tak szybko, że mało brakowało, a by cię zmylił. Potem przekłada je przez kilka sekund.)}
{320}{}{COŚ ty, kolego powiedział?}
{330}{}{Słuchaj, nie mam czasu dla płaczków. Płacisz i dostajesz szansę. Jeśli chcesz GRAĆ, w porządku, ale jeśli masz się mazać, gdy przegrywasz, to spadaj!}
{340}{}{(Wręczasz mu pieniądze. Monte kiwa głową, potem kładzie karty i przekłada je przez kilka chwil.)}
{360}{}{(Wręczasz mu pieniądze. Monte kiwa głową, pokazuje ci karty, potem kładzie je na ziemi i przekłada przez kilka sekund.}
{375}{}{(Monte odwraca kartę. Królowa kier. Wydaje się, że Monte doznał paraliżującego wstrząsu.) Eee? He. Yyy... }
{385}{}{(Monte odwraca kartę. Królowa kier. Wygląda na wstrząśniętego.) Co? He... yyy... }
{400}{}{(Coś go chyba boli) Eee... no, może coś mam... ale to jest warte o WIELE więcej niż twoja wygrana... ale...}
{405}{}{Eee... hmmmm... to zależy od tego, co chcesz wiedzieć.}
{415}{}{Eee... cóż... słuchaj, ja ci tego nie mówiłem, ale założę się, że to Renesco, ten dupek, który prowadzi aptekę w zachodniej dzielnicy. Nie mam pewności, czy on to dzieciakowi SPRZEDAŁ, ale coś wie. To wszystko, co zamierzam powiedzieć.}
{420}{}{Eee... no cóż... (wygląda jakby walczył sam ze sobą) ...słuchaj, ja ci tego nie mówiłem, ale na twoim miejscu sprawdziłbym piwnicę pod Desperado.}
{425}{}{(Mruży oczy i pochyla się) Zapytałbym Julesa przy wjeździe do miasta. Nic się obok niego nie prześlizgnie... a jeśli się PRZEŚLIZGNĘŁO, to on maczał w tym palce, czaisz?}
{430}{}{No cóż... znasz tego Eldridge'a, który prowadzi Bronie z Nowego Reno? Mówi, że robi ulepszenia broni, ale nigdy nie widziałem go przy racy. Może warto by kiedyś obejrzeć jego dom... ale ja ci tego nie mówiłem.}
{435}{}{(Na twój widok Monte marszczy brwi) Słuchaj, dziś nie ma żadnego grania, dobra? Znikaj.}
{440}{}{Nie. Nie zamierzam się jej pozbywać. Koniec, kropka. To AUTENTYCZNA pamiątka sprzed wojny... mały kawałek historii. NIE MA MOWY.}
{450}{}{Co z twoimi uszami? Ta suma nawet mnie nie zainteresuje.}
{460}{}{No, w końcu nie jest dla mnie AŻ TAK cenna. Weź ją sobie. (Spogląda na prawo, na lewo, po czym ściąga jeden z butów, odkręca obcas i wyciąga ze środka kartę do gry) Masz. Dbaj o nią.}
{465}{}{(Marszczy brwi) To, czy będę mówił, zależy od tego, o co zapytasz. A nie jestem tani.}
{475}{}{Za żadne skarby Golgoty nie będę nawet TYKAĆ tego tematu. Odwal się.}
{490}{}{(Potrząsa głową) Nie ma mowy. Paplanie o tym ściągnęłoby na kogoś śmierć, a na mnie pewnie w pierwszej kolejności. Zapomnij.}
{495}{}{Och... nooo... to mnóstwo dolarów. (Oblizuje usta. Wygląda jakby walczył sam z sobą... ale ta walka nie trwa długo.) Słuchaj, ja ci tego nie powiedziałem...}
{500}{}{(Uśmiecha się drwiąco) Może coś słyszałem, a może nie. Podaj cenę.}
{510}{}{Ha! Za tyle nie kupisz kubła szczyn. Zapomnij.}
{515}{}{Taaaaak, to rozumiem. (Szczerzy zęby.) Słuchaj, ja ci tego nie mówiłem, ale na twoim miejscu poszukałbym w piwnicy pod Desperado w Alei Dziewic. Jest tam mnóstwo "szczurów", jeśli łapiesz moją aluzję.}
{520}{}{(Wzrusza ramionami) Może coś o tym wiem, a może nie. Podaj cenę, a może będę miał coś do powiedzenia.}
{530}{}{(Mrużąc oczy pochyla się nad tobą.) Za taką sumę nie wiem nic.}
{535}{}{To ja rozumiem... (mrużąc oczy pochyla się nad tobą) ...zapytałbym Julesa przy wjeździe do miasta. Nic się obok niego nie prześlizgnie... a jeśli się PRZEŚLIZGNĘŁO, to on maczał w tym palce, kumasz?}
{540}{}{(Wzrusza ramionami) Czasem coś słyszę, czasem coś widzę. Być może za 200 dolców podzieliłbym się swoimi doświadczeniami, łapiesz?}
{550}{}{Coś z twoimi uszami? POWIEDZIAŁEM 200 dolców i nie zmienię zdania.}
{555}{}{Stoi. (Monte pochyla się nad tobą) Widzisz, znasz tego faceta, co prowadzi Bronie z Ner Reno, Eldridge'a? On MÓWI, że ulepsza bronie, ale nigdy nie widziałem go przy pracy. Może warto by obejrzeć jego dom... ale ja ci tego nie mówiłem.}
{560}{}{Umrzykowo na południe od miasta. Śmierdzi jak diabli, o tak.}
{565}{}{Stawiałbym na Renesco, tego starego dupka, który prowadzi aptekę w zachodzniej dzielnicy. Nie mam pewności, czy SPRZEDAŁ to dzieciakowi, ale COŚ wie. (Rozgląda się) To wszystko, co mam do powiedzenia.}
{570}{}{(Rozgląda się, po czym zdejmuje jeden z butów, odkręca obcas i wyjmuje ze środka kartę... na karcie widać mężczyznę w dziwnej czapce, trzymającego w ręku pałkę.) No i jak? Autentyczna pamiątka sprzed wojny.}
