{100}{}{You see a card dealer.}
{101}{}{Widzisz Montego Trzy-Karty.}
{150}{}{Widzisz wrzecionowatego starszego mężczyznę o twarzy spalonej słońcem. Jest tak chudy, że wygląda, jakby był zrobiony z patyków.}
{151}{}{You see Three-Card Monte. He scopes out the street, spots you, and nods.}
{152}{}{You see Three-Card Monte. He scopes out the street, spots you, and nods.}
{200}{}{Nie wiem jak mogłem przegrać...}
{201}{}{Just keep walking... Monte's not in business today.}
{202}{}{Did I palm the wrong card?}
{203}{}{How did that stupid tribal keep picking the right card?}
{205}{}{Heeeej! Bohaterze! Jesteś w porząsiu, w porząsiu.}
{206}{}{::Pokazuje ci wyciągnięty do góry kciuk::}
{207}{}{::Smiles, nods::}
{208}{}{You done good, hero. You done good.}
{215}{}{Gdzie do licha są moje karty? Jeszcze PRZED CHWILĄ je miałem.}
{216}{}{Goddamn car key gnomes, now they're going after my playing cards.}
{220}{}{Jo, chłopie, olej kasyna. Chodź zagrać u Montego.}
{221}{}{Looking to take a chance, pal? Best odds in New Reno! C'mon...}
{222}{}{You, pal. You look like a lucky guy, c'mon over.}
{223}{}{Anybody looking to play? Free mon-ay, free mon-ay.}
{224}{}{C'mon over and play. Just the other day, I guy won 50 chips off me, easy.}
{225}{}{Easy, just guess the Queen, red Queen, and you win. That easy.}
{226}{}{You allergic to easy money? Then get over here.}
{227}{}{Everybody's winning today... you want to be the next one?}
{228}{}{Casinos'll rip you off, rob you blind... Monte treats you right, gives you a fair chance.}
{229}{}{Looking to take a chance, lady? Best odds in New Reno! C'mon...}
{230}{}{You allergic to easy money, lady? Then get over here.}
{231}{}{You, lady. You look like a lucky gal, c'mon over.}
{232}{}{Yo, lady, don't bother with the casinos. Come play with Monte.}
{233}{}{U Montego dzisiaj nieczynne. Te cholerne karty gdzieś się zapodziały.}
{234}{}{(Staruszek uśmiecha się, a skóra wokół jego oczu marszczy się) Chcesz zagrać, co?}
{235}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{236}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{237}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, friend?}
{238}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{239}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{240}{}{Three-Card Monte's the name, and the game's the same as the name. Slap down 20 chips, and we'll get down to it.}
{241}{}{You cheater. You no play fair}
{242}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{243}{}{Uh, me flattered but me not want to get down to it now... byyyyye}
{244}{}{Odejdź bez słowa.}
{245}{}{Let's play.}
{246}{}{Uh, get down to what?}
{247}{}{I'm familiar with the game. Let's play.}
{248}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{249}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{250}{}{Nie dzisiaj, dzięki.}
{251}{}{W co? W grę oczywiście!}
{252}{}{See... (shows you three cards) ...one of these is a queen. I lay them face down, shuffle them, then you pick which one the queen is. If you're right, you win.}
{253}{}{That simple, pal.}
{254}{}{That simple, lady.}
{255}{}{I'm not playing with a cheater like you.}
{256}{}{Could you explain the rules again?}
{257}{}{Sounds simple enough. Let's play. Here's 20 chips.}
{258}{}{Nie dzisiaj, dzięki.}
{260}{}{(Wręczasz mu pieniądze. Monte kiwa głową, pokazuje ci karty, potem kładzie je na ziemi i przekłada przez kilka sekund.}
{261}{}{So... which one's the queen, pal?}
{262}{}{So... which one's the queen, lady?}
{263}{}{(You think it's the one on the left.)}
{264}{}{(You think it's the one in the middle.)}
{265}{}{(You think it's the one on the right.)}
{266}{}{(You don't know. The cards moved too fast.)}
{267}{}{Lucy leftie}
{268}{}{Middle of th'road}
{269}{}{Rightie tightie}
{270}{}{The one on the left.}
{271}{}{The one on the right.}
{272}{}{The one in the middle.}
{280}{}{(Monte turns over the card. It is the }
{281}{}{Sorry, pal, not this time, but you were CLOSE.}
{282}{}{Sorry, lady, not this time, but you were CLOSE.}
{283}{}{You sure do got the eye for it, though. Wanna try again?}
{284}{}{You cheater. You no play fair}
{285}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{286}{}{Nuh-uh Me no LIKE game BYYYYE}
{287}{}{I'm not playing with a cheater like you.}
{288}{}{Sure. Here's 20 chips.}
{289}{}{Nie, dziękuję.}
{300}{}{(Wręczasz mu pieniądze. Monte kiwa głową, pokazuje ci karty i kładzie je na ziemi. W tej samej chwili podmienia kartę tak szybko, że mało brakowało, a by cię zmylił. Potem przekłada je przez kilka sekund.)}
{301}{}{So... which one's the queen, pal?}
{302}{}{So... which one's the queen, lady?}
{303}{}{You put it in sleevie weevie you no play fair}
{304}{}{Lucy leftie}
{305}{}{Middle of th'road}
{306}{}{Rightie tightie}
{307}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{308}{}{The one in your sleeve.}
{309}{}{The one on the left.}
{310}{}{The one on the right.}
{311}{}{The one in the middle.}
{320}{}{COŚ ty, kolego powiedział?}
{321}{}{WHAT did you say, lady?}
{322}{}{You accusing me of cheating?}
{323}{}{Uh-uh. Me KNOW you cheet}
{324}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{325}{}{Tak.}
{326}{}{Screw this. Keep the money, I'm outta here.}
{330}{}{Słuchaj, nie mam czasu dla płaczków. Płacisz i dostajesz szansę. Jeśli chcesz GRAĆ, w porządku, ale jeśli masz się mazać, gdy przegrywasz, to spadaj!}
{331}{}{ME BREAK YOU}
{332}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{333}{}{That's it. You're dead.}
{334}{}{All right, all right. I'm sorry. Here's 20 chips. Let's play again.}
{335}{}{Screw you. Keep the money, I'm outta here.}
{340}{}{(Wręczasz mu pieniądze. Monte kiwa głową, potem kładzie karty i przekłada je przez kilka chwil.)}
{341}{}{So... which one's the queen, pal?}
{342}{}{So... which one's the queen, lady?}
{343}{}{(Monte's using his normal deck! You need to steal his other deck to complete the switch.)}
{344}{}{You put it in sleevie weevie you no play fair}
{345}{}{Uh... Lucy leftie}
{346}{}{Uh... Middle of th'road}
{347}{}{Uh... Rightie tightie}
{348}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{349}{}{The one in your sleeve.}
{350}{}{Uh, the one on the left.}
{351}{}{Uh, the one on the right.}
{352}{}{Uh, the one in the middle.}
{360}{}{(Wręczasz mu pieniądze. Monte kiwa głową, pokazuje ci karty, potem kładzie je na ziemi i przekłada przez kilka sekund.}
{361}{}{(You hand over the cash. Monte looks uncomfortable.) Uh... all right... (Monte puts the cards on the ground and shuffles them.)}
{362}{}{So... which one's the queen, pal?}
{363}{}{So... which one's the queen, lady?}
{364}{}{(Monte's using the marked deck. Any pick is the right one.)}
{365}{}{Leftie! Leftie!}
{366}{}{Rightie! Rightie!}
{367}{}{Middlie! Middlie!}
{368}{}{Oh, I don't know... the one on the left.}
{369}{}{Hmmmm... maybe the one on the right?}
{370}{}{Gee, I'm not sure... I think it's the one in the middle.}
{375}{}{(Monte odwraca kartę. Królowa kier. Wydaje się, że Monte doznał paraliżującego wstrząsu.) Eee? He. Yyy... }
{376}{}{guess you win, pal.}
{377}{}{guess you win, lady.}
{378}{}{(He hands over the cash reluctantly.)}
{379}{}{Again! Again!}
{380}{}{Thanx me go now}
{381}{}{So we gonna play again or what? C'mon, Monte. I'm just getting started.}
{382}{}{Well, thanks, Monte. See you later.}
{385}{}{(Monte odwraca kartę. Królowa kier. Wygląda na wstrząśniętego.) Co? He... yyy... }
{386}{}{guess you win, pal.}
{387}{}{guess you win, lady.}
{388}{}{That cleans me out, though... (Looks at you weakly) Anything else I could do for you?}
{389}{}{Nuttin. Me just wanted sum extra EXP. Bye. Bye.}
{390}{}{What have you GOT?}
{391}{}{Why don't you give me some information?}
{392}{}{Forget it, Monte. We'll call it even for today.}
{400}{}{(Coś go chyba boli) Eee... no, może coś mam... ale to jest warte o WIELE więcej niż twoja wygrana... ale...}
{401}{}{Well? What is it?}
{402}{}{If it's worth more to you than dying on Golgotha because you welched on a debt, that's your problem. I'd think
 about it, if I were you.}
{404}{}{Eee... hmmmm... to zależy od tego, co chcesz wiedzieć.}
{405}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{406}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{407}{}{You know where my car is, Monte?}
{408}{}{Got anything you think I should know?}
{409}{}{Nevermind, Monte. We're even. See you later.}
{415}{}{Eee... cóż... słuchaj, ja ci tego nie mówiłem, ale założę się, że to Renesco, ten dupek, który prowadzi aptekę w zachodniej dzielnicy. Nie mam pewności, czy on to dzieciakowi SPRZEDAŁ, ale coś wie. To wszystko, co zamierzam powiedzieć.}
{416}{}{All right then, Monte. We're even.}
{420}{}{Eee... no cóż... (wygląda jakby walczył sam ze sobą) ...słuchaj, ja ci tego nie mówiłem, ale na twoim miejscu sprawdziłbym piwnicę pod Desperado.}
{421}{}{All right then, Monte. We're even.}
{425}{}{(Mruży oczy i pochyla się) Zapytałbym Julesa przy wjeździe do miasta. Nic się obok niego nie prześlizgnie... a jeśli się PRZEŚLIZGNĘŁO, to on maczał w tym palce, czaisz?}
{426}{}{All right then, Monte. We're even.}
{430}{}{No cóż... znasz tego Eldridge'a, który prowadzi Bronie z Nowego Reno? Mówi, że robi ulepszenia broni, ale nigdy nie widziałem go przy racy. Może warto by kiedyś obejrzeć jego dom... ale ja ci tego nie mówiłem.}
{431}{}{All right then, Monte. We're even.}
{435}{}{(Na twój widok Monte marszczy brwi) Słuchaj, dziś nie ma żadnego grania, dobra? Znikaj.}
{436}{}{Can I buy that card you showed me before?}
{437}{}{I wanted some information...}
{438}{}{All right, Monte. I'll leave... for now.}
{440}{}{Nie. Nie zamierzam się jej pozbywać. Koniec, kropka. To AUTENTYCZNA pamiątka sprzed wojny... mały kawałek historii. NIE MA MOWY.}
{441}{}{You making me ANOTHER offer? Look, I told you I ain't selling it.}
{442}{}{How about a thousand chips? I got it with me. It's yours in exchange for that card.}
{443}{}{Not even for 750 chips?}
{444}{}{How about 500 chips?}
{445}{}{250 chips sound about right?}
{446}{}{Dobra. Mam inne pytanie...}
{447}{}{Nevermind then, Monte. I'm outta here.}
{450}{}{Co z twoimi uszami? Ta suma nawet mnie nie zainteresuje.}
{451}{}{How about I suggest another amount...?}
{452}{}{Mam kilka innych pytań...}
{453}{}{Nevermind then, Monte. I'm outta here.}
{460}{}{No, w końcu nie jest dla mnie AŻ TAK cenna. Weź ją sobie. (Spogląda na prawo, na lewo, po czym ściąga jeden z butów, odkręca obcas i wyciąga ze środka kartę do gry) Masz. Dbaj o nią.}
{461}{}{Mam kilka innych pytań...}
{462}{}{Thanks, Monte. Always a pleasure.}
{465}{}{(Marszczy brwi) To, czy będę mówił, zależy od tego, o co zapytasz. A nie jestem tani.}
{466}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{467}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{468}{}{You know where my car is, Monte?}
{469}{}{Got anything you think I should know?}
{470}{}{Nevermind then, Monte. I'm outta here.}
{475}{}{Za żadne skarby Golgoty nie będę nawet TYKAĆ tego tematu. Odwal się.}
{476}{}{Look, that subject's just bad news. Leave it alone, all right?}
{477}{}{You making me another offer? Look, I told you I AIN'T going talk about it.}
{478}{}{A thousand chips change your mind? I got it with me.}
{479}{}{Not even for 750 chips?}
{480}{}{How about 500 chips?}
{481}{}{250 chips sound about right?}
{482}{}{Uh... Golgotha?}
{483}{}{Mam kilka innych pytań...}
{484}{}{Nevermind then, Monte. I'm outta here.}
{490}{}{(Potrząsa głową) Nie ma mowy. Paplanie o tym ściągnęłoby na kogoś śmierć, a na mnie pewnie w pierwszej kolejności. Zapomnij.}
{491}{}{How about if I offered you this...}
{492}{}{Mam kilka innych pytań...}
{493}{}{Nevermind then, Monte. I'm outta here.}
{495}{}{Och... nooo... to mnóstwo dolarów. (Oblizuje usta. Wygląda jakby walczył sam z sobą... ale ta walka nie trwa długo.) Słuchaj, ja ci tego nie powiedziałem...}
{496}{}{Understood. Go on.}
{500}{}{(Uśmiecha się drwiąco) Może coś słyszałem, a może nie. Podaj cenę.}
{501}{}{All right... talk a price.}
{502}{}{How about a thousand chips? I got it with me.}
{503}{}{Not even for 750 chips?}
{504}{}{How about 500 chips?}
{505}{}{250 chips sound about right?}
{506}{}{Mam kilka innych pytań...}
{507}{}{Nevermind then, Monte. I'm outta here.}
{510}{}{Ha! Za tyle nie kupisz kubła szczyn. Zapomnij.}
{511}{}{How about if I offered you this...}
{512}{}{Mam kilka innych pytań...}
{513}{}{Nevermind then, Monte. I'm outta here.}
{515}{}{Taaaaak, to rozumiem. (Szczerzy zęby.) Słuchaj, ja ci tego nie mówiłem, ale na twoim miejscu poszukałbym w piwnicy pod Desperado w Alei Dziewic. Jest tam mnóstwo "szczurów", jeśli łapiesz moją aluzję.}
{516}{}{Mam kilka innych pytań...}
{517}{}{Łapię. Dzięki.}
{520}{}{(Wzrusza ramionami) Może coś o tym wiem, a może nie. Podaj cenę, a może będę miał coś do powiedzenia.}
{521}{}{All right... talk a price.}
{522}{}{How about a thousand chips? I got it with me.}
{523}{}{Not even for 750 chips?}
{524}{}{How about 500 chips?}
{525}{}{250 chips sound about right?}
{526}{}{Mam kilka innych pytań...}
{527}{}{Nevermind then, Monte. I'm outta here.}
{530}{}{(Mrużąc oczy pochyla się nad tobą.) Za taką sumę nie wiem nic.}
{531}{}{How about if I offered you this...}
{532}{}{Mam kilka innych pytań...}
{533}{}{Nevermind then, Monte. I'm outta here.}
{535}{}{To ja rozumiem... (mrużąc oczy pochyla się nad tobą) ...zapytałbym Julesa przy wjeździe do miasta. Nic się obok niego nie prześlizgnie... a jeśli się PRZEŚLIZGNĘŁO, to on maczał w tym palce, kumasz?}
{536}{}{Mam kilka innych pytań...}
{537}{}{All right then, Monte. Thanks.}
{540}{}{(Wzrusza ramionami) Czasem coś słyszę, czasem coś widzę. Być może za 200 dolców podzieliłbym się swoimi doświadczeniami, łapiesz?}
{541}{}{Here's 200 chips.}
{542}{}{I'll give you 150.}
{543}{}{100 chips or nothing.}
{544}{}{Mam kilka innych pytań...}
{545}{}{Nevermind then, Monte. I'm outta here.}
{550}{}{Coś z twoimi uszami? POWIEDZIAŁEM 200 dolców i nie zmienię zdania.}
{551}{}{All right. Here's 200 chips.}
{552}{}{Mam kilka innych pytań...}
{553}{}{Nevermind then, Monte. I'm outta here.}
{555}{}{Done. (Monte leans in) Well, know that guy Eldridge, runs New Reno Arms? He SAYS he does
 weapon upgrades, but I never see him do any work. You might want to check out his place... but you didn't hear that from me.}
{556}{}{Mam kilka innych pytań...}
{557}{}{Understood. Thanks, Monte.}
{560}{}{Umrzykowo na południe od miasta. Śmierdzi jak diabli, o tak.}
{561}{}{Oh... I see. Now, about the Wright kid...}
{562}{}{Forget the Wright kid. I had some other questions...}
{563}{}{All right then, Monte. Thanks.}
{565}{}{Stawiałbym na Renesco, tego starego dupka, który prowadzi aptekę w zachodzniej dzielnicy. Nie mam pewności, czy SPRZEDAŁ to dzieciakowi, ale COŚ wie. (Rozgląda się) To wszystko, co mam do powiedzenia.}
{566}{}{Mam kilka innych pytań...}
{567}{}{All right then, Monte. Thanks.}
{570}{}{(Rozgląda się, po czym zdejmuje jeden z butów, odkręca obcas i wyjmuje ze środka kartę... na karcie widać mężczyznę w dziwnej czapce, trzymającego w ręku pałkę.) No i jak? Autentyczna pamiątka sprzed wojny.}
{571}{}{No, I already have enough inventory items... I'd rather have some information instead.}
{572}{}{Uh, sure. Why not? This'll settle things between us.}
{573}{}{Sorry pal, no chips, no game. Come back when you got more money.}
{574}{}{Sorry lady, no chips, no game. Come back when you got more money.}
{575}{}{Yeah, maybe next time then.}
{576}{}{You quickly swap Monte's deck of cards for the marked deck.}
{600}{}{spades}
{601}{}{hearts}
{602}{}{diamonds}
{603}{}{clubs}
{604}{}{dwa}
{605}{}{trzy}
{606}{}{cztery}
{607}{}{pięć}
{608}{}{sześć}
{609}{}{siódemka}
{610}{}{osiem}
{611}{}{dziewięć}
{612}{}{dziesięć}
{613}{}{ z }
