# 0. LOOK (WTG)
{100}{}{Widzisz Montego Karciarza.}

# 0. LOOK (WTG)
{150}{}{Widzisz wrzecionowatego starszego mê¿czyznê o twarzy spalonej s³oñcem. Jest tak chudy, ¿e wygl¹da, jakby by³ zrobiony z patyków.}
{000}{}{Widzisz Montego Karciarza, który obserwuj¹c uwa¿nie ulicê dostrzega ciê i kiwa g³ow¹.}
{000}{}{Widzisz Montego Karciarza, który obserwuj¹c uwa¿nie ulicê dostrzega ciê i kiwa g³ow¹.}

# 1. FLOAT (MONTE_BEATEN] (WTG)
{200}{}{Nie widzisz, ¿e przegra³em...}
{000}{}{IdŸ dalej... interes Montego jest dzisiaj zamkniêty.}
{000}{}{Czy wymaca³em nie tê kartê?}
{000}{}{Jak tej wioskowej je³opie uda³o siê wyci¹gn¹æ w³aœciw¹ kartê?}

# 3. FLOAT [FALLOUT2 = ENCLAVE_DESTROYED] (WTG)
{205}{}{Heeeej! Hiro³! W porz¹siu, w porz¹siu.}
{000}{}{::Pokazuje ci wyci¹gniêty do góry kciuk::}
{000}{}{::Uœmiecha siê, kiwa g³ow¹::}
{000}{}{Dobra robota, naprawdê dobra.}

# 4. FLOAT [NO CARDS] (WTG)
{215}{}{Gdzie do licha s¹ moje karty? Jeszcze PRZED CHWIL¥ je mia³em.}
{000}{}{Te cholerne chochliki drukarskie dobra³y siê teraz do moich kart.}

# 5. FLOAT [GENERIC] (WTG)
{220}{}{Jo, ch³opie, olej kasyna. ChodŸ zagraæ u Montego.}
{000}{}{Szukasz szczêœcia, ch³opie? Tu masz najwiêksze szanse w Nowym Reno! No chodŸ...}
{000}{}{Hej, facet. ChodŸ tu, wygl¹dasz na szczêœciarza.}
{000}{}{Ktoœ chce zagraæ? Piniondze za nic, piniondze za nic.}
{000}{}{ChodŸ tu zagraæ. Jednego dnia jeden facet wygra³ u mnie 50 dolców.}
{000}{}{Proste, zgadnij, gdzie jest królowa, czerwona królowa, a wygrasz. To proste.}
{000}{}{Masz uczulenie na ³atw¹ forsê? To chodŸ tutaj.}
{000}{}{Dzisiaj ka¿dy wygrywa... chcesz te¿ siê na to za³apaæ?}
{000}{}{W kasynach obedr¹ ciê ze skóry, ograbi¹ w bia³y dzieñ... Monte dobrze ciê potraktuje, da ci uczciw¹ szansê.}
{000}{}{Szukasz szczêœcia panno? Tu masz najwiêksze szanse w Nowym Reno! No chodŸ...}
{000}{}{Hej, panno, masz uczulenie na ³atw¹ forsê? To chodŸ tutaj.}
{000}{}{Chodzino tu panno, wygl¹dasz na szczêœciarê.}
{000}{}{Jo, panno, olej kasyna. ChodŸ zagraæ u Montego.}

# 7. PLAYING CARDS GONE (WTG)
{230}{}{U Montego dzisiaj nieczynne. Te cholerne karty gdzieœ siê zapodzia³y.}

# 8. INTRO (WTG)
{231}{}{(Staruszek uœmiecha siê, a skóra wokó³ jego oczu marszczy siê) Chcesz zgraæ, co?}
{000}{}{(Staruszek uœmiecha siê, a skóra wokó³ jego oczu marszczy siê) Chcesz zagræ panno?}
{000}{}{(Staruszek uœmiecha siê, a skóra wokó³ jego oczu marszczy siê) Hiro³, chcesz zagraæ?}
{000}{}{(Monte uœmiecha siê, a skóra wokó³ jego oczu marszczy siê) Chcesz zgraæ, co?}
{000}{}{(Monte uœmiecha siê, a skóra wokó³ jego oczu marszczy siê) Chcesz zagræ panno?}
{000}{}{(Monte uœmiecha siê, a skóra wokó³ jego oczu marszczy siê) Hiro³, chcesz zagraæ?}
{000}{}{Monte Karciarz jestem, a gra to trzy karty. Wyk³adaj 20 dolców i zaczynajmy.}
{000}{}{Ty oszust. Ty nie gra uczciwa}
{000}{}{Dobra tu dolców ja nie wie ile 20 wiêc tu troche}
{000}{}{Uch, mi mi³o, ale nie chcê teraz z tob¹ tego zaczynaæ... paaaaa.}
{000}{}{OdejdŸ bez s³owa.}
{000}{}{Nie gram z takim oszustem jak ty.}
{000}{}{Uch, zacz¹æ co?}
{000}{}{Znam tê grê. Tu jest 20 dolców. Zagrajmy.}
{000}{}{Monte Karciarz, co? K³adziesz trzy karty koszulkami do góry, przek³adasz je na stole, a ja wybieram jedn¹. Jeœli to jest w³aœciwa karta - a nie jest, poniewa¿ podmieni³eœ j¹ w czasie przek³adania - to wygrywam. Dziêki, ch³opie, ale nie skorzystam.}
{000}{}{Monte Karciarz, co? K³adziesz trzy karty koszulkami do góry, przek³adasz je na stole, a ja wybieram jedn¹. Jeœli to jest w³aœciwa karta - a nie jest, poniewa¿ podmieni³eœ j¹ w czasie przek³adania - to wygrywam. Dziêki, ch³opie, ale nie skorzystam.}
{000}{}{Nie dzisiaj, dziêki.}

# 9. UH, GET DOWN TO WHAT? (8)
{250}{}{Zacz¹æ co? Grê oczywiœcie!}
{000}{}{Popatrz... (pokazuje ci trzy karty) ...jedna z nich to królowa. K³adê j¹ koszulk¹ do góry, przek³adam, a ty masz pokazaæ, która z nich to królowa. Jeœli zgadniesz, wygrywasz. }
{000}{}{To proste, ch³opie.}
{000}{}{To proste, panno.}
{000}{}{Nie gram z takim oszustem jak ty.}
{000}{}{Czy móg³bys jeszcze raz wyt³umaczyæ zasady?}
{000}{}{Brzmi doœæ prosto. Zagrajmy. Tu masz 20 dolców.}
{000}{}{Dziêki, ale nie dzisiaj.}

# 10. PLAYING, BASIC CHEATING (8, 9, 11)
{260}{}{(Wrêczasz mu pieni¹dze. Monte kiwa g³ow¹, pokazuje ci karty, potem k³adzie je na ziemi i przek³ada przez kilka sekund.}
{000}{}{No, ch³opie... i która z nich to królowa?}
{000}{}{No, panno... i która z nich to królowa?}
{000}{}{(Wydaje ci siê, ¿e to ta po lewej.)}
{000}{}{(Wydaje ci siê, ¿e to ta po œrodku.)}
{000}{}{(Wydaje ci siê, ¿e to ta po prawej.)}
{000}{}{(Nie wiesz. Karty rusza³y siê zbyt szybko.)}
{000}{}{Lubi lewy}
{000}{}{Wprost na wprost}
{000}{}{Prawy bez obawy}
{000}{}{Ta po lewej.}
{000}{}{Ta po prawej.}
{000}{}{Ta po œrodku.}

# 11. PLAYING, LOST (10, 12, 15)
{280}{}{(Monte odwraca kartê. Dwójka pik.)}
{000}{}{Przykro mi, ch³opie, nie tym razem, ale by³eœ BLISKO.}
{000}{}{Przykro mi, panno, nie tym razem, ale by³aœ BLISKO.}
{000}{}{Ale widaæ, ¿e masz do tego oko. Chcesz spróbowaæ jeszcze raz?}
{000}{}{Ty oszust. Ty nie gra uczciwy}
{000}{}{Dobra tu dolców ja nie wie ile 20 wiêc tu troche}
{000}{}{Na-naa Ja nie LUBI gra PAAAAA}
{000}{}{Nie bêdê graæ z takim oszustem jak ty.}
{000}{}{Proszê. Tu masz 20 dolców.}
{000}{}{Nie, dziêkujê.}

# 12. PLAYING, NOTICE MONTE CHEATING (8, 9, 11, 14)
{300}{}{(Wrêczasz mu pieni¹dze. Monte kiwa g³ow¹, pokazuje ci karty i k³adzie je na ziemi. W tej samej chwili podmienia kartê tak szybko, ¿e ma³o brakowa³o, a by ciê zmyli³. Potem przek³ada je przez kilka sekund.)}
{000}{}{No, ch³opie... i która z nich to królowa?}
{000}{}{No, panno... i która z nich to królowa?}
{000}{}{Ty w³o¿yæ rêkawa ty nie gra uczciwy}
{000}{}{Lubi lewy}
{000}{}{Wprost na wprost}
{000}{}{Prawy bez obawy}
{000}{}{Ty przeklêty OSZUŒCIE. Podmieni³eœ kartê. Oddaj mi moje pieni¹dze, albo zabijê ciê na miejscu.}
{000}{}{Ta w twoim rêkawie.}
{000}{}{Ta po lewej.}
{000}{}{Ta po prawej.}
{000}{}{Ta w œrodku.}

# 13. YOU GODDAMN CHEATER... (8, 9, 11, 12, 15)
{320}{}{COŒ ty, ch³opie powiedzia³?}
{000}{}{CO powiedzia³aœ panno?}
{000}{}{Oskar¿asz mnie o oszukiwanie?}
{000}{}{Achaaaa. Ja WIE ty uszuk}
{000}{}{Na-naa! Na-naa! Nie byæ z³y. Ja iœæ}
{000}{}{Tak.}
{000}{}{Chrzaniæ to. WeŸ sobie pieni¹dze, idê st¹d.}

# 14. YES (13)
{330}{}{S³uchaj, nie mam czasu dla p³aczków. P³acisz i dostajesz szansê. Jeœli chcesz GRAÆ, w porz¹dku, ale jeœli masz siê mazaæ, gdy przegrywasz, to spadaj!}
{000}{}{JA TY PO£AMIE}
{000}{}{Na-naa! Na-naa! Ty nie wœciekaæ. Ja iœæ.}
{000}{}{Doœæ tego. Jesteœ martwy.}
{000}{}{Ju¿ dobrze, dobrze. Przepraszam. Tu masz 20 dolców. Zgrajmy jeszcze raz.}
{000}{}{Chrzañ siê. WeŸ sobie pieni¹dze, ja st¹d spadam.}

# 15. PLAYING, SWITCH BUT NOT COMPLETE, MONTE CHEATING (8, 9)
{340}{}{Wrêczasz mu pieni¹dze. Monte kiwa g³ow¹, potem k³adzie karty i przek³ada je przez kilka chwil.}
{000}{}{No, ch³ppie... i która z nich to królowa?}
{000}{}{No, panno... i która z nich to królowa?}
{000}{}{(Monte u¿ywa swojej zwyk³ej talii! Musisz ukraœæ mu tê taliê, by podmiana odnios³a skutek.)}
{000}{}{Ty w³o¿yæ rêkawa ty nie gra uczciwy}
{000}{}{Uch... lubie lewy}
{000}{}{Uch... wprost na wprost}
{000}{}{Uch... prawy bez obawy}
{000}{}{Ty przeklêty OSZUŒCIE. Podmieni³eœ kartê. Oddaj mi moje pieni¹dze, albo zabijê ciê na miejscu.}
{000}{}{Ta w twoim rêkawie.}
{000}{}{Uch, ta po lewej.}
{000}{}{Uch, ta po prawej.}
{000}{}{Uch, ta po srodku.}

# 16. PLAYING, CHEATED MONTE (8, 9, 17)
{360}{}{(Wrêczasz mu pieni¹dze. Monte kiwa g³ow¹, pokazuje ci karty, potem k³¹dzie je na ziemi i przek³ada przez kilka chwil.)}
{000}{}{(Wrêczasz mu pieni¹dze. Monte sprawia wra¿enie zaniepokojonego.) Uch... no dobra... (Monte k³adzie karty na ziemi i przek³ada je przez kilka chwil.)}
{000}{}{No, ch³opie... i która z nich to królowa?}
{000}{}{No, panno... i która z nich to królowa?}
{000}{}{(Monte u¿ywa znaczonych kart. Ka¿dy wybór jest teraz w³aœciwy.)}
{000}{}{Lewy! Lewy!}
{000}{}{Prawy! Prawy!}
{000}{}{Wprost! Wprost!}
{000}{}{No nie wiem... ta po lewej.}
{000}{}{Hmmmm... mo¿e ta po prawej?}
{000}{}{Kurczê, nie mam pewnoœci... chyba ta po œrodku.}

# 17. PLAYING, WON (16)
{375}{}{(Monte odwraca kartê. Królowa kier. Wydaje siê, ¿e Monte dozna³ og³uszaj¹cego wstrz¹su.) Eee? He. Yyy... }
{000}{}{No to, ch³opie chyba wygra³eœ.}
{000}{}{No to, panno chyba wygra³aœ.}
{000}{}{(Oci¹gaj¹c siê daje ci pieni¹dze.)}
{000}{}{Jeszcze! Jeszcze!}
{000}{}{Dzienks ja ju¿ iœæ}
{000}{}{No to jak, zagramy jeszcze raz? No, Monte. Dopiero siê rozkrêcam!}
{000}{}{Dziêki Monte. Na razie.}

# 18. PLAYING, DON'T HAVE ANY MORE CASH (16)
{385}{}{(Monte odwraca kartê. Królowa kier. Wygl¹da na wstrz¹œniêtego.) Co? He... yyy... }
{000}{}{No to, ch³opie chyba wygra³eœ.}
{000}{}{No to, panno chyba wygra³aœ.}
{000}{}{Ale przez to jestem ju¿ go³y... (rzuca ci bezsilne spojrzenie) czy mogê zrobiæ dla ciebie coœ jeszcze?}
{000}{}{Nia. Ja tylko chcieæ trochê wiêcej PD. Pa. Pa.}
{000}{}{A co MASZ?}
{000}{}{A mo¿e dasz mi kilka informacji?}
{000}{}{Niewa¿ne Monte. Powiedzmy, ¿e na dziœ jesteœmy kwita.}

# 19. WHAT HAVE YOU *GOT?* (18)
{400}{}{(Coœ go chyba boli) Eee... no, mo¿e coœ mam... ale to jest warte o WIELE wiêcej ni¿ twoja wygrana... ale...}
{000}{}{No? Co to takiego?}
{000}{}{Jeœli jest dla ciebie wiêcej warte ni¿ œmieræ na Golgocie z powodu niesp³aconych d³ugów, to ju¿ twój problem. Radzê ci to przemyœleæ.}

# 20. WHY DON'T YOU GIVE ME SOME INFO? (18, 44)
{405}{}{Eee... hmmmm... to zale¿y od tego, co chcesz wiedzieæ.}
{000}{}{Wiesz, kto pos³a³ do piachu dzieciaka Wrightów? Zrobi³ z niego œ.p. za pomoc¹ Jetu?}
{000}{}{Czy wiesz, gdzie znajdê goœcia o imieniu Œliczny Ch³opiec Lloyd?}
{000}{}{Wiesz gdzie jest mój samochód, co Monte?}
{000}{}{Czy wiesz coœ, czym warto by siê ze mn¹ podzieliæ?}
{000}{}{Niewa¿ne Monte. Jesteœmy kwita. Na razie.}

# 21. O.D. ON JET (20)
{415}{}{Eee... có¿... s³uchaj, ja ci tego nie mówi³em, ale za³o¿ê siê, ¿e to Renesco, ten dupek, który prowadzi aptekê w zachodniej dzielnicy. Nie mam pewnoœci, czy on to dzieciakowi SPRZEDA£, ale coœ wie. To wszystko, co zamierzam powiedzieæ.}
{000}{}{W porz¹dku Monte. Jesteœmy kwita.}

# 22. PRETTY BOY (20)
{420}{}{Eee... no có¿... (wygl¹da jakby walczy³ sam ze sob¹) ...s³uchaj, ja ci tego nie mówi³em, ale na twoim miejscu sprawdzi³bym piwnicê pod Desperado.}
{000}{}{W porz¹dku Monte. Jesteœmy kwita.}

# 23. KNOW WHERE MY CAR IS? (20)
{425}{}{(Mru¿y oczy i pochyla siê) Zapyta³bym Julesa przy wjeŸdzie do miasta. Nic siê obok niego nie przeœlizgnie... a jeœli siê PRZEŒLIZGNÊ£O, to on macza³ w tym palce, czaisz?}
{000}{}{W porz¹dku Monte. Jesteœmy kwita.}

# 24. GOT ANYTHING YOU THINK I SHOULD KNOW? (20)
{430}{}{No có¿... znasz tego Eldridge'a, który prowadzi Bronie z Nowego Reno? Mówi, ¿e robi ulepszenia broni, ale nigdy nie widzia³em go przy racy. Mo¿e warto by kiedyœ obejrzeæ jego dom... ale ja ci tego nie mówi³em.}
{000}{}{W porz¹dku Monte. Jesteœmy kwita.}

# 25. MONTE_BEATEN (WTG)
{435}{}{(Na twój widok Monte marszczy brwi) S³uchaj, dziœ nie ma ¿adnego grania, dobra? Spadaj.}
{000}{}{Mogê kupiæ tê kartê, któr¹ mi kiedyœ pokaza³eœ?}
{000}{}{Potrzebujê kilku informacji...}
{000}{}{No dobra Monte. Idê sobie... ale wrócê.}

# 26. CAN I BUY THAT CARD? (25, 27)
{440}{}{Nie. Nie bêdê siê ni¹ dzieliæ. Koniec, kropka. To AUTENTYCZNA pami¹tka sprzed wojny... ma³y kawa³ek historii. NIE MA MOWY.}
{000}{}{ZNOWU mnie nagabujesz? Mówi³em ci ju¿, ¿e jej nie sprzedam.}
{000}{}{Co powiesz na tysi¹c dolców? Mam je przy sobie. S¹ twoje w zamian za kartê.}
{000}{}{Nawet za 750 dolców?}
{000}{}{A co powiesz na 500 dolców?}
{000}{}{250 dolców bêdzie dobrze?}
{000}{}{W porz¹dku. Mam kilka innych pytañ...}
{000}{}{Niewa¿ne Monte. Spadam st¹d.}

# 27. NOPE. (26)
{450}{}{Co z twoimi uszami? Ta suma nawet mnie nie zainteresuje.}
{000}{}{A co powiesz na inn¹ sumê...?}
{000}{}{Mam kilka innych pytañ...}
{000}{}{W porz¹dku Monte. Spadam st¹d.}

# 28. OKAY. (26)
{460}{}{No, w koñcu nie jest dla mnie A¯ TAK cenna. WeŸ j¹ sobie. (Spogl¹da na prawo, na lewo, po czym œci¹ga jeden z butów, odkrêca obcas i wyci¹ga ze œrodka kartê do gry) Masz. Uwa¿aj na ni¹.}
{000}{}{Mam kilka innych pytañ...}
{000}{}{Dziêki Monte. Interesy z tob¹ to przyjemnoœæ.}

# 29. WHY DON'T YOU GIVE ME SOME INFO? (25, 26, 27, 28, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43)
{465}{}{(Marszczy brwi) To, czy bêdê mówi³, zale¿y od tego, o co zapytasz. A nie jestem tani.}
{000}{}{Wiesz, kto pos³a³ do piachu dzieciaka Wrightów? Zrobi³ z niego œ.p. za pomoc¹ Jetu?}
{000}{}{Czy wiesz, gdzie znajdê goœcia o imieniu Œliczny Ch³opiec Lloyd?}
{000}{}{Wiesz gdzie jest mój samochód, co Monte?}
{000}{}{Czy wiesz coœ, czym warto by siê ze mn¹ podzieliæ?}
{000}{}{Niewa¿ne Monte. Jesteœmy kwita. Na razie.}

# 30. O.D. ON JET, BUYING INFO (29, 31, 42)
{475}{}{Za ¿adne skarby Golgoty nie bêdê nawet TYKAÆ tego tematu. Odwal siê.}
{000}{}{S³uchaj, ten temat oznacza k³opoty. Zostawmy to, dobra?}
{000}{}{Znowu mnie nagabujesz? Mówi³em ci ju¿, ¿e NIE BÊDÊ o tym rozmawiaæ.}
{000}{}{Co powiesz na tysi¹c dolców? Mam je przy sobie.}
{000}{}{Nawet za 750 dolców?}
{000}{}{A co powiesz na 500 dolców?}
{000}{}{250 dolców bêdzie dobrze?}
{000}{}{Uch... Gologta?}
{000}{}{Mam kilka innych pytañ...}
{000}{}{Niewa¿ne Monte. Spadam st¹d.}

# 31. O.D. ON JET, NO DEAL (30)
{490}{}{(Potrz¹sa g³ow¹) Nie ma mowy. Paplanie o tym œci¹gnê³oby na kogoœ œmieræ, a na mnie pewnie w pierwszej kolejnoœci. Zapomnij.}
{000}{}{A mo¿e zaproponujê ci to...}
{000}{}{Mam kilka innych pytañ...}
{000}{}{Niewa¿ne Monte. Spadam st¹d.}

# 32. O.D. ON JET, BOUGHT INFO (30)
{495}{}{Och... nooo... to mnóstwo dolarów. (Oblizuje usta. Wygl¹da jakby walczy³ sam ze sob¹... ale ta walka nie trwa d³ugo.) S³uchaj, ja ci tego nie powiedzia³em...}
{000}{}{Oczywiœcie. Mów dalej.}

# 33. LLOYD, BUYING INFO (29, 34)
{500}{}{(Uœmiecha siê drwi¹co) Mo¿e coœ s³ysza³em, a mo¿e nie. Podaj cenê.}
{000}{}{No dobra... podaj cenê.}
{000}{}{Co powiesz na tysi¹c dolców? Mam je przy sobie.}
{000}{}{Nawet za 750 dolców?}
{000}{}{A co powiesz na 500 dolców?}
{000}{}{250 dolców bêdzie dobrze?}
{000}{}{Mam kilka innych pytañ...}
{000}{}{Niewa¿ne Monte. Spadam st¹d.}

# 34. PRETTY BOY, NOPE (33)
{510}{}{Ha! Za tyle to bym nie kupi³ kub³a siuœków. Zapomnij.}
{000}{}{No to co powiesz na inn¹ propozycjê...}
{000}{}{Mam kilka innych pytañ...}
{000}{}{Niewa¿ne, Monte. Spadam st¹d.}

# 35. PRETTY BOY, SURE (33)
{515}{}{Taaaaak, to rozumiem. (Szczerzy zêby) S³uchaj, ja ci tego nie mówi³em, ale na twoim miejscu poszuka³bym w piwnicy pod Desperado w Alei Dziewic. Jest tam mnóstwo "szczurów", jeœli ³apiesz moj¹ aluzjê.}
{000}{}{Mam kilka innych pytañ...}
{000}{}{£apiê. Dziêki.}

# 36. KNOW WHERE MY CAR IS? (29, 37)
{520}{}{(Wzrusza ramionami) Mo¿e coœ o tym wiem, a mo¿e nie. Podaj cenê, a mo¿e bêdê mia³ coœ do powiedzenia.}
{000}{}{Dobra... porozmawiajmy o cenie.}
{000}{}{Co powiesz na tysi¹c dolców? Mam je przy sobie.}
{000}{}{Nawet za 750 dolców?}
{000}{}{A co powiesz na 500 dolców?}
{000}{}{250 dolców bêdzie dobrze?}
{000}{}{Mam kilka innych pytañ...}
{000}{}{Niewa¿ne Monte. Spadam st¹d.}

# 37. KNOW WHERE MY CAR IS? NO (36)
{530}{}{(Mru¿¹c oczy pochyla siê nad tob¹) Za tak¹ sumê nie wiem nic.}
{000}{}{A co powiesz na tak¹ propozycjê...}
{000}{}{Mam kilka innych pytañ...}
{000}{}{Niewa¿ne Monte. Spadam st¹d.}

# 38. KNOW WHERE MY CAR IS? YES (36)
{535}{}{To ja rozumiem... (mru¿¹c oczy pochyla siê nad tob¹) ...zapyta³bym Julesa przy wjeŸdzie do miasta. Nic siê obok niego nie przeœlizgnie... a jeœli siê PRZEŒLIZGNÊ£O, to on macza³ w tym palce, kumasz?}
{000}{}{Mam kilka innych pytañ...}
{000}{}{W porz¹ddku Monte. Dziêki.}

# 39. GOT ANYTHING YOU THINK I SHOULD KNOW? (29)
{540}{}{(Wzrusza ramionami) Czasem coœ s³yszê, czasem coœ widzê. Byæ mo¿e za 200 dolców podzieli³bym siê swoimi doœwiadczeniami, ³apiesz?}
{000}{}{Oto 200 dolców.}
{000}{}{Dam ci 150.}
{000}{}{100 dolców albo nic.}
{000}{}{Mam kilka innych pytañ...}
{000}{}{Niewa¿ne Monte. Spadam st¹d.}

# 40. GOT ANYTHING YOU THINK I SHOULD KNOW? NOPE (39)
{550}{}{Coœ z twoimi uszami? POWIEDZIA£EM 200 dolców i nie zmieniê zdania.}
{000}{}{No dobra. Oto 200 dolców.}
{000}{}{Mam kilka innych pytañ...}
{000}{}{Niewa¿ne Monte. Spadam st¹d.}

# 41. GOT ANYTHING YOU THINK I SHOULD KNOW? YES (39, 40)
{555}{}{Stoi. (Monte pochyla siê nad tob¹) Widzisz, znasz tego faceta, co prowadzi Bronie z Ner Reno, Eldridge'a? On MÓWI, ¿e ulepsza bronie, ale nigdy nie widzia³em do przy pracy. Mo¿e warto by obejrzeæ jego dom... ale ja ci tego nie mówi³em.}
{000}{}{Mam kilka innych pytañ...}
{000}{}{Rozumiem. Dziêki Monte.}

# 42. GOLGOTHA (30)
{560}{}{Umrzykowo na po³udnie od miasta. Œmierdzi jak diabli, o tak.}
{000}{}{Och... rozumiem. A teraz co do tego dzieciaka Wrightów...}
{000}{}{Zapomnij o dzieciaku Wrightów. Mam kilka innych pytañ...}
{000}{}{W porz¹dku Monte. Dziêki.}

# 43. O.D. ON JET, BOUGHT INFO 2 (32)
{565}{}{Stawia³bym na Renesco, tego starego dupka, który prowadzi aptekê w zachodzniej dzielnicy. Nie mam pewnoœci, czy SPRZEDA£ to dzieciakowi, ale COÆ wie. (Rozgl¹da siê) To wszystko, co mam do powiedzenia.}
{000}{}{Mam kilka innych pytañ...}
{000}{}{W porz¹dku MOnte. Dziêki.}

# 44. WHY DON'T YOU GIVE ME THAT CARD? (19)
{570}{}{(Rozgl¹da siê, po czym zdejmuje jeden z butów, odkrêca obcas i wyjmuje ze œrodka kartê... na karcie widaæ mê¿czyznê w dziwnej czapce, trzymaj¹cego w rêku pa³kê) No i jak? Autentyczna pami¹tka sprzed wojny.}
{000}{}{Nie, ju¿ i tak mam dosyæ przedmiotów w inwentarzu... zamiast tego przyda³oby mi siê kilka informacji.}
{000}{}{Uch, Pewnie. Czemu nie? To powinno wyrównaæ nasze rachunki.}
