{100}{}{Widzisz Słodką Nikki.}
{125}{}{Widzisz jedną z krupierek kasyna.}
{150}{}{Widzisz Słodką Nikki.}
{160}{}{Widzisz Słodką Nikki. Zaprasza cię gestem do swojego stołu.}
{170}{}{Widzisz jedną z krupierek kasyna.}
{180}{}{Widzisz jedną z krupierek kasyna. Zaprasza cię gestem do swojego stołu.}
{200}{}{::Wiwatuje::}
{210}{}{Witaj, [MM]. Czy mogę pomóc... w czymkolwiek.}
{220}{}{Hazard hazardem, ale tak ryzykować własnym życiem...}
{230}{}{Hej, siłaczu. Chcesz przepuścić trochę żetonów?}
{250}{}{Witaj, gwiazdorze. Chcesz przepuścić trochę żetonów?}
{270}{}{Witaj, skarbie. Chcesz przepuścić trochę żetonów?}
{290}{}{Cóż, jesteś niespełna rozumu, skoro tu przychodzisz, ale... Proszę obstawiać. Minimalna stawka 5 żetonów. Proszę obstawiać...}
{310}{}{Eee... to świetnie, proszę pana. Niech nas pan jeszcze odwiedzi.}
{320}{}{Oczywiście. Niech nas pan jeszcze odwiedzi.}
{330}{}{Przykro mi. Może następnym razem będzie pan miał więcej szczęścia.}
{340}{}{Brawo! Gratuluję panu!}
{350}{}{Brawo! Podwoił pan swoje pieniądze! Gratuluję!}
{360}{}{Brawo! Potroił pan swoje pieniądze! Dzisiaj jest pana szczęśliwy dzień! Gratuluję!}
{370}{}{A co cię to obchodzi? Masz zamiar marnować mój czas, czy coś obstawić?}
{380}{}{Tak, słyszałam, że NIE ŻYJE. To chcesz usłyszeć?! Co?! Chcesz coś obstawić, czy będziesz dalej pieprzyć?}
{390}{}{Obawiam się, że PRZEGRASZ ten zakład, skarbie, ale jeśli twoja głupota dorównuje brzydocie, i tak pewnie postawisz. Nie widziałam tego łajdaka odkąd oszukał pana Salvatore.}
{400}{}{Skarbie, MÓWIŁAM ci już, że nie wiem gdzie on jest. Słuchaj, ja tu PRACUJĘ, więc wracaj do swojej klatki i...}
{410}{}{Dotknij mnie tylko, a pan Salvatore obedrze cię żywcem ze skóry.}
{420}{}{O czym ty mówisz?}
{430}{}{Słuchaj, JAK JUŻ MÓWIŁAM, nie wiem gdzie on jest. Ale *może* słyszałam, że kiedyś wynajmował pokój w Desperado. Poszukaj tam. A teraz, jeśli łaska, chcę wrócić do pracy.}
{440}{}{Słuchaj, pracuję tu od niedawna i nie potrafię rozpoznać każdego szulera i oszusta, który tu wejdzie. Potrafię natomiast rozpoznać takich przygłupów jak ty.}
{450}{}{Tak, wystarczy wziąć dość Jetu i WSZYSTKO wydaje się dziwne, nie?}
{460}{}{Wynoś się stąd natychmiast. Nie mam ci nic więcej do powiedzenia.}
{470}{}{Masz giętki język... jak wąż. MOŻE i wiem, gdzie jest Lloyd, MOŻE nie wiem. Masz te 500 żetonów?}
{480}{}{MOŻLIWE, że Lloyd jeszcze nie dał mi mojej doli i nie mam pewności, że ją jeszcze kiedyś zobaczę. A więc MOŻLIWE, że - za 500 żetonów MOGŁABYM powiedzieć ci gdzie ten zasmarkany kłamca się ukrywa.}
{490}{}{(Chowa pieniądze) Zajrzyj do kotłowni w piwnicy Desperado. Ten sukinsyn miał tam przeczekać, aż sprawa nieco przycichnie.}
{500}{}{Idź sobie stąd! Jeśli ludzie zobaczą, że rozmawiamy, zaczną się plotki. Rozumiesz?}
{510}{}{Więc idź do diabła! Już NIGDY się do ciebie nie odezwę.}
