{100}{}{Widzisz Słodką Nikki.}
{125}{}{Widzisz jedną z krupierek kasyna.}
{150}{}{Widzisz Słodką Nikki.}
{151}{}{You see Darlin' Nikki. She winks at you.}
{152}{}{Widzisz Słodką Nikki. Zaprasza cię gestem do swojego stołu.}
{153}{}{You see Darlin' Nikki. Mason was right about her ass.}
{154}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{155}{}{You see Darlin' Nikki. Mason was right about her ass.}
{156}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{160}{}{Widzisz Słodką Nikki. Zaprasza cię gestem do swojego stołu.}
{161}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{162}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{170}{}{Widzisz jedną z krupierek kasyna.}
{171}{}{Widzisz jedną z krupierek kasyna. Mruga do ciebie.}
{172}{}{Widzisz jedną z krupierek kasyna. Zaprasza cię gestem do swojego stołu.}
{173}{}{Widzisz jedną z krupierek kasyna. Ma niezłe... atrybuty.}
{174}{}{Widzisz jedną z krupierek kasyna. Jej sukienka więcej odsłania niż zakrywa.}
{175}{}{Widzisz jedną z krupierek kasyna. Cudownie pachnie.}
{180}{}{Widzisz jedną z krupierek kasyna. Zaprasza cię gestem do swojego stołu.}
{181}{}{Widzisz jedną z krupierek kasyna. Jej sukienka więcej odsłania niż zakrywa.}
{182}{}{Widzisz jedną z krupierek kasyna. Jej sukienka więcej odsłania niż zakrywa.}
{183}{}{Widzisz jedną z krupierek kasyna. Zaprasza cię gestem do swojego stołu.}
{200}{}{::Wiwatuje::}
{201}{}{::Klaszcze::}
{202}{}{::Gwiżdże::}
{203}{}{! Witaj w naszym kasynie!}
{204}{}{Thought you'd forgotten about us while you were saving the world.}
{210}{}{Witaj, }
{211}{}{Jeśli szukasz towarzyszki zabaw...}
{212}{}{Hey, you...(winks)...you looking to gamble?}
{213}{}{Wygląda tak... (drży) ...niebezpiecznie.}
{214}{}{Witaj w naszym kasynie, }
{215}{}{Szepnij o mnie ciepłe słówko szefowi, dobrze?}
{216}{}{Witam panią. Proszę dać znać, jeśli będę mogła w czymś pomóc.}
{217}{}{Chce pani spróbować szczęścia?}
{218}{}{Wygląda tak... (drży) ...niebezpiecznie.}
{220}{}{Hazard hazardem, ale tak ryzykować własnym życiem...}
{221}{}{Chyba pomyliły się mu kasyna...}
{222}{}{Jeśli nie wyjdzie stąd zanim zobaczą go chłopcy...}
{223}{}{O cholera. Będą kłopoty...}
{224}{}{Hazard hazardem, ale tak ryzykować własnym życiem...}
{225}{}{Chyba pomyliły się jej kasyna...}
{226}{}{Jeśli nie wyjdzie stąd zanim zobaczą ją chłopcy...}
{230}{}{Hej, siłaczu. Chcesz przepuścić trochę żetonów?}
{231}{}{Hey, champ...(winks)...you looking to gamble?}
{232}{}{Hey, champ...(smiles)...wanna take a chance?}
{233}{}{Jeśli szukasz towarzyszki zabaw...}
{234}{}{Może się do mnie odezwie...}
{235}{}{Hej, }
{236}{}{Jeśli chcesz szybko się wzbogacić, jesteś we właściwym miejscu.}
{237}{}{Best casino in New Reno. In the WORLD, even.}
{238}{}{Dzisiaj szczęście sprzyja wszystkim... mamy mnóstwo wygranych!}
{239}{}{Zapraszam }
{240}{}{Chcesz jeszcze coś do picia?}
{241}{}{Witaj w naszym kasynie, }
{242}{}{Witaj, }
{243}{}{Chcesz przepuścić trochę pieniędzy, }
{244}{}{Witaj w naszym kasynie, }
{250}{}{Witaj, gwiazdorze. Chcesz przepuścić trochę żetonów?}
{251}{}{Hej, }
{252}{}{Hej, }
{253}{}{Jeśli chcesz szybko się wzbogacić }
{254}{}{Best casino in New Reno. In the WORLD, even.}
{255}{}{Dzisiaj szczęście sprzyja wszystkim... mamy mnóstwo wygranych!}
{266}{}{Zapraszam }
{267}{}{Chcesz jeszcze coś do picia?}
{268}{}{Witaj w naszym kasynie, }
{269}{}{Hey there, Mrs. Movie Star. Looking to spend a paycheck?}
{270}{}{Witaj, skarbie. Chcesz przepuścić trochę żetonów?}
{271}{}{Hey, sweetie...(winks)...you looking to gamble?}
{272}{}{Hey, sweetie...(smiles)...wanna take a chance?}
{273}{}{Jeśli chcesz szybko się wzbogacić, jesteś we właściwym miejscu.}
{274}{}{Best casino in New Reno. In the WORLD, even.}
{275}{}{Dzisiaj szczęście sprzyja wszystkim... mamy mnóstwo wygranych!}
{276}{}{Zapraszam, zabaw się trochę.}
{277}{}{Chcesz jeszcze jednego drinka, skarbie?}
{278}{}{Witaj w naszym kasynie, skarbie.}
{279}{}{Jeśli chcesz spróbować szczęścia, to zapraszam do stołu.}
{280}{}{Witaj, skarbie. Chcesz przepuścić parę żetonów?}
{281}{}{Chcesz spróbować szczęścia, skarbie?}
{282}{}{Witaj w naszym kasynie, skarbie.}
{290}{}{Cóż, jesteś niespełna rozumu, skoro tu przychodzisz, ale... Proszę obstawiać. Minimalna stawka 5 żetonów. Proszę obstawiać...}
{291}{}{Um... place your bets... minimum bet 5 chips. Place your bets...}
{292}{}{Place your bet, sir. Minimum bet 5 chips. Place your bets...}
{293}{}{Place your bet, ma'am. Minimum bet 5 chips. Place your bets...}
{294}{}{Place your bets, minimum bet 5 chips. Place your bets...}
{295}{}{Moja grać w pałkera, tak?}
{296}{}{Ja grać jak gówno w spodnie.}
{297}{}{What this game? Can you bet Gecko skin? Me got geck... ooooh... pretty lights over there!}
{298}{}{Bet 5 chips?}
{299}{}{Bet 15 chips?}
{300}{}{Bet 25 chips?}
{301}{}{Bet 50 chips?}
{302}{}{You Nikki?}
{303}{}{How you doing, Nikki?}
{304}{}{Whoa, too rich for my blood. I'm outta here.}
{305}{}{Może innym razem, dzięki.}
{310}{}{Eee... to świetnie, proszę pana. Niech nas pan jeszcze odwiedzi.}
{311}{}{Eee... to świetnie, proszę pani. Niech nas pani jeszcze odwiedzi }
{312}{}{Podobno na zapleczu rozdają sprawne mózgi. Może tobie też się coś dostanie?}
{313}{}{Paaa-paaa.}
{314}{}{Ojejej. }
{315}{}{Uh... brains... what them?}
{320}{}{Oczywiście. Niech nas pan jeszcze odwiedzi.}
{321}{}{Oczywiście. Niech nas pani jeszcze odwiedzi.}
{322}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{323}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{324}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{325}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{326}{}{Może kiedyś, dziękuję.}
{327}{}{Maybe so, but at least *I* don't live here.}
{330}{}{Przykro mi. Może następnym razem będzie pan miał więcej szczęścia.}
{331}{}{Przykro mi. Może następnym razem będzie pani miała więcej szczęścia.}
{332}{}{Przykro mi. Może następnym razem się uda.}
{333}{}{You have [C] chips. Keep playing?}
{334}{}{Na dzisiaj wystarczy.}
{335}{}{Jak na jedną noc wystarczy.}
{340}{}{Brawo! Gratuluję panu!}
{341}{}{Winner! Well done, ma'am!}
{342}{}{Winner!}
{343}{}{You have [C] chips. Keep playing?}
{344}{}{Na dzisiaj wystarczy.}
{345}{}{Jak na jedną noc wystarczy.}
{350}{}{Brawo! Podwoił pan swoje pieniądze! Gratuluję!}
{351}{}{Brawo! Podwoiła pani swoje pieniądze! Gratuluję!}
{352}{}{Brawo! Bank płaci podwójnie! Gratuluję!}
{353}{}{You have [C] chips. Keep playing?}
{354}{}{Na dzisiaj wystarczy.}
{355}{}{Jak na jedną noc wystarczy.}
{360}{}{Brawo! Potroił pan swoje pieniądze! Dzisiaj jest pana szczęśliwy dzień! Gratuluję!}
{361}{}{Wygrana! Doskonale pani idzie! Potroiła pani wypłatę! Szczęście sprzyja nam dzisiaj!}
{362}{}{Brawo! Bank płaci potrójnie!}
{363}{}{You have [C] chips. Keep playing?}
{364}{}{Na dzisiaj wystarczy.}
{365}{}{Jak na jedną noc wystarczy.}
{370}{}{A co cię to obchodzi? Masz zamiar marnować mój czas, czy coś obstawić?}
{371}{}{I'm whoever you WANT me to be, sweetheart. Now, you gonna place a bet?}
{372}{}{I'm whoever you WANT me to be, girlfriend. Now, you gonna place a bet?}
{373}{}{Place a bet.}
{374}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{375}{}{Yeah, I'm betting you and Pretty Boy Lloyd were both stealing money from Mr. Salvatore. Hard to believe you
 didn't notice him cheating all those times.}
{376}{}{Znasz może kogoś, kto nazywa się Śliczny Chłopiec Lloyd?}
{377}{}{We'll talk later, Nikki.}
{380}{}{Tak, słyszałam, że NIE ŻYJE. To chcesz usłyszeć?! Co?! Chcesz coś obstawić, czy będziesz dalej pieprzyć?}
{381}{}{Nope. You gonna place a bet?}
{382}{}{Place a bet.}
{383}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{384}{}{Yeah, I'm betting you and Pretty Boy Lloyd were both stealing money from Mr. Salvatore. Hard to believe you didn't notice
 Lloyd cheating all those times.}
{385}{}{We'll talk later, Nikki.}
{390}{}{Obawiam się, że PRZEGRASZ ten zakład, skarbie, ale jeśli twoja głupota dorównuje brzydocie, i tak pewnie postawisz. Nie widziałam tego łajdaka odkąd oszukał pana Salvatore.}
{391}{}{Then that's a bet you'd lose, sweetheart. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{392}{}{Then that's a bet you'd lose, girlfriend. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{393}{}{Maybe you didn't hear me the first time, so for the benefit of the hearing impaired: Where is Lloyd?}
{394}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{395}{}{Fine. We'll talk later, Nikki.}
{400}{}{Skarbie, MÓWIŁAM ci już, że nie wiem gdzie on jest. Słuchaj, ja tu PRACUJĘ, więc wracaj do swojej klatki i...}
{401}{}{Girlfriend, I TOLD you that I don't know where he is. Now, look, I'm WORKING here, so go back to whatever rock you --}
{402}{}{Nikki, Nikki... I'm losing PATIENCE here. If you don't tell me where Lloyd is, I'm going to lose my temper, too.}
{403}{}{Nikki, I don't know what happened between you and Lloyd. But guess what? I don't NEED to know. I'll just tell
 Mr. Salvatore what I suspect.}
{404}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{405}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{406}{}{We'll talk later then, Nikki.}
{410}{}{Dotknij mnie tylko, a pan Salvatore obedrze cię żywcem ze skóry.}
{411}{}{Salvatore won't protect you; dealers like you are a chip a dozen. Cut the shit and tell me where Lloyd is or ELSE.}
{412}{}{Salvatore won't protect you; he's dead. Cut the shit and tell me where Lloyd is or ELSE.}
{413}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{414}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{415}{}{We'll talk later then, Nikki.}
{420}{}{O czym ty mówisz?}
{421}{}{Nikki, if you don't tell me everything right now, I'll tell Mr. Salvatore you were in on it, whether you were or not.
 He'll have Mason cut you up seven ways to Sunday, and have your job filled in an hour.}
{422}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{423}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{424}{}{We'll talk later then, Nikki.}
{430}{}{Słuchaj, JAK JUŻ MÓWIŁAM, nie wiem gdzie on jest. Ale *może* słyszałam, że kiedyś wynajmował pokój w Desperado. Poszukaj tam. A teraz, jeśli łaska, chcę wrócić do pracy.}
{431}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{432}{}{Pretty suspicious that you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{433}{}{We'll talk later then, Nikki.}
{440}{}{Słuchaj, pracuję tu od niedawna i nie potrafię rozpoznać każdego szulera i oszusta, który tu wejdzie. Potrafię natomiast rozpoznać takich przygłupów jak ty.}
{441}{}{Oh, so that's how you and Lloyd hooked up then?}
{442}{}{So you just started work, huh? Pretty convenient. Well, that's all I need to know. Tell Lloyd he's a dead man.}
{443}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{444}{}{We'll talk later then, Nikki.}
{450}{}{Tak, wystarczy wziąć dość Jetu i WSZYSTKO wydaje się dziwne, nie?}
{451}{}{It IS suspicious. You should have had Lloyd pegged for what he was as soon as he walked in this casino.}
{452}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{453}{}{We'll talk later then, Nikki.}
{460}{}{Wynoś się stąd natychmiast. Nie mam ci nic więcej do powiedzenia.}
{461}{}{I got nothing to say to you. Get out of here.}
{462}{}{Not now, maybe. We'll talk later though, Nikki. Count on it.}
{470}{}{Masz giętki język... jak wąż. MOŻE i wiem, gdzie jest Lloyd, MOŻE nie wiem. Masz te 500 żetonów?}
{471}{}{Maybe. Depends on what you got for me.}
{480}{}{MOŻLIWE, że Lloyd jeszcze nie dał mi mojej doli i nie mam pewności, że ją jeszcze kiedyś zobaczę. A więc MOŻLIWE, że - za 500 żetonów MOGŁABYM powiedzieć ci gdzie ten zasmarkany kłamca się ukrywa.}
{481}{}{Done. Here's the 500 chips. Tell me where he is.}
{482}{}{That's a pretty steep price for a whole bunch of "maybes" and "coulds." I'll find him on my own.}
{483}{}{I don't have enough chips, but I'll be back. You better still be here when I return.}
{490}{}{(Chowa pieniądze) Zajrzyj do kotłowni w piwnicy Desperado. Ten sukinsyn miał tam przeczekać, aż sprawa nieco przycichnie.}
{491}{}{All right then. Later, Nikki.}
{500}{}{Idź sobie stąd! Jeśli ludzie zobaczą, że rozmawiamy, zaczną się plotki. Rozumiesz?}
{501}{}{All right then. Later, Nikki.}
{510}{}{Więc idź do diabła! Już NIGDY się do ciebie nie odezwę.}
{511}{}{Breaks my heart. Later, Nikki.}
{600}{}{You bribe Nikki in telling you where Lloyd might be hiding.}
{1210}{}{. Can I help you with... anything?}
{1214}{}{.}
{1235}{}{. Chcesz przepuścić trochę żetonów?}
{1239}{}{, zabaw się trochę.}
{1241}{}{.}
{1242}{}{. Daj znać, jeśli mogę ci w czymś pomóc.}
{1243}{}{?}
{1244}{}{.}
{1251}{}{...(winks)...you looking to gamble?}
{1252}{}{...(smiles)...wanna take a chance?}
{1253}{}{, you came to the right place.}
{1266}{}{, zabaw się trochę.}
{1268}{}{.}
{1314}{}{ could always use new inventory item}
{2699}{}{Tańczysz dzisiaj?}
