{100}{}{Widzisz S³odk¹ Nikki.}
{125}{}{Widzisz jedn¹ z krupierek kasyna.}
{150}{}{Widzisz S³odk¹ Nikki.}
{160}{}{Widzisz S³odk¹ Nikki. Zaprasza ciê gestem do swojego sto³u.}
{170}{}{Widzisz jedn¹ z krupierek kasyna.}
{180}{}{Widzisz jedn¹ z krupierek kasyna. Zaprasza ciê gestem do swojego sto³u.}
{200}{}{::Wiwatuje::}
{210}{}{Hello, [MM]. Can I help you with... anything?}
{220}{}{Hazard hazardem, ale tak ryzykowaæ w³asnym ¿yciem...}
{230}{}{Hej, si³aczu. Chcesz przepuœciæ trochê ¿etonów?}
{250}{}{Witaj, gwiazdorze. Chcesz przepuœciæ trochê ¿etonów?}
{270}{}{Witaj, skarbie. Chcesz przepuœciæ trochê ¿etonów?}
{290}{}{Có¿, jesteœ niespe³na rozumu, skoro tu przychodzisz, ale... Proszê obstawiaæ. Minimalna stawka 5 ¿etonów. Proszê obstawiaæ...}
{310}{}{Eee... to œwietnie, proszê pana. Niech nas pan jeszcze odwiedzi.}
{320}{}{Oczywiœcie. Niech nas pan jeszcze odwiedzi.}
{330}{}{Przykro mi. Mo¿e nastêpnym razem bêdzie pan mia³ wiêcej szczêœcia.}
{340}{}{Brawo! Gratulujê panu!}
{350}{}{Brawo! Podwoi³ pan swoje pieni¹dze! Gratulujê!}
{360}{}{Brawo! Potroi³ pan swoje pieni¹dze! Dzisiaj jest pana szczêœliwy dzieñ! Gratulujê!}
{370}{}{A co ciê to obchodzi? Masz zamiar marnowaæ mój czas, czy coœ obstawiæ?}
{380}{}{Tak, s³ysza³am, ¿e NIE ¯YJE. To chcesz us³yszeæ?! Co?! Chcesz coœ obstawiæ, czy bêdziesz dalej pieprzyæ?}
{390}{}{Obawiam siê, ¿e PRZEGRASZ ten zak³ad, skarbie, ale jeœli twoja g³upota dorównuje brzydocie, i tak pewnie postawisz. Nie widzia³am tego ³ajdaka odk¹d oszuka³ pana Salvatore.}
{400}{}{Skarbie, MÓWI£AM ci ju¿, ¿e nie wiem gdzie on jest. S³uchaj, ja tu PRACUJÊ, wiêc wracaj do swojej klatki i...}
{410}{}{Dotknij mnie tylko, a pan Salvatore obedrze ciê ¿ywcem ze skóry.}
{420}{}{O czym ty mówisz?}
{430}{}{S³uchaj, JAK JU¯ MÓWI£AM, nie wiem gdzie on jest. Ale *mo¿e* s³ysza³am, ¿e kiedyœ wynajmowa³ pokój w Desperado. Poszukaj tam. A teraz, jeœli ³aska, chcê wróciæ do pracy.}
{440}{}{S³uchaj, pracujê tu od niedawna i nie potrafiê rozpoznaæ ka¿dego szulera i oszusta, który tu wejdzie. Potrafiê natomiast rozpoznaæ takich przyg³upów jak ty.}
{450}{}{Tak, wystarczy wzi¹æ doœæ Jetu i WSZYSTKO wydaje siê dziwne, nie?}
{460}{}{Wynoœ siê st¹d natychmiast. Nie mam ci nic wiêcej do powiedzenia.}
{470}{}{Masz giêtki jêzyk... jak w¹¿. MO¯E i wiem, gdzie jest Lloyd, MO¯E nie wiem. Masz te 500 ¿etonów?}
{480}{}{MO¯LIWE, ¿e Lloyd jeszcze nie da³ mi mojej doli i nie mam pewnoœci, ¿e j¹ jeszcze kiedyœ zobaczê. A wiêc MO¯LIWE, ¿e - za 500 ¿etonów MOG£ABYM powiedzieæ ci gdzie ten zasmarkany k³amca siê ukrywa.}
{490}{}{(Chowa pieni¹dze) Zajrzyj do kot³owni w piwnicy Desperado. Ten sukinsyn mia³ tam przeczekaæ, a¿ sprawa nieco przycichnie.}
{500}{}{IdŸ sobie st¹d! Jeœli ludzie zobacz¹, ¿e rozmawiamy, zaczn¹ siê plotki. Rozumiesz?}
{510}{}{Wiêc idŸ do diab³a! Ju¿ NIGDY siê do ciebie nie odezwê.}
