# 0. QUICK LOOK
{100}{}{Widzisz zarz¹dcê kasyna.}

# 0. LOOK
{150}{}{Widzisz dobrze ubranego mê¿czyznê nadzoruj¹cego kasyno.}
{151}{}{Widzisz zarz¹dcê nadzoruj¹cego kasyno.}

# 1. FLOAT DIALOGUE: POWER ARMOR (WTG)
{200}{}{Uch... musisz zdj¹æ tê zbrojê.}
{201}{}{Uch, obawiam siê, ¿e musi pan... albo pani... zdj¹æ tê zbrojê.}
{202}{}{Nie mo¿e pan... pani... nosiæ tego w kasynie.}

# 2. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, SNEAK (WTG)
{205}{}{Uch, czemu siê pan tak skrada?}
{206}{}{Uch, czemu siê pan ukrywa?}

# 3. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, SNEAK (WTG)
{210}{}{Uch, czemu siê pani tak skrada?}
{211}{}{Uch, czemu siê pani ukrywa?}

# 4. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, NIGHT (WTG)
{215}{}{Ach, pan }
{1215}{}{. Witam pana.}
{216}{}{Ach, to pan }
{1216}{}{. Dobry wieczór.}

# 5. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, NIGHT (WTG)
{220}{}{Ach, pani }
{1220}{}{. Witam pani¹.}
{221}{}{Ach, to pani }
{1221}{}{. Dobry wieczór.}

# 6. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO (WTG)
{225}{}{Ach, pan }
{1225}{}{. Dzieñ dobry.}

# 7. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO (WTG)
{230}{}{Ach, pani }
{1230}{}{. Dzieñ dobry.}

# 8. FLOAT DIALOGUE: MALE, MADE MAN, NOT SAME CASINO (WTG)
{235}{}{Kolego, wpychasz siê nie do tego kasyna, co trzeba.}
{236}{}{Lepiej idŸ st¹d. Ale ju¿.}
{237}{}{To nie jest miejsce odpowiednie do grania w koœci ze œmierci¹. Lepiej odejdŸ.}
{238}{}{Suko, w³azisz do z³ego kasyna.}

# 10. FLOAT DIALOGUE: MALE, PRIZEFIGHTER/PORN STAR (ARMED) (WTG)
{245}{}{Przepraszam pana, ale nalegam, by zabezpieczy³ pan tê broñ.}

# 11. FLOAT DIALOGUE: FEMALE, PRIZEFIGHTER (ARMED) (WTG)
{250}{}{Przepraszam pani¹, ale nalegam, by zabezpieczy³a pani tê broñ.}

# 12. FLOAT DIALOGUE: PORN STAR, FEMALE (ARMED) (WTG)
{255}{}{Kochanie, wybacz, ale nie mo¿na wnosiæ broni do kasyna. He-he... i tak jesteœ wystarczaj¹co zabójcza.}

# 13. FLOAT DIALOGUE: PORN STAR, FEMALE (SNEAK) (WTG)
{260}{}{Kochanie, z takim cia³kiem nie dasz rady przeœlizgn¹æ siê obok kogokolwiek.}

# 14. FLOAT DIALOGUE: MALE, NO REP (ARMED) (WTG)
{265}{}{Dzikusie, lepiej od³ó¿ tê broñ, ale JU¯.}

# 15. FLOAT DIALOGUE: MALE, NO REP (SNEAK) (WTG)
{270}{}{Dzikusie, lepiej przestañ siê tak skradaæ, ale JU¯.}

# 16. MYRON, MORDINO (WTG)
{275}{}{Hej, hej... Myron! Dawno ju¿ nie widzia³em ciê poza laboratorium.}
{276}{}{Przychodzisz tu z próbkami nowego towaru, co Myron?}
{277}{}{Hej Myron! W³aŸ do nas.}

# 17. MARCUS (WTG)
{285}{}{¯adnych mutantów. On poczeka na zewn¹trz.}
{286}{}{Nie obchodzi mnie, ¿e twój kumpel jest Ex-Manem, mutanty musz¹ czekaæ na zewn¹trz.}
{287}{}{To zmutowane dziwad³o nie mo¿e tu wejœæ.}

# 18. ROBOBRAIN (WTG)
{295}{}{¯adnych robotów.}
{296}{}{Nie obs³ugujemy robotów.}
{297}{}{¯adnych robotów. Roboty musz¹ poczekaæ na zewn¹trz.}

# 19. FLOAT DIALOGUE: FLAG: ENCLAVE DESTROYED IS TRUE (WTG)
{305}{}{Nie powinienem plotkowaæ w czasie pracy, ale cieszê siê, ¿e uda³o ci siê skopaæ ty³ek Enklawie.}
{306}{}{Hej, }
{1306}{}{. Odpocznij trochê od ratowania œwiata i zabaw siê.}

# 20. FLOAT DIALOGUE: DAY (WTG)
{315}{}{Potrzebujê trochê wiêcej ¿etonów przy stoliku trzecim...}
{316}{}{Ale dzisiaj t³um...}

# 21. FLOAT DIALOGUE: NIGHT (WTG)
{325}{}{Potrzebujê trochê wiêcej ¿etonów przy stoliku trzecim...}
{326}{}{Ale dzisiaj t³um...}

# 22. INTRO (WTG)
{335}{}{Hej, }
{336}{}{! S³ysza³em, ¿e to ty wkopa³eœ Enklawê z powrotem do epoki kamienia ³upanego! Poinstruowano mnie, aby daæ ci trochê ¿etonów na koszt kasyna. Niech siê pan dobrze bawi.}
{337}{}{! S³ysza³em, ¿e to ty wkopa³aœ Enklawê z powrotem do epoki kamienia ³upanego! Poinstruowano mnie, aby daæ ci trochê ¿etonów na koszt kasyna. Niech siê pani dobrze bawi.}
{338}{}{. Co jest szefie? Coœ podaæ? Drinka? Kelnerkê?}
{339}{}{. Najpiêkniejsza dziewczyna w kasynie. Coœ podaæ? Drinka? Osobisty stolik?}
{340}{}{Czym mogê s³u¿yæ, koleœ?}
{341}{}{Czym mogê s³u¿yæ, z³otko?}
{342}{}{Fuuuuuuuuu fuu fuu fuuuuu}
{343}{}{OdejdŸ}
{344}{}{Kim jesteœ?}
{345}{}{Co to za kasyno?}
{346}{}{Czy mo¿esz opowiedzieæ mi coœ o tym kasynie?}
{347}{}{Znasz mo¿e kogoœ, kto nazywa siê Œliczny Ch³opiec Lloyd?}
{348}{}{Kim jest ten stary facet przy automacie?}
{349}{}{Ten komik, którego tu macie, jest kiepski. Mogê go zast¹piæ?}
{350}{}{Dziêki. Potrzebujesz kogoœ, kto by zatanczy³ dziœ w nocy? Mogê siê zgodziæ na umowê czasow¹.}
{351}{}{Dziêki, postaram siê.}
{352}{}{Niczym, dziêki. Przepraszam za k³opot.}
{353}{}{Tylko sprawdzam jak sprawy stoj¹. Trzym siê.}

# 23. PORN STAR (WTG)
{360}{}{Hej, zobaczcie kto tu jest! Czeœæ }
{361}{}{. Witamy w [CN]. Kochamy twoje filmy.}
{362}{}{Fuuuuuuu fuu fuu fuuuuu}
{363}{}{OdejdŸ}
{364}{}{Kim jesteœ?}
{365}{}{Co to za kasyno?}
{366}{}{Mo¿esz opowiedzieæ mi coœ o tym kasynie?}
{367}{}{Znasz kogoœ o imieniu Œliczny Ch³opiec Lloyd?}
{368}{}{Kim jest ten stary facet przy automacie?}
{369}{}{Dziêki. Potrzebujesz kogoœ, kto by zatanczy³ dziœ w nocy? Mogê siê zgodziæ na umowê czasow¹.}
{370}{}{Dziêki za komplement. Wpadam tylko, ¿eby powiedzieæ dzieñ dobry.}

# 24. I HAD SOME QUESTIONS (31, 32, 33, 34, 35, 36, 37, 38)
{280}{}{Pewnie. Co chcesz wiedzieæ?}
{281}{}{Fuuuuu fuu fuu fuuuuu}
{282}{}{OdejdŸ}
{283}{}{Kim jesteœ?}
{284}{}{Co to za kasyno?}
{285}{}{Czy mo¿esz powiedzieæ mi coœ o tym kasynie?}
{286}{}{Znasz kogoœ o imieniu Œliczny Ch³opiec Lloyd?}
{287}{}{Kim jest ten stary facet przy automacie?}
{288}{}{Ten wasz komik jest kiepski. Mogê go zast¹piæ?}
{289}{}{Dziêki. Potrzebujesz kogoœ, kto by zatañczyl dziœ w nocy? Mogê siê zgodziæ na umowê czasow¹.}
{290}{}{Dziêki, postaram siê.}
{291}{}{Nic, dziêki. Przepraszam za k³opot.}
{292}{}{Tylko sprawdzam, jak sprawy stoj¹. Trzym siê.}

# 25. RETARD (22, 23, 24)
{300}{}{Uch, niech pan lepiej ju¿ pójdzie.}
{301}{}{Uch, niech pani lepiej ju¿ pójdzie.}
{302}{}{Wynoœ siê st¹d niedorozwoju.}
{303}{}{Mama mówi ja wyj¹tkowe dziecko}
{304}{}{OdejdŸ}

# 26. MOM SAYS I WAS SPESHAL (25)
{315}{}{Jasne, twoja mama mówi³a, ¿e ja te¿ by³em wyj¹tkowy. A teraz zmiataj... mo¿e znajdziesz j¹ gdzieœ w Alei Dziewic.}
{316}{}{Ojejku! Pa pa}
{317}{}{OdejdŸ}

# 27. WHO ARE YOU? (22, 23, 24, 29, 30, 31)
{325}{}{Jestem zarz¹dc¹. Co mogê dla ciebie zrobiæ?}
{326}{}{Zarz¹dzam tym piêtrem kasyna. Jeœli czegoœ potrzebujesz, to powiedz.}
{327}{}{Co to za kasyno?}
{328}{}{Mo¿esz powiedzieæ mi coœ o tym kasynie?}
{329}{}{Niewa¿ne, dziêki. Przepraszam za k³opot.}

# 28. WHAT CASINO IS THIS? (22, 23, 24, 27)
{335}{}{To jest [CN]. Jeœli czegoœ potrzebujesz, to powiedz.}
{336}{}{To jest [CN]. W ka¿dym razie tak by³o, gdy ostatnio patrzy³em na szyld. Co mogê dla ciebie zrobiæ?}
{337}{}{Kim jesteœ?}
{338}{}{Mo¿esz powiedzieæ mi coœ o tym kasynie?}
{339}{}{Niewa¿ne, dziêki. Przepraszam za k³opot.}

# 29. WHAT CAN YOU TELL ME ABOUT THIS CASINO? (22, 23, 24, 27, 28, 30)
{345}{}{Najlepsze kasyno w mieœcie... ale jestem troszkê stronniczy. Chcesz wiedzieæ coœ jeszcze?}
{346}{}{Najlepsze kasyno w mieœcie, najlepsze sto³y... ale dlaczego nie pójdziesz i ich nie wypróbujesz? Dobrze?}
{347}{}{Kim jesteœ?}
{348}{}{Kto jest w³aœcicielem kasyna?}
{349}{}{Dziêki. Przepraszam za k³opot.}

# 30. WHO OWNS THIS CASINO? (29)
{355}{}{Rodzina [CA]. Oni tchnêli w to miejsce ¿ycie, zrobili z niego prawdziwy nocny lokal, b³yszcz¹cy klejnot Nowego Reno.}
{356}{}{Rodzina [CA]. Jakiœ problem? Bo jeœli nie jesteœ tu dla hazardu, to to nie jest miejsce dla ciebie. Zrozumiano?}
{357}{}{Kim jesteœ?}
{358}{}{Mo¿esz powiedzieæ mi coœ o tym kasynie?}
{359}{}{Rozumiem. Dziêki za poœwiêcony czas.}

# 31. McGEE (22, 23, 24)
{365}{}{Tamten facet? Stary McGee? Stukniêty skurczybyk... gra ci¹gle na tej maszynie ju¿ od kilku lat, wci¹¿ w nadziei na g³ówn¹ wygran¹. Ca³y dorobek jego ¿ycia musi siedzieæ w tej maszynie, ale ona nie da mu ani jednego dolara.}
{366}{}{Tamten facet? Stary McGee? Stukniêty skurczybyk, nie ma w¹tpliwoœci. Ha. Ale siê na ciebie wkurzy³ za zgarniêcie jego fortuny. Uwa¿aj na niego.}
{367}{}{Czy ta maszyna oszukuje?}
{368}{}{Mam kilka innych pytañ...}
{369}{}{Dziêki za informacjê.}

# 32. IS THE MACHINE RIGGED? (31)
{375}{}{Nie, jest po prostu uparta... zupe³nie jak on. Pewnie przyda³aby siê jej ma³a naprawa, ale nie mamy ¿adnego mechanika, który umia³by z t¹ cholern¹ maszyn¹ coœ zrobiæ.}
{376}{}{Mam kilka innych pytañ...}
{377}{}{Ciekawe. Dziêki za informacje.}

# 33. PRETTY BOY LLOYD? (22, 23, 24)
{385}{}{Jasne, ten skurwysyn przyszed³ tu tak z tydzieñ temu, roz³o¿y³ jeden stolik na jakieœ tysi¹c dolarów, a potem znik³. Nie wiem, gdzie jest teraz, ale kiedyœ mia³ pokój w Desperado.}
{386}{}{Jasne, facet o tym imieniu wynajmowa³ jeden z pokoi na górze... 204. Wszystkie rachunki mia³ uregulowane, ale znik³ nagle kilka dni temu i nikt go od tamtej pory nie widzia³.}
{387}{}{Pan Salvatore wspomina³, ¿e Lloyd wygra³ te pieni¹dze u konkretnego krupiera. Kto to by³?}
{388}{}{Mam kilka innych pytañ...}
{389}{}{Dziêki za informacje.}

# 34. NIKKI? (33)
{395}{}{Nikki? Jasne, jest tam, przy œrodkowym stoliku. Jakiœ problem?}
{396}{}{¯adnych problemów. Chcê tylko z ni¹ pogadaæ. Mam kilka innych pytañ...}
{397}{}{Dziêki za informacje.}

# 35. NIKKI DEAD (33)
{405}{}{MIA£A na imiê Nikki. Pracowa³a tu kiedyœ, ale dosta³a w czapê... nie tak dawno temu.}
{406}{}{Hmmm. Czy bêdziesz mia³ coœ przeciwko, jeœli zadam nastêpne pytanie...?}
{407}{}{Ciekawe. Dziêki za informacje.}

# 36. NIKKI RAN (33)
{415}{}{Mia³a na imiê Nikki. Pracowa³a tu kiedyœ, ale odesz³a nie tak dawno temu. Tak po prostu spakowa³a swoje rzeczy i znik³a.}
{416}{}{Czy bêdziesz mia³ coœ przeciwko, jeœli zadam nastêpne pytanie...?}
{417}{}{Ciekawe. Dziêki za informacje.}

# 37. NEED A DANCER (22, 23, 24)
{425}{}{Pewnie, nie zaszkodzi. Przebieralnia jest z ty³u...}
{426}{}{Doskonale. Bêdê na scenie za kilka minut...}
{427}{}{Nie teraz. Mam kilka innych pytañ...}
{428}{}{Nie teraz. Ale wrócê.}

# 38. NEED A DANCER (22, 23, 24)
{435}{}{Nie, wci¹¿ podnosimy siê z upadku po twoich ostatnich wyczynach. Mo¿e lepiej spróbuj w innych kasynach.}
{436}{}{Dobra, dziêki. Wiesz co, mam kilka innych pytañ...}
{437}{}{Dobra... ale jeszcze tu wrócê.}

# 39. PERFORM (37)
{445}{}{Zliczasz uzbierane tej nocy pieni¹dze. Ca³kiem nieŸle.}
{446}{}{Ta skóra to by³ niez³y chwyt.}
{447}{}{Ten kawa³ z pi³k¹ te¿ by³ w porz¹dku.}
{448}{}{Nastêpnym razem postaram siê jeszcze bardziej...}

# 40. PERFORM (22, 24)
{455}{}{Pewnie, œmierdzi gorzej ni¿ braminie ³ajno. No ale ty...? A do licha, czemu nie. Ma³a improwizacja nie zaszkodzi, ale to jest trudna publicznoœæ... lepiej siê postaraj.}
{456}{}{Och, to dla mnie proœcizna... tylko popatrz.}
