{100}{}{Widzisz szefa ochrony kasyna.}
{150}{}{Widzisz elegancko ubranego mê¿czyznê. Rozgl¹da siê po kasynie.}
{151}{}{Widzisz zarz¹dcê nadzoruj¹cego kasyno.}
{200}{}{Hmmm... obawiam siê, ¿e musisz zdj¹æ tê zbrojê.}
{201}{}{Uch, obawiam siê, ¿e musi pan... albo pani... zdj¹æ tê zbrojê.}
{202}{}{Nie mo¿e pan... pani... nosiæ tego w kasynie.}
{205}{}{Mogê wiedzieæ, czemu siê pan skrada?}
{206}{}{Uch, czemu siê pan ukrywa?}
{210}{}{Mogê wiedzieæ dlaczego siê pani skrada?}
{211}{}{Uch, czemu siê pani ukrywa?}
{215}{}{Ach, pan }
{216}{}{Ach, to pan }
{220}{}{Ach, pan }
{221}{}{Ach, to pan }
{225}{}{Ach, pan }
{230}{}{Ach, pan }
{235}{}{Chyba pomyli³y ci siê kasyna.}
{236}{}{Lepiej idŸ st¹d. Ale ju¿.}
{237}{}{To nie jest miejsce odpowiednie do grania w koœci ze œmierci¹. Lepiej odejdŸ.}
{238}{}{Suko, w³azisz do z³ego kasyna.}
{245}{}{Przepraszam pana, musi pan od³o¿yæ broñ.}
{250}{}{Przepraszam pani¹, musi pani od³o¿yæ broñ.}
{255}{}{Kochanie, wybacz, ale nie mo¿na wnosiæ broni do kasyna. He-he... i tak jesteœ wystarczaj¹co zabójcza.}
{260}{}{Kociaku, z takim cia³em nie masz szans ukryæ siê w t³umie.}
{265}{}{Dzikusie, lepiej od³ó¿ tê broñ, ale JU¯.}
{270}{}{Dzikusie, lepiej przestañ siê tak skradaæ, ale JU¯.}
{275}{}{Hej, hej... Myron! Dawno ju¿ nie widzia³em ciê poza laboratorium.}
{276}{}{Przychodzisz tu z próbkami nowego towaru, co Myron?}
{277}{}{Hej Myron! W³aŸ do nas.}
{280}{}{Jasne. Co chcesz wiedzieæ?}
{281}{}{Fuuuuuuuuu fuu fuu fuuuuu}
{282}{}{OdejdŸ}
{283}{}{Kim jesteœ?}
{284}{}{Co to za kasyno?}
{285}{}{Czy mo¿esz opowiedzieæ mi coœ o tym kasynie?}
{286}{}{Znasz mo¿e kogoœ, kto nazywa siê Œliczny Ch³opiec Lloyd?}
{287}{}{Kim jest ten stary facet przy automacie?}
{288}{}{Ten komik, którego tu macie, jest kiepski. Mogê go zast¹piæ?}
{289}{}{Dziêki. Potrzebujesz kogoœ, kto by zatanczy³ dziœ w nocy? Mogê siê zgodziæ na umowê czasow¹.}
{290}{}{Dziêki, postaram siê.}
{291}{}{Nic, dziêkujê. Mi³o siê rozmawia³o.}
{292}{}{Tylko sprawdzam jak sprawy stoj¹. Trzym siê.}
{295}{}{¯adnych robotów.}
{296}{}{Nie obs³ugujemy robotów.}
{297}{}{¯adnych robotów. Roboty musz¹ poczekaæ na zewn¹trz.}
{300}{}{Sugerujê, ¿eby pan ju¿ sobie poszed³.}
{301}{}{Uch, niech pani lepiej ju¿ pójdzie.}
{302}{}{Wynoœ siê st¹d niedorozwoju.}
{303}{}{Mama mówi ja wyj¹tkowe dziecko}
{304}{}{OdejdŸ}
{305}{}{W zasadzie nie wolno mi rozmawiaæ z goœæmi, ale ta zadyma w Enklawie to kawa³ dobrej roboty.}
{306}{}{Hej, }
{315}{}{Jasne, twoja mama o mnie te¿ tak mówi³a. A teraz spadaj... mo¿e znajdziesz j¹ przy Alei Dziewic.}
{316}{}{Ojejku! Pa pa}
{317}{}{OdejdŸ}
{325}{}{Jestem zarz¹dc¹. Co mogê dla ciebie zrobiæ?}
{326}{}{Zarz¹dzam tym piêtrem kasyna. Jeœli czegoœ potrzebujesz, to powiedz.}
{327}{}{Co to za kasyno?}
{328}{}{Czy mo¿esz opowiedzieæ mi coœ o tym kasynie?}
{329}{}{Nic, dziêkujê. Mi³o siê rozmawia³o.}
{335}{}{To jest [CN]. Jak bêdziesz czegoœ potrzebowaæ, przyjdŸ do mnie.}
{336}{}{This is [CN]. At least, last time I checked the sign outside the door. Now what can I do for you?}
{337}{}{Kim jesteœ?}
{338}{}{Czy mo¿esz opowiedzieæ mi coœ o tym kasynie?}
{339}{}{Nic, dziêkujê. Mi³o siê rozmawia³o.}
{340}{}{Czym mogê s³u¿yæ, koleœ?}
{341}{}{Czym mogê s³u¿yæ, z³otko?}
{342}{}{Fuuuuuuuuu fuu fuu fuuuuu}
{343}{}{OdejdŸ}
{344}{}{Kim jesteœ?}
{345}{}{Najlepsze kasyno w mieœcie... ale jestem troszkê stronniczy. Chcesz wiedzieæ coœ jeszcze?}
{346}{}{Najlepsze kasyno w mieœcie, najlepsze sto³y... ale dlaczego nie pójdziesz i ich nie wypróbujesz? Dobrze?}
{347}{}{Kim jesteœ?}
{348}{}{Kto jest w³aœcicielem kasyna?}
{349}{}{Dziêki. Przepraszam za k³opot.}
{350}{}{Dziêki. Potrzebujesz kogoœ, kto by zatanczy³ dziœ w nocy? Mogê siê zgodziæ na umowê czasow¹.}
{351}{}{Dziêki, postaram siê.}
{352}{}{Nic, dziêkujê. Mi³o siê rozmawia³o.}
{353}{}{Tylko sprawdzam jak sprawy stoj¹. Trzym siê.}
{355}{}{Rodziny [CA]. Wpakowali w ten lokal sporo kasy, ale op³aci³o siê. To jedna z lokalnych atrakcji Nowego Reno.}
{356}{}{The [CA] Family. That a problem? Cause if you ain't here to gamble, then this ain't the place for you. Understand?}
{357}{}{Kim jesteœ?}
{358}{}{Czy mo¿esz opowiedzieæ mi coœ o tym kasynie?}
{359}{}{Rozumiem. Dziêki za poœwiêcenie mi czasu.}
{360}{}{Hej, zobaczcie kto tu jest! Czeœæ }
{361}{}{. Welcome to [CN]. Love your films.}
{362}{}{Fuuuuuuuuu fuu fuu fuuuuu}
{363}{}{OdejdŸ}
{364}{}{Kim jesteœ?}
{365}{}{Tamten facet? Stary McGee? Stukniêty skurczybyk... gra ci¹gle na tej maszynie ju¿ od kilku lat, wci¹¿ w nadziei na g³ówn¹ wygran¹. Ca³y dorobek jego ¿ycia musi siedzieæ w tej maszynie, ale ona nie da mu ani jednego dolara.}
{366}{}{Tamten facet? Stary McGee? Stukniêty skurczybyk, nie ma w¹tpliwoœci. Ha. Ale siê na ciebie wkurzy³ za zgarniêcie jego fortuny. Uwa¿aj na niego.}
{367}{}{Czy ta maszyna oszukuje?}
{368}{}{Mam kilka innych pytañ...}
{369}{}{Dziêki za informacje.}
{370}{}{Dziêki za komplement. Wpadam tylko, ¿eby powiedzieæ dzieñ dobry.}
{375}{}{Nie, jest po prostu uparta... zupe³nie jak on. Pewnie przyda³aby siê jej ma³a naprawa, ale nie mamy ¿adnego mechanika, który umia³by z t¹ cholern¹ maszyn¹ coœ zrobiæ.}
{376}{}{Mam kilka innych pytañ...}
{377}{}{Ciekawe. Dziêki za informacje.}
{385}{}{Jasne, ten skurwysyn przyszed³ tu tak z tydzieñ temu, roz³o¿y³ jeden stolik na jakieœ tysi¹c dolarów, a potem znik³. Nie wiem, gdzie jest teraz, ale kiedyœ mia³ pokój w Desperado.}
{386}{}{Jasne, facet o tym imieniu wynajmowa³ jeden z pokoi na górze... 204. Wszystkie rachunki mia³ uregulowane, ale znik³ nagle kilka dni temu i nikt go od tamtej pory nie widzia³.}
{387}{}{Pan Salvatore wspomina³, ¿e Lloyd wygra³ te pieni¹dze u konkretnego krupiera. Kto to by³?}
{388}{}{Mam kilka innych pytañ...}
{389}{}{Dziêki za informacje.}
{395}{}{Nikki? Jasne, jest tam, przy œrodkowym stoliku. Jakiœ problem?}
{396}{}{¯adnych problemów. Chcê tylko z ni¹ pogadaæ. Mam kilka innych pytañ...}
{397}{}{Dziêki za informacje.}
{405}{}{MIA£A na imiê Nikki. Pracowa³a tu kiedyœ, ale dosta³a w czapê... nie tak dawno temu.}
{406}{}{Hmmm. Czy bêdziesz mia³ coœ przeciwko, jeœli zadam nastêpne pytanie...?}
{407}{}{Ciekawe. Dziêki za informacje.}
{415}{}{Nazywa³a siê Nikki. Pracowa³a u nas, ale niedawno da³a nogê. Wziê³a swoje rzeczy i œlad po niej zagin¹³.}
{416}{}{Czy bêdziesz mia³ coœ przeciwko, jeœli zadam nastêpne pytanie...?}
{417}{}{Ciekawe. Dziêki za informacje.}
{425}{}{Jasne, to przyci¹gnie klientów. Przebieralnia jest na zapleczu...}
{426}{}{Doskonale. Bêdê na scenie za kilka minut...}
{427}{}{Nie teraz, mam kilka innych pytañ...}
{428}{}{Nie teraz. Ale wrócê.}
{435}{}{Nie, wci¹¿ podnosimy siê z upadku po twoich ostatnich wyczynach. Mo¿e lepiej spróbuj w innych kasynach.}
{436}{}{Dobra, dziêki. Wiesz co, mam kilka innych pytañ...}
{437}{}{Dobra... ale jeszcze tu wrócê.}
{445}{}{You count up the evening's tally. chips. Not a bad haul.}
{446}{}{The leather was a nice touch.}
{447}{}{That ball gag you had with you didn't hurt, either.}
{448}{}{I'll do even better next time...}
{455}{}{Pewnie, œmierdzi gorzej ni¿ braminie ³ajno. No ale ty...? A do licha, czemu nie. Ma³a improwizacja nie zaszkodzi, ale to jest trudna publicznoœæ... lepiej siê postaraj.}
{456}{}{Och, to dla mnie proœcizna... tylko popatrz.}
{1215}{}{. Witam pana.}
{1216}{}{. Witam pana.}
{1220}{}{. Witam pani¹.}
{1221}{}{. Witam pani¹.}
{1225}{}{. Witam pana.}
{1230}{}{. Witam pani¹.}
{1306}{}{. Odpocznij trochê od ratowania œwiata i zabaw siê.}
