{100}{}{Widzisz szefa ochrony kasyna.}
{150}{}{Widzisz elegancko ubranego mężczyznę. Rozgląda się po kasynie.}
{151}{}{Widzisz zarządcę nadzorującego kasyno.}
{200}{}{Hmmm... obawiam się, że musisz zdjąć tę zbroję.}
{201}{}{Uch, obawiam się, że musi pan... albo pani... zdjąć tę zbroję.}
{202}{}{Nie może pan... pani... nosić tego w kasynie.}
{205}{}{Mogę wiedzieć, czemu się pan skrada?}
{206}{}{Uch, czemu się pan ukrywa?}
{210}{}{Mogę wiedzieć dlaczego się pani skrada?}
{211}{}{Uch, czemu się pani ukrywa?}
{215}{}{Ach, pan }
{216}{}{Ach, to pan }
{220}{}{Ach, pan }
{221}{}{Ach, to pan }
{225}{}{Ach, pan }
{230}{}{Ach, pan }
{235}{}{Chyba pomyliły ci się kasyna.}
{236}{}{Lepiej idź stąd. Ale już.}
{237}{}{To nie jest miejsce odpowiednie do grania w kości ze śmiercią. Lepiej odejdź.}
{238}{}{Suko, włazisz do złego kasyna.}
{245}{}{Przepraszam pana, musi pan odłożyć broń.}
{250}{}{Przepraszam panią, musi pani odłożyć broń.}
{255}{}{Kochanie, wybacz, ale nie można wnosić broni do kasyna. He-he... i tak jesteś wystarczająco zabójcza.}
{260}{}{Kociaku, z takim ciałem nie masz szans ukryć się w tłumie.}
{265}{}{Dzikusie, lepiej odłóż tę broń, ale JUŻ.}
{270}{}{Dzikusie, lepiej przestań się tak skradać, ale JUŻ.}
{275}{}{Hej, hej... Myron! Dawno już nie widziałem cię poza laboratorium.}
{276}{}{Przychodzisz tu z próbkami nowego towaru, co Myron?}
{277}{}{Hej Myron! Właź do nas.}
{280}{}{Jasne. Co chcesz wiedzieć?}
{281}{}{Fuuuuuuuuu fuu fuu fuuuuu}
{282}{}{Odejdź}
{283}{}{Kim jesteś?}
{284}{}{Co to za kasyno?}
{285}{}{Czy możesz opowiedzieć mi coś o tym kasynie?}
{286}{}{Znasz może kogoś, kto nazywa się Śliczny Chłopiec Lloyd?}
{287}{}{Kim jest ten stary facet przy automacie?}
{288}{}{Ten komik, którego tu macie, jest kiepski. Mogę go zastąpić?}
{289}{}{Dzięki. Potrzebujesz kogoś, kto by zatanczył dziś w nocy? Mogę się zgodzić na umowę czasową.}
{290}{}{Dzięki, postaram się.}
{291}{}{Nic, dziękuję. Miło się rozmawiało.}
{292}{}{Tylko sprawdzam jak sprawy stoją. Trzym się.}
{295}{}{Żadnych robotów.}
{296}{}{Nie obsługujemy robotów.}
{297}{}{Żadnych robotów. Roboty muszą poczekać na zewnątrz.}
{300}{}{Sugeruję, żeby pan już sobie poszedł.}
{301}{}{Uch, niech pani lepiej już pójdzie.}
{302}{}{Wynoś się stąd niedorozwoju.}
{303}{}{Mama mówi ja wyjątkowe dziecko}
{304}{}{Odejdź}
{305}{}{W zasadzie nie wolno mi rozmawiać z gośćmi, ale ta zadyma w Enklawie to kawał dobrej roboty.}
{306}{}{Hej, }
{315}{}{Jasne, twoja mama o mnie też tak mówiła. A teraz spadaj... może znajdziesz ją przy Alei Dziewic.}
{316}{}{Ojejku! Pa pa}
{317}{}{Odejdź}
{325}{}{Jestem zarządcą. Co mogę dla ciebie zrobić?}
{326}{}{Zarządzam tym piętrem kasyna. Jeśli czegoś potrzebujesz, to powiedz.}
{327}{}{Co to za kasyno?}
{328}{}{Czy możesz opowiedzieć mi coś o tym kasynie?}
{329}{}{Nic, dziękuję. Miło się rozmawiało.}
{335}{}{To jest [CN]. Jak będziesz czegoś potrzebować, przyjdź do mnie.}
{336}{}{To jest [CN]. W każdym razie tak było, gdy ostatnio patrzyłem na szyld. Co mogę dla ciebie zrobić?}
{337}{}{Kim jesteś?}
{338}{}{Czy możesz opowiedzieć mi coś o tym kasynie?}
{339}{}{Nic, dziękuję. Miło się rozmawiało.}
{340}{}{Czym mogę służyć, koleś?}
{341}{}{Czym mogę służyć, złotko?}
{342}{}{Fuuuuuuuuu fuu fuu fuuuuu}
{343}{}{Odejdź}
{344}{}{Kim jesteś?}
{345}{}{Najlepsze kasyno w mieście... ale jestem troszkę stronniczy. Chcesz wiedzieć coś jeszcze?}
{346}{}{Najlepsze kasyno w mieście, najlepsze stoły... ale dlaczego nie pójdziesz i ich nie wypróbujesz? Dobrze?}
{347}{}{Kim jesteś?}
{348}{}{Kto jest właścicielem kasyna?}
{349}{}{Dzięki. Przepraszam za kłopot.}
{350}{}{Dzięki. Potrzebujesz kogoś, kto by zatanczył dziś w nocy? Mogę się zgodzić na umowę czasową.}
{351}{}{Dzięki, postaram się.}
{352}{}{Nic, dziękuję. Miło się rozmawiało.}
{353}{}{Tylko sprawdzam jak sprawy stoją. Trzym się.}
{355}{}{Rodziny [CA]. Wpakowali w ten lokal sporo kasy, ale opłaciło się. To jedna z lokalnych atrakcji Nowego Reno.}
{356}{}{Rodzina [CA]. Jakiś problem? Bo jeśli nie jesteś tu dla hazardu, to to nie jest miejsce dla ciebie. Zrozumiano?}
{357}{}{Kim jesteś?}
{358}{}{Czy możesz opowiedzieć mi coś o tym kasynie?}
{359}{}{Rozumiem. Dzięki za poświęcenie mi czasu.}
{360}{}{Hej, zobaczcie kto tu jest! Cześć }
{361}{}{. Witamy w [CN]. Kochamy twoje filmy.}
{362}{}{Fuuuuuuuuu fuu fuu fuuuuu}
{363}{}{Odejdź}
{364}{}{Kim jesteś?}
{365}{}{Tamten facet? Stary McGee? Stuknięty skurczybyk... gra ciągle na tej maszynie już od kilku lat, wciąż w nadziei na główną wygraną. Cały dorobek jego życia musi siedzieć w tej maszynie, ale ona nie da mu ani jednego dolara.}
{366}{}{Tamten facet? Stary McGee? Stuknięty skurczybyk, nie ma wątpliwości. Ha. Ale się na ciebie wkurzył za zgarnięcie jego fortuny. Uważaj na niego.}
{367}{}{Czy ta maszyna oszukuje?}
{368}{}{Mam kilka innych pytań...}
{369}{}{Dzięki za informacje.}
{370}{}{Dzięki za komplement. Wpadam tylko, żeby powiedzieć dzień dobry.}
{375}{}{Nie, jest po prostu uparta... zupełnie jak on. Pewnie przydałaby się jej mała naprawa, ale nie mamy żadnego mechanika, który umiałby z tą cholerną maszyną coś zrobić.}
{376}{}{Mam kilka innych pytań...}
{377}{}{Ciekawe. Dzięki za informacje.}
{385}{}{Jasne, ten skurwysyn przyszedł tu tak z tydzień temu, rozłożył jeden stolik na jakieś tysiąc dolarów, a potem znikł. Nie wiem, gdzie jest teraz, ale kiedyś miał pokój w Desperado.}
{386}{}{Jasne, facet o tym imieniu wynajmował jeden z pokoi na górze... 204. Wszystkie rachunki miał uregulowane, ale znikł nagle kilka dni temu i nikt go od tamtej pory nie widział.}
{387}{}{Pan Salvatore wspominał, że Lloyd wygrał te pieniądze u konkretnego krupiera. Kto to był?}
{388}{}{Mam kilka innych pytań...}
{389}{}{Dzięki za informacje.}
{395}{}{Nikki? Jasne, jest tam, przy środkowym stoliku. Jakiś problem?}
{396}{}{Żadnych problemów. Chcę tylko z nią pogadać. Mam kilka innych pytań...}
{397}{}{Dzięki za informacje.}
{405}{}{MIAŁA na imię Nikki. Pracowała tu kiedyś, ale dostała w czapę... nie tak dawno temu.}
{406}{}{Hmmm. Czy będziesz miał coś przeciwko, jeśli zadam następne pytanie...?}
{407}{}{Ciekawe. Dzięki za informacje.}
{415}{}{Nazywała się Nikki. Pracowała u nas, ale niedawno dała nogę. Wzięła swoje rzeczy i ślad po niej zaginął.}
{416}{}{Czy będziesz miał coś przeciwko, jeśli zadam następne pytanie...?}
{417}{}{Ciekawe. Dzięki za informacje.}
{425}{}{Jasne, to przyciągnie klientów. Przebieralnia jest na zapleczu...}
{426}{}{Doskonale. Będę na scenie za kilka minut...}
{427}{}{Nie teraz, mam kilka innych pytań...}
{428}{}{Nie teraz. Ale wrócę.}
{435}{}{Nie, wciąż podnosimy się z upadku po twoich ostatnich wyczynach. Może lepiej spróbuj w innych kasynach.}
{436}{}{Dobra, dzięki. Wiesz co, mam kilka innych pytań...}
{437}{}{Dobra... ale jeszcze tu wrócę.}
{445}{}{Podliczasz dzisiejszy utarg. żetonów. Całkiem nieźle.}
{446}{}{The leather was a nice touch.}
{447}{}{Ten kawał z piłką też był w porządku.}
{448}{}{Następnym razem będzie jeszcze lepiej...}
{455}{}{Pewnie, śmierdzi gorzej niż braminie łajno. No ale ty...? A do licha, czemu nie. Mała improwizacja nie zaszkodzi, ale to jest trudna publiczność... lepiej się postaraj.}
{456}{}{Och, to dla mnie prościzna... tylko popatrz.}
{1215}{}{. Witam pana.}
{1216}{}{. Witam pana.}
{1220}{}{. Witam panią.}
{1221}{}{. Witam panią.}
{1225}{}{. Witam pana.}
{1230}{}{. Witam panią.}
{1306}{}{. Odpocznij trochę od ratowania świata i zabaw się.}
