{100}{}{Widzisz du¿ego oprycha.}
{101}{}{Widzisz Rico.}
{150}{}{Widzisz ogromnego mê¿czyznê o nieprzyjaznym wyrazie twarzy. Wygl¹da jakby na œniadanie jada³ gwoŸdzie.}
{151}{}{Widzisz Rico, ochroniarza Monty'ego. Wygl¹da jakby na œniadanie jada³ gwoŸdzie.}
{175}{}{Harggg}
{176}{}{Hnrfff}
{177}{}{Snffff}
{178}{}{Urb-luu}
{179}{}{Klargggg}
{180}{}{Oog}
{200}{}{Ja kumpel Monte. TY kumpel Monte?}
{201}{}{Me hit people Monte tell me to.}
{202}{}{Ja biæ ludzia.}
{203}{}{Ja biæ ludzia pi¹œæmi jak graæ na bêben.}
{204}{}{Ja lubi biæ.}
{205}{}{::Szczerzy siê w bezzêbnym uœmiechu::}
{206}{}{::Drapie siê::}
{207}{}{::Napina miêœnie::}
{208}{}{Wrrr}
{209}{}{Wrrr - Wrrr.}
{210}{}{Ja nie chce rozmawiaæ.}
{211}{}{Yoo smell guuud.}
{212}{}{Yoo smell like mom.}
{213}{}{Yoo cute. Me no hit you.}
{214}{}{Yoo make me blush.}
{215}{}{Uuuch... ja Rico...}
