#############################################################
#he following lines are for describing the NPC when
#lanced and and examined. #
#############################################################
{100}{}{}
{101}{}{}

#############################################################

{110}{}{Czujesz niemi³e mrowienie stóp.}
{120}{}{Chyba robi¹ ci siê niema³e odciski.}
{130}{}{Twoje buty zaczynaj¹ byæ zbyt ciasne. Te odciski rosn¹ b³yskawicznie.}
{140}{}{Wygl¹da na to, ¿e odciski zamieni³y siê w dodatkowe palce u stop. Przynajmniej nie odczuwasz ju¿ tego upiornego mrowienia.}
{141}{}{Mój Bo¿e, to Bess!}

{150}{}{Zyskujesz }
{151}{}{ PD za zdobycie GECKa.}
