{100}{}{Widzisz smutnego, starszego mężczyznę.}
{101}{}{Widzisz Dave'a, "Pana Nieszczęście".}
{102}{}{You see a grumpy, older man in his early sixties.  He has a weathered face and looks as if he
 has had his fair share of abuse.}
{103}{}{Och. Nie zauważyłem cię.}
{104}{}{Jak to nie? Moja duża.}
{105}{}{Ty smutna. Czemu?}
{106}{}{Moja iść pa pa.}
{107}{}{Nic się nie stało, każdemu zdarza się pogrążyć w myślach. Wyglądasz na przygnębionego. Mogę wiedzieć, co się stało?}
{108}{}{Taaa, jasne. Czemu jesteś taki skwaszony?}
{109}{}{Nie ma sprawy. Następnym razem kopnę cię w tyłek. Wtedy mnie na pewno zauważysz, nie?}
{110}{}{Nie szkodzi. Muszę się zając pewną pilną sprawą. Żegnaj.}
{111}{}{Cóż, podobno nieszczęścia chodzą po ludziach - mnie chcą chyba stratować.}
{112}{}{Uch... moja już iść.}
{113}{}{Na przykład?}
{114}{}{Nieciekawe podejście do życia. Dlaczego tak uważasz?}
{115}{}{W takim razie wolę nie stać zbyt długo koło ciebie.}
{116}{}{I was born two months premature.  When I was one, I was dropped on the porch. When I was two, I
 had pneumonia. When I was three, I got the chicken pox. When I was four, I fell down the stairs and broke
 six ribs. When I was five, my uncle was decapitated by a watermelon.  When I was six, my parents hit me
 in the head with a shovel. When I was seven, I lost my right index finger to my pet rat.}
{117}{}{Uch, moja słyszy - ktoś woła. Pa!}
{118}{}{Przykro, niedobrze.}
{119}{}{To dawno, zapomnieć. Teraz cacy?}
{120}{}{Jej! Jakie to szczęście, że nie jestem w twojej skórze!}
{121}{}{W porządku, rozumiem. A teraz co cię trapi?}
{122}{}{Współczuję ci, że musiałeś tak wiele wycierpieć w życiu. Mam nadzieję, że teraz lepiej ci się powodzi?}
{123}{}{Przepraszam, ale mam jeszcze coś bardzo ważnego do zrobienia. Żegnaj.}
{124}{}{Cóż, podobno nieszczęścia chodzą po ludziach - mnie chcą chyba stratować.}
{125}{}{Co się stać?}
{126}{}{Moja już słyszeć. Pa.}
{127}{}{Dlaczego jesteś znowu przygnębiony?}
{128}{}{Nie chcę nawet o tym słyszeć. Muszę już iść.}
{129}{}{Podróżowałem sobie spokojnie przez pustynię, kiedy ni z tego ni z owego moja bramina wyciągnęła kopyta. Zaraz potem odkryłem, że kończy mi się woda, a z tych nerwów bardzo chciało mi się pić. W nocy zaczęło mnie łamać w kościach i rozbolała mnie głowa. Do tego doszła jeszcze biegunka i swędząca wysypka, która za cholerę nie chciała sobie pójść. Usiadłem na ziemi i czekałem na śmierć.}
{130}{}{Moja... uch... ty... Ty nie mieć rodzina?}
{131}{}{Twoja już nie mówić! Moja iść.}
{132}{}{Mam już dość tej historii. Nie zbliżaj się do mnie pod żadnym pozorem!}
{133}{}{Cholera, powiedz mi, że nie masz żadnych dzieci.}
{134}{}{Nope.  When I turned twenty-two this strange fungus started to grow on my test...}
{135}{}{Aaaarr! Twoja cicho! Moja iść!}
{136}{}{Stój! Nie chcę tego słyszeć!}
{137}{}{Och. Cześć. Co mogę dla ciebie zrobić?}
{138}{}{Twoja jeszcze opowiedzieć?}
{139}{}{Przepraszać, moja iść.}
{140}{}{Możesz mi jeszcze raz opowiedzieć historię twojego życia?}
{141}{}{Oj, przepraszam, szukam kogoś innego.}
{142}{}{Nareszcie, mój czas dobiegł końca. Zabijesz mnie teraz, prawda?}
{143}{}{Tak.}
{144}{}{Nie.}
{145}{}{Kiedy miałem osiem lat mój pies, Spike, zginął pod kołami traktora. Potem moja mama straciła rękę w wyniku ataku szalonej braminy. Kiedy miałem dziesięć lat stado dzikich psów rozszarpało moją siostrę. Kiedy miałem jedenaście lat mój dziadek popełnił samobójstwo, bo nie mógł już na mnie patrzeć. Rok później to samo zrobiła moja babcia. Kiedy miałem trzynaście lat mój ojciec w pijackim amoku wykłuł sobie oko widłami.}
{146}{}{Później mój brat włożył rękę do sieczkarni, a moja ciotka udławiła się rybią ością. Kiedy miałem szesnaście lat mój kuzyn padł ofiarą borsuka. Rok później odrąbałem sobie motyką duży palec u nogi. Do tego wszystkiego mój ojciec stracił nogę w wypadku spowodowanym przez ten sam traktor, który zabił mojego psa. Kiedy miałem dziewiętnaście lat... }
{147}{}{Tak więc siedziałem sobie na gorącym piasku pustyni, czekając, aż wydam z siebie ostatnie tchnienie, kiedy nagle zaroiło się dookoła mnie od szponów śmierci. Cóż, pomyślałem sobie, teraz już na pewno umrę. Skończę jako sterta szponowego gówna wysychająca w prażącym słońcu pustyni. Ale nie... Okrutny los szykował dla mnie jeszcze jedną niespodziankę.}
{148}{}{Widzisz, szpony śmierci wcale nie chciały mnie zabić. Zamiast tego dały mi wodę i sprowadziły tutaj. Na miejscu nakarmiono mnie, umyto, dano mi własny pokój. Tyle tylko, że nie mogę stąd wyjść. Założę się, że chcą mnie utuczyć zanim dokonają na mnie jakiegoś bestialskiego, rytualnego mordu. Powtarzam im ciągle, że chude mięso jest zdrowsze, ale nie chcą mnie słuchać. Tylko szczerzą zęby w jakimś groteskowym uśmiechu, poklepują mnie po plecach i mówią 'Nie martw się, człowieku, wszystko będzie dobrze.' Ha! Już ja dobrze wiem, co mają na myśli.}
{149}{}{Żeby już w ogóle było fatalnie, zaczęły mi podawać jakieś lekarstwo. Miałem po nim straszne gazy, więc przestałem je zażywać - i chyba dobrze zrobiłem. Podejrzewam, że przez te środki chemiczne szpony śmierci w jakiś sposób manipulowały moją psychiką, bo przez pewien czas NAPRAWDĘ zacząłem wierzyć, że wszystko będzie dobrze! To już chyba wszystko. Teraz tylko czekam, aż ich przywódca da sygnał do wielkiej uczty, na której będę grał główną rolę.}
