{100}{}{Widzisz terminal komputerowy.}
{101}{}{Widzisz terminal z dostêpem g³osowym.}
{102}{}{Widzisz standardowy terminal przystosowany do przyjmowania poleceñ g³osowych.}
{103}{}{Ogl¹dasz terminal, ale nie zauwa¿asz niczego, co by³oby w oczywisty sposób niew³aœciwe. Co teraz?}
{104}{}{Uderz go w ten "wyj¹tkowy" sposób.}
{105}{}{Kopnij go w to "wyj¹tkowe" miejsce.}
{106}{}{Uruchom program diagnostyczny.}
{107}{}{Otwórz go i zajrzyj do œrodka.}
{108}{}{Zostaw go w spokoju.}
{109}{}{Gapisz siê przez chwilê na konsolê, by zdecydowaæ, w które miejsce bêdzie najlepiej uderzyæ. Po otrzymaniu twojego najlepszego uderzenia z serii "to-powinno-zadzia³aæ", monitor kilka razy rozb³yska, po czym stabilizuje siê. Nie ma ¿adnego innego efektu. Co teraz?}
{110}{}{Kopnij go w to "wyj¹tkowe" miejsce.}
{111}{}{Uruchom program diagnostyczny.}
{112}{}{Otwórz go i zajrzyj do œrodka.}
{113}{}{Zostaw go w spokoju.}
{114}{}{Ta szeroko znana metoda naprawcza powoduje dwa efekty. Po pierwsze, monitor przez kilka sekund wariuje, a potem stabilizuje siê. Po drugie, s³yszysz jeden z tych odg³osów ³amanego metalu, po czym kopniêta przez ciebie p³yta odpada na pod³ogê. Co teraz?}
{115}{}{Uruchom program diagnostyczny.}
{116}{}{Ta cholerna rzecz siê otworzy³a. Nie zaszkodzi zajrzeæ do œrodka.}
{117}{}{Zostaw go w spokoju.}
{118}{}{Masz pewnoœæ, ¿e w takim systemie powinien byæ dostêpny zestaw procedur diagnostycznych. Jednak¿e wygl¹da na to, ¿e wejœcie klawiaturowe zosta³o unieczynnione. Ten terminal przyjmuje tylko polecenia g³osowe. Co teraz?}
{119}{}{Zosta³o ju¿ tylko zajrzeæ do œrodka.}
{120}{}{Zostaw go w spokoju.}
{121}{}{Przygl¹daj¹c siê uwa¿nie tej ca³ej masie kabli i uk³adów scalonych, zauwa¿asz, ¿e system niew¹tpliwie pad³ ofiar¹ sabota¿u. Jednej z p³yt, modu³u rozpoznawania g³osu, nie da siê naprawiæ i musi zostaæ wymieniona. Teraz wszystko, co trzeba zrobiæ, to znaleŸæ odpowiedni¹ czêœæ zamienn¹.}
{122}{}{W porz¹dku.}
{123}{}{W porz¹dku.}
{124}{}{Montujesz modu³ w terminalu. System zosta³ naprawiony.}
{125}{}{Terminal potrzebuje modu³u rozpoznawania mowy, zanim znów bêdzie mo¿na go u¿ywaæ.}
{126}{}{W porz¹dku.}
{127}{}{System dzia³a teraz bez zarzutu.}
{128}{}{Przeszukujê zdjêcia z kamer bezpieczeñstwa, rozpoczynam odtwarzanie holograficzne...}
{129}{}{Gruthar, ju¿ tylko ty zosta³eœ. Plama twojego rodu zostanie niebawem wyczyszczona.}
{130}{}{Powiedz temu twojemu tak zwanemu prezydentowi, ¿e bêdzie siê za to sma¿y³.}
{131}{}{Tak, tak. Nigdy nie by³eœ niczym wiêcej ni¿ gadaj¹cym zwierzakiem.}
{132}{}{Byæ mo¿e, ale powstaliœmy na skutek waszych eksperymentów. Daliœcie nam ¿ycie!}
{133}{}{A teraz dam ci œmieræ.}
{134}{}{Zabierz jego cia³o. Doktor chcia³ dostaæ próbkê.}
{135}{}{Ich krew bêdzie p³ynê³a jak Nil!}
