{100}{}{Widzisz terminal komputerowy.}
{101}{}{Widzisz terminal z dostępem głosowym.}
{102}{}{Widzisz standardowy terminal przystosowany do przyjmowania poleceń głosowych.}
{103}{}{Oglądasz terminal, ale nie zauważasz niczego, co byłoby w oczywisty sposób niewłaściwe. Co teraz?}
{104}{}{Uderz go w ten "wyjątkowy" sposób.}
{105}{}{Kopnij go w to "wyjątkowe" miejsce.}
{106}{}{Uruchom program diagnostyczny.}
{107}{}{Otwórz go i zajrzyj do środka.}
{108}{}{Zostaw go w spokoju.}
{109}{}{Gapisz się przez chwilę na konsolę, by zdecydować, w które miejsce będzie najlepiej uderzyć. Po otrzymaniu twojego najlepszego uderzenia z serii "to-powinno-zadziałać", monitor kilka razy rozbłyska, po czym stabilizuje się. Nie ma żadnego innego efektu. Co teraz?}
{110}{}{Kopnij go w to "wyjątkowe" miejsce.}
{111}{}{Uruchom program diagnostyczny.}
{112}{}{Otwórz go i zajrzyj do środka.}
{113}{}{Zostaw go w spokoju.}
{114}{}{Ta szeroko znana metoda naprawcza powoduje dwa efekty. Po pierwsze, monitor przez kilka sekund wariuje, a potem stabilizuje się. Po drugie, słyszysz jeden z tych odgłosów łamanego metalu, po czym kopnięta przez ciebie płyta odpada na podłogę. Co teraz?}
{115}{}{Uruchom program diagnostyczny.}
{116}{}{Ta cholerna rzecz się otworzyła. Nie zaszkodzi zajrzeć do środka.}
{117}{}{Zostaw go w spokoju.}
{118}{}{Masz pewność, że w takim systemie powinien być dostępny zestaw procedur diagnostycznych. Jednakże wygląda na to, że wejście klawiaturowe zostało unieczynnione. Ten terminal przyjmuje tylko polecenia głosowe. Co teraz?}
{119}{}{Zostało już tylko zajrzeć do środka.}
{120}{}{Zostaw go w spokoju.}
{121}{}{Przyglądając się uważnie tej całej masie kabli i układów scalonych, zauważasz, że system niewątpliwie padł ofiarą sabotażu. Jednej z płyt, modułu rozpoznawania głosu, nie da się naprawić i musi zostać wymieniona. Teraz wszystko, co trzeba zrobić, to znaleźć odpowiednią część zamienną.}
{122}{}{Zrobione.}
{123}{}{Zrobione.}
{124}{}{Montujesz moduł w terminalu. System został naprawiony.}
{125}{}{Terminal potrzebuje modułu rozpoznawania mowy, zanim znów będzie można go używać.}
{126}{}{Zrobione.}
{127}{}{System działa teraz bez zarzutu.}
{128}{}{Przeszukuję zdjęcia z kamer bezpieczeństwa, rozpoczynam odtwarzanie holograficzne...}
{129}{}{Gruthar, już tylko ty zostałeś. Plama twojego rodu zostanie niebawem wyczyszczona.}
{130}{}{Powiedz temu twojemu tak zwanemu prezydentowi, że będzie się za to smażył.}
{131}{}{Tak, tak. Nigdy nie byłeś niczym więcej niż gadającym zwierzakiem.}
{132}{}{Być może, ale powstaliśmy na skutek waszych eksperymentów. Daliście nam życie!}
{133}{}{A teraz dam ci śmierć.}
{134}{}{Zabierz jego ciało. Doktor chciał dostać próbkę.}
{135}{}{Ich krew będzie płynęła jak Nil!}
