{100}{}{Widzisz starszego jegomościa sprawiającego miłe wrażenie.}
{101}{}{To dr Jubilee.}
{102}{}{To stary człowiek ze śnieżnobiałą brodą i lekko nieobecnym spojrzeniu.}
{103}{}{Jestem dr Jubilee. Co się stało, młody człowieku?}
{104}{}{Co się stało, młody człowieku?}
{105}{}{Moja ranne.}
{106}{}{Potrzebuję lekarza.}
{107}{}{A nie możesz po prostu wziąć jakichś pigułek czy co, żeby przestać mnie już męczyć tym marudzeniem?}
{108}{}{Do diabła, ledwo krwawisz.}
{109}{}{No nie wiem. Chyba nie dam rady jej uratować. Pewnie będziemy musieli amputować tę nogę.}
{110}{}{Chyba żartujesz.}
{111}{}{Ha-ha.}
{112}{}{Już lepiej synku.}
{113}{}{Znowu.}
{114}{}{Dzięki doktorze. Może mógłbyś wspomóc mnie odpowiedzią na kilka pytań?}
{115}{}{Żegnaj.}
{116}{}{To będzie kosztować 50$.}
{117}{}{Po prostu mnie wylecz.}
{118}{}{Nie zostanę tu ani chwili.}
{119}{}{Ty zrób ja lepiej.}
{120}{}{Moja iść już}
{121}{}{Nie. Nigdy nie żartuję. Będzie najlepiej, jeśli odetnę tę nogę, zanim wda się zakażenie.}
{122}{}{Nie ma mowy, żebyś cokolwiek odcinał, zrozumiano?}
{123}{}{Dosyć tego, wychodzę.}
{124}{}{Jak chcesz, ale jeśli zacznie ropieć, to nie miej do mnie pretensji.}
{125}{}{To nie jest darmowy szpital. Będziesz potrzebować gotówki zanim zabiorę się za cokolwiek.}
{126}{}{No więc, co mogę dla ciebie zrobić?}
{127}{}{Wal śmiało.}
{128}{}{Krypty 13?}
{129}{}{Wiesz może gdzie trzeba szukać Krypty 13?}
{130}{}{Ktoś kiedyś przy mnie mówił, że pan Westin ma się nie najlepiej. To prawda? Martwię się, że coś mogłoby mu się stać. Jest mi winien trochę pieniędzy.}
{131}{}{Jest taki koleś, Peklowany Bob, który twierdzi, że ukradłeś mu mapę. O co biega?}
{132}{}{Szukam pracy. Wiesz coś o jakiejś?}
{133}{}{Doktorze, nie wiesz przypadkiem czegoś o tej grupie, która walczy z tymi niegodziwymi łowcami niewolników, co?}
{134}{}{Nie masz się czym martwić. Jeśli tylko nie nadwyręży swojego organizmu, przeżyje nas wszystkich. Oczywiście o ile będzie przestrzegał moich zaleceń i brał swoje lekarstwa.}
{135}{}{Cóż, dobrze wiedzieć. Jest jeszcze coś, nad czym się zastanawiam.}
{136}{}{Dzięki doktorze.}
{137}{}{Ten stary pijak! Jedyna rzecz, jaką kiedykolwiek od niego wziąłem, to mój obraz, "Aksamitny Elvii" - w zastępstwie pieniędzy.}
{138}{}{Aksamitny Elvii? Czy mogę go zobaczyć?}
{139}{}{Niezupełnie mapa, co? No, pozwól, że zajmę twoje szare komórki czymś innym.}
{140}{}{No, muszę się już zbierać.}
{141}{}{Nikt mi o niej nie wspominał od czasu, gdy przyniesiono tu starego Peklowanego. Udar. Trząsł się w gorączce przez trzy dni, wrzeszcząc ciągle o tym, jak znalazł Kryptę 13 i tę całą jego Rdzenną Żyłę.}
{142}{}{Rdzenną Żyłę?}
{143}{}{Gdzie to jest?}
{144}{}{Gdzie Krypta?}
{145}{}{Nie umiem ci powiedzieć. Peklowany zawsze twierdził, że ma mapę, ale nikt nigdy jej nie widział.}
{146}{}{Peklowany?}
{147}{}{Pytać jeszcze.}
{148}{}{No cóż, zawsze to trochę więcej informacji, niż wcześniej.}
{149}{}{Bardzo dużą po prostu. Peklowany to stary poszukiwacz uranu - ściślej mówiąc, pijak. Żyje sobie teraz na posiadłości Westina.}
{150}{}{Kolejne pytanie...}
{151}{}{Dzięki za opowieść.}
{152}{}{Właściwie to miałem wielką nadzieję, że dostanę za niego trochę pieniędzy. Puszczę go za $}
{153}{}{Może później, mam jeszcze jedno pytanie...}
{154}{}{Może później, muszę już iść.}
{155}{}{Peklowany to stary poszukiwacz uranu. Żyje sobie teraz na posiadłości Westina.}
{156}{}{Kolejne pytanie...}
{157}{}{Dzięki za opowieść.}
{158}{}{Najlepiej pójdź z tym do prezydent Tandi. Słyszałem, że szuka osoby o specjalnych kwalifikacjach.}
{159}{}{Kolejne pytanie...}
{160}{}{Dziękuję.}
{161}{}{Może wiem... jest taka grupa skierowana przeciwko niewolnictwu i - no, także przeciwko większości innych występków. Można ich czasem spotkać w tym dużym sklepie, jak dłubią przy samochodzie.}
{162}{}{Kolejne pytanie...}
{163}{}{Dziękuję.}
{164}{}{Hej, zabieraj się od tego, ćwoku!}
{165}{}{Uważaj z tym! Już niewielka dawka może ci zaszkodzić.}
{166}{}{Odłóż to! Możesz sobie tym zrobić poważną krzywdę.}
{167}{}{Te leki są dla pana Westina, a nie dla ciebie. Odłóż je.}
{168}{}{Odsuń się stamtąd. Widzisz, muszę być ostrożny. Nie chciałbym, żeby pan Westin dostał teraz niewłaściwe leki.}
{169}{}{Uważaj! Dopiero co odmierzyłem dawkę dla pana Westina.}
{170}{}{Jestem dr Jubilee. Co się stało, młoda damo?}
{171}{}{Co się stało, młoda damo?}
{172}{}{Już lepiej, młoda damo.}
{173}{}{Młoda damo, nie masz się czym martwić. Jeśli tylko nie nadwyręży swojego organizmu, przeżyje nas wszystkich. Oczywiście o ile będzie przestrzegał moich zaleceń i brał swoje lekarstwa.}
{174}{}{Pewnie. Oto $}
{175}{}{Dzięki, usiłowałem wyciągnąć te pieniądze od Peklowanego, ale ten łąjdak nigdy ich nie ma.}
{176}{}{.}
