{100}{}{Widzisz starszego jegomoœcia sprawiaj¹cego mi³e wra¿enie.}
{101}{}{To dr Jubilee.}
{102}{}{To stary cz³owiek ze œnie¿nobia³¹ brod¹ i lekko nieobecnym spojrzeniu.}
{103}{}{Jestem dr Jubilee. Co siê sta³o, m³ody cz³owieku?}
{104}{}{Co siê sta³o, m³ody cz³owieku?}
{105}{}{Ja boli.}
{106}{}{Potrzebujê lekarza.}
{107}{}{A nie mo¿esz po prostu wzi¹æ jakichœ pigu³ek czy co, ¿eby przestaæ mnie ju¿ mêczyæ tym marudzeniem?}
{108}{}{Do diab³a, ledwo krwawisz.}
{109}{}{No nie wiem. Chyba nie dam rady jej uratowaæ. Pewnie bêdziemy musieli amputowaæ tê nogê.}
{110}{}{Chyba ¿artujesz.}
{111}{}{Ha-ha.}
{112}{}{Ju¿ lepiej synku.}
{113}{}{Znowu.}
{114}{}{Dziêki doktorze. Mo¿e móg³byœ wspomóc mnie odpowiedzi¹ na kilka pytañ?}
{115}{}{Do widzenia.}
{116}{}{To bêdzie kosztowaæ $50.}
{117}{}{Po prostu mnie wylecz.}
{118}{}{Nie zostanê tu ani chwili.}
{119}{}{Ty zrób ja lepiej.}
{120}{}{Ja iœæ ju¿.}
{121}{}{Nie. Nigdy nie ¿artujê. Bêdzie najlepiej, jeœli odetnê tê nogê, zanim wda siê zaka¿enie.}
{122}{}{Nie ma mowy, ¿ebyæ cokolwiek odcina³, zrozumiano?}
{123}{}{Dosyæ tego, wychodzê.}
{124}{}{Jak chcesz, ale jeœli zacznie ropieæ, to nie miej do mnie pretensji.}
{125}{}{To nie jest darmowy szpital. Bêdziesz potrzebowaæ gotówki zanim zabiorê siê za cokolwiek.}
{126}{}{No wiêc, co mogê dla ciebie zrobiæ?}
{127}{}{Wal œmia³o.}
{128}{}{Krypta 13?}
{129}{}{Wiesz mo¿e gdzie trzeba szukaæ Krypty 13?}
{130}{}{Ktoœ kiedyœ przy mnie mówi³, ¿e pan Westin ma siê nie najlepiej. To prawda? Martwiê siê, ¿e coœ mog³oby mu siê staæ. Jest mi winien trochê pieniêdzy.}
{131}{}{Jest taki koleœ, Saltbeef, który twierdzi, ¿e ukrad³eœ mu mapê. O co biega?}
{132}{}{Szukam pracy. Wiesz coœ o jakiejœ?}
{133}{}{Doktorze, nie wiesz przypadkiem czegoœ o tej grupie, która walczy z tymi niegodziwymi ³owcami niewolników, co?}
{134}{}{Nie masz siê czym martwiæ. Jeœli tylko nie nadwyrê¿y swojego organizmu, prze¿yje nas wszystkich. Oczywiœcie o ile bêdzie przestrzega³ moich zaleceñ i bra³ swoje lekarstwa.}
{135}{}{Och, dobrze wiedzieæ. Jest jeszcze coœ, nad czym siê zastanawiam.}
{136}{}{Dziêki doktorze.}
{137}{}{Ten stary pijak! Jedyna rzecz, jak¹ kiedykolwiek od niego wzi¹³em, to mój obraz, "Aksamitny Elvii" - w zastêpstwie pieniêdzy.}
{138}{}{Aksamitny Elvii? Czy mogê go zobaczyæ?}
{139}{}{Niezupe³nie mapa, co? No, pozwól, ¿e zajmê twoje szare komórki czymœ innym.}
{140}{}{No, muszê siê ju¿ zbieraæ.}
{141}{}{Nikt mi o niej nie wspomina³ od czasu, gdy przyniesiono tu starego Saltbeefa. Udar. Trz¹s³ siê w gor¹czce przez trzy dni, wrzeszcz¹c ci¹gle o tym, jak znalaz³ Kryptê 13 i tê ca³¹ jego Rdzenn¹ ¯y³ê.}
{142}{}{Rdzenn¹ ¯y³ê?}
{143}{}{Gdzie to jest?}
{144}{}{Gdzie krypta?}
{145}{}{Nie umiem ci powiedzieæ. Saltbeef zawsze twierdzi³, ¿e ma mapê, ale nikt nigdy jej nie widzia³.}
{146}{}{Saltbeef?}
{147}{}{Pytaæ jeszcze.}
{148}{}{No có¿, zawsze to trochê wiêcej informacji, ni¿ wczeœniej.}
{149}{}{Bardzo du¿¹ po prostu. Saltbeef to stary poszukiwacz uranu - œciœlej mówi¹c, pijak. ¯yje sobie teraz na posiad³oœci Westina.}
{150}{}{Jeszcze jedno pytanie...}
{151}{}{Dziêki za opowieœæ.}
#CMH changing per Fergus... Now you have to pay 1000 or steal the painting off of him.
{152}{}{W³aœciwie to mia³em wielk¹ nadziejê, ¿e dostanê za niego trochê pieniêdzy. Puszczê go za $}
{153}{}{Mo¿e póŸniej, mam jeszcze jedno pytanie...}
{154}{}{Mo¿e póŸniej, muszê ju¿ iœæ.}
{155}{}{Saltbeef to stary poszukiwacz uranu. ¯yje sobie teraz na posiad³oœci Westina.}
{156}{}{Jeszcze jedno pytanie...}
{157}{}{Dziêki za opowieœæ.}
{158}{}{Najlepiej pójdŸ z tym do prezydent Tandi. S³ysza³em, ¿e szuka osoby o specjalnych kwalifikacjach.}
{159}{}{Jeszcze jedno pytanie...}
{160}{}{Dziêki.}
{161}{}{Mo¿e wiem... jest taka grupa skierowana przeciwko niewolnictwu i - no, tak¿e przeciwko wiêkszoœci innych wystêpków.}
{162}{}{Jeszcze jedno pytanie...}
{163}{}{Dziêki.}
{164}{}{Hej, zabieraj siê od tego, æwoku!}
{165}{}{Uwa¿aj z tym! Ju¿ niewielka dawka mo¿e ci zaszkodziæ.}
{166}{}{Od³ó¿ to! Mo¿esz sobie tym zrobiæ powa¿n¹ krzywdê.}
{167}{}{Te laki s¹ dla pana Westina, a nie dla ciebie. Od³ó¿ je.}
{168}{}{Odsuñ siê stamt¹d. Widzisz, muszê byæ ostro¿ny. Nie chcia³bym, ¿eby pan Westin dosta³ teraz niew³aœciwe leki.}
{169}{}{Uwa¿aj! Dopiero co odmierzy³em dawkê dla pana Westina.}

{170}{}{Jestem dr Jubilee. Co siê sta³o, m³oda damo?}
{171}{}{Co siê sta³o, m³oda damo?}
{172}{}{Ju¿ lepiej, m³oda damo.}
{173}{}{M³oda damo, nie masz siê czym martwiæ. Jeœli tylko nie nadwyrê¿y swojego organizmu, prze¿yje nas wszystkich. Oczywiœcie o ile bêdzie przestrzega³ moich zaleceñ i bra³ swoje lekarstwa.}
{174}{}{Pewnie. Oto $}
{175}{}{Dziêki, usi³owa³em wyci¹gn¹æ te pieni¹dze od Saltbeefa, ale ten ladaco nigdy ich nie ma.}
{176}{}{.}
