{100}{}{Widzisz ładną, młodą kobietę ubraną w uniform bojowy.}
{101}{}{To Elise.}
{102}{}{Wokół niej roztacza się aura karności, tak jakby była przyzwyczajona do wydawania rozkazów i, że inni je wykonają.}
{103}{}{Czego chcesz?}
{104}{}{Znowu ty?}
{105}{}{Przysyła mnie Karl.}
{106}{}{Doktor Jubilee powiedział, że mam z tobą porozmawiać.}
{107}{}{Kim jesteś?}
{108}{}{Gy?}
{109}{}{Szukam pewnej grupy. Takiej, która nienawidzi niewolnictwa. Nazywają się Strażnikami Republiki Nowej Kalifornii.}
{110}{}{Czy możesz naprawić mój samochód?}
{111}{}{Ee - to miejsce wydawało mi się być opuszczone.}
{112}{}{Tak? Co ci powiedział?}
{113}{}{Niewiele. Że jesteście dobrymi ludźmi i, że być może zechcę się z wami związać.}
{114}{}{Powiedział, że płacicie niezłą kasę.}
{115}{}{Jestem Elise. To jest Gond. Jesteśmy członkami "grupy", która próbuje czynić dobro dla ludzi.}
{116}{}{Nie wyglądacie mi na organizację charytatywną, ani na kościół.}
{117}{}{Brzmi interesująco. Dokładniej w jaki sposób?}
{118}{}{Chcę tylko naprawić mój samochód.}
{119}{}{Wynoś się stąd. Saloon jest na głównej ulicy.}
{120}{}{Nienawidzi niewolnictwa, hmm. Ciekawe. A co zrobisz, gdy już znajdziesz tę grupę?}
{121}{}{Spytam, czy nie chcieliby mniej przyjąć.}
{122}{}{Skopię im tyłki.}
{123}{}{Nic nic.}
{124}{}{Nie twój interes. A teraz spadaj.}
{125}{}{Interes samochodowy jest już zamknięty, nieodwołalnie. Do widzenia.}
{126}{}{Nie. Do widzenia.}
{127}{}{W porządku, więc powiedz mi... co myślisz o łowcach niewolników?}
{128}{}{Nienawidzę ich. Obrzydliwe, nikczemne szumowiny Ziemi.}
{129}{}{Jeżeli zostawiają mnie w spokoju, to i ja ich zostawiam w spokoju.}
{130}{}{Niektórzy z moich najlepszych kumpli są łowcami niewolników.}
{131}{}{Czy tylko zależy ci na pieniądzach?}
{132}{}{Oczywiście, że nie. Wierzę w prawdę, sprawiedliwość i walkę w obronie uciśnionych,}
{133}{}{To początek - dopóki ktoś nie poda mi lepszej sprawy, dla której można by walczyć.}
{134}{}{A jest coś więcej?}
{135}{}{Nie wciskaj mi kitu. Widzę przecież, z kim mam do czynienia. Żegnam.}
{136}{}{Jeżeli nie wiesz, to tracę swój czas. Do widzenia.}
{137}{}{Nie, nie jesteśmy organizacją religijną. Mogę ci zadać pytanie?}
{138}{}{Jasne, mów.}
{139}{}{Nie tak szybko. Musisz zdać test, aby przyłączyć się do Strażników.}
{140}{}{W porządku. Mów.}
{141}{}{Test? Co to jest - szkoła?}
{142}{}{Na zewnątrz miasta jest łowca niewolników. Może rzucił ci się już w oczy jego obóz. Uwolnij tam niewolników, a potem wróć i porozmawiamy.}
{143}{}{Mogę to zrobić.}
{144}{}{Nie ma mowy. Nie chcę tu mieć żadnych kłopotów.}
{145}{}{Cóż, to twój szczęśliwy dzień.}
{146}{}{Właśnie takie podejście jest główną przyczyną istnienia okrucieństwa niewolnictwa. Przykro mi, ale nie ma dla ciebie miejsca w naszej organizacji.}
{147}{}{W porządku.}
{148}{}{Więc, zmiana zdania? Czy możesz już udowodnić swoją wartość?}
{149}{}{Jasne.}
{150}{}{Co dokładnie chcieliście mieć załatwione?}
{151}{}{Czy nie masz jakiejś roboty? Nie wracaj, dopóki zadanie nie zostanie wykonane.}
{152}{}{Słyszałam już wieści. Niewolnicy są wolni. Dobra robota! A więc czy chcesz już zostać Strażnikiem?}
{153}{}{Tak.}
{154}{}{Nie.}
{155}{}{Słyszałam, że to dzięki tobie wszyscy niewolnicy z przedmieścia zostali uwolnieni. To wspaniały czyn i chciałabym ci uścisnąć dłoń.}
{156}{}{Dziękuję.}
{157}{}{To proste. Wierzymy, że niewolnictwo jest złe i zrobimy wszystko aby je zwalczać. W RNK mamy wielu wysoko postawionych przyjaciół. Dzięki nim już zabroniliśmy niewolnictwa na południu, ale teraz mamy nadzieję szerzyć słowo na północy.}
{158}{}{Z dumą dołączę do takiej grupy, jak Strażnicy. Zapiszcie mnie.}
{159}{}{Interesujące... pomyślę o tym, co powiedziałaś.}
{160}{}{Czy przysięgasz walczyć z niewolnictwem, kiedy tylko wystąpi po temu sposobność i pomagać innym Strażnikom, kiedy tylko będą w potrzebie?}
{161}{}{Tak.}
{162}{}{Nie.}
{163}{}{Gratulacje, należysz teraz do Strażników.}
{164}{}{Miło cię widzieć, Strażniku. Obawiam się jednak, że w tej chwili nie ma tu dużo do roboty. Większość ludzi jest już na patrolach. Rozpowiem wszystkim, że należysz do nas. Nie chciałabym, aby któryś z nas cię zastrzelił.}
{165}{}{Cóż, zawsze szukamy dobrych ludzi, którzy pociągną dalej naszą sprawę. Jeżeli zmienisz zdanie, przyjdź do mnie. Z pewnością nie chcesz się teraz przyłączyć?}
{166}{}{Na pewno.}
{167}{}{Cóż, teraz, gdy o tym mówisz, chyba jednak chcę zostać Strażnikiem.}
{168}{}{Rozumiem. Cóż, reprezentuję grupę nazywaną Strażnikami Republiki Nowej Kalifornii. Ktoś z takimi poglądami, jak twoje, mógłby kwalifikować się na członka. Interesuje cię to?}
{169}{}{Wspaniale! Zapiszcie mnie.}
{170}{}{Brzmi interesująco. Co możesz mi powiedzieć o Strażnikach?}
{171}{}{Rozumiem. Dzięki za odwiedziny, ale nie widzę niczego innego, co moglibyśmy sobie powiedzieć. Jeżeli zmienisz zdanie, wróć i zobacz się ze mną.}
{172}{}{W porządku.}
{173}{}{W takim razie muszę prosić cię o zejście mi z oczu. Już!}
{174}{}{W porządku.}
{175}{}{Łowca niewolników! Wynoś się stąd zanim usunę ci ten tatuaż kulą!}
{176}{}{Jasne.}
{177}{}{Tylko spróbuj!}
{178}{}{Mamy agentów i sympatyków w niektórych miastach na północy. Roznosimy słowo i uderzamy w łowców niewolników gdzie tylko możemy.}
{179}{}{Witaj ponownie. Czy chcesz się jednak przyłączyć?}
{180}{}{Nieważne.}
{181}{}{To nie należy do ciebie. A teraz wyjdź, zanim okażę przemoc.}
{182}{}{Nie wiem, co się przez ciebie stało Gondowi, ale zapłacisz za to!}
