{100}{}{Widzisz ³adn¹, m³od¹ kobietê ubran¹ w uniform bojowy.}
{101}{}{To Elise.}
{102}{}{Wokó³ niej roztacza siê aura karnoœci, tak jakby by³a przyzwyczajona do wydawania rozkazów i, ¿e inni je wykonaj¹.}
{103}{}{Co chcesz zrobiæ?}
{104}{}{Znowu ty?}
{105}{}{Przysy³a mnie Karl.}
{106}{}{Doktor Jubilee powiedzia³, ¿e mam z tob¹ porozmawiaæ.}
{107}{}{Kim jesteœ?}
{108}{}{Gy?}
{109}{}{Szukam pewnej grupy. Takiej, która nienawidzi niewolnictwa. Nazywaj¹ siê Stra¿nikami Republiki Nowej Kalifornii.}
{110}{}{Czy mo¿esz naprawiæ mój samochód?}
{111}{}{Ee - to miejsce wydawa³o mi siê byæ opuszczone.}
{112}{}{Tak? Co ci powiedzia³?}
{113}{}{Niewiele. ¯e jesteœcie dobrymi ludŸmi i, ¿e byæ mo¿e zechcê siê z wami zwi¹zaæ.}
{114}{}{Powiedzia³, ¿e p³acicie niez³¹ kasê.}
{115}{}{Jestem Elise. To jest Gond. Jesteœmy cz³onkami "grupy", która próbuje czyniæ dobro dla ludzi.}
{116}{}{Nie wygl¹dacie mi na organizacjê charytatywn¹, ani na koœció³.}
{117}{}{Brzmi interesuj¹co. Dok³adniej w jaki sposób?}
{118}{}{Chcê tylko naprawiæ mój samochód.}
{119}{}{Wynoœ siê st¹d. Saloon jest na g³ównej ulicy.}
{120}{}{Nienawidzi niewolnictwa, hmm. Ciekawe. A co zrobisz, gdy ju¿ znajdziesz tê grupê?}
{121}{}{Spytam, czy nie chcieliby mniej przyj¹æ.}
{122}{}{Skopiê im ty³ki.}
{123}{}{Niczego.}
{124}{}{Nie twój interes. A teraz spadaj.}
{125}{}{Interes samochodowy jest ju¿ zamkniêty, nieodwo³alnie. Do widzenia.}
{126}{}{Nie. Do widzenia.}
{127}{}{W porz¹dku, wiêc powiedz mi... co myœlisz o ³owcach niewolników?}
{128}{}{Nienawidzê ich. Obrzydliwe, nikczemne szumowiny Ziemi.}
{129}{}{Je¿eli zostawiaj¹ mnie w spokoju, to i ja ich zostawiam w spokoju.}
{130}{}{Niektórzy z moich najlepszych kumpli s¹ ³owcami niewolników.}
{131}{}{Czy tylko zale¿y ci na pieni¹dzach?}
{132}{}{Oczywiœcie, ¿e nie. Wierzê w prawdê, sprawiedliwoœæ i walkê w obronie uciœnionych,}
{133}{}{To pocz¹tek - dopóki ktoœ nie poda mi lepszej sprawy, dla której mo¿na by walczyæ.}
{134}{}{A jest coœ wiêcej?}
{135}{}{Nie wciskaj mi kitu. Widzê przecie¿, z kim mam do czynienia. ¯egnam.}
{136}{}{Je¿eli nie wiesz, to tracê swój czas. Do widzenia.}
{137}{}{Nie, nie jesteœmy organizacj¹ religijn¹. Mogê ci zadaæ pytanie?}
{138}{}{Jasne, mów.}
{139}{}{Nie tak szybko. Musisz zdaæ test, aby przy³¹czyæ siê do Stra¿ników.}
{140}{}{W porz¹dku. Mów.}
{141}{}{Test? Co to jest - szko³a?}
{142}{}{Na zewn¹trz miasta jest ³owca niewolników. Mo¿e rzuci³ ci siê ju¿ w oczy jego obóz. Uwolnij tam niewolników, a potem wróæ i porozmawiamy.}
{143}{}{Mogê to zrobiæ.}
{144}{}{Nie ma mowy. Nie chcê tu mieæ ¿adnych k³opotów.}
{145}{}{Có¿, to twój szczêœliwy dzieñ.}
{146}{}{W³aœnie takie podejœcie jest g³ówn¹ przyczyn¹ istnienia okrucieñstwa niewolnictwa. Przykro mi, ale nie ma dla ciebie miejsca w naszej organizacji.}
{147}{}{Dobrze.}
{148}{}{Wiêc, zmiana zdania? Czy mo¿esz ju¿ udowodniæ swoj¹ wartoœæ?}
{149}{}{Jasne.}
{150}{}{Co dok³adnie chcieliœcie mieæ za³atwione?}
{151}{}{Czy nie masz jakiejœ roboty? Nie wracaj, dopóki zadanie nie zostanie wykonane.}
{152}{}{S³ysza³am ju¿ wieœci. Niewolnicy s¹ wolni. Dobra robota! A wiêc czy chcesz ju¿ zostaæ Stra¿nikiem?}
{153}{}{Tak.}
{154}{}{Nie.}
{155}{}{S³ysza³am, ¿e to dziêki tobie wszyscy niewolnicy z przedmieœcia zostali uwolnieni. To wspania³y czyn i chcia³abym ci uœcisn¹æ d³oñ.}
{156}{}{Dziêki.}
{157}{}{To proste. Wierzymy, ¿e niewolnictwo jest z³e i zrobimy wszystko aby je zwalczaæ. W RNK mamy wielu wysoko postawionych przyjació³. Dziêki nim ju¿ zabroniliœmy niewolnictwa na po³udniu, ale teraz mamy nadziejê szerzyæ s³owo na pó³nocy.}
{158}{}{Z dum¹ do³¹czê do takiej grupy, jak Stra¿nicy. Zapiszcie mnie.}
{159}{}{Interesuj¹ce... pomyœlê o tym, co powiedzia³aœ.}
{160}{}{Czy przysiêgasz walczyæ z niewolnictwem, kiedy tylko wyst¹pi po temu sposobnoœæ i pomagaæ innym Stra¿nikom, kiedy tylko bêd¹ w potrzebie?}
{161}{}{Tak.}
{162}{}{Nie.}
{163}{}{Gratulacje, nale¿ysz teraz do Stra¿ników.}
{164}{}{Mi³o ciê widzieæ, Stra¿niku. Obawiam siê jednak, ¿e w tej chwili nie ma tu du¿o do roboty. Wiêkszoœæ ludzi jest ju¿ na patrolach. Rozpowiem wszystkim, ¿e nale¿ysz do nas. Nie chcia³abym, aby któryœ z nas ciê zastrzeli³.}
{165}{}{Có¿, zawsze szukamy dobrych ludzi, którzy poci¹gn¹ dalej nasz¹ sprawê. Je¿eli zmienisz zdanie, przyjdŸ do mnie. Z pewnoœci¹ nie chcesz siê teraz przy³¹czyæ?}
{166}{}{Na pewno.}
{167}{}{Có¿, teraz, gdy o tym mówisz, chyba jednak chcê zostaæ Stra¿nikiem.}
{168}{}{Rozumiem. Có¿, reprezentujê grupê nazywan¹ Stra¿nikami Republiki Nowej Kalifornii. Ktoœ z takimi pogl¹dami, jak twoje, móg³by kwalifikowaæ siê na cz³onka. Interesuje ciê to?}
{169}{}{Wspaniale! Zapiszcie mnie.}
{170}{}{Brzmi interesuj¹co. Co mo¿esz mi powiedzieæ o Stra¿nikach?}
{171}{}{Rozumiem. Dziêki za odwiedziny, ale nie widzê niczego innego, co moglibyœmy sobie powiedzieæ. Je¿eli zmienisz zdanie, wróæ i zobacz siê ze mn¹.}
{172}{}{Dobrze.}
{173}{}{W takim razie muszê prosiæ ciê o zejœcie mi z oczu. Ju¿!}
{174}{}{Dobrze.}
{175}{}{£owca niewolników! Wynoœ siê st¹d zanim usunê ci ten tatua¿ kul¹!}
{176}{}{Jasne.}
{177}{}{Tylko spróbuj!}
{178}{}{Mamy agentów i sympatyków w niektórych miastach na pó³nocy. Roznosimy s³owo i uderzamy w ³owców niewolników gdzie tylko mo¿emy.}
{179}{}{Witaj ponownie. Czy chcesz siê jednak przy³¹czyæ?}
{180}{}{Niewa¿ne.}
{181}{}{To nie nale¿y do ciebie. A teraz wyjdŸ, zanim oka¿ê przemoc.}
{182}{}{Nie wiem, co siê przez ciebie sta³o Gondowi, ale zap³acisz za to!}
