{100}{}{To jest du¿y supermutant.}
{101}{}{To jest Gond, supermutant.}
{102}{}{Jest du¿y, jest zielony i nie wygl¹da na m¹drzejszego od innych takich jak on.}
{103}{}{Hej, Elise pozwoli³a ci tu przyjœæ?}
{104}{}{Ty te¿ jesteœ Stra¿nik?}
{105}{}{Nie powinno ciê tu byæ.}
{106}{}{Witaj (bracie/siostro).}
{107}{}{Praca Stra¿nika nigdy siê nie koñczy.}
{108}{}{Radujmy siê! Jeden z naszych braci w zesz³ym tygodniu zniszczy³ obóz ³owców niewolników.}
