{100}{}{To muskularny facet, z rozwiniêt¹ klat¹.}
{101}{}{To Hal, szef spêdu braminów.}
{102}{}{¯uje kawa³ek czegoœ co, masz nadziejê, nie wypluje w twoj¹ stronê, bo œmierdzi to jak diabli.}
{103}{}{Jesteœ tu na spêd?}
{104}{}{}
{105}{}{Tak.}
{106}{}{Nie.}
{107}{}{Potrzebujê wózków z Redding!!!}
{108}{}{Ta, potrzebujê wózków z Redding!!}
{109}{}{Ciekawe, za ile tu chodz¹ wózki z Redding.}
{110}{}{Super. Bierz je. ProwadŸ je do ch³opaków z Redding!}
{111}{}{Wiêc zostaw mnie w spokoju. Mam 500 bramiñskich g³ów do wyprowadzenia na szlak.}
{112}{}{Znowu ty? OdejdŸ.}
{113}{}{Có¿, to dopiero by³a rzeŸnia! Bojê siê, ¿e w tym spêdzie nie ma kasy dla ¿adnego z nas. Ciesz siê, ¿e ¿yjesz.}
{114}{}{Có¿, ranczerzy nie s¹ zbyt zadowoleni - za ten spêd tylko $1000. Cholerne szczêœcie.}
{115}{}{Có¿, mieliœmy troszkê pecha, ale uda³o nam siê. Oto $2000, na które siê umówiliœmy.}
{116}{}{Cholera, doskonale ci posz³o! Oto $1000 premii dla ciebie. To i $2000 razem daje twoj¹ zap³atê. Niech Redding lepiej dzisiaj w nocy uwa¿a!}
{117}{}{Dalej pod¹¿asz ju¿ beze mnie. Dobrze siê z tob¹ podró¿owa³o.}
