{100}{}{Widzisz mê¿czyznê w brudnym, poplamionym krwi¹ ubraniu.}
{101}{}{To wiêzieñ.}
{102}{}{Jego twarz i ramiona pokrywaj¹ stare blizny od ciêæ no¿em, a szalone spojrzenie jego oczu mówi ci, ¿e jest on bandyt¹ wyjêtym spod prawa.}
{103}{}{Marnujesz mój czas. Nie mam ci, ani nikomu innemu nic do powiedzenia.}
{104}{}{Odwal siê ode mnie, œwinio.}
{105}{}{Czy¿by nagle zaczê³o tu œmierdzieæ?}
{106}{}{No i co zrobisz - zmusisz mnie do mówienia?}
{107}{}{Nie przestraszysz mnie.}
{108}{}{Czemu po prostu nie poca³ujesz mnie gdzieœ?}
{109}{}{Co do cholery? Próbujesz mnie zabiæ! Stra¿nik!}
{110}{}{Gadaæ lub moja zabiæ.}
{111}{}{Nikt tu nie przyjdzie, ¿eby ci pomóc. Jeœli chcesz ¿yæ, to lepiej zacznij gadaæ.}
{112}{}{Okej, okej! Co chcesz wiedzieæ? Tylko nie rób mi ju¿ wiêcej krzywdy.}
{113}{}{Krypta 15 - ty gadaæ.}
{114}{}{Co wiesz o Krypcie 15?}
{115}{}{Look, I'm just a guy, not the guy in charge - that's Darion. He's the one you want. He's got this thing about Shady Sands and that old bitch Tandi. He's got a hideout in Vault 15, even got the locals thinking he's on their side.  That's all I know. Honest!}
{116}{}{Naprawdê, nie wiem nic wiêcej! Powiedzia³em ci wszystko, co wiem, s³owo! Nie rób mi wiêcej krzywdy.}
{117}{}{Nie ma mowy! Nie dam siê nabraæ na ten numer. BUM! - Zastrzelony podczas próby ucieczki. Zapomnij o tym!}
