{100}{}{Widzisz mężczyznę w brudnym, poplamionym krwią ubraniu.}
{101}{}{To więzień.}
{102}{}{Jego twarz i ramiona pokrywają stare blizny od cięć nożem, a szalone spojrzenie jego oczu mówi ci, że jest on bandytą wyjętym spod prawa.}
{103}{}{Marnujesz mój czas. Nie mam ci, ani nikomu innemu nic do powiedzenia.}
{104}{}{Odwal się ode mnie, świnio.}
{105}{}{Czyżby nagle zaczęło tu śmierdzieć?}
{106}{}{No i co zrobisz - zmusisz mnie do mówienia?}
{107}{}{Nie przestraszysz mnie.}
{108}{}{Czemu po prostu nie pocałujesz mnie gdzieś?}
{109}{}{Co do cholery? Próbujesz mnie zabić! Strażnik!}
{110}{}{Gadać lub moja zabić.}
{111}{}{Nikt tu nie przyjdzie, żeby ci pomóc. Jeśli chcesz żyć, to lepiej zacznij gadać.}
{112}{}{Okej, okej! Co chcesz wiedzieć? Tylko nie rób mi już więcej krzywdy.}
{113}{}{Krypta 15 - ty gadać.}
{114}{}{Co wiesz o Krypcie 15?}
{115}{}{Look, I'm just a guy, not the guy in charge - that's Darion. He's the one you want. He's got this thing about Shady Sands and that old bitch Tandi. He's got a hideout in Vault 15, even got the locals thinking he's on their side.  That's all I know. Honest!}
{116}{}{Naprawdę, nie wiem nic więcej! Powiedziałem ci wszystko, co wiem, słowo! Nie rób mi więcej krzywdy.}
{117}{}{Nie ma mowy! Nie dam się nabrać na ten numer. BUM! - Zastrzelony podczas próby ucieczki. Zapomnij o tym!}
