{100}{}{Widzisz wychudzonego starca z piórem zatkniętym za ucho i okularami balansującymi na końcu nosa.}
{101}{}{To Vortis, właściciel tego obozu niewolników.}
{102}{}{Ma co najwyżej trzy zęby. Jego palce i koszula są ubrudzone niebieskim atramentem. Na jego czole widzisz porządnie zamazany tatuaż łowcy niewolników.}
{103}{}{No, czego chcesz?}
{104}{}{Bracie, witaj w domu Vortisa. Jak mogę ci pomóc?}
{105}{}{Zaczynasz mnie denerwować.}
{106}{}{To miejsce należy do mnie, a ja, Vortis, prowadzę uczciwy i legalny interes bez względu na to, co mówią ci dranie z RNK. Ponieważ RNK nie zezwala na trzymanie niewolników wewnątrz, ja opiekuje się nimi dla ludzi, którzy pracują w mieście.}
{107}{}{Głupi jesteś, czy co? To jest obóz niewolników. Mam na niego licencję.}
{108}{}{}
{109}{}{Mam tylko kilka pytań.}
{110}{}{Szukam pracy.}
{111}{}{Hm?}
{112}{}{Nie być wygódka? Moja iść.}
{113}{}{Co to za miejsce?}
{114}{}{Nic, pomyliłem miejsca.}
{115}{}{O, patrzcie - wypieszczony laluś z lizaczkiem w łapce. Chłopcy, znieście tego palanta sprzed moich oczu!}
{116}{}{Pieprzyć to.}
{117}{}{No i?}
{118}{}{Szukam Krypty 13.}
{119}{}{Masz może GECK?}
{120}{}{Co możesz mi powiedzieć o tym mieście?}
{121}{}{Pieprzony łowco niewolników! Dlaczego nie miałbym cię rozwalić?}
{122}{}{Słyszałem o tych gościach - Strażnikach Nowej Kalifornii. Macie z nimi jakieś kłopoty?}
{123}{}{Pozwolisz, że się trochę porozglądam?}
{124}{}{Praca? Cóż... może coś się znajdzie. Słyszałeś kiedyś o Strażnikach Nowej Kalifornii?}
{125}{}{Tak.}
{126}{}{Nie.}
{127}{}{Pierdol się. Chłopcy, eskortujcie tego palanta do drzwi.}
{128}{}{Pocałuj mnie w dupę!}
{129}{}{Krypta 13! Spadaj stąd. To przeklęte miejsce to mit. Krypta 13, też coś.}
{130}{}{Kolejne pytanie...}
{131}{}{Cóż, dzięki za nic.}
{132}{}{Co? No cóż, cokolwiek to jest nie mam tego.}
{133}{}{Kolejne pytanie...}
{134}{}{Cóż, dzięki za nic.}
{135}{}{Republika Nowej Kalifornii - miasto wyrachowanych, zimnych drani i kupców. Mają świra na punkcie łowców niewolników i niewolnictwa, ale do cholery, ja z tego żyję.}
{136}{}{Kolejne pytanie...}
{137}{}{Dzięki, muszę spadać.}
{138}{}{Ktoś cię skierował pod zły adres. Ja nie mam kłopotów z nikim - zwłaszcza ze Strażnikami. Wszystko co robię jest legalne, więc nic na mnie nie mają.}
{139}{}{Kolejne pytanie...}
{140}{}{Cokolwiek powiesz. Już sobie idę.}
{141}{}{Taa, być może mam pewne odczucia co do Strażników. Szukasz pracy?}
{142}{}{Tak.}
{143}{}{Nie.}
{144}{}{Nie, nie wolno ci się tu szwendać, pojebie! To nie jest muzeum!}
{145}{}{Kolejne pytanie...}
{146}{}{Przestań mnie ciągle obrażać. Spadam stąd.}
{147}{}{W takim razie musisz wiedzieć, że dla niektórych są źródłem nieustannych problemów. Byłoby cholernie fajnie mieć w posiadaniu mapę ich kryjówek na północy - w Nowym Reno, Klamath, gdziekolwiek. Zapłacę ci, powiedzmy, 500$ za coś takiego. Myślisz, że możesz to dla mnie zdobyć?}
{148}{}{Jasne.}
{149}{}{Nie wydaje mi się.}
{150}{}{W takim razie ci powiem. Ci Strażnicy postanowili skończyć raz na zawsze z nami i niewolnictwem. Sprawiają dużo kłopotu ciężko pracującym ludziom.}
{151}{}{Działają w tajemnicy, zwłaszcza na północy.}
{152}{}{Jezu, mam ci to przeliterować? Najeżdżają na nas, wyzwalają niewolników i szmuglują ich na południe, na tereny RNK, gdzie niewolnictwo jest nielegalne. Interesuje cię to?}
{153}{}{Nie ma żadnego "i"! Bierzesz tę robotę, czy nie?}
{154}{}{No i?}
{155}{}{Co mam zrobić?}
{156}{}{Świetnie. Będę tu niecierpliwie czekał na mapę.}
{157}{}{Gdzie znajdę tę mapę?}
{158}{}{W porządku, ale mam jeszcze kilka pytań.}
{159}{}{Wchodzę w to. Zobaczymy się później.}
{160}{}{Skąd do cholery mam wiedzieć!? Gdybym wiedział, miałbym ją, co nie? Wiem tylko, że mają jakąś norę gdzieś w mieście. Znajdź ich i zobacz, co da się zrobić.}
{161}{}{Jeszcze kilka pytań.}
{162}{}{W porządku. Jeszcze tu wrócę.}
{163}{}{To znowu ty. Masz mapę?}
{164}{}{Tak.}
{165}{}{Nie.}
{166}{}{Najpierw skończ pierwszą robotę!}
{167}{}{A tak, wypadło mi to z pamięci.}
{168}{}{Nie, od kiedy wykonałeś swoją robotę. Dzięki.}
{169}{}{Jedno lub dwa pytanka.}
{170}{}{Nie ma sprawy. Cześć.}
{171}{}{Dobra robota. Najlepsze, co teraz możesz zrobić, to ulotnić się, na wypadek gdyby Strażnicy czegoś się domyślili.}
{172}{}{Interesy z tobą to przyjemność.}
{173}{}{Nie szwendaj się tutaj kretynie! Ktoś może nabrać podejrzeń.}
{174}{}{W porządku, łapię o co biega.}
{175}{}{Co do cholery? Straże! Mamy intruza!}
{176}{}{Wejdź tam, a rozpierdolę ci łeb. Kapujesz?}
{177}{}{Jest już późno, mamy zamknięte. Wróć rano.}
