{100}{}{Widzisz tablicê og³oszeniow¹.}
{101}{}{Widzisz tablicê z wywieszonymi prawami RNK.}
{102}{}{To typowa tablica og³oszeniowa z kilkoma przypiêtymi kartkami papieru. Najwa¿niejsze z nich to prawa RNK.}
{103}{}{Witamy w Republice Nowej Kalifornii! Zanim wejdziesz do naszego sprawiedliwego miasta, poœwiêæ chwilê czasu na zapoznanie siê z nastêpuj¹cymi prawami i regulacjami.}
{104}{}{¯adna broñ nie mo¿e byæ otwarcie noszona w murach miasta.}
{105}{}{Osoby zatrzymane pod wp³ywem alkoholu lub narkotyków zostan¹ aresztowane.}
{106}{}{Niewolnictwo, hazard i prostytucja s¹ zabronione na terenie miasta.}
{107}{}{Nieznajomoœæ prawa szkodzi i nie mo¿e byæ ¿adnym wyt³umaczeniem. G³upek dostanie w ty³ek równie szybko, jak m¹drala.}
{108}{}{Je¿eli nie potrafisz ¿yæ wed³ug tych praw - to wynoœ siê st¹d!}
{109}{}{Lepiej od³ó¿ swoj¹ broñ. Mówimy powa¿nie.}
{110}{}{Podporz¹dkowanie siê prawu to œwiadectwo dobrego obywatelstwa.}
{111}{}{Powróæ}
{112}{}{Wystarczy ju¿ tego czytania.}
{113}{}{To nie jest dobry znak dla twoich rekreacyjnych zwyczajów.}
{114}{}{Dobrze, nie bêdzie przynajmniej pijaczków, czy obszarpañców naprzykrzaj¹cych ci siê o jak¹œ ja³mu¿nê.}
{115}{}{Powróæ}
{116}{}{Wystarczy ju¿ tego czytania.}
{117}{}{Có¿, oto jak kilka dodatkowych dochodowych interesów jest spuszczanych z wod¹ w klozecie!}
{118}{}{Wygl¹da na to, ¿e staraja siê stworzyæ szanowane, porz¹dne spo³eczeñstwo.}
{119}{}{Powróæ}
{120}{}{Wystarczy ju¿ tego czytania.}
{121}{}{Ostre s³owa. Mo¿e nawet warto by zobaczyæ, czy mo¿esz zrobiæ tak, aby siê nimi ud³awili.}
{122}{}{Równoœæ przed prawem to dobra rzecz.}
{123}{}{Powróæ}
{124}{}{Wystarczy ju¿ tego czytania.}
{125}{}{Nauczenie tych goœci odrobny respektu coraz bardziej wysuwa siê na czo³o twojej listy "rzeczy do zrobienia".}
{126}{}{Powiedziane nieco bez ogródek, ale to uœwiadamia, o co tu chodzi.}
{127}{}{Powróæ}
{128}{}{Wystarczy ju¿ tego czytania.}
