{100}{}{Widzisz starszego mê¿czyznê z g³êbokimi zmarszczkami na twarzy. Nawet jeœli widzi, ¿e mu siê przygl¹dasz, to nie okazuje tego.}
{101}{}{Widzisz Cassidy'ego.}
{102}{}{Widzisz starszego mê¿czyznê z g³êbokimi zmarszczkami na twarzy. Kiwa do ciebie g³ow¹.}
{103}{}{Well, now. I ain't seen you around before, stranger. Name's Cassidy. I run this place. What can I do for you?}
{104}{}{Well now, if it ain't the mysterious stranger. What can I do for you today?}
{105}{}{Ug Nog?}
{106}{}{OdejdŸ bez s³owa.}
{107}{}{Szukam Krypty.}
{108}{}{Czy wci¹¿ myœlisz o tym, ¿eby siê st¹d wynieœæ?}
{109}{}{Co masz do picia?}
{110}{}{Dzieje siê tutaj coœ ciekawego?}
{111}{}{Dziêki, ale dziœ nie skorzystam.}
{112}{}{Hit on the head a little too often, eh? Sorry, I don't speak imbecile.}
{113}{}{Ne-mu?}
{114}{}{Vault? Only Vault I know of is the one inside the city. Big friggin' hole... you can't miss it, trust me.}
{115}{}{Masz coœ do picia?}
{116}{}{Dzieje siê tutaj coœ ciekawego?}
{117}{}{Dziêki za wskazówki. Powodzenia.}
{118}{}{Beer for $20, shot of whiskey for $30. Nothing special. Why, you want something?}
{119}{}{Szukam Krypty.}
{120}{}{Poproszê piwo.}
{121}{}{Strzelê sobie setê.}
{122}{}{Dzieje siê tutaj coœ ciekawego?}
{123}{}{Nieszczególnie. Ale dziêki.}
{124}{}{"Interesting?" Heh. Friend, Vault City ain't an "interesting" place... unless the guards get bored, then you
 better take cover. Why you asking? You looking for something in this sinkhole?}
{125}{}{Masz coœ do picia?}
{126}{}{W³aœciwie, szukam Krypty.}
{127}{}{Nie mo¿e tu byæ a¿ tak Ÿle.}
{128}{}{Nieszczególnie. Ale dziêki.}
{129}{}{Here you go. Drink up. It might help you forget where you are.}
{130}{}{Nie mo¿e tu byæ a¿ tak Ÿle.}
{131}{}{Dziêki za drinka. Muszê lecieæ.}
{132}{}{Oh, really? Well, hell then, I must be mistaken, considering YOU'RE the authority and all. Guess you must have been napping during the raid last week?}
{133}{}{Nalotu?}
{134}{}{Aw, yeah, a beautiful sight it was. A guard patrol broke in here looking for "illegal substances." They busted down the door, busted up my stock, then busted up a few of my customers, too.}
{135}{}{A co siê sta³o potem?}
{136}{}{Przykro mi to s³yszeæ. Pogadamy póŸniej.}
{137}{}{After they hauled away this one guy, Joshua, for resisting arrest, they fined my ass for finding - get this - REAL whiskey on the premises. Nevermind that I got a permit from Stark three months before. Bastards.}
{138}{}{Rany... Bez jaj...}
{139}{}{Przykro mi to s³yszeæ. Pogadamy póŸniej.}
{140}{}{It gets better. Now I'm in debt to the guards for the fine, an' I had to buy a new case of alcohol from a merchant at triple my standard rate. I'm expecting the guards to come knocking again soon, just to bust my chops. }
{141}{}{Jak tu zwykle jest?}
{142}{}{Mam nadziejê, ¿e sprawy siê wyprostuj¹. Do zobaczenia.}
{143}{}{Even the good days ain't worth a damn. The Citizens don't drink much, so I'm stuck here pouring drinks for merchants. The next cheap sonuvabitch who haggles for a drink is going to be wearing his ass as a hat.}
{144}{}{Dlaczego tu siedzisz, skoro tak nienawidzisz tego miejsca?}
{145}{}{Przykro mi to s³yszeæ. Szukam Krypty. Mo¿esz mi pomóc?}
{146}{}{Przykro mi to s³yszeæ. Mam nadziejê, ¿e sytuacja siê poprawi.}
{147}{}{I have a bad heart. Need cardio booster shots to keep it beating. This city's the only place to get real medical care, so I thought I'd settle here, try and make a living.}
{148}{}{Zdaje siê masz ju¿ ca³kiem doœæ tego miejsca.}
{149}{}{Rozumiem. S³uchaj, szukam Krypty. Mo¿esz mi w tym pomóc?}
{150}{}{Mam nadziejê, ¿e sprawy siê wyprostuj¹. Do zobaczenia.}
{151}{}{Makes me want to close up shop and let this City rot. Screw 'em all.}
{152}{}{Wiêc czemu nie odejdziesz?}
{153}{}{Przykro mi to s³yszeæ. Mam nadziejê, ¿e sprawy jakoœ siê u³o¿¹.}
{154}{}{Go into the wastes by myself? Ha! I'm sick of this place, but I ain't stupid.}
{155}{}{Wybieram siê nied³ugo w podró¿. Chcia³byœ siê przy³¹czyæ?}
{156}{}{Có¿, wobec tego - powodzenia.}
{157}{}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{158}{}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{159}{}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{160}{}{Naw... you look like you got enough of a crowd already.}
{161}{}{W porz¹dku. Trzymaj siê.}
{162}{}{Zapomnij o tym pytaniu, dupku. Wracaj do swojego gównianego baru.}
{163}{}{Wobec tego niewa¿ne. Twoja strata.}
{164}{}{Heh. You serious?}
{165}{}{Pewnie. Czemu nie? Wygl¹dasz na kogoœ, kto umie zadbaæ o siebie w walce.}
{166}{}{Z drugiej strony, jest tam jednak zbyt niebezpiecznie, zw³aszcza dla kogoœ z chorym sercem. Tutaj bêdzie ci lepiej.}
{167}{}{All right, count me in.}
{168}{}{Do dzie³a.}
{169}{}{}
{170}{}{}
{171}{}{What's up? You got that "I need to tell you something you might not like" look again.}
{172}{}{Taak?}
{173}{}{What's up? You got that "I'm pulling rank" look again.}
{174}{}{Mam do ciebie kilka pytañ...}
{175}{}{Wygl¹da na to, ¿e trochê oberwa³eœ. U¿yj stimpaków, by siê podleczyæ.}
{176}{}{Cassidy, zaczekaj tutaj na mój powrót.}
{177}{}{Schowaj broñ.}
{178}{}{B¹dŸ blisko mnie.}
{179}{}{Nie odchodŸ za daleko.}
{180}{}{Musimy siê trochê rozsun¹æ.}
{181}{}{ChodŸ, Cassidy, czas na nas.}
{182}{}{Nic, niewa¿ne.}
{261}{}{You want me to put a bullet in Myron's head, is that it? It'd be no trouble. Just give the word.}
{262}{}{What's on your mind?}
{263}{}{Po co ci ten Myron?}
{264}{}{Na jakiej broni siê znasz?}
{265}{}{W³aœciwie, chcê ¿ebyœ jeszcze coœ zrobi³...}
{266}{}{W³aœciwie, chcê ¿ebyœ coœ zrobi³...}
{267}{}{Niewa¿ne. Ruszajmy.}
{268}{}{Nie, nie rób krzywdy Myronowi. Przynajmniej nie dzisiaj. Dam znaæ, jeœli bêdzie trzeba.}
{269}{}{Well, shotguns and rifles, mostly... just personal preference. I ain't a bad shot with pistols, neither.}
{270}{}{Coœ jeszcze?}
{271}{}{Dobra. Mam inne pytanie...}
{272}{}{W porz¹dku. Tylko sprawdzam.}
{273}{}{If you ever need to learn somebody some manners up close and personal, slip me some brass knuckles, and I can tapdance on their face with my fists.}
{274}{}{Œwietnie. Coœ jeszcze?}
{275}{}{Dobra. Mam inne pytanie...}
{276}{}{W porz¹dku. Tylko sprawdzam.}
{277}{}{Uh, well... just between you and me, I can also use a spear pretty good. Me and my buddies used to hunt radscorpions with spears way back when... fact I'm alive and they ain't might tell you something.}
{278}{}{Nie ma nic z³ego w u¿ywaniu dzidy.}
{279}{}{Dobra. Mam inne pytanie...}
{280}{}{W porz¹dku. Tylko sprawdzam.}
{281}{}{Says you. Just don't be calling me no tribal, and we'll get along just fine.}
{282}{}{Don't want people mistaking me for ol' Bone-nose over there. Heh-heh. I ain't never seen no tribal do something as dumb as jam a bone in his nose.}
{283}{}{Of course there isn't. Spear's a fine weapon. Lots of tribal friends of mine use 'em.}
{284}{}{A wiesz, ¿e ja te¿ jestem "dzikusem"?}
{285}{}{Hmmm. Mam inne pytanie...}
{286}{}{W porz¹dku. Dziêki za raport.}
{287}{}{Aw, don't be playing with ol' Cassidy now. You ain't no tribal.}
{288}{}{Tak, dok³adnie.}
{289}{}{Wszystko jedno. Mam inne pytanie...}
{290}{}{Niewa¿ne. Nie chcê tego teraz roztrz¹saæ.}
{291}{}{Uh, well... damn it all, you can have my apology right here and now. I didn't mean any offense.}
{292}{}{Jasne, ¿e nie. Mam inne pytanie...}
{293}{}{Zapomnij o tym. ChodŸmy.}
{294}{}{Well, now, before you go, I got a question for you. What are we doing out here? We seem to be running all over the place looking for something. Have we got some sort of plan?}
{295}{}{Szukamy GECKa - Generatora Ekosystemu Cudownej Krainy. Jest potrzebny mojej wiosce, by mog³a siê wy¿ywiæ.}
{296}{}{Pójdziemy do Krypty, a potem zaniesiemy GECK do wioski.}
{297}{}{Mieszkañców mojej wioski porwano. Próbujê ustaliæ, co siê z nimi sta³o.}
{298}{}{Them things come in kits now, huh? Man, the good book don't mention that, does it? Well, all right then. Let's get hunting.}
{299}{}{Huh. All right then, just checking.}
{300}{}{I wouldn't mind plugging a few holes in some kidnappers. A little frontier justice never hurt anyone... well, at least not me.}
{301}{}{W porz¹dku. ChodŸmy.}
{302}{}{The things that little cuss says ain't fit for decent ears.}
{303}{}{Especially a woman's.}
{304}{}{Rany, Cassidy, nie wiedzia³am, ¿e zwracasz na to uwagê. A¿ mi cieplej na sercu.}
{305}{}{No i? Co masz na myœli?}
{306}{}{Wiesz, sam te¿ sporo przeklinasz, Cassidy.}
{307}{}{A pewnie. Ruszajmy.}
{308}{}{Yeah, but when I do it, it's got style. He's just a little trash mouth.}
{309}{}{And I don't like the way he looks at you, neither.}
{310}{}{Rany, Cassidy, nie wiedzia³am, ¿e zwracasz na to uwagê. A¿ mi cieplej na sercu.}
{311}{}{No i? Co masz na myœli?}
{312}{}{A pewnie. Ruszajmy.}
{313}{}{Now hold on, I didn't mean it like that.}
{314}{}{All I'm saying is that bona fide little asshole's gonna get his number clocked one day when it's just me and him and a hole in the desert.}
{315}{}{Có¿ ¿ycie potrafi byæ surowym nauczycielem. Mam inne pytanie...}
{316}{}{Có¿, i tak ugryzie. Nie przejmuj siê.}
{317}{}{Spokojnie, Cassidy. Zostaw Myrona w spokoju.}
{318}{}{Nie cierpiê tego miejsca.}
{319}{}{Mia³em nadziejê, ¿e na zawsze opuœci³em to miejsce.}
{320}{}{Miasto dupków...}
{321}{}{Tu jest gorzej ni¿ w Kryptopolis.}
{322}{}{Dobrze, ¿e nabi³em broñ zanim tu przyszliœmy.}
{323}{}{Jeœli kopne w kalendarz, nie chowajcie mnie tutaj.}
{324}{}{Uwa¿ajmy na siebie. Tubylcy nie s¹ zbyt mili.}
{325}{}{Ha! Nie s¹dzi³em, ¿e zobaczê San Francisco.}
{326}{}{Nie s¹dzi³em, ¿e tak d³ugo zechcesz trzymaæ przy sobie kogoœ w moim wieku. Za³atwmy to, co planujemy i wracajmy do domu.}
{327}{}{Redding to miasto górnicze. Wydobywaj¹ g³ównie z³oto. Do Kryptopolis przybywa st¹d spora liczba karawan.}
{328}{}{Broken Hills to miasto górnicze... Wydobywaj¹ g³ównie rudê uranu. To mo¿e byæ nieprzyjemna okolica, wiêc uwa¿ajmy na siebie.}
{329}{}{Jestem nieco przytruty. Mamy jakieœ antidotum?}
{330}{}{Œwiecê niczym neon. Mamy jakieœ proszki antyradiacyjne?}
{331}{}{Mocno oberwa³em. Mamy stimpaki?}
{332}{}{¯adnych prochów, Myron. Mam ciê na oku.}
{333}{}{Podskocz tylko, Myron, a spadniesz w kawa³kach.}
{334}{}{Cholera, Lenny, potrzebna ci k¹piel. Albo dezynfekcja.}
{335}{}{Lepiej trzymaj siê z daleka, ghulu. Rany, ale œmierdzisz.}
{336}{}{Bardziej wrednego psa w ¿yciu nie widzia³em.}
{337}{}{Dobra psina. Cassidy jest twoim przyjacielem, prawda?}
{338}{}{Ciekawe, co ten cyberpies je. Pewnie ludzi.}
{339}{}{Jeœli ten cyberpies skoczy mi na nogê, rozwalê go.}
{340}{}{Aaaach. Rany... Dobrze, ¿e zrobili tego miliony, nim spad³y bomby.}
{341}{}{Stokrotne dziêki.}
{342}{}{Mam nadziejê, ¿e te stimpaki nie zaszkodz¹ mi na serce...}
{343}{}{Co do...?! Nie! Moje serce! Ja...*hrrrkkk*}
{344}{}{Przepraszam, podziwia³em widoki.}
{345}{}{Niech to... Wobec tego, stanê gdzieœ tam.}
{346}{}{Przepraszam, przyjacielu. Nie chcia³em stan¹æ na twojej drodze.}
{347}{}{Aaaach. To jest to. Uprzejmie dziêkujê.}
{348}{}{*Hik* He he. Na ciœnienie nie ma to jak stara, dobra woda ognista.}
{349}{}{Dziêki. Do diab³a! Ty te¿ sobie ³yknij.}
{350}{}{Oto Krypta. Wielgachna, nie?}
{351}{}{Chcesz, bym znów siê przy³¹czy³?}
{352}{}{Pójdê tam, gdzie ty.}
{353}{}{Na pewno nie potrzebujesz mojej pomocy?}
{354}{}{Œwierzbi mnie, ¿eby ju¿ iœæ.}
{355}{}{Chêtnie poci¹gnê dymka.}
{356}{}{Tata da³ mi imiê po jakiejœ postaci z przedwojennego komiksu. Ponoæ to te¿ by³ kawa³ sukinsyna.}
{357}{}{Mi³o jest byæ znowu w drodze. Od mieszkania w Kryptopolis dostawa³em odcisków.}
{358}{}{Mam nadziejê, ¿e moje serce nie bêdzie siê wyg³upiaæ podczas podró¿y...}
{359}{}{Chêtnie bym siê napi³.}
{360}{}{Lepiej sprawdzê swój sprzêt.}
{361}{}{Cholerny artretyzm...}
{362}{}{Gdybym mia³ dwadzieœcia lat mniej, ruszy³bym na wschód, by zwiedziæ Œrodkowy Zachód. Teraz ju¿ chyba na to za póŸno.}
{363}{}{Na Œrodkowym Zachodzie ponoæ by³y tornada szerokie na mile. Teraz to wielka, radioaktywna pustynia.}
{364}{}{Ciekawe, czy Teksas przetrwa³ wojnê...}
{365}{}{Dziêki. Ja... Hej... Wzrok mam zamglony!}
{366}{}{Ponoæ od tego mo¿na dostaæ halucyn... Hej! Sk¹d, u licha, wziê³y siê tutaj te wê¿e?!}
{367}{}{Zawsze kiedy to biorê, mam napady wspomnieñ.}
{368}{}{Nie ma to jak plemienne leczenie...}
{369}{}{Bêdê potrzebowa³ kul i wózka inwalidzkiego.}
{370}{}{Cassidy umiera na atak serca.}
{371}{}{Uda³o ci siê przekonaæ Cassidy'ego ¿eby przy³¹czy³ siê do twojej dru¿yny.}
{372}{}{Pozwól mi najpierw po³kn¹æ tabletkê na serce...}
{1000}{}{Well... all right, then. I'll wait here 'til you get back. }
{1100}{}{Sure. Can't promise I won't pull it out again if there's trouble, though.}
{1200}{}{All right, I'll stick close to you then. You must be expecting trouble.}
{1300}{}{All right, I'll keep some distance. Get a better vantage point that way.}
{1400}{}{All right, I'll be watching your back. You need me, holler, and I'll come running.}
{2000}{}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{2100}{}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{2200}{}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{2300}{}{Naw... you look like you got enough of a crowd already.}
{2400}{}{W takim razie w porz¹dku.}
{2999}{}{W porz¹dku. Uwa¿aj na siebie.}
{3000}{}{Idziemy.}
{3100}{}{Wiêc zapomnij o tym, dupku.}
{3200}{}{No to niewa¿ne. Twoja strata.}
{4100}{}{Okay, everything's stitched up. I'm good to go.}
{4200}{}{Okay, pretty much everything is patched up.}
{4300}{}{To mi ca³kiem dobrze zrobi³o, ale przyda³oby siê jeszcze parê stimów.}
{4400}{}{I used what I could, but I'm still pretty messed up. If you got any more stims to spare, I could sure use 'em. I can still walk, though.}
{9999}{}{Mam do ciebie kilka pytañ...}
{10001}{}{WeŸ trochê stymulantów i podlecz siê.}
{10002}{}{Cassidy, zaczekaj tutaj na mój powrót.}
{10003}{}{Schowaj broñ.}
{10004}{}{B¹dŸ blisko mnie.}
{10005}{}{Nie odchodŸ za daleko.}
{10006}{}{Musimy siê trochê rozsun¹æ.}
{10007}{}{No to idziemy.}
{10100}{}{ChodŸ, Cassidy, czas na nas.}
{20000}{}{All right, I'm listening.}
{20001}{}{My gear? What about it?}
{20002}{}{No problem. Too hot for that kinda gear, anyway. Makes me sweat like a New Reno whore.}
{20003}{}{Zmieñmy szyk.}
{20004}{}{Muszê z tob¹ porozmawiaæ o walce.}
{20005}{}{Niewa¿ne. Zostañmy przy tym szyku.}
{20006}{}{Niewa¿ne. Niczego nie potrzebujê wiedzieæ o twoim sprzêcie.}
{20007}{}{Zdejmij swój pancerz.}
