{100}{}{Widzisz brudnego ale wygl¹daj¹cego na silnego mê¿czyznê.}
{101}{}{Widzisz Connara.}
{102}{}{Hey you! What are you doing!}
{103}{}{Ani kroku dalej, przybyszu. Co tu robisz?}
{104}{}{I'm killing off the monsters here.}
{105}{}{A co ciê to obchodzi?}
{106}{}{Czemu ty krzyczy!}
{107}{}{I bet those bastards at Vault City sent you. Well you best be off, and leave everything else
 alive.}
{108}{}{Có¿, na to ju¿ chyba trochê za póŸno.}
{109}{}{Czemu?}
{110}{}{Przykro mi, mam robotê do wykonania.}
{111}{}{Those creatures are the only thing that are stopping Vault City from making us their so-called
 servants.}
{112}{}{Well they're paying me to get rid of the monsters, and that's what I'm going to do.}
{113}{}{Tego mi nie powiedzieli.}
{114}{}{Zap³acili mi za wytêpienie potworów, wiêc zosta³y wytêpione.}
{115}{}{Odbi³o ci?! Dlaczego to robisz!}
{116}{}{Potrzebujê pieniêdzy.}
{117}{}{Wiedz, ¿e jeœli to zrobisz, przyjd¹ po nas i bêdziemy zgubieni.}
{118}{}{To nie moja sprawa.}
{119}{}{Wiêc ud³aw siê nimi! Wkrótce po nas przyjd¹, jesteœmy zgubieni.}
{120}{}{Nie powiedzieli mi, ¿e o to im chodzi.}
{121}{}{Ta. Có¿, i tak nie robiê interesów z takimi œmieciami jak wy.}
{122}{}{Nie mo¿emy ci na to pozwoliæ.}
{123}{}{Rób co uwa¿asz za konieczne.}
{124}{}{I wierzysz im tak na s³owo? Musisz siê jeszcze du¿o nauczyæ o tym œwiecie.}
{125}{}{Mogê wam w jakiœ sposób pomóc?}
{126}{}{Ch³opcy z Kryptopolis nie nale¿¹ do najodwa¿niejszych. Jak tylko zwêsz¹ jak¹œ rozróbê podkulaj¹ ogon i wiej¹ do domu. Gdybyœmy mieli jak¹œ broñ, moglibyœmy trzymaæ ich na dystans.}
{127}{}{What sort of guns?}
{128}{}{Well, I'm good with a shotgun, and we have some people in here that can handle a rifle. I think
 three of those would do.}
{129}{}{Zobaczê, co siê da zrobiæ.}
{130}{}{Nie chcemy ciê tutaj. OdejdŸ.}
{131}{}{Mo¿e jednak zmieniê zdanie. Jak mogê wam pomóc?}
{132}{}{Ta. Có¿, i tak wkrótce was tu nie bêdzie.}
{133}{}{Jakby mnie to obchodzi³o.}
{134}{}{Ju¿ jesteœ! Masz dla nas broñ?}
{135}{}{Mo¿esz mi jeszcze raz powiedzieæ czego potrzebujecie?}
{136}{}{Tak, proszê bardzo.}
{137}{}{We need three rifles and a shotgun. The sooner you can get them to us, the better.}
{138}{}{Dobra.}
{139}{}{With these, we'll be able to make something of this place over the next months. If you ever need
 a place to rest, you will always be welcome here.}
{140}{}{Nie ma za co.}
{141}{}{Welcome back. Things are going well. We're going to work on expanding the Village.}
{142}{}{Witaj ponownie! Jak widzisz u nas wszystko w najlepszym porz¹dku. Rozejrzyj siê trochê jeœli masz czas.}
{143}{}{Wci¹¿ budujemy. W przysz³ym miesi¹cu powinniœmy powiêkszyæ mury.}
{144}{}{Greetings! The village has expanded again as we have hoped. You are welcome as always.}
{145}{}{We have nothing to fear from Vault City any longer, and will be able to live here in peace.
 Thank you again, wanderer.}
{146}{}{Tylko nie zabijaj tu niczego, prostaku.}
