{100}{}{Widzisz umorusanego osi³ka.}
{101}{}{Widzisz Connara.}
{102}{}{Hej ty! Co ty wyprawiasz!}
{103}{}{Ani kroku dalej, przybyszu. Czego tu szukasz?}
{104}{}{Zabijam potwory.}
{105}{}{A co ciê to obchodzi?}
{106}{}{Czemu ty krzyczy!}
{107}{}{Za³o¿ê siê, ¿e przys³a³y ciê te pajace z Kryptopolis. Lepiej bêdzie jeœli od razu sobie st¹d pójdziesz. I nie wa¿ siê nikogo skrzywdziæ.}
{108}{}{Có¿, na to ju¿ chyba trochê za póŸno.}
{109}{}{Dlaczego?}
{110}{}{Przykro mi, mam robotê do wykonania.}
{111}{}{Te stworzenia to jedyna rzecz powstrzymuj¹ca Kryptopolis przed uczynieniem z nas s³u¿¹cych.}
{112}{}{Có¿, miasto zap³aci³o mi za wytêpienie potworów i to w³aœnie zamierzam zrobiæ.}
{113}{}{Tego mi nie powiedzieli.}
{114}{}{Zap³acili mi za wytêpienie potworów, wiêc zosta³y wytêpione.}
{115}{}{Dlaczego?! Czy ty wiesz co siê z nami teraz stanie?!}
{116}{}{Potrzebujê pieniêdzy.}
{117}{}{Jeœli to zrobisz, bêdziemy zgubieni.}
{118}{}{To nie moja sprawa.}
{119}{}{Wiêc ud³aw siê nimi! Jesteœmy zgubieni.}
{120}{}{Nie powiedzieli mi, ¿e o to im chodzi.}
{121}{}{Có¿, i tak nie pertraktujê z takimi œmieciami jak ty.}
{122}{}{Nie mo¿emy ci na to pozwoliæ.}
{123}{}{Rób co uwa¿asz za konieczne.}
{124}{}{I wierzysz im tak na s³owo? Musisz siê jeszcze du¿o nauczyæ o tym œwiecie.}
{125}{}{Mogê wam w jakiœ sposób pomóc?}
{126}{}{Ch³opcy z Kryptopolis nie nale¿¹ do najodwa¿niejszych. Jak tylko zwêsz¹ jak¹œ rozróbê podkulaj¹ ogon i wiej¹ do domu. Gdybyœmy mieli jak¹œ broñ, moglibyœmy trzymaæ ich na dystans.}
{127}{}{Jak¹ broñ masz na myœli?}
{128}{}{Có¿, umiem strzelaæ ze strzelby, a paru moich ludzi poradzi sobie z karabinem. Wystarcza trzy sztuki.}
{129}{}{Zobaczê co siê da zrobiæ.}
{130}{}{Nie chcemy ciê tutaj. Wynoœ siê.}
{131}{}{Mo¿e jednak zmieniê zdanie. Jak mogê wam pomóc?}
{132}{}{Có¿, i tak nied³ugo was tu nie bêdzie.}
{133}{}{Mam to w nosie.}
{134}{}{Ju¿ jesteœ! Masz dla nas broñ?}
{135}{}{Mo¿esz mi jeszcze raz wyjaœniæ czego potrzebujecie?}
{136}{}{Tak, proszê bardzo.}
{137}{}{Potrzebujemy trzech karabinów i strzelby. Im szybciej je tutaj dostarczysz, tym lepiej.}
{138}{}{Rozumiem.}
{139}{}{Dziêki nim jakoœ utrzymamy to miejsce przez kilka najbli¿szych miesiêcy. Jeœli bêdziesz kiedyœ potrzebowaæ bezpiecznego schronienia, zajrzyj do nas.}
{140}{}{Ca³a przyjemnoœæ po mojej stronie.}
{141}{}{Witaj znowu. U nas wszystko w porz¹dku. Planujemy w³aœnie powiêkszyæ nasz¹ wioskê.}
{142}{}{Witaj ponownie! Jak widzisz u nas wszystko w najlepszym porz¹dku. Rozejrzyj siê trochê w wolnej chwili.}
{143}{}{Wci¹¿ budujemy. W przysz³ym miesi¹cu powinniœmy powiêkszyæ ogrodzenie.}
{144}{}{Witaj! Mi³o ciê znów widzieæ. Nasza wioska dalej siê rozrasta.}
{145}{}{Nie musimy siê ju¿ obawiaæ niebezpieczeñstwa ze strony Kryptopolis. Od tej pory mo¿emy ¿yæ w spokoju. W imieniu nas wszystkich dziêkujê ci.}
{146}{}{Tylko nie zabijaj tu niczego, prostaku.}
