{100}{}{Widzisz brudnego ale wyglądającego na silnego mężczyznę.}
{101}{}{Widzisz Connara.}
{102}{}{Hey you! What are you doing!}
{103}{}{Ani kroku dalej, przybyszu. Co tu robisz?}
{104}{}{I'm killing off the monsters here.}
{105}{}{A co cię to obchodzi?}
{106}{}{Czemu ty krzyczy!}
{107}{}{I bet those bastards at Vault City sent you. Well you best be off, and leave everything else
 alive.}
{108}{}{Cóż, na to już chyba trochę za późno.}
{109}{}{Dlaczego?}
{110}{}{Przykro mi, mam robotę do wykonania.}
{111}{}{Those creatures are the only thing that are stopping Vault City from making us their so-called
 servants.}
{112}{}{Well they're paying me to get rid of the monsters, and that's what I'm going to do.}
{113}{}{Tego mi nie powiedzieli.}
{114}{}{Zapłacili mi za wytępienie potworów, więc zostały wytępione.}
{115}{}{Odbiło ci?! Dlaczego to robisz!}
{116}{}{Potrzebuję pieniędzy.}
{117}{}{Wiedz, że jeśli to zrobisz, przyjdą po nas i będziemy zgubieni.}
{118}{}{To nie moja sprawa.}
{119}{}{Więc udław się nimi! Wkrótce po nas przyjdą, jesteśmy zgubieni.}
{120}{}{Nie powiedzieli mi, że o to im chodzi.}
{121}{}{Ta. Cóż, i tak nie robię interesów z takimi śmieciami jak wy.}
{122}{}{Nie możemy ci na to pozwolić.}
{123}{}{Rób co uważasz za konieczne.}
{124}{}{You believed them at face value?  You've a lot to learn about the world, friend.}
{125}{}{Mogę wam w jakiś sposób pomóc?}
{126}{}{Chłopcy z Kryptopolis nie należą do najodważniejszych. Jak tylko zwęszą jakąś rozróbę podkulają ogon i wieją do domu. Gdybyśmy mieli jakąś broń, moglibyśmy trzymać ich na dystans.}
{127}{}{What sort of guns?}
{128}{}{Well, I'm good with a shotgun, and we have some people in here that can handle a rifle. I think
 three of those would do.}
{129}{}{Zobaczę, co da się zrobić.}
{130}{}{Nie chcemy cię tutaj. Odejdź.}
{131}{}{Może jednak zmienię zdanie. Jak mogę wam pomóc?}
{132}{}{Ta. Cóż, i tak wkrótce was tu nie będzie.}
{133}{}{Jakby mnie to obchodziło.}
{134}{}{Już jesteś! Masz dla nas broń?}
{135}{}{Możesz mi jeszcze raz powiedzieć czego potrzebujecie?}
{136}{}{Tak, proszę bardzo.}
{137}{}{We need three rifles and a shotgun. The sooner you can get them to us, the better.}
{138}{}{W porządku.}
{139}{}{With these, we'll be able to make something of this place over the next months. If you ever need
 a place to rest, you will always be welcome here.}
{140}{}{Cała przyjemność po mojej stronie.}
{141}{}{Welcome back. Things are going well. We're going to work on expanding the Village.}
{142}{}{Witaj ponownie! Jak widzisz u nas wszystko w najlepszym porządku. Rozejrzyj się trochę jeśli masz czas.}
{143}{}{Wciąż budujemy. W przyszłym miesiącu powinniśmy powiększyć mury.}
{144}{}{Greetings! The village has expanded again as we have hoped. You are welcome as always.}
{145}{}{We have nothing to fear from Vault City any longer, and will be able to live here in peace.
 Thank you again, wanderer.}
{146}{}{Tylko nie zabijaj tu niczego, prostaku.}
