{100}{}{Widzisz obywatela w jasnoniebieskim kombinezonie. Wygl¹da jak zwyk³y ubiór mieszkañca Krypty, ale na plecach brakuje numeru.}
{101}{}{Widzisz oficera Darrowa z Sekcji Udogodnieñ}
{102}{}{Widzisz obywatela w jasnoniebieskim kombinezonie. Wygl¹da jak zwyk³y ubiór mieszkañca Krypty, ale na plecach brakuje numeru.}
{103}{}{::klaszcze::}
{104}{}{Oto bohater! Patrzcie!}
{105}{}{Mój bo¿e! To Bohater, tutaj, w Kryptopolis!}
{106}{}{Dobrego dnia, Kapitanie.}
{107}{}{Kryptopolis ponad wszystkim, Kapitanie.}
{108}{}{Dobrego dnia, obywatelu.}
{109}{}{Kryptopolis ponad wszystkim, obywatelu.}
{110}{}{Mutant! Stra¿e! Stra¿e!}
{111}{}{Ghul! Stra¿e! Stra¿e!}
{112}{}{Muszê siê zaj¹æ zamówieniem wiêkszej liczby narzêdzi z Redding.}
{113}{}{Ma³y dzisiaj ruch.}
{114}{}{Ciekawe, czy Randal skoñczy³ ju¿ tê listê zakupów.}
{115}{}{Wydaje siê, ¿e dopiero co da³em Randalowi tê listê towarów.}
{116}{}{Przynajmniej ta robota przebija pracê w Biurze List.}
{117}{}{S³u¿¹cy wci¹¿ zu¿ywaj¹ wiêkszoœæ narzêdzi. Jak bym chcia³, ¿eby bardziej o nie dbali...}
{118}{}{Przyda³yby mi siê wakacje.}
{119}{}{Biuro Sekcji Udogodnieñ jest w nocy zamkniête... wróæ tu rano. }
{120}{}{W tej chwili przyjmuje towar. Wróæ, gdy otworzymy nad rankiem.}
{121}{}{Zamkniête. Mo¿esz spróbowaæ w sklepie wielobran¿owym na zewn¹trz, je¿eli ju¿ czegoœ naprawdê potrzebujesz.}
{122}{}{Mogê ci w czymœ pomóc, Kapitanie?}
{123}{}{Mogê ci w czymœ pomóc, obywatelu?}
{124}{}{Przepraszam, mogê w czymœ pomóc?}
{125}{}{Czym? Dudle-dudle duuuuuuuu}
{126}{}{Wytocz siê na zewn¹trz}
{127}{}{Co to za miejsce?}
{128}{}{Czy mogê zobaczyæ, co masz na stanie?}
{129}{}{Nie dzisiaj, dziêki.}
{130}{}{Poczekaj tu chwilê, dobra? Przyprowadzê tu kogoœ, ¿eby ci pokazaæ.}
{131}{}{NIE JA NIE ISC}
{132}{}{Okiiii-dokiiii }
{133}{}{S³uchaj, mo¿e ci siê to przydaæ, na Podmurzu jest taki sklep wielobran¿owy, mo¿esz tam spróbowaæ coœ kupiæ... s³ysza³em, ¿e facet ma wybór prawie tak dobry, jak nasz.}
{134}{}{Ee, dziêki.}
{135}{}{Bêdê kupowaæ, gdzie mi siê bêdzie chcia³o, kapujesz?}
{136}{}{Dziêki za odwiedziny. Kryptopolis ponad wszystkim, obywatelu.}
{137}{}{Dziêki za odwiedziny. Kryptopolis ponad wszystkim, Kapitanie}
{138}{}{Kryptopolis ponad wszystkim, obywatelu.}
{139}{}{Dzieñ dobry, obywatelu.}
{140}{}{Biuro A Sekcji Udogodnieñ. Jestem odpowiedzialny za zapotrzebowania na sprzêt ogólny, jak narzêdzia i sprzêt do napraw. Nazywam siê Darrow... Oficer Sekcji Udogodnieñ Darrow. Widzisz coœ, co by ci by³o potrzebne?}
{141}{}{To Biuro A Sekcji Udogodnieñ... Zajmujemy siê dostarczaniem narzêdzi i sprzêtu naprawczego dla miasta. Na pewno to jest miejsce, którego szukasz?}
{142}{}{Czy mogê zobaczyæ, co masz na stanie?}
{143}{}{Tak, to to miejsce. Czy mogê zobaczyæ, co masz na stanie?}
{144}{}{Nie dzisiaj, dziêki.}
{145}{}{Nie s¹dzê. Do widzenia.}
{146}{}{Ej! OdejdŸ stamt¹d!}
{147}{}{Doœæ tego! Wynocha st¹d!}

{148}{}{Dziêki.}
{149}{}{[dalej]}
