{100}{}{Widzisz mieszkañca wioski.}
{101}{}{Widzisz mieszkañca wioski.}
{102}{}{Witaj.}
{103}{}{Dzieñ dobry.}
{104}{}{Witaj w naszej wiosce.}
{105}{}{Potwory nas broni¹.}
{106}{}{Wracaj szybko.}
{107}{}{Bez broni ani rusz.}
{108}{}{Witaj.}
{109}{}{IdŸ sobie!}
{110}{}{Wracaj sk¹d przybywasz!}
{111}{}{IdŸ do diab³a!}
{112}{}{Jesteœmy ju¿ bezpieczni.}
{113}{}{Dziêkujemy.}
{114}{}{Zawsze bêdziemy ciê pamiêtaæ.}
