{100}{}{Widzisz mieszkańca wioski.}
{101}{}{Widzisz mieszkańca wioski.}
{102}{}{Cześć.}
{103}{}{Do widzenia.}
{104}{}{Witaj w naszej wiosce.}
{105}{}{Potwory nas bronią.}
{106}{}{Wróć szybko.}
{107}{}{Wkrótce będziemy potrzebować tej broni.}
{108}{}{Cześć.}
{109}{}{Odejdź, teraz!}
{110}{}{Wracaj, skąd przychodzisz!}
{111}{}{Idź do diabła!}
{112}{}{Teraz jesteśmy bezpieczni.}
{113}{}{Dziękuję.}
{114}{}{Niech Cię Bóg błogosławi, wędrowcze.}
