{100}{}{Widzisz małego, jowialnego mężczyznę.}
{101}{}{Widzisz Szczęśliwego Harry'ego, właściciela sklepu.}
{102}{}{O, witaj! Cóż mogę dla ciebie zrobić?}
{103}{}{Chcę pohandlować! Mogę zobaczyć, co masz do zaoferowania?}
{104}{}{Nadal chcesz sprzedać ten pług leżący przed wejściem?}
{105}{}{Ja kupić.}
{106}{}{Dzięki, ale dziś nie skorzystam.}
{107}{}{Przepraszam, nie mogę ci pomóc, koleżko.}
{108}{}{Ależ tak. Jeśli cię interesuje, mogę ci go pchnąć za osiem stówek.}
{109}{}{Dam ci sześćset!}
{110}{}{Umowa stoi. Biorę.}
{111}{}{Co? Osiemset? Eee... to część, wrócę z kasą.}
{112}{}{Zapomnij! Za taką cenę Smithowie mogą trochę pocierpieć.}
{113}{}{Jest twój. [Płacisz.] Zapakować i dostarczyć w jakieś konkretne miejsce, czy sam go weźmiesz?}
{114}{}{Dostarcz to Smithowi.}
{115}{}{Wybacz, ale będzie cię to kosztować osiem stów!}
{119}{}{Słuchaj, potrzebujesz pieniędzy, aby mi zapłacić!}
{120}{}{Jeszcze tu wrócę... z pieniędzmi.}
{121}{}{Żaden problem, sam się tym zajmę.}
{122}{}{Pewnie chciałeś tylko pooglądać, co? Nędzny złodziej! Straż! Straż!}
