{100}{}{Widzisz ma³ego, jowialnego mê¿czyznê.}
{101}{}{Widzisz Szczêœliwego Harry'ego, w³aœciciela sklepu.}
{102}{}{O, witaj! Có¿ mogê dla ciebie zrobiæ?}
{103}{}{Chcê pohandlowaæ! Mogê zobaczyæ, co masz do zaoferowania?}
{104}{}{Nadal chcesz sprzedaæ ten p³ug le¿¹cy przed wejœciem?}
{105}{}{Ja kupiæ.}
{106}{}{Niczego dziœ nie potrzebujê, dziêki.}
{107}{}{Przepraszam, nie mogê ci pomóc, kole¿ko.}
{108}{}{Ale¿ tak. Jeœli ciê interesuje, mogê ci go pchn¹æ za osiem stówek.}
{109}{}{Dam ci szeœæset!}
{110}{}{Umowa stoi. Biorê.}
{111}{}{Co? Osiemset? Eee... to czêœæ, wrócê z kas¹.}
{112}{}{Zapomnij! Za tak¹ cenê Smithowie mog¹ trochê pocierpieæ.}
{113}{}{Jest twój. [P³acisz.] Zapakowaæ i dostarczyæ w jakieœ konkretne miejsce, czy sam go weŸmiesz?}
{114}{}{Dostarcz to Smithowi.}
{115}{}{Wybacz, ale bêdzie ciê to kosztowaæ osiem stów!}
{119}{}{S³uchaj, potrzebujesz pieniêdzy, aby mi zap³aciæ!}
{120}{}{Jeszcze tu wrócê... z pieniêdzmi.}
{121}{}{¯aden problem, sam siê tym zajmê.}
{122}{}{Pewnie chcia³eœ tylko poogl¹daæ, co? Nêdzny z³odziej! Stra¿! Stra¿!}
