{100}{}{Widzisz starego mê¿czyznê z dzikim b³yskiem w oku.}
{101}{}{Widzisz Starego Joe, miejsczowego uczonego idiotê.}
{102}{}{Hej. Dawno ciê nie widzia³em.}
{103}{}{Czy my siê znamy?}
{104}{}{O tak. Kope lat. Co przez ten czas robi³eœ?}
{105}{}{Racja, tyle lat minê³o. Czym siê teraz zajmujesz?}
{106}{}{Bywa³o siê tu i tam. Sk¹d mnie znasz?}
{107}{}{S³uchaj staruchu, nie mam pojêcia kim jesteœ.}
{108}{}{O tak. Wiesz, krêci³em siê po okolicy, a¿ w koñcu znalaz³em siê w tym przeklêtym miejscu. Nie jak za dawnych czasów, o nie.}
{109}{}{Ech, stared dobre czasy. Pamiêtasz jak kiedyœ...}
{110}{}{Nic teraz nie jest takie jak dawniej, o nie. A teraz powiedz mi... co takiego razem zrobiliœmy?}
{111}{}{Nie pamiêtasz mnie, prawda? Rzeczywiœcie, wygl¹dasz doœæ m³odo.}
{112}{}{Co chcesz przez to powiedzieæ?}
{113}{}{A jednak wygl¹dasz znajomo. Ach, to pewnie przez ten mój wzrok. Dobrego dnia ¿yczê.}
{114}{}{Uch, pewnie... mi³ego dnia.}
{115}{}{Pewnie, nieŸle dokopaliœmy Mistrzowi, prawda? Ale kiedy ciebie zabrak³o, wszystko siê posypa³o. Musia³em siê przeprowadziæ i zmieniæ imiê. A gdzie ciebie ponios³o?}
{116}{}{Opiekowano siê mn¹ w ma³ej wiosce.}
{117}{}{Wiesz, lepiej uwa¿aj na siebie. Nic nie jest takie ³atwe jak kiedyœ. Lepiej dobrze siê pilnuj.}
{118}{}{Dobrze, dziêki.}
{119}{}{Szuka³em przez jakiœ czas twojej Krypty, ale nigdy jej nie znalaz³em. Masz mo¿e jakieœ ciekawe historie dla swojego starego przyjaciela Iana?}
{120}{}{Ian?}
{121}{}{No pewnie, Ian. Nie pamiêtasz mnie? To ju¿ tyle lat. Myœla³by kto, ¿e nie zapomnisz swego najlepszego kumpla. No... mo¿e oprócz tego ca³ego strzelania w plecy. Jeszcze raz przepraszam.}
{122}{}{Przykro mi, ale chyba wzi¹³eœ mnie za Przybysza z Krypty. Moja wioska zosta³a za³o¿ona przez osobê, która pochodzi³a z Krypty.}
{123}{}{No, teraz to siê trochê lepiej trzyma kupy. Dobrze wiedzieæ, ¿e mój przyjaciel sobie poradzi³. Stary Ian ma dla ciebie radê. Uwa¿aj tu na siebie. To miejsce nie jest takie s³odkie, na jakie wygl¹da. }
{124}{}{Co tu siê dzieje?}
{125}{}{Widzisz, obywatele Kryptopolis bardzo sobie ceni¹ swój rodowód i nie interesuj¹ siê zbytnio takimi jak ja czy ty. WeŸ tê broñ. Pomo¿e ci jeœli sprawy wymkn¹ siê spod kontroli. Lepiej chyba, ¿eby nikt nie widzia³ jak rozmawiasz ze starym wariatem. Lepiej ju¿ ruszaj.}
{126}{}{Dziêki za pomoc.}
{127}{}{Pozwól staruszkowi odpocz¹æ.}
{128}{}{Takie podobieñstwo...}
{129}{}{Zostaw mnie teraz samego.}
{130}{}{Lepiej ju¿ idŸ.}
{131}{}{Jeœli bêdziemy d³u¿ej rozmawiaæ, ktoœ mo¿e nabraæ podejrzeñ.}
{132}{}{No ju¿, idŸ. Uczyñ mojego przyjaciela dumnym.}
