{100}{}{Widzisz starego mężczyznę z dzikim błyskiem w oku.}
{101}{}{Widzisz Starego Joe, miejscowego uczonego idiotę.}
{102}{}{Hej. Dawno cię nie widziałem.}
{103}{}{Czy my się znamy?}
{104}{}{O tak. Kopę lat. Co przez ten czas robiłeś?}
{105}{}{Racja, tyle lat minęło. Czym się teraz zajmujesz?}
{106}{}{Bywało się tu i tam. Skąd mnie znasz?}
{107}{}{Słuchaj staruchu, nie mam pojęcia kim jesteś.}
{108}{}{O tak. Wiesz, kręciłem się po okolicy, aż w końcu znalazłem się w tym przeklętym miejscu. Nie jak za dawnych czasów, o nie.}
{109}{}{Ech, stare dobre czasy. Pamiętasz jak kiedyś...}
{110}{}{Nic teraz nie jest takie jak dawniej, o nie. A teraz powiedz mi... co takiego razem zrobiliśmy?}
{111}{}{Nie pamiętasz mnie, prawda? Rzeczywiście, wyglądasz za młodo.}
{112}{}{Co chcesz przez to powiedzieć?}
{113}{}{A jednak wyglądasz tak znajomo. Ach, to pewnie przez ten mój wzrok. Dobrego dnia życzę.}
{114}{}{Uch, pewnie... miłego dnia.}
{115}{}{Pewnie, nieźle dokopaliśmy Mistrzowi, prawda? Ale kiedy ciebie zabrakło, wszystko się posypało. Musiałem się przeprowadzić i zmienić imię. A gdzie ciebie poniosło?}
{116}{}{Opiekowano się mną w małej wiosce.}
{117}{}{Wiesz, lepiej uważaj tutaj na siebie. Nic nie jest takie łatwe jak kiedyś. Lepiej dobrze się pilnuj.}
{118}{}{Dobra, dzięki.}
{119}{}{Szukałem przez jakiś czas twojej Krypty, ale nigdy jej nie znalazłem. Masz może jakieś ciekawe historie dla swojego starego przyjaciela Iana?}
{120}{}{Ian?}
{121}{}{Ta, Ian. Nie pamiętasz mnie? To już tyle lat. Myślałby kto, że nie zapomnisz swego najlepszego kumpla. No... może oprócz tego całego strzelania w plecy. Jeszcze raz przepraszam.}
{122}{}{Przykro mi, ale chyba wziąłeś mnie za Przybysza z Krypty. Moja wioska została założona przez osobę, która pochodziła z Krypty.}
{123}{}{No, teraz to się trochę lepiej trzyma kupy. Dobrze wiedzieć, że mój przyjaciel sobie poradził. Stary Ian ma dla ciebie radę. Uważaj tu na siebie. To miejsce nie jest takie słodkie, na jakie wygląda. }
{124}{}{Co tu się dzieje?}
{125}{}{Widzisz, Obywatele Kryptopolis bardzo sobie cenią swój rodowód i nie interesują się zbytnio takimi jak ja czy ty. Weź to. Pomoże ci jeśli sprawy wymkną się spod kontroli. Chyba będzie lepiej, żeby nikt cię nie widział jak rozmawiasz ze starym wariatem. Lepiej już ruszaj.}
{126}{}{Dziękujemy za pomoc.}
{127}{}{Pozwól staruszkowi odpocząć.}
{128}{}{Takie podobieństwo...}
{129}{}{Zostaw mnie teraz samego.}
{130}{}{Lepiej już idź.}
{131}{}{Jeśli będziemy dłużej rozmawiać, ktoś może nabrać podejrzeń.}
{132}{}{No już, idź. Uczyń mojego przyjaciela dumnym.}
