{100}{}{Widzisz stra¿nika. Ma on na sobie metalow¹ zbrojê i trzyma strzelbê.}
{101}{}{Widzisz stra¿nika Kryptopolis.}
{102}{}{Tak? O co chodzi?}
{103}{}{Ja chce wejœæ do du¿a dziura w górze.}
{104}{}{Chcê wejœæ do Krypty.}
{105}{}{Nic, przepraszam, ¿e przeszkadzam.}
{106}{}{Ju¿ po 18. Mo¿esz iœæ.}
{107}{}{OK. Ju¿ idê.}
{108}{}{OK. Potrzebujê tylko minutê.}
{109}{}{Mam coœ do za³atwienia. Wrócê jak ju¿ to zrobiê.}
{110}{}{Umag Nak!?! Umag NAK!}
{111}{}{Stra¿nicy ciê odeskortuj¹.}
{112}{}{Dobra. ChodŸmy.}
{113}{}{Brog Frup}
{114}{}{Don't bother. I can find my own way.}
{115}{}{Przykro mi, ale takie s¹ rozkazy.}
{116}{}{Dobra... ale nie cieszy mnie to zbytnio. Chyba z³o¿ê formalny protest...}
{117}{}{Ja zostajê.}
{118}{}{Nie chcê u¿ywaæ si³y je¿eli nie bêdzie to konieczne. Nie czyñ tego trudniejszym ni¿ ju¿ jest.}
{119}{}{OK, dobrze, dobrze... Idê..}
{120}{}{Je¿eli mnie dotkniesz bêdziesz móg³ u¿yæ swojej dupy jako kapelusza.}
{121}{}{Witam, obywatelu. W czym mogê pomóc?}
{122}{}{Chcê wejœæ do Krypty.}
{123}{}{Wejœæ w dziura w góra!}
{124}{}{Ech... nic... przepraszam.}
{125}{}{Przykro mi, ale tylko obywatele s¹ upowa¿nieni do wejœcia do Krypty. Wiem, ¿e to zrozumiesz.}
{126}{}{Tylko obywatele mog¹ wejœæ. OdejdŸ.}
{127}{}{Okay.}
{128}{}{Umgh}
{129}{}{Oczywiœcie. Proszê wejœæ.}
{130}{}{Dziêki!}
{131}{}{Dziêkujê.}
{132}{}{Tak? W czym mogê pomóc?}
{133}{}{Chcê wejœæ do Krypty.}
{134}{}{Przepraszam, ¿e przeszkadzam.}
{135}{}{Przykro mi, ale tylko obywatele mog¹ wejœæ do Krypty.}
{136}{}{Ja *jestem* obywatelem.}
{137}{}{Wybacz ale... nie znam ciê. Rozkazy mówi¹ wyraŸnie, ¿e tylko obywatele mog¹ wejœæ do Krypty. Byæ mo¿e Pierwszy Obywatel Lynette ci pomo¿e. Do widzenia.}
{138}{}{Witam Kapitanie. W czym mogê pomóc?}
{139}{}{Och, dobrze.}
{140}{}{Oczywiœcie. Rozgl¹dam siê.}
{141}{}{Umgh}
{142}{}{Ta, jasne. Gadaj sobie.}
{143}{}{Hej, Ty! Co ten ghul robi w Kryptopolis?!}
{144}{}{Hej! Ty! Co ten mutant robi w Kryptopolis?!}
{145}{}{Breep-oop foop foop}
{146}{}{Ghul? Gdzie?}
{147}{}{Mutant? Gdzie?}
{148}{}{Jest ze mn¹.}
{149}{}{Podró¿uje ze mn¹. Je¿eli jakiœ rasista ma w tym problem to mo¿emy to rozwi¹zaæ tu i teraz.}
{150}{}{Je¿eli on jest z tob¹, to obaj powinniœcie wróciæ na Podmurze, a nie wychodziæ na ulice Kryptopolis.}
{151}{}{Dobra, dobra... Wracamy.}
{152}{}{Nie zechcia³byœ nas eskortowaæ? Zapewniam ciê, ¿e by³oby to pouczaj¹ce doœwiadczenie trepie.}
{153}{}{Jak ci obcy siê tu dostali...?}
{154}{}{To coœ, tam.}
{155}{}{Wracajcie na Podmurze i nie szlajajcie siê po ulicach Kryptopolis.}
{156}{}{JA NIE IŒÆ! TY FA GAS!}
{157}{}{Odejdziemy po-ci-chu-tku}
{158}{}{Dobra... odchodzimy.... spokojnie.}
{159}{}{On podró¿uje ze mn¹. Je¿eli jakiœ rasista ma w tym problem to mo¿e powinniœmy go rozwi¹zaæ tu i teraz.}
{160}{}{Stra¿e! Intruzi w mieœcie!}
{161}{}{Hrngh!}
{162}{}{Nie wiesz z kim zacz¹³eœ psi synu.}
{163}{}{Hej! Oto i nasz bohater!}
{164}{}{Hej! Opowiedz nam o zniszczeniu Enklawy!}
{165}{}{Witam w Kryptopolis.}
{166}{}{Twoja wyprawa zrobi³a wra¿enie nawet na Pierwszym Obywatelu.}
{167}{}{S³ysza³em, ¿e uda³o ci siê zwiedziæ ca³y œwiat podczas wyprawy na Enklawê. To prawda?}
{168}{}{Czy to prawda, ¿e USA nadal prowadzi wojnê?}
{169}{}{Ktoœ powinien spisaæ twoje dokonania w komputerze Kryptopolis.}
{170}{}{Mo¿esz zostaæ w Kryptopolis tak d³ugo jak chcesz.}
{171}{}{Mo¿esz wgraæ swojego Pip-boya na g³ówny serwer Kryptopolis.}
{172}{}{Kapitanie.}
{173}{}{Kryptopolis ponad wszystkim, Kapitanie.}
{174}{}{Witam, Kapitanie.}
{175}{}{Kryptopolis ponad wszystkim, obywatele.}
{176}{}{Obywatelu.}
{177}{}{Witam, obywatelu.}
