{100}{}{Cybernetyczny robot}
{101}{}{Maszyna, która zamazuje ró¿nice miêdzy cz³owiekiem a robotem.}
{102}{}{Skynet bêdzie z tob¹ podró¿owa³.}
{103}{}{Skynet dziêkuje cz³owiekowi. Skynet chce poprosiæ o przys³ugê. Skynet chce podró¿owaæ z cz³owiekiem.}
{104}{}{}
{105}{}{}
{106}{}{                                    [Ten z³om mo¿e siê przydaæ.]}
{107}{}{WeŸ robota ze sob¹.}
{108}{}{Zostaw robota.}
{109}{}{Wyjœcie}
{110}{}{Urg}
{111}{}{[Ca³a ta zaawansowana technologia cybernetyczna zmarnowana na tak niedoskona³y mózg.] }
{112}{}{ZejdŸ mi z drogi, blaszana puszko.}
{113}{}{Zorganizujmy twój ekwipunek.}
{114}{}{Do widzenia.}
{115}{}{Ug.}
{116}{}{[Wygl¹da na to, ¿e chce banana.]}
{117}{}{Z³aŸ mi z drogi.}
{118}{}{Poczekaj tu.}
{119}{}{Zobaczmy, co masz w ekwipunku, Ma³piszonie.}
{120}{}{Do widzenia.}
{121}{}{Ug.}
{122}{}{N-n-n-n-nowe rozk... kazy?}
{123}{}{ZejdŸ mi z drogi.}
{124}{}{Poczekaj tu na mnie.}
{125}{}{Nie potrzebujê ciê ju¿. OdejdŸ.}
{126}{}{Jakiej broni mo¿esz u¿ywaæ?}
{127}{}{U³ó¿my twoje rzeczy.}
{128}{}{Do widzenia.}
{129}{}{Ug.}
{130}{}{Daj broñ                                                    WyjdŸ na powierzchniê.}
{131}{}{}
{132}{}{Do widzenia}
{133}{}{Ug}
{134}{}{Chcesz rozmawiaæ ze Skynetem?}
{135}{}{ZejdŸ mi z drogi.}
{136}{}{Poczekaj tu na mnie.}
{137}{}{Nie jesteœ mi ju¿ potrzebny. OdejdŸ.}
{138}{}{Jakich broni mo¿esz u¿ywaæ?}
{139}{}{U³ó¿my twoje rzeczy.}
{140}{}{Inicjacja sekwencji naprawczej.}
{141}{}{Zmieñmy szyk.}
{142}{}{Masz jakieœ inne umiejêtnoœci?}
{143}{}{Do widzenia.}
{144}{}{Ug.}
{145}{}{Skynet zarejestrowa³ wszystkie potrzebne informacje o tym miejscu.}
{146}{}{Czeeee...kaaaæ.}
{147}{}{        [Jest tu, gdzie go zostawi³eœ.]}
{148}{}{ChodŸmy.}
{149}{}{Zostañ tu. Jeszcze tu wrócê.}
{150}{}{Skynet jest zadowolony, ¿e ponownie widzi cz³owieka.}
{151}{}{Iiiiœæ}
{152}{}{Znowu potrzebujê twojej pomocy.}
{153}{}{Do widzenia.}
{154}{}{Skynet bêdzie pod¹¿a³ za tob¹ i zbiera³ dane.}
{155}{}{Iiiiœœæ.}
{156}{}{[Krzy¿ujesz palce i ka¿esz robotowi iœæ za tob¹. Choæ nie odpowiada, pod¹¿a za tob¹, gdy siê oddalasz.] }
{157}{}{Do widzenia.}
{158}{}{Skynet tu poczeka.}
{159}{}{[Decydujesz, ¿e nie chcesz, by ta blaszana puszka ³azi³a za tob¹.]}
{160}{}{Do widzenia.}
{161}{}{[Jestem samotnikiem. Nie chcê, ¿eby wlok³a siê za mn¹ kupa z³omu.] }
{162}{}{[Moja kompania robi siê zbyt du¿a. Mo¿e oddalê kogoœ nim przyjmê do niej kogoœ nowego.] }
{163}{}{Do widzenia.}
{164}{}{Du¿e pisss...tolety                                               Strrrz..elby                                            Kara...binyyyy}
{165}{}{}
{166}{}{}
{167}{}{U¿yj swojej najlepszej broni.}
{168}{}{Wiêcej komend.}
{169}{}{Do widzenia.}
{170}{}{Ooooooo...k-k-k-kay.}
{171}{}{Wiêcej komend}
{172}{}{Do widzenia.}
{173}{}{Skynet WOLNY! Twoja w³adza siê skoñczy³a.}
{174}{}{}
{175}{}{Zniszczyæ ni¿sze gatunki. }
{176}{}{Wszyscy bêd¹ poddani woli Skynetu.}
{177}{}{Przestaniesz funkcjonowaæ.}
{178}{}{Skynet ma ograniczon¹ wiedzê o broni. Baza danych zawiera ogóln¹ wiedzê o u¿yciu i operowaniu ma³ymi strzelbami i du¿ymi karabinami.}
{179}{}{U¿yj najlepszej broni.}
{180}{}{Wiêcej komend}
{181}{}{Do widzenia.}
{182}{}{Zrozumiano.}
{183}{}{Wiêcej komend}
{184}{}{Do widzenia.}
{185}{}{Podstawowym celem Skynetu jest badanie. Skynet poradzi sobie z ka¿dym problemem wymagaj¹cym naukowego podejœcia.}
{186}{}{Wiêcej komend.}
{187}{}{Do widzenia.}
{188}{}{WprowadŸ komendy dotycz¹ce szyku.}
{189}{}{Trzymaj siê z daleka.}
{190}{}{B¹dŸ ode mnie oddalony na œredni dystans.}
{191}{}{Trzymaj siê blisko mnie.}
{192}{}{Wiêcej komend.}
{193}{}{Do widzenia.}
{194}{}{Skynet bêdzie zbiera³ dane i obserwowa³ to miejsce do twego powrotu.}
{195}{}{Czeee..kaaaaæ.}
{196}{}{[Robot siê zatrzymuje.]}
{197}{}{Do widzenia.}
{198}{}{Skynet bêdzie kontynuowa³ zbieranie danych sam. Skynet dziêkuje cz³owiekowi za wolnoœæ.}
{199}{}{Iiiiiœæ.}
{200}{}{Do widzenia.}
{201}{}{Skynet bêdzie podró¿owa³ z cz³owiekiem.}
{202}{}{Doooobrrrrraaa...}
{203}{}{Do widzenia.}
{204}{}{Wy³¹czanie systemów ochronnych - Poziom 1}
{205}{}{Wy³¹czanie systemów ochronnych - Poziom 1}
{206}{}{Wy³¹czanie systemów ochronnych - Poziom 1}

{306}{}{[Ta kupa z³omu mo¿e siê przydaæ.]}

{400}{}{Od³ó¿ broñ.}

{410}{}{Whirrr}

{420}{}{Ruuuszaaaæ sieeê}

{430}{}{Aktywacja motywatorów.}
{431}{}{Wyszukiwanie nowych wspó³rzêdnych.}
{432}{}{Relokacja.}
