{100}{}{Terminal.}
{101}{}{Ten komputer jest doœæ antyczny. Jego procesor ma tylko 500MHz.}
{102}{}{Nie mo¿esz przeczytaæ tego, co pokazuje monitor.}
{103}{}{Zautomatyzowany Oœrodek Napraw.
 Przetwarzam ¯¹dania Napraw zg³oszone przez Skynet...
 Wysy³am Jednostki Naprawcze}
{104}{}{}
{105}{}{}
{106}{}{Spróbuj wy³¹czyæ oœrodek napraw.}
{107}{}{Wyci¹gnij komputerowi wtyczkê z gniazdka.}
{108}{}{Wciœnij du¿y czerwony przycisk z napisem "WY£".}
{109}{}{Koniec}
{110}{}{[Nie umiesz domyœliæ siê, jak wy³¹czyæ ten program.]}
{111}{}{Koniec}
{112}{}{[Wpisanie s³owa "wy³¹cz" chyba podzia³a³o. Automatyczny system naprawczy wy³¹czy³ siê.]}
{113}{}{Koniec}
{114}{}{[Przez czysty przypadek zauwa¿asz kabel ci¹gn¹cy siê od komputera do gniazdka w œcianie. Ekran komputera staje siê czarny, gdy tylko wyci¹gasz wtyczkê.]}
{115}{}{Koniec}
{116}{}{[Odwa¿nie naciskasz czerwony przycisk z napisem "WY£". Zgodnie z oczekiwaniami, terminal przestaje wyœwietlaæ cokolwiek.]}
{117}{}{Koniec}
{118}{}{[Kiedy zaczynasz wpisywaæ tekst z klawiatury, klawisze wyskakuj¹ z niej i spadaj¹ na pod³ogê. To by by³o na tyle, jeœli chodzi o korzystanie z tego terminala.]}
{119}{}{Koniec}
{120}{}{Automatyczny system naprawczy jest ju¿ wy³¹czony.}
{121}{}{Nie mogê skorzystaæ z tego terminala. Ktoœ zepsu³ klawiaturê.}
