{100}{}{Terminal.}
{101}{}{Oszczêdzacz ekranu jest w³¹czony.}
{103}{}{System Bezpieczeñstwa Skynet.
 Intruz na Poziomie 2.
 Uruchamiam Œrodki Zapobiegawcze na Poziomie 2...
 Œrodki Zapobiegawcze - Transmisja Przerwana.
 Uruchamiam Zautomatyzowany System Naprawczy}
{104}{}{System Bezpieczeñstwa Skynet.
 Intruz na Poziomie 2.
 Uruchamiam Œrodki Zapobiegawcze na Poziomie 2...
 Podejmujê próbê okrê¿nego pod³¹czenia zasilania do generatorów pola}
{105}{}{System Bezpieczeñstwa Skynet.
 Intruz na Poziomie 2.
 Uruchamiam Œrodki Zapobiegawcze na Poziomie 2}
{106}{}{Alarm na Poziomie 2 odwo³any - Fa³szywy alarm.}
{107}{}{[Dostrzegasz na klawiaturze klawisz z napisem "Pomoc".] Wciœnij klawisz.}
{108}{}{W³am siê do systemu bezpieczeñstwa.}
{109}{}{Spróbuj wy³¹czyæ alarm.}
{110}{}{Koniec.}
{111}{}{Ajj! [Uderzasz ze z³oœci¹ piêœci¹ w klawiaturê.]}
{113}{}{System Bezpieczeñstwa Skynet.
 Uwaga! Wykryto Intruza na Poziomie 1.
 Uruchomiono Czytnik Siatkówki.
 Trwa Odczyt...
 Przeszukujê Bazê Danych}
{300}{}{ - To¿samoœæ Potwierdzona}
{301}{}{Ostatnie Wejœcie: }
{302}{}{Wy³¹czam Blokadê Windy}

{303}{}{Kapral Dixon}
{304}{}{Genera³ Clifton}
{305}{}{5 Grudnia 2120}
{306}{}{ dni temu.}

{114}{}{System Bezpieczeñstwa Skynet.
 Uwaga! Wykryto Intruza na Poziomie }
{307}{}{System Bezpieczeñstwa Skynet.
 Uwaga! Wykryto Intruzów na Poziomach: }
{115}{}{W³¹czam System Alarmowy na Poziomie 2}
{116}{}{W³¹cz program autodiagnostyczny.}
{117}{}{Koniec}
{118}{}{Ajj! [Uderzasz ze z³oœci¹ piêœci¹ w klawiaturê.]}
{120}{}{System Bezpieczeñstwa Skynet.
 Dostêp z Tego Terminala jest Zabroniony}
{122}{}{Koniec.}
{124}{}{B³¹d!
 Brak plików programowych.
 Proszê prze³adowaæ system}
{126}{}{Koniec}
{127}{}{Trwa Analiza Polecenia, Proszê Czekaæ...
 Uniewa¿niam Polecenie Uzytkownika.
 Dostêp Zabroniony}
{128}{}{[Dalej]}
{129}{}{Aby Wy³¹czyæ Alarm Wciœnij - 1.
 Aby W³¹czyæ Program Autodiagnostyczny Wciœnij - 2.
 Aby Zakoñczyæ Wciœnij - 3}
{130}{}{Wciœnij 1}
{131}{}{Wciœnij 2}
{132}{}{Wciœnij 3}
{133}{}{Koniec}
{134}{}{Uwaga! Ten program dzia³a najlepiej, gdy wszystkie programy zostan¹ wy³¹czone. Czy chcesz zroibc to teraz?}
{135}{}{Tak.}
{136}{}{Nie.}
{137}{}{Koniec}
{138}{}{Wy³¹czam Program Ochronny Skynet...
 Analizujê Strukturê Danych...
 Przerwano Diagnozê.
 Przerwano Program Diagnostyczny.
 Ponownie Uruchamiam Program Ochronny...
 Resetujê Alarm.
 System Bezpieczeñstwa Skynet - Gotów}
{139}{}{Koniec}
{140}{}{Dostêp Zabroniony...
 Dostêp Zabroniony...
 Dostêp Przyznany.
 Wy³¹czam System Alarmowy na Poziomie 2}
{141}{}{Koniec}
{142}{}{Nieupowa¿nione Wejœcie.
 Uruchamiam Blokadê Ochronn¹ tego Termianala}
{143}{}{Koniec}
{144}{}{Trwa Analiza Polecenia, Proszê Czakaæ...
 Zakoñcz wsz...
 Uniewa¿nione Przez Skynet - Kod 667.
 Dostêp do tego Terminala zosta³ Odciêty.}
{145}{}{Koniec.}
{146}{}{Wy³¹czam Program Diagnostyczny.}
{147}{}{[Dalej]}
