{100}{}{Terminal.}
{101}{}{W wielu miejscach do obudowy poprzylepiano zdjêcia sk¹po odzianych kobiet.}
{102}{}{Nie mo¿esz przeczytaæ tego, co pokazuje monitor.}
{103}{}{Terminal Zarz¹dzania Wyposa¿eniem.
 Pole Si³owe - Wy³¹czone.
 P³yty Pora¿aj¹ce - Wy³¹czone}
{104}{}{Terminal Zarz¹dzania Wyposa¿eniem.
 Pole Si³owe - Wy³¹czone.
 P³yty Pora¿aj¹ce - W³¹czone}
{105}{}{Terminal Zarz¹dzania Wyposa¿eniem.
 Pole Si³owe - W³¹czone.
 P³yty Pora¿aj¹ce - Wy³¹czone}
{106}{}{Terminal Zarz¹dzania Wyposa¿eniem.
 Pole Si³owe - W³¹czone.
 P³yty Pora¿aj¹ce - W³¹czone}
{107}{}{Wy³¹cz P³yty Pora¿aj¹ce}
{108}{}{Wy³¹cz Pole Si³owe}
{109}{}{Przeczytaj Pocztê}
{110}{}{Koniec}
{111}{}{[Mimo usilnych prób z twojej strony, te wszystkie dziwne kreski nic ci nie mówi¹.]}
{112}{}{Wy³¹cz P³yty Pora¿aj¹ce. Proszê Podaæ Has³o:}
{113}{}{W³am siê do sytemu bezpieczeñstwa}
{114}{}{Zgadnij Has³o}
{115}{}{Wróæ do G³ównego Menu}
{116}{}{Koniec}
{117}{}{[Ten program jest dla ciebie po prostu zbyt skomplikowany.]}
{118}{}{Wróæ do G³ównego Menu}
{119}{}{Koniec}
{120}{}{[Udaje ci siê obejœæ sprawdzanie has³a i wy³¹czyæ P³yty Pora¿aj¹ce.]}
{121}{}{Wróæ do G³ównego Menu}
{122}{}{Koniec}
{123}{}{Wy³¹cz Pola Si³owe.
 Proszê Podaæ Has³o:}
{124}{}{W³am siê do systemu bezpieczeñstwa}
{125}{}{Zgadnij Has³o}
{126}{}{Wróæ do G³ównego Menu.}
{127}{}{Koniec}
{128}{}{[Te pliki s¹ zakodowane i bez dekodera nie dasz rady cokolwiek z nich odczytaæ.]}
{129}{}{Wróæ do G³ównego Menu}
{130}{}{Koniec}
{131}{}{[Dzieciêca igraszka. Pola si³owe s¹ teraz wy³¹czone.]}
{132}{}{Wróæ do G³ównego Menu.}
{133}{}{Koniec.}
{134}{}{[Ktoœ zapomnia³ zamkn¹æ swoj¹ skrzynkê pocztow¹.]
 Potwierdzenie Zamówienia,
 Uwaga dot. Ewakuacji,
 Randka w Ciemno,
 Handel}
{135}{}{[Wybiesz, który plik chcesz odczytaæ.]}
{136}{}{Przeczytaj list "Potwierdzenie Zamówienia"}
{137}{}{Przeczytaj list "Uwaga dot. Ewakuacji"}
{138}{}{Przeczytaj list "Randka w Ciemno"}
{139}{}{Przeczytaj list "Handel"}
{140}{}{Wróæ do G³ównego Menu}
{141}{}{Koniec}
{142}{}{To jest potwierdzenie odbioru Pañskiego zamówienia na "T³oczenie Debbie i Jej Ró¿ne Æwiczenia Ustne, zestaw 1059". Zamówione przez Pani¹/Pana towary powinny nadejœæ poczt¹ w ci¹gu 2 do 4 tygodni. Dziêkujemy za Pañskie zamówienie.}
{143}{}{Przeczytaj inne listy}
{144}{}{Koniec}
{145}{}{Ewakuacja Sk³adu Wojskowego Sierra zosta³a przyspieszona o tydzieñ. Wszystkie œrodki ochronne musz¹ byæ uruchomione do tego czasu. Z rozkazu Genera³a Cliftona.}
{146}{}{Przeczytaj inne listy}
{147}{}{Koniec}
{148}{}{[Rozlega siê ciche furkotanie i z terminala zaczynaj¹ wydobywaæ siê k³eby dymu. Stoisz tak i patrzysz jak klawiatura zamienia siê w lepk¹ ka³u¿ê. Hmm... to musia³ byæ jeden z tych wirusów, o których ci tyle mówiono.]}
{149}{}{Koniec}
{150}{}{Tu Klinger z 8063-ciej. Desperacko potrzebujemy czêœci numer 102-53B. Gdybyœ móg³ wys³aæ dla nas zamówienie, to mam skrzynkê Chateau Lafayette z 2155. Odpisz mi ASAP.}
{151}{}{Przeczytaj inne listy}
{152}{}{Koniec}
{153}{}{[Có¿ za nieprawdopodobne szczêœcie! Uda³o ci siê zgadn¹æ w³aœciwe has³o. "Melony".] Wy³¹czam P³yty Pora¿aj¹ce}
{154}{}{Wróæ do G³ównego Menu}
{155}{}{Koniec}
{156}{}{[Mimo usilnych prób nie jesteœ w stanie odgadn¹æ has³a.]}
{157}{}{Wróæ do G³ównego Menu}
{158}{}{Koniec}
{159}{}{[Ta osoba musia³a mieæ obsesjê na punkcie biustów. Prawid³owe has³o to "cycuszki"]
 Wy³¹czam Pola Si³owe}
{160}{}{Wróæ do G³ównego Menu}
{161}{}{Koniec}
{162}{}{[Mimo usilnych prób nie jesteœ w stanie odgadn¹æ has³a.]}
{163}{}{Wróæ do G³ównego Menu}
{164}{}{Koniec}
{165}{}{[Jakimœ cudem twoje majstrowanie powoduje, ¿e terminal wybucha ci prosto w twarz.]}
{166}{}{Koniec}

{200}{}{[Ten terminal nie jest ju¿ sprawny.]}
