{100}{}{Terminal.}
{101}{}{Terminal Kontroli Zasobów Biologicznych.}
{102}{}{Nie mo¿esz przeczytaæ tego, co pokazuje monitor.}
{103}{}{Zak³ad Przechowywania Zasobów Biologicznych.
 G³ówne Menu:
 Pobierz,
 Przechowaj}
{104}{}{}
{105}{}{}
{106}{}{}
{107}{}{Pobierz}
{108}{}{Przechowaj}
{109}{}{Koniec}
{110}{}{Ug.}
{111}{}{[Nie mo¿esz przeczytaæ tego, co pokazuje monitor.]}
{112}{}{Ten terminal jest Nieczynny.
 Proszê skontaktowaæ siê z administratorem sieci w celu uzyskania dalszych szczególów.}
{113}{}{}
{114}{}{Urg}
{115}{}{Koniec}
{116}{}{G³ówne Menu Pobierania:
 Wirus,
 Organy,
 Zw³oki}
{117}{}{}
{118}{}{}
{119}{}{}
{120}{}{Wybierz Wirusa}
{121}{}{Wybierz Organy}
{122}{}{Wybierz Zw³oki}
{123}{}{Wróæ do G³ównego Menu}
{124}{}{Koniec}
{125}{}{Wybór Wirusa:
 W¹glik,
 Czarna Œmieræ (Odmiana 238),
 Ospa (Odmiana 1025),
 Ebola,
 Hantawirus (Odmiana 304)}
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}
{130}{}{}
{131}{}{Pobierz W¹glika}
{132}{}{Pobierz Czarn¹ Œmieræ}
{133}{}{Pobierz Ospê}
{134}{}{Pobierz Ebolê}
{135}{}{Pobierz Hantawirusa}
{137}{}{Wróæ do G³ównego Menu Pobierania}
{138}{}{Koniec}
{139}{}{[Obserwujesz jak robot przemieszcza siê wœród rzêdów pojemników z materia³ami biologicznymi i wraca z ma³¹ probówk¹, któr¹ szybko wk³ada do otworu w œcianie. Obserwujesz z zachwytem jak probówka zostaje przeniesiona ze szczelnego œrodowiska obszaru magazynowego do sali, w której siê znajdujesz. Twój zachwyt zmienia siê w przera¿enie, gdy probówka spada i rozbija siê o pod³ogê. Ucieczka wydaje siê doskona³ym pomys³em.]}
{140}{}{Koniec}
{141}{}{Wybór Organu:
 Serce,
 Mózg,
 Nerka,
 W¹troba,
 P³uco}
{142}{}{}
{143}{}{}
{144}{}{}
{145}{}{}
{146}{}{}
{147}{}{Pobierz Serce}
{148}{}{Pobierz Mózg}
{149}{}{Pobierz Nerkê}
{150}{}{Pobierz W¹trobê}
{151}{}{Pobierz P³uco}
{152}{}{Wróæ do G³ównego Menu Pobierania}
{153}{}{Koniec}
{154}{}{Uwaga! Awaria aparatu przechowuj¹cego.
 [S¹dz¹c z odczytów, urz¹dzenia przechowuj¹ce te organy zepsu³y siê dawno temu. O ile nie masz ochoty na zupê, pobieranie czgokolwiek nie ma wiêkszego sensu.]}
{155}{}{}
{156}{}{Wróæ do Menu Wyboru Organu}
{157}{}{Wróæ do G³ównego Menu Pobierania}
{158}{}{Koniec}
{159}{}{Uwaga! Awaria aparatu przechowuj¹cego.
 Zbiorniki 101 - 104.
 Potrzebne Poprawki Ustawieñ.
 [Do uratowania mózgów potrzebne bêd¹ bardzo precyzyjne wyliczenia. Ci¹gi wzorów i wyników pomiarów przelatuj¹ przez ekran. To wszystko sprawia wra¿enie bardzo uczonego.]}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{Spróbuj dokonaæ poprawek}
{164}{}{Wróæ do G³ównego Menu Pobierania}
{165}{}{Spróbój póŸniej.}
{166}{}{[Na skutek niedorzecznoœci twoich dzia³añ wszystkie mózgi umieraj¹. Podwy¿szanie temperatury do 98.6 stopni Celsjusza to by³o chyba trochê za du¿o. Nauki œcis³e nigdy nie by³y twoj¹ mocn¹ stron¹.]}
{167}{}{Koniec.}
{168}{}{[Metoda prób i b³êdów jest chyba twoj¹ g³ówn¹ metod¹ rozwi¹zywania tego problemu. Udaje ci siê uratowaæ jeden z czterech mózgów. Zreszt¹ nauka jest dla palantów.]}
{169}{}{Pobierz Mózg}
{170}{}{[U¿ywaj¹c prawa uœredniania udaje ci siê uratowaæ piêædziesi¹t procent mózgów. Naukowcem to ty nie jesteœ.]}
{171}{}{Pobierz Mózg}
{172}{}{[Z pewnoœci¹ wiesz co robisz. Pomijaj¹c jeden b³¹d, uda³o ci siê uratowaæ 3 z 4 mózgów. Coœ ci mówi³o ca³y czas, ¿e czytanie tych wszystkich czasopism naukowych mo¿e siê na coœ przydaæ.]}
{173}{}{Pobierz Mózg}
{174}{}{[Dziêki u¿yciu kilku szybkich skrótów klawiszowych udaje ci siê zapobiec kryzysowi i uratowaæ wszystkie mózgi. Nauki œcis³e to dla ciebie zdecydowanie coœ wiêcej ni¿ hobby.]}
{175}{}{Pobierz Mózg}
{176}{}{Wybór Mózgu:
 Mózg Upoœledzony,
 Mózg Szympansa,
 Mózg Cz³owieka,
 Mózg Cybernetyczny}
{177}{}{Wybór Mózgu:
 Mózg Upoœledzony,
 Mózg Szympansa,
 Mózg Cz³owieka,
 Mózg Cybernetyczny - Martwy}
{178}{}{Wybór Mózgu:
 Mózg Upoœledzony,
 Mózg Szympansa,
 Mózg Cz³owieka - Martwy,
 Mózg Cybernetyczny - Martwy}
{179}{}{Wybór Mózgu:
 Mózg Upoœledzony,
 Mózg Szympansa - Martwy,
 Mózg Cz³owieka - Martwy,
 Mózg Cybernetyczny - Martwy}
{180}{}{}
{185}{}{}
{189}{}{}
{193}{}{}
{196}{}{Mózg Upoœledzony}
{197}{}{Mózg Szympansa}
{198}{}{Mózg Cz³owieka}
{199}{}{Mózg Cybernetyczny}
{200}{}{[Chocia¿ odczyty wskazuj¹, ¿e ten mózg jest zywy, poziomy wyjœæ nerwowych s¹ du¿o poni¿ej normy.]
 Pobraæ?}
{201}{}{}
{202}{}{Tak}
{203}{}{Nie}
{204}{}{[Fale mózgowe s¹ aktywne, ale ró¿ni¹ siê od tych, które ma mózg cz³owieka.]
 Pobraæ?}
{208}{}{[Aktywnoœæ mózgu jest taka jak u przeciêtnego c¿³owieka.]
 Pobraæ?}
{212}{}{[Aktywnoœæ mózgu przebija wszystkie skale! Na oko sygna³y s¹ zarówno ludzkiego pochodzenia jak i cyfrowe.]
 Pobraæ?}
{216}{}{[Robot szybko odje¿d¿a by pobraæ twój mózg. Kiedy wraca, dostrzegasz, ¿e ma jakieœ problemy. Przypuszczenia potwierdzaj¹ siê, gdy robot niespodziewanie wybucha. Na szczêœcie dla ciebie, uda³o mu siê dostarczyæ mózg, zanim siê rozpad³.]}
{217}{}{Koniec}
{218}{}{Wybór Zw³ok:
 Szeregowy Dobbs}
{219}{}{}
{220}{}{Pobierz Szeregowego Dobbsa}
{221}{}{Wróæ do G³ównego Menu Pobierania}
{222}{}{Koniec}
{223}{}{[Wnosz¹c z odczytów, szeregowy Dobbs jest ¿ywy! Umieszczono go w zbiorniku regeneracyjnym, zawieraj¹cym Eksperymentalny ¯el Biomed.] Pobraæ?}
{224}{}{}
{225}{}{Tak}
{226}{}{Nie}
{227}{}{[Cia³o Szeregowego Dobbsa le¿y teraz u twych stóp, ale ku twemu zaskoczeniu, wstaje i zaczyna do ciebie mówiæ. Zabawne, wcale nie wygl¹da na trupa.]}
{228}{}{Koniec}
{229}{}{W tej chwili w magazynie nie ma ¿adnych zw³ok.}
{230}{}{Wróæ do G³ównego Menu Pobierania}
{231}{}{Koniec}
{232}{}{[Mimo i¿ na w³asne oczy widzisz puste pojemniki, odczyty wskazuj¹, ¿e s¹ one pe³ne. Widocznie w programie jest jakiœ b³¹d. Zreszt¹ kto by siê tym przejmowa³.]}
{233}{}{Wróæ do G³ównego Menu}
{234}{}{Koniec }

{300}{}{ nie mo¿e przeczytaæ tego, co pokazuje monitor.}
