{100}{}{Widzisz w³¹czony terminal.}
{101}{}{Przygl¹daj¹c siê uwa¿nie terminalowi dostrzegasz napis: "I*tel Inside".}
{102}{}{Nie mo¿esz przeczytaæ tego, co jest wyœwietlone na monitorze.}
{200}{}{ nie mo¿e przeczytaæ tego, co jest wyœwietlone na monitorze.}

{103}{}{G³ówne Zasilanie = Od³¹czone. Zasilanie Zapasowe = Za³¹czone. Ponowne uruchomienie Programu Ochronnego... Uwaga - Niedobór Mocy - Pola Si³owe ustawione na 50%. £adowanie zakoñczone... System Bezpieczeñstwa Skynet - Punkt Kontrolny 1. Proszê Wprowadziæ Has³o:_}
{104}{}{System Bezpieczeñstwa Skynet - Punkt Kontrolny 1. Proszê Wprowadziæ Has³o:_}
{105}{}{Czajkowski}
{106}{}{Otwórz}
{107}{}{Sierra}
{108}{}{Armageddon}
{109}{}{W³am siê do systemu ochronnego.}
{110}{}{Nie mam pojêcia. Koniec.}
{113}{}{Pola Si³owe Od³¹czone - Poziom 1}
{115}{}{Koniec}
{117}{}{Dostêp z tego termianala zosta³ odciêty.}
{119}{}{Koniec}
{121}{}{B³¹d 29. Po³¹czenie z serwerem niemo¿liwe. Proszê prze³adowaæ system.}
{123}{}{Koniec}
{124}{}{Przyznano dostêp. Pola Si³owe na Poziomie 1: Od³¹czone}
{125}{}{Koniec}
{126}{}{Z³e Has³o. Dostêp Zabroniony. Proszê Wprowadziæ Has³o:_}
{127}{}{Czajkowski}
{128}{}{Otwórz}
{129}{}{Sierra}
{130}{}{Armageddon}
{131}{}{W³am siê do systemu ochronnego.}
{132}{}{Nie masz pojêcia. Koniec.}
{133}{}{[Naciœniêcie <Ctrl><Alt><C> powoduje wykrzaczenie programu. Masz nadziejê, ¿e reszta zabezpieczeñ bêdzie równie ³atwa do pokonania.]}
{134}{}{Koniec.}
{135}{}{Naruszenie Bezpieczeñstwa na Poziomie 1. Uruchamiam Protokó³ Bezpieczeñstwa... Dostêp z tego terminala zostaje odciêty. Koniec Transmisji}
{136}{}{Koniec}
{137}{}{Twoja nieudolnoœæ spowodowa³a uruchomienie alarmu.}
{138}{}{To na nic siê nie zda, ten program jest dla ciebie po prostu zbyt skomplikowany.}
{139}{}{Koniec}

{300}{}{Wygl¹da na to, ¿e komputer ma zainstalowany jakiœ mechanizm obronny.}
{301}{}{Ulegasz pora¿eniu za }
{302}{}{ ulega pora¿eniu za }
{303}{}{ punktów.}
