{100}{}{Terminal}
{101}{}{Ma ma³¹ naklejkê z napisem "I*tel inside".}
{102}{}{[Nie mo¿esz przeczytaæ tego, co pokazuje monitor.]}
{103}{}{Terminal Steruj¹cy.
 Projekt: Eksperymentalna Synteza Mechaniczno Organiczna}
{104}{}{}
{105}{}{Kontrola Systemu.}
{106}{}{Uruchom Robota}
{107}{}{Koniec}
{108}{}{Erg?}
{109}{}{[Nie mo¿esz przeczytaæ tego, co pokazuje monitor.]}
{110}{}{Koniec Programu}
{111}{}{Koniec}
{112}{}{Ug}
{113}{}{Proszê Czekaæ...
 Korpus Robota - OK.
 Zbiorniki ¿elu Biomed - Pe³ne.
 Organiczne Urz¹dzenie Przechowawcze - Odpowiada.
 Gotowy na Uruchomienie}
{114}{}{Proszê Czekaæ...
 Korpus Robota - OK.
 Zbiorniki ¿elu Biomed - Uzupe³niæ.
 Organiczne Urz¹dzenie Przechowawcze - Brak.
 Uruchomienie niezalecane}
{115}{}{Proszê Czekaæ...
 Korpus Robota - Wymieniæ Napêd.
 Zbiorniki ¿elu Biomed - OK.
 Organiczne Urz¹dzenie Przechowawcze - Odpowiada.
 Uruchomienie niezalecane}
{116}{}{Proszê Czekaæ...
 Korpus Robota - OK.
 Zbiorniki ¿elu Biomed - Uzupe³niæ.
 Organiczne Urz¹dzenie Przechowawcze - Brak.
 Uruchomienie niezalecane}
{117}{}{Proszê Czekaæ...
 Korpus Robota - OK.
 Zbiorniki ¿elu Biomed - Uzupe³niæ.
 Organiczne Urz¹dzenie Przechowawcze - Odpowiada.
 Uruchomienie niezalecane}
{118}{}{Proszê Czekaæ...
 Korpus Robota - OK.
 Zbiorniki ¿elu Biomed - Uzupe³niæ.
 Organiczne Urz¹dzenie Przechowawcze - Brak.
 Uruchomienie niezalecane}
{119}{}{Proszê Czekaæ...
 Korpus Robota - Wymieniæ Napêd.
 Zbiorniki ¿elu Biomed - Uzupe³niæ.
 Organiczne Urz¹dzenie Przechowawcze - Odpowiada.
 Uruchomienie niezalecane}
{120}{}{Proszê Czekaæ...
 Korpus robota - Wymieniæ Napêd.
 Zbiorniki ¿elu Biomed - Uzupe³niæ.
 Organiczne Urz¹dzenie Przechowawcze - Brak.
 Uruchomienie niezalecane}
{121}{}{}
{122}{}{}
{124}{}{}
{153}{}{Rozpocznij Sekwencjê Startow¹}
{154}{}{Koniec}
{155}{}{Ostrze¿enia zignorowane.
 Jednostka zosta³a uruchomiona}
{156}{}{}
{157}{}{}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{}
{164}{}{Rozpoczynam sekwencjê startow¹}
{165}{}{ Poziomy Zasilania - w normie}
{166}{}{ Wsp. Synchronizacji - 75%}
{167}{}{ Jednostka jest sprawna}
{170}{}{ Wsp. Synchronizacji - 50%}
{174}{}{ Wsp. Synchronizacji - 10%}
{176}{}{Koniec}
{200}{}{ nie mo¿e przeczytaæ tego, co pokazuje monitor.}
{300}{}{Komputer jest najwyraŸniej wyposa¿ony w jakiœ mechanizm obronny.}
{500}{}{Rozpoczynam sekwencjê startow¹...
 Poziomy Zasilania - w normie.
 Przerwano Program.
 Pobieram Dane...
 Kontynuacja Programu.
 Wsp. Synchronizacji - 100%.
 Jednostka jest sprawna}
