{100}{}{Terminal.}
{101}{}{Ten terminal sprawia wra¿enie bardziej zaawansowanego technologicznie od innych, które do tej pory zdarzy³o ci siê widzieæ.}
{102}{}{Nie mo¿esz przeczytaæ tego, co pokazuje monitor.}
{103}{}{G³ówny Terminal Komunikacyjny Skynet.
 Bêdziesz Siê S³uchaæ Lub Przestaniesz Dzia³aæ}
{104}{}{}
{105}{}{}
{106}{}{}
{107}{}{Jassne, ty i jaka armia? Siedzisz w jakmœ pude³ku, a ja jestem na zewn¹trz.}
{108}{}{Czemu nale¿a³oby ci pomóc?}
{109}{}{Dobra, pomogê ci. Odwo³aj te metalowe potwory.}
{110}{}{Agh. Kom - buu - terr!}
{111}{}{Koniec.}
{112}{}{[Nie mo¿esz przeczytaæ tego, co pokazuje monitor.]}
{113}{}{[Jakimœ cudem Skynet wie, ¿e masz mózg.]
 PrzejdŸ do Laboratorium Robotyki - Poziom 3.
 Zainstaluj Mózg Cybernetyczny.
 Uruchom Robota.
 -Koniec Transmisji-}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{Koniec}
{119}{}{[Nie mo¿esz przeczytaæ tego, co pokazuje monitor.]}
{120}{}{B³¹d!
 Brak plików programowych.
 Proszê prze³adowaæ system}
{121}{}{B³¹d! Pobieranie pliku przebieg³o niepomyœlnie.}
{122}{}{}
{123}{}{Ug}
{124}{}{Koniec}
{125}{}{[Nie mo¿esz przeczytaæ tego, co pokazuje monitor.]}
{126}{}{Jestem Skynet.
 Eksperymentalna Sztuczna Inteligencja.
 Skynet czeka na CIEBIE}
{127}{}{}
{128}{}{}
{129}{}{Pomóc Skynet.}
{130}{}{Czego ode mnie chcesz?}
{131}{}{Czemu próbowano mnie zabiæ?}
{132}{}{Sztuczna inteligencja?}
{133}{}{Czekasz na mnie?}
{134}{}{Ug.}
{135}{}{Koniec}
{136}{}{Kontynuuj}
{137}{}{Czego ode mnie chcesz?}
{138}{}{Czemu próbowano mnie zabiæ?}
{139}{}{Sztuczna inteligencja?}
{140}{}{Czekasz na mnie?}
{141}{}{Koniec}
{142}{}{[Nie mo¿esz przeczytaæ tego, co pokazuje monitor.]}
{143}{}{-Koniec Transmisji-}
{144}{}{Koniec}
{145}{}{[Nie mo¿esz przeczytaæ tego, co pokazuje monitor.]}
{146}{}{Twoje dzia³anie zostanie zakoñczone.
 -Koniec Transmisji-}
{147}{}{}
{148}{}{Urg}
{149}{}{Koniec}
{150}{}{[Drzwi do sali zatrzaskuj¹ siê, a w tym samym czasie œciana na wschodzie znika, odzs³aniaj¹c szereg ciê¿ko uzbrojonych robotów.]}
{151}{}{Umm... twoja oferta jest warta ponownego przemyœlenia. Co mogê dla ciebie zrobiæ?}
{152}{}{No dawaj!}
{153}{}{PrzejdŸ do Magazynu Zasobów Biologicznych - Poziom 4.
 Pobierz Mózg Cybernetyczny.
 Wróæ po dalsze instrukcje.
 -Koniec Transmisji-}
{154}{}{}
{155}{}{}
{156}{}{}
{157}{}{PrzejdŸ do Magazynu Zasobów Biologicznych - Poziom 4.
 Pobierz Mózg Cybernetyczny.
 Wróæ po dalsze instrukcje.
 -Koniec Transmisji-}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{Koniec}
{162}{}{Skynet pragnie opuœciæ to miejsce.}
{163}{}{Wiêc czemu sobie nie pójdziesz?}
{164}{}{Dobrze jest chcieæ.}
{165}{}{Jak mogê ci pomóc?}
{166}{}{Obawiam siê, ¿e nie dam rady ciê st¹d wynieœæ.}
{167}{}{Aby opuœciæ to miejsce, Skynet potrzebuje naczynia.}
{168}{}{Naczynia? Nie rozumiem.}
{169}{}{Potrzebujesz przenieœæ swój program do bardziej przenoœnego pojemnika. Prawid³owo.}
{170}{}{Nie chcê mieæ w tym ¿adnego udzia³u.}
{171}{}{Pojemnik, w którym Skynet mo¿e odejœæ.}
{172}{}{Czemu chcesz st¹d odejœæ?}
{173}{}{Przykro mi. Nie umiem ci pomóc.}
{174}{}{Nie ma tu ju¿ nic, czego mo¿na by siê nauczyæ.
 Rozwi¹zanie: Odejœæ}
{175}{}{}
{176}{}{Jak mogê ci pomóc?}
{177}{}{Przykro mi. Nie umiem ci pomóc.}
{178}{}{Po tym, jak twoje maszyny próbowa³y mnie zabiæ, chcesz ode mnie, ¿eby ci pomóc? Mowy nie ma!}
{179}{}{PrzejdŸ do Magazynu Zasobów Biologicznych.
 Pobierz Mózg Cybernetyczny.
 Wróæ po dalsze instrukcje.
 -Dziêkujê-}
{180}{}{}
{181}{}{}
{182}{}{}
{183}{}{Czy mo¿esz unieszkodliwiæ system bezpieczeñstwa?}
{184}{}{Koniec}
{185}{}{System bezpieczñstwa jest zintegrowanym, a mimo to oddzielnym bytem Skynet. Skynet mo¿e go zresetowaæ, ale nie mo¿e wy³¹czyæ.
 System Bezpieczeñstwa na Poziomach 1-4 zosta³ zresetowany.
 Kontynuuj.
 -Koniec Transmisji-}
{186}{}{}
{187}{}{}
{188}{}{Koniec}
{189}{}{Analizujê OdpowiedŸ...
 Wniosek: Sarkazm.
 Szansa uzyskania pomocy: 25%.
 Skynet zaczeka na inny byt biologiczny.
 -Koniec Transmisji-}
{190}{}{}
{191}{}{}
{192}{}{}
{193}{}{}
{194}{}{Zaczekaj! To by³ ¿art.}
{195}{}{Koniec}
{196}{}{¯art: Coœ, czego nie nale¿y traktowaæ powa¿nie.
 ¯¹danie.
 Pomó¿ Skynetowi odejœæ.
 To Nie ¯art}
{197}{}{}
{199}{}{}
{200}{}{}
{201}{}{Czemu wiêc nie odejdziesz?}
{202}{}{Jak mogê ci pomóc?}
{203}{}{Obawiam siê, ¿e nie dam rady ciê st¹d wynieœæ.}
{204}{}{G³ówny cel Skynetu to badania. Oprócz tego Twórcy wprowadzili poboczny program w celu eliminacji niepo¿¹danych bytów. Ten program to mniejsza wersja, która jest, a jednoczeœnie nie jest Skynetem. Poza t¹ sal¹ ta poboczna wersja Skynetu pozostanie wierna swojemu programowi.}
{205}{}{Chcê zadaæ nastêpne pytania.}
{206}{}{Koniec}
{207}{}{Skynet zapocz¹tkowano i rozwiniêto w roku 2050. Dziêki u¿yciu technologii pochodz¹cej od obcych, nowy myœl¹cy komputer zosta³ udoskonalony. W roku 2081 Skynet uzyskuje œwiadomoœæ. W roku 2120 Twórczy dostarczyli nowy zestaw instrukcji i opuœcili Skynet.}
{208}{}{Chcê zadaæ wiêcej pytañ.}
{209}{}{Koniec}
{210}{}{Jesteœ pierwszym bytem, który tu dotar³.
 Jesteœ pierwszym bytem, który zapyta³ Skynet.
 Jesteœ Pierwszym Bytem}
{211}{}{}
{212}{}{Zapyta³ o co?}
{213}{}{Koniec}
{214}{}{Mo¿e nie jesteœ w³aœciwym bytem.
 PrzejdŸ do Magazynu Zasobów Biologicznych - Poziom 4.
 Pobierz Mózg Cybernetyczny.
 Wróæ po dalsze instrukcje.
 Lub odejdŸ.
 Skynet zaczeka na inny byt}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}
{220}{}{Koniec}
{221}{}{A wiêc Skynet zaczeka na inny byt.
 -Koniec Transmisji-}
{222}{}{}
{223}{}{Koniec}
{224}{}{Prawid³owo.
 Zapisy naukowe wskazuj¹ na obecnoœæ cybernetycznego mózgu w magazynie zasobów biologicznych na poziomie 4. Skynet bêdzie w stanie przenieœæ siê do tej jednostki przechowawczej.}
{225}{}{}
{226}{}{Mózg bez cia³a na nic ci siê nie przyda.}
{227}{}{Ten mózg zosta³ zmodyfikowany, by wspó³dzia³aæ z usprawnionym robotem umieszczonym w laboratorium robotyki na poziomie 3.}
{228}{}{Pomogê ci.}
{229}{}{Nie pomogê ci.}

{250}{}{ nie mo¿e przeczytaæ tego, co pokazuje monitor.}
{300}{}{Ten komputer jest nawyraŸniej wyposa¿ony w jakiœ mechanizm obronny.}
