{100}{}{Terminal.}
{101}{}{To chyba jest terminal systemu bezpieczeñstwa.}
{102}{}{Nie mo¿esz przeczytaæ tego, co pokazuje monitor.}
{103}{}{System Bezpieczeñstwa Skynet.
 Dostêp Zabroniony}
{104}{}{}
{105}{}{Koniec}
{106}{}{B³¹d!
 Brak plików programowych.
 Proszê prze³adowaæ system}
{107}{}{}
{108}{}{}
{109}{}{Koniec}


{200}{}{ nie mo¿e przeczytaæ tego, co pokazuje monitor.}
{300}{}{Komputer jest najwyraŸniej wyposa¿ony w jakiœ mechanizm obronny.}
