############################################################
# The following lines are for describing the NPC when
# glanced and and examined.
############################################################
{100}{}{Widzisz typowego udomowionego bramina.}
{101}{}{Krowa + radiacja = dwug³owy mutant. Reszta jest milczeniem.}
{102}{}{Jego widok nie budzi twego zdziwienia.}
{103}{}{Braminy s¹ znane z ma³omównoœci...}
{104}{}{Czy naprawdê nie masz nic lepszego do roboty, ni¿ gadanie z dwug³ow¹ krow¹?!}
{105}{}{Oto bramin. Dwug³owy bramin.}

{201}{}{Muuu...}
{202}{}{Muuu Muuu Muuu...}
{203}{}{Muuuu...}
{204}{}{Muuuuuu...}
{205}{}{Muuuuuuuuuu...}
{206}{}{:: EHEM::}
