{100}{}{Ten samochód nie sprawia wra¿enia dzia³aj¹cego. Mimo to odnosisz wra¿enie, ¿e jest w lepszej kondycji ni¿ reszta samochodów w okolicy. Mo¿e da siê go naprawiæ.}
{101}{}{W tej chwili samochód nie sprawia wra¿enia dzia³aj¹cego, poniewa¿ potrzebny mu jest kontroler baterii zasilaj¹cych.}

{200}{}{Udaje ci siê naprawiæ samochód za pomoc¹ kontrolera baterii zasilaj¹cych.}
{210}{}{Nie udaje ci siê naprawiæ samochodu za pomoc¹ kontrolera baterii zasilaj¹cych.}

{300}{}{Nie udaje ci siê naprawiæ samochodu. Mo¿e da³oby siê go naprawiæ za pomoc¹ tego kontrolera baterii zasilaj¹cych, o którym mówi³ Smitty.}

{400}{}{Otwarcie maski i zajêcie siê samochodem narobi³oby zbyt du¿o ha³asu.}
