# 
# FALLOUT BATTLECRIES
# When the Bomb Drops, the real fun begins - So let's get to Work!!!
#
# Version 1.0  May 13, 1997  Scott Bennie
#         1.1  May 14, 1997  Chris Taylor (edits and line number change)
#         1.2  June 19, 1997 Leonard, Jason, Chris (edits)
#
# Version 2.0 July 29, 1998 Feargus Urquhart - modified for Fallout 2, most text has been rearranged, however some lines were still authored by the above people.
#
#  READ THIS!! READ THIS!! READ THIS!! READ THIS!!
#
#  This new file is different than the old one in that body locations are listed in a generic fashion first and are only listed for particular types of characters.  This is followed by a list of generic characters, which is then followed by the more specific taunts and party member taunts.
#
#
####################################################################################
#
#                    Generic Body Parts
#
####################################################################################
#                     
#                     Notes
#                     
#                     00-09 Hit in Head
#                     10-19 Hit in Left Arm
#                     20-29 Hit in Right Arm
#                     30-59 Hit in Torso (Generic Non-Called Shot Hit)
#                     60-69 Hit in Right Leg
#                     70-79 Hit in Left Leg
#                     80-89 Hit in Eyes
#                     90-99 Hit in Groin
#
#                     1000 Wimpy Person
#                     1100 Normal Person
#                     1200 Tough Person
#                     1300 Berserk Person
#                     1400 Robot
#                     1500 Primitive
#                     1600 Ghoul
#                     1700 Raider (Khan)
#                     1800 Junkie
#
####################################################################################
#
#
############################################
# 1000 Wimpy Person
############################################
#
# target hit in head
#
{1000}{}{Az arcom! Az arcom!}
{1001}{}{Áu! Ez fájt!}
{1002}{}{Uuuú! Kellene egy kis jég a fejemre!}
#
# target hit in left arm
#
{1010}{}{Jaj, a karom!}
{1011}{}{Ááá!}
{1012}{}{Eltörted a karom!}
#
# target hit in right arm
#
{1020}{}{Áu, a karom!}
{1021}{}{Áááááhh!}
{1022}{}{Istenem! A karom!}
#
# target hit in torso
#
{1030}{}{Oh! Ez tényleg fájt!}
{1031}{}{Asszem, mindjárt elájulok.}
{1032}{}{Áuuh!}
{1033}{}{Uuufh!}
{1034}{}{Ez fájt!}
{1035}{}{Hagyjál már békén!}
{1036}{}{Ohhh, fájdalom!}
#
# target hit in right leg
#
{1060}{}{Oh, a lábam!}
{1061}{}{A térdem!}
{1062}{}{Áu!}
#
# target hit in left leg
#
{1070}{}{Au, a lábam!}
{1071}{}{A térdem!}
{1072}{}{Aaaaarrrghhh!}
#
# target hit in eyes
#
{1080}{}{Jaj!! A szemem!}
{1081}{}{Az arcom! A szemem! Aaarrgh!}
{1082}{}{A szemem!}
#
# target hit in groin
#
{1090}{}{Oooooooooh, a lágyékom! Oooooooh...}
{1091}{}{Áááu... ez fááj!}
{1092}{}{Urgh!}
{1093}{}{Oooh! auuuu...}
{1094}{}{Nehm...khapok...levegõt...}
{1095}{}{Fááj, fáááááááj...}
#
############################################
# 1100 Normal Person
############################################
#
# target hit in head
#
{1100}{}{Francba!}
{1101}{}{Fejbe trafáltál!}
{1102}{}{Az arcom! Az arcom!}
#
# target hit in left arm
#
{1110}{}{Aah! A karom!}
{1111}{}{A karom!}
{1112}{}{Hé ember, ez fáj!}
#
# target hit in right arm
#
{1120}{}{Aah! A karom}
{1121}{}{A karom!}
{1122}{}{Bazzeg!}
#
# target hit in torso
#
{1130}{}{}
{1131}{}{Uuuuh!}
{1132}{}{Ááoouuh!}
{1133}{}{Uh! A bordám}
{1134}{}{Ugh! Ez fájt!}
{1135}{}{Szemét! Köpök rád!}
{1136}{}{Argh!}
{1138}{}{Oh, a bordám!}
{1139}{}{Ow!!!}
{1140}{}{Oof!}
#
# target hit in right leg
#
{1160}{}{Auuhhh! A lábam!}
{1161}{}{A lábam!}
{1162}{}{Ennyit a térdemrõl.}
#
# target hit in left leg
#
{1170}{}{Aggghhh! A lábam!}
{1171}{}{A lábam!}
{1172}{}{Ennyit a térdemröl.}
#
# target hit in eyes
#
{1180}{}{Ááááááh! Nem látok!}
{1181}{}{A szemem! A szemem!}
{1182}{}{A szemem! Ezért megfizetsz te görény!}
#
# target hit in groin
#
{1190}{}{Ooooooh, a tököm!}
{1191}{}{Ooooooooooh!}
{1192}{}{Nem...khapok...levegõt...}
{1193}{}{Hoppá! Ennyit a családról!}
{1194}{}{Fááj, fááááááááj...}
{1195}{}{A fenébe, nagyon fáj!}
#
############################################
# 1200 Tough Person
############################################
#
# target hit in head
#
{1200}{}{Ow! Fa..fej!}
{1201}{}{Betört az orrom!}
{1202}{}{Letépem a fejed!}
#
# target hit in left arm
#
{1210}{}{Ow, a karom!}
{1211}{}{Ez volt életed legnagyobb és egyben utolsó hibája!}
{1212}{}{A karom!}
#
# target hit in right arm
#
{1220}{}{Ow, a karom!}
{1221}{}{Ez volt életed legnagyobb és egyben utolsó hibája!}
{1222}{}{A karom!}
#
# target hit in torso
#
{1230}{}{Urp!}
{1231}{}{Oof!}
{1232}{}{Ouch!}
{1233}{}{}
{1234}{}{Ugh! Ez fájt!}
{1235}{}{Ouch!}
{1236}{}{Áááá!}
{1237}{}{Oh, a bordám!!}
{1238}{}{Ow!!! Még jó, hogy két vesém van!}
{1239}{}{Oof!}
#
# target hit in right leg
#
{1260}{}{Ow, a combom!}
{1261}{}{Nem kell láb, hogy megöljelek!}
{1262}{}{Hol a térdem??}
#
# target hit in left leg
#
{1270}{}{Ow, a lábam!}
{1271}{}{Ülve is tudok ölni!}
{1272}{}{A térdem!}
#
# target hit in eyes
#
{1280}{}{Hova tûntél??}
{1281}{}{Ez a harc egyre rosszabb!}
{1282}{}{Ez gyenge lövés volt, pajti!}
#
# target hit in groin
#
{1290}{}{Oooooo, a tököm!}
{1291}{}{Reggelente lesz egy kis gondom!}
{1292}{}{Lemondhatok a gyerekekrõl!}
{1293}{}{Urp!}
{1294}{}{}
{1295}{}{}
#
############################################
# 1300 Berserk Person
############################################
#
# target hit in head
#
{1300}{}{Váó! Ez király heget hagy!}
{1301}{}{Mostmár kezdesz idegesíteni!}
{1302}{}{Merd még egyszer, köcsög!}
#
# target hit in left arm
#
{1310}{}{Én se fogok már szárnyalni!}
{1311}{}{}
{1312}{}{Lehet hogy eltörted a karom, de még mindig el tudom törni a nyakad!}
#
# target hit in right arm
#
{1320}{}{}
{1321}{}{Ez csak egy karcolás, de nekem éppen elég...}
{1322}{}{Eltörted a kezem, ezért kitekerem a nyakad!}
#
# target hit in torso
#
{1330}{}{Egy kis vér senkinek se árt!}
{1331}{}{Oof! Ezért kicsontozlak!}
{1332}{}{Ááu!}
{1333}{}{Imádom a fájdalmat!}
{1334}{}{Imádom a borda reccsenését!}
{1335}{}{Ez semmiség!}
{1336}{}{Arg!}
#
# target hit in right leg
#
{1360}{}{Imádom a csontok ropogását!}
{1361}{}{}
{1362}{}{Eltörted a lábam, de amint utolérlek, kinyírlak!}
#
# target hit in left leg
#
{1370}{}{Imádom a csontok ropogását!}
{1371}{}{}
{1372}{}{Eltörted a lábam! ezért meghalsz!}
#
# target hit in eyes
#
{1380}{}{Héé, megvakultam!}
{1381}{}{Nem látok! Így már van esélyed!}
{1382}{}{A szemem, te fasz!}
#
# target hit in groin
#
{1390}{}{Oof, a tököm!!}
{1391}{}{Ez tökös húzás volt!}
{1392}{}{}
{1393}{}{}
{1394}{}{Hát, ha így akarsz játszani!}
{1395}{}{Ack!}
#
############################################
# 1400 Robot 
############################################
#
# target hit in CPU
#
{1400}{}{Figyelmeztetés, CPU meghibásodást észleltem!}
{1401}{}{Figyelem! CPU sérülés! Irányítás megsérült!}
{1402}{}{Figyelem! CPU megsérült! Létfontosságú áramkörök átirányítása!}
#
# target hit in left manipulator
#
{1410}{}{Robotkar sérülés észlelve!}
{1411}{}{Kárjelentés: bal robotkar megsérült.}
{1412}{}{Robotkar sérült. Javítás folyamatban.}
#
# target hit in right manipulator
#
{1420}{}{Robotkar sérülés észlelve!}
{1421}{}{Kárjelentés: jobb robotkar megsérült.}
{1422}{}{Robotkar sérült. Javítás folyamatban.}
#
# target hit in frame
#
{1430}{}{Gépház eltalálva. Javítás szükséges.}
{1431}{}{Gépház eltalálva. Javító áramkör aktiválva.}
{1432}{}{Gépház támadás alatt.}
{1433}{}{Páncélzat áttörve!}
{1434}{}{Gépház támadás alatt. Javítás.}
{1435}{}{Az egység támadás alatt.}
{1436}{}{Harci üzemmód}
{1437}{}{Brzzt!}
{1438}{}{Könnyû sérülés.}
{1439}{}{Brzzt!}
#
# target hit in right motivator
#
{1460}{}{Robotláb sérülés észlelve!}
{1462}{}{Kárjelentés: jobb robotláb megsérült.}
{1463}{}{Robotláb sérült. Javítás folyamatban.}
#
# target hit in left motivator
#
{1470}{}{Robotláb sérülés észlelve!}
{1471}{}{Kárjelentés: bal robotláb megsérült.}
{1472}{}{Robotláb sérült. Javítás folyamatban.}
#
# target hit in sensors
#
{1480}{}{Szenzor találat! Szenzor találat!}
{1481}{}{Szenzor megsérült! Szenzor megsérült!}
{1482}{}{Szenzor meghibásodott, javítási-kísérlet!}
#
# target hit in regulator
#
{1490}{}{Mozgásközpont sérülés észlelve!}
{1491}{}{Mozgásközpont megsérült! Mozgászavar!}
{1492}{}{Mozgásközpont megsérült! Javítás folyamatban!}
#
#
############################################
# 1500 Primitive
############################################
#
# target hit in head
#
{1500}{}{A fejemet gonosz szellemek szállták meg!} 
{1501}{}{Hallom az õseim hívását!} 
{1502}{}{Erre a sebhelyre büszke leszek!}
{1503}{}{Ouuuuch!}
{1504}{}{Ég a fejem!}
{1505}{}{Éget, éget!}
{1506}{}{Fájdalom.}
{1507}{}{Erõs a varázserõd!}
{1508}{}{Így nem szerzed meg a lelkemet!} 
{1509}{}{A varázslatod nem gyõz felettem!}
#
# target hit in left arm
#
{1510}{}{A jobb kezemmel foglak megölni!} 
{1511}{}{Egy kézzel is elbánok veled!} 
{1512}{}{A te fájdalmad még nagyobb lesz!} 
{1513}{}{Úgyse kell annyi ujj!} 
{1514}{}{Úgyis hosszabb  volt az a kezem!} 
{1515}{}{Ezért mind a két karod kitépem!} 
{1516}{}{Ezért lassan öllek meg téged!} 
{1517}{}{Jájjj!}
{1518}{}{Olyan sok vér...}
{1519}{}{Valami amit megmutathatok a kisembereknek!}
#
# target hit in right arm
#
{1520}{}{A bal kezemmel öllek meg!} 
{1521}{}{Ennyire rosszul célzol?}
{1522}{}{Egy kézzel is elbánok veled!} 
{1523}{}{Úgyse kell annyi ujj!} 
{1524}{}{Ezért lassan öllek meg téged!}
{1525}{}{Ezért mind a két karod kitépem!} 
{1526}{}{Te elveszed a karom, én elveszem a fejed!}
{1527}{}{Meg akarsz nyomorítani?}
{1528}{}{A beledbõl fogok vacsorázni!} 
{1529}{}{Hosszú ideig fogsz haldokolni!}
#
# target hit in torso
#
{1530}{}{Aúúúúú!}
{1531}{}{Ég a testem!}
{1532}{}{Égnek a zsigereim!}
{1533}{}{Az élet-szellemek menekülnek belõlem!} 
{1534}{}{Szétnyíltam!}
{1535}{}{Csak éljek addig amíg megöllek!} 
{1536}{}{Õsök! Jövök már!}
{1537}{}{Sose látom többet a falut!} 
{1538}{}{Büszkén halok meg!} 
{1539}{}{A testvéreim megbosszulnak!} 
{1540}{}{Nincs bennem már lélegzet!} 
{1541}{}{Elvetted a lelkem!}
{1542}{}{Megcsonkítanál?}
{1543}{}{Kibeleztek, mint egy brahmint!} 
{1544}{}{Nem vagyok jól!}
{1545}{}{Nem érzem a lábam!}
{1546}{}{Hirtelen elálmosodtam.} 
{1547}{}{Errrggggg!}
{1548}{}{Eghhh! kucc, kucc.}
{1549}{}{Muszáj folytatni, meg kell ölni ellen...} 
{1550}{}{A sötétség szólít!} 
{1551}{}{A halálom órája közeleg!} 
{1552}{}{A Sámánnak igaza volt, nem térek már vissza!} 
{1553}{}{Az Idegen legyõzött!} 
{1554}{}{Megöltek!}
{1555}{}{A beleim meglazultak!} 
{1556}{}{Ne hagyd, hogy a halál szégyent hozzon rám!} 
{1557}{}{Francba a beleimmel.} 
{1558}{}{Hé, nézd csak, látom az ebédem.} 
{1559}{}{Hova tûnt a levegõ?}
#
# target hit in right leg
#
{1560}{}{Odakúszom és megöllek!}
{1561}{}{Muszáj állni, muszáj...} 
{1562}{}{Remélem, futás nélkül is elkaplak!}
{1563}{}{Megcsonkítasz! Gyáva!} 
{1564}{}{Aúúúúú!}
{1565}{}{Csont? Olyan fehér....}
{1566}{}{Mért nem tudok járni?}
{1567}{}{Arrrrrrgh.}
{1568}{}{Unnhhh.}
{1569}{}{Lábam, mint a tûz!}
#
# target hit in left leg
#
{1570}{}{Odakúszom és megöllek!}
{1571}{}{Állva kell maradnom!} 
{1572}{}{Remélem, futás nélkül is elkaplak!} 
{1573}{}{Megcsonkítasz! Gonosz!} 
{1574}{}{Aúúúúúú!}
{1575}{}{Csont? Olyan fehér....}
{1576}{}{Nem tudok járni. Oh a fájdalom....} 
{1577}{}{Ezért leégetem a lábad!} 
{1578}{}{Áuuuuú-áááá!}
{1579}{}{Lábam mint a tûz!}
#
# target hit in eyes
#
{1580}{}{A sötétség eljött.}
{1581}{}{Hol vagy?}
{1582}{}{Segítség, segíts.}
{1583}{}{Még mindig hallak!}
{1584}{}{Megpróbálsz megvakítani? Te gyáva!} 
{1585}{}{Ellopták a látásom!}
{1586}{}{A szemeimet elveheted, de a bátorságom nem!} 
{1587}{}{Gyere ide, hogy megölhesselek!} 
{1588}{}{Sötétség!Sötétség! Ájjj!} 
{1589}{}{Hol a szemem? Hova tûnt!?!}
#
# target hit in groin
#
{1590}{}{így is van elég leszármazott!} 
{1591}{}{Büszkeség nélkül harcolsz.}
{1592}{}{Úgyse használom, házas vagyok.} 
{1593}{}{Szent szellemek, a világ felrobbant.} 
{1594}{}{Hhh...nem kapok levegõt....}
{1595}{}{Magas hangon: Ouch!} 
{1596}{}{Unnhhh. Le kell ülnöm.} 
{1597}{}{Te szemét--Ezért lassú halálod lesz.} 
{1598}{}{Semmit sem tudsz a becsületrõl.}
{1599}{}{Ezért lemészárollak, mint egy állatot!}
#
#
############################################
# 1600 Ghoul
############################################ 
#
# target hit in head
#
{1600}{}{Oh, ennyit a jóképûségemrõl}
{1601}{}{Fájnak az agyaim.}
{1602}{}{Na, mostmár úgy nézek ki, mint Van Gogh.}
{1603}{}{Picsába, ott az orrom!}
{1604}{}{Hé! Ez volt az utolsó fogam!} 
{1605}{}{Megskalpoltak!}
{1606}{}{Ennél még az üveg is jobb...} 
{1607}{}{Hadd adjak egy kis darabot a fejembõl!} 
{1608}{}{Ez a jó szemem, Arrr.} 
{1609}{}{Ettõl még a jó szemem is sír!}
#
# target hit in left arm
#
{1610}{}{Lekezelsz?!}
{1611}{}{Ooohh, a fájdalom, a fájdalom.}
{1612}{}{Még mindig maradt pár ujjam.} 
{1613}{}{Csak egy ujj kell hozzád, haver.} 
{1614}{}{Kell egy segítõ kéz?} 
{1615}{}{Hát ez szarabb érzés, mint a hosszúra nõtt köröm.} 
{1616}{}{Mostmár legalább nincs útban.} 
{1617}{}{Leszúrlak a csonkkal!} 
{1618}{}{Hé, hova tûntek az ujjaim?} 
{1619}{}{Mostmár legalább hasznát venném egy kampókéznek!} 
#
# target hit in right arm
#
{1620}{}{A jobb kezemet kellett volna védenem.} 
{1621}{}{Eltörted a karom!}
{1622}{}{Ezt még megbánod!}
{1623}{}{Héjkás! Megöjnek!}
{1624}{}{Na, lemondhatok Wimbledon-ról.}
{1625}{}{Dobo..ja, mindegy.}
{1626}{}{Lekezelsz?}
{1627}{}{Téged egy ujjal is lenyomlak, pubi!} 
{1628}{}{Hát, akkor, asszem szétrugom a fejed.} 
{1629}{}{Ennyit a flitteres kesztyûmrõl!} 
#
# target hit in torso
#
{1630}{}{Az az én májam! Add vissza!} 
{1631}{}{Csak egy kicsit jobbra, ááhh, mingyárt jobb.} 
{1632}{}{Ufff!}
{1633}{}{Minek van ilyen penészes szaga? Ja, ezek csak a belsõségeim.} 
{1634}{}{Most, hogy így felbontottál, mint egy konzervet, egész karcsú lettem! Köszi!} 
{1635}{}{./~ Elvesztettem a szívem.../~}
{1636}{}{Ez megcsikizte pár bordámat.}
{1633}{}{Kinek kell egyáltalán vakbél!} 
{1634}{}{Csak egy kicsit a szélébõl, doki.} 
{1635}{}{Arrggghh, a gerincem!}
{1636}{}{A lábam! Nem érzem a lábam!} 
{1637}{}{Ez egy bél-lövés, Uram!}
{1638}{}{Csak a puhányoknak kell tüdõ!}
{1639}{}{Nézdmár! Van bordám!}
#
# target hit in right leg
#
{1660}{}{Aú, a lábam.}
{1661}{}{Ezért kinyírlak!}
{1662}{}{Argh! Eltöröd a lábam, eltöröm a nyakad!} 
{1663}{}{Francba, én se fogok többet tangózni.}
{1664}{}{Picsába, mintha kevesebb lábujjam lenne, mint az elõbb.}
{1665}{}{Nem ártana egy mûláb!}
{1666}{}{Megsérült a kék szarvasbõr csizmám!} 
{1667}{}{Szétbarmoltad a bokám!}
{1668}{}{Épp most borotváltam.} 
{1669}{}{Leharapom a térdkalácsod!} 
#
# target hit in left leg
#
{1670}{}{A lábam!}
{1671}{}{Átlõtted a Gucci-mat!}
{1672}{}{Ouch! Hé! Ez öv alatt volt!} 
{1673}{}{Olyan szép heg lesz utána, mint senki másnak...} 
{1674}{}{Fenekelj el Mami, csintalan voltam.} 
{1675}{}{Szépen fog hegedni!}
{1676}{}{Ez mind az én vérem?}
{1677}{}{Marshall Dillon, Marshall Dillon!} 
{1678}{}{Ez szép hólyagos lesz.}
{1679}{}{Ájj, jájj, jeee, ájj, aj!}
#
# target hit in eyes
#
{1680}{}{Francos vér ment a szememben!}
{1681}{}{A szemem! Ezért megfizetsz!} 
{1682}{}{Köcsög!}
{1683}{}{Ki kapcsolta le a villanyt?} 
{1684}{}{Háhá, ez az üvegszemem volt!} 
{1685}{}{Szétnyomódik, mint az érett szõlõ, nincs igazam?}
{1686}{}{Szemmel tartalak, ömm, vissza tudnád adni?} 
{1687}{}{Hang alapján is meg tudom állapítani, hogy hol vagy!}
{1688}{}{Ájjj! Áúú! A szemem!}
{1689}{}{Megvakítasz, mer félsz, há nem?} 
#
# target hit in groin
#
{1690}{}{Hát nem lovagias?}
{1691}{}{Yooooouuuuch!} 
{1692}{}{Unnhhhhh!}
{1693}{}{Talán ha nem mozdulok...} 
{1694}{}{Na, ennyit a kolbászomról!}
{1695}{}{Ennyit a szociális életemrõl.} 
{1693}{}{Asszem, le kell ülnöm egy kicsit.}
{1694}{}{Tyü!Ha lennének lány-ghoulok akkor mérges lennék rád.} 
{1695}{}{Oohh, ez fájt.}
{1696}{}{Eltaláltál? Ja, igen, az fáj.} 
{1697}{}{Nézd már! Rántotta lett a tojásomból!} 
{1698}{}{Tört mogyorót valaki?}
{1699}{}{Na, én se írom többet a nevem a hóba.}
#
############################################
# 1700 Raider (Khan)
############################################
#
# target hit in head
#
{1700}{}{Ne a kibaszott fejem, te...}
{1701}{}{Minden...elkezdett...forogni...}
{1702}{}{Ugnnn!}
{1703}{}{Az arcom ne! Az arcom ne!}
#
# target hit in left arm
#
{1710}{}{Egy kézzel is lenyomlak!}
{1711}{}{Felcser! Szétbaszták a karom!}
{1712}{}{Áh! Még jó, hogy kétke...mindegy.}
#
# target hit in right arm
#
{1720}{}{Eltört a kezem! Így már van esélyed!}
{1721}{}{Felcser! Szétbaszták a kezem!}
{1722}{}{Többre lesz szükséged, ahhoz, hogy megmentsd a bõröd.}
#
# target hit in torso
#
{1730}{}{Ahhg! Zsiger-lövés!}
{1731}{}{Hnrgggg! Le..ve..gõt!}
{1732}{}{A bordáim! Hamarosan kitépem a tieid! Csak így becsületes!}
{1733}{}{Ezért..meg..fi..zetsz..!}
{1734}{}{*Ooooof* Istenem, utálom ezt...}
{1735}{}{Nggg! Ez talált, básszeg!}
#
# target hit in right leg
#
{1760}{}{Picsába! A lábam!}
{1761}{}{Nem kell két láb ahhoz, hogy szétrúgjam a segged.}
{1762}{}{Kéne egy stimpakk a lábamnak...}
{1763}{}{Urggg...láb...szétcseszve...}
#
# target hit in left leg
#
{1770}{}{Köcsögit! A lábam!}
{1771}{}{*Ergg* Ezután biztos sántítani fogok...}
{1772}{}{Kéne egy stimpakk a lábamnak...}
{1773}{}{Urggg...láb...szétbaszva...}
#
# target hit in eyes
#
{1780}{}{Francba! Ne a szemembe!}
{1781}{}{Megpróbálod lebénítani a kifinomult érzékelésem, mi?}
{1782}{}{Nem...látok...vér...a...szemben...}
{1783}{}{Nem kell, hogy lássalak, a szaglásom még mindig mûködik.}
#
# target hit in groin
#
{1790}{}{Mit gondolsz, hogy mi ez? Valami szar kis akció film?}
{1791}{}{A tököm!!! Gyere csak ide, megtudod, hogy milyen érzés!}
{1792}{}{Hát, ennyit arról, hogy tökös legény vagyok.}
{1793}{}{Elnézést kérek, amíg végigokádom magam...}
{1794}{}{Fasza. Ezentúl tök-fixációval kell harcolnom.}
{1795}{}{Hadd feküdjek le egy kicsit, utána megöllek.}
{1796}{}{Bolond! Na, mindegy, nekem se lesz már kölyköm.}
#
############################################
# 1800 Junkie
############################################
#
# target hit in head
#
{1800}{}{Hoppá. Valami pofán trafált.}
{1801}{}{Ez meg mi volt?}
{1802}{}{Ngggg}
{1803}{}{Még jó, hogy rákattantam a Jetre, különben ez fájt volna.}
{1804}{}{Aúúú! Valaki hozzon egy Stimpakkot! Vagy Jetet!}
#
# target hit in left arm
#
{1810}{}{Hé! Valaki a karomba lõtt!}
{1811}{}{Figyu, a kezem a tûknek van! Ne lõdd má széjjel!}
{1812}{}{Nggggg}
{1813}{}{Aúúúú! Valaki hozzon egy Stimpakkot! Vagy Jetet!}
#
# target hit in right arm
#
{1820}{}{Héj! Valaki a karomba lõtt!}
{1821}{}{Figyu, a kezem a tûknek van! Ne lõdd má széjjel!}
{1822}{}{Nggggg}
{1823}{}{Aúúúú! Valaki hozzon egy Stimpakkot! Vagy Jetet!}
#
# target hit in torso
#
{1830}{}{A gyomrom!}
{1831}{}{Áuu! Aúúúú, az a hülye mellkasom! Áuú!}
{1832}{}{Hé! Mi a faszér lõttél belém? Faszfej!}
{1833}{}{Ne lõjjél már belém!}
{1834}{}{Váo. A mellkasom. Eltaláltad. Király.}
{1835}{}{Nrgggg}
{1836}{}{*hfff*}
{1837}{}{Aúúúú! Valaki hozzon egy Stimpakkot! Vagy Jetet!}
#
# target hit in right leg
#
{1860}{}{Hé! Valaki épp most lõtt a lábamba!}
{1861}{}{Hé! Én ezen a lábon járok!}
{1862}{}{Aúúúú! Valaki hozzon egy Stimpakkot! Vagy Jetet!}
#
# target hit in left leg
#
{1870}{}{Hé! Valaki eltrafálta a lábam!}
{1871}{}{Hé! Én használom azt a lábat!}
{1872}{}{Aúúú! Valaki hozzon egy Stimpakkot! Vagy Jetet!!}
#
# target hit in eyes
#
{1880}{}{EZ nem olyan volt, mint egy tû a szemembe...}
{1881}{}{Hé! Én azzal a szemmel nézek!}
{1882}{}{A szemem! A szemem! Fáj a szemem!}
#
# target hit in groin
#
{1890}{}{Annyira rákattantam a Jetre, hogy ezt már meg se éreztem. Vagy mégis? }
{1891}{}{*Hurhkkkk*}
{1892}{}{Lécci rúgjál még tökön!}
{1893}{}{Nghhhhh!}
{1894}{}{Ne a tököm, ne a tököm!}
{1895}{}{A TÖKÖM! A TÖKÖM! Szegény tököm!}
{1896}{}{Elnézést kérek, amíg körbeokádom itt a placcot.}
{1897}{}{Ez...NAGYON...fájt.}
{1898}{}{Remélem, a tököm a nemiszervek mennyországába jut!}
#
####################################################################################
#
#                    Generic People
#
####################################################################################
#                     
#                     Notes
#                     
#                     00-19 Running Away
#                     20-39 Moving in to Attack
#                     40-59 Attacking
#                     60-79 Target being Missed.
#
#                     2000 Wimpy Person
#                     2100 Normal Person
#                     2200 Tough Person
#                     2300 Berserk Person
#                     2400 Guard (Normal)
#                     2500 Guard (Tough)
#                     2600 Primitive
#                     2700 Soldier
#                     2800 Leader
#                     2900 Raider (Khan)
#                     3000 Robot
#                     3100 Ghoul
#                     3200 Junkie
#
####################################################################################
#
#
############################################
# 2000 Wimpy Person
############################################
#
#  running away
#
{2000}{}{Kegyelem!}
{2001}{}{Valaki segítsen!}
{2002}{}{Kérlek ne!}
{2003}{}{Segítség!!}
{2004}{}{Áááááá!}
{2005}{}{Kegyelmezz!}
#
# moving in to attack
#
{2020}{}{Hmm, ömm, állj!}
{2021}{}{Nem szeretjük a te fajtádat errefelé...}
{2022}{}{Reméltem, hogy erre nem kerül sor...}
{2023}{}{Úgy tûnik meg kell védenem magam}
{2024}{}{Úgy tûnik meg kell védenem magam}
{2025}{}{Reméltem, hogy erre nem kerül sor...}
#
# attacking
#
{2040}{}{Nesze!}
{2041}{}{Nem kellett volna elkezdened!}
{2042}{}{Te kérted!}
{2043}{}{És ez hogy tetszik?}
{2044}{}{}
{2045}{}{Te szemét!}
{2046}{}{Nem akarom ezt tenni!}
{2047}{}{}
{2048}{}{Nem akartam ezt a harcot, de...}
{2049}{}{Te fattyú!}
#
# target being missed
#
{2060}{}{}
{2061}{}{Mellé!}
{2062}{}{Váó, ez fájhatott volna!}
{2063}{}{Huhh! Még mindig élek!}
{2064}{}{Hé! Ez fájhatott volna!}
{2065}{}{Huh! Még élek!}
#
############################################
# 2100 Normal Person
############################################
#
#  running away
#
{2100}{}{Legyél szíves, és támadj meg valaki mást!}
{2101}{}{Kegyelmezz!}
{2102}{}{Valaki segítsen!}
{2103}{}{Kérlek hagyd abba!}
{2104}{}{}
{2105}{}{Ezért nem akarok meghalni!}
#
# moving in to attack
#
{2120}{}{Csak várj amíg elkaplak...}
{2121}{}{}
{2122}{}{Hé te!}
{2123}{}{Itt nem látunk szívesen}
{2124}{}{Senki nem veszi át ezt a területet...}
{2125}{}{Mégis mit gondolsz, ki vagy?}
#
# attacking
#
{2140}{}{Ezt nem kellett volna csinálnod}
{2141}{}{Gondoskodunk magunkról}
{2142}{}{Ez az amit a férgekkel mûvelünk!}
{2143}{}{Te mutáns szörny!}
{2144}{}{Te szemét!}
{2145}{}{Megetetlek a kutyáimmal!}
{2146}{}{Ez majd móresre tanít!}
{2147}{}{Rendben. Te kérted.}
{2148}{}{Te állat!}
{2149}{}{Megérdemled ami feléd közeleg!}
#
# target being missed
#
{2160}{}{Nem is vagyok olyan rossz, mi?}
{2161}{}{Láttam már nálad értelmesebb Brahmint is}
{2162}{}{Huh!}
{2163}{}{Nem vagyok gyerekjáték}
{2164}{}{Hála Istennek}
{2165}{}{Mellé!}
#
############################################
# 2200 Tough Person
############################################
#
#  running away
#
{2200}{}{Ez nem éri meg!}
{2201}{}{Van jobb dolgom is!}
{2202}{}{Valaki segítsen!}
{2203}{}{Jobb voltál...most az egyszer}
{2204}{}{Meg fogod kapni ami közeleg feléd!}
{2205}{}{Ezér nem halok meg!}
#
# moving in to attack
#
{2220}{}{Túl késõ elfutni}
{2221}{}{Ki engedett be ide?}
{2222}{}{Hé te!}
{2223}{}{Nem szeretjük a te fajtádat errefelé!}
{2224}{}{Senki nem veszi át ezt a területet...}
{2225}{}{Mit gondolsz, hogy ki a franc vagy?}
#
# attacking
#
{2240}{}{Ezt kapd be!}
{2241}{}{És ez, hogy tetszik?}
{2242}{}{Ezt csináljuk a férgekkel is!}
{2243}{}{Ez a tied, tessék!}
{2244}{}{Viszlát!}
{2245}{}{Bunyóra fel!}
{2246}{}{Bajkeverõ szemét!}
{2247}{}{Szétverlek, te nyomorult féreg...}
{2248}{}{Te állat!}
{2249}{}{Meg fogod bánni, hogy betetted ide a lábad!}
#
# target being missed
#
{2260}{}{Nem vagy olyan jó, mint amire számítottam}
{2261}{}{Szánalmas}
{2262}{}{Csak egy tipikus gengszter vagy!}
{2263}{}{Semmi különleges nincs benned}
{2264}{}{Nem leszek az áldozatod.}
{2265}{}{Ez volt az utolsó baklövésed.}
#
############################################
# 2300 Berserk Person
############################################
#
#  running away
#
{2300}{}{Most jobb, ha lelépek!}
{2301}{}{Visszatérek!}
{2302}{}{Késõbb punk!}
{2303}{}{Jót mulattam, de mostmár lelépek!}
{2304}{}{Ezért megfizetsz - de csak késõbb!}
{2305}{}{Ezt hamarosan újra megpróbálhatjuk!}
#
# moving in to attack
#
{2320}{}{Visszaszögelem a füleid!}
{2321}{}{Friss hús!}
{2322}{}{Ez ma az én napom!}
{2323}{}{A rabszolgám leszel!}
{2324}{}{Visszaszögelem a füleid!}
{2325}{}{Lenyugtatom a segged!}
#
# attacking
#
{2340}{}{Elkaplak!}
{2341}{}{Ideje játszani!}
{2342}{}{Kérlek ne könyörögj. A halálnak méltóságteljesnek kell lennie.}
{2343}{}{Remélem, nem adod fel egykönnyen!}
{2344}{}{Van utolsó kívánságod?}
{2345}{}{Ezt kapd ki!}
{2346}{}{Halál! Halál! Halál! Halál! Halál!}
{2347}{}{Dögölj meg!}
{2348}{}{Na, nézzünk a dolgok belsejébe...}
{2349}{}{Kutyakaja vagy, haver.}
#
# target being missed
#
{2360}{}{Még csak a szele sem ért el.}
{2361}{}{Szarrá unom magam...}
{2362}{}{Gyerünk punk, harcot akarok!}
{2363}{}{Ez a legjobb amit tudsz?}
{2364}{}{Béna vagy!}
{2365}{}{Ez könnyebb lesz, mint gondoltam}
#
############################################
# 2400 Guard (Normal)
############################################
#
#  running away
#
{2400}{}{Én lelépek!}
{2401}{}{Ez nem volt valami jó ötlet}
{2402}{}{Valaki mást bánts, oké?}
{2403}{}{Futás!}
{2404}{}{Nem fogok itt meghalni!}
{2405}{}{Ez túl sok nekem}
#
# moving in to attack
#
{2420}{}{Hé te!}
{2421}{}{Megtanítalak veszíteni}
{2422}{}{Nem kedveljük a te fajtádat errefelé!}
{2423}{}{Ideje, hogy tanulj egy kis tiszteletet!}
{2424}{}{Ideje pénzt keresni...}
{2425}{}{Csak várd meg amíg odaérek...}
{2426}{}{Ezt most minek kell?}
{2427}{}{Mindig akad egy hülye aki felbassza az agyamat!}
#
# attacking
#
{2440}{}{Nesze!}
{2441}{}{Ez tetszik, mi?}
{2442}{}{Békén kellett volna hagynod}
{2443}{}{Ez hogy tetszik?}
{2444}{}{Na, most hol van anyuci?}
{2445}{}{Nesze neked!}
{2446}{}{Nézzük milyen kemény vagy...}
{2447}{}{Punk}
{2448}{}{Söpredék!}
{2449}{}{Elteszlek láb alól}
#
# target being missed
#
{2460}{}{Ezt anyucitól tanultad?}
{2461}{}{Balfasz!}
{2462}{}{Nem vagy elég jó}
{2463}{}{Ez volt az utolsó melléfogásod}
{2464}{}{Amatõr}
{2465}{}{Bárokban tanultál verekedni?}
#
############################################
# 2500 Guard (Tough)
############################################
#
#  running away
#
{2500}{}{Elhúzom a belem!}
{2501}{}{Visszatérek...}
{2502}{}{Ma nem ölsz meg!}
{2503}{}{Késõbb punk!}
{2504}{}{Nem utoljára láttál!}
{2505}{}{Ezért megfizetsz -- csak nem most!}
#
# moving in to attack
#
{2520}{}{A múlté vagy!}
{2521}{}{Friss hús...}
{2522}{}{Táncolni fogok a sírodon}
{2523}{}{Figyelem! Céllövölde!}
{2524}{}{Kész vagy, picinyem?!}
{2525}{}{Ezt élvezni fogom...}
#
# attacking
#
{2540}{}{Ezt kapd be!!!}
{2541}{}{Ne is álmodozz kegyelemrõl...}
{2542}{}{Ez a rész a kedvencem...}
{2543}{}{Kell még?! Huh?!}
{2544}{}{Kutyakaja lesz belõled}
{2545}{}{Nem kellett volna belekezdened abba, amit nem tud befejezni}
{2546}{}{Remélem, nem adod fel túl hamar}
{2547}{}{Csak az egyikünk megy el innen}
{2548}{}{Halj meg!}
{2549}{}{Ilyen punkokat eszek meg reggelire}
{2550}{}{Az iguanám fog felfalni}
{2551}{}{A mosolygó arcomat fogod utoljára látni}
{2552}{}{Ezért imádom ezt a munkát}
#
# target being missed
#
{2560}{}{Ez egy vicc}
{2561}{}{ez a legtöbb amit kihozol magadból?}
{2562}{}{Így túl egyszerû}
{2563}{}{Ez nevetséges...}
{2564}{}{Túl lassú!}
{2565}{}{Lúzer!}
#
############################################
# 2600 Primitive
############################################
#
#  running away
#
{2600}{}{ Fussatok a Gonosztól!}
{2601}{}{A szellemek azt ajánlják, hogy fussak el!}
{2602}{}{Az ellenségünknek erõs a varázsereje--Futás! Valaki hívja a Sámánt!}
{2603}{}{Erõs a Sötét-szellem. A halál köztünk jár!}
{2604}{}{A Sötét-szellem itt van!}
{2605}{}{A Sötét-szellem megbüntet minket. Meneküljetek! A lelkem menekül, és nekem követnem kell!}
{2606}{}{ Ájjjj!!}
#
# moving in to attack
#
{2620}{}{Õsök, segítsétek a harcos kezem!}
{2621}{}{Az erõd az enyém lesz.}
{2622}{}{Nagy lesz a dicsõség.}
{2623}{}{Szégyent hozok a törzsedre.}
{2624}{}{Ajjáh! Nabataluk!}
{2625}{}{Szellemek legyetek velem!}
{2626}{}{Gyere, hadd táncoljanak a pengéim.}
{2627}{}{Kezdõdjön a harc!}
{2628}{}{U-Suthoooo!}
{2629}{}{A Szellemek velem vannak!}
#
# attacking
#
{2640}{}{Az õseid elhagytak téged.}
{2641}{}{A legyõzésed nagy tiszteletet hoz nekem. A varázserõm legyõzhetetlen!}
{2642}{}{Add fel most, és nem esszük meg a szíved.}
{2643}{}{Bátran harcolsz--Megeszem a bátorságod. A Sámánok énekelni fognak gyõzelmemrõl.}
{2644}{}{A véredben fogok fürdeni!}
{2645}{}{Nem félek tõled!}
{2646}{}{Békét hozok neked, elveszett-lélek.}
{2647}{}{Dicsõség a harcbam örökké tartó életet hoz! Tisztellek, különös-lélek.}
{2648}{}{A homály neked int.}
{2649}{}{Az õseim a lelkedre szomjúhoznak.}
{2650}{}{A pengéim szomjaznak a véredre. }
{2651}{}{Igyunk a harc poharából!}
#
# target being missed
#
{2660}{}{A gyûlölet elhomályosítja a látásod.}
{2661}{}{A szellemek elhagytak téged.}
{2662}{}{A varázserõm mûködik!}
{2663}{}{Legyõzhetetlen vagyok!}
{2664}{}{Az élet-erõd gyengül!}
{2665}{}{"A félelem az elme gyilkosa" }
{2666}{}{A harci-énekem használ!}
{2667}{}{A gyerekeim jobban harcolnak!}
{2668}{}{Túl sokáig ismerted a békét.}
{2669}{}{Mindenki ilyen gyenge a törzsedben?}
#
############################################
# 2700 Soldier
############################################
#
#  running away
#
{2700}{}{Erõsítést!}
{2701}{}{Tõlem akár hadbíróság elé is állíthatnak...}
{2702}{}{Felcser!}
{2703}{}{Visszavonulás! Visszavonulás!}
{2704}{}{Meneküljetek! Meneküljetek!}
{2705}{}{A harcot megnyerted...}
#
# moving in to attack
#
{2720}{}{Essünk túl rajta!}
{2721}{}{Yahoo!}
{2722}{}{Ideje tanulnod némi modort}
{2723}{}{A múlté vagy!}
{2724}{}{Támadás!}
{2725}{}{Temessük el ezt a lúzert!}
{2726}{}{Tölts és tüzelj!}
{2727}{}{Isten fog dönteni arról, hogy mi marad belõled}
#
# attacking
#
{2740}{}{Nesze!}
{2741}{}{Most megvagy!}
{2742}{}{Most meghalsz!}
{2743}{}{Ez hogy tetszik?}
{2744}{}{Ez nekem nem csak munka}
{2745}{}{Nem kellett volna belekezdened abba, amit nem tudsz befejezni}
{2746}{}{Jobb lesz ha elkezdesz imádkozni!}
{2747}{}{Nem fogsz reggel hatig kitartani!}
{2748}{}{Jól vagy?}
{2749}{}{A pokolban találkozunk}
#
# target being missed
#
{2760}{}{Nem most kéne gyakorolnod}
{2761}{}{Ez a legtöbb amit tudsz?}
{2762}{}{Gyerünk lúzer, harcolni akarok!}
{2763}{}{Legközelebb célozni is kéne}
{2764}{}{Hülye civil...}
{2765}{}{Legközelebb hagyd a profikra}
#
############################################
# 2800 Leader
############################################
#
#  running away
#
{2800}{}{}
{2801}{}{}
{2802}{}{}
{2803}{}{}
{2804}{}{}
{2805}{}{}
#
# moving in to attack
#
{2820}{}{}
{2821}{}{}
{2822}{}{}
{2823}{}{}
{2824}{}{}
{2825}{}{}
{2826}{}{}
{2828}{}{}
#
# attacking
#
{2840}{}{}
{2841}{}{}
{2842}{}{}
{2843}{}{}
{2844}{}{}
{2845}{}{}
{2846}{}{}
{2847}{}{}
{2848}{}{}
{2849}{}{}
#
# target being missed
#
{2860}{}{}
{2861}{}{}
{2862}{}{}
{2863}{}{}
{2864}{}{}
{2865}{}{}
#
############################################
# 2900 Raider
############################################
#
#  running away
#
{2900}{}{Meneküljetek! Meneküljetek!}
{2901}{}{Visszavonulás!}
{2902}{}{Újracsoportosulás!}
{2903}{}{Fussatok!}
{2904}{}{visszavonulás!}
{2905}{}{Aaaaghhh!}
#
# moving in to attack
#
{2920}{}{Öljétek meg ezt a bolondot!}
{2921}{}{Friss hús...}
{2922}{}{Fosztogatás!}
{2923}{}{Ö az enyém!}
{2924}{}{Ahhhhhhh!}
{2925}{}{Támadás!}
#
# attacking
#
{2940}{}{Élvezd ki az életed utolsó pillanatait.}
{2941}{}{Vér! Vér! Vér!}
{2942}{}{A szíved az enyém!}
{2943}{}{RAAAAAAARRRR!!}
{2944}{}{A fegyvereid a trófeáim lesznek!}
{2945}{}{Halál!}
{2946}{}{Én foglak megölni!}
{2947}{}{A csontjaid a sivatagban fognak kifehéredni!}
{2948}{}{Vér és Sötétség!}
{2949}{}{YAAAAAAAAAAAAH!}
{2950}{}{Belezzétek ki a nyeszlett férget!}
#
# target being missed
#
{2960}{}{Elvesztegetett erõfeszítés!}
{2961}{}{Vesztettél!}
{2962}{}{A vérem erõsebb, mint a tied!}
{2963}{}{ÉLEK!!}
{2964}{}{A tested gyenge és szánalmas!}
#
############################################
# 3000 Robot
############################################
#
#  running away
#
{3000}{}{Programindítás: Visszavonulás}
{3001}{}{Javasolt program: visszavonulás}
{3002}{}{Harci teljesítmény elégtelen. Visszavonulás javasolt.}
{3003}{}{Taktikai analízis kész: visszavonulás javasolt.}
{3004}{}{Programindítás: Menekülés}
{3005}{}{Visszavonulás javasolt. Elindítva.}
#
# moving in to attack
#
{3020}{}{Célpont bemérve!}
{3021}{}{Megsemmisítés! Megsemmisítés!}
{3022}{}{Az emberszabású nem menekülhet}
{3023}{}{Megsemmisíteni a behatolót}
{3024}{}{Harci üzemmód aktiválva}
{3025}{}{Harci program elindítva}
#
# attacking
#
{3040}{}{Harci program megkezdése}
{3041}{}{Célpont támadása}
{3042}{}{Támadó program indítása}
{3043}{}{Elpusztítani a behatolót!}
{3044}{}{Taktikai analízis kész: támadás indul.}
{3045}{}{Támadás megkezdve}
{3046}{}{Az célpont megsemmisítése folyamatban}
{3047}{}{Ellenség megsemmisítése folyamatban}
{3048}{}{Célpont elpusztítása!}
{3049}{}{Támadó program elindítva}
#
# target being missed
#
{3060}{}{Analízis. Védekez program sikeres.}
{3061}{}{Analízis. Ellenséges aktivitás elhanyagolható.}
{3062}{}{Célpont támadása sikertelen. Válaszlépés számítása...}
{3063}{}{Az egység sértetlen}
{3064}{}{Célpont veszélyességének újraértékelése folyamatban}
{3065}{}{Analízis. A célpont hibázott. Az egység sértetlen.}
#
############################################ 
# 3100 Ghoul
############################################ 
#
#  running away
#
{3100}{}{El kell tûnnöm innen!}
{3101}{}{Visszatérek...}
{3102}{}{Ma sem fogsz megölni!} 
{3103}{}{Késõbb, simabõrû!}
{3104}{}{Nem utoljára hallottál rólam!} 
{3105}{}{Ezért megfizetsz -- csak nem most!} 
{3106}{}{Nem akarok másodszorra is meghalni.}
{3107}{}{Lábak, most ne hagyjatok cserben!}
{3108}{}{Csinálok egy hátra-arcot!} 
{3109}{}{Öö, itt az idõ egy taktikai visszavonuláshoz.} 
{3110}{}{Függöny, balra el.}
{3111}{}{Ööö, késõbb van, mint gondoltam.} 
{3112}{}{Mennem kell. Csáo.}
{3113}{}{Futáááás!}
{3114}{}{Mennem kell, vissza kell raknom pár részemet} 
{3115}{}{Nem bírják már ezek az öreg csontok.} 
{3116}{}{Nem az évek, hanem a mérföldek száma jelent gondot.} 
{3117}{}{Micsoda világ, micsoda világ....}
{3118}{}{Vége a leckének mára, én leléptem!} 
{3119}{}{Hé, ne hátrálj!}
#
# moving in to attack
#
{3120}{}{A múlté vagy!}
{3121}{}{Friss hús...}
{3122}{}{Kolbi, kolbi, kolbi!} 
{3123}{}{Ide az agyadat...}
{3124}{}{Ki fogom fosztani a sírod...} 
{3125}{}{Remélem, a fejed nem sérül meg...} 
{3126}{}{Még több agyat nekem...}
{3127}{}{Még több zsarut!}
{3128}{}{Még több orvost!}
{3129}{}{Jól jönne pár új testrész.} 
{3130}{}{Egy nyúlpaprikás rendel.}
{3131}{}{Gyere és megkapod!}
{3132}{}{Folyik már a ketchup?}
{3133}{}{Megsült már a hús??}
{3134}{}{Mmm, imádom a simabõrûeket.} 
{3135}{}{Ráléptél az árnyékomra...vagy mi...} 
{3136}{}{Hallom hogy harangoznak az ebédhez.} 
{3137}{}{Nézzétek ki lesz vacsorára.} 
{3138}{}{Testrész az testrész.}
{3139}{}{Szóval te vagy az új szerv-donor, huh?} 
#
# attacking
#
{3140}{}{Látom a számod!}
{3141}{}{Ne is próbálkozz kegyelemért kiáltozni...} 
{3142}{}{Ezt élvezni fogom}
{3143}{}{Úuuu, ez fájhatott!}
{3144}{}{Eljött a csihi-puhi ideje!}
{3145}{}{Megsütöm a májad vacsira!}
{3146}{}{Remélem, nem halsz meg túl hamar} 
{3147}{}{Vacsora!}
{3148}{}{Dögölj meg!}
{3149}{}{Ilyen punkokat eszem reggelire, és ebédre} 
{3150}{}{Hogy lehet rossz az ami ilyen koszos?} 
{3151}{}{Csak hadd kóstoljam meg!}
{3152}{}{Vidítsd fel apucit egy kicsit!} 
{3153}{}{Van egy kád forró vizem a számodra!}
{3154}{}{Maradj nyugton! Nem fog annyira fájni.}
{3155}{}{Ne rángatózz, a séf a konyhában van!} 
{3156}{}{Imádom nézni ahogy fészkelõdnek.}
{3157}{}{Finom és tápláló !}
{3158}{}{Te aztán sokat vérzel, biztos zsenge és szaftos vagy.} 
{3159}{}{Azt hiszem, több a félelem, mint az izgalom.} 
#
# target being missed
#
{3160}{}{Engem nem bírsz bántani!}
{3161}{}{És te mondod, hogy a ghoulok lassúak?!} 
{3162}{}{Mellé, simabõrû!}
{3163}{}{Mellé, simabõrû!}
{3164}{}{Nem tudod megölni azt, amit el sem találsz!} 
{3165}{}{Túl lassú!}
{3166}{}{OK, most próbáld meg max. sebességgel.} 
{3167}{}{Rám céloztál?} 
{3168}{}{Ez meg mi volt?}
{3169}{}{Ez nem az "Amerikából jöttünk".}
{3170}{}{A harchoz koncentrálni is kell.}
{3171}{}{Kár, hogy az elsõ alkalmad az utolsó is.} 
{3172}{}{Te most felém nézel?}
{3173}{}{Talán akkor kéne próbálkoznod, amikor tudod is, hogy mit csinálsz.} 
{3174}{}{Nem, nem, nem! A hegyes vége felém mutasson, világos?} 
{3175}{}{Mire céloztál? Céloztál egyáltalán?} 
{3176}{}{Mi a hibakódod, merev-farok?}
{3177}{}{Most csináltad elõször, igaz?} 
{3178}{}{Én jövök!}
{3179}{}{Ez volt a legjobb lövésed? Ember, hát nem béna vagy?}
#
############################################
# 3200 Junkie
############################################
#
#  running away
#
{3200}{}{Vhoá. Nagyon ott leszek.}
{3201}{}{Visszajövök...miután megvolt a lövésem.}
{3202}{}{Tudtam, hogy több Buffout-ot kellett volna bevennem...}
{3203}{}{Nemtok megnõni, ha meghalok...}
{3204}{}{Aieeeeeee! Ne bánts! Ne bánts!}
{3205}{}{Ez a hallucináció túúl valóságos nekem...}
#
# moving in to attack
#
{3220}{}{Ezt kapd be!}
{3221}{}{Szarul jársz, ha nincs nálad Stimpakk,... vagy egy kis Jet.}
{3222}{}{Hmmm, talán eladhatom a tested egy kis Jetért...}
{3223}{}{El...kap...lak...}
{3224}{}{Talán a megölésed lesz olyan jó, mint egy lövés...}
{3225}{}{Megöllek! Megöllek! Megöllek!}
{3226}{}{A halálod lesz a betépésem csúcspontja...}
#
# attacking
#
{3240}{}{Ezt kapd ki!}
{3241}{}{Kinyírlak! Megöllek! Szétszedlek!}
{3242}{}{Kell valami?!}
{3243}{}{Nrrrg}
{3244}{}{Hiyaaaaaa}
{3245}{}{Lassan öllek meg...}
{3246}{}{Lemész, mint egy olcsó kurva...}
#
# target being missed
#
{3260}{}{Közeli, de nem Jet.}
{3261}{}{Váo, úgy látszik a föld felett nem tudsz eltalálni!}
{3262}{}{Melyik énre céloztál?}
{3263}{}{Vhoa. Majdnem elkaptál.}
{3264}{}{Tudtam, hogy a Jettõl gyorsabb leszek...}
{3265}{}{Elég rosszul harcol ez a hallucináció.}
#
####################################################################################
#
#                   Area People
#
####################################################################################
#                     
#
#                     4000  Arroyo
#                     6000  The Den
#                     8000  Modoc
#                     10000  Klamath
#                     12000  Vault City / Raiders
#                     14000  Gecko
#                     16000 Broken Hills
#                     18000 New Reno
#                     20000 Sierra Army Depot
#                     22000 Redding
#                     24000 NCR
#                     26000 V13 / V15
#                     28000 Military Base
#                     30000 Navarro
#                     32000 San Fransisco
#                     34000 The Enclave
#                     36000 Special (Encounters and Created)
#
#                     Note : Some of these people will just have run away, moving to attack, # attacking, and getting
#                                missed.  Others will also have cataloged hit locations.
#
####################################################################################
#
####################################################################################
#
# 4000 Arroyo
#
#                   4000 The Elder
#                   4100 Hakunin
#                   4200 Standing Fist
#
####################################################################################
#
#
####################################################################################
#
# 12000 Vault City / Raiders
#
#                   12000 Raider Mercs
#                   12100 Raider Captain
#                   12200 Gangster
#                   12300 Raider (Hit Locations)
#
####################################################################################
#
############################################
# 12000 Raider Mercs
############################################
#
#  running away
#
{12000}{}{Nincs az a pénz, amiért ezen a szar helyen meghalnék...}
{12001}{}{Visszavonulás!}
{12002}{}{Ideje eltûnni...}
{12003}{}{Szétszóródni!}
{12004}{}{Hátrálni!}
{12005}{}{Elkaplak te geci, de még megvárom amíg kijön a Fallout 3...}
{12006}{}{Bishop megtarthatja a kurva pénzét...}
#
# moving in to attack
#
{12020}{}{Célpont!}
{12021}{}{Valaki fedezzen!}
{12022}{}{Hop Hop Hop Hop Hop Hop}
{12023}{}{Hop Hop Hop Hop Hop Hop}
{12024}{}{Hop Hop Hop Hop Hop Hop}
{12025}{}{Búcsuzz el a seggedtöl...}
{12026}{}{Ideje lenyomni az anyabaszót...}
{12027}{}{Tölts és tüzelj!}
{12028}{}{Rock and roll!}
{12029}{}{Nézzétek, itt az ingyenes céllövölde...}
{12030}{}{Imádkozz, hogy legyen elég stimpakkod, rézbõrû...}
{12031}{}{Látom már a faszarcút!}
{12032}{}{Betörtek a területünkre!}
{12033}{}{Srácok, van egy behatolónk!}
{12034}{}{Kússzatok ide fiúk, van itt egy behatoló!}
{12035}{}{Valami mocskot fújt ide a szél...}
{12036}{}{Csak a fejét, hogy meg ne sántuljon...}
{12037}{}{Emberek, figyeljetek a részletekre!}
{12038}{}{Folyamatos tüzelést!}
#
# attacking
#
{12040}{}{Pusztítsunk!}
{12041}{}{Kifogytál a szaros szerencsébõl, rézbõrû...}
{12042}{}{Olyan mélyen seggberúglak, hogy egy hétig cipõápolót fogsz szagolni.}
{12043}{}{::De szeretnék légidesszantos lenni...::}
{12044}{}{Kritikus találatra menj!}
{12045}{}{Ez kell neked?! EZ? KELL? NEKED?!}
{12046}{}{Hiyaaaaaa!!!}
{12047}{}{Nesze!}
{12048}{}{Imádkozz, hogy legyen elég stimpakkod, rézbõrû...}
{12049}{}{Adj egy búcsúcsókot a seggednek...}
#
# target being missed
#
{12060}{}{Úgy lõsz, mint ahogy az öregek basznak!}
{12061}{}{Ha! Mellé!}
{12062}{}{Túl gyors ez neked...}
{12063}{}{Ne reménykedj lassú halálban...}
{12064}{}{Béna...}
{12065}{}{Gyenge ÉS lassú, értem.}
#
############################################
# 12100 Raider Captain
############################################
#
#  running away
#
{12100}{}{Ki kell jutnom innen!}
{12101}{}{Visszatérek...}
{12102}{}{Nem ma fogsz megölni!}
{12103}{}{Késõbb, buzi!}
{12104}{}{Nem most hallottál utoljára rólam!}
{12105}{}{Ezért megfizetsz -- máskor!}
#
# moving in to attack
#
{12120}{}{Múlté vagy!}
{12121}{}{Friss hús...}
{12122}{}{Ah, itt a vacsi.}
{12123}{}{Agyak...}
{12124}{}{Felásom a sírod...}
{12125}{}{Csak maradjon egyben a fejed...}
#
# attacking
#
{12140}{}{Látom a számod!}
{12141}{}{Ne sikíts kegyelemért...}
{12142}{}{Ezt élvezni fogom}
{12143}{}{Oooo, ez fájhatott!}
{12144}{}{}
{12145}{}{Megeszem a májad!}
{12146}{}{Lassú halálod lesz, remélem}
{12147}{}{Vacsoraidõ!}
{12148}{}{Halál!}
{12149}{}{Ilyen punkokat eszem reggelire, és ebédre}
#
# target being missed
#
{12160}{}{Engem nem bánthatsz!}
{12161}{}{}
{12162}{}{Mellé, hülyegyerek!}
{12163}{}{Mellé, szararcú!}
{12164}{}{Amit nem találsz el, azt nem tudod megölni!}
{12165}{}{Túl lassú!}
#
############################################
# 12200 Gangster (Combat Messages)
############################################
#
#  running away
#
{12200}{}{Vhoa, túl nehéz ez a szar.}
{12201}{}{Ideje hozni egy kis segítséget...}
{12202}{}{Legközelebb elkaplak!}
{12203}{}{Szerencséd, hogy nincs nálam Stimpakk...}
{12204}{}{Ideje lelépni.}
{12205}{}{Kell Stimpakk, gyorsan...}
#
# moving in to attack
#
{12220}{}{Könnyû vagy, mint az áprilisi szellõ.}
{12221}{}{Pedig azt hittem, hogy ma nem kell megölnöm senkit, hát, tévedtem...}
{12222}{}{Úgy tûnik Golgotha-nak új lakosa van...}
{12223}{}{A nehezebb utat választottad...}
{12224}{}{Kockákat csinálok a fogaidból.}
{12225}{}{Valaki az életét tette fel... és elvesztette}
{12226}{}{Kinyírlak, aztán a családod, és végül a kutyád.}
{12227}{}{Ideje kivinni a szemetet...}
{12228}{}{Eltörlek, mint a szerencsesütit...}
#
# attacking
#
{12240}{}{Úgy seggberúglak, hogy a seggedet fogod kalapként viselni.}
{12241}{}{Fortuna ma nincs veled...}
{12242}{}{Addig verlek amíg ronda nem leszel.}
{12243}{}{Ideje seggberúgni a hallottat.}
{12244}{}{Széttaposom a szíved.}
{12245}{}{Bár lenne nálam egy satu...}
{12246}{}{Hadd mutassam meg, mit csinálunk a szeméttel...}
{12247}{}{Úgy megütlek, hogy asszed földrengés van...}
{12248}{}{Elegem van ebbõl a köcsögbõl...}
{12249}{}{Helyettem is köszönj az angyaloknak...}
#
# target being missed
#
{12260}{}{Az ilyenek miatt fogsz kórházba kerülni...}
{12261}{}{Úgy ütsz, mint egy rossz kurva...}
{12262}{}{Szép volt. Megmutassam hogy kell csinálni?}
{12263}{}{Azt tudtam, hogy hülye vagy, de hogy még vak is?}
{12264}{}{Miva? Belõtted magad?}
{12265}{}{A kaszinó fényes oldalát se találnád el.}
{12266}{}{Ha a levegõt akartad eltalálni, akkor talált.}
#
############################################
# 12300 Raider (Hit Locations)
############################################
#
# target hit in head
#
{12300}{}{Ngggg}
{12301}{}{A...fejem...minden...forog}
{12302}{}{Ugnnn!}
{12303}{}{Az arcom! Ne az arcomat!}
#
# target hit in left arm
#
{12310}{}{A...kezem...a...gyönyörû...kezem.}
{12311}{}{Felcser! Szétbaszták a karom!}
{12312}{}{*hffff*}
#
# target hit in right arm
#
{12320}{}{Az ütö karom! Nem szégyelled magad?!}
{12321}{}{Felcser! Szétbaszták a karom!}
{12322}{}{Hát ezzel a kezemmel se fogom többet fegyverem fényesíteni...}
#
# target hit in torso
#
{12330}{}{A hasam!}
{12331}{}{Hnrgggg}
{12332}{}{*hff*}
{12333}{}{Ezért...meg...fogsz...fizetni...!}
{12334}{}{*Ooooof*}
{12335}{}{Nggg! A kurva életbe!}
#
# target hit in right leg
#
{12360}{}{Picsába! A lábam!}
{12361}{}{*Ergg*}
{12362}{}{Kéne egy stimpakk a lábamba...}
{12363}{}{Urggg...a lábam...szétcseszve...}
#
# target hit in left leg
#
{12370}{}{Gecibe! A lábam!}
{12371}{}{*Ergg*}
{12372}{}{Kéne egy stimpakk a lábamba...}
{12373}{}{Urggg...lábam...szétbaszva...}
#
# target hit in eyes
#
{12380}{}{A szemem! A gyönyörû szemem!}
{12381}{}{Megpróbálsz megvakítani, mi?}
{12382}{}{Nem...látok...vér...a...szememben...}
#
# target hit in groin
#
{12390}{}{Asszed ez valami olcsó akciófilm??}
{12391}{}{Mostmár nem úgy beszélek, mint akinek vannak golyói.}
{12392}{}{Hát, ennyit arról, hogy tökös legény vagyok.}
{12393}{}{Elnézést, amíg végigokádom magam.}
{12394}{}{Fasza. Egy férfi gólyó-fixálóval.}
{12395}{}{Hadd pihenjek le egy kicsit, utána kinyírlak.}
{12396}{}{Fasza!}
#
####################################################################################
#
# 26000         V13/V15
#
#                    26000  Normal Khan
#                    26100  Tough Khan
#
####################################################################################
#
############################################
# 26000 Khan - Normal
############################################
#
#  running away
{26000}{}{Meneküljetek!}
{26001}{}{Visszavonulás!}
{26002}{}{Újracsoportosulás!}
{26003}{}{Futás!}
{26004}{}{Hátrálni!}
{26005}{}{Én leléptem!}
#
# moving in to attack
#
{26020}{}{Öljétek meg, ezt a bolondot!}
{26021}{}{Már halott vagy...}
{26022}{}{Szétbaszlak!}
{26023}{}{Ö az enyém!}
{26024}{}{Gyerünk!}
{26025}{}{A füleid szép trófeák lesznek!}
#
# attacking
#
{26040}{}{Élvezd az életed utolsó pillanatait}
{26041}{}{Vér! Vér! Vér!}
{26042}{}{Kitépem a szívedet!}
{26043}{}{Imádom ezt csinálni veled!}
{26044}{}{A fegyvereidet berakom a vitrinembe!}
{26045}{}{Ölés és fosztogatás. A két kedvenc cselekvésem!}
{26046}{}{Én foglak megölni!}
{26047}{}{A csontjaidat odaadom a kutyámnak!}
{26048}{}{Vér és sötétség!}
{26049}{}{Kifosztom a tetemed!}
{26050}{}{Belezzétek ki a nyeszlett férget!}
#
############################################
# 26100 Khan - Tough
############################################
#
#  running away
#
{26100}{}{Khanok! Fedezzetek!}
{26101}{}{Visszavonulás!}
{26102}{}{Újracsoportosulni!}
{26103}{}{Meneküljetek!}
{26104}{}{Futás!}
{26105}{}{Szétválni és újracsoportosulni!}
#
# moving in to attack
#
{26106}{}{Kezdõdjön a harc!}
{26107}{}{Téged használlak céltáblának!}
{26108}{}{Nincs kegyelem!}
{26109}{}{Ö az enyém!}
{26110}{}{Khanok támadás!}
{26111}{}{Buli van!}
{26111}{}{Kinyírná már végre valaki ezt a szemetet?!}
#
# attacking
#
{26112}{}{Khanok ölés!}
{26113}{}{A Khanok a sivatag elitjei!}
{26114}{}{Király vagyok!}
{26115}{}{A Khanok uralkodni fognak!}
{26116}{}{A Khanok legyõzhetetlenek!}
{26117}{}{Nincs menekülés! Nincs feladás!}
{26118}{}{Megöllek!}
{26119}{}{A füleidet felfûzöm a nyakláncomra!}
{26120}{}{Vér és Sötétség!}
{26121}{}{A Khanok erõsek!}
#
# target being missed
#
{26122}{}{Szép lövés, de én itt vagyok!}
{26123}{}{Nem tudsz megölni!}
{26124}{}{Sérthetetlen vagyok!}
{26125}{}{A vérem erõsebb a tiednél!}
{26126}{}{Szólj, ha befejezted a gyakorlást!}
{26127}{}{Nem vagy méltó rá, hogy velem harcolj!}
{26128}{}{Mért pazarlom rád az idõmet?}
#
####################################################################################
#
# 32000        San Fransisco
#
#                    32000  Shi Hit Location Messages
#                    32100  The Dragon
#                    32200  Lo Pan
#                    32300  Chip
#                    32400  Badger
#                    32500  Ryan
#                    32600  Shi Guards
#                    32700  Elron Hit Locations
#                    32800  Elron Guards
#                    32900  Ron Cruz/Nikki Goldman
#                    33000  OZ-9
#                    33100  OZ-7
#                    33200  Punk (Hit Locations)
#
####################################################################################
#
############################################
# 32000 Shi Hit Locations
############################################
#
# target hit in head
#
{32000}{}{Az arcom! Az arcom!}
{32001}{}{A skalpom!}
{32002}{}{oooh... a fülem...}
#
# target hit in left arm
#
{32010}{}{Aú, a karom!}
{32011}{}{Aú!}
{32012}{}{Eltörted a kezem!}
#
# target hit in right arm
#
{32020}{}{Aú, a kezem!}
{32021}{}{Aúúúúú!}
{32022}{}{Istenem! A kezem!}
#
# target hit in torso
#
{32030}{}{Aúúúú!}
{32031}{}{Azt hiszem, elájulok...}
{32032}{}{Hé! A gyomrom!}
{32033}{}{Oooof!}
{32034}{}{Ez fájt!}
{32035}{}{Azt hiszem, eltaláltad a májam!}
{32036}{}{Ohhh, fájdalom!}
#
# target hit in right leg
#
{32060}{}{Aú, a lábam}
{32061}{}{A térdem!}
{32062}{}{Pont az artériát!}
#
# target hit in left leg
#
{32070}{}{Aú, a lábam!}
{32071}{}{::hop... hop::}
{32072}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{32080}{}{Nem látok! Te szemét!}
{32081}{}{Az arcom! A szemem! Arrrrgh!}
{32082}{}{Hol vagy? Segítség!}
#
# target hit in groin
#
{32090}{}{Óóóóóó, a golyóim! Óóóóóóó...}
{32091}{}{Fá... fá... fáááj...}
{32092}{}{::nyüszít::}
{32093}{}{::öklendezik::}
{32094}{}{Nhem... khapok... lhevhegõt...}
{32095}{}{Fáj, nagyon fáj...}
#
############################################
# 32100 The Dragon
############################################
#
#  running away
#
{32100}{}{Te jobban harcolsz!}
{32101}{}{Igazán erõs vagy. Viszlát!}
{32102}{}{Aieee! Gyõz a Gonosz!}
{32103}{}{Ó, ne...}
{32104}{}{Vesztettem.}
{32105}{}{Megszégyenítettek.}
#
# moving in to attack
#
{32120}{}{Elszomorít, hogy harcolunk kell.}
{32121}{}{Azt javaslom, fuss!}
{32122}{}{Csak egy gyáva használ fegyvereket.}
{32123}{}{Menekülj, amíg tudsz!}
{32124}{}{Készülj fel, gonosztevõ!}
{32125}{}{Fuss és nem bántalak!}
{32126}{}{Ha harc, hát legyen harc...}
{32128}{}{Azt hiszed, legyõzhetsz?}
#
# attacking
#
{32140}{}{Haiiiiiiii-YA!}
{32141}{}{Balhé Bronxban...}
{32142}{}{rúúÚÚÚúúúúú!}
{32143}{}{Hai!}
{32144}{}{Hé!}
{32145}{}{Hai úúúúúú!}
{32146}{}{Hai - ah!}
{32147}{}{Mutass valamit!}
{32148}{}{Mongol Hús!}
{32149}{}{Szemberúglak!}
#
# target being missed
#
{32160}{}{Csak egy gyáva használ fegyvert!}
{32161}{}{Félsz kiállni egy igazi harcossal?}
{32162}{}{A te Kung Fu-d itt hatástalan.}
{32163}{}{Add meg magad!}
{32164}{}{Ezt nevezed te harcnak?}
{32165}{}{Úgy mozogsz, mint egy terhes jak.}
#
############################################
# 32200 Lo Pan
############################################
#
#  running away
#
{32200}{}{Keresek magamnak egy zöld szemû nõt... viszlát!}
{32201}{}{Igen uram... a csekk a levélben van.}
{32202}{}{Azt hiszem, találkozóm van...}
{32203}{}{Oké, te nyertél!}
{32204}{}{Feladom!}
{32205}{}{Ügyesebben harcolsz, mint én!}
#
# moving in to attack
#
{32220}{}{Villám! Mennydörgés! Öljétek meg!}
{32221}{}{Gyenge vagy!}
{32222}{}{A te harci tudásod engem nem sebezhet meg!}
{32223}{}{Legyõzhetetlen vagyok!}
{32224}{}{Menekülj, féreg!}
{32225}{}{A halál közeleg feléd!}
{32226}{}{Lebegj, mint a lepke!}
{32228}{}{Szúrj, mint a darázs!}
#
# attacking
#
{32240}{}{Ki az a Jack Burton?}
{32241}{}{Olyan nagy kérés az, hogy meghalj?!}
{32242}{}{Kifizetted az adósságaidat, Jack?}
{32243}{}{Van egy kis gond az arcoddal.}
{32244}{}{A számla a levélben van!}
{32245}{}{A pokol már vár rád!}
{32246}{}{Üdvözöld az õseidet helyettem is!}
{32247}{}{Halhatatlan vagyok!}
{32248}{}{BALHÉ BRONX-BAN!}
{32249}{}{Hai-YA!}
#
# target being missed
#
{32260}{}{Legyõzhetetlennek érzem magam!}
{32261}{}{Próbáld még egyszer!}
{32262}{}{Sima ügy.}
{32263}{}{Nem is tudod, hogy kell harcolni, mi?}
{32264}{}{Ezt hívod te harcnak?}
{32265}{}{::ásít::}
#
############################################
# 32300 Chip
############################################
#
#  running away
#
{32300}{}{Nekem családom van!}
{32301}{}{Nee.. öö.. ma van a szülinapom!}
{32302}{}{Óó... a lépem...}
{32303}{}{Vissza a kórházba!}
{32304}{}{Meg... kell... védeni... a lépem... helyét...}
{32305}{}{Óó, fáj a májam.}
#
# moving in to attack
#
{32320}{}{Ne kényszeríts, hogy használjam ezt a játék-kést.}
{32321}{}{Úgy leverlek...}
{32322}{}{Kicsi kis szarcsimbókokat eszel reggelire?}
{32323}{}{Szétrúgom a szaros segged!}
{32324}{}{Megváglak!}
{32325}{}{Asszem, csak ennyit kellett mondanom.}
#
# attacking
#
{32340}{}{Bumm a fejbe!}
{32341}{}{Szétrúgom a segged!}
{32342}{}{IGGGEN!}
{32343}{}{Igen, bébi, igen!}
{32344}{}{Ezt akartad?}
{32345}{}{Ne mozogj!}
{32346}{}{Bumm-saka-laka, bébi!}
{32347}{}{Ó, ez a fejed volt?}
{32348}{}{Nagy májernek érzed magad, mi?}
#
# target being missed
#
{32360}{}{Eltévesztetted a lépem! Haha!}
{32361}{}{FOS vagy!}
{32362}{}{Haha! Király vagyok!}
{32363}{}{Adj egy puszit, drágaságom!}
{32364}{}{Ideje mennem, bébi.}
{32365}{}{Leváglak!}
#
############################################
 # 32400 Badger
############################################
#
#  running away
#
{32400}{}{Az arcom! Csak ne az arcom!}
{32401}{}{Szétbasztad a hajam, te görény!}
{32402}{}{Szemét! Ezért ledarállak!}
{32403}{}{Kell egy nagyobb fegyver!}
{32404}{}{Vaaaaaaaaaaa!!!}
{32405}{}{AAGGH!! Seggbelõttél!!}
#
# moving in to attack
#
{32420}{}{Azt fogod kívánni, bárcsak körültekintõbb lett volna az apád!}
{32421}{}{Figyu... olyan az arcod, mint egy nagy valag!}
{32422}{}{Nézzük mid van, pöcsfej!}
{32423}{}{Hajolj elõre, és fogd meg a bokád!}
{32424}{}{Ezt most Shane-ért!!}
{32425}{}{Megpróbálom olyan fájdalmasan csinálni, ahogy csak tudom.}
{32426}{}{Baj, ha a térdkalácsod töröm szét elõször?}
{32428}{}{Gyerünk, kislány! Mutasd mit tudsz!}
#
# attacking
#
{32440}{}{Remélem, nincs szükséged erre a karodra...}
{32441}{}{Francba, ez fájt, mi?}
{32442}{}{Uf-da!}
{32443}{}{Imádom így reggelente a vér illatát...}
{32444}{}{Gyerek, vérzel?}
 {32445}{}{::::böff:::::}
{32446}{}{Bepiszkítottad a pólómat!!!}
{32447}{}{Forró ólom-beöntés rendel!!}
{32448}{}{Ezt kapd ki!!}
#
# target being missed
#
{32460}{}{Bénább vagy, mint az anyám... pedig õ már rég meghalt!}
{32461}{}{Picsába, szar vagy!}
{32462}{}{Menj vissza L.A.-be, köcsög!}
{32463}{}{Akarod, hogy fél lábon álljak?}
{32464}{}{:::fingik:::}
{32465}{}{Ó, ez jó volt...}
#
############################################
# 32500 Ryan
############################################
#
#  running away
#
{32500}{}{Francba, még nyalakodtam volna egy kicsit!}
{32501}{}{La la la... segítség!}
{32502}{}{Ha ha AJJ!}
{32503}{}{AT! AT! At at at at at!}
{32504}{}{Carramba!}
{32505}{}{Segítséééég!}
#
# moving in to attack
#
{32520}{}{Ez nem fog tetszeni neked!}
{32521}{}{Gyere csak, gyere!}
{32522}{}{Kóstolgatsz, kispajtás?}
{32523}{}{Gyere a papához! Jól beakasztok neked!}
{32524}{}{Halott vagy haver, egy jó nagy hulla!}
{32525}{}{Máskor jobban vigyázz, kivel kezdesz ki!}
{32526}{}{Gyere csak, mutatok valamit, bizonyám!}
#
# attacking
#
{32540}{}{Most már késõ, végig kell csinálnod.}
{32541}{}{::dalolászik::}
{32542}{}{Ne félj, nem foglak elfelejteni.}
{32543}{}{Na, essünk túl rajta gyorsan!}
{32544}{}{Ennyi volt, véged van!}
{32545}{}{Hajolj csak elõre szépen...}
{32546}{}{Van számodra egy kis meglepetésem.}
{32547}{}{Énrám hajtasz?}
{32548}{}{Lövök... találok!}
{32549}{}{Most megtudod, milyen egy 'kemény' csávó!}
#
# target being missed
#
{32560}{}{Ez az!}
{32561}{}{Csak így tovább!}
{32562}{}{Ha ha ha!}
{32563}{}{Nem tudsz jobbat?}
{32564}{}{Mi lesz már?}
{32565}{}{Aoúú! Ha ha... csak vicceltem!}
#
############################################
# 32600 Shi Guards
############################################
#
#  running away
#
{32600}{}{Futás!}
{32601}{}{Mentem a bõröm!}
{32602}{}{Visszavonulás!}
{32603}{}{Meneküljünk! Meneküljünk!}
{32604}{}{Futás!}
#
# moving in to attack
#
{32620}{}{Most meggyalázlak!}
{32621}{}{Készülj fel a halálra!}
{32622}{}{Semmi sem tart örökké... még te sem!}
{32623}{}{Szétzúzlak, mint egy gyorsvonat!}
{32624}{}{Figyelmeztettünk...}
{32625}{}{Egy fasírt rendel!}
{32626}{}{Viszlát, a másvilágon!}
#
# attacking
#
{32640}{}{Egyet az én kedvemért...}
{32641}{}{... egyet a mama kedvéért...}
{32642}{}{...egyet a papa kedvéért...}
{32643}{}{...egyet a tesó kedvéért...}
{32644}{}{... és egyet a Halál kedvéért!}
{32645}{}{Húzd el innen a beled!}
{32646}{}{Dögölj meg!}
{32647}{}{Meghalsz!}
{32648}{}{Eltiporlak, mint egy hangyát!}
{32649}{}{Már a jelenléted is idegesít!}
#
# target being missed
#
{32660}{}{Minden csak a reflexeken múlik.}
{32661}{}{Balfék!}
{32662}{}{::sóhajt:: Mikor jön már egy igazi ellenfél?}
{32663}{}{Még ma befejezed?}
{32664}{}{Még ebben az évben eltalálsz, vagy majd csak jövõre?}
{32665}{}{Ez kezd nagyon unalmas lenni...}
#
############################################
# 32700 Elron Hit Locations
############################################
#
# target hit in head
#
{32700}{}{Az arcom! Az arcom!}
{32701}{}{Csillagbéli Atyám! Gyógyíts meg!}
{32702}{}{Jajj! Jól jönne egy kis jég a fejemre.}
#
# target hit in left arm
#
{32710}{}{Ajj, a karom!}
{32711}{}{Ajj!}
{32712}{}{Eltörted a karom!}
#
# target hit in right arm
#
{32720}{}{Ajj, a karom!}
{32721}{}{Ááááhh!}
{32722}{}{A karom!!}
#
# target hit in torso
#
{32730}{}{Aú! Ez tényleg fájt!}
{32731}{}{Menten elájulok.}
{32732}{}{Aouú!}
{32733}{}{Csillagbéli Atyám! Segíts!}
{32734}{}{Ez fájt!}
{32735}{}{Hagyj már békén!}
{32736}{}{Óóó, ez fáááj!}
#
# target hit in right leg
#
{32760}{}{Aú, a lábam!}
{32761}{}{A térdem!}
{32762}{}{Aúú!}
#
# target hit in left leg
#
{32770}{}{Aúúú, a sípcsontom!}
{32771}{}{A térdem!}
{32772}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{32780}{}{Aúú!! A szemem!}
{32781}{}{Az arcom! A szemem! Arrrrgh!}
{32782}{}{A szemem!}
#
# target hit in groin
#
{32790}{}{Óóóóóóóóóóó, a tököm! Óóóóóóó...}
{32791}{}{Ajj... ez nagyon fááj!}
{32792}{}{Aaaah!}
{32793}{}{::nyüszít::}
{32794}{}{Nem... khapok...leveghõt...}
{32795}{}{Még jó... hogy eleve... steril vagyok...}
#
############################################
# 32800 Elron Guards
############################################
#
#  running away
#
{32800}{}{Csillagbéli Atyám! Segíts!}
{32801}{}{Ó, Atyám!}
{32802}{}{Nem akarok még meghalni!}
{32803}{}{Aiieee!}
{32804}{}{Mentsetek meg!}
{32805}{}{BHK-9! Segíts rajtunk!}
#
# moving in to attack
#
{32820}{}{Na, most aztán jól beszabályozlak!}
{32821}{}{Jó lesz végre itthagyni a magadfajtákat...}
{32822}{}{Sajnálhatod, hogy nem látod a jövõt.}
{32823}{}{Soha ne ellenkezz a Csillagbéli Atya akaratával!}
{32824}{}{Hubbell lesújt rád!}
{32825}{}{Mi vagyunk a Csillagbéli Atya bosszúálló öklei!}
{32826}{}{Halál a be nem szabályzottra!}
{32828}{}{Képzeld azt, hogy ez egy újszerû Zéta-vizsgálat!}
#
# attacking
#
{32840}{}{Megtisztítalak a negatív energiáktól!}
{32841}{}{Elõre a Csillagbéli Atyáért!}
{32842}{}{Elõre Hubbell-ért!}
{32843}{}{Elõre Quetzel-ért!}
{32844}{}{Elõre BHK-9-ért!}
{32845}{}{Halál a tisztátalanra!}
{32846}{}{Ne szennyezd be a szentélyünket!}
{32847}{}{Ezt BHK-9 nevében kapod!}
#
# target being missed
#
{32860}{}{Nem figyelsz eléggé!}
{32861}{}{Ha közülünk való volnál, eltalálnál!}
{32862}{}{Nem koncentrálsz!}
{32863}{}{Nem bánthatsz egy igaz hívõt!}
{32864}{}{Ez majd észre térít!}
{32865}{}{Tisztátalan lélek!}
#
############################################
# 32900 Ron Cruz/Nikki Goldman
############################################
#
#  running away
#
{32900}{}{Én csak egy színész vagyok!}
{32901}{}{Félre az útból, híresség vagyok!}
{32902}{}{Ez nem volt benne a forgatókönyvben!}
{32903}{}{Csillagbéli Atyám! Segíts!}
{32904}{}{Én híresség vagyok!}
#
############################################
# 33000 OZ-9
############################################
#
#  running away
#
{33000}{}{Csillagbéli Atyám! Segíts!}
{33001}{}{Ne! Ne engem!}
{33002}{}{Inkább valaki mást ölj meg!}
{33003}{}{Ne ölj meg! Én BHK-9 vagyok!}
{33004}{}{Õrség! Segítsetek!}
{33005}{}{Nem ölhetsz meg! Túl fontos személy vagyok!}
#
# moving in to attack
#
{33020}{}{Pedig beállhattál volna közénk.}
{33021}{}{Az ostoba mindig a nála jobbal kezd ki.}
{33022}{}{Süt rólad a tisztátalanság!}
{33023}{}{Csak le kellett volna tenned az esküt...}
{33024}{}{Csillagbéli Atyánk lesújt rád!}
{33025}{}{Sosem jutsz el a Quetzel bolygóra!}
{33026}{}{Elárultad az embereket!}
{33028}{}{Értéktelen és tisztátalan vagy!}
#
# attacking
#
{33040}{}{Az érintésem megtisztít!}
{33041}{}{Halálra sújtalak!}
{33042}{}{Hubbell nevében!}
{33043}{}{Dicsõséges Csillagbéli Atyánk nevében!}
{33044}{}{Érezd Hubbell haragját!}
{33045}{}{Ez majd segít rajtad!}
#
# target being missed
#
{33060}{}{Csillagbéli Atyám, vigyázz rám!}
{33061}{}{Hubbell vigyáz rám!}
{33062}{}{Reménytelen eset vagy.}
{33063}{}{Nem tudsz bántani!}
{33064}{}{Miért nem próbálsz meg koncentrálni?}
#
############################################
# 33100 OZ-7
############################################
#
#  running away
#
{33100}{}{Csillagbéli Atyám! Segíts!}
{33101}{}{Nekem most a Quetzel-en lenne a helyem!}
{33102}{}{Ne engem! Ne engem ölj meg!}
{33103}{}{Én csak egy lakáj vagyok!}
{33104}{}{Nem én hozom a döntéseket!}
{33105}{}{Nem én kellek neked!}
#
# moving in to attack
#
{33120}{}{Bár ne kéne ezt tennem...}
{33121}{}{Biztos, hogy nem akarod inkább feladni?}
{33122}{}{Inkább beszéljük meg... mit szólsz?}
{33123}{}{Ha BHK-9 azt mondja gonosz vagy, akkor biztos az vagy!}
{33124}{}{Ezt... ööö... Hubbell nevében kapod!}
{33125}{}{A harc nem tesz jót a lelkednek!}
{33126}{}{Nem tudok hihetõen fenyegetõzni...}
{33128}{}{Elõre is bocsánat, ha esetleg bántanálak.}
#
# attacking
#
{33140}{}{Vigyázz!}
{33141}{}{::lehunyt szemmel támadásba lendül::}
{33142}{}{Próbáljuk meg újra...}
{33143}{}{Ha elfutnál, nem kéne ezt csinálnom.}
{33144}{}{Gyerünk! Tûnj el innen!}
{33145}{}{Eridj! Eridj!}
{33146}{}{Hagyd abba a harcot!}
{33147}{}{Hellóóóó-bellóóóóó!}
{33148}{}{Jó szagod van.}
{33149}{}{Beszéljük meg!}
#
# target being missed
#
{33160}{}{Miért csinálsz úgy, mintha bántani akarnál?}
{33161}{}{Mit vétettem én ellened?}
{33162}{}{Te is tudod, hogy nem muszáj harcolnunk!}
{33163}{}{Én sem akarlak bántani!}
{33164}{}{Nem akarom, hogy bánts!}
{33165}{}{Mi lenne, ha felnõttek módjára intéznénk ezt el?}

############################################
# 33200 Punk Hit Locations
############################################
#
# target hit in head
#
{33200}{}{Asszem, eltört az állkapcsom!}
{33201}{}{Az arc-csontom!}
{33202}{}{Ennek csúnya helye lesz.}
#
# target hit in left arm
#
{33210}{}{Hé! Ezzel a kezemmel szoktam írni!}
{33211}{}{A könyököm!}
{33212}{}{Hé! Vigyázz!}
#
# target hit in right arm
#
{33220}{}{Ahhh! Aiee! Ahh!}
{33221}{}{Váhhhh!}
{33222}{}{Ajj! A karom!!}
#
# target hit in torso
#
{33230}{}{Asszem, ez a vesém volt!}
{33231}{}{A hasam!}
{33232}{}{::zihál::}
{33233}{}{Úhhh!}
{33234}{}{Nem kéne ezt csinálnod...}
{33235}{}{Oké, ez tényleg fájt!}
{33236}{}{Óóóó... aúúúú}
#
# target hit in right leg
#
{33260}{}{A sípcsontom!}
{33261}{}{A térdem!}
{33262}{}{Ajj!}
#
# target hit in left leg
#
{33270}{}{Óóó, a lábam!}
{33271}{}{A térdem!}
{33272}{}{Ezután sántítani fogok..}
#
# target hit in eyes
#
{33280}{}{Asszem, levált a retinám!}
{33281}{}{A szemem! A gyönyörû szemem!}
{33282}{}{Megvakultam! Megvakultam!}
#
# target hit in groin
#
{33290}{}{Ez... ez... fáj, mint állat...}
{33291}{}{Mama...}
{33292}{}{::nyüszít::}
{33293}{}{Atya... Úr... Isten!}
{33294}{}{Hmmm. Aú. Hmmm.}
{33295}{}{Mindjárt sokkot kapok!}
#
####################################################################################
#
# 36000        Special Encounters (Randoms)
#
#                   36000 Kaga (Hit Locations)
#                   36100 Kaga (Combat Messages - Area 1)
#                   36200 Kaga (Combat Messages - Area 2)
#                   36300 Kaga (Combat Messages - Area 3)
#                   36400 Kaga (Combat Messages - Area 4)
#                   36500 Kaga (Combat Messages - Area 5)
#                   36600 Super Mutant (Master Army) - Hit Locations
#                   36700 Super Mutant (Master Army) - Combat Messages
#                   36800 Bounty Hunters - Combat Messages
#
####################################################################################
#
############################################
# 36000 Kaga (Hit Locations)
############################################
#
# target hit in head
#
{36000}{}{Ez telibekapta a fejem!}
{36001}{}{Ajj! A fejem!}
{36002}{}{Úúh! Kaga feje fáj!}
#
# target hit in left arm
#
{36010}{}{A kezem!}
{36011}{}{Ajj! Még jó, hogy jobbkezes vagyok...}
{36012}{}{Ajj!!}
#
# target hit in right arm
#
{36020}{}{Ajj, a karom!}
{36021}{}{Eltörted a kezem!}
{36022}{}{Ezt még megbánod!}
#
# target hit in torso
#
{36030}{}{(Röff!)}
{36031}{}{Ez csak karcolás!}
{36032}{}{Grrr!}
{36033}{}{Ezt megbánod!}
{36034}{}{Fejezd be, amíg még tudod!}
{36035}{}{Jó lövés... Most én jövök!}
#
# target hit in right leg
#
{36060}{}{Ajj, a lábam!}
{36061}{}{Ezért megfizetsz!}
{36062}{}{Ah! A LÁBAM!}
#
# target hit in left leg
#
{36070}{}{A lábam!}
{36071}{}{Öhh! Miért célzol ennyire lefelé?}
{36072}{}{Te tényleg a lábamra céloztál!?!}
#
# target hit in eyes
#
{36080}{}{A fenébe, vérzik a szemem!}
{36081}{}{A szemem! Ezért megfizetsz!}
{36082}{}{Szemét állat!}
#
# target hit in groin
#
{36090}{}{Óóóóóóó, idõt kérek, össze kell szednem a maradványokat!}
{36091}{}{Óóó! Ezt a technikát meg kéne tanulnom...}
{36092}{}{Örg! A Büszkeségem! Jól vagy, Kisöreg?}
{36093}{}{Ez... aoúúú... ez fájt!}
{36094}{}{Örhf!}
{36095}{}{Áááoh!}
#
###########################################
# 36100 Kaga (Combat Messages) Area 1
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36100}{}{Még találkozunk!}
{36101}{}{Még visszatérek...}
{36102}{}{Még soha nem gyõztek le!}
{36103}{}{Megesküszöm, hogy megtalállak és elkaplak!}
{36104}{}{Hallasz még felõlem!}
{36105}{}{Ezért még megfizetsz... késõbb!}
#
# moving in to attack
#
{36120}{}{Nekem kéne a Kiválasztottnak lennem!}
{36121}{}{Arroyo még megbánja, hogy számûzött!}
{36122}{}{Rajtad állok bosszút!}
{36123}{}{Kaga átküld a másvilágra.}
{36124}{}{Még egy halandó Kiválasztott!}
#
# attacking
#
{36140}{}{Nincs itt anyuci, hogy segítsen!}
{36141}{}{Ezt élvezni fogom...}
{36142}{}{Úúúú, ez fájhatott!}
{36143}{}{Visszaviszem a fejedet a Törzsfõnek!}
{36144}{}{Megeszem a májad!}
{36145}{}{Remélem, nem halsz meg olyan gyorsan, mint a többiek!}
{36146}{}{Még egy Kiválasztott, akit meg kell ölnöm!}
{36147}{}{Halál rád!}
{36148}{}{Sikolts a kedvemért!}
#
# target being missed
#
{36160}{}{Engem nem bánthatsz!}
{36161}{}{A szellemek megvédenek.}
{36162}{}{Remélem, nem ez volt a legjobb lövésed!}
{36163}{}{Hahaha. Kagának még lehasalnia se kellett!}
{36164}{}{Nem ölhetsz meg, ha el sem találsz!}
{36165}{}{Túl lassú vagy!}
#
############################################
# 36200 Kaga (Combat Messages) Area 2
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36200}{}{Még találkozunk!}
{36201}{}{Még visszatérek...}
{36202}{}{Nem tudod megölni a hatalmas Kagát!}
{36203}{}{Szerencséd van! Kagának más dolga van!}
{36204}{}{Te és Kaga még találkozni fognak!}
{36205}{}{Ezért megfizetsz... késõbb!}
#
# moving in to attack
#
{36220}{}{Miután megöltelek, porig égetem Arroyót!}
{36221}{}{Mindenkinek rettegnie kell tõlem!}
{36222}{}{A fejed Kaga trófeája lesz!}
{36223}{}{Add meg magad és ígérem, gyors halálod lesz!}
#
# attacking
#
{36240}{}{Érezd Kaga haragját!}
{36241}{}{Felesleges kegyelemért könyörögnöd...}
{36242}{}{Ezt nagyon fogom élvezni!}
{36243}{}{Óóóó, ezt még Kaga is érezte!}
{36244}{}{Elviszem a fejed az Törzsfõnek!}
{36245}{}{Kiskanállal fogom kikaparni a szíved!}
{36246}{}{Remélem, tovább bírod, mint a többiek!}
{36247}{}{Egy újabb halott Kiválasztott!}
{36248}{}{Halál rád!}
{36249}{}{Kiabálj a kedvemért!}
#
# target being missed
#
{36260}{}{Nem bánthatsz!}
{36261}{}{A szellemek megvédenek!}
{36262}{}{Remélem, ennél jobbat is tudsz.}
{36263}{}{Buahaha. Kagának még csak le sem kellett hajolnia!}
{36264}{}{Nem ölhetsz meg, ha el sem találsz!}
{36265}{}{Túl lassú vagy!}
#
############################################
# 36300 Kaga (Combat Messages) Area 3
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36300}{}{Remélem, ez nem válik szokásommá...}
{36301}{}{Kagának még gyakorolnia kell...}
{36302}{}{Visszatérek még. Bla-bla-bla... és megöllek!}
{36303}{}{Szerencsés vagy! Kagának fontos dolga akadt...}
{36304}{}{Te és Kaga még találkoztok!}
{36305}{}{Ezért megfizetsz... késõbb!}
#
# moving in to attack
#
{36320}{}{Kaga és a Kiválaszott újra találkozik.}
{36321}{}{Ideje befejezni.}
{36322}{}{Megbánod azt is, hogy egyáltalán hallottál rólam!}
{36323}{}{Sokat fejlõdtem, mióta legutóbb találkoztunk.}
#
# attacking
#
{36340}{}{Érezd Kaga haragját!}
{36341}{}{Ezt nagyon fogom élvezni!}
{36342}{}{Óóóó, ezt még Kaga is érezte!}
{36343}{}{Elviszem a fejed a Törzsfõnek!}
{36344}{}{Kiskanállal fogom kikaparni a szíved!}
{36345}{}{Remélem, tovább bírod, mint a többiek!}
{36346}{}{Egy újabb halott Kiválasztott!}
{36347}{}{Halál rád!}
{36348}{}{Kiabálj a kedvemért!}
#
# target being missed
#
{36360}{}{Nem bánthatsz!}
{36361}{}{A szellemek megvédenek.}
{36362}{}{Remélem, ennél jobbat is tudsz!}
{36363}{}{Buahaha. Kagának még csak el sem kellett hajolnia!}
{36364}{}{Nem ölhetsz meg, ha el sem találsz!}
{36365}{}{Túl lassú vagy!}
#
############################################
# 36400 Kaga (Combat Messages) Area 4
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36400}{}{Remélem, ez nem válik szokásommá.}
{36401}{}{Kagának még gyakorolnia kell...}
{36402}{}{Nem most láttad utoljára Kagát...}
{36403}{}{Szerencséd van! Kagának máshol van dolga...}
{36404}{}{Te és Kaga még találkoztok!}
{36405}{}{Ezért megfizetsz... máskor!}
#
# moving in to attack
#
{36420}{}{A Kiválasztott sosem tér vissza Arroyóba!}
{36421}{}{Kaga porrá zúz téged!}
{36422}{}{Kaga nem fél senkitõl!}
{36423}{}{Kaga most megmutatja, mit tanult legutóbb!}
#
# attacking
#
{36440}{}{Érezd Kaga haragját!}
{36441}{}{Ne mozdulj, hogy Kaga jól eltalálhasson!}
{36442}{}{Ezt élvezni fogom!}
{36443}{}{Óóóó, ezt még Kaga is érezte!}
{36444}{}{Elviszem a fejedet a Törzsfõnek!}
{36445}{}{Kiskanállal kaparom ki a szíved!}
{36446}{}{Remélem, tovább bírod, mint a többiek!}
{36447}{}{Egy újabb halott Kiválasztott!}
{36448}{}{Halál rád!}
{36449}{}{Üvölts a kedvemért!}
#
# target being missed
#
{36460}{}{Nem bánthatsz!}
{36461}{}{A szellemek megvédenek.}
{36462}{}{Ez a legjobb, ami tõled telik?}
{36463}{}{Buahaha. Kagának még csak el sem kellett hajolnia!}
{36464}{}{Nem ölhetsz meg, ha el sem találsz!}
{36465}{}{Túl lassú vagy!}
#
############################################
# 36500 Kaga (Combat Messages) Area 5
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36500}{}{}
{36501}{}{}
{36502}{}{}
{36503}{}{}
{36504}{}{}
{36505}{}{}
#
# moving in to attack
#
{36520}{}{Kaga most már készen áll.}
{36521}{}{Nem vagy ellenfél Kagának!}
{36522}{}{Kaga átküld a másvilágra!}
{36523}{}{Hiányozni fogsz Kagának...}
#
# attacking
#
{36540}{}{Érezd Kaga haragját!}
{36541}{}{Kaga híres lesz, ha megöl téged!}
{36542}{}{Ezt nagyon élvezem!}
{36543}{}{Óóóó, ezt még Kaga is érezte!}
{36544}{}{Elviszem a fejedet a Törzsfõnek!}
{36545}{}{Véged van, Kiválasztott!}
{36546}{}{Kagának most meg kell ölnie téged!}
{36547}{}{Halál rád!}
{36548}{}{Üvölts!}
#
# target being missed
#
{36560}{}{Nem bánthatsz!}
{36561}{}{A szellemek megvédenek.}
{36562}{}{Remélem, ennél jobbat is tudsz!}
{36563}{}{Buhaha. Kagának el sem kellett hajolnia!}
{36564}{}{Nem ölhetsz meg, ha el sem találsz!}
{36565}{}{Túl lassú vagy!}
#
#
############################################
# 36600 Super Mutant (Master Army) - Hit Locations
############################################
#
# target hit in head
#
{36600}{}{Ahhhgh! A pofám!}
{36601}{}{A pofám! Ezért szenvedni fogsz!}
{36602}{}{Ahhhgh! Darabokra téplek!}
#
# target hit in left arm
#
{36610}{}{Ahhhgh!}
{36611}{}{Ajj! Majdnem megsebesítettél!}
{36612}{}{Ahhhgh! Ezért kitöröm a nyakad!}
#
# target hit in right arm
#
{36620}{}{Ahhhgh!}
{36621}{}{Ajj! Majdnem megsebesítettél!}
{36622}{}{Ahhhgh! Ezért még kitöröm a nyakad!}
#
# target hit in torso
#
{36630}{}{Úhh!}
{36631}{}{Grrr!}
{36632}{}{Ezért megöllek!}
{36633}{}{Nem bántasz majd, ha halott leszel!}
{36634}{}{Röhögök a szánalmas támadásodon!}
{36635}{}{Óhhhh!}
{36636}{}{Szétszaggatlak!}
{36637}{}{Grrr! Feldühítesz!}
{36638}{}{Agh!}
{36639}{}{Ezt még visszakapod!}
{36640}{}{Úhh!}
{36641}{}{Jajjj!}
{36642}{}{Hmm, még a végén baj lehet veled...}
{36643}{}{Grrr! Várom már a halálodat!}
{36644}{}{Megsebesíthetsz, de nem gyõzhetsz!}
{36645}{}{Ajj! Nem jó ötlet bántani engem!}
#
# target hit in right leg
#
{36660}{}{Ahhhgh! A lábam!}
{36661}{}{Szerinted ez fájt? Csak nevetek!}
{36662}{}{Ahhhgh! Ezért még kitekerem a nyakad!}
#
# target hit in left leg
#
{36670}{}{Ahhhgh! A lábam!}
{36671}{}{Szerinted ez fájt? Csak nevetek!}
{36672}{}{Ahhhgh! Ezért még kitekerem a nyakad!}
#
# target hit in eyes
#
{36680}{}{Ahhhgh! Szánalmas ember! Megvakítottál!}
{36681}{}{Ahhhgh! Fáj! Mit tettél velem?!}
{36682}{}{Ahhhgh! Soká foglak kínozni!}
#
# target hit in groin
#
{36690}{}{Ez az emberek gyengesége!}
{36691}{}{Azt hiszed, ez fájt? Ne nevettess!}
{36692}{}{Hülye vagy, ember!}
{36693}{}{Miért pont "ott" támadsz??}
{36694}{}{Órákig kínozlak majd!}
{36695}{}{Miért támadsz ott?}
#
############################################
# 36600 Super Mutant (Master Army) - Combat Messages
############################################
#
#  running away
#
{36700}{}{Futás!}
{36701}{}{Nem fogsz megölni!}
{36702}{}{Visszajövök én még!}
{36703}{}{A társaim majd elintéznek!}
{36704}{}{Megfizetsz... késõbb!}
{36705}{}{Én nem halhatok meg, de te igen! Késõbb!}
#
# moving in to attack
#
{36720}{}{A halál már vár!}
{36721}{}{Akik minket zavarnak, mást már nem fognak!}
{36722}{}{A fegyvereid nem bánthatnak!}
{36723}{}{Szenvedni fogsz, de nagyon!}
{36724}{}{Ha harcolok, ölök is!}
{36725}{}{Ki olyan hülye, hogy feldühítsen minket?}
{36726}{}{Ellenséget látok!}
{36727}{}{Szenvedni fogsz, de nagyon!}
#
# attacking
#
{36740}{}{Most meghalsz!}
{36741}{}{Senki sem menthet meg!}
{36742}{}{Hadd lássam, ahogy szenvedsz!}
{36743}{}{Szörnyû halált halsz!}
{36744}{}{Pusztulj, hülye ember!}
{36745}{}{Szörnyû halálod lesz!}
{36746}{}{Szenvedj!}
{36747}{}{Szétzúzlak!}
{36748}{}{Nem gyõzhetsz le minket!}
{36749}{}{Szenvedj, ember!}
#
# target being missed
#
{36760}{}{Miért erõlködsz?}
{36761}{}{Ennyit tudnak az emberek!}
{36762}{}{Nincs erõd!}
{36763}{}{Jót röhögök rajtad!}
{36764}{}{Ez támadás volt netán?}
{36765}{}{Mi vagyunk az erõsebbek!}
#
####################################################################################
#
#                    Party Members
#
####################################################################################
#                     
#                     Notes
#                     
#                     00-09 Hit in Head
#                     10-19 Hit in Left Arm
#                     20-29 Hit in Right Arm
#                     30-59 Hit in Torso (Generic Non-Called Shot Hit)
#                     60-69 Hit in Right Leg
#                     70-79 Hit in Left Leg
#                     80-89 Hit in Eyes
#                     90-99 Hit in Groin
#                     00-19 Running Away
#                     20-39 Moving in to Attack
#                     40-59 Attacking
#                     60-79 Target being Missed
#
#                     40000 Sulik *
#                     40400 Vic
#                     40800 MacRae *
#                     41200 Lenny *
#                     41600 Marcus *
#                     42000 Myron *
#                     42400 Davin
#                     42800 Miria
#                     43200 Laddie
#                     43600 Cyberdog
#                     44000 Robo-Brain (Idiot/Chimp) *
#                     44400 Robo-Brain (Human/Cybernetic) *
#                     44800 Goris **
#
####################################################################################
#
############################################
# 44800 Goris
############################################
#
# target hit in head
#
{44800}{}{Kemény egy fejem van, de ez még nekem is fájt!}
{44801}{}{Mocskosul megfájdult a fejem!}
{44802}{}{Ömf. Ne a fejemet!}
{44803}{}{Fejsérülést én is tudok okozni, sejtheted!}
{44804}{}{Arrrgh! Szédülök...}
#
# target hit in left arm
#
{44810}{}{A másik karommal foglak legyilkolni!}
{44811}{}{Nem kell ahhoz két kar, hogy tönkretegyem a napodat!}
{44812}{}{Ezt a karomat amúgy sem használom sokat.}
{44813}{}{Ajj! Tudok parittyázni a karommal.}
{44814}{}{Az egyik karom odalett, de megmaradt a másik!}
 #
# target hit in right arm
#
{44820}{}{Hé, ez a fontosabbik karom volt!}
{44821}{}{Francba, fáj a karom!}
{44822}{}{A hozzád hasonlókat egy karral is eltángálom.}
{44823}{}{A jobb karom... arrgh!}
{44824}{}{Eltaláltad a karom! Ezért letépem a tiedet!}
#
# target hit in torso
#
{44830}{}{Ömf... nem... kapok... levegõt.}
{44831}{}{Na, egyel megint kevesebb bordám lett.}
{44832}{}{Jaj! Gyûlölöm a haslövéseket.}
{44833}{}{Arrgghh! Fáj a mellkasom!}
{44834}{}{Gyomorszáj... atttyaég, ez fájt!}
{44835}{}{Ez most harc, vagy így szeretnéd felhívni magadra a figyelmet?}
{44836}{}{Csak szólj, ha ennek fájnia kellett volna, mert akkor felkiáltok a kedvedért.}
{44837}{}{A mamád tanított harcolni?}
{44838}{}{Ó, de fáj (ásít). Kérlek, ne bánts többet!}
{44839}{}{Ha szerinted ez találat, majd mindjárt megmutatom, mi az igazi találat!}
{44840}{}{Ezért nagyon seggbe rúglak!}
{44841}{}{Azta! Ez egy kicsit szúr!}
{44842}{}{Ezért hagytam ott a Menedéket!?}
{44843}{}{Asszem, pihenõre lesz szükségem.}
{44844}{}{Aúúúúú! Ez fájt!}
{44845}{}{Ez egyáltalán nem fájt!}
{44846}{}{Hol van a stimpakk, amikor szükség van rá?}
{44847}{}{Amint újra tudok mozogni, neked annyi!}
{44848}{}{Érzéketlen vagyok a fájdalomra!}
{44849}{}{Ezért a magam brutál módján fogom megtaposni az arcodat!}
#
# target hit in right leg
#
{44860}{}{Nagyszerû! Én leszek az egyetlen sánta halálkarom.}
{44861}{}{Ajjaj! A lábam...}
{44862}{}{A lábaddal fizetsz azért, amit az enyémmel mûveltél!}
{44863}{}{Hiányozni fog ez a láb...}
{44864}{}{Nem kell két láb ahhoz, hogy megöljelek.}
#
# target hit in left leg
#
{44870}{}{Nagyszerû! Sánta leszek.}
{44871}{}{Franc essen beléd! A lábam...}
{44872}{}{Ne már a lábamat! Nem fogok tudni járni!}
{44873}{}{Eltörted a lábam, eltörted a lábam!}
{44874}{}{Arrggh! Fáj a térdem!}
#
# target hit in eyes
#
{44880}{}{Nem látok!}
{44881}{}{Ne már a szemembe!}
{44882}{}{Vér... a szemembe vér ment... nem látok.}
{44883}{}{Nem látlak ugyan, de érzem a szagodat.}
{44884}{}{Ezután szemüvegre lesz szükségem!}
#
# target hit in groin
#
{44890}{}{Az ágyéklövés annyira kisstílû dolog!}
{44891}{}{Ne... próbálj... még egyszer... övön alul!}
{44892}{}{Ez mocsokság! Mi lenne, ha én is tökön lõnélek?}
{44893}{}{Gyûlölöm az ágyéklövéseket! Önngh...}
{44894}{}{Ágyéklövés... Még jó, hogy nem vagyok ember!}
#
#  running away
#
{44900}{}{Lépjünk olajra!}
{44901}{}{Én akkor távoznék...}
{44902}{}{Visszavonulás!}
{44903}{}{Visszaaa!}
{44904}{}{Na, én leléptem!}
{44905}{}{Lábam, cserben ne hagyj!}
{44906}{}{El az útból, menekülés van!}
{44907}{}{Nem menekülök, hanem stratégiailag visszavonulok.}
{44908}{}{Na, elég ebbõl a szarságból!}
{44909}{}{El kell tûnnöm!}
#
# moving in to attack
#
{44920}{}{Gyere csak ide, mindjárt benyomok egyet!}
{44921}{}{Az enyém vagy!}
{44922}{}{Válassz: te vagy én... én rád szavazok!}
{44923}{}{Készülj a temetésedre!}
{44924}{}{Gyere, most megkapod!}
{44925}{}{Most utolér a végzeted!}
{44926}{}{Addig búcsúzkodj, amíg tudsz!}
{44927}{}{Most ellátom a bajodat!}
{44928}{}{Bulizzunk!}
{44929}{}{Itt jövök!}
{44930}{}{Találkozunk a tûzvonalban!}
{44931}{}{Na, itt az idõ, hogy valakibe belekössek!}
{44932}{}{Elõre a végsõ megsemmisítés útján!}
{44933}{}{Embermódra bánok el most veled!}
{44934}{}{Itt az idõ egy kis adok-kapokra!}
{44935}{}{Most összeakasztjuk a bajszunkat!}
{44936}{}{Itt jön a rosszaság!}
{44937}{}{Itt jövök, nézd csak!}
{44938}{}{Célpont bemérve, célra tartok!}
{44939}{}{Most jön a vihar!}
#
# attacking
#
{44940}{}{Most bántalmazni foglak... de nagyon!}
{44941}{}{Ez sokkal jobban fog fájni neked, mint nekem!}
{44942}{}{Csináld másokkal, mielõtt õk csinálják veled!}
{44943}{}{Ha van még olyan részed, ami nem fájt eddig, most az is fájni fog!}
{44944}{}{Test-test ellen. Imádom!}
{44945}{}{Mondd meg a neved, hogy értesíthessem a családodat!}
{44946}{}{Én vagyok az, aki a halált rakta a halálkarom szóba!}
{44947}{}{Jobb adni, mint kapni!}
{44948}{}{Remélem, legalább annyira élvezed, mint én!}
{44949}{}{Csak nem fájt? Ha nem, legközelebb majd fog.}
{44950}{}{Hohó, itt mindjárt vérezni fog valaki!}
{44951}{}{Ha végeztem, nem fognak egy stimpakkal helyrehozni.}
{44952}{}{Remélem, van egészségügyi biztosításod. Szükséged lesz rá!}
{44953}{}{Ideverek, odaverek, megjöttek a pulóverek...}
{44954}{}{Nem érdekel, ki kezdte, de most szépen befejezzük!}
{44955}{}{Szeretem a szakadó hús hangját. Te nem?}
{44956}{}{Ez még csak a bemelegítés, a java csak most jön!}
{44957}{}{Na, élesítsük meg egy kicsit a körmeinket...}
{44958}{}{Hoppá! Remélem, ez nem hiányzott!}
{44959}{}{Csak akkor távozom, ha helybenhagytalak!}
#
# target being missed
#
{44960}{}{Segítene, ha egyszerûen csak álldogálnék?}
{44961}{}{Szemüveg! Be kéne ruházni egy szemüvegbe!}
{44962}{}{Lerajzoljam a célpontot?}
{44963}{}{Miért oda célzol, amikor itt vagyok?}
{44964}{}{Remélem, nincs szándékodban karriert csinálni ebbõl.}
{44965}{}{Hogy tudtál egy ekkora célpontot elvéteni?}
{44966}{}{Ha! Argh grrnnngh thppppt! (Halálkarom gúnyolódás)}
{44967}{}{Ügyes kis szaros vagyok, mi?}
{44968}{}{Örülhetsz, hogy az anyád nem látta ezt.}
{44969}{}{Tényleg többet kéne gyakorolnod.}
{44970}{}{Ez nagyon zavarba ejtõ. Nem mondom el senkinek, milyen béna vagy..}
{44971}{}{Szóval arra képeztek ki, hogy ne találd el a célpontot?}
{44972}{}{Ez nem akaszt ki téged?}
{44973}{}{Ne sírj! Talán majd legközelebb sikerül.}
{44974}{}{Remek, Grace! Mi lesz a ráadás?}
{44975}{}{Ez kiváló példája volt annak, hogy lehet elvéteni egy célpontot.}
{44976}{}{Kezdem azt hinni, hogy téged nem erre találtak ki.}
{44977}{}{Azt akarod, hogy halálra röhögjem magam?}
{44978}{}{Ezzel mondjuk megkavartad kissé a levegõt, de semmi egyéb!}
{44979}{}{Elvétettél vagy mifene?}
#
