#
# Messages used in gdialog.c for custom NPC combat control.
#
{0}{}{Sorozatlövés}
{1}{}{Menekülés}
{2}{}{Fegyverhasználat}
{3}{}{Távolság}
{4}{}{Kit támadjon}
{5}{}{Droghasználat}

{10}{}{Kész}
{11}{}{Mégse}

#
# Burst options.
#
{99}{}{Nem lehetséges.}
{100}{}{Mindig!}
{101}{}{Néha nem baj, ha eltalálsz.}
{102}{}{Légy biztos benne, hogy nem találsz el!}
{103}{}{Nagyon vigyázz, hogy el ne találj!}
{104}{}{Légy teljesen biztos benne, hogy nem találsz el!}

#
# Run away options.
#
{200}{}{Fuss, mint a nyúl!}
{201}{}{Ha fáj az ujjad.}
{202}{}{Ha egy kicsit vérzel.}
{203}{}{Ha nem érzed jól magad.}
{204}{}{Ha csak egy hajszál választ el a haláltól.}
{205}{}{Soha!}

#
# Weapon pref options.
#
{300}{}{Semmilyen.}
{301}{}{Közelharci.}
{302}{}{Közelharci, utána távolsági.}
{303}{}{Távolsági, utána közelharci.}
{304}{}{Távolsági.}
{305}{}{Pusztakezes.}

#
# Distance options.
#
{400}{}{Maradj mellettem!}
{401}{}{Roham!}
{402}{}{Maradj távol az ellenségtõl!}
{403}{}{Ahogy neked tetszik.}
{404}{}{Maradj ahol vagy!}

#
# Attack who options.
#
{500}{}{Aki engem támad.}
{501}{}{A legerõsebbet.}
{502}{}{A leggyengébbet.}
{503}{}{Akit akarsz.}
{504}{}{Aki a legközelebb van.}

#
# Chem use options.
#
{600}{}{Tiszta vagyok.}
{601}{}{Stimpakkot, ha fáj egy kicsit.}
{602}{}{Stimpakkot, ha nagyon fáj.}
{603}{}{Bármilyen drogot, de csak ritkán.}
{604}{}{Bármikor bármit.}