#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used by EDITOR.C
#
# (These MUST match "text message" enumeration on the top of EDITOR.C)
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
#
{100}{}{OK}
{101}{}{OPCIÓK}
{102}{}{MÉGSE}
{103}{}{MENTÉS}
{104}{}{KOR}
{105}{}{NEM}
{106}{}{NÉV}
{107}{}{FÉRFI}
{108}{}{NÕ}
{109}{}{KÉPESS.}
{110}{}{KARMA}
{111}{}{HULLÁK}
{112}{}{KÉPZ. PONTOK}
{113}{}{Szint:}
{114}{}{TP:}
{115}{}{Köv. szint:}
{116}{}{KAR.PONTOK}
{117}{}{KÉPZETTSÉGEK}
{118}{}{Mielõtt elkezdenéd a játékot,} # 1
{119}{}{az összes karakter pontot használd fel!}     # 2
#
{120}{}{Karakterpontok}
{121}{}{Szabad karakterpontok, amiket az elsõdleges képességek növelésére használhatsz.}
{122}{}{Következõ szint}
{123}{}{Ennyi tapasztalati pont kell még a következõ szint eléréséhez.}
{124}{}{Képességek}
{125}{}{Karma}
{126}{}{Hullák}
{127}{}{A képességek további tulajdonságokat adnak. Minden harmadik szinten választhatsz egy képességet.}
{128}{}{A játékban hozott döntéseid eredménye.}
{129}{}{Ez a számláló tartja számon, milyen élõlénybõl mennyit öltél meg, vagy öltek meg a jelenlétedben.}
{130}{}{Képzettség pontok}
{131}{}{Ezekkel a pontokkal növelheted a képzettségeidet. Ahogy egyre ügyesebb leszel valamiben, annál több pont kell a növelésére. Egy képzettség elsajátítása sok idõbe és erõfeszítésbe telik.}
#
{132}{}{Elérte a maximum értéket.}    # 1
{133}{}{Nem tudod növelni.} # 2
{134}{}{Minimum értéken van.}    # 1
{135}{}{Nem tudod csökkenteni.} # 2
{136}{}{Nincs elég képzettség pontod.}
{137}{}{Alap:}
{138}{}{SPEC KÉPZ.}
{139}{}{VÁLASZTHATÓ JELLEMVONÁSOK}
{140}{}{Már megvan a maximum} # 1
{141}{}{három spec képzettséged!}        # 2
{142}{}{Mielõtt elkezdenéd a játékot,} # 1
{143}{}{válassz három spec. képzettséget!}    # 2
{144}{}{Speciális képzettségek}
{145}{}{A speciális képzettségekhez +20%-ot kapsz, és kétszer gyorsabban fejlõdnek. Hármat kell választanod!}
{146}{}{Választható jellemvonások}
{147}{}{A jellemvonások részletezik a karaktered egyéniségét. Mindegyiknek van pozitív és negatív hatása. Legfeljebb kettõt választhatsz.}
{148}{}{Már megvan a két választható} # 1
{149}{}{jellemvonásod!}           # 2
{150}{}{Képzettségek}
{151}{}{A képzettségek elsajátított tudást jelölnek. Tapasztalattal, vagy játék közbeni különleges események során nõnek. Minél nagyobb az érték, annál jártasabb vagy az adott képzettségben.}
#
{152}{}{Válassz egy képességet}
{153}{}{Válassz egy új jellemvonást}
{154}{}{Jellemvonás elvesztése}
{155}{}{Válassz egy új spec képzettséget}
{156}{}{Jellemvonás}
#
{157}{}{Minden tulajdonságnak 1 és 10 között kell lennie,} # 1
{158}{}{mielõtt elkezded a játékot!}     # 2
# Fallout 2:
{160}{}{Nem adtál nevet a karakterednek.} # 1
{161}{}{Így is õt választod?}    # 2

{175}{}{Köv. szint:} # Short for Level:


#
# Abbreviated basic stat levels
#
{200}{}{Pocsék} # Terrible
{201}{}{Rossz}  # Bad
{202}{}{Gyenge} # Poor
{203}{}{Elmegy} # Fair
{204}{}{Átlag} # Average
{205}{}{Jó}   # Good
{206}{}{Nyerõ}  # Very Good
{207}{}{Kiváló} # Great
{208}{}{Tuti} # Excellent
{209}{}{Hõsies} # Heroic

#
# Abbreviated Derived/Non Derived stat names
#
{300}{}{Életpont}
{301}{}{Akciópont}
{302}{}{Védelmi érték}
{303}{}{Pusztak. sebz.}
{304}{}{Pusztak. sebz.}
{305}{}{Sebzésell.}
{306}{}{Méregellenállás}
{307}{}{Sugárzás-ell.}
{308}{}{Reakció}
{309}{}{Regenerálódás}
{310}{}{Kritikus esélye}
{311}{}{Teherbírás}
{312}{}{Mérgezés}
{313}{}{Sugárfertõzés}
{314}{}{Szemsérülés}
{315}{}{Törött jobb kar}
{316}{}{Törött bal kar}
{317}{}{Törött jobb láb}
{318}{}{Törött bal láb}

#
# Damage info texts
#
# Poisoned
{400}{}{Méreg van a szervezetedben. Amíg meg nem gyógyítod, vagy magától nem távozik, folyamatos sebzést szenvedsz tõle.}
# Radiation
{401}{}{Sugárfertõzésben szenvedsz. Minél több, annál súlyosabb a hatása.}
# Eye Damage
{402}{}{Megsérült az egyik, vagy mindkét szemed. Ez befolyással van az Érzékelésedre.}
# Crippled right arm
{403}{}{Megsérült a jobb karod és nem tudod rendesen használni. Ha megsérült az egyik karod, nem tudsz kétkezes fegyvereket használni. Ha mindkettõ megsérült, nem tudsz fegyvert használni.}
# Crippled left arm
{404}{}{Megsérült a bal karod és nem tudod rendesen használni. Ha megsérült az egyik karod, nem tudsz kétkezes fegyvereket használni. Ha mindkettõ megsérült, egyáltalán nem tudsz fegyvert használni.}
# Crippled right leg
{405}{}{Eltört a jobb lábad.}
# Crippled left leg
{406}{}{Eltört a bal lábad.}

# Month strings
{500}{}{Január}
{501}{}{Február}
{502}{}{Március}
{503}{}{Április}
{504}{}{Május}
{505}{}{Június}
{506}{}{Július}
{507}{}{Augusztus}
{508}{}{Szeptember}
{509}{}{Október}
{510}{}{November}
{511}{}{December}

#
# Option menu text
#
{600}{}{MENTÉS}
{601}{}{TÖLTÉS}
{602}{}{MENTÉS TXT-BE}
{603}{}{TÖRLÉS}
{604}{}{KÉSZ}
{605}{}{Biztos, hogy törölni akarod}   # line 1
{606}{}{ezt a karaktert?}         # line 2
{607}{}{ sikeresen elmentve.}
{608}{}{ sikeresen betöltve.}
{609}{}{már létezik.}
{610}{}{Biztos, hogy felülírod?}
{611}{}{Hiba a mentésben }
{612}{}{Hiba a töltésben }
{613}{}{Karakter fájl érvénytelen.}
{614}{}{Karakter adat érvénytelen.}
{615}{}{Hiba a fájl lista olvasásában!}
{616}{}{NYOMTATÁS}
{617}{}{JÁTÉKOS}
{618}{}{BLANK.GCD}

#
# ASCII text file printing text
#
{620}{}{FALLOUT}          # Title line 1
{621}{}{VAULT-13 PERSONNEL RECORD} # Title line 2
{622}{}{hours} # Title line 3
# -
# -
#{000}{}{        Erõ: 00      Életpontok: 000/000      Reakció: 00}
#{000}{}{     Érzékelés: 00    Védelmi érték: 000     Regenerálódás: 00}
#{000}{}{      Kitartás: 00     Akciópontok: 000    Kritikus esélye: 000%}
#{000}{}{      Karizma: 00  Közelharci sebzés: 000      Teherbírás: 000 font}
#{000}{}{   Intelligencia: 00   Sebzésellenállás: 000%}
#{000}{}{      Ügyesség: 00 Sugárzás-ellenállás: 000%}
#{000}{}{     Szerencse: 00    Méregellenállás: 000%}
#
{623}{}{ ::: Statisztika :::}
{624}{}{    Erõ:}
{625}{}{    Életpontok:}
{626}{}{     Reakció:}
# -
{627}{}{   Érzékelés:}
{628}{}{    Védelmi érték:}
{629}{}{    Regenerálódás:}
# -
{630}{}{   Kitartás:}
{631}{}{   Akciópontok:}
{632}{}{   Kritikus esélye:}
# -
{633}{}{    Karizma:}
{634}{}{   Pusztakezes sebzés:}
{635}{}{     Teherbírás:}
# -
{636}{}{  Intelligencia:}
{637}{}{    Sebzésellenállás:}
# -
{638}{}{    Ügyesség:}
{639}{}{  Sugárzás-ellenállás:}
# -
{640}{}{      Szerencse:}
{641}{}{    Méregellenállás:}
# -
# -
#{000}{}{ Name: 01234567890    Age: 00     Gender: Female}
{642}{}{ Név:}
{643}{}{Kor:}
{644}{}{        Nem:}
{645}{}{Férfi}
{646}{}{Nõ}
#-
#{000}{}{ Level: 00         Exp: 000,000  Next Level: 000,000}
{647}{}{ Szint:}
{648}{}{        TP:}
{649}{}{Köv. szint:}
#-
{650}{}{ ::: Jellemvonások :::}
{651}{}{ ::: Képességek :::}
{652}{}{ ::: Karma :::}

#-
{653}{}{ ::: Képzettségek :::        ::: Hullák :::}
#-
{654}{}{ ::: Tárgylista :::}
#-
{655}{}{                   Össz tömeg:}
{656}{}{ ::: Függõségek :::}
{657}{}{ ::: Hírnév :::}

#
# Karma name strings
#
{1000}{}{Hírnév (Általános) }
{1001}{}{Berzerker}
{1002}{}{Bajnok}
{1003}{}{Gyerekgyilkos}
{1004}{}{Nuka-Cola függõség}
{1005}{}{Buffout függõség}
{1006}{}{Mentát függõség}
{1007}{}{Pszicho függõség}
{1008}{}{RadAway függõség}
{1009}{}{Alkohol függõség}
{1010}{}{Jet-függõség}
{1011}{}{Tragic kártyafüggõség}
{1012}{}{THIS GOES WITH THE TEMPORARY ONE FOR DESCRIPTIONS #1112: DON'T TRANSLATE THIS}
{1013}{}{Szexpert}
{1014}{}{Bokszoló}
{1015}{}{Dzsigoló}
{1016}{}{Sír-rabló}
{1017}{}{A Salvatore család tagja}
{1018}{}{Házas}
{1019}{}{Pornósztár}
{1020}{}{Rabszolga-kereskedõ}
{1021}{}{A Puszta Szüze}
{1022}{}{A Bishop család tagja}
{1023}{}{A Mordino család tagja}
{1024}{}{A Wright család tagja}
{1025}{}{Elvált}

#
# Karma description strings
#
{1100}{}{Ez a változó érték mutatja az általános megítélésedet. Minél nagyobb, annál elismertebb vagy a térségben. Ha negatív az érték, gonosz tetteid miatt sokan gyûlölnek.}
{1101}{}{Nagyon sok embert öltél meg. Ez nem tesz túl jót a hírnevednek, habár a rossz emberek jobban fognak kedvelni.}
{1102}{}{A tetteid miatt az emberek Bajnoka lettél. A gonosz elleni harcodról mindenfelé hallott. A tisztességes emberek jobban kedvelnek.}
{1103}{}{Gyerekeket öltél meg, a Pusztaság fiatalságát. Ez bizony nagyon rossz dolog. Te nagyon, nagyon rossz ember vagy.}
{1104}{}{Iszonyúan élvezed a Nuka-Kólát, a poszt-nukleáris világ üdítõitalát.}
{1105}{}{Buffout-függõ lettél. Ezt a drogot rendszeresen kell szedned, vagy viselned kell a hátrányait.}
{1106}{}{Mentat függõségben szenvedsz. Szedned kell, vagy szenvedni fogsz a megvonástól.}
{1107}{}{Függõ vagy. Ha nem szeded a Psycho-t, szenvedni fogsz. Ha szeded, mások fognak szenvedni.}
{1108}{}{Függõ lettél a Radaway-re. Igaz, hogy nem életveszélyes, de rendszeresen kell szedned.}
{1109}{}{Problémád van az alkohollal. Pontosabban az ivással.}
{1110}{}{Jet-függõ vagy. Rendszeresen kell szedned.}
{1111}{}{Tragic kártyajáték függõ vagy. Állandóan új kártyákat akarsz szerezni.}
{1112}{}{TEMPORARY - What is this?}
{1113}{}{Tudod, mi az a szex, és tudod, mi az az elõjáték. Van fogalmad róla, hogyan kell kielégíteni az ellenkezõ nem tagjait.}
{1114}{}{Te vagy Észak-Kalifornia nehézsúlyú bokszbajnoka. Hírnevet és elismerést szereztél... és egy kis bónuszt a keménységedhez valamint a pusztakezes képzettségedhez.}
{1115}{}{Legyünk õszinték: Mindennel lefekszel, ami két lábon jár, de néha még ennyire sem vagy válogatós.}
{1116}{}{"Õk már halottak, nem érdekli õket" - ez lett a te mottód. Mások maradványainak felásása számodra már meghaladja a hobbi szintet.}
{1117}{}{A Salvatore család tagja lettél. Ismert és elismert vagy, ráadásul remekül nézel ki öltönyben.}
{1118}{}{Bekötötték a fejed. Hé, ez a te bajod, nem a miénk.}
{1119}{}{Hatalmas, fényes, és tündöklõ csillag vagy. Egész New Reno ismeri a szexuális teljesítményedet.}
{1120}{}{Beléptél a Rabszolga-kereskedõk csoportjába. Attól a tetkótól a homlokodon mindenkinek nyilvánvalóvá válik a foglalkozásod.}
{1121}{}{Többet kéne randiznod. A szexuális tapasztalataid... hát, hogy is mondjam... egysíkúak.}
{1122}{}{A Bishop család tagja lettél. Ismert és elismert vagy, ráadásul remekül nézel ki öltönyben.}
{1123}{}{A Mordino család tagja lettél. Ismert és elismert vagy, ráadásul remekül nézel ki öltönyben.}
{1124}{}{A Wright család tagja lettél. Ismert és elismert vagy, ráadásul remekül nézel ki öltönyben.}
{1125}{}{A házastársad már nincs veled. Remélem, boldog vagy.}

#
# Town reputations
#
{2000}{}{Bálványozott}
{2001}{}{Kedvelt}
{2002}{}{Elfogadott}
{2003}{}{Semleges}
{2004}{}{Ellenszenves}
{2005}{}{Utált}
{2006}{}{Üldözött}

{2100}{}{Ezen a környéken mindenki hozzád hasonló szeretne lenni. Te vagy a város hõse, és mindenki példaképe.}
{2101}{}{Az emberek elõre köszönnek, integetnek neked, akárhova is mész azon a környéken. Mindenki hallott rólad, és örülnek a hallottaknak.}
{2102}{}{Igaz, hogy nem fogadnak tárt karokkal, de minimum bólintanak, amikor találkoznak veled. A többiekhez hasonlóan beilleszkedtél.}
{2103}{}{Általában gyanakvóak az idegenekkel szemben, de még nem ismernek eléggé.}
{2104}{}{Te is csak egy újabb kívülálló vagy, aki valószínûleg csak bajt kever.}
{2105}{}{Bebizonyítottad az embereknek, hogy gyanakvásuk nem volt hiábavaló. Amikor a közelükbe érsz, összesúgnak a hátad mögött. Tudják, hogy bajkeverõ vagy.}
{2106}{}{Amikor mások közelébe mész, megbámulnak és suttognak, néhányan átmennek az utca másik felére, csak hogy ne kelljen melletted elmenni, míg mások leköpnek, elfordulnak tõled. Mindenki tudja, hogy te vagy a létezõ legrosszabb dolog az életükben.}

#
# Karma status strings
#
{3000}{}{Elesettek Megmentõje}
{3001}{}{A Puszta Õrzõje}
{3002}{}{A Reménység Pajzsa}
{3003}{}{Védelmezõ}
{3004}{}{Vándor}
{3005}{}{Áruló}
{3006}{}{A Kétségbeesés Fegyvere}
{3007}{}{A Puszta Ostora}
{3008}{}{Sátánfajzat}

#
# Karma section titles.
#
{4000}{}{Hírnév}
{4001}{}{függõségek}

#
# Karma section descriptions.
#
{4100}{}{Megmutatja, milyen a hírneved az adott helyen.}
{4101}{}{Ezekre a dolgokra vagy függõ.}

#
# Special Demo version only text
#
{5000}{}{Sorry, you can only print your}  # 1
{5001}{}{character in the full version.}  # 2
{5002}{}{Sorry, you can only save your}  # 1
{5003}{}{character in the full version.}  # 2
{5004}{}{Sorry, you can only load a saved} # 1
{5005}{}{character in the full version.}  # 2
{5006}{}{CHEAT MODE}
{5007}{}{Not available in demo.}