#
# Item.c messages
#
{1}{}{%d ponttal nõtt az %s.}
{2}{}{%d ponttal csökkent az %s.}
{3}{}{Jobban érzed magad.}
{4}{}{Túladagolás miatt végzetes szívrohamot kaptál.}
{5}{}{A nálad lévõ %s kifogyott.}
{6}{}{A nálad lévõ %s bekapcsolt.}
{7}{}{A nálad lévõ %s kikapcsolt.}
{8}{}{Végighúzod magadon a Geiger-számlálót. A kijelzõ %d értéket mutat.}
{9}{}{Ezt a tárgyat csak a kezedbõl tudod használni.}
{10}{}{Nem történt semmi.}


# Fallout 2:
{50}{}{Nem úgy tûnik, mintha túl sokat csinált volna.}


#
# Fallout 2
#
{500}{}{Nincs elég fény a tárgy feltöltéséhez.}
#
{600}{}{A drog ártalmas hatása miatt %s csökkenést tapasztalsz.}

# Weapon Damage strings
{800}{}{Könnyû}
{801}{}{Közepes}
{802}{}{Nehéz}
{803}{}{Extrém}
# Weapon Range strings
{820}{}{Rövid}
{821}{}{Közepes}
{822}{}{Hosszú}