has#
# Miscellaneous game engine messages.
#
# Defined in game.h
#
{0}{}{Biztosan ki akarsz lépni?}
{1}{}{Demó verzió}
{2}{}{Alap Karakter használata.}
{3}{}{Kép elmentve.}
{4}{}{Gyorstöltés sikerült.}
{5}{}{Gyorsmentés sikerült.}
{6}{}{Demo time limit exceeded.}
{7}{}{A PipBoyt nem használhatod harc közben!}
{8}{}{Hiba a kép mentése során.}
{9}{}{}
{10}{}{}
{11}{}{}
{12}{}{}
{13}{}{}
{14}{}{}
{15}{}{Akció Pontok}
{16}{}{Élet Pontok}
{17}{}{A mozgásérzékelõ nincs installálva.}
{18}{}{A mozgásérzékelõ lemerült.}
{20}{}{Copyright(c) 1998 Interplay Productions.  All rights reserved.}


{30}{}{Folytatod a játékot?}

{50}{}{A Fallout 2 indításához szükség van a CD-re!} 

#
# Game config text. Defined in gconfig.c
#
{100}{}{Hiba a beállítások mentésében!}
{101}{}{A játék beállításait nem sikerült elmenteni!}
#
# Some radiation messages used in critter.c
#
{1000}{}{Rosszul érzed magad.}
{1001}{}{Nagyon rosszul vagy, és erõteljes hányást követõen még fáradt is.}
{1002}{}{Nagyon kimerültél, és nem bírod abbahagyni a hányást. Ez erõsen kihat a felépülési idõdre.}
{1003}{}{Iszonyúan vérzel. Hányingered van, és hullik a hajad.}
{1004}{}{Iszonyúan és egyfolytában vérzel. Vért hánysz, a bõröd pedig lemállik a csontjaidról.}
{1005}{}{Belsõ vérzésed és hasmenésed van. Fel vagy fújódva és agonizálsz.}
{1006}{}{Meghaltál a sugárfertõzéstõl.}
{1007}{}{Nagy mennyiségû sugárzást kaptál.}
{1008}{}{A Geiger-számláló kattog.}
{1009}{}{A Geiger-számláló vadul kattog.}
#
# Message used in actions.c
#
{2000}{}{Nem tudsz oda menni.}
{2001}{}{A zár beragadt.}
#
# poison messages from critter.c
#
{3000}{}{Megmérgeztek!}
{3001}{}{A méregtõl sebzést szenvedsz.}
{3002}{}{Kicsivel jobban vagy.}
{3003}{}{Jobban vagy.}
#
# from queue.c
#
{4000}{}{Hozzá-nemértésed miatt a kelleténél korábban detonált a robbanószer.} 
#
# from combatai.c
#
{5000}{}{tárgyat használ:}
{5001}{}{kifogyott a lõszerbõl. Így most használhatatlan az üres}
{5002}{}{lõszert készít elõ, és máris harcra kész a megtöltött}
#Igy egy fokkal jobb, mint ahogy volt (bass)
#
# from gdialog.c - new tell me about stuff
#
{6000}{}{Mirõl kérdezel?}

#
# from pipboy.c -- Fallout 2
#
// Fallout 2:  For Pipboy
{7000}{}{Nincs nálad a PipBoy!}

#
# from anim.c -- Fallout 2
#
{8000}{}{Túl vagy terhelve.}  # Carrying too much weight
{8001}{}{%s túl van terhelve.}

#
# from worldmap.c -- Fallout 2
#
{8500}{}{A túlélési képzettséged sikeres használatáért %d tapasztalati pontot kapsz.}

#
# from party.c -- Fallout 2
#
{9000}{}{%s újabb képességekre tett szert.} # Party Member has gained experience/level
# Individuals

{9010}{}{Azta! Hirtelen megszállt a tapasztalat!} # pMMyron_PID
{9011}{}{Szintlépés, bébi! Szintlépés!}
{9012}{}{Óriási zavart érzek az Erõben. A képzettségeim mintha nõttek volna % pontot.}
{9013}{}{Szívósabb lettem! Erõsebb! Okosabb!}

{9020}{}{Hûûû! Úgy érzem, korlátlan tapasztalathoz jutottam és erõsebb lettem!} # pMMarcus_PID
{9021}{}{Aaagggh! Izmok... duzzadnak... Képzettségek... nõnek... Szintlépés...}
{9022}{}{Adjatok egy diplomát, meg egy olyan hülye rojtos sipkát, mert épp most végeztem!}
{9023}{}{Hé, erõsebb lettem! Ezért kapok fizetésemelést?} 

{9030}{}{A türelem rózsát terem...} # pMMacRae_PID
{9031}{}{Heh. Ezek szerint még ez az öreg róka is tud tanulni új trükköket.}
{9032}{}{Úgy látszik, megért ennyit utazgatni.}
{9033}{}{Tanultam néhány új trükköt.} 

{9040}{}{Vén-csont tanít. Mi tanulunk.} # pMSulik_PID
{9041}{}{Tanulunk a Szellemektõl, ember.}
{9042}{}{Tanulunk.}
{9043}{}{A Nagy Szellem beleszállt Sulikba.}
{9044}{}{Mi most már okosabb lettünk.}
{9045}{}{Mi tanulunk Vén-csonttóll.}

{9050}{}{Hûû... ettõl éppenséggel okosabb lettem.} # pMLenny_PID
{9051}{}{Ennek a bûne fog megölni.}
{9052}{}{El sem hiszem, hogy eddig túléltem.}

{9060}{}{Vaú!} # pMCyberdog_PID
{9061}{}{Vaú!}
{9062}{}{Vaú!}
{9063}{}{Vaú!}
{9064}{}{Vaú! Vaú!}

{9070}{}{Tanultam néhány új dolgot!} # pMDoc_PID
{9071}{}{Tanultam néhány új dolgot!}

{9080}{}{Szerintem most újabb tudásra tettem szert!} # pMGoris_PID
{9081}{}{A tudás világossága ajándék.}
{9082}{}{Szerintem szépen fejlõdök.}
{9083}{}{Még Gruthart is lekörözöm a tudásommal.}
{9084}{}{Még a falka tagjainál is erõsebb vagyok.}
{9085}{}{Most már én vagyok falka leghatalmasabbika.}

{9090}{}{Tanultam néhány új dolgot!} # pMDavin_PID
{9091}{}{Tanultam néhány új dolgot!}

{9100}{}{Tanultam néhány új dolgot!} # pMMaria_PID
{9101}{}{Tanultam néhány új dolgot!}

{9110}{}{Tanultam néhány új dolgot!!} # pMLaddie_PID
{9111}{}{Tanultam néhány új dolgot!}

{9120}{}{INFORMÁCIÓ ELEMZÉSE KÉSZ. RENDSZER FEJLESZTÉSE.} # pMRoboBrain_PID  -- CyberBrain
{9121}{}{ÚJ INFORMÁCIÓT SZEREZTEM. TÁMADÓ RENDSZER FEJLESZTÉSE.}
{9122}{}{RENDSZER BõVÍTÉSE KÉSZ.}
{9123}{}{CÉLZÓ RENDSZER BEÁLLÍTVA. 20%-KAL NõTT A PONTOSSÁG.}
{9124}{}{ELÉRTEM AZ OPTIMÁLIS TELJESÍTMÉNYT.}

{9130}{}{Fõnök! Asszem, ráéreztem erre a dologra.} # pMVic_PID
{9131}{}{Egyre jobb vagyok! Mondtam, hogy nem okozok csalódást, fõnök.}
{9132}{}{Hé... várj... most már megvan. Szerintem tudnék még fejlõdni.}
{9133}{}{Látod, fõnök?! Még egy ilyen vén róka is tud tanulni!}
{9134}{}{Tudod mit, fõnök? Asszem, tanultam egy-két új dolgot.}
{9135}{}{Egyre jobb vagyok ebben. Látod, Fõnök? Idõvel minden jó dolog még jobb lesz.}

{9140}{}{Tanultam néhány új dolgot!} # pMBess_PID
{9141}{}{Tanultam néhány új dolgot!}

{9150}{}{Tanultam néhány új dolgot!} # pMChicken_PID
{9151}{}{Tanultam néhány új dolgot!}

{9160}{}{Tanultam néhány új dolgot!} # pMKarl_PID
{9161}{}{Tanultam néhány új dolgot!}

{9170}{}{Tanultam néhány új dolgot!!} # pMJonny_PID
{9171}{}{Tanultam néhány új dolgot!}

{9180}{}{Tanultam néhány új dolgot!} # pMLloyd_PID
{9181}{}{Tanultam néhány új dolgot!}

{9190}{}{Vaú, VAÚ!} # pMDogMeat_PID
{9191}{}{Vaú, VAÚ, VAÚÚÚÚ!}
{9192}{}{Vaú, VAÚ, VAÚÚÚÚ!}
{9193}{}{Vaú, VAÚ, VAÚÚÚÚ!}
{9194}{}{Vaú, VAÚ, VAÚÚÚÚ!}
{9195}{}{Va-VAÚÚÚÚ!}

{9200}{}{} # pMRoboBrain_PID -- Human

{9210}{}{} # pMRoboBrain_PID -- Abnormal

{9220}{}{} # pMRoboBrain_PID -- Chimp

{9230}{}{} # pMPariahDog_PID 

{9240}{}{Program fejlesztése folyamatban, Mester... Fejlesztés kész.}  # pMK9_PID
{9241}{}{Szoftver telepítése, Mester... 2.0 Verzió telepítve.}
{9242}{}{Hardver fejlesztése, Mester... Rendszer átlagos.}
{9243}{}{Hardver fejlesztése, Mester... Rendszer optimális!}


{9250}{}{} # pMCarTrunk_PID

