{100}{}{Égõ olajoshordó}
{101}{}{A hordóban papír és más éghetõ anyag parázslik.}
{200}{}{Fa ajtó}
{201}{}{Egy fából készült ajtó.}
{300}{}{Fa asztal}
{301}{}{Egy fából készült asztal.}
{400}{}{Fa asztal}
{401}{}{Egy fából készült asztal.}
{500}{}{Fém hordó}
{501}{}{Egy régi, acélból készült hordó.}
{600}{}{Fém hordó}
{601}{}{Egy régi, acélból készült hordó.}
{700}{}{Abroncsok}
{701}{}{Egy rakás poros gumiabroncs. Vulkanizált és keményített fajta. Valószínûleg a hõ által.}
{800}{}{Biztonsági ajtó}
{801}{}{Ez az ajtó nagyon biztonságosnak látszik. A külsõ világ elemeitõl és a veszélyes teremtményektõl véd.}
{900}{}{Számítógép}
{901}{}{Egy számítógépes terminál, amely fel van csatlakoztatva egy szerverre.}
{1000}{}{Oszlop}
{1001}{}{Támasztóoszlop, ami az egész komplexumra esõ nyomást hívatott csökkenteni.}
{1100}{}{Számítógép}
{1101}{}{Számítógép, melyet a központi számítógépre kapcsoltak.}
{1200}{}{Számítógép}
{1201}{}{Terminál, amely kapcsolatban áll egy központi számítógéppel.}
{1300}{}{Monitor}
{1301}{}{Monokróm monitor, melyen különbözõ információjú bitek jelennek meg. Néha egy-egy bájt is feltûnik.}
{1400}{}{Monitor}
{1401}{}{Zöld színû képernyõ, amin mindenféle bitek rohangásznak.}
{1500}{}{Holovetítõ}
{1501}{}{Szélessávú THT-magnó. Már vagy 80 éve nem gyártottak új filmet hozzá.}
{1600}{}{Képernyõk}
{1601}{}{Egy háromtagú monitorsor, melyeken más-más adatok futnak végig.}
{1700}{}{Képernyõk}
{1701}{}{Egy három képernyõbõl álló monitorcsokor, különbözõ adatokat mutatnak a Menedék minden részérõl.}
{1800}{}{Ajtó}
{1801}{}{Közelebbi vizsgálódás után is ajtónak tûnik.}
{1900}{}{Ajtó}
{1901}{}{Akárhogy is nézed, ez egy ajtó.}
{2000}{}{Szellõzõ}
{2001}{}{Egy ventillátor, ami tisztítja és frissíti a bázis levegõjét.}
{2100}{}{Szellõzõ}
{2101}{}{Egy szellõztetõ, ami megtisztítja és felfrissíti a bázis levegõjét.}
{2200}{}{A 13-as Menedék ajtaja}
{2201}{}{Egy óriási ajtó, ami bármilyen sérülésnek vagy nyomásnak képes ellenállni.}
{2300}{}{A 13-as Menedék ajtaja}
{2301}{}{Egy páncélozott ajtó, amit arra terveztek, hogy minden támadásnak és csapásnak ellenálljon.}
{2400}{}{Talapzat}
{2401}{}{Hidraulikus emelõ, mely az egész emelvény energiaellátásáért és a kommunikációért felel.}
{2500}{}{Monitor}
{2501}{}{Ha egy monitort láttál, mindet láttad.}
{2600}{}{Monitor}
{2601}{}{Egy monitor, amin különbözõ adatok láthatók.}
{2700}{}{Rács}
{2701}{}{Rács a padlón.}
{2800}{}{Csövek}
{2801}{}{Néhány csõ. Egész közelrõl is csõnek tûnnek.}
{2900}{}{Szellõztetõ}
{2901}{}{Szabványos Menedék-Tek szellõzõrendszer.}
{3000}{}{Oszlop}
{3001}{}{Szabványos Menedék-Tek támoszlop-rendszer.}
{3100}{}{Oszlop}
{3101}{}{Szabványos Menedék-Tek támasztóoszlop.}
{3200}{}{Szellõztetõ}
{3201}{}{Alapkiszerelésû Menedék-Tek szellõzõrendszer.}
{3300}{}{Szellõztetõ}
{3301}{}{A Menedék-Tek alap szellõzõrendszer típusa.}
{3400}{}{Ágy}
{3401}{}{Egy ágy, ami sokkal kényelmesebbnek látszik, mint amiben eddig aludtál.}
{3500}{}{Ágy}
{3501}{}{Egy átlagos ágy. Puhának tûnik.}
{3600}{}{Ágy}
{3601}{}{Ágy. Kényelmesnek látszik.}
{3700}{}{Ágy}
{3701}{}{Egy normál ágy. Ebben aztán lehet aludni!}
{3800}{}{Lift}
{3801}{}{Ez a karbantartók liftje.}
{3900}{}{Szék}
{3901}{}{Ez egy szék. Kár, hogy nincs idõd leülni és pihennni egy kicsit.}
{4000}{}{Szék}
{4001}{}{Ez tényleg Szék. Sajnos nincs idõd leülni és egy jót lustálkodni.}
{4100}{}{Szék}
{4101}{}{Egy szokványos szék. Csak idõd nincs rá, hogy lelülj rá.}
{4200}{}{Szék}
{4201}{}{Hát nem széknek néz ki? Szívesen bele is huppannál, de sajnos nincs rá idõd.}
{4300}{}{Monitor}
{4301}{}{Egy számítógép monitorja, amin számodra érdektelen adatok láthatók.}
{4400}{}{Monitor}
{4401}{}{Monitor. Mit mondhatnék még róla?}
{4500}{}{Monitor}
{4501}{}{Egy monitor. Számok és betûk szaladgálnak össze-vissza rajta.}
{4600}{}{Monitor}
{4601}{}{Monitor, ami (számodra annyira nem) fontos adatokat jelenít meg.}
{4700}{}{Monitor}
{4701}{}{Az egyik számítógép monitorja, amin hosszú számsorok futnak végig.}
{4800}{}{Monitor}
{4801}{}{Ezen a monitor is ugyanaz látható, mint a többin. Semmi érdekes.}
{4900}{}{A szektor kijárata}
{4901}{}{A szektor kijárata}
{5000}{}{Levegõ Tisztító Egység}
{5001}{}{Az LTE megtisztítja és frissen juttatja vissza a levegõt a komplexumba. Ez itt épp tönkrement.}
{5100}{}{Szék}
{5101}{}{Ez egy szék. De sietned kell, és ezért sajnos nem ülhetsz rá!}
{5200}{}{Szék}
{5201}{}{Ez bizony szék. Milyen jól néz ki! Szívesen kipróbálnád.}
{5300}{}{Szék}
{5301}{}{Szék. Megrázó, de mélyreható elemzését idõ hiányában most hanyagolnod kell.}
{5400}{}{Szék}
{5401}{}{Ez egy szék, nem vitás. Hát akkor miért nem ülsz rá?}
{5500}{}{VME}
{5501}{}{A Videó Megjelenítõ Egység különféle monitorokból és képernyõkbõl áll. Nagyon dolgozik a kicsike.}
{5600}{}{VME}
{5601}{}{A Videó Megjelenítõ Egység pár monitorból és egy-két másik képernyõbõl áll. Szorgosan dolgozik.}
{5700}{}{Szék}
{5701}{}{Egy átlagos szék. Nagyon puhának tûnik.}
{5800}{}{Szék}
{5801}{}{Széknek tûnik... és pedig milyen kényelmes széknek!}
{5900}{}{Szék}
{5901}{}{Egy szék. A kényelmesebb fajtából.}
{6000}{}{Szék}
{6001}{}{Ez egy szék. Hm, felettéb kényelmesnek látszik.}
{6100}{}{Asztal}
{6101}{}{Tudtad, hogy amíg nem voltak asztalok, az emberek kénytelenek voltak a földre tenni a dolgaikat?}
{6200}{}{Asztal}
{6201}{}{Minden kétséget kizáróan ez egy asztal.}
{6300}{}{Kúszónövény}
{6301}{}{Ez egy kúszónövény. Természetesen, még soha nem láttál élõ kúszónövényt ezelõtt. Jobb lesz, ha megnézed közelebbrõl.}
{6400}{}{Kaktusz}
{6401}{}{Hát, nem látsz túl sok érdekes dolgot ezen a kaktuszon.}
{6500}{}{Kaktusz}
{6501}{}{Nem látsz semmi feltûnõt ezen a kaktuszon. Biztos jó kis pálinkát lehetne belõle készíteni.}
{6600}{}{Fa}
{6601}{}{Egy kiszáradt fa. Itt semmi sem nõ rendesen.}
{6700}{}{Szuper-Titkos Hexagon}
{6701}{}{Ha ezt olvasod, akkor lehet panaszkodni a dizájnereknek!}
{6800}{}{Lépcsõ}
{6801}{}{Egy lépcsõ. Furcsa, nem?}
{6900}{}{Cseppkõ}
{6901}{}{Sztalagmit.}
{7000}{}{Cseppkõ}
{7001}{}{A kõpadló természetes kinövése.}
{7100}{}{Vértócsa}
{7101}{}{Ebben a tócsában nincsen semmi rendkívüli. Eltekintve persze attól, hogy itt valaki vagy valami bizony meghalt.}
{7200}{}{Kõoszlop}
{7201}{}{Ez a vastag kõbõl készült oszlop a padlótól egészen a plafonig ér.}
{7300}{}{Kõoszlop}
{7301}{}{Tömör kõoszlop, mely a padlóból indul és a mennyezetnél ér véget.}
{7400}{}{Kövek}
{7401}{}{Kigúvadt szemekkel figyeled a köveket egy darabig, de nem mozdulnak.}
{7500}{}{Kövek}
{7501}{}{Közelebbrõl is szemügyre veszed ezeket a kavicsokat, hátha meg akarnának támadni.}
{7600}{}{Autó}
{7601}{}{NINCS}
{7700}{}{Kapu}
{7701}{}{Fából készült kapu.}
{7800}{}{Kövek}
{7801}{}{Nagy rakás kõ. A környékrõl származnak.}
{7900}{}{Kövek}
{7901}{}{Egy kupacnyi kõ.}
{8000}{}{Kövek}
{8001}{}{Egy kisebb halomnyi szikladarab.}
{8100}{}{Kövek}
{8101}{}{Baromi sok kõ.}
{8200}{}{Csontok}
{8201}{}{Egy nagy halom kifehéredett állati csont. Legalábbis állati csontoknak véled...}
{8300}{}{Csontok}
{8301}{}{Kifakult állati csontok nagy halomban. Legalábbis úgy gondolod, hogy mind állatoktól származik...}
{8400}{}{Csontok}
{8401}{}{Rengeteg megsárgult csont. Nem tudod megállapítani, milyen fajtájú állathoz tartoznak.}
{8500}{}{Csontok}
{8501}{}{Valamikor egy szarvaskenguru vázát alkothatták, de nem vagy benne biztos. Ehhez már túlságosan elporladtak.}
{8600}{}{Csontok}
{8601}{}{Ezek a csontok egy böhöm nagy kétfejû tehéné voltak valamikor.}
{8700}{}{Kapu}
{8701}{}{Fából ácsolt kapu. Ki lehet nyitni és be lehet zárni, ki lehet nyitni és be lehet zárni...}
{8800}{}{Kapu}
{8801}{}{Fakapu.}
{8900}{}{Kapu}
{8901}{}{Egy fa alapanyagú, kapunak látszó tárgy.}
{9000}{}{Kövek}
{9001}{}{Nagyon sok kõ. Hátborzongató, ahogy itt hevernek.}
{9100}{}{Kövek}
{9101}{}{Egy nagy rakás kõ. Ha egy picit közelebbrõl megnézed, apró öregemberek arcait láthatod a kövek oldalán.}
{9200}{}{Kövek}
{9201}{}{Kövek, kövek, kövek! Bárhova nézel, mindenhol csak köveket látsz!}
{9300}{}{Kövek}
{9301}{}{Egy kis halom kõ.}
{9400}{}{Bárpult}
{9401}{}{Itt aztán mindenféle fõzött ital megtalálható a porzó májak szolgálatában.}
{9500}{}{Szék}
{9501}{}{Ez egy öreg, szétrohadt szék, amit egy õsrégi autó ülésébõl készítettek.}
{9600}{}{Szék}
{9601}{}{A sokat látott széknek már szaga van, lábait pedig téglákkal pótolták. Nem túl kényelmes.}
{9700}{}{Szék}
{9701}{}{Egy büdös, penészes ülés, ami valaha egy autó része volt. Mocskosul kényelmetlennek tûnik.}
{9800}{}{Szék}
{9801}{}{Egy szakadt, színtelen, szikkadt és erõsen szagló szék.}
{9900}{}{Dívány}
{9901}{}{Egy elképesztõen kényelmetlennek tûnõ ülõalkalmatosság, melyet dívány néven emlegetnek.}
{10000}{}{Dívány}
{10001}{}{Neve alapján ez egy dívány lenne, de aki ült már rajta, ezt erõsen kétségbe vonja.}
{10100}{}{Abroncs}
{10101}{}{Egy régi gumiabroncs, mely némi gaz közepén csücsül.}
{10200}{}{Bozót}
{10201}{}{Némi sivatagi gaz.}
{10300}{}{Bozót}
{10301}{}{Egy sivatagi bokor.}
{10400}{}{Bozót}
{10401}{}{Egy csokornyi a sivatag legrondább növényeibõl.}
{10500}{}{Bozót}
{10501}{}{Egy kis dekoráció a sivatagban.}
{10600}{}{Szemét}
{10601}{}{Egy rozsdás kocsiajtó támaszkodik egy rozsdás fém hordónak. Merõ egy rozsda az egész.}
{10700}{}{Szemét}
{10701}{}{Egy törött vécécsésze, félig betemette már a homok. Olyan akár az élet.}
{10800}{}{Gaz}
{10801}{}{Egy amolyan sivatagi bozót. Ha nõtt is valamit az utóbbi idõben, biztosan nem mostanában tette.}
{10900}{}{Szemét}
{10901}{}{Egy autókerék, amit jócskán belepett a homok. Kis fadarabok hevernek körülötte.}
{11000}{}{Kövek}
{11001}{}{Kicsit közelebbrõl megnézve, úgy látod, hogy ezek valójában megkövesedett fadarabok.}
{11100}{}{Kosz}
{11101}{}{Kis kupac por, melybõl elhalt gaz kandikál elõ.}
{11200}{}{Kosz}
{11201}{}{Egy kis kupac kosz.}
{11300}{}{Kosz}
{11301}{}{A szél szorgos munkájának eredménye.}
{11400}{}{Kosz}
{11401}{}{Összetömörült por.}
{11500}{}{Gaz}
{11501}{}{Egy koszbucka, amin keresztülfut egy megszáradt gazcsomó.}
{11600}{}{Szemét}
{11601}{}{Egy meghajlott rozsdás fémdarab.}
{11700}{}{Szemét}
{11701}{}{Törött fadarabok.}
{11800}{}{Szemét}
{11801}{}{Mindenféle haszontalan dolog.}
{11900}{}{Kosz}
{11901}{}{Kis rakás kosz.}
{12000}{}{Kosz}
{12001}{}{Egy rakás kosz.}
{12100}{}{Kosz}
{12101}{}{Összefújt homok.}
{12200}{}{Kosz}
{12201}{}{Kosz. Kis tételben.}
{12300}{}{Kosz}
{12301}{}{Igen, ez egy kupac por.}
{12400}{}{Kosz}
{12401}{}{Porszemek gyülekezõhelye.}
{12500}{}{Gaz}
{12501}{}{Nahát, megint egy igen érdekes növényre bukkantál!}
{12600}{}{Gaz}
{12601}{}{Íme, ilyenek élnek meg a sivatagban.}
{12700}{}{Gaz}
{12701}{}{Egy átlagos sivatagi növény.}
{12800}{}{Titkos-Hexagon (NoLight)}
{12900}{}{Fal}
{13000}{}{Fal}
{13100}{}{Fal}
{13200}{}{Fal}
{13300}{}{Fal}
{13400}{}{Fal}
{13500}{}{Lefolyó}
{13501}{}{Undorító bûz áramlik a csatornalefolyóból. Pár pillanat múlva már nem is tûnik annyira rossznak a szag.}
{13600}{}{Lefolyó}
{13601}{}{Tisztán ki tudsz venni valami mozgást a rács mögött. Parányi rád meredõ vörös szempárt látsz. Egy patkány szemei.}
{13700}{}{Lefolyó}
{13701}{}{A lefolyóból csobogó víz hangja hallatszik, a szag pedig undorító.}
{13800}{}{Lefolyó}
{13801}{}{Hallod a víz bugyogását a lefolyóban. Jó kis bukéja van!}
{13900}{}{Létra}
{13901}{}{Régi, roskatag létra. Úgy tûnik, nem nagyon bírná el a súlyod.}
{14000}{}{Csatornalejáró}
{14001}{}{Mintha egy csatornarendszer bejárata lenne.}
{14100}{}{Fényforrás}
{14200}{}{Ajtó}
{14201}{}{Úgy látszik, ez a menedék-ajtó megsérült, talán megégett. Ezzel szemben még mindig mûködik.}
{14300}{}{Ajtó}
{14301}{}{Ez a hagyományos menedékajtó mintha megégett volna. Ennek ellenére még lehet használni.}
{14400}{}{Fedél}
{14401}{}{Egy jó nehéz fedõlemez. Elég jó állapotban van és nemrég rakták arrébb.}
{14500}{}{Lyuk}
{14501}{}{Az ajtón egy óriási lyuk tátong.}
{14600}{}{Lyuk}
{14601}{}{Az ajtón ez a lyuk jött létre egy robbanást követõen.}
{14700}{}{Golyóálló üveg}
{14701}{}{Teljesen törhetetlen üveg. Meg se próbáld...}
{14800}{}{Golyóálló üveg}
{14801}{}{Golyó- és ütésálló üveg. Nem érdemes próbálkozni.}
{14900}{}{Golyóálló üveg}
{14901}{}{Ez az üveg mindenféle csapást kibír. Hiába is próbálkoznál.}
{15000}{}{Golyóálló üveg}
{15001}{}{Ezt az üveget nem lehet áttörni, se átlõni. Nyugodtan feladhatod.}
{15100}{}{Ajtó}
{15101}{}{Ez az ajtó nagyon modern. Tágulva nyílik ki, ahogy a három alkotórésze elfordul.}
{15200}{}{Ajtó}
{15201}{}{Ez egy nagyon hiper-szuper nyílászáró. Három részbõl áll, ezek forognak el nyitódáskor.}
{15300}{}{Ajtó}
{15301}{}{Az ajtóra az Acél Testvériségének címerét pingálták.}
{15400}{}{Ajtó}
{15401}{}{Ahogy rápillantasz az ajtóra, egybõl az Acél Testvériségének emblémája ötlik a szemedbe.}
{15500}{}{Lift}
{15501}{}{Ez egy Testvériségi lift belseje. Makulátlan!}
{15600}{}{Lift}
{15601}{}{Amit most látsz, az egy Testvériségi lift belsõ tere. Kristálytiszta!}
{15700}{}{Jel}
{15701}{}{Ez az Acél Testvériségének jelképe. Jelzi, hogy ez a terület az övék, és jobb lesz, ha azonnal eltûnsz innen.}
{15800}{}{Monitor}
{15801}{}{Egy számítógép monitorját látod. A Testvériség technológiájával készült.}
{15900}{}{Monitor}
{15901}{}{Ez egy számítógép monitorja. A Testvériség technológiájával készült.}
{16000}{}{Számítógép}
{16001}{}{Ez egy számítógépes adatbank. Valószínûleg ezt is a Testvériség készítette.}
{16100}{}{Számítógép}
{16101}{}{Számítógépesített emlékezettároló. Nyilván ez is a Testvériség munkája.}
{16200}{}{Számítógép}
{16201}{}{Egy nagyon modern számítógép, ami a szintén modern szalagos tárolási megoldást alkalmazza a már rég elavult lyukkártyák helyett.}
{16300}{}{Számítógép}
{16301}{}{Az egyik legújabb típusú számítógép, amelyen a tárolást szalagokkal oldották meg, nem pedig lyukkártyákkal.}
{16400}{}{Monitor}
{16401}{}{Egy monitor. A Testvériség gyártmánya.}
{16500}{}{Monitor}
{16501}{}{Monitor. Maga az Acél Testvérisége tervezte.}
{16600}{}{Vezeték}
{16601}{}{Valamelyik monitor vezetéke.}
{16700}{}{Vezeték}
{16701}{}{Az egyik monitorhoz tartozó kábel.}
{16800}{}{Vezeték}
{16801}{}{Ahogy végignézed, rájössz, hogy az egyik monitorhoz kapcsolódik.}
{16900}{}{Oszlop}
{16901}{}{Ez egy támpillér.}
{17000}{}{Oszlop}
{17001}{}{Egy hatalmas támaszték.}
{17100}{}{Bejárati terminál}
{17101}{}{Ez a gép irányítja a menedék böszme nagy ajtaját. Ha mûködésre akarod bírni, meg kell adnod a helyes kódot.}
{17200}{}{Tábla}
{17201}{}{Ez Gizmó Kaszinójának hirdetõtáblája.}
{17300}{}{A 13-as Menedék külsõ ajtaja}
{17301}{}{Ezen az ajtón keresztül lehet kijutni a menedékbõl a külvilágba.}
{17400}{}{A 13-as Menedék külsõ ajtaja}
{17401}{}{Ez az ajtó a kapocs a menedék és a külsõ világ között.}
{17500}{}{Kaszinó felirat}
{17501}{}{A tábla ezen részen látható egy elektromos motor, ami lassan pörgeti körbe-körbe a hozzákapcsolt neon feliratot.}
{17600}{}{Lefele nyíl}
{17700}{}{Felfele nyíl}
{17800}{}{Láda}
{17900}{}{Láda}
{18000}{}{Láda}
{18100}{}{Lift tetõ}
{18101}{}{A lift egyik részét látod.}
{18200}{}{Számítógépes konzol}
{18201}{}{Egy szimpla terminál, ami egy kábellel kapcsolódik valami óriási számítógéphez. A Testvériség technológiáját alkalmazza.}
{18300}{}{Számítógépes konzol}
{18301}{}{Ez egy néma terminál, amit egy kábel köt hozzá a központi számítógéphez. Az Acél Testvériség tervein alapul.}
{18400}{}{Embléma}
{18401}{}{Ez a Testvériség emblémája. A fogaskerekek jelentik a mûszaki tudásukat, a kard a védelmi képességeiket, a szárnyak a felemelkedõ reményeket.}
{18500}{}{Embléma}
{18501}{}{A Testvériség címere. A fogaskerekek a hozzáértést, a kard a harcosságot, a szárnyak pedig a reményt jelentik.}
{18600}{}{'Elsõ szint' tábla}
{18601}{}{Arra gondolsz, hogy ez valószínûleg azt jelenti, hogy az épület elsõ szintjén vagy.}
{18700}{}{'Második szint' tábla}
{18701}{}{A komplexum második szintjén vagy. A tábla szerint.}
{18800}{}{'Harmadik szint' tábla}
{18801}{}{Minden bizonnyal a harmadik szinten vagy az egész kócerájon belül.}
{18900}{}{'Negyedik szint' tábla}
{18901}{}{Kétségtelen, hogy ez a negyedik szintet jelzi.}
{19000}{}{Emeletes ágy}
{19001}{}{Egy katonai emeletes ágy. Nagyon durvának látszik. Sõt, úgy tûnik, hogy még egy pénzérme is visszapattanna a takarókról.}
{19100}{}{Emeletes ágy}
{19101}{}{Katonásan rendrevágott ágy. Eléggé kényelmetlennek tûnik. Ezen kívül a lepedõk is feltûnõen keményre vannak vasalva.}
{19200}{}{Emeletes ágy}
{19201}{}{A katonák rendszeresített fekhelye. Elsõ látásra nagyon barátságtalan. Második látásra sem változott meg a véleményed.}
{19300}{}{Láda}
{19400}{}{Nuka-Cola automata}
{19401}{}{A gép oldalán lévõ hirdetés a híres üdítõt reklámozza.}
{19500}{}{Fal}
{19600}{}{Csapóajtó}
{19601}{}{Egy nagyon rafinált csapóajtó.}
{19700}{}{Nyílás}
{19701}{}{A nyílásban levõ létra az ismeretlen sötétségbe vezet. Jujj, mindjárt beviz, Elek.}
{19800}{}{Oltár}
{19801}{}{Ez egy oltár.}
{19900}{}{Szószék}
{19901}{}{Az emberek e mögül szoktak beszédet tartani. Van egy kis hely rajta az elõre megírt beszédeknek.}
{20000}{}{Pad}
{20001}{}{Pontosan úgy néz ki, mint amire számítottál. Nincs rajta az égvilágon semmi különös.}
{20100}{}{Útjelzõ}
{20101}{}{A tábla már egy kissé berozsdált.}
{20200}{}{Útjelzõ}
{20201}{}{A ráerõsített táblát kezdi ellepni a rozsda.}
{20300}{}{Útjelzõ}
{20301}{}{Kicsit rozsdás a táblája.}
{20400}{}{Útjelzõ}
{20401}{}{A rajta lévõ feliratot már kezdi megenni az itteni levegõ.}
{20500}{}{Útjelzõ}
{20501}{}{Úgy látszik, ez a tábla nem nagyon bírja a környezetét. Csupa rozsda.}
{20600}{}{Régi matrac}
{20601}{}{Ez egy öreg, viharvert matrac. Úgy véled, valami rovarféle szörnyeteg él benne.}
{20700}{}{Régi matrac}
{20701}{}{Még ha meg is próbálnál aludni ezen a valamin, lehet, hogy nem lennél egyedül.}
{20800}{}{Ágy}
{20801}{}{Egy kihúzható ágy. Valahonnan máshonnan származik.}
{20900}{}{Ágy}
{20901}{}{Ez az ágy kihúzható. Valahonnan ki lett hajítva.}
{21000}{}{Ágy}
{21001}{}{Az ez ágy már látott jobb napokat (és valószínûleg éjjeleket is.)}
{21100}{}{Ágy}
{21101}{}{Közelebbrõl megvizsgálva, úgy veszed észre, hogy az ágynemût már nagyon-nagyon régen nem húzták újra.}
{21200}{}{Ágy}
{21201}{}{Ezen a jól ismert fekvõ-alkalmatosságon néhány kétes eredetû folt éktelenkedik.}
{21300}{}{Ágy}
{21301}{}{Ez az ágy már látott egy s mást. Valami bizonyára végigkúszott a matracok között és ágyban, párnák közt halt meg...}
{21400}{}{Könyvespolc}
{21500}{}{Könyvespolc}
{21600}{}{Könyvespolc}
{21700}{}{Könyvespolc}
{21800}{}{Könyvespolc}
{21900}{}{Könyvespolc}
{22000}{}{Ládák}
{22001}{}{Ezeket a ládákat már kikezdte az idõjárás.}
{22100}{}{Ládák}
{22101}{}{Úgy tûnik, semmi említésre méltó nincs ezekben a ládákban.}
{22200}{}{Ládák}
{22201}{}{Úgy látszik, rengeteg felesleges idõd van, hogy még e szétmálló roncs vizsgálatára is ráérsz.}
{22300}{}{Ládák}
{22301}{}{A ládákat annyira megviselte az idõjárás, hogy mindjárt szétesnek.}
{22400}{}{Autó}
{22401}{}{Ez az automobil rettentõen néz ki. Gondolni se merj arra, hogy egyszer majd üzemképes lesz!}
{22500}{}{Autó}
{22501}{}{Ezt a rozsdás fémdarabot már nem lehet helyrerakni.}
{22600}{}{Autó}
{22601}{}{Minden jel arra utal, hogy ez a jármû már többet nem fog közlekedni. De tényleg.}
{22700}{}{Autó}
{22701}{}{Semmi esély arra, hogy ezt a szemétnek is alig nevezhetõ valamit valaki, valaha is vezetni fogja.}
{22800}{}{Autó}
{22801}{}{Még ha az Év autószerelõje hirtelen melletted is teremne, akkor se tudnátok megjavítani ezt a rozsdahegyet.}
{22900}{}{Szék}
{22901}{}{Egy kényelmes szék.}
{23000}{}{Szék}
{23001}{}{Ennek a széknek már leülték a fedele javát.}
{23100}{}{Szék}
{23101}{}{Ez a szék már penészes és mocskos. Ráadásul szaglik is rendesen, mint ahogy azt sejthetted.}
{23200}{}{Szék}
{23201}{}{Ez a szék szétesõben van. Nem kell már neki sok.}
{23300}{}{Szék}
{23301}{}{Ha valaki fizetne érte, talán akkor megfontolnád, hogy leülj erre a székre.}
{23400}{}{Szék}
{23401}{}{Olyan, mint egy régi irodai szék, és még több év elteltével is mindig nagyon jól néz ki.}
{23500}{}{Szék}
{23501}{}{Ez egy régi irodai szék. Lehet, hogy elbírna még egy embert is.}
{23600}{}{Szék}
{23601}{}{Ez az irodai szék már láthatott jobb napokat is. De most nem több egy rakás szemétnél.}
{23700}{}{Szék}
{23701}{}{Ez a szék úgy néz ki, mintha egy temetkezési vállalkozónál láttad volna. Halott.}
{23800}{}{Asztal}
{23900}{}{Asztal}
{24000}{}{Öltözõasztal}
{24100}{}{Öltözõasztal}
{24200}{}{Öltözõasztal}
{24300}{}{Tûzcsap}
{24301}{}{Ez egy tûzcsap. A Menedékben már megszokott tûzoltókészülékek hiányában lehet, hogy ezekre még szükséged lehet a tüzek oltásában.}
{24400}{}{Lámpaoszlop}
{24401}{}{Ez a lámpaoszlop még mindig mûködõképesnek látszik. Hihetetlen, de van ami még mûködik errefelé.}
{24500}{}{Lámpaoszlop}
{24501}{}{Ez a lámpaoszlop már soha többé nem fog világítani.}
{24600}{}{Lámpaoszlop}
{24601}{}{Ez egy üzemelõ lámpaoszlop. Éjjelente sápadt, bársonyos fényt áraszt, amirõl neked az égvilágon semmi nem jut eszedbe.}
{24700}{}{Lámpaoszlop}
{24701}{}{Egy törött lámpaoszlop. Nem lehet megjavítani.}
{24800}{}{Lámpaoszlop}
{24801}{}{Ez a lámpa világít.}
{24900}{}{Lámpaoszlop}
{24901}{}{Az oszlopon lévõ lámpa összetört a javítás során.}
{25000}{}{Lámpaoszlop}
{25001}{}{Ez egy mûködõ lámpaoszlop.}
{25100}{}{Kapu}
{25101}{}{A kapu le van zárva és a retesz igen robusztusnak tûnik.}
{25200}{}{Szemét}
{25201}{}{Szemét, mi más?}
{25300}{}{Szemét}
{25301}{}{Kétségtelen, hogy ez csak szemét.}
{25400}{}{Szemét}
{25401}{}{Haszontalan szemét. Nem is tudom, az ember miért tartja rajta a szemét.}
{25500}{}{Szemét}
{25501}{}{Szemét, szemét, szemét!}
{25600}{}{Szemét}
{25601}{}{Kicsinálták Kennyt! Szemetek!}
{25700}{}{Postaláda}
{25701}{}{A postaláda üres. Van egy olyan érzésed, hogy már jó ideje.}
{25800}{}{Ajtó}
{25801}{}{Egy nagyon finoman megmunkált fa ajtó, tûrhetõ állapotban.}
{25900}{}{Ajtó}
{25901}{}{Hosszú idõk munkája, és még mindig áll.}
{26000}{}{Ajtó}
{26001}{}{Ezen a fából készült ajtón még látszik, hogy egy ügyeskezû mesterember készítette.}
{26100}{}{Ajtó}
{26101}{}{Az ajtót fából készítették és csodálatosan kimunkált. Kitûnõ állapotban van.}
{26200}{}{Pad}
{26201}{}{Ez a fapad menten az atomjaira hullik szét.}
{26300}{}{Pad}
{26301}{}{A pad nagyon gondozatlan, elég viseltesnek és átázottnak látszik.}
{26400}{}{Pad}
{26401}{}{Egy fából ácsolt pad, ami engedett a kornak és a kínzásnak.}
{26500}{}{Újságautomata}
{26501}{}{A gépben egy fia újság sincs.}
{26600}{}{Újságautomata}
{26601}{}{Újságok nélkül.}
{26700}{}{Újságautomata}
{26701}{}{Tök üres.}
{26800}{}{Újságautomata}
{26801}{}{Sajnos, az automata gyomra egyetlen napilapot sem rejt.}
{26900}{}{Újságautomata}
{26901}{}{Belekukkantasz, de nem látsz benne semmit.}
{27000}{}{Újságautomata}
{27001}{}{Kong az ürességtõl. Pedig úgy tûnik, hogy régebben olcsó szexlapok voltak benne.}
{27100}{}{Szemét}
{27101}{}{Egy matrac, ami szinte alig felismerhetõ. Még a patkányok se aludnának rajta vagy épp' benne.}
{27200}{}{Szemét}
{27201}{}{Egy franciaágy matraca, ami már biztos megélt a mainál szebb napokat is.}
{27300}{}{Szemét}
{27301}{}{Egy halom koszos és korhadt fa. Még kilóra se tudnád eladni.}
{27400}{}{Szemét}
{27401}{}{Egy rakat fa, benne néhány rozsdás, hajlott szöggel.}
{27500}{}{Dobozok}
{27501}{}{Rengeteg kartondoboz egymáson. El se tudod képzelni, hogyan bírták ki ilyen sokáig.}
{27600}{}{Dobozok}
{27601}{}{Kartondobozok, jó nagy halomban.}
{27700}{}{Szemét}
{27701}{}{Elsõre szemétnek látszik, de neked úgy rémlik, mintha valaha, mielõtt a természet ki nem kezdte volna, matrac volt.}
{27800}{}{Kövek}
{27900}{}{Kövek}
{28000}{}{Kövek}
{28100}{}{Kavicsok}
{28101}{}{Sok kavics és néhány nagyobb kõdarab. Vigyázz!}
{28200}{}{Lefolyó}
{28201}{}{Egy porcelánból készült lefolyó, ami már rég nem mûködik.}
{28300}{}{Lefolyó}
{28301}{}{Törött porcelán lefolyó. Az alján egy poshadt vízû tócsa, amiben egy döglött patkány úszkál.}
{28400}{}{Lefolyó}
{28401}{}{Ez a lefolyó már nem használható. Ezt a közepén éktelenkedõ óriási repedésbõl tudtad megállapítani.}
{28500}{}{Lefolyó}
{28501}{}{Egy lepukkant porcelán remekmû. A kagylóban egy döglött patkány fürdõzik a barna vízfelszínen.}
{28600}{}{Stoptábla}
{28601}{}{Egy vörös tábla, amin marha nagy betûkkel a "STOP" felirat van felírva.}
{28700}{}{Stoptábla}
{28701}{}{A tábla alapszíne vörös, de egy jól látható "STOP" felirat is díszíti. Ezenkívül még egy extra golyónyom is látható rajta.}
{28800}{}{Stoplámpa}
{28801}{}{Egy õsrégi jelzõlámpa.}
{28900}{}{Stoplámpa}
{28901}{}{Ez nem más, mint egy átlagos lámpa, nagy stop-hatással.}
{29000}{}{Stoplámpa}
{29001}{}{Ezt valaha még jármûvek irányítására használták.}
{29100}{}{Utcai lámpa}
{29101}{}{Ez a lámpa ad némi világosságot az éj leszálltával, vagy a sötétebb területeken.}
{29200}{}{Utcai lámpa}
{29201}{}{Az utca fényét ez a lámpa adja, miután beköszöntött az éjszaka, vagy ha egyéb okból sötét lenne.}
{29300}{}{Utcai lámpa}
{29301}{}{Ez itt a fény az éjszakában.}
{29400}{}{Utcai lámpa}
{29401}{}{Ez a valami fénylik a sötétben errefelé.}
{29500}{}{Utcai lámpa}
{29501}{}{A lámpa elméletileg az utcát világítja meg éjszaka vagy ha egyszerûen túl sötét lenne. Sajnos elromlott.}
{29600}{}{Utcai lámpa}
{29601}{}{A lámpa kiégett, így nemes feladatát már nem tudja kellõen ellátni.}
{29700}{}{Utcai lámpa}
{29701}{}{Ettõl a lámpától akár sötét is lehetne. Rá se ránt.}
{29800}{}{Utcatábla}
{29801}{}{Ezen a táblán elméletileg az utca nevének kellene lennie, de a betûk már a feledésbe vesztek.}
{29900}{}{Utcatábla}
{29901}{}{A táblán valamelyik utca neve szerepelne, de sajnos ezt már nem lehet elolvasni.}
{30000}{}{Asztal}
{30001}{}{Fából tákolt asztal, még mindig tûrhetõ állapotban.}
{30100}{}{Asztal}
{30101}{}{Egy fából összeállított asztal, de még mindig áll.}
{30200}{}{Asztal}
{30201}{}{Egy fa asztal, eléggé ramaty a kinézete.}
{30300}{}{Asztal}
{30301}{}{Ez is egy faasztal lenne, bár a teteje mûanyagból van, ami már egy ideje meg van repedve.}
{30400}{}{Asztal}
{30401}{}{Fából készült és hányászöldre van festve. Nincs mit javítani rajta.}
{30500}{}{Asztal}
{30501}{}{Úgy néz ki, mint egy régi dohányzóasztal, közel a földhöz. Nyilván az apró termetû mutánsok számára készült.}
{30600}{}{Asztal}
{30601}{}{Egy koros dohányzóasztal. Az asztal lapja alacsonyan van. talán azért, hogy a kisebb méretû lények is fel tudják érni.}
{30700}{}{WC}
{30701}{}{Mivel a csészének le vannak törve a szélei, igen kényelmetlen lenne a trónolás.}
{30800}{}{WC}
{30801}{}{A csésze eltört.}
{30900}{}{WC}
{30901}{}{Pfúj! Aki legutoljára használta, elfelejtette lehúzni!}
{31000}{}{WC}
{31001}{}{A WC ülõkéje eltört, így ha nõ vagy, tutira használhatatlan a számodra.}
{31100}{}{Szemét}
{31101}{}{Néhány szétrohadt csõ bukkan elõ a mocsokból. Semmi látnivaló nincs itt. Eredj tovább!}
{31200}{}{Szemét}
{31201}{}{Egy-két törött üveg és más tropára ment szemétdarabok.}
{31300}{}{Szemét}
{31301}{}{Nem látsz mást, csak üvegcserepeket és még több szemetet.}
{31400}{}{Szemét}
{31401}{}{Egy csõ, ami ketté van törve. Úgy látszik, csak addig rozsdásodott, míg össze nem szakadt a saját súlya alatt.}
{31500}{}{Szemetes}
{31501}{}{Egy szeméttároló. Ezt lehet olvasni a rajta lévõ címkén: "Tartsuk tisztán az utcáinkat!"}
{31600}{}{Fa}
{31601}{}{Egy kiszáradt fa.}
{31700}{}{Fa}
{31701}{}{Egy tuskó. Nincs rajta semmi spéci. Bár, ami azt illeti, ez az egyik legérdekesebb dolog, amin valaha is rajtafelejtetted a szemed.}
{31800}{}{Fa}
{31801}{}{Ez a fa már nem él.}
{31900}{}{Fa}
{32000}{}{Fa}
{32100}{}{Fa}
{32200}{}{Teherautó}
{32300}{}{Teherautó}
{32301}{}{A dízeles teherautó utolsó maradványai. Ez a nagy rakás fém már soha nem fog tudni mozogni.}
{32400}{}{Teherautó}
{32401}{}{Ennek a teherautónak már rég lõttek. Jó régen.}
{32500}{}{Fürdõkád}
{32501}{}{A fürdõkád meg van repedve és alig nem több, mint egy rakás ócskavas.}
{32600}{}{Fürdõkád}
{32601}{}{Ahogy alaposabban végigméred, arra a következtetésre jutsz, hogy ebben te bizony nem fürödnél.}
{32700}{}{Vizelde}
{32701}{}{Na, ide lehet pisilni.}
{32800}{}{Vizelde}
{32801}{}{Ez egy vizelde lenne. Hehehe.}
{32900}{}{Vizelde}
{32901}{}{Mindenki ide vizel, de amúgy semmi érdekes.}
{33000}{}{Vizelde}
{33001}{}{Egy könnyítési lehetõség a játékban.}
{33100}{}{Víztartály}
{33101}{}{Ebben az óriási tartályban folyadékot tárolnak. Esetünkben, (feltételezéseid szerint) ez eredetileg víztartály lenne.}
{33200}{}{Ajtó}
{33201}{}{Alapanyaga: fa. Különleges ismertetõjele: nincs.}
{33300}{}{Ajtó}
{33301}{}{100% fa felhasználásával létrehozott ajtó. Ezen keresztül ki és be lehet menni az épületbe.}
{33400}{}{Fali lámpa}
{33401}{}{Úgy látszik, ez a lámpa még mûködõképes.}
{33500}{}{Fali lámpa}
{33501}{}{A lámpa törött. Nagyon nem lep meg.}
{33600}{}{Fali lámpa}
{33601}{}{Még mûködik.}
{33700}{}{Fali lámpa}
{33701}{}{Törött lámpa. Ez nem okozott neked túl nagy megrökönyödést.}
{33800}{}{Fali lámpa}
{33801}{}{Szerencsére még nem romlott el.}
{33900}{}{Fali lámpa}
{33901}{}{El van törve. És?}
{34000}{}{Fali lámpa}
{34001}{}{OK. Be lehet kapcsolni.}
{34100}{}{Fali lámpa}
{34101}{}{Törött. Nem csoda, hogy nem mûködik.}
{34200}{}{Tábla}
{34201}{}{Valaha ez egy "Elsõbbségadás kötelezõ" tábla volt.}
{34300}{}{Tábla}
{34301}{}{A szövege már kifakult, de te még mindig elsõbbségadásra kötelezed a világot.}
{34400}{}{Titkos-Hexagon (Auto Inviso)}
{34401}{}{Ha ezt olvasod, jelentsd a készítõknek!}
{34500}{}{Padló}
{34600}{}{Ajtó}
{34601}{}{Egy gazdagon díszített fa ajtó. Biztos társadalmi munka keretében készült.}
{34700}{}{Pad}
{34701}{}{Ezt az ülést nagy betontömbök tartják. Igaz, ez nem annyira fontos. Te vagy az egyetlen, aki ezt észrevette.}
{34800}{}{Lépcsõ}
{34801}{}{Felfelé vezet.}
{34900}{}{Lépcsõ}
{34901}{}{Itt felfele lehet menni.}
{35000}{}{Lépcsõ}
{35001}{}{Ezzel egyel magasabb emeletre jut az ember.}
{35100}{}{Lépcsõ}
{35101}{}{Fel.}
{35200}{}{Lépcsõ}
{35201}{}{Felfelé.}
{35300}{}{Lépcsõ}
{35301}{}{Feleslegesen feleselek, de ezen felfele mehetsz fel. Eh.}
{35400}{}{Lépcsõ}
{35401}{}{Ahogy nézed, ez a feljebb lévõ emeletre visz.}
{35500}{}{Lépcsõ}
{35501}{}{Lehet, hogy nem látszik, de ez felfelé visz.}
{35600}{}{Lépcsõ}
{35601}{}{Lefele vezet.}
{35700}{}{Fal}
{35701}{}{Most a katedrális oldalát látod.}
{35800}{}{Fal}
{35801}{}{Éppen a katedrális oldalfalát bámulod.}
{35900}{}{Fal}
{35901}{}{Ez a katedrális fala kívülrõl.}
{36000}{}{Fal}
{36001}{}{A katedrális külsõ falfelületét láthatod.}
{36100}{}{Függöny}
{36101}{}{Úgy látszik, ezt a függönyt igen egyszerû okból készítették, de minden nagyon jól leplezhetõ vele.}
{36200}{}{Függöny}
{36201}{}{Nem túl bonyolult az oka, miért csinálták ezt a függönyt. Bár a vasfüggönyt meg se közelíti.}
{36300}{}{Tál}
{36301}{}{Egy precíz és kitartó munkával készített fatál. Valószínûleg a gabona õrlésére és leválogatására szolgál.}
{36400}{}{Tál}
{36401}{}{Hát ez bizony fatál is.}
{36500}{}{Fazék}
{36501}{}{Nagyon ügyes volt, aki csinálta.}
{36600}{}{Növény}
{36601}{}{Mintha egy mutáns káposzta lenne. Láthatólag kedvez neki a meleg idõjárás.}
{36700}{}{Növény}
{36701}{}{Úgy néz ki, mint egy mutálódott káposzta. Nagyon jót tesz neki a meleg idõ.}
{36800}{}{Talicska}
{36801}{}{Egyszerû, de hasznos mezõgazdasági eszköz.}
{36900}{}{Növény}
{36901}{}{Egy mutáns kukoricacsutka. Ezek a feltételek kedvezõleg hatnak rá.}
{37000}{}{Növény}
{37001}{}{Ez egy csutka, amin mutáció lépett fel. Szépen növekszik.}
{37100}{}{Növény}
{37101}{}{Kukoricacsutka, mutálódva. Elég nagyra nõtt még ezen a helyen is.}
{37200}{}{Fazék}
{37201}{}{Egy nagyon szépen formázott agyagedény.}
{37300}{}{Gereblye}
{37301}{}{Ez a gereblye azé, akié. Nem is gondolsz arra, hogy használd.}
{37400}{}{Gereblye}
{37401}{}{Ennek a gereblyének is nyilván megvan a maga gazdája. Eszed ágában sincs hozzányúlni.}
{37500}{}{Gereblye}
{37501}{}{Ez a gereblye csak látszólag gazdátlan. De mit érdekel ez téged...?}
{37600}{}{Szõnyeg}
{37601}{}{Egy normál szõnyeg. Valószínûleg tehetséges kezek terméke.}
{37700}{}{Szõnyeg}
{37701}{}{Szõnyeg. Nagyon gondosan szõtt.}
{37800}{}{Szõnyeg}
{37801}{}{Ez egy szõnyeg, semmi több. A szövõ bizonyára értett a szakmájához.}
{37900}{}{Ásó}
{37901}{}{Ehhez az ásóhoz nyilván tartozik valaki. De nem is annyira fontos.}
{38000}{}{Ásó}
{38001}{}{Mint minden egyéb ásót, ezt is ásónak nézi valaki. Te nem tartozol közéjük.}
{38100}{}{Ásó}
{38101}{}{Ásó, hozzátartozik egy paraszt hátsó. Nem a te hátsód.}
{38200}{}{Váza}
{38201}{}{Nagyon aranyos agyagváza.}
{38300}{}{Kút}
{38301}{}{Egy tipikus kút, amit az ember a semmi közepén találhat.}
{38400}{}{Rúd}
{38401}{}{Nincs jurta rúd nélkül.}
{38500}{}{Rúd}
{38501}{}{Ez a jurta egyik támasztéka.}
{38600}{}{Rúd}
{38601}{}{Ami a sátornak a sátorvas, az a rúd ennek a jurtának.}
{38700}{}{Rúd}
{38701}{}{Ez a rúd tartja a jurtát.}
{38800}{}{Rúd}
{38801}{}{Ne vedd el ezt a rudat, mert a jurta azonnal összeomlik.}
{38900}{}{Rúd}
{38901}{}{Bonyolult világunkba e rúd egy jurta megtartását kapta hõsi feladatául.}
{39000}{}{Menedék-ajtó}
{39001}{}{Ez a Menedék-ajtó mostantól már nem több, mint egy rakás fémdarab.}
{39100}{}{Fal}
{39101}{}{A nagy Menedék-ajtó irányító mechanizmusa megsérült a javítás során.}
{39200}{}{Dúc}
{39201}{}{Ez a dúc támasztja alá a védõfalat.}
{39300}{}{Dúc}
{39301}{}{"Ha jönnek a galambok, lesz pár dúc."}
{39400}{}{Dúc}
{39401}{}{Segítségével ez a fal nem omlik le egykönnyen.}
{39500}{}{Dúc}
{39501}{}{Az, hogy a berlini fallal ellentétben ez még mindig áll, ennek a dúcnak köszönhetõ.}
{39600}{}{Fém hordó}
{39601}{}{Egy rozsdaette, fémes kongású hordó. Persze hogy üres.}
{39700}{}{Fém hordó}
{39701}{}{Ebbõl a döngõ hangzásból ítélve a hordó tökre üres.}
{39800}{}{Fém hordók}
{39801}{}{Ezek a hordók túlságosan öblös hangot adnak ahhoz, hogy legyen bennük valami.}
{39900}{}{Fém hordók}
{39901}{}{Nem sok minden lehet benne, mert a hang kényelmesen cikázik fel s alá a belsejében.}
{40000}{}{Szellõztetõ}
{40001}{}{Ez a szellõztetõ látszólag egy földalatti építményt lát el levegõvel.}
{40100}{}{Láda}
{40101}{}{Egy faláda. Bár nehéz lenne annak nézni ebben az állagában.}
{40200}{}{Láda}
{40201}{}{Egy egyszerû láda, ami fából van. Elég jól tartja magát.}
{40300}{}{Láda}
{40301}{}{Ez a láda összerogyott a saját súlya alatt.}
{40400}{}{Asztal}
{40401}{}{Egy sima asztal, számítógéppel.}
{40500}{}{Asztal}
{40501}{}{Ez egy asztal, amin egy számítógép van.}
{40600}{}{Ajtó}
{40601}{}{Egy fából készített ajtó, még felismerhetõ állapotban.}
{40700}{}{Barlangnyílás}
{40701}{}{Irdatlan sok kõ, sokkal több, mint amennyit könnyedén arrébb lehetne rakni.}
{40800}{}{Autó}
{40801}{}{Ezt az elsüllyedt autót már nem lehet megszerelni.}
{40900}{}{Autó}
{40901}{}{Az autó egy kicsit már vizes, és nagyon már szerelni se lehet.}
{41000}{}{Autó}
{41001}{}{A jármûvet elég bénán parkolták le. Sajnos, éppen javítják.}
{41100}{}{Szemét}
{41101}{}{Teljesen szétáztatta a szennyezett tengervíz.}
{41200}{}{Szemét}
{41201}{}{Majdnem elmosta a víz.}
{41300}{}{Szemét}
{41301}{}{Valaki ügyesen összeválogatott egy rakat haszontalan szemetet.}
{41400}{}{Csövek}
{41401}{}{Ezek a csövek szállítják az üzemanyagot a földalatti tartályból a garázsba. Már régóta nem használták õket.}
{41500}{}{Csõ}
{41501}{}{Valamikoron egy föld alá temetett tartályból szállították a naftát a garázs felé. Az utóbbi idõben viszont nem használták.}
{41600}{}{Csövek}
{41601}{}{A csövek egy földalatti tankból hozták fel a benzint egykor. Már régen nem használják régen.}
{41700}{}{Liftakna}
{41701}{}{A liftrendszer része.}
{41800}{}{Liftakna}
{41801}{}{Egy liftakna, ami mélyen a földben gyökeredzik. Lerobbant.}
{41900}{}{Lift}
{41901}{}{Egy lift. Ezzel lehet közlekedni lefelé és felfelé a szintek között.}
{42000}{}{Liftakna}
{42001}{}{Liftakna, ami mélyen a földben található. Komoly javításra szorul.}
{42100}{}{Liftajtó}
{42101}{}{Ez az ajtó vezet a lift motorjához. Ha használni akarod a liftet, elõször ezt az ajtót kell kinyitnod.}
{42200}{}{Csõ}
{42201}{}{Egy fémcsõ. A további részletek már nem fontosak.}
{42300}{}{Piszok}
{42400}{}{Doboz}
{42500}{}{Doboz}
{42600}{}{Doboz}
{42700}{}{Doboz}
{42800}{}{Kövek}
{42801}{}{Apró kõpiramis. Nem túl izgalmas.}
{42900}{}{Kövek}
{42901}{}{Kövek egy rakáson. Nem lényeges.}
{43000}{}{Kövek}
{43001}{}{Kövek, kis csoportban. Egy cseppet sem érdekesek a számodra.}
{43100}{}{Kövek}
{43101}{}{Sok kavics együtt.}
{43200}{}{Kövek}
{43201}{}{Sok kis kõdarab sokra megy. Ha lenne lábuk...}
{43300}{}{Kövek}
{43301}{}{Kicsi a rakás. Kõ még valaki.}
{43400}{}{Kövek}
{43401}{}{Talán, ha egymás tetejére állítanád ezeket a köveket...}
{43500}{}{Kövek}
{43501}{}{Nagyon kicsi ez a rakás.}
{43600}{}{Menedékajtó}
{43601}{}{E Menedékajtó nagyon hasonlít a 13-as Menedék egyik ajtajához. Azonban ezt itt kikapcsolták.}
{43700}{}{Ajtó}
{43701}{}{Egy precízen elkészített fa ajtó, megerõsítve egy-két dekoráló fémkapoccsal, ami majdnem hipnotikus kinézetet ad neki.}
{43800}{}{Ajtó}
{43801}{}{Gondosan készített fa anyagú ajtó, némi fémmel kimerevítve, s ettõl egy kicsit meglepõen néz ki.}
{43900}{}{Kádak}
{43901}{}{Mindenféle kádak. Nem vagy benne teljesen biztos, de ezekben az óriási kádakban valami zöldes trutymót látsz, ami aligha tûnik fontosnak.}
{44000}{}{Kádak}
{44001}{}{Kádak. Nem vagy róla meggyõzõdve, be amit ezekben a kádakban látsz, nem feltétlenül információdúsak.}
{44100}{}{Kádak}
{44101}{}{Kádhegyek. A bennük lévõ zöldes folyadék inkább hányingert kelt benned, mint hiányingert.}
{44200}{}{Kádak}
{44201}{}{Több, különbözõ fajta kád. Van ezekben mindenféle zöldes trutyi, de rövid elemzésed alapján nem tûnnek túl érdekesnek.}
{44300}{}{Kádak}
{44301}{}{Sok fajta kádat látsz. Bár pontosan nem is tudod, miket látsz, mindenesetre nem tûnnek nagyon izgalmasnak.}
{44400}{}{Kádak}
{44401}{}{Medencékhez hasonlítanak. Mintha valami zöldes genny úszkálna bennük... Ah, inkább felejtsd el!}
{44500}{}{Kádak}
{44501}{}{Jó sok. Gusztus híján nem sikerült túl sokat kiderítened a tartalmukról.}
{44600}{}{Kádak}
{44601}{}{Akad egy pár darab. Nem teljesen egyértelmû, mik is ezek valójában, de a bennük kavargó 'anyag' nem túl bíztató.}
{44700}{}{Fal}
{44800}{}{Ajtó}
{44801}{}{Egy biztonsági ajtó. Nagyon páncélozottnak tûnik.}
{44900}{}{Nukleáris robbanófej}
{45000}{}{Kút}
{45001}{}{A pusztaságban található átlagos kútfajta.}
{45100}{}{Pókerasztal}
{45101}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{45200}{}{Pókerasztal}
{45201}{}{Most nincs idõ pókerezni.}
{45300}{}{Pókerasztal}
{45301}{}{Régebben sokat pókereztél, talán ha Fortuna most is melléd szegõdne...}
{45400}{}{Pókerasztal}
{45401}{}{Kártyák meg zsetonok, na meg a pókerarcok. Ez a póker.}
{45500}{}{Pókerasztal}
{45501}{}{Te akarsz lenni a közkedvelt Pókerember?}
{45600}{}{Pókerasztal}
{45601}{}{No komment.}
{45700}{}{Pókerasztal}
{45701}{}{Érdekes, hogy a pókernek még mindig van helye.}
{45800}{}{Pókerasztal}
{45801}{}{Cinkelt lapok kíméljenek!}
{45900}{}{Pókerasztal}
{45901}{}{Gyors és egyszerû pénznyerési lehetõség. Csak eléggé kockázatos.}
{46000}{}{Pókerasztal}
{46001}{}{Tény, hogy ez egy pókerezõ asztal.}
{46100}{}{Kõ}
{46101}{}{Egy apró kövecske, teljesen lényegtelen a történet szempontjából.}
{46200}{}{Kõ}
{46300}{}{Kõ}
{46400}{}{Kõ}
{46500}{}{Nyerõautomata}
{46501}{}{Csak a pénzt nyeli. Így van beállítva.}
{46600}{}{Nyerõautomata}
{46601}{}{Ezzel aztán lehet szerencsétlenkedni.}
{46700}{}{Ajtókeret}
{46800}{}{Lift}
{46900}{}{Lift}
{47000}{}{Liftajtó}
{47100}{}{Ablak}
{47101}{}{Üveg helyett ebben az ablakban burkolólap van.}
{47200}{}{Ablak}
{47201}{}{Úgy tûnik, az üveget kispórolták, mert a helyére valami lapot raktak.}
{47300}{}{Ablak}
{47301}{}{Az ablak teljesen normális, attól eltekintve, hogy valaki alaposan beburkolta.}
{47400}{}{Ablak}
{47401}{}{Mondhatnánk, hogy ez egy vakablak. Elvégre még szeme sincs.}
{47500}{}{Ajtó}
{47501}{}{Ez egy görgõs fém ajtó, amit belülrõl lereteszeltek.}
{47600}{}{Ajtó}
{47601}{}{Kerekeken mozgó, óriási, acélajtó. Belülrõl van bezárva.}
{47700}{}{Ajtó}
{47701}{}{Nagy fémkerekes ajtó, amit a belsõ oldaláról lezártak. A felirat: "CSAK BERAKODÁS"}
{47800}{}{Ajtó}
{47801}{}{Ez egy óriási, kerekes fém ajtó. A belsõ oldala felõl van bezárva.}
{47900}{}{Ajtó}
{47901}{}{Ez a bazi nagy fém ajtó be van zárva. Méghozzá belülrõl.}
{48000}{}{Ajtó}
{48001}{}{Az ajtót belülrõl lezárták. Amúgy a eltolható fém ajtó lenne. Ez van ráírva: "CSAK BERAKODÁS"}
{48100}{}{Ajtó}
{48101}{}{Ez az ajtó gyanúsan emlékeztet egy raktár ajtajára.}
{48200}{}{Ajtó}
{48201}{}{Hm, ezt az ajtót mintha egy raktárházon láttad volna utoljára.}
{48300}{}{Szélkakas}
{48301}{}{Ez a szélkakas segít a helybelieknek elõre jelezni az idõt.}
{48400}{}{Oltár}
{48401}{}{Egy primitív oltár, amit fából készítettek, majd lefestettek.}
{48500}{}{Pódium}
{48501}{}{Ez egy normál katedra, ideális a felszólalásokra.}
{48600}{}{Oltár}
{48700}{}{Monitor}
{48701}{}{Egy nagy fekete-fehér monitor. A vétel elég jó ahhoz képest, hogy épületen belül van és nincs antennája.}
{48800}{}{Monitor}
{48801}{}{Egy óriási monitor, ami FF (Fekete-Fehér). Egy csuhás figurát látsz, amint valamilyen vallásos imádságot mormol lázasan.}
{48900}{}{Erõtér}
{48901}{}{Ez egy nagyon erõs energiamezõ.}
{49000}{}{Erõtér}
{49001}{}{Egy hihetetlenül nagy erejû energiamezõ.}
{49100}{}{Erõtér}
{49101}{}{Az egész mezõt áthatolhatatlan energia szövi át.}
{49200}{}{Erõtér}
{49201}{}{Ezen az energiamezõn nem lehet átjutni.}
{49300}{}{Asztal}
{49301}{}{Egy hétköznapi faasztal.}
{49400}{}{Asztal}
{49401}{}{Az asztal fából készült és nincs benne semmi különös.}
{49500}{}{Asztal}
{49501}{}{Fából van, ennyi.}
{49600}{}{Asztal}
{49601}{}{Teljesen hétköznapi asztal, amit fából csináltak.}
{49700}{}{Asztal}
{49701}{}{Olyan, akár egy normális asztal, amit fából készítettek.}
{49800}{}{Asztal}
{49801}{}{Egy teljesen átlagos, fából készült asztal.}
{49900}{}{Polc}
{50000}{}{Polc}
{50100}{}{Polc}
{50200}{}{Polc}
{50300}{}{Polc}
{50400}{}{Polc}
{50500}{}{Oltár}
{50501}{}{Egy nagyon egyszerû oltárféleség, ami festett fából készült.}
{50600}{}{Oltár}
{50601}{}{Fából lett összerakva és ezután lefestették.}
{50700}{}{Oltár}
{50701}{}{Nagyon primitív faoltár, egyszerûen le van festve.}
{50800}{}{Oltár}
{50801}{}{Nem egy túlcizellált munkadarab. Csak festék és fa.}
{50900}{}{Kõdarab}
{50901}{}{Ezt a nagy rakás kõtörmeléket a tetõ beomlott része alkotja. A köteled visszavezet a felszínre.}
{51000}{}{Könyvespolc}
{51100}{}{Könyvespolc}
{51200}{}{Könyvespolc}
{51300}{}{Könyvespolc}
{51400}{}{Könyvespolc}
{51500}{}{Könyvespolc}
{51600}{}{Asztal}
{51601}{}{Ez a nagy asztal fontosnak néz ki. Talán valami találkozót szoktak itt tartani?}
{51700}{}{Asztal}
{51701}{}{Egy fontosnak látszó asztal. Csak nem valami találka színhelye?}
{51800}{}{Asztal}
{51801}{}{Nagy asztal, nagy jelentõséggel. Hm, csak nem a törzshely?}
{51900}{}{Asztal}
{51901}{}{Ez asztal bizonyára a játék egyik nagyon fontos momentuma. Talán nem is véletlenül?}
{52000}{}{Asztal}
{52001}{}{Nagy asztal. Valami találkozó szokott itt lenni?}
{52100}{}{Asztal}
{52101}{}{Egy jó nagy asztal, fontosnak látszik. Esetleg a fontos megbeszélések terepe?}
{52200}{}{Oltár}
{52201}{}{Egy oltár, amit az Acél Testvériség tervezett és készített (ki más?). A jelképük fémesen csillog rajta.}
{52300}{}{Oltár}
{52301}{}{Ezt az oltárt a Testvériség tagjai gyártották a saját terveik alapján. Az emblémájuk is látható rajta.}
{52400}{}{Oltár}
{52401}{}{Az Acél Testvériség tervei alapján az Acél Testvériség építette ezt az oltárt. Le se tagadhatnák, hiszen rajta a jelük.}
{52500}{}{Pad}
{52501}{}{Egy nagyon divatos, de annál kényelmetlenebb padka. A seggem majd' szétnyomta.}
{52600}{}{Pódium}
{52601}{}{Egy aranyos fa emelvény. Egy súgógép is bele van építve, ami a beszélõ felé néz.}
{52700}{}{Utánfutó}
{52701}{}{A karaván egyik utánfutója, amit egy korábban tropára ment automobil darabjaiból raktak össze.}
{52800}{}{Utánfutó}
{52801}{}{Ez az utánfutó a karaván egyik tagja. Teljesen környezetkímélõ módszerrel épült, kizárólag használt alkatrészekbõl.}
{52900}{}{Utánfutó}
{52901}{}{Ez az utánfutó a karavánhoz tartozik. Egy régi autótípust vélsz felismerni benne. Persze, hiszen abból készült.}
{53000}{}{Utánfutó}
{53001}{}{Egy lelkes szerelõ egy régi autó hozzáadásával konvertálta a karaván egyik utánfutójává.}
{53100}{}{Utánfutó}
{53101}{}{Elég költségkímélõ megoldás egy szétvert autó alkatrészeibõl karavánt építeni.}
{53200}{}{Utánfutó}
{53201}{}{Egy karaván utánfutója. Nem tévesztendõ össze a sajttal, bár ezt is sajtolták.}
{53300}{}{Szõnyeg}
{53301}{}{Egy gyakorlószõnyeg.}
{53400}{}{Szõnyeg}
{53401}{}{Ezen szoktak gyakorolni.}
{53500}{}{Szõnyeg}
{53501}{}{Egy szõnyeg, amin lehet gyakni és orolni is.}
{53600}{}{Szõnyeg}
{53601}{}{Aki itt elesik, az puhára esik; a pofája helyett.}
{53700}{}{Boksz-zsák}
{53701}{}{Ez egy IzomCsávó(tm) márkájú boksz-zsák.}
{53800}{}{Lépcsõzõgép}
{53801}{}{Gyakorlógép.}
{53900}{}{Lépcsõzõgép}
{54000}{}{Szobabicikli}
{54001}{}{Ezt lehet tekerni. Ehe.}
{54100}{}{Futópad}
{54101}{}{Eleve lehetetlen lenne... He?}
{54200}{}{Fekpad}
{54201}{}{Ezen aztán lehet nyomni! Jobb esetben a súlyt...}
{54300}{}{Fekpad}
{54301}{}{Ez az izompacsirták játékszere.}
{54400}{}{Palánk}
{54401}{}{Ezek a kemény palánkok jól össze vannak erõsítve.}
{54500}{}{Palánk}
{54501}{}{Sok megerõsített fapalánk erõsen összetákolva.}
{54600}{}{Rulettasztal}
{54601}{}{Tegye próbára a szerencséjét!}
{54700}{}{Rulettasztal}
{54701}{}{Nem az a ruszki fajta.}
{54800}{}{Rulettasztal}
{54801}{}{Talán hozhat egy kis pénzügyi fellendülést.}
{54900}{}{Rulettasztal}
{54901}{}{Rulett. A kártya mellett kedvelt pénznyerési lehetõség.}
{55000}{}{Rulettasztal}
{55001}{}{Nahát, látni itt ilyet is!}
{55100}{}{Hordó}
{55101}{}{Ezen az üres hordón a radioaktív lóhere látható az oldalára festve élénksárgával.}
{55200}{}{Hordó}
{55201}{}{Ebben a hordóban van valami sugárzó trutyesz. A radioaktív lóhere jele talán kicsit segít, hogy ez a trutymó vajon mi lehet.}
{55300}{}{Számítógép}
{55301}{}{Egy nagyon modern kinézetû számítógép.}
{55400}{}{Számítógép}
{55401}{}{Ez a számítógép nagyon modernnek tûnik.}
{55500}{}{Függõtartály}
{55501}{}{Valamiféle orvosi vagy kísérleti segédeszköz, olybá tûnik, hogy akár egy nagyobb méretû emberi testet is képes lenne tárolni.}
{55600}{}{Rossz függõtartály}
{55601}{}{Egy elromlott darab. Még mindig javítják.}
{55700}{}{Szuperszámítógép}
{55701}{}{Ez egy termetes szuperszámítógép. Valószínûleg az egyik leggyorsabb számítógép, amit valaha láttál.}
{55800}{}{Dobogó}
{55801}{}{Ezen a dobogón van a nagy szuperszámítógép a hûtõtartályok felett.}
{55900}{}{Ne használd}
{56000}{}{Ne használd}
{56100}{}{Ágy}
{56101}{}{Egy meglehetõsen katonai jellegû emeletes ágy. Nem túl kényelmes. Sõt, a takarók teljesen ki vannak merevítve.}
{56200}{}{Ágy}
{56201}{}{A katonák szoktak manapság ilyen emeletes ágyakban aludni. A lepedõk is úgy néznek ki, mintha valaki rengeteg keményítõt tett volna bele.}
{56300}{}{Ágy}
{56301}{}{Egy katonai emeletes ágy. Kényelmetlen. Még a visszajárót is visszaadja.}
{56400}{}{Vezeték}
{56401}{}{Valami soros kábel.}
{56500}{}{Vezeték}
{56501}{}{Egy RS-232-es kábel a Fallout-ban?!}
{56600}{}{Tábla}
{56601}{}{A táblán az áll, hogy "BÁR". A többi már magától értetõdik.}
{56700}{}{Gerenda}
{56701}{}{Ez a vastag gerenda egy kráter felé van kirakva.}
{56800}{}{Gerenda}
{56801}{}{A gerendáról kötél lóg lefelé. Úgy néz ki, most már lemászhatsz a kráterba.}
{56900}{}{Polc}
{56901}{}{Csak egy nagyon üres fémpolcot látsz.}
{57000}{}{Polc}
{57001}{}{Ez a polc se most fog összerogyni!}
{57100}{}{Polc}
{57101}{}{Fémpolc. Nincs rajta semmi (látnivaló).}
{57200}{}{Polc}
{57201}{}{Ezen a polcon nincs semmi! Nihil!}
{57300}{}{Bokor}
{57301}{}{Egy bokor, bakker.}
{57400}{}{Bokor}
{57401}{}{Gáz ez a gaz.}
{57500}{}{Bokor}
{57501}{}{Bokor biza.}
{57600}{}{Táj}
{57601}{}{Szép kilátás nyílik a Csonttelepre ebbõl a toronyból. Lassan már kezded érezni, hogy milyen magasan is vagy.}
{57700}{}{Táj}
{57701}{}{Nagyon szépen látható innen a Csonttelep.}
{57800}{}{Fal}
{57801}{}{A Katedrális oldala.}
{57900}{}{Fal}
{57901}{}{Ez a fal a Katedrális külsõ része.}
{58000}{}{Fal}
{58001}{}{A Katedrális külsõ oldala lenne ez. Nahát!}
{58100}{}{Ajtó}
{58101}{}{Egy ajtó, ami remekül mutat otthon egy cellában.}
{58200}{}{Tábla}
{58201}{}{A felirat szerint az üzletet "Pocsolyá"-nak hívják.}
{58300}{}{Létra}
{58301}{}{Ez a létra a lenn tátongó sötétségbe mered.}
{58400}{}{Létra}
{58401}{}{A létra a lenti sötétbe vezet.}
{58500}{}{Gép}
{58501}{}{Valami régi nyomdagép, vagy mi a franckarika.}
{58600}{}{Gép}
{58601}{}{Ez egy nyomdagép lenne, vagy mi a szent biszbasz?}
{58700}{}{Gép}
{58701}{}{Nyomdagép vagy talán csak nyomnak épp?}
{58800}{}{Gép}
{58801}{}{Valamikor a hõskorában ez nyomdagép lehetett, de esetleg akár nemtudommi is.}
{58900}{}{Gép}
{58901}{}{Izé, ez egy olyan izé, amivel jól lehet izélni az izéket, ha van hozzá izénk is.}
{59000}{}{Gép}
{59001}{}{Hogyishívják már' ezt a gépet?}
{59100}{}{Asztal}
{59101}{}{Ez a fémbõl készült asztal látszólag nagyon jó állapotban van. Van egy lefolyó a közepén.}
{59200}{}{Asztal}
{59201}{}{Az asztal nagyon jó kondícióban van. Hopp, egy lyuk van a közepén.}
{59300}{}{Asztal}
{59301}{}{Ezen a fémasztalon valami szerves tócsa terpeszkedik.}
{59400}{}{Asztal}
{59401}{}{Az asztal tetején szerves trutyi látható.}
{59500}{}{Asztal}
{59501}{}{Az asztal fémbõl van, a tetején leledzõ biomassza pedig nem tudom mibõl.}
{59600}{}{Hirdetõtábla}
{59601}{}{Különbözõ munkahirdetés van felragasztva a táblára. Látszólag elég gyakran használják.}
{59700}{}{Õrbódé}
{59701}{}{Ez az õrbódé már vagy száz éves, de még mindig(!) kitûnõ(!!) állapotban van!!!}
{59800}{}{Tábla}
{59801}{}{"Szatócsbolt".}
{59900}{}{Tábla}
{59901}{}{A táblán lévõ felirat a "Szatócsbolt".}
{60000}{}{Tábla}
{60001}{}{Az van rajta, hogy "Piac".}
{60100}{}{Medence}
{60101}{}{Nagyon egészségtelennek tûnik. Mielõtt fürdõt vennél, fel kellene venned egy páncélozott fürdõruhát.}
{60200}{}{Medence}
{60201}{}{Nem néz ki valami jól. Az úszást csak megfelelõ védõruhában ajánlanám.}
{60300}{}{Medence}
{60301}{}{Ránézésre nem túl biztató. Ha bele akarnál ugrani, nem ártana felvenned egy speciális fürdõruhát.}
{60400}{}{Asztal}
{60401}{}{Fémesen csillogó asztal.}
{60500}{}{Asztal}
{60501}{}{Ez az asztal ragyogó állapotban van.}
{60600}{}{Asztal}
{60601}{}{Egy fémes fényû asztal.}
{60700}{}{Asztal}
{60701}{}{Minden rendben van ezzel az asztallal.}
{60800}{}{Asztal}
{60801}{}{Ezt a fémasztalt nagyon nem gondozzák. A rozsda már teljesen átütött rajta.}
{60900}{}{Asztal}
{60901}{}{Nagyon jól nézne ki az asztal, ha nem lenne ennyire rozsdás.}
{61000}{}{Asztal}
{61001}{}{Egy fém asztal. Nagyon jó állapotú lenne, ha nem lenne rozsdás.}
{61100}{}{Asztal}
{61101}{}{Ha nem lenne rozsdás, akkor ez az asztal normális lenne.}
{61200}{}{Tûzhely}
{61201}{}{A tûz szelíden ég.}
{61300}{}{Tükör}
{61301}{}{Egy ideig nézegeted magadat.}
{61400}{}{Tükör}
{61401}{}{Egy jó ideig mustrálgatod a tükörképedet.}
{61500}{}{Mosdó}
{61501}{}{A csap tökéletesen mûködik. Szép és tiszta.}
{61600}{}{WC}
{61601}{}{A WC mentes a kosztól. És le is lehet húzni.}
{61700}{}{Vizelde}
{61701}{}{Ebbe a vizeldébe még nyugodtan lehet csurgatni.}
{61800}{}{WC}
{61801}{}{Ha lenne egy WC-illatosítód, ez lenne a világ legjobb WC-je.}
{61900}{}{Mosdó}
{61901}{}{A mosdó kifogástalan állapotban van.}
{62000}{}{Vizelde}
{62001}{}{A vizelde agyszerû állapotban van. Fél szemmel is tökéletes.}
{62100}{}{Zuhanyzó}
{62101}{}{Katonai zuhany. Szemérmes emberek alapból nem is használják.}
{62200}{}{Zuhanyzó}
{62201}{}{Katonák zuhanyoznak ilyenben. Nem való a szemérmeskedõknek.}
{62300}{}{Zuhanyzó}
{62301}{}{Katonai-jellegû zuhanyzó. Csak erõs idegzetûeknek!}
{62400}{}{Zuhanyzó}
{62401}{}{Zuhanyzó, a katonásabb fajtából. Leginkább csak katonák használják.}
{62500}{}{Zuhanyzó}
{62501}{}{Ez egy rendszeresített hadizuhanyzó. Nem szégyenlõsöknek való.}
{62600}{}{Zuhanyzó}
{62601}{}{Egy olyan zuhanyzó, amit katonák használnak. Itt nemigen lehet mit takargatni.}
{62700}{}{Ágy}
{62701}{}{Ez az ágy nagyon kényelmesnek látszik.}
{62800}{}{Ágy}
{62801}{}{Egy pihe-puha ágyacska.}
{62900}{}{Ágy}
{62901}{}{Egy megerõsített vázú emeletes ágy.}
{63000}{}{Ágy}
{63001}{}{Ez az ágy továbbfejlesztett vázzal rendelkezik.}
{63100}{}{Ágy}
{63101}{}{Kicsit strapabíróbb, mint egy átlagos emeletes ágy.}
{63200}{}{Terminál}
{63300}{}{Terminál}
{63400}{}{Zászló}
{63401}{}{Ez a zászló a Katedrális Gyermekeinek jelképe.}
{63500}{}{Zászló}
{63501}{}{A lobogó a Katedrális Gyermekei fõ szimbóluma.}
{63600}{}{Zászló}
{63601}{}{Ez a zászló jelképezi a Katedrális Gyermekeit.}
{63700}{}{Számítógép}
{63701}{}{Egy hatalmas számítógép.}
{63800}{}{Számítógép}
{63801}{}{Egy méretes számítógép.}
{63900}{}{Számítógép}
{63901}{}{Ez egy óriási számítógép.}
{64000}{}{Terminál}
{64001}{}{A terminál egy nagy számítógéphez kapcsolódik.}
{64100}{}{Hulla}
{64101}{}{Úgy látszik, ez az ember kínok között halt meg.}
{64200}{}{Hulla}
{64201}{}{Halálnak halálával halálosan halt hulla heverészik. Hah!}
{64300}{}{Hulla}
{64301}{}{Nos, ez a valaki elég sokat szenvedhetett, mielõtt meghalt volna.}
{64400}{}{Hulla}
{64401}{}{Ahogy végigméred ezt hullát, arra következtetsz, hogy sokat szenvedhetett.}
{64500}{}{Ajtó}
{64501}{}{Ez az elreteszelt ajtó tökéletesen megfelel cellaajtónak.}
{64600}{}{Terminál}
{64700}{}{Terminál}
{64800}{}{Targonca}
{64801}{}{A targonca nem mûködik.}
{64900}{}{Targonca}
{64901}{}{Nem lehet mûködésre bírni.}
{65000}{}{Felszerelés}
{65100}{}{Orvosi asztal}
{65101}{}{Ez az asztal nagyon rozsdaette. Az asztal közepén lévõ lyuk el van dugulva.}
{65200}{}{Orvosi asztal}
{65201}{}{Rettenetesen megfertõzte a rozsda.}
{65300}{}{Kapu}
{65301}{}{A kapun van egy retesz, ami fel és le jár.}
{65400}{}{Csõ}
{65500}{}{Csõ}
{65600}{}{Generátor}
{65601}{}{Egy Kandó Elek-Trobox típusú generátor. A háború utáni elterjedt tartalékgenerátor-fajta.}
{65700}{}{Tartály}
{65701}{}{Egy óriási víztartály. Megfigyeléseid alapján rendesen karbantartják és ez annyira fantasztikus!}
{65800}{}{Szekrény}
{65801}{}{Egy rendõrségi szekrény még Angliából, kb. 1960-ból.}
{65900}{}{Asztal}
{65901}{}{Egy ízlésesen elkészített asztal. Kézzel csináltak rajta mindent, de ettõl függetlenül a legszebb, amit valaha láttál.}
{66000}{}{Asztal}
{66001}{}{Nagyon szép asztal. A kivitelezésen látszik, hogy aprólékos, gondos kezek munkája. Igen, ezt nem gép rakta össze.}
{66100}{}{Asztal}
{66101}{}{Ez az asztal lenyûgözõ. Kivételesen kézzel készült, ritka és bizonyára értékes darab.}
{66200}{}{Szék}
{66201}{}{Egy gyönyörû szék.}
{66300}{}{Szék}
{66301}{}{Aranyos.}
{66400}{}{Szék}
{66401}{}{Csodálatos.}
{66500}{}{Szék}
{66501}{}{Egy ügyes mester kezeit dicséri.}
{66600}{}{Szék}
{66601}{}{Remek munka.}
{66700}{}{Szék}
{66701}{}{Nem látsz rajta semmi rosszat.}
{66800}{}{Szék}
{66801}{}{Ügyes.}
{66900}{}{Szék}
{66901}{}{Kiválóan megmunkált darab.}
{67000}{}{Szék}
{67001}{}{Bizonyára nagyon kényelmes.}
{67100}{}{Szék}
{67101}{}{Szép kis szék ez...}
{67200}{}{Szék}
{67201}{}{Jól nézünk ki, jól nézünk ki!}
{67300}{}{Szék}
{67301}{}{Kifogástalannak ítéled meg.}
{67400}{}{Szék}
{67401}{}{Mint szék, ez mind nagyon szép.}
{67500}{}{Szék}
{67501}{}{Nem sokszor találkozol ilyen székkel.}
{67600}{}{Szék}
{67601}{}{Azta! Egy szék!}
{67700}{}{Szék}
{67701}{}{Ez egy szék a javából!}
{67800}{}{Ágy}
{67801}{}{Kifogástalan.}
{67900}{}{Ágy}
{67901}{}{Szép.}
{68000}{}{Ágy}
{68001}{}{Okés.}
{68100}{}{Ágy}
{68101}{}{Gond egy szál se.}
{68200}{}{Kályha}
{68201}{}{Egy még most is használható fatüzelésû kályha.}
{68300}{}{Kályha}
{68301}{}{A kályhát fával kell táplálni, hogy fûtsön.}
{68400}{}{Kályha}
{68401}{}{Ez egy használható állapotban lévõ faüzemû kályha.}
{68500}{}{Kályha}
{68501}{}{Egy régebbi típus, ebben fát kell eltüzelni.}
{68600}{}{Törött oszlop}
{68700}{}{Lerombolt bejárat}
{68800}{}{Kövek}
{68801}{}{Ezek a kövek valamilyen alakzatot formálnak. Ez nem tûnik számodra természetesnek.}
{68900}{}{Kövek}
{68901}{}{Úgy néz ki, mintha a kövekbõl egy alakzat képe állna össze. Bizonyára eredetileg nem így helyezkedtek el.}
{69000}{}{WC}
{69001}{}{Egy egyszerû, de nagyszerû WC. Néhány levél van a lyukba dobva, ami megpróbálja elfedni az illatokat.}
{69100}{}{Hegy}
{69101}{}{Azok a távoli hegyoldalak elérhetetlennek látszanak.}
{69200}{}{Hegy}
{69201}{}{Egy messzi hegy kérges oldalát látod.}
{69300}{}{Hegy}
{69301}{}{A hegy bizonyára nagyon messze van, távol tõled.}
{69400}{}{Hegy}
{69401}{}{Ez most nem a hegymászás ideje!}
{69500}{}{Hegy}
{69501}{}{Egy hatalmas hegy panorámáját láthatod innen.}
{69600}{}{Hegy}
{69601}{}{A hegyoldal megközelíthetetlennek látszik.}
{69700}{}{Trutymó}
{69701}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{69800}{}{Trutymó}
{69801}{}{Szerves, szeszélyes, szokatlan.}
{69900}{}{Trutymó}
{69901}{}{Ne nagyon taperold!}
{70000}{}{Trutymó}
{70001}{}{Nem valami bizalomgerjesztõ.}
{70100}{}{Trutymó}
{70101}{}{Vigyázz vele, nem tûnik ártalmatlannak!}
{70200}{}{Trutymó}
{70201}{}{Próbálok valami vicces megjegyzést tenni, de egy trutyiról mi mókásat lehetne mondani?}
{70300}{}{Trutymó}
{70301}{}{Ennek a fele sem tréfa. Persze, inkább valami biológiai hulladék.}
{70400}{}{Trutymó}
{70401}{}{Az tény, ez valami bioragacs, de vajon nem veszélyes-e?}
{70500}{}{Trutymó}
{70501}{}{Tartsd távol tõle magad! Ne számíts indoklásra :)}
{70600}{}{Trutymó}
{70601}{}{Vizuálisan is megerõsítetted, hogy ez bizony az. Szóval nem ez, vagy amaz.}
{70700}{}{Trutymó}
{70701}{}{Trutty-trutty-trutty-tritty.}
{70800}{}{Trutymó}
{70801}{}{A látszat néha csal, mint ahogy a közmondás is tartja; bár most kérdés, mennyire.}
{70900}{}{Trutymó}
{70901}{}{Szegény kalandozó. Szóval információkra van szükséged. Nesze: "strange", "noxious" és "biological".}
{71000}{}{Trutymó}
{71001}{}{Tudod te egyáltalán, hogy most mirõl akarsz megtudni bõvebb információt?}
{71100}{}{Trutymó}
{71101}{}{Emberi fogyasztásra alkalmatlan szerves trutyesz.}
{71200}{}{Trutymó}
{71201}{}{Sokat nem tudni róla, de az a kevés sem hangzik túl jól.}
{71300}{}{Trutymó}
{71301}{}{Alaposan áttanulmányozod, és azáltal jobbnak tûnik, ha tartasz némi távolságot.}
{71400}{}{Trutymó}
{71401}{}{"Hozzányúlkálás csak saját felelõsségre!". Akár egy ilyen tábla is úszkálhatna benne.}
{71500}{}{Trutymó}
{71501}{}{Az egészségedet kockáztatod, ha ezt piszkálgatod.}
{71600}{}{Trutymó}
{71601}{}{Igen, ez valami mérgezõ szerves ragadék. Többet én sem tudok.}
{71700}{}{Trutymó}
{71701}{}{Trutymó trutyi hátán.}
{71800}{}{Trutymó}
{71801}{}{Érdemes odafigyelni rá, mert nagyon mérgezõnek látszik.}
{71900}{}{Trutymó}
{71901}{}{Ez nevezetesen egy kellemetlen szerves elem.}
{72000}{}{Trutymó}
{72001}{}{Csak óvatosan! Nagyon veszélyes anyag.}
{72100}{}{Trutymó}
{72101}{}{Kevés pontos adattal rendelkezel, de azok mind arra utalnak, hogy vedd fel a kötelezõ távolságot.}
{72200}{}{Trutymó}
{72201}{}{Egy furcsa, mérgezõ és szerves anyagot látsz.}
{72300}{}{Trutymó}
{72301}{}{Ha a szemed nem csal, ez valami rettenetesen veszélyes ragad.}
{72400}{}{Trutymó}
{72401}{}{Nem árt körültekintõnek lenned ennek az anyagnak a közelében.}
{72500}{}{Trutymó}
{72501}{}{Ez a ragacs mérgezõ.}
{72600}{}{Trutymó}
{72601}{}{Mintha biohulladék lenne.}
{72700}{}{Trutymó}
{72701}{}{Ronda... és hogy finom-e, azt viszont nem tudod.}
{72800}{}{Trutymó}
{72801}{}{Rákkeltõ anyagot tartalmaz; erre mindig felébrednek a rákok.}
{72900}{}{Trutymó}
{72901}{}{Valami veszélyes váladék.}
{73000}{}{Trutymó}
{73001}{}{Jobb lesz, ha nem játszadozol vele.}
{73100}{}{Trutymó}
{73101}{}{Gratulálunk! Valakinek megint sikerült elõállítania egy újabb veszélyes és elpusztíthatatlan anyagot.}
{73200}{}{Trutymó}
{73201}{}{Méregerõs biomassza ez.}
{73300}{}{Trutymó}
{73301}{}{Ami az illeti, ez a trutymó nem egészséges.}
{73400}{}{Trutymó}
{73401}{}{Óvatosan, óvatosan, ember! Ki tudja, milyen veszélyt rejt magában.}
{73500}{}{Trutymó}
{73501}{}{A fene ette volna meg ezt a gennyet!}
{73600}{}{Trutymó}
{73601}{}{Ne számíts semmi jóra. Jó?}
{73700}{}{Trutymó}
{73701}{}{A takony távoli rokona, sokkal sugárzóbb (pompázóbb?) kiszerelésben.}
{73800}{}{Trutymó}
{73801}{}{Már szemre sem tûnik túl bíztatónak ez a trutyadék.}
{73900}{}{Trutymó}
{73901}{}{Nem több, mint biológiai szemét.}
{74000}{}{Trutymó}
{74001}{}{Veszélyes hulladék, és csak így szabadon!}
{74100}{}{Trutymó}
{74101}{}{Egy rakás ragacsos biotrágya.}
{74200}{}{Trutymó}
{74201}{}{Ez a trutymó, amit most látsz, nagyon veszélyes rád.}
{74300}{}{Trutymó}
{74301}{}{Ez a biológiai hulladék távolabbról megvizsgálva sem látszik veszélytelennek.}
{74400}{}{Trutymó}
{74401}{}{Én óva intenélek attól, hogy belenyúlj!}
{74500}{}{Trutymó}
{74501}{}{Azt se mondhatnám, hogy ez a massza nem látszik ártalmatlannak.}
{74600}{}{Trutymó}
{74601}{}{Ön a sugárzó méregmassza adását fogja.}
{74700}{}{Trutymó}
{74701}{}{A trutymó számodra nem hasznos, viszont káros, mert mérgezõ.}
{74800}{}{Trutymó}
{74801}{}{Ez valami káros biológiai hulladék.}
{74900}{}{Számítógép}
{74901}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{75000}{}{Számítógép}
{75001}{}{Nagyon nehéz hozzáférni, mert az egész merõ ragacs.}
{75100}{}{Számítógép}
{75101}{}{Hiába nézed át többször is, a rátapadt ragadéktól szinte lehetetlen használni.}
{75200}{}{Számítógép}
{75201}{}{Túl sok a trutymó, kevés a szabad felület.}
{75300}{}{Számítógép}
{75301}{}{Hm, szerintem itt nyugodtan rendezhetnének egy takarítóversenyt.}
{75400}{}{Számítógép}
{75401}{}{Valakinek beleborult a kólája a billentyûzetbe. Bizonyára.}
{75500}{}{Számítógép}
{75501}{}{Hûha, ezt a számítógépet nagyon nem takarították az utóbbi idõben!}
{75600}{}{Számítógép}
{75601}{}{Igazából még mindig rejtély, miként jöttél rá arra, hogy ez alatt egy számítógép van...}
{75700}{}{Számítógép}
{75701}{}{Heh, ez a gép a következõ generációs poloska: mindenhez könnyen hozzátapad (hála a rajta lévõ trutyinak).}
{75800}{}{Számítógép}
{75801}{}{Most mondja meg nekem valaki, miért kellett leokádni az egész számítógépet?}
{75900}{}{Számítógép}
{75901}{}{Szívesen végigzongoráznád a tasztatúrát, de félõ, hogy az ujjaid ottmaradnának.}
{76000}{}{Számítógép}
{76001}{}{Látják? Ezt teszi a számítógép elõtt ért stressz az emberekkel.}
{76100}{}{Monitorok}
{76101}{}{A rácsapódott nagy mennyiségû trutyi miatt semmit nem tudsz elolvasni a monitorokon.}
{76200}{}{Monitorok}
{76201}{}{Nem tudod kivenni, mi lehet a monitorokon, mivel az összes tele van trutymóval.}
{76300}{}{Monitorok}
{76301}{}{Lehetetlen bármilyen információt is kicsikarni a képernyõkbõl, mert tiszta genny az egész.}
{76400}{}{Monitorok}
{76401}{}{Nem tudod, hogy valaki szándékosan csinálta-e, de a célját elérte. Semmit nem lehet látni a képernyõkbõl.}
{76500}{}{Padló}
{76501}{}{Meg mernél esküdni, hogy valami mozog.}
{76600}{}{Talapzat}
{76601}{}{Úgy néz ki, mintha a talapzat lassan lélegezne ki... és be..., ki... és be....}
{76700}{}{Padló}
{76800}{}{Bomba}
{76801}{}{Ez egy atombomba. Szerintem nem kellene tétlenül üldögélned! (a narrátor)}
{76900}{}{Bázis}
{76901}{}{Itt nyugszik az atombomba.}
{77000}{}{Konzol}
{77001}{}{Ez az atombombát vezérlõ számítógép. Nagyon levédettnek tûnik, és van egy nyílás rajta valami furcsa alakú kulcsnak.}
{77100}{}{Vezetékek}
{77101}{}{Ezek a vezetékek kötik a bombát a számítógéphez.}
{77200}{}{Szék}
{77201}{}{Semmi szokatlan.}
{77300}{}{Szék}
{77301}{}{Tök átlagos.}
{77400}{}{Szék}
{77401}{}{Olyan, mint a többi szék.}
{77500}{}{Szék}
{77501}{}{Nincs vele semmi.}
{77600}{}{Szék}
{77601}{}{Nem sok érdekeset látsz rajta.}
{77700}{}{Szék}
{77701}{}{Ohne furcsaság.}
{77800}{}{Szék}
{77801}{}{Minden OK.}
{77900}{}{Szék}
{77901}{}{Vizuálisan nem észlelsz semmi eltérést a normális székmodelltõl.}
{78000}{}{Oszlop}
{78001}{}{Ezt azt oszlopot valaminek a megtámasztására használják.}
{78100}{}{Oszlop}
{78101}{}{Jó szponzor lenne belõle, hiszen õ a fõtámogató itt.}
{78200}{}{Oszlop}
{78201}{}{Precíz elemzésed azt támasztja alá, hogy az oszlop a plafont támasztja alá.}
{78300}{}{Oszlop}
{78301}{}{Nélküle itt összedõlne minden.}
{78400}{}{Ágy}
{78401}{}{Szánalmas, ahogy kinéz.}
{78500}{}{Ágy}
{78501}{}{Nincs valami komfortos kinézete.}
{78600}{}{Ágy}
{78601}{}{Az állapota válságos, de nem súlyos.}
{78700}{}{Ágy}
{78701}{}{Eléggé rosszul néz ki.}
{78800}{}{Monitorok}
{78801}{}{Ezek a monitorok ripityára vannak törve és nem is mûkõdnek.}
{78900}{}{Monitorok}
{78901}{}{Teljesen lepukkant az állomány, és persze hogy nem is üzemel.}
{79000}{}{Monitorok}
{79001}{}{Nem használhatóak, mert teljesen tré állapotban vannak.}
{79100}{}{Monitorok}
{79101}{}{Nem funkcionálnak, állapotuk inkonzisztens.}
{79200}{}{Szellõztetõ}
{79201}{}{Csak egy nagyon parányi friss levegõ érkezik ezen a szerkezeten keresztül.}
{79300}{}{Szellõztetõ}
{79301}{}{Szinte alig érezhetõ friss levegõ jön belõle.}
{79400}{}{Szellõztetõ}
{79401}{}{Semmi friss levegõ nem jõ'.}
{79500}{}{Szellõztetõ}
{79501}{}{Észrevétlenül kicsiny mennyiségû tiszta és friss levegõt érzel.}
{79600}{}{Asztal}
{79601}{}{Semmi feltûnõ nincs ezen az asztalon, eltekintve attól, hogy már nagyon a végét járja.}
{79700}{}{Asztal}
{79701}{}{Az asztal romokban áll. Kész csoda, hogy még áll egyáltalán.}
{79800}{}{Asztal}
{79801}{}{Nagyon lepusztult státuszban van.}
{79900}{}{Asztal}
{79901}{}{Minek akarod átkutatni ezt az asztalt?}
{80000}{}{Monitorok}
{80001}{}{Az itt lévõ monitorok képernyõi megsemmisültek.}
{80100}{}{Monitorok}
{80101}{}{A monitorok képernyõi megsérültek és éppen javítás alatt állnak.}
{80200}{}{Monitor}
{80201}{}{A képernyõ össze van törve, a monitor pedig tönkrement.}
{80300}{}{Monitor}
{80301}{}{Ez a monitor szinte értéktelen egy elromlott képernyõvel.}
{80400}{}{Számítógép}
{80401}{}{Használhatatlan.}
{80500}{}{Számítógép}
{80501}{}{Nem jó.}
{80600}{}{Számítógép}
{80601}{}{Tropa.}
{80700}{}{Szék}
{80701}{}{El van rongyolódva.}
{80800}{}{Szék}
{80801}{}{Erre már ne nagyon ülj le.}
{80900}{}{Szék}
{80901}{}{Nem több, mint szemét.}
{81000}{}{Szék}
{81001}{}{Ez széktelenség!}
{81100}{}{Szellõztetõ}
{81101}{}{Valami gondja van; javítás alatt áll.}
{81200}{}{Szellõztetõ}
{81201}{}{Ez a példány nagyon súlyos károkat szenvedett el, nem lehet rendbehozni.}
{81300}{}{Szellõztetõ}
{81301}{}{Ez a szellõztetõ nem teljesen mûködik.}
{81400}{}{Számítógép}
{81401}{}{Ez a számítógép alig-alig mûködik.}
{81500}{}{Számítógép}
{81501}{}{Nem látsz semmi mûködõt ezen a számítógépen.}
{81600}{}{Monitor}
{81601}{}{Ez a monitor se húzza már sokáig.}
{81700}{}{Monitor}
{81701}{}{A monitor nem produkál látványos teljesítményt.}
{81800}{}{Számítógép}
{81801}{}{Egyszerûen nem mûködik.}
{81900}{}{Számítógép}
{81901}{}{Vagy kikapcsolta valaki, vagy nem is mûködik.}
{82000}{}{Monitor}
{82001}{}{Képtelen!}
{82100}{}{Monitor}
{82101}{}{Semmit nem látsz rajta. Csak a sötétséget.}
{82200}{}{Ajtókeret}
{82201}{}{Szemrevételezésed szerint ez egy nagyon szép ajtókeret. Sõt, eredeti funkcióját (mint az ajtó kerete) is nagyszerûen betölti.}
{82300}{}{Monitorok}
{82301}{}{Ezek a monitorok eléggé jó állapotban vannak (egyelõre).}
{82400}{}{Monitorok}
{82401}{}{A monitorok még viszonylag mûködésre hajlamosak.}
{82500}{}{Fal}
{82600}{}{Nagyajtó}
{82601}{}{Egy nagyon komoly és vaskos menedékajtó. Ez az ajtó áthatolhatatlannak látszik.}
{82700}{}{Lámpa}
{82701}{}{Egy biztonsági lámpa.}
{82800}{}{Lámpa}
{82801}{}{Biztonsági lámpa.}
{82900}{}{Oszlop}
{82901}{}{Ez az oszlop a tér egyik fontos eleme. Történeteket tartalmaz, amik emlékeztetik az embereket a békére és a reményre.}
{83000}{}{Robottároló}
{83001}{}{Ez egy raktár. Amikor a robotok nincsenek szolgálatban, ide állnak be, kikapcsolnak, majd feltöltõdnek.}
{83100}{}{Robottároló}
{83101}{}{A robotok pihenõhelye. Amikor nem kell semmit sem csinálniuk, a robotok ide jönnek egy kicsit felfrissülni.}
{83200}{}{Robottároló}
{83201}{}{Itt raktározzák a szolgálaton kívüli botokat. Itt aztán szépen ledokkolnak és feltöltik magukat.}
{83300}{}{Robottároló}
{83301}{}{Egy robottöltõ-üzem. Ha egy robot éppen munka nélkül marad, visszatér ide, bedokkol és tölt.}
{83400}{}{Robottároló}
{83401}{}{Ezt a helyet a robotok újratöltésére használják. Innen merítenek egy kis energiát.}
{83500}{}{Gép}
{83501}{}{A gép robotállomáson dolgozik valamit. Annyira nem tûnik érdekesnek.}
{83600}{}{Gép}
{83601}{}{Ez a gép csinál valamit robotok szervízállomásával. Nagyon nem tudott felajzani.}
{83700}{}{Csík}
{83800}{}{Csík}
{83900}{}{Csík}
{84000}{}{Csík}
{84100}{}{Csík}
{84200}{}{Csík}
{84300}{}{Csík}
{84400}{}{Csík}
{84500}{}{Csík}
{84600}{}{Csík}
{84700}{}{Csík}
{84800}{}{Ajtó}
{84801}{}{Egy nagyon-nagyon is átlagos fa ajtó.}
{84900}{}{Ajtó}
{84901}{}{Teljesen, totálisan átlagos fa ajtó.}
{85000}{}{Ajtó}
{85001}{}{Ezen az ajtón nincs semmi extra. Fából van és kész.}
{85100}{}{Tábla}
{85101}{}{A tábla a "Baráti Kölcsön Bt."-é.}
{85200}{}{Embléma}
{85201}{}{Ez valami vallásos jelképnek tûnik.}
{85300}{}{Orvosi asztal}
{85301}{}{Ez pont úgy néz ki, mint egy egészségügyi vizsgálóasztal.}
{85400}{}{Tábla}
{85401}{}{Ez a neonfelirat a "Máltai Sólyom" hirdetésére szolgál.}
{85500}{}{Graffiti}
{85600}{}{Graffiti}
{85700}{}{Graffiti}
{85800}{}{Graffiti}
{85900}{}{Graffiti}
{86000}{}{Graffiti}
{86100}{}{Graffiti}
{86200}{}{Graffiti}
{86300}{}{Graffiti}
{86400}{}{Graffiti}
{86500}{}{Graffiti}
{86600}{}{Graffiti}
{86700}{}{Graffiti}
{86800}{}{Graffiti}
{86900}{}{Tábla}
{86901}{}{Assz'ondja: "FEGYVEREK". Ott akkor bizonyára fegyvereket árulnak.}
{87000}{}{Tábla}
{87001}{}{A tábla szerint ez a "Rendõrség".}
{87100}{}{Tábla}
{87101}{}{Ez a "Hosszú-Távú Kereskedõk" táblája.}
{87200}{}{Tábla}
{87201}{}{A táblán a betûk a következõ szót formálják: "Fegyverkereskedõk".}
{87300}{}{Tábla}
{87301}{}{Ez a "Karmazsin Karaván" kereskedelmi vállalat cégtáblája.}
{87400}{}{Tábla}
{87401}{}{"Kórház". Biztos jó lehet.}
{87500}{}{Tábla}
{87501}{}{Ön most a "Vászon Ház" tábláját olvassa fel a narrátorral.}
{87600}{}{Tábla}
{87601}{}{Ezen a semmitmondó táblácskán az olvasható, hogy "Bob Korábban Már Használt Autók Piaca".}
{87700}{}{Tábla}
{87701}{}{Ez a tábla a Vízkereskedõké, ami a Központ egyik kis cége.}
{87800}{}{Tojáshéj}
{87801}{}{Egy széttörött tojás darabjai.}
{87900}{}{Tojáshéj}
{87901}{}{Ebben van a vitamin, komám!}
{88000}{}{Tojáshéj}
{88001}{}{Egy tojás héja, több darabos kiszerelésben.}
{88100}{}{Tojáshéj}
{88101}{}{E tojás héja már csak imitt-amott található meg.}
{88200}{}{Tojáshéj}
{88201}{}{Egy törött tojás darabjai.}
{88300}{}{Tojáshéj}
{88301}{}{Hé! Ja, ez itt egy tojás héja!}
{88400}{}{Tojáshéj}
{88401}{}{Egy törött tojás törött darabja.}
{88500}{}{Tojáshéj}
{88501}{}{Ennek a tojáshéjnak igen nagy a fregmentációja.}
{88600}{}{Lámpaoszlop}
{88601}{}{Egy lámpaoszlop. Látszólag minden rendben van vele.}
{88700}{}{Tábla}
{88701}{}{A tábla szövege: "Panzió".}
{88800}{}{Gombák}
{88801}{}{Ez a cserép tele van trágyával, amiben boldogan növekvõ gombákat látsz.}
{88900}{}{Gombák}
{88901}{}{Egy cserép, melyben némi trágya hozzájárulásával gombák növekednek boldogan.}
{89000}{}{Csontváz}
{89100}{}{Tábla}
{89101}{}{Ez van ráírva: "Börtön".}
{89200}{}{Tábla}
{89201}{}{A tábla szerint ez a "Ürrgejuk" nevû kocsma és elmegyógyintézet.}
{89300}{}{Tábla}
{89301}{}{Ez a hirdetés a Penge márkájú borotvapengéé.}
{89400}{}{Zuhanyzó}
{89401}{}{Egy nagyjából tûrhetõ zuhanyzó.}
{89500}{}{Zuhanyzó}
{89501}{}{Egy zuhanyfülke, tûrhetõ állapotban.}
{89600}{}{Tábla}
{89601}{}{Ez a "Baráti Kölcsön Bt." táblája.}
{89700}{}{Tábla}
{89701}{}{"Baráti Kölcsön Bt.". Ez áll a táblán feketén-fehéren.}
{89800}{}{Plakát}
{89801}{}{Ez a plakát egy horrorfilmhez tartozik, még a háború elõtti idõkbõl.}
{89900}{}{Plakát}
{89901}{}{Egy háború elõtti horrorfilm posztere.}
{90000}{}{Bárpult}
{90001}{}{Egy urna pihen a bárpulton. Az urna egy kissé viharvertnek tûnik, de attól még értékes lehet.}
{90100}{}{Liftakna}
{90101}{}{Az aknában egy kötél lóg le a felsõbb szintrõl.}
{90200}{}{Liftakna}
{90201}{}{Egy kötél lóg lefelé az akna szélérõl.}
{90300}{}{Orvosi ágy}
{90301}{}{Az ágyhoz tartozik egy beépített kijelzõ, ami a páciens állapotát figyeli.}
{90400}{}{Vízpumpa}
{90401}{}{Ez a gép a vizet pumpálja fel az alacsonyabban fekvõ helyekrõl.}
{90500}{}{Orvosi ágy}
{90501}{}{Az ágynak egy beépített monitor is része, amelyen figyelemmel lehet kísérni a betegek állapotát.}
{90600}{}{Energiapáncél-darabok}
{90601}{}{Ezek a részek alkotják a híres Energiapáncélt.}
{90700}{}{Lámpa}
{90701}{}{Ez az élénkvörös biztonsági lámpa folyamatosan villog.}
{90800}{}{Lámpa}
{90801}{}{A lámpa vörös színben pulzál.}
{90900}{}{Szimbólum}
{91000}{}{Szimbólum}
{91100}{}{Szimbólum}
{91200}{}{Szimbólum}
{91300}{}{Szimbólum}
{91400}{}{Szimbólum}
{91500}{}{Kötél}
{91600}{}{Kötél}
{91700}{}{Kötél}
{91800}{}{Kötél}
{91900}{}{Kötél}
{92000}{}{Kötél}
{92100}{}{Kötél}
{92200}{}{Kötél}
{92300}{}{Kanyon}
{92400}{}{Kanyon}
{92500}{}{Kanyon}
{92600}{}{Kanyon}
{92700}{}{Kanyon}
{92800}{}{Kanyon}
{92900}{}{Kanyon}
{93000}{}{Kanyon}
{93100}{}{Barlang kövezet}
{93200}{}{Nyithatatlan ajtó}
{93201}{}{Úgy látszik, ennek az ajtónak nincs nyitómechanizmusa.}
{93300}{}{Lerombolt ajtó}
{93301}{}{Az ajtó ki lett robbantva.}
{93400}{}{Ajtó}
{93401}{}{Egy ajtó, bonyolult zárral.}
{93500}{}{Fáklya}
{93501}{}{Egy égõ fáklya a falon.}
{93600}{}{Fáklya}
{93601}{}{A fali tartóban pislákoló fáklya.}
{93700}{}{Emlékmû}
{93800}{}{Emlékmû}
{93900}{}{Emlékmû}
{94000}{}{Koponyatartó}
{94001}{}{Egy rúd, amire emberi koponyák vannak függesztve.}
{94100}{}{Koponyatartó}
{94101}{}{Ez nem más, mint egy rúd, amin szerencsétlen emberek koponyái vannak.}
{94200}{}{Koponyatartó}
{94201}{}{Ez egy rúd, amire valaki koponyákat aggatott.}
{94300}{}{Növény}
{94301}{}{}
{94400}{}{Növény}
{94500}{}{Fa}
{94600}{}{Fa}
{94700}{}{Fa}
{94800}{}{Ágy}
{94900}{}{Ágy}
{95000}{}{Lyuk}
{95001}{}{Egy gyanús lyuk a falban.}
{95100}{}{Kiemelkedõ kõlap}
{95101}{}{Egy kibukkanó kõlap.}
{95200}{}{Tönkrement kõlap}
{95201}{}{Ez a kõlap már nem lát el semmilyen funkciót.}
{95300}{}{Benyomott kõlap}
{95301}{}{Egy lenyomódott kõlap.}
{95400}{}{Ajtó}
{95500}{}{Ajtó}
{95600}{}{Ajtó}
{95700}{}{Ajtó}
{95800}{}{Ajtó}
{95900}{}{Ajtó}
{96000}{}{Ajtó}
{96100}{}{Ajtó}
{96200}{}{Ajtó}
{96300}{}{Növény}
{96301}{}{Egy mutáns kukoricacsutka.}
{96400}{}{Növény}
{96401}{}{Kukoricacsutka, ami mutálódott.}
{96500}{}{Növény}
{96501}{}{Kukorica ala mutáció. Ez undorító.}
{96600}{}{Növény}
{96601}{}{Ennek a növénynek az õsei kukoricák voltak.}
{96700}{}{Növény}
{96701}{}{Mutáns növény, mutáns kukorica.}
{96800}{}{Növény}
{96801}{}{Vajon mire hasonlíthatna ez a növény? Egy kukoricára?!}
{96900}{}{Fa támaszték}
{97000}{}{Fa támaszték}
{97100}{}{Fa támaszték}
{97200}{}{Fa támaszték}
{97300}{}{Fa támaszték}
{97400}{}{Fa támaszték}
{97500}{}{Sérült fa támaszték}
{97501}{}{Úgy látszik, ez a támaszték könnyen összeroppanna, ha egy kicsit nagyobb terhelés érné.}
{97600}{}{Beomlott padló}
{97601}{}{A kõpadló ezen a ponton omlott le az alatta lévõ szintre.}
{97700}{}{Létra lefelé}
{97701}{}{Ez egy emberméretû nyílás, amiben egy létra vezet lefelé.}
{97800}{}{Ajtó}
{97900}{}{Fal}
{98000}{}{"5-ÖS REAKTOR"}
{98100}{}{Ajtó}
{98200}{}{Ajtó}
{98300}{}{Ajtó}
{98400}{}{Ajtó}
{98500}{}{Radioaktív trutyi}
{98600}{}{Radioaktív trutyi}
{98700}{}{Radioaktív trutyi}
{98800}{}{Radioaktív trutyi}
{98900}{}{Biztonsági ajtó}
{99000}{}{Menedékajtó}
{99100}{}{Rakodódaru}
{99200}{}{Rakodódaru}
{99300}{}{Kút}
{99400}{}{Kút}
{99500}{}{Melléképület}
{99600}{}{Lyuk}
{99601}{}{Nem látod a gödör mélyét.}
{99700}{}{Padlólap}
{99701}{}{Egy padlólapnak álcázott csapdát látsz.}
{99800}{}{Tönkrement padlólap}
{99801}{}{Ez a padlólapnak látszó csapda már nem jelenthet veszélyt neked.}
{99900}{}{Bekapcsolt padlólap}
{99901}{}{Ez a padlólap-csapda aktiválódott. Hopp!}
{100000}{}{Szeszfõzde}
{100001}{}{Hm, ez egy fával tüzelt szeszkazán.}
{100100}{}{Radskorpió darabok}
{100101}{}{Nem látsz mást, csak egy halom radskorpió-darabot. Át vannak lyukasztva és egy kampót akasztottak beléjük.}
{100200}{}{Erõmûvi gépezet}
{100201}{}{A reaktor egyik tartozéka, egy plutónium-gamma pajzs.}
{100300}{}{Erõmûvi gépezet}
{100301}{}{A gép a reaktorhoz tartozik. Ez egy Jupiter térkiegyenlítõ.}
{100400}{}{Erõmûvi gépezet}
{100401}{}{Ez a reaktorhoz kapcsolódik. Egy uránrúd-kalibrátor.}
{100500}{}{Erõmûvi gépezet}
{100501}{}{Ez egy neptúnium terelõlapát. A reaktor egyik gépe.}
{100600}{}{Erõmûvi gépezet}
{100601}{}{Saturn típusú kondenzátor, ami a reaktor eleme.}
{100700}{}{Erõmûvi pumpa}
{100701}{}{Ez a hûtést irányító pumpálógép a reaktor részeleme.}
{100800}{}{A brahmin oldala}
{100900}{}{Autó}
{101000}{}{Chrysalis}
{101001}{}{A Chrysalis autógyár "Highwayman" típusú modellje. A korához képest elég jó formában van.}
{101100}{}{Autó}
{101200}{}{Sírhely}
{101201}{}{Egy sírhely található itt.}
{101300}{}{Sírkõ}
{101301}{}{Sírkõ}
{101400}{}{Sírkõ}
{101401}{}{Sírkõ}
{101500}{}{Sírkõ}
{101501}{}{Sírkõ}
{101600}{}{Sírkõ}
{101601}{}{Sírkõ}
{101700}{}{Eke}
{101701}{}{Ezt ez ekét arra tervezték, hogy egy brahmin húzza.}
{101800}{}{Eke}
{101801}{}{Egy brahmin-vontatta ekevas.}
{101900}{}{Víz}
{102000}{}{Tábla}
{102001}{}{"New Reno"}
{102100}{}{Tábla}
{102101}{}{A tábla jelzi, hogy New Reno következik.}
{102200}{}{Tábla}
{102201}{}{Egy New Reno tábla.}
{102300}{}{Tábla}
{102301}{}{A tábla New Reno bejáratát hirdeti.}
{102400}{}{Tábla}
{102401}{}{Itt lenne New Reno, ha még nem derült volna ki.}
{102500}{}{Tábla}
{102501}{}{New Reno. Legalábbis a tábla szerint.}
{102600}{}{Árnyék}
{102700}{}{Árnyék}
{102800}{}{Árnyék}
{102900}{}{Graffiti}
{103000}{}{Graffiti}
{103100}{}{Graffiti}
{103200}{}{Graffiti}
{103300}{}{Graffiti}
{103400}{}{Graffiti}
{103500}{}{Graffiti}
{103600}{}{Graffiti}
{103700}{}{Graffiti}
{103800}{}{Graffiti}
{103900}{}{Graffiti}
{104000}{}{Graffiti}
{104100}{}{Graffiti}
{104200}{}{Graffiti}
{104300}{}{Graffiti}
{104400}{}{Graffiti}
{104500}{}{Graffiti}
{104600}{}{Graffiti}
{104700}{}{Graffiti}
{104800}{}{Graffiti}
{104900}{}{Graffiti}
{105000}{}{Graffiti}
{105100}{}{Graffiti}
{105200}{}{Graffiti}
{105300}{}{Graffiti}
{105400}{}{Graffiti}
{105500}{}{Graffiti}
{105600}{}{Graffiti}
{105700}{}{Graffiti}
{105800}{}{Graffiti}
{105900}{}{Graffiti}
{106000}{}{Tábla}
{106100}{}{Graffiti}
{106200}{}{Graffiti}
{106300}{}{Graffiti}
{106400}{}{Graffiti}
{106500}{}{Graffiti}
{106600}{}{Graffiti}
{106700}{}{Graffiti}
{106800}{}{Graffiti}
{106900}{}{Graffiti}
{107000}{}{Graffiti}
{107100}{}{Graffiti}
{107200}{}{Graffiti}
{107300}{}{Graffiti}
{107400}{}{Graffiti}
{107500}{}{Graffiti}
{107600}{}{Graffiti}
{107700}{}{Graffiti}
{107800}{}{Graffiti}
{107900}{}{Graffiti}
{108000}{}{Graffiti}
{108100}{}{Graffiti}
{108200}{}{Graffiti}
{108300}{}{Graffiti}
{108400}{}{Graffiti}
{108500}{}{Graffiti}
{108600}{}{Graffiti}
{108700}{}{Graffiti}
{108800}{}{Graffiti}
{108900}{}{Graffiti}
{109000}{}{Graffiti}
{109100}{}{Graffiti}
{109200}{}{Graffiti}
{109300}{}{Graffiti}
{109400}{}{Graffiti}
{109500}{}{Graffiti}
{109600}{}{Graffiti}
{109700}{}{Graffiti}
{109800}{}{Graffiti}
{109900}{}{Graffiti}
{110000}{}{Graffiti}
{110100}{}{Graffiti}
{110200}{}{Graffiti}
{110300}{}{Graffiti}
{110400}{}{Graffiti}
{110500}{}{Graffiti}
{110600}{}{Graffiti}
{110700}{}{Graffiti}
{110800}{}{Graffiti}
{110900}{}{Graffiti}
{111000}{}{Tábla}
{111100}{}{Tábla}
{111200}{}{Tábla}
{111300}{}{Tábla}
{111400}{}{Tábla}
{111500}{}{Tábla}
{111600}{}{Tábla}
{111700}{}{Tábla}
{111800}{}{Tapéta}
{111900}{}{Tapéta}
{112000}{}{Tapéta}
{112100}{}{Tapéta}
{112200}{}{Tapéta}
{112300}{}{Tapéta}
{112400}{}{Tapéta}
{112500}{}{Tapéta}
{112600}{}{Tapéta}
{112700}{}{Tapéta}
{112800}{}{Tapéta}
{112900}{}{Tapéta}
{113000}{}{Tapéta}
{113100}{}{Tapéta}
{113200}{}{Tapéta}
{113300}{}{Tapéta}
{113400}{}{Tapéta}
{113500}{}{Tapéta}
{113600}{}{Tapéta}
{113700}{}{Tapéta}
{113800}{}{Tapéta}
{113900}{}{Tapéta}
{114000}{}{Tapéta}
{114100}{}{Filmfelvevõ}
{114200}{}{Koporsó}
{114300}{}{Koporsó}
{114400}{}{Koporsó}
{114500}{}{Koporsó}
{114600}{}{Acélrudak}
{114700}{}{Acélrudak}
{114800}{}{Acélzsalu}
{114900}{}{Acélzsalu}
{115000}{}{Lézeres csapda}
{115100}{}{Lézeres csapda}
{115200}{}{Csille}
{115300}{}{Csille acélrúddal}
{115400}{}{Csille dinamittal}
{115500}{}{"Zárva"}
{115600}{}{"Zárva"}
{115700}{}{"Bordélyház"}
{115800}{}{"Vic"}
{115900}{}{Fal}
{116000}{}{Fal}
{116100}{}{Retinaszkenner}
{116101}{}{Ez egy biztonsági berendezés, ami a retinák leolvasásán és ellenõrzésén alapul.}
{116200}{}{"Irányítószoba"}
{116300}{}{"Irányítószoba"}
{116400}{}{"Irányítószoba"}
{116500}{}{"Építkezés"}
{116600}{}{"Építkezés"}
{116700}{}{Gép}
{116701}{}{Egy üzemképtelen masinéria.}
{116800}{}{Gép}
{116801}{}{Egy mûködésképtelen gépecske.}
{116900}{}{Ajtó}
{117000}{}{Ajtó}
{117100}{}{Csövek}
{117101}{}{Ezek a csövek a reaktorba vezetnek.}
{117200}{}{Tartály}
{117300}{}{Tartályok}
{117400}{}{Tartályok}
{117500}{}{Tartályok}
{117600}{}{Szellõztetõ}
{117700}{}{Szellõztetõ}
{117800}{}{A "Hárfa" cégére}
{117900}{}{Fûrészbak}
{118000}{}{Fûrészbak}
{118100}{}{Fûrészbak}
{118200}{}{Szellõztetõ}
{118300}{}{Szellõztetõ}
{118400}{}{"Gépészbolt"}
{118500}{}{"Menedzseri iroda"}
{118600}{}{"Raktár"}
{118700}{}{"Sugárzásveszély!"}
{118800}{}{Gõz}
{118900}{}{Gép}
{118901}{}{Az erõmû egyik masinája.}
{119000}{}{Tartály}
{119100}{}{Tûz}
{119200}{}{Víz}
{119300}{}{"Prémvadász Város"}
{119400}{}{"Arany Gekkó"}
{119500}{}{"Fürdõház"}
{119600}{}{Barlangrajz}
{119700}{}{Barlangrajz}
{119800}{}{Barlangrajz}
{119900}{}{Barlangrajz}
{120000}{}{Tûzhely}
{120100}{}{Barlangfal}
{120200}{}{Barlangfal}
{120300}{}{Barlangfal}
{120400}{}{Barlangfal}
{120500}{}{Barlangfal}
{120600}{}{Barlangfal}
{120700}{}{Barlangfal}
{120800}{}{Barlangfal}
{120900}{}{Barlangfal}
{121000}{}{Barlangfal}
{121100}{}{Barlangfal}
{121200}{}{Barlangfal}
{121300}{}{Barlangfal}
{121400}{}{Barlangfal}
{121500}{}{Barlangfal}
{121600}{}{Karó}
{121601}{}{Úgy látszik, ebbe a karóba már belehúztak valakit!}
{121700}{}{Karó}
{121701}{}{A karóbahúzás nem valami szép halál!}
{121800}{}{Karó}
{121801}{}{Vajon mióta feszít ez a lény a karón?}
{121900}{}{Karó}
{121901}{}{Mindenkinek megvan a maga karója...}
{122000}{}{Karó}
{122001}{}{Ennek valami biztos szöget ütött a fejébe.}
{122100}{}{Karó}
{122101}{}{Ez az ember kapott egy karót.}
{122200}{}{Karó}
{122201}{}{Egy koponya látható ízlésesen elhelyezve egy karó tetejébe.}
{122300}{}{Karó}
{122301}{}{Karó koponyával. Olyan szép, hogy akár Munkácsi is megfesthette volna.}
{122400}{}{Karó}
{122401}{}{Úgy néz ki, ez a karó már csak a hozzátartozó fejet várja.}
{122500}{}{Karó}
{122501}{}{Ez a karó még üres egyelõre. De meddig?}
{122600}{}{Karó}
{122601}{}{A karó várja kedves (karóba) húzakodó ügyfeleit...}
{122700}{}{Karó}
{122701}{}{Nyilván erre a karóra is kerül majd varjú.}
{122800}{}{"Körözvény"}
{122801}{}{Ez a kép nagyon hasonlít rád! Pedig a sok akcióban elég nehéz lehetett elkapni a vonásaidat.}
{122900}{}{Padló}
{123000}{}{Kikapcsolt roboagy}
{123001}{}{Egy kissé szétszórt kibernetikus szerkezet.}
{123100}{}{Tarack}
{123101}{}{Ezt a furcsa valamit már láttad valahol. Hol is? Talán a történelem könyvedben. Igen, ez háború elõtt ereklye. De hogy kerül ez ide?}
{123200}{}{Tábla}
{123300}{}{Tábla}
{123400}{}{Tábla}
{123500}{}{Tábla}
{123600}{}{Fõkapcsoló}
{123700}{}{Kereszt}
{123800}{}{Kereszt}
{123900}{}{Kereszt}
{124000}{}{Kereszt}
{124100}{}{Kereszt}
{124200}{}{Kereszt}
{124300}{}{Benzintöltõ}
{124400}{}{Benzintöltõ}
{124500}{}{Benzintöltõ}
{124600}{}{"Pep benzinkútja" cégér}
{124700}{}{Árnyék}
{124800}{}{Alom}
{124900}{}{Alom}
{125000}{}{Alom}
{125100}{}{Alom}
{125200}{}{Alom}
{125300}{}{Alom}
{125400}{}{"Dusty Ebédlõje"}
{125500}{}{Bob és fia}
{125501}{}{Egy utcai árus standja.}
{125600}{}{Bob és fia}
{125601}{}{Ez egy utcai árus.}
{125700}{}{Bob és fia}
{125701}{}{Hm. Egy utcai árus.}
{125800}{}{Bob és fia}
{125801}{}{Ez a stand egy utcai árushoz tartozik.}
{125900}{}{"ÚKK"}
{126000}{}{"Kongresszusi terem"}
{126100}{}{"Kongresszusi terem"}
{126200}{}{ÚKK plakát}
{126300}{}{ÚKK plakát}
{126400}{}{ÚKK plakát}
{126500}{}{ÚKK plakát}
{126600}{}{"Rawhide Szalon"}
{126700}{}{"Kaszinó"}
{126800}{}{"Kaszinó"}
{126900}{}{"Kaszinó"}
{127000}{}{"Kaszinó"}
{127100}{}{"Kaszinó"}
{127200}{}{"Kaszinó"}
{127300}{}{Kõrakás}
{127301}{}{Ezek a kövek valamit hordanak a szívük alatt.}
{127400}{}{Gerenda}
{127500}{}{Gerenda}
{127600}{}{Gerenda}
{127700}{}{Gerenda}
{127800}{}{Gerenda}
{127900}{}{Gerenda}
{128000}{}{Gerenda}
{128100}{}{Gerenda}
{128200}{}{Gerenda}
{128300}{}{Gerenda}
{128400}{}{Árnyék}
{128500}{}{Árnyék}
{128600}{}{Árnyék}
{128700}{}{Árnyék}
{128800}{}{Árnyék}
{128900}{}{Árnyék}
{129000}{}{Árnyék}
{129100}{}{Árnyék}
{129200}{}{Árnyék}
{129300}{}{Liftpálya}
{129400}{}{Benzintöltõ}
{129500}{}{Benzintöltõ}
{129600}{}{Benzintöltõ}
{129700}{}{Kötél}
{129800}{}{Lyuk}
{129900}{}{Brahminhús}
{130000}{}{Brahminhús}
{130100}{}{Brahminhús}
{130200}{}{Brahminhús}
{130300}{}{Brahminhús}
{130400}{}{Brahminhús}
{130500}{}{Gerenda}
{130600}{}{Gerenda}
{130700}{}{Gerenda}
{130800}{}{Gerenda}
{130900}{}{Gerenda}
{131000}{}{Gerenda}
{131100}{}{Gerenda}
{131200}{}{Gerenda}
{131300}{}{Árnyék}
{131400}{}{Árnyék}
{131500}{}{Árnyék}
{131600}{}{Árnyék}
{131700}{}{Árnyék}
{131800}{}{Árnyék}
{131900}{}{Árnyék}
{132000}{}{Árnyék}
{132100}{}{Vér}
{132200}{}{Vér}
{132300}{}{Vér}
{132400}{}{Vér}
{132500}{}{Vér}
{132600}{}{Vér}
{132700}{}{Vér és csontok}
{132800}{}{Vér és csontok}
{132900}{}{Vér és csontok}
{133000}{}{A barlang szája}
{133100}{}{Felszerelés}
{133200}{}{Felszerelés}
{133300}{}{Felszerelés}
{133400}{}{Felszerelés}
{133500}{}{Számítógép}
{133501}{}{Egy menedékbeli terminál, rákapcsolódva a Menedék fõszámítógépére.}
{133600}{}{Számítógép}
{133601}{}{A menedék egyik számítógépes terminálja, ami a központi számítógéphez csatlakozik.}
{133700}{}{Menedékváros kapuja}
{133800}{}{Menedékváros kapuja}
{133900}{}{Fal}
{134000}{}{Fal}
{134100}{}{Fal}
{134200}{}{Fal}
{134300}{}{Fal}
{134400}{}{Fal}
{134500}{}{Fal}
{134600}{}{Fal}
{134700}{}{Ajtó}
{134800}{}{Kirobbantott ajtó}
{134900}{}{Ajtótörmelék}
{135000}{}{Épület}
{135100}{}{Épület}
{135200}{}{Épület}
{135300}{}{Épület}
{135400}{}{Épület}
{135500}{}{Épület}
{135600}{}{Épület}
{135700}{}{Épület}
{135800}{}{Ajtó}
{135900}{}{Templom}
{136000}{}{Templom}
{136100}{}{Templom}
{136200}{}{Templom}
{136300}{}{Templom}
{136400}{}{Templom}
{136500}{}{Tûzhely}
{136600}{}{Tûzhely}
{136700}{}{Tarack}
{136701}{}{Ez a különös kinézetû ágyú mintha a háború elõtti szép napokból származó egyik relikvia lenne. Vajon hogy kerülhetett ide?}
{136800}{}{Templom}
{136900}{}{Templom}
{137000}{}{Hegy}
{137100}{}{Barlang}
{137200}{}{Ajtósín}
{137300}{}{Fáklya}
{137301}{}{Egy égõ fáklya egy fali tartóban.}
{137400}{}{Fáklya}
{137401}{}{A falon található fáklyatartóban ég.}
{137500}{}{Fáklya}
{137501}{}{A fáklya egy falra szerelt tartóban ég.}
{137600}{}{Fáklya}
{137601}{}{A fáklya vígan ég a falra illesztett tartójában.}
{137700}{}{Gépmadár}
{137701}{}{HOSSZÚ.}
{137800}{}{Lerombolt ajtó}
{137801}{}{Az energiaállomás ajtaja megsemmisült.}
{137900}{}{Lerombolt ajtó}
{137901}{}{Valahogy tönkrement az energiaállomás bejárata.}
{138000}{}{Fal}
{138100}{}{Fal}
{138200}{}{Fal}
{138300}{}{Fal}
{138400}{}{Fal}
{138500}{}{Fal}
{138600}{}{Lámpa}
{138700}{}{Ajtó}
{138800}{}{Ajtó}
{138900}{}{Ajtó}
{139000}{}{Ajtó}
{139100}{}{Ajtó}
{139200}{}{Ajtó}
{139300}{}{Zászló}
{139400}{}{Pózna}
{139500}{}{Post}
{139600}{}{Zászló}
{139700}{}{Zászló}
{139800}{}{Pózna}
{139900}{}{Pózna}
{140000}{}{Zászló}
{140100}{}{Árnyék}
{140200}{}{Árnyék}
{140300}{}{Zászló}
{140400}{}{Zászló}
{140500}{}{Zászló}
{140600}{}{Zászló}
{140700}{}{"Cat's Paw"}
{140800}{}{"Cat's Paw"}
{140900}{}{Tábla}
{141000}{}{Jungle edzõterem cégére}
{141100}{}{Jungle edzõterem cégére}
{141200}{}{Jungle edzõterem cégére}
{141300}{}{"Renesco Patikája"}
{141400}{}{"New Reno-i fegyverbolt"}
{141500}{}{"Salvatore bárja"}
{141600}{}{Szobor}
{141700}{}{Raktárház ajtaja}
{141800}{}{Raktárház ajtaja}
{141900}{}{"Johnson doki"}
{142000}{}{"Seriff"}
{142100}{}{"Malamut Szalon"}
{142200}{}{"Morningstar bánya"}
{142300}{}{"Kokowebe bánya"}
{142400}{}{"Kokowebe bánya"}
{142500}{}{"Kokowebe bánya"}
{142600}{}{Jelzõtábla}
{142601}{}{Ez a fából készült tábla New Reno és a "Pokol" felé mutat. Arra gyanakszol, hogy felcserélték az irányokat.}
{142700}{}{"1"}
{142800}{}{"2"}
{142900}{}{"3"}
{143000}{}{"4"}
{143100}{}{"5"}
{143200}{}{"6"}
{143300}{}{Kötél}
{143301}{}{Ezzel a kötéllel át tudsz mászni a falon.}
{143400}{}{Ajtó}
{143500}{}{Ajtó}
{143600}{}{Ablak}
{143700}{}{Ablak}
{143800}{}{Ablak}
{143900}{}{Ablak}
{144000}{}{Ablak}
{144100}{}{Ablak}
{144200}{}{Ablak}
{144300}{}{Ablak}
{144400}{}{Ablak}
{144500}{}{Ablak}
{144600}{}{Ablak}
{144700}{}{Ablak}
{144800}{}{Medencelétra}
{144900}{}{Ajtó}
{145000}{}{Boltív}
{145100}{}{Boltív}
{145200}{}{Boltív}
{145300}{}{Boltív}
{145400}{}{Boltív}
{145500}{}{Boltív}
{145600}{}{Boltív}
{145700}{}{Boltív}
{145800}{}{Árnyék}
{145900}{}{Árnyék}
{146000}{}{Árnyék}
{146100}{}{Boltív}
{146200}{}{Boltív}
{146300}{}{Boltív}
{146400}{}{Árnyék}
{146500}{}{Árnyék}
{146600}{}{Kiskapu}
{146700}{}{Kiskapu}
{146800}{}{Parancsnoki szék}
{146801}{}{Ez az a hely, ahol általában a Felvigyázó ülni szokott.}
{146900}{}{Szakadék}
{147000}{}{Szakadék}
{147100}{}{Szakadék}
{147200}{}{Szakadék}
{147300}{}{A kaszinó bejárata}
{147400}{}{A kaszinó bejárata}
{147500}{}{Szõnyeg}
{147600}{}{A kaszinó bejárata}
{147700}{}{A kaszinó bejárata}
{147800}{}{A kaszinó bejárata}
{147900}{}{Kaszinóajtó}
{148000}{}{Kaszinóajtó}
{148100}{}{A kaszinó bejárata}
{148200}{}{A kaszinó bejárata}
{148300}{}{A kaszinó bejárata}
{148400}{}{A kaszinó bejárata}
{148500}{}{A kaszinó bejárata}
{148600}{}{A kaszinó bejárata}
{148700}{}{A kaszinó bejárata}
{148800}{}{A kaszinó bejárata}
{148900}{}{A kaszinó bejárata}
{149000}{}{A kaszinó bejárata}
{149100}{}{Kaszinóajtó}
{149200}{}{Kaszinóajtó}
{149300}{}{Falilámpa}
{149400}{}{Falilámpa}
{149500}{}{Falilámpa}
{149600}{}{Falilámpa}
{149700}{}{Falilámpa}
{149800}{}{Fal}
{149900}{}{Fal}
{150000}{}{Ventillátor}
{150100}{}{Ventillátor}
{150200}{}{Tûzoltó készülék}
{150300}{}{Tûzoltó készülék}
{150400}{}{Csõ}
{150500}{}{Elosztó}
{150600}{}{Elosztó}
{150700}{}{Fal}
{150800}{}{Fal}
{150900}{}{Fal}
{151000}{}{Fal}
{151100}{}{Fal}
{151200}{}{Fal}
{151300}{}{Fal}
{151400}{}{Fal}
{151500}{}{Fal}
{151600}{}{Fa borítás}
{151700}{}{Fa borítás}
{151800}{}{Csõ}
{151900}{}{Csõ}
{152000}{}{Csõ}
{152100}{}{Csõ}
{152200}{}{Csõ}
{152300}{}{Csõ}
{152400}{}{Csõ}
{152500}{}{Csõ}
{152600}{}{Csõ}
{152700}{}{Csõ}
{152800}{}{Csõ}
{152900}{}{Légkondi}
{153000}{}{Légkondi}
{153100}{}{Ajtó}
{153200}{}{Ajtó}
{153300}{}{Ajtó}
{153400}{}{Ajtó}
{153500}{}{Ajtó}
{153600}{}{Ajtó}
{153700}{}{Zuhanyzó}
{153800}{}{Az ûrsikló fala}
{153900}{}{Az ûrsikló fala}
{154000}{}{Az ûrsikló fala}
{154100}{}{Az ûrsikló fala}
{154200}{}{Az ûrsikló fala}
{154300}{}{Az ûrsikló fala}
{154400}{}{Az ûrsikló fala}
{154500}{}{Az ûrsikló fala}
{154600}{}{Az ûrsikló fala}
{154700}{}{Az ûrsikló fala}
{154800}{}{Erõtér}
{154900}{}{Erõtér}
{155000}{}{Szerv-eltávolító egység}
{155001}{}{A Menedék-Tek legújabb "Csináld Magad" típusú sebészeti egysége. A kívánt szervet automatikusan eltávolítja egy gombnyomásra.}
{155100}{}{Ûrsikló}
{155200}{}{Ûrsikló}
{155300}{}{Ûrsikló}
{155400}{}{Ûrsikló}
{155500}{}{Ûrsikló}
{155600}{}{Ûrsikló}
{155700}{}{Ûrsikló}
{155800}{}{Ûrsikló}
{155900}{}{Ûrsikló}
{156000}{}{Ûrsikló}
{156100}{}{Ûrsikló}
{156200}{}{Ûrsikló}
{156300}{}{Ûrsikló}
{156400}{}{Ûrsikló}
{156500}{}{Ûrsikló}
{156600}{}{Árnyék}
{156700}{}{Árnyék}
{156800}{}{Árnyék}
{156900}{}{Árnyék}
{157000}{}{Árnyék}
{157100}{}{Árnyék}
{157200}{}{Trónus}
{157300}{}{Ajtó}
{157400}{}{Ajtó}
{157500}{}{Ajtó}
{157600}{}{Ajtó}
{157700}{}{Légkondi}
{157800}{}{AutoDoki}
{157801}{}{Az AutoDokit betegségek gyógyítására és különbözõ drogok beadására tervezték.}
{157900}{}{Szobor}
{157901}{}{Egy híres menedéklakó szobra.}
{158000}{}{Kõhalmaz}
{158100}{}{Erõtér}
{158101}{}{Egy erõtér állja az utadat.}
{158200}{}{Erõtér}
{158201}{}{Egy erõtér akadályoz meg a továbbjutásban.}
{158300}{}{Erõtér}
{158301}{}{Ez az erõtér felelõs azért, hogy nem tudsz továbbmenni.}
{158400}{}{Erõtér}
{158401}{}{Elállja az utad.}
{158500}{}{Tartályhajó}
{158600}{}{Tartályvagon}
{158700}{}{Tartályvagon}
{158800}{}{Tartályvagon}
{158900}{}{Tartályvagon}
{159000}{}{Tartályvagon}
{159100}{}{Tartályvagon}
{159200}{}{Tartályvagon}
{159300}{}{Tartályvagon}
{159400}{}{Tartályvagon}
{159500}{}{Tartályvagon}
{159600}{}{Tartályvagon}
{159700}{}{Tartályvagon}
{159800}{}{Tartályvagon}
{159900}{}{Tartályvagon}
{160000}{}{Fal}
{160100}{}{Fal}
{160200}{}{Benyomódás a padlón}
{160300}{}{Kõpad}
{160400}{}{Kõpad}
{160500}{}{Füstölõ}
{160600}{}{Parabola antenna}
{160700}{}{Parabola antenna}
{160800}{}{Árnyék}
{160900}{}{Dokk árnyék}
{161000}{}{Dokk árnyék}
{161100}{}{Dokk árnyék}
{161200}{}{Dokk árnyék}
{161300}{}{Gerenda}
{161400}{}{Gerenda}
{161500}{}{Dokk árnyék}
{161600}{}{Dokk árnyék}
{161700}{}{Dokk árnyék}
{161800}{}{Dokk árnyék}
{161900}{}{Lépcsõ}
{162000}{}{Kikapcsolt kiberkutya}
{162001}{}{Ez egy hatástalanított kiberkutya.}
{162100}{}{Lerombolt generátor}
{162101}{}{Egy szétvert áramgenerátort látsz.}
{162200}{}{Sín}
{162300}{}{Sín}
{162400}{}{Sín}
{162500}{}{Csille}
{162600}{}{Csille acélrúddal}
{162700}{}{Csille dinamittal}
{162800}{}{Lerobbant csille}
{162900}{}{Csille}
{163000}{}{Biliárdasztal}
{163100}{}{Biliárdasztal}
{163200}{}{Biliárdasztal}
{163300}{}{Biliárdasztal}
{163400}{}{Biliárdasztal}
{163500}{}{Biliárdasztal}
{163600}{}{Asztal}
{163700}{}{Zászló}
{163800}{}{Fal}
{163900}{}{Fal}
{164000}{}{Fal}
{164100}{}{Fal}
{164200}{}{Kiömlõ nyílás}
{164300}{}{Asztal}
{164400}{}{Asztal}
{164500}{}{Lépcsõ lefelé}
{164600}{}{Lépcsõ felfelé}
{164700}{}{Lépcsõ felfelé}
{164800}{}{Lépcsõ felfelé}
{164900}{}{Nagy-számítógép}
{165000}{}{Nagy-számítógép}
{165100}{}{Nagy-számítógép}
{165200}{}{"Karaván iroda"}
{165300}{}{Ravatal}
{165400}{}{Ravatal}
{165500}{}{Bányalift}
{165600}{}{Bányalift}
{165700}{}{Zászlórúd}
{165800}{}{ÚKK zászló}
{165900}{}{"Poseidon üzemanyag"}
{166000}{}{Lépcsõ lefelé}
{166100}{}{"Klinika"}
{166200}{}{"Nevelõ Központ"}
{166300}{}{"Vámhivatal"}
{166400}{}{"Vámhivatal"}
{166500}{}{"Üdvözlõ Hivatal"}
{166600}{}{"Boldog Harry"}
{166700}{}{"A lyuk"}
{166800}{}{"Információs Központ"}
{166900}{}{"Információs Központ"}
{167000}{}{"Menedékváros"}
{167100}{}{"Fõtanács"}
{167200}{}{"Fõtanács"}
{167300}{}{Karbantartó központ}
{167400}{}{"A Szalon"}
{167500}{}{"Csapszék"}
{167600}{}{"Westin marhatelep"}
{167700}{}{"Komfort Osztály"}
{167800}{}{"A Épület"}
{167900}{}{"B Épület"}
{168000}{}{Szolgaközvetítõ Központ}
{168100}{}{Szolgaközvetítõ Központ}
{168200}{}{"Komfort Hivatal"}
{168300}{}{"Komfort Hivatal"}
{168400}{}{Bányalift}
{168500}{}{Bányalift}
{168600}{}{Bányalift}
{168700}{}{Bányalift}
{168800}{}{Gépmadár}
{168900}{}{Gépmadár}
{169000}{}{Gépmadár}
{169100}{}{Gépmadár}
{169200}{}{Gépmadár}
{169300}{}{Árnyék}
{169400}{}{Árnyék}
{169500}{}{Árnyék}
{169600}{}{Árnyék}
{169700}{}{Lezuhant Gépmadár}
{169800}{}{Lezuhant Gépmadár}
{169900}{}{Lezuhant Gépmadár}
{170000}{}{Lezuhant Gépmadár}
{170100}{}{Lezuhant Gépmadár}
{170200}{}{Lezuhant Gépmadár}
{170300}{}{Árnyék}
{170400}{}{Árnyék}
{170500}{}{Árnyék}
{170600}{}{Lerombolt híd}
{170601}{}{Az Arroyo-híd maradványait látod. Most már nincs visszaút a faluba.}
{170700}{}{Lerombolt híd}
{170701}{}{Ennyi maradt Arroyóból. A faluba már nem tudsz visszajutni.}
{170800}{}{Kanyon}
{170900}{}{Ajtó}
{171000}{}{Ajtó}
{171100}{}{Fal}
{171200}{}{Fal}
{171300}{}{Fal}
{171400}{}{Fal}
{171500}{}{Fal}
{171600}{}{Fal}
{171700}{}{Fal}
{171800}{}{Fal}
{171900}{}{Légkondi}
{172000}{}{Légkondi}
{172100}{}{Golyóálló üveg}
{172200}{}{Golyóálló üveg}
{172300}{}{Golyóálló üveg}
{172400}{}{Nehézlézer-löveg}
{172500}{}{Nehézlézer-löveg}
{172600}{}{Kövek}
{172700}{}{Kövek}
{172800}{}{Kövek}
{172900}{}{Kövek}
{173000}{}{Kövek}
{173100}{}{Kövek}
{173200}{}{Kövek}
{173300}{}{Kövek}
{173400}{}{Kövek}
{173500}{}{Kövek}
{173600}{}{Kövek}
{173700}{}{"Becky Kaszinója"}
{173800}{}{"Becky Kaszinója"}
{173900}{}{"Utolsó lehelet"}
{174000}{}{"Mama fõztje"}
{174100}{}{"Rabszolga-kereskedõ"}
{174200}{}{"Túlélõ/Cucc"}
{174300}{}{"Tubby kocsmája"}
{174400}{}{"Tubby kocsmája"}
{174500}{}{A bányalift kapuja}
{174600}{}{Ventillátor}
{174700}{}{Ventillátor}
{174800}{}{Az elnök irodájának ajtaja}
{174900}{}{Ábra a szemrõl}
{175000}{}{Romok}
{175100}{}{Az Örökkévalóság Õrzõje}
{175200}{}{"Nem mûködik"}
{175300}{}{Beszakadt padló}
{175400}{}{WC}
{175500}{}{Kereszt}
{175600}{}{Fal}
{175700}{}{Fal}
{175800}{}{Fal}
{175900}{}{Fal}
{176000}{}{Fal}
{176100}{}{Fal}
{176200}{}{Fal}
{176300}{}{Fal}
{176400}{}{Épület}
{176500}{}{Épület}
{176600}{}{Épület}
{176700}{}{Épület}
{176800}{}{Épület}
{176900}{}{Épület}
{177000}{}{Acéltámaszték}
{177100}{}{Acéltámaszték}
{177200}{}{Acéltámaszték}
{177300}{}{Víz}
{177400}{}{Víz}
{177500}{}{Víz}
{177600}{}{Víz}
{177700}{}{Víz}
{177800}{}{Víz}
{177900}{}{Vízesés}
{178000}{}{Út}
{178100}{}{Út}
{178200}{}{Út}
{178300}{}{Út}
{178400}{}{Út}
{178500}{}{Út}
{178600}{}{Út}
{178700}{}{Hídtámaszték}
{178800}{}{Hídtámaszték}
{178900}{}{Hídtámaszték}
{179000}{}{Kerítés}
{179100}{}{Lámpa}
{179200}{}{Lámpa}
{179300}{}{Döglött bálna}
{179301}{}{Úgy látszik, ez a bálna jó magasról eshetett le.}
{179400}{}{Döglött bálna}
{179401}{}{Ez bálna mintha nagy magasságból szédült volna le.}
{179500}{}{Bálnauszony}
{179501}{}{A döglött bálna uszonya.}
{179600}{}{Bálnaszem}
{179601}{}{A megboldogult bálna egyik szeme.}
{179700}{}{Bálnadarab}
{179701}{}{A bálna egyik darabja.}
{179800}{}{Bálnadarab}
{179801}{}{Ez a bálna egyik testrésze.}
{179900}{}{Bálnadarab}
{179901}{}{Ez a bálna kicsit szétszórt.}
{180000}{}{Bálnadarab}
{180001}{}{A bálna földi maradványai.}
{180100}{}{Bálnadarab}
{180101}{}{Ez a bálna bárcsak kiabálna.}
{180200}{}{A Fõnök lábai}
{180300}{}{Kövek}
{180400}{}{Kövek}
{180500}{}{Kövek}
{180600}{}{Kövek}
{180700}{}{"Tímár"}
{180800}{}{"Rose Panziója}
{180900}{}{"Vortis Holding"}
{181000}{}{"Vortis Holding"}
{181100}{}{"Nagy Wanamingo bánya"}
{181200}{}{"Ascorti Ásza"}
{181300}{}{Lezuhant ûrhajó}
{181301}{}{Valamiféle ûrsikló. Úgy látszik, nemrég pottyant ide.}
{181400}{}{Koporsó}
{181500}{}{"Marhatenyésztõk Szövetsége"}
{181600}{}{"Mészárszék"}
{181700}{}{Palánk}
{181800}{}{Fa ajtó}
{181900}{}{Fa ajtó}
{182000}{}{Hûtõ}
{182100}{}{Hûtõ}
{182200}{}{Kályha}
{182300}{}{Kályha}
{182400}{}{Kályha}
{182500}{}{Kályha}
{182600}{}{Cucc}
{182700}{}{Cucc}
{182800}{}{Cucc}
{182900}{}{Cucc}
{183000}{}{Cucc}
{183100}{}{Cucc}
{183200}{}{Cucc}
{183300}{}{Cucc}
{183400}{}{Az elnök széke}
{183500}{}{Lépcsõ}
{183600}{}{Világtérkép}
{183700}{}{Szituációs térkép}
{183800}{}{Haditanácskozó asztal}
{183900}{}{Tanácskozó asztal}
{184000}{}{Tanácskozó asztal}
{184100}{}{Haditanácskozó asztal}
{184200}{}{Fa}
{184300}{}{Fa}
{184400}{}{Rámpa}
{184500}{}{Golden Globes Filmstúdió}
{184600}{}{Kormánykerék}
{184700}{}{Sebességszabályzó}
{184800}{}{Kommunikációs állomás}
{184900}{}{Konzol}
{185000}{}{Zsalu}
{185100}{}{Gõz}
