{100}{}{Bõrpáncél}
{101}{}{Az legalapvetõbb teljesen bõr ruházatod. Finoman szabott cserzett brahminbõrbõl készült.}
{200}{}{Fémpáncél}
{201}{}{Fényezett fémlapok félelmetes fergetege, melyek vadul villogó vértben végzõdnek.}
{300}{}{Energiapáncél}
{301}{}{Univerzális ruházat, mely a legújabb technológiákkal készült. Energiáját egy mikrofúziós reaktor adja, amely elegendõ hajtóanyaggal rendelkezik legalább vagy száz évig.}
{400}{}{Kés}
{401}{}{Egy pengeéles szúró- és vágófegyver. Min. ER: 2.}
{500}{}{Tomfa}
{501}{}{A katonaság vagy a rendõrség által használt népnevelõ eszköz. Tömör fa az anyaga. Min. ER: 3.}
{600}{}{Pöröly}
{601}{}{Nagy kalapács, mely hosszú bottal jár... Nagyon kedvelt az õt felemelni képes emberek körében. Min. ER: 6.}
{700}{}{Lándzsa}
{701}{}{Borotvaéles végû, botszerû fegyver. A nyele fából készült, az hegye pedig edzett acél. Min. ER: 4.}
{800}{}{10 mm-es pisztoly}
{801}{}{10 mm-es Colt 6520 öntöltõ pisztoly. Az elsütõ billentyû minden egyes meghúzásakor automatikusan csõre tölti a lõszert, amíg a tár ki nem ürül. A nagyerejû 10 mm-es lövedékeket kibocsájtó lõfegyver csak egyes lövések leadására képes. Min. ER: 3.}
{900}{}{10 mm-es GPI}
{901}{}{Heckler & Koch MP9-es géppisztoly (10 mm-es változat). Közepes méretû GPI, mely képes egyes lövések és sorozatok leadására is. Min. ER: 4.}
{1000}{}{Vadászpuska}
{1001}{}{.223-as kaliberû (5,56 mm-es) Colt Rangemaster félautomata vadászpuska. Csak egyes lövés adható le vele. Min. ER: 5.}
{1100}{}{Lángszóró}
{1101}{}{A Flambe 450 típusú lángvetõ csibészesebb verziója. Nagyon forró, gyúlékony folyadékot permetez, igen kis hatótávban. Különleges adalékokkal kezelt üzemanyagra van szükség a használatához. Min. ER: 6.}
{1200}{}{Gépágyú}
{1201}{}{Rockwell CZ53-as kézi gépágyú. Ez egy többcsöves forgófejes gépfegyver, amely 5 mm-es lövedékeket küld útjára, megközelítõleg 60.000-es fordulatszámmal. Min. ER: 7.}
{1300}{}{Rakétavetõ}
{1301}{}{A Rockwell cég BigBazooka fantázianevét viselõ rakétavetõje, kiegészítve egy 3 fontos (1,36 kg-os) ráadás elsütõbillentyûvel. Mind PT (Páncéltörõ), mind robbanófejes rakétákat is képes kilõni. Min. ER: 6.}
{1400}{}{Robbanófejes rakéta}
{1401}{}{Ez egy mezei rakéta, egy bazi nagy robbanófejjel a végén.}
{1500}{}{Plazmafegyver}
{1501}{}{P94 típusú plazmafegyver. Nos, ez egy ipari energiafegyver, amely izzó, tüzes plazmasugarakat lõ ki arra, amerre a szupravezetõbõl készült csöve mutat. Energiáját mikrofúziós elemekbõl meríti. Min. ER: 6.}
{1600}{}{Lézerpisztoly}
{1601}{}{Wattz 1000 gyártmányú lézerpisztoly. Ez egy utcai változat, ezért a teljesítménye kisebb, mint a rendõrségi vagy a katonai modelleké. Mûködtetéséhez kis elemekre van szükség. Min. ER: 3.}
{1700}{}{Harci páncél}
{1701}{}{A csúcstechnológia egyik mûremeke, védõpolimerek segítségével készült.}
{1800}{}{.44-es Desert Eagle}
{1801}{}{Egy korosodó .44-es magnum pisztoly, a Desert Eagle. A XX. századi késõi filmjeiben (pl. Mátrix) való számtalan szereplése tette minden idõk egyik legnépszerûbb maroklõfegyverévé. Min ER: 4.}
{1900}{}{Kõdarab}
{1901}{}{Ez nem más, mint egy kõdarab, amit a Szilárd Gránit Kft. alkotott meg. Ez a modell az utóbbi idõben komoly fejlesztéseken ment át. Min. ER: 1.}
{2000}{}{Feszítõvas}
{2001}{}{Egy nagyon kemény és súlyos fémdarab, amelyet legfõképp arra terveztek, hogy emelõerõt tudjunk rajta keresztül kifejteni. Vagy éppen az ütõerõnket... Min. ER: 5.}
{2100}{}{Boxer}
{2101}{}{Acélos csengésû - kivételesen acélból is készített, ökölre húzható marokfegyver. Hasznos segítség: megvédi a bütyköket, többet lehet vele sebezni (ha éppen páncélozatlan az ellenfél...). Min. ER: 1.}
{2200}{}{14 mm-es pisztoly}
{2201}{}{Sig-Sauer típusú 14 mm-es automata pisztoly. Óriási méretû, egyes lövéseket leadó fegyver. Precízen megmunkált markolata az eszmei értékét növeli. Min. ER: 4.}
{2300}{}{Rohamfegyver}
{2301}{}{Egy 5 mm-es AK-112-es rohamfegyver. Egy régebbi katonai típus, már kb. a háború óta nem használja a kutya se. Képes egyenként vagy akár sorozatokban is szórni a nagy sebességû 5 mm-es lövedékeket. Min. ER: 5.}
{2400}{}{Plazmapisztoly}
{2401}{}{Glock 86-os plazmapisztoly, melyet a Gaston Glock mesterséges agy tervezett. Kis nyalábokban nagy hõmérsékletû plazmát lõ ki. Kis elemekkel lehet némileg mûködésre bírni. Min. ER: 4.}
{2500}{}{Repeszgránát}
{2501}{}{Rendszeresített repeszgránát. Egy kevéske nagy (feszítõ)erejû robbanószert tartalmaz, maga a külsõ borítás pedig a gyilkos repeszekbõl áll. Becsapódáskor robban. Min. ER: 3.}
{2600}{}{Plazmagránát}
{2601}{}{Mágnesesen lezárt, belsejében plazmát rejtõ fegyver, felszerelve a használatához szükséges detonátorral. Landoláskor a gránátból egy túlhevített plazmarobbanás tör ki. Min. ER: 4.}
{2700}{}{Elektrogránát}
{2701}{}{Elektromágneses gránát, amely a detonáció során sûrû mágneses mezõt hoz létre ott, ahol az földetért. Nincs hatással semmilyen szerves élõlényre. Min. ER: 4.}
{2800}{}{Gyorstüzelõ lézer}
{2801}{}{H&K L30-as gyorstüzelõ lézer. Közvetlenül katonai jellegû felhasználásra hozták létre, a háború kirobbanásakor ezek még csak prototípusként léteztek. A több csõvel lehetõvé válik, hogy hosszabb ideig lehessen vele tüzelni, mindenféle túlmelegedés nélkül. A mûködéséhez szükséges energiát mikrofúziós elemekbõl nyeri. Min. ER: 6.}
{2900}{}{10 mm-es JHP}
{2901}{}{Lõszer. Kaliber: 10 mm. Köpenyes üregeshegyû (vagyis Jacketed Hollow Point).}
{3000}{}{10 mm-es PT}
{3001}{}{10 mm-es páncéltörõ (PT) lövedék.}
{3100}{}{.44-es magnum JHP}
{3101}{}{Egy tár .44-es magnum fajtájú, ólomborítású, üreges hegyû lõszer.}
{3200}{}{Lángszóró-üzemanyag}
{3201}{}{Ebben a tartályban fokozottan gyúlékony folyadékot tárolnak, mely egyben a különbözõ lángszórók üzemanyagául szolgál.}
{3300}{}{14 mm-es PT}
{3301}{}{Mint a méretébõl (14 mm) is kiderül, ez egy nagy kaliberû, páncéltörõ (PT) lõszer.}
{3400}{}{.223-as FMJ}
{3401}{}{0,223 hüvelyk (5,56 mm) átmérõjû töltény, mely teljesen fémborítású (Full Metal Jacket).}
{3500}{}{5 mm-es JHP}
{3501}{}{Ez egy tár, amelyben kiskaliberû, könnyûsúlyú lõszer van. Jellemzõi: 5 mm-es átmerõ és köpenyegelt üreges hegy (Jacketed Hollow Point).}
{3600}{}{5 mm-es PT}
{3601}{}{Kiskaliberû, 5 mm-es páncéltörõ (PT) muníció van ebben a tárban.}
{3700}{}{PT rakéta}
{3701}{}{Rakéta, melyben ugyan kevesebb robbanóanyag van, de még mindig elég ahhoz, hogy páncéltörõnek (PT) tituláljuk.}
{3800}{}{Kis elem}
{3801}{}{Kis méretû, független energiatároló eszköz.}
{3900}{}{Mikrofúziós elem}
{3901}{}{Közepes méretû energiatermelõ egység. Saját fúziós telepe van.}
{4000}{}{Stimuláns}
{4001}{}{Gyógyító vegyület. Beadásakor azonnali gyógyulást eredményez a kisebb sérülések esetében.}
{4100}{}{Pénz}
{4101}{}{Törvényes fizetõeszköz pusztaságban.}
{4200}{}{Hûtõ}
{4201}{}{Egy hûtõszekrény, hûtõfolyadék nélkül.}
{4300}{}{Jégláda}
{4301}{}{Régi vágású jeges láda. Hmmm... a zsanérok még mindig feltûnõen jó állapotban vannak.}
{4400}{}{Jégláda}
{4401}{}{Egy jéggel töltött láda, még a letûnt korok idejébõl. A csuklópántok még mindig használhatóak!}
{4500}{}{Dobókés}
{4501}{}{Ez nem más mint egy kés, amely külön a dobásra van kiegyensúlyozva. Titánból készült, és dolgos lézerek fenték félelmtesen élesre. Min. ER: 3.}
{4600}{}{Zsák}
{4601}{}{Egy teljesen hétköznapi méretû zsák, melyet brahminszõrbõl szõttek.}
{4700}{}{Elsõsegély készlet}
{4701}{}{Egy kicsike csomag, amiben megtalálható a szükséges orvosi felszerelés: kötszer, fásli, fertõtlenítõ spray, és még rengeteg minden...}
{4800}{}{Radiodeaktivizátor}
{4801}{}{Vegyi oldat, mely megköti a radioaktív részecskéket és eltávolítja a szervezetbõl. De ehhez szüksége van némi idõre!}
{4900}{}{Ellenszer}
{4901}{}{Ebben a üvegben házilag kotyvasztott mérge elleni szer található. Nem más, mint valami tejes folyadék, amiben radskorpiók húsának darabjai ínycsiklandozóan üldözik egymást.}
{5000}{}{Fenntartott tárgy}
{5001}{}{Ez egy késõbbi célokra fenntartott tárgy. NE HASZNÁLD!}
{16500}{}{Iguánás stand}
{16501}{}{"Bob iguána falatkái". Mit nem lehet szeretni egy frissen sült iguánán...?}