#
# Quest descriptons
#
#    Please leave space between the areas (like 100 or so)
#


#
# Arroyo Quests
#
{100}{}{Irtsd ki a gonosz növényeket, amik megszállták Hakunin kertjét!}
{110}{}{Szerezz kovakövet, hogy Mynoc kiélesíthesse a lándzsádat!}
{120}{}{Mentsd meg Nagor kutyáját, Füstöt, aki csapdába esett a vadonban!}
{130}{}{Szerezz egy ÉLET-et Arroyo számára!}
{140}{}{Találd meg Vicet a kereskedõt!}

#
# Den Quests
#
{200}{}{Szabadítsd ki Vicet: vidd el neki klamath-i házából a rádióját, és fizesd ki az adósságát Metzgernek!}
{201}{}{Szabotáld Becky szeszlepárlóját!}
{202}{}{Szerezz egy üzemanyag-szabályozót Smittynek az autóhoz!}
{203}{}{Szerezd vissza Anna medálját!}
{204}{}{Hajtsd be Fred adósságát!}
{205}{}{Szerezd vissza a könyvet Derek-tõl!}
{206}{}{Vidd el Smittynek az ebédjét!}
{207}{}{Lara tudni akarja, mit õriznek a templomban.}
{208}{}{Kérj engedélyt Metzgertõl a bandaháborúhoz!}
{209}{}{Találj valami kihasználható gyengeséget a templomot õrzõ Tyler bandában!}
{210}{}{Segíts Larának legyõzni Tyler bandáját!}

#
# Klamath Quests
#
{300}{}{Gyújtsd be a szeszlepárlót!}
{301}{}{Keresd meg Smileyt, a prémvadászt!}
{302}{}{Védd meg a brahminokat!}
{303}{}{Hajtsd el a brahminokat!}
{304}{}{Öld meg a Patkánykirályt!}
{305}{}{Mentsd meg Torrt!}

#
# Modoc Quests
#
{400}{}{Fura dolgok történnek a Modoctól észak-keletre lévõ farmon. Nézz körül és jelentsd Jo-nak, hogy mit láttál!}
{401}{}{Cornelius elvesztette az aranyóráját. Találd meg és add vissza neki!}
{402}{}{Farrel megkért, hogy keresd meg Cornelius aranyóráját. Találd meg és vidd vissza Farrelnek!}
{403}{}{A kis Jonny eltûnt. Keresd meg és vidd haza Balthashoz!}
{404}{}{Jonny az Aljanép barlangjában van. Juttasd haza Balthashoz!}
{405}{}{Farrel kertjét ellepték a rágcsálók. Szabadulj meg tõlük!}
{406}{}{Juttasd el az Aljanép üzenetét Jo-hoz Modocba!}
{407}{}{Jo-nak aggályai vannak az Aljanéppel kapcsolatban. Vizsgáld meg a holttesteket a kísértet farmon, és tudd meg, mi történt Karllal!}
{408}{}{Menj el Rejtekbe, és szólj Karlnak, hogy nyugodtan hazamehet!}

#
# Vault City Quests
#
{500}{}{Szerezz egy ekét Mr. Smith számára!}
{501}{}{Vidd el Moore aktatáskáját Mr. Bishopnak New Renóba!}
{502}{}{Vigyél egy adag Jetet Dr. Troy részére!}
{503}{}{Oldd meg a gekkói erõmû problémáját!}
{504}{}{Vidd el Lynette hololemezét Westinnek az ÚKK-ba!}
{505}{}{Szabadítsd ki Joshuát, Amanda férjét!}
{506}{}{Vigyél 10 sört és 10 piát Lydiának!}
{507}{}{Vigyél egy fogót és egy villáskulcsot Valerie-nek!}
{508}{}{Derítsd fel a Gekkó körüli 8 szektort és térj vissza Starkhoz!}
{509}{}{Menj el az ÚKK-ba és térj vissza Starkhoz!}

#
# Gecko Quests
#
{600}{}{Oldd meg a gekkói erõmû problémáját!}
{601}{}{Javítsd meg az erõmûvet!}
{602}{}{Optimalizáld az erõmûvet!}
{603}{}{Szerezz egy nagy szerszámkészletet Felixnek!}
{604}{}{Szerezz egy 3-fázisú plazmaátalakítót Felixnek!}
{605}{}{Keresd meg Woody-t a ghoult. Próbálkozz Rejtekben!}

#
# Broken Hills Quests
#
{700}{}{}
{701}{}{Javítsd meg a bánya légtisztítóját!}
{702}{}{Marcus kérésére találd meg az eltûnt embereket!}
{703}{}{Nyomd le Francist szkanderban!}
{704}{}{Szabadítsd ki Mansont és France-t a börtönbõl!}
{705}{}{Robbantsd fel a bánya légtisztítóját!}
{706}{}{Intézd el, hogy Eric házába több áram jusson!}

#
# New Reno Quests
#
{800}{}{Szerezd vissza az ellopott kocsidat!}
{801}{}{Találd meg, ki felelõs Richard Wright haláláért!}
{802}{}{     Gyanúsított: Csipkés Jimmy J.}
{803}{}{     Gyanúsított: Jules}
{804}{}{     Gyanúsított: Kis Jesus Mordino}
{805}{}{     Gyanúsított: Renesco}
{806}{}{Juss be a Sierra hadiraktárba!}
{807}{}{Találd meg Szépfiú Lloydot, szerezd vissza az ellopott pénzt, és állíts elrettentõ példát az esetbõl!}
{808}{}{Látogasd meg Rakétás Renescót és hajtsd be rajta az 1000 dollárt, amivel Mr. Salvatorénak tartozik!}
{809}{}{Vegyél részt õrként egy titkos üzletkötésen, kint a sivatagban!}
{810}{}{Találj valamilyen endorfinblokkolót, amibõl Jet-ellenszer készíthetõ!}
{811}{}{Verd szét Wright szeszfõzdéjét a vasútállomás alatt!}
{812}{}{Öld meg Westint az ÚKK-ban, anélkül hogy gyilkosságnak tûnne!}
{813}{}{Gyilkold meg Carlsont az ÚKK-ban!}
{814}{}{Vigyél 10 Cat's Paw magazint Kitty kisasszonynak!}
{815}{}{Vigyél egy lézerpisztolyt Eldridge-nek!}
{816}{}{Vidd el Nagy Jesus csomagját Ramireznek az Istállóba!}
{817}{}{Gyûjtsd be a védelmi pénzt a Korzikai Testvérektõl!}
{818}{}{Nagy Jesus Mordino megbízásából gyilkold meg a Salvatore családfõt!}

#
# Sierra Army Base Quests
#
{900}{}{}

#
# Vault 15 Quests
# Moved it to 3000 on accedent
{1000}{}{}

#
# New California Republic Quests
#
{1100}{}{Juss be a 15-ös Menedékbe és szerezd meg a számítógép alkatrészeket!}
{1101}{}{Mira kérésére fékezd meg Jacket, a rendõrtisztet!}
{1102}{}{Kísérd el a karavánt!}
{1103}{}{Szerezd meg a papírokat Dr Henrytõl!}
{1104}{}{Teszteld le a mutagén szérumot egy szupermutánson, mondjuk Broken Hillsben!}
{1105}{}{Iktasd ki Bishopot!}
{1106}{}{Vidd el Westin hololemezét Lynette-nek, Menedékvárosba!}
{1107}{}{Szerezd meg a térképet az ÚKK-i Felderítõktõl, és add oda Vortisnak, a rabszolga-kereskedõnek!}
{1108}{}{A Felderítõk megbízásából szabadítsd fel a rabszolgákat a városszéli rabszolga-táborból!}
{1109}{}{Vidd el a Hubologista helyzetjelentést BHK-9-nek, San Franciscóba!}
{1110}{}{Merk megbízásából öld meg a Hubologistát!}
{1111}{}{Vess véget a brahminok eltûnésének!}
#
# Vault 13 Quests
#
{1200}{}{Javítsd meg a 13-as Menedék számítógépét!}
{1201}{}{Beszélj Gorisszal!}

#
# Military Base Quests
#
{1300}{}{}

#
# Redding Quests
#
{1400}{}{Találd meg az örömlány támadóját!}
{1401}{}{Találd meg az exkavátor chipet!}
{1402}{}{Akadályozd meg a kocsmai verekedést!}
{1403}{}{Öldd meg Hûtõs Mortont!}

#
# San Francisco Quests
#
{1500}{}{A tartályhajóba üzemanyag kell!}
{1501}{}{A navigációs számítógép mûködéséhez szükség van a NavKomp chipre!}
{1502}{}{Szükséged van egy FBK-ra, hogy hozzáférj a navigációs számítógéphez!}
{1503}{}{Pusztítsd el a Shi császárt!}
{1504}{}{A Hubologistáknak szüksége van a gépmadár tervrajzára Navarróból!}
{1505}{}{Lopd el a gépmadár tervrajzát a Shiktõl!}
{1506}{}{A Hubologistáknak üzemanyag kell az ûrhajójukhoz!}
{1507}{}{Intézd el a Borzot, hogy a tankhajó jöttment lakói befogadják a Hubologistákat!}
{1508}{}{Végezz BHK-9-el!}
{1509}{}{A Shiknek szüksége van a gépmadár tervrajzára Navarróból!}
{1510}{}{Lopd el a gépmadár tervrajzát a Hubologistáktól!}
{1511}{}{Keresd meg a Borz barátnõjét a hajó rakterében!}
{1512}{}{A Sárkány megkért, hogy verd meg Lo Pant - pusztakézzel!}
{1513}{}{Lo Pan megkért, hogy verd meg a Sárkányt - pusztakézzel, ha lehetséges!}
{1514}{}{Szerezd vissza Chip lépét!}
{1515}{}{Szerezz egy megerõsített erõpáncélt Crockettõl!}
{1516}{}{Szerezd meg a gépmadár tervrajzát az Acél Testvérisége számára !}
#
# Navarro Quests
#
#1515, ...
{1600}{}{Intézd el a halálkarmot!}
{1601}{}{Javítsd meg K9-et!}
{1602}{}{Szerezd meg az FBK-t a támaszpont parancsnokától!}

#
# The Enclave Quests
#
{1700}{}{}

#
# The Abbey Quests
#
{1800}{}{}

#
# Primitive Tribe Quests
#
{1900}{}{}

#
# EPA Quests
#
{2000}{}{}

#
# Ghost Town Quests
#
{2100}{}{}

#
# Car outta Gas Quests
#
{2200}{}{}

#
# Destroyed Arroyo Quests
#
{2300}{}{}

#
# Toxic Caves Quests
#
{2400}{}{}

#
# Den Slave Run Quests
#
{2500}{}{}

#
# Raiders Quests
#
{2600}{}{}

#
# Desert Encounter Quests
#
{2700}{}{}

#
# Mountain Encounter Quests
#
{2800}{}{}

#
# Ruined City Encounter Quests
#
{2900}{}{}

#
# Coast Encounter Quests
#
{3000}{}{}

#
# Golgotha Quests
#
{3100}{}{}


#
# Vault 15 Quests
#
{3200}{}{Mentsd meg Chrissy-t!}
{3201}{}{Nyírd ki Dariont!}
{3202}{}{Köss megállapodást az ÚKK-val!}
{3203}{}{Juttasd el a Kém hololemezt az ÚKK-i hatóságokhoz!}