#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the name which will  #
#           be displayed for critter or items when they     #
#           get hit. Each script from scripts.lst should    #
#           have a name associated with it.                 #
#                                                           #
#  Created: October 06, 1997                                #
#############################################################

{101}{}{}                               # obj_dude.int    ; Player script.
{102}{}{Script Test 0}                  # Test0.int       ; Used to Test Scripts
{103}{}{Script Test 1}                  # Test1.int       ; Used to Test Scripts
{104}{}{Script Test 2}                  # Test2.int       ; Used to Test Scripts
{105}{}{Script Test 3}                  # Test3.int       ; Used to Test Scripts
{106}{}{Script Test 4}                  # Test4.int       ; Used to Test Scripts
{107}{}{Script Test 5}                  # Test5.int       ; Used to Test Scripts
{108}{}{Arroyói harcos}                 # ACWarior.int    ; Generic Warrior in Arroyo
{109}{}{Arroyói lakos}                  # ACVillgr.int    ; Generic Villager of Arroyo
{110}{}{Mynoc}                          # ACMynoc.int     ; Mynoc, Bridge Guard of Arroyo
{111}{}{Arroyo törzsfõje}               # AHElder.int     ; Elder of Arroyo
{112}{}{Hakunin}                        # AHHakun.int     ; Hakunin, Shaman of Arroyo
{113}{}{Ajtó}                           # Door.int        ; generic locked and trapped door
{114}{}{Általános}                      # Generic.int     ; Generic dialog for scripts
{115}{}{Láda}                           # AILkBox.int     ; Locked box in Arroyo Elder's room
{116}{}{Páncéldoboz}                    # Containr.int    ; Generic locked and trapped container
{117}{}{Brahmin}                        # ACBrahmn.int    ; Brahmin for pen in Arroyo
{118}{}{Húsevõ növény}                    # ACSporPl.int    ; Spore plants in Arroyo
{119}{}{}                               # ZClRat.int      ; Generic lesser rat
{120}{}{Skorpió}                        # ZClScorp.int    ; Generic lesser scorpion
{121}{}{Imádkozó sáska}                 # ZClManti.int    ; Generic lesser mantis
{122}{}{Kis halálkarom}                 # ZClDthCL.int    ; Generic lesser death claw
{123}{}{Váza}                           # AIVase.int      ; Vase in Arroyo Villager's Hut
{124}{}{Láda}                           # AIChest.int     ; Chest in Arroyo Shaman's Hut
{125}{}{Arroyói barlang}                # ArCaves.int     ; Map Script for Arroyo Caves
{126}{}{Faajtó}                         # DoorL100.int    ; Generic Locked Door (+100%) (Wood)
{127}{}{Arroyo}                         # ArVillag.int    ; Map Script for Arroyo Village
{128}{}{Arroyo hídja}                   # ArBridge.int    ; Map Script for Arroyo Bridge
{129}{}{Ósdi ajtó}                      # AICavDor.int    ; Locked wooden door in Arroyo Caves (0/-20)
{130}{}{Padlólap}                       # SprTrp0.int     ; Generic spear Trap (0)
{131}{}{Padlólap}                       # SprTrp50.int    ; Arroyo Spear Trap for Caves (50)
{132}{}{Padlólap}                       # SprTrp51.int    ; Arroyo Spear Trap for Caves (50)
{133}{}{Padlólap}                       # SprTrp52.int    ; Arroyo Spear Trap for Caves (50)
{134}{}{Padlólap}                       # SprTrp53.int    ; Arroyo Spear Trap for Caves (50)
{135}{}{Ajtó}                           # AIBkDor.int     ; Door w/out a handle In Arroyo Caves
{136}{}{Drogfüggõ}                      # DCAddict.int    ; Addict from the Den
{137}{}{Õr}                             # DCG2Grd.int     ; Gang 2 Guard from the Den
{138}{}{Városlakó}                      # DCCustmr.int    ; Generic Customer in the Den
{139}{}{Bandatag}                       # DCCustmr.int    ; Thug in the Den
{140}{}{Árva}                           # DCOrphan.int    ; Thieving Orphan in the Den
{141}{}{Joey}                           # DCJoey.int      ; Special thug in the Den
{142}{}{Flick}                          # DCFlick.int     ; Kwik N Save store owner in the Den
{143}{}{Õr}                             # DCG2Grd.int     ; Gang 2 Guard in the Den
{144}{}{Petey}                          # DCPetey.int     ; Petey, the alley addict in the Den
{145}{}{Smitty}                         # DCSmitty.int    ; Smitty the junkyard guy in the Den
{146}{}{Metzger}                        # dcMetzge.int    ; Metzger the Slaver in the Den
{147}{}{Hajcsár}                        # DCSlaver.int    ; Regular Slaver in the Den
{148}{}{Tubby}                          # DCTubby.int     ; Tubby the store owner in the Den
{149}{}{Anna}                           # DCAnna.int      ; Anna the Ghost in the Den
{150}{}{Vic}                            # DCVic.int       ; Trader Vic in the Den, can be a party member
{151}{}{Frankie}                        # DCFranki.int    ; Frankie, owner of the Hole in the Den
{152}{}{Rebecca}                        # DCRebecc.int    ; Rebecca in the Den
{153}{}{Billy}                          # DCBilly.int     ; One-tooth Billy in the Hole in the Den
{154}{}{Sheila}                         # DCSheila.int    ; Sheila, the prostitute in the Hole in the Den
{155}{}{Mama}                           # DCMom.int       ; Mom, who run's Mom's in the Den
{156}{}{Falubeli}                       # DCSlvRun.int    ; Generic People for Slave Runs
{157}{}{Rabszolga-vadászat}             # DNSlvRun.int    ; Map Script for Den Slave Runs
{158}{}{Rabszolga-fogat}                # DISlvCrt.int    ; Slave Cart to take the Player to Den
{159}{}{Rejtek, üzleti negyed}          # DenBus1.int     ; Map Script for Den business area 1
{160}{}{Rejtek, üzleti negyed}          # DenBus2.int     ; Map Script for Den business area 2
{161}{}{Rejtek, lakónegyed}             # DenRes1.int     ; Map Script for Den residential area
{162}{}{Sírhely}                        # diAnnGrv.int    ; Grave of Anna the ghost in the Den
{163}{}{Sírhely}                        # diDadGrv.int    ; Grave of Anna the ghost's Dad in the Den
{164}{}{Sírhely}                        # diMomGrv.int    ; Grave of Anna the ghost's Mom in the Den
{165}{}{Csontok}                        # diBones.int     ; Bones of Anna the ghost in the Den
{166}{}{Napló}                          # diDiary.int     ; Diary of Anna the ghost in the Den
{167}{}{Medál}                          # diLocket.int    ; Locket of Anna the ghost in the Den
{168}{}{Szeszlepárló}                   # diStill.int     ; Still that Maggie has in the basement in the Den
{169}{}{Sírhely}                        # ziGenGrv.int    ; Generic grave
{170}{}{Black Jack asztal}              # ziBlkJck.int    ; Generic black jack table
{171}{}{Rabszolga}                      # zcSlave.int     ; Generic slave
{172}{}{Black Jack asztal}              # dcBlkJck.int    ; Den black jack table from Maggie's place
{173}{}{Ajtó}                           # diChcDor.int    ; Church door from the Den
{174}{}{Whiskey Bob}                    # KCBob.int       ; Whiskey Bob from Klamath
{175}{}{Craps}                          # dcCraps.int     ; Maggie Craps dealer in the den
{176}{}{Aldo}                           # KCAldo.int      ; Aldo from Klamath
{177}{}{Ardin}                          # KCArdin.int     ; Ardin from Klamath
{178}{}{Kölyök}                         # KChild.int      ; Child from Klamath
{179}{}{Városlakó}                      # KCitizen.int    ; Citizen from Klamath
{180}{}{Maida}                          # KCMaida.int     ; Maida from Klamath
{181}{}{Sajag}                          # KCSajag.int     ; Sajag from Klamath
{182}{}{Sally}                          # KCSally.int     ; Sally from Klamath
{183}{}{Smiley}                         # KCSmiley.int    ; Smiley from Klamath
{184}{}{Jenny}                          # KCJenny.int     ; Jenny from Klamath
{185}{}{Slim}                           # KCSlim.int      ; Slim from Klamath
{186}{}{Torr}                           # KCTorr.int      ; Torr from Klamath
{187}{}{Dunton}                         # KCDunton.int    ; Dunton from Klamath
{188}{}{Polgár}                         # VCCrtCit.int    ; Vault City Courtyard Citizen
{189}{}{Utazó}                          # VCCrtOut.int    ; Vault City Courtyard Outsider
{190}{}{Menedékvárosi õr}               # VCCrtGrd.int    ; Vault City Courtyard Guard
{191}{}{Menedékvárosi õr}               # VCInGrd.int     ; Vault City Inner Guard
{192}{}{Steve}                          # VCSteve.int     ; Steve from Vault City
{193}{}{Andrew}                         # VCAndy.int      ; Andy the Medic in the Central Vault City
{194}{}{Menedékvárosi õr}               # VCGatGrd.int    ; Vault City Main Gate Guard
{195}{}{Dr. Troy}                       # VCDrTroy.int    ; Vault City Dr. Troy in the Vault
{196}{}{Sárga kutya}                    # KCYellow.int    ; Yellow Dog in Klamath
{197}{}{Balthas}                        # mcBaltha.int    ; Balthas in Modoc
{198}{}{Cornelius}                      # mcCornel.int    ; Cornelius in Modoc
{199}{}{Davin}                          # mcDavin.int     ; Davin in Modoc
{200}{}{Farrel}                         # mcFarrel.int    ; Farrel in Modoc
{201}{}{Grisham}                        # mcGrisha.int    ; Grisham in Modoc
{202}{}{Jo}                             # mcJo.int        ; Jo in Modoc
{203}{}{Jonny}                          # mcJonny.int     ; Jonny in Modoc
{204}{}{Karl}                           # mcKarl.int      ; Karl in Modoc
{205}{}{Laddie}                         # mcLaddie.int    ; Laddie in Modoc
{206}{}{Miria}                          # mcMiria.int     ; Miria in Modoc
{207}{}{Kormányzó}                      # mcProtec.int    ; Protector in Modoc
{208}{}{Rose}                           # mcRose.int      ; Rose in Modoc
{209}{}{Vegeir}                         # mcVegeir.int    ; Vegeir in Modoc
{210}{}{Ed}                             # VCEd.int        ; Ed the Brahma dealer in Vault City
{211}{}{Harry}                          # VCHarry.int     ; Happy Harry the store keep in Vault City
{212}{}{Mrs. Smith}                     # VCFSmith.int    ; Mrs. Smith from Vault City (Farmer)
{213}{}{Melinda}                        # VCMelind.int    ; Town Greeter Melinda, Vault City
{214}{}{Prémvadász}                     # KCTrapr.int     ; Generic trapper in Klamath
{215}{}{Mr. Smith}                      # VCMSmith.int    ; Mr. Smith from Vault City (Farmer)
{216}{}{Skeeve}                         # VCSkeeve.int    ; Skeeve, sells fake passes to Vault City
{217}{}{Gregory fõtanácsos}             # VCGreg.int      ; Proconsul Gregory of Vault City
{218}{}{Nancy nõvér}                    # VCNancy.int     ; Nurse Nancy in Vault City
{219}{}{Randal}                         # VCRandal.int    ; Chief Admenities Officer of Vault City
{220}{}{Trutyi}                         # KTGoo.int       ; Toxic Goo in the rat caves (Klamath)
{221}{}{Barkus}                         # VCBarkus.int    ; Barkus, Vault City Service Coordinator
{222}{}{Falubeli}                       # VCGenVil.int    ; Generic Villager around Vault City
{223}{}{Stark}                          # VCStark.int     ; Vault City Sargent Stark
{224}{}{Menedék kapuõr}                 # VCVltGrd.int    ; Guard for entrance into the Vault of VC
{225}{}{Vén Joe}                        # VCOldJoe.int    ; Crazy Old Joe (Vault City)
{226}{}{Connar}                         # VCConnar.int    ; Connar from Vault City
{227}{}{Wallace}                        # VCWalace.int    ; Wallace the Customs Official (Vault City)
{228}{}{Lynette}                        # VCLynett.int    ; First Citizen Lynette of Vault City
{229}{}{McClure}                        # VCMClure.int    ; Senior Council Member MCclure (Vault City)
{230}{}{Mutáns patkány}                 # GCBrain.int     ; Intelligent rat in Gecko
{231}{}{Festus}                         # GCFestus.int    ; Festering ghoul in Gecko
{232}{}{Gordon}                         # GCGordon.int    ; Ghoul with economic data in Gecko
{233}{}{Hank}                           # GCHank.int      ; Ghoul that monitors the reactor in Gecko
{234}{}{Jeremy}                         # GCJerem.int     ; Ghoul in charge of supply cabinet in Gecko
{235}{}{Lumpy}                          # GCLumpy.int     ; Watches the Brahmin and helps Skeeter
{236}{}{Skeeter}                        # GCSkeetr.int    ; Gadgeteer in Gecko
{237}{}{Zomak}                          # GCZomak.int     ; Muscle man for the Brain
{238}{}{Wooz}                           # GCWooz.int      ; Bar owner and Tragic player
{239}{}{Lenny}                          # GCLenny.int     ; Stuttering ghoul that can join party
{240}{}{Eligazító õr}                   # GGCRDesk.int    ; Reactor Desk guard
{241}{}{Ghoul munkás}                   # GCRWorkr.int    ; Reactor worker
{242}{}{Fénylõ ghoul}                   # GCRGlow.int     ; Reactor glowing one
{243}{}{Ghoul õr}                       # GCRGuard.int    ; Reactor guard
{244}{}{Robot}                          # GCRRobot.int    ; Reactor robot
{245}{}{Ghoul polgár}                   # GCFolk.int      ; Townsfolk in Gecko
{246}{}{Map Script}                     # DepoLv1.int     ; Map script for Sierra Army Depot, Level 1
{247}{}{Map Script}                     # DepoLvA.int     ; Map script for Sierra Army Depot Undergound
{248}{}{Map Script}                     # DepoLvB.int     ; Map script for Sierra. Underground B
{249}{}{Biztonsági robot}               # WCSecBot.int    ; Sierra Base, Security Robot (generic)
{250}{}{Javítórobot}                    # WCRepBot.int    ; Sierra Base, Repair Robot (generic)
{251}{}{Hololemez}                      # WIEvcDsk.int    ; Sierra Base, Evacution Holodisk
{252}{}{Hololemez}                      # WIMedDsk.int    ; Sierra Base, Medical Log 1 Holodisk
{253}{}{Hololemez}                      # WIExpDsk.int    ; Sierra Base, Experiment Log Holodisk
{254}{}{Terminál}                       # WSTerm1A.int    ; Security Computer, Level 1 -- Sierra Base
{255}{}{Terminál}                       # WSTerm1B.int    ; Security Systems, Level 1 -- Sierra Base
{256}{}{Terminál}                       # WSTerm2A.int    ; Security Computer, Level 2 -- Sierra Base
{257}{}{Terminál}                       # WSTerm2B.int    ; Security Systems, Level 2 -- Sierra Base
{258}{}{Terminál}                       # WSTerm2C.int    ; Auto Repair System, Level 2 -- Sierra Base
{259}{}{Terminál}                       # WSTerm3A.int    ; Security Computer, Level 3 -- Sierra Base
{260}{}{Terminál}                       # WSTerm3B.int    ; Skynet Terminal, Level 3 -- Sierra Base
{261}{}{Terminál}                       # WSTerm3C.int    ; Robobrain Activator, Level 3 -- Sierra Base
{262}{}{Terminál}                       # WSTerm4A.int    ; Security Computer, Level 4 -- Sierra Base
{263}{}{Terminál}                       # WSTerm4B.int    ; Organ Extractor, Level 4 -- Sierra Base
{264}{}{Terminál}                       # WSTerm4C.int    ; BioStorage Computer, Level 4 -- Sierra Base
{265}{}{Papír}                          # WIPaswrd.int    ; Piece of paper with the password on it
{266}{}{Dobbs közlegény}                # WCDobbs.int     ; Private Dobbs, Sierra Army Depot
{267}{}{Agy-bot}	                      # WCBrnBot.int    ; Brain Bot in the Army Depot
{268}{}{Felvonó}                        # ZSElev01.int    ; Generic Elevator
{269}{}{Felvonó}                        # ZSElev02.int    ; Generic Elevator
{270}{}{Páncéldoboz}                    # DITubBox.int    ; Tubby's box of inventory
{271}{}{Páncéldoboz}                    # DIFlkBox.int    ; Flick's box of inventory
{272}{}{Tandi}                          # SHTandi.int     ; Tandi the talking head in the NCR2 area
{273}{}{Lándzsa-csapda}                 # ATSrTrp0.int    ; Arroyo Spear Trap for Caves (50)
{274}{}{Lándzsa-csapda}                     # ATSrTrp1.int    ; Arroyo Spear Trap for Caves (50)
{275}{}{Lándzsa-csapda}                     # ATSrTrp2.int    ; Arroyo Spear Trap for Caves (50)
{276}{}{Lándzsa-csapda}                     # ATSrTrp3.int    ; Arroyo Spear Trap for Caves (50)
{277}{}{Lándzsa-csapda}                     # ATSrTrp4.int    ; Arroyo Spear Trap for Caves (50)
{278}{}{Lándzsa-csapda}                     # ATSrTrp5.int    ; Arroyo Spear Trap for Caves (50)
{279}{}{Lándzsa-csapda}                     # ATSrTrp6.int    ; Arroyo Spear Trap for Caves (50)
{280}{}{Lándzsa-csapda}                     # ATSrTrp7.int    ; Arroyo Spear Trap for Caves (50)
{281}{}{Lándzsa-csapda}                     # ATSrTrp8.int    ; Arroyo Spear Trap for Caves (50)
{282}{}{Lándzsa-csapda}                     # ATSrTrp9.int    ; Arroyo Spear Trap for Caves (50)
{283}{}{Lándzsa-csapda}                     # ATSrTrpA.int    ; Arroyo Spear Trap for Caves (50)
{284}{}{Lándzsa-csapda}                     # ATSrTrpB.int    ; Arroyo Spear Trap for Caves (50)
{285}{}{Lándzsa-csapda}                     # ATSrTrpC.int    ; Arroyo Spear Trap for Caves (50)
{286}{}{Lándzsa-csapda}                     # ATSrTrpD.int    ; Arroyo Spear Trap for Caves (50)
{287}{}{Lándzsa-csapda}                     # ATSrTrpE.int    ; Arroyo Spear Trap for Caves (50)
{288}{}{Lándzsa-csapda}                     # ATSrTrpF.int    ; Arroyo Spear Trap for Caves (50)
{289}{}{1-es kísértetbarlang}                 # GstCav1.int     ; Modoc Ghost Cave 1
{290}{}{2-es kísértetbarlang}                 # GstCav2.int     ; Modoc Ghost Cave 2
{291}{}{Kísértet farm}                     # GstFarm.int     ; Modoc Ghost Farm
{292}{}{Modoc, brahmin legelõ}            # ModBrah.int     ; Modoc Brahmin Field
{293}{}{Modoc, kert}                   # ModGard.int     ; Modoc Garden
{294}{}{Modoc, fogadó}                      # ModInn.int      ; Modoc Inn
{295}{}{Modoc}                     # ModMain.int     ; Modoc Main
{296}{}{Modoc, pöcegödör}                     # ModShit.int     ; Modoc under the shitter
{297}{}{Modoc, kút}                       # ModWell.int     ; Modoc Well
{298}{}{ÚKK, 2. terület}                     # ncr2.int        ; NCR area 2
{299}{}{Arroyo kert}                 # ArGarden.int    ; Arroyo Gardens map script
{300}{}{Gekkó}                          # ACGecko.int     ; generic Gecko creature
{301}{}{Broc virág}                    # AIBroc.int      ; Arroyo Broc Flower
{302}{}{Xander gyökér}                    # AIXander.int    ; Arroyo Xander Root
{303}{}{Brahmin}                        # ZCBrahmn.int    ; Generic Brahmin
{304}{}{Balthas felesége}                   # mcBalWif.int    ; Modoc Balthas wife
{305}{}{Brahmin}                        # mcBrahmn.int    ; Modoc brahmin
{306}{}{Vad kutya}                       # mcAtkDog.int    ; Modoc Attack Dog
{307}{}{Kövek}                          # miDclRks.int    ; Modoc Rocks in front of the death claw cage
{308}{}{Kövek}                          # miShtRks.int    ; Modoc Rocks under the shitter
{309}{}{Fali széf}                      # miWalSfe.int    ; Modoc Farrel's wall safe
{310}{}{Pénzeszsák}                       # miCoinBg.int    ; Modoc Coin bags at the bottom of the well
{311}{}{Mellékhelység}                         # miToilet.int    ; ; Modoc Toliet
{312}{}{Doboz}                            # miLstFnd.int    ; Modoc Lost and Found at Rose's
{313}{}{Jordan}                         # ACJordan.int    ; Jordan. Trains player in Melee
{314}{}{Morlis nagynéni}                    # ACMorlis.int    ; Aunt Morlis. Has flint to give player
{315}{}{Lucas}                  # ACFist.int      ; Standing Fist. Trains player in Unarmed
{316}{}{Feargus}                        # ACEric.int      ; Whiny person asking to fix the well
{317}{}{Kút}                           # ASWell.int      ; Arroyo Well. It's broken. Fix w/ Repair
{318}{}{Gruthar}                        # OCGrutha.int    ; Vault 13 Gruthar Deathclaw leader
{319}{}{Map Script}                     # Kladwtwn.int    ; Map script for Klamath Downtown
{320}{}{Skeeter}                        # SCSkeete.int    ; Skeeter dialog script for NCR Entrance area
{321}{}{Nagor}                          # ACNagor.int     ; You cousin who has lost his dog
{322}{}{Füst}                          # ACDog.int       ; Nagor's dog Smoke
{323}{}{ÚKK, 1-es terület}                     # Ncr1.int        ; Ncr area 1 map
{324}{}{ÚKK, 2-es terület}                     # Ncr3.int        ; Ncr area 3 map
{325}{}{ÚKK, 3-as terület}                     # Ncr4.int        ; Ncr area 4 map
{326}{}{ÚKK, Külsõ terület}              # Ncrent.int      ; Ncr area Entrance map
{327}{}{Mikey}                          # SCMikey.int     ; NCR Lizard Dealer
{328}{}{Mikey doboza}                    # SIMbox.int      ' NCR Mikey's inventory box. (off Screen)
{329}{}{Generátor}                        # WSEmit1a.int    ; Emitter, Level 1, Section A   (Sierra Base)
{330}{}{Generátor}                        # WSEmit1b.int    ; Emitter, Level 1, Section B   (Sierra Base)
{331}{}{Generátor}                        # WSEmit1c.int    ; Emitter, Level 1, Section C   (Sierra Base)
{332}{}{Generátor}                        # WSEmit1d.int    ; Emitter, Level 1, Section D   (Sierra Base)
{333}{}{Generátor}                        # WSEmit1e.int    ; Emitter, Level 1, Section E   (Sierra Base)
{334}{}{Generátor}                        # WSEmit2a.int    ; Emitter, Level 2, Section A   (Sierra Base)
{335}{}{Generátor}                        # WSEmit2b.int    ; Emitter, Level 2, Section B   (Sierra Base)
{336}{}{Generátor}                        # WSEmit2c.int    ; Emitter, Level 2, Section C   (Sierra Base)
{337}{}{Generátor}                        # WSEmit2d.int    ; Emitter, Level 2, Section D   (Sierra Base)
{338}{}{Generátor}                        # WSEmit3a.int    ; Emitter, Level 3, Section A   (Sierra Base)
{339}{}{Generátor}                        # WSEmit3b.int    ; Emitter, Level 3, Section B   (Sierra Base)
{340}{}{Erõtér}                    # WSFeld1a.int    ; F. Field, Level 1, Section A   (Sierra Base)
{341}{}{Erõtér}                    # WSFeld1b.int    ; F. Field, Level 1, Section B   (Sierra Base)
{342}{}{Erõtér}                    # WSFeld1c.int    ; F. Field, Level 1, Section C   (Sierra Base)
{343}{}{Erõtér}                    # WSFeld1d.int    ; F. Field, Level 1, Section D   (Sierra Base)
{344}{}{Erõtér}                    # WSFeld1e.int    ; F. Field, Level 1, Section E   (Sierra Base)
{345}{}{Erõtér}                    # WSFeld2a.int    ; F. Field, Level 2, Section A   (Sierra Base)
{346}{}{Erõtér}                    # WSFeld2b.int    ; F. Field, Level 2, Section B   (Sierra Base)
{347}{}{Erõtér}                    # WSFeld2c.int    ; F. Field, Level 2, Section C   (Sierra Base)
{348}{}{Erõtér}                    # WSFeld2d.int    ; F. Field, Level 2, Section D   (Sierra Base)
{349}{}{Erõtér}                    # WSFeld3a.int    ; F. Field, Level 3, Section A   (Sierra Base)
{350}{}{Erõtér}                    # WSFeld3b.int    ; F. Field, Level 3, Section B   (Sierra Base)
{351}{}{Riasztó}                         # WSKlaxon.int    ; Changes lights to Flashing w/ Sierra on Alert
{352}{}{Buster}                         # SCBuster.int    ; Buster gun dealer at NCR entrance
{353}{}{Könyvespolc}                      # SIShelf1.int    ; Busters shelves where items are kept
{354}{}{Könyvespolc}                      # SIShelf2.int    ; Busters shelves where items are kept
{355}{}{Könyvespolc}                      # SIShelf3.int    ; Busters shelves where items are kept
{356}{}{Fosztogató}                         # ECRaider.int    ; Random Encounter Raider
{357}{}{Farmer}                        # ECPeasnt.int    ; Random Encounter Peasant
{358}{}{Kereskedõ}                       # ECMrchnt.int    ; Random Encounter Merchant
{359}{}{Õr}                          # ECGuard.int     ; Random Encounter Gaurd
{360}{}{Rawhide vendég}                 # SCRawpat.int    ; Rawhide patron in NCR Entrance
{361}{}{Padló}                          # WTElFlr2.int    ; Electric Floor on Level 2 Sierra Base
{362}{}{Plazma csapda}                    # WTPlTrp0.int    ; Plasma Trap for Sierra Base(-30)
{363}{}{Plazma csapda}                    # WTPlTrp1.int    ; Plasma Trap for Sierra Base(-30)
{364}{}{Terminál}                       # WSPwrDwn.int    ; Power Switch for the Sierra Base
{365}{}{Hírdetõtábla}                 # KSBboard.int    ; Klamath bulletin board
{366}{}{Kapu}                           # ASCrlDr.int     ; Arroyo Corral Gate
{367}{}{Trutyi}                            # ATGoo.int       ; Goo in the Garden Map
{368}{}{Ajtó}                           # KSCVDoor.int    ; Door in Klamath Rat Caves
{369}{}{Ajtó}                           # KSMalldr.int    ; Door in Klamall..get key from Slim or Dog
{370}{}{}                               # ZCGecko.int     ; Generic gecko
{371}{}{}                               # ZCLGecko.int    ; Generic Golden Gecko
{372}{}{Map Script}                     # 2ndSt.int       ; 2nd Street Map Script
{373}{}{Map Script}                     # ChopShop.int    ; Chop Shop Map Script
{374}{}{Map Script}                     # GeckPwpl.int    ; Gecko Power Plant Map Script
{375}{}{Map Script}                     # GeckTunl.int    ; Gecko Tunnels Map Script
{376}{}{Map Script}                     # KlaCnyn.int     ; Klamath Canyon Map Script
{377}{}{Map Script}                     # MBase12.int     ; Military Base Level 1,2 Map Script
{378}{}{Map Script}                     # MBase34.int     ; Military Base Level 3,4 Map Script
{379}{}{Map Script}                     # MBClose.int     ; Military Base Closed Map Script
{380}{}{Map Script}                     # ModShit.int     ; Map Script for Modoc Shitter
{381}{}{Map Script}                     # NCR1.int        ; Map Script for NCR1
{382}{}{Map Script}                     # NCR2.int        ; Map Script for NCR2
{383}{}{Map Script}                     # NCR3.int        ; Map Script for NCR3
{384}{}{Map Script}                     # NCR4.int        ; Map Script for NCR4
{385}{}{Map Script}                     # NCREx.int       ; Map Script for NCR Exit
{386}{}{Map Script}                     # Stable.int      ; Map Script for Stables
{387}{}{Map Script}                     # V13_Orig.int    ; Map Script for Original Vault 13
{388}{}{Map Script}                     # V13Ent.int      ; Map Script for Vault 13 Entrance
{389}{}{Map Script}                     # V15_Orig.int    ; Map Script for Original Vault 15
{390}{}{Map Script}                     # V15Ent.int      ; Map Script for Vault 15 Entrance
{391}{}{Map Script}                     # Vault13.int     ; Map Script for Vault 13
{392}{}{Map Script}                     # Vault15.int     ; Map Script for Vault 15
{393}{}{Map Script}                     # VaultNec.int    ; Map Script for Necropolis Vault
{394}{}{Map Script}                     # VCtyVlt.int     ; Map Script for Vault City Vault
{395}{}{Map Script}                     # Virgin.int      ; Map Script for Virgin (these still exist?)
{396}{}{Szeszlepárló}                          # Kstill.int      ; Script for still in Klamath
{397}{}{Bárvendég}                   # Kcggcust.int    ; Script for Klamath golden gecko customer
{398}{}{Bárvendég}                   # Kcbhcust.int    ; Script for Klamath buckner house customer
{399}{}{Vortis}                         # SCVortis.int    ; Script for Vortis slave pen dude in NCR entrance
{400}{}{Fürdõszemélyzet}                 # Kcbgirl.int     ; Script for Klamath bath girl
{401}{}{Rabszolgák}                         # SCSlaves.int    ; Script for NCR Entrance slaves
{402}{}{Skorpió}                       # Kcscorp.int     ; Script for Klamath scorpions on the graze map
{403}{}{Brahmin}                        # Kcbrahmn.int    ; Script for Klamath brahmin on the graze map
{404}{}{Autó}                            # ZSDrvCar.int    ; Drivable Car for the player
{405}{}{Asztal}                          # diVicTbl.int    ; Den, table that Vic works at
{406}{}{Map Script}                     # Klagraz.int     ; Map Script for Klamath graze map
{407}{}{Map Script}                     # CarDesrt.int    ; Car Out of Gas Desert Map
{408}{}{Map Script}                     # GeckSetl.int    ; Map Script for Gecko Settlememt
{409}{}{Map Script}                     # VCtyCtyd.int    ; Map Script for Vault City Courtyard
{410}{}{Corvega}                        # Kscorveg.int    ; Klamath broken car with fuel injection
{411}{}{Map Script}                     # KlaToxCv.int    ; Klamath Toxic Caves  Map Script
{412}{}{Fémajtó}                     # SISlvdor.int    ; Slave pen door in NCR Entrance
{413}{}{Map Script}                     # RndDsrt.int     ; Random Encounter Desert Map Script
{414}{}{Map Script}                     # RndCoast.int    ; Random Encounter Coast Map Script
{415}{}{Map Script}                     # RndMnt.int      ; Random Encounter Mountain Map Script
{416}{}{Páncéldoboz}                        # Kidbox.int      ; Klamath dunton inventory box
{417}{}{Páncéldoboz}                        # Kibbox.int      ; Klamath buckner inventory box
{418}{}{Páncéldoboz}                        # Kisbox.int      ; Klamath sajag inventory box
{419}{}{Ratch}                          # SCRatch.int     ; Ncr entrance JUNK dealer
{420}{}{Bokszoló}                          # ncBoxer.int     ; New Reno Generic Boxer
{421}{}{Pete McKneely}                  # ncMcKnee.int    ; New Reno Mike McKneely
{422}{}{Evan Hollyfeld}                 # ncHollyf.int    ; New Reno Evan Hollyfeld
{423}{}{Húsdaráló}                     # ncTyson.int     ; New Reno Mike Tyson
{424}{}{Tudós}                      # ncScient.int    ; New Reno Generic Scientist
{425}{}{Merk}                           # SCMerk.int      ; Merk an NCR mob type guy
{426}{}{Szurkoló}                            # ncBoxFan.int    ; New Reno Boxing Fan
{427}{}{Drogárus}                    # ncDrgDlr.int    ; New Reno Drug Dealer
{428}{}{Kaszinó vendég}                  # ncCasPat.int    ; New Reno Casino Patron
{429}{}{Strici}                           # ncPimp.int      ; New Reno Generic Pimp
{430}{}{Narkós}                         # ncJunkie.int    ; New Reno Generic Junkie
{431}{}{Bútor}                      # stuff.int       ; signals critters on steal attempt
{432}{}{Padló}                          # trespass.int    ; same as stuff only for an area
{433}{}{Talaj}                         # ATDeath.int     ; Spatial telling the player about Nagor dead
{434}{}{Hololemez}                       # SIFakhlo.int    ; Fake holodisk you get from Merk in NCR.
{435}{}{Lenny}                          # SCLenny.int     ; Lenny a guy in NCR Entrance
{436}{}{Doboz}                            # SCPtbox.int     ; Players temp box to hold his stuff for the fight with lenny
{437}{}{Prostituált}                     # ncProsti.int    ; New Reno Prostitute with billions of messages
{438}{}{Rabszolga}                          # ncSlave.int     ; New Reno Slaves
{439}{}{Rico}                           # ncRico.int      ; New Reno Rico, Monte's thug
{440}{}{Pornó-színésznõ}                   # ncActres.int    ; New Reno Porn Actress
{441}{}{Kurva}                        # ncFluffe.int    ; New Reno Porn Fluffer/Extra
{442}{}{Map Script}                     # Klacanyn.int    ; Map script for Klamath Canyon
{443}{}{Farkas}                           # ECWlfPck.int    ; Military Base Wolf Pack
{444}{}{Generátor}                      # ESPwrGen.int    ; Military Base Power Generator
{445}{}{Ajtó}                           # ESLkDor.int     ; Military Base Locked Door (-30)
{446}{}{Szupermutáns}                   # ECGenMut.int    ; Military Base Generic Mutant
{447}{}{Salvatore embere}                # ncSalMen.int    ; New Reno Salvatore's Men
{448}{}{Bishop embere}                   # ncBisMen.int    ; New Reno Bishop's Men
{449}{}{Mordino embere}                  # ncMorMen.int    ; New Reno Mordino's Men
{450}{}{Wright-gyerek}                 # ncWriTee.int    ; New Reno Wright's Sons & Daughters
{451}{}{Kidobóember}                 # ncCasBou.int    ; New Reno Generic Casino Bouncer
{452}{}{Mira}                           # SCMira.int      ; NCR entrance bartender
{453}{}{New Reno, Szûz utca}         # NewR1.int       ; New Reno Map Virgin Street
{454}{}{New Reno, Második utca}            # NewR2.int       ; New Reno Map 2nd Street
{455}{}{New Reno, Kereskedelmi negyed}        # NewR3.int       ; New Reno Map Commercial Row
{456}{}{New Reno, Keleti oldal}             # NewR4.int       ; New Reno Map East Side
{457}{}{New Reno, Istálló}               # NewRSt.int      ; New Reno Map Stables
{458}{}{New Reno, Rontó-Bontó}             # NewRCS.int      ; New Reno Map Chop Shop
{459}{}{New Reno, Gologta}              # NewRGo.int      ; New Reno Map Gologtha
{460}{}{New Reno, Bishop alagsora}       # NewRBa.int      ; New Reno Map Bishop Basement
{461}{}{Hololemez}                       # EIOutDsk.int    ; Military Base Holodisk (Outside)
{462}{}{Hololemez}                       # EILv1Dsk.int    ; Military Base Holodisk (Level 1)
{463}{}{Hololemez}                       # EILv2Dsk.int    ; Military Base Holodisk (Level 2)
{464}{}{Hololemez}                       # EILv3Dsk.int    ; Military Base Holodisk (Level 3)
{465}{}{Hololemez}                       # EILv4Dsk.int    ; Military Base Holodisk (Level 4)
{466}{}{Õr}                          # SCGteGrd.int    ; Ncr gate guard
{467}{}{Csörlõ}                      # ESMinCrt.int    ; Military Base Mine Cart to explode on door
{468}{}{Melchior}                       # ECMelchr.int    ; Melchoir the Magnificent (psuedo-mage)
{469}{}{Mutáns szörny}                  # ECMutRat.int    ; Mutated Rats in Military Base
{470}{}{FEV Ragacs}                        # ETGoo.int       ; FEV Goo in the Military Base
{471}{}{Õrség kapitány}                  # SCGGCap.int     ; NCR Entrance Gate guard captain
{472}{}{Rabszolga-felügyelõ}                 # SCslvovr.int    ; NCR Entrance slave overseer
{473}{}{Melchior szörnye}                 # ECMelPet.int    ; Melchior's Pets
{474}{}{Rabszolga-hajcsár}                   # SCslvgrd.int    ; Slaver Guard in NCR Entrance
{475}{}{Ajtó}                           # SIclsdor.int    ; Closing door
{476}{}{Terminál}                       # SITerm.int      ; Slave pen terminals NCR Entrance
{477}{}{Pénznyerõ automata}                   # ziSlots.int     ; Generic Slot Machine
{478}{}{Gyerek}                          # ncWriChi.int    ; New Wright children
{479}{}{Sheb}                           # ncSheb.int      ; New Reno Sheb
{480}{}{Õr}                          # SCMrkGrd.int    ; Merk's guards NCR Entrance and council
{481}{}{Emitter}                        # SIEmtr.int      ; Emitter in NCR Entrance
{482}{}{Erõtér}                    # SIFField.int    ; Force field in NCR Entrance
{483}{}{Sulik}                          # Kcsulik.int     ; Sulik from Klamath
{484}{}{Dr. Henry}                      # SCHenry.int     ; Henry NCR Entrance
{485}{}{Õr}                          # SCCarGrd.int    ; Carlson's guards NCR2
{486}{}{Carlson Guards Attack}          # STCaratk.int    ; Carlson's guards attack spatial
{487}{}{Carlson kapuõre}          # SCcgtgrd.int    ; Carlson's gate Guards
{488}{}{Fogoly}                       # VCOutPrs.int    ; Vault City Outsider Prisoner (Generic)
{489}{}{Fogoly}                       # VCCitPrs.int    ; Vault City Citizen Prisoner (Generic)
{490}{}{Polgár}                        # VCGenFam.int    ; Vault City Generic Family
{491}{}{Komfort felelõs}                  # VCAmAid.int     ; Vault City Amenities Aid
{492}{}{Eligazító õr}                     # GCRDesk.int     ; Gecko Reactor Desk Guard
{493}{}{Ghoul Munkás}                   # GCRGhoul.int    ; Gecko Reactor Ghoul Worker
{494}{}{Fénylõ ghoul}                    # GCRGlow.int     ; Gecko Glowing One
{495}{}{Ghoul õr}                    # GCRGuard.int    ; Gecko Red Door Guard
{496}{}{Robot}                          # GCRobot.int     ; Gecko Reactor Robot
{497}{}{Ghoul}                          # GCFolk.int      ; Gecko Townsfolk
{498}{}{Hívõ}                           # GCWorshp.int    ; Gecko Worshippers
{499}{}{Harold}                         # GCHarold.int    ; Harold in Gecko
{500}{}{Tiszt}                        # GCPACOff.int    ; Gecko Powered Armor Com Officer
{501}{}{Toto}                           # SCToto.int      ; Toto hlper bot in NCR 1
{502}{}{Dorothy}                        # SCDoroth.int    ; Dorothy Repair chick in NCR 1
{503}{}{Városlakó}                    # ncPerson.int    ; New Reno Generic Townsperson/Citizen
{504}{}{Ghoul õr}                    # GCYGuard.int    ; Gecko Yellow Door Guard
{505}{}{Ghoul õr}                    # GCGuard.int     ; Gecko Generic Guard
{506}{}{Gond}                           # SCGond.int      ; Ranger Guard, NCR 1
{507}{}{Duppo}                          # SCDuppo.int     ; Stockman's yard store owner
{508}{}{Cucc}                          # SIdtbl.int      ; Duppo's tables in shop
{509}{}{Bob}                            # SCsalbob.int    ; Salt Beef Bob NCR 3
{510}{}{Kaszinólány}                    # ziDceGrl.int    ; Generic Casino Girl with Dice Game
{511}{}{Kaszinólány}                    # niDceGrl.int    ; New Reno Casino Girl with Dice Game
{512}{}{Mágikus 8-as golyó}               # zi8Ball.int     ; EPA Magic 8 Ball
{513}{}{Brahmin}                        # ncAngBra.int    ; New Reno Angry Brahmin
{514}{}{Pénznyerõ automata}                   # niMcGSlt.int    ; New Reno McGee's Slot Machine
{515}{}{Vén McGee}                  # ncMcGee.int     ; New Reno Old Man (Bobby) McGee
{516}{}{"Ittapiros" Monte}               # nc3Monte.int    ; New Reno Three Card Monte
{517}{}{Algernon}                       # ncAlgern.int    ; New Reno Algernon
{518}{}{Bill}                           # ncBill .int     ; New Reno Bill (Trees Lounge)
{519}{}{Testõr}                      # ncBisGrd.int    ; New Reno Bishop's Bodyguards
{520}{}{John Bishop}                    # ncBishop.int    ; New Reno John Bishop
{521}{}{Játékautomata}                 # niCasMac.int    ; New Reno Casino Machine
{522}{}{Rontó-Bontó szerelõ}                  # ncChpBoy.int    ; New Reno Chop Shop Boys
{523}{}{Chris Wright}                   # ncChrWri.int    ; New Reno Chris Wright
{524}{}{Cody}                           # ncCody .int     ; New Reno Cody
{525}{}{A Korzikai Testvérek egyike}                # ncCorBro.int    ; New Reno Corsican Bothers
{526}{}{Eldridge}                       # ncEldrid.int    ; New Reno Eldridge
{527}{}{Etil Wright}    # ncEthWri.int    ; New Reno Ethyl Wright
{528}{}{Tully atya}                   # ncFTully.int    ; New Reno Father Tully
{529}{}{HumperdumperDIDO}               # ncHumper.int    ; New Reno HumperdumperDIDO
{530}{}{Kis Jesus Mordino}             # ncLilJes.int    ; New Reno Lil' Jesus Mordino
{531}{}{Csipkés Jimmy J.}                 # ncJimmyJ.int    ; New Reno Jagged Jimmy J
{532}{}{Keith Wright}                   # ncKeiWri.int    ; New Reno Keith Wright
{533}{}{Lee Anne Bishop}                # ncLABish.int    ; New Reno Lee Anne Bishop
{534}{}{Szépfiú Lloyd}               # ncLloyd.int     ; New Reno Pretty Boy Lloyd
{535}{}{Mason}                          # ncMason.int     ; New Reno Mason
{536}{}{Istálló õr}                          # ncMyrGrd.int    ; New Reno Myron's Guards
{537}{}{Myron}                          # nhMyron.int     ; New Reno Myron (Talking Head)
{538}{}{Nikki}                          # ncNikki.int     ; New Reno Darlin' Nikki
{539}{}{Orville Wright}                 # ncOrvill.int    ; New Reno Orville Wright
{540}{}{Felvigyázó}                       # ncPitBos.int    ; New Reno Generic Pit Boss
{541}{}{Rakétás Renesco}         # ncRenesc.int    ; New Reno Renesco the Rocket-Man
{542}{}{Kutató}                     # ncResear.int    ; New Reno Stables Researcher
{543}{}{Salvatore, a nagyfõnök}                 # ncSalvat.int    ; New Reno Boss Salvatore
{544}{}{Stuart Little}                  # ncStuLit.int    ; New Reno Stuart Little (Agent)
{545}{}{T-Ray}                          # ncTRay .int     ; New Reno T-Ray
{546}{}{Kurva}                          # ncBitch.int     ; New Reno Corsican Brothers Bitches
{547}{}{Wright-gyerek}                   # ncWriPly.int    ; New Reno Wright Children Playing
{548}{}{ÚKK rendõr}                     # SCCop.int       ; NCR cop
{549}{}{Oswald}                         # SCOswald.int    ; Raider Oswald captive NCR 1
{550}{}{Dusty}                          # SCDusty.int     ; Dusty bartender in NCR 1
{551}{}{Jules}                          # ncJules.int     ; New Reno Jules
{552}{}{Kitty kisasszony}                     # ncKitty.int     ; New Reno Miss Kitty
{553}{}{Csapos}                      # ncBarten.int    ; New Reno Bartender
{554}{}{Karl, a megbízott}                    # SCKarl.int      ; NCR Deputy
{555}{}{Cella ajtaja}                      # SIKdoor.int     ; NCR Cell door
{556}{}{Nagy Jesus Mordino}              # ncBigJes.int    ; New Reno Big Jesus Mordino
{557}{}{Hoss}                           # SCHoss.int      ; Hoss, bully NCR 1 map
{558}{}{Mutagén Szérum}                # SIMserum.int    ; Mutagenic Serum
{559}{}{Doboz}                            # niSalBox.int    ; New Reno Salvatore Bartender Shop Inventory
{560}{}{Doboz}                            # niMorBox.int    ; New Reno Mordino Bartender Shop Inventory
{561}{}{Doboz}                            # niBisBox.int    ; New Reno Bishop Bartender Shop Inventory
{562}{}{Doboz}                            # niTmpBox.int    ; New Reno Personal Inventory Swap Box
{563}{}{Doktor Jubilee}                 # SCDocJub.int    ; Doctor Jubilee NCR Map 1
{564}{}{Ajtó}                           # GSYDoor.int     ; Yellow Door in Gecko Reactor
{565}{}{Ajtó}                           # GSRDoor.int     ; Red Door in Gecko Reactor
{566}{}{Könyvszekrény}                       # SIdshelf.int    ; Bookshelf for the Doc NCR 1
{567}{}{Dumont seriff}                 # SCsherif.int    ; Sheriff in NCR map 1
{568}{}{Elise}                          # SCElise.int     ; Elise in NCR map 1 ranger leader chick
{569}{}{Ranch dolgozó}                     # SCwrHand.int    ; Westin Ranch Hand NCR 3
{570}{}{Felix}                          # SCFelix.int     ; Westin's forman on NCR 3
{571}{}{Westin}                         # SCWestin.int    ; Westin big dude on NCR 3
{572}{}{Rondo}                          # SCRondo.int     ; Rondo Ranger NCR 1
{573}{}{Robokutya}                        # SCRobo.int      ; Robodog NCR 1
{574}{}{Lépcsõ}                         # NIBissta.int    ; New Reno Bishop's stairs
{575}{}{Hal}                            # SCHal.int       ; Hal, Drive Leader
{576}{}{Gunther}                        # SCGunthr.int    ; Gunther Tandi's assistant NCR 2
{577}{}{Brahmin}                        # ECCrtBra.int    ; Random Encounter Brahmin for carts
{578}{}{Karavánmester}                 # ECCvnMst.int    ; Random Encounter Caravan Master
{579}{}{Karavánvezetõ}                 # ECCvnDrv.int    ; Random Encounter Caravan Driver
{580}{}{Karaván õr}                  # ECCvnGrd.int    ; Random Encounter Caravan Guard
{581}{}{Fosztogató}                         # ECRadLdr.int    ; Random Encounter Raider Leader
{582}{}{Gengszter}                        # ECMobstr.int    ; Random Encounter Mobster (Outside New Reno)
{583}{}{Vadász}                         # ECHntLdr.int    ; Random Encoutner Hunting Party Leader
{584}{}{Vadász}                         # ECHunter.int    ; Random Encounter Hunting Party
{585}{}{Felderítõ}                         # ECRanger.int    ; Random Encounter NCR Rangers (Patrol)
{586}{}{Zsoldos}                      # ECMercs.int     ; Random Encounter Mercenaries
{587}{}{Zsoldos}                      # ECMrcLdr.int    ; Random Encounter Mercenary Leader
{588}{}{Fosztogató}                         # ECRadGrp.int    ; Random Encounter Raider Party
{589}{}{Karavánvezetõ}                 # ECRndDrv.int    ; Random Encounter Other Caravan Driver
{590}{}{Karaván õr}                  # ECRndGrd.int    ; Random Encounter Other Caravan Guard
{591}{}{Járõr}                   # ECVltPat.int    ; Random Encounter Vault City Patrols
{592}{}{Járõr kapitány}                 # ECVltCpt.int    ; Random Encounter Vault City Patrol Capt.
{593}{}{Farmer}                         # ECFarmer.int    ; Random Encounter Farmer
{594}{}{Brahmin}                        # ECBraHrd.int    ; Random Encounter Brahmin Herd
{595}{}{Brahmin}                        # ECLedBra.int    ; Random Encounter Lead Brahmin
{596}{}{Utazó}                       # ECTrvlr.int     ; Random Encounter Traveler
{597}{}{Járõr}                   # ECGhlPat.int    ; Random Encounter Ghoul Patrol
{598}{}{Járõr kapitány}                 # ECGhlCpt.int    ; Random Encounter Ghoul Patrol Capt.
{599}{}{Járõr}                   # ECMutPat.int    ; Random Encounter Mutant Patrol
{600}{}{Járõr kapitány}                 # ECMutCpt.int    ; Random Encounter Mutant Patrol Capt.
{601}{}{Brahmin hajtó}                 # ECBraDrv.int    ; Random Encounter Brahmin Driver
{602}{}{Marhatolvaj}                        # ECBraRst.int    ; Random Encounter Brahmin Rustler
{603}{}{Földbitorló}                       # ECSquatr.int    ; Random Encounter Squatters
{604}{}{Szörnyszakértõ}                   # ECAbolst.int    ; Random Encounter Abolitionist
{605}{}{Szeszcsempész}                     # ECMonShn.int    ; Random Encounter Moonshine Runner
{606}{}{Szuper Mutáns}                   # ECRogMut.int    ; Random Encounter Rogue Super Mutants
{607}{}{Halász}                      # ECFshrmn.int    ; Random Encounter Fisherman
{608}{}{Rabszolga-hajcsár}                         # ECSlaver.int    ; Random Encounter Slaver
{609}{}{Prémvadász}                        # ECTrappr.int    ; Random Encounter Trapper
{610}{}{Carlson kölyök}                  # SCCarkid.int    ; Carlson's kid NCR map 2
{611}{}{Carlson}                        # SCCarlsn.int    ; Carlson NCR 2
{612}{}{}                               # Animfrv.int     ; Animate forever
{613}{}{Jack, a tiszt}                   # SCOfjack.int    ; Officer Jack NCR 1
{614}{}{A Megvilágosodott}            # SCEnlOne.int    ; The Enlightened One NCR 1
{615}{}{Ajtó}                           # diDoor.int      ; Den Auto Closing Door
{616}{}{Számítógép}                       # GsTerm.int      ; Gecko robot control terminal
{617}{}{Brahmin}                         # SCBrahmn.int    ; NCR Map 4 Brahmin.
{618}{}{Halálkarom}                      # SCDthcla.int    ; NCR Map 4 Deathclaw.
{619}{}{Kijárat}                      # SIExit.int      ; NCR Map 4 Exit Grid control
{620}{}{Számítógép}                       # SSComp.int      ; NCR Map 1 computer terminal that blows up
{621}{}{Feargus}                        # SCFergus.int    ; NCR Map 2
{622}{}{Ariel}                          # OCAriel.int     ; Vault 13 Ariel
{623}{}{Fannie Mae}                     # RCFannie.int    ; Fannie Mae the hooker in Redding
{624}{}{Számítógép-terminál}              # OCComptr.int    ; Computer terminal in Vault 13
{625}{}{Dalia}                          # OCDalia.int     ; Dalia in Vault 13
{626}{}{Dar}                            # OCDar.int       ; Dar Deathclaw guard Vault 13
{627}{}{Dave}                           # OCDave.int      ; Dave NPC in Vault 13
{628}{}{Gordon}                         # OCGordon.int    ; Gordon the shrine temple dude
{629}{}{"Üzemen kívül" tábla}           # ziClosed.int    ; Generic "Out of Business" signs
{630}{}{Reaktor vezérlõ gépezet}      # gsReactr.int    ; Script to animate reactor
{631}{}{Jimmy}                          # OCJimmy.int     ; Jimmy guy in computer room Vault 13
{632}{}{Joseph}                         # OCJoseph.int    ; The Doctor in Vault 13
{633}{}{Matt}                           # OCMatt.int      ; Matt prisonner in Vault 13
{634}{}{}                               # RCFitRat.int    ; Redding Fighting Molerats
{635}{}{Map Script}                     # RedMEnt.int     ; Redding Mine Entrance Map Script
{636}{}{V13 map script}                 # vault13.int     ; Vault13 map script
{637}{}{Sandy}                          # OCSandy.int     ; Sandy Vault 13 child.
{638}{}{Doboz}                            # ziTmpBox.int    ; Generic Temporary swap box
{639}{}{Thearn}                         # OCThearn.int    ; Vault 13 Guard Thearn.
{640}{}{Doboz}                            # miGriBox.int    ; Modoc Grisham Merchant box
{641}{}{Doboz}                            # miJoBox.int     ; Modoc Jo Merchant box
{642}{}{Valdis}                         # OCValdis.int    ; Valdis guard in Vault 13
{643}{}{Számítógép-terminál}              # OSvdrcmp.int    ; Door computer vault 13 entrance
{644}{}{Fémszekrény}                   # OIÖltözõszekrény.int    ; Metal locker in Vault 13
{645}{}{Katonai láda}                     # OIftlkr.int     ; Footlocker in Vault 13
{646}{}{Halálkarom õr}                # OCgrunt.int     ; Generic Vault 13 Deathclaw guard
{647}{}{Goris}                          # OCGoris.int     ; Goris possible party NPC vault 13
{648}{}{Doboz}                            # miBalBox.int    ; Modoc Balthas Merchant box
{649}{}{Fémszekrény}                   # siÖltözõszekrény.int    ; Guard's lockers in NCR 1
{650}{}{Csaló}                        # Cheater.int     ; Cheater Character
{651}{}{V15 map Script}                 # vault15.int     ; Vault 15 map script
{652}{}{Phil}                           # bcPhil.int      ; Phil the secret vault 15 entrance guard
{653}{}{Bill}                           # bcBill.int      ; Bill in Vault 15 Entrance
{654}{}{Mészáros}                        # mcButchr.int    ; Slaughter house guys in Modoc
{655}{}{Dalia}                          # bcDalia.int     ; Guard who guards a trail and shows up in v13
{656}{}{John}                           # bcJohn.int      ; Vault 15 guy entrance
{657}{}{Jones}                          # BCJones.int     ; Vault 15 doctor
{658}{}{Karla}                          # BCKarla.int     ; Karla Vault 15 guard.
{659}{}{M15 titkos bejárat térkép}      # V15sent.int     ; Vault 15 secret entrance map
{660}{}{Rebecca}                        # BCRebecc.int    ; Vault 15 Rebecca
{661}{}{Ajtó}                           # miDoor.int      ; Modoc Doors
{662}{}{Halálkarom}                     # mcDthClw.int    ; Modoc Rose's "Chicken"
{663}{}{Roberta}                        # bcRobert.int    ; Roberta Vault 15 Entrace
{664}{}{Sara}                           # bcSara.int      ; Sara vault 15 Entrance
{665}{}{Zeke}                           # bcZeke.int      ; Zeke vault 15 Entrance mayor dude
{666}{}{Brahmin}                        # bcBrahmn.int    ; Generic Brahmin in Vault15 Entrance
{667}{}{Faajtó}                      # BiEntDr.int     ; Trapped Vault15 entrance door
{668}{}{Chrissy}                        # BCCrissy.int    ; Crissy, Rebecca's daughter
{669}{}{Darion}                         # BCDarion.int    ; Big bad dude in Vault 15
{670}{}{Darion testõre}                 # BCDargrd.int    ; Darion's guard in Vault 15
{671}{}{Darion kutyája}                   # BCDardog.int    ; Darion's dog in Vault 15
{672}{}{Cassidy}                        # VCCasidy.int    ; Cassidy the  bar person in Vault City
{673}{}{Kút}                           # miWell.int      ; Modoc Well
{674}{}{Vakondpatkány}                       # mcMolRat.int    ; Modoc Shitter Mole Rat
{675}{}{Nagydarab brahmin}                  # miBraMea.int    ; Modoc Brahmin Chunks
{676}{}{Brahmin}                        # mcKilBra.int    ; Modoc Slaughterhouse brahmin
{677}{}{Liftajtó}                  # bsElev.int      ; Elevator door in V15sent
{678}{}{Kutya}                            # mcKilDog.int    ; Modoc Dog that hangs out at the slaughter house
{679}{}{Patkány}                            # mcRat.int       ; Modoc Garden Rat
{680}{}{Napsütéses hely}                       # ziSunSpt.int    ; Generic Sun Spot
{681}{}{Bess}                           # mcBess.int      ; Modoc Bess the Brahmin
{682}{}{Doboz}                            # miJkyBox.int    ; Modoc Jerky box
{683}{}{Kockajátékos}                   # zcCrpDel.int    ; Craps Dealer
{684}{}{15-ös Menedékõr}                 # bcGenGrd.int    ; Vault 15 Khan Guard
{685}{}{Az aljanép egyike}                           # mcSlag.int      ; Modoc Generic Slag
{686}{}{Szõnyeg}                            # mtRug.int       ; Modoc Spacial Script for Rug
{687}{}{Gyerek}                          # mcChild.int     ; Modoc Child
{688}{}{Aileen}                         # hcAileen.int    ; Aileen in Broken Hills
{689}{}{Õr}                          # hcBnkGrd.int    ; Bank Guard in Broken Hills
{690}{}{Holiday doki}                    # hcDoc.int       ; Doc in Broken Hills
{691}{}{Bérenc}                       # hcencha.int     ; Henchman A in Broken Hills
{692}{}{Bérenc}                       # hcenchb.int     ; Henchman B in Broken Hills
{693}{}{Nõ}                          # hcfemale.int    ; Female in Broken Hills
{694}{}{Francis}                        # hcFranci.int    ; Francis in Broken Hills
{695}{}{Frank}                          # hcFrank.int     ; Frank in Broken Hills
{696}{}{Ghoul}                          # hcGhoul.int     ; Ghoul in Broken Hills
{697}{}{Liz}                            # hcLiz.int       ; Liz in Broken Hills
{698}{}{Férfi}                            # hcmale.int      ; Male in Broken Hills
{699}{}{Manson}                         # hcManson.int    ; Manson in Broken Hills
{700}{}{Marcus}                         # hcMarcus.int    ; Marcus in Broken Hills
{701}{}{Bányász}                          # hcMiners.int    ; Miners in Broken Hills
{702}{}{Mutáns}                         # hcMutant.int    ; Mutant in Broken Hills
{703}{}{Bill}                           # hcOutfit.int    ; Outfitter in Broken Hills
{704}{}{Phil}                           # hcPhil.int      ; Phil the bartender in Broken Hills
{705}{}{Steve}                          # hcSteve.int     ; Steve in Broken Hills
{706}{}{Ellenõr}                     # hcSuper.int     ; Supervisor in Broken Hills
{707}{}{Zaius}                          # hcZaius.int     ; Zaius in Broken Hills
{708}{}{Jacob}                          # hcJacob.int     ; Jacob in Broken Hills
{709}{}{Kémikus készlet}                  # hchems.int      ; Chemistry Set in Broken Hills
{710}{}{Karó}                           # miGstPrp.int    ; Modoc Ghost Farm Prop
{711}{}{Ajtó}                           # bssdor1.int     ; Shack doors on V15sEnt map
{712}{}{Számítógép}                       # BSComp1.int     ; Library Computer Vault 15
{713}{}{Chad}                           # hcchad.int      ; Chad from Broken Hills
{714}{}{Húsevõ növény}                    # ECPlant.int     ; Random Encounter Spore Plant
{715}{}{Gekkó}                          # ECGecko.int     ; Random Encounter Gecko
{716}{}{Radskorpió}                    # ECScorp.int     ; Random Encounter Scorpions
{717}{}{}                               # ECRat.int       ; Random Encounter Rats
{718}{}{Harcos}                        # ECWarPty.int    ; Random Encounter War Party
{719}{}{Kannibál}                       # ECCanibl.int    ; Random Encounter Cannibals
{720}{}{Számûzött}                        # ECOutCst.int    ; Random Encounter Outcasts
{721}{}{Szent ember}                    # ECHlyPpl.int    ; Random Encounter Holy People
{722}{}{Nomád}                          # ECNomad.int     ; Random Encounter Nomads
{723}{}{Hajléktalan}                # ECHomles.int    ; Random Encounter Homeless
{724}{}{Bandita}                         # ECBandit.int    ; Random Encounter Bandit
{725}{}{Rabló}                         # ECRobber.int    ; Random Encounter Robber
{726}{}{Útonálló}                     # ECHiwymn.int    ; Random Encounter Highwaymen
{727}{}{Rabszolga-hajcsár}                         # ECSlvRun.int    ; Random Encounter Slavers on a Slave Run
{728}{}{Rabszolga}                          # ECSlave.int     ; Random Encounter Slaves
{729}{}{Bulizó}                        # ECRavPty.int    ; Random Encounter Rave Party
{730}{}{Imádkozó sáska}                         # ECMantis.int    ; Random Encounter Mantis
{731}{}{Brahmin}                        # ECBrahmn.int    ; Random Encounter Brahmin
{732}{}{Kutya}                            # ECWldDog.int    ; Random Encounter Wild Dogs
{733}{}{Számítógép}                       # BSComp2.int     ; Darion's computer terminal Vault15
{734}{}{Számítógép}                       # BSComp3.int     ; Force field computer terminal
{735}{}{Számítógép-terminál}              # BSComp4.int     ; Force Field control computer by entrance Vault 15
{736}{}{Számítógép}                       # BSComp5.int     ; Computer at the Power area. Vault 15
{737}{}{Áramfejlesztõ}                # BSPower.int     ; Power Generator in Vault 15
{738}{}{Erõtér}                    # BSField.int     ; Force Field in Vault 15
{739}{}{Paraszt}                        # mcPeasan.int    ; Modoc Peasant Person
{740}{}{Emitter}                        # bsEmtr.int      ; Emitter in Vault 15
{741}{}{Menedék-ajtó}                     # osv13dr.int     ; Vault 13 Door
{742}{}{Biztonsági ajtó}                  # osDoor1.int     ; Vault 13 Door that shows deathclaws
{743}{}{Találkozás Bess-szel}                 # rndBess.int     ; Random Encounter for Bess outside of modoc
{744}{}{Bess}                           # ECBess.int      ; Bess in Bess's Encounter (she's dead jim)
{745}{}{Brahmin}                        # ECBesCow.int    ; One of the Brahmin in Bess's herd
{746}{}{Angela Bishop}                  # ncAngBis.int    ; New Reno Angela Bishop
{747}{}{Tökös Tomi} # ncTommy.int ; New Reno Tommy the Balls (YEAH! OUR HERO)
{748}{}{Széf}                           # niABisSf.int    ; New Reno Angela Bishop's Safe
{749}{}{Széf}                           # niMrBSf.int     ; New Reno Mr. Bishop's Safe
{750}{}{Széf}                           # niMrsBSf.int    ; New Reno Mrs. Bishop's Safe
{751}{}{Széf}                           # niOWriSf.int    ; New Reno Orville Wright's Safe
{752}{}{Sírhely}                          # niPriGrv.int    ; New Reno Pritchard's Grave
{753}{}{Ruhásszekrény}                        # niWridrs.int    ; New Reno Richard Wright's Dresser
{754}{}{Sírhely}                          # niWriGrv.int    ; New Reno Righard Wright's Grave
{755}{}{Szeszlepárló}                          # niWriSti.int    ; New Reno Wright Stills
{756}{}{Ramirez}                        # ncRamire.int    ; New Reno Ramirez
{757}{}{Barlang 1, Véletlen esemény}    # cave01.int      ; Cave 1 Random Encounter Map
{758}{}{Doboz}                            # niRenBox.int    ; New Reno Renesco Box
{759}{}{Ajtó}                           # niDoor.int      ; New Reno Door
{760}{}{Barlang 2, Véletlen esemény}    # cave02.int      ; Cave 2 Random Encounter Map
{761}{}{Barlang 3, Véletlen esemény}    # cave03.int      ; Cave 3 Random Encounter Map
{762}{}{Barlang 4, Véletlen esemény}    # cave04.int      ; Cave 4 Random Encounter Map
{763}{}{Barlang 2, Véletlen esemény}    # cave02.int      ; Cave 2 Random Encounter Map
{764}{}{Ajtó}                           # VIEntDor.int    ; Vault City Entrance Door
{765}{}{Map Script}                     # VCtyDwtn.int    ; Vault City Downtown Map script
{766}{}{Csapóajtó}                      # miTrpDor.int    ; Modoc Ghost Farm Trap Door
{767}{}{Páncéldoboz}                        # Hilbox.int      ; Broken Hills Liz inventory box
{768}{}{Szoba}                           # ntLydRom.int    ; New Reno Lloyd Room
{769}{}{Thomas Moore}                   # VCMoore.int     ; Thomas Moore from Vault City
{770}{}{Ajtó}                           # ZILckDor.int    ; Generic Locked Door (-20)
{771}{}{Öltözõszekrény}                         # niLydBox.int    ; New Reno Lloyd's Loot Box
{772}{}{Aknanyílás}                        # niManhol.int    ; New Reno Manhole to Lloyd's Loot
{773}{}{Sírhely}                          # niLydGrv.int    ; New Reno Lloyd's Loot Grave
{774}{}{Raktár õr}                   # VCSupGrd.int    ; Vault City Supply Guard Martin
{775}{}{Map Script}                     # broken1.int     ; Map Script for Broken Hills Map 1
{776}{}{Map Script}                     # rndexcow.int    ; Map Script for Low Luck encounter
{777}{}{Veszett brahmin}                    # eccowbmb.int    ; The cows that blow
{778}{}{Hakeswill}                      # RCHakes.int     ; Hakeswill from Redding
{779}{}{Redding, Belváros}               # REDDown.int     ; Redding Downtown map script
{780}{}{Map Script}                     # BHRndDst.int    ; Broken Hills Caravan Desert Map
{781}{}{Map Script}                     # BHRndMtn.int    ; Broken Hills Caravan Mountain Map
{782}{}{Lou}                            # RCLou.int       ; Lou from Redding
{783}{}{Arthur}                         # ECArthur.int    ; Arthur the leader of the Special Encounter knights
{784}{}{Robin}                          # ECRobin.int     ; Robin one of the Knights with Arthur
{785}{}{Bedemir}                        # ECBedemi.int    ; Bedemir one of the Knights with Arthur
{786}{}{Sir Launcelot}                  # ECSirLau.int    ; Sir Launcelot one of the Knights with Arthur
{787}{}{Galahad}                        # ECGalaha.int    ; Galahad one of the knights iwth Arthur
{788}{}{Ben Wade}                       # RCWade.int      ; Ben Wade from Radding
{789}{}{Athabaska Dick}                 # RCDick.int      ; Athabaska Dick from Redding
{790}{}{Özvegy Rooney-né}                   # RCRooney.int    ; Widow Rooney from Redding
{791}{}{Városlakó}                    # RCGenPes.int    ; Generic Townsperson in Redding
{792}{}{Stanwell}                       # RCStanwl.int    ; Stannwell from Redding
{793}{}{Savinelli}                      # RCSavine.int    ; Savinelli from Redding
{794}{}{Marge}                          # RCMarge.int     ; Marge LeBarge from Redding
{795}{}{Madam Modjeska}                 # RCModjes.int    ; Madam Modjeska from Redding
{796}{}{James Hoffy}                    # RCHoffy.int     ; James Hoffy, Caravan Master for Redding
{797}{}{Map Script}                     # Rndholy1.int    ; Random Encounter Holy Knights 1 map
{798}{}{Balfi}                          # ECPatsy.int     ; Arthur's horse HOLY 1 encounter
{799}{}{Concorde}                       # ECConcor.int    ; Concord Launcelot's horse.
{800}{}{Eric}                           # ECEric.int      ; Robin's horse
{801}{}{John}                           # ECJohn.int      ; Bedemir's horse
{802}{}{Joshua}                         # ECJoshua.int    ; Joshua Robin's minstrel
{803}{}{Létra}                         # miLadder.int    ; Modoc Shitter Ladder
{804}{}{Nagy fej}                       # ecBHead.int     ; Big Head special encounter
{805}{}{Fekete hõs}                     # ecBlkHro.int    ; Black Hero model
{806}{}{Vörös hõsnõ}                    # ecRedHro.int    ; Red Heroine model
{807}{}{Set}                            # ecSet.int       ; Set in Cafe of Broken Dreams
{808}{}{Tandi}                          # ecTandi.int     ; Tandi in Cafe of " "
{809}{}{Fehér hõs}                     # ecWhro1.int     ; White Hero Model 1 " " "
{810}{}{Fehér hõs}                     # ecWhro2.int     ; White Hero Model 2 " " "
{811}{}{Fehér hõsnõ}                  # ecWheon1.int    ; White Heroine Model 1
{812}{}{Doboz}                            # NiJulBox.int    ; New Reno Jules Shop Inventory Box
{813}{}{Doboz}                            # niEldBox.int    ; New Reno Eldridge Shop Box
{814}{}{Doboz}                            # niEldBx2.int    ; New Reno Eldridge Shop Box (For Made Men)
{815}{}{Map Script}                     # rndholy2.int    ; Hi-Luck random Holy knight encounter 2
{816}{}{Vorpal patkány}                     # ECVorRat.int    ; Vorpal Rat for Holy Knight 2
{817}{}{Kutya}                            # ECPDog.int      ; Pariah Dog... not good to have following you around
{818}{}{Kiképzõ õrmester}                 # CCDrill.int     ; Drill Seargant in Colusa/Nevarro (ez nem a neve)
{819}{}{Õr}                          # CCGuard.int     ; Guard in Colusa/Nevarro
{820}{}{Technikus}                     # CCTech.int      ; Technician in Colusa/Nevarro
{821}{}{Parancsnok}                      # CCMandr.int     ; Commander in Colusa Nevarro
{822}{}{Chris}                          # CCChris.int     ; Chris the gas station attendant in Colusa
{823}{}{Raktáros}                 # CCMaster.int    ; Quarter Master in Colusa/Nevarro
{824}{}{Õr}                          # CCGGuard.int    ; Gate Guard in Colusa/Nevarro
{825}{}{Sírhely}                          # ntLydGrv.int    ; New Reno Lloyd's Loot Grave (Spacial Script)
{826}{}{Autó}                            # ntCar1.int      ; New Reno Stolen Car Seed Spacial 1
{827}{}{Autó}                            # ntCar2.int      ; New Reno Stolen Car Seed Spacial 2
{828}{}{Sírhely}                          # niMorGrv.int    ; New Reno Mordino Stash Grave
{829}{}{Köpenyes alak}                   # EcBridge.int    ; Bridge guy special encounter
{830}{}{Marhatartó}                   # SCdrvpay.int    ; Cattle drive from NCR to redding.
{831}{}{Map Script}                     # RndBridg.int    ; Random Bridge encounter
{832}{}{Titokzatos idegen}            # ECMstStr.int    ; Mysterious Stranger
{833}{}{Veszett brahmin}                     # ECgcwbmb.int    ; Generic Cow bomb
{834}{}{}                               # ECYakuza.int    ; Random Encounter Yakuza
{835}{}{}                               # ECWilder.int    ; Random Encounter Wilder
{836}{}{Kutya}                            # ncWriDog.int    ; New Reno Wright Dog
{837}{}{Doboz}                            # niRamBox.int    ; New Reno Box to be delivered to Ramirez
{838}{}{}                               # ECUniPat.int    ; Unity Patrol Random Encounter
{839}{}{}                               # ECTravlr.int    ; Random Encounter Travler
{840}{}{Füst}                          # KtSmoke.int     ; displays message about smoke smell in Duntons
{841}{}{Kereskedõ}                         # ECTrader.int    ; Random Encounter Trader
{842}{}{Guberáló}                      # ECScaven.int    ; Random Encounter Scavenger
{843}{}{Kereskedõ}                       # FCMercha.int    ; San Fran Air bag merchant
{844}{}{Paraszt}                        # FCBadPea.int    ; San Fran Bad Peasants
{845}{}{Arroyo, Templom}                  # ARTemple.int    ; Arroyo Temple map script
{846}{}{Dokkmunkás}                    # FCDokWrk.int    ; San Fran Dock Worker
{847}{}{Polgár}  # FCGudPea.int    ; San Fran Good Peasants
{848}{}{Shi õr}                      # FCShiGrd.int    ; San Fran Shi Guard
{849}{}{Harcos}                        # ACTemVil.int    ; Temple challenge person
{850}{}{Ajtó}                           # AITemDor.int    ; Temple doors that lock at the challenge
{851}{}{Klint}                          # ACKlint.int     ; Klint the guardian of the temple exit
{852}{}{Termés}                          # AICrops.int     ; Crops that die after a period of time
{853}{}{Shi labortechnikus}                   # FCslabte.int    ; San Fran Shi Lab techs
{854}{}{Gyerek}                          # FCSkids.int     ; San Fran Shi Kids
{855}{}{Ghoul}                          # GCWander.int    ; wandering ghouls in Gecko
{856}{}{Dr. Fung}                        # FCDrFung.int    ; San Fran Dr Fung
{857}{}{Jul}                            # OCJul.int       ; Vault 13 Denmother Guard
{858}{}{Kerith}                         # OCKerith.int    ; Vault 13 Den Mother
{859}{}{Láda}                          # AITemCst.int    ; Temple Chest to hold the players things
{860}{}{Ghoul}                          # GCRGhul.int     ; Reactor ghoul that doesn't move
{861}{}{}                               # ECRaiBow.int    ; Random Encounter Gays
{862}{}{}                               # ECMstAmy.int    ; Random Encounter Master's Army
{863}{}{Földmérõ}                       # ECProspe.int    ; Random Encounter Prospector
{864}{}{}                               # ECPrsGng.int    ; Random Encounter Press Gang
{865}{}{Nomád fõnök}                    # ECNomChf.int    ; Random Encounter Nomad Chief
{866}{}{Hubologista}                     # ECElRon.int     ; Hubologist Patrol
{867}{}{Õrült}                          # ECCrazy.int     ; Crazies from Random Encounter
{868}{}{Földfoglaló}                    # ECClmJmp.int    ; Random Encounter Claim Jumpers
{869}{}{Kannibál}                       # ECCanbal.int    ; Random Encounter Cannibals
{870}{}{Nomád sámán}                   # ECNomSha.int    ; Random Encounter Nomad Shamon
{871}{}{Martalóc}                       # ECMaradr.int    ; Random Encounter Marauder
{872}{}{Zsivány}                          # ECRogue.int     ; Random Encounter Rogue
{873}{}{Remete}                         # ECHermit.int    ; Random Encounter Hermit
{874}{}{}                               # ECGangs.int     ; Random Encounter Gangs
{875}{}{Karavánmester}                 # ECMstKla.int    ; Random Encounter Klamath Caravan Master
{876}{}{Karavánmester}                 # ECMstDen.int    ; Random Encounter Den Caravan Master
{877}{}{Karavánmester}                 # ECMstNew.int    ; Random Encounter New Reno Caravan Master
{878}{}{Karavánmester}                 # ECMstRed.int    ; Random Encounter Redding Caravan Master
{879}{}{Karavánmester}                 # ECMstBro.int    ; Random Encounter Broken Hills Caravan Master
{880}{}{Karavánmester}                 # ECMstGec.int    ; Random Encounter Gecko Caravan Master
{881}{}{Karavánmester}                 # ECMstSan.int    ; Random Encounter San Fran Caravan Master
{882}{}{Karavánmester}                 # ECMstNCR.int    ; Random Encounter NCR Caravan Master
{883}{}{Karavánmester}                 # ECMstV15.int    ; Random Encounter Vault 15 Caravan Master
{884}{}{Farmer felesége}                  # ECFrmWfe.int    ; Random Encounter Farmer's wife
{885}{}{Farmer kölyke}                   # ECFrmKid.int    ; Random Encounter Farmer's Kid
{886}{}{Tanyasi}                    # ECHomest.int    ; Random Encounter Homesteader
{887}{}{Tanyasi felesége}             # ECHomwfe.int    ; Random Encounter Homesteader's Wife
{888}{}{Tanyasi kölyke}              # ECHomKid.int    ; Random Encounter Homesteader's Kid
{889}{}{Karavánmester}                 # ECMstVC.int     ; Random Encounter Vault City Caravan Master
{890}{}{}                               # ECAlien.int     ; Random Encounter Alien
{891}{}{}                               # ECDthclw.int    ; Random Encounter Deathclaws
{892}{}{}                               # ECFloatr.int    ; Random Encounter Floater
{893}{}{}                               # ECCentur.int    ; Random Encounter Centaurs
{894}{}{Enklávé járõr}              # ECElvPat.int    ; Random Encounter Enclave Patrol
{895}{}{Zsoldoskapitány}                   # icMrcCpt.int    ; Raiders Merc Captain
{896}{}{Zsoldos fosztogató}                    # icMerc.int      ; Raiders Merc
{897}{}{"Árnyék-Aki-Jár"}             # icScout.int     ; Raiders Scout
{898}{}{Széf}                           # iiSafe.int      ; Raiders Safe
{899}{}{}                               # raiders1.int    ; Raiders 1 Enterance
{900}{}{}                               # raiders2.int    ; Raiders 2 Caves
{901}{}{}                               # HSCellDr.int    ; Broken Hills bank/jail door
{902}{}{Doboz}                            # niTRyBox.int    ; New Reno Chop Shop T-Ray Box
{903}{}{Richardson elnök}           # qhPrzRch.int    ; Enclave President Richardson talking head.
{904}{}{Tarack}                       # WIHowitz.int    ; Howitzer in the Sierra Base
{905}{}{Ajtó}                           # WIEntDor.int    ; Entrance to Sierra Base Door
{906}{}{Halálkarom kölyök}                 # OCBabDth.int    ; Baby Deathclaws in Vault 13
{907}{}{"Veszélyes" Dan}                  # RCMcGrew.int    ; Dangerous Dan McGrew from redding
{908}{}{Johnson doki}                    # RCDrJohn.int    ; Painless Doc Johnson (breaks Jet)
{909}{}{Marion seriff}                 # RCMarion.int    ; Sheriff Earl Marion
{910}{}{Ascorti polgármester}                  # RCAscort.int    ; Mayor Ascorti of Redding
{911}{}{Nording}                        # RCNord.int      ; Nording, the payoff man for Stanwell
{912}{}{Velani}                         # RCVelani.int    ; Velani, the payoff man for Savinelli
{913}{}{Ferndown}                       # RCFern.int      ; Ferndown, the payoff man for Wade
{914}{}{A Sárkány}                     # FCDragon.int    ; The Dragon, San Fran
{915}{}{Istállófiú}                     # mcSblBoy.int    ; Modoc Stable Boy
{916}{}{Kereskedõ}                         # mcTrader.int    ; Modoc Trader
{917}{}{Városlakó}                    # mcPerson.int    ; Modoc Townspeople
{918}{}{Aljanép õr}                           # mcSlgExt.int    ; Ghost Farm Slag Exit Guard
{919}{}{Aljanép õr}                           # mcSlgGrd.int    ; Ghost Farm Slag Enterance Guard
{920}{}{Lo Pan}                         # FCLoPan.int     ; Lo Pan in San Fran.
{921}{}{A Borz}                         # FCBadger.int    ; Badger in San Fran.
{922}{}{Josh}                           # RCJosh.int      ; Josh Laurance of Redding
{923}{}{Caminetto}                      # RCCamint.int    ; Caminetto in bar fight in redding
{924}{}{Bette}                          # RCBette.int     ; Blasphemous Bette in bar fight in redding
{925}{}{Fegyverárus}                   # FCGunmer.int    ; San Fran's gun Merchant
{926}{}{Ajtó}                           # ZIWodDor.int    ; Generic Wooden Door
{927}{}{Ajtó}                           # ZIMtlDor.int    ; Generic Metal Door
{928}{}{Emitter}                        # SSEmtN2.int     ; Emitter in NCR area 2
{929}{}{Patkánykirály}                        # ZCRatGod.int    ; Rat God in Klamath
{930}{}{}                               # ECBox.int       ; Random box that has stuff in it.
{931}{}{Kaga}                           # ECKaga1.int     ; Random Encounter Kaga 1
{932}{}{Kaga}                           # ECKaga2.int     ; Random Encounter Kaga 2
{933}{}{Kaga}                           # ECKaga3.int     ; Random Encounter Kaga 3
{934}{}{Kaga}                           # ECKaga4.int     ; Random Encounter Kaga 4
{935}{}{Kaga}                           # ECKaga5.int     ; Random Encounter Kaga 5
{936}{}{Fejvadász}                  # ECBHunter.int   ; Random Encounter Bounty Hunter
{937}{}{Számítógép}                       # VIMedCom.int    ; Vault City Medical Computer
{938}{}{Számítógép}                       # VICenCom.int    ; Vault City Central Computer
{939}{}{Számítógép}                       # VIAloCom.int    ; Vault City Allocation Computer
{940}{}{Darrow}                         # VCDarrow.int    ; Vault City Sub-Amenities Officer Darrow
{941}{}{Farrell}                        # VCFarrel.int    ; Vault City Sub-Amenities Officer Farrell
{942}{}{Bárvendég}                     # VCBarPat.int    ; Vault City Bar Patron
{943}{}{Menedékvárosi polgár}                  # VCWrkCit.int    ; Vault City Working Citizen
{944}{}{Menedékvárosi szolga}                  # VCSlave.int     ; Vault City Slave
{945}{}{Szellõzõnyílás}              # VIShft2b.int    ; Vault City Ventilation Shaft 2B
{946}{}{Charlie}                        # VCCharli.int    ; Vault City Puking Charlie
{947}{}{Hûtésvezérlõ panel}          # GSValve.int     ; Gecko Coolant Control Panel
{948}{}{Brahminszar}                            # ziBraPoo.int    ; Generic BRAHMIN SHIT!!! YES YES YES
{949}{}{Grant}                          # scWesGrd.int    ; Westin's Force Field Guard
{950}{}{Emitter}                        # SSEmiWes.int    ; Westin's Force Field Emitter
{951}{}{Emitter}                        # SSEmiWe1.int    ; Westin's force field on the other map.
{952}{}{Számítógép-terminál}              # SICmpWes.int    ; Westin's computer terminal for the field.
{953}{}{Uralkodó Terminál v8.8}          # FSEmpTer.int    ; Computer Terminal in San Fran
{954}{}{Bird alelnök}         		   # QCBird.int      ; Enclave, Vice President Bird
{955}{}{Martin}                         # QCMartin.int    ; Enclave, Martin Frobishner, V13 spokesman
{956}{}{Ken Lee}                        # FCKenLee.int    ; Ken Lee in San Francisco
{957}{}{Granite õrmester}                   # QCGranit.int    ; Sgt. Granite of the Enclave Patrol
{958}{}{Frank Horrigan}                 # QCFrank.int     ; Secret Service Agent Frank (End Boss)
{959}{}{Map Script}                     # GeckJunk.int    ; Map Script for Gecko Junkyard
{960}{}{Map Script}                     # GeckTunl.int    ; Map Script for Gecko Tunnels
{961}{}{Ajtó}                           # SSFrgDor.int    ; Fergus's Door script
{962}{}{Ajtó}                           # SSGunDor.int    ; Gunther's Door script to Tandi
{963}{}{Ajtó}                           # SSFlxDor.int    ; Felix's Door script
{964}{}{Kötél}                           # SSRope.int      ; Rope.. for you to climb
{965}{}{Emitter}                        # SSEmiEnt.int    ; Emitter in Ncr Entrance
{966}{}{Dr. Curling}                    # QCCurlng.int    ; Dr. Charles Curling, Chem Corps.
{967}{}{Hirdetõtábla}                 # SSSign.int      ; Sign in NCR Entrance
{968}{}{Vakondpatkány}                       # mcMolRat.int    ; Ghost Farm Mole Rat
{969}{}{Elnök titkárnõje}          # QCPrsSec.int    ; President's personal intern (uh sectretary)
{970}{}{Tom Murray}                     # QCMurray.int    ; Tom Murray, head of AEC
{971}{}{Masszív ajtó}                    # SSCrpDor.int    ; Craps table door in NCR
{972}{}{Városlakó}                    # mcPeasan.int    ; Modoc Peasant, they attack the farm
{973}{}{Menedékváros tanácsház}        # VCtyCocl.int    ; Map Script Vault City Council Area
{974}{}{Légtisztító}                   # HSPurify.int    ; Air Purifier for Broken Hills
{975}{}{Kövek}                          # esEntRks.int    ; Military Base Enterance Rocks
{976}{}{Szerencsejátékos}                        # RCGamble.int    ; Redding Generic Gamblers
{977}{}{Spatial Script}                 # HtCorpse.int    ; Spatial Script for Corpses
{978}{}{SCCheat}                        # SCCheat.int     ; Cheat Character for NCR
{979}{}{Fogoly}                       # QCGenPrs.int    ; Enclave Generic Prisoner
{980}{}{Polgár}                        # QCGenCit.int    ; Enclave Generic Citizens
{981}{}{Õr}                          # QCGenGrd.int    ; Enclave Generic Guards
{982}{}{Tudós}                      # QCGenSci.int    ; Enclave Generic Scientist
{983}{}{Terminál}                       # QIPzlTrm.int    ; Enclave terminal in the Puzzle Level
{984}{}{}                               # etEnter.int     ; Military Base Enterance Spacial Message
{985}{}{}                               # etBattle.int    ; Military Base Battle Area Spacial Message
{986}{}{Emitter}                        # SSEmiEn1.int    ; Ncr emitters for ncr entrance on map 1
{987}{}{Ajtó}                     # QIBstDr1.int    ; Blast Door for Reactor Off to remain closed
{988}{}{Ajtó}                     # QIBstDr2.int    ; Blast Door for Reactor On to remain closed
{989}{}{Darrow áruja}                 # VIDarBox.int    ; Vault City Darrow Shop Inventory
{990}{}{Ajtó}                           # HSCrlDr.int     ; Jail cell door for Broken Hills
{991}{}{Szuperdupermutáns}             # ecTlkMut.int    ; Military Base Conversation Mutants
{992}{}{Vegyész}                        # fcChemst.int    ; Chemist in San Francisco
{993}{}{Grundel}                        # ecGrunde.int    ; Military Base Mouse Hunter
{994}{}{Kölyök}                            # ecMelKid.int    ; Some Town USA, Melchior's Kid
{995}{}{Retinaszkenner}                # WIRetScn.int    ; Retinal Scanner in the Sieera Base
{996}{}{Liftajtó}                  # WIElvDor.int    ; Elevator Door in the Seirra Base
{997}{}{Kibernetikus robottest}          # WIBrkBrn.int    ; Broken Brain Bot in the Sierra Base
{998}{}{Fal}                           # WIScrtDr.int    ; Sierra Base Secert Door
{999}{}{Map Script}                     # broken2.int     ; Map Script for Broken Hills Map 2
{1000}{}{Farrell áruja}               # VIFarBox.int    ; Vault City Farrell Shop Inventory
{1001}{}{Harry áruja}                 # VIHarBox.int    ; Vault City Harry Shop Inventory
{1002}{}{Doboz}                           # VICtyBox.int    ; Vault City Courtyard Temp Inventory Box
{1003}{}{Doboz}                           # VIDwtBox.int    ; Vault City Downtown Temp Inventory Box
{1004}{}{Derek}                         # dcDerek.int     ; Derek in the Den
{1005}{}{Tubby barátja}                # dcTubFri.int    ; Tubby's Junkie Friends in the Den
{1006}{}{Szerencsejátékos}                       # dcGamble.int    ; Gamblers in the Den
{1007}{}{Rabszolga}                         # dcSlave.int     ; Pen Slaves in the Den
{1008}{}{Õr}                         # dcMetRom.int    ; Metzger Room Guard in the Den
{1009}{}{Rabszolga-hajcsár}                        # dcPenGrd.int    ; Slaver Pen Guard in the Den
{1010}{}{Lara}                          # dcLara.int      ; Lara in the Den
{1011}{}{Tyler}                         # dcTyler.int     ; Tyler in the Den
{1012}{}{Marc}                          # dcMarc.int      ; Marc in the Den
{1013}{}{Hirdetõtábla}                # diBulBrd.int    ; Bulletin Board in the Den
{1014}{}{Rabszolga-hajcsár}                        # dcVicGrd.int    ; Vic Guard in the Den
{1015}{}{Rabszolga-hajcsár}                        # dcSlvGrt.int    ; Slaver Greeter in the Den
{1016}{}{Fred}                          # dcFred.int      ; Fred in the Den
{1017}{}{Doboz}                           # diFliBox.int    ; Flick Box in the Den
{1018}{}{Doboz}                           # diMomBox.int    ; Mom Box in the Den
{1019}{}{Doboz}                           # diSmiBox.int    ; Smitty Box in the Den
{1020}{}{Csomagtartó}                     # ZICrTrnk.int    ; generic script for Car Trunk
{1021}{}{Biztonsági ajtó}                 # QIPzlDor.int    ; Door for the puzzle room in the Enclave
{1022}{}{Számítógép-terminál}             # FSPhySta.int    ; Physics computer station in San Fran
{1023}{}{Számítógép-terminál}             # FSBioSta.int    ; Biology computer station in San Fran
{1024}{}{Számítógép-terminál}             # FSCheSta.int    ; Chemistry computer station in San Fran
{1025}{}{Lao Chou}                      # FCLaoCho.int    ; Merchant in San Fran
{1026}{}{}                              # FIPaper.int     ; Scrap Papers that combine should only be put on one of the peaces.
{1027}{}{}                              # CSVent.int      ; Ventilation shaft for Navarro
{1028}{}{Map Script}                    # EncTrp.int      ; Map Script for Enclave Trap Rooms
{1029}{}{Holttest}                     # HtBody.int      ; Script for dead bodies in Broken Hills
{1030}{}{Vezeték}                 # QIWires.int     ; Wires on the ground in the trap room
{1031}{}{Doboz}                           # diMetBox.int    ; Metzger Box from Slave Crap
{1032}{}{Rabszolga}                         # dcRunSlv.int    ; Den Slave Run Fleeing Slaves
{1033}{}{Rabszolga}                         # dcAtkSlv.int    ; Den Slave Run Hostile Slaves
{1034}{}{Rabszolga-hajcsár}                        # dcRnSlvr.int    ; Den Slave Run Slavers
{1035}{}{Chip}                          # FCChip.int      ; Chip in San Fran no splean
{1036}{}{Reaktor}                       # QIReactr.int    ; Reactor in the Enclave
{1037}{}{Reaktor számítógép}              # QIRctrCm.int    ; Reactor Computer in the Enclave
{1038}{}{Pénztáros}                   # RCCshTnd.int    ; Redding Cash Tender in the Casino
{1039}{}{Pénzesláda}                      # RICshBox        ; Cash Box for the Cash Tender
{1040}{}{Wanamingo}                     # RCWanami.int    ; Wanamingo
{1041}{}{Bárvendég}                    # dcStory1.int    ; Story Teller 1 in the Den
{1042}{}{Bárvendég}                    # dcStory2.int    ; Story Teller 2 in the Den
{1043}{}{Börtönajtó}                     # RIJalDor.int    ; Jail Door in Redding
{1044}{}{Suze}                          # FCSuze.int      ; Suze in San Fran
{1045}{}{Ron Meyers, a kapitány}            # FCRonMey.int    ; Captain Ron Meyers
{1046}{}{Ajtó}                      # diPenDor.int    ; Slave Pen Door in the Den
{1047}{}{Wanamingo bánya}                # RedWan1.int     ; Map Script for Wanamingo Mine
{1048}{}{Wanamingo bánya bejárata}       # RedWane.int     ; Map Script for Wanamingo Mine Entrance
{1049}{}{Hûtõs Morton}                   # RCFrog.int      ; Frog Morton
{1050}{}{Dave H.}                       # FCDaveh.int     ; Dave Handy in San Fran
{1051}{}{Ajtó}                          # diVicDor.int    ; Vic's Room Door in the Den
{1052}{}{Ajtó}                          # diRomDor.int    ; Metzger's Room Door in the Den
{1053}{}{Hányós Charlie}                # vccharly.int    ; Puking Charlie in Vault Courtyard
{1054}{}{Festmény}                      # SIPaint.int     ; Revales Vault 13 on examination.
{1055}{}{Map Script}                    # SFChina.int     ; San Fran China Map
{1056}{}{Csapos}                     # VCCouBar.int    ; Vault City Council Area Bartender
{1057}{}{Doboz}                           # VIBarBox.int    ; Vault City Slave Sale Inventory Dump
{1058}{}{Auto-Doki}                      # VIAutDoc.int    ; Vault City Courtyard Auto-Doc
{1059}{}{}                              # RIMinEnt.int    ; Entrance Back to the Mines
{1060}{}{Bányász alagút}                 # RedMTun.int     ; Map Script for Mining Tunnel
{1061}{}{Robot}                         # KCRob.int       ; Robot on Klamath Canyon
{1062}{}{}                              # FiGunTbl.int    ; Gun Merchant table in San fran
{1063}{}{Map Script}                    # KlaMall.int     ; Map Script for Klamath Mall area
{1064}{}{Map Script}                    # KlaTrap.int     ; Map Script for Klamath Still area
{1065}{}{Lydia}                         # VCDwnBar.int    ; Vault City Downtown Bartender
{1066}{}{}                              # RedDTun.int     ; Redding Downtown Tunnels
{1067}{}{Rakétakezelõ}                     # FCRocMan.int    ; Rocket man in San Fran
{1068}{}{BHK-7}                         # FCOz7.int       ; Oz 7 in San Fran
{1069}{}{Crockett}                      # FCCrocke.int    ; Crockett in San Fran
{1070}{}{Amanda}                        # VCAmanda.int    ; Vault City Coutryard Amanda, Joshua's Wife
{1071}{}{Joshua}                        # VCJoshua.int    ; Vault City Courtyard Joshua, Slave
{1072}{}{Valerie}                       # VCMainWk.int    ; Valerie, Vic's Daughter and Maintence Worker
{1073}{}{Tanítórendszer}               # VITeach.int     ; Vault City Teaching System
{1074}{}{Láda}                         # diCrate.int     ; Den Crate in Church
{1075}{}{Pisáló srác}                    # VCUrine.int     ; Peeing Guy in Vault City Council Area
{1076}{}{Curtis}                        # VCCurtis.int    ; Curtis, Amanda and Joshua's Son
{1077}{}{Marc}                          # FCMarc.int      ; Marc, Punk in San Fran
{1078}{}{Számítógép}                      # FSElComp.int    ; Hubologists computer
{1079}{}{BHK-9}                         # FCOz9.int       ; Hubologist main dude
{1080}{}{Õr}                         # FCElGrd.int     ; Hubologist's guards
{1081}{}{Kõhalom}                 # VIRocks.int     ; Pile of Rocks w/ Hidden Wrench
{1082}{}{Ajtó}                          # VIVltDor.int    ; Vault City 2nd floor doors
{1083}{}{Õr}                         # dcRebGrd.int    ; Den Rebecca Guard
{1084}{}{Õr}                         # dcRebDor.int    ; Den Rebecca Door Guard
{1085}{}{Ajtó}                          # diRebDor.int    ; Den Rebecca Door
{1086}{}{Körözvény}                   # ZSWsign.int     ; Generic Wanted Sign
{1087}{}{Dr. Wong}                      # FCDrWong.int    ; Dr. Wong in San Fran area
{1088}{}{Asztal}                         # FIlaotbl.int    ; Lao Cho's stock tables in san Fran
{1089}{}{Ajtó}                          # WILv1Dor.int    ; Locked Door on Level 1 Entrance               # local_vars=8
{1090}{}{Punk}                          # FCFemPnk.int    ; San Fran Female punk
{1091}{}{Punk}                          # FCMalPnk.int    ; San Fran Male Punk
{1092}{}{Ryan}                          # FCRyan.int      ; San Fran Punk Ryan
{1093}{}{Doboz}                           # HIBh1Box.int    ; Broken Hills Temp Inventory Box
{1094}{}{}                              # FCJuavki.int    ; Juan and Vikkin in San Fran Elron Camp
{1095}{}{Csatornanyílás}                       # HIManHol.int    ; Manhole to Basement in Liz's Store
{1096}{}{Map Script}                    # SFElronb.int    ; Elron Base map Script
{1097}{}{Létra}                        # HILadder.int    ; Ladder up to Liz's Store
{1098}{}{Bokszzsák}                  # WIPnchBg.int    ; Punching Bag in the Sierra Depot
{1099}{}{Ajtó}                          # WIBayDor.int    ; Sierra Base Repair Bay Door
{1100}{}{Riasztó}                         # GSAlarm.int     ; Gecko Reactor alarm
{1101}{}{Padlólemez}                   # WIPlTrp2.int    ; Plasma Floor Trap Level 2 of Seirra
{1102}{}{Padlólemez}                   # WIPlTrp3.int    ; Plasma Floor Trap Level 2 of Seirra
{1103}{}{Padlólemez}                   # WIPlTrp4.int    ; Plasma Floor Trap Level 2 of Seirra
{1104}{}{Padlólemez}                   # WIPlTrp5.int    ; Plasma Floor Trap Level 2 of Seirra
{1105}{}{Padlólemez}                   # WIPlTrp6.int    ; Plasma Floor Trap Level 2 of Seirra
{1106}{}{Padlólemez}                   # WIPlTrp7.int    ; Plasma Floor Trap Level 2 of Seirra
{1107}{}{Padlólemez}                   # WIPlTrp8.int    ; Plasma Floor Trap Level 2 of Seirra
{1108}{}{Padlólemez}                   # WIPlTrp9.int    ; Plasma Floor Trap Level 2 of Seirra
{1109}{}{Padlólemez}                   # WIPlTrpA.int    ; Plasma Floor Trap Level 2 of Seirra
{1110}{}{Padlólemez}                   # WIPlTrpB.int    ; Plasma Floor Trap Level 2 of Seirra
{1111}{}{Padlólemez}                   # WIPlTrpC.int    ; Plasma Floor Trap Level 2 of Seirra
{1112}{}{Padlólemez}                   # WIPlTrpD.int    ; Plasma Floor Trap Level 2 of Seirra
{1113}{}{Padlólemez}                   # WIPlTrpE.int    ; Plasma Floor Trap Level 2 of Seirra
{1114}{}{Padlólemez}                   # WIPlTrpF.int    ; Plasma Floor Trap Level 2 of Seirra
{1115}{}{Emitter}                       # WSEmit4a.int    ; Emitter, Level 4 in Sierra Base
{1116}{}{Emitter}                       # WSEmit4b.int    ; Emitter, Level 4 in Sierra Base
{1117}{}{Emitter}                       # WSEmit4c.int    ; Emitter, Level 4 in Sierra Base
{1118}{}{Erõtér}                   # WSFeld4a.int    ; Force Field, Level 4 in Sierra Base
{1119}{}{Erõtér}                   # WSFeld4b.int    ; Force Field, Level 4 in Sierra Base
{1120}{}{Erõtér}                   # WSFeld4c.int    ; Force Field, Level 4 in Sierra Base
{1121}{}{Hubologista}                    # FCElrInd.int    ; Elron Indoctrinee
{1122}{}{Számítógép}                      # FStnkCmp.int    ; Posiden Tanker Computer
{1123}{}{Bunkerajtó}                   # WIBnkDor.int    ; Bunker Door for the Sierra Depot
{1124}{}{Kapu}                          # miGate.int      ; Modoc Gate
{1125}{}{Doboz}                           # WITrpBx1.int    ; Sierra Base Trapped Box
{1126}{}{Az egyik Morton fivér}                # RCMorBrs.int    ; Morton Brothers, Inc.
{1127}{}{Emitter}                       # FSEmt1.int      ; Force Field emitter 1 in San Fran
{1128}{}{Emitter}                       # FSEmt2.int      ; Force Field emitter 2 in San Fran
{1129}{}{Emitter}                       # FSEmt3.int      ; Force Field emitter 3 in San Fran
{1130}{}{Map Script}                    # Cave6.int       ; Fake Vault 13 Cave map
{1131}{}{Chet}                          # VCChet.int      ; Illicit Allocations Officer Chet
{1132}{}{Map Script}                    # NewRVB.int      ; New Reno Helicopter Script Map
{1133}{}{Gépmadár}                     # nsVertib.int    ; New Reno Helicopter Script Vertibird
{1134}{}{Salvatore õre}               # ncHSSal1.int    ; New Reno Helicopter Script Salvatore 1
{1135}{}{Salvatore õre}               # ncHSSal2.int    ; New Reno Helicopter Script Salvatroe 2
{1136}{}{Katona}                      # ncHSPow1.int    ; New Reno Helicopter Script Power Armor 1
{1137}{}{Katona}                      # ncHSPow2.int    ; New Reno Helicopter Script Power Armor 2
{1138}{}{Láda}                         # niHSCrat.int    ; New Reno Helicopter Script Crate
{1139}{}{Mr. Handy}                     # ncHSHand.int    ; New Reno Helicopter Script Handy
{1140}{}{Salvatore õre}               # ncHSGSal.int    ; New Reno Helicopter Script Salvatore Guard
{1141}{}{Spacial Script}                # ntHSGrd.int     ; New Reno Helicopter Script Guarding Spacial
{1142}{}{Ajtó}                          # niEldDor.int    ; New Reno Elderidge Door
{1143}{}{Ajtó}                          # niSalDor.int    ; New Reno Salvatore Door
{1144}{}{Ajtó}                          # niMyrDor.int    ; New Reno Myron Door
{1145}{}{}                              # FcMonst.int     ; Monster in the PMS Tanker
{1146}{}{Map Script}                    # SFTanker.int    ; San Fran Tanker map
{1147}{}{Rabszolga}                         # VCSlav2.int     ; Vault City Prisoner Slaves
{1148}{}{Menedékvárosi polgár}                 # VCBarCit.int    ; Vault City Bar Patron
{1149}{}{Ajtó}                          # niBasDor.int    ; New Reno Locking Doors
{1150}{}{Bokszoló}                         # ncFightr.int    ; New Reno Boxer Actually Fighting
{1151}{}{Bunker Ajtó}                    # RIVltDor.int    ; Locked Vault Door in Redding
{1152}{}{Xarn}                          # CcXarn.int      ; Xarn in Navarro
{1153}{}{Raul}                          # CcRaul.int      ; Raul in Navarro
{1154}{}{Quincy}                        # CcQuincy.int    ; Quincy in Navarro
{1155}{}{Raktáros}                 # CcQmstr.int     ; Quartermaster in Navarro
{1156}{}{Õr}                         # CcMedGrd.int    ; Med Lab Guard in Navarro
{1157}{}{Kibernetikus kutya}                # CcK9.int        ; K9 in Navarro
{1158}{}{Doktor}                        # CcDoctor.int    ; Dr Shreber in Navarro
{1159}{}{Technikus}                    # CcATech.int     ; Air Tech in Navarro
{1160}{}{Technikus}                    # CcACon.int      ; Air Control in Navarro
{1161}{}{Õr}                         # CcDrGrd.int     ; Door Guard in Navarro
{1162}{}{Õr}                         # Ccggbak.int     ; Gate Guard Backup in Navarro
{1163}{}{Õr}                         # CcGrdca.int     ; Guard (combat armor) in Navarro
{1164}{}{Õr}                         # CcGrdpa.int     ; Guard (power armor) in Navarro
{1165}{}{Technikus}                    # CcTech1.int     ; Com Tech1 in Navarro
{1166}{}{Technikus}                    # CcTech2.int     ; Com Tech2 in Navarro
{1167}{}{Technikus}                    # CcComp1.int     ; Computer Tech1 in Navarro
{1168}{}{Technikus}                    # CcComp2.int     ; Computer Tech2 in Navarro
{1169}{}{Beomlott barlang}                       # HICaveIn.int    ; Broken Hills Caved-In mine
{1170}{}{Enklávé járõr}              # QCEPSqad.int    ; Enclave EP Squad (joins player in fighting
{1171}{}{Ajtó}                    # QIEndDor.int    ; Doors at the End Fight Area
{1172}{}{Map Script}                    # EncDet.int      ; Map Script for Enclave Detention Center
{1173}{}{Map Script}                    # EncDock.int     ; Map Script for Enclave Dock
{1174}{}{Map Script}                    # EncGd.int       ; Map Script for Enclave Guard Barracks
{1175}{}{Map Script}                    # EncPres.int     ; Map Script for Enclave Presidential Area
{1176}{}{Map Script}                    # EncRetr.int     ; Map Script for Enclave Reactor Area
{1177}{}{Map Script}                    # EncFite.int     ; Map Script for Enclave Fight Area
{1178}{}{Biztonsági robot}                # QCSecBot.int    ; Enclave Security Robot
{1179}{}{Adománygyûjtõ persely}                      # niTulBox.int    ; New Reno Poor Box
{1180}{}{Test}                          # hiDead.int      ; Dead body in Broken Hills Tunnels
{1181}{}{Doboz}                           # HiJacBox.int    ; Broken Hills Jacob inventory box
{1182}{}{Doboz}                           # HiDocBox.int    ; Broken Hills Doc Holliday Inventory box
{1183}{}{Doboz}                           # HiOutBox.int    ; Broken Hills Outfitter inventory box
{1184}{}{Karaván õr}                 # RCCvnGrd.int    ; Generic Caravan Guard
{1185}{}{Karaván vezetõ}                # RCCvnDrv.int    ; Generic Caravan Driver
{1186}{}{Mûsorközlõ}                # ncAnounc.int    ; New Reno Boxing Anouncer
{1187}{}{Ringlány}                     # ncRngGrl.int    ; New Reno Ring Grrrl
{1188}{}{Bokszoló}                         # ncPrzFtr.int    ; New Reno Prize Fighter
{1189}{}{Ajtó}                          # VIVltDr2.int    ; Vault Doors in Vault 8
{1190}{}{Csaló karakter}               # ncCheat.int     ; New Reno Cheat Character
{1191}{}{Hololemez}                      # WIGNNDsk.int    ; Sierra Base GNN Transscript
{1192}{}{Hololemez}                      # WIMisDsk.int    ; Sierra Base Mission Statement Disk
{1193}{}{Hololemez}                      # FIElrDsk.int    ; Hubologist Holodisk
{1194}{}{Jegyzet}                          # HINote.int      ; Script for Francis/Zaius Note
{1195}{}{Dogmeat}                       # ECDogMet.int    ; Dog Meat from Special random encounter
{1196}{}{Cat's Paw magazin 5-ös példánya}         # niCatPw5.int    ; New Reno Cat's Paw magazine 5
{1197}{}{Fosztogatók térképe}                   # niRaiMap.int    ; New Reno Raiders Map in Bishop's Safe
{1198}{}{Pária kutya}                    # ECPariah.int    ; Pariah Dog in Low Luck encounter
{1199}{}{Riasztó}                        # QIKlaxon.int    ; Klaxon Lights for Enclave when under alert
{1200}{}{Bánya}                          # IIMine.int      ; Mines in Raiders Cave
{1201}{}{Üreg}                           # IIPit.int       ; Pits in the Raiders Cave
{1202}{}{Tanker fegyverkereskedõ}               # FCTnkGmr.int    ; Tanker Gun Merchant San Fran
{1203}{}{Tanker csapos}              # FCTnkBar.int    ; Tanker Bar Tender
{1204}{}{Tanker kereskedõ}               # FCTnkMer.int    ; Tanker Merchant
{1205}{}{}                              # FITGunTb.int    ; Tanker Gun Mer's table
{1206}{}{}                              # FITMerTb.int    ; Tanker Merchant's Table
{1207}{}{Emitter}                       # FSPemtr1.int    ; Palace Emitter 1
{1208}{}{Emitter}                       # FSPemtr2.int    ; Palace Emitter 2
{1209}{}{Emitter}                       # FSPemtr3.int    ; Palace Emitter 3
{1210}{}{Emitter}                       # FSEmpEmt.int    ; Emporor Computer's Force Field
{1211}{}{Fallout 2 leírás}            # niF2Hint.int    ; New Reno Fallout 2 Hintbook
{1212}{}{}                              # csTouch.int     ; Script to signal if dude touches container objects (in Navarro)
{1213}{}{}                              # csArea.int      ; Script to signal if dude enters an area (in Navarro)
{1214}{}{Õr}                         # RCAscGrd.int    ; Generic Guard for Ascorti's Bar
{1215}{}{Földmérõ}                      # ECLdPros.int    ; Random Encounter Lead Prospector
{1216}{}{Szeszcsempész}                   # ECLdBoot.int    ; Random Encounter Lead Bootlegger
{1217}{}{}                              # csOpen.int      ; Script to signal if dude uses door w/o permision (in Navarro)
{1218}{}{Dan}                           # hcDan.int       ; Dan, Spouse of murdered conspirator.
{1219}{}{kezdõ komikus}               # ncComedi.int    ; New Reno Comedian
{1220}{}{A Szemetes énekese}            # ncBand.int      ; New Reno Trashcan Band
{1221}{}{Map Script}                    # ARDead.int      ; Destroyed Arroyo Bridge map script
{1222}{}{}                              # csGate.int      ; Script to signal if dude uses gate w/o permision (in Navarro)
{1223}{}{Sírhely}                         # niWilGrv.int    ; New Reno Coffin Willie's Grave
{1224}{}{Koporsós Willie}                 # ncWillie.int    ; New Reno Coffin Willie
{1225}{}{FBK terminál}		        # FSFobTer.int    ; Fob Terminal
{1226}{}{FBK ajtó}                     # FSFobDor.int    ; Fob Door
{1227}{}{Számítógép}                      # ccNComp.int     ; Navarro Computer
{1228}{}{Kohl}                          # vcKohl.int      ; Vault City Info Officer Kohl
{1229}{}{Gyerek}                         # ECChild.int     ; Random Encounter Children
{1230}{}{Szakács}                          # ccCook.int      ; Navarro Cook
{1231}{}{Torony}                        # ccTurret.int    ; Navarro Turret
{1232}{}{Brian}                         # hcBrian.int     ; Brian, the Power Technician
{1233}{}{Generátor}                     # hiPower.int     ; Power Generator for Broken Hills
{1234}{}{Konzol}                       # hiConsole.int   ; Power Station Console in Broken Hills
{1235}{}{Óriáshangya}                     # hcAnt1.int      ; Standard Broken Hills Ant
{1236}{}{Óriáshangya}                     # hcAnt2.int      ; Broken Hills Ant - Missing Person Quest
{1237}{}{Ajtó}                          # csXDoor.int     ; Another lousy door script -signals xarn to leave
{1238}{}{}                              # htSecret.int    ; Spatial for secret area of Broken Hills Mine
{1239}{}{Doboz}                           # niEthBox.int    ; New Reno Ethyl Wright Shop Box
{1240}{}{Eric}                          # hcEric.int      ; Eric the Smelly Boy, Broken Hills
{1241}{}{}                              # htFlies.int     ; Spatial Flies script for Broken Hills
{1242}{}{Doboz}                           # viRanBox.int    ; Randal's Stock Box in Vault City
{1243}{}{Óriásskorpió}                # iiScorp.int     ; Raiders Scorpions 2X poison
{1244}{}{Jane}                          # RCJane.int      ; Redding Jackpot Jane
{1245}{}{}                              # VTAloMrk.int    ; Spatial Script for Allocation Computer VCity
{1246}{}{Map Script}                    # Cave7.int       ; Fake Vault 13 map
{1247}{}{Dermális PipBoy}                # niDermal.int    ; New Reno Dermal Pip Boy
{1248}{}{Eb}                         # ncEldDog.int    ; New Reno Eldridge Dogs
{1249}{}{Rattray}                       # RCRatray.int    ; Rattray, Doc Johnson's assistant
{1250}{}{Házastárs}                        # HCHusWif.int    ; Mutant Husband/Wife Broken Hills
{1251}{}{LoPan õre}                   # FCLoGrd.int     ; LoPan Guard in San Fran
{1252}{}{Map Script}                    # Navarro.int     ; Map script for Navarro
{1253}{}{Ajtó}                          # VIVltDr3.int    ; Vault Door in Vault 8 - Martin
{1254}{}{Kibernetikus kutya}                # CcFak9.int      ; Fake K-9 Scenery obj
{1255}{}{Luke}                          # FCNLuke.int     ; Luke in NCR
{1256}{}{Joshua}                        # FCDJosh.int     ; Joshua BOS in the Den
{1257}{}{Gate}                          # iiLockDr.int    ; Gates in Raiders area
{1258}{}{Matt}                          # FCFmatt.int     ; Matt in San Fran BOS
{1259}{}{Ajtó}                          # FSBroDor.int    ; Brotherhood Door
{1260}{}{Õr}                         # hcGrd2.int      ; Bank Guard 2 in Broken Hills
{1261}{}{Ajtó}                          # QIGeckDr.int    ; Door Requiring the player to use the geck
{1262}{}{Számítógép}                      # FSFace.int      ; Ace Computer system in San Fran
{1263}{}{Terminál}                      # QITurTrm.int    ; Generic Enclave Turret Terminal
{1264}{}{Lövegtorony}                        # QCTurret.int    ; Enclave Turrets
{1265}{}{Chuck Stodgers}                # hcChuck.int     ; Chuck Stodgers, Broken Hills
{1266}{}{}                              # htChuck.int     ; Spatial Script for waking up Chuck
{1267}{}{Terminál}                      # viTerm.int      ; Vault City Vault Terminal
{1268}{}{Bandatag}                     # RCMotGng.int    ; Frog Morton's gang
{1269}{}{Csaló}                       # ccCheat.int     ; Cheat character in Navarro
{1270}{}{}                              # FSTnkrdr.int    ; Tanker Doors in San Fran
{1271}{}{Paraszt}                       # OCPeaon.int     ; NCR peaons
{1272}{}{A levendula virága}           # diRebBok.int    ; Den Becky's Book
{1273}{}{Radskorpió}                   # hcScorp.int     ; Broken Hills Scorpion
{1274}{}{Professszor}                     # hcProf.int      ; Broken Hills Professor
{1275}{}{Doboz}                           # hiPrfBx1.int    ; Professor's Box in Broken Hills
{1276}{}{Doboz}                           # hiPrfBx2.int    ; Professor's Box in Broken Hills
{1277}{}{Seymour}                       # hcSeymore.int   ; Seymour the talking Plant/Broken Hills
{1278}{}{John Sullivan}                 # hcSulvan.int    ; John Sullivan - Broken Hills
{1279}{}{Lumpy}                         # hcLumpy.int     ; Lumpy the car accident victim - Broken Hills
{1280}{}{}                              # BISpyHol.int    ; Spy Holodisk for NCR
{1281}{}{}                              # SIHisHol.int    ; NCR History Holodisk
{1282}{}{}                              # SIWesHol.int    ; Westin Holodisk
{1283}{}{Õr}                         # SCBGrd.int      ; Buster's Guard
{1284}{}{}                              # SIElnObj.int    ; Elise Notify Object
{1285}{}{}                              # SIGcaObj.int    ; NCR Guard Captain notify obj
{1286}{}{Typhon}                        # hcTyphon.int    ; Typhon, Son of Set - Broken Hills
{1287}{}{Testõr}                     # ECBdyGrd.int    ; BodyGuard in Vignette
{1288}{}{Map Script}                    # GamMovie.int    ; Game Movie map
{1289}{}{Öltözõszekrény}                        # ziÖltözõszekrény.int    ; Generic Öltözõszekrény Script
{1290}{}{Kút}                          # hiWell.int      ; Broken Hills Well
{1291}{}{Micky}                         # hcMicky.int     ; Mickey the Dwarf - Broken Hills
{1292}{}{Lövegtorony}                        # WCTurret.int    ; Turret for Sierra Depot
{1293}{}{Öreg ghoul}                     # hcOldGhl.int    ; Ghouls in Old-Folks Home - Broken Hills
{1294}{}{Bérenc}                      # hcHench.int     ; Broken Hills Outfitter Henchmen
{1295}{}{Elmo}                          # hcElmo.int      ; Elmo - Broken Hills
{1296}{}{WC}                        # niToilet.int    ; Toilet - Contains Grenades - New Reno
{1297}{}{Kereszt}                         # niCross.int     ; Cross - Golgotha - Buried Cash
{1298}{}{Eke}                          # viPlow1.int     ; Plow - Vault City
{1299}{}{Eke}                          # viPlow2.int     ; Plow - Vault City
{1300}{}{Skorpió}                      # kcScorpa.int    ; Attacking scorpion in klamath
{1301}{}{Generátor}                     # kcGnratr.int    ; Generator player repairs in toxic caves
{1302}{}{Ajtó}                          # kcLvatr.int     ; Elevator door in toxic caves
{1303}{}{Ajtó}                          # SIVDor.int      ; Vortis Slave Door
{1304}{}{Orvosi PipBoy}               # niMedica.int    ; New Reno "Doctor Skill" Upgrade
{1305}{}{Öltözõszekrény}                        # niPrstLk.int    ; New Reno Prostitute"Öltözõszekrény"
{1306}{}{Öltözõszekrény}                        # niBigJLk.int    ; New Reno Big Jesus "Öltözõszekrény"
{1307}{}{Öltözõszekrény}                        # niMor1Lk.int    ; New Reno Mordino No Lock/No Ignore "Öltözõszekrény"
{1308}{}{Öltözõszekrény}                        # niBoxrLk.int    ; New Reno Boxer "Öltözõszekrény"
{1309}{}{Öltözõszekrény}                        # niBis1Lk.int    ; New Reno Bishop Family OK "Öltözõszekrény"
{1310}{}{Öltözõszekrény}                        # niPornLk.int    ; New Reno Porn Actress "Öltözõszekrény"
{1311}{}{Öltözõszekrény}                        # niBtchLk.int    ; New Reno Bitch "Öltözõszekrény"
{1312}{}{Öltözõszekrény}                        # niBis2Lk.int    ; New Reno Bishop Family NO IGNORE "Öltözõszekrény"
{1313}{}{Öltözõszekrény}                        # niEldrLk.int    ; New Reno Eldridge "Öltözõszekrény"
{1314}{}{Öltözõszekrény}                        # niWrT1Lk.int    ; New Reno Wright Teen NO IGNORE "Öltözõszekrény"
{1315}{}{Öltözõszekrény}                        # niOWriLk.int    ; New Reno Orville Wright "Öltözõszekrény"
{1316}{}{Öltözõszekrény}                        # niWrT2Lk.int    ; New Reno Wright Teen FAMILY IGNORE "Öltözõszekrény"
{1317}{}{Öltözõszekrény}                        # niMor1Lk.int    ; New Reno Mordino FAMILY IGNORE "Öltözõszekrény"
{1318}{}{Öltözõszekrény}                        # niMyGdLk.int    ; New Reno Myron Guard "Öltözõszekrény"
{1319}{}{Öltözõszekrény}                        # niMor2Lk.int    ; New Reno Mordino NO IGNORE "Öltözõszekrény"
{1320}{}{Öltözõszekrény}                        # niMyrnLk.int    ; New Reno Myron "Öltözõszekrény"
{1321}{}{Öltözõszekrény}                        # niChp1Lk.int    ; New Reno Chop Shop Boy LOCKED "Öltözõszekrény"
{1322}{}{Öltözõszekrény}                        # niChp2Lk.int    ; New Reno Chop Shop Boy NO-LOCK "Öltözõszekrény"
{1323}{}{Öltözõszekrény}                        # niTryLk.int     ; New Reno Tray "Öltözõszekrény"
{1324}{}{Öltözõszekrény}                        # niMor3Lk.int    ; New Reno Mordino locker, no warning
{1325}{}{Map Script}                    # rndtoxic.int    ; Random Toxic Map
{1326}{}{Nem látsz}              # ecirrad.int     ; critter that irradates
{1327}{}{Bádogember}                  # ecTinWod.int    ; Tin Woodsman
{1328}{}{Map Script}                    # rndTinWd.int    ; Tin Woodsman Map Script
{1329}{}{Az örökkévalóség õrzõje}               # ecGrdFrv.int    ; Guardian of Forever
{1330}{}{}                              # rndForvr.int    ; Guardian of Forever Rnd Enct Map Script
{1331}{}{Terminál}                      # ecGrdTrm.int    ; Guardian of Forever Water Chip Terminal
{1332}{}{Öltözõszekrény}                        # niEld2Lk.int    ; New Reno Eldridge "Öltözõszekrény" HARD LOCK
{1333}{}{}                              # SiRagobj.int    ; Uhh box that Rondo cares
{1334}{}{Map Script}                    # SFCHINA2.int    ; China 2 map
{1335}{}{Védelmi robot}                  # WCDedBot.int    ; Fighting Bot that does nothing
{1336}{}{Védelmi robot}                  # KCWupass.int    ; Klamath Guard Robot under Toxic Caves
{1337}{}{Öltözõszekrény}                        # viHarWch.int    ; VCty - Harry Watch Script
{1338}{}{Öltözõszekrény}                        # viEdWch.int     ; VCty - Ed Watch Script
{1339}{}{Öltözõszekrény}                        # viAndWch.int    ; VCty - Doc Andrew Watch Script
{1340}{}{Öltözõszekrény}                        # viLynWch.int    ; VCty - Lynette Watch Script
{1341}{}{Öltözõszekrény}                        # viGrgWch.int    ; VCty - Gregory Watch Script
{1342}{}{Öltözõszekrény}                        # viCGWch1.int    ; VCty - Prison Door Watch Script
{1343}{}{Öltözõszekrény}                        # viCGWch2.int    ; VCty - Greeting Watch Script
{1344}{}{Öltözõszekrény}                        # viRNWch1.int    ; VCty - Randal1 Watch Script
{1345}{}{Öltözõszekrény}                        # viRNWch2.int    ; VCty - Randal2 Watch Script
{1346}{}{Öltözõszekrény}                        # viStkWch.int    ; VCty - Stark Watch Script
{1347}{}{Öltözõszekrény}                        # viBarWch.int    ; VCty - Barkus Watch Script
{1348}{}{Öltözõszekrény}                        # viVLWch1.int    ; VCty - Valerie1 Watch Script
{1349}{}{Öltözõszekrény}                        # viVLWch2.int    ; VCty - Valerie2 Watch Script
{1350}{}{Öltözõszekrény}                        # viWalWch.int    ; VCty - Wallace Watch Script
{1351}{}{Öltözõszekrény}                        # viSkvWch.int    ; VCty - Greeting Watch Script
{1352}{}{Öltözõszekrény}                        # viInWch1.int    ; VCty - InGrd Watch Script
{1353}{}{Öltözõszekrény}                        # viInWch2.int    ; VCty - InGrd Watch Script
{1354}{}{Öltözõszekrény}                        # viInWch3.int    ; VCty - InGrd Watch Script
{1355}{}{Öltözõszekrény}                        # viFamWch.int    ; VCty - GenFam Watch Script
{1356}{}{Öltözõszekrény}                        # viCsWch1.int    ; VCty - Cassidy Watch Script
{1357}{}{Dokklakó}                 # FCDocSqa.int    ; San Fran - Doc Squatter
{1358}{}{Dokklakó kölyök}                      # FCDocKid.int    ; San Fran - Doc Kids
{1359}{}{Map Script}                    # RndWhale.int    ; Random Whale Script
{1360}{}{Percy Crump}                   # gcPercy.int     ; Percy Crump, Gecko Merchant
{1361}{}{Doboz}                           # giPerBox.int    ; Percy's Stock Box
{1362}{}{Doboz}                           # giJnkBox.int    ; Gecko Junkyard Temp Inventory Box
{1363}{}{Ajtó}                          # niWriDor.int    ; New Reno Wright Room Door
{1364}{}{A Nagy Ananias}             # dcAnan.int      ; The Great Ananias, Mummy Master
{1365}{}{Map Script}                    # RndUVilg.int    ; Unwashed Villager map
{1366}{}{Mosdatlan Falusi}             # ECWash.int      ; Unwashed Villagers... Ug You figure out where they go.
{1367}{}{Házaló}                       # ECSpammr.int    ; Spammer in Unwashed Encounter
{1368}{}{Térkép}                           # eiSanMap.int    ; Military Base San Francisco Map
{1369}{}{Map Script}                    # RndShutl.int    ; Random Shuttle Map
{1370}{}{Map Script}                    # rndParih.int    ; Random Pariah Map Script
{1371}{}{Map Script}                    # rndBHead.int    ; Random Big Head map
{1372}{}{Map Script}                    # rndcafe.int     ; Random Cafe Map
{1373}{}{Nuka-Cola automata}             # ZINuke.int      ; Nuka-Cola Machine
{1374}{}{Dokk}                          # sfdock.int      ; map script for San Fran Dock
{1375}{}{Ajtó}                          # ciCrisDr.int    ; Chris's Door
{1376}{}{Akna}                     # rtlndmin.int    ; Redding Land Mines
{1377}{}{Akna}                     # wtlndmin.int    ; Sierra Depot Land Mines
{1378}{}{Az exed}                       # ncExSpou.int    ; New Reno Ex-Spouse script
{1379}{}{Mel}                           # ECMel.int       ; Mel that Dogmeat Creates.
{1380}{}{Szellõzõ}                          # ciVent.int      ; Vent into Navarro
{1381}{}{Kevin}                         # ccKevin.int     ; Kevin in Navarro
{1382}{}{Riasztó}                         # csAlarm.int     ; Navarro base on alert lights
{1383}{}{Öltözõszekrény}                        # ciQunWch.int    ; Quincy Öltözõszekrény watch script
{1384}{}{Öltözõszekrény}                        # ciRulWch.int    ; Raul Öltözõszekrény Watch Script
{1385}{}{Öltözõszekrény}                        # ciCmdWch.int    ; Commanded Öltözõszekrény Watch Script
{1386}{}{}                              # SSSign.int      ; NCR Statue
{1387}{}{}                              # ctFob.int       ; Fob EXP Spatial Script
{1388}{}{}                              # ctPlans.int     ; Vertibird EXP Spatial Script
{1389}{}{}                              # ctK9Part.int    ; K9 Part EXP Spatial Script
{1390}{}{}                              # csArea2.int     ; Script to signal if dude enters an area
{1391}{}{}                              # csOpen2.int      ; Script to signal if dude uses door w/o permision (in Navarro)
{1392}{}{}                              # ctSound.int     ; Soundproof Room Spatial Script
{1393}{}{}                              # csOpen3.int     ; Script to signal if dude uses door w/o permis
{1394}{}{Szeszcsempész}                    # ECTlkMon.int    ; Talking Moonshiners
{1395}{}{}                              # ziWeakLk.int    ; Generic Weak Lock Watch Script
{1396}{}{}                              # ziMedmLk.int    ; Generic Medium Lock Watch Script
{1397}{}{Carny kölyök}                     # dcCarnKd.int    ; Carny Kid - The Den
{1398}{}{}                              # ciDocWch.int    ; Raul Öltözõszekrény Watch Script
{1399}{}{}                              # ziHardLk.int    ; Generic Hard Lock Watch Script
{1400}{}{Bánya}                          # CIMine.int      ; Mines in Raiders Cave
{1401}{}{Öltözõszekrény}                        # niBisHLk.int    ; New Reno Bishop Hard Öltözõszekrény
{1402}{}{Ajtó}                          # niBisHDr.int    ; New Reno Bishop Hard Locked Door
{1403}{}{}                              # ntRicRom.int    ; New Reno Richard Wright Room Spacial