#
#   Messages from skill.c
#
#
#   SKILL NAMES
#
{100}{}{Kézi lõfegyverek}
{101}{}{Nehéz lõfegyverek}
{102}{}{Energiafegyverek}
{103}{}{Ökölharc}
{104}{}{Közelharc}
{105}{}{Hajítás}
{106}{}{Elsõsegély}
{107}{}{Orvos}
{108}{}{Lopózás}
{109}{}{Zárak}
{110}{}{Lopás}
{111}{}{Csapdák}
{112}{}{Tudományok}
{113}{}{Javítás}
{114}{}{Beszéd}
{115}{}{Üzletelés}
{116}{}{Szerencsejáték}
{117}{}{Túlélés}
#
#   SKILL DESCRIPTIONS
#
{200}{}{Kézi lõfegyverek használata, karbantartása és általános ismerete - pisztolyok, géppisztolyok és puskák.}
{201}{}{Nehéz lõfegyverek használata és karbantartása - gépágyúk, rakétavetõk, lángszórók, stb.}
{202}{}{Energia alapú fegyverek feltöltése és használata - minden, ami lézer- vagy plazma technológiával mûködik.}
{203}{}{Harcmûvészetek, boksz, és egyéb pusztakezes harctudományok. Harc kézzel és lábbal.}
{204}{}{A nem távolsági fegyverek használata - kések, kalapácsok, lándzsák, bunkók, stb.}
{205}{}{Hajítófegyverek használatának képzettsége - dobókések, lándzsák és gránátok.}
{206}{}{A gyógyítás legalapvetõbb ismeretei. Könnyebb sebek, horzsolások és egyéb kisebb betegségek ellátása. Több ÉP-t gyógyíthat, mint az ugyanannyi ideig tartó pihenés.}
{207}{}{Súlyos sérülések, sérült végtagok gyógyítása. Enélkül sokkal több idõ kell a sérült végtagok gyógyulásához.}
{208}{}{A csendes mozgás és az észrevétlenség képessége. Ha sikeres, sokkal nehezebben vesznek észre. Nem tudsz egyszerre futni és lopakodni.}
{209}{}{Zárak kinyitása a megfelelõ kulcs híján. Tolvajkulcs vagy elektromos zárnyitó használata jelentõsen növeli ezt a képzettséget.}
{210}{}{Mások dolgainak eltulajdonítása. Tárgyak ellopása emberektõl, vagy különbözõ helyekrõl.}
{211}{}{Csapdák megtalálásának és hatástalanításának, valamint robbanóanya-gok használatának képzettsége.}
{212}{}{Tudományok, ismeretek gyûjtõképzettsége, mint például a számítás-technika, biológia, fizika és geológia.}
{213}{}{A Tudományok képzettség gyakorlati alkalmazása lerobbant, hibás berendezések, gépek vagy elektronikus eszközök javítására.}
{214}{}{A kommunikáció célratörõ és hatásos módja. Mások meggyõzése arról, hogy amit te mondasz az úgy is van. A leleplezõdés nélküli hazudozás képzettsége.}
{215}{}{Kereskedelem és minden hozzá kapcsolódó feladat. A megfelelõ képzettség, hogy drágán adj el, és olcsón vásárolj.}
{216}{}{A fogadás mikéntjének ismerete és gyakorlati alkalmazása. Kártya, kocka és egyéb hazárdjátékok ûzése.}
{217}{}{A pusztákon való túlélés gyakorlati alkalmazása. Magában foglalja az állatok és növények ismeretét.}
#
#   SKILL ATTRIBUTES
#
#   Updated: 6/5/97 KSW
#   Updated to New Skill System: 9/16/98 rwh2
#
{300}{}{+ (4 x ÜG)}
{301}{}{+ (2 x ÜG)}
{302}{}{+ (2 x ÜG)}
{303}{}{+ (2 x (ÜG + ER))}
{304}{}{+ (2 x (ÜG + ER))}
{305}{}{+ (4 x ÜG)}
{306}{}{+ (2 x (ÉR + IN))}
{307}{}{+ (ÉR + IN)}
{308}{}{+ (3 x ÜG)}
{309}{}{+ (ÉR + ÜG)}
{310}{}{+ (3 x ÜG)}
{311}{}{+ (ÉR + ÜG)}
{312}{}{+ (4 x IN)}
{313}{}{+ (3 x IN)}
{314}{}{+ (5 x KA)}
{315}{}{+ (4 x KA)}
{316}{}{+ (5 x SZ)}
{317}{}{+ (2 x (KI + IN))}
#
#   Skill Use Text
#
{500}{}{%d életerõt gyógyítottál.}
{501}{}{Már makk egészséges vagy.}
{502}{}{%s makk egészségesnek látszik.}
{503}{}{Nem sikerült gyógyítanod.}
{505}{}{A képzettség használatáért %d TP-t kapsz.}
{510}{}{\nskill_use: invalid skill used.}
{512}{}{A halottakat képtelenség meggyógyítani.}
{513}{}{Hagyd a halottat békében nyugodni!}
{514}{}{Meghalt, nincs mit tenni.}
{520}{}{Meggyógyítottad a %s.}
{521}{}{Meggyógyítottad a %s.}
{525}{}{Nem sikerült meggyógyítani a %s.}
{526}{}{Nem sikerült meggyógyítani a %s.}
{530}{}{sérült szemet}    # Lines 530-534 are the endings to lines 525 & 526.
{531}{}{sérült bal karodat}
{532}{}{sérült jobb karodat}
{533}{}{sérült jobb lábadat}
{534}{}{sérült bal lábadat}
{550}{}{Nem sikerült feltörnöd a zárat.}
{551}{}{Nem találtál csapdát.}
{552}{}{Nem lettél okosabb.}
{553}{}{Nem tudod megjavítani.}
{570}{}{Lebuktál az áhított %s ellopása közben.}
{571}{}{Sikerült ellopnod: %s.}
{572}{}{Miközben a tiltott %s becsempészésén ügyködtél, sikeresen lebuktál.}
{573}{}{Sikerült becsempészned: %s.}
{590}{}{Kimerítetted a képzettséged, próbáld meg késõbb!}
{591}{}{Túl fáradt vagy.}
{592}{}{Belehalnál az erõfeszítésbe.}

# Fallout 2!
{600}{}{Nem vagy elég képzett ilyen sérülések gyógyítására.}
{601}{}{Ezt a robotot már nem lehet megjavítani.}



#
# Fallout 2: Party Member skill use generic responses
#

#   I'll try
{1000}{}{Hadd segítsek!}
{1001}{}{Ezt meg tudom csinálni!}
{1002}{}{Megvan!}
{1003}{}{Örülök, hogy segíthettem.}
{1004}{}{Oké.}
{1005}{}{Megpróbálom.}

#   Player wants to do it
{1100}{}{Ha van valami gond, csak szólj!}
{1101}{}{Megvan?}
{1102}{}{Ahogy akarod...}
{1103}{}{Gyerünk, próbáld meg!}
{1104}{}{Próbáld meg te!}