{200}{}{Grottingång}
{201}{}{Entrance}
{202}{}{Bostadsutrymme}
{203}{}{Kommandocentral}
{210}{}{Ökeningång}
{211}{}{Grottor/Ingång}
{212}{}{Bostadsutrymme}
{213}{}{Kommandocentral}
{220}{}{Entrance}
{221}{}{Garden}
{222}{}{Brahmin Pen}
{230}{}{Entrance}
{231}{}{Crash House}
{232}{}{Kasino}
{240}{}{Bas}
{250}{}{Hotell}
{251}{}{Hall}
{252}{}{Vattenskjul}
{260}{}{Entrance}
{261}{}{Downtown}
{262}{}{Höjder}
{263}{}{Gamla stan}
{264}{}{Köpmän}
{265}{}{Cave}
{270}{}{Entrance}
{271}{}{Level 1}
{272}{}{Level 2}
{273}{}{Level 3}
{274}{}{Level 4}
{280}{}{Entrance}
{281}{}{Fästning Nivå 1}
{282}{}{Fästning Nivå 2}
{283}{}{Vats Level 1}
{284}{}{Vats Level 2}
{290}{}{Krater}
{291}{}{Level 1}
{300}{}{Adytum}
{301}{}{Downtown}
{302}{}{Bibliotek}
{303}{}{Fästning}
{304}{}{Warehouse}
{310}{}{Entrance}
{311}{}{Interiör}
{500}{}{You gained 10,000 experience points!}
{501}{}{Ruins}
{1000}{}{Desert}
{1001}{}{Mountains}
{1002}{}{City}
{1003}{}{Coast}
{1004}{}{Okänt}
