#
# Messages used in gdialog.c for custom NPC combat control.
#
{0}{}{Raffica}
{1}{}{Fuga}
{2}{}{Arma pref.}
{3}{}{Distanza}
{4}{}{Attacca}
{5}{}{Usa droghe}

{10}{}{Fatto}
{11}{}{Canc.}

#
# Burst options.
#
{99}{}{Non Disponibile.}
{100}{}{Sempre!}
{101}{}{A volte, e non preoccuparti di non colpirmi}
{102}{}{Sii sicuro di non colpirmi}
{103}{}{Stai attento a non colpirmi}
{104}{}{Sii assolutamente certo di non colpirmi}

#
# Run away options.
#
{200}{}{Miserabile codardo}
{201}{}{Ti sei graffiato un dito}
{202}{}{Sanguini un po'}
{203}{}{Non ti senti bene}
{204}{}{Ti serve un laccio emostatico}
{205}{}{Mai!}

#
# Weapon pref options.
#
{300}{}{Nessuna}
{301}{}{Mischia}
{302}{}{Mischia e poi a distanza}
{303}{}{A distanza e poi Mischia}
{304}{}{A distanza}
{305}{}{Disarmato}

#
# Distance options.
#
{400}{}{Stammi vicino}
{401}{}{Carica!}
{402}{}{Colpisci da lontano}
{403}{}{Da solo}
{404}{}{Stai dove sei}

#
# Attack who options.
#
{500}{}{Chiunque mi stia attaccando}
{501}{}{Il piu' forte}
{502}{}{Il piu' debole}
{503}{}{Chi vuoi}
{504}{}{Il piu' vicino}

#
# Chem use options.
#
{600}{}{Sono contrario all'uso di droghe}
{601}{}{Stimpack se ferito leggermente}
{602}{}{Stimpack se ferito gravemente}
{603}{}{Qualsiasi droga, ma non sempre}
{604}{}{Qualsiasi droga, quando vuoi}