#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used by EDITOR.C
#   kinpa
#   Translated by Ragfox
# (These MUST match "text message" enumeration on the top of EDITOR.C)
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
#
{100}{}{OK}
{101}{}{OPZIONI}
{102}{}{CANC.}
{103}{}{STAMPA}
{104}{}{ETA'}
{105}{}{SESSO}
{106}{}{NOME}
{107}{}{MASCHIO}
{108}{}{FEMMINA}
{109}{}{STRENNE}
{110}{}{KARMA}
{111}{}{MORTI}
{112}{}{PUNTI ABILITA'}
{113}{}{Livello:}
{114}{}{Esp:}
{115}{}{Pros. Liv.:}
{116}{}{ P. PERSON.}
{117}{}{ABILITA'}
{118}{}{Devi usare tutti i punti personaggio} # 1
{119}{}{prima di inziare il gioco!}           # 2
#
{120}{}{Punti personaggio}
{121}{}{Ammontare di punti personaggio gratuiti che possono essere aggiunti a una delle tue caratteristiche di base.}
{122}{}{Prossimo Livello}
{123}{}{L'ammontare di punti esperienza necessari per arrivare al prossimo livello.}
{124}{}{Strenne}
{125}{}{Karma}
{126}{}{Uccisioni}
{127}{}{Le Strenne aggiungono abilita' addizionali. Ogni tre livelli di esperienza, puoi scegliere una Strenna.}
{128}{}{Questi sono gli effetti delle scelte da te effettuate durante il gioco.}
{129}{}{Un contatore che tiene conto del tipo e del numero delle creature da te massacrate, o che sono state uccise in tua presenza.}
{130}{}{Punti Abilita'}
{131}{}{Usa i Punti Abilita' per aumentare il livello di una abilita'. A mano a mano che migliori in un'abilita', tuttavia, aumentarla costera' piu' punti. Diventare esperti in una abilita' puo' richiedere un sacco di tempo e fatica.}
#
{132}{}{Livello massimo.}          # 1
{133}{}{Non puoi aumentarlo.}         # 2
{134}{}{Livello minimo.}           # 1
{135}{}{Non puoi diminuirlo.}         # 2
{136}{}{Punti abilita' insufficienti.}
{137}{}{Base:}
{138}{}{"SCELTE"}
{139}{}{TRATTI OPZIONALI}
{140}{}{Hai gia' un massimo di}               # 1
{141}{}{tre "Scelte"!}                        # 2
{142}{}{Devi selezionare tutte le "Scelte"}   # 1
{143}{}{prima di cominciare il gioco!} # 2
{144}{}{"Scelte"}
{145}{}{Le "Scelte" sono abilita' nelle quali il tuo personaggio si specializza. Ogni abilita' "Scelta" prende un bonus +20% e aumenta al doppio della velocita'. Devi selezionare tre "Scelte".}
{146}{}{Tratti Opzionali}
{147}{}{I tratti opzionali descrivono piu' in dettaglio il tuo personaggio. Tutti i tratti hanno effetti positivi e effetti negativi. Puoi scegliere al massimo due tratti durante la fase di creazione del personaggio.}
{148}{}{Hai gia' un massimo di} # 1
{149}{}{due tratti opzionali!}  # 2
{150}{}{Abilita'}
{151}{}{L'insieme delle conoscenze acquisite. Le abilita' migliorano con l'esperienza o per effetti speciali durante il gioco. Maggiore il livello d'abilita', migliore la tua padronanza di quella abilita'.}
#
{152}{}{SCEGLI UNA STRENNA}
{153}{}{SCEGLI UN NUOVO TRATTO}
{154}{}{PERDI UN TRATTO}
{155}{}{SCEGLI UN NUOVA "SCELTA"}
{156}{}{TRATTI}
#
{157}{}{Tutte le caratteristiche devono essere}   # 1
{158}{}{comprese tra 1 e 10 prima di cominciare!} # 2
# Fallout 2:
{160}{}{Attento: non hai inserito un nome.} # 1
{161}{}{Utilizzi lo stesso il personaggio?} # 2

{175}{}{Pr. Lvl:}  # Short for Level:


#
# Abbreviated basic stat levels
#
{200}{}{Pessim} # Terrible
{201}{}{Scarso} # Bad
{202}{}{Medcre} # Poor
{203}{}{Discrt} # Fair
{204}{}{Medio}  # Average
{205}{}{Buono}  # Good
{206}{}{M.Buon} # Very Good
{207}{}{Ottimo} # Great
{208}{}{Ecclnt} # Excellent
{209}{}{Eroico} # Heroic

#
# Abbreviated Derived/Non Derived stat names
#
{300}{}{Punti Vita}
{301}{}{Punti Azione}
{302}{}{Classe Armat.}
{303}{}{Danno C-a-C}
{304}{}{Danno Mischia}
{305}{}{Res. al Danno }
{306}{}{Res. al Veleno}
{307}{}{Res. a Radiaz.}
{308}{}{Sequenza}
{309}{}{Tasso di guar.}
{310}{}{% Col. Critici}
{311}{}{Peso Portato}
{312}{}{Avvelenato}
{313}{}{Irradiato}
{314}{}{Danno agli Occhi}
{315}{}{Braccio dx ferito}
{316}{}{Braccio sx ferito}
{317}{}{Gamba dx ferita}
{318}{}{Gamba sx ferita}

#
# Damage info texts
#
# Poisoned
{400}{}{Il tuo personaggio e' stato avvelenato. Il veleno agira' per un certo periodo di tempo, finche' non viene curato o eliminato dal tuo metabolismo.}
# Radiation
{401}{}{Il tuo personaggio sta subendo gli effetti di un pesante avvelenamento radioattivo. Maggiore il danno da radiazioni, piu' mortali gli effetti.}
# Eye Damage
{402}{}{Questo significa che il tuo personaggio e' stato colpito duramente a uno o ad entrambi gli occhi.  Cio' influisce sulla Percezione.}
# Crippled right arm
{403}{}{Il braccio destro del tuo personaggio e' stato colpito duro e non funziona bene. Se un braccio e' stato ferito gravemente, non puoi usare armi a due mani. Se entrambe le braccia sono state ferite, non puoi attaccare con le armi.}
# Crippled left arm
{404}{}{Il braccio sinistro del tuo personaggio e' stato colpito duro e non funziona bene. Se un braccio e' stato ferito gravemente, non puoi usare armi a due mani. Se entrambe le braccia sono state ferite, non puoi attaccare con le armi.}
# Crippled right leg
{405}{}{Il tuo personaggio ha una brutta ferita alla gamba destra.}
# Crippled left leg
{406}{}{Il tuo personaggio ha una brutta ferita alla gamba sinistra.}

# Month strings
{500}{}{Gennaio}
{501}{}{Febbraio}
{502}{}{Marzo}
{503}{}{Aprile}
{504}{}{Maggio}
{505}{}{Giugno}
{506}{}{Luglio}
{507}{}{Agosto}
{508}{}{Settembre}
{509}{}{Ottobre}
{510}{}{Novembre}
{511}{}{Dicembre}

#
# Option menu text
#
{600}{}{SALVA}
{601}{}{CARICA}
{602}{}{STAMPA SU FILE}
{603}{}{CANC.}
{604}{}{OK}
{605}{}{Sei sicuro di voler cancellare}      # line 1
{606}{}{questo personaggio?}              # line 2
{607}{}{ e' stato salvato con successo.}
{608}{}{ e' stato caricato con successo.}
{609}{}{esiste gia'.}
{610}{}{Vuoi sovrascrivere?}
{611}{}{Errore di salvataggio: }
{612}{}{Errore di caricamento: }
{613}{}{File del personaggio non valido.}
{614}{}{Dati del personaggio non validi.}
{615}{}{Errore nella lettura della lista dei file!}
{616}{}{STAMPA}
{617}{}{GIOCATORE}
{618}{}{BLANK.GCD}

#
# ASCII text file printing text
#
{620}{}{FALLOUT}                   # Title line 1
{621}{}{VAULT-13: STATO DEL PERSONALE} # Title line 2
{622}{}{Ore} # Title line 3
# -
# -
#{000}{}{      	  Forza: 00        Punti Vita: 000/000          Sequenza: 00}
#{000}{}{    Percezione: 00      Cl. Armatura: 000        Tasso di guar.: 00}
#{000}{}{    Resistenza: 00      Punti Azione: 000        % Col. Critici: 000%}
#{000}{}{       Carisma: 00     Danno Mischia: 000          Peso Portato: 000 lbs.}
#{000}{}{  Intelligenza: 00     Res. al Danno: 000%}
#{000}{}{      Agilita': 00    Res. a Radiaz.: 000%}
#{000}{}{       Fortuna: 00    Res. al Veleno: 000%}
#
{623}{}{ ::: Statistiche :::}
{624}{}{       Forza:}
{625}{}{        Punti Vita:}
{626}{}{        Sequenza:}
# -
{627}{}{     Percezione:}
{628}{}{       Cl. Armatura:}
{629}{}{        Tasso di guarigione:}
# -
{630}{}{      Resistenza:}
{631}{}{     Punti Azione:}
{632}{}{      % Col. Critici:}
# -
{633}{}{        Carisma:}
{634}{}{      Danno Mischia:}
{635}{}{         Peso portato:}
# -
{636}{}{   Intelligenza:}
{637}{}{       Res al Danno:}
# -
{638}{}{        Agilita':}
{639}{}{    Res. a Radiaz.:}
# -
{640}{}{          Fortuna:}
{641}{}{       Res. al Veleno:}
# -
# -
#{000}{}{ Nome: 01234567890       Eta': 00         Sesso: Femmina}
{642}{}{  Nome:}
{643}{}{Eta':}
{644}{}{               Sesso:}
{645}{}{Maschio}
{646}{}{Femmina}
#-
#{000}{}{ Livello: 00                 Esp: 000,000    Pros. Liv.: 000,000}
{647}{}{ Livello:}
{648}{}{                Esp:}
{649}{}{Pros. Liv:}
#-
{650}{}{ ::: Tratti :::}
{651}{}{ ::: Strenne :::}
{652}{}{ ::: Karma :::}

#-
{653}{}{ ::: Abilita' :::                ::: Morti :::}
#-
{654}{}{ ::: Inventario :::}
#-
{655}{}{                                      Peso Totale:}
{656}{}{ ::: Dipendenze :::}
{657}{}{ ::: Reputazione :::}

#
# Karma name strings
#
{1000}{}{Reputazione (Generale) }
{1001}{}{Berserker}
{1002}{}{Eroe}
{1003}{}{Ammazzabambini}
{1004}{}{Dipendenza dalla Nuka Cola}
{1005}{}{Dipendenza da Buffout}
{1006}{}{Dipendenza da Mentat}
{1007}{}{Dipendenza da Psycho}
{1008}{}{Dipendenza da RadAway}
{1009}{}{Dipendenza dall'Alcol}
{1010}{}{Dipendenza da Jet}
{1011}{}{Dipendenza da Tragic}
{1012}{}{THIS GOES WITH THE TEMPORARY ONE FOR DESCRIPTIONS #1112: DON'T TRANSLATE THIS}
{1013}{}{Sexperto}
{1014}{}{Campione}
{1015}{}{Gigolo}
{1016}{}{Tombarolo}
{1017}{}{Picciotto: Salvatore}
{1018}{}{Sposato}
{1019}{}{Pornostar}
{1020}{}{Schiavista}
{1021}{}{Vergine delle Lande}
{1022}{}{Picciotto: Bishop}
{1023}{}{Picciotto: Mordino}
{1024}{}{Picciotto: Wright}
{1025}{}{Divorziato}

#
# Karma description strings
#
{1100}{}{Questa statistica rappresenta la tua reputazione generale. Piu'alto il valore, piu' sei conosciuto e rispettato. Se la tua reputazione e' negativa, qualcuno ti odia per le tue cattive azioni.}
{1101}{}{Hai ucciso un gran numero di persone. Di solito non e' molto positivo diventare famosi per questo. Delinquenti e sbandati, tuttavia, ti rispetteranno di piu'.}
{1102}{}{Le tue azioni ti hanno fatto diventare l'eroe della gente. Notizie della tua guerra contro il male e la delinquenza sono giunte in molti luoghi. Le persone onorevoli ti rispetteranno di piu'.}
{1103}{}{Hai ucciso dei bambini, la gioventu' di queste lande desolate. Questa e' considerata una cosa molto malvagia. Brutto cattivaccio!}
{1104}{}{Ti sei riempito di Nuka-Cola, la bibita del mondo post-nucleare.}
{1105}{}{Sei dipendente dalla droga Buffout. Devi assumere questa droga regolarmente oppure soffrirai gli effetti dell'astinenza.}
{1106}{}{Stai male a causa della dipendenza da Mentat. Devi assumere questa particolare droga oppure soffrirne le crisi d'astinenza.}
{1107}{}{Sei tossicodipendente. Se non assumi Psycho con regolarita', soffrirai. Se l'assumi, soffriranno gli altri.}
{1108}{}{Il tuo corpo e' diventato dipendente da RadAway. Sebbene non sia pericoloso, sei costretto ad assumerlo regolarmente.}
{1109}{}{Hai un problema di alcolismo. In realta', hai molti problemi causati dalle tue abitudini nel bere.}
{1110}{}{Sei tossicodipendente. Devi assumere Jet con regolarita'.}
{1111}{}{Tragicamente, sei dipendente da "L'Accozzaglia". Sei continuamente alla ricerca di nuove espansioni.}
{1112}{}{TEMPORARY - What is this?}
{1113}{}{Conosci il sesso. Conosci le tecniche. Sai come far godere una persona di sesso opposto e lasciarla con una voglia matta di rifarlo.}
{1114}{}{Sei il campione dei pesi massimi del Nord California. Hai ottenuto fama, rispetto, l'amore delle folle... e un bonus per la resistenza fisica e l'abilita' Disarmato.}
{1115}{}{Siamo onesti: vai a letto con qualsiasi cosa cammini su due gambe. Talvolta, non sei neanche cosi' pignolo.}
{1116}{}{"Sono morti, a loro non dispiace" e' diventato il tuo motto. Dissotterrare i resti degli altri e' piu' che un hobby per te.}
{1117}{}{Sei un "Picciotto" della famiglia Salvatore. Sei ben conosciuto, rispettato e stai benissimo con la coppola.}
{1118}{}{Ti hanno incastrato. Ehi, e' un problema tuo, non nostro.}
{1119}{}{Sei una grande, luminosa, brillante stella. Le tue performance sessuali sono ben note in tutta New Reno.}
{1120}{}{Sei stato marchiato come un componente della Gilda degli Schiavisti. Il tatuaggio sulla tua fronte rende la tua professione evidente per chiunque ti incontri.}
{1121}{}{Dovresti davvero cercare di sforzarti un po' di piu'. Le tue performance sessuali sono state...beh, assolutamente piatte.}
{1122}{}{Sei un "Picciotto" della famiglia Bishop. Sei ben conosciuto, rispettato e stai benissimo con la coppola.}
{1123}{}{Sei un "Picciotto" della famiglia Mordino. Sei ben conosciuto, rispettato e stai benissimo con la coppola.}
{1124}{}{Sei un "Picciotto" della famiglia Wright. Sei ben conosciuto, rispettato e stai benissimo con la coppola.}
{1125}{}{La tua dolce meta' non e' piu' con te. Spero tu sia contento.}

#
# Town reputations
#
{2000}{}{Idolatrato}
{2001}{}{Amato}
{2002}{}{Accettato}
{2003}{}{Neutro}
{2004}{}{Antipatico}
{2005}{}{Odiato}
{2006}{}{Diffamato}

{2100}{}{Tutti in questa zona vorrebbero essere come te. Sei il piu' ammirato del posto e sei considerato uno splendente esempio di come tutte le persone dovrebbero essere.}
{2101}{}{Le persone di questa zona ti salutano ovunque tu vada. Tutti hanno sentito parlare di te e a tutti piace quello che hanno sentito.}
{2102}{}{Sebbene tu non sia accolto a braccia aperte, la maggior parte delle persone in questa zona ti faranno un cenno con la testa quando le incontri. Sei accettato come molti altri.}
{2103}{}{Sebbene siano normalmente sospettosi nei riguardi degli stranieri, gli abitanti di questa zona non si sono ancora fatti un'idea precisa su di te.}
{2104}{}{Non sei nient'altro che l'ennesimo forestiero giunto in questa zona. E probabilmente non porti nulla di buono.}
{2105}{}{Hai dimostrato alla gente di questa zona che la loro iniziale sfiducia era ben giustificata. Tutti ti guardano male e iniziano a mormorare non appena ti avvicini. Sanno che non porterai nulla di buono.}
{2106}{}{Ti fissano e mormorano, alcuni cambiano strada per non camminare vicino a te, mentre altri sputano e si girano da un'altra parte quando arrivi. Sanno che sei una delle peggiori cose che siano mai passate nella zona.}

#
# Karma status strings
#
{3000}{}{Salvatore dei Dannati}
{3001}{}{Guardiano delle Lande}
{3002}{}{Scudo della Speranza}
{3003}{}{Difensore}
{3004}{}{Viaggiatore}
{3005}{}{Traditore}
{3006}{}{Spada della Disperazione}
{3007}{}{Flagello delle Lande}
{3008}{}{Figlio del Demonio}

#
# Karma section titles.
#
{4000}{}{Reputazione}
{4001}{}{Dipendenza}

#
# Karma section descriptions.
#
{4100}{}{Rappresenta la tua reputazione in una data locazione.}
{4101}{}{Le cose per le quali sei diventato dipendente.}

#
# Special Demo version only text
#
{5000}{}{Sorry, you can only print your}   # 1
{5001}{}{character in the full version.}   # 2
{5002}{}{Sorry, you can only save your}    # 1
{5003}{}{character in the full version.}   # 2
{5004}{}{Sorry, you can only load a saved} # 1
{5005}{}{character in the full version.}   # 2
{5006}{}{CHEAT MODE}
{5007}{}{Not available in demo.}