#
# Item.c messages
#
{1}{}{Hai guadagnato %d %s.}
{2}{}{Hai perso %d %s.}
{3}{}{Ti senti meglio.}
{4}{}{Hai subito un attacco di cuore letale a causa di un'overdose.}
{5}{}{%s non ha piu' colpi.}
{6}{}{%s e' accesa.}
{7}{}{%s e' spenta.}
{8}{}{Passi il contatore Geiger sul tuo corpo. Il contatore rem indica: %d}
{9}{}{Questo oggetto puo' essere usato solo dall'interfaccia.}
{10}{}{Non accade nulla.}


# Fallout 2:
{50}{}{Non sembra aver fatto molto.}


#
# Fallout 2
#
{500}{}{Non c'e' abbastanza luce per ricaricare questo oggetto.}
#
{600}{}{%s muore a causa degli effetti negativi delle droghe assunte.}

# Weapon Damage strings
{800}{}{Leggero}
{801}{}{Medio}
{802}{}{Pesante}
{803}{}{Estremo}
# Weapon Range strings
{820}{}{Corto}
{821}{}{Medio}
{822}{}{Lungo}