
#
# Messages for Maps
#



#
# Map Names for (Automap) Descriptions
#	Note: This order must *NOT* change!
#
#	Note: The maximum description width is approximately:
#	  "Brotherhood of Steel (Lower Levels)" -- about 34 characters,
#	  but it's proportional, so you need to double-check it by
#	  going into mapper/game and going to the automap for that map.
#
#	Note: Descriptions *MUST* *NOT* be empty, and so temporary
#	  descriptions are just the map name itself (this also helps
#	  pinpoint unfinished ones when you go through here).
#
{100}{}{Deserto}                           // DESERT1.MAP
{101}{}{Deserto}                           // DESERT2.MAP
{102}{}{Deserto}                           // DESERT3.MAP
{103}{}{Arroyo}                           // arcaves.MAP
{104}{}{Arroyo}                           // arvillag.MAP
{105}{}{Arroyo}                           // arbridge.MAP
{106}{}{Il Den}                              // denbus1.MAP
{107}{}{Il Den}                              // denbus2.MAP
{108}{}{Il Den}                              // denres1.MAP
{109}{}{Klamath}                          // .MAP  ;Downtown
{110}{}{Klamath}                          // .MAP  ;Mall
{111}{}{Klamath}                          // .MAP  ;Rat Caves
{112}{}{Klamath}                          // .MAP  ;Toxic Caves
{113}{}{Klamath}                          // .MAP  ;Trapping Caves
{114}{}{Klamath}                          // .MAP  ;Grazing Area
{115}{}{Vault City}                       // vctyctyd.MAP
{116}{}{Vault City}                       // vctydwtn.MAP
{117}{}{Vault City}                       // vctycocl.MAP
{118}{}{error:Map Name}                        // .MAP
{119}{}{Rovine di Citta'}                            // CITY1.MAP
{120}{}{Costa}                                 // COAST1.MAP
{121}{}{Costa}                                 // COAST2.MAP
{122}{}{Deserto}                                // COLATRUK.MAP
{123}{}{Deserto}                                // FSAUSER.MAP
{124}{}{error:Map Name}                              // RAIDERS.MAP
{125}{}{error:Map Name}                          // SHADYE.MAP
{126}{}{error:Map Name}                          // SHADYW.MAP
{127}{}{error:Map Name}                                 // GLOWENT.MAP
{128}{}{error:Map Name}                             // LAADYTUM.MAP
{129}{}{error:Map Name}                             // LAFOLLWR.MAP
{130}{}{error:Map Name}                        // MBENT.MAP
{131}{}{error:Map Name}                        // MBSTRG12.MAP
{132}{}{error:Map Name}                        // MBVATS12.MAP
{133}{}{error:Map Name}                        // MSTRLR12.MAP
{134}{}{error:Map Name}                        // MSTRLR34.MAP
{135}{}{error:Map Name}                             // V13ENT.MAP
{136}{}{error:Map Name}                                  // HUBENT.MAP
{137}{}{Hub}                                  // DETHCLAW.MAP
{138}{}{Hub}                                  // HUBDWNTN.MAP
{139}{}{Hub}                                  // HUBHEIGT.MAP
{140}{}{Hub}                                  // HUBOLDTN.MAP
{141}{}{Hub}                                  // HUBWATER.MAP
{142}{}{Glow}                                 // GLOW1.MAP
{143}{}{Glow}                                 // GLOW2.MAP
{144}{}{Boneyard}                             // LABLADES.MAP
{145}{}{Boneyard}                             // LARIPPER.MAP
{146}{}{Boneyard}                             // LAGUNRUN.MAP
{147}{}{Cathedral}                            // CHILDEAD.MAP
{148}{}{Zona Militare}                             // MBDEAD.MAP
{149}{}{Mountagne}                            // MOUNTN1.MAP
{150}{}{Mountagne}                            // MOUNTN2.MAP
{151}{}{Deserto}                               // FOOT.MAP
{152}{}{Deserto}                               // TARDIS.MAP
{153}{}{Deserto}                               // TALKCOW.MAP
{154}{}{Deserto}                               // USEDCAR.MAP
{155}{}{Confraternita}                          // BRODEAD.MAP
{156}{}{Deserto}                               // DESCRVN1.MAP
{157}{}{Deserto}                               // DESCRVN2.MAP
{158}{}{Montagne}                            // MNTCRVN1.MAP
{159}{}{Montagne}                            // MNTCRVN2.MAP
{160}{}{Viper Camp}
{161}{}{Deserto}
{162}{}{Montagne}
{163}{}{Deserto}
{164}{}{Montagne}


#
# City elevation names -- AUTOMAP Names!
#
# Format: 3 (max elevations), by city
#
# 00: Desert, DESERT1.MAP
{200}{}{Deserto}
{201}{}{}
{202}{}{}
# 01: Desert, DESERT2.MAP
{203}{}{Deserto}
{204}{}{}
{205}{}{}
# 02: Desert, DESERT3.MAP
{206}{}{Deserto}
{207}{}{}
{208}{}{}
# 03: Arroyo Temple, ARCAVES.MAP
{209}{}{Tempio: Entrata}
{210}{}{Tempio: Vestibolo}
{211}{}{Tempio: Santuario Interno}
# 04: Arroyo Village, .MAP
{212}{}{Villaggio}
{213}{}{}
{214}{}{}
# 05: Arroyo Bridge, .MAP
{215}{}{Ponte}
{216}{}{Ponte Distrutto}
{217}{}{}
# 06: Den, denbus1.MAP
{218}{}{Zona Ovest}
{219}{}{}
{220}{}{}
# 07: Den, denbus2.MAP
{221}{}{Zona Est}
{222}{}{}
{223}{}{}
# 08: Den, denres1.MAP
{224}{}{Zona Residenziale}
{225}{}{}
{226}{}{}
# 09: , .MAP ;Klamath Downtown
{227}{}{Centro}
{228}{}{Centro}
{229}{}{Centro}
# 10: , .MAP ;Klamath Mall
{230}{}{Viale}
{231}{}{Viale}
{232}{}{}
# 11: , .MAP ;Klamath Rat Caves
{233}{}{Grotte dei Ratti}
{234}{}{Grotte dei Ratti}
{235}{}{Grotte dei Ratti}
# 12: , .MAP ;Klamath Toxic Caves
{236}{}{Entrata}
{237}{}{Tunnel con Scorie Radioattive}
{238}{}{Magazzini}
# 13: , .MAP ;Klamath Trapping Caves
{239}{}{Territorio di Caccia}
{240}{}{Territorio di Caccia}
{241}{}{Territorio di Caccia}
# 14: , .MAP ;Klamath Grazing Area
{242}{}{Pascolo}
{243}{}{Pascolo}
{244}{}{}
# 15: , .MAP ; Vault City Courtyard
{245}{}{Cortile}
{246}{}{}
{247}{}{}
# 16: , .MAP ; Vault City Downtown
{248}{}{Centro}
{249}{}{}
{250}{}{}
# 17: , .MAP ; Vault City Council
{251}{}{Consiglio}
{252}{}{}
{253}{}{}
# 18: , .MAP ; Modoc Main Street
{254}{}{Strada Principale}
{255}{}{}
{256}{}{}
# 19: , .MAP ; Modoc Bed & Breakfast
{257}{}{Bed & Breakfast}
{258}{}{Bed & Breakfast}
{259}{}{}
# 20: , .MAP ; Modoc Brahmin Pastures
{260}{}{Pascoli dei Brahmin}
{261}{}{}
{262}{}{}
# 21: , .MAP ; Modoc Farrel's Garden
{263}{}{Giardino di Farrel}
{264}{}{}
{265}{}{}
# 22: , .MAP ; Modoc Down the Shitter
{266}{}{Sotto al Cesso}
{267}{}{}
{268}{}{}
# 23: , .MAP ; Modoc Town Hall
{269}{}{Pozzo Cittadino}
{270}{}{}
{271}{}{}
# 24: , .MAP ; Modoc Ghost Town: The Ghost Farm
{272}{}{Fattoria}
{273}{}{}
{274}{}{}
# 25: , .MAP ; Modoc Ghost Town: Main Cavern
{275}{}{Caverna}
{276}{}{}
{277}{}{}
# 26: , .MAP ; Modoc Ghost Town: Underground Lake
{278}{}{Lago sotterraneo}
{279}{}{}
{280}{}{}
# 27: , .MAP ; Sierra Army Depot: The Battlefield
{281}{}{Campo di Battaglia}
{282}{}{}
{283}{}{}
# 28: , .MAP ; Sierra Army Depot: Levels 1-3
{284}{}{Personale}
{285}{}{Magazzini}
{286}{}{Laboratorio Robotica}
# 29: , .MAP ; Sierra Army Depot: Level 4
{287}{}{Laboratorio BioRicerca}
{288}{}{}
{289}{}{}
# 30: Vault City Vault, .MAP
{290}{}{Vault: Livello 1}
{291}{}{Vault: Livello 2}
{292}{}{Vault: Livello 3}
# 31: Gecko Settlement
{293}{}{Insediamento}
{294}{}{Insediamento}
{295}{}{Insediamento}
# 32: Gecko Power Plant, .MAP
{296}{}{Centrale Energetica}
{297}{}{Centrale Energetica}
{298}{}{}
# 33: Gecko Junkyard, .MAP
{299}{}{Discarica}
{300}{}{Discarica}
{301}{}{Discarica}
# 34: Gecko Access Tunnels, .MAP
{302}{}{Tunnel d'Accesso}
{303}{}{Tunnel d'Accesso}
{304}{}{Tunnel d'Accesso}
# 35: Arroyo Wilderness, .MAP
{305}{}{Selva}
{306}{}{}
{307}{}{}
# 36: Vault 15, .MAP
{308}{}{Vault 15: Livello 1}
{309}{}{Vault 15: Livello 2}
{310}{}{Vault 15: Livello 3}
# 37: Vault 15, .MAP
{311}{}{Abusivi}
{312}{}{}
{313}{}{}
# 38: Vault 15, .MAP
{314}{}{Abusivi}
{315}{}{}
{316}{}{}
# 39: Vault 15, .MAP
{317}{}{Entrata Est}
{318}{}{}
{319}{}{}
# 40: Vault 13, .MAP
{320}{}{Livello 1}
{321}{}{Livello 2}
{322}{}{Livello 3}
# 41: Vault 13, .MAP
{323}{}{Caverna}
{324}{}{}
{325}{}{}
# 42: NCR, .MAP
{326}{}{Downtown}
{327}{}{}
{328}{}{}
# 43: NCR, .MAP
{329}{}{Sala del Consiglio}
{330}{}{}
{331}{}{}
# 44: NCR, .MAP
{332}{}{Ranch Westin}
{333}{}{}
{334}{}{}
# 45: NCR, .MAP
{335}{}{Pascoli}
{336}{}{}
{337}{}{}
# 46: NCR, .MAP
{338}{}{Bazaar}
{339}{}{}
{340}{}{}
# 47: NCR, .MAP
{341}{}{Sala del Consiglio}
{342}{}{}
{343}{}{}
# 48: Klamath, klacanyn.MAP
{344}{}{Canyon}
{345}{}{Canyon}
{346}{}{Canyon}
# 49: Military Base, mbase12.MAP
{347}{}{Livello 1}
{348}{}{Livello 2}
{349}{}{}
# 50: Military Base, mbase34.MAP
{350}{}{Livello 3}
{351}{}{Livello 4}
{352}{}{}
# 51: Military Base, mbclose.MAP
{353}{}{Entrata}
{354}{}{}
{355}{}{}
# 52: Den Slave Run dnslvrun.MAP
{356}{}{Deserto}
{357}{}{Villaggio}
{358}{}{Accampamento}
# 53: Car Desert out-of-gas, CarDesrt.MAP
{359}{}{Deserto}
{360}{}{}
{361}{}{}
# 54: New Reno 1 newr1.MAP
{362}{}{Virgin Street}
{363}{}{Scantinato del Desperado}
{364}{}{Desperado, 2do Piano}
# 55: New Reno 2 newr2.MAP
{365}{}{2da Strada}
{366}{}{Shark Club, 2do Piano}
{367}{}{Shark Club, 3zo Piano}
# 56: New Reno 3 newr3.MAP
{368}{}{Zona Commerciale}
{369}{}{Scantinato New Reno Arms}
{370}{}{}
# 57: New Reno 4 newr4.MAP
{371}{}{Zona Est}
{372}{}{Stazione Ferroviaria}
{373}{}{}
# 58: New Reno Chop Shop newrcs.MAP
{374}{}{Chop Shop}
{375}{}{}
{376}{}{}
# 59: New Reno GO newrgo.MAP
{377}{}{Cimitero}
{378}{}{Rifugio Antiatomico}
{379}{}{}
# 60: New Reno ST newrst.MAP
{380}{}{Recinto degli Schiavi}
{381}{}{Laboratorio}
{382}{}{}
# 61: New Reno Boxing Arena newrba.MAP
{383}{}{Palestra di Boxe}
{384}{}{Palestra di Boxe}
{385}{}{Palestra di Boxe}
# 62: Redding Wanamingo Mine Entrance  RedWame.Map
{386}{}{Entrata della Miniera}
{387}{}{Entrata della Miniera}
{388}{}{Entrata della Miniera}
# 63: Great Wanamingo Mine, Level 1 and 2  RedWan1.MAP
{389}{}{Miniera, Livello 1}
{390}{}{Miniera, Livello 2}
{391}{}{}
# 64: Redding Downtown  RedDown.MAP
{392}{}{Centro}
{393}{}{Centro}
{394}{}{Centro}
# 65: Redding Mine Entrance   RedMEnt.MAP
{395}{}{Campo Minerario}
{396}{}{Campo Minerario}
{397}{}{Campo Minerario}
# 66: Redding Downtown Tunnels  RedDTun.MAP
{398}{}{Tunnel}
{399}{}{Tunnel}
{400}{}{Tunnel}
# 67: Redding Mine Entrance Tunnels
{401}{}{Tunnel}
{402}{}{Tunnel}
{403}{}{Tunnel}
# 68: Random Encounter City 1
{404}{}{Citta'}
{405}{}{Citta'}
{406}{}{Citta'}
# 69: Random Encounter Cavern 0
{407}{}{Montagna}
{408}{}{Montagna}
{409}{}{Montagna}
# 70: Random Encounter Cavern 1
{410}{}{Caverne}
{411}{}{Caverna}
{412}{}{Caverna}
# 71: Random Encounter Cavern 2
{413}{}{Caverna}
{414}{}{Caverna}
{415}{}{Caverna}
# 72: Random Encounter Cavern 3
{416}{}{Caverna}
{417}{}{Caverna}
{418}{}{Caverna}
# 73: Random Encounter Cavern 4
{419}{}{Caverna}
{420}{}{Caverna}
{421}{}{Caverna}
# 74: Random Encounter Mountain 1
{422}{}{Montagna}
{423}{}{Montagna}
{424}{}{Montagna}
# 75: Random Encounter Mountain 2
{425}{}{Montagna}
{426}{}{Montagna}
{427}{}{Montagna}
# 76: Random Encounter Coast 1
{428}{}{Costa}
{429}{}{Costa}
{430}{}{Costa}
# 77: Random Encounter Coast 2
{431}{}{Costa}
{432}{}{Costa}
{433}{}{Costa}
# 78: Broken Hills 1  broken1.map
{434}{}{Centro}
{435}{}{Scantinato}
{436}{}{Unused}
# 79: Broken Hills 2 broken2.map
{437}{}{Zona Residenziale}
{438}{}{Sottoterra}
{439}{}{Miniera}
# 80: Random Encounter Cavern 5
{440}{}{Caverna}
{441}{}{Caverna}
{442}{}{Caverna}
# 81: Random Encounter Desert 4
{443}{}{Deserto}
{444}{}{Deserto}
{445}{}{Deserto}
# 82. Random Encounter Desert 5
{446}{}{Deserto}
{447}{}{Deserto}
{448}{}{Deserto}
# 83. Random Encounter Desert 6
{449}{}{Deserto}
{450}{}{Deserto}
{451}{}{Deserto}
# 84. Random Encounter Desert 7
{452}{}{Deserto}
{453}{}{Deserto}
{454}{}{Deserto}
# 85. Random Encounter Coast 3
{455}{}{Costa}
{456}{}{Costa}
{457}{}{Costa}
# 86. Random Encounter Coast 4
{458}{}{Costa}
{459}{}{Costa}
{460}{}{Costa}
# 87. Random Encounter Coast 5
{461}{}{Costa}
{462}{}{Costa}
{463}{}{Costa}
# 88. Random Encounter Coast 6
{464}{}{Costa}
{465}{}{Costa}
{466}{}{Costa}
# 89. Random Encounter Coast 7
{467}{}{Costa}
{468}{}{Costa}
{469}{}{Costa}
# 90. Random Encounter Coast 8
{470}{}{Costa}
{471}{}{Costa}
{472}{}{Costa}
# 91. Random Encounter Coast 9
{473}{}{Costa}
{474}{}{Costa}
{475}{}{Costa}
# 92. Raiders Camp 1
{476}{}{Campo dei Predoni}
{477}{}{Campo dei Predoni}
{478}{}{Campo dei Predoni}
# 93. Raider Camp 2
{479}{}{Entrata della Grotta}
{480}{}{Nido degli Scorpioni}
{481}{}{Caserma}
# 94. Broken Hills Random Encounter Desert
{482}{}{Deserto}
{483}{}{Deserto}
{484}{}{Deserto}
# 95. Broken Hills Random Encounter Mountain
{485}{}{Montagna}
{486}{}{Montagna}
{487}{}{Montagna}
# 96. Special Encounter: Whale
{488}{}{Deserto}
{489}{}{Deserto}
{490}{}{Deserto}
# 97. Special Encounter: Tin Woodsman
{491}{}{Deserto}
{492}{}{Deserto}
{493}{}{Deserto}
# 98. Special Encounter: Talking Head
{494}{}{Deserto}
{495}{}{Deserto}
{496}{}{Deserto}
# 99. Special Encounter: Federation Shuttle
{497}{}{Deserto}
{498}{}{Deserto}
{499}{}{Deserto}
# 100. Special Encounter: Unwashed Villagers
{500}{}{Deserto}
{501}{}{Deserto}
{502}{}{Deserto}
# 101. Special Encounter: Bridge
{503}{}{Ponte della Morte}
{504}{}{Ponte della Morte}
{505}{}{Ponte della Morte}
# 102. Special Encounter: Cafe of Broken Dreams
{506}{}{Caffe' dei Sogni Infranti}
{507}{}{Caffe' dei Sogni Infranti}
{508}{}{Caffe' dei Sogni Infranti}
# 103. Special Encounter: Holy Hand Grenade 1
{509}{}{Deserto}
{510}{}{Deserto}
{511}{}{Deserto}
# 104. Special Encounter: Holy Hand Grenade 2
{512}{}{Montagna}
{513}{}{Caverna}
{514}{}{Caverna}
# 105. Special Encounter: Guardian of Forever
{515}{}{Guardiano}
{516}{}{Vault 13}
{517}{}{Vault 13}
# 106. Special Encounter: Toxic Waste Dump
{518}{}{Discarica di Rifiuti Tossici}
{519}{}{Discarica di Rifiuti Tossici}
{520}{}{Discarica di Rifiuti Tossici}
# 107. Special Encounter: Pahiahs
{521}{}{Deserto}
{522}{}{Deserto}
{523}{}{Deserto}
# 108. Special Encounter: Mad Brahmin
{524}{}{Deserto}
{525}{}{Deserto}
{526}{}{Deserto}
# 109. Navarro Entrance
{527}{}{Pompa di Benzina}
{528}{}{Sottoterra}
{529}{}{Base dei Vertibird}
# 110. Coast Encounter 10
{530}{}{Costiera}
{531}{}{Costiera}
{532}{}{Costiera}
# 111. Coast Encounter 11
{533}{}{Costiera}
{534}{}{Costiera}
{535}{}{Costiera}
# 112. Coast Encounter 12
{536}{}{Costiera}
{537}{}{Costiera}
{538}{}{Costiera}
# 113. Desert Encounter 8
{539}{}{Deserto}
{540}{}{Deserto}
{541}{}{Deserto}
# 114. Desert Encounter 9
{542}{}{Deserto}
{543}{}{Deserto}
{544}{}{Deserto}
# 115. Desert Encounter 10
{545}{}{Deserto}
{546}{}{Deserto}
{547}{}{Deserto}
# 116. Desert Encounter 11
{548}{}{Deserto}
{549}{}{Deserto}
{550}{}{Deserto}
# 117. Desert Encounter 12
{551}{}{Deserto}
{552}{}{Deserto}
{553}{}{Deserto}
# 118. Cavern Encounter 5
{554}{}{Caverna}
{555}{}{Caverna}
{556}{}{Caverna}
# 119. Cavern Encounter 6
{557}{}{Caverna}
{558}{}{Caverna}
{559}{}{Caverna}
# 120. Cavern Encounter 7
{560}{}{Caverna}
{561}{}{Caverna}
{562}{}{Caverna}
# 121. Mountain Encounter 3
{563}{}{Montagna}
{564}{}{Montagna}
{565}{}{Montagna}
# 122. Mountain Encounter 4
{566}{}{Montagna}
{567}{}{Montagna}
{568}{}{Montagna}
# 123. Mountain Encounter 5
{569}{}{Montagna}
{570}{}{Montagna}
{571}{}{Montagna}
# 124. Mountain Encounter 6
{572}{}{Montagna}
{573}{}{Montagna}
{574}{}{Montagna}
# 125. City Encounter
{575}{}{Citta' Abbandonata}
{576}{}{Citta' in Rovina}
{577}{}{Citta' in Rovina}
# 126. Arroyo Temple
{578}{}{Sagrato del Tempio}
{579}{}{Sagrato del Tempio}
{580}{}{Sagrato del Tempio}
# 127. Destroyed Arroyo
{581}{}{Ponte Distrutto}
{582}{}{Ponte Distrutto}
{583}{}{Ponte Distrutto}
# [Map 128] lookup_name=Enclave Detention
{584}{}{Celle di Detenzione}
{585}{}{Celle di Detenzione}
{586}{}{Celle di Detenzione}
# [Map 129] lookup_name=Enclave Dock
{587}{}{Molo}
{588}{}{Molo}
{589}{}{Molo}
# [Map 130] lookup_name=Enclave End Fight
{590}{}{Salone d'Ingresso}
{591}{}{Salone d'Ingresso}
{592}{}{Salone d'Ingresso}
# [Map 131] lookup_name=Enclave Guard Barracks
{593}{}{Caserma delle Guardie}
{594}{}{Caserma delle Guardie}
{595}{}{Caserma delle Guardie}
# [Map 132] lookup_name=Enclave Presidential
{596}{}{Area Presidenziale}
{597}{}{Area Presidenziale}
{598}{}{Area Presidenziale}
# [Map 133] lookup_name=Enclave Reactor
{599}{}{Reattore}
{600}{}{Reattore}
{601}{}{Reattore}
# [Map 134] lookup_name=Enclave Trap Room
{602}{}{Corridoio d'Accesso}
{603}{}{Corridoio d'Accesso}
{604}{}{Corridoio d'Accesso}
# [Map 135] lookup_name=San Fran Tanker
{605}{}{Petroliera}
{606}{}{Petroliera}
{607}{}{Petroliera}
# [Map 136] lookup_name=San Fran Dock
{608}{}{Porto}
{609}{}{Porto}
{610}{}{Porto}
# [Map 137] lookup_name=San Fran China
{611}{}{Chinatown}
{612}{}{Chinatown}
{613}{}{Chinatown}
# 138. Shuttle Exterior
{614}{}{Rampa di Lancio}
{615}{}{Rampa di Lancio}
{616}{}{Rampa di Lancio}
# 139. Shuttle Interior
{617}{}{Interno dello Shuttle}
{618}{}{Interno dello Shuttle}
{619}{}{Interno dello Shuttle}
# 140. Hubologist Base
{620}{}{Base Hubologista}
{621}{}{Base Hubologista}
{622}{}{Base Hubologista}
# 141. City Encounter 3
{623}{}{Citta' Distrutta}
{624}{}{Citta' Distrutta}
{625}{}{Citta' Distrutta}
# 142. City Encounter 4
{626}{}{Citta' Distrutta}
{627}{}{Citta' Distrutta}
{628}{}{Citta' Distrutta}
# 143. City Encounter 5
{629}{}{Citta' Distrutta}
{630}{}{Citta' Distrutta}
{631}{}{Citta' Distrutta}
# 144. City Encounter 6
{632}{}{Citta' Distrutta}
{633}{}{Citta' Distrutta}
{634}{}{Citta' Distrutta}
# 145. City Encounter 7
{635}{}{Citta' Distrutta}
{636}{}{Citta' Distrutta}
{637}{}{Citta' Distrutta}
# 146. City Encounter 8
{638}{}{Citta' Distrutta}
{639}{}{Citta' Distrutta}
{640}{}{Citta' Distrutta}
# 147. New Reno VB  newrvb.MAP
{641}{}{Area del Vertibird}
{642}{}{Area del Vertibird}
{643}{}{Area del Vertibird}
# 148. Shi Temple
{644}{}{Tempio Shi}
{645}{}{}
{646}{}{Base della Confraternita}
# 149. In Game Movie
{647}{}{Deserto}
{648}{}{Deserto}
{649}{}{Deserto}
# 150. RndBess
{650}{}{Deserto}
{651}{}{Deserto}
{652}{}{Deserto}
# 151. Abbey
{653}{}{Entrata}
{654}{}{Piano Inferiore}
{655}{}{Deserto}
# 151. EPA
{656}{}{}
{657}{}{}
{658}{}{}

#
#	Short City names
#
{1500}{}{Arroyo}
{1501}{}{Il Den}
{1502}{}{Klamath}
{1503}{}{Modoc}
{1504}{}{Vault City}
{1505}{}{Gecko}
{1506}{}{Broken Hills}
{1507}{}{New Reno}
{1508}{}{Deposito Militare Sierra}
{1509}{}{Vault 15}
{1510}{}{New California Republic}
{1511}{}{Vault 13}
{1512}{}{Base Militare}
{1513}{}{Redding}
{1514}{}{San Francisco}
{1515}{}{Navarro}
{1516}{}{L'Enclave}
{1517}{}{Deserto}           # Abbey
{1518}{}{Deserto}           # Primitive Tribe
{1519}{}{Deserto}           # EPA
{1520}{}{Fattoria Fantasma}
{1521}{}{Macchina a secco}
{1522}{}{Arroyo}
{1523}{}{Grotte Tossiche}
{1524}{}{Raid Schiavista}
{1525}{}{Predoni}
{1526}{}{Deserto}
{1527}{}{Montagna}
{1528}{}{Citta' in Rovina}
{1529}{}{Costa}
{1530}{}{Golgotha}
{1531}{}{Balena Arenata}
{1532}{}{Uomo di Latta}
{1533}{}{Testa Parlante}
{1534}{}{Shuttle della Federazione}
{1535}{}{Unwashed Villagers}
{1536}{}{Ponte}
{1537}{}{Caffe' dei Sogni Infranti}
{1538}{}{Paladini}
{1539}{}{Grotta del Ratto Vorpal}
{1540}{}{Guardiano del Persempre}
{1541}{}{Discarica di Rifiuti Tossici}
{1542}{}{I Paria}
{1543}{}{Brahmin Pazzo}
{1544}{}{Carovana}
{1545}{}{Vault 13}
{1546}{}{Falso Vault 13}
{1547}{}{Incontro Casuale}
{1548}{}{Stalle}
{1549}{}{Abbazia}
{1550}{}{EPA} # Environmental Protection Agency = Ente di Protezione Ambientale
