#
# Miscellaneous game engine messages.
#
# Defined in game.h
#
{0}{}{Sei sicuro di voler uscire?}
{1}{}{Versione demo}
{2}{}{Default character will be used.}
{3}{}{Immagine salvata.}
{4}{}{Caricamento rapido effettuato.}
{5}{}{Salvataggio rapido effettuato.}
{6}{}{Demo time limit exceeded.}
{7}{}{Il Pipboy non e' accessibile in combattimento!}
{8}{}{Errore nel salvare l'immagine.}
{9}{}{INTRO}
{10}{}{NUOVO}
{11}{}{CARICA}
{12}{}{OPZIONI}
{13}{}{CREDITI}
{14}{}{ESCI}
{15}{}{Punti Azione}
{16}{}{Punti Vita}
{17}{}{Il sensore di movimento non e' installato.}
{18}{}{Il sensore di movimento ha esaurito la carica.}
{20}{}{(C) 1998 Interplay Prod. All rights reserved. Traduzione Italiana: Ragfox}

{30}{}{Vuoi continuare a giocare?}

{50}{}{Fallout 2 richiede il CD per funzionare!}

#
# Game config text. Defined in gconfig.c
#
{100}{}{Errore nel salvataggio della configurazione!}
{101}{}{Configurazione non salvata.}
#
# Some radiation messages used in critter.c
#
{1000}{}{Hai un forte senso di nausea.}
{1001}{}{Hai la nausea e, dopo una breve vomitata, sei leggermente affaticato.}
{1002}{}{Sei molto affaticato, il vomito non si ferma e le tue capacita' di recupero sono compromesse.}
{1003}{}{Stai avendo un'emorragia massiva. Stai molto male e stai perdendo i capelli.}
{1004}{}{Hai una violenta e continua emorragia. Il vomito e' rosso a causa del sangue. La pelle ti si sta staccando dalle ossa.}
{1005}{}{C'e' una emorragia nel tuo intestino e hai gravi attacchi di diarrea. Ti senti gonfio e sei in agonia.}
{1006}{}{Sei morto a causa delle radiazioni.}
{1007}{}{Hai ricevuto una pesante dose di radiazioni.}
{1008}{}{Il contatore Geiger sta ticchettando.}
{1009}{}{Il contatore Geiger sta ticchettando intensamente.}
#
# Message used in actions.c
#
{2000}{}{Non puoi andarci.}
{2001}{}{La serratura si e' inceppata.}
#
# poison messages from critter.c
#
{3000}{}{Sei stato avvelenato!}
{3001}{}{Hai subito gli effetti del veleno.}
{3002}{}{Ti senti un po' meglio.}
{3003}{}{Ti senti meglio.}
#
# from queue.c
#
{4000}{}{A causa della tua inettitudine, l'esplosivo e' detonato prima del previsto.}
#
# from combatai.c
#
{5000}{}{usa}
{5001}{}{ha finito le munizioni per}
{5002}{}{ricarica}
#
# from gdialog.c - new tell me about stuff
#
{6000}{}{Chiedi a proposito di?}

#
# from pipboy.c -- Fallout 2
#
{7000}{}{Non stai indossando il PipBoy!}

#
# from anim.c -- Fallout 2
#
{8000}{}{Sei troppo carico.}  # Carrying too much weight
{8001}{}{%s e' troppo carico.}

#
# from worldmap.c -- Fallout 2
#
{8500}{}{Guadagni %d punti esperienza per aver utilizzato con successo l'abilita' Escursionista.}

#
# from party.c -- Fallout 2
#
{9000}{}{%s ha guadagnato un livello di esperienza.} # Party Member has gained experience/level
# Individuals

{9010}{}{Wow. Ho improvvisamente avvertito un flusso di esperienza.} # pMMyron_PID
{9011}{}{Livello, baby! Livello!}
{9012}{}{Sento un grande disturbo nella Forza. Come se tutte le mie abilita' avessero guadagnato punti percentuali.}
{9013}{}{Mi sento piu' grosso. Piu' forte. Piu' intelligente.}

{9020}{}{Wow! Mi sento come se avessi passato un qualche valore arbitrario di esperienza e avessi guadagnato piu' forza!} # pMMarcus_PID
{9021}{}{Aaagggh! Muscoli... si gonfiano... Condizione... in miglioramento.... Livello guadagnato...}
{9022}{}{Datemi un diploma e un ridicolo cappello con una nappa: mi sono appena laureato!}
{9023}{}{Ehi, mi sento piu' forte! Significa per caso che prendero' un aumento di paga?}

{9030}{}{Tutto ritorna da me, adesso...} # pMMacRae_PID
{9031}{}{Heh. Sembra che anche un vecchio lupo come me possa ancora imparare qualche trucchetto nuovo.}
{9032}{}{Sembra che tutto questo viaggiare mi stia ripagando.}
{9033}{}{Ho imparato qualche nuovo trucchetto.}

{9040}{}{Grande Avo insegna. Noi impara.} # pMSulik_PID
{9041}{}{Noi impara molto da spiriti, amico.}
{9042}{}{Noi ora stare imparando.}
{9043}{}{Ora Grandi Spiriti si muovere in Sulik.}
{9044}{}{Ora noi e Osso di Grande Avo essere uno, amico.}
{9045}{}{Ora noi essere Grande Avo.}

{9050}{}{Oh mamma...Ho imparato qualcosa.} # pMLenny_PID
{9051}{}{Il rimorso mi uccidera'.}
{9052}{}{Non posso credere di essere sopravvissuto fin qui.}

{9060}{}{Woof!} # pMCyberdog_PID
{9061}{}{Woof!}
{9062}{}{Woof!}
{9063}{}{Woof!}
{9064}{}{Woof! Woof!}

{9070}{}{Ho imparato qualcosa di nuovo!} # pMDoc_PID
{9071}{}{Ho imparato qualcosa di nuovo!}

{9080}{}{Credo di aver appreso nuove conoscenze!} # pMGoris_PID
{9081}{}{La chiarezza nella conoscenza e' un dono.}
{9082}{}{Pare che io stia maturando positivamente.}
{9083}{}{Supero in conoscenza persino Gruthar.}
{9084}{}{Ho aumentato il mio potere nel branco.}
{9085}{}{Ora sono il migliore del mio branco.}

{9090}{}{Ho imparato qualcosa di nuovo!} # pMDavin_PID
{9091}{}{Ho imparato qualcosa di nuovo!}

{9100}{}{Ho imparato qualcosa di nuovo!} # pMMaria_PID
{9101}{}{Ho imparato qualcosa di nuovo!}

{9110}{}{Ho imparato qualcosa di nuovo!} # pMLaddie_PID
{9111}{}{Ho imparato qualcosa di nuovo!}

{9120}{}{ANALISI DATI COMPLETATA. AGGIORNAMENTO DEL SISTEMA IN CORSO.} # pMRoboBrain_PID  -- CyberBrain
{9121}{}{NUOVI DATI RACCOLTI. MIGLIORAMENTO DEI SISTEMI DI PUNTAMENTO IN CORSO.}
{9122}{}{AGGIORNAMENTO SISTEMA COMPLETATO.}
{9123}{}{SISTEMI DI PUNTAMENTO RICALIBRATI. MIGLIORAMENTO PRECISIONE: 20%.}
{9124}{}{FUNZIONAMENTO OTTIMALE RAGGIUNTO.}

{9130}{}{Capo! Credo di esserne finalmente venuto a capo.} # pMVic_PID
{9131}{}{Sto migliorando! L'avevo detto che non ti avrei deluso, Capo.}
{9132}{}{Ehi... 'spetta... ora ci sono. Forse dovrei sparare un po' di piu' ai miei bersagli.}
{9133}{}{Vedi, Capo? Anche una vecchia talpa puo' imparare qualche trucco nuovo!}
{9134}{}{Sai una cosa, Capo? Penso di stare imparando una o due cose.}
{9135}{}{Sto diventando abbastanza bravo. Vedi, Capo. Ogni buona cosa diventa migliore col tempo.}

{9140}{}{Ho imparato qualcosa di nuovo!} # pMBess_PID
{9141}{}{Ho imparato qualcosa di nuovo!}

{9150}{}{Ho imparato qualcosa di nuovo!} # pMChicken_PID
{9151}{}{Ho imparato qualcosa di nuovo!}

{9160}{}{Ho imparato qualcosa di nuovo!} # pMKarl_PID
{9161}{}{Ho imparato qualcosa di nuovo!}

{9170}{}{Ho imparato qualcosa di nuovo!} # pMJonny_PID
{9171}{}{Ho imparato qualcosa di nuovo!}

{9180}{}{Ho imparato qualcosa di nuovo!} # pMLloyd_PID
{9181}{}{Ho imparato qualcosa di nuovo!}

{9190}{}{Woof WOOF!} # pMDogMeat_PID
{9191}{}{Woof WOOF WOOOOF!}
{9192}{}{Woof WOOF WOOOOF!}
{9193}{}{Woof WOOF WOOOOF!}
{9194}{}{Woof WOOF WOOOOF!}
{9195}{}{Wa-WOOOOF!}

{9200}{}{} # pMRoboBrain_PID -- Human

{9210}{}{} # pMRoboBrain_PID -- Abnormal

{9220}{}{} # pMRoboBrain_PID -- Chimp

{9230}{}{} # pMPariahDog_PID

{9240}{}{Iniziato aggiornamento programma, Padrone... Aggiornamento completo.}  # pMK9_PID
{9241}{}{Installazione aggiornamento programma in corso, Padrone... Versione 2.0 installata.}
{9242}{}{Modificazione del software in corso, Padrone... Sistemi a posto.}
{9243}{}{Modificazione del software in corso, Padrone... Massima efficienza dei sistemi!}


{9250}{}{} # pMCarTrunk_PID
