{100}{}{un Eroe}
{101}{}{}
{200}{}{un'Eroina}
{201}{}{}
{300}{}{un Abitante del Villaggio}
{400}{}{un'Abitante del Villaggio}
{500}{}{un Radscorpione}
{501}{}{Un piccolo scorpione mutante.}
{600}{}{un Radscorpione}
{601}{}{Uno scorpione mutante.}
{700}{}{un Deathclaw}
{701}{}{Un Deathclaw immaturo.}
{800}{}{un Deathclaw}
{801}{}{Un Deathclaw immaturo.}
{900}{}{un Cane}
{901}{}{Un canide, probabilmente un meticcio.}
{1000}{}{un Brahmin}
{1001}{}{Una mucca mutante bicipite.}
{1100}{}{un Ratto}
{1101}{}{Un grosso ratto comune.}
{1200}{}{una Mantide}
{1201}{}{Una mantide mutante.}
{1300}{}{l'Anziana}
{1400}{}{Hakunin}
{1500}{}{Mynoc}
{1600}{}{una Pianta Sporigena}
{1601}{}{Una pianta carnivora.}
{1700}{}{una Schiava carina}
{1800}{}{uno Schiavo affascinante}
{1900}{}{una Schiava in salute}
{2000}{}{uno Schiavo in salute}
{2100}{}{una Schiava forte}
{2200}{}{uno Schiavo forte}
{2300}{}{una Schiava da combattimento}
{2400}{}{uno Schiavo da combattimento}
{2500}{}{una Schiava intelligente}
{2600}{}{uno Schiavo intelligente}
{2700}{}{una Schiava generica}
{2800}{}{uno Schiavo generico}
{2900}{}{Anna}
{3000}{}{un Criminale robusto}
{3100}{}{una Criminale robusta}
{3200}{}{un Criminale da mischia}
{3300}{}{una Criminale da mischia}
{3400}{}{un Criminale agile}
{3500}{}{una Criminale agile}
{3600}{}{un Criminale con pistola}
{3700}{}{una Criminale con pistola}
{3800}{}{un Criminale con grossa pistola}
{3900}{}{una Criminale con grossa pistola}
{4000}{}{una Guardia robusta}
{4100}{}{una Guardia}
{4200}{}{una Guardia da mischia}
{4300}{}{una Guardia}
{4400}{}{una Guardia agile}
{4500}{}{una Guardia}
{4600}{}{una Guardia con pistola}
{4700}{}{una Guardia con pistola}
{4800}{}{una Guardia con grossa pistola}
{4900}{}{una Guardia con grossa pistola}
{5000}{}{un Orfano}
{5100}{}{un'Orfana}
{5200}{}{un Bambino}
{5300}{}{una Bambina}
{5400}{}{un Perdente}
{5500}{}{una Perdente}
{5600}{}{un Mercante Scarso}
{5700}{}{una Mercante Scarsa}
{5800}{}{un Mercante nella Media}
{5900}{}{una Mercante nella Media}
{6000}{}{un Maestro Mercante}
{6100}{}{una Maestra Mercante}
{6200}{}{Vic}
{6300}{}{un Contadino Debole}
{6400}{}{una Contadina Debole}
{6500}{}{un Contadino nella Media}
{6600}{}{una Contadina nella Media}
{6700}{}{un Contadino Forte}
{6800}{}{una Contadina Forte}
{6900}{}{una Debole Guardia da Mischia}
{7000}{}{una Debole Guardia da Mischia}
{7100}{}{una Debole Guardia con Pistola}
{7200}{}{una Debole Guardia con Pistola}
{7300}{}{un Robot per le Riparazioni}
{7400}{}{un Robot per le Riparazioni vers. II}
{7500}{}{Robobrain}
{7600}{}{un Eye-Bot}
{7700}{}{un Robot Sentinella}
{7800}{}{un Robot Sentinella vers. II}
{7900}{}{Robobrain}
{8000}{}{un Piccolo Gecko}
{8100}{}{un Gecko Piccolo ma Tenace}
{8200}{}{un Cane Selvatico}
{8201}{}{Un cane meticcio selvatico.}
{8300}{}{un Gecko Dorato}
{8400}{}{un Deathclaw}
{8500}{}{un Cucciolo di Deathclaw}
{8600}{}{un Tenace Gecko Dorato}
{8700}{}{Lynette}
{8800}{}{il Dr. Troy}
{8900}{}{John Cassidy}
{9000}{}{Gregory}
{9100}{}{una Cittadina}
{9200}{}{un Cittadino}
{9300}{}{una Cittadina di Classe}
{9400}{}{un Cittadino di Classe}
{9500}{}{un Trapper}
{9600}{}{una Trapper}
{9700}{}{Sulik}
{9800}{}{Maida Buckner}
{9900}{}{Torr}
{10000}{}{Lumpy}
{10100}{}{un Luminoso del Reattore}
{10200}{}{un Ghoul del Reattore}
{10300}{}{una Guardia del Reattore}
{10400}{}{Zomak}
{10500}{}{Skeeter}
{10600}{}{Il Prof}
{10700}{}{Lenny}
{10800}{}{Wooz}
{10900}{}{Harold}
{11000}{}{un Ratto-talpa}
{11100}{}{un Ratto-talpa Maggiore}
{11200}{}{un Ratto-porco}
{11300}{}{un Ratto-porco Tenace}
{11400}{}{un Brahmin Debole}
{11401}{}{Una mucca mutante bicipite.}
{11500}{}{A.Pwr.Armor (don't use)}
{11600}{}{un Ratto Mutante}
{11601}{}{Un tenace ratto mutante.}
{11700}{}{un Ratto-talpa Mutante}
{11701}{}{Un tenace ratto-talpa mutante.}
{11800}{}{un Ratto-porco Mutante}
{11801}{}{Un tenace ratto-talpa mutante.}
{11900}{}{un Super Mutante}
{12000}{}{Mutante Potente}
{12100}{}{Melchior}
{12200}{}{Hero Andro (don't use)}
{12300}{}{Hero Andro (don't use)}
{12400}{}{Hero Male (don't use)}
{12500}{}{Hero Female (don't use)}
{12600}{}{Hero Male (don't use)}
{12700}{}{Hero Female (don't use)}
{12800}{}{Hero Male (don't use)}
{12900}{}{Hero Female (don't use)}
{13000}{}{Hero Male (don't use)}
{13100}{}{Hero Female (don't use)}
{13200}{}{Hero Male (don't use)}
{13300}{}{Hero Female (don't use)}
{13400}{}{una Guardia di Vault City}
{13500}{}{una Guardia di Vault City}
{13600}{}{un Cybercane}
{13700}{}{una Guardia di NCR}
{13800}{}{una Guardia di NCR}
{13900}{}{una Guardia da Mischia di NCR}
{14000}{}{una Guardia degli Schiavisti}
{14100}{}{un Caposquadra degli Schiavisti}
{14200}{}{un Gran Maestro Mercante}
{14300}{}{una Gran Maestra Mercante}
{14400}{}{Tandi}
{14500}{}{Merc}
{14600}{}{Ratch}
{14700}{}{Doofus}
{14800}{}{Mikey}
{14900}{}{il Barista di NCR}
{15000}{}{un Negoziante}
{15100}{}{Gruthar}
{15200}{}{Goris}
{15300}{}{un Ratto-talpa Guerriero}
{15400}{}{un Ratto-talpa Guerriero}
{15500}{}{un Ratto-talpa Guerriero}
{15600}{}{un Ratto-talpa Guerriero}
{15700}{}{un Ratto-talpa Guerriero}
{15800}{}{un Ratto-talpa Guerriero}
{15900}{}{un Ghoul Generico}
{16000}{}{Myron}
{16100}{}{Marcus}
{16200}{}{Doc Jones}
{16300}{}{Davin}
{16400}{}{Miria}
{16500}{}{Laddie}
{16600}{}{Rondo}
{16700}{}{un Bracciante del Ranch}
{16800}{}{una Bracciante del Ranch}
{16900}{}{un Bracciante del Ranch}
{17000}{}{un Buttafuori}
{17100}{}{un Buttafuori}
{17200}{}{un Mr. Handy Debole}
{17300}{}{un Luminoso Generico}
{17400}{}{Dar}
{17500}{}{Dalia}
{17600}{}{Gordon}
{17700}{}{test (don't use)}
{17800}{}{un Ghoul del Reattore}
{17900}{}{un Ghoul Generico}
{18000}{}{Matt}
{18100}{}{il Capo dei Cacciat. di taglie (1-6)}
{18200}{}{un Cacciatore di taglie (1-6)}
{18300}{}{il Capo dei Cacciat. di taglie (7-12)}
{18400}{}{un Cacciatore di taglie (7-12)}
{18500}{}{una Cacciatrice di taglie (7-12)}
{18600}{}{il Capo dei Cacciat. di taglie (13-18)}
{18700}{}{un Cacciatore di taglie (13-18)}
{18800}{}{una Cacciatrice di taglie (13-18)}
{18900}{}{il Capo dei Cacciat. di taglie (19-?)}
{19000}{}{un Cacciatore di taglie (19-?)}
{19100}{}{Bess}
{19101}{}{Una mucca mutante bicipite.}
{19200}{}{Balthas}
{19300}{}{Grisham}
{19400}{}{Phil}
{19500}{}{la Gallina}
{19600}{}{Karl}
{19700}{}{Jonny}
{19800}{}{Jo}
{19900}{}{Zeke}
{20000}{}{un Macellaio}
{20100}{}{Petey}
{20200}{}{un Cacciatore Primitivo}
{20300}{}{una Cacciatrice Primitiva}
{20400}{}{un Cannibale}
{20500}{}{una Cannibale}
{20600}{}{un Uomo di Chiesa}
{20700}{}{una Donna di Chiesa}
{20800}{}{un Nomade- Bas}
{20900}{}{un Nomade- Med}
{21000}{}{una Nomade- Bas}
{21100}{}{una Nomade- Med}
{21200}{}{un Bandito}
{21300}{}{una Donna Bandito}
{21400}{}{un Contadino}
{21500}{}{una Contadina}
{21600}{}{una Mantide}
{21700}{}{uno Schiavista}
{21800}{}{una Schiavista}
{21900}{}{un Brahmin Selvatico}
{22000}{}{un Colono}
{22100}{}{una Colona}
{22200}{}{una Guardia di Pattuglia di Vault City}
{22300}{}{una Guardia di Pattuglia di Vault City}
{22400}{}{uno Schiavista Forte}
{22500}{}{una Schiavista Forte}
{22600}{}{un Pazzo}
{22700}{}{uno Sciacallo}
{22800}{}{un Fosforescente Pazzo}
{22900}{}{un Fosforescente Sciacallo}
{23000}{}{un Pescatore}
{23100}{}{una Pescatrice}
{23200}{}{un Selvaggio}
{23300}{}{una Selvaggia}
{23400}{}{un Contrabbandiere}
{23500}{}{un Donna Contrabbandiere}
{23600}{}{un Cercatore}
{23700}{}{una Cercatrice}
{23800}{}{un Predone}
{23900}{}{una Predone}
{24000}{}{un Gecko di Fuoco}
{24100}{}{un Tenace Gecko di Fuoco}
{24200}{}{un Alieno}
{24300}{}{un Alieno Tenace}
{24400}{}{un Deathclaw Piccolo ma Tenace}
{24500}{}{un Deathclaw Tenace}
{24600}{}{un Fluttuante}
{24700}{}{un Fluttuante Cattivo}
{24800}{}{un Centauro}
{24900}{}{un Centauro Maligno}
{25000}{}{una Guardia di Pattuglia dell'Enclave}
{25100}{}{una Guardia di Pattuglia dell'Enclave}
{25200}{}{un Membro della Squadra di Arruolamento}
{25300}{}{un Membro della Squadra di Arruolamento}
{25400}{}{un Mercenario}
{25500}{}{una Mercenaria}
{25600}{}{un Nightkin}
{25700}{}{un Nightkin Tenace}
{25800}{}{un Ghoul Tenace}
{25900}{}{un Gangster}
{26000}{}{uno Yakuza}
{26100}{}{un Ranger di NCR}
{26200}{}{una Ranger di NCR}
{26300}{}{un Razziatore}
{26400}{}{una Razziatrice}
{26500}{}{"Pretty Boy" Lloyd}
{26600}{}{Ratto Vorpal}
{26700}{}{un Uomo del Vault 13}
{26800}{}{una Donna del Vault 13}
{26900}{}{il Guardiano del Ponte}
{27000}{}{lo Straniero Misterioso}
{27100}{}{la Straniera Misteriosa}
{27200}{}{Hakeswill}
{27300}{}{Big Jesus Mordino}
{27400}{}{Dumar}
{27500}{}{Madre Deathclaw}
{27600}{}{Dragon}
{27700}{}{Lo Pan}
{27800}{}{un Hubologista}
{27900}{}{una Hubologista}
{28000}{}{lo Straniero Mistrioso}
{28100}{}{la Straniera Mistriosa}
{28200}{}{lo Straniero Mistrioso}
{28300}{}{la Straniera Mistriosa}
{28400}{}{lo Straniero Mistrioso}
{28500}{}{la Straniera Mistriosa}
{28600}{}{lo Straniero Mistrioso}
{28700}{}{la Straniera Mistriosa}
{28800}{}{il Gorilla del Pres.}
{28900}{}{un Uovo di Deathclaw}
{29000}{}{Metzger}
{29100}{}{una Persona}
{29200}{}{una Persona in uno strano tipo di corazza}
{29300}{}{il Presidente}
{29400}{}{il Vicepresidente}
{29500}{}{un Tecnico}
{29600}{}{Badger}
{29700}{}{il Dr. Fung}
{29800}{}{un Bambino}
{29900}{}{un Bambino}
{30000}{}{un Mercante d'armi}
{30100}{}{un Tecnico del Lab. Shi}
{30200}{}{una Guardia}
{30300}{}{un Contadino Shi}
{30400}{}{una Contadina Shi}
{30500}{}{un Contadino di Lo Pan}
{30600}{}{una Contadina di Lo Pan}
{30700}{}{un Lavoratore del Porto}
{30800}{}{un Mercante Shi}
{30900}{}{il Reeh Rat'to}
{31000}{}{Sulik - Stage 1}
{31100}{}{Sulik - Stage 2}
{31200}{}{Sulik - Stage 3}
{31300}{}{Sulik - Stage 4}
{31400}{}{Sulik - Stage 5}
{31500}{}{Sulik - Stage 6}
{31600}{}{Lenny - Stage 1}
{31700}{}{Lenny - Stage 2}
{31800}{}{Lenny - Stage 3}
{31900}{}{Goris - Stage 1}
{32000}{}{Goris - Stage 2}
{32100}{}{Goris - Stage 3}
{32200}{}{Goris - Stage 4}
{32300}{}{Goris - Stage 5}
{32400}{}{Goris - Stage 6}
{32500}{}{Myron - Stage 1}
{32600}{}{Myron - Stage 2}
{32700}{}{Myron - Stage 3}
{32800}{}{Myron - Stage 4}
{32900}{}{Marcus - Stage 1}
{33000}{}{Marcus - Stage 2}
{33100}{}{Marcus - Stage 3}
{33200}{}{Marcus - Stage 4}
{33300}{}{Marcus - Stage 5}
{33400}{}{Cybercane - Stage 1}
{33500}{}{Cybercane - Stage 2}
{33600}{}{Cybercane - Stage 3}
{33700}{}{Cybercane - Stage 4}
{33800}{}{Cassidy - Stage 1}
{33900}{}{Cassidy - Stage 2}
{34000}{}{Cassidy - Stage 3}
{34100}{}{Cassidy - Stage 4}
{34200}{}{Dogmeat}
{34300}{}{Dogmeat - Stage 1}
{34400}{}{Dogmeat - Stage 2}
{34500}{}{Dogmeat - Stage 3}
{34600}{}{Dogmeat - Stage 4}
{34700}{}{Dogmeat - Stage 5}
{34800}{}{Dogmeat - Stage 6}
{34900}{}{Robobrain - Stage 1}
{35000}{}{Robobrain - Stage 2}
{35100}{}{Robobrain - Stage 3}
{35200}{}{Robobrain - Stage 4}
{35300}{}{Robobrain - Stage 5}
{35400}{}{la Regina Aliena}
{35500}{}{un Radscorpione Nero}
{35600}{}{un Radscorpione Nero}
{35700}{}{Spud}
{35800}{}{il Capitano dei Mercenari}
{35900}{}{un Mercenario}
{36000}{}{un Mercenario}
{36100}{}{Ombra-che-cammina}
{36200}{}{un Punk}
{36300}{}{una Punk}
{36400}{}{Marc}
{36500}{}{Dave H.}
{36600}{}{il Capit. A. Ron Meyers}
{36700}{}{Chip}
{36800}{}{AHS-9}
{36900}{}{una Guardia Hubologist}
{37000}{}{una Guardia Hubologist}
{37100}{}{Juan}
{37200}{}{Vikki}
{37300}{}{Vic - Stage 1}
{37400}{}{Vic - Stage 2}
{37500}{}{Vic - Stage 3}
{37600}{}{Vic - Stage 4}
{37700}{}{Vic - Stage 5}
{37800}{}{Vic - Stage 6}
{37900}{}{Robobrain - Scimpanze'}
{38000}{}{Robobrain - Anormale}
{38100}{}{Robobrain - Umano}
{38200}{}{una Formica Gigante}
{38300}{}{una Formica Gigante Tenace}
{38400}{}{Cane Paria}
{38500}{}{Zurak}
{38600}{}{Imbot}
{38700}{}{Jimmy}
{38800}{}{Wejungh}
{38900}{}{Herb}
{39000}{}{Loopal}
{39100}{}{Jobe}
{39200}{}{Smitty}
{39300}{}{Rube}
{39400}{}{Master Krall}
{39500}{}{Ziggy}
{39600}{}{Master Khung}
{39700}{}{John Bishop}
{39800}{}{Angela Bishop}
{39900}{}{la Signora Bishop}
{40000}{}{una Guardia di Bishop 1}
{40100}{}{una Guardia di Bishop 2}
{40200}{}{un Criminale di Bishop 1}
{40300}{}{un Criminale di Bishop 2}
{40400}{}{un Brahmin Infuriato}
{40500}{}{Lil' Jesus}
{40600}{}{Big Jesus}
{40700}{}{un Uomo di Mordino 1}
{40800}{}{un Uomo di Mordino 2}
{40900}{}{un Uomo di Mordino 3}
{41000}{}{una Guardia di Myron 1}
{41100}{}{una Guardia di Myron 2}
{41200}{}{Mr. Wright}
{41300}{}{Mrs. Wright}
{41400}{}{Chris Wright}
{41500}{}{Keith Wright}
{41600}{}{un Figlio di Wright 1}
{41700}{}{un Figlio di Wright 2}
{41800}{}{una Figlia di Wright 1}
{41900}{}{una Figlia di Wright 2}
{42000}{}{Mr. Salvatore}
{42100}{}{Mason}
{42200}{}{un Gangster di Salvatore 1}
{42300}{}{un Gangster di Salvatore 2}
{42400}{}{un Barista Generico 1}
{42500}{}{un Barista Generico 2}
{42600}{}{un Barista Generico 3}
{42700}{}{un Pugile 1}
{42800}{}{un Pugile 2}
{42900}{}{un Pugile 3}
{43000}{}{un Pugile 4}
{43100}{}{Mike il Masticatore}
{43200}{}{Holyfeld}
{43300}{}{McKneely}
{43400}{}{Stuart Little}
{43500}{}{uno dei Fratelli Corsican}
{43600}{}{una delle Puttane dei Corsican}
{43700}{}{Padre Tully}
{43800}{}{un Buttafuori del Casino' 1}
{43900}{}{un Buttafuori del Casino' 2}
{44000}{}{una Ragazza del Casino'}
{44100}{}{uno Spacciatore/Pappone1}
{44200}{}{uno Spacciatore/Pappone2}
{44300}{}{uno Spacciatore/Pappone3}
{44400}{}{uno Spacciatore/Pappone4}
{44500}{}{McGee}
{44600}{}{Miss Kitty}
{44700}{}{una Sgualdrina Generica 1}
{44800}{}{una Sgualdrina Generica 2}
{44900}{}{Jimmy J, lo Sfregiato}
{45000}{}{Renesco}
{45100}{}{Scienziato}
{45200}{}{Eldridge}
{45300}{}{Algernon}
{45400}{}{Jules}
{45500}{}{un Burocrate 1}
{45600}{}{un Burocrate 2}
{45700}{}{un Mercante 1}
{45800}{}{un Mercante 2}
{45900}{}{una Guardia 1}
{46000}{}{una Guardia 2}
{46100}{}{una Guardia 3}
{46200}{}{una Guardia 4}
{46300}{}{un Soldato 1}
{46400}{}{un Soldato 2}
{46500}{}{un Soldato 3}
{46600}{}{un Soldato 4}
{46700}{}{il Sgt. Stark}
{46800}{}{Doc Andrew}
{46900}{}{un Barista}
{47000}{}{una Torretta Armata}
{47001}{}{Questa e' una torretta automatica armata con un Cannone a Doppio Plasma.}
{47100}{}{K-9 (base)}
{47200}{}{K-9 (stage 1)}
{47300}{}{K-9 (stage 2)}
{47400}{}{K-9 (stage 3)}
{47500}{}{K-9 (stage 4)}
{47600}{}{un Cybercane Generico}
{47700}{}{un Uovo di Wanamingo}
{47800}{}{una Guardia di Lo Pan}
{47900}{}{Marjorie}
{48000}{}{una Mitragliatrice}
{48100}{}{un Gecko Speciale}
{48200}{}{Grim Reaper}
{48300}{}{Frank Horrigan}
{48301}{}{La Guardia del Corpo del Presidente.}
