{100}{}{Uccidi le piante maligne che infestano il giardino di Hakunin.}
{110}{}{Ottieni della selce affinche' Mynoc possa affilare la tua lancia.}
{120}{}{Salva Smoke, il cane di Nagor, dalla selva.}
{130}{}{Recupera il GECK per Arroyo.}
{140}{}{Trova Vic il mercante.}
{200}{}{Libera Vic recuperando la sua radio dalla sua casa a Klamath e pagando Metzger.}
{201}{}{Scopri come Becky riesce a vendere il suo liquore ad un prezzo cosi' basso.}
{202}{}{Sabota il distillatore di Becky.}
{203}{}{Recupera il pezzo dell'automobile per Smitty.}
{204}{}{Riporta il medaglione ad Anna.}
{205}{}{Recupera i soldi di Rebecca da Fred.}
{206}{}{Recupera il libro di Rebecca da Derek.}
{207}{}{Consegna un pranzo a Smitty da parte di Mama.}
{208}{}{Lara vuole sapere a cosa stanno facendo la guardia nella chiesa.}
{209}{}{Ottieni il permesso da Metzger per una guerra fra bande.}
{210}{}{Trova un punto debole nella banda di Tyler che sta controllando la chiesa.}
{211}{}{Aiuta Lara ad attaccare la banda di Tyler.}
{300}{}{Rifornisci il distillatore.}
{301}{}{Salva Smiley il Trapper.}
{302}{}{Fa' la guardia ai brahmin.}
{303}{}{Ruba i brahmin.}
{304}{}{Uccidi il dio ratto.}
{305}{}{Salva Torr.}
{400}{}{Qualcosa di strano sta succedendo nella fattoria a nordest di Modoc. Indaga e fai rapporto a Jo.}
{401}{}{Cornelius ha perso il suo orologio da taschino d'oro. Trovalo e riportaglielo.}
{402}{}{Farrel vuole che tu ritrovi l'orologio da taschino d'oro di Cornelius. Trovalo e riportalo a Farrel.}
{403}{}{Jonny e' scomparso. Trovalo e riportalo a casa da Balthas.}
{404}{}{Jonny si trova nelle grotte degli Slag. Trova un modo per riportare Jonny a casa da Balthas.}
{405}{}{Farrel ha un problema con i roditori nel suo giardino. Rimuovi l'infestazione.}
{406}{}{Consegna il messaggio degli Slag a Jo di Modoc.}
{407}{}{Jo ha dei sospetti sugli Slag. Scopri l'origine dei cadaveri alla Fattoria Fantasma e scopri cos'e' successo a Karl.}
{408}{}{Vai al Den e di' a Karl che puo' tornare a casa.}
{409}{}{Fa' la guardia ai brahmin di Grisham.}
{500}{}{Trova un aratro per Mr. Smith.}
{501}{}{Consegna la valigetta di Moore a Mr. Bishop di New Reno.}
{502}{}{Consegna una dose di Jet al Dr. Troy.}
{503}{}{Risolvi il problema della centrale energetica di Gecko.}
{504}{}{Consegna l'olodisco di Lynette a Westin di NCR.}
{505}{}{Salva il marito di Amanda, Joshua.}
{506}{}{Consegna della Birra e del Liquore (10 bottiglie di ognuno) a Lydia.}
{507}{}{Consegna delle pinze (attrezzi) e una chiave inglese a Valerie.}
{508}{}{Esplora gli otto settori intorno a Gecko e torna da Stark.}
{509}{}{Entra a NCR e torna da Stark.}
{600}{}{Risolvi il problema della centrale energetica di Gecko.}
{601}{}{Ripara la centrale.}
{602}{}{Ottimizza la centrale.}
{603}{}{Recupera il Disco del Sistema Economico e consegnalo a McClure a Vault City.}
{604}{}{Recupera un Super Set di Attrezzi "Snap-Off" per Skeeter.}
{605}{}{Recupera un trasformatore di plasma trifasico per Skeeter.}
{606}{}{Trova Woody il ghoul per Percy. Prova al Den.}
{700}{}{}
{701}{}{Ripara il purificatore d'aria della miniera.}
{702}{}{Trova le persone scomparse per Marcus.}
{703}{}{Batti Francis in una sfida a braccio di ferro.}
{704}{}{Fa' evadere Manson e Franc dalla prigione.}
{705}{}{Fa' esplodere il purificatore d'aria della miniera.}
{706}{}{Devia piu' elettricita' verso la casa di Eric.}
{800}{}{Recupera la tua auto rubata.}
{801}{}{Scopri chi e' il responsabile dell'overdose di Richard Wright.}
{802}{}{     Sospetto: Jagged Jimmy J}
{803}{}{     Sospetto: Jules}
{804}{}{     Sospetto: Lil' Jesus Mordino}
{805}{}{     Sospetto: Renesco}
{806}{}{Trova un modo per entrare nel Dep. Militare Sierra.}
{807}{}{Snida Pretty Boy Lloyd, recupera i soldi rubati, e infliggigli una... punizione esemplare.}
{808}{}{Va' da Renesco e incassa i 1000$ per Mr. Salvatore.}
{809}{}{Fa' la guardia ad una transazione segreta che avverra' nel deserto.}
{810}{}{Trova degli inibitori di endorfina per creare un'antidoto contro il Jet.}
{811}{}{Fa' scoppiare la distilleria di Wright sotto la stazione ferroviaria.}
{812}{}{Uccidi Westin a NCR facendo in modo che non sembri un assassinio.}
{813}{}{Ammazza Carlson a NCR.}
{814}{}{Consegna dieci riviste Cat's Paw a Miss Kitty.}
{815}{}{Consegna una pistola laser a Eldridge.}
{816}{}{Consegna il pacco di Big Jesus a Ramirez presso le Stalle.}
{817}{}{Incassa il pizzo dai fratelli Corsican.}
{818}{}{Uccidi il Boss Salvatore per conto di Mordino.}
{900}{}{}
{1000}{}{}
{1100}{}{Recupera i componenti/Ottieni l'accesso al Vault 15.}
{1101}{}{"Prenditi cura" di Jack il poliziotto per Mira.}
{1102}{}{Completa il viaggio con i brahmin.}
{1103}{}{Recupera i documenti dal Dr. Henry.}
{1104}{}{Prova il siero mutagenico su un super-mutante. Prova a Broken Hills.}
{1105}{}{Elimina Mr. Bishop.}
{1106}{}{Consegna l'olodisco di Westin a Lynette di Vault City.}
{1107}{}{Recupera la mappa dai Ranger di NCR per Vortis lo schiavista.}
{1108}{}{Libera gli schiavi detenuti nel recinto degli schiavi per i Ranger.}
{1109}{}{Consegna il rapporto dell'Hubologista a AHS-9 a San Francisco.}
{1110}{}{Uccidi l'Hubologista per Merk.}
{1111}{}{Metti fine alle razzie di brahmin.}
{1200}{}{Ripara il computer del Vault 13.}
{1201}{}{Parla con Goris.}
{1300}{}{}
{1400}{}{Trova il chip per la scavatrice.}
{1401}{}{Placa la rissa nel bar.}
{1402}{}{Scopri chi ha sfregiato la prostituta.}
{1403}{}{Uccidi Frog Morton.}
{1500}{}{La petroliera ha bisogno di carburante.}
{1501}{}{Il computer di navigazione ha bisogno di un NavComp per funzionare.}
{1502}{}{Devi utilizzare un codice FOB per accedere al computer di navigazione.}
{1503}{}{Uccidi l'Imperatore Shi.}
{1504}{}{Gli Hubologisti hanno bisogno dei piani per un vertibird che si trovano a Navarro.}
{1505}{}{Ruba gli schemi tecnici per un vertibird dagli Shi.}
{1506}{}{Gli Hubologisti hanno bisogno di carburante per la loro astronave.}
{1507}{}{Uccidi Badger. In questo modo i nomadi che popolano la petroliera diventeranno seguaci dell'Hub.}
{1508}{}{Uccidi l'AHS-9.}
{1509}{}{Gli Shi hanno bisogno dei piani per un vertibird che si trovano a Navarro.}
{1510}{}{Ruba il progetto per un vertibird dagli Hubologisti.}
{1511}{}{Trova la ragazza di Badger nella stiva sotto la nave.}
{1512}{}{Dragon ti ha chiesto di battere Lo Pan - corpo a corpo.}
{1513}{}{Lo Pan ti ha chiesto di battere Dragon - corpo a corpo, se possibile.}
{1514}{}{Recupera la milza di Chip.}
{1515}{}{Prendi qualche Power-Armor rinforzata da Crockett.}
{1516}{}{Recupera i piani per un vertibird per la Confraternita d'Acciaio.}
{1600}{}{Occupati del Deathclaw.}
{1601}{}{Fix K-9.}
{1602}{}{Recupera il FOB dal comandante della base.}
{1700}{}{}
{1800}{}{}
{1900}{}{}
{2000}{}{}
{2100}{}{}
{2200}{}{}
{2300}{}{}
{2400}{}{}
{2500}{}{}
{2600}{}{}
{2700}{}{}
{2800}{}{}
{2900}{}{}
{3000}{}{}
{3100}{}{}
{3200}{}{Salva Chrissy.}
{3201}{}{Uccidi Darion.}
{3202}{}{Completa l'accordo con NCR.}
{3203}{}{Consegna l'olodisco spia alle autorita' di NCR.}
