{101}{}{}
{102}{}{Script Test 0}
{103}{}{Script Test 1}
{104}{}{Script Test 2}
{105}{}{Script Test 3}
{106}{}{Script Test 4}
{107}{}{Script Test 5}
{108}{}{un guerriero di Arroyo}
{109}{}{un abitante di Arroyo}
{110}{}{Mynoc}
{111}{}{l'Anziana di Arroyo}
{112}{}{Hakunin}
{113}{}{Porta}
{114}{}{Generico}
{115}{}{Baule}
{116}{}{Cassaforte}
{117}{}{un Brahmin}
{118}{}{una Pianta Sporigena}
{119}{}{}
{120}{}{uno Scorpione Minore}
{121}{}{una Mantide Minore}
{122}{}{un Deathclaw Minore}
{123}{}{Vaso}
{124}{}{Baule}
{125}{}{Grotte di Arroyo}
{126}{}{Porta di Legno}
{127}{}{Villaggio di Arroyo}
{128}{}{Ponte di Arroyo}
{129}{}{una Vecchia Porta}
{130}{}{Piastrella del Pavimento}
{131}{}{Piastrella del Pavimento}
{132}{}{Piastrella del Pavimento}
{133}{}{Piastrella del Pavimento}
{134}{}{Piastrella del Pavimento}
{135}{}{Porta}
{136}{}{un Tossicodipendente}
{137}{}{una Guardia}
{138}{}{un Paesano}
{139}{}{un Delinquente}
{140}{}{un Orfano}
{141}{}{Joey}
{142}{}{Flick}
{143}{}{una Guardia}
{144}{}{Petey}
{145}{}{Smitty}
{146}{}{Metzger}
{147}{}{Schiavista}
{148}{}{Tubby}
{149}{}{Anna}
{150}{}{Vic}
{151}{}{Frankie}
{152}{}{Rebecca}
{153}{}{Billy}
{154}{}{Sheila}
{155}{}{Mama}
{156}{}{un'Abitante del Villaggio}
{157}{}{Raid Schiavista}
{158}{}{il Carro Schiavista}
{159}{}{Den, Zona Commerciale}
{160}{}{Den, Zona Commerciale}
{161}{}{Den Zona Residenziale}
{162}{}{Tomba}
{163}{}{Tomba}
{164}{}{Tomba}
{165}{}{Ossa}
{166}{}{Diario}
{167}{}{Medaglione}
{168}{}{Distillatore}
{169}{}{Tomba}
{170}{}{Tavolo del Black Jack}
{171}{}{uno Schiavo}
{172}{}{Tavolo del Black Jack}
{173}{}{Porta}
{174}{}{Whiskey Bob}
{175}{}{Dadi}
{176}{}{Aldo}
{177}{}{Ardin}
{178}{}{un Bambino}
{179}{}{un Cittadino}
{180}{}{Maida}
{181}{}{Sajag}
{182}{}{Sally}
{183}{}{Sorridente}
{184}{}{Jenny}
{185}{}{Magro}
{186}{}{Torr}
{187}{}{uno dei due Dunton}
{188}{}{un Cittadino}
{189}{}{un Viaggiatore}
{190}{}{una Guardia di Vault City}
{191}{}{una Guardia di Vault City}
{192}{}{Steve}
{193}{}{Andrew}
{194}{}{una Guardia di Vault City}
{195}{}{il Dr. Troy}
{196}{}{un Cane Giallo}
{197}{}{Balthas}
{198}{}{Cornelius}
{199}{}{Davin}
{200}{}{Farrel}
{201}{}{Grisham}
{202}{}{Jo}
{203}{}{Jonny}
{204}{}{Karl}
{205}{}{Laddie}
{206}{}{Miria}
{207}{}{un Protettore}
{208}{}{Rose}
{209}{}{Vegeir}
{210}{}{Ed}
{211}{}{Harry}
{212}{}{la Sig.ra Smith}
{213}{}{Melinda}
{214}{}{una Trapper}
{215}{}{Signor Smith}
{216}{}{Skeeve}
{217}{}{il Proconsole Gregory}
{218}{}{Infermiera Phyllis}
{219}{}{Randal}
{220}{}{Sostanza Gelatinosa}
{221}{}{Barkus}
{222}{}{un'Abitante del Villaggio}
{223}{}{Stark}
{224}{}{una Guardia dell'Entrata del Vault}
{225}{}{il Vecchio Joe}
{226}{}{Connar}
{227}{}{Wallace}
{228}{}{Lynette}
{229}{}{McClure}
{230}{}{un Ratto Mutante}
{231}{}{Festus}
{232}{}{Gordon}
{233}{}{Hank}
{234}{}{Jeremy}
{235}{}{Bitorzoluto}
{236}{}{Skeeter}
{237}{}{Zomak}
{238}{}{Wooz}
{239}{}{Lenny}
{240}{}{una Guardia Ghoul}
{241}{}{un Lavoratore Ghoul}
{242}{}{un Lavoratore Luminoso}
{243}{}{una Guardia Ghoul}
{244}{}{un Robot}
{245}{}{un Cittadino Ghoul}
{246}{}{Script Mappa}
{247}{}{Script Mappa}
{248}{}{Script Mappa}
{249}{}{un Robot della Sicurezza}
{250}{}{un Robot Riparatore}
{251}{}{Olodisco}
{252}{}{Olodisco}
{253}{}{Olodisco}
{254}{}{Terminale}
{255}{}{Terminale}
{256}{}{Terminale}
{257}{}{Terminale}
{258}{}{Terminale}
{259}{}{Terminale}
{260}{}{Terminale}
{261}{}{Terminale}
{262}{}{Terminale}
{263}{}{Terminale}
{264}{}{Terminale}
{265}{}{Carta}
{266}{}{Il Soldato Dobbs}
{267}{}{BrainBot}
{268}{}{Ascensore}
{269}{}{Ascensore}
{270}{}{Cassaforte}
{271}{}{Cassaforte}
{272}{}{Tandi}
{273}{}{Trappola-Lancia}
{274}{}{Trappola-Lancia}
{275}{}{Trappola-Lancia}
{276}{}{Trappola-Lancia}
{277}{}{Trappola-Lancia}
{278}{}{Trappola-Lancia}
{279}{}{Trappola-Lancia}
{280}{}{Trappola-Lancia}
{281}{}{Trappola-Lancia}
{282}{}{Trappola-Lancia}
{283}{}{Trappola-Lancia}
{284}{}{Trappola-Lancia}
{285}{}{Trappola-Lancia}
{286}{}{Trappola-Lancia}
{287}{}{Trappola-Lancia}
{288}{}{Trappola-Lancia}
{289}{}{Grotta Fantasma Uno}
{290}{}{Grotta Fantasma Due}
{291}{}{Fattoria Fantasma}
{292}{}{Campo dei Brahmin di Modoc}
{293}{}{Giardino di Modoc}
{294}{}{Locanda di Modoc}
{295}{}{Modoc Centrale}
{296}{}{Il letamaio di Modoc}
{297}{}{Pozzo di Modoc}
{298}{}{Ncr Area 2}
{299}{}{Giardini di Arroyo}
{300}{}{Gecko}
{301}{}{Fiore di Broc}
{302}{}{Radice di Xander}
{303}{}{un Brahmin}
{304}{}{la Moglie di Balthas}
{305}{}{un Brahmin}
{306}{}{un Cane Selvatico}
{307}{}{Rocce}
{308}{}{Rocce}
{309}{}{Cassaforte a Muro}
{310}{}{Sacchetto di Denaro}
{311}{}{Bagno}
{312}{}{Scatola}
{313}{}{Jordan}
{314}{}{Zia Morlis}
{315}{}{Lucas}
{316}{}{Feargus}
{317}{}{Pozzo}
{318}{}{Gruthar}
{319}{}{Script Mappa}
{320}{}{Skeeter}
{321}{}{Nagor}
{322}{}{Smoke}
{323}{}{Ncr Area 1}
{324}{}{Ncr Area 3}
{325}{}{Ncr Area 4}
{326}{}{Ingresso Area Ncr}
{327}{}{Mikey}
{328}{}{Scatola di Mikey}
{329}{}{Emettitore}
{330}{}{Emettitore}
{331}{}{Emettitore}
{332}{}{Emettitore}
{333}{}{Emettitore}
{334}{}{Emettitore}
{335}{}{Emettitore}
{336}{}{Emettitore}
{337}{}{Emettitore}
{338}{}{Emettitore}
{339}{}{Emettitore}
{340}{}{Campo di Forza}
{341}{}{Campo di Forza}
{342}{}{Campo di Forza}
{343}{}{Campo di Forza}
{344}{}{Campo di Forza}
{345}{}{Campo di Forza}
{346}{}{Campo di Forza}
{347}{}{Campo di Forza}
{348}{}{Campo di Forza}
{349}{}{Campo di Forza}
{350}{}{Campo di Forza}
{351}{}{Sirena}
{352}{}{Buster}
{353}{}{Scaffale}
{354}{}{Scaffale}
{355}{}{Scaffale}
{356}{}{una Predone}
{357}{}{un Contadino}
{358}{}{un Mercante}
{359}{}{una Guardia}
{360}{}{un Cliente del Rawhide}
{361}{}{Pavimento}
{362}{}{Trappola al Plasma}
{363}{}{Trappola al Plasma}
{364}{}{Terminale}
{365}{}{Bacheca degli Annunci}
{366}{}{Cancello}
{367}{}{Sostanza Gelatinosa}
{368}{}{Porta}
{369}{}{Porta}
{370}{}{}
{371}{}{}
{372}{}{Script Mappa}
{373}{}{Script Mappa}
{374}{}{Script Mappa}
{375}{}{Script Mappa}
{376}{}{Script Mappa}
{377}{}{Script Mappa}
{378}{}{Script Mappa}
{379}{}{Script Mappa}
{380}{}{Script Mappa}
{381}{}{Script Mappa}
{382}{}{Script Mappa}
{383}{}{Script Mappa}
{384}{}{Script Mappa}
{385}{}{Script Mappa}
{386}{}{Script Mappa}
{387}{}{Script Mappa}
{388}{}{Script Mappa}
{389}{}{Script Mappa}
{390}{}{Script Mappa}
{391}{}{Script Mappa}
{392}{}{Script Mappa}
{393}{}{Script Mappa}
{394}{}{Script Mappa}
{395}{}{Script Mappa}
{396}{}{Distillatore}
{397}{}{un Cliente del Bar}
{398}{}{un Cliente del Bar}
{399}{}{Vortis}
{400}{}{un'Inserviente della Bath House}
{401}{}{uno Schiavo}
{402}{}{Scorpione}
{403}{}{un Brahmin}
{404}{}{Automobile}
{405}{}{Tavolo}
{406}{}{Script Mappa}
{407}{}{Script Mappa}
{408}{}{Script Mappa}
{409}{}{Script Mappa}
{410}{}{Corvega}
{411}{}{Script Mappa}
{412}{}{Porta in Metallo}
{413}{}{Script Mappa}
{414}{}{Script Mappa}
{415}{}{Script Mappa}
{416}{}{Cassaforte}
{417}{}{Cassaforte}
{418}{}{Cassaforte}
{419}{}{Ratch}
{420}{}{un Pugile}
{421}{}{Pete McKneely}
{422}{}{Evan Hollyfeld}
{423}{}{Il Masticatore}
{424}{}{Scienziato}
{425}{}{Merk}
{426}{}{Ventilatore}
{427}{}{uno Spacciatore di Droga}
{428}{}{un Cliente del Casino'}
{429}{}{un Pappone}
{430}{}{un Drogato}
{431}{}{Mobili}
{432}{}{Pavimento}
{433}{}{Terreno}
{434}{}{Olodisco}
{435}{}{Lenny}
{436}{}{Scatola}
{437}{}{una Prostituta}
{438}{}{uno Schiavo}
{439}{}{Rico}
{440}{}{un'Attrice Porno}
{441}{}{un'Assistente}
{442}{}{Script Mappa}
{443}{}{Lupo}
{444}{}{Generatore}
{445}{}{Porta}
{446}{}{Super mutanti}
{447}{}{un Uomo di Salvatore}
{448}{}{un Uomo di Bishop}
{449}{}{un Uomo di Mordino}
{450}{}{uno dei Figli di Wright}
{451}{}{un Buttafuori del Casino'}
{452}{}{Mira}
{453}{}{New Reno - Via della Vergine}
{454}{}{New Reno - Seconda Strada}
{455}{}{New Reno - Viale Commerciale}
{456}{}{New Reno - Lato Est}
{457}{}{New Reno - Scuderie}
{458}{}{New Reno - Officina di smontaggio}
{459}{}{New Reno Gologtha}
{460}{}{New Reno - Sotterranei dei Bishop}
{461}{}{Olodisco}
{462}{}{Olodisco}
{463}{}{Olodisco}
{464}{}{Olodisco}
{465}{}{Olodisco}
{466}{}{una Guardia}
{467}{}{Carretto da Minatore}
{468}{}{Melchior}
{469}{}{una Bestia Mutante}
{470}{}{Melma FEV}
{471}{}{il Capitano delle Guardie}
{472}{}{un Guardiano degli Schiavi}
{473}{}{uno dei Cuccioli di Melchior}
{474}{}{una Guardia degli Schiavisti}
{475}{}{Porta}
{476}{}{Terminale}
{477}{}{Slot Machine}
{478}{}{un Bambino}
{479}{}{Sheb}
{480}{}{una Guardia}
{481}{}{Emettitore}
{482}{}{Campo di Forza}
{483}{}{Sulik}
{484}{}{il Dr. Henry}
{485}{}{una Guardia}
{486}{}{Attacco delle guardie di Carlson}
{487}{}{una Guardia di Carlson addetta al Cancello}
{488}{}{un Prigioniero}
{489}{}{un Prigioniero}
{490}{}{un Cittadino}
{491}{}{un Assistente dell'Emporio}
{492}{}{una Guardia del Bancone}
{493}{}{un Lavoratore Ghoul}
{494}{}{un Luminoso}
{495}{}{una Guardia Ghoul}
{496}{}{un Robot}
{497}{}{un Ghoul}
{498}{}{un Adoratore}
{499}{}{Harold}
{500}{}{un Ufficiale}
{501}{}{Toto}
{502}{}{Dorothy}
{503}{}{un Paesano}
{504}{}{una Guardia Ghoul}
{505}{}{una Guardia Ghoul}
{506}{}{Gond}
{507}{}{Duppo}
{508}{}{Roba}
{509}{}{Bob}
{510}{}{una Ragazza del Casino'}
{511}{}{una Ragazza del Casino'}
{512}{}{Palla Magica 8}
{513}{}{un Brahmin}
{514}{}{Slot Machine}
{515}{}{il Vecchio McGee}
{516}{}{Gioco delle Tre Carte}
{517}{}{Algernon}
{518}{}{Bill}
{519}{}{una Guardia del Corpo di Bishop}
{520}{}{John Bishop}
{521}{}{Macchina da Casino'}
{522}{}{un "Chop Shop Boy"}
{523}{}{Chris Wright}
{524}{}{Cody}
{525}{}{uno dei Fratelli Corsican}
{526}{}{Eldridge}
{527}{}{Ethyl Wright}
{528}{}{Padre Tully}
{529}{}{HumperdumperDIDO}
{530}{}{Lil' Jesus Mordino}
{531}{}{Jimmy J, lo Sfregiato}
{532}{}{Keith Wright}
{533}{}{Lee Anne Bishop}
{534}{}{"Pretty Boy" Lloyd}
{535}{}{Mason}
{536}{}{una Guardia}
{537}{}{Myron}
{538}{}{Nikki}
{539}{}{Orville Wright}
{540}{}{Boss}
{541}{}{Renesco "the Rocket-Man"}
{542}{}{Marjorie Reed}
{543}{}{il Boss Salvatore}
{544}{}{Stuart Little}
{545}{}{T-Ray}
{546}{}{una Puttana}
{547}{}{un Bambino degli Wright}
{548}{}{un Poliziotto di NCR}
{549}{}{Oswald}
{550}{}{Dusty}
{551}{}{Jules}
{552}{}{Miss Kitty}
{553}{}{un Barista}
{554}{}{il Vicesceriffo Karl}
{555}{}{Porta della Cella}
{556}{}{Big Jesus Mordino}
{557}{}{Hoss}
{558}{}{Siero Mutagenico}
{559}{}{Scatola}
{560}{}{Scatola}
{561}{}{Scatola}
{562}{}{Scatola}
{563}{}{Il Dottor Jubilee}
{564}{}{Porta}
{565}{}{Porta}
{566}{}{Libreria}
{567}{}{lo Sceriffo Dumont}
{568}{}{Elise}
{569}{}{un Bracciante del Ranch}
{570}{}{Felix}
{571}{}{Westin}
{572}{}{Rondo}
{573}{}{Robocane}
{574}{}{Scale}
{575}{}{Hal}
{576}{}{Gunther}
{577}{}{un Brahmin}
{578}{}{il Capo della Carovana}
{579}{}{un Guidatore della Carovana}
{580}{}{una Guardia della Carovana}
{581}{}{una Predone}
{582}{}{un Gangster}
{583}{}{un Cacciatore}
{584}{}{un Cacciatore}
{585}{}{Ranger}
{586}{}{un Mercenario}
{587}{}{un Mercenario}
{588}{}{una Predone}
{589}{}{un Guidatore della Carovana}
{590}{}{una Guardia della Carovana}
{591}{}{una Guardia di Pattuglia}
{592}{}{il Capitano della Pattuglia}
{593}{}{una Contadina}
{594}{}{un Brahmin}
{595}{}{un Brahmin}
{596}{}{un Viaggiatore}
{597}{}{una Guardia di Pattuglia}
{598}{}{il Capitano della Pattuglia}
{599}{}{una Guardia di Pattuglia}
{600}{}{il Capitano della Pattuglia}
{601}{}{un Pastore di Brahmin}
{602}{}{un Ladro di Bestiame}
{603}{}{un Abusivo}
{604}{}{un Abolizionista}
{605}{}{una Contrabbandiera}
{606}{}{Super mutanti}
{607}{}{un Pescatore}
{608}{}{Schiavista}
{609}{}{una Trapper}
{610}{}{il figlio di Carlson}
{611}{}{Carlson}
{612}{}{}
{613}{}{l'Agente Jack}
{614}{}{l'Illuminata}
{615}{}{Porta}
{616}{}{Computer}
{617}{}{un Brahmin}
{618}{}{Deathclaw}
{619}{}{Griglia d'Uscita}
{620}{}{Computer}
{621}{}{Feargus}
{622}{}{Ariel}
{623}{}{Fannie Mae}
{624}{}{Computer Terminal}
{625}{}{Dalia}
{626}{}{Dar}
{627}{}{Dave}
{628}{}{Gordon}
{629}{}{Cartello "Chiuso per fallimento"}
{630}{}{Macchinari di controllo del reattore}
{631}{}{Jimmy}
{632}{}{Joseph}
{633}{}{Matt}
{634}{}{}
{635}{}{Script Mappa}
{636}{}{Script mappa V13}
{637}{}{Sandy}
{638}{}{Scatola}
{639}{}{Thearn}
{640}{}{Scatola}
{641}{}{Scatola}
{642}{}{Valdis}
{643}{}{Computer Terminal}
{644}{}{Armadietto Metallico}
{645}{}{Contenitore}
{646}{}{una Guardia Deathclaw}
{647}{}{Goris}
{648}{}{Scatola}
{649}{}{Armadietto Metallico}
{650}{}{un Imbroglione}
{651}{}{Script mappa V15}
{652}{}{Phil}
{653}{}{Bill}
{654}{}{Macellaio}
{655}{}{Dalia}
{656}{}{John}
{657}{}{Jones}
{658}{}{Karla}
{659}{}{V15 Secrect entrance map}
{660}{}{Rebecca}
{661}{}{Porta}
{662}{}{Deathclaw}
{663}{}{Roberta}
{664}{}{Sara}
{665}{}{Zeke}
{666}{}{un Brahmin}
{667}{}{Porta di Legno}
{668}{}{Chrissy}
{669}{}{Darion}
{670}{}{una Guardia di Darion}
{671}{}{il Cane di Darion}
{672}{}{Cassidy}
{673}{}{Pozzo}
{674}{}{un Ratto-talpa}
{675}{}{Pezzo di Brahmin}
{676}{}{un Brahmin}
{677}{}{Porta dell'Ascensore}
{678}{}{un Cane}
{679}{}{un Ratto}
{680}{}{Macchia di Sole}
{681}{}{Bess}
{682}{}{Scatola}
{683}{}{una Croupier}
{684}{}{una Guardia del Vault 15}
{685}{}{uno Slag}
{686}{}{Tappeto}
{687}{}{un Bambino}
{688}{}{Aileen}
{689}{}{una Guardia}
{690}{}{Doc Holliday}
{691}{}{un Seguace}
{692}{}{un Seguace}
{693}{}{una Donna}
{694}{}{Francis}
{695}{}{Frank}
{696}{}{un Ghoul}
{697}{}{Liz}
{698}{}{un Uomo}
{699}{}{Manson}
{700}{}{Marcus}
{701}{}{un Minatore}
{702}{}{Mutante}
{703}{}{Bill}
{704}{}{Phil}
{705}{}{Steve}
{706}{}{il Supervisore}
{707}{}{Zaius}
{708}{}{Jacob}
{709}{}{Kit di chimica}
{710}{}{Ogg. Scena}
{711}{}{Porta}
{712}{}{Computer}
{713}{}{Chad}
{714}{}{una Pianta Sporigena}
{715}{}{}
{716}{}{un Radscorpione}
{717}{}{}
{718}{}{un Guerriero}
{719}{}{una Cannibale}
{720}{}{un Reietto}
{721}{}{un Uomo di Chiesa}
{722}{}{un Nomade}
{723}{}{un Senzatetto}
{724}{}{una Donna Bandito}
{725}{}{un Ladro}
{726}{}{un Rapinatore}
{727}{}{Schiavista}
{728}{}{uno Schiavo}
{729}{}{un Partecipante al Party}
{730}{}{Mantide}
{731}{}{un Brahmin}
{732}{}{un Cane Selvatico}
{733}{}{Computer}
{734}{}{Computer}
{735}{}{Computer Terminal}
{736}{}{Computer}
{737}{}{Generatore Elettrico}
{738}{}{Campo di Forza}
{739}{}{un Contadino}
{740}{}{Emettitore}
{741}{}{Porta del Vault}
{742}{}{Porta di Sicurezza}
{743}{}{Incontro con Bess}
{744}{}{Bess}
{745}{}{un Brahmin}
{746}{}{Angela Bishop}
{747}{}{Tommy "Palle d’Acciaio"}
{748}{}{Sicura}
{749}{}{Sicura}
{750}{}{Sicura}
{751}{}{Sicura}
{752}{}{Tomba}
{753}{}{Credenza}
{754}{}{Tomba}
{755}{}{Distillatore}
{756}{}{Ramirez}
{757}{}{Mappa incontro casuale - Caverna 1}
{758}{}{Scatola}
{759}{}{Porta}
{760}{}{Mappa incontro casuale - Caverna 2}
{761}{}{Mappa incontro casuale - Caverna 3}
{762}{}{Mappa incontro casuale - Caverna 4}
{763}{}{Mappa incontro casuale - Caverna 2}
{764}{}{Porta}
{765}{}{Script Mappa}
{766}{}{Botola}
{767}{}{Cassaforte}
{768}{}{Stanza}
{769}{}{Thomas Moore}
{770}{}{Porta}
{771}{}{Armadietto}
{772}{}{Tombino}
{773}{}{Tomba}
{774}{}{la Guardia del Magazzino}
{775}{}{Script Mappa}
{776}{}{Script Mappa}
{777}{}{Brahmin Pazzo}
{778}{}{Hakeswill}
{779}{}{Redding - Centro}
{780}{}{Script Mappa}
{781}{}{Script Mappa}
{782}{}{Lou}
{783}{}{Artu'}
{784}{}{Robin}
{785}{}{Bedemir}
{786}{}{Sir Lancillotto}
{787}{}{Galahad}
{788}{}{Ben Wade}
{789}{}{Athabaska Dick}
{790}{}{la Vedova Rooney}
{791}{}{un Paesano}
{792}{}{Stanwell}
{793}{}{Savinelli}
{794}{}{Marge}
{795}{}{Madame Modjeska}
{796}{}{James Hoffy}
{797}{}{Script Mappa}
{798}{}{Patsy}
{799}{}{Concorde}
{800}{}{Eric}
{801}{}{John}
{802}{}{Joshua}
{803}{}{Scala}
{804}{}{la Testa Enorme}
{805}{}{L'Eroe Nero}
{806}{}{l'Eroina Rossa}
{807}{}{Set}
{808}{}{Tandi}
{809}{}{un Eroe Bianco}
{810}{}{un Eroe Bianco}
{811}{}{un'Eroina Rossa}
{812}{}{Scatola}
{813}{}{Scatola}
{814}{}{Scatola}
{815}{}{Script Mappa}
{816}{}{Ratto Vorpal}
{817}{}{un Cane}
{818}{}{il Sergente Istruttore}
{819}{}{una Guardia}
{820}{}{un Tecnico}
{821}{}{il Comandante}
{822}{}{Chris}
{823}{}{il Furiere}
{824}{}{una Guardia}
{825}{}{Tomba}
{826}{}{Automobile}
{827}{}{Automobile}
{828}{}{Tomba}
{829}{}{il Figuro Incappucciato}
{830}{}{un Compratore di Bestiame}
{831}{}{Script Mappa}
{832}{}{Straniero Misterioso}
{833}{}{Brahmin Pazzo}
{834}{}{un Membro della Yakuza}
{835}{}{una Selvaggia}
{836}{}{un Cane}
{837}{}{Scatola}
{838}{}{un Membro della Pattuglia}
{839}{}{un Viaggiatore}
{840}{}{Smoke}
{841}{}{un Commerciante}
{842}{}{uno Sciacallo}
{843}{}{un Mercante}
{844}{}{un Contadino}
{845}{}{Tempio di Arroyo}
{846}{}{un Lavoratore del Porto}
{847}{}{un Contadino}
{848}{}{una Guardia}
{849}{}{Cameron}
{850}{}{Porta}
{851}{}{Klint}
{852}{}{Coltivazioni}
{853}{}{un Tecnico del Lab. Shi}
{854}{}{un Bambino}
{855}{}{un Ghoul}
{856}{}{il Dr. Fung}
{857}{}{Jul}
{858}{}{Kerith}
{859}{}{Baule}
{860}{}{un Ghoul}
{861}{}{}
{862}{}{}
{863}{}{una Cercatrice}
{864}{}{un Membro della Gang}
{865}{}{il Capo Nomade}
{866}{}{una Hubologista}
{867}{}{un Pazzo}
{868}{}{un Cacciatore di Concessioni}
{869}{}{una Cannibale}
{870}{}{lo Sciamano Nomade}
{871}{}{un Razziatore}
{872}{}{un Furfante}
{873}{}{un Eremita}
{874}{}{}
{875}{}{il Capo della Carovana}
{876}{}{il Capo della Carovana}
{877}{}{il Capo della Carovana}
{878}{}{il Capo della Carovana}
{879}{}{il Capo della Carovana}
{880}{}{il Capo della Carovana}
{881}{}{il Capo della Carovana}
{882}{}{il Capo della Carovana}
{883}{}{il Capo della Carovana}
{884}{}{la Moglie del Contadino}
{885}{}{il Figlio del Contadino}
{886}{}{una Colona}
{887}{}{la Moglie del Colono}
{888}{}{Il Figlio del Colone}
{889}{}{il Capo della Carovana}
{890}{}{}
{891}{}{}
{892}{}{}
{893}{}{}
{894}{}{un Soldato dell'Enclave}
{895}{}{un Capitano di Merc}
{896}{}{un Predone di Merc}
{897}{}{"Ombra-che-Cammina"}
{898}{}{Sicura}
{899}{}{}
{900}{}{}
{901}{}{}
{902}{}{Scatola}
{903}{}{il Presidente Richardson}
{904}{}{Obice}
{905}{}{Porta}
{906}{}{un cucciolo di Deathclaw}
{907}{}{Dan il Pericoloso}
{908}{}{Dottor Johnson}
{909}{}{lo Sceriffo Marion}
{910}{}{il Sindaco Ascorti}
{911}{}{Nording}
{912}{}{Velani}
{913}{}{Ferndown}
{914}{}{Dragon}
{915}{}{uno Stalliere}
{916}{}{un Commerciante}
{917}{}{un Paesano}
{918}{}{uno Slag}
{919}{}{uno Slag}
{920}{}{Lo Pan}
{921}{}{Tasso}
{922}{}{Josh}
{923}{}{Caminetto}
{924}{}{Bette}
{925}{}{Mai Da Chiang}
{926}{}{Porta}
{927}{}{Porta}
{928}{}{Emettitore}
{929}{}{il Dio Ratto}
{930}{}{}
{931}{}{Kaga}
{932}{}{Kaga}
{933}{}{Kaga}
{934}{}{Kaga}
{935}{}{Kaga}
{936}{}{un Cacciatore di Taglie}
{937}{}{Computer}
{938}{}{Computer}
{939}{}{Computer}
{940}{}{Darrow}
{941}{}{Farrel}
{942}{}{un Cliente del Bar}
{943}{}{un Cittadino del Vault}
{944}{}{un Servo del Vault}
{945}{}{Condotto di ventilazione}
{946}{}{Charlie}
{947}{}{Pannello di controllo del refrigerante}
{948}{}{Poo}
{949}{}{Grant}
{950}{}{Emettitore}
{951}{}{Emettitore}
{952}{}{Computer Terminal}
{953}{}{il Computer Imperatore v8.8}
{954}{}{il Vicepresidente Bird}
{955}{}{Martin}
{956}{}{Ken Lee}
{957}{}{il Ser. Granite}
{958}{}{Frank Horrigan}
{959}{}{Script Mappa}
{960}{}{Script Mappa}
{961}{}{Porta}
{962}{}{Porta}
{963}{}{Porta}
{964}{}{Corda}
{965}{}{Emettitore}
{966}{}{il Dr. Curling}
{967}{}{Bacheca degli Annunci}
{968}{}{un Ratto-talpa}
{969}{}{la Segretaria del Presidente}
{970}{}{Tom Murray}
{971}{}{Porta robusta}
{972}{}{un Paesano}
{973}{}{Vault City - Area del Consiglio}
{974}{}{Purificatore d'aria}
{975}{}{Rocce}
{976}{}{Giocatore d'Azzardo}
{977}{}{Spatial Script}
{978}{}{SCCheat}
{979}{}{un Prigioniero}
{980}{}{un Cittadino}
{981}{}{una Guardia}
{982}{}{Scienziato}
{983}{}{Terminale}
{984}{}{}
{985}{}{}
{986}{}{Emettitore}
{987}{}{Porta Blindata}
{988}{}{Porta Blindata}
{989}{}{Scorte di Darrow}
{990}{}{Porta}
{991}{}{un Super Mega Mutante}
{992}{}{il Dr. Jing Tie Gahng}
{993}{}{Grundel}
{994}{}{Melchior Jr.}
{995}{}{Scanner della Retina}
{996}{}{Porta dell'Ascensore}
{997}{}{Recettore Cibernetico}
{998}{}{Parete}
{999}{}{Script Mappa}
{1000}{}{Scorte di Farrel}
{1001}{}{Scorte di Harry}
{1002}{}{Scatola}
{1003}{}{Scatola}
{1004}{}{Derek}
{1005}{}{un Amico di Tubby}
{1006}{}{Giocatore d'Azzardo}
{1007}{}{uno Schiavo}
{1008}{}{una Guardia}
{1009}{}{Schiavista}
{1010}{}{Lara}
{1011}{}{Tyler}
{1012}{}{Mark}
{1013}{}{Bacheca degli Annunci}
{1014}{}{Schiavista}
{1015}{}{Schiavista}
{1016}{}{Fred}
{1017}{}{Scatola}
{1018}{}{Scatola}
{1019}{}{Scatola}
{1020}{}{Bagagliaio}
{1021}{}{Porta di Sicurezza}
{1022}{}{Computer Terminal}
{1023}{}{Computer Terminal}
{1024}{}{Computer Terminal}
{1025}{}{Lao Chou}
{1026}{}{}
{1027}{}{Condotto di ventilazione}
{1028}{}{Script Mappa}
{1029}{}{Cadavere}
{1030}{}{Cavi scoperti}
{1031}{}{Scatola}
{1032}{}{uno Schiavo}
{1033}{}{uno Schiavo}
{1034}{}{Schiavista}
{1035}{}{Chip}
{1036}{}{Reattore}
{1037}{}{Computer del Reattore}
{1038}{}{il Cassiere}
{1039}{}{Cassetta dei Contanti}
{1040}{}{un Wanamingo}
{1041}{}{un Cliente del Bar}
{1042}{}{un Cliente del Bar}
{1043}{}{Porta della Cella}
{1044}{}{Suze}
{1045}{}{il Capitano Ron Meyers}
{1046}{}{Porta del Recinto}
{1047}{}{Miniera di Wanamingo}
{1048}{}{Ingresso della Miniera di Wanamingo}
{1049}{}{Frog Morton}
{1050}{}{Dave H.}
{1051}{}{Porta}
{1052}{}{Porta}
{1053}{}{"Vomitino" Charlie}
{1054}{}{Dipinto}
{1055}{}{Script Mappa}
{1056}{}{un Barista}
{1057}{}{Scatola}
{1058}{}{Auto-Doc}
{1059}{}{}
{1060}{}{Galleria Mineraria}
{1061}{}{un Robot}
{1062}{}{}
{1063}{}{Script Mappa}
{1064}{}{Script Mappa}
{1065}{}{Lydia}
{1066}{}{}
{1067}{}{Harry l'Addetto al Razzo}
{1068}{}{AHS-7}
{1069}{}{Crockett}
{1070}{}{Amanda}
{1071}{}{Joshua}
{1072}{}{Valerie}
{1073}{}{Sistema Didattico}
{1074}{}{Cassa}
{1075}{}{il Tipo che Piscia}
{1076}{}{Curtis}
{1077}{}{Mark}
{1078}{}{Computer}
{1079}{}{AHS-9}
{1080}{}{una Guardia}
{1081}{}{Mucchio di rocce}
{1082}{}{Porta}
{1083}{}{una Guardia}
{1084}{}{una Guardia}
{1085}{}{Porta}
{1086}{}{Manifesto di un Ricercato}
{1087}{}{il Dr. Wong}
{1088}{}{Tavolo}
{1089}{}{Porta}
{1090}{}{una Punk}
{1091}{}{una Punk}
{1092}{}{Ryan}
{1093}{}{Scatola}
{1094}{}{}
{1095}{}{Tombino}
{1096}{}{Script Mappa}
{1097}{}{Scala}
{1098}{}{Sacco da Pugile}
{1099}{}{Porta}
{1100}{}{Alarm}
{1101}{}{Piastrella del Pavimento}
{1102}{}{Piastrella del Pavimento}
{1103}{}{Piastrella del Pavimento}
{1104}{}{Piastrella del Pavimento}
{1105}{}{Piastrella del Pavimento}
{1106}{}{Piastrella del Pavimento}
{1107}{}{Piastrella del Pavimento}
{1108}{}{Piastrella del Pavimento}
{1109}{}{Piastrella del Pavimento}
{1110}{}{Piastrella del Pavimento}
{1111}{}{Piastrella del Pavimento}
{1112}{}{Piastrella del Pavimento}
{1113}{}{Piastrella del Pavimento}
{1114}{}{Piastrella del Pavimento}
{1115}{}{Emettitore}
{1116}{}{Emettitore}
{1117}{}{Emettitore}
{1118}{}{Campo di Forza}
{1119}{}{Campo di Forza}
{1120}{}{Campo di Forza}
{1121}{}{una Hubologista}
{1122}{}{Computer}
{1123}{}{Porta del Bunker}
{1124}{}{Cancello}
{1125}{}{Scatola}
{1126}{}{uno dei Fratelli Morton}
{1127}{}{Emettitore}
{1128}{}{Emettitore}
{1129}{}{Emettitore}
{1130}{}{Script Mappa}
{1131}{}{Chet}
{1132}{}{Script Mappa}
{1133}{}{Vertibird}
{1134}{}{una delle Guardie di Salvatore}
{1135}{}{una delle Guardie di Salvatore}
{1136}{}{un Soldato}
{1137}{}{un Soldato}
{1138}{}{Cassa}
{1139}{}{Signor Handy}
{1140}{}{una delle Guardie di Salvatore}
{1141}{}{Spacial Script}
{1142}{}{Porta}
{1143}{}{Porta}
{1144}{}{Porta}
{1145}{}{}
{1146}{}{Script Mappa}
{1147}{}{uno Schiavo}
{1148}{}{un Cittadino del Vault}
{1149}{}{Porta}
{1150}{}{un Pugile}
{1151}{}{Porta del Vault}
{1152}{}{Xarn}
{1153}{}{Raul}
{1154}{}{Quincy}
{1155}{}{il Furiere}
{1156}{}{una Guardia}
{1157}{}{K-9}
{1158}{}{Dottor Schreber}
{1159}{}{un Tecnico}
{1160}{}{un Tecnico}
{1161}{}{una Guardia}
{1162}{}{una Guardia}
{1163}{}{una Guardia}
{1164}{}{una Guardia}
{1165}{}{un Tecnico}
{1166}{}{un Tecnico}
{1167}{}{un Tecnico}
{1168}{}{un Tecnico}
{1169}{}{Frana}
{1170}{}{un Soldato di Pattuglia dell'Enclave}
{1171}{}{Porta Blindata}
{1172}{}{Script Mappa}
{1173}{}{Script Mappa}
{1174}{}{Script Mappa}
{1175}{}{Script Mappa}
{1176}{}{Script Mappa}
{1177}{}{Script Mappa}
{1178}{}{un Robot della Sicurezza}
{1179}{}{Cassetta delle elemosine}
{1180}{}{Cadavere}
{1181}{}{Scatola}
{1182}{}{Scatola}
{1183}{}{Scatola}
{1184}{}{una Guardia della Carovana}
{1185}{}{un Guidatore della Carovana}
{1186}{}{l'Annunciatore}
{1187}{}{la Ragazza del Ring}
{1188}{}{un Pugile}
{1189}{}{Porta}
{1190}{}{l'Imbroglione}
{1191}{}{Olodisco}
{1192}{}{Olodisco}
{1193}{}{Olodisco}
{1194}{}{Note}
{1195}{}{Polpetta}
{1196}{}{Cat's Paw Magazine #5}
{1197}{}{Mappa dei Predoni}
{1198}{}{Cane Paria}
{1199}{}{Sirena}
{1200}{}{Miniera}
{1201}{}{Pit}
{1202}{}{Cal}
{1203}{}{Magro}
{1204}{}{Jenna}
{1205}{}{}
{1206}{}{}
{1207}{}{Emettitore}
{1208}{}{Emettitore}
{1209}{}{Emettitore}
{1210}{}{Emettitore}
{1211}{}{Libro degli Indizi per Fallout 2}
{1212}{}{}
{1213}{}{}
{1214}{}{una Guardia}
{1215}{}{una Cercatrice}
{1216}{}{un Contrabbandiere}
{1217}{}{}
{1218}{}{Dan}
{1219}{}{un Comico da Strapazzo}
{1220}{}{un Cantante di Strada}
{1221}{}{Script Mappa}
{1222}{}{}
{1223}{}{Tomba}
{1224}{}{"Becchino" Willie}
{1225}{}{Computer d'accesso senza chiave}
{1226}{}{Porta d'accesso senza chiave}
{1227}{}{Computer}
{1228}{}{Kohl}
{1229}{}{un Bambino}
{1230}{}{Biscotto}
{1231}{}{Torretta}
{1232}{}{Brian}
{1233}{}{Generatore}
{1234}{}{Console}
{1235}{}{una Formica Gigante}
{1236}{}{una Formica Gigante}
{1237}{}{Porta}
{1238}{}{}
{1239}{}{Scatola}
{1240}{}{Eric}
{1241}{}{}
{1242}{}{Scatola}
{1243}{}{uno Scorpione Gigante}
{1244}{}{Jane}
{1245}{}{}
{1246}{}{Script Mappa}
{1247}{}{Dermal Pip Boy}
{1248}{}{un Cuccioletto}
{1249}{}{Rattray}
{1250}{}{un Consorte}
{1251}{}{una Guardia di Lo Pan}
{1252}{}{Script Mappa}
{1253}{}{Porta}
{1254}{}{un Cane Cybernetico}
{1255}{}{Luke}
{1256}{}{Joshua}
{1257}{}{Cancello}
{1258}{}{Matt}
{1259}{}{Porta}
{1260}{}{una Guardia}
{1261}{}{Porta}
{1262}{}{Computer}
{1263}{}{Terminale}
{1264}{}{Torretta}
{1265}{}{Chuck Stodgers}
{1266}{}{}
{1267}{}{Terminale}
{1268}{}{un Criminale}
{1269}{}{un Imbroglione}
{1270}{}{}
{1271}{}{un Contadino}
{1272}{}{Il Fiore di Lavanda}
{1273}{}{un Radscorpione}
{1274}{}{il Professore}
{1275}{}{Scatola}
{1276}{}{Scatola}
{1277}{}{Seymour}
{1278}{}{John Sullivan}
{1279}{}{Bitorzoluto}
{1280}{}{}
{1281}{}{}
{1282}{}{}
{1283}{}{una Guardia}
{1284}{}{}
{1285}{}{}
{1286}{}{Typhon}
{1287}{}{una Guardia del Corpo}
{1288}{}{Script Mappa}
{1289}{}{Armadietto}
{1290}{}{Pozzo}
{1291}{}{Micky}
{1292}{}{Torretta}
{1293}{}{un Vecchio Ghoul}
{1294}{}{un Seguace}
{1295}{}{Elmo}
{1296}{}{Bagno}
{1297}{}{Croce}
{1298}{}{Aratro}
{1299}{}{Aratro}
{1300}{}{Scorpione}
{1301}{}{Generatore}
{1302}{}{Porta}
{1303}{}{Porta}
{1304}{}{Medical Pip Boy}
{1305}{}{Armadietto}
{1306}{}{Armadietto}
{1307}{}{Armadietto}
{1308}{}{Armadietto}
{1309}{}{Armadietto}
{1310}{}{Armadietto}
{1311}{}{Armadietto}
{1312}{}{Armadietto}
{1313}{}{Armadietto}
{1314}{}{Armadietto}
{1315}{}{Armadietto}
{1316}{}{Armadietto}
{1317}{}{Armadietto}
{1318}{}{Armadietto}
{1319}{}{Armadietto}
{1320}{}{Armadietto}
{1321}{}{Armadietto}
{1322}{}{Armadietto}
{1323}{}{Armadietto}
{1324}{}{Armadietto}
{1325}{}{Script Mappa}
{1326}{}{Non puoi vedermi}
{1327}{}{Uomo di Latta}
{1328}{}{Script Mappa}
{1329}{}{una Formazione Rocciosa}
{1330}{}{}
{1331}{}{Terminale}
{1332}{}{Armadietto}
{1333}{}{}
{1334}{}{Script Mappa}
{1335}{}{un Robot della Sicurezza}
{1336}{}{un Robot della Sicurezza}
{1337}{}{Armadietto}
{1338}{}{Armadietto}
{1339}{}{Armadietto}
{1340}{}{Armadietto}
{1341}{}{Armadietto}
{1342}{}{Armadietto}
{1343}{}{Armadietto}
{1344}{}{Armadietto}
{1345}{}{Armadietto}
{1346}{}{Armadietto}
{1347}{}{Armadietto}
{1348}{}{Armadietto}
{1349}{}{Armadietto}
{1350}{}{Armadietto}
{1351}{}{Armadietto}
{1352}{}{Armadietto}
{1353}{}{Armadietto}
{1354}{}{Armadietto}
{1355}{}{Armadietto}
{1356}{}{Armadietto}
{1357}{}{un Abusivo del Porto}
{1358}{}{un Ragazzo del Porto}
{1359}{}{Script Mappa}
{1360}{}{Percy Crump}
{1361}{}{Scatola}
{1362}{}{Scatola}
{1363}{}{Porta}
{1364}{}{il Grande Ananias}
{1365}{}{Script Mappa}
{1366}{}{un "Unwashed Villager"}
{1367}{}{uno Spammer}
{1368}{}{Mappa}
{1369}{}{Script Mappa}
{1370}{}{Script Mappa}
{1371}{}{Script Mappa}
{1372}{}{Script Mappa}
{1373}{}{Distributore di Nuka-Cola}
{1374}{}{Porto}
{1375}{}{Porta}
{1376}{}{Mina terrestre}
{1377}{}{Mina terrestre}
{1378}{}{l'ex}
{1379}{}{Mel}
{1380}{}{Presa d'Aria}
{1381}{}{Kevin}
{1382}{}{Alarm}
{1383}{}{Armadietto}
{1384}{}{Armadietto}
{1385}{}{Armadietto}
{1386}{}{}
{1387}{}{}
{1388}{}{}
{1389}{}{}
{1390}{}{}
{1391}{}{}
{1392}{}{}
{1393}{}{}
{1394}{}{una Contrabbandiera}
{1395}{}{}
{1396}{}{}
{1397}{}{un ragazzetto}
{1398}{}{}
{1399}{}{}
{1400}{}{Miniera}
{1401}{}{Armadietto}
{1402}{}{Porta}
{1403}{}{}
{1404}{}{}
{1405}{}{}
{1406}{}{}
{1407}{}{}
{1408}{}{}
