#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the name which will  #
#           be displayed for critter or items when they     #
#           get hit. Each script from scripts.lst should    #
#           have a name associated with it.                 #
#                                                           #
#  Created: October 06, 1997                                #
#############################################################

{101}{}{}                               # obj_dude.int    ; Player script.
{102}{}{Script Test 0}                  # Test0.int       ; Used to Test Scripts
{103}{}{Script Test 1}                  # Test1.int       ; Used to Test Scripts
{104}{}{Script Test 2}                  # Test2.int       ; Used to Test Scripts
{105}{}{Script Test 3}                  # Test3.int       ; Used to Test Scripts
{106}{}{Script Test 4}                  # Test4.int       ; Used to Test Scripts
{107}{}{Script Test 5}                  # Test5.int       ; Used to Test Scripts
{108}{}{un guerriero di Arroyo}                 # ACWarior.int    ; Generic Warrior in Arroyo
{109}{}{un abitante di Arroyo}                # ACVillgr.int    ; Generic Villager of Arroyo
{110}{}{Mynoc}                          # ACMynoc.int     ; Mynoc, Bridge Guard of Arroyo
{111}{}{l'Anziana di Arroyo}                   # AHElder.int     ; Elder of Arroyo
{112}{}{Hakunin}                        # AHHakun.int     ; Hakunin, Shaman of Arroyo
{113}{}{una porta}                           # Door.int        ; generic locked and trapped door
{114}{}{Generico}                        # Generic.int     ; Generic dialog for scripts
{115}{}{un baule}                          # AILkBox.int     ; Locked box in Arroyo Elder's room
{116}{}{una scatola}                        # Containr.int    ; Generic locked and trapped container
{117}{}{un brahmin}                        # ACBrahmn.int    ; Brahmin for pen in Arroyo
{118}{}{una pianta Sporigena}                    # ACSporPl.int    ; Spore plants in Arroyo
{119}{}{}                               # ZClRat.int      ; Generic lesser rat
{120}{}{uno Scorpione Minore}                # ZClScorp.int    ; Generic lesser scorpion
{121}{}{una Mantide Minore}                  # ZClManti.int    ; Generic lesser mantis
{122}{}{un Deathclaw Minore}               # ZClDthCL.int    ; Generic lesser death claw
{123}{}{un vaso}                           # AIVase.int      ; Vase in Arroyo Villager's Hut
{124}{}{un baule}                          # AIChest.int     ; Chest in Arroyo Shaman's Hut
{125}{}{Grotte di Arroyo}                   # ArCaves.int     ; Map Script for Arroyo Caves
{126}{}{una Porta di Legno}                    # DoorL100.int    ; Generic Locked Door (+100%) (Wood)
{127}{}{Villaggio di Arroyo}                 # ArVillag.int    ; Map Script for Arroyo Village
{128}{}{Ponte di Arroyo}                  # ArBridge.int    ; Map Script for Arroyo Bridge
{129}{}{una Vecchia Porta}                       # AICavDor.int    ; Locked wooden door in Arroyo Caves (0/-20)
{130}{}{Piastrella del Pavimento}                    # SprTrp0.int     ; Generic spear Trap (0)
{131}{}{Piastrella del Pavimento}                    # SprTrp50.int    ; Arroyo Spear Trap for Caves (50)
{132}{}{Piastrella del Pavimento}                    # SprTrp51.int    ; Arroyo Spear Trap for Caves (50)
{133}{}{Piastrella del Pavimento}                    # SprTrp52.int    ; Arroyo Spear Trap for Caves (50)
{134}{}{Piastrella del Pavimento}                    # SprTrp53.int    ; Arroyo Spear Trap for Caves (50)
{135}{}{una Porta}                           # AIBkDor.int     ; Door w/out a handle In Arroyo Caves
{136}{}{un Tossicodipendente}                         # DCAddict.int    ; Addict from the Den
{137}{}{una Guardia}                          # DCG2Grd.int     ; Gang 2 Guard from the Den
{138}{}{un Paesano}                    # DCCustmr.int    ; Generic Customer in the Den
{139}{}{un Delinquente}                           # DCCustmr.int    ; Thug in the Den
{140}{}{un Orfano}                         # DCOrphan.int    ; Thieving Orphan in the Den
{141}{}{Joey}                           # DCJoey.int      ; Special thug in the Den
{142}{}{Flick}                          # DCFlick.int     ; Kwik N Save store owner in the Den
{143}{}{una Guardia}                          # DCG2Grd.int     ; Gang 2 Guard in the Den
{144}{}{Petey}                          # DCPetey.int     ; Petey, the alley addict in the Den
{145}{}{Smitty}                         # DCSmitty.int    ; Smitty the junkyard guy in the Den
{146}{}{Metzger}                        # dcMetzge.int    ; Metzger the Slaver in the Den
{147}{}{uno Schiavista}                         # DCSlaver.int    ; Regular Slaver in the Den
{148}{}{Tubby}                          # DCTubby.int     ; Tubby the store owner in the Den
{149}{}{Anna}                           # DCAnna.int      ; Anna the Ghost in the Den
{150}{}{Vic}                            # DCVic.int       ; Trader Vic in the Den, can be a party member
{151}{}{Frankie}                        # DCFranki.int    ; Frankie, owner of the Hole in the Den
{152}{}{Rebecca}                        # DCRebecc.int    ; Rebecca in the Den
{153}{}{Billy}                          # DCBilly.int     ; One-tooth Billy in the Hole in the Den
{154}{}{Sheila}                         # DCSheila.int    ; Sheila, the prostitute in the Hole in the Den
{155}{}{Mama}                            # DCMom.int       ; Mom, who run's Mom's in the Den
{156}{}{un Abitante del Villaggio}                       # DCSlvRun.int    ; Generic People for Slave Runs
{157}{}{Raid Schiavista}                      # DNSlvRun.int    ; Map Script for Den Slave Runs
{158}{}{il Carro Schiavista}                     # DISlvCrt.int    ; Slave Cart to take the Player to Den
{159}{}{Den Business Area}              # DenBus1.int     ; Map Script for Den business area 1
{160}{}{Den Business Area}              # DenBus2.int     ; Map Script for Den business area 2
{161}{}{Den Residential Area}           # DenRes1.int     ; Map Script for Den residential area
{162}{}{Tomba}                          # diAnnGrv.int    ; Grave of Anna the ghost in the Den
{163}{}{Tomba}                          # diDadGrv.int    ; Grave of Anna the ghost's Dad in the Den
{164}{}{Tomba}                          # diMomGrv.int    ; Grave of Anna the ghost's Mom in the Den
{165}{}{Ossa}                          # diBones.int     ; Bones of Anna the ghost in the Den
{166}{}{Diario}                          # diDiary.int     ; Diary of Anna the ghost in the Den
{167}{}{Medaglione}                         # diLocket.int    ; Locket of Anna the ghost in the Den
{168}{}{il Distillatore}                          # diStill.int     ; Still that Maggie has in the basement in the Den
{169}{}{Tomba}                          # ziGenGrv.int    ; Generic grave
{170}{}{Black Jack}                     # ziBlkJck.int    ; Generic black jack table
{171}{}{uno Schiavo}                          # zcSlave.int     ; Generic slave
{172}{}{Black Jack}                     # dcBlkJck.int    ; Den black jack table from Maggie's place
{173}{}{Porta}                           # diChcDor.int    ; Church door from the Den
{174}{}{Whiskey Bob}                    # KCBob.int       ; Whiskey Bob from Klamath
{175}{}{Dadi}                          # dcCraps.int     ; Maggie Craps dealer in the den
{176}{}{Aldo}                           # KCAldo.int      ; Aldo from Klamath
{177}{}{Ardin}                          # KCArdin.int     ; Ardin from Klamath
{178}{}{un Bambino}                          # KChild.int      ; Child from Klamath
{179}{}{un Cittadino}                        # KCitizen.int    ; Citizen from Klamath
{180}{}{Maida}                          # KCMaida.int     ; Maida from Klamath
{181}{}{Sajag}                          # KCSajag.int     ; Sajag from Klamath
{182}{}{Sally}                          # KCSally.int     ; Sally from Klamath
{183}{}{Smiley}                         # KCSmiley.int    ; Smiley from Klamath
{184}{}{Jenny}                          # KCJenny.int     ; Jenny from Klamath
{185}{}{Slim}                           # KCSlim.int      ; Slim from Klamath
{186}{}{Torr}                           # KCTorr.int      ; Torr from Klamath
{187}{}{uno dei due Dunton}                         # KCDunton.int    ; Dunton from Klamath
{188}{}{un Cittadino}                        # VCCrtCit.int    ; Vault City Courtyard Citizen
{189}{}{un Viaggiatore}                       # VCCrtOut.int    ; Vault City Courtyard Outsider
{190}{}{una Guardia di Vault City}               # VCCrtGrd.int    ; Vault City Courtyard Guard
{191}{}{una Guardia di Vault City}               # VCInGrd.int     ; Vault City Inner Guard
{192}{}{Steve}                          # VCSteve.int     ; Steve from Vault City
{193}{}{Andrew}                         # VCAndy.int      ; Andy the Medic in the Central Vault City
{194}{}{una Guardia di Vault City}               # VCGatGrd.int    ; Vault City Main Gate Guard
{195}{}{Dr. Troy}                       # VCDrTroy.int    ; Vault City Dr. Troy in the Vault
{196}{}{un Cane Giallo}                     # KCYellow.int    ; Yellow Dog in Klamath
{197}{}{Balthas}                        # mcBaltha.int    ; Balthas in Modoc
{198}{}{Cornelius}                      # mcCornel.int    ; Cornelius in Modoc
{199}{}{Davin}                          # mcDavin.int     ; Davin in Modoc
{200}{}{Farrel}                         # mcFarrel.int    ; Farrel in Modoc
{201}{}{Grisham}                        # mcGrisha.int    ; Grisham in Modoc
{202}{}{Jo}                             # mcJo.int        ; Jo in Modoc
{203}{}{Jonny}                          # mcJonny.int     ; Jonny in Modoc
{204}{}{Karl}                           # mcKarl.int      ; Karl in Modoc
{205}{}{Laddie}                         # mcLaddie.int    ; Laddie in Modoc
{206}{}{Miria}                          # mcMiria.int     ; Miria in Modoc
{207}{}{un Protettore}                      # mcProtec.int    ; Protector in Modoc
{208}{}{Rose}                           # mcRose.int      ; Rose in Modoc
{209}{}{Vegeir}                         # mcVegeir.int    ; Vegeir in Modoc
{210}{}{Ed}                             # VCEd.int        ; Ed the Brahma dealer in Vault City
{211}{}{Harry}                          # VCHarry.int     ; Happy Harry the store keep in Vault City
{212}{}{la Sig.ra Smith}                     # VCFSmith.int    ; Mrs. Smith from Vault City (Farmer)
{213}{}{Melinda}                        # VCMelind.int    ; Town Greeter Melinda, Vault City
{214}{}{un Trapper}                        # KCTrapr.int     ; Generic trapper in Klamath
{215}{}{Mr. Smith}                      # VCMSmith.int    ; Mr. Smith from Vault City (Farmer)
{216}{}{Skeeve}                         # VCSkeeve.int    ; Skeeve, sells fake passes to Vault City
{217}{}{il Proconsole Gregory}              # VCGreg.int      ; Proconsul Gregory of Vault City
{218}{}{l'Infermiera Phyllis}                    # VCNancy.int     ; Nurse Nancy in Vault City
{219}{}{Randal}                         # VCRandal.int    ; Chief Admenities Officer of Vault City
{220}{}{Melma Fosforescente}                            # KTGoo.int       ; Toxic Goo in the rat caves (Klamath)
{221}{}{Barkus}                         # VCBarkus.int    ; Barkus, Vault City Service Coordinator
{222}{}{un Abitante del Villaggio}                       # VCGenVil.int    ; Generic Villager around Vault City
{223}{}{Stark}                          # VCStark.int     ; Vault City Sargent Stark
{224}{}{una Guardia dell'Entrata del Vault}               # VCVltGrd.int    ; Guard for entrance into the Vault of VC
{225}{}{il Vecchio Joe}                        # VCOldJoe.int    ; Crazy Old Joe (Vault City)
{226}{}{Connar}                         # VCConnar.int    ; Connar from Vault City
{227}{}{Wallace}                        # VCWalace.int    ; Wallace the Customs Official (Vault City)
{228}{}{Lynette}                        # VCLynett.int    ; First Citizen Lynette of Vault City
{229}{}{McClure}                        # VCMClure.int    ; Senior Council Member MCclure (Vault City)
{230}{}{un Ratto Mutante}                    # GCBrain.int     ; Intelligent rat in Gecko
{231}{}{Festus}                         # GCFestus.int    ; Festering ghoul in Gecko
{232}{}{Gordon}                         # GCGordon.int    ; Ghoul with economic data in Gecko
{233}{}{Hank}                           # GCHank.int      ; Ghoul that monitors the reactor in Gecko
{234}{}{Jeremy}                         # GCJerem.int     ; Ghoul in charge of supply cabinet in Gecko
{235}{}{Bitorzolo}                          # GCLumpy.int     ; Watches the Brahmin and helps Skeeter
{236}{}{Skeeter}                        # GCSkeetr.int    ; Gadgeteer in Gecko
{237}{}{Zomak}                          # GCZomak.int     ; Muscle man for the Brain
{238}{}{Wooz}                           # GCWooz.int      ; Bar owner and Tragic player
{239}{}{Lenny}                          # GCLenny.int     ; Stuttering ghoul that can join party
{240}{}{una Guardia Ghoul}                    # GGCRDesk.int    ; Reactor Desk guard
{241}{}{un Lavoratore Ghoul}                   # GCRWorkr.int    ; Reactor worker
{242}{}{un Lavoratore Luminoso}                 # GCRGlow.int     ; Reactor glowing one
{243}{}{una Guardia Ghoul}                    # GCRGuard.int    ; Reactor guard
{244}{}{un Robot}                          # GCRRobot.int    ; Reactor robot
{245}{}{un Cittadino Ghoul}                  # GCFolk.int      ; Townsfolk in Gecko
{246}{}{Map Script}                     # DepoLv1.int     ; Map script for Sierra Army Depot, Level 1
{247}{}{Map Script}                     # DepoLvA.int     ; Map script for Sierra Army Depot Underground
{248}{}{Map Script}                     # DepoLvB.int     ; Map script for Sierra. Underground B
{249}{}{un Robot della Sicurezza}                 # WCSecBot.int    ; Sierra Base, Security Robot (generic)
{250}{}{un Robot Riparatore}                   # WCRepBot.int    ; Sierra Base, Repair Robot (generic)
{251}{}{Olodisco}                       # WIEvcDsk.int    ; Sierra Base, Evacuation Holodisk
{252}{}{Olodisco}                       # WIMedDsk.int    ; Sierra Base, Medical Log 1 Holodisk
{253}{}{Olodisco}                       # WIExpDsk.int    ; Sierra Base, Experiment Log Holodisk
{254}{}{Terminale}                       # WSTerm1A.int    ; Security Computer, Level 1 -- Sierra Base
{255}{}{Terminale}                       # WSTerm1B.int    ; Security Systems, Level 1 -- Sierra Base
{256}{}{Terminale}                       # WSTerm2A.int    ; Security Computer, Level 2 -- Sierra Base
{257}{}{Terminale}                       # WSTerm2B.int    ; Security Systems, Level 2 -- Sierra Base
{258}{}{Terminale}                       # WSTerm2C.int    ; Auto Repair System, Level 2 -- Sierra Base
{259}{}{Terminale}                       # WSTerm3A.int    ; Security Computer, Level 3 -- Sierra Base
{260}{}{Terminale}                       # WSTerm3B.int    ; Skynet Terminal, Level 3 -- Sierra Base
{261}{}{Terminale}                       # WSTerm3C.int    ; Robobrain Activator, Level 3 -- Sierra Base
{262}{}{Terminale}                       # WSTerm4A.int    ; Security Computer, Level 4 -- Sierra Base
{263}{}{Terminale}                       # WSTerm4B.int    ; Organ Extractor, Level 4 -- Sierra Base
{264}{}{Terminale}                       # WSTerm4C.int    ; BioStorage Computer, Level 4 -- Sierra Base
{265}{}{Carta}                          # WIPaswrd.int    ; Piece of paper with the password on it
{266}{}{Il Soldato Dobbs}                  # WCDobbs.int     ; Private Dobbs, Sierra Army Depot
{267}{}{BrainBot}                      # WCBrnBot.int    ; Brain Bot in the Army Depot
{268}{}{Ascensore}                       # ZSElev01.int    ; Generic Elevator
{269}{}{Ascensore}                       # ZSElev02.int    ; Generic Elevator
{270}{}{Scatola}                        # DITubBox.int    ; Tubby's box of inventory
{271}{}{Scatola}                        # DIFlkBox.int    ; Flick's box of inventory
{272}{}{Tandi}                          # SHTandi.int     ; Tandi the talking head in the NCR2 area
{273}{}{Trappola-Lancia}                     # ATSrTrp0.int    ; Arroyo Spear Trap for Caves (50)
{274}{}{Trappola-Lancia}                     # ATSrTrp1.int    ; Arroyo Spear Trap for Caves (50)
{275}{}{Trappola-Lancia}                     # ATSrTrp2.int    ; Arroyo Spear Trap for Caves (50)
{276}{}{Trappola-Lancia}                     # ATSrTrp3.int    ; Arroyo Spear Trap for Caves (50)
{277}{}{Trappola-Lancia}                     # ATSrTrp4.int    ; Arroyo Spear Trap for Caves (50)
{278}{}{Trappola-Lancia}                     # ATSrTrp5.int    ; Arroyo Spear Trap for Caves (50)
{279}{}{Trappola-Lancia}                     # ATSrTrp6.int    ; Arroyo Spear Trap for Caves (50)
{280}{}{Trappola-Lancia}                     # ATSrTrp7.int    ; Arroyo Spear Trap for Caves (50)
{281}{}{Trappola-Lancia}                     # ATSrTrp8.int    ; Arroyo Spear Trap for Caves (50)
{282}{}{Trappola-Lancia}                     # ATSrTrp9.int    ; Arroyo Spear Trap for Caves (50)
{283}{}{Trappola-Lancia}                     # ATSrTrpA.int    ; Arroyo Spear Trap for Caves (50)
{284}{}{Trappola-Lancia}                     # ATSrTrpB.int    ; Arroyo Spear Trap for Caves (50)
{285}{}{Trappola-Lancia}                     # ATSrTrpC.int    ; Arroyo Spear Trap for Caves (50)
{286}{}{Trappola-Lancia}                     # ATSrTrpD.int    ; Arroyo Spear Trap for Caves (50)
{287}{}{Trappola-Lancia}                     # ATSrTrpE.int    ; Arroyo Spear Trap for Caves (50)
{288}{}{Trappola-Lancia}                     # ATSrTrpF.int    ; Arroyo Spear Trap for Caves (50)
{289}{}{Grotta Fantasma Uno}                 # GstCav1.int     ; Modoc Ghost Cave 1
{290}{}{Ghost Cave Two}                 # GstCav2.int     ; Modoc Ghost Cave 2
{291}{}{Ghost Farm}                     # GstFarm.int     ; Modoc Ghost Farm
{292}{}{Modoc Brahmin Field}            # ModBrah.int     ; Modoc Brahmin Field
{293}{}{Modoc Garden}                   # ModGard.int     ; Modoc Garden
{294}{}{Modoc Inn}                      # ModInn.int      ; Modoc Inn
{295}{}{Modoc Main}                     # ModMain.int     ; Modoc Main
{296}{}{Modoc Shit}                     # ModShit.int     ; Modoc under the shitter
{297}{}{Mod Well}                       # ModWell.int     ; Modoc Well
{298}{}{Ncr Area 2}                     # ncr2.int        ; NCR area 2
{299}{}{Arroyo Gardens}                 # ArGarden.int    ; Arroyo Gardens map script
{300}{}{un Gecko}                          # ACGecko.int     ; generic Gecko creature
{301}{}{Broc Flower}                    # AIBroc.int      ; Arroyo Broc Flower
{302}{}{Xander Root}                    # AIXander.int    ; Arroyo Xander Root
{303}{}{un Brahmin}                        # ZCBrahmn.int    ; Generic Brahmin
{304}{}{la Moglie di Balthas}                   # mcBalWif.int    ; Modoc Balthas wife
{305}{}{un Brahmin}                        # mcBrahmn.int    ; Modoc brahmin
{306}{}{un Cane Selvatico}                       # mcAtkDog.int    ; Modoc Attack Dog
{307}{}{Rocce}                          # miDclRks.int    ; Modoc Rocks in front of the death claw cage
{308}{}{Rocce}                          # miShtRks.int    ; Modoc Rocks under the shitter
{309}{}{Cassaforte a Muro}                      # miWalSfe.int    ; Modoc Farrel's wall safe
{310}{}{Sacchetto di Denaro}                       # miCoinBg.int    ; Modoc Coin bags at the bottom of the well
{311}{}{Toilet}                         # miToilet.int    ; ; Modoc Toliet
{312}{}{Scatola}                            # miLstFnd.int    ; Modoc Lost and Found at Rose's
{313}{}{Jordan}                         # ACJordan.int    ; Jordan. Trains player in Melee
{314}{}{Zia Morlis}                    # ACMorlis.int    ; Aunt Morlis. Has flint to give player
{315}{}{Lucas}                          # ACFist.int      ; Standing Fist. Trains player in Unarmed
{316}{}{Feargus}                        # ACEric.int      ; Whiny person asking to fix the well
{317}{}{Pozzo}                           # ASWell.int      ; Arroyo Well. It's broken. Fix w/ Repair
{318}{}{Gruthar}                        # OCGrutha.int    ; Vault 13 Gruthar Deathclaw leader
{319}{}{Map Script}                     # Kladwtwn.int    ; Map script for Klamath Downtown
{320}{}{Doofus}                         # SCSkeete.int    ; Doofus dialog script for NCR Entrance area
{321}{}{Nagor}                          # ACNagor.int     ; You cousin who has lost his dog
{322}{}{Smoke}                          # ACDog.int       ; Nagor's dog Smoke
{323}{}{Ncr Area 1}                     # Ncr1.int        ; Ncr area 1 map
{324}{}{Ncr Area 3}                     # Ncr3.int        ; Ncr area 3 map
{325}{}{Ncr Area 4}                     # Ncr4.int        ; Ncr area 4 map
{326}{}{Ncr Area Entrance}              # Ncrent.int      ; Ncr area Entrance map
{327}{}{Mikey}                          # SCMikey.int     ; NCR Lizard Dealer
{328}{}{Scatola di Mikey}                    # SIMbox.int      ; NCR Mikey's inventory box. (off Screen)
{329}{}{Emettitore}                        # WSEmit1a.int    ; Emitter, Level 1, Section A   (Sierra Base)
{330}{}{Emettitore}                        # WSEmit1b.int    ; Emitter, Level 1, Section B   (Sierra Base)
{331}{}{Emettitore}                        # WSEmit1c.int    ; Emitter, Level 1, Section C   (Sierra Base)
{332}{}{Emettitore}                        # WSEmit1d.int    ; Emitter, Level 1, Section D   (Sierra Base)
{333}{}{Emettitore}                        # WSEmit1e.int    ; Emitter, Level 1, Section E   (Sierra Base)
{334}{}{Emettitore}                        # WSEmit2a.int    ; Emitter, Level 2, Section A   (Sierra Base)
{335}{}{Emettitore}                        # WSEmit2b.int    ; Emitter, Level 2, Section B   (Sierra Base)
{336}{}{Emettitore}                        # WSEmit2c.int    ; Emitter, Level 2, Section C   (Sierra Base)
{337}{}{Emettitore}                        # WSEmit2d.int    ; Emitter, Level 2, Section D   (Sierra Base)
{338}{}{Emettitore}                        # WSEmit3a.int    ; Emitter, Level 3, Section A   (Sierra Base)
{339}{}{Emettitore}                        # WSEmit3b.int    ; Emitter, Level 3, Section B   (Sierra Base)
{340}{}{Campo di Forza}                    # WSFeld1a.int    ; F. Field, Level 1, Section A   (Sierra Base)
{341}{}{Campo di Forza}                    # WSFeld1b.int    ; F. Field, Level 1, Section B   (Sierra Base)
{342}{}{Campo di Forza}                    # WSFeld1c.int    ; F. Field, Level 1, Section C   (Sierra Base)
{343}{}{Campo di Forza}                    # WSFeld1d.int    ; F. Field, Level 1, Section D   (Sierra Base)
{344}{}{Campo di Forza}                    # WSFeld1e.int    ; F. Field, Level 1, Section E   (Sierra Base)
{345}{}{Campo di Forza}                    # WSFeld2a.int    ; F. Field, Level 2, Section A   (Sierra Base)
{346}{}{Campo di Forza}                    # WSFeld2b.int    ; F. Field, Level 2, Section B   (Sierra Base)
{347}{}{Campo di Forza}                    # WSFeld2c.int    ; F. Field, Level 2, Section C   (Sierra Base)
{348}{}{Campo di Forza}                    # WSFeld2d.int    ; F. Field, Level 2, Section D   (Sierra Base)
{349}{}{Campo di Forza}                    # WSFeld3a.int    ; F. Field, Level 3, Section A   (Sierra Base)
{350}{}{Campo di Forza}                    # WSFeld3b.int    ; F. Field, Level 3, Section B   (Sierra Base)
{351}{}{Klaxon}                         # WSKlaxon.int    ; Changes lights to Flashing w/ Sierra on Alert
{352}{}{Buster}                         # SCBuster.int    ; Buster gun dealer at NCR entrance
{353}{}{Bookshelf}                      # SIShelf1.int    ; Busters shelves where items are kept
{354}{}{Bookshelf}                      # SIShelf2.int    ; Busters shelves where items are kept
{355}{}{Bookshelf}                      # SIShelf3.int    ; Busters shelves where items are kept
{356}{}{un Predone}                         # ECRaider.int    ; Random Encounter Raider
{357}{}{un Contadino}                        # ECPeasnt.int    ; Random Encounter Peasant
{358}{}{un Mercante}                       # ECMrchnt.int    ; Random Encounter Merchant
{359}{}{una Guardia}                          # ECGuard.int     ; Random Encounter Guard
{360}{}{un Cliente del Rawhide}                 # SCRawpat.int    ; Rawhide patron in NCR Entrance
{361}{}{Floor}                          # WTElFlr2.int    ; Electric Floor on Level 2 Sierra Base
{362}{}{Plasma Trap}                    # WTPlTrp0.int    ; Plasma Trap for Sierra Base(-30)
{363}{}{Plasma Trap}                    # WTPlTrp1.int    ; Plasma Trap for Sierra Base(-30)
{364}{}{Terminal}                       # WSPwrDwn.int    ; Power Switch for the Sierra Base
{365}{}{Bulletin Board}                 # KSBboard.int    ; Klamath bulletin board
{366}{}{Gate}                           # ASCrlDr.int     ; Arroyo Corral Gate
{367}{}{Goo}                            # ATGoo.int       ; Goo in the Garden Map
{368}{}{Door}                           # KSCVDoor.int    ; Door in Klamath Rat Caves
{369}{}{Door}                           # KSMalldr.int    ; Door in Klamall..get key from Slim or Dog
{370}{}{}                               # ZCGecko.int     ; Generic gecko
{371}{}{}                               # ZCLGecko.int    ; Generic Golden Gecko
{372}{}{Map Script}                     # 2ndSt.int       ; 2nd Street Map Script
{373}{}{Map Script}                     # ChopShop.int    ; Chop Shop Map Script
{374}{}{Map Script}                     # GeckPwpl.int    ; Gecko Power Plant Map Script
{375}{}{Map Script}                     # GeckTunl.int    ; Gecko Tunnels Map Script
{376}{}{Map Script}                     # KlaCnyn.int     ; Klamath Canyon Map Script
{377}{}{Map Script}                     # MBase12.int     ; Military Base Level 1,2 Map Script
{378}{}{Map Script}                     # MBase34.int     ; Military Base Level 3,4 Map Script
{379}{}{Map Script}                     # MBClose.int     ; Military Base Closed Map Script
{380}{}{Map Script}                     # ModShit.int     ; Map Script for Modoc Shitter
{381}{}{Map Script}                     # NCR1.int        ; Map Script for NCR1
{382}{}{Map Script}                     # NCR2.int        ; Map Script for NCR2
{383}{}{Map Script}                     # NCR3.int        ; Map Script for NCR3
{384}{}{Map Script}                     # NCR4.int        ; Map Script for NCR4
{385}{}{Map Script}                     # NCREx.int       ; Map Script for NCR Exit
{386}{}{Map Script}                     # Stable.int      ; Map Script for Stables
{387}{}{Map Script}                     # V13_Orig.int    ; Map Script for Original Vault 13
{388}{}{Map Script}                     # V13Ent.int      ; Map Script for Vault 13 Entrance
{389}{}{Map Script}                     # V15_Orig.int    ; Map Script for Original Vault 15
{390}{}{Map Script}                     # V15Ent.int      ; Map Script for Vault 15 Entrance
{391}{}{Map Script}                     # Vault13.int     ; Map Script for Vault 13
{392}{}{Map Script}                     # Vault15.int     ; Map Script for Vault 15
{393}{}{Map Script}                     # VaultNec.int    ; Map Script for Necropolis Vault
{394}{}{Map Script}                     # VCtyVlt.int     ; Map Script for Vault City Vault
{395}{}{Map Script}                     # Virgin.int      ; Map Script for Virgin (these still exist?)
{396}{}{un distillatore}                          # Kstill.int      ; Script for still in Klamath
{397}{}{un Cliente del Bar}                   # Kcggcust.int    ; Script for Klamath golden gecko customer
{398}{}{un Cliente del Bar}                   # Kcbhcust.int    ; Script for Klamath buckner house customer
{399}{}{Vortis}                         # SCVortis.int    ; Script for Vortis slave pen dude in NCR entrance
{400}{}{un'Inserviente della Bath House}                 # Kcbgirl.int     ; Script for Klamath bath girl
{401}{}{uno Schiavo}                         # SCSlaves.int    ; Script for NCR Entrance slaves
{402}{}{uno Scorpione}                       # Kcscorp.int     ; Script for Klamath scorpions on the graze map
{403}{}{un Brahmin}                        # Kcbrahmn.int    ; Script for Klamath brahmin on the graze map
{404}{}{Car}                            # ZSDrvCar.int    ; Drivable Car for the player
{405}{}{Table}                          # diVicTbl.int    ; Den, table that Vic works at
{406}{}{Map Script}                     # Klagraz.int     ; Map Script for Klamath graze map
{407}{}{Map Script}                     # CarDesrt.int    ; Car Out of Gas Desert Map
{408}{}{Map Script}                     # GeckSetl.int    ; Map Script for Gecko Settlement
{409}{}{Map Script}                     # VCtyCtyd.int    ; Map Script for Vault City Courtyard
{410}{}{Corvega}                        # Kscorveg.int    ; Klamath broken car with fuel injection
{411}{}{Map Script}                     # KlaToxCv.int    ; Klamath Toxic Caves  Map Script
{412}{}{Metal Door}                     # SISlvdor.int    ; Slave pen door in NCR Entrance
{413}{}{Map Script}                     # RndDsrt.int     ; Random Encounter Desert Map Script
{414}{}{Map Script}                     # RndCoast.int    ; Random Encounter Coast Map Script
{415}{}{Map Script}                     # RndMnt.int      ; Random Encounter Mountain Map Script
{416}{}{Lockbox}                        # Kidbox.int      ; Klamath dunton inventory box
{417}{}{Lockbox}                        # Kibbox.int      ; Klamath buckner inventory box
{418}{}{Lockbox}                        # Kisbox.int      ; Klamath sajag inventory box
{419}{}{Ratch}                          # SCRatch.int     ; Ncr entrance JUNK dealer
{420}{}{un Pugile}                          # ncBoxer.int     ; New Reno Generic Boxer
{421}{}{Pete McKneely}                  # ncMcKnee.int    ; New Reno Mike McKneely
{422}{}{Evan Hollyfeld}                 # ncHollyf.int    ; New Reno Evan Hollyfeld
{423}{}{Il Masticatore}                     # ncTyson.int     ; New Reno Mike Tyson
{424}{}{uno Scienziato}                      # ncScient.int    ; New Reno Generic Scientist
{425}{}{Merk}                           # SCMerk.int      ; Merk an NCR mob type guy
{426}{}{un Fan}                            # ncBoxFan.int    ; New Reno Boxing Fan
{427}{}{uno Spacciatore di Droga}                    # ncDrgDlr.int    ; New Reno Drug Dealer
{428}{}{un Cliente del Casino'}                  # ncCasPat.int    ; New Reno Casino Patron
{429}{}{un Pappone}                           # ncPimp.int      ; New Reno Generic Pimp
{430}{}{un Drogato}                         # ncJunkie.int    ; New Reno Generic Junkie
{431}{}{Furniture}                      # stuff.int       ; signals critters on steal attempt
{432}{}{Floor}                          # trespass.int    ; same as stuff only for an area
{433}{}{Ground}                         # ATDeath.int     ; Spatial telling the player about Nagor dead
{434}{}{Holodisk}                       # SIFakhlo.int    ; Fake holodisk you get from Merk in NCR.
{435}{}{Lenny}                          # SCLenny.int     ; Lenny a guy in NCR Entrance
{436}{}{Box}                            # SCPtbox.int     ; Players temp box to hold his stuff for the fight with lenny
{437}{}{una Prostituta}                     # ncProsti.int    ; New Reno Prostitute with billions of messages
{438}{}{uno Schiavo}                          # ncSlave.int     ; New Reno Slaves
{439}{}{Rico}                           # ncRico.int      ; New Reno Rico, Monte's thug
{440}{}{un'Attrice Porno}                   # ncActres.int    ; New Reno Porn Actress
{441}{}{un'Assistente}                        # ncFluffe.int    ; New Reno Porn Fluffer/Extra
{442}{}{Map Script}                     # Klacanyn.int    ; Map script for Klamath Canyon
{443}{}{un Lupo}                           # ECWlfPck.int    ; Military Base Wolf Pack
{444}{}{un Generatore}                      # ESPwrGen.int    ; Military Base Power Generator
{445}{}{una Porta}                           # ESLkDor.int     ; Military Base Locked Door (-30)
{446}{}{un Super Mutante}                   # ECGenMut.int    ; Military Base Generic Mutant
{447}{}{un Uomo di Salvatore}                # ncSalMen.int    ; New Reno Salvatore's Men
{448}{}{un Uomo di Bishop}                   # ncBisMen.int    ; New Reno Bishop's Men
{449}{}{un Uomo di Mordino}                  # ncMorMen.int    ; New Reno Mordino's Men
{450}{}{uno dei Figli di Wright}                 # ncWriTee.int    ; New Reno Wright's Sons & Daughters
{451}{}{un Buttafuori del Casino'}                 # ncCasBou.int    ; New Reno Generic Casino Bouncer
{452}{}{Mira}                           # SCMira.int      ; NCR entrance bartender
{453}{}{New Reno Virgin Street}         # NewR1.int       ; New Reno Map Virgin Street
{454}{}{New Reno 2nd Street}            # NewR2.int       ; New Reno Map 2nd Street
{455}{}{New Reno Commercial Row}        # NewR3.int       ; New Reno Map Commercial Row
{456}{}{New Reno East Side}             # NewR4.int       ; New Reno Map East Side
{457}{}{New Reno Stables}               # NewRSt.int      ; New Reno Map Stables
{458}{}{New Reno Chop Shop}             # NewRCS.int      ; New Reno Map Chop Shop
{459}{}{New Reno Gologtha}              # NewRGo.int      ; New Reno Map Gologtha
{460}{}{New Reno Bishop Basement}       # NewRBa.int      ; New Reno Map Bishop Basement
{461}{}{Holodisk}                       # EIOutDsk.int    ; Military Base Holodisk (Outside)
{462}{}{Holodisk}                       # EILv1Dsk.int    ; Military Base Holodisk (Level 1)
{463}{}{Holodisk}                       # EILv2Dsk.int    ; Military Base Holodisk (Level 2)
{464}{}{Holodisk}                       # EILv3Dsk.int    ; Military Base Holodisk (Level 3)
{465}{}{Holodisk}                       # EILv4Dsk.int    ; Military Base Holodisk (Level 4)
{466}{}{una Guardia}                          # SCGteGrd.int    ; Ncr gate guard
{467}{}{Mine Cart}                      # ESMinCrt.int    ; Military Base Mine Cart to explode on door
{468}{}{Melchior}                       # ECMelchr.int    ; Melchoir the Magnificent (pseudo-mage)
{469}{}{una Bestia Mutante}                  # ECMutRat.int    ; Mutated Rats in Military Base
{470}{}{FEV Goo}                        # ETGoo.int       ; FEV Goo in the Military Base
{471}{}{il Capitano delle Guardie}                  # SCGGCap.int     ; NCR Entrance Gate guard captain
{472}{}{un Guardiano degli Schiavi}                 # SCslvovr.int    ; NCR Entrance slave overseer
{473}{}{uno dei Cuccioli di Melchior}                 # ECMelPet.int    ; Melchior's Pets
{474}{}{una Guardia Schiavista}                   # SCslvgrd.int    ; Slaver Guard in NCR Entrance
{475}{}{Door}                           # SIclsdor.int    ; Closing door
{476}{}{Terminal}                       # SITerm.int      ; Slave pen terminals NCR Entrance
{477}{}{Slot Machine}                   # ziSlots.int     ; Generic Slot Machine
{478}{}{un Bambino}                          # ncWriChi.int    ; New Wright children
{479}{}{Sheb}                           # ncSheb.int      ; New Reno Sheb
{480}{}{una Guardia}                          # SCMrkGrd.int    ; Merk's guards NCR Entrance and council
{481}{}{Emitter}                        # SIEmtr.int      ; Emitter in NCR Entrance
{482}{}{Force Field}                    # SIFField.int    ; Force field in NCR Entrance
{483}{}{Sulik}                          # Kcsulik.int     ; Sulik from Klamath
{484}{}{il Dr. Henry}                      # SCHenry.int     ; Henry NCR Entrance
{485}{}{una Guardia}                          # SCCarGrd.int    ; Carlson's guards NCR2
{486}{}{Carlson Guards Attack}          # STCaratk.int    ; Carlson's guards attack spatial
{487}{}{una Guardia di Carlson addetta al Cancello}          # SCcgtgrd.int    ; Carlson's gate Guards
{488}{}{un Prigioniero}                       # VCOutPrs.int    ; Vault City Outsider Prisoner (Generic)
{489}{}{un Prigioniero}                       # VCCitPrs.int    ; Vault City Citizen Prisoner (Generic)
{490}{}{un Cittadino}                        # VCGenFam.int    ; Vault City Generic Family
{491}{}{un Assistente dell'Emporio}                  # VCAmAid.int     ; Vault City Amenities Aid
{492}{}{una Guardia del Bancone}                     # GCRDesk.int     ; Gecko Reactor Desk Guard
{493}{}{un Lavoratore Ghoul}                   # GCRGhoul.int    ; Gecko Reactor Ghoul Worker
{494}{}{un Luminoso}                    # GCRGlow.int     ; Gecko Glowing One
{495}{}{una Guardia Ghoul}                    # GCRGuard.int    ; Gecko Red Door Guard
{496}{}{un Robot}                          # GCRobot.int     ; Gecko Reactor Robot
{497}{}{un Ghoul}                          # GCFolk.int      ; Gecko Townsfolk
{498}{}{un Adoratore}                     # GCWorshp.int    ; Gecko Worshippers
{499}{}{Harold}                         # GCHarold.int    ; Harold in Gecko
{500}{}{un Ufficiale}                        # GCPACOff.int    ; Gecko Powered Armor Com Officer
{501}{}{Toto}                           # SCToto.int      ; Toto hlper bot in NCR 1
{502}{}{Dorothy}                        # SCDoroth.int    ; Dorothy Repair chick in NCR 1
{503}{}{un Abitante}                    # ncPerson.int    ; New Reno Generic Townsperson/Citizen
{504}{}{una Guardia Ghoul}                    # GCYGuard.int    ; Gecko Yellow Door Guard
{505}{}{una Guardia Ghoul}                    # GCGuard.int     ; Gecko Generic Guard
{506}{}{Gond}                           # SCGond.int      ; Ranger Guard, NCR 1
{507}{}{Duppo}                          # SCDuppo.int     ; Stockman's yard store owner
{508}{}{Stuff}                          # SIdtbl.int      ; Duppo's tables in shop
{509}{}{Bob}                            # SCsalbob.int    ; Salt Beef Bob NCR 3
{510}{}{una Ragazza del Casino'}                    # ziDceGrl.int    ; Generic Casino Girl with Dice Game
{511}{}{una Ragazza del Casino'}                    # niDceGrl.int    ; New Reno Casino Girl with Dice Game
{512}{}{Magic Eight Ball}               # zi8Ball.int     ; EPA Magic 8 Ball
{513}{}{un Brahmin}                        # ncAngBra.int    ; New Reno Angry Brahmin
{514}{}{Slot Machine}                   # niMcGSlt.int    ; New Reno McGee's Slot Machine
{515}{}{il Vecchio McGee}                  # ncMcGee.int     ; New Reno Old Man (Bobby) McGee
{516}{}{Three Card Monte}               # nc3Monte.int    ; New Reno Three Card Monte
{517}{}{Algernon}                       # ncAlgern.int    ; New Reno Algernon
{518}{}{Bill}                           # ncBill .int     ; New Reno Bill (Trees Lounge)
{519}{}{una Guardia del Corpo di Bishop}             # ncBisGrd.int    ; New Reno Bishop's Bodyguards
{520}{}{John Bishop}                    # ncBishop.int    ; New Reno John Bishop
{521}{}{Casino Machine}                 # niCasMac.int    ; New Reno Casino Machine
{522}{}{un "Chop Shop Boy"}                  # ncChpBoy.int    ; New Reno Chop Shop Boys
{523}{}{Chris Wright}                   # ncChrWri.int    ; New Reno Chris Wright
{524}{}{Cody}                           # ncCody .int     ; New Reno Cody
{525}{}{uno dei Fratelli Corsican}                # ncCorBro.int    ; New Reno Corsican Bothers
{526}{}{Eldridge}                       # ncEldrid.int    ; New Reno Eldridge
{527}{}{Ethyl Wright}                   # ncEthWri.int    ; New Reno Ethyl Wright
{528}{}{Padre Tully}                   # ncFTully.int    ; New Reno Father Tully
{529}{}{HumperdumperDIDO}               # ncHumper.int    ; New Reno HumperdumperDIDO
{530}{}{Lil' Jesus Mordino}             # ncLilJes.int    ; New Reno Lil' Jesus Mordino
{531}{}{Jimmy J, lo Sfregiato}                 # ncJimmyJ.int    ; New Reno Jagged Jimmy J
{532}{}{Keith Wright}                   # ncKeiWri.int    ; New Reno Keith Wright
{533}{}{Lee Anne Bishop}                # ncLABish.int    ; New Reno Lee Anne Bishop
{534}{}{Pretty Boy Lloyd}               # ncLloyd.int     ; New Reno Pretty Boy Lloyd
{535}{}{Mason}                          # ncMason.int     ; New Reno Mason
{536}{}{una Guardia}                          # ncMyrGrd.int    ; New Reno Myron's Guards
{537}{}{Myron}                          # nhMyron.int     ; New Reno Myron (Talking Head)
{538}{}{Nikki}                          # ncNikki.int     ; New Reno Darlin' Nikki
{539}{}{Orville Wright}                 # ncOrvill.int    ; New Reno Orville Wright
{540}{}{Boss}                       # ncPitBos.int    ; New Reno Generic Pit Boss
{541}{}{Renesco "the Rocket-Man"}         # ncRenesc.int    ; New Reno Renesco the Rocket-Man
{542}{}{Marjorie Reed}                  # ncResear.int    ; New Reno Stables Researcher
{543}{}{il Boss Salvatore}                 # ncSalvat.int    ; New Reno Boss Salvatore
{544}{}{Stuart Little}                  # ncStuLit.int    ; New Reno Stuart Little (Agent)
{545}{}{T-Ray}                          # ncTRay .int     ; New Reno T-Ray
{546}{}{una Puttana}                          # ncBitch.int     ; New Reno Corsican Brothers Bitches
{547}{}{un Bambino degli Wright}                   # ncWriPly.int    ; New Reno Wright Children Playing
{548}{}{un Poliziotto di NCR}                     # SCCop.int       ; NCR cop
{549}{}{Oswald}                         # SCOswald.int    ; Raider Oswald captive NCR 1
{550}{}{Dusty}                          # SCDusty.int     ; Dusty bartender in NCR 1
{551}{}{Jules}                          # ncJules.int     ; New Reno Jules
{552}{}{Miss Kitty}                     # ncKitty.int     ; New Reno Miss Kitty
{553}{}{il Barista}                      # ncBarten.int    ; New Reno Bartender
{554}{}{il Vicesceriffo Karl}                    # SCKarl.int      ; NCR Deputy
{555}{}{Cell Door}                      # SIKdoor.int     ; NCR Cell door
{556}{}{Big Jesus Mordino}              # ncBigJes.int    ; New Reno Big Jesus Mordino
{557}{}{Hoss}                           # SCHoss.int      ; Hoss, bully NCR 1 map
{558}{}{Mutagenic Serum}                # SIMserum.int    ; Mutagenic Serum
{559}{}{Box}                            # niSalBox.int    ; New Reno Salvatore Bartender Shop Inventory
{560}{}{Box}                            # niMorBox.int    ; New Reno Mordino Bartender Shop Inventory
{561}{}{Box}                            # niBisBox.int    ; New Reno Bishop Bartender Shop Inventory
{562}{}{Box}                            # niTmpBox.int    ; New Reno Personal Inventory Swap Box
{563}{}{Il Dottor Jubilee}                 # SCDocJub.int    ; Doctor Jubilee NCR Map 1
{564}{}{Door}                           # GSYDoor.int     ; Yellow Door in Gecko Reactor
{565}{}{Door}                           # GSRDoor.int     ; Red Door in Gecko Reactor
{566}{}{Bookcase}                       # SIdshelf.int    ; Bookshelf for the Doc NCR 1
{567}{}{lo Sceriffo Dumont}                 # SCsherif.int    ; Sheriff in NCR map 1
{568}{}{Elise}                          # SCElise.int     ; Elise in NCR map 1 ranger leader chick
{569}{}{un Bracciante}                     # SCwrHand.int    ; Westin Ranch Hand NCR 3
{570}{}{Felix}                          # SCFelix.int     ; Westin's forman on NCR 3
{571}{}{Westin}                         # SCWestin.int    ; Westin big dude on NCR 3
{572}{}{Rondo}                          # SCRondo.int     ; Rondo Ranger NCR 1
{573}{}{Robocane}                        # SCRobo.int      ; Robodog NCR 1
{574}{}{Stairs}                         # NIBissta.int    ; New Reno Bishop's stairs
{575}{}{Hal}                            # SCHal.int       ; Hal, Drive Leader
{576}{}{Gunther}                        # SCGunthr.int    ; Gunther Tandi's assistant NCR 2
{577}{}{un Brahmin}                        # ECCrtBra.int    ; Random Encounter Brahmin for carts
{578}{}{il Capo della Carovana}                 # ECCvnMst.int    ; Random Encounter Caravan Master
{579}{}{un Guidatore della Carovana}                 # ECCvnDrv.int    ; Random Encounter Caravan Driver
{580}{}{una Guardia della Carovana}                  # ECCvnGrd.int    ; Random Encounter Caravan Guard
{581}{}{un Predone}                         # ECRadLdr.int    ; Random Encounter Raider Leader
{582}{}{un Delinquente}                        # ECMobstr.int    ; Random Encounter Mobster (Outside New Reno)
{583}{}{un Cacciatore}                         # ECHntLdr.int    ; Random Encoutner Hunting Party Leader
{584}{}{un Cacciatore}                         # ECHunter.int    ; Random Encounter Hunting Party
{585}{}{un Ranger}                         # ECRanger.int    ; Random Encounter NCR Rangers (Patrol)
{586}{}{un Mercenario}                      # ECMercs.int     ; Random Encounter Mercenaries
{587}{}{un Mercenario}                      # ECMrcLdr.int    ; Random Encounter Mercenary Leader
{588}{}{un Predone}                         # ECRadGrp.int    ; Random Encounter Raider Party
{589}{}{un Guidatore della Carovana}                 # ECRndDrv.int    ; Random Encounter Other Caravan Driver
{590}{}{una Guardia della Carovana}                  # ECRndGrd.int    ; Random Encounter Other Caravan Guard
{591}{}{una Guardia di Pattuglia}                   # ECVltPat.int    ; Random Encounter Vault City Patrols
{592}{}{il Capitano della Pattuglia}                 # ECVltCpt.int    ; Random Encounter Vault City Patrol Capt.
{593}{}{un Contadino}                   # ECFarmer.int    ; Random Encounter Farmer
{594}{}{un Brahmin}                     # ECBraHrd.int    ; Random Encounter Brahmin Herd
{595}{}{un Brahmin}                     # ECLedBra.int    ; Random Encounter Lead Brahmin
{596}{}{un Viaggiatore}                 # ECTrvlr.int     ; Random Encounter Traveler
{597}{}{una Guardia di Pattuglia}       # ECGhlPat.int    ; Random Encounter Ghoul Patrol
{598}{}{il Capitano della Pattuglia}    # ECGhlCpt.int    ; Random Encounter Ghoul Patrol Capt.
{599}{}{una Guardia di Pattuglia}       # ECMutPat.int    ; Random Encounter Mutant Patrol
{600}{}{il Capitano della Pattuglia}    # ECMutCpt.int    ; Random Encounter Mutant Patrol Capt.
{601}{}{un Pastore di Brahmin}          # ECBraDrv.int    ; Random Encounter Brahmin Driver
{602}{}{un Ladro di Bestiame}           # ECBraRst.int    ; Random Encounter Brahmin Rustler
{603}{}{un Abusivo}                     # ECSquatr.int    ; Random Encounter Squatters
{604}{}{un Abolizionista}               # ECAbolst.int    ; Random Encounter Abolitionist
{605}{}{un Contrabbandiere}             # ECMonShn.int    ; Random Encounter Moonshine Runner
{606}{}{un Super Mutante}               # ECRogMut.int    ; Random Encounter Rogue Super Mutants
{607}{}{un Pescatore}                   # ECFshrmn.int    ; Random Encounter Fisherman
{608}{}{uno Schiavista}                 # ECSlaver.int    ; Random Encounter Slaver
{609}{}{un Trapper}                     # ECTrappr.int    ; Random Encounter Trapper
{610}{}{il figlio di Carlson}     # SCCarkid.int    ; Carlson's kid NCR map 2
{611}{}{Carlson}                        # SCCarlsn.int    ; Carlson NCR 2
{612}{}{}                               # Animfrv.int     ; Animate forever
{613}{}{l'Agente Jack}               # SCOfjack.int    ; Officer Jack NCR 1
{614}{}{l'Illuminata}                   # SCEnlOne.int    ; The Enlightened One NCR 1
{615}{}{Door}                           # diDoor.int      ; Den Auto Closing Door
{616}{}{Computer}                       # GsTerm.int      ; Gecko robot control terminal
{617}{}{un Brahmin}                     # SCBrahmn.int    ; NCR Map 4 Brahmin.
{618}{}{un Deathclaw}                   # SCDthcla.int    ; NCR Map 4 Deathclaw.
{619}{}{Exit Grid}                      # SIExit.int      ; NCR Map 4 Exit Grid control
{620}{}{Computer}                       # SSComp.int      ; NCR Map 1 computer terminal that blows up
{621}{}{Feargus}                        # SCFergus.int    ; NCR Map 2
{622}{}{Ariel}                          # OCAriel.int     ; Vault 13 Ariel
{623}{}{Fannie Mae}                     # RCFannie.int    ; Fannie Mae the hooker in Redding
{624}{}{Computer Terminal}              # OCComptr.int    ; Computer terminal in Vault 13
{625}{}{Dalia}                          # OCDalia.int     ; Dalia in Vault 13
{626}{}{Dar}                            # OCDar.int       ; Dar Deathclaw guard Vault 13
{627}{}{Dave}                           # OCDave.int      ; Dave NPC in Vault 13
{628}{}{Gordon}                         # OCGordon.int    ; Gordon the shrine temple dude
{629}{}{Out of Business Sign}           # ziClosed.int    ; Generic "Out of Business" signs
{630}{}{Reactor Control Machinery}      # gsReactr.int    ; Script to animate reactor
{631}{}{Jimmy}                          # OCJimmy.int     ; Jimmy guy in computer room Vault 13
{632}{}{Joseph}                         # OCJoseph.int    ; The Doctor in Vault 13
{633}{}{Matt}                           # OCMatt.int      ; Matt prisonner in Vault 13
{634}{}{}                               # RCFitRat.int    ; Redding Fighting Molerats
{635}{}{Map Script}                     # RedMEnt.int     ; Redding Mine Entrance Map Script
{636}{}{V13 map script}                 # vault13.int     ; Vault13 map script
{637}{}{Sandy}                          # OCSandy.int     ; Sandy Vault 13 child.
{638}{}{Box}                            # ziTmpBox.int    ; Generic Temporary swap box
{639}{}{Thearn}                         # OCThearn.int    ; Vault 13 Guard Thearn.
{640}{}{Box}                            # miGriBox.int    ; Modoc Grisham Merchant box
{641}{}{Box}                            # miJoBox.int     ; Modoc Jo Merchant box
{642}{}{Valdis}                         # OCValdis.int    ; Valdis guard in Vault 13
{643}{}{Computer Terminal}              # OSvdrcmp.int    ; Door computer vault 13 entrance
{644}{}{Metal Locker}                   # OILocker.int    ; Metal locker in Vault 13
{645}{}{Footlocker}                     # OIftlkr.int     ; Footlocker in Vault 13
{646}{}{una Guardia Deathclaw}           # OCgrunt.int     ; Generic Vault 13 Deathclaw guard
{647}{}{Goris}                          # OCGoris.int     ; Goris possible party NPC vault 13
{648}{}{Box}                            # miBalBox.int    ; Modoc Balthas Merchant box
{649}{}{Metal Locker}                   # siLocker.int    ; Guard's lockers in NCR 1
{650}{}{l'Imbroglione}                  # Cheater.int     ; Cheater Character
{651}{}{V15 map Script}                 # vault15.int     ; Vault 15 map script
{652}{}{Phil}                           # bcPhil.int      ; Phil the secret vault 15 entrance guard
{653}{}{Bill}                           # bcBill.int      ; Bill in Vault 15 Entrance
{654}{}{un Macellaio}                   # mcButchr.int    ; Slaughter house guys in Modoc
{655}{}{Dalia}                          # bcDalia.int     ; Guard who guards a trail and shows up in v13
{656}{}{John}                           # bcJohn.int      ; Vault 15 guy entrance
{657}{}{Jones}                          # BCJones.int     ; Vault 15 doctor
{658}{}{Karla}                          # BCKarla.int     ; Karla Vault 15 guard.
{659}{}{V15 Secrect entrance map}        # V15sent.int     ; Vault 15 secret entrance map
{660}{}{Rebecca}                        # BCRebecc.int    ; Vault 15 Rebecca
{661}{}{Door}                           # miDoor.int      ; Modoc Doors
{662}{}{un Deathclaw}                  # mcDthClw.int    ; Modoc Rose's "Chicken"
{663}{}{Roberta}                        # bcRobert.int    ; Roberta Vault 15 Entrance
{664}{}{Sara}                           # bcSara.int      ; Sara vault 15 Entrance
{665}{}{Zeke}                           # bcZeke.int      ; Zeke vault 15 Entrance mayor dude
{666}{}{un Brahmin}                     # bcBrahmn.int    ; Generic Brahmin in Vault15 Entrance
{667}{}{Wood Door}                      # BiEntDr.int     ; Trapped Vault15 entrance door
{668}{}{Chrissy}                        # BCCrissy.int    ; Crissy, Rebecca's daughter
{669}{}{Darion}                         # BCDarion.int    ; Big bad dude in Vault 15
{670}{}{una Guardia di Darion}           # BCDargrd.int    ; Darion's guard in Vault 15
{671}{}{il Cane di Darion}              # BCDardog.int    ; Darion's dog in Vault 15
{672}{}{Cassidy}                        # VCCasidy.int    ; Cassidy the  bar person in Vault City
{673}{}{Well}                           # miWell.int      ; Modoc Well
{674}{}{un Ratto-talpa}                 # mcMolRat.int    ; Modoc Shitter Mole Rat
{675}{}{Brahmin Chunk}                  # miBraMea.int    ; Modoc Brahmin Chunks
{676}{}{un Brahmin}                     # mcKilBra.int    ; Modoc Slaughterhouse brahmin
{677}{}{Elevator Door}                  # bsElev.int      ; Elevator door in V15sent
{678}{}{un Cane}                        # mcKilDog.int    ; Modoc Dog that hangs out at the slaughter house
{679}{}{un Ratto}                       # mcRat.int       ; Modoc Garden Rat
{680}{}{Sun Spot}                       # ziSunSpt.int    ; Generic Sun Spot
{681}{}{Bess}                           # mcBess.int      ; Modoc Bess the Brahmin
{682}{}{Box}                            # miJkyBox.int    ; Modoc Jerky box
{683}{}{una Croupier}                   # zcCrpDel.int    ; Craps Dealer
{684}{}{una Guardia del Vault 15}       # bcGenGrd.int    ; Vault 15 Khan Guard
{685}{}{uno Slag}                       # mcSlag.int      ; Modoc Generic Slag
{686}{}{Rug}                            # mtRug.int       ; Modoc Spacial Script for Rug
{687}{}{un Bambino}                     # mcChild.int     ; Modoc Child
{688}{}{Aileen}                         # hcAileen.int    ; Aileen in Broken Hills
{689}{}{una Guardia}                    # hcBnkGrd.int    ; Bank Guard in Broken Hills
{690}{}{Doc Holliday}                   # hcDoc.int       ; Doc in Broken Hills
{691}{}{un Seguace}                     # hcencha.int     ; Henchman A in Broken Hills
{692}{}{un Seguace}                     # hcenchb.int     ; Henchman B in Broken Hills
{693}{}{una Donna}                      # hcfemale.int    ; Female in Broken Hills
{694}{}{Francis}                        # hcFranci.int    ; Francis in Broken Hills
{695}{}{Frank}                          # hcFrank.int     ; Frank in Broken Hills
{696}{}{un Ghoul}                       # hcGhoul.int     ; Ghoul in Broken Hills
{697}{}{Liz}                            # hcLiz.int       ; Liz in Broken Hills
{698}{}{un Uomo}                        # hcmale.int      ; Male in Broken Hills
{699}{}{Manson}                         # hcManson.int    ; Manson in Broken Hills
{700}{}{Marcus}                         # hcMarcus.int    ; Marcus in Broken Hills
{701}{}{un Minatore}                    # hcMiners.int    ; Miners in Broken Hills
{702}{}{un Mutante}                     # hcMutant.int    ; Mutant in Broken Hills
{703}{}{Bill}                           # hcOutfit.int    ; Outfitter in Broken Hills
{704}{}{Phil}                           # hcPhil.int      ; Phil the bartender in Broken Hills
{705}{}{Steve}                          # hcSteve.int     ; Steve in Broken Hills
{706}{}{il Supervisore}                 # hcSuper.int     ; Supervisor in Broken Hills
{707}{}{Zaius}                          # hcZaius.int     ; Zaius in Broken Hills
{708}{}{Jacob}                          # hcJacob.int     ; Jacob in Broken Hills
{709}{}{Chemistry Set}                  # hchems.int      ; Chemistry Set in Broken Hills
{710}{}{Prop}                           # miGstPrp.int    ; Modoc Ghost Farm Prop
{711}{}{Door}                           # bssdor1.int     ; Shack doors on V15sEnt map
{712}{}{Computer}                       # BSComp1.int     ; Library Computer Vault 15
{713}{}{Chad}                           # hcchad.int      ; Chad from Broken Hills
{714}{}{una Pianta Sporigena}           # ECPlant.int     ; Random Encounter Spore Plant
{715}{}{}                               # ECGecko.int     ; Random Encounter Gecko
{716}{}{un Radscorpione}                # ECScorp.int     ; Random Encounter Scorpions
{717}{}{}                               # ECRat.int       ; Random Encounter Rats
{718}{}{un Guerriero}                   # ECWarPty.int    ; Random Encounter War Party
{719}{}{un Cannibale}                   # ECCanibl.int    ; Random Encounter Cannibals
{720}{}{un Reietto}                     # ECOutCst.int    ; Random Encounter Outcasts
{721}{}{un Uomo di Chiesa}              # ECHlyPpl.int    ; Random Encounter Holy People
{722}{}{un Nomade}                      # ECNomad.int     ; Random Encounter Nomads
{723}{}{un Senzatetto}                  # ECHomles.int    ; Random Encounter Homeless
{724}{}{un Bandito}                     # ECBandit.int    ; Random Encounter Bandit
{725}{}{un Ladro}                       # ECRobber.int    ; Random Encounter Robber
{726}{}{un Rapinatore}                  # ECHiwymn.int    ; Random Encounter Highwaymen
{727}{}{uno Schiavista}                 # ECSlvRun.int    ; Random Encounter Slavers on a Slave Run
{728}{}{uno Schiavo}                    # ECSlave.int     ; Random Encounter Slaves
{729}{}{un Partecipante al Party}       # ECRavPty.int    ; Random Encounter Rave Party
{730}{}{una Mantide}                    # ECMantis.int    ; Random Encounter Mantis
{731}{}{un Brahmin}                     # ECBrahmn.int    ; Random Encounter Brahmin
{732}{}{un Cane Selvatico}                       # ECWldDog.int    ; Random Encounter Wild Dogs
{733}{}{Computer}                       # BSComp2.int     ; Darion's computer terminal Vault15
{734}{}{Computer}                       # BSComp3.int     ; Force field computer terminal
{735}{}{Computer Terminal}              # BSComp4.int     ; Force Field control computer by entrance Vault 15
{736}{}{Computer}                       # BSComp5.int     ; Computer at the Power area. Vault 15
{737}{}{Power Generator}                # BSPower.int     ; Power Generator in Vault 15
{738}{}{Force Field}                    # BSField.int     ; Force Field in Vault 15
{739}{}{un Contadino}                   # mcPeasan.int    ; Modoc Peasant Person
{740}{}{Emitter}                        # bsEmtr.int      ; Emitter in Vault 15
{741}{}{Vault Door}                     # osv13dr.int     ; Vault 13 Door
{742}{}{Security Door}                  # osDoor1.int     ; Vault 13 Door that shows deathclaws
{743}{}{Bess Encounter}                 # rndBess.int     ; Random Encounter for Bess outside of modoc
{744}{}{Bess}                           # ECBess.int      ; Bess in Bess's Encounter (she's dead jim)
{745}{}{un Brahmin}                     # ECBesCow.int    ; One of the Brahmin in Bess's herd
{746}{}{Angela Bishop}                  # ncAngBis.int    ; New Reno Angela Bishop
{747}{}{Tommy "The Balls"}              # ncTommy.int     ; New Reno Tommy the Balls (YEAH! OUR HERO)
{748}{}{Safe}                           # niABisSf.int    ; New Reno Angela Bishop's Safe
{749}{}{Safe}                           # niMrBSf.int     ; New Reno Mr. Bishop's Safe
{750}{}{Safe}                           # niMrsBSf.int    ; New Reno Mrs. Bishop's Safe
{751}{}{Safe}                           # niOWriSf.int    ; New Reno Orville Wright's Safe
{752}{}{Grave}                          # niPriGrv.int    ; New Reno Pritchard's Grave
{753}{}{Dresser}                        # niWridrs.int    ; New Reno Richard Wright's Dresser
{754}{}{Grave}                          # niWriGrv.int    ; New Reno Righard Wright's Grave
{755}{}{Still}                          # niWriSti.int    ; New Reno Wright Stills
{756}{}{Ramirez}                        # ncRamire.int    ; New Reno Ramirez
{757}{}{Cave 1 Random Encounter Map}    # cave01.int      ; Cave 1 Random Encounter Map
{758}{}{Box}                            # niRenBox.int    ; New Reno Renesco Box
{759}{}{Door}                           # niDoor.int      ; New Reno Door
{760}{}{Cave 2 Random Encounter Map}    # cave02.int      ; Cave 2 Random Encounter Map
{761}{}{Cave 3 Random Encounter Map}    # cave03.int      ; Cave 3 Random Encounter Map
{762}{}{Cave 4 Random Encounter Map}    # cave04.int      ; Cave 4 Random Encounter Map
{763}{}{Cave 2 Random Encounter Map}    # cave02.int      ; Cave 2 Random Encounter Map
{764}{}{Door}                           # VIEntDor.int    ; Vault City Entrance Door
{765}{}{Map Script}                     # VCtyDwtn.int    ; Vault City Downtown Map script
{766}{}{Trap Door}                      # miTrpDor.int    ; Modoc Ghost Farm Trap Door
{767}{}{Lockbox}                        # Hilbox.int      ; Broken Hills Liz inventory box
{768}{}{Room}                           # ntLydRom.int    ; New Reno Lloyd Room
{769}{}{Thomas Moore}                   # VCMoore.int     ; Thomas Moore from Vault City
{770}{}{Door}                           # ZILckDor.int    ; Generic Locked Door (-20)
{771}{}{Locker}                         # niLydBox.int    ; New Reno Lloyd's Loot Box
{772}{}{Manhole}                        # niManhol.int    ; New Reno Manhole to Lloyd's Loot
{773}{}{Grave}                          # niLydGrv.int    ; New Reno Lloyd's Loot Grave
{774}{}{la Guardia del Magazzino}       # VCSupGrd.int    ; Vault City Supply Guard Martin
{775}{}{Map Script}                     # broken1.int     ; Map Script for Broken Hills Map 1
{776}{}{Map Script}                     # rndexcow.int    ; Map Script for Low Luck encounter
{777}{}{un Brahmin Pazzo}               # eccowbmb.int    ; The cows that blow
{778}{}{Hakeswill}                      # RCHakes.int     ; Hakeswill from Redding
{779}{}{Redding Downtown}               # REDDown.int     ; Redding Downtown map script
{780}{}{Map Script}                     # BHRndDst.int    ; Broken Hills Caravan Desert Map
{781}{}{Map Script}                     # BHRndMtn.int    ; Broken Hills Caravan Mountain Map
{782}{}{Lou}                            # RCLou.int       ; Lou from Redding
{783}{}{Artu'}                          # ECArthur.int    ; Arthur the leader of the Special Encounter knights
{784}{}{Robin}                          # ECRobin.int     ; Robin one of the Knights with Arthur
{785}{}{Bedemir}                        # ECBedemi.int    ; Bedemir one of the Knights with Arthur
{786}{}{Sir Lancillotto}                # ECSirLau.int    ; Sir Launcelot one of the Knights with Arthur
{787}{}{Galahad}                        # ECGalaha.int    ; Galahad one of the knights with Arthur
{788}{}{Ben Wade}                       # RCWade.int      ; Ben Wade from Radding
{789}{}{Athabaska Dick}                 # RCDick.int      ; Athabaska Dick from Redding
{790}{}{la Vedova Rooney}               # RCRooney.int    ; Widow Rooney from Redding
{791}{}{un Abitante}                    # RCGenPes.int    ; Generic Townsperson in Redding
{792}{}{Stanwell}                       # RCStanwl.int    ; Stannwell from Redding
{793}{}{Savinelli}                      # RCSavine.int    ; Savinelli from Redding
{794}{}{Marge}                          # RCMarge.int     ; Marge LeBarge from Redding
{795}{}{Madame Modjeska}                # RCModjes.int    ; Madam Modjeska from Redding
{796}{}{James Hoffy}                    # RCHoffy.int     ; James Hoffy, Caravan Master for Redding
{797}{}{Map Script}                     # Rndholy1.int    ; Random Encounter Holy Knights 1 map
{798}{}{Patsy}                          # ECPatsy.int     ; Arthur's horse HOLY 1 encounter
{799}{}{Concorde}                       # ECConcor.int    ; Concord Launcelot's horse.
{800}{}{Eric}                           # ECEric.int      ; Robin's horse
{801}{}{John}                           # ECJohn.int      ; Bedemir's horse
{802}{}{Joshua}                         # ECJoshua.int    ; Joshua Robin's minstrel
{803}{}{Ladder}                         # miLadder.int    ; Modoc Shitter Ladder
{804}{}{la Testa Enorme}                # ecBHead.int     ; Big Head special encounter
{805}{}{L'Eroe Nero}                    # ecBlkHro.int    ; Black Hero model
{806}{}{l'Eroina Rossa}                 # ecRedHro.int    ; Red Heroine model
{807}{}{Set}                            # ecSet.int       ; Set in Cafe of Broken Dreams
{808}{}{Tandi}                          # ecTandi.int     ; Tandi in Cafe of " "
{809}{}{un Eroe Bianco}                 # ecWhro1.int     ; White Hero Model 1 " " "
{810}{}{un Eroe Bianco}                 # ecWhro2.int     ; White Hero Model 2 " " "
{811}{}{un'Eroina Rossa}                # ecWheon1.int    ; White Heroine Model 1
{812}{}{Box}                            # NiJulBox.int    ; New Reno Jules Shop Inventory Box
{813}{}{Box}                            # niEldBox.int    ; New Reno Eldridge Shop Box
{814}{}{Box}                            # niEldBx2.int    ; New Reno Eldridge Shop Box (For Made Men)
{815}{}{Map Script}                     # rndholy2.int    ; Hi-Luck random Holy knight encounter 2
{816}{}{il Ratto Vorpal}                # ECVorRat.int    ; Vorpal Rat for Holy Knight 2
{817}{}{un Cane}                        # ECPDog.int      ; Pariah Dog... not good to have following you around
{818}{}{il Sergente Istruttore}                 # CCDrill.int     ; Drill Seargant in Colusa/Nevarro
{819}{}{una Guardia}                    # CCGuard.int     ; Guard in Colusa/Nevarro
{820}{}{un Tecnico}                     # CCTech.int      ; Technician in Colusa/Nevarro
{821}{}{il Comandante}                  # CCMandr.int     ; Commander in Colusa Nevarro
{822}{}{Chris}                          # CCChris.int     ; Chris the gas station attendant in Colusa
{823}{}{il Furiere}                 # CCMaster.int    ; Quarter Master in Colusa/Nevarro
{824}{}{una Guardia}                    # CCGGuard.int    ; Gate Guard in Colusa/Nevarro
{825}{}{Grave}                          # ntLydGrv.int    ; New Reno Lloyd's Loot Grave (Spacial Script)
{826}{}{Car}                            # ntCar1.int      ; New Reno Stolen Car Seed Spacial 1
{827}{}{Car}                            # ntCar2.int      ; New Reno Stolen Car Seed Spacial 2
{828}{}{Grave}                          # niMorGrv.int    ; New Reno Mordino Stash Grave
{829}{}{il Figuro Incappucciato}        # EcBridge.int    ; Bridge guy special encounter
{830}{}{un Compratore di Bestiame}      # SCdrvpay.int    ; Cattle drive from NCR to redding.
{831}{}{Map Script}                     # RndBridg.int    ; Random Bridge encounter
{832}{}{lo Straniero Misterioso}        # ECMstStr.int    ; Mysterious Stranger
{833}{}{un Brahmin Pazzo}                    # ECgcwbmb.int    ; Generic Cow bomb
{834}{}{un Membro della Yakuza}                  # ECYakuza.int    ; Random Encounter Yakuza
{835}{}{un Primitivo}                         # ECWilder.int    ; Random Encounter Wilder
{836}{}{un Cane}                        # ncWriDog.int    ; New Reno Wright Dog
{837}{}{Box}                            # niRamBox.int    ; New Reno Box to be delivered to Ramirez
{838}{}{un Membro della Pattuglia}                  # ECUniPat.int    ; Unity Patrol Random Encounter
{839}{}{un Viaggiatore}                       # ECTravlr.int    ; Random Encounter Travler
{840}{}{Smoke}                          # KtSmoke.int     ; displays message about smoke smell in Duntons
{841}{}{un Commerciante}                # ECTrader.int    ; Random Encounter Trader
{842}{}{uno Sciacallo}                  # ECScaven.int    ; Random Encounter Scavenger
{843}{}{un Mercante}                    # FCMercha.int    ; San Fran Air bag merchant
{844}{}{un Contadino}                   # FCBadPea.int    ; San Fran Bad Peasants
{845}{}{Arroyo Temple}                  # ARTemple.int    ; Arroyo Temple map script
{846}{}{un Lavoratore del Porto}        # FCDokWrk.int    ; San Fran Dock Worker
{847}{}{un Contadino}                   # FCGudPea.int    ; San Fran Good Peasants
{848}{}{una Guardia Shi}                # FCShiGrd.int    ; San Fran Shi Guard
{849}{}{Cameron}                        # ACTemVil.int    ; Temple challenge person
{850}{}{Door}                           # AITemDor.int    ; Temple doors that lock at the challenge
{851}{}{Klint}                          # ACKlint.int     ; Klint the guardian of the temple exit
{852}{}{Crops}                          # AICrops.int     ; Crops that die after a period of time
{853}{}{un Tecnico del Laboratorio Shi} # FCslabte.int    ; San Fran Shi Lab techs
{854}{}{un Bambino}                          # FCSkids.int     ; San Fran Shi Kids
{855}{}{un Ghoul}                       # GCWander.int    ; wandering ghouls in Gecko
{856}{}{il Dr. Fung}                        # FCDrFung.int    ; San Fran Dr Fung
{857}{}{Jul}                            # OCJul.int       ; Vault 13 Denmother Guard
{858}{}{Kerith}                         # OCKerith.int    ; Vault 13 Den Mother
{859}{}{Chest}                          # AITemCst.int    ; Temple Chest to hold the players things
{860}{}{un Ghoul}                       # GCRGhul.int     ; Reactor ghoul that doesn't move
{861}{}{}                               # ECRaiBow.int    ; Random Encounter Gays
{862}{}{}                               # ECMstAmy.int    ; Random Encounter Master's Army
{863}{}{un Cercatore}                   # ECProspe.int    ; Random Encounter Prospector
{864}{}{un Membro della Gang}                    # ECPrsGng.int    ; Random Encounter Press Gang
{865}{}{il Capo Nomade}                 # ECNomChf.int    ; Random Encounter Nomad Chief
{866}{}{un Hubologista}                 # ECElRon.int     ; Hubologist Patrol
{867}{}{un Pazzo}                          # ECCrazy.int     ; Crazies from Random Encounter
{868}{}{un Cacciatore di Concessioni}   # ECClmJmp.int    ; Random Encounter Claim Jumpers
{869}{}{un Cannibale}                   # ECCanbal.int    ; Random Encounter Cannibals
{870}{}{lo Sciamano Nomade}              # ECNomSha.int    ; Random Encounter Nomad Shamon
{871}{}{un Razziatore}                  # ECMaradr.int    ; Random Encounter Marauder
{872}{}{un Furfante}                    # ECRogue.int     ; Random Encounter Rogue
{873}{}{un Eremita}                      # ECHermit.int    ; Random Encounter Hermit
{874}{}{}                               # ECGangs.int     ; Random Encounter Gangs
{875}{}{il Capo della Carovana}         # ECMstKla.int    ; Random Encounter Klamath Caravan Master
{876}{}{il Capo della Carovana}         # ECMstDen.int    ; Random Encounter Den Caravan Master
{877}{}{il Capo della Carovana}         # ECMstNew.int    ; Random Encounter New Reno Caravan Master
{878}{}{il Capo della Carovana}         # ECMstRed.int    ; Random Encounter Redding Caravan Master
{879}{}{il Capo della Carovana}         # ECMstBro.int    ; Random Encounter Broken Hills Caravan Master
{880}{}{il Capo della Carovana}         # ECMstGec.int    ; Random Encounter Gecko Caravan Master
{881}{}{il Capo della Carovana}         # ECMstSan.int    ; Random Encounter San Fran Caravan Master
{882}{}{il Capo della Carovana}         # ECMstNCR.int    ; Random Encounter NCR Caravan Master
{883}{}{il Capo della Carovana}         # ECMstV15.int    ; Random Encounter Vault 15 Caravan Master
{884}{}{la Moglie del Contadino}        # ECFrmWfe.int    ; Random Encounter Farmer's wife
{885}{}{il Figlio del Contadino}        # ECFrmKid.int    ; Random Encounter Farmer's Kid
{886}{}{un Colono}                      # ECHomest.int    ; Random Encounter Homesteader
{887}{}{la Moglie del Colono}           # ECHomwfe.int    ; Random Encounter Homesteader's Wife
{888}{}{Il Figlio del Colone}           # ECHomKid.int    ; Random Encounter Homesteader's Kid
{889}{}{il Capo della Carovana}         # ECMstVC.int     ; Random Encounter Vault City Caravan Master
{890}{}{}                               # ECAlien.int     ; Random Encounter Alien
{891}{}{}                               # ECDthclw.int    ; Random Encounter Deathclaws
{892}{}{}                               # ECFloatr.int    ; Random Encounter Floater
{893}{}{}                               # ECCentur.int    ; Random Encounter Centaurs
{894}{}{un Soldato dell'Enclave} # ECElvPat.int    ; Random Encounter Enclave Patrol
{895}{}{un Capitano di Merc}            # icMrcCpt.int    ; Raiders Merc Captain
{896}{}{un Predone di Merc}             # icMerc.int      ; Raiders Merc
{897}{}{"Ombra-che-Cammina"}            # icScout.int     ; Raiders Scout
{898}{}{Safe}                           # iiSafe.int      ; Raiders Safe
{899}{}{}                               # raiders1.int    ; Raiders 1 Enterance
{900}{}{}                               # raiders2.int    ; Raiders 2 Caves
{901}{}{}                               # HSCellDr.int    ; Broken Hills bank/jail door
{902}{}{Box}                            # niTRyBox.int    ; New Reno Chop Shop T-Ray Box
{903}{}{il Presidente Richardson}       # qhPrzRch.int    ; Enclave President Richardson talking head.
{904}{}{Howitzer}                       # WIHowitz.int    ; Howitzer in the Sierra Base
{905}{}{Door}                           # WIEntDor.int    ; Entrance to Sierra Base Door
{906}{}{un cucciolo di Deathclaw}       # OCBabDth.int    ; Baby Deathclaws in Vault 13
{907}{}{Dangerous Dan}                  # RCMcGrew.int    ; Dangerous Dan McGrew from redding
{908}{}{Doc Johnson}                    # RCDrJohn.int    ; Painless Doc Johnson (breaks Jet)
{909}{}{lo Sceriffo Marion}             # RCMarion.int    ; Sheriff Earl Marion
{910}{}{il Sindaco Ascorti}             # RCAscort.int    ; Mayor Ascorti of Redding
{911}{}{Nording}                        # RCNord.int      ; Nording, the payoff man for Stanwell
{912}{}{Velani}                         # RCVelani.int    ; Velani, the payoff man for Savinelli
{913}{}{Ferndown}                       # RCFern.int      ; Ferndown, the payoff man for Wade
{914}{}{Dragon}                         # FCDragon.int    ; The Dragon, San Fran
{915}{}{uno Stalliere}                  # mcSblBoy.int    ; Modoc Stable Boy
{916}{}{un Commerciante}                # mcTrader.int    ; Modoc Trader
{917}{}{un Abitante}                    # mcPerson.int    ; Modoc Townspeople
{918}{}{uno Slag}                       # mcSlgExt.int    ; Ghost Farm Slag Exit Guard
{919}{}{uno Slag}                       # mcSlgGrd.int    ; Ghost Farm Slag Enterance Guard
{920}{}{Lo Pan}                         # FCLoPan.int     ; Lo Pan in San Fran.
{921}{}{Badger}                         # FCBadger.int    ; Badger in San Fran.
{922}{}{Josh}                           # RCJosh.int      ; Josh Laurance of Redding
{923}{}{Caminetto}                      # RCCamint.int    ; Caminetto in bar fight in redding
{924}{}{Bette}                          # RCBette.int     ; Blasphemous Bette in bar fight in redding
{925}{}{Mai Da Chiang}                  # FCGunmer.int    ; San Fran's gun Merchant
{926}{}{Door}                           # ZIWodDor.int    ; Generic Wooden Door
{927}{}{Door}                           # ZIMtlDor.int    ; Generic Metal Door
{928}{}{Emitter}                        # SSEmtN2.int     ; Emitter in NCR area 2
{929}{}{il Dio Ratto}                   # ZCRatGod.int    ; Rat God in Klamath
{930}{}{}                               # ECBox.int       ; Random box that has stuff in it.
{931}{}{Kaga}                           # ECKaga1.int     ; Random Encounter Kaga 1
{932}{}{Kaga}                           # ECKaga2.int     ; Random Encounter Kaga 2
{933}{}{Kaga}                           # ECKaga3.int     ; Random Encounter Kaga 3
{934}{}{Kaga}                           # ECKaga4.int     ; Random Encounter Kaga 4
{935}{}{Kaga}                           # ECKaga5.int     ; Random Encounter Kaga 5
{936}{}{un Cacciatore di Taglie}        # ECBHunter.int   ; Random Encounter Bounty Hunter
{937}{}{Computer}                       # VIMedCom.int    ; Vault City Medical Computer
{938}{}{Computer}                       # VICenCom.int    ; Vault City Central Computer
{939}{}{Computer}                       # VIAloCom.int    ; Vault City Allocation Computer
{940}{}{Darrow}                         # VCDarrow.int    ; Vault City Sub-Amenities Officer Darrow
{941}{}{Farrel}                        # VCFarrel.int    ; Vault City Sub-Amenities Officer Farrell
{942}{}{un Cliente del Bar}             # VCBarPat.int    ; Vault City Bar Patron
{943}{}{un Cittadino del Vault}         # VCWrkCit.int    ; Vault City Working Citizen
{944}{}{un Servo del Vault}             # VCSlave.int     ; Vault City Slave
{945}{}{Ventilation Shaft}              # VIShft2b.int    ; Vault City Ventilation Shaft 2B
{946}{}{Charlie}                        # VCCharli.int    ; Vault City Puking Charlie
{947}{}{Coolant Control Panel}          # GSValve.int     ; Gecko Coolant Control Panel
{948}{}{Poo}                            # ziBraPoo.int    ; Generic BRAHMIN SHIT!!! YES YES YES
{949}{}{Grant}                          # scWesGrd.int    ; Westin's Force Field Guard
{950}{}{Emitter}                        # SSEmiWes.int    ; Westin's Force Field Emitter
{951}{}{Emitter}                        # SSEmiWe1.int    ; Westin's force field on the other map.
{952}{}{Computer Terminal}              # SICmpWes.int    ; Westin's computer terminal for the field.
{953}{}{il Computer Imperatore v8.8}    # FSEmpTer.int    ; Computer Terminal in San Fran
{954}{}{il Vicepresidente Bird}         # QCBird.int      ; Enclave, Vice President Bird
{955}{}{Martin}                         # QCMartin.int    ; Enclave, Martin Frobishner, V13 spokesman
{956}{}{Ken Lee}                        # FCKenLee.int    ; Ken Lee in San Francisco
{957}{}{il Ser. Granite}                # QCGranit.int    ; Sgt. Granite of the Enclave Patrol
{958}{}{Frank Horrigan}                 # QCFrank.int     ; Secret Service Agent Frank (End Boss)
{959}{}{Map Script}                     # GeckJunk.int    ; Map Script for Gecko Junkyard
{960}{}{Map Script}                     # GeckTunl.int    ; Map Script for Gecko Tunnels
{961}{}{Door}                           # SSFrgDor.int    ; Fergus's Door script
{962}{}{Door}                           # SSGunDor.int    ; Gunther's Door script to Tandi
{963}{}{Door}                           # SSFlxDor.int    ; Felix's Door script
{964}{}{Rope}                           # SSRope.int      ; Rope.. for you to climb
{965}{}{Emitter}                        # SSEmiEnt.int    ; Emitter in Ncr Entrance
{966}{}{il Dr. Curling}                    # QCCurlng.int    ; Dr. Charles Curling, Chem Corps.
{967}{}{Bulletin Board}                 # SSSign.int      ; Sign in NCR Entrance
{968}{}{un Ratto-talpa}                 # mcMolRat.int    ; Ghost Farm Mole Rat
{969}{}{la Segretaria del Presidente}   # QCPrsSec.int    ; President's personal intern (uh sectertary)
{970}{}{Tom Murray}                     # QCMurray.int    ; Tom Murray, head of AEC
{971}{}{Sturdy Door}                    # SSCrpDor.int    ; Craps table door in NCR
{972}{}{un Paesano}                     # mcPeasan.int    ; Modoc Peasant, they attack the farm
{973}{}{Vault City Council Area}        # VCtyCocl.int    ; Map Script Vault City Council Area
{974}{}{Air Purifier}                   # HSPurify.int    ; Air Purifier for Broken Hills
{975}{}{Rocks}                          # esEntRks.int    ; Military Base Entrance Rocks
{976}{}{un Giocatore d'Azzardo}         # RCGamble.int    ; Redding Generic Gamblers
{977}{}{Spatial Script}                 # HtCorpse.int    ; Spatial Script for Corpses
{978}{}{SCCheat}                        # SCCheat.int     ; Cheat Character for NCR
{979}{}{un Prigioniero}                 # QCGenPrs.int    ; Enclave Generic Prisoner
{980}{}{un Cittadino}                   # QCGenCit.int    ; Enclave Generic Citizens
{981}{}{una Guardia}                    # QCGenGrd.int    ; Enclave Generic Guards
{982}{}{uno Scienziato}                 # QCGenSci.int    ; Enclave Generic Scientist
{983}{}{un Terminale}                   # QIPzlTrm.int    ; Enclave terminal in the Puzzle Level
{984}{}{}                               # etEnter.int     ; Military Base Enterance Spacial Message
{985}{}{}                               # etBattle.int    ; Military Base Battle Area Spacial Message
{986}{}{Emitter}                        # SSEmiEn1.int    ; Ncr emitters for ncr entrance on map 1
{987}{}{Blast Door}                     # QIBstDr1.int    ; Blast Door for Reactor Off to remain closed
{988}{}{Blast Door}                     # QIBstDr2.int    ; Blast Door for Reactor On to remain closed
{989}{}{Darrow's Stock}                 # VIDarBox.int    ; Vault City Darrow Shop Inventory
{990}{}{Door}                           # HSCrlDr.int     ; Jail cell door for Broken Hills
{991}{}{un Super Mega Mutante}          # ecTlkMut.int    ; Military Base Conversation Mutants
{992}{}{il Dr. Jing Tie Gahng}             # fcChemst.int    ; Chemist in San Francisco
{993}{}{Grundel}                        # ecGrunde.int    ; Military Base Mouse Hunter
{994}{}{Melchior Jr.}                   # ecMelKid.int    ; Some Town USA, Melchior's Kid
{995}{}{Retinal Scanner}                # WIRetScn.int    ; Retinal Scanner in the Sieera Base
{996}{}{Elevator Door}                  # WIElvDor.int    ; Elevator Door in the Seirra Base
{997}{}{Cybernetic Receptacle}          # WIBrkBrn.int    ; Broken Brain Bot in the Sierra Base
{998}{}{Wall}                           # WIScrtDr.int    ; Sierra Base Secert Door
{999}{}{Map Script}                     # broken2.int     ; Map Script for Broken Hills Map 2
{1000}{}{Farrell's Stock}               # VIFarBox.int    ; Vault City Farrell Shop Inventory
{1001}{}{Harry's Stock}                 # VIHarBox.int    ; Vault City Harry Shop Inventory
{1002}{}{Box}                           # VICtyBox.int    ; Vault City Courtyard Temp Inventory Box
{1003}{}{Box}                           # VIDwtBox.int    ; Vault City Downtown Temp Inventory Box
{1004}{}{Derek}                         # dcDerek.int     ; Derek in the Den
{1005}{}{un Amico di Tubby}             # dcTubFri.int    ; Tubby's Junkie Friends in the Den
{1006}{}{un Giocatore d'azzardo}        # dcGamble.int    ; Gamblers in the Den
{1007}{}{uno Schiavo}                   # dcSlave.int     ; Pen Slaves in the Den
{1008}{}{una Guardia}                   # dcMetRom.int    ; Metzger Room Guard in the Den
{1009}{}{uno Schiavista}                # dcPenGrd.int    ; Slaver Pen Guard in the Den
{1010}{}{Lara}                          # dcLara.int      ; Lara in the Den
{1011}{}{Tyler}                         # dcTyler.int     ; Tyler in the Den
{1012}{}{Marc}                          # dcMarc.int      ; Marc in the Den
{1013}{}{Bulletin Board}                # diBulBrd.int    ; Bulletin Board in the Den
{1014}{}{uno Schiavista}                # dcVicGrd.int    ; Vic Guard in the Den
{1015}{}{uno Schiavista}                # dcSlvGrt.int    ; Slaver Greeter in the Den
{1016}{}{Fred}                          # dcFred.int      ; Fred in the Den
{1017}{}{Box}                           # diFliBox.int    ; Flick Box in the Den
{1018}{}{Box}                           # diMomBox.int    ; Mom Box in the Den
{1019}{}{Box}                           # diSmiBox.int    ; Smitty Box in the Den
{1020}{}{Car Trunk}                     # ZICrTrnk.int    ; generic script for Car Trunk
{1021}{}{Security Door}                 # QIPzlDor.int    ; Door for the puzzle room in the Enclave
{1022}{}{Computer Terminal}             # FSPhySta.int    ; Physics computer station in San Fran
{1023}{}{Computer Terminal}             # FSBioSta.int    ; Biology computer station in San Fran
{1024}{}{Computer Terminal}             # FSCheSta.int    ; Chemistry computer station in San Fran
{1025}{}{Lao Chou}                      # FCLaoCho.int    ; Merchant in San Fran
{1026}{}{}                              # FIPaper.int     ; Scrap Papers that combine should only be put on one of the peaces.
{1027}{}{Ventilation Shaft}             # CSVent.int      ; Ventilation shaft for Navarro
{1028}{}{Map Script}                    # EncTrp.int      ; Map Script for Enclave Trap Rooms
{1029}{}{Dead Body}                     # HtBody.int      ; Script for dead bodies in Broken Hills
{1030}{}{Exposed wires}                 # QIWires.int     ; Wires on the ground in the trap room
{1031}{}{Box}                           # diMetBox.int    ; Metzger Box from Slave Crap
{1032}{}{uno Schiavo}                   # dcRunSlv.int    ; Den Slave Run Fleeing Slaves
{1033}{}{uno Schiavo}                   # dcAtkSlv.int    ; Den Slave Run Hostile Slaves
{1034}{}{uno Schiavista}                # dcRnSlvr.int    ; Den Slave Run Slavers
{1035}{}{Chip}                          # FCChip.int      ; Chip in San Fran no spleen
{1036}{}{Reactor}                       # QIReactr.int    ; Reactor in the Enclave
{1037}{}{Reactor Computer}              # QIRctrCm.int    ; Reactor Computer in the Enclave
{1038}{}{il Cassiere}                   # RCCshTnd.int    ; Redding Cash Tender in the Casino
{1039}{}{Cash Box}                      # RICshBox        ; Cash Box for the Cash Tender
{1040}{}{un Wanamingo}                  # RCWanami.int    ; Wanamingo
{1041}{}{un Cliente del Bar}           # dcStory1.int    ; Story Teller 1 in the Den
{1042}{}{un Cliente del Bar}           # dcStory2.int    ; Story Teller 2 in the Den
{1043}{}{Jail Door}                     # RIJalDor.int    ; Jail Door in Redding
{1044}{}{Suze}                          # FCSuze.int      ; Suze in San Fran
{1045}{}{il Capitano Ron Meyers}        # FCRonMey.int    ; Captain Ron Meyers
{1046}{}{Pen Door}                      # diPenDor.int    ; Slave Pen Door in the Den
{1047}{}{Wanamingo Mine}                # RedWan1.int     ; Map Script for Wanamingo Mine
{1048}{}{Wanamingo Mine Entrance}       # RedWane.int     ; Map Script for Wanamingo Mine Entrance
{1049}{}{Frog Morton}                   # RCFrog.int      ; Frog Morton
{1050}{}{Dave H.}                       # FCDaveh.int     ; Dave Handy in San Fran
{1051}{}{Door}                          # diVicDor.int    ; Vic's Room Door in the Den
{1052}{}{Door}                          # diRomDor.int    ; Metzger's Room Door in the Den
{1053}{}{"Vomitino" Charlie}            # vccharly.int    ; Puking Charlie in Vault Courtyard
{1054}{}{Painting}                      # SIPaint.int     ; Revales Vault 13 on examination.
{1055}{}{Map Script}                    # SFChina.int     ; San Fran China Map
{1056}{}{il Barista}                    # VCCouBar.int    ; Vault City Council Area Bartender
{1057}{}{Box}                           # VIBarBox.int    ; Vault City Slave Sale Inventory Dump
{1058}{}{Auto-Doc}                      # VIAutDoc.int    ; Vault City Courtyard Auto-Doc
{1059}{}{}                              # RIMinEnt.int    ; Entrance Back to the Mines
{1060}{}{Mining Tunnel}                 # RedMTun.int     ; Map Script for Mining Tunnel
{1061}{}{un Robot}                      # KCRob.int       ; Robot on Klamath Canyon
{1062}{}{}                              # FiGunTbl.int    ; Gun Merchant table in San fran
{1063}{}{Map Script}                    # KlaMall.int     ; Map Script for Klamath Mall area
{1064}{}{Map Script}                    # KlaTrap.int     ; Map Script for Klamath Still area
{1065}{}{Lydia}                         # VCDwnBar.int    ; Vault City Downtown Bartender
{1066}{}{}                              # RedDTun.int     ; Redding Downtown Tunnels
{1067}{}{Harry l'Addetto al Razzo}           # FCRocMan.int    ; Rocket man in San Fran
{1068}{}{AHS-7}                         # FCOz7.int       ; Oz 7 in San Fran
{1069}{}{Crockett}                      # FCCrocke.int    ; Crockett in San Fran
{1070}{}{Amanda}                        # VCAmanda.int    ; Vault City Coutryard Amanda, Joshua's Wife
{1071}{}{Joshua}                        # VCJoshua.int    ; Vault City Courtyard Joshua, Slave
{1072}{}{Valerie}                       # VCMainWk.int    ; Valerie, Vic's Daughter and Maintence Worker
{1073}{}{Teaching System}               # VITeach.int     ; Vault City Teaching System
{1074}{}{Crate}                         # diCrate.int     ; Den Crate in Church
{1075}{}{il Tipo che Piscia}            # VCUrine.int     ; Peeing Guy in Vault City Council Area
{1076}{}{Curtis}                        # VCCurtis.int    ; Curtis, Amanda and Joshua's Son
{1077}{}{Marc}                          # FCMarc.int      ; Marc, Punk in San Fran
{1078}{}{Computer}                      # FSElComp.int    ; Hubologists computer
{1079}{}{AHS-9}                         # FCOz9.int       ; Hubologist main dude
{1080}{}{una Guardia}                   # FCElGrd.int     ; Hubologist's guards
{1081}{}{Pile of rocks}                 # VIRocks.int     ; Pile of Rocks w/ Hidden Wrench
{1082}{}{Door}                          # VIVltDor.int    ; Vault City 2nd floor doors
{1083}{}{una Guardia}                   # dcRebGrd.int    ; Den Rebecca Guard
{1084}{}{una Guardia}                   # dcRebDor.int    ; Den Rebecca Door Guard
{1085}{}{Door}                          # diRebDor.int    ; Den Rebecca Door
{1086}{}{Wanted Sign}                   # ZSWsign.int     ; Generic Wanted Sign
{1087}{}{il Dr. Wong}                      # FCDrWong.int    ; Dr. Wong in San Fran area
{1088}{}{Table}                         # FIlaotbl.int    ; Lao Cho's stock tables in san Fran
{1089}{}{Door}                          # WILv1Dor.int    ; Locked Door on Level 1 Entrance               # local_vars=8
{1090}{}{una Punk}                      # FCFemPnk.int    ; San Fran Female punk
{1091}{}{un Punk}                       # FCMalPnk.int    ; San Fran Male Punk
{1092}{}{Ryan}                          # FCRyan.int      ; San Fran Punk Ryan
{1093}{}{Box}                           # HIBh1Box.int    ; Broken Hills Temp Inventory Box
{1094}{}{}                              # FCJuavki.int    ; Juan and Vikkin in San Fran Elron Camp
{1095}{}{Manhole}                       # HIManHol.int    ; Manhole to Basement in Liz's Store
{1096}{}{Map Script}                    # SFElronb.int    ; Elron Base map Script
{1097}{}{Ladder}                        # HILadder.int    ; Ladder up to Liz's Store
{1098}{}{Punching Bag}                  # WIPnchBg.int    ; Punching Bag in the Sierra Depot
{1099}{}{Door}                          # WIBayDor.int    ; Sierra Base Repair Bay Door
{1100}{}{Alarm}                         # GSAlarm.int     ; Gecko Reactor alarm
{1101}{}{Floor Plate}                   # WIPlTrp2.int    ; Plasma Floor Trap Level 2 of Seirra
{1102}{}{Floor Plate}                   # WIPlTrp3.int    ; Plasma Floor Trap Level 2 of Seirra
{1103}{}{Floor Plate}                   # WIPlTrp4.int    ; Plasma Floor Trap Level 2 of Seirra
{1104}{}{Floor Plate}                   # WIPlTrp5.int    ; Plasma Floor Trap Level 2 of Seirra
{1105}{}{Floor Plate}                   # WIPlTrp6.int    ; Plasma Floor Trap Level 2 of Seirra
{1106}{}{Floor Plate}                   # WIPlTrp7.int    ; Plasma Floor Trap Level 2 of Seirra
{1107}{}{Floor Plate}                   # WIPlTrp8.int    ; Plasma Floor Trap Level 2 of Seirra
{1108}{}{Floor Plate}                   # WIPlTrp9.int    ; Plasma Floor Trap Level 2 of Seirra
{1109}{}{Floor Plate}                   # WIPlTrpA.int    ; Plasma Floor Trap Level 2 of Seirra
{1110}{}{Floor Plate}                   # WIPlTrpB.int    ; Plasma Floor Trap Level 2 of Seirra
{1111}{}{Floor Plate}                   # WIPlTrpC.int    ; Plasma Floor Trap Level 2 of Seirra
{1112}{}{Floor Plate}                   # WIPlTrpD.int    ; Plasma Floor Trap Level 2 of Seirra
{1113}{}{Floor Plate}                   # WIPlTrpE.int    ; Plasma Floor Trap Level 2 of Seirra
{1114}{}{Floor Plate}                   # WIPlTrpF.int    ; Plasma Floor Trap Level 2 of Seirra
{1115}{}{Emitter}                       # WSEmit4a.int    ; Emitter, Level 4 in Sierra Base
{1116}{}{Emitter}                       # WSEmit4b.int    ; Emitter, Level 4 in Sierra Base
{1117}{}{Emitter}                       # WSEmit4c.int    ; Emitter, Level 4 in Sierra Base
{1118}{}{Force Field}                   # WSFeld4a.int    ; Force Field, Level 4 in Sierra Base
{1119}{}{Force Field}                   # WSFeld4b.int    ; Force Field, Level 4 in Sierra Base
{1120}{}{Force Field}                   # WSFeld4c.int    ; Force Field, Level 4 in Sierra Base
{1121}{}{un Hubologista}                # FCElrInd.int    ; Elron Indoctrinee
{1122}{}{Computer}                      # FStnkCmp.int    ; Posiden Tanker Computer
{1123}{}{Bunker Door}                   # WIBnkDor.int    ; Bunker Door for the Sierra Depot
{1124}{}{Gate}                          # miGate.int      ; Modoc Gate
{1125}{}{Box}                           # WITrpBx1.int    ; Sierra Base Trapped Box
{1126}{}{uno dei Fratelli Morton}       # RCMorBrs.int    ; Morton Brothers, Inc.
{1127}{}{Emitter}                       # FSEmt1.int      ; Force Field emitter 1 in San Fran
{1128}{}{Emitter}                       # FSEmt2.int      ; Force Field emitter 2 in San Fran
{1129}{}{Emitter}                       # FSEmt3.int      ; Force Field emitter 3 in San Fran
{1130}{}{Map Script}                    # Cave6.int       ; Fake Vault 13 Cave map
{1131}{}{Chet}                          # VCChet.int      ; Illicit Allocations Officer Chet
{1132}{}{Map Script}                    # NewRVB.int      ; New Reno Helicopter Script Map
{1133}{}{Vertibird}                     # nsVertib.int    ; New Reno Helicopter Script Vertibird
{1134}{}{una delle Guardie di Salvatore} # ncHSSal1.int    ; New Reno Helicopter Script Salvatore 1
{1135}{}{una delle Guardie di Salvatore} # ncHSSal2.int    ; New Reno Helicopter Script Salvatroe 2
{1136}{}{un Soldato}                      # ncHSPow1.int    ; New Reno Helicopter Script Power Armor 1
{1137}{}{un Soldato}                      # ncHSPow2.int    ; New Reno Helicopter Script Power Armor 2
{1138}{}{Crate}                         # niHSCrat.int    ; New Reno Helicopter Script Crate
{1139}{}{Mr. Handy}                     # ncHSHand.int    ; New Reno Helicopter Script Handy
{1140}{}{una delle Guardie di Salvatore} # ncHSGSal.int    ; New Reno Helicopter Script Salvatore Guard
{1141}{}{Spacial Script}                # ntHSGrd.int     ; New Reno Helicopter Script Guarding Spacial
{1142}{}{Door}                          # niEldDor.int    ; New Reno Elderidge Door
{1143}{}{Door}                          # niSalDor.int    ; New Reno Salvatore Door
{1144}{}{Door}                          # niMyrDor.int    ; New Reno Myron Door
{1145}{}{}                              # FcMonst.int     ; Monster in the PMS Tanker
{1146}{}{Map Script}                    # SFTanker.int    ; San Fran Tanker map
{1147}{}{uno Schiavo}                   # VCSlav2.int     ; Vault City Prisoner Slaves
{1148}{}{un Cittadino del Vault}        # VCBarCit.int    ; Vault City Bar Patron
{1149}{}{Door}                          # niBasDor.int    ; New Reno Locking Doors
{1150}{}{un Pugile}                     # ncFightr.int    ; New Reno Boxer Actually Fighting
{1151}{}{Vault Door}                    # RIVltDor.int    ; Locked Vault Door in Redding
{1152}{}{Xarn}                          # CcXarn.int      ; Xarn in Navarro
{1153}{}{Raul}                          # CcRaul.int      ; Raul in Navarro
{1154}{}{Quincy}                        # CcQuincy.int    ; Quincy in Navarro
{1155}{}{il Furiere}                # CcQmstr.int     ; Quartermaster in Navarro
{1156}{}{una Guardia}                   # CcMedGrd.int    ; Med Lab Guard in Navarro
{1157}{}{un Cane Cybernetico}           # CcK9.int        ; K9 in Navarro
{1158}{}{Doctor Schreber}               # CcDoctor.int    ; Dr Shreber in Navarro
{1159}{}{un Tecnico}                    # CcATech.int     ; Air Tech in Navarro
{1160}{}{un Tecnico}                    # CcACon.int      ; Air Control in Navarro
{1161}{}{una Guardia}                   # CcDrGrd.int     ; Door Guard in Navarro
{1162}{}{una Guardia}                   # Ccggbak.int     ; Gate Guard Backup in Navarro
{1163}{}{una Guardia}                   # CcGrdca.int     ; Guard (combat armor) in Navarro
{1164}{}{una Guardia}                   # CcGrdpa.int     ; Guard (power armor) in Navarro
{1165}{}{un Tecnico}                    # CcTech1.int     ; Com Tech1 in Navarro
{1166}{}{un Tecnico}                    # CcTech2.int     ; Com Tech2 in Navarro
{1167}{}{un Tecnico}                    # CcComp1.int     ; Computer Tech1 in Navarro
{1168}{}{un Tecnico}                    # CcComp2.int     ; Computer Tech2 in Navarro
{1169}{}{Cave In}                       # HICaveIn.int    ; Broken Hills Caved-In mine
{1170}{}{un Soldato di Pattuglia dell'Enclave}             # QCEPSqad.int    ; Enclave EP Squad (joins player in fighting
{1171}{}{Blast Door}                    # QIEndDor.int    ; Doors at the End Fight Area
{1172}{}{Map Script}                    # EncDet.int      ; Map Script for Enclave Detention Center
{1173}{}{Map Script}                    # EncDock.int     ; Map Script for Enclave Dock
{1174}{}{Map Script}                    # EncGd.int       ; Map Script for Enclave Guard Barracks
{1175}{}{Map Script}                    # EncPres.int     ; Map Script for Enclave Presidential Area
{1176}{}{Map Script}                    # EncRetr.int     ; Map Script for Enclave Reactor Area
{1177}{}{Map Script}                    # EncFite.int     ; Map Script for Enclave Fight Area
{1178}{}{un Robot della Sicurezza}      # QCSecBot.int    ; Enclave Security Robot
{1179}{}{Poor Box}                      # niTulBox.int    ; New Reno Poor Box
{1180}{}{Body}                          # hiDead.int      ; Dead body in Broken Hills Tunnels
{1181}{}{Box}                           # HiJacBox.int    ; Broken Hills Jacob inventory box
{1182}{}{Box}                           # HiDocBox.int    ; Broken Hills Doc Holliday Inventory box
{1183}{}{Box}                           # HiOutBox.int    ; Broken Hills Outfitter inventory box
{1184}{}{una Guardia della Carovana}    # RCCvnGrd.int    ; Generic Caravan Guard
{1185}{}{un Guidatore della Carovana}   # RCCvnDrv.int    ; Generic Caravan Driver
{1186}{}{l'Annunciatore}                # ncAnounc.int    ; New Reno Boxing Announcer
{1187}{}{la Ragazza del Ring}           # ncRngGrl.int    ; New Reno Ring Grrrl
{1188}{}{un Pugile}                     # ncPrzFtr.int    ; New Reno Prize Fighter
{1189}{}{Door}                          # VIVltDr2.int    ; Vault Doors in Vault 8
{1190}{}{l'Imbroglione}                 # ncCheat.int     ; New Reno Cheat Character
{1191}{}{Holodisk}                      # WIGNNDsk.int    ; Sierra Base GNN Transscript
{1192}{}{Holodisk}                      # WIMisDsk.int    ; Sierra Base Mission Statement Disk
{1193}{}{Holodisk}                      # FIElrDsk.int    ; Hubologist Holodisk
{1194}{}{Note}                          # HINote.int      ; Script for Francis/Zaius Note
{1195}{}{Dogmeat}                       # ECDogMet.int    ; Dog Meat from Special random encounter
{1196}{}{Cat's Paw Magazine #5}         # niCatPw5.int    ; New Reno Cat's Paw magazine 5
{1197}{}{Raiders Map}                   # niRaiMap.int    ; New Reno Raiders Map in Bishop's Safe
{1198}{}{un Cane Paria}                 # ECPariah.int    ; Pariah Dog in Low Luck encounter
{1199}{}{Klaxon}                        # QIKlaxon.int    ; Klaxon Lights for Enclave when under alert
{1200}{}{Mine}                          # IIMine.int      ; Mines in Raiders Cave
{1201}{}{Pit}                           # IIPit.int       ; Pits in the Raiders Cave
{1202}{}{Cal}		                # FCTnkGmr.int    ; Tanker Gun Merchant San Fran
{1203}{}{Slim}		                # FCTnkBar.int    ; Tanker Bar Tender
{1204}{}{Jenna}		                # FCTnkMer.int    ; Tanker Merchant
{1205}{}{}                              # FITGunTb.int    ; Tanker Gun Mer's table
{1206}{}{}                              # FITMerTb.int    ; Tanker Merchant's Table
{1207}{}{Emitter}                       # FSPemtr1.int    ; Palace Emitter 1
{1208}{}{Emitter}                       # FSPemtr2.int    ; Palace Emitter 2
{1209}{}{Emitter}                       # FSPemtr3.int    ; Palace Emitter 3
{1210}{}{Emitter}                       # FSEmpEmt.int    ; Emporor Computer's Force Field
{1211}{}{Fallout 2 Hintbook}            # niF2Hint.int    ; New Reno Fallout 2 Hintbook
{1212}{}{}                              # csTouch.int     ; Script to signal if dude touches container objects (in Navarro)
{1213}{}{}                              # csArea.int      ; Script to signal if dude enters an area (in Navarro)
{1214}{}{una Guardia}                   # RCAscGrd.int    ; Generic Guard for Ascorti's Bar
{1215}{}{un Cercatore}                  # ECLdPros.int    ; Random Encounter Lead Prospector
{1216}{}{un Contrabbandiere}               # ECLdBoot.int    ; Random Encounter Lead Bootlegger
{1217}{}{}                              # csOpen.int      ; Script to signal if dude uses door w/o permission (in Navarro)
{1218}{}{Dan}                           # hcDan.int       ; Dan, Spouse of murdered conspirator.
{1219}{}{un Comico da Strapazzo}        # ncComedi.int    ; New Reno Comedian
{1220}{}{un Cantante di Strada}  # ncBand.int      ; New Reno Trashcan Band
{1221}{}{Map Script}                    # ARDead.int      ; Destroyed Arroyo Bridge map script
{1222}{}{}                              # csGate.int      ; Script to signal if dude uses gate w/o permision (in Navarro)
{1223}{}{Grave}                         # niWilGrv.int    ; New Reno Coffin Willie's Grave
{1224}{}{"Becchino" Willie}             # ncWillie.int    ; New Reno Coffin Willie
{1225}{}{Keyless entry computer}        # FSFobTer.int    ; Fob Terminal
{1226}{}{Keyless entry Door}            # FSFobDor.int    ; Fob Door
{1227}{}{Computer}                      # ccNComp.int     ; Navarro Computer
{1228}{}{Kohl}                          # vcKohl.int      ; Vault City Info Officer Kohl
{1229}{}{un Bambino}                    # ECChild.int     ; Random Encounter Children
{1230}{}{Cookie}                        # ccCook.int      ; Navarro Cook
{1231}{}{una Torretta}                  # ccTurret.int    ; Navarro Turret
{1232}{}{Brian}                         # hcBrian.int     ; Brian, the Power Technician
{1233}{}{Generator}                     # hiPower.int     ; Power Generator for Broken Hills
{1234}{}{Console}                       # hiConsole.int   ; Power Station Console in Broken Hills
{1235}{}{una Formica Gigante}           # hcAnt1.int      ; Standard Broken Hills Ant
{1236}{}{una Formica Gigante}           # hcAnt2.int      ; Broken Hills Ant - Missing Person Quest
{1237}{}{Door}                          # csXDoor.int     ; Another lousy door script -signals xarn to leave
{1238}{}{}                              # htSecret.int    ; Spatial for secret area of Broken Hills Mine
{1239}{}{Box}                           # niEthBox.int    ; New Reno Ethyl Wright Shop Box
{1240}{}{Eric}                          # hcEric.int      ; Eric the Smelly Boy, Broken Hills
{1241}{}{}                              # htFlies.int     ; Spatial Flies script for Broken Hills
{1242}{}{Box}                           # viRanBox.int    ; Randal's Stock Box in Vault City
{1243}{}{uno Scorpione Gigante}         # iiScorp.int     ; Raiders Scorpions 2X poison
{1244}{}{Jane}                          # RCJane.int      ; Redding Jackpot Jane
{1245}{}{}                              # VTAloMrk.int    ; Spatial Script for Allocation Computer VCity
{1246}{}{Map Script}                    # Cave7.int       ; Fake Vault 13 map
{1247}{}{Dermal Pip Boy}                # niDermal.int    ; New Reno Dermal Pip Boy
{1248}{}{un Cuccioletto}                # ncEldDog.int    ; New Reno Eldridge Dogs
{1249}{}{Rattray}                       # RCRatray.int    ; Rattray, Doc Johnson's assistant
{1250}{}{un Consorte}                   # HCHusWif.int    ; Mutant Husband/Wife Broken Hills
{1251}{}{una Guardia di Lo Pan}         # FCLoGrd.int     ; LoPan Guard in San Fran
{1252}{}{Map Script}                    # Navarro.int     ; Map script for Navarro
{1253}{}{Door}                          # VIVltDr3.int    ; Vault Door in Vault 8 - Martin
{1254}{}{un Cane Cybernetico}           # CcFak9.int      ; Fake K-9 Scenery obj
{1255}{}{Luke}                          # FCNLuke.int     ; Luke in NCR
{1256}{}{Joshua}                        # FCDJosh.int     ; Joshua BOS in the Den
{1257}{}{Gate}                          # iiLockDr.int    ; Gates in Raiders area
{1258}{}{Matt}                          # FCFmatt.int     ; Matt in San Fran BOS
{1259}{}{Door}                          # FSBroDor.int    ; Brotherhood Door
{1260}{}{una Guardia}                   # hcGrd2.int      ; Bank Guard 2 in Broken Hills
{1261}{}{Door}                          # QIGeckDr.int    ; Door Requiring the player to use the geck
{1262}{}{Computer}                      # FSFace.int      ; Ace Computer system in San Fran
{1263}{}{Terminal}                      # QITurTrm.int    ; Generic Enclave Turret Terminal
{1264}{}{Torretta}                      # QCTurret.int    ; Enclave Turrets
{1265}{}{Chuck Stodgers}                # hcChuck.int     ; Chuck Stodgers, Broken Hills
{1266}{}{}                              # htChuck.int     ; Spatial Script for waking up Chuck
{1267}{}{Terminal}                      # viTerm.int      ; Vault City Vault Terminal
{1268}{}{un Criminale}                  # RCMotGng.int    ; Frog Morton's gang
{1269}{}{un Imbroglione}                # ccCheat.int     ; Cheat character in Navarro
{1270}{}{}                              # FSTnkrdr.int    ; Tanker Doors in San Fran
{1271}{}{un Contadino}                  # OCPeaon.int     ; NCR peaons
{1272}{}{Il Fiore di Lavanda}           # diRebBok.int    ; Den Becky's Book
{1273}{}{un Radscorpione}               # hcScorp.int     ; Broken Hills Scorpion
{1274}{}{il Professore}                 # hcProf.int      ; Broken Hills Professor
{1275}{}{Box}                           # hiPrfBx1.int    ; Professor's Box in Broken Hills
{1276}{}{Box}                           # hiPrfBx2.int    ; Professor's Box in Broken Hills
{1277}{}{Seymour}                       # hcSeymore.int   ; Seymour the talking Plant/Broken Hills
{1278}{}{John Sullivan}                 # hcSulvan.int    ; John Sullivan - Broken Hills
{1279}{}{Lumpy}                         # hcLumpy.int     ; Lumpy the car accident victim - Broken Hills
{1280}{}{}                              # BISpyHol.int    ; Spy Holodisk for NCR
{1281}{}{}                              # SIHisHol.int    ; NCR History Holodisk
{1282}{}{}                              # SIWesHol.int    ; Westin Holodisk
{1283}{}{una Guardia}                   # SCBGrd.int      ; Buster's Guard
{1284}{}{}                              # SIElnObj.int    ; Elise Notify Object
{1285}{}{}                              # SIGcaObj.int    ; NCR Guard Captain notify obj
{1286}{}{Typhon}                        # hcTyphon.int    ; Typhon, Son of Set - Broken Hills
{1287}{}{una Guardia del Corpo}         # ECBdyGrd.int    ; BodyGuard in Vignette
{1288}{}{Map Script}                    # GamMovie.int    ; Game Movie map
{1289}{}{Armadietto}                        # ziLocker.int    ; Generic Locker Script
{1290}{}{Pozzo}                          # hiWell.int      ; Broken Hills Well
{1291}{}{Micky}                         # hcMicky.int     ; Mickey the Dwarf - Broken Hills
{1292}{}{Torretta}                        # WCTurret.int    ; Turret for Sierra Depot
{1293}{}{un Vecchio Ghoul}              # hcOldGhl.int    ; Ghouls in Old-Folks Home - Broken Hills
{1294}{}{un Seguace}                    # hcHench.int     ; Broken Hills Outfitter Henchmen
{1295}{}{Elmo}                          # hcElmo.int      ; Elmo - Broken Hills
{1296}{}{Toilet}                        # niToilet.int    ; Toilet - Contains Grenades - New Reno
{1297}{}{Croce}                         # niCross.int     ; Cross - Golgotha - Buried Cash
{1298}{}{Aratro}                          # viPlow1.int     ; Plow - Vault City
{1299}{}{Aratro}                          # viPlow2.int     ; Plow - Vault City
{1300}{}{uno Scorpione}                 # kcScorpa.int    ; Attacking scorpion in klamath
{1301}{}{Generatore}                     # kcGnratr.int    ; Generator player repairs in toxic caves
{1302}{}{Porta}                          # kcLvatr.int     ; Elevator door in toxic caves
{1303}{}{Porta}                          # SIVDor.int      ; Vortis Slave Door
{1304}{}{Medical Pip Boy}               # niMedica.int    ; New Reno "Doctor Skill" Upgrade
{1305}{}{Locker}                        # niPrstLk.int    ; New Reno Prostitute"Locker"
{1306}{}{Locker}                        # niBigJLk.int    ; New Reno Big Jesus "Locker"
{1307}{}{Locker}                        # niMor1Lk.int    ; New Reno Mordino No Lock/No Ignore "Locker"
{1308}{}{Locker}                        # niBoxrLk.int    ; New Reno Boxer "Locker"
{1309}{}{Locker}                        # niBis1Lk.int    ; New Reno Bishop Family OK "Locker"
{1310}{}{Locker}                        # niPornLk.int    ; New Reno Porn Actress "Locker"
{1311}{}{Locker}                        # niBtchLk.int    ; New Reno Bitch "Locker"
{1312}{}{Locker}                        # niBis2Lk.int    ; New Reno Bishop Family NO IGNORE "Locker"
{1313}{}{Locker}                        # niEldrLk.int    ; New Reno Eldridge "Locker"
{1314}{}{Locker}                        # niWrT1Lk.int    ; New Reno Wright Teen NO IGNORE "Locker"
{1315}{}{Locker}                        # niOWriLk.int    ; New Reno Orville Wright "Locker"
{1316}{}{Locker}                        # niWrT2Lk.int    ; New Reno Wright Teen FAMILY IGNORE "Locker"
{1317}{}{Locker}                        # niMor1Lk.int    ; New Reno Mordino FAMILY IGNORE "Locker"
{1318}{}{Locker}                        # niMyGdLk.int    ; New Reno Myron Guard "Locker"
{1319}{}{Locker}                        # niMor2Lk.int    ; New Reno Mordino NO IGNORE "Locker"
{1320}{}{Locker}                        # niMyrnLk.int    ; New Reno Myron "Locker"
{1321}{}{Locker}                        # niChp1Lk.int    ; New Reno Chop Shop Boy LOCKED "Locker"
{1322}{}{Locker}                        # niChp2Lk.int    ; New Reno Chop Shop Boy NO-LOCK "Locker"
{1323}{}{Locker}                        # niTryLk.int     ; New Reno Tray "Locker"
{1324}{}{Locker}                        # niMor3Lk.int    ; New Reno Mordino locker, no warning
{1325}{}{Map Script}                    # rndtoxic.int    ; Random Toxic Map
{1326}{}{Non puoi vedermi}              # ecirrad.int     ; critter that irradates
{1327}{}{il Boscaiolo di Latta}         # ecTinWod.int    ; Tin Woodsman
{1328}{}{Map Script}                    # rndTinWd.int    ; Tin Woodsman Map Script
{1329}{}{una Formazione Rocciosa}       # ecGrdFrv.int    ; Guardian of Forever
{1330}{}{}                              # rndForvr.int    ; Guardian of Forever Rnd Enct Map Script
{1331}{}{Terminal}                      # ecGrdTrm.int    ; Guardian of Forever Water Chip Terminal
{1332}{}{Locker}                        # niEld2Lk.int    ; New Reno Eldridge "Locker" HARD LOCK
{1333}{}{}                              # SiRagobj.int    ; Uhh box that Rondo cares
{1334}{}{Map Script}                    # SFCHINA2.int    ; China 2 map
{1335}{}{un Robot della Sicurezza}      # WCDedBot.int    ; Fighting Bot that does nothing
{1336}{}{un Robot della Sicurezza}      # KCWupass.int    ; Klamath Guard Robot under Toxic Caves
{1337}{}{Locker}                        # viHarWch.int    ; VCty - Harry Watch Script
{1338}{}{Locker}                        # viEdWch.int     ; VCty - Ed Watch Script
{1339}{}{Locker}                        # viAndWch.int    ; VCty - Doc Andrew Watch Script
{1340}{}{Locker}                        # viLynWch.int    ; VCty - Lynette Watch Script
{1341}{}{Locker}                        # viGrgWch.int    ; VCty - Gregory Watch Script
{1342}{}{Locker}                        # viCGWch1.int    ; VCty - Prison Door Watch Script
{1343}{}{Locker}                        # viCGWch2.int    ; VCty - Greeting Watch Script
{1344}{}{Locker}                        # viRNWch1.int    ; VCty - Randal1 Watch Script
{1345}{}{Locker}                        # viRNWch2.int    ; VCty - Randal2 Watch Script
{1346}{}{Locker}                        # viStkWch.int    ; VCty - Stark Watch Script
{1347}{}{Locker}                        # viBarWch.int    ; VCty - Barkus Watch Script
{1348}{}{Locker}                        # viVLWch1.int    ; VCty - Valerie1 Watch Script
{1349}{}{Locker}                        # viVLWch2.int    ; VCty - Valerie2 Watch Script
{1350}{}{Locker}                        # viWalWch.int    ; VCty - Wallace Watch Script
{1351}{}{Locker}                        # viSkvWch.int    ; VCty - Greeting Watch Script
{1352}{}{Locker}                        # viInWch1.int    ; VCty - InGrd Watch Script
{1353}{}{Locker}                        # viInWch2.int    ; VCty - InGrd Watch Script
{1354}{}{Locker}                        # viInWch3.int    ; VCty - InGrd Watch Script
{1355}{}{Locker}                        # viFamWch.int    ; VCty - GenFam Watch Script
{1356}{}{Locker}                        # viCsWch1.int    ; VCty - Cassidy Watch Script
{1357}{}{un Abusivo del Porto}          # FCDocSqa.int    ; San Fran - Doc Squatter
{1358}{}{un Ragazzo del Porto}          # FCDocKid.int    ; San Fran - Doc Kids
{1359}{}{Map Script}                    # RndWhale.int    ; Random Whale Script
{1360}{}{Percy Crump}                   # gcPercy.int     ; Percy Crump, Gecko Merchant
{1361}{}{Box}                           # giPerBox.int    ; Percy's Stock Box
{1362}{}{Box}                           # giJnkBox.int    ; Gecko Junkyard Temp Inventory Box
{1363}{}{Door}                          # niWriDor.int    ; New Reno Wright Room Door
{1364}{}{il Grande Ananias}             # dcAnan.int      ; The Great Ananias, Mummy Master
{1365}{}{Map Script}                    # RndUVilg.int    ; Unwashed Villager map
{1366}{}{un "Unwashed Villager"}        # ECWash.int      ; Unwashed Villagers... Ug You figure out where they go.
{1367}{}{uno Spammer}                   # ECSpammr.int    ; Spammer in Unwashed Encounter
{1368}{}{Map}                           # eiSanMap.int    ; Military Base San Francisco Map
{1369}{}{Map Script}                    # RndShutl.int    ; Random Shuttle Map
{1370}{}{Map Script}                    # rndParih.int    ; Random Pariah Map Script
{1371}{}{Map Script}                    # rndBHead.int    ; Random Big Head map
{1372}{}{Map Script}                    # rndcafe.int     ; Random Cafe Map
{1373}{}{Nuka-Cola Machine}             # ZINuke.int      ; Nuka-Cola Machine
{1374}{}{Dock}                          # sfdock.int      ; map script for San Fran Dock
{1375}{}{Door}                          # ciCrisDr.int    ; Chris's Door
{1376}{}{Land Mine}                     # rtlndmin.int    ; Redding Land Mines
{1377}{}{Land Mine}                     # wtlndmin.int    ; Sierra Depot Land Mines
{1378}{}{l'ex}                     # ncExSpou.int    ; New Reno Ex-Spouse script
{1379}{}{Mel}                           # ECMel.int       ; Mel that Dogmeat Creates.
{1380}{}{Vent}                          # ciVent.int      ; Vent into Navarro
{1381}{}{Kevin}                         # ccKevin.int     ; Kevin in Navarro
{1382}{}{Alarm}                         # csAlarm.int     ; Navarro base on alert lights
{1383}{}{Locker}                        # ciQunWch.int    ; Quincy Locker watch script
{1384}{}{Locker}                        # ciRulWch.int    ; Raul Locker Watch Script
{1385}{}{Locker}                        # ciCmdWch.int    ; Commanded Locker Watch Script
{1386}{}{}                              # SSSign.int      ; NCR Statue
{1387}{}{}                              # ctFob.int       ; Fob EXP Spatial Script
{1388}{}{}                              # ctPlans.int     ; Vertibird EXP Spatial Script
{1389}{}{}                              # ctK9Part.int    ; K9 Part EXP Spatial Script
{1390}{}{}                              # csArea2.int     ; Script to signal if dude enters an area
{1391}{}{}                              # csOpen2.int     ; Script to signal if dude uses door w/o permision (in Navarro)
{1392}{}{}                              # ctSound.int     ; Soundproof Room Spatial Script
{1393}{}{}                              # csOpen3.int     ; Script to signal if dude uses door w/o permis
{1394}{}{un Contrabbandiere}            # ECTlkMon.int    ; Talking Moonshiners
{1395}{}{}                              # ziWeakLk.int    ; Generic Weak Lock Watch Script
{1396}{}{}                              # ziMedmLk.int    ; Generic Medium Lock Watch Script
{1397}{}{un ragazzetto}                     # dcCarnKd.int    ; Carny Kid - The Den
{1398}{}{}                              # ciDocWch.int    ; Raul Locker Watch Script
{1399}{}{}                              # ziHardLk.int    ; Generic Hard Lock Watch Script
{1400}{}{Mine}                          # CIMine.int      ; Mines in Raiders Cave
{1401}{}{Locker}                        # niBisHLk.int    ; New Reno Bishop Hard Locker
{1402}{}{Door}                          # niBisHDr.int    ; New Reno Bishop Hard Locked Door
{1403}{}{}                              # ntRicRom.int    ; New Reno Richard Wright Room Spacial
{1404}{}{}                          # MIMirDor.int    ; Miria's Bedroom Door
{1405}{}{}                          # MIDavDor.int    ; Davin's Bedroom Door
{1406}{}{}                          # SIPtbox2.int    ; box where Merk hides your car trunk stuff
{1407}{}{}                          # sfshutl1.int    ; map script to Hubologist entrance (shuttle)
{1408}{}{}                          # patchinf.int    ; patchinf
{1409}{}{}                          # nijjbox.int     ; Jagged Jimmy J Inventory Box
