#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used by town and world map
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#

#
# Town map selection names
#
# Format:
#	city type.
#	Up to 10 selection names
#
# Vault 13
{200}{}{Entrata della Caverna}
{201}{}{Entranta}
{202}{}{Alloggi}
{203}{}{Centro di Comando}
#
# Vault 15
{210}{}{Entrata dal Deserto}
{211}{}{Caverne/Entrata}
{212}{}{Alloggi}
{213}{}{Centro di Comando}
#
# Shady Sands
{220}{}{Entrance}
{221}{}{Garden}
{222}{}{Brahmin Pen}
#
# Junktown
{230}{}{Entrance}
{231}{}{Crash House}
{232}{}{Casino}
#
# Raiders
{240}{}{Base}
#
# Necropolis
{250}{}{Hotel}
{251}{}{Hall}
{252}{}{Watershed}
#
# Hub
{260}{}{Entrance}
{261}{}{Downtown}
{262}{}{Heights}
{263}{}{Old Town}
{264}{}{Merchants}
{265}{}{Cave}
#
# Brotherhood
{270}{}{Entrance}
{271}{}{Level 1}
{272}{}{Level 2}
{273}{}{Level 3}
{274}{}{Level 4}
#
# Military Base
{280}{}{Entrance}
{281}{}{Stronghold Level 1}
{282}{}{Stronghold Level 2}
{283}{}{Vats Level 1}
{284}{}{Vats Level 2}
#
# Glow
{290}{}{Crater}
{291}{}{Level 1}
#
# Boneyard
{300}{}{Adytum}
{301}{}{Downtown}
{302}{}{Library}
{303}{}{Fortress}
{304}{}{Warehouse}
#
# Cathedral
{310}{}{Entrance}
{311}{}{Interior}

# Misc messages
{500}{}{Hai guadagnato 10,000 punti esperienza!}
{501}{}{Rovine}

#
# Terrain type names for world map hover button
#
{1000}{}{Deserto}
{1001}{}{Montagne}
{1002}{}{Citta'}
{1003}{}{Costa}
{1004}{}{Ignoto}  # Unknown/visited city

