{100}{}{You see a short, jovial man.}
{101}{}{You see Happy Harry, the store owner.}
{102}{}{Well, hello there... what can I do for you?}
{103}{}{I'm looking to trade. Can I see what you have in stock?}
{104}{}{You still selling that plow out there?}
{105}{}{Me Buy}
{106}{}{Nothing today, thanks.}
{107}{}{Sorry. Can't help you, neighbor.}
{108}{}{Why, yes I am. I'll let it go for... say, eight hundred.}
{109}{}{I'll give you six hundred for it.}
{110}{}{It's a deal. I'll take it.}
{111}{}{Eh, eight hundred? I'll be back... with the money.}
{112}{}{Forget it. The Smiths can starve.}
{113}{}{It's yours. [Pockets the money.] You just going to take it, or do you need it
 delivered somewhere?}
{114}{}{Drop it off with the Smiths.}
{115}{}{Sorry, friend. It's going to cost you eight hundred.}
{119}{}{You need the money to pay me, friend.}
{120}{}{I'll be back with the money.}
{121}{}{Not a problem. I'll have it dropped off right now.}
{122}{}{Thought you'd just help yourself, huh? Damn thief... guards! Guards!}