#############################################################
#  Message File: ACBrahmn.msg                               #
#                                                           #
#       Body Type:  Brahmin                                 #
#       Combat AI: None                                     #
#       Weapons: None                                       #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log: kinpa                                               #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated&Translated: Ragfox 2002                          #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Vedi un normale brahmin addomesticato.}
{101}{}{La testa aggiuntiva del brahmin e' probabilmente il risultato di una mucca normale esposta troppo presto alle radiazioni.}
{102}{}{Non noti nulla di strano in questo brahmin.}
{103}{}{I brahmin non sono il massimo per fare due chiacchiere.}
{104}{}{Non hai niente di meglio da fare che rimanertene qui a parlare con una mucca bicipite?}
{105}{}{I brahmin sono una razza mutante di mucca.}