{100}{}{Vedi la guardia del ponte.}
{101}{}{Vedi Mynoc, la guardia del ponte.}
{150}{}{Davanti a te c'e' un possente guerriero del tuo villaggio che impugna una lancia.}
{151}{}{[PARLA]}
{152}{}{Salve, Prescelto. Stai partendo alla ricerca del GECK?}
{153}{}{Si'.}
{154}{}{Si'. Ma prima che io vada, vorrei farti qualche domanda.}
{155}{}{Adesso no. Voglio guardarmi in giro ancora un po'.}
{156}{}{Bene, che gli dei veglino su di te.}
{157}{}{Grazie, arrivederci.}
{158}{}{Cosa vuoi sapere?}
{159}{}{Cosa puoi dirmi degli uomini che commerciano col nostro villaggio?}
{160}{}{Cosa puoi dirmi di questo oggetto che e' stato preso da un Vault?}
{161}{}{Niente, non importa.}
{162}{}{Molto bene, ma non perdere troppo tempo. Senza il GECK, siamo spacciati.}
{163}{}{Lo so, non temere -- Ho tutto sotto controllo.}
{164}{}{Perche'?}
{165}{}{Devo andare. Arrivederci.}
{166}{}{I commercianti? Arrivano da Klamath ogni due mesi circa. Non ne arrivera' un altro per un mese o piu', ma Klamath e' solo pochi giorni a est di qui.}
{167}{}{Grazie. Arrivederci.}
{168}{}{Cosa puoi dirmi di questo oggetto che e' stato preso dal sacro Vault?}
{169}{}{Sembra una fiaschetta di metallo. Forse il Vault ce l'ha spedito come augurio.}
{170}{}{Puoi dirmi chi ha portato questo oggetto al nostro villaggio?}
{171}{}{Grazie. Devo andare. Arrivederci.}
{172}{}{Lo spero.}
{173}{}{La tua eccessiva sicurezza ci fa soffrire tutti! Addio!}
{174}{}{Arrivederci.}
{175}{}{Perche'? Guardati intorno -- il nostro villaggio muore. I campi avvizziscono e ogni giorno ci sono dei bambini e dei vecchi che muoiono. Devi portarci l'Eden prima che sia troppo tardi!}
{176}{}{Ci pensero' io. Arrivederci.}
{177}{}{Io sono il Prescelto -- Io "devo" fare solo cio' che voglio. Addio.}
{178}{}{Non ricordo il suo nome, so solo che era vecchio e rozzo -- troppo rozzo per avere delle buone maniere -- ma sapeva molte cose. Veniva da Klamath. Da est, come ho gia' detto.}
{179}{}{Grazie, arrivederci.}
{180}{}{Sei ancora qui? Devi trovare il GECK. Restando qui non ci aiuti di certo.}
{181}{}{Questo ponte e' l'unica cosa di cui ti devi preoccupare, amico. So badare benissimo a me stesso.}
{182}{}{Stavo appunto per andare. Arrivederci, amico.}
{183}{}{Non parlero' un attimo di piu' con te, porco insubordinato!}
{184}{}{Vorrei farti un'altra domanda.}
{185}{}{Che velocita'! Hai trovato il sacro Vault 13?}
{186}{}{Si'.}
{187}{}{No, non ancora.}
{188}{}{Davvero? Meraviglioso! Hai portato il GECK?}
{189}{}{No.}
{190}{}{No. Non ho ancora parlato con gli abitanti del Vault.}
{191}{}{Non credo che questi siano affari tuoi, amico mio.}
{192}{}{No? Prescelto, tre anziani sono morti da quando sei partito. Non devi sprecare altro tempo.}
{193}{}{Lo trovero', non preoccuparti.}
{194}{}{Mi sto stufando del tuo continuo brontolare.}
{195}{}{Beh, perche' stai parlando con me? Parla con loro, e recupera il GECK.}
{196}{}{Lo faro' -- a tempo debito, amico mio.}
{197}{}{Mi sto stufando del tuo continuo brontolare.}
{198}{}{Che notizie sul GECK, Prescelto?}
{199}{}{Ho trovato il Vault!}
{200}{}{Non sono stato in grado di trovare il Vault 13.}
{201}{}{Ma che sorpresa: il Prescelto.}
{202}{}{Salve.}
{203}{}{Taci.}
{204}{}{Posso farti una domanda?}
{205}{}{No, non ho tempo.}
{206}{}{Vabbe'. Arrivederci.}
{207}{}{Oh bene. Ci si vede.}
{208}{}{Muori.}
{209}{}{Salute, stupidone! Vedere ponte? Tu attraversare, tu stare attento. Ponte pericoloso. Tu non volere cadere. Okay?}
{210}{}{Umm... Hunh?}
{211}{}{Disgraziato! Hai deluso tutto il villaggio!}
{212}{}{Hai tradito la nostra fiducia. Per questo morirai!}
{213}{}{Sei un traditore della tua stessa gente.}
{214}{}{Perche' fai questo?}
{215}{}{L'Anziana si sbagliava. Sei malvagio.}
{300}{}{Mio padre mi ha insegnato come affilare le lance. Portami una selce e affilero' anche la tua. Ti servira', nel deserto.}
{301}{}{Dove posso trovare un po' di questa selce?}
{302}{}{Si dice che tua Zia Morlis ne abbia una provvista. E' cosi' permalosa che non penso che qualcuno gliel'abbia mai chiesta. Di sicuro quella strega vorra' qualcosa in cambio.}
{303}{}{Grazie. Arrivederci.}
{304}{}{Sei riuscito ad ottenere la selce da tua zia?}
{305}{}{Si', ne ho un pezzo proprio qui.}
{306}{}{Non ancora.}
{307}{}{E' un bel pezzo. Dammi la tua lancia.}
{308}{}{Ecco qua.}
{309}{}{Non credo di averne una.}
{310}{}{Ora, metti i pezzi in questo modo...}
{311}{}{Il Prescelto senza una lancia? Beh, dovrai prendere una delle mie. Mettiamoci al lavoro, adesso...}
{312}{}{Ecco la tua nuova lancia.}
{313}{}{Grazie, amico mio -- Questa mi sara' di grande aiuto.}
{314}{}{Si', ma la tua lancia mi incuriosisce. Sembra diversa dalle altre.}
{400}{}{Bentornato a casa, Prescelto! Hai trovato il Vault? Sei tornato con il GECK?}
{401}{}{Me no trovato ancora.}
{402}{}{No, non l'ho ancora trovato.}
{403}{}{Non sono in vena di rispondere alle tue domande. Addio.}
{404}{}{Le cose non vanno bene, Prescelto. La siccita' non ci da' tregua e i raccolti verranno sicuramente distrutti. Stiamo raccogliendo il possibile per creare delle scorte alimentari.}
{405}{}{Perche' non commerciare con altri villaggi?}
{406}{}{Io fa mio meglio. Me trova GECK. Me ritorna.}
{407}{}{Perche' non commerciare con altri villaggi per il cibo che ci serve? }
{408}{}{Faccio del mio meglio. Quando avro' trovato il GECK, tornero'.}
{409}{}{Siamo gente semplice e abbiamo poco da offrire in uno scambio commerciale. I pochi paesi che abbiamo contattato mentre eri via non hanno mostrato alcun interesse ad aiutarci.}
{410}{}{Me capisce.}
{411}{}{Capisco.}
{412}{}{Sei la nostra unica speranza, Prescelto. Per favore, non deluderci!}
{413}{}{E' bello vederti, Prescelto. Come va la tua missione?}
{414}{}{Me ancora cerca.}
{415}{}{La sto ancora cercando.}
{416}{}{Non ho voglia di parlarne.}
{417}{}{Devi sbrigarti. Qui le cose vanno sempre peggio. Presto ci sara' poco cibo e l'Anziana sta pensando di razionare quello che abbiamo. Temo per il futuro di Arroyo.}
{418}{}{Prescelto! Per favore, dimmi che hai portato a termine la tua missione. Il nostro villaggio sta morendo, cosi' come la nostra gente.}
{419}{}{No, me ancora cercare.}
{420}{}{No, sto ancora cercando.}
{421}{}{Come vanno le cose?}
{422}{}{Mi spiace, Prescelto, ma inizio a dubitare della mia fede in te. Le vite della nostra gente sono nelle tue mani. Per favore: trova il sacro Tredici e torna da noi con il GECK!}
{423}{}{I raccolti sono distrutti, i brahmin muoiono, tutti sono affamati. I pianti dei bambini, di notte, non consentono a nessuno di dormire. Siamo disperati.}
{424}{}{Me continua a cercare.}
{425}{}{Faro' quel che posso.}
{426}{}{Ancora una volta torni da noi, Prescelto. Non a mani vuote, voglio sperare!}
{427}{}{Me spiacente, no trovato GECK ancora.}
{428}{}{Mi dispiace, non ho ancora trovato il GECK.}
{429}{}{Ne ho abbastanza.}
{430}{}{Mentre tu passeggi per le lande, qui la nostra gente muore. Forse dovresti cercare da qualche altra parte invece che tornare qui.}
{500}{}{Hai gia' parlato con l'Anziana?}
{1000}{}{Elder}
{1001}{}{Founder}
{1002}{}{Vault Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Chosen One}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Healing Powder}
{1010}{}{Bridge}
{1011}{}{Mynoc}
{1100}{}{The Elder is your mother and our leader.}
{1101}{}{Our great ancestor who gave us knowledge.}
{1102}{}{The first to fight and win over chaos.}
{1103}{}{That would be our beautiful village.}
{1104}{}{E' un avamposto commerciale a pochi giorni a est di qui.}
{1105}{}{The Vault is heaven.}
{1106}{}{You are the Chosen One.}
{1107}{}{Egli ci cura con le sue erbe e con la magia. Si trova nella zona nord del villaggio.}
{1108}{}{Egli ci cura con le sue erbe e con la magia. Si trova nella zona nord del villaggio.}
{1109}{}{E' una polvere magica che ti guarisce, ma che ti intorpidisce.}
{1110}{}{The Great Bridge exits our village in the south.}
{1111}{}{Si tratta di me.}
