#############################################################
#  Message File: ACSporPL.msg                               #
#                                                           #
#       Body Type:  Spore Plant(Plant with Dark Soul)       #
#       Combat AI: ?                                        #
#       Weapons: ?                                          #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log: Ragfox                                              #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Vedi una Pianta dall'Essenza Oscura.}
{101}{}{Queste piante non sono pericolose solo per il giardino.  Hanno la capacita' di attaccare persino gli uomini e altre creature.}
{102}{}{Queste Piante dall'Essenza Oscura rappresentano uno strano esempio di mutazione. Non e' sicuro che siano mutate in questo modo per cause naturali.}
{103}{}{Non noti niente di particolare in queste piante - a parte il fatto che sono in grado di attaccare gli umani.}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################
{150}{}{Hai liberato il giardino da tutte le Piante dall'Essenza Oscura.} 