#############################################################
#  Message File: ACWarior.msg                               #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Vedi un membro della tribu'.}
{101}{}{Vedi un membro della tribu'.}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################

{150}{}{Davanti a te c'e' un robusto guerriero del tuo villaggio, che indossa pantaloni ottenuti da pelli di animali.}
{151}{}{[PARLA]}
{152}{}{Salve, Prescelto, posso aiutarti nella tua missione?}
{153}{}{Sto solo dando un'ultima occhiata al villaggio prima di partire.}
{154}{}{Cosa puoi dirmi dei mercanti che commerciano con noi?}
{155}{}{Puoi dirmi dove posso trovare dell'altra polvere curativa?}
{156}{}{Che gli dei ti diano la rapidita' per portarci l'Eden prima che sia troppo tardi.}
{157}{}{Ho una domanda da farti.}
{158}{}{Arrivederci, amico mio.}
{159}{}{Oh, vuoi mettermi alla prova. Va' a trovare Hakunin nell'angolo nord del villaggio. E' lui che prepara le nostre medicine.}
{160}{}{Grazie. Arrivederci.}
{161}{}{Beh, li vedo talvolta quando Mynoc ci mette a guardia del ponte, ma e' lui che si occupa di tutte le trattative. Parla con lui al Grande Ponte.}
{162}{}{Grazie. Arrivederci.}
{163}{}{Puoi dirmi dove si trova il Grande Ponte?}
{164}{}{Un'altra domanda, se posso.}
{165}{}{Prescelto? Il Grande Ponte si trova sul confine sud del villaggio. Lo sai anche tu, ci sei stato tante volte.}
{166}{}{Grazie. Arrivederci.}
{167}{}{Un'altra domanda, se posso.}
{168}{}{Certo, cosa c'e'?}
{169}{}{Puoi dirmi dove posso trovare delle erbe curative?}
{170}{}{Cosa puoi dirmi dei mercanti che commerciano con noi?}
{171}{}{Come non detto.}
{172}{}{Ehi, ritardato. Si dice che tu sia il Prescelto. Devo ammettere che lo spirito del Fondatore agisce in modo strano.}
{173}{}{Oon Ga.}
{174}{}{Fa' buon viaggio, ritardato -- per amor nostro.}
{175}{}{????}
{176}{}{Ci hai tradito.  Devi morire.}
{177}{}{Un traditore della tua stessa gente!}
{178}{}{Perche' fai questo?}
{179}{}{Morte al malvagio!}
{180}{}{Non valgono niente per noi! Per vivere razziano i corpi morenti nel deserto.}
{181}{}{Puoi dirmi dove posso trovare delle erbe curative?}
{182}{}{Grazie. Arrivederci.}
{183}{}{Un'altra domanda, se posso.}

# Starting Dialog after 1st Hakunin Movie
{300}{}{Salve di nuovo, Prescelto. Possano gli spiriti guerrieri proteggerti e guidarti.}

# Starting Dialog after 2nd Hakunin Movie
{301}{}{Stai incontrando delle difficolta', Prescelto? Non devi deluderci - per favore, sbrigati.}

# Starting Dialog after 3rd Hakunin Movie
{302}{}{Perche' aspetti cosi' a lungo? Dobbiamo avere il GECK in fretta. Prescelto, il nostro villaggio sta morendo.}

# Starting Dialog after 4th Hakunin Movie
{303}{}{Prescelto, il nostro villaggio e' quasi morto. Perche' non ci hai ancora portato il sacro GECK?}



#############################################################
#  TELL - ME - ABOUTS                                       #
#############################################################

#                      #
#                      #
# TELL ME ABOUT STUFF  #
#      "my name"       #
#      (970-979)       #
#                      #
#                      #
{970}{}{Questo e' il mio nome.}
{971}{}{Stai parlando con me.}
{972}{}{Che domanda sciocca. Sono io.}

#                      #
#                      #
# TELL ME ABOUT STUFF  #
#     "don't know"     #
#      (980-989)       #
#                      #
#                      #
{980}{}{Non ne so nulla.}
{981}{}{Spiacente. Non so nulla.}
{982}{}{Mai sentito.}


{1000}{}{Anziana}
{1001}{}{Fondatore}
{1002}{}{Abitante del Vault}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Prescelto}
{1007}{}{Sciamano}
{1008}{}{Hakunin}
{1009}{}{Polvere curativa}
{1010}{}{Ponte}
{1011}{}{Mynoc}

{1100}{}{L'Anziana e' nostra madre e il nostro capo.}
{1101}{}{Il nostro grande antenato che ci ha dato la conoscenza.}
{1102}{}{Il primo a combattere e vincere contro il caos.}
{1103}{}{Si tratta del nostro splendido villaggio.}
{1104}{}{E' un avamposto commerciale a pochi giorni a est di qui.}
{1105}{}{Il Vault e' il Paradiso.}
{1106}{}{Tu sei il prescelto.}
{1107}{}{Egli ci cura con le sue erbe e con la magia. Si trova nella zona nord del villaggio.}
{1108}{}{Egli ci cura con le sue erbe e con la magia. Si trova nella zona nord del villaggio.}
{1109}{}{E' una polvere magica che ti guarisce, ma che ti intorpidisce.}
{1110}{}{Il Grande Ponte e' l'uscita sud del nostro villaggio.}
{1111}{}{Egli fa la guardia al ponte che conduce al nostro villaggio.}
