{100}{}{Vedi un uomo basso con un libro tra le mani.}
{101}{}{Vedi Doc Jones, il dottore.}
{102}{}{Vedi un uomo basso con un libro intitolato "E cosi' tu vorresti diventare dottore..."}
{103}{}{Salve, sono Doc Jones. Puoi chiamarmi Doc. Come posso aiutarti?}
{104}{}{Fatto bua. Tu aggiustare?}
{105}{}{Sento vomito. Tu aggiustare?}
{106}{}{Me moncherino, tu aggiustare?}
{107}{}{Me ha domande. Okay?}
{108}{}{Scusa, me va.}
{109}{}{Sono ferito. Puoi aiutarmi?}
{110}{}{Mi sento male. Puoi aiutarmi?}
{111}{}{Sono stato menomato. Puoi aiutarmi?}
{112}{}{Volevo farti qualche domanda.}
{113}{}{Volevo solo salutare.}
{114}{}{Beh, certo. Ecco, ti daro' un po' di questo -- brucera' un poco -- ora una benda, et voila', sei a posto.}
{115}{}{Me ringrazia. Ciao.}
{116}{}{Grazie, Doc. Mi sento molto meglio.}
{117}{}{Beh, certo. Ecco, devi bere questo -- tutto... so che ha un brutto sapore. Adesso stenditi su quel letto; ti svegliero' domattina.}
{118}{}{Me sente meglio. Ciao.}
{119}{}{Grazie Doc, il tuo trucchetto ha funzionato.}
{120}{}{Mi spiace, ma non ho le attrezzature necessarie per eseguire operazioni chirurgiche. Ti suggerisco di andare in una delle citta' piu' grandi e di visitare un chirurgo. Prova Vault City. E' a nord di qui.}
{121}{}{Okay. Ciao}
{122}{}{Capisco. Grazie comunque.}
{123}{}{Cosa vorresti sapere?}
{124}{}{Tu lavorare per Darion?}
{125}{}{Tu lasciare qui quando volere?}
{126}{}{Tu cosa sapere di Darion?}
{127}{}{Come tu essere qui?}
{128}{}{Avere detto Darion avere cagnolino?}
{129}{}{Me va ora.}
{130}{}{Lavori per Darion?}
{131}{}{Puoi andartene quando vuoi?}
{132}{}{Cosa puoi dirmi a proposito di Darion?}
{133}{}{Come hai fatto a finire quaggiu'?}
{134}{}{Hai detto che Darion ha un cane?}
{135}{}{Grazie per le informazioni. Adesso devo andare.}
{136}{}{Beh, si' e no. Non e' una mia scelta. Sono un prigioniero. Darion sta invecchiando e gli serve un dottore personale che si prenda cura di lui. I Khan mi tengono qui per i suoi bisogni. Preferirei essere qui per curare gli abitanti del paese sopra di noi. Non hanno nessun supporto medico e ci sarebbe molto che potrei fare per loro.}
{137}{}{Okay. Me bisogna sapere di piu'.}
{138}{}{Grazie. Ciao.}
{139}{}{E' molto ammirevole da parte tua.}
{140}{}{Capisco. Adesso devo andare.}
{141}{}{Sono abusivi! Lasciali morire. Continua a vivere senza pensarci.}
{142}{}{No, sono praticamente intrappolato qui. Non posso neanche allontanarmi per rifornirmi di medicinali. Darion manda i suoi a prendere quello che mi serve.}
{143}{}{Me capisce. Va ora.}
{144}{}{Me bisogna chiedere di piu'.}
{145}{}{Immagino che tu non sia una persona abbastanza affidabile da poterti concedere la liberta'...}
{146}{}{Capisco. Mi spiace, ma devo andare.}
{147}{}{Mi dispiace.}
{148}{}{Darion e' un malato mentale, puro e semplice. Ha piu' fantasmi lui in testa che pulci il suo cane. Per quello che so, era un membro di un'altra banda di criminali chiamati anch'essi Khan. Una volta rapirono una ragazza, Tandi, e la tennero prigioniera per chiedere un riscatto. Suo padre non accetto' le loro condizioni, e assoldo' un mercenario per liberarla. Darion fu l'unico a sopravvivere.}
{149}{}{Uh... certo, certo.}
{150}{}{Me deve andare ora.}
{151}{}{Uh-huh. Beh, ora devo andare.}
{152}{}{Wow; sono stupito dalla tua conoscenza.}
{153}{}{Sembra proprio il mio tipo.}
{154}{}{Sono stato rapito. Stavo viaggiando da Vault City a New Reno per una ben meritata vacanza. Una notte mi sono accampato e la mattina dopo mi sono risvegliato legato e imbavagliato. Una settimana circa dopo, mi sono ritrovato qui. E qui mi trovo da allora.}
{155}{}{Ugh.}
{156}{}{Grazie. Me va ora.}
{157}{}{I deboli sono spesso preda dei forti.}
{158}{}{Mi dispiace.}
{159}{}{Interessante, ma devo proprio andare.}
{160}{}{Si', ha un cane. Personalmente, ritengo che sia la creatura piu' meschina e piu' cattiva sulla faccia della terra. Sembra adorare Darion, pero', quindi credo che non possa essere cosi' cattivo.}
{161}{}{Me chiede altro.}
{162}{}{Uh, ciao.}
{163}{}{Capisco. Beh, grazie dell'avvertimento.}
{164}{}{Ah. Beh, ora devo andare.}
{165}{}{Non aiutero' uno come te. Vattene.}
{166}{}{Okay, beh, stai attento... e torna, se ti serve qualcosa.}
{167}{}{Ok.}
{168}{}{Adesso e' paranoico. Crede che Tandi sia ancora sulle sue tracce. E' ossessionato dalla vendetta, e vorrebbe vedere Tandi morta. E' tormentato dal rimorso, dato che lui preferi' nascondersi e sopravvivere, invece di morire con la sua banda... e la lista potrebbe continuare.}
