{100}{}{Vedi un tecnico.}
{101}{}{Vedi un tecnico dell'Enclave.}
{102}{}{Vedi una persona che indossa un camice da laboratorio. Sembra sicuro di se'.}

{103}{}{Si', soldato?}
{104}{}{Me nuovo qui. Serve chiede domande.}
{105}{}{Me solo dice ciao. Me va ora.}
{106}{}{Sono nuovo di qui e sto cercando di ambientarmi nella base. Posso farti qualche domanda?}
{107}{}{Volevo solo salutare. Ci si vede.}

{108}{}{Certo. Ho giusto un paio di minuti. }
{109}{}{Come posso aiutarti?}
{110}{}{Cosa essere questo posto?}
{111}{}{Cosa tuo lavora?}
{112}{}{Dove base madre di Enclave essere?}
{113}{}{Me cerca progetti di vertibird. Dove io trova?}
{117}{}{Me va ora.}
{118}{}{Cos'e' questo posto?}
{119}{}{Di che cosa ti occupi?}
{120}{}{Dove si trova il quartier generale dell'Enclave?}
{121}{}{Avrei bisogno di dare un'occhiata ai progetti dei vertibird. Dove sono custoditi?}
{125}{}{Nulla. Devo andare.}

{126}{}{Questo e' il centro di controllo del traffico aereo. Da qui possiamo monitorare tutti gli spostamenti dei vertibird.}
{127}{}{Me capito. Me chiede ancora.}
{128}{}{Bene. Ancora un paio di domande...}

{129}{}{Sono il responsabile informatico. Mantengo i contatti con il mainframe situato qui sotto.}
{130}{}{Uh-uh....}
{131}{}{Bene. Continua cosi'.}

{132}{}{Non arrivi da li'?}
{133}{}{Uh... no, me viene da nord.}
{134}{}{Veramente no; vengo da nord.}

{135}{}{Oh... Non sapevo che ci fosse un nostro avamposto, lassu'. Ad ogni modo... il quartier generale si trova al largo della costa di San Francisco.}
{136}{}{Come noi arrivare la'?}
{137}{}{Bene... come ci si arriva?}

{138}{}{Con i vertibird, e' ovvio. Non c'e' altro modo, a meno che tu non abbia una nave. E' troppo distante per arrivarci nuotando.}
{139}{}{Grazie.}
{140}{}{Grazie.}

{141}{}{I progetti dei vertibird... Non so proprio a cosa ti possano servire. Ad ogni modo, ti suggerisco di rivolgerti qui accanto, in Manutenzione.}
{142}{}{Okay.}
{143}{}{Capito.}

{153}{}{Ma sei pazzo ad andare in giro senza armatura? Vatti a vestire!}
{154}{}{Se il sergente ti becca senza uniforme, ti fa un culo cosi'.}
{155}{}{Perche' sei senza uniforme? }

{156}{}{Cazzo! Ci stanno invadendo! Allarme!}
{157}{}{Intrusi! Chiamate le guardie!}
{158}{}{Guardie! Intrusi nel centro comunicazioni!}

{159}{}{Che succede? Ci stanno attaccando?}
{160}{}{Come mai e' scattato l'allarme? Che cosa succede?}
{161}{}{Cosa diavolo sta succedendo?}

{162}{}{Sono solo un tecnico! Non spararmi!}
{163}{}{Non sono un soldato, ho fatto solo l'addestramento tecnico!}
{164}{}{Questo e' un camice, non un'armatura! Io taglio la corda!}