{100}{}{Vedi Mr. Cheater.}
{101}{}{Ha comunque l'aria di un cheater.}
{200}{}{Ciao, sono Mr. Cheater. Come posso aiutarti?}
{201}{}{Rapiresti la mia tribu'?}
{202}{}{Mi manderesti alla missione degli Shi?}
{203}{}{Mi manderesti alla missione degli Elron?}
{204}{}{Mi manderesti alla missione della Confraternita?}
{205}{}{Fa' in modo che io sia gia' stato alla base militare.}
{206}{}{Ho rapito la tua tribu'.}
{207}{}{Ti ho assegnato alla missione degli Shi.}
{208}{}{Ti ho assegnato alla missione degli Elron.}
{209}{}{Ti ho assegnato alla missione della Confraternita.}
{210}{}{Ora sei stato alla base militare.}
{211}{}{Grazie, Mr. Cheater.}
