{100}{}{Vedi una guardia.}
{101}{}{Vedi una guardia che indossa una Power-Armor.}
{102}{}{Vedi una persona che indossa una Power-Armor dall'aspetto insolito. Sul petto c'e' uno stemma che non ti e' familiare.}
{103}{}{Niente da segnalare.}
{104}{}{Qui non succede nulla... li' da te, invece?}
{105}{}{Perche' non sei al tuo posto, soldato? Non dovresti gironzolare da queste parti.}
{106}{}{Sei senza uniforme. }
{107}{}{Faresti meglio a presentarti dal Sergente e a vestirti.}
{108}{}{Stai prendendo un grosso rischio a girare senza armatura. Faresti meglio a presentarti all'armeria.}
{109}{}{Chi diavolo...? Allarme! Intrusi!}
{110}{}{Intrusi nel settore! Allarme!}
{111}{}{Intrusi multipli! Suonate l'allarme!}
{112}{}{Allarme sicurezza! Sigillate la base!}
{113}{}{Chiudete tutte le postazioni! Allarme!}
{114}{}{Allarme intruso! Codice rosso!}
{115}{}{Ti schiacceremo!}
{116}{}{L'Enclave dominera' il mondo!}
{117}{}{Perche' l'Enclave viva, tu devi morire!}
{200}{}{...stronzo...}
{201}{}{...si', fai BENE ad andartene...}
{202}{}{...Giovane Marmotta dei miei stivali...}
{203}{}{...si', signore! Fottiti, signore!...}
{300}{}{Aspetta un attimo. Cosa pensi di fare con quel vertibird? Non c'è nessun volo in programma nei prossimi giorni.}
{301}{}{Nrg?}
{302}{}{Lo so.}
{303}{}{Ah, scusa. Stavo solo dando un'occhiata. Me ne vado subito.}
{304}{}{C'è stato un cambio di programma. Questo lo prendo io.}
{310}{}{Come? Oh, capisco. Guardare, ma non toccare. Okay? Toccalo un'altra volta e sei morto.}
{311}{}{(Sorridi poi attacca.)}
{312}{}{(Allontanati.)}
{315}{}{Oh, merda! Abbiamo un intruso. Codice Rosso! Ripeto, Codice Rosso!}
{316}{}{Davvero un'ottima idea. Tocca di nuovo il vertibird e ti pianto una pallottola in mezzo agli occhi.}
{320}{}{Certo. E quindi tu sei...}
{321}{}{...Intenzionato a lasciarti in pace. Scusa il disturbo.}
{322}{}{...Incaricato di portare un messaggio importante al quartier generale.}
{323}{}{Oh, davvero? E cosa dice questo messaggio?}
{324}{}{E' super top secret. Non posso dirtelo.}
{325}{}{Te lo diro', ma e' di vitale importanza che tu non comunichi tale informazione a nessun altro, o scatenerai il panico. Mi e' giunta notizia che uno degli schiavi dell'ultimo carico era infetto. Si tratterebbe di un virus sconosciuto e letale. *Devo* raggiungere la base immediatamente, o saremo tutti spacciati. Adesso piantala di farmi perdere tempo... non c'e' un secondo da perdere.}
{326}{}{E tu speri che me la beva? Sembra proprio che abbiamo un intruso tra noi...}
{327}{}{Diamine! Ah, pazienza. Qua dentro non mi dice mai nulla nessuno. D'accordo. Vai pure.}
{328}{}{Woah, sembra piuttosto grave. Farai meglio ad andare subito. Questa patata bollente te la lascio volentieri. Oh, e non temere: non diro' nulla a nessuno.}
{329}{}{[FATTO]}
