{100}{}{Vedi una persona che indossa una Power-Armor. }
{101}{}{Vedi il Comandante della base di Navarro.}
{102}{}{Vedi una persona che indossa una Power-Armor dall'aspetto insolito. Sul petto c'e' uno stemma che non ti e' familiare.}

{103}{}{Chi diavolo...? Allarme! Intrusi nella base!}
{104}{}{Non ho tempo per chiacchierare con i soldati. Puoi andare.}
{105}{}{E' tempo... di morire.}
{106}{}{Okay.}

{107}{}{Ti ho detto che non ho tempo per te. Esci da questo ufficio e non tornare a meno che non ti mandi a chiamare. Puoi andare!}
{108}{}{Disobbedire ad un ordine diretto di un ufficiale superiore e' considerato tradimento. Non ho tempo per convocare la corte marziale, quindi me ne occupero' personalmente. Guardie! Uccidete questo idiota!}
{109}{}{Okay.}
{110}{}{Fottiti!}

{111}{}{Il FOB e' nell'armadietto la' in fondo. Fa' in modo che l'ufficiale di servizio mi contatti, una volta che il codice sara' stato messo al sicuro. Puoi andare.}
{112}{}{Sissignore!}

{113}{}{Fa' in fretta, soldato: non ho tutto il giorno.}
{114}{}{Sissignore!}

{115}{}{Lascia in pace il mio armadietto o te ne faro' pentire amaramente.}
{116}{}{Sissignore!}

{117}{}{Questa base e' allertata e io non ti riconosco. Fammi vedere i tuoi documenti, soldato.}
{118}{}{Che documenti?}
{119}{}{Andare a diavolo!}
{120}{}{Non credo di averli portati...}
{121}{}{Documenti? Eccoli qua i documenti che cerchi!}

{122}{}{Risposta sbagliata, pidocchio. Devi sempre portare i documenti con te, in ogni momento. Dovresti saperlo!}
{123}{}{Fottiti.}

{124}{}{Lascia in pace il mio armadietto o te ne faro' pentire amaramente.}
{125}{}{E' tempo... di morire.}