#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the information      #
#           concerning doors in a locked state, trapped     #
#           state, locked and trapped state.                #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: September 26, 1997                              #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for description of the door. The #
#  first lines, line 100-1, are for the look_at_proc. The   #
#  remainder until the next block are for description_proc  #
#  based one skill and perception success.                  #
#############################################################

# look_at_proc
{100}{}{Vedi una cassetta di legno.}
{101}{}{Vedi un armadietto di metallo.}
{212}{}{Vedi un refrigeratore.}

# description_proc

# Perception Check Critical Success
{102}{}{Vedi un contenitore robusto con un lucchetto (che puo' essere aperto con un set da scassinatore) e una trappola esplosiva. Utilizzando una leva dovresti essere in grado di forzare il contenitore.}
{103}{}{Vedi un contenitore robusto con un lucchetto e una trappola esplosiva. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}
{104}{}{Vedi un contenitore robusto apparentemente senza serrature e una trappola esplosiva. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}
{105}{}{Vedi un contenitore robusto con un vecchio lucchetto arrugginito e una trappola esplosiva. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}

{106}{}{Vedi un contenitore robusto con un lucchetto (che puo' essere aperto con un set da scassinatore) e una trappola. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}
{107}{}{Vedi un contenitore robusto con un lucchetto e una trappola. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}
{108}{}{Vedi un contenitore robusto apparentemente senza serrature e una trappola. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}
{109}{}{Vedi un contenitore robusto con un vecchio lucchetto arrugginito e una trappola. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}

{110}{}{Vedi un contenitore robusto con un lucchetto (che puo' essere aperto con un set da scassinatore) e un filo tagliato che ne fuoriesce. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}
{111}{}{Vedi un contenitore robusto con un lucchetto e un filo tranciato che ne fuoriesce. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}
{112}{}{Vedi un contenitore robusto apparentemente senza serrature e un filo tranciato che ne fuoriesce. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}
{113}{}{Vedi un contenitore robusto con un vecchio lucchetto arrugginito e un filo tagliato che ne fuoriesce. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}

{114}{}{Vedi un contenitore robusto con un lucchetto (che puo' essere aperto con un set da scassinatore). Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}
{115}{}{Vedi un contenitore robusto con un lucchetto. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}
{116}{}{Vedi un contenitore robusto apparentemente senza serrature. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}
{117}{}{Vedi un contenitore robusto con un vecchio lucchetto arrugginito. Utilizzando una leva, dovresti essere in grado di forzare il contenitore.}

# Perception Check Success

{118}{}{Vedi un contenitore robusto con un lucchetto (che puo' essere aperto con un set da scassinatore) e una trappola esplosiva.}
{119}{}{Vedi un contenitore robusto con un lucchetto e una trappola esplosiva.}
{120}{}{Vedi un contenitore robusto apparentemente senza serrature e una trappola esplosiva.}
{121}{}{Vedi un contenitore robusto con un vecchio lucchetto arrugginito e una trappola esplosiva.}

{122}{}{Vedi un contenitore robusto con un lucchetto (che puo' essere aperto con un set da scassinatore) e una trappola.}
{123}{}{Vedi un contenitore robusto con un lucchetto e una trappola.}
{124}{}{Vedi un contenitore robusto apparentemente senza serrature e una trappola.}
{125}{}{Vedi un contenitore robusto con un vecchio lucchetto arrugginito e una trappola.}

{126}{}{Vedi un contenitore robusto con un lucchetto (che puo' essere aperto con un set da scassinatore) e un filo tagliato che ne fuoriesce.}
{127}{}{Vedi un contenitore robusto con un lucchetto e un filo tranciato che ne fuoriesce.}
{128}{}{Vedi un contenitore robusto apparentemente senza serrature e un filo tranciato che ne fuoriesce.}
{129}{}{Vedi un contenitore robusto con un vecchio lucchetto arrugginito e un filo tagliato che ne fuoriesce.}

{130}{}{Vedi un contenitore robusto con un lucchetto (che puo' essere aperto con un set da scassinatore).}
{131}{}{Vedi un contenitore robusto con un lucchetto.}
{132}{}{Vedi un contenitore robusto apparentemente senza serrature.}
{133}{}{Vedi un contenitore robusto con un vecchio lucchetto arrugginito.}

# Perception Check Critical Failure

{134}{}{Vedi un contenitore danneggiato con un lucchetto (che puo' essere aperto con un set da scassinatore) e una trappola esplosiva.}
{135}{}{Vedi un contenitore danneggiato con un lucchetto e una trappola esplosiva.}
{136}{}{Vedi un contenitore danneggiato apparentemente senza serrature e una trappola esplosiva.}
{137}{}{Vedi un contenitore danneggiato con un vecchio lucchetto arrugginito e una trappola esplosiva.}

{138}{}{Vedi un contenitore danneggiato con un lucchetto (che puo' essere aperto con un set da scassinatore) e una trappola.}
{139}{}{Vedi un contenitore danneggiato con un lucchetto e una trappola.}
{140}{}{Vedi un contenitore danneggiato apparentemente senza serrature e una trappola.}
{141}{}{Vedi un contenitore danneggiato con un vecchio lucchetto arrugginito e una trappola.}

{142}{}{Vedi un contenitore danneggiato con un lucchetto (che puo' essere aperto con un set da scassinatore) e un filo tagliato che ne fuoriesce.}
{143}{}{Vedi un contenitore danneggiato con un lucchetto e un filo tranciato che ne fuoriesce.}
{144}{}{Vedi un contenitore danneggiato apparentemente senza serrature e un filo tranciato che ne fuoriesce.}
{145}{}{Vedi un contenitore danneggiato con un vecchio lucchetto arrugginito e un filo tagliato che ne fuoriesce.}

{146}{}{Vedi un contenitore danneggiato con un lucchetto (che puo' essere aperto con un set da scassinatore).}
{147}{}{Vedi un contenitore danneggiato con un lucchetto.}
{148}{}{Vedi un contenitore danneggiato apparentemente senza serrature.}
{149}{}{Vedi un contenitore danneggiato con un vecchio lucchetto arrugginito.}

# Perception Check Failure

{150}{}{Vedi un vecchio contenitore con un lucchetto (che puo' essere aperto con un set da scassinatore) e una trappola esplosiva.}
{151}{}{Vedi un vecchio contenitore con un lucchetto e una trappola esplosiva.}
{152}{}{Vedi un vecchio contenitore apparentemente senza serrature e una trappola esplosiva.}
{153}{}{Vedi un vecchio contenitore con un vecchio lucchetto arrugginito e una trappola esplosiva.}

{154}{}{Vedi un vecchio contenitore con un lucchetto (che puo' essere aperto con un set da scassinatore) e una trappola.}
{155}{}{Vedi un vecchio contenitore con un lucchetto e una trappola.}
{156}{}{Vedi un vecchio contenitore apparentemente senza serrature e una trappola.}
{157}{}{Vedi un vecchio contenitore con un vecchio lucchetto arrugginito e una trappola.}

{158}{}{Vedi un vecchio contenitore con un lucchetto (che puo' essere aperto con un set da scassinatore) e un filo tagliato che ne fuoriesce.}
{159}{}{Vedi un vecchio contenitore con un lucchetto e un filo tranciato che ne fuoriesce.}
{160}{}{Vedi un vecchio contenitore apparentemente senza serrature e un filo tranciato che ne fuoriesce.}
{161}{}{Vedi un vecchio contenitore con un vecchio lucchetto arrugginito e un filo tagliato che ne fuoriesce.}

{162}{}{Vedi un vecchio contenitore con un lucchetto (che puo' essere aperto con un set da scassinatore).}
{163}{}{Vedi un vecchio contenitore con un lucchetto.}
{164}{}{Vedi un vecchio contenitore apparentemente senza serrature.}
{165}{}{Vedi un vecchio contenitore con un vecchio lucchetto arrugginito.}

#############################################################
#  The following lines are for damage done to the player or #
#  critter who tried to open the door, or failed a traps    #
#  roll.                                                    #
#############################################################

# The following sets of lines are to be translated as:
# You set off the trap and were hit for [x] points of damage.
# NPC sets of the trap and was hit for [x] points of damage.

# Player sets off the trap
{166}{}{Fai scattare la trappola e subisci }
{167}{}{ punti di danno.}

# NPC sets off the trap
{168}{}{ fa scattare la trappola e subisce }
{169}{}{ punti di danno.}

#############################################################
#  The following lines are for when the player uses skills  #
#  on the door.                                             #
#############################################################

# Player uses a skill on the door
# Unlock Door
{170}{}{Riesci abilmente a scassinare il contenitore.}
{171}{}{La tua mancanza di abilita' ha bloccato la serratura del contenitore.}
{172}{}{Non riesci a scassinare il contenitore.}

# Lock Door
{189}{}{Chiudi a chiave il contenitore.}
{190}{}{Non riesci a chiudere a chiave il contenitore.}

# Find Trap on the Door
{194}{}{Trovi una trappola nel contenitore.}
{195}{}{Non riesci a trovare trappole nel contenitore.}

# Disarm the Trap on the Door
{196}{}{Sei riuscito a disattivare la trappola.}
{198}{}{Non riesci a disattivare la trappola.}

# NPC uses a skill on the door
# The following lines are prepended by the NPC's name

# Unlock Door
{173}{}{ riesce abilmente a scassinare il contenitore.}
{174}{}{, con la sua mancanza di abilita', ha bloccato la serratura del contenitore.}
{175}{}{ non riesce a scassinare il contenitore.}

# Lock Door
{191}{}{ chiude a chiave il contenitore.}
{192}{}{ non e' riuscito a chiudere a chiave la porta.}

# Find Trap on the Door
{199}{}{ trova una trappola nel contenitore.}
{200}{}{ non riesce a trovare trappole nel contenitore.}

# Disarm the Trap on the Door
{201}{}{ disattiva abilmente la trappola.}
{202}{}{ non riesce a disattivare la trappola.}

# Using a key on the door.
{400}{}{Apri il contenitore.}

#############################################################
#  The following lines are for when the player tries to     #
#  use items on the door which are not lockpicks.           #
#############################################################

# Player uses an item on the door
{176}{}{Forzi il contenitore.}
{177}{}{Nel tentativo di forzare il contenitore, ti stiri la schiena e subisci un punto di danno.}

# The following set of lines is to be translated as:
# While trying to bust the lock, you strain your back and
# take [x] points of damage.

{178}{}{Nel tentativo di forzare il contenitore, ti stiri la schiena e subisci }
{179}{}{ punti di danno.}
{180}{}{Sei troppo debole per forzare il contenitore.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ forza il contenitore.}
{182}{}{, nel tentativo di forzare il contenitore, si stira la schiena e subisce un punto di danno.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{, nel tentativo di forzare il contenitore, si stira la schiena e subisce }
{184}{}{ punti di danno.}

{185}{}{ e' troppo debole per forzare il contenitore.}
{186}{}{ si stira la schiena nel tentativo di forzare il contenitore e subisce un punto di danno.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ si stira la schiena nel tentativo di forzare il contenitore e subisce }
{188}{}{ punti di danno.}

#############################################################
#  Damage done to the door due to explosives.               #
#############################################################

{193}{}{L'esplosivo non ha fatto un graffio al contenitore.}

#############################################################
#  Reporting Door Status should it be used.                 #
#############################################################

{203}{}{Il contenitore sembra essere chiuso a chiave.}
{204}{}{Noti una trappola collegata al contenitore.}

# NPC finds trap
# The following line is to be translated as:
# NPC notices a trap in the door jamb.

{205}{}{ nota una trappola collegata allo stipite del contenitore.}

#############################################################
#  Setting traps on a door and whether the door is open or  #
#  closed to set the trap.                                  #
#############################################################

# Player tries to set a trap on an open door
{206}{}{Non sei in grado di piazzare una trappola su questo contenitore, perche' il contenitore e' aperto.}

# NPC tries to set a trap on an open door
{207}{}{ non e' in grado di piazzare una trappola su questo contenitore, perche' il contenitore e' aperto.}

# Player tries to set a trap on a closed door
{208}{}{Piazzi una trappola nel contenitore.}
{209}{}{Non riesci a piazzare una trappola nel contenitore.}

# NPC tries to set a trap on a closed door
{210}{}{ piazza una trappola nel contenitore.}
{211}{}{ non riesce a piazzare una trappola nel contenitore.}
