# Player uses a skill on the door
# Unlock Door
{170}{}{Riesci a scassinare abilmente l'armadietto.}
{171}{}{La tua mancanza di abilita' ha bloccato la serratura dell'armadietto.} 
{172}{}{Non riesci a scassinare l'armadietto.}

# Unlock Door
{173}{}{ riesce abilmente a scassinare l'armadietto.}
{174}{}{, con la sua mancanza di abilita', ha bloccato la serratura dell'armadietto.}
{175}{}{ non riesce a scassinare l'armadietto.}

# Player uses an item on the door
{176}{}{Forzi l'armadietto.}
{177}{}{Nel tentativo di forzare l'armadietto, ti stiri la schiena e subisci un punto di danno.}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] points of damage.

{178}{}{Nel tentativo di forzare l'armadietto, ti stiri la schiena e subisci }
{179}{}{ punti di danno.}
{180}{}{Sei troppo debole per forzare l'armadietto.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ forza l'armadietto.}
{182}{}{, nel tentativo di forzare l'armadietto, si stira la schiena e subisce un punto di danno.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{, nel tentativo di forzare l'armadietto, si stira la schiena e subisce }
{184}{}{ punti di danno.}

{185}{}{ e' troppo debole per forzare l'armadietto.}
{186}{}{ si stira la schiena nel tentativo di forzare l'armadietto e subisce un punto di danno.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ si stira la schiena nel tentativo di forzare il l'armadietto e subisce }
{188}{}{ punti di danno.}

# Lock Door
{189}{}{Chiudi a chiave l'armadietto.}
{190}{}{Non riesci a chiudere a chiave l'armadietto.}

# Lock Door
{191}{}{ chiude a chiave l'armadietto.}
{192}{}{ non riesce a chiudere a chiave l'armadietto.}

{203}{}{L'armadietto sembra essere chiuso a chiave.}

{800}{}{Hai recuperato il FOB.}
{810}{}{Hai recuperato gli schemi tecnici.}
{820}{}{Hai recuperato il motivatore di K-9.}