{100}{}{Vedi un membro della Gilda degli Schiavisti.}
{150}{}{Vedi Metzger, il capo della Gilda degli Schiavisti.}
{151}{}{[PARLA]}
{152}{}{Guardie! Attaccate!}
{153}{}{[fatto]}
{154}{}{Torna di mattina, dannazione! Faccio affari durante il giorno.}
{155}{}{[fatto]}
{156}{}{Cosa c'e' adesso? Stai davvero cominciando a farmi incazzare.}
{157}{}{Vorrei scusarmi.}
{158}{}{Scusa, ero drogato prima. Non volevo dire niente.}
{159}{}{Ehi, qual e' il tuo problema?}
{160}{}{Volevo farti una domanda.}
{161}{}{A quanto pare si'. Arrivederci.}
{162}{}{Wah.}
{163}{}{Beh, e' troppo tardi per quello. Vattene.}
{164}{}{Per favore, per favore, per favore; mi dispiace.}
{165}{}{Oh beh, ci ho provato.}
{166}{}{Allora vaffanculo!}
{167}{}{Va bene, va bene. Scuse accettate.}
{168}{}{Uff. Posso farti alcune domande?}
{169}{}{Sono contento che abbiamo chiarito. A piu' tardi.}
{170}{}{Ciao. Fa' piacere vederti.}
{171}{}{Ciao Metzger. Dobbiamo parlare.}
{172}{}{Anche a te. Ciao.}
{173}{}{Blurp.}
{174}{}{Sono Metzger, capo della Gilda degli Schiavisti. Cosa ti serve?}
{175}{}{Si', avrei delle domande.}
{176}{}{No grazie. Me ne vado.}
{177}{}{Schiavisti???}
{178}{}{Per favore vattene. Adesso.}
{179}{}{Oppure cosa?}
{180}{}{D'accordo. Ma tornero'!}
{181}{}{OK. ciao.}
{182}{}{Cosa vorresti sapere?}
{183}{}{A proposito del Mercante Vic...}
{184}{}{Posso unirmi alla Gilda degli Schiavisti?}
{185}{}{Vorrei vendere mio marito come schiavo.}
{186}{}{Vorrei vendere mia moglie. Quanto mi date?}
{187}{}{Vorrei vendere uno dei miei amici qui.}
{188}{}{Parlami della gilda.}
{189}{}{Quali citta' comprano i vostri schiavi?}
{190}{}{Vorrei comprare uno schiavo.}
{191}{}{Sto cercando il Vault 13. Ne hai sentito parlare?}
{192}{}{Metzger? E' un nome strano.}
{193}{}{Niente. Devo andare.}
{195}{}{Viene da una lingua antica, del prima guerra o qualcosa del genere.}
{196}{}{Metzger significa macellaio. Appropriato, non credi?}
{197}{}{Era il nome di mio bisnonno. Veniva da qualche posto lontano a
 est. Al di la' di un grande specchio d'acqua.}
{198}{}{Ho letto di un certo Metzger in un libro. Era un presidente, o qualcosa del genere.}
{199}{}{Guarda chi parla, selvaggio.}
{200}{}{E' Germen, Tedesco, Garmen, o qualcosa del genere. Una lingua antica, di
 molto tempo fa.}
{201}{}{Et tu, Brutus?}
{202}{}{Capisco. Ho ancora una domanda, pero'.}
{203}{}{E' la cosa piu' stupida che abbia mai sentito.}
{204}{}{Affascinante. Devo andare.}
{205}{}{La nostra missione e' fornire una forza lavoro stabile e di alta qualita' per
 soddisfare la crescente domanda delle citta' piu' grandi. Vuoi unirti a noi?}
{206}{}{Certo. Sembra ottimo.}
{207}{}{Assolutamente no.}
{208}{}{Ci pensero' su. Quali citta' comprano i vostri schiavi?}
{209}{}{Spiacente, sono informazioni riservate della gilda.}
{210}{}{Ok. Iscrivimi!}
{211}{}{No! Siete dei malati!}
{212}{}{Ci pensero'. Ho altre domande.}
{213}{}{Hmm, tornero' piu' tardi.}
{214}{}{Dovremo marchiare una piccola incisione sulla tua fronte per mostrare a tutti
 la tua appartenenza alla gilda degli schiavisti. Sei pronto?}
{215}{}{Ottimo! Fallo!}
{216}{}{Ho cambiato idea. Posso fare un'altra domanda?}
{217}{}{Non ho tempo adesso. Devo andare.}
{218}{}{Benvenuto nella gilda!}
{219}{}{Ottimo, ho delle domande!}
{220}{}{Ok, grazie. Tornero'.}
{221}{}{Vault 13? No. Aspetta... credo che Vic venga da Vault City. Forse e' quello.}
{222}{}{Si', dov'e'?}
{223}{}{No. Ho un'altra domanda, pero'.}
{224}{}{No, lascia perdere.}
{225}{}{Vendiamo la maggior parte dei nostri schiavi a Vault City e New Reno. New Reno e'
 a sud-est di qui e la maggior parte del Den commercia con essa.}
{226}{}{Dov'e' Vault City?}
{227}{}{Ho delle altre domande.}
{228}{}{Grazie, devo andare.}
{229}{}{Vault City e' a est di qui, un po' a sud. Vic viene da li'.}
{230}{}{Ho delle altre domande.}
{231}{}{Grazie, devo andare.}
{232}{}{Hmm, sembra uno schiavo in buona salute. Ti daro'}
{233}{}{ monete.}
{234}{}{Ok! Affare fatto.}
{235}{}{Uh, lascia perdere.}
{236}{}{Neanche per sogno! Ne voglio il doppio!}
{237}{}{Sei un osso duro. Ecco i tuoi soldi!}
{238}{}{Grazie. Ho altre domande.}
{239}{}{Grazie. Ciao.}
{240}{}{Altro?}
{241}{}{Si', ho una domanda.}
{242}{}{No. Ci vediamo.}
{243}{}{Quale "amico" vuoi vendere?}
{244}{}{Uhm, lascia perdere.}
{245}{}{Interessante. Ti daro'}
{246}{}{ monete.}
{247}{}{Venduto!}
{248}{}{No, grazie.}
{249}{}{Voglio piu' soldi di cosi'!}
{250}{}{D'accordo, ti daro'}
{251}{}{ ma non di piu'!}
{252}{}{Venduto!}
{253}{}{Non basta.}
{254}{}{E' decisamente troppo poco. Me ne vado.}
{255}{}{Che cosa vuoi da Vic? Ora e' roba mia. Non avrebbe dovuto mettersi contro di me.}
{256}{}{Vorrei comprarlo.}
{257}{}{Perche' lo trattieni qui?}
{258}{}{Nulla. Non importa.}
{259}{}{He is not for sale, yet.}
{260}{}{Perche' no?}
{261}{}{Oh, okay.}
{262}{}{He will cost $2000.}
{263}{}{Here is your money.}
{264}{}{That's a lot. Maybe later.}
{265}{}{The cost is $1000.}
{266}{}{Here is your money.}
{267}{}{Don't have that much yet. Bye.}
{268}{}{Our radio is broken and he's in charge of fixing it.}
{269}{}{Capisco.}
{270}{}{You haven't got the money!}
{271}{}{Too bad for me. Can I ask you a question?}
{272}{}{Sorry, I'll come back.}
{307}{}{How dare you return after abandoning your brothers during a Slave Run! Guards! Attack!}
{308}{}{[fatto]}
{309}{}{Excellent! It may take a few days for you to travel there and back. Are you ready to leave now?}
{310}{}{No. Tornero'.}
{311}{}{Yes, I'm ready. Let's go.}
{312}{}{Ah, you are back from the Slave run. Let's see how you did...}
{313}{}{[avanti]}
{314}{}{[avanti]}
{315}{}{You killed potential slaves! A dead man brings us no income! Only kill the ones that are a threat,
 the others are of no threat.}
{316}{}{[avanti]}
{317}{}{You returned no slaves at all! What the hell is wrong with you? We're trying to make money here,
 not lose it.}
{318}{}{[avanti]}
{319}{}{Overall, you did well this Run. Keep up the good work and I might keep you around a while.}
{320}{}{Thank you. I will.}
{321}{}{I don't know if I like this too much.}
{322}{}{You need to improve your enslavement technique.}
{323}{}{Ci provero'.}
{324}{}{I apologize for my poor performance.}
{325}{}{I think I'm good enough.}
{326}{}{Damn it! You did terribly in this Run. Are you trying to ruin me? Be more careful next time.
 You don't need to kill them all! Just kill off the hostile ones. Leave the unarmed ones for collection.}
{327}{}{I'm sorry, Metzger.}
{328}{}{Hey, it's tough work to be a Slaver!}
{329}{}{I'd like to see you do better.}
{330}{}{Vorrei partecipare ad un rastrellamento di schiavi.}
{331}{}{Damn it! I hate losing any guild member on a Run. Try to watch each other's back!}
{332}{}{Overall, you did well this Run. Here is $}
{333}{}{ as an incentive for you to keep up the good work.}
