{100}{}{Vedi un uomo magro, dall'aspetto untuoso.}
{150}{}{Vedi Flick. Si sta dando una prolungata grattata al pacco.}
{151}{}{Vedi un tipo poco pulito con un brutto tic facciale.}
{200}{}{Fora dae bae, goldon.}
{201}{}{Ehi, digo a ti! Si', ti. Fora.}
{202}{}{Ti xe sordo o cossa?}
{203}{}{Che problemi ti ga, eh?}
{204}{}{Fora dae bae.}
{220}{}{Ehila', me ciamo Flick. Cossa diavolo ti vol, eh?}
{221}{}{Cossa ti ga? Ti xe drio a sprecar il mio tempo.}
{222}{}{Come mai hai questo strano accento, Flick?}
{223}{}{Cosa diavolo fai qui?}
{224}{}{Sto cercando un Vault - ah si', e anche un certo mercante di nome Vic. Sai per caso dove potrebbero essere?}
{225}{}{Vorrei barattare con te.}
{240}{}{Te va ben, amico?}
{241}{}{Veramente, mi piacerebbe dare un'altra occhiata alla tua merce, se possibile.}
{242}{}{Veramente, vorrei farti una domanda.}
{243}{}{That did it. See you around, Flick.}
{260}{}{Mi so un mercante, cossa ti credi? 'na specie de bon Samurai-tano.}
{261}{}{Come?}
{262}{}{Certo, ehm, beh…lascia che ti chieda qualcos'altro.}
{263}{}{Ah, oh. OK. Ci vediamo, Flick.}
{280}{}{Vendo per i miei fioi.}
{281}{}{Vendi fiori?}
{290}{}{Fi-o-i, ti sa, i bambini. I miei bambini.}
{291}{}{I tuoi bambini?}
{292}{}{Beh, non mi interessano composizioni floreali fatte da bambini. Lascia che ti chieda qualcos'altro.}
{300}{}{Certo, ostrega... beh, i lavora per mi. I me porta dele cosse. Picole cosse. Cio', ti sa?}
{301}{}{Uh, no.}
{302}{}{Oh, OK. Lascia che ti chieda qualcos'altro, allora.}
{303}{}{Ah, capisco. Beh, non vorrei rovinarti gli, ehm, affari, stando qui. Ci vediamo.}
{315}{}{They bring me stuff that they find. Little, little things. Stuff no one ain't usin' no more. In return, I takes care of 'em.}
{316}{}{Sembra che vi siate sistemati bene.}
{325}{}{(alza le spalle) No me lamento.}
{326}{}{Lascia che ti chieda qualcos'altro, allora.}
{327}{}{Sicuramente ti hanno portato dei veri affari. Vediamo cos'hai da offrirmi.}
{328}{}{Ero solo curioso. Beh, ci vediamo, Flick.}
{340}{}{Cossa ti xe drio a dir? Ti credi che sia un goldon? Ti credi che abbia ea mare putana? Ti credi che sia un paiasso? Che sia qui per divertirte, eh?}
{341}{}{Ehm, no. Scusa, ero solo curioso. Lascia che ti chieda qualcos'altro.}
{342}{}{Si', esatto, testa di cazzo. E niente mi divertira' di piu' che sentire i tuoi lamenti prima di morire.}
{343}{}{Beh, se devi proprio diventare cosi' permaloso, me ne vado.}
{360}{}{Vault, eh? Forse ea Mama ne sa qualcossa, ma mi no so niente. Ma quel fio, Vic - lo cognosso. Metzger lo ga preso, sa morti cani.}
{361}{}{Vic? E chi xe quel vecio che ti ga co' ti? Goldon. Ma 'sto Volt... mi no so cossa sia. Forse ea Mama lo sa.}
{362}{}{Chi e' Metzger?}
{363}{}{Ea Mama?}
{364}{}{Grazie. Lascia che ti chieda qualcos'altro.}
{365}{}{Grazie, e' tutto quello che mi serviva sapere. Ci vediamo.}
{380}{}{Ea Mama xe la parona del bacaro nela parte est dela citta'. Subito dopo el simitero. Xe un bel posto, fa dea bona pasta, Mama mia.}
{381}{}{Grazie. Cosa mi sai dire a proposito di questo Metzger, il tipo che ha preso Vic?}
{382}{}{Grazie. Lascia che ti chieda qualcos'altro.}
{383}{}{Grazie, e' tutto quello che mi serviva sapere. Ci vediamo.}
{400}{}{Gia'. Metzger, quel cancaro, xe morto. No so cossa sia sucesso a Vic.}
{401}{}{Quel Metzger, el xe un vero rompiballe. Xe el paron dela Gilda dei Sciavi. Nea zona est dela citta', a nord del bacaro dea Mama. Comunque, xe lu che ga preso Vic, son sicuro.}
{402}{}{Grazie, ma cosa mi sai dire di Mama?}
{403}{}{Grazie. Lascia che ti chieda qualcos'altro.}
{404}{}{Grazie, e' tutto quello che mi serviva sapere. Ci vediamo.}
