# 0. Look
{100}{}{Vedi un gangster.}

{150}{}{Pare sia un membro della gang di Lara.}
{151}{}{Pare sia un membro della gang di Lara.}

# 1. Hostile
{200}{}{Fa' il bravo.}
{201}{}{Eccoti qua.}
{202}{}{La pagherai.}
{203}{}{Vieni qui.}
{204}{}{Non te la faro' passare liscia.}
{205}{}{Stronzo.}

# 2. Metzger's Dead
{225}{}{Mi domando quanto potranno andare avanti le cose, adesso che Metzger e' morto...}
{226}{}{E cosi', alla fine Metzger e' morto...}
{227}{}{E' stata opera tua?}
{228}{}{Il Den non sara' mai piu' lo stesso.}

# 3. 2Won
{240}{}{Non posso crederci, li abbiamo sconfitti sul serio!}
{241}{}{Adesso Metzger dovra' mostrarci rispetto.}
{242}{}{Gliel'abbiamo proprio fatta vedere.}
{243}{}{Abbiamo mostrato loro cosa noi intendiamo per "giustizia".}
{244}{}{Non ce l'avremmo mai fatta senza di te!}
{245}{}{Grazie dell'aiuto!}
{246}{}{Ce l'abbiamo fatta!}

# 4. NO SHOW
{247}{}{Ci hai preso per il culo?}
{248}{}{Farai meglio a guardarti le spalle.}
{249}{}{Lara e' l'unica ragione che ci trattiene dal farti fuori.}
{250}{}{Che cosa cercavi di fare?}

# 5. COWARD
{251}{}{Codardo.}
{252}{}{Mi fai vomitare.}
{253}{}{Smamma.}
{254}{}{Sparisci.}

# 6. FIGHT
{255}{}{Siamo pronti quando lo sei tu.}
{256}{}{E' quasi giunta l'ora di fargliela pagare.}
{257}{}{Odio aspettare.}
{258}{}{Andiamo, dai!}
{259}{}{Non sei ancora pronto?}
{260}{}{Fa' sapere a Lara quand'e' giunto il momento.}

# 7. NO
{270}{}{Vuoi unirti a noi?}
{271}{}{Sei qui per vedere Lara, immagino.}
{272}{}{Come va?}
{273}{}{Lara e' la persona con la quale dovresti parlare.}
{274}{}{Ciao.}
{275}{}{Sei qui per vedere Lara?}

# 8. Else
{300}{}{Ciao.}
{301}{}{Come va?}
{302}{}{Spero che le cose ti vadano bene.}
{303}{}{Non e' che potresti aiutarci?}
{304}{}{E' bello vederti.}
{305}{}{Presto gliela faremo pagare, a Tyler...}
{306}{}{Ci sono novita'?}

# 9. Lara Dead
{310}{}{Grazie dell'aiuto. E' un peccato che Lara non ce l'abbia fatta.}
{311}{}{Finalmente li abbiamo sconfitti!}
{312}{}{Non ce l'avremmo mai fatta senza di te.}
{313}{}{Almeno Lara e' caduta in battaglia.}
{314}{}{Non riesco a credere che Lara non ce l'abbia fatta.}
{315}{}{Abbiamo dimostrato a Metzger chi sono i migliori.}
{316}{}{Metzger fara' meglio a non darci fastidio.}

# 10. Running to fight
{350}{}{L'hai detto!}
{351}{}{Sono carne morta!}
{352}{}{Spacchiamo tutto!}
