# 0. Look
{100}{}{Vedi Lara.}

{150}{}{E' la leader di questa banda.}

# 1. Start (From Where to go)
{200}{}{Mi chiamo Lara; sono il capo di questa banda. Sara' meglio che tu non sia qui per causare guai o preparati a sperimentare un nuovo modo di intendere il dolore.}
{201}{}{Ciao. Ti serve qualcosa?}
{202}{}{Hai del lavoro?}
{203}{}{Stavo solo dando un'occhiata in giro.}
{204}{}{Sto cercando un mercante di nome Vic.}
{205}{}{Aruh.}
{206}{}{Rara.}

# 2. Dumb, bye (From 1, 26)
{220}{}{Non ci sono dottori qui in citta' e io non posso aiutarti.}
{221}{}{Scusa, continuo a non capire.}
{222}{}{Ack.}

# 3. Vic (From 1)
{230}{}{Questo nome non mi dice molto, ma comunque io non sto molto attenta a chi entra o esce dalla citta'. Prova a chiedere a Becky. Prima o poi tutti passano dal suo locale. Forse lei lo sa.}
{231}{}{Hai del lavoro?}
{232}{}{Grazie. Addio.}

# 4. Looking around (From 1)
{240}{}{Se non sei venuto al Den per un motivo specifico, probabilmente faresti meglio ad andartene. Questo non e' un posto molto sicuro.}
{241}{}{Oh, okay.}
{242}{}{Hai del lavoro?}
{243}{}{So badare a me stesso.}
{244}{}{Okay, grazie.}

# 5. Handle (From 4)
{250}{}{Non ne dubito. Altrimenti non ce l'avresti mai fatta ad arrivare vivo fino a qui.}
{251}{}{Uh, si', lo so. Me l'hai gia' detto prima.}
{252}{}{Hai del lavoro?}
{253}{}{Okay, grazie.}

# 6. Got work? (From 1, 3-5)
{260}{}{Beh, dipende da quello che sei in grado di fare. C'e' qualcosa che mi incuriosisce. Se riesci a scoprire quello che voglio, ti paghero'.}
{261}{}{Come ti ho detto, sto cercando informazioni su un certo oggetto... o luogo. Ti paghero', naturalmente.}
{262}{}{D'accordo. Di cosa si tratta?}
{263}{}{Magari un'altra volta.}

# 7. Bye, let me know if mind changes (From 6)
{270}{}{Fammi sapere se cambi idea.}
{271}{}{D'accordo.}

# 8. Setting Crates (From 6)
{280}{}{Beh, c'e' una chiesa ad est di qui. Metzger ha messo delle persone a guardia di quello che c'e' all'interno. Scopri di cosa si tratta e ti daro' 200$.}
{281}{}{E' facile. Lo so gia'.}
{282}{}{Certo.}
{283}{}{Vedro' di fare il possibile.}

# 9. Thanks (From 8)
{290}{}{Grazie. Non farti coinvolgere in uno scontro... per adesso. Ho un piano.}
{291}{}{Nessun problema.}
{292}{}{Torno subito.}

# 10. Crates Answered (From 8)
{300}{}{Di cosa si tratta?}
{301}{}{Composti chimici grezzi contenuti in grandi casse.}
{302}{}{Grossi contenitori che contengono prodotti chimici di qualche tipo.}
{303}{}{Vorrei controllare un'altra volta.}

# 11. Crates Answered (From 10, 18)
{310}{}{Il tutto ha un senso. Grazie. Ecco i tuoi soldi.}
{311}{}{Cosa vuoi dire?}
{312}{}{Nessun problema. Addio.}

# 12. Makes Sense? (From 11)
{320}{}{Ho visto alcune carovane provenienti da Vault City scaricare quelle casse, che vengono poi prelevate da altre carovane arrivate qui da New Reno.}
{321}{}{E allora? Perche' dici che tutto ha un senso?}
{322}{}{Oh.}

# 13. Makes Sense, Bye (From 12)
{340}{}{New Reno e' la capitale della droga. Da qualche parte dovranno pur prendere i materiali grezzi per produrla, no? E sembra proprio che ne prendano una parte, o addirittura tutti, da Vault City.}
{341}{}{Dove si trova New Reno?}
{342}{}{Okay, grazie.}

# 14. Located? (From 13)
{350}{}{Non lo so con esattezza. Da qualche parte a sud, credo. Non ci sono mai stata, ho solo visto le loro carovane fermarsi qui una volta, parecchio tempo fa.}
{351}{}{Ah, okay. Grazie.}

# 15. (From 11-14)
{360}{}{Che ne diresti di qualche soldo veloce-veloce? 50$. Soldi facili.}
{361}{}{Certo.}
{362}{}{Dimmi tutto.}

# 16. Set Ask (From 15)
{370}{}{Voglio che tu vada da Metzger a chiedergli se ci puo' dare il suo nulla-osta per sedare una vecchia questione tra me e Tyler. Lui capira' a cosa mi riferisco.}
{371}{}{Perche' vuoi che vada io a chiederglielo?}
{372}{}{Se capitera' l'occasione.}
{373}{}{Okay.}

# 17. Why PC ask Metzger (From 16)
{380}{}{Perche' non voglio che Tyler veda qualcuno della mia banda entrare o uscire dal palazzo di Metzger. Non voglio rovinare la sorpresa.} ###???I don't want to tip our hand
{381}{}{Non lo capisci? Se Tyler dovesse vedermi parlare con Metzger, potrebbe sospettare qualcosa.}
{382}{}{Vedremo.}
{383}{}{Okay.}

# 18. On Crate Quest (From WTG)
{390}{}{Allora, hai scoperto cosa c'e' la' dentro?}
{391}{}{Composti chimici grezzi contenuti in grandi casse.}
{392}{}{Grossi contenitori che contengono prodotti chimici di qualche tipo.}
{393}{}{Non ancora.}

# 19. Ask/Permission (From WTG)
{400}{}{Hai gia' parlato con Metzger? Che cosa dice?}
{401}{}{Dice di si'. Se vincete, potete prendere il loro lavoro, come sempre.}
{402}{}{Nah.}

# 20. Permission Done (From 19)
{410}{}{Ottimo. Speravo proprio che dicesse cosi'. Ho sentito che ultimamente si era lamentato di loro. Ecco i tuoi soldi.}
{411}{}{Adesso immagino ci sia qualcos'altro da fare, giusto?}
{412}{}{Grazie. Addio.}

# 21. Wait, need info... (From 20)
{420}{}{Ho un altro lavoro per te. Non so come tu possa fare, ma dal momento che sei riuscito ad entrare, forse significa che si fidano di te.}
{421}{}{In realta' sono entrato di nascosto.}
{422}{}{Di cosa si tratta?}

# 22. Snuck (From 21)
{430}{}{Sono sicura che riuscirai ad inventarti qualcosa.}
{431}{}{Okay, di cosa si tratta?}

# 23. Setting Find (From 20-22)
{440}{}{Non possiamo batterli, data la loro forza attuale. Loro hanno piu' soldi e ci sono leggermente superiori di numero. Se tu riuscissi a trovare una qualche loro debolezza che ci consenta di equilibrare le forze, o se tu scoprissi qualcosa da sfruttare a nostro favore...}
{441}{}{Eh? Trovare una debolezza? E come credi che possa farcela?}
{442}{}{Quanto?}
{443}{}{Consideralo fatto.}

# 24. How Much? (From 23)
{450}{}{Ti daremo 150$. Non c'e' modo per noi di avvicinarci abbastanza a loro da scoprirla.}
{451}{}{Vedro' di fare il possibile.}
{452}{}{Okay.}

# 25. Weakness??? (From 23)
{460}{}{Non lo so. E' per questo che ti sto chiedendo aiuto.}
{461}{}{Ci provero'.}
{462}{}{Tutto questo non ha senso.}

# 26. Find/Weakness report (From WTG)
{470}{}{Hai scoperto qualcosa?}
{471}{}{Si'. Stanotte faranno una festa.}
{472}{}{Non ancora. Te lo faro' sapere.}
{473}{}{Gra.}
{474}{}{Na.}

# 27. Skeleton crew(From 4)
{480}{}{Eccellente! Lasceranno sicuramente un corpo di guardia ridotto all'osso. Questo sara' un gran bel vantaggio per noi. Faremo fuori quelli alla festa dopo aver assaltato la chiesa.} ###???They're sure to leave a skeleton crew
{481}{}{E i miei soldi?}

# 28. Money ? (From WTG & 27)
{490}{}{Non credo che te li daro' subito. Se vuoi vedere i tuoi soldi, dovrai venire con noi. Non ti sto chiedendo di combattere, ma voglio essere sicura che non sia una trappola. In totale ti daremo 300$.}
{491}{}{Sei pronto?}
{492}{}{Okay, andiamo.}
{493}{}{Dammi un attimo per prepararmi.}
{494}{}{Puoi scordartelo. Tieniti pure i tuoi soldi!}

# 29. Wait to fight. (From 28, 30)
{500}{}{Okay, ma noi ci muoveremo presto, quindi non impiegarci troppo o perderemo la nostra occasione.}
{501}{}{Okay.}

# 30. Coward (From WTG & 28)
{510}{}{Non devi combattere. Soldi facili.}
{511}{}{Beh, hai cambiato idea?}
{512}{}{Andiamo. Sono pronto.}
{513}{}{Okay, torno subito.}
{514}{}{No.}
{515}{}{Uk}

# 31. CF: No Show (From WTG)
{520}{}{Per colpa tua abbiamo perso la nostra occasione.}
{521}{}{Codardo!}
{522}{}{Non vedrai un quattrino.}
{523}{}{Probabilmente era una trappola.}
{524}{}{Mi spiace, ma non sei affidabile.}
{525}{}{Non posso fidarmi di te.}

# 32. CF: 2 Won (From WTG)
{530}{}{Ce l'abbiamo fatta!}
{531}{}{Grazie dell'aiuto.}
{532}{}{Grazie mille!}
{533}{}{Finalmente ho ripagato Tyler per quello che ha fatto a mio fratello.}
{534}{}{Grazie di nuovo.}

# 33. CF: Metzger Dead (From WTG)
{540}{}{Adesso che Metzger e' morto, non so cosa succedera'.}
{541}{}{Forse dovremmo sciogliere la banda.}
{542}{}{Hai sentito che Metzger e' morto? Adesso non so cosa fare.}
{543}{}{Adesso cosa accadra' al Den? Forse le cose miglioreranno.}
{544}{}{La morte di Metzger forse migliorera' le cose.}

# 34. CF: Hostile (From WTG)
{550}{}{Bastardo!}
{551}{}{Puttana!}

# 35. CF:  Reward (From WTG)
{560}{}{Grazie. Ecco i tuoi soldi e un bonus di 100$.}

# 36. Gang Dead (From WTG)
{570}{}{Hai ucciso Tyler e la sua banda? E adesso come faremo a dimostrare la nostra forza a Metzger? Non ci assumera' mai. Questa era la nostra unica possibilita'.}
{571}{}{Non abbiamo piu' un lavoro. Qualcuno ha ucciso le guardie di Metzger e adesso lui non ci rivolge la parola. Crede che siamo stati noi. Davvero magnifico...}
{572}{}{Scusa.}
{573}{}{Che peccato.}
{574}{}{Sono stato io, e voi siete i prossimi.}
{575}{}{Oh. Okay, ciao.}
{576}{}{Uhr?}
{577}{}{Ug.}

# 37. Gang Dead Cont. (From 36)
{590}{}{Ti avevo detto che dovevamo andare insieme. Dal momento che non c'era nessuno a sorvegliare la chiesa, qualcuno l'ha ripulita e adesso Metzger e' incazzato nero.}
{591}{}{Ti avevo detto di trovare un punto debole, non di ucciderli! Dal momento che non c'era nessuno a sorvegliare la chiesa, qualcuno l'ha ripulita e adesso Metzger e' incazzato nero.}
{592}{}{Dannazione! Ti avevo detto di andare a chiedere il permesso a Metzger, non di ucciderli! Dal momento che non c'era nessuno a sorvegliare la chiesa, qualcuno l'ha ripulita e adesso Metzger e' incazzato nero.}
{593}{}{Dannazione! Ti avevo detto di non attaccarli! Dal momento che non c'era nessuno a sorvegliare la chiesa, qualcuno l'ha ripulita e adesso Metzger e' incazzato nero.}
{594}{}{Oh, beh, devo andare.}
{595}{}{Un vero peccato.}
{596}{}{E tu sei la prossima, troia.}
{597}{}{Hmph!}
{598}{}{Tu essere prossima!}

# 38. CF: Next times Gang Dead (From WTG)
{610}{}{Sai davvero come mandare a puttane le cose, vero?}
{611}{}{Non abbiamo piu' bisogno del tuo aiuto.}
{612}{}{Va' a disturbare qualcun altro.}
{613}{}{Sara' meglio per te che Metzger non dia la colpa a noi.}
{614}{}{Mi spiace. Non posso aiutarti.}
{615}{}{Non posso parlare. Sto cercando di capire cosa fare adesso.}
{616}{}{Spero che Metzger non pensi che noi c'entriamo qualcosa.}
{617}{}{E adesso che cosa faremo?}
{618}{}{Faremo meglio ad andarcene in fretta in caso Metzger pensasse che siamo stati noi ad uccidere le sue guardie.}
{619}{}{Sei mai stato a New Reno? Forse ci dirigeremo la' - o a nord.}

# 39. Running to Fight
{650}{}{Okay! Andiamo! Seguitemi!}
