{100}{}{You see the owner of the saloon.}
{101}{}{You see Becky.}
{150}{}{This looks like the owner.}
{151}{}{This is Becky, owner of this place.}
{152}{}{[PARLA]}
{153}{}{Hello, stranger, and welcome to my saloon. I'm Becky.}
{154}{}{Hello, I am }
{155}{}{. Cosa c'e' da fare da queste parti?}
{156}{}{Ciao, sono }
{157}{}{. Can I ask some questions?}
{158}{}{Mammina?}
{159}{}{Mag gah.}
{160}{}{Smamma. Non ho bisogno di gente come te da queste parti.}
{161}{}{Mmmm...}
{162}{}{Fottiti.}
{163}{}{Sto andando.}
{164}{}{Sorry, no offense was meant. Can I ask something?}
{165}{}{Drink of whiskey is $5 and the gambling tables are right over there. Have a good one.}
{166}{}{Posso farti una domanda?}
{167}{}{I want a drink!}
{168}{}{Hmm, those are some cheap drinks. Let's see one.}
{169}{}{Grazie. Ciao.}
{170}{}{Vault 13? Nope, never heard of it.}
{171}{}{Hmm, can I ask something else?}
{172}{}{Damn, I need to find it. Bye.}
{173}{}{Cosa vorresti sapere?}
{174}{}{C'e' un buon posto dove mangiare?}
{175}{}{Sa dove si trova il Vault 13?}
{176}{}{Come mai i tuoi drink sono cosi' a buon mercato?}
{177}{}{Nulla. Arrivederci.}
{178}{}{Mom runs a little restaurant across town.}
{179}{}{Mommy! Mommy!}
{180}{}{One more question.}
{181}{}{Grazie. Ciao.}
{182}{}{Smamma.}
{183}{}{Gwah.}
{184}{}{Ti daro' io qualcosa da battere.}
{185}{}{Quick question first?}
{186}{}{Addio.}
{187}{}{A shot of whiskey is $5. Pay first.}
{188}{}{Eh?}
{189}{}{Ok. Ecco i soldi.}
{190}{}{Changed my mind.}
{191}{}{Sono un po' a corto di soldi. Posso mettere in conto?}
{192}{}{Posso farti una domanda?}
{193}{}{Gotta go.}
{194}{}{Ecco l'ordinazione. Serve qualcos'altro?}
{195}{}{Question?}
{196}{}{Yeha, how about you and I...}
{197}{}{No.}
{198}{}{Hey, you don't enough cash for this drink. You're poorer than even these sops!}
{199}{}{Scusa.}
{200}{}{Hmm, tornero' piu' tardi.}
{201}{}{Hmm. Let me get someone to watch the bar. You and I can go into the back room and play a little
 game I call "First Strike." If you're good, well, there's "Ground Zero."}
{202}{}{OK!}
{203}{}{Er... uh... devo andare.}
{205}{}{You were OK.}
{206}{}{Next time, let's play "Into the Glow." But for now...}
{207}{}{Puoi fare qualcosa per me?}
{208}{}{Devo andare, ma tornero' piu' tardi.}
{209}{}{What can I do for you, sweet cheeks?}
{210}{}{Ho bisogno di un altro po' d'amore.}
{211}{}{I got some questions.}
{212}{}{How can you sell your drinks so cheaply?}
{213}{}{How about a drink?}
{214}{}{Devo correre. Ci si vede.}
{215}{}{Not now. Maybe later. Yes, definitely later.}
{216}{}{Posso farti una domanda?}
{217}{}{A piu' tardi, allora.}
{218}{}{I have a still in the basement. I made it myself. Beats paying triple to those New Reno
 gangsters.}
{219}{}{Smart girl! I like that!}
{220}{}{Hmm, devo andare. Ci vedremo piu' tardi.}
{221}{}{Why? Why did you destroy my still? You bastard!}
{222}{}{Nothing personal. I got paid to do it.}
{223}{}{Mi dispiace.}
{224}{}{Addio.}
{225}{}{Ne faro' semplicemente un altro, lo sai.}
{226}{}{I know.}
{227}{}{Beh, e' un bene.}
{228}{}{Addio.}
{232}{}{Why? Why did you destroy my still? You bitch!}
{233}{}{Where are you, baby?}
{234}{}{Are you coming?}
{235}{}{Sto aspettando.}
{236}{}{I'm in here, lover.}
{237}{}{I've got a bar to run.}
{238}{}{Follow me, sugar.}
{240}{}{How did you... Do that... Uhhh...}
{241}{}{It's O.K., size doesn't really matter.}
{242}{}{That was, ummm, nice -- I guess.}
{243}{}{Thanks, sweety; that was fun.}
