{100}{}{Vedi un tossicodipendente.}
{101}{}{Vedi Petey.}
{150}{}{Questo qui e' un povero tossicodipendente.}
{151}{}{Petey sembra aver bisogno di aiuto.}
{152}{}{[parla]}
{155}{}{[cough, cough] Hai qualche spicciolo da dare a Petey?}
{156}{}{Certo, ecco qua.}
{157}{}{No, sta' lontano da me.}
{158}{}{Pipii'?}
{159}{}{Sei piu' fatto di me. [cough] Grazie lo stesso.}
{160}{}{Mi spiace; ciao.}
{161}{}{Duh, grazie mile, ah-hah, certo.}
{162}{}{Sara' per la prossima volta. Grazie lo stesso. [cough]}
{163}{}{[fatto]}
{164}{}{Grazie mille. [cough] Mille mila mille.}
{165}{}{Di nulla.}
{166}{}{Seh, seh.}
{167}{}{Signore, [cough] potrebbe aiutare un povero derelitto?}
{168}{}{Here's $5.}
{169}{}{Non oggi.}
{170}{}{Va' a lavorare.}
{171}{}{Gentile signora, la prego, aiuti [cough] un povero uomo affamato, troppo [cough] malato per lavorare.}
{172}{}{Oh, poverino... ecco 5$.}
{173}{}{Ho la sana abitudine di non dare soldi agli accattoni, io.}
{174}{}{No.}
{200}{}{Ehi, amico; hai qualche spicciolo?}
{201}{}{Ha qualche spicciolo, gentile signore?}
{202}{}{Ehi, potresti darmi qualche dollaro?}
{203}{}{Credi di potermi dare un paio di dollari?}
{204}{}{Credi di potermi prestare qualche spicciolo?}
{205}{}{Ha qualche spicciolo, gentile signora?}
{206}{}{Ehi, miss; hai qualche spicciolo?}
{220}{}{La prego, mi aiuti, signore.}
{221}{}{Ahhh, sto male.}
{222}{}{Ho bisogno di aiuto. Sto tanto male.}
{223}{}{Signora, mi puo' aiutare?}
{225}{}{Ti ringrazio molto.}
{226}{}{Ehi, cosa pensi di fare?}
{230}{}{E' cosi' piacevole.}
{231}{}{Uhhh...}
{232}{}{[risatina]}
{233}{}{Ehi...}
{300}{}{Ahhh, chi cazzo ha ucciso Tubby?}
{301}{}{Cosa cazzo e' successo a Tubby?}
{302}{}{Oh merda, Tubby e'...}
{303}{}{Ahhh...}
{304}{}{Comunque non mi piaceva quello stronzo.}
{305}{}{Flick e' morto? Cazzo.}
{306}{}{Cos'e' successo a Flick?}
{307}{}{Flick...}
{310}{}{Ehi Tubby, uhhh, ho bisogno di aiuto.}
{311}{}{EHI TUBBY!}
{312}{}{Salve.}
{313}{}{Ehi!}
{314}{}{Ehi Flick, uhhh, ho bisogno di aiuto.}
{315}{}{EHI FLICK!}
{320}{}{Ehi Tubby, mi puoi servire? I soldi ce li ho.}
{321}{}{Ummm, Tubby, ho qui un po' di soldi.}
{322}{}{Uhhh...}
{323}{}{Ho bisogno di una aggiustatina.}
{324}{}{Ehi, Flick; mi puoi servire? I soldi ce li ho.}
{325}{}{Ummm, Flick, ho qui un po' di soldi.}
{330}{}{Uhhh... Grazie ancora, Tubby.}
{331}{}{Sei un amico, Tubby.}
{332}{}{Lo prometto. Domani smetto.}
{333}{}{Sei un amico.}
{334}{}{Uhhh... Grazie ancora, Flick.}
{335}{}{Sei un amico, Flick.}
