# examines
{100}{}{Vedi un robusto schiavista di mezz'eta'.}
{101}{}{Vedi uno schiavista con una profonda cicatrice sul volto.}
{102}{}{Vedi uno schiavista piuttosto ben piantato.}

{150}{}{Ecco uno schiavista che sembra amare il suo lavoro.}
{151}{}{Questo schiavista sembra essere molto forte, ma non molto sveglio.}
{152}{}{Questo schiavista sembra essere ben armato, come gli altri.}

# 1. CF: Hostile Not Done - no kills
{225}{}{Prendiamoli vivi.}
{226}{}{Uccidete solo quelli ostili.}
{227}{}{Facci starda; siamo proprio dietro di te.}
{228}{}{Fate fuori solo gli ostili - gli altri sono la nostra paga.}
{229}{}{Sono pronto per spaccare qualche testa.}
{230}{}{Dove si sono cacciati? Li vedete?} ###???Where they at

# 2. CF: Hostile Not Done - have kills
{235}{}{Non e' ancora il momento di andarsene.}
{236}{}{Abbattete gli ultimi ostili.}
{237}{}{Lasciate perdere gli inermi. Fate fuori gli altri.}
{238}{}{Dobbiamo ancora portare a termine il massacro.}

# 3. CF: Done with run - Poor
{245}{}{Questo raid e' stato terribile.}
{246}{}{Avremmo quasi fatto meglio a non venire. Abbiamo fatto schifo.}
{247}{}{La prossima volta ammazza solo quelli ostili. Non e' tutto pizza e fichi.}
{248}{}{Metzger si incazzera' non poco.}

# 4. CF: Done with run - Average
{255}{}{Non male -- ma la prossima volta lascia stare quelli disarmati se vuoi essere pagato.}
{256}{}{Non male. Questo raid ci ha fruttato qualche bello schiavo.}
{257}{}{Ho visto raid migliori, ma almeno saremo pagati.}

# 5. CF: Done with run - Good
{265}{}{Ehi, ci e' andata piuttosto bene. Li abbiamo quasi presi tutti.}
{266}{}{Grazie dell'aiuto.}
{267}{}{Un bel lavoretto. La paga per questo raid non sara' male.}
{268}{}{E' stato divertente e la paga non dovrebbe essere male.}

# 6. CF: Done with run - Perfect
{275}{}{Siamo stati grandi. Metzger fara' meglio a darci un grosso extra.}
{276}{}{Un lavoro perfetto! Mi ubriachero' fino a vomitare l'anima, stanotte.}
{277}{}{Un fottuto 10 e lode. Siamo stati grandi.}
{278}{}{Cosi' si fa!}

# 7. BF: Hostile Not Done - no kills
{285}{}{Dove sono finiti?}
{286}{}{Mi prudono le mani...}
{287}{}{Scommetto che stavolta ne ammazzero' piu' di te.}
{288}{}{Qui, micio, micio, micio.}

# 8. BF: Hostile Not Done - have kills
{295}{}{Siete tutti morti; ma ancora non lo sapete.}
{296}{}{Non potete sfuggirci!}
{297}{}{Uscite fuori, o vi spappolero' le vostre fottute teste.}
{298}{}{Ah, molto bene! Dove sono finiti gli altri?}

# 9. BF: Done with run - Poor
{305}{}{Merda.}
{306}{}{Che schifo.}
{307}{}{Al diavolo.}
{308}{}{Sara' meglio che non succeda piu'.}
{309}{}{Cazzo... e io che stanotte volevo andare a bere.}
{310}{}{Andiamocene da qui. Che fottuto disastro di merda.}

# 10. BF: Done with run - Average
{320}{}{Non male.}
{321}{}{Speriamo di averne presi abbastanza. Ho bisogno di rimpinguare la mia riserva di Jet.}
{322}{}{Andiamo.}
{323}{}{Ho visto raid migliori, ma i soldi sono soldi.}
{324}{}{A Metzger dovrebbero bastare.}

# 11. BF: Done with run - Good
{325}{}{Bene.}
{326}{}{Sbrigatevi. Ce ne andiamo.}
{327}{}{Un lavoro ben fatto.}
{328}{}{Proprio un bel carico.}
{329}{}{Andiamo. Voglio i miei soldi.}

# 12. BF: Done with run - Perfect
{335}{}{Bonus time!}
{336}{}{Grandi.}
{337}{}{Forza, metteteli in gruppo: stiamo per partire.} ###???Round them up and let's get going
{338}{}{Smettetela di cazzeggiare. Andiamo.}
{339}{}{Diavolo, questo raid e' stato grande.}