# looks
# primitive
{100}{}{Vedi un uomo grosso, dall'aspetto primitivo.}
{101}{}{Vedi un'esile donna primitiva.}

# nomads
{200}{}{Vedi un uomo dall'aspetto strano.}
{201}{}{Vedi un uomo cencioso.}
{202}{}{Vedi un uomo che indossa degli abiti laceri.}

{210}{}{Vedi una donna molto sporca.}
{211}{}{Vedi una donna piuttosto sudicia.}
{212}{}{Vedi una donna pelle e ossa.}

# 10. BF: Fleeing Primitive
{270}{}{Loro no trovare me.}
{271}{}{Noi dovere nascondere. Dovere nascondere.}
{272}{}{Perche' loro volere fare male?}
{273}{}{Me paura.}
{274}{}{Me no lotta.}
{275}{}{Me vuole vivere.}
{276}{}{No fare male famiglia.}

# 11. BF: Fleeing Nomad
{280}{}{Oh, merda!}
{281}{}{Perche' stanno facendo questo?}
{282}{}{Cosa ne sara' della mia famiglia?}
{283}{}{Non voglio morire.}
{284}{}{Non voglio diventare uno schiavo.}
{285}{}{Mi merito qualcosa di meglio.}

# 14. Fleeing Primitive
{300}{}{Ahhh!}
{301}{}{No uccidere! No uccidere!}
{302}{}{Fermare!}
{303}{}{Aiutooooo!}
{304}{}{Via!}
{305}{}{Lasciare in pace!}
{306}{}{No fare male!}
{307}{}{Noi no fare male te!}
{308}{}{Io no combattere!}

# 15. Fleeing Nomad
{350}{}{Scappate se tenete alle vostre vite!}
{351}{}{Non lasciate che vi prendano!}
{352}{}{Schiavisti! Via di qui!}
{353}{}{Qualcuno ci aiuti! Per pieta'!}
{354}{}{Scappa, Marty!}
{355}{}{Ahhh!}
{356}{}{Fermate questa follia!}
{357}{}{Non abbiamo fatto nulla! Lasciateci in pace!}
{358}{}{Riconosco quel tatuaggio!}
{359}{}{No, vi prego!}
{360}{}{Vi prego, non uccidetemi!}
{361}{}{Non combattero'; non uccidetemi!}
{362}{}{Vi prego, non voglio morire!}
{363}{}{Siete schiavisti, non e' vero? Oh mio Dio...}