# 0. Male Look - Primitive
{100}{}{Vedi un uomo enorme, dall'aspetto primitivo.}
{101}{}{Quest'uomo sembra discretamente forte e sveglio.}

# 1. Female Look - Primitive
{110}{}{Vedi una donna primitiva mingherlina.}
{111}{}{Sembra forte, nonostante la sua taglia.}

# 2. Male Look - Nomad
{120}{}{Vedi un uomo dall'aspetto strano.}
{121}{}{Sembra terribilmente magro.}

{130}{}{Vedi un uomo dall'aspetto rozzo.}
{131}{}{Questo qui sembra discretamente forte.}

{140}{}{Vedi un uomo che indossa degli abiti consunti.}
{141}{}{Dai suoi movimenti si direbbe un tipo veloce.}

# 3. Female Look - Nomad
{150}{}{Vedi una donna molto sporca.}
{151}{}{Sembra che non si sia mai fatta un bagno in vita sua.}

{160}{}{Vedi una donna abbastanza robusta.}
{161}{}{Sembrerebbe essere una forte guerriera.}

{170}{}{Vedi una donna pelle e ossa.}
{171}{}{Questa non dovrebbe dare troppi problemi.}

# 4. CF: Hostile Primitive
{200}{}{Muori!}
{201}{}{Dove essere?}
{202}{}{Me fare male te.}

# 5. CF: Hostile Nomad
{210}{}{Te la faro' pagare per questo!}
{211}{}{Dannati schiavisti!}
{212}{}{La pagherai per questo!}

# 6. CF: Fleeing Primitive
{220}{}{Lasciare noi in pace!}
{221}{}{No fare bua!}
{222}{}{Noi no fatto male te!}
{223}{}{Io no combatte!}

# 7. CF: Fleeing Nomad
{230}{}{Riconosco quel tatuaggio!}
{231}{}{No, vi prego!}
{232}{}{Vi prego, non uccidetemi!}
{233}{}{Non combattero'; non uccidetemi!}
{234}{}{Vi supplico, non voglio morire!}
{235}{}{Siete schiavisti, vero? O Dio...}

# 8. BF: Hostile Primitive
{245}{}{Silenzio! Loro vicini.}
{246}{}{Uccidere uomini cattivi.}
{247}{}{No prendere famiglia di me.}
{248}{}{Io protegge famiglia.}
{249}{}{Non dovere trovare noi.}
{250}{}{Loro cattivi persone.}

# 9. BF: Hostile Nomad
{260}{}{Gli schiavisti stanno arrivando. Fate tutti silenzio.}
{261}{}{State pronti; credo siano vicini.}
{262}{}{Non mi arrendero' senza combattere.}
{263}{}{Non ci faranno mai schiavi.}
{264}{}{Quegli schiavisti la pagheranno per questo.}
{265}{}{Nessuno schiavista prendera' la mia famiglia.}

# 10. BF: Fleeing Primitive
{270}{}{Loro no trovare me.}
{271}{}{Me deve nascondere. Me deve nascondere.}
{272}{}{Perche' loro volere fare male noi?}
{273}{}{Me spaventato.}
{274}{}{Me no combatte.}
{275}{}{Me vuole vivere.}
{276}{}{No fare male famiglia.}

# 11. BF: Fleeing Nomad
{280}{}{Oh, merda!}
{281}{}{Perche' ci fanno questo?}
{282}{}{Che ne e' della mia famiglia?}
{283}{}{Non voglio morire.}
{284}{}{Non voglio diventare uno schiavo.}
{285}{}{Mi merito una vita migliore.}

# 12. Combat Float: Hostile Primitive
{290}{}{Tu morire ora!}
{291}{}{Me uccide!}
{292}{}{Tu no fare male famiglia!}
{293}{}{Tu no prendere famiglia!}
{294}{}{Io proteggere!}
{295}{}{Io fare male te!}
{296}{}{Tu pagare!}

# 13. Combat Float: Hostile Nomad
{300}{}{Non prenderai la mia famiglia, schiavista!}
{301}{}{Muori, feccia schiavista!}
{302}{}{La pagherai, bastardo!}
{303}{}{Combattero' fino alla morte per la mia famiglia!}
{304}{}{Non la farai franca!}
{305}{}{Non te ne andrai da qui con i miei amici!}

# 14. Combat Float: Fleeing Primitive
{310}{}{Ahhh!}
{311}{}{No uccidere! No uccidere!}
{312}{}{Basta!}
{313}{}{Aiutoooooo!}
{314}{}{Scappare!}
{315}{}{No fare questo!}

# 15. Combat Float: Fleeing Nomad
{320}{}{Scappate, se ci tenete alla pelle!}
{321}{}{Non lasciate che vi catturino!}
{322}{}{Schiavisti! Scappate!}
{323}{}{Qualcuno ci aiuti! Vi prego!}
{324}{}{Scappa, Marty!}
{325}{}{Ahhh!}
{326}{}{Fermate questa follia!}
{327}{}{Non abbiamo fatto nulla! Lasciateci in pace!}