# 0. Look
{100}{}{Vedi uno schiavista.}

{150}{}{Sembra prestare molta attenzione alla porta accanto a se'.}

# 1. Self Initiated Floats
{200}{}{Ehi! Via le mani da li'.}
{201}{}{Te la sei voluta!}

# 2. Open Door 1 - Self Initiated Floats
{210}{}{Problemi?}
{211}{}{Ti stai esercitando?}
{212}{}{Hmmm.}

# 3. Open Door 2 - Self Initiated Floats (From 9, 16)
{220}{}{Prego.}

# 4. Starting Node (From Where to go)
{230}{}{Ehi, come va?}
{231}{}{Ehi, adesso sei uno dei nostri, eh? Forte. Spero faremo qualche raid insieme.}
{232}{}{Allora, cosa mi vuoi chiedere?}
{233}{}{Allora, chi c'e' li' dentro?}
{234}{}{A proposito di Vic...}
{235}{}{Bene, grazie.}
{236}{}{Devo andare.}
{237}{}{Wuk?}
{238}{}{Meko veek?}
{239}{}{Ugruk.}
{240}{}{Ruru!}

# 5. Who's that? & About Vic... (From 4)
{250}{}{Il suo nome e' Vic - un mercante che ha rotto qualcosa di proprieta' del mio capo, o una roba del genere. Non ne sono troppo sicuro.}
{251}{}{Il suo nome e' Vic - un mercante che ha rotto qualcosa di proprieta' del capo, o una roba del genere. Non ne sono troppo sicuro.}
{252}{}{Oh, lui? Si', e' un mercante. Credo abbia rotto qualcosa, ma non ne sono sicuro. Perche'? Lo conosci?}
{253}{}{Oh, lui? Si', e' un mercante. Credo abbia rotto qualcosa, ma non ne sono sicuro. Perche'? Lo conosci?}
{254}{}{Si'?}
{255}{}{Perche' gli fai la guardia?}
{256}{}{Chi e' il tuo capo?}
{257}{}{Posso vederlo?}
{258}{}{Beh, sono abbastanza bravo nel riparare le cose. Forse potrei essere d'aiuto.}
{259}{}{Beh, sono abbastanza bravo nelle questioni scientifiche... forse potrei aiutare.}
{260}{}{La porta e' chiusa a chiave. Puoi aprirla?}
{261}{}{Grazie.}

# 6. Guard Will let PC see Vic. (From 18)
{275}{}{Grazie per la grana. Ti lascero' parlare con lui. Non tentare strani scherzi. Non puo' lasciare la stanza senza l'okay di Metzger.}
{276}{}{Vabbe', ti lascio parlare con lui, contento? Non tentare scherzi strani, pero'. Non puo' lasciare la stanza senza l'okay di Metzger.}
{277}{}{Okay.}

# 7. Why guarding Vic (From 5)
{285}{}{Per essere sicuro che nessuno lo disturbi mentre sta lavorando per il capo, ma soprattutto per essere sicuro che non scappi.}
{286}{}{Solo per essere sicuri che non scappi, credo. In qualche modo e' riuscito a riparare quella ricetrasmittente.}
{287}{}{Chi e' il tuo capo?}
{288}{}{Posso vederlo?}
{289}{}{Posso vederlo?}
{290}{}{Okay, grazie.}

# 8. Can I see him - Slaver (From 7)
{295}{}{Oh, certo. Non vedo perche' non potresti vederlo, adesso che sei uno schiavista.}
{296}{}{Oh, certo. Credo di si'. Non e' occupato e non va da nessuna parte, per cui credo non ci siano problemi.}
{297}{}{Bene, puoi aprirmi la porta, allora?}
{298}{}{Okay, grazie.}

# 9. Unlock door, Okay to see (From 5, 8)
{305}{}{Certamente. Non sapevo tu volessi parlargli in questo momento, scusa. Credevo tu fossi solamente curioso.}
{306}{}{Grazie.}

# 10. Who's your boss? (From 5, 7, 18)
{310}{}{Eh? Hai per caso l'abitudine di andare in giro in posti che non conosci? Questa e' la Gilda degli Schiavisti.}
{311}{}{Oh, quindi il nome del vostro capo sarebbe...}
{312}{}{Oh, e' qui che mi trovo? Credevo di essere in Kansas.}
{313}{}{Okay, grazie.}

# 11. Kansas (From 10)
{320}{}{Dove? No, non ne ho mai sentito parlare. Questo e' il Den. Non ho idea di dove sia quell'altro posto, non esco spesso. Mi dispiace.}
{321}{}{Imbecille.}
{322}{}{Uh, okay. Grazie.}

# 12. Don't know Boss? (From 10)
{330}{}{Diamine. Metzger e' il Mastro Schiavista. E' lui che manda avanti le cose, qui.}
{331}{}{Diamine, miss. Questo e' l'ultimo luogo dove una signora come voi vorrebbe trovarsi. Metzger e' il Mastro Schiavista.}
{332}{}{Oh, dov'e' il suo ufficio?}
{333}{}{Okay, ci vediamo.}

# 13. Where's his office? (From 12)
{340}{}{Subito dopo quella porta laggiu'.}
{341}{}{Grazie.}

# 14. Dumb Exit (From 4, 15, 20)
{350}{}{Scusa, non capisco.}
{351}{}{Hmph.}

# 15. Dumb Vic ? (From 4)
{360}{}{Mi spiace, Vic non puo' ricevere visite.}
{361}{}{Si', e' Vic.}
{362}{}{Seve?}
{363}{}{Surek?}
{364}{}{Gaw.}

# 16. Dumb Can See Vic (From 15)
{370}{}{Certo, puoi vederlo.}
{371}{}{Certo, puoi vederlo. Lascia che ti apra la porta.}
{372}{}{Gazie.}

# 17. Repair or Science skills (From 5)
{380}{}{Oh, davvero? Sono sicuro che il boss lo apprezzerebbe. Basta che se ne stia buono. Non vogliamo che scappi ancora.}
{381}{}{Grazie.}

# 18. Can I see Vic? (From 5, 7)
{390}{}{No, mi dispiace. E' occupato: sta facendo un lavoro per il capo.}
{391}{}{Mi dispiace, non posso lasciarti entrare. Ordini diretti del boss.}
{392}{}{Bene, hai i soldi?}
{393}{}{Devo solo fargli un paio di domande.}
{394}{}{Oh, dai. Lasciami parlare con lui, faro' in fretta.}
{395}{}{Si'. Ecco.}
{396}{}{No. Tornero'.}
{397}{}{Chi e' il tuo capo?}
{398}{}{Lasciamo perdere. Ci vediamo.}

# 19. See Vic is Never (From )
{410}{}{Smettila di rompere. Va' a parlare con Metzger. E' lui il boss.}
{411}{}{Lasciami in pace! Hai dei problemi o cosa?}
{412}{}{Ho detto: parla con Metzger!}
{413}{}{Okay, va bene! Puoi parlare con lui, ma solo questo! Non puo' mettere piede fuori dalla sua stanza. Hai capito? Adesso smamma!}
{414}{}{Okay.}
{415}{}{Grazie!}

# 20. Wuk? (From 4)
{430}{}{Si', parla con Metzger. Sicuramente ha del lavoro da farti fare. Mi pare abbia detto che gli serviva un altro uomo.}
{431}{}{Si', parla con Metzger. Sicuramente ha del lavoro da farti fare. Mi pare abbia detto che gli serviva un altro uomo... ma credo vada bene anche tu.}
{432}{}{Parla con Metzger.}
{433}{}{Ruru?}
{434}{}{Uh?}
{435}{}{Oh.}

# 21. Hostile (From Where to go)
{450}{}{Prendetelo, ragazzi.}
{451}{}{Prendetela, ragazzi.}

# 22. Just a few questions. (From 18)
{460}{}{E' occupato.}
{461}{}{Ti prego, non lascera' la stanza. Prometto.}
{462}{}{Non possiamo metterci d'accordo - finanziariamente, magari?}
{463}{}{Okay, ci vediamo.}

# 23. Bribe 1 (From 22)
{470}{}{Beh, uh... non saprei. Credo non ci sia niente di male se gli parli solamente. 300$ e ti lascero' entrare.}
{471}{}{Sei matto. E' troppo!}
{472}{}{Fottiti, amico!}
{473}{}{Certo.}
{474}{}{Mi dispiace, non posso permettermelo.}

# 24. Fine. (From 22)
{480}{}{Okay. Per quel che mi frega...} ###???see if I care
{481}{}{Okay.}
{482}{}{Bene.}

# 25. No. (From 23)
{490}{}{No, mi dispiace.}
{491}{}{Ho detto no. Adesso sparisci. Devi parlare con Metzger.}
{492}{}{Okay.}

# 26. Vic Free (From Where to go)
{500}{}{E' un peccato che tu non ti sia unito a noi.}
{501}{}{Dovresti entrare nella nostra gilda.}
{502}{}{Faccio solo la guardia.}
{503}{}{Spero che Vic ti sia utile.}
{504}{}{Sara' bene che Vic lavori bene per te.}
{505}{}{Magari ci becchiamo durante un raid.}
{506}{}{Come va?}
{507}{}{Ciao.}
