# 0. Look
{100}{}{Vedi una bacheca degli annunci.}

{150}{}{Sembrano esserci un po' di messaggi affissi.}

# 1. Main Page
{200}{}{Bacheca del Den: Sponsorizzata dal Casino' Bar di Rebecca, il miglior liquore del Den. }
{201}{}{Bacheca del Den: Sponsorizzata dal Casino' Bar di Rebecca...}
{202}{}{[Qualcuno ha scarabocchiato qualcosa su di un lato di questo annuncio.]}
{203}{}{[Noti che una parte di questo annuncio e' stata strappata via.]}
{204}{}{Gilda degli Schiavisti}
{205}{}{Bar & Gioco d'Azzardo}
{206}{}{Ristoranti}
{207}{}{Negozi}

# 2. Slaver's Guild
{225}{}{La Gilda degli Schiavisti e' la migliore, nonche' unica, fornitrice di schiavi delle Lande.}

# 3. Slaver's - Continue
{250}{}{Per opportunita' di impiego e compravendite di schiavi, rivolgetevi a Metzger, il Mastro Schiavista.}

# 4. Slaver's - Directions
{275}{}{La Gilda degli Schiavisti si trova nella zona est della citta', subito dopo i locali di Becky e Frankie.}

# 5. Slaver's - Not selling
{300}{}{A causa dell'aumentata domanda, al momento non si vendono schiavi al pubblico.}

# 6. Bars and Gambling
{325}{}{[Nell'elenco ci sono due nomi.]}

# 7. Becky's Casino Bar
{350}{}{Il Casino' Bar di Rebecca ha sia tavoli da gioco sia bevande a prezzi stracciati.}

# 8. Becky's Directions.
{375}{}{Siamo situati pochi passi a est di questa bacheca. Siamo il primo edificio sulla sinistra quando entrate in citta'. Venite a farci visita!}

# 9. Frankie's Message
{400}{}{Becky e' una putana e il suo licuore e' anaquatto! E' una inbroliona e una buggiarda! [La scritta e' a malapena leggibile.]}
{401}{}{[Il messaggio che era qui e' stato strappato con cura.]}

# 10. Dumb Board
{425}{}{Parole parole... vicino... parole... Bar... parole... nel Den.}
{426}{}{Trovi tutto molto confuso e la testa comincia a farti male.}

# 11. Frankie's
{450}{}{Frankie gestisce un bar, un albergo e affari di "piacere" nella zona est della citta'.}

# 12. Dining
{475}{}{Quello di Mama e' l'unico ristorante del Den. Si trova nella zona est della citta', subito a sud della Gilda degli Schiavisti.}

# 13. Becky Dead
{500}{}{[Sembra che qualcuno abbia cercato di incendiarlo. Non riesci a leggere nessuno degli annunci.]}

# 14. Shops
{525}{}{[Qui ci sono tre annunci.]}

# 15. Tubby's
{550}{}{Tubby vende ogni tipo d'oggetto, ma soprattutto droghe e munizioni.}

# 16. Tubby's Directions
{575}{}{Potete trovare Tubby nell'edificio a ovest di questa bacheca. E' la prima casa alla vostra destra quando entrate in citta'.}

# 17. Flick
{600}{}{Flick vende vari oggetti nel suo 'ufficio', nell'edificio residenziale subito a sud di qui e subito a sud del Casino' Bar di Rebecca.} ###???sells various items out of his 'office' in the residential building

# 18. Smitty
{625}{}{Smitty e' il meccanico del posto. Talvolta ha delle cose da vendere.}

# 19. Smitty Directions
{650}{}{Smitty si trova nella discarica nell'angolo sudovest della citta'.}

# MENU OPTIONS
{1000}{}{Continua}
{1010}{}{Indicazioni:}
{1020}{}{Esci}
{1030}{}{Flick}
{1040}{}{Frankie}
{1050}{}{Casino' Bar di Rebecca}
{1060}{}{Ritorna alla Pagina Principale}
{1070}{}{Smitty}
{1080}{}{Nota Speciale:}
{1090}{}{Tubby}
