{100}{}{Vedi un bandito.} #bandit
{101}{}{Vedi un razziatore.} #marauder
{102}{}{Vedi un ladro.} #robber
{103}{}{Vedi un rapinatore.} #highwayman
{104}{}{Vedi un furfante.} #rogue

{200}{}{Arrendetevi!}
{201}{}{O la borsa o la vita.}
{202}{}{Questa e' una rapina.}
{203}{}{Datemi tutte le cose di valore.}
{204}{}{Non muovetevi! Questa e' una rapina.}
{205}{}{Mani in alto.}
{206}{}{Ripuliteli.}
{207}{}{Niente panico; sara' tutto finito nel giro di un minuto.}
{208}{}{Vediamo un po' quelle mani.}
{209}{}{Copritemi, compagni.}

{210}{}{Non rendete tutto piu' difficile.}
{211}{}{Consegnate il bottino.}
{212}{}{Prendeteli, ragazzi.}
{213}{}{Uccideteli tutti.}
{214}{}{Vi prometto che la vostra morte sara' rapida.}
{215}{}{Piu' in alto, quelle mani!}
{216}{}{Non muovetevi.}
