{100}{}{Vedi un uomo magro e abbronzato.}
{200}{}{Vedi una donna magra e abbronzata.}
# male
{101}{}{Vedi un contadino.}
# female
{201}{}{Vedi una contadina.}
{102}{}{Noti che ha la classica abbronzatura da contadino.}
{202}{}{Noti che ha la classica abbronzatura da contadina.}
{103}{}{Sei arrivato appena in tempo. Se tu non fossi arrivato al momento giusto... Beh, meglio ringraziarti semplicemente per essere arrivato in tempo. Non abbiamo molto, ma ti preghiamo di accettare questo come ringraziamento per averci aiutato. [Ti da' qualcosa.]}
{104}{}{Grazie.}
{105}{}{Ug}
{106}{}{Grazie ancora per averci aiutato.}
{107}{}{}
{108}{}{}
{109}{}{Tieni le mani dove possa vederle. Stiamo stati martoriati dai banditi ultimamente e sospetto che tu possa essere uno di loro. Che cosa vuoi?}
{110}{}{Vorrei solo comprare delle provviste.}
{111}{}{Ero solo di passaggio. Me ne vado subito.}
{112}{}{Ug.}
{113}{}{Beh, credo che non ci siano pericoli, in questo caso. Ecco quello che ho.}
{114}{}{[Baratta]}
{115}{}{OK, adesso sparisci!}
{116}{}{[Baratta]}
{117}{}{Ho detto: sparisci!}
{118}{}{}
{119}{}{[Si rilassa un poco.] Sei troppo stupido per essere un bandito. Ti servono delle provviste?}
{120}{}{Ah hah.}
{121}{}{Eh eh.}
{122}{}{Beh, allora non abbiamo nulla da dirci. Continua per la tua strada.}
{123}{}{[FINE]}
{124}{}{Andatevene dalla mia fattoria!}
{125}{}{Nessuno prendera' la mia casa.}
{126}{}{Luridi banditi.}
{127}{}{Via dalla mia terra.}
{128}{}{Non ci si puo' fidare di nessuno, di questi tempi.}
{129}{}{Dannati banditi.}
{130}{}{Ho lavorato troppo duramente per arrendermi adesso.}
{131}{}{Magari andro' a fare il contadino da qualche altra parte.}
{132}{}{Sono solo un povero contadino.}
{133}{}{Vi prego, non bruciate la mia fattoria.}
{134}{}{Comunque non mi piaceva fare il contadino.}
{135}{}{Tornero'.}
{136}{}{Prendete mia moglie - vi prego...}