{100}{}{Vedi un uomo che indossa una Power-Armot Ver.II. Non sembra molto amichevole.}
{101}{}{Vedi Kaga in una Power Armor Ver.II.}
{102}{}{Un grosso blocco di metallo con braccia e armi.}
{103}{}{Sono stanco di inseguirti. Facciamola finita.}
{104}{}{Questa e' l'ultima volta che incontrerai Kaga.}
{105}{}{Sei un moscerino al confronto di Kaga.}
{106}{}{Non vedo l'ora di spedirti alla tua prossima vita.}
{107}{}{Sei stato un nemico valoroso.}
{108}{}{Questa parte delle lande non ha bisogno di un benefattore come te.}
{109}{}{Dopo che ti avro' ucciso, io saro' la persona piu' temuta di questa parte delle lande.}
{110}{}{Non vedo l'ora di tornare al villaggio, ad Arroyo - per ridurlo in cenere.}
{111}{}{Kaga sara' famoso per averti ucciso.}
