{100}{}{Vedi un uomo che indossa un'armatura di cuoio.}
{101}{}{Vedi Kaga.}
{102}{}{Indossa un'armatura di cuoio e ha la seccante abitudine di parlare di se' in terza persona.}
{103}{}{Qeusta sara' l'ultima volta che Kaga ti incontra.}
{104}{}{Dopo che Kaga ti avra' ucciso, egli ridurra' in cenere Arroyo.}
{105}{}{Assaggia l'ira di Kaga!}
{106}{}{Sono il grande Kaga!}
{107}{}{Tutti devono temere Kaga.}
{108}{}{Kaga prendera' la tua testa come trofeo.}
{109}{}{Arrenditi e la tua morte sara' rapida.}
{110}{}{Kaga tornera'!}
{111}{}{Non puoi uccidere il grande Kaga!}
{112}{}{Sei fortunato che Kaga abbia degli affari da sbrigare.}
{113}{}{Kaga ti incontrera' di nuovo.}
