{100}{}{Vedi un uomo vestito di pochi stracci.}
{101}{}{Vedi Kaga.}
{103}{}{Indossa dei pantaloni e sembra provenire da una tribu'.}
{104}{}{Dovrei essere io il Prescelto!}
{105}{}{Come ha osato Arroyo? Cacciare ME dalla tribu'.}
{106}{}{Avro' la mia vendetta... a tue spese!}
{107}{}{Kaga ti spedira' nella vita seguente.}
{108}{}{Ci rivedremo!}
{109}{}{Non sono mai stato sconfitto prima d'ora!}
{110}{}{Dedichero' tutto me stesso alla tua distruzione.}
