{100}{}{Vedi una strana bestia.}
{101}{}{Vedi un super mutante che sembra un po' svitato.}
{102}{}{Stop!}
{103}{}{Non un passo di piu'! Melchior il Magnifico te lo ordina!}
{104}{}{Guarda! Sono il piu' grande mago del mondo!}
{105}{}{Trema di fronte alla potenza di Melchior il Magnifico!}
{106}{}{I miei animali banchetteranno con le tue carni!}
{107}{}{Ti avevo avvertito! Attaccate, miei prediletti!}

# CREATION COMMENTS
# DEATH CLAWS
{1000}{}{SHAHOOEY!}
{1001}{}{I miei animali artigliati si prenderanno cura di te.}
{1002}{}{Attaccate, cosi artigliati!}

# FIRE GECKOS
{1010}{}{ABADABRA!}
{1011}{}{Melchior crea degli animali di fuoco per bruciare l'umano.}
{1012}{}{Bru Ciate l'U - MANO!}

# FLOATERS
{1020}{}{ZIMZOWY!}
{1021}{}{I miei animali dalle fauci taglienti ti sbraneranno!}
{1022}{}{Mangiatelo, miei cari.}

# MOLE RATS
{1030}{}{KALIMAJIGGER!}
{1031}{}{Merda! Me rimasti solo grassi topi.}
{1032}{}{Me quasi finito animali.}

# OUT
{1050}{}{Uh Oh. Me finiti cosi pelosi da muuuuu...tare.}