{100}{}{Vedi un viaggiatore.}
{101}{}{Ehila', compagno viaggiatore!}
{102}{}{Ho bisogno di informazioni. Puoi aiutarmi?}
{103}{}{Dove siete diretti?}
{104}{}{Che cosa fai?}
{105}{}{Ug.}
{106}{}{Beh... non saprei. Sono nuovo di queste parti e ho visitato solo queste zone:}
{107}{}{New Reno}
{108}{}{Vault City}
{109}{}{Redding}
{110}{}{Il Den}
{111}{}{San Francisco}
{112}{}{New California Republic}
{113}{}{Una miniera abbandonata.}
{114}{}{No, li' ci sono gia' stato. Grazie lo stesso.}
{115}{}{New Reno -- un gran bel posto dove andare. Sesso, droghe e gioco d'azzardo. Cosa si puo' chiedere di piu'? Ecco, lascia che ti mostri dove si trova.}
{116}{}{Grazie.}
{117}{}{Vault City -- una citta' di idioti. Fatti crescere un dito in piu' e ti tratteranno come un mostro. Non ci sono mai andato, ma so dov'e'.}
{118}{}{Grazie.}
{119}{}{Redding... non ne so molto, a parte che si tratta di una vecchia citta' di minatori. Si trova a nord, proprio nel mezzo di alcune tra le montagne piu' squallide che si siano mai viste.}
{120}{}{Grazie.}
{121}{}{Starei lontano dal Den, se fossi in te. E' una sorta di calamita per i disgraziati della zona. Ti mostrero' dove si trova, ma non ti consiglio di andarci.}
{122}{}{Grazie.}
{123}{}{San Francisco. Uhm...tutto quello che posso dire e' che li' le persone sono... strane. Si trova sulla costa.}
{124}{}{Grazie.}
{125}{}{La New California Republic... davvero un bel posto. Mi piacerebbe stabilirmi li', prima o poi. Pulita, bella gente e molto ben tenuta. Si trova proprio in questo punto della tua mappa.}
{126}{}{Grazie.}
{127}{}{E' cosi'! Poco fa mi sono imbattuto in una miniera abbandonata. Pensavo di fermarmi li' per un giorno o due, ma sono comparsi dei lupi e ho preferito andarmene. Un vero peccato: sembra che i minatori l'abbiano abbandonata in tutta fretta. Hanno lasciato un sacco di roba. Non credo di tornarci, percio' credo non ci siano problemi se ti mostro dov'e'.}
{128}{}{Grazie.}
{129}{}{Oh... non ha molta importanza. Semplicemente, un giorno ho deciso di viaggiare e... beh, eccomi qua.}
{130}{}{Forse puoi aiutarmi. Ho bisogno di informazioni.}
{131}{}{Che cosa fai?}
{132}{}{E' stato bello parlare con te.}
{133}{}{Faccio dei lavoretti qua e la' per vivere. Ma di solito viaggio e basta.}
{134}{}{Forse puoi aiutarmi. Ho bisogno di informazioni.}
{135}{}{Dove sei diretto?}
{136}{}{E' stato bello parlare con te.}
{137}{}{Adesso devo proprio andare. E' stato bello parlare con te.}
{138}{}{Forse ci incontreremo ancora.}
{139}{}{Vorrei arrivare alla prossima citta' prima che cali la notte. Farei meglio ad andare.}
{140}{}{Vado.}
{141}{}{Imboscata!}
{142}{}{Non ci si puo' fidare di nessuno, di questi tempi.}
{143}{}{Hai infranto il codice del viaggiatore.}
{144}{}{E' ora di andare.}
{145}{}{Ho abusato della tua ospitalita'.}
{146}{}{Devo lasciarti.}
{150}{}{Grazie. Ho bisogno di informazioni su altri posti.}
