{100}{}{Vedi uno Shi con uno sguardo torvo.}
{101}{}{Vedi il Dr. Jing Tie Gahng.}
{102}{}{Vedi uno Shi con un camice da laboratorio.}
{103}{}{Chi sei? Cosa vuoi?}
{104}{}{Cosa?}
{105}{}{Chi sei TU?}
{106}{}{Io sono }
{107}{}{Non sono affari tuoi.}
{108}{}{Niente. Me ne stavo andando.}
{109}{}{Non puoi essere uno dei nostri se sei un imbecille. Sparisci subito, prima che chiami le guardie.}
{110}{}{Non riesci proprio a capire quello che ti sto dicendo, vero? Forse le guardie ti potranno aiutare. Guardie! Un intruso!}
{111}{}{[FATTO]}
{112}{}{Io sono Jing Tie Gahng. Sono a capo del laboratorio chimico del Palazzo d'Acciaio... e tu stai interrompendo un lavoro importante. Sei pregato di andartene. ADESSO - prima che chiami le guardie.}
{113}{}{Fa' pure e chiamale, vecchio.}
{114}{}{Va bene, va bene. Me ne vado.}
{115}{}{Bene,}
{116}{}{Si'. Sono qui per ottenere del carburante per la petroliera Poseidon Oil.}
{117}{}{Mi piacerebbe sapere cosa fate qui.}
{118}{}{Sono qui per ottenere del carburante per gli Hubologisti.}
{119}{}{No. Me ne stavo giusto andando.}
{120}{}{Ahh, ma vedi, questi SONO affari miei. Questo e' il mio laboratorio. Adesso vedi di farti gli affari tuoi.}
{121}{}{Sono qui per ottenere del carburante per la petroliera Poseidon Oil.}
{122}{}{Mi piacerebbe sapere cosa fate qui.}
{123}{}{Sono qui per ottenere del carburante per gli Hubologisti.}
{124}{}{No. Me ne stavo giusto andando.}
{125}{}{Vuoi del carburante per la petroliera? E io voglio una Power-Armor rinforzata. So che un Hubologista, un tipo di nome Crocket, conosce un processo attraverso il quale e' possibile potenziare una Power-Armor standard. Procurami un'armatura di questo tipo e io trasferiro' il carburante per te.}
{126}{}{Lo faro'.}
{127}{}{Non posso promettere nulla.}
{128}{}{Ne ho una proprio qui.}
{129}{}{Creo composti e dispositivi per il consigliere dell'Imperatore, Ken Lee. Attualmente sto studiando dei derivati di carburante e alcuni polimeri in grado di sopportare attacchi massicci. Ma naturalmente questo non ti interessa, dato che il tutto e' ancora, per la maggior parte, su un piano teorico.}
{130}{}{In realta' mi interessa. Vorrei del carburante per la petroliera Poseidon Oil.}
{131}{}{Scommetto che interesserebbe molto agli Hubologisti. Vogliono del carburante.}
{132}{}{No, non ancora. Ma tornero'.}
{133}{}{Vogliono del carburante? Davvero? Beh, sebbene siano cosi' irritanti, anche loro potrebbero tornare utili. Ho sentito dire che hanno sviluppato un processo attraverso il quale riescono a rendere una Power-Armor ancora piu' impenetrabile. Se potenzieranno un'armatura di questo tipo per me, io inviero' il carburante al condotto. Immagino sia per la loro astronave-giocattolo. E' il tipo chiamato Crocket, quello con il quale devi parlare.}
{134}{}{Lo faro'.}
{135}{}{Non posso promettere nulla.}
{136}{}{Ne ho una proprio qui.}
{137}{}{Anche se volessi aiutarti, non potrei farlo. Le nostre riserve di carburante sono state prosciugate. Forse faresti meglio ad andare a chiedere aiuto agli Hubologisti. Addio.}
{138}{}{Oh. Beh, e' tutto, allora.}
{139}{}{Questo sara' piuttosto difficile. La nostra scorta di carburante e' gia' sparita. Anche se volessi aiutare gli Hubologisti, e si da' il caso che io non voglia farlo, non potrei. Buona giornata.}
{140}{}{Okay. Ciao.}
{141}{}{Bene. Allora lasciami tornare a quello che stavo facendo.}
{142}{}{[FATTO]}
{143}{}{Non puoi farlo? Allora non posso venderti il carburante. Adesso vattene. Sono occupato.}
{144}{}{[FATTO]}
{145}{}{Hai una Power-Armor rinforzata? Magnifico! In che modo vuoi essere pagato?}
{146}{}{Indirizza il carburante verso i serbatoi degli Hubologisti.}
{147}{}{Indirizza il carburante verso la petroliera Poseidon Oil.}
{148}{}{Cosa ne diresti di un po' di soldi? Credo che }
{149}{}{Ho deciso che preferisco tenermela.}
{150}{}{Consideralo fatto. Eseguiro' le operazioni necessarie a breve. Adesso, se vuoi scusarmi, devo tornare al mio lavoro.}
{151}{}{Grazie. Ciao.}
{152}{}{Cosi' tanto? Ah! Tuttavia, per un'armatura cosi' potente da studiare... molto bene. Ecco i tuoi soldi.}
{153}{}{Grazie. Addio.}
{154}{}{Vuoi tenertela? Molto bene. Se dovessi cambiare idea, fammelo sapere.}
{155}{}{Lo faro'. Arrivederci.}
{156}{}{Credici. Addio.}
{157}{}{Guardie! Guardie! L'intruso e' tornato! Uccidetelo! }
{158}{}{Hai parlato con questo Hubologista che si fa chiamare Crocket? Hai ottenuto l'armatura?}
{159}{}{No, non ancora.}
{160}{}{E allora perche' continui a tornare qui a disturbarmi?}
{161}{}{Perche' ho delle domande.}
{162}{}{Non ne ho idea. Arrivederci.}
{163}{}{Non forzare la mia pazienza.}
{164}{}{Cosa vuoi?}
{165}{}{Di che cosa ti occupi?}
{166}{}{Sono qui per ottenere del carburante per la petroliera Poseidon Oil.}
{167}{}{Sono qui per ottenere del carburante per gli Hubologisti.}
{168}{}{Niente. Scusa.}
{169}{}{Adesso siamo completamente a secco. Non posso piu' aiutarti. Sono troppo impegnato con questa armatura. Buona giornata.}
{170}{}{Addio.}
{171}{}{. Sto solo dando un'occhiata in giro.}
{172}{}{, sei qui per qualcosa in particolare?}
{173}{}{ non sarebbero male.}
{174}{}{Ho tutto quel che mi serve. Parla con Wong se proprio devi.}
