{100}{}{Vedi uno Shi basso e paffuto.}
{101}{}{Vedi il dottor Wong Yi Tze.}
{102}{}{Vedi uno Shi basso e paffuto.}
{103}{}{Posso aiutarla in qualche modo?}
{104}{}{Daghi nu?}
{105}{}{Chi tu?}
{106}{}{Mi hanno detto che lei ha la milza di qualcuno.}
{107}{}{Chi e' lei?}
{108}{}{Di che cosa si occupa?}
{109}{}{No, grazie. E' tutto.}
{110}{}{Devo confessarle che non parlo la sua lingua. Forse dovrebbe parlare con Ken Lee, che conosce molte lingue.}
{111}{}{Aagh!}
{112}{}{Io sono il Dr. Wong. Sono il capo scienziato di questo insediamento.}
{113}{}{Altre domande, per cortesia.}
{114}{}{Grazie. Arrivederci.}
{115}{}{Io soprintendo agli esperimenti scientifici che vengono qui concepiti e realizzati. Sono anche il responsabile della rete informatica.}
{116}{}{Che cosa state progettando?}
{117}{}{Come si fa ad accedere alla rete informatica?}
{118}{}{Ho delle altre domande.}
{119}{}{Capisco. Arrivederci.}
{120}{}{Ah, ma se io le rivelassi i nostri progetti, tutti li conoscerebbero. Mi dispiace, ma i nostri progetti sono segreti, per il momento.}
{121}{}{D'accordo, d'accordo. Ho delle altre domande.}
{122}{}{Grazie. Arrivederci.}
{123}{}{Cosa ne diresti se ti piantassi una pistola nel naso e ti obbligassi a rivelarmeli?}
{124}{}{Beh, per farlo, una persona dovrebbe scoprire o come violare il sistema o come farsi amico uno dei miei sottoposti. Sto scherzando, ovviamente, a proposito di violare il sistema - se lei tentasse di farlo, manderei qualcuno ad ucciderla. [Sorride per indicare che non sta minacciando.]}
{125}{}{Davvero mi farebbe uccidere?}
{126}{}{Dunque lei non porrebbe nessuna reale opposizione se io tentassi di accedere al computer?}
{127}{}{Ho delle altre domande.}
{128}{}{Certo che lo farei. Arrivederci.}
{129}{}{A quel punto io dovrei considerarla come una minaccia e dovrei avvertirla che un tale comportamento potrebbe essere dannoso per la sua salute.}
{130}{}{Facciamo una prova.}
{131}{}{Stavo solo scherzando. Ho delle altre domande.}
{132}{}{[Sorride] Dobbiamo difendere il nostro onore, straniero.}
{133}{}{Err, giusto. Dunque lei non porrebbe nessuna reale opposizione se io tentassi di accedere al computer?}
{134}{}{Giussssto. Ho delle altre domande.}
{135}{}{Posso immaginarlo. Addio.}
{136}{}{Solo se lei riuscisse a convincere uno dei miei sottoposti a farlo. Ma io di certo non lo farei.}
{137}{}{E se ficcassi una pistola nel tuo naso?}
{138}{}{Ottimo. Beh, ho delle altre domande.}
{139}{}{Hmm. Capisco. Beh, addio.}
{140}{}{Ahh, si'! E' vero. La preparero' con un contorno di fave e un buon Chianti.}
{141}{}{Ce l'ha ancora? Bene. Chip la rivuole.}
{142}{}{Quella e' una milza umana, pazzo bastardo!}
{143}{}{Lei lo sa che con quel vino si dovrebbe servire il fegato, e non la milza, non e' vero?}
{144}{}{Quella e' una milza umana, lo sa?}
{145}{}{Chi e' questo Chip? Questa milza adesso e' mia, e me la mangero' per cena.}
{146}{}{Chip e' il proprietario originale della milza. Era ubriaco e l'ha venduta a Lao Chou.}
{147}{}{Gli serve per sopravvivere, sa com'e'... Viene dall'interno del suo corpo.}
{148}{}{Forse allora farei meglio ad ucciderla.}
{149}{}{Gli affari sono affari. Non puo' averla. Mi dispiace, ma abbiamo fatto una transazione regolare e non possiamo dichiararla nulla solo perche' questo Chip se n'e' pentito.}
{150}{}{[AVANTI]}
{151}{}{E' una milza umana? Lao Chou non me l'aveva detto!}
{152}{}{Tuttavia, a causa della scortesia del messaggero, credo che riterro' comunque valido l'affare. Invece di cucinarla, la usero' per i miei esperimenti.} ###??? because of the rudeness of the messenger, I believe I will hold all parties to the bargain. I will experiment on it instead
{153}{}{Dica al suo amico di venire a riprendersela entro domani e saro' ben lieto di restituirgliela. Spero solo che possiate trovare un modo per rimetterla nel suo corpo in tempo.}
{154}{}{Molto bene.}
{155}{}{Ah ah! Si', anch'io ho visto quel vecchio film. Un attimo... cosa significa? Vuole forse dire che...?}
{156}{}{Si', e' una milza umana.}
{157}{}{In realta' avrei da obiettare su questo punto. Lei stesso non ha certo dimostrato di avere un buon carattere. Proprio non so perche' io stia parlando con lei. Buona giornata.}
{158}{}{[FATTO]}
{159}{}{Aiee! Guardie! Il lao wai intruso e' qui!}
{160}{}{Ha quegli schemi tecnici da darmi?}
{161}{}{Ken Lee mi ha detto di dare questi a lei.}
{162}{}{Si'. E io cosa ottengo in cambio?}
{163}{}{No, non ancora.}
{164}{}{Parli con Ken Lee, che decidera' cosa sara' del suo futuro. Grazie. Con questi saremo in grado di verificare alcuni nostri dati. Buona giornata.} ###???and he shall discuss what happens in your future. Thank you. We shall be able to verify some of our test data with these. Good day
{165}{}{Veramente avrei delle altre domande.}
{166}{}{Addio.}
