{100}{}{Vedi un uomo che sembrerebbe proprio essere un negoziante.}
{101}{}{Vedi Lao Chou, il negoziante.}
{102}{}{Vedi un uomo in abiti comodi e funzionali.}
{103}{}{Salve! Benvenuto nel mio negozio, il Drago Volante 8.}
{104}{}{Cosa posso fare per lei?}
{105}{}{Da aggle oo!}
{106}{}{Roba!}
{107}{}{Chi sei?}
{108}{}{Vorrei dell'equipaggiamento.}
{109}{}{Vorrei delle informazioni.}
{110}{}{Arrivederci.}
{111}{}{Vuole comprare qualcosa?}
{112}{}{::fai cenno di si' con la testa::}
{113}{}{::fai cenno di no con la testa::}
{114}{}{Questo e' quello che abbiamo.}
{115}{}{[FINE]}
{116}{}{Beh, temo che questo sia tutto quello che posso fare per lei. Buona giornata.}
{117}{}{[FATTO]}
{118}{}{Io sono Lao Chou. Sono il proprietario di questo esercizio commerciale, il Dragone Volante 8, un emporio. Sono noto per la mia compravendita di... informazioni.}
{119}{}{Che tipo di informazioni?}
{120}{}{Capisco. Vorrei acquistare dell'equipaggiamento.}
{121}{}{Poche cose in questa citta' accadono senza che io lo sappia. Naturalmente, lei deve conoscere la domanda giusta da farmi, si'? Cosa le serve sapere?}
{122}{}{Sto cercando dei potenziamenti per il mio equipaggiamento.}
{123}{}{Dove posso trovare degli schemi tecnici di un vertibird?}
{124}{}{Ho bisogno di trovare del carburante per la petroliera VMP Valdez.}
{125}{}{Mi e' stato detto che mi serve un FOB per accedere al computer della Valdez.}
{126}{}{Ho bisogno di alcuni componenti per il computer del VMP Valdez.}
{127}{}{Sto cercando una milza.}
{128}{}{Mi e' stato detto che alcune macchine volanti hanno portato qui un carico di selvaggi.}
{129}{}{Nulla. Arrivederci.}
{130}{}{Parli con Crocket, giu' al campo Hubologista. E' il loro scienziato capo.}
{131}{}{Grazie. Vorrei delle altre informazioni.}
{132}{}{Grazie. Arrivederci.}
{133}{}{Provi a nord, a Navarro. C'e' una base segreta vicino alla pompa di benzina.}
{134}{}{Grazie. Vorrei delle altre informazioni.}
{135}{}{Grazie. Arrivederci.}
{136}{}{Ha provato a cercare nei vecchi Vault? Ho sentito dire che sono una vera miniera di informazioni e tecnologia degli antenati.}
{137}{}{Grazie. Vorrei delle altre informazioni.}
{138}{}{Grazie. Arrivederci.}
{139}{}{Una milza? Ah ah! Si', Chip della Valdez ha perso la sua milza durante una partita a carte, l'altro giorno. L'ho venduta al dottor Wong. Ne era affascinato.}
{140}{}{Il dr. Wong? Dove posso trovarlo?}
{141}{}{Come si fa a perdere la milza?}
{142}{}{Grazie. Vorrei delle altre informazioni.}
{143}{}{Ah, e' cosi'... Arrivederci.}
{144}{}{Il dr. Wong e' il capo scienziato del Palazzo d'Acciaio. Provi a cercarlo li'.}
{145}{}{Come si fa a perdere la milza, comunque?}
{146}{}{Grazie. Vorrei delle altre informazioni.}
{147}{}{Grazie. Arrivederci.}
{148}{}{Era ubriaco. Molto, molto ubriaco. Per tutta la notte e' rimasto fissato con la sua milza. E allora l'ha scommessa.}
{149}{}{E cosi' tu hai preso la sua MILZA?}
{150}{}{Capisco. Beh, ho delle altre domande.}
{151}{}{Si'. Era un debito. E' un uomo onorevole.}
{152}{}{Capisco. Mi servono altre informazioni.}
{153}{}{Sei un rozzo bastardo malato, non e' vero?}
{154}{}{Giusto. Arrivederci.}
{155}{}{Lei e' una persona disonorevole. Non voglio averla nel mio negozio. Torni un'altra volta.}
{156}{}{Se lo dici tu...}
{157}{}{No, non e' esatto. Arrivavano da nord e hanno sorvolato la citta', dirigendosi poi verso il mare aperto.}
{158}{}{Al di la' dell'orizzonte? Come diavolo ci arrivo laggiu'?}
{159}{}{Si', certo, hanno fatto cosi'... Dimmi dove si trovano prima che ti apra come una scatola di sardine.}
{160}{}{Beh... nessuna delle nostre barche e' in grado di coprire una simile distanza. A meno che...}
{161}{}{A meno che...?}
{162}{}{Grazie dell'"aiuto". Andro' a cercare qualcuno che mi sia davvero utile.}
{163}{}{...a meno che lei non riesca a far funzionare la vecchia petroliera giu' al porto. E' una vecchia nave, ma probabilmente puo' ancora funzionare, se ci si lavora un po'. Chieda ai punk per altre informazioni.}
{164}{}{Grazie. Vorrei delle altre informazioni.}
{165}{}{Grazie. Arrivederci.}
{166}{}{Voci dicono che gli Hubologisti sono entrati in possesso di una grande quantita' di carburante, recentemente. Provi a contrattare con loro.}
{167}{}{Grazie. Vorrei delle altre informazioni.}
{168}{}{Grazie. Arrivederci.}
{169}{}{Potrebbe provare con qualcuno degli scienziati Shi all'interno del Palazzo d'Acciaio. Forse loro potranno fornirle il carburante che le serve.}
{170}{}{Grazie. Vorrei delle altre informazioni.}
{171}{}{Grazie. Arrivederci.}
{172}{}{Tu sei un nemico della mia gente. Muori!}
{173}{}{Ha reso un grande servizio alla mia gente, assassinando AHS-9. Spero di poterle essere d'aiuto in qualche modo.}
{174}{}{Chi sei?}
{175}{}{Vorrei dell'equipaggiamento.}
{176}{}{Vorrei delle informazioni.}
{177}{}{Arrivederci.}
{178}{}{Li ha gia' consegnati agli Hubologisti. No?}
{179}{}{Oh, certo... ahem... Posso chiederle qualcos'altro?}
{180}{}{Oh, certo... Arrivederci.}
