{100}{}{Vedi un uomo che indossa un'armatura di metallo.}
{101}{}{Vedi Luke.}
{102}{}{Vedi un uomo che indossa un'armatura di metallo con uno stemma raffigurante un fulmine.}
{103}{}{Salve, }
{104}{}{. Io sono Luke, cosa posso fare per te?}
{105}{}{Come tu sapere mio nome?}
{106}{}{Come fai a conoscere il mio nome?}
{107}{}{Joshua mi ha detto che ti sei fermato al nostro ufficio del Den. Ha detto che eri come un piccolo pesce che faceva molte onde.}
{108}{}{Le voci corrono. Sei un pesciolino che fa molte onde.}
{109}{}{Cosa questo significare?}
{110}{}{Cosa vuoi dire con questo?}
{111}{}{Stai attirando l'attenzione di molte persone. Dovrai stare in guardia.}
{112}{}{Andare avanti.}
{113}{}{Va' avanti, ti seguo.}
{114}{}{Ho detto abbastanza, per adesso. Credo che dovresti tornare ad occuparti delle tue faccende.}
{115}{}{Questo essere stesso modo che Joshua me mandato via. Me deve chiedere domande.}
{116}{}{Aspettare, me deve fare domande.}
{117}{}{Questo e' lo stesso discorsetto precotto che mi ha servito Joshua. Posso farti delle domande?}
{118}{}{Aspetta, devo farti qualche domanda.}
{119}{}{Joshua ti ha concesso una domanda; io faro' lo stesso. Qual e' questa domanda?}
{120}{}{D'accordo, ti e' concesso farmi una domanda. Qual e' questa domanda?}
{121}{}{Sapere dove trovare GECK?}
{122}{}{Sapere dove trovare Vault 13?}
{123}{}{Chi diavolo essere voi?}
{124}{}{Sai dove posso trovare un GECK?}
{125}{}{Sai dove posso trovare il Vault 13?}
{126}{}{Chi diavolo siete voi?}
{127}{}{Si', credo che il Vault 13 non abbia mai usato il suo. Dovresti essere in grado di trovarne uno, laggiu'. Buona fortuna,}
{128}{}{Aspettare! Dove vault?}
{129}{}{Aspetta un secondo! Dov'e' il vault?}
{130}{}{Si', la sua posizione e' registrata nel computer del vault 15, a est di qui. Buona fortuna, }
{131}{}{.}
{132}{}{Grazie.}
{133}{}{Noi siamo la Confraternita d'Acciaio. Non ti diro' nient'altro, per adesso. Buona fortuna, }
{134}{}{Aspettare! Me serve sapere piu', ora!}
{135}{}{Aspetta, non puoi lasciare il discorso in sospeso a quel modo!}
{136}{}{Salve di nuovo. Non ho nient'altro da dirti.}
{137}{}{. Beh... Ne hai fatta di strada dal semplice membro di tribu' che eri. Dovresti fare una visita al nostro ufficio di San Francisco, quando avrai tempo. Potresti trovarlo... interessante. Adesso, se vuoi scusarmi, devo andare.}
{138}{}{Salve di nuovo. Non ho nient'altro da dirti.}
{139}{}{Aspetta...}
{140}{}{Questo e' un ufficio privato.}
{141}{}{Non c'e' niente per te, li' dentro.}
{142}{}{Questa e' proprieta' privata, gira al largo.}