{100}{}{Vedi una persona che indossa un cappello da capitano.}
{101}{}{Vedi il Capitano A. Ron Meyers.}
{102}{}{Vedi un punk in abiti consunti che indossa un cappello da capitano.}
{103}{}{Che cosa diavolo vuoi? Non parlo con nessuno, a meno che non si tratti di un mio amico o di una brava persona. Fa' qualcosa per uno dei miei compari e poi potrai parlare con me.}
{104}{}{[FATTO]}
{105}{}{Mi hanno riferito quello che hai fatto per i miei uomini. Grazie. Come posso aiutarti?}
{106}{}{Chi tu?}
{107}{}{Mi hanno detto che tu sai tutto a proposito di questa nave.}
{108}{}{Perche' ti chiamano il Capitano?}
{109}{}{Come si fa a far partire questa nave?}
{110}{}{Nulla.}
{111}{}{Io sono il Capitano. Comando questa nave. Se hai altre domande, va' a parlare con gli Shi o con Badger o con qualcun altro. Non ho tempo da perdere con te.}
{112}{}{[FATTO]}
{113}{}{Questa nave e' una petroliera Poseidon. E' stata costruita con la tecnologia sopravvissuta alla guerra. E' necessario un FOB per accedere alla stanza del computer di navigazione, ed e' dotata di un emettitore di segnali SIAN per proteggerla dalle armi Poseidon.}
{114}{}{Come fa a sapere tutto questo?}
{115}{}{Cos'e' un emettitore di segnali SIAN?}
{116}{}{Come si fa a farla partire?}
{117}{}{Grazie. Ciao.}
{118}{}{Una volta lavoravo per l'Enclave. Poi ho capito che non stavo combattendo per gli USA; lo stavo facendo per quei bastardi dei vecchi ricchi che non volevano rinunciare al loro potere. Ho disertato e adesso vivo qui, tra persone piu' oneste.}
{119}{}{Persone piu' oneste? Queste?}
{120}{}{Cos'e' l'Enclave, esattamente?}
{121}{}{Come si fa a far partire questa nave?}
{122}{}{Addio.}
{123}{}{Come si fa a far partire questa nave? Riempila con un po' di carburante - prova dagli Hubologisti o dagli Shi, dopo che ti sarai occupato delle altre cose - e premi il pulsante d'avviamento. Il computer si occupera' del resto, se funziona ancora. Si dirigera' esattamente verso la piattaforma petrolifera, e grazie all'emettitore di segnali SIAN non verrai accolto a cannonate. Devi solo fare in modo di avere tutto quel che ti serve: un FOB, un computer funzionante, e il carburante. Piuttosto facile, no? }
{124}{}{Gia'... Come fai a sapere tutte queste cose?}
{125}{}{Cosa sono un emettitore di segnali SIAN e un FOB?}
{126}{}{Quale piattaforma petrolifera?}
{127}{}{Si'. Ci vediamo.}
{128}{}{SIAN: Sistema di Identificazione Amico/Nemico. Vuol dire che questa nave e' classificata come amica: in questo modo le altre proprieta' Poseidon - tipo, ad esempio, una piattaforma petrolifera - non le spareranno addosso una volta entrata nel raggio dei loro radar. Oh, e un FOB e' una tecnologia utilizzata dall'Enclave che ti permette di aprire una porta chiusa elettronicamente. E' probabile che tu riesca a trovarne uno in una delle loro basi, o in un posto simile.}
{129}{}{Come fa a sapere tutto questo?}
{130}{}{Quale piattaforma petrolifera?}
{131}{}{Grazie. Ciao.}
{132}{}{Si'. Tra queste persone sai esattamente dove ti trovi. Non giocano sporco. L'Enclave era come un branco di iene pronte a tradirti nel giro di un attimo.}
{133}{}{Cos'e' l'Enclave, esattamente?}
{134}{}{Come mai ti sei unito a loro?}
{135}{}{L'Enclave e' cio' che rimane dei vecchi tempi. Se riesci a portare questa nave fino alla piattaforma che c'e' al largo, lo vedrai con i tuoi occhi.}
{136}{}{Come faccio a farla partire?}
{137}{}{Quale piattaforma?}
{138}{}{Semplice. Un giorno ho abbandonato la base di Navarro e mi sono diretto qui. Pensavo che questo sarebbe stato l'ultimo posto dove mi avrebbero cercato. Inoltre, l'Enclave certo non mi giudica abbastanza importante per venirmi a cercare - sono solo uno sbandato.}
{139}{}{Cos'e' l'Enclave, esattamente?}
{140}{}{Grazie. Ciao.}
{141}{}{Qui al largo c'e' una grande piattaforma petrolifera Poseidon. E' il quartier generale dell'Enclave}
{142}{}{Come fa a sapere tutto questo?}
{143}{}{Che cos'altro succede sulla piattaforma?}
{144}{}{Grazie. Ciao.}
{145}{}{Le voci corrono.}
{146}{}{Capisco. Cos'altro succede giu' alla piattaforma?}
{147}{}{Capisco. Arrivederci.}
{148}{}{Non ne ho idea. Ero un tecnico di Navarro, non un operatore della piattaforma. Parlavamo con loro attraverso le linee di comunicazione, e questo e' tutto.}
{149}{}{Capisco. Com'e' che faccio a far partire questa nave?}
{150}{}{Grazie. Ciao.}
{151}{}{Hai fatto un grave errore a metterti contro il Capitano e i suoi amici...}
{152}{}{Come si fa a far partire questa nave? Beh, vedo che le hai gia' fatto il pieno. Quando ti sarai occupato di tutto il resto, basta che tu prema il pulsante d'avviamento. Il computer fara' il resto, se funziona ancora. Si dirigera' esattamente verso la piattaforma petrolifera, e grazie all'emettitore di segnali SIAN non verrai accolto a cannonate. Devi solo fare in modo di avere tutto quel che ti serve: un FOB, un computer funzionante, e il carburante. Piuttosto facile, no? }
{153}{}{Ah, certo. Devi anche mettere in funzione il computer di navigazione. Scommetto che troverai il pezzo che ti serve in uno dei vecchi vault.}
{154}{}{Mi fa piacere rivederti. Che cosa ti serve?}
{155}{}{, and unless I miss my bet, that's where your friends are, too.}
{156}{}{.}
