{100}{}{Vedi un terminale di computer.}
{101}{}{Vedi la postazione di Biologia.}
{102}{}{Vedi un terminale di computer funzionante.}
{103}{}{Benvenuti. Prego confermare identita'.}
{104}{}{[Oooh! Guarda che belle lucine colorate!]}
{105}{}{::prova ad indovinare la password::}
{106}{}{INTLVR-Dnky-Pnch-98790}
{107}{}{::viola il sistema di sicurezza del computer::}
{108}{}{Esci}
{109}{}{Dati da trovare: -Programma Botanico- -Programma Genetico- -Programma Xeno-}
{110}{}{Programma Botanico.}
{111}{}{Programma Genetico.}
{112}{}{Programma Xeno.}
{113}{}{Note Recenti sul Personale.}
{114}{}{Disattiva postazione.}
{115}{}{Password non corretta. Siete pregati di rivolgervi all'amministratore di sistema. Arrivederci.}
{116}{}{::viola il sistema di sicurezza del computer::}
{117}{}{::lascia perdere::}
{118}{}{Allarme intruso attivato. Spegnimento in corso. Buona giornata.}
{119}{}{-fatto-}
{120}{}{(Dopo circa venti minuti, riesci a scoprire questo: i risultati iniziali della ricerca sulla dissipazione botanica delle radiazioni si sono dimostrati non promettenti. Il Dr. Sheng elabora una forma di vita vegetale resistente alle radiazioni - seguono spiacevoli effetti collaterali. La risultante forma di vita vegetale viene giudicata troppo pericolosa. Sheng insiste nel mandare avanti il progetto e afferma la necessita' di associarlo al programma genetico.)}
{121}{}{Programma Genetico.}
{122}{}{Programma Xeno.}
{123}{}{Note recenti sul Personale.}
{124}{}{Indietro.}
{125}{}{(Dopo circa venti minuti metti insieme queste informazioni: Usando le basi del virus FEV, il Dr. Long Wang e' convinto di essere in grado di creare dei soldati mutanti. Crea quindi un siero che fornisce interessanti risultati negli esperimenti sui roditori. Il Dr. Long Wang si inietta una dose di siero e si dissolve. Il Dr. Sheng decide di non proseguire questa linea di ricerca. Con la morte del dottor Long, il Dr. Sheng diventa il responsabile capo. Sheng richiede che gli sforzi siano tutti concentrati sullo studio di forme di vita vegetale in grado di eliminare le radiazioni.)}
{126}{}{Programma Botanico.}
{127}{}{Programma Xeno.}
{128}{}{Note recenti sul Personale.}
{129}{}{Indietro.}
{131}{}{Programma Botanico.}
{132}{}{Programma Genetico.}
{133}{}{Note recenti sul Personale.}
{134}{}{Indietro.}
{136}{}{Programma Botanico.}
{137}{}{Programma Genetico.}
{138}{}{Programma Xeno.}
{139}{}{Indietro.}
{140}{}{Postazione disattivata.}
{141}{}{Attiva postazione.}
{142}{}{-vattene-}
{143}{}{[Il tuo premere a caso alcuni tasti ti fa azzeccare la password corretta... la tua fortuna e' incredibile!]}
{144}{}{-avanti-}


{145}{}{Il computer non risponde a nessun input.}
{146}{}{Non trovi nessun posto dove potresti metterlo.}
