{100}{}{Vedi un terminale di computer.}
{101}{}{Vedi un computer degli Hubologisti.}
{102}{}{Vedi un computer. Sembra essere in buono stato, sebbene sia antiquato.}
{103}{}{Questa unita' non accetta comandi. Arrivederci.}
{104}{}{[Provi di tutto, ma non sembra che tu sia in grado di violare il codice che controlla questo computer.]}
{105}{}{Esci.}
{106}{}{Benvenuti in HubLink.}
{107}{}{Siete pregati di inserire adesso i vostri comandi.}
{108}{}{Accedere al database.}
{109}{}{Accedere ai controlli.}
{110}{}{Esci.}
{111}{}{Selezionare database.}
{112}{}{Ricerca.}
{113}{}{Obiettivi futuri.}
{114}{}{Finanze.}
{115}{}{Indietro.}
{116}{}{[Dopo aver superato con fatica gli incomprensibili discorsi religiosi, scopri che gli Hubologisti hanno trovato un modo per rendere piu' robuste le Power-Armor. Hanno anche trovato un modo per calcolare traiettorie di lancio, orbite e destinazioni spaziali. In piu', pare stiano concentrando le ricerche sul controllo atmosferico.]}
{117}{}{Indietro.}
{118}{}{Esci.}
{119}{}{[Spendi quasi mezz'ora leggendo gli obiettivi che AHS-9 sta cercando di realizzare. Oltre all'illuminazione e al ricongiungimento col Padre Stellare, sembra che non si faccia nessuno scrupolo a pensare di distruggere gli umani che non sono stati con lui fin dall'inizio. E' un po' toccato.]}
{120}{}{Indietro.}
{121}{}{Esci.}
{122}{}{[La Chiesa Hubologista sembra essere enormemente facoltosa. L'approccio standard consiste nel chiedere ad ogni nuova recluta la donazione spontanea di tutte le sue proprieta' terrene alla Chiesa come segno di buona fede. Quando a qualcuno non viene chiesta la suddetta donazione, spesso vuol dire che gli Hubologisti non hanno intenzione di comportarsi onestamente. Hanno un enorme bottino nascosto da qualche parte nel deserto. Non riesci pero' a scoprire la sua posizione.]}
{123}{}{Indietro.}
{124}{}{Esci.}
{125}{}{Accesso ai controlli concesso. Selezionare operazione.}
{126}{}{Formattazione l'hard disk.}
{127}{}{Analisi del sistema.}
{128}{}{Indietro.}
{129}{}{Esci.}
{130}{}{Operazione ad accesso limitato. Consultare l'amministratore del sistema. Spegnimento in corso. Arrivederci.}
{131}{}{[FATTO]}
{132}{}{Non sembra esserci un'interfaccia per quello.}

{133}{}{HSS Quetzel: rifornita e pronta al lancio.}
{134}{}{HSS Quetzel: carburante mancante.}
{135}{}{Mainframe: operativo. Tubature: operative. Postazioni di ricerca: operative. Centro riparazioni: operativo. Telecamere: operative.}
{136}{}{Indietro.}
{137}{}{Esci.}


{250}{}{Inviare il combustibile alla petroliera Poseidon.}
{251}{}{Combustibile inviato come richiesto. Cisterne = Vuote. Chiusura programma in corso.}
{252}{}{[FATTO]}
