{100}{}{Vedi il terminale di un computer.}
{101}{}{Vedi il terminale del Computer Imperatore.}
{102}{}{Vedi un computer che come interfaccia usa un "touch screen" integrato. Incisa su di un lato c'e' la scritta "Terminale del Computer Imperatore v8.8".}
{103}{}{Benvenuti. Siete pregati di inserire la password per confermare la vostra identita'.}
{104}{}{::sbava::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{::viola il sistema di sicurezza del computer::}
{109}{}{Logout.}
{110}{}{Identita' confermata.}
{111}{}{A quale funzione desiderate accedere?}
{112}{}{Diagnostica.}
{113}{}{Database.}
{114}{}{Previsioni.}
{115}{}{Nessuna.}
{116}{}{Rivolgersi all'amministratore di sistema. Arrivederci.}
{117}{}{::viola il sistema di sicurezza del computer::}
{118}{}{::lascia perdere::}
{119}{}{Allarme intruso attivato. Spegnimento in corso. Buona giornata.}
{120}{}{[FATTO]}
{121}{}{Funzioni Diagnostiche? }
{122}{}{Scansione di rete.}
{123}{}{Formattazione disco.}
{124}{}{Controllo integrita' disco rigido.}
{125}{}{Indietro.}
{126}{}{Quale database desiderate consultare?}
{127}{}{Biologia.}
{128}{}{Chimica.}
{129}{}{Fisica.}
{130}{}{Storia.}
{131}{}{Indietro.}
{132}{}{I figli di Shi-town sono in pericolo. Probabilita' che un assassino si insinui tra di loro = 50%.}
{133}{}{Un pericolo e' giunto a Shi-town. Probabilita' che un danno sia causato ai residenti = 75%.}
{134}{}{Probabilita' che il lancio dell'astronave hubologista fallisca = 95%. Cause: Mancanza di carburante, sigillatura inadatta, incapacita' dei leader, mancanza di iniziativa.}
{135}{}{Probabilita' che il "Prescelto" riesca nella sua missione = 15%.}
{136}{}{I dati indicano che l'"Enclave" e' molto piu' potente di quanto ritenuto in precedenza; si consiglia di tenersi alla larga.}
{137}{}{Chances of submarine reappearing in this game: 0%}
{138}{}{Probabilita' che i vagabondi della petroliera si liberino, senza aiuti esterni, delle creature che infestano la loro stiva = 0%. Calcolo dei vantaggi di un eventuale intervento in corso.}
{139}{}{Dati attuali: Petroliera Poseidon Oil inadatta a navigare. Ulteriori dati richiesti.}
{140}{}{Funzione non attiva. Ulteriori dati richiesti.}
{141}{}{[AVANTI]}
{142}{}{Indietro.}
{143}{}{Postazione Biologia: Attiva}
{144}{}{Postazione Biologia: Inattiva}
{145}{}{Postazione Chimica: Attiva}
{146}{}{Postazione Chimica: Inattiva}
{147}{}{Postazione Fisica: Attiva}
{148}{}{Postazione Fisica: Inattiva}
{149}{}{Disattivare Postazione Biologia.}
{150}{}{Disattivare Postazione Chimica.}
{151}{}{Disattivare Postazione Fisica.}
{152}{}{Accedere a Postazione Biologia.}
{153}{}{Accedere a Postazione Chimica.}
{154}{}{Accedere a Postazione Fisica.}
{155}{}{Attivare Postazione Biologia.}
{156}{}{Attivare Postazione Chimica.}
{157}{}{Attivare Postazione Fisica.}
{158}{}{Indietro.}
{159}{}{Formattazione disco: Tutti i dati contenuti andranno persi. Continuare?}
{160}{}{Si'.}
{161}{}{No.}
{162}{}{L'integrita' funzionale del sistema e' del 92%. L'integrita' del nucleo protetto del Computer Imperatore e' del 100%. L'integrita' dei dati e' del 100%. Riscontrati limitati cali di potenza nel Sistema Predittivo - tempo necessario per le riparazioni: 6 giorni. Modulo Predizioni operativo al 15%.}
{163}{}{Indietro.}
{164}{}{Siete sicuri di voler formattare questa unita'? Questo e' un processo irreversibile.}
{165}{}{Si'.}
{166}{}{No.}
{167}{}{Formattazione in corso... formattazione in corso... formattazione completa. Il riavvio richiede l'installazione completa. Spegnimento in corso. Spegnimento... completato...}
{168}{}{[FATTO]}
{169}{}{Data to find: - Botany program - Genetic program - Xeno program.}
{170}{}{Programma botanico.}
{171}{}{Programma genetico.}
{172}{}{Programma Xeno.}
{173}{}{Indietro.}
{174}{}{(Dopo circa venti minuti, scopri queste informazioni: I risultati iniziali degli esperimenti sull'eliminazione botanica delle radiazioni si rivelano insoddisfacenti. Il dr. Sheng crea una forma di vita vegetale resistente alle radiazioni - seguono spiacevoli effetti collaterali. Forma di vita vegetale ritenuta troppo pericolosa. Sheng insiste nella sua linea e cerca di integrare il programma botanico con quello genetico.)}
{175}{}{Programma genetico.}
{176}{}{Programma Xeno.}
{177}{}{Indietro.}
{178}{}{(Dopo circa venti minuti riesci a mettere insieme queste informazioni: Studiando le basi del virus FEV, il dr. Long Wang si convince della possibilita' di creare soldati mutanti. Crea un siero che da' risultati interessanti negli esperimenti sui roditori. Si inietta il siero e si dissolve, diventando un ammasso di gelatina. Il dr. Sheng interrompe questa linea di ricerca. Con la morte del dr. Long, il dr. Sheng diventa capo del progetto. Sheng chiede di concentrare le ricerche sulle forme di vita vegetali in grado di eliminare le radiazioni.)}
{179}{}{Programma botanico.}
{180}{}{Programma Xeno.}
{181}{}{Indietro.}
{182}{}{"The subject on which we had hoped to establish a series of meaningful experiments has disappeared, presumed either destroyed or stolen by the Hubologists. Further inquiries have proven fruitless. Until such time as further specimens are obtained, this database will remain inoperative." - Dr. Sheng.}
{183}{}{Programma botanico.}
{184}{}{Programma genetico.}
{185}{}{Indietro.}
{186}{}{Database chimico: Carburante e derivati - Polimeri}
{187}{}{Combustibile e derivati.}
{188}{}{Polimeri.}
{189}{}{Indietro.}
{190}{}{(After sifting through the complex chemical formulae and lab notes, you come to the conclusion that the Shi have created a kind of fuel from plant extracts and sealife. Apparently, they have hooked into previously existing pipelines so they can transport fuel to a wide variety of destinations.)}
{191}{}{(Ti imbatti in una vasta serie di formule chimiche complesse e note di laboratorio. Non sei molto sicuro di cosa possano significare.)}
{192}{}{Inviare il combustibile alla petroliera Poseidon.}
{193}{}{Inviare il combustibile agli Hubologisti.}
{194}{}{Indietro.}
{195}{}{(Dopo aver superato la simbologia e le disquisizioni tecniche, scopri che gli Shi stanno lavorando a un nuovo tipo di armatura da combattimento polimerica, resistente alle fiamme e alla penetrazione. E' ancora molto lontana dall'essere completata. Trovi anche degli accenni a nuove armi e a moderne tecniche di costruzione. Apparentemente gli Shi hanno dei piani per il futuro.)}
{196}{}{Indietro.}
{197}{}{Combustibile inviato come richiesto. Cisterne = Vuote. Chiusura programma in corso.}
{198}{}{[FATTO]}
{199}{}{Combustibile inviato come richiesto. Cisterne = Vuote. Chiusura programma in corso.}
{200}{}{[FATTO]}
{201}{}{Database Fisica: Esplorazione - Teoria}
{202}{}{Exploration.}
{203}{}{Theory.}
{204}{}{Indietro.}
{205}{}{"Con la recente acquisizione degli schemi tecnici del vertibird, le possibilita' di creare una macchina volante operativa sono aumentate esponenzialmente. Riteniamo di poter avere un prototipo funzionante entro la fine dell'anno e di essere in grado di avviare la produzione di massa di questi veicoli entro due anni." -Dr. Wong}
{206}{}{::copia schemi tecnici:: Indietro.}
{207}{}{Indietro.}
{208}{}{"Stiamo ancora lavorando ad un modello funzionante di un velivolo aereo. Nessuno dei progetti da noi elaborati si e' dimostrato sicuro o aerodinamico. Se solo potessimo entrare in possesso dei documenti degli antenati..." - Dr. Wong}
{209}{}{Indietro.}
{210}{}{(Dopo aver faticosamente letto l'introduzione e la parte dedicata alla matematica, scopri che gli Shi stanno imparando a sfruttare nuovamente l'energia nucleare, sono a buon punto nella riscoperta delle teorie degli antenati sul viaggio spaziale - una vera e propria sfida agli Hubologisti - e sono prossimi ad imbrigliare l'energia del sole, del vento e del mare. Almeno, questo e' quanto ti pare dicano questi dati.)}
{211}{}{Indietro.}
{212}{}{Postazione attivata.}
{213}{}{Indietro.}
{214}{}{Il terminale del computer non sembra avere l'interfaccia adatta per quello.}
{215}{}{Il computer non sembra essere operativo.}
{216}{}{Il sistema e' stato compromesso. Gli ordini sono di attaccare!}
{217}{}{Attaccare l'intruso!}
{218}{}{E' giunto il tempo di pagare per le tue azioni, lao wai!}
{219}{}{C'e' un traditore tra le nostre fila!}
{220}{}{Geo-puntamento.}
{221}{}{Cosa desiderate localizzare?}
{222}{}{Gli abitanti del mio villaggio.}
{223}{}{Probabilita' complessive: 97% - Gli abitanti si trovano alle coordinate del complesso Enclave.}
