{100}{}{Vedi un uomo magro, dall'aspetto affabile.}
{101}{}{Vedi Chad, il carovaniere.}
{102}{}{Vedi un uomo magro, con un sorriso che pare uno scudo. Indossa abiti indefinibili e ha il tipico atteggiamento di chi sa cosa sta facendo.}
{120}{}{Ehila', amico! Cosa posso fare per te?}
{121}{}{Altre domande? Vediamo cosa posso fare per darti delle risposte.}
{122}{}{Deerk deegler!}
{123}{}{Chi tu?}
{124}{}{Marcus ha fatto delle domande sul tuo conto.}
{125}{}{There's enough evidence to arrest you for stealing money that's supposed to go to Broken Hills. You're going down.}
{126}{}{There's enough evidence to arrest you for stealing money that's supposed to go to Broken Hills. Cut me in for $1000 and I'll make sure you can flee town.}
{127}{}{Chi sei?}
{128}{}{Parlami di questo posto.}
{129}{}{Nulla. Arrivederci.}
{130}{}{Guardate un po' cos'e' sbucato fuori dalle Lande! Scusa, amico, non posso aiutarti.}
{131}{}{Aivedecci!}
{132}{}{Io sono Chad. }
{133}{}{Guarda, sono molto occupato. Per favore, va' a disturbare qualcun altro.}
{134}{}{I'm the caravan master for the city. I take care of the business on the other end of the trade routes. These days I'm focusing primarily on Gecko.}
{135}{}{D'okay!}
{136}{}{Vorrei lavorare con te.}
{137}{}{Sembra eccitante.}
{138}{}{Sembra noioso.}
{139}{}{Ho delle altre domande.}
{140}{}{Grazie. Ciao.}
{141}{}{Tell you about Broken Hills? Well... I moved here a few years back. Got a job with the Bill --
 that's the Outfitter -- and moved up to where I am now. I report to Marcus and the Bill, but I'm
 responsible for the livelihood of the town.}
{142}{}{Ho delle altre domande.}
{143}{}{Addio.}
{144}{}{Ad esempio?}
{145}{}{He suspects that you are skimming the money that's supposed to go to Broken Hills.}
{146}{}{Non proprio. Arrivederci.}
{147}{}{Guarda, non mi piace la gente che mi accusa di qualcosa di cui non so nulla. Ti suggerisco di andartene.}
{150}{}{I'm going to find out the truth. Bye.}
{156}{}{Parla con Bill. Ti aiutera' lui.}
{157}{}{Ho delle altre domande.}
{158}{}{Grazie. Ciao.}
{159}{}{Si', lo e'. Uno magari non ci pensa, ma in questo modo posso viaggiare e vedere il mondo... e mi sento come se contribuissi allo sviluppo di questa citta'. E' un bel modo di vivere.}
{160}{}{Sembra splendido. Mi piacerebbe un lavoro cosi'.}
{161}{}{In realta', mi sembra un po' noioso.}
{162}{}{Ho delle altre domande.}
{163}{}{Addio.}
{164}{}{Sicuramente piu' eccitante di quello che fai tu della tua vita, stronzo.}
{165}{}{Se lo dici tu... Ho delle altre domande.}
{166}{}{Ah ah ah ah! Certo. Ci vediamo, perdente.}
{167}{}{Un giorno la pagherai per questo, coglione.}
{168}{}{Sparisci dalla mia vista, stronzo.}
{169}{}{Quella carovana e' andata proprio a farsi benedire, amico mio. Lo stesso vale per i tuoi soldi.}
{170}{}{Hai davvero fatto un casino con quella carovana, amico mio. Dubito che riuscirai a fartene affidare un'altra da Broken Hills.}
{171}{}{Hai fatto un buon lavoro con quella carovana. Ecco i tuoi 200$.}
{172}{}{Fuori di qui. Il tuo aiuto non e' piu' desiderato.}
{173}{}{Occhi aperti.}
{174}{}{Ti copro io.}
{175}{}{Non lasciare che i bastardi ti colgano di sorpresa.}
