{100}{}{Vedi una persona che impugna un'arma potente.}
{101}{}{Vedi un membro della societa' di commercio e protezione di Broken Hills.}
{102}{}{Vedi una persona che impugna un'arma potente ed e' coperta dalla polvere della strada.}
{103}{}{Ti diro'... un altro gruppo di banditi e nel prossimo viaggio mi porto dietro della dinamite.}
{104}{}{Ci farebbe proprio comodo un po' di aiuto aggiuntivo per le carovane.}
{105}{}{Cavoli... lavorare in una pattuglia dell'Unita' mi e' davvero difficile.}
{106}{}{Poi ho visto questo selvaggio arrivare e... non importa.}
{107}{}{Se incontro un'altra "Pattuglia Arcobaleno", giuro che ammazzo qualcuno.}
{108}{}{Me lo sento, se i banditi si fanno piu' feroci e numerosi, moriremo tutti entro il prossimo anno.}
{109}{}{Da quale sperduto villaggio provieni?}
{110}{}{Che ne diresti di offrire qualcosa da bere ad un lavoratore?}
{111}{}{Quel viaggio con la carovana mi ha talmente stancanto che non ho nemmeno la forza per parlare.}
{112}{}{Se hai bisogno di qualcosa, parla con Bill, il Fornitore.}
{113}{}{Pensavo che dopo tutto questo tempo passato cercando di civilizzare le lande noi fossimo un po' piu' vicini al nostro obiettivo...}
{114}{}{Sono stufo di tutte queste beghe tra umani e mutanti. Non dovremmo dare il buon esempio?}
{115}{}{'zzo vuoi? Non vedi che sto riposando?}
{116}{}{Quand'e' che parte la prossima carovana?}
{117}{}{Pattugliamenti, pattugliamenti, pattugliamenti... non faccio altro da mattina a sera.}
{118}{}{Avrei bisogno di schiacciare un pisolino.}
{119}{}{Mi merito un aumento. E' un lavoro pericoloso, questo.}
