{100}{}{Un grosso macchinario.}
{101}{}{Il purificatore d'aria emette sordi rumori metallici. Sembra essere rotto. Forse ha bisogno di un pezzo di ricambio.}
{102}{}{Il purificatore d'aria emette un lieve sibilo. Sembrerebbe essere in funzione.}
{110}{}{Quel pezzo non puo' ripararlo.}
{120}{}{Hai riparato il purificatore d'aria.}
{125}{}{Hai distrutto il purificatore d'aria.}
{129}{}{I cospiratori non possono piu' inviare il segnale di distruzione alla spoletta dell'esplosivo. Ormai non serve piu' a nulla, percio' la butti via.}
{130}{}{E' gia stato riparato.}
{131}{}{Clunk}
{132}{}{Creak}
{133}{}{Clank}
{134}{}{Whirrrrrrrr}
