# 0. QUICK LOOK
{100}{}{Vedi un capitano mercenario.}

# 0. LOOK
{150}{}{Vedi un uomo dall'aspetto rude, vestito con un'armatura da combattimento. La sua  armatura e le sue armi sembrano ben tenute, quasi nuove.}
{151}{}{Vedi un capitano mercenario. Sta controllando la zona e accarezza la sua arma.}

# 1. FLOAT DIALOGUE: INTRUDER (WTG)
{200}{}{Beh, guardate un po' che palle di bronzo che ha, questo figlio di puttana...}
{201}{}{Contatto!}
{202}{}{Abbiamo un intruso, ragazzi!}
{203}{}{Allarme, ragazzi, abbiamo un intruso!}
{204}{}{Beh, guardate un po' chi e' venuto a farsi ammazzare…}
{205}{}{Cazzo! Qualcuno ci ha scoperto!}
{206}{}{Hai del fegato per entrare qui…}
{207}{}{Sei appena entrata nel posto *sbagliato*, troia.}
{208}{}{Beh, ne ha di fegato, la troia...}

# 2. FLOAT DIALOGUE: NORMAL (WTG)
{215}{}{Sara' meglio richiamare presto quelle squadre della morte...}
{216}{}{Credo che la squadra Bravo si trovi a pochi kilometri a sud di Vault City...stanno ancora inseguendo quella carovana.}
{217}{}{Sara' meglio che quel "Desert Cherry" si dia una regolata e in fretta... certe stronzate non funzionano da queste parti.} ###???That desert cherry better shape up soon...that sort of shit won't wash around here
{218}{}{E' quasi l'ora di mandare qualche uomo a controllare il perimetro…}
{219}{}{Se solo potessimo sabotare quei cannoni laser di Vault City…}
{220}{}{Stiamo ancora aspettando notizie da Bishop…}
{221}{}{E' passata una settimana da quando Bishop ci ha mandato un messaggero.}
{222}{}{Credo che la prossima carovana in programma sia quella da NCR a Vault City…}
{223}{}{Dobbiamo essere pronti a muoverci nel giro di pochi secondi.} #?at a moment's notice
{224}{}{Spero che i ragazzi abbiano controllato quelle trappole.}
{225}{}{Le squadre Alfa e Bravo hanno fatto rapporto?}