# 0. QUICK LOOK
{100}{}{Vedi Ombra-che-Cammina.}

# 0. LOOK
{150}{}{Vedi un uomo primitivo molto muscoloso con cicatrici nere che ricoprono la sua faccia. Ti sta fissando in silenzio.}
{151}{}{Vedi Ombra-che-Cammina. Il suo viso e' pesantemente sfregiato da tatuaggi rituali.}

# 1. CLICK ON HIM (WTG)
{200}{}{Ti guarda semplicemente in silenzio.}
{201}{}{Ti guarda in silenzio.}

# WABBITS
{300}{}{Shhh... Sono a caccia di conigli.}