{100}{}{Vedi uno dei bambini di Klamath.}
{101}{}{Vedi uno dei bambini di Klamath.}
{150}{}{Non mangiarmi!}
{151}{}{Eeeee! L'uomo nero!}
{152}{}{Il mio papa' mi ha detto che sei una persona brutta.}
{153}{}{Aieeee! Viaaaa!}
{154}{}{Mi fai paura.}
{155}{}{Smettila di guardarmi.}
{156}{}{Non mi e' permesso parlare con i selvaggi.}
{157}{}{Sei proprio uguale ai Dunton.}
{158}{}{La mia mamma dice che se faccio il cattivo tu mi mangerai.}
{159}{}{Non ho paura di te!}
{160}{}{Aiutooooo!}
{161}{}{Mi sta inseguendo!}
{162}{}{Per piacere non farmi male!}
{163}{}{Stai lontano da me!}
{164}{}{Eeeeeeeeek!}
{165}{}{Ti odio!}
{166}{}{Mammina mammina mammina!}
{167}{}{Lasciami in pace!}
{168}{}{Puzzi!}
{170}{}{Ciao.}
{171}{}{Giochiamo insieme?}
{172}{}{Ti sei davvero infilato un osso nel naso?}
{173}{}{Perche' sei cosi' buffo?}
{174}{}{La mia mamma dice che sei un uomo delle caverne.}
{175}{}{La tua tribu' ha smesso di mangiare le persone?}
{176}{}{Chi ti ha vestito in un modo cosi' buffo?}
{177}{}{Scommetto che sei piu' buono di quanto sembra.}
{178}{}{Giochiamo a ce l’hai! Ce l’hai tu.}
{179}{}{Non puzzi cosi' tanto.}
{180}{}{Hai visto il mio amico invisibile?}
{181}{}{Quando saro' vecchio come te, voglio viaggiare per il mondo.}
{182}{}{Sei un selvaggio simpatico, non sei come gli altri.}
{183}{}{Scommetto che ti sei fatto il bagno.}
{184}{}{Sei piu' sveglio di Torr.}
{185}{}{La punta della tua lancia e' molto tagliente?}
{186}{}{Voglio essere proprio come te quando saro' grande.}
{187}{}{Il mio cane adora la carne secca.}
{188}{}{Ho un bel sassolino lucido.}
{189}{}{Hai visto il mio amico invisibile?}
{190}{}{Posso unirmi alla tua tribu'?}
{191}{}{Sei carino.}
{192}{}{Sei buffo.}
{193}{}{Cosa stai indossando?}
{194}{}{Voglio andare al pascolo con i brahmin!}
{195}{}{Vieni da lontano?}
{196}{}{Weeee! Ah, ah, ah!}
{197}{}{Non andartene!}
{198}{}{Hai del cibo?}
{199}{}{Ti do fastidio?}
{200}{}{Dove stai andando?}
{201}{}{Posso venire con te?}
{202}{}{Quanti anni hai?}
{203}{}{Come ti chiami?}
{204}{}{Ti piacciono i bambini?}
{205}{}{Cos'e' quello?}
{206}{}{Giochiamo insieme?}
{207}{}{Che fai?}
{208}{}{Hai visto qualche insetto?}
{209}{}{Dove l'hai preso quello?}
{210}{}{Posso averlo?}
{211}{}{Che cosa fai?}
{212}{}{Posso correre veloce. Vuoi vedere?}
{213}{}{Guardami! Guardami!}
{214}{}{La mia mamma dice che parlo troppo.}
{215}{}{Dov'e' casa tua?}
{216}{}{Heeee! Heeee!}
{217}{}{Rimarrai qui?}
{218}{}{Hai dei bambini?}
{219}{}{Perche' sei venuto qui?}
{220}{}{A me mi piaci.}
{221}{}{A te ti piaccio?}
{222}{}{Sei sposato?}
{223}{}{Uno, due, tre... Weee!}
{1000}{}{Anziana}
{1001}{}{Fondatore}
{1002}{}{Vault Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{l'Eletto}
{1007}{}{Sciamano}
{1008}{}{Hakunin}
{1009}{}{Polvere curativa}
{1010}{}{Ponte}
{1011}{}{Mynoc}
{1100}{}{L'Anziana e' tua madre e la nostra guida.}
{1101}{}{Il nostro grande antenato che ci ha donato la conoscenza.}
{1102}{}{I primi a combattere e a vincere sul caos.}
{1103}{}{Quello sarebbe il nostro bellissimo villaggio.}
{1104}{}{That’s trading outpost a few days east of here.}
{1105}{}{Il Vault e' il paradiso.}
{1106}{}{Tu sei il Prescelto.}
{1107}{}{He heals us with his herbs and magic. He is in the north part of our village.}
{1108}{}{He heals us with his herbs and magic. He is in the north part of our village.}
{1109}{}{It is a magic powder which will heal you, but will make you sleepy.}
{1110}{}{Il Grande Ponte esce dal nostro villaggio a sud.}
{1111}{}{Lui custodisce il ponte che conduce al nostro villaggio.}
