#############################################################
#  Message File: ktgoo.msg                                  #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: March 1, 1998                                   #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Vedi: Liquido Tossico.}
{101}{}{Vedi del liquido tossico.}

#############################################################
#  The following lines are floaters for citizens            #
#############################################################

{110}{}{Ouch - questa sostanza brucia!}
{120}{}{Questi vecchi stivali di gomma impediscono a quel liquido dall'aspetto malsano di corroderti i piedi.}
{130}{}{I tuoi stivali si sono appena sciolti.}
{140}{}{I tuoi piedi cominciano a bruciare e a prudere.}
{150}{}{I tuoi piedi bruciano e prudono per un po', ma poi ti senti meglio.}