# Before Jonny Found
{100}{}{Sob-}
{101}{}{Jonny...}
{102}{}{Sniff...}
{103}{}{Mi manca mio figlio.}

# Player accepts find Jonny Seed
{110}{}{La prego... trovi Jonny.}

# After Jonny Found
{120}{}{La prego... mi riporti Jonny.}

# Jonny Returned
{121}{}{Grazie per aver ritrovato il mio Jonny.}

# looks
{150}{}{Vedi la moglie di Balthas.}
{151}{}{Vedi la moglie di Balthas. Sembra essere abbastanza turbata.}
{152}{}{Vedi la moglie di Balthas. Sembra essere di buon umore, adesso.}
