# Flee
{100}{}{Via!}
{101}{}{Aiuto!}
{102}{}{I "superficiali" ci attaccano!}
{103}{}{Lasciateci in pace.}
{104}{}{Non possiamo discuterne pacificamente?}

# Attack
{150}{}{Tornatevene da dove siete venuti.}
{151}{}{Non siete desiderati.}
{152}{}{Tutti i "superficiali" sono uguali.}
{153}{}{Non ci scapperete.}

# General Dialogue (above ground)
{200}{}{Groan!}
{201}{}{Boo!}
{202}{}{Moaaaaaaan.}
{203}{}{*Clank*}
{204}{}{*Clink*}

# General Dialogue (below ground)
{250}{}{Un tempo vivevamo nel terreno di sopra.}
{251}{}{Com'e' il terreno di sopra?}
{252}{}{E' cosi' GRANDE lassu'.}
{253}{}{Che aspetto ha il sole?}
{254}{}{Salve, "superficiale".}

# General Dialogue when Seed is completely done
{300}{}{Sapevo di potermi fidare di te.}
{301}{}{Grazie per averci aiutato.}
{302}{}{E' bello rivederti.}