#############################################################
#  Message File: ModMain.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 15, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for the map script in describing #
#  what is happening when you first enter the map.          #
#############################################################

{100}{}{Una piccola, caratteristica comunita' rurale, circondata da vasti campi con le coltivazioni morte o morenti.}

# from the vermin hunter seed
{500}{}{Pare proprio che tu li abbia uccisi tutti.}
{501}{}{Tutti cattivi morsatori morti.}

# Coin Bag Descriptions
{600}{}{Vedi un sacchetto pieno di monete.}
{601}{}{Vedi un sacchetto pieno di monete. Probabilmente qualcuno l'ha buttato nel pozzo per esprimere un desiderio.}
{610}{}{Questo e' il MIO sogno, il MIO desiderio e me lo riprendo indietro. Me li riprendo tutti!}

# KILL THEM ALL
{1000}{}{Uccideteli tutti!}
{1001}{}{A morte gli Slag!}
{1002}{}{Voglio vederli gridare!}
{1003}{}{Andiamo a prenderli!}

# fall through floor
{1100}{}{Cadi per quasi 5 metri all'interno di una grotta scarsamente illuminata. Vari strumenti agricoli giacciono ben disposti contro il muro piu' lontano.}

# blown out of hole
{1200}{}{Esci dal buco un secondo prima che l'esplosione avvenga dietro di te. Lo spostamento d'aria ti fa volare fuori.}
