# QUICK LOOK
{100}{}{Vedi un'attrice porno.}

# EXAMINES
{150}{}{Vedi una donna attraente. Sembra che stia parlando a se stessa.}
{151}{}{Sembra impegnata a memorizzare le sue battute. Di tanto in tanto si ferma, fa un "O" con la bocca e comincia a muovere la testa avanti e indietro.}
{152}{}{Vedi un'attrice porno. Ti ignora freddamente.}

# 1. [MALE, ENCLAVE IS DESTROYED]
{200}{}{Immagino che dovrei dirti "grazie per aver salvato il mondo", ma preferirei molto di piu' fare del sesso sfrenato e selvaggio con te. Ti va bene?}
{201}{}{Mi hanno detto che sei tu lo stallone che ha fatto il culo all'Enclave.}
{202}{}{Gli uomini che fanno a pezzi le enclave di governi malvagi, mi hanno sempre fatto bagnare.}
{203}{}{Mi hanno detto che i Fratelli ti stanno cercando. Vogliono fare un film ispirato alle tue avventure.}

# 2. [FEMALE, ENCLAVE IS DESTROYED]
{210}{}{Immagino che dovrei ringraziarti per aver salvato il mondo. Uh…grazie.}
{211}{}{Mi e' stato detto che sei stata tu a spaccare il culo all'Enclave. Sono impressionata.}
{212}{}{Ho sentito dire che i Fratelli ti stanno cercando. Vogliono fare un film ispirato alle tue avventure. Ehm...puoi vedere se riesci a farmi dare una parte…?}

# 3. [POWER ARMOR]
{220}{}{Potresti PER CORTESIA smetterla di andare in giro a far casino con quella roba addosso? Sto cercando di imparare la mia parte.}
{221}{}{Tornatene nel gioco di Mech dal quale sei venuto! Questo e' un GdR!}
{222}{}{Stai cercando di compensare qualcosa?}

# 4. [PORN STAR]
{230}{}{Come butta, }
{231}{}{Mi sembri in forma, }
{232}{}{Ehila', zucchero! Ti tieni in forma?}
{233}{}{La mia paga non e' ASSOLUTAMENTE adeguata.}
{234}{}{Vediamo… "Oddio"… "Dammelo…" Diamine! Qual era la battuta dopo?!}
{235}{}{D'accordo, ma qual e' la MOTIVAZIONE per girare questa scena?}
{236}{}{Vediamo…(Studia il copione)… lui entra, facciamo sesso. Ho capito.}
{237}{}{Quello che vorrei, in realta', e' fare la regista.}
{238}{}{Grazie a Dio hanno finalmente installato quella testiera imbottita.}
{239}{}{Non so proprio cosa ci vedano in LEI i Fratelli Corsican…}
{240}{}{Vorrei che se ne andasse per sempre.}
{241}{}{Rovina il mio stile.}
{242}{}{Oh certo, e' proprio una mangiatrice di uomini, una vera cannibala.}
{243}{}{Hmmpph. Spazzatura di fogna.}
{244}{}{Ha lo stesso talento di una roccia ed e' due volte piu' brutta.}

# 5. [PRIZEFIGHTER]
{250}{}{Come butta, }
{251}{}{ECCO un guaio nel quale vorrei proprio cacciarmi.}
{252}{}{Cercavi me?}
{253}{}{Perche' non vieni a trovarmi piu' spesso?}
{254}{}{Ho un vuoto che tu potresti riempire.}
{255}{}{Finalmente un vero uomo, qui dentro…}
{256}{}{Vediamo… "Oddio"… "Dammelo…" Diamine! Qual era la battuta dopo?}
{257}{}{D'accordo, ma qual e' la mia MOTIVAZIONE per girare questa scena?}
{258}{}{Vediamo…(Studia il copione)… lui entra, facciamo sesso. Ho capito.}
{259}{}{Quello che vorrei, in realta', e' fare la regista.}
{260}{}{Grazie a Dio hanno finalmente installato quella testiera imbottita.}

# 6. [MADE MAN]
{265}{}{Come butta, }
{266}{}{ECCO un guaio nel quale vorrei proprio cacciarmi.}
{267}{}{Cercavi me?}
{268}{}{Perche' non vieni a trovarmi piu' spesso?}
{269}{}{Ho un vuoto che tu potresti riempire.}
{270}{}{Finalmente un vero uomo, qui dentro…}
{271}{}{Vediamo… "Oddio"… "Dammelo…" Diamine! Qual era la battuta dopo?}
{272}{}{D'accordo, ma qual e' la mia MOTIVAZIONE per girare questa scena?}
{273}{}{Vediamo…(Studia il copione)… lui entra, facciamo sesso. Ho capito.}
{274}{}{Quello che vorrei, in realta', e' fare la regista.}
{275}{}{Grazie a Dio hanno finalmente installato quella testiera imbottita.}

# 7. [NO REP]
{280}{}{Cos'e' 'sta puzza?}
{281}{}{Perfetto. Un altro pesta-merde selvaggio.}
{282}{}{Non parlare con me.}
{283}{}{Vediamo… "Oddio"… "Dammelo…" Diamine! Qual era la battuta dopo?}
{284}{}{D'accordo, ma qual e' la mia MOTIVAZIONE per girare questa scena?}
{285}{}{Vediamo…(Studia il copione)… lui entra, facciamo sesso. Ho capito.}
{286}{}{Quello che vorrei, in realta', e' fare la regista.}
{287}{}{Grazie a Dio hanno finalmente installato quella testiera imbottita.}
{288}{}{Preferirei che tu non dicessi una parola mentre mi parli. Formula un discorso nella tua mente e poi fa' finta che io ti stia rispondendo.}
{289}{}{Chi sei?}
{290}{}{Sei una delle assistenti?}

# 8. [POWER ARMOR]
{295}{}{Non sei un po' basso per appartenere alle truppe d'assalto?}
{296}{}{Aighhhhhh! Cosa stai cercando di fare? Vuoi farmi venire un infarto?! Fuori di qui!}
{297}{}{In quale film CREDI di dover recitare? Ultimatum alla Terra? Fuori di qui!}
{298}{}{Potresti PER CORTESIA smetterla di andare in giro a far casino con quella roba addosso? Sto cercando di imparare la mia parte.}
{299}{}{Stai cercando di compensare qualcosa?}

# 9. [MALE, PORN STAR]
{305}{}{Come butta, }
{306}{}{Vuoi aiutarmi a ripassare la mia parte?}
{307}{}{Vorresti fare la doccia insieme a me, prima della prossima scena?}
{308}{}{Adoro quel lavoretto che fai con la lingua.}
{309}{}{Mi hanno dato la parte della studentessa francese della porta accanto.}
{310}{}{Nella scena 3, sei il maggiordomo o l'autista?}
{311}{}{Potresti procurarmi un po' di Jet?}
{312}{}{Queste scene mi stanno apren... er, stancando molto.} ???These shoots are stretch... er, wearing me out
{313}{}{Credo che FINALMENTE faremo una scena insieme.}
{314}{}{I miei fidanzati non sanno che lavoro qui. Non che mi interessi quello che pensano.}
{315}{}{Non ho visto i Fratelli qui in giro... hai provato in ufficio?}
{316}{}{Non mi interessa dove va messa, ma la camera deve riprendere il momento in cui verra'.}
{317}{}{Sei un uomo di passione e mistero. Un uomo di desiderio.}
{318}{}{Beh, possiamo farlo nel modo che ti e' piu' comodo, qualunque esso sia.}
{319}{}{Saro' pronta per la prossima scena solo quando mi saro' fatta una lunga doccia bollente.}
{320}{}{Sono una madre per tutti quelli che hanno bisogno d'amore.}
{321}{}{Diventerai una stella. Una grande, brillante, luccicante stella.}
{322}{}{Sei piu' eruttivo di un vulcano quand'e' infuriato.}
{323}{}{Adoro quando mi parli in spagnolo.}
{324}{}{Sei bellissimo, zucchero.}

# 10. [PORN STAR, FEMALE]
{330}{}{::Ti ignora::}
{331}{}{Nella prossima scena tu interpreti la ragazza francese o quella russa?}
{332}{}{Vorrei tanto che il metodo di controllo delle nascite fosse un pochino piu' affidabile.}
{333}{}{Sei stata tu a rubare le mie scarpe con i tacchi a spillo?}
{334}{}{Mi sento un po' stanca… hai del Jet?}
{335}{}{Hmphhh!}
{336}{}{No, mi dispiace, dolcezza. Non so dove siano i Fratelli Corsican.}
{337}{}{Vuoi che ti mostri dov'e' l'uscita?}
{338}{}{Sei ingrassata, per caso?}
{339}{}{Potresti per cortesia allontanarti un po'. Il tuo… profumo… mi fa venire la nausea.}
{340}{}{Ho sentito che i Fratelli ti stanno per scaricare. Mi dispiace, e' un VERO peccato.}
{341}{}{Credo che, se persino una persona senza talento come te ce la puo' fare, io sia destinata a cose ben migliori.}
{342}{}{Il tuo culo e' cosi' grassoccio! Che carino!}
{343}{}{Inizio a pensare che non sia difficile sfondare in questo settore.}
{344}{}{*Io* non ho mai detto che sei grassa e brutta. Dev'essere stato qualcun altro.}
{345}{}{Ho sentito dire che nessuno degli attori vuole lavorare con te.}
{346}{}{Non ti sei fatta il bagno prima di farti vedere?} ???before you showed up

# 11. [MALE, PRIZEFIGHTER OR MADE MAN]
{350}{}{Come butta, }
{351}{}{Stai uscendo dal mondo della boxe per entrare in quello del porno? Stessa cosa, diverso palcoscenico.}
{352}{}{Vuoi fare un salto sul ring con me, campione?}
{353}{}{Vuoi boxare, campione?}
{354}{}{Fa' attenzione al Masticatore. E' un vero stronzo. Ha provato a mordermi via un orecchio, una volta.}
{355}{}{Vuoi aiutarmi a ripassare la mia parte?}
{356}{}{Potresti procurarmi un po' di Jet?}
{357}{}{Queste scene mi stanno apren... er, stancando molto.}
{358}{}{Quello che vorrei, in realta', e' fare la regista...} ???Come to sample some of the coozine
{359}{}{Bel pezzo di ferro hai li'.}
{360}{}{I miei fidanzati non sanno che lavoro qui. Non che mi interessi quello che pensano.}
{361}{}{Se stai cercando compagnia, piu' tardi non ho nulla da fare.}
{362}{}{Stai per entrare nel giro? Benvenuto a bordo.}
{363}{}{Hai proprio un bel pezzo, li' sotto.}
{364}{}{Dovresti darti al porno. Hai il corpo adatto per farlo.}
{365}{}{Bel pezzo di ferro hai li'.}
{366}{}{Se stai cercando compagnia, piu' tardi non ho nulla da fare.}
{367}{}{Ho sentito parlare di te. Sei }
{368}{}{E' stato il tuo capo a mandarti da me?}
{369}{}{Stai cercando di costringermi a fare sesso con te? Accomodati.}
{370}{}{Il tuo capo ti ha mai parlato di me?}

# 12. [FEMALE, PRIZEFIGHTER OR MADE MAN]
{380}{}{Com'e' la boxe?}
{381}{}{Fa' attenzione al Masticatore. E' un vero stronzo. Ha provato a mordermi via un orecchio, una volta.}
{382}{}{Mi piace il tuo completino. Tres chic.}
{383}{}{Quel completo ti sta d'incanto.}
{384}{}{Cosa cavolo vuo… oh! Madame! Benvenuta nello studio.}
{385}{}{I miei fidanzati non sanno che lavoro qui. Non che mi interessi quello che pensano.}
{386}{}{Um…non e' che potrebbe procurarmi un po' di Jet, signora?}
{387}{}{Queste scene mi stanno apren... er, stancando molto.}
{388}{}{Se faccio qualcosa piu' tardi? Er… no, signora. Per niente.}
{389}{}{Com'e' lavorare per il capo?}
{390}{}{Il capo le parla mai di me?}

# 13. [LEATHER]
{395}{}{Senti, il bondage e il SadoMaso si fanno solo di mercoledi'. Ora strizza il tuo culo di cuoio fuori di qui.}
{396}{}{Dubito seriamente che i Fratelli vogliano fare un altro film sesso&pelle, dopo il fiasco di Apelle dalle Palle fasciate di Pelle.} ???I seriously doubt the Brothers are looking for another leather act after that Happily Leather After fiasco.
{397}{}{Smettila di darmi fastidio. Sto cercando di imparare queste battute.}
{398}{}{Mi PAREVA di aver sentito odore di cuoio. Credevo pero' che si trattasse del divano.}
{399}{}{Senti, coniglietta-tutta-cuoio, se non hai la tua frusta personale, i Fratelli non ti diranno nemmeno l'ora.} ???if you don't have your own whip, the Brothers won't even give you the time of day

# 14. [MALE, NO REP]
{410}{}{Tu? No grazie. Il mio rossetto saprebbe scoparmi meglio.}
{411}{}{Perche' non ti vai a divertire un po' con un temperamatite?}
{412}{}{Non ho il tempo di intrattenere una noiosa conversazione senza senso con te, al momento.}
{413}{}{Non mi interessa se sei capace di piantare un chiodo da 15cm in un'asse usando il tuo pene. Adesso sparisci.}
{414}{}{Sesso? No, sono sposata, e anche se non lo fossi, non lo farei lo stesso.}
{415}{}{Non do' appuntamenti ai bianchi.}
{416}{}{Dubito che tu possa essere migliore del mio massaggiatore da doccia.}
{417}{}{Non mi pare che tu possa permetterti di assecondare le mie abitudini in fatto di shopping.}
{418}{}{Zucchero, sono troppo cara per te.}
{419}{}{Sto solo cercando il tipo giusto. E' gentile da parte tua tenermi compagnia fino a quando non si fara' vedere.}
{420}{}{Non c'e' speranza che tu riesca a infilarti nelle mie mutandine. C'e' posto per un solo buco del culo li' dentro.}
{421}{}{Mi spiace, credevo che avessi un bell'aspetto, ma mi sono sbagliata.}
{422}{}{Tu? Mi spiace, ma non saro' MAI cosi' disperata.}
{423}{}{No, non li ho visti i Fratelli qui in giro… adesso non disturbarmi. Sono un'attrice.}
{424}{}{Per favore… niente autografi.}
{425}{}{Vorrei tanto fare la regista.}
{426}{}{Ballo al casino', il giovedi'. Vieni a vedermi e porta un po' di quattrini.}
{427}{}{Non puoi lontanamente immaginare quanto stressante sia questa vita.}
{428}{}{I miei fidanzati non sanno che lavoro qui. Non che mi interessi quello che pensano.}
{429}{}{TI PREGO, smettila di disturbarmi. Sto cercando di imparare queste battute.}
{430}{}{Se stai cercando un lavoro, parla con i Fratelli Brothers.}
{431}{}{Sei la nuova assistente?} #fluffer
{432}{}{Sei la nuova assistente? Non riesco a immaginare chi altri potresti essere.}
{433}{}{Se sei la nuova assistente, potresti cominciare frustandomi il culo.}
{434}{}{Non li ho visti i Fratelli qui in giro, ragazza... adesso cerca di non disturbarmi. Sono un'attrice.}
{435}{}{Per piacere, ragazza… niente autografi.}
{436}{}{Se ti fossi pulita un po' di piu', FORSE avresti potuto fare l'assistente.}
{437}{}{Mi spiace, no, non faccio sesso lesbico per meno di 200 dollari. 300, per te.}
{438}{}{Ballo al casino', il giovedi'. Vieni a vedermi e porta un po' di quattrini.}
{439}{}{Ragazza, TU non puoi lontanamente immaginare quanto stressante sia questa vita.}

{1230}{}{?}
{1231}{}{.}
{1250}{}{?}
{1265}{}{?}
{1305}{}{?}
{1350}{}{?}
{1367}{}{, vero?}