# 0. QUICK LOOK
{100}{}{Vedi un brahmin infuriato.}

# 0. LOOK
{150}{}{Vedi un grosso brahmin infuriato. Il suo stomaco sembra gonfio, e i suoi occhi sono iniettati di sangue.}
{151}{}{Vedi un grosso brahmin infuriato. Il suo stomaco sembra gonfio, e i suoi occhi sono iniettati di sangue. Sembra stare molto male. Forse puoi aiutarlo in qualche modo.}

# 2.  FLOAT/CLICK
# success doctor skill
{198}{}{::Rnnnrrrrr?::}
{199}{}{::Hrrnnnnr?::}
# any
{200}{}{Muu}
{201}{}{Muuuuuuuuu}
{202}{}{Muuuu}
{203}{}{::Rnnr::}
# failed doctor skill
{204}{}{::Rnnnrrrrr!!!::}
{205}{}{::Gnnnnnrrrr!!!::}
{206}{}{::Hrrnnnnr!!!::}

# 3.  DESCRIPTION: GOOD DOCTOR SKILL
{225}{}{Estrai l'oggetto che era conficcato nell'intestino del brahmin.}

# 4.  DESCRIPTION: FAIL DOCTOR ROLL
{235}{}{C'e' qualcosa conficcato nell'intestino del brahimn, ma non sei riuscito a prenderlo.}