# QUICK LOOK
{100}{}{Vedi un barista.}

# EXAMINE
{150}{}{Vedi un uomo tozzo che sta dietro al bancone. Ti fa un cenno con la testa.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Ehi! }
{201}{}{! Sei stato grande a spaccare in due l'Enlcave! Vuoi qualcosa da bere?}

# 2. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA = SAME CASINO (WTG)
{206}{}{! Come va?!}

# 3. FLOAT DIALOGUE: NORMAL (WTG)
{210}{}{Un bicchiere di tritabudella in arrivo...}
{211}{}{Fanno tre dollari...}
{212}{}{Un altro, amico?}
{213}{}{Eccoti un ricostituente, se ne hai bisogno.} ###???ricochet
{214}{}{Non inalare il Jet tutto in una volta... prendine un colpo, un respiro profondo, poi aspetta che la scarica si esaurisca.}
{215}{}{Vuoi due confezionis da mezza oncia, o una fiala?}
{216}{}{L'inalatore per Jet devi comprarlo a parte...}
{217}{}{Lasciami indovinare: te lo devo mettere sul conto?}
{218}{}{Un'atomica on the rocks, in arrivo.}
{219}{}{Non permettiamo che i clienti assumano del Buffout qui dentro, amico.}

# 4. CLICK DIALOGUE: THREAT (WTG)
{225}{}{Farai meglio ad uscire da qui prima che io ti serva piu' piombo di quanto tu ne possa digerire, capito?}
{226}{}{Su... esci. Non vogliamo guai.}
{227}{}{Ti uccideranno se rimani nei paraggi. Sparisci.}
{228}{}{Abbiamo finito tutto. Ora va' via, sparisci.}

# 5. INTRO (WTG)
{236}{}{! Quale veleno vuoi che ti serva?}
{237}{}{Eeeeeehi, campione! Quale veleno vuoi che ti serva?}
{238}{}{Quale veleno vuoi che ti serva, amico?}
{239}{}{Quale veleno vuoi che ti serva, dolcezza?}
{240}{}{Mele-no sembrare buono}
{241}{}{Veleno?! Me no vuole veleno!}
{242}{}{Cosa avete da bere?}
{243}{}{Che tipo di droghe avete?}
{244}{}{Chi e' il vecchio attaccato a quella schifosa slot machine?}
{245}{}{Chi e' il tizio con il coltello al bancone?}
{246}{}{Niente per oggi, grazie.}

# 6. WHAT'S WITH McGEE? (5)
{250}{}{Oh, intendi dire il vecchio McGee? E' innocuo. Ha speso praticamente una fortuna in quella vecchia slot machine e sono anni che non guadagna qualcosa. E' fallito, credo. Comunque... posso offrirti qualcosa, amico?}

# 7.  WHAT'S WITH LIL' JESUS? (5)
{260}{}{Quello e'  Lil' Jesus, il figlio di Jesus. Lui e il suo coltello sono come amici per la pelle... Gli ho visto fare delle cose davvero terribili con quello. Comunque... posso offrirti qualcosa, amico?}
