{100}{}{Vedi Frenchy.}
{101}{}{Vedi Paine.}
{102}{}{Vedi Sims.}
{150}{}{Vedi un uomo vestito di stracci. E' vicino ad un bidone della spazzatura incendiato e sta cantando. Ha una discreta voce.}
{151}{}{Vedi un cantante. E' vicino ad un bidone della spazzatura incendiato e sta cantando.}
{200}{}{Ehi... }
{203}{}{Ti serve qualcosa, figliolo?}
{204}{}{::Tocca la tesa di un cappello immaginario:: Le serve qualcosa, miss?}
{205}{}{La conoshete 'row row boat down stream?'}
{206}{}{Potreshte… potreshte cantarme Nove BILLYoni di bottije di birra shul muro?}
{207}{}{Nooo me va ora}
{208}{}{Ne sarei onorato. Grazie, ragazzi.}
{209}{}{Ecco un po' di spiccioli. Potreste cantare qualcos'altro?}
{210}{}{No, ascolto solamente, grazie.}
{300}{}{D'accordo, allora… avete sentito il signore, ragazzi. Proviamo qualcosa di diverso.}
{301}{}{D'accordo, allora… avete sentito la signora, ragazzi. Proviamo qualcosa di diverso.}
{302}{}{Grassshie}
{303}{}{Grazie, ragazzi.}
{400}{}{Oooooh}
{402}{}{La mia donna non torneraaaa a casaaa...}
{405}{}{La mia donna mi ha fattoooo del maaale...}
{408}{}{La mia donna se n'e' andataaa e mi ha lasciatooo da solooo...}
{409}{}{}
{500}{}{Go on}
{501}{}{Assapora il dolore}
{502}{}{Torna a trovarci un altro giorno}
{503}{}{}
{600}{}{ Bottiglie di Birra sul Muro...}
{601}{}{ Bottiglie di Birra...}
{602}{}{Prendine una...}
{603}{}{Passala di mano...}
{605}{}{}
{700}{}{Row Row Row}
{701}{}{La tua barca}
{702}{}{Dolcemente giu' per il torrente}
{703}{}{Allegramente}
{706}{}{La vita non e' che un sogno...}
{707}{}{}
{800}{}{Non abbiamo bisogno di un altro eroe...}
{801}{}{Non abbiamo bisogno di sapere la strada di casa...}
{802}{}{Tutto cio' di cui abbiamo bisogno e' cio' che sta oltre...}
{803}{}{Metadone}
{804}{}{}
{900}{}{Dammi}
{901}{}{Un bacio su cui costruire un sogno}
{902}{}{E la mia immaginazione}
{903}{}{Prosperera' grazie a quel bacio}
{904}{}{Mmmmm}
{905}{}{Tesoro,}
{906}{}{Non chiedo altro che questo:}
{910}{}{Un bacio prima che tu mi lasci}
{912}{}{Nutrira' il mio cuore affamato}
{913}{}{Leave me one thing before we part…}
{915}{}{Quando sono solo}
{916}{}{Con le mie fantasie}
{917}{}{Sarooooo' con teeeeee}
{918}{}{Tessendo ro-manze}
{919}{}{Facendo finta che siano vere}
{920}{}{Oh, dammi le tue labbra per un solo momento}
{921}{}{And my imagination will make that moment live…}
{923}{}{Dammi cio' che solo tu puoi darmi}
{925}{}{::Tromba a bocca::}
{930}{}{Saro'... con teeee}
{933}{}{Ohhhh}
{935}{}{labbra per un solo momento}
{937}{}{Rendero' quel momento vivo}
{941}{}{}
{1200}{}{! Il grande eroe! Come possiamo aiutarti? Forse potremmo cantarti qualcosa di speciale, eh?}
{1201}{}{. Possiamo aiutarti?}
{1202}{}{. Ti serve qualcosa, campione?}
