# 0. QUICK LOOK (WTG)
{100}{}{Vedi Bill.}

# 0. LOOK (WTG)
{150}{}{Vedi un uomo deperito con le sopracciglia bianche e cespugliose. Sembra che abbia bisogno di farsi una bevuta.}

# 1. FLOATS (WTG)
{200}{}{::Tossisce::}
{201}{}{::Guarda il barista::}
{202}{}{::Fa un gesto per chiedere un altro drink::}
{203}{}{::Guarda::}

# 2. STUPID FLOATS (WTG)
{210}{}{Sparisci, idiota.}

# 3. NORMAL (WTG)
{220}{}{(L'uomo non alza nemmeno lo sguardo mentre ti avvicini. Sta fissando il muro dietro al bancone.)}
{221}{}{Uh, ehi, novita'?}
{222}{}{Ehi, cosa ne pensi degli occhiali che indosso?}
{223}{}{Ehi, hai mai ucciso qualcuno?}
{224}{}{-Lo lasci in pace-}

# 4. FALLOUT2 = ENCLAVE_DESTROYED (3)
{230}{}{Ma che cazzo di domanda e' questa?}
{231}{}{Whoa. Calmati. Ero solo curioso.}
{232}{}{Okay. Beh, lasciamo perdere allora.}

# 5. FALLOUT2 = ENCLAVE_DESTROYED (4, 6)
{240}{}{Calmati tu.}
{241}{}{Non prima di averti dato una lezione.}

# 6. FALLOUT2 = ENCLAVE_DESTROYED (3)
{250}{}{(L'uomo rivolge lo sguardo verso di te.) Sembri un idiota.}
{251}{}{Whoa. Calmati. Stavo solo chiedendoti un'opinione.}
{252}{}{Uh… grazie dell'onesta'...}

# 7. What's going on?
{260}{}{(Ti fa cenno di stare zitto e di lasciarlo bere.)}
{261}{}{-Lo lasci in pace-}