# QUICK LOOK
{100}{}{Vedi uno degli uomini di Bishop.}

# EXAMINES
{150}{}{Vedi un uomo dall'aspetto robusto che indossa un'armatura di pelle. Il suo corpo e' coperto da varie cicatrici di ferite d'arma da fuoco ora rimarginate.}
{151}{}{Vedi uno degli uomini di Bishop. Osserva la zona mentre accarezza la sua arma.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE
{200}{}{Ehi! }
{201}{}{::esulta::}
{202}{}{::applaude::}
{203}{}{::fischia::}

# 2. FLOAT DIALOGUE: POWER ARMOR
{205}{}{Come diavolo fai ad andare al cesso con una roba del genere addosso?}

# 3. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [ARMED]
{210}{}{Bel ferro, }

# 4. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [SNEAK]
{215}{}{Uh, perche' cerchi di non farti vedere, }
{216}{}{Uh, ehi, }

# 5. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [NORMAL]
{220}{}{Yo, }
{221}{}{Ehi, }
{222}{}{Ehi, }

# 6. FLOAT/CLICK DIALOGUE: MADE MAN, FA=NOT BISHOP
{225}{}{Sei appena entrato nel posto sbagliato, sacco di merda.}
{226}{}{Beh, guardate un po' che fegato ha questo figlio di puttana... smamma, ragazzo, se non vuoi beccarti una pallottola in corpo.}
{227}{}{Questo tizio cerca guai...}
{228}{}{Mi hanno detto che i }
{229}{}{Faresti meglio ad andartene, }
{230}{}{Beh, che mi venga un colpo se quello non e' }
{231}{}{Non pensavo che i membri della famiglia }
{232}{}{Sei appena entrata nel posto sbagliato, troia.}
{233}{}{Beh, guardate quant'e' sfacciata questa puttana...}
{234}{}{Smamma, ragazza, se non vuoi beccarti una pallottola in corpo.}
{235}{}{Questa troia cerca guai...}
{236}{}{Mi hanno detto che i membri della famiglia }

# 8. FLOAT DIALOGUE: MALE, PRIZEFIGHTER [ARMED]
{250}{}{Yo, campione. Niente armi qui dentro, 'kay?}
{251}{}{Yo, campione! Metti via quell'arma.}
{252}{}{Ehi, }

# 9. FLOAT DIALOGUE: MALE, PRIZEFIGHTER AND MALE PORN STAR [SNEAK]
{255}{}{Perche' cerchi di non farti vedere?}
{256}{}{Stai cercando di evitare i tuoi fan?}
{257}{}{Uh, perche' tutta questa segretezza?}

# 10. FLOAT DIALOGUE: MALE/FEMALE, PRIZEFIGHTER
{260}{}{Yo, }
{261}{}{Yo, }

# 11. FLOAT DIALOGUE: PORN STAR [ARMED]
{265}{}{Yo, grande amatore. Niente armi qui dentro, 'kay?}
{266}{}{Ehi, }
{267}{}{Yo, }
{268}{}{Dolcezza, qui dentro non puoi portare delle armi. Eh eh... sei gia' abbastanza letale senza.}
{269}{}{Ehi, }

# 13. FLOAT DIALOGUE: [PORN STAR, FEMALE] [SNEAK]
{275}{}{Dolcezza, con un corpo come il tuo, non puoi sperare di passare inosservata.}

# 14. FLOAT DIALOGUE: [PORN STAR, NORMAL]
{280}{}{Adoro i tuoi film, }
{281}{}{Mi ha molto colpito la tua recitazione in "L'ano del Dragone".}
{282}{}{Avro' sempre in mente la scena di "Eiacula il Vampiro" in cui tu...}
{283}{}{Sono un tuo grande fan da quando ti ho visto in "Porka&Onta".}
{284}{}{Ho amato alla follia "Luci Rosse nel Vault". Davvero intenso. Un vero tour-de-force cinematografico.}
{285}{}{::Fischia::}

# 16. FLOAT DIALOGUE: SLAVER [ARMED]
{295}{}{C'e' forse una fossa vuota che ti aspetta sul Golgotha, schiavista? Metti via quell'arma.}
{296}{}{Metti via quell'arma, schiavista, o faro' un po' di tiro al bersaglio su di te.}
{297}{}{Schiavista, faresti meglio a rinfoderare quell'arma. IMMEDIATAMENTE.}

# 17. FLOAT DIALOGUE: SLAVER [SNEAK]
{300}{}{C'e' forse una fossa vuota che ti aspetta sul Golgotha, schiavista? Smettila di muoverti furtivamente.}
{301}{}{Smettila di nasconderti, schiavista, o faro' del tiro al bersaglio con te.}
{302}{}{Forse faresti meglio a tornare alla scuola per Ninja, schiavista - adesso smettila di muoverti furtivamente.}
{303}{}{Schiavista, faresti meglio a smetterla di cercare di mimetizzarti con il fondale. IMMEDIATAMENTE.}

# 18. FLOAT DIALOGUE: MALE/FEMALE, NO REP [ARMED]
{305}{}{C'e' forse una fossa vuota che ti aspetta sul Golgotha, selvaggio? Metti via quell'arma.}
{306}{}{Metti via quell'arma, selvaggio, o faro' un po' di tiro al bersaglio su di te.}
{307}{}{Selvaggio, faresti meglio a rinfoderare quell'arma. IMMEDIATAMENTE.}

# 19. FLOAT DIALOGUE: MALE/FEMALE, NO REP [SNEAK]
{310}{}{C'e' forse una fossa vuota che ti aspetta sul Golgotha, selvaggio? Smettila di nasconderti nell'ombra.}
{311}{}{Smettila di nasconderti, selvaggio, o faro' del tiro al bersaglio con te.}
{312}{}{Forse faresti meglio a tornare alla scuola per Ninja, selvaggio - adesso smettila di muoverti furtivamente.}
{313}{}{Selvaggio, faresti meglio a smetterla di cercare di mimetizzarti con il fondale. IMMEDIATAMENTE.}

# 20. FLOAT DIALOGUE: COMPANION: ROBOBRAIN
{315}{}{Porta quel robot fuori di qui. Subito.}
{316}{}{Porta quel robot fuori di qui prima che gli dia fuoco come fosse un cassonetto.}
{317}{}{Quel robot verra' smontato pezzo per pezzo, se rimane qui.}

# 21. FLOAT DIALOGUE: COMPANION: MARCUS (WTG)
{320}{}{Mi *pareva* di aver sentito puzza di mutante. Faresti meglio a portare il suo brutto muso fuori di qui. Subito.}
{321}{}{Tu e il tuo amico mutante state cercando di farvi sparare un colpo in testa? Sparite.}
{322}{}{Quel mutante fara' meglio ad uscire subito, oppure appenderemo la sua testa al muro come trofeo.}

# 22. FLOAT DIALOGUE: MALE/FEMALE, NO REP
{325}{}{Hai visto l'incontro, ieri notte?}
{326}{}{Dopo il lavoro me ne andro' al bar.}

# 23. CLICK DIALOGUE: ENCLAVE DESTROYED IS TRUE
{330}{}{Pensavo che il Presidente fosse una leggenda, uno spauracchio usato per spaventare i bambini.}
{331}{}{Sembra che tu abbia fatto un viaggio di andata e ritorno dall'Inferno. Prenditi una pausa. Te la meriti.}
{332}{}{Stavano per rilasciare un qualche nuovo virus nell'aria? Che bastardi. Spero che tu ne abbia ucciso un paio anche per me.}
{333}{}{Puoi ricominciare il gioco con un altro personaggio, se vuoi.}
{334}{}{Devi avere un bel po' di forza per esser riuscito a distruggere l'Enclave a quel modo.}
{335}{}{Ti stai facendo un giretto per mettere insieme un po' di punti esperienza dopo aver finito il gioco, eh? Beh, ti prego, vedi di non uccidere ME, okay?}
{336}{}{New Reno e' stata ideata da Chris Avellone e gli script sono stati realizzati da Tom French. Si dice che si sposeranno presto e che chiameranno loro figlio Ragfox.}
{337}{}{Spero di poter essere uno dei personaggi principali di Fallout 3, tipo Tandi o Ian. Fare il criminale di strada e' una schifezza.}
{338}{}{E' vero! Una volta mi sono scopato Tandi. Cioe', quand'era giovane.}
{339}{}{Quella tipa, Lynette, ha solo un dannato bisogno d'amore, sai?}
{340}{}{Ho sentito che hai spazzato via l'Enclave, giu' a sud. Davvero coraggioso.}

# 24. CLICK DIALOGUE: MALE/FEMALE, MADE MAN, SAME FAMILY
{350}{}{Ehi, }
{351}{}{Yo, }
{352}{}{Ehi, }
{353}{}{Ho sentito che Tommy the Balls e' tornato in citta' per tenere d'occhio le cose. Fa' attenzione.}
{354}{}{Se vedi Tommy the Balls, vedi di non metterti contro di lui.}
{355}{}{Metterai una buona parola con Bishop per me?}
{356}{}{Bei vestiti. Vorrei anch'io essere in cosi' buoni rapporti con il boss.}
{357}{}{Hai qualche consiglio per un tipo come me?}
{358}{}{Mi trovo bene nella Famiglia Bishop.}
{359}{}{John Bishop comandera' questa citta'.}
{360}{}{L'atmosfera e' piuttosto tranquilla, oggi.}
{361}{}{Sta per arrivare un temporale.}
{362}{}{La puzza che veniva dal Golgotha stanotte era insopportabile.}
{363}{}{Quand'e' che spazzeremo via una delle altre famiglie?}
{364}{}{Con te al nostro fianco, le altre famiglie non avranno scampo, boss.}
{365}{}{Ti serve qualcosa, boss?}
{366}{}{Hai qualche notizia sulle altre famiglie?}
{367}{}{Um, hai del Jet?}
{368}{}{Avrei proprio bisogno di un drink...}
{369}{}{La signora Bishop mi ha osservato di nuovo a quel modo, oggi. Mi fa sentire a disagio.}
{370}{}{La signora Bishop continua a guardarmi come se fossi una succosa bistecca. Vorrei che capisse che io non voglio guai.} ###???that I just want to be held
{371}{}{La figlia di Bishop e' davvero un bel pezzo di...}
{372}{}{La figlia di Bishop e' un concentrato di guai.}
{373}{}{Ho sentito che uno dei ragazzi ha fatto ubriacare la figlia di Bishop e che per questo Mr. Bishop l'ha fatto scorticare.}
{374}{}{Se parli con Bishop, sta' lontano da sua moglie e da sua figlia... ti risparmierai un sacco di guai.}

# 25. CLICK DIALOGUE: PRIZEFIGHTER
{380}{}{Ho sentito che la signora Bishop ti sta cercando. Occhio, amico.}
{381}{}{Ho sentito che la figlia di Bishop ti stava cercando. Attento a non cacciarti in qualche guaio.}
{382}{}{Non mi sembri poi cosi' forte, Mr. Campione del Mondo.}
{383}{}{Sai, la Famiglia Bishop avrebbe proprio bisogno di un tipo come te. Forte. Irriducibile.}
{384}{}{Dovresti parlare con Bishop per farti dare un lavoro.}
{385}{}{Credo che dovresti considerare l'idea di unirti a noi. Presto saremo i padroni di New Reno.}
{386}{}{Ho scommesso 20$ su di te!}
{387}{}{Ehi, campione! L'ultimo incontro e' stato grandioso!}
{388}{}{Ti ho visto combattere sul ring. Quel gancio destro che hai tirato e' stato spettacolare.}
{389}{}{Sei sicuro di poter vincere ancora? Ho scommesso 30$ su di te.}
{390}{}{Quante flessioni fai al giorno?}
{391}{}{Dov'e' che ti alleni?}
{392}{}{Occhio al Masticatore. Ha la passione per le orecchie.}
{393}{}{Ti offrirei da bere, se non avessi perso tutti i miei soldi scommettendo sul tuo avversario.}
{394}{}{Che ne dici di una sfida a braccio di ferro?}
{395}{}{Non mi sembri poi tanto forte, Miss Gancio Sinistro.}
{396}{}{Posso vedere i tuoi addominali mentre si flettono?}

# 27. CLICK DIALOGUE: PORN STAR
{400}{}{Ho sentito che la signora Bishop ti sta cercando. Occhio, amico.}
{401}{}{Potresti trovarmi un lavoro, amico? Eddai. Sono il re degli stalloni.}
{402}{}{Adoro i tuoi film, }
{403}{}{Mi ha molto colpito la tua recitazione in "La Lampo di Aladino".}
{404}{}{Avro' sempre in mente la scena di "Eiacula il Vampiro" in cui tu...}
{405}{}{Sono un tuo grande fan da quando ti ho visto in "Porka&Onta".}
{406}{}{Ho amato alla follia "Luci Rosse nel Vault". Davvero intenso. Un vero tour-de-force cinematografico.}
{407}{}{Ho sentito che la figlia di Bishop ti stava cercando. Attento a non cacciarti in qualche guaio.}
{408}{}{Hai qualche "buco" da riempire, nel tuo cast?}
{409}{}{Ho amato alla follia "Luci Rosse nel Vault". Davvero intenso. Un vero tour-de-force cinematografico.}
{410}{}{Ho sentito che Tommy the Balls vorrebbe vederti privatamente per un provino.}
{411}{}{Il tuo ultimo film mi e' piaciuto tantissimo. Posso aiutarti nelle prove per il prossimo?}
{412}{}{Dammi una parte in uno dei tuoi film e io ti insegnero' un paio dei miei trucchetti.}
{413}{}{Quand'e' che ti fermerai e mi darai un'occhiata?}
{414}{}{Ehi, ballerai qui, stasera?}
{415}{}{Hai un cul... due tet... un corp... uno sguardo bellissimo, dolcezza.}
{416}{}{Madama Fortuna diventera' gelosa, se continui a farti vedere da queste parti.}

# 29. CLICK DIALOGUE: [SLAVER]
{420}{}{Come vanno le cose, su al Den?}
{421}{}{Ti ha fatto male quando ti hanno impresso il marchio da schiavista?}
{422}{}{Avrei voluto diventare uno schiavista, una volta, ma odio viaggiare.}
{423}{}{Stai cercando le Stalle? E' li' dove stanno la maggior parte degli schiavi.}
{424}{}{Stare nella Famiglia Bishop non e' male, come occupazione.}
{425}{}{Stai portando una nuova partita di schiavi in citta', oppure ne stai trasferendo qualcuno da qualche altra parte?}
{426}{}{Voi ragazzi dovreste fare un po' piu' di attenzione con la vostra merce... l'ultima partita di schiavi faceva proprio schifo.}
{427}{}{Avete catturato qualche altro schiavo selvaggio?}
{428}{}{Come sono i prezzi degli schiavi, ultimamente?}
{429}{}{Schiavi... Brahmin... nessuna differenza.}

# 30. CLICK DIALOGUE: MALE/FEMALE, NO REP (Good Reaction)
{440}{}{Se stai cercando un lavoro, un tipo come te potrebbe servirci. Parla con Mr. Bishop.}
{441}{}{Stai cercando lavoro? Forse dovresti parlare con Mr. Bishop.}

# 31. CLICK DIALOGUE: MALE, NO REP (Bad Reaction)
{445}{}{Smamma, selvaggio.}
{446}{}{Non ho droghe da darti, selvaggio.}
{447}{}{Vatti a fumare il tuo calumet della pace, selvaggio.}
{448}{}{Non ho VOGLIA di chiacchierare. Sparisci.}
{449}{}{Sparisci, selvaggio.}
{450}{}{Sai chi sono io? Sono uno degli uomini di Bishop. Adesso va' a farti fottere.}
{451}{}{Stai cercando di farmi incazzare? Ti assicuro che se mi incazzo non ti divertirai molto.}
{452}{}{Smamma prima che ti usi come bersaglio mobile.}
{453}{}{Cerchi guai? Continua a parlare con me e vedrai cosa ti succede.}

# 32. CLICK DIALOGUE: FEMALE, NO REP (Bad Reaction)
{460}{}{Al momento non ho voglia di spassarmela con una tribale. Torna un'altra volta.}
{461}{}{Adesso non ho tempo per fotterti, selvaggia. Perche' non torni un'altra volta?}
{462}{}{No, non so dove si trovi, adesso sparisci! ::Stupidi selvaggi.::}
{463}{}{Tornatene alla tua tribu'.}
{464}{}{I Bishop non parlano con la spazzatura tribale. Abbiamo di meglio da fare.}
{465}{}{Non ho droghe da darti, selvaggia.}
{466}{}{Vatti a fumare il tuo calumet della pace, selvaggia.}
{467}{}{Non ho VOGLIA di chiacchierare. Sparisci.}
{468}{}{Sparisci, selvaggia.}
{469}{}{Sai chi sono io? Sono uno degli uomini di Bishop. Adesso va' a farti fottere.}
{470}{}{Stai cercando di farmi incazzare? Ti assicuro che se mi incazzo non ti divertirai molto.}
{471}{}{Smamma prima che ti usi come bersaglio mobile.}
{472}{}{Cerchi guai? Continua a parlare con me e vedrai cosa ti succede.}
{473}{}{Non saro' mai cosi' ubriaco. Sparisci.}
{474}{}{Credo che tu sia la piu' brutta donna di tribu' che io abbia mai visto.}
{475}{}{Vattene da qui prima che ti picchi cosi' tanto da farti diventare piu' brutta di quanto tu non sia gia'.}
{476}{}{Va' a sculettare davanti a qualcuno piu' ubriaco di me, troia.}

# 34. FLOAT DIALOGUE: COMPANION: LENNY
{490}{}{Mi *pareva* di aver sentito puzza di qualcosa che sta andando a male. Porta quel ghoul fuori di qui.}
{491}{}{Porta quel ghoul puzzolente fuori di qui. Adesso.}
{492}{}{Se quel ghoul non e' fuori di qui entro un minuto, sara' piu' morto di quanto non sia gia'.}

# END OF LINES
{1200}{}{! Gliel'hai proprio fatta vedere a quelli dell'Enclave!}
{1210}{}{.}
{1215}{}{?}
{1216}{}{... perche' tutta questa segretezza?}
{1220}{}{, come butta?}
{1221}{}{, cos'hai fatto di bello, ultimamente?}
{1222}{}{! Ti sei tenuto alla larga dai guai?}
{1228}{}{ sono un branco di femminucce. Tu cosa ne dici?}
{1229}{}{. Subito.}
{1230}{}{. Non credi che la tua famiglia sentira' la tua mancanza?}
{1231}{}{ avessero tempo per fare altre cose oltre a leccare il culo del loro capo.}
{1236}{}{ sono un branco di femminucce. Adesso vedo che quelle voci sono vere.}
{1252}{}{! Non puoi impugnare un'arma qui dentro, ok?}
{1260}{}{. Tutto a posto?}
{1261}{}{. Come va?}
{1266}{}{! Non puoi impugnare un'arma qui dentro, ok?}
{1267}{}{! Metti via quell'arma.}
{1269}{}{! Puoi tirar fuori le tue tette, ma quell'arma devi metterla via, ok?}
{1280}{}{!}
{1350}{}{. Come butta?}
{1351}{}{. Cos'hai fatto di bello, ultimamente?}
{1352}{}{. Ti sei tenuto alla larga dai guai?}
{1402}{}{!}
