# 0. QUICK LOOK
{100}{}{Vedi una delle guardie del corpo dei Fratelli Corsican.}

# 1. LOOK (WTG)
{150}{}{Vedi una donna dall'aspetto robusto con una cresta di capelli verdi in testa. Sta coccolando la sua mitraglietta come fosse un bambino.}
{151}{}{Vedi una delle guardie del corpo dei Fratelli Corsican.}


# 2. FLOAT (ANY) TO [FLAG: ENCLAVE DESTROYED] (WTG)
{200}{}{Hai salvato il mondo, eh? Davvero 'na bella roba.}
{201}{}{Oh, gee, sei il mio eroe. Adesso SMAMMA.}

# 3. What, you too good for me or what?
{300}{}{Ehi, ciaooo?}
{301}{}{Sai, c'era questa bionda mozzafiato...}
{302}{}{Cos'e'? Sei troppo figa per parlare con me?}
{303}{}{Dimmi qualcosa. Qualsiasi cosa!}

# 4. Prick
{400}{}{Testa di cazzo.}
{401}{}{Stronzo.}
{402}{}{Rotto in culo.}
{403}{}{Si', stai alla larga, idiota.}
{404}{}{Spero di non avere il "piacere" di incontrare di nuovo quella faccia da culo.}
{405}{}{Quella sgualdrina ha bisogno di mentine per l'alito.}
{406}{}{Troia.}

# 5. Nothing
{500}{}{Ti guarda in modo assente.}
{501}{}{Sembra che non abbia nulla da dirti.}

# 6. Porn Star
{600}{}{Mi piacerebbe tanto giocare con lui a... biliardo.}
{601}{}{Puoi farmi avere un appuntamento con lui?}
{602}{}{Hmmm...}
{603}{}{Puoi farmi avere un appuntamento con lei?}
{604}{}{Vorrei tanto andare con lei.}
{605}{}{Mi sono presa la *piu' grossa* cotta della mia vita per lei, ma sono troppo spaventata per dire qualcosa.}