# quick look
{100}{}{Vedi un fanatico della boxe molto eccitato. }

# examine
{150}{}{Vedi un uomo esagitato. Sta urlando qualcosa a perdifiato.}
{151}{}{Vedi un fanatico della boxe molto eccitato. Urla che vuole vedere il sangue.}
{152}{}{Vedi una donna esagitata. Sta urlando qualcosa a perdifiato.}
{153}{}{Vedi una fanatica della boxe molto eccitata. Urla che vuole vedere il sangue.}

# 1. FLOAT DIALOGUES [FAN=MALE, PC NOT A PRIZEFIGHTER]
{200}{}{Yeeeaaaaahhhhh!}
{201}{}{::urla:: ::grida:: ::urla::}
{202}{}{Uccidilo, }
{1202}{}{!}
{203}{}{Sei il migliore, }
{1203}{}{!}
{204}{}{Fallo fuori, }
{1204}{}{!}
{205}{}{Siii'! Fagliela vedere!}
{206}{}{}
{1206}{}{ e' il MIGLIORE. Il MIGLIORE.}
{207}{}{}
{1207}{}{!!!}
{208}{}{}
{1208}{}{, sei grande!}
{209}{}{}
{1209}{}{ e' il piu' grande campione di pugilato che io abbia mai visto.}
{210}{}{}
{1210}{}{ e' anche molto furbo. Sa davvero come colpire qualcuno.}
{211}{}{}
{1211}{}{ si preoccupa dei suoi fan. Non li uccide come fanno gli altri pugili.}
{212}{}{}
{1212}{}{ e' coooosi' bello.}
{213}{}{}
{1213}{}{ e' cooooosi' macho.}
{214}{}{Io adoro }
{1214}{}{ Aiiiieeeeeeeee!}
{215}{}{::urla:: ::urla::}
{216}{}{}
{1216}{}{ ci tiene a noi. Me l'ha detto l'altra notte.}

# 2. FLOAT DIALOGUES [FAN=MALE, PC = FEMALE OR MALE PRIZEFIGHTER]
{250}{}{}
{1250}{}{, sei grande!}
{251}{}{}
{1251}{}{ e' anche molto furbo. Sa davvero come colpire qualcuno.}
{252}{}{}
{1252}{}{ si preoccupa dei suoi fan. Non li uccide come fanno gli altri pugili.}
{253}{}{Ho sentito dire che }
{1253}{}{ era praticamente uno sconosciuto, un novellino appena arrivato dalle Lande, prima di venire a boxare qui a New Reno. Misterioso! Letale!}
{254}{}{Ommioddio! }
{1254}{}{! Fammi un autografo!}
{255}{}{Dammi un pugno! Dammi un pugno! Voglio dire ai miei figli che mi hai dato un pugno!}
{256}{}{Sei il migliore, }
{1256}{}{! Fagli assaggiare l'inferno!}
{257}{}{Uccidilo, }
{1257}{}{!}
{258}{}{Sei la migliore, }
{1258}{}{!}
{259}{}{Fagli sputare sangue, }
{1259}{}{!}
{260}{}{Siii'! Fagliela vedere!}
{261}{}{}
{1261}{}{, e' il MIGLIORE. Il MIGLIORE.}
{262}{}{}
{1262}{}{!!!}
{263}{}{Yeeeaaaaahhhhh!}
{264}{}{::urla:: ::grida:: ::urla::}
{265}{}{}
{1265}{}{ e' la miglior campionessa di pugilato che io abbia mai visto.}
{266}{}{}
{1266}{}{, sei la donna piu' forte del mondo!}
{267}{}{Sei piu' forte di Robbin' Givens!}
{268}{}{}
{1268}{}{, sei grande!}
{269}{}{}
{1269}{}{ e' anche molto furba. Sa davvero come colpire qualcuno.}
{270}{}{}
{1270}{}{ si preoccupa dei suoi fan. Non li uccide come fanno gli altri pugili.}
{271}{}{Ho sentito dire che  }
{1271}{}{ era praticamente una sconosciuta, una novellina appena arrivata dalle Lande, prima di venire a boxare qui a New Reno. Misteriosa! Letale!}

# 3. FLOAT DIALOGUES [FAN=FEMALE, PC = PRIZEFIGHTER]
{280}{}{Un bacio portafortuna?}
{281}{}{}
{1281}{}{, sei grande!}
{282}{}{}
{1282}{}{ e' cosi' beeeeello.}
{283}{}{}
{1283}{}{ ha il fisico di un carroarmato!}
{284}{}{}
{1284}{}{ e' anche molto furbo. Sa davvero come colpire qualcuno.}
{285}{}{}
{1285}{}{ si preoccupa dei suoi fan. Non li uccide come fanno gli altri pugili.}
{286}{}{Ho sentito dire che }
{1286}{}{ era praticamente uno sconosciuto, un novellino appena arrivato dalle Lande, prima di venire a boxare qui a New Reno. Misterioso! Letale!}
{287}{}{Ommioddio! }
{1287}{}{! Fammi un autografo!}
{288}{}{Dammi un pugno! Dammi un pugno! Voglio dire ai miei figli che mi hai dato un pugno!}
{289}{}{Sei il migliore, }
{1289}{}{! Fagli assaggiare l'inferno!}
{290}{}{Ammazzalo, }
{1290}{}{!}
{291}{}{Sei la migliore, }
{1291}{}{!}
{292}{}{Mettilo al tappeto, }
{1292}{}{!}
{293}{}{Siii'! Fagliela vedere!}
{294}{}{}
{1294}{}{, sei il MIGLIORE. Il MIGLIORE.}
{295}{}{}
{1295}{}{!!!}
{296}{}{Aiiiieeeeeeeee!}
{297}{}{::urla:: ::urla::}
{298}{}{}
{1298}{}{ e' il miglior campione di pugilato che abbia mai visto.}
{299}{}{}
{1299}{}{, sei la donna piu' forte del mondo!}
{300}{}{Sei piu' forte di Robbin' Givens!}
{301}{}{}
{1301}{}{, sei grande!}
{302}{}{}
{1302}{}{ e' anche molto furba. Sa davvero come colpire qualcuno.}
{303}{}{}
{1303}{}{ si preoccupa dei suoi fan. Non li uccide come fanno gli altri pugili.}
{304}{}{Ho sentito dire che }
{1304}{}{ era praticamente una sconosciuta, una novellina appena arrivata dalle Lande, prima di venire a boxare qui a New Reno. Misteriosa! Letale!}

# 4. CLICK DIALOGUES [FAN=FEMALE OR MALE, PC NOT A PRIZEFIGHTER]
{320}{}{ uccidera' chiunque intralci il suo cammino!}
{321}{}{ e' il MIGLIORE. Il MIGLIORE.}
{322}{}{!!!}
{323}{}{ e' grande!}
{324}{}{ e' il piu' grande campione che io abbia mai visto.}
{325}{}{ e' anche molto furbo. Sa davvero come colpire qualcuno.}
{326}{}{ si preoccupa dei suoi fan. Non li uccide come fanno gli altri pugili.}
{327}{}{ e' cosi' belllooooo.}
{328}{}{ ci tiene a noi. Me l'ha detto lui.}

# 5. CLICK DIALOGUES [FAN=MALE, PC = PRIZEFIGHTER]
{350}{}{}
{1350}{}{, sei il migliore!}
{351}{}{A casa ho un vasetto con dentro un po' del tuo sudore.}
{352}{}{Ommioddio! }
{1352}{}{! Fammi un autografo!}
{353}{}{Dammi un pugno! Dammi un pugno! Voglio dire ai miei figli che mi hai dato un pugno!}
{354}{}{Sei il migliore }
{1354}{}{! Fagli assaggiare l'inferno!}
{355}{}{Sei la migliore, }
{1355}{}{!}
{356}{}{Fagli sputare sangue, }
{1356}{}{!}
{357}{}{}
{1357}{}{, sei il MIGLIORE. Il MIGLIORE.}
{358}{}{}
{1358}{}{!!!}
{359}{}{Yeeeaaaaahhhhh!}
{360}{}{}
{1360}{}{, tu sei il piu' grande campione di pugilato che io abbia mai visto.}
{361}{}{}
{1361}{}{, tu sai davvero come far del male a qualcuno.}
{362}{}{}
{1362}{}{, tu ti preoccupi davvero per i tuoi fan. Non li uccidi come fanno gli altri pugili.}
{363}{}{Ho sentito dire che tu eri uno sconosciuto, un novellino appena arrivato dalle Lande, prima di venire a boxare qui a New Reno. Da dove vieni?}
{364}{}{}
{1364}{}{, sei la donna piu' forte del mondo!}
{365}{}{Sei piu' forte di Robbin' Givens!}
{366}{}{}
{1366}{}{, sei grandissima!}

# 6. CLICK DIALOGUES [FAN=FEMALE, PC = PRIZEFIGHTER]
{380}{}{Un bacio portafortuna?}
{381}{}{}
{1381}{}{, sei grande!}
{382}{}{}
{1382}{}{, sei cosi' bellllloooo.}
{383}{}{::Sembra sul punto di svenire mentre parli con lei::}
{384}{}{A casa ho un vasetto con dentro un po' del tuo sudore.}
{385}{}{Ommioddio! }
{1385}{}{! Fammi un autografo!}
{386}{}{Dammi un pugno! Dammi un pugno! Voglio dire ai miei figli che mi hai dato un pugno!}
{387}{}{Sei il migliore }
{1387}{}{! Fagli assaggiare l'inferno!}
{388}{}{Ammazzali, }
{1388}{}{!}
{389}{}{Sei il migliore, }
{1389}{}{!}
{390}{}{Rompigli il muso, }
{1390}{}{!}
{391}{}{.}
{1391}{}{, sei il MIGLIORE. Il MIGLIORE.}
{392}{}{}
{1392}{}{!!!}
{393}{}{Aiiiieeeeeeeee!}
{394}{}{}
{1394}{}{, tu sei il piu' grande campione di pugilato che io abbia mai visto.}
{395}{}{}
{1395}{}{, tu sai davvero come far del male a qualcuno.}
{396}{}{}
{1396}{}{, tu ti preoccupi davvero per i tuoi fan. Non li uccidi come fanno gli altri pugili.}
{397}{}{Ho sentito dire che eri uno sconosciuto, un novellino appena arrivato dalle Lande, prima di venire a boxare qui a New Reno. Da dove vieni?}
{398}{}{}
{1398}{}{, sei la donna piu' forte del mondo!}
{399}{}{Sei piu' forte di Robbin' Givens!}
{400}{}{}
{1400}{}{, sei grandissima!}
