# quick look
{100}{}{Vedi un cliente del casino'.}
{101}{}{Vedi una cliente del casino'.}


# examines
{150}{}{Vedi uno dei clienti del casino'. Sembra stanco.}
{151}{}{Vedi uno dei clienti del casino'. I suoi occhi luccicano d'oro.}
{152}{}{Vedi uno dei clienti del casino'. Si tiene la faccia tra le mani.}
{153}{}{Vedi uno dei clienti del casino'. Sembra un po' alticcio.}
{154}{}{Vedi uno dei clienti del casino'. Ti strizza vistosamente l'occhio, poi si allontana barcollando.}
{155}{}{Vedi uno dei clienti del casino'. Sta cercando di attirare l'attenzione della cameriera.}
{156}{}{Vedi una delle clienti del casino'. Sembra stanca.}
{157}{}{Vedi una delle clienti del casino'. I suoi occhi luccicano d'oro.}
{158}{}{Vedi una delle clienti del casino'. Si tiene la faccia tra le mani.}
{159}{}{Vedi una delle clienti del casino'. Sembra un po' alticcia.}
{160}{}{Vedi una delle clienti del casino'. Ti strizza vistosamente l'occhio, poi si allontana barcollando.}
{161}{}{Vedi una delle clienti del casino'. Sta cercando di attirare l'attenzione del cameriere.}

# float
{200}{}{::Batte le mani::}
{201}{}{::Saluta::}
{202}{}{Sei stato grande a mandare all'inferno quei bastardi dell'Enclave! Cosi' si fa!}
{203}{}{Sei stato grande a schiacciare l'Enclave, }
{204}{}{Congratulazioni per aver sconfitto l'Enclave, }
{205}{}{Congratulazioni per aver sconfitto l'Enclave, }
{206}{}{Uh-oh. Liberate la strada.}
{207}{}{La sola vista di quell'uomo...donna...coso...*qualsiasi* cosa sia, mi fa venire i brividi.}
{208}{}{Credete che quel coso sia qui per far fuori qualcuno?}
{209}{}{E' la furia dell'inferno incarnata! Uh, sotto l'armatura, s'intende.}
{210}{}{Non intralciate il cammino di quel coso.}
{211}{}{Questo si' che ha un aspetto pericoloso…}
{212}{}{*Gulp*}
{213}{}{Credo che quel Mr. Roboto li' mi abbia appena scansionato.}
{214}{}{Credo che quel carroarmato a due gambe mi abbia appena rivolto lo sguardo della morte... Io taglio la corda.}
{215}{}{Ho sentito che quel coso ha freddato tre banditi proprio ieri.}
{216}{}{Il solo guardarlo mi fa venire i brividi.}
{217}{}{Credete che sia qui per fare fuori qualcuno?}
{218}{}{Non intralciate quell'uomo.}
{219}{}{Credo che mi stesse guardando.}
{220}{}{Credo che mi abbia appena rivolto lo sguardo della morte. Io taglio la corda.}
{221}{}{Ho sentito che proprio ieri ha ammazzato tre pistoleri.}
{222}{}{Uh-oh. Liberate la strada.}
{223}{}{E' la furia dell'inferno in carne e ossa.}
{224}{}{Questo si' che ha un aspetto pericoloso…}
{225}{}{*Gulp*}
{226}{}{La Femme Nikita, e qualcosa di piu'.}
{227}{}{Il solo guardarla mi fa venire i brividi.}
{228}{}{Credete che sia qui per far fuori qualcuno?}
{229}{}{Credo che mi stesse guardando.}
{230}{}{Credo che mi abbia appena rivolto lo sguardo della morte. Io taglio la corda.}
{231}{}{Ho sentito che proprio ieri ha ammazzato tre pistoleri.}
{232}{}{Che bella fig... Uh, figura, naturalmente.}
{233}{}{Non mi sembri poi cosi' forte, signor Campione.}
{234}{}{Ho puntato 20 dollari su di te!}
{235}{}{Ehi, campione! Quell'ultimo incontro e' stato grandioso!}
{236}{}{Ti ho visto combattere sul ring. Hai tirato proprio un bel gancio destro.}
{237}{}{Accetterai la prossima sfida? Ho gia' puntato 30 dollari su di te.} ###???You gonna take the fall
{238}{}{Quanto tempo ti alleni?}
{239}{}{Dov'e' che ti sei allenato?}
{240}{}{Occhio al Masticatore. Adora le orecchie.}
{241}{}{Ti offrirei da bere se non mi fossi rovinato scommettendo tutti i miei soldi sul tuo avversario.}
{242}{}{Non mi sembri poi cosi' forte, miss "Gancio Sinistro".}
{243}{}{Posso vedere i tuoi addominali che si flettono?}
{244}{}{Whoa. Guardate che bomba.}
{245}{}{Guardate un po' chi abbiamo qui.}
{246}{}{::Sulla sua bocca si puo' leggere la parola "diamine"::}
{247}{}{Lo SAPEVO che dovevo radermi, stamattina.}
{248}{}{Vieni a chiacchierare un po' con me, tettine d'oro.}
{249}{}{Che tette che hanno le selvagge! Cazzo!}
{250}{}{Guardate che fondoschiena si ritrova, quella ragazza di tribu'.}
{251}{}{Ecco la mia puledra preferita.}
{252}{}{Per quella donna sarei pronto a farmi persino un bagno.}
{253}{}{Vieni a vedere che bel regalino ho qui per te.}
{254}{}{Ollelle'! Ollalla'!}
{255}{}{Faccela vede'! Faccela tocca'!}
{256}{}{::Fischia::}
{257}{}{Ma quelle gambe non finiscono mai?}
{258}{}{Caaaaaaaaazzo.}
{259}{}{Ti hanno dato un permesso speciale per andare in giro con quell'armamentario, bellezza?}
{260}{}{Forse stasera ballera'...}
{261}{}{Avete visto il suo ultimo film? Roba calda, amici, BOLLENTE.}
{262}{}{Scusatemi. Devo andare un attimo in bagno a, er, pettinarmi un po'.}
{263}{}{Vorrei tanto essere le sue mutandine.}
{264}{}{Vorrei tanto essere il suo reggiseno.}
{265}{}{Mi piacerebbe annusare il suo tanga.}
{266}{}{Quella si' che e' una donna arrapante.}
{267}{}{Cazzo. Tutte quelle curve e io non ho freni.}
{268}{}{Beh, ehila', bello.}
{269}{}{Uno stallone come te ha bisogno di montare... domani sera io sono libera.}
{270}{}{Cosa fai piu' tardi, marinaio?}
{271}{}{Posso toccare i tuoi muscoli?}
{272}{}{Come fai a non svenire quando ti viene un'erezione?}
{273}{}{Che ne dici di passare da me per un drink?}
{274}{}{Vorrei mangiare il mio pranzo sul tuo petto.}
{275}{}{Hai bisogno di una partner per il tuo prossimo film?}
{276}{}{::Fissa i tuoi bicipiti::}
{277}{}{Quella cosa che ti segue e' per caso una specie di slot machine?}
{278}{}{Quello e' un robot slot machine, per caso?}
{279}{}{Il tuo robot sa fare trucchi? Uh…trucchi magici, intendo.}
{280}{}{Tutto questo mi pare piu' assurdo di un lupo che ama una gallina.}
{281}{}{Gira, fortuna, gira.} ###???Roll the bones
{282}{}{Il bambino ha bisogno di un paio di scarpe nuove...}
{283}{}{Dannati turisti che giocano al ribasso…}
{284}{}{Cavoli! Ero in attivo di *53* dollari, quando…}
{285}{}{Per tutte le sfortune…}
{286}{}{Per un pelo!}
{287}{}{Sto facendo un sacco di soldi.}
{288}{}{Io? Sto facendo un mucchio di soldi. Guardami.}
{289}{}{Il banco mi era avverso.}
{290}{}{La fortuna era contro di me.}
{291}{}{Madama Fortuna, non tradirmi proprio adesso.}
{292}{}{Il banco ha avuto pieta' di me.}
{293}{}{Ci sono un sacco di novellini e di giocatori ubriachi, oggi…} ###???Between tips and these drunken spending sprees
{294}{}{Continua a puntare cifre come quella, e presto chiamerai il Golgotha "casa"…}
{295}{}{Cameriera, ancora da bere!}
{296}{}{Cameriere, ancora da bere!}
{297}{}{Questi drink hanno un sapore…strano.}
{298}{}{Ho la febbre del gioco!}
{299}{}{Ho gia' finito tutte le mie fiche?}
{300}{}{La fortuna e' una puttana volubile, proprio come mia suocera.}
{301}{}{Ultimamente in citta' si vedono parecchi schiavisti.}
{302}{}{Mi domando cosa succeda alle Stalle che si trovano fuori citta'.}
{303}{}{Un'altra faida sta per cominciare.}
{304}{}{Il mondo e' pieno di incoscienti...}
{305}{}{Magnifico, un altro giocatore della domenica.}
{306}{}{Chiamatemi Paperone.} ###???I am SO money
{307}{}{Dormiro' quando saro' morto.}
{308}{}{Cavoli, devo andare a pisciare. I miei denti stanno nuotando.}
{309}{}{Cavoli, devo andare a cambiare l'acqua al pesce.}
{310}{}{Cazzo, lasciano entrare chiunque, qui dentro.}
{311}{}{Eddai 7! Esci!}
{312}{}{Hai avuto una bella fortuna, baby.}
{313}{}{Chi e' il grande vincitore di stanotte? Mikey!}
{314}{}{Non tradirmi…dai…}
{315}{}{Devo mettercela tutta.}
{316}{}{Che gioco di MERDA.}
{317}{}{Ho perso solo 60 dollari... nei primi 5 minuti.}
{318}{}{23 rosso! 23 rosso! Dai…23 rosso…}
{319}{}{50 dollari sul 15 nero…}
{320}{}{Gira, gira la pallina in tondo…nessuno sa dove si fermera' in fondo…}
{321}{}{Sei stato grande ad arrostire quei bastardi dell'Enclave! Cosi' si fa!}
{322}{}{L'ho sempre saputo che il Presidente ci voleva vedere tutti morti.}
{323}{}{Il Presidente era vivo? Quando sono state le ultime elezioni?}
{324}{}{Hai distrutto l'Enclave, eh? Beh, lascia che ti offra da bere.}
{325}{}{Sei stato grande a schiacciare l'Enclave, }
{326}{}{Distruggendo l'Enclave hai reso questo casino' un posto migliore per i miei figli. Come potro' mai ringraziarti?}
{327}{}{L'Enclave non mi aveva mai dato fastidio, ma sono contento che non ci sia piu'.}
{328}{}{Non posso credere che quelli dell'Enclave stessero ancora combattendo la guerra dopo tutto questo tempo. Che idioti.}
{329}{}{Ho sentito come una grande perturbazione... come se un centinaio di luridi bastardi su di una piattaforma petrolifera avessero gridato terrorizzati e, a un tratto, si fossero zittiti. Strano.}
{330}{}{Congratulazioni per aver sconfitto l'Enclave, }
{331}{}{Congratulazioni per aver sconfitto l'Enclave, }
{332}{}{Stai cercando tuo fratello Robby? Sai, il Robot? Aw, come non detto.}
{333}{}{Scusa, ti bloccavo la strada? Me ne vado subito... dalla citta'.}
{334}{}{Scusa, stavo respirando la tua aria? La smetto subito.}
{335}{}{Non sapevo che facessero porte della tua grandezza.}
{336}{}{::bussa sull'armatura:: C'e' nessuno?}
{337}{}{"Pericolo, Will Robinson! Pericolo, Will Robinson!" Eheh. Uh…stavo solo scherzando.}
{338}{}{Beeeeeella armatura. L'aria condizionata ce l'ha?}
{339}{}{Non hai caldo, li' dentro?}
{340}{}{Posso strofinare questi dadi sulla tua armatura per un po' di fortuna?}
{341}{}{Hai perso il cuore, uomo di latta?}
{342}{}{Uh, salve, signore…o signora…o qualunque cosa tu sia.}
{343}{}{Porta i miei saluti a chiunque ti abbia fornito quell'armatura.}
{344}{}{Qualcosa non va, signore…signora…uh, qualunque cosa tu sia?}
{345}{}{Sei uno dei nuovi buttafuori? O sei per caso un nuovo coin-op semovente?}
{346}{}{No, NON oliero' le tue giunture.}
{347}{}{La tua armatura si puo' trasformare in aereo e volare via, per caso? Sono solo curioso.}
{348}{}{Certo, certo, "clank-whirrr-clank" anche a te.}
{349}{}{Se credi che quell'armatura mi spaventi... beh, hai perfettamente ragione.}
{350}{}{Devi essere una di quelle console per videogiochi del periodo pre-bellico.}
{351}{}{Guarda, per favore…non voglio guai. Mi fermo solo un giorno, in citta'.}
{352}{}{Guarda, per favore…non voglio guai.}
{353}{}{Scusa, ti bloccavo la strada? Me ne vado subito... dalla citta'.}
{354}{}{Scusa, stavo respirando la tua aria? La smetto subito.}
{355}{}{Porta i miei saluti al tuo boss.}
{356}{}{Uh…*gulp*…qualcosa non va?}
{357}{}{Guarda, per favore…non voglio guai. Mi fermo solo un giorno, in citta'.}
{358}{}{Guarda, per favore…non voglio guai.}
{359}{}{Sei in vendita?}
{360}{}{Posso comprare i tuoi vestiti? Subito, intendo...}
{361}{}{Lo SAPEVO che dovevo farmi la barba, stamattina.}
{362}{}{Vieni a chiacchierare con me per un po', tettine d'oro.}
{363}{}{Dai, labbra di burro… cammina con me.}
{364}{}{Sei una tipetta sveglia, vero?}
{365}{}{Per te sarei pronto a farmi persino un bagno.}
{366}{}{Ho un bel regalino per te... proprio qui.}
{367}{}{Ma quelle gambe non finiscono mai?}
{368}{}{Ballerai per noi, stanotte?}
{369}{}{Scusatemi. Devo andare al bagno per, er, pettinarmi un attimo.}
{370}{}{Vorrei comprare le tue mutande.}
{371}{}{Mi piacerebbe annusare il tuo tanga.}
{372}{}{Sei davvero una donna arrapante.}
{373}{}{Che tu possa fottermi all'istante se mi sbaglio, cara, ma non e' che vorresti darmi un bacetto?}
{374}{}{Cazzo. Tutte quelle curve e io sono senza freni.}
{375}{}{Sai cosa ti starebbe bene addosso? Io.}
{376}{}{Le tue mutandine forse non saranno la cosa migliore su questa terra, ma, diamine, ci sono davvero vicine...}

{503}{}{!}
{504}{}{! Sei grande! Sei GRANDE!}
{505}{}{! Sei il MIGLIORE!} ###???You are so MONEY
{625}{}{!}
{630}{}{! Sei grande! Sei GRANDE!}
{631}{}{! Sei la MIGLIORE!}