# QUICK LOOK
{100}{}{Vedi un buttafuori del casino'.}

# LOOK
{150}{}{Vedi un buttafuori del casino'. E' ENORME.}
{151}{}{Vedi un buttafuori del casino'. Sembra enorme. E arrabbiato.}
{152}{}{Vedi un buttafuori del casino'. Ti guarda con sospetto.}
{153}{}{Vedi un buttafuori del casino'. Pensavi che solo i mutanti potessero essere cosi' grossi.}

# 1. FLOAT DIALOGUE: POWER ARMOR
{200}{}{Uh… devi toglierti quell'armatura... beh... come non detto.}
{201}{}{Uh, signore…o signora… dovrebbe togliersi quell'armatura...uh, come non detto.}
{202}{}{Signore…signora…non puo' indossare quell'armatura mentre si trova nel casino'...uh, a meno che lei non lo desideri. Lasciamo stare.}

# 2. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, SNEAK
{205}{}{Uh, perche' si muove cosi' silenziosamente, signore?}
{206}{}{Uh, e' in missione segreta, signore?}

# 3. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, SNEAK
{210}{}{Uh, perche' si muove cosi' silenziosamente, signora?}
{211}{}{Uh, e' in missione segreta, signora?}

# 4. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, NIGHT
{215}{}{Buonasera, signore.}
{216}{}{'sera, signore.}

# 5. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, NIGHT
{220}{}{Buonasera, signora.}
{221}{}{'sera, signora.}

# 6. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO
{225}{}{Buongiorno, signore.}

# 7. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO
{230}{}{Buongiorno, signora.}

# 8. FLOAT DIALOGUE: MALE, MADE MAN, NOT SAME CASINO
{235}{}{Amico, stai entrando nel casino' sbagliato.}
{236}{}{Farai meglio ad andartene. Subito.}
{237}{}{Questo non e' il posto giusto dove mettere in gioco la tua vita. Sara' meglio che tu te ne vada.}

# 9. FLOAT DIALOGUE: FEMALE, MADE MAN, NOT SAME CASINO
{240}{}{Troia, stai entrando nel casino' sbagliato.}
{241}{}{Farai meglio ad andartene. Subito.}
{242}{}{Questo non e' il posto giusto dove mettere in gioco la tua vita. Sara' meglio che tu te ne vada.}

# 10. FLOAT DIALOGUE: MALE, PRIZEFIGHTER/PORN STAR (ARMED)
{245}{}{Signore, mi dispiace ma deve mettere via quell'arma.}

# 11. FLOAT DIALOGUE: FEMALE, PRIZEFIGHTER (ARMED)
{250}{}{Signora, mi dispiace ma deve mettere via quell'arma.}

# 12. FLOAT DIALOGUE: PORN STAR, FEMALE (ARMED)
{255}{}{Dolcezza, mi dispiace, ma non puoi portare armi all'interno del casino'. Eh-eh... sei gia' fatale cosi' come sei.}

# 13. FLOAT DIALOGUE: PORN STAR, FEMALE (SNEAK)
{260}{}{Dolcezza, con un corpo come quello, non riusciresti a passare inosservata nemmeno in un ospizio per ciechi.}

# 14. FLOAT DIALOGUE: MALE, NO REP (ARMED)
{265}{}{Selvaggio, farai meglio a mettere via quell'arma IMMEDIATAMENTE.}

# 15. FLOAT DIALOGUE: MALE, NO REP (SNEAK)
{270}{}{Selvaggio, farai meglio a smetterla di muoverti furtivamente... SUBITO.}

# 16. MYRON, MORDINO
{275}{}{Ehi, ehi…Myron! Era da un po' che non ti si vedeva fuori dal laboratorio.}
{276}{}{Sei qui per provare un po' della nuova merce, Myron?}
{277}{}{Ehi! Entra, Myron.}

# 17. MARCUS
{280}{}{Niente mutanti. Lui aspetta fuori.}
{281}{}{Lascia il tuo animaletto fuori, amico dei mutanti.}
{282}{}{Quel mostro mutante non puo' entrare.}

# 18. ROBOBRAIN
{285}{}{Niente droidi.}
{286}{}{Qui non serviamo i droidi.}
{287}{}{Niente droidi. Loro se ne stanno fuori.}

# 19. CLICK DIALOGUES: MADE MAN, SAME CASINO
{290}{}{Benvenuto al casino', signore.}
{291}{}{Bel vestito, signore.}
{292}{}{Oggi nessun problema, signore.}
{293}{}{Uh, c'e' qualche problema, signore? Oppure e' venuto solo a farci visita?}
{294}{}{Tommy the Balls le manda i suoi saluti.}
{295}{}{Puo' mettere una buona parola con il boss per me?}
{296}{}{Benvenuta al casino', signora.}
{297}{}{Bel vestito, signora.}
{298}{}{Oggi nessun problema, signora.}
{299}{}{Uh, c'e' qualche problema, signora? Oppure e' venuta solo a farci visita?}

# 21. CLICK DIALOGUE: MALE, PRIZEFIGHTER/PORN STAR
{310}{}{Benvenuto al casino', signore.}
{311}{}{Bel vestito, signore.}
{312}{}{Quand'e' il suo prossimo incontro, signore?}

# 22. CLICK DIALOGUE: FEMALE, PRIZEFIGHTER
{315}{}{Benvenuta al casino', signora.}
{316}{}{Bel vestito, signora.}
{317}{}{Quand'e' il suo prossimo incontro, signora?}

# 24. CLICK DIALOGUE: FEMALE, PORN STAR
{320}{}{Quand'e' che verrai a trovarmi?}
{321}{}{Ehi, benvenuta al casino'! Ballerai, stanotte?}
{322}{}{Hai un corpo da favola, dolcezza.}
{323}{}{Donna Fortuna s'ingelosira' se continui a farti vedere da queste parti.}
{324}{}{Ho sentito che Tommy the Balls vorrebbe proporti di fare un provino per lui in forma privata.} ###???private screening

# 25. CLICK DIALOGUE: MALE, NO REP
{330}{}{Il casino' e' all'interno. Non parlare con me.}
{331}{}{Il casino' e' all'INTERNO. IN-TER-NO. Stupidi selvaggi...}

# 26. CLICK DIALOGUE: FEMALE, NO REP (CUTE/UGLY)
{335}{}{Va' a sculettare davanti a qualcun altro, selvaggia.}
{336}{}{Il casino' e' all'INTERNO. IN-TER-NO. Stupidi selvaggi.}
{337}{}{Adesso non ho tempo di guardare il culo ad una selvaggia. Sparisci.}
{338}{}{Smamma, muso da cane. Sto lavorando.}
{339}{}{Va' ad abbaiare con qualcuno piu' ubriaco di me, muso da cane.}

# 28. FLOAT DIALOGUE: FLAG: ENCLAVE DESTROYED IS TRUE
{345}{}{Non dovrei chiacchierare mentre sono in servizio, ma sono contento che tu abbia distrutto l'Enclave.}
{346}{}{Sei grande, selvaggio. Dopo aver salvato il mondo, che ne diresti adesso di riposarti e di divertirti un po'?}
{347}{}{Mi hanno detto che Tommy the Balls ti sta cercando. Occhio.}

# 29. CLICK DIALOGUE: FLAG: ENCLAVE DESTROYED IS TRUE
{350}{}{Hai avuto davvero un bel fegato per riuscire a sconfiggere l'Enclave a quel modo.}
{351}{}{Immagino che eliminare l'Enclave nel modo in cui l'hai fatto tu abbia richiesto piu' fegato di quanto ne abbiano tutti gli abitanti di New Reno messi insieme.}
{352}{}{Distruggere l'Enclave ti rende un duro quasi alla pari con Tommy the Balls.}
{353}{}{Non dovrei chiacchierare mentre sono in servizio, ma sono contento che tu abbia distrutto l'Enclave.}
{354}{}{Sei grande, selvaggia. Dopo aver salvato il mondo, che ne diresti adesso di riposarti e di divertirti un po'?}
{355}{}{Devi avere due palle di bronzo per essere riuscita a distruggere l'Enclave a quel modo. Beh, non PALLE in senso letterale... sono sicuro che hai capito cosa intendo.}
{356}{}{Zucchero, immagino che eliminare l'Enclave nel modo in cui l'hai fatto tu abbia richiesto piu' fegato di quanto ne abbiano tutti gli abitanti di New Reno messi insieme.}
{357}{}{Credi che ti potrebbe piacere un tipo come me? Voglio dire: non sono uno in grado di salvare il mondo, ma sono piuttosto forte e ho un buon cuore.}

# 30. FLOAT/CLICK DIALOGUE: LENNY
{360}{}{Se quel ghoul entra qui dentro, morira' una seconda volta.}
{361}{}{Il ghoul rimane fuori.}
{362}{}{I ghoul non sono ammessi qui. Riportalo a Gecko, dove quelli come lui devono stare.}