# 0. QUICK LOOK

# 0. LOOK
{150}{}{Vedi un giovane alto, con i capelli alla mohicana. E' coperto di catene e cuoio.} ###??? mohawk
{151}{}{Vedi Chris Wright.}
{152}{}{Vedi Chris Wright. Sembra essere annoiato a morte.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Ehi! }
{201}{}{Sei grande, }
{202}{}{Sei un maranza, }
{203}{}{::Esulta::}
{204}{}{::Applaude::}
{205}{}{::Fischia::}

# 2. FLOAT DIALOGUE: POWER ARMOR (WTG)
{215}{}{Come fai ad andare in bagno con quella roba addosso?}

# 3. FLOAT DIALOGUE: WARNING - PLAYER IS MADE MAN (WTG)
{220}{}{Ehila', }
{221}{}{Gran caldo oggi, eh, }
{222}{}{Ehila', }

# 4. FLOAT/CLICK (DAD IS DEAD) (WTG)
{230}{}{Non riesco ancora a credere che papa' sia morto. C'erano cosi' tante cose che avrei voluto dirgli…}

# 5. FLOAT/CLICK [MALE, MADE MAN, FA = WRIGHT, NORM] (WTG)
{235}{}{Smamma.}
{236}{}{Smamma. Faccio sul serio.}
{237}{}{Non ho niente da dirti.}

# 6. INTRO (NORMAL) (WTG)
{245}{}{Si'?}
{246}{}{Ehi! Come va, }
{1246}{}{? Ti trattano col dovuto rispetto? Ti serve qualcosa?}
{247}{}{Ehi, ti ringrazio per aver scoperto chi ha ucciso Richard, }
{248}{}{. Ti dobbiamo un grosso favore, e gli Wright i loro debiti li pagano sempre. Cosa posso fare per te?}
{249}{}{Mattah. Uomo e' Mattah!} ###???Mattah
{250}{}{Hoobajuube}
{251}{}{-Allontanati-}
{252}{}{Chi sei?}
{253}{}{Sto cercando lavoro. La famiglia Wright ha bisogno di un paio di braccia in piu'?}
{254}{}{Sai, ho incontrato tua madre.}
{255}{}{Puoi parlarmi di Richard?}
{256}{}{Niente. Scusa il disturbo.}
{257}{}{Puoi parlarmi della famiglia Wright?}

# 7.  RETARD (6)
{265}{}{Smamma, ritardato. Non ho tempo per usare il linguaggio dei gesti con te.}

# 8.  WHO ARE YOU? (6)
{275}{}{Sono Chris. Chris Wright. Della Famiglia Wright. Contento adesso?}
{277}{}{La Famiglia Wright? Cioe'?}
{278}{}{Chris Wright, eh? Sai, ho incontrato tua madre.}
{279}{}{Potresti dirmi cos'e' successo a tuo fratello Richard?}
{280}{}{Non molto. Scusa il disturbo.}

# 9. FAMILY WRIGHT? WHO'S THAT? (8, 10, 12)
{290}{}{Non hai mai sentito parlare della Famiglia *Wright*? Devi essere rimasto nel deserto un po' troppo a lungo. La Famiglia Wright e' la piu' grande famiglia criminale di New Reno. Presto domineremo questa citta'.}
{291}{}{Davvero? Sembra proprio che la famiglia Wright tenga le redini di tutto, qui. Avete bisogno di un paio di braccia in piu'?}
{292}{}{Veramente avevo l'impressione che fosse una delle famiglie piu' deboli... Voglio dire, vendono solo alcolici e non hanno un casino' ne' spacciano droga e i loro uomini sono pochi, confrontati con quelli delle altre famiglie.}
{293}{}{A proposito di famiglia, ho incontrato tua madre.}
{295}{}{Davvero? Molto interessante... beh, scusa, ma devo andare.}
{296}{}{La Famiglia Wright e' la piu' grande famiglia criminale di New Reno. Presto domineremo questa citta'.}

# 10. QUESTIONS (15, 16, 17, 18, 19, 20, 22, 25, 26, 28)
{305}{}{Ad esempio?}
{306}{}{Puoi parlarmi della famiglia Wright?}
{307}{}{La Famiglia Wright ha bisogno di un paio di braccia in piu'?}
{308}{}{Non molto tempo fa ho incontrato tua madre. E' una bella donna.}
{310}{}{No, nessun'altra domanda. Sara' meglio che vada.}

# 11. INTRO (SLAVER) (WTG)
{315}{}{(Il giovane ti squadra. I suoi occhi si fermano sul marchio che hai sulla fronte.) Bene, bene. (Ridacchia, poi ti sputa sui piedi.) Perche' non ti rendi utile e lo tiri su con la lingua, schiavista?}
{316}{}{(Il giovane ti squadra.) Bene, bene. (Ridacchia, poi ti sputa sui piedi.) Perche' non ti rendi utile e lo tiri su con la lingua, brutto pezzo di merda }
{317}{}{?}
{318}{}{-Prendilo a calci con lo stivale sul quale ha sputato-}
{320}{}{-Lascialo perdere. Per questa volta- }

# 12. I'M LOOKING FOR A JOB . . . [GOOD RESPONSE] (6, 8, 9, 10)
{325}{}{Beh, io… cioe', la famiglia Wright… la mia famiglia… potrebbe avere qualcosa da farti fare. Non ti prometto nulla, ma va' nella grande casa che c'e' subito a sud di qui, trova mio fratello Keith e digli che ti mando io. Mi chiamo Chris. Chris Wright.}
{326}{}{Uh, la famiglia Wright? Chi sono?}
{327}{}{Wright, eh? Ho incontrato tua madre.}
{329}{}{Grazie.}
{330}{}{Grazie. Posso farti qualche domanda?}

# 13. I'M LOOKING FOR A JOB . . . [BAD RESPONSE] (6, 8, 9, 10)
{335}{}{Nah... di solito non prendiamo nessuno che non sia della famiglia. Puoi provare a chiedere a Pa', giu' a casa, ma molto probabilmente ti dira' di no.}
{336}{}{D'accordo.}

# 14. I RAN INTO YOUR MOM (NORMAL) (6, 9, 10, 11, 12)
{345}{}{(Si irrigidisce.) *Magnifiiico*. Ha fatto la predica anche a te?}
{346}{}{Una specie. Non vuoi bene a tua madre?}
{347}{}{No. Di solito lo fa?}
{348}{}{Veramente no. Senti, sara' meglio che vada. }

# 15. I RAN INTO YOUR MOM (INSULT) (9, 16)
{355}{}{Cos'e', uno scherzo? Se e' cosi', ti sei dimenticato di aggiungere la parte divertente. Stai cercando di avere dei casini con la Famiglia Wright?}
{356}{}{Se sto cercando dei casini? No, sto solo cercando di farvi TUTTI SECCHI.}
{357}{}{No, scusa. Mi devo essere espresso male. Ascolta, avrei delle altre domande…}
{358}{}{No, assolutamente no. Adesso credo proprio di dover andare. }

# 16. DO YOU NOT LIKE YOUR MOM? (14)
{365}{}{(Alza le spalle.) Semplicemente non presta attenzione a quello che succede intorno a lei. Le voglio bene, certo, ma a volte e' piu' testarda di un mulo e piu' cieca di una talpa.}
{366}{}{Beh, non molto tempo fa, ha fatto dei casini con il nostro distillatore e ha mandato in malora l'intera distilleria, distruggendo la nostra fonte di reddito! Le voglio bene, certo, ma a volte e' piu' cieca di una talpa.}
{367}{}{Eh eh. E le assomiglia, anche.}
{368}{}{Cieca? Cosa vuoi dire?}
{369}{}{Oh. Avrei delle altre domande…}
{370}{}{Lo immagino. Senti, adesso devo andare. }

# 17. WHAT DO YOU MEAN? (16)
{380}{}{Va in giro a fare delle prediche sul peccato e robe del genere, ma non sa neppure cosa fa veramente nostro padre. O non lo sa, o fa finta di non saperlo.}
{381}{}{Cosa fa tuo padre?}
{382}{}{Hmmmm. Senti, avrei delle altre domande…}
{383}{}{Interessante. Beh, adesso devo andare. }

# 18. WHAT DOES YOUR DAD DO? (17)
{390}{}{Distilla alcol, si occupa degli affari sporchi, elimina le persone che cercano di fregarlo... le solite cose da famiglia, insomma. La mamma andrebbe fuori di testa se lo sapesse. E soprattutto se scoprisse questa distilleria.}
{391}{}{E quanto potrebbe arrabbiarsi?}

# 19. HOW PISSED? (18)
{400}{}{Probabilmente abbastanza da spaccare questo posto… come minimo. Poi darebbe a tutti noi una bella strigliata e ci obbligherebbe a lunghe giornate di preghiera. Eh. }
{401}{}{Interessante. Senti, avrei delle altre domande…}
{402}{}{Hmmmmm. Grazie. }

# 20. WHAT ABOUT RICHARD? (6, 8, 9, 10, 12)
{410}{}{Richard? L'hanno trovato morto in un fosso, come uno strafatto di Jet qualsiasi. Da quel che sappiamo, qualcuno deve averlo imbottito di droghe finche' non e' morto.}
{411}{}{"Qualcuno" gli avrebbe dato troppa droga? Come fate a dire che non e' morto di overdose perche' LUI ha preso troppa droga?}
{412}{}{Chi pensate possa averlo fatto?}
{413}{}{Mi dispiace. Avrei delle altre domande…}
{414}{}{Terribile. Senti, adesso devo andare. }

# 21. GAVE HIM TOO MUCH? (20)
{420}{}{Perche' era una ragazzo pulito… La mamma l'aveva cresciuto BENE. E se non sei d'accordo, tu ed io possiamo risolvere subito la questione, che ne dici?!} ###???Mom taught him THAT much
{421}{}{Non volevo insinuare nulla. Scusa se te ne ho parlato.}
{422}{}{Non puoi fare finta che l'idea che abbia preso la droga di sua volonta' sia campata in aria. Il Jet crea una forte dipendenza.}
{423}{}{Ascolta, *ragazzo*, se ci tieni alla pelle, smettila di prendertela a male ogni volta che una piccola verita' viene a galla e ti fa male.}
{425}{}{Non voglio guai. Me ne vado. }

# 22. I'M SORRY. I DIDN'T MEAN IT LIKE THAT (21)
{435}{}{Okay... beh, vedi di stare in guardia. Discorsi del genere farebbero arrabbiare qualsiasi Wright, percio' non andare in giro a dire certe fesserie, okay?}
{437}{}{Senti, RAGAZZO, vedi di non metterti contro uno come me. Se ci tieni alla pelle, smettila di prendertela a male ogni volta che una piccola verita' viene a galla e ti fa male.}
{438}{}{Scusa, non intendevo offendervi. Ascolta, avrei qualche altra domanda…}
{439}{}{Ho capito. Sara' meglio che vada. }

# 23. APOLOGY FAILED (15, 21, 22)
{445}{}{Sparisci. Non ho nient'altro da dirti.}
{446}{}{Aspetta, ho solo un'altra domanda da farti…}
{447}{}{Me ne vado, me ne vado. }

# 24. IMPLY RICH KEPT TAKING DRUGS (15, 21, 22, 23)
{455}{}{(Chris ti fissa per un attimo, poi si getta contro di te!)}
{456}{}{Allora e' COSI' che vogliamo METTERLA, eh? D'ACCORDO, DIAMOCI DENTRO, BRUTTO STR -- }

# 25. WHO DO YOU THINK DID IT? (20, 21)
{465}{}{Io credo che siano stati i Mordino; probabilmente uno dei loro spacciatori, se non addirittura un membro della famiglia. Quei bastardi producono tonnellate di Jet.}
{466}{}{Ho capito. Senti, avrei delle altre domande…}
{467}{}{Quale spacciatore pensi possa aver venduto il Jet a Richard?}
{468}{}{Capisco. Sara' meglio che vada. }

# 26. WHO DO YOU THINK SOLD IT? (25)
{475}{}{Potrebbe essere stato chiunque: Jimmy J, quel fottuto sfregiato all'angolo di Virgin Street, oppure Renesco "the Rocketman", quel vecchio e viscido merdoso che vende il Jet accanto all'armeria nel West Side.}
{476}{}{Ci sono altri spacciatori?}

# 27. WHO DO YOU THINK SOLD IT? (28)
{485}{}{Ehi, amico, GRAZIE. }
{486}{}{Ehi, ragazza mia, GRAZIE. }
{487}{}{Hai scoperto chi ha ucciso mio fratello, e tutta la Famiglia Wright ti ringraziera', stanne certo. E non sara' un ringraziamento da poco, credimi.}
{488}{}{Ho capito. Ci becchiamo dopo, Chris. }

# 28. ANYBODY ELSE? (26)
{495}{}{Anche Jules, all'entrata della citta', vende il Jet, ma di solito i suoi clienti sono turisti... poi c'e' Little Jesus Mordino: potrebbe aver venduto la droga a mio fratello mentre Rich era fuori da solo. Lo troverai al Desperado.}
{497}{}{Jimmy J lo Sfregiato, Renesco "the Rocketman", Jules e Little Jesus… Andro' a parlare con loro. Grazie delle informazioni, Chris. }


# end lines
{1200}{}{! Gliel'hai proprio fatta vedere, a quell'Enclave!}
{1201}{}{! Sei forte!}
{1202}{}{!}
{1220}{}{. Cos'hai fatto di bello?}
{1221}{}{?}
{1222}{}{. Come vanno le cose?}