# 0. LOOK
{150}{}{Vedi un meccanico coperto di grasso.}
{151}{}{Vedi un meccanico, o, come preferisce farsi chiamare, uno dei "chop shop boyz".}
{152}{}{Vedi un meccanico dall'aspetto meschino. Si fa fatica a distinguere la sua fisionomia sotto tutto quel grasso e olio.}

# 1. FLOAT OR CLICK DIALOGUES [POWER ARMOR] (WTG)
{200}{}{Oh, cazzo. *Gulp* Guardate cos'e' appena entrato.}
{201}{}{Beh, che mi venga un colpo se quello non e' Mr. Macinacaffe'.}
{202}{}{C'e' nessuno in quel coso?}
{203}{}{Possiamo portarle qualcosa? Una birra? Dell'acqua? Un dolcetto?}
{204}{}{Spero vada tutto bene, uh, signore…o signora... Qualunque cosa ci sia la' dentro.}
{205}{}{Se qualcosa non va, il responsabile e' T-Ray. Io andrei a parlare con lui.}
{206}{}{E' per caso un nuovo tipo di automobile?}
{207}{}{Non vogliamo guai.}
{208}{}{Forse sei venuto qui per parlare con T-Ray. E' nel retro.}

# 2. FLOAT/CLICK TEXT [PORN STAR/CHR > 5, FEMALE] (WTG)
{220}{}{Beh, ehila', signorinella. Le tue performance sono sempre memorabili.}
{221}{}{Wow. Non abbiamo molti visitatori da queste parti. Cosa possiamo fare per lei, Miss }
{5221}{}{?}
{222}{}{Come fai a mettere le gambe sopra la testa?}
{223}{}{Quelle tette sono naturali? Posso provare?}
{224}{}{Ti sarebbe troppo di disturbo darmi una controllatina sotto al cofano?}
{225}{}{Aw, diavolo, ho un aspetto da schifo... proprio adesso. Non faccia caso al grasso, miss.}
{226}{}{Sei in cerca di nuovi talenti? T-Ray e' nel retro, quindi non serve che vai la'.}
{227}{}{Lo sapevo che oggi dovevo farmi un bagno…}
{228}{}{Vuole che le controlli l'olio? Eh-heh.}
{229}{}{Vuoi vedere la mia chiave inglese?}
{230}{}{::Fischia::}
{231}{}{Diamine. Tutte quelle curve e io non ho freni.}
{232}{}{Beh, ehila', signorinella.}
{233}{}{Wow. Non abbiamo molti visitatori da queste parti. Cosa possiamo fare per lei, miss?}
{234}{}{Sei in cerca di un amante bollente? T-Ray e' nel retro, quindi non serve che vai la'.}

# 3. FLOAT/CLICK DIALOGUES [PRIZEFIGHTER] (WTG)
{245}{}{Ti ho visto combattere sul ring. Che gran gancio destro che hai sferrato.}
{246}{}{Sei sicuro di vincere il prossimo incontro? Ho puntato 30 dollari su di te.}
{247}{}{Non sembri poi cosi' forte, per essere un campione.}
{248}{}{Quante flessioni fai, al giorno?}
{249}{}{Dov'e' che ti alleni?}
{250}{}{Occhio al Masticatore. Ha una passione per le orecchie.}
{251}{}{Vuoi una birra? Di solito le mettiamo da parte per quando lavoriamo.}
{252}{}{T-Ray dice che non sei poi cosi' forte. Ti do 5 dollari se vai da lui e gli tiri un pugno.}
{253}{}{T-Ray dice che hai la mascella di cristallo. Lui sta nella stanza sul retro, se ci vuoi parlare.}
{254}{}{Il Masticatore e' un vero codardo. Uh, questo non devi dirglielo, pero'.}

# 4. FLOAT/CLICK DIALOGUES [MADE MAN] (WTG)
{265}{}{Spero che non ci siano problemi, signora.}
{266}{}{Non volevamo mancarle di rispetto, signora.}
{267}{}{Oh, cazzo. *Gulp* Guardate chi e' entrato.}
{268}{}{Cosa possiamo fare per lei, }
{5268}{}{?}
{269}{}{Possiamo portarle qualcosa? Una birra? Un po' d'acqua? Un dolcetto?}
{270}{}{Qualunque sia il problema, il responsabile e' T-Ray. Vada a parlare con lui.}
{271}{}{Porti i nostri saluti al suo capo.}
{272}{}{Forse e' qui per vedere T-Ray. Lo puo' trovare nel retrobottega.}
{273}{}{Spero che non ci siano problemi, signore.}
{274}{}{Non volevamo mancarle di rispetto, signore.}

# 5. FLOAT OR CLICK DIALOGUES [CAR RECOVERED] (WTG)
{300}{}{Siamo mortificati per quel malinteso con la Highwayman.}
{301}{}{Non sapevamo che la Highwayman fosse sua.}
{302}{}{Si', la Highwayman non e' una brutta macchina, ma preferisco le Omni.}
{303}{}{Vuole forse vendere la sua Highwayman?}
{304}{}{Vai, fulmine lubrificato, vai.}
{305}{}{Grasso e' la parola che mi piace sentire…dum dum dum dum…} ###???Grease is the word that I heard
{306}{}{La Highwayman e' una bella macchina; quelli della Chryslus sapevano davvero come farle.}
{307}{}{T-Ray sta "lavorando" nella stanza sul retro. Pigro bastardo.}
{308}{}{Sono stufo di fare anche il lavoro di T-Ray.} ###???I'm sick of picking up T-Ray's slack
{309}{}{T-Ray ha di nuovo messo gli occhi sulla mia ragazza.}
{310}{}{T-Ray e' andato a letto con mia sorella. E con mia madre. E con il mio cane.}
{311}{}{T-Ray e' piu' arrapato di un mandrillo con otto testicoli.} ###???'s hornier than a four-headed goat
{312}{}{T-Ray e' nel retro. E' al telefono.}
{313}{}{Il motore e' ancora in buone condizioni.}
{314}{}{All'interno c'e' una puzza... sembra che qualcuno ci abbia riversato dentro un carico di letame.}
{315}{}{Gli interni puzzano di gecko.}
{316}{}{Non e' una brutta macchina, ma io preferisco le Omni.}
{317}{}{La Highwayman e' dotata di un sistema completamente analogico, 800 e piu' cavalli e va da 0 a 60 miglia orarie in meno di un secondo.}
{318}{}{Se e' veloce? La Highwayman va da 0 a 60 miglia orarie in meno di un secondo.}
{319}{}{La Highwayman e' davvero potente: 800 e piu' cavalli.}
{320}{}{Sei sicuro di essere nel posto giusto?}
{321}{}{Quasi mi dispiace per quell'idiota che ha lasciato in giro questa Highwayman.}
{322}{}{La Highwayman ha un sistema completamente analogico e nessun computer. Niente robe strane, su questa macchina. Nossignore.}

# 6. FLOAT DIALOGUES [WARNING] (WTG)
{330}{}{Togli le mani o le mani te le togliamo noi. Capito?}
{331}{}{Sta' LONTANO da quell'auto.}
{332}{}{La tua vita non vale molto piu' di quella macchina. Toccala di nuovo e te lo dimostrero'.}