# 0. QUICK LOOK
{100}{}{Vedi Chris Wright.}

# 0. LOOK
{150}{}{Vedi un ragazzo molto alto con i capelli alla mohicana. Ha addosso un quantita' notevole di catene e di cuoio.}
{151}{}{Vedi Chris Wright.}
{152}{}{Vedi Chris Wright. Sembra annoiarsi a morte.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Ehi! }
{201}{}{Che ganzo, }
{202}{}{Sei un maranza, }
{203}{}{::Esulta::}
{204}{}{::Applaude::}
{205}{}{::Fischia::}

# 2. FLOAT DIALOGUE: POWER ARMOR (WTG)
{215}{}{Come fai ad andare al bagno con quella roba addosso?}

# 3. FLOAT DIALOGUE: WARNING - PLAYER IS MADE MAN (WTG)
{220}{}{Ehila', }
{221}{}{Che caldo infernale, eh, }
{222}{}{Ehila', }

# 4. FLOAT/CLICK (DAD IS DEAD) (WTG)
{230}{}{Non riesco a credere che papa' sia morto. Avrei voluto dirgli cosi' tante cose…}

# 5. FLOAT/CLICK [MALE, MADE MAN, FA = WRIGHT, NORM] (WTG)
{235}{}{Smamma.}
{236}{}{Smamma. Faccio sul serio.}
{237}{}{Non ho nulla da dirti.}

# 6. INTRO (NORMAL) (WTG)
{245}{}{Si'?}
{246}{}{Ehi! Come va, }
{1246}{}{? Ti trattano tutti col dovuto rispetto? Ti serve qualcosa?}
{247}{}{Ehi, ti ringrazio per aver scoperto chi ha ucciso Richard, }
{248}{}{. Ti dobbiamo un grosso favore, e gli Wright onorano sempre i loro debiti. Cosa posso fare per te?}
{249}{}{Mattah. Uomo e' Mattah!}
{250}{}{Hoobajuube}
{251}{}{-Allontanati-}
{252}{}{Chi sei?}
{253}{}{Veramente, si'. Sto cercando un lavoro. La Family Wright ha bisogno di un paio di braccia in piu'?}
{254}{}{Ho conosciuto tua mamma, sai?}
{255}{}{Puoi parlarmi di Richard?}
{256}{}{Niente, grazie. Scusa il disturbo.}

# 7.  RETARD (6)
{265}{}{Smamma, ritardato. Non ho voglia ne' tempo di usare il linguaggio dei segni con te.}
{266}{}{-Allontanati-}

# 8.  WHO ARE YOU? (6)
{275}{}{Sono Chris. Chris Wright. Della Famiglia Wright. Sei felice d'avermelo chiesto?}
{276}{}{Veramente, si'. Sto cercando un lavoro. La Family Wright ha bisogno di un paio di braccia in piu'?}
{277}{}{Famiglia Wright? E chi sarebbero?}
{278}{}{Chris Wright, eh? Ho conosciuto tua mamma, sai?}
{279}{}{Potresti dirmi cos'e' successo a tuo fratello Richard?}
{280}{}{Non molto. Scusa il disturbo.}

# 9. FAMILY WRIGHT? WHO'S THAT? (8, 10, 12)
{290}{}{Non hai mai sentito parlare della Famiglia Wright? Devi aver passato troppo tempo nel deserto, allora. Gli Wright sono la piu' grossa famiglia criminale di Reno. Presto domineremo questa citta'.}
{291}{}{Davvero? Sembra proprio che la famiglia Wright abbia tutte le carte in regola. Avete bisogno di un paio di braccia in piu'?}
{292}{}{Veramente avevo l'impressione che fosse una delle famiglie piu' deboli... Voglio dire, vendono solo alcol e non hanno un casino ne' spacciano droga. Come se non bastasse non sono numerosi quanto le altre famiglie.}
{293}{}{A proposito di famiglia... ho conosciuto tua madre.}
{294}{}{Puoi dirmi cos'e' successo a tuo fratello Richard?}
{295}{}{Davvero? Molto interessante... beh, senti, adesso devo andare.}

# 10. QUESTIONS (15, 16, 17, 18, 19, 20, 22, 25, 26, 28)
{305}{}{Ad esempio?}
{306}{}{Puoi dirmi qualcosa a proposito della famiglia Wright?}
{307}{}{La Family Wright ha bisogno di un paio di braccia in piu'?}
{308}{}{Ho conosciuto tua madre, non molto tempo fa. E' una bella signora.}
{309}{}{Puoi dirmi cos'e' successo a tuo fratello Richard?}
{310}{}{No, nessun'altra domanda. Sara' meglio che vada.}

# 11. INTRO (SLAVER) (WTG)
{315}{}{(Il giovane si gira verso di te, ti guarda dall'alto in basso. I suoi occhi si fermano sul marchio che hai sulla fronte.) Guarda un po' chi abbiamo qui... (Sogghigna, poi sputa ai tuoi piedi) Perche' non ti rendi utile leccando via quello sputo da terra, schiavista?}
{316}{}{(Il giovane si gira verso di te e ti guarda dall'alto in basso.) Guarda un po' chi abbiamo qui... (Sogghigna, poi sputa ai tuoi piedi) Perche' non ti rendi utile leccando via quello sputo da terra, brutto pezzo di merda [FA]?}
{317}{}{Tiragli un calcio con lo stivale sul quale ha sputato.}
{318}{}{-Allontanati- }
{319}{}{Ignoralo. Per questa volta. }

# 12. I'M LOOKING FOR A JOB . . . [GOOD RESPONSE] (6, 8, 9, 10)
{325}{}{Beh…forse io…cioe', la famiglia Wright…la mia famiglia…potrebbe avere bisogno di te. Non prometto nulla, ma... prova ad andare nella grande casa subito a sud di qui, trova mio fratello Keith e digli che ti mando io. Io mi chiamo Chris. Chris Wright.}
{326}{}{Uh, la famiglia Wright? E chi sarebbero?}
{327}{}{Wright, eh? Ho conosciuto tua madre.}
{328}{}{Puoi dirmi cos'e' successo a tuo fratello Richard?}
{329}{}{Grazie. Vado subito a parlare con lui.}

# 13. I'M LOOKING FOR A JOB . . . [BAD RESPONSE] (6, 8, 9, 10)
{335}{}{Nah, non credo proprio che abbiamo bisogno di altra gente. Quasi tutte le famiglie della citta' sono praticamente al completo.} ###??? Most of the families in town are pretty close-knit
{336}{}{D'accordo.}

# 14. I RAN INTO YOUR MOM (NORMAL) (6, 9, 10, 11, 12)
{345}{}{Oh, magnifico. Ha fatto la predica anche a te?}
{346}{}{Una specie. Non vuoi bene a tua madre?}
{347}{}{No. Di solito la fa?}
{348}{}{Veramente no. Scusa, adesso devo proprio andare. }

# 15. I RAN INTO YOUR MOM (INSULT) (9, 16)
{355}{}{Cos'e' questo? Uno *scherzo*? Se e' cosi', sappi che e' molto lontano dall'essere divertente. Con la Famiglia Wright non si scherza, capito volpone?}
{356}{}{Scherzare? No, sono dannatamente *serio*.}
{357}{}{Si', mi dispiace. Non intendevo dire nulla di male. Senti, avrei delle altre domande…}
{358}{}{Si', alla perfezione. Credo sia meglio che me ne vada.}

# 16. DO YOU NOT LIKE YOUR MOM? (14)
{365}{}{(Alza le spalle.) Semplicemente non presta attenzione a quello che succede intorno a lei. Le voglio bene, certo, ma a volte e' piu' testarda di un mulo e piu' cieca di una talpa.}
{366}{}{Beh, non molto tempo fa, ha fatto dei casini con il nostro distillatore e ha mandato in malora l'intera distilleria, mandando all'aria i nostri affari! Le voglio bene, certo, ma ha volte e' piu' cieca di una talpa.} ###???she charged into our alcohol still here and busted up the place, destroying our entire cash crop
{367}{}{Eh eh. E le assomiglia, anche.}
{368}{}{Cieca? Cosa vuoi dire?}
{369}{}{Oh. Avrei delle altre domande…}
{370}{}{Lo immagino. Beh, adesso devo andare. }

# 17. WHAT DO YOU MEAN? (16)
{380}{}{Va in giro a fare delle prediche sul peccato e robe del genere, ma non sa neppure cosa fa veramente nostro padre. O non lo sa, o fa finta di non saperlo.}
{381}{}{Cosa fa tuo padre?}
{382}{}{Hmmmm. Senti, avrei delle altre domande…}
{383}{}{Interessante. Beh, adesso devo andare. }

# 18. WHAT DOES YOUR DAD DO? (17)
{390}{}{Distilla alcol, si occupa degli affari sporchi, elimina le persone che cercano di fregarlo... le solite cose da famiglia. La mamma andrebbe fuori di testa se si accorgesse di quello che succede davvero. E soprattutto si arrabbierebbe se scoprisse questa distilleria.}
{391}{}{E quanto potrebbe arrabbiarsi?}
{392}{}{Hmmmm. Senti, avrei delle altre domande…}
{393}{}{Interessante. Beh, adesso devo andar. }

# 19. HOW PISSED? (18)
{400}{}{Probabilmente abbastanza da spaccare questo posto… come minimo. Poi darebbe a tutti noi una bella strigliata e ci obbligherebbe a lunghe giornate di preghiera. Eh. }
{401}{}{Interessante. Senti, avrei delle altre domande…}
{402}{}{Hmmmmm. Grazie. }

# 20. WHAT ABOUT RICHARD? (6, 8, 9, 10, 12)
{410}{}{Rich? Aw, l'hanno trovato morto in un fosso, come uno strafatto di Jet qualsiasi. Da quel che sappiamo, qualcuno deve averlo imbottito di droghe finche' non e' morto.}
{411}{}{'Qualcuno' gli ha dato troppa droga? Come fate a dire che non e' morto di overdose perche' LUI ha preso troppa droga?}
{412}{}{Chi pensate possa averlo fatto?}
{413}{}{Mi dispiace. Avrei delle altre domande…}
{414}{}{Terribile. Senti, adesso devo andare. }

# 21. GAVE HIM TOO MUCH? (20)
{420}{}{Cause he was a clean kid…Mom taught him THAT much. And if you feel like saying any different, maybe you and I
 should settle it right here.}
{421}{}{Non volevo insinuare nulla. Scusa se te ne ho parlato.}
{422}{}{Non puoi fare finta che l'idea che abbia preso la droga di sua volonta' sia campata in aria. Il Jet crea una forte dipendenza.}
{423}{}{Ascolta, *ragazzo*, se ci tieni alla pelle, smettila di prendertela a male ogni volta che una piccola verita' viene a galla e ti fa male.}
{424}{}{Chi pensate possa averlo fatto?}
{425}{}{Non voglio guai. Me ne vado. }

# 22. I'M SORRY. I DIDN'T MEAN IT LIKE THAT (21)
{435}{}{Certo... beh, vedi di stare in guardia. Discorsi del genere farebbero arrabbiare qualsiasi Wright, percio' non andare a in giro a dire simili fesserie, okay?}
{436}{}{Non puoi fare finta che l'idea che abbia preso la droga di sua volonta' sia campata in aria. Il Jet crea una forte dipendenza.}
{437}{}{Senti, RAGAZZO, non cercare di metterti contro uno come me. Se ci tieni alla pelle, smettila di prendertela a male ogni volta che una piccola verita' viene a galla e ti fa male.}
{438}{}{Scusa, non intendevo offendervi. Ascolta, avrei qualche altra domanda…}
{439}{}{Ho capito. Sara' meglio che vada. }

# 23. APOLOGY FAILED (15, 21, 22)
{445}{}{Sparisci. Non ho nient'altro da dirti.}
{446}{}{Aspetta, ho solo un'altra domanda da farti…}
{447}{}{Me ne vado, me ne vado. }

# 24. IMPLY RICH KEPT TAKING DRUGS (15, 21, 22, 23)
{455}{}{(Chris ti fissa per un attimo, poi si getta contro di te!)}
{456}{}{Allora e' COSI' che vogliamo METTERLA, eh? D'ACCORDO, DIAMOCI DENTRO, BRUTTO STR -- }

# 25. WHO DO YOU THINK DID IT? (20, 21)
{465}{}{Io credo siano stati i Mordino; probabilmente uno dei loro spacciatori, se non addirittura un membro della famiglia. Quei bastardi producono tonnellate di Jet.}
{466}{}{Ho capito. Senti, avrei delle altre domande…}
{467}{}{Quale spacciatore pensi possa aver venduto il Jet a Richard?}
{468}{}{Capisco. Sara' meglio che vada. }

# 26. WHO DO YOU THINK SOLD IT? (25)
{475}{}{Potrebbe essere stato chiunque: Jagged Jimmy J, quel fottuto sfregiato all'angolo di Virgin Street, o Renesco 'the Rocketman', quel vecchio e viscido merdoso che vende il Jet accanto all'armeria nel West Side.}
{476}{}{Ci sono altri spacciatori?}
{477}{}{Ho capito. Senti, avrei delle altre domande…}

# 27. WHO DO YOU THINK SOLD IT? (28)
{485}{}{Ehi, amico, GRAZIE. }
{486}{}{Ehi, ragazza mia, GRAZIE. }
{487}{}{Hai scoperto chi ha ucciso mio fratello, e tutta la Famiglia Wright ti ringraziera', stanne certo. E non sara' un ringraziamento da poco, credimi.}
{488}{}{Ho capito. Ci becchiamo dopo, Chris. }

# 28. ANYBODY ELSE? (26)
{495}{}{Anche Jules, all'entrata della citta', vende il Jet, ma di solito i suoi clienti sono turisti... poi c'e' Little Jesus Mordino: potrebbe aver venduto la droga a mio fratello mentre Rich era fuori da solo. Lo troverai al Desperado.}
{496}{}{Ho capito. Senti, avrei delle altre domande…}
{497}{}{Jagged Jimmy J, Renesco the Rocketman, Jules e Little Jesus… Andro' a parlare con loro. Grazie delle informazioni, Chris. }



# end lines
{1200}{}{! Gliel'hai proprio fatta vedere, a quell'Enclave!}
{1201}{}{! Sei forte!}
{1202}{}{!}
{1220}{}{. Cos'hai fatto di bello?}
{1221}{}{?}
{1222}{}{. Come vanno le cose?}