# 0. QUICK LOOK
{100}{}{Vedi uno dei Fratelli Corsican.}

# 0. LOOK
{150}{}{Vedi un uomo ben vestito che profuma di vaselina. Per qualche ragione, ti pare abbia un aspetto quasi da rettile.} ###???For some reason, he strikes you as faintly reptilian
{151}{}{Vedi Marty, uno dei Fratelli Corsican. I suoi capelli sono pettinati all'indietro, coperti di gel, e la sua faccia e' ricoperta da un sottile velo di sudore.}
{152}{}{Vedi Sid, uno dei Fratelli Corsican. Porta un parrucchino e indossa occhiali scuri.}

# 1. FALLOUT2 = ENCLAVE_DESTROYED (WTG)
{200}{}{Ehi, }
{201}{}{}
{202}{}{Yo, }

# 2. POWER ARMOR (WTG)
{210}{}{Come diavolo ci vai al bagno con quella roba addosso?}
{211}{}{E' un nuovo tipo di vibratore, quello?}
{212}{}{E' un nuovo tipo di preservativo integrale, quello?}

# 3. PORN STAR (WTG)
{220}{}{Sei piu' infuocato di un vulcano che sta passando un brutto quarto d'ora.}
{221}{}{Sei una stella. Una stella che ESPLODE.}
{222}{}{Sei una stella. Una stella che SPRUZZA... ehm... BRILLA.}
{223}{}{Sei una stella. Una stella PALPITANTE.}
{224}{}{Ogni tua performance vale almeno mille erezioni.}
{225}{}{}
{226}{}{Sei una stella. Una stella brillante.}
{227}{}{Ehi, bentornato!}
{228}{}{Vieni a fare due chiacchiere con me un secondo.}
{229}{}{Parliamo d'affari.}
{230}{}{Torna a trovarci!}
{231}{}{Sai cosa sto guardando? Sto guardando la donna piu' sexy del mondo intero.}
{232}{}{}
{233}{}{Ehi, bentornata, tettine d'oro!}

# 5. MADE MAN (WTG)
{245}{}{Uh-oh. Uno della Famiglia. State tutti in guardia.}
{246}{}{Salve, }

# 6. PRIZEFIGHTER (WTG)
{250}{}{Ehila', Ercole del sesso!}
{251}{}{Guardate quei pettorali. Facci qualche flessione.}
{252}{}{Hai mai pensato di far carriera nel giro, }
{253}{}{Posso farti recitare in un paio di scene, se vuoi. Pensaci, okay?}
{254}{}{Hai un bello stile di combattimento. Com'e' il tuo stile di accoppiamento?}
{255}{}{Qui sei sempre il benvenuto. Senti, se vuoi possiamo parlare d'affari...}
{256}{}{Ehi, }
{257}{}{Torna ancora!}
{258}{}{Continua cosi', Xena.}
{259}{}{Hai davvero un bel ventre piatto. Come una tavola da surf.}

# 8. SLAVER (WTG)
{270}{}{Siamo pieni, schiavista.}
{271}{}{Questi schiavi sono miei, schiavista. Bada a dove metti gli occhi.}

# 9. FLOAT/CLICK [COMPANION: ROBO-DOG] (WTG)
{275}{}{Uh, bel robo-cane, ma noi non giriamo quel genere di film. Per adesso.}
{276}{}{Quel robo-cane e' addestrato a non fare i suoi bisognini in casa, vero?}

# 10. FLOAT/CLICK [COMPANION: ROBOBRAIN] (WTG)
{280}{}{Whoa. Guardate le filettature sulle braccia di quel robot.} ###???Check out the treads on that bot
{281}{}{Quello e' per caso uno di quei vibratori robotici dei quali ho sentito parlare?}
{282}{}{Quel tuo robot sarebbe interessato a fare un film?}

# 11. FLOAT/CLICK [COMPANION: MARCUS] (WTG)
{290}{}{Senti, porta il tuo amico mutante fuori di qui. Non giriamo quel tipo di film, qua dentro.}
{291}{}{Francamente, penso che nessuna delle nostre attrici sarebbe in grado di occuparsi del tuo amico mutante.}
{292}{}{Abbiamo gia' girato un film con un mutante - il mutante si e' divorato tutte le attrici. E quando dico "divorato", lo intendo per davvero.}

# 12. FLOAT/CLICK [COMPANION: LENNY] (WTG)
{300}{}{K-risto! Porta via quel puzzone d'un ghoul prima che il tanfo si diffonda.}
{301}{}{Non ci interessano film con ghoul come protagonisti. Portalo fuori di qui.}
{302}{}{*Phewww* La puzza di quel ghoul e' infernale! Portate qui un deodorante per l'aria prima che svenga.}

# 13. FLOAT DIALOGUES (WTG)
{310}{}{Bene, le luci sono spente...}
{311}{}{Ma a chi volete che INTERESSI se in quella scena si vede la giraffa?!}
{312}{}{Potremmo concentrarci sul culo, per cortesia?}
{313}{}{Le riprese stanno durando troppo. Andremo sul lastrico a furia di pagare le assistenti...}
{314}{}{Vuole CHE COSA?!! Digli di fottersi, lui e quel brahmin che monta!}
{315}{}{Le cose andavano meglio, quando c'erano le protesi...}
{316}{}{I costi si fanno sempre piu' elevati.}
{317}{}{Amavo quel Diggler...}
{318}{}{Il ragazzo e' vera dinamite sessuale!}
{319}{}{NON daro' inizio alle riprese se rimani in quello stato.}
{320}{}{E' un missile! E' un razzo! E ancora deve spiccare il volo, Sid: ascolta quel che ti dico!}
{321}{}{Cazzo-lutamente!}
{322}{}{Di' a quel bastardo che puo' andarsene all'inferno!}
{323}{}{Ascolta, se quella ragazza dal culo magnifico si fa rivedere...}
{324}{}{Avevo chiesto piu' impegno.} ###??? Wham-bam-thank-you-ma'am
{325}{}{Se questa non le batte tutte...}
{326}{}{Non prendiamoci per il culo.} ###???No skin off my ass
{327}{}{Di' a quello stronzo figlio di puttana che...}
{328}{}{Beh, lui ha preso una scatola di scoiattoli di pezza e poi...} ###??? seam squirrels
{329}{}{Questo non e' semplice cinema. Questa e' *arte*.} ###??? MP. That's a *YP.*
{330}{}{20 minuti, baby.}
{331}{}{Vediamo... (Controlla il copione.) Entra Randy, lui e Sylvia lo fanno... Christy va al bagno, Peter la raggiunge, lo fanno. Entra Ron...}

# 14. INTRO (NORMAL) (WTG)
{345}{}{I Fratelli Corsican al vostro servizio... (Ti rivolge un'occhiata irritata, poi ti guarda un'altra volta.) Ehi... ma tu sei quello di prima - eri qui per il posto di assistente, giusto?}
{346}{}{I Fratelli Corsican al vostro servizio... (Ti rivolge un'occhiata irritata.) Ancora tu. Ascolta, ti interessa fare l'assistente o no?}
{347}{}{I Fratelli Corsican al vostro servizio... (Ti rivolge un'occhiata irritata, poi ti guarda un'altra volta.) Sei qui per il posto di assistente?}
{348}{}{I Fratelli Corsican al vostro servizio... (Ti rivolge un'occhiata irritata.) Sei qui per il posto di assistente?}
{349}{}{Me 'stente}
{350}{}{Me no stenta! Me forte!}
{351}{}{-Allontanati-}
{353}{}{Certamente.}
{354}{}{Veramente, e' mia moglie ad essere interessata.}
{356}{}{No. Sono qui per i soldi di Big Jesus Mordino.}
{357}{}{No. Scusa il disturbo.}
{358}{}{Nooooooo. Scusa il disturbo.}

# 15. ME fluff (UGLY) (14, 58)
{370}{}{D'accordo, ritardato. La paga e' di 5... er, 3 dollari a colpo. Adesso va' nel bagno e comincia a lucidare l'asta di quel tipo.}
{371}{}{Lucidare asta? Ma me servire stracci e --}
{372}{}{[Fai come ti dice.]}

# 16. SHAFT 2 (15)
{380}{}{Ti bastera' la lingua.}
{381}{}{Lingua! Ma come potere...}

# 17. SHAFT 3 (16)
{390}{}{Senti, hai presente l'asta che ogni uomo ha in mezzo alle gambe? Ti assicuro che basta la lingua per tirarla a lucido.}
{391}{}{-Vai a lucidare l'asta del tipo-}

# 18. ME fluff (GOOD-LOOKING) (14, 51, 54, 58)
{400}{}{Hmmmm. Quante flessioni fai al giorno?}
{401}{}{Hmmmm. Sei davvero tosta come sembri, tettine d'oro?}
{402}{}{Me flette}
{403}{}{Me no fa flessioni me si fa donne}
{404}{}{Me pettine d'oro}
{405}{}{Me tosta}

# 19. ME BENCH/ME NO DO BENCH (18)
{415}{}{Cerrrrrrto. Amico, so da dove vieni e so ESATTAMENTE dove stai andando. Che ne diresti di recitare?}
{416}{}{Cerrrrrrto. Tettine d'oro, so da dove vieni e so ESATTAMENTE dove stai andando. Che ne diresti di recitare?}
{417}{}{Me piace questo!}
{418}{}{Recitare come?}

# 20. ME LIKE STUFF (19)
{425}{}{Davvero? Anche a me piace! Abbiamo gia' cosi' tante cose in comune! Vedi, noi siamo uno studio cinematografico... qui noi creiamo la MAGIA. Tu...}
{426}{}{tu, amico, puoi essere PARTE di questa magia!}
{427}{}{tu, tettine d'oro, puoi essere PARTE di questa magia!}
{428}{}{Occhei}
{429}{}{Magia! Magia! Me piace magia!}

# 21. ACT LIKE WHAT (19)
{435}{}{Recitare come una BESTIA. Come un rinoceronte selvatico. Un animale selvaggio, nato soltanto per soddisfare i suoi desideri per la felicita' delle masse! MAGIA, BABY, MAGIA! E' di QUESTO che sto parlando!} ###???A primal animal, built only to harness his lust for the gratitude of the masses!
{436}{}{Recitare come una BESTIA. Come una pantera in calore. Un animale selvaggio, la cui ANIMA desidera soltanto eccitare i desideri delle masse! MAGIA, BABY, MAGIA! E' di QUESTO che sto parlando!}

# 22. MAGIC! MAGIC! ME LIKE MAGIC! (20, 21)
{445}{}{Eccellente! Adesso vediamo di fare un provino. Devo vedere come sai entrare nel "ruolo". }
{446}{}{Ci stai, amico?}
{447}{}{Ci stai, tettine d'oro?}
{448}{}{Oh-Kay}

# 23. OKEE-DOKEE!/SURE! (22, 44, 59)
{455}{}{Cominciamo subito, allora! Non c'e' tempo da perdere! Ehi! Qualcuno mi porti qualcosa di speciale! } ###???Somebody get me an extra
{456}{}{Okay, amico: e' tempo di brillare...}
{457}{}{Okay, tettine d'oro: e' tempo di brillare...}
{458}{}{[Fai come ti dice lo strano uomo.]}
{459}{}{Ci puoi scommettere. E non hai ancora visto NIENTE.}

# 24. POOR AGILITY (23)
{465}{}{Mi dispiace, amico, ma non sei abbastanza FLESSIBILE per quello che ci serve. Lavoraci su, e magari piu' avanti potremo parlare ancora d'affari, okay?}
{466}{}{Mi dispiace, tettine d'oro, ma non sei abbastanza FLESSIBILE per quello che ci serve. Lavoraci su, e magari piu' avanti potremo parlare ancora d'affari, okay?}
{467}{}{Me PIACE fare affari qui. Me TORNERA'.}
{468}{}{*Snffff* O-kay. *Snffff* Me sentire oggetto.}
{469}{}{Cerchero' di migliorare la mia agilita'. Sara' per un'altra volta.}
{470}{}{Forse tornero'. Dopo una doccia. Una lunga doccia.}

# 25. POOR CON (23)
{475}{}{Mi dispiace, amico... sei bellissimo ed anche abbastanza flessibile, e' solo che non hai la, ehm, resistenza che ci serve... Allenati un po', e poi, forse, potremo parlare ancora d'affari, okay?}
{476}{}{Mi dispiace, tettine d'oro... sei bellissima ed anche abbastanza flessibile, e' solo che non hai la, ehm, resistenza che ci serve... Allenati un po', e poi, forse, potremo parlare ancora d'affari, okay?}
{479}{}{Cerchero' di migliorare la mia resistenza. Sara' per un'altra volta.}

# 26. POOR SEX EXPERIENCE (23)
{485}{}{Mi dispiace, amico... sei bellissimo, sei flessibile, hai la resistenza di un brahmin, ma ti serve un po' piu' di esperienza in questo campo prima di poter lavorare con noi, okay? Non abbiamo tempo per insegnarti come si fa.}
{486}{}{Mi dispiace, tettine d'oro... sei bellissima, sei flessibile, hai la resistenza di un brahmin, ma ti serve un po' piu' di esperienza in questo campo prima di poter lavorare con noi, okay? Non abbiamo tempo per insegnarti come si fa, patatina.}
{489}{}{Cerchero' di aumentare la mia, ehm, esperienza. Sara' per un'altra volta.}

# 27. PLAYER IS A STAR! (23)
{495}{}{Amico, sei stato in-credibile. }
{496}{}{Tettine d'oro, sei stata in-credibile. }
{497}{}{La tua performance e' stata oro, puro oro di Reno! Una cosa del genere vale almeno un MIGLIAIO di erezioni! Che ne diresti di fare un film con noi? Dai, parliamone, baby, PARLIAMONE!}
{498}{}{Okeei... me parla con te. Me vuole fare questa cosa ancora e ancora.}
{499}{}{Uh-uh. Me vuole andare, ora. Me sente sporco dentro.}
{500}{}{Mi interessa. Il mio prezzo: 200 dollari a... botta.}
{501}{}{Mi interessa. Ma prima, alcune condizioni. Per prima cosa, io lavoro solo con partner PULITI, mi aspetto almeno 500 dollari a scena, il 20% delle royalties, e niente STRONZATE. Io sono una stella, e tuo lo sai.}
{503}{}{Puoi scordartelo. Mi serve una doccia. Una lunga doccia.}

# 28. OKEE DOKEE . . . ME TALK WITH YOU . . . (27, 29)
{515}{}{(Tira fuori un pezzo di carta dalla giacca e ti fa scrivere una "X" su di esso.) Fatto! La tua carriera comincia qui! Prima di tutto, ti servira' un nome d'arte; qualcosa che dica al mondo "Io sono una STAR". Hai qualche idea?}
{516}{}{(Tira fuori un pezzo di carta dalla giacca e te lo fa firmare.) Fatto! La tua carriera comincia qui! Prima di tutto, ti servira' un nome d'arte; qualcosa che dica al mondo "Io sono una STAR". Hai qualche idea?}
{517}{}{Okay - che ne dici di un altro nome?}

# 29. I'M INTERESTED, BUT . . . (SMART) (28)
{525}{}{Io...hmmmm...Io...hmmmm. Ascolta, posso anche concederti i 500 dollari, ma NIENTE ROYALTIES. Siamo intesi?}
{526}{}{D'accordo.}
{527}{}{Niente da fare. Ci vediamo.}
{528}{}{Niente royalties, niente }
{5528}{}{. Me ne vado da questo studio cinematografico di merda.}

# 30. INPUT LINE: X = NOT RECOGNIZED. (28)
{535}{}{D'accordo! "}
{5535}{}{"! Mi AGGRADA! Mi AGGRADA! E adesso... SI GIRA...}
{6535}{}{! Luci! Camera! Azione!}
{536}{}{Achtung! Achtung!}
{537}{}{[Ti dai da fare.]}

# 31. INPUT LINE: X = RON JEREMY. (28)
{545}{}{Ehm... non QUEL nome, 'kay? Evoca brutte sensazioni. Cioe', nessuno vuole vedere un attore con quel nome in un porno decente. Scegli un altro nome, eh?}
{546}{}{Okay...}
{547}{}{Ma PIACERE davvero quel nome.}
{548}{}{Ma a me piace davvero, quel nome.}

# 32. INPUT LINE: X = DIRK DIGGLER. (28)
{555}{}{Wow, QUESTO si' che e' un nome cosi' brillante e luminoso che ESPLODERA' per la sua immensa potenza! Ottima scelta, amico, ottima scelta. E adesso... si GIRA! Luci! Camera! Azione!}
{556}{}{QUESTO e' un nome che racchiude in se' storia e magia. Ottima scelta, amico, ottima scelta. E adesso... si GIRA! Luci! Camera! Azione!}
{557}{}{QUESTO e' un nome che porta in se' una carica magica. Ottima scelta, tettine d'oro, ottima scelta. E ora... si GIRA! Luci! Camera! Azione!}
{558}{}{Wow, QUESTO si' che e' un nome cosi' brillante e luminoso che ESPLODERA' per la sua immensa potenza! Ottima scelta, tettine d'oro, ottima scelta. E ora... si GIRA! Luci! Camera! Azione!}

# 33."FILMING" FADE. (30, 31, 32)
{565}{}{D'accordo! D'accordo! Gente, si comincia! Forza! Sveglia! Sei pronto?}
{566}{}{Me pronto.}
{567}{}{Io sono NATO pronto.}

# 34. FILMING DONE (STUPID) (33, 48)
{575}{}{Bene, mio vulcanico amico. Per oggi abbiamo finito. Una performance STELLARE! STELLARE! E quell'ultimo amplesso! Perfetto! Se vuoi fare un altro film, puoi tornare qui tra un mese, okay?}
{576}{}{Bene, tettine d'oro. Per oggi abbiamo finito. Una performance STELLARE! STELLARE! Se vuoi fare un altro film, puoi tornare qui tra un mese, okay?}
{577}{}{Okee... Ciao ciao.}

# 35. FILMING DONE (SMART) (33, 48)
{585}{}{Stop! Bene, amico. }
{586}{}{Stop! Bene, tettine d'oro. }
{587}{}{Grande interpretazione. Una performance STELLARE! }
{588}{}{E quell'amplesso! }
{589}{}{E quei grugniti di piacere! }
{590}{}{Perfetto! Ecco la tua parte: }
{591}{}{200 dollari. }
{592}{}{500 dollari. }
{593}{}{Se vuoi fare un altro film, puoi tornare qui tra un mese, okay?}
{594}{}{D'accordo.}

# 36. UH, WHAT'S A fluffER? (UGLY) (14, 58)
{610}{}{Mi prendi per il culo? Senti, se me lo chiedi vuol dire che NON SEI la persona adatta per questo lavoro. E adesso che vuoi?}
{612}{}{Un lavoro, eh? Bene, allora... io SONO un assistente. Il migliore della piazza.}
{613}{}{Um, nulla. Devo essere nel posto sbagliato.}

# 37. UH, WHAT'S A fluffER? (ATTRACTIVE) (14, 58)
{620}{}{Whoa, ma a cosa stavo pensando? Tu entri qua, sprizzando classe da tutti i pori, e io mi metto a dire cose senza senso come un idiota! Ascolta, amico: scusa per quello che ti ho detto prima. Senti, ehm, cerchi lavoro? Niente posti da assistente per te. Io parlo di RECITARE, capisci?}
{621}{}{Whoa, ma a cosa stavo pensando? Tu entri qua, sprizzando classe da tutti i pori, e io mi metto a dire cose senza senso come un idiota! Ascolta, tettine d'oro: scusa per quello che ti ho detto prima. Senti, ehm, cerchi lavoro? Niente posti da assistente per te. Io parlo di RECITARE, capisci?}
{622}{}{Per prima cosa, cos'e' questo posto?}
{623}{}{Se c'e' uno stipendio fisso, mi interessa.}

# 38. SURE AM. (UGLY) (14, 36, 40, 41, 42, 43)
{630}{}{D'accordo. Va' nel retro e comincia a lucidare un po' di "manici". Ecco la tua paga: 5 dollari.}
{631}{}{[Fa' come dice.]}
{632}{}{Um, veramente ho cambiato idea. No grazie. Sara' meglio che vada.}

# 39. MY SPOUSE IS. (14, 58)
{640}{}{La tua dolce meta', eh? Hmmmmm. D'accordo. Fallo andare nel retro e digli di cominciare a tirare a lucido i "manici". Ecco la tua paga: 3 dollari.}
{641}{}{Fa' come ti dice quest'uomo, Davin-tesoro. Cosi' la tua }
{5641}{}{ sara' orgogliosa di te.}
{642}{}{Fa' come ti dice, Miria cara. SUBITO.}

# 40. WHAT'S THIS PLACE? (14, 36, 37, 47, 48, 58, 59)
{650}{}{Questo posto? Dai, mi stai prendendo in giro? Ci troviamo al Golden Globes, uno studio CINEMATOGRAFICO, l'unico presente a Reno, e probabilmente l'UNICO ad essere rimasto ancora in piedi. Non riconosci nemmeno casa tua? Cosi' fai del male al mio povero cuore!}
{651}{}{Questo? Questo e' il Golden Globes, uno studio CINEMATOGRAFICO, amico, l'unico presente a Reno, e probabilmente l'UNICO al mondo ad essere ancora in piedi, capito? Ora: hai intenzione di sfinirmi con le tue chiacchiere, oppure vuoi un lavoro?}
{652}{}{Questo? Questo e' il Golden Globes, uno studio CINEMATOGRAFICO, tesoro, l'unico presente a Reno, e probabilmente l'UNICO al mondo ad essere ancora in piedi, capito? Ora: hai intenzione di sfinirmi con le tue chiacchiere, oppure vuoi un lavoro?}
{653}{}{Questo vecchio posto? Questo e' il Golden Globes, uno studio CINEMATOGRAFICO, probabilmente l'UNICO al mondo ad essere ancora in piedi. Ma basta parlare di questo posto... stai cercando lavoro, amico? Abbiamo BISOGNO di talenti come te.}
{654}{}{Questo vecchio posto? Questo e' il Golden Globes, uno studio CINEMATOGRAFICO, probabilmente l'UNICO al mondo ad essere ancora in piedi. Ma basta parlare di questo posto... stai cercando lavoro, tettine d'oro?}
{655}{}{Come fate a girare i film? Voglio dire, dai... avete bisogno di telecamere, pellicola, proiettori... dove potreste mai trovare tutta questa roba?}
{657}{}{No grazie. Devo andare.}
{658}{}{Volevo solo controllare. Mi sono sentito un po' svuotato, ultimamente.}

# 41. WHERE DO YOU GET THE STUFF (ATTRACTIVE) (40, 52, 55)
{670}{}{Siamo fortunati... NON abbiamo BISOGNO di quelle stronzate risalenti all'eta' della pietra. Siamo entrati in possesso un proiettore pornogra... ehm... OLOgrafico FUNZIONANTE.}
{671}{}{Davveeeeero? Quali sono le caratteristiche tecniche del proiettore?}
{672}{}{Capisco... beh, senti: mi interesserebbe un lavoro, se avete qualche posto per me.}
{673}{}{E' stato bello parlare con te, ma adesso devo andare.}

# 42. SPECS (41)
{680}{}{Beh... non abbiamo ancora raggiunto la capacita' massima del drive QEWB - ma posso dirti che dovrebbe essere un cubo di memoria ad alta densita' da 300 GB circa. Nonostante Winblows 57 si mangi il 70-75% dello spazio, possiamo girare film per almeno un centinaio d'anni, con quel cubo.}
{681}{}{E adesso dove si trova questo cubo? Posso vederlo?}
{683}{}{Wow. Sono un SACCO di porno. Credo che dovro' pensarci su per un po'.}

# 43. CUBE (42)
{690}{}{No, cerchiamo di non fare entrare nessuno nella sala di registrazione... tutti vogliono sempre dire la loro quando c'e' da montare un film. Inoltre, il cubo vale oro per noi - non vogliamo che gli accada qualcosa.}
{692}{}{Il ragionamento fila. Dio solo sa che cosa potrebbe farsene un ladro di quel cubo, se ci mettesse le mani sopra. Oh, vabbe'. Ciao!}

# 44. I'll TAKE A JOB . . . (ATTRACTIVE) (37, 40, 41, 42, 43)
{700}{}{Eccellente! Naturalmente dovro' prima scoprire di che pasta sei fatto: un piccolo provino per vedere se ci sai "fare". Ci stai, amico?}
{701}{}{Eccellente! Naturalmente dovro' prima scoprire di che pasta sei fatta: un piccolo provino per vedere se ci sai "fare". Ci stai, tettine d'oro?}
{702}{}{Certo.}
{703}{}{Uh, no grazie. Ho cambiato idea. Magari un'altra volta.}

# 45. FUCK OFF! (50)
{710}{}{Allora vattene subito da qui, insignificante pezzo di merda! Non abbiamo bisogno di te! Sparisci! Non farai piu' un porno in vita tua!}
{711}{}{Me no volere, comunque!}
{712}{}{Fottiti! Tu non sei il mio capo. Solo io sono il fottuto capo di }
{5712}{}{!}

# 46. BROS. PISSED (WTG)
{720}{}{Vattene da qui. Non ho niente da dirti.}
{721}{}{Tu ed io non abbiamo niente da dirci. Sparisci.}

# 47. PORN STAR, LESS THAN 30 DAYS (WTG)
{730}{}{Ehi, bentornato, }
{5730}{}{! Oggi non si gira; riprova tra qualche giorno. }
{732}{}{Potresti parlarmi un po' dello studio?}
{733}{}{Sono felice che tu l'abbia detto. Vedi, sono qui per i soldi di Big Jesus Mordino.}
{734}{}{D'accordo. Tornero' presto.}

{735}{}{(Ti fa l'occhiolino.) Sei una stella dorata, baby, nient'altro che una stella!}

# 48. PORN STAR, MORE THAN 30 DAYS (WTG)
{740}{}{I Fratelli Corsican al vostro servizio... (L'uomo alza lo sguardo, sorride.) Ehi, bentornato, }
{5740}{}{! Sei pronto per girare un altro film?}
{743}{}{Certo. Andiamo a spaccare qualche materasso.}
{745}{}{Veramente no. Sono qui per i soldi di Big Jesus Mordino.}
{746}{}{No grazie.}

# 49. NO THANKS (48)
{755}{}{Whoa... non vuoi FARLO?! Cos'e'? Sei troppo FIGO per noi, adesso? Siamo stati noi a fare di te quello che sei, "}
{5755}{}{"! Non dimenticarlo!}
{756}{}{Me no dimentica no arrabbiare fare me triste me torna ma adesso deve andare.}
{758}{}{-Ignoralo e allontanati-}
{759}{}{Calma. Oggi non ho voglia di recitare, okay? Tornero' un'altra volta, quando ti sarai calmato.}
{760}{}{Andate al diavolo. Non mi servono queste stronzate. Io sono una stella! Una grande, luminosa, brillante stella!}

# 50. DRUGS . . . (48)
{765}{}{Ehi... tutto bene? Sembri un po' strano. Non ti sei drogato, vero? Perche' non ho ALCUNA intenzione di riprenderti in questo stato.}
{766}{}{Me vuole fare film ORA, piccola persona.}
{768}{}{Tu non sei il mio capo! Io voglio fottere, il cazzo e' mio, quindi preparatevi tutti a girare questo cazzo di film. ADESSO!}
{769}{}{Tu non sei il mio capo! Io voglio fottere, la figa e' mia, quindi preparatevi tutti a girare questo cazzo di film. ADESSO!}
{770}{}{D'accordo. Tornero' quando mi saro', ehm, calmato un po'.}

# 51. PRIZEFIGHTER, BUT NOT PORN STAR (WTG)
{780}{}{I Fratelli Corsican al vostro servizio... (L'uomo alza lo sguardo, sconvolto, poi ti guarda nuovamente.) Cristo... }
{5780}{}{?! Perche' non sei venuto prima? Ottimo incontro, a proposito! Ottimo incontro! Cosa posso fare per te?}
{781}{}{Me no perte! Me vince!}
{782}{}{Niente.}
{783}{}{Cos'e' questo posto?}
{784}{}{Puoi dirmi qualcosa a proposito di questo studio?}
{785}{}{Hai qualche "spazio vuoto" da farmi riempire?}
{786}{}{Hai del lavoro per uno come me?}
{787}{}{Sono qui per i soldi di Big Jesus Mordino.}
{788}{}{Niente. Scusa il disturbo.}

# 52. PRIZEFIGHTER: WHAT IS THIS PLACE? (51)
{795}{}{Lo studio cinematografico Golden Globes e' il posto giusto per tutti i talenti che abitano cio' che resta del mondo. E tu, amico, potresti essere una STAR, capisci cio' che ti sto dicendo? Ti interessa recitare?}
{797}{}{Certo. Dici sul serio?}
{799}{}{Al momento no. Scusa il disturbo.}

# 53. ANY OPENINGS? (51, 52)
{805}{}{Diavolo, si'! Vediamo come te la cavi! Ehi! Portatemi qualcosa di speciale! Abbiamo un astro nascente, qui!}
{806}{}{[Fa' come ti dice l'uomo.]}

# 54. MADE MAN, BUT NOT PORN STAR (WTG)
{810}{}{I Fratelli Corsican al vostro servizio... (L'uomo alza lo sguardo, sconvolto, poi ti guarda nuovamente.) Cristo...uh... ehi come va, }
{5810}{}{?! Come sta il Boss }
{6810}{}{? Siediti pure! Allora, ehm, cosa posso fare per te?}
{812}{}{Niente.}
{813}{}{Cos'e' questo posto?}
{814}{}{Soddisfami. Parlami un po' di questo studio.}
{815}{}{Bella domanda. Hai qualche "spazio vuoto" da farmi riempire?}
{816}{}{Bella domanda. Hai del lavoro per uno come me?}

# 55. MADE MAN: WHAT IS THIS PLACE? (54, 57)
{825}{}{Lo studio cinematografico Golden Globes e' LO Studio per tutti i talenti che abitano cio' che resta del mondo. Allora... ehm, cosa posso fare per te?}
{827}{}{Hai tempo per sottopormi ad un provino? Stavo pensando che potrei anche diventare una star... capisci quello che voglio dire?}
{829}{}{Per oggi niente. Scusa il disturbo.}

# 56. MADE MAN: AUDITION ME? (54, 55)
{835}{}{Um, certo. Certo. Vediamo di fare questo, uhm, provino. Devo vedere se hai cio' che serve. Cioe', siamo piuttosto pieni, ma possiamo darti lo stesso una possibilita', okay? Ehm... qualcosa di speciale quaggiu', per cortesia! Presto!}
{836}{}{[Fa' come dice.]}

# 57. I'M HERE FOR THE MONEY (14, 47, 48, 51, 52, 54, 55, 58, 59)
{845}{}{Um, certo, certo! Certo... ecco qua. 250 dollari. E, uhm, saluta Big Jesus da parte mia, okay?}
{846}{}{Um, certo, certo! Certo... scusa se non ci siamo capiti subito. Ecco qua. 250 dollari. E, uhm, saluta Big Jesus da parte mia, okay?}
{847}{}{Non c'e' fretta. Prima di cacciarmi via, perche' non mi racconti cosa fate qui, verme?}
{848}{}{Gia'. Forse. Ci vediamo piu' tardi, amico.}

# 58. SECOND TIME (WTG)
{855}{}{Fratelli Corsican al vostro servizio... (Alza lo sguardo.) Ancora tu. Vuoi lavorare ancora, Mister "Assistente"?}
{856}{}{Fratelli Corsican al vostro servizio... (Alza lo sguardo.) Ancora tu. Vuoi lavorare ancora, Signorinella "Assistente"?}
{857}{}{Fratelli Corsican al vostro servizio... (Alza lo sguardo.) Tu! Che cosa ti e' SUCCESSO? Cioe', va bene, va tutto bene... L'ultima volta dev'essermi sfuggito qualcosa. Ti interessava quel posto da assistente, giusto?}
{861}{}{Uh, qual e' il compito di un assistente?}
{862}{}{Gia'. C'e' dell'altro lavoro per me?}

# 59. SECOND TIME (WTG)
{875}{}{Fratelli Corsican al vostro servizio... (Alza lo sguardo.) Ehi! Hai pensato alla mia offerta? Eh?}
{876}{}{Fratelli Corsican al vostro servizio... (Alza lo sguardo.) Ehi! Vuoi un altro provino? E' cosi'?}
{877}{}{Fratelli Corsican al vostro servizio... (Alza lo sguardo.) Ehi! Hai pensato alla mia offerta? Vuoi farti un altro giro per vedere se hai ancora il tocco magico? Eh?}
{879}{}{D'oh-Kay}
{881}{}{Si'. Ho cambiato idea. Basta che io me lo tiri fuori, oppure...?}
{882}{}{Si'. Ho cambiato idea. Basta che io mi cali i pantaloni, oppure...?}

# 60. ENCLAVE_DESTROYED (WTG)
{895}{}{... Ho sentito parlare delle tue imprese... di come hai fatto "esplodere la pompa" a tutti i membri dell'Enclave. Ci vuole uno stomaco di ferro, per fare una cosa del genere.}
{896}{}{Yup}
{897}{}{Nup}
{899}{}{Ehi, no... non ho fatto *pompini* ai membri dell'Enclave. Vedi, in realta' e' successo che --}
{900}{}{Sara' meglio che vada.}

# 61. ENCLAVE_DESTROYED, PT 2 (60)
{910}{}{Non essere modesto. So che dev'essere stata dura. Molte persone non avrebbero avuto lo stomaco per farlo. Ma tu hai ingoiato il tuo orgoglio e hai fatto quello che andava fatto. QUESTO e' il potere di una star.}
{911}{}{Yup}
{914}{}{Uh, senti, NON ho fatto *pompini* ai membri dell'Enclave. Vedi --}
{915}{}{Sara' meglio che vada.}

# 62. ENCLAVE_DESTROYED, PT 3 (61)
{920}{}{Sai a cosa stavo pensando, }
{5920}{}{? Stavo pensando che potremmo girare un film basato sulle tue imprese. Lo chiameremo "FALLO!(ut): Un Orgasmo Post-Nucleare". Sei con noi? Eh?}
{921}{}{Sei un eroe, }
{5921}{}{. Un vero eroe. Non scordero' mai tutta la merda che hai dovuto ingoiare per salvarci. E quando il nostro film sbanchera' il botteghino, anche tutto il resto del mondo lo sapra'.} ###???,I'm not gonna forget all the shit you had to swallow for us. And once all the box office receipts come in, the whole world will know, too
{922}{}{Yup}
{924}{}{Yuppity-yup. Ciaooo.}
{926}{}{Certo, e che diavolo. Ho finito il gioco. Facciamolo.}
{927}{}{Graaaande. Grazie...}
{928}{}{Prima lasciami andare a salvare il gioco. Piu' tardi potrei anche tornare qui e accettare la tua proposta...}

# 63. CUBE GONE (WTG)
{935}{}{Rovinati. Siamo rovinati.}
{936}{}{Senza quel cubo siamo... rovinati.}
{937}{}{Oh, crudeli, crudeli divinita' del sesso! Quale offesa possiamo mai avervi rivolto per convincervi a privarci del cubo?} ###???What offense did we give you that caused you to take the cube from us
{938}{}{::Sigh:: Adesso che il cubo non c'e' piu', forse dovrei appendere il macrame' al chiodo.}

# Display Messages
# stupid dude
{1000}{}{Me sentire malato-malatino in pancino.}
# regular dude
{1100}{}{Ack! ::sputo, sputo:: che SCHIFO!}
{1101}{}{Hai un sapore malsano e nauseante in bocca, e il tuo stomaco protesta. Ma, ehi! 5 dollari sono 5 dollari!}
# spouse
{1200}{}{Non... mi sento tanto bene.}
{1201}{}{Il vero amore trionfa ancora. La tua dolce meta' e' ridotta ad uno straccio, ma almeno siete piu' ricchi di 3 dollari!}

{1250}{}{Sei diventato una stella. Una grande, luminosa, brillante stella.}

# END-LINES
{5200}{}{! Proprio l'eroe che volevamo vedere!}
{5201}{}{, il nostro amico eroe. Abbiamo un affare da proporti!}
{5202}{}{! Abbiamo sentito quello che hai fatto a quelli dell'Enclave! Adesso parliamo di quello che noi possiamo fare per TE...}
{5225}{}{ e' oro. Oro puro.}
{5232}{}{! Dolcezza! Tettine d'oro!}
{5246}{}{. Bel tempo oggi, eh?}
{5252}{}{?}
{5256}{}{, se hai VOGLIA di fare qualche ripresa con noi...}
