# 0. QUICK LOOK, BOXES (WTG)
{100}{}{Vedi diverse casse piene di prodotti chimici.}

# 0. LOOK, BOXES (WTG)
{150}{}{Vedi diverse casse piene di prodotti chimici. Non riesci a identificare tali prodotti, ma sono stati imballati con *molta* cura.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{175}{}{Vedi un Vertibird.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{199}{}{Vedi un Vertibird... un modello avanzato di elicottero. Sfortunatamente, non hai idea di come pilotarlo. }

# 2. NORMAL ACTION SEQUENCE (WTG)
{200}{}{(Questi tizi mi fanno venire i brividi...)}
{000}{}{(Zitti. Ecco che arrivano.)}
{000}{}{*Zztttt* Avete la merce che vi abbiamo chiesto? *Zzzttt**}
{000}{}{Si', i prodotti chimici sono tutti qui. Potete controllarli, se volete.}
{000}{}{*Zztttt* Non sara' necessario. *Zzzttt**}
{000}{}{*Zztttt* Sapete bene cosa succedera' se i prodotti non dovessero soddisfare le nostre richieste *Zzzttt**} ###???do not meet the specifications we requested.
{000}{}{Certo, naturalmente. Uhm, e voi avete portato i fulminatori...?}
{000}{}{*Zztttt* Le armi laser sono nel nostro cargo. *Zzzttt**}
{000}{}{*Zztttt* Per assicurare la vostra cooperazione, trasmetteremo la sequenza di attivazione solo quando i prodotti chimici saranno stati caricati a bordo. *Zzzttt**}
{000}{}{Uh...bene...d'accordo, allora. Caricate le casse, ragazzi --}
{000}{}{*Zztttt* No. *Zzzttt**}
{000}{}{*Zztttt* Le caricheremo noi sul nostro cargo. *Zzzttt**}
{000}{}{Uh, giusto... giusto. Naturalmente. Fate spazio, ragazzi.}
{000}{}{Bene; qui abbiamo finito. Il resto di voi guardie... anche tu, novellino... si diriga verso Reno. Ci ritroveremo la'.}

# 3. FLOAT SEQUENCE: INTRUDER (WTG)
{250}{}{Guardate! Qualcuno ci stava spiando!}
{000}{}{Uccideteli!}
{000}{}{Sembra proprio che ci sia una spia...!}
{000}{}{*Zztttt* Missione annullata. Attivata sequenza di bloccaggio del cargo. *Zzzttt**}
{000}{}{*Zztttt* Eliminare gli ostili, e poi fare ritorno alla base. *Zzzttt**}

# 4. FLOAT SEQUENCE: OUT OF POSITION WARNING (WTG)
{300}{}{Non avvicinarti troppo a quei tipi corazzati. Ti apriranno in due.}
{000}{}{Riprendi la tua posizione.}
{000}{}{Smettila di muoverti... a quei tipi corazzati non piace molto.}

# 5. FLOAT SEQUENCE: OUT OF POSITION, FINAL (WTG)
{350}{}{Cazzo! Cosa stai facendo, coglione?!}
{000}{}{Torna al tuo posto! Cosa diavolo stai fa --?!}
{000}{}{*Zztttt* Missione annullata. Attivata sequenza di bloccaggio del cargo. *Zzzttt**}
{000}{}{*Zztttt* Eliminare gli ostili, poi fare ritorno alla base. *Zzzttt**}

# 6. VERTIBIRD SEQUENCE: (WTG)
{400}{}{[Sembra che qui ci sia una porta. La apri e ti infili dentro?]}
{000}{}{Si'.}
{000}{}{-Allontanati-}
{000}{}{Entra nel Vertibird.}
{000}{}{Lasciala stare.}

# 7. VERTIBIRD: TAKE OFF (7)
{450}{}{[La porta si chiude dietro di te, e il Vertibird decolla! Non puoi piu' aprire la porta!]}
{000}{}{Uh-oh}
{000}{}{Oh, merda...}

# 8. DISPLAY TEXT: BOXES (WTG)
{500}{}{Queste casse sono riempite con pesanti cilindri di metallo. A giudicare dalla cura con la quale sono stati imballati, sospetti che contengano un qualche tipo di prodotto chimico pericoloso.}