# 0. QUICK LOOK
{100}{}{Vedi Mason.}

# 0. LOOK
{150}{}{Vedi un uomo molto robusto con un accenno di calvizie.}
{151}{}{Vedi Mason. Ti sta osservando attentamente.}

# 1. FLOAT (WTG)
{200}{}{Che ci fai quassu'?}

# 2. FLOAT: PLAYER IS TRAVELING WITH COMPANIONS (WTG)
{205}{}{Ma che bel gruppetto di coglioni.}

# 3. FLOAT: PLAYER TOUCHES DOOR, PERMISSION = FALSE (WTG)
{210}{}{Tocca di nuovo quella porta e ti trasformero' in una torcia umana.}

# 4. FLOAT/CLICK: PERMISSION = TRUE (WTG)
{215}{}{Puoi entrare...STAVOLTA.}

# 5. INTRO (WTG)
{220}{}{Sei venuto nel posto sbagliato, selvaggio. Smamma.}
{221}{}{Questo non e' uno studio pornografico. Smamma.}
{222}{}{Che ci fai qui, campioncino? Hai perso la strada del ring? Vattene da qui.}
{223}{}{Fatti furbo}
{224}{}{Oog fare racconto di missione} ###???make mission statement
{225}{}{-Allontanati-}
{226}{}{Cosa c'e' dietro quella porta?}
{227}{}{Voglio incontrare Mr. Salvatore.}
{228}{}{Posso chiederti da dove prendete quelle pistole laser?}
{229}{}{In giro si dice che siate stati voi Salvatore ad avvelenare il figlio di Wright.}
{230}{}{D'accordo, me ne vado.}

# 6. GET SMART (5)
{240}{}{Smamma, ritardato. Non te lo diro' un'altra volta.}
{241}{}{Dire me ancora COSA?}

# 7. I WANT TO SEE MR. SALVATORE (5, 11)
{250}{}{La vita e' piena di delusioni. Adesso SMAMMA, capish?}
{251}{}{(Sarcastico.) Dietro quella porta? Proprio quella porta li'? Beh, c'e' la stanza di Mr. SALVATORE. Adesso SPARISCI.}
{252}{}{Voglio vedere Mr. Salvatore. Voglio un lavoro.}
{253}{}{Ascolta, pezzo di merda... vuoi avercelo ancora il tuo lavoro, domattina? Ho delle informazioni riguardanti una delle altre famiglie di Reno che Mr. Salvatore vorra' sicuramente conoscere. Quindi lasciami parlare con lui, SUBITO.}
{254}{}{Dove prendete quelle pistole laser?}

# 8. LOOK, DIPSHIT . . . (FAILED) (7)
{265}{}{}
{266}{}{Ragazzo, devi avere il cervello pieno di MERDA per parlarmi a quel modo. Un'altra parola, solo UN'altra parola, e diventi una torcia umana.}
{267}{}{Ragazza, devi avere il cervello pieno di MERDA per parlarmi a quel modo. Un'altra parola, solo UN'altra parola, e diventi una torcia umana.}
{268}{}{Ho DETTO che voglio vedere Mr. Salvatore.}
{270}{}{(Vattene senza fare storie.)}

# 9. LOOK, DIPSHIT . . . (SUCCEEDS) (7)
{275}{}{(La sua faccia diventa rossa. Improvvisamente parla all'aria.) Mi scusi, Mr. Salvatore, sono Mason. }
{276}{}{C'e' un...uomo...che dice di avere qualcosa che le potrebbe interessare.}
{277}{}{C'e' una...donna...che dice di avere qualcosa che le potrebbe interessare.}
{278}{}{(Aspetta...)}
{279}{}{(Attacca Mason prima che possa continuare.)}

# 10. I WANT TO SEE MR. SALVATORE. I WANT A JOB. (7)
{285}{}{Guarda, forse non l'hai SENTITO, selvaggio, ma questo e' il locale di Salvatore. Il MIO lavoro e' quello di assicurarmi che il boss non venga infastidito da certi cani che abbaiano come te. Adesso tornatene alla tua tribu' e vatti a cucinare uno dei tuoi compagni per cena.}

# 11. WHERE DO YOU GET THOSE LASER PISTOLS? (5, 7, 10)
{295}{}{Queste pistole? Aw, cavoli, non saprei proprio. Ho come un vuoto di memoria. (Si fa serio.) Ascoltami bene, selvaggio. Se non sparisci immediatamente, ti trasformero' in una torcia umana. Adesso smamma.}
{298}{}{Okay! Me ne vado, me ne vado.}
{299}{}{-Vattene senza dire nulla-}

# 12. FINAL STRAW (6, 8)
{305}{}{Ti avevo AVVERTITO, coglione! Adesso sei... (Mason si ferma improvvisamente, e si mette ad ascoltare qualcosa che tu non puoi sentire. Dopo qualche istante, i suoi denti si serrano.) Mr. Salvatore dice che puoi entrare... }
{1305}{}{.}
{306}{}{Oh, lo faro' subito. Dopo averti ucciso.}
{307}{}{Grazie, coglionazzo. Mi ricordero' di parlare a Mr. Salvatore dei tuoi modi gentili.}
{308}{}{D'accordo.}

# 13. WARNING ABOUT MR. SALVATORE BEFORE GOING IN (56)
{315}{}{(Mason ti ferma.) Ascoltami... (Si avvicina, abbassa la voce.) ...Ecco qualche regola di base, ragazzo.}
{316}{}{Ascoltami... (Si avvicina, abbassa la voce.) ...ecco qualche regola di base, ragazza. }
{317}{}{Non sprecare il tempo di Mr. Salvatore e non raccontargli stronzate, oppure dovrai risponderne a me.}
{318}{}{Ho capito.}
{319}{}{Bla, bla, bla. Vabbe'. Adesso togliti di mezzo.}

# 14. WARNING ABOUT MR. SALVATORE BEFORE GOING IN (13)
{325}{}{(Mason ti ferma ancora.) Non ho ancora FINITO. Mostragli RISPETTO. Chiamalo sempre *Mr. Salvatore*, e quando lui parla, tu *sta' zitto e ascolta*. Hai capito?}
{327}{}{E' la tua ultima opportunita', Mason: Togliti dai piedi.}

# 15. WARNING ABOUT MR. SALVATORE BEFORE GOING IN (14)
{335}{}{Un giorno, tu ed io dovremo risolvere questo problema che hai con l'autorita'.}
{336}{}{Io non ho nessun problema. Tutto ok per me.}
{337}{}{Al diavolo.}

# 16. PATIENCE = 0 (5, 7, 10, 13, 14, 15, 17, 18, 19, 20, 21, 22, 27, 30, 34, 35, 36, 42, 53, 56, 57, 58, 59)
{345}{}{D'accordo... adesso BASTA, sapientone! Hai superato il limite... (si scrocchia le dita)... adesso vedremo chi e' davvero lo scemo del villaggio.}
{346}{}{Villaggio? Paolo?}
{347}{}{Si balla.}
{348}{}{E qui lo SCEMO del villaggio sei solo TU! Mi hai SENTITO, MASON?! LO SCEMO DEL VILLAGGIO SEI SOL --} ###???No, YOU'RE the one who's gonna get HURT! You HEAR ME, MASON?! YOU'RE THE ONE WHO'S GONNA GET H

# 17. MISSION ONE LLOYD = MASON (WTG)
{355}{}{Era ora che ti facessi vedere, ragazzo. }
{356}{}{Era ora che ti facessi vedere, ragazza. }
{357}{}{Era ora che ti facessi vedere. Non so perche' Mr. Salvatore abbia assunto della feccia pornografica come te, ma non saro' certo io a mettere in dubbio le sue scelte. }
{358}{}{Lo stronzo che ha rubato dei soldi a Mr. Salvatore si chiama Lloyd. Mr. Salvatore vuole vederlo morto e vuole riavere indietro i suoi soldi. Quando avrai portato a termine il lavoro, riferisci a ME, capito? Credi di potercela fare?}
{359}{}{Dove posso trovare Lloyd?}
{360}{}{Che aspetto ha Lloyd?}
{361}{}{Quanto ha rubato?}
{362}{}{Perche' non ci vai TU a cercare Lloyd?}
{364}{}{Certo. Grazie, Mason.}
{365}{}{Ce la posso fare. Adesso levati e lasciami lavorare.}
{366}{}{Mi sono gia' occupato del "problema" Lloyd.}

# 18. QUESTION NODE? (19, 20, 21, 22, 23, 24, 25, 26)
{375}{}{Davvero? E cioe'?}
{381}{}{E' tutto quello che volevo sapere. Grazie, Mason.}
{382}{}{E' tutto quello che volevo sapere. Adesso levati e lasciami lavorare, Mason.}

# 19. WHERE CAN I FIND LLOYD? (17, 18)
{390}{}{Ha mantenuto un basso profilo, per cui scovarlo sara' compito TUO, ragazzo. }
{391}{}{Ha mantenuto un basso profilo, per cui scovarlo sara' compito TUO, ragazza. }
{392}{}{Vuoi un consiglio? Controlla i bar lungo Virgin Street. Forse Lloyd sta organizzando un'altra truffa da quelle parti.} ###???Best bet
{393}{}{Avrei delle altre domande...}

# 20. WHAT DOES LLOYD LOOK LIKE? (17, 18)
{400}{}{Lloyd? Diavolo... e' di statura media, bianco, capelli castani. L'ultima volta che l'ho visto aveva una camica beige e una sciarpa marrone scuro. Probabilmente non ha cambiato vestiti, dall'ultima volta che l'ho visto.}
{401}{}{Sai, e' davvero strano... questa descrizione combacia con DECINE di persone che ho incontrato da quando ho lasciato Arroyo.}

# 21. SIMILAR MODELS (20)
{410}{}{Haw! Non dirmelo. Al giorno d'oggi i nomi sono l'unico modo per distinguere le persone. Si potrebbe pensare che esistano soltanto dieci tipi di persone al mondo. (Si avvicina) Per come la vedo io, ci dev'essere stato un grosso incidente con le clonazioni, in passato.}

# 22. HOW MUCH DID HE STEAL? (17, 18)
{420}{}{Circa duecento sacchi. Vedi, questa cifra e' una bazzecola per Mr. Salvatore, ma questa e' la sua linea nei confronti di CHIUNQUE prenda QUALCOSA da lui. Se fossi in te, me ne ricorderei. Mr. Salvatore vorra' avere indietro fino all'ULTIMO spicciolo.}

# 23. WHY AREN'T YOU TRACKING DOWN LLOYD? (17, 18)
{430}{}{Ho tenuto gli occhi aperti, ma Lloyd e' stato ben attento a nascondersi... dagli occhi di un Salvatore, almeno. Probabilmente il boss pensa che tu potresti aver miglior fortuna, essendo nuovo in citta'.}
{431}{}{Sara'... Credo che --}
{432}{}{Avrei delle altre --}
{433}{}{D'accordo, andro' a cont --}

# 24. CHILL. I WAS JUST CURIOUS. (57)
{440}{}{D'accordo.}
{442}{}{E' tutto quello che volevo sapere. Adesso levati e lasciami lavorare.}

# 26. YOU FOUND LLOYD? (WTG)
{465}{}{Hai trovato Lloyd?}
{466}{}{(Aggrotta le sopracciglia.) Farai MEGLIO ad avere delle buone notizie per me. Hai trovato Lloyd?}
{467}{}{(Aggrotta le sopracciglia.)  Farai MEGLIO ad avere delle buone notizie per Mr. Salvatore, oppure stanotte dormirai con i radscorpioni.}
{468}{}{No, non ancora. Avrei delle domande da farti su questo Lloyd...}
{470}{}{Si', ho trovato Lloyd.}
{472}{}{No, credo che abbia lasciato la citta' con il denaro.}
{473}{}{Non ancora. Scusa se ti ho disturbato.}

# 27. LAST TIME (18, 19, 20, 21, 22, 24, 25, 26, 57)
{480}{}{Aspetta un secondo, Speedy Gonzales. Te lo diro' in maniera molto CHIARA cosi' potrai capire: non rivolgermi piu' la parola finche' non avrai trovato Lloyd. Altrimenti mi farai incazzare. Adesso va' a fare il tuo LAVORO.}
{481}{}{D'accordo, d'accordo...}
{482}{}{Vattene al diavolo, Mason.}

# 28. LAST TIME (26)
{490}{}{Ti avevo detto di non tornare prima di aver trovato Lloyd... Te l'avevo DETTO. (Si batte l'indice sulla testa) Sei stupido?! Dev'essere cosi', dal momento che sei qui a parlarmi ancora. Stupido... e MORTO.}
{491}{}{Fatti sotto, faccia di merda.}
{492}{}{Vediamo cosa sai fare.} ###???Bring it on
{493}{}{No, sei TU che sei STUPIDO E MORTO! Mi hai SENTITO, MASON?! SEI TU CHE SEI STU --}

# 29. NO, HE LEFT TOWN WITH THE CASH (26)
{500}{}{(Ti guarda incredulo.) Hai mandato tutto in vacca. Ti avevamo dato un compito semplice e tu hai mandato... tutto... in vacca. }
{501}{}{Sei il piu' STUPIDO figlio di puttana del mondo. }
{502}{}{Sei la piu' STUPIDA puttana del mondo. }
{503}{}{(Sorride di traverso, mette mano alle armi.) E' tempo di morire, selvaggio.}
{506}{}{No, sei TU quello che MORIRA'! Hai CAPITO, MASON?! SEI TU QUELLO CHE M --}

# 30. SUCCESS (26)
{514}{}{Beh, perche' diavolo non l'hai detto SUBITO, idiota. Va' a dire a Mr. Salvatore cosa hai trovato.}
{515}{}{(Annuisce, aggrotta leggermente le sopracciglia.) Beh, d'accordo... Va' a dire a Mr. Salvatore cosa hai trovato.}
{516}{}{Oh, DAVVERO? E' QUESTO che dovrei fare? Grazie, Mason. Senza di te, non saprei neanche andare da un posto all'altro. Pfui. Idiota.}
{517}{}{Okay.}

# 31. FLOAT MESSAGE: DONE JOB? (WTG)
{520}{}{Hai portato a termine il tuo lavoro?}

# 32. FLOAT MESSAGE: GO SEE THE BOSS (WTG)
{525}{}{Va' da Mr. Salvatore. Ti sta aspettando.}

# 33. TRIBUTE = MASON (WTG)
{530}{}{Bene. Per questo lavoro diventerai un'agenzia di riscossione crediti formata da una sola persona. Il compito e' semplice: recati nella farmacia di Renesco nella Zona Commerciale, raccogli il tributo, 1000 cucuzze, e portalo qui.}
{531}{}{Okay... c'e' dell'altro?}

# 34. RETURN FROM RENESCO (WTG)
{535}{}{Hai riscosso il tributo?}
{536}{}{(Si acciglia.) Hai riscosso il pizzo?}
{537}{}{(Corruga la fronte.) Questa volta i soldi farai MEGLIO ad averceli, merdaccia. Mr. Salvatore sta aspettando.}
{539}{}{Dov'era che dovevo andare a riscuotere?}
{540}{}{Renesco non mi ha dato un cazzo. Dice che ha gia' pagato due settimane fa e che non dovrebbe pagare per almeno un altro mese.}
{542}{}{Uh... si'. Ecco i soldi.}
{543}{}{Si', ma non ho i soldi qui con me...}
{544}{}{Quasi. La prossima volta ti portero' i soldi, Mason.}
{546}{}{Il tuo tributo ce l'ho proprio qui... cadavere ambulante.}

# 35. RENESCO'S? (34)
{555}{}{*Farmacia di Renesco*. Nella zona ovest. Mille cucuzze. Adesso va'.}
{556}{}{E' tutto quello che mi serve sapere. Adesso cavati dai piedi e lasciami lavorare, Mason.}

# 36. WARNING (34, 35, 38, 39, 59)
{565}{}{Aspetta un secondo, Speedy Gonzales. Te lo diro' in maniera molto CHIARA, cosi' potrai capire: Non parlarmi piu' finche' non avrai preso quei soldi da Renesco. Altrimenti mi farai incazzare. Adesso fa' il tuo LAVORO.}

# 37. LAST TIME (34)
{575}{}{Ti avevo detto di non tornare qui prima di aver preso quei soldi... te l'avevo DETTO. (si tocca la testa con l'indice) Sei stupido?! Dev'essere cosi', dal momento che mi stai rivolgendo di nuovo la parola. Stupido... e MORTO.}

# 38. RENESCO'S GIVING ME SHIT. (34)
{585}{}{(Mason sgrana gli occhi.) E che cazzo di problema c'e'? Gli hai detto per chi lavori?}
{586}{}{Si'.}
{587}{}{Beh, no.}

# 39. YES. (38)
{595}{}{Allora gli hai fatto VEDERE per chi lavori?}
{596}{}{Fatto vedere?}
{598}{}{Uh, no. La prossima volta ti portero' i soldi, Mason.}

# 40. NO. (38, 39)
{605}{}{Cos'e'? Devo portarti a MANINA?! E' la cosa piu' dannatamente facile al mondo, e tu vieni qui a dirmi piagnucolando: "Me-son, Me-son, cosi' e cosa' non paga il tributo."}
{606}{}{Ehi, aspetta un secondo...}

# 41. IF PLAYER KILLED RENESCO. (WTG)
{615}{}{(Non appena ti vede, Mason sorride in modo non molto rassicurante.) Proprio l'idiota rottinculo che stavo cercando. }
{617}{}{Non si puo' riscuotere il pizzo dai morti. (Mette mano alle armi.) Hai finito di fare cazzate. Per SEMPRE.}
{618}{}{Gia', beh, stavo comunque cominciando a stufarmi di te...}
{619}{}{No, TU sei quello che ha FINITO PER SEMPRE DI FARE CAZZATE! HAI CAPITO, MASON?! TU SEI QUELLO CHE HA FINITO PER SEM --}

# 42. PLAYER GOT MONEY. (34)
{625}{}{(Mason annuisce, sembra deluso.) Heh. Credo che abbiamo prosciugato il vecchio Renesco fino all'ultimo decino. Okay, beh... porta i soldi al boss. (Corruga la fronte) Muoviti.}

# 43. GET THE HELL OUTTA HERE. (WTG)
{635}{}{Vattene da qui. Mr. Salvatore non ha piu' intenzione di fare affari con te.}

# 44. GUARD = MASON (WTG)
{640}{}{Okay, il boss dice che devi presenziare ad una piccola TRANSAZIONE che stiamo per fare. Vedi di venire armato... e non portare pistole ad acqua... poi torna qui e parla con me.}
{642}{}{Mr. Salvatore mi ha detto che mi avresti dato una pistola laser.}
{643}{}{Cos'e' questa transazione che stiamo per fare?}
{644}{}{Sono pronto. Andiamo.}
{645}{}{Dammi un po' di tempo per prepararmi e poi tornero'.}

# 45. SALVATORE SAID YOU WERE GOING TO GIVE ME A LASER PISTOL. (44, 46, 49)
{655}{}{Gia', cosi' ha detto. Ecco qua... vedi di non giocherellarci. Prova a far del male a QUALCUNO con quella e io ti ammazzo.}
{656}{}{Puoi insegnarmi come si usa?}
{658}{}{D'accordo, sono pronto. Andiamo.}

# 46. WHAT IS THIS TRANSACTION WE'RE DOING? (44, 45, 49, 51, 52)
{665}{}{(Sogghigna.) Se il boss non te l'ha detto, allora vuol dire che non lo devi sapere. Quindi tappati quella fogna... e non dire a nessuno quello che sta per succedere o faro' in modo che tu non possa piu' dire altro.}

# 47. I'M READY TO GO RIGHT NOW. (45, 46, 49, 51, 52)
{675}{}{Allora andiamo.}
{676}{}{Segui lui e gli altri Salvatore nel deserto...}

# 48. GIVE ME SOME TIME TO GET READY . . . (44, 45, 46, 49, 51, 52)
{685}{}{Vedi di sbrigarti. Abbiamo una finestra di 24 ore prima che l'accordo salti. Se lo manchi, faro' in modo che tu marcisca sul Golgotha.}
{686}{}{Non temere, ci saro'.}

# 49. RETURN . . . (WTG)
{695}{}{Ti sei fatto il tuo bel pisolino? Forse ADESSO sei pronto?}
{696}{}{Cos'era questa transazione che dobbiamo fare?}
{697}{}{Si'. Andiamo.}
{698}{}{Ho bisogno di ancora un po' di tempo. Poi tornero'.}
{699}{}{Puoi insegnarmi come si usa questa pistola?}

# 50. RETURN LATE . . . (WTG)
{705}{}{Avevo una gran voglia di ucciderti da MOLTO tempo... ti avevo AVVERTITO riguardo a quello che ti sarebbe successo nel caso in cui tu fossi arrivato in ritardo.}
{706}{}{Beh, cazzo, scusami se non ho un orologio.}
{707}{}{No, TU sei quello che era stato AVVERTITO! Hai CAPITO, MASON?! TU SEI QUELLO CHE ERA STATO AVV --}

# 51. WHY DO I NEED . . . (52)
{715}{}{Perche' diavolo devi chiedermi qualcosa ogni volta che parlo?! Ascolta: l'ALTRO gruppo presente a questa transazione non puo' essere ferito da questi fulminatori, okay? Quindi vedi di portarti qualcosa d'ALTRO.}

# 52. CAN YOU TEACH ME . . . (45, 49, 51)
{725}{}{(Grugnisce.) Per tutti i... ascolta, prima di tutto devi tenerla COSI'. (Aggiusta la tua presa) Ora, la camera di caricamento e' qui... (dopo un'ora, e un po' d'esercizio, Mason ha incrementato la tua abilita' con le Armi a Energia.)}
{726}{}{Beh, ma allora perche' mi serve qualcos'altro, oltre a questa? Queste pistole mi sembrano piuttosto potenti.}
{728}{}{Bene, sono pronto. Andiamo.}
{729}{}{Okay. Dammi un po' di tempo per prepararmi e poi tornero'.}

# 53. MADE MAN. (WTG)
{735}{}{(Grugnisce.) Ehila'...}
{736}{}{-Prendi gli oggetti-}

# 54. MADE MAN 2. (53)
{745}{}{Inoltre, noi Salvatore abbiamo un... RAPPORTO speciale con Miss Kitty, giu' al Cat's Paw. E con Eldridge del negozio di armi... e con Renesco. (Strizza l'occhio) Divertiti.}
{746}{}{Grazie, Mason.}
{747}{}{Gee, Mason, grazie... solo una cosa: la prossima volta, perche' non mi chiami "signore"? Lo gradirei molto. AH AH AH AH AH AH...}
{748}{}{Gee, Mason, grazie... solo una cosa: la prossima volta, perche' non mi chiami "signora"? Lo gradirei molto. AH AH AH AH AH AH...}

# 55. MADE MAN 2. (WTG)
{755}{}{Salve...signore.}
{756}{}{Salve...signora.}

# 56. LOOK, DIPSHIT . . . (SUCCEEDS) (9)
{765}{}{(Mason si ferma, mentre ascolta qualcosa che tu non puoi sentire. Dopo un attimo, i suoi denti si serrano.) Mr. Salvatore dice che puoi entrare, }
{766}{}{Grazie, coglionazzo. Mi ricordero' di parlare a Mr. Salvatore dei tuoi modi gentili.}

# 57. WHY AREN'T YOU TRACKING DOWN LLOYD? (23)
{775}{}{(Sgrana gli occhi.) Naturalmente, se stai INSINUANDO che non faccio il mio LAVORO, tu ed io possiamo discuterne personalmente anche adesso. Mr. Salvatore non si chiedera' certo cos'e' successo al tuo brutto muso.}
{776}{}{Non sto insinuando che non fai il tuo lavoro. Lo AFFERMO.}
{777}{}{Calmati. Ero solo curioso.}
{778}{}{Questa conversazione comincia ad annoiarmi. Me ne vado.}

# 58. EXTORTION ASSIGNMENT (33)
{785}{}{Vedi di non farti raccontare stronzate da quel vecchio... se lo fa, digli che lavori per Mr. Salvatore. Questo dovrebbe chiarire ogni equivoco. Hai capito?}
{786}{}{Ho capito. Adesso spostati e lasciami lavorare.}

# 59. NO 2. (40)
{795}{}{Fatti crescere un po' di PALLE, ragazzo, e *occupatene*.}
{796}{}{Avrei dovuto immaginarlo che sarebbe successo... mandare una donna a fare un lavoro da uomini... Smettila di *brontolare* e vedi di *occupartene*.}
{797}{}{Me ne occupero', allora. Grazie, Mason. Mi sei stato di GRANDE aiuto.}
{798}{}{Me ne occupero', allora.}
{799}{}{Oh, adesso mi occupo di tutto. A cominciare da te.}

# 60. IF SALVATORE WAS ASSASSINATED (WTG)
{805}{}{Povero Mr. Salvatore... stava diventando piuttosto vecchio. Credo che abbia infine esalato l'ultimo respiro.}
{806}{}{*Sniff*...Mr. Salvatore...era quasi un padre per me.}
{807}{}{Amavo quel vecchio storpio ansimante. Adesso che e' morto non sapra' mai cosa provavo.}

# 61. IF PC KILLED RENESCO BEFORE TALKING TO MASON (WTG)
{815}{}{(Sogghigna mentre ti vede.) Ho saputo che Renesco e' rimasto vittima di un "incidente". Per strada si dice che tu abbia qualcosa a che fare con quello che e' successo. Solo perche' tu lo sappia, selvaggio, lui era uno dei NOSTRI. Credo che tu sia in debito con noi... un debito di SANGUE.}
{818}{}{No, sei TU quello che dara' il SANGUE! Hai CAPITO, MASON?! SEI TU QUELLO CHE DARA' IL S --} ###???YOU'RE the one who's gonna RETIRE! You HEAR ME, MASON?! YOU'RE THE ONE WHO'S GONNA R

# 62. ACCUSE MURDER (5, 7, 10)
{825}{}{(Il volto di Mason si fa di pietra mentre mette mano alle armi.)}
{826}{}{Non credo che uccidere ME sia tanto facile quanto avvelenare quel ragazzo...}

# 63. TRADE DISRUPTED (WTG)
{835}{}{Niente da fare. Il lavoro e' stato cancellato. Vattene.}

# 64. GO SEE THE BOSS
{840}{}{Sono felice che tu sia tornato. Il boss vuole vederti.}


# END LINES
{5735}{}{. Mr. Salvatore mi ha detto della tua promozione. Congratulazioni. Ho della roba per te... vediamo... (ti da' un mucchio di oggetti). Sta' attento con questa roba...}
{5765}{}{.}
