# 0. QUICK LOOK
{100}{}{Vedi una guardia.}

# 0. LOOK
{150}{}{Vedi una guardia dall'aria annoiata. Sembrerebbe non desiderare altro che essere da qualsiasi altra parte.}
{151}{}{Vedi una delle guardie annoiate di Myron.}
{152}{}{Vedi una delle guardie annoiate di Myron. Sembrerebbe non desiderare altro che essere da qualsiasi altra parte.}

# 1. FLOAT [TOUCH LOCKER] (WTG)
{200}{}{Tocca ancora la mia roba e ti uccido.}

# 2. FLOAT [TOUCH DOOR AND MYRON_PERMISSION = TRUE] (WTG)
{205}{}{Entra pure. E' tutto ok.}
{206}{}{Entra. E' ok.}

# 3. FLOAT [TOUCH DOOR] (WTG)
{210}{}{Sfiora ancora quella porta e ti ritrovi monco.}
{211}{}{Sta' lontano da li'.}

# 4. COMPANION: MYRON (X)
{215}{}{Ehi, Myron. Vai a farti un giretto?}
{216}{}{Sta' attento, Myron.}
{217}{}{Non cacciarti nei guai, Myron, ok?}
{218}{}{Non andare troppo lontano, Myron.}

# 5. FLOAT [MADE MAN]
{225}{}{Ehi, }
{5225}{}{! Come butta?}

# 6. FLOAT [MADE MAN, NOT MORDINO, ARMED]
{230}{}{E' uno degli sgherri di }
{5230}{}{! Facciamolo secco!}

# 7. FLOAT/CLICK [MALE, MADE MAN, NOT SAME FAMILY]
{235}{}{Hai del fegato a farti vedere da queste parti. Ti consiglio pero' di abbassare la cresta e di andartene.}
{236}{}{Hai proprio la faccia di un uomo di }

# 8. CLICK [FEMALE, MADE MAN, NOT SAME FAMILY]
{240}{}{Faresti meglio a tornartene al tuo canile, puta di una }
{241}{}{Hai proprio la faccia di una }

# 9. FLOAT [ARMED, MALE, NO REP]
{245}{}{Metti via quell'arma... a meno che tu non stia CERCANDO guai.}

# 10. FLOAT [SNEAK, MALE, NO REP]
{250}{}{Intruso!}

# 11. FLOAT [COMPANION: ROBOBRAIN]
{260}{}{Porta fuori di qui quel cassonetto ambulante.}
{261}{}{I droidi qui non sono ammessi. Fallo sparire.}
{262}{}{Se non se ne va subito, quel robot sara' presto ridotto ad un rottame.}

# 12. FLOAT [COMPANION: MARCUS]
{270}{}{Mi *pareva* di aver sentito puzza di mutante. Portalo fuori di qui, prima che ci incazziamo di brutto.}
{271}{}{Sei un amico dei mutanti? Il suo posto e' di FUORI.}
{272}{}{Quel mutante vuole forse diventare il nostro bersaglio mobile di oggi? Se non se ne va subito lo accontenteremo volentieri.}

# 13. FLOAT [COMPANION: LENNY]
{280}{}{Mi *pareva* di aver sentito puzza di qualcosa che sta andando a male. Porta quel tuo ghoul fuori di qui.}
{281}{}{Porta quel coglione di un ghoul puzzolente fuori di qui. Adesso.}
{282}{}{Se quel ghoul non e' fuori di qui entro un minuto, sara' piu' morto di quanto non sia gia'.}

# 14. [PORN STAR, FEMALE OR FEMALE, CHR > 5] (WTG)
{290}{}{::Whoa.:: Guarda QUELLA.}
{291}{}{Ehi, chica, cerchi compagnia?}
{292}{}{Che ne dici di passare un po' di tempo con noi, chica?}
{293}{}{::Ulula come un lupo non appena ti vede:: Auuuuuuuuuu!}

# 15. [SLAVER] (WTG)
{300}{}{Che cosa diavolo vuoi, schiavista? Gli schiavi sono di sopra.}

# 16. FLOAT [MYRON_LEFT_STABLES] (WTG)
{305}{}{Cos'e' successo a Myron?}

# 17. FLOAT [NORMAL] (WTG)
{310}{}{Myron sta ancora dormendo?}
{311}{}{Che noia.}
{312}{}{Hai visto l'incontro, ieri sera?}
{313}{}{Non vedo l'ora di finire il turno.}

# 18. INTRO (WTG)
{320}{}{Ti serve qualcosa, amigo? Questa e' una zona vietata.}
{321}{}{Bene, bene, bene... abbiamo una vera star tra di noi. Hai un appuntamento con Myron, chica?}
{322}{}{Posso aiutarti, chica? Questa e' una zona vietata.}
{323}{}{(La guardia sorride e ti osserva.) Hai un appuntamento con Myron, chica?}
{324}{}{Me vuole pace in mondo}
{325}{}{Me vuole entrare in stanza}
{326}{}{Chiituu}
{327}{}{-Allontanati-}
{328}{}{Vietata? Cosa c'e' dietro quella porta?}
{329}{}{Sono qui per parlare con Myron.}
{330}{}{Sono qui per parlare con Myron. Ho un pass.}
{331}{}{Sono qui per parlare con Myron. Lui ed io abbiamo un "appuntamento speciale", capito?}
{332}{}{Certo che ce l'ho. Mi vuoi far rimanere ancora qui fuori, oppure ti sei gia' rifatto gli occhi a sufficienza, bellezza?}
{333}{}{Come? Che appuntamento?}
{334}{}{Scusa, ho sbagliato stanza. Me ne vado subito.}

# 19. RETARD (18)
{350}{}{Sei scappato dal tuo recinto, schiavo? Faresti meglio a riportare le tue chiappe di sopra, prima che ti mettiamo in una delle gabbie.}
{351}{}{ME VUOLE PACE IN MONDO ME VUOLE PACE IN MONDO}
{352}{}{IO DETTO ME VUOLE ENTRARE IN STANZA}
{353}{}{CHIITUU}
{354}{}{[Allontanati]}

# 20. LOUD RETARD (19)
{360}{}{(Impugna l'arma.) Credo che mi divertiro'. E' da quasi un'ora che non torturo uno schiavo...}
{361}{}{(Impugna l'arma.) Credo che mi divertiro'. Sono due giorni che non uccido nessuno...}
{362}{}{TU AVERE MALE, NO ME}
{363}{}{ SCHIACCIA}
{364}{}{[Prova a scappare.]}
{365}{}{Amico, stai per ricevere la piu' dura lezione della tua vita.} ###???you're about to get the ass whipping of a life time

# 21. WHAT'S BEHIND THAT DOOR? (18, 30)
{370}{}{(Sghignazza.) Spiacente. E' roba "Top Secret". Adesso smamma... amigo.}
{371}{}{(Sghignazza.) Spiacente. E' roba "Top Secret". Adesso smamma, chica.}
{374}{}{Lasciami passare. Devo entrare in quella stanza.}
{375}{}{D'accordo... d'accordo...}

# 22. I'M HERE TO SEE MYRON (18, 21, 30)
{380}{}{Oh, DAVVERO? Beh, cazzo, perche' non l'hai detto prima? Ci saremmo risparmiati tutta questa chiacchierata e io ti avrei detto di andartene a cagare sin dall'inizio.}
{381}{}{Myron mi sta aspettando. Sara' meglio che mi lasciate entrare; dopo potreste pentirvi di non averlo fatto.}

# 23. MYRON'S EXPECTING ME (22, 29)
{390}{}{Nah. Non lo incontrerai. Adesso smamma prima che mi arrabbi.}
{391}{}{Potresti almeno recapitargli un messaggio da parte mia?}

# 24. MYRON'S EXPECTING ME  2 (21, 22, 23)
{400}{}{No. Adesso sparisci, stronzetto.}
{401}{}{Staro' qui finche' non mi farete entrare. Voglio proprio vedere se PROVERETE a spostarmi.}
{402}{}{Staro' qui finche' non mi farete entrare. Voglio proprio vedere se voi due sacchi di merda avrete il CORAGGIO di spostarmi.}
{404}{}{D'accordo.}

# 25. I'M STAYING (24)
{411}{}{Lo stesso vale per me...} ###???Neither have I
{412}{}{Difenditi.}

# 26. MYRON + BADGE (18, 21, 22, 23, 24, 29, 30)
{425}{}{Davvero? Fammi vedere. Hmmmm. (Controlla il pass, alza le spalle.) D'accordo, ma sbrigati. Myron e' molto occupato e non gli piace esser disturbato.}
{426}{}{Ok.}

# 27. SURE DO (18)
{435}{}{(I suoi occhi corrono su e giu' seguendo le curve del tuo corpo.) Ok, per adesso...eh eh...tuttavia potrei aver bisogno di rifarmeli tra un po'. Dopo che avrai finito con Myron.}
{436}{}{D'accordo... non dimenticartene. Posso entrare?}
{437}{}{Vedremo, ok?}

# 28. CAN I HEAD ON IN? (27, 31)
{445}{}{Certo, dolcezza. Entra pure.}
{446}{}{Si', entra.}
{447}{}{Grazie.}

# 29. SKANKY REFUSAL (18)
{455}{}{Tu? Ah! Chica, a meno che Myron non sia diventato improvvisamente cieco, tu non entrerai. Conosco i suoi gusti, capito? Non gli interessano le troie sboldre che vengono qui a implorare una goccia di Jet.}
{457}{}{Senti, sono qui per incontrare Myron. Ho un pass.}
{458}{}{Me ne vado subito.}

# 30. APPOINTMENT? (18)
{465}{}{Oh, scusa. Pensavo tu fossi qualcun altro. Che cosa vuoi, chica?}
{466}{}{Cosa c'e' dietro quella porta?}

# 31. MADE MAN OR PERMISSION (WTG)
{475}{}{Myron ti sta aspettando?}
{5476}{}{! Myron e' proprio dietro a quella porta. Ti aspetta?}
{477}{}{Si'. Posso entrare? Ho degli affari da discutere con lui.}
{478}{}{No, non adesso. Statemi bene, ragazzi.}

{479}{}{Si'. Posso entrare? Ho degli "affari" da discutere con lui. Se capisci cosa voglio dire (Strizzi l'occhio alla guardia)}
{480}{}{Eh, ne sono convinto. Cerca di non fare troppo casino mentre sei qui. (Tra se' e se': Dannazione, Myron e' un uomo cosi' fortunato.)}

# 32. MYRON AIN'T AROUND (WTG)
{485}{}{Myron non c'e'.}
{5486}{}{, come butta? Oh, ehi...Myron non c'e'.}
{487}{}{Posso entrare lo stesso?}

# 33. MYRON AIN'T AROUND 2 (32)
{495}{}{(Alza le spalle.) Fa' pure. Sei libero di aspettare che ritorni, se vuoi. Non so quando... o SE... ritornera'.}

# END LINES
{5236}{}{ che non sa di essere ad un passo dalla morte.}
{5240}{}{?}
{5241}{}{ che non sa di essere ad un passo dalla morte.}
