# 0. QUICK LOOK
{100}{}{Vedi Renesco "the Rocketman".}

# 0. LOOK (GLASSES = DISCOUNT, FREEBIE, DONE)
{150}{}{Vedi un vecchio con un paio di occhiali spessi e vistosi. Sospira irritato mentre lo guardi.}

# 0. LOOK (GLASSES = NOTHING)
{200}{}{Vedi Renesco "the Rocketman". Mentre lo guardi, si toglie i suoi occhiali rotti e pulisce l'unica lente buona.}
{201}{}{Vedi Renesco "the Rocketman". Mentre lo guardi, si toglie i suoi occhiali rotti e pulisce l'unica lente buona.}

# 1. FLOAT DIALOGUES (WTG)
{210}{}{Un'altra lente, e' tutto cio' che chiedo.}
{211}{}{Dannatissimi occhiali!}
{212}{}{Dannati i miei occhi!}
{213}{}{Vuoi COMPRARE qualcosa?}
{214}{}{Questa non e' una mensa per i poveri. Vuoi COMPRARE qualcosa?}
{215}{}{Se continua cosi' finisce che divento cieco.}
{216}{}{Mi servira' ancora un po' di chemtex nove...} #Gonna need some more base chemtex nine
{217}{}{La domanda sta crescendo...} #Demand's picking up

# 2. FLOAT DIALOGUES (WTG)
{225}{}{Va' all'inferno.}
{226}{}{Vattene da qui, o saro' costretto ad ammazzarti. Due volte.}
{227}{}{Vattene VIA da qui.}
{228}{}{Fuori! Fuori! Fuori! Fuori! Fuori!}

# 3. INTRO SPIEL (WTG)
{235}{}{(Il vecchio si aggiusta sul naso gli occhiali rotti e sospira, seccato.) SI'? Che cosa vuoi? }
{236}{}{Forza, ragazzo, tira fuori quello che vuoi!}
{237}{}{Forza, donna, tira fuori quello che vuoi!}
{238}{}{Okay, ecco che arrivare... tu fare bene stare lontano (Zip.)}
{239}{}{Okay. Me prima deve aprire reggiseno. Aspettare (Zip.)}
{240}{}{Cosa io VOLERE? Che cosa tu AVERE?}
{241}{}{[Osservalo per un momento, solo per assicurarti che sia vero, poi allontanati]}
{242}{}{Chi sei?}
{243}{}{Ehi, ho qui un paio di occhiali, se li vuoi.}
{244}{}{Come vanno gli occhiali?}
{245}{}{Sai, ci sono delle marche di decaffeinato che hanno lo stesso sapore di quello vero.}
{246}{}{Cavoli, sono nel posto sbagliato. Addio.}

# 4.  RETARD (3, 5)
{255}{}{(Ti guarda scioccato.)}
{256}{}{...un altro mezzo-aborto ritardato in un mondo post-olocausto pieno di uomini-bambini idioti. (Alza i pugni) Fuori dal mio negozio! Esci immediatamente! E non tornare, hai capito?!}
{257}{}{Me scusa piccolo }
{258}{}{Me no sa come rimettere su reggiseno}
{259}{}{No gridare a }
{260}{}{ odia te! }
{261}{}{Me va, me va. Per ora.}

# 5.  WHO ARE YOU? (3)
{270}{}{Io? Oh, sono solamente il buon vecchio Babbo Natale... mezzo idiota con problemi mentali che non sei altro.}
{271}{}{Io? Io sono il buon vecchio Babbo Natale. E TU devi essere quello stupido teppista a pagamento che gira per la citta' come un cane affamato in cerca dei suoi escrementi.}
{272}{}{Io? Io sono il buon vecchio Babbo Natale. E TU devi essere quello stupido pezzo di spazzatura porno che monta come un cavallo ed e' stupido come un asino.} #And YOU must be that stupid piece of tailchasing porno trash that's hung like a horse and as stupid as one
{273}{}{Io? Io sono il buon vecchio Babbo Natale. E TU devi essere quello stupido pezzo di spazzatura porno che i vecchi incappottati usano per soddisfare le loro fantasie masturbatorie.}
{274}{}{Bene, sono felice di non aver bisogno di presentarmi. Cosa ci fai qui, "Natale"?}
{275}{}{Babbo Natale? Che diavolo di nome e'?}
{276}{}{Senti nonnetto, un'altra osservazione come questa e usero' i tuoi denti come collana.}
{277}{}{Senti, sorvolero' sulle tue osservazioni... per questa volta. Adesso dimmi chi sei.}
{278}{}{Un vocabolario davvero impressionante... "Natale". Sei di queste parti?}
{279}{}{Come non detto. Me ne vado.}

# 6. WHO ARE YOU? (3, 5)
{290}{}{(Ti guarda, poi sbuffa.) Mi chiamo Renesco. Dimmi che cos'e' che vuoi, tu...beh, qualunque cosa tu sia. (Ti da' un'occhiata.) Sembreresti uno di quei primati adoratori del sole, sotto i vestiti.}
{291}{}{Vengo da un villaggio a nordovest. Arroyo.}
{292}{}{Che cosa vendi?}
{293}{}{Che cosa VOGLIO? Non lo so esattamente. Il piu' delle volte lascio perdere la mia missione ed entro nelle case altrui per saccheggiare gli scaffali...ohh, proprio come quelli laggiu'!}
{294}{}{Hai un vocabolario davvero interessante... Renesco. Sei di queste parti?}
{295}{}{Me ne vado.}

# 7. WHAT DO YOU SELL? (6, 36, 42)
{305}{}{Per lo piu' vendo droghe ricreative. E' per questo che mi hanno rifilato quel soprannome idiota, "the Rocketman". Hmmmph. Vendo anche delle provviste per carovane. Ti SERVE qualcosa o posso tornare ad occuparmi di cose piu' importanti?}
{306}{}{Rocketman, eh? Hai presente il verso di quella canzone di Elton John: "Rocketman, burning off the mmmncfnfm there at home?" Cos'e' che dice in realta'?}
{307}{}{Posso vedere quello che hai da vendere?}
{308}{}{Vendi droga qui, nel NEGOZIO?}
{309}{}{Tipo vendere droga al figlio di Wright?}
{310}{}{Torna a fare quello che stavi facendo.}

# 8. ROCKETMAN/IGNORE QUEST (6, 7, 32, 36)
{320}{}{(Renesco ti fissa. Sembra che ti stia spogliando lentamente, e poi che ti stia strappando gli arti ad uno ad uno.)}
{321}{}{Lasciamo perdere, allora. Avrei delle altre domande...}
{322}{}{Lasciamo perdere, allora.}

# 9. YOU SELL DRUGS IN THE STORE? (7)
{330}{}{(Renesco ti guarda disgustato.) Si'. Nel NEGOZIO. Non siamo nel 20esimo secolo, dove la droga erano venduta agli angoli delle strade da pidocchi che vivevano nel terrore delle autorita'.} #This isn't the 20th century where chems are sold by
{331}{}{Bene, allora -}
{332}{}{Ma -}
{333}{}{Uh, credo che farei meglio a -}

# 10. YOU SELL DRUGS IN THE STORE? (9)
{350}{}{Questa e' NEW RENO. Non ci sono piedipiatti, non ci sono leggi ed e' pieno di clienti che non si fanno problemi a comprare del veleno alla farmacia giu' in strada. QUESTO ti basta come risposta alle tue domande, primate?}
{351}{}{Si', ma non risponde a questo: Richard Wright era uno dei tuoi clienti?}
{352}{}{D'accordo, d'accordo... che cos'hai da vendermi?}
{353}{}{Veramente, avrei delle altre domande...}
{354}{}{Ma, come hai detto, le droghe sono... velenose. Uccidono l'anima. Non ti da' fastidio venderle?}
{355}{}{Certamente. Devo andare adesso.}

# 11. DOES IT BOTHER YOU TO SELL DRUGS IN THE STORE? (10)
{365}{}{Mi stai chiedendo se mi da' FASTIDIO venderle agli idioti, agli schiavisti, ai boss del crimine e ai selvaggi dei quali il mondo farebbe volentieri a meno? Primate, solo una parola: svegliati.}
{366}{}{OK...posso vedere la tua merce?}
{367}{}{D'accordo, d'accordo. Senti, avrei delle altre domande...}
{368}{}{Le droghe di New Reno si stanno diffondendo anche in altri posti, facendo del male alle persone che vivono li'. Non ti preoccupa una cosa del genere?}
{369}{}{Comincero' a farlo andandomene da qui.}

# 12. YOU SELL DRUGS IN THE STORE 2? (11)
{375}{}{E allora? Che te ne frega?}
{377}{}{La razza umana e' stata colpita da una terribile tragedia. Adesso sta cercando di ricostruire cio' che e' andato distrutto. Vendere Jet mi sembra... controproducente a questa ricostruzione.}
{378}{}{Bene, come vuoi tu. Adesso devo andare.}

# 13. SOME OF THE PEOPLE BEING HARMED ARE . . . (12)
{385}{}{E allora? Nessuno OBBLIGA quegli idioti ad inalare Jet. Nessuno va in giro a ficcarlo nelle loro gole!}
{386}{}{Posso vedere -}
{387}{}{Ma non  -}
{388}{}{Questo e' quello -}

# 14. SOME OF THE PEOPLE BEING HARMED ARE . . . 2 (13)
{395}{}{Quegli idioti spaccasassi di Redding SANNO quello che stanno prendendo, per cui non provo un millimetro di pieta' per loro! Per quello che mi interessa, il Jet spazza via quei rifiuti umani che sarebbe meglio fossero morti quando caddero le bombe!}
{396}{}{Uh, okay. Posso vedere la tua merce?}
{397}{}{Dov'e' questa Redding di cui parli? Perche' l'hai menzionata?}
{398}{}{Hai menzionato Redding in modo specifico. Come mai la presenza del Jet e' cosi' forte a Redding?}
{400}{}{E' tuo diritto pensarla cosi'. Adesso devo andare.}

# 15. REDDING 1 (14)
{410}{}{Beh, Redding e' un... caso particolare. Vedi, qui a Reno ci sono persone che fanno in modo che Redding sia sempre ben rifornita. Dopotutto, una volta che hai assaggiato il Jet non ne puoi piu' fare a meno. E cosi' IO mi guadagno da vivere.}
{411}{}{A proposito, posso vedere la tua merce?}
{412}{}{Chi e' che fa in modo che Redding sia rifornita? E perche'?}
{413}{}{L'ho notato. Senti, ho delle altre domande...}
{414}{}{Capisco... Adesso devo andare.}

# 16. WHO'S SUPPLYING REDDING? (15)
{420}{}{Beh, selvaggio, non credo che tu abbia la sensibilita' necessaria per notarlo, ma New Reno non produce nulla di utile. E' come una grossa e luminosa zecca dei campi in mezzo al deserto. Redding, invece...}
{421}{}{Continua.}
{422}{}{...PRODUCE qualcosa di importante.}
{423}{}{Ho sentito abbastanza.}

# 17. . . . DOES PRODUCE SOMETHING USEFUL (16)
{430}{}{Questa sara' la prima e l'ultima volta che ti avvertiro', selvaggio: non finire le mie dannatissime frasi. Non mi piacciono i primati sapientoni che parlano quando dovrebbero ascoltare. Non mi meraviglia il fatto che voialtri usiate ancora le lance...}
{431}{}{C'e' qualche eccezione. Per farti un esempio, io uso svariate armi per uccidere le persone... lascia che te lo dimostri.}
{432}{}{Perdonami. Continua, per favore.}
{433}{}{Che tu possa bruciare all'inferno. Me ne vado. }

# 18. GO ON ABOUT REDDING (16, 17)
{440}{}{Redding ha una forza lavoro stabile che estrae minerali grezzi: oro, soprattutto. A New Reno farebbe davvero comodo quell'oro. Qualcuno ha scoperto che tutto quello che doveva fare era riuscire a far diventare quei minatori dei Jet-dipendenti, in modo da farli diventare suoi burattini per sempre. Hai capito adesso?} # Somebody figures all we gotta do is get those miners hooked, and we got 'em for life.
{441}{}{Si'... a parte una cosa: da dove arriva questo Jet?}
{442}{}{Chi sta cercando di far diventare Jet-dipendenti i minatori?}
{443}{}{Certo, capisco. Senti, avrei delle altre domande...}
{444}{}{Non voglio sentire altro. Adesso devo andare.}

# 19. WHERE DID JET COME FROM? (20)
{450}{}{(Indica Myron.) Perche' non lo chiedi a quel tuo amichetto arrapato? Sono sicuro che sarebbe molto felice di dirtelo. (Fissa Myron.) Giusto, ragazzo?}
{451}{}{C'e' una persona che dobbiamo ringraziare per il Jet. Hai sentito parlare del piccolo "golden boy" della famiglia Mordino, Myron? Beh, quel piccolo bastardo ha CREATO il Jet. Big Jesus Mordino lo fa sapere a tutti, dove possono trovarlo.}
{452}{}{Parlami di piu' di questo Myron.}
{453}{}{Esiste una qualche cura per il Jet?}
{454}{}{Avrei delle altre domande...}

# 20. WHERE DID JET COME FROM? (18)
{460}{}{Big Jesus Mordino sta pompando il Jet a Redding. E' il tipico gioco di potere. Una volta che il flusso si sara' stabilizzato, quei minatori saranno spacciati.}
{461}{}{Da dove proviene il Jet?}
{463}{}{Capisco. Senti, avrei delle altre domande...}

# 21. TALK ABOUT MYRON (19, 24)
{470}{}{Arrapato come un mandrillo e con la stessa morale. E' un ragazzo sveglio, pero'. Un alto QI. Sta sprecando le sue doti nella produzione di droghe, questo e' certo.}
{471}{}{Dove posso trovarlo?}
{472}{}{Capisco. avrei delle altre domande...}

# 22. WHERE CAN I FIND MYRON? (21)
{480}{}{I Mordino lo hanno messo sotto chiave da qualche parte. Strettamente sorvegliato, probabilmente. Non so esattamente dove.}
{481}{}{Grazie per l'informazione. Posso vedere la tua merce?}

# 23. ANY CURE FOR JET? (19, 20)
{490}{}{Una CURA per la dipendenza da metamfetamine?! Ah! Ne conosco solo due: una e' la morte. L'altra e' chiudersi per un anno in una gabbia senza Jet per permettere all'organismo di sputarlo fuori. Hmmmph. "Cura" un cazzo! Che assurdita'!}
{492}{}{Dev'esserci una cura. Qual e' la composizione chimica del Jet?}

# 24. JET COMPOSITON? (23)
{505}{}{Perche' non lo chiedi al tuo amico? E' lui quello che ha ideato la droga.}
{506}{}{Io la vendo solamente, questa roba. Se fossi in te lo chiederei ad uno scienziato. O a Myron. E' lui quello che ha ideato la droga.}

# 25. TALK ABOUT VILLAGE (6, 42)
{515}{}{(Renesco ti fissa in silenzio.)}
{516}{}{(Renesco ti fissa nuovamente, questa volta in silenzio.)}
{517}{}{Credo che Arroyo ti piacerebbe. E' un villaggio tranquillo. Se si escludono le piante possedute da spiriti malvagi... e, naturalmente, se escludiamo il Tempio delle Prove, pieno di trappole letali e di formiche giganti mangia-uomini.}
{518}{}{Ehi, hai mai sentito parlare di un Kit di Creazione del Giardino dell'Eden? O del Vault 13?}
{519}{}{Okay, allora... meglio che vada.}

# 26. TALK ABOUT VILLAGE 2 (25)
{525}{}{(Renesco continua a guardarti.)}
{526}{}{E talvolta l'Anziana si arrabbia per delle quisquilie, come...eheh...quella notte che ho ignorato il mio voto di castita' e mi sono imboscato nel canyon di Arroyo con Reyna-le-cui-gambe-stringono-con-la-forza-di-mille-serpenti...}
{1526}{}{E talvolta l'Anziana si arrabbia per delle quisquilie, come...eheh...quella notte che ho ignorato il mio voto di castita' e mi sono imboscata nel canyon di Arroyo con Kor-che-tira-come-mille-stalloni...}

# 27. TALK ABOUT VILLAGE 2 (26)
{535}{}{(Renesco ti rivolge un'occhiata fulminante.)}
{536}{}{Me lo ricordo come fosse ieri. Il corpo di Reyna riluceva come argento al chiaro di luna mentre lei si metteva a novan...ehi, sai una cosa? L'Anziana potrebbe piacerti. Avete piu' o meno la stessa eta'.}
{1536}{}{Me lo ricordo come fosse ieri. Il corpo di Kor brillava come bronzo al chiaro di luna mentre mi offrivo a lui e...ehi, sai una cosa? L'Anziana potrebbe piacerti. Avete piu' o meno la stessa eta'.}

# 28. WHO ARE YOU? (27)
{545}{}{(Renesco ti continua a fissare come se, pensandolo abbastanza intensamente, potesse in qualche modo farti scomparire.)}
{546}{}{Ti ho gia' detto che Arroyo e' stato fondato dal mio antenato, il santo Abitante del Vault? Egli compi' un viaggio leggendario da sud, dopo aver sconfitto un terribile malvagio. (Gonfi il petto e guardi in avanti con orgoglio.) Oggi, *io* sono il salvatore della mia tribu', scelto per andare alla ricerca del sacro GECK!}
{547}{}{Okay, allora, basta storie... Sara' meglio che vada. Lode al Vault!}

# 29. GECK? (25, 26, 27, 28, 36)
{555}{}{(Gli occhi di Renesco sussultano.) }
{556}{}{GECK? Cioe' un "Kit di Creazione del Giardino dell'Eden"? Comprensivo di un replicatore base, un lettore di olodischi con estratti dalla Libreria del Congresso e una piccola torcia elettrica?}
{557}{}{Si', ma questo non e' importante, adesso. Non ho ancora finito di parlarti di Arroyo.}
{558}{}{Si'! Il mio villaggio ha dei problemi con i raccolti e il GECK ci serve per salvarli. Sai dove potrei trovarne uno?}
{559}{}{Si dice che sia sigillato all'interno del Vault 13, o almeno cosi' dicono le leggende. Conosci questo luogo?}
{560}{}{Se non vuoi ASCOLTARMI mentre recito le sacre scritture, me ne vado.}
{561}{}{Potrebbe essere. Senti, devo andare.}

# 30. I HAVEN'T FINISHED TELLING YOU ABOUT ARROYO (29)
{570}{}{Al diavolo il tuo sperduto villaggio di fumatori d'erba e tu con lui. Per quale ragione un primate come te sta cercando un GECK?}
{571}{}{Arroyo... il mio sperduto villaggio di fumatori d'erba, come hai detto tu...ha dei problemi con i raccolti. Il GECK ci serve per salvarli.}
{572}{}{Si dice che sia sigillato all'interno del Vault 13. Conosci questo luogo?}
{573}{}{Non penso di volerti far sapere una cosa del genere, per il momento. Ci vediamo.}

# 31. GECK NEEDED TO RESTORE VILLAGE (29, 30)
{580}{}{Hmmmmm. Certamente potrebbe farlo...e facilmente. Se tu riuscissi a trovarne uno. Non so nemmeno dove potresti cominciare le tue ricerche. NCR o Vault City, forse, ma dubito che ne abbiano uno... pero'...}
{581}{}{Pero'...?}

# 32. GECK NEEDED TO RESTORE VILLAGE (31)
{590}{}{Pero', quegli ipocriti bastardi potrebbero essere in grado di darti qualche indicazione. Certo, dovrebbero parlare lentamente e usare parole semplici...}
{591}{}{NCR o Vault City dici? Andro' a cercare questi posti e chiedero' agli abitanti notizie sul GECK. Grazie.}
{592}{}{Perche' mai il GECK non dovrebbe trovarsi all'interno del sacro Vault 13? Le scritture AFFERMANO che il GECK e' sigillato all'interno del sacro Vault 13.}
{593}{}{Molto divertente. Avrei delle altre domande...}
{594}{}{Okay, allora... andro' a controllare. Grazie.}

# 33. GECK NEEDED TO RESTORE VILLAGE (X)
{600}{}{Diavolo no, primate. Ho sentito parlare dei vault, certo, ma mai del Vault 13. La cosa che piu' gli si avvicina e' la Vault City che c'e' a nordest... e se quegli aristocratici damerini hanno vissuto in un Vault, in passato, e' sicuro che adesso non ci vivono piu'.}
{601}{}{Vault City, dici? Andro' a cercare questa Vault City e chiedero' agli abitanti notizie sul GECK. Grazie, Renesco. Lode al Vault! }
{602}{}{"DEI" vault? Esistono altri vault?}
{603}{}{Hmmm. Avrei delle altre domande...}

# 34. THANKS (32, 33, 35)
{610}{}{Se stai per andare a Vault City, non ringraziarmi, primate. Te ne stai meglio qui a New Reno. Qui almeno le persone che ti prendono le misure per la cassa da morto lo fanno onestamente.}
{611}{}{Okay, allora... vado a Vault City. Lode al Vault! }
{612}{}{Capisco. Grazie dell'avvertimento. }

# 35. MORE THAN ONE VAULT? (33)
{620}{}{Perche' credi sia chiamato Vault TREDICI, getta-lance? Cos'e', la tua tribu' era a corto di intelligenza o piu' semplicemente siete soliti eseguire lobotomie rituali per eliminare la vocina della ragione che parla nella vostra testa?}
{623}{}{Ecco, ancora una volta mi rivolgi parole gentili. Grazie... dell'informazione, almeno. }

# 36. YOUR VOCABULARY IS IMPRESSIVE (6, 42)
{630}{}{Il passato di una persona non e' un bell'argomento di conversazione qui a New Reno. Ora: che cosa vuoi?}
{632}{}{Mi sembri proprio un uomo acculturato. Hai mai sentito parlare di un GECK o di un posto chiamato Vault 13?}
{634}{}{Nulla, non importa.}

# 37. GLASSES (3, 42)
{640}{}{(Renesco ti strappa gli occhiali dalle mani e li indossa. I suoi occhi si spalancano.) Santissima Reno! Dunque e' QUESTO l'aspetto di 'sto dannato negozio. (Aggrotta le sopracciglia) Che casino... e cosa c'e' sopra gli scaffali? Sembra merda di brahmin.}
{641}{}{Prego, non c'e' di che...}
{642}{}{Divertiti.}

# 38. YOU'RE WELCOME (37)
{650}{}{Hmpphh! Io...hmmm...ehm...dove li hai presi questi?}
{651}{}{Beh, vedi, c'era questo piccolo radscorpione e c'era questo scienziato che lo stava addestrando e...sai una cosa? Anch'io stento a crederci. Tieniteli e basta, ok?}
{652}{}{Diciamo solo che li ho trovati. Da qualche parte.}

# 39. YOU'RE WELCOME 2 (37)
{660}{}{Ehi! Aspettaunsecondo! Dove li hai presi questi?}
{661}{}{Beh, vedi, c'era questo piccolo radscorpione e c'era questo scienziato che lo stava addestrando e...sai una cosa? Anch'io stento a crederci. Tieniteli e basta, ok?}

# 40. I GOT THEM (38, 39)
{670}{}{Beh, Io...hmnnn...Io...ehm, ti ringrazio. Pensavo che avrei dovuto sopportare queste lenti rotte per il resto della mia vita. Se posso fare qualcosa per te, fammelo sapere...e, ehm, io... ci PENSERO' su.}
{671}{}{Che ne dici di uno sconto?}
{672}{}{Non fa nulla... senti, indossali e stammi bene, okay? Avrei delle altre domande...}
{673}{}{Un giorno - e possa quel giorno non arrivare mai - io ti chiedero' di farmi un favore. Ma fino a quel giorno, accetta questi occhiali come un dono nel giorno del matrimonio di mia figlia. } #Someday - and that day may never come - I'll call upon you to do a service for me. But until that day accept these glasses as a gift on my daughter's wedding day

# 41. DISCOUNT (40)
{680}{}{Ehhh...}
{681}{}{Errr....}
{682}{}{Beh...}
{683}{}{Okay! Okay! Ti faro' uno sconto! Hmphhh.}
{684}{}{Dai. Solo un piccolo sconticino. Dai...}
{687}{}{Ottimo! Vediamo quello che hai, "amico".}
{688}{}{Splendido! Senti, avrei delle altre domande...}
{689}{}{Tornero' piu' tardi. }

# 42. QUESTIONS? (8, 10, 11, 14, 15, 18, 19, 20, 21, 22, 23, 24, 32, 33, 41, 49, 50, 51, 54, 55, 57, 65, 66, 67, 68, 71, 72, 73, 74, 75)
{700}{}{Fa' in fretta.}
{701}{}{Senti, sono un uomo molto occupato...}
{702}{}{Embe'? Sputa il rospo!}
{703}{}{Si'?}
{704}{}{Ti ho mai parlato di Arroyo, il mio villaggio?}
{706}{}{Hai venduto del Jet a Richard Wright?}
{707}{}{Sono venuto a prendere il tributo per Mr. Salvatore.}
{710}{}{Sto cercando dei pezzi di ricambio per la miniera di Broken Hills...}
{711}{}{Hai un vocabolario interessante... sei di queste parti?}
{712}{}{Lasciamo perdere. }

# 43.  TOOLS: SO? (3, 42)
{725}{}{(Socchiude gli occhi.) E allora?}
{726}{}{Beh, mi servono delle parti per riparare il purificatore d'aria nella loro miniera. Mi e' stato detto che tu potevi aiutarmi.}
{727}{}{Beh, mi servono delle parti per riparare il purificatore d'aria nella loro miniera. Mi manda Zaius. Ha detto, uhm...detto...uhm...merda.}
{728}{}{Beh, mi servono delle parti per riparare il purificatore d'aria nella loro miniera. Mi manda Zaius. Ha detto, "Il canarino ha tirato le cuoia".} #kicked the bucket

# 44.  TOOLS: SURE. HERE'S SOME MONEY (43)
{735}{}{Si', si da' il caso che io abbia alcune parti che potrebbero riparare il purificatore d'aria. 100 verdoni.}
{736}{}{Le prendo. Ecco a te.}
{737}{}{Che ne diresti di cinquanta verdoni?}
{738}{}{Uh, non ho un centone con me...tornero' piu' tardi con il denaro. }

# 45.  200 OR NOTHING (3, 42, 44)
{745}{}{Inflazione dovuta ad irritazione del manager nei confronti di quelli che tirano sul prezzo. 200 o non se ne fa niente.}
{746}{}{(Aggrotta le sopracciglia.) 200 o non se ne fa niente.}
{747}{}{Duecento?! Ma se hai detto CENTO un secondo fa!}
{748}{}{Uh, le prendo. Ecco a te.}
{749}{}{Uh, non ho duecento dollari con me...tornero' piu' tardi con il denaro. }

# 46.  HE SAID: SHIT (43)
{755}{}{Dubito FORTEMENTE che abbia detto questo. Non era "Il canarino ha tirato le cuoia", per caso?}
{756}{}{Beh, si'.}

# 47.  HE SAID: AND . . . (43, 46)
{760}{}{E...?}
{761}{}{"E"?}

# 48.  SECOND PART? (47)
{765}{}{E la SECONDA parte e'...?}
{766}{}{"Seconda parte"? Non ha detto nulla a proposito di una SECONDA parte. Quel brutto bast -!}

# 49.  HE DIDN'T?! THAT BASTARD! (44, 45)
{769}{}{Ti stavo solo mettendo alla prova. Non c'e' nessuna seconda parte. Beh, se e' Zaius che ti manda, CREDO di avere qualche pezzo di ricambio da darti. }
{770}{}{Ecco a te. E non farli cadere.}
{771}{}{Grazie. Avrei delle altre domande...}
{772}{}{Uh, grazie. }

# 50. YOU SELL DRUGS TO WRIGHT'S SON? (7, 10, 42)
{780}{}{Non PROVARCI nemmeno ad accusare me. Se vuoi sapere chi l'ha fatto, chiedi a Tweedledum e Tweedledumber se vendono ancora il Jet corretto con l'arsenico.}
{781}{}{"Tweedledum" e "Tweedledumber"? Chi sono?}
{782}{}{Jules ha detto di chiederlo a te. Dice che vendi della merda cattiva.}
{783}{}{Jimmy lo Sfregiato ha detto di chiederlo a te. Dice che vendi della merda cattiva.}
{784}{}{Entrambi mi hanno detto di chiederlo a TE. Dicono che vendi della merda cattiva.}
{785}{}{Non penso fosse arsenico... CREDO invece sia stato avvelenato.}
{786}{}{Mi puoi dire qualcosa a proposito di questa fiala di Jet vuota?}
{788}{}{Andro' a chiederlo a loro, allora. }

# 51. WHO ARE THEY? (50)
{795}{}{Quell'avvoltoio di Jules e quel reprobo bugiardo di Jimmy "lo Sfregiato". Jules e' sempre appollaiato vicino all'entrata della citta' in cerca di visitatori ignoranti da imbrogliare e Jimmy lo Sfregiato vende il Jet sulla Seconda Strada al resto delle bestie di Reno.}
{798}{}{Mi hanno detto di chiederlo a te. Dicono che vendi della merda. Merda che uccide le persone.}
{800}{}{Andro' a parlare con loro, allora. }

# 52. THEY SAID ASK YOU. (51)
{805}{}{Senti, primate...non hai la MINIMA idea di quello che vai cianciando.}
{806}{}{Oh, io credo -}
{807}{}{Davvero? Bene... allora, perche' non -}
{808}{}{Come non detto. Avrei delle altre do -}
{809}{}{Senti, forse farei meglio ad and -}

# 53. THEY SAID ASK YOU 2. (52)
{815}{}{APRI ancora quella tua bocca, o fa' in modo che un FIATO o anche un INDIZIO che io... o tu... possa avere a che fare con l'overdose di quel ragazzo raggiunga Mr. Wright e le nostre vite varranno meno della merda di Brahmin. Se CIO' dovesse accadere --}
{816}{}{Oh? Allora tu -}
{817}{}{Io?! Ehi, aspetta un secon -}

# 54. THEY SAID ASK YOU 3. (53)
{825}{}{Se CIO' dovesse accadere, MERDOSO selvaggio, ti GIURO che morirai prima di me. Adesso, te lo dico per l'ULTIMA volta: quel ragazzo non ha mai neppure comprato della MERDA da me, capito? Non pronunciare MAI piu' il suo nome qui dentro, oppure...} #or so help me
{826}{}{JULES dice che non ha venduto nulla al ragazzo. JIMMY dice che non ha venduto nulla al ragazzo. TU dici che non gli hai venduto nulla. Uno di voi sta mentendo.}
{827}{}{JULES dice che non ha venduto nulla al ragazzo. JIMMY dice che non ha venduto nulla al ragazzo. TU dici che non gli hai venduto nulla. O tutti voi state mentendo, oppure... il responsabile e' qualcun altro.}
{828}{}{Puoi dirmi qualcos'altro a proposito di Richard Wright? Sai se andava in giro con qualcuno che potrebbe far uso di droghe?}
{829}{}{D'accordo...senti, avrei delle altre domande...}
{830}{}{Okay, okay... adesso devo andare. }

# 55. THEY SAID THEY DON'T KNOW. (54)
{835}{}{Posso risponderti facilmente. Uno di quei due bastardi sta mentendo per salvarsi il culo. Quei due vendono il 90% del Jet a Reno, e queste sono le uniche fonti dalle quali il "ragazzo" di cui stiamo parlando puo' averlo preso.}
{836}{}{O da qualcuno che l'ha comprato da uno di voi tre. Chi sono i tuoi clienti dell'ultimo mese che potrebbero aver avuto dei contatti con...la vittima?}
{837}{}{Puoi dirmi qualcos'altro a proposito di Richard Wright? Sai se andava in giro con qualcuno che potrebbe far uso di droghe?}
{838}{}{Capisco...avrei delle altre domande...}
{839}{}{Adesso devo andare. }

# 56. THEY SAID ASK YOU. (55)
{845}{}{STUPIDO bastardo. }
{846}{}{STUPIDA troia. }
{847}{}{Ti avevo DETTO di non pronunciare il suo nome qui dentro. Vattene via! Se ti vedo un'altra volta, TI AMMAZZO. Se Mr. Wright dovesse venire a cercarmi pensando che io abbia ucciso suo figlio, TU morirai prima di me.}
{848}{}{Non minacciarmi, vecchio...}
{849}{}{Whoa. Adesso devo andare. }

# 57. KILLER REVEALED! . . . (55)
{855}{}{NON ne ho idea. Non conoscevo il ragazzo, per cui non conosco i suoi amici O le sue abitudini. L'unico che potrebbe dirtelo con certezza e' troppo occupato a fare il morto al Golgotha per dirtelo.}
{856}{}{Golgotha?}
{858}{}{Ci pensero'. Addio. }

# 58. TRIBUTE (3, 42)
{865}{}{Allora hai fatto un viaggio per niente. Ho PAGATO a Mr. Salvatore il suo "omaggio" *due settimane fa*, come da programma. Io non so chi tu sia, o cosa tu creda di fare, ma non avrai un cent da me. Fuori!}
{866}{}{Senti, nonnetto. Smettila di farmi perdere tempo. Sputa fuori i soldi o ti ritroverai a sputare sangue.}
{867}{}{Io rappresento Mr. Salvatore. Tu mi darai il tributo che ti ho chiesto, e lo farai subito.}
{868}{}{Andro' ad informarmi da Mr. Salvatore riguardo al programma, poi tornero'. }

# 59. TRIBUTE 2 (58)
{875}{}{Sei diventato sordo, ragazzo? }
{876}{}{Sei diventata sorda, ragazza? }
{877}{}{TI HO DETTO CHE HO. GIA'. PAGATO. IL. PIZZO. *Due settimane fa*. Se sei davvero un uomo di Salvatore, dovresti saperlo. Adesso smamma!}
{878}{}{Senti. Per l'ultima volta: tira fuori i quattrini!}
{879}{}{Sei tu quello che e' diventato sordo. Io rappresento Mr. Salvatore e tu pagherai il pizzo.}
{880}{}{Ti avevo avvertito, nonnetto. Vorra' dire che dovro' procedere con le cattive. E' tempo di morire.}
{881}{}{Mi informero' con Mr. Salvatore a proposito del pagamento, poi tornero'. }

# 60. SPEECH SUCCESS (59)
{890}{}{Dimostrami che sei un uomo di Salvatore, e PRENDERO' in considerazione la possibilita' di darti la grana. Altrimenti non avrai un cazzo da me.}
{891}{}{Non ho bisogno di dimostrare un bel nulla. Io sono il suo rappresentante, e questo e' tutto quello che ti serve sapere.}
{892}{}{Cosa? Credi che questa pistola laser ce l'abbia per bellezza?}
{893}{}{Se non mi consegni il pizzo in cinque secondi, io ti UCCIDERO'.}

# 61. SPEECH FAILURE (59, 60)
{900}{}{Vattene via, delinquente da quattro soldi! Fa' vedere la tua faccia qui dentro un'altra volta e ti uccidero' con le mie mani!}
{901}{}{Ti avevo avvisato. Preparati a morire.}

# 62. SHOW OFFICIAL, CAN'T PAY (3, 42, 60)
{910}{}{Hmmmph. Non ha importanza, non posso pagare. L'ultima 'donazione' mi ha lasciato praticamente a secco.}
{911}{}{Questo non mi interessa. Tu mi darai quei soldi adesso. Mr. Salvatore non ha voglia di sentire le tue scuse.}

# 63. GIVE ME MONEY EVEN THOUGH YOU CAN'T PAY (62)
{920}{}{Minacciarmi non ti sara' d'aiuto. Mr. Salvatore vuole i suoi soldi. Io non li ho. S'incazzera' con me, ma anche con te. A Salvatore non PIACCIONO le persone che lo deludono...farai meglio ad escogitare in fretta qualcosa.}
{921}{}{L'ho gia' fatto. Paghero' la tua parte, per questa volta. In cambio, tu mi farai degli sconti nel tuo negozio.}
{924}{}{Cerchero' di inventarmi qualcosa... tornero'.}

# 64. IN EXCHANGE FOR FREE ACCESS TO YOUR STORE (63)
{930}{}{Aspetta un secondo, Neanderthaliano...}
{931}{}{Non discutero' un minuto di piu' con te. La mia pazienza ha raggiunto il limite. Queste sono le mie condizioni.}

# 65. THOSE ARE MY TERMS (64)
{940}{}{Io...senti, ehm, io...hmmmm...d'accordo, allora. Avrai uno..."sconto".}
{941}{}{Fammi vedere la tua merce. Faro' i miei "acquisti" adesso.}
{943}{}{Non voglio niente al momento; ma non temere, tornero'. }

# 66. HOW'S THE GLASSES (64)
{950}{}{(Incrocia le braccia.) Soddisfacente. Se ti aspetti qualche elemosina perche' sei un Buon Samaritano, ti sbagli DI GROSSO. Ora... che cosa vuoi?}
{951}{}{Che Dio maledica il DeathClaw o il direttore del marketing che ti ha generato! VUOI qualcosa?! Ecco! ECCO! Prendi QUESTO! Prendi TUTTO quello che ho! Tutto purche' tu mi LASCI IN PACE!}
{952}{}{Fammi vedere la tua merce.}
{953}{}{Avrei delle domande...}
{955}{}{Cosa diavolo E' questo...? }

# 67. POISONED (50)
{960}{}{Avvelenato? Di cosa stai parlando?}
{961}{}{La condizione del cadavere e' compatibile con l'avvelenamento da veleno di Radscorpione. Credo sia morto perche' il suo Jet era avvelenato e NON in seguito ad un overdose.}
{962}{}{Ho trovato una fiala di Jet vuota nella sua stanza. Al suo interno c'erano tracce di veleno di Radscorpione.}
{963}{}{Lasciamo perdere. Avrei delle altre domande...}
{964}{}{Come non detto. Devo andare adesso. }

# 68. POISONED 2 (67, 73, 74)
{970}{}{Radscorpione...? (Renesco improvvisamente si blocca, come se si fosse ricordato di qualcosa.)}
{971}{}{Brutto figlio di puttana. Sei stato tu ad *avvelenare* il ragazzo, non e' vero?}
{972}{}{Tu ne sai qualcosa, vero?}

# 69. POISONED 3 (68)
{980}{}{Whoa! Aspetta un secondo...!}
{981}{}{Non fare il furbo con me, Renesco! Prova a fregarmi e andrai a far compagnia a Richard. Capito?}
{982}{}{Adesso basta. Io e il signor Wright stiamo per fare un bel discorsetto. Buona giornata, Renesco...o forse dovrei dire "addio".}

# 70. POISONED 4 (69)
{990}{}{Aspetta un secondo! Senti...io non l'ho VENDUTO al ragazzo! Non ha mai comprato NULLA da me! Mi... e' stato CHIESTO di fare un po' di Jet corretto con del veleno di radscorpione, ma... ma io NON l'ho venduto al ragazzo!}
{991}{}{Ti e' stato CHIESTO di fare del Jet avvelenato? Per chi?}
{992}{}{A chi l'hai VENDUTO?}

# 71. POISONED 5 (70)
{995}{}{I Salvatore me l'hanno chiesto -- hanno detto che si trattava di una..."ordinazione speciale". Non sapevo che avessero intenzione di darla al giovane Wright. Tu DEVI credermi... io non avveleno i ragazzi!}
{996}{}{Solo gli adulti, eh, Renesco? Brutto figlio di puttana...}
{997}{}{PERCHE' hai messo il veleno nel Jet? Avresti dovuto sapere che l'avrebbero usato per uccidere.}
{998}{}{D'accordo, d'accordo, ti credo. Avrei delle altre domande...}
{999}{}{Sta' zitto. Senti, avrei delle altre domande...}
{1000}{}{I Salvatore, eh? Credo che Mr. Wright vorra' saperlo. }

# 72. RESPONSE (71)
{1005}{}{I Salvatore POSSIEDONO me, POSSIEDONO questo posto e quando vogliono qualcosa, io glielo do. Se non lo facessi mi ucciderebbero e metterebbero qualcun altro al mio posto. Non avevo intenzione di far del male a quel ragazzo.}
{1007}{}{Sta' zitto. Senti, avrei delle altre domande per te...}
{1008}{}{Certo, sicuramente eri animato da buone intenzioni mentre allungavi quel Jet con il veleno. Addio, Renesco.}
{1009}{}{A dopo, Renesco. }

# 73. JET CANISTER (50)
{1020}{}{E' vuoto. E' una fiala di Jet identica alle centinaia d'altre che puoi trovare a New Reno. Posso esserti d'aiuto con qualcos'altro?}
{1021}{}{Questa ti appartiene?}
{1022}{}{Sai qualcosa a proposito delle tracce di veleno di radscorpione che sono presenti in questa fiala?}
{1023}{}{Certo, avrei delle altre domande...}

# 74. JET CANISTER (73)
{1030}{}{No. Posso aiutarti con QUALCOS'altro?}
{1033}{}{No. Addio. }

# 75. GOLGOTHA? (57)
{1040}{}{Il Golgotha? Un enorme cimitero fuori dalla citta', a sud. Segui la puzza... quella che senti OLTRE alla tua.}
{1041}{}{Oh. Avrei delle altre domande...}
{1042}{}{Continua a parlarmi in questo modo, Renesco, e passerai un bel po' di tempo a fare il morto. } #and you'll be a long time dying
{1043}{}{GRAZIE, Renesco. }

{2000}{}{Hai scoperto che Renesco e' coinvolto nella morte di Richard Wright.}

# END LINES
{5257}{}{ essere cosi' grande. Me va ora }
{5259}{}{ no urlare PERCHE' SE TU CONTINUARE URLARE ME METTE FINE URLARE }
{6259}{}{ UCCIDERE TE}
{5260}{}{...*sniff*... vado a cercare il mio fratellone perche' ti picchi, vecchio! Poi ci mangeremo un gelato e...*sniff*... una TORTA e ci sara' una grossa festa con i clown e...} #...*sniff*...go get big brother to beat you up, vecchio! Then we'll have ice cream and...*sniff*...CAKE
