{100}{}{Vedi un grosso delinquente.}
{101}{}{vedi Rico.}
{150}{}{Vedi un enorme uomo dalla faccia di marmo. Non ti stupiresti se mangiasse mattoni.}
{151}{}{Vedi un enorme uomo dalla faccia di marmo. Non ti stupiresti se mangiasse mattoni.}
{175}{}{Hurggg}
{176}{}{Hnrfff}
{177}{}{Snffff}
{178}{}{Urb-luu}
{179}{}{Klurgggg}
{180}{}{Oog}
{200}{}{Me amico di Monte. Tu amico di Monte?}
{201}{}{Me colpisce persone Monte dire di colpire.}
{202}{}{Me colpisce persone.}
{203}{}{Me colpisce persone con pugni come suonare tamburo.}
{204}{}{Me piace colpire.}
{205}{}{::Sorride senza denti::}
{206}{}{::Si gratta::}
{207}{}{::Gonfia i muscoli::}
{208}{}{Grunt.}
{209}{}{Grunt - Grunt.}
{210}{}{Me no piace parlare.}
{211}{}{Tu odorare buono...}
{212}{}{Tu odorare come mamma.}
{213}{}{Tu carina. Me no colpire te.}
{214}{}{Tu fare me arrossire...}
{215}{}{Uhhh...Me Rico...}
