0. QUICK LOOK (NORMAL)
{100}{}{Vedi una slot machine.}
1. QUICK LOOK (HIGH-ROLLER)
{101}{}{Vedi una scintillante slot machine.}

0. LOOK (NORMAL)
{150}{}{Vedi una slot machine. Giureresti di averla beccata, con la coda dell'occhio, mentre era intenta ad osservarti.}
{151}{}{La sua struttura lucente e la sua leva dorata scintillano sensualmente sotto le luci di New Reno.}
{152}{}{Vedi una scintillante slot machine. E' fatta apposta per i giocatori accaniti…la puntata minima e' di }
{153}{}{ monete.}
{154}{}{Vedi una scintillante slot machine.}

2. FLOAT DIALOGUE (PLAYER = DRUNK OR HIGH) (WTG)
{160}{}{*Vieni a giocare con me per un secondo, cowboy.*}
{161}{}{*Ehila', marinaio.*}
{162}{}{*Inserisci una moneta, tira il braccio. Saro' carina con te.*}
{163}{}{*Tick…Tick…Tiiiiick…*}
{164}{}{*Ehila', bellezza. Vieni a giocare con me.*}
{165}{}{*Ehila', bellezza.*}
{166}{}{*Sei proprio una cosettina carina. Perche' non vieni a giocare con me?*}

3. FLOAT DIALOGUE (NORMAL) (WTG)
{175}{}{*Ding*}
{176}{}{*Bing*}
{177}{}{*Kaaa-ching*}
{178}{}{*Zzzzzzz*}
{179}{}{*Ring-a-ling*}
{180}{}{*Dingity-ding*}

4. RETARD (WTG)
{185}{}{Vedi una strana scatola di metallo dorato con tre occhi e un braccio. E' una delle cose piu' carine che tu abbia mai visto.}
{186}{}{Me }
{187}{}{ chi tu?}
{188}{}{Me manca MAMMA. }
{189}{}{ manca ARR-YO. Me vuole andare casa}
{190}{}{(Le stringi la mano)}
{191}{}{Tu essere strano mutante}
{192}{}{Lode al Vault! Lode al Vault!}
{193}{}{Essere tu Uota-Cip?}
{194}{}{(Allontanati, cerca altre cose luccicose)}
{195}{}{(Vai via.)}

5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{205}{}{La strana e carina scatola di metallo dorato con tre occhi e un braccio non risponde.}
{206}{}{ME }
{207}{}{ TU RISPONDERE ME}
{208}{}{(Le stringi la mano)}
{209}{}{Me figlio di Abitante di Vault. Tu parlare me ORA}
{210}{}{Tu essere strano mutante}
{211}{}{Essere tu Uota-Cip?}
{212}{}{(Allontanati, cerca altre cose luccicose)}
{213}{}{(Vai via.)}

6.  RETARD PULLS HANDLE (4, 5)
{220}{}{Impugni il suo braccio e lo scuoti calorosamente. Appeno la fai, si sente un *bzzzzzzz,* e la scatola parla! "Prego... inserire... monete."}
{221}{}{Aighhhhh! Robot! Robot! Scappare!}
{222}{}{(Vai via.)}

7.  NO MONEY (WTG, 9)
{225}{}{Osservi la slot machine e ti rendi conto, maledicendo la tua poverta', che non hai abbastanza denaro per giocare. Sara' per la prossima volta…}
{226}{}{(Vai via.)}

8.  PLAY. . . ? (WTG, 14, 15)
{230}{}{Vedi una slot machine. La sua struttura lucente e la sua leva dorata scintillano sensualmente sotto le luci di New Reno. La sua fessura per le monete ti chiama a se', e senti il sangue fluire al volto per l'eccitazione.}
{231}{}{(La tua mano trema mentre cerchi le monete. La slot machine continua a sussurrarti.) *Vieni, zucchero…ecco…vieni adesso…non scherzare…*}
{232}{}{(La tua mano trema mentre cerchi le monete. La slot machine continua a sussurrarti.) *Vieni, dolcezza…ecco…impugna il manico…impugnalo saldamente…vieni adesso…*}
{233}{}{Hai }
{234}{}{ monete con te. Vuoi rischiare tutto?}
{235}{}{Hai }
{236}{}{ monete. Vuoi scommettere }
{237}{}{ monete?}
{238}{}{Vuoi scommettere }
{239}{}{ monete?}
{240}{}{Smetti di giocare.}
{241}{}{Smetti di giocare.}

9.  LOOOOOOSER (8)
{245}{}{Gli slot girano, e…non esce nulla.}
{246}{}{NULLA. NULLA! La senti ridere, e ti infuri…i buttafuori sono costretti a strappare con la forza il tuo corpo urlante dalla slot machine.}
{247}{}{(La slot machine ridacchia.) *Ho avuto quello che volevo da questa relazione. Mi spiace, dolcezza. Sta' attento che le porte del casino non ti sbattano sul sedere, quando esci. Ah ah ah ah ah ah ah.*}
{248}{}{Ora ti rimangono }
{249}{}{ monete. Cerchi di recuperare le perdite e continui a giocare?}
{250}{}{Hai }
{251}{}{ moneta rimasta. Vuoi rischiare tutto?}
{252}{}{Sei al verde. Sei costretto a smettere di giocare.}
{253}{}{Sei al verde. Sei costretto a smettere di giocare.}
{254}{}{Smetti di giocare.}
{255}{}{Smetti di giocare.}

10.  WIN x1 (8)
{260}{}{Tre Pugnali. Vinci quello che avevi puntato.}
{261}{}{(La slot machine continua a sussurrarti.) *Dai, zucchero…succede a tutti almeno una volta nella vita…provaci ancora…ti prego…*}
{262}{}{(La slot machine continua a sussurrarti.) *Dai, dolcezza…provaci di nuovo…impugna il manico…impugnalo saldamente…vieni adesso…*}
{263}{}{Hai ancora }
{264}{}{ moneta. Continui a giocare?}
{265}{}{Hai ancora }
{266}{}{ monete. Continui a giocare?}
{267}{}{Smetti di giocare.}
{268}{}{Smetti di giocare.}

11.  WIN x2 (8)
{275}{}{Tre Proiettili! Raddoppi i tuoi soldi!}
{276}{}{(La slot machine emette un gemito di piacere.) *Cosi', zucchero…continua a tirare la leva…piu' veloce, piu' forte, piu' veloce…dai, adesso…*}
{277}{}{(La slot machine emette un gemito di piacere.) *Cosi', dolcezza…continua a tirare il manico…piu' veloce, piu' forte, piu' veloce…dai, adesso…*}
{278}{}{Adesso hai }
{279}{}{ monete! Continui a giocare?}
{280}{}{Smetti di giocare.}
{281}{}{Smetti di giocare.}

12.  WIN x3 (8)
{290}{}{Tre Granate! CAPPERI! Triplichi i tuoi soldi!}
{291}{}{(La slot machine grida di piacere mentre le monete cadono tintinnando nella vaschetta.) *Aieeeeeeee! Cosi', zuccheroh! Oh Dio, si'! Si'! Si', ancora! Piu' veloce! Piu' forte! Che cosa stai aspettando?! Ancora!*}
{292}{}{(La slot machine mugola di piacere mentre le monete cadono tintinnando nella vaschetta.) *Ennnnghhhh! Cosi', dolcezza! Chi sa farti godere?! Chi sa farti godere?!! Ancora! Tira piu' forte questa volta! Piu' forte!*}
{293}{}{Esegui una danza della vittoria, roteando il bacino e lanciando le braccia al cielo, poi prendi un respiro profondo e continui a giocare.}
{294}{}{Evvai: granate! Il bambino ha bisogno di un nuovo paio di scarpe! (Continua a giocare.)}
{295}{}{Adesso hai }
{296}{}{ monete. Continui a giocare?}
{297}{}{Smetti di giocare.}
{298}{}{Smetti di giocare.}

13. DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{305}{}{(Vedi una slot machine. La sua struttura lucente e la sua leva dorata scintillano sensualmente sotto le luci di New Reno. La sua fessura per le monete ti chiama a se', e senti il sangue fluire al volto per l'eccitazione. Come la osservi, una delle sue tre finestrelle ti fa l'occhiolino. Dalla fessura per le monete senti provenire una voce gutturale.) *Beh, perbacco! Ehilaaaaaaa', zucchero. Vuoi far divertire una ragazza?*}
{306}{}{(Vedi una slot machine. La sua struttura solida e ruvida e la sua leva dorata scintillano come un dio solare sotto le luci di New Reno. La sua fessura per le monete ti chiama a se', e senti il sangue fluire al volto per l'eccitazione. Come la osservi, improvvisamente una profonda voce maschile ti sussurra dalla fessura delle monete.) *Non ho mai visto una ragazza bella come te, prima d'ora... Vuoi tentare la fortuna?*}
{307}{}{::Ti dai un pizzicotto::}
{308}{}{Uh…salve?}
{309}{}{::Respiri profondamente, te ne vai.::}

14. DRUNK CONVERSATION 1 (13)
{315}{}{*Sono ancora qui, carina.* (La slot machine abbassa la voce.) *Dai, vieni…vuoi giocare?*}
{316}{}{*Sohno ancora qui, zuccheroh.* (La slot machine abbassa la voce.) *Sei un gran pezzo d'uomo, lo sai? Vieni, dai... non vuoi mettere qualche monetina dentro di me?*}
{317}{}{Chiiii SEI tuuuuu?}
{318}{}{Sherto che vojo sgiocarre con teee}
{319}{}{Penso sia meglio che me ne vada prima di fare qualcosa di cui potrei pentirmi.}
{320}{}{::Respiri profondamente, te ne vai.::}

15. DRUNK 2 (14)
{325}{}{*Sono il tuo uomo ideale.* (La slot machine ti fa l'occhiolino.) *Dammi un po' di monete, e ti faro' godere come MAI nessun uomo ha fatto prima d'ora.*}
{326}{}{*Sono la tua donna ideale, zucchero. Tutto cio' che voglio e' un po' di attenzione. Puoi aiutarmi? Dai, solo una moneta o due?*}
{327}{}{Non posshiamo shemplishemente paarlare?}
{328}{}{Sherto che vojo sgiocarre con teee}
{329}{}{Penso sia meglio che me ne vada prima di fare qualcosa di cui potrei pentirmi.}
{330}{}{::Respiri profondamente, te ne vai.::}

16. DRUNK 3 (15)
{335}{}{*Certo che possiamo, dolcezza, certo che possiamo...* (La slot machine sembra comprensiva.) *Cosa turba la tua piccola dolce testolina?*}
{336}{}{*Certo che possiamo, zucchero, certo che possiamo...* (La slot machine sembra comprensiva.) *Che cosa ti turba, splendore?*}
{337}{}{Me manca MAMMA e manca ARROYO e me...…no trova GECK e…*sniff*}
{338}{}{Me manca MAMMA e Arroyo stato ATTACCATO e me…no sa dove essere loro…e…*sniff*}
{339}{}{Me deve riparare grande barca…e me no sa COME…e la muh-muh-mia Mamma MORTA e...*sniff*}
{340}{}{Ho fiiinito il sgioco... e ora shto sholo vagabondando e... ho paura shia tutto ffinito e... *sniff*}
{341}{}{E' che Fhallowt dueee non s'porta la mia sshcheda 3DFxxxxx e ho shpeso coshi' tanti *shooldi* per comprarla e *sniff*}
{342}{}{Ho provato a creare un bbuon pe...personaggio ma... penso di aver shbajato *completamente* la dishtribusshione dei punti... e ora ho un pershonaggio di meeerda... e...…*sniff*}
{343}{}{Shto parlaando cooon una shlot mmaaashin, devo essher messoooh maleh}
{344}{}{::Respiri profondamente, te ne vai.::}

17. DRUNK 4 (16)
{350}{}{*Su, su... non pensare piu' a queste brutte cose…lascia che mi occupi io di tutto. Su, appoggia la tua testa su di me. Ecco. Sfogati pure.*}
{351}{}{*Su, su... non pensarci piu', zucchero… lascia fare tutto a me. Dai, appoggia la tua splendida testa su di me. Ecco. Sfogati pure.*}
{352}{}{Grascie, shlot mashiiin *sniff* sei la migliore}
{353}{}{Tu shei la shooola persona *buona* che ho incontrato finora... tu-tutti gli altri sono cosi' cattivi e hanno tentato di farmi *male* e di prendere i miei shooldi e…*sniff*}
{354}{}{::Respiri profondamente, te ne vai.::}

18. DRUNK 5 (17)
{360}{}{(Appoggi la tua stanca testa sulla macchina.)}
{361}{}{*Sei sicura di stare bene, dolcezza? Non mi sento tranquillo a lasciarti andare via da sola vedendoti in questo stato.*}
{362}{}{*Sei sicuro di stare bene, zucchero? Non mi sento tranquilla a lasciarti andare via da solo vedendoti in questo stato.*}
{363}{}{Sto bbene…graascie per avver parlato cooon mee, shlot masciin ti amooooo}

19. DRUNK 6 (18)
{370}{}{(Una lacrima sembra formarsi in una delle finestrelle.)}
{371}{}{*Sei la sola eroina che abbiamo in questo piccolo mondo di bastardi e ladri, }
{372}{}{. Adesso devi cercare di farti forza, hai capito, dolcezza?* (Si volta.) *Faresti meglio ad andartene prima che cominci a comportarmi in maniera poco virile.*}
{373}{}{*Sei il solo eroe che abbiamo in questo piccolo mondo di bastardi e ladri, }
{374}{}{. Tu...tu...devi cercare di farti forza, hai capito, zucchero? (Si volta.) *Faresti bene ad andartene prima che cominci a piangere.*}
{375}{}{Sciaaoooo}

20.  PLAY, HIGH-ROLLING MACHINE. . . ? (WTG, 14, 15, 21, 22, 23, 24)
{380}{}{Vedi una slot machine per veri amanti del rischio - la puntata minima e' di }
{381}{}{ monete. La sua struttura lucente e la sua leva dorata scintillano sensualmente sotto le luci di New Reno. La sua fessura per le monete ti chiama a se', e senti il sangue fluire al volto per l'eccitazione.}
{382}{}{(La tua mano trema mentre raggiunge le monete. La slot machine continua a sussurrarti.) *Vieni, zucchero…ecco…vieni adesso…non scherzare…*}
{383}{}{(La tua mano trema mentre raggiunge le monete. La slot machine continua a sussurrarti.) *Vieni, dolcezza…ecco…impugna il manico…impugnalo saldamente…vieni adesso…*}
{384}{}{Hai  }
{385}{}{ monete rimaste. Vuoi rischiare tutto?}
{386}{}{Hai }
{387}{}{ monete. Vuoi puntare }
{388}{}{ monete?}
{389}{}{Vuoi puntare }
{390}{}{ monete?}
{391}{}{Smetti di giocare.}
{392}{}{Smetti di giocare.}

21.  LOOOOOOSER, HIGH-ROLLING (20)
{400}{}{Gli slot girano, e…non esce nulla.}
{401}{}{NULLA. NULLA! La senti ridere, e ti infuri…i buttafuori sono costretti a strappare con la forza il tuo corpo urlante dalla slot machine.}
{402}{}{((La slot machine ridacchia.) *Ho avuto quello che volevo da questa relazione. Mi spiace, dolcezza. Sta' attento che le porte del casino non ti sbattano sul sedere, quando esci. Ah ah ah ah ah ah ah.*}
{403}{}{Adesso ti rimangono }
{404}{}{ monete. Cerchi di recuperare le perdite e continui a giocare?}
{405}{}{Hai }
{406}{}{ monete rimaste. Vuoi rischiare tutto?}
{407}{}{Non puoi piu' permetterti una giocata. Sei costretto a smettere.}
{408}{}{Non puoi piu' permetterti una giocata. Sei costretto a smettere.}
{409}{}{Smetti di giocare.}
{410}{}{Smetti di giocare.}

22.  WIN x1, HIGH-ROLLING (20)
{415}{}{Tre Bombe…vinci quello che avevi puntato.}
{416}{}{(La slot machine continua a sussurrarti.) *Dai, zucchero…succede a tutti almeno una volta nella vita…provaci ancora…ti prego…*}
{417}{}{(La slot machine continua a sussurrarti.) *Dai, dolcezza…provaci di nuovo…impugna il manico…impugnalo saldamente…vai, adesso…*}
{418}{}{Hai ancora }
{419}{}{ monete. Continui a giocare?}
{420}{}{Smetti di giocare.}
{421}{}{Smetti di giocare.}

23.  WIN x2, HIGH-ROLLING (20)
{425}{}{Tre Atomiche! Raddoppi i tuoi soldi!}
{426}{}{(La slot machine emette un gemito di piacere.) *Cosi', zucchero…continua a tirare la leva…piu' veloce, piu' forte, piu' veloce…dai, adesso…*}
{427}{}{(La slot machine emette un gemito di piacere.) *Cosi', dolcezza…continua a tirare il manico…piu' veloce, piu' forte, piu' veloce…dai, adesso…*}
{428}{}{Adesso hai }
{429}{}{ monete! Continui a giocare?}
{430}{}{Smetti di giocare.}
{431}{}{Smetti di giocare.}

24.  WIN x3, HIGH-ROLLING (8)
{435}{}{Tre Funghi Atomici! Triplichi i tuoi soldi!}
{436}{}{(La slot machine grida di piacere mentre le monete cadono tintinnando nella vaschetta.) *Aieeeeeeee! Cosi', zuccheroh! Oh Dio, si'! Si'! Si', ancora! Piu' veloce! Piu' forte! Che cosa stai aspettando?! Ancora!*}
{437}{}{(La slot machine mugola di piacere mentre le monete cadono tintinnando nella vaschetta.) *Ennnnghhhh! Cosi', dolcezza! Chi sa farti godere?! Chi sa farti godere?!! Ancora! Tira piu' forte questa volta! Piu' forte!*}
{438}{}{Esegui una danza della vittoria, roteando il bacino e lanciando le braccia al cielo, poi prendi un respiro profondo e continui a giocare.}
{439}{}{Evvai, funghi atomici! Il bambino ha bisogno di un nuovo paio di scarpe! (Continua a giocare.)}
{440}{}{Adesso hai }
{441}{}{ monete. Continui a giocare?}
{442}{}{Smetti di giocare.}
{443}{}{Smetti di giocare.}

# use gambling skill on table, the +1 is for high roller tables
# critical failures
{1000}{}{The odds don't seem quite right.}
{1001}{}{Odds look right.}
# failures
{1005}{}{You can't gauge the odds for certain.}
{1006}{}{Odds seem to be about right.}
# success
{1010}{}{The odds seem right.}
{1011}{}{The odds don't seem right.}
# critical success
{1015}{}{The odds seem right.}
{1016}{}{The odds don't seem right.}