# 0. QUICK LOOK (WTG)
{100}{}{Vedi una bella "personcina".}
{101}{}{Vedi Stuart Little.}

# 0. LOOK (WTG)
{150}{}{Vedi un nanerottolo che indossa dei vestiti da bambino. Sta masticando uno stuzzicadenti e ti osserva con attenzione.}
{151}{}{Vedi Stuart Little, il minuscolo agente dei pugili. Sta masticando uno stuzzicadenti e ti osserva con attenzione.}
{152}{}{Vedi Stuart Little, il minuscolo agente dei pugili. E' cosi' cariiino. Come un orsacchiotto di pezza, con il pelo rosso e puzzolente.}

# 1. FLOAT DIALOGUES (ENCLAVE_DESTROYED = TRUE + PRIZEFIGHTER) (WTG)
{200}{}{Ragazzo, sapevo che avresti fatto grandi cose, ma non avrei mai creduto che avresti addirittura salvato il mondo. Ottimo.}
{201}{}{Sono fiero di te, ragazzo.}
{202}{}{Ce l'hai fatta, ragazzo. Stuart e' fiero di te.}

# 2. FLOAT DIALOGUES (ENCLAVE_DESTROYED = TRUE) (WTG)
{210}{}{Mi sarebbe piaciuto vedere come il tuo pugno si faceva strada attraverso la guardia dell'Enclave.}
{211}{}{La battaglia contro l'Enclave dev'essere stata qualcosa di spettacolare. Diamine.}
{212}{}{Ah! Hai mai pensato di usare la tua forza sul RING, oltre che per salvare il mondo?}

# 3. FLOAT [MALE, PRIZEFIGHTER] (WTG)
{220}{}{Come butta, campione?}
{221}{}{Mi sembri in forma, amico.}
{222}{}{I tuoi pugni sono pugni d'oro.}
{223}{}{Ragazzo, tu mangi fulmini e cachi tuoni.}
{224}{}{Ti sei liberato di quel figlio di puttana come ci si libera di una cattiva abitudine. Ottimo lavoro.}
{225}{}{Sono felice di aver puntato su di te, dolcezza.}
{226}{}{Mi sembri in forma, cara.}

# 5. FLOAT DIALOGUES NORMAL (WTG)
{230}{}{Mi serve qualche nuovo talento...}
{231}{}{Culi di piombo buoni a nulla...}
{232}{}{Se solo fossi un pochino piu' alto...}
{233}{}{Questi ragazzi combattono di merda...}

# 6. INTRO (WTG)
{240}{}{(Il nanerottolo ti studia mentre ti avvicini a lui, poi si toglie lo stuzzicadenti dalla bocca.) }
{241}{}{Gia'... Che cosa VUOI, ragazzone?}
{242}{}{Cosa posso fare per te, zucchero?}
{243}{}{Ehila', eroe. Cosa posso fare per te?}
{244}{}{Hunh?}
{245}{}{Perche' tu cooooosi' piccolo?}
{246}{}{[Allontanati.]}
{247}{}{Chi sei?}
{248}{}{Niente. Stavo solo dando un'occhiata in giro.}

# 7. HUNH?/ME NO LOOK PRETTY/WHY YOU SOOO SMALL? (6)
{250}{}{(Ti fa cenno di smammare.) Sparisci, testa di cazzo. Mi stai facendo perdere del tempo.}
{251}{}{Me no mago, me no sa sparire. Ma me andare via, ora.}

# 8. HUNH? [EXCEPT THE PLAYER LOOKS LIKE A FIGHTER] (6)
{260}{}{(Sospira, sembra quasi essere sul punto di dire qualcosa, poi si blocca e osserva il tuo corpo.) Hai mai fatto dei combattimenti? Sembreresti essere bell'e pronto per cominciare a combattere.}
{261}{}{Me combatte MOLTO. Me combatte te?}
{262}{}{Me no sembrare bello. Tu piacere uomini? Me disposto.}

# 9. ME FIGHT A LOT. ME FIGHT YOU? (8)
{270}{}{No, no... sto parlando di combattere sul RING! Sai, il ring? (indica il ring, mima dei pugni.) E' una cosa che potrebbe interessarti?}
{271}{}{(Dai un pugno sul muso all'ometto e prendi i suoi soldi per il pranzo)}
{272}{}{Ah-hah}
{273}{}{Me puo' avere gelato se me combatte?}
{274}{}{Nah-ah}
{275}{}{Me sposato all'avenciura. Me andare.}

# 10. PUNCH HIM BACK (9)
{280}{}{(Fa un salto indietro.) Ehi, testa di cazzo! Conserva queste cose per il ring. Ascolta: sei dentro o fuori?}
{281}{}{Me dentro.}
{283}{}{Me fuori.}

# 11. UH-HUH (9, 10)
{290}{}{(Sorride.) Bene, allora siamo d'accordo. Io sono Stuart; molti mi chiamano Stuart Little, ma solo perche'... beh, tutto quello che serve sapere A TE e' che sono grande in tutte le cose importanti. Hai un nome, testa di cazzo?}
{291}{}{Me }
{292}{}{Me...ah...me...}
{293}{}{Me Grande Stu}
{296}{}{[Allontanati in cerca di avventure.]}

# 12. ALL RIGHT NAME (11)
{300}{}{Me-a-me, eh? "Miami..." Mi PIACE. Mi PIACE. D'accordo, allora: vediamo di fare un po' di danni.}
{301}{}{(Aggrotta le sopracciglia.) Facciamo gli spiritosi, eh? Hmmph... non si riesce ad avere il minimo rispetto, in questa citta'. (Alza le spalle) D'accordo, allora: vediamo di fare un po' di danni.}
{302}{}{, eh? D'accordo, }
{1302}{}{ vediamo di fare un po' di danni.}
{305}{}{[Scappa e nasconditi.]}

# 13. SEXY (22)
{310}{}{(Sbuffa con indignazione.) Guarda. Anche se la mia altezza non rientra nella cosiddetta "media", cio' non significa che debba ricorrere a metodi sostitutivi per avere un po' di eccitazione.} ###???Just because I'm not of so-called "average height" does not mean I have to receive my thrills vicariously
{311}{}{Davvero?}

# 14. RETARD LOSE (WTG)
{320}{}{Sparisci dalla mia vista, testa di cazzo. In questa citta' non c'e' speranza per te. Smamma!}
{321}{}{Non avrei MAI dovuto darti la mia fiducia... che delusione assoluta. Adesso vattene! Smamma!}
{322}{}{ME }
{1322}{}{ NO TESTA CAZZO ME UCCIDE TE UCCIDE TE UCCIDE T--}
{323}{}{E dove essere gelato?}
{324}{}{[Scappa via piangendo.]}
{326}{}{[Sorridi placidamente, annuisci, poi lo attacchi.]}
{327}{}{Dammi un'altra possibilita', Stuart. Dai, solo UNA. Posso farcela!}
{328}{}{[Te ne vai.]}
{329}{}{(Stuart ti guarda con disgusto mentre vieni trascinato fuori dal ring.) }

# 15. ANOTHER CHANCE...HELL NO (14, 24)
{330}{}{Cosa c'e'? Il Masticatore ti ha per caso strappato le orecchie a morsi, ragazzo?! }
{331}{}{Cosa c'e'? Il Masticatore ti ha per caso strappato le orecchie a morsi, ragazza?! }
{332}{}{Ti ho detto di SMAMMARE! Vattene da qui!}
{333}{}{[Picchia il chiassoso ometto dai capelli rossi.]}
{334}{}{[Ti allontani colmo di rabbia.]}
{336}{}{[Te ne vai.]}
{337}{}{(Diventa rosso.) }

# 16. ANOTHER CHANCE...HELL NO (14, 24)
{340}{}{Un'altra possibilita'. A me va il 75%... e niente discussioni.}
{341}{}{Un'altra possibilita'. A me va sempre il 75%... e niente discussioni.}
{342}{}{Ci sto. Sono pronto per combattere ancora. Fa' strada, Stuart.}
{343}{}{Ci sto. Dammi un po' di tempo per riposarmi e saro' pronto per combattere ancora.}
{344}{}{Non vale la pena soffrire cosi' tanto.} ###???Nothing's worth this much grief
{345}{}{(Stuart diventa rosso, come se stesse per cominciare ad urlare, poi si calma.) D'accordo. }
{346}{}{Sgarra un'altra volta e sei fuori.}

# 17. RETARD/NORMAL WIN (WTG)
{350}{}{(Stuart sta sorridendo come uno sciacallo.) Davvero un'ottima performance, }
{1350}{}{... tutto bene, ti senti in forma? Fammi sapere quando sei pronto per il prossimo incontro.}
{351}{}{Me pronto ora PRONTO FARE DANNI ORA ORA}
{352}{}{Me fa breve sonnellino poi me pronto combattere ancora.}
{353}{}{Me vuole gelato.}
{355}{}{Sono pronto. Al lavoro!}
{356}{}{Lasciami riposare un attimo, poi saro' pronto.}
{357}{}{Credo di averne avuto abbastanza di questo mondo, Stuart... lassu', sul ring, ho visto la morte e mi ha spaventato. Appendo i guantoni al chiodo.}

# 18. ICE CREAM (9, 10, 17)
{360}{}{(Il nanerottolo sbatte le palpebre, poi aggrotta le sopracciglia) Gela-CHE?}
{361}{}{Il Gelato Colato fa venire il Conato} ###???I scream, you scream, everybody screams for ice cream
{362}{}{Uh-uh. GELATO}
{363}{}{[Allontanati in cerca di avventure.]}

# 19. ICE CREAM (18)
{370}{}{(Il nanerottolo sorride a fatica.) }
{371}{}{Beh, qualcosa di "dolce" te lo posso anche procurare, amico... ma si tratta di prostitute o di droghe di vario tipo... nient'altro. }
{372}{}{Beh, qualcosa di "dolce" te lo posso anche procurare, cara... ma si tratta di uomini da marciapiede o di droghe di vario tipo... nient'altro. }
{373}{}{Ora... vuoi combattere o no?}
{374}{}{Okay}
{375}{}{Me vuole riposare un po' prima.}
{376}{}{Nah}

# 20. NUH-UH/NAW (9, 10, 17, 19)
{380}{}{Beh, non voglio costringerti, ma avremmo formato proprio una bella coppia, io e te. Insieme saremmo arrivati in men che non si dica al top dei top, dritti nel firmamento dei grandi campioni... torna da me, se cambi idea. Tu sei oro puro, ragazzo.}

# 21. WIN, FIGHT AGAIN (17, 24, 30, 31)
{390}{}{D'accordo, allora! Diamo inizio alle danze!}
{391}{}{[Seguilo.]}

# 22. WHO ARE YOU? (6, 40)
{400}{}{Cos... non hai MAI sentito parlare di me? Stuart, Stuart Little? Il piu' grande agente di tutta Reno? }
{401}{}{Qualcuno ti ha fatto un bel dispetto, amico, non parlandoti di me. }
{402}{}{Qualcuno ti ha fatto un bel dispetto, cara, non parlandoti di me. }
{404}{}{Hmmmph. Ok. Come ti chiami?}
{405}{}{}
{1405}{}{.}
{1406}{}{, e voglio boxare. Puoi aiutarmi?}
{407}{}{Hai mai lavorato in un circo, Stuart?}
{408}{}{"Stuart Little"?}
{409}{}{Oltre alle gambe c'e' di piu', Stuart. Quindi fa' il bravo, altrimenti per te sara' ancora piu' difficile avere un appuntamento galante in questa citta'. Siamo intesi?} ###???There's a little more to me than my legs, Stuart. So be polite, or else you're going to have even more trouble getting a date in this town, all right
{410}{}{Veramente stavo solo dando un'occhiata in giro. Ci vediamo dopo, Stuart.}
{411}{}{(Si rimette lo stuzzicadenti in bocca e comincia a morderlo) Hai un nome?}
{412}{}{(Ti guarda dall'alto in basso.) Hai un nome, oltre a quelle gambe?}

# 23. I'M X (22, 33)
{420}{}{(Stuart annuisce.) }
{421}{}{D'accordo, }
{1421}{}{. Piacere di fare la tua conoscenza. }
{422}{}{... }
{1422}{}{... Mi piace. E' un bel nome. Beh, e' un piacere fare la tua conoscenza, }
{3422}{}{. }
{423}{}{Che cosa posso fare per te?}
{424}{}{Vorrei boxare. Tu puoi aiutarmi?}

# 24. BOXED BEFORE (WTG)
{430}{}{(Stuart annuisce e sorride mentre ti avvicini.) Ehi, eroe! Ho sentito quello che hai fatto. Congratulazioni. Cosa ti porta qui?}
{431}{}{(Stuart annuisce mentre ti avvicini.) Eeeeehi, }
{1431}{}{! Come va? Sei pronto per tornare sul ring?}
{432}{}{(Stuart ghigna mentre ti avvicini.) Beh, che mi venga un colpo se non e' "}
{1432}{}{". Che cosa ti riporta da queste parti?}
{433}{}{Me vuole combattere ancora}
{434}{}{Il cielo. Ciaaaaao}
{435}{}{Sono prooooonto alla lotta.}
{436}{}{Dammi un'altra possibilita', Stuart. POSSO farcela! Dai...}
{437}{}{Niente. Stavo solo dando un'occhiata in giro.}

# 25. OFFER TO BOX, PC DOESN'T MATCH UP (23, 33)
{440}{}{Vuoi BOXARE? Uh... d'accordo, voglio essere onesto con te, ragazzo. Non credo proprio che tu abbia il fisico adatto.}
{441}{}{Vuoi BOXARE? Beh, adesso le ho proprio sentite tutte. Ascolta, le principali opportunita' di lavoro per le donne vengono dal settore... hmmm. Beh, forse quel tipo di lavoro non e' adatto a te.} ###???Well, from the looks of it, maybe those jobs weren't cut out for you
{442}{}{Vuoi BOXARE? Beh, adesso le ho proprio sentite tutte. Senti, non voglio essere scortese o altro, e' solo che la boxe e' un sporto BRUTTO&CATTIVO... e anche le persone che lo praticano rischiano di diventare brutte. Nel tuo caso, sarebbe un vero peccato.}
{444}{}{Dammi una possibilita', e io dimentichero' la PICCOLA battuta che hai appena fatto.}
{445}{}{Dammi una possibilita', Stuart.}
{446}{}{Oh, al diavolo queste stronzate. Me ne vado.}

# 26. CHANCE (FAIL) (25)
{450}{}{No, mi dispiace, cara, troppi rischi... la boxe non e' fatta per le donne. Ora tornatene a casa, okay?}
{451}{}{No, mi dispiace, amico, troppi rischi... sarebbe un massacro. Ora tornatene a casa, okay?}
{452}{}{Non esistono molte donne pugili, Stuart, e' questo che voglio dirti. Tu saresti il primo agente a gestire una donna pugile. La gente accorrerebbe a FROTTE per vedermi.}
{453}{}{Ma e' proprio quello che voglio dirti, Stu...posso chiamarti Stu, vero?...Sarebbe un VERO massacro. Sai quanta attenzione potrebbe catalizzare? Sarebbe come andare ad assistere ad un'esecuzione!}
{454}{}{Oh, queste sono soltanto stronzate. Me ne vado.}

# 27. CHANCE (FAIL AGAIN) (25, 26, 27)
{460}{}{No, mi dispiace, cara, troppi rischi... probabilmente non ti lascerebbero nemmeno combattere. Adesso tornatene a casa, okay?}
{461}{}{No, mi dispiace, amico, non sarebbe un massacro divertente. Adesso tornatene a casa, okay?}
{462}{}{Ci sono dei rischi, certo... ma sai, Stuart, potrei anche *spogliarmi un po'* mentre mi trovo sul ring. Una cosa del genere attirerebbe piu' gente di quanta si sia mai vista qui dentro...}
{463}{}{Oh, queste sono soltanto stronzate. Me ne vado.}

# 28. STRONG FELLA, AGREES (23, 25, 26, 27, 33)
{470}{}{Hmmmmm...d'accordo, ti daro' una possibilita'... ma non ti prometto nulla. Se questo danneggia i miei affari, anche in maniera lieve, tu sei fuori. (Mette le mani sui fianchi.) Io prendo la meta' della vincita, e niente discussioni su questo punto.}
{471}{}{Hmmmmm...Ti daro' una possibilita'... ma non ti prometto nulla; ti sto facendo un favore, prendendo uno sconosciuto qualsiasi sotto la mia ala. Io prendo la meta' delle vincite... niente discussioni su questo punto.}
{472}{}{Ci sto.}
{473}{}{Accontentati del 25%, e l'accordo e' fatto.}
{474}{}{Oh, queste sono soltanto stronzate. Me ne vado.}

# 29. WE'VE REACHED AN AGREEMENT (28)
{480}{}{(L'accigliamento di Stuart si fa piu' marcato. Sembra stia per protestare, poi scuote la testa con un sorrisetto.) D'accordo, allora! Se hai finito di ridurre all'osso i miei mezzi di sostentamento, vediamo di discutere meglio la cosa.}
{481}{}{Okay...}

# 30. YOU'RE GONNA NEED A HANDLE (28, 29, 32)
{490}{}{D'accordo... (Stuart ti guarda.) Ti serve un nome... sai, un soprannome facile da ricordare. Qualcosa che sembri "tosto". "Cattivo". Tipo }
{1490}{}{ il Tifone, }
{2490}{}{ il Rissoso... sai, cose di questo genere.}

# 31. SPECIAL HANDLE (30)
{500}{}{(Il nanerottolo aggrotta le sopracciglia.) Ma non era morto tempo fa contro quel tipo che veniva dalla Russia? Aw, lasciamo perdere. Possiamo andare sul ring?}
{501}{}{(Il nanerottolo aggrotta le sopracciglia.) Credo proprio che tu e il "Masticatore" andrete d'amore e d'accordo. Vedi solo di non mordere via troppe orecchie. Bene... possiamo andare sul ring?}
{502}{}{(Il nanerottolo aggrotta le sopracciglia.) Non hai l'aspetto di un Russo. Ma se sta bene a te... possiamo andare sul ring?}
{503}{}{(Il nanerottolo aggrotta le sopracciglia.) Beh, okay... ma speriamo che la TUA carriera vada da qualche parte. Possiamo andare sul ring, adesso?} ###???"Pity the fo," eh?
{504}{}{(Il nanerottolo aggrotta le sopracciglia.) Gli occhi della tigre, eh? "Adriaaanaaaaa", "Adriaaanaaaaa"... Eh eh. Mi piace... e' un nome di un certo peso. Possiamo salire sul ring?}
{505}{}{(Il nanerottolo annuisce.) }
{2505}{}{... non male, non male. Ti si addice. (Fa un cenno con la testa verso il ring.) Possiamo cominciare, allora? Sei pronto?}
{506}{}{Cominciamo.}

# 32. WE HAVE NOT REACHED AN AGREEMENT (28)
{510}{}{Scordatelo. Fifty-fifty o NIENTE. Se non ti piace la cosa, vattene.}
{511}{}{Va bene. Anche se non sapevo che esistessero vampiri della tua taglia.}
{512}{}{Okay. 50/50. E adesso?}
{513}{}{Ho detto 25/75? VOLEVO dire 50/50. Divideremo i profitti esattamente a meta'. Nessun problema.}
{514}{}{[Vattene.]}

# 33. STUART LITTLE (22, 33, 39)
{520}{}{Si', si', lo so, "Stuart Little". Mia madre leggeva molto E. B. White. Ora... ce l'hai un nome?}
{521}{}{Hmmpph. Ce l'hai un nome?}
{526}{}{Piacere di conoscerti, Stu. Non ho tempo per parlare, adesso. Ci vediamo dopo.}

# 34. DONE MUCH CIRCUS WORK IN YOUR LIFE? (33)
{530}{}{E che cosa ti fa pensare che io abbia mai visto uno spettacolo circense, o, peggio, che io sia stato rapito da un circo?}
{531}{}{Uh...beh, mi pare che molti dei cittadini di New Reno si comportino come se fossero appena usciti da un circo, e quindi pensavo che...}

# 35. DONE MUCH CIRCUS WORK IN YOUR LIFE? (34)
{540}{}{TU pensavi che, poiche' sono una persona di bassa statura, l'unica carriera che potevo intraprendere era quella di essere rinchiuso in un cosiddetto "circo"!}
{541}{}{Uh...beh, io...}

# 36. DONE MUCH CIRCUS WORK IN YOUR LIFE? (35)
{550}{}{Mi hai dato solo una RAPIDA occhiata e hai pensato di conoscere la mia intera vita. Non ti sarebbe mai passato per l'anticamera del cervello che una persona della mia statura potesse far carriera come *agente di pugili*.}
{551}{}{Mi dispiace, non volevo offenderti.}

# 37. I MEANT NO OFFENSE . . . (36)
{560}{}{E perche' avrei dovuto offendermi? Solo perche' sembra che tutti, in questo gioco, abbiano il vizio di dare giudizi istantanei sugli altri PNG, basandosi solamente sul loro aspetto fisico?}
{561}{}{Beh, non so cosa tu intenda per giudizio ISTANTANEO...}

# 38. . . . (37)
{570}{}{Beh, io ho fatto la stessa cosa con te, ad esempio.}
{571}{}{Oh?}

# 39. . . . (42)
{580}{}{(Ti guarda pietosamente.) Ma non capisci la TRAGEDIA? Io ti avevo erroneamente ridotto ad uno stereotipo, ad una caricatura, ad un generico modello umano di Fallout, piuttosto che considerarti come una persona unica e particolare.}
{581}{}{Uh, ma Stuart, io SONO il tipico modello di eroe. Infatti io sono il personaggio giocante di questo gioco.}

# 40. UH (13)
{590}{}{Non tutte le donne sono attratte dai modelli umani maschili dal torace possente e dai muscoli super-pompati. Rimarresti sorpreso nello scoprire quante donne trovino la mia taglia affascinante e ATTRAENTE.}
{591}{}{E tu rimarresti sorpreso nello scoprire quanti maschi la pensino come loro.}

# 41. . . . (38)
{600}{}{Mi sono lasciato ingannare dal tuo fisico ridicolmente super-muscoloso, dal tuo audace comportamento da Mad Maxx dei poveri, dalla tua distribuzione di punti-personaggio priva di fantasia e ti ho bollato come un bulletto rissoso.} mini maxing munchkin
{601}{}{Mi sono lasciato ingannare dal tuo seno iper-pixellato, dalla tua ridicola andatura sculettante, dalla tua distribuzione di punti-personaggio priva di fantasia e ti ho bollato come una Laura Kroft dei poveri...una "bulletta".}
{602}{}{Io...}

# 42. . . . (41)
{610}{}{Non sei nient'altro che il tipico "Modello Maschile di Eroe di GdR" e, se vuoi, uno di TANTI modelli simili; cosi' tanti che sembrano essere presenti in massa, in questo mondo.}
{611}{}{Non sei nient'altro che il tipico "Modello Femminile di Eroe di GdR" e, se vuoi, uno di TANTI modelli simili; cosi' tanti che sembrano essere presenti in massa, in questo mondo.}
{612}{}{Beh...}
