{100}{}{Vedi un pugile.}
{101}{}{Vedi Mike "il Masticatore."}
{150}{}{Le sue braccia sono grosse come tronchi d'albero.}
{151}{}{Quei pugni sembrano piu' pesanti di palle di cannone.}
{152}{}{Quando si muove e' come trovarsi di fronte a uno tsunami di muscoli.}
{153}{}{Ti osserva l'orecchio con aria affamata.}
{154}{}{La sua faccia sembra una grossa bistecca di manzo.}
{158}{}{Hurgghhh}
{159}{}{Gunhrrhh}
{160}{}{Mike schiaccia.}
{161}{}{Adoro il gelato alla vaniglia.}
{162}{}{Gnarrrr}
{163}{}{Nrrrurhhh}
{164}{}{Mike ama le orecchie.}
{165}{}{Orecchie... mmmmmmm.}
{166}{}{Grrrrrr}
{167}{}{Gr. Gr? Grrrrrrr.}
{168}{}{Gr?}
{169}{}{Rrrgggg}
{170}{}{Me mangia orecchie.}
{171}{}{Orecchie... yum.}
{172}{}{Gr...grrrgr?}
{173}{}{Snrggg}
{174}{}{Me odia Robbin' Givens.}
{175}{}{Grrrrrgrrrrgrrr...grrr...grrr...grr! Grr! Grrr?}
{176}{}{Cosa significa 'percentuale'?}
{200}{}{::Mike si copre quando ti avvicini::}
{201}{}{::Mike piagnucola quando ti avvicini::}
{202}{}{::Mike alza le mani in segno di resa quando ti avvicini::}
{203}{}{Tu carina.}
{204}{}{Me piace tue orecchie.}
{205}{}{Basta parlare. Andiamo a letto.}
{206}{}{Robin? Sei tu?}
