# quick look
{100}{}{Vedi un pugile.}
{101}{}{Vedi Mike "il Masticatore."}

# examines
{150}{}{Le sue braccia sono grosse come tronchi d'albero.}
{151}{}{Quei pugni sembrano piu' pesanti di palle di cannone.}
{152}{}{Quando si muove e' come trovarsi di fronte a uno tsunami di muscoli.}
{153}{}{Ti osserva l'orecchio con l'aria di uno che ha una gran fame.}
{154}{}{La sua faccia sembra una grossa bistecca di manzo.}

# FLOAT DIALOGUE
{158}{}{Hurgghhh.}
{159}{}{Gunhrrhh}
{160}{}{Mike schiaccia}
{161}{}{Adoro il gelato alla vaniglia}
{162}{}{Gnarrrr}
{163}{}{Nrrrurhhh}
{164}{}{Mike ama le orecchie}
{165}{}{Orecchie... mmmmmmm}
{166}{}{Grrrrrr}
{167}{}{Gr. Gr? Grrrrrrr.}
{168}{}{Gr?}
{169}{}{Rrrgggg}
{170}{}{Me mangia orecchie}
{171}{}{Orecchie... yum}
{172}{}{Gr...grrrgr?}
{173}{}{Snrggg}
{174}{}{Me odia Robbin' Givens}
{175}{}{Grrrrrgrrrrgrrr...grrr...grrr...grr! Grr! Grrr?}
{176}{}{Cosa significa 'percentuale'?}

# CLICK DIALOGUE
# (PRIZEFIGHTER)
{200}{}{::Mike si copre quando ti avvicini::}
{201}{}{::Mike piagnucola quando ti avvicini::}
{202}{}{::Mike alza le mani in segno di resa quando ti avvicini::}
# (FEMALE, ANY BUT PRIZEFIGHTER)
{203}{}{Tu carina }
{204}{}{me piace tue orecchie}
{205}{}{Parlato abbastanza. Ora a letto}
{206}{}{Robin? Sei tu?}
