# QUICK LOOK
{100}{}{Vedi uno dei bambini degli Wright. }

# LOOK (IF MALE) (WTG)
{150}{}{Vedi un ragazzino con i capelli neri.}
{151}{}{Vedi una ragazzina con i capelli neri. I suoi capelli corti, tagliati alla bell'e meglio, te l'hanno fatta quasi scambiare per un maschio.}

{155}{}{Ti fa una linguaccia.}
{156}{}{Ti sta fissando con un'aria imbronciata.}
{157}{}{Ti fa una linguaccia.}
{158}{}{I capelli neri di questa bambina sono stati tagliati in modo tale da poter comodamente utilizzare gli sprite del modello "maschio: bambino" anche per questo PNG.}
{159}{}{Ti sta fissando con un'aria imbronciata.}

# 2. FLOAT [ENCLAVE_DESTROYED = TRUE] (WTG)
{175}{}{Fallout 2 vi e' stato offerto da Letter Z.}
{176}{}{Ehi! }
{177}{}{}
{178}{}{Grazie per averci salvato, }
{179}{}{Quando saro' grande voglio salvare il mondo proprio come te.}
{180}{}{Quando saro' grande posso anch'io diventare un eroe?}
{181}{}{Quando saro' grande voglio essere come }

# 3. FLOAT [POWER ARMOR] (WTG)
{190}{}{Sei un ROBOT?}
{191}{}{Come fai a fare pipi' in quel coso?}
{192}{}{Posso arrampicarmi sulle tue spalle? Ti preeego?}
{193}{}{Vuoi giocare con noi? Daaaaai?}

# 4. FLOAT AND CLICK [SLAVER OR BAD REP] (WTG)
{200}{}{Faresti meglio ad andartene prima che il mio papa' ti veda.}
{201}{}{Faresti meglio ad andartene prima che i miei fratelli ti vedano.}
{202}{}{Sei una persona cattiva. Faresti meglio ad andartene prima che vada a chiamare i miei fratelli.}

# 5. FLOAT AND CLICK [SNEAKING] (WTG)
{210}{}{Ti ho visto! Ti ho visto!}
{211}{}{Stai giocando a nascondino? Posso giocare anch'io?}

# 6. FLOAT COMMENTS [ROBOBRAIN + MARCUS] (WTG)
{215}{}{Guardate il robot! Guardate il robot!}
{216}{}{Quel cervello dentro al robot e' un cervello veeero?}
{217}{}{Oooooooh. Guardate il robot!}
{218}{}{Guardate il mutante! Guardate il mutante!}
{219}{}{Mutante, mutande, mutante, mutande.} ###???Mutante, stoopant, mutante, stoopant
{220}{}{Quello e' un vero mutante? E' "bruttiffimo".}
{221}{}{Oooooooh. Guardate il mutante!}
{222}{}{Quel mutante e' GROSSO. Piu' grosso del mio papa'.}

# 7. FLOAT COMMENTS [LENNY + DOG] (WTG)
{230}{}{Un ghoul! Guardate, e' un ghoul!}
{231}{}{Ewwwwwww! Ghoul! Ghoul!}
{232}{}{Ghouliiino ghouliiino ghouliiino!}
{233}{}{Guardate il cagnolino di metallo!}
{234}{}{Cagnolino! Qui, cagnolino!}
{235}{}{Anch'io voglio un cucciolo!}


# 10. FLOAT [ENCLAVE_DESTROYED = TRUE] (WTG)
{290}{}{Quando saro' grande voglio salvare il mondo proprio come hai fatto tu.}
{291}{}{Quando saro' grande posso anch'io diventare un eroe?}
{292}{}{Quando saro' grande voglio essere come te.}
{293}{}{Perche' tu volere essere come me? Me STUPIDO}
{294}{}{Me ha usato testa di ragazza come cappello, una volta.}
{295}{}{[Allontanati]}
{296}{}{Eh-eh. Beh, grazie, piccoletto. Ma ascolta il consiglio che ti da' }
{297}{}{Insegui sempre i tuoi sogni. Possono diventare realta'. Io ne sono la prova vivente.}
{298}{}{Ma certo. Senti... mi dispiace per quello che e' successo a tuo fratello Richie. Tu sai cosa gli e' successo?}
{299}{}{Una volta ho attraversato ben tre stati usando la testa di una bambina come cappello.}
{300}{}{[Lascialo giocare.]}
{301}{}{[Lasciala giocare.]}

# 11. WHY YOU WANNA BE ME? ME DUMB. (10)
{310}{}{Nah-ah! Tu sei SVEGLIO! Tu sei un EROE e sei CORAGGIOSO e io voglio essere come TE quando saro' grande. Grazie per averci salvati, }
{311}{}{Gazzie piccola persona. Tu fatto }

# 12. FOLLOW YOUR DREAMS. (10)
{315}{}{Okay, }
{316}{}{Adesso devo andare. Mi raccomando, eh? Ho delle faccende "da eroe" delle quali occuparmi.}

# 13. I'VE GOT SOME THINGS TO DO. (12)
{320}{}{(il bambino ti ferma.) Um... }
{321}{}{Uh...no. Lo prometto.}
{322}{}{Uh...questa e' una cosa che non posso dirti.}
{323}{}{Non preoccuparti, piccolo. Tornero' a trovarvi con un altro personaggio.}
{324}{}{Non temere, piccolo. Non sentirai niente.}

# 14. UH, HARD DRIVE (13)
{330}{}{Sogneremo?}
{331}{}{Uh...certo. Certamente.}
{332}{}{E che ne so? Io credo di non aver mai sognato, quindi probabilmente neanche voi lo farete. La vita fa proprio schifo, eh?}

# 15. POWER ARMOR 1 (WTG)
{341}{}{Cosa essere Rombo'?}
{344}{}{Eh-eh. Ma che carino che sei. No, piccolo, non sono un robot.}
{345}{}{No, no, sotto questa armatura c'e' una persona normale. A proposito, mi dispiace per tuo fratello Richie. Tu sai cosa gli e' successo?}

# 16. WATZ A ROBOT?/YER DUMB, PEE-FACE/MOOTANT? (15, 25, 27, 29, 41)
{355}{}{STUPIDO.}
{356}{}{ANCHE TU}
{357}{}{Come te, solo che tu essere di piu'}
{358}{}{TU essere piu' stupido}
{359}{}{Chi lo dice sa di esserlo}
{360}{}{Specchio riflesso!}
{361}{}{-Scappa via piangendo-}

# 17. YER DUMBERR (16)
{370}{}{Tu sei lo stupido piu' stupido in un mondo di stupidi in un universo di stupidi!}

# 18. POOR RESPONSE (16, 17)
{395}{}{Nah-ah, SCEMO! (Il bambino corre via, mentre la sua risata risuona crudelmente nelle tue orecchie.)}
{396}{}{Me no vuole parlare con te... *snfff*... me... *snfff*... fa una FESTA... con *snfff* TORTA e GELATO... e TU non venire [Te ne vai.]}

# 19. YER DUMB-ESSTT-ERR (17)
{405}{}{(Il bambino sbatte gli occhi, apre la bocca e poi la richiude. Sul suo viso si forma una lacrima che subito si trasforma in un pianto a dirotto.)}
{406}{}{Eh eh, ME vinto!}

# 20. I'M NOT A ROBOT (15, 28)
{410}{}{Oh. (Ci pensa un attimo, poi ti guarda con sospetto.) Perche' non sei un robot?}
{411}{}{Uh... perche'... beh, i robot e le persone hanno parti... ehm, diverse.}
{412}{}{Devo andare.}

# 21. ROBOTS AND PEOPLE HAVE DIFFERENT PARTS (20)
{425}{}{Ah, si'? (Sempre piu' sospettoso.) Ad esempio?}
{426}{}{Uh...beh...senti, bambino, la tua mamma e il tuo papa' non te l'hanno spiegato?}
{427}{}{Uh...urca! Guarda che ore sono! Devo andare.}

# 22. DIDN'T MOMMY AND DADDY EXPLAIN THIS TO YOU? (21)
{435}{}{Spiegato cosa?}
{436}{}{Uh...beh...i robot...hanno l'olio, dentro. Gli umani...beh, gli umani...sanguinano.}

# 23. HUMANS BLEED (22)
{445}{}{La mia mamma e le mie sorelle grandi sanguinano ogni mese circa. Poi diventano molto scontrose. Vorrei tanto che fossero robot.}
{446}{}{Uh...certo. Magnifico. Senti, adesso devo andare - non dire a tua madre che hai parlato con me.}

# 24. POWER ARMOR 2 (WTG)
{456}{}{Me fa pipi' qui dentro. Me deve solo abituarsi a puzza.}
{459}{}{Eh eh. In realta', la pipi' la faccio dentro l'armatura. L'urina viene poi riciclata, come le altre cose. Interessante, no? Tu sai cosa vuol dire "riciclare", eh, piccolo?}
{460}{}{Di certo non e' comodo. Senti, mi spiace per tuo fratello Richie. Tu sai cosa gli e' successo?}

# 25. I PEE IN ARMOR (24)
{475}{}{Che SCHIFO.}
{476}{}{Si'! Riciclare vuol dire che ti bevi la tua pipi'!}
{477}{}{TU SCHIFO, FACCIA di pipi'!}
{479}{}{Uh, eh...eheh. Veramente vuol dire che...}

# 26. NO, ACTUALLY, IT MEANS . . . (25, 26)
{485}{}{Tu bevi la pipi'! Tu bevi la pipi'!}
{486}{}{Uh, eh...eheh...abbassa la voce, piccolo...riciclare non significa che bevo la mia p... beh, non ESATTAMENTE almeno...cioe'...}
{487}{}{-Lascia che lo stronzetto torni a giocare con i suoi amici-}
{488}{}{-Te ne vai-}

# 27. CLICK [ROBOBRAIN] (WTG)
{495}{}{Quello e' un robot VERO?}
{499}{}{Il Robobrain? Beh, si': lo e'.}
{500}{}{Lui CREDE di esserlo. Non ricominciamo con questa storia.} ###???It THINKS it is. Don't even get me started
{501}{}{Si', ma non dargli fastidio. Credo voglia distruggere la razza umana.}
{502}{}{Si', lo e'. Senti, mi dispiace per tuo fratello Richie. Tu sai cosa gli e' successo?}

# 28. CLICK [ROBOBRAIN] (27)
{515}{}{Anche TU sei un robot?}

# 29. CLICK [MARCUS] (WTG)
{525}{}{E' un VERO mutante, quello?}
{526}{}{Mutande?}
{529}{}{Beh, si'. Si chiama Marcus. Non aver paura, non morde.}
{530}{}{Beh, si': E' un mutante. Gosh, spero proprio che non abbia fame di bambini...}
{531}{}{Beh, si'. Un mutante molto AFFAMATO. Ed e' quasi ora del suo spuntino. Una fortunata coincidenza.}
{532}{}{Si', lo e'. Senti, mi dispiace per tuo fratello Richie. Tu sai cosa gli e' successo?}

# 30. INTRO (WTG)
{540}{}{(Il bambino si ferma e ti guarda.)}
{541}{}{Ciaooooo}
{544}{}{Ciao, piccolo.}
{545}{}{Ehila', piccola.}
{546}{}{Mi dispiace per tuo fratello Richie. Tu sai cosa gli e' successo?}

# 31. I DROVE THROUGH 3 STATES . . . (10, 15, 24, 27, 29 30, 41)
{555}{}{Sei malato?}
{556}{}{Perche' me lo chiedi?}

# 32. WHY DO YOU ASK? (31)
{560}{}{Tu sembri DAVVERO malato.}
{561}{}{Sono malato.}

# 33. I AM SICK. (32)
{565}{}{Prendi la medicina?}
{566}{}{Non c'e' medicina per la mia malattia.}

# 34. THERE IS NO MEDICINE FOR WHAT I HAVE. (33)
{570}{}{Vuoi cantare?}
{571}{}{Cantare?}

# 35. SING? (34)
{575}{}{Conosci "E l'universo intero e' con Lui?"}
{576}{}{Si', la conosco.}

# 36. YES, I DO. (35)
{580}{}{::Canta:: "E l'universo intero e' con Lui. E l'universo intero e' con Lui." Dai.}
{581}{}{::Canta:: "E l'universo intero e' con Lui. E l'universo intero e' con Lui."}

# 37. SING TOGETHER (36)
{585}{}{::Cantando insieme:: "E l'universo intero e' con Lui." ::Cantando piu' piano:: "E l'universo intero e' con Lui."}
{586}{}{Grazie per aver cantato con me. Magari tornero' piu' tardi... se mi servira' un cappello.}

# 38. HELLO, LITTLE MAN/WOMAN. (14, 37)
{590}{}{(Il bambino ti strizza l'occhio.)}
{591}{}{D'accordo. Ci vediamo.}

# 39. TALK TO YOU LATER/LET HIM GO BACK TO PLAYING/THANKS FOR SINGING WITH ME (38)
{595}{}{(Il bambino corre via.)}

# 40. HELLO (MALE) (30, 40, 42)
{648}{}{Oh.}
{650}{}{Davvero? Cos'altro?}

# 41. CLICK [LENNY] (WTG)
{665}{}{E' un VERO ghoul, quello?}
{666}{}{Guul?}
{669}{}{Beh, si', lo e'. Si chiama Lenny. Non aver paura, non morde.}
{670}{}{Beh, si': E' un ghoul. Gosh, spero proprio che non abbia fame di bambini...}
{671}{}{Beh, si'. Un ghoul molto AFFAMATO. Ed e' quasi ora del suo spuntino. Una fortunata coincidenza.}

# 42. HIS NAME IS MARCUS. (29, 40, 41)
{685}{}{Ciao, mutante Mar-cus. Sei davvero grosso. Hee-hee... e la tua animazione mentre ti muovi e' davvero buffa.}
{686}{}{Ciao, ghoul Len-ee. Phew... puzzi davvero tanto.}
{687}{}{Vero, eh? Allora... che succede, ragazzo?}
{688}{}{Vero, eh? Allora... che succede, ragazzo?}
{689}{}{Beh, devo andare. Ci vediamo.}

# 43. MARCUS/LENNY IS HUNGRY (29, 40, 41)
{695}{}{(Il bambino impallidisce, poi scappa via, urlando.)}
{696}{}{Eh eh eh eh. "E' un VERO mutante?" Questo gli insegnera' a non fare domande.}
{697}{}{Un mutante "affamato"! Pfui. Tutti sanno che i mutanti non mangiano gli uom - uh, perche' mi guardi a quel modo, Marcus?}
{698}{}{Eh eh eh eh. "E' un VERO ghoul?" Questo gli insegnera' a non fare domande.}
{699}{}{Un ghoul "affamato"! Pfui. Tutti sanno che i ghoul non mangiano gli uom - uh, perche' mi guardi a quel modo, Lenny?}

# 44. OD (10, 15, 24, 27, 29, 30, 40, 41)
{710}{}{Uh-uh. Il papa' e' davvero arrabbiato perche' non sa chi ha ucciso Richie. Dice che se mai dovesse beccarci a farci di Jet, ci prendera' a cinghiate.}
{711}{}{Tu sai CHI potrebbe aver dato a Richie il Jet che l'ha ucciso?}
{712}{}{Tu sai DOVE Richie ha preso il Jet che l'ha ucciso?}
{713}{}{-Lascia che il piccolo torni a giocare-}

# 45. DO YOU KNOW WHO? (44, 46)
{720}{}{Uh-uh.}

# 46. DO YOU KNOW WHERE? (44, 45)
{730}{}{Uh-uh. Passava molto nella zona ovest della citta', vicino alla Zona Commerciale, e papa' ci ha detto di non andare laggiu'.}

# sleeping
{800}{}{*Shhh* Dovrei gia' essere addormentato.}
{801}{}{Ho bisogno di dormire un po'. Domani ci sara' una bella partita a insetto guerriero di metallo.}
{802}{}{Se papa' scopre che non sto dormendo, si arrabbiera' moltissimo.}

# 8/40. FLOAT [WRIGHT CHILDREN: BOYS] (WTG)
{900}{}{Ambaraba' cicci' cocco'.} ###???My ding-a-ling, my ding-a-ling
{901}{}{::Alza una pistola finta:: Va' all'inferno, carogna!}
{902}{}{Specchio di gomma, la parola ti ritorna.}
{903}{}{Quando saro' grande voglio fare il pappone.}
{904}{}{Quando saro' grande dominero' New Reno, proprio come il mio papa'.}
{905}{}{Voglio un animaletto domestico. Papa' dice che quando saro' grande mi dara' una donna.}
{906}{}{Vorrei tanto che papa' fosse forte come Tommy the Balls.}
{907}{}{Ho un pene.}
# self_is_male ^
{908}{}{::Strilla::}
{909}{}{::Tira fuori la lingua::}
{910}{}{Papa' dice che la mamma e' una fabbrica di bambini.}
{911}{}{Papa' ha detto che ci frustera' se ci dovesse beccare a prendere il Jet.}
{912}{}{Papa' dice che quando andiamo fuori dobbiamo stare attenti.}
{913}{}{Papa' ci frustera' se andremo ancora in giro senza il suo permesso.}
{914}{}{Papa' e' molto nervoso da quando mio fratello Richie e' morto.}
{915}{}{Papa' e' di nuovo in affari.}
{916}{}{Padre Tully quando non riesce a camminare dritto e' davvero buffo.}
{917}{}{E l'universo intero e' con Lui...E l'universo intero e' con Lui...}
{918}{}{Ho fatto la pupu'.}
{919}{}{Mi manca Richie, mio fratello. E' morto perche' ha preso troppo tanto Jet.}
{920}{}{Non vedo piu' Christopher.}
{921}{}{Ho visto Mikey che baciava Meri Mordino.}
{922}{}{Ho visto la mamma e il papa' che saltavano l'uno sull'altro.}
{923}{}{Vorrei che Christopher giocasse con me.}
{924}{}{Kyle si beve la sua pipi'!}
{925}{}{Kyle se l'e' fatta addosso.} ###???squirts
{926}{}{Indovina indovinello, Kyle e' proprio senza cervello.}
{927}{}{Guardami! Guardami!}
{928}{}{Mikey e Meri sotto un albero... e si B-A-C-I-A-V-A-N-O.}
{929}{}{Milicent e' cattivo.}
{930}{}{Latte, Latte, limonata. E la torta e' preparata.}
{931}{}{Mamma e papa' hanno parlato ancora con Dio a letto, ieri notte.}
{932}{}{Ho visto la mamma che piangeva. Credo sia per quello che e' successo a mio fratello Richie.}
{933}{}{La mamma e' molto triste da quando mio fratello Richie e' morto.}
{934}{}{La mamma e' andata di nuovo in chiesa.} ###???Mommy's down by the church again
{935}{}{La nostra famiglia e' la migliore.}
{936}{}{Phfttttt!}
{937}{}{Testa di cacca! Testa di cacca!}
{938}{}{Lo zio Nick dice che le parolacce non servono. Lo zio Nick dovrebbe darsi una svegliata.}
{939}{}{Vuoi giocare a selvaggi e schiavisti?}
{940}{}{Abbiamo diciassette fratelli e sorelle.}
{941}{}{Wheeeeeeee!}
{942}{}{Ce l'hai tu!}
{943}{}{Hai i pidocchi!}
{944}{}{Sembri un radscorpione!}
# self_is_female v
{945}{}{Chiedero' a papa' se posso diventare una troia, quando saro' grande. Dice sempre che gliene servirebbe una.}
{946}{}{Quando saro' grande voglio diventare una troia. Papa' dice che dovremmo averne di piu'.}
{947}{}{Ho una vagina.}

# line endings
{1176}{}{! Raccontaci la storia dell'Enclave! Per favore?}
{1177}{}{! Yaaaaay!}
{1178}{}{!}
{1181}{}{.}
{1296}{}{: quando sarai grande potrai diventare TUTTO cio' che vuoi.}
{1310}{}{. Non ti dimentichero' MAI.}
{1311}{}{ si sente meglio. Me felice me salvato voi}
{1315}{}{. Non lo dimentichero', lo prometto, anche se dovessi vivere cent'anni.}
{1320}{}{? Adesso che hai finito il gioco, ci cancellerai dal tuo hard disk?}
