# 0.  LOOK, CLOSED (WTG)
{100}{}{Vedi una cassaforte incassata saldamente nel muro. E' chiusa.}

# 1.  LOOK, OPEN (WTG)
{150}{}{Vedi una cassaforte incassata saldamente nel muro. E' aperta.}

# 2.  EXAMINE SAFE, CLOSED (WTG)
{200}{}{(C'e' una piccola porta nel muro. Dev'essere la casa di una persona davvero molto, molto piccola! Al centro della porta c'e' una maniglia con dei numeri sopra.)}
{000}{}{-Allontanati-}

# 3.  SAFE IS OPEN (WTG, 7)
{220}{}{(Si sente un KER-KLANK, e la cassaforte si apre.)}

# 5.  CLICKING (2, 5, 6, 8)
{240}{}{(Giri lentamente la manopola per svariati minuti, ma non riesci ad ottenere alcunche'.)}

# 6.  TRAPS . . . ? (2, 6, 8)
{260}{}{(Non trovi trappole collegate alla cassaforte.)}

# 7.  SPIN RANDOM, SUCCEED (2, 5, 6, 8, 9)
{270}{}{(Stai girando la maniglia... quando improvvisamente si sente un KER-KLANK, e la porta si apre!)}

# 8.  SPIN RANDOM, FAIL (2, 5, 6, 8, 9)
{280}{}{(Giri la maniglia, ma la porticina non si apre!)}

# 9.  HELLO? (2, 8, 9)
{300}{}{(Non senti nessuno e non riesci a vedere il campanello. Forse in casa non c'e' nessuno.)}
