# 0.  LOOK, CLOSED (WTG)
{100}{}{Vedi una cassaforte incassata saldamente nel muro. E' chiusa.}

# 1.  LOOK, OPEN (WTG)
{150}{}{Vedi una cassaforte incassata saldamente nel muro. E' aperta.}

# 2.  EXAMINE SAFE, CLOSED (WTG)
{200}{}{(C'e' una piccola porta nel muro. Dev'essere la casa di una persona davvero molto, molto piccola! Al centro della porta c'e' una maniglia con dei numeri sopra.)}
{000}{}{(Esamini la cassaforte a muro. Sembra saldamente ancorata nel muro e all'esterno ha una manopola numerata per inserire la combinazione.)}
{000}{}{Bussa alla porta}
{000}{}{Gira la maniglia}
{000}{}{-Allontanati-}
{000}{}{[SSS]}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Gira la manopola a caso.}
{000}{}{Esamina la cassaforte in cerca di trappole.}
{000}{}{Lascia stare la cassaforte.}

# 3.  SAFE IS OPEN (WTG, 2, 5, 6, 7, 8)
{220}{}{(Si sente un KER-KLANK, e la cassaforte si apre.)}
{000}{}{(La cassaforte e' aperta.)}
{000}{}{(La porta si spalanca. L'interno della casettina e' davveeeeero buio. E piccino.)}
{000}{}{(La porta e' aperta. L'interno e' davveeeeero buio. E piccino.)}
{000}{}{Vedi se c'e' qualcuno in casa}
{000}{}{-Allontanati-}
{000}{}{Controlla il fondo della cassaforte in cerca dello scompartimento segreto menzionato dalla signora Bishop.}
{000}{}{Svuota la cassaforte.}
{000}{}{Lascia stare la cassaforte.}

# 4.  OPEN COMPARTMENT (3)
{230}{}{(Apri un piccolo pannello sul fondo della cassaforte. Dubiti che saresti riuscito a trovarlo se la signora Bishop non te ne avesse parlato. All'interno c'e' uno strano dispositivo da collegare al pip-boy.)}
{000}{}{Prendilo, puoi svuota il resto della cassaforte.}

# 5.  CLICKING (2, 5, 6, 8)
{240}{}{(Giri lentamente la manopola per svariati minuti, ma non riesci ad ottenere alcunche'.)}
{000}{}{[SSS]}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Gira la manopola a caso.}
{000}{}{Esamina la cassaforte in cerca di trappole.}
{000}{}{Lascia stare la cassaforte.}

# 6.  TRAPS . . . ? (2, 6, 8)
{250}{}{(Non trovi trappole collegate alla cassaforte.)}
{000}{}{[SSS]}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Gira la manopola a caso.}
{000}{}{Esamina la cassaforte in cerca di trappole.}
{000}{}{Lascia stare la cassaforte.}

# 7.  SPIN RANDOM, SUCCEED (2, 5, 6, 8, 9)
{260}{}{(Stai girando la maniglia... quando improvvisamente si sente un KER-KLANK, e la porta si apre!)}
{000}{}{(Stai girando la manopola a caso, quando improvvisamente la manopola prende un numero... si sente un KER-KLANK, e la cassaforte si spalanca!)}
{000}{}{Ehila'? Ehillaaaa'? Nessuno in casa?}
{000}{}{Yeah, *io* ho proprio il tocco magico...}

# 8.  SPIN RANDOM, FAIL (2, 5, 6, 8, 9)
{270}{}{(Giri la maniglia, ma la porticina non si apre!)}
{000}{}{(Giri la manopola per diversi minuti, ma non succede nulla.)}
{000}{}{Bussa alla porta}
{000}{}{Continua a girare la manopola}
{000}{}{-Allontanati-}
{000}{}{[SSS]}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Gira la manopola, presta attenzione al rumore dei meccanismi interni.}
{000}{}{Continua a girare la manopola a caso.}
{000}{}{Esamina la cassaforte in cerca di trappole.}
{000}{}{Lascia stare la cassaforte.}

# 9.  HELLO? (2, 8, 9)
{290}{}{(Non senti nessuno e non riesci a vedere il campanello. Forse in casa non c'e' nessuno.)}
{000}{}{(Nessuno viene ad aprire la porta.)}
{000}{}{(La tua mano comincia a farti male.)}
{000}{}{(Anche se c'e' qualcuno in casa, non viene ad aprirti la porta.)}
{000}{}{Bussa ancora una volta}
{000}{}{Gira la maniglia}
{000}{}{-Allontanati-}