# 0.  LOOK, CLOSED (WTG)
{100}{}{Vedi una cassaforte a combinazione incassata saldamente nel muro. E' chiusa.}

# 1.  LOOK, OPEN (WTG)
{101}{}{Vedi una cassaforte a combinazione incassata saldamente nel muro. E' aperta.}

# LOCKPICKING
# trapped
{120}{}{Proprio mentre stai per cominciare a scassinare la cassaforte, noti un filo che va ad infilarsi nel muro appena sotto la cassaforte. Sembra proprio che questa bastarda sia collegata ad una trappola.}
{121}{}{C'e' sempre una trappola collegata alla cassaforte.}

# successfull unlock
{150}{}{Si sente un KER-KLANK e la cassaforte si apre.}

# lucky unlock
{160}{}{Stai girando la manopola a caso, quando improvvisamente la manopola prende un numero... si sente un KER-KLANK e la cassaforte si apre.}

# failed unlocks
{170}{}{Giri lentamente la manopola per svariati minuti, ma non riesci ad ottenere alcunche'.}
{171}{}{Giri la manopola per diversi minuti, ma non succede nulla.}

# TRAPS
# disarm
{180}{}{Trovi una trappola collegata alla cassaforte e riesci a disattivarla.}
{181}{}{Disattivi con successo la trappola collegata alla cassaforte.}

# find trap
{190}{}{Trovi una trappola collegata alla cassaforte, ma non riesci a disattivarla.}

# fail
{200}{}{Non sembrano esserci trappole collegate alla cassaforte.}
{201}{}{Non riesci a disattivare la trappola collegata alla cassaforte.}

# fail critical

# CHANGING COMBO ON SAFE
# trap needs re-arming
{220}{}{Sara' meglio riarmare la trappola collegata alla cassaforte con dell'esplosivo al plastico o con della dinamite, prima.}

# changed combination
{230}{}{La combinazione della cassaforte e' stata cambiata con successo... eh eh eh...}
{231}{}{La combinazione della cassaforte e' stata cambiata con successo... di nuovo.}

# no skills
{240}{}{Non hai l'abilita' necessaria per cambiare la combinazione.}
{241}{}{ non ha l'abilita' necessaria per cambiare la combinazione.}

# it's open
{250}{}{La cassaforte deve essere chiusa.}

# REARMING TRAP
{260}{}{Sembra che ci sia gia' una trappola collegata alla cassaforte.}

{270}{}{Non riesci a collegare una trappola alla cassaforte.}
{271}{}{ non riesce a collegare una trappola alla cassaforte.}

{280}{}{La trappola collegata alla cassaforte e' stata riattivata con successo.}

# trap_boom
{300}{}{Senti un boato sordo provenire dal piano di sopra.}

{400}{}{Apri un piccolo pannello sul fondo della cassaforte. Dubiti che saresti riuscito a trovarlo se la signora Bishop non te ne avesse parlato. All'interno c'e' uno strano dispositivo da collegare al pip-boy.}

# critical fail
{290}{}{Mentre esamini la cassaforte in cerca di una trappola, provochi un'esplosione.}
{291}{}{Hai tirato il filo sbagliato mentre disarmavi la trappola.}