# 1.  DISPLAY (WTG)
{100}{}{Vedi un'enorme vasca per la fermentazione dell'alcol. Sta emettendo un lieve rumore sommesso.}

# 2.  DISPLAY (WTG)
{110}{}{Vedi un'enorme vasca per la fermentazione dell'alcol. Al suo interno galleggia la coda del radscorpione.}

# 3.  DISPLAY (WTG)
{120}{}{Vedi un'enorme vasca per la fermentazione dell'alcol. E' rotta, e il danno sembra irreparabile.}

# 4.  DISPLAY (WTG)
{130}{}{La vasca si blocca con un rumore sinistro. Sembra essere irreparabilmente danneggiata.}

# 5.  DISPLAY (WTG)
{140}{}{La fai cadere nella vasca, e la guardi affondare sul fondo, mentre il veleno fuoriesce dalla sacca velenifera.}

# 6.  DISPLAY (WTG)
{150}{}{Il danno sembra irreparabile.}

# destroyed
{300}{}{Hai distrutto i distillatori della famiglia Wright.}

# working
{250}{}{Hmmmmmmmm}
{251}{}{Thmmmmmmm}

# Broken
{200}{}{::Ker-chunk::}
{201}{}{::Klunk::}
{202}{}{::Whirrrr-klunk::}
{203}{}{::Kerrrrr-chunk::}
{204}{}{::Kzzztttt::}
