#############################################################
#  Message File: obj_dude.msg                               #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: April 14, 1998                                  #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{}
{101}{}{}

#############################################################

{110}{}{I tuoi piedi prudono terribilmente.}
{120}{}{Ti stanno venendo dei brutti calli su entrambi gli alluci.}
{130}{}{Le tue scarpe sono davvero strette; quei calli si stanno infiammando.}
{140}{}{Quei due brutti calli sembrano essersi trasformati in due dita aggiuntive. Ma almeno quel continuo e doloroso prurito se n'e' andato.}
{141}{}{Oh mio Dio, e' Bess!}

{150}{}{Guadagni }
{151}{}{ punti esperienza per aver recuperato il GECK.}
