{100}{}{Vedi un'imponente figura corazzata dall'aspetto umano.}
{101}{}{Vedi Frank Horrigan, agente del Servizio Segreto.}
{102}{}{Vedi un'enorme creatura umanoide che ti fissa con uno sguardo di puro odio.}
{103}{}{Non uscirai vivo da qui, mutante.}
{104}{}{Dannato mutante.}
{105}{}{Sporco mutante rosso!}
{106}{}{Hai distrutto tutti noi.}
{107}{}{Pagherai per quel che hai fatto.}

# Node 2
{108}{ssa2}{Tu (cough)... tu non hai vinto. Tu e quei bastardi dei tuoi amici mutanti mi raggiungerete presto all'inferno in una vecchia, cara nube nucleare. Ho appena attivato l'autodistruzione. Eh, eh (cough, cough...) Il Progetto andra' avanti. Non avete fatto nulla qui, se non firmare le vostre stesse condanne a morte.  Dovere, (cough) onore... coraggio... Semper Fiiiii........}
{109}{ssa2}{Tu (cough), tu non hai vinto. Tu e quei bastardi dei tuoi amici mutanti mi raggiungerete presto all'inferno in una vecchia, cara nube nucleare. Ho appena attivato l'autodistruzione. Eh, eh (cough, cough,...) Il Progetto andra' avanti. Non avete fatto nulla qui, se non firmare le vostre stesse condanne a morte.  Dovere, (cough) onore... coraggio... Semper Fiiiii........}
{110}{}{Uh-oh. Cose brutte succedere qui. Me corre subito a nave.}
{111}{}{Sara' meglio raggiungere in fretta la nave e tagliare la corda il piu' presto possibile.}

# Node 3
{112}{ssa3alt}{Sei arrivato piu' lontano di quanto avresti dovuto; d'altronde non avevi ancora incontrato Frank Horrigan. La tua corsa finisce qui, mutante. E' tempo di morire.} ###???You've gotten a lot farther than you should have, but then you haven't met Frank Horrigan either
{113}{}{Riusciro' a batterti, che tu lo voglia o no.}
{114}{}{Non possiamo discuterne?}

# Node 4
{115}{ssa4a}{L'aver liberato nell'aria la tossina F.E.V. non fa di te un eroe. Tu sei soltanto un mutante qualsiasi che deve essere soppresso.}
{116}{ssa4b}{L'aver provocato la fusione del nucleo del nostro reattore significa che presto l'atmosfera qui diventera' piuttosto bollente. E' un vero peccato che tu non vivrai abbastanza a lungo da vederlo. Tu non sei un eroe, sei soltanto un cadavere ambulante.}
{117}{}{Per parlare sai parlare, ma quanto al fare, lo sai fare? Io non credo proprio.}
{118}{}{Aspetta un minuto! Aspetta! Non possiamo discuterne?}

# Node 5
{119}{ssa5}{L'abbiamo appena fatto. Il tempo per parlare e' finito.}
{120}{}{Allora facciamola finita.}
{121}{}{Aspetta!}

# Node 6
{140}{ssa6}{Feccia mutante! Me l'aspettavo che avresti provato uno stratagemma come questo. Non ti aiutera', comunque. Nulla puo' aiutarti, adesso.}
{141}{}{Passero' sul tuo cadavere e non c'e' niente che tu possa fare.}
{142}{}{Aspetta, parliamone.}

# Node 7
{130}{ssa7}{Io, Frank Horrigan, ecco chi. Servizio Segreto degli Stati Uniti. Non andrai da nessuna parte.}
{131}{}{Mi lascerai passare, che tu lo voglia o no.}
{132}{}{Aspetta un secondo, parliamone.}
{133}{}{Non andro' da nessuna parte finche' non avro' cancellato il tuo brutto muso dalla faccia della terra.}

# Additional PC responses to Node 3
{134}{}{Eh? Frank chi?}

# Additional PC responses to Node 4
{135}{}{C'e' solo un mutante qui, e quello sei tu. E' tempo di morire, mostro.}


