{100}{}{Vedi un personaggio che bara.}
{101}{}{Questo tizio non dovrebbe essere qui.}
{102}{}{Ehi, è un personaggio che bara.}
{103}{}{Ehi, questo fa male.}
{104}{}{Ciao, cosa vorresti che succedesse?}
{105}{}{Impostazione dei flag di Westin.}
{106}{}{Impostare “Accetta l’eliminazione di Westin”?}
{107}{}{Annulla “Accetta l’eliminazione di Westin”.}
{108}{}{Imposta Westin come morto.}
{109}{}{Annulla “Westin morto”.}
{110}{}{Imposta “Annulla l’eliminazione di Westin”.}
{111}{}{Annulla “Annulla l’eliminazione di Westin”.}
{112}{}{Imposta “Westin conosce le droghe”.}
{113}{}{Annulla “Westin conosce le droghe”.}
{114}{}{Imposta “Fallimento di Westin”.}
{115}{}{Annulla “Fallimento di Westin”.}
{116}{}{Imposta “Westin completato”.}
{117}{}{Annulla “Westin completato”.}
{118}{}{Imposta “Westin conosce lo snuff”.}
{119}{}{Annulla “Westin conosce lo snuff”.}
{120}{}{Impostazione dei flag di Carlson.}
{121}{}{Imposta “Carlson accetta l’eliminazione”.}
{122}{}{Annulla “Carlson accetta l’eliminazione”.}
{123}{}{Imposta “Carlson morto”.}
{124}{}{Annulla “Carlson morto”.}
{125}{}{Imposta “Carlson in servizio di sicurezza”.}
{126}{}{Annulla “Carlson in servizio di sicurezza”.}
{127}{}{Imposta “Carlson annulla l’eliminazione”.}
{128}{}{Annulla “Carlson annulla l’eliminazione”.}
{129}{}{Imposta “Carlson completato”.}
{130}{}{Annulla “Carlson completato”.}
{131}{}{Imposta “Carlson fallito”.}
{132}{}{Annulla “Carlson fallito”.}
