{100}{}{Vedi un vecchio tizio dall'aspetto amichevole.}
{101}{}{E' Doc Jubilee.}
{102}{}{E' un vecchio con una candida barba e uno sguardo piuttosto assente.}
{103}{}{Sono Doc Jubilee. Cosa c'e' che non va, giovanotto?}
{104}{}{Cosa c'e' che non va, giovanotto?}
{105}{}{Me ferito.}
{106}{}{Ho bisogno di un dottore.}
{107}{}{Non potresti semplicemente prendere delle pillole o qualcosa del genere invece di disturbarmi per queste sciocchezze?}
{108}{}{Diavolo, sanguini appena!}
{109}{}{Non so. Non penso di poterla salvare. Forse dovremo amputare questa gamba.}
{110}{}{Stai scherzando.}
{111}{}{Ah-ah.}
{112}{}{Ecco a te, figliuolo.}
{113}{}{Ancora.}
{114}{}{Grazie, Doc. Forse potresti rispondere a qualche domanda.}
{115}{}{Arrivederci.}
{116}{}{Ti costera' 50$.}
{117}{}{Basta che mi curi.}
{118}{}{Me ne vado.}
{119}{}{Tu fare stare me meglio.}
{120}{}{Me va ora.}
{121}{}{No. Non scherzo mai. E' meglio amputare quella gamba prima che vada in gangrena.}
{122}{}{Puoi scordarti di amputarmi qualcosa, capito?}
{123}{}{Questo e' troppo, me ne vado.}
{124}{}{Beh, se poi ti va in gangrena, non venire a dare la colpa a me.}
{125}{}{Non gestisco un istituto di carita'. Dovrai darmi dei soldi prima che io faccia qualcosa.}
{126}{}{Allora, cosa posso fare per te?}
{127}{}{Spara.}
{128}{}{Vault 13?}
{129}{}{Sai dove potrei trovare il Vault 13?}
{130}{}{Ho sentito dire da qualcuno che il signor Westin non sta molto bene. E' vero? Non vorrei che gli capitasse qualcosa. Mi deve dei soldi.}
{131}{}{C'e' questo tizio, Saltbeef, che dice che gli hai rubato una mappa. Cos'e' 'sta storia?}
{132}{}{Sto cercando lavoro. Sai dove potrei trovarne uno?}
{133}{}{Doc, tu non sai nulla a proposito di un gruppo che combatte i malvagi schiavisti, vero?}
{134}{}{Beh, non dovresti preoccuparti, ragazzo. Se non stressa il suo fisico, probabilmente ci sotterrera' tutti. Naturalmente deve sottoporsi a visite periodiche e prendere sempre la sua medicina.}
{135}{}{Buono a sapersi. C'e' un'altra cosa che mi stavo chiedendo...}
{136}{}{Grazie, Doc.}
{137}{}{Quel vecchio ubriacone! L'unica cosa che gli abbia mai preso e' stato il mio dipinto di "Velvet Elvii" - l'ho preso come pagamento.}
{138}{}{Un Velvet Elvii? Posso vederlo?}
{139}{}{Non e' esattamente una mappa, eh? Beh, lascia che ti chieda qualcos'altro.}
{140}{}{Bene, adesso devo andare.}
{141}{}{Non ne sento parlare dal giorno in cui il vecchio Saltbeef e' stato portato qui. Colpo di sole. Bruciato dalle febbri per tre giorni, continuava a vaneggiare dicendo di aver trovato il Vault 13, il suo tesoro.}
{142}{}{Tesoro?}
{143}{}{E allora... dov'e'?}
{144}{}{Dove vault?}
{145}{}{Non saprei dirtelo. Saltbeef ha sempre detto di avere una mappa, ma nessuno l'ha mai vista.}
{146}{}{Saltbeef?}
{147}{}{Un'altra cosa...}
{148}{}{Beh, e' piu' di quanto non avessi prima.}
{149}{}{Il colpo grosso. Saltbeef e' un vecchio cercatore d'uranio - piu' precisamente, un ubriacone. Negli ultimi tempi vive nella proprieta' di Westin.}
{150}{}{Un'altra domanda...}
{151}{}{Grazie per la storia.}
{152}{}{Beh, speravo proprio di ricavarci dei soldi. Te lo lascero' per }
{153}{}{Magari piu' tardi. Un'altra domanda...}
{154}{}{Magari un'altra volta. Devo andare.}
{155}{}{Saltbeef e' un vecchio cercatore d'uranio. Negli ultimi tempi vive nella proprieta' di Westin.}
{156}{}{Un'altra domanda...}
{157}{}{Grazie per la storia.}
{158}{}{Faresti meglio ad andare a parlare con il Presidente Tandi. Ho sentito dire che sta cercando una persona speciale.}
{159}{}{Un'altra domanda...}
{160}{}{Grazie.}
{161}{}{Forse... Esiste un gruppo che ha come obiettivo la scomparsa della schiavitu' e - beh, di praticamente tutte le altre cattiverie. Puoi trovarli in quel grande negozio, che lavorano su qualche automobile.}
{162}{}{Un'altra domanda...}
{163}{}{Grazie.}
{164}{}{Ehi, giu' le mani da li', ragazzaccio!}
{165}{}{Fa' attenzione! Basta poco di quello per farti male.}
{166}{}{Mettilo a posto! Potresti farti male sul serio con quella roba.}
{167}{}{Quelle medicine sono per Mr. Westin, non per te. Mettile giu'.}
{168}{}{Sta' lontano da li'. Devo stare attento. Non vorrei che Mr. Westin assumesse la medicina sbagliata.}
{169}{}{Occhio! Ho appena preparato la medicina per Mr. Westin.}
{170}{}{Sono Doc Jubilee. Cosa c'e' che non va, signorina?}
{171}{}{Cosa c'e' che non va, signorina?}
{172}{}{Ecco a te, signorina.}
{173}{}{Beh, non dovresti preoccuparti, signorina. Se non stressa il suo fisico, probabilmente ci sotterrera' tutti. Naturalmente deve sottoporsi a visite periodiche e prendere sempre la sua medicina.}
{174}{}{Certo. Ecco i }
{175}{}{Grazie; ho cercato di farmi dare i soldi da Saltbeef, ma quel vagabondo non ne ha mai avuti.}
{176}{}{.}
