{100}{}{Vedi un uomo vestito con abiti da lavoro.}
{101}{}{It's brahmin buyer. He is expecting Hal's caravan.}
{102}{}{Puzza di brahmin.}
{113}{}{Che merda di lavoro abbiamo fatto! Temo che stavolta non ci saranno soldi per noi. Accontentati di aver salvato la pelle.}
{114}{}{Beh, i proprietari non sono troppo contenti - Questo e' un lavoro da soli 1000$. Che sfortuna.}
{115}{}{Beh, abbiamo avuto un po' di sfortuna ma ce l'abbiamo fatta. Eccoti i 2000$ pattuiti.}
{116}{}{Per tutti i vitelli da latte! Hai fatto davvero un ottimo lavoro! Eccoti i tuoi 2000$ e anche 1000$ di bonus. Redding fara' bene a stare in guardia, stanotte!}
{118}{}{Sei la peggior guardia che abbia mai visto in vita mia. Sparisci!}
{119}{}{Peccato che Hal non ce l'abbia fatta.}
{120}{}{Peccato per Hal...}
{121}{}{E' bello fare affari con te.}
{213}{}{Accidenti, Hal e' morto! E anche i brahmin! Temo che non ci siano soldi in questo viaggio per nessuno di noi. Sii felice di essere ancora vivo.}
{214}{}{Accidenti, Hal e' morto! E i mandriani non sono affatto contenti - e' solo un viaggio da 1000$. Che sfortuna.}
{215}{}{Accidenti, Hal e' morto! Almeno i brahmin stanno bene. Ecco i 2000$ pattuiti.}
{216}{}{Per tutti i vitelli da latte! Hai fatto davvero un ottimo lavoro! Eccoti i tuoi 2000$ e anche 1000$ di bonus.}
