{100}{}{Vedi una piastrella rialzata. Sembrerebbe fare parte di una trappola.}

# NPC name prepends this line
{101}{}{ vede una piastrella rialzata. Sembrerebbe fare parte di una trappola.}

{102}{}{Vedi una piastrella rialzata.}

# NPC name prepends this line
{103}{}{ vede una piastrella rialzata.}

{104}{}{Fai scattare la trappola ed eviti per un pelo il dardo fuoriuscito dal muro.}

# NPC name prepends this line
{105}{}{ fa scattare la trappola ed evita per un pelo il dardo fuoriuscito dal muro.}

{106}{}{Vedi una piastrella rialzata che sembrerebbe innocua.}