{100}{}{Vedi il Capo delle Assegnazioni Illecite, Chet.}
{101}{}{Vedi un uomo dall’aria losca che indossa una tuta del Vault 13.}
{102}{}{Vedi il Capo delle Assegnazioni Illecite, Chet.}
{103}{}{Vedi un uomo dall’aria losca che indossa una tuta del Vault 13.}
{104}{}{Ehi. Sono il Capo delle Assegnazioni Illecite… ma puoi chiamarmi Chet. Ti serve qualcosa?}
{105}{}{Ti serve altro?}
{106}{}{Imposta il flag di fine partita, Chet. Ho finito.}
{107}{}{Fammi Capitano della Guardia. Subito.}
{108}{}{Rendimi un vero cittadino, per favore.}
{109}{}{Fammi diventare un cittadino fasullo e dammi i documenti.}
{110}{}{Fammi diventare un cittadino espulso.}
{111}{}{Cambia la mia reputazione.}
{112}{}{(Non funziona) Mi serve un personaggio nel gruppo.}
{113}{}{No, niente.}
{114}{}{A cosa?}
{115}{}{Fammi diventare uno schiavista.}
{116}{}{Fammi diventare un assassino di bambini.}
{117}{}{Niente… abbassami il karma di 100.}
{118}{}{Non importa. Vorrei qualcos'altro...}
{119}{}{No, niente.}
{120}{}{Chi e'?}
{121}{}{Marcus.}
{122}{}{Lenny.}
{123}{}{Vic.}
{124}{}{Myron.}
{125}{}{Nessuno. Ho altre esigenze.}
{126}{}{Lasciamo perdere. Ci vediamo.}
