{100}{}{Vedi un uomo sporco ma dall'aspetto robusto.}
{101}{}{Vedi Connar.}
{102}{}{Ehi, tu! Che cosa stai facendo!}
{103}{}{Adesso sta' fermo dove sei, viaggiatore. Che cosa ci fai qui?}
{104}{}{Sto facendo fuori i mostri che ci sono qui.}
{105}{}{Perche', cosa ti interessa?} ###???Why, what's it to you
{106}{}{Perche' tu URLA!}
{107}{}{Scommetto che sono stati quei bastardi di Vault City a mandarti. Beh, farai meglio ad andartene e a lasciare ogni altra cosa in vita.}
{108}{}{Beh, e' un po' tardi per farlo.}
{109}{}{Perche'?}
{110}{}{Scusa, ho del lavoro da fare.}
{111}{}{Quelle creature sono l'unica cosa che impedisce a Vault City di farci diventare i loro cosiddetti servi.} ###???Those creatures are the only thing that are stopping Vault City from making us their so-called servants
{112}{}{Beh, loro mi pagano per sbarazzarmi dei mostri ed e' proprio quello che faro'.}
{113}{}{Questo non me l'avevano detto.}
{114}{}{Loro mi pagano perche' io mi sbarazzi dei mostri e ho completato il mio lavoro.}
{115}{}{Idiota! Perche' diavolo l'hai fatto?}
{116}{}{Mi servivano i soldi.}
{117}{}{Verrano a prenderci se lo fai, lo sai questo?}
{118}{}{Non e' un problema mio.}
{119}{}{Beh, spero che ti vadano di traverso. Presto, loro verranno a prenderci.}
{120}{}{Non sapevo che fosse questo il motivo per cui volevano che qualcuno lo facesse.}
{121}{}{Certo, beh, comunque non tratto con la spazzatura come te.}
{122}{}{Beh, noi non possiamo permettere che tu lo faccia.}
{123}{}{Bisogna fare quello che bisogna fare.}
{124}{}{E hai creduto a loro sulla parola? Hai un sacco di cose da imparare dal mondo, amico.}
{125}{}{C'e' niente che possa fare per aiutarvi?}
{126}{}{I tipi di Vault City non sono certo i piu' coraggiosi del mondo. Basta un po' di casino e scappano come conigli. Se avessimo un po' di armi, credo che potremmo tenerli a distanza.}
{127}{}{Che tipo di armi?}
{128}{}{Beh, sono piuttosto bravo con i fucili a pompa, e abbiamo un paio di uomini qui che possono maneggiare un fucile. Credo che tre di questi dovrebbero andar bene.}
{129}{}{Vedro' di fare il possibile.}
{130}{}{Non sei il benvenuto qui. Vattene.}
{131}{}{Ho cambiato idea. Cosa posso fare per aiutarvi?}
{132}{}{Certo... beh, voi non rimarrete qui a lungo, comunque.}
{133}{}{Come se me ne fregasse qualcosa.}
{134}{}{Sei tornato! Hai portato le armi per noi?}
{135}{}{Che cos'e' che vi serviva?}
{136}{}{Si', eccole qua.}
{137}{}{Abbiamo bisogno di tre fucili e di un fucile a pompa. Prima ce li riesci a portare e meglio e'.}
{138}{}{Okay.}
{139}{}{Con questi, saremo in grado, nei prossimi mesi, di ricavare qualcosa da questo posto. Se dovessi avere bisogno di un posto dove riposare, sarai sempre il benvenuto qui.}
{140}{}{Non c'e' di che.}
{141}{}{Bentornato. Le cose vanno per il meglio. Stiamo lavorando per espandere il villaggio.}
{142}{}{Ehila'! Le cose vanno bene, come vedi. Da' un'occhiata in giro, se ne hai il tempo.}
{143}{}{Stiamo continuando a costruire. Speriamo di espandere nuovamente le mura entro la fine del prossimo mese.}
{144}{}{Salve! Il villaggio ha continuato ad espandersi come speravamo. Tu sei il benvenuto, come sempre.}
{145}{}{Non abbiamo piu' niente da temere da Vault City e saremo in grado di vivere in questo luogo pacificamente. Grazie ancora, viaggiatore.}
{146}{}{Cerca solo di non uccidere niente qui intorno, sempliciotto.}