{100}{}{Vedi un'abitante del villaggio.}
{101}{}{Vedi un'abitante del villaggio.}
{102}{}{Salve.}
{103}{}{Buona giornata.}
{104}{}{Welcome to our village.}
{105}{}{I mostri ci proteggono.}
{106}{}{Vattene.}
{107}{}{Quelle armi ci serviranno presto.}
{108}{}{Salve.}
{109}{}{Ora vattene!}
{110}{}{Torna da dove sei venuto!}
{111}{}{Vattene immediatamente da qui!}
{112}{}{Adesso siamo salvi.}
{113}{}{Grazie.}
{114}{}{Che tu sia benedetto, viaggiatore.}
