{100}{}{Vedi un uomo basso e gioviale.}
{101}{}{Vedi Happy Harry, il proprietario del negozio.}
{102}{}{Beh, salve... cosa posso fare per te?}
{103}{}{Vorrei barattare delle cose. Posso vedere cos'hai?}
{104}{}{E' ancora in vendita quell'aratro la' fuori?}
{105}{}{Me compra}
{106}{}{Per oggi niente, grazie.}
{107}{}{Spiacente. Non posso aiutarti, vicino.}
{108}{}{Beh, si'. Te lo posso vendere per... diciamo... ottocento.}
{109}{}{Te ne daro' seicento.}
{110}{}{D'accordo. Lo prendo.}
{111}{}{Eh, ottocento? Tornero'... con i soldi.}
{112}{}{Scordatelo. Gli Smith possono anche morire di fame.}
{113}{}{E' tuo. [incassa il denaro.] Lo prendi subito, o desideri che venga recapitato da qualche parte?}
{114}{}{Consegnalo agli Smith.}
{115}{}{Spiacente, amico. Ti costera' ottocento monete.}
{119}{}{Hai bisogno dei soldi per pagarmi, amico.}
{120}{}{Tornero' con i soldi.}
{121}{}{Nessun problema. Lo faro' consegnare immediatamente.}
{122}{}{Credevi di poterti servire da solo, eh? Dannato ladro... Guardie! Guardie!}
