{100}{}{Vedi un uomo anziano con profonde rughe sul volto.}
{101}{}{Vedi John MacRae.}
{102}{}{Ehi, non ti ho mai visto da queste parti. Io sono MacRae — gestisco questo posto.
Che posso fare per te?}
{103}{}{Sto cercando il Vault.}
{104}{}{Hai voglia di lasciare questo posto?}
{105}{}{Che cosa avete qui?}
{106}{}{Succede qualcosa da queste parti?}
{107}{}{Ug Nog}
{108}{}{Per oggi niente, grazie.}
{109}{}{Vault? L'unico Vault che conosco e' quello all'interno della citta'. Un grosso, fottutissimo buco... Non puoi mancarlo, credimi.}
{110}{}{Cos'avete da bere, qui?}
{111}{}{Succede qualcosa da queste parti?}
{112}{}{Grazie per le indicazioni. addio.}
{113}{}{La solita roba. Birra a 20 dollari, uno shot di whiskey a 30. Niente di speciale.
Vuoi qualcosa?}
{114}{}{Sai qualcosa sul Vault?}
{115}{}{Prendero' una birra.}
{116}{}{Prendero' il whiskey.}
{117}{}{Cosa succede da queste parti?}
{118}{}{Niente per oggi, grazie. Arrivederci.}
{119}{}{Qui intorno? Sempre la solita storia. La maggior parte del tempo mi annoia da morire.
Perche’, stai cercando qualcosa?}
{120}{}{Cos'avete da bere, qui?}
{121}{}{Sai qualcosa sul Vault?}
{122}{}{Non può essere così terribile.}
{123}{}{Nulla. Arrivederci.}
{124}{}{Hai sbattuto la testa un po' troppo spesso, eh? Scusa, ma non parlo con gli imbecilli.}
{125}{}{Tieni. Bevi. È praticamente l’unico divertimento che vedrai in questo posto di rigidi.}
{126}{}{Non può essere così terribile.}
{127}{}{Grazie per il drink. Direi che me ne vado.}
{128}{}{Ascolta. Ti ho chiesto se volevi da bere e poi ti ho detto quanto costava. La maggior parte della gente capisce come funziona. Se non hai i soldi, non avresti dovuto chiedere.}
{129}{}{Scusa. Pensavo di avere i soldi. Non poter vedere i tuoi soldi nella schermata di dialogo crea qualche problema, sai?}
{130}{}{Vabbe', come vuoi. Io me ne vado.}
{131}{}{È peggio. I Cittadini non bevono molto, quindi resto qui a servire da bere ai mercanti. Il prossimo tirchio che prova a contrattare per un drink si ritroverà il mio stivale nel culo.}
{132}{}{Sembri piuttosto stufo di questo posto.}
{133}{}{Sorry to hear that. What do you know about the Vault?}
{134}{}{We all make mistakes... some more than others. So what do you want?}
{135}{}{Cosa succede da queste parti?}
{136}{}{Niente per oggi, grazie. Arrivederci.}
{137}{}{Yeah, wish I could get the hell outta here.}
{138}{}{Perche' non te vai?}
{139}{}{Go into the wastes by myself? I'm bored, but I'm not stupid.}
{140}{}{Io sto per andarmene da qui. Perche' non vieni con me?}
{141}{}{Beh, buona fortuna.}
{142}{}{Nah... mi pare che tu abbia gia' una discreta folla al tuo seguito.}
{143}{}{D'accordo. Beh, buona fortuna.}
{144}{}{You know, that doesn't sound like a half bad idea. Count me in.}
{145}{}{Yeah, what?}
{146}{}{Voglio che tu ti tolga di mezzo.}
{147}{}{Come stai?}
{148}{}{Curati.}
{149}{}{Voglio che tu stia qua finche' non ritorno.}
{150}{}{You! Ooyag!}
{151}{}{E' tutto, per ora.}
{152}{}{OK, everything's stitched up. Let's get going.}
{153}{}{OK, pretty much everything is patched up.}
{154}{}{Sono quasi a posto, ma mi farebbe comodo un altro paio di stim.}
{155}{}{I used what I could, but I'm still pretty messed up. Got any stims on you?}
{156}{}{Use First Aid on yourself.}
{157}{}{Lasciamo stare.}
{158}{}{OK.}
{159}{}{OK, I'll wait here.}
{160}{}{Lasciamo stare.}
{161}{}{OK.}
{162}{}{Let's get going.}
{163}{}{OK.}
{164}{}{Look, you have enough people following your coat tails now.}
{165}{}{Yeah, you go with that.}
{166}{}{Credo che non prendero' nulla, grazie.}
{167}{}{I think I'm just going to hang around here a little longer.}
