{100}{}{Vedi un vecchio con un barlume di follia negli occhi.}
{101}{}{Vedi il Vecchio Joe, l'"idiot savant" locale.}
{102}{}{Ciao. E' da un po' che non ci si vede.}
{103}{}{Ti conosco?}
{104}{}{Ah, si'. E' da un po'. Che cosa hai fatto in questo periodo?}
{105}{}{Beh, e' passato un po' di tempo. Cos'hai fatto in questo periodo?}
{106}{}{Un po' questo e un po' quello. Come fai a conoscermi?}
{107}{}{Senti, vecchio, non so chi diavolo tu sia.}
{108}{}{Eh, si'. Beh, ho girato un po'; alla fine sono finito qui, in questo posto dimenticato da dio. Non e' come i bei vecchi tempi. Nossignore.}
{109}{}{Certo, i bei vecchi tempi. Ricordi quella volta che noi...}
{110}{}{Ultimamente non e' piu' lo stesso, questo e' sicuro. Ora... cos'abbiamo fatto insieme?}
{111}{}{Non ti ricordi di me, eh? Infatti mi sembri un po' troppo giovane.}
{112}{}{Cosa stai cercando di dirmi?}
{113}{}{Hai un'aria cosi' familiare, pero'... Ah, devono essere i miei vecchi occhi. Beh, buona giornata a te.}
{114}{}{Uh, certo... addio.}
{115}{}{Gia'... abbiamo proprio fatto vedere l'inferno al Master, vero? E' andato tutto a puttane dopo che te ne sei andato. Sono stato costretto a spostarmi di continuo e a cambiar nome. Dov'eri finito?}
{116}{}{Ho vissuto in un piccolo villaggio.}
{117}{}{Beh, farai meglio a stare attento da queste parti. Le cose non sono cosi' chiare come una volta. Farai meglio a guardarti le spalle.}
{118}{}{Okay, grazie.}
{119}{}{Ho cercato il tuo Vault per un po', ma non l'ho mai trovato. Allora, hai qualche bella storia da raccontare al tuo vecchio amico Ian?}
{120}{}{Ian?}
{121}{}{Certo, Ian. Non ti ricordi di me? Sono passati un sacco di anni. Pensavo che non avresti mai dimenticato il tuo migliore amico. Beh... a parte quella faccenda degli spari alla schiena. Scusami ancora per quello.}
{122}{}{Mi dispiace, ma forse mi hai scambiato l'Abitante del Vault. Il mio villaggio e' stato fondato da una persona che proveniva dal Vault.}
{123}{}{Beh, questo spiega un po' le cose. Beh, mi fa piacere sentire che il mio amico ha fatto qualcosa di buono. Beh, il vecchio Ian ha un consiglio per te. Sta' attento. Questo posto non e' cosi' candido come sembra.} ###???to hear my friend did well
{124}{}{Cosa succede?}
{125}{}{Beh, i Cittadini di Vault City tengono molto alla loro stirpe e non considerano molto le persone come me e te. Prendi questa. Ti proteggera' se le cose dovessero complicarsi un po'. Probabilmente non dovresti farti vedere a parlare con un vecchio pazzo. Farai meglio ad andartene.}
{126}{}{Grazie per il tuo aiuto.}
{127}{}{Lascia riposare questo povero vecchio.}
{128}{}{Cosi' familiare...}
{129}{}{Adesso lasciami solo.}
{130}{}{Faresti meglio ad andare.}
{131}{}{Si insospettiranno se ci vedono parlare ancora.}
{132}{}{Su, vai. Fa' in modo che il mio vecchio amico sia fiero di te.} ###???get
