{100}{}{Vedi il Cittadino Sergente Stark.}
{101}{}{Vedi un enorme uomo di colore con un'armatura pesante addosso. Ti sta guardando attentamente.}
{102}{}{Vedi il Cittadino Sergente Stark.}
{103}{}{Vedi un enorme uomo di colore con un'armatura pesante addosso. Ti sta guardando attentamente.}
{104}{}{Hai fatto un buon lavoro, giu' a sud. I fuochi d'artificio si son visti persino qui.}
{105}{}{Buongiorno... signore.}
{106}{}{Vault City prevale... signore.}
{107}{}{Buongiorno, Cittadino.}
{108}{}{Vault City prevale, Cittadino.}
{109}{}{Ti faro' desiderare d'esser rimasto fuori dalla citta'... Guardie!}
{110}{}{Un mutante! Guardie!}
{111}{}{Un ghoul! Guardie!}
{112}{}{Devo redigere queste liste di munizioni...}
{113}{}{Domani devo controllare gli armadietti delle armi, giu' nel Vault...}
{114}{}{Forse passare qualche giorno in cella ti insegnera' a comportarti bene. }
{115}{}{E RIMARRAI in quella cella finche' il Primo Cittadino non ti avra' perdonato. }
{116}{}{Sono spiacente, Cittadino, ma a nessuno e' permesso entrare nel Centro Correttivo dopo il tramonto. Ritorni domattina.}
{117}{}{E' cominciato il coprifuoco. Che cosa ci fai ancora in citta'?}
{118}{}{Yah!}
{119}{}{Uh, dal momento che sono un Cittadino, ho il permesso di rimanere in citta' dopo il tramonto.}
{120}{}{Avevo degli affari da concludere prima di andarmene.}
{121}{}{Me ne stavo andando proprio adesso.}
{122}{}{Ah, davvero? Beh, io conosco TUTTI i Cittadini di Vault City, e non ti riconosco. Dove sono i tuoi documenti?}
{123}{}{Li vuoi? Vieni a prenderli.}
{124}{}{Non li ho con me.}
{125}{}{Eccoli qua.}
{126}{}{E allora smettila di farmi perdere tempo, "Cittadino". Forza, andiamo.}
{127}{}{Per oggi i tuoi affari qui sono terminati. Forza, andiamo.}
{128}{}{Io non vado da nessuna parte. Se provi a portarmi fuori con la forza, te ne pentirai.}
{129}{}{D'accordo, vado.}
{130}{}{Capitano... Posso aiutarla... signore?}
{131}{}{Posso aiutarla, Cittadino?}
{132}{}{Che cosa vuoi?}
{133}{}{Yah!}
{134}{}{-Allontanati-}
{135}{}{Chi sei?}
{136}{}{Nulla, scusa se ti ho disturbato.}
{137}{}{Vieni con me, ragazzo. ADESSO.}
{138}{}{Vieni con me, ragazza. ADESSO.}
{139}{}{Me andare? Me andare!}
{140}{}{ME NO VA. ADESSO.}
{141}{}{Ti pentirai di questa risposta.}
{142}{}{ME NO VA ALLA POSTA!}
{143}{}{Sergente Stark... signore. Le serve qualcosa?}
{144}{}{Io sono il Cittadino SERGENTE Stark, Cittadino. Posso aiutarla in qualche modo?}
{145}{}{Io sono il Cittadino SERGENTE Stark, Esterno. Che cosa vuoi?}
{146}{}{Di cosa si occupa?}
{147}{}{Potrebbe dirmi dove si trova il Vault?}
{148}{}{Nulla, scusi se l'ho disturbata.}
{149}{}{Faccio il SUO STESSO lavoro, signore.}
{150}{}{Sono il responsabile del Centro Correttivo. Ed eseguo i suoi ordini, signore.}
{151}{}{Sono il responsabile del Centro Correttivo. Tengo in riga gli Esterni. Mi assicuro che i Servi si comportino bene. Pianifico i pattugliamenti. Cerco di proteggere la citta' dai predoni.}
{152}{}{Ha qualche problema, Sergente?}
{153}{}{E' lei che ha fatto irruzione nel bar di Cassidy?}
{154}{}{Conosce per caso un servo di nome Joshua?}
{155}{}{Pattugliamenti?}
{156}{}{Predoni?}
{157}{}{A proposito di quei predoni...}
{158}{}{Posso farle qualche domanda?}
{159}{}{Grazie. Arrivederci.}
{160}{}{Vorrei il permesso di parlare liberamente, signore.}
{161}{}{Concesso.}
{162}{}{No. Prima vorrei essere io a farle delle domande.}
{163}{}{Non oggi, Sergente.}
{164}{}{Lei non MERITA di ricoprire questo incarico. Io sono nato e vissuto a Vault City. Gli uomini e le donne sotto il MIO comando si fidano di me e rispettano me, non lei... signore.}
{165}{}{E' per questo che ho bisogno di lei, Sergente. Non ci sono dubbi che lei sia un elemento valido e che lei conosca Vault City meglio di quanto la conosca io. Ciononostante, io ho raggiunto dei RISULTATI dove lei ha FALLITO. Non se lo dimentichi mai.}
{166}{}{Ne prendo nota, Sergente. Adesso vorrei farle qualche domanda.}
{167}{}{Ne prendo nota, Sergente. Le consiglio di placare i bollenti spiriti e di continuare a svolgere il suo lavoro. Buona giornata.}
{168}{}{E' stato molto chiaro, signore.}
{169}{}{Adesso sono io che vorrei farle qualche domanda.}
{170}{}{Allora torni a fare quello che stava facendo, Sergente.}
{171}{}{Signorsi'. Ho guidato personalmente un'irruzione autorizzata nella proprieta' del sig. Cassidy.}
{172}{}{Forse il tuo amico Cassidy non ti ha detto che nel suo locale erano presenti sostanze illegali e che la sua licenza per la vendita di alcolici era scaduta. Ti sei dimenticato di dire queste cose al tuo amico, eh, Cassidy?}
{173}{}{Cassidy dice che lui era a posto con i pagamenti, ma che voi avete fatto irruzione ugualmente.}
{174}{}{Come non detto. Avrei delle altre domande...}
{175}{}{Come non detto, allora. Arrivederci.}
{176}{}{No, signore. Il sig. Cassidy non aveva pagato la licenza per la vendita di alcolici valevole per quel mese, eppure continuava a venderli nel suo locale. La lista dei suoi pagamenti e' riportata nel computer.}
{177}{}{Cassidy e' stato trovato colpevole di possesso di alcolici senza licenza. Se non gli sta bene, puo' andarsene da Vault City. Semplice.}
{178}{}{Le credo, Sergente. Ben fatto. Adesso mi ascolti: voglio che lei ritiri le accuse contro il sig. Cassidy, ripulisca la sua fedina penale e che gli dia un risarcimento per i danni causati dalla sua squadra al suo locale.}
{179}{}{Sai, credo che molto presto il mio pugno e la tua faccia avranno una bella discussione.}
{180}{}{Come non detto. Avrei delle altre domande...}
{181}{}{Come non detto, allora. Arrivederci.}
{182}{}{Grazie per avermi aiutato, amico. Stark e' davvero un testardo figlio di puttana.}
{183}{}{Provaci. Non vedo l'ora di dare una bella lezione a due sacchi di spazzatura come te e Cassidy.}
{184}{}{Perfetto. Io non vedo l'ora di spaccarti il muso.}
{185}{}{Come non detto. Avrei delle altre domande...}
{186}{}{Come non detto, allora. Arrivederci.}
{187}{}{Si'... SIGNORE.}
{188}{}{SUBITO, Sergente.}
{189}{}{Forza, Sergente. Chop-chop.}
{190}{}{Ecco a lei, SIGNORE.}
{191}{}{Adesso vorrei farle qualche domanda, Sergente.}
{192}{}{Molto bene, Sergente. Continui cosi'.}
{193}{}{Certo, si tratta di quell'Esterno ubriaco che ha colpito una delle mie guardie durante l'irruzione allo Spittoon. Adesso si trova al Centro di Collocamento Servi dove lo stanno... educando. E' in fondo a questa strada.}
{194}{}{Avrei un'altra domanda...}
{195}{}{Hmmm. Ci vado subito.}
{196}{}{Il Vault si trova proprio qua fuori... signore.}
{197}{}{Il Vault si trova proprio qua fuori. Basta che dica alle guardie che lei e' un Cittadino, e loro la lasceranno passare.}
{198}{}{Il Vault si trova proprio qua fuori. Solo ai Cittadini e' permesso l'ingresso, percio' non voglio nemmeno vederti a discutere con le guardie.}
{199}{}{Posso chiederle qualcos'altro?}
{200}{}{Ma io sono un Cittadino.}
{201}{}{Come si diventa Cittadini?}
{202}{}{Grazie. Arrivederci.}
{203}{}{Ah, davvero? Io non ti riconosco... e si' che conosco TUTTI i Cittadini di Vault City.}
{204}{}{Ecco i miei documenti. Credo scoprira' che e' tutto in regola.}
{205}{}{Uh, come non detto. Avrei delle altre domande...}
{206}{}{Sara' meglio che vada.}
{207}{}{Bene, bene... che mi venga un colpo se questi non sono i documenti che sono stati rubati il mese scorso. Sembra proprio che io abbia finalmente trovato il colpevole. Vieni con me, Esterno.}
{208}{}{Toccami e te ne pentirai.}
{209}{}{Mi muovo, mi muovo. Smettila di spingere.}
{210}{}{Io sono NATO Cittadino. Sei interessato a diventare un Cittadino? Allora parla con un membro del Consiglio.}
{211}{}{Posso chiederle qualcos'altro?}
{212}{}{Lo faro', grazie. Arrivederci.}
{213}{}{Si', cosa vuoi dirmi?}
{214}{}{Ho trovato la loro base.}
{215}{}{Li ho eliminati.}
{216}{}{Ha qualche idea di dove si possa trovare il luogo dal quale sferrano i loro attacchi?}
{217}{}{Come non detto. Avrei delle altre domande...}
{218}{}{Lasciamo perdere. Magari possiamo parlarne un'altra volta.}
{219}{}{Davvero? Dove si trova?}
{220}{}{Si', me l'hai gia' detto. Dovresti parlare con il Primo Cittadino, se non l'hai gia' fatto.}
{221}{}{Giu' a sud, in un dedalo di caverne nelle montagne. Ecco, lasci che glielo indichi...}
{222}{}{Avrei delle domande da farle.}
{223}{}{D'accordo. Andro' a riferirglielo.}
{224}{}{Li hai eliminati?}
{225}{}{Si', me l'hai gia' detto. Dovresti parlare con il Primo Cittadino, se non l'hai gia' fatto.}
{226}{}{Certo, Vault City non deve piu' preoccuparsi di loro.}
{227}{}{Avrei delle domande da farle.}
{228}{}{D'accordo. Andro' a riferirglielo.}
{229}{}{Avverti subito il Primo Cittadino. Sono certo che vorra' esserne informata al piu' presto.}
{230}{}{Prima vorrei farle qualche domanda.}
{231}{}{D'accordo. Vado subito da lei.}
{232}{}{Esatto, predoni. I loro attacchi sono stati piuttosto pesanti, ultimamente. (Aggrotta le sopracciglia) Perche' vuoi che ti parli di loro?}
{233}{}{Vorrei provare a scoprire dove si trova la loro base, e magari mettere fine ai loro attacchi, se posso.}
{234}{}{Pura curiosita'.}
{235}{}{Come non detto. Avrei delle domande...}
{236}{}{Lasciamo perdere. Magari possiamo parlarne un'altra volta.}
{237}{}{Sei una specie di buon Samaritano, o cosa? Non la bevo.}
{238}{}{Non sono un Samaritano. In realta' sono nativo di Arroyo - un villaggio che si trova a ovest di qui.}
{239}{}{Mi piacerebbe aiutare, se possibile.}
{240}{}{Ascolti, conosco abbastanza il mondo per sapere che aiutare le persone presto o tardi si rivelera' essere d'aiuto anche per me.} ###???I've seen enough of the world to know that helping out people seems to come back and help me in the end
{241}{}{Come non detto. Avrei delle altre domande...}
{242}{}{Lasciamo perdere. Magari possiamo parlarne un'altra volta.}
{243}{}{Sei venuto qua per fare lo spiritoso, o cosa? E' cosi'?}
{244}{}{Oh, davvero? Beh, affrontare questa banda di predoni potrebbe rivelarsi un'impresa piu' grande di quanto immagini.}
{245}{}{No, ma se avete bisogno di aiuto, sarei felice di aiutarvi.}
{246}{}{Vorrei comunque provare ad aiutarvi.}
{247}{}{Come non detto, allora. Avrei delle altre domande...}
{248}{}{Lasciamo perdere. Magari possiamo parlarne un'altra volta.}
{249}{}{Hmmm. Beh, al punto in cui siamo non saro' certo io a dire di no ad un'offerta di aiuto. Se riesci a trovare la loro base, o, ancora meglio, se riesci a farli fuori, corri ad avvertire il Primo Cittadino.}
{250}{}{Veramente, io ho gia' trovato la loro base.}
{251}{}{Veramente, io li ho gia' fatti tutti fuori.}
{252}{}{Ha qualche idea di dove possa trovarsi la loro base?}
{253}{}{D'accordo. Avrei delle altre domande...}
{254}{}{Lo faro'.}
{255}{}{Curiosita', eh? Anch'io sono molto curioso. Ora, che cosa sai *tu* a proposito dei predoni?}
{256}{}{Vorrei provare a scoprire dove si trova la loro base, e magari mettere fine ai loro attacchi, se posso.}
{257}{}{Io non so nulla. E' per questo che chiedo a lei.}
{258}{}{Come non detto. Avrei delle altre domande...}
{259}{}{Lasciamo perdere. Magari possiamo parlarne un'altra volta.}
{260}{}{Non sai nulla? Magari potrei tenerti qui nel Centro Correttivo fino a quando non ti sarai RICORDATO qualcosa.}
{261}{}{Vorrei provare a scoprire dove si trova la loro base, e magari mettere fine ai loro attacchi, se posso.}
{262}{}{Mi ha beccato. E' chiaro che sono in combutta con i predoni. Mi arresti.}
{263}{}{Ascolti, adesso io me ne vado. Se prova a fermarmi, ci saranno guai.}
{264}{}{Sei gia' nei guai. Vuoi forse peggiorare le cose?}
{265}{}{No, vorrei provare a scoprire dove si trova la loro base, e magari mettere fine ai loro attacchi, se posso.}
{266}{}{Mi ha beccato. E' chiaro che sono in combutta con i predoni. Mi arresti.}
{267}{}{Io me ne vado. Vuoi fermarmi? Accomodati pure.}
{268}{}{Benissimo, allora...}
{269}{}{Whoa! Whoa! Io non --}
{270}{}{Fatti sotto, morto ambulante.}
{271}{}{Non credo che dovremmo lasciar cadere l'argomento cosi' facilmente. Ora... che cosa sai a proposito dei predoni?}
{272}{}{Vorrei provare a scoprire dove si trova la loro base, e magari mettere fine ai loro attacchi, se posso.}
{273}{}{Pura curiosita'.}
{274}{}{Ascolti, adesso io me ne vado. Se prova a fermarmi, ci saranno guai.}
{275}{}{Non saprei. Quei predoni sono piuttosto strani. SE si tratta davvero di predoni.}
{276}{}{Che cosa intende dire?}
{277}{}{Avrei delle altre domande...}
{278}{}{Devo andare.}
{279}{}{Hanno armi molto potenti. E costose. Sono pratici di tattiche militari. Avanzano in formazione. Non incrociano mai le loro linee di fuoco. E si fermano sempre poco prima di fare breccia nelle nostre difese.}
{280}{}{Uh... si fermano poco prima di fare breccia nelle difese?}
{281}{}{Avrei delle altre domande...}
{282}{}{Devo andare.}
{283}{}{Li ho visti con i miei occhi. Durante l'ultimo attacco erano riusciti a mettere fuori uso una torretta laser sul perimetro occidentale. Era un'ottima occasione per penetrare in citta'. A quel punto ho visto uno dei loro "capitani" ORDINARE loro di ritirarsi. Tutto cio' non ha senso.}
{284}{}{Ha idea da dove provengano?}
{285}{}{Hmmm. Avrei delle altre domande...}
{286}{}{Interessante. Devo andare.}
{287}{}{No. E questa e' la parte piu' frustrante. Continuano a ritirarsi verso sud. Non posso permettermi di inviare uomini ad esplorare la zona. Credo che i predoni abbiano una guida autoctona che li conduce attraverso i canyon meridionali.}
{288}{}{Come mai a sud?}
{289}{}{Hmmm. Avrei delle altre domande...}
{290}{}{Interessante. Devo andare.}
{291}{}{Ci sono un sacco di posti dove nascondersi se non si sa dove cercare. Quel posto e' un dedalo di caverne.}
{292}{}{Probabilmente io saprei trovarli.}
{293}{}{Avrei delle altre domande...}
{294}{}{Hmmm. Me ne ricordero'. Arrivederci.}
{295}{}{Accomodati pure. In credo che l'unico modo per trovarli sia sperare che ci diano una mappa.}
{296}{}{Avrei delle altre domande...}
{297}{}{Se l'unica soluzione e' questa... grazie dell'informazione.}
{298}{}{Certo, abbiamo un piccolo gruppo di pattuglie. Abbiamo gia' pochi uomini per proteggere Vault City, figurarsi se posso mandare delle guardie ad effettuare le perlustrazioni necessarie.}
{299}{}{Lustra-che?}
{300}{}{Io viaggio molto. Posso aiutare in qualche modo?}
{301}{}{Mi dispiace. Avrei delle altre domande...}
{302}{}{Come non detto, allora. Arrivederci.}
{303}{}{Esplorazioni.}
{304}{}{Che cosa vuoi dire?}
{305}{}{Potrei fare un po' di esplorazioni per conto vostro, se siete a corto di uomini.}
{306}{}{Lasciamo perdere. Avrei delle altre domande...}
{307}{}{Come non detto, allora. Arrivederci.}
{308}{}{No, ti servirebbe un Pip Boy per fare bene questo lavoro, e non posso dartene uno, al momento.}
{309}{}{Sono gia' in possesso di un Pip Boy. E' vecchio... e scassato... e mancano un sacco di cavi e di pulsanti... ma funziona.}
{310}{}{Bene, d'accordo. Avrei delle altre domande...}
{311}{}{Come non detto, allora. Arrivederci.}
{312}{}{Davvero? Ha in memoria la mappa della California settentrionale?}
{313}{}{Si'. Beh, almeno a giudicare da quanto riesco a vedere attraverso tutta questa dannata "fog of war".}
{314}{}{Allora ho un lavoro per te. Mi serve che qualcuno esplori i terreni intorno a Gecko... l'insediamento ghoul a nordest. Tocca gli otto settori che circondano la citta', e poi torna qui per il rapporto.}
{315}{}{Perche'?}
{316}{}{Nessun problema. Ho gia' esplorato quella zona.}
{317}{}{D'accordo. Tornero' quando avro' esplorato la zona.}
{318}{}{Ripensandoci: non contate su di me. Addio.}
{319}{}{Se i ghoul continuano ad avvelenare le falde acquifere, potremmo essere costretti ad intraprendere un'azione militare contro di loro. }
{320}{}{Voglio vedere quali danni ha causato l'esplosione della centrale in quella zona. }
{321}{}{Potremmo essere costretti ad intraprendere un'azione militare contro di loro, in futuro... soprattutto nel caso in cui ricominciassero ad avvelenare le falde acquifere. }
{322}{}{Ora: lo vuoi il lavoro o no?}
{323}{}{Si'. Pero' io ho gia' esplorato la zona.}
{324}{}{Accetto. Faro' rapporto non appena avro' portato a termine la missione.}
{325}{}{Accetto. Prima avrei delle domande da farle, pero'...}
{326}{}{No grazie. Magari un'altra volta.}
{327}{}{Davvero? Eh. Beh... d'accordo allora.}
{328}{}{Ben fatto. Scarica le informazioni da te raccolte nel mio Pip Boy e io le inseriro' nei computer delle pattuglie.}
{329}{}{D'accordo...}
{330}{}{Queste informazioni sembrano buone. Ben fatto. Ecco la tua ricompensa... trecento dollari.}
{331}{}{D'accordo, allora... avete dell'altro da farmi fare?}
{332}{}{Ottimo. Avrei delle altre domande...}
{333}{}{Grazie. E' un piacere fare affari con voi.}
{334}{}{Veramente si'... Mi serve che qualcuno vada fino a NCR. Da alcuni rapporti recenti pare che la Repubblica stia potenziando il suo esercito. Che questo sia vero o no, mi serve che qualcuno tracci un percorso fino a NCR e che torni a fare rapporto.}
{335}{}{Nessun problema. L'ho gia' fatto.}
{336}{}{Basta arrivare a NCR e poi tornare indietro?}
{337}{}{Lasciamo perdere. Avrei delle altre domande...}
{338}{}{No grazie. Addio.}
{339}{}{Questo e' tutto quello che chiedo. Mi interessa soprattutto il percorso, piu' che la Repubblica in se', ma comunque e' necessario che tu entri in citta', una volta giuntovi.}
{340}{}{Nessun problema. L'ho gia' fatto.}
{341}{}{Accetto. Faro' rapporto non appena avro' portato a termine la missione.}
{342}{}{Accetto. Prima di andare, avrei delle domande da farle...}
{343}{}{No grazie. Avrei delle altre domande, pero'...}
{344}{}{Non credo di volere questo lavoro. Magari un'altra volta.}
{345}{}{Davvero? Eh.}
{346}{}{D'accordo, allora. Scarica le informazioni da te raccolte nel mio Pip Boy e io le inseriro' nei computer delle pattuglie.}
{347}{}{D'accordo.}
{348}{}{Queste informazioni sembrano buone. Ben fatto. Ecco la ricompensa per il lavoro svolto: cinquecento dollari... in piu', forse questo ti tornera' utile.}
{349}{}{Cos'e'?}
{350}{}{E' un sensore di movimento Vault-Tec. Volevamo ricavarne pezzi di ricambio, dal momento che e' troppo vecchio per i nostri Pip Boy, ma sembra essere compatibile con il tuo modello.}
{351}{}{Come funziona?}
{352}{}{Basta tenerlo in mano e, quando usato, identifichera' i bersagli ostili nelle immediate vicinanze. Oppure puoi accedere normalmente alla funzione Automappa del Pip Boy, e premere il pulsante "scanner" e i bersagli ostili si illumineranno come un'insegna al neon.}
{353}{}{Grazie, potrebbe tornarmi utile. Senta, posso farle qualche altra domanda?}
{354}{}{Grazie mille. Vado subito a provarlo.}
{355}{}{Salve... Capitano. Desidera qualcosa?}
{356}{}{Benritrovato, Cittadino. Posso aiutarla?}
{357}{}{Sei tornato? Ti sei perso, o vuoi qualcosa?}
{358}{}{Ad esempio... signore?}
{359}{}{Si', Cittadino. Che cosa desidera sapere?}
{360}{}{Ovvero?}
{361}{}{Hep-Hep Schlep-Bep}
{362}{}{-Allontanati-}
{363}{}{Ha qualche problema, per caso, Sergente?}
{364}{}{E' lei che ha fatto irruzione nel bar di Cassidy?}
{365}{}{Conosce per caso un servo di nome Joshua?}
{366}{}{Di cosa si occupa?}
{367}{}{Puo' dirmi dove si trova il Vault?}
{368}{}{Ho esplorato l'area di Gecko per lei.}
{369}{}{Ha altri compiti d'esplorazione da darmi?}
{370}{}{Ho tracciato un percorso fino a NCR per lei.}
{371}{}{A proposito di quei Predoni...}
{372}{}{Come non detto. Arrivederci.}
{373}{}{Buona giornata... signora.}
{374}{}{Vault City prevale... signora.}
{375}{}{Capitano... Posso aiutarla... signora?}
{376}{}{Sergente Stark... signora. Le serve qualcosa?}
{377}{}{Faccio il SUO STESSO lavoro, signora.}
{378}{}{Sono il responsabile del Centro Correttivo. Ed eseguo i suoi ordini, signora.}
{379}{}{Vorrei il permesso di parlare liberamente, signora.}
{380}{}{Lei non MERITA di ricoprire questo incarico. Io sono nato e vissuto a Vault City. Gli uomini e le donne sotto il MIO comando si fidano di me e rispettano me, non lei... signora.}
{381}{}{E' stata molto chiara, signora.}
{382}{}{Signorasi'. Ho guidato personalmente un'irruzione autorizzata nella proprieta' del sig. Cassidy.}
{383}{}{No, signora. Il sig. Cassidy non aveva pagato la licenza per la vendita di alcolici valevole per quel mese, eppure continuava a venderli nel suo locale. La lista dei suoi pagamenti e' riportata nel computer.}
{384}{}{Si'... SIGNORA.}
{385}{}{Ecco a lei, SIGNORA.}
{386}{}{Hai usato i tuoi gradi con Stark per aiutare il tuo amico Cassidy.}
{387}{}{Il Vault e' proprio qui fuori... signora.}
{388}{}{Hai esplorato Gecko per Vault City.}
{389}{}{Hai esplorato NCR per Vault City.}
{390}{}{Ad esempio... signora?}
