{100}{}{Un terminale di computer.}
{101}{}{Sono i comandi dell'unita' di estrazione organi Vault-Tec.}
{102}{}{Non sei in grado di leggere quello che c'e' sul monitor.}
{103}{}{Il modernissimo dispositivo di estrazione organi Vault-Tec vi da' il benvenuto. Per eseguire l'operazione, prego collocare il donatore nella sala operatoria, impostare la specie adatta sul quadrante e selezionare l'organo da estrarre.}
{104}{}{Seleziona specie}
{105}{}{Seleziona organo}
{106}{}{Esci.}
{107}{}{Arg!}
{108}{}{Il quadrante ha la seguente lista di animali:                  Canide                                                       Felide                                                            Struzzo                                                           Roditore                                                          Umano (inciso sulla console)}
{109}{}{}
{110}{}{}
{111}{}{}
{112}{}{}
{113}{}{}
{114}{}{Seleziona Canide}
{115}{}{Seleziona Felide}
{116}{}{Seleziona Struzzo}
{117}{}{Seleziona Roditore}
{118}{}{Seleziona Umano}
{119}{}{[Incidi un nuovo nome sulla console.]}
{120}{}{Esci.}
{121}{}{[Prendi un pezzo di metallo e pensi a cosa incidere sulla console.]}
{122}{}{Incidi la parola 'Mutante' sulla console.}
{123}{}{Incidi la parola 'Deathclaw' sulla console.}
{124}{}{Esci.}
{125}{}{Impostazioni correnti: }
{126}{}{Specie: }
{127}{}{Organo: }
{128}{}{Seleziona specie}
{129}{}{Seleziona organo}
{130}{}{Procedere con l'estrazione.}
{131}{}{Esci.}
{132}{}{Il quadrante ha la seguente lista di organi:                   Cuore                                                        Cervello                                                          Rene                                                              Fegato                                                            Polmone                                                           Appendice                                                         Colon (inciso sulla console)}
{133}{}{}
{134}{}{}
{135}{}{}
{136}{}{}
{137}{}{}
{138}{}{}
{139}{}{}
{140}{}{Seleziona Cuore}
{141}{}{Seleziona Cervello}
{142}{}{Seleziona Rene}
{143}{}{Seleziona Fegato}
{144}{}{Seleziona Polmone}
{145}{}{Seleziona Appendice}
{146}{}{Seleziona Colon}
{147}{}{Esci.}
{148}{}{Il soggetto donatore non e' presente nella sala operatoria.}
{149}{}{Estrazione fallita.}
{150}{}{Estrazione completa.}
{151}{}{Estrazione completa                                            Grazie per aver usato un prodotto Vault-Tec. Consultate il nostro catalogo per conoscere l'intera linea di prodotti Vault-Tec.}
{152}{}{}
{153}{}{Esci.}
{154}{}{Extraction failed-- local sensor overload.}
{155}{}{Extraction failed-- unable to initialize procedure for subject physiology.}
{170}{}{Umano }
{171}{}{Cane}
{172}{}{Felino }
{173}{}{Road Runner }
{174}{}{Roditore }
{175}{}{Mutante }
{176}{}{Deathclaw }
{180}{}{Cervello }
{181}{}{Cuore }
{182}{}{Rene }
{183}{}{Fegato }
{184}{}{Polmone }
{185}{}{Appendice }
{186}{}{Colon }
{200}{}{ non e' in grado di leggere quello che c'e' sul monitor.}
