{100}{}{Vedi una tomba.}
{101}{}{Vedi una tomba dissotterrata.}
{102}{}{Questa e' una fossa.}
{103}{}{La fossa e' stata dissotterrata.}
{150}{}{La fossa e' stata ricoperta di terra.}
{151}{}{La fossa e' stata dissotterata.}
{200}{}{Vedi una lapide. }
{201}{}{Vedi un paletto segnatombe. }
{250}{}{Non ci sono scritte su questa lapide.}
{251}{}{Il nome su questa lapide e' stato cancellato.}
{252}{}{Scolpito su questa lapide c'e' il nome John Doe.}
{253}{}{Il nome e la data su questo paletto sono stati cancellati dalle intemperie.}
{260}{}{Non ci sono scritte su questo paletto.}
{261}{}{Il nome su questo paletto e' stato cancellato.}
{262}{}{Inciso su questo paletto c'e' il nome John Doe.}
{263}{}{Il nome e la data su questo paletto sono stati cancellati dalle intemperie.}
{275}{}{Sulla lapide c'e' scritto: }
{276}{}{Sul paletto c'e' scritto: }
{300}{}{"Qui giace Chris Avellone, Re del Dance Floor."}
{301}{}{"Chris Jones. Figlio della notte."}
{302}{}{"Christopher Michael Holland, aka 'Chris Holland', aka 'Chris': Ci sono due ragioni e mezza per leggere questa lapide... Normalmente ci si aspetterebbe che queste ragioni fossero elencate."}
{303}{}{"Colin McComb: Un'altra vita inutile."}
{304}{}{"David Hendee: il piu' chiassoso tra i morti. Possa riposare in pace, e in silenzio."}
{305}{}{"Ed Hyland. Mando' a quel paese il mondo."}
{306}{}{"Eric Demilt. Il VERO Tipo da Combattimento."}
{307}{}{"Feargus Urquhart: Compilo' un dannato listato di troppo."}
{308}{}{"Fred Hatch. Morto mentre registrava la voce di Myron."}
{309}{}{"Gary Platner. Ucciso per non aver fatto un numero maggiore di modelli di Abitanti del Vault."}
{310}{}{"Jason Anderson: non piu' un dio vivente."}
{311}{}{"Jason G. Suinn."}
{312}{}{"Jason Taylor."}
{313}{}{"Jeremy Barnes. La scimmia calva della Black Isle."}
{314}{}{"Jesse Reynolds. Amava i biscotti allo zenzero. Troppo."}
{315}{}{"La terra qui accoglie le spoglie mortali di ThingFish, betatester, TIFONE. Desiderava tanto raggiungere Frank Zappa, il suo idolo. E' stato accontentato. R.I.P."}
{316}{}{"Qui giace quel gran rompiscatole di Nicola Baleani, betatester, TIFONE. Continuava a ripetere "un'altra perk! Il mio regno per un'altra perk!!" Ma le perk erano finite. Non che lui avesse un regno da offrirci, comunque."}
{317}{}{"Leonard Boyarski. Esiliato da Vault City."}
{318}{}{"Rupert Dinkos, morto nell'Inverno '00."}
{319}{}{"Matt Norton. Avrebbe potuto essere qualcuno. Avrebbe potuto essere un combattente, invece del coglione che era."}
{320}{}{"Nick Kesting." [C'e' un piccolo secchiello pieno di pallottole di rame sopra la tomba]}
{321}{}{"Robert Collier. Silenzioso. Mortale. Rob."}
{322}{}{"Robert Hertenstein 2. Il suo dottore aveva cercato di dirglielo, ma lui insisteva, 'Sono un po' troppe informazioni.'"}
{323}{}{"Scott Campbell. Non la zuppa."}
{324}{}{"Qui giace Scott Everts. In ritardo con il lavoro. In ritardo con la vita."}
{325}{}{"Scott Rodenhizer. Modello' le teste in 3D."}
{326}{}{"Thomas French: Morto mentre cercava di imparare la Ghigliottina Volante."}
{327}{}{"Tim Cain. Fondatore, Amante, Guerriero, Programmatore."}
{328}{}{"Tramell Ray Isaac: Qui giace uno dei piu' indefessi lavoratori di quest'industria. Animatore straordinario. Credo. R.I.P. T.Ray"}
{329}{}{"Zeb -- Piu' anziano della polvere."}
{330}{}{"Dennis Presnell. Possiamo quasi sentire la sua voce... 'E quello lo chiamate un funerale?! Faceva schifo! Ragazzi, siete dei veri !@#£ioni! Non ho intenzione di morire un'altra volta! Blah blah blah...'" Un'incisione piu' in basso recita, "Dio dia riposo a 'Piagnone' D. Se solo si fosse concentrato di piu' sulla patch..."}
{331}{}{"Rupert Diukos, morto il 24/9/96"}
{332}{}{"Sal De Ban, morto il 24/9/96"}
{333}{}{"Greg Zeschule, Autunno '99"}
{334}{}{"Ray Muzyka, Estate '98"}
{335}{}{"Evan Chantland, 74-??: Non era paranoico, c'era davvero qualcuno che lo seguiva."}
{336}{}{"Qui giace Moose, morto ammazzato. Lo abbiamo trovato qui, decapitato."}
{337}{}{"Amy Presnell."}
{338}{}{"Stephen Bokkes, anni 25. Reciso nel pieno della giovinezza dai colpi e dai dardi d'avversa fortuna." }
{339}{}{"R.I.P. Doug "Skully" Finch (la data non ha importanza). Ucciso al French Market per aver acceso una sigaretta. Le sue ultime parole - 'Ma vattela a pigliare nel culo!'"}
{340}{}{"Qui giace Donnie Cornwell, bell'e morto. Riposa in una bara enorme per contenere la sua enorme testa."}
{341}{}{"Rob Giampa visse i suoi giorni cosi' come le donne che gli piacevano: veloci, a buon mercato e facili."}
{342}{}{"T. D. Hamilton: Qui giace una fetida zoccola che sarebbe stato meglio fosse morta prima. Riposa all'inferno, Troia!"}
{343}{}{"Un'altra vittima dei tempi di consegna."}
{344}{}{"Canebomba e' morto. Lunga vita al Cane."}
{345}{}{"Kris Snider: Trooooppo competitivo."}
{346}{}{"Stai facendo qualcosa di utile con la tua vita?"}
{347}{}{"Perche' non ti ammazzi da solo e risparmi a qualcun altro il disturbo?"}
{348}{}{"Charles Cuevas: Una volta disse, 'o Hockey o morte.' Non sembra abbia avuto l'hockey."}
{349}{}{"William Lebus."}
{350}{}{"Reg Arnedo: Possiamo ancora sentire la sua voce nei corridoi."}
{351}{}{"Shanna SanPaolo."}
{352}{}{"Mandriano di brahmin."}
{353}{}{"Josh Walters, 1971-2011. Morto per complicazioni durante il suo quinto trapianto di fegato."}
{354}{}{"Doug Avery. Odio' la guerra per avergli tolto la possibilita' di andare in campeggio."}
{355}{}{"Qui giace Ezekial Aikle, anni 102. I migliori muoiono giovani."}
{356}{}{"Qui giace Ann Mann: era una donna in gamba, ma mori' in Mann. 8 dicembre, 1767"}
{357}{}{"I figli d'Israele volevano cibo e il Signore mando' loro la manna; il vecchio sagrestano Wallace voleva una moglie e il Diavolo gli mando' Anna."}
{358}{}{"Qui giace Johnny Yeast. Scusate se non mi alzo."}
{359}{}{"Qui giace il corpo di Jonathan Blake che schiaccio' il pedale dell'acceleratore invece di quello del freno."}
{360}{}{"Qui giace Butch, nessuno l'ha mai pianto. Era veloce con il grilletto, ma ad estrarre non altrettanto."}
{361}{}{"Consacrata alla memoria di mio marito John Barnes, morto il 3 gennaio 1803. La sua bella e giovane vedova, di anni 23, ha fama di essere una buona moglie e desidera ardentemente essere consolata."}
{362}{}{"Sir Giovanni Strano, qui giace un avvocato onesto, e questo e' invero Strano."}
{363}{}{"Ero qualcuno. Chi, non sono affari vostri."}
{364}{}{"Qui giace Lester Moore, quattro colpi di .44, non uno di meno, non uno di piu'."}
{365}{}{"Ve l'avevo detto che ero malato!"}
{366}{}{"O lettore, se in cerca di soldi tu sei, scava per 4 piedi e Penny tu troverai."}
{367}{}{"Diceva sempre che i suoi piedi la stavano uccidendo, ma nessuno le credeva."}
{368}{}{"Il ventiduesimo giorno di Giugno - Jonathan Fiddle - Mori' sbattendo il grugno."}
{369}{}{"Qui giace il corpo della nostra Anna, portata alla morte da una banana. Non fu il frutto il galeotto, ma la buccia, che l'osso del collo le ha rotto."}
{370}{}{"Owen Moore sta facendo un viaggio piu' lungo di quanto potesse permettersi."}
{371}{}{"In memoria di Little Chris Wood, detto "Pino". Qui giace un 'Pino' chiuso in una bara d'abete; un albero dentro un altro. Il legno esterno e' davvero molto buono, ma quello interno non possiamo giurare che lo sia.}
{372}{}{"Sotto la terra e sotto le foglie giacciono di Jonathan Pease le spoglie. C'e' solo il guscio, ei qui non e' piu': Pease ne sguscio' e da Dio ando' lassu'."}
{373}{}{"Morto per le ustioni letali riportate il 21 marzo 1870, dopo l'esplosione di una lampada riempita con il 'Combustibile Non Esplosivo di R.E. Danforth'"}
{374}{}{"Nato 1903 -- Morto 1942. Guardo' nel pozzo dell'ascensore per vedere se la cabina stava scendendo. E lo stava facendo."}
{375}{}{"Qui giace un Ateo vestito di tutto punto, ma senza un posto dove andare."}
{376}{}{"Eileen Cardillo: Frequento' la Scuola Legale W&M; adesso e' Eileen Cavillo"}
{377}{}{"Sarah Smart: Oratrice, Autrice, Professoressa, De Amicitia."}
{378}{}{"Tim Winkle - Non sopporto l'ipocrisia... a parte la mia"}
{379}{}{"Jughead - Re del Queen Archie's World"}
{380}{}{"R.I.P Casey Donahue. Morto il 6/8/98. Ucciso da una Spigola Mutante molto irritabile."}
{381}{}{"Qui giace G.M. e giace e giace e giace. p.s. Non bacio' mai una brutta ragazza"}
{382}{}{"Jay "Piedi a Patata" Nielson. Musicista. Passato a miglior vita all'eta' di 104 anni, durante un assolo di tamburo."}
{383}{}{"Nitsa - La ragione per cui Charles non ebbe il suo hockey."}
{384}{}{"Thuy Dang. Possa Dio avere pieta' del suo nome."}
{500}{}{Piazzi una trappola nella tomba.}
{501}{}{Non riesci a piazzare una trappola nella tomba.}
{510}{}{ piazza una trappola nella tomba.}
{511}{}{ non riesce a piazzare un trappola nella tomba.}
{515}{}{Trovi una trappola collegata alla tomba.}
{516}{}{Non trovi trappole collegate alla tomba.}
{520}{}{ trova una trappola collegata alla tomba.}
{521}{}{ non trova trappole collegate alla tomba.}
{525}{}{Riesci a disattivare la trappola.}
{526}{}{Non riesci a disattivare la trappola.}
{530}{}{ riesce a disattivare la trappola.}
{531}{}{ non riesce a disattivare la trappola.}
