/*
	Copyright 1998-2003 Interplay Entertainment Corp.  All rights reserved.
*/

/*
        Name:
        Location: New Reno
        Description:

        Log:

           Created: May 6, 1998

           Updated:
*/

/* Include Files */
#include "../headers/define.h"
#define NAME                    SCRIPT_NCPITBOS
#define TOWN_REP_VAR            GVAR_TOWN_REP_NEW_RENO
#include "../headers/command.h"
#include "../headers/newreno.h"

/* Standard Script Procedures */
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;

/* Script Specific Procedure Calls */
procedure Node998;                                      // This Node is Always Combat
procedure Node999;                                      // This Node is Always Ending

procedure Node001;

/* Local Variables which are saved. All Local Variables need to be
   prepended by LVAR_ */

#define LVAR_Flags                     (0)
#define LVAR_Family                    (1)

#define self_family                    (local_var(LVAR_Family))

/* Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_) */

/* Local variables which do not need to be saved between map changes. */


procedure start begin
end

procedure timed_event_p_proc begin
   if (combat_is_initialized == false) then begin
      //floater_rand(, );
   end
   nr_add_timer_event_rand(self_obj, 15, 30, float_param);
end

procedure map_enter_p_proc begin
   destroy_object(self_obj);
   /*
   if (is_loading_game == false) then begin
   end
   if (map_first_run) then begin
   end
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_NEW_RENO_);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_AI_PACKET,AI_);
   */
   nr_add_timer_event_rand(self_obj, 5, 30, float_param);
end

procedure critter_p_proc begin
   if ((hostile) and (self_can_see_dude)) then begin

      self_attack_dude;
   end
end

procedure damage_p_proc begin
   if (source_obj == dude_obj) then begin
      set_personal_enemy;
   end
end

procedure pickup_p_proc begin
   if (source_obj == dude_obj) then begin
      call Node998;
   end
end

procedure talk_p_proc begin
   set_herebefore;
end

procedure destroy_p_proc begin
   // inc__critter ***
   dec_family_counter(self_family);
end

procedure look_at_p_proc begin
   script_overrides;
   // display_mstr(100); ***
end

procedure description_p_proc begin
   script_overrides;
   // display_mstr_rand(,); ***
   set_examined;
end

procedure use_skill_on_p_proc begin
end

procedure Node998 begin
   if (hostile == false) then begin
      set_hostile;
   end
end
procedure Node999 begin
end
/*
#define is_insert_message(x)  ((x == ) or (x == ) or        \
                               ((<= x) and (x <= )) or     \
                               (x == ))

*/

procedure Node001 begin
   // floater_rand(, ); ***
end
/*
# 0. QUICK LOOK
{100}{}{You see the casino pit boss.}

# 0. LOOK
{150}{}{You see a well-dressed man. He is surveying the casino.}
{151}{}{You see a pit boss. He is surveying the casino.}

# 1. FLOAT DIALOGUE: POWER ARMOR (WTG)
{200}{}{Uh…you'll need to remove that armor.}
{201}{}{Uh, sir…or ma'am…you'll need to remove that armor.}
{202}{}{Sir…ma'am…you can't wear that in the casino.}

# 2. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, SNEAK (WTG)
{205}{}{Uh, why are you sneaking around, sir?}
{206}{}{Uh, are you undercover, sir?}

# 3. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, SNEAK (WTG)
{210}{}{Uh, why are you sneaking around, ma'am?}
{211}{}{Uh, are you undercover, ma'am?}

# 4. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, NIGHT (WTG)
{215}{}{Good evening, }
{1215}{}{, sir.}
{216}{}{Evening, }
{1216}{}{, sir.}

# 5. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, NIGHT (WTG)
{220}{}{Good evening, }
{1220}{}{, ma'am.}
{221}{}{Evening, }
{1221}{}{, ma'am.}

# 6. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO (WTG)
{225}{}{Good day, }
{1225}{}{, sir.}

# 7. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO (WTG)
{230}{}{Good day, }
{1230}{}{, ma'am.}

# 8. FLOAT DIALOGUE: MALE, MADE MAN, NOT SAME CASINO (WTG)
{235}{}{Friend, you're walking into the wrong casino.}
{236}{}{You better leave. Now.}
{237}{}{This ain't the place to be gambling with your life. You better leave.}
{238}{}{Bitch, you're walking into the wrong casino.}

# 10. FLOAT DIALOGUE: MALE, PRIZEFIGHTER/PORN STAR (ARMED) (WTG)
{245}{}{Sir, I'm sorry, you'll have to secure that weapon.}

# 11. FLOAT DIALOGUE: FEMALE, PRIZEFIGHTER (ARMED) (WTG)
{250}{}{Ma'am, I'm sorry, you'll have to secure that weapon.}

# 12. FLOAT DIALOGUE: PORN STAR, FEMALE (ARMED) (WTG)
{255}{}{Honey, I'm sorry, you can't carry weapons into the casino. [Smiles.] You're deadly enough as it is.}

# 13. FLOAT DIALOGUE: PORN STAR, FEMALE (SNEAK) (WTG)
{260}{}{Honey, with a body like that, you won't be able to sneak anywhere.}

# 14. FLOAT DIALOGUE: MALE, NO REP (ARMED) (WTG)
{265}{}{Tribal, you better secure that weapon right *now.*}

# 15. FLOAT DIALOGUE: MALE, NO REP (SNEAK) (WTG)
{270}{}{Tribal, you better stop that sneaking around shit right *now.*}

# 16. MYRON, MORDINO (WTG)
{275}{}{[To Myron] Hey, hey…Myron! Ain't seen you outside the lab in a long time.}
{276}{}{[To Myron] You here to sample some of the new merchandise, Myron?}
{277}{}{[To Myron] Hey! Come on in, Myron.}

# 17. MARCUS (WTG)
{285}{}{[Nods at Marcus.] No mutants. He waits outside.}
{286}{}{[Nods at Marcus.] I don't care if your friend one of the Ex-Men, mutants wait outside.}
{287}{}{[Glares at Marcus.] That mutant freak ain't allowed in here.}

# 18. ROBOBRAIN (WTG)
{295}{}{No droids.}
{296}{}{We don't serve droids.}
{297}{}{No droids. They wait outside.}

# 19. FLOAT DIALOGUE: FLAG: ENCLAVE DESTROYED IS TRUE  (WTG)
{305}{}{I'm not s'posed ta chat while on duty, but I'm glad you kicked the Enclave's ass.}
{306}{}{Hey, }
{1306}{}{. Take a rest from saving the world and have some fun.}

# 20. FLOAT DIALOGUE: DAY (WTG)
{315}{}{Need some more chips at table three…}
{316}{}{Good crowd today…}

# 21. FLOAT DIALOGUE: NIGHT (WTG)
{325}{}{Need some more chips at table three…}
{326}{}{Good crowd tonight…}

# 22. INTRO (WTG)
{335}{}{Hey, }
{336}{}{! Heard yer the one who kicked the Enclave back to the stone age! [Becomes formal.] I've been instructed to give you some caps, courtesy of the casino. Enjoy yourself, sir.}
{337}{}{! Heard yer the one who kicked the Enclave back to the stone age! [Becomes formal.] I've been instructed to give you some caps, courtesy of the casino. Enjoy yourself, ma'am. [Winks.]}
{338}{}{. [Smiles.] What's up, chief? Something I can do for you? Get you a drink, get you a waitress?}
{339}{}{. [Smiles.] Prettiest girl at the casino. Something I can do for you, ma'am? Get you a drink? A private table?}
{340}{}{[The pit boss doesn't take his eyes away from the casino floor.] What can I do for you, pal?}
{341}{}{[The pit boss doesn't take his eyes away from the casino floor.] What can I do for you, hon?}
{342}{}{Fooooooo foo foo fooooo}
{343}{}{Wander off [Leave.]}
{344}{}{Who are you?}
{345}{}{What casino is this?}
{346}{}{Can you tell me a little about the casino?}
{347}{}{You know somebody named Pretty Boy Lloyd?}
{348}{}{Who's that old guy at the slot machine?}
{349}{}{That comic you got on stage is weak. Mind if I try?}
{350}{}{Thanks. Do you need a dancer for the night? I'm open for a limited engagement.}
{351}{}{Thanks, I will. [Leave.]}
{352}{}{Nothing, thanks. Sorry to bother you. [Leave.]}
{353}{}{Just checking on things. Carry on. [Leave.]}

# 23. PORN STAR (WTG)
{360}{}{Hey, look who's here! Hey, }
{361}{}{. [Smiles.] Welcome to [CN]. Love your films.}
{362}{}{Fooooooo foo foo fooooo}
{363}{}{Wander off [Leave.]}
{364}{}{Who are you?}
{365}{}{What casino is this?}
{366}{}{Can you tell me a little about the casino?}
{367}{}{You know somebody named Pretty Boy Lloyd?}
{368}{}{Who's that old guy at the slot machine?}
{369}{}{Thanks. Do you need a dancer for the night? I'm open for a limited engagement.}
{370}{}{Thanks, I'm flattered. Just stopped by to say hello. [Leave.]}

# 24. I HAD SOME QUESTIONS (31, 32, 33, 34, 35, 36, 37, 38)
{280}{}{Shoot. What d'you want to know?}
{281}{}{Fooooooo foo foo fooooo}
{282}{}{Wander off [Leave.]}
{283}{}{Who are you?}
{284}{}{What casino is this?}
{285}{}{Can you tell me a little about the casino?}
{286}{}{You know somebody named Pretty Boy Lloyd?}
{287}{}{Who's that old guy at the slot machine?}
{288}{}{That comic you got on stage is weak. Mind if I try?}
{289}{}{Thanks. Do you need a dancer for the night? I'm open for a limited engagement.}
{290}{}{Thanks, I will. [Leave.]}
{291}{}{Nothing, thanks. Sorry to bother you. [Leave.]}
{292}{}{Just checking on things. Carry on. [Leave.]}

# 25.  RETARD (22, 23, 24)
{300}{}{Uh, you better run along now, sir.}
{301}{}{Uh, you better run along now, ma'am.}
{302}{}{[Sneers.] Get outta here, retard.}
{303}{}{Mom says I was speshal}
{304}{}{Wander off [Leave.]}

# 26.  MOM SAYS I WAS SPESHAL (25)
{315}{}{Yeah, yer Mom said I was special, too. Now take a hike…maybe she's along Virgin street somewhere.}
{316}{}{Oh goodie! Bye bye [Leave.]}
{317}{}{Wander off [Leave.]}

# 27.  WHO ARE YOU? (22, 23, 24, 29, 30, 31)
{325}{}{I'm the pit boss. [Looks slightly irritated.] Now what can I do for you?}
{326}{}{I run the floor of the casino here. You need anything, just ask.}
{327}{}{What casino is this?}
{328}{}{Can you tell me a little about the casino?}
{329}{}{Nothing, thanks. Sorry to bother you.}

# 28.  WHAT CASINO IS THIS? (22, 23, 24, 27)
{335}{}{This is [CN]. Need anything, just ask.}
{336}{}{This is [CN]. At least, last time I checked the sign outside the door. [Frowns.] Now what can I do for you?}
{337}{}{Who are you?}
{338}{}{Can you tell me a little about the casino?}
{339}{}{Nothing, thanks. Sorry to bother you.}

# 29.  WHAT CAN YOU TELL ME ABOUT THIS CASINO? (22, 23, 24, 27, 28, 30)
{345}{}{Best goddamn casino in town…but I am a little biased. [Laughs.] Anything else you want to know?}
{346}{}{Best goddamn casino in town, best goddamn tables…now why don't you run along now, check 'em out? All right?}
{347}{}{Who are you?}
{348}{}{Who owns this casino?}
{349}{}{Okay, thanks. Sorry to bother you. [Leave.]}

# 30.  WHO OWNS THIS CASINO? (29)
{355}{}{The [CA] family. They pumped a lot of life into this place, made it a real night spot, a shining jewel in New Reno.}
{356}{}{The [CA] Family. [Glances at you.] That a problem? Cause if you ain't here to gamble, then this ain't the place for you. Understand?}
{357}{}{Who are you?}
{358}{}{Can you tell me a little about the casino?}
{359}{}{I see. Thanks for your time. [Leave.]}

# 31.  McGEE (22, 23, 24)
{365}{}{That guy? Old Man McGee? Crazy sumabitch…he's been playing that machine there for the past few years, waiting for the big jackpot. His life fortune must be sitting in that thing, but it won't give him a single cap.}
{366}{}{That guy? Old Man McGee? Crazy sumabitch, that's for sure. Heh. Sure was pissed about you winning his fortune. I'd be careful around him.}
{367}{}{Is the machine rigged?}
{368}{}{I had some other questions…}
{369}{}{Thanks for the information. [Leave.]}

# 32.  IS THE MACHINE RIGGED? (31)
{375}{}{[Shakes his head.] Nope, it's just stubborn…just like him. [Shrugs.] It could probably use a little repair work, but we ain't got no slot mechanics that can fix that damn thing.}
{376}{}{I had some other questions…}
{377}{}{Interesting. Thanks for the information. [Leave.]}

# 33.  PRETTY BOY LLOYD? (22, 23, 24)
{385}{}{Yeah, that son of a bitch came in here about a week ago, ripped off one table of about a thousand caps, then bailed. Don't know where he is now, but he used to have a room at the Desperado.}
{386}{}{Yeah, some guy by that name was rentin' one of th' rooms upstairs...204. He was all paid up, but he bailed a few days ago and nobody saw him leave.}
{387}{}{Mr. Salvatore mentioned that there was a specific dealer that Lloyd won the money from. Who was that?}
{388}{}{I had some other questions…}
{389}{}{Thanks for the information. [Leave.]}

# 34.  NIKKI? (33)
{395}{}{Nikki? [Scans the floor.] Yeah, she's over there, at the middle table. Is there some sort of problem?}
{396}{}{No problem. Just wanted to meet her. I had some other questions…}
{397}{}{Thanks for the information. [Leave.]}

# 35.  NIKKI DEAD (33)
{405}{}{Her name *was* Nikki. She used to work here but she got aced…not too long ago.}
{406}{}{Hmmm. Do you mind if I ask you some other questions…?}
{407}{}{Interesting. Thanks for the information. [Leave.]}

# 36.  NIKKI RAN (33)
{415}{}{Her name was Nikki. She used to work here but she took off not too long ago. Just packed her shit and bailed.}
{416}{}{Do you mind if I ask you some other questions…}
{417}{}{Interesting. Thanks for the information. [Leave.]}

# 37.  NEED A DANCER (22, 23, 24)
{425}{}{Sure, be good for business. Dressing room's in the back…}
{426}{}{[Perform.]}
{427}{}{Not right now. I had some other questions…}
{428}{}{Not right now, but I'll be back. [Leave.]}

# 38.  NEED A DANCER (22, 23, 24)
{435}{}{[Shakes his head.] No, we're still recovering from your last gig. You might want to check some of the other casinos.}
{436}{}{All right, thanks. Say, I had some other questions…}
{437}{}{Okay…though I *will* be back. [Leave.]}

# 39.  PERFORM (37)
{445}{}{You count up the evening's tally. Caps. Not a bad haul.}
{446}{}{The leather was a nice touch.}
{447}{}{That ball gag you had with you didn't hurt, either.}
{448}{}{[Done.]}

# 40.  PERFORM (22, 24)
{455}{}{Yeah, he stinks worse than brahmin shit. Still, you…? [Looks you up and down skeptically.] Aw, why the hell not. A little improv ain't gonna hurt, but it's a rough crowd…better hope you're good.}
{456}{}{Oh, I'm good…just watch me go.}
*/