{100}{}{Te encuentras con rufianes y lobos.}
{101}{}{Te encuentras con rufianes.}
{102}{}{Te encuentras con lobos.}
{103}{}{Te encuentras con escorpiones rad.}
{104}{}{Te encuentras con plantas de esporas.}
{105}{}{Te encuentras con una Patrulla de la Unidad luchando contra rufianes.}
{106}{}{Te encuentras con una Patrulla de la Unidad luchando contra lobos.}
{107}{}{Te encuentras con una Patrulla de la Unidad.}
{150}{}{Te encuentras con esclavistas y perros.}
{151}{}{Te encuentras con esclavistas.}
{152}{}{Te encuentras con geckos dorados.}
{153}{}{Te encuentras con perros salvajes.}
{154}{}{Te encuentras una patrulla con perros luchando contra esclavistas.}
{155}{}{Te encuentras unos esclavistas luchando contra geckos dorados.}
{156}{}{Te encuentras una patrulla luchando contra esclavistas.}
{157}{}{Te encuentras una patrulla luchando contra geckos dorados.}
{158}{}{Te encuentras una patrulla luchando contra perros salvajes.}
{159}{}{Te encuentras con una patrulla.}
{200}{}{Eres emboscado por saqueadores.}
{201}{}{Te encuentras con lobos.}
{202}{}{Te encuentras con una caravana que lucha por defenderse de saqueadores.}
{203}{}{Te encuentras con una caravana que lucha por defenderse de saqueadores.}
{204}{}{Te encuentras con una caravana que lucha por defenderse de saqueadores}
{205}{}{Te encuentras con una caravana que lucha por defenderse de saqueadores.}
{206}{}{Te encuentras con una caravana.}
{207}{}{Te encuentras con una caravana.}
{208}{}{Te encuentras con una caravana.}
{209}{}{Te encuentras con una caravana.}
{250}{}{Te encuentras con unos merodeadores.}
{251}{}{Te encuentras con lobos.}
{252}{}{Te encuentras con escorpiones rad.}
{253}{}{Te encuentras con una caravana que lucha por defenderse de los merodeadores.}
{254}{}{Te encuentras con una caravana que lucha por defenderse de los merodeadores.}
{255}{}{Te encuentras con una caravana defendiéndose de unos lobos.}
{256}{}{Te encuentras con una caravana defendiéndose de mutaescorpiones.}
{257}{}{Te encuentras con una caravana.}
{258}{}{Te encuentras con una caravana.}
{259}{}{Te encuentras con una caravana.}
{260}{}{Te encuentras con una caravana.}
{261}{}{Te encuentras con un viajero.}
{300}{}{Te encuentras con restos del ejército del Maestro.}
{301}{}{Te encuentras con unos merodeadores.}
{302}{}{Te encuentras con Rangers de la RNC combatiendo contra restos del ejército del Maestro.}
{303}{}{Te encuentras con Rangers de la RNC luchando contra bandidos.}
{304}{}{Te encuentras con granjeros defendiéndose de los restos del ejército del Maestro.}
{305}{}{Te encuentras con granjeros defendiéndose de bandidos.}
{306}{}{Te encuentras con Rangers de la RNC.}
{307}{}{Te encuentras con unos granjeros.}
{350}{}{Te encuentras con una caravana de esclavistas.}
{351}{}{Te encuentras con unos asaltantes y ladrones.}
{352}{}{Te encuentras con unos asaltantes.}
{353}{}{Te encuentras con unos ladrones.}
{354}{}{Te encuentras una caravana defendiéndose de unos asaltantes.}
{355}{}{Te encuentras una caravana peleando con unos ladrones.}
{356}{}{Te encuentras con una caravana luchando contra asaltantes.}
{357}{}{Te encuentras con una caravana asediada por ladrones.}
{358}{}{Te encuentras con una caravana de esclavos luchando contra una caravana.}
{359}{}{Te encuentras con asaltantes luchando contra ladrones.}
{360}{}{Te encuentras con una caravana.}
{361}{}{Te encuentras con una caravana.}
{400}{}{Te encuentras con unos asaltantes.}
{401}{}{Te encuentras con unos ladrones.}
{402}{}{Te encuentras con ladrones y asaltantes.}
{403}{}{Te encuentras con geckos dorados y escorpiones rad.}
{404}{}{Te encuentras con geckos dorados.}
{405}{}{Te encuentras con ratas topo y ratas cerdo.}
{406}{}{Te encuentras con escorpiones rad.}
{407}{}{Te encuentras con plantas de esporas.}
{408}{}{Te encuentras con ladrones luchando contra asaltantes.}
{409}{}{Te encuentras una caravana defendiéndose de unos asaltantes.}
{410}{}{Te encuentras con una caravana defendiéndose de ladrones.}
{411}{}{Te encuentras con una caravana defendiéndose de mutaescorpiones.}
{412}{}{Te encuentras con geckos luchando contra escorpiones rad.}
{413}{}{Te encuentras con una caravana.}
{450}{}{Te encuentras con unos asaltantes y ladrones.}
{451}{}{Te encuentras con asaltantes y geckos.}
{452}{}{Te encuentras con geckos dorados.}
{453}{}{Te encuentras con escorpiones rad y plantas de esporas.}
{454}{}{Te encuentras con unos ladrones luchando contra escorpiones rad.}
{455}{}{Te encuentras con escorpiones rad luchando contra ladrones.}
{456}{}{Te encuentras una caravana defendiéndose de unos asaltantes.}
{457}{}{Te encuentras con una caravana defendiéndose de ladrones.}
{458}{}{Te encuentras con algunos asaltantes podando algunas plantas de esporas.}
{459}{}{Te encuentras con una caravana.}
{500}{}{Te encuentras con asaltantes y perros salvajes.}
{501}{}{Te encuentras con ladrones y perros salvajes.}
{502}{}{Te encuentras con unos ladrones.}
{503}{}{Te encuentras con unos asaltantes.}
{504}{}{Te encuentras con un enjambre de mantis y algunas plantas de esporas.}
{505}{}{Te encuentras con perros y plantas de esporas.}
{506}{}{Te encuentras con un enjambre de mantis.}
{507}{}{Te encuentras con perros salvajes.}
{508}{}{Te encuentras con ladrones luchando contra perros.}
{509}{}{Te encuentras con una caravana defendiéndose de unos perros.}
{510}{}{Te encuentras con una caravana defendiéndose de ladrones.}
{511}{}{Te encuentras una caravana defendiéndose de unos asaltantes.}
{512}{}{Te encuentras con una caravana.}
{550}{}{Te encuentras con geckos y lobos.}
{551}{}{Te encuentras con incursores.}
{552}{}{Te encuentras con lobos.}
{553}{}{Te encuentras con geckos dorados.}
{554}{}{Te encuentras con prospectores defendiéndose de incursores.}
{555}{}{Te encuentras con tramperos cazando geckos.}
{556}{}{Te encuentras con contrabandistas de licor luchando contra lobos.}
{557}{}{Te encuentras con unos colonos luchando contra incursores.}
{558}{}{Te encuentras con unos colonos luchando contra lobos.}
{559}{}{Te encuentras con contrabandistas de licor.}
{560}{}{Te encuentras con tramperos.}
{561}{}{Te encuentras con prospectores.}
{600}{}{Te encuentras con sanguinarios.}
{601}{}{Te encuentras con geckos de fuego.}
{602}{}{Te encuentras con una caravana huyendo de sanguinarios.}
{603}{}{Te encuentras con una caravana luchando contra sanguinarios.}
{604}{}{Te encuentras con una caravana luchando contra geckos de fuego.}
{605}{}{Te encuentras con una caravana luchando contra geckos de fuego.}
{606}{}{Te encuentras con una caravana.}
{607}{}{Te encuentras con una caravana.}
{608}{}{Te encuentras con una caravana.}
{609}{}{Te encuentras con una caravana.}
{650}{}{Te encuentras con aliens y sanguinarios.}
{651}{}{Te encuentras con centauros y nómadas.}
{652}{}{Te encuentras con geckos de fuego.}
{653}{}{Te encuentras con aliens.}
{654}{}{Te encuentras con sanguinarios.}
{655}{}{Te encuentras con geckos de fuego.}
{656}{}{Te encuentras con aliens.}
{657}{}{Te encuentras con centauros.}
{658}{}{Te encuentras con nómadas.}
{700}{}{Te encuentras con algunos Yakuza.}
{701}{}{Te encuentras con una banda.}
{702}{}{Te encuentras con algunos lobos.}
{703}{}{Te encuentras con algunos gángsters luchando contra algunos Yakuza.}
{704}{}{Te encuentras con algunos gángsters luchando contra una banda.}
{705}{}{Te encuentras con algunos gángsters.}
{706}{}{Te encuentras con un viajero.}
{750}{}{Te encuentras con una caravana defendiéndose de los restos del ejército del Maestro.}
{751}{}{Te encuentras con una caravana luchando contra los restos del ejército del Maestro.}
{752}{}{Te encuentras con una caravana luchando contra sanguinarios.}
{753}{}{Te encuentras con una caravana.}
{754}{}{Te encuentras con una caravana.}
{755}{}{Te encuentras con una caravana.}
