{100}{}{Ves un terminal de ordenador.}
{101}{}{Ves el terminal del ordenador de Darion.}
{102}{}{Ves el terminal de un ordenador estandar. Parece estar funcionando y listo para usar.}
{103}{}{Accedes al ordenador y rápidamente escaneas todos los archivos disponibles. Entre algunos diarios personales,
encuentras varios informes detallados sobre la RNC. Parece que hay un espía en su consejo. Copias el informe a un holodisco.}
{104}{}{Tienes dificultades para acceder a los archivos.}
{105}{}{Hecho.}
{106}{}{Salvo por los informes sobre el espía de la RNC, el ordenador no contiene más información útil.}
{107}{}{Hecho.}
