{100}{}{Ves un terminal de ordenador.}
{101}{}{Ves el terminal informático de la biblioteca.}
{102}{}{Ves el terminal de un ordenador estandar. Parece estar funcionando y listo para usar.}
{103}{}{Accedes al ordenador y rápidamente escaneas todos los archivos disponibles. Encuentras la localización
del Refugio 13 y lo copias en tu PIP-Boy.}
{104}{}{Tienes dificultades para acceder a los archivos.}
{106}{}{Con excepción de la localización del Refugio 13, el ordenador no contiene más información útil.}
