{100}{}{Ves un terminal de ordenador.}
{101}{}{Ves el terminal del ordenador del centro de energía.}
{102}{}{Ves el terminal de un ordenador estandar. Parece estar funcionando y listo para usar.}
{103}{}{Este terminal supervisa el generador de energía. Indica que todo está funcionando con normalidad.}
{104}{}{Este terminal supervisa el generador de energía. Indica que la unidad está apagada debido a algún fallo.}
{105}{}{Hecho.}
