{100}{}{Ves a una persona aburrida, vestida con una armadura de cuero.}
{101}{}{Ves a Max, el guardia de las caravanas.}
{102}{}{Ves a una persona polvorienta y aburrida, vistiendo una armadura de cuero. Por el olor a brahmin y la confiada
 forma de caminar, esta persona es claramente un guardia de caravana.}
{103}{}{¿Puedo ayudarte en algo?}
{104}{}{¿Urg?}
{105}{}{¡Tra-bajo aquí!}
{106}{}{¿Quién eres?}
{107}{}{¿Qué puedes contarme sobre Chad?}
{108}{}{No tengo paciencia para los idiotas. Lo siento, amigo, pero tendrás que buscar a algún otro con quien jugar.}
{109}{}{::sniff::}
{110}{}{Soy Max. Uno de los guardias de las caravanas.}
{111}{}{¿Qué puedes contarme sobre Chad?}
{112}{}{Gracias. Adiós.}
{113}{}{No me gusta mucho. Parece que siempre recibe dinero extra de sus trabajos de las caravanas. Es muy injusto.}
{114}{}{Bueno, Marcus sospecha que está rociando parte del dinero que se supone que va a Broken Hills.}
{115}{}{Gracias. Adiós.}
{116}{}{Thanks. I'm sure glad that's over. You better watch your back though.}
{117}{}{Adiós.}
{118}{}{¡Es el enemigo! ¡Muere!}
{119}{}{Ups.}
{120}{}{[Lowers his voice and looks around] That's gotta be it. I once saw myself that he was taking some "slice" of that money he got from uranium shipment from Gecko.}
{121}{}{Really? Then why didn't you report that to Marcus?}
{122}{}{¿Eres tonto? Si voy a contarlo, mucha gente en este ciudad ni siquiera me mirará. Además, podría tener algún tipo de venganza.}
{123}{}{Hmm, podría decirlo a Marcus, porque no hacer el plan a quedar aquí demasiado tiempo de todos modos.}
{124}{}{De acuerdo. Haz lo que quieras, pero no dice nada sobre me. Y nunca tuvimos esta conversación, vale?}
{125}{}{No te preocupes, no quiero te meter en problemas, adiós.}
