{100}{}{Ves a un hombre sonriente con armadura de cuero.}
{101}{}{Ves a Steve, el ordenanza de Broken Hills.}
{102}{}{Ves a un hombre amigable con armadura de cuero. Parece como si estuviera ahí de pie todo el día esperando a alguien con quien hablar.}
{103}{}{¡Hola! Soy Steve. Soy el tipo que puede decirte dónde está cada sitio y qué es qué en este hermoso pueblo. ¿Puedo darte alguna dirección o ayudarte en algo hoy?}
{104}{}{Duh...}
{105}{}{¿Noken Heel?}
{106}{}{Háblame sobre este sitio.}
{107}{}{¿Quienes viven aquí?}
{108}{}{¿Quién está al mando?}
{109}{}{¿Qué hay de nuevo?}
{110}{}{¿Qué servicios se ofrecen por aquí?}
{111}{}{No. Lo siento.}
{112}{}{Oh, pequeño. Otro pobre niño del Yermo. Bien, pasa. Verás que somos tan hospitalarios como cualquiera de las otras ciudades del Yermo.}
{113}{}{¡Tíooooooooooooo!}
{114}{}{Exacto. Buena suerte, viajero. Y adiós.}
{115}{}{¡Dos!}
{116}{}{Broken Hills. Somos un pueblo minero. Cavamos para obtener cosas. Luego las vendemos.}
{117}{}{¿Cavar?}
{118}{}{¡Veder!}
{119}{}{Correcto. Sacar de la tierra. Tenemos una mina. Sin embargo, no creo que tengan un trabajo para ti. Si quieres uno, habla con el Proveedor.}
{120}{}{Bi-en.}
{121}{}{¿Vender cosas?}
{122}{}{Vendemos lo que extraemos a otras ciudades de por aquí. Ellos lo encuentran útil. Si quieres vender algo, puedes hablar con la mayoría de los mercaderes de por aquí. De cualquier forma, debo volver al trabajo. Sé bueno y cuídate, ¿vale?}
{123}{}{¡Va-le! ¡Adiooooos!}
{124}{}{Debo volver al trabajo. Sé bueno y cuídate, ¿vale?}
{125}{}{You again? Well, you know what you have to do -- be good and careful. Take care!}
{126}{}{¡Va-le! ¡Adiooooos!}
{127}{}{Guarda tus armas, compañero. No obtendrás respuestas de mí mientras las muestres de esa forma.}
{128}{}{Somos una pequeña comunidad minera. Fundada hace varias décadas por nuestro sheriff, Marcus, y un hombre llamado Jacob. Eligieron este sitio porque estaba cerca de algunos depósitos de uranio. ¿Quieres que te cuente más?}
{129}{}{Sí.}
{130}{}{No.}
{131}{}{Somos un colectivo de humanos, mutantes y necrófagos. No tenemos las tensiones raciales que plagan Ciudad Refugio; para nosotros, todos somos iguales.}
{132}{}{¿Vivís al lado de mutantes? ¿No sabéis que son malvados?}
{133}{}{¿Iguales?}
{134}{}{Gracias. Adiós.}
{135}{}{Nominalmente, el sheriff Marcus está al cargo de la ciudad. Ayudó a fundarla, y nos ayuda a atravesar nuestras crisis. Lo cierto, sin embargo, es que todos en la ciudad tienen voz.}
{136}{}{Eso parece impracticable.}
{137}{}{Parece una buena forma de dirigir las cosas.}
{138}{}{Sigue.}
{139}{}{¿El tipo que ayudó a crear la ciudad sigue al cargo? Eso implica que será muy, muy viejo.}
{140}{}{Gracias. Adiós.}
{141}{}{Sin contar que todos los mutantes estén MUERTOS y el pueblo CONDENADO…}
{142}{}{Sin contar que todos los mutantes estén muertos y nuestra única fuente de sustento haya sido destruida…}
{143}{}{Aparte de ti siendo un héroe al exponer la corrupción que había entre nosotros…}
{144}{}{Aparte de descubrir que tenemos un cáncer entre nosotros, con la fuga de Franc y Manson…}
{145}{}{Aside from Chad's betrayal of the city and your justice -- for which everyone's grateful -- }
{146}{}{No mucho, realmente.}
{147}{}{Tengo más preguntas.}
{148}{}{Adiós.}
{149}{}{Oh. Otra vez tú.}
{150}{}{Hola de nuevo.}
{151}{}{Bienvenido de nuevo.}
{152}{}{¿Quieres saber más?}
{153}{}{¿Qué hay de nuevo?}
{154}{}{¿Quién está al mando?}
{155}{}{Háblame sobre este sitio.}
{156}{}{¿Quienes viven aquí?}
{157}{}{¿Qué servicios se ofrecen por aquí?}
{158}{}{No, gracias.}
{159}{}{Vivimos de refinar el mineral que extraemos de las colinas, y venderlo a comunidades cercanas como Ciudad Refugio, Gecko y la República de Nueva California. Usamos un poco para nuestra propia red eléctrica. ¿Algo más?}
{160}{}{Sí.}
{161}{}{No.}
{162}{}{Todos somos iguales. Todos procedemos del ser humano; todos tenemos lo mismo bajo el exterior. Decir que alguien es malvado únicamente por su apariencia sólo indica ignorancia.}
{163}{}{¿Me estás llamando ignorante?}
{164}{}{Es verdad.}
{165}{}{No necesariamente. ¿Quién sabe qué hizo el virus que mutó sus mentes?}
{166}{}{Lo que sea. Adiós.}
{167}{}{Entendemos que funciona bien para nuestros propósitos. Además, Marcus es sumamente justo.}
{168}{}{¿Dónde puedo encontrar a Marcus?}
{169}{}{Adiós.}
{170}{}{Es viejo. Pero lo lleva bien. Verás, es un mutante, y aparentemente ellos viven más que el resto.}
{171}{}{¿Dejáis que un MUTANTE dirija este sitio? ¿Estáis locos?}
{172}{}{¿De verdad? Habría jurado que la mayoría estarían muertos a día de hoy.}
{173}{}{Un sheriff mutante, ¿eh? Apuesto a que entonces casi todos respetan la ley. Eso debe funcionar bien.}
{174}{}{Adiós.}
{175}{}{So now we're eking out a living, creating our own version of civilization, and doing our best
 to avoid giving in to Vault City or NCR -- we don't need their style of government. That's all.}
{176}{}{Genial. Tengo más preguntas.}
{177}{}{Gracias. Adiós.}
{178}{}{Si vas a insistir en la creencia de que puedes juzgar la mente de alguien por lo que ves en su exterior, entonces sí. Eres indudablemente ignorante.}
{179}{}{Al diablo contigo, amigo. TÚ eres el ignorante.}
{180}{}{Oh, de acuerdo. Es un buen argumento.}
{181}{}{De todas formas, eso es todo lo que quería decir. Bienvenido a Broken Hills.}
{182}{}{Espera.}
{183}{}{Adiós.}
{184}{}{If the mutants intended us harm, they'd have moved on us before now. They're not going to last
 forever -- in fact, most of them are going senile now. Building a community isn't going to help them
 achieve their aims.}
{185}{}{Es un buen argumento.}
{186}{}{Siguen siendo malvados.}
{187}{}{Adiós.}
{188}{}{Amigo, cuanto más hablo contigo, más tonto me siento. Con esa actitud, no serás bienvenido en Broken Hills. Discúlpame. Tengo trabajo que hacer.}
{189}{}{Capullo.}
{190}{}{Hora de morir, cabrón.}
{191}{}{We have a mine, a refinery, a tavern, a hotel -- which, by the way, has lost its owner, so we
 just let people stay there free -- a hospital, a general store, and a chemist. We grow our own food.}
{192}{}{Bien. Tengo más preguntas.}
{193}{}{Adiós.}
{194}{}{Bueno, muchos lo han hecho. Dado que los mutantes son estériles… o eso me han hecho creer… están muriendo. Los que quedan se están volviendo seniles. Marcus no, sin embargo. Sigue tan listo como siempre.}
{195}{}{¿Dónde puedo encontrar a Marcus?}
{196}{}{Tengo más preguntas.}
{197}{}{Adiós.}
{198}{}{Marcus, ¿estás seguro de que no quieres quedarte y liderarnos un tiempo más?}
{199}{}{Marcus: Eso no tiene futuro. Lo haréis bien sin mí.}
{200}{}{[MÁS]}
{201}{}{Amigo, no te queremos aquí. Ya has hecho suficiente daño.}
{202}{}{[HECHO]}
{300}{}{You can usually find Marcus near the bank -- that also serves as a tougher jail -- or at the
 Jail. Sometimes he's in the tavern or at home, but he's usually working.}
{301}{}{¡Alborotador!}
{302}{}{¡Maldición!}
{303}{}{¡Hurra!}
{304}{}{¡Canallas!}
{305}{}{¡Esa sucia rata!}
