{100}{}{Ves a un anciano con profundas arrugas en su rostro. Si se ha dado cuenta de que le miras, no da señales de ello.}
{101}{}{Ves a Cassidy.}
{102}{}{Ves a un anciano con profundas arrugas en su rostro. Te saluda con un movimiento de cabeza.}
{103}{Cas0103}{Well, now. I ain't seen you around before, stranger. Name's Cassidy. I run this place. What can I do for you?}
{104}{Cas0104}{Well now, if it ain't the mysterious stranger. What can I do for you today?}
{105}{}{¿Hacer yo?}
{106}{}{Dejas de balbucear}
{107}{}{Estoy buscando el Refugio.}
{108}{}{¿Ya estás buscando el irte de aquí?}
{109}{}{¿Qué tienes para tomar?}
{110}{}{¿Pasa algo interesante por aquí?}
{111}{}{Hoy nada, gracias.}
{112}{Cas0112}{Hit on the head a little too often, eh? Sorry, I don't speak imbecile.}
{113}{}{be-cil?}
{114}{Cas0114}{Vault? Only Vault I know of is the one inside the city. Big friggin' hole... you can't miss it, trust me.}
{115}{}{¿Qué tienes para beber?}
{116}{}{¿Pasa algo interesante por aquí?}
{117}{}{Gracias por las indicaciones. Adiós.}
{118}{Cas0118}{Beer for $20, shot of whiskey for $30. Nothing special. Why, you want something?}
{119}{}{Estoy buscando el Refugio.}
{120}{}{Tomaré una cerveza.}
{121}{}{Que sea un trago de whisky.}
{122}{}{¿Pasa algo interesante por aquí?}
{123}{}{En realidad, no. Gracias de todos modos.}
{124}{Cas0124}{"Interesting?" Heh. Friend, Vault City ain't an "interesting" place... unless the guards get bored, then you
 better take cover. Why you asking? You looking for something in this sinkhole?}
{125}{}{¿Qué tienes para beber?}
{126}{}{En realidad, estoy buscando el Refugio.}
{127}{}{Esto no puede ser tan malo.}
{128}{}{En realidad, no. Gracias de todos modos.}
{129}{Cas0129}{Here you go. Drink up. It might help you forget where you are.}
{130}{}{Este lugar no puede ser tan malo.}
{131}{}{Gracias, por la bebida. Tengo que irme.}
{132}{Cas0132}{Oh, really? Well, hell then, I must be mistaken, considering YOU'RE the authority and all. Guess you must have been napping during the raid last week?}
{133}{}{¿Hubo un asalto?}
{134}{Cas0134}{Aw, yeah, a beautiful sight it was. A guard patrol broke in here looking for "illegal substances." They busted down the door, busted up my stock, then busted up a few of my customers, too.}
{135}{}{¿Qué sucedió después?}
{136}{}{Lamento oír eso. Hablaremos más tarde.}
{137}{Cas0137}{After they hauled away this one guy, Joshua, for resisting arrest, they fined my ass for finding - get this - REAL whiskey on the premises. Nevermind that I got a permit from Stark three months before. Bastards.}
{138}{}{Wow. ¿En serio?}
{139}{}{Lamento oír eso. Hablaremos más tarde.}
{140}{Cas0140}{It gets better. Now I'm in debt to the guards for the fine, an' I had to buy a new case of alcohol from a merchant at triple my standard rate. I'm expecting the guards to come knocking again soon, just to bust my chops. }
{141}{}{¿Cómo es la mayor parte del tiempo?}
{142}{}{Espero que las cosas mejoren en el futuro. Nos vemos.}
{143}{Cas0143}{Even the good days ain't worth a damn. The Citizens don't drink much, so I'm stuck here pouring drinks for merchants. The next cheap sonuvabitch who haggles for a drink is going to be wearing his ass as a hat.}
{144}{}{¿Por qué estás aquí si tanto odias el lugar?}
{145}{}{Lamento oír eso. Estoy buscando un Refugio. ¿Puedes ayudarme?}
{146}{}{Lamento oír eso. Espero que las cosas mejoren.}
{147}{Cas0147}{I have a bad heart. Need cardio booster shots to keep it beating. This city's the only place to get real medical care, so I thought I'd settle here, try and make a living.}
{148}{}{Pareces bastante harto del lugar.}
{149}{}{Ya veo. Mira, estoy buscando un Refugio. ¿Puedes ayudarme?}
{150}{}{Espero que las cosas te vayan mejor de ahora en adelante. Nos vemos.}
{151}{Cas0151}{Makes me want to close up shop and let this City rot. Screw 'em all.}
{152}{}{¿Por qué no te marchas?}
{153}{}{Siento oír eso. Espero que te salgan bien las cosas.}
{154}{Cas0154}{Go into the wastes by myself? Ha! I'm sick of this place, but I ain't stupid.}
{155}{}{Yo me dirijo de nuevo a ese camino. ¿Por qué no me acompañas?}
{156}{}{Bien, buena suerte entonces.}
{157}{Cas0157}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{158}{Cas0158}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{159}{Cas0159}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{160}{Cas0160}{Naw... you look like you got enough of a crowd already.}
{161}{}{De acuerdo. Bien, buena suerte.}
{162}{}{Entonces olvida lo que te he preguntado, capullo. Sigue atendiendo tu bar en esta apestosa ciudad.}
{163}{}{No importa. Tú te lo pierdes.}
{164}{Cas0164}{Heh. You serious?}
{165}{}{Claro. ¿Por qué no? Tienes pinta de saber cuidar de ti mismo en una pelea.}
{166}{}{Pensándolo mejor, ahí fuera hay bastante peligro, en especial para alguien con problemas de corazón. Mejor que te quedes aquí.}
{167}{Cas0167}{All right, count me in.}
{168}{}{Vamos allá.}
{169}{}{}
{170}{}{}
{171}{Cas0171}{What's up? You got that "I need to tell you something you might not like" look again.}
{172}{Cas0172}{Yeah?}
{173}{Cas0173}{What's up? You got that "I'm pulling rank" look again.}
{174}{}{Quería hacerte algunas preguntas...}
{175}{}{Parece que te han hecho daño. Usa algunos estimulantes para curarte.}
{176}{}{Cassidy, necesito que esperes aquí hasta que vuelva.}
{177}{}{Guarda tu arma.}
{178}{}{Quedarse cerca de mí.}
{179}{}{No te alejes demasiado.}
{180}{}{Deberíamos separarnos un poco.}
{181}{}{Vamos, Cassidy. Hora de marcharse.}
{182}{}{Nada, no importa.}
{261}{Cas0261}{You want me to put a bullet in Myron's head, is that it? It'd be no trouble. Just give the word.}
{262}{Cas0262}{What's on your mind?}
{263}{}{¿Por qué quieres cargarte a Myron?}
{264}{}{¿Qué armas sabes manejar?}
{265}{}{En realidad, había otra cosa que quiero que hagas...}
{266}{}{En realidad, había algo que quiero que hagas...}
{267}{}{No importa. Movámonos.}
{268}{}{No, no le hagas daño a Myron. Hoy no, al menos. Te mantendré informado.}
{269}{Cas0269}{Well, shotguns and rifles, mostly... just personal preference. I ain't a bad shot with pistols, neither.}
{270}{}{¿Algo más?}
{271}{}{Vale. Tenía otras preguntas...}
{272}{}{Está bien. Sólo lo comprobaba.}
{273}{Cas0273}{If you ever need to learn somebody some manners up close and personal, slip me some brass knuckles, and I can tapdance on their face with my fists.}
{274}{}{Fantástico. ¿Algo más?}
{275}{}{Vale. Tenía otras preguntas...}
{276}{}{Está bien. Sólo lo comprobaba.}
{277}{Cas0277}{Uh, well... just between you and me, I can also use a spear pretty good. Me and my buddies used to hunt radscorpions with spears way back when... fact I'm alive and they ain't might tell you something.}
{278}{}{No veo nada malo en usar una lanza.}
{279}{}{Vale. Tenía otras preguntas...}
{280}{}{Está bien. Sólo lo comprobaba.}
{281}{Cas0281}{Says you. Just don't be calling me no tribal, and we'll get along just fine.}
{282}{Cas0282}{Don't want people mistaking me for ol' Bone-nose over there. Heh-heh. I ain't never seen no tribal do something as dumb as jam a bone in his nose.}
{283}{Cas0283}{Of course there isn't. Spear's a fine weapon. Lots of tribal friends of mine use 'em.}
{284}{}{¿Sabías que yo soy un “tribal"?}
{285}{}{Mmm, mira, tengo otras preguntas...}
{286}{}{De acuerdo. Gracias por la lección.}
{287}{Cas0287}{Aw, don't be playing with ol' Cassidy now. You ain't no tribal.}
{288}{}{Sí, lo soy.}
{289}{}{Lo que sea. Mira, tenía unas preguntas más...}
{290}{}{Olvídalo. No quiero entrar en eso contigo en este momento.}
{291}{Cas0291}{Uh, well... damn it all, you can have my apology right here and now. I didn't mean any offense.}
{292}{}{Seguro que no. Verás, tenía otras preguntas...}
{293}{}{Olvídalo. Movámonos.}
{294}{Cas0294}{Well, now, before you go, I got a question for you. What are we doing out here? We seem to be running all over the place looking for something. Have we got some sort of plan?}
{295}{}{Buscamos un GECK: un Kit de Creación del Jardín del Edén. Mi pueblo necesita recuperar sus cultivos.}
{296}{}{Vamos al Refugio, para después devolver el GECK a mi aldea.}
{297}{}{Mi tribu ha sido secuestrada. Estoy intentando descubrir qué les pasó.}
{298}{Cas0298}{Them things come in kits now, huh? Man, the good book don't mention that, does it? Well, all right then. Let's get hunting.}
{299}{Cas0299}{Huh. All right then, just checking.}
{300}{Cas0300}{I wouldn't mind plugging a few holes in some kidnappers. A little frontier justice never hurt anyone... well, at least not me.}
{301}{}{De acuerdo. Vamos.}
{302}{Cas0302}{The things that little cuss says ain't fit for decent ears.}
{303}{Cas0303}{Especially a woman's.}
{304}{}{Pues, Cassidy, no sabía que te importaba. Mi corazón está todo alborotado.}
{305}{}{¿Y? ¿Qué estás diciendo?}
{306}{}{Ya sabes, tú blasfemas lo tuyo, Cassidy.}
{307}{}{Dímelo a mí. En marcha.}
{308}{Cas0308}{Yeah, but when I do it, it's got style. He's just a little trash mouth.}
{309}{Cas0309}{And I don't like the way he looks at you, neither.}
{310}{}{Pues, Cassidy, no sabía que te importaba. Mi corazón está todo alborotado.}
{311}{}{¿Y? ¿Qué estás diciendo?}
{312}{}{Dímelo a mí. En marcha.}
{313}{Cas0313}{Now hold on, I didn't mean it like that.}
{314}{Cas0314}{All I'm saying is that bona fide little asshole's gonna get his number clocked one day when it's just me and him and a hole in the desert.}
{315}{}{Bueno, la vida puede ser una maestra dura en sí misma. Tenía algunas preguntas para ti...}
{316}{}{Bien, de todas formas está obligado a morder en todo momento. Yo no me preocuparía.}
{317}{}{Tranquilízate, Cassidy. Deja tranquilo a Myron.}
{318}{}{Odio este lugar.}
{319}{}{Había tenido la esperanza de que nos mantendríamos alejados de este lugar para siempre.}
{320}{}{Ciudad de reprimidos...}
{321}{}{Este lugar parece peor que Ciudad Refugio.}
{322}{}{Afortunadamente comprobé mis armas antes de venir aquí.}
{323}{}{Si estiro la pata, no me entierres aquí.}
{324}{}{Ten cuidado por aquí. Los lugareños no son demasiado amigables.}
{325}{}{Je. Nunca pensé que vería San Francisco.}
{326}{}{Nunca pensé que mantendrías a un viejo veterano como yo dando vueltas tanto tiempo. Vamos a hacer este trabajo, y volvamos a casa.}
{327}{}{Redding es un pueblo minero. Oro, en su mayor parte. Muchas caravanas van a Ciudad Refugio desde aquí.}
{328}{}{Broken Hills es un pueblo minero... de mineral de uranio, en su mayor parte. Puede ser un lugar complicado, así que ándate con ojo.}
{329}{}{Algún veneno recorre mi cuerpo. ¿Tienes algún antídoto?}
{330}{}{Estoy brillando como un cartel de neón. ¿Tienes alguna droga anti-radiación?}
{331}{}{Estoy bastante herido. ¿Tienes algún estimulante?}
{332}{}{No te metas en líos, Myron. Te estoy vigilando.}
{333}{}{Acércate, Myron, y te rajo.}
{334}{}{Maldición, Lenny, necesitas un baño. O algo de desinfectante.}
{335}{}{Necrofaguito, mejor que mantengas la maldita distancia. Porque, campeón, apestas.}
{336}{}{Ese es el perro con peor pinta que haya visto alguna vez.}
{337}{}{Calma, chucho. Cassidy es tu amigo, ¿vale?}
{338}{}{Me pregunto lo que come ese ciberperro. Humanos, seguro.}
{339}{}{Si ese ciberperro empieza a tirar de mi pierna, me lo cargo.}
{340}{}{Ahhhh. Amigo, menos mal que hicieron millones de estas cosas antes de lanzar las bombas.}
{341}{}{Gracias, amigo.}
{342}{}{Espero que tomar estos estimulantes no me dañe el corazón...}
{343}{}{Pero qu--?! ¡No, mi corazón! Yo... *hrrrkkk*}
{344}{}{Perdón, sólo admiraba la vista.}
{345}{}{Maldición, entonces estaré por aquí.}
{346}{}{Perdona, amigo. No quería bloquear tu camino.}
{347}{}{Ahhhhh. Eso ha dado en la diana. Muchas gracias.}
{348}{}{*Hic* je je. Nada como la vieja agua de fuego para mantener la sangre corriendo por mis venas.}
{349}{}{Gracias. Demonios, tú también deberías tomar un trago.}
{350}{}{Ese es el Refugio. Menudo pedazo de sitio, ¿a que sí?}
{351}{}{¿Quieres que me una a ti otra vez?}
{352}{}{Estoy listo cuando tú estés listo.}
{353}{}{¿Seguro que no necesitas mi ayuda?}
{354}{}{Tengo ganas de ponerme en marcha.}
{355}{}{Claro que podría ir a fumar.}
{356}{}{Papá me puso el nombre por un personaje de comic de antes de la guerra. Decía que él también era un hijoputa.}
{357}{}{Es agradable viajar otra vez. Vivir en Ciudad Refugio me estaba provocando una úlcera.}
{358}{}{Espero que mi corazón no me dé guerra mientras estamos de viaje...}
{359}{}{Claro que podría tomar un trago.}
{360}{}{Mejor será que vuelva a comprobar mi equipo.}
{361}{}{Maldita artritis...}
{362}{}{Si tuviera veinte años menos, me gustaría ir al este y explorar el Medio Oeste. Ahora es demasiado tarde, supongo.}
{363}{}{He oído que tienen tornados con kilómetros de anchura en el Medio Oeste. Ahora es un gran desierto radiactivo.}
{364}{}{Me pregunto si Texas sobrevivió a la guerra...}
{365}{}{Gracias, amigo. Yo... hey. Empiezo a ver borroso.}
{366}{}{He oído que este material te hace alucinar...¡Ey! ¡¿De dónde demonios salieron estas serpientes?!}
{367}{}{Cada vez que tomo esta cosas, me vienen a la cabeza viejos recuerdos.}
{368}{}{Nada como un poco de curativo tribal de mala muerte...}
{369}{}{Creo que voy a necesitar unas muletas y una silla de ruedas.}
{370}{}{Cassidy muere de un ataque al corazón.}
{371}{}{Has convencido a Cassidy para unirse a tu grupo.}
{372}{}{Sólo déjame sacar una píldora para el corazón primero...}
{1000}{Cas1000}{Well... all right, then. I'll wait here 'til you get back. }
{1100}{Cas1100}{Sure. Can't promise I won't pull it out again if there's trouble, though.}
{1200}{Cas1200}{All right, I'll stick close to you then. You must be expecting trouble.}
{1300}{Cas1300}{All right, I'll keep some distance. Get a better vantage point that way.}
{1400}{Cas1400}{All right, I'll be watching your back. You need me, holler, and I'll come running.}
{2000}{Cas2000}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{2100}{Cas2100}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{2200}{Cas2200}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{2300}{Cas2300}{Naw... you look like you got enough of a crowd already.}
{2400}{Cas2400}{All right, then.}
{2999}{}{De acuerdo. Ten cuidado, entonces.}
{3000}{}{Salgamos.}
{3100}{}{Entonces olvida lo que he dicho, gilipollas.}
{3200}{}{No importa, entonces. Tú te lo pierdes.}
{4100}{Cas4100}{Okay, everything's stitched up. I'm good to go.}
{4200}{Cas4200}{Okay, pretty much everything is patched up.}
{4300}{Cas4300}{That pretty much did it, but I could use a couple more stims.}
{4400}{Cas4400}{I used what I could, but I'm still pretty messed up. If you got any more stims to spare, I could sure use 'em. I can still walk, though.}
{9999}{}{Quería hacerte algunas preguntas...}
{10001}{}{Toma algún estimulante más y cúrate.}
{10002}{}{Cassidy, necesito que esperes aquí hasta que vuelva.}
{10003}{}{Guarda tu arma.}
{10004}{}{Quedarse cerca de mí.}
{10005}{}{No te alejes demasiado.}
{10006}{}{Deberíamos separarnos un poco.}
{10007}{}{Vámonos pues.}
{10100}{}{Vamos, Cassidy. Hora de marcharse.}
{20000}{Cas20000}{All right, I'm listening.}
{20001}{Cas20001}{My gear? What about it?}
{20002}{Cas20002}{No problem. Too hot for that kinda gear, anyway. Makes me sweat like a New Reno whore.}
{20003}{}{Intentemos una formación diferente.}
{20004}{}{Tengo que hablar contigo sobre tu armamento.}
{20005}{}{Olvídalo. Mantengamos la formación que tenemos ahora.}
{20006}{}{No importa. No hay nada que necesite saber sobre tu armamento.}
{20007}{}{Necesito quitarte la armadura que llevas.}
