call ..\p WCBRNBOT
call ..\p WCDEDBOT
call ..\p WCDOBBS
call ..\p WCREPBOT
call ..\p WCSECBOT
call ..\p WCTURRET
call ..\p WIBAYDOR
call ..\p WIBNKDOR
call ..\p WIBRKBRN
call ..\p WIELVDOR
call ..\p WIENTDOR
call ..\p WIEVCDSK
call ..\p WIEXPDSK
call ..\p WIGNNDSK
call ..\p WIHOWITZ
call ..\p WILV1DOR
call ..\p WIMEDDSK
call ..\p WIMISDSK
call ..\p WIPASWRD
call ..\p WIPNCHBG
call ..\p WIRETSCN
call ..\p WISCRTDR
call ..\p WITRPBX1
call ..\p WSEMIT1A
call ..\p WSEMIT1B
call ..\p WSEMIT1C
call ..\p WSEMIT1D
call ..\p WSEMIT1E
call ..\p WSEMIT2A
call ..\p WSEMIT2B
call ..\p WSEMIT2C
call ..\p WSEMIT2D
call ..\p WSEMIT3A
call ..\p WSEMIT3B
call ..\p WSEMIT4A
call ..\p WSEMIT4B
call ..\p WSEMIT4C
call ..\p WSFELD1A
call ..\p WSFELD1B
call ..\p WSFELD1C
call ..\p WSFELD1D
call ..\p WSFELD1E
call ..\p WSFELD2A
call ..\p WSFELD2B
call ..\p WSFELD2C
call ..\p WSFELD2D
call ..\p WSFELD3A
call ..\p WSFELD3B
call ..\p WSFELD4A
call ..\p WSFELD4B
call ..\p WSFELD4C
call ..\p WSKLAXON
call ..\p WSPWRDWN
call ..\p WSTERM1A
call ..\p WSTERM1B
call ..\p WSTERM2A
call ..\p WSTERM2B
call ..\p WSTERM2C
call ..\p WSTERM3A
call ..\p WSTERM3B
call ..\p WSTERM3C
call ..\p WSTERM4A
call ..\p WSTERM4B
call ..\p WSTERM4C
call ..\p WTELFLR2
call ..\p WTLNDMIN
call ..\p WTPLTRP0
call ..\p WTPLTRP1
call ..\p WTPLTRP2
call ..\p WTPLTRP3
call ..\p WTPLTRP4
call ..\p WTPLTRP5
call ..\p WTPLTRP6
call ..\p WTPLTRP7
call ..\p WTPLTRP8
call ..\p WTPLTRP9
call ..\p WTPLTRPA
call ..\p WTPLTRPB
call ..\p WTPLTRPC
call ..\p WTPLTRPD
call ..\p WTPLTRPE
call ..\p WTPLTRPF
