{100}{}{Du ser en vanlig tam brahmin.}
{101}{}{Brahminens extra huvud är troligen resultatet av en vanlig
 ko som utsattes för tidigt för strålning.}
{102}{}{Du lägger inte märke till något ovanligt med brahminen.}
{103}{}{Brahmin aren't much for conversations.}
{104}{}{Don't you have anything better to do than sit around
 talking to a two-headed cow?}
{105}{}{Brahmin are a mutated breed of cows.}
