{100}{}{Du ser Lucas.}
{101}{}{Lucas är den främste krigaren i din stam.}
{102}{}{Så där är du, Utvalde. Hmmmph! Hur går ditt uppdrag?}
{103}{}{Ganska bra.}
{104}{}{Inte så bra.}
{105}{}{Ugh?!}
{106}{}{Jag måste fortsätta.}
{107}{}{Du kanske behöver en krigares hjälp.}
{108}{}{Visst. Vad kan du hjälpa mig med?}
{109}{}{Nej. Det går bra.}
{110}{}{Bra svar, dumskalle. Håll tyst nu medan jag övar.}
{111}{}{Uh-kej.}
{112}{}{Jag vet hur man slåss med nävar och fötter. Tror 'u att du kan lära dig det?}
{113}{}{Vad kan du lära mig?}
{114}{}{Må vinden vara i din rygg, Utvalde.}
{115}{}{Farväl.}
{116}{}{Hmmm -- tillbringa en dag med mig så ska jag lära dig hur man slår hårdare.}
{117}{}{Okej. Då gör vi det.}
{118}{}{Tyvärr, har inte tid just nu.}
{119}{}{Du vet allt jag kan lära dig, Utvalde. Lycka till i ditt sökande.}
{120}{}{Åh, okej.}
{121}{}{Ha! Utvalde, du är inte graciös nog för att jag ska kunna lära dig något.}
{122}{}{Åh, okej.}
{123}{}{Du är inte tillräckligt snabb i strid för att min träning ska hjälpa dig, Utvalde.}
{124}{}{Åh, okej.}
{125}{}{Du måste lära dig mer om strid innan jag kan hjälpa dig, lillebror.}
{126}{}{Åh, okej.}
{127}{}{Jag kan lära dig en kraftfullare spark. Det kommer att ta oss en hel dag.}
{128}{}{Okej.}
{129}{}{Jag kan lära dig tillräckligt för att slåss bättre. Det kommer att ta oss en dag.}
{130}{}{Okej.}
{131}{}{Du har lärt dig väl, Utvalde. Må vinden vara i din rygg.}
{132}{}{Tack för din hjälp.}
{133}{}{Jag har lärt dig allt jag kan, Utvalde. Lycka till med ditt uppdrag.}
