{100}{}{Du ser Jordan, som snurrar på sitt spjut som vanligt.}
{101}{}{Du ser Jordan, som snurrar på sitt spjut som vanligt.}
{102}{}{Lycka till! Jag måste återgå till min träning.}
{103}{}{Hej, utvalde. Jag ser att du behöver lite träning. Kan jag vara till hjälp?}
{104}{}{Visst.}
{105}{}{Nej tack.}
{106}{}{Det här kommer att ta en liten stund.}
{107}{}{Sådär, du har lärt dig allt jag kan lära dig om spjut.}
{108}{}{Tack Jordan, det kommer att hjälpa mycket.}
