{100}{}{Du ser Jordan, som snurrar på sitt spjut som vanligt.}
{101}{}{Du ser Jordan, som snurrar på sitt spjut som vanligt.}
{102}{}{Lycka till! Vår by är beroende av dig.}
{103}{}{Utvalde, som du använder ett spjut blir du kött åt geckoödlorna
 på nolltid. Jag kan visa dig några trick.}
{104}{}{Visst.}
{105}{}{Nej, tack.}
{106}{}{Det här kommer att ta en liten stund.}
{107}{}{Du lär dig fort -- det ser ut som om du har lärt dig allt jag kan
 lära dig.}
{108}{}{Tack Jordan, det kommer att hjälpa mycket.}
