{100}{}{Du ser Klint, en stamfrände.}
{101}{}{Du ser Klint.}
{102}{}{Du ser en ung man med stora muskler och en mycket självsäker utstrålning.}
{103}{}{God dag på dig,}
{104}{}{. Du har inte avklarat den Äldste prövning och får inte passera.}
{105}{}{Eh...}
{106}{}{Jag måste tillbaka till byn.}
{107}{}{Jag har några frågor till dig.}
{108}{}{Visst, nu ska jag göra prövningen.}
{109}{}{(suck)}
{110}{}{. You go temple. You take test. You not come back here until take test. Obey Elder. Go!}
{111}{}{Me go.}
{112}{}{Forgive me, }
{113}{}{, but I cannot allow you to pass. If you wish to return to the village you may do so only by passing the trial set before you.}
{114}{}{I see. I guess I'll be going then.}
{115}{}{Can I ask you some questions then?}
{116}{}{I could kick your ass and just walk out of here.}
{117}{}{Forgive me, but I have no answers to your questions. Take the trial set before you by the Elder and prove yourself worthy to lead our people.}
{118}{}{Mycket bra.}
{119}{}{Två personer som arbetar tillsammans kan flytta obelisken som blockerar vägen. Ensam skulle du misslyckas. Jag har inte för avsikt att hjälpa dig förrän du klarar den Äldstes prövning.}
{120}{}{M-hm. Jag fattar.}
{121}{}{Var hälsad, Utvalde! Det är trevligt att se dig. Hur kan jag tjäna dig?}
{122}{}{Jag säga hej. Det allt.}
{123}{}{Jag tänkte bara säga hej. Jag ger mig snart av på mitt uppdrag.}
{124}{}{Må våra förfäders andar skydda dig, Utvalde. Jag önskar dig lycka till på din resa.}
