{100}{}{You see Klint, a fellow tribesman.}
{101}{}{You see Klint.}
{102}{}{You see a young man with bulging muscles and a very confident air about him.}
{103}{}{Good day to you, }
{104}{}{. You have not completed the trial of the Elder and may not pass.}
{105}{}{Eh...}
{106}{}{I need to go back to the village.}
{107}{}{I have some questions for you.}
{108}{}{All right, I'm off to take the test.}
{109}{}{(suck)}
{110}{}{. You go temple. You take test. You not come back here until take test. Obey Elder. Go!}
{111}{}{Me go.}
{112}{}{Forgive me, }
{113}{}{, but I cannot allow you to pass. If you wish to return to the village you may do so only by passing the trial set before you.}
{114}{}{I see. I guess I'll be going then.}
{115}{}{Can I ask you some questions then?}
{116}{}{I could kick your ass and just walk out of here.}
{117}{}{Forgive me, but I have no answers to your questions. Take the trial set before you by the Elder and prove yourself worthy to lead our people.}
{118}{}{Very well.}
{119}{}{Två personer som arbetar tillsammans kan flytta obelisken som blockerar vägen. Ensam skulle du misslyckas. Jag har inte för avsikt att hjälpa dig förrän du klarar den Äldstes prövning.}
{120}{}{M-hm. Jag fattar.}
{121}{}{Var hälsad, Utvalde! Det är trevligt att se dig. Hur kan jag tjäna dig?}
{122}{}{Jag säga hej. Det allt.}
{123}{}{Just thought I'd say hello. I'll be leaving on my quest soon.}
{124}{}{May the spirits of our ancestors protect you, Chosen One. I wish you well on your journey.}
