{100}{}{Du ser Klint, en stamfrände.}
{101}{}{Du ser Klint.}
{102}{}{Du ser en ung man med stora muskler och en mycket självsäker utstrålning.}
{103}{}{God dag på dig,}
{104}{}{. Du har inte avklarat den Äldste prövning och får inte passera.}
{105}{}{Eh...}
{106}{}{Jag måste tillbaka till byn.}
{107}{}{Jag har några frågor till dig.}
{108}{}{Visst, nu ska jag göra prövningen.}
{109}{}{(suck)}
{110}{}{. Du gå tempel. Du gör test. Du inte komma tillbaka före du har gjort prov. Lyd Äldste. Gå!}
{111}{}{Jag gå.}
{112}{}{Förlåt mig, }
{113}{}{, men jag kan inte låta dig passera. Om du vill återvända till byn kan du bara göra det genom att klara av den prövning som ställs inför dig.}
{114}{}{Jag förstår. Jag antar att jag borde gå då.}
{115}{}{Får jag ställa några frågor då?}
{116}{}{Jag skulle kunna spöa dig och bara gå härifrån.}
{117}{}{Förlåt mig, men jag har inga svar på dina frågor. Ta den prövning som den Äldste har satt dig inför och visa dig värdig att leda vårt folk.}
{118}{}{Mycket bra.}
{119}{}{Två personer som arbetar tillsammans kan flytta obelisken som blockerar vägen. Ensam skulle du misslyckas. Jag har inte för avsikt att hjälpa dig förrän du klarar den Äldstes prövning.}
{120}{}{M-hm. Jag fattar.}
{121}{}{Var hälsad, Utvalde! Det är trevligt att se dig. Hur kan jag tjäna dig?}
{122}{}{Jag säga hej. Det allt.}
{123}{}{Jag tänkte bara säga hej. Jag ger mig snart av på mitt uppdrag.}
{124}{}{Må våra förfäders andar skydda dig, Utvalde. Jag önskar dig lycka till på din resa.}
