{100}{}{Du ser Morlis, en av dina mostrar -- hon som aldrig gillade dig.}
{101}{}{Varför stör du mig, brorson? Kan du inte se att jag är upptagen?}
{102}{}{Umm, okej. Förlåt.}
{103}{}{Vad är det? Du vet att jag har mycket att göra!}
{104}{}{Ummm, Mynoc sa...}
{105}{}{Vad sa Mynoc? Ut med det, barn!}
{106}{}{Att, ehh, du kanske har lite flinta.}
{107}{}{I do. You want some, is that it?}
{108}{}{Well, yeah.}
{109}{}{Well... I want three doses of healing powder. Bad times are coming
 and I'm going to be ready. Bring them to me and you can have the flint. Now
 get to it!}
{110}{}{Yes, ma'am!}
{111}{}{Now don't waste my time. Do you have the powders?}
{112}{}{Yes, here they are.}
{113}{}{Umm, I guess not.}
{114}{}{Here is the flint. Now off with you! I don't have time to gossip.}
{115}{}{Thank you, Aunt Morlis.}
{116}{}{Again you waste my time, worthless nephew! How did you ever become
 the Chosen One?}
{117}{}{Yes, Aunt Morlis.}
{118}{}{Uh, Aunt Morlis, I have three right here.}
{150}{}{Aunt Morlis, I'm on a perilous quest for the salvation of our village.
 My chances of success will be greatly enhanced if I keep the healing powders
 for myself and you give me the flint. Don't you agree?}
{151}{}{What do you think you are doing, child? This is no way for the Chosen One to act. Now get out of my sight!}
{152}{}{If this flint is so important that you are willing to disgrace the name of the Chosen One, then here. Take
 the flint and get out of my sight.}
{153}{}{Yes, Aunt Morlis.}
{154}{}{Well... Oh, very well. Here is the flint. I wish you a safe journey, child. }
{155}{}{No, I don't. Now stop wasting my time and get out of here!}
{156}{}{Yes, Aunt Morlis.}
{200}{}{So you've returned. Did you find the holy Thirteen?}
{201}{}{No, Aunt Morlis, I...}
{202}{}{Then get yourself out of here and find it! People are depending on you!}
{203}{}{Yes, Aunt Morlis.}
{204}{}{Well, here you are again. Have you once again failed to complete your quest?}
{205}{}{Yes, Aunt Morlis, but...}
{206}{}{Then get yourself out of here and don't come back until you do! Why waste time coming back here, when you could be using that time to continue your search!?}
{207}{}{Yes, Aunt Morlis.}
{208}{}{The fact that you are standing here must mean that you have completed your quest. You wouldn't waste precious time returning here empty-handed, would you?}
{209}{}{Yes, Aunt Morlis. I mean no, Aunt Morlis. Uh, I've got to go, Aunt Morlis.}
{210}{}{So, child. Once again you stand before me. Are you empty-handed yet again?}
{211}{}{Yes, Aunt Morlis.}
{212}{}{Lyssna,}
{213}{}{. People are dying, cattle are dying, and crops are failing. Everyone is either hungry, sick, or both. Our time draws near. If you do not find the GECK soon, we are doomed. Do you understand me?}
{214}{}{Yes, Aunt Morlis.}
{215}{}{Then get yourself out of here and find the GECK! People are depending on you!}
{216}{}{Yes, Aunt Morlis.}
{300}{}{Well, I seem to have misplaced the flint. Oh well, at least I got my powders. Now off with you! I don't have time to gossip.}
{301}{}{Why do you bother me, niece? Can't you see I'm busy?}
{302}{}{Well, I can't seem to find the flint. I'm sure you took it from me when I wasn't looking though. I caught you before. Now off with you! I don't have time to gossip.}
{303}{}{Well... Oh, I'm sorry but I seem to have misplaced the flint. I wish you a safe journey though, child. }
{304}{}{I already gave you the flint, stupid. Now stop wasting my time and get out of here!}
{305}{}{I already gave you the flint, stupid. Oh well, at least I got my powders. Now off with you! I don't have time to gossip.}
