{100}{}{Du ser Morlis, en av dina mostrar -- hon som aldrig gillade dig.}
{101}{}{Varför stör du mig, brorson? Kan du inte se att jag är upptagen?}
{102}{}{Umm, okej. Förlåt.}
{103}{}{Vad är det? Du vet att jag har mycket att göra!}
{104}{}{Ummm, Mynoc sa...}
{105}{}{Vad sa Mynoc? Ut med det, barn!}
{106}{}{Att, ehh, du kanske har lite flinta.}
{107}{}{Det har jag. Du vill ha lite, är det så?}
{108}{}{Alltså, ja.}
{109}{}{Ja, men... Jag vill ha tre doser läkande pulver. Dåliga tider är på väg
 och jag kommer att vara redo. Ta dem till mig och du kan få flintan.
 Sätt igång nu!}
{110}{}{Ja, frun!}
{111}{}{Slösa inte bort min tid nu. Har du pulvret?}
{112}{}{Ja, här är det.}
{113}{}{Hmm. Jag antar inte det.}
{114}{}{Här är flintan. Iväg med dig nu! Jag har inte tid att skvallra.}
{115}{}{Tack, moster Morlis.}
{116}{}{Återigen slösar du bort min tid, värdelöse brorson! Hur blev du någonsin
 den Utvalde?}
{117}{}{Ja, moster Morlis.}
{118}{}{Eh, moster Morlis, jag har tre här.}
{150}{}{Moster Morlis, jag är på en farlig resa för att rädda vår by.
 Mina chanser att lyckas ökar om jag behåller läkepulvret
 för mig själv och du ger mig flintan. Håller du inte med?}
{151}{}{Vad tror du att du gör, unge? Detta är inget sätt för den Utvalde att agera. Försvinn ur min åsyn nu!}
{152}{}{Om den här flintan är så viktig att du är beredd att vanära den Utvaldes namn, så ta den. Ta
 flintan och försvinn ur min åsyn.}
{153}{}{Ja, moster Morlis.}
{154}{}{Jaha... Åh, mycket bra. Här är flintan. Jag önskar dig en säker resa, mitt barn.}
{155}{}{Nej, det gör jag inte. Sluta slösa bort min tid och försvinn härifrån!}
{156}{}{Ja, moster Morlis.}
{200}{}{Så du har återvänt. Hittade du det heliga Tretton?}
{201}{}{Nej, moster Morlis, jag...}
{202}{}{Then get yourself out of here and find it! People are depending on you!}
{203}{}{Ja, moster Morlis.}
{204}{}{Ja, nu är du tillbaka igen. Har du än en gång misslyckats med att slutföra ditt uppdrag?}
{205}{}{Ja, moster Morlis, men...}
{206}{}{Ge dig då härifrån och kom inte tillbaka förrän du har gjort det! Varför slösa tid på att komma tillbaka hit, när du kan använda den tiden till att fortsätta ditt sökande!?}
{207}{}{Ja, moster Morlis.}
{208}{}{Eftersom du står här måste det betyda att du har slutfört ditt uppdrag. Du skulle inte slösa bort dyrbar tid på att återvända hit tomhänt, eller hur?}
{209}{}{Ja, moster Morlis. Jag menar nej, moster Morlis. Eh, jag måste gå, moster Morlis.}
{210}{}{Så, mitt barn. Ännu en gång står du framför mig. Är du tomhänt ännu en gång?}
{211}{}{Ja, moster Morlis.}
{212}{}{Lyssna,}
{213}{}{. Människor dör, boskap dör och skördarna slår fel. Alla är antingen hungriga, sjuka eller både och. Vår tid närmar sig. Om du inte hittar GECK snart, är vi dödsdömda. Förstår du vad jag säger?}
{214}{}{Ja, moster Morlis.}
{215}{}{Ge dig då av och hitta GECK! Folk är beroende av dig!}
{216}{}{Ja, moster Morlis.}
{300}{}{Jag verkar ha tappat bort flintan. Nå ja, jag har i alla fall mitt pulver. Iväg med dig nu! Jag har inte tid att skvallra.}
{301}{}{Why do you bother me, niece? Can't you see I'm busy?}
{302}{}{Jag kan inte hitta flintan. Jag är säker på att du tog den från mig när jag inte tittade. Jag har fångat dig förut. Iväg med dig nu! Jag har inte tid att skvallra.}
{303}{}{Jaha... Åh, jag är ledsen, men jag verkar ha tappat bort flintan. Jag önskar dig en säker resa, mitt barn. }
{304}{}{Jag har redan gett dig flintan, dumbom. Sluta slösa bort min tid och stick härifrån!}
{305}{}{I already gave you the flint, stupid. Oh well, at least I got my powders. Now off with you! I don't have time to gossip.}
