{100}{}{Du ser Morlis, en av dina mostrar -- hon som aldrig gillade dig.}
{101}{}{Varför stör du mig, brorson? Kan du inte se att jag är upptagen?}
{102}{}{Umm, okej. Förlåt.}
{103}{}{Vad är det? Du vet att jag har mycket att göra!}
{104}{}{Ummm, Mynoc sa...}
{105}{}{Vad sa Mynoc? Ut med det, barn!}
{106}{}{Att, ehh, du kanske har lite flinta.}
{107}{}{Det har jag. Du vill ha lite, är det så?}
{108}{}{Alltså, ja.}
{109}{}{Ja, men... Jag vill ha tre doser läkande pulver. Dåliga tider är på väg
 och jag kommer att vara redo. Ta dem till mig och du kan få flintan.
 Sätt igång nu!}
{110}{}{Ja, frun!}
{111}{}{Slösa inte bort min tid nu. Har du pulvret?}
{112}{}{Ja, här är det.}
{113}{}{Hmm. Jag antar inte det.}
{114}{}{Här är flintan. Iväg med dig nu! Jag har inte tid att skvallra.}
{115}{}{Tack, moster Morlis.}
{116}{}{Återigen slösar du bort min tid, värdelöse brorson! Hur blev du någonsin
 den Utvalde?}
{117}{}{Ja, moster Morlis.}
{118}{}{Eh, moster Morlis, jag har tre här.}
{150}{}{Moster Morlis, jag är på en farlig resa för att rädda vår by.
 Mina chanser att lyckas ökar om jag behåller läkepulvret
 för mig själv och du ger mig flintan. Håller du inte med?}
{151}{}{Vad tror du att du gör, unge? Detta är inget sätt för den Utvalde att agera. Försvinn ur min åsyn nu!}
{152}{}{Om den här flintan är så viktig att du är beredd att vanära den Utvaldes namn, så ta den. Ta
 flintan och försvinn ur min åsyn.}
{153}{}{Ja, moster Morlis.}
{154}{}{Jaha... Åh, mycket bra. Här är flintan. Jag önskar dig en säker resa, mitt barn.}
{155}{}{No, I don't. Now stop wasting my time and get out of here!}
{156}{}{Ja, moster Morlis.}
{200}{}{So you've returned. Did you find the holy Thirteen?}
{201}{}{No, Aunt Morlis, I...}
{202}{}{Then get yourself out of here and find it! People are depending on you!}
{203}{}{Ja, moster Morlis.}
{204}{}{Well, here you are again. Have you once again failed to complete your quest?}
{205}{}{Yes, Aunt Morlis, but...}
{206}{}{Then get yourself out of here and don't come back until you do! Why waste time coming back here, when you could be using that time to continue your search!?}
{207}{}{Ja, moster Morlis.}
{208}{}{The fact that you are standing here must mean that you have completed your quest. You wouldn't waste precious time returning here empty-handed, would you?}
{209}{}{Yes, Aunt Morlis. I mean no, Aunt Morlis. Uh, I've got to go, Aunt Morlis.}
{210}{}{So, child. Once again you stand before me. Are you empty-handed yet again?}
{211}{}{Ja, moster Morlis.}
{212}{}{Lyssna,}
{213}{}{. People are dying, cattle are dying, and crops are failing. Everyone is either hungry, sick, or both. Our time draws near. If you do not find the GECK soon, we are doomed. Do you understand me?}
{214}{}{Ja, moster Morlis.}
{215}{}{Then get yourself out of here and find the GECK! People are depending on you!}
{216}{}{Ja, moster Morlis.}
{300}{}{Well, I seem to have misplaced the flint. Oh well, at least I got my powders. Now off with you! I don't have time to gossip.}
{301}{}{Why do you bother me, niece? Can't you see I'm busy?}
{302}{}{Well, I can't seem to find the flint. I'm sure you took it from me when I wasn't looking though. I caught you before. Now off with you! I don't have time to gossip.}
{303}{}{Well... Oh, I'm sorry but I seem to have misplaced the flint. I wish you a safe journey though, child. }
{304}{}{I already gave you the flint, stupid. Now stop wasting my time and get out of here!}
{305}{}{I already gave you the flint, stupid. Oh well, at least I got my powders. Now off with you! I don't have time to gossip.}
