{100}{}{Du ser brovakten.}
{101}{}{Du ser Mynoc, brovakten.}
{150}{}{Framför dig står en stor krigare från din by,
 med ett spjut i handen.}
{151}{}{[TALA]}
{152}{}{Hej, Utvalde. På väg för att hitta GECK?}
{153}{}{Ja.}
{154}{}{Ja. Men innan jag går skulle jag vilja ställa
 några frågor till dig.}
{155}{}{Inte riktigt än. Jag ska se mig omkring
 lite mer.}
{156}{}{Må gudarna vaka över dig.}
{157}{}{Tack, hej då.}
{158}{}{Vad vill du veta?}
{159}{}{Vad kan du berätta om männen som handlar med våra
 by?}
{160}{}{Vad kan du berätta om det här föremålet jag har från
 ett valv?}
{161}{}{Inget, glöm det.}
{162}{}{Very well, but don't waste too much time. Without the GECK,
 we're doomed.}
{163}{}{Jag vet, oroa dig inte -- Jag har allt under kontroll.}
{164}{}{Varför?}
{165}{}{Jag måste gå nu. Hej då.}
{166}{}{Handlarna? De kommer från Klamath ungefär varannan månad. De
 kommer inte förrän om en månad eller mer, men Klamath ligger bara några dagar
 österut härifrån.}
{167}{}{Tack. Hej då.}
{168}{}{Vad kan du berätta om det här föremålet jag har från
 det heliga valvet?}
{169}{}{Ser ut som en vattenkalebass gjord av metall. Kanske
 valvet skickade den till oss som ett omen.}
{170}{}{Kan du berätta vem som tog med sig det här föremålet till vår by?}
{171}{}{Tack så mycket. Jag måste gå nu. Adjö.}
{172}{}{Jag hoppas att du gör det.}
{173}{}{Ditt överdrivna självförtroende får oss alla att lida! Adjö!}
{174}{}{Farväl.}
{175}{}{Why? Look around you -- our village dies. The gardens wither and
 every day children and old ones collapse. You must bring Eden to us before
 it is too late!}
{176}{}{And I will take care of it. Goodbye.}
{177}{}{I am the Chosen One -- I "must" do only as I
 please. Goodbye.}
{178}{}{I don't remember his name, just that he was old and loud -- too
 loud for proper manners -- but he knew many things. He was from Klamath, east
 like I said.}
{179}{}{Tack, hej då.}
{180}{}{Are you still here? You must go find the GECK. Staying here
 doesn't help us.}
{181}{}{This bridge is all you need to worry about,
 friend. I can take care of myself.}
{182}{}{I was just heading out. Goodbye, my friend.}
{183}{}{I will speak to you no longer, insubordinate pig!}
{184}{}{I would like to ask you another question.}
{185}{}{That was quick! Have you found the holy Vault 13?}
{186}{}{Ja.}
{187}{}{No, not yet.}
{188}{}{You have? Wonderful! Did you bring back the
 GECK?}
{189}{}{Nej.}
{190}{}{No. I haven't spoken to the people of the vault yet.}
{191}{}{I don't believe that's any business of yours, my friend.}
{192}{}{No? Chosen One, three old ones have died since you left. You must
 not waste any more time.}
{193}{}{I'll find it, don't worry.}
{194}{}{I'm getting sick of your constant nagging.}
{195}{}{Well, why are you talking to me? Talk to them, and get the GECK.}
{196}{}{I will -- all in good time, my friend.}
{197}{}{I'm getting sick of your constant nagging.}
{198}{}{What news of the GECK, Chosen One?}
{199}{}{I have found the vault!}
{200}{}{I have not been able to find Vault 13.}
{201}{}{Well, look, it's the Chosen One.}
{202}{}{Hej.}
{203}{}{Shut up.}
{204}{}{Can I ask you a question?}
{205}{}{No, I've no time for you.}
{206}{}{Whatever. Good bye.}
{207}{}{Oh well. See you around.}
{208}{}{Go die.}
{209}{}{Greetings, dull one! See bridge? You cross, you be careful.
 Bridge dangerous. You not want to fall. Okay?}
{210}{}{Umm... Hunh?}
{211}{}{Wretch! You have failed the village!}
{212}{}{You betray us. For that you'll die!}
{213}{}{You are a traitor to your own people.}
{214}{}{Why do you do this?}
{215}{}{The Elder was wrong. You are evil.}
{300}{}{My father taught me how to make stronger blades than most. Get me a piece
 of flint and I'll fix your spear, too. You'll need it in the wilderness.}
{301}{}{Where would I get some of this flint?}
{302}{}{They say your Aunt Morlis has been hoarding a piece. She's so
 ill-tempered I don't think anyone's asked her. Of course, the witch will want
 something in return.}
{303}{}{Thanks. Goodbye.}
{304}{}{Did you talk your aunt out of her flint?}
{305}{}{Yes, I have some right here.}
{306}{}{Not yet.}
{307}{}{It's a good piece. Give me your spear.}
{308}{}{Varsågod.}
{309}{}{I guess I don't have one.}
{310}{}{Now, you put the pieces like so...}
{311}{}{The Chosen One without a spear? Well, you'll have to take one of
 mine. Now, let's get to work...}
{312}{}{Here is your new spear.}
{313}{}{Thank you, my friend -- this will help a lot.}
{314}{}{Yes, but I was wondering about your spear. It looks a little
 different.}
{400}{}{Welcome home, Chosen One! Did you find the vault? Have you returned with the GECK?}
{401}{}{Me not find yet.}
{402}{}{No, I haven't found it yet.}
{403}{}{I'm not in the mood for your questions. Goodbye.}
{404}{}{Things are not going well, Chosen One. The drought is getting worse and our crops are
 sure to fail. We are trying to salvage what we can to build up our food reserves.}
{405}{}{Why no trade with other villages?}
{406}{}{Me doing best me can. Me find GECK. Me return.}
{407}{}{Why can't we trade with other villages for the food we need? }
{408}{}{I'm doing my best. When I find the GECK I'll return with it.}
{409}{}{We are a simple people and have little to offer in trade. The few towns that we have
 contacted while you were away have shown no interest in helping us.}
{410}{}{Me see.}
{411}{}{I see.}
{412}{}{You are our only hope, Chosen One. Please do not fail us!}
{413}{}{It is good to see you, Chosen One. How fares your quest?}
{414}{}{Me still look.}
{415}{}{I'm still looking.}
{416}{}{I don't want to talk about it.}
{417}{}{You must hurry. Things are getting worse here at home. Soon there will be little food and
 the Elder speaks of rationing what we have. I fear for the future of Arroyo.}
{418}{}{Chosen One! Please tell me that you have completed your quest. Our village is dying, and so
 are our people. }
{419}{}{No, me still look.}
{420}{}{No, I'm still looking.}
{421}{}{How are things?}
{422}{}{I am sorry, Chosen One, but I am beginning to question my faith in you. The very lives of
 our people are in your hands. Please find the holy Thirteen and return to us with the GECK!}
{423}{}{Our crops fail, the brahmin die, everyone goes hungry now. The cries of the children at night
 allow no one any sleep. We are becoming a desperate people.}
{424}{}{Me continue look.}
{425}{}{I'll do what I can.}
{426}{}{Once again you return to us, Chosen One. Not empty-handed, I hope?}
{427}{}{Me sorry, no find GECK yet.}
{428}{}{I'm sorry, I still haven't found the GECK.}
{429}{}{I've had enough of this.}
{430}{}{People are dying here while you stroll about the lands. Perhaps you should be searching
 elsewhere instead of returning here.}
{500}{}{Have you talked to the Elder yet?}
{1000}{}{Äldste}
{1001}{}{Grundare}
{1002}{}{Valvinvånare}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Valv}
{1006}{}{Den Utvalde}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Helande pulver}
{1010}{}{Bro}
{1011}{}{Mynoc}
{1100}{}{Den Äldste är din mamma och vår ledare.}
{1101}{}{Vår store förfader som gav oss kunskap.}
{1102}{}{Den förste att kämpa och vinna över kaos.}
{1103}{}{Det skulle vara vår vackra by.}
{1104}{}{Det är en handelsutpost några dagar österut.}
{1105}{}{Valvet är himmelriket.}
{1106}{}{Du är den Utvalde.}
{1107}{}{Han läker oss med sina örter och sin magi. Han är i den
 norra delen av vår by.}
{1108}{}{Han läker oss med sina örter och sin magi. Han är i den
 norra delen av vår by.}
{1109}{}{Det är ett magiskt pulver som kommer att läka dig, men kommer
 gör dig sömnig.}
{1110}{}{Den stora bron leder ut ur vår by i söder.}
{1111}{}{Det skulle vara jag.}
