{100}{}{Du ser brovakten.}
{101}{}{Du ser Mynoc, brovakten.}
{150}{}{Framför dig står en stor krigare från din by,
 med ett spjut i handen.}
{151}{}{[TALA]}
{152}{}{Hej, Utvalde. På väg för att hitta GECK?}
{153}{}{Ja.}
{154}{}{Ja. Men innan jag går skulle jag vilja ställa
 några frågor till dig.}
{155}{}{Inte riktigt än. Jag ska se mig omkring
 lite mer.}
{156}{}{Må gudarna vaka över dig.}
{157}{}{Tack, hej då.}
{158}{}{Vad vill du veta?}
{159}{}{Vad kan du berätta om männen som handlar med våra
 by?}
{160}{}{Vad kan du berätta om det här föremålet jag har från
 ett valv?}
{161}{}{Inget, glöm det.}
{162}{}{Nå väl, men slösa inte för mycket tid. Utan GECK,
 är vi dödsdömda.}
{163}{}{Jag vet, oroa dig inte -- Jag har allt under kontroll.}
{164}{}{Varför?}
{165}{}{Jag måste gå nu. Hej då.}
{166}{}{Handlarna? De kommer från Klamath ungefär varannan månad. De
 kommer inte förrän om en månad eller mer, men Klamath ligger bara några dagar
 österut härifrån.}
{167}{}{Tack. Hej då.}
{168}{}{Vad kan du berätta om det här föremålet jag har från
 det heliga valvet?}
{169}{}{Ser ut som en vattenkalebass gjord av metall. Kanske
 valvet skickade den till oss som ett omen.}
{170}{}{Kan du berätta vem som tog med sig det här föremålet till vår by?}
{171}{}{Tack så mycket. Jag måste gå nu. Adjö.}
{172}{}{Jag hoppas att du gör det.}
{173}{}{Ditt överdrivna självförtroende får oss alla att lida! Adjö!}
{174}{}{Farväl.}
{175}{}{Why? Look around you -- our village dies. The gardens wither and
 every day children and old ones collapse. You must bring Eden to us before
 it is too late!}
{176}{}{Och jag ska ta hand om det. Adjö.}
{177}{}{Jag är den Utvalde - jag "måste " bara göra som jag
 behagar. Adjö.}
{178}{}{Jag minns inte hans namn, bara att han var gammal och högljudd - för
 högljudd för att uppföra sig ordentligt - men han visste många saker. Han var från Klamath, österut
 som jag sa.}
{179}{}{Tack, hej då.}
{180}{}{Är du kvar här? Du måste gå och hitta GECK. Att stanna här
 hjälper oss inte.}
{181}{}{Den här bron är allt du behöver bry dig om,
 min vän. Jag kan ta hand om mig själv.}
{182}{}{Jag var på väg ut. Adjö, min vän.}
{183}{}{Jag tänker inte tala med dig längre, ditt olydiga svin!}
{184}{}{Jag skulle vilja fråga dig något annat.}
{185}{}{Det var snabbt! Har du hittat det heliga Valv 13?}
{186}{}{Ja.}
{187}{}{Nej, inte än.}
{188}{}{Har du? Underbart! Tog du med dig GECK:en
 tillbaka?}
{189}{}{Nej.}
{190}{}{Nej, jag har inte pratat med folket i valvet än.}
{191}{}{Jag tror inte att du har med det att göra, min vän.}
{192}{}{Inte? Utvalde, tre gamla har dött sedan du lämnade oss. Du får
 inte slösa mer tid.}
{193}{}{Jag ska hitta den, oroa er inte.}
{194}{}{Jag börjar bli trött på ditt ständiga tjat.}
{195}{}{Varför pratar du med mig? Prata med dem, och hämta GECK:en.}
{196}{}{Det ska jag göra -- allt i sinom tid, min vän.}
{197}{}{Jag börjar bli trött på ditt ständiga tjat.}
{198}{}{Vad nytt om GECK:en, Utvalde?}
{199}{}{Jag har hittat valvet!}
{200}{}{Jag har inte lyckats hitta Valv 13.}
{201}{}{Ser man på, det är ju Den Utvalde.}
{202}{}{Hej.}
{203}{}{Håll tyst.}
{204}{}{Får jag ställa en fråga?}
{205}{}{Nej, jag har inte tid med dig.}
{206}{}{Visst. Adjö.}
{207}{}{Nåväl. Vi ses.}
{208}{}{Gå och dö.}
{209}{}{Var hälsad, ers tröghet! Se bro? Du korsa, du var försiktig.
 Bro farlig. Du inte vill falla. Okej?}
{210}{}{Ehh... Hunh?}
{211}{}{Din usling! Du har svikit byn!}
{212}{}{Du förråder oss. För det kommer du att dö!}
{213}{}{Du är en förrädare mot ditt eget folk.}
{214}{}{Varför gör du så här?}
{215}{}{Den Äldste hade fel. Du är ond.}
{300}{}{Min far lärde mig att göra starkare blad än de flesta. Ge mig en bit
 flinta så lagar jag ditt spjut också. Du kommer att behöva det i vildmarken.}
{301}{}{Var skulle jag få tag på den här flintstenen?}
{302}{}{They say your Aunt Morlis has been hoarding a piece. She's so
 ill-tempered I don't think anyone's asked her. Of course, the witch will want
 something in return.}
{303}{}{Tack. Hej då.}
{304}{}{Did you talk your aunt out of her flint?}
{305}{}{Ja, jag har lite här.}
{306}{}{Inte än.}
{307}{}{Det är en bra bit. Ge mig ditt spjut.}
{308}{}{Varsågod.}
{309}{}{Jag antar att jag inte har någon.}
{310}{}{Nu sätter du ihop delarna så här...}
{311}{}{Den Utvalde utan spjut? Tja, du får ta ett av
 mina. Låt oss nu sätta igång...}
{312}{}{Här är ditt nya spjut.}
{313}{}{Tack, min vän -- det här kommer att hjälpa mycket.}
{314}{}{Ja, men jag undrade över ditt spjut. Det ser lite
 annorlunda ut.}
{400}{}{Välkommen hem, Utvalde! Hittade du valvet? Har du återvänt med GECK?}
{401}{}{Jag inte hitta än.}
{402}{}{Nej, jag har inte hittat det än.}
{403}{}{Jag är inte på humör för dina frågor. Adjö.}
{404}{}{Det går inte så bra, Utvalde. Torkan blir värre och våra grödor kommer
 säkert på att vissna. Vi försöker rädda vad vi kan för att bygga upp våra matreserver.}
{405}{}{Varför inte byta andra byar?}
{406}{}{Jag göra gott jag kan. Jag hitta GECK. Jag återvända.}
{407}{}{Varför kan vi inte handla med andra byar för att få den mat vi behöver? }
{408}{}{Jag gör mitt bästa. När jag hittar GECK kommer jag tillbaka med det.}
{409}{}{Vi är ett enkelt folk och har inte mycket att erbjuda i handeln. De få städer som vi har
 kontaktat medan du var borta har inte visat något intresse för att hjälpa oss.}
{410}{}{Jag fatta.}
{411}{}{Jag förstår.}
{412}{}{Du är vårt enda hopp, Utvalde. Snälla, svik oss inte!}
{413}{}{Det är trevligt att se dig, Utvalde. Hur går det med ditt uppdrag?}
{414}{}{Jag fortfarande leta.}
{415}{}{Jag letar fortfarande.}
{416}{}{Jag vill inte prata om det.}
{417}{}{Du måste skynda. Saker och ting blir värre här hemma. Snart kommer det att finnas lite mat och
 den Äldste talar om att ransonera det vi har. Jag fruktar för Arroyos framtid.}
{418}{}{Utvalde! Snälla, säg att du har slutfört ditt uppdrag. Vår by håller på att dö, och så
 gör vårt folk.}
{419}{}{Nej, jag fortfarande leta.}
{420}{}{Nej, jag letar fortfarande.}
{421}{}{Hur är det?}
{422}{}{Jag är ledsen, Utvalde, men jag börjar tvivla på mitt förtroende för dig. Självaste livet för
 vårt folk ligger i dina händer. Snälla, hitta det heliga Tretton och återvänd till oss med GECK!}
{423}{}{Our crops fail, the brahmin die, everyone goes hungry now. The cries of the children at night
 allow no one any sleep. We are becoming a desperate people.}
{424}{}{Me continue look.}
{425}{}{I'll do what I can.}
{426}{}{Once again you return to us, Chosen One. Not empty-handed, I hope?}
{427}{}{Me sorry, no find GECK yet.}
{428}{}{I'm sorry, I still haven't found the GECK.}
{429}{}{I've had enough of this.}
{430}{}{People are dying here while you stroll about the lands. Perhaps you should be searching
 elsewhere instead of returning here.}
{500}{}{Have you talked to the Elder yet?}
{1000}{}{Äldste}
{1001}{}{Grundare}
{1002}{}{Valvinvånare}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Valv}
{1006}{}{Den Utvalde}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Helande pulver}
{1010}{}{Bro}
{1011}{}{Mynoc}
{1100}{}{Den Äldste är din mamma och vår ledare.}
{1101}{}{Vår store förfader som gav oss kunskap.}
{1102}{}{Den förste att kämpa och vinna över kaos.}
{1103}{}{Det skulle vara vår vackra by.}
{1104}{}{Det är en handelsutpost några dagar österut.}
{1105}{}{Valvet är himmelriket.}
{1106}{}{Du är den Utvalde.}
{1107}{}{Han läker oss med sina örter och sin magi. Han är i den
 norra delen av vår by.}
{1108}{}{Han läker oss med sina örter och sin magi. Han är i den
 norra delen av vår by.}
{1109}{}{Det är ett magiskt pulver som kommer att läka dig, men kommer
 gör dig sömnig.}
{1110}{}{Den stora bron leder ut ur vår by i söder.}
{1111}{}{Det skulle vara jag.}
