{100}{}{Du ser din unga kusin, Nagor. Du ser inte hans hund, Smoke, någonstans.}
{101}{}{Du har känt Nagor sedan han var ett spädbarn och har alltid hjälpt honom när du har kunnat.}
{102}{}{Kusin, vad jag är glad att se dig! Jag behöver din hjälp.}
{103}{}{Ledsen, men jag har inte tid.}
{104}{}{Vad behöver du hjälp med?}
{105}{}{Då ger jag mig ut i vildmarken själv!}
{106}{}{Vänta lite... vad var det du behövde hjälp med?}
{107}{}{Gör det du.}
{108}{}{Smoke sprang iväg till jaktmarkerna och har inte kommit tillbaka och nu vägrar Morlis
 låta mig leta efter honom. Hon säger att det är för farligt och att han bara är en hund, men jag tänkte
 göra det i alla fall. Men nu är du här och du kan göra det och jag skulle inte hamna i
 trubbel.}
{109}{}{Visst. Men var är jaktmarkerna?}
{110}{}{Visst. Jag ska leta efter honom nu.}
{111}{}{Glöm det, jag har inte tid med det här.}
{112}{}{What'd you do, get hit in the head with a rock? They're on the far side of
 Hakunin's tent, north of the village.}
{113}{}{Jag kommer snart tillbaka med honom.}
{114}{}{Har du hittat Smoke än?}
{115}{}{Nej, inte än. Var sa du att jaktmarkerna fanns?}
{116}{}{No, not yet.}
{117}{}{Har du hittat Smoke än?}
{118}{}{Nej, inte än. Men jag kommer tillbaka snart.}
{119}{}{Jag är ledsen, men han är död.}
{120}{}{Det säger du bara för att du inte vill leta! Jag bryr mig inte om vad
 Morlis säger, jag ska hitta honom.}
{121}{}{Nagor, tänk om något händer dig? Morlis skulle vara ensam och det skulle
 göra henne riktigt ledsen. Du vill väl inte göra henne ledsen, eller hur?}
{122}{}{Gör det du.}
{123}{}{Nej, det vill jag inte göra. Okej, jag kommer inte att gå, men det är inte rättvist!}
{124}{}{Smoke kommer att klara sig. Hej då.}
{125}{}{Du hittade Smoke! Tack! Smoke, du är en stygg hund!}
{126}{}{Varsågod. Hej då.}
{127}{}{Tack åter igen. Jag hoppas att du får en riktigt rolig resa!}
{128}{}{Jag saknar Smoke. Varför kunde du inte rädda honom? Du är den Utvalde.}
{129}{}{Jag är upptagen, dumskalle. Gå och lek någon annanstans.}
{130}{}{Jag går.}
{131}{}{Jag letar efter Smoke.}
{200}{}{Hej kusin... eh, jag menar Utvalde. Jag hoppas att du har hittat GECK. Jag 'har hört en hel del
 prat om kommande svåra tider.}
{201}{}{Hej kusin... eh, jag menar Utvalde. Jag hoppas att du har hittat GECK. Jag 'har hört en hel del
 prat om kommande svåra tider.}
{202}{}{Jag fortfarande titta, Nagor.}
{203}{}{I'm still looking, cousin.}
{204}{}{Welcome home, cousin. Things are getting a little tight around here. Have you found the holy
 Thirteen and the GECK?}
{205}{}{Welcome home, cousin. Things are getting a little tight around here. Have you found the holy
 Thirteen and the GECK?}
{206}{}{Me not find. Sorry.}
{207}{}{I'm sorry, Nagor. I'm still looking.}
{208}{}{Hello again, cousin. I guess you've noticed that things are really falling apart here. Please
 find the GECK. We are in desperate need!}
{209}{}{Hello again, cousin. I guess you've noticed that things are really falling apart here. Please
 find the GECK. We are in desperate need!}
{210}{}{Hi, cousin.}
{211}{}{Hi, cousin.}
{212}{}{You not sound like usual self.}
{213}{}{You don't sound like your usual self.}
{214}{}{I'm sorry, cousin. Things have been getting worse and worse since you last left. People are
 sick, the brahmin are dying and... I... my dog Smoke died - Morlis cooked him. I miss him so much. Sorry, but I can't
 really talk any more...}
{215}{}{I'm sorry, cousin. Things have been getting worse and worse since you last left. People are sick,
 the brahmin are dying and... I... my dog Smoke died. I miss him so much. Sorry, but I can't really
 talk any more...}
{300}{}{Du ser Nagor.}
{302}{}{Kusin, vad jag är glad att se dig! Jag behöver din hjälp.}
