{100}{}{Du ser din unga kusin, Nagor. Du ser inte hans hund, Smoke, någonstans.}
{101}{}{Du har känt Nagor sedan han var ett spädbarn och har alltid hjälpt honom när du har kunnat.}
{102}{}{Kusin, vad jag är glad att se dig! Jag behöver din hjälp.}
{103}{}{Ledsen, men jag har inte tid.}
{104}{}{Vad behöver du hjälp med?}
{105}{}{Då ger jag mig ut i vildmarken själv!}
{106}{}{Vänta lite... vad var det du behövde hjälp med?}
{107}{}{Gör det du.}
{108}{}{Smoke sprang iväg till jaktmarkerna och har inte kommit tillbaka och nu vägrar Morlis
 låta mig leta efter honom. Hon säger att det är för farligt och att han bara är en hund, men jag tänkte
 göra det i alla fall. Men nu är du här och du kan göra det och jag skulle inte hamna i
 trubbel.}
{109}{}{Visst. Men var är jaktmarkerna?}
{110}{}{Visst. Jag ska leta efter honom nu.}
{111}{}{Glöm det, jag har inte tid med det här.}
{112}{}{What'd you do, get hit in the head with a rock? They're on the far side of
 Hakunin's tent, north of the village.}
{113}{}{Jag kommer snart tillbaka med honom.}
{114}{}{Har du hittat Smoke än?}
{115}{}{Nej, inte än. Var sa du att jaktmarkerna fanns?}
{116}{}{No, not yet.}
{117}{}{Har du hittat Smoke än?}
{118}{}{Nej, inte än. Men jag kommer tillbaka snart.}
{119}{}{Jag är ledsen, men han är död.}
{120}{}{Det säger du bara för att du inte vill leta! Jag bryr mig inte om vad
 Morlis säger, jag ska hitta honom.}
{121}{}{Nagor, tänk om något händer dig? Morlis skulle vara ensam och det skulle
 göra henne riktigt ledsen. Du vill väl inte göra henne ledsen, eller hur?}
{122}{}{Gör det du.}
{123}{}{Nej, det vill jag inte göra. Okej, jag kommer inte att gå, men det är inte rättvist!}
{124}{}{Smoke kommer att klara sig. Hej då.}
{125}{}{Du hittade Smoke! Tack! Smoke, du är en stygg hund!}
{126}{}{Varsågod. Hej då.}
{127}{}{Tack åter igen. Jag hoppas att du får en riktigt rolig resa!}
{128}{}{Jag saknar Smoke. Varför kunde du inte rädda honom? Du är den Utvalde.}
{129}{}{Jag är upptagen, dumskalle. Gå och lek någon annanstans.}
{130}{}{Jag går.}
{131}{}{Jag letar efter Smoke.}
{200}{}{Hej kusin... eh, jag menar Utvalde. Jag hoppas att du har hittat GECK. Jag 'har hört en hel del
 prat om kommande svåra tider.}
{201}{}{Hej kusin... eh, jag menar Utvalde. Jag hoppas att du har hittat GECK. Jag 'har hört en hel del
 prat om kommande svåra tider.}
{202}{}{Jag fortfarande letar, Nagor.}
{203}{}{Jag letar fortfarande, kusin.}
{204}{}{Välkommen hem, kusin. Det börjar bli lite tufft här. Har du hittat den heliga
 Tretton och GECK?}
{205}{}{Välkommen hem, kusin. Det börjar bli lite tufft här. Har du hittat den heliga
 Tretton och GECK?}
{206}{}{Jag inte hitta. Ledsen.}
{207}{}{Jag är ledsen, Nagor. Jag letar fortfarande.}
{208}{}{Hej igen, kusin. Jag antar att du har märkt att saker och ting verkligen faller samman här. Snälla
 hitta GECK. Vi är i desperat behov!}
{209}{}{Hej igen, kusin. Jag antar att du har märkt att saker och ting verkligen faller samman här. Snälla
 hitta GECK. Vi är i desperat behov!}
{210}{}{Hej, kusin.}
{211}{}{Hej, kusin.}
{212}{}{Du inte låta som vanligt.}
{213}{}{Du låter inte som ditt vanliga jag.}
{214}{}{Jag är ledsen, kusin. Saker och ting har blivit värre och värre sedan du senast var här. Folk är
 sjuka, brahminerna är döende och... jag... min hund Smoke dog - Morlis lagade mat av honom. Jag saknar honom så mycket. Ledsen, men jag kan inte
 riktigt prata längre...}
{215}{}{Jag är ledsen, kusin. Saker och ting har blivit värre och värre sedan du senast var här. Folk är sjuka,
 brahminerna är döende och... jag... min hund Smoke dog. Jag saknar honom så mycket. Ledsen, men jag kan inte
 riktigt prata längre...}
{300}{}{Du ser Nagor.}
{302}{}{Kusin, vad jag är glad att se dig! Jag behöver din hjälp.}
