{100}{}{Du ser en växt med en mörk själ.}
{101}{}{Dessa växter är inte bara skadliga för trädgården. De har också förmågan att attackera människor
 och andra varelser.}
{102}{}{Dessa växter med en mörk själ är en udda mutation. Det är tveksamt att de muterade på detta sätt som
 ett resultat av naturliga orsaker.}
{103}{}{Du märker inget ovanligt med dessa växter - annat än att de angriper människor.}
{150}{}{Du har befriat trädgården från alla växter med mörka själar.}
