{100}{}{Du ser Cameron, en stamfrände.}
{101}{}{Du ser Cameron.}
{102}{}{Du ser en ung man med stora muskler och en mycket självsäker utstrålning.}
{103}{}{Hälsningar,}
{104}{}{. Jag har äran att vara din sista utmaning. För att fortsätta i din strävan måste du besegra
 mig i obeväpnad strid. Ska vi börja?}
{105}{}{Ja ha frågor.}
{106}{}{Okej, vi slåss.}
{107}{}{Nej, jag göra i ordning först.}
{108}{}{Jag har några frågor till dig först.}
{109}{}{Visst, nu kör vi.}
{110}{}{Jag tror att jag behöver en stund för att förbereda mig för det här.}
{111}{}{Vad skulle du vilja veta? }
{112}{}{Varför vi slåss?}
{113}{}{Vi slåss till döds?}
{114}{}{Vi slåss obeväpnade?}
{115}{}{Okej, vi slåss nu.}
{116}{}{Jag måste göra redo.}
{117}{}{Varför måste vi slåss?}
{118}{}{Är det här en kamp på liv och död?}
{119}{}{Säger du att vi ska strida obeväpnade?}
{120}{}{Dags att få den här striden överstökad.}
{121}{}{Jag behöver en stund för att förbereda mig för striden.}
{122}{}{Den Utvaldes väg är inte en lätt stig att följa, }
{123}{}{. Du kommer att ställas inför många utmaningar under din livstid, och den svåraste
 av dessa kommer att vara att handskas med dina medmänniskor. Det kommer att komma en tid då diplomati och takt
 visar sig vara värdelösa och din hand måste höjas istället. Denna utmaning förbereder dig för att möta
 en annan människa, se honom i ögonen och veta att du kanske måste döda honom.}
{124}{}{Okej.}
{125}{}{Jag förstår.}
{126}{}{Nej, min vän, du behöver bara besegra mig. När tiden är inne kommer vi att avsluta striden.}
{127}{}{Ja' förstå.}
{128}{}{Okej.}
{129}{}{Ja. Vapen tenderar att distansera oss från striden och göra oss okänsliga för effekterna av våra handlingar
 mot andra. När du slår en annan människa med din bara näve, både ser och känner du den
 smärta du orsakar. Striden blir då mycket personlig och alltför verklig. Detta är en viktig läxa för
 dig, }
{130}{}{.}
{131}{}{Ja' fatta.}
{132}{}{Jag förstår.}
{133}{}{Mycket bra. Ska vi börja?}
{134}{}{Jag redo.}
{135}{}{Nej, jag göra i ordning först.}
{136}{}{Jag är redo.}
{137}{}{Nej, jag behöver lite tid för att förbereda mig.}
{138}{}{Okej, då. Återvänd och säg till när du är redo för din utmaning.}
{139}{}{Är du redo för din utmaning,}
{140}{}{?}
{141}{}{Jag redo. }
{142}{}{Jag inte redo än.}
{143}{}{Jag tror det.}
{144}{}{Nej, vänta en stund.}
{145}{}{Utmärkt! Din utrustning kommer att förvaras i kofferten utanför rummet.
 Du kan hämta den efter striden. Låt striden börja! Lycka till }
{146}{}{.}
{147}{}{Det är trevligt att se dig igen, Utvalde. Hur kan jag hjälpa dig?}
{148}{}{Jag vill templet igen.}
{149}{}{Vill slåss igen?}
{150}{}{Bara säga hej. Jag gå nu.}
{151}{}{Jag skulle vilja besöka templet igen.}
{152}{}{Hej, Cameron. Redo för ännu en strid?}
{153}{}{Jag tänkte bara säga hej. Vi ses senare.}
{154}{}{Ta stigen till vänster om mig, Utvalde. Den leder till det egentliga templet.
 Grottingången bakom mig leder dig till den sista kammaren.}
{155}{}{Okej, ja' gå.}
{156}{}{Okej, då. Tack.}
{157}{}{Nej, tack ska du ha, Utvalde. Jag bär fortfarande på blåmärkena från vårt senaste möte och kommer att behöva
 år för att återhämta mig!}
{158}{}{Hej då, Cameron.}
{159}{}{Ha! Ha en god dag, Cameron.}
{160}{}{Den Utvalde, i helvete heller. Jag ska göra dig till den döde!}
{161}{}{Du har besegrat mig. Du är värdig, Utvalde.}
{165}{}{Jag håller inte med dig. Jag tror att det är möjligt att hitta en fredlig lösning på alla problem.}
{166}{}{Du kan ha rätt, }
{167}{}{men inte i vår nuvarande situation. Du måste besegra mig för att lyckas med din utmaning.}
{168}{}{Jag känner inte till alla dina styrkor och svagheter, och du känner inte till mina.
 Olyckor händer, så vad händer om en av oss oavsiktligt dödar den andra? Låt'oss bara
 avsluta det här nu istället för att ta den chansen, okej?}
{169}{}{Hmm... Jag förstår vad du menar. Jag skulle inte vilja vara ansvarig för att
 döda dig när allt jag ville göra var att testa din förmåga. Mycket bra -- du kan
 passera, Utvalde.}
{170}{}{Hmm... Jag förstår din poäng. Men vi måste fortfarande strida. Jag kommer
 helt enkelt se till att inte skada dig för mycket.}
{171}{}{Tack! Vi ses igen i byn.}
{172}{}{Jag förstår.}
{200}{}{Jag minns inte vår senaste strid, Utvalde. Jag kommer alltid att undra hur du lyckades
 att ta dig förbi mig.}
{201}{}{Du har en tunga av renaste silver, den Utvalde. Din skicklighet med ord kommer att öppna många dörrar
 för dig.}
{300}{}{Och till dig också, Utvalde. Må andarna vägleda dig i ditt sökande.}
{301}{}{Tack, Cameron.}
{302}{}{Utvalde, jag kunde inte undgå att märka att du saknar starka stridskunskaper. Det har varit min erfarenhet att man inte alltid kan förlita sig på sitt förstånd eller sina ord för skydd. Med din tillåtelse ska jag lära dig några saker som jag tror att du kommer att finna väldigt användbara.}
{303}{}{Ja, du lära.}
{304}{}{Nej, jag inte behöva.}
{305}{}{Ja, var snäll och lär mig allt du kan.}
{306}{}{Tack, men jag tror att jag klarar mig bra själv.}
{307}{}{You learn well, Chosen One. I think you will be able to handle yourself in a fight now. However, remember that even the strongest of warriors must sometimes retreat. There is no shame in living to fight another day.}
{308}{}{Me thank you, Cameron.}
{309}{}{Thanks, Cameron. I will remember your words.}
{310}{}{Very well. Return to me if you change your mind.}
{311}{}{Me thank you, Cameron.}
{312}{}{Thanks, Cameron. I will remember your offer.}
