{100}{}{You see a male villager.}
{101}{}{You see a female villager.}
{150}{}{A kindly member of your village.}
{151}{}{[TALA]}
{152}{}{Hello! I hear you are the Chosen One. Now, perhaps, our village can be saved.}
{153}{}{Can you tell me where I can find more healing powder?}
{154}{}{What can you tell me of the traders who trade with us?}
{155}{}{It is good to see you, but I must be going.}
{156}{}{Gods protect you on your journey.}
{157}{}{I do have a question for you.}
{158}{}{Goodbye, my friend.}
{159}{}{Go see Hakunin in the northern corner of the village. He can help you.}
{160}{}{Tack. Hej då.}
{161}{}{Oh, it's not my place to deal with the traders. Talk to Mynoc, the guardian of the
 great bridge. He sees them all.}
{162}{}{Tack. Hej då.}
{163}{}{Could you tell me where the great bridge is located?}
{164}{}{One more question, if I may.}
{165}{}{Good joke, Chosen One! You know where it is. That way -- to the south.}
{166}{}{Tack. Hej då.}
{167}{}{One more question, if I may.}
{168}{}{Of course, what is it?}
{169}{}{Could you tell me where I can find some healing herbs?}
{170}{}{What can you tell me of the traders who trade with us?}
{171}{}{Never mind.}
{172}{}{Oh gods -- may the spirit of the Founder guide you. If you're the Chosen One, we're
 going to need it.}
{173}{}{Uun Ga.}
{174}{}{Have a safe journey.}
{175}{}{????}
{176}{}{We're doomed! You have failed your quest.}
{177}{}{You cannot continue like this.}
{180}{}{You are a traitor to your own people.}
{181}{}{Why do you do this?}
{182}{}{You are evil. The Chosen One is evil!}
{183}{}{They come to our village from the east, but their goods are poor.}
{184}{}{Could you tell me where I can find some healing herbs?}
{185}{}{Tack. Hej då.}
{186}{}{One more question, if I may.}
{300}{}{Hello, Chosen One. Nice to see you again. I pray that your holy quest is going well. Is there something I can help you with?}
{301}{}{Chosen One, our people are dying. You must hurry your search for the holy GECK. What may I do to aid you in this most holy of quests?}
{302}{}{We are running out of time, Chosen One. Please, finish your holy quest soon. We cannot afford to wait much longer. If there's anything I can do to help you to save us, let me know.}
{303}{}{Chosen One, our village is almost dead... you're our only hope. Is there anything
 I could tell you that would aide you in our salvation?}
{1000}{}{Äldste}
{1001}{}{Grundare}
{1002}{}{Valvinvånare}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Valv}
{1006}{}{Den Utvalde}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Helande pulver}
{1010}{}{Bro}
{1011}{}{Mynoc}
{1100}{}{Den Äldste är din mamma och vår ledare.}
{1101}{}{Vår store förfader som gav oss kunskap.}
{1102}{}{Den förste att kämpa och vinna över kaos.}
{1103}{}{Det skulle vara vår vackra by.}
{1104}{}{Det är en handelsutpost några dagar österut.}
{1105}{}{Valvet är himmelriket.}
{1106}{}{Du är den Utvalde.}
{1107}{}{He heals us with his herbs and magic. He is in the northern part
 of our village.}
{1108}{}{He heals us with his herbs and magic. He is in the northern part
 of our village.}
{1109}{}{It is a magic powder which will heal you, but will make you
 sleepy.}
{1110}{}{Den stora bron leder ut ur vår by i söder.}
{1111}{}{He guards the bridge leading into our village.}
