{100}{}{Du ser din bys Äldste.}
{101}{}{Det är den Äldste.}
{102}{}{Den Äldste är just det - gammal, äldre än du kan minnas. Ändå har hon
 styrkan och glöden som krävs för att leda byn genom dessa svåra tider.}
{103}{aeld1}{Gratulerar, Utvalde, du har överlevt Prövningarnas Tempel. Är
 du redo för ditt uppdrag?}
{104}{}{Vad höll du på med? Försökte du få mig dödad i templet?}
{105}{}{Självklart.}
{106}{}{Jag skulle vilja tänka på det lite mer.}
{107}{aeld2a}{I am proud of you, Chosen. You have overcome much. Now. You must go find Vault
 13. Vault 13. Bring the GECK home. GECK. Here is a shiny bottle. Vic gave us this. Vic.
 He is a trader in Klamath. Klamath. Go to Vic. Find Vault 13. Find GECK. Come home. Do
 your best, child.}
{112}{aeld2b}{You not find vault. Find vault! Vault 13.}
{113}{}{Eh.}
{114}{aeld3}{Chosen One, do you wish us all dead? You must find the Vault!}
{115}{}{I'm sorry, Elder. I will not fail.}
{116}{}{Yeah, yeah. Stop yelling.}
{117}{aeld4}{Chosen One, why are you here?}
{118}{}{I know where Vault 13 is!}
{119}{}{I am ready for the holy quest.}
{120}{}{I need some more info.}
{121}{}{I'm not going to get myself killed!}
{122}{}{What was I supposed to do again?}
{123}{}{I'm going now.}
{124}{aeld5}{That is good news, but not enough to save us. You must come back soon with the
 GECK or our people will die!}
{125}{}{I need some more info.}
{126}{}{Fine, I'm going now.}
{127}{aeld6}{You survived. The Chosen One cannot be weak or we are all doomed. Are you
 prepared for your quest?}
{128}{}{I've passed the test. Of course, I'm ready.}
{129}{}{I need to think about this.}
{130}{}{I'm not going to get myself killed!}
{131}{aeld7}{Lyssna noga. Hitta det heliga Valv 13 och ta tillbaka GECK. Vic, handlaren
 från Klamath, gav oss flaskan från det heliga Tretton. Börja din sökning hos honom.
 Disken kommer att påminna dig om din uppgift. Må Valvets gudar vaka över dig.}
{133}{}{Before I go, I have some questions.}
{134}{}{Goodbye. I will not fail the tribe.}
{135}{aeld8}{Very well. See me when you decide - but do not wait too long.}
{136}{}{Farväl.}
{137}{aeld9}{I cannot help much. So much has been lost from the Long Ago. What wisdom do you seek?}
{138}{aeld9b}{What do you need?}
{139}{}{Tell me more about the GECK.}
{140}{}{How do I get to Klamath?}
{141}{}{Where is Vault 13?}
{142}{}{On second thought, I don't need any help now. Goodbye.}
{143}{aeld10}{It is a holy artifact - the Garden of Eden Creation Kit. The disks promise it
 will make our lands green and our village prosperous. It will save us. More, I do not know.}
{144}{}{There's more I want to know.}
{145}{}{Farväl.}
{146}{aeld11}{Klamath is to the east.}
{147}{}{There are other things I would learn.}
{148}{}{I am ready. Goodbye.}
{149}{aeld12}{Det heliga Tretton? Jag kan inte hjälpa dig. Bara Valvinvånaren visste. Hans berättelser har
 toner av en farofylld resa.}
{150}{}{Jag förstår. Det är mycket jag behöver veta.}
{151}{}{Adjö, Äldste.}
{152}{aeld13}{Att vara en fegis kommer att döda oss alla! Inklusive dig. Du klarade
 tempelutmaningarna. Vi har förtroende för dig. Vi behöver dig.}
{153}{}{Inte så fort, gamla tant. Jag behöver tid att tänka på det här!}
{154}{}{Som du vill, Äldste.}
{155}{aeld14a}{Du har förrått oss. Du kommer att förgås.}
{156}{aeld14b}{Du är en förrädare!}
{157}{aeld14c}{Varför gör du så här?}
{158}{aeld14d}{Jag visste att du hade mörkrets själ!}
{159}{aeld15}{Ta då den här flaskan. Den är från det heliga Valv 13. Vic, en handlare i Klamath,
 tog den till oss. Han kanske vet var valvet är. Du kan också behöva lite av vad de
 kallar pengar. Här.}
{160}{}{Eh... Vad var mitt uppdrag nu igen?}
{161}{}{Finns det något mer du kan berätta för mig?}
{162}{}{Önska mig lycka till, Äldste, och jag ska inte svika dig.}
{163}{aeld16}{Hitta Vic i Klamath. Vi räknar med dig.}
{164}{aeld17}{Det är skönt att se dig igen, mitt barn. Jag menar inte att vara abrupt men jag ser att du
 inte har slutfört ditt uppdrag att hitta det heliga Tretton. Snälla, låt oss inte slösa tid
 med att prata. Vårt folks behov är stort. Gå och hitta Valvet!}
{165}{}{Jag gå nu.}
{166}{}{Okej, jag går nu.}
{167}{}{Jag kommer inte att svika dig, äldste.}
{168}{}{Jag jobbar på det, Ok?}
{169}{aeld18}{Ännu en gång återvänder du utan GECK. Våra grödor börjar svika oss, Utvalde. Vårt
 behov blir större med tidens gång. Gå och hitta det heliga Tretton!}
{170}{}{Okej, jag gå nu.}
{171}{}{Ja, Äldste.}
{172}{}{Jag kommer inte att svika dig eller vårt folk, Äldste.}
{173}{}{Hörru. Om du tror att du kan göra det bättre... }
{174}{aeld19}{Utvalde, saker och ting är inte bra här. Vi behöver GECK om vår by ska kunna
 överleva. Vårt folk blir svaga av hunger och våra matreserver räcker inte mycket
 längre. Snälla, hitta det heliga Tretton och återvänd till oss. Gå nu.}
{175}{}{Jag gå.}
{176}{}{Javisst. Jag är på väg.}
{177}{}{Jag ska göra mitt bästa för att hitta GECK och rädda vår by.}
{178}{}{Pressa mig inte, gamla tant. Jag gör mitt bästa.}
{179}{aeld20}{Mitt barn, vårt behov är större än någonsin tidigare. Vårt folk är sjukt, brahminerna
 är döende, och vår mat är nästan slut. Landets fördärv kan bara botas med
 GECK. Gå, hitta GECK och rädda vårt folk.}
{180}{}{Ja' förstå.}
{181}{}{Jag är på väg.}
{182}{}{Förlåt mig, Äldste. Jag ska hitta GECK utan dröjsmål.}
{183}{}{Ja, ja. Du börjar låta som en trasig disk...}
{200}{eeld1}{Utvalde! Hur kom du hit?}
{201}{}{Ehh... öh?}
{202}{}{Jag har kommit för att rädda dig.}
{203}{}{Vad i helvete är på gång här?}
{204}{eeld2}{Ditt monster! Har du kommit för att döda mig också?}
{205}{}{Ehhh?}
{206}{}{Nej, det är jag, den Utvalde!}
{207}{}{Håll käften, din gamla kärring! Det är jag, din Utvalde.}
{208}{eeld3}{Åh, gudar... Lyssna - gå ner. Hitta maskin som gör ström. Döda maskinen. Döda onda män. Döda allihop! Du dödar, vi går hem. Och om inte du ha GECK, leta efter GECK här. Måste ha GECK för att rädda by! Frihet är ingenting utan hem att återvända till. Förstått? Åh, gudar.}
{209}{}{A-ha!}
{210}{eeld4}{Försiktigt, rör inte glödväggen. Jag tror att maskinen som matar den är under oss. Förstör den så att vi kan fly. Hur kom du hit?}
{211}{}{Jag har ett skepp. }
{212}{eeld5}{Män kom till vår by i flygande maskiner och tog oss. Det var andra också - från det heliga Tretton! Jag trodde att vi var räddade. Jag trodde att vi skulle komma till himlen. (suck)}
{213}{}{Och sedan?}
{214}{eeld5a}{Sen förde de oss hit, till helvetet. De har dödat de flesta av oss med något de kallar effeevee. De kommer att döda oss alla innan de är klara!
 Vet du vad som måste göras, Utvalde?}
{215}{}{Effeevee?}
{216}{}{Ja.}
{217}{}{Nej.}
{218}{eeld6}{Om du förstör maskinen, hittar vi skeppet. Skynda er, vi är inte många kvar. }
{219}{}{Vad hände?}
{220}{}{Jag förstår.}
{221}{eeld7}{Du måste förstöra maskinen och döda djävlarna på denna plats. Vi möter dig utanför! Och Utvalde, om du inte har hittat GECK, sök den här. Vår frihet är ingenting om vi inte kan rädda vår by. Gå nu!}
{222}{}{Farväl.}
{223}{eeld8}{Jag är fortfarande den Äldste. Minns din plats! Be om ursäkt, annars hjälper jag dig inte mer.}
{224}{}{Ledsen, du är inte en gammal kärring. Vad är det som händer?}
{225}{}{Som om du kunde hjälpa mig där inne? Dra åt helvete och dö.}
{226}{eeld9}{Gå härifrån. Du är inte bättre än de här djävlarna. Jag gråter över att du utsågs till den Utvalde.}
{227}{eeld10}{Varför är du här? Varje minut du slösar kan leda till att någon annan av oss dödas. Och glöm inte GECK! Vi måste ha den.}
{228}{}{Nä??}
{229}{}{Var skulle jag gå?}
{230}{}{Jag ville bara reta dig. Jag jobbar på det. Oroa dig inte.}
{231}{eeld11}{(suck) Gå ner. Döda. Krossa maskiner. Gå nu!}
{232}{eeld12}{Lyssna den här gången! Gå till våningarna under oss. Hitta maskinen som gör ström. Stoppa den så kan vi fly. Männen här är inte trogna till Valv-drömmen. De är onda. Och om du ännu inte har hittat GECK, sök den här. Vår frihet är ingenting om vår by inte kan räddas. Gå nu!}
{233}{}{Jag förstår.}
{234}{eeld13}{That is what they call it. They stick needles into our skin, like stimpaks, but then terrible things happen. Then... (chokes up)}
{235}{}{Sen då?}
{236}{}{Det här kommer att få mig att må illa, eller hur?}
{237}{eeld13a}{Sedan bubblar huden som om det vore likmaskar under den. Bölder växer och spricker. Blodet rinner ur öronen och tungan sväller. De som har tur kvävs till döds. De som inte har det...}
{238}{}{De kommer att få betala för det här.}
{239}{}{Det var verkligen äckligt. Vad ska jag göra?}
