{100}{}{Before you stands Hakunin, the village shaman. He appraises you with his crazy eyes from somewhere in the world only he inhabits....}
{101}{}{You see Hakunin lying on the ground. He's badly wounded.}
{102}{}{You see Hakunin. He's very near death.}
{103}{}{Hakunin is badly burned. He smells like roast chicken, looks like burnt meatloaf, and you don't know how he's managed to stay alive this long.}
{104}{hak001}{Var hälsad, utvalde. Varför värms jorden framför mig vid beröringen av din passage?}
{105}{}{Eh? }
{106}{}{Jag har kommit för att säga adjö. Jag ger mig av på mitt heliga uppdrag. }
{107}{}{Jag är på väg ut. Jag hoppades att du för en gångs skull kunde prata som en riktig person. }
{108}{}{Du tar alldeles för många droger. Jag sticker härifrån. }
{109}{}{Jag är skadad. Kan du läka mig?}
{110}{}{Det fanns några ganska otäcka växter i din trädgård- jag har tagit hand om dem åt dig.}
{111}{hak001a}{Vänligen avslöja för grumlade ögon syftet med din passage.}
{112}{}{Eh? }
{113}{}{Jag har kommit för att säga adjö. Jag ger mig av på mitt heliga uppdrag. }
{114}{}{Jag är på väg ut. Jag hoppades att du för en gångs skull kunde prata som en riktig person. }
{115}{}{Du tar alldeles för många droger. Jag sticker härifrån. }
{116}{}{Det fanns några ganska otäcka växter i din trädgård- jag har tagit hand om dem åt dig.}
{117}{hak002}{Jorden sjunger med nyheten om en ärad kämpe i vårt land.... Kanske, innan du går, kan du skänka en vänlighet?}
{118}{}{Visst. Vad behöver du?}
{119}{}{Det beror på... Vad tänker du ge mig?}
{120}{hak002a}{Världens vyer är många - en lektion du snart kommer att lära dig.... Kanske, innan du skördar livets erfarenheter, skulle du skänka en vänlighet?}
{121}{}{Bad du mig just att göra dig en tjänst? Om så är fallet, varför inte?}
{122}{}{Jag ska göra något för dig, men eftersom jag måste arbeta så här hårt bara för att förstå dig, kommer den här uppgiften att kosta.}
{123}{hak003}{En välsignelse över dig, för du är verkligen ett naturens barn. Kan du vara snäll och använda dina speciella talanger och befria min trädgård från den mörka själens växter?}
{124}{}{Aha. }
{125}{}{Näe. Duuu. Ge me. Huve ont.}
{126}{hak004}{Må din aura pryda min närvaro när du är... Åh, kom till min dörr när du är klar så ska jag ge dig något välgörande.}
{127}{}{Urgh.}
{128}{hak005}{Den mörka själens växter har angripit min trädgård igen. Många årstider har berört mina ben och jag är för bräcklig för den kamp som är evig till sin natur. Jag ber att du ska vara min ärekämpe.}
{129}{}{Jag tror inte det. Jag måste påbörja mitt uppdrag direkt.}
{130}{}{Jag vet att du inte är en ond snubbe, men jag har redan huvudvärk, så jag tror att jag måste avstå.}
{131}{}{Glöm det. Jag är den framtida ledaren för denna stam och det skulle vara ovärdigt för mig att göra ditt trädgårdsarbete åt dig.}
{132}{}{Det vore en ära, o helige.}
{133}{}{Bad du mig just att rensa ogräs i din trädgård? Om så är fallet, okej.}
{134}{}{För ett pris.}
{135}{hak006}{Att begära betalning för en gåva kommer att ge dig mindre än gåvan själv. Jag ska ge dig en sådan och lägga till lärdomen om din självbesvikelse vid mottagandet.}
{136}{}{Det räcker gott och väl. Var är trädgården?}
{137}{}{Du vet, en trevlig present skulle vara att PRATA SVENSKA!}
{138}{}{Vad sägs om att jag ger dig en lektion i besvikelse och går nu? Hej då.}
{139}{}{Om det är din inställning är jag nog inte intresserad. Hejdå.}
{140}{hak006a}{Om vi säger samma ord, menar vi då samma sak? För ord alltid samma beröring till en själ?}
{141}{}{Just ja. Mycket bättre. Och läxan jag lärde mig är att hålla tyst och bara fråga var trädgården är.}
{142}{}{Låt oss prova orden "hej då", som betyder att jag tänker gå. }
{143}{hak007}{Du minns ju att det är åt nordost, din dåre.}
{144}{}{Tack för din hjälp.}
{145}{}{Tack. Jag förstod faktiskt det där.}
{146}{}{Kallar du mig en dåre? Jag tror inte att jag vill hjälpa dig, trots allt. }
{147}{}{Jag kommer tillbaka för min betalning snart.}
{148}{hak008}{Den börda du bär nu kommer att bli allt tyngre.}
{149}{hak009}{Må gudarna välsigna dina ansträngningar, Utvalde. Må din aura pryda min närvaro när jorden andas rent igen.}
{150}{}{Jag antar att du vill träffa mig igen när jag är klar... Du kunde bara ha sagt det, vet du.}
{151}{}{Farväl.}
{152}{hak010}{Ha! Grundarens anda lever i dig. Fokusera på att stärka dig själv för att utöka din storhet och göra det möjligt för dig att beröra världen. Naturligtvis kommer belöningarna att vara mer än andens. }
{153}{}{Det låter bra. Jag kommer tillbaka när jag är klar.}
{154}{}{Så jag får en riktig sak i betalning. Det låter bra. Syns senare.}
{155}{}{Jag tror att du har lekt med växterna alldeles för mycket. För att undvika ditt öde håller jag mig borta från trädgården.}
{156}{hak011}{Tid kan varken slösas bort eller sparas - den måste alltid vara nu. Det är handlingarna som väver ditt livs tyg.}
{157}{}{Ja, just det. Som jag sa, jag måste gå. Hej då.}
{158}{}{Att prata med dig får mig att fundera på idén om att tid inte kan slösas bort. Jag sticker härifrån. }
{159}{}{Om jag bara hade din visdom, du vise. Förlåt mig - naturligtvis ska jag ta hand om det åt dig.}
{160}{hak012}{Du må bära den Utvaldes mantel, men din mörka själ skriker inifrån.}
{161}{}{Jag ber om din förlåtelse, du helige. Hur kan jag rena min själ? }
{162}{}{Det stämmer, Hakunin, och du skulle vara en riktigt klok man om du inte glömde det.}
{163}{}{Mitt huvud värker inifrån när jag lyssnar på dig. Jag är borta.}
{164}{}{Booka!}
{165}{hak013}{Rena din själ som du skulle fördriva demoner från min trädgård.}
{166}{}{Det ska ske, du vise. Jag kommer och söker din förlåtelse efter att jag har renat din trädgård.}
{167}{}{Du försöker säga att det är bra för mig att rensa ogräs i din trädgård, eller hur? Okej, jag ska ge det ett försök.}
{168}{}{Jag gillar faktiskt min själ som den är. Hej då.}
{169}{}{Jag är inte värdig. Jag ska ta min avsked nu.}
{170}{hak014}{Utvalde, än en gång är helheten av din varelse som ett välsignat land.}
{171}{}{Tack.}
{172}{}{Du menar att jag mår bättre, eller hur?}
{173}{hak015}{Att göra en människa hel ger en uppfyllande känsla som du skulle må bra av att förstå, Utvalde.}
{174}{}{Vänta, säg det inte. Jag mår bättre och du mådde bra av att göra det, eller hur? Tack för det.}
{175}{}{Du är vis och vänlig, O Helige.}
{176}{hak017}{In what way may I touch the chosen soul, Seed of the Dweller?}
{177}{}{Eh, var exakt ligger din trädgård?}
{178}{}{Jag är skadad. Kan du läka mig?}
{179}{}{Åh, ingenting. Hej då.}
{180}{hak018}{Ahh. You return the spirit of the Dweller to the world and bring a smile to the soul of an old man in passing. For this, I give you powders of healing. Remember, they fog the mind as they cleanse the body.}
{181}{}{Tack.}
{182}{hak018a}{Och dessutom kommer jag att blanda brocblomman med xanderroten när du ger mig båda. Må dina vägar gå rätt fram och ditt hjärta följa därefter. }
{183}{}{Var kan jag hitta dessa saker?}
{184}{}{Tack.}
{185}{}{Jag är nästan ledsen att jag måste gå. Jag kan nästan förstå dig nu. Hej då.}
{186}{hak019}{Åh, Utvalde, min trädgård är välskött- hur är din?}
{187}{}{Jag mår bra.}
{188}{}{Jag behöver läkning.}
{189}{}{Var sa du att växterna var?}
{190}{}{Jag har ingen trädgård- vad i helvete pratar du om den här gången?}
{191}{}{Jag vill att du gör lite läkande pulver åt mig.}
{192}{}{Åh, glöm det. Jag måste gå.}
{193}{}{Aj?}
{194}{}{Fnys! Bårt!}
{195}{hak020}{Njutningen av dessa ord fyller mig. Ack, gudarna viskar för mitt öra. Adjö.}
{196}{}{Hej då.}
{197}{}{Du blandar fortfarande örterna, va? Vi ses senare.}
{198}{hak021}{We all have gardens. May your journeys act as tending. Be well. I must seek audience with the gods now.}
{199}{}{See ya.}
{200}{}{I'm betting you carry your audience with you wherever you go. Be well.}
{201}{hak022}{Titta norrut, Utvalde, och vägen kommer att vara öppen.}
{202}{}{Okej. Tack.}
{203}{hak023}{Jag är ärad att få tjäna den Utvalde.}
{204}{hak024}{Sådant är livet. Två skapar en tredje. Du behöver både xanderrot och brokblomma för det helande pulvret.}
{205}{}{Åh. Tack}
{206}{}{Bajs.}
{207}{hak025}{Må detta vara utan nytta.}
{208}{}{Okej. Tack.}
{209}{}{Uh!}
{210}{hak026}{Du mår bra.}
{211}{}{Tack.}
{212}{}{Inga lektioner? Inga obegripliga tal? Är du säker på att du är okej?}
{213}{hak027}{Välkommen, Utvalde. Välsigna oss med ord om att GECK kommer att hittas snart. Vår by lider, vårt behov är stort, vår tid, kort.}
{214}{}{Nä.}
{215}{}{Och din förmåga att tala normalt, obefintlig. Jag försöker fortfarande.}
{216}{}{Jag jobbar på det. }
{217}{}{Låt mig vara, gamla gubbe. Jag gör så gott jag kan.}
{218}{}{Jag letar fortfarande, helige. Jag hoppas ha GECK snart.}
{219}{hak028a}{Må Jorden dämpa stegen du måste ta.}
{220}{hak028b}{Må Vattnet lugna din resa.}
{221}{hak028c}{Må Vinden leda dig till ditt mål.}
{222}{hak028d}{Må Elden bränna din rumpa tills du får det här gjort.}
{223}{}{Tack.}
{224}{}{Vad sa du?!}
{225}{}{Eh.}
{226}{}{Va?!}
{227}{hak029}{Welcome back, Chosen. I see by your face the salvation of the GECK is not yet ours. Be tireless as the ant before our reserves run out. You are our last hope.}
{228}{}{Aha.}
{229}{}{I'm trying. I'd like to see the ant covering the miles I am.}
{230}{}{I'm doing my best.}
{231}{}{I'll double my efforts, holy one. I will not let you down.}
{232}{}{Yeah, yeah. I've heard it all before.}
{233}{hak030}{Chosen - the village cries in desperation. The children are weak with hunger. Please, we cannot hold out much longer.}
{234}{}{Aha.}
{235}{}{I'm trying. I'm trying! Give me a break!}
{236}{}{I'll find the GECK, holy one. You have my word.}
{237}{}{I'll do my best to find the GECK.}
{238}{hak031}{Chosen, the sands of time are but a few grains. Please. Bring the GECK soon and make the future of the village like the beach of the ocean. Quickly, before the last grain falls.}
{239}{}{Aha.}
{240}{}{All right. I'm off to find it.}
{241}{}{Life's a beach, huh?}
{242}{}{I will find the GECK, holy one. I will not let our people down.}
{243}{hak032}{Chosen, the spirits of our ancestors guide me to a world of dreams that I may touch thoughts. Our village suffers without the holy GECK. Your hands hold our lives as a father holds his children.}
{244}{hak033}{Once again my spirit touches you from the void, Chosen. Our crops fail, our reserves are meager. Return to us with the GECK. Your failure is our last light.}
{245}{hak034}{Chosen. The village weakens. It is harder to touch your dreams. You must hurry or we will all...}
{246}{hak035}{Chosen? Chosen? Do you hear me? The village dies. All of our futures die, too. We have little left in both time and essence... Hurry. Hurry...}
{247}{hak101}{Chosen - the shadow of darkness arrived before you.}
{248}{}{Ajjjj!}
{249}{}{Vad hände?}
{250}{}{You look bad. Let me help.}
{251}{hak102}{Child of Nature, how could we put such a burden on your shoulders? (sigh) Your people have been taken.}
{252}{}{Ehhh?}
{253}{hak103}{Yes. Gone. Many dark souls came, riding the metal birds like a flock of hungry chittick bugs, hiding their evil in shiny skins. }
{254}{}{Ooo! Shiny Purty!}
{255}{hak104}{No! Not shiny pretty! They kidnapped our people and took them to the southwest.}
{256}{}{Aj.}
{257}{hak105}{Yes. Great sadness and pain. I stand between worlds to tell you, Chosen. Save your people.}
{258}{}{Eh?}
{259}{hak106}{Chosen, please let my words touch you. Go southwest. South and west. Save our people. Save our people.}
{260}{}{Aha.}
{261}{hak107}{Thank the ancestors. Now my soul may join the eternal song. Safe journey, Chosen.}
{262}{}{Gå?}
{263}{hak108}{Gå!...}
{264}{}{Bye bye.}
{265}{hak109}{Dark souls came. They took everyone.}
{266}{}{Dark souls? What do you mean?}
{267}{hak110}{A rush of wind came. On it were great dragonflies that spat flame. Evil men crawled from the beasts' bellies and brought death to our warriors.}
{268}{}{Our warriors couldn't stop them?}
{269}{hak112}{Anden var villig, men spjutspetsarna var svaga. De onda brände våra krigare med skärseld.}
{270}{}{Dödade de alla?}
{271}{hak113}{Alla blev dödade eller tillfångatagna. Min ande återvände till köttet bara för att avslöja sanningen för Den Utvalde.}
{272}{}{Vad hände med de som togs?}
{273}{hak114}{Odjuren svalde alla och gav sig sedan iväg för vinden.}
{274}{}{Eh, åt vilket håll blåste vindarna som de följde?}
{275}{hak115}{Lyssnade du aldrig när jag lärde dig vindandarnas årliga dans? Söderut, så klart.}
{276}{}{Dina beskrivningar var så levande och kraftfulla, store Hakunin, att jag ofta blev helt hänförd under dina lektioner.}
{277}{}{Åh, de vindarna. Såklart. }
{278}{hak116}{Ja, de färdades med vinden söderut. Jag hörde de mörka själarna tala. De planerade att vila sina bestar på en plats som heter Navarro innan de korsade den stora funt fylld med vår jordmoders tårar.}
{279}{}{Vad skall jag göra?}
{280}{}{Tårarnas funt?}
{281}{hak117}{För mig, ingenting. Utvalde, du måste söka de mörkas flock och rädda vårt folk.}
{282}{}{Jag ska försöka.}
{283}{hak118}{Du är den Utvalde. Du måste göra det.}
{284}{}{Hakunin?}
{285}{}{Första gången jag förstod vad du menade.}
{286}{hak120}{Ett hav av tårar, gråtit av en mor för sina barn.}
{287}{}{Åh, havet. Men vad skall jag göra?}
{288}{hak121}{En märklig dimma stal deras sinnen och skickade dem till Sömnens land. De onda vandrade bland drömmare, men drömde inte.}
{289}{}{Och sedan?}
{290}{hak122}{För många årstider och för många sår, Utvalde. Istället måste du lyssna.}
{291}{}{Okej.}
{300}{}{De som stjäl bär på en stor börda. Kom ihåg detta, Utvalde.}
{301}{}{Du måste nu betala för dina synder, Utvalde.}
