{100}{}{Du ser en ockupant.}
{101}{}{Du ser Bill, ockupanten.}
{102}{}{Du ser en medelålders man som bär slitna kläder.}
{103}{}{Ledsen, främling. Jag har inte tid att prata med dig.}
{104}{}{Hörru, jag sa att jag inte har tid att prata. Var snäll och försvinn.}
{105}{}{Tack för att du hjälpte Rebecca. Det var bra gjort av dig.}
{106}{}{Lämna mig ifred. Jag är inget hot mot dig.}
{107}{}{Javisst, javisst. Jag rör på mig.}
