{100}{}{Du ser en ung kvinna.}
{101}{}{Du ser Chrissy, Rebeccas dotter.}
{102}{}{Du ser en vacker ung kvinna. Hon ser självsäker ut och kan ta hand om sig själv i en strid.}
{103}{}{Om du är här för att försöka våldta mig, kommer du bära dina kulor som en fluga. Fattar du?}
{104}{}{Låt mig gissa. Killarna är trötta på att jag sparkar dem där det gör ont, så de skickade in dig hit för att
 göra något hemskt. Jag kan skada dig lika illa, jag behöver bara sparka högre. Fattar du?}
{105}{}{Fluga?}
{106}{}{}
{107}{}{Vad hända här? Vem du?}
{108}{}{}
{109}{}{Jag skulle vilja veta vem du är och vad som pågår här.}
{110}{}{Japp. Ett tjusigt tygstycke som bärs runt halsen som dekoration. Det är som en rosett, men för
 män. Tänk dig nu att jag sparkar dig så hårt att det slutar med att du bär dina dinglisar runt halsen. Fattar du
 det?}
{111}{}{Jag förstå. Du inte göra mig illa.}
{112}{}{Jag fattar; snälla gör mig inte illa.}
{113}{}{Okej, så varför är du här?}
{114}{}{}
{115}{}{Jag veta vill vad händer här? Vem du?}
{116}{}{}
{117}{}{Jag skulle vilja veta vem du är och vad som pågår här.}
{118}{}{Verkligen? Grymt! Nu kör vi.}
{119}{}{Okej.}
{120}{}{In a nutshell, my name is Chrissy and I'm from the Squat. I was out exploring last week when I
 found that entrance out there. I thought it might be an abandoned mine or something, so I decided to
 check it out. Well, it's not a mine; it's a secret entrance into Vault 15. The vault is being
 used as a base for a band of raiders called the Khans. They caught me snooping around and their leader, Darion, had me locked up in here.}
{121}{}{Okej. Jag dig tar hem.}
{122}{}{Okej, jag tar dig hem.}
{123}{}{Ja, det var som fan. Idag måste vara min turdag. Vad förskaffar mig nöjet att få träffa dig
 igen?}
{124}{}{}
{125}{}{Vad hända här? Vem du?}
{126}{}{}
{127}{}{Jag skulle vilja veta vem du är och vad som pågår här.}
{128}{}{Snälla ta mig till min mamma, Rebecca.}
{129}{}{Min riddare i skinande rustning återvänder. Ja, den skulle glänsa om du gjorde rent den lite
 då och då. Och du kanske skulle överväga att bada dig själv också. Så, vad kan jag göra för dig?}
{130}{}{Jag bara säga hej. Jag gå nu.}
{131}{}{Jag tänkte bara säga hej. Jag ska gå nu.}
{132}{}{Hey, I know I have a smart mouth, but I want you to know that I'm very grateful for you saving
 my butt. Thanks very much!}
{133}{}{Det så lite.}
{134}{}{Det var så lite.}
{135}{}{The people of the Squat are protecting these guys by helping them keep the vault a secret, but they
 don't know what's really going on here. Darion told us that the vault was being repaired so we could have
 a safe place to live with lots of food and water, but it's all a lie. I've been in there and looked
 around. The vault is dead, and the food and water machines don't work. Our food and water's been coming
 from the spoils
 of raids against caravans.}
{136}{}{Jag måsteta mig hem och varna alla för vad som verkligen pågår här. Vi kan inte hjälpa de här
 monstren. Kan du ta mig hem?}
