{100}{}{Du ser en ung kvinna i trasiga kläder.}
{101}{}{Du ser Dalia.}
{102}{}{Du ser en ung kvinna i trasiga kläder. Hon verkar mycket alert och iakttar sin omgivning
 noggrant.}
{103}{}{Hej. Jag heter Dalia. Vad kan jag hjälpa dig med?}
{104}{}{Inget, bara säg hej.}
{105}{}{Öh, vem du?}
{106}{}{Vad du gör här?}
{107}{}{Du ser ut som vakt.}
{108}{}{Jag gå nu.}
{109}{}{Säger bara hej.}
{110}{}{Vem är du?}
{111}{}{Vad är det du gör?}
{112}{}{Du ser ut som om du vaktar den där stigen.}
{113}{}{Jag ska gå nu.}
{114}{}{Ja men, hej på dig. Jag är ledsen, men du borde gå.}
{115}{}{Jag prata vill.}
{116}{}{Ok, ja' gå.}
{117}{}{Jag vill prata med dig.}
{118}{}{Hej då.}
{119}{}{Jag sa att jag heter Dalia. Jag vill inte vara oförskämd, men jag vill inte prata med någon just nu. Okej?}
{120}{}{Okej, hej då.}
{121}{}{Bara mer lite.}
{122}{}{Då går jag.}
{123}{}{Jag vill bara ställa en fråga till dig.}
{124}{}{Jag gillar den friska luften, jag gillar träden, så jag står här. Har du något problem med det?}
{125}{}{Ledsen, jag gå.}
{126}{}{Nej, inte problem. Jag fråga dig något.}
{127}{}{Jag har inget problem, men jag är nyfiken på en sak.}
{128}{}{Ledsen, jag ska gå då.}
{129}{}{Nej, jag vaktar inte stigen. Det finns inget i det här hålet som är värt att vakta. Jag sa ju att jag
 njuter av den friska luften. Försvinn nu.}
{130}{}{Du trevlig prata med. Jag prata mer.}
{131}{}{Ledsen jag stör. Jag gå.}
{132}{}{Men vi har ett så trevligt samtal, varför sluta?}
{133}{}{Jag antar att det är dags att gå.}
{134}{}{Åh nej, det är skadedjuret igen. Jag har inget att säga till dig. Gå din väg!}
{135}{}{}
{136}{}{}
{137}{}{Jag har inget otalt med dig. Låt mig vara i fred.}
{138}{}{}
{139}{}{}
{140}{}{Hej. Jag heter Dalia. Vad kan jag hjälpa dig med?}
{141}{}{Person som förbi här? Bråttom?}
{142}{}{Ingenting.}
{143}{}{Ingenting.}
{144}{}{Såg du någon ha bråttom förbi här?}
{145}{}{I see people go by here every day. I really don't pay much attention to them.}
{146}{}{Me not have time for you crap.}
{147}{}{Åh, okej.}
{148}{}{Girl life at stake. Young girl. Someone daughter. You please help?}
{149}{}{I don't have time for your crap.}
{150}{}{Fine, bye.}
{151}{}{Look, a young girl's life is at stake here. The daughter of a worried mother. Can you please
 help me out?}
{152}{}{I don't give a radrat's ass... I'm sorry. I'm just a gun who was hired to stand here and guard
 this trail. Other than that, I don't know what's going on around here. I had a daughter once, though,
 and... yeah, some guy went by here. I let him through because he knew the proper sign... just like the
 sign you gave me. Go on. I'm outta here. }
{153}{}{Tack. Jag inte glömma det här, Dalia.}
{154}{}{Tack. Jag kommer inte att glömma det här, Dalia.}
{155}{}{Dra åt helvete då och låt mig vara!}
{156}{}{Färdigt.}
{157}{}{Dra åt helvete då och låt mig vara!}
{158}{}{Färdigt.}
