{100}{}{Du ser en Khan-plundare.}
{101}{}{Du ser en Khan-plundare.}
{102}{}{Du ser en tuff person med rustning, vapen och en dålig attityd. Det måste vara en Khan.}
{103}{}{Vad i...? Jag tror inte att jag känner dig. Vem fan är du?}
{104}{}{Jag har mitt ID här! Jag ska visa dig.}
{105}{}{Jag heter... ehh... Pat, och jag är ny här.}
{106}{}{Okej, lustigkurre. Gör ett bra försök.}
{107}{}{Jaha. Jag är ledsen. Kände inte igen dig först. Fortsätt med vad du höll på med.}
{108}{}{Jag är inte så dum som du ser ut.}
{109}{}{Är du inte död än? Skit också.}
{110}{}{Asså, Darion betalar mig inte tillräckligt för att bara stå här och inte göra något.}
{111}{}{Ibland sitter jag och tänker på absolut ingenting.}
{112}{}{Jag bryr mig i allmänhet inte om vad någon annan tycker.}
{113}{}{Okunnighet är lycka... tror jag.}
{114}{}{When's the next caravan passing through? I could use some action.}
{115}{}{I could use a break.}
{116}{}{Damn, I still hurt from that bitch Chrissy kicking me.}
{117}{}{Hey, we never get any new blood around here.}
{118}{}{So when are we going to get out of this stupid place?}
{119}{}{I don't know about you, but I think this sucks.}
{120}{}{There ain't nothin' to kill around here.}
{121}{}{Where's the damn bathroom?}
{122}{}{Hey, we never get a break around here. Isn't there some law or something?}
{123}{}{We should start up a government like in the old days.}
{124}{}{Man, I wonder what it was like to be President back then?}
{125}{}{I bet you could do anything you wanted if you were President.}
{126}{}{I think my father would be proud of me today. Too bad I killed him.}
{127}{}{I HATE RATS! HATE HATE HATE!}
{128}{}{Hey, is that new armor you have on? How do you rate getting new armor?}
{129}{}{This damn vault smells. Don't you hate it?}
{130}{}{Hey, who is it we're supposed to be keeping an eye open for?}
{131}{}{All I do is stand, stand, stand.}
{132}{}{I think we should just waste everyone upstairs and say to hell with this place.}
{133}{}{What the hell is your problem with rats?}
{134}{}{Have you ever pulled one of the legs off of a rat?}
{135}{}{I like guns, yeah! GUNS I LIKE! GUNS: I REALLY, REALLY LIKE THEM!}
{136}{}{Hey, is anyone listening to me?}
{137}{}{Oh well, I just talk to keep myself sane anyway.}
{138}{}{Hey, anyone remember what was in a Long Island Ice Tea?}
{139}{}{Yeah, vodka, rum, tequila, triple sec, lime, and Nuka.}
{140}{}{Hey, look -- the lights came on. What the...}
{141}{}{Darion said he'd get the damn lights fixed. I guess he came through.}
{142}{}{I don't think the generator just fixes itself, does it?}
{143}{}{That was kind of weird; now I can see. Jesus, this place looks like shit!}
{144}{}{Wow, it's bright in here. Where's the dimmer control?}
{145}{}{Dö!}
