{100}{}{Du ser en ockupant.}
{101}{}{Du ser John, ockupanten.}
{102}{}{Du ser en medelålders man som bär slitna kläder.}
{103}{}{Ledsen, främling, jag har inte tid att prata med dig.}
{104}{}{Varför prata inte?}
{105}{}{Okej, vågigt.}
{106}{}{Okej, vi ses.}
{107}{}{Vänta lite nu. Varför vill du inte prata med mig?}
{108}{}{Vi är ett mycket privat samhälle här, och vi vill inte ha några problem eller störningar från utomstående
 källor. Snälla, låt oss bara vara.}
{109}{}{Okej.}
{110}{}{Hej... och hej då.}
{111}{}{Tack för allt du har gjort. Jag ber om ursäkt för det kalla bemötandet tidigare.}
{112}{}{Fan ta dig, skitstövel!}
{113}{}{Fan, jag hatar när det händer.}
{114}{}{Ta den där! Ja, det ska du få se.}
