{100}{}{Du ser en Khan-plundare.}
{101}{}{Du ser Phil, en Khanvakt.}
{102}{}{Du ser en tuff ung man i metallrustning. Han är tungt beväpnad.}
{103}{}{Jag borde skjuta ihjäl dig, men jag är lite nyfiken på vad du kan tänkas ha att säga till
 mig.}
{104}{}{Jag leta spion. Gå den här vägen.}
{105}{}{Jag leta försvunnen flicka. Vet du var hitta?}
{106}{}{Jag kom hit misstag. Gå nu.}
{107}{}{Fan ta dig. Jag skjuta dig död.}
{108}{}{Eh, vi prata om det här?}
{109}{}{Jag letar efter en tjuvlyssnare som kom den här vägen.}
{110}{}{Jag letar efter en försvunnen flicka. Har du sett henne?}
{111}{}{Förlåt, jag råkade ta fel spår av misstag. Måste gå.}
{112}{}{Kör upp den och ät en frukost av kulor, skitstövel.}
{113}{}{Jag tror att vi kan prata ut om det här som två civiliserade varelser.}
{114}{}{Ah, det skulle vara jag. Nu när du har hittat mig, vad händer härnäst?}
{115}{}{Varför du spioner Rebecca?}
{116}{}{Now me know not be shooting wrong person. Thanks!}
{117}{}{Nothing, me go now.}
{118}{}{Why are you spying on Rebecca?}
{119}{}{Just wanted to make sure I'm shooting the right person. Thanks, and have a nice day!}
{120}{}{Hmm. Nothing, I guess I'll be going now.}
{121}{}{I can't believe that you think you can just waltz in here and get answers to your questions!
 Oh, what the hell, you're about to die anyway and I feel generous. We've got her kid locked in the
 back room and have been having some fun with her. That bitch, Rebecca, has been trying to find her, so
 we've been keeping an eye open to make sure she doesn't get too close.}
{122}{}{You sicky in head. Me fix by remove head.}
{123}{}{What you mean have fun with girl?}
{124}{}{Oh, that explain. Me leave now.}
{125}{}{You are one sick puppy. I think I'll put you to sleep now.}
{126}{}{Fine, have fun and I'll be going now.}
{127}{}{Hand over the girl and we can all leave here alive.}
{128}{}{Think about it as you die, stupid.}
{129}{}{}
{130}{}{}
{131}{}{Why in the hell should I do that?}
{132}{}{It's good for your eternal soul.}
{133}{}{Because I'm the worst thing that you could ever fear happening to you. Hand her over or feel
 the pain.}
{134}{}{Because if we fight, one of us will die. I don't want to die any more than you do, so let's end
 this peacefully. Okay?}
{135}{}{Screw that noise.}
{136}{}{}
{137}{}{}
{138}{}{That sounds like a challenge. I'll take it.}
{139}{}{}
{140}{}{}
{141}{}{Hmm... I... Yeah, Okay. Here's the key to her cell; she's in the back room of the shack. Take her
 and get out, but don't come back. If I see you again, we'll see who lives and who dies.}
{142}{}{Let's see who comes out of this alive.}
{143}{}{Thanks, you did the right thing.}
{144}{}{The only way you're leaving here is feet first, in a box.}
{145}{}{}
{146}{}{}
{147}{}{You mean the one locked up in back that we've been having fun with? No, I haven't seen her.}
{148}{}{You sicky in head. Me fix by remove head.}
{149}{}{What you mean have fun with girl?}
{150}{}{Oh. Me leave now.}
{151}{}{You are one sick puppy. I think I'll put you to sleep now.}
{152}{}{Fine, have fun and I'll be going now.}
{153}{}{Hand over the girl and we can all leave here alive.}
{154}{}{So, you've returned. Let's see who comes out on top.}
{155}{}{We killed that bitch Chrissy, and now it's your turn to die!}
