{100}{}{You see an older woman.}
{101}{}{Du ser Rebecca.}
{102}{}{You see an older woman. Although she appears to have lived a hard life, she has not lost any of
 her natural beauty.}
{103}{}{Hi, I'm Rebecca. Can we talk privately, please?}
{104}{}{What talk about?}
{105}{}{Why need talk private?}
{106}{}{Okej.}
{107}{}{No. Me leave.}
{108}{}{Sorry, not interested.}
{109}{}{What do you want to talk to me about?}
{110}{}{Sure, where can we go for privacy?}
{111}{}{Why the need for privacy?}
{112}{}{(whispering) My daughter is missing and I need help finding her. I can't talk about it here,
 though. Can we go somewhere private?}
{113}{}{Okej.}
{114}{}{Why need talk private?}
{115}{}{No, me go.}
{116}{}{All right, let's go.}
{117}{}{Why the need for privacy?}
{118}{}{No thanks, I don't want to get involved.}
{119}{}{(whispering) You may think I'm crazy but I get the feeling I'm being watched all the time. It's
 rather disturbing, and I'm a bit on edge because of it.}
{120}{}{Okej, vi gå privat.}
{121}{}{Ingen tid för sjuk i huvudet.}
{122}{}{All right; where can we go to talk?}
{123}{}{Sorry, I don't like the sound of this.}
{124}{}{Thanks; we can go to my tent.}
{125}{}{Okej.}
{126}{}{We should be able to talk here.}
{127}{}{Okay, what problem?}
{128}{}{Me got questions first.}
{129}{}{Okay, so what's so important?}
{130}{}{I have some questions for you, first.}
{131}{}{I have a daughter named Chrissy who's a bit of a tomboy. She likes to run around, explore,
 and pretty much stick her nose into things. Chrissy's a good kid, though. She doesn't
 cause trouble, she's always home on time and she's shown herself to be a very responsible young lady.
 I let her do as she pleases most of the time. Last week Chrissy didn't come home. I've asked
 around, and nobody's seen or heard from her. I tried to find her myself, but Zeke, he's... sort of the
 mayor here... stopped me. He said it wasn't safe for me to go out looking on my own; he'd have some of
 his men do it. They couldn't find her, either, and said that maybe the slavers got her.}
{132}{}{No, not get involved.}
{133}{}{Need think before decide.}
{134}{}{Ok, me seem be hero type lately.}
{135}{}{Sorry, not interested.}
{136}{}{I need to think about this.}
{137}{}{All right, Rebecca. I'll try to help you.}
{138}{}{If I help you, what's in it for me?}
{139}{}{Vad vill du veta?}
{140}{}{What go on here?}
{141}{}{Who boss?}
{142}{}{Me try find Vault 13. You know where is?}
{143}{}{Tell about vault.}
{144}{}{Tell about Darion.}
{145}{}{Thanks. We talk you problem?}
{146}{}{Vad är på gång häromkring?}
{147}{}{Who's in charge around here?}
{148}{}{I'm looking for Vault 13. Do you know anything about it?}
{149}{}{Tell me about the vault.}
{150}{}{So tell me about Darion.}
{151}{}{Thanks Rebecca. Let's talk about your problem now.}
{152}{}{We call this place the 'Squat' because it was settled by the homeless of many cities. It's not
 much, but it's all we have. To the west is a city called the NCR. They've known about us for quite some
 time, and never offered us any kind of help or hindrance. Now, they are suddenly claiming this area as their
 ancestral home, and they want it back.}
{153}{}{Okej.}
{154}{}{What here they want?}
{155}{}{Jag förstår.}
{156}{}{What is here that they want so badly?}
{157}{}{Well... there is a vault here; I think it's number 15. They want to loot it for any of the old
 technology that may still be there.}
{158}{}{Ah. Me understand.}
{159}{}{I knew there had to be something here other than the waste-of-flesh inhabitants.}
{160}{}{Jag förstår.}
{161}{}{That explains a lot. You've been very helpful. I need to ask some more questions, though.}
{162}{}{That would be Zeke. He runs everything up here. You can find him in the building over there.
 ::points north-east::}
{163}{}{Thanks. Ask more.}
{164}{}{Thank you. I need to ask you some more questions.}
{165}{}{I'm sorry, I have no idea. I would ask about it in NCR. They've taken a great interest in
 vaults lately.}
{166}{}{Okay, me do.}
{167}{}{All right, I will.}
{168}{}{Så... Vi får inte prata om det, men eftersom jag behöver din hjälp... Valvet håller på att
 reparerat av Darion. Han är vår välgörare. När det är fullt fungerande, ska vi alla flytta in.
 där vi kommer att vara säkra från plundrare, slavhandlare och liknande. Än så länge har han mat- och vattensystemen uppe, men
 det är typ allt.}
{169}{}{Förstår. Behöva veta mer.}
{170}{}{Jag behöver veta mer.}
{171}{}{Det finns inte mycket att säga, egentligen. Darion håller sig för sig själv och lämnar aldrig valvet. Om han har
 något att säga, så säger han det genom Zeke. Jag har bara träffat honom en gång, och han verkade vara en trevlig kille.}
{172}{}{Okej.}
{173}{}{Nice guys finish last. I wonder what he's up to?}
{174}{}{Jag förstår.}
{175}{}{Det är okej. Du är väldigt hjälpsam.}
{176}{}{Jag har inget annat att ge dig än min eviga tacksamhet.}
{177}{}{Det är mer än tillräckligt. Jag tänker hjälpa dig.}
{178}{}{Det krävs mer än så för att köpa min hjälp.}
{179}{}{Vad fan, jag tänker hjälpa dig.}
{180}{}{Thank you so much. I'll never be able to repay you for this. I'll wait here until you bring...
 Hey, there was someone outside listening to us! I saw their shadow on the tent wall. They just ran off
 that way! ::points north-east:: They must have heard everything!}
{181}{}{Me stop, no get away!}
{182}{}{Du inte oroa, hittar flicka.}
{183}{}{Ojdå.}
{184}{}{Jag ska försöka stoppa dem.}
{185}{}{They won't stop me from finding your daughter.}
{186}{}{Oh well. Shit happens.}
{187}{}{Please, just go away.}
{188}{}{Have you thought things through?}
{189}{}{Me ask questions.}
{190}{}{No, still think.}
{191}{}{No, I'm still considering everything.}
{192}{}{I want to ask you some questions.}
{193}{}{Have you changed your mind? Will you help me?}
{194}{}{Sorry, no.}
{195}{}{Me help.}
{196}{}{Yes, I'll help you.}
{197}{}{You must be the person who saved my daughter. I can never repay you for your kindness. Thank you.
 Please wait here, I need to talk to Chrissy and then I'd like to talk to you.}
{198}{}{You saved my daughter. I can never repay you for your kindness. Thank you.
 Please wait here, I need to talk to Chrissy and then I'd like to talk to you.}
{199}{}{Okej.}
{200}{}{My daughter has told me everything. I find it hard to believe that Darion is such a monster
 after all he's been doing for us. And to think, we've been helping him hide his operations as a raider.
 I can guarantee you we won't stand for it any longer. I've already talked to Zeke, and he wants to see
 you. You should go see him now.}
{201}{}{I find it hard to believe that Darion is such a monster after all he's been doing for us. And to
 think, we've been helping him hide his operations as a raider. I can guarantee you we won't stand for
 it any longer. I'll talk to Zeke and explain everything. I'm sure he'll want to see you. You should go
 talk to him later.}
{202}{}{Tack.}
{203}{}{I hope you find Chrissy soon.}
{204}{}{Letar.}
{205}{}{Jag kommer att fortsätta leta efter henne.}
{206}{}{Tack för allt du har gjort för mig.}
{207}{}{Jag kan inte förklara varför, men jag tror inte att slavhandlarna tog henne. Jag har en obehaglig känsla av att
 något annat år på gång. Och så känner jag mig förföljd. Jag har haft det ända
 sedan jag pratade med Zeke om Chrissy. Jag behöver nån som hjälper mig att hitta min dotter. Vill du hjälpa mig,
 snälla?}
{208}{}{De fortsätter skicka hit folk för att övertyga oss om att lämna vårt hem, men de förstår inte
 att vi inte har någon annanstans att ta vägen. Vi har inte de färdigheter som krävs för att överleva på egen hand om vi flyttar
 härifrån.}
{209}{}{You know, it's kind of funny that they managed to get something that complex fixed, but not the
 lights. The damn place is lit by torches. Anyway, Darion doesn't want anyone to know what's going on
 with the vault. He's afraid that someone will take it all away from us if they find out. So, we're told
 to drive off anyone who shows up here -- especially the NCR.}
