{100}{}{Du ser en ockupant.}
{101}{}{Du ser Roberta, en husockupant.}
{102}{}{Du ser en medelålders kvinna som bär slitna kläder.}
{103}{}{Åh, herre. Jag är ledsen, men jag har inget att säga till dig. Var snäll och gå härifrån.}
{104}{}{Snälla, gå härifrån. Jag vill inte bli störd.}
{105}{}{Tack för att du hjälpte Rebecca. Jag hade fel om dig.}
{106}{}{Jag är inget hot mot dig. Snälla, döda mig inte.}
