{100}{}{Du ser en ockupant.}
{101}{}{Du ser Sara, en husockupant.}
{102}{}{Du ser en medelålders kvinna som bär slitna kläder.}
{103}{}{Var snäll och stör mig inte, jag är väldigt upptagen just nu.}
{104}{}{Snälla, gå härifrån. Det finns inget här för dig.}
{105}{}{Tack för att du hjälpte Rebecca. Det var underbart av dig att göra det för en främling.}
{106}{}{Jag är inget hot mot dig. Snälla, döda mig inte.}
