{100}{}{Du ser en äldre husockupant.}
{101}{}{Du ser Zeke, en husockupant.}
{102}{}{Du ser en äldre man med tunt, vitt hår.}
{103}{}{Jag heter Zeke, främling. Jag är ledsen, men jag har inte tid att prata med dig -- och jag tror inte
 att det finns något för dig i den här stan. Du borde gå vidare.}
{104}{}{Eh, okej.}
{105}{}{Ja ha frågor.}
{106}{}{Okej, jag ska gå.}
{107}{}{Jag ville bara ställa ett par frågor.}
{108}{}{Jag tror att du kommer att upptäcka att vi har slut på svar här. Varför kommer du inte tillbaka när vi
 får in en leverens?}
{109}{}{Färdigt.}
{110}{}{Hej, igen. Jag har fortfarande inga svar åt dig, främling. Varför hajar du inte och
 hrar åt delvete?}
{111}{}{Färdigt.}
{112}{}{Rebecca har berättat vad du gjorde för henne. Jag vill be om ursäkt för den behandling du fick
 här. Du förtjänade det verkligen inte. Vad kan jag hjälpa dig med?}
{113}{}{Ja ha frågor.}
{114}{}{Inget. Vinkis.}
{115}{}{Jag har några frågor till dig.}
{116}{}{Inget för tillfället, tack.}
{117}{}{Vad vill du veta?}
{118}{}{Jobbar 'u för Darion?}
{119}{}{Vad gör ni åt plundrare?}
{120}{}{Var valvdörr?}
{121}{}{Något annat händer här?}
{122}{}{Jag gå nu.}
{123}{}{Do you work for Darion?}
{124}{}{Vad tänker du göra åt plundrarna?}
{125}{}{Var är ingången till valvet?}
{126}{}{Är det något annat på gång här?}
{127}{}{Jag antar att det var allt. Jag ska gå nu.}
{128}{}{Ja, det gör jag. Jag agerar mellanhand mellan honom och folket här uppe. Jag är inte särskilt glad över
 det faktumet, nu när jag vet vad han håller på med.}
{129}{}{Okej.}
{130}{}{Jag förstår.}
{131}{}{Ingenting. De har vapnen, de kontrollerar vattnet och de kontrollerar maten. Det betyder
 att de bestämmer. Punkt slut. Vi har inga färdigheter och inget stöd utan Darions hjälp.
 Hur kan vi vända oss mot honom? Vi är utlämnade till hans nåd.}
{132}{}{Hmm. Jag tro förstå.}
{133}{}{Hmm. Jag förstår.}
{134}{}{Den är bakom dörren där borta, men den är låst från andra sidan och kopplad tillfällor också. Jag har inte
 något sätt att öppna den... Vänta lite nu. Jag hittade det här nyckelkortet för ett tag sedan, och jag har ingen aning om vad
 det är till för. Rebecca säger att du hittade nån sorts dörr där de höll Chrissy. Kanske det här
 kortet kan öppna den. Här, ta det.}
{135}{}{Jag tack dig.}
{136}{}{Tack. Jag ska försöka med det.}
{137}{}{Det finns en stad västerut som heter NKR. De hävdar att Valv 15 är deras förfäders hem och de vill ha det
 tillbaka. De har skickat hit folk för att försöka övertala oss att ge oss av, men vi går inte med på det. Det här är det enda hem vi känner till.}
{138}{}{Du kanske gör möte NKR?}
{139}{}{Kan ni tänka er att arrangera ett möte med NKR?}
{140}{}{Det beror helt på. Vad hade du tänkt dig?}
{141}{}{Gå med NKR-stam. Lär från de äldste. Ge NKR er tillstånd gå i valvet. Båda glada.}
{142}{}{Gå med i NKR, låt dem annektera ert territorium och ge dem tillgång till valvet. I gengäld kan de lära er alla färdigheter
 ni behöver för att överleva på egen hand och erbjuda er sitt skydd.}
{143}{}{Inte illa... Jag gillar det. Vi går med på det om du kan få NKR att acceptera det också. Men...
 Lyssna, någon måste ta hand om Darion och hans kumpaner. Det bör göras nu innan de inser vad som har hänt
 och har tid att förbereda sig för en attack. Varför inte få det här överstökat och ta Darion nu?
 Du har överraskningsmomentet på din sida.}
{144}{}{Du rätt, jag löser.}
{145}{}{Jag inte säker.}
{146}{}{Ja, jag antar att det måste göras.}
{147}{}{Jag vet inte.}
{148}{}{Utmärkt. Lycka till och tack så mycket.}
{149}{}{Färdigt.}
{150}{}{Ta dig tid att tänka på det, men vet detta -- tills Darion är ute ur bilden, har
 jag inget annat val än att behålla saker här som de är. Det är för alla berördas
 säkerheten. Det betyder inget avtal och du är fortfarande persona non grata. Förstått?}
{151}{}{Okej.}
{152}{}{Hej. Jag väntar fortfarande på en slutgiltig lösning på våra problem. Med andra ord, spöa Darion!}
{153}{}{Färdigt.}
{154}{}{Du har gjort det, min vän! Vi släpar inte längre Darions ok. Tack så mycket! Jag är redo att acceptera ditt avtal med NKR nu.
 Be dem bara skicka en av sina representanter så ska jag signera avtalet.}
{155}{}{Färdigt.}
{156}{}{Tack för att du gav oss chansen till ett nytt liv. Vi står alla i din skuld.}
{157}{}{Bara gå härifrån. Jag har inget att säga till dig.}
{158}{}{Vänta, innan du går... Jag hittade det här nyckelkortet för ett tag sen, och jag har ingen aning om vad det är till för.
 Rebecca säger att du hittade nån sorts ingång där de höll Chrissy. Kanske det här kortet kommer
 öppna den. Här, ta det.}
{159}{}{Tack.}
{160}{}{Vad kan jag hjälpa dig med?}
{161}{}{Bara problemen med NKR, men jag tror att avtalet du erbjöd kommer att lösa det.}
{162}{}{Du har gjort det, min vän! Vi är inte längre under Darions ok. Tack!}
{163}{}{Nu när Darion är borta har vi inget sätt att skaffa mat. Vi kommer säkert att förgås! Tack så mycket.}
