{100}{}{Du möter skurkar och vargar.}
{101}{}{Du möter skurkar.}
{102}{}{Du möter vargar.}
{103}{}{Du möter radioaktiva skorpioner.}
{104}{}{Du möter sporväxter.}
{105}{}{Du möter en Enighetspatrull som slåss mot skurkar.}
{106}{}{Du möter en Enighetspatrull som slåss mot vargar.}
{107}{}{Du möter en Enighetspatrull.}
{150}{}{Du möter slavhandlare och hundar.}
{151}{}{Du möter slavhandlare.}
{152}{}{Du möter gyllene geckoödlor.}
{153}{}{Du möter vildhundar.}
{154}{}{Du möter en patrull och hundar som slåss mot slavhandlare.}
{155}{}{Du möter slavhandlare som slåss mot gyllene geckoödlor.}
{156}{}{Du möter en patrull som slåss mot slavhandlare.}
{157}{}{Du möter en patrull som slåss mot gyllene geckoödlor.}
{158}{}{Du möter en patrull som slåss mot vildhundar.}
{159}{}{Du möter en patrull.}
{200}{}{Du blir överfallen av plundrare.}
{201}{}{Du möter vargar.}
{202}{}{Du möter en karavan som försvarar sig mot plundrare.}
{203}{}{Du möter en karavan som försvarar sig mot plundrare.}
{204}{}{Du möter en karavan som försvarar sig mot plundrare}
{205}{}{Du möter en karavan som försvarar sig mot plundrare.}
{206}{}{Du möter en karavan.}
{207}{}{Du möter en karavan.}
{208}{}{Du möter en karavan.}
{209}{}{Du möter en karavan.}
{250}{}{Du möter marodörer.}
{251}{}{Du möter vargar.}
{252}{}{Du möter radioaktiva skorpioner.}
{253}{}{Du möter en karavan som försvarar sig mot marodörer.}
{254}{}{Du möter en karavan som försvarar sig mot marodörer.}
{255}{}{Du möter en karavan som försvarar sig mot vargar.}
{256}{}{Du möter en karavan som försvarar sig mot radioaktiva skorpioner.}
{257}{}{Du möter en karavan.}
{258}{}{Du möter en karavan.}
{259}{}{Du möter en karavan.}
{260}{}{Du möter en karavan.}
{261}{}{Du möter en resenär.}
{300}{}{Du möter rester av Mästarens armé.}
{301}{}{Du möter marodörer.}
{302}{}{You encounter NCR Rangers battling remnants of the Master's army.}
{303}{}{You encounter NCR Rangers fighting marauders.}
{304}{}{Du möter bönder som försvarar sig mot rester av Mästarens armé.}
{305}{}{Du möter bönder som försvarar sig mot marodörer.}
{306}{}{You encounter NCR Rangers.}
{307}{}{Du möter bönder.}
{350}{}{Du möter en slavhandlarkaravan.}
{351}{}{Du möter stråtrövare och rånare.}
{352}{}{Du möter stråtrövare.}
{353}{}{Du möter rånare.}
{354}{}{Du möter en karavan som försvarar sig mot stråtrövare.}
{355}{}{Du möter en karavan som slåss mot rånare.}
{356}{}{Du möter en karavan som slåss mot stråtrövare.}
{357}{}{Du möter en karavan belägrad av rånare.}
{358}{}{Du möter en slavkaravan som slåss mot en karavan.}
{359}{}{Du möter stråtrövare som slåss mot rånare.}
{360}{}{Du möter en karavan.}
{361}{}{Du möter en karavan.}
{400}{}{Du möter stråtrövare.}
{401}{}{Du möter rånare.}
{402}{}{Du möter rånare och stråtrövare.}
{403}{}{Du möter gyllene geckoödlor och radioaktiva skorpioner.}
{404}{}{Du möter gyllene geckoödlor.}
{405}{}{You encounter mole rats and pig rats.}
{406}{}{Du möter radioaktiva skorpioner.}
{407}{}{Du möter sporväxter.}
{408}{}{Du möter rånare som slåss mot stråtrövare.}
{409}{}{Du möter en karavan som försvarar sig mot stråtrövare.}
{410}{}{Du stöter på en karavan som försvarar sig mot rånare.}
{411}{}{Du möter en karavan som försvarar sig mot radioaktiva skorpioner.}
{412}{}{Du möter geckoödlor som slåss mot radioaktiva skorpioner.}
{413}{}{Du möter en karavan.}
{450}{}{Du möter stråtrövare och rånare.}
{451}{}{Du möter stråtrövare och geckoödlor.}
{452}{}{Du möter gyllene geckoödlor.}
{453}{}{Du möter radioaktiva skorpioner och sporväxter.}
{454}{}{Du möter rånare som slåss mot radioaktiva skorpioner.}
{455}{}{Du möter radioaktiva skorpioner som slåss mot rånare.}
{456}{}{Du möter en karavan som försvarar sig mot stråtrövare.}
{457}{}{Du stöter på en karavan som försvarar sig mot rånare.}
{458}{}{Du möter några stråtrövare som rensar bort några sporväxter.}
{459}{}{Du möter en karavan.}
{500}{}{Du möter stråtrövare och vildhundar.}
{501}{}{Du möter rånare och vildhundar.}
{502}{}{Du möter rånare.}
{503}{}{Du möter stråtrövare.}
{504}{}{Du möter en svärm med bönsyrsor och några sporväxter.}
{505}{}{Du möter hundar och sporväxter.}
{506}{}{Du möter en svärm med bönsyrsor.}
{507}{}{Du möter vildhundar.}
{508}{}{Du möter rånare som slåss mot hundar.}
{509}{}{Du möter en karavan som försvarar sig mot hundar.}
{510}{}{Du stöter på en karavan som försvarar sig mot rånare.}
{511}{}{Du möter en karavan som försvarar sig mot stråtrövare.}
{512}{}{Du möter en karavan.}
{550}{}{Du stöter på geckoödlor och vargar.}
{551}{}{You encounter claim jumpers.}
{552}{}{Du möter vargar.}
{553}{}{Du möter gyllene geckoödlor.}
{554}{}{You encounter prospectors fending off claim jumpers.}
{555}{}{Du möter jägare som jagar geckoödlor.}
{556}{}{Du möter förfalskare som slåss mot vargar.}
{557}{}{You encounter homesteaders fighting claim jumpers}
{558}{}{Du möter hemvändare som slåss mot vargar.}
{559}{}{Du möter förfalskare.}
{560}{}{Du möter jägare.}
{561}{}{Du möter prospektörer.}
{600}{}{Du möter dödsklor.}
{601}{}{Du möter eldsprutande geckoödlor.}
{602}{}{Du möter en karavan som flyr från dödsklor.}
{603}{}{Du möter en karavan som strider mot dödsklor.}
{604}{}{Du möter en karavan som strider mot eldsprutande geckoödlor.}
{605}{}{Du möter en karavan som strider mot eldsprutande geckoödlor.}
{606}{}{Du möter en karavan.}
{607}{}{Du möter en karavan.}
{608}{}{Du möter en karavan.}
{609}{}{Du möter en karavan.}
{650}{}{Du möter utomjordingar och dödsklor.}
{651}{}{Man möter kentaurer och svävare.}
{652}{}{Du möter eldsprutande geckoödlor.}
{653}{}{Du möter utomjordingar.}
{654}{}{Du möter dödsklor.}
{655}{}{Du möter eldsprutande geckoödlor.}
{656}{}{Du möter utomjordingar.}
{657}{}{Du möter kentaurer.}
{658}{}{Du möter svävare.}
{700}{}{Du möter några Yakuza-medlemmar.}
{701}{}{Du möter ett gäng.}
{702}{}{Du möter några vargar.}
{703}{}{Du möter några gangstrar som slåss mot några Yakuza.}
{704}{}{Du möter några gangstrar som slåss mot ett gäng.}
{705}{}{Du möter några gangstrar.}
{706}{}{Du möter en resenär.}
{750}{}{Du stöter på en karavan som driver bort rester av Mästarens armé.}
{751}{}{Du möter en karavan som slåss mot rester av mästarens armé.}
{752}{}{Du möter en karavan som strider mot dödsklor.}
{753}{}{Du möter en karavan.}
{754}{}{Du möter en karavan.}
{755}{}{Du möter en karavan.}
