{100}{}{Du möter skurkar och vargar.}
{101}{}{Du möter skurkar.}
{102}{}{Du möter vargar.}
{103}{}{You encounter radscorpions.}
{104}{}{Du möter sporväxter.}
{105}{}{Du möter en Enighetspatrull som slåss mot skurkar.}
{106}{}{Du möter en Enighetspatrull som slåss mot vargar.}
{107}{}{Du möter en Enighetspatrull.}
{150}{}{Du möter slavhandlare och hundar.}
{151}{}{Du möter slavhandlare.}
{152}{}{Du möter gyllene geckoödlor.}
{153}{}{Du möter vilda hundar.}
{154}{}{Du möter en patrull och hundar som slåss mot slavhandlare.}
{155}{}{Du möter slavhandlare som slåss mot gyllene geckoödlor.}
{156}{}{Du möter en patrull som slåss mot slavhandlare.}
{157}{}{Du möter en patrull som slåss mot gyllene geckoödlor.}
{158}{}{Du möter en patrull som slåss mot vilda hundar.}
{159}{}{Du möter en patrull.}
{200}{}{Du blir överfallen av plundrare.}
{201}{}{Du möter vargar.}
{202}{}{Du möter en karavan som försvarar sig mot plundrare.}
{203}{}{Du möter en karavan som försvarar sig mot plundrare.}
{204}{}{Du möter en karavan som försvarar sig mot plundrare}
{205}{}{Du möter en karavan som försvarar sig mot plundrare.}
{206}{}{Du möter en karavan.}
{207}{}{Du möter en karavan.}
{208}{}{Du möter en karavan.}
{209}{}{Du möter en karavan.}
{250}{}{You encounter marauders.}
{251}{}{Du möter vargar.}
{252}{}{You encounter radscorpions.}
{253}{}{You encounter a caravan fending off marauders.}
{254}{}{You encounter a caravan fending off marauders.}
{255}{}{You encounter a caravan fending off wolves.}
{256}{}{You encounter a caravan fending off radscorpions.}
{257}{}{Du möter en karavan.}
{258}{}{Du möter en karavan.}
{259}{}{Du möter en karavan.}
{260}{}{Du möter en karavan.}
{261}{}{You encounter a traveler.}
{300}{}{You encounter remnants of the Master's army.}
{301}{}{You encounter marauders.}
{302}{}{You encounter NCR Rangers battling remnants of the Master's army.}
{303}{}{You encounter NCR Rangers fighting marauders.}
{304}{}{You encounter farmers fending off remnants of the Master's army.}
{305}{}{You encounter farmers fending off marauders.}
{306}{}{You encounter NCR Rangers.}
{307}{}{You encounter farmers.}
{350}{}{You encounter a slaver caravan.}
{351}{}{You encounter highwaymen and robbers.}
{352}{}{You encounter highwaymen.}
{353}{}{You encounter robbers.}
{354}{}{You encounter a caravan fending off highwaymen.}
{355}{}{You encounter a caravan fighting robbers.}
{356}{}{You encounter a caravan fighting highwaymen.}
{357}{}{You encounter a caravan besieged by robbers.}
{358}{}{You encounter a slave caravan fighting a caravan.}
{359}{}{You encounter highwaymen fighting robbers.}
{360}{}{Du möter en karavan.}
{361}{}{Du möter en karavan.}
{400}{}{You encounter highwaymen.}
{401}{}{You encounter robbers.}
{402}{}{You encounter robbers and highwaymen.}
{403}{}{You encounter golden geckos and radscorpions.}
{404}{}{Du möter gyllene geckoödlor.}
{405}{}{You encounter mole rats and pig rats.}
{406}{}{You encounter radscorpions.}
{407}{}{Du möter sporväxter.}
{408}{}{You encounter robbers fighting highwaymen.}
{409}{}{You encounter a caravan fending off highwaymen.}
{410}{}{You encounter a caravan fending off robbers.}
{411}{}{You encounter a caravan fending off radscorpions.}
{412}{}{You encounter geckos fighting radscorpions.}
{413}{}{Du möter en karavan.}
{450}{}{You encounter highwaymen and robbers.}
{451}{}{You encounter highwaymen and geckos.}
{452}{}{Du möter gyllene geckoödlor.}
{453}{}{You encounter radscorpions and spore plants.}
{454}{}{You encounter robbers fighting radscorpions.}
{455}{}{You encounter radscorpions fighting robbers.}
{456}{}{You encounter a caravan fending off highwaymen.}
{457}{}{You encounter a caravan fending off robbers.}
{458}{}{You encounter some highwaymen weeding out some spore plants.}
{459}{}{Du möter en karavan.}
{500}{}{You encounter highwaymen and wild dogs.}
{501}{}{You encounter robbers and wild dogs.}
{502}{}{You encounter robbers.}
{503}{}{You encounter highwaymen.}
{504}{}{You encounter a swarm of mantis and some spore plants.}
{505}{}{You encounter dogs and spore plants.}
{506}{}{You encounter a swarm of mantis.}
{507}{}{Du möter vilda hundar.}
{508}{}{You encounter robbers fighting dogs.}
{509}{}{You encounter a caravan fending off dogs.}
{510}{}{You encounter a caravan fending off robbers.}
{511}{}{You encounter a caravan fending off highwaymen.}
{512}{}{Du möter en karavan.}
{550}{}{Du stöter på geckoödlor och vargar.}
{551}{}{You encounter claim jumpers.}
{552}{}{Du möter vargar.}
{553}{}{Du möter gyllene geckoödlor.}
{554}{}{You encounter prospectors fending off claim jumpers.}
{555}{}{Du möter jägare som jagar geckoödlor.}
{556}{}{Du möter förfalskare som slåss mot vargar.}
{557}{}{You encounter homesteaders fighting claim jumpers}
{558}{}{Du möter hemvändare som slåss mot vargar.}
{559}{}{Du möter förfalskare.}
{560}{}{Du möter jägare.}
{561}{}{Du möter prospektörer.}
{600}{}{You encounter deathclaws.}
{601}{}{Du möter eldsprutande geckoödlor.}
{602}{}{Du möter en karavan som flyr från dödsklor.}
{603}{}{Du möter en karavan som strider mot dödsklor.}
{604}{}{Du möter en karavan som strider mot eldsprutande geckoödlor.}
{605}{}{Du möter en karavan som strider mot eldsprutande geckoödlor.}
{606}{}{Du möter en karavan.}
{607}{}{Du möter en karavan.}
{608}{}{Du möter en karavan.}
{609}{}{Du möter en karavan.}
{650}{}{Du möter utomjordingar och dödsklor.}
{651}{}{Man möter kentaurer och svävare.}
{652}{}{Du möter eldsprutande geckoödlor.}
{653}{}{Du möter utomjordingar.}
{654}{}{You encounter deathclaws.}
{655}{}{Du möter eldsprutande geckoödlor.}
{656}{}{Du möter utomjordingar.}
{657}{}{Du möter kentaurer.}
{658}{}{Du möter svävare.}
{700}{}{Du möter några Yakuza-medlemmar.}
{701}{}{Du möter ett gäng.}
{702}{}{Du möter några vargar.}
{703}{}{You encounter some mobsters fighting some Yakuza.}
{704}{}{Du möter några gangstrar som slåss mot ett gäng.}
{705}{}{Du möter några gangstrar.}
{706}{}{You encounter a traveler.}
{750}{}{Du stöter på en karavan som driver bort resterna av Mästarens armé.}
{751}{}{Du möter en karavan som slåss mot rester av mästarens armé.}
{752}{}{Du möter en karavan som strider mot dödsklor.}
{753}{}{Du möter en karavan.}
{754}{}{Du möter en karavan.}
{755}{}{Du möter en karavan.}
