{100}{}{Du ser en datorterminal.}
{101}{}{You see the power center computer terminal.}
{102}{}{Du ser en vanlig datorterminal. Den ser ut att fungera och vara redo för inmatning.}
{103}{}{This terminal monitors the power generator. It indicates that everything is functioning
 normally.}
{104}{}{This terminal monitors the power generator. It indicates that the unit is off line due to a
 malfunction of some sort.}
{105}{}{Färdigt.}
