{100}{}{Du ser en datorterminal.}
{101}{}{You see the control center computer terminal.}
{102}{}{Du ser en vanlig datorterminal. Den ser ut att fungera och vara redo för inmatning.}
{103}{}{The terminal indicates that the security force field at the vault entrance has been activated
 now that power has been restored.}
{104}{}{The terminal indicates that all security systems in the vault are off line due to power
 failure.}
{105}{}{Turn the force field off.}
{106}{}{Turn the force field on.}
{107}{}{Färdigt.}
{108}{}{You give the command to deactivate the force field.}
{109}{}{Färdigt.}
{110}{}{You give the command to activate the force field.}
{111}{}{Färdigt.}
{112}{}{The terminal indicates that the field is off by manual override.}
{113}{}{The terminal indicates that the field system has been compromised.}
{114}{}{The terminal indicates that the field system is off.}
