{100}{}{Du ser en datorterminal.}
{101}{}{Du ser Darions datorterminal.}
{102}{}{Du ser en vanlig datorterminal. Den ser ut att fungera och vara redo för inmatning.}
{103}{}{You access the computer and quickly scan all available files. Among some personal journal
 entries, you find several detailed reports on the NCR. It seems there is a spy on their council.
 You copy the reports to a holodisk.}
{104}{}{Du har problem med att komma åt filerna.}
{105}{}{Färdigt.}
{106}{}{Other than the information about the NCR spy, the computer contains no useful information.}
{107}{}{Färdigt.}
