{100}{}{Du ser en datorterminal.}
{101}{}{Du ser bibliotekets datorterminal.}
{102}{}{Du ser en vanlig datorterminal. Den ser ut att fungera och vara redo för inmatning.}
{103}{}{Du går in i datorn och skannar snabbt alla tillgängliga filer. Du hittar platsen för Valv 13
 och kopierar det till din PIPP-Pojke.}
{104}{}{Du har problem med att komma åt filerna.}
{106}{}{Förutom platsen för Valv 13 innehåller datorn ingen användbar information.}
