{100}{}{Du ser en datorterminal.}
{101}{}{Du ser elcentralens datorterminal.}
{102}{}{Du ser en vanlig datorterminal. Den ser ut att fungera och vara redo för inmatning.}
{103}{}{Denna terminal övervakar elcentralen. Den indikerar att allting fungerar
 normalt.}
{104}{}{Denna terminal övervakar elcentralen. Den indikerar att enheten är avstängd på grund av
 någon typ av funktionsfel.}
{105}{}{Färdigt.}
