{100}{}{Du ser en datorterminal.}
{101}{}{You see the security computer terminal.}
{102}{}{Du ser en vanlig datorterminal. Den ser ut att fungera och vara redo för inmatning.}
{103}{}{This terminal monitors the force field generators. It indicates that everything is functioning
 normally.}
{104}{}{This terminal monitors the force field generators. It indicates that the unit is off line due
 to power failure.}
{105}{}{Turn the force field off.}
{106}{}{Turn the force field on.}
{107}{}{Färdigt.}
{108}{}{You give the command to deactivate the force field.}
{109}{}{Du verkar inte kunna komma runt säkerhetskoderna för att avaktivera kraftfältet.}
{110}{}{Färdigt.}
{111}{}{You give the command to activate the force field.}
{112}{}{Du verkar inte kunna komma runt säkerhetskoderna för att aktivera kraftfältet.}
{113}{}{Färdigt.}
{114}{}{Denna terminal övervakar kraftfältsgeneratorerna. Den indikerar att kraftfältet är avstängt.}
{115}{}{Denna terminal övervakar kraftfältsgeneratorerna. Den indikerar att kraftfältet är
 temporärt avstängt.}
{116}{}{Denna terminal övervakar kraftfältsgeneratorerna. Den indikerar att kraftfältet 
 äventyrats.}
