{100}{}{Du ser en trädörr.}
{101}{}{Du ser en metalldörr.}
{102}{}{You see a sturdy door with a lock, which can be picked with
 lockpicks, and a highly explosive trap in the doorframe, which
 you may be able to pry open.}
{103}{}{Du ser en robust dörr med ett lås på och en högexplosiv 
 fälla i dörrkarmen, som du kanske kan
 bända upp.}
{104}{}{Du ser en robust dörr utan uppenbar låsanordning och
 en högexplosiv fälla i dörrkarmen, som du kanske kan
 bända upp.}
{105}{}{Du ser en robust dörr med ett gammalt rostigt lås och en högexplosiv 
 fälla i dörrkarmen, som du kanske kan bända 
 upp.}
{106}{}{Du ser en robust dörr med ett lås (som kan öppnas 
 med dyrkar) och en fälla i dörrkarmen, som du kanske kan
 bända upp.}
{107}{}{Du ser en robust dörr med ett lås på och en fälla i
 dörrkarmen, som du kanske kan bända upp.}
{108}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en fälla i dörrkarmen, som du kanske kan bända upp.}
{109}{}{Du ser en robust dörr med ett gammalt, rostigt lås och en fälla
 i dörrkarmen, som du kanske kan bända upp.}
{110}{}{You see a sturdy door with a lock, which can be picked with
 lockpicks, and a cut wire in the doorframe, which you may be
 able to pry open.}
{111}{}{Du ser en robust dörr med ett lås på och en avklippt sladd
 i dörrkarmen, som du kanske kan bända upp.}
{112}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en avklippt sladd i dörrkarmen, som du kanske kan bända
 upp.}
{113}{}{Du ser en robust dörr med ett gammalt, rostigt lås och en avklippt
 sladd i dörrkarmen, som du kanske kan bända upp.}
{114}{}{Du ser en robust dörr med ett lås (som kan dyrkas upp med
 dyrkar), som du kanske kan bända upp.}
{115}{}{Du ser en robust dörr med ett lås på, som du kanske kan
 bända upp.}
{116}{}{Du ser en robust dörr utan synbar låsanordning,
 som du kanske kan bända upp.}
{117}{}{Du ser en robust dörr med ett gammalt rostigt lås som
 du kanske kan bända upp.}
{118}{}{You see a sturdy door with a lock, which can be picked with
 lockpicks, and a highly explosive trap in the doorframe.}
{119}{}{Du ser en robust dörr med ett lås på och en högexplosiv
 fälla i dörrkarmen.}
{120}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en högexplosiv fälla i dörrkarmen.}
{121}{}{Du ser en robust dörr med ett gammalt rostigt lås och en högexplosiv
 fälla i dörrkarmen.}
{122}{}{You see a sturdy door with a lock, which can be picked with
 lockpicks, and a trap in the doorframe.}
{123}{}{You see a sturdy door with a lock on it and a trap in
 the doorframe.}
{124}{}{You see a sturdy door with no apparent locking device and
 a trap in the doorframe.}
{125}{}{You see a sturdy door with an old, rusty lock and a trap
 in the doorframe.}
{126}{}{You see a sturdy door with a lock, which can be picked with
 lockpicks, and a cut wire in the doorframe.}
{127}{}{You see a sturdy door with a lock on it and a severed wire
 in the doorframe.}
{128}{}{You see a sturdy door with no apparent locking device and
 a severed wire in the doorframe.}
{129}{}{You see a sturdy door with an old, rusty lock and a cut
 wire in the doorframe.}
{130}{}{You see a sturdy door with a lock, which can be picked with
 lockpicks, on it.}
{131}{}{You see a sturdy door with a lock on it.}
{132}{}{Du ser en robust dörr utan någon uppenbar låsanordning.}
{133}{}{Du ser en robust dörr med ett gammalt, rostigt lås.}
{134}{}{You see a damaged door with a lock, which can be picked with
 lockpicks, and a highly explosive trap in the doorframe.}
{135}{}{You see a damaged door with a lock on it and a highly
 explosive trap in the doorframe.}
{136}{}{You see a damaged door with no apparent locking device and
 a highly explosive trap in the doorframe.}
{137}{}{You see a damaged door with an old, rusty lock and a highly
 explosive trap in the doorframe.}
{138}{}{You see a damaged door with a lock, which can be picked with
 lockpicks, and a trap in the doorframe.}
{139}{}{You see a damaged door with a lock on it and a trap in
 the doorframe.}
{140}{}{You see a damaged door with no apparent locking device and
 a trap in the doorframe.}
{141}{}{You see a damaged door with an old, rusty lock and a trap
 in the doorframe.}
{142}{}{You see a damaged door with a lock, which can be picked with
 lockpicks, and a cut wire in the doorframe.}
{143}{}{You see a damaged door with a lock on it and a severed wire
 in the doorframe.}
{144}{}{You see a damaged door with no apparent locking device and
 a severed wire in the doorframe.}
{145}{}{You see a damaged door with an old, rusty lock and a cut
 wire in the doorframe.}
{146}{}{You see a damaged door with a lock, which can be picked with
 lockpicks.}
{147}{}{You see a damaged door with a lock on it.}
{148}{}{You see a damaged door with no apparent locking device.}
{149}{}{Du ser en skadad dörr med ett gammalt, rostigt lås.}
{150}{}{You see an old door with a lock, which can be picked with
 lockpicks, and a highly explosive trap in the doorframe.}
{151}{}{You see an old door with a lock on it and a highly
 explosive trap in the doorframe.}
{152}{}{You see an old door with no apparent locking device and
 a highly explosive trap in the doorframe.}
{153}{}{You see an old door with an old, rusty lock and a highly
 explosive trap in the doorframe.}
{154}{}{You see an old door with a lock, which can be picked with
 lockpicks, and a trap in the doorframe.}
{155}{}{You see an old door with a lock on it and a trap in
 the doorframe.}
{156}{}{You see an old door with no apparent locking device and
 a trap in the doorframe.}
{157}{}{You see an old door with an old, rusty lock and a trap
 in the doorframe.}
{158}{}{You see an old door with a lock, which can be picked with
 lockpicks, and a cut wire in the doorframe.}
{159}{}{You see an old door with a lock on it and a severed wire
 in the doorframe.}
{160}{}{You see an old door with no apparent locking device and
 a severed wire in the doorframe.}
{161}{}{You see an old door with an old, rusty lock and a cut
 wire in the doorframe.}
{162}{}{You see an old door with a lock, which can be picked with
 lockpicks,.}
{163}{}{You see an old door with a lock on it.}
{164}{}{You see an old door with no apparent locking device.}
{165}{}{You see an old door with an old, rusty lock.}
{166}{}{You set off the trap and were hit for }
{167}{}{ points of damage.}
{168}{}{ sets off the trap and was hit for }
{169}{}{ points of damage.}
{170}{}{You deftly pick the lock on the door.}
{171}{}{Your lack of skill has jammed the lock on this door.}
{172}{}{You fail to pick the lock on this door.}
{173}{}{ deftly picks the lock on the door.}
{174}{}{'s lack of skill has jammed the lock on this door.}
{175}{}{ failed to pick the lock on this door.}
{176}{}{You bust the lock off the door.}
{177}{}{While trying to bust the lock, you strain your back and
 take a point of damage.}
{178}{}{While trying to bust the lock, you strain your back and
 take }
{179}{}{ points of damage.}
{180}{}{You are too weak to bust the lock.}
{181}{}{ busts the lock off the door.}
{182}{}{ strains his back while trying to bust the lock and takes
 a point of damage.}
{183}{}{ strains his back while trying to bust the lock and takes }
{184}{}{ points of damage.}
{185}{}{ is too weak to bust the lock.}
{186}{}{ strains her back while trying to bust the lock and takes
 a point of damage.}
{187}{}{ strains her back while trying to bust the lock and takes }
{188}{}{ points of damage.}
{189}{}{You deftly lock the door.}
{190}{}{You fail to lock the door.}
{191}{}{ deftly locks the door.}
{192}{}{ failed to lock the door.}
{193}{}{The explosives don't even put a scratch on the door.}
{194}{}{You find a trap on the door.}
{195}{}{You fail to find any traps on the door.}
{196}{}{You skillfully disarm the trap.}
{198}{}{You fail to disarm the trap.}
{199}{}{ finds a trap on the door.}
{200}{}{ fails to find any traps on the door.}
{201}{}{ skillfully disarms the trap.}
{202}{}{ fails to disarm the trap.}
{203}{}{The door appears to be locked. It looks like it takes some kind of thin card as a key.}
{204}{}{You hear the crackling of electricity running through the door.}
{205}{}{ notices the crackling of electricity running through the door.}
{206}{}{You are unable to place a trap on this door because
 the door is open.}
{207}{}{ is unable to place a trap on this door because the
 door is open.}
{208}{}{You skillfully set a trap in the door frame.}
{209}{}{You fail to set the trap properly in the door frame.}
{210}{}{ skillfully sets a trap in the door frame.}
{211}{}{ fails to set the trap properly in the door frame.}
{300}{}{Du låser upp dörren.}
{301}{}{Du låser dörren.}
{302}{}{Du kan inte låsa den här dörren medan den är öppen.}
{303}{}{Den nyckeln passar inte i det här låset.}
{320}{}{Det finns inget sätt att låsa den här dörren.}
{400}{}{Du låser upp dörren.}
{500}{}{There is no way to untrap the door.}
