{100}{}{Du ser en trädörr.}
{101}{}{Du ser en metalldörr.}
{102}{}{Du ser en robust dörr med ett lås som kan dyrkas upp med
 dyrkar och en högexplosiv fälla i dörrkarmen, som
 du kanske kan bända upp.}
{103}{}{Du ser en robust dörr med ett lås på och en högexplosiv 
 fälla i dörrkarmen, som du kanske kan
 bända upp.}
{104}{}{Du ser en robust dörr utan uppenbar låsanordning och
 en högexplosiv fälla i dörrkarmen, som du kanske kan
 bända upp.}
{105}{}{Du ser en robust dörr med ett gammalt rostigt lås och en högexplosiv 
 fälla i dörrkarmen, som du kanske kan bända 
 upp.}
{106}{}{Du ser en robust dörr med ett lås (som kan öppnas 
 med dyrkar) och en fälla i dörrkarmen, som du kanske kan
 bända upp.}
{107}{}{Du ser en robust dörr med ett lås på och en fälla i
 dörrkarmen, som du kanske kan bända upp.}
{108}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en fälla i dörrkarmen, som du kanske kan bända upp.}
{109}{}{Du ser en robust dörr med ett gammalt, rostigt lås och en fälla
 i dörrkarmen, som du kanske kan bända upp.}
{110}{}{Du ser en robust dörr med ett lås som kan öppnas med
 dyrkar och en klippt sladd i dörrkarmen, som du kanske kan
 bända upp.}
{111}{}{Du ser en robust dörr med ett lås på och en avklippt sladd
 i dörrkarmen, som du kanske kan bända upp.}
{112}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en avklippt sladd i dörrkarmen, som du kanske kan bända
 upp.}
{113}{}{Du ser en robust dörr med ett gammalt, rostigt lås och en avklippt
 sladd i dörrkarmen, som du kanske kan bända upp.}
{114}{}{Du ser en robust dörr med ett lås (som kan dyrkas upp med
 dyrkar), som du kanske kan bända upp.}
{115}{}{Du ser en robust dörr med ett lås på, som du kanske kan
 bända upp.}
{116}{}{Du ser en robust dörr utan synbar låsanordning,
 som du kanske kan bända upp.}
{117}{}{Du ser en robust dörr med ett gammalt rostigt lås som
 du kanske kan bända upp.}
{118}{}{You see a sturdy door with a lock, which can be picked with
 lockpicks, and a highly explosive trap in the doorframe.}
{119}{}{Du ser en robust dörr med ett lås på och en högexplosiv
 fälla i dörrkarmen.}
{120}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en högexplosiv fälla i dörrkarmen.}
{121}{}{Du ser en robust dörr med ett gammalt rostigt lås och en högexplosiv
 fälla i dörrkarmen.}
{122}{}{You see a sturdy door with a lock, which can be picked with
 lockpicks, and a trap in the doorframe.}
{123}{}{Du ser en robust dörr med ett lås på och en fälla i
 dörrkarmen.}
{124}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en fälla i dörrkarmen.}
{125}{}{Du ser en robust dörr med ett gammalt, rostigt lås och en fälla
 i dörrkarmen.}
{126}{}{You see a sturdy door with a lock, which can be picked with
 lockpicks, and a cut wire in the doorframe.}
{127}{}{Du ser en robust dörr med ett lås på och en avklippt sladd
 i dörrkarmen.}
{128}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en avklippt sladd i dörrkarmen.}
{129}{}{Du ser en robust dörr med ett gammalt, rostigt lås och en avklippt
 sladd i dörrkarmen.}
{130}{}{You see a sturdy door with a lock, which can be picked with
 lockpicks, on it.}
{131}{}{Du ser en robust dörr med ett lås på.}
{132}{}{Du ser en robust dörr utan någon uppenbar låsanordning.}
{133}{}{Du ser en robust dörr med ett gammalt, rostigt lås.}
{134}{}{You see a damaged door with a lock, which can be picked with
 lockpicks, and a highly explosive trap in the doorframe.}
{135}{}{Du ser en skadad dörr med ett lås på och en högexplosiv
 fälla i dörrkarmen.}
{136}{}{Du ser en skadad dörr utan någon uppenbar låsanordning och
 en högexplosiv fälla i dörrkarmen.}
{137}{}{Du ser en robust dörr med ett gammalt rostigt lås och en högexplosiv
 fälla i dörrkarmen.}
{138}{}{You see a damaged door with a lock, which can be picked with
 lockpicks, and a trap in the doorframe.}
{139}{}{Du ser en skadad dörr med ett lås på och en fälla i
 dörrkarmen.}
{140}{}{Du ser en skadad dörr utan någon uppenbar låsanordning och
 en fälla i dörrkarmen.}
{141}{}{Du ser en skadad dörr med ett gammalt, rostigt lås och en fälla
 i dörrkarmen.}
{142}{}{Du ser en skadad dörr med ett lås som kan dyrkas upp med
 dyrkar och en avklippt tråd i dörrkarmen.}
{143}{}{Du ser en skadad dörr med ett lås på och en avklippt sladd
 i dörrkarmen.}
{144}{}{Du ser en skadad dörr utan någon uppenbar låsanordning och
 en avklippt sladd i dörrkarmen.}
{145}{}{Du ser en skadad dörr med ett gammalt, rostigt lås och en avklippt
 sladd i dörrkarmen.}
{146}{}{You see a damaged door with a lock, which can be picked with
 lockpicks.}
{147}{}{Du ser en skadad dörr med ett lås på.}
{148}{}{Du ser en skadad dörr utan synbar låsanordning.}
{149}{}{Du ser en skadad dörr med ett gammalt, rostigt lås.}
{150}{}{You see an old door with a lock, which can be picked with
 lockpicks, and a highly explosive trap in the doorframe.}
{151}{}{Du ser en gammal dörr med ett lås på och en högexplosiv
 fälla i dörrkarmen.}
{152}{}{Du ser en gammal dörr utan någon uppenbar låsanordning och
 en högexplosiv fälla i dörrkarmen.}
{153}{}{Du ser en gammal dörr med ett gammalt rostigt lås och en högexplosiv
 fälla i dörrkarmen.}
{154}{}{You see an old door with a lock, which can be picked with
 lockpicks, and a trap in the doorframe.}
{155}{}{Du ser en gammal dörr med ett lås på och en fälla i.
 dörrkarmen.}
{156}{}{Du ser en gammal dörr utan någon uppenbar låsanordning och
 en fälla i dörrkarmen.}
{157}{}{Du ser en gammal dörr med ett gammalt, rostigt lås och en fälla
 i dörrkarmen.}
{158}{}{You see an old door with a lock, which can be picked with
 lockpicks, and a cut wire in the doorframe.}
{159}{}{Du ser en gammal dörr med ett lås på och en avklippt sladd
 i dörrkarmen.}
{160}{}{Du ser en gammal dörr utan någon uppenbar låsanordning och
 en avklippt sladd i dörrkarmen.}
{161}{}{Du ser en gammal dörr med ett gammalt, rostigt lås och en avklippt
 sladd i dörrkarmen.}
{162}{}{You see an old door with a lock, which can be picked with
 lockpicks,.}
{163}{}{Du ser en gammal dörr med ett lås på.}
{164}{}{Du ser en gammal dörr utan någon uppenbar låsanordning.}
{165}{}{Du ser en gammal dörr med ett gammalt, rostigt lås.}
{166}{}{Du utlöser fällan och skadades }
{167}{}{ skadepoäng.}
{168}{}{ utlöser fällan och skadades }
{169}{}{ skadepoäng.}
{170}{}{Du dyrkar skickligt upp låset på dörren.}
{171}{}{Din oskicklighet har gjort låset på dörren obrukbart.}
{172}{}{Du lyckas inte dyrka upp låset på den här dörren.}
{173}{}{ dyrkar skickligt upp låset på dörren.}
{174}{}{s oskicklighet har gjort låset på dörren obrukbart.}
{175}{}{ misslyckades med att dyrka upp låset på den här dörren.}
{176}{}{Du slår bort låset från dörren.}
{177}{}{While trying to bust the lock, you strain your back and
 take a point of damage.}
{178}{}{While trying to bust the lock, you strain your back and
 take }
{179}{}{ skadepoäng.}
{180}{}{Du är för svag för att bryta upp låset.}
{181}{}{ slår bort låset från dörren.}
{182}{}{ sträcker ryggen när han försöker bryta upp låset och skadas
 ett hälsopoäng.}
{183}{}{ sträcker ryggen när han försöker bryta upp låset och skadas }
{184}{}{ skadepoäng.}
{185}{}{ är för svag för att bryta upp låset.}
{186}{}{ sträcker ryggen när hon försöker bryta upp låset och skadas
 ett hälsopoäng.}
{187}{}{ sträcker ryggen när hon försöker bryta upp låset och skadas }
{188}{}{ skadepoäng.}
{189}{}{Du låser skickligt dörren.}
{190}{}{Du misslyckas med att låsa dörren.}
{191}{}{ låser skickligt dörren.}
{192}{}{ misslyckades med att låsa dörren.}
{193}{}{The explosives don't even put a scratch on the door.}
{194}{}{Du hittar en fälla på dörren.}
{195}{}{Du hittar inga fällor på dörren.}
{196}{}{Du avväpnar skickligt fällan.}
{198}{}{Du misslyckas med att desarmera fällan.}
{199}{}{ hittar en fälla på dörren.}
{200}{}{ hittar inga fällor på dörren.}
{201}{}{ avväpnar skickligt fällan.}
{202}{}{ misslyckas med att desarmera fällan.}
{203}{}{The door appears to be locked. It looks like it takes some kind of thin card as a key.}
{204}{}{You hear the crackling of electricity running through the door.}
{205}{}{ notices the crackling of electricity running through the door.}
{206}{}{You are unable to place a trap on this door because
 the door is open.}
{207}{}{ is unable to place a trap on this door because the
 door is open.}
{208}{}{Du gillrar skickligt en fälla i dörrkarmen.}
{209}{}{You fail to set the trap properly in the door frame.}
{210}{}{ gillrar skickligt en fälla i dörrkarmen.}
{211}{}{ fails to set the trap properly in the door frame.}
{300}{}{Du låser upp dörren.}
{301}{}{Du låser dörren.}
{302}{}{Du kan inte låsa den här dörren medan den är öppen.}
{303}{}{Den nyckeln passar inte i det här låset.}
{320}{}{Det finns inget sätt att låsa den här dörren.}
{400}{}{Du låser upp dörren.}
{500}{}{There is no way to untrap the door.}
