{100}{}{Generatorn fungerar normalt. Eltillförseln är optimalt.}
{101}{}{Generatorn verkar vara i standby-läge för nödsituationer. Eltillförseln är minimal.}
{102}{}{Försök att diagnostisera problemet.}
{103}{}{Åh, ja. Måste gå.}
{104}{}{There must have been a short in the system at some time. The emergency circuit breakers kicked
 in, but fused in the open position. You may be able to free them up and restore power.}
{105}{}{You can't seem to find anything wrong. It just doesn't work.}
{106}{}{Try to repair it.}
{107}{}{Time to leave.}
{108}{}{You manage to break the contacts loose and restore power!}
{109}{}{Damn. This is tougher than it looks.}
{110}{}{Färdigt.}
