{100}{}{Du ser någon i militäruniform.}
{101}{}{Du ser någon i militäruniform.}
{102}{}{Du ser någon som bär en militäruniform men som verkar vara mer en tekniker än en soldat.}
{103}{}{Hej. Hur går det?}
{104}{}{'Roger that, I've got you on the scope' -- sorry, but I'm in the middle of something right now.}
{105}{}{Jag kan inte prata just nu.}
{106}{}{Titta gärna runt, men rör inget.}
{107}{}{Är du galen som går omkring här utan uniform? Byt om!}
{108}{}{Om sergeanten ser dig utan uniform kommer han att spöa upp dig.}
{109}{}{Varför har du inte uniform på dig? }
{110}{}{Jävla skit! Vi har blivit invaderade! Varning!}
{111}{}{Inkräktare! Kalla på vakten!}
{112}{}{Vakt! Inkräktare i flygtrafikledningen!}
{113}{}{Läget? Är vi under attack?}
{114}{}{Varför går larmet? Vad händer?}
{115}{}{Vad i helvete är på gång?}
