{100}{}{Du ser en tekniker.}
{101}{}{Du ser en Enklav-tekniker.}
{102}{}{Du ser någon som bär en labbrock. Han verkar självsäker och trygg i sig själv.}
{103}{}{Ja, soldat?}
{104}{}{Jag ny här. Behöver ställa fråga.}
{105}{}{Me just say hi. Me go now.}
{106}{}{Jag är ny här och jag försöker bekanta mig med basen. Får jag ställa några frågor?}
{107}{}{Jag säger bara hej. Vi ses.}
{108}{}{Visst. Jag har några minuter.}
{109}{}{What can I help you with?}
{110}{}{Vad det här stället?}
{111}{}{Vad du jobb?}
{112}{}{Var Enklaven huvudbas någonstans?}
{113}{}{Jag leta Vertibird-ritningar. Var hittar jag?}
{117}{}{Jag gå ska nu.}
{118}{}{Vad är det här för ställe?}
{119}{}{Vad är ditt jobb här?}
{120}{}{Var ligger Enklavens huvudbas?}
{121}{}{Jag måste titta på Vertibird-planerna. Var förvaras de?}
{125}{}{Ingenting. Jag måste gå.}
{126}{}{Det här är flygtrafikledningen. Härifrån kan vi följa varje vertibirds rörelser.}
{127}{}{Jag se. Jag mer fråga.}
{128}{}{Okej, då. Ett par frågor till.}
{129}{}{Jag är en datatekniker, första klass. Jag upprätthåller länken till stordatorn nedan.}
{130}{}{Eh... visst.}
{131}{}{Bra. Fortsätt med det goda arbetet.}
{132}{}{Kom du inte därifrån?}
{133}{}{Eh... nej, jag komma från uppe i norr.}
{134}{}{Nej faktiskt, jag kommer norrifrån.}
{135}{}{Åh... Jag visste inte att vi hade en utpost där uppe. Hur som helst, huvudbasen ligger en bit utanför San Frans kust.}
{136}{}{Hur vi komma dit?}
{137}{}{Men... Hur kommer vi dit?}
{138}{}{Med vertibird, så klart. Det finns inget annat sätt, om du inte har ett skepp. Det är alldeles för långt att simma.}
{139}{}{Tack.}
{140}{}{Tack.}
{141}{}{Vertibird plans... I don't see why you would need to know that. I suggest you talk to maintenance next door.}
{142}{}{Okej.}
{143}{}{Got it.}
{153}{}{Are you nuts, walking around here out of uniform? Get suited up!}
{154}{}{Om sergeanten ser dig utan uniform kommer han att spöa upp dig.}
{155}{}{Varför har du inte uniform på dig? }
{156}{}{Jävla skit! Vi har blivit invaderade! Varning!}
{157}{}{Inkräktare! Kalla på vakten!}
{158}{}{Guard! Intruders in the comm center!}
{159}{}{Läget? Är vi under attack?}
{160}{}{Varför går larmet? Vad händer?}
{161}{}{Vad i helvete är på gång?}
{162}{}{I'm just a tech! Don't shoot me!}
{163}{}{I didn't sign up for combat, just tech training!}
{164}{}{This is a lab coat, not armor! I'm outta here!}
