{100}{}{Du ser en kock.}
{101}{}{Du ser Kakan, kocken.}
{102}{}{Du ser en man i rustning som bär en kockmössa och ett förkläde.}
{103}{}{Hej, soldat. Letar 'u efter lite käk eller bara någon att prata med?}
{104}{}{Jag vill mat ha.}
{105}{}{Jag prata vill.}
{106}{}{Jag äter gärna något.}
{107}{}{Vi kan snacka en stund.}
{108}{}{Här har du. Ta en blajja på en skyffel. Snön och flugskiten är där borta. Nåt annat?}
{109}{}{Vad du vill att jag äta?}
{110}{}{Skit? Snö? Vad fan är det här för mat?}
{111}{}{Jag är ledsen, du måste va' ny i armén. Ta inte illa upp för det jag sa, det är bara vad vi kallar saker här.
 Blajja på en skyffel är köttfärs på toast. Snö och flugskit är andra ord för salt och peppar.}
{112}{}{Åh... tack. Vi prata medan äter.}
{113}{}{Jag fattar, förlåt. Vi kan prata medan jag äter.}
{114}{}{Vad ville ru snacka om?}
{115}{}{What go on here?}
{116}{}{Where vertibird plans?}
{118}{}{Var huvudbas?}
{119}{}{Jag tillbaka i tjänst måste. Tack.}
{120}{}{Vad är på gång häromkring?}
{121}{}{I'm interested in the vertibirds. If I wanted to look at the plans, where could I find them?}
{123}{}{Var är Enklavens huvudbas?}
{124}{}{Tack. Jag måste återgå till min tjänstgöringsplats.}
{125}{}{Letar du efter lite skvaller? Jag kan ge dig det senaste om vad som händer i underhåll, medicinlabbet eller bland soldaterna.}
{126}{}{Vad ville ru höra?}
{127}{}{Hur är det med underhåll?}
{128}{}{Vad medicinlabb du vet?}
{129}{}{Vad soldater du vet?}
{130}{}{Nåt annat?}
{131}{}{Jag tillräckligt hört.}
{132}{}{Vad händer på underhållssidan?}
{133}{}{Vad kan du berätta om medicinlabbet?}
{134}{}{Hur är det med oss soldater?}
{135}{}{Händer det något annat?}
{136}{}{Jag har hört tillräckligt, tror jag.}
{137}{}{Raul, the vertibird mechanic, doesn't like Quincy, the head of maintenance. Those two are always
 getting into it. I don't think it's a case of professional rivalry either. Anyway, Raul's an arrogant
 ass but Quincy's an okay kind of guy. I hope he wins in the end.}
{138}{}{Okej.}
{139}{}{Ja, jag håller med.}
{140}{}{Med lab's been taken over by an Enclave egghead named Schreber. Mean son of a bitch; don't care
 for nothing or nobody. He's been doing some sort of experiments on deathclaws down there, don't know
 what though. Anyway, he was making all kinds of noise until the commander ordered the room soundproofed.}
{141}{}{Jag förstår.}
{142}{}{That's interesting. }
{143}{}{Ha! We're talking romance, my friend. It seems one of the computer geeks has fallen for one of the grunts, the guard outside med lab. Even has one of those cutesy names for her. Calls her "Snookie" of all things.}
{144}{}{Gulligt.}
{145}{}{Nej, det är allt häromkring. Om jag hör något mer så säger ja' till. Jag gillar att prata om det lika mycket som jag gillar att höra det!}
{146}{}{Tack.}
{147}{}{Varför är 'u intresserad av dem? Nåja, spelar roll. Quincy har dem borta i underhållet tror jag. }
{148}{}{Okej.}
{149}{}{Var det?}
{150}{}{Jag förstår.}
{151}{}{Var är det?}
{152}{}{Nordöstra hörnet av basen, kompis. Kan inte missa det.}
{153}{}{Okej. Tack.}
{156}{}{I'm surprised ya don't know, ya must be a local, I guess. Anyway, main base's in the middle of the goddamned
 ocean. Well, not smack ass in the middle, but it might as well be. Only way to get there is by ship or vertibird
 and the damn ship's been tinkered with. Ya need a fob to operate the damn thing.}
{157}{}{Fob?}
{158}{}{Yeah, a passkey. Commander keeps it in his office. Without it ya can't access some areas of the ship and that
 keeps the locals down in San Fran from paying an unwelcome visit.}
{159}{}{Good idea.}
{160}{}{Where commander office?}
{161}{}{That's a good idea.}
{162}{}{So where's the commander's office?}
{163}{}{Take the elevator in the next room down, follow the hallway to the main junction, and go straight. }
{164}{}{Tack.}
{165}{}{Hey, soldier. Good to hear from you again. Grub or talk this time?}
{166}{}{Mat.}
{167}{}{Småprat.}
{168}{}{Me just say hi.}
{169}{}{Neither, I'm just saying hi.}
{170}{}{Here ya go. It's dead, it's cooked, it's unidentifiable. Enjoy.}
{171}{}{Uh... Thanks.}
{172}{}{Son, I can tell from the smell that you're not wearin' one of them powered armor suits.
 If the Sarge sees you out of uniform you're screwed. And I ain't talking the type of screwing that feels good. Now get your ass down to supply and suit up.}
{173}{}{Little lady, I can tell from the smell that you're not wearin' one of them powered armor suits.
 If the Sarge sees you out of uniform you're screwed. And I ain't talking the type of screwing that feels good. Now get your ass down to supply and suit up.}
{174}{}{Var det?}
{175}{}{Okej.}
{176}{}{Var är det?}
{177}{}{I'll take care of it.}
{178}{}{Take the elevator in the next room down, follow the hall to the main junction, turn left, and it's the first door on your left. Off you go.}
{179}{}{Tack.}
{180}{}{Holy shit! I'm just a cook... and a blind one at that. I didn't see any intruders come through here.}
{181}{}{Tack.}
{182}{}{Damned alarms. Always such a ruckus when they go off.}
{183}{}{What the hell is that damn thing going on about this time?}
{184}{}{I wish to hell we'd use silent alarms, damn thing gives me a headache.}
{185}{}{I'm gonna fry your ass up and serve it on a plate.}
{186}{}{Your goose is cooked. Ha! I made a funny!}
{187}{}{Out of the frying pan and into the fire.}
