{100}{}{You see bright, shiny tin man.}
{101}{}{A soldier in power armor.}
{102}{}{A soldier in some new type of power armor, you'd guess.}
{103}{}{Can you believe it? I got KP duty again!}
{104}{}{Word is the old man's gonna issue leave to SF!}
{105}{}{To hell with waiting. I say we nuke all these primitives and get things over with.}
{106}{}{Got a light? Oh wait, never mind. Got one.}
{107}{}{Craps game behind the hanger tonight. Don't let the CO know.}
{108}{}{Who the--? <zzzt> We got an intruder here!}
{109}{}{You there! Halt!}
{110}{}{Intruder on base!}
{111}{}{Vänta du--åh, glöm det. }
{112}{}{Bäst att du hämtar din legitimation. De här falska larmen gör alla nervösa.}
{113}{}{Du ska vara här, eller hur? De här falska larmen går mig på nerverna!}
{114}{}{Inkräktaren är här borta! Ta 'em!}
{115}{}{Där är inkräktaren!}
{116}{}{Här borta! Låt 'em inte komma undan!}
{117}{}{Vi blir attackerade på framsidan. Skicka förstärkning!}
{118}{}{Låt inte inkräktaren komma fram till grinden!}
{119}{}{Die, primitive!}
