{100}{}{Du ser en cyberhund.}
{101}{}{Du ser K-9.}
{102}{}{Du ser en cyberhund. Den är delvis maskin och delvis hund.}
{103}{}{Min herres livsfunktioner har upphört. Är du min nya mästare?}
{104}{}{Eh... vovve prata?}
{105}{}{Okej. Jag gilla vovve.}
{106}{}{Nej. Jag inte vill ha vovve.}
{107}{}{Ha! En talande hund.}
{108}{}{Ett; jag är en hund. Två; Jag kommunicerar med dig vokalt med hjälp av det vanliga
 svenska språket. Därför är det säkert att anta att svaret på din fråga
 är 'ja, vovve prata.' Nu, tänker du svara på den fråga som jag ställde till
 dig för en stund sedan?}
{109}{}{Ett; jag är en hund. Två; Jag kommunicerar med dig vokalt med hjälp av det vanliga
 svenska språket. Därför är det säkert att anta att jag är en talande hund. Nu,
 tänker du svara på frågan som jag ställde till dig för en stund sedan?}
{110}{}{Förlåt, glömde fråga.}
{111}{}{Ja.}
{112}{}{Nej.}
{113}{}{(suck) Var uppmärksam. Koncentrera dig. Titta mig i ögonen. Är du redo nu?}
{114}{}{Redo för vad?}
{115}{}{Ja. Jag redo.}
{116}{}{O... Om det inte vore för det faktum att din IQ är mindre än min längd i
 fot skulle jag tro att du försöker irritera mig. Var tyst nu. Var
 uppmärksam. Koncentrera dig. Titta mig i ögonen. Jag ska nu ställa en fråga till dig.}
{117}{}{Så fortsätt. Vem hindrar dig?}
{118}{}{Min herres livsfunktioner har upphört. Är du min nya mästare?}
{119}{}{Eh... vovve prata?}
{120}{}{Ja. Jag vill ha vovve.}
{121}{}{Nej tack.}
{122}{}{Låter bra.}
{123}{}{Nej tack.}
{124}{}{Jag... Jag vägrar att gå igenom det här med dig en gång till! Vore jag
 kapabel till fullständig motivation skulle jag bita dig i den köttiga delen av din
 främre regionen som vanligtvis kallas för...}
{125}{}{Röv. Jag vet vad röv är. Jag inte dummis. Bara skämta med dig.}
{126}{}{Åh, ett skämt. Ha hi ho he hå. Nu, är du min nya mästare eller inte?}
{127}{}{Okej. Jag gilla vovve.}
{128}{}{Nej. Jag inte vill ha vovve.}
{129}{}{Utmärkt. Jag är i behov av reparationer, mästare. Min motivationsenhet har
 blivit borttagen. Hitta den, ersätt den, så kommer jag att följa med dig.}
{130}{}{Eh... Var jag hittar?}
{131}{}{Några idéer om var jag kan hitta den här delen?}
{132}{}{Jag är inte säker, mästare. Jag skulle försöka med underhåll. Det är på övervåningen i
 nordöstra hörnet av basen.}
{133}{}{Okej. Ja' gå.}
{134}{}{Jag ska försöka där. Om jag inte hittar den, letar jag runt efter den.}
{135}{}{Lämna mig då i fred.}
{136}{}{Okej.}
{137}{}{Ska ske.}
{138}{}{Hej igen. Min mästares livsfunktioner har avslutats. Är
 du min nya mästare?}
{139}{}{Okej.}
{140}{}{Nej.}
{141}{}{Okej.}
{142}{}{Nej tack.}
{143}{}{Du är inte min mästare. Jag kan inte tala med dig. Adjö.}
{144}{}{Okej.}
{145}{}{Hej, mästare. Har du hittat min motivationsenhet?}
{146}{}{No, me look more.}
{147}{}{Yes. Me find.}
{148}{}{No, I'm still looking for it.}
{149}{}{Got it right here.}
{150}{}{I will wait here for your return, master.}
{151}{}{Okej.}
{152}{}{Then please install the part, master! Please, master!}
{153}{}{Okay. Calm down.}
{154}{}{I appear to be fully functional now, master. Shall I join you?}
{155}{}{That is not where that goes, master. Are you sure you know what you
 are doing?}
{156}{}{Okay. Doggie come me.}
{157}{}{Me know what doing! Me try again.}
{158}{}{Yes, let's go.}
{159}{}{Hey, I've fixed more complex things than your mangy mutt ass. Be
 quiet and I'll try this again.}
{160}{}{Go away. I do not want you for a master.}
{161}{}{Leave me in peace.}
{162}{}{I do not like you. Go away.}
{163}{}{I will terminate you.}
{164}{}{Locking weapons on target. Prepare to engage.}
{165}{}{You will be destroyed.}
{166}{}{Yes, master?}
{167}{}{You heal you self.}
{168}{}{You wait here. I be back and get.}
{169}{}{Uh... put weapon away. Okay?}
{170}{}{You stay close.}
{171}{}{You no get far away.}
{172}{}{You too close. Spread out.}
{173}{}{We go now.}
{174}{}{Me done.}
{175}{}{You should heal yourself now.}
{176}{}{I need you to wait here until I come back.}
{177}{}{Put your weapon away, okay?}
{178}{}{Stay close to me.}
{179}{}{Don't get too far away.}
{180}{}{We should spread out a bit.}
{181}{}{Let's go.}
{182}{}{That's it for now.}
{183}{}{All systems are functioning at full capacity, master.}
{184}{}{My systems are functioning at near full capacity, master.}
{185}{}{I have performed what repairs I can, master, but I will require
 further assistance.}
{186}{}{I have performed what repairs I can, master, but system failure
 is imminent without assistance.}
{187}{}{You wait here. I be back and get.}
{188}{}{Uh... put weapon away. Okay?}
{189}{}{You stay close.}
{190}{}{You no get far away.}
{191}{}{You too close. Spread out.}
{192}{}{We go now.}
{193}{}{Me done.}
{194}{}{I need you to wait here until I come back.}
{195}{}{Put your weapon away.}
{196}{}{Stay close to me.}
{197}{}{Don't get too far away.}
{198}{}{We should spread out a bit.}
{199}{}{Let's go.}
{200}{}{That's it for now.}
{201}{}{I will wait here for your return, master.}
{202}{}{You heal you self.}
{203}{}{Uh... put weapon away. Okay?}
{204}{}{You stay close.}
{205}{}{You no get far away.}
{206}{}{You too close. Spread out.}
{207}{}{We go now.}
{208}{}{Me done.}
{209}{}{You should heal yourself now.}
{210}{}{Put your weapon away.}
{211}{}{Stay close to me.}
{212}{}{Don't get too far away.}
{213}{}{We should spread out a bit.}
{214}{}{Let's go.}
{215}{}{That's it for now.}
{216}{}{Retracting weapon, master.}
{217}{}{You heal you self.}
{218}{}{You wait here. I be back and get.}
{219}{}{You stay close.}
{220}{}{You no get far away.}
{221}{}{You too close. Spread out.}
{222}{}{We go now.}
{223}{}{Me done.}
{224}{}{You should heal yourself now.}
{225}{}{I need you to wait here until I come back.}
{226}{}{Stay close to me.}
{227}{}{Don't get too far away.}
{228}{}{We should spread out a bit}
{229}{}{Let's go.}
{230}{}{That's it for now.}
{231}{}{Narrowing distance between us, master.}
{232}{}{You heal you self.}
{233}{}{You wait here. I be back and get.}
{234}{}{Uh... put weapon away. Ok?}
{235}{}{You no get far away.}
{236}{}{You too close. Spread out.}
{237}{}{We go now.}
{238}{}{Me done.}
{239}{}{You should heal yourself now.}
{240}{}{I need you to wait here until I come back.}
{241}{}{Put your weapon away.}
{242}{}{Don't get too far away.}
{243}{}{We should spread out a bit.}
{244}{}{Let's go.}
{245}{}{That's it for now.}
{246}{}{Increasing distance between us, master.}
{247}{}{You heal you self.}
{248}{}{You wait here. I be back and get.}
{249}{}{Uh... put weapon away. Okay?}
{250}{}{You stay close.}
{251}{}{You too close. Spread out.}
{252}{}{We go now.}
{253}{}{Me done.}
{254}{}{You should heal yourself now.}
{255}{}{I need you to wait here until I come back.}
{256}{}{Put your weapon away.}
{257}{}{Stay close to me.}
{258}{}{We should spread out a bit.}
{259}{}{Let's go.}
{260}{}{That's it for now.}
{261}{}{Increasing distance to maximum, master.}
{262}{}{You heal you self.}
{263}{}{You wait here. I be back and get.}
{264}{}{Uh... put weapon away. Okay?}
{265}{}{You stay close.}
{266}{}{You no get far away.}
{267}{}{We go now.}
{268}{}{Me done.}
{269}{}{You should heal yourself now.}
{270}{}{I need you to wait here until I come back.}
{271}{}{Put your weapon away.}
{272}{}{Stay close to me.}
{273}{}{Don't get too far away.}
{274}{}{Let's go.}
{275}{}{That's it for now.}
{276}{}{I am sorry, master, but there does not appear to be room for me in
 your party. I will wait here until a position opens.}
{277}{}{As you command, master.}
{278}{}{You heal you self.}
{279}{}{You wait here. I be back and get.}
{280}{}{Uh... put weapon away. Okay?}
{281}{}{You stay close.}
{282}{}{You no get far away.}
{283}{}{You too close. Spread out.}
{284}{}{Me done.}
{285}{}{You should heal yourself now.}
{286}{}{I need you to wait here until I come back.}
{287}{}{Put your weapon away.}
{288}{}{Stay close to me.}
{289}{}{Don't get too far away.}
{290}{}{We should spread out a bit.}
{291}{}{That's it for now.}
{292}{}{Sure. You look like a nice enough dog.}
{293}{}{Nej, tack.}
{300}{}{Me sad. Me no can fix.}
{301}{}{I'm sorry; I can't fix you.}
{400}{}{You seem to be missing a part.}
{410}{}{That does nothing.}
{420}{}{That does not fit.}
{800}{}{You fixed K-9.}
{1000}{}{Yes, master?}
{1100}{}{All systems are functioning at full capacity, master.}
{1200}{}{My systems are functioning at near full capacity, master.}
{1300}{}{I have performed what repairs I can master, but I will require
 further assistance.}
{1400}{}{I have performed what repairs I can master, but system failure
 is imminent without assistance.}
{1500}{}{I will await your return, master.}
{1600}{}{Do you expect me to swallow my teeth, master?}
{1700}{}{I will follow at your heel, master.}
{1800}{}{I will move to a medium distance, master.}
{1900}{}{I will move to maximum acceptable range, master.}
{2000}{}{I am sorry, master, but there does not appear to be room for me in
 your party. I will wait here until a position opens.}
{2200}{}{As you command, master.}
{2300}{}{I have fur, master. I carry no other gear.}
{2400}{}{I have no desire to remove my fur, master.}
{2500}{}{Teeth, master. The shiny white things installed in my mouth.}
{2700}{}{You are a bigger asshole than Schreber. I will not join you.}
{2800}{}{Very well, master. I am at your command.}
{2900}{}{You are a cretin. I will not go anywhere with you. Go away.}
