{100}{}{Stor överraskning -- det ser ut som en snubbe i kraftrustning.}
{101}{}{Japp, det är fortfarande en snubbe i kraftrustning.}
{102}{}{Han har något slags märke på bröstet som skiljer sig från alla andra du sett
 häromkring.}
{103}{}{<Skzzzt-spork> -vapenförrådet!}
{104}{}{Vad i- <zzzzaaark!>>}
{105}{}{(Så, Sergeanten skickade dig. Nåt om att behöva en kraftrustning. Tja, allt jag har är en inne för
 underhåll. Kan ha några problem fortfarande, så ta det lugnt. Skriv bara under här.)}
{106}{}{Eh... Kan du upprepa det?}
{107}{}{Jag tror att det är något fel på din rustning.}
{108}{}{Visst, det ska jag göra.}
{109}{}{Inte en chans. Glöm det.}
{110}{}{E du snubben Arch ropa' in om?}
{111}{}{Är du säker på att du inte är killen?}
{112}{}{Vadå?}
{113}{}{Ja.}
{114}{}{Nej.}
{115}{}{Vem är du? Vad gör du här?}
{116}{}{Vad?}
{117}{}{Eh... jag är ny här?}
{118}{}{Tittut!}
{119}{}{Vem är du? Vad gör du här?}
{120}{}{Vad?}
{121}{}{Eh... jag är ny här?}
{122}{}{Tittut!}
{123}{}{Vad menar du med det? Den här rustningen fungerar bra! Ska du skriva på papperna eller inte?}
{124}{}{Jag förstår inte ett ord av det här.}
{125}{}{Din högtalare är trasig.}
{126}{}{Visst.}
{127}{}{Åt helvete med det här!}
{128}{}{(Vad, är du döv? Jag sa att jag har en rustning; skriv bara på här.)}
{129}{}{Är du en clown? Tja, jag behöver inte det här. Förklara för sergeanten varför du inte har en uniform!}
{130}{}{Vadå?}
{131}{}{Okej, bra. Jag ska göra det.}
{132}{}{Glöm det bara, okej?}
{133}{}{Din högtalare är inte trasig. Jag hör dig alldeles utmärkt. Skriv bara under papperna så kan vi få det här
 gjort.}
{134}{}{Vadå?}
{135}{}{Okej, jag ger upp!}
{136}{}{Du vill att jag ska göra vadå? Jag är inte den sortens person!}
{137}{}{Okej, vad heter du?}
{138}{}{[Spelarens namn]}
{139}{}{Fiskarna?}
{140}{}{Jag vill ha kraftrustningen.}
{141}{}{Svärdfisk.}
{142}{}{Okej. Enhet?}
{143}{}{Arroyo.}
{144}{}{Näpp.}
{145}{}{Jag blev bättre.}
{146}{}{42.}
{147}{}{That with an S or a C?}
{148}{}{Ja.}
{149}{}{Nej.}
{150}{}{Jag vet inte.}
{151}{}{You'll get the damn armor when I'm good and ready! Now, answer the question.}
{152}{}{[Spelarens namn]}
{153}{}{Fiskarna?}
{154}{}{Svärdfisk.}
{155}{}{Arroy-- Wait a minute! We just hit that place. You're a damn tribal! Guards!}
{156}{}{Look, clown, don't be making trouble or I'll have your insubordinate ass up on report. Just
 answer the question. }
{157}{}{Arroyo.}
{158}{}{42.}
{159}{}{That's it! Get your ass over to your sergeant. I'm sending you up on charges. Dismissed.}
{160}{}{The 42nd, eh? Good unit. Okay. Here's your gear. Dismissed, soldier.}
{161}{}{What are you, deaf? Are you the guy or not?}
{162}{}{Ja.}
{163}{}{Like a fish in water.}
{164}{}{Inte.}
{165}{}{Okej, nu skyndar vi på. Ta av dig den där så får du en ny kostym.}
{166}{}{Jag hör bara sprakande från dig.}
{167}{}{Vadå?}
{168}{}{Okej.}
{169}{}{Tänker du döda mig? Jag tror inte det!}
{170}{}{Åh, ja, glöm det.}
{171}{}{The power armor. Give me the power armor, you moron.}
{172}{}{Okej.}
{173}{}{I already made the deal. I'm not giving you any more.}
{174}{}{You bet I got something for you, you bastard.}
{175}{}{Okay, here's the suit. Now get out of here.}
{176}{}{You moron; you don't have the suit. Get out of here!}
{177}{}{What the hell are you talking about? Give me the suit.}
{178}{}{All right, already!}
{179}{}{Screw this!}
{180}{}{Right, J. Okay, Unit?}
{181}{}{Arroyo.}
{182}{}{Näpp.}
{183}{}{Jag blev bättre.}
{184}{}{42.}
{185}{}{You deaf? Who are you?}
{186}{}{I'm the new guy?}
{187}{}{Nope, never heard of 'em.}
{188}{}{New guy, eh? Suppose you want your issue. Why don't anybody ever tell me these things? What's
 your name?}
{189}{}{Huh? You ain't nothing but static.}
{190}{}{[Spelarens namn]}
{191}{}{Not if I shoot first!}
{192}{}{Wait a minute -- you're not one of us! GUARDS!}
{193}{}{Look soldier, I already gave you your gear, so get on out of here.}
{194}{}{Vad vill du?}
{195}{}{Drååg?}
