{100}{}{You see someone in power armor. }
{101}{}{Du ser befälhavaren för Navarro-basen.}
{102}{}{You see someone wearing power armor of an unusual design. There is an insignia on the breastplate that you are unfamiliar with.}
{103}{}{Vilka fan är ni... Varning! Inkräktare på basen!}
{104}{}{I don't have time to chitchat with the grunts. You're dismissed.}
{105}{}{Dags att dö.}
{106}{}{Okej.}
{107}{}{I told you I don't have time for you. Leave this office and do not come back here unless I send for you. Dismissed!}
{108}{}{Att inte lyda en direkt order från en högre officer är förräderi. Jag har inte tid att ställa dig inför krigsrätt, så jag sköter det här själv. Vakter! Döda den här idioten!}
{109}{}{Okej.}
{110}{}{Fan ta dig!}
{111}{}{The Fob is in the locker over there. Have the duty officer contact me once it's secured. Dismissed!}
{112}{}{Ja, sir!}
{113}{}{Gör det snabbt soldat, jag har inte hela dagen på mig att stå här.}
{114}{}{Ja, sir!}
{115}{}{Lämna mitt skåp ifred annars kommer jag att göra ditt liv smärtsamt.}
{116}{}{Ja, sir!}
{117}{}{Den här basen är i beredskap och jag känner inte igen dig. Visa mig dina papper, soldat.}
{118}{}{Vilka papper?}
{119}{}{Dra åt helvete!}
{120}{}{Jag verkar inte ha dem med mig...}
{121}{}{Papers? I've got your papers right here!}
{122}{}{Fel svar, kryp. Du ska alltid ha dina papper med dig. Det borde du veta!}
{123}{}{Fan ta dig.}
{124}{}{Lämna mitt skåp ifred annars kommer jag att göra ditt liv smärtsamt.}
{125}{}{Dags att dö.}
