{100}{}{Du ser en man i militäruniform.}
{101}{}{Du ser Quincy, mekanikern.}
{102}{}{Du ser en man i militäruniform. Att döma av fettfläckarna tror du
 att han är mer av en mekaniker än en soldat.}
{103}{}{Namnet är Quincy, soldat. Varför knackar du på min axel och ser vilsen ut?}
{104}{}{Jag fråga dig en sak.}
{105}{}{Ingenting.}
{106}{}{Hej. Jag måste fråga dig en sak.}
{107}{}{Never mind.}
{108}{}{Okej, men det måste gå fort. Jag har en inventering att göra.}
{109}{}{Vad behöver du veta?}
{110}{}{What this place?}
{111}{}{Jag leta Vertibird-ritningar. Var hittar jag?}
{112}{}{Jag veta från tekniker jag hitta Vertibird-planer här.}
{113}{}{Jag gå nu.}
{114}{}{Vad är det här för ställe?}
{115}{}{Jag letar efter Vertibird-ritningar. Vet du var jag kan hitta dem?}
{116}{}{Jag fick höra av en tekniker att jag kunde hitta Vertibird-planerna här.}
{117}{}{Nåväl, jag måste gå.}
{118}{}{Det här är underhåll. Vi reparerar i stort sett allt utom vertibirderna.}
{119}{}{Where vertibird get repair?}
{120}{}{Where do the vertibirds get repaired?}
{121}{}{They only fit in the hangar or outdoors. You figure it out from there, okay?}
{122}{}{Oh... okay.}
{123}{}{Oh, yeah. I get it.}
{124}{}{Well... I've got a copy of the plans but I can't just hand them out to
 anyone who asks for them. What do you want with them?}
{125}{}{Me got friends down south who want.}
{126}{}{Uh... well...}
{127}{}{I've got some friends down south who want to get their hands on them.}
{128}{}{I was told by the Sarge to get them.}
{129}{}{Down south... Holy shit! We've got a spy here! Guards! Alert!}
{130}{}{Ojdå.}
{131}{}{Ooops. Put my foot in it this time.}
{132}{}{You're one round short of a full clip, aren't you? Well, they call you
 grunts for a reason. Look, Einstein, I can't give you the plans without
 authorization, okay? So, go back to whoever sent you here and get the proper
 paperwork.}
{133}{}{Look, Einstein, I can't give you the plans without authorization, okay?
 So, go back to whoever sent you here and get the proper paperwork.}
{134}{}{Okej, ja' gå.}
{135}{}{No, me shoot you first, find plans second, then... what come after two?}
{136}{}{Hey, you got it.}
{137}{}{No, I think I'll shoot you instead and look around for the plans while
 you bleed.}
{138}{}{A tech told you... You mean Raul? Did he send you?}
{139}{}{Uh, yeah.}
{140}{}{Uh, no.}
{141}{}{Yeah, that's the guy.}
{142}{}{No, I don't think it was Raul.}
{143}{}{Damn it! You know, Raul would lose his head if it weren't placed so
 firmly up his ass! This is the third time this quarter that he's lost those
 plans! And now he doesn't even have the brass bouncing balls to come to me
 and ask for them? Fine, they're in the locker over there. Oh and, when you
 deliver them, tell that asshole I want to see him.}
{144}{}{Tack.}
{145}{}{So you're back. Did you get the authorization?}
{146}{}{You again? What is it now?}
{147}{}{Yeah, me got plasma rifle. That good enough me!}
{148}{}{Nej, inte än.}
{149}{}{Yeah, I've got a big fucking gun. That's good enough for me!}
{150}{}{Nej, inte än.}
{151}{}{Me ask you something.}
{152}{}{Me just say 'Hi'.}
{153}{}{I need to ask you something.}
{154}{}{Nothing, just saying 'Hi'.}
{155}{}{Are you nuts? Walking around here out of uniform? Get suited up!}
{156}{}{If the sergeant catches you out of uniform, he'll hand you your ass.}
{157}{}{Why are you out of uniform?}
{158}{}{Holy shit! We're being invaded! Alert!}
{159}{}{Intruders! Call the guard!}
{160}{}{Guard! Intruders in maintenance!}
{161}{}{What's up? Are we under attack?}
{162}{}{Why the alert? What's happening?}
{163}{}{What the hell's going on?}
{164}{}{Hey! Don't be rummaging through those drawers.}
{165}{}{I told you not to go through my stuff! Guards!}
{200}{}{Yeah. Well, don't believe everything you hear.}
{201}{}{Who told you that? 'Cause he's next after I knock some sense into you.}
{300}{}{Can't you see that I am busy?}
{301}{}{Hey! Don't be rummaging through those drawers!}
{302}{}{I told you not to go through my stuff! Guards!}
