{100}{}{Du ser en tekniker.}
{101}{}{Du ser en Enklav-tekniker.}
{102}{}{Du ser någon som bär en labbrock med ett fickskydd och massor av pennor i. Han ser lite förvirrad ut som någon som är ny på ett jobb.}
{103}{}{Ja, sir?}
{104}{}{Jag ny här. Behöver ställa fråga.}
{105}{}{Me just say hi. Me go now.}
{106}{}{Jag är ny här. Jag behöver ställa några frågor för att bekanta mig med basen.}
{107}{}{Ledsen att störa dig. Jag säger bara hej.}
{108}{}{Jag är själv nyrekryterad, sir. Jag vet inte om jag kan svara på alla dina frågor, men jag ska försöka.}
{109}{}{What can I help you with?}
{110}{}{Vad det här stället?}
{111}{}{Vad du jobb?}
{112}{}{Where Enclave main base at.}
{113}{}{Jag leta Vertibird-ritningar. Var hittar jag?}
{117}{}{Jag gå ska nu.}
{118}{}{Vad är det här för ställe?}
{119}{}{Vad är ditt jobb här?}
{120}{}{Var ligger Enklavens huvudbas?}
{121}{}{Jag måste titta på Vertibird-planerna. Var förvaras de?}
{125}{}{Ingenting. Jag måste gå.}
{126}{}{Det här är kommunikationscentralen. Vi sköter all kommunikation med huvudbasen härifrån.}
{127}{}{Jag se. Jag mer fråga.}
{128}{}{Okej, då. Ett par frågor till.}
{129}{}{Jag är en kommunikationscentertekniker, andra klass. Jag sköter all kommunikation med huvudbasen och underhåller utrustningens status.}
{130}{}{Eh... visst.}
{131}{}{Bra. Fortsätt med det goda arbetet.}
{132}{}{Du måste skämta, eller hur? }
{133}{}{Inte skämt. Var bas?}
{134}{}{Ser jag ut som om jag skojar?}
{135}{}{Huvudbasen ligger utanför Stillahavskusten nära staden San Francisco. Får jag fråga varför du frågar?}
{136}{}{Nej. Anledning militär. Hur många sätt till basen?}
{137}{}{Nej, det här är en militär angelägenhet. Hur många sätt känner du till för att nå basen?}
{138}{}{Well... there's the vertibirds, but that's pretty obvious. Then there's the tanker down in San Fran. Other than that I guess you'd have to swim.}
{139}{}{Tack.}
{140}{}{Tack.}
{141}{}{De skulle finnas på underhållsavdelningen, bredvid flygledningen. }
{142}{}{Okej.}
{143}{}{Got it.}
{153}{}{Are you nuts, walking around here out of uniform? Get suited up!}
{154}{}{Om sergeanten ser dig utan uniform kommer han att spöa upp dig.}
{155}{}{Varför har du inte uniform på dig? }
{156}{}{Jävla skit! Vi har blivit invaderade! Varning!}
{157}{}{Inkräktare! Kalla på vakten!}
{158}{}{Guard! Intruders in the comm center!}
{159}{}{Läget? Är vi under attack?}
{160}{}{Varför går larmet? Vad händer?}
{161}{}{Vad i helvete är på gång?}
{162}{}{Jag är bara en tekniker, skjut mig inte!}
{163}{}{I didn't sign up for combat, just tech training!}
{164}{}{This is a lab coat, not armor! I'm outta here!}
