{100}{}{Du ser en tekniker.}
{101}{}{Du ser en Enklav-tekniker.}
{102}{}{Du ser någon som bär en labbrock. Han verkar självsäker och trygg i sig själv.}
{103}{}{Ja, sir?}
{104}{}{Jag ny här. Behöver ställa fråga.}
{105}{}{Jag bara säga hej. Jag gå nu.}
{106}{}{Jag är ny här och jag försöker bekanta mig med basen. Får jag ställa några frågor?}
{107}{}{Jag säger bara hej. Vi ses.}
{108}{}{Självklart, soldat.}
{109}{}{Vad kan jag hjälpa dig med?}
{110}{}{Vad det här stället?}
{111}{}{Vad du jobb?}
{112}{}{Var Enklaven huvudbas någonstans?}
{113}{}{Jag leta Vertibird-ritningar. Var hittar jag?}
{117}{}{Jag gå ska nu.}
{118}{}{Vad är det här för ställe?}
{119}{}{Vad är ditt jobb här?}
{120}{}{Var ligger Enklavens huvudbas?}
{121}{}{Jag måste titta på Vertibird-planerna. Var förvaras de?}
{125}{}{Ingenting. Jag måste gå.}
{126}{}{Det här är kommunikationscentralen. Härifrån sköter vi all kommunikation med huvudbasen och alla andra utposter som har upprättats.}
{127}{}{Jag se. Jag mer fråga.}
{128}{}{Okej, då. Ett par frågor till.}
{129}{}{Jag är en kommunikationscentertekniker, första klass. Jag utför övervakningsuppgifter. Jag ser främst till att de andra teknikerna inte klantar sig.}
{130}{}{Eh... visst.}
{131}{}{Bra. Fortsätt med det goda arbetet.}
{132}{}{Soldat, den informationen är "behöver veta"-klassad. Om du måste ställa frågan så behöver du inte veta.}
{133}{}{Okej.}
{134}{}{Kom igen, jag är ju ingen jäkla stammedlem eller nåt. Vi är från samma grupp; ser du märket på rustningen?}
{135}{}{Jag förstår.}
{136}{}{Ja, sir. Huvudbasen ligger vid Stillahavskusten nära staden San Francisco. Får jag fråga varför ni undrar, sir?}
{137}{}{Soldat, jag sa ju att den informationen är "behöver veta"-klassad.}
{138}{}{Av säkerhetsskäl kontrollerar jag baspersonalens informationsmedvetenhet. Berätta nu om alla sätt du personligen känner till för att ta dig till huvudbasen.}
{139}{}{Jag förstår.}
{140}{}{Yes, sir. First, the vertibirds are the primary method used in reaching main base. Due to the complexity of their operation it is doubtful that subversives could commandeer a vertibird. Second, there is an operational fuel tanker in San Francisco harbor. The ship has, however, been disabled and a passkey is required to restart it. The base commander has the passkey in his possession. Third, with the proper equipment, you could conceivably swim to main base but the probability of survival is next to nil.}
{141}{}{Tack.}
{142}{}{Tack.}
{143}{}{De skulle finnas på underhållsavdelningen, bredvid flygledningen. }
{144}{}{Okej.}
{145}{}{Jag förstår.}
{155}{}{Are you nuts, walking around here out of uniform? Get suited up!}
{156}{}{Om sergeanten ser dig utan uniform kommer han att spöa upp dig.}
{157}{}{Why are you out of uniform?}
{158}{}{Jävla skit! Vi har blivit invaderade! Varning!}
{159}{}{Inkräktare! Kalla på vakten!}
{160}{}{Guard! Intruders in the comm center!}
{161}{}{Läget? Är vi under attack?}
{162}{}{Varför går larmet? Vad händer?}
{163}{}{Vad i helvete är på gång?}
{164}{}{Jag är bara en tekniker, skjut mig inte!}
{165}{}{I didn't sign up for combat, just tech training!}
{166}{}{This is a lab coat, not armor! I'm outta here!}
