{100}{}{You see a tech.}
{101}{}{You see an Enclave technician.}
{102}{}{Du ser någon som bär en labbrock med ett fickskydd och massor av pennor i. Han ser lite förvirrad ut som någon som är ny på ett jobb.}
{103}{}{Ja, sir?}
{104}{}{Me new here. Need ask question.}
{105}{}{Me just say hi. Me go now.}
{106}{}{Jag är ny här. Jag behöver ställa några frågor för att bekanta mig med basen.}
{107}{}{Ledsen att störa dig. Jag säger bara hej.}
{108}{}{Jag är själv nyrekryterad, sir. Jag vet inte om jag kan svara på alla dina frågor, men jag ska försöka.}
{109}{}{What can I help you with?}
{110}{}{What this place?}
{111}{}{What you job?}
{112}{}{Where Enclave main base at.}
{113}{}{Me look for vertibird plans. Where I find?}
{117}{}{Me be go now.}
{118}{}{Vad är det här för ställe?}
{119}{}{What is your job here?}
{120}{}{Where is the Enclave main base located?}
{121}{}{I need to look at the vertibird plans. Where are they kept?}
{125}{}{Nothing. I've got to go.}
{126}{}{Det här är kommunikationscentralen. Vi sköter all kommunikation med huvudbasen härifrån.}
{127}{}{Me see. Me ask more.}
{128}{}{All right. A couple more questions.}
{129}{}{Jag är en kommunikationscentertekniker, andra klass. Jag sköter all kommunikation med huvudbasen och underhåller utrustningens status.}
{130}{}{Uh... yeah.}
{131}{}{Good. Keep up the good work.}
{132}{}{Du måste skämta, eller hur? }
{133}{}{Inte skämt. Var bas?}
{134}{}{Ser jag ut som om jag skojar?}
{135}{}{Huvudbasen ligger utanför Stillahavskusten nära staden San Francisco. Får jag fråga varför du frågar?}
{136}{}{Nej. Anledning militär. Hur många sätt till basen?}
{137}{}{Nej, det här är en militär angelägenhet. Hur många sätt känner du till för att nå basen?}
{138}{}{Well... there's the vertibirds, but that's pretty obvious. Then there's the tanker down in San Fran. Other than that I guess you'd have to swim.}
{139}{}{Tack.}
{140}{}{Tack.}
{141}{}{De skulle finnas på underhållsavdelningen, bredvid flygledningen. }
{142}{}{Okej.}
{143}{}{Got it.}
{153}{}{Are you nuts, walking around here out of uniform? Get suited up!}
{154}{}{If the sergeant catches you out of uniform he'll hand you your ass.}
{155}{}{Why are you out of uniform? }
{156}{}{Holy shit! We're being invaded! Alert!}
{157}{}{Intruders! Call the guard!}
{158}{}{Guard! Intruders in the comm center!}
{159}{}{What's up? Are we under attack?}
{160}{}{Why the alert? What's happening?}
{161}{}{What the hell's going on?}
{162}{}{I'm just a tech, don't shoot me!}
{163}{}{I didn't sign up for combat, just tech training!}
{164}{}{This is a lab coat, not armor! I'm outta here!}
