{100}{}{You see a tech.}
{101}{}{You see an Enclave technician.}
{102}{}{You see someone wearing a lab coat. He appears confident and self-assured.}
{103}{}{Ja, sir?}
{104}{}{Me new here. Need ask question.}
{105}{}{Me just say hi. Me go now.}
{106}{}{I'm new here and I'm trying to get familiar with the base. Can I ask you some questions?}
{107}{}{Just saying hi. See ya.}
{108}{}{Självklart, soldat.}
{109}{}{What can I help you with?}
{110}{}{What this place?}
{111}{}{What you job?}
{112}{}{Where Enclave main base at?}
{113}{}{Me look for vertibird plans. Where I find?}
{117}{}{Me be go now.}
{118}{}{Vad är det här för ställe?}
{119}{}{What is your job here?}
{120}{}{Where is the Enclave main base located?}
{121}{}{I need to look at the vertibird plans. Where are they kept?}
{125}{}{Nothing. I've got to go.}
{126}{}{Det här är kommunikationscentralen. Härifrån sköter vi all kommunikation med huvudbasen och alla andra utposter som har upprättats.}
{127}{}{Me see. Me ask more.}
{128}{}{All right. A couple more questions.}
{129}{}{Jag är en kommunikationscentertekniker, första klass. Jag utför övervakningsuppgifter. Jag ser främst till att de andra teknikerna inte klantar sig.}
{130}{}{Uh... yeah.}
{131}{}{Good. Keep up the good work.}
{132}{}{Soldat, den informationen är "behöver veta"-klassad. Om du måste ställa frågan så behöver du inte veta.}
{133}{}{Okej.}
{134}{}{Kom igen, jag är ju ingen jäkla stammedlem eller nåt. Vi är från samma grupp; ser du märket på rustningen?}
{135}{}{Jag förstår.}
{136}{}{Ja, sir. Huvudbasen ligger vid Stillahavskusten nära staden San Francisco. Får jag fråga varför ni undrar, sir?}
{137}{}{Soldat, jag sa ju att den informationen är "behöver veta"-klassad.}
{138}{}{Av säkerhetsskäl kontrollerar jag baspersonalens informationsmedvetenhet. Berätta nu om alla sätt du personligen känner till för att ta dig till huvudbasen.}
{139}{}{Jag förstår.}
{140}{}{Yes, sir. First, the vertibirds are the primary method used in reaching main base. Due to the complexity of their operation it is doubtful that subversives could commandeer a vertibird. Second, there is an operational fuel tanker in San Francisco harbor. The ship has, however, been disabled and a passkey is required to restart it. The base commander has the passkey in his possession. Third, with the proper equipment, you could conceivably swim to main base but the probability of survival is next to nil.}
{141}{}{Tack.}
{142}{}{Tack.}
{143}{}{De skulle finnas på underhållsavdelningen, bredvid flygledningen. }
{144}{}{Okej.}
{145}{}{Got it.}
{155}{}{Are you nuts, walking around here out of uniform? Get suited up!}
{156}{}{Om sergeanten ser dig utan uniform kommer han att spöa upp dig.}
{157}{}{Why are you out of uniform?}
{158}{}{Holy shit! We're being invaded! Alert!}
{159}{}{Intruders! Call the guard!}
{160}{}{Guard! Intruders in the comm center!}
{161}{}{What's up? Are we under attack?}
{162}{}{Why the alert? What's happening?}
{163}{}{What the hell's going on?}
{164}{}{Jag är bara en tekniker, skjut mig inte!}
{165}{}{I didn't sign up for combat, just tech training!}
{166}{}{This is a lab coat, not armor! I'm outta here!}
