{100}{}{En soldat i tjänsteuniform.}
{101}{}{Some Pfc-Tech, grade X.}
{102}{}{Han bär en militäruniform, men det är uppenbart att han är mer av en tekniker än en soldat.}
{103}{}{Hörni, hur många gånger måste jag säga det till er klåpare? Stå inte i vägen!}
{104}{}{Har du inte något att skjuta?}
{105}{}{Var hälsad, soldat.}
{106}{}{Vem är du? Vakter!}
{107}{}{Vad i helvete är det här? Infiltratör på basen!}
{108}{}{Fan! Var är mitt gevär!}
{109}{}{De har redan letat här och inte hittat nåt.}
{110}{}{Jösses, de här falska larmen gör mig nervös som fan.}
{111}{}{Great, another false alarm. Now we'll have to tear the whole system down and put it back
 together again. }
{112}{}{Goddamn it! Over here! Get the spy!}
{113}{}{Shit! It's an attack! Where's my piece?}
{114}{}{Shooting? Nobody said there'd be any shooting!}
{115}{}{Who the hell are you? Guards!}
{116}{}{You're not Enclave! Guards!}
{117}{}{Infiltrators! Saboteurs! Over here!}
{118}{}{Hey, don't mess up the plans. I'm working here.}
{119}{}{Where the hell's that gyrovator part?}
{120}{}{Damn fly-boys, always breaking my machines.}
{121}{}{Roger that, we got you on the scope -- don't bother me, I'm working.}
{122}{}{Look, no personal calls allowed, soldier.}
{123}{}{Sorry, can't help you now.}
{124}{}{You have business down here? If not, out of my way.}
{125}{}{This is a restricted area, soldier.}
{126}{}{Move out of my way, soldier.}
{127}{}{What the hell? What's going on up there?}
{128}{}{Shit! They've broken in!}
{129}{}{Those clowns! It's probably just another false alarm.}
