{100}{}{Var hälsad, människa. Jag är krigaren Xarn. Kommer du att bli min bödel?}
{101}{}{Ja.}
{102}{}{Nej, jag här rädda dig.}
{103}{}{Inte vet. Vill veta varför du här.}
{104}{}{Ja det är jag.}
{105}{}{Nej, jag är här för att rädda dig.}
{106}{}{Jag vet inte. Jag skulle vilja veta varför du är här.}
{107}{}{Låt det så bli. Jag tänker inte gå tyst, människa. Låt oss göra detta till en
 strid att minnas!}
{108}{}{Okej.}
{109}{}{Vänta. Jag ändrat mig. Varför är du här?}
{110}{}{Jag är redo. Nu kör vi.}
{111}{}{Vänta lite nu. Varför är du här?}
{112}{}{I find it hard to believe that an Enclave soldier is here to rescue me.
 More likely, you are here to build up my hopes so that you can dash them to pieces.}
{113}{}{Nej. Jag här rädda dig. Verkligen.}
{114}{}{Jag är verkligen här för att rädda dig!}
{115}{}{Du är mitt sista hopp, så jag litar på dig. Dörren
 där borta leder till ett luftschakt som mynnar ut i skogen ovanför.
 Jag borde kunna klättra upp i schaktet och bli fri. Men,
 dörren är säkert låst och kräver en nyckel för att öppnas.
 Hitta nyckeln, lås upp dörren och ge mig min frihet.}
{116}{}{Okay, me do.}
{117}{}{Jag tänka på det.}
{118}{}{Visst, jag ska göra det.}
{119}{}{Jag ska tänka på det.}
{120}{}{(Xarn stares at you intently for a moment) Very well.
 The Enclave created my people as a slave warrior race. They
 enhanced our intellect hoping we could better understand their
 commands, and yet not recognize our status as slaves.
 They failed; we are much more intelligent than they suspect.}
{121}{}{We decided to play the fool until we could gain our
 freedom. Our chance arrived when the Enclave decided to test
 us outside their control, here on the mainland. Doctor Schreber
 opposed their decision, but he was overruled.}
{122}{}{Not accepting the Enclave decision, he chose exile to this base,
 captured me, and has been performing experiments to determine my
 true nature. He has been successful. When he reports his findings
 to the Enclave my people will be hunted down and slain. I must
 escape and warn my people.}
{123}{}{(Xarn stirrar på dig intensivt för ett ögonblick) Jag har ingenting
 att berätta för dig, människa. Jag kan känna mörkret i din själ.}
{124}{}{Om doktor stort hot, varför du inte döda?}
{125}{}{Fan ta dig då. Jag skjuta din röv.}
{126}{}{Om den här snubben är ett sånt hot, varför dödade du honom inte bara?}
{127}{}{Up yours, then. Die, deathclaw.}
{128}{}{(suck) Nyligen började jag överväga just en sådan handling,
 även om det inte är mitt sätt att döda. Jag är säker på att läkaren
 märkte det eftersom han slutade träffa mig personligen. Valet är
 inte längre mitt att göra.}
{129}{}{You not worry. Doctor dead. He not make report.}
{130}{}{Jag tacka för berättelse.}
{131}{}{Du behöver inte oroa dig. Doktorn är död och han
 gjorde inte rapporten.}
{132}{}{Tack för berättelsen. Den var intressant.}
{133}{}{Jag är ledsen att höra om hans död men det är för det
 bättre att det är så. Jag skulle vilja be dig att hjälpa mig att fly
 den här platsen. Kan du göra det?}
{134}{}{Ja, jag gör.}
{135}{}{Jag tänka på det.}
{136}{}{Nej, jag inte tro det.}
{137}{}{Ja, jag ska göra det.}
{138}{}{Nej, men jag ska fundera på det.}
{139}{}{Nej, det tror jag inte.}
{140}{}{Nåväl... Jag väntar här tills du har fattat ett beslut.}
{141}{}{Färdigt.}
{142}{}{Nåväl... Jag är ledsen över ditt beslut men det är
 ditt val. Om du ändrar dig kommer jag att vara här.}
{143}{}{Hej då.}
{144}{}{Farväl.}
{145}{}{Jag vill be dig att hjälpa mig att fly härifrån. Kan du göra det?}
{146}{}{Ja, jag gör.}
{147}{}{Jag tänka på det.}
{148}{}{Nej, jag inte tro det.}
{149}{}{Ja, jag ska göra det.}
{150}{}{Nej, men jag ska fundera på det.}
{151}{}{Nej, det tror jag inte.}
{152}{}{Hej igen. Är du redo för vår strid?}
{153}{}{No want fight, want hear you story.}
{154}{}{Me not want fight. Me here rescue you.}
{155}{}{Nej. Jag gå.}
{156}{}{Ja. Jag redo.}
{157}{}{Jag vill egentligen inte slåss. Kan jag få höra din historia istället?}
{158}{}{Jag är här för att rädda dig, inte för att slåss.}
{159}{}{Nej, jag ska gå nu.}
{160}{}{Okej, låt oss få det överstökat.}
{161}{}{Hej igen. Har du ändrat dig? Tänker du hjälpa mig?}
{162}{}{Ja.}
{163}{}{Nej.}
{164}{}{Hej igen. Har du ändrat dig? Tänker du hjälpa mig?}
{165}{}{Ja.}
{166}{}{No. Me still think about it.}
{167}{}{Nej. Jag inte hjälpa.}
{168}{}{Nej, jag tänker fortfarande.}
{169}{}{Jag vill inte hjälpa dig.}
{170}{}{Hello again. Have you found the key to the door?}
{171}{}{Yes, me open for you.}
{172}{}{Me still look.}
{173}{}{Yeah, I've got it. I'll open the door for you.}
{174}{}{I'm still looking.}
{175}{}{Thank you. I will not forget this.}
{176}{}{You welcome.}
{177}{}{You are welcome.}
{178}{}{Thank you again, my friend. I owe you a debt that can not be repaid.}
{179}{}{Greetings, human. The base is on full alert. Are you by any chance the cause?}
{180}{}{Hello again. The base is on full alert. Are you the cause?}
{181}{}{Yes, me cause. Who you, why you want know?}
{182}{}{Yes, me cause. Why?}
{183}{}{I am Xarn, pack warrior. Allow me to join you and fight at your side for our freedom. Together we stand a chance; alone... who knows?}
{184}{}{Then allow me to join you and fight at your side. Together
 we may be able to gain our freedom; alone... who knows?}
{185}{}{Before me decide you tell why you here?}
{186}{}{Uh... okay. You come me. We fight way out together.}
{187}{}{You on you own. Me out of here.}
{188}{}{Before I come to any decision I'd like to know why you're here?}
{189}{}{Fine. We're in this together. Load up your claws and let's party down!}
{190}{}{You're on your own pal. I'm out of here.}
{191}{}{Uh... okay. You come me. We fight way out together.}
{192}{}{You on you own. Me out of here.}
{193}{}{Fine. We're in this together. Load up your claws and let's party down!}
{194}{}{You're on your own pal. I'm out of here.}
{195}{}{I thank you, human. Let us kick some Enclave ass! Pack Gruthar! Grrrrrrrhh!}
{196}{}{Okej.}
{200}{}{[MER]}
{201}{}{Yes. Who are you?}
{202}{}{Yes. Why?}
{300}{}{Very well. The Enclave created my people as a slave warrior race.
 They enhanced our intellect hoping we could better understand their
 commands, and yet not recognize our status as slaves. They failed; we are
 much more intelligent than they suspect.}
{301}{}{We decided to play the fool until we could gain our freedom. Our
 chance arrived when the Enclave decided to test us outside their control, here
 on the mainland. Doctor Schreber opposed their decision, but he was overruled.}
{302}{}{Not accepting the Enclave decision, he chose exile to this base, captured
 me, and has been performing experiments to determine my true nature. He has
 been successful. When he reports his findings to the Enclave my people will be
 hunted down and slain. I must escape and warn my people.}
{500}{}{You are a true Pack brother. May we meet again in more peaceful times.
 I must go now to prepare my people for war.}
{501}{}{I am going to tear off your limbs and beat you with them.}
{502}{}{Die, treacherous human!}
{503}{}{This will hurt you a lot more than it does me.}
{600}{}{Together we will crush our enemies.}
{601}{}{You line 'em up and I'll knock 'em down.}
{602}{}{Time for some serious head bashing.}
{700}{}{You see a deathclaw. It watches you with strangely intelligent eyes.}
{701}{}{You see Xarn, the Deathclaw.}
{702}{}{You see a typical deathclaw. The creature is huge, with a powerful body, sharp teeth, and long claws.}
{800}{}{You killed Xarn.}
{810}{}{You freed Xarn.}
{820}{}{You joined Xarn.}
{900}{}{No. Me here rescue you. Really. Me already open door for leave. You go.}
{901}{}{Look, I really am here to rescue you! I already unlocked the other door. You are free to leave.}
