{100}{}{Du ser en kort man med en tjock mustasch.}
{101}{}{Du ser den store Ananias.}
{102}{}{Du ser en kortväxt, mustaschprydd man med ett lite lömskt utseende.}
{103}{}{Du där! Vad vill du göra med den, tidigare, store Ananias nu?}
{104}{}{Försvinn från mig!}
{105}{}{Gå och förstör någon annans affärer.}
{106}{}{Låt det gå ut över någon annan.}
{107}{}{Du har redan gjort ditt värsta mot mig.}
{108}{}{Försvinn bara, du har gjort mig tillräckligt illa.}
{109}{}{Jag är så hungrig.}
{110}{}{Hur ska jag någonsin kunna föda min familj nu?}
{111}{}{Du föddes med ett hjärta som var 12 storlekar för litet.}
{112}{}{Nej, min vän, en MUMIE! Direkt från sanden i forntida Egypten till sanden i Ödemarken! Exklusivt för dig att se!}
{113}{}{Okej, jag nappar. Hur mycket för att se det förvridna liket?}
{114}{}{(för dig själv) Hmm, En mumie skulle på sätt och vis beskriva hur en ghul ser ut. OK, jag skulle vilja ta en titt -- hur mycket?}
{115}{}{Jag har redan sett tillräckligt med lik. Adjö.}
{116}{}{Hallå, välkomen, hälsningar! Jag är den store Ananias (han ger dig en lätt bugning, med en viftning). Jag för med mig mysterier från nära och fjärran, min vän. Mysterier från en värld bortom vår egen... från Underjorden.}
{117}{}{Har du kommit tillbaka för att lära dig mer om den stora Ananias mysterier från Underjorden?}
{118}{}{Vilken typ av mysterier?}
{119}{}{Eh, trevligt att träffas, herr Stora Anus... någonting.}
{120}{}{Hmm, mysterier får mig att sova oroligt. Bäst att jag går. Hej då.}
{121}{}{Stig fram!}
{127}{}{Idag, i rummet innanför, har jag, för era ögon exklusivt... En e-ku-ta Egyptisk Mumie!}
{128}{}{En mumie?}
{129}{}{A mummy? Hmm, I wonder if it could be.... No, nobody could be that stupid.}
{130}{}{I don't have any interest in that sort of thing. Corpses scare me.}
{131}{}{Out of the way, you're blocking paying customers.}
{132}{}{I don't think this is for you.}
{133}{}{Why don't you take your little tribal self elsewhere.}
{134}{}{This isn't really for you.}
{135}{}{I see, hmmm, how about GO (he points) AWAY!}
{136}{}{For a person of your obvious class I would be happy to show this unique, and historic, specimen to you for a mere $25.}
{137}{}{OK, I'll cough up the dough. Now... Show Me The Mummy!}
{138}{}{I don't want to spend that much. I think I'll survive without seeing the thing. Goodbye.}
{139}{}{Simply open the sarcophagus lid and the marvelous Mummy will be revealed, in all its ancient glory, to you. But please, no touching, and, uh, no flash photography.}
{140}{}{Utmärkt.}
{141}{}{There you go! The MUMMY! (the door to the sarcophagus swings open to reveal a desiccated corpse, that looks very much like an ordinary ghoul, standing in a poorly painted, chipped and cracked paper-mache sarcophagus.)}
{142}{}{There you go! Presenting, the MUMMY! (a crypt-like door swings open to reveal a jan-u-wine Egyptian mummy standing in an open sarcophagus that looks as though it's made out of pure gold!)}
{143}{}{Hey, wait a minute. That's not a Mummy. That's a ghoul. WOODY! Hey WOODY! Is that you?}
{144}{}{That sure looks like a ghoul to me.}
{145}{}{That's a mummy? I can't believe I just paid $25 to see a six-foot hunk of jerky. Goodbye.}
{146}{}{Wow, that's fantastic... I guess. (you look at the Mummy very intently for a while). Uh, thanks, Goodbye.}
{147}{}{(the Mummy, snorts, stretches languidly, and then looks at you with a sleepy blink to its eyes) Hello. (he says, sleepily)}
{148}{}{Holy shit! That *is* Woody! Run Woody, run for it! Well, uh, gimp for it then! Go Woody go!}
{149}{}{I assure you that the Mummy is, in fact, quite jan-u-wine.}
{150}{}{I don't think I believe you. Let me try something. WOODY! Hey WOODY! Is that you?}
{151}{}{Well, if you say so. But I sure think it looks like an ordinary ghoul. Goodbye.}
{152}{}{(Woody--för det är faktiskt Woody, inte en Mumie, som står lite sömnig framför dig--tar tag i sidorna på
 Papier-
maché-sarkofagen, ger ifrån sig ett skrik och springer mot dörren, efterlämnande ett spår av toalettpapper 'mumie-omslag'
 och et hastigt "Tak så micke', Fr'mling!" efter sig.)}
{153}{}{Hah! Jag visste det! Det är slut med dig i den här stan. Du är inte den store Ananias längre, du är bara ännu en skitstövel.}
{154}{}{Heja Woody! Ahah! Jag visste det!}
{155}{}{(The Great Ananias shrugs) I knew I should have picked up that mono-headed Brahmin instead. Oh well, back to the drawing board.}
{156}{}{Mono-headed brahmin? Sure, who would ever believe that! Goodbye, you Charlatan.}
{157}{}{You woke up Woody the ghoul and freed him from indentured mummy-tude.}
{158}{}{I think I'd rather hear the ghost story.}
{200}{}{I know things that mere mortal man is not meant to know. Aiiieeee! Nyarloth... Oh, sorry (heh, heh). Got a little carried away
 there for a moment. I have tales of a Ghost that haunts these very grounds, as well as a Jan-u-wine Egypt-ee-an Mummy that you
 can see, right here in this marvelous sarcophagus.}
{201}{}{Tell me about the mummy. I'm just dying to hear more about that.}
{202}{}{I've just got to hear that ghost story. Uh, do I get a nice hot cup of cocoa to go with it?}
{203}{}{I don't think I have any more time to waste on whatever it is that you're hawking.}
{300}{}{Well, you see, (he motions you closer) there was once a great queen that ruled all of the surrounding town. She kept her
 throne by virtue of a special amulet that she kept around her neck at all times. Great stuff, huh?}
{301}{}{Uh, yeah. You bet. So this princess had a *magic* amulet. Oh, do go on. I just can't stand this level of suspense
 much longer (yawn).}
{302}{}{OK. I think I've heard just about enough. Goodbye.}
{400}{}{Well, I'll cut to the chase then. So, the evil wizard poisoned the young princess and took her amulet. She's been wandering
 around the room next door ever since. Well, uh, that is, just at the witching hour, anyway. That's why I keep the door locked.
 Pretty darn scary, huh?}
{401}{}{The ghost of an amuletless princess in the trashed room next door? That's it? I can't believe you're peddling *that* as a story.
 I'd rather hear about this stupid Mummy you're supposed to have here.}
{402}{}{OK. I think I've heard just about enough. Goodbye.}
