{100}{}{Du ser en kort man med en tjock mustasch.}
{101}{}{Du ser den store Ananias.}
{102}{}{Du ser en kortväxt, mustaschprydd man med ett lite lömskt utseende.}
{103}{}{Du där! Vad vill du göra med den, tidigare, store Ananias nu?}
{104}{}{Försvinn från mig!}
{105}{}{Gå och förstör någon annans affärer.}
{106}{}{Låt det gå ut över någon annan.}
{107}{}{Du har redan gjort ditt värsta mot mig.}
{108}{}{Försvinn bara, du har gjort mig tillräckligt illa.}
{109}{}{Jag är så hungrig.}
{110}{}{Hur ska jag någonsin kunna föda min familj nu?}
{111}{}{Du föddes med ett hjärta som var 12 storlekar för litet.}
{112}{}{Nej, min vän, en MUMIE! Direkt från sanden i forntida Egypten till sanden i Ödemarken! Exklusivt för dig att se!}
{113}{}{Okej, jag nappar. Hur mycket för att se det förvridna liket?}
{114}{}{(för dig själv) Hmm, En mumie skulle på sätt och vis beskriva hur en ghul ser ut. OK, jag skulle vilja ta en titt -- hur mycket?}
{115}{}{Jag har redan sett tillräckligt med lik. Adjö.}
{116}{}{Hallå, välkomen, hälsningar! Jag är den store Ananias (han ger dig en lätt bugning, med en viftning). Jag för med mig mysterier från nära och fjärran, min vän. Mysterier från en värld bortom vår egen... från Underjorden.}
{117}{}{Har du kommit tillbaka för att lära dig mer om den stora Ananias mysterier från Underjorden?}
{118}{}{Vilken typ av mysterier?}
{119}{}{Eh, trevligt att träffas, herr Stora Anus... någonting.}
{120}{}{Hmm, mysterier får mig att sova oroligt. Bäst att jag går. Hej då.}
{121}{}{Stig fram!}
{127}{}{Idag, i rummet innanför, har jag, för era ögon exklusivt... En e-ku-ta Egyptisk Mumie!}
{128}{}{En mumie?}
{129}{}{En mumie? Hmm, jag undrar om det kan vara.... Nej, ingen kan vara så dum.}
{130}{}{Jag är inte intresserad av sånt. Lik skrämmer mig.}
{131}{}{Ur vägen, du blockerar betalande kunder.}
{132}{}{Jag tror inte att det här är något för dig.}
{133}{}{Why don't you take your little tribal self elsewhere.}
{134}{}{Det här är inte riktigt för dig.}
{135}{}{Jag förstår, hmmm, vad sägs om GÅ (han pekar) HÄRIFRÅN!}
{136}{}{För en person av din uppenbara klass skulle jag gärna visa detta unika och historiska exemplar för dig för bara $25.}
{137}{}{Okej, jag hostar upp degen. Nu... Visa mig mumien!}
{138}{}{Jag vill inte spendera så mycket. Jag tror att jag överlever utan att se den. Hej då.}
{139}{}{Öppna helt enkelt sarkofaglocket och den magnifika Mumien kommer att avslöjas i all sin antika prakt för dig. Men snälla, rör inte vid den och, eh, fotografera inte med blixt.}
{140}{}{Utmärkt.}
{141}{}{Så där ja! MUMIEN! (dörren till sarkofagen svängs upp och avslöjar ett uttorkat lik, som ser mycket ut som en vanlig ghul, som står i en dåligt målad, flisig och sprucken sarkofag av papier-maché).}
{142}{}{Så där ja! Presenterar, MUMIEN! (en kryptliknande dörr svängs upp och avslöjar en e-ku-ta egyptisk mumie som står i en öppen sarkofag som ser ut att vara gjord av rent guld!)}
{143}{}{Hallå, vänta lite. Det är inte en mumie. Det är en ghul. WOODY! Hej WOODY! Är det du?}
{144}{}{Jag tycker att det verkligen ser ut som en ghul.}
{145}{}{Är det där en mumie? Jag kan inte fatta att jag betalade $25 för att se en 1,80 meter lång bit torkat kött. Adjö.}
{146}{}{Wow, det där är fantastiskt... antar jag. (du tittar på mumien mycket intensivt en stund). Eh, tack, Hej då.}
{147}{}{(Mumien fnyser, sträcker sig slött och tittar sedan på dig med en sömnig blinkning i ögonen) Hej. (säger han sömnigt)}
{148}{}{Herrejävlar! Det *är* Woody! Spring Woody, spring iväg! Hm, eh, stappla iväg istället! Heja Woody!}
{149}{}{Jag försäkrar er att Mumien faktiskt är riktigt e-ku-ta.}
{150}{}{Jag tror inte att jag tror på dig. Låt mig försöka med något. WOODY! Hej WOODY! Är det du?}
{151}{}{Ja, om du säger det. Men jag tycker verkligen att den ser ut som en vanlig ghul. Adjö.}
{152}{}{(Woody--för det är faktiskt Woody, inte en Mumie, som står lite sömnig framför dig--tar tag i sidorna på
 Papier-
maché-sarkofagen, ger ifrån sig ett skrik och springer mot dörren, efterlämnande ett spår av toalettpapper 'mumie-omslag'
 och et hastigt "Tak så micke', Fr'mling!" efter sig.)}
{153}{}{Hah! Jag visste det! Det är slut med dig i den här stan. Du är inte den store Ananias längre, du är bara ännu en skitstövel.}
{154}{}{Heja Woody! Ahah! Jag visste det!}
{155}{}{(Den store Ananias rycker på axlarna) Jag visste att jag borde ha valt den där enhövdade brahminen istället. Nåja, tillbaka till ritbordet.}
{156}{}{Enhövdad brahmin? Visst, vem skulle någonsin tro det! Adjö, din lurendrejare.}
{157}{}{Du väckte ghulen Woody och befriade honom från obetald mumie-tjänst.}
{158}{}{Jag tror att jag hellre vill höra spökhistorien.}
{200}{}{I know things that mere mortal man is not meant to know. Aiiieeee! Nyarloth... Oh, sorry (heh, heh). Got a little carried away
 there for a moment. I have tales of a Ghost that haunts these very grounds, as well as a Jan-u-wine Egypt-ee-an Mummy that you
 can see, right here in this marvelous sarcophagus.}
{201}{}{Tell me about the mummy. I'm just dying to hear more about that.}
{202}{}{I've just got to hear that ghost story. Uh, do I get a nice hot cup of cocoa to go with it?}
{203}{}{I don't think I have any more time to waste on whatever it is that you're hawking.}
{300}{}{Well, you see, (he motions you closer) there was once a great queen that ruled all of the surrounding town. She kept her
 throne by virtue of a special amulet that she kept around her neck at all times. Great stuff, huh?}
{301}{}{Uh, yeah. You bet. So this princess had a *magic* amulet. Oh, do go on. I just can't stand this level of suspense
 much longer (yawn).}
{302}{}{OK. I think I've heard just about enough. Goodbye.}
{400}{}{Well, I'll cut to the chase then. So, the evil wizard poisoned the young princess and took her amulet. She's been wandering
 around the room next door ever since. Well, uh, that is, just at the witching hour, anyway. That's why I keep the door locked.
 Pretty darn scary, huh?}
{401}{}{The ghost of an amuletless princess in the trashed room next door? That's it? I can't believe you're peddling *that* as a story.
 I'd rather hear about this stupid Mummy you're supposed to have here.}
{402}{}{OK. I think I've heard just about enough. Goodbye.}
