{100}{}{You see a member of the Slaver's Guild.}
{150}{}{You see Metzger, head of the Slaver's Guild.}
{151}{}{[TALA]}
{152}{}{Guards! Attack!}
{153}{}{[färdig]}
{154}{}{Come back in the morning damn it! I do my business during the day.}
{155}{}{[färdig]}
{156}{}{What is it now? You're really starting to piss me off.}
{157}{}{I would like to apologize.}
{158}{}{Sorry, I was drugged earlier. I didn't mean anything.}
{159}{}{Whoa, what's your problem?}
{160}{}{I wanted to ask you a question.}
{161}{}{Apparently I have. Good bye.}
{162}{}{Wah.}
{163}{}{Well, it's too late for that. Get out.}
{164}{}{Please, please, please; I'm sorry.}
{165}{}{Oh well, I tried.}
{166}{}{Screw you, then!}
{167}{}{Alright, alright. Apology accepted.}
{168}{}{Whew. Can I ask you some questions?}
{169}{}{I'm glad we straightened that out. See you later.}
{170}{}{Hello. It's good to see you.}
{171}{}{Hi Metzger. We need to talk.}
{172}{}{You too. Bye.}
{173}{}{Rap.}
{174}{}{I am Metzger, Head of the Slaver's Guild. Whatcha need?}
{175}{}{Yes, I have some questions.}
{176}{}{No thanks. I'll just go now.}
{177}{}{Swavuh???}
{178}{}{Please leave. Now.}
{179}{}{Or what?}
{180}{}{Alright. But I'll be back!}
{181}{}{OK. Bye.}
{182}{}{What would you like to know?}
{183}{}{About Trader Vic...}
{184}{}{Can I join the Slaver's Guild?}
{185}{}{I'd like to sell my husband into slavery.}
{186}{}{I'd like to sell my wife. How much?}
{187}{}{I'd like to sell one of my friends here.}
{188}{}{Tell me about the guild.}
{189}{}{What cities buy your slaves?}
{190}{}{I'd like to buy a slave.}
{191}{}{I'm looking for Vault 13. Have you heard of it?}
{192}{}{Metzger? That's a strange name.}
{193}{}{Nothing. I have to go.}
{195}{}{It's from an old language, prewar or something.}
{196}{}{Metzger means butcher. Fitting, don't you think?}
{197}{}{That was my great grandfather's name. He came from somewhere far to
 the east. Across a large body of water.}
{198}{}{I read some book about a Metzger. He was a president, or something.}
{199}{}{Look who's talking tribal.}
{200}{}{It's Germen, German, Garmen, or something. Ancient language, from a
 long time ago.}
{201}{}{Et tu, Brutus?}
{202}{}{I see. I still have a question, though.}
{203}{}{That is the dumbest thing I have ever heard.}
{204}{}{Fascinating. Gotta go.}
{205}{}{Our mission is to provide a steady and high-quality labor force to
 handle the ever-growing demands of the larger cities. Would you like to join?}
{206}{}{Sure. Sounds great.}
{207}{}{No way.}
{208}{}{I'll get back to you on that. What cities buy your slaves?}
{209}{}{Sorry, that's private guild information.}
{210}{}{OK. Sign me up!}
{211}{}{No! You guys are sick people!}
{212}{}{I'll consider that. I have more questions.}
{213}{}{Hmm, I'll come back later.}
{214}{}{We will need to brand a small marking on your forehead to show to all
 your allegiance with the slavers guild. Are you ready?}
{215}{}{Sounds great! Do it!}
{216}{}{I've changed my mind. Can I ask another question?}
{217}{}{I don't have time right now. I have to go.}
{218}{}{Welcome to the guild!}
{219}{}{Great, I have questions!}
{220}{}{OK, thanks. I'll be back.}
{221}{}{Vault 13? No. Wait... I think Vic's from Vault City. Maybe that's it.}
{222}{}{Yes, where is it?}
{223}{}{No. I have another question though.}
{224}{}{No, never mind.}
{225}{}{We sell most of our slaves to Vault City and New Reno. New Reno is
 south east of here and most of the Den trades with it.}
{226}{}{Where is Vault City?}
{227}{}{I have more questions.}
{228}{}{Thanks, gotta go.}
{229}{}{Vault City is east of here, and a little south. Vic's from there.}
{230}{}{I have more questions.}
{231}{}{Thanks; gotta go.}
{232}{}{Hmm, looks like a healthy slave. I'll give you }
{233}{}{ mynt.}
{234}{}{OK! It's a deal.}
{235}{}{Uh, never mind.}
{236}{}{No way! I want double!}
{237}{}{You drive a hard bargain. Here is your money!}
{238}{}{Thanks. I have some more questions.}
{239}{}{Tack. Hej då.}
{240}{}{Nåt annat?}
{241}{}{Yes, I have a question.}
{242}{}{Nope. Bye.}
{243}{}{Which "friend" are you selling?}
{244}{}{Um, never mind.}
{245}{}{Interesting. I'll give you }
{246}{}{ mynt.}
{247}{}{Såld!}
{248}{}{No, thanks.}
{249}{}{I want more money than that!}
{250}{}{Alright, I'll give you }
{251}{}{ but no more!}
{252}{}{Såld!}
{253}{}{Not good enough.}
{254}{}{That's way too little. I'm leaving.}
{255}{}{What do you want with Vic? He's my property now. He shouldn't have fucked with me.}
{256}{}{I'd like to buy him.}
{257}{}{Varför håller du honom här?}
{258}{}{Nothing. Never mind.}
{259}{}{Han är inte till salu, än.}
{260}{}{Varför inte?}
{261}{}{Oh, okay.}
{262}{}{Han kommer att kosta $2000.}
{263}{}{Här får du dina pengar.}
{264}{}{Det är en hel del. Kanske senare.}
{265}{}{Kostnaden är $1000.}
{266}{}{Här får du dina pengar.}
{267}{}{Har inte så mycket än. Hej då.}
{268}{}{Vår radio är trasig och han är ansvarig för att laga den.}
{269}{}{I see.}
{270}{}{Du har inte pengarna!}
{271}{}{Synd för mig. Får jag fråga dig en sak?}
{272}{}{Ledsen, jag kommer tillbaka.}
{307}{}{Hur vågar du återvända efter att ha övergett dina bröder under en slavjakt! Vakter! Anfall!}
{308}{}{[färdig]}
{309}{}{Utmärkt! Det kan ta några dagar för dig att resa fram och tillbaka. Är du redo att åka nu?}
{310}{}{Nej. Jag kommer tillbaka.}
{311}{}{Ja, jag är redo. Nu drar vi.}
{312}{}{Ah, du är tillbaka från slavjakten. Nu ska vi se hur det gick för dig...}
{313}{}{[mer]}
{314}{}{[mer]}
{315}{}{Du dödade potentiella slavar! En död man ger oss ingen inkomst! Döda bara de som är ett hot,
 de andra är inget hot.}
{316}{}{[mer]}
{317}{}{Ni återtog inga slavar alls! Vad fan är det för fel på dig? Vi försöker tjäna pengar här,
 inte förlora dem.}
{318}{}{[mer]}
{319}{}{Överlag gjorde du bra ifrån dig den här rundan. Fortsätt med det goda arbetet så kanske jag behåller dig ett tag till.}
{320}{}{Tack så mycket. Det ska jag göra.}
{321}{}{Jag vet inte om jag gillar det här så mycket.}
{322}{}{Du måste förbättra din förslavningsteknik.}
{323}{}{Jag ska försöka.}
{324}{}{Jag ber om ursäkt för min dåliga prestation.}
{325}{}{Jag tror att jag är tillräckligt bra.}
{326}{}{Damn it! You did terribly in this Run. Are you trying to ruin me? Be more careful next time.
 You don't need to kill them all! Just kill off the hostile ones. Leave the unarmed ones for collection.}
{327}{}{I'm sorry, Metzger.}
{328}{}{Hey, it's tough work to be a Slaver!}
{329}{}{I'd like to see you do better.}
{330}{}{I'd like to go on a slave run.}
{331}{}{Damn it! I hate losing any guild member on a Run. Try to watch each other's back!}
{332}{}{Overall, you did well this Run. Here is $}
{333}{}{ as an incentive for you to keep up the good work.}
