{100}{}{You see a customer.}
{101}{}{You see a townsperson.}
{150}{}{He looks like he's headed somewhere.}
{151}{}{She looks like she's headed somewhere.}
{152}{}{He's busy drinking and talking to other customers.}
{153}{}{She seems to be busy talking.}
{154}{}{He's looking over Tubby's shelves.}
{155}{}{She seems to be looking around Tubby's store.}
{156}{}{You don't see anything unusual about him.}
{157}{}{You don't see anything unusual about her.}
{200}{}{Försvinn från mig!}
{201}{}{Lämna mig ifred!}
{202}{}{Don't touch me!}
{203}{}{Stop it!}
{204}{}{Vad är det du gör?}
{300}{}{Sorry, can't talk now.}
{301}{}{Where was I going again?}
{302}{}{Hej.}
{303}{}{Excuse me.}
{304}{}{Hej.}
{305}{}{Becky's place is the best, and not just cuz of the prices.}
{306}{}{You here for the drinks or the tables?}
{307}{}{All we need now are some troubadours.}
{308}{}{Hej.}
{309}{}{You a gambler?}
{310}{}{How's the outside world?}
{311}{}{Frankie's a scum bag. He's mean to Becky for no reason.}
{312}{}{You a friend of Becky?}
{313}{}{Grab a drink, friend!}
{314}{}{Drink up! Drinks are cheap!}
{315}{}{There's no way these are watered down.}
{316}{}{That Dyer sure knows her stuff.}
{317}{}{Nothing like good drinks and good company.}
{318}{}{Only trouble with Becky's drinks is you tend to drink to many!}
{319}{}{Becky... I mean Rebecca sure is a sweetheart.}
{320}{}{If anyone ever lays a finger on her, they'll regret it.}
{321}{}{This is some good stuff.}
{340}{}{We should kill you for what you did.}
{341}{}{Jag vet inte vad hon gjorde mot dig, men hon förtjänade inte att dö.}
{342}{}{Vi kanske ska åka till New Reno, eftersom Becky's är stängt.}
{343}{}{Jag saknar Beckys leende.}
{344}{}{Ingen mer billig sprit.}
{345}{}{Lyan är inte densamma utan Becky's.}
{360}{}{Frankie's is truly a hole... in the wall, that is.}
{361}{}{Jag gillar Hålet bättre än Becky's.}
{362}{}{Vi kallar den här platsen för Hålet.}
{363}{}{Sätt dig ner. Åh, vänta lite. Kanske inte.}
{364}{}{Frankie's has action. Becky's is just a money pit.}
{365}{}{Frankie gillar verkligen inte Becky.}
{366}{}{Frankie säger att Beckys drinkar är urvattnade.}
{367}{}{Hur går det?}
{368}{}{Frankie vet hur man festar.}
{369}{}{Beckys bord är riggade! Eller, det är i alla fall vad Frankie säger.}
{370}{}{Botten upp!}
{390}{}{Fan, jag varnade Frankie för hur han behandlade folk.}
{391}{}{Frankie borde ha hållit sig i skinnet.}
{392}{}{Var ska vi nu hänga?}
{393}{}{Synd att Frankie är borta. Han visste hur man festade.}
{394}{}{Du har ett riktigt temperament. Vad har Frankie gjort mot dig?}
{395}{}{Har Frankie förolämpat din mamma eller nåt?}
{410}{}{I'm just looking around.}
{411}{}{Jag är inte säker på vad jag letar efter.}
{412}{}{Tubby sure goes through a lot of Jet.}
{413}{}{Har du sett något bra?}
{414}{}{Inte mycket här.}
{415}{}{Tubby needs to get some better suppliers.}
{416}{}{You need drugs? Tubby is normally well stocked.}
{430}{}{What did you kill Tubby for?}
{431}{}{No great loss, but Tubby was the only real shop in town.}
{432}{}{What'd Tubby do to piss you off?}
{433}{}{Tubby sold you some bad shit, didn't he?}
{434}{}{The rumor is you whacked Tubby because of a bad deal or something.}
{435}{}{Not surprised really. A lot of people have been sore with Tubby lately.}
{440}{}{Nothing I'm interested in today...}
{441}{}{Oh, hi. Just talking to my good friend Flick.}
{442}{}{What are you doing in here?}
{443}{}{You a friend of Flick's, too?}
{444}{}{I didn't do anything.}
{445}{}{What are you staring at?}
{446}{}{Just pretend you don't see me.}
{447}{}{Bry dig inte om mig.}
{460}{}{Fan också. Du dödade Flick.}
{461}{}{Lurade Flick dig?}
{462}{}{Flick's been into some dangerous work.}
{463}{}{That sucks about Flick.}
{464}{}{Wonder what all those kids are going to do now that Flick is dead.}
{465}{}{Surprised Flick lasted this long.}
{480}{}{We call this home.}
{481}{}{Most of us grew up on Mom's cooking.}
{482}{}{I've known Mom since I was a kid.}
{483}{}{Mom takes care of everyone in the Den.}
{484}{}{Mom can make a sandwich out of anything.}
{485}{}{I hope you get to know Mom as well as us.}
{486}{}{Great company, great food. What else could you ask for?}
{487}{}{Skål!}
{488}{}{Hej.}
{500}{}{How could you have hurt poor old Mom?}
{501}{}{I've known, I mean, knew Mom all my life.}
{502}{}{What did she ever do to you?}
{503}{}{Murderer! Poor Mom...}
{504}{}{Why did you have to do that?}
{505}{}{You heartless monster!}
