{100}{}{Du ser en tunn, oljig man.}
{150}{}{Du ser Flick, som kliar sig ordentligt i skrevet.}
{151}{}{Du ser en oren man med en otäck ansiktsryckning.}
{200}{}{Draa hääifrån, din idiot.}
{201}{}{Hörru, köttbullen! Ja, du. Draa hääirån.}
{202}{}{Är du dum elle'?}
{203}{}{Whatchur problem, eh?}
{204}{}{Draa hääifrån, fö' i helvette}
{220}{}{Hallå dä', jag ä' Flick. Vad i helvete vill du, va?}
{221}{}{Now what? You wastin' my time heeya.}
{222}{}{Vad är grejen med den knäppa dialekten, Flick?}
{223}{}{Vad i helvete gör du häromkring?}
{224}{}{Jag letar efter ett Valv - och en handelsman som heter Vic också. Vet du var de kan vara?}
{225}{}{Jag skulle vilja byta med dig.}
{240}{}{That 'bout do it for ya, pal?}
{241}{}{Egentligen skulle jag vilja ta en titt till på dina varor om jag får.}
{242}{}{Jag skulle faktiskt vilja ställa en fråga till dig.}
{243}{}{Det var allt. Vi ses, Flick.}
{260}{}{I'm a fuckin' provider, waddya think? I'm like a good Samurai-itan guy.}
{261}{}{Vad sa du?}
{262}{}{Ja, eh, nåja.. låt mig fråga dig något annat.}
{263}{}{Eh, åh. OK, Hej då, Flick.}
{280}{}{Jag försörjer fö' de små paisanos.}
{281}{}{Försörjer du små pianon?}
{290}{}{Pai-san-o, du vet, barnen. Mina barn.}
{291}{}{Dina barn?}
{292}{}{Jag är inte riktigt intresserad av musiklektioner för barn. Låt mig fråga dig om något annat.}
{300}{}{Ja, de jobbar för mig. De ger mig saker. Små saker. Du vet.}
{301}{}{Uh, no.}
{302}{}{Åh, okej. Låt mig fråga dig något annat då.}
{303}{}{Jaha, jag förstår. Jag vill inte störa din, eh, stil. Hej då.}
{315}{}{They bring me stuff that they find. Little, little things. Stuff no one ain't usin' no more. In return, I takes care of 'em.}
{316}{}{Låter som ett trevligt arrangemang.}
{325}{}{(Flick rycker på axlarna) Jag klarar mig bra.}
{326}{}{Låt mig fråga dig om något annat då.}
{327}{}{De måste ha gett dig några riktiga fynd. Låt mig se vad du har.}
{328}{}{Jag kollar bara. Hej då, Flick.}
{340}{}{Vad snackar 'u om? Tror du att jag är en dum jävla pirla? Nån dum filio di puttana? Tror du att jag är nån sorts clown? Är jag här för att roa dig, va?}
{341}{}{Eh, nej. Förlåt, jag var bara nyfiken. Låt mig fråga dig om något annat.}
{342}{}{Ja, det stämmer, skitskalle. Och inget kommer att roa mig mer än dina dödsryckningar.}
{343}{}{Tja, om du ska bli upprörd över det så går jag.}
{360}{}{Vault huh? Maybe Momma knows about that, 'cause I don't. But that Vic guy - him I know. Metzger's got that porca pistola.}
{361}{}{Vic? Ain't that him with you? You biota. But Momma, her I know.}
{362}{}{Who's Metzger?}
{363}{}{Who's Momma?}
{364}{}{Thanks. Let me ask you something else.}
{365}{}{Thanks, that's all I need to know. Goodbye.}
{380}{}{Momma runs a food place over in da East side a town. Just past the graveyard. Nice place, she got good pasta, Mama mia.}
{381}{}{Thanks, What about that Metzger fellow that's got Vic?}
{382}{}{Thanks. Let me ask you something else.}
{383}{}{Thanks, that's all I need to know. Goodbye.}
{400}{}{That's right. Metzger, that stronzo, he's dead. I don't know what happen to Vic.}
{401}{}{That Metzger, he's a real rompiballe, that one. Runs the Slaver's Guild. East side of town, just north of Momma's. Anyhow, he got Vic, I know.}
{402}{}{Thanks, now what about Momma?}
{403}{}{Thanks. Let me ask you something else.}
{404}{}{Thanks, that's all I need to know. Goodbye.}
