{100}{}{Du ser en vakt.}
{150}{}{He's one of Tyler's guards.}
{151}{}{She's one of Tyler's guards.}
{200}{}{You still alive?}
{210}{}{We showed them, didn't we?}
{211}{}{No one messes with us.}
{212}{}{We kicked ass.}
{213}{}{About time we finished them off.}
{214}{}{I can't forget the look on his face. It was great.}
{215}{}{I'm surprised Metzger didn't get pissed.}
{216}{}{I wonder why Metzger didn't step in.}
{225}{}{I don't know why Metzger has us guard this shit.}
{226}{}{Who's going to try and steal this crap?}
{227}{}{This job is a cakewalk.}
{228}{}{No one ever messes with us.}
{229}{}{I think this stuff came from a Vault or something.}
{230}{}{What are you looking for anyway?}
{231}{}{There's nothing in here but us mice.}
{232}{}{Don't waste your time, we've checked this stuff over a million times.}
{233}{}{Tonight's the night.}
{234}{}{I hate waiting.}
{235}{}{I'll pass up drinks for this anytime.}
{236}{}{Är det dags än? Jag kan knappt bärga mig.}
{237}{}{I hope I get the first kill.}
{238}{}{Varför har de väntat tills nu med att bråka med oss?}
{239}{}{Det här kommer att bli intressant.}
{240}{}{Synd bara att vi inte fick strida trots allt.}
{241}{}{Jag undrar varför de ändrade sig.}
{242}{}{All denna väntan och ingenting.}
{243}{}{Vad hände med fällan som du skulle hjälpa oss att gillra?}
{244}{}{Vad hände häromnatten?}
{245}{}{Synd att de fegisarna drog sig ur. Det hade varit trevligt att göra slut på dem.}
{246}{}{Jag kan inte tro att de jävlarna skulle försöka lägga sig i bakhåll för oss.}
