{100}{}{Du ser en gangster.}
{150}{}{Han verkar vara medlem i Laras gäng.}
{151}{}{Hon verkar vara medlem i Laras gäng.}
{200}{}{Wise guy.}
{201}{}{Där får du.}
{202}{}{Hämnd.}
{203}{}{Kom hit.}
{204}{}{Jag är inte färdig med dig.}
{205}{}{Subba.}
{225}{}{Undrar hur länge det kommer att hålla i sig här nu när Metzger är borta?}
{226}{}{Så Metzger är äntligen död?}
{227}{}{Var det ditt hantverk?}
{228}{}{Lyan kommer aldrig att bli sig lik igen.}
{240}{}{Jag kan inte tro det, vi slog dem faktiskt!}
{241}{}{Metzger måste visa oss respekt nu.}
{242}{}{Vi visade dem verkligen.}
{243}{}{Vi gav 'em vår egen typ av rättvisa.}
{244}{}{Vi skulle inte ha klarat det utan dig!}
{245}{}{Tack för din hjälp!}
{246}{}{Vi klarade det!}
{247}{}{Jävlas du med oss?}
{248}{}{Det är bäst att du är försiktig med var du går.}
{249}{}{Lara är den enda anledningen till att vi inte hänger dig nu.}
{250}{}{Vad försökte du åstadkomma?}
{251}{}{Ynkrygg.}
{252}{}{Du gör mig illamående.}
{253}{}{Försvinn.}
{254}{}{Beat it.}
{255}{}{Vi är redo när du är det.}
{256}{}{Det är på tiden att vi hämnas på dem.}
{257}{}{I hate waiting.}
{258}{}{Let's go already.}
{259}{}{Är du redo än?}
{260}{}{Säg bara till Lara när det är dags.}
{270}{}{Vill du gå med i vårt gäng?}
{271}{}{Du måste vara här för att träffa Lara.}
{272}{}{How's it going?}
{273}{}{Lara är den du borde prata med.}
{274}{}{Hej.}
{275}{}{Är du här för att träffa Lara?}
{300}{}{Hej.}
{301}{}{How's it going?}
{302}{}{Hoppas att allt går bra.}
{303}{}{Så du kanske kan hjälpa oss?}
{304}{}{Kul att se dig.}
{305}{}{We'll pay back Tyler soon...}
{306}{}{Any new developments?}
{310}{}{Thanks for the help. Too bad about Lara.}
{311}{}{We finally got em!}
{312}{}{We couldn't have done this without you.}
{313}{}{At least Lara went out in fight.}
{314}{}{I can't believe Lara didn't make it.}
{315}{}{We sure showed Metzger who's best.}
{316}{}{Metzger's better off with us.}
{350}{}{You said it!}
{351}{}{They're dead meat!}
{352}{}{We're going to kick some serious ass!}
