{100}{}{Du ser en gangster.}
{150}{}{Han verkar vara medlem i Laras gäng.}
{151}{}{Hon verkar vara medlem i Laras gäng.}
{200}{}{Wise guy.}
{201}{}{Där får du.}
{202}{}{Hämnd.}
{203}{}{Kom hit.}
{204}{}{Jag är inte färdig med dig.}
{205}{}{Subba.}
{225}{}{Undrar hur länge det kommer att hålla i sig här nu när Metzger är borta?}
{226}{}{Så Metzger är äntligen död?}
{227}{}{Var det ditt hantverk?}
{228}{}{Lyan kommer aldrig att bli sig lik igen.}
{240}{}{Jag kan inte tro det, vi slog dem faktiskt!}
{241}{}{Metzger måste visa oss respekt nu.}
{242}{}{Vi visade dem verkligen.}
{243}{}{Vi gav 'em vår egen typ av rättvisa.}
{244}{}{Vi skulle inte ha klarat det utan dig!}
{245}{}{Tack för din hjälp!}
{246}{}{Vi klarade det!}
{247}{}{Jävlas du med oss?}
{248}{}{Det är bäst att du är försiktig med var du går.}
{249}{}{Lara's the only reason we don't string you up right now.}
{250}{}{What were you trying to pull?}
{251}{}{Ynkrygg.}
{252}{}{You make me sick.}
{253}{}{Get lost.}
{254}{}{Beat it.}
{255}{}{We're ready when you are.}
{256}{}{It's about time we pay them back.}
{257}{}{I hate waiting.}
{258}{}{Let's go already.}
{259}{}{You ready yet?}
{260}{}{Just let Lara know when it's time.}
{270}{}{You looking to join up?}
{271}{}{You must be here to see Lara.}
{272}{}{How's it going?}
{273}{}{Lara's the person you should be talking to.}
{274}{}{Hej.}
{275}{}{You here to see Lara?}
{300}{}{Hej.}
{301}{}{How's it going?}
{302}{}{Hope things are going good.}
{303}{}{So you might be able to help us out?}
{304}{}{Good to see you.}
{305}{}{We'll pay back Tyler soon...}
{306}{}{Any new developments?}
{310}{}{Thanks for the help. Too bad about Lara.}
{311}{}{We finally got em!}
{312}{}{We couldn't have done this without you.}
{313}{}{At least Lara went out in fight.}
{314}{}{I can't believe Lara didn't make it.}
{315}{}{We sure showed Metzger who's best.}
{316}{}{Metzger's better off with us.}
{350}{}{You said it!}
{351}{}{They're dead meat!}
{352}{}{We're going to kick some serious ass!}
