{100}{}{Du ser ägaren till salongen.}
{101}{}{You see Becky.}
{150}{}{This looks like the owner.}
{151}{}{Det här är Becky, ägaren av det här stället.}
{152}{}{[TALA]}
{153}{}{Hello, stranger, and welcome to my saloon. I'm Becky.}
{154}{}{Hello, I am }
{155}{}{. Vad finns det att göra här omkring?}
{156}{}{Hi, I'm }
{157}{}{. Can I ask some questions?}
{158}{}{Mamma?}
{159}{}{Mag gah.}
{160}{}{Run along. I don't need your kind here.}
{161}{}{Mmmm...}
{162}{}{Screw you.}
{163}{}{I'm going.}
{164}{}{Sorry, no offense was meant. Can I ask something?}
{165}{}{En whisky kostar $5 och spelborden står där borta. Ha det så trevligt.}
{166}{}{Can I ask a question?}
{167}{}{I want a drink!}
{168}{}{Hmm, those are some cheap drinks. Let's see one.}
{169}{}{Tack. Hej då.}
{170}{}{Valv 13? Nej, aldrig hört talas om det.}
{171}{}{Hmm, can I ask something else?}
{172}{}{Fan, jag måste hitta det. Hej då.}
{173}{}{What would you like to know?}
{174}{}{Where's a good place to eat?}
{175}{}{Vet du var Valv 13 ligger?}
{176}{}{Why are your drinks so cheap?}
{177}{}{Nothing. Bye.}
{178}{}{Mamma driver en liten restaurang på andra sidan stan.}
{179}{}{Mamma! Mamma!}
{180}{}{En fråga till.}
{181}{}{Tack. Hej då.}
{182}{}{Beat it.}
{183}{}{Gwah.}
{184}{}{Jag ska ge dig nåt att slå.}
{185}{}{En snabb fråga först?}
{186}{}{Hej då.}
{187}{}{En shot whisky kostar $5. Betala först.}
{188}{}{Vadå?}
{189}{}{Här är pengarna.}
{190}{}{Jag ändrade mig.}
{191}{}{Jag har lite ont om pengar. Kan jag få en nota?}
{192}{}{Can I ask a question?}
{193}{}{Måste dra.}
{194}{}{Här är drinken. Något annat?}
{195}{}{Fråga?}
{196}{}{Yeha, how about you and I...}
{197}{}{Näpp.}
{198}{}{Hey, you don't enough cash for this drink. You're poorer than even these sops!}
{199}{}{Förlåt.}
{200}{}{Hmm, I'll come back.}
{201}{}{Hmm. Let me get someone to watch the bar. You and I can go into the back room and play a little
 game I call "First Strike." If you're good, well, there's "Ground Zero."}
{202}{}{OK!}
{203}{}{Er... uh... I have to go.}
{205}{}{You were OK.}
{206}{}{Nästa gång spelar vi "In i Strålningen." Men för tillfället...}
{207}{}{Can you do something for me?}
{208}{}{I have to go, but I'll come back.}
{209}{}{What can I do for you, sweet cheeks?}
{210}{}{I need some more lovin'.}
{211}{}{I got some questions.}
{212}{}{Hur kan du sälja dina drinkar så billigt?}
{213}{}{Vad sägs om en drink?}
{214}{}{Måste sticka. Vi ses.}
{215}{}{Inte nu. Kanske senare. Ja, definitivt senare.}
{216}{}{Can I ask a question?}
{217}{}{Later then.}
{218}{}{I have a still in the basement. I made it myself. Beats paying triple to those New Reno
 gangsters.}
{219}{}{Smart tjej! Det gillar jag!}
{220}{}{Hmm, jag måste gå. Vi ses senare.}
{221}{}{Varför? Varför förstörde du min destillationsapparat? Din jävel!}
{222}{}{Inget personligt. Jag fick betalt för att göra det.}
{223}{}{Jag är ledsen.}
{224}{}{Hej då.}
{225}{}{Jag gör bara en till, vet du.}
{226}{}{Jag vet.}
{227}{}{Ja, det är bra.}
{228}{}{Hej då.}
{232}{}{Varför? Varför förstörde du min destillationsapparat? Din subba!}
{233}{}{Var är du, älskling?}
{234}{}{Kommer du?}
{235}{}{Jag väntar.}
{236}{}{Jag är här inne, älskling.}
{237}{}{Jag har en bar att sköta.}
{238}{}{Följ mig, sötnos.}
{240}{}{Hur gjorde du... Det där... Öhhh...}
{241}{}{Det är okej, storleken spelar ingen roll.}
{242}{}{Det var, ehhh, trevligt -- antar jag.}
{243}{}{Tack, raring. Det var kul.}
