{100}{}{You see a big, primitive looking man.}
{101}{}{This man looks fairly strong and alert.}
{110}{}{You see a slender primitive woman.}
{111}{}{She seems strong despite her size.}
{120}{}{You see a strange looking man.}
{121}{}{He seems to be awfully thin.}
{130}{}{You see a ragged looking man.}
{131}{}{This one looks fairly strong.}
{140}{}{You see a man in tattered clothing.}
{141}{}{He moves with suggesting speed.}
{150}{}{You see a very grimy woman.}
{151}{}{She doesn't seem to have ever bathed.}
{160}{}{You see a rather large woman.}
{161}{}{Hon ser ut som stark kämpe.}
{170}{}{You see a scrawny looking woman.}
{171}{}{Den här verkar inte vara något större problem.}
{200}{}{Dö!}
{201}{}{Where you at?}
{202}{}{I'm gunna hurt you.}
{210}{}{I'm going to get your for this!}
{211}{}{God damn slavers!}
{212}{}{You'll pay for this!}
{220}{}{Leave alone!}
{221}{}{Don't hurt!}
{222}{}{No hurt you!}
{223}{}{I don't fight!}
{230}{}{I recognize that tattoo!}
{231}{}{No, please!}
{232}{}{Please don't kill me!}
{233}{}{I won't fight; don't kill me!}
{234}{}{Please, I don't want to die!}
{235}{}{You're slavers aren't you? Oh, god.}
{245}{}{Tyst! De närmar sig.}
{246}{}{Kill bad men.}
{247}{}{Inte ta familj från mig.}
{248}{}{Jag skydda familj.}
{249}{}{Får inte hitta oss.}
{250}{}{De dåliga människor.}
{260}{}{Slavhandlare kommer. Tysta allihop.}
{261}{}{Get ready; I think they're close now.}
{262}{}{Jag tänker inte ge mig utan strid.}
{263}{}{De kommer aldrig att förslava oss.}
{264}{}{De där slavhandlarna ska få betala för det här.}
{265}{}{Ingen slavhandlare kommer att ta min familj.}
{270}{}{They no find me.}
{271}{}{Must hide. Must hide.}
{272}{}{Why they want hurt.}
{273}{}{Me scared.}
{274}{}{Me no fight.}
{275}{}{Me want live.}
{276}{}{No hurt family.}
{280}{}{Oh, shit!}
{281}{}{Why are they doing this?}
{282}{}{What about my family?}
{283}{}{I don't want to die.}
{284}{}{I don't want to be a slave.}
{285}{}{I deserve better than this.}
{290}{}{Du dör nu!}
{291}{}{Jag döda!}
{292}{}{Du inte skada familj!}
{293}{}{Du inte ta familj!}
{294}{}{Jag skydda!}
{295}{}{Jag skada dig!}
{296}{}{Du betala!}
{300}{}{Du kommer inte att få ta min familj, slavhandlare!}
{301}{}{Dö, slavdrivande avskum!}
{302}{}{Du ska få betala, din jävel!}
{303}{}{I'll fight to the death for my family!}
{304}{}{You won't get away with this!}
{305}{}{You're not leaving here with my friends!}
{310}{}{Ahhh!}
{311}{}{No kill! No kill!}
{312}{}{Stopp!}
{313}{}{Hjäääälp!}
{314}{}{Spring!}
{315}{}{No do that!}
{320}{}{Run for your lives!}
{321}{}{Don't let them catch you!}
{322}{}{Slavers! Run for it!}
{323}{}{Help someone! Please!}
{324}{}{Run for it, Marty!}
{325}{}{Ahhh!}
{326}{}{Stop the insanity!}
{327}{}{We didn't do anything! Leave us alone!}
