{100}{}{Du ser en trädörr.}
{101}{}{Du ser en metalldörr.}
{102}{}{Du ser en robust dörr med ett lås (som kan dyrkas upp med
 dyrkar) och en högexplosiv fälla i dörrkarmen, som
 du kanske kan bända upp.}
{103}{}{Du ser en robust dörr med ett lås på och en högexplosiv 
 fälla i dörrkarmen, som du kanske kan
 bända upp.}
{104}{}{Du ser en robust dörr utan uppenbar låsanordning och
 en högexplosiv fälla i dörrkarmen, som du kanske kan
 bända upp.}
{105}{}{Du ser en robust dörr med ett gammalt rostigt lås och en högexplosiv 
 fälla i dörrkarmen, som du kanske kan bända 
 upp.}
{106}{}{Du ser en robust dörr med ett lås (som kan öppnas 
 med dyrkar) och en fälla i dörrkarmen, som du kanske kan
 bända upp.}
{107}{}{Du ser en robust dörr med ett lås på och en fälla i
 dörrkarmen, som du kanske kan bända upp.}
{108}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en fälla i dörrkarmen, som du kanske kan bända upp.}
{109}{}{Du ser en robust dörr med ett gammalt, rostigt lås och en fälla
 i dörrkarmen, som du kanske kan bända upp.}
{110}{}{Du ser en robust dörr med ett lås (som kan öppnas 
 med dyrkar) och en fälla i dörrkarmen, som du kanske kan
 bända upp.}
{111}{}{Du ser en robust dörr med ett lås på och en avklippt sladd
 i dörrkarmen, som du kanske kan bända upp.}
{112}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en avklippt sladd i dörrkarmen, som du kanske kan bända
 upp.}
{113}{}{Du ser en robust dörr med ett gammalt, rostigt lås och en avklippt
 sladd i dörrkarmen, som du kanske kan bända upp.}
{114}{}{Du ser en robust dörr med ett lås (som kan dyrkas upp med
 dyrkar), som du kanske kan bända upp.}
{115}{}{Du ser en robust dörr med ett lås på, som du kanske kan
 bända upp.}
{116}{}{Du ser en robust dörr utan synbar låsanordning,
 som du kanske kan bända upp.}
{117}{}{Du ser en robust dörr med ett gammalt rostigt lås som
 du kanske kan bända upp.}
{118}{}{Du ser en robust dörr med ett lås (som kan dyrkas upp med
 dyrkar) och en högexplosiv fälla i dörrkarmen.}
{119}{}{Du ser en robust dörr med ett lås på och en högexplosiv
 fälla i dörrkarmen.}
{120}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en högexplosiv fälla i dörrkarmen.}
{121}{}{Du ser en robust dörr med ett gammalt rostigt lås och en högexplosiv
 fälla i dörrkarmen.}
{122}{}{Du ser en robust dörr med ett lås (som kan dyrkas upp med
 dyrkar) och en fälla i dörrkarmen.}
{123}{}{Du ser en robust dörr med ett lås på och en fälla i
 dörrkarmen.}
{124}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en fälla i dörrkarmen.}
{125}{}{Du ser en robust dörr med ett gammalt, rostigt lås och en fälla
 i dörrkarmen.}
{126}{}{Du ser en robust dörr med ett lås (som kan dyrkas upp med
 dyrkar) och en avklippt sladd i dörrkarmen.}
{127}{}{Du ser en robust dörr med ett lås på och en avklippt sladd
 i dörrkarmen.}
{128}{}{Du ser en robust dörr utan någon uppenbar låsanordning och
 en avklippt sladd i dörrkarmen.}
{129}{}{Du ser en robust dörr med ett gammalt, rostigt lås och en avklippt
 sladd i dörrkarmen.}
{130}{}{Du ser en robust dörr med ett lås (som kan dyrkas upp med
 dyrkar) på den.}
{131}{}{Du ser en robust dörr med ett lås på.}
{132}{}{Du ser en robust dörr utan någon uppenbar låsanordning.}
{133}{}{Du ser en robust dörr med ett gammalt, rostigt lås.}
{134}{}{Du ser en skadad dörr med ett lås (som kan dyrkas upp med
 dyrkar) och en högexplosiv fälla i dörrkarmen.}
{135}{}{Du ser en skadad dörr med ett lås på och en högexplosiv
 fälla i dörrkarmen.}
{136}{}{Du ser en skadad dörr utan någon uppenbar låsanordning och
 en högexplosiv fälla i dörrkarmen.}
{137}{}{Du ser en robust dörr med ett gammalt rostigt lås och en högexplosiv
 fälla i dörrkarmen.}
{138}{}{Du ser en skadad dörr med ett lås (som kan dyrkas upp med
 dyrkar) och en fälla i dörrkarmen.}
{139}{}{Du ser en skadad dörr med ett lås på och en fälla i
 dörrkarmen.}
{140}{}{Du ser en skadad dörr utan någon uppenbar låsanordning och
 en fälla i dörrkarmen.}
{141}{}{Du ser en skadad dörr med ett gammalt, rostigt lås och en fälla
 i dörrkarmen.}
{142}{}{Du ser en skadad dörr med ett lås (som kan dyrkas upp med
 dyrkar) och en avklippt sladd i dörrkarmen.}
{143}{}{Du ser en skadad dörr med ett lås på och en avklippt sladd
 i dörrkarmen.}
{144}{}{Du ser en skadad dörr utan någon uppenbar låsanordning och
 en avklippt sladd i dörrkarmen.}
{145}{}{Du ser en skadad dörr med ett gammalt, rostigt lås och en avklippt
 sladd i dörrkarmen.}
{146}{}{Du ser en skadad dörr med ett lås (som kan dyrkas upp med
 dyrkar).}
{147}{}{Du ser en skadad dörr med ett lås på.}
{148}{}{Du ser en skadad dörr utan synbar låsanordning.}
{149}{}{Du ser en skadad dörr med ett gammalt, rostigt lås.}
{150}{}{Du ser en gammal dörr med ett lås (som kan dyrkas upp med
 låsvrickor) och en högexplosiv fälla i dörrkarmen.}
{151}{}{Du ser en gammal dörr med ett lås på och en högexplosiv
 fälla i dörrkarmen.}
{152}{}{Du ser en gammal dörr utan någon uppenbar låsanordning och
 en högexplosiv fälla i dörrkarmen.}
{153}{}{Du ser en gammal dörr med ett gammalt rostigt lås och en högexplosiv
 fälla i dörrkarmen.}
{154}{}{Du ser en gammal dörr med ett lås (som kan dyrkas upp med
 dyrkar) och en fälla i dörrkarmen.}
{155}{}{Du ser en gammal dörr med ett lås på och en fälla i.
 dörrkarmen.}
{156}{}{Du ser en gammal dörr utan någon uppenbar låsanordning och
 en fälla i dörrkarmen.}
{157}{}{Du ser en gammal dörr med ett gammalt, rostigt lås och en fälla
 i dörrkarmen.}
{158}{}{Du ser en gammal dörr med ett lås (som kan dyrkas upp med
 dyrkar) och en avklippt sladd i dörrkarmen.}
{159}{}{Du ser en gammal dörr med ett lås på och en avklippt sladd
 i dörrkarmen.}
{160}{}{Du ser en gammal dörr utan någon uppenbar låsanordning och
 en avklippt sladd i dörrkarmen.}
{161}{}{Du ser en gammal dörr med ett gammalt, rostigt lås och en avklippt
 sladd i dörrkarmen.}
{162}{}{Du ser en gammal dörr med ett lås (som kan dyrkas upp med
 dyrkar).}
{163}{}{Du ser en gammal dörr med ett lås på.}
{164}{}{Du ser en gammal dörr utan någon uppenbar låsanordning.}
{165}{}{Du ser en gammal dörr med ett gammalt, rostigt lås.}
{166}{}{You set off the trap and were hit for }
{167}{}{ skadepoäng.}
{168}{}{ sets off the trap and was hit for }
{169}{}{ skadepoäng.}
{170}{}{Du dyrkar skickligt upp låset på dörren.}
{171}{}{Your lack of skill has jammed the lock on this door.}
{172}{}{Du lyckas inte dyrka upp låset på den här dörren.}
{173}{}{ dyrkar skickligt upp låset på dörren.}
{174}{}{'s lack of skill has jammed the lock on this door.}
{175}{}{ misslyckades med att dyrka upp låset på den här dörren.}
{176}{}{Du slår bort låset från dörren.}
{177}{}{You strain your back while trying to bust the lock and
 take a point of damage.}
{178}{}{You strain your back while trying to bust the lock and
 take }
{179}{}{ skadepoäng.}
{180}{}{Du är för svag för att bryta upp låset.}
{181}{}{ slår bort låset från dörren.}
{182}{}{ strains his back while trying to bust the lock and takes
 a point of damage.}
{183}{}{ strains his back while trying to bust the lock and takes }
{184}{}{ skadepoäng.}
{185}{}{ är för svag för att bryta upp låset.}
{186}{}{ strains her back while trying to bust the lock and takes
 a point of damage.}
{187}{}{ strains her back while trying to bust the lock and takes }
{188}{}{ skadepoäng.}
{189}{}{You deftly lock the door.}
{190}{}{You fail to lock the door.}
{191}{}{ deftly locks the door.}
{192}{}{ failed to lock the door.}
{193}{}{That doesn't even put a scratch on the door.}
{194}{}{You find a trap on the door.}
{195}{}{You fail to find any traps on the door.}
{196}{}{You skillfully disarm the trap.}
{198}{}{You fail to disarm the trap.}
{199}{}{ finds a trap on the door.}
{200}{}{ fails to find any traps on the door.}
{201}{}{ skillfully disarms the trap.}
{202}{}{ fails to disarm the trap.}
{203}{}{The door appears to be locked.}
{204}{}{You notice a trap in the door jamb.}
{205}{}{ notices a trap in the door jamb.}
{206}{}{You are unable to place a trap on this door, because
 the door is open.}
{207}{}{ is unable to place a trap on this door, because the
 door is open.}
{208}{}{You skillfully set a trap in the door frame.}
{209}{}{You fail to properly set the trap in the door frame.}
{210}{}{ skillfully sets a trap in the door frame.}
{211}{}{ fails to properly set the trap in the door frame.}
{300}{}{Du låser upp dörren.}
{301}{}{Du låser dörren.}
{302}{}{Du kan inte låsa den här dörren medan den är öppen.}
{303}{}{Den nyckeln passar inte i det här låset.}
{320}{}{Det finns inget sätt att låsa den här dörren.}
{330}{}{Denna dörr har fastnat öppen.}
{400}{}{Du låser upp dörren.}
{414}{}{Du ser en robust dörr med ett lås (som kan dyrkas upp med
 dyrkar), som du kanske kan bända upp.}
{415}{}{Du ser en robust dörr med ett lås på, som du kanske kan
 bända upp.}
{416}{}{Du ser en robust dörr utan synbar låsanordning,
 som du kanske kan bända upp.}
{417}{}{Du ser en robust dörr som du kanske kan bända upp.}
{500}{}{Den här dörren är för tung för att bända upp.}
{501}{}{Det verkar som om du måste få igång generatorn först.}
{502}{}{Du ser: Hissdörr.}
{503}{}{Det verkar som om du behöver ett elektrisk verktyg för att öppna det här låset.}
{601}{}{It is open, dummy.}
{610}{}{You fail spectacularly, and the explosive goes off prematurely.}
{611}{}{ fails spectacularly, and the explosive goes off prematurely.}
{620}{}{You bend the crowbar beyond recognition. It's useless now.}
{621}{}{ bends the crowbar beyond recognition. It's useless now.}
