{100}{}{You see a traveler.}
{101}{}{This person seems to be looking for something.}
{200}{}{It's a slaver! Kill him!}
{201}{}{Kill the oppressor!}
{202}{}{Kill the evil slaver!}
{203}{}{Down with slavery! Kill the slavers!}
{204}{}{Dö, slavdrivande avskum!}
{250}{}{Hello there!}
{251}{}{Hey stranger!}
{300}{}{Hey stranger, what are you doing out in these parts?}
{301}{}{I'm lost.}
{302}{}{Just wandering around.}
{303}{}{Not much. What are you doing out here?}
{304}{}{Looking for people to kill.}
{305}{}{Nothing. Bye.}
{306}{}{huh?}
{307}{}{Um, I think I need to be going now. Bye.}
{310}{}{I wish I could help you, but I've been wandering these parts
 for so long, I'm not certain where anything is any more.}
{311}{}{Why are you wandering around here?}
{312}{}{What are you doing out here?}
{313}{}{Nåväl, lycka till.}
{314}{}{Ja, lycka till. Åh, förresten, se upp för
 Lyan. De gillar att sälja folk där.}
{315}{}{Lyan?}
{316}{}{Sälja människor?}
{317}{}{Visst. Hej då.}
{320}{}{Folk här gillar visst att ha slavar. Jag är här för att
 försöka befria slavarna. Och om en slavhandlare eller två dör under processen, är det ingen stor grej.}
{321}{}{Vad är det för fel med att äga slavar? Jag skulle äga några om jag kunde hitta dem.}
{322}{}{Jag ska hålla ögonen öppna efter de jävlarna.}
{323}{}{Killing is never justified.}
{324}{}{Kill? I'll help you kill them.}
{330}{}{Really? That's great. Well, I have to head out and look for more
 slaves to free.}
{331}{}{Lycka till.}
{335}{}{No, sometimes you need to kill a few people to save many. Sacrifices
 of the land. Besides, they're slavers; it's not like they are real people.}
{336}{}{Yeah, you're right. Well, I've gotta go.}
{337}{}{Really? Well, to me you're dead meat.}
{338}{}{Whatever. Bye.}
{340}{}{You bastard! I'll kill you for that!}
{341}{}{You bitch! I'll kill you for that!}
{342}{}{Not if I kill you first!}
{350}{}{Yeah. They attack small groups of people. Any that live go to the
 auction blocks.}
{351}{}{That's horrible. I'll remember to watch out for them. Thanks.}
{355}{}{The Den's a town. They specialize in slavery and all sorts of
 evil. They're no good at all.}
{356}{}{Thanks for the information. Bye.}
{360}{}{Just looking to shut down the slave routes.}
{361}{}{Vad menar du?}
{362}{}{Oh, ok. Good luck to you.}
{363}{}{Whatever. Bye.}
{370}{}{Try slavers. They make really good kills. Nice and messy.}
{371}{}{Cool. Thanks for the info.}
{372}{}{You're here. I'd rather kill you.}
