{100}{}{Du ser en liten pojke.}
{101}{}{Du ser en liten flicka.}
{200}{}{Är vi framme snart?}
{201}{}{Jag är trött.}
{202}{}{Kan du bära mig?}
{203}{}{Jag får inte prata med främlingar.}
{204}{}{Mamma och pappa gick ut hit.}
{205}{}{Vill 'u se min glänsiga sten?}
{206}{}{Vill du leka med mig?}
{207}{}{La la la la la la. Jag lyssnar inte.}
{208}{}{Varför får jag inte leka nu?}
{209}{}{Vill du leka?}
