{100}{}{Du ser en vakt.}
{101}{}{Du ser en av vakterna som hjälper dig med karavanrundan.}
{200}{}{Du ser en karavanförare.}
{201}{}{Du ser en av förarna som hjälper dig med den här karavanrundan.}
{300}{}{Jag hoppas att vi inte råkar ut för alltför många fler möten längs vägen.}
{301}{}{Det ska bli skönt att få den där lönechecken i slutet av rundan.}
{302}{}{Jag hoppas att de har baren öppen när jag kommer dit.}
{303}{}{Det ska bli skönt att få lite riktig mat för en gångs skull.}
{304}{}{Jag har alltid velat resa. Jag antar att det här är det närmaste jag kommer det.}
{305}{}{Mina fötter tar kol på mig. Jag önskar att de där dumma brahminerna kunde skynda sig.}
{306}{}{Jag har hört att vi inte har så långt kvar på den här resan.}
