{100}{}{För Enigheten!}
{101}{}{Håll dem borta, mina herrar!}
{102}{}{Döda inkräktarna!}
{103}{}{Skydda staden!}
{104}{}{Go! Go! Go!}
{105}{}{Se upp! Plundrare!}
{106}{}{Nu sticker vi härifrån!}
{107}{}{Oh man... just when I thought we were safe! No more! No more!}
{108}{}{Spring!}
{109}{}{Behandla vårt folk med respekt.}
{110}{}{Bryt inte mot lagen.}
{111}{}{Om du tänker ställa till med problem, kom ihåg oss. Bete er bra så kommer Marcus att bete sig bra.}
{112}{}{Vi är fredliga i Broken Hills, men vi vet hur man slåss.}
