{100}{}{Måste varna Lynette!}
{101}{}{Måste varna Valvstaden!}
{102}{}{Utbölingsavskum...}
{103}{}{Degenerate filth...}
{104}{}{Dags att rensa ut mer utbölingsskräp... Dö, utbölingar!}
{105}{}{Vad gör du runt Valvstaden?}
{106}{}{What is your business near Vault City?}
{107}{}{Det här är en del av Valvstadens territorium.}
{108}{}{Se dig för.}
{109}{}{Valvstaden är inte en fristad för *alla.* Så gå vidare.}
{110}{}{Din sort hör hemma i Lyan.}
{111}{}{I suggest you go there now.}
{112}{}{Hello, citizen.}
{113}{}{Anything we can do for you, citizen?}
{114}{}{Do you need an escort to Vault City?}
{115}{}{What are you doing so far from Vault City, citizen?}
{116}{}{We were worried you might have been hurt, citizen.}
