{100}{}{Du ser en boxare.}
{150}{}{Du ser en kraftigt muskulös svart man. Han ser ut som om han precis har avslutat ett träningspass.}
{151}{}{Du ser en enorm svart man. Och jag menar verkligen ENORM.}
{152}{}{Han ser ut som om han precis har avslutat ett träningspass.}
{153}{}{Du trodde nästan att han var ett litet berg.}
{154}{}{Han är enorm. Enooooorm.}
{155}{}{Han flinar tandlöst mot dig.}
{156}{}{Han ser ut som om han precis har avslutat ett träningspass.}
{157}{}{Du trodde nästan att han var ett litet berg.}
{158}{}{Han är enorm. Enooooorm.}
{159}{}{Han flinar tandlöst mot dig.}
{160}{}{Han jabbar mot en osynlig motståndare och morrar hot ut i luften.}
{161}{}{Han ser tillfälligt förvirrad ut, som om han glömt vem han var, men ler
 sedan och kliar sig i huvudet.}
{162}{}{Han gör knäböj.}
{163}{}{Du ser en stor vit man. Hans armar ser ut som trädstammar.}
{164}{}{Du ser en kraftigt muskulös vit man. Han spänner sig och grymtar för sig själv.}
{165}{}{Du ser en kraftigt muskulös vit man. Han tittar på ditt huvud som på en boxningssäck.}
{166}{}{Han jabbar mot en osynlig motståndare och morrar hot ut i luften.}
{167}{}{Han ser tillfälligt förvirrad ut, som om han glömt vem han var, men ler
 sedan och kliar sig i huvudet.}
{168}{}{Han tittar på ditt huvud som på en boxningssäck.}
{200}{}{Hnffff}
{201}{}{Hnrggg}
{202}{}{::Spänner::}
{203}{}{::Boxaren tittar på dig med skrämda ögon::}
{204}{}{Jaherrn?}
{205}{}{Kam ja låna nåra tänner?}
{206}{}{You need spotter?}
{207}{}{Aha.}
{208}{}{::Nickar dumt åt allt du säger::}
{209}{}{Du stor peshon. Jag liten.}
{210}{}{Du tuff. Jag svag.}
{211}{}{Me hungry.}
{212}{}{Jag inte gilla prata.}
{213}{}{Du luktar gooott.}
{214}{}{Du luktar som Mamma.}
{215}{}{Nog prat. Dags att lägga sig.}
{216}{}{::Ler tandlöst::}
{217}{}{::Kliar sig själv::}
{218}{}{::Spänner::}
{219}{}{Grymt}
{220}{}{Du slåss mot mig?}
{221}{}{Bli arg bli arg bli arg.}
{222}{}{Fo-kuss, Fo-kuss.}
{223}{}{Get critikal.}
{224}{}{Fight past that shit.}
{225}{}{Me need spotter.}
{226}{}{You small person.}
{227}{}{Jag inte gilla prata.}
{300}{}{Ernhhh}
{301}{}{Unfff}
{302}{}{Hrghhh}
{303}{}{Nfff}
{304}{}{Hrggg}
{305}{}{Ooof}
{310}{}{Too slow!}
{311}{}{Not the face!}
{312}{}{You punch like my grandmother!}
{313}{}{No hitting below the belt!}
{314}{}{You ain't bad.}
{315}{}{Dat all you got?}
{320}{}{And stay down!}
{321}{}{You got knocked da fuck out!}
{322}{}{Who's your Daddy?}
{323}{}{If he dies, he dies.}
{330}{}{Coulda been a contender!}
{331}{}{How could such a... geggghhh...}
{332}{}{*Huuuuurrrrllllll*}
{333}{}{Ooo, care bears...}
{334}{}{I think I'll just lay here for a little while.}
{335}{}{No pain, no pain, no pain...}
{340}{}{Eat this!}
{341}{}{You want some of this?!}
{342}{}{Subba!}
{343}{}{Now you're mine.}
{344}{}{I eat green berets for breakfast.}
{345}{}{Haadookin.}
{346}{}{Now you DIE.}
{347}{}{SUPER... NUCLEAR... TORNADO... FIST...}
{350}{}{Adrian! Adrian!}
{351}{}{You're going down!}
{352}{}{Make you a bitch...}
{353}{}{I must break you.}
{354}{}{You're fighting like a bum!}
{355}{}{You got no guts!}
{356}{}{You're a bum! A bum!}
{357}{}{Gonna beat you like a dog...}
{360}{}{Ain't gonna be no rematch!}
{361}{}{Hit like a butterfly...}
{362}{}{Keep your hands up...}
{363}{}{Stay sharp!}
{364}{}{Fight past that shit!}
{365}{}{Get critical!}
{366}{}{Cut me, Mick.}
{367}{}{Remember, stick the jab!}
{368}{}{I see three of 'em!}
