{100}{}{You see a big thug.}
{101}{}{You see Rico.}
{150}{}{You see a huge, stone-faced man. He looks like he eats bricks.}
{151}{}{You see Rico, Monte's bodyguard. He looks like he eats bricks.}
{175}{}{Hurggg}
{176}{}{Hnrfff}
{177}{}{Snffff}
{178}{}{Urb-luu}
{179}{}{Klurgggg}
{180}{}{Oog}
{200}{}{Me Monte friend. YOU Monte friend?}
{201}{}{Me hit people Monte tell me to.}
{202}{}{Me hit people.}
{203}{}{Me hit people with fists like playing drum.}
{204}{}{Me like to hit.}
{205}{}{::Ler tandlöst::}
{206}{}{::Kliar sig själv::}
{207}{}{::Spänner::}
{208}{}{Grunt.}
{209}{}{Grunt - Grunt.}
{210}{}{Jag inte gilla prata.}
{211}{}{Yoo smell guuud...}
{212}{}{Yoo smell like mom.}
{213}{}{Yoo cute. Me no hit you.}
{214}{}{Yoo make me blush...}
{215}{}{Uhhh... Me Rico...}
