{100}{}{Du ser en ockupant.}
{101}{}{You see Bill, the squatter}
{102}{}{You see a middle age man wearing worn clothing.}
{103}{}{Sorry stranger. I don't have time to chat with you.}
{104}{}{Varför prata inte?}
{105}{}{Ok, wavy.}
{106}{}{Okej, vi ses.}
{107}{}{Vänta lite nu. Varför vill du inte prata med mig?}
{108}{}{We're a very private community here and we don't want any trouble or interference from outside sources. Please just leave us be.}
{109}{}{Ok.}
{110}{}{Hej... och hej då.}
{111}{}{Thank you for all that you've done. I apologize for the cold shoulder.}
{112}{}{Screw you asshole!}
