{100}{}{Du ser en välklädd snubbe som säljer ödlekebab.}
{101}{}{Det är ödla-på-pinne-försäljaren.}
{102}{}{För att vara en ödla-på-pinne-försäljare har den här snubben stil. Han är ren, välklädd och driver en ganska fläckfri liten verksamhet.}
{103}{}{Hungrig, främling? Jag har den bästa ödlan här. Fråga vem som helst!}
{104}{}{What can I get you?}
{105}{}{Ge me' kött.}
{106}{}{Jag tar en.}
{107}{}{What can you tell me about this town?}
{108}{}{Farväl.}
{109}{}{Varsågod, främling!}
{110}{}{Det finns senap och lök där borta.}
{111}{}{Hej, kompis.}
{112}{}{Ja, hej då.}
{113}{}{Nästa!}
{114}{}{Jag har en regel. Jag säger inget om nån. Det är en bra regel, för om jag håller truten, så håller jag mig borta från problem. Capiche?}
{115}{}{Jag hör ingenting, jag ser ingenting och jag säger framför allt ingenting. Sluta nu att besvära mig med det där.}
{116}{}{Okej. Jag är hungrig.}
{117}{}{Do you have a GECK?}
{118}{}{Förlåt att jag besvärar dig, Herregud!}
{119}{}{A GECK? Well, that's old history, so what the hell. You mean the old Garden of Eden Kit. We had one - I mean our grandparents had one. Used it when they came out of Vault 15. Got this place started, they say. It's all used up now.}
{120}{}{Jag är fortfarande hungrig.}
{121}{}{Tack för inte så mycket.}
