{100}{}{You see a villager.}
{101}{}{You see a villager.}
{102}{}{Hej.}
{103}{}{Good day.}
{104}{}{Welcome to our village.}
{105}{}{The monsters protect us.}
{106}{}{Hurry back.}
{107}{}{We'll need those guns soon.}
{108}{}{Hej.}
{109}{}{Leave now!}
{110}{}{Go back to where you came from!}
{111}{}{Get the hell out of here!}
{112}{}{We're safe now.}
{113}{}{Tack.}
{114}{}{Bless you, wanderer.}
