{100}{}{Du ser en luggsliten bonde.}
{101}{}{Du ser Smith.}
{102}{}{Jag tror inte jag har sett dig här förut, främling. Namnet är Smith. Kan jag hjälpa
 dig med något?}
{103}{}{Var det något annat du ville?}
{104}{}{Can you tell me about Vault City?}
{105}{}{What do you do around here?}
{106}{}{I'm looking for the Vault.}
{107}{}{Jag skulle vilja hjälpa dig med den där plogen.}
{108}{}{Din fru säger att ni har haft det svårt.}
{109}{}{Nej, jag är bara på genomresa. Hej då.}
{110}{}{Um... Waga Nu-kik?}
{111}{}{Tja, det du ser här är inte riktigt Valvstaden... du står faktiskt
 på stadens Innergård.}
{112}{}{Varför är du inte i stan?}
{113}{}{What do you do here?}
{114}{}{Can I ask you something else?}
{115}{}{Tack. Hej då.}
{116}{}{Min familj och jag arbetar på en gård här på Innergården. Vi klarar oss. Vet inte
 för hur länge, dock.}
{117}{}{What's the problem?}
{118}{}{Varför är du inte i stan?}
{119}{}{Can I ask you something else?}
{120}{}{Ja, det är tuffa tider. Hej då.}
{121}{}{Det stämmer, storponken. Jag måste gå nu.}
{122}{}{Pratar du om Valvet inne i staden? Jag har bara sett det en gång... det är
 innanför grindarna, längs klippan, tror jag. De släpper bara in Medborgare i det,
 däremot.}
{123}{}{Can I ask you something else?}
{124}{}{Thanks for the directions. Goodbye.}
{125}{}{Ja' och familjen är inte den sortens människor som de släpper in där. Så vi
 bor här under deras beskydd.}
{126}{}{Varför får ni inte bo i stan?}
{127}{}{Skydd? Vilken typ av skydd? }
{128}{}{Can I ask you something else?}
{129}{}{Jag förstår. Tack för att du tog dig tid. Adjö.}
{130}{}{Tja, det är svårt utan en plog. Jag och frun försöker, men jordbruket går
 långsamt.}
{131}{}{Kan jag hjälpa till?}
{132}{}{Can I ask you something else?}
{133}{}{Nåja, det var tråkigt att höra. Adjö.}
{134}{}{Visst.}
{135}{}{Tja, vi är från ödemarken... precis som du. Så allt vi kan få är
 skydd från Valvstaden.}
{136}{}{Vilken typ av skydd?}
{137}{}{Can I ask you something else?}
{138}{}{Tack. Hej då.}
{139}{}{They keep us safe from the outside, but it costs me and the wife quite
 a bit. And without a plow... well, making ends meet is difficult.}
{140}{}{Can I help with the plow?}
{141}{}{Can I ask you something else?}
{142}{}{Nåja, det var tråkigt att höra. Adjö.}
{143}{}{Me and the wife don't talk with your kind.}
{144}{}{Mary, keep away from this fella.}
{145}{}{You'd help people like us? We can't offer much, but we sure would
 appreciate it.}
{146}{}{Whoa! If you can't pay, I can't help you.}
{147}{}{No problem. I'd like to help.}
{148}{}{Can I ask you something else?}
{149}{}{I'll have to think about it. Goodbye.}
{150}{}{Well, we have about a hundred and fifty saved, if that would help. But
 we won't be able to make our next payment if we don't have the plow by next week.}
{151}{}{I'll take the money.}
{152}{}{Don't worry about the money. I'll help you anyway.}
{153}{}{Never mind... I can't help you. Goodbye.}
{154}{}{Well, thank you kindly, stranger.}
{155}{}{Do you know where I can find a plow?}
{156}{}{There's one over near the Guns and Ammo store. Harry might be selling it.}
{157}{}{All right, I'll go look for it.}
{158}{}{Did you find a plow?}
{159}{}{Sorry, not yet.}
{160}{}{I don't think I'm going to be able to get one for you.}
{161}{}{Well, we can do without for a little longer. But not much beyond that.}
{162}{}{My Pa told me to watch out for people like you... get outta here. Go on, get!}
{163}{}{Thank you kindly. Here's a little something my pa gave me before he
 left this world. With the guards protecting us, we don't need it... but you might be
 able to make some use of it.}
{164}{}{Thanks very much. I'm sure this will come in handy. Take care.}
{165}{}{Thanks for the help, stranger. Much appreciated.}
{166}{}{You have found a plow for Mr. Smith and his family.}
