{100}{}{Du ser en stark man i arbetskläder. Han håller blicken stadigt fäst på marken.}
{101}{}{Du ser en slav från Valvstaden.}
{102}{}{Du ser en stark man i arbetskläder. Han håller blicken stadigt fäst på marken.}
{103}{}{Du ser en kvinna i arbetskläder som ser frisk ut. Hon håller blicken stadigt fäst på
 marken.}
{104}{}{Du ser en slav från Valvstaden.}
{105}{}{Du ser en kvinna i arbetskläder som ser frisk ut. Hon håller blicken stadigt fäst på
 marken.}
{106}{}{I have heard of your brave deeds. You have done a great service for Vault City... and the world.}
{107}{}{Your battle against the Enclave impressed even the First Citizen.}
{108}{}{Jag önskar att jag på något sätt kunde ge dig något för allt du har gjort för oss, men jag har inget att
 ge... förutom mitt tack.}
{109}{}{De andra tjänarna kommer att vara avundsjuka på att jag pratade med hjälten från Ödemarken.}
{110}{}{Yes, Captain?}
{111}{}{Kapten?}
{112}{}{Är det något du vill att jag ska göra, Kapten?}
{113}{}{Har du en uppgift åt mig, Kapten?}
{114}{}{I'm sorry, Captain. I will try and work harder.}
{115}{}{I'm sorry, Captain. I will try to be more attentive.}
{116}{}{Yes, Citizen?}
{117}{}{Citizen?}
{118}{}{Is there something you wanted me to do, Citizen?}
{119}{}{Did you have a task for me, Citizen?}
{120}{}{I'm sorry, Citizen. I will try and work harder.}
{121}{}{I'm sorry, Citizen. I will try to be more attentive.}
{122}{}{Mutants are not allowed inside the city!}
{123}{}{Om vakterna ser din mutant kommer du att tvingas gå.}
{124}{}{Mutanter är inte tillåtna inne i staden! Ni måste ge er av!}
{125}{}{Ghuler är inte tillåtna inne i staden!}
{126}{}{Om vakterna ser din ghul, kommer du att tvingas lämna.}
{127}{}{Ghuler är inte tillåtna inne i staden! Ni måste lämna staden!}
{128}{}{Yes, I am already owned. The Servant Allocation Center has my papers.}
{129}{}{Please leave me be. I am a Servant of Vault City.}
{130}{}{Jag ber dig: har du sett två barn, mörkhåriga...? De togs av andra slavhandlare för två år
 sedan och såldes norrut.}
{131}{}{Snälla... Jag får inte tala med någon.}
{132}{}{Om en Medborgare ertappar mig med att prata med en slavhandlare, kommer jag att straffas.}
{133}{}{Vakterna kommer att rapportera mig om du fortsätter att prata med mig.}
{134}{}{I cannot speak to you. I have duties.}
{135}{}{Please go away, slaver. I don't want any trouble.}
{136}{}{Fly? Jag... har aldrig försökt fly härifrån. Livet är bra här.}
{137}{}{Medborgarna sa till mig att om jag arbetar tillräckligt hårt kan *jag* en dag bli en Medborgare.}
{138}{}{Medborgarna lär oss att arbete är sin egen belöning.}
{139}{}{Medborgarna berättar att eftersom vi tjänar dem får de mer tid för viktigare saker.}
{140}{}{Jag hade tur att Valvstaden behövde tjänare. Jag kunde ha hamnat i New Reno.}
{141}{}{Valvstaden belönar tjänare som arbetar flitigt med extra ransoner.}
{142}{}{Jag har hört att de gör hemska saker mot slavarna i New Reno.}
{143}{}{Medborgarna tog med sig hela min stam in i staden för att tjäna som tjänare.}
{144}{}{Medborgarna tog mig in från ödemarken och lärde mig att läsa.}
{145}{}{Medborgarna behandlar mig mycket bra. Maten här är utmärkt.}
{146}{}{Jag får inte tala med Utomstående.}
{147}{}{Jag saknade min familj först, men det var många år sedan jag såg dem.}
{148}{}{Jag togs från en stamby norrifrån. Livet är mycket bättre här.}
{149}{}{Jag fångades först i Lyan. Lyckligtvis hamnade jag här.}
{150}{}{I hear the First Citizen occasionally loses her temper with her servants.}
{151}{}{I cannot speak to you. I have work to do.}
{152}{}{I must finish my duties within the hour.}
{153}{}{Speaking to Outsiders is against the rules.}
{154}{}{Escape? Why?}
{155}{}{Yes? Can I help you?}
{156}{}{I was captured by slavers long ago. I barely remember it.}
{157}{}{I used to have two children, but they were shipped northwards. I hope they make their way here
 someday.}
{158}{}{I'm sorry, but I don't have time to talk.}
