{100}{}{Du siehst die Brückenwache.}
{101}{}{Du siehst Mynoc, den Brückenwächter.}
{150}{}{Vor dir steht ein großer Krieger deines Dorfes mit einem Speer.}
{151}{}{[GESPRÄCH]}
{152}{}{Hallo, Auserwähltes Wesen. Machst du dich auf die Suche nach dem GECK?}
{153}{}{Ja.}
{154}{}{Ja. Aber bevor ich geh, würde ich dir gerne ein paar Fragen stellen.}
{155}{}{Jetzt noch nicht. Ich werde mich noch etwas umsehen.}
{156}{}{Mögen die Götter über dich wachen.}
{157}{}{Danke, Wiedersehn.}
{158}{}{Was willst du wissen?}
{159}{}{Was kannst du mir über die Männer erzählen, die mit unserem Dorf handeln?}
{160}{}{Was kannst du mir über dieses Ding sagen? Ich hab's aus einer Vault?}
{161}{}{Nichts, gar nichts.}
{162}{}{Na gut, aber verschwende nicht zu viel Zeit. Ohne das GECK sind wir verloren.}
{163}{}{Ich weiß, mach dir keine Sorgen. Ich hab alles unter Kontrolle.}
{164}{}{Warum?}
{165}{}{Ich muss los. Wiedersehen.}
{166}{}{Die Händler? Sie kommen so alle zwei Monate aus Klamath. Es dauert noch gut einen Monat, bis wieder jemand kommt, aber Klamath liegt nur ein paar Tage östlich von hier.}
{167}{}{Vielen Dank. Auf Wiedersehen.}
{168}{}{Was kannst du mir zu diesem Ding sagen, das ich aus der heiligen Vault habe?}
{169}{}{Sieht wie eine Wasserflasche aus Metall aus. Vielleicht hat es uns die Vault als Omen geschickt.}
{170}{}{Weißt du, wer das in unser Dorf gebracht hat?}
{171}{}{Danke. Ich muss jetzt gehn, Tschüss.}
{172}{}{Ich hoffe, das tust du.}
{173}{}{Dein übersteigertes Selbstvertrauen macht uns alle krank! Tschüss.}
{174}{}{Wiedersehn.}
{175}{}{Warum? Sieh dich doch um, unser Dorf stirbt. Unsere Gärten verdorren und jeden Tag brechen Kinder und alte Menschen zusammen. Du musst uns Eden bringen, bevor es zu spät ist.}
{176}{}{Ich werd mich drum kümmern. Wiedersehn.}
{177}{}{Ich bin das Auserwählte Wesen - ich "muss" nur wenn ich will. Tschüss.}
{178}{}{Ich kann mich nicht an seinen Namen erinnern. Ich weiß nur, dass er alt und laut war - zu laut für gute Manieren. Aber er wusste viel. Er kam aus Klamath, im Osten, wie ich bereits sagte.}
{179}{}{Danke, Wiedersehn.}
{180}{}{Bist du immer noch hier? Du musst gehen und das GECK finden. Dumm herumstehen hilft uns nicht weiter.}
{181}{}{Das einzige worüber du dir Gedanken machen musst Freund, ist die Brücke. Ich kann auf mich selbst aufpassen.}
{182}{}{Ich wollte gerade gehn. Tschüss, mein Freund.}
{183}{}{Mit dir sprech ich nicht mehr, aufsässiges Schwein!}
{184}{}{Ich hätt noch eine Frage.}
{185}{}{Das ging aber schnell. Hast du die heilige Vault 13 gefunden?}
{186}{}{Ja.}
{187}{}{Nein, noch nicht.}
{188}{}{Du hast? Wunderbar! Hast du das GECK zurückgebracht?}
{189}{}{Nein.}
{190}{}{Nein. Ich hab noch nicht mit den Leuten aus der Vault gesprochen.}
{191}{}{Ich glaub, das geht dich nichts an, mein Freund.}
{192}{}{Nein? Auserwähltes Wesen, seit du gegangen bist sind drei alte Menschen gestorben. Du darfst nicht noch mehr Zeit verschwenden.}
{193}{}{Ich werd's schon finden, keine Sorge.}
{194}{}{Dein ständiges Meckern geht mir auf die Nerven.}
{195}{}{Also, warum redest du dann mit mir? Red mit ihnen und hol das GECK.}
{196}{}{Das werde ich - alles zu seiner Zeit, mein Freund.}
{197}{}{Dein ständiges Meckern geht mir auf die Nerven.}
{198}{}{Was gibt es Neues über das GECK, Auserwähltes Wesen?}
{199}{}{Ich hab die Vault gefunden!}
{200}{}{Ich konnte Vault 13 nicht finden.}
{201}{}{Schau mal, er ist das Auserwählte Wesen.}
{202}{}{Hallo.}
{203}{}{Halt's Maul.}
{204}{}{Darf ich dich was fragen?}
{205}{}{Nein, ich hab keine Zeit für dich.}
{206}{}{Was auch immer. Tschüss.}
{207}{}{Na gut. Man sieht sich.}
{208}{}{Geh und stirb.}
{209}{}{Sei gegrüßt, dümmliches Wesen. Du sehen Brücke? Du überqueren, aber seien vorsichtig. Brücke gefährlich. Du nicht fallen. OK?}
{210}{}{Hmm... Häh?}
{211}{}{Blödmann! Du hast das Dorf im Stich gelassen!}
{212}{}{Du verrätst uns. Dafür wirst du sterben!}
{213}{}{Du bist ein Verräter am eigenen Volk.}
{214}{}{Warum tust du das?}
{215}{}{Die Älteste hatte Unrecht. Du bist schlecht.}
{300}{}{Mein Vater hat mir beigebracht, wie man besonders stabile Klingen macht. Hol mir ein Stück Feuerstein, dann optimier ich auch deinen Speer. In der Wildnis wirst du ihn brauchen.}
{301}{}{Wo finde ich Feuerstein?}
{302}{}{Man sagt, deine Tante Morlis hat einen Vorrat. Sie ist so schlecht gelaunt, dass sie bestimmt noch niemand gefragt hat. Aber die Hexe will bestimmt etwas dafür haben.}
{303}{}{Vielen Dank. Auf Wiedersehn.}
{304}{}{Hast du Feuerstein von deiner Tante bekommen?}
{305}{}{Ja, hier hab ich was.}
{306}{}{Noch nicht.}
{307}{}{Das ist ein schönes Stück. Gib mir deinen Speer.}
{308}{}{Bitte.}
{309}{}{Ich glaub, ich hab keinen.}
{310}{}{Jetzt machst du das mit den Stücken so...}
{311}{}{Das Auserwählte Wesen ohne Speer? Dann musst du einen von meinen nehmen. Und jetzt lass uns an die Arbeit gehen...}
{312}{}{Hier ist dein neuer Speer.}
{313}{}{Danke mein Freund - das ist mir eine große Hilfe.}
{314}{}{Ja, aber ich hab mich über deinen Speer gewundert. Er sieht etwas anders aus.}
{400}{}{Willkommen zu Hause, Auserwähltes Wesen! Hast du die Vault gefunden? Hast du das GECK mitgebracht?}
{401}{}{Noch nix finden.}
{402}{}{Nein, ich hab es noch nicht gefunden.}
{403}{}{Ich bin jetzt nicht in der Stimmung für Fragen. Tschüss.}
{404}{}{Es läuft nicht besonders gut, Auserwähltes Wesen. Die Dürre wird immer schlimmer und unsere Ernte wird mit Sicherheit ausfallen. Wir versuchen zu retten, was zu retten ist, um unsere Nahrungsvorräte anzulegen.}
{405}{}{Warum nicht Handel mit anderen Dörfern?}
{406}{}{Ich mein bestes tun. Ich werden GECK finden. Kommen zurück.}
{407}{}{Warum können wir nicht mit anderen Dörfern handeln, um Nahrungsmittel zu bekommen?}
{408}{}{Ich tue mein bestes. Wenn ich das GECK gefunden habe, komme ich zurück.}
{409}{}{Wir sind ein kleines Volk und können nicht viel zum Handeln anbieten. Die wenigen Städte, mit denen wir während deiner Abwesenheit Kontakt aufgenommen haben, haben kein Interesse daran, uns zu helfen.}
{410}{}{Ich verstehn.}
{411}{}{Verstehe.}
{412}{}{Du bist unsere letzte Hoffnung, Auserwähltes Wesen. Lass uns nicht im Stich.}
{413}{}{Gut dich zu sehen, Auserwähltes Wesen. Was macht deine Suche?}
{414}{}{Ich noch suchen.}
{415}{}{Ich suche noch.}
{416}{}{Ich will nicht darüber reden.}
{417}{}{Du musst dich beeilen. Die Lage hier in der Heimat wird immer schlimmer. Bald wird kaum noch was zu essen da sein. Die Älteste spricht bereits davon das Vorhandene zu rationieren. Ich fürchte um die Zukunft von Arroyo.}
{418}{}{Auserwähltes Wesen! Bitte sag, dass du deinen Auftrag ausgeführt hast. Unser Dorf und unser Volk sterben.}
{419}{}{Nein, ich noch suchen.}
{420}{}{Nein, ich suche noch immer.}
{421}{}{Wie läuft es?}
{422}{}{Tut mir leid, Auserwähltes Wesen, aber allmählich hab ich kein Vertrauen mehr. Das Leben unseres Volkes liegt in deinen Händen. Bitte finde die Heilige Dreizehn und komm mit dem GECK zurück! }
{423}{}{Unsere Ernte bleibt aus, die Brahmin sterben, alle leiden Hunger. Die Schreie der Kinder in der Nacht halten uns wach. Unser Volk ist am verzweifeln.}
{424}{}{Ich weiter suchen.}
{425}{}{Ich tu, was ich kann.}
{426}{}{Wiedereinmal kehrst du zurück, Auserwähltes Wesen. Doch nicht mit leeren Händen, hoffe ich?}
{427}{}{Tut leid, ich GECK noch nicht finden.}
{428}{}{Tut mir leid, ich habe das GECK noch nicht gefunden.}
{429}{}{Mir reicht's.}
{430}{}{Die Leute sterben hier, während du durch die Lande ziehst. Du solltest vielleicht woanders suchen, anstatt zurückzukommen.}
{500}{}{Hast du schon mit der Ältesten gesprochen?}
{1000}{}{Älteste}
{1001}{}{Gründer}
{1002}{}{Vaultbewohner}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Auserwähltes Wesen}
{1007}{}{Schamane}
{1008}{}{Hakunin}
{1009}{}{Heilpulver}
{1010}{}{Brücke}
{1011}{}{Mynoc}
{1100}{}{Die Älteste ist unsere Mutter und unsere Führerin.}
{1101}{}{Unsere große Ahne, der wir unser Wissen zu verdanken haben.}
{1102}{}{Die erste, der gegen das Chaos gekämpft und gesiegt hat.}
{1103}{}{Das wäre unser schönes Dorf.}
{1104}{}{Das ist ein äußerer Handelsposten, einige Tage östlich von hier.}
{1105}{}{Die Vault ist der Himmel.}
{1106}{}{Du bist das Auserwählte Wesen.}
{1107}{}{Er heilt uns mit seinen Kräutern und seiner Magie. Er lebt im nördlichen Teil des Dorfes.}
{1108}{}{Er heilt uns mit seinen Kräutern und seiner Magie. Er lebt im nördlichen Teil des Dorfes.}
{1109}{}{Es ist ein magisches Pulver, das dich heilen wird, aber es macht auch schläfrig.}
{1110}{}{Die große Brücke führt im Süden aus dem Dorf hinaus.}
{1111}{}{Das bin ich.}
