{100}{}{Du siehst einen kleinen Mann mit einem Buch in den Händen.}
{101}{}{Du siehst Doc Jones, den Arzt.}
{102}{}{Du siehst einen kleinen Mann mit dem Buch "Also, du willst Arzt werden?".}
{103}{}{Hallo, ich bin Doc Jones. Du kannst mich auch Doc nennen. Was kann ich für dich tun?}
{104}{}{Hab Aua. Du helfen?}
{105}{}{Fühl schlecht. Du helfen?}
{106}{}{Ich lahm, du helfen?}
{107}{}{Hab Fragen. OK?}
{108}{}{Tut leid. Ich gehn.}
{109}{}{Ich bin verletzt, kannst du mir helfen?}
{110}{}{Ich fühl mich elend, kannst du mir helfen?}
{111}{}{Ich bin verstümmelt, kannst du mir helfen?}
{112}{}{Ich möchte dich was fragen.}
{113}{}{Ich wollte nur mal Hallo sagen.}
{114}{}{Ja, sicher. Hier, wir geben dir eine Dosis hiervon — das piekst ein bisschen — jetzt eine Bandage, und schon bist du wieder OK.}
{115}{}{Danke. Wieder-sehn.}
{116}{}{Danke Doc. Ich fühl mich schon viel besser.}
{117}{}{Ja, sicher. Hier, trink das — alles, ich weiß, dass es furchtbar schmeckt. Jetzt leg dich da drüben aufs Bett. Ich weck dich morgen früh.}
{118}{}{Ich fühlen gut. Tschüss.}
{119}{}{Danke, Doc. Das hat geholfen.}
{120}{}{Tut mir leid, aber ich hab nicht die richtigen Utensilien, um eine Operation durchzuführen. Du solltest in eine der größeren Städte gehn und einen Chirurgen aufsuchen. Versuch es in Vault City. Das ist nördlich von hier.}
{121}{}{OK. Tschüss.}
{122}{}{Na gut. Danke trotzdem.}
{123}{}{Was möchtest du denn wissen?}
{124}{}{Du Arbeit Darion?}
{125}{}{Du gehn hier wenn wollen?}
{126}{}{Was du wissen über Darion?}
{127}{}{Wie du kommen her?}
{128}{}{Du sagen, Darion hat Hund?}
{129}{}{Ich gehn.}
{130}{}{Arbeitest du für Darion?}
{131}{}{Kannst du gehn, wenn du willst?}
{132}{}{Was kannst du mir über Darion sagen?}
{133}{}{Wie bist du hier her gekommen?}
{134}{}{Du sagtest, Darion hat einen Hund?}
{135}{}{Danke für die Informationen; ich geh jetzt los.}
{136}{}{Äh, ja und nein. Ich bin nicht ganz freiwillig hier. Ich bin ein Gefangener. Darion wird älter und braucht einen engagierten Arzt, der sich um ihn kümmert. Die Khans behalten mich seinetwegen hier. Ich würde lieber den Leuten oben in der Stadt helfen. Sie haben überhaupt keine medizinische Hilfe und dort gibt es viel zu tun.}
{137}{}{OK. Muss mehr wissen.}
{138}{}{Danke. Tschüss.}
{139}{}{Das ist sehr lobenswert von dir.}
{140}{}{Verstehe. Ich werd jetzt gehn.}
{141}{}{Das sind bloß illegale Siedler! Lass sie sterben und leb dein eigenes Leben.}
{142}{}{Nein, ich sitz hier ziemlich in der Falle. Ich komme noch nicht mal weg, um meine medizinischen Vorräte aufzustocken. Darion schickt Leute, um alles zu besorgen, was ich brauche.}
{143}{}{Ich verstehn. Jetzt gehn.}
{144}{}{Ich noch Fragen.}
{145}{}{Ich schätze, du bist keine vertrauenswürdige Person, der man Freiheit zugestehen kann.}
{146}{}{OK. Tut mir leid, aber ich muss weiter.}
{147}{}{Tut mir leid, das zu hören.}
{148}{}{Darion ist schlicht und einfach verrückt. Er hat mehr Wahnvorstellungen im Kopf als sein Hund Flöhe im Fell. Soweit ich weiß, gehörte er früher einer Gang an, die ebenfalls Khans hießen. Sie haben dieses Mädchen Tandi entführt und hielten sie als Geisel. Ihr Vater hat sich darauf nicht eingelassen und heuerte einige Söldner an, um sie zu befreien. Darion hat als einziger überlebt.}
{149}{}{Oh... du sagen.}
{150}{}{Muss gehn.}
{151}{}{Mhm. Tja, ich werd jetzt gehn.}
{152}{}{Wow, ich bin beeindruckt von deinem Wissen.}
{153}{}{Klingt, als wär er mein Typ...}
{154}{}{Ich bin entführt worden. Ich war auf dem Weg von Vault City nach New Reno um meinen wohlverdienten Urlaub anzutreten. Ich ging eines Abends zu Bett und bin am nächsten Morgen gefesselt und geknebelt aufgewacht. Eine Woche später oder so war ich hier. Seitdem bin ich hier.}
{155}{}{Ugh.}
{156}{}{Danke. Ich wohl gehn.}
{157}{}{Die Schwachen sind oft die Beute der Starken.}
{158}{}{Tut mir leid, das zu hören.}
{159}{}{Interessant, aber ich muss jetzt weiter.}
{160}{}{Ja, er hat einen Hund. Wenn du mich fragst, ist es die hinterhältigste und abscheulichste Kreatur auf Erden. Aber er scheint Darion zu lieben, also kann er so schrecklich auch wieder nicht sein.}
{161}{}{Ich mehr Fragen.}
{162}{}{Äh, Tschüss.}
{163}{}{Verstehe. Danke für die Warnung.}
{164}{}{Ah. Tja, ich muss jetzt gehn.}
{165}{}{Jemandem wie dir werde ich bestimmt nicht helfen. Verschwinde.}
{166}{}{OK, also pass auf dich auf, und komm wieder wenn du irgendwas brauchst.}
{167}{}{OK.}
{168}{}{Jetzt ist er paranoid. Er glaubt, dass Tandi draußen auf ihn lauert. Er ist von Rache besessen: Er will Tandi töten. Außerdem hat er Schuldgefühle, weil er abgehauen ist und überlebt hat und nicht mit seiner Gang gestorben ist... die Liste ist endlos.}
