{100}{}{Du siehst eine Wache.}
{101}{}{Du siehst eine Wache in einer Powerrüstung.}
{102}{}{Du siehst jemanden in einer außergewöhnlichen Powerrüstung. Das Symbol auf der Brustpanzerung ist dir nicht bekannt.}
{103}{}{Nichts zu melden.}
{104}{}{Bei mir ist tote Hose und bei dir?}
{105}{}{Solltest du dich nicht auf deinem Posten befinden, Soldat? Es ist nicht gut, hier
 herumzustreunen.}
{106}{}{Du trägst keine Uniform.}
{107}{}{Du meldest dich lieber beim Sarge und lässt dich ausrüsten.}
{108}{}{Das ist sehr riskant, ohne Uniform herumzulaufen. Meld dich lieber beim Nachschub.}
{109}{}{Wer zum Teufel seid ihr...Alarm! Eindringlinge!}
{110}{}{Wir wurden unterwandert! Alarm!}
{111}{}{Eindringlinge! Schlagt Alarm!}
{112}{}{Sicherheitsalarm! Riegelt die Basis ab!}
{113}{}{Sichert alle Stationen! Wir sind im Alarmzustand}
{114}{}{Angriffsalarm! Code Rot!}
{115}{}{Dich legen wir um!}
{116}{}{Die Enklave wird die Welt beherrschen!}
{117}{}{Du stirbst, damit die Enklave überlebt!}
{200}{}{...Arschloch...}
{201}{}{...Ja…du haust BESSER ab...}
{202}{}{...was für eine Memme...}
{203}{}{...Ja, Sir! Verdammt Ja, Sir!...}
{300}{}{Warte mal. Was hast du mit dem Flugzeug vor? Es gibt keine planmäßigen Flüge für mehrere Tage.}
{301}{}{Hä?}
{302}{}{Dessen bin ich mir bewusst.}
{303}{}{Tut mir leid. Ich hab nur was geschaut. Ich werde nun gehen.}
{304}{}{Es gibt eine Planänderung. Ich nehme das Flugzeug.}
{310}{}{Was? Oh, ich seh schon. Hör mal, nicht anfassen. Okay? Fass nochmal an und du tot.}
{311}{}{[Lächle und dann greif an.]}
{312}{}{[Verschwinde]}
{315}{}{Oh Scheiße, sieht so aus als ob wir hier Eindringlinge haben. Alarmstufe Rot! Ich wiederhole, Alarmstufe Rot!}
{316}{}{Das klingt nach einer guten Idee. Fass das Flugzeug nochmal an und ich verpass dir ne Kugel in deinen Kopf.}
{320}{}{Genau. Und deshalb wirst du...}
{321}{}{Jetzt gehen. Ich wollte Sie nicht stören.}
{322}{}{Eine Wichtige Nachricht für die Hauptbasis übermitteln.}
{323}{}{Ach wirklich? Und was steht drin?}
{324}{}{Es ist streng geheim. Ich kann es nicht sagen.}
{325}{}{Ich werde es dir sagen, aber es ist absolut notwendig, dass du diese Informationen nicht an Dritte weitergibst, sonst ist eine Massenpanik zu befürchten. Weißt du, ich habe bemerkt, das eine der letzten Lieferungen von Sklaven mit einem unbekannten und höchst tödlichen Virus infiziert ist. Ich *muss* augenblicklich zur Basis gelangen, oder wir alle könnten unser Leben verlieren. Jetzt hör auf, meine Zeit zu vergeuden, da wir keine Minute erübrigen können.}
{326}{}{Ja, ich glaub dir. Sieht so aus als hätten wir einen Eindringling...}
{327}{}{Verdammt! Ach, was auch immer. Mir sagt ja nie jemand was. Gut. Geh weiter.}
{328}{}{Oh Mann, das hört sich schlimm an. Du machst dich dann besser auf den Weg, ich will für diese Scheiße nicht den Kopf hinhalten. Ach, und mach dir keine Sorgen, ich werd es keinem sagen.}
{329}{}{[Erledigt]}
