{100}{}{Du siehst jemanden in Powerrüstung. }
{101}{}{Du siehst den Basiskommandanten von Navarro.}
{102}{}{Du siehst jemanden in einer außergewöhnlichen Powerrüstung. Das Symbol auf der Brustpanzerung ist dir nicht bekannt.}
{103}{}{Wer zum Teufel seid ihr... Alarm! Eindringlinge in der Basis!}
{104}{}{Ich habe keine Zeit, mit euch Füchsen zu ratschen. Weggetreten.}
{105}{}{Zeit zum sterben.}
{106}{}{OK.}
{107}{}{Ich hab doch schon gesagt, dass ich keine Zeit für dich habe. Verlass das Büro und komm nicht wieder, außer ich schicke nach dir. Weggetreten!}
{108}{}{Die Nichtbefolgung eines direkten Befehls eines ranghöheren Offiziers ist Verrat. Ich habe keine Zeit für ein Militärgericht, das mache ich selber. Wache! Legt den Idioten um!}
{109}{}{OK.}
{110}{}{Geh zum Teufel!}
{111}{}{Der Schlüssel befindet sich im Spind da drüben. Der diensthabende Offizier soll sich bei mir melden, wenn er sichergestellt ist. Weggetreten!}
{112}{}{Jawohl, Sir!}
{113}{}{Mach schnell, Soldat, ich kann nicht den ganzen Tag hier herumstehen.}
{114}{}{Jawohl, Sir!}
{115}{}{Lass die Finger vom Spind, oder du wirst gleich echte Schmerzen erleben.}
{116}{}{Jawohl, Sir!}
{117}{}{Die Basis befindet sich in Alarmbereitschaft und ich kenne dich nicht. Zeig mir deine
 Papiere, Soldat.}
{118}{}{Welche Papiere?}
{119}{}{Erwischt!}
{120}{}{Die hab ich wohl nicht dabei...}
{121}{}{Papiere? Deine Papiere habe ich hier!}
{122}{}{Falsche Antwort, du Wurm. Du musst deine Papiere immer bei dir haben und das solltest du wissen!}
{123}{}{LMAA.}
{124}{}{Lass die Finger vom Spind, oder du wirst gleich echte Schmerzen erleben.}
{125}{}{Zeit zum sterben.}
