{100}{}{Du siehst eine nette ältere Frau.}
{150}{}{Du siehst Mom beim Kochen und Putzen.}
{151}{}{Du siehst eine stämmige ältere Frau mit einem glücklichen Lächeln im Gesicht.}
{200}{}{Hallo, ich bin Mom. Ich hab dich hier noch nie gesehen.}
{201}{}{Hallo. Was kann Mom für dich tun?}
{202}{}{Ich }
{203}{}{Mmmm. Uk? Wiedersehn, Mommy.}
{220}{}{Du hast mir hier schon fast die Haare vom Kopf gefressen. Geh doch mal 'ne Weile woanders hin. Du hast hier heute schon genug gegessen.}
{221}{}{Naja }
{222}{}{ du siehst wirklich ein bisschen verwirrt aus. Ich sehe niemanden gerne leiden. Willst du was zu essen?}
{223}{}{Ich satt. Essen von Mom gut. Wiedersehen Mom.}
{224}{}{Ich zahlen?}
{225}{}{Ich gehn. Wiedersehen Mom.}
{240}{}{Na, OK. Was hast du? (Mom greift nach deinem Geldbeutel)}
{241}{}{Mom? (Du hältst deinen Geldbeutel hin)}
{242}{}{Nein! Ich gehen. Tschüss, Mommy.}
{250}{}{Nein, eigentlich nicht. Es tut mir leid. Wir haben nur Rattenpastete, Rattenbraten und Spaghetti.}
{251}{}{Was soll es diesmal sein?}
{252}{}{Äh, könnte ich etwas mit weniger Rattenfleisch kriegen?}
{253}{}{Dann nehm ich halt den Rattenbraten.}
{254}{}{Dann nehm ich halt die Rattenpastete.}
{270}{}{Du kannst die Spaghetti nehmen, da ist nicht allzuviel Ratte drin. Eigentlich nur in der Soße.}
{271}{}{Na gut, dann nehme ich die Spaghetti mit Rattensoße.}
{280}{}{Ich besorge dir gleich eine schöne Portion. Das macht dann $10.}
{281}{}{Ich habe gerade nicht genug Geld. Ich möchte dich statt dessen etwas fragen.}
{282}{}{$10 für Ratte? Du bist wohl verrückt. Im Dorf verlangen wir viel mehr für eine schönes saftiges Stück. Wir sind im Geschäft.}
{283}{}{Na gut. Hier ist dein Geld.}
{284}{}{Ich habe es mir doch anders überlegt. Ich möchte dir lieber eine Frage stellen.}
{285}{}{Ich glaube, ich komme später noch mal wieder. Auf Wiedersehen.}
{300}{}{Du hast ziemlichen Appetit. Ich sehe gerne gesunde Esser. Ist es genug?}
{301}{}{Keine Chance, Mom, ich möchte noch 'n Nachschlag.}
{302}{}{Natürlich. Lass mich dich was fragen, Mom.}
{303}{}{Das war genug. Wiedersehn, Mom.}
{320}{}{Ich brauch jemanden, der ein Essen zu Smitty bringt. Er ist ein Stück westlich auf dem Schrottplatz. Kannst du das für mich machen? Du bekommst ein kostenloses Essen.}
{321}{}{Klar, mach ich doch gern.}
{322}{}{Das muss ich mir noch überlegen. In der Zwischenzeit möchte ich dich etwas anderes fragen.}
{323}{}{Tut mir leid, Mom. Ich kann nicht. Wiedersehn.}
{340}{}{Du hast Glück. Es gibt Radskorpion-Eintopf.}
{341}{}{Bei uns gibt's Schwein(eratte).}
{342}{}{Wir servieren gedünsteten Radskorpion-Schwanz in Buttersoße.}
{343}{}{Im Augenblick hab ich nur Kohlsuppe.}
{344}{}{Frische Brahmin-Fritten!}
{345}{}{Kochend heiße Gecko-Pastete, ist gleich fertig.}
{346}{}{Hüftsteak.}
{347}{}{Gut durchwachsene Maulwurfsratte.}
{348}{}{Floater-Frikassee.}
{349}{}{Filet Mignon.}
{350}{}{Gegrillte Geckomedallions.}
{351}{}{Gottesanbeterinnen-Curry.}
{352}{}{Maulwurfsratte Manicotti.}
{353}{}{Brahmin en brochette.}
{354}{}{Radskorpion en croute.}
{355}{}{Saftiges Ferkelfleisch.}
{356}{}{Ich bin mir nicht sicher, aber es schmeckt wie Huhn.}
{357}{}{Zentaurenkotelett, meine Spezialität.}
{358}{}{Es ist eine Überraschung.}
{359}{}{Es ist Dosenfleisch!}
{360}{}{Wirklich?}
{375}{}{Hier. Du siehst halb verhungert aus. (Mom reicht dir einen großen dampfenden Teller mit köstlich riechendem Essen.)}
{376}{}{Dan-ki, Mom.}
{385}{}{Na siehst du. Ich wusste, dass dir das schmeckt.}
{386}{}{Mmmh, lecker! Tschüss, Mom.}
{395}{}{Oh vielen Dank! Ich würde es selbst tun, aber ich kann nicht weg, weil jemand auf den Laden aufpassen muss. Hier ist das Essen für Smitty. Wenn ich nicht dafür sorgen würde, dass er was isst, würde er es wahrscheinlich vergessen.}
{396}{}{Ich bring es ihm rüber.}
{405}{}{Ich bin sehr enttäuscht von dir. Der arme Smitty musste sich sein Essen selbst abholen. Was willst du denn?}
{406}{}{Hallo! Ich heiße Mom und ich führe diesen Laden. Hier gibt's das beste Essen nördlich von New Reno.}
{407}{}{Worüber wolltest du mit Mom sprechen?}
{408}{}{Du bist nicht meine Mama.}
{409}{}{Hast du von einer Vault oder jemandem namens Vic gehört?}
{410}{}{Was kann man hier in der Stadt machen?}
{411}{}{Was gibt es hier zu Essen?}
{425}{}{Das weiß ich. Aber so nennen mich alle. Ich gehe mit den Leuten auch so um, als wären sie Verwandte. Das heißt, solange meine Regeln befolgt werden.}
{426}{}{Regeln?}
{435}{}{Genau! Kein Stehlen, kein Fluchen und keine Schlägereien. So was gibt's hier nicht. Sonst fliegste raus. Ich will, dass es hier friedlich zugeht.}
{436}{}{Ach so. Lass mich dich noch was fragen.}
{437}{}{Das sehe ich ein. Bis später, Mom.}
{445}{}{Mal sehen, im Westen und etwas nördlich von hier liegt die sogenannte Vault City. Und Vic, hmm, lass mich nachdenken.}
{446}{}{Ich hoffe, du weißt, wo Vic ist. Er ist ein Händler.}
{447}{}{Danke, aber mehr muss ich nicht wissen. Tschüss, Mom.}
{455}{}{Händler Vic? Das kommt mir bekannt vor. Ja, ich glaube, er wird aus irgendeinem Grund von Metzger festgehalten.}
{456}{}{Wer ist Metzger und wo finde ich ihn?}
{457}{}{Sehr gut, Mom. Danke.}
{465}{}{Metzger ist der Anführer der hiesigen Sklavenhändlergilde. Er hat alle möglichen Leute bei sich eingesperrt. Es ist hier die Straße lang, genau nördlich von hier.}
{466}{}{Metzger war früher der Anführer der hiesigen Sklavenhändlergilde. Er hatte alle möglichen Leute bei sich eingesperrt. Wie's jetzt ist, weiß ich nicht. Hab gehört, er wurde umgebracht.}
{467}{}{Danke für die Informationen. Ich möchte dich aber noch was anderes fragen, Mom.}
{468}{}{Ich muss mich um was Geschäftliches kümmern. Danke, Mom.}
{475}{}{Dann bring das Essen jetzt mal zu Smitty.}
{476}{}{Ich helfe dir nur, wenn du versprichst, Wort zu halten.}
{477}{}{Beeil dich jetzt.}
{478}{}{Geh und bring Smitty sein Essen. Beeil dich.}
{479}{}{Jetzt raff dich endlich auf und bring das Essen zu Smitty.}
{485}{}{Das war gute Arbeit. Du hast jetzt bestimmt großen Appetit. Als Belohnung habe ich etwas
 ganz Besonderes für dich. Einen gemischten Teller mit dem besten Essen, das ich habe.
 Nur für dich.}
{486}{}{Das hört sich klasse an! Immer her damit!}
{487}{}{Puh, Mom, ich kann jetzt echt nichts essen. Trotzdem danke. Wiedersehn.}
{500}{}{Hmm, ich weiß nicht viel darüber. Wahrscheinlich macht sich bloß jemand einen Spaß.}
{501}{}{Hat es dort schon immer gespukt?}
{502}{}{Ist dieses Haus bewohnt?}
{503}{}{Glaub ich auch. Tschüss.}
{520}{}{Es hat vor ungefähr 2 Jahren angefangen. Ich habe von dem Stöhnen und den Geistern und so gehört.
 Ich glaube aber nicht daran.}
{521}{}{Also zwei Jahre? War das Haus damals bewohnt?}
{522}{}{Ich auch nicht. Danke!}
{540}{}{Einer der Jungs hat da vor ein paar Jahren übernachtet. Vielleicht weiß er etwas.}
{541}{}{Wer?}
{542}{}{Wahrscheinlich nicht. Tschüss.}
{560}{}{Er ist öfters vorbeigekommen und wollte Sachen versetzen. Hauptsächlich Schmuck.
 Ich erinnere mich an ein kleines Goldmedaillon, das er selbst behielt.}
{561}{}{Erinnerst du dich an seinen Namen?}
{562}{}{Medaillon? Seltsam. Wer war das?}
{563}{}{Ich möchte dich noch was anderes fragen.}
{564}{}{Danke, Tschüss.}
{580}{}{Ich bin mir nicht sicher. Er hieß Joe oder Joel oder so ähnlich. Er ist jetzt fast 19.
 Er hat sich hier ein paar Schlägern angeschlossen.}
{581}{}{Danke. Ich möchte dich noch was fragen.}
{582}{}{Danke, Tschüss.}
{600}{}{Was weißt du über das Haus, in dem es spukt?}
