{100}{}{You see a chem reliant.}
{101}{}{Du siehst Petey.}
{150}{}{This here is a poor chem reliant.}
{151}{}{Petey sieht aus, als könnte er Hilfe gebrauchen.}
{152}{}{[plaudern]}
{155}{}{[hust, hust] Hast Du etwas Kleingeld für Petey übrig?}
{156}{}{Sicher, hier hast Du etwas.}
{157}{}{Nein, laß mich in Ruhe.}
{158}{}{Peetee?}
{159}{}{Du bist schlimmer dran als ich. [hust] Trotzdem danke.}
{160}{}{Tut mir leid. Tschüß.}
{161}{}{Puh, gerne geschehen, uh-huh, ja.}
{162}{}{Vielleicht beim nächsten Mal. Trotzdem danke. [hust]}
{163}{}{[Fertig]}
{164}{}{Vielen Dank. [hust] Vielen, vielen, vielen Dank.}
{165}{}{Gern geschehen.}
{166}{}{Ja, ja.}
{167}{}{Gnä' Herr, [hust] können Sie einem armen Mann helfen, den das Glück verlassen hat?}
{168}{}{Here's $5.}
{169}{}{Heute nicht.}
{170}{}{Such' Dir einen Job.}
{171}{}{Verehrte Dame, bitte helfen Sie [hust] einem armen, verhungernden Mann, der [hust]
 zu krank zum Arbeiten ist.}
{172}{}{Du armes Ding, hier hast Du $5.}
{173}{}{Ich gebe Bettlern prinzipiell nichts.}
{174}{}{Nein.}
{200}{}{Hey, Mann. Gibst Du mir etwas Kohle?}
{201}{}{Haben Sie etwas Kleingeld übrig, verehrter Herr?}
{202}{}{Hey, kannst Du mir mit ein paar Kröten aushelfen?}
{203}{}{Do you think you can help me out with a coupla dollars?}
{204}{}{Könntest Du mir vielleicht ein paar Kröten leihen?}
{205}{}{Haben Sie etwas Kleingeld übrig, verehrte Dame?}
{206}{}{Hey, Frollein haste was Kohle übrig?}
{220}{}{Bitte helfen Sie mir, Herr.}
{221}{}{Ahhh, es tut weh.}
{222}{}{Ich brauche Hilfe. Es tut sehr weh.}
{223}{}{Gnädige Frau, können Sie Hilfe holen?}
{225}{}{Ich weiß das sehr zu schätzen.}
{226}{}{Hey, was glaubst Du, was Du da machst?}
{230}{}{Fühlt sich sehr gut an.}
{231}{}{Ähhh...}
{232}{}{[kicher]}
{233}{}{Hey...}
{300}{}{Ahhh, someone fucking killed Tubby?}
{301}{}{Was zum Teufel ist mit Tubby passiert?}
{302}{}{Oh shit, Tubby's...}
{303}{}{Ahhh...}
{304}{}{Konnte den Hundesohn sowieso nicht leiden.}
{305}{}{Flick's dead? Crap.}
{306}{}{Was ist mit Flick passiert?}
{307}{}{Flick...}
{310}{}{Hey Tubby, I, Uhhh, need some help here.}
{311}{}{HEY TUBBY!}
{312}{}{Hallo.}
{313}{}{HEY!}
{314}{}{Hey Flick, I, Uhhh, need some help here.}
{315}{}{HEY FLICK!}
{320}{}{Hey Tubby, kannst Du mir was beschaffen? Ich habe Bargeld.}
{321}{}{Ähm, Tubby, ich habe etwas Geld.}
{322}{}{Ähhh...}
{323}{}{Ich brauche etwas Jet, Mann.}
{324}{}{Hey, Flick. Kannst Du mir was beschaffen? Ich habe Bargeld.}
{325}{}{Ähm, Flick, ich habe etwas Geld.}
{330}{}{Ähhh... Danke nochmal, Tubby.}
{331}{}{Bist echt ein Kumpel, Tubby.}
{332}{}{Ich verspreche, morgen höre ich auf.}
{333}{}{Du bist ein echter Freund.}
{334}{}{Ähhh... Danke nochmal, Flick.}
{335}{}{Bist echt ein Kumpel, Flick.}
