{100}{}{Du siehst einen Mann der eine MKII Power-Rüstung trägt. Er sieht nicht freundlich aus.}
{101}{}{Ne jetzt... Du siehst Kaga der eine MKII Power-Rüstung trägt.}
{102}{}{Ein großes Stück aus Metall und Armen mit Waffen daran.}
{103}{}{Ich werde der Verfolgung müde. Lass es uns beenden.}
{104}{}{Das ist das letzte Mal, dass wir uns treffen werden, Kaga.}
{105}{}{Du bist keine Herausforderung für Kaga!}
{106}{}{Ich freue mich darauf, dich endlich in dein nächstes Leben zu schicken.}
{107}{}{Du bist ein würdiger Feind gewesen.}
{108}{}{Dieser Teil des Ödlands braucht keinen Weltverbesserer wie dich!}
{109}{}{Nachdem ich dich getötet habe, werde ich die am meisten gefürchtete Person in diesem Teil des Ödlands sein.}
{110}{}{Ich freue mich schon darauf, nach Arroyo zurückzukehren - um es nieder zu brennen!!!}
{111}{}{Kaga wird berühmt sein, wenn er dich getötet hat.}
