{100}{}{Du siehst einen Mann der eine Lederrüstung trägt.}
{101}{}{Du siehst Kaga.}
{102}{}{Er trägt eine Lederrüstung und hat die Unsitte bei einer Unterhaltung über sich selbst in der dritten Person zu Sprechen.}
{103}{}{Das wird das letzte Mal sein wo du Kaga siehst.}
{104}{}{After Kaga kill yous, he will burn Arroyo to the ground.}
{105}{}{Fühle den Zorn des Kaga!}
{106}{}{Ich bin der große Kaga!}
{107}{}{Kaga wird von allen gefürchtet.}
{108}{}{Kaga wird deinen Kopf als Trophäe behalten.}
{109}{}{Gib auf und dein Tod wird schnell sein.}
{110}{}{Kaga wird zurückkommen!}
{111}{}{Du kannst den großen Kaga nicht töten!}
{112}{}{Du hast Glück, dass Kaga woanders geschäftliche Dinge zu erledigen hat.}
{113}{}{Kaga wird dich wiedertreffen.}
