{100}{}{Du siehst einen Mann der eine Kampfrüstung trägt.}
{101}{}{Du siehst den verdammten Kaga in einer Kampfrüstug.}
{102}{}{Das glaube ich jetzt nicht... Kaga hat nun eine Kampfrüstung und scheint einige anständige Waffen zu besitzen.}
{103}{}{Dieses mal bin ich vorbereitet!}
{104}{}{Das "Auserwählte Wesen wird niemals nach Arroyo zurückkehren!}
{105}{}{Kaga wird dich zerquetschen!}
{106}{}{Kaga fürchtet niemanden!}
{107}{}{Stillhalten, damit Kaga einen guten Treffer landen kann.}
{108}{}{Wir werden uns wiedersehen!}
{109}{}{Dies ist nicht das letzte mal an dem du Kaga sehen wirst.}
{110}{}{Kaga braucht definitiv mehr Training.}
