{100}{}{Du siehst einen Mann der eine Metallrüstung trägt.}
{101}{}{Du siehst Kaga.}
{102}{}{Jepp, es ist Kaga "Der nicht so Große". Er besitzt nun eine Metallrüstung und will dich töten.}
{103}{}{Du schon wieder!}
{104}{}{Ich habe unsere ermüdenden treffen langsam satt.}
{105}{}{Das "Auserwählte Wesen" - Pah!}
{106}{}{Bringen wir es endlich hinter uns.}
{107}{}{Du wirst es bereuen, jemals den Namen Kaga gehört zu haben!}
{108}{}{Meine Fähigkeiten haben sich seit unserem letzten zusammentreffen verbessert.}
{109}{}{Das scheint wohl eine schlechte Angewohnheit von dir zu werden.}
{110}{}{Kaga muss noch ein bisschen trainieren.}
{111}{}{Kaga wird wiederkommen.}
