{100}{}{Du siehst einen Mann der wenig Kleidung trägt.}
{101}{}{Du siehst Kaga.}
{103}{}{Er trägt eine Hose und sieht aus, als wenn er aus deinem Stamm käme.}
{104}{}{Ich sollte das "Auserwählte Wesen" sein!}
{105}{}{Wie konnten Sie es nur wagen, mich aus dem Dorf zu verbannen.}
{106}{}{Ich werde mich an dir Rächen!}
{107}{}{Kaga wird dich in dein nächstes Leben senden!}
{108}{}{Wir werden uns wiedersehen!}
{109}{}{Ich wurde noch nie zuvor besiegt!}
{110}{}{Ich werde es zu meinem Ziel machen dich zu vernichten.}
