{100}{}{Ein Reisender.}
{101}{}{Sei gegrüßt, Reisender.}
{102}{}{Ich hab mich verirrt. Kannst du mir helfen?}
{103}{}{Wohin willst du?}
{104}{}{Was machst'n du so?}
{105}{}{Agh.}
{106}{}{Nun... Keine Ahnung. Ich bin ziemlich neu hier in der Gegend und kam bisher nur an folgenden Orten vorbei.}
{107}{}{New Reno}
{108}{}{Vault City}
{109}{}{Redding}
{110}{}{Den}
{111}{}{San Francisco}
{112}{}{New California Republic}
{113}{}{Eine aufgegebenen Mine.}
{114}{}{Ne, da war ich schon. Trotzdem danke.}
{115}{}{New Reno -- Das ist ne Stadt Mann. Sex, Drogen und Glücksspiel. Was kann man da noch verlangen? Lass mich dir zeigen wo es liegt.}
{116}{}{Danke.}
{117}{}{Vault City -- Also das ist die Stadt der Vollidioten. Lässt dir nen Extrafinger wachsen und schon behandeln sie dich wie nen Freak. War nie drin, aber ich weiß wo es liegt.}
{118}{}{Danke.}
{119}{}{Redding... Weiß nicht mehr, als das es ne alte Minenstadt ist. Es liegt im Norden, gleich im Schoß der gemeinsten Berge die du je gesehen hast.}
{120}{}{Danke.}
{121}{}{Ich würd mich an deiner Stelle von Den fern halten. Es ist eine Anlaufstelle für allen möglichen Abfall in der Gegend. Ich zeig dir wo es ist  aber ich rate dir dort nicht hinzugehen.}
{122}{}{Danke.}
{123}{}{San Francisco. Öhm... alles was Ich darüber sagen kann ist, dass die Leute dort... Merkwürdig sind. Es ist an der Küste.}
{124}{}{Danke.}
{125}{}{Die NCR. Ist ne nette Stadt. Ich würd mich dort eines Tages gerne zur Ruhe setzen. Sauber, nette Leute und ziemlich gut ausgebaut. Es ist gleich hier auf deiner Karte.}
{126}{}{Danke.}
{127}{}{Ja, vor ner Weile traf ich auf ein verlassenes Zeltlager bei einer Mine. Hab geplant, mich für ein oder zwei Tage dort auszuruhen. Aber dann tauchten überall Wölfe auf und ich dachte mir, dass es das Beste wäre zu verduften. Wirklich schade, die Minenarbeiter müssen den Platz in ziemlicher Eile geräumt haben. Die ließen allerhand Zeug dort liegen. Ich beabsichtige nicht, dahin zurückzukehren aber ich denk es ist in Ordnung wenn ich dir den Weg zeig.}
{128}{}{Danke.}
{129}{}{Oh... Ist wirklich nicht wichtig. Eines Tages dachte ich mir, fängst du an zu wandern, und nun bin ich hier.}
{130}{}{Vielleicht kannst du mir helfen. Ich brauch ein paar Wegbeschreibungen.}
{131}{}{Was machst'n du so?}
{132}{}{War nett mit dir zu reden.}
{133}{}{Ich halt mich hier und da mit Gelegenheitsjobs über Wasser. Aber die meiste Zeit reise ich einfach.}
{134}{}{Vielleicht kannst du mir helfen. Ich brauch ein paar Wegbeschreibungen.}
{135}{}{Wohin gehst du?}
{136}{}{War nett mit dir zu reden.}
{137}{}{Ich sollte jetzt wirklich weiter. War nett mit dir Bekanntschaft zu machen.}
{138}{}{Vielleicht sehen wir uns wieder.}
{139}{}{Ich möchte noch vor Sonnenuntergang in der nächsten Stadt sein. Ich geh besser.}
{140}{}{Ich geh dann besser.}
{141}{}{Hinterhalt!}
{142}{}{Heutzutage kann man niemandem trauen.}
{143}{}{Du hast die Regeln des Reisens gebrochen.}
{144}{}{Zeit zu gehen.}
{145}{}{Meine Gastfreundschaft wird überstrapaziert.}
{146}{}{Ich muss weiter.}
{150}{}{Danke. Ich brauch eine Wegbeschreibung zu anderen Orten.}
