{100}{}{Du siehst einen Mann, der aussieht wie ein Ladenbesitzer.}
{101}{}{Du siehst Lao Chou, den Ladenbesitzer.}
{102}{}{Du siehst einen Mann in bequemer Arbeitskleidung.}
{103}{}{Guten Tag! Willkommen in meinem Laden, dem Fliegenden 8. Drachen.}
{104}{}{Was kann ich für dich tun?}
{105}{}{Da eggel uuh!     }
{106}{}{Sachen!}
{107}{}{Wer bist du?}
{108}{}{Ich brauche eine Ausrüstung.}
{109}{}{Ich bräuchte da mal ein paar Infos.}
{110}{}{Tschüss.}
{111}{}{Möchtest du was kaufen?}
{112}{}{::Kopfnicken::}
{113}{}{::Kopfschütteln::}
{114}{}{Hier siehst du, was wir haben.}
{115}{}{[Erledigt]}
{116}{}{Tja, dann kann ich dir wohl leider nicht weiterhelfen. Guten Tag.}
{117}{}{[Erledigt]}
{118}{}{Ich bin Lao Chou. Mir gehört dieser Laden, Fliegender 8. Drache heißt er, ein Laden für alles. Aber ich handle vor allem mit... Informationen.}
{119}{}{Was für Informationen?}
{120}{}{Aha. Ich hätte gern eine Ausrüstung.}
{121}{}{In dieser Stadt passiert kaum etwas, worüber ich nicht Bescheid wüsste. Natürlich musst du wissen, welche Frage du stellen musst, klar? Was willst du also wissen?}
{122}{}{Ich will meine Ausrüstung aufrüsten.}
{123}{}{Wo bekomme ich Vertibird-Pläne?}
{124}{}{Ich brauche Benzin für die PHS Valdez.}
{125}{}{Man sagte mir, ich brauche einen SHS, um auf den Valdez-Computer zuzugreifen.}
{126}{}{Ich brauche Computerteile für die PHS Valdez.}
{127}{}{Ich suche eine Milz.}
{128}{}{Ich hab gehört, eine Gruppe von Dorfbewohnern wurde von Flugmaschinen hierher gebracht.}
{129}{}{Nichts. Tschüss.}
{130}{}{Am besten redest du mit Crockett, drüben im Hubologen-Lager. Er ist ihr Chefwissenschaftler.}
{131}{}{Danke. Ich brauche mehr Informationen.}
{132}{}{Danke. Tschüss.}
{133}{}{Geh nach Norden. In Navarro liegt eine versteckte Basis in der Nähe der Tankstelle.}
{134}{}{Danke. Ich brauche mehr Informationen.}
{135}{}{Danke. Tschüss.}
{136}{}{Hast du es schon in den alten Vaults versucht? Angeblich haben sie da eine Fülle von Informationen und Technologien der Alten Welt.}
{137}{}{Danke. Ich brauche mehr Informationen.}
{138}{}{Danke. Tschüss.}
{139}{}{Eine Milz? Ha ha! Mal sehn, Chip von der Valdez hat neulich seine Milz beim Kartenspielen verloren. Ich hab sie Dr. Wong verkauft. Er war sehr daran interessiert.}
{140}{}{Dr. Wong? Wo finde ich ihn?}
{141}{}{Wie kann man denn seine Milz verlieren?}
{142}{}{Danke. Ich habe noch weitere Fragen.}
{143}{}{Ach so. Wiedersehn.}
{144}{}{Dr. Wong ist Chefwissenschaftler im Stahlpalast. Dort wirst du ihn finden.}
{145}{}{Wie kann man denn überhaupt eine Milz verlieren?}
{146}{}{Danke. Ich brauche mehr Informationen.}
{147}{}{Danke. Tschüss.}
{148}{}{Er war betrunken. Sturzbetrunken. Den ganzen Abend hat ihm seine Milz zu schaffen gemacht. Da hat er sie halt verwettet.}
{149}{}{Also du hast seine MILZ genommen?}
{150}{}{Ach so. Ich hätte noch ein paar Fragen.}
{151}{}{Ja. Es war eine Spielschuld und er ist ein ehrlicher Mensch.}
{152}{}{Ach so. Ich brauche noch weitere Informationen.}
{153}{}{Du perverser, unverschämter Mistkerl!}
{154}{}{OK. Wiedersehn.}
{155}{}{Du bist kein rechtschaffener Mann. Ich will dich nicht in meinem Laden haben. Komm ein andermal wieder.}
{156}{}{Wie du willst.}
{157}{}{Das stimmt nicht. Sie kamen von Norden und sind über uns hinweg aufs Meer hinaus geflogen.}
{158}{}{Richtung Horizont? Wie zum Henker soll ich da hinkommen?}
{159}{}{Dass ich nicht lache! Du sagst mir jetzt, wo sie sind, oder ich schneid dich auf wie eine Sardinenbüchse.}
{160}{}{Mmh... keines unserer Boote ist für solche Entfernungen geeignet. Es sei denn...}
{161}{}{Es sei denn...?}
{162}{}{Vielen Dank für die "Hilfe". Ich geh und hol mir woanders 'ne richtige Auskunft.}
{163}{}{... es sei denn, du kriegst den alten Tanker im Trockendock wieder hin. Das Schiff ist zwar alt, aber lässt sich mit ein bisschen Arbeit bestimmt wieder flott machen. Frag die Vagabunden, wenn du mehr wissen willst.}
{164}{}{Danke. Ich brauche mehr Informationen.}
{165}{}{Danke. Tschüss.}
{166}{}{Es geht das Gerücht um, die Hubologen seien vor kurzem in den Besitz größerer Mengen Benzins gekommen. Handel doch mit denen.}
{167}{}{Danke. Ich brauche mehr Informationen.}
{168}{}{Danke. Tschüss.}
{169}{}{Versuch's doch mal bei den Shi-Wissenschaftlern im Stahlpalast. Vielleicht können die dir mit Benzin aushelfen.}
{170}{}{Danke. Ich brauche mehr Informationen.}
{171}{}{Danke. Tschüss.}
{172}{}{Du bist ein Feind meines Volkes. Stirb!}
{173}{}{Du hast meinem Volk geholfen, indem du AHS-9 vernichtet hast. Ich hoffe, ich kann auch dir irgendwie weiterhelfen.}
{174}{}{Wer bist du?}
{175}{}{Ich brauche eine Ausrüstung.}
{176}{}{Ich bräuchte da mal ein paar Infos.}
{177}{}{Tschüss.}
{178}{}{Du hast sie schon den Hubologen gegeben, stimmt's?}
{179}{}{Ja...ähm...ich hätte da noch 'ne Frage...}
{180}{}{Ja...Wiedersehn.}
