{100}{}{Du siehst jemanden der eine Kapitänsmütze trägt.}
{101}{}{Du siehst Kapitän A. Ron Meyers.}
{102}{}{Du siehst einen Vagabunden in zerrissenen Klamotten der eine Kapitänsmütze trägt.}
{103}{}{Was zum Teufel willst du? Ich rede mit niemanden, außer mit Freunden oder guten Menschen. Tu was für einen meiner Kumpels, dann kannst du wiederkommen. }
{104}{}{[Erledigt]}
{105}{}{Ich habe gehört, was du für meine Männer getan hast. Vielen Dank. Womit kann ich dir helfen? }
{106}{}{Du wer?}
{107}{}{Man sagte mir, du bist derjenige, der alles über dieses Schiff weiß.}
{108}{}{Wieso nennt man dich den Kapitän?}
{109}{}{Wie bringt man dieses Ding in Gang?}
{110}{}{Nichts.}
{111}{}{Ich bin der Kapitän. Ich kommandiere dieses Schiff. Falls du noch mehr Fragen hast, geh zu einem der Shi oder zu Dachs oder so. Ich habe keine Zeit für dich. }
{112}{}{[Erledigt]}
{113}{}{This ship's a Poseidon tanker. It's equipped with tech that lasted through the war. It's got a FOB that allows access to the navigation computer room, and it's got an IFF transponder that protects it from Poseidon guns.}
{114}{}{Woher weißt du das alles?}
{115}{}{Was ist ein IFF-Transponder?}
{116}{}{Wie bringst du ihn zum Laufen?}
{117}{}{Danke. Tschüß.}
{118}{}{Ich tat Dienst in der Enklave, bis mir aufging, daß ich nicht für die USA kämpfte, sondern für ein paar reiche alte Hirnrisse, die an der Macht bleiben wollten. Da bin ich desertiert und nun lebe ich hier zusammen mit anderen ehrlichen Leuten.}
{119}{}{Ehrliche Leute? Meinst du etwa diese Typen?}
{120}{}{Was genau ist eigentlich die Enklave?}
{121}{}{Wie bringt man dieses Ding in Gang?}
{122}{}{Tschüß.}
{123}{}{How do you pilot this rig? Fill 'er up with some gas - try the Hubologists or the Shi after you've taken care of everything else - and press the button. The computer will take care of the rest, if it's still working. It'll sail right out to the oil rig, and they won't fire at you because you've got the IFF transponder. Just make sure you've got what you need to access everything: FOB, working computer, and fuel. Easy enough, huh?}
{124}{}{Klar. Woher weißt du das alles?}
{125}{}{Was ist ein IFF-Transponder und ein SHS?}
{126}{}{Was für eine Bohrinsel?}
{127}{}{Ja. Tschüß.}
{128}{}{IFF: Identifiziere Freund oder Feind. Das bedeutet, daß dieses Schiff als Freund identifiziert wird und andere Poseidon-Stationen, wie zum Beispiel eine Bohrinsel, nicht auf dich feuern, wenn du in Schußweite kommst. Ach so, und ein SHS ist eine Art Technologie der Enklave, mit der du eine Tür elektronisch öffnen kannst. Wahrscheinlich wirst du einen in einer ihrer Basen finden.}
{129}{}{Woher weißt du das alles?}
{130}{}{Was für eine Bohrinsel?}
{131}{}{Danke. Tschüß.}
{132}{}{Ja. Bei diesen Leuten weißt du genau, woran du bist. Sie fackeln nicht lange. Die Enklave war wie ein Rudel Hyänen, von einer Sekunde zur nächsten fallen sie über dich her.}
{133}{}{Was genau ist eigentlich die Enklave?}
{134}{}{Wie bist du an sie geraten?}
{135}{}{Die Enklave ist ein Relikt aus alten Tagen. Wenn du in diesem Ding hier übers Wasser zur Bohrinsel kommst, wirst du es selbst sehen.}
{136}{}{Wie kann ich es steuern?}
{137}{}{Was für eine Bohrinsel?}
{138}{}{Ganz einfach. Ich hab die Navarro-Basis eines Tages verlassen und bin hier runter gekommen, weil ich dachte, das ist bestimmt der letzte Ort, wo man mich suchen wird. Außerdem bin ich nicht wichtig genug, als daß die Enklave nach mir suchen würde. Ich bin nur ein kleiner Fisch. }
{139}{}{Was genau ist eigentlich die Enklave?}
{140}{}{Danke. Tschüß.}
{141}{}{Es gibt noch eine große Poseidon-Bohrinsel draußen auf dem Wasser. Sie ist die letzte Basis der Enklave.}
{142}{}{Woher weißt du das alles?}
{143}{}{Was passiert sonst noch da draußen auf der Bohrinsel?}
{144}{}{Danke. Tschüß.}
{145}{}{Neuigkeiten verbreiten sich eben.}
{146}{}{Ach so. Was passiert sonst noch da draußen auf der Bohrinsel?}
{147}{}{Ich verstehe. Bis dann.}
{148}{}{Da muß ich passen. Ich war ein Techniker in Navarro, mit dem Bohrinselbetrieb hatte ich nichts zu tun. Wir haben mit den zuständigen Leuten per Videoübertragung kommuniziert, das war so ziemlich alles. }
{149}{}{Ach so. Also, wie soll ich das Ding noch mal steuern?}
{150}{}{Danke. Tschüß.}
{151}{}{Du hast einen großen Fehler gemacht, als du dich mit dem Kapitän und seinen Freunden angelegt hast...}
{152}{}{How do you pilot this rig? Well, I see you already gassed her up. When you've taken care of everything else, just press the button. The computer will take care of the rest, if it's still working. It'll sail right out to the oil rig, and they won't fire at you because you've got the IFF transponder. Just make sure you've got what you need to access everything: FOB, working computer, and fuel. Easy enough, huh?}
{153}{}{Oh ja. Du mußt auch den Navigationscomputer funktionstüchtig machen. Ich wette du findest in den alten Vaults die Teile.}
{154}{}{Schön, dich wiederzusehen, Was brauchst du?}
{155}{}{, und ich Wette, das deine Freunde auch dort sind.}
{156}{}{.}
