{100}{}{Du siehst ein Terminal.}
{101}{}{Du siehst das Kaisercomputer-Terminal.}
{102}{}{Du siehst einen Computer mit einem eigebauten Touch-Screen Monitor. Auf der Seite ist die Aufschrift "Kaisercomputer-Terminal Version 8.8" eingraviert.}
{103}{}{Willkommen. Bitte Kennwort eingeben und Identität bestätigen.}
{104}{}{::Sabber::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{[Hack dich in den Computer]}
{109}{}{Abmelden}
{110}{}{Identität bestätigt.}
{111}{}{Auf welche Funktion möchtest du zugreifen?}
{112}{}{Diagnose.}
{113}{}{Datenbank.}
{114}{}{Prognosen.}
{115}{}{Keine.}
{116}{}{Bitte mit Systemverwalter in Verbindung setzen. Auf Wiedersehen.}
{117}{}{[Hack dich in den Computer]}
{118}{}{[Geh]}
{119}{}{Eindringling in System. Alarm. Sitzung wird beendet. Auf Wiedersehen.}
{120}{}{[Erledigt]}
{121}{}{Diagnosefunktionen?}
{122}{}{Netzwerk durchsuchen.}
{123}{}{Festplatte formatieren.}
{124}{}{Festplatte auf Fehler überprüfen.}
{125}{}{Zurück.}
{126}{}{Welche Datenbank soll überprüft werden?}
{127}{}{Biologie.}
{128}{}{Chemie.}
{129}{}{Physik.}
{130}{}{Geschichte.}
{131}{}{Zurück.}
{132}{}{Die Kinder von Shi-Town sind in Gefahr. Die Wahrscheinlichkeit, dass ein Killer unter ihnen ist, liegt bei 50%.}
{133}{}{Shi-Town ist in Gefahr. Die Wahrscheinlichkeit, dass den Einwohnern etwas zustößt, liegt bei 75%.}
{134}{}{Die Wahrscheinlichkeit eines Fehlstarts der Hubologenrakete liegt bei 95%. Gründe: Kein Treibstoff, ungeeignetes Dichtungsmaterial, schlechte Führung, Mangel an Initiative.}
{135}{}{Die Wahrscheinlichkeit, dass der sogenannte "Auserwählte" seine Aufgabe erfüllt, liegt bei 15%.}
{136}{}{Eingabewert zeigt, dass "Enklave" stärker als vermutet. Nicht annähern.}
{137}{}{Wahrscheinlichkeit, dass U-Boot in diesem Spiel wieder auftaucht: 0%}
{138}{}{Wahrscheinlichkeit, dass die Tankervagabunden die Monsterplage ohne Hilfe von außen bewältigen gleich 0%. Nutzen einer Hilfeleistung wird untersucht.}
{139}{}{Eingabe: Poseidon-Öltanker nicht bereit zum Auslaufen. Weitere Eingaben nötig.}
{140}{}{Keine Bearbeitung. Weitere Eingaben nötig}
{141}{}{[Mehr]}
{142}{}{Zurück.}
{143}{}{Biologiestation: Aktiv}
{144}{}{Biologiestation: Inaktiv}
{145}{}{Chemiestation: Aktiv}
{146}{}{Chemiestation: Inaktiv}
{147}{}{Physikstation: Aktiv}
{148}{}{Physikstation: Inaktiv}
{149}{}{Biologiestation deaktivieren.}
{150}{}{Chemiestation deaktivieren.}
{151}{}{Physikstation deaktivieren.}
{152}{}{Zugriff zu Biologiestation.}
{153}{}{Zugriff zu Chemiestation.}
{154}{}{Zugriff zu Physikstation.}
{155}{}{Biologiestation aktivieren.}
{156}{}{Chemiestation aktivieren.}
{157}{}{Physikstation aktivieren.}
{158}{}{Zurück.}
{159}{}{Festplatte formatieren. Bei diesem Vorgang werden alle Daten gelöscht. Soll Laufwerk wirklich formatiert werden?}
{160}{}{Ja.}
{161}{}{Nein.}
{162}{}{Die Funktionalität dieses Systems liegt bei 92%.  Im abgeschirmten Kern des Kaisercomputers bei 100%. Die Integrität der Daten beträgt 100%. Stromversorgungsprobleme am Prognoseknotenpunkt - zur Reparatur veranschlagte Zeit: 6 Tage. Prognose zu 15% einsatzbereit.}
{163}{}{Zurück.}
{164}{}{Soll diese Einheit wirklich formatiert werden? Dieser Vorgang ist unumkehrbar.}
{165}{}{Ja.}
{166}{}{Nein.}
{167}{}{Formatierung wird durchgeführt... Formatierung abgeschlossen. Neustart erfordert komplette Installation. System wird heruntergefahren... Beendet...}
{168}{}{[Erledigt]}
{169}{}{Daten für: - Botanikprogramm - Genetikprogramm - Xeno-Programm.}
{170}{}{Botanikprogramm.}
{171}{}{Genetikprogramm}
{172}{}{Xeno-Programm.}
{173}{}{Zurück.}
{174}{}{(Nach ca. zwanzig Minuten, entdeckst du folgendes: Erste Ergebnisse über botanische Strahlenbarrieren sind nicht sehr vielversprechend. Dr. Sheng entwickelt Pflanzen, die gegen Strahlung resistent sind - mit unerwünschten Nebenwirkungen. Entstandenes Pflanzengut scheint zu gefährlich. Sheng besteht darauf, mit Experiment fortzufahren und es mit dem genetischen Programm zu verbinden.}
{175}{}{Genetikprogramm}
{176}{}{Xeno-Programm.}
{177}{}{Zurück.}
{178}{}{(Nach etwa zwanzig Minuten setzt du folgende Informationen zusammen: Dr. Long Wang ist davon überzeugt, dass er auf der Grundlage des FEV-Virus Mutantensoldaten erschaffen kann. Er entwickelt ein Serum, das interessante Ergebnisse bei Versuchen mit Nagetieren bringt. Er macht einen Selbstversuch und wird zu einer Schmalzlache. Dr. Sheng stellt die Versuchsreihe ein. Nach dem Tod von Dr. Long wird Dr. Sheng sein Nachfolger. Sheng befiehlt, die Forschungsarbeit auf strahlenabsorbierende Pflanzen zu konzentrieren.)}
{179}{}{Botanikprogramm.}
{180}{}{Xeno-Programm.}
{181}{}{Zurück.}
{182}{}{"Das Versuchsobjekt, an dem wir eine Reihe von bedeutenden Experimenten durchführen wollten, ist verschwunden, wahrscheinlich zerstört oder von den Hubologen gestohlen. Alle weiteren Nachforschungen verliefen ergebnislos. Diese Datenbank wird bis zum Erhalt weiterer Exemplare gesperrt bleiben." - Dr. Sheng}
{183}{}{Botanikprogramm.}
{184}{}{Genetikprogramm}
{185}{}{Zurück.}
{186}{}{Chemiedatenbank: Benzin und Derivate - Polymere}
{187}{}{Benzin und Derivate}
{188}{}{Polymere}
{189}{}{Zurück.}
{190}{}{(Nach Durchsicht der komplexen chemischen Formeln und Laboraufzeichnungen, stellst du fest, dass die Shi eine Art Kraftstoff aus Pflanzenextrakten und Meereslebewesen entwickelt haben. Anscheinend  haben sie bereits bestehende Pipelines benutzt, um den Treibstoff an möglichst viele Orte zu transportieren)}
{191}{}{(Du entdeckst eine unglaubliche Masse komplexer chemischer Formeln und Laboraufzeichnungen. Du weißt nicht genau, was das alles zu bedeuten hat.}
{192}{}{Leite Benzin zum Poseidon-Tanker.}
{193}{}{Leite Benzin zu Hubologen.}
{194}{}{Zurück.}
{195}{}{(Nachdem du dich durch die Symbolik und die technischen Abhandlungen gekämpft hast, entdeckst du, dass die Shi an einer neuen feuer- und waffensicheren Polymer-Kampfrüstung arbeiten. Sie sind noch meilenweit von der Vollendung entfernt. Es ist außerdem von neuen Waffen und Konstruktionsmöglichkeiten die Rede. Anscheinend haben die Shi so manche Zukunftspläne.}
{196}{}{Zurück.}
{197}{}{Benzin wurde entsprechend umgeleitet. Lagertanks = Leer. Programm wird geschlossen.}
{198}{}{[Erledigt]}
{199}{}{Benzin wurde entsprechend umgeleitet. Lagertanks = Leer. Programm wird geschlossen.}
{200}{}{[Erledigt]}
{201}{}{Physikdatenbank: Forschung - Theorie}
{202}{}{Erkundung.}
{203}{}{Theorie.}
{204}{}{Zurück.}
{205}{}{"Durch die vor kurzem erworbenen Vertibird-Pläne sind wir der Möglichkeit, eine in der Praxis anwendbare Flugmaschine zu bauen, einen Quantensprung näher gekommen. Wir hoffen, bis zum Jahresende einen flugfähigen Prototypen fertigzustellen und innerhalb der nächsten zwei Jahre mit der Massenproduktion starten zu können." - Dr. Wong}
{206}{}{[Kopiere Pläne] Zurück.}
{207}{}{Zurück.}
{208}{}{"Wir arbeiten noch an dem funktionsfähigen Modell einer Flugmaschine. Keiner der bisherigen Entwürfe konnte in Bezug auf Sicherheit oder Aerodynamik überzeugen. Vielleicht wenn wir Zugriff auf die Pläne der Alten Welt hätten..." - Dr. Wong }
{209}{}{Zurück.}
{210}{}{(Nachdem du dich durch die Einleitung und die mathematischen Berechnungen gequält hast, entdeckst du, dass die Shi wieder lernen, Atomenergie zu entwickeln, indem sie die Raumflugtheorien der Alten Welt rekonstruieren - wobei sie die Hubologen belächeln. Neben Sonnenenergie nutzen sie auch Wind- und Wasserkraft, zumindest steht es so in den Aufzeichnungen.)}
{211}{}{Zurück.}
{212}{}{Station aktiviert.}
{213}{}{Zurück.}
{214}{}{Das Computerterminal scheint kein Interface dafür zu haben.}
{215}{}{Das Computerterminal scheint nicht betriebsbereit zu sein.}
{216}{}{Es gab einen Fehler im System. Befehl zum Angriff erteilt!}
{217}{}{Greift den Eindringling an!}
{218}{}{Jetzt wirst du für Deine Taten bezahlen, Lao Wai!}
{219}{}{Unter uns ist ein Verräter!}
{220}{}{Geo-Lokalisierung.}
{221}{}{Was möchtest du lokalisieren?}
{222}{}{Die Dorfbewohner aus meiner Heimat.}
{223}{}{Wahrscheinlichkeit insgesamt: 97%. Bewohner bei den Koordinaten des Enklavengeländes lokalisiert.}
