{100}{}{Du siehst einen freundlich wirkenden, leicht gebeugten, Mann.}
{101}{}{Du siehst Chad von der Karawane.}
{102}{}{Du siehst einen leicht gebeugten Mann, der sein Lächeln wie einen Schild trägt. Er trägt
 unauffällige Kleidung und wirkt, als wisse er, was er tut.}
{120}{}{Hallo da! Was kann ich für dich tun?}
{121}{}{Noch mehr Fragen? Mal sehen, was ich dir für Antworten geben kann.}
{122}{}{Dierk diegler!}
{123}{}{Du wer?}
{124}{}{Marcus hat ein paar Fragen über dich gestellt.}
{125}{}{There's enough evidence that you've been stealing money that's supposed to go to Broken Hills
 that you can be arrested. You're going down.}
{126}{}{There's enough evidence that you've been stealing money that's supposed to go to Broken Hills
 that you can be arrested. Cut me in for $1000 and I'll make sure you can flee town.}
{127}{}{Wer bist du?}
{128}{}{Erzähl mir was über diesen Ort.}
{129}{}{Nichts. Tschüß.}
{130}{}{Was das Ödland so alles hierherweht! Tut mir leid Kumpel, ich kann dir auch nicht helfen.}
{131}{}{Schüssi!}
{132}{}{Ich heiße Chad. }
{133}{}{Ich hab leider sehr viel zu tun. Such dir jemand anderen, und geh dem auf die Nerven.}
{134}{}{I'm the caravan master for the city. I take care of the business on the other end of the trade
 routes. These days I'm focusing primarily on Gecko. }
{135}{}{OK!}
{136}{}{Ich würde gern für dich arbeiten.}
{137}{}{Hört sich interessant an.}
{138}{}{Das hört sich aber langweilig an.}
{139}{}{Ich habe noch weitere Fragen.}
{140}{}{Danke. Tschüß.}
{141}{}{Tell you about Broken Hills? Well... I moved here a few years back. Got a job with the Bill --
 that's the Outfitter -- and moved up to where I am now. I report to Marcus and the Bill, but I'm
 responsible for the livelihood of the town.}
{142}{}{Ich habe noch weitere Fragen.}
{143}{}{Tschüß.}
{144}{}{Wie zum Beispiel?}
{145}{}{He suspects, that you are skimming the money that's supposed to go Broken Hills.}
{146}{}{Nicht wirklich, Tschüß.}
{147}{}{Look, I don't like people to accuse me about something that I don't know anything about. I suggest that you leave.}
{150}{}{I'm going to find the truth. Bye.}
{156}{}{Red mal mit Bill. Der wird dir helfen.}
{157}{}{Ich habe noch weitere Fragen.}
{158}{}{Danke. Tschüß.}
{159}{}{Ja stimmt. Hört sich zwar nicht so an, aber ich reise herum und sehe was von der Welt...
 und ich kann was zum Wohlergehen der Stadt beitragen. Mir geht's schon ganz gut.}
{160}{}{Hört sich ja toll an. So einen Job hätte ich auch gern.}
{161}{}{Das klingt ja todlangweilig.}
{162}{}{Ich habe noch weitere Fragen.}
{163}{}{Tschüß.}
{164}{}{Bestimmt aufregender, als was du Versager mit deinem Leben machst!}
{165}{}{Ja, kann schon sein. Ich habe noch ein paar Fragen.}
{166}{}{Ha ha ha ha! Aber sicher. Bis dann, du Verlierer.}
{167}{}{Dafür wirst du eines Tages büßen, du Nichts.}
{168}{}{Geh mir aus den Augen, du Schwachkopf.}
{169}{}{Das mit der Karawane hast du ganz schön versaut, Freundchen. Soviel zu deiner Bezahlung.}
{170}{}{Die Karawane hast du ganz schön vermasselt. Viel Glück, wenn du versuchen solltest,
 jemals wieder eine aus Broken Hills zu kriegen.}
{171}{}{Gute Arbeit während der Karawane. Hier sind deine $200.}
{172}{}{Raus hier. Deine Hilfe wird nicht mehr benötigt.}
{173}{}{Halt bloß die Augen auf.}
{174}{}{Ich deck dir den Rücken.}
{175}{}{Paß auf, daß dich keiner von hinten drankriegt.}
