{100}{}{Du siehst einen freundlich wirkenden, leicht gebeugten, Mann.}
{101}{}{Du siehst Chad von der Karawane.}
{102}{}{Du siehst einen leicht gebeugten Mann, der sein Lächeln wie einen Schild trägt. Er trägt
 unauffällige Kleidung und wirkt, als wisse er, was er tut.}
{120}{}{Hallo da! Was kann ich für dich tun?}
{121}{}{Noch mehr Fragen? Mal sehen, was ich dir für Antworten geben kann.}
{122}{}{Dierk diegler!}
{123}{}{Du wer?}
{124}{}{Marcus hat ein paar Fragen über dich gestellt.}
{125}{}{Es gibt genug Beweise, um dich dafür festzunehmen, dass du Geld, das für Broken Hills
 bestimmt war, gestohlen hast. Du bist verloren.}
{126}{}{Es gibt genug Beweise, um dich dafür festzunehmen, dass du Geld, das für Broken Hills
 bestimmt war, gestohlen hast. Gib mir $1000, dann sorg ich dafür, dass du
 abhauen kannst.}
{127}{}{Wer bist du?}
{128}{}{Erzähl mir was über diesen Ort.}
{129}{}{Nichts. Tschüss.}
{130}{}{Was das Ödland so alles hierherweht! Tut mir leid Kumpel, ich kann dir auch nicht helfen.}
{131}{}{Schüssi!}
{132}{}{Ich heiße Chad. }
{133}{}{Ich hab leider sehr viel zu tun. Such dir jemand anderen, und geh dem auf die Nerven.}
{134}{}{Ich bin der Karawanenmeister der Stadt. Ich kümmere mich um die Geschäfte am anderen Ende
 der Handelswege, in letzter Zeit hauptsächlich um Gecko. }
{135}{}{OK!}
{136}{}{Ich würde gern für dich arbeiten.}
{137}{}{Hört sich interessant an.}
{138}{}{Das hört sich aber langweilig an.}
{139}{}{Ich habe noch weitere Fragen.}
{140}{}{Danke. Tschüss.}
{141}{}{Dir was über Broken Hills erzählen? Tja... ich bin vor ein paar Jahren hierhergezogen.
 Hab eine Stelle bei Bill bekommen, das ist unser Ausstatter hier. Hab mich dann bis hierhin
 hochgearbeitet. Ich unterstehe Marcus und Bill, aber ich bin für das Wohlergehen der Stadt
 verantwortlich.}
{142}{}{Ich habe noch weitere Fragen.}
{143}{}{Tschüss.}
{144}{}{Wie zum Beispiel?}
{145}{}{Er verdächtigt dich, dass du Geld abzweigst, das für Broken Hills bestimmt ist.}
{146}{}{Nicht wirklich, Tschüss.}
{147}{}{Hör mal, ich mag es nicht, wenn man mich wegen etwas beschuldigt, von dem ich nichts weiß. Du gehst besser.}
{150}{}{Ich krieg die Wahrheit schon noch raus, Tschüss.}
{156}{}{Red mal mit Bill. Der wird dir helfen.}
{157}{}{Ich habe noch weitere Fragen.}
{158}{}{Danke. Tschüss.}
{159}{}{Ja stimmt. Hört sich zwar nicht so an, aber ich reise herum und sehe was von der Welt...
 und ich kann was zum Wohlergehen der Stadt beitragen. Mir geht's schon ganz gut.}
{160}{}{Hört sich ja toll an. So einen Job hätte ich auch gern.}
{161}{}{Das klingt ja todlangweilig.}
{162}{}{Ich habe noch weitere Fragen.}
{163}{}{Tschüss.}
{164}{}{Bestimmt aufregender, als was du Versager mit deinem Leben machst!}
{165}{}{Ja, kann schon sein. Ich habe noch ein paar Fragen.}
{166}{}{Ha ha ha ha! Aber sicher. Bis dann, du Verlierer.}
{167}{}{Dafür wirst du eines Tages büßen, du Nichts.}
{168}{}{Geh mir aus den Augen, du Schwachkopf.}
{169}{}{Das mit der Karawane hast du ganz schön versaut, Freundchen. Soviel zu deiner Bezahlung.}
{170}{}{Die Karawane hast du ganz schön vermasselt. Viel Glück, wenn du versuchen solltest,
 jemals wieder eine aus Broken Hills zu kriegen.}
{171}{}{Gute Arbeit während der Karawane. Hier sind deine $200.}
{172}{}{Raus hier. Deine Hilfe wird nicht mehr benötigt.}
{173}{}{Halt bloß die Augen auf.}
{174}{}{Ich deck dir den Rücken.}
{175}{}{Pass auf, dass dich keiner von hinten drankriegt.}
