{100}{}{Du siehst eine gelangweilte Gestalt in einer Lederrüstung.}
{101}{}{Du siehst Max, den Karawanenwächter.}
{102}{}{Du siehst eine staubige, gelangweilte Gestalt in einer Lederrüstung. Dem Brahmin-Gestank
 und dem selbstbewußten Gang nach ist es eindeutig ein Karawanenwächter.}
{103}{}{Kann ich dir irgendwie helfen?}
{104}{}{Är?}
{105}{}{Hier arbeiten!}
{106}{}{Wer sind Sie?}
{107}{}{Was kannst du mir über Chad erzählen?}
{108}{}{Ich hab leider keine Zeit für Idioten. Tut mir leid, aber du mußt dir jemand anderen zum
 Spielen suchen.}
{109}{}{::schnüff::}
{110}{}{Ich heiße Max. Ich bin ein Karawanenwächter.}
{111}{}{Was kannst du mir über Chad erzählen?}
{112}{}{Danke. Tschüß.}
{113}{}{Ich mag ihn nicht besonders. Er scheint immer extra Geld aus seinen Karawanenjobs zu bekommen. Das ist wirklich unfair.}
{114}{}{Well, Marcus suspects that he is skimming some of the money that supposed to go Broken Hills.}
{115}{}{Danke. Tschüß.}
{116}{}{Thanks. I'm sure glad that this is over. You better watch your back thought.}
{117}{}{Tschüß.}
{118}{}{Der Feind! Stirb!}
{119}{}{Hoppla.}
{120}{}{(Senkt seine Stimme und schaut sich um) Das muss es sein. Ich habe selbst einmal gesehen, dass er einen "Teil" des Geldes, das er von der Uranlieferung von Gecko bekommen hat, mitgenommen hat.}
{121}{}{Really? Then why you haven't tell about it to Marcus then?}
{122}{}{Bist du verrückt? Wenn ich es erzähle, werden mich viele Leute in dieser Stadt nicht einmal mehr anschauen.
Außerdem könnte sich jemand rächen wollen.}
{123}{}{Hmm, I could tell it about to Marcus, cause I don't plan to stay here too long anyway.}
{124}{}{Ok. Do what you want, but don't tell anything about me. And we never had this conversation, ok?}
{125}{}{Don't worry, I don't want to get you in any trouble, bye.}
