{100}{}{Du siehst eine gelangweilte Gestalt in einer Lederrüstung.}
{101}{}{Du siehst Max, den Karawanenwächter.}
{102}{}{Du siehst eine staubige, gelangweilte Gestalt in einer Lederrüstung. Dem Brahmin-Gestank
 und dem selbstbewussten Gang nach ist es eindeutig ein Karawanenwächter.}
{103}{}{Kann ich dir irgendwie helfen?}
{104}{}{Är?}
{105}{}{Hier arbeiten!}
{106}{}{Wer bist du?}
{107}{}{Was kannst du mir über Chad erzählen?}
{108}{}{Ich hab leider keine Zeit für Idioten. Tut mir leid, aber du musst dir jemand anderen zum
 Spielen suchen.}
{109}{}{::schnüff::}
{110}{}{Ich heiße Max. Ich bin ein Karawanenwächter.}
{111}{}{Was kannst du mir über Chad erzählen?}
{112}{}{Danke. Tschüss.}
{113}{}{Ich mag ihn nicht besonders. Er scheint immer extra Geld aus seinen Karawanenjobs zu bekommen. Das ist wirklich unfair.}
{114}{}{Nun, Marcus vermutet, dass er etwas von dem Geld abzweigt, das nach Broken Hills gehen sollte.}
{115}{}{Danke. Tschüss.}
{116}{}{Danke. Ich bin froh, dass das endlich ein Ende hat. Du solltest allerdings auf der Hut sein.}
{117}{}{Tschüss.}
{118}{}{Der Feind! Stirb!}
{119}{}{Hoppla.}
{120}{}{(Senkt seine Stimme und schaut sich um) Das muss es sein. Ich habe selbst einmal gesehen, dass er einen "Teil" des Geldes, das er von der Uranlieferung von Gecko bekommen hat, mitgenommen hat.}
{121}{}{Wirklich? Warum hast du das Marcus dann noch nicht berichtet?}
{122}{}{Bist du verrückt? Wenn ich es erzähle, werden mich viele Leute in dieser Stadt nicht einmal mehr anschauen.
 Außerdem könnte sich jemand rächen wollen.}
{123}{}{Hmm, dann könnte ich vielleicht Marcus davon erzählen, hab eh nicht vor noch länger hier zu bleiben.}
{124}{}{He, du musst tun was du tun musst, aber zieh mich einfach nicht mit hinein. Dieses Gespräch hat nie stattgefunden, verstanden?}
{125}{}{Keine Sorge, ich will dir keinen Ärger machen. Tschüss.}
