{100}{}{Du siehst eine Person die eine mächtige Waffe führt.}
{101}{}{Du siehst ein Mitglied des Broken Hills Handels– und Sicherheitskorps.}
{102}{}{Du siehst eine Person die eine mächtige Waffe führt und vom Schmutz der Reise bedeckt ist.}
{103}{}{Ich sags dir, noch ne Gruppe Wegelagerer und ich nehm für die nächste Reise Dynamit mit.}
{104}{}{'türlich können wir bei den Karawanen etwas mehr Hilfe gebrauchen.}
{105}{}{Mann... die Arbeit bei der Einheits-Patrouille macht einen echt alt.}
{106}{}{Dann sah ich diesen Sippling kommen und... Öh, vergesst es.}
{107}{}{Noch mal so ne "Regenbogenpatrouille" und ich knall einen ab.}
{108}{}{Ich schwör dir, wenn diese Banditen noch etwas schlimmer werden, werden wir alle im nächsten Jahr sterben.}
{109}{}{Aus welchem Rattennest kommst du her?}
{110}{}{Willste nem arbeitendem Menschen nen Drink ausgeben?}
{111}{}{Ich bin von der Karawane zu müde um mit dir zu Reden.}
{112}{}{Wenn du was brauchst, rede mit Bill, dem Händler.}
{113}{}{Man sollte nach all dieser Zeit, in der versucht wurde das Ödland zu zivilisieren, meinen, wir wären einen Schritt weiter.}
{114}{}{Ich bin diese Mensch/Mutanten-Streitereien satt. Sollen wir nicht ein Vorbild darstellen?}
{115}{}{Was willste? Siehst du nicht dass ich mich ausruhe??}
{116}{}{Wann fährt die nächste Karawane los?}
{117}{}{Patrouille, Patrouille, Patrouille... Was anderes mach ich hier nicht.}
{118}{}{Ich glaub ich brauch ne Pause.}
{119}{}{Ich verdiene eine Gehaltserhöhung. Der Job ist gefährlich.}
