{100}{}{Du siehst eine kräftige alte Frau mit einem müden Lächeln.}
{101}{}{Du siehst Ardin Buckner, die Inhaberin des Buckner-Hauses.}
{102}{}{Du siehst eine sehr rüstige und muntere Frau Anfang 50.}
{110}{}{Du hast meinen Smiley gefunden - ich danke dir vielmals. Ich glaubte schon, er sei tot. Ich bin so wütend auf ihn. Jetzt, da er zurück ist, werden wir Sulik wohl nicht mehr brauchen.}
{111}{}{Gecko hat Smiley gebissen. Smiley Aua.}
{112}{}{Freut mich, daß ich helfen konnte. Und daß Sulik gehen darf.}
{113}{}{Ich glaube, er mag dich trotzdem lieber als die Geckos. Aber erzähl mir doch was anderes.}
{114}{}{Na, sei nicht zu streng mit ihn. Er hat sich ja auch nicht gerade amüsiert. Wiedersehn.}
{120}{}{Ich hab gehört, du hast meinen Jungen Torr verletzt. Ich weiß nicht genau, was passiert ist, aber ich will dich hier nicht mehr sehen. Verschwinde.}
{130}{}{Hallo. Mein Name ist Ardin Buckner und das ist das Buckner-Haus.}
{131}{}{Argl. Guhp}
{132}{}{Schönes Haus.}
{140}{}{Du erinnerst mich an meinen Jungen Torr. Ich wette, ihr beiden würdet euch prima verstehen. Warum gehst du nicht zu ihm und redest mit ihm? Tschüß.}
{150}{}{Hallo. Mein Name ist Ardin Buckner und dieser Laden gehört mir. Du hast nicht zufällig einen Fallensteller namens Smiley außerhalb der Stadt gesehen? (Halb zu sich) Er ist schon zu lange weg. Ich hätte dieser idiotischen Suche niemals zustimmen dürfen.}
{151}{}{Smiley? Nein, ich hab keinen Fallensteller getroffen, der so heißt. Erzähl mir von ihm.}
{152}{}{Im Moment brauch ich was anderes.}
{153}{}{Hallo Ardin. Ich glaub, ich muß jetzt weiter. Wiedersehn.}
{160}{}{Darüber solltest du mit meiner Tochter Maida sprechen. Ich bin nicht gerade auf dem neuesten Stand. Es reicht schon, daß ich mich um mein Geschäft kümmern muß.}
{161}{}{Oh, OK, das werde ich tun. Im Moment brauch ich allerdings andere Informationen.}
{162}{}{Dann werd ich mit ihr darüber sprechen. Wiedersehn.}
{170}{}{Ich rate dir, hier keine Dummheiten zu machen. Was willst du?}
{171}{}{Wie kann ich dir helfen, mein Freund?}
{172}{}{Erzähl mir von Smiley, dem Fallensteller.}
{173}{}{Ich hab mich gefragt, ob du Bescheid weißt, was es Neues in der Stadt gibt?}
{174}{}{Ich möchte ein Zimmer mieten.}
{175}{}{Wir möchten ein Zimmer mieten.}
{176}{}{Ich möchte etwas kaufen.}
{177}{}{Im Moment brauche ich wohl nichts mehr. Wiedersehen.}
{180}{}{Naja, Smiley und ich haben es wirklich ernst gemeint. Ich dachte, ich hätt ihn endlich doch überzeugt, sich hier niederzulassen und mir bei meinen Geschäften zu helfen. Aber er sagte, er müsse sich ein letztes Mal auf die Suche machen.}
{181}{}{Die Suche?}
{190}{}{Ich bin hier nur für die Zimmer zuständig. Wenn du etwas kaufen oder eintauschen willst, sprich mit meiner Tochter Maida.}
{191}{}{Ah, verstehe. Dann erzähl mir was anderes.}
{192}{}{Vielen Dank. Auf Wiedersehn.}
{200}{}{Wir sind im Augenblick ziemlich ausgebucht. Tut mir leid.}
{201}{}{Hmm, laß mal sehen. Wir haben ein Zimmer frei. Kostet $25.}
{202}{}{Ich nehme es. Hier sind $25. Vielen Dank.}
{203}{}{Ich glaube, das will ich jetzt nicht. Ich möchte dich was anderes fragen.}
{204}{}{Ich glaub, ich brauche das Zimmer doch nicht. Wiedersehn.}
{210}{}{Tut mir leid, aber dafür reicht dein Geld wohl nicht aus.}
{211}{}{Ups. Ich glaube, ich bin gerade etwas knapp bei Kasse. Ich möchte dich noch was fragen.}
{212}{}{Tut mir leid. Ich geh wohl besser und besorge noch was. Wiedersehn.}
{220}{}{Danke. Ich bin so glücklich, daß du meinen Jungen gefunden hast. Ich dachte schon, ich würde diesen Verrückten nie mehr wieder sehen.}
{221}{}{Torr Freund.}
{222}{}{Freut mich, daß ich helfen konnte.}
{223}{}{War da nicht von einer Belohnung die Rede?}
{230}{}{Naja, vielen Dank. Du brauchst vielleicht jemanden, der etwas cleverer ist und auf dich aufpassen kann, einen Wegbegleiter. Ich werde Maida fragen, ob sie Sulik gehen läßt.}
{231}{}{Ich weiß nicht, wie wir dir jemals danken sollen.}
{232}{}{Torr Freund}
{233}{}{Ihr müßt mir nicht danken. Es war Hilfe nötig, und ich war gerade zur Stelle.}
{234}{}{Ich würde sagen, Geld ist ein geeignetes Mittel, Dank auszudrücken.}
{235}{}{Wenn du Sulik seine Schulden erlassen würdest, wäre das schon Belohnung genug.}
{236}{}{. Sulik Freund?}
{240}{}{Ich werde mit Maida reden, sie wird das mit Sulik regeln. Vielleicht solltest du aber auch mit ihr reden.}
{241}{}{Maida befreien Sulik. Maida}
{242}{}{Danke. Ich bin sicher, Sulik wird dir für die Erlassung seiner Schulden dankbar sein. Ich rede sofort mit Maida. Wiedersehn.}
{243}{}{Freut mich, daß du Sulik nicht mehr brauchst. Ich möchte dich was fragen.}
{244}{}{ Freund.}
{250}{}{Ich hab nicht viel, aber hier sind $100. Ich wünschte, es wäre mehr, aber wegen all der Brahmin, die wir verloren haben, können wir uns nicht mehr leisten. Tut mir leid.}
{251}{}{Danke Mrs. Buckner. Auf Wiedersehen.}
{252}{}{Vielleicht sollte ich eine andere Belohnung nehmen.}
{260}{}{Es muß doch etwas geben, mit dem ich dir zeigen kann, wie dankbar ich dir bin. Ich werde Sulik seine Schulden erlassen. Er ist frei. Wahrscheinlich sind doch nicht alle Wilden Unruhestifter.}
{261}{}{Hört sich gut an. Tschüß.}
{262}{}{Hmm, vielleicht sollte ich eine andere Belohnung nehmen.}
{270}{}{Ich weiß einfach nicht, was ich glauben soll. Mein Junge, Torr, ist verschwunden. Ich wünschte, mir würde jemand helfen, ihn zu finden. Er war noch nie so lange von zu Hause weg.}
{271}{}{Torr?}
{272}{}{Was ist passiert?}
{273}{}{Das ist nett, aber ich hätte da ein Anliegen.}
{274}{}{Ich sehe, du bist beschäftigt. Ich komme später wieder. Tschüß.}
{280}{}{Er ist letzte Nacht verschwunden. Ich bin ausgerastet, nachdem wir diese letzten paar Brahmin verloren haben. Wir können es uns einfach nicht leisten, weitere zu verlieren. Und er redete von nichts anderem als von den Wanzenmännern, die sie mitgenommen haben. Dieser dumme Junge.}
{281}{}{Torr gehen?}
{282}{}{Ich glaube, daß die Duntons etwas mit den verschwundenen Brahmin zu tun haben. Du solltest deswegen nicht zu streng mit Torr sein. Wo glaubst du, ist er hingegangen?}
{283}{}{Wo glaubst du, ist er hingegangen?}
{290}{}{Er hat immer gesagt, daß er die Wanzenmänner kriegen möchte, wo sie wohnen. Östlich des Feldes, wo die Brahmin immer grasen, ist ein Canyon. In letzter Zeit konnte man von dort immer komische Geräusche hören. }
{291}{}{Geräusche?}
{300}{}{Danke, daß du nach meinem Jungen suchen wirst. Ich hoffe wirklich, daß du ihn findest. Ich mach mir solche Sorgen um ihn. Beeil dich, bitte.}
{301}{}{OK.}
{310}{}{Hast du meinen Jungen schon gefunden? Ich weiß nicht, wie lang er dort draußen alleine überleben kann. Bitte finde ihn.}
{311}{}{Torr?}
{312}{}{Ich habe noch nicht aufgegeben. Aber zuerst brauche ich etwas.}
{313}{}{Ich wollte nur nachsehen, ob er schon zurück gekommen ist. Ich werde weitersuchen. Wiedersehn.}
{320}{}{Torr war sich sicher, daß die Wanzenmänner, die unsere Brahmin stehlen, von dort kommen. Sagte was davon, daß er es uns beweisen werde. Ich wünschte, jemand würde mir meinen Jungen zurückbringen.}
{321}{}{Torr Canyon.}
{322}{}{Nicht gehen Torr.}
{323}{}{Hört sich an, als ob dieser Canyon ein guter Platz wäre, mit der Suche zu beginnen. Ich werde nach dem Jungen suchen, Mrs. Buckner.}
{324}{}{Ich würde gerne helfen - wenn ich nicht so beschäftigt wäre. Ich bin mir sicher, Torr kommt gut alleine zurecht. Tschüß.}
{325}{}{ Torr gehen.}
{330}{}{Naja, er nannte es eine Suche. Er sagte, er wisse, wo all die goldenen Geckos herkämen und wolle sichergehen. Er meinte, es sei eine Art magische Quelle oder so was wie eine verborgene Höhle oder eine Vault.}
{331}{}{Hmmm.}
{340}{}{Ich weiß nicht mehr genau, was er alles gesagt hat, aber er konnte es kaum erwarten zu gehen. Ich hätte ihn nicht gehen lassen sollen. Er ist schon zwei Wochen länger weg als geplant. Ich mach mir wirklich Sorgen.}
{341}{}{Ich würde gern helfen. Ich könnte nach ihm suchen.}
{342}{}{Das tut mir leid. Kann ich noch eine Frage stellen?}
{343}{}{That's too bad, Mrs. Buckner. Maybe he just ran out on you. I think I know why he would, too.
 Goodbye.}
{350}{}{Oh, vielen Dank. Ich werde auf der Karte markieren, wo er suchen wollte. Ich hoffe wirklich, daß du ihn findest. Er ist niemand besonderes, aber ich liebe ihn immer noch und vermisse ihn mehr, als ich es für möglich gehalten hätte. Bitte finde ihn.}
{351}{}{Ich werde tun, was ich kann. Ich habe allerdings noch eine Frage.}
{352}{}{I'll do my best, Mrs. Buckner. Goodbye.}
{353}{}{Ich glaube nicht, daß ich dir jetzt helfen kann. Wiedersehn.}
{360}{}{Hast du meinen Smiley gefunden?}
{361}{}{Tut mir leid, Mrs. Buckner. Ich suche immer noch nach ihm. Ich würde allerdings zuerst gerne noch was fragen.}
{362}{}{Nein, ich werde mich jedoch auf die Suche nach ihm machen. Auf Wiedersehen.}
{370}{}{Ich glaube, meinem armen Torr ist etwas Schreckliches zugestoßen ist. Ich hatte so gehofft (schluchz), du würdest ihn finden, bevor es zu spät ist. Dieser arme, hilflose Junge. Ich kann einfach nicht glauben, daß ich mich auf dich verlassen habe.}
{371}{}{Ich wünschte, du hättest bei der Suche nach meinem armen kleinen Torr helfen können. Er war so eine gute Seele und jetzt ist er sicher tot. Ich vermisse ihn so.}
{372}{}{Tut mir leid, Mrs. Buckner. Ich habe mein Bestes gegeben, ihn zu finden. Äh, ich hätte da allerdings noch ein Anliegen.}
{373}{}{Vielleicht kann ich finden, was noch von ihm übriggeblieben ist. Auf Wiedersehen.}
{374}{}{Torr? Wer Torr? (Du zuckst mit den Schultern) Tschüß.}
{375}{}{Tut mir leid, ich wollte wirklich helfen, aber ich konnte nicht. Äh, ich hasse es, jetzt davon zu sprechen, aber ich hätte da noch ein Anliegen.}
{376}{}{Ich glaub, ich sollte ein anderes Mal wiederkommen. Auf Wiedersehen.}
{380}{}{Ich muß sagen, irgendwie überrascht mich das nicht. Mein Gott, ich hab meinen armen Jungen angeschrien, obwohl es nicht mal seine Schuld war. (Schluchz) Ich werde diese Duntons kriegen. Diesmal sind sie zu weit gegangen.}
{381}{}{Das tut mir leid. Wo, glaubst du, ist Torr hingegangen?}
{390}{}{OK.}
{400}{}{What? My Smiley is...}
{401}{}{Who? Did I say Smiley? Oh, uh, no. I don't know where he went. Uh, say, let me ask you about something else.}
{402}{}{Yes, he's dead. He was eaten by geckos.}
{403}{}{I was just joking. I, uh, saw him. He said he was running off with another woman. Whoa! Look at the time. I've gotta run.}
{404}{}{Äh, ich, äh, das heißt... Äh, nein. Ich bin immer noch am Suchen. Aber ich bin sicher, daß er in den nächsten Tagen auftauchen wird. Äh, auf Wiedersehen.}
{410}{}{Eaten by geckos? I just don't believe you. Geckos would never catch my Smiley, he's too good a trapper for that. You must be mistaken.}
{411}{}{Ja, vielleicht hast du recht. Tut mir leid, wenn ich dich erschreckt habe. Aber ich hätte da 'ne Frage an dich.}
{412}{}{Nee. Ich hab ihn gesehen. Oder jedenfalls das, was noch von ihm übrig war. War kein schöner Anblick. Naja, bis demnächst. Tschüß.}
{413}{}{Erwischt! Hä, ha, wollte dich nur auf 'n Arm nehmen. Ja, das war's. Mach's mal gut.}
{500}{}{Ich glaube die Dunton Brüder stehlen deine Brahmin. Ich dachte du solltest das Wissen.}
{510}{}{Du hast nicht zufällig einen Fallensteller namens Smiley außerhalb der Stadt gesehen? (halb zu sich selbst) Er ist schon viel zu lange weg. Hätt ihn nie auf diese hirnrissige Suche gehen lassen sollen.}
{520}{}{Du bist mir echt 'ne Riesenhilfe gewesen. Danke.}
{530}{}{Ich frage mich, was hier in der Gegend sonst noch so passiert.}
{600}{}{Du bist einfach Klasse.}
{610}{}{Du bist einfach Klasse. Du hast mir meinen Sohn Torr und meinen Smiley zurückgebracht. Wie kann ich dir bloß danken?}
{620}{}{Du hast meinen Sohn Torr gefunden. Vielen, vielen Dank.}
{630}{}{Du hast also meinen Smiley gefunden. Danke. Vielen, vielen Dank.}
{640}{}{Bin froh, dir helfen zu können. Wär doch 'ne Schande gewesen, wenn du zwei Menschen verloren hättest, an denen dir soviel liegt.}
{650}{}{Torr braucht ab und zu mal 'n bißchen Hilfe. Bin froh, daß ich ihm helfen konnte.}
{660}{}{Diesmal hat Smiley Glück gehabt. Sag ihm, das nächste mal soll er vorsichtiger sein.}
{670}{}{Bin froh, wenn ich helfen kann, Mrs. Buckner. Aber ich hätte da noch 'ne Frage.}
{680}{}{Gurrgel blubb?}
{690}{}{Aber bitte - keine Ursache, Madame. Auf Wiedersehen.}
{700}{}{Torr ist tot.}
{710}{}{Smiley's dead.}
{720}{}{Ich, äh, ich weiß nicht, wo sie sind. Hör mal, darf ich dir 'ne Frage stellen?}
{730}{}{Sind beide mausetot.}
{740}{}{Torr ist weg? Was meinst du damit?}
{750}{}{Ich weiß nicht, wo er ist. Darf ich dich mal was fragen? Vielleicht kommen sie ja wieder, während wir uns unterhalten.}
{760}{}{Ich suche sie immer noch. Ich mach mich besser wieder auf die Suche. Auf Wiedersehen.}
{770}{}{Ich suche ihn immer noch. Ich mach mich besser wieder auf die Suche. Auf Wiedersehen.}
{780}{}{Ich...äh...weiß nicht, wo er ist. Hmm. Herrjeh, ist es schon so spät? Ich muß gehn.}
{790}{}{Hör mal, dürfte ich dir noch 'ne Frage stellen?}
{800}{}{Es wartet eine ganze Menge Arbeit auf mich. Tschüß.}
{810}{}{Aha.}
{900}{}{Hast du meinen Sohn Torr gefunden? Ich mach mir solche Sorgen um ihn.}
{910}{}{Hast du meinen Smiley gefunden?}
{920}{}{Hast du meinen Sohn Torr oder meinen Freund Smiley, den Fallensteller, schon gefunden?}
{930}{}{Mein armer Torr ist abgehauen.}
{940}{}{Das glaub ich nicht.}
{942}{}{Ist aber wahr. Die werden wahrscheinlich inzwischen von den Würmern gefressen - naja, die paar Schnipsel, die sich nicht sowieso schon längst in Geckokacke verwandelt haben. Tja, hatten eben Pech. Mach's gut.}
{943}{}{Äh, war wohl 'n schlechter *Scherz*, 'tschuldigung.}
{950}{}{Will mit dir nicht reden.}
{951}{}{Verschwinde.}
{952}{}{Verdammte Sippenleute. Nichts als Ärger.}
{953}{}{Verschwinde, du Barbar.}
{954}{}{Leute wie dich will ich hier nicht sehen.}
{955}{}{Von mir kriegst du sowieso nichts, Sippenheini.}
{956}{}{Hast hier schon genügend Schaden angerichtet.}
{957}{}{Laß mich einfach in Ruhe.}
{958}{}{Sippen-Stänkerer, hau ab.}
{959}{}{Hab genug von dir. Mach' daß du wegkommst!}
