{100}{}{Du siehst "drei Karten" Monte.}
{150}{}{Du siehst einen spindeldürren Mann, mit sonnenverbranntem Gesicht. Er ist so dünn, seine Arme erinnern dich an Zweige.}
{200}{}{Ich weiß gar nicht, warum ich verloren hab...}
{205}{}{Heeeey! Du bist ein Held! Du bist in Ordnung.}
{215}{}{Wo zum Teufel sind meine Karten? Ich hatte sie doch gerade noch.}
{220}{}{Yo, Kumpel, mach dir keine Scherereien mit dem Kasino. Komm und spiel mit Monte.}
{230}{}{Monte hat heute nicht offen mein Freund; meine verdammten Karten sind weg.}
{231}{}{(Der alte Mann lächelt, dabei bilden sich Falten um seine Augen.) Lust auf ein Spiel, Freund?}
{250}{}{Mit was loslegen? Dem Spiel natürlich!}
{260}{}{(Du gibst das Geld rüber. Monte nickt, zeigt dir die Karten, dann legt er sie hin.)}
{280}{}{(Monte wendet die Karte. Es ist Pik Zwei.}
{300}{}{(Du gibst das Geld rüber. Monte nickt, zeigt dir die Karten, dann legt er sie hin. Gleichzeitig versteckt er eine Karte so schnell, dass du es kaum mitbekommst. Dann vertauscht er die Karten noch ne Weile.)}
{320}{}{WAS hast du gesagt, Kumpel?}
{330}{}{Pass auf, Ich hab keine Zeit für schlechte Verlierer. Du hast bezahlt, du hast deine Chance gehabt. Wenn du spielen willst, gut, wenn du aber rumzickst wenn du verlierst, verschwinde von hier!}
{340}{}{(Du gibst das Geld rüber. Monte nickt, zeigt dir die Karten, dann legt er sie hin.)}
{360}{}{(Du gibst das Geld rüber. Monte nickt, zeigt dir die Karten, dann legt er sie hin.)}
{375}{}{(Monte dreht die Karte um. Es ist die Herz Dame. Er scheint vor Schreck wie gelähmt zu sein.) Was...? Hey. Äh...}
{385}{}{(Monte dreht die Karte um. Es ist die Herz Dame. Er sieht geschockt aus.) Oh...? Hey... äh...}
{400}{}{(Er schaut schmerzerfüllt.) Äh... gut, ich hab da etwas... aber es ist mehr Wert als du bis jetzt gewonnen hast...}
{405}{}{Oh... hmnnn... kommt darauf an was du wissen willst.}
{415}{}{Äh... gut... hör mal, du hast es nicht von mir, aber ich wette es war Renesco, das Arschloch, dass die Apotheke auf der West Side leitet.
 Ich bin mir nicht sicher ob er es an das Kind verkauft hat, aber er weiß etwas. Mehr sage ich aber nicht.}
{420}{}{Äh... gut... (Scheint als ob er einen inneren Kampf austrägt.) ...pass auf, du hast es nicht von mir gehört, aber wenn ich du wäre, würde ich im Keller vom Desperado suchen.}
{425}{}{(Er kneift die Augen zusammen.) Ich würde ol' Jules am Stadtrand fragen. Da passiert nichts ohne dass er's mitbekommt, und wenn doch, steckt er selber mit drin, verstehst du was ich damit sagen will?}
{430}{}{Gut... kennst du diesen Eldridge, der New Reno Arms betreibt? Er sagt er würde Waffen aufrüsten, aber ich hab ihn noch nie arbeiten gesehen. Könnte sich als wertvoll erweisen mal dort nachzuforschen... aber das hast du nicht von mir gehört.}
{435}{}{(Monte wirft dir einen finsteren Blick zu, als er dich sieht.) Pass auf. Ich mache heute keine Spiele, alles klar? }
{440}{}{Nein. Das kannst du vergessen. Basta. Sie ist ein ECHTES Vorkriegs-Erinnerungsstück... ein kleines Stück Geschichte. Keine Chance.}
{450}{}{Bist du Taub? Der Betrag ist nicht hoch genug um mein Interesse zu wecken.}
{460}{}{Gut, SO teuer ist sie mir auch nicht. Sie gehört dir Kumpel. (Er schaut nach links und rechts, dann bückt er sich und zieht seinen Stiefel aus. Er dreht den Absatz, öffnet ihn und holt die Spielkarte raus.) Hier ist sie. Pass darauf auf.}
{465}{}{(Er blickt finster.) Ob ich rede hängt davon ab was du wissen willst. Und es wird nicht billig.}
{475}{}{Auf keinen Fall, wenn ich dieses Thema auch nur ANSTREIFE werde ich in Golgotha landen. Hau ab.}
{490}{}{(Schüttelt seinen Kopf.) Keine Chance. Darüber zu sprechen könnte schon jemanden umbringen, und ich bin sicher der Erste, der daran glauben muss. Vergiss es.}
{495}{}{Äh... gut... das sind eine Menge Chips. (Leckt seine Lippen. Er sieht aus als ob er einen inneren Konflikt hätte... aber der Kampf ist schnell entschieden.) Pass auf, du hast es nicht von mir gehört...}
{500}{}{(Er wirft dir ein höhnisches Lächeln zu.) Vielleicht hab ich was gehört, vielleicht auch nicht. Sag einen Preis.}
{510}{}{Ha! Für den Preis kriegst du nicht mal einen Eimer Pisse. Vergiss es.}
{515}{}{Daaaas stimmt. (Grinst böse.) Das hast du nicht von mir, aber ich an deiner Stelle würde ich es mal im Keller des Desperado in der Virgin Street probieren. Da unten gibt es viele Ratten, wenn du verstehst was ich meine.}
{520}{}{(Zuckt mit den Achseln.) Vielleicht hab ich was gehört, vielleicht auch nicht. Sag mir den Preis und vielleicht kann ich dir dazu was sagen.}
{530}{}{(Er kneift die Augen zusammen.) Für den Preis weiß ich gar nichts.}
{535}{}{Das stimmt... (Er kneift die Augen zusammen.) ...ich würde ol' Jules am Stadtrand fragen. Da passiert nichts ohne dass er's mitbekommt, und wenn doch, steckt er selber mit drin, verstehst du was ich damit sagen will?}
{540}{}{(Er zuckt mit den Schultern.) Ich höre und sehe viel. Für eine kleine Spende von 200 Chips... du verstehst was ich meine?}
{550}{}{Bist du taub? ICH SAGTE 200 Chips, nicht weniger.}
{555}{}{Abgemacht. (Monte schaut sich um.) Gut... kennst du diesen Typen Eldridge, der New Reno Arms betreibt? Er sagt er würde Waffen aufrüsten, aber ich hab ihn noch nie arbeiten gesehen. Könnte sich als wertvoll erweisen mal dort nachzuforschen... aber das hast du nicht von mir gehört.}
{560}{}{Massengrab südlich der Stadt. Stinkt zu Himmel.}
{565}{}{Ich wette es war Renesco, das Arschloch, das die Apotheke auf der West Side leitet.
 Ich bin mir nicht sicher ob er es an das Kind verkauft hat, aber er weiß etwas. (Schaut sich um.) Mehr sage ich aber nicht.}
{570}{}{(Er schaut sich um, dann bückt er sich und zieht seinen Stiefel aus. Er dreht den Absatz ab und holt eine Karte raus... auf der Karte ist ein Mann mit einem komischen Hut zu sehen, der eine Keule schwingt.) Interessiert? Das ist ein echtes Vorkriegsandenken.}
