{100}{}{You see a card dealer.}
{101}{}{Du siehst "drei Karten" Monte.}
{150}{}{Du siehst einen spindeldürren Mann, mit sonnenverbranntem Gesicht. Er ist so dünn, seine Arme erinnern dich an Zweige.}
{151}{}{You see Three-Card Monte. He scopes out the street, spots you, and nods.}
{152}{}{You see Three-Card Monte. He scopes out the street, spots you, and nods.}
{200}{}{Ich weiß gar nicht, warum ich verloren hab...}
{201}{}{Just keep walking... Monte's not in business today.}
{202}{}{Did I palm the wrong card?}
{203}{}{How did that stupid tribal keep picking the right card?}
{205}{}{Heeeey! Du bist ein Held! Du bist in Ordnung.}
{206}{}{::Gibt dir einen Daumen-hoch-Zeichen::}
{207}{}{::Smiles, nods::}
{208}{}{You done good, hero. You done good.}
{215}{}{Wo zum Teufel sind meine Karten? Ich hatte sie doch gerade noch.}
{216}{}{Goddamn car key gnomes, now they're going after my playing cards.}
{220}{}{Yo, Kumpel, mach dir keine Scherereien mit dem Kasino. Komm und spiel mit Monte.}
{221}{}{Looking to take a chance, pal? Best odds in New Reno! C'mon...}
{222}{}{You, pal. You look like a lucky guy, c'mon over.}
{223}{}{Anybody looking to play? Free mon-ay, free mon-ay.}
{224}{}{C'mon over and play. Just the other day, I guy won 50 chips off me, easy.}
{225}{}{Easy, just guess the Queen, red Queen, and you win. That easy.}
{226}{}{You allergic to easy money? Then get over here.}
{227}{}{Everybody's winning today... you want to be the next one?}
{228}{}{Casinos'll rip you off, rob you blind... Monte treats you right, gives you a fair chance.}
{229}{}{Looking to take a chance, lady? Best odds in New Reno! C'mon...}
{230}{}{You allergic to easy money, lady? Then get over here.}
{231}{}{You, lady. You look like a lucky gal, c'mon over.}
{232}{}{Yo, lady, don't bother with the casinos. Come play with Monte.}
{233}{}{Monte hat heute nicht offen mein Freund; meine verdammten Karten sind weg.}
{234}{}{(Der alte Mann lächelt, dabei bilden sich Falten um seine Augen.) Lust auf ein Spiel, Freund?}
{235}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{236}{}{(The old man smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{237}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, friend?}
{238}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, lady?}
{239}{}{(Monte smiles, and the skin around his eyes crinkles.) Looking to play, hero?}
{240}{}{Three-Card Monte's the name, and the game's the same as the name. Slap down 20 chips, and we'll get down to it.}
{241}{}{You cheater. You no play fair}
{242}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{243}{}{Uh, me flattered but me not want to get down to it now... byyyyye}
{244}{}{Verzieh dich}
{245}{}{Let's play.}
{246}{}{Uh, get down to what?}
{247}{}{I'm familiar with the game. Let's play.}
{248}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{249}{}{Three-Card Monte, huh? You put three cards face down, shuffle them around, and I pick a card. If it's the right card - which it won't be, since you palmed it while shuffling - then I win. No thanks, pal.}
{250}{}{Nicht heute, danke.}
{251}{}{Mit was loslegen? Dem Spiel natürlich!}
{252}{}{See... (shows you three cards) ...one of these is a queen. I lay them face down, shuffle them, then you pick which one the queen is. If you're right, you win.}
{253}{}{That simple, pal.}
{254}{}{That simple, lady.}
{255}{}{I'm not playing with a cheater like you.}
{256}{}{Could you explain the rules again?}
{257}{}{Sounds simple enough. Let's play. Here's 20 chips.}
{258}{}{Nicht heute, danke.}
{260}{}{(Du gibst das Geld rüber. Monte nickt, zeigt dir die Karten, dann legt er sie hin.)}
{261}{}{So... which one's the queen, pal?}
{262}{}{So... which one's the queen, lady?}
{263}{}{(You think it's the one on the left.)}
{264}{}{(You think it's the one in the middle.)}
{265}{}{(You think it's the one on the right.)}
{266}{}{(You don't know. The cards moved too fast.)}
{267}{}{Lucy leftie}
{268}{}{Middle of th'road}
{269}{}{Rightie tightie}
{270}{}{The one on the left.}
{271}{}{The one on the right.}
{272}{}{The one in the middle.}
{280}{}{(Monte turns over the card. It is the }
{281}{}{Sorry, pal, not this time, but you were CLOSE.}
{282}{}{Sorry, lady, not this time, but you were CLOSE.}
{283}{}{You sure do got the eye for it, though. Wanna try again?}
{284}{}{You cheater. You no play fair}
{285}{}{Okay here chips me not sure how many 20 is so herez a bunch}
{286}{}{Nuh-uh Me no LIKE game BYYYYE}
{287}{}{I'm not playing with a cheater like you.}
{288}{}{Sure. Here's 20 chips.}
{289}{}{Nein, danke.}
{300}{}{(Du gibst das Geld rüber. Monte nickt, zeigt dir die Karten, dann legt er sie hin. Gleichzeitig versteckt er eine Karte so schnell, dass du es kaum mitbekommst. Dann vertauscht er die Karten noch ne Weile.)}
{301}{}{So... which one's the queen, pal?}
{302}{}{So... which one's the queen, lady?}
{303}{}{You put it in sleevie weevie you no play fair}
{304}{}{Lucy leftie}
{305}{}{Middle of th'road}
{306}{}{Rightie tightie}
{307}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{308}{}{The one in your sleeve.}
{309}{}{The one on the left.}
{310}{}{The one on the right.}
{311}{}{The one in the middle.}
{320}{}{WAS hast du gesagt, Kumpel?}
{321}{}{WHAT did you say, lady?}
{322}{}{You accusing me of cheating?}
{323}{}{Uh-uh. Me KNOW you cheet}
{324}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{325}{}{Ja.}
{326}{}{Screw this. Keep the money, I'm outta here.}
{330}{}{Pass auf, Ich hab keine Zeit für schlechte Verlierer. Du hast bezahlt, du hast deine Chance gehabt. Wenn du spielen willst, gut, wenn du aber rumzickst wenn du verlierst, verschwinde von hier!}
{331}{}{ME BREAK YOU}
{332}{}{Nuh-uh! Nuh-uh! Don' be mad. Me going.}
{333}{}{That's it. You're dead.}
{334}{}{All right, all right. I'm sorry. Here's 20 chips. Let's play again.}
{335}{}{Screw you. Keep the money, I'm outta here.}
{340}{}{(Du gibst das Geld rüber. Monte nickt, zeigt dir die Karten, dann legt er sie hin.)}
{341}{}{So... which one's the queen, pal?}
{342}{}{So... which one's the queen, lady?}
{343}{}{(Monte's using his normal deck! You need to steal his other deck to complete the switch.)}
{344}{}{You put it in sleevie weevie you no play fair}
{345}{}{Uh... Lucy leftie}
{346}{}{Uh... Middle of th'road}
{347}{}{Uh... Rightie tightie}
{348}{}{You goddamn CHEATER. I saw you palm that card. Give me back my cash before I kill you here in the street.}
{349}{}{The one in your sleeve.}
{350}{}{Uh, the one on the left.}
{351}{}{Uh, the one on the right.}
{352}{}{Uh, the one in the middle.}
{360}{}{(Du gibst das Geld rüber. Monte nickt, zeigt dir die Karten, dann legt er sie hin.)}
{361}{}{(You hand over the cash. Monte looks uncomfortable.) Uh... all right... (Monte puts the cards on the ground and shuffles them.)}
{362}{}{So... which one's the queen, pal?}
{363}{}{So... which one's the queen, lady?}
{364}{}{(Monte's using the marked deck. Any pick is the right one.)}
{365}{}{Leftie! Leftie!}
{366}{}{Rightie! Rightie!}
{367}{}{Middlie! Middlie!}
{368}{}{Oh, I don't know... the one on the left.}
{369}{}{Hmmmm... maybe the one on the right?}
{370}{}{Gee, I'm not sure... I think it's the one in the middle.}
{375}{}{(Monte dreht die Karte um. Es ist die Herz Dame. Er scheint vor Schreck wie gelähmt zu sein.) Was...? Hey. Äh...}
{376}{}{guess you win, pal.}
{377}{}{guess you win, lady.}
{378}{}{(He hands over the cash reluctantly.)}
{379}{}{Again! Again!}
{380}{}{Thanx me go now}
{381}{}{So we gonna play again or what? C'mon, Monte. I'm just getting started.}
{382}{}{Well, thanks, Monte. See you later.}
{385}{}{(Monte dreht die Karte um. Es ist die Herz Dame. Er sieht geschockt aus.) Oh...? Hey... äh...}
{386}{}{guess you win, pal.}
{387}{}{guess you win, lady.}
{388}{}{That cleans me out, though... (Looks at you weakly) Anything else I could do for you?}
{389}{}{Nuttin. Me just wanted sum extra EXP. Bye. Bye.}
{390}{}{What have you GOT?}
{391}{}{Why don't you give me some information?}
{392}{}{Forget it, Monte. We'll call it even for today.}
{400}{}{(Er schaut schmerzerfüllt.) Äh... gut, ich hab da etwas... aber es ist mehr Wert als du bis jetzt gewonnen hast...}
{401}{}{Well? What is it?}
{402}{}{If it's worth more to you than dying on Golgotha because you welched on a debt, that's your problem. I'd think
 about it, if I were you.}
{404}{}{Oh... hmnnn... kommt darauf an was du wissen willst.}
{405}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{406}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{407}{}{You know where my car is, Monte?}
{408}{}{Got anything you think I should know?}
{409}{}{Nevermind, Monte. We're even. See you later.}
{415}{}{Äh... gut... hör mal, du hast es nicht von mir, aber ich wette es war Renesco, das Arschloch, dass die Apotheke auf der West Side leitet.
 Ich bin mir nicht sicher ob er es an das Kind verkauft hat, aber er weiß etwas. Mehr sage ich aber nicht.}
{416}{}{All right then, Monte. We're even.}
{420}{}{Äh... gut... (Scheint als ob er einen inneren Kampf austrägt.) ...pass auf, du hast es nicht von mir gehört, aber wenn ich du wäre, würde ich im Keller vom Desperado suchen.}
{421}{}{All right then, Monte. We're even.}
{425}{}{(Er kneift die Augen zusammen.) Ich würde ol' Jules am Stadtrand fragen. Da passiert nichts ohne dass er's mitbekommt, und wenn doch, steckt er selber mit drin, verstehst du was ich damit sagen will?}
{426}{}{All right then, Monte. We're even.}
{430}{}{Gut... kennst du diesen Eldridge, der New Reno Arms betreibt? Er sagt er würde Waffen aufrüsten, aber ich hab ihn noch nie arbeiten gesehen. Könnte sich als wertvoll erweisen mal dort nachzuforschen... aber das hast du nicht von mir gehört.}
{431}{}{All right then, Monte. We're even.}
{435}{}{(Monte wirft dir einen finsteren Blick zu, als er dich sieht.) Pass auf. Ich mache heute keine Spiele, alles klar? }
{436}{}{Can I buy that card you showed me before?}
{437}{}{I wanted some information...}
{438}{}{All right, Monte. I'll leave... for now.}
{440}{}{Nein. Das kannst du vergessen. Basta. Sie ist ein ECHTES Vorkriegs-Erinnerungsstück... ein kleines Stück Geschichte. Keine Chance.}
{441}{}{You making me ANOTHER offer? Look, I told you I ain't selling it.}
{442}{}{How about a thousand chips? I got it with me. It's yours in exchange for that card.}
{443}{}{Not even for 750 chips?}
{444}{}{How about 500 chips?}
{445}{}{250 chips sound about right?}
{446}{}{OK. Ich hätt da noch ein paar Fragen...}
{447}{}{Nevermind then, Monte. I'm outta here.}
{450}{}{Bist du Taub? Der Betrag ist nicht hoch genug um mein Interesse zu wecken.}
{451}{}{How about I suggest another amount...?}
{452}{}{Ich hab da noch ein paar Fragen...}
{453}{}{Nevermind then, Monte. I'm outta here.}
{460}{}{Gut, SO teuer ist sie mir auch nicht. Sie gehört dir Kumpel. (Er schaut nach links und rechts, dann bückt er sich und zieht seinen Stiefel aus. Er dreht den Absatz, öffnet ihn und holt die Spielkarte raus.) Hier ist sie. Pass darauf auf.}
{461}{}{Ich hab da noch ein paar Fragen...}
{462}{}{Thanks, Monte. Always a pleasure.}
{465}{}{(Er blickt finster.) Ob ich rede hängt davon ab was du wissen willst. Und es wird nicht billig.}
{466}{}{You know who dusted Wright's kid? Made him O.D. on Jet?}
{467}{}{You know where I could find some guy named Pretty Boy Lloyd?}
{468}{}{You know where my car is, Monte?}
{469}{}{Got anything you think I should know?}
{470}{}{Nevermind then, Monte. I'm outta here.}
{475}{}{Auf keinen Fall, wenn ich dieses Thema auch nur ANSTREIFE werde ich in Golgotha landen. Hau ab.}
{476}{}{Look, that subject's just bad news. Leave it alone, all right?}
{477}{}{You making me another offer? Look, I told you I AIN'T going talk about it.}
{478}{}{A thousand chips change your mind? I got it with me.}
{479}{}{Not even for 750 chips?}
{480}{}{How about 500 chips?}
{481}{}{250 chips sound about right?}
{482}{}{Uh... Golgotha?}
{483}{}{Ich hab da noch ein paar Fragen...}
{484}{}{Nevermind then, Monte. I'm outta here.}
{490}{}{(Schüttelt seinen Kopf.) Keine Chance. Darüber zu sprechen könnte schon jemanden umbringen, und ich bin sicher der Erste, der daran glauben muss. Vergiss es.}
{491}{}{How about if I offered you this...}
{492}{}{Ich hab da noch ein paar Fragen...}
{493}{}{Nevermind then, Monte. I'm outta here.}
{495}{}{Äh... gut... das sind eine Menge Chips. (Leckt seine Lippen. Er sieht aus als ob er einen inneren Konflikt hätte... aber der Kampf ist schnell entschieden.) Pass auf, du hast es nicht von mir gehört...}
{496}{}{Understood. Go on.}
{500}{}{(Er wirft dir ein höhnisches Lächeln zu.) Vielleicht hab ich was gehört, vielleicht auch nicht. Sag einen Preis.}
{501}{}{All right... talk a price.}
{502}{}{How about a thousand chips? I got it with me.}
{503}{}{Not even for 750 chips?}
{504}{}{How about 500 chips?}
{505}{}{250 chips sound about right?}
{506}{}{Ich hab da noch ein paar Fragen...}
{507}{}{Nevermind then, Monte. I'm outta here.}
{510}{}{Ha! Für den Preis kriegst du nicht mal einen Eimer Pisse. Vergiss es.}
{511}{}{How about if I offered you this...}
{512}{}{Ich hab da noch ein paar Fragen...}
{513}{}{Nevermind then, Monte. I'm outta here.}
{515}{}{Daaaas stimmt. (Grinst böse.) Das hast du nicht von mir, aber ich an deiner Stelle würde ich es mal im Keller des Desperado in der Virgin Street probieren. Da unten gibt es viele Ratten, wenn du verstehst was ich meine.}
{516}{}{Ich hab da noch ein paar Fragen...}
{517}{}{Alles klar, danke.}
{520}{}{(Zuckt mit den Achseln.) Vielleicht hab ich was gehört, vielleicht auch nicht. Sag mir den Preis und vielleicht kann ich dir dazu was sagen.}
{521}{}{All right... talk a price.}
{522}{}{How about a thousand chips? I got it with me.}
{523}{}{Not even for 750 chips?}
{524}{}{How about 500 chips?}
{525}{}{250 chips sound about right?}
{526}{}{Ich hab da noch ein paar Fragen...}
{527}{}{Nevermind then, Monte. I'm outta here.}
{530}{}{(Er kneift die Augen zusammen.) Für den Preis weiß ich gar nichts.}
{531}{}{How about if I offered you this...}
{532}{}{Ich hab da noch ein paar Fragen...}
{533}{}{Nevermind then, Monte. I'm outta here.}
{535}{}{Das stimmt... (Er kneift die Augen zusammen.) ...ich würde ol' Jules am Stadtrand fragen. Da passiert nichts ohne dass er's mitbekommt, und wenn doch, steckt er selber mit drin, verstehst du was ich damit sagen will?}
{536}{}{Ich hab da noch ein paar Fragen...}
{537}{}{All right then, Monte. Thanks.}
{540}{}{(Er zuckt mit den Schultern.) Ich höre und sehe viel. Für eine kleine Spende von 200 Chips... du verstehst was ich meine?}
{541}{}{Here's 200 chips.}
{542}{}{I'll give you 150.}
{543}{}{100 chips or nothing.}
{544}{}{Ich hab da noch ein paar Fragen...}
{545}{}{Nevermind then, Monte. I'm outta here.}
{550}{}{Bist du taub? ICH SAGTE 200 Chips, nicht weniger.}
{551}{}{All right. Here's 200 chips.}
{552}{}{Ich hab da noch ein paar Fragen...}
{553}{}{Nevermind then, Monte. I'm outta here.}
{555}{}{Done. (Monte leans in) Well, know that guy Eldridge, runs New Reno Arms? He SAYS he does
 weapon upgrades, but I never see him do any work. You might want to check out his place... but you didn't hear that from me.}
{556}{}{Ich hab da noch ein paar Fragen...}
{557}{}{Understood. Thanks, Monte.}
{560}{}{Massengrab südlich der Stadt. Stinkt zu Himmel.}
{561}{}{Oh... I see. Now, about the Wright kid...}
{562}{}{Forget the Wright kid. I had some other questions...}
{563}{}{All right then, Monte. Thanks.}
{565}{}{Ich wette es war Renesco, das Arschloch, das die Apotheke auf der West Side leitet.
 Ich bin mir nicht sicher ob er es an das Kind verkauft hat, aber er weiß etwas. (Schaut sich um.) Mehr sage ich aber nicht.}
{566}{}{Ich hab da noch ein paar Fragen...}
{567}{}{All right then, Monte. Thanks.}
{570}{}{(Er schaut sich um, dann bückt er sich und zieht seinen Stiefel aus. Er dreht den Absatz ab und holt eine Karte raus... auf der Karte ist ein Mann mit einem komischen Hut zu sehen, der eine Keule schwingt.) Interessiert? Das ist ein echtes Vorkriegsandenken.}
{571}{}{No, I already have enough inventory items... I'd rather have some information instead.}
{572}{}{Uh, sure. Why not? This'll settle things between us.}
{573}{}{Sorry pal, no chips, no game. Come back when you got more money.}
{574}{}{Sorry lady, no chips, no game. Come back when you got more money.}
{575}{}{Yeah, maybe next time then.}
{576}{}{You quickly swap Monte's deck of cards for the marked deck.}
{600}{}{spades}
{601}{}{hearts}
{602}{}{diamonds}
{603}{}{clubs}
{604}{}{zwei}
{605}{}{drei}
{606}{}{vier}
{607}{}{fünf}
{608}{}{sechs}
{609}{}{sieben}
{610}{}{acht}
{611}{}{neun}
{612}{}{zehn}
{613}{}{ , }
