{100}{}{Du siehst Darlin' Nikki.}
{125}{}{Du siehst eine Mitarbeiterin des Kasinos.}
{150}{}{Du siehst Darlin' Nikki.}
{151}{}{You see Darlin' Nikki. She winks at you.}
{152}{}{Du siehst Darlin' Nikki. Sie macht dir ein Zeichen, dass du rüberkommen und spielen sollst.}
{153}{}{You see Darlin' Nikki. Mason was right about her ass.}
{154}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{155}{}{You see Darlin' Nikki. Mason was right about her ass.}
{156}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{160}{}{Du siehst Darlin' Nikki. Sie macht dir ein Zeichen, dass du rüberkommen und spielen sollst.}
{161}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{162}{}{You see Darlin' Nikki. Her dress barely covers her body.}
{170}{}{Du siehst eine Mitarbeiterin des Kasinos.}
{171}{}{Du siehst eine Kasino-Mitarbeiterin. Sie winkt dir zu.}
{172}{}{Du siehst eine Kasino-Mitarbeiterin. Sie macht dir ein Zeichen, dass du rüberkommen und spielen sollst.}
{173}{}{Du siehst eine Kasino-Mitarbeiterin. Sie hat ein paar gute "Spiele".}
{174}{}{Du siehst eine Kasino-Mitarbeiterin. Ihr Kleid bedeckt nur knapp ihren Körper.}
{175}{}{Du siehst eine Kasino-Mitarbeiterin. Sie riecht seeehr gut.}
{180}{}{Du siehst eine Kasino-Mitarbeiterin. Sie macht dir ein Zeichen, dass du rüberkommen und spielen sollst.}
{181}{}{Du siehst eine Kasino-Mitarbeiterin. Ihr Kleid bedeckt nur knapp ihren Körper.}
{182}{}{Du siehst eine Kasino-Mitarbeiterin. Ihr Kleid bedeckt nur knapp ihren Körper.}
{183}{}{Du siehst eine Kasino-Mitarbeiterin. Sie macht dir ein Zeichen, dass du rüberkommen und spielen sollst.}
{200}{}{::Jubelt::}
{201}{}{::Klatscht::}
{202}{}{::Pfeift::}
{203}{}{! Willkommen im Kasino, Held!}
{204}{}{Thought you'd forgotten about us while you were saving the world.}
{210}{}{Hallo, }
{211}{}{wenn du noch eine Begleitung für später suchst...}
{212}{}{Hey, you...(winks)...you looking to gamble?}
{213}{}{Er sieht so... (erschaudert)...gefährlich aus.}
{214}{}{Willkommen im Kasino, }
{215}{}{Legst du beim Boss ein gutes Wort für mich ein?}
{216}{}{Hallo, Verehrteste. Lass mich wissen, wenn ich dir irgendwie behilflich sein kann.}
{217}{}{Wollen sie spielen Verehrteste?}
{218}{}{Sie sieht so... (erschaudert)...gefährlich aus.}
{220}{}{Sieht so aus, als würdest du schon mit deinen Leben spielen.}
{221}{}{Äh, ich denke du bist hier im falschen Kasino…}
{222}{}{Wenn der nicht abhaut, bevor ihn die Jungs sehen…}
{223}{}{Oh-oh. Ärger…}
{224}{}{Sieht so aus, als würdest du schon mit deinen Leben spielen.}
{225}{}{Oh, ich denke, sie ist im falschen Kasino…}
{226}{}{Wenn sie nicht verschwindet bevor die Jungs sie sehen…}
{230}{}{Hey starker Mann, willst du ein paar Chips setzten?}
{231}{}{Hey, champ...(winks)...you looking to gamble?}
{232}{}{Hey, champ...(smiles)...wanna take a chance?}
{233}{}{wenn du noch eine Begleitung für später suchst...}
{234}{}{Soll ich ih ansprechen…}
{235}{}{Hey, }
{236}{}{Wenn du ein paar Chips gewinnen willst bist du hier genau richtig.}
{237}{}{Best casino in New Reno. In the WORLD, even.}
{238}{}{Die Glücksfee ist heute bei uns zu Gast, ihr könnt nur gewinnen!}
{239}{}{Komm her, }
{240}{}{Willst du nen Drink?}
{241}{}{Willkommen im Kasino, }
{242}{}{Hallo, }
{243}{}{Willst du spielen, }
{244}{}{Willkommen im Kasino, }
{250}{}{Hey Filmstar, willst du ein paar Chips verdienen?}
{251}{}{Hey, }
{252}{}{Hey, }
{253}{}{Wenn du hier bist um ein paar Chips zu gewinnen }
{254}{}{Best casino in New Reno. In the WORLD, even.}
{255}{}{Die Glücksfee ist heute bei uns zu Gast, ihr könnt nur gewinnen!}
{266}{}{Komm her, }
{267}{}{Willst du nen Drink?}
{268}{}{Willkommen im Kasino, }
{269}{}{Hey there, Mrs. Movie Star. Looking to spend a paycheck?}
{270}{}{Hey Süße, willst du ein paar Chips verspielen?}
{271}{}{Hey, sweetie...(winks)...you looking to gamble?}
{272}{}{Hey, sweetie...(smiles)...wanna take a chance?}
{273}{}{Wenn du ein paar Chips gewinnen willst bist du hier genau richtig.}
{274}{}{Best casino in New Reno. In the WORLD, even.}
{275}{}{Die Glücksfee ist heute bei uns zu Gast, ihr könnt nur gewinnen!}
{276}{}{Komm her und gewinne ein paar Chips.}
{277}{}{Willst du nen Drink Süße?}
{278}{}{Willkommen im Kasino Süße.}
{279}{}{Wenn du spielen willst, dieser Tisch ist frei…}
{280}{}{Hallo süße. Willst du ein paar Chips gewinnen?}
{281}{}{willst du spielen Süße?}
{282}{}{Willkommen im Kasino Süße.}
{290}{}{Hm, du bist verrückt das du hierher gekommen bist, aber gut. setzte deine Chips. Minimum 5 Chips.}
{291}{}{Um... place your bets... minimum bet 5 chips. Place your bets...}
{292}{}{Place your bet, sir. Minimum bet 5 chips. Place your bets...}
{293}{}{Place your bet, ma'am. Minimum bet 5 chips. Place your bets...}
{294}{}{Place your bets, minimum bet 5 chips. Place your bets...}
{295}{}{Ich besser als du}
{296}{}{Ich spielen Krebs in Unterhose}
{297}{}{What this game? Can you bet Gecko skin? Me got geck... ooooh... pretty lights over there!}
{298}{}{Bet 5 chips?}
{299}{}{Bet 15 chips?}
{300}{}{Bet 25 chips?}
{301}{}{Bet 50 chips?}
{302}{}{You Nikki?}
{303}{}{How you doing, Nikki?}
{304}{}{Whoa, too rich for my blood. I'm outta here.}
{305}{}{Kein Glücksspiel heute, Danke.}
{310}{}{Oh, sehr gut Sir. Kommen Sie bald wieder.}
{311}{}{Oh, sehr gut Ma'am. Kommen sie später wieder.}
{312}{}{Hm… Ich habe gehört die geben verlorene Gehirne raus. Vielleicht sollte ich da mal hin.}
{313}{}{Tschööö.}
{314}{}{Gooodie. }
{315}{}{Uh... brains... what them?}
{320}{}{Oh, sehr gut Sir. Kommen Sie bald wieder.}
{321}{}{Oh, sehr gut Ma'am. Kommen sie später wieder.}
{322}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{323}{}{5 chips? 'Too rich for your blood?' Pal, you're in the wrong town.}
{324}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{325}{}{5 chips? 'Too rich for your blood?' Girl, you're in the wrong town.}
{326}{}{Werde ich machen, Danke.}
{327}{}{Maybe so, but at least *I* don't live here.}
{330}{}{Es tut mir leid Sir. Viel Glück beim nächsten Mal.}
{331}{}{Es tut mir leid Ma'am. Viel Glück beim nächsten Mal.}
{332}{}{Tut mir leid, viel Glück beim nächsten Mal.}
{333}{}{You have [C] chips. Keep playing?}
{334}{}{Ist heute wohl dein Tag.}
{335}{}{Ist heute wohl deinen Nacht.}
{340}{}{Gewonnen! Gut gemacht Sir!}
{341}{}{Winner! Well done, ma'am!}
{342}{}{Winner!}
{343}{}{You have [C] chips. Keep playing?}
{344}{}{Ist heute wohl dein Tag.}
{345}{}{Ist heute wohl deinen Nacht.}
{350}{}{Gewonnen! Du hast dein Geld verdoppelt! Gut gemacht Sir!}
{351}{}{Gewonnen! Du hast dein Geld verdoppelt! Gut gemacht Ma'am!}
{352}{}{Gewonnen! Du hast dein Geld verdoppelt!}
{353}{}{You have [C] chips. Keep playing?}
{354}{}{Ist heute wohl dein Tag.}
{355}{}{Ist heute wohl deinen Nacht.}
{360}{}{Gewonnen! du hast dein Geld verdreifacht! Du hast wohl ne Glückssträhne! Gut gemacht Sir!}
{361}{}{Gewonnen! du hast dein Geld verdreifacht! Du hast wohl ne Glückssträhne! Gut gemacht Ma'am!}
{362}{}{Gewonnen! du hast dein Geld verdreifacht!}
{363}{}{You have [C] chips. Keep playing?}
{364}{}{Ist heute wohl dein Tag.}
{365}{}{Ist heute wohl deinen Nacht.}
{370}{}{Was willst du den jetzt? Willst du jetzt meine Zeit verschwenden, oder willst du setzten?}
{371}{}{I'm whoever you WANT me to be, sweetheart. Now, you gonna place a bet?}
{372}{}{I'm whoever you WANT me to be, girlfriend. Now, you gonna place a bet?}
{373}{}{Place a bet.}
{374}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{375}{}{Yeah, I'm betting you and Pretty Boy Lloyd were both stealing money from Mr. Salvatore. Hard to believe you
 didn't notice him cheating all those times.}
{376}{}{Kennst du jemanden der sich Schönling Llyod nennt?}
{377}{}{We'll talk later, Nikki.}
{380}{}{Ja, Ich habe gehört, es sei tot. Wolltest du das hören, Mörder?! Häh?! Willst du jetzt setzen, oder weiterhin solchen Mist verzapfen?}
{381}{}{Nope. You gonna place a bet?}
{382}{}{Place a bet.}
{383}{}{Yeah. I'm betting you know where Pretty Boy Lloyd is.}
{384}{}{Yeah, I'm betting you and Pretty Boy Lloyd were both stealing money from Mr. Salvatore. Hard to believe you didn't notice
 Lloyd cheating all those times.}
{385}{}{We'll talk later, Nikki.}
{390}{}{Dann wirst du wohl deinen Einsatz VERLIEREN Süßer, aber wenn du genauso dumm wie hässlich bist, kannst du ruhig darauf setzen. Ich hab das Schwein nicht mehr gesehen, seit er Mr. Salvatore betrogen hat.}
{391}{}{Then that's a bet you'd lose, sweetheart. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{392}{}{Then that's a bet you'd lose, girlfriend. I ain't seen that bum since he pulled that swindle on Mr. Salvatore.}
{393}{}{Maybe you didn't hear me the first time, so for the benefit of the hearing impaired: Where is Lloyd?}
{394}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{395}{}{Fine. We'll talk later, Nikki.}
{400}{}{Süßer, Ich hab dir schon gesagt, dass ich nicht weiß wo er ist. Jetzt pass auf, ich muss hier arbeiten, also verschwinde wieder dahin wo du hergekommen bist —}
{401}{}{Girlfriend, I TOLD you that I don't know where he is. Now, look, I'm WORKING here, so go back to whatever rock you --}
{402}{}{Nikki, Nikki... I'm losing PATIENCE here. If you don't tell me where Lloyd is, I'm going to lose my temper, too.}
{403}{}{Nikki, I don't know what happened between you and Lloyd. But guess what? I don't NEED to know. I'll just tell
 Mr. Salvatore what I suspect.}
{404}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{405}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{406}{}{We'll talk later then, Nikki.}
{410}{}{Fass mich an und Mr. Salvatore wird dich bei lebendigen Leibe Häuten.}
{411}{}{Salvatore won't protect you; dealers like you are a chip a dozen. Cut the shit and tell me where Lloyd is or ELSE.}
{412}{}{Salvatore won't protect you; he's dead. Cut the shit and tell me where Lloyd is or ELSE.}
{413}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{414}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{415}{}{We'll talk later then, Nikki.}
{420}{}{Wovon redest du?}
{421}{}{Nikki, if you don't tell me everything right now, I'll tell Mr. Salvatore you were in on it, whether you were or not.
 He'll have Mason cut you up seven ways to Sunday, and have your job filled in an hour.}
{422}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{423}{}{Pretty suspicious you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{424}{}{We'll talk later then, Nikki.}
{430}{}{Pass auf, wie ich es schon gesagt hatte. Ich weiß nicht wo er ist. Aber *vielleicht* hab ich gehört, dass er ein Zimmer im Desperado hat. Vielleicht wirst du dort fündig. Wenn es dir nichts ausmacht, arbeite ich dann weiter.}
{431}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{432}{}{Pretty suspicious that you didn't notice him cheating all those times. You'd have to be blind... or bribed.}
{433}{}{We'll talk later then, Nikki.}
{440}{}{Ich habe gerade erst angefangen hier zu arbeiten und ich kann unmöglich jeden Kartenzähler oder Taschenkünstler erkennen. Nicht so gut wie Idioten wie dich.}
{441}{}{Oh, so that's how you and Lloyd hooked up then?}
{442}{}{So you just started work, huh? Pretty convenient. Well, that's all I need to know. Tell Lloyd he's a dead man.}
{443}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{444}{}{We'll talk later then, Nikki.}
{450}{}{Ja, wenn man so auf Jet ist wie du, sieht alles verdächtig aus, oder?}
{451}{}{It IS suspicious. You should have had Lloyd pegged for what he was as soon as he walked in this casino.}
{452}{}{Nikki, I know you helped Lloyd cheat. Tell me where Lloyd is, and I'll give you half of his take: 500 chips.}
{453}{}{We'll talk later then, Nikki.}
{460}{}{Verschwinde sofort von hier. Ich habe dir nichts mehr zu sagen.}
{461}{}{I got nothing to say to you. Get out of here.}
{462}{}{Not now, maybe. We'll talk later though, Nikki. Count on it.}
{470}{}{Du weißt gar nicht wovon du da redest. Vielleicht weiß ja ich wo Lloyd ist, vielleicht aber auch nicht. Hast du 500 Chips?}
{471}{}{Maybe. Depends on what you got for me.}
{480}{}{Es KÖNNTE sein, dass Lloyd noch immer meinen Anteil hat, und ich bin mir nicht so sicher, dass er ihn mir geben wird. Also KÖNNTE ich dir, für 500 Chips, sagen, wo sich dieses verlogene Arschloch rumtreibt.}
{481}{}{Done. Here's the 500 chips. Tell me where he is.}
{482}{}{That's a pretty steep price for a whole bunch of "maybes" and "coulds." I'll find him on my own.}
{483}{}{I don't have enough chips, but I'll be back. You better still be here when I return.}
{490}{}{(Packt das Geld weg.) Schau im Boilerraum im Keller des Desperado nach. Dorthin ist der Hurensohn verschwunden, als es ihm zu heiß wurde.}
{491}{}{All right then. Later, Nikki.}
{500}{}{Könntest du bitte gehen?! Wenn uns die Leute so sprechen sehen, werden sie über uns sprechen. Verstanden?}
{501}{}{All right then. Later, Nikki.}
{510}{}{Verschwinde! Ich habe dir nichts mehr zu sagen, für immer.}
{511}{}{Breaks my heart. Later, Nikki.}
{600}{}{You bribe Nikki in telling you where Lloyd might be hiding.}
{1210}{}{. Can I help you with... anything?}
{1214}{}{.}
{1235}{}{. willst du ein paar Chips setzten?}
{1239}{}{, und gewinn ein paar Chips.}
{1241}{}{.}
{1242}{}{. Lass mich wissen, wenn ich dir irgendwie helfen kann.}
{1243}{}{?}
{1244}{}{.}
{1251}{}{...(winks)...you looking to gamble?}
{1252}{}{...(smiles)...wanna take a chance?}
{1253}{}{, you came to the right place.}
{1266}{}{, und gewinn ein paar Chips.}
{1268}{}{.}
{1314}{}{ could always use new inventory item}
{2699}{}{Tanzt du heute?}
