{100}{}{Du siehst Darlin' Nikki.}
{125}{}{Du siehst eine Mitarbeiterin des Kasinos.}
{150}{}{Du siehst Darlin' Nikki.}
{160}{}{Du siehst Darlin' Nikki. Sie macht dir ein Zeichen, dass du rüberkommen und spielen sollst.}
{170}{}{Du siehst eine Mitarbeiterin des Kasinos.}
{180}{}{Du siehst eine Kasino-Mitarbeiterin. Sie macht dir ein Zeichen, dass du rüberkommen und spielen sollst.}
{200}{}{::Jubelt::}
{210}{}{Hallo, [MM]. Kann ich dir helfen mit…irgendwas?}
{220}{}{Sieht so aus, als würdest du schon mit deinen Leben spielen.}
{230}{}{Hey starker Mann, willst du ein paar Chips setzten?}
{250}{}{Hey Filmstar, willst du ein paar Chips verdienen?}
{270}{}{Hey Süße, willst du ein paar Chips verspielen?}
{290}{}{Hm, du bist verrückt das du hierher gekommen bist, aber gut. setzte deine Chips. Minimum 5 Chips.}
{310}{}{Oh, sehr gut Sir. Kommen Sie bald wieder.}
{320}{}{Oh, sehr gut Sir. Kommen Sie bald wieder.}
{330}{}{Es tut mir leid Sir. Viel Glück beim nächsten Mal.}
{340}{}{Gewonnen! Gut gemacht Sir!}
{350}{}{Gewonnen! Du hast dein Geld verdoppelt! Gut gemacht Sir!}
{360}{}{Gewonnen! du hast dein Geld verdreifacht! Du hast wohl ne Glückssträhne! Gut gemacht Sir!}
{370}{}{Was willst du den jetzt? Willst du jetzt meine Zeit verschwenden, oder willst du setzten?}
{380}{}{Ja, Ich habe gehört, es sei tot. Wolltest du das hören, Mörder?! Häh?! Willst du jetzt setzen, oder weiterhin solchen Mist verzapfen?}
{390}{}{Dann wirst du wohl deinen Einsatz VERLIEREN Süßer, aber wenn du genauso dumm wie hässlich bist, kannst du ruhig darauf setzen. Ich hab das Schwein nicht mehr gesehen, seit er Mr. Salvatore betrogen hat.}
{400}{}{Süßer, Ich hab dir schon gesagt, dass ich nicht weiß wo er ist. Jetzt pass auf, ich muss hier arbeiten, also verschwinde wieder dahin wo du hergekommen bist —}
{410}{}{Fass mich an und Mr. Salvatore wird dich bei lebendigen Leibe Häuten.}
{420}{}{Wovon redest du?}
{430}{}{Pass auf, wie ich es schon gesagt hatte. Ich weiß nicht wo er ist. Aber *vielleicht* hab ich gehört, dass er ein Zimmer im Desperado hat. Vielleicht wirst du dort fündig. Wenn es dir nichts ausmacht, arbeite ich dann weiter.}
{440}{}{Ich habe gerade erst angefangen hier zu arbeiten und ich kann unmöglich jeden Kartenzähler oder Taschenkünstler erkennen. Nicht so gut wie Idioten wie dich.}
{450}{}{Ja, wenn man so auf Jet ist wie du, sieht alles verdächtig aus, oder?}
{460}{}{Verschwinde sofort von hier. Ich habe dir nichts mehr zu sagen.}
{470}{}{Du weißt gar nicht wovon du da redest. Vielleicht weiß ja ich wo Lloyd ist, vielleicht aber auch nicht. Hast du 500 Chips?}
{480}{}{Es KÖNNTE sein, dass Lloyd noch immer meinen Anteil hat, und ich bin mir nicht so sicher, dass er ihn mir geben wird. Also KÖNNTE ich dir, für 500 Chips, sagen, wo sich dieses verlogene Arschloch rumtreibt.}
{490}{}{(Packt das Geld weg.) Schau im Boilerraum im Keller des Desperado nach. Dorthin ist der Hurensohn verschwunden, als es ihm zu heiß wurde.}
{500}{}{Könntest du bitte gehen?! Wenn uns die Leute so sprechen sehen, werden sie über uns sprechen. Verstanden?}
{510}{}{Verschwinde! Ich habe dir nichts mehr zu sagen, für immer.}
