{100}{}{Du siehst den Aufseher des Kasinos.}
{150}{}{Du siehst einen elegant gekleideten Mann. Er ist der Aufseher des Kasinos.}
{151}{}{Du siehst einen Kasinoaufseher, der aufmerksam alles kontrolliert.}
{200}{}{Ähem...ich fürchte, du musst diese Rüstung ablegen.}
{201}{}{Ähem...ich fürchte, du musst diese Rüstung ablegen.}
{202}{}{Äh...in dieser Aufmachung kommst du nicht ins Kasino.}
{205}{}{Äh, warum schleichst du hier herum, Jungchen?}
{206}{}{Äh, bist du hier undercover, Mister?}
{210}{}{Äh, warum schleichst du hier herum, Mädchen?}
{211}{}{Äh, bist du hier undercover, Lady?}
{215}{}{Guten Abend, }
{216}{}{'n Abend, }
{220}{}{Guten Abend, }
{221}{}{'n Abend, }
{225}{}{Guten Tag, }
{230}{}{Guten Tag, }
{235}{}{Freund, du gehst ins Falsche Kasino!}
{236}{}{Du solltest besser gehen. Jetzt.}
{237}{}{Dies ist nicht der richtige Ort um mit dem Leben zu Spielen. Du gehst besser.}
{238}{}{Schlampe, du gehst ins falsche Kasino!}
{245}{}{Es tut mir leid, aber du musst die Waffe wegstecken.}
{250}{}{Es tut mir leid, aber du musst die Waffe wegstecken.}
{255}{}{Schätzchen, es tut mir leid, aber du darfst im Kasino keine Waffen tragen. Ha-ha... du bist auch so schon tödlich genug.}
{260}{}{Schätzchen, mit so 'nem Körper kannst du dich nirgendwo vorbeischleichen.}
{265}{}{Hey, Sippentrottel, du solltest diese Waffe besser JETZT GLEICH wegstecken.}
{270}{}{Hey, Sippentrottel, du solltest besser JETZT GLEICH aufhören, hier rumzuschleichen.}
{275}{}{He, he... Myron! Hab dich ja lange nicht außerhalb des Labors gesehen.}
{276}{}{Bist du hier um mir ein paar neue Kreationen vorzustellen, Myron?}
{277}{}{Hey! Komm doch rein, Myron.}
{280}{}{Schieß los. Was willst du wissen?}
{281}{}{Fuuuuuuh fuh fuh fuuuuh}
{282}{}{[Verschwinde]}
{283}{}{Wer bist du?}
{284}{}{Was ist das hier für ein Kasino?}
{285}{}{Kannst du mir ein bisschen was über das Kasino erzählen?}
{286}{}{Kennst du jemanden der sich Schönling Llyod nennt?}
{287}{}{Wer ist der Alte an dem Automaten da?}
{288}{}{Der Komiker, den ihr da auf der Bühne habt, ist ganz schön schlecht. Was dagegen, wenn ich's mal probiere?}
{289}{}{Danke. Braucht ihr für heute Abend eine Tänzerin? Ich wär grade mal frei.}
{290}{}{Danke, das werd ich.}
{291}{}{Nichts weiter, danke. Entschuldige die Störung.}
{292}{}{Wollte nur mal nach dem Rechten sehen. Lass dich nicht stören.}
{295}{}{Keine Roboter!}
{296}{}{Wir haben hier nichts für Droiden!}
{297}{}{Keine Droiden. Die müssen draußen warten.}
{300}{}{Äh, du verdrückst dich jetzt besser mal, Mister.}
{301}{}{Äh, du verdrückst dich jetzt besser mal, Madame.}
{302}{}{[Lächelt höhnisch.] Raus hier, du Dorftrottel.}
{303}{}{Mama sagen, ich was Besonderes}
{304}{}{[Verschwinde]}
{305}{}{Ich hab grad kein Bock zu plaudern, aber ich freu mich das du der Enklave in den Arsch getreten hast.}
{306}{}{Hey, }
{315}{}{Ja, ich bin auch was ganz Besonderes, frag deine Mama. Und jetzt mach dich auf die Socken...vielleicht ist sie ja
 irgendwo auf der Virgin Street.}
{316}{}{Prima! Winke, winke}
{317}{}{[Verschwinde]}
{325}{}{Ich bin der Kasinoaufseher. [Guckt ein wenig irritiert.] Also, was kann ich für dich tun?}
{326}{}{Ich bin ich hier der Leiter des Kasinobereichs. Wenn du was brauchst, wende dich an mich.}
{327}{}{Was ist das hier für ein Kasino?}
{328}{}{Kannst du mir ein bisschen was über das Kasino erzählen?}
{329}{}{Nichts weiter, danke. Entschuldige die Störung.}
{335}{}{This is [CN]. Need anything, just ask.}
{336}{}{Das is [CN]. Steht zumindest draußen auf dem Schild, soweit ich mich erinnern kann. Also, was kann ich für dich tun?}
{337}{}{Wer bist du?}
{338}{}{Kannst du mir ein bisschen was über das Kasino erzählen?}
{339}{}{Nichts weiter, danke. Entschuldige die Störung.}
{340}{}{[Der Blick des Aufsehers bleibt auf die Spieltische gerichtet.] Was kann ich für dich tun, Kumpel?}
{341}{}{[Der Blick des Aufsehers bleibt auf die Spieltische gerichtet.] Was kann ich für dich tun, Baby?}
{342}{}{Fuuuuuuh fuh fuh fuuuuh}
{343}{}{[Verschwinde]}
{344}{}{Wer bist du?}
{345}{}{Das geilste Kasino in der ganzen Stadt...bin da aber nicht ganz objektiv, das geb ich zu. [Lacht.] Sonst noch
 Fragen?}
{346}{}{Das geilst Kasino in der ganzen Stadt...die besten Tische...aber warum probierst du's nicht einfach selber aus?}
{347}{}{Wer bist du?}
{348}{}{Wer ist der Eigentümer?}
{349}{}{Gut, besten Dank. Entschuldige die Störung. [Ab.].}
{350}{}{Danke. Braucht ihr für heute Abend eine Tänzerin? Ich wär grade mal frei.}
{351}{}{Danke, das werd ich.}
{352}{}{Nichts weiter, danke. Entschuldige die Störung.}
{353}{}{Wollte nur mal nach dem Rechten sehen. Lass dich nicht stören.}
{355}{}{Die [CA]-Familie. Sie haben viel Leben in diesen Ort gepumpt, ihn zu einem richtigen Anziehungspunkt gemacht, einem leuchtenden Juwel in New Reno.}
{356}{}{Die [CA] Familie. Was dagegen einzuwenden? Wenn du nicht zum Spielen hier bist, bist du an der falschen Adresse. Kapiert?}
{357}{}{Wer bist du?}
{358}{}{Kannst du mir ein bisschen was über das Kasino erzählen?}
{359}{}{Ah ja. Besten Dank für die Auskunft.}
{360}{}{Hey, schau mal, wer da ist! Hey, }
{361}{}{. Willkommen bei [CN]. Ich steh auf deine Filme.}
{362}{}{Fuuuuuuh fuh fuh fuuuuh}
{363}{}{[Verschwinde]}
{364}{}{Wer bist du?}
{365}{}{Der da? Der alte McGee? Total durchgeknallt, der Typ...der steht schon seit Jahren an diesem Automat und wartet auf
 den großen Jackpot. Dürfte inzwischen so ziemlich sein ganzes Vermögen an das Ding verfüttert haben. Hat noch nie auch nur
 einen müden Dollar davon wiedergesehen.}
{366}{}{Der da? Der alte McGee? Total durchgeknallt, der Typ, davon kannst du ausgehen. Ha, ha. War ziemlich sauer, dass du
 sein Vermögen gewonnen hast. An deiner Stelle würd ich mich vor dem in acht nehmen.}
{367}{}{Ist der Automat getürkt oder so?}
{368}{}{Ich hab da noch ein paar Fragen...}
{369}{}{Danke für die Auskunft.}
{370}{}{Danke, sehr schmeichelhaft. Wollte nur mal Tag sagen. [Ab.]}
{375}{}{[Schüttelt den Kopf.] Nicht die Bohne, nur ein bisschen stur...genau wie McGee. [Zuckt die Achseln.] Müsste vielleicht
 mal wieder überholt werden, aber wir haben keinen Mechaniker, der mit dem verdammten Ding klarkommt.}
{376}{}{Ich hab da noch ein paar Fragen...}
{377}{}{Gut zu wissen. Danke für die Information.}
{385}{}{Ja, dieser Dreckskerl ist letzte Woche hier reingekommen und hat an einem von den Tischen um die tausend Chips
 abgezogen. Keine Ahnung, wo er jetzt steckt. Hat jedenfalls eine Zeitlang im Desperado gewohnt.}
{386}{}{Ja, es gab da jemanden, der hieß so. Hatte eines von den Zimmern oben gemietet, die 204. Immer alles bezahlt. Vor ein
 paar Tagen hat er sich davongemacht. Keiner hat ihn gehen sehen.}
{387}{}{Mr. Salvatore meinte was von einem ganz bestimmten Geber, bei dem Lloyd das Geld gewonnen hat. Wer war das?}
{388}{}{Ich hab da noch ein paar Fragen...}
{389}{}{Danke für die Auskunft.}
{395}{}{Nikki? [Sieht sich um.] Ja, die ist da drüben, am mittleren Tisch. Gibt's irgendwelche Probleme?}
{396}{}{Probleme? Nein. Ich wollte nur mal mit ihr reden, ein paar Fragen stellen...}
{397}{}{Danke für die Auskunft.}
{405}{}{Das war an Nikkis Tisch. Aber die arbeitet nicht mehr hier...ist letztens rausgeflogen.}
{406}{}{Hmmm. Macht's dir was aus, wenn ich dir noch ein paar Fragen stelle...?}
{407}{}{Gut zu wissen. Danke für die Information.}
{415}{}{Das war bei Nikki. Die arbeitet aber nicht mehr hier. Hat einfach ihren Kram gepackt und sich verdrückt, gar nicht
 lange her.}
{416}{}{Kann ich dir noch ein paar Fragen stellen...}
{417}{}{Gut zu wissen. Danke für die Information.}
{425}{}{Klar, ist gut fürs Geschäft. Die Garderobe ist da hinten...}
{426}{}{[Vorstellung geben.]}
{427}{}{Im Moment nicht. Ich hätte da ein paar andere Fragen...}
{428}{}{Nein nicht jetzt, aber ich komme später zurück.}
{435}{}{[Schüttelt den Kopf.] Nein, wir erholen uns grade noch von deiner letzten Show. Frag mal in den anderen Kasinos nach.}
{436}{}{Geht in Ordnung, danke. Pass mal auf, ich wollte dich noch was fragen...}
{437}{}{Okay...aber verlass dich drauf, ich komm wieder.}
{445}{}{Du zählst die Chips des Abends zusammen. Keine schlechte Ausbeute.}
{446}{}{Das mit dem Leder kam gut. }
{447}{}{Die Spielchen mit dem Ballknebel waren auch nicht von schlechten Eltern. }
{448}{}{Nächstes Mal wird's noch besser...}
{455}{}{Ja, der stinkt nach Brahminkacke, nur noch schlimmer. Und du willst trotzdem...? [Nimmt eine skeptische Musterung
 deiner Person vor.] Zum Teufel, warum eigentlich nicht. Kann nicht schaden, so eine kleine Showeinlage. Aber mit dem
 Publikum ist nicht zu spassen. Will hoffen, dass du's drauf hast.}
{456}{}{Klar hab ich's drauf...guck's dir einfach an.}
{1215}{}{, mein Herr.}
{1216}{}{, mein Herr.}
{1220}{}{, meine Dame.}
{1221}{}{, meine Dame.}
{1225}{}{, mein Herr.}
{1230}{}{, meine Dame.}
{1306}{}{. Mach mal Pause und amüsier dich. Die Welt kommt auch mal zwei Stunden ohne Retter aus.}
