{100}{}{}
{101}{}{}
{110}{}{Deine Füße jucken fürchterlich.}
{120}{}{Du entdeckst störende Schwellungen an jedem Fuß.}
{130}{}{Deine Schuhe sind plötzlich zu eng, diese Schwellungen entzünden sich.}
{140}{}{Diese Schwellungen an den Füßen scheinen sich zu einem sechsten Zeh auszuwachsen. Aber zumindest ist der ständige brennende Schmerz weg.}
{141}{}{Oh mein Gott, das ist ja Bess!}
{150}{}{Du erhältst }
{151}{}{ Erfahrungspunkte, weil du das GECK gefunden hast.}
