{100}{}{Du siehst ein Terminal.}
{101}{}{Du siehst das Sprachsteuerungs- Terminal.}
{102}{}{Du siehst ein Standard- Computerterminal, das für akustische Befehle eingerichtet wurde.}
{103}{}{Du untersuchst das Computerterminal, kannst aber nichts auffällig fehlerhaftes feststellen. Was machst du?}
{104}{}{Du wendest deinen "Spezialschlag" an.}
{105}{}{Du versetzt ihm einen Tritt, wo es weh tut.}
{106}{}{Du startest das Diagnoseprogramm.}
{107}{}{Du öffnest es und siehst dir das Ganze von innen an.}
{108}{}{Du lässt die Finger davon.}
{109}{}{Du siehst die Konsole eine Weile an und überlegst, wo du den Schlag am besten anbringst. Nachdem du zugeschlagen hast (mit Gewalt geht alles!), blinkt der Bildschirm ein paarmal auf, stabilisiert sich dann aber wieder. Sonst passiert nichts. Was machst du?}
{110}{}{Du versetzt ihm einen Tritt, wo es weh tut.}
{111}{}{Du startest das Diagnoseprogramm.}
{112}{}{Du öffnest es und siehst dir das Ganze von innen an.}
{113}{}{Du lässt die Finger davon.}
{114}{}{Diese bekannte Reparaturmethode bewirkt zum einen, dass der Bildschirm für einige Sekunden verrückt zu spielen scheint, sich dann aber wieder stabilisiert, und zu anderen ein Geräusch von zerbrechendem Metall. Die Abdeckung, der du den Tritt versetzt hast, fällt zu Boden. Was machst du?}
{115}{}{Du startest das Diagnoseprogramm.}
{116}{}{Das verdammte Ding ist offen, also kann man auch gleich reinsehen.}
{117}{}{Du lässt die Finger davon.}
{118}{}{Du bist sicher, dass im System einige Diagnoseroutinen verfügbar sein sollten. Doch die Eingabe über die Tastatur scheint deaktiviert zu sein. Die Einheit akzeptiert nur akustische Befehle. Was machst du?}
{119}{}{Das einzige, was dir übrig bleibt, ist, in den Computer reinzuschauen.}
{120}{}{Du lässt die Finger davon.}
{121}{}{Beim Untersuchen des Kabelgewirrs und der Platinen stellst du fest, dass das System absichtlich sabotiert wurde. Eine der Platinen, das Modul zur Stimmerkennung, ist völlig zerstört und muss ausgetauscht werden. Jetzt musst du nur noch ein Ersatzmodul finden.}
{122}{}{OK.}
{123}{}{OK.}
{124}{}{Du installierst das Modul im Terminal. Das System ist repariert.}
{125}{}{Es muss ein Modul zur Stimmerkennung installiert werden, bevor das Terminal wieder betriebsbereit ist.}
{126}{}{OK.}
{127}{}{Jetzt arbeitet das System einwandfrei.}
{128}{}{Aufzeichnungen des Überwachungssystems werden abgerufen. Holografische Wiedergabe wird gestartet...}
{129}{}{Du bist als letzter noch übrig, Gruthar. In Kürze wird der Schandfleck deines Geschlechts getilgt sein.}
{130}{}{Sag deinem sogenannten Präsidenten, dass er dafür in der Hölle schmoren wird.}
{131}{}{Was soll's. Letztendlich wart ihr doch nur sprechende Tiere.}
{132}{}{Das kann schon sein, aber wir sind bei euren Experimenten entstanden. Wir haben euch unsere Entstehung zu verdanken!}
{133}{}{Und nun versetze ich dir den Todesstoß.}
{134}{}{Nimm seine Leiche mit. Der Doktor wollte gerne ein Exemplar.}
{135}{}{Ihr Blut wird strömen wie die Wasser des Nils!}
