{100}{}{Du siehst eine hübsche junge Frau im Kampfanzug.}
{101}{}{Das ist Elise.}
{102}{}{Sie wirkt sehr sachlich und kühl. Sie ist es offensichtlich gewohnt, Befehle zu erteilen. Und sie geht davon aus, dass man ihr gehorcht.}
{103}{}{Was willst du?}
{104}{}{Du schon wieder?}
{105}{}{Karl hat mich hergeschickt.}
{106}{}{Doktor Jubilee meinte, ich soll mit dir reden.}
{107}{}{Wer bist du?}
{108}{}{Gah?}
{109}{}{Ich suche nach einer Gruppe von Leuten, die was gegen Sklaverei haben. Nennen sich New California Ranger.}
{110}{}{Kannst du mein Auto reparieren?}
{111}{}{Äh, ich dachte, hier gäbe es längst niemand mehr.}
{112}{}{Er wusste davon? Was hat er dir gesagt?}
{113}{}{Nicht viel. Das ihr gute Leute seid und dass ich mich euch vielleicht anschließen könnte.}
{114}{}{Er meinte, ihr zahlt ganz ordentlich.}
{115}{}{Ich bin Elise. Das ist Gond. Wir gehören zu einer "Gruppe", die sich für die Menschen einsetzt.}
{116}{}{Ihr seht nicht gerade nach Wohlfahrt oder Kirchengemeinde aus.}
{117}{}{Klingt interessant. Und wie sieht dieser Einsatz aus?}
{118}{}{Ich bräuchte jemanden, der mir mein Auto repariert.}
{119}{}{Mach, dass du hier wegkommst. Die Kneipe ist in der Dorfstraße.}
{120}{}{Die was gegen Sklaverei haben, aha. Sehr interessant. Und was würdest du machen, wenn du diese Gruppe findest?}
{121}{}{Ich würde mich ihr anschließen.}
{122}{}{Ich würde ihnen die Fresse polieren.}
{123}{}{Nichts.}
{124}{}{Geht dich nichts an. Und jetzt raus hier.}
{125}{}{Wir machen hier nicht mehr in Autos. Geschlossen, für immer. Wiedersehn.}
{126}{}{Falsch gedacht. Wiedersehn.}
{127}{}{Also gut, dann mal los. Was hältst du von Sklavenhändlern?}
{128}{}{Ich hasse sie. Ekelhafter, schmutziger Abschaum der Menschheit.}
{129}{}{Wenn sie mich in Ruhe lassen, lass ich sie auch in Ruhe.}
{130}{}{Ich habe Freunde, die sind selber welche.}
{131}{}{Du bist wohl ausschließlich scharf aufs Geld?}
{132}{}{Natürlich nicht. Ich glaube an die Wahrheit, die Gerechtigkeit und an den Kampf für die Unterdrückten,}
{133}{}{Es ist ein Anfang - bis jemand einen besseren Grund zum Kämpfen findet.}
{134}{}{Was gibt's denn sonst noch?}
{135}{}{Verarsch dich selber. Ich seh dir doch an, was du für einer bist. Auf Nimmerwiedersehen.}
{136}{}{Wenn du's nicht weißt, dann hat es keinen Sinn, dass ich mich mit dir abgebe. Tschüss.}
{137}{}{Nein, wir sind keine religiöse Organisation. Darf ich dir ein paar Fragen stellen?}
{138}{}{Klar, nur zu.}
{139}{}{Nur nicht so hastig. Wenn du bei den Rangern aufgenommen werden willst, musst du erst mal eine Prüfung absolvieren.}
{140}{}{Kein Problem. Schieß los.}
{141}{}{Eine Prüfung? Sind wir hier in der Schule oder was?}
{142}{}{Unmittelbar vor der Stadt gibt es einen Sklavenhändler. Kann sein, dass du an seinem Haus vorbeigekommen bist. Befreie die Sklaven, die dort gehalten werden und komm anschließend wieder her.}
{143}{}{Das mach ich glatt.}
{144}{}{Kommt nicht in Frage. Ich will hier keinen Ärger machen.}
{145}{}{Na, heute ist dein Glückstag.}
{146}{}{Genau das ist die Haltung, durch die die Greuel der Sklaverei überhaupt erst möglich werden. Tut mir leid, aber jemanden wie dich können wir in unserer Organisation nicht gebrauchen.}
{147}{}{OK.}
{148}{}{Also, hast du's dir anders überlegt? Willst du beweisen, dass du etwas taugst?}
{149}{}{Sicher.}
{150}{}{Was soll ich gleich noch mal machen?}
{151}{}{Hattest du nicht etwas zu erledigen? Komm erst wieder her, wenn du mit der Arbeit fertig bist.}
{152}{}{Ich hab's schon gehört. Du hast die Sklaven befreit. Gut gemacht! Bist du jetzt bereit, ein Ranger zu werden?}
{153}{}{Ja.}
{154}{}{Nein.}
{155}{}{Ich habe gehört, dass du es warst, der die Sklaven vor den Toren der Stadt befreit hat. Das war eine gute Tat. Lass mich dir die Hand reichen.}
{156}{}{Danke.}
{157}{}{Ganz einfach. Unser Ziel ist, die Sklaverei auszurotten und dafür tun wir alles. Wir haben in der NCR eine Menge einflussreicher Freunde und ihnen verdanken wir, dass die Sklaverei im Süden bereits verboten ist. Jetzt wollen wir das gleiche auch im Norden durchsetzen.}
{158}{}{Ich werde stolz darauf sein, zu den Rangern zu gehören. Nehmt mich bei euch auf.}
{159}{}{Interessant... Ich werde mir das mal durch den Kopf gehen lassen.}
{160}{}{Schwörst du, bei jeder sich bietenden Gelegenheit gegen die Sklaverei zu kämpfen und deinen in Not geratenen Rangerkameraden beizustehen?}
{161}{}{Ja.}
{162}{}{Nein.}
{163}{}{Glückwünsche, du bist jetzt ein Ranger.}
{164}{}{Sei gegrüßt, Rangerkamerad. Ich fürchte, hier ist momentan nicht allzuviel für dich zu tun. Die meisten unserer Leute sind auf Patrouille. Ich mach bekannt, dass du jetzt zu uns gehörst. Ich will ja nicht, dass du von den eigenen Leuten erschossen wirst.}
{165}{}{Wir sind immer auf der Suche nach neuen Leuten, die unsere Sache unterstützen. Solltest du's dir noch mal überlegen, komm einfach zu mir. Bist du dir sicher, dass du dir die Gelegenheit entgehen lassen möchtest?}
{166}{}{Ganz sicher.}
{167}{}{Jetzt wo du's sagt, denk ich mir, ich wär wohl doch ganz gern ein Ranger.}
{168}{}{Ich verstehe. Also, ich vertrete eine Gruppe, die unter dem Namen New California Ranger bekannt ist. Jemand mit deinen Ansichten käme für eine Mitgliedschaft in Frage. Wärst du daran interessiert?}
{169}{}{Ausgezeichnet! Ich bin dabei.}
{170}{}{Klingt interessant. Was kannst du mir über die Ranger erzählen?}
{171}{}{Ich verstehe. Ich danke dir, dass du vorbeigekommen bist, aber ich glaube nicht, dass wir uns noch etwas zu sagen haben. Wenn du's dir anders überlegst, komm einfach wieder her.}
{172}{}{OK.}
{173}{}{Wenn das so ist, muss ich dich auffordern, mir aus den Augen zu gehen. Und zwar sofort!}
{174}{}{OK.}
{175}{}{Ein Sklavenhändler! Mach, dass du dich hier verpisst, sonst puste ich dir deine Tätowierung mit 'ner Kugel weg!}
{176}{}{Sicher.}
{177}{}{Versuch's!}
{178}{}{Wir haben in einigen Städten im Norden Agenten und Sympathisanten. Wir werben für unsere Auffassungen und knöpfen uns alle Sklavenhändler vor, deren wir habhaft werden können.}
{179}{}{Tag. Hast du's dir noch mal überlegt von wegen deiner Mitgliedschaft bei uns?}
{180}{}{Macht nichts.}
{181}{}{Das gehört dir nicht. Jetzt geh, sonst muss ich sehr unhöflich werden.}
{182}{}{Ich weiß nicht, was du mit Gond angestellt hast, aber es wird dich teuer zu stehen kommen!}
