{100}{}{Du siehst einen hageren alten Mann mit einem Füllfederhalter hinterm Ohr und einer
 Nickelbrille auf der Nasenspitze.}
{101}{}{Das ist Vortis, der Inhaber dieses Sklavenpferchs.}
{102}{}{Er hat ungefähr drei Zähne. Seine Finger und sein Hemd sind mit blauer Tinte bekleckert.
 Auf seiner Stirn ist eine stark ausgeblichene Sklavenhändlertätowierung zu erkennen.}
{103}{}{Was willst du hier?}
{104}{}{Willkommen, Bruder, in Vortis' Halle. Womit kann ich dienen?}
{105}{}{Du fängst an mir auf die Nerven zu gehen.}
{106}{}{Dieser Sklavenpferch hier gehört mir und ich, Vortis, betreibe hier ein ehrliches und
 rechtmäßiges Geschäft, egal was sie dir in der NCR erzählen. Da innerhalb der NCR keine Sklaven
 erlaubt sind, betreue ich die Sklaven von Leuten, die dort zu tun haben.}
{107}{}{Bist du nicht ganz bei Trost? Das hier ist ein Sklavenpferch. Ich habe eine Lizenz dafür.}
{108}{}{}
{109}{}{Nur ein paar Fragen.}
{110}{}{Ich such Arbeit.}
{111}{}{Uh?}
{112}{}{Nix Klo? Ich gehn.}
{113}{}{Was ist das hier?}
{114}{}{Nichts. Bin hier falsch.}
{115}{}{Ach, sieh einer an - mit einem waschechten Tugendbold haben wir's hier zu tun. Leute,
 schafft mir diesen heuchlerischen Ausbund an Rechtschaffenheit aus den Augen!}
{116}{}{Scheiß drauf.}
{117}{}{Also?}
{118}{}{Ich bin auf der Suche nach Vault 13.}
{119}{}{Hast du ein GECK?}
{120}{}{Was kannst du mir über die Stadt erzählen?}
{121}{}{Du schmutziger Sklavenhändler! Was hindert mich daran, dich zu töten?}
{122}{}{Ich hab da von diesen Typen gehört, den New California Rangern. Hattest du
 irgendwelchen Ärger mit denen?}
{123}{}{Stört es, wenn ich mich ein bisschen hier umschaue?}
{124}{}{Arbeit? Ich... ich hätte da eventuell was für dich. Schon mal was von den
 New California Rangern gehört?}
{125}{}{Ja.}
{126}{}{Nein.}
{127}{}{Drecksack. Leute, schafft mir diesen Quälgeist aus den Augen.}
{128}{}{Lass mich in Ruh'!}
{129}{}{Vault 13! Raus hier. Alles erstunken und erlogen. Vault 13, dass ich nicht lache!}
{130}{}{Noch eine Frage...}
{131}{}{Besten Dank für nichts.}
{132}{}{Wie bitte? Was immer das sein soll, ich hab's nicht.}
{133}{}{Noch eine Frage...}
{134}{}{Besten Dank für nichts.}
{135}{}{New California Republic - alles nur Enthaltsamkeitsspinner und Kaufleute. Haben was
 gegen Sklavenhändler und Sklaverei. Zum Teufel, was soll's, ich mach dadurch meine Geschäfte.}
{136}{}{Noch eine Frage...}
{137}{}{Danke, muss gehen.}
{138}{}{Da hat dich jemand aufs Glatteis geführt. Ich hab keine Probleme mit niemandem und schon
 gar nicht mit irgendwelchen Rangern. Was ich hier tue, ist völlig legal. Mir kann keiner was
 anhaben.}
{139}{}{Noch eine Frage...}
{140}{}{Wie du meinst. Ich gehe.}
{141}{}{Ja, ich hab da so meine eigene Auffassung, was die Ranger anbelangt. Suchst du Arbeit?}
{142}{}{Ja.}
{143}{}{Nein.}
{144}{}{Nein, du schnüffelst mir hier nicht rum, Vollidiot! Ist doch kein Museum hier!}
{145}{}{Noch eine Frage...}
{146}{}{Mit dir komm ich nicht klar. Ich gehe.}
{147}{}{Also gut. Du musst wissen, dass es Leute gibt, die sie als mögliches Problem ansehen. Es
 wäre ausgesprochen gut, wenn wir eine Karte hätten, auf der ihre geheimen Unterschlupfe im
 Norden verzeichnet sind - New Reno, Klamath und so. Ich wäre bereit, sagen wir, 500 Dollar für
 so was zu zahlen. Meinst du, du kannst mir so eine Karte beschaffen?}
{148}{}{Sicher.}
{149}{}{Ich glaube nicht.}
{150}{}{Dann hör mir mal gut zu. Diese Ranger haben es sich in den Kopf gesetzt, die Sklaverei
 und die Sklavenhändler auszurotten - mit Gewalt. Das wird allmählich zu einem echten Problem
 für Leute wie mich, die nur ihren Geschäften nachgehen wollen.}
{151}{}{Sie arbeiten im verborgenen, besonders oben im Norden.}
{152}{}{Heiliger Bimbam, dir muss man wohl alles haarklein auseinandersetzen! Sie überfallen die
 Sklavenhändler und schmuggeln die Ware in in Süden, in das Gebiet der NCR, wo Sklaverei verboten
 ist. Also, wie steht's, bist du interessiert?}
{153}{}{Da gibt es kein "Und"! Willst du den Job, oder willst du ihn nicht?}
{154}{}{Oh-oh...}
{155}{}{Also, was soll ich machen?}
{156}{}{Schön. Wenn du die Karte hast - du findest mich hier.}
{157}{}{Wo finde ich denn so eine Karte?}
{158}{}{Na gut. Aber ich hätte da noch ein paar Fragen.}
{159}{}{Geht schon los. Wir sehen uns.}
{160}{}{Woher zum Teufel soll ich das wissen? Wenn ich's wüsste, dann hätte ich die Karte schon
 längst! In der Stadt gibt es angeblich eine Zelle. Die musst du erst mal finden. Dann kannst du
 weitersehn.}
{161}{}{Nur noch ein paar kleine Fragen.}
{162}{}{Also gut, es geht los.}
{163}{}{Da bist du ja schon wieder! Hast du die Karte?}
{164}{}{Ja.}
{165}{}{Nein.}
{166}{}{Ich warte immer noch drauf, dass du den ersten Auftrag zu Ende bringst!}
{167}{}{Ach ja, das hatte ich ganz vergessen.}
{168}{}{Nicht mehr, seit du deinen Auftrag ausgeführt hast. Danke.}
{169}{}{Nur noch ein, zwei Fragen.}
{170}{}{Kein Problem. Tschüss.}
{171}{}{Gute Arbeit. Ich würde dir raten, dich ein bisschen im Hintergrund zu halten, falls diese
 Ranger jemals dahinterkommen.}
{172}{}{So machen die Geschäfte richtig Spaß.}
{173}{}{Häng hier nicht rum, du Trottel, sonst schöpft noch jemand Verdacht.}
{174}{}{Schon gut, ich hab's gefressen.}
{175}{}{Ach du Sch...! Wache! Hier ist ein Eindringling!}
{176}{}{Wenn du hier reingehst, zieh ich dir das Fell über die Ohren. Verstanden?}
{177}{}{Es ist schon spät und wir haben geschlossen. Komm morgen früh wieder.}
