{100}{}{Du siehst einen älteren Mann mit tiefen Furchen im Gesicht. Er lässt sich nicht anmerken,
 ob er mitkriegt, dass du ihn ansiehst.}
{101}{}{Du siehst Cassidy.}
{102}{}{Du siehst einen älteren Mann mit tiefen Furchen im Gesicht. Er nickt dir zu.}
{103}{Cas0103}{Well, now. I ain't seen you around before, stranger. Name's Cassidy. I run this place. What can I do for you?}
{104}{Cas0104}{Well now, if it ain't the mysterious stranger. What can I do for you today?}
{105}{}{Urg nurg?}
{106}{}{Verzieh dich}
{107}{}{Ich suche die Vault.}
{108}{}{Du suchst einen Weg hier raus?}
{109}{}{Was gibt's denn hier im Ausschank?}
{110}{}{Ist hier irgendwas Interessantes los?}
{111}{}{Heute nichts, danke.}
{112}{Cas0112}{Hit on the head a little too often, eh? Sorry, I don't speak imbecile.}
{113}{}{Wack-köff?}
{114}{Cas0114}{Vault? Only Vault I know of is the one inside the city. Big friggin' hole... you can't miss it, trust me.}
{115}{}{Was hast du für Drinks auf Lager?}
{116}{}{Ist hier irgendwas Interessantes los?}
{117}{}{Danke für die Beschreibung. Tschüss.}
{118}{Cas0118}{Beer for $20, shot of whiskey for $30. Nothing special. Why, you want something?}
{119}{}{Ich suche die Vault.}
{120}{}{Ich nehm ein Bier.}
{121}{}{Ich nehm einen Whisky.}
{122}{}{Ist hier irgendwas Interessantes los?}
{123}{}{Nee, eigentlich nicht. Trotzdem Danke.}
{124}{Cas0124}{"Interesting?" Heh. Friend, Vault City ain't an "interesting" place... unless the guards get bored, then you
 better take cover. Why you asking? You looking for something in this sinkhole?}
{125}{}{Was hast du für Drinks auf Lager?}
{126}{}{Ich suche die Vault.}
{127}{}{So schlimm wird's wohl auch wieder nicht sein hier.}
{128}{}{Nee, eigentlich nicht. Trotzdem Danke.}
{129}{Cas0129}{Here you go. Drink up. It might help you forget where you are.}
{130}{}{So schlimm kann's hier doch wohl auch nicht sein.}
{131}{}{Danke für den Drink. Ich muss jetzt gehen.}
{132}{Cas0132}{Oh, really? Well, hell then, I must be mistaken, considering YOU'RE the authority and all. Guess you must have been napping during the raid last week?}
{133}{}{Razzia?}
{134}{Cas0134}{Aw, yeah, a beautiful sight it was. A guard patrol broke in here looking for "illegal substances." They busted down the door, busted up my stock, then busted up a few of my customers, too.}
{135}{}{Und was passierte dann?}
{136}{}{Tut mir echt leid. Bis später.}
{137}{Cas0137}{After they hauled away this one guy, Joshua, for resisting arrest, they fined my ass for finding - get this - REAL whiskey on the premises. Nevermind that I got a permit from Stark three months before. Bastards.}
{138}{}{Wow! Was du nicht sagst.}
{139}{}{Tut mir echt leid. Bis später.}
{140}{Cas0140}{It gets better. Now I'm in debt to the guards for the fine, an' I had to buy a new case of alcohol from a merchant at triple my standard rate. I'm expecting the guards to come knocking again soon, just to bust my chops. }
{141}{}{Wie läuft es denn normalerweise?}
{142}{}{Na, hoffentlich läuft's demnächst wieder besser. Tschüss.}
{143}{Cas0143}{Even the good days ain't worth a damn. The Citizens don't drink much, so I'm stuck here pouring drinks for merchants. The next cheap sonuvabitch who haggles for a drink is going to be wearing his ass as a hat.}
{144}{}{Warum bist du noch hier, wenn dich das alles so annervt?}
{145}{}{Tut mir echt leid. Ich such eine Vault. Kannst du mir helfen?}
{146}{}{Tut mir echt leid. Hoffentlich geht's bald wieder bergauf.}
{147}{Cas0147}{I have a bad heart. Need cardio booster shots to keep it beating. This city's the only place to get real medical care, so I thought I'd settle here, try and make a living.}
{148}{}{Hört sich so an als ob du echt genug hättest.}
{149}{}{Verstehe. Hör mal, ich suche eine Vault. Kannst du mir da weiterhelfen?}
{150}{}{Hoffentlich läuft's von jetzt an wieder besser. Tschüss.}
{151}{Cas0151}{Makes me want to close up shop and let this City rot. Screw 'em all.}
{152}{}{Warum haust du nicht einfach ab?}
{153}{}{Tut mir echt leid. Hoffentlich läuft's bald wieder besser.}
{154}{Cas0154}{Go into the wastes by myself? Ha! I'm sick of this place, but I ain't stupid.}
{155}{}{Ich verschwinde wieder. Warum kommst du nicht mit mir?}
{156}{}{Na ja, dann viel Glück.}
{157}{Cas0157}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{158}{Cas0158}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{159}{Cas0159}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{160}{Cas0160}{Naw... you look like you got enough of a crowd already.}
{161}{}{Alles klar. Viel Glück.}
{162}{}{Dann vergiss es einfach, du Penner. Dann bleib doch Barkeeper in dieser Miststadt.}
{163}{}{Na, dann nicht. Dein Pech.}
{164}{Cas0164}{Heh. You serious?}
{165}{}{Klar. Warum denn auch nicht? Siehst aus, als ob du ein guter Kämpfer wärst.}
{166}{}{Andererseits: Da draußen ist es ganz schön gefährlich, besonders für jemanden mit
 Herzproblemen. Hier bist du wohl sicherer.}
{167}{Cas0167}{All right, count me in.}
{168}{}{Lass uns die Sache angehen.}
{169}{}{}
{170}{}{}
{171}{Cas0171}{What's up? You got that "I need to tell you something you might not like" look again.}
{172}{Cas0172}{Yeah?}
{173}{Cas0173}{What's up? You got that "I'm pulling rank" look again.}
{174}{}{Ich wollte dich was fragen...}
{175}{}{Sieht aus, als ob du was abgekriegt hättest. Nimm paar Stimpaks und heil dich.}
{176}{}{Cassidy, warte hier auf mich.}
{177}{}{Leg deine Waffe weg.}
{178}{}{Bleib dicht bei mir.}
{179}{}{Bleib in meiner Nähe aber entferne dich nicht allzu weit von mir.}
{180}{}{Wir sollten uns ein bisschen verteilen.}
{181}{}{Los, Cassidy. Zeit, die Fliege zu machen.}
{182}{}{Nichts, schon gut.}
{261}{Cas0261}{You want me to put a bullet in Myron's head, is that it? It'd be no trouble. Just give the word.}
{262}{Cas0262}{What's on your mind?}
{263}{}{Warum möchtest du Myron umlegen?}
{264}{}{Mit was für Waffen kannst du umgehen?}
{265}{}{Ehrlich gesagt, möchte ich, dass du was anderes tust...}
{266}{}{Ehrlich gesagt, hätte ich da was, das du tun sollst...}
{267}{}{Vergiss es. Los, weiter.}
{268}{}{Nein, tu Myron nichts. Jedenfalls heute nicht. Ich werd dich auf dem laufenden halten.}
{269}{Cas0269}{Well, shotguns and rifles, mostly... just personal preference. I ain't a bad shot with pistols, neither.}
{270}{}{Noch irgendwas?}
{271}{}{OK. Ich hätt da noch ein paar Fragen...}
{272}{}{Alles klar. Wollte ich nur mal wissen.}
{273}{Cas0273}{If you ever need to learn somebody some manners up close and personal, slip me some brass knuckles, and I can tapdance on their face with my fists.}
{274}{}{Super. Sonst noch was?}
{275}{}{OK. Ich hätt da noch ein paar Fragen...}
{276}{}{Alles klar. Wollte ich nur mal wissen.}
{277}{Cas0277}{Uh, well... just between you and me, I can also use a spear pretty good. Me and my buddies used to hunt radscorpions with spears way back when... fact I'm alive and they ain't might tell you something.}
{278}{}{Nicht schlecht, wenn man mit einem Speer umgehen kann.}
{279}{}{OK. Ich hätt da noch ein paar Fragen...}
{280}{}{Alles klar. Wollte ich nur mal wissen.}
{281}{Cas0281}{Says you. Just don't be calling me no tribal, and we'll get along just fine.}
{282}{Cas0282}{Don't want people mistaking me for ol' Bone-nose over there. Heh-heh. I ain't never seen no tribal do something as dumb as jam a bone in his nose.}
{283}{Cas0283}{Of course there isn't. Spear's a fine weapon. Lots of tribal friends of mine use 'em.}
{284}{}{Wusstest du, dass ich aus einer Sippe stamme?}
{285}{}{Hmmm. Hör mal, ich hätt da noch ein paar andere Fragen...}
{286}{}{Alles klar. Danke für die Auskunft.}
{287}{Cas0287}{Aw, don't be playing with ol' Cassidy now. You ain't no tribal.}
{288}{}{Doch, bin ich.}
{289}{}{Was soll's. Hör mal, ich hätte da noch ein paar andere Fragen...}
{290}{}{Vergiss es. Darüber möcht ich mich im Moment nicht weiter mit dir unterhalten.}
{291}{Cas0291}{Uh, well... damn it all, you can have my apology right here and now. I didn't mean any offense.}
{292}{}{Ja gut, glaub ich dir. Hör mal, ich hätte da noch ein paar Fragen...}
{293}{}{Vergiss es. Lass uns aufbrechen.}
{294}{Cas0294}{Well, now, before you go, I got a question for you. What are we doing out here? We seem to be running all over the place looking for something. Have we got some sort of plan?}
{295}{}{Wir suchen nach einem GECK - einem Garden-Eden-Creation-Kit. Mein Dorf braucht es, um
 seine Felder zu retten.}
{296}{}{Wir gehen zur Vault und bringen dann das GECK in mein Dorf.}
{297}{}{Meine Leute wurden verschleppt. Ich versuche herauszufinden, was mit ihnen passiert ist.}
{298}{Cas0298}{Them things come in kits now, huh? Man, the good book don't mention that, does it? Well, all right then. Let's get hunting.}
{299}{Cas0299}{Huh. All right then, just checking.}
{300}{Cas0300}{I wouldn't mind plugging a few holes in some kidnappers. A little frontier justice never hurt anyone... well, at least not me.}
{301}{}{Alles klar. Auf geht's!}
{302}{Cas0302}{The things that little cuss says ain't fit for decent ears.}
{303}{Cas0303}{Especially a woman's.}
{304}{}{Oha, Cassidy. Hätte nicht geglaubt, dass dir sowas was ausmacht. Ich krieg ja
 Herzflattern.}
{305}{}{Also? Was willst du damit sagen?}
{306}{}{Also weißt du: Du fluchst auch ziemlich oft, Cassidy.}
{307}{}{Als ob ich das nicht wüsste... Lass uns aufbrechen.}
{308}{Cas0308}{Yeah, but when I do it, it's got style. He's just a little trash mouth.}
{309}{Cas0309}{And I don't like the way he looks at you, neither.}
{310}{}{Oha, Cassidy. Hätte nicht geglaubt, dass dir sowas was ausmacht. Ich krieg ja
 Herzflattern.}
{311}{}{Also? Was willst du damit sagen?}
{312}{}{Als ob ich das nicht wüsste... Lass uns aufbrechen.}
{313}{Cas0313}{Now hold on, I didn't mean it like that.}
{314}{Cas0314}{All I'm saying is that bona fide little asshole's gonna get his number clocked one day when it's just me and him and a hole in the desert.}
{315}{}{Das Leben kann schon ein harter Lehrmeister sein. Ich hätt da noch ein paar Fragen an
 dich...}
{316}{}{Er muss jetzt sowieso jeden Augenblick dran glauben. Darüber würde ich mir keine Sorgen
 machen.}
{317}{}{Beruhige dich schon, Cassidy. Lass Myron in Ruhe.}
{318}{}{Ich hasse diesen Ort.}
{319}{}{Ich hatte gehofft, wir wären endgültig von hier weggekommen.}
{320}{}{Stadt der Dummgesichter...}
{321}{}{Sieht hier ja noch schlimmer aus als in Vault City.}
{322}{}{Gut, dass ich meine Waffen durchgecheckt habe, bevor ich hier reinkam.}
{323}{}{Falls ich den Löffel abgebe: Hier will ich nicht begraben sein.}
{324}{}{Haltet hier bloß die Augen auf. Die Einwohner hier sind nicht allzu freundlich.}
{325}{}{Heh! Ich hätte nie gedacht, dass ich jemals nach San Francisco kommen würde.}
{326}{}{Hätte nie geglaubt, dass ihr 'n Oldtimer wie mich soweit mitschleppen würdet. Lass uns die
 Sache zu Ende bringen und nach Hause gehen.}
{327}{}{Redding ist eine Bergbaustadt. Hauptsächlich Gold. Von hier aus sind früher immer eine
 Menge Karawanen nach Vault City gekommen.}
{328}{}{Broken Hills ist eine Bergbausiedlung... hauptsächlich Uranerz. Kann hier ziemlich rauh
 zugehen. Passt lieber auf.}
{329}{}{Ich habe Gift im Körper. Hast du ein Gegenmittel?}
{330}{}{Ich strahle wie 'ne Leuchtreklame. Hast du ein Anti-Strahlen-Mittel?}
{331}{}{Ich habe hier ziemlich üble Schmerzen. Hast du Stimpaks dabei?}
{332}{}{Halt dich bloß bedeckt, Myron. Ich hab dich im Auge.}
{333}{}{Wenn du aus der Reihe tanzt, Myron, kriegst du von mir eins auf den Deckel.}
{334}{}{Verdammt, Lenny, du brauchst ein Bad. Oder eine Dosis Desinfektionsmittel.}
{335}{}{Ghul-Boy, bleib mir bloß vom Leib. Iiiihhh-gitt, du stinkst ja vielleicht.}
{336}{}{Das ist der fieseste Hund, den ich je gesehen habe.}
{337}{}{Nur die Ruhe, Fifi. Komm mal her zum lieben Cassidy.}
{338}{}{Wovon lebt dieser Cyberhund eigentlich? Wahrscheinlich von Menschenfleisch.}
{339}{}{Wenn der Cyberhund mir ans Bein pinkelt, bring ich ihn um.}
{340}{}{Ahhhh. Junge, bin ich froh, dass die Millionen von den Dingern hergestellt haben, bevor
 die Bombe runterging.}
{341}{}{Danke, mein Freund.}
{342}{}{Hoffentlich kriegt mein Herz nichts ab, wenn ich diese Stimpaks nehme...}
{343}{}{Was ist d--?! Nein! mein Herz! Ich... *hrrrkkk*.}
{344}{}{Tschuldige, ich hab nur die Aussicht bewundert.}
{345}{}{Verdammt, ich stell mich jetzt einfach hierhin.}
{346}{}{Tut mir leid. Ich wollte dir nicht den Weg versperren.}
{347}{}{Ahhhhh. Das hat's gebracht. Herzlichen Dank.}
{348}{}{*Hick* Hä-hä. Nichts bringt den Kreislauf besser in Schwung als gutes altes Feuerwasser.}
{349}{}{Danke. Verdammt, du solltest auch 'nen Schluck nehmen.}
{350}{}{Das ist die Vault. Ziemlich dickes Ding, was?}
{351}{}{Möchtest du, dass ich wieder mitmache?}
{352}{}{Ich bin bereit loszuziehen, wann immer du möchtest.}
{353}{}{Bist du sicher, dass du keine Hilfe brauchst?}
{354}{}{Ich brenne drauf, aufzubrechen.}
{355}{}{Klar könnte ich jetzt eine rauchen.}
{356}{}{Paps hat mich nach so 'ner Comicfigur von vorm Krieg benannt. Sagte, der wär auch so 'n
 gemeiner Dämlack gewesen.}
{357}{}{Tut gut, wieder unterwegs zu sein. In Vault City habe ich Magengeschwüre gekriegt.}
{358}{}{Hoffentlich spielt mein Herz nicht verrückt, während wir unterwegs sind. }
{359}{}{Klar könnt ich 'n Drink gebrauchen.}
{360}{}{Ich check lieber noch mal meine Ausrüstung durch.}
{361}{}{Verdammtes Rheuma...}
{362}{}{Wenn ich zwanzig Jahre jünger wär, würd ich nach Osten gehen und mir den Mittleren Westen
 ansehen. Jetzt ist's dazu wohl zu spät.}
{363}{}{Hab gehört, dort hätte es kilometerbreite Wirbelstürme gegeben. Ist heute nur noch ein
 riesiger alter radioaktiver Mülleimer.}
{364}{}{Möcht wissen, ob Texas den Krieg überlebt hat.}
{365}{}{Danke, Freund. Ich... boahhh. Ich seh auf einmal alles so verschwommen.}
{366}{}{Ich habe gehört, dieses Zeug macht Halluzina... boah! Wo zum Teufel kommen auf einmal
 diese ganzen Schlangen her?! }
{367}{}{Jedesmal, wenn ich das Zeug nehme, kriege ich Flashbacks.}
{368}{}{Die altmodischen Heilmethoden der Sippen haben's echt in sich...}
{369}{}{Ich brauch hier ein paar Krücken und einen Rollstuhl.}
{370}{}{Cassidy stirbt an 'nem Herzinfarkt.}
{371}{}{Du hast Cassidy dazu überredet, sich der Gruppe anzuschließen.}
{372}{}{Lass mich erstmal ne Tablette einschmeißen...}
{1000}{Cas1000}{Well... all right, then. I'll wait here 'til you get back. }
{1100}{Cas1100}{Sure. Can't promise I won't pull it out again if there's trouble, though.}
{1200}{Cas1200}{All right, I'll stick close to you then. You must be expecting trouble.}
{1300}{Cas1300}{All right, I'll keep some distance. Get a better vantage point that way.}
{1400}{Cas1400}{All right, I'll be watching your back. You need me, holler, and I'll come running.}
{2000}{Cas2000}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{2100}{Cas2100}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{2200}{Cas2200}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{2300}{Cas2300}{Naw... you look like you got enough of a crowd already.}
{2400}{Cas2400}{All right, then.}
{2999}{}{Alles klar. Dann mach's mal gut.}
{3000}{}{Lass uns aufbrechen.}
{3100}{}{Dann vergiss es einfach wieder, du Armleuchter.}
{3200}{}{Na, dann nicht. Dein Pech.}
{4100}{Cas4100}{Okay, everything's stitched up. I'm good to go.}
{4200}{Cas4200}{Okay, pretty much everything is patched up.}
{4300}{Cas4300}{That pretty much did it, but I could use a couple more stims.}
{4400}{Cas4400}{I used what I could, but I'm still pretty messed up. If you got any more stims to spare, I could sure use 'em. I can still walk, though.}
{9999}{}{Ich wollte dich was fragen...}
{10001}{}{Nimm paar Stimpaks und heil dich selbst.}
{10002}{}{Cassidy, warte hier auf mich.}
{10003}{}{Leg deine Waffe weg.}
{10004}{}{Bleib dicht bei mir.}
{10005}{}{Bleib in meiner Nähe aber entferne dich nicht allzu weit von mir.}
{10006}{}{Wir sollten uns ein bisschen verteilen.}
{10007}{}{Wir sollten jetzt aufbrechen.}
{10100}{}{Los, Cassidy. Zeit, die Fliege zu machen.}
{20000}{Cas20000}{All right, I'm listening.}
{20001}{Cas20001}{My gear? What about it?}
{20002}{Cas20002}{No problem. Too hot for that kinda gear, anyway. Makes me sweat like a New Reno whore.}
{20003}{}{Lass uns mal eine andere Anordnung ausprobieren.}
{20004}{}{Ich muss mit dir über deine Ausrüstung reden.}
{20005}{}{Kannste vergessen. Wir bleiben bei der selben Anordnung wie immer.}
{20006}{}{Schon gut. Ich muss gar nichts über deine Sachen wissen.}
{20007}{}{Du musst diese Rüstung da ausziehen.}
