{100}{}{Du siehst einen kräftigen, schmutzigen Mann.}
{101}{}{Du siehst Connar.}
{102}{}{Hey you! What are you doing!}
{103}{}{Bleib erst mal da stehen, Wanderer. Was willst du hier?}
{104}{}{I'm killing off the monsters here.}
{105}{}{Was juckt's dich?}
{106}{}{Geht dich nichts an.}
{107}{}{I bet those bastards at Vault City sent you. Well you best be off, and leave everything else
 alive.}
{108}{}{Dafür ist's ein bißchen zu spät.}
{109}{}{Warum?}
{110}{}{Tut mir leid, habe einen Auftrag zu erledigen.}
{111}{}{Those creatures are the only thing that are stopping Vault City from making us their so-called
 servants.}
{112}{}{Well they're paying me to get rid of the monsters, and that's what I'm going to do.}
{113}{}{Das hat mir niemand gesagt.}
{114}{}{Sie bezahlen mich, um sie loszuwerden, und die Arbeit ist erledigt.}
{115}{}{Du Idiot! Warum machst du sowas, verdammt noch mal.}
{116}{}{Ich brauche das Geld.}
{117}{}{Die werden kommen und uns holen, wenn du das machst.}
{118}{}{Nicht mein Problem.}
{119}{}{Hoffentlich erstickst du dran. Die werden schon sehr bald hier auftauchen und uns
 abschleppen.}
{120}{}{Ich wußte nicht, daß die mir deshalb den Auftrag gegeben haben.}
{121}{}{Mag schon sein. Aber ich laß mir von Gesocks wie dir trotzdem nichts sagen.}
{122}{}{Wir können das nicht zulassen.}
{123}{}{Tu, was du nicht lassen kannst.}
{124}{}{Du hast denen das einfach so geglaubt? Da mußt du aber noch einiges über das Leben
 lernen, mein Freund.}
{125}{}{Kann ich euch denn irgendwie helfen?}
{126}{}{Die Jungs aus Vault City sind ziemliche Feiglinge. Wenn du denen ein bißchen Angst
 einjagst, rennen die wie die Karnickel. Mit ein paar Waffen könnten wir sie uns bestimmt
 vom Leib halten.}
{127}{}{What sort of guns?}
{128}{}{Nun, ich kann gut mit einer Schrotflinte umgehen, und wir haben hier drinnen einige Leute,
die mit einem Gewehr umgehen können. Ich denke, drei davon müssten reichen.}
{129}{}{Ich werd sehen, was ich tun kann.}
{130}{}{Du bist hier unerwünscht. Los verschwinde.}
{131}{}{Ich hab's mir anders überlegt. Wie kann ich euch helfen?}
{132}{}{Hör zu, die wirst hier trotzdem gleich verschwinden.}
{133}{}{Du kannst mich mal.}
{134}{}{Da bist du ja wieder! Hast du die Gewehre mitgebracht?}
{135}{}{Was sollte ich noch mal mitbringen?}
{136}{}{Ja. Hier sind sie.}
{137}{}{We need three rifles and a shotgun. The sooner you can get them to us, the better.}
{138}{}{OK.}
{139}{}{With these, we'll be able to make something of this place over the next months. If you ever need
 a place to rest, you will always be welcome here.}
{140}{}{Gern geschehen.}
{141}{}{Welcome back. Things are going well. We're going to work on expanding the Village.}
{142}{}{Hallo, da bist du ja wieder! Hier bei uns ist es gut vorangegangen, wie du siehst. Schau
 dich mal um, wenn du 'n bißchen Zeit hast.}
{143}{}{Wir sind dauernd am Bauen. Wir hoffen, daß wir bis nächsten Monat das Dorf wieder ein
 Stück erweitert haben.}
{144}{}{Greetings! The village has expanded again as we have hoped. You are welcome as always.}
{145}{}{We have nothing to fear from Vault City any longer, and will be able to live here in peace.
 Thank you again, wanderer.}
{146}{}{Hör einfach auf, da draußen irgendwas zu töten, du Einfaltspinsel.}
