{100}{}{Du siehst einen kräftigen, schmutzigen Mann.}
{101}{}{Du siehst Connar.}
{102}{}{He, du! Was tust du da?!}
{103}{}{Bleib erst mal da stehen, Wanderer. Was willst du hier?}
{104}{}{Ich beseitige die ganzen Monster.}
{105}{}{Was juckt's dich?}
{106}{}{Geht dich nichts an.}
{107}{}{Ich möchte wetten, die Bastarde aus Vault City haben dich geschickt. Am besten
 verschwindest du und lässt alle am Leben.}
{108}{}{Dafür ist's ein bisschen zu spät.}
{109}{}{Warum?}
{110}{}{Tut mir leid, habe einen Auftrag zu erledigen.}
{111}{}{Diese Kreaturen sind das einzige, das Vault City davon abhält, uns zu ihren sogenannten
 "Dienern" zu machen.}
{112}{}{Hör mal, sie bezahlen mich dafür, ihnen diese Viecher vom Hals zu schaffen, und genau das mache ich.}
{113}{}{Das hat mir niemand gesagt.}
{114}{}{Sie bezahlen mich, um sie loszuwerden, und die Arbeit ist erledigt.}
{115}{}{Du Idiot! Warum machst du sowas, verdammt noch mal.}
{116}{}{Ich brauche das Geld.}
{117}{}{Die werden kommen und uns holen, wenn du das machst.}
{118}{}{Nicht mein Problem.}
{119}{}{Hoffentlich erstickst du dran. Die werden schon sehr bald hier auftauchen und uns
 abschleppen.}
{120}{}{Ich wusste nicht, dass die mir deshalb den Auftrag gegeben haben.}
{121}{}{Mag schon sein. Aber ich lass mir von Gesocks wie dir trotzdem nichts sagen.}
{122}{}{Wir können das nicht zulassen.}
{123}{}{Tu, was du nicht lassen kannst.}
{124}{}{Du hast denen das einfach so geglaubt? Da musst du aber noch einiges über das Leben
 lernen, mein Freund.}
{125}{}{Kann ich euch denn irgendwie helfen?}
{126}{}{Die Jungs aus Vault City sind ziemliche Feiglinge. Wenn du denen ein bisschen Angst
 einjagst, rennen die wie die Karnickel. Mit ein paar Waffen könnten wir sie uns bestimmt
 vom Leib halten.}
{127}{}{Welche Art von Waffen?}
{128}{}{Nun, ich kann gut mit einer Schrotflinte umgehen, und wir haben hier drinnen einige Leute,
 die mit einem Gewehr umgehen können. Ich denke, drei davon müssten reichen.}
{129}{}{Ich werd sehen, was ich tun kann.}
{130}{}{Du bist hier unerwünscht. Los verschwinde.}
{131}{}{Ich hab's mir anders überlegt. Wie kann ich euch helfen?}
{132}{}{Hör zu, die wirst hier trotzdem gleich verschwinden.}
{133}{}{Du kannst mich mal.}
{134}{}{Da bist du ja wieder! Hast du die Gewehre mitgebracht?}
{135}{}{Was sollte ich noch mal mitbringen?}
{136}{}{Ja. Hier sind sie.}
{137}{}{Wir brauchen drei Sturmgewehre und eine Schrotflinte. Je schneller du sie uns bringst, desto
 besser.}
{138}{}{OK.}
{139}{}{Mit denen werden wir in der Lage sein, im Lauf der nächsten Monate was aus diesem Ort zu machen.
 Herzlichen Dank, und he, falls du mal einen Platz zum ausruhen brauchst, Freunde sind bei uns immer willkommen.}
{140}{}{Gern geschehen.}
{141}{}{Willkommen, da bist du ja wieder. Bei uns läuft's gut. Wir erweitern gerade das Dorf.}
{142}{}{Hallo, da bist du ja wieder! Hier bei uns ist es gut vorangegangen, wie du siehst. Schau
 dich mal um, wenn du 'n bisschen Zeit hast.}
{143}{}{Wir sind dauernd am Bauen. Wir hoffen, dass wir bis nächsten Monat das Dorf wieder ein
 Stück erweitert haben.}
{144}{}{Willkommen! Das Dorf ist noch ein Stück gewachsen, genau, wie wir gehofft hatten. Wie
 immer bist du hier willkommen.}
{145}{}{Jetzt haben wir von Vault City nichts mehr zu befürchten — sieht so aus, als ob wir hier endlich in
 Frieden leben können. Nochmals vielen Dank, Reisender.}
{146}{}{Hör einfach auf, da draußen irgendwas zu töten, du Einfaltspinsel.}
