{100}{}{Du siehst einen Dorfbewohner.}
{101}{}{Du siehst einen Dorfbewohner.}
{102}{}{Hallo.}
{103}{}{Auf Wiedersehen.}
{104}{}{Willkommen in unserem Dorf.}
{105}{}{Die Monster beschützen uns.}
{106}{}{Komm schnell wieder.}
{107}{}{Wir brauchen die Gewehre dringend.}
{108}{}{Hallo.}
{109}{}{Geh jetzt!}
{110}{}{Verschwinde dahin, wo du hergekommen bist!}
{111}{}{Mach, dass du schleunigst hier wegkommst!}
{112}{}{Jetzt sind wir sicher.}
{113}{}{Danke.}
{114}{}{Gott segne dich, Reisender.}
