{100}{}{Du siehst einen kleinen, fröhlichen Mann.}
{101}{}{Du siehst Happy Harry, den Ladeninhaber.}
{102}{}{Hallo, guten Tag... was kann ich für dich tun?}
{103}{}{Ich suche günstige Waren. Kann mal sehen, was du auf Lager hast?}
{104}{}{Ist der Pflug da draußen immer noch zu haben?}
{105}{}{Ik gauf}
{106}{}{Heute nichts, danke.}
{107}{}{Tut mir leid, da kann ich dir nicht helfen, Freund.}
{108}{}{Aber ja, natürlich! Der kostet, sagen wir... achthundert.}
{109}{}{Ich gebe dir sechshundert dafür.}
{110}{}{Einverstanden. Ich nehm ihn.}
{111}{}{Hmmm, achthundert? Bin gleich wieder da. Ich hole nur das Geld.}
{112}{}{Vergiss es. Sollen die Smiths doch verhungern.}
{113}{}{Er gehört dir. [Steckt das Geld ein.] Nimmst du ihn gleich mit, oder soll er
 irgendwohin geliefert werden?}
{114}{}{Liefer den doch bitte bei den Smiths ab.}
{115}{}{Tut mir leid, aber dafür musst du schon achthundert hinblättern.}
{119}{}{Hast du das Geld dabei, Freundchen?}
{120}{}{Ich gehe das Geld holen.}
{121}{}{Kein Problem. Ich möchte, dass er sofort geliefert wird.}
{122}{}{Hast wohl gedacht, du könntest dich hier selbst bedienen, was? Verdammter Dieb... Wachen! Wachen!}
