{100}{}{Du siehst einen alten Mann mit leicht irrem Blick.}
{101}{}{Du siehst Old Joe, den lokalen idiotischen Gelehrten.}
{102}{}{Hallo. Hab dich schon lang nicht mehr gesehen.}
{103}{}{Kenn ich dich?}
{104}{}{Ach ja, das ist aber schon eine ganze Weile her. Wie ist es dir ergangen?}
{105}{}{Ja, das ist schon lange her. Was hast du so getrieben?}
{106}{}{Dieses und jenes. Woher kennst du mich?}
{107}{}{Hör mal, Alter. Ich hab nicht die geringste Ahnung, wer du bist.}
{108}{}{Jaja. Bin viel herumgekommen. Zum Schluss bin ich hier an diesem gottverlassenen Ort
 gelandet. Ist eben alles nicht mehr so wie früher. Nee, wirklich...}
{109}{}{Ja die guten alten Zeiten. Ich erinnere mich noch, als wir mal...}
{110}{}{Ist jedenfalls alles nicht mehr das, was es mal war. Also, was haben wir denn zusammen
 gemacht?}
{111}{}{Du erinnerst dich nicht an mich, was? Naja, du siehst auch noch 'n bisschen zu jung aus.}
{112}{}{Was versuchst du mir eigentlich die ganze Zeit zu sagen?}
{113}{}{Aber du kommst mir trotzdem irgendwie bekannt vor. Naja, muss an meinen alten Augen
 liegen. Na, jedenfalls schönen Tag noch.}
{114}{}{Äh, ja. Wiedersehn.}
{115}{}{Klar, wir haben dem Meister schön eingeheizt, stimmt's? Trotzdem brach alles auseinander,
 nachdem du weg warst. Musste abhauen und meinen Namen ändern. Wo bist du schließlich gelandet?}
{116}{}{Ich hab in einem kleinen Dorf gelebt.}
{117}{}{Hör, mal, sei hier lieber vorsichtig. Es ist alles nicht mehr so einfach, wie's mal war.
 Halt dir den Rücken frei.}
{118}{}{Okay, danke.}
{119}{}{Ja, ich hab 'ne Zeit lang nach deiner Vault gesucht, ihn aber nie gefunden. Hast du denn
 ein paar gute Nachrichten für deinen alten Freund Ian?}
{120}{}{Ian?}
{121}{}{Ja, Ian. Kennst du mich nicht mehr? Ist schon 'n paar Jährchen her. Aber normalerweise
 vergisst man doch seinen besten Kumpel nicht. Naja, bis auf die Sache mit dem Schuss in den
 Rücken. Du, ich sag's noch mal: Tut mir wirklich leid.}
{122}{}{Tut mir leid, aber du hältst mich wohl für den Vaultbewohner. Mein Dorf wurde
 von ihm gegründet.}
{123}{}{Ja, das macht schon etwas mehr Sinn. Gut zu hören, dass mein Freund Erfolg gehabt hat. Hör
 zu, der alte Ian gibt dir jetzt einen Rat. Gib acht dort draußen. Das ist hier nicht so
 idyllisch, wie's aussieht. }
{124}{}{Was läuft hier?}
{125}{}{Die Vaultbürger halten viel auf ihre Abstammung und kümmern sich nicht wirklich um Leute
 wie dich oder mich. Hier. Nimm diese Knarre. Die schützt dich, wenn es mal drunter und
 drüber geht. Besser, man sieht dich nicht mit mir verrücktem altem Mann reden. Am besten machst
 du dich jetzt davon.}
{126}{}{Danke für die Hilfe.}
{127}{}{Lass mich alten Mann in Frieden.}
{128}{}{So vertraut...}
{129}{}{Lass mich jetzt in Ruhe.}
{130}{}{Besser du gehst jetzt.}
{131}{}{Die werden misstrauisch, wenn wir weiter reden.}
{132}{}{Na los. Wird's bald! Und enttäusche mich nicht.}
