name: build

on:
  push:
  pull_request:

env:
  sfall_version: 4.5.1
  mpack_version: 4.5.1

jobs:
  build:
    if: github.actor != 'bgforge-hive' && github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0

      - name: Fallout tests
        uses: BGforgeNet/fallout-tests@67a424fd4fc46cf1dd1eea24dad8a4f211d4c6bb # main
        with:
          scripts_h: scripts_src/headers/scripts.h
          scripts_lst: data/scripts/scripts.lst
          scripts_dir: scripts_src
          dialog_dir: data/text/english/dialog

      - name: Install packages
        run: |
          sudo DEBIAN_FRONTEND=noninteractive eatmydata apt-get install -o=Dpkg::Use-Pty=0 -y crudini dos2unix gcc p7zip

      - name: Build and package
        run: ./extra/full.sh

      - name: Upload artifacts - exe
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: upu.exe
          path: upu*.exe

      - name: Upload artifacts - translations zip
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: upu_translations.zip
          path: upu*_translations.zip

      # so that main glob doesn't catch it
      - name: Remove translations zip
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: rm -f upu*_translations.zip

      - name: Upload artifacts - main zip
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: upu.zip
          path: upu*.zip

      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            upu*.exe
            upu*.zip
            torrents/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create torrents
      - name: Release torrents
        if: startsWith(github.ref, 'refs/tags/')
        uses: devopsx/action-torrent@18d1dfef495e73cb94093731e9e5c845653fbc11 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          local: false
