call ..\p ANIMFRVR
call ..\p DOORL100
call ..\p ZCBRAHMN
call ..\p ZCCRPDEL
call ..\p ZCGECKO
call ..\p ZCLDTHCL
call ..\p ZCLGECKO
call ..\p ZCLMANTI
call ..\p ZCLRAT
call ..\p ZCLSCORP
call ..\p ZCSLAVE
call ..\p ZI8BALL
call ..\p ZIBLKJCK
call ..\p ZIBRAPOO
call ..\p ZICLOSED
call ..\p ZICRTRNK
call ..\p ZIDCEGRL
call ..\p ZIGENGRV
call ..\p ZIHARDLK
call ..\p ZILCKDOR
call ..\p ZILOCKER
call ..\p ZIMEDMLK
call ..\p ZIMTLDOR
call ..\p ZINUKE
call ..\p ZISLOTS
call ..\p ZISUNSPT
call ..\p ZITMPBOX
call ..\p ZIWEAKLK
call ..\p ZIWODDOR
call ..\p ZSDRVCAR
call ..\p ZSELEV01
call ..\p ZSELEV02
call ..\p ZSWSIGN
